### ISSUE TITLE
spack version not incremented in releases after 0.8.15

### ISSUE THREAD

**Issue by JohnWestlund** [LLNL/spack#1007]
The **init.**.py still have the old version.

**Comment by tgamblin** [comment]
the tagged commits on `master` seem right and I just updated `develop` to `0.9.1` (it was stuck at `0.9`) -- where is it wrong?

**Comment by tgamblin** [comment]
@JohnWestlund

**Comment by JohnWestlund** [comment]
@tgamblin You're good on Master/devel -- but the releases for 0.8.16 and 0.8.17 didn't increment the version string

**Comment by adamjstewart** [comment]
Should this be closed? I don't think we're going to go back and fix old releases are we?
