### ISSUE TITLE
`spack load` doesn't load right module when refined by dependency

### ISSUE THREAD

**Issue by tgamblin** [LLNL/spack#101]
Issue reported by @albertdefusco et al.:

    $ spack load metis		
    ==> Error: Multiple matches for spec metis.  Choose one:
    metis@5.1.0%intel@15.0.3=haswell
         ^openmpi@1.8.6%intel@15.0.3=haswell
    metis@5.1.0%intel@15.0.3=haswell
         ^mvapich2@2.1%intel@15.0.3=haswell
    $ spack load metis ^openmpi
    ==> Error: Multiple matches for spec metis^openmpi.  Choose one:
    metis@5.1.0%intel@15.0.3=haswell
         ^openmpi@1.8.6%intel@15.0.3=haswell
    metis@5.1.0%intel@15.0.3=haswell
         ^mvapich2@2.1%intel@15.0.3=haswell

The second of these should definitely work and load the `openmpi` version.

This is on [this `dev` branch](https://github.com/AlbertDeFusco/spack/tree/dev).

**Comment by alalazo** [comment]
I think this is solved now : 
```
$ spack find -vd parmetis
==> 2 installed packages.
-- linux-Ubuntu14-x86_64 / gcc@4.8 ------------------------------
    parmetis@4.0.3~debug~gdb+shared
        ^metis@5.1.0~debug~gdb~idx64~real64+shared
        ^mpich@3.2+hydra+pmi~verbs

    parmetis@4.0.3~debug~gdb+shared
        ^metis@5.1.0~debug~gdb~idx64~real64+shared
        ^openmpi@2.0.0~mxm~pmi~psm~psm2~slurm~sqlite3~thread_multiple~tm~verbs+vt
            ^hwloc@1.11.3
                ^libpciaccess@0.13.4
                    ^libtool@2.4.6

$ spack load parmetis 
==> Error: the constraint 'None' matches multiple packages, and this is not allowed in this context
parmetis@4.0.3%gcc@4.8~debug~gdb+shared arch=linux-Ubuntu14-x86_64
parmetis@4.0.3%gcc@4.8~debug~gdb+shared arch=linux-Ubuntu14-x86_64

$ spack load parmetis^openmpi

$ module list

Currently Loaded Modules:
  1) parmetis-4.0.3-gcc-4.8-i25qjy7
```

**Comment by adamjstewart** [comment]
Can this be closed?
