### ISSUE TITLE
Download progress bar bugs

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#1017]
I've noticed a weird bug with my progress bar lately. When fetching a package, it instantly jumps to 100% and pauses. The cursor jumps back and forth across the line, but it remains at 100%. Eventually (after it actually finishes downloading) it continues to install the package. Has any of the progress bar logic been changed? I also updated to Python 2.7.11 and cURL 7.47.1 recently, so that may be causing the problem.

Another longstanding problem is that if the terminal is fewer than 80 characters wide, the progress bar spits out thousands of lines of comment symbols instead of overwriting the original line. It can't be that hard to dynamically determine the width of the terminal, right? Is this functionality part of Spack or is it part of an external dependency?

**Comment by tgamblin** [comment]
Spack's using `curl`'s progress bar, which AFAIK is just a command line option on the way `curl` is invoked.  I have been thinking that it might be a good idea to just use `urrlib2` instead, as it would give us more control over things like this, and more consistency in how SSL and such are done when things are fetched.

Do you actually use a lot of terminals that are fewer than 80 characters wide?  I think a lot of things have issues with that.

**Comment by adamjstewart** [comment]
Not usually, but I have noticed it. It's not really that big of a problem, but I'm sure it's annoying for some people.

**Comment by adamjstewart** [comment]
I'm going to close this. It sounds like this is a bug with cURL, not Spack.
