### ISSUE TITLE
Cannot create a mirror for git spec

### ISSUE THREAD

**Issue by mwilliammyers** [LLNL/spack#1019]
First off: love this package manager, it is exactly what we had been looking for.

Secondly:
`spack mirror create git` produces the error:

```
==> Warning: Error while fetching git@2.8.1
  Cannot archive without matching extensions.
==> Successfully updated mirror in /mirror
  Archive stats:
    0    already present
    0    added
    1    failed to fetch.
==> Error: Failed downloads:
git@2.8.1
```
Which seems to be because it is expecting an extension on [this] (https://github.com/LLNL/spack/blob/76d42b520069e15aa7cf0fa8cbfb3d83c9be7052/lib/spack/spack/fetch_strategy.py#L310) line.

But the tarball it downloads is: `$SPACK_ROOT/var/spack/stage/git-2.8.1-mdglrz6t3slmg7xkhdsq7ia3opouudxw/v2.8.1`

I would be happy to create a PR to fix this...

**Comment by adamjstewart** [comment]
@mwilliammyers: Welcome to Spack, we're glad to have you!

Feel free to contribute a PR if you think you can fix it. If not, one of us should get around to it eventually. It seems like this bug should affect a lot of packages that use a Git URL.

**Comment by mwilliammyers** [comment]
So I got a chance to look into this more and I am not convinced that we need to be checking to see if the extensions match seeing as they will be check-summed... If we, do the best solution I could come up with would involve calling the [`downloaded_file_extension`](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/url.py#L143) method on the `url` class to get the expected extension. This seems like an unnecessary check to me though. I just didn't want to take out the check in case is there is a good reason it is there seeing as this would affect a lot of URLs. As it stands right now I don't think any URL that uses GitHub's [archive scheme](https://developer.github.com/v3/repos/contents/#get-archive-link) will work.

**Comment by adamjstewart** [comment]
Hmm, the only reason I can think of that we would want to check the extension would be for #282. Not sure if that was ever fixed. Anyone else have any knowledge of `download_file_extension()`?
