### ISSUE TITLE
problem with shebang of Python scripts being too long

### ISSUE THREAD

**Issue by karenyyng** [LLNL/spack#104]
Some Python packages install python scripts to be executed via bash.
If we use the Python installed with `spack`, the path of the python is something like:
`#!/<SOME_DIR>/spack_git_repo/opt/spack/chaos_5_x86_64_ib/gcc-4.4.7/python-2.7.10-              yqkr6m74axh3nafjscgtjb3zj3htx3fe/bin/python`

Somehow the bash interpreter will cut it off when the shebang is longer than a certain number of characters as documented [here](http://www.in-ulm.de/~mascheck/various/shebang/#issues)

For me it cut off so the she-bang looked like:
``#!/<SOME_DIR>/spack_git_repo/opt/spack/chaos_5_x86_64_ib/gcc-4.4.7/python-2.7.10-              yqkr6m74axh3nafjscgtjb3zj3htx3fe/bin/p`

A simple fix is to change the line of shebang to:
`#!/bin/env python` 

Is there a better solution than manually changing all the shebangs for the python scripts?
In any case, I thought it may be nice to document this behavior somewhere in the `spack` documentation for Python use.
Thanks.

**Comment by tgamblin** [comment]
Duplicates #54
