### ISSUE TITLE
The hash changes when indirect dependency is modified

### ISSUE THREAD

**Issue by glennpj** [LLNL/spack#1055]
I ran into situations when spack was unexpectedly reinstalling packages. It turns out to be due to generating different hashes depending on whether an indirect dependency is listed explicitly or not. Consider the following spec for R (I picked a version I did not have installed):
```
Concretized
------------------------------
  R@3.2.2%gcc@6.1.0~external-lapack arch=linux-x86_64
      ^bzip2@1.0.6%gcc@6.1.0 arch=linux-x86_64
      ^cairo@1.14.0%gcc@6.1.0 arch=linux-x86_64
          ^fontconfig@2.11.1%gcc@6.1.0 arch=linux-x86_64
              ^freetype@2.5.3%gcc@6.1.0 arch=linux-x86_64
                  ^libpng@1.6.16%gcc@6.1.0 arch=linux-x86_64
                      ^zlib@1.2.8%gcc@6.1.0 arch=linux-x86_64
              ^libxml2@2.9.2%gcc@6.1.0~python arch=linux-x86_64
                  ^xz@5.2.2%gcc@6.1.0 arch=linux-x86_64
          ^glib@2.42.1%gcc@6.1.0 arch=linux-x86_64
              ^libffi@3.2.1%gcc@6.1.0 arch=linux-x86_64
              ^pkg-config@0.28%gcc@6.1.0 arch=linux-x86_64
          ^pixman@0.32.6%gcc@6.1.0 arch=linux-x86_64
      ^curl@7.47.1%gcc@6.1.0 arch=linux-x86_64
          ^openssl@1.0.2h%gcc@6.1.0 arch=linux-x86_64
      ^icu@54.1%gcc@6.1.0 arch=linux-x86_64
      ^jdk@8u66-linux-x64%gcc@6.1.0 arch=linux-x86_64
      ^jpeg@9b%gcc@6.1.0 arch=linux-x86_64
      ^libtiff@4.0.3%gcc@6.1.0 arch=linux-x86_64
      ^ncurses@6.0%gcc@6.1.0 arch=linux-x86_64
      ^pango@1.36.8%gcc@6.1.0 arch=linux-x86_64
          ^harfbuzz@0.9.37%gcc@6.1.0 arch=linux-x86_64
      ^pcre@8.38%gcc@6.1.0+utf arch=linux-x86_64
      ^readline@6.3%gcc@6.1.0 arch=linux-x86_64
      ^tcl@8.6.5%gcc@6.1.0 arch=linux-x86_64
      ^tk@8.6.3%gcc@6.1.0 arch=linux-x86_64
```
The R package.py file has `depends_on('zlib')` explicitly although it is an indirect dependency pulled in elsewhere. I suppose there is a question about whether all dependencies should be explicit or not but the fact is that indirect dependencies are not always listed explicitly. So, as a test, comment out the `depends_on('zlib')` entry and recalculate the DAG. As expected, the DAG is exactly the same whether the indirect dependency is listed explicitly or not. However, a different hash is generated when the indirect dependency is explicit versus not. This causes another install to be generated for the package.

That seems like a bug in that the same DAG should always yield the same hash. After all, the package gets installed with the same set of dependencies whether indirect dependencies are listed or not.

**Comment by alalazo** [comment]
@glennpj The DAG is not the same : it misses the edge connecting node `R` to node `zlib`, or am I missing something?

**Comment by glennpj** [comment]
Maybe I am using the wrong terminology. I saved the concretization output for the package when zlib was explicitly listed and when it was not. They were identical to each other and what I posted earlier. In sum, the package dependency list is exactly the same but the hash is different. The end result is that two packages get installed where the only difference between them is the hash.

**Comment by glennpj** [comment]
Another thing that I noticed that may or may not be related to this.
`spack info gcc`
```
Dependencies:
    gmp  isl  mpc  binutils  mpfr
```
and `spack info mpc`
```
Dependencies:
    gmp  mpfr
```

Looking at the spec for gcc,
```
Concretized
------------------------------
  gcc@6.1.0%gcc@6.1.0+binutils+gold arch=linux-x86_64
      ^binutils@2.26%gcc@6.1.0+gold~krellpatch~libiberty arch=linux-x86_64
          ^bison@3.0.4%gcc@6.1.0 arch=linux-x86_64
              ^m4@1.4.17%gcc@6.1.0+sigsegv arch=linux-x86_64
                  ^libsigsegv@2.10%gcc@6.1.0 arch=linux-x86_64
          ^flex@2.6.0%gcc@6.1.0 arch=linux-x86_64
      ^gmp@6.1.0%gcc@6.1.0 arch=linux-x86_64
      ^isl@0.14%gcc@6.1.0 arch=linux-x86_64
      ^mpc@1.0.3%gcc@6.1.0 arch=linux-x86_64
          ^mpfr@3.1.4%gcc@6.1.0 arch=linux-x86_64
```

Since `gmp` and `mpfr` are both dependencies of `mpc` and `gcc` why is `gmp` not listed as a dependency of `mpc` as `mpfr` is?

**Comment by alalazo** [comment]
I would have suggested:
```
$ spack graph gcc+binutils
o  gcc
|\
o |  mpfr
|/
o  gmp
o  m4
```
but it seems the command has problems on its own (`binutils` is not mentioned at all). I believe the hash behavior is correct (but would like to hear @tgamblin on that) and that the code for both : 
```
spack spec ...
spack graph ...
```
needs to be reviewed.

**Comment by adamjstewart** [comment]
@glennpj take a look at #1409. That might solve this problem.

**Comment by becker33** [comment]
I believe that this issue is correct behavior. You remove an edge from the DAG, the hash should change. The output of concretize will not necessarily change, since each dependency is listed once, but the install behavior does change. With `depends_on('zlib)` in the R package.py file, zlib is rpath'd into R. Without, it is only an indirect dependency and is indirectly rpath'd through cairo and several other steps. That's reason enough for the hash to differ.

@glennpj does that make sense to you?

**Comment by glennpj** [comment]
It does make sense, but is undesirable at a high level, mostly because it is not reflected in the output of `spack spec`. I think that the generated spec should reflect these hash differences so it is clear that there is a difference. I think the other point that I raised is also relevant. That is, when should dependencies be specified explicitly? The answer is, it depends on the package, but this seems like a hurdle for package authors.

**Comment by tgamblin** [comment]
@alalazo Maybe concretization should be done by default with `spack graph`?  See below.

```
$ spack graph --concretize gcc+binutils
o  gcc
|\
| |\
| | |\
| | | |\
| o | | |  mpc
|/| | | | 
| | |/ /
| |/| | 
o | | |  mpfr
|/ / /
| o |  isl
|/ /
o |  gmp
| o  binutils
|/| 
| |\
| o |  flex
|/| | 
| |/
| o  bison
|/
o  m4
o  libsigsegv
```

**Comment by tgamblin** [comment]
@adamjstewart: I don't think this one is actually #1409, but FWIW that's getting fixed soon.

**Comment by tgamblin** [comment]
@glennpj: how would you like `spack spec` to display the spec output?  Right now it does a depth-first traversal of the DAG and displays it like a tree.  You can control how it decides to descend into a subtree [see `Spec.traverse()`](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/spec.py#L767) -- whether it should display unique nodes (only visit each node once), unique edges (only traverse each edge once or all paths (can get really bushy).  None of them is really ideal.

Spack graph is the other option, but it has its own issues, mainly that it can get very *long*.  You can use `spack graph --dot` to get a dot file for `graphviz`, which can be better but is kind of cumbersome.  The tree seemed like a nice compromise, but you're right it's not the full mental model of the DAG.

If someone wants to design a compact and preferably wider ASCII graph visualizer than `spack graph`'s current `git`-like style, I'd be all for that.

**Comment by glennpj** [comment]
@alalazo: I am not sure how it should be displayed or if it is really worth any effort to change things. It seems like there is not really an issue here other than how to convey information. In the end, what I really want is for spack not to rebuild packages when it seems unnecessary (to me) so this probably gets solved when that gets addressed in other issues.

If everyone agrees that spack is actually behaving properly here then we can close this issue.

Thanks.

**Comment by tgamblin** [comment]
Yes, the hash should change when the DAG changes, even if that's just an edge.

**Comment by becker33** [comment]
Closing the issue now, if anyone wants to take on creating a better output format for `spack spec` I'm sure people will appreciate it, but that's a separate discussion.
