### ISSUE TITLE
Set up environment variables for package directories

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1070]
For example, `module load boost` should set up an environment variable `SPACK_BOOST_DIR=...`, with the same value that is put into `CMAKE_PREFIX_PATH`.

**Comment by mathstuf** [comment]
What uses `SPACK_BOOST_DIR`? What precedence is there for it?

**Comment by alalazo** [comment]
@eschnett This is possible customizing your `modules.yaml`. See [here](https://spack.readthedocs.io/en/latest/tutorial_sc16_modules.html).
