### ISSUE TITLE
spack load broken

### ISSUE THREAD

**Issue by ashkan2200** [LLNL/spack#1074]
Hi,
I just updated to the latest develop and now `spack load` is not working anymore.
I installed gcc again and when I try loading I get this error

      ModuleCmd_Load.c(208):ERROR:105: Unable to locate a modulefile for 'gcc-6.1.0-gcc-4.2.1-w2fahnzqgqife5lbbmsbtxnv24umogh4'

Also `spack compiler find` is broken but that is mentioned in another bug report as well.

**Comment by ashkan2200** [comment]
I forgot to mention that this is on Mac OS X Yosemite. I installed environment-modules and gcc and tried loading gcc

**Comment by tgamblin** [comment]
duplicates #1075 -- closing and continuing discussion there.
