### ISSUE TITLE
build time increased recently

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#1086]
i have a feeling that build time increased dramatically in recent weeks. I just built `gettext` and it took
```
==> Successfully installed gettext
  Fetch: 34.79s.  Build: 1h 15m 25.01s.  Total: 1h 15m 59.80s.
```
I don't recall it taking that much time last time. Among ~20 packages I build the worst was trilinos (on the order of 1 hour).

I will try other packages and compare it to my stable branch and update the post.

**Comment by davydden** [comment]
it is seems the issues were on my side caused by antivirus.

**Comment by tgamblin** [comment]
My favorite kind of issue!

**Comment by davydden** [comment]
yeah, if only all issues were like this one :smile:
