### ISSUE TITLE
No Silent DB Upgrades!

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#1088]
I merged new stuff into my Spack and then ran it.  It silently upgraded my DB to a new version (presumably without backing up the old version).  The new Spack isn't working for me, but now I can't roll back.  Argh!

Spack needs to avoid silently upgrading the DB format.

**Comment by alalazo** [comment]
I know it's not the perfect solution, but as the DB consists of a bunch of records stored in a `yaml` file, you can easily regenerate it using : 
```
spack reindex
```
Most of the times this fixes issues related to DB.

**Comment by citibeth** [comment]
OK, good to know.  When Spack quits because the DB is the wrong version, it
should tell you in the error message that the DB can be regenerated.

**Comment by citibeth** [comment]
See #1097 , this should fix the problem.
