### ISSUE TITLE
spack create should automatically add dependencies for build system

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#1110]
If `spack create` detects the build system as cmake, it should add `depends_on('cmake')`. Same goes for SCons. It already adds `extends('python')` or `extends('R')`. Should we also add `depends_on('autotools')`?

**Comment by tgamblin** [comment]
yes for all but `autotools`.  A dependency on autotools should only be necessary if you need to *regenerate* the build system.

**Comment by adamjstewart** [comment]
Awesome. I'll work on this when I get the chance.

**Comment by adamjstewart** [comment]
Closed by #1112
