### ISSUE TITLE
spack long-shebang handling breaks lua scripts

### ISSUE THREAD

**Issue by trws** [LLNL/spack#1123]
Since `#` is not a comment character in lua, adding the second line after a shebang causes breakage.

It's... unfortunate, but this may have to be handled with per-language modeline behavior of some kind to work right for languages that don't use `#` as their comment character.

**Comment by tgamblin** [comment]
Pull latest develop.  Fixed last week.

**Comment by trws** [comment]
😖  👍  thanks @tgamblin, sorry for the noise.

**Comment by tgamblin** [comment]
No worries.  See #1101 and #1102.

**Comment by tgamblin** [comment]
@trws: what other languages allow shebang but don't use # as the comment character?

**Comment by trws** [comment]
As far as I can think of:

* Lisp
* Haskell
* JavaScript (think node.js)
* VimScript (technically, this will probably never come up)

**Comment by tgamblin** [comment]
@trws: it would be nice to handle the first three, although adding vim script wouldn't kill us.  Can you look at the code added at [`sbang.py:62`](/LLNL/spack/blob/develop/lib/spack/spack/hooks/sbang.py#L62) and see if there is a decent way to handle those gracefully?  We could go by suffix or interpreter name.

Seems like we would just need to add support for `//!`, `;!`, and `"!` (really?) in [`sbang`](https://github.com/LLNL/spack/blob/develop/bin/sbang) itself.
