### ISSUE TITLE
Mumps is broken by PR 1023

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#1132]
Mumps is broken on OSX with clang+gfortran by https://github.com/LLNL/spack/pull/1023. It manifests in a segmentation fault when trying to use Trilinos + MUMPS direct solver as a [unit test during installation of  deal.ii@8.4.1](https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/dealii/package.py#L279) which worked before. 

To confirm it I took a [pre-PR version of MUMPS](https://github.com/LLNL/spack/blob/ddaba07d8297544f2587f0c31fcbd2dafa824eb3/var/spack/repos/builtin/packages/mumps/package.py), build it with current develop and my [usual patch](https://github.com/dealii/dealii/wiki/deal.II-in-Spack#mixing-gcc-and-clang-on-osx) to mix clang and fortran and it works good and does not produce a segmentation fault!

Most likely it is [related to this](https://github.com/LLNL/spack/commit/9b299cb2bbe6e1e20df38c1900d6a05483c81a3f#diff-2b1c47a5b3acd753325522d1c1c65956L137), but could also be related to the big shared patch introduced in https://github.com/LLNL/spack/pull/1023.
Alternatively, it could be related to the way [MUMPS is used in Trilinos](https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/trilinos/package.py#L221).

@nrichart would you mind having a second look at your PR and see what could cause the issue?

**Comment by nrichart** [comment]
I do not have access to an OSX machine yet but I will try to see if I can already reproduce this on linux or if it might be linked on the specific lines for darwin.
Is it possible to reproduce the bug with a simple case that does not depend on Trilinos and deal.ii ?

**Comment by davydden** [comment]
i will test tomorrow with a clean install on linux, but i am afraid it is related to either (i) darwin or (ii) clang. As for a stand alone test, perhaps some small example program which use only Mumps would do. Unfortunately the current small test programs run ok, it seems.

**Comment by davydden** [comment]
Looking at [mumps in homebrew](https://github.com/Homebrew/homebrew-science/blob/master/mumps.rb), there must be `c_example.c` file, which could show the issue. Will try tomorrow...

**Comment by nrichart** [comment]
If it is clang I might be able to reproduce it, I'm spack installing a clang right know.
You installed deal.ii@8.4.1 with everything default or with some specific variants ? so I install the same

**Comment by davydden** [comment]
`dealii@8.4.1` (default) should show the issue.

**Comment by davydden** [comment]
@nrichart i checked my installation logs on Linux, it builds fine with gcc. It must be related to this line you changed https://github.com/LLNL/spack/commit/9b299cb2bbe6e1e20df38c1900d6a05483c81a3f#diff-2b1c47a5b3acd753325522d1c1c65956L140 which is related to reworking the makefile.

**Comment by nrichart** [comment]
Today I couldn't work on it I will try to find a mac osx tomorrow to try to compile.

**Comment by davydden** [comment]
@nrichart this PR https://github.com/LLNL/spack/pull/1145 shows the segmentation fault in PETSc example, which is way faster to compiler compared to Trilinos.
