### ISSUE TITLE
Documentation for: Features/cache archives #579

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#1139]
Great news that the download cache has been merged.  However... I can't find documentation for it!  Key questions need to be addressed include:

1. How do you turn this feature on/off?
1. Where is the cache located?
1. What do tarballs look like in the cache?
1. Anything else regarding special cases, etc?

Hopefully this shouldn't be much.  @scheibelp can you please add docs to the Spack user manual and submit in a new PR?  That will ensure that people are able to make use of all the work that went into this feature.  Thanks!

**Comment by scheibelp** [comment]
I'm trying to figure out which details should go in. This is an always-on feature (and should never give the wrong answer). The location could be given to users but in a sense given that caching is not configurable it could arguably be part of the internal workings of Spack. Given that it could still be useful to say "Spack caches downloads for you when it can". To answer questions specifically (which may be useful for a discussion)

2. var/spack/cache
3. tarball filename is <package>-<version>.tar.gz
4. Only resources determined to be unique are cached (either they have an associated digest or a commit id)

It has occurred to me thinking on this that if a URL resource was at one time identifiable with a digest, and then the digest was removed from package.py without changing the version, and the resource was altered (i.e. by the maintainer), that this would mistakenly use the old resource from the cache. I'll actually raise that as an issue in the next hour.

**Comment by tgamblin** [comment]
I think you could update the parts on directory structure and fetching to talk about the first two.  For (3) you can just say that the cache is a mirror and refer users to the mirror documentation to understand how it looks in the cache.  And you can just say that you cache one thing per version, and not per DAG configuration like the installs.

**Comment by citibeth** [comment]
On Wed, Jun 29, 2016 at 1:05 PM, scheibelp <notifications@github.com> wrote:

> I'm trying to figure out which details should go in. This is an always-on
> feature (and should never give the wrong answer).
>
Always on is nice, since it will improve our lives just with a "git pull."
 We do need to know how to edit / blow away the cache if needed.  Probably
nothing more than a description in the docs of where it is, and explaining
it's OK to use "rm".


> The location could be given to users but in a sense given that caching is
> not configurable it could arguably be part of the internal workings of
> Spack.
>

Docs should tell the default location --- and if it's configurable, how to
configure it.


>
>
> It has occurred to me thinking on this that if a URL resource was at one
> time identifiable with a digest, and then the digest was removed from
> package.py without changing the version, and the resource was altered (i.e.
> by the maintainer), that this would mistakenly use the old resource from
> the cache. I'll actually raise that as an issue in the next hour.
>
This possibility sounds pretty remote.  Digests should not be removed from
package.py.  But if they are... I mentioned in another thread that Spack
should have a "verified" mode, in which it ensures all tarballs/git
downloads/whatnot are properly verified.  If Spack is running in verified
mode, then it would refuse to install a package version without a digest,
and this corner case would never be a problem.

**Comment by tgamblin** [comment]
@scheibelp: I mentioned it in another PR but not here -- there should be mention of `spack purge --cache`  and `spack purge --all` I added to do what @citibeth is asking about.

**Comment by citibeth** [comment]
Are these `spack purge` commands already implemented?  I'm trying to
contain this issue to be documentation-only.

**Comment by tgamblin** [comment]
yes.

**Comment by scheibelp** [comment]
In the process of updating docs - PR should be linked today.

**Comment by scheibelp** [comment]
@tgamblin #1146 has been merged so this issue can be closed

Let me know if there is a better way to mention that (AFAIK I cannot close these issues myself)

**Comment by adamjstewart** [comment]
@scheibelp This should do the trick for future reference: https://help.github.com/articles/closing-issues-via-commit-messages/
