### ISSUE TITLE
Documentation: Missing examples in licensed software

### ISSUE THREAD

**Issue by mamelara** [LLNL/spack#1140]
The licensed software documentation looks a bit incomplete. Some places look like they are missing images to show examples of how the global license file looks like and also another for how to use a license from another server.

Also, I think it might be helpful to add an example about a package that has multiple licenses. For example, a user at NERSC was trying to install allinea-forge and had two licenses, license.ddt and license.map. They thought that when Spack prompted them to use the global file that there would be two global files for each specified license. So it might be helpful to mention that all licenses should be placed in the global file, or something like that.

**Comment by adamjstewart** [comment]
@mamelara I was the one who wrote the documentation on licensed software and who added the allinea packages. Looks like you're right, there are a couple of code blocks I added that aren't showing up. I don't actually know reStructuredText very well, so if someone can help me out I'd be glad to fix it. Is there a quick and easy way to view a .rst file locally?

Allinea is a bit complicated. Forge includes MAP and DDT. We have a single license for Forge, so I wasn't aware that you could have licenses for the individual components. They may have merged them recently? If not, we could also add separate packages for allinea-map and allinea-ddt.

**Comment by tgamblin** [comment]
@adamjstewart: if you just type `make` in the docs directory, and you have sphinx with py-pygments, it should build fine.

**Comment by adamjstewart** [comment]
@tgamblin Did you update the docs hosted online? My change didn't seem to work.

**Comment by tgamblin** [comment]
Erm... yes... I did... and I totally didn't just do it now.

**Comment by mamelara** [comment]
@adamjstewart So will allinea-forge require two packages then? Or could we do a resource() of allinea ddt and allinea map under one allinea-forge package? Sorry to derail the thread since this is about the documentation.

**Comment by adamjstewart** [comment]
@tgamblin Oh yay, it worked!

@mamelara Allinea Forge can be downloaded as a single tarball, so it should be fine as a single package. If Allinea MAP and Allinea DDT can still be downloaded individually, then they could very well have their own packages as well. Either way, if putting both licenses in the same file works, it works. I'm not sure if it's worth changing the current documentation to describe the edge case in which multiple licenses need to go in one file.

**Comment by mamelara** [comment]
@adamjstewart fair enough. Thanks for updating the docs!

**Comment by adamjstewart** [comment]
No prob, thanks for pointing out that they were broken!
