### ISSUE TITLE
Unify convention to mark external packages provided by the system

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#1150]
#721 assumes external packages pointing to system libraries to be using the `@system` version, the `openssl` package instead assumes `@external`. I think we should set for one of the two name (I don't mind which) and correct the other.

**Comment by citibeth** [comment]
I agree.  Any votes on which name to use?  If there are no preferences, I nominate that @alalazo do whatever he thinks is best.

**Comment by tgamblin** [comment]
I'm tempted to go with `system`, as there's already a concept of "external" packages but they're not necessarily "system" packages.  `system` as you're using it is just a placeholder that means you don't care about versioning for that particular package, and you expect the system to upgrade it in place. "external" packages can also be outside spack as part of the "system", but you can also be specific about their versions, compilers, etc.

**Comment by alalazo** [comment]
@tgamblin @citibeth just FYI, in #1135 the reference to `@system` added in #761 has been removed : it seemed to me it was there just to skip external packages because they don't have (currently) any module file generated. I changed the logic in #1135 so that we actually test for the existence of the module file, as this also accounts for blacklisted module files or will account for modules generated for `@system` packages in case.

This : 

> system as you're using it is just a placeholder that means you don't care about versioning for that particular package, and you expect the system to upgrade it in place.

anyhow convinced me that `system` is a better tag than `external` and so #1163 ...
