### ISSUE TITLE
`py-h5py` should not depend on `hdf5~mpi`

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1152]
`py-h5py` wraps the HDF5 library. It contains these lines:
```Python
    depends_on('hdf5@1.8.4:+mpi', when='+mpi')
    depends_on('hdf5@1.8.4:~mpi', when='~mpi')
    depends_on('mpi', when='+mpi')
```

The first two of these should probably read instead
```Python
    depends_on('hdf5@1.8.4:')
    depends_on('hdf5+mpi', when='+mpi')
```
This would allow using a plain `h5py` (which is `h5py~mpi`) with a `hdf5+mpi`. I don't think there is a reason to disallow this.

**Comment by tgamblin** [comment]
I'm ok with this change.  Want to submit a PR?

@adamjstewart?

**Comment by adamjstewart** [comment]
Sounds fine to me!
