### ISSUE TITLE
Archiving broke git build

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1160]
I receive the error message
```
==> Trying to fetch from https://github.com/git/git/tarball/v2.8.1
ValueError: Cannot archive without matching extensions
```
while installing git. The build then aborts.

@tgamblin suggested that "This looks like an issue with tarball caching, which was recently merged.  Spack now keeps the tarballs you download in a local mirror so that if you build 5 variants of one thing you don't have to download 5 times."

Reverting to an earlier version of Spack -- before archiving was merged -- provided a work-around for me.

**Comment by tgamblin** [comment]
Fixed by #1128
