### ISSUE TITLE
Spack-installed tmux does not work any more

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1162]
I used to install `tmux` via Spack, and then run it via its path, e.g. as `/work/00507/eschnett/src/spack/opt/spack/linux-centos6-x86_64/gcc-6.1.0-spack/tmux-2.2-7mbznhvouy5l5gbqy7djtlczsz5ip3hg/bin/tmux`. Since recently this does not work any more; I then receive the error message

```
open terminal failed: can't find terminfo database
```

Since there was no recent change to the `tmux` package, I wonder whether Spack's handling of environment variables changed, and could be causing this problem?

**Comment by tgamblin** [comment]
I'm not sure if there were any recent environment changes that would cause this.  We now unset `CPATH` and `LIBRARY_PATH` in `build_environment`, but I think that is unrelated.  Do you know which version it actually worked in?

**Comment by alalazo** [comment]
Tried tmux at 1ece25bdc288136a0039a8dd2c5b9ddeb544797d and can't reproduce.
