### ISSUE TITLE
Suite Sparse Fails to build

### ISSUE THREAD

**Issue by lee218llnl** [LLNL/spack#1172]
My build fails with:

cc -L/nfs/tmp2/lee218/pkg/spack/opt/spack/linux-redhat6-x86_64/gcc-4.4.7/suite-sparse-4.5.1-4v7uz6oaksyjnpnqpirqzeedbwuoibmk/lib -shared -Wl,-soname -Wl,libspqr.so.2 -Wl,--no-undefined spqr_rmap.o SuiteSparseQR_C.o SuiteSparseQR_expert.o spqr_parallel.o spqr_kernel.o spqr_analyze.o spqr_assemble.o spqr_cpack.o spqr_csize.o spqr_fcsize.o spqr_debug.o spqr_front.o spqr_factorize.o spqr_freenum.o spqr_freesym.o spqr_freefac.o spqr_fsize.o spqr_maxcolnorm.o spqr_rconvert.o spqr_rcount.o spqr_rhpack.o spqr_rsolve.o spqr_stranspose1.o spqr_stranspose2.o spqr_hpinv.o spqr_1fixed.o spqr_1colamd.o SuiteSparseQR.o spqr_1factor.o spqr_cumsum.o spqr_shift.o spqr_happly.o spqr_panel.o spqr_happly_work.o SuiteSparseQR_qmult.o spqr_trapezoidal.o spqr_larftb.o spqr_append.o spqr_type.o spqr_tol.o -o /nfs/tmp2/lee218/pkg/spack/opt/spack/linux-redhat6-x86_64/gcc-4.4.7/suite-sparse-4.5.1-4v7uz6oaksyjnpnqpirqzeedbwuoibmk/lib/libspqr.so.2.0.5 -lm -lrt -Wl,-rpath=/nfs/tmp2/lee218/pkg/spack/opt/spack/linux-redhat6-x86_64/gcc-4.4.7/suite-sparse-4.5.1-4v7uz6oaksyjnpnqpirqzeedbwuoibmk/lib -lamd -lcolamd -lcholmod -lsuitesparseconfig -llapack -lopenblas
spqr_rmap.o:(.data.DW.ref.__gxx_personality_v0[DW.ref.__gxx_personality_v0]+0x0): undefined reference to `__gxx_personality_v0'

It looks to me like this either needs to link with CXX or bring in -lstdc++. I will look at fixing this.

**Comment by davydden** [comment]
in a private communication suite-sparse developers told that there could be a problem with linking in make files. In particular, linking was done with `$(CC)` instead of `$(CXX)`. That was the case for SPQR lib, but may also be present in other places.

There is now `4.5.3` and `4.6.0`. Could be that the issue is fixed there.

**Comment by lee218llnl** [comment]
Fixed in #1174
