### ISSUE TITLE
module refresh fails with: AttributeError: type object 'TclModule' has no attribute 'path'

### ISSUE THREAD

**Issue by paulhopkins** [LLNL/spack#1182]
Running module refresh fails with the error message: AttributeError: type object 'TclModule' has no attribute 'path'. This is due to a change in the file lib/spack/spack/cmd/module.py which replace the path attribute with the file name property.

**Comment by paulhopkins** [comment]
I have added a pull request that fixes this, though there may be more required: #1183

**Comment by alalazo** [comment]
I think this has been solved with #1135

**Comment by paulhopkins** [comment]
This has been fixed. Closing.
