### ISSUE TITLE
Python and bzip2

### ISSUE THREAD

**Issue by lee218llnl** [LLNL/spack#122]
Python is not building the bz2 module because it is trying to link to the bzip2 package's .a file which was not compiled -fpic. The bzip2 package does build a shared library, but only appears to generate versioned .so files/links, i.e., libbz2.so.1.0 and libbz2.so.1.0.6 and not the generic libbz2.so.

**Comment by tgamblin** [comment]
@lee218llnl: would adding the symlink fix this?  I could add this to the `bzip2` package post-`make('install')`.  If not, then we could build the `.a` with `-fpic` but I dunno what other packages that might affect (Mark Miller and I [kind of talked about this here](https://groups.google.com/forum/#!topic/spack/7brRuR0v6O4))

**Comment by lee218llnl** [comment]
Todd, I think adding a symlink will suffice. I will work on this.

**Comment by sjtbham** [comment]
@lee218llnl @tgamblin The python package doesn't work properly at the moment. Although it "depends" on openssl, bzip2 etc, it doesn't build the modules for them. (If you have the OS openssl-devel package installed then it will). I've been trying to work out why my python wasn't built correctly and found that if the LDFLAGS and CPPFLAGS aren't set correctly, then setup.py won't find the headers and libraries. As these are normally set by the cc wrapper, they don't end up visible to setup.py.

I'm just testing an updated package for python at the moment, (with some updates for python3 as well).

**Comment by sjtbham** [comment]
@lee218llnl @tgamblin I've added PR 215 which I think resolves the build issues.

**Comment by tgamblin** [comment]
Fixed by #215
