### ISSUE TITLE
Spack name?

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#1253]
@tgamblin I am interested in the history of the `spack` name...

**Comment by davydden** [comment]
> Based on our experiences at LLNL, we have developed Spack, the Supercomputing Package manager

from http://www.computer.org/csdl/proceedings/sc/2015/3723/00/2807623.pdf

**Comment by tgamblin** [comment]
That, and it was google-able when I tried 3 years ago.  The top results were peoples' names; couldnt find any other widely used software products or organizations.

**Comment by mwilliammyers** [comment]
We have been wondering at my work, is it pronounced *s pack* or *spack*?

**Comment by tgamblin** [comment]
I pronounce it "spack".
