### ISSUE TITLE
Should the lmod package depend on tcl?

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#1257]
I'm new to Spack, this is as much a question about how Spack thinks as it is a question about the lmod package....

I'm working from a fairly minimal system image (Digital Ocean's CentOS 7 + the packages that LinuxBrew lists as prerequisites).

I just used spack to install *lmod*.  Along the way I discovered that *lmod* requires *tclsh*.  I used spack to install *tcl*.  The *tcl* package has a tclsh8.6 in it's bin, but

- w/out a module command there's no obvious way to get the *tcl* package's `.../bin` on my path; and
- the *tcl* package doesn't link `tclsh8.6` to `tclsh`.

I did both of these by hand so that I could make things work (I was working towards a working flake8 so that I could clean up my jdk PR), but clearly That's Not Right.  I'm trying to figure out what is the right way to handle this.

Perhaps tcl is considered a Spack prerequisite?  Is there a list of prerequisites?

Or would it be useful (is it possible?) for the lmod package to "depend_on" the tcl package if tclsh doesn't exist, and would satisfying that dependency (aka installing the *tcl* package) set things up so that lmod's configure script would run successfully?

**Comment by alalazo** [comment]
I can confirm that despite I didn't find mention of tcl in [the documentation](http://lmod.readthedocs.io/en/latest/030_installing.html#why-does-lmod-install-differently) of lmod, `configure` wants it to complete successfully. I would say that here a `depends_on('tcl')` is missing.

**Comment by hartzell** [comment]
I just gave it a try and the simple this:

```
[throgg@flaky spack]$ git diff
diff --git a/var/spack/repos/builtin/packages/lmod/package.py b/var/spack/repos/builtin/packages/lmod/package.py
index efa235f..caa9ea1 100644
--- a/var/spack/repos/builtin/packages/lmod/package.py
+++ b/var/spack/repos/builtin/packages/lmod/package.py
@@ -44,6 +44,7 @@ class Lmod(Package):
     depends_on('lua@5.2:')
     depends_on('lua-luaposix', type=nolink)
     depends_on('lua-luafilesystem', type=nolink)
+    depends_on('tcl')

     parallel = False
```

is insufficient.

The generated log file says:

```
[...]
checking for ps... /usr/bin/ps
checking for expr... /usr/bin/expr
checking for basename... /usr/bin/basename
checking for git... /usr/bin/git
checking for less... /usr/bin/less
checking for sha1sum... /usr/bin/sha1sum
checking for tclsh... UNKNOWN

The tclsh program must be in your path. Quitting!

==> 'make' 'install'
make: *** No rule to make target `install'.  Stop.
```

Is there a way to get the tcl package's bin added to the build's PATH?

**Comment by davydden** [comment]
> Is there a way to get the tcl package's bin added to the build's PATH?

it actually should already be in the path during build as default dependency type is `build`+`link`, IIRC. You can check `spack-build.env` file in the build folder.

**Comment by adamjstewart** [comment]
It might be a good idea to check the configure file and see what line looks for tclsh. If you can figure out exactly which filename it is looking for, then you can check to make sure Spack builds that file. If it's looking for `tclsh` and Spack builds `tclsh8.6`, you'll have to add a symlink via the tcl package.

**Comment by davydden** [comment]
@adamjstewart good point, Spack bult `tcl` (at least on macOS) had `tclsh8.6` only.

**Comment by hartzell** [comment]
It's definitely looking for `tclsh`, when I did it by hand I made a link myself.

I'll peek into the tcl package and either learn how to make the link or see if there's a configure option.

All good learning.  Thanks for the help!

**Comment by hartzell** [comment]
{Home,Linux}brew have a command (`brew install -i package_name`) that grabs the tarball, unpacks it, and then plunks you into a shell with the environment set up just as it is during a non-interactive install.

Is there a way to do something similar in spack?

**Comment by adamjstewart** [comment]
> I'll peek into the tcl package and either learn how to make the link or see if there's a configure option.

Check out the bzip2 package. You should be able to do something like:
```python
with working_dir(prefix.bin):
    symlink('tclsh{0}'.format(self.version.up_to(2)), 'tclsh')
```
And put this at the end of tcl's install method.

**Comment by adamjstewart** [comment]
> {Home,Linux}brew have a command (brew install -i package_name) that grabs the tarball, unpacks it, and then plunks you into a shell with the environment set up just as it is during a non-interactive install.
>
> Is there a way to do something similar in spack?

@citibeth?

**Comment by hartzell** [comment]
Thanks @adamjstewart!  I was heading in that general direction but was going to end up with something much less Pythonically graceful for pulling the version out of the existing scripts name.

Testing it now....

**Comment by hartzell** [comment]
Ok, this lets *lmod* build for me:

```
[throgg@flaky spack]$ git diff
diff --git a/var/spack/repos/builtin/packages/lmod/package.py b/var/spack/repos/builtin/packages/lmod/package.py
index efa235f..caa9ea1 100644
--- a/var/spack/repos/builtin/packages/lmod/package.py
+++ b/var/spack/repos/builtin/packages/lmod/package.py
@@ -44,6 +44,7 @@ class Lmod(Package):
     depends_on('lua@5.2:')
     depends_on('lua-luaposix', type=nolink)
     depends_on('lua-luafilesystem', type=nolink)
+    depends_on('tcl')

     parallel = False

diff --git a/var/spack/repos/builtin/packages/tcl/package.py b/var/spack/repos/builtin/packages/tcl/package.py
index a4d8b51..a3294d8 100644
--- a/var/spack/repos/builtin/packages/tcl/package.py
+++ b/var/spack/repos/builtin/packages/tcl/package.py
@@ -49,3 +49,5 @@ class Tcl(Package):
             configure("--prefix=%s" % prefix)
             make()
             make("install")
+        with working_dir(prefix.bin):
+            symlink('tclsh{0}'.format(self.version.up_to(2)), 'tclsh')
[throgg@flaky spack]$
```

I think this will be a change for folks who were previously using the system's tclsh.

Should (how should) I conditionalize it?

**Comment by adamjstewart** [comment]
No need to conditionalize it, I think this is a perfectly fine change. Go ahead and submit a PR.

**Comment by davydden** [comment]
> Should (how should) I conditionalize it?

you should not. This was a bug which you will fix. If someone wants to use system's `tclsh`, they should configure it as an external package in `packages.yaml`.

**Comment by citibeth** [comment]
> Is there a way to do something similar in spack?
>
>
Does `spack env` do the trick?

**Comment by tgamblin** [comment]
@hartzell: `spack env <spec> bash` where `spec` is the same as in `spack install <spec>`.

Note that for `spack env <spec>`, `<spec>` should not have spaces.  I'm working on that (sorry!)

**Comment by hartzell** [comment]
`spack env` is not the same as `brew install -i`.

The latter downloads the tarball, creates a temporary directory, unpacks it, perhaps patch it, then drops you in a shell ready to poke around and practice building it.

Here's brew's help for that option:

```
brew install --interactive [--git] formula:
    Download and patch formula, then open a shell. This allows the user to
    run ./configure --help and otherwise determine how to turn the software
    package into a Homebrew formula.

    If --git is passed, Homebrew will create a Git repository, useful for
    creating patches to the software.
```

`spack env` sets up the environment, but I'm stuck with the rest of the busy work.  But *spack* has taken care of the magical bit.

I don't think that there's anything more to do here, I'll just wait for the PR merge to close the issue.

**Comment by citibeth** [comment]
> spack env is not the same as brew install -i.

I see, thanks for the explanation.  Would anyone be interested in adding
this as a Spack command?  It would be very much like `spack setup` (maybe
could share code), except it would set up env vars and start a shell,
rather than writing `spconfig.py`.

The existing `spack setup` might also work for you (unfortunately only
CMake-based projects at this time).
​

**Comment by adamjstewart** [comment]
`brew install -i` kind of sounds like:
```
spack stage <spec>
spack cd <spec>
spack env <spec>
```
or something like that.

**Comment by citibeth** [comment]
Yes, all the parts are there.  Someone needs to make a Spack cmd that
bundles them up in the right combination that people want.
