### ISSUE TITLE
Allow prefix != spack source tree

### ISSUE THREAD

**Issue by mathstuf** [LLNL/spack#126]
When developing, I'm going to have many spack trees, so it'd be nice to locate the prefix and staging directory somewhere other than the spack source tree.

I have local edits for it right now, but plumbing a command line argument down should be the way to do it (similar for other settings in `lib/spack/spack/__init__.py` while that's going on anyways).

**Comment by adamjstewart** [comment]
@mathstuf Can this be closed now that #2152 is merged?
