### ISSUE TITLE
Add a `test` deptype

### ISSUE THREAD

**Issue by mathstuf** [LLNL/spack#1279]
How it works needs to be figured out (does it act like a build dep? link? run? some combination?), but it should exist.

**Comment by adamjstewart** [comment]
I mentioned this in #1169, but I'll say it again here.

This will be very useful as a lot of packages require certain dependencies only for testing purposes. [GCC](https://gcc.gnu.org/install/test.html) requires DejaGnu, Tcl, and Expect to run its testsuite. [MEEP](https://github.com/adamjstewart/spack/blob/12ca121d4716e066bd3a62c61f36d1a57567af9d/var/spack/repos/builtin/packages/meep/package.py) requires GSL to run its testsuite.

As for linking, I think it should be pretty similar to the build deptype. The only difference is that it isn't required unless someone installs with `--run-tests`.

**Comment by adamjstewart** [comment]
@tgamblin One of the goals of Spack v1.0 is better package testing. Can we add this Issue and #2869 to the list of requirements?

**Comment by scheibelp** [comment]
I have self-assigned this. However, it will take me a while to get to it: I plan on having an update here by 5/8. If anyone else wants to attack this before then feel free (although FYI the concretization logic related to making a change like this is currently being altered).

**Comment by adamjstewart** [comment]
@scheibelp Any updates? There are at least 48 packages with commented out test deptypes now.

**Comment by scheibelp** [comment]
I'm working on a PR for this and plan to have it ready by this Thursday 8/17
