### ISSUE TITLE
[proposal] Make jpeg a virtual dependency

### ISSUE THREAD

**Issue by mwilliammyers** [LLNL/spack#1286]
How does everyone feel about me making jpeg a virtual dependency that is provided by:
- libjpeg
- ipp
- libjpeg-turbo

Am I missing any?

I came across this while I was revamping the opencv package in #1234 and felt like it would be handy there...

**Comment by tgamblin** [comment]
I've wanted to do this for a while.  What I currently don't have is a good hierarchy of `packages.yaml` files to store a preference in.  We will eventually move to a model where Spack ships with a default, per-platform `packages.yaml` files, and sites/users can override that with their own.  This would allow Spack to prefer, say, `libjpeg-turbo` but users to set things up so their stack builds by default with `ipp`.  I'd rather not implement this proposal until we have that capability.  sound reasonable?

**Comment by mwilliammyers** [comment]
Works for me! 

On that note, spack currently ships with a site `modules.yml` , should I overwrite this file to customize it or is there a better way to overwrite the site wide config? As it is right now I just have to be careful not to commit my changes to it...

**Comment by mwilliammyers** [comment]
Yeah that is exactly what I thought but I am confused because in `config.py` [here](https://github.com/LLNL/spack/blob/7555c3d9492b14d30866b7c5ec0ead79347ead05/lib/spack/spack/config.py#L496) where it actually loads the config files and in the comments of `config.py` [here](https://github.com/LLNL/spack/blob/7555c3d9492b14d30866b7c5ec0ead79347ead05/lib/spack/spack/config.py#L35) and in the documentation [here](http://software.llnl.gov/spack/configuration.html#external-packages), [here](http://software.llnl.gov/spack/developer_guide.html#directory-structure) and [here](http://software.llnl.gov/spack/configuration.html#concretization-preferences) it only mentions 2 places where `modules.yaml` would be stored:

1. `$SPACK_ROOT/etc/spack/` (per-site/per-project) 
2. `~/.spack/` (user)

The key thing is that everything is ignored by git under  `$SPACK_ROOT/etc/spack/` by [this](https://github.com/LLNL/spack/blob/7555c3d9492b14d30866b7c5ec0ead79347ead05/.gitignore#L8) line *except* for `$SPACK_ROOT/etc/spack/{modules.yaml,repos.yaml}` which were already versioned before that directory was added to `.gitignore` in 34401cf. Meaning that I can edit `$SPACK_ROOT/etc/spack/packages.yaml` as my site-wide packages config no problem but I can't do the same for`$SPACK_ROOT/etc/spack/modules.yaml`.

**Comment by tgamblin** [comment]
@mwilliammyers: FYI, this can be done now.  There has been for a while an `etc/spack/defaults/packages.yaml` file that you can put default deps in.  So we have the ability to set a default JPEG implementation that users can override... If you want to take a stab at it.

**Comment by adamjstewart** [comment]
Feel free to create a virtual dependency for jpeg if you want. If not, that's fine too. I'm going to close this issue as it sounds like the discussion is done. Trying to close out old issues so that we can focus on the relevant bugs.
