### ISSUE TITLE
[Proposal] Add sanity check to import Python modules

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#1305]
I've run into a few Python packages so far that built without any trouble, but raised error messages when trying to import them. See https://github.com/LLNL/spack/pull/1156#issuecomment-233030464 for an example.

A quick and easy sanity check would be to import the newly installed Python package using the Python installation it was built with. In the case of py-meep, the module name depends on how it was built. For `py-meep+mpi`, the module name is `meep_mpi`. For `py-meep~mpi`, it is `meep`. We will need some kind of function to return the correct module name for each package. It is probably safe to default to `self.name.replace('py-', '')`.

I believe the actual implementation should wait until after #1186 is complete. That way, it can easily be added to a PythonPackage class.

**Comment by alalazo** [comment]
Just FIY, this week I'll be pretty busy with [this](https://ep2016.europython.eu/en/) but next week I'll try to fix `spack setup` in #1186, which is the last bit remaining for the PR to be in a reviewable state.
