### ISSUE TITLE
Spack prefers cmake@3.4.3 instead of the newest version

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1306]
I am installing a few packages. cmake is pulled in as dependency. No cmake version is specified explicitly, although some package specify cmake version constraints.

Spack decides to install `cmake @3.4.3`. This version number does not appear anywhere. However, it is the version number given in cmake's `url` string.

This looks like a bug. Spack should choose the most modern cmake version here, which is `cmake @3.6.0`.

**Comment by adamjstewart** [comment]
I can't reproduce this. What commit are you on? What's the output of `spack spec cmake`? What about `spack spec arpack-ng`, or any other package that depends on cmake?

**Comment by davydden** [comment]
maybe a concrete example would help to debug the issue. Have you checked for `cmake@:3.4` being mentioned? That could lead to `3.4.3` being chosen.

**Comment by davydden** [comment]
@adamjstewart you beat me by 2 seconds :smile:

**Comment by davydden** [comment]
@eschnett you can also change url to, say, `3.5.2` and see if this has any effect.

**Comment by eschnett** [comment]
`spack spec` tells me that `cmake` is not required. I assume this means that `cmake` is not a run-time dependency, which is correct. But it is a build-time dependency. Is there a way to output them?

**Comment by adamjstewart** [comment]
Build dependencies should be output as well. With the current develop head:
```
$ spack spec cmake
Input spec
------------------------------
  cmake

Normalized
------------------------------
  cmake

Concretized
------------------------------
  cmake@3.6.0%gcc@6.1.0~doc+ncurses+openssl~qt arch=darwin-elcapitan-x86_64
      ^ncurses@6.0%gcc@6.1.0 arch=darwin-elcapitan-x86_64
      ^openssl@1.0.2h%gcc@6.1.0 arch=darwin-elcapitan-x86_64
          ^zlib@1.2.8%gcc@6.1.0 arch=darwin-elcapitan-x86_64

$ spack spec arpack-ng
Input spec
------------------------------
  arpack-ng

Normalized
------------------------------
  arpack-ng
      ^blas
      ^lapack

Concretized
------------------------------
  arpack-ng@3.4.0%gcc@6.1.0~mpi+shared arch=darwin-elcapitan-x86_64
      ^atlas@3.10.2%gcc@6.1.0+shared arch=darwin-elcapitan-x86_64
      ^cmake@3.6.0%gcc@6.1.0~doc+ncurses+openssl~qt arch=darwin-elcapitan-x86_64
          ^ncurses@6.0%gcc@6.1.0 arch=darwin-elcapitan-x86_64
          ^openssl@1.0.2h%gcc@6.1.0 arch=darwin-elcapitan-x86_64
              ^zlib@1.2.8%gcc@6.1.0 arch=darwin-elcapitan-x86_64
```

**Comment by eschnett** [comment]
```
$ spack spec arpack-ng
Input spec
------------------------------
  arpack-ng

Normalized
------------------------------
  arpack-ng
      ^blas
      ^lapack

Concretized
------------------------------
  arpack-ng@3.4.0%gcc@6.1.0-spack~mpi+shared arch=darwin-elcapitan-x86_64
      ^atlas@3.10.2%gcc@6.1.0-spack+shared arch=darwin-elcapitan-x86_64
      ^cmake@3.4.3%gcc@6.1.0-spack~doc+ncurses+openssl~qt arch=darwin-elcapitan-x86_64
          ^ncurses@6.0%gcc@6.1.0-spack arch=darwin-elcapitan-x86_64
          ^openssl@1.0.2h%gcc@6.1.0-spack arch=darwin-elcapitan-x86_64
              ^zlib@1.2.8%gcc@6.1.0-spack arch=darwin-elcapitan-x86_64
```

So Spack chooses version `3.4.3`.

This is with the head of the `develop` branch (commit `dd7bd4f`).

**Comment by eschnett** [comment]
Nevermind; there was a file `~/.spack/packages.yaml`.
