### ISSUE TITLE
R module (and dotkit?) file needs LIBRARY_PATH and LD_LIBRARY_PATH for bioconductor installs

### ISSUE THREAD

**Issue by adamhough** [LLNL/spack#1314]
Currently the module file setup by spack for R will not add the correct library paths which results in broken library links.

$ ldd ~/R/x86_64-pc-linux-gnu-library/3.3/ncdf4/libs/ncdf4.so  | grep -i not
        libR.so => not found

If the library paths are added to the environment then ncdf4.so dynamically links correctly.
$  ldd R/x86_64-pc-linux-gnu-library/3.3/ncdf4/libs/ncdf4.so | grep libR.so
        libR.so => /gpfs/software/spack/opt/spack/linux-redhat6-x86_64/gcc-6.1.0/R-3.3.1-tpkh25pakjkfxwqth7kp3gxl4grlf6c2/rlib/R/lib/libR.so (0x00002aaaae244000)

Need to add the following to the R module file:
prepend-path --delim ":" LIBRARY_PATH "PATH_TO_R_library"
prepend-path --delim ":" LD_LIBRARY_PATH "PATH_TO_R_library"

ncdf4 was installed as a pre-req to GENESIS. https://www.bioconductor.org/packages/devel/bioc/html/GENESIS.html

I will look into this further to submit a patch as I get my user running.

**Comment by davydden** [comment]
it could have to do with the absence of `soname`/`install_name` in `libR`, which should be fixed. My understanding is that otherwise `netcdf` will be dynamically linking against anything it can find in paths, not necessarily something installed by Spack.

**Comment by alalazo** [comment]
@adamhough You can customize what gets written in module files, see [the documentation here](http://software.llnl.gov/spack/basic_usage.html#configuration-files).

**Comment by adamhough** [comment]
Possibly that would also explain why I am picking up modules from other packages not in my listed library paths which is because of netcdf.  That would also explain why ncdf4.so is also picking up libscif from torque even though it is not in any default path in my build environment.

**Comment by adamhough** [comment]
@alalazo Thanks for pointing that out as I had forgotten about that.  Only started using spack last week.

**Comment by alalazo** [comment]
@adamhough Not a problem!

**Comment by glennpj** [comment]
I just submitted #1323 that should address this by putting the paths in the environment module.
