### ISSUE TITLE
Question: How to use depends_on w/out caring about variants.

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#1362]
I'm working on a package (cask) that depends_on('emacs').  I have emacs installed w/out X:

```
[throgg@spack-central spack]$ spack find -v emacs
==> 1 installed packages.
-- linux-centos7-x86_64 / gcc@5.4.0 -----------------------------
emacs@24.5~X~gtkplus
```

Cask ends up wanting emacs *with* X, which won't work (stripped remote access machine).

```
[throgg@spack-central spack]$ spack spec cask
Input spec
------------------------------
  cask

Normalized
------------------------------
  cask
      ^emacs
          ^ncurses

Concretized
------------------------------
  cask@0.7.4%gcc@5.4.0 arch=linux-centos7-x86_64
      ^emacs@24.5%gcc@5.4.0+X~gtkplus arch=linux-centos7-x86_64
          ^giflib@5.1.4%gcc@5.4.0 arch=linux-centos7-x86_64
          ^libpng@1.6.16%gcc@5.4.0 arch=linux-centos7-x86_64
              ^zlib@1.2.8%gcc@5.4.0 arch=linux-centos7-x86_64
          ^libtiff@4.0.3%gcc@5.4.0 arch=linux-centos7-x86_64
              ^jpeg@9b%gcc@5.4.0 arch=linux-centos7-x86_64
              ^xz@5.2.2%gcc@5.4.0 arch=linux-centos7-x86_64
          ^libxpm@3.5.11%gcc@5.4.0 arch=linux-centos7-x86_64
          ^ncurses@6.0%gcc@5.4.0 arch=linux-centos7-x86_64
```

I think that this is because the X variant in the emacs package defaults to `True`.

I expected a dependency on a package w/out a variant spec to essentially wildcard that variant when it was concretized.

Is there a way to specify a dependency w/out regard to variants?  I don't see any mention in [the dependencies section of the packaging guide](http://software.llnl.gov/spack/packaging_guide.html#dependencies).

**Comment by adamjstewart** [comment]
Yes, it would be great if Spack queried already installed packages before concretization. Unfortunately, this is not the case. Right now, Spack concretizes the spec without any consideration of what is already installed. See any of the following discussions for more information:

#1325 
#1280 
#1178 
#1055 
#839 
#646 
#644 
#577 
#311 

Basically, most people agree that this would be really nice behavior, but no one has gotten around to implementing it.

In the meantime, you have a couple of options. If you just want to install it once and get it working, you can be more specific:
```
spack install cask ^emacs~gtkplus
```
Or if you think you'll have multiple installations that run into this problem, you can permanently set gtkplus to default to False. Run `spack config edit packages` and enter the following text:
```yaml
packages:
  emacs:
    variants: ~gtkplus
```
More information on Spack's configuration settings can be found at:
http://software.llnl.gov/spack/configuration.html

**Comment by hartzell** [comment]
From the newbie perspective, I'm surprised that the issue is

> Spack concretizes the spec without any consideration of what is already installed [...]

I'd expect that Spack would assume that any unmentioned variant in a `depends_on()` would be a "don't care" and more-or-less wild card them.

Perhaps that's another way of saying the same thing.

I suspect that this is well plowed ground and I'll dig into those issues.

Thanks!
