### ISSUE TITLE
Question: What are the plans for X11/xorg?

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#1368]
What is Spack's plan for things that use X11?  

Is there interest/support for doing something like what [Linuxbrew did with homebrew-xorg](https://github.com/Linuxbrew/homebrew-xorg/blob/master/xorg.rb) or is the approach to depend on OS distributions, or ?

I see packages for *xproto*, *xorg-util-macros*, *libxshmfence*, and *dri2proto*.

**Comment by citibeth** [comment]
I don't have much interest, I'm happy relying on my system-provided X libraries.  That lack of interest would change if I found myself on some crazy ancient system.

**Comment by bcdarwin** [comment]
It would be useful on grids where the admins haven't installed a full suite of xlibs, since lots of software needs some subset of these (and sometimes it's not even too easy to find out what/where packages are installed on headless nodes) ...

**Comment by tgamblin** [comment]
@hartzell: I'd be very interested in having a package like this.  I think many of the pieces are there, Spack just doesn't currently have a meta-package to lump them all together.

**Comment by citibeth** [comment]
@hartzell is building X11/Xorg librarys particularly different from any other library?  I imagine that someone just needs to write the Spack packages.  In my experience, that is not really any harder than reading the directions for the software in question and installing by hand.

**Comment by hartzell** [comment]
@citibeth -- I don't think that there's anything particularly hard about it, other than perhaps there seem to be a double handful of them.  I'd start with the existing bits and the Linuxbrew work and go from there.

It's mostly a question about whether people would use them (is it worth the time) and whether it's in line with where Spack is trying to go.

**Comment by tgamblin** [comment]
We're interested at LLNL for packaging performance tools (which is actually what Spack was originally for).  A lot of them have GUIs and such, and I'd really like to be able to support building those on Mac, Linux, and HPC front-end machines.

**Comment by citibeth** [comment]
I'm of the opinion that any package is worth the effort if at least one
person wants it.

**Comment by hartzell** [comment]
Sounds like it's worth investing in.

Thanks for the feedback.

**Comment by tgamblin** [comment]
@hartzell: thanks for asking!

**Comment by adamjstewart** [comment]
I'm currently trying to install ncview which depends on the X11 Athena Widgets, which apparently aren't installed on CentOS 6 already. So some X11 packages would certainly be useful.

**Comment by citibeth** [comment]
I got it on my CentOS 7 just fine.

**Comment by adamjstewart** [comment]
Yeah, I ended up installing it with yum.
