### ISSUE TITLE
qa : issues with flake8 update and OrderedDict

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#1370]
It seems the last update of `flake8` removed support for python 2.6  : 
```
File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/flake8/utils.py", line 287, in parameters_for
    parameters = collections.OrderedDict([
AttributeError: 'module' object has no attribute 'OrderedDict'
```
which makes all the tests failing since yesterday. What if we run flake8 checks only for python2.7 ?

**Comment by adamjstewart** [comment]
I've been thinking about this a lot lately, and honestly it would be really nice if we could split up all of the tests. Right now, if you have a flake8 error, Travis says that all tests failed. Could we run `spack test` for Python 2.6 and 2.7 and then in a separate test could we run flake8?

Another thing that is weird/annoying is that we run `spack test` regardless of whether we update core Spack code, a package.py file, or the documentation. If we could only run `spack test` when we edit core Spack code and only run flake8 when we edit a Python file then I think CI will be less confusing and time consuming.

There's no logic in place right now for this, but it would be cool if someday, when I submit a PR to edit a package.py, Travis tries to build that package. Of course, if we wanted to do it right, it would try building on a couple architectures with a few compilers.

**Comment by alalazo** [comment]
From [flake8 docs](http://flake8.pycqa.org/en/3.0.2/release-notes/3.0.0.html) :  

> Drop explicit support for Pythons 2.6, 3.2, and 3.3.

**Comment by alalazo** [comment]
@adamjstewart I fully agree with the comment above

**Comment by alalazo** [comment]
@tgamblin If it is fine with you I'll try to put together a small PR to : 
- separate `flake8` from `spack test`
- execute `flake8` only with `python@2.7`
- (maybe) submit coverage results only from `python@2.7`

**Comment by tgamblin** [comment]
@alalazo: That sound good to me.  I really wish Travis had a way to put *two* check marks on the PR, instead of requiring you to drill down to the Travis control panel to see what worked and what did not.  But seeing it separately in Travis is better than requiring people to go all the way to the log.

I think the python 2.7 and coverage ideas are good too.
