### ISSUE TITLE
Can't build CMake with Intel compilers

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#1415]
@mathstuf Here is the build log when I try to build CMake 3.6.0 with Intel 15.0.0 on the latest develop branch: [spack-build.out](https://github.com/LLNL/spack/files/394819/spack-build.txt)

Let me know if you want any other files.

**Comment by mathstuf** [comment]
I have a fix for 3.6.2. See this issue: https://gitlab.kitware.com/cmake/cmake/issues/16226.

**Comment by adamjstewart** [comment]
Awesome, thank you!

**Comment by adamjstewart** [comment]
Just tried out your patch and it works perfectly. I'll add it to #1412
