### ISSUE TITLE
spack command recursing and crashing

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#1429]
After updating my fork, and also in a freshly cloned repository `spack` is crashing:

```
[throgg@baloney spack]$ spack clean git
Traceback (most recent call last):
  File "/home/throgg/foo/spack/bin/spack", line 179, in <module>
    main()
  File "/home/throgg/foo/spack/bin/spack", line 157, in main
    return_val = command(parser, args)
  File "/home/throgg/foo/spack/lib/spack/spack/cmd/clean.py", line 46, in clean
    package.do_clean()
  File "/home/throgg/foo/spack/lib/spack/spack/package.py", line 1376, in do_clean
    self.stage.destroy()
  File "/home/throgg/foo/spack/lib/spack/spack/package.py", line 532, in stage
    self._stage = self._make_stage()
  File "/home/throgg/foo/spack/lib/spack/spack/package.py", line 512, in _make_stage
    stage = self._make_root_stage(fetcher)
  File "/home/throgg/foo/spack/lib/spack/spack/package.py", line 496, in _make_root_stage
    mp = spack.mirror.mirror_archive_path(self.spec, fetcher)
  File "/home/throgg/foo/spack/lib/spack/spack/mirror.py", line 72, in mirror_archive_path
    return join_path(spec.name, mirror_archive_filename(spec, fetcher))
  File "/home/throgg/foo/spack/lib/spack/spack/mirror.py", line 64, in mirror_archive_filename
    filename = "%s-%s" % (spec.package.name, spec.version)
[...]
  File "/home/throgg/foo/spack/lib/spack/llnl/util/lang.py", line 248, in <lambda>
    setter('__hash__', lambda self: hash(self._cmp_key()))
  File "/home/throgg/foo/spack/lib/spack/spack/spec.py", line 2058, in _cmp_key
    for name in sorted(dep_dict)),)
  File "/home/throgg/foo/spack/lib/spack/spack/spec.py", line 2058, in <genexpr>
    for name in sorted(dep_dict)),)
  File "/home/throgg/foo/spack/lib/spack/llnl/util/lang.py", line 248, in <lambda>
    setter('__hash__', lambda self: hash(self._cmp_key()))
RuntimeError: maximum recursion depth exceeded while calling a Python object
```

The full trace is here:  https://gist.github.com/hartzell/108ac201d1686146386d03148e03dd7c

**Comment by hartzell** [comment]
This commit fails:

    commit 353726f08f620aab527931069dfdb882e8eb409e
    Merge: 7ae163d ab885a5
    Author: becker33 <becker33@llnl.gov>
    Date:   Wed Aug 3 10:07:05 2016 -0700

This commit (the previous one) works as it should:

    commit 7ae163d4369f7ab74b816f52cd0cbb4727a35876

**Comment by adamjstewart** [comment]
@becker33

**Comment by tgamblin** [comment]
Should be fixed by #1430.  Please reopen if this still fails.

**Comment by hartzell** [comment]
I just fetched, and am still having the problem.  I think that the cray thing is different.  I'm here:

```
commit dce105d16f69eb14ce81ba6cdd705aad05234485
Merge: 88bb67e 7c46a4c
Author: Todd Gamblin <tgamblin@llnl.gov>
Date:   Wed Aug 3 13:45:18 2016 -0700
```

**Comment by hartzell** [comment]
I can't find a "reopen" button....

**Comment by hartzell** [comment]
Hang on.  It **only** happens when I try to clean `git`, not any other packages.  My git build blew up a bit ago when I lost my network connection, ...  Let me get out a big stick and clean house.

**Comment by hartzell** [comment]
I'm still having trouble.  `spack clean gettext` also crashes.

Is it a problem for git to `depend_on('gettext')` and gettext to `depend_on('git...')`?

E.g. in the [diff of the commit that broke things for me](https://github.com/LLNL/spack/commit/353726f08f620aab527931069dfdb882e8eb409e#diff-77224be694a7362036aead6d09393f5bR39))

and/or line 52.

**Comment by tgamblin** [comment]
@adamjstewart: can you look at this one?

**Comment by hartzell** [comment]
Commenting out the `depends_on('gettext')` in the git package let's clean run successfully.

g.

**Comment by adamjstewart** [comment]
Oh yes, git can't depend on gettext if gettext depends on git. We don't want any circular dependencies here. I'm not super familiar with how git uses gettext or how gettext uses git, but we should probably comment out one of the dependencies and leave a note mentioning that it's a circular dependency. We can also check if either of those package tarballs come with that dependency already.

**Comment by adamjstewart** [comment]
I think we could also tell git to `depends_on('gettext~git')`. What do other people think?

**Comment by tgamblin** [comment]
That seems reasonable, although if we don't understand how `git` uses `gettext` or vice-versa, why not make `gettext` just not depend on `git`?  Is the integration necessary?  Seems like a big dependency.

**Comment by adamjstewart** [comment]
From gettext's configure:
```
Optional Packages:
  --without-git           don't use git to compress the infrastructure archive
```
and gettext's DEPENDENCIES:
```
* git 1.6 or newer
  + Recommended.
    Needed by the 'autopoint' program, if not configured with --without-git
    or --with-cvs.
```
From git's INSTALL:
```
        - A gettext library is used by default for localizing Git. The
          primary target is GNU libintl, but the Solaris gettext
          implementation also works.

          We need a gettext.h on the system for C code, gettext.sh (or
          Solaris gettext(1)) for shell scripts, and libintl-perl for Perl
          programs.

          Set NO_GETTEXT to disable localization support and make Git only
          use English. Under autoconf the configure script will do this
          automatically if it can't find libintl on the system.
```

Localization for git is probably more important that compression for gettext? Both packages will build without those dependencies, or will pick up the system dependencies if they exist.

**Comment by tgamblin** [comment]
It sounds like git is only a `run` dependency of `gettext`, specifically its `autopoint` program, so it shouldn't be required as part of the *build* of `gettext`.

That said, Spack is not currently smart enough to figure out that `run`-only deps can be built *after* things that require them... It assumes a DAG in many places.  Can we remove the dependency for now?

@mathstuf: you should probably look at this one.

**Comment by hartzell** [comment]
I'm inclined to agree that the i18n support in git is more likely to be important.

Looks like some guy named:

    7e53f432 (Adam J. Stewart 2016-07-01 16:30:11 -0500  52)     depends_on('git@1.6:', when='+git')

enabled it for gettext.  We could ask him :smile:

**Comment by adamjstewart** [comment]
Haha, I just blindly added all dependencies.

**Comment by hartzell** [comment]
I'm having other gettext related problems building git, see #1436

**Comment by mathstuf** [comment]
Something else to add onto the #839 heap?

**Comment by IanLee1521** [comment]
FWIW, a straight ``./bin/spack install git`` from a completely clean clone of spack also causes the recurse and die behavior.

**Comment by tgamblin** [comment]
Fixed by removing git dependency by gettext.  We can add that back when we're smart enough to handle run dependencies that don't actually introduce cycles.
