### ISSUE TITLE
spack compiler wrappers munging include file lines when building cbtf-krell

### ISSUE THREAD

**Issue by jgalarowicz** [LLNL/spack#1434]
Unless I am missing something, it appears that the spack compiler wrappers are causing the `cbtf-krell` component to fail to build.

For the file that fails to build, I've isolated the failing compile line out and replaced the
`/home/jgalaro/spack/lib/spack/env/gcc/g++` phrase with `/usr/bin/g++`
With `/usr/bin/g++` the compile works, but with the spack wrapper the `-I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/build_cbtf_krell/messages/src/symtab` seems to be mucked up by the wrapper.

Here is the compile command I invoked:

```
/home/jgalaro/spack/lib/spack/env/gcc/g++   -DHAVE_DLOPEN -DHAVE_STDINT_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_TARGET_DLOPEN -DVERSION=\"1.6.0\" -Dcbtf_messages_converters_symtab_EXPORTS -Dos_linux -O2 -g -std=c++0x -fPIC -I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/build_cbtf_krell/messages/src/symtab -I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/messages/src/symtab -I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/build_cbtf_krell/messages/src/symtab -I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/build_cbtf_krell/messages/src/symtab../base -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/mrnet-5.0.1-2-2rcgpsm2uiffkx5ptg25m7wstz5rddti/include -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/mrnet-5.0.1-2-2rcgpsm2uiffkx5ptg25m7wstz5rddti/lib/mrnet-5.0.1/include -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/mrnet-5.0.1-2-2rcgpsm2uiffkx5ptg25m7wstz5rddti/lib/xplat-5.0.1/include -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/boost-1.53.0-p2fdcohijrb4gvd27olpdcnxjugrcfhg/include -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/cbtf-1.6-4j6wcyigyzwhvufnhklj57y7puebxqvo/include -I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/messages/src/base -I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/build_cbtf_krell/messages/src/base    -o CMakeFiles/cbtf-messages-converters-symtab.dir/Converters.cpp.o -c /tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/messages/src/symtab/Converters.cpp
```

But the spack wrapper munged the include line:   See `-p/jgalaro` in bold.   I added the same line again and it munged the second one in a different way.   See `**/cbtf-krell/bucbtf_krell/me**`  that is supposed to be `**/cbtf-krell/build_cbtf_krell/me**`

```
bash-4.1$ /home/jgalaro/spack/lib/spack/env/gcc/g++   -DHAVE_DLOPEN -DHAVE_STDINT_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_TARGET_DLOPEN -DVERSION=\"1.6.0\" -Dcbtf_messages_converters_symtab_EXPORTS -Dos_linux -O2 -g -std=c++0x -fPIC **-p/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/build_cbtf_krell/messages/src/symtab** -I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/messages/src/symtab **-I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/bucbtf_krell/messages/src/symtab** -I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/build_cbtf_krell/messages/src/symtab../base -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/mrnet-5.0.1-2-2rcgpsm2uiffkx5ptg25m7wsddti/include -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/mrnet-5.0.1-2-2rcgpsm2uiffkx5ptg25m7wstz5rddti/lib/mrnet-5.0.1/include -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/mrnet-5.0.1-2-2rcgpsm2uiffkx5pt7wstz5rddti/lib/xplat-5.0.1/include -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/boost-1.53.0-p2fdcohijrb4gvd27olpdcnxjugrcfhg/include -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/cbtf-1.6-4j6wcyigyzwhvufn57y7puebxqvo/include -I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/messages/src/base -I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/build_cbtf_krell/messages/src/base    -o CMakeFiles/cbtf-messages-conver-symtab.dir/Converters.cpp.o -c /tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/messages/src/symtab/Converters.cpp
/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/messages/src/symtab/Converters.cpp:25: error: ‘CBTF_Protocol_AddressBitmap’ was not declared in this scope
...
...
...
/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/messages/src/symtab/Converters.cpp:29: error: invalid type in declaration before ‘;’ token
/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/messages/src/symtab/Converters.cpp:29: error: redefinition of ‘int KrellInstitute::CBTF::Impl::instance’
/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/messages/src/symtab/Converters.cpp:25: error: ‘int KrellInstitute::CBTF::Impl::instance’ previously declared here
bash-4.1$
bash-4.1$
**/usr/bin/g++ works:**
bash-4.1$
bash-4.1$ /usr/bin/g++   -DHAVE_DLOPEN -DHAVE_STDINT_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_TARGET_DLOPEN -DVERSION=\"1.6.0\" -Dcbtf_messages_converters_symtab_EXPORTS -Dos_linux -O2 -g -std=c++0x -fPIC -I/tmp/jgalaro/spack-stage/spatage-Qb0Vjp/cbtf-krell/build_cbtf_krell/messages/src/symtab -I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/messages/src/symtab -I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/build_cbtf_krell/messages/src/sb -I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/build_cbtf_krell/messages/src/symtab../base -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/mrnet-5.0.1-2-2rcgpsm2uiffkx5ptg25m7wstz5rddti/include -I/home/jgalspack/opt/spack/Linux-x86_64/gcc-4.4.7/mrnet-5.0.1-2-2rcgpsm2uiffkx5ptg25m7wstz5rddti/lib/mrnet-5.0.1/include -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/mrnet-5.0.1-2-2rcgpsm2uiffkx5ptg25m7wstz5rddti/lib/xplat-5.0nclude -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/boost-1.53.0-p2fdcohijrb4gvd27olpdcnxjugrcfhg/include -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/cbtf-1.6-4j6wcyigyzwhvufnhklj57y7puebxqvo/include -I/tgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/messages/src/base -I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/build_cbtf_krell/messages/src/base    -o CMakeFiles/cbtf-messages-converters-symtab.dir/Converters.cp-c /tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/messages/src/symtab/Converters.cpp
bash-4.1$
```

**Comment by jgalarowicz** [comment]
Does anyone have an idea on where to start on this one?   I can debug, but I'm not sure where to look.

**Comment by jgalarowicz** [comment]
@tgamblin Do you have any ideas on this one and where I or someone should look for a fix?   This issues is holding up our spack release milestone to the Trilabs, as I can't submit a pull request for our changes because cbtf-krell fails to build.   Thanks.

**Comment by jgalarowicz** [comment]
@tgamblin 
@becker33  Do you have any ideas on this one and where I or someone should look for a fix? This issues is holding up our spack release milestone to the Trilabs, as I can't submit a pull request for our changes because cbtf-krell fails to build. Thanks.

**Comment by tgamblin** [comment]
@jgalarowicz: sorry for the slow response. I'll prioritize this this week.

**Comment by jgalarowicz** [comment]
@tgamblin Thanks!

**Comment by tgamblin** [comment]
@jgalarowicz: I tried this several different ways and can't seem to replicate it.  I tried to run that compile line through the compiler wrapper in bash 3 and bash 4.1, and I can't get it to munge the text.

Here's what I did to launch spack in debug mode:
```sh
$ spack -d env cbtf-krell bash
$ /home/jgalaro/spack/lib/spack/env/gcc/g++   -DHAVE_DLOPEN -DHAVE_STDINT_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_TARGET_DLOPEN -DVERSION=\"1.6.0\" -Dcbtf_messages_converters_symtab_EXPORTS -Dos_linux -O2 -g -std=c++0x -fPIC -I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/build_cbtf_krell/messages/src/symtab -I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/messages/src/symtab -I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/build_cbtf_krell/messages/src/symtab -I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/build_cbtf_krell/messages/src/symtab../base -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/mrnet-5.0.1-2-2rcgpsm2uiffkx5ptg25m7wstz5rddti/include -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/mrnet-5.0.1-2-2rcgpsm2uiffkx5ptg25m7wstz5rddti/lib/mrnet-5.0.1/include -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/mrnet-5.0.1-2-2rcgpsm2uiffkx5ptg25m7wstz5rddti/lib/xplat-5.0.1/include -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/boost-1.53.0-p2fdcohijrb4gvd27olpdcnxjugrcfhg/include -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/cbtf-1.6-4j6wcyigyzwhvufnhklj57y7puebxqvo/include -I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/messages/src/base -I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/build_cbtf_krell/messages/src/base    -o CMakeFiles/cbtf-messages-converters-symtab.dir/Converters.cpp.o -c /tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/messages/src/symtab/Converters.cpp
bash: /home/jgalaro/spack/lib/spack/env/gcc/g++: No such file or directory
```

That produces two output files -- a `spack-cc-*.in.log` and a `spack-cc-*.out.log`, which you can diff.  Is that how you figured out that the line is munged?  The `spack*.out.log` file should contain what the compiler wrapper actually invoked, but for me it is  not different from the input file, save for the `-I` directories inserted before the command line.

I noticed you're using bash 4.1, so I tried that since my bash version is 3.2 and the `cc` wrapper in `lib/spack/env` is written in `bash`.  But that gets me the same results.

What does `which bash` return in your environment?  Is it actually a bash install?  Or is it some other shell?  And what OS release and specific bash version are you running?

I took your compile line above and differ it with your munged version.  It looks like more than what you mentioned is happening.

Here are the parts of the file that had diffs -- hashes and other things seem to be getting truncated in your output too:

```diff
- -I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/build_cbtf_krell/messages/src/symtab
+ -p/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/build_cbtf_krell/messages/src/symtab
```

```diff
- -I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/build_cbtf_krell/messages/src/symtab
+ -I/tmp/jgalaro/spack-stage/spack-stage-Qb0Vjp/cbtf-krell/bucbtf_krell/messages/src/symtab
```

```diff
- -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/mrnet-5.0.1-2-2rcgpsm2uiffkx5ptg25m7wstz5rddti/include
+ -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/mrnet-5.0.1-2-2rcgpsm2uiffkx5ptg25m7wsddti/include
```

```diff
- -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/mrnet-5.0.1-2-2rcgpsm2uiffkx5ptg25m7wstz5rddti/lib/xplat-5.0.1/include
+ -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/mrnet-5.0.1-2-2rcgpsm2uiffkx5pt7wstz5rddti/lib/xplat-5.0.1/include
```

```diff
- -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/cbtf-1.6-4j6wcyigyzwhvufnhklj57y7puebxqvo/include
+ -I/home/jgalaro/spack/opt/spack/Linux-x86_64/gcc-4.4.7/cbtf-1.6-4j6wcyigyzwhvufn57y7puebxqvo/include
```

```diff
- -o CMakeFiles/cbtf-messages-converters-symtab.dir/Converters.cpp.o
+ -o CMakeFiles/cbtf-messages-conver-symtab.dir/Converters.cpp.o
```

**Comment by jgalarowicz** [comment]
@tgamblin  Thanks for looking at this.

That is weird that it works for you, but that makes sense, since no one else is having this issue.   Maybe I need to put my .bashrc aside and try building with a skeletal .bashrc.   This happens to me on skybridge at SNL and NASA pfe, but I usually duplicate my laptop version on the other machines.
So if there is something wrong in my .bashrc, then it will be on all the machines.

Here is some data:
[jeg@localhost ~]$ which bash
/usr/bin/bash
[jeg@localhost ~]$ bash --version
GNU bash, version 4.2.53(1)-release (x86_64-redhat-linux-gnu)
Copyright (C) 2011 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>

[jeg@localhost ~]$ 
[jeg@localhost ~]$ uname -a
Linux localhost 3.14.27-100.fc19.x86_64 #1 SMP Wed Dec 17 19:36:34 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
[jeg@localhost ~]$ 

I wonder what could cause that kind of munging?

I'll try playing with my environment.
As a sanity check, I have this in my .bashrc - maybe this is the problem?

export SPACK_ROOT=/home/jeg/spack
export PATH=$SPACK_ROOT/bin:$PATH
SYS_TYPE=$(uname -sp) 
export SYS_TYPE=${SYS_TYPE/ /-}  #  i.e. "linux-fedora19-x86_64".  Replace spaces with dash.
. $SPACK_ROOT/share/spack/setup-env.sh

**Comment by jgalarowicz** [comment]
@tgamblin Hi Todd,   Well I moved my .bashrc off to the side and put a simple one in its place, started from scratch with a fresh download of spack, then a merge of the upstream, but cbtf-krell still fails.  
Here is my env:
[jeg@localhost packages]$ env
XDG_VTNR=1
SVN_RSH=ssh
XDG_SESSION_ID=1
SPACK_ROOT=/home/jeg/spack3/spack
HOSTNAME=localhost
IMSETTINGS_INTEGRATE_DESKTOP=yes
GPG_AGENT_INFO=/run/user/1000/keyring-yXuJfn/gpg:0:1
GUIDEHOME=/usr/openwin/lib/guide
TERM=xterm-256color
VTE_VERSION=3409
XDG_MENU_PREFIX=gnome-
SHELL=/bin/bash
HISTSIZE=1000
GJS_DEBUG_OUTPUT=stderr
CVSROOT=:ext:jgalarowicz@openss.cvs.sourceforge.net:/cvsroot/openss
WINDOWID=35677046
QTDIR=/usr/lib64/qt-3.3
GNOME_KEYRING_CONTROL=/run/user/1000/keyring-yXuJfn
QTINC=/usr/lib64/qt-3.3/include
GJS_DEBUG_TOPICS=JS ERROR;JS LOG
IMSETTINGS_MODULE=none
QT_GRAPHICSSYSTEM_CHECKED=1
USER=jeg
LS_COLORS= < removed for space >
OPENWINHOME=/usr/openwin
SSH_AUTH_SOCK=/run/user/1000/keyring-yXuJfn/ssh
SESSION_MANAGER=local/unix:@/tmp/.ICE-unix/1585,unix/unix:/tmp/.ICE-unix/1585
USERNAME=jeg
HELPPATH=/usr/openwin/lib/help
DESKTOP_SESSION=gnome
MAIL=/var/spool/mail/jeg
PATH=/home/jeg/spack3/spack/bin:/opt/cisco_trilabs/anyconnect/bin:/usr/local/krb5/bin:/usr/kerberos/bin:/opt/cisco-trilabs/anyconnect/bin:/usr/lib64/qt-3.3/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/usr/openwin/bin:/home/jeg/.local/bin:/home/jeg/bin
QT_IM_MODULE=ibus
PWD=/home/jeg/spack3/spack/var/spack/repos/builtin/packages
XMODIFIERS=@im=ibus
GNOME_KEYRING_PID=1583
LANG=en_US.utf8
KDE_IS_PRELINKED=1
GDM_LANG=en_US.utf8
MODULEPATH=/home/jeg/spack3/spack/share/spack/modules/linux-fedora19-x86_64:/home/jeg/privatemodules:/home/jeg/privatemodules:/home/jeg/privatemodules:/usr/share/Modules/modulefiles:/etc/modulefiles
LOADEDMODULES=
KDEDIRS=/usr
KRB5_CONFIG=/usr/local/krb5/etc/krb5.conf
GDMSESSION=gnome
HISTCONTROL=ignoredups
SHLVL=2
HOME=/home/jeg
XDG_SEAT=seat0
GNOME_DESKTOP_SESSION_ID=this-is-deprecated
LOGNAME=jeg
CVS_RSH=ssh
QTLIB=/usr/lib64/qt-3.3/lib
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-FystgbFfv5,guid=d690c61e00dd863462bb62b357c9dcf3
SYS_TYPE=Linux-x86_64
MODULESHOME=/usr/share/Modules
LESSOPEN=||/usr/bin/lesspipe.sh %s
WINDOWPATH=1
XDG_RUNTIME_DIR=/run/user/1000
DISPLAY=:0
SVNROOT=:ext:jgalarowicz@launchmon.svn.sourceforge.net/svnroot/launchmon
QT_PLUGIN_PATH=/usr/lib64/kde4/plugins:/usr/lib/kde4/plugins
DK_NODE=/home/jeg/spack3/spack/share/spack/dotkit/linux-fedora19-x86_64
XAUTHORITY=/run/gdm/auth-for-jeg-1uHA4f/database
COLORTERM=gnome-terminal
BASH_FUNC_module()=() {  eval `/usr/bin/modulecmd sh $*`
}
_=/usr/bin/env


I have no idea, what would cause one file not to compile out of all the packages I can build successfully.

**Comment by jgalarowicz** [comment]
@tgamblin I'm still struggling with this one.  Have you tried "spack install cbtf-krell" on any platforms?  It fails everywhere I try it and I'm stuck.

**Comment by jgalarowicz** [comment]
This one was caused by having an include file named Symbol.h that was satisfied by the Dyninst Symbol.h and not the CBTF include file named Symbol.h.  By placing a full path to the CBTF include we resolved this issue.
