### ISSUE TITLE
Package Tags

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#1456]
Package tags have been proposed as a way to organize packages into groups.

@tgamblin 

> w.r.t. organizing them, I was pondering adding tags (ala gmail) to the packages. It would be easy to implement and would give us a more categorical high level view of the packages themselves. What do people think of that? 
> 
> We'd probably want either another command or another argument for spack list to show this. I was thinking it might be nice if, say, "spack tags" showed total package count, available tags and number of packages with each tag (likely not distinct sets). It would also allow listing the packages with one or more tags. Thoughts? I like this better than strict hierarchical layouts used by things like Gentoo and macports.

@davydden 

> I think tags is a very good idea which would help a lot to organise packages (such as LinearAlgebra, PartialDifferentialEquations). One would need to find a good compromise in "granularity", but that should work. A github issue to discuss and agree with the list of tags which fits the current packages ought to do it.
> 
> Obviously a single package can have several tags attached. One should probably maintain the list of tags somewhere with their description and then force packages to use only those tags.

The purpose of this issue is to assemble input on a set of tags we will use canonically in Spack.  Current suggested tags are:

`
LinearAlgebra: <Any blas/lapack implementation>, eigen, py-numpy
PartialDifferentialEquations: eigen, py-scipy
`

I would suggest some others:

```
Numerical:  scipy,octave
Climate: modele, icebin
Cryosphere: icebin, pism
MolecularDynamics
...other domain-specific stuff...
DomainSpecific: (would subsume Climate, MolecularDynamics, etc)
Storage: netcdf, hdf5, mariadb, etc.
Database: mariadb
GUI: qt,gnome, etc.
Language: python, perl, r, ghc, ruby, etc.
Python,R,Perl, Haskell, Ruby, etc.
Cxx: boost
Compiler: (includes glibc as well)
Utilities: git,curl,elfutils
Typesetting: tex
SystemLibs: openssl, glibc, dbus
Supercomputer: mpi,openmp,slurm
```

Now that I'm thinking this through.... we want not just tags, but a lattice built out of tags and packages.  In layman's terms, this means that Tags can have Tags on them as well.  So... the `Cryosphere` tag would have the `Climate` tag on it.  Anything listing of `Climate` packages would also list `Cryosphere` packages (unless you're looking for packages that explicitly list `Climate`, i.e. they are not transitive).  When you query the lattice, the results should include both tags and packages (unless the user asked for only one type).

Other conventions: package names are always lower case (any violations of this convention in current Spack are subject to change).  Tag names are always upper camel case.

Also, let's make tags always singular.  No plurals.

**Comment by citibeth** [comment]
More suggestions:

1. Membership of a package in various tags would be specified in the `package.py` file.

2. There will be a single `tags.yaml` file specifying legal tags, as well as lattice relationships between those tags.

**Comment by alalazo** [comment]
While i think this is still relevant, there's another bit of discussion in #1526. Just linking for future reference.
