### ISSUE TITLE
mrnet can't detect version error

### ISSUE THREAD

**Issue by jgalarowicz** [LLNL/spack#1459]
When I try to build mrnet with these commands I get the error message that spack can't detect the version of mrnet in https://github.com/dyninst/mrnet.git.
There seems to be a problem with the mrnet package.py file with regards to finding the source code to use for the build.

[jeg@localhost packages]$ spack install mrnet
==> Installing mrnet
==> boost is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/boost-1.61.0-wngezegu6antkdja4gjfuo3h3xec5qpi
==> Error: Couldn't detect version in: https://github.com/dyninst/mrnet.git
==> Error: Installation process had nonzero exit code : 256
[jeg@localhost packages]$ 

spack install mrnet@5.0.1-2
==> Installing mrnet
==> boost is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/boost-1.61.0-wngezegu6antkdja4gjfuo3h3xec5qpi
==> Error: Couldn't detect version in: https://github.com/dyninst/mrnet.git
==> Error: Installation process had nonzero exit code : 256
[jeg@localhost packages]$ 

[jeg@localhost packages]$ spack install mrnet@5.0.1:
==> Installing mrnet
==> boost is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/boost-1.61.0-wngezegu6antkdja4gjfuo3h3xec5qpi
==> Error: Couldn't detect version in: https://github.com/dyninst/mrnet.git
==> Error: Installation process had nonzero exit code : 256
[jeg@localhost packages]$ spack install mrnet@5.0.1-2:
==> Installing mrnet
==> boost is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/boost-1.61.0-wngezegu6antkdja4gjfuo3h3xec5qpi
==> Error: Couldn't detect version in: https://github.com/dyninst/mrnet.git
==> Error: Installation process had nonzero exit code : 256

If I comment out this line, then spack will build the 5.0.1 version by default (spack install mrnet)
version('5.0.1-2', git='https://github.com/dyninst/mrnet.git', commit='20b1eacfc6d680d9f6472146d2dfaa0f900cc2e9')

spack install mrnet@5.0.1 does work though.

**Comment by glennpj** [comment]
This is related to #1346. What is happening is that when the default_fetcher object is parsed it throws an error as it can not determine the version from the git URL. The error is coming from `lib/spack/spack/util/web.py`. The mrnet package has a url and a list_url in the package file which are the conditions to do the check. I think the thing to do is catch that error, print a message, and move on. I will work up a PR for that.

**Comment by glennpj** [comment]
@jgalarowicz 
Can you see if PR #1460 gets things working?

**Comment by jgalarowicz** [comment]
Yes, I will try with #1460 and post result.   Thanks!

**Comment by jgalarowicz** [comment]
Yes,  #1460 resolves the mrnet issue I was seeing.   Thanks!
