### ISSUE TITLE
Package Bug : Latest pkg-config Patch Fails

### ISSUE THREAD

**Issue by xjrc** [LLNL/spack#1461]
Since #1156 was merged, I haven't been able to build `pkg-config` due to patching failures.  Specifically, the `g_date_strftime.patch` patch fails to patch a section of the `glib/glib/gdate.c` file.  I've included the contents of the error file output by `patch` below:

```
--- glib/glib/gdate.c
+++ glib/glib/gdate.c
@@ -2439,6 +2439,9 @@
  *
  * Returns: number of characters written to the buffer, or 0 the buffer was too small
  */
+#pragma GCC diagnostic push
+#pragma GCC diagnostic ignored "-Wformat-nonliteral"
+
 gsize
 g_date_strftime (gchar       *s,
                  gsize        slen,
```

@adamjstewart: Do you have any idea what could be causing this problem?  I created a tentative fix [here](https://github.com/xjrc/spack/commit/23ba2dfbb9ad549a16052b0be5d914dbcd15614c) that circumvents the problem by only applying this patch when GCC@6.1 is used, but it doesn't seem complete to me because this issue seems to be wholly related to patching and not at all to which compiler is used.  If you have any suggestions, I'd be happy to implement and test them out.

**Comment by adamjstewart** [comment]
Hmm, let me take a look. The patch worked for me when I submitted it. Perhaps they patched the source code and re-released it without changing the version.

**Comment by adamjstewart** [comment]
Oh wait, I remember what the problem was here. The original source code has trailing whitespace on those lines, but I think my .gitconfig says to ignore changes to whitespace, so I think that's what the problem is.
