### ISSUE TITLE
I keep being surprised that compilers "global" instead of per-spack tree.

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#1471]
I have multiple copies of the spack repository cloned and keep stepping on my toes, using the compiler from one tree to build things in the others.

I finally realized that compilers do not have to be personal.  Things still seem to work after moving ~/.spack/compilers.yaml to .../etc/spack/compilers.yaml.

Other than needing to be careful to use the '--scope' flag to `spack compiler add` etc..., am I walking in to something unexpected?

**Comment by tgamblin** [comment]
Nope -- the stuff in `etc/` is per-spack.  So this will work fine.

**Comment by hartzell** [comment]
Thanks!
