### ISSUE TITLE
Spack should use checksums (or hashes) when downloading via git

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1475]
When Spack installs a particular git branch or tag, there is no way to ensure that this is indeed the version that the package developer intended. Git supports hashes, and Spack should compare these hashes after downloading a particular version via git.

**Comment by tgamblin** [comment]
Using branches or tags is risky because they can move, and the Spack docs mention this.  You *can* use a checksum by just cloning a particular commit:

    version('abc123', git='<clone url>', commit='abc123')

Then git will verify the SHA for you.

**Comment by eschnett** [comment]
Thanks.
