### ISSUE TITLE
Can't uninstall all packages

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#1477]
I would like to be able to uninstall all packages. The following doesn't work:
```
$ spack uninstall -a
==> Error: uninstall requires at least one package argument.
```

**Comment by adamjstewart** [comment]
P.S.  I know I can manually delete everything and run `spack reindex`. I just think `spack uninstall -a` should be valid.

**Comment by pramodk** [comment]
came across this today, would be nice to have!
