### ISSUE TITLE
Compiler detect not working with Cray wrappers

### ISSUE THREAD

**Issue by robertdfrench** [LLNL/spack#1481]
I think this comes down to a typo somewhere -- spack is attempting to query the version of CC by running `/opt/cray/craype/2.5.4/bin/CC ([Vv]ersion).*(\d+(\.\d+)+)`. I think that argument is a regex that is supposed to be going to a different function call, or perhaps as a different argument in the get_compiler_version method.

To reproduce on Cori, BlueWaters, or Titan, run `compiler find` with -vd.

**Comment by robertdfrench** [comment]
I believe @mpbelhorn had some thoughts on this

**Comment by mpbelhorn** [comment]
I think that there is a missing argument `-V` for the CCE compilers. Also, the environment module name is `cce` on our Crays, not `craype`. I haven't checked if this is true elsewhere.

My branch is not pull-worthy yet, but can be found at https://github.com/mpbelhorn/spack/tree/olcf/correct_cce_compiler_name
```
diff --git a/lib/spack/spack/compilers/craype.py b/lib/spack/spack/compilers/craype.py
index 4ba8b11..030e2ee 100644
--- a/lib/spack/spack/compilers/craype.py
+++ b/lib/spack/spack/compilers/craype.py
@@ -45,7 +45,7 @@ class Craype(Compiler):
     suffixes = [r'-mp-\d\.\d']
 
     PrgEnv = 'PrgEnv-cray'
-    PrgEnv_compiler = 'craype'
+    PrgEnv_compiler = 'cce'
 
     link_paths = { 'cc'  : 'cc',
                    'cxx' : 'c++',
@@ -54,5 +54,5 @@ class Craype(Compiler):
  
     @classmethod
     def default_version(cls, comp):
-        return get_compiler_version(comp, r'([Vv]ersion).*(\d+(\.\d+)+)')
+        return get_compiler_version(comp, '-V', r'[Vv]ersion.*(\d+(\.\d+)+)')
```

**Comment by becker33** [comment]
@mpbelhorn Is this aspect of your branch working? You mentioned your branch isn't pull ready, but is that related to this issue or entirely separate?

**Comment by mpbelhorn** [comment]
@becker33 It appears to work on Titan, but I hadn't testing it on other systems or checked that `cce` is the right name when I posted. It does appear that `cce` is the correct module name on Cori, Titan, Edison, Eos, etc. That branch updates the python module to use the more correct name 'cray' instead of 'craype' for the Cray compiler suite. I've tested it on Titan and it seems OK. @robertdfrench Does this work for you?

**Comment by mpbelhorn** [comment]
It occurs to me the better name is `cce` as that is the name of the module so it follows the other compilers that the `spack compilers` shows the same name used in specs.

**Comment by robertdfrench** [comment]
Ah, I believe I have found a clue. `$MODULEPATH` is getting assembled in such a way that this command:

`modulecmd python avail gcc`

loses its lunch. This prevents the CNL operating system class from finding any modulefiles that look like gcc/1.2.3, because the output from the above modulecmd invocation is just a bunch of path errors. And that is precluding any CNL compilers from being added.

I will put together a patch.
