### ISSUE TITLE
Spack identifies my Linux CentOS as macos

### ISSUE THREAD

**Issue by KineticTheory** [LLNL/spack#1489]
I'm working on a CentOS Linux system that spack thinks is `macos.`  I can't seem to build most packages that I try -- possibly due to this misidentification:

```
% cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

```
% spack compiler info intel@16.0.3
intel@16.0.3:
	cc  = /projects/opt/intel/compilers/compilers_and_libraries_2016.3.210/linux/bin/intel64/icc
	cxx = /projects/opt/intel/compilers/compilers_and_libraries_2016.3.210/linux/bin/intel64/icpc
	f77 = /projects/opt/intel/compilers/compilers_and_libraries_2016.3.210/linux/bin/intel64/ifort
	fc  = /projects/opt/intel/compilers/compilers_and_libraries_2016.3.210/linux/bin/intel64/ifort
	modules  = []
	operating system  = macos
```

You can see that the operating system is identified as **macos**.  The `arch` command reports the same:

```
% spack arch
darwin-macos-x86_64
```

When I try to compile a package (`metis` in the example below), the build fails because the compiler runtime libraries are not found.  

```
% spack install --dirty -v metis%intel@16.0.3
...
[100%] Linking C executable cmpfillin
ld: warning: libimf.so, needed by ../libmetis/libmetis.so, not found (try using -rpath or -rpath-link)
ld: warning: libsvml.so, needed by ../libmetis/libmetis.so, not found (try using -rpath or -rpath-link)
ld: warning: libirng.so, needed by ../libmetis/libmetis.so, not found (try using -rpath or -rpath-link)
ld: warning: libimf.so, needed by ../libmetis/libmetis.so, not found (try using -rpath or -rpath-link)
ld: warning: libintlc.so.5, needed by ../libmetis/libmetis.so, not found (try using -rpath or -rpath-link)
ld: warning: libsvml.so, needed by ../libmetis/libmetis.so, not found (try using -rpath or -rpath-link)
ld: warning: libirng.so, needed by ../libmetis/libmetis.so, not found (try using -rpath or -rpath-link)
ld: warning: libintlc.so.5, needed by ../libmetis/libmetis.so, not found (try using -rpath or -rpath-link)
ld: graphchk: hidden symbol `__intel_cpu_feature_indicator_x' in /projects/opt/intel/compilers/compilers_and_libraries_2016.3.210/linux/ipp/../compiler/lib/intel64/libirc.a(cpu_feature_disp.o) is referenced by DSO
ld: final link failed: Bad value
ld: mpmetis: hidden symbol `__intel_cpu_feature_indicator_x' in /projects/opt/intel/compilers/compilers_and_libraries_2016.3.210/linux/ipp/../compiler/lib/intel64/libirc.a(cpu_feature_disp.o) is referenced by DSO
ld: final link failed: Bad value
make[2]: *** [programs/graphchk] Error 1
```

The above error may or may not be caused by OS misidentification. However, it is my understanding that the `--dirty` option should preserve the full environment (including `LD_LIBRARY_PATH`) and  I can cut&paste the cmake/make commands from spack-build.out and the build works fine. This is why I'm thinking the os identification may be causing my trouble. (I'm using the develop branch from Aug. 9.)

Thoughts?

**Comment by mamelara** [comment]
Interesting find. I'm surprised that spack isn't detecting that you're on linux. It should detect whether you're on a linux machine via 'uname -a' by checking whether linux is in the output string. For macs, we use the same method but check for darwin instead. 

What happens to be the 'uname -a' output for your system?

**Comment by KineticTheory** [comment]
@mamelara After your comment, I think I know what is going on.  This machine's name is **darwin**.

```
% uname -a
Linux darwin-fe1.lanl.gov 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by adamjstewart** [comment]
Hahaha, that's hilarious. We could use `uname` instead of `uname -a` to find the kernel. Or we could only use the first element of `uname -a`.

**Comment by tgamblin** [comment]
@mamelara: can you fix that by just calling Python's [`platform.system`](https://docs.python.org/2/library/platform.html#platform.system) instead of `uname`?  Let Python do the hard part.

**Comment by KineticTheory** [comment]
#1499 resolves this issue.
