### ISSUE TITLE
spack compiler find doesn't pick up new compilers on different OS

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#1492]
When I run `spack compiler find` on CentOS 6, it picks up all of the compilers I want. But when I run the same command on RHEL 5, it doesn't pick up any new compilers. I assume it's because all of the compilers are already in there, just for a different OS. Spack should add the OS to the existing compilers.

**Comment by adamjstewart** [comment]
By the way, it doesn't seem you can list multiple OSes for a single compiler. You need to duplicate the entire yaml section for a different compiler. We should probably allow lists here.

**Comment by becker33** [comment]
This is fixed in the current develop (I don't recall which PR it was, I think #2261 or #2500). Closing as resolved.
