### ISSUE TITLE
gcc/java requires zip

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1501]
Installing gcc on Ubuntu 16.04 system fails unless the `zip` package is installed. Since Spack provides `zip`, `gcc` should depend on `zip` if it builds Java.

**Comment by tgamblin** [comment]
can you add a build dependency?

    depends_on('zip', when='+java')

**Comment by adamjstewart** [comment]
There is no `zip` package in Spack. GCC also doesn't have a `+java` variant.

**Comment by eschnett** [comment]
Oops -- I must have mistaken `zlib` or so for `zip`.

With `+java` I meant the GCC configuration options that enables Java as language. It's listed explicitly in the package source, but indeed not as variant.
