### ISSUE TITLE
Remove binutils 2.26 deprecation

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1506]
Binutils provides version 2.26, but makes version 2.25 the default, with the comment "2.26 is incompatible with py-pillow build for some reason.".

I find that Binutils 2.25 does not build LLVM on Ubuntu 16.04, while Binutils 2.26 is working fine. The problem with version 2.25 is well known; see e.g. <https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=808205>.

If py-pillow requires a specific version of Binutils, then it should describe this in its package.py file instead.

**Comment by adamjstewart** [comment]
Agreed. The problem with binutils may have been resolved in newer versions of py-pillow for all I know. @citibeth You added the binutils dependency to py-pillow. Do you have any comments?

**Comment by citibeth** [comment]
No comments.  I will only know if pypillow breaks in the future.

**Comment by citibeth** [comment]
Inspection of my past builds shows py-pillow building with binutils@2.26.  I don't know where this @2.25 stuff came from, maybe it was a typo on my part.  binutils@2.25 seems to be a dog for so many reasons...
