### ISSUE TITLE
add tags to packages

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#1526]
subj. I would say for starters, one-to-many (one package many tags) without hierarchies of tags is perfectly enough to help users better orient in packages.

As a CLI i think it's enough to have:

```
spack tags                   (show all tags with their short description, two column print out)
spack list --tag=<var>       (show all packages from a tag <var>)
spack find --tag=<var>       (show all installed packages from a tag <var>)
```

Each package declare tags via:

```
tags = one, two, three
```

with some (manual) checks that `one, two, three` are contained in the list of tags stored in `repo.yaml` as a pairs of strings `name - description`.

in reference to the discussion  https://groups.google.com/forum/?fromgroups#!topic/spack/zGs-0RKz3_U

**Comment by alalazo** [comment]
@davydden I think this duplicates @1456, can we close this?

**Comment by davydden** [comment]
sure, i must have missed that one.

**Comment by alalazo** [comment]
@davydden No prob, doing housework today if you didn't notice :smile:

**Comment by davydden** [comment]
I did :smile:
