### ISSUE TITLE
Spack load broken

### ISSUE THREAD

**Issue by ashkan2200** [LLNL/spack#1549]
Hi,
I use spack on OS X 10. 
When I try loading anything, I don't get any errors. However, nothing gets loaded in the environment. 

For instance, if I try 'spack load gcc' and then look at the loaded modules using 'module list' I will not see gcc in that list.

**Comment by davydden** [comment]
Hm, which version are you using?

For me on `macOS 10.11.6` a095fd517f34c9570fd930a7b4819d607593785f works fine:

```
$ spack load gcc
$ module list
Currently Loaded Modulefiles:
  1) gcc-6.1.0-clang-7.3.0-apple-yjkpe3c
```

**Comment by ashkan2200** [comment]
@davydden I use macOS 10.10.5. 
I can directly load modules with `module load ...` but not from spack.

**Comment by ashkan2200** [comment]
Also I have the latest spack source.

**Comment by davydden** [comment]
@ashkan2200 can you check if it works for you with the version i mentioned? Also if `spack module refresh` changes anything?

**Comment by ashkan2200** [comment]
@davydden Ok `spack module refresh` did the trick. Sorry. I didn't find this command earlier. 

Now I have an issue with the external packages command but I'll open another issue.

Thank you.
