### ISSUE TITLE
Document Spack Resources

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#1551]
@tgamblin @alalazo @adamjstewart

I cannot find documentation on Spack resources mechanism at this point.  We need this documentation before it can be considered a feature we wish people to use.

**Comment by citibeth** [comment]
@davydden

**Comment by alalazo** [comment]
@becker33 @tgamblin If you assign this to me (just as a reminder), I'll try to write something up asap. Any preference where to put the docs ?

**Comment by citibeth** [comment]
Thanks! I would suggest putting it as a new section in the Packaging Guide.

**Comment by tgamblin** [comment]
This should probably go in the packaging guide after VCS fetching

**Comment by tgamblin** [comment]
Thanks!

**Comment by alalazo** [comment]
Please tell me if you want something more than what is in #1627

**Comment by citibeth** [comment]
Thank you!

I would want more description of why we use resources, rather than
downloading stuff inside our `install()` method.  I'm happy to see this get
merged as-is and I'll take it from there; can you just confirm these
questions:

1. Am I right that resources, as currently implemented, will work for
systems not connected to the Internet, just like regular tarball downloads
do?
2. And will resource downloads be cached by our new tarball caching
mechanism?

**Comment by tgamblin** [comment]
@citibeth: 

1. Spack checks mirrors for them first, like package tarballs.
1. yes.
