### ISSUE TITLE
preferred=True overrides packages.yaml (and it shouldn't)

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#1556]
Try the following:
1. Clone latest Spack develop.
2. Use the following `packages.yaml`:

```
packages:
    python:
        version: [3.5]
```
1. `spack spec python` yields:

```
  python@2.7.12%gcc@4.8.5~tk~ucs4 arch=linux-centos7-x86_64
```

This is wrong.  `preferred=True` should have the same precedence as one version simply having the highest number.  It is possible to get v3.5 with `spack spec python@3:`

```
python@3.5.2%gcc@4.8.5~tk~ucs4 arch=linux-centos7-x86_64
```

For now, I'm removing `preferred=True` from `python/package.py`.

**Comment by citibeth** [comment]
@tgamblin

**Comment by adamjstewart** [comment]
Looks like this was fixed.

### Before
```
$ spack spec python
...
python@2.7.13%gcc@6.2.1~tk~ucs4 arch=linux-fedora25-x86_64 
```

### After

With a `packages.yaml` like:
```yaml
packages:
    python:
        version: [3.5]
```
I see:
```
$ spack spec python
...
python@3.5.2%gcc@6.2.1~tk~ucs4 arch=linux-fedora25-x86_64 
```
Reopen if you find another way to reproduce the problem.

**Comment by citibeth** [comment]
Yes I fixed it.
