### ISSUE TITLE
Non-numeric version numbers don't work in packages.yaml

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#1557]
I have the following package `ibmisc`:

```
class Ibmisc(CMakePackage):
    """Misc. reusable utilities used by IceBin."""

    homepage = "https://github.com/citibeth/ibmisc"
    url      = "https://github.com/citibeth/ibmisc/tarball/v0.1.0"

    version('0.1.2', '3a6acd70085e25f81b63a7e96c504ef9')
    version('0.1.1', '1bca77795cca96c583dcf75a0c666552')
    version('0.1.0', '058af1c774b5836a1a71fd10611d80b5')

    version('develop',
        git='https://github.com/citibeth/ibmisc.git',
        branch='develop')
...
```

I then add to `packages.yaml`:

```
    ibmisc:
        version: [9999]
        variants: +python +netcdf
```

Now try `spack spec ibmisc`, and I get:

```
ibmisc@0.1.2%gcc@4.8.5+blitz+boost~everytrace+googletest+netcdf+proj+python+udunits2 arch=linux-centos7-x86_64
```

I can work around this by adopting (arcane) conventions that certain numeric version numbers mean certain things.  For example, if I search-and-replace `develop` --> `9999` in the above `package.py` and `packages.yaml`, then `spack spec ibmisc` yields my development version:

```
ibmisc@9999%gcc@4.8.5+blitz+boost~everytrace+googletest+netcdf+proj+python+udunits2 arch=linux-centos7-x86_64
```

**Comment by davydden** [comment]
so you tried 
```
ibmisc:
        version: [develop]
        variants: +python +netcdf
```
and it does not work?

p.s. was not clear from the OP, probably because of the typo.

**Comment by citibeth** [comment]
Yes

**Comment by adamjstewart** [comment]
Maybe this was fixed? I can no longer reproduce this.

### Before
```
$ spack spec bash-completion
...
bash-completion@2.3%gcc@6.2.1 arch=linux-fedora25-x86_64 
```

### After

With a `packages.yaml` like:
```yaml
packages:
  bash-completion:
    version: [develop]
```
I see:
```
$ spack spec bash-completion
...
bash-completion@develop%gcc@6.2.1 arch=linux-fedora25-x86_64 
```
Reopen if you find another way to reproduce it.

**Comment by citibeth** [comment]
Yes I fixed

**Comment by adamjstewart** [comment]
If you have any other open issues that you know are fixed, please close them. It's really hard to keep track of what bugs need to be solved when you have close to 500 open issues 😆
