### ISSUE TITLE
spack view broken because platform.distribution does not grok Amazon linux

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#1560]
I'm using spack on a system based on Amazon Linux.

I built a couple of things successfully and tried to set up a view but it always exited successfully (status = 0) w/out linking anything.

I stuck a bit of debugging code in the view code and saw this:

```
==> Linking package: "tree"
==> foo: /spack/opt/spack/linux-None-x86_64/gcc-4.8.3/tree-1.7.0-xqgjymlch5unsleqou7w3nxvood6qina
```

and/but when I look in the installed stuff I see this:

```
opt/spack/linux--x86_64/gcc-4.8.3/tree-1.7.0-xqgjymlch5unsleqou7w3nxvood6qina/bin/tree
```

Notice that the platforms are different (and both not particularly useful).

This is also a nice test case:

```
[ec2-user@ip-10-0-0-46 spack]$ spack arch
linux--x86_64
```

A bit of digging around and I discovered [this python bug report](https://bugs.python.org/issue18872).

If I take their "advice" and do this:

```
[ec2-user@ip-10-0-0-46 spack]$ git diff
diff --git a/lib/spack/spack/operating_systems/linux_distro.py b/lib/spack/spack/operating_systems/linux_distro.py
index 6d70ae8..7ce3af8 100644
--- a/lib/spack/spack/operating_systems/linux_distro.py
+++ b/lib/spack/spack/operating_systems/linux_distro.py
@@ -13,6 +13,7 @@ class LinuxDistro(OperatingSystem):

     def __init__(self):
         distname, version, _ = py_platform.linux_distribution(
+            supported_dists=['system'],
             full_distribution_name=False)

         # Grabs major version from tuple on redhat; on other platforms
```

Now I get this:

```
[ec2-user@ip-10-0-0-46 spack]$ spack arch
linux-system2016-x86_64
```

Which isn't right but at least it's not the empty string.

If I clean up the old installed things [and also blow away the compilers.yaml file because it contains the incorrect info] and install fresh, I can build a view.

**But**, that os name isn't quite right.

I'm not sure where to take this from here....

For what it's worth, here's the contents of _/etc/os-release_:

```
[ec2-user@ip-10-0-0-46 spack]$ cat /etc/os-release
NAME="Amazon Linux AMI"
VERSION="2016.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2016.03"
PRETTY_NAME="Amazon Linux AMI 2016.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2016.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
[ec2-user@ip-10-0-0-46 spack]$
```

**Comment by tgamblin** [comment]
Fixed by #1629.
