### ISSUE TITLE
numpy dependency problem in Trilinos

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1577]
The Trilinos package contains the comment:
```
    # not everyone has py-numpy activated, keep it disabled by default to avoid
    # configure errors
    variant('python',       default=False, description='Build python wrappers')
```
Later, it specifies a dependency on `python`, but not on `py-numpy`. If Trilinos actually depends on `numpy` when Python is used, then it needs to say so in its dependencies.

**Comment by davydden** [comment]
Would be good if someone who use `python` and `numpy` look at this. I think it was myself who added the comment when extending `trilinos` package a while ago as I had problems building `trilinos`.

**Comment by davydden** [comment]
fixing it...
