### ISSUE TITLE
Trilinos download server down

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1578]
Trilinos cannot be downloaded, the specified server does not respond. This has been the case for more than a week by now.

**Comment by sknigh** [comment]
Why doesn't the package download from the public SNL-managed git repository? 
https://github.com/trilinos/Trilinos/releases

**Comment by tgamblin** [comment]
@davydden

**Comment by davydden** [comment]
> Why doesn't the package download from the public SNL-managed git repository? 

IIRC they name files differently. As a result Spack can't pick up versions from archives. 

for now Homebrew also uses the smae download link as Spack https://github.com/Homebrew/homebrew-science/blob/master/trilinos.rb

**Comment by davydden** [comment]
Looks like Homebrew is moving to Github download https://github.com/Homebrew/homebrew-science/issues/4035, ugly thing is that checksums change. 

Is there a way to pickup versions automatically from https://github.com/trilinos/Trilinos/archive/trilinos-release-12-6-4.tar.gz ?

**Comment by sknigh** [comment]
Github API
https://developer.github.com/v3/

For Trilinos
```
curl https://api.github.com/repos/trilinos/Trilinos/tags
```

Spack would be more useful to me if it had support for scraping Github. I use a lot of FOSS hosted there.

**Comment by davydden** [comment]
testing a patch now...
