### ISSUE TITLE
install_tree is not mentioned in File functions

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#1581]
mention `install_tree` in Packaging guide.

**Comment by davydden** [comment]
FYI, here is a bit more complicated wrapper to native `copy_tree` : http://stackoverflow.com/questions/1868714/how-do-i-copy-an-entire-directory-of-files-into-an-existing-directory-using-pyth .

**Comment by adamjstewart** [comment]
I think we should also add `lib/spack/env` and `lib/spack/llnl` to the API docs. Then users can at least find documentation on `install_tree` there.

**Comment by davydden** [comment]
it's now in LLNL API Docs section http://spack.readthedocs.io/en/latest/llnl.util.html?highlight=install_tree#llnl.util.filesystem.install_tree
