### ISSUE TITLE
Document `depends_on`

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1588]
The documentation of `depends_on` currently reads:

```
spack.depends_on(*args, **kwargs)
Creates a dict of deps with specs defining when they apply.
```

We now have multiple dependency types, and package reviewers insist that they be used properly. Consequently I need these to be documented so that I can do that, instead of using `grep` to look for examples.

**Comment by alalazo** [comment]
Strangely enough I found the docs in a second [here](http://software.llnl.gov/spack/packaging_guide.html?highlight=dependency%20type#dependency-specs)

**Comment by eschnett** [comment]
Maybe all that's missing is a pointer from the reference section to the packaging guide.

(Or maybe the packaging guide part has become too large, and should be split or shrunk, and details moved into the reference manual.)

**Comment by citibeth** [comment]
How is this docstring?

    """Creates a dict of deps with specs defining when they apply.
    This directive is to be used inside a Package definition to declare
    that the package requires other packages to be built first.
    @see The section "Dependency specs" in the Spack Packaging Guide."""

**Comment by eschnett** [comment]
That sounds good!

**Comment by alalazo** [comment]
Already fixed as @citibeth proposed

**Comment by willelm** [comment]
The link above is now broken. Coming back to spack after a hiatus, I see that depends_on has changed and I can't find documentation at readthedocs.

**Comment by tgamblin** [comment]
Bill: was went to readthedocs so the docs stay updated all the time.  Here are the dependency docs: http://spack.readthedocs.io/en/latest/packaging_guide.html#depends-on. Unfortunately, it looks like LLNL's software.llnl.gov is not forwarding to RTD like it used to.
