### ISSUE TITLE
Update documentation of `url_for_version`

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1589]
This function is currently documented as

```
url_for_version(version)
Returns a URL that you can download a new version of this package from.
```

The documentation should state that
- this function is meant to be overloaded in a package
- if so, it should take `self` as first parameter
- the type of the argument `version` is `Version` (is it?)
- a pointer to the documentation of the class `Version`, so that I see what methods it defines

**Comment by citibeth** [comment]
Some of this is really basic Python stuff.  What do you think of the following docstring?

        """Returns a URL from which the specified version of this package
        may be downloaded.

        version: class Version
            The version for which a URL is sought.

        @see Class Version (version.py)
        """
