### ISSUE TITLE
`url_for_version` called with both `Version` and `str` objects

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1591]
While trying to write a `url_for_version` function, I notice that this function is during initialization called multiple times -- sometimes with a `Version` object, sometimes with a `str`.

The work-around is to call `str` on the version object, which then always returns a string.

**Comment by adamjstewart** [comment]
Hmm, but we use `version.up_to(2)` everywhere, which should only work for `Version` objects. The only difference is that `up_to()` is a method and `dashed` is a property. What does the code and error message look like?

**Comment by eschnett** [comment]
The error message was something like `str is not a callable object`. The code was something like `version.up_to(2)`. I tried to introduce two code paths by checking the type via `isinstance`, but that didn't work either.

Maybe I was confused regarding properties and methods, and regarding the error location, and a `version.dashed()` caused the actual error.

Assuming confusion on my side, closing the issue.

**Comment by adamjstewart** [comment]
Yeah, I think the problem is that `version.dashed` is correct and `version.dashed()` is wrong. `dashed` is a property, whereas `up_to()` is a method.
