### ISSUE TITLE
Curl error message should be suppressed while searching cache

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1592]
When Spack looks at the cache and fails to find a package there, it outputs errors like:

```
curl: (37) Couldn't open file /Users/eschnett/src/spack/var/spack/cache/porta/porta-1.4.1.tgz
```

These errors should be suppressed. Only if the subsequent download fails is there a real error.

**Comment by adamjstewart** [comment]
Duplicate of #1274.
