### ISSUE TITLE
Documentation: Title underline too short

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#1605]
In the Basic Usage and Packaging Guide documentation, several section title underlines were too short. This caused warning messages like:
```
basic_usage.rst:1500: WARNING: Title underline too short.

Limitations of Filesystem Views
~~~~~~~~~~~~~~~~~~~~~~~~~~~~          <
```
Aside from the warning message, I don't see any other problems this caused.

This bug was discovered in #1576 by adding documentation testing. It will be fixed in #1576. This issue is being opened to track the problem.

**Comment by adamjstewart** [comment]
With Sphinx, the title underlines need to be at least as long as the title:
http://www.sphinx-doc.org/en/stable/rest.html#sections

While I'm at it, I also want to use the optional overline as I think it helps the titles stand out more when viewing the raw .rst files.

**Comment by EliasOPrado** [comment]
I am having the same issue with `README.rst` in which I have an issue with less `=` characters if compared with the title. I changed and ran the command: `twine check dist/*` but the error still there as same as if there had an cache issue in the id not recognising the changes.

```
`long_description` has syntax errors in markup and would not be rendered on PyPI.
    line 1: Warning: Title overline too short.

    ===================
    Django company project Users Api
    ===================
  warning: `long_description_content_type` missing. defaulting to `text/x-rst`.
```

**Comment by adamjstewart** [comment]
@EliasOPrado this doesn't seem to have anything to do with Spack's documentation, but your issue is pretty easy to solve:

> With Sphinx, the title underlines need to be at least as long as the title:
> http://www.sphinx-doc.org/en/stable/rest.html#sections

**Comment by EliasOPrado** [comment]
Yes, that was the issue. I had to remove the `dist/` folder edit the `README.rsd` file with specified and the error now is gone. Thanks.
