### ISSUE TITLE
Nice Spack

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#1607]
I'm going to suggest that when Spack forks, it runs the child process as "nice" by default.  This will make it play better on shared machines, and have little effect elsewhere.  Any objections?

**Comment by tgamblin** [comment]
Are you suggesting we run them as a particular user, or that we nice them down in priority somewhat, via `os.nice()`?

**Comment by citibeth** [comment]
Just nice it down.  A little background here...

When you move from manual building to Spack building, you hammer (hog) the
CPU a lot more than before.  So... on shared resources where it used to be
perfectly OK to type "configure; make; make install", now sysadmins get
worried when you run "spack install" and it kicks off 24 jobs for an hour.
They suggested I run Spack as a SLURM job, which would not be fun.  So I'd
rather try "nice" and use the '-j' flag (if Spack does that).

I've put "alias spack='nice spack'" in my .bashrc, but that's just one more
thing that has to be done to set up Spack.

-- Elizabeth

**Comment by alalazo** [comment]
> They suggested I run Spack as a SLURM job, which would not be fun

For the record : that's what we do here at EPFL. It works quite fine using a CI framework and parametrized jobs. In the end we just need to select the right backend and give a spec to trigger an installation.

**Comment by tgamblin** [comment]
@citibeth: you probably want to just call something like `os.nice(10)` in `build_environment.fork()`.  Ideally that value would be configurable via a file.

**Comment by tgamblin** [comment]
@alalazo: with the new locking I'm implementing I think it should be relatively straightforward soonish to get a distributed, bottom-up DAG build going in a SLURM environment.

**Comment by citibeth** [comment]
I believe this has been merged...
