### ISSUE TITLE
Documentation: Include file not found or reading it failed

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#1608]
This is the most severe documentation bug I've found so far. In the [Configuration Files section of the Basic Usage documentation](http://software.llnl.gov/spack/basic_usage.html#configuration-files), we are supposed to be reading in Spack's default site configuration file. Sphinx can't find it and issues the warning:
```
basic_usage.rst:1271: WARNING: Include file u'/blues/gpfs/home/software/spack-0.9.1/etc/spack/modules.yaml' not found or reading it failed
```
The problem is that this file was moved from `etc/spack` to `etc/spack/defaults`. The solution is to update the path accordingly.

This bug was discovered in #1576 by adding documentation testing. It will be fixed in #1576. This issue is being opened to track the problem.

**Comment by tgamblin** [comment]
@adamjstewart: thanks for the assiduous issue tracking!
