### ISSUE TITLE
`scorep` does not work on Darwin

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1609]
The Score-P package requires a case-sensitive file system. This is described in the install notes, and I confirmed with the developers. I suggest to disable Score-P on Darwin to avoid others having to track down this problem in the same way I had to. Alternatively, we can add an install-time test whether the build or install directories are on a case-insensitive file system.

**Comment by tgamblin** [comment]
We don't currently have a way to check this before install, but I agree a quick check in `install` would be good.
