### ISSUE TITLE
ADIOS package doesn't declare NetCDF dependency

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1610]
The ADIOS package expects NetCDF to be installed, but doesn't declare it as dependency.

**Comment by tgamblin** [comment]
Are you working on a PR for this?

**Comment by eschnett** [comment]
No, I'm not.

**Comment by ax3l** [comment]
will update that in a sec (is `netcdf` enough or do we need `netcdf-cxx`, `netcdf-cxx4` and `netcdf-fortran` as dependencies, too?).

will also update to ADIOS' `1.10.0` release

**Comment by tgamblin** [comment]
@ax3l: thanks!  Welcome to Spack!

**Comment by ax3l** [comment]
thanks, looking forward to your SC16 tutorial!
