### ISSUE TITLE
Concretizer hangs on unsatisfiable constraints

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#16134]
I found a way to make Spack's concretizer hang.

### Steps to reproduce the issue

First, run `spack edit m4` and change:
```python
depends_on('libsigsegv')
```
to:
```python
depends_on('libsigsegv ^zlib')
```
There is a `when='+sigsegv'` there too, but it appears to be optional when reproducing this bug. 

Then, run `spack spec m4`. Voila!

Of course, `libsigsegv` does not depend on `zlib`, so the expected behavior would be:
```
==> Error: Package libsigsegv does not depend on zlib
```
which is what happens when you perform the same test on the command line.

### Information on your system

* **Spack:** 0.14.2-693-985af94c45
* **Python:** 3.7.6
* **Platform:** darwin-catalina-ivybridge

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
This can be reproduced in b4ea74c Maybe we should not allow the `^` symbol to be used in the first argument of `depends_on`, and sanitize the argument upon the call to the directive. I can't think of a legitimate case where something like:
```console
depends_on('libsigsegv ^zlib')
```
shouldn't be written as:
```console
depends_on('libsigsegv')
depends_on('zlib')
```

**Comment by adamjstewart** [comment]
> I can't think of a legitimate case...

I agree, although my main reason for wanting to support it anyway is so that I can say "`depends_on` supports the same spec syntax you can use on the CLI" and not be wrong.

If we don't support it, then it shouldn't hang, it should at least give some kind of error message.

**Comment by alalazo** [comment]
This doesn't hang with `clingo`, but gives wrong/unexpected results:
```console
$ spack spec m4
Input spec
--------------------------------
m4

Concretized
--------------------------------
m4@1.4.19%gcc@9.4.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-ubuntu20.04-icelake
    ^diffutils@3.9%gcc@9.4.0 build_system=autotools arch=linux-ubuntu20.04-icelake
        ^libiconv@1.17%gcc@9.4.0 build_system=autotools libs=shared,static arch=linux-ubuntu20.04-icelake
    ^libsigsegv@2.14%gcc@9.4.0 build_system=autotools arch=linux-ubuntu20.04-icelake
```
Using 65556eb53e184e78aaacce2a9e325ea4507bca2c

**Comment by adamjstewart** [comment]
I'm fine with closing this as "solved by the new concretizer", we can open a new issue if we're concerned about the new behavior. My main concern was the hanging.
