### ISSUE TITLE
QMCPACK Quantum-ESPRESSO converter moving to Quantum-ESPRESSO package

### ISSUE THREAD

**Issue by naromero77** [LLNL/spack#16223]
@adamjstewart @tgamblin 

This is kind of a draft PR. I thought I would run this by you guys since its the opposite of what we discussed at the outset of ECP. If I don't hear back from you in a couple of days, I will assume that you have no concerns and will proceed with the code changes described below.

The QMCPACK Spack package currently patches Quantum-ESPRESSO (QE) so that QMCPACK can read QE's output. This forms the basis of >80% of the QMCPACK user workflows. So far, we have not succeeded in upstreaming our patch into QE but we would still like to do this envtually. The QMCPACK Spack package currently performs a dependency patching of QE. Unfortunately, the resulting `spack install qmcpack+qe` only consistently works with GCC. A lot of breakage arises from shortcomings in the QE build system. 

I would like to move the QMCPACK-QE converter from QMCPACK Spack package to the QE Spack package -- I would then introduce a new variant and apply the patch the normal way. In on other worlds, I would like to move the equivalent lines of code below:
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/qmcpack/package.py#L162-L172
into the QE Spack package.

This would be much easier for users... it would be two instead of one Spack install invocations, `spack install qmcpack` and `spack install quantum-espresso`, but the probability of those install succeeding with a non-GCC compiler would be higher.  (mostly because I think QE will continue to only be compiled with GCC or the Intel compiler, while QMCPACK can be compiled with at least four compilers). Finally, we would be able to bundle these two science codes in a Spack environment
https://spack.readthedocs.io/en/latest/environments.html

@prckent

**Comment by adamjstewart** [comment]
> I would like to move the QMCPACK-QE converter from QMCPACK Spack package to the QE Spack package -- I would then introduce a new variant and apply the patch the normal way.

What would be the advantage of this?

**Comment by naromero77** [comment]
Best to show with examples:

In principle, this would just work:
`spack install qmcpack+qe%clang ^quantum-espresso%intel`

(note that qmcpack is C++ and quantum-espresso is Fortran)
but getting all the dependencies to actually compile and link correctly with those compilers leads to something that is not very easy for a user to resolve. It ends up being something like:

`spack install qmcpack+qe%clang ^quantum-espresso%intel ^(union of all dependencies between qmcpack and clang that will not compile/link with either clang or intel)%gcc`

The above example is particularly bad. Because both packages depend on HDF5, but one only needs C bindings while the other needs the Fortran bindings. So in principle, all this can be resolved by mixed compiler toolchains, packages.yaml, and setting explicit dependencies but these are complex for a user to set-up.

It far simple for the user to do something like:
`spack install qmcpack%clang`
`spack install quantum-espresso+qmc_converter%intel`

This is far more likely to succeed and if there are dependencies that will not compile with clang and intel, they will be easier to identify.

Here is another example of one that is complicated:
`spack install qmcpack+qe%pgi ^quantum-espresso%intel`
In this case, the problem is that the QE's autoconf detection of PGI has a number of shortcomings and it would just be easier to compile quantum-espresso with the Intel compiler and get it over with than try to fix the PGI issues in QE.

**Comment by adamjstewart** [comment]
> It far simple for the user to do something like:
> ```console
> $ spack install qmcpack%clang
> $ spack install quantum-espresso+qmc_converter%intel
> ```

But won't that cause Spack to try to rebuild `quantum-espresso` with the Clang compiler? Or are you proposing to remove the dependency altogether?

**Comment by naromero77** [comment]
Clang cannot build quantum-espresso at all, since Clang is a C and C++ compiler only (at least for now). You would have to create mixed toolchain with Clang + gfortran in `compilers.yaml`

The first spack install invocation
`spack install qmcpack%clang`
would not have a quantum-espresso dependency at all. The dependency of QMCPACK on QE is not a real dependency in terms of linkage, compiling, or even a runtime dependency. Its a dependency in the overall user workflow to get science calculations done.

**Comment by adamjstewart** [comment]
Ah, I see. In that case, I agree with the approach proposed here. We should remove the dependency from the package if it's not a build/link/run dep, which necessitates moving the patch as well.

**Comment by prckent** [comment]
@naromero77 Since you tagged me above, I'll note that as the QMCPACK PI I'll support whatever gives the best experience for users. As you have outlined here, splitting the dependencies is definitely an improved approach.
