### ISSUE TITLE
Installation issue: visit%gcc: Gcc object has no attribute 'cxx_pic_flag'

### ISSUE THREAD

**Issue by KineticTheory** [LLNL/spack#16227]
### Steps to reproduce the issue

```console
$ spack install visit %gcc@9.2.0
==> Error: AttributeError: 'Gcc' object has no attribute 'cxx_pic_flag'

/ccs/opt/vendors/spack-0.14.2/var/spack/repos/builtin/packages/visit/package.py:75, in cmake_args:
         72            '-DVISIT_VTK_DIR:PATH=' + spec['vtk'].prefix,
         73            '-DVISIT_ZLIB_DIR:PATH=' + spec['zlib'].prefix,
         74            '-DVISIT_USE_GLEW=OFF',
  >>     75            '-DCMAKE_CXX_FLAGS=' + self.compiler.cxx_pic_flag,
         76            '-DCMAKE_C_FLAGS=' + self.compiler.cc_pic_flag,
         77        ]
         78
```

### Information on your system

I'm using `spack-0.14.2`.  `spack debug report` doesn't work.

### Additional information

* No other spackage uses ` self.compiler.cxx_pic_flag`.  This looks like a possible recipe bug.
* No maintainer listed for this package.
* I will try modifying the recipe to use the cmake option `-DCMAKE_POSITION_INDEPENDENT_CODE=ON`.

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files (didn't upload because the build error seems obvious and not related to build environment.  I can add these later if needed.)
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by KineticTheory** [comment]
My suggested change allows cmake to finish, but then I run into a build error.  Here is the recipe diff:

```diff

            '-DVISIT_VTK_DIR:PATH=' + spec['vtk'].prefix,
            '-DVISIT_ZLIB_DIR:PATH=' + spec['zlib'].prefix,
            '-DVISIT_USE_GLEW=OFF',
+           '-DCMAKE_POSITION_INDEPENDENT_CODE=ON'
-           '-DCMAKE_CXX_FLAGS=' + self.compiler.cxx_pic_flag,
-           '-DCMAKE_C_FLAGS=' + self.compiler.cc_pic_flag,
        ]

        if '+python' in spec:
```

The new build error is:

```console
/tmp/kellyt/spack-stage/spack-stage-visit-3.0.1-b2sfhkgvsjshptwkkwajoxq3xrkmygto/spack-src/src/visit_vtk/lightweight/vtkSkewLookupTable.C:69:36: error: invalid conversion from 'const unsigned char*' to 'unsigned char*' [-fpermissive]
   69 |   return this->Superclass::MapValue(temp);
      |          ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
      |                                    |
      |                                    const unsigned char*
make[2]: *** [visit_vtk/lightweight/CMakeFiles/lightweight_visit_vtk.dir/vtkSkewLookupTable.C.o] Error 1
make[2]: *** Waiting for unfinished jobs....
```

I'll upload the build and environment logs.

[spack-build-env.txt](https://github.com/spack/spack/files/4513848/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/4513849/spack-build-out.txt)

**Comment by adamjstewart** [comment]
It appears that you're using the Visit package written after #15474, but you're using Spack core from before #15474, is this correct? If so, don't do that. #15474 modified both core Spack and the packages that use it, so they have to be kept in sync. This is one of the reasons that core Spack and Spack packages are still in the same repo instead of in separate repos.

**Comment by KineticTheory** [comment]
> It appears that you're using the Visit package written after #15474, but you're using Spack core from before #15474, is this correct? If so, don't do that. #15474 modified both core Spack and the packages that use it, so they have to be kept in sync. This is one of the reasons that core Spack and Spack packages are still in the same repo instead of in separate repos.

@adamjstewart I didn't clone spack.  I'm using the 0.14.2 release from this [download link](https://github.com/spack/spack/releases/download/v0.14.2/spack-0.14.2.tar.gz).  It seems that the visit recipe is broken in this release.

**Comment by adamjstewart** [comment]
@KineticTheory I just downloaded the release from that link and the `visit` package uses `self.compiler.pic_flag`, not `self.compiler.cxx_pic_flag`.

**Comment by KineticTheory** [comment]
> @KineticTheory I just downloaded the release from that link and the `visit` package uses `self.compiler.pic_flag`, not `self.compiler.cxx_pic_flag`.

Yep. You are right.  I have so many copies of spack in front of me that I must have looked at the wrong one.  I'm going to close this issue since I've gotten past it.  I may open a new one wrt to the visit build failure.  I'm trying visit@2.13.3 and visit@3.1.1 right now.  Maybe 3.0.1 is just broken for my versions of gcc.
