### ISSUE TITLE
Installation issue: gmp

### ISSUE THREAD

**Issue by KineticTheory** [LLNL/spack#16245]
### Steps to reproduce the issue

```console
$ spack clean -a
$ spack install gmp %gcc@9.2.0

==> 2477: Installing gmp
==> Finding buildcaches in /ccs/opt/vendors/spack.mirror/build_cache
==> Fetching file:///ccs/opt/vendors/spack.mirror/build_cache/linux-rhel7-sandybridge-gcc-9.2.0-gmp-6.1.2-j4rkamfvvdjpmee3cc3f6viqrgefav3t.spec.yaml
curl: (37) Couldn't open file /ccs/opt/vendors/spack.mirror/build_cache/linux-rhel7-sandybridge-gcc-9.2.0-gmp-6.1.2-j4rkamfvvdjpmee3cc3f6viqrgefav3t.spec.yaml
==> Failed to fetch file from URL: file:///ccs/opt/vendors/spack.mirror/build_cache/linux-rhel7-sandybridge-gcc-9.2.0-gmp-6.1.2-j4rkamfvvdjpmee3cc3f6viqrgefav3t.spec.yaml
    Curl failed with error 37
==> Fetching from file:///ccs/opt/vendors/spack.mirror/build_cache/linux-rhel7-sandybridge-gcc-9.2.0-gmp-6.1.2-j4rkamfvvdjpmee3cc3f6viqrgefav3t.spec.yaml failed.
==> Using cached archive: /ccs/opt/vendors/spack.develop/var/spack/cache/_source-cache/archive/52/5275bb04f4863a13516b2f39392ac5e272f5e1bb8057b18aec1c9b79d73d8fb2.tar.bz2
==> Staging archive: /tmp/kellyt/spack-stage/spack-stage-gmp-6.1.2-j4rkamfvvdjpmee3cc3f6viqrgefav3t/gmp-6.1.2.tar.bz2
==> Created stage in /tmp/kellyt/spack-stage/spack-stage-gmp-6.1.2-j4rkamfvvdjpmee3cc3f6viqrgefav3t
==> No patches needed for gmp
==> 2477: gmp: Building gmp [AutotoolsPackage]
==> 2477: gmp: Executing phase: 'autoreconf'
==> 2477: gmp: Executing phase: 'configure'
==> 2477: gmp: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

17 errors found in build log:
     627    /bin/sh ../libtool --mode=compile --tag=CC ../mpn/m4-ccas --m4="m4"
             /ccs/opt/vendors/spack.develop/lib/spack/env/gcc/gcc -c -DHAVE_CON
            FIG_H -I. -I..  -D__GMP_WITHIN_GMP -I.. -DOPERATION_`echo mul_1 | s
            ed 's/_$//'`   -O2 -pedantic -fomit-frame-pointer -m64 -mtune=k8 -m
            arch=k8 -Wa,--noexecstack `test -f 'mul_1.asm' || echo './'`mul_1.a
            sm
     628    /bin/sh ../libtool --mode=compile --tag=CC ../mpn/m4-ccas --m4="m4"
             /ccs/opt/vendors/spack.develop/lib/spack/env/gcc/gcc -c -DHAVE_CON
            FIG_H -I. -I..  -D__GMP_WITHIN_GMP -I.. -DOPERATION_`echo addmul_1 
            | sed 's/_$//'`   -O2 -pedantic -fomit-frame-pointer -m64 -mtune=k8
             -march=k8 -Wa,--noexecstack `test -f 'addmul_1.asm' || echo './'`a
            ddmul_1.asm
     629    libtool: Version mismatch error.  This is libtool 2.4.6, but the
     630    libtool: definition of this LT_INIT comes from libtool 2.4.2.
     631    libtool: You should recreate aclocal.m4 with macros from libtool 2.
            4.6
     632    libtool: and run autoconf again.
  >> 633    make[2]: *** [fib_table.lo] Error 63
     634    make[2]: *** Waiting for unfinished jobs....
```

### Information on your system

```console
 %  spack debug report
* **Spack:** 0.14.2-774-63ff121
* **Python:** 2.7.5
* **Platform:** linux-rhel7-sandybridge
```

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/4518949/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/4518951/spack-build-out.txt)

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by KineticTheory** [comment]
I tracked my build failure down to the package option `force_autoreconf = True`.  Commenting out this line allows me to build again.  This option has been in the `gmp/package.py` for 3 years, so it can't be the source of the real issue. It seems that forcing the reconfigure breaks my build and I don't know why.

Several people have contributed to this package and I am pinging you for help: @adamjstewart @alalazo @michaelkuhn 

Thanks!

**Comment by KineticTheory** [comment]
Now mpfr is refusing to build with the same type of error.

It looks like the package is mixing the use of spack provided libtool (2.4.6) and the system libtool (2.4.2).  Could there be something in the base class for  AutotoolsPackage that has changed?

Adding the following to `packages.yaml` seems to be a functioning work around for now:

```yaml
  libtool:
    version: [2.4.2]
    paths:
      libtool@2.4.2: /usr
    buildable: False
```

[Update] This allowed me to install many packages, but it breaks the `graphviz` build.

**Comment by michaelkuhn** [comment]
gmp builds fine for me, strange. My Spack is a bit more recent, though: 0.14.2-909-6d7daf0de @adamjstewart has done some changes to the autotools machinery a few days ago, so maybe try updating to a more recent snapshot?

**Comment by KineticTheory** [comment]
I'm getting the same issues from today's develop version (hash 42d7fd30c46482fe3d8da1e65301bf5e7da2df6f).  I think the issue is that my OS and system tools are very old.

**Comment by adamjstewart** [comment]
Yes, you can try with or without #15784 and #16132 and make sure neither of those PRs broke anything.

**Comment by KineticTheory** [comment]
@adamjstewart I messed with a fresh spack install and determined that the underlying issue was mixing autotools versions.  I've had a lot of trouble building m4 from scratch and so I was pointing to a very old version on from my OS.  When I reverted to spack-built m4, libtool, etc., everything started working again.
