### ISSUE TITLE
spack arch return nehalem on a broadwell node

### ISSUE THREAD

**Issue by siddsghosh** [LLNL/spack#16265]
The file: spack/lib/spack/llnl/util/cpu/microarchitectures.json has 'aes' in the 'features' field for a broadwell cpu. As we understand this field stands for 'Acceleration for Advanced Encryption Standards' not something we care for. In our checkout we drop this feature and everything seem fine. We were just wondering, would you consider dropping this feature from this file as well ? Otherwise, in our broadwell node we get:
spack arch -t
nehalem
as against
broadwell.

**Comment by alalazo** [comment]
@siddsghosh This is from the GCC manual on broadwell (emphasis mine):
```
broadwell
               Intel Broadwell CPU with 64-bit extensions, MOVBE, MMX, SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2,
               POPCNT, AVX, AVX2, **AES**, PCLMUL, FSGSBASE, RDRND, FMA, BMI, BMI2, F16C, RDSEED, ADCX and PREFETCHW
               instruction set support.
```
That means that `-march=broadwell` allows for AES instructions, so I'd say it's safe to keep AES as a requirement for `broadwell`. Would you mind sharing 1 processor entry of your `proc/cpuinfo` file?

**Comment by alalazo** [comment]
Closing the issue as the question seems answered to me. Feel free to reopen if you think otherwise.
