### ISSUE TITLE
Splitting qt into qt4 and qt5

### ISSUE THREAD

**Issue by mathstuf** [LLNL/spack#163]
Qt4 and Qt5 are sufficiently different that separate packages might make more sense. Almost every package mentioning Qt is basically requiring specific versions of Qt anyways (either transitively or explicitly).

**Comment by tgamblin** [comment]
For other packages we've pretty much decided that in Spack we'll keep them together.  I don't see too much difference between `depends_on('qt@4')` and `depends_on('qt4')`... I guess I could be persuaded but they are pretty separable as-is.  Is there a benefit besides the fact that other package managers separate the versions?

**Comment by mathstuf** [comment]
The only one I can think of is using a Qt4-based build tool which is Qt5-based (for a real-world example, shiboken generates Python bindings and uses Qt4 itself, but the application which uses those bindings might be Qt5-based. Currently, such a setup will fail to concretize due to the conflicting Qt requirements.

Hopefully fixable by future work on #378. I'll close it since other packages have similar problems (Python 2 versus Python 3 comes to mind; compiler requirements might as well).

**Comment by tgamblin** [comment]
@mathstuf: I think we can address this with work on #378.  The concretization rules should probably be made a bit more relaxed for packages that *really* need particular versions of build tools when unrelated sub-DAGs use some *other* version of the build tool.  That is hardly a common case though :smile:
