### ISSUE TITLE
Documentation: `spack test operating_system` crashes

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#1631]
When trying to import all of the Python packages for docstring documentation, Sphinx issues the following error message:
```
spack.test.rst:201: WARNING: autodoc: failed to import module u'spack.test.operating_system'; the following exception was raised:
Traceback (most recent call last):
  File "/blues/gpfs/home/software/spack-0.9.1/opt/spack/linux-centos6-x86_64/gcc-6.1.0/python-2.7.12-g5ik6qb4hhhjye4gefrnxmbljjvot7wg/lib/python2.7/site-packages/Sphinx-1.4.5-py2.7.egg/sphinx/ext/autodoc.py", line 518, in import_object
    __import__(self.modname)
  File "/blues/gpfs/home/software/spack-0.9.1/lib/spack/spack/test/operating_system.py", line 30, in <module>
    from spack.platforms.cray_xc import CrayXc
ImportError: No module named cray_xc
```
Recently, the cray_xc.py file was renamed to cray.py. The import statement in operating_system.py wasn't updated to reflect this.

This bug was discovered in #1576 by adding documentation testing. It will be fixed in #1576. This issue is being opened to track the problem.

**Comment by adamjstewart** [comment]
Also, these tests weren't even being run because it wasn't included in `__init__.py`. I'll add them and make sure they work on Linux. We should check that they work on other OSes.

**Comment by adamjstewart** [comment]
Ok, this might have been over my head. I added `operating_system` to `test_names` in `__init__.py` but now I'm getting the following error:
```
$ spack test operating_system
spack.test.operating_system
==> Running test: operating_system
E
======================================================================
ERROR: Failure: AttributeError ('module' object has no attribute 'operating_system')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/blues/gpfs/home/software/spack-0.9.1/lib/spack/external/nose/loader.py", line 407, in loadTestsFromName
    module = resolve_name(addr.module)
  File "/blues/gpfs/home/software/spack-0.9.1/lib/spack/external/nose/util.py", line 322, in resolve_name
    obj = getattr(obj, part)
AttributeError: 'module' object has no attribute 'operating_system'

----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)
==> Tests Complete.
      1 tests run
      0 failures
      1 errors
==> FAIL
```
What else is involved in adding a new test? @alalazo @becker33

**Comment by adamjstewart** [comment]
@mamelara You wrote this file right?

**Comment by tgamblin** [comment]
@adamjstewart: that looks like a circular import error.

**Comment by adamjstewart** [comment]
@tgamblin Any idea which import statement needs to go? Otherwise I just won't add the test.

**Comment by adamjstewart** [comment]
Found another bug:
```
spack.test.rst:201: WARNING: autodoc: failed to import module u'spack.test.operating_system'; the following exception was raised:
Traceback (most recent call last):
  File "/blues/gpfs/home/software/spack-0.9.1/opt/spack/linux-centos6-x86_64/gcc-6.1.0/python-2.7.12-g5ik6qb4hhhjye4gefrnxmbljjvot7wg/lib/python2.7/site-packages/Sphinx-1.4.5-py2.7.egg/sphinx/ext/autodoc.py", line 518, in import_object
    __import__(self.modname)
  File "/blues/gpfs/home/software/spack-0.9.1/lib/spack/spack/test/operating_system.py", line 33, in <module>
    from spack.operating_system.linux_distro import LinuxDistro
ImportError: No module named operating_system.linux_distro
```
This time there actually is an `operating_system/linux_distro.py`. But the `__init__.py` file in that directory is blank. Is it supposed to be?

**Comment by mamelara** [comment]
Apologies. These tests look old and should be updated.

**Comment by mamelara** [comment]
Oh, also I think it might be spack.operating_system**s**. With an S. Might be causing the error?

**Comment by adamjstewart** [comment]
@mamelara There definitely is a missing S. I tried adding it but I still see the same error message. Maybe there's also a circular import error? That empty `__init__.py` is definitely sketchy.

Anyway, it's holding up completing my #1576 PR and I can't figure out what's wrong with it. If you could debug it and submit a PR, I can merge that into #1576. Otherwise, I'm just going to delete the file because it's not being run currently anyway.

**Comment by tgamblin** [comment]
@mamelara: it looks like the test is kind of old and never actually evolved with the code.  I'm going to remove it -- can you add back a working version/

**Comment by tgamblin** [comment]
I think this resolves the issue.

**Comment by adamjstewart** [comment]
Found one more bug from this. The `cray_xc.pyc` file was still left over, which caused problems for me. I added it to the list of orphaned pyc files in `bin/spack` in #1576.
