### ISSUE TITLE
Documentation: Don't parse command output as shell script

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#1634]
Throughout the documentation, we display examples of Spack command output. This usually includes a sample Spack command and several lines of formatted output or error messages and how to prevent them. In the .rst files, we tell Sphinx to lex this as shell script, despite the fact that there is no shell script present. Normally this is fine, and Sphinx won't do any syntax highlighting except for a couple numbers being a different color. But sometimes this generates warning messages:
```
basic_usage.rst:1801: WARNING: Could not lex literal_block as "sh". Highlighting skipped.
```
The solution is to specify a language of "none" for these code blocks since there is no code being displayed. They will still be formatted in code blocks, but there won't be any attempts at syntax highlighting.

This bug was discovered in #1576 by adding documentation testing. It will be fixed in #1576. This issue is being opened to track the problem.

**Comment by adamjstewart** [comment]
I also noticed that a lot of inline code, such as `spack install mpileaks` used single backticks instead of double backticks. In reStructuredText, single backticks means _italic_ and double backticks means `code`. I'm fixing these mistakes as well.

**Comment by adamjstewart** [comment]
Whoa, turns out Sphinx has a specific language lexer for [console sessions](http://build-me-the-docs-please.readthedocs.io/en/latest/Using_Sphinx/ShowingCodeExamplesInSphinx.html#pygments-lexers)! I'm going to use `console` instead of `sh` because that's what it actually is. Maybe it will format it nicely.

**Comment by tgamblin** [comment]
is this done?

**Comment by adamjstewart** [comment]
Yes, this has been added to PR #1576.
