### ISSUE TITLE
New Package: git-lfs

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/spack#1636]
Has anyone ever looked at adding a [git-lfs](https://git-lfs.github.com) package?

Specifically, for the client side support. This is a missing piece for LLNL LC users that might be thinking about using BitBucket's Git LFS support.

**Comment by davydden** [comment]
judging from Homebrew's formula https://github.com/Homebrew/homebrew-core/blob/master/Formula/git-lfs.rb , it should be extremely straight-forward to compile.
