### ISSUE TITLE
Installation issue: petsc

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#16374]
Trying to build `petsc@3.13.0` using gcc@7.3.0 fails on x86_64 for:
* Ubuntu 18.04
* RHEL 7, RHEL 8

Using `spack@develop`, commit `b6b44948b86` from Wed, Apr 29, 2020.

It is failing during configure phase with the following message:
```
*******************************************************************************
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
--with-hdf5-dir=/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.3.0/hdf5-1.10.6-fmakhotquabwy24zyn4kfzi53mtlsl3l did not work
*******************************************************************************
```

[configure.log](https://github.com/spack/spack/files/4553113/configure.log)
[spack-build-out.txt](https://github.com/spack/spack/files/4553114/spack-build-out.txt)

@balay @germasch @BarrySmith @jedbrown

**Comment by balay** [comment]
Likely due to change in d9992a778faa6688143a537d802b3078416c0a7a

To work arround : 
`spack install petsc ^hdf5+hl+fortran`

**Comment by eugeneswalker** [comment]
That worked for me. Thank you! If `petsc` in fact depends on `hdf5+hl+fortran` -- why does the package recipe for `petsc` not state this explictly?

**Comment by balay** [comment]
@eugeneswalker please try the fix in `balay/petsc-update-hdf5-check` and see if this works

**Comment by eugeneswalker** [comment]
> @eugeneswalker please try the fix in `balay/petsc-update-hdf5-check` and see if this works

This worked! Thanks!
