### ISSUE TITLE
Installation issue: py-configobj

### ISSUE THREAD

**Issue by elleryames** [LLNL/spack#16407]
### Issue
Installation fetches version 5.0.6 and fails with a ChecksumError: 

> Error: ChecksumError: sha256 checksum failed for /tmp/user/spack-stage/spack-stage-py-configobj-5.0.6-6uaczs2kvvkt6uh2hqiqnetlbrbkiqaz/v5.0.6.tar.gz
    Expected a2f5650770e1c87fb335af19a9b7eb73fc05ccf22144eb68db7d00cd2bcb0902 but got 2e140354efcca6f558ff9ee941b435ae09a617bc071797bef62c8d6ed2033d5e

### Steps to reproduce the issue

```console
$ spack install py-configobj
```

### Information on your system

* **Spack:** 0.14.2-828-f20202387
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-zen2

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
@Sinan81 I believe you wrote this package. Can you take a look? This is why I prefer to download Python packages from PyPI, where the checksum can't change like on GitHub.

**Comment by elleryames** [comment]
Would either editing the package file or installing with no-checksum be a viable work-around?

**Comment by Sinan81** [comment]
Sorry, just saw the discussion thread.

@elleryames you can install without checksum like
```
spack install --no-checksum py-configobj
```

**Comment by Sinan81** [comment]
@adamjstewart this package name rings a bell. I remember experiencing some issues with the version at pypi. Let me take a look at it.

**Comment by Sinan81** [comment]
From the corresponding PR https://github.com/spack/spack/pull/12639

> Turns out v 5.0.6 on PyPi was outdated (although the version number is same as the latest release github which is absolutely confusing). Neither version 4.7.2 nor v 5.0.6 on github depends on setuptools, hence mystery is solved.

**Comment by elleryames** [comment]
@Sinan81 Thanks for this. Yeah, I looked more into the configobj package and it seems the maintainers of the project must be busy with other things and have neglected it. There are many people calling for an updated PyPi version (last released 2014).
