### ISSUE TITLE
Proper way to add a Ruby Package

### ISSUE THREAD

**Issue by DiegoMagdaleno** [LLNL/spack#16421]
So I wanted to add a Ruby Package, more precisely, [Cocoapods](https://cocoapods.org) but, I can't find proper documentation on how to make properly package a ruby gem, what would be the official way to do it?.

**Comment by adamjstewart** [comment]
#3127 started work on a `RubyPackage` base class, but it's pretty out-of-date by now. If you want to try again I will be happy to review, although I don't know much about Ruby gems.

**Comment by rodent5** [comment]
woeis @DiegoMagdaleno droem gone
