### ISSUE TITLE
Documentation: Invalid signature for automodule

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#1642]
Does anyone know what this means or how to fix it?
```
spack.cmd.rst:249: WARNING: invalid signature for automodule (u'spack.cmd.package-list')
spack.cmd.rst:249: WARNING: don't know which module to import for autodocumenting u'spack.cmd.package-list' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
spack.cmd.rst:345: WARNING: invalid signature for automodule (u'spack.cmd.test-install')
spack.cmd.rst:345: WARNING: don't know which module to import for autodocumenting u'spack.cmd.test-install' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
spack.cmd.rst:385: WARNING: invalid signature for automodule (u'spack.cmd.url-parse')
spack.cmd.rst:385: WARNING: don't know which module to import for autodocumenting u'spack.cmd.url-parse' (try placing a "module" or "currentmodule" directive in the document, or giving an explicit module name)
```

**Comment by tgamblin** [comment]
That is sphinx complaining that those commands' names contain `-`, which isn't legal in python identifiers (e.g., module names).  Spack allows dashes in module names, and Python is ok with it... it just means you can't import a command with a native Python `import` statement.  e.g.:

```
>>> [c for c in dir(spack.cmd) if '-' in c]
['package-list', 'test-install', 'url-parse']
```

I guess we could make Sphinx happy by renaming the files to use `_` and converting the `_` to `-` when the command is registered with the parser in the `bin/spack` script.  I don't see any real disadvantage to that.  

Package names are the other place this happens in Spack.  e.g., you can have a package called `py-foo`.  I'd rather not make a change to the way repo layouts and naming work, as I think keeping that simple is important.  You're not parsing docs or anything for the packages, are you?

**Comment by adamjstewart** [comment]
> You're not parsing docs or anything for the packages, are you?

@tgamblin The docstrings of every package are parsed just to create http://software.llnl.gov/spack/package_list.html, but I don't see any complaints with this yet.

**Comment by tgamblin** [comment]
@adamjstewart: that's ok b/c it uses a different mechanism to load the packages.   When `sphinx`spiders the code, it's going through regular python import, but `spack package-list` goes through `spack.repo.all_packages()`, which uses the repo loading mechanism.

**Comment by adamjstewart** [comment]
@tgamblin I renamed the files to use _ instead of -. Now, as far as Spack is concerned, the commands are named with underscores. I'm not sure exactly what you want me to edit in `bin/spack`. Is there a reason we can't just rename the commands with underscores?

**Comment by adamjstewart** [comment]
I noticed `test_install.py` contains a line:
```
# The use of __import__ is necessary to maintain a name with hyphen (which      
# cannot be an identifier in python)                                            
test_install = __import__("spack.cmd.test-install", fromlist=['test_install'])
```
I assume this can be removed now.

**Comment by adamjstewart** [comment]
Alright, this is now fixed in 601db61. Let me know if there's anything else that needs to be done. It passes `spack test` and fixes the documentation problem.

**Comment by tgamblin** [comment]
@adamjstewart: 
> @tgamblin I renamed the files to use _ instead of -. Now, as far as Spack is concerned, the commands are named with underscores. I'm not sure exactly what you want me to edit in bin/spack. Is there a reason we can't just rename the commands with underscores?

I don't like underscores and don't want them in any command names/options. 😄 Why require the extra shift just to get the docs right?  That would be favoring an implementation detail over usability.  Also if you `man` `ls`, `git` or any other typical unix command, the options all use `-`, not `_`.

I was saying that if you change the filenames to use `_` (which is reasonable for docs), you should also do this in `bin/spack`, which solves both problems:

```diff
  import spack.cmd
  for cmd in spack.cmd.commands:
      module = spack.cmd.get_module(cmd)
+     cmd_name = cmd.replace('_', '-')
-      subparser = subparsers.add_parser(cmd, help=module.description)
+     subparser = subparsers.add_parser(cmd_name, help=module.description)
      module.setup_parser(subparser)
```

**Comment by adamjstewart** [comment]
@tgamblin 
```console
$ spack package-list
Traceback (most recent call last):
  File "/soft/spack-0.9.1/bin/spack", line 192, in <module>
    main()
  File "/soft/spack-0.9.1/bin/spack", line 167, in main
    command = spack.cmd.get_command(args.command)
  File "/blues/gpfs/home/software/spack-0.9.1/lib/spack/spack/cmd/__init__.py", line 89, in get_command
    return getattr(get_module(name), get_cmd_function_name(name))
  File "/blues/gpfs/home/software/spack-0.9.1/lib/spack/spack/cmd/__init__.py", line 74, in get_module
    level=0)
ImportError: No module named package-list
```

**Comment by adamjstewart** [comment]
I think I need to do the same thing in `get_module` for `lib/spack/spack/cmd/__init__.py`. Let me try it out.

**Comment by tgamblin** [comment]
@adamjstewart: you need to handle the call to `get_command`:

```
command = spack.cmd.get_command(args.command)
```

`args.command` now needs to be the module name (with `_`, not `-`).  Or we could simplify things and just hide the `_`/`-` stuff all inside of `spack.cmd`.

**Comment by adamjstewart** [comment]
Ok, that seems to be working

**Comment by adamjstewart** [comment]
Alright, 7d5f215 passes `spack test`, `run-doc-tests`, and looks right from a UI and help message standpoint. Can you take a look at #1641? That's the last error message I have to solve.
