### ISSUE TITLE
Spack Environments w/ View and py-jupyter

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#16451]
I built my environment, and it gave the following error at the end of the `env install` process.  Although I don't use `py-jupyter` directly, it *is* part of this env:

```
==> Updating view at /Users/eafischer2/spack/var/spack/environments/pismip6-catalina/.spack-env/view
==> Error: [Errno 2] No such file or directory: '/Users/eafischer2/spack/var/spack/environments/pismip6-catalina/.spack-env/view/bin/jupyter-run'
```

### Information on your system

See attached `spack.lock` describing my environment.

[spack.lock.txt](https://github.com/spack/spack/files/4575685/spack.lock.txt)

**Comment by adamjstewart** [comment]
What happens when you run:
```console
$ cd /Users/eafischer2/spack/var/spack/environments/pismip6-catalina
$ rm -rf .spack-env spack.lock
$ spack install
```
I've noticed a lot of little bugs with Spack Environments that require me to blow away the environment and start over. I've never successfully installed an environment, updated a package, then reinstalled the environment without having to jump through this hoop.

**Comment by citibeth** [comment]
Yes then it worked its way out.

**Comment by adamjstewart** [comment]
@tgamblin I added this to the TODO list for the next release since I encounter this problem very regularly.

**Comment by becker33** [comment]
@adamjstewart I'm moving this to the next patch release, since we're trying to put out a release this week and I'm focused on features for the first release of the new major series (v0.15.0). This is moving to v0.15.1.

**Comment by alalazo** [comment]
Closing, since environment seem to be more stable than they used to be :slightly_smiling_face:
