### ISSUE TITLE
Installation issue: unifyfs

### ISSUE THREAD

**Issue by scottwittenburg** [LLNL/spack#16487]
After #16458 (which marked `argobots` 1.0 as preferred) was merged, we can no longer concretize the `unifyfs` package.  The `unifyfs` package depends indirectly on `argobots` through it's `margo` dependency.

To reproduce the issue, on either linux or osx, just attempt to concretize the `unifyfs` package using `spack spec unifyfs`:

```
$ spack spec unifyfs
Input spec
--------------------------------
unifyfs

Concretized
--------------------------------
==> Error: Invalid Version range: 1.0rc1:1.0
``` 

Tagging maintainers from `spack blame argobots`:

@shintaro-iwasaki @roblatham00 @tgamblin @dorier @raffenet

**Comment by scottwittenburg** [comment]
fyi @eugeneswalker

**Comment by mdorier** [comment]
The margo package should be updated to depend on argobots@1.0 instead of rc1.

**Comment by scottwittenburg** [comment]
Yeah, that did it.  Thanks @mdorier!
