### ISSUE TITLE
Installation issue: ncurses@5.9

### ISSUE THREAD

**Issue by vvolkl** [LLNL/spack#16506]
### Steps to reproduce the issue

```console
$ spack install ncurses@5.9
...
```

### Information on your system

* **Spack:** 0.14.2-998-b196e43
* **Python:** 2.7.5
* **Platform:** linux-centos7-broadwell

### Additional information

```
 -I../../ncurses/../include -I/home/vavolkl/spack/opt/spack/linux-centos7-broadwell/gcc-8.3.0/ncurses-5.9-ixqhwqbfooygj5brj4rhq6nyz2nfsa3q/include -O2 --param max-inline-insns-single=1200 -fPIC -c ../../ncurses/base/lib_getch.c -o ../obj_s/lib_getch.o
In file included from ../../ncurses/curses.priv.h:283,
                 from ../ncurses/lib_gen.c:19:
_10307.c:835:15: error: expected ')' before 'int'
../include/curses.h:1594:56: note: in definition of macro 'mouse_trafo'
 #define mouse_trafo(y,x,to_screen) wmouse_trafo(stdscr,y,x,to_screen)
                                                        ^
make[1]: *** [../obj_s/lib_gen.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory `/tmp/vavolkl/spack-stage/spack-stage-ncurses-5.9-ixqhwqbfooygj5brj4rhq6nyz2nfsa3q/spack-src/build_ncurses/ncurses'
make: *** [all] Error 2
```

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [ ] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
Trying to assess priority of this build error. Is there any package that constrains `ncurses` to version `5.9`?

**Comment by vvolkl** [comment]
I encountered this setting the version manually while debugging an unrelated error, a quick `grep` search of the builtin repo only brings up `hstr` with a constraint of `ncurses@:5.99.99`.
