### ISSUE TITLE
Container, spack and conflicts with the host's python

### ISSUE THREAD

**Issue by healther** [LLNL/spack#16508]
I'm not completely sure if this should be considered a bug in spack or whether the use case below is too strange.

We deploy the software we depend on in singularity containers containing different apps (for different use cases). In the last update of the base image we moved to python3-providing one, this exposed the following problem:

```
$ singularity shell --app simulation /containers/testing/c7215p26_2020-05-06_1.img
Singularity c7215p26_2020-05-06_1.img:~> . /opt/init/spack.sh 
Fatal Python error: initfsencoding: Unable to get the locale encoding
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00007f3ce89d8740 (most recent call first):
```

The reason for this is a combination of
- the `spack` binary preferring `python3` unconditionally
- our app setting `PYTHONHOME` 

unsetting `PYTHONHOME` solves the problem. But as we need this, we have a couple of options to solve this problem:
- hiding the python3 binary in the app via adding a `python3 -> python2` symlink
- patching the spack binary to override the automatic detection via an environment variable

The latter looks like adding
```
if [ -n "${SPACK_PYTHON_BINARY+x}" ]; then
    exec ${SPACK_PYTHON_BINARY} $0 "$@"
fi
```
before the auto detection in the special no-op things. This overrides the automatic detection by a magic environment variable, which we would set in the app. Is this something you would consider adding to upstream spack? (Naming and things are obviously up for changes)

**Comment by healther** [comment]
FYI: This it how it looks https://github.com/electronicvisions/spack/commit/6a7ea1580f388a588ff676cbf852b1307d8a82bf
I can make a PR from this commit

**Comment by alalazo** [comment]
> our app setting PYTHONHOME

I think this is a problem of the `app` more than of Spack, or am I missing something? Also, there's already a way of forcing the use of a particular python interpreter with Spack:
```console
$ python2 $SPACK_ROOT/bin/spack ...
```
so I don't see a case for allowing an override by an environment variable.

**Comment by alalazo** [comment]
Also, is this container related at all? If the `app` sets the wrong `PYTHONHOME` I assume it will break also outside of a container, right?

**Comment by healther** [comment]
I _thought_ `PYTHONHOME` is the way to go when you want to use a non-standard installation path for the default `python` binary [doc](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHOME). Since we try to overwrite all system-provided installations, I _think_ our usage of setting `PYTHONHOME` is correct, at least in so far as we want to point our `python{,2,3}` binary to the view when looking for standard libraries.

The problem comes when the view only provides a `python` and a `python2` binary and the host system provides a `python3` binary. But you are right it is not necessarily container related. You would see the same "problem" when trying to use a python2-based environment, when the OS provides a python3 binary (provided you'd set `PYTHONHOME` to make the `python2` binary look in the view before looking in `/usr/local/lib/`).

Explicitly prefixing `python2` somewhat breaks the user experience when using spack (for us: inside the container), so I think we will keep our workaround for now. At the same time I think it is fine to keep this as "won't fix".
