### ISSUE TITLE
gcc and open foam install conflicting mpfr packages

### ISSUE THREAD

**Issue by alansill** [LLNL/spack#16538]
/home/asill/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.0/mpc-1.1.0-6utlrx5ydo6c4gvfcync2naozmza6hjh
==> 183004: Installing gcc
==> Using cached archive: /home/asill/spack/var/spack/cache/_source-cache/archive/71/71e197867611f6054aa1119b13a0c0abac12834765fe2d81f35ac57f84f742d1.tar.xz
==> Staging archive: /tmp/asill/spack-stage/spack-stage-gcc-9.3.0-5abm3xgixzmahrtwe27z2zgopjx3iju7/gcc-9.3.0.tar.xz
==> Created stage in /tmp/asill/spack-stage/spack-stage-gcc-9.3.0-5abm3xgixzmahrtwe27z2zgopjx3iju7
==> Ran patch() for gcc
==> 183004: gcc: Building gcc [AutotoolsPackage]
==> 183004: gcc: Executing phase: 'autoreconf'
==> 183004: gcc: Executing phase: 'configure'
==> 183004: gcc: Executing phase: 'build'
==> 183004: gcc: Executing phase: 'install'
==> 183004: gcc: Successfully installed gcc
  Fetch: 0.47s.  Build: 24m 46.79s.  Total: 24m 47.26s.
[+] /home/asill/spack/opt/spack/linux-centos7-broadwell/gcc-7.3.0/gcc-9.3.0-5abm3xgixzmahrtwe27z2zgopjx3iju7
==> Updating view at /home/asill/spack/var/spack/environments/openfoam-gcc-7-3-0/.spack-env/view
==> Error: [/home/asill/spack/var/spack/environments/openfoam-gcc-7-3-0/.spack-env/view] Package conflict detected:
   (Linked) mpfr@4.0.2%gcc@7.3.0 patches=8f15fd27ab65341a60d724d594897d32f4597ddf642d0dc121995e2150181b0c arch=linux-centos7-broadwell/7a72fyr
(Specified) mpfr@3.1.6%gcc@7.3.0 patches=7a6dd71bcda4803d6b89612706a17b8816e1acd5dd9bf1bec29cf748f3b60008 arch=linux-centos7-broadwell/nyiycqa

**Comment by alansill** [comment]
Command was spack install -j 18 mpfr@4.0.2 gcc@9.3.0 openfoam +paraview+vtk+zoltan ^mpi

Same result if I leave off the "mpfr@4.0.2" which was just added to try to avoid the conflict.

**Comment by adamjstewart** [comment]
Can you share your environment file? I think you need to add:
```yaml
concretization: together
```
in order for them to take each other into account.

**Comment by alansill** [comment]
Closing this now to try a more comprehensive approach.
