### ISSUE TITLE
Installation issue: gcc

### ISSUE THREAD

**Issue by sjpb** [LLNL/spack#16623]
### Steps to reproduce the issue

```console
spack install gcc@10

...
==> 44767: Installing gcc
==> Warning: There is no checksum on file to fetch gcc@10 safely.
==>   Fetch anyway? [y/N] y
==> Fetching with no checksum.
  Add a checksum or use --no-checksum to skip this check.
==> Fetching https://ftpmirror.gnu.org/gcc/gcc-10/gcc-10.tar.xz

curl: (22) The requested URL returned error: 404 Not Found
==> Failed to fetch file from URL: https://ftpmirror.gnu.org/gcc/gcc-10/gcc-10.tar.xz
    URL https://ftpmirror.gnu.org/gcc/gcc-10/gcc-10.tar.xz was not found!
==> Fetching from https://ftpmirror.gnu.org/gcc/gcc-10/gcc-10.tar.xz failed.
==> Cannot find version 10 in url_list
==> Error: FetchError: All fetchers failed for spack-stage-gcc-10-j36mzxjvostks5ggr42hislh2w4ndueb
```

Same for `gcc@9`, `gcc@5` too at least.

### Information on your system

```shell
-bash-4.2$ spack debug report
* **Spack:** 0.14.2-1100-043d507
* **Python:** 3.6.8
* **Platform:** linux-centos7-broadwell
```

### General information

@michaelkuhn

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by sjpb** [comment]
I should mention that I checked in the browser and that address fails too. So hopefully it's not just a network issue my end!

**Comment by michaelkuhn** [comment]
`@10` is not a valid version, `@10.1.0` is. Something like `@10:` should also work.

**Comment by sjpb** [comment]
Doh. Many thanks.
