### ISSUE TITLE
Fix `spack load --dependencies`

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#1662]
`basic_usage.rst` claims:

```
Modules may be loaded recursively with the ``load`` command's
``--dependencies`` or ``-r`` argument:

.. code-block:: sh

    $ spack load --dependencies <spec> ...
```

This is incorrect.  `spack module loads` has the recursive feature, but not `spack load`.  We should upgrade `spack load` with this feature.

**Comment by alalazo** [comment]
@citibeth `spack load` is an alias for `module load` set when you source `share/spack/setup-env.sh`. I think it would be difficult to add this feature there. Besides you can generate modules that load their dependencies automatically.

**Comment by tgamblin** [comment]
@alalazo: I don't think it would actually be that hard to add this to the shell function, or to make `spack load` call `spack module loads`.  `spack load` already calls `spack location -m` to get the module location.

But then again I'm a little curious why @citibeth's module configuration doesn't load the right things recursively.  @citibeth: Is that intentional or is that something you tried that didn't work?

**Comment by citibeth** [comment]
I installed `environment-modules`, which I believe does not do recursive
loading.  What is the recommend way these days?  No, I don't want to use
Lmod (our center doesn't use it, and it's more complex to get installed).

**Comment by alalazo** [comment]
@citibeth neither of the tools does recursive loading by default: it's spack that can write module files that are able to load dependencies automatically. Lmod does hierarchical loading, which basically prevents users from loading more than one compiler / mpi at a time (but that's another story).

**Comment by tgamblin** [comment]
But both *can* recursively load prereqs. I think writing the prereqs into the module file is better than having two commands.

This is kind of documented -- there is a note on it but not an example in the [modules docs](http://spack.readthedocs.io/en/latest/module_file_support.html#using-module-files-via-spack)

@alalazo: is it just a matter of adding `prerequisites=True`?  Should prereqs be on by default?

**Comment by alalazo** [comment]
@tgamblin I think the line you are searching is [this](http://spack.readthedocs.io/en/latest/module_file_support.html#autoload-dependencies). I didn't advertise a lot `prerequisites` because it maps to [prereq](http://modules.sourceforge.net/man/modulefile.html) which I don't find super-useful: the tool will start complaining until you load manually every dependency listed.

**Comment by citibeth** [comment]
OK, I see the docs ("Autoload dependencies"):
http://spack.readthedocs.io/en/latest/module_file_support.html#configuration-in-modules-yaml

I'm not quite sure what `autoload=direct` vs. `all` means; I think it's
referring to whether things recurse past the first level down.  That is
worthwhile fixing in the docs.

I'm also concerned about avoiding repeats in the DAG; which could become
quite expensive at module load time if a package is both a commonly-used
dependency and has a lot of dependencies itself.  Unless that has already
been taken care of with this feature.  Note that when one pre-generates
`module load` commands, repeats can be more easily filtered out.

I like the idea of recursively loading dependencies for packages that need
it.  But this information should be an intrinsic part of the package, it
should go in `package.py`, and it should "just work" and be turned on by
default.  It should not have to be a separate per-package configuration
option in `modules.yaml` --- which should just contain a high-level option
to turn on/off recursive module loading in general.

For all these reasons, I think that recursive module loading, although an
interesting feature, is not yet ready for prime time.  Let's see if we can
get this feature part of `PythonPackage`, and see if it "just works" in
practice for Python packages.  That would be a nice win.  As it is now, I
have to "know" which packages do / do not need recursive loading; or, I
just recursively load the kitchen sink and making everything recursive,
including a lot of things I don't need.

**Comment by alalazo** [comment]
> I'm also concerned about avoiding repeats in the DAG; which could become
quite expensive at module load time if a package is both a commonly-used
dependency and has a lot of dependencies itself.  Unless that has already
been taken care of with this feature.  Note that when one pre-generates
`module load` commands, repeats can be more easily filtered out.

What do you mean? There's no DAG in a module file, just dumb TCL code:
```tcl
if ![ is-loaded python/2.7.12-gcc-6.2.0 ] {
    puts stderr "Autoloading python/2.7.12-gcc-6.2.0"
    module load python/2.7.12-gcc-6.2.0
}
```

> But this information should be an intrinsic part of the package, it
should go in `package.py`, and it should "just work" and be turned on by
default.  It should not have to be a separate per-package configuration
option in `modules.yaml` --- which should just contain a high-level option
to turn on/off recursive module loading in general.

I don't really agree with it. We may want to turn it on by default, but:

    1. the configuration is not per package, it's per selection with a convenient `all` keyword
    1. the DAG information is already in the spec, that's the CORE feature of spack

> Let's see if we can get this feature part of `PythonPackage`, and see if it "just works" in
practice for Python packages. 

Can you please clarify? I have the impression it will duplicate what is already there in the best case.

**Comment by citibeth** [comment]
> What do you mean? There's no DAG in a module file, just dumb TCL code:
>
> if ![ is-loaded python/2.7.12-gcc-6.2.0 ] {
>     puts stderr "Autoloading python/2.7.12-gcc-6.2.0"
>     module load python/2.7.12-gcc-6.2.0
> }
>
> Suppose A -> (B,C,D,E,F,G)
And also (B,C,D,E,F,G) -> Z
Now if I do a recursive-load on A, will I not end up loading Z 6 times?

The problem here (if it is a currently a problem, which I don't know) is
you are visiting nodes in the DAG as if it's a tree.  In worst-case
scenarios, this can cause exponential blowup in time.  For example,
consider:

A -> (B,C)
(B,C) -> (D,E)
(D,E) -> (F,G)
...

As you can see... `module load A` will load B and C once each; D and E
twice, F and G four times, etc.  It blows up exponentially.


> But this information should be an intrinsic part of the package, it
> should go in package.py, and it should "just work" and be turned on by
> default. It should not have to be a separate per-package configuration
> option in modules.yaml --- which should just contain a high-level option
> to turn on/off recursive module loading in general.
>
> I don't really agree with it. We may want to turn it on by default, but:
>
> 1. the configuration is not per package, it's per selection with a convenient `all` keyword
> 1. the DAG information is already in the spec, that's the CORE feature of spack
>
>
Huh?  How do we know what `module load py-xyz` should auto-load
dependencies, but `module load emacs` should not?  Where is that
information stored?


> Let's see if we can get this feature part of PythonPackage, and see if it
> "just works" in
> practice for Python packages.
>
> Can you please clarify? I have the impression it will duplicate what is
> already there in the best case.
>
If packages tell Spack whether they need their dependencies loaded, then
`PythonPackage` would turn it on by default.  We would then try it with
hundreds of python packages, and discover whether things really work when
you say `module load py-xyz`.

**Comment by alalazo** [comment]
> Now if I do a recursive-load on A, will I not end up loading Z 6 times?

No. It's under a conditional. And it has never been an issue in any environment I used so far.

> Huh?  How do we know what `module load py-xyz` should auto-load
dependencies, but `module load emacs` should not?  Where is that
information stored?

In `modules.yaml`.

> If packages tell Spack whether they need their dependencies loaded, then
`PythonPackage` would turn it on by default.  We would then try it with
hundreds of python packages, and discover whether things really work when
you say `module load py-xyz`.

If packages hard-code what they need loaded in module files things will not be configurable anymore, while now:
```yaml
modules:
  tcl:
    ^python:
      autoload:  'all'
```
will create module files that load their dependencies only if they depend on python.

**Comment by citibeth** [comment]
On Tue, Jan 10, 2017 at 1:20 PM, Massimiliano Culpo <
notifications@github.com> wrote:

> Now if I do a recursive-load on A, will I not end up loading Z 6 times?
>
> No. It's under a conditional. And it has never been an issue in any
> environment I used so far.
>

Is this a conditional in the generated TCL module?


> In modules.yaml.
>
> If packages tell Spack whether they need their dependencies loaded, then
> PythonPackage would turn it on by default. We would then try it with
> hundreds of python packages, and discover whether things really work when
> you say module load py-xyz.
>
> If packages hard-code what they need loaded in module files things will
> not be configurable anymore, while now:
>
> modules:
>   tcl:
>     ^python:
>       autoload:  'all'
>
> will create module files that load their dependencies only if they depend
> on python.
>
The information needs to be collected in the `package.py`s that ship with
Spack because it is intrinsic to the nature of the package.  How about
adding this to `depends_on()`, for example:
```
class PyUdunits(Package):
    ...
    extends('python')
    depends_on('py-six', type=('build', 'run'), autoload=True)
    depends_on('py-netcdf', type=('build', 'run'), autoload=True)
    depends_on('udunits2')

```
Or do we already have this info?  Should `run` dependencies be
automatically set to `autoload=True`?


Just because this info is in `package.py` doesn't mean Spack has to do
anything in particular with it.  Configurations in `modules.yaml` could
configure what Spack does with it --- for example, a simple on/off switch.
One could even imagine per-package overrides in `modules.yaml`, but I doubt
that will be necessary.

**Comment by alalazo** [comment]
> Is this a conditional in the generated TCL module?

Yes, just a couple of comments above you have a posted example. I'll re-post it here for convenience:
```tcl
if ![ is-loaded python/2.7.12-gcc-6.2.0 ] {
    puts stderr "Autoloading python/2.7.12-gcc-6.2.0"
    module load python/2.7.12-gcc-6.2.0
}
```

> Just because this info is in `package.py` doesn't mean Spack has to do
anything in particular with it.  Configurations in `modules.yaml` could
configure what Spack does with it --- for example, a simple on/off switch.
One could even imagine per-package overrides in `modules.yaml`, but I doubt
that will be necessary.

I don't really agree in having this information in a `build_system` base class or, even worse, within the directives. I think it will make the overall design more inter-dependent and less moduler. The correct way if we want to generate modules that load dependencies as a default is to modify the `modules.yaml` shipped with spack.

Bottom-line: if you plan doing this can you please do it in a separate PR than #2778 ? I like what is there currently, but I feel kind of strong about not adding module related information to build-system classes or directives.

**Comment by citibeth** [comment]
>
> I feel kind of strong about not adding module related information to
> build-system classes or directives.


This conversation started with the suggestion that I generate
recursive-loading modules, rather than using `spack module loads -r` or
`spack load -r`:

Besides you can generate modules that load their dependencies automatically.


`spack module loads -r` is not perfect, but it gets the job done and is
simple to use.  After some back-and-forth, my conclusion is that **I will
continue to use `spack module loads -r` for the foreseeable future.**
 Because generating recursive-loading modules currently involves too much
manual tweaking, whereas `spack module loads -r` works out of the box.  I
would predict that others make a similar choice for the same reason, and
that this feature does not get much use in its current form.

Since I expect to continue using `spack module loads -r`, an upgraded
`spack load -r` is something I a would be interested in.

If Spack were upgraded to generate recursive-loading modules
out-of-the-box, and if it "just works," then I would be happy to switch.

On Tue, Jan 10, 2017 at 1:52 PM, Massimiliano Culpo <
notifications@github.com> wrote:

> Is this a conditional in the generated TCL module?
>
> Yes, just a couple of comments above you have a posted example. I'll
> re-post it here for convenience:
>
> if ![ is-loaded python/2.7.12-gcc-6.2.0 ] {
>     puts stderr "Autoloading python/2.7.12-gcc-6.2.0"
>     module load python/2.7.12-gcc-6.2.0
> }
>
>
Great!  So there is no problem on that front.  Maybe worth documenting
this, just to convince readers that it has been done right.

**Comment by alalazo** [comment]
> Maybe worth documenting this, just to convince readers that it has been done right.

I copy-pasted the snippet from the docs. :smile:

**Comment by michaelkuhn** [comment]
Maybe I am misunderstanding something here but `spack load` has been supporting `-r`/`--dependencies` for quite a while (I added support for it to the `.sh` version back in July). The `.csh` version is still missing this, though.

**Comment by adamjstewart** [comment]
@citibeth Is this still an issue? From what @michaelkuhn says it sounds like it works now.

**Comment by citibeth** [comment]
I don't use it, don't know.
