### ISSUE TITLE
Nginx: how to include kinds of module?

### ISSUE THREAD

**Issue by darmac** [LLNL/spack#16656]
When we install `nginx`, some additional module is needed for some test case.
e.g. 
```
./configure --add-module=../njs/nginx --prefix=/usr/local/nginx --with-http_ssl_module --with-http_image_filter_module
make
make install
```

But there are too much module for nginx, I think now we need add variants for each module? Is that  a more flexiable method for us to add the nginx module?

**Comment by adamjstewart** [comment]
Yes, the preferred way of doing this would be to add variants for each module.
