### ISSUE TITLE
Variants: Meaning of ~ + -

### ISSUE THREAD

**Issue by ax3l** [LLNL/spack#1665]
After checking example packages and the [docs](http://software.llnl.gov/spack/spack.html) I could not find a clear definition of the meaning `~` vs `-` vs `+` for *variants*.

What I am trying to build is a package depending always on mpi (easy) but as an option on `hdf5` or alternatively `hdf5+mpi` (for parallel i/o "aggregation"). Now I am confused if I should also add `hdf5~mpi` or even `hdf5-mpi` :-)

**Comment by ax3l** [comment]
Also, is there a way to say `when='NOT +parallel?'`?

Example:
```python
[...]
    variant('parallel', default=True, description='Enable parallel I/O transform support')

    # always depends on MPI but only (aggregated) parallel I/O
    # depends on parallel HDF5, too
    depends_on('mpi')
    depends_on('hdf5@1.8.6:', when='!+parallel')
    depends_on('hdf5@1.8.6:+/~/-mpi', when='+parallel')
[...]
```

**Comment by tgamblin** [comment]
`~` and `-`are the same.  `~` is there to disambiguate from `-` because `-` is also a valid identifier. `-` is also allowed because `~` can be expanded by shells if you add a space before it...

Examples:

```bash
# install a package called "foo-bar" (- is legal in identifiers)
$ spack install foo-bar

# Install a package called "foo" with variant "bar" disabled
$ spack install foo~bar

# Install a package called "foo" with variant "bar" disabled
$ spack install foo -bar

# Install a package called "foo" with variant "bar" disabled
# but possibly get a weird error if there is a user named "bar" on your system
$ spack install foo ~bar
```

**Comment by tgamblin** [comment]
> Also, is there a way to say when='NOT +parallel?'?

`when='~parallel'`

**Comment by tgamblin** [comment]
Most of the packages use a variant called just `mpi` for MPI support (as opposed to the more ambiguous "parallel").  You probably want this:

```python
variant('mpi', default=True, description="Enable parallel I/O transform support")

depends_on('hdf5@1.8.6:', when='~parallel')
depends_on('hdf5@1.8.6:+mpi', when='+parallel')
```

The constraints above allow the serial version to link with either `hdf5+mpi` or `hdf5~mpi` but the parallel version needs `hdf5+mpi`.

**Comment by ax3l** [comment]
thank you for the quick answer!

so **not** means `~` or `-` and **with variant** is `+`.

> Most of the packages use a variant called just mpi for MPI support (as opposed to the more ambiguous "parallel").

I know, it's super confusing in the MPI-I/O HDF5 context. What HDF5 people (and the hdf5 package `+mpi`) mean is MPI-I/O with aggregation to a single file.

The library I am writing a package for can support "MPI programs" writing posix style, domain-decomposed files with serial HDF5 and a second, "MPI-I/O, `hdf5 ./configure --enable-parallel` aggregated" writing to a single file.

**Comment by tgamblin** [comment]
> so not means ~ or - and with variant is +.

Yes.  And omitting the variant from a constraint means "don't care".

**Comment by ax3l** [comment]
excellent, then the code you posted is excatly what I want (but I still have to call the variant `parallel` since I always depend on MPI but only in one version on *parallel HDF5*)

**Comment by ax3l** [comment]
actually just found a way to call the variant `mpi` instead of `parallel`, too by skipping some parallel tools in it. PR incoming :)
