### ISSUE TITLE
Add spack bootstrap back (as a no-op)

### ISSUE THREAD

**Issue by mdorier** [LLNL/spack#16696]
The `spack bootstrap` command has recently been removed (commit https://github.com/spack/spack/commit/43c9ad34216a282a50cc1bbd107949c24db38835). Would it be possible to re-enabled it simply as a no-op with a warning message indicating that it has been deprecated and won't do anything?

I've had multiple CI jobs fail on me for the past week because this command does not exist anymore, and I'm still not done tracking scripts I authored that are now being used and will fail their users. I'm sure I'm not the only one with a hard-coded `spack bootstrap` somewhere (for starter, any script aiming at reproducing a set of experiments from scratch that rely on spack is likely to have that).

**Comment by tgamblin** [comment]
I think we already ripped the band-aid off on this one and will continue to break people even if we add it back.  But we can try to more gently remove things in the future.
