### ISSUE TITLE
[Discussion] : turn `self.<provider>_shared_lib` into an iterable

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#1670]
Attributes like `lapack_shared_lib` in `lapack` providers now return a single full path to a library.  Changing those attributes to be iterables of paths would help in dealing with libraries like `MKL` that require to link more than one library with a well defined ordering.

If there is general agreement on this change I volunteer to prepare a PR that : 
- will change all the relevant virtual packages in such way
- will modify all the packages that are now using those attributes accordingly
- will add a few convenience functions to handle common manipulations of those iterables 

Let me know :smile:

**Comment by tgamblin** [comment]
This sounds good to me.

**Comment by davydden** [comment]
here is some a rough overview of how one may need to provide blas/lapack:

library names (space/semicolon separated) + dir: [Hypre](https://github.com/davydden/homebrew-science/blob/mkl_dealii/hypre.rb#L39-L45), [Trilinos](https://github.com/davydden/homebrew-science/blob/mkl_dealii/trilinos.rb#L115-L120)
ldflags : [Superlu_dist](https://github.com/davydden/homebrew-science/blob/mkl_dealii/superlu_dist.rb#L31), [scalapack](https://github.com/davydden/homebrew-science/blob/mkl_dealii/scalapack.rb#L28-L29), [mumps](https://github.com/davydden/homebrew-science/blob/mkl_dealii/mumps.rb#L107-L108), [p4est](https://github.com/davydden/homebrew-science/blob/mkl_dealii/p4est.rb#L32)
full path (space/semicolon separated) : [Petsc](https://github.com/davydden/homebrew-science/blob/mkl_dealii/petsc.rb#L92-L93), [deal.II](https://github.com/davydden/homebrew-science/blob/mkl_dealii/dealii.rb#L58-L62)

p.s. links are to my ruby code for homebrew, which should nonetheless be easy to read. This worked for me with MKL **without** single dynamic library.

**Comment by davydden** [comment]
@nrichart ping. 

Here is also a link to a last-year discussion on this topic https://github.com/LLNL/spack/issues/234.

**Comment by nrichart** [comment]
In fact it is somethinng we already do for our production installation of spack.
The idea of @alalazo is I guess to see with you guys, if there is a point to clean the work and to push it upstream.

**Comment by tgamblin** [comment]
@nrichart: yes, please.

**Comment by alalazo** [comment]
While I am working on this I noticed that all `blas`, `lapack`, `scalapack` virtual providers all have a `shared` variant. Would it be welcome if I could reduce `lapack_shared_libs` and `lapack_static_libs` to just `lapack_libs` ?

**Comment by davydden** [comment]
>  Would it be welcome if I could reduce lapack_shared_libs and lapack_static_libs to just lapack_libs ?

:+1:  i don't see any possible problems with this approach.

This would also enforce that within a DAG all packages need to only one type of blas/lapack libs ( e.g. `shared` even if `static` libs are also available). Don't know whether there are cases when this might not be desirable. Should also bee fine when there is a lib in DAG which is build as static (e.g. `hypre` on macOS) among other things which are `shared` and use `shared` blas/lapack.

@nrichart: 

> In fact it is somethinng we already do for our production installation of spack.

do you do this the same way as @alalazo suggests?

**Comment by nrichart** [comment]
@davydden I work at EPFL with @alalazo, so yes I do the same way :).

for the `lapack_shared_libs` it also mean that you have to write the `depends_on` as `depends_on('lapack+shared')` otherwhy it is not valid.
And you enforce a variant `+shared` just because you cannot write the fact you depend on whatever was built.

With `lapack_libs` and `depends_on('lapack')` in a package you could do both `spack install foo^lapack~shared` and `spack install foo^lapack+shared`

**Comment by davydden** [comment]
> @davydden I work at EPFL with @alalazo, so yes I do the same way :).

oh, sure :smile:

> With lapack_libs and depends_on('lapack') in a package you could do both spack install foo^lapack~shared and spack install foo^lapack+shared

that makes perfect sense.

**Comment by davydden** [comment]
Thinking about making threading-realted variants the same in blas/lapack providers. It should be enough to have two variants which can't be `True` simultaneously: `pthread` and `openmp`. 

If there is package which needs no threads whatsoever in blas/lapack, it should be able to write `depends_on('blas~openmp~pthread')` to enforce this. Otherwise, both `blas+pthread` or `blas+openmp` should satisfy `depends_on('blas')`. `blas+openmp+thread` is not possible (somebody should throw and error).

Both `openblas` and `atlas` can provide threading using either `pthreads` or `openmp` (see http://stackoverflow.com/questions/19808706/which-library-is-more-universal-more-flexible-among-on-pthread-intel-tbb-open/19810039#19810039 for a quick overview of shared parallelization). 

This gets more tricky with `mkl`, which has more options (see [link advisor](https://software.intel.com/en-us/articles/intel-mkl-link-line-advisor/)): `serial`, use `tbb`, use two flavours of `OpenMP library`: Intel's `libomp5` (the only choice for Intel compilers!) or GNU `libgomp`. 

I suggest we treat the two variants in the following way for `mkl`: 

- `+openmp`:   use Intel's openmp with Intel's compilers and GNU otherwise.
- `~pthread`:  use completely sequential library.
- `+pthread`: either throw and error or also use completely sequential library. From practical perspective IMHO the latter makes more sense as one would not harm a package with serial blas.

Does this sound reasonable @alalazo @nrichart @tgamblin ?

**Comment by glennpj** [comment]
Would non-Boolean variants work here? Something like:
`threading=none`
`threading=openmp`
`threading=pthreads`

**Comment by davydden** [comment]
> Would non-Boolean variants work here? Something like:
threading=none
threading=openmp
threading=pthreads

I like as long as one can write in a package
```
depends_on('blas+threading=none')
```
 But I have not tested it. @tgamblin: are non-boolean variants in virtual packages passed to providers?

**Comment by davydden** [comment]
Looks like 
```
    depends_on('blas+threading=openmp')
```
is not possible:
```
==> Error: Unexpected token
```
Otherwise spec conretization shows default `threading`:
```
^openblas@0.2.18%clang@7.3.0-apple+fpic~openmp+shared threading=none arch=darwin-elcapitan-x86_64
```

**Comment by davydden** [comment]
wow, actually variants are not passed to providers at all:

with modified `arpack-ng` by `depends_on('blas+openmp')` I see
```
$ spack spec arpack-ng
Input spec
------------------------------
  arpack-ng

Normalized
------------------------------
  arpack-ng
      ^blas+openmp
      ^lapack

Concretized
------------------------------
  arpack-ng@3.4.0%clang@7.3.0-apple~mpi+shared arch=darwin-elcapitan-x86_64
      ^cmake@3.6.1%clang@7.3.0-apple~doc+ncurses+openssl~ownlibs~qt arch=darwin-elcapitan-x86_64
          ^bzip2@1.0.6%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
          ^curl@7.50.1%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
              ^openssl@1.0.2h%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
                  ^zlib@1.2.8%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
          ^expat@2.2.0%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
          ^libarchive@3.2.1%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
              ^libxml2@2.9.4%clang@7.3.0-apple~python arch=darwin-elcapitan-x86_64
                  ^xz@5.2.2%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
              ^lz4@131%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
              ^lzma@4.32.7%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
              ^lzo@2.09%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
              ^nettle@3.2%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
                  ^gmp@6.1.1%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
                      ^m4@1.4.17%clang@7.3.0-apple+sigsegv arch=darwin-elcapitan-x86_64
                          ^libsigsegv@2.10%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
          ^ncurses@6.0%clang@7.3.0-apple arch=darwin-elcapitan-x86_64
      ^openblas@0.2.18%clang@7.3.0-apple+fpic~openmp+shared arch=darwin-elcapitan-x86_64
```
Note `~openmp` in `openblas`.

**Comment by davydden** [comment]
Moreover
```
$ spack spec arpack-ng
Input spec
------------------------------
  arpack-ng

Normalized
------------------------------
  arpack-ng
      ^blas+openmp
      ^lapack+openmp

Concretized
------------------------------
==> Error: Package lapack not found in repository [Repo 'builtin' at '/Users/davydden/spack/var/spack/repos/builtin']
```

**Comment by davydden** [comment]
One also can't specify non-boolean variant from a CLI
```
$ spack spec arpack-ng ^openblas+threading=none
==> Error: Unexpected token
```

**Comment by adamjstewart** [comment]
@davydden I believe the syntax is something like:
```console
$ spack spec arpack-ng ^openblas threading=openmp
```

**Comment by davydden** [comment]
@adamjstewart thanks, you are right, `$ spack spec arpack-ng ^openblas threading=openmp` works.

**Comment by davydden** [comment]
still it seems like you can't pass any variants (boolean or not) from virtual packages to actual providers. From this perspective, i would go with `threading=none|openmp|pthreads` in a hope that the issue will be fixed eventually.

**Comment by alalazo** [comment]
@davydden @glennpj  Passing non-boolean variants would be the way to go also for other packages (e.g. `mvapich2` and network selection), not sure though we are ready yet to change packages in this direction.

**Comment by davydden** [comment]
@alalazo i think we can still go with non-boolean variants for blas threading, right? we won't break anything which is working.

**Comment by davydden** [comment]
i checked that currently no package specifies variants for blas:
```
$ag --py 'depends_on\(.blas\+'
```
is empty. Same for lapack: `ag --py 'depends_on\(.lapack\+'`.

**Comment by davydden** [comment]
same applies to `mpi`, no variants in any package, as far as I can tell.

**Comment by alalazo** [comment]
@davydden 
> i think we can still go with non-boolean variants for blas threading, right?

Yes, I would go for that, but not in #1682 . I also need to check if we can constrain the variant values to a predefined set. I would like to emit an error if somebody tries : 
```
spack install atlas threading=<wrong-string>
```
Otherwise we risk to turn a possible typo into an unintended installation...

**Comment by davydden** [comment]
> Yes, I would go for that, but not in #1682

fair enough.

>  I also need to check if we can constrain the variant values to a predefined set.

fully agree. I looked at documentation and examples, there aren't really any constraints now.
