### ISSUE TITLE
Potential for a fork bomb in "spack versions"

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#16720]
Forwarding here a severe bug that was reported in a direct conversation with @nazavode. Having ~10 users running at the same time `spack versions` on front-end nodes caused kernel lockup due to the high number of sockets opened (sys-admin reports ~210k distributed over 3 nodes). Users were internal, so they had `ulimit -n` set to ~70k.

### Steps to reproduce the issue
The forking behavior can be observed by just running
```console
$ spack versions boost
[ ... ]
```
and checking the number of processes spawned. Not that processes per-se are not the issue, but each one of them opens a socket which might stress `iptables`.

### Error Message

In the original issue the kernel watchdog was reporting:
```console
Message from syslogd@login03 at May 19 12:01:30 ...
kernel:Watchdog CPU:110 Hard LOCKUP
Message from syslogd@login03 at May 19 12:01:31 ...
kernel:watchdog: BUG: soft lockup - CPU#110 stuck for 23s! [python3:2756]
Message from syslogd@login03 at May 19 12:01:31 ...
kernel:watchdog: BUG: soft lockup - CPU#94 stuck for 22s! [iptables:5603]
```

### Information on your system

I was able to observe the forking behavior in:

* **Spack:** 0.14.2-1163-31ccf8029
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-broadwell

Original issue was reported on a Power 9 front-end node.

### Additional information

The potential fork bomb comes from a recursive generation of pools to scrape `urls` in:

https://github.com/spack/spack/blob/31ccf80294382a391743728a736574737217c23b/lib/spack/spack/util/web.py#L394-L401

in `_spider`. The pool uses a high number of processes and each process potentially recurse into this same function and generates another pool due to the implementation of `_spider_wrapper`:

https://github.com/spack/spack/blob/31ccf80294382a391743728a736574737217c23b/lib/spack/spack/util/web.py#L437-L439

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by nazavode** [comment]
@alalazo thanks for taking care of summing up all the info in an issue. In the meantime I asked all the Spack users on the system to use `spack versions --safe` since it looks like a safe way to avoid web scraping.

**Comment by alalazo** [comment]
If they just want to query safe versions they can also use `spack info`:
```console
$ spack info zlib
Package:   zlib

Description:
    A free, general-purpose, legally unencumbered lossless data-compression
    library.

Homepage: http://zlib.net

Tags: 
    None

Preferred version:  
    1.2.11    http://zlib.net/fossils/zlib-1.2.11.tar.gz

Safe versions:  
    1.2.11    http://zlib.net/fossils/zlib-1.2.11.tar.gz
    1.2.8     http://zlib.net/fossils/zlib-1.2.8.tar.gz
    1.2.3     http://zlib.net/fossils/zlib-1.2.3.tar.gz

Variants:
    Name [Default]    Allowed values    Description
    ==============    ==============    ===================================================

    optimize [on]     on, off           Enable -O2 for a more optimized lib
    pic [on]          on, off           Produce position-independent code (for shared libs)
    shared [on]       on, off           Enables the build of shared libraries.

Installation Phases:
    install

Build Dependencies:
    None

Link Dependencies:
    None

Run Dependencies:
    None

Virtual Packages: 
    None

```

**Comment by luigi-calori** [comment]
I can confirm that the issue is real:  on our power9 login nodes 
spack versions openfoam  
resut in enormous number of python process spawned that hangs the node.

PR  #16749 change behaviour and a single process is present during the command execution
no hangs happen
