### ISSUE TITLE
Option to copy configs to any hard config scope

### ISSUE THREAD

**Issue by white238** [LLNL/spack#16733]
Add command to copy an environment file to override a config scope (user, site, system)

### Rationale

WSC codes want to be very sure that the packages and compilers used are the ones described by the project. Several projects current patch spack through uberenv to limit extra scopes creeping in.  This would remove that hack.

### Description

git clone spack
cd spack/repo
bin/spack env activate --without-view --scope=user <path/to/environment/file>

Then all further commands in the spack repository would honor only that environment file.  This would require piggy back on the on going work of moving the user config out of the users home directory.

**Comment by becker33** [comment]
After discussion with @tgamblin, it might make more sense from an interface perspective to have this functionality appear as a subcommand of `spack config`. This could be done in conjunction with #13920.

@white238 do you have strong feelings about where this functionality should live, or do you not care as long as you can achieve it with a single command?

**Comment by white238** [comment]
I don't care what the command is as long as its a single command that overrides all scopes to obey my bidding.  I leave it up to you guys to decide what is best in your framework/vision.
