### ISSUE TITLE
some mistake in package cdo-1.9.8 download address

### ISSUE THREAD

**Issue by hgrhgy** [LLNL/spack#16757]
package cdo-1.9.8 download address should be ：
https://code.mpimet.mpg.de/attachments/download/20826/cdo-1.9.8.tar.gz
not
https://code.mpimet.mpg.de/attachments/download/20286/cdo-1.9.8.tar.gz

**Comment by alalazo** [comment]
@hgrhgy Can you submit a PR for this issue?

**Comment by adamjstewart** [comment]
@skosukhin is the maintainer

**Comment by skosukhin** [comment]
see #16764
