### ISSUE TITLE
How can I develop a package with different PackageClass by each version?

### ISSUE THREAD

**Issue by darmac** [LLNL/spack#16796]
There is some package depends on different version of `protobuf`,
The `protobuf@:2.5.0`  is a `AutotoolsPackage`, while the other version using `CMakePackage`.
So, is there any example we can put the the two package type in one package?
e.g.  `Ginkgo` (but show more detailed than it.)

**Comment by alalazo** [comment]
There's no unique answer to this question yet. A good starting point for the on-going discussion is https://github.com/spack/spack/pull/15420 where you can also find links to alternative proposals on how to solve the issue of packages that change build systems over time.
