### ISSUE TITLE
Mirror All Dependencies in Environment

### ISSUE THREAD

**Issue by RobertRosca** [LLNL/spack#16808]
This is more like unexpected behaviour than an actual bug, but 'bug' is the closest fit. I ran `spack mirror create --all` expecting it to mirror "all packages in the current environment", but it only mirrors the `user_specs` for the environment not `all_specs`.

Passing through a combination of `--all --dependencies` doesn't mirror everything either.

For me the expected behaviour of `--all` or `--all --dependencies` would be to mirror everything in the current environment, so everything in `all_specs` not just `user_specs`.

I made a [fork](https://github.com/RobertRosca/spack/tree/bugfix/mirror-env-dependencies) that allows you to run `spack mirror create --dependencies` to mirror everything non-external, and was going to do a PR but maybe my expectation is wrong and this is supposed to behave as it currently does :stuck_out_tongue:

Is there another way to mirror everything in an environment that I'm not aware of, or is it worth me making this PR?

Edit: if this does have to be a new flag, the options I can think of are:
- `spack mirror --dependencies` with an environment activated fetches everything in `all_specs` (what I do in my fork); currently this throws a `No packages were specified` error so adding this in as an option wouldn't break people's existing workflows as it's new.
- `spack mirror --all` with an environment activated fetches everything in `all_specs`, with a new `--user` flag that behaves the same way as `--all` currently does, might confuse people used to the current behaviour.
- `spack mirror --all --dependencies` might make more sense, but it could change existing behaviour as passing `--all --dependencies` currently 'works' but ignores the flags.

**Comment by glennpj** [comment]
This seems to be the same issue as #14335, so any potential fix would likely apply to that as well.

**Comment by eugeneswalker** [comment]
I came here to post that I was having this problem as well. `spack mirror create -D --all` is not grabbing the dependencies when run in context of a spack environment. @becker33

**Comment by RobertRosca** [comment]
Ah I didn't notice the other issue.

The main problem is that if you're in an environment the `--dependency` and `--all` flags don't seem to get checked or affect what is mirrored, as the checks for those flags only happen if you aren't in an environment.

Fixing this in the code is simple, but deciding what flags should do what is a bit tricky I guess.

**Comment by scheibelp** [comment]
I think I see where the code needs to be updated to gather dependencies in environments (detail: I need to use `all_specs_by_hash` to gather them). As of now, there isn't a way to mirror all of the dependency specs. Perhaps that should happen if the user specifies `--all` or perhaps they should also specify `--dependencies`, but I'll need to update it so that one of those works.

If you specify `--all` outside of an environment, `--dependencies` is ignored. Generally this is because Spack will be collecting every package in the repository, so it is assumed there wouldn't be a need to concretize packages to learn their dependencies.

**Comment by scheibelp** [comment]
I can create a fix for this tomorrow, which would allow some combination of options to retrieve/mirror all the specs (including dependencies) in an environment.

**Comment by scheibelp** [comment]
I have updated https://github.com/spack/spack/pull/14154 to allow for this (in addition to adding a couple other behaviors).

**Comment by RobertRosca** [comment]
Awesome, thanks! And the exclude option will also be useful.
