### ISSUE TITLE
Installation issue: intel-tbb

### ISSUE THREAD

**Issue by tamaradanceva** [LLNL/spack#16825]
#14608 # Steps to reproduce the issue

I got the issue while trying to install hpctoolkit
```console
$ spack install hpctoolkit all-static=True mpi=True ^intel-mpi@2019.5.281 ^intel-tbb@2019.5`
```
A minimal example:
```console
$ spack install intel-tbb@2019.5`
```
Error:
```
==> Error: ChecksumError: sha256 checksum failed for /tmp/ubuntu/spack-stage/spack-stage-intel-tbb-2019.5-jf44x6rzrwqk2asrjgpm53dbe44bokjs/2019_U5.tar.gz
    Expected 2ea82d74dec50e18075b4982b8d360f8bd2bf2950f38e2db483aef82e0047444 but got abf9236e6ec9a3675fa59ab56c2192c7ab4f7096a82af118e8efa514b2541578

/shared/spack/lib/spack/spack/package.py:1114, in do_fetch:
       1111        self.stage.fetch(mirror_only)
       1112        self._fetch_time = time.time() - start_time
       1113
  >>   1114        if checksum and self.version in self.versions:
       1115            self.stage.check()
       1116
       1117        self.stage.cache_local()
```
I have found this related thread, https://github.com/oneapi-src/oneTBB/issues/30, but I was not sure it s appropriate to reopen it. I also saw a patch in the develop branch for intel-tbb@2020/. Thanks in advance.

**Comment by mwkrentel** [comment]
How old is your copy of spack?
This works for me with today's spack.

Intel keeps moving their repo around.  This was updated in spack in
#15675 on March 27 and AFAIK, versions after that work.

**Comment by mwkrentel** [comment]
I checked commit 16f104aafe2b that I mentioned above, and it includes:

```
-    version('2019.5', sha256='2ea82d74dec50e18075b4982b8d360f8bd2bf2950f38e2db483aef82e0047444')
+    version('2019.5', sha256='abf9236e6ec9a3675fa59ab56c2192c7ab4f7096a82af118e8efa514b2541578')
```

So, the old sha is what your spack expected, but what it got was the
new sha.  This confirms that you have an old version of spack and this
was fixed two months ago.

**Comment by tamaradanceva** [comment]
That is right, thanks, I got into another issue now though with hpctoolkit. I will open anohter issue and close this one.
