### ISSUE TITLE
Installation issue: ssht should install headers into `include/ssht` subdir

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#16866]
The `ssht` package seems to install its header into the wrong location.

The `ssht` package uses `cp` to copy header files into the `include` directory of the install location. However, there is also an (unused) `install` target in the `CMakeFile`, which would install the header files into `include/ssht`.

How should this be resolved? I assume the long-term goal is to rely on the package's built-in mechanism as much as possible. However, this would be a breaking change. Are there guidelines or mechanisms for handling this?

**Comment by scheibelp** [comment]
It sounds like users of `ssht` are expected to `include <ssht/foo.h>`. If that's true and `ssht` isn't generating files there, the ideal solution is to suggest an upstream patch. If there's an option you can provide to the build system via Spack, that would also work.

If neither of those options are available, then I would say there isn't a standard way to deal with it: I've seen cases where the makefile is patched and others where the `install` method moves files where they need to be.

Also, if the headers appear in a subdirectory of `include/`, the `ssht` package would need to implement the `headers` property.

**Comment by eschnett** [comment]
Yes, it sounds as if people are expected to use `#include <ssht/ssht.h>`. What the Spack `ssht` package currently generates are files `include/ssht.h` instead since it circumvents the makefile when installing files. The question is whether or how to update the `ssht` package since changing this will presumably break code that currently uses Spack.

I don't understand what you mean by `headers` property.

**Comment by scheibelp** [comment]
> Yes, it sounds as if people are expected to use #include <ssht/ssht.h>. What the Spack ssht package currently generates are files include/ssht.h instead since it circumvents the makefile when installing files. The question is whether or how to update the ssht package since changing this will presumably break code that currently uses Spack.

If users of the `ssht` package are expected to do this, I'd assume that Spack packages which depend on `ssht` would have to go out of their way to refer to `ssht` header files; you could edit these packages and have the Spack `ssht` package use the associated Makefile. If `ssht` dependents aren't modified, I'd suspect that those dependents may be incorrectly using `ssht` and their code would have to be patched.

> I don't understand what you mean by headers property.

I just realized I was wrong, but what I meant was that you should implement a function

```
@property
def headers(self):
   return os.path.join(prefix, 'include', 'ssht')
```

That would actually be wrong if users of `ssht` expect to include `<ssht/...>` so there is no need for this.
