### ISSUE TITLE
Compilers built with 'install_missing_compilers' should be marked as explicit specs

### ISSUE THREAD

**Issue by nicholas-sly** [LLNL/spack#16871]
When a spec specifies a compiler for an environment to be used to build an explicit spec, it should be possible for the compiler to be an explicit spec as well.  Adding the compiler to the spec list is not necessarily an adequate fix if the package tries to modify variants in unexpected ways.  

### Rationale

We're building a Spack Stacks environment against 3 compilers and 3 MPI implementations with LMOD modules where one of the compilers is also the "Core" compiler.  If the compilers are not explicitly installed, it's not in the environment.  When trying to build the LMOD modules, no module is generated for those compilers.  As such, there is no module to access those packages built using those compilers.  

### Description

To see the issue, recreate the situation below:

```
sly@sly-laptop:~/git/spack-test$ cat spack.yaml
spack:
        specs:
                - zlib%gcc@9.2.0
        config:
                install_missing_compilers: true
sly@sly-laptop:~/git/spack-test$ spack concretize -f && spack install
==> Concretized zlib%gcc@9.2.0
[+]  6jyao6l  zlib@1.2.11%gcc@9.2.0+optimize+pic+shared arch=linux-ubuntu18.04-skylake

==> Updating view at /home/sly/git/spack-test/.spack-env/view
==> Installing environment /home/sly/git/spack-test
==> Updating view at /home/sly/git/spack-test/.spack-env/view

sly@sly-laptop:~/git/spack-test$ spack find
==> In environment /home/sly/git/spack-test
==> Root specs
-- no arch / gcc@9.2.0 ------------------------------------------
zlib%gcc@9.2.0 

==> 1 installed package
-- linux-ubuntu18.04-skylake / gcc@9.2.0 ------------------------
zlib@1.2.11
```

### General information

- [x] I have run `spack --version` and reported the version of Spack
  - commit: 712fc696bab72c3a1ba92fc84d1c14ad2d6347af
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
The option was deprecated
