### ISSUE TITLE
Intel Masquarading as GCC

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#1687]
I remember some issues of Intel compilers pretending to be GCC, and trying to be compatible with certain versions of GCC.  Is there anything on this topic people think should go in the Spack manual?

@tgamblin  wrote:

> This is an area of the dependency model that’s not covered well currently.
> 
> Compilers are getting more complicated, and the way the Intel compiler in particular handles ABI compatibility is complicated.  icpc relies on gcc’s libstdc++, standard c headers, etc. So it requires gcc as a build and link dependency.  For normal users, it does this in a relatively simple way; it finds the gcc in your PATH and assumes that’s the right one.  This works for most people with one install of icc on a standard linux distro.  For people in combinatorial hell, not so much. You can supply –gcc-name=<path to gcc> to tell it which gcc to use. This has become more of an issue recently because people need newer versions of gcc (often newer than what is on the system) to support C++11/14/17 features in icpc.  Matching the versions can get pretty nasty.
> 
> Basically this means gcc is a dependency of icc, so you have:
> 1. ```
>      A build (compiler) dependency on the intel compiler b/c you wanted to use it
>    ```
> 2. ```
>      A build dependency from icc -> gcc for compatibility
>    ```
> 3. ```
>      A link dependency on the particular gcc’s runtime libraries (glibc, libstdc++)
>    ```
> 
> The solution we would like to implement is to make compilers into fancier build dependencies, and to allow compiler to _impose_ additional link dependencies on things that use them as build dependencies.  That would maintain the ability to have different compilers for different parts of your DAG, but it would also enforce ABI compatibility through the link dependencies, which would need to be normalized (shared) across the DAG. So basically we’d have a way to use Spack’s “one version of everything in the DAG” rule on compiler runtime libraries, but to allow it to understand that runtime libraries might be shareable in certain ways across compilers.  i.e., you could reliably build a multi-compiler executable, and maybe pick the fastest compiler for different nodes in the DAG.  This is something that is currently rather painful to do (so no one does it).
> 
> The other nice thing this would do would be to allow you to use the virtual dependency system with compilers, so we can make compilers providers of particular languages at particular versions (c@99, c@03, cxx@11, cxx@14, fortran@77, etc.) and packages then only have to depend on the language they need.  We could get rid of the sort-of-weird 4-tuple compiler system Spack currently uses.  This would also let you mix C and Fortran compilers more easily.
> 
> So, short story: this is something not currently in Spack’s dependency model, but we’re working on it.  I would hold off on putting this in the docs.  Unless you think the explanation above is something that should go in the docs.
> 
> -Todd

**Comment by citibeth** [comment]
The fancy mix-n-match you describe sounds neat, but I think we can do a lot in the docs now.

I think the interesting part here is how a single icc instance actually acts like one of many different compilers, depending on how it's set up and what the env vars are.  Most users are probably not aware of how that works because it is "automagic" when you install.

Therefore, I think what the docs need NOW is a guide on how to configure `icc` to a desired GCC version.  Assuming you've `spack install`ed your target GCC version, then what do you do?  And I ask that question in two senese:

1. Regardless of Spack, how do you tell `icc` which GCC to target?  Do you set an env var?  Change a config file?  Write a wrapper?  Is it easy to get any GCC target you want at any time, or is there some global config file you always have to be changing?

2. Assuming you know how to do (1) above, how do you get Spack to do it in a way that works reliably and predictably?

3. How do you name this compiler for Spack purposes?  Would I call it `icc@16.3-5.6` --- meaning, this is Intel compiler version 16.3, targeting GCC 5.6 compatibility?

**Comment by citibeth** [comment]
Let's link this to #638

**Comment by citibeth** [comment]
I added the following section to the docs, any comments?

```
^^^^^^^^^^^^^^^
Intel Compilers
^^^^^^^^^^^^^^^

Intel compilers are unusual because a single Intel compiler version
can emulate multiple GCC versions.  In order to provide this
functionality, the Intel compiler needs GCC to be installed.
Therefore, the following steps are necessary to successfully use Intel
compilers:

 #. Install a version of GCC that implements the desired language
    features (``spack install gcc``).

 #. Identify the location of the compiler you just installed:

    .. code-block:: console

        $ spack location -i gcc
        /home2/rpfische/spack2/opt/spack/linux-centos7-x86_64/gcc-4.9.3-iy4rw...

 #. Tell the Intel compiler how to find that desired GCC.  This may be
    done in one of two ways: (text taken from `Intel Reference Guide
    <https://software.intel.com/en-us/node/522750>`_):

    > By default, the compiler determines which version of ``gcc`` or ``g++``
    > you have installed from the ``PATH`` environment variable.
    > 
    > If you want use a version of ``gcc`` or ``g++`` other than the default
    > version on your system, you need to use either the ``-gcc-name``
    > or ``-gxx-name`` compiler option to specify the path to the version of
    > ``gcc`` or ``g++`` that you want to use.

    This is accomplished through a manual compiler setup in
    ``compilers.yaml``.  For example:

    .. code-block:: yaml

        compilers:
        - compiler:
            modules = [intel-15.0.24]
            operating_system: centos7
            paths:
              cc: /opt/intel-15.0.24/bin/icc-15.0.24-beta
              cflags: -gcc-name /home2/rpfische/spack2/opt/spack/linux-centos7-x86_64/gcc-4.9.3-iy4rw.../bin/gcc
              cxx: /opt/intel-15.0.24/bin/icpc-15.0.24-beta
              cxxflags: -gxx-name /home2/rpfische/spack2/opt/spack/linux-centos7-x86_64/gcc-4.9.3-iy4rw.../bin/g++
              f77: /opt/intel-15.0.24/bin/ifort-15.0.24-beta
              fc: /opt/intel-15.0.24/bin/ifort-15.0.24-beta
              fflags: -gcc-name /home2/rpfische/spack2/opt/spack/linux-centos7-x86_64/gcc-4.9.3-iy4rw.../bin/gcc
            spec: intel@15.0.24.4.9.3

    .. note::

        The version number on the Intel compiler is a combination of
        the "native" Intel version number and the GNU compiler it is
        targeting.

    .. warning::

        This solution has not yet been tested.  Details may vary.
```

**Comment by glennpj** [comment]
I think the easiest way to do this is via the PATH set by environment modules.
```
icc -v
icc version 16.0.3 (gcc version 4.8.5 compatibility)
module load gcc/6.2.0-gcc-4.8.5-hgatyaj
icc -v
icc version 16.0.3 (gcc version 6.2.0 compatibility)
```

**Comment by adamjstewart** [comment]
@glennpj Yes, but if you rely on the PATH, then you'll get different results each time you run Spack and forget to add that module. If you add it directly to the compilers.yaml file, you'll always get what you want.

**Comment by glennpj** [comment]
@adamjstewart That is certainly a good point, assuming the installation has multiple modules for the intel compiler pointing to different gcc versions for different compatibility.

**Comment by glennpj** [comment]
The only other thing to point out is that passing flags in the compilers.yaml is currently broken, see #1532.

**Comment by citibeth** [comment]
OK, looks like what I wrote won't currently work.  Can modules work?  Here's the latest rewritten text.  I must maintain discipline and only document things as they are today.

```
^^^^^^^^^^^^^^^
Intel Compilers
^^^^^^^^^^^^^^^

Intel compilers are unusual because a single Intel compiler version
can emulate multiple GCC versions.  In order to provide this
functionality, the Intel compiler needs GCC to be installed.
Therefore, the following steps are necessary to successfully use Intel
compilers:

 #. Install a version of GCC that implements the desired language
    features (``spack install gcc``).

 #. Tell the Intel compiler how to find that desired GCC.  This may be
    done in one of two ways: (text taken from `Intel Reference Guide
    <https://software.intel.com/en-us/node/522750>`_):

    > By default, the compiler determines which version of ``gcc`` or ``g++``
    > you have installed from the ``PATH`` environment variable.
    > 
    > If you want use a version of ``gcc`` or ``g++`` other than the default
    > version on your system, you need to use either the ``-gcc-name``
    > or ``-gxx-name`` compiler option to specify the path to the version of
    > ``gcc`` or ``g++`` that you want to use.

Intel compilers may therefore be configured in one of two ways with
Spack: using modules, or using compiler flags.

""""""""""""""""""""""""""
Configuration with Modules
""""""""""""""""""""""""""

One can control which GCC is seen by the Intel compiler with modules.
A module must be loaded both for the Intel Compiler (so it will run)
and GCC (so the compiler can find the intended GCC).  The following
configuration in ``compilers.yaml`` illustrates this technique:

    .. code-block:: yaml

        compilers:
        - compiler:
            modules = [gcc-4.9.3, intel-15.0.24]
            operating_system: centos7
            paths:
              cc: /opt/intel-15.0.24/bin/icc-15.0.24-beta
              cxx: /opt/intel-15.0.24/bin/icpc-15.0.24-beta
              f77: /opt/intel-15.0.24/bin/ifort-15.0.24-beta
              fc: /opt/intel-15.0.24/bin/ifort-15.0.24-beta
            spec: intel@15.0.24.4.9.3


    .. note::

        The version number on the Intel compiler is a combination of
        the "native" Intel version number and the GNU compiler it is
        targeting.

    .. warning::

        This solution has not yet been tested.  Details may vary.

""""""""""""""""""""""""""
Command Line Configuration
""""""""""""""""""""""""""

. warning::

    As of the writing of this manual, added compilers flags are broken;
    see `GitHub Issue <https://github.com/LLNL/spack/pull/1532>`_.

One can also control which GCC is seen by the Intel compiler by adding
flags to the ``icc`` command:

 #. Identify the location of the compiler you just installed:

    .. code-block:: console

        $ spack location -i gcc
        /home2/rpfische/spack2/opt/spack/linux-centos7-x86_64/gcc-4.9.3-iy4rw...

#. Set up ``compilers.yaml``, for example:

    .. code-block:: yaml

        compilers:
        - compiler:
            modules = [intel-15.0.24]
            operating_system: centos7
            paths:
              cc: /opt/intel-15.0.24/bin/icc-15.0.24-beta
              cflags: -gcc-name /home2/rpfische/spack2/opt/spack/linux-centos7-x86_64/gcc-4.9.3-iy4rw.../bin/gcc
              cxx: /opt/intel-15.0.24/bin/icpc-15.0.24-beta
              cxxflags: -gxx-name /home2/rpfische/spack2/opt/spack/linux-centos7-x86_64/gcc-4.9.3-iy4rw.../bin/g++
              f77: /opt/intel-15.0.24/bin/ifort-15.0.24-beta
              fc: /opt/intel-15.0.24/bin/ifort-15.0.24-beta
              fflags: -gcc-name /home2/rpfische/spack2/opt/spack/linux-centos7-x86_64/gcc-4.9.3-iy4rw.../bin/gcc
            spec: intel@15.0.24.4.9.3

.. warning::

    This solution has not yet been tested.  Details may vary.
```

**Comment by citibeth** [comment]
I'm interested in feedback on the commit referenced above.

**Comment by lee218llnl** [comment]
@citibeth This writeup is very nice! I was able to test this out and get it to work. As you indicated, the details of the compilers.yaml structure for the "Command Line Configuration" will need to be updated after #1532 is merged (the [c,cxx,f]flags will need to be moved into the flags sub category. It may also be worth noting that rpaths are not being set for the gcc location, so users will have to add this to their ldflags in compilers.yaml or load the appropriate gcc module when running to actually pick up the specified gcc's libraries at run time.

**Comment by citibeth** [comment]
Gregory, thank you for the update.

Can you please be specific about how the text should change?  That would be
really helpful because I'm not running this stuff myself right now, and
it's easy to get wrong.  The current version of the docs is found below
(See the section called "Intel Compilers").  Best would be if you can
submit a PR on the citibeth/spack repo.

https://github.com/citibeth/spack/blob/efischer/docs2/lib/spack/docs/getting_started.rst

**Comment by adamjstewart** [comment]
It looks like this documentation made it into the Getting Started guide. Reopen if you think there is anything missing.
