### ISSUE TITLE
spack install hanging on BG/Q

### ISSUE THREAD

**Issue by lee218llnl** [LLNL/spack#1689]
Running something simple like `spack install curl` hangs on BG/Q. It appears to be hanging pretty early in Spack's initialization, as I notice a compilers.yaml file doesn't get generated.

**Comment by pramodk** [comment]
@lee218llnl : could you try PR #1980 ?

**Comment by tgamblin** [comment]
@lee218llnl can you please verify that this doesn't happen anymore since #1980 has been merged, and reopen if it does?

**Comment by lee218llnl** [comment]
@tgamblin Confirmed that this no longer occurs.

**Comment by tgamblin** [comment]
Thanks!
