### ISSUE TITLE
Testing an installation

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#169]
When installing software, I like to run a quick test that the installation works fine. This is nothing more than building and running a trivial program that outputs the version numbers. Often, this catches problems with install paths or library paths. It would be good to support this as a post-install step.

**Comment by davydden** [comment]
:+1: for a `test` block in each package as a post-install step invoked by `spack test <package>`. Here are a couple of examples from Homebrew: [deal.ii](https://github.com/Homebrew/homebrew-science/blob/master/dealii.rb#L107-L158), [mumps](https://github.com/Homebrew/homebrew-science/blob/master/mumps.rb#L184-L218), [petsc](https://github.com/Homebrew/homebrew-science/blob/master/petsc.rb#L165-L244).

Also many packages are missing `make test` runs or equivalent, which normally do not take more than a minute or so but are good to check that things are working as expected before doing production runs.

**Comment by adamjstewart** [comment]
I've definitely run into some `make test` runs that take significantly longer than the `configure` or `make` steps, so we may not want them enabled by default. Personally, I would love to run `make test` so I can sleep well at night. If we separate configure and install, then we could easily add a `test()` function. We could then add a `-t/--test` option to `make install` that runs `test()`.

One thing to consider would be something like GCC, which requires a few [additional dependencies](https://gcc.gnu.org/install/test.html) to properly run the test suite. There has already been talk of separating build dependencies and runtime dependencies. This may require us to add test dependencies.

**Comment by tgamblin** [comment]
@davydden: I would really like to add testing capability.  One challenge is that Spack is designed for big machines, and the command to actually run stuff (esp. on BG/Q, XC40, etc.) can be very different from site to site.  I would want to add a generic, auto-detected `msub`/`qsub`/`srun` command that could be used in Spack tests.

**Comment by davydden** [comment]
@tgamblin I was thinking about the following HPC usage case: create a job for a single node which does nothing for a couple of hours; ssh to the node; run spack to install everything. Since it's on the node, one will be able to use `mpiexec` or whatever name it has locally, which is not always the case on the front-end.

**Comment by alalazo** [comment]
@tgamblin we would also be interested in scheduler support within spack. If it may be of interest [this](http://gc3pie.readthedocs.org/en/master/) is the only package I found that seems to go in the direction of supporting different schedulers. Didn't have much time to play with it though...

**Comment by adamjstewart** [comment]
How do people feel about including `make("test")` in packages?

**Comment by mathstuf** [comment]
Depends on how reliable the test suites are. There should probably be a `--no-test` argument to `spack install` to suppress testing so that test suites which take a long time (I'm thinking at least VTK and ParaView here, but they're not the only ones) can be skipped.

**Comment by davydden** [comment]
i would not have a separate option `--no-test`, instead all the tests which are reasonable fast should be done unconditionally. Whereas tests which are long should be done (if possible) by something like `spack test <package>`.

The rationale is that `--no-test` does not change the variant of the package (like `+openmp`, `+mpi`, `+shared`, etc) so i would avoid those.

**Comment by mathstuf** [comment]
Well, there's the problem that the default is to not keep stage directories around, so a `spack test` would require rebuilding the package from scratch in the "common" case.

**Comment by alalazo** [comment]
I think we can distinguish between install time tests (`make test` or similar things) and post-install tests (like the small executable that @davydden provided for openblas). For the former I agree with @mathstuf in that `spack install --no-tests ...` is needed, for the latter I think we should be able to execute them after the installation like @davydden proposes.

**Comment by alalazo** [comment]
A couple random thoughts on this:
- #1169 added a switch to run tests at install time 
- #1186 might provide a modular solution to attach custom tests to packages

**Comment by davydden** [comment]
i think essentially whe/if #1186 is merged, what's missing is `spack test <package>` which would run a post-install step `install_test()`.

**Comment by alalazo** [comment]
@eschnett Is there something more that needs to be done? Or are you fine with : 
```
spack install --run-tests ...
```
if appropriate functions have been defined in the package (like in `hdf5` fo instance)?

**Comment by alalazo** [comment]
@eschnett I am going to close this because I think it has been fixed already. Please reopen if still necessary.
