### ISSUE TITLE
Installation issue: mpich does not build with gcc 10

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#16913]
The mpich package does not build with gcc 10. gcc 10 enforces the Fortran standard, which reports argument mismatches for certain MPI calls. This issue is well known; see e.g. https://gcc.gnu.org/gcc-10/porting_to.html and https://lists.mpich.org/pipermail/discuss/2020-January/005863.html. The work-around is to add -fallow-argument-mismatch to FCFLAGS when building mpich, and presumably also when using mpich with a Fortran compiler.

**Comment by eschnett** [comment]
Adding `'FCFLAGS=-fallow-argument-mismatch'` and `'FFLAGS=-fallow-argument-mismatch'` to the configure arguments indeed makes mpich build. I'm not familiar with how to insert this into the proper Spack mechanisms.

**Comment by becker33** [comment]
@eschnett 
What version of Spack are you using?

My latest pull has
```
        if self.spec.satisfies('%gcc@10:'):                                     
            env.set('FFLAGS', '-fallow-argument-mismatch')  
```
already in the `mpich` package.py file.

**Comment by eschnett** [comment]
```
$ git status
On branch master
Your branch is up to date with 'origin/master'.
```

D'oh. It's `develop` in this project.
