### ISSUE TITLE
Specs have the same SHA-1 prefix on fresh installation.

### ISSUE THREAD

**Issue by brettviren** [LLNL/spack#1692]
I'm trying to develop a packaging for BEM++.  

I'm using development branch of a few hours ago at f5bc0cbb65c95249b3f1fd1b5c63da5a03acbded

Building the dependencies in a fresh, empty Spack area gives the error `Specs <a> and <b> have the same SHA-1 prefix!`

```
==> Building py-nose
==> Warning: Patched overlong shebang in /home/bvdb/larf-spack/spack/opt/spack/linux-redhat6-x86_64/gcc-4.4.7/py-nose-1.3.7-fb4ywvfh47agdfnfokiouclpzmdv7vhk/bin/nosetests-2.7
==> Warning: Patched overlong shebang in /home/bvdb/larf-spack/spack/opt/spack/linux-redhat6-x86_64/gcc-4.4.7/py-nose-1.3.7-fb4ywvfh47agdfnfokiouclpzmdv7vhk/bin/nosetests
==> Successfully installed py-nose
  Fetch: 0.20s.  Build: 1.41s.  Total: 1.61s.
[+] /home/bvdb/larf-spack/spack/opt/spack/linux-redhat6-x86_64/gcc-4.4.7/py-nose-1.3.7-fb4ywvfh47agdfnfokiouclpzmdv7vhk
==> Installing py-numpy
==> python is already installed in /home/bvdb/larf-spack/spack/opt/spack/linux-redhat6-x86_64/gcc-4.4.7/python-2.7.12-7balpamix4h4zcrl455g6a2eyaa43ahm
==> Error: Specs py-nose@1.3.7%gcc@4.4.7 arch=linux-redhat6-x86_64^bzip2@1.0.6%gcc@4.4.7 arch=linux-redhat6-x86_64^ncurses@6.0%gcc@4.4.7 arch=linux-redhat6-x86_64^openssl@1.0.2h%gcc@4.4.7 arch=linux-redhat6-x86_64^py-setuptools@25.2.0%gcc@4.4.7 arch=linux-redhat6-x86_64^python@2.7.12%gcc@4.4.7~tk~ucs4 arch=linux-redhat6-x86_64^readline@6.3%gcc@4.4.7 arch=linux-redhat6-x86_64^sqlite@3.8.5%gcc@4.4.7 arch=linux-redhat6-x86_64^zlib@1.2.8%gcc@4.4.7 arch=linux-redhat6-x86_64 and py-nose@1.3.7%gcc@4.4.7 arch=linux-redhat6-x86_64^bzip2@1.0.6%gcc@4.4.7 arch=linux-redhat6-x86_64^ncurses@6.0%gcc@4.4.7 arch=linux-redhat6-x86_64^openssl@1.0.2h%gcc@4.4.7 arch=linux-redhat6-x86_64^python@2.7.12%gcc@4.4.7~tk~ucs4 arch=linux-redhat6-x86_64^readline@6.3%gcc@4.4.7 arch=linux-redhat6-x86_64^sqlite@3.8.5%gcc@4.4.7 arch=linux-redhat6-x86_64^zlib@1.2.8%gcc@4.4.7 arch=linux-redhat6-x86_64 have the same SHA-1 prefix!
```

This looks maybe related to #1559 but as it's in a fresh spack area, maybe not.

Here is the current BEM++ packaging:

```python
from spack import *

class Bempp(Package):
    """BEM++ provides PDE Solving via the Boundary Element Method"""
    homepage = "http://www.bempp.org"
    url = "https://github.com/bempp/bempp"

    version("development", git = "https://github.com/bempp/bempp.git",
            branch="development")


    depends_on("cmake@3.6.1:", type="build")
    depends_on("tbb")
    depends_on("gmsh")
    depends_on("python@2.7.12:")
    depends_on("py-cython")
    depends_on("py-numpy")
    depends_on("py-scipy")
    depends_on("py-setuptools")
    depends_on("py-matplotlib")
    #depends_on("paraview+python")                                                            


    parallel = True

    def install(self, spec, prefix):
	with working_dir('spack-build', create=True):
            cmake('..', *std_cmake_args)
            make()
            make('install')

```

**Comment by tgamblin** [comment]
Apparently I should've tried harder to reproduce this in #1535.  I'm on it.

**Comment by eschnett** [comment]
I see this in unrelated packages:
```
==> Error: Specs gmp@6.1.1%gcc@5.4.0 arch=linux-Ubuntu16-x86_64^libsigsegv@2.10%gcc@5.4.0 arch=linux-Ubuntu16-x86_64^m4@1.4.17%gcc@5.4.0+sigsegv arch=linux-Ubuntu16-x86_64 and gmp@6.1.1%gcc@5.4.0 arch=linux-Ubuntu16-x86_64 have the same SHA-1 prefix!
```

**Comment by glennpj** [comment]
Not sure if this information is helpful or just piling on but I see it when trying to build py-sphinx

``
==> Error: Specs py-babel@2.3.4%gcc@4.8.5 arch=linux-centos7-x86_64^bzip2@1.0.6%gcc@4.8.5 arch=linux-centos7-x86_64^ncurses@6.0%gcc@4.8.5 arch=linux-centos7-x86_64^openssl@1.0.2h%gcc@4.8.5 arch=linux-centos7-x86_64^py-pytz@2016.6.1%gcc@4.8.5 arch=linux-centos7-x86_64^py-setuptools@25.2.0%gcc@4.8.5 arch=linux-centos7-x86_64^python@2.7.12%gcc@4.8.5~tk+ucs4 arch=linux-centos7-x86_64^readline@6.3%gcc@4.8.5 arch=linux-centos7-x86_64^sqlite@3.8.5%gcc@4.8.5 arch=linux-centos7-x86_64^zlib@1.2.8%gcc@4.8.5 arch=linux-centos7-x86_64 and py-babel@2.3.4%gcc@4.8.5 arch=linux-centos7-x86_64^bzip2@1.0.6%gcc@4.8.5 arch=linux-centos7-x86_64^ncurses@6.0%gcc@4.8.5 arch=linux-centos7-x86_64^openssl@1.0.2h%gcc@4.8.5 arch=linux-centos7-x86_64^py-pytz@2016.6.1%gcc@4.8.5 arch=linux-centos7-x86_64^python@2.7.12%gcc@4.8.5~tk+ucs4 arch=linux-centos7-x86_64^readline@6.3%gcc@4.8.5 arch=linux-centos7-x86_64^sqlite@3.8.5%gcc@4.8.5 arch=linux-centos7-x86_64^zlib@1.2.8%gcc@4.8.5 arch=linux-centos7-x86_64 have the same SHA-1 prefix!
``

**Comment by jgalarowicz** [comment]
I am also seeing this with the develop version, freshly updated.   It happened several times.  Each time, if I went back and uninstalled the last few packages, then the message went away on the spack install I was trying to do.  But, it happens again when I try to do another install.

**Comment by eschnett** [comment]
Yes, just to make sure this is clear: This is a critical problem that makes Spack currently completely unusable for me.

**Comment by tgamblin** [comment]
@eschnett: please see if this is resolved for you.
