### ISSUE TITLE
Installation issue: gcc@7.3.0

### ISSUE THREAD

**Issue by jjolly** [LLNL/spack#16968]
### Steps to reproduce the issue

From Ubuntu 20.04 with gcc 9.3.0 installed
```console
$ spack install gcc@7.3.0
...
In file included from /tmp/jjolly/spack-stage/spack-stage-gcc-7.3.0-qew2co74raqn36lqlwarwxe7pn6vq63n/spack-src/libsanitizer/sanitizer_common/sanitizer_platform_limits_posix.cc:190:0:
/tmp/jjolly/spack-stage/spack-stage-gcc-7.3.0-qew2co74raqn36lqlwarwxe7pn6vq63n/spack-src/libsanitizer/sanitizer_common/sanitizer_internal_defs.h:261:72: error: size of array 'assertion_failed__1150' is negative
     typedef char IMPL_PASTE(assertion_failed_##_, line)[2*(int)(pred)-1]
                                                                        ^
/tmp/jjolly/spack-stage/spack-stage-gcc-7.3.0-qew2co74raqn36lqlwarwxe7pn6vq63n/spack-src/libsanitizer/sanitizer_common/sanitizer_internal_defs.h:255:30: note: in expansion of macro 'IMPL_COMPILER_ASSERT' #define COMPILER_CHECK(pred) IMPL_COMPILER_ASSERT(pred, __LINE__)
                              ^~~~~~~~~~~~~~~~~~~~
/tmp/jjolly/spack-stage/spack-stage-gcc-7.3.0-qew2co74raqn36lqlwarwxe7pn6vq63n/spack-src/libsanitizer/sanitizer_common/sanitizer_platform_limits_posix.h:1461:3: note: in expansion of macro 'COMPILER_CHECK'
   COMPILER_CHECK(sizeof(((__sanitizer_##CLASS *) NULL)->MEMBER) == \
   ^~~~~~~~~~~~~~
/tmp/jjolly/spack-stage/spack-stage-gcc-7.3.0-qew2co74raqn36lqlwarwxe7pn6vq63n/spack-src/libsanitizer/sanitizer_common/sanitizer_platform_limits_posix.cc:1150:1: note: in expansion of macro 'CHECK_SIZE_AND_OFFSET'
 CHECK_SIZE_AND_OFFSET(ipc_perm, mode);
 ^~~~~~~~~~~~~~~~~~~~~
make[4]: *** [Makefile:523: sanitizer_platform_limits_posix.lo] Error 1
```

### Information on your system

```console
$ spack debug report
* **Spack:** 0.14.2-1341-2ec680bbf
* **Python:** 3.8.2
* **Platform:** linux-ubuntu20.04-x86_64
```

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/4736493/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/4736502/spack-build-env.txt)

gcc maintainer: @michaelkuhn 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by jjolly** [comment]
I have backported patches that fix the issue for gcc@5.3.0:7.4.0. PR to follow shortly.

**Comment by vsoch** [comment]
I think we just hit this error, but for an older gcc install attempt. Note that it was working before:

https://github.com/rse-ops/docker-images/runs/4123921483?check_suite_focus=true

How do we fix it? cc @davidbeckingsale

**Comment by davidbeckingsale** [comment]
I think that our problem was caused by using Ubuntu 22.04. Backporting  the fixes to old versions can be quite challenging, might not be worth it.

**Comment by vsoch** [comment]
Huh, how did we get a 22 04? I thought the release date would be April 2022? Did we time travel? :laughing:
