### ISSUE TITLE
Installation issue: libflame

### ISSUE THREAD

**Issue by vkallesh** [LLNL/spack#16970]
[spack-build-env.txt](https://github.com/spack/spack/files/4737656/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/4737659/spack-build-out.txt)

### Steps to reproduce the issue

```console
$ spack install <spec>
...
```

### Additional information

* [spack-build-out.txt]()
* [spack-build-env.txt]()

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by vkallesh** [comment]
[spack-build-out.txt](https://github.com/spack/spack/files/4737673/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/4737676/spack-build-env.txt)
[spack-db.releases-v0.14.7a68a4d85.2020-06-05-230245.tar.gz](https://github.com/spack/spack/files/4737682/spack-db.releases-v0.14.7a68a4d85.2020-06-05-230245.tar.gz)
[libflame.log](https://github.com/spack/spack/files/4737684/libflame.log)

**Comment by vkallesh** [comment]
spack find will fail for libflame installation.

Steps to reproduce:
1. git clone https://github.com/spack/spack.git
2. cd spack
3. git checkout releases/v0.14
4. source spack/share/spack/setup-env.sh
5. spack install -v gcc 
6. spack compiler add <gcc install path>
7. spack install -v libflame %gcc@9.2.0
8. spack find libflame

Error message:
No package matches the query: libflame
 

1.

**Comment by adamjstewart** [comment]
It looks like the installation finishes, but Spack fails when it tries to update the database:
```
[+] /home/amd/SPACK/spack/opt/spack/linux-ubuntu18.04-zen/gcc-9.2.0/libflame-5.2.0-4cgvlkjcafxbxcmobw6bjeyzjkwftidd
==> Warning: Dependency missing: may be deprecated or corrupted:
  /home/amd/SPACK/spack/opt/spack/linux-ubuntu18.04-zen/gcc-9.2.0/libflame-5.2.0-4cgvlkjcafxbxcmobw6bjeyzjkwftidd
  Specs libflame@5.2.0%gcc@9.2.0~debug+lapack2flame patches=bf75a5b56d4d63f23d01976eb2e61bb0b2816b662a7c7a3de9f03b9276b0973a,c5cae9e9afe42a6cdca1dcfdc39058a3e75d076483467c1e0fefe6bb76a4b16b +shared+static threads=no arch=linux-ubuntu18.04-zen ^openblas@0.3.8%gcc@9.2.0~consistentFPCSR~ilp64+pic+shared threads=none arch=linux-ubuntu18.04-zen and libflame@5.2.0%gcc@9.2.0~debug+lapack2flame patches=bf75a5b56d4d63f23d01976eb2e61bb0b2816b662a7c7a3de9f03b9276b0973a,c5cae9e9afe42a6cdca1dcfdc39058a3e75d076483467c1e0fefe6bb76a4b16b +shared+static~threads arch=linux-ubuntu18.04-zen ^openblas@0.3.8%gcc@9.2.0~consistentFPCSR~ilp64+pic+shared threads=none arch=linux-ubuntu18.04-zen have the same SHA-1 prefix!
```
@scheibelp have you ever seen anything like this before?

**Comment by vkallesh** [comment]
@scheibelp could you please help with more information for this issue.

**Comment by scheibelp** [comment]
Spack appears to be having an issue with variants that can have the value "no" or "yes" - in the case of `libflame` that is the "threads" variant. https://github.com/spack/spack/pull/17063 addresses this by updating `libflame` (Spack core should be updated to allow these values but I think that will take longer).

If you get a chance, can you let me know whether that resolves the issue for you?

**Comment by vkallesh** [comment]
Sorry from the comment section I could infer much details.
Is issue resolved ?, on which branch changes were done?

**Comment by vkallesh** [comment]
From this link https://github.com/spack/spack/pull/17063 I got the fix.

Just curious to understand:
1. What are tests that above changes needs to undergo for this recipe to be part of release?
2. How much time required for this change to be part of spack next release?
