### ISSUE TITLE
add `pthread` variant to openblas

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#1697]
https://github.com/xianyi/OpenBLAS/wiki/faq

> .., if OpenBLAS was compiled with threading support (USE_THREAD=1 by default), custom programs statically linked against libopenblas.a should also link to the pthread library 

with default to `True`.

Similar to `atlas`, it would provide two shared memory parallelisation options: pthreads or openmp.

**Comment by davydden** [comment]
@alalazo could you please address it in your blas/lapack PR to make variant names in `atlas` and `openblas` consistent?

**Comment by davydden** [comment]
for a record, here's a nice [Stackoverflow answer](http://stackoverflow.com/a/19810039) which explains different shared memory parallelisation options.

**Comment by alalazo** [comment]
> could you please address it in your blas/lapack PR to make variant names in atlas and openblas consistent?

@davydden sure
