### ISSUE TITLE
Behavior on Missing Dependency Version

### ISSUE THREAD

**Issue by ax3l** [LLNL/spack#1700]
When I am running a `spack install` on an explicit version of an optional dependency that can not be satisfied spack does not abort but continues with "some other" version.

```
$ spack install adios +hdf5 ^hdf5@1.9 # does not exist
[...]
Can not find version 1 in url_list
==> Trying to fetch from http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.0-patch1/src/hdf5-1.10.0-patch1.tar.gz
[...]
# just chooses 1.10.0-patch1, the next found HDF5 version, instead
```

I think it should abort instead since my explicit requirement can not be fulfilled.

**Comment by adamjstewart** [comment]
It looks like this was fixed at some point:
```
$ spack install adios +hdf5 ^hdf5@1.9
[...]
==> Warning: There is no checksum on file to fetch hdf5@1.9 safely.
==>   Fetch anyway? [y/N]
```
Reopen if you find another package to reproduce it with.
