### ISSUE TITLE
Building a Dependency on libtool and mpi fails

### ISSUE THREAD

**Issue by ax3l** [LLNL/spack#1701]
I am running the latest `develop` as of f5bc0cbb65c95249b3f1fd1b5c63da5a03acbded and am building adios
- `depends_on('libtool', type='build')`
-  `depends_on('mpi', when='+mpi')` while `mpi=True` is the default

.

Doing a `spack install adios` leads to an install of `libtool` itself for build and `libtool` again due to `mpi` with `^libsigsegv@2.10%gcc@4.9.2`
```bash
$ spack graph --concretize openmpi
o  openmpi
o  hwloc
o  libpciaccess
o  libtool
o  m4
o  libsigsegv
```
This results in an error while `spack install`-ing adios, directly after building `openmpi`:
```
==> Building openmpi
==> Successfully installed openmpi
  Fetch: 10.65s.  Build: 10m 40.85s.  Total: 10m 51.50s.
[+] [...]/opt/spack/linux-debian8-x86_64/gcc-4.9.2/openmpi-2.0.0-[...]

==> Error: Specs libtool@2.4.6%gcc@4.9.2
  arch=linux-debian8-x86_64^libsigsegv@2.10%gcc@4.9.2
    arch=linux-debian8-x86_64^m4@1.4.17%gcc@4.9.2+sigsegv
    arch=linux-debian8-x86_64
  and
  libtool@2.4.6%gcc@4.9.2
    arch=linux-debian8-x86_64
  have the same SHA-1 prefix!
```

I cleaned my repo with
```bash
rm -rf /tmp/$(whoami)/spack-stage bin/ etc/ lib/ opt/ share/ var/
git checkout .
```

beforehand.

**Comment by davydden** [comment]
see https://github.com/LLNL/spack/pull/1698 for fixes of `same SHA-1 prefix`.

**Comment by ax3l** [comment]
thanks @davydden !

I will pull #1698 in and you can close this as a duplicate.
