### ISSUE TITLE
Installation issue: py-h5py

### ISSUE THREAD

**Issue by codeandkey** [LLNL/spack#17022]
### Steps to reproduce the issue

$ spack install py-h5py

### Information on your system

```
* **Spack:** 0.14.2-1378-25a837b
* **Python:** 3.7.6
* **Platform:** linux-rhel7-skylake_avx512
```

### Additional information

* [spack-build-out.txt](http://ix.io/2oJK)
* [spack-build-env.txt](http://ix.io/2oJJ)

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
@codeandkey did you ever resolve this build issue? Looking at https://github.com/h5py/h5py/pull/1321 it looks like the h5py developers are aware of some of the changes in newer versions of HDF5 but haven't put out a new release yet. Maybe `py-h5py` requires an older version of `hdf5` to build?

**Comment by codeandkey** [comment]
Yes, the issue was resolved somewhere upstream- not sure where exactly but it builds fine now. Closing!
