### ISSUE TITLE
spack install --overwrite doesn't reinstall a package

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#17060]
### Steps to reproduce the issue

I'm having trouble reproducing this with simpler packages, but I can reliably reproduce this locally:
```console
$ spack install --overwrite readline
==> The following package specs will be reinstalled:

-- linux-ubuntu20.04-skylake / gcc@9.3.0 ------------------------
6erg6r3 readline@8.0%gcc
==> The following package specs are not installed and the --overwrite flag was given. The package spec will be newly installed:

-- linux-ubuntu20.04-skylake / gcc@9.3.0 ------------------------
6erg6r3 readline@8.0%gcc
==> Do you want to proceed? [y/N] y
[+] /home/adam/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/pkgconf-1.7.3-lwcroefxaeuqfg5nshj4wl7ps4allnsy
[+] /home/adam/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/ncurses-6.2-v3z5jtv4ztmho7onysxesbp2wqrrbn5x
[+] /home/adam/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/readline-8.0-6erg6r3ryymdcoplpwglxcfvqlpqaxxc
```
This is the full output, it isn't actually rebuilding readline for some reason, it thinks it's already installed so it doesn't have to build it again.

The only local modification I have from develop is #17059, which is why I want to reinstall readline.

### Information on your system

* **Spack:** 0.14.2-1395-4c976dfe6
* **Python:** 3.8.2
* **Platform:** linux-ubuntu20.04-skylake (via WSL)

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
### Workarounds

I found that the following gets me the desired behavior:
```console
$ spack uninstall --force readline
$ spack install readline
```

**Comment by alalazo** [comment]
Can't reproduce with:

* **Spack:** 0.14.2-1394-3609f36e6
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-broadwell

This is what I tried:
```console
$ spack install hdf5~mpi
[+] /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-10.1.0/zlib-1.2.11-kepdmuvfmqqbsnhq54i2xrkh42aclueu
[+] /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-10.1.0/hdf5-1.10.6-lfgp3h2vfhve45jdgfg2mcpgzxa7dnil

$ spack install --overwrite zlib
==> The following package specs will be reinstalled:

-- linux-ubuntu18.04-broadwell / gcc@10.1.0 ---------------------
kepdmuv zlib@1.2.11%gcc +optimize+pic+shared
==> Do you want to proceed? [y/N] y
==> 1209: Installing zlib
[ ... ]
==> 1209: zlib: Successfully installed zlib
  Fetch: 0.00s.  Build: 3.99s.  Total: 4.00s.
[+] /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu18.04-broadwell/gcc-10.1.0/zlib-1.2.11-kepdmuvfmqqbsnhq54i2xrkh42aclueu
```

**Comment by adamjstewart** [comment]
Yeah, I couldn't reproduce this with libsigsegv and m4 either. I have no idea what is special about readline and python. Perhaps because it is an extension? Perhaps because it is present in an environment?

**Comment by darmac** [comment]
Is there any plan to fix this issue? We have encountered this too...

**Comment by adamjstewart** [comment]
It's likely going to be difficult to fix until we can figure out how to reliably reproduce it.

**Comment by daniellivingston** [comment]
I've encountered this issue on a clean install of Spack running on Ubuntu 18.04.

The workaround from @adamjstewart doesn't work for me; I've settled on this as a band-aid solution for my specific use case:

```bash
$ export PACKAGE=wrf # Spack package name to remove
$ spack find --paths ${PACKAGE} | tail -1 | awk '{print $2}' | xargs rm -rf
$ spack uninstall --force ${PACKAGE}
$ spack install --overwrite --no-cache ${PACKAGE}
```

**Comment by haampie** [comment]
Can you still reproduce @adamjstewart and @daniellivingston? There's been some changes in the installer and `--overwrite` since, in particular https://github.com/spack/spack/pull/24049 and https://github.com/spack/spack/pull/25579

**Comment by adamjstewart** [comment]
I've never been able to reproduce this reliably unfortunately.

**Comment by adamjstewart** [comment]
Let's close and hope that one of those PRs solved the issue.

**Comment by ltalirz** [comment]
I'm still seeing something slightly different, but similar in that I am unable to force spack to rebuild the package

Note: this is inside an environment

```
[root@hb2la-pg0-8 AlmaLinux-HPC-8_7-gen2-zen2-aocc]# spack install --overwrite lammps
==> The following package specs will be reinstalled:

-- linux-almalinux8-zen2 / aocc@4.0.0 ---------------------------
ixnp622 lammps@20220623.4%aocc ~adios~asphere~atc~awpmd~bocs~body~bpm~brownian~cg-dna~cg-sdk~class2~colloid~colvars~compress~coreshell~cuda~cuda_mps~dielectric~diffraction~dipole~dpd-basic~dpd-meso~dpd-react~dpd-smooth~drude~eff~electrode~exceptions~extra-compute~extra-dump~extra-fix~extra-molecule~extra-pair~fep~ffmpeg~granular~h5md+intel~interlayer~ipo~jpeg~kim+kokkos+kspace~latboltz~latte+lib~machdyn~manifold+manybody~mc~meam~mesont~mgpt~misc~ml-hdnnp~ml-iap~ml-rann~ml-snap~mofff+molecule~molfile+mpi~mpiio~netcdf~opencl+openmp+openmp-package~opt~orient~peri~phonon~plugin~plumed~png~poems~ptm~python~qeq~qtb~reaction~reaxff~replica+rigid~rocm~shock~smtbq~sph~spin~srd~tally~uef~voronoi~vtk~yaff build_system=cmake build_type=RelWithDebInfo fftw_precision=double generator=make lammps_sizes=smallbig
==> Do you want to proceed? [y/N] y
==> All of the packages are already installed
```

**Comment by HealthyPear** [comment]
I have the exact same issue as @ltalirz : I need to update the installation of a package for which there has been a PR merge here and even with `spack install --reuse-deps --overwrite --no-cache blabla` it simply tells me that is already installed.

**Comment by karqo** [comment]
I also observe exactly this issue, that is, obtaining
`==> All of the packages are already installed`
only.

**Comment by HealthyPear** [comment]
I'll open a new issue so it gets proper attention.
