### ISSUE TITLE
Documentation should have pointer to Github repo

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#171]
I was looking at the Spack documentation, and there doesn't seem to be a link pointing to the Github repo that's easy to find. I would have expected such a link in two places -- in the left column of `http://scalability-llnl.github.io/spack/`, and in the text that suggests opening pull requests.

**Comment by mathstuf** [comment]
Hmm, a quick look at how rst's `toctree` works, I don't see a way to add an absolute link to the left panel.

**Comment by adamjstewart** [comment]
Currently, there is a link to the GitHub repo on the documentation homepage and in the Getting Started section. I think this is sufficient. Thoughts?

**Comment by adamjstewart** [comment]
As @mathstuf said, I don't know of a way to include an absolute link on the left-hand navigation panel. But at this point, there is a link to the GitHub repo on the documentation homepage, Getting Started section, and the Contribution Guide, so I think we have enough of our bases covered. I'm going to close this issue, but feel free to reopen it if you don't feel like this is sufficient.
