### ISSUE TITLE
non-boolean variants are not documented

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#1710]
subj.

**Comment by davydden** [comment]
document in packaging guide and/or their usage in intro, i.e. `$ spack spec arpack-ng ^openblas threading=openmp`. note the space between `openblas` and `threading`.

**Comment by adamjstewart** [comment]
It's already documented in http://spack.readthedocs.io/en/latest/basic_usage.html#variants

**Comment by davydden** [comment]
i missed that, i was looking in `Packaging guide`. Still, there is no example on how to use them for conretization.
