### ISSUE TITLE
Pipelines: Option to cache a cloned spack

### ISSUE THREAD

**Issue by scottwittenburg** [LLNL/spack#17119]
Currently we allow one of two modes of operation:

1. Assume spack command is already available in the runner environment, so we take no action.
2. Allow user to provide `--spack-repo` and `--spack-ref` arguments to the `spack ci generate ...` command, which will cause all jobs to be generated with essentially the following `before_script`:

```
git clone ${SPACK_REPO}
pushd ./spack && git checkout ${SPACK_REF} && popd
. "./spack/share/spack/setup-env.sh"
```

and `after_script':

```
rm -rf ./spack
```

We propose to support a third mode of operation, where if the runner supports it, we can cache the cloned spack so that it doesn't need to be cloned before every job.

### Rationale

The spack project has a lot of history, which results in needed to write a lot of files every time it is cloned.  Because we need to support checking out an arbitrary SHA of spack, we can no longer use some of the shallow cloning and single branch cloning approaches we used at one time.  When every job needs to clone spack, it can overload a filesystem with file I/O activity.

### Description

One assumption we have made until now is that within the environment repo, spack will be cloned directly at the root of the repository, and this feature will continue to rely on that assumption.  Implementation of the feature should require no change to how users invoke `spack ci generate ...`, but should only require us to implement some checks and perhaps extra steps within the generated build jobs:

- Add a `cache` declaration to each job, specifying the spack directory as the path
- Before the `clone` step in each job, check to make sure `./spack` doesn't already exist
  - If `./spack` does already exist, change into the directory and:
    1. Add `SPACK_REPO` remote if necessary (e.g. as `git remote add ci-spack ${SPACK_REPO}`)
    2. `git fetch ci-spack`
    3. git checkout ${SPACK_REF}
  - If `./spack' does not already exist, clone and checkout as we currently do
- In any case, remove the generated `after_script` that deletes spack.  

~~There may be just enough new logic in the above steps, that it could make sense to add it as spack python instead of bash code.  If so, we can either add a `spack ci` subcommand (possible names: `clone`, 'getspack', ...) which we invoke from the `before_script`, or else we can fold the new logic into the rebuild jobs.~~

On further thought, since this is about how we get our hands on spack, I don't think we can assume we have a spack to help with that.  So maybe bash is our best option at the moment.

### Caveats

For the caching of the cloned spack to work, there are some requirements on the runner.  This is an excerpt from the gitlab [documentation](https://docs.gitlab.com/12.9/ee/ci/caching/index.html#good-caching-practices) on caching:

_From the perspective of the Runner, in order for cache to work effectively, one of the following must be true:_

_Use a single Runner for all your jobs._
_Use multiple Runners (in autoscale mode or not) that use distributed caching, where the cache is stored in S3 buckets (like shared Runners on GitLab.com)._
_Use multiple Runners (not in autoscale mode) of the same architecture that share a common network-mounted directory (using NFS or something similar) where the cache will be stored._

And since the gitlab documentation on caching also says the that cache directory needs to live within the project space, I assume that means the third bullet point above assumes that your project space is sitting on that network-mounted NFS.

**Comment by scottwittenburg** [comment]
@adrienbernede @tldahlgren I've created an issue for the pipeline optimization we discussed last Friday.  Can you take a look and let me know if you think it will solve your issue?

FYI @opadron @zackgalbreath @tgamblin @eugeneswalker

**Comment by scottwittenburg** [comment]
Question for @adrienbernede or @tldahlgren: When were discussing this on Friday, @tgamblin mentioned that multiple pipelines would potentially be re-using the cached spack, and thus we would maybe need that `git fetch` and `git reset` mentioned above.  But I'm curious about this.  Is it possible multiple pipelines could be running simultaneously, maybe needing different versions of spack?

**Comment by tldahlgren** [comment]
> @adrienbernede @tldahlgren I've created an issue for the pipeline optimization we discussed last Friday. Can you take a look and let me know if you think it will solve your issue?

This issue is consistent with what I recall from last Friday's meeting.  It should prove to make the process of testing environments (`spack.yaml`) far more efficient in terms of file system access.

**Comment by adrienbernede** [comment]
@scottwittenburg Thank you for tackling this.

I have to admit I barely played with caches in GitLab, mainly because the prerequisites are not straightforward, at least at first.

If I understand correctly, caching will allow to reuse a path for a given job, in subsequents pipelines.
The consequences are:
- if we have 100 jobs, we still need to store 100 clones of Spack.
- if the job name changes, we need to clone Spack again.
That is to say I wonder in this will completely addresses our need. Also, does it actually works with generated jobs?

You said the assumption was that Spack be in the job working directory/root dir. Why can’t this assumption be broken?
- `before_script` loads Spack, so I though all we needed was Spack to be loaded. That’s why we had this idea of using the _same_ unique Spack instance.
- Also, wouldn’t it work if Spack was sym-linked?

**Comment by scottwittenburg** [comment]
> @scottwittenburg Thank you for tackling this.
> 
> I have to admit I barely played with caches in GitLab, mainly because the prerequisites are not straightforward, at least at first.

Agreed.  I read through the documentation a couple times today to figure out how we could (maybe) use it.

> If I understand correctly, caching will allow to reuse a path for a given job, in subsequents pipelines.

There are tons of ways you can use the caching, assuming you meet one of the criteria I pasted above (I'm guessing in your case, you either have a single runner (1) or your runners have a shared filesystem (3)).  But what you suggested is just one way.  You can also have a cache created in an initial job and used by the rest of the jobs in the pipeline, which is how I thought we would use this feature.

> The consequences are:
> 
> * if we have 100 jobs, we still need to store 100 clones of Spack.

I feel like that would be terrible, we won't do it if that's what it means.

> * if the job name changes, we need to clone Spack again.

You can use any predefined environment variable as a cache key, or just have a global cache all your jobs use.

>   That is to say I wonder in this will completely addresses our need. Also, does it actually works with generated jobs?

I will need to make a few changes to the spack ci code in order to support this, if that's what you mean.  But it shouldn't be too big of a change.

> You said the assumption was that Spack be in the job working directory/root dir. Why can’t this assumption be broken?

As I work to implement the feature, it may turn out that assumption could be relaxed (or just go away I guess).  When I have a PR for this, I'll link to this issue so anyone who gets involved here will be notified.

> * `before_script` loads Spack, so I though all we needed was Spack to be loaded. That’s why we had this idea of using the _same_ unique Spack instance.

As long as I have your attention, where is the spack you want to use in your jobs located, and how is that related to your jobs project directory?  Totally different I guess?  If it's not in the project directory but on some arbitrary shared file system, I don't think the notion of gitlab caching would even help.  Their documentation states that anything you want to cache has to reside within the project directory.

> * Also, wouldn’t it work if Spack was sym-linked?

Do you mean if there was a sym-link to some other spack directory in the environments root directory (sibling to `spack.yaml` and `.gitlab-ci.yml`)?  I'm not sure, but that might be true.

Thanks for your thoughts and questions.

**Comment by adrienbernede** [comment]
You clearly spent time thinking the details, so I trust you on the usage of cache here :).

We would typically use a specific reference in github spack or a clone. But to answer your question about spack location, here is what I would have done if I were able to customize the `before_script`:

```
# Store spack in a custom cache location (NFS case), i.e. using ${CI_BUILDS_DIR}, the parent directory of all builds directories.
variables:
  SPACK_LOCATION: ${CI_BUILDS_DIR}/{CI_PROJECT_NAME}/spack

# Preparation job, overriding before_script
get_spack:
  before_script:
  script:
    - if [[ -d ${SPACK_LOCATION} ]]; then git clone ${SPACK_URL} ${SPACK_REF} ${SPACK_LOCATION}; fi
    - cd ${SPACK_LOCATION}
    - git_checkout ${SPACK_REF}

# Before script definition (could go in spack.yaml)
before_script:
    - cd ${SPACK_LOCATION}
    - . share/spack/setup-env.sh

# spack generate job
...
```

It’s interesting to see that I may simply not have the same constraints as you in my usage of GitLab, hence the fact I end up with a solution that may be simpler (to me at least) but not portable (NFS hypothesis).

**Comment by scottwittenburg** [comment]
@adrienbernede Yeah, I think leaving it to users to provide their own scripts is much nicer.  I took an initial stab at that in #17129.

**Comment by scottwittenburg** [comment]
I created a new issue (#17164) because this one describes an approach that doesn't really solve the problem experienced by some folks.

**Comment by scottwittenburg** [comment]
Closing in favor of #17164
