### ISSUE TITLE
vtk8.2 python modules do not get loaded in PYTHONPATH

### ISSUE THREAD

**Issue by bhatiaharsh** [LLNL/spack#17126]
Maintainers: @chuckatkins @danlipsa

It appears `vtk` restructured their python bindings starting `8.2.0` (https://blog.kitware.com/vtk-8-2-0/). However, this change is apparently not reflected in `spack`, and therefore, I am not getting the correct `PYTHONPATH`.

### Steps to reproduce the issue

I can install version `8.2.0` successfully, and it puts python bindings in `lib64`. Upon loading the package, `spack` puts `lib` in the `PYTHONPATH`, and I cannot import the python package.

```console
$ spack install vtk@8.2.0 +python # i installed with +mpi+osmesa, but that should not matter here
$ spack cd -i vtk@8.2.0
$ ls lib/python3.7/site-packages/          # returns empty
$ ls lib64/python3.7/site-packages/
vtk.py	vtkmodules

$ spack load -r vtk@8.2.0
$ echo $PYTHONPATH
$SPACK_ROOT/opt/spack/linux-rhel7-broadwell/gcc-7.3.0/vtk-8.2.0-75xr5zuecmun6av2rmgbrzjammyh62sz/lib/python3.7/site-packages: .....
```

Here is the behavior for `vtk@8.1.2` (works correctly)
```console
$ spack install vtk@8.1.2 +python # i installed with +mpi+osmesa, but that should not matter here
$  spack cd -i vtk@8.1.2
$ ls lib/python3.7/site-packages/
vtk               # python package
$ ls lib64/python3.7/site-packages/          # does not exist

$ spack load -r vtk@8.1.2
$ echo $PYTHONPATH
$SPACK_ROOT/opt/spack/linux-rhel7-broadwell/gcc-7.3.0/vtk-8.1.2-6emg5zldy6rw5qgcf33x7s3unh55s6z6/lib/python3.7/site-packages: ....
```

### Information on your system

Tried this on `linux-rhel7-broadwell` architecture. 

### General information

- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
We could modify the `python` package to check both `lib/pythonX.Y/site-packages` and `lib64/pythonX.Y/site-packages`, but I've literally never seen a package that uses the latter. Was this a mistake made by the VTK team or do they know more than me?

**Comment by mathstuf** [comment]
lib64 is picked up from the host's preferred library directory. Spack can pass `CMAKE_INSTALL_LIBDIR=lib` to always use it instead.
