### ISSUE TITLE
"More documentation" link missing

### ISSUE THREAD

**Issue by adrienbernede** [LLNL/spack#17135]
Documentation does not always link a command to its documentation.

This link is useful because, IMO, it makes is easy to find a command documentation from command reference page.

### Steps to reproduce the issue

Command Reference (in command_index.in) states:
> Commands that also have sections in the main documentation have a link to
> "More documentation".

I see this link for `spack clean` (points to spack clean in packaging_guide), but not for `spack ci` and associated subcommands (should point to spack ci in pipelines).

### Error Message

I tried re-building the documentation, no sign of error.

### Information on your system

I don’t think it depends on the system

### Additional information

I read a bit more about this, and talked to @becker33:
- If `spack ci` should be referenced somewhere for the link to be generated, I couldn’t find where.
- On the contrary, I think this is supposed to be automatically generated through `SpackArgparsRstWriter()` and `rst()` functions, but I could not find what’s wrong with `spack ci` in particular, or `pipeline.rst`.

Maybe @scottwittenburg has some clues too?

**Comment by scottwittenburg** [comment]
Thanks for reporting @adrienbernede, I wasn't aware of that linking functionality.  I'm not sure how to make that happen for the `spack ci` command, but I'll look into it.

**Comment by adrienbernede** [comment]
Not sure if it’s specific to `spack ci` :).
