### ISSUE TITLE
Concretizer: 'xsdk' version in package is wrongly accepted

### ISSUE THREAD

**Issue by sethrj** [LLNL/spack#17145]
Related to https://github.com/spack/spack/pull/9445: concretizing an older nonexistent version is causing an `xsdk` version to be accepted even though the xsdk tags are not related to the actual version number.

### Steps to reproduce the issue

```console
$ spack spec superlu-dist@:4.3
Input spec
--------------------------------
superlu-dist@:4.3

Concretized
--------------------------------
superlu-dist@xsdk-0.2.0 <snip...>
```

### Information on your system

```
$ spack debug report
* **Spack:** 0.14.2-1466-32e5480ae
* **Python:** 3.7.6
* **Platform:** linux-rhel7-skylake_avx512
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by sethrj** [comment]
I'm pretty sure this happened because non-numeric tags sort "before" numeric tags but are still included in the open ranges; and https://github.com/spack/spack/pull/9445 erroneously deleted the 4.3 versions of superlu-dist.

**Comment by sethrj** [comment]
See https://github.com/spack/spack/issues/8421

**Comment by alalazo** [comment]
Closing, since with #36273 we can use the `@=` syntax to specify a version.
