### ISSUE TITLE
`setup_environment` for run environment not executed for dependent modules

### ISSUE THREAD

**Issue by alfredo-gimenez** [LLNL/spack#1714]
With `setup_environment`, `JAVA_HOME` is appropriately set on `spack load jdk`, which is great.

However, if I do `spack load thing_that_depends_on_jdk`, it is not set.

Seems like the behavior should be to set the runtime environment for all dependencies when loading a package. Right now I have to explicitly `spack load jdk` before loading any modules that depend on jdk, since they look for `JAVA_HOME` at runtime.

**Comment by alfredo-gimenez** [comment]
See #1713

**Comment by tmerrick1** [comment]
This is the same problem that I was having running flake8.  The `spack load py-flake8` did not include `py-setuptools` even when I changed the type to `alldeps` as it is needed for runtime too.  Nor did it include `python` which should be done automatically on all extension loads.
