### ISSUE TITLE
Cross-compiling detection/stored in the spec object

### ISSUE THREAD

**Issue by naromero77** [LLNL/spack#17239]
In support of large scale supercomputer and even mid-tier linux clusters, it would be desirable to store in the `spec` whether the the current spack install invocation is a cross-compiling scenario.

### Rationale

Here is a concrete use case:
https://github.com/spack/spack/pull/17180

Quantum ESPRESSO uses autoconf and does not have much of a concept of cross-compilation AFAIK. You have to manually add `--host` if you are in a cross-compile scenario. This flag suppresses autoconf from running config tests on the login node. That is all it does.

For package developers, it would be desirable if in the `spec` there was a boolean that took into account the architecture/platform and the compilation target to determine whether we are in a cross-compilation scenario.

### Description

The platform/architecture object stores information about the frontend and backend for both the os and the target. I think it would be simple if the `spec` where to take this information along with the target and determine if the package needs to be cross-compiled.

Both @becker33 and @alalazo where helpful for the aforementioned pull request. It is possible to detect cross-compilation fairly easily with `spec.satisfies(...)` for BG/Q and Cray, but it does not cover a Linux cluster with host login nodes that are different in architecture from the compute nodes. Also, cross-compilation is not as simple as just comparing target of the frontend versus the backend -- possibly also need to compare the os. We haven't even added accelerated into the mix here.

It would of been possible for me to just hack something together to get this done based on @alalazo suggestion, but it would be more desirable to have a consistent way for package developers to do this.

### General information

naromero@thetalogin6:~/spack> spack --version
0.14.2-1489-a20ba315f

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by commodo** [comment]
@naromero77 @tgamblin @alalazo @becker33 

i'm also interested in this cross-compilation aspect;
especially cross-compiling between 2 different architectures;
the use-case is in the direction of embedded devices;
while i understand that Spack is oriented towards HPC, we are evaluating Spack for the embedded use-case;

right now where we are is:
* we're able to cross-compile some packages to ARM64 (from an x86_64 host)
* the packages that don't cross-compile need a host-compatible compiler to build certain build-time tools

typically, (as you may know already) embedded build-systems make use of the `--host=` & `--target` directives (when building these build-time tools)
i think we should do something similar here;

at least for the embedded use-case, what would be sufficient:
1. Have a list of compilers (in `compilers.yaml`)  - one for the cross-target, and one that is host-compatible
2. In `concretizer.yaml `  set `host_compatible` to `False`
3. Spack currently picks out (correctly) the target compiler with the `target=aarch64` directive
4. (The current above stuff already exists)
5. Somewhere in the solver, we'll need to pick out a host-compatible compiler (for the embedded use-case, any compiler that produces functional host binaries is fine)
6. If there is no host-compatible compiler (in compilers.yaml) then issue a warning

This "should" handle nicely the use-case of cross-compiling packages, and then be able to use these packages on a target.

Any thoughts/ideas?

I'm currently trying to find my way a bit with selecting a host-compiler (when `host_compatible` is False).

**Comment by naromero77** [comment]
I filed this almost three years ago... by the looks of it there was some issue with compiling Quantum Espresso on a Cray supercomputer. I think that a lot of work has been done with cross-compilation.

@commodo I am not really familiar with embedded space world, have you tried the asking on the Slack channel? I have not really thought much about the `host_compatible` is False case since I am typically in the True case.

**Comment by naromero77** [comment]
I am going to close this PR, since whatever problem I had two employers ago is likely no longer a problem :)

**Comment by commodo** [comment]
I did not know about the Slack channel.
Will check it out.

It's fine for closing this issue (from my side).
Will see about spinning up a version that handles the embedded use-case.

Thanks
Alex
