### ISSUE TITLE
Installation issue: samrai:  All fetchers fail error

### ISSUE THREAD

**Issue by tldahlgren** [LLNL/spack#17243]
I am getting the following error (running from LC/Quartz) when I try to install `SAMRAI` from `develop` at commit `bc53bb9`.

```
==> Fetching https://computing.llnl.gov/projects/samrai/download/SAMRAI-v3.12.0.tar.gz

curl: (28) Connection timed out after 10001 milliseconds
==> Failed to fetch file from URL: https://computing.llnl.gov/projects/samrai/download/SAMRAI-v3.12.0.tar.gz
    Curl failed with error 28
==> Fetching from https://computing.llnl.gov/projects/samrai/download/SAMRAI-v3.12.0.tar.gz failed.
==> Error: FetchError: All fetchers failed for spack-stage-samrai-3.12.0-yxm452dtcy7wykfoblkq32pbzmdmbymb
```

Hovering over SAMRAI links at https://computing.llnl.gov/projects/samrai/software shows the URL should be accurate. Clicking on them in a web browser brings an Open/Save dialog box.

**Comment by adamjstewart** [comment]
This now "works" in the sense that we download from Spack's source mirror instead of computing.llnl.gov

**Comment by adamjstewart** [comment]
Website is back up, and fetching from either the source mirror or the original website should work.
