### ISSUE TITLE
Installation issue: sundials `all fetchers failed` error

### ISSUE THREAD

**Issue by tldahlgren** [LLNL/spack#17241]
I am getting the following error (running from LC/Quartz) when I try to install `SUNDIALS` using `develop` at commit `bc53bb9`.

```
==> Fetching https://computing.llnl.gov/projects/sundials/download/sundials-5.3.0.tar.gz

curl: (28) Connection timed out after 10001 milliseconds
==> Failed to fetch file from URL: https://computing.llnl.gov/projects/sundials/download/sundials-5.3.0.tar.gz
    Curl failed with error 28
==> Fetching from https://computing.llnl.gov/projects/sundials/download/sundials-5.3.0.tar.gz failed.
==> Error: FetchError: All fetchers failed for spack-stage-sundials-5.3.0-ezvti26nbt3evp4gximaoygtrqd4dw6r
```

Hovering over the `SUNDIALS` link at https://computing.llnl.gov/projects/sundials/sundials-software shows the URL is accurate.  Clicking on that link in a web browser brings an Open/Save dialog box.

**Comment by tldahlgren** [comment]
@gardner48  ping

**Comment by tldahlgren** [comment]
@gardner48 Recommend adding `list_url = 'https://github.com/LLNL/sundials/releases'` to the package.  This works for me.

**Comment by gardner48** [comment]
I have this same problem on quartz and lassen but not my laptop so it seems like this might be an LC issue. Adding
```
list_url = 'https://github.com/LLNL/sundials/releases'
``` 
or 
```
urls = ["https://computing.llnl.gov/projects/sundials/download/sundials-2.7.0.tar.gz",
           "https://github.com/LLNL/sundials/releases/download/v2.7.0/sundials-2.7.0.tar.gz"]
```
works for me. I'll put a PR to address this issue.

**Comment by adamjstewart** [comment]
@gardner48 did you ever get a chance to submit this PR?
