### ISSUE TITLE
Installation issue: mpfr

### ISSUE THREAD

**Issue by chchang6** [LLNL/spack#17281]
### Steps to reproduce the issue

```console
$ spack install mpfr@4.0.2 %gcc@4.8.5
...
```

### Information on your system

* **Spack:** 0.14.2-1093-701fc1f
* **Python:** 3.6.8
* **Platform:** linux-centos7-skylake_avx512

### Additional information
==> Fetching https://www.mpfr.org/mpfr-4.0.2/allpatches
######################################################################## 100.0%
==> Error: ChecksumError: sha256 checksum failed for /tmp/cchang/spack-stage/spack-stage-6ie6x_sq/allpatches
    Expected 8f15fd27ab65341a60d724d594897d32f4597ddf642d0dc121995e2150181b0c but got 3f80b836948aa96f8d1cb9cc7f3f55973f19285482a96f9a4e1623d460bcccf0

/nopt/nrel/apps/base/2020-05-12/spack/lib/spack/spack/package.py:1151, in do_fetch:
       1148
       1149        self.stage.cache_local()
       1150
  >>   1151        for patch in self.spec.patches:
       1152            patch.fetch()
       1153            if patch.stage:
       1154                patch.stage.cache_local()

==> Error: Failed to install mpfr due to ChildError: ChecksumError: sha256 checksum failed for /tmp/cchang/spack-stage/spack-stage-6ie6x_sq/allpatches
    Expected 8f15fd27ab65341a60d724d594897d32f4597ddf642d0dc121995e2150181b0c but got 3f80b836948aa96f8d1cb9cc7f3f55973f19285482a96f9a4e1623d460bcccf0
/nopt/nrel/apps/base/2020-05-12/spack/lib/spack/spack/package.py:1151, in do_fetch:
       1148
       1149        self.stage.cache_local()
       1150
  >>   1151        for patch in self.spec.patches:
       1152            patch.fetch()
       1153            if patch.stage:
       1154                patch.stage.cache_local()

Traceback (most recent call last):
  File "/nopt/nrel/apps/base/2020-05-12/spack/lib/spack/spack/build_environment.py", line 813, in child_process
    return_value = function()
  File "/nopt/nrel/apps/base/2020-05-12/spack/lib/spack/spack/installer.py", line 1056, in build_process
    pkg.do_patch()
  File "/nopt/nrel/apps/base/2020-05-12/spack/lib/spack/spack/package.py", line 1182, in do_patch
    self.do_stage()
  File "/nopt/nrel/apps/base/2020-05-12/spack/lib/spack/spack/package.py", line 1167, in do_stage
    self.do_fetch(mirror_only)
  File "/nopt/nrel/apps/base/2020-05-12/spack/lib/spack/spack/package.py", line 1152, in do_fetch
    patch.fetch()
  File "/nopt/nrel/apps/base/2020-05-12/spack/lib/spack/spack/patch.py", line 194, in fetch
    self.stage.check()
  File "/nopt/nrel/apps/base/2020-05-12/spack/lib/spack/spack/stage.py", line 490, in check
    self.fetcher.check()
  File "/nopt/nrel/apps/base/2020-05-12/spack/lib/spack/spack/fetch_strategy.py", line 72, in wrapper
    return fun(self, *args, **kwargs)
  File "/nopt/nrel/apps/base/2020-05-12/spack/lib/spack/spack/fetch_strategy.py", line 504, in check
    "Expected %s but got %s" % (self.digest, checker.sum))
spack.fetch_strategy.ChecksumError: sha256 checksum failed for /tmp/cchang/spack-stage/spack-stage-6ie6x_sq/allpatches
    Expected 8f15fd27ab65341a60d724d594897d32f4597ddf642d0dc121995e2150181b0c but got 3f80b836948aa96f8d1cb9cc7f3f55973f19285482a96f9a4e1623d460bcccf0

N/A -- installed by skipping checksum, assume staging from prior attempt deleted.

None

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
This should be fixed by #16937. Can you update to the tip of develop and try again?

**Comment by chchang6** [comment]
Just pulled today, and looks like mpfr is installing as hoped. Thanks!
