### ISSUE TITLE
Installation issue: bin utils

### ISSUE THREAD

**Issue by cbontoiu** [LLNL/spack#17294]
Hello, I am trying to install ```Spack``` on a cluster which seems to assume ```gcc@4.8.5``` as default. However I need Spack to be used by a code called ```PIConGPU``` whoose latest version makes use o ```gcc@7.4.0```.

I downloaded ``Spack``` through git, as git clone https://github.com/spack/spack.git volatile/src/spack, sourced the environment as source volatile/src/spack/share/spack/setup-env.sh and then I did ```spack compiler list | grep -q gcc@7.4.0 || spack install gcc@7.4.0 && spack load gcc@7.4.0 && spack compiler add``` once and another time with a completely fresh download of ```Spack``` I did ```spack install gcc@7.4.0~binutils```. The errors were identical as are shown below.

![image](https://user-images.githubusercontent.com/7108691/86005221-3e8ca500-ba0c-11ea-8ed6-cb074df9b13f.png)

![image](https://user-images.githubusercontent.com/7108691/86005234-43515900-ba0c-11ea-8a60-bae1a360f850.png)

Please let mek now how could I find a work around for my problem.
Many thnaks,

Cristian

**Comment by michaelkuhn** [comment]
`gcc`'s `binutils` variant is off by default (see `spack info gcc`). Can you try `spack install gcc@7.5.0+binutils` (if your Spack is new enough, otherwise stick to `@7.4.0`)?

**Comment by cbontoiu** [comment]
@michaelkuhn The same error appears with a fresh download of ```Spack``` downloaded as  ```  git clone https://github.com/spack/spack.git volatile/src/spack ``` and with ``` spack install gcc@7.5.0+binutils  ``` the same error appears. I don't know how to activate ```binutils``` and maybe this is not essential. All I wanted was to get some new version of gcc installed. I tried with 
``` spack compiler list | grep -q gcc@7.4.0 || spack install gcc@7.4.0 && spack load gcc@7.4.0 && spack compiler add``` and failed with the same arroe as below.

![image](https://user-images.githubusercontent.com/7108691/86060581-e92cb400-ba5c-11ea-92e7-e078d372e2a2.png)

**Comment by michaelkuhn** [comment]
What kind of system are you trying this on? Please paste the output of `spack debug report`.

**Comment by cbontoiu** [comment]
@michaelkuhn  

![image](https://user-images.githubusercontent.com/7108691/86103854-32a8ed80-bab5-11ea-9189-22d5e73365e7.png)

There is also this hint 

![image](https://user-images.githubusercontent.com/7108691/86104132-8adfef80-bab5-11ea-939c-0d0f2de5136f.png)

**Comment by michaelkuhn** [comment]
Thanks!

I just tried building `gcc@7.5.0` (and `@9.3.0`) on our CentOS 7 machines and got different results than you:
- Without binutils, it works fine.
- With binutils, I get the same error as you.

It seems there is some difference between our CentOS installations. There is also a long issue about similar problems (#1866).

**Comment by michaelkuhn** [comment]
Turns out my Spack repository was not up-to-date. Now that I have pulled a new version including commit cc284934490cfbf3bce53c0a0ae3c6997098c47c, I get the failure both with and without binutils.
