### ISSUE TITLE
PermissionError with different side-by-side OSes

### ISSUE THREAD

**Issue by hainest** [LLNL/spack#17304]
I recently did an in-situ upgrade from Ubuntu 19.04 to 20.04. When I try to install packages for the new OS alongside the old ones, I get a PermissionError. I believe the issue is that the proper `mkdir` command is missing since that directory is owned by me and the base error message is "Operation not permitted" (i.e., it's not _really_ a permission error).

	$ spack install zlib
	==> 19225: Installing zlib
	==> Error: Failed to install zlib due to PermissionError: [Errno 1] Operation not permitted: '/home/tim/workspace/spack/opt/spack/linux-linuxmint20-piledriver'
	==> Error: [Errno 1] Operation not permitted: '/home/tim/workspace/spack/opt/spack/linux-linuxmint20-piledriver'
	
	$ mkdir /home/tim/workspace/spack/opt/spack/linux-linuxmint20-piledriver

	$ spack install zlib
	==> 19333: Installing zlib
	<snip>
	==> 19333: zlib: Successfully installed zlib
	  Fetch: 0.46s.  Build: 2.98s.  Total: 3.44s.
	[+] /home/tim/workspace/spack/opt/spack/linux-linuxmint20-piledriver/gcc-10.0.1/zlib-1.2.11-tw26trhvzwkiql2kico7oldoeruexvuv

And everything is fine.

	$ spack find
	==> 57 installed packages
	-- linux-linuxmint18-piledriver / gcc@9.3.0 ---------------------
	<snip>

	-- linux-linuxmint20-piledriver / gcc@10.0.1 --------------------
	zlib@1.2.11

Feel free to change the title of the issue. I couldn't think of something better.

**Comment by becker33** [comment]
Do you have debug output from `spack -d install zlib` that you could paste in here? That will really help to quickly figure out what operation is causing the problem.

**Comment by hainest** [comment]
I finally had a chance to test this out again, and I didn't get the error this time. I'm now using the current head of develop (35a9626ae). Closing.
