### ISSUE TITLE
Auto-find system libraries

### ISSUE THREAD

**Issue by jrmadsen** [LLNL/spack#17319]
This may already be in the works or suggested already but here goes...

### Rationale

It is kind of annoying to generate packages.yaml files like this:

```yaml
packages:
  cmake:
    paths:
      cmake@3.14.1: /usr
```

### Description

There would be a spack command like `spack system find cmake` that would create the `packages.yaml` entry.
This `spack system find` command could have options like `--buildable <bool>`.

I want to propose a `def find_system(self)` function that packages can add to support finding pre-installed versions. This would be an optional member function that packages could provide if they want to support it and throw an error if the package doesn't support it.

This isn't necessary the solution I _want_, I would just like to see this feature available.

For CMake it might look something like:

```python
from spack import *

import re
import os
import subprocess
class Cmake(Package):
  # ...

  def find_system(self):
      # this is a dictionary where the key is the spec string and the mapped value is the path
      system_versions = {}
      # loop over the paths
      for p in os.environ.get("PATH", "").split(':'):
          exe = os.path.join(p, 'cmake')
          if os.path.exists(exe):
              version = subprocess.check_output([exe, "--version"]).decode('ascii').split()[2]
              # generate the spec as the key and the root path
              system_versions["@{}".format(version)] = os.path.dirname(p)
 
    # this would be something like:
    # { "3.14.1" : "/usr" } when /usr/bin/cmake was 3.14.1
    return system_versions
```

### General information

- [ ] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by jrmadsen** [comment]
It actually looks like there is already a way to determine the spec info in `cmake/package.py`:

```python
    @classmethod
    def determine_spec_details(cls, prefix, exes_in_prefix):
        # ...
```

This makes it easier. Maybe just something like:

```python
  def find_system(self, prefix):
      # this is a dictionary where the key is the spec string and the mapped value is the path
      system_versions = {}
      for p in prefix:
          _spec = determine_spec_details(p, ["cmake"])
          if _spec is not None:
             system_versions[_spec] = os.path.dirname(p)
 
    # this would be something like: { "cmake@3.14.1" : "/usr" } when /usr/bin/cmake was 3.14.1
    return system_versions
```

**Comment by jrmadsen** [comment]
Also something like `spack system list cmake` would be nice to list everything that might be generated

**Comment by becker33** [comment]
I think what you want is the `spack external find` command.

I'm going to close this issue as we already have this functionality. It is supported on a package-by-package basis, so PRs are welcome to add it to packages you care about.

**Comment by jrmadsen** [comment]
@becker33 Good to know it exists, doesn't seem to do anything though:

```console
$ grep -rih  'def ' /opt/spack/var/spack/repos/builtin/packages | sort -u | egrep 'find|external'
        def find_optional_library(name, prefix):
     def resolve_external(self, func, sect):
    def external_prefix(self):'

/opt/spack/var/spack/repos/builtin/packages/zziplib/python2to3.patch:     def resolve_external(self, func, sect):
/opt/spack/var/spack/repos/builtin/packages/mfem/package.py:        def find_optional_library(name, prefix):
/opt/spack/var/spack/repos/builtin/packages/cray-libsci/package.py:    def external_prefix(self):
```

So where is the info on how to do this?

**Comment by alalazo** [comment]
>So where is the info on how to do this?

@jrmadsen [Here](https://spack.readthedocs.io/en/latest/build_settings.html#cmd-spack-external-find) you can find documentation on the feature, while [here](https://spack.readthedocs.io/en/latest/packaging_guide.html#making-a-package-discoverable-with-spack-external-find) it is explained how to make a package discoverable. Also, there's #16526 that extends on previous work done on external package detection and is on the roadmap for v0.16.0. The PR comes with doc changes, so if you want to get a sense of what it does you can start by reading the `rst` files :wink:
