### ISSUE TITLE
Installation issue: eospac@6.4.0 % gcc@10.1.0

### ISSUE THREAD

**Issue by KineticTheory** [LLNL/spack#17370]
### Context

* I have no problem building `spack install eospac@6.4.0 % gcc@7.5.0`
* On a different machine I have successfully build this version with intel-17, intel-18, intel-19, gcc-6.4.0, and more.  This issue seems to be specific to `gcc@10:`.

### Steps to reproduce the issue

```console
$ spack install gcc@10.1.0
# add gcc@10.1.0 to compilers.yaml
$ spack install eospac@6.4.0 % gcc@10.1.0
```

### Information on your system

* **Spack:** 0.15.0
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-ivybridge

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/4869879/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/4869881/spack-build-out.txt)

* Main build error:

```
/home/kellyt/spack-0.15.0/lib/spack/env/gcc/gcc   -O -I/tmp/kellyt/spack-stage/spack-stage-eospac-6.4.0-a34lrdg2uj6kilznlbuzdqwekxpjmsad/spack-src/Source/include/x86_64-avx-ubuntu18-linux-gnu/gcc -I/tmp/kellyt/spack-stage/spack-stage-eospac-6.4.0-a34lrdg2uj6kilznlbuzdqwekxpjmsad/spack-src/Source/ses_io/include -L/tmp/kellyt/spack-stage/spack-stage-eospac-6.4.0-a34lrdg2uj6kilznlbuzdqwekxpjmsad/spack-src/Source/lib/x86_64-avx-ubuntu18-linux-gnu/gcc  -o /tmp/kellyt/spack-stage/spack-stage-eospac-6.4.0-a34lrdg2uj6kilznlbuzdqwekxpjmsad/spack-src/Source/example/x86_64-avx-ubuntu18-linux-gnu/gcc/TestC /tmp/kellyt/spack-stage/spack-stage-eospac-6.4.0-a34lrdg2uj6kilznlbuzdqwekxpjmsad/spack-src/Source/_OBJ/x86_64-avx-ubuntu18-linux-gnu/gcc/TestC.o -leospac6 -lm

/tmp/kellyt/spack-stage/spack-stage-eospac-6.4.0-a34lrdg2uj6kilznlbuzdqwekxpjmsad/spack-src/Source/lib/x86_64-avx-ubuntu18-linux-gnu/gcc/libeospac6.a(_globals.o):(.bss+0x0): multiple definition of `_number_open_handles'
/tmp/kellyt/spack-stage/spack-stage-eospac-6.4.0-a34lrdg2uj6kilznlbuzdqwekxpjmsad/spack-src/Source/lib/x86_64-avx-ubuntu18-linux-gnu/gcc/libeospac6.a(eos_SesUtils.o):(.bss+0x0): first defined here
```

Ping @certik @junghans 

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by certik** [comment]
Thanks for the report @KineticTheory. I don't have time right now to debug it unfortunately.
