### ISSUE TITLE
Failed to fetch OpenFoam source code

### ISSUE THREAD

**Issue by iWangJiaxiang** [LLNL/spack#17438]
OpenFoam source code fetch url gets redirected because of sourceforge.

The link <https://sourceforge.net/projects/openfoam/files/v2006/OpenFOAM-v2006.tgz> will be led to

![image](https://user-images.githubusercontent.com/19409802/87025610-35ba8100-c20d-11ea-9e96-510d5ba30cce.png)

### Steps to reproduce the issue

```console
$ spack mirror create openfoam
```

### Error Message

```console
==> Adding package openfoam@2006 to mirror
==> openfoam: 2006
==> Fetching https://develop.openfoam.com/Development/openfoam/commit/8831dfc58b0295d0d301a78341dd6f4599073d45.patch
####################################################################################################################################################################################################### 100.0%
==> Already downloaded /tmp/root/spack-stage/spack-stage-jwd648ct/8831dfc58b0295d0d301a78341dd6f4599073d45.patch
==> Already downloaded /tmp/root/spack-stage/spack-stage-jwd648ct/8831dfc58b0295d0d301a78341dd6f4599073d45.patch
==> Warning: Error while fetching openfoam@2006
  sha256 checksum failed for /tmp/root/spack-stage/spack-stage-jwd648ct/8831dfc58b0295d0d301a78341dd6f4599073d45.patch

```

### Additional information

- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
@olesenm

**Comment by olesenm** [comment]
Not sure what is going on here. Are you able to fetch one of the older versions? Just to identify where the problem is

**Comment by olesenm** [comment]
Looks like the sha might have changed somewhere along the way.

**Comment by Julius-Plehn** [comment]
> Looks like the sha might have changed somewhere along the way.

Yes, the hash of `8831dfc58b0295d0d301a78341dd6f4599073d45.patch` changed to `531146be868dd0cda70c1cf12a22110a38a30fd93b5ada6234be3d6c9256c6cf`

**Comment by olesenm** [comment]
Interesting, it looks to be pulling the patch for 1806 which isn't actually needed. I guess this was cached on my system and so didn't trigger the issue.

**Comment by olesenm** [comment]
https://github.com/spack/spack/pull/17483

**Comment by olesenm** [comment]
@iWangJiaxiang - in case this takes longer to resolve, you can use a local hack to comment out the patch for 1806.
