### ISSUE TITLE
spack hangs on centos 7 probably a lock error 

### ISSUE THREAD

**Issue by robertosussex** [LLNL/spack#17460]
Hi there,

I have installed spack on the login node of our cluster. It was working fine. However, after and NFS remount of the home directories where the user have their data (including mine) spack hangs. For instance

 source share/spack/setup-env.sh
-bash-4.2$ spack --debug find
==> [2020-07-10-14:43:38.701278, 25090] Imported find from built-in commands
==> [2020-07-10-14:43:38.702756, 25090] Imported find from built-in commands
==> [2020-07-10-14:43:38.703585, 25090] Reading config file /mnt/maths/rs558/spa                   ck/etc/spack/defaults/config.yaml
==> [2020-07-10-14:43:38.729605, 25090] DATABASE LOCK TIMEOUT: 3s
==> [2020-07-10-14:43:38.729749, 25090] PACKAGE LOCK TIMEOUT: No timeout
==> [2020-07-10-14:43:38.730461, 25090] READ LOCK (database): /mnt/maths/rs558/s                   pack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2020-07-10-14:43:38.731264, 25090] read locking [0:0]: timeout 3 sec

We had similar problems in the past for instance with Jupyter notebook and the solution was to change the config to save db files to a non NFS mounted volume or to memory. Any similar possibility in spack? Or any other suggestion ?

Many thanks

Roberto

**Comment by tgamblin** [comment]
What version of NFS is this, and is the lock server running properly if it's version 3?

Does this command reliably succeed on your nodes?

```console
$ spack test lib/spack/spack/test/llnl/util/lock.py
```

**Comment by robertosussex** [comment]
I managed by changing
  build_stage:
    - /tmp/rs558/$user/spack-stage
    - /tmp/rs558/.spack/stage

in 

./etc/spack/defaults/config.yaml

and creating a symbolic link

.spack-db -> /tmp/rs558/.spack-db

in 

/its/home/rs558/spack/opt2/spack


Many thanks



Roberto
