### ISSUE TITLE
"spack ci" unit tests add a test mirror to user configuration

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#17479]
Running:
```console
spack test lib/spack/spack/test/cmd/ci.py 
```
changes user configuration by adding a "local_mirror" that is apparently used for testing purposes.

### Steps to reproduce the issue
The issue can be reproduced like this:
```console
$ spack mirror list
spack-public    https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/

$ spack test lib/spack/spack/test/cmd/ci.py 
[ ... ]

$ spack mirror list
spack-public    https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/
local_mirror    file:///tmp/pytest-of-culpo/pytest-19/test_ci_rebuild_basic0/working_dir/local_mirror
```

### Error Message

No error message, but the user configuration gets changed by Spack unexpectedly. 

As a side note, the tests above are failing when run on their own while they pass when they are run as part of the entire suite (so they might be depending on some global state set by previous tests to pass).

### Information on your system

* **Spack:** 0.15.1-107-9c42f246e
* **Python:** 3.7.4
* **Platform:** linux-ubuntu18.04-broadwell

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands ~in debug mode~ and reported the output

**Comment by adamjstewart** [comment]
Possible duplicate of #15376?

**Comment by alalazo** [comment]
Duplicate of #15736

**Comment by alalazo** [comment]
@adamjstewart I would be for not closing this issue, though it is definitely a duplicate, since it has a shorter title and a simpler reproducer. When I opened this issue I tried to search if something was reported already but didn't find the issue above.

**Comment by adamjstewart** [comment]
I would be fine with closing my old issue, as long as it gets fixed I don't mind which issue is used to track it.

**Comment by alalazo** [comment]
Unreproducible as of 65556eb53e184e78aaacce2a9e325ea4507bca2c
