### ISSUE TITLE
Want issue label "minor package update"

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1749]
I have several pull requests open that are almost no-brainers -- they update e.g. the `cereal` package from version `1.2` to `1.2.1`, with no other change. I hope that by labelling such pull requests accordingly, code review becomes simpler, and the turn-around time is reduced.

**Comment by citibeth** [comment]
Does #1772 work for you?

**Comment by eschnett** [comment]
Sure.

**Comment by adamjstewart** [comment]
Closing in favor of #1772, which is more complete.
