### ISSUE TITLE
Output environment at beginning of log file

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#175]
I'm trying to debug a build problem. I see the `configure` command, but `configure` also looks at environment variables. It would be good to add the equivalent of `env | sort` at the beginning of the log file.

**Comment by becker33** [comment]
You can use the command

spack env <package>

to get the environment settings for any install.

**Comment by tgamblin** [comment]
We should probably output the environment in a separate file in `$prefix/.spack`.

If you want to debug a build, there is the `spack env` option Greg recommends above.  You can also get a shell that will allow you to run the spack compilers by hand (`cc`, `c++`, `fc`, `f77`) the way Spack would like this:
```
    spack stage <spec>
    spack cd <spec>  # requires sourcing setup-env.sh
    spack env <spec> bash    # launches a shell with the build env
```

**Comment by tgamblin** [comment]
Made a PR that writes out the environment along with the build log
