### ISSUE TITLE
"spack fetch" does not have "hg" executable in path

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1750]
I am developing a package `py-yt` that declares this dependency:

``` Python
    depends_on("mercurial", type="build")
```

and yet fails with this error:

```
$ spack -k fetch py-yt
==> Warning: You asked for --insecure. Will NOT check SSL certificates.
==> Trying to fetch from file:///home/eschnett/src/spack-yt/var/spack/cache/py-yt/py-yt-3.3.1.tar.gz
curl: (37) Couldn't open file /home/eschnett/src/spack-yt/var/spack/cache/py-yt/py-yt-3.3.1.tar.gz
==> Fetching from file:///home/eschnett/src/spack-yt/var/spack/cache/py-yt/py-yt-3.3.1.tar.gz failed.
==> Trying to clone Mercurial repository:
  https://bitbucket.org/yt_analysis/yt
==> Error: spack requires hg.  Make sure it is in your path.
```

Any pointers towards correcting the `mercurial` package to properly provide the `hg` executable are appreciated.

**Comment by adamjstewart** [comment]
Hmm, this should be handled by `lib/spack/spack/fetch_strategy.py`:
```python
    @property                                                                   
    def hg(self):                                                               
        if not self._hg:                                                        
            self._hg = which('hg', required=True)                               
        return self._hg        
```
As long as hg is in your PATH, it _should_ work. Adding mercurial as a dependency might not be the best way to go as it isn't really a build dependency. Like, we don't list git as a dependency for packages that download from git.

But if you really want to hack the mercurial package just to get it working, see Autoconf's `setup_dependent_package` method.
