### ISSUE TITLE
having an opengl dependency fails with a confusing error message

### ISSUE THREAD

**Issue by cyrush** [LLNL/spack#17512]
Running on linux, trying to test installing visit, I hit the following error:

### Steps to reproduce the issue

```console
$ spack spec visit  ^python+shared ^glib@2.56.3 ^py-setuptools@44.1.0
```

### Error Message
```console
==> Error: There are no valid versions for opengl that match ':'
```
@becker33  informed me this is b/c opengl is a non-buildable virtual package, to solve this we can inject the mesa as opengl:

```console
$ spack spec visit  ^python+shared ^glib@2.56.3 ^py-setuptools@44.1.0  ^mesa+opengl
```

### Information on your system

This was on pascal @ LLNL.

**Comment by cyrush** [comment]
More context from Greg:

That appears to be a Spack bug. You should be able to work around it by adding ^mesa+opengl to your spec, or by configuring an external opengl to use the system version.
Could you also open an issue about this? The opengl package currently is only a placeholder for the OS provider, and that means it’s not buildable at the moment. In the long run we need to fix that, but in the short run you should be able to work around it via one of the methods above

**Comment by jrood-nrel** [comment]
I've been hitting this a lot. I can't figure out how to set a gl provider in such a way to always use mesa.

**Comment by glennpj** [comment]
According to `git bisect` this problem began with the change to the gl provider in #14572.

**Comment by opadron** [comment]
I've also been running into this, and other strange concretizer behavior with `gl`.  (#17663)

I also ran into a situation that caused the concretizer to run in an infinite loop.  I'm going to wait and see if the above fix does anything to fix things before submitting another issue.

**Comment by opadron** [comment]
@jrood-nrel Have you tried overriding the `gl` and `glx` providers in your `packages` config to prefer `mesa`?

```YAML
packages:
  all:
    providers:
      gl: [mesa+opengl~glvnd, ...]
      glx: [mesa+glx~glvnd, ...]
```

You should also be able to use mesa through libglvnd, if you wanted to go that route.  That's how the providers are setup by default.

All this is with the caveat that the changes in #14572 might be hitting corner cases in the concretizer and making a mess of things.  I plan on digging further into what's going on and trying to clean things up.

**Comment by jrood-nrel** [comment]
Hmm, I think that is what I was trying, but I will look again.

**Comment by jrood-nrel** [comment]
Oh, without the `~glvnd` though. So maybe that's it.

**Comment by opadron** [comment]
After taking a closer look, we decided to revert #14572 for now (#17682).  We will be (re)iterating on the changes in a new PR and making sure nothing gets accidentally left out this time around.

@jrood-nrel @cyrush, could you try your specs with the latest `develop` and let me know if you're still encountering problems?  Note that `libglvnd` is no longer a "thing" until we merge a fixed version of the branch, so maybe try on a clean clone of spack?

**Comment by pat-s** [comment]
Just stumbled across this issue - `^opengl` workaround helped.

**Comment by alalazo** [comment]
Cannot reproduce with 65556eb53e184e78aaacce2a9e325ea4507bca2c
