### ISSUE TITLE
Installation issue: Trilinos

### ISSUE THREAD

**Issue by carsonwoods** [LLNL/spack#17530]
On Trilinos 12.12.1, Spack will fail to install when compiling with OpenMP support if the compiler is gcc@9.3.0. 

```console
$ spack install trilinos@12.12.1 %gcc@9.3.0 +openmp
...
```

### Information on your system

```console
$ spack debug report
* **Spack:** 0.14.2-1768-fa614404e
* **Python:** 3.6.7
* **Platform:** linux-ubuntu18.04-skylake_avx512
```

### Additional information
[spack-build-env.txt](https://github.com/spack/spack/files/4919941/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/4919942/spack-build-out.txt)

@aprokop 
@keitat 
### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by aprokop** [comment]
Does not seem like a Spack issue:
```
/tmp/cwwoods/spack-stage/spack-stage-trilinos-12.12.1-pvbxkv2yoybbuelv3u3yckpzanzhxre5/spack-src/packages/epetra/src/Epetra_CrsGraph.cpp:1949:7: error: 'numMyBlockRows' not specified in enclosing 'parallel'
 1949 |       for(int i = 0; i < numMyBlockRows; i++) {
      |       ^~~
/tmp/cwwoods/spack-stage/spack-stage-trilinos-12.12.1-pvbxkv2yoybbuelv3u3yckpzanzhxre5/spack-src/packages/epetra/src/Epetra_CrsGraph.cpp:1947:9: error: enclosing 'parallel'
 1947 | #pragma omp parallel for default(none) shared(indexOffset,all_indices,indices)
      |         ^~~
/tmp/cwwoods/spack-stage/spack-stage-trilinos-12.12.1-pvbxkv2yoybbuelv3u3yckpzanzhxre5/spack-src/packages/epetra/src/Epetra_CrsGraph.cpp:1989:6: error: 'numMyBlockRows' not specified in enclosing 'parallel'
 1989 |      for(int i = 0; i < numMyBlockRows; i++) {
      |      ^~~
/tmp/cwwoods/spack-stage/spack-stage-trilinos-12.12.1-pvbxkv2yoybbuelv3u3yckpzanzhxre5/spack-src/packages/epetra/src/Epetra_CrsGraph.cpp:1987:9: error: enclosing 'parallel'
 1987 | #pragma omp parallel for default(none) shared(indexOffset,old_all_indices,new_all_indices)
```
Need current Trilinos developers to weigh in.

@carsonwoods Is there a reason for you to use a 3-year old version of Trilinos?

**Comment by carsonwoods** [comment]
@aprokop I'm converting an existing software environment that uses this version of Trilinos into an environment built using Spack.

**Comment by aprokop** [comment]
Interesting. So your existing software environment was able to build this version of Trilinos with OpenMP just fine? Could you please compare the cmake output for it with the one from Spack to see what the differences are?

**Comment by carsonwoods** [comment]
@aprokop I spoke with the maintainers for the software environment and they said that listing Trilinos with OpenMP support as being able to be built with gcc 9.3.0 was a mistake and that they don't actually build it for their environment, it is in fact a Trilinos issue, not a Spack issue.  Though there should probably be a `conflicts('+openmp', when='%gcc@9.3.0')` added to the Trilinos package file. I can close this issue now or make a PR to close it.

**Comment by aprokop** [comment]
> conflicts('+openmp', when='%gcc@9.3.0')

It is totally unclear at this point what versions of Trilinos are affected by which versions of gcc. Sure, you could do `conflicts('+openmp', when='@12.12.1%gcc@9.3.0')`, but I'm not sure how useful that is.

**Comment by carsonwoods** [comment]
Good point. I'll close the issue then.
