### ISSUE TITLE
Spack re-installs packages without necessity

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#1754]
While working on and trying to install `py-yt`, Spack installed `py-scipy` as dependency. When the install of `py-yt` failed, I corrected its package, and tried to install it again. Spack then began by re-installing `py-scipy`. I don't know why -- nothing in this package on its dependencies changed, and none of their variants changed either. However, the hash is different.

I still have the respective prefix directories of `py-scipy` if that helps.

I've seen this problem several times with several different packages; currently, Spack is re-installing `py-scikit`.

**Comment by davydden** [comment]
FYI, one possible reason is https://github.com/LLNL/spack/issues/1457#issuecomment-239318984

**Comment by tgamblin** [comment]
@eschnett: do you still see this and do you have a reproducer?
