### ISSUE TITLE
"spack config add" fails to validate type of fields where the default constructor value is not allowed

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#17543]
The command:
```console
$ spack config add config:build_jobs:2
==> Error: Cannot determine valid type for path 'config:build_jobs'.
```
fails while it should instead write:
```yaml
config:
  build_jobs: 2
```
in the most appropriate configuration scope.

### Steps to reproduce the issue
Just try the following command:
```console
$ spack config add config:build_jobs:2
```

### Error Message

```console
$ spack -d --stacktrace config add config:build_jobs:2
lib/spack/spack/cmd/__init__.py:122 ==> [2020-07-15-12:06:35.452404, 5188] Imported config from built-in commands
lib/spack/spack/cmd/__init__.py:122 ==> [2020-07-15-12:06:35.456601, 5188] Imported config from built-in commands
lib/spack/spack/config.py:834 ==> [2020-07-15-12:06:35.458919, 5188] Reading config file /home/culpo/.spack/config.yaml
lib/spack/spack/main.py:764 ==> [2020-07-15-12:06:35.462300, 5188] ConfigError: Cannot determine valid type for path 'config:build_jobs'.
lib/spack/spack/error.py:55 ==> [2020-07-15-12:06:35.462819, 5188] Error: Cannot determine valid type for path 'config:build_jobs'.
Traceback (most recent call last):
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 761, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 489, in _invoke_command
    return_val = command(parser, args)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/cmd/config.py", line 432, in config
    action[args.config_command](args)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/cmd/config.py", line 245, in config_add
    existing = spack.config.get_valid_type(path)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/config.py", line 913, in get_valid_type
    raise ConfigError("Cannot determine valid type for path '%s'." % path)
spack.config.ConfigError: Cannot determine valid type for path 'config:build_jobs'.
```

### Information on your system

* **Spack:** 0.15.1-127-a6abd530b
* **Python:** 3.7.4
* **Platform:** linux-ubuntu18.04-broadwell

### Additional information

The issue is due to the fact that the field in question has a minimum allowed value in the schema:

https://github.com/spack/spack/blob/d25c7ddd6f1686f115f6dc2615a3bd3b6b3d29c4/lib/spack/spack/schema/config.py#L67

This causes the validation done in:

https://github.com/spack/spack/blob/d25c7ddd6f1686f115f6dc2615a3bd3b6b3d29c4/lib/spack/spack/config.py#L870-L884

to fail since there's an attempt to validate with `{'config': {'build_jobs': 0}}`. The failure is not because of the type but because of the value.

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by ChristianTackeGSI** [comment]
This happened for `config:concretizer:clingo` for me.
My current workaround:
```
$ cat enable_clingo.yaml
config:
  concretizer: clingo
$ ./bin/spack config --scope=site add -f enable_clingo.yaml
```
