### ISSUE TITLE
Installation issue: kallisto (why mpich dependency)

### ISSUE THREAD

**Issue by payerle** [LLNL/spack#17550]
spack info kallisto 
reports that kallisto depends on mpich.

This is surprising to me because it is not optional and specific to the mpich package (and not a dependency on the virtual MPI package).  But even more surprising, is I do not see any mention of kallisto supporting MPI.  I cannot find any mention of MPI in the source code, and the only MPI dependency appears to be indirect via hdf5 built with MPI support (see e.g. 
https://github.com/pachterlab/kallisto/issues/91)

### Steps to reproduce the issue

```console
$ spack install <spec>
...
```

### Additional information

* [spack-build-out.txt]()
* [spack-build-env.txt]()

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by payerle** [comment]
spack debug report
* **Spack:** 0.14.2
* **Python:** 3.6.8
* **Platform:** linux-rhel8-x86_64

Package lallisto has no maintainers listed.
I have not included build log, etc. as problem occurs before that stage.

**Comment by adamjstewart** [comment]
It looks like this package was added by @akthoma in #5063 and updated by @odoublewen and @hartzell, maybe one of them can comment on this? It would be great to add a maintainer for this package if anyone would like to volunteer!
