### ISSUE TITLE
Installation issue: netlib-scalapack 2.1.0

### ISSUE THREAD

**Issue by cpraveen** [LLNL/spack#17579]
### Steps to reproduce the issue

```console
$ spack install -j40 --only dependencies dealii


```

### Information on your system

```console
$ spack debug report
* **Spack:** 0.15.1
* **Python:** 3.8.3
* **Platform:** linux-opensuse_tumbleweed20200715-broadwell
```

```console
$ cat ~/.spack/linux/packages.yaml 
packages:
   hdf5:
      variants: +fortran +cxx +hl
   petsc:
      variants: +mumps +suite-sparse
   cgns:
      variants: +fortran
   trilinos:
      variants: +rol
   all:
      providers:
         mpi: [mpich]
```

### Additional information

 * [spack-build-out.txt](https://github.com/spack/spack/files/4941037/spack-build-out.txt)
 * [spack-build-env.txt](https://github.com/spack/spack/files/4941038/spack-build-env.txt)

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by jlow2016** [comment]
My current workaround is to add the development branch until the GCC 10 fix/patch is available.
Use `spack edit netlib-scalapack`

```
    url = "http://www.netlib.org/scalapack/scalapack-2.0.2.tgz"
    git = "https://github.com/Reference-ScaLAPACK/scalapack.git"

    version('develop', branch='master')
    version('2.1.0', sha256='61d9216cf81d246944720cfce96255878a3f85dec13b9351f1fa0fd6768220a6')
    version('2.0.2', sha256='0c74aeae690fe5ee4db7926f49c5d0bb69ce09eea75beb915e00bba07530395c')
    version('2.0.1', sha256='a9b34278d4e10b40cbe084c6d87d09af8845e874250719bfbbc497b2a88bfde1')
    version('2.0.0', sha256='e51fbd9c3ef3a0dbd81385b868e2355900148eea689bf915c5383d72daf73114')
```

Related PR: https://github.com/spack/spack/pull/17647

**Comment by cpraveen** [comment]
Thank you, I could continue using develop branch.

But I am getting error with Mumps now.
