### ISSUE TITLE
Few questions regarding spack.

### ISSUE THREAD

**Issue by Joe23232** [LLNL/spack#17582]
I am interested in getting it but I have a few questions regarding `spack` package manager.

* Does the packages get installed into the `~` directory? Or does it get installed whereever the `spack` git package is located?
* Does it share dependencies like `pacman` does so it doesn't take extra space?
* Am I able to specify the flags (like with Gentoo's portage package manager) so I can get higher optimisations?
* How many packages are available in the repo? Is it less than the official Arch Linux repository?
* Is it in beta or stable?

**Comment by adamjstewart** [comment]
Hi @Joe23232, welcome to Spack!

1. By default, if you clone Spack to some directory `SPACK_ROOT`, your packages are installed to `$SPACK_ROOT/opt/spack/`. However, you can change this by modifying the `install_tree` setting in `config.yaml` so that packages can be installed anywhere on the filesystem: https://spack.readthedocs.io/en/latest/config_yaml.html#install-tree
2. Yes, Spack shares all dependencies across installations. Note that Spack is currently very picky about installing the latest and greatest, so for example, if a new version of package A comes out, and you already have an older version installed, Spack will reinstall package A. This behavior will change once the new concretizer comes out (Spack v0.16.0) and Spack will be more aggressive about reusing already-installed packages.
3. Yes, the syntax looks like: `spack install foo cflags="-O2"`
4. There are 4,371 packages in the repo, and more being added every day! https://spack.readthedocs.io/en/latest/package_list.html
5. Spack is currently in beta release. We won't officially be stable until you see a 1.0 release. However, many sites like ANL and LLNL have been using Spack in production for the last 5 years, so I wouldn't worry too much about stability. While some current features may be removed, old installations will still be valid for newer Spack releases.

Hope this answers your questions! I'm happy to answer any other questions you might have.

**Comment by Joe23232** [comment]
> Hi @Joe23232, welcome to Spack!

Thanks mate :)

> By default, if you clone Spack to some directory SPACK_ROOT, your packages are installed to $SPACK_ROOT/opt/spack/. However, you can change this by modifying the install_tree setting in config.yaml so that packages can be installed anywhere on the filesystem: https://spack.readthedocs.io/en/latest/config_yaml.html#install-tree

Ah I see.

> Yes, Spack shares all dependencies across installations. Note that Spack is currently very picky about installing the latest and greatest, so for example, if a new version of package A comes out, and you already have an older version installed, Spack will reinstall package A. This behavior will change once the new concretizer comes out (Spack v0.16.0) and Spack will be more aggressive about reusing already-installed packages.

Sounds like `pacman` to me

> Yes, the syntax looks like: spack install foo cflags="-O2"

Oh that is good, is it possible if I modify some config files so by default it can then use the `cflags` that I assign it to?

> There are 4,371 packages in the repo, and more being added every day! https://spack.readthedocs.io/en/latest/package_list.html

Ah I see that is great, hope to see it grow :) One question though, am I able to add a github/gitlab repository if a package is not available in the main repository?

> Spack is currently in beta release. We won't officially be stable until you see a 1.0 release. However, many sites like ANL and LLNL have been using Spack in production for the last 5 years, so I wouldn't worry too much about stability. While some current features may be removed, old installations will still be valid for newer Spack releases.

That is pretty good :)

**Comment by adamjstewart** [comment]
> Oh that is good, is it possible if I modify some config files so by default it can then use the `cflags` that I assign it to?

Yes, you can add any flag you want permanently to your `compilers.yaml`, see https://spack.readthedocs.io/en/latest/getting_started.html#manual-compiler-configuration

I used to do this pretty heavily when I worked at ANL: https://github.com/spack/spack-configs/blob/master/ANL/LCRC/linux/compilers.yaml

> One question though, am I able to add a github/gitlab repository if a package is not available in the main repository?

Yes, Spack is completely open source, we accept pull requests for any package you want to add. See the [Packaging Guide](https://spack.readthedocs.io/en/latest/packaging_guide.html) for instructions on how to write new packages. You can also modify existing packages to add new versions/variants/etc. Spack already has over 500 contributors, mostly contributing new packages.

**Comment by Joe23232** [comment]
> Yes, you can add any flag you want permanently to your compilers.yaml, see https://spack.readthedocs.io/en/latest/getting_started.html#manual-compiler-configuration

Ah I see.

> I used to do this pretty heavily when I worked at ANL: https://github.com/spack/spack-configs/blob/master/ANL/LCRC/linux/compilers.yaml

Looks very complicated, I wouldn't really understand what the code does in the file.

> Yes, Spack is completely open source, we accept pull requests for any package you want to add. See the Packaging Guide for instructions on how to write new packages. You can also modify existing packages to add new versions/variants/etc. Spack already has over 500 contributors, mostly contributing new packages.

Am I able to just add it to the program though on my local machine?

---

One other question, say if I compiled some Linux applications using `spack`, if I copied the executable over to Mac OS, would it still run the executable or do I need to recompile the application from the source code?

**Comment by adamjstewart** [comment]
> Am I able to just add it to the program though on my local machine?

Yes, you can write a recipe without contributing it upstream. But then no other users would be able to use your recipe. 

> say if I compiled some Linux applications using spack, if I copied the executable over to Mac OS, would it still run the executable or do I need to recompile the application from the source code?

You would need to recompile from source code. The system headers and libraries on macOS and Linux are drastically different. Even if you built on Ubuntu 18.04 you would have to recompile on Ubuntu 20.04.

**Comment by Joe23232** [comment]
> Yes, you can write a recipe without contributing it upstream. But then no other users would be able to use your recipe.

Ah I see. Of course I would contribute but just curious to know.

> You would need to recompile from source code. The system headers and libraries on macOS and Linux are drastically different. Even if you built on Ubuntu 18.04 you would have to recompile on Ubuntu 20.04.

What about on BSD, if I used OpenBSD, would it also be drastically different as well compared to Linux?

**Comment by adamjstewart** [comment]
> What about on BSD, if I used OpenBSD, would it also be drastically different as well compared to Linux?

Yes, you should assume every OS and OS version will require a different compilation. Depending on the package (and which headers/libraries it links to) it might work, but Spack will rebuild it anyway just in case. Spack's compiler wrappers inject microarchitecture-specific flags to build the most optimized binaries for your hardware, so executables aren't general purpose like they are with other package managers. For example:
```
$ spack arch
linux-ubuntu20.04-skylake
```
If I switched to a new computer with CentOS, or with Ubuntu 18.04, or with a haswell CPU, Spack would rebuild my packages.

**Comment by adamjstewart** [comment]
It sounds like all of your questions have been answered? Is it safe to close this issue?

**Comment by Joe23232** [comment]
Yeah of course, thanks for your help mate :)
