### ISSUE TITLE
CUDA stubs directory ends up in rpath, making NVIDIA profiling tools segfault

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#17607]
### Steps to reproduce the issue

The following segfaults when `config:shared_linking == rpath` (default value):

```
$ spack install sirius+cuda
$ spack load sirius
$ nvprof sirius.scf
```
but it works fine with `config:shared_linking == runpath`. Also other profilers segfault: `ncu sirius.scf` and `nsys sirius.scf`. Just running `sirius.scf` works fine.

This is because spack seems to misconfigure a path that most likely propagates to the nvidia profiler tools, whereas it does not affect runpath because that is limited to direct dependencies. When building a package that depends on cuda, spack generates the `SPACK_RPATH_DIRS` variable that contains a path to the CUDA stubs folder:

```
SPACK_RPATH_DIRS=.....:/spack/opt/spack/linux-ubuntu20.04-zen/gcc-8.4.0/cuda-10.2.89-5sqjnk2pe3bwluyrcw3afah4ohgbxsqn/targets/x86_64-linux/lib/stubs:....
```

This ends up in the rpath, which is incorrect:

```
$ readelf -d `which sirius.scf` | grep stubs
 0x000000000000000f (RPATH)              Library rpath: [......:/spack/opt/spack/linux-ubuntu20.04-zen/gcc-8.4.0/cuda-10.2.89-5sqjnk2pe3bwluyrcw3afah4ohgbxsqn/targets/x86_64-linux/lib/stubs:......]
```

(On a related note, the documentation is also [giving the advice to add directories of linked libraries to the RPATH](https://spack.readthedocs.io/en/latest/workflows.html#write-the-cmake-build) using `CMAKE_INSTALL_RPATH_USE_LINK_PATH`, which has the same problem of inadvertently adding stub libraries to the RPATH. It seems the pytorch people have been running into this problem as well: https://github.com/pytorch/pytorch/pull/37737. Maybe we should rewrite that section to avoid having these issues.)

### Additional information

- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
@ax3l @svenevs

**Comment by svenevs** [comment]
I cannot look into this at this time but I can confirm that we definitely don't want stubs dir in rpath. That's not for public consumption.
