### ISSUE TITLE
LLVM subprojects are always checked out

### ISSUE THREAD

**Issue by 0ax1** [LLNL/spack#1764]
When installing LLVM, subprojects are checked out with svn even if they are explicitly deactivated. (`spack install -lldb llvm@trunk  %gcc@4.8`) I have been trying to install LLVM trunk with spack on Ubuntu 14.04.5 LTS. This failed, as CMake emitted an error that lldb cannot be built with the current c++ std lib version. Removing the lldb  checkout in the llvm `package.py` fixed the problem for me.
https://github.com/LLNL/spack/blob/master/var/spack/repos/builtin/packages/llvm/package.py#L131 Wouldn't it be better to just check out the needed ones?

**Comment by adamjstewart** [comment]
@0ax1 Is this fixed by #3015? Or are subprojects and resources different things?

**Comment by adr-ableton** [comment]
@adamjstewart  #3015 addresses exactly what I meant. Thanks for referencing the fix and having a look at this issue!
