### ISSUE TITLE
Installation issue: py-pymol cannot link against libGLEW.so

### ISSUE THREAD

**Issue by g-mathias** [LLNL/spack#17691]
With the latest versions of spack I run into a link error when running
```
spack install py-pymol
```
The error message is
```
            /temp.linux-x86_64-3.7/ov/src/OVLexicon.o build/temp.linux-x86_64-3.7/ov/src/OVOneToAny.o build/temp.linux-x86_64-3.7/o
            v/src/OVOneToOne.o build/temp.linux-x86_64-3.7/ov/src/OVRandom.o build/temp.linux-x86_64-3.7/ov/src/ov_utility.o -L/usr
            /lib64 -L/usr/lib -L/dss/dsshome1/07/lu64bag3/src/spack_fork/opt/spack/linux-sles15-haswell/gcc-8.4.0/python-3.7.7-pehn
            4dcqx6q73aytm4jsddc5dse4dxcl/lib -lpng -lfreetype -lxml2 -lGL -lGLEW -lpython3.7m -o build/lib.linux-x86_64-3.7/pymol/_
            cmd.cpython-37m-x86_64-linux-gnu.so
  >> 986    /dss/dsshome1/lrz/sys/spack/release/20.1/opt/x86_64/binutils/2.32-gcc-luqbviq/bin/ld: cannot find -lGLEW
  >> 987    collect2: error: ld returned 1 exit status
  >> 988    error: command '/lrz/sys/spack/release/20.1/opt/x86_64/gcc/8.4.0-gcc-cozjb4b/bin/g++' failed with exit status 1

> spack debug report
* **Spack:** 0.15.1
* **Python:** 3.6.10
* **Platform:** linux-sles15-haswell
```
The build node runs on SLES15 (target=x86_64); the glew package is **not** installed on the host system.

There is no maintainer for py-pymol but @hseara has worked on the package lately.

[spack-build-out.txt](https://github.com/spack/spack/files/4970852/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/4970853/spack-build-env.txt)

A striped down version of the package builds on spack@0.13.4. On spack@0.15.1 it yields the same error.
I checked:
- compilers:
    - gcc@7.5.0 (system)
    - gcc@8.4.0 (spack-installed)
- python:
    - python@3.7.8
    - python@3.7.4 (same as in spack 0.13.4)
    - python@3.8.3
- spack
    - development ( on 2020-07-22)

all yielding the same error. 

I don't see how the libdirs are passed to the linker. There are no corresponding -L statements, but that has not changed from spack@0.13.4. However, glew is provided in the SPACK_LINK_DIRS and SPACK_RPATH_DIRS (see spack-build-env.txt). The glew package has not changed since spack@0.13.4.

Any help is appreciated.
Gerald

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
> I don't see how the libdirs are passed to the linker. There are no corresponding -L statements, but that has not changed from spack@0.13.4. However, glew is provided in the SPACK_LINK_DIRS and SPACK_RPATH_DIRS (see spack-build-env.txt). The glew package has not changed since spack@0.13.4.

For most packages, Spack's compiler wrappers take care of this automatically. Python packages are a bit of an exception, as they usually use the compilers directly, making it challenging. The first thing I would try is using `LIBRARY_PATH` and `CPATH` to allow the compiler to locate extensions. See `py-torchvision` for an example of this, basically add:
```python
   def setup_build_environment(self, env):                                     
        include = []                                                            
        library = []                                                            
        for dep in self.spec.dependencies(deptype='link'):                      
            query = self.spec[dep.name]                                         
            include.extend(query.headers.directories)                           
            library.extend(query.libs.directories)                              
                                                                                   
        env.set('CPATH', ':'.join(include))                                     
        env.set('LIBRARY_PATH', ':'.join(library))
```
If that doesn't work, we can probably use `filter_file` to add these to the `setup.py` under `lib_dirs = []`. It looks like there is also a newer release of pymol if you want to try adding that. Let me know if you need help!

**Comment by adamjstewart** [comment]
@g-mathias did you ever get a chance to try any of these suggestions? Is this issue still present on develop?

**Comment by g-mathias** [comment]
We fixed all linking problems. The remaining bug is the path injection discussed in #27455 .
I'll close this issue.
