### ISSUE TITLE
GitHub Labels

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#1772]
@tgamblin @alalazo @adamjstewart @davydden 

With the "new improved" permissions, we are now able to add labels to Issues and PR's.  GitHub provides the following labels:

> bug
> duplicate
> enhancement
> invalid
> needs-review
> needs-work
> question
> spec-change
> will-merge
> wontfix

They all seem reasonable; but maybe we can get rid of spec-change.  I propose we add some new labels as well:

**package**: This PR modifies only one or more `package.py` files, not core Spack
**new**: Add to **package**-labelled PR's to indicate it's a new package no previously in Spack.  (Do we need this?  Not sure)
**bugfix**: This PR aims to fix a known bug (bug Issue should be referenced in the PR)

Thoughts, anyone?  Apparently I can't add new labels, someone at LLNL would need to do that.

**Comment by citibeth** [comment]
We also need:

**docs**: This PR is documentation-related, no code.  (Docs are also welcome in code-containing PRs, documenting the code they contain).

**Comment by davydden** [comment]
I was thinking about something similar:

package
bugfix     // i.e. package + bugfix; feature + bugfix
feature
new         // i.e. new + package; new+ feature
wip
ready to merge
build error
user configuration
help wanted
discussion
documentation
enhancement
question

**Comment by davydden** [comment]
if I am not mistaken, same list of label is used for both issues and PRs.

**Comment by adamjstewart** [comment]
Those all look good to me. We should keep `spec-change` though. It is used to mark a PR that will cause all of your hashes to change. This causes everyone to have to either rebuild their packages or reinstall Spack. The purpose of the label was so that spec-changing PRs could be gathered together and merged all at the same time. Spack's internal version could then be changed and an email could be sent out to tell people to reinstall Spack. We haven't been very careful about this in the past.

**Comment by citibeth** [comment]
OK, how about the following tags; in `.rst` format, which will make it easy
for Adam to cut-n-paste into the contributor's guide:

```
Issue Tags
==========

* **issue/build-error**: Problem with a package building.  (Should
  also have **issue/bug** set).

* **issue/bug**: Reports a bug, other than a build error.

* **issue/enhancement**: Request for a new feature or enhancement.

* **issue/documentation**: Request for documentation

* **issue/package**: Issue with a single (or small number of) packages.

* **issue/discussion**: Issue is a general discussion, not linked to
  an existing feature or problem.

* **issue/help**: User wants help.


PR Tags
=======


Properties
----------

* **pr/enhancement**: This PR adds a feature or other functionality to
  Spack.

* **pr/bugfix**: This PR addresses a bug (and links to that bug, if it
  appears in an Issue).

* **pr/docs**: This PR contains ONLY documentation.

* **pr/package**: This PR contains ONLY changes to packages, or new
  packages.  (If it contains new packages, **enhancement** should also
  be set).

* **pr/hash-changes**: This PR results in Spack hashes changing
  globally.


Status Set by Author
--------------------

* **status/author/in-progress**: Indicates the author is showing work in
progress

* **status/author/needs-review**: Indicates the author is seeking review of
    the PR (beyond the normal review procedures); but it might not be
    ready to merge.

* **status/author/needs-merge**: Indicates the author believes it is ready
to
    merge.

Status Set by Reviewer(s)
-------------------------

* **status/reviewer/needs-work**: Indicates the reviewer has determined this
  PR needs more work before merging.  When setting this tag, the
  reviewer should remove **author-needs-merge** tag, if set.  The
  author can remove this tag after the work is completed.

* **status/reviewer/needs-docs**: Indicates the PR is an **enhancement** and
  needs documentation --- but does not have any.
```

**Comment by citibeth** [comment]
Also, I see that tags are color coded.  I might suggest the following colors:

Issue Tags
========

issue/bug, issue/build-error: red
issue/enhancement: blue
issue/documentation: orange
issue/package: pink
issue/help: yellow
issue/discussion: green

PR Tags
=======

pr/enhancement: blue
pr/bugfix: brown
pr/docs: orange
pr/package: pink
pr/hash-changes: ???

status/author/in-progress, status/reviewer/needs-work, status/reviewer/needs-docs: read
status/author/needs-review: yellow
status/author-needs-merge, status/reviewer/ready-to-merge: green




Color A: issue/*

**Comment by adamjstewart** [comment]
I don't think we need to include slashes in the tags, if that's what you're suggesting. issue/package and pr/package can just be a single package label. But it would definitely be nice to include these in the Contribution Guide.

hash-changes/spec-changes were previously red, kind of like a "danger" warning so that they didn't get accidentally merged.

It would definitely be nice to replace thinks like [WIP] and [RtM] in the title of a PR with actual labels.

**Comment by citibeth** [comment]
On Wed, Sep 14, 2016 at 5:14 PM, Adam J. Stewart <notifications@github.com>
wrote:

> I don't think we need to include slashes in the tags, if that's what
> you're suggesting. issue/package and pr/package can just be a single
> package label.
>
Users usually select labels from a drop-down list.  The hierarchical label
naming ensures that labels of similar function appear together in that
list.  This is a real usability issue with more than about 5 labeles.

But I agree also... if users were typing these labels instead of selecting
them from a list, I'd suggest we do without the stuff before the slashes.


> But it would definitely be nice to include these in the Contribution Guide.
>
The idea is so we're all on the same page about what each label means.

> hash-changes/spec-changes were previously red, kind of like a "danger"
> warning so that they didn't get accidentally merged.
>

Can you suggest modifications to the color scheme?  (Or modify my post
above to reflect the changes you think best)?

**Comment by davydden** [comment]
> Users usually select labels from a drop-down list.

IIRC an average user is not allowed to set labels. It's a privilege of maintainers or those with extra rights. At least this is the default.

But it's good to spell out the meaning of labels in Contribution Guide so that contributors know what means what in Spack.

**Comment by citibeth** [comment]
On Wed, Sep 14, 2016 at 5:58 PM, Denis Davydov <notifications@github.com>
wrote:

> Users usually select labels from a drop-down list.
>
> IIRC an average user is not allowed to set labels. It's a privilege of
> maintainers or those with extra rights. At least this is the default.
>

And the maintainers select the labels from a drop-down list.

**Comment by alalazo** [comment]
I just had time to read this thread. I am not against labels, but what we have here are really A LOT of them...

Regarding the proposed tags I would make the following changes : 
```
spec-change -> hash-change # (on this I agree with @citibeth above)
docs -> docs-only
```

**Comment by davydden** [comment]
i guess this can be closed, see https://github.com/LLNL/spack/labels

**Comment by citibeth** [comment]
That's good to know.  Now we need a bit of documentation and organization on the labels, and then this can be closed IMHO.

**Comment by tgamblin** [comment]
I think probably only a few of them (WIP, ready, etc.) really need prescriptive docs... it would be nice to allow the labels to grow organically.

**Comment by alalazo** [comment]
Can we close this or is there something that hasn't been done yet ?

**Comment by adamjstewart** [comment]
The only thing that wasn't added was documentation, but idk if it really needs to be documented...

**Comment by citibeth** [comment]
close.
