### ISSUE TITLE
llvm package includes conflict directive with nonexistent flag

### ISSUE THREAD

**Issue by goxberry** [LLNL/spack#17796]
This issue isn't strictly a bug, so it didn't seem to make sense to use one of the existing templates.

[Line 162 of the `llvm` package in commit 75042c381c9fd1412f0fce99aab9ebd43fd528c8 (current `HEAD` of `develop` as of this writing)](https://github.com/spack/spack/blob/8b515f3ba07d6a67e8a75c506a2d5d4816a73fa6/var/spack/repos/builtin/packages/llvm/package.py#L162) mentions a nonexistent `+clang_extra` flag in a `conflicts` directive, i.e.:

```python
conflicts("+clang_extra", when="~clang")
```

**Comment by adamjstewart** [comment]
Want to submit a PR to remove that line? @trws @naromero77 are the maintainers.

**Comment by naromero77** [comment]
Just got back from "vacation" and catching up on many things. Give me a day or two to take a look -- want to make sure nothing accidentally disappeared.

**Comment by naromero77** [comment]
I went back over a year in the git history. That conflict has been there for a while, but I don't think it has ever done anything.

Maybe @homerdin might know.

I will just plan on deleting that tomorrow if I don't hear back from anyone.
