### ISSUE TITLE
libxc: Conflicting optimization options break build with Intel 19.1.x

### ISSUE THREAD

**Issue by RemiLacroix-IDRIS** [LLNL/spack#17794]
The libxc package configures some optimization options for the build through setting `CFLAGS` and `FCFLAGS`:
https://github.com/spack/spack/blob/ab7b07553beecd54475e90127e2e02ba269ec99e/var/spack/repos/builtin/packages/libxc/package.py#L55-L78

This predates the whole architecture detection added in v0.13.0 but now it can somehow conflict.

In our case, Spack detects that we have `skylake_avx512` so it injects `-march` and `-mtune` accordingly which "conflicts" with `-xSSE4.2 -axAVX,CORE-AVX2`.

Supposedly the compilers are supposed to handle this but currently it breaks with Intel 19.1.X, or at least for libxc it causes an internal compiler error at link time. Of course I will make sure to report this to Intel because it is a compiler bug.

However I am wondering if the "libxc" specific optimizations still make sense now that Spack tries to optimize the builds in general.

Depending on your opinion, I could provide a PR which:
1. adds a `conflicts` with Intel 19.1.x
2. disable the "libxc" optimizations for Intel 19.1.x to workaround the issue
3. remove the "libxc" optimizations.

**Comment by RemiLacroix-IDRIS** [comment]
> Of course I will make sure to report this to Intel because it is a compiler bug.

I have opened an Intel support case for this issue.

**Comment by RemiLacroix-IDRIS** [comment]
@alalazo or @adamjstewart: Any thoughts about this?

**Comment by adamjstewart** [comment]
I would remove the optimizations from the package and let Spack automatically handle those with its compiler wrappers.
