### ISSUE TITLE
`spack view symlink/hardlink dir py-something` should create/update `easy-install.pth`

### ISSUE THREAD

**Issue by muffgaga** [LLNL/spack#1789]
If one calls `spack activate py-somepackage` to extend a python package `Python.activate()` creates an updated `site-packages/easy-install.pth` in the `python` package installation.

A similar mechanism for the filesystem view feature would allow for multiple package distributions (containing different versions/collections of python packages but the same python package);
currently, `easy-install.pth` is symlinked to some python package which was symlinked first and has to be fixed manually (using the list of symlinked python packages and merging all `easy-install.pth`s, which is what `activate()` does.

**Comment by citibeth** [comment]
So... this is a suggestion that the `python` stuff in `spack activate` be extended to filesystem views?

An alternative to `spack activate` and filesystem views is to create and use a script that loads all the required modules via `spack module load --dependencies` commands.

**Comment by muffgaga** [comment]
Yes, it's a suggestion (sorry for not making this clearer) :).

In the past, we used to provide "tested" lists of modules for our users/developers. However, the filesystem view mechanism seems much nicer. There you can have one module which we could manage using some VCS (and the view itself, at least in the symlink case).

**Comment by muffgaga** [comment]
@obreitwi provided a pull request (#3227) implementing this feature (i.e. `spack view` uses the existing activation/deactivation functionality to enable extensions (for us it's about the python packages → merging of all `easy-install.pth` into a single one)).

**Comment by alalazo** [comment]
This should be resolved by #5415, right?

**Comment by obreitwi** [comment]
Right, it is!
