### ISSUE TITLE
Installation issue: parse extension error of cray-libsci

### ISSUE THREAD

**Issue by t-karatsu** [LLNL/spack#17891]
When I tried to install the cray-libsci package, the following error occurred.
```
$ spack install cray-libsci
==> Warning: Missing a source id for cray-libsci@18.11.1.2
==> Error: Unable to parse extension from http://www.nersc.gov/users/software/programming-libraries/math-libraries/libsci/.

If this URL is for a tarball but does not include the file extension
in the name, you can explicitly declare it with the following syntax:

    version('1.2.3', 'hash', extension='tar.gz')

If this URL is for a download like a .jar or .whl that does not need
to be expanded, or an uncompressed installation script, you can tell
Spack not to expand it with the following syntax:

    version('1.2.3', 'hash', expand=False)
```
Is this package supposed to include external libraries?
In that case, it seems unnecessary to define `url` and `version`.

We also think that it is necessary to define a `conflict` if the available environment(ex. architecture) is limited.

### Steps to reproduce the issue

```console
$ spack install cray-libsci
```
### Information on your system

* **Spack:** 0.11.2-8091-944ea18b9
* **Python:** 3.7.7
* **Platform:** linux-rhel8-a64fx

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
This package cannot be downloaded, it comes vendored with Cray hardware. You're supposed to add it as an external package in `packages.yaml` to use it.

@tldahlgren is there any way we could make this more clear for packages like this? `spack external find` support would also help.

**Comment by tldahlgren** [comment]
Note:
1) `spack maintainers cray-libsci` doesn't return anything because there are no maintainers listed in the package
2) Only two individuals have worked on this package: @junghans and @becker33 
3) The package's `homepage` and `url` are outdated

**Comment by tldahlgren** [comment]
> This package cannot be downloaded, it comes vendored with Cray hardware. You're supposed to add it as an external package in `packages.yaml` to use it.
> 
> @tldahlgren is there any way we could make this more clear for packages like this?

Certainly, given the right information.

The warning and error each come from one place each in the code.  The first from `package.py` and the second from `mirror.py`.   So the issue would be how to determine that the package is external.  

> `spack external find` support would also help.

I am not familiar with this command so would have to dig into it to address the issue.

**Comment by adamjstewart** [comment]
@tldahlgren I'm just wondering if we could do something similar to what you did for packages that must be manually downloaded and print a warning message saying that this package must be vendored.

`spack external find` searches for specific executables in your `PATH`, queries the version, and adds them to the `packages.yaml`. I'm not sure if `cray-libsci` has any corresponding executable though.

**Comment by tldahlgren** [comment]
Right now the only thing I see in its package that even *hints* that it is external is the `external_prefix` property.  And it appears to be the only built-in package that has such a property.

Based on the `lustre` package's solution, it looks like this package should be raising an `InstallError`.

**Comment by tldahlgren** [comment]
> `spack external find` searches for specific executables in your `PATH`, queries the version, and adds them to the `packages.yaml`. I'm not sure if `cray-libsci` has any corresponding executable though.

According to Greg B. it does not.  But options are being discussed that could help with this eventually.

**Comment by adamjstewart** [comment]
> Right now the only thing I see in its package that even hints that it is external is the external_prefix property. And it appears to be the only built-in package that has such a property.

We can always add some equivalent to what we had for manually downloaded packages.

**Comment by tldahlgren** [comment]
> > Right now the only thing I see in its package that even hints that it is external is the external_prefix property. And it appears to be the only built-in package that has such a property.
> 
> We can always add some equivalent to what we had for manually downloaded packages.

Very true.  And that would allow us to provide a more meaningful error earlier on in the processing.  It looks like `cray-libsci` would not be the only package to benefit from this capability either.

Perhaps something to discuss with Todd so we can raise the priority?

**Comment by becker33** [comment]
The `external_prefix` method is because the prefix to the cray-libsci package cannot be determined from the module by the normal methods, Cray has all sorts of internal structure in that directory. Other packages can implement that method if they need fancy ways to determine the prefix from the module contents.
