### ISSUE TITLE
Creating packages in external repos seems not to work

### ISSUE THREAD

**Issue by robertdfrench** [LLNL/spack#1791]
Hello!

I am hoping to be able to do something like this:
```bash
./bin/spack repo add /path/to/site-repo
./bin/spack create -r site-repo https://internal.gitlab/coolpackage-1.2.3tgz
```
But the create command fails with this message:

```
==> Error: No repo.yaml found in 'site-repo'
```

However, I would argue that I do in fact have a repo.yaml file in the `/path/to/site-repo` folder with these contents:

```yaml
repo:
  namespace: 'site-repo'
```

However, if I manually copy a created package into the 'site-repo' folder, I am able to install it just fine.

**Comment by citibeth** [comment]
So the problem is... `spack create` doesn't work, but you can create packages by writing your own `package.py`?

**Comment by robertdfrench** [comment]
Yes. Or I can use create without the "-r" flag and it will make one in the
builtin repo just fine, which i can then copy to the external repo.

**Comment by citibeth** [comment]
Hmm... I don't think that external repos are used much, so I'm not
surprised that there's an issue here.  I've also never used `spack create`
much, found it easier to just build my own packages.

**Comment by JavierCVilla** [comment]
I find an interesting feature what @robertdfrench say. Given that spack provide you an automatic way to create your own packages, why not to specify the proper repo to install this package? If there is the option to have different repos there should be also the option to create packages directly on them with `spack create`.

**Comment by citibeth** [comment]
So the suggestion is to add a `--repo` flag to `spack create`?  Sounds to
me like a good approach.

**Comment by JavierCVilla** [comment]
Yes, exactly that.

**Comment by tgamblin** [comment]
You can already specify `--repo` or `--namespace`:

```text
$ spack create --help
usage: spack create [-h] [--keep-stage] [-n NAME] [-r REPO] [-N NAMESPACE]
                    [-f]
                    [url]

positional arguments:
  url                   url of package archive

optional arguments:
  -h, --help            show this help message and exit
  --keep-stage          Don't clean up staging area when command completes.
  -n NAME, --name NAME  Override the autodetected name for the created
                        package.
  -r REPO, --repo REPO  Path to a repository where the package should be
                        created.
  -N NAMESPACE, --namespace NAMESPACE
                        Specify a namespace for the package. Must be the
                        namespace of a repository registered with Spack.
  -f, --force           Overwrite any existing package file with the same
                        name.
```



`-n` is the namespace of a repo (e.g. `builtin` or maybe `gov.llnl` -- it's set in `repo.yaml` at the top level of any repo).  With `-r` you supply a path.  You can actually create packages in unregistered repos with `-r`.  But if you want to see possible namespaces and  paths for *registered* repos, `spack repo list` will tell you:

```console
 spack repo list
==> 1 package repository.
builtin    /Users/gamblin2/src/spack/var/spack/repos/builtin
```

Namespace is on the left, path is on the right.

**Comment by tgamblin** [comment]
@robertdfrench: you want `spack create -n site-repo ...` -- see above for how it works.

Perhaps `-r` should be happy if it one supplies a namespace _or_ a path?  I think many people are going to do the same thing you did, so it might be useful.  Thoughts?

**Comment by tgamblin** [comment]
If someone wants `spack repo create --repo` to take either a repo or a namespace (b/c they find the current state of things confusing) they should open another issue specifically for that.

**Comment by JavierCVilla** [comment]
Thank you very much @tgamblin for the explanation. I was confused about that because didn't find anything about how to do it in the documentation and I didn't check the `help` command. Thanks again. 

> Perhaps -r should be happy if it one supplies a namespace or a path?

Regarding to that, IMHO yes. I find more intuitive to use -r or --repo flags with the name of the repo than the namespace flag.

**Comment by JavierCVilla** [comment]
> @robertdfrench: you want spack create -n site-repo ... -- see above for how it works.

By the way, shouldn't be: `spack create -N site-repo` with uppercase N?

**Comment by willelm** [comment]
The issue can be fixed by having -r accept a repo "name" instead of a repo location. I got the same error as the original commenter when trying to use the name assigned to my repo and not where the repo was on the filesystem.
