### ISSUE TITLE
spack arch doesnt work on amazon linux

### ISSUE THREAD

**Issue by robertdfrench** [LLNL/spack#1792]
Tried to fire up spack on an ec2 box because I am an travel and away from my beloved/wretched Cray systems. Spack detected arch as "linux--x86_64". I ran `uname -a` and noticed it does not specify the os the same way rhel and sles do.

**Comment by adamjstewart** [comment]
Duplicate of #1560

**Comment by robertdfrench** [comment]
agreed. thanks @adamjstewart
