### ISSUE TITLE
PGI compilers integration in NVIDIA HPC SDK

### ISSUE THREAD

**Issue by RemiLacroix-IDRIS** [LLNL/spack#17930]
NVIDIA released its HPC SDK today. It includes the ex-PGI compilers which have been rebranded `nvc`, `nvc++` and `nvfortran`.

How do you plan to accommodate this rebranding? Should we keep using the NVIDIA compilers as PGI compilers or should it be new compilers (which might break existing packages since "%pgi" wouldn't catch those although it will probably be needed in most cases)?

**Comment by RemiLacroix-IDRIS** [comment]
Any thoughts about this? @adamjstewart or @alalazo maybe?

We could just start using NVIDIA HPC compilers 20.7 as PGI compilers 20.7 but we would rather do something consistent with what Spack will choose in the future.

**Comment by adamjstewart** [comment]
I'll be honest, I'm not up-to-date on the latest news from NVIDIA/PGI. Are these new compilers going to completely replace the old compilers? Or is this a fork or a new compiler using PGI as the backend? If it's just a rebrand, I think we should modify our existing `pgi` support and maybe rename the compiler.

**Comment by RemiLacroix-IDRIS** [comment]
Yes, the new NVIDIA compilers are replacing the PGI ones. The [PGI website](https://www.pgroup.com) is now basically empty with just a link to the new compilers.

As far as I know it is mostly a rebrand to unify the NVIDIA software ecosystem.

**Comment by adamjstewart** [comment]
Wow, they even continued the same versioning scheme. In that case, I'm in favor of renaming `%pgi` to `%nvidia` or something like that. I'll give @alalazo a chance to chime in first.

**Comment by alalazo** [comment]
I'll try to have a look at this and discuss it with other core developers asap. I need to check better what are the implications of renaming `pgi` vs. maintaining it and having also `nvidia` alongside for newer versions.

**Comment by RemiLacroix-IDRIS** [comment]
I would say both solutions are not completely straightforward:
- renaming `pgi` would require a mechanism not to break existing Spack installs
- adding `nvidia` would probably break existing packages as special handlings for `%pgi` would not apply.

**Comment by alalazo** [comment]
@RemiLacroix-IDRIS Adding `nvidia` doesn't prevent us from pushing common code in a base class to be inherithed by both `pgi` and `nvidia`. This would solve your second point I guess.

**Comment by RemiLacroix-IDRIS** [comment]
@alalazo Sorry I wasn't clear, I meant that some packages handle the PGI compilers specifically with code like `if '%pgi' in spec ...` and those special handlings would not be used by a new `nvidia` compiler although it is likely that they would still be needed.

Of course it would be easy to fix (`if '%pgi' in spec or '%nvidia' in spec ...`) but it would require to modify multiple packages.

**Comment by adamjstewart** [comment]
Just realized that to add to the confusion, `nvc`, `nvc++`, and `nvfortran` will be the new PGI compilers, while `nvcc` will be the CUDA compiler. And I'm sure the NVIDIA HPC stack will contain both. They might even change the output messages during the unification.

**Comment by RemiLacroix-IDRIS** [comment]
> They might even change the output messages during the unification.

I am not sure to understand why it matters but I would guess that they changed the branding everywhere, including in the output messages from the ex-PGI compilers.

I haven't been able to test the NVIDIA HPC Compilers 20.7 yet but as soon as our sysadmin team can perform the install, I will have a closer look.

**Comment by adamjstewart** [comment]
> I am not sure to understand why it matters

It matters for compiler detection/external package detection. If someone runs `spack compiler find` or `spack external find pgi` (which will at some point be unified) we run `pgcc -V` and search for something like `pgcc 1.2.3`. See `lib/spack/spack/compilers/pgi.py` or #18148 for details.

**Comment by RemiLacroix-IDRIS** [comment]
Ok, that was my guest. I indeed think this will require some changes in Spack and somehow could justify that a new `nvidia` compiler is introduced.

**Comment by adamjstewart** [comment]
It wouldn't be hard to support both as a single compiler, the executable names and regexes are both lists, so we can add more entries. I'll let @alalazo decide, but I'm still leaning towards a single unified `%nvidia` compiler. It isn't hard to replace all `%pgi` with `%nvidia` in `package.py` files.

**Comment by alalazo** [comment]
@adamjstewart I think the issue would be people still stuck with old PGI compilers. Should we erroneously recognize them as `nvidia`?

**Comment by adamjstewart** [comment]
> Should we erroneously recognize them as nvidia?

Yes, and I wouldn't even consider that "erroneous". The PGI compilers have essentially been renamed as far as I can tell.

**Comment by RemiLacroix-IDRIS** [comment]
What about existing Spack installs? Wouldn't that cause some inconsistencies in the DB?

**Comment by adamjstewart** [comment]
Related to #18261

**Comment by RemiLacroix-IDRIS** [comment]
Any news regarding this? We would like to start using the new NVIDIA compilers.

**Comment by adamjstewart** [comment]
@alalazo any more thoughts on this? Would renaming the compiler break anything? Does it make more sense to simply add a new compiler anyway?

**Comment by alalazo** [comment]
@fspiga might have an opinion on this issue
