### ISSUE TITLE
Installation issue: charliecloud 0.16 & 0.17

### ISSUE THREAD

**Issue by g-mathias** [LLNL/spack#17968]
I find two minor issues installing the latest charliecloud versions

1. Encoding problem

```console
$ spack install charliecloud
==> charliecloud: Executing phase: 'configure'
==> Error: Exception occurred in writer daemon!
Traceback (most recent call last):
  File "/dss/dsshome1/07/lu64bag3/src/spack_fork/lib/spack/llnl/util/tty/log.py", line 644, in _writer_daemon
    line = _retry(in_pipe.readline)()
  File "/dss/dsshome1/07/lu64bag3/src/spack_fork/lib/spack/llnl/util/tty/log.py", line 703, in wrapped
    return function(*args, **kwargs)
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 721: ordinal not in range(128)
==> Error: BrokenPipeError: [Errno 32] Broken pipe

/dss/dsshome1/07/lu64bag3/src/spack_fork/lib/spack/spack/build_environment.py:862, in child_process:
        859            tb_string = traceback.format_exc()
        860
        861            # build up some context from the offending package so we can
  >>    862            # show that, too.
        863            package_context = get_package_context(tb)
        864
        865            build_log = None
```
* **Spack:** 0.15.0-457-73486df9f
* **Python:** 3.6.10
* **Platform:** linux-sles15-haswell

Google tells me e.g. https://stackoverflow.com/questions/18649512/unicodedecodeerror-ascii-codec-cant-decode-byte-0xe2-in-position-13-ordinal

[spack-build-out-py@3.6.10.txt](https://github.com/spack/spack/files/5049572/spack-build-out-py%403.6.10.txt)
[spack-build-env-py@3.6.10.txt](https://github.com/spack/spack/files/5049573/spack-build-env-py%403.6.10.txt)

2. Problem 1 does not show up for python 3.7.8, but a second problem occurs

The soft link commands in the makefiles of the test subdir are missing the `-T` option. Seemingly, this causes trouble if the `/tmp/` dir has the sticky bit set. 
* **Spack:** 0.15.3
* **Python:** 3.7.8
* **Platform:** linux-sles15-haswell

```console
==> Installing charliecloud
==> No binary for charliecloud found: installing from source
==> charliecloud: Executing phase: 'autoreconf'
==> charliecloud: Executing phase: 'configure'
==> charliecloud: Executing phase: 'build'
==> charliecloud: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j24' 'install'

1 warning found in build log:
     52    checking for squashfuse... no
     53    checking for tar... tar
     54    checking if in chroot... no
     55    checking if user+mount namespaces work... yes
     56    checking for wget... wget
     57    checking if wget version >= 1.11... ok (1.20.3)
  >> 58    configure: WARNING: forcing --disable-man: no suitable sphinx-build
     59    checking that generated files are newer than configure... done
     60    configure: creating ./config.status
     61    config.status: creating Makefile
     62    config.status: creating bin/Makefile
     63    config.status: creating doc/Makefile
     64    config.status: creating examples/Makefile
```

The relevant section in spack-build-out.txt is
```
Making install in test
make[1]: Entering directory '/gpfs/scratch/pr28fa/lu64bag3/lu64bag3/x86_64/spack-stage-charliecloud-0.16-vwfj3nhb4cvcmjlxbaz2ly4nl4>
ln -fs /tmp fixtures/symlink-to-tmp
ln: failed to create symbolic link 'fixtures/symlink-to-tmp/tmp': Operation not permitted
make[1]: *** [Makefile:664: all-local] Error 1
make[1]: Leaving directory '/gpfs/scratch/pr28fa/lu64bag3/lu64bag3/x86_64/spack-stage-charliecloud-0.16-vwfj3nhb4cvcmjlxbaz2ly4nl4v>
make: *** [Makefile:389: install-recursive] Error 1

> ll -d /tmp
drwxrwxrwt 19 root root 8192 Aug 10 10:05 /tmp
```
[spack-build-out.txt](https://github.com/spack/spack/files/5049619/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/5049620/spack-build-env.txt)

For 0.16 I've created a patch

```
--- a/test/Makefile.in	2020-08-09 12:17:29.474772000 +0200
+++ b/test/Makefile.in	2020-08-09 12:18:40.766768940 +0200
@@ -661,12 +661,12 @@
 
 # See comment about symlinks in examples/Makefile.am.
 @ENABLE_TEST_TRUE@all-local:
-@ENABLE_TEST_TRUE@	ln -fs /tmp fixtures/symlink-to-tmp
+@ENABLE_TEST_TRUE@	ln -fTs /tmp fixtures/symlink-to-tmp
 @ENABLE_TEST_TRUE@clean-local:
 @ENABLE_TEST_TRUE@	rm -f fixtures/symlink-to-tmp
 @ENABLE_TEST_TRUE@install-data-hook:
 @ENABLE_TEST_TRUE@	mkdir $(DESTDIR)$(testdir)/fixtures
-@ENABLE_TEST_TRUE@	ln -fs /tmp $(DESTDIR)$(testdir)/fixtures/symlink-to-tmp
+@ENABLE_TEST_TRUE@	ln -fTs /tmp $(DESTDIR)$(testdir)/fixtures/symlink-to-tmp
 @ENABLE_TEST_TRUE@uninstall-hook:
 @ENABLE_TEST_TRUE@	rm -f $(DESTDIR)$(testdir)/fixtures/symlink-to-tmp
 @ENABLE_TEST_TRUE@	rmdir $(DESTDIR)$(testdir)/fixtures || true

```
that fixes the problem. However, the patch does not work for 0.17 #17855 out of the box, so one would probably need to fix the Makefile.am and run autotools again.

pinging maintainers: @j-ogas @reidpr 
### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by reidpr** [comment]
Hi, thanks for the bug reports!

Re. problem 1, I think this is a Spack bug. Charliecloud's configure output includes Unicode characters, specifically the greater than or equal to symbol U+2265 “≥”, which in UTF-8 is represented by the sequence [E2 89 A5](http://www.ltg.ed.ac.uk/~richard/utf-8.cgi?input=%E2%89%A5&mode=char). Note the offending byte `0xe2`. Spack should be fixed to accept Unicode output from configure.

I believe Problem 2 was fixed upstream in PR hpc/charliecloud#722, which went into 0.16.

**Comment by g-mathias** [comment]
Issue 1 may be a particular problem of python 3.6.x - I've seen similar bug reports for Ubuntu as well.

For Issue 2 PR hpc/charliecloud#722 fixes the issue only in `examples` - the `test` directory was forgotten. Hope it will be fixed in the upcoming 0.18 version of charliecloud.

**Comment by reidpr** [comment]
I merged the PR for issue 2. Is there a way to test our master in Spack?

And I claim issue 1 isn't a problem with the Charliecloud package but rather Spack more broadly.

As to what to do with this issue according to the Spack workflow, I don't know.

**Comment by g-mathias** [comment]
Hi, for issue 1 using python@3.7 for spack seems to be a viable workaround. Building charliecloud@master now works and I see the `ln -fTs /tmp  ...charliecloud/test/fixtures/symlink-to-tmp` now. Great, thanks!
Personally, I would consider this issue resolved. Fixing it for 0.16&0.17 seems too much effort considering the fast release policy of charliecloud. If somebody has the same problem and needs  0.16&0.17 this issue gives a blueprint how to fix it.

**Comment by g-mathias** [comment]
charliecloud@0.18 is out and works out of the box. I'll close the issue.
