### ISSUE TITLE
Problem with compiler selection Intel vs AMD; allow more specific targets in compilers.yaml

### ISSUE THREAD

**Issue by payerle** [LLNL/spack#17987]
Spack does not appear to readily allow one to specify a different compiler to use for AMD vs Intel builds.  This is problematic because I am seeing cases wherein compiling a package on AMD using a gcc compiler built on Intel platform fails, but the same compilation (same spack command) succeeds if I replace the compiler in compilers.yaml with the same version of gcc built on AMD system.

However, I am unable to have single compilers.yaml with both Intel and AMD built compilers and have the correct compiler selected based on the CPU microarchitecture.  If I include both AMD and Intel built gccs (same version) in compilers.yaml, they both have to have the 'target' field set to 'x86_64', and the first one occuring in compilers.yaml is used for both architectures.  If I try to set the 'target' field to something more specific (e.g. 'zen'), I get an error like
==> Error: the "target" field in compilers.yaml accepts only target families [replace "zen" with "x86_64" in "gcc@8.4.0" specification]
whenever concretizing a spec.

Although it would be nice if one only needed to match compilers to the target family, this does not appear to be the case, as described below:

I have an Intel (mostly ivybridge) based cluster to which an AMD zen2 system was added, all running RHEL8. I built gcc@8.4.0 on x86_64 system using spack, added it to compilers.yaml, and 
successfully used to build many packages (including pkg-config) on both x86_64 and ivybridge
systems.  When I tried to reproduce the software stack on the zen2 system, I quickly ran into issues.
While trying to build pkg-config@0.29.2 +internal_glib %gcc@8.4.0
using the x86_64 (Intel) built compiler, it failed (the configuration of the internal glib failed with an error complaining that I needed to use a 64 bit compiler like gcc).
However, I discovered if I built gcc@8.4.0 on the zen2 system (using the same spack configuration/variants/etc used to build on the Intel systems) and replaced the compiler in
compilers.yaml with the AMD built one, and the same spack command succeeded.

Further investigation revealed that some of the header files installed/used by the two different gcc
builds were different.  In particular, during a configuration test for the internal glib in pkg-config to determine the sizeof the long data type, the differences in the 
$INSTALL_ROOT/gcc-8.4.0-$HASH/lib/gcc/x86_64-pc-linux-gnu/8.4.0/include-fixed/bits/statx.h
headers (around line 38, the stanza after the GCC PR 80005 comment) were causing the test code to fail to compile, resulting in errors further down in the configure script.

While I believe the configure script has issues, the fact is that using the Intel built gcc on an AMD system potentially results in gcc having trouble processing its own header files, and I expect this will cause widespread issues in building a software stack on AMD.  I would like to force the use of an AMD built compiler on the AMD systems, but this cannot be readily done in compilers.yaml.  (I can do it using environments, but that is non-ideal/somewhat messy.)

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by payerle** [comment]
### Additional Information
spack debug report
* **Spack:** 0.14.2
* **Python:** 3.6.8
* **Platform:** linux-rhel8-zen2

**Comment by ilbiondo** [comment]
As AMD and Intel seem to have diverged sufficiently to not be compatible a simpler solution might be to split them into two families. 

This is defined in lib/spack/llnl/util/cpu/microarchitectures.json and looks to be reasonably simple to change.

Changing

```
     "zen": {
      "from": "x86_64",
      "vendor": "AuthenticAMD",
```

to

```
    "zen": {
      "from": "null",
      "vendor": "AuthenticAMD",
```

Should be enough to create a new "zen" family although it would be cleaner to start at the top and create `x86_64_Intel` and `x86_64_AMD` but that's a bit more work.

**Comment by alalazo** [comment]
@ilbiondo The issue here is more subtle and has to do with the fact that currently we only have a single `target` attribute while we should have at least two attributes like e.g. `host` and `target`. One would serve to identify where the compiler can run the other where the executables it produces can run. There's work on-going to improve support for cross-compilation that will touch this aspect, but as far as I know it's to be expected after v0.16 (very likely after we turned compilers into proper dependencies).

**Comment by payerle** [comment]
The comments of others and the work towrd making compilers full fledged dependencies notwithstanding, it looks like I my initial diagnosis of the problem that led to this discussion was in error.

The error building pkg-config appears not to have been due to the intel vs amd difference, but issues with the RHEL8 glibc --- see e.g. 
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=94089

The new amd system was installed with the newer glibc, the intel systems initially had the older glibc (and were updated later).  The gccs built on the intel systems were built against the older glibc, and did not like building stuff against the newer glibc on the amd system (and eventually, after glibc on the intel systems were upgraded, on the intel systems).  Rebuilding the gccs against the new glibc seems to have resolved the issues.

Based on the earlier discussion, there seem to be some motivation and recognition of a need to allow for better compiler selection distinct from my issue --- if that is the case and you wish to leave this ticket open for that purpose, feel free to do so.  Otherwise, it is fine by me if you wish to close the ticket.

**Comment by alalazo** [comment]
Closing this after https://github.com/spack/spack/issues/17987#issuecomment-680235510 Anybody who disagrees, let me know if you want this reopened.
