### ISSUE TITLE
LLVM's support lib cmake targets have dependencies on system libs (zlib, ncurses/tinfo)

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#17981]
When building `spack install llvm`, it creates a cmake file:

https://github.com/llvm/llvm-project/blob/master/llvm/lib/Support/CMakeLists.txt#L1

which is installed to e.g.

```
opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/llvm-10.0.0-576xf5b5mlqxsskl45ucl3xxxmjxssio/lib/cmake/llvm
```
It contains certain strict dependencies on 'system libraries':

```
$ grep tinfo LLVMExports.cmake 
  INTERFACE_LINK_LIBRARIES "z;rt;dl;tinfo;-lpthread;m;/home/harmen/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/z3-4.8.7-qiwh5wxz2mdknzv4gef7lwxxdnlf5ycx/lib/libz3.so;LLVMDemangle"
```
only `z3` has a proper path to the spack installed lib.

In my case I was building rocBLAS, which uses this LLVM target, links against the system version of `libtinfo.so`, but gets an RPATH to the spack-version of it, and therefore it fails at runtime.

**Comment by naromero77** [comment]
Yes, please report the issue on LLVM bugzilla. It would be good to get this upstreamed.

@trws Are you OK with the change?

**Comment by haampie** [comment]
@naromero77 I was about to submit a patch, but a few hours ago someone pushed changes that actually already address `zlib`, they now use find_package :) https://reviews.llvm.org/D79219. 

So we can drop at least part of my patch in upcoming releases of LLVM

I've submitted a patch for ncurses here: https://reviews.llvm.org/D85820

**Comment by trws** [comment]
Yeah, I'm good with this.  As long as we're not overriding something they vendor, but replacing usage of a system package, I think it's an improvement.  Thanks!

**Comment by haampie** [comment]
@trws and @naromero77: the patches upstream will not be merged into LLVM 11, since they not only changed how zlib / ncurses are detected, they also changed how certain cmake variables are used. We shouldn't backport those exact commits to LLVM 10 or anything.

I would still be in favor of fixing those things in spack for LLVM <= 10 (and then LLVM 11 too, later) using non-invasive patches. Some care has to be taken though, cause in my recent experience with submitting a patch to LLVM it's very easy to break things, cause everything is used in some obscure way (I broke OCaml bindings with a trivial patch).

We basically need https://github.com/spack/spack/pull/17986, and on top of that something that ensures that this `LLVM_SYSTEM_LIBS` variable in https://github.com/llvm/llvm-project/blob/17cd34409a3ab1c46ff55960b7b89c11e1d5674d/llvm/lib/Support/CMakeLists.txt#L232 still contains `z` and `tinfo`, instead of full paths to libs -- this variable is used by some non-cmake-build systems to link against things, so it should end up with `-lz` and not `-lpath/to/libz.so` etc. Currently this is done through this new function: https://github.com/llvm/llvm-project/blob/17cd34409a3ab1c46ff55960b7b89c11e1d5674d/llvm/lib/Support/CMakeLists.txt#L5-L16

Should I contribute that as well, or is it too big of a patch?

**Comment by naromero77** [comment]
I am OK with a non-invasive patch or even several non-invasive patches as long as they don't break other critical things.

**Comment by haampie** [comment]
There is no such a thing as a non-intrusive patch to LLVM :laughing:.

Upstream patches have been reverted temporarily because of too many issues. I'll give it another try this weekend.

**Comment by sethrj** [comment]
@haampie it looks like these patches got merged upstream so I'll close this issue, please reopen if it's not addressed.

**Comment by haampie** [comment]
Indeed I didn't look at it that weekend
