### ISSUE TITLE
Doc error? include config in env spack.yaml applied in different order than online docs say

### ISSUE THREAD

**Issue by payerle** [LLNL/spack#17993]
The online documentation:
https://spack.readthedocs.io/en/latest/environments.html
in the section "Included configurations"
states
"Included configs listed later will have higher precedence, as the included configs are applied in order."

This does not match what I see when using included configurations.
### Steps to reproduce the issue
1) Clone a new spack instance, copy yaml configs from etc/spack/defaults to etc/spack, and create a compilers.yaml with system compiler

2) spack env create test

3) Edit the spack.yaml for test env to be
```yaml
spack:
  specs: []
  view: true
  include:
    - /homes/payerle/spacktest/A/test.yaml
    - /homes/payerle/spacktest/B/testb.yaml
```
4) Create the /homes/payerle/spacktest/A/test.yaml
with contents:
```yaml
packages:
  libiconv:
    version: [1.15]
```
5) Create the /homes/payerle/spacktest/B/testb.yaml
with contents:
```yaml
packages:
  libiconv:
    version: [0.14]
```
6) Run a spec command for libiconv using the test environment:
```console
$ spack --debug --env test spec libiconv
==> [2020-08-11-12:12:40.487271] Imported spec from built-in commands
==> [2020-08-11-12:12:40.487841] Imported spec from built-in commands
Input spec
--------------------------------
libiconv

Concretized
--------------------------------
==> [2020-08-11-12:12:40.489582] Reading config file /homes/payerle/spacktest/B/testb.yaml
==> [2020-08-11-12:12:40.493707] Reading config file /homes/payerle/spacktest/A/test.yaml
==> [2020-08-11-12:12:40.496421] Reading config file /export/data/localhome/home/payerle/git/spack.test/var/spack/environments/test/spack.yaml
==> [2020-08-11-12:12:40.498496] Reading config file /export/data/localhome/home/payerle/git/spack.test/etc/spack/defaults/repos.yaml
==> [2020-08-11-12:12:40.499822] Reading config file /export/data/localhome/home/payerle/git/spack.test/etc/spack/repos.yaml
==> [2020-08-11-12:12:40.529911] Reading config file /export/data/localhome/home/payerle/git/spack.test/etc/spack/defaults/packages.yaml
==> [2020-08-11-12:12:40.546539] Reading config file /export/data/localhome/home/payerle/git/spack.test/etc/spack/packages.yaml
==> [2020-08-11-12:12:40.563246] Reading config file /export/data/localhome/home/payerle/git/spack.test/etc/spack/compilers.yaml
==> [2020-08-11-12:12:40.568517] Reading config file /homes/payerle/.spack/linux/compilers.yaml
==> [2020-08-11-12:12:40.579323] '/usr/bin/gcc' '-dumpversion'
==> [2020-08-11-12:12:40.582085] '/usr/bin/gcc' '-dumpversion'
==> [2020-08-11-12:12:40.584372] '/usr/bin/gcc' '-dumpversion'
==> [2020-08-11-12:12:40.586276] Warning: gcc@rh7-4.8.5 cannot build optimized binaries for "skylake". Using best target possible: "haswell"
==> [2020-08-11-12:12:40.593281] DATABASE LOCK TIMEOUT: 3s
==> [2020-08-11-12:12:40.593362] PACKAGE LOCK TIMEOUT: No timeout
==> [2020-08-11-12:12:40.596693] '/usr/bin/gcc' '-dumpversion'
libiconv@1.15%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
```
As can be seen from the debug messages and from the final result (libiconv@1.15), the testb.yaml file is applied before the test.yaml file, so test.yaml "wins" the conflict re libiconv version.

Thus the include files are applied in reverse order, with earlier files "beating" later files, which
contradicts the documentation.

I would recommend fixing the documentation to accurately reflect what is happening.

### Information on your system
spack debug report
* **Spack:** 0.15.3-488-313511b
* **Python:** 2.7.5
* **Platform:** linux-rhel7-skylake

### Additional information
See also issue #17992

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
@tgamblin @becker33

**Comment by payerle** [comment]
Sorry, I just realized I had ability to make pull requests for docs, so added my proposed doc change.
