### ISSUE TITLE
Included configs in env spack.yaml ignored if basename matches previously included config

### ISSUE THREAD

**Issue by payerle** [LLNL/spack#17992]
When using the include: field inside a spack.yaml for an environment, it appears that if two of the included configurations have the same basename (i.e. same name but in different directories), only the first file with the same basename is "included".  I would have expected both to be included.

### Steps to reproduce the issue

1) Clone a new spack install, copy *.yaml from ../etc/spack/defaults to ../etc/spack, and create a compilers.yaml with system compiler.

2) spack env create test

3) Edit the spack.yaml for the newly created test environment to be
```yaml
# This is a Spack Environment file.
#
# It describes a set of packages to be installed, along with
# configuration settings.
spack:
  # add package specs to the `specs` list
  specs: []
  view: true
  include: 
    - /homes/payerle/spacktest/A/test.yaml
    - /homes/payerle/spacktest/B/test.yaml
```
4) Create /homes/payerle/spacktest/A/test.yaml with contents:
```yaml
packages:
  libiconv:
    version: [1.15]
```
5) Create  /homes/payerle/spacktest/B/test.yaml with contents:
```yaml
packages:
  pkg-config:
    version: [0.28]
```
6) Run the following spack spec commands:
6a) spack  spec libiconv
Returns libiconv@1.16 as expected (no env specified, latest version of libiconv)
6b) spack  spec pkg-config
Returns pkg-config@0.29.2 as expected (no env specified, latest version of pkg-config)
6c) spack  --env test spec libiconv
Returns libiconv@1.15 (env test via A/test.yaml says to use 1.15)
6d) spack --env test spec pkg-config
Returns pkg-config@0.29.2
I expect it to return pkg-config@0.28 as is using env test and B/test.yaml says to use 0.28

If one reverses the order of the two include lines in spack.yaml for test env (so B precedes A),
then 6d returns pkg-config@0.28 as expected, but 6c returns libiconv@1.16, not as expected.

Indeed, if I add the line 'xxx' before the 'packages:' in either A/test.yaml or B/test.yaml (making it
syntactically invalid), an error is only reported when the invalid test.yaml is first in the include list.
I.e., if using the original order (A/test.yaml then B/test.yaml), adding a syntax error to B/test.yaml
does not cause spack to report an error (but adding to A/test.yaml does).  This seems to indicate that the second file is not even being parsed.

If I rename B/test.yaml to B/testb.yaml (and change the the include line accordingly), things work as expected (specs of both libiconv and pkg-config return the expected version with the test env).

```console
$ spack <command1> <spec>
$ spack <command2> <spec>
...
```
spack debug report
* **Spack:** 0.15.3-488-313511b
* **Python:** 2.7.5
* **Platform:** linux-rhel7-skylake

### Additional information

Running the command from 6d in debug mode (with the original settings:
A/test.yaml then B/test.yaml in the include list returns:
```console
$ spack  --debug  --env test spec pkg-config
==> [2020-08-11-11:58:43.867071] Imported spec from built-in commands
==> [2020-08-11-11:58:43.867622] Imported spec from built-in commands
Input spec
--------------------------------
pkg-config

Concretized
--------------------------------
==> [2020-08-11-11:58:43.868596] Reading config file /homes/payerle/spacktest/A/test.yaml
==> [2020-08-11-11:58:43.871876] Reading config file /export/data/localhome/home/payerle/git/spack.test/var/spack/environments/test/spack.yaml
==> [2020-08-11-11:58:43.873922] Reading config file /export/data/localhome/home/payerle/git/spack.test/etc/spack/defaults/repos.yaml
==> [2020-08-11-11:58:43.875212] Reading config file /export/data/localhome/home/payerle/git/spack.test/etc/spack/repos.yaml
==> [2020-08-11-11:58:43.905672] Reading config file /export/data/localhome/home/payerle/git/spack.test/etc/spack/defaults/packages.yaml
==> [2020-08-11-11:58:43.921249] Reading config file /export/data/localhome/home/payerle/git/spack.test/etc/spack/packages.yaml
==> [2020-08-11-11:58:43.938180] Reading config file /export/data/localhome/home/payerle/git/spack.test/etc/spack/compilers.yaml
==> [2020-08-11-11:58:43.942277] Reading config file /homes/payerle/.spack/linux/compilers.yaml
==> [2020-08-11-11:58:43.953119] '/usr/bin/gcc' '-dumpversion'
==> [2020-08-11-11:58:43.955920] '/usr/bin/gcc' '-dumpversion'
==> [2020-08-11-11:58:43.958114] '/usr/bin/gcc' '-dumpversion'
==> [2020-08-11-11:58:43.960050] Warning: gcc@rh7-4.8.5 cannot build optimized binaries for "skylake". Using best target possible: "haswell"
==> [2020-08-11-11:58:43.967341] DATABASE LOCK TIMEOUT: 3s
==> [2020-08-11-11:58:43.967411] PACKAGE LOCK TIMEOUT: No timeout
==> [2020-08-11-11:58:43.970835] '/usr/bin/gcc' '-dumpversion'
pkg-config@0.29.2%gcc@rh7-4.8.5+internal_glib arch=linux-rhel7-haswell
```

- [x ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by payerle** [comment]
See also #17993 (re order in which include files applied.  The example in the current issue display that as well, but as the ordering issue is basically just a mismatch between docs and actual behavior and will likely be just a doc fix, I split into a separate issue)

**Comment by adamjstewart** [comment]
@tgamblin @becker33
