### ISSUE TITLE
Want Spack Docker container based on Ubuntu 20.04

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#18005]
I want a Spack Docker container based on Ubuntu 20.04. I refer to the image that is used by Spack to build packages (the "build" stage).

### Rationale

Ubuntu 18.04 provides GCC 7, which is too old. I need at least GCC 8. By using Ubuntu 20.04 as base image, this would be solved.

### Description

It is possible to install GCC 8 with Ubuntu 18.04, and change a few settings to make it the default compiler. However, this would also need to be done in the base image that Spack uses to build, and might be more difficult than switching to Ubuntu 20.04.

Another option would be to build a newer GCC with Spack, and use this later to build other packages. This is also a more complex approach.

### General information

$ spack --version
0.15.3-490-80a382c21

- [x] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
FWIW, it's trivial to install gcc-9 on ubuntu:16.04 even:

```
FROM ubuntu:16.04

RUN apt-get update -qq && \
  apt-get install -qq software-properties-common apt-transport-https --no-install-recommends && \
  add-apt-repository -y ppa:ubuntu-toolchain-r/test && \
  apt-get -qq install gcc-9 g++-9 gfortran-9 --no-install-recommends && \
  rm -rf /var/lib/apt/lists/*
```
it could be useful because linking against an older libc makes your binaries compatible with newer versions too. At the same time though, spack sees different OS-platforms as incompatible by default, since it's part of the triplet.

**Comment by eschnett** [comment]
GCC-9 produces (in its default setting) code that is not binary compatible with older versions of GCC. The problem is that the STL (e.g. the `string` class) is sensitive to whether `-std=c++17` is used or not, and this option is the default on newer versions of GCC, but not on older ones. Hence packages written in C++ (Boost etc.) are not binary compatible: I cannot use GCC-9 to compiler code that wants to link to a system Boost, since the system Boost was built without this option and is hence not ABI compatible.
