### ISSUE TITLE
Clang/Cuda compatibility on power9

### ISSUE THREAD

**Issue by JulienLoiseau** [LLNL/spack#18001]
I am working on Power9 architecture. 
The module already existing are: 
cuda 9.2 
cuda 10.2 
cuda 11.0 

I have multiple versions of clang available: 
clang 8.0.1 
clang 8.0.0
clang 7.0.0
I also installed llvm 10.0.0 and master (11.0.0?) using spack. 

I want to install Kokkos using a combination of clang/cuda but I encounter problems of compatibility even if as listed (https://gist.github.com/ax3l/9489132#clang--x-cuda) there should not be any problem for these version. 
I took Kokkos as a simple example here but all the other code that depend on Cuda give me the same problem with Clang/Cuda. 

#### Clang 10 : only clang 10 + cuda 11 is working properly 

Clang 10/Cuda 9.2
```console
spack install kokkos +cuda cuda_arch=72 %clang@10.0.0 ^cuda@9.2
```
Error: 
```console
==> Warning: the attribute "modules" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('cuda@9.2', 'cuda/9.2'), ('cuda@10.2', 'cuda/10.2'), ('cuda@11.0', 'cuda/11.0')])]
==> Error: Conflicts in concretized spec "kokkos@3.1.01%clang@10.0.0~aggressive_vectorization~compiler_warnings+cuda~cuda_lambda~cuda_ldg_intrinsic~cuda_relocatable_device_code~cuda_uvm~debug~debug_bounds_check~debug_dualview_modify_check~deprecated_code~examples~explicit_instantiation~hip~hpx~hpx_async_dispatch~hwloc~memkind~numactl~openmp~pic+profiling~profiling_load_print~pthread~qthread+serial+shared~tests~wrapper amd_gpu_arch=none build_type=RelWithDebInfo cuda_arch=72 std=11 arch=linux-rhel7-power9le/ie32y66"
List of matching conflicts for spec:

    kokkos@3.1.01%clang@10.0.0~aggressive_vectorization~compiler_warnings+cuda~cuda_lambda~cuda_ldg_intrinsic~cuda_relocatable_device_code~cuda_uvm~debug~debug_bounds_check~debug_dualview_modify_check~deprecated_code~examples~explicit_instantiation~hip~hpx~hpx_async_dispatch~hwloc~memkind~numactl~openmp~pic+profiling~profiling_load_print~pthread~qthread+serial+shared~tests~wrapper amd_gpu_arch=none build_type=RelWithDebInfo cuda_arch=72 std=11 arch=linux-rhel7-power9le
        ^cmake@3.18.1%clang@10.0.0~doc+ncurses+openssl+ownlibs~qt arch=linux-rhel7-power9le
            ^ncurses@6.2%clang@10.0.0~symlinks+termlib arch=linux-rhel7-power9le
                ^pkgconf@1.7.3%clang@10.0.0 arch=linux-rhel7-power9le
            ^openssl@1.1.1g%clang@10.0.0+systemcerts arch=linux-rhel7-power9le
                ^perl@5.30.3%clang@10.0.0+cpanm+shared+threads arch=linux-rhel7-power9le
                    ^berkeley-db@18.1.40%clang@10.0.0 arch=linux-rhel7-power9le
                    ^gdbm@1.18.1%clang@10.0.0 arch=linux-rhel7-power9le
                        ^readline@8.0%clang@10.0.0 arch=linux-rhel7-power9le
                ^zlib@1.2.11%clang@10.0.0+optimize+pic+shared arch=linux-rhel7-power9le
        ^cuda@9.2%clang@10.0.0 arch=linux-rhel7-power9le

1. "%clang@6:" conflicts with "kokkos+cuda ^cuda@:9.2 arch=linux-None-ppc64le:"
2. "%clang@7.1:" conflicts with "kokkos+cuda ^cuda@:10.1.105 arch=linux-None-ppc64le:"
3. "%clang@8.1:" conflicts with "kokkos+cuda ^cuda@:10.2.89 arch=linux-None-ppc64le:"
```

Clang 10/Cuda 10.2
```console
spack install kokkos +cuda cuda_arch=72 %clang@10.0.0 ^cuda@10.2
```
Error: 
```console
==> Warning: the attribute "modules" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('cuda@9.2', 'cuda/9.2'), ('cuda@10.2', 'cuda/10.2'), ('cuda@11.0', 'cuda/11.0')])]
==> Error: Conflicts in concretized spec "kokkos@3.1.01%clang@10.0.0~aggressive_vectorization~compiler_warnings+cuda~cuda_lambda~cuda_ldg_intrinsic~cuda_relocatable_device_code~cuda_uvm~debug~debug_bounds_check~debug_dualview_modify_check~deprecated_code~examples~explicit_instantiation~hip~hpx~hpx_async_dispatch~hwloc~memkind~numactl~openmp~pic+profiling~profiling_load_print~pthread~qthread+serial+shared~tests~wrapper amd_gpu_arch=none build_type=RelWithDebInfo cuda_arch=72 std=11 arch=linux-rhel7-power9le/7mbl2ho"
List of matching conflicts for spec:

    kokkos@3.1.01%clang@10.0.0~aggressive_vectorization~compiler_warnings+cuda~cuda_lambda~cuda_ldg_intrinsic~cuda_relocatable_device_code~cuda_uvm~debug~debug_bounds_check~debug_dualview_modify_check~deprecated_code~examples~explicit_instantiation~hip~hpx~hpx_async_dispatch~hwloc~memkind~numactl~openmp~pic+profiling~profiling_load_print~pthread~qthread+serial+shared~tests~wrapper amd_gpu_arch=none build_type=RelWithDebInfo cuda_arch=72 std=11 arch=linux-rhel7-power9le
        ^cmake@3.18.1%clang@10.0.0~doc+ncurses+openssl+ownlibs~qt arch=linux-rhel7-power9le
            ^ncurses@6.2%clang@10.0.0~symlinks+termlib arch=linux-rhel7-power9le
                ^pkgconf@1.7.3%clang@10.0.0 arch=linux-rhel7-power9le
            ^openssl@1.1.1g%clang@10.0.0+systemcerts arch=linux-rhel7-power9le
                ^perl@5.30.3%clang@10.0.0+cpanm+shared+threads arch=linux-rhel7-power9le
                    ^berkeley-db@18.1.40%clang@10.0.0 arch=linux-rhel7-power9le
                    ^gdbm@1.18.1%clang@10.0.0 arch=linux-rhel7-power9le
                        ^readline@8.0%clang@10.0.0 arch=linux-rhel7-power9le
                ^zlib@1.2.11%clang@10.0.0+optimize+pic+shared arch=linux-rhel7-power9le
        ^cuda@10.2%clang@10.0.0 arch=linux-rhel7-power9le

1. "%clang@8.1:" conflicts with "kokkos+cuda ^cuda@:10.2.89 arch=linux-None-ppc64le:"
```

Clang 10/Cuda 11

```console
 spack install kokkos +cuda cuda_arch=72 %clang@10.0.0 ^cuda@11.0
```

This is the only working combination.

I have the same kind of error using other version of clang like clang 8.0.0 or clang 7.0.0 even if these versions should be compatible regarding to: https://gist.github.com/ax3l/9489132#clang--x-cuda

### Information on your system

debug report: 
```
* **Spack:** 0.15.3-489-2f0fd44
* **Python:** 3.7.8
* **Platform:** linux-rhel7-power9le: 
```
packages.yaml: 
```
packages:
  cuda: 
    modules:
      cuda@9.2: cuda/9.2 
      cuda@10.2: cuda/10.2
      cuda@11.0: cuda/11.0
```
### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
@ax3l @svenevs

**Comment by JulienLoiseau** [comment]
The file with the conflicts: 
https://github.com/spack/spack/blob/develop/lib/spack/spack/build_systems/cuda.py

**Comment by junghans** [comment]
Details here: https://gist.github.com/ax3l/9489132

**Comment by svenevs** [comment]
Only had time for a quick look but AFAICT this is a usage misunderstanding?

1. There is usually only one version of clang you can use as the host compiler. nvcc will wrap that rather than gcc, similar to how Intel works. For a given version of CUDA, check the install guide for your platform (which are also encoded in the cuda build system, e.g. search "CUDA 11 install guide Linux"). Example clang 9 is the only supported version in CUDA 11: https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#system-requirements
2. The LLVM project has started being able to build CUDA on its own. I forget when this started, but it's essentially the reverse -- CUDA toolkit needs to be installed and llvm compiled with it. We don't currently support this (clang as CUDA compiler), and it may be a while before we do. So this part https://gist.github.com/ax3l/9489132#clang--x-cuda is not something spack supports currently.

Does that explain what's going on here? The concretizer is enforcing the constraints from (1), we don't have a way of enforcing or supporting (2) currently and probably won't until compilers are "proper" dependencies (the new concretizer). I believe many projects that build with "proper CUDA" (v1 with nvcc) will need attention / support to work with "clang -x cuda", it's not going to be as simple as "compile with clang instead."

Sorry if I misread, I will try and take a deeper look this weekend if I misunderstood the problem!

**Comment by scothalverson** [comment]
Hi, I'm working with Julien and encountering the same issue.  While I understand the points you're making, I think they're orthogonal to the issue that Julien and I are seeing.  

The crux of it is that we're seeing conflicts listed where nominally (and practically) there aren't any.  We're trying to compile with a combination of Clang 10.0 and CUDA 10.1 or 10.2.  In doing so, we're seeing conflicts associated with Clang 6, 7, and 8 which should not apply, and don't represent real conflicts.  That is, Clang 10.0 and CUDA 10.1 are compatible in the way we're using them.  That combination is also not listed as a conflict anywhere in Spack.  Yet, spack is picking this up as a conflict, likely to an overly broad conflict detection.

**Comment by ax3l** [comment]
Hi @JulienLoiseau ,

the table you linked https://gist.github.com/ax3l/9489132#clang--x-cuda is not the nvcc with clang (as host-compiler) compatibility, but the clang (as CUDA device compiler) compatibility with the CUDA SDK.

The first table for nvcc as device compiler https://gist.github.com/ax3l/9489132#nvcc shows the compatibilities with host compilers, including clang.

NVCC from Nvidia only supports clang 8 as host compiler in CUDA 10.2.
NVCC shipping with CUDA 11.0 also supports clang 9. There is no vendor support for clang 10 as host-compiler for NVCC yet.

> That is, Clang 10.0 and CUDA 10.1 are compatible in the way we're using them.

Which way do you mean exactly, are you using `clang -x cuda` as paired host & device compiler? What we could potentially do is, as [mentioned above in 2)](https://github.com/spack/spack/issues/18001#issuecomment-675771610), add a variant to the `cuda` package that takes `nvcc` or `clang` as the cuda device compiler. That way we can also change the conflicts.
Individual packages that provide a cuda variant, like kokkos, would need to query the selected device compiler in their recipe and set according build flags. (This should work well with CMake 3.18+.)

**Comment by DavidPoliakoff** [comment]
Hi @JulienLoiseau , so far we've had Spack users, and clang-cuda users, but I don't that we've had Spack clang-cuda users. We'll be discussing this in our Slack, but we have CMake lines for this that work, we'll see about pushing them to the Spack package. What we'd need from Spack

1) Verify that the Clang we're using enables the NVPTX target
2) A way to find the CUDA toolkit to pass a --cuda-path argument to Clang

Are there idioms for achieving those two things? Or magic that makes them not matter (my favorite option)?

EDIT: I was going to recommend you bring that Scot Halverson guy in, but I see we've already done that :)

**Comment by DavidPoliakoff** [comment]
It looks like this is the problem:

https://github.com/spack/spack/blob/develop/lib/spack/spack/build_systems/cuda.py#L106-L116

Spack is saying "we conflict with Clang between 5 and *10* (for some reason)" on these CUDA versions. Well, we just happen to pass a Clang > 10, which avoids that set, but it's not really clear why that works how it does.

**Comment by scothalverson** [comment]
Hi @ax3l,

We end up using clang both as host+device through `-x cuda` and as a host-only compiler paired with NVCC.  The latter is How Legion requires us to build right now for example.    

 @DavidPoliakoff, so this issue doesn't present itself with a Clang greater than 10?  Can you elaborate on which pairing of Clang and CUDA you're using?  And perhaps more specifically, are you successfully using it to compile GPU code via `-x cuda` ?

**Comment by crtrott** [comment]
If I understand this correct: This is NOT a problem in Kokkos, we support any (and test a few) combinations of clang and CUDA with clang as the device compiler (i.e. clang++ -x cuda, where we add the -x cuda internally). But spack apparently has its ownd compatibility list which is independent of Kokkos and which is just the conflict list of using clang as the host compiler for nvcc - not what you are trying to do. That conflict list for using clang as the host compiler is correct from spack but there is a different conflict list when using clang as the main compiler. We do not enforce that actually. That means if you compile for example with clang 8 and CUDA 10.2 you will just get cryptic errors. This is a change one needs to make in spack itself.

**Comment by DavidPoliakoff** [comment]
@scothalverson , this is actually more confusing than I thought, I saw the original comment mention that

` spack install kokkos +cuda cuda_arch=72 %clang@10.0.0 ^cuda@11.0` - worked

And thought the issue might be to do with the CUDA conflicts based on [this comment](https://github.com/spack/spack/issues/18001#issuecomment-675584879).

But then if `Clang 10/Cuda 10.2` doesn't work, that explanation falls apart. This feels like some really weird oblique constraint (or something thunderingly obvious that I'm just missing). Does anybody have a sense of how to debug Spack's constraint solving, see where a conflict is arising from?

**Comment by DavidPoliakoff** [comment]
@JulienLoiseau , good catch from @crtrott, could we get the exact version of your CUDA 11 (patch included)? There's this small gap where Spack only blocks Clang 10 when CUDA 11 is exactly CUDA 11.0.2, that could create interesting situations

**Comment by JulienLoiseau** [comment]
@DavidPoliakoff 

The CUDA 11 which works with clang 10.0.0: 
Cuda compilation tools, release 11.0, V11.0.167

**Comment by scothalverson** [comment]
> If I understand this correct: This is NOT a problem in Kokkos, we support any (and test a few) combinations of clang and CUDA with clang as the device compiler (i.e. clang++ -x cuda, where we add the -x cuda internally). But spack apparently has its ownd compatibility list which is independent of Kokkos and which is just the conflict list of using clang as the host compiler for nvcc - not what you are trying to do. That conflict list for using clang as the host compiler is correct from spack but there is a different conflict list when using clang as the main compiler. We do not enforce that actually. That means if you compile for example with clang 8 and CUDA 10.2 you will just get cryptic errors. This is a change one needs to make in spack itself.

You're correct that this is not an issue with Kokkos.  Its definitely a Spack issue.  


I realize I'm likely misunderstanding two things that might cause this to make more sense:

1) the syntax of constraints in Spack:  
`conflicts('%clang@:3.2,9:', when='+cuda ^cuda@10.2.89' + arch_platform)` - If I'm understanding this correctly now, this is saying there is a conflict if (clang version <= 3.2 or clang version >= 9) and cuda version == 10.2.89 ?

2) The compatibility list that Nvidia provides for Clang as the host compiler is different than the list of CUDA versions a particular version of Clang can rely on for `-x cuda` device compilation.

And to follow from that, Spack is enforcing requirements based on NVCC being the device compiler, even when we want to use Clang as the device compiler.

**Comment by svenevs** [comment]
@scothalverson yes you got it

>  If I'm understanding this correctly now, this is saying there is a conflict if (clang version <= 3.2 or clang version >= 9) and cuda version == 10.2.89 ?

Yes, I think @adamjstewart originally created this "hack" (clever workaround based on constraints of other parts of spack). It's a bit confusing, but all of those constraints are encoding min / max versions of clang / gcc / icc / etc as declared by NVIDIA (what `nvcc` is tested against wrapping).

> The compatibility list that Nvidia provides for Clang as the host compiler is different than the list of CUDA versions a particular version of Clang can rely on for -x cuda device compilation.

Exactly. Sorry for not explaining more, the clang / cuda stuff is a bit complicated. LLVM decides what versions of CUDA they support, which they for all intents and purposes maintain independently of NVIDIA meaning we would want to track all of that separately. In reality it's going to be NVIDIA releases next CUDA version, and usually shortly after it will show up in LLVM head depending on the release. For example patch releases are quick, but if it's a major release with a new architecture they may support it but not optimize for it.

I'm not fully up to speed on all of that (some corrections may be needed...), but for spack it means

1. We need a way to say "clang is cuda compiler not nvcc".
2. Constrain cuda versions based on clang version when (1) is true

I don't think there are currently any concrete plans for clang as a cuda compiler, but maybe if it's desirable there is a way for it to be hacked in? The flags change a little bit, but if the package you want to build supports clang as CUDA then their build system should "just work" -- in other words, not too much effort for spack (?)

Unfortunately I don't really have any good advice on how to achieve this. I think we can make the `CudaPackage` have a variant to say "use clang", but that would show up everywhere and give users the impression it works. If a package doesn't actually account for clang as cuda compiler, there will be many errors or worse nvcc may somehow get picked up depending on the system and just get used anyway. So then an alternative would be to have each package introduce a variable such as `supports_clang_as_cudacc = True`, which we can look for in the metaclasses to conditionally add the variant? I've thought about it on and off for a while and don't really like either option, one is problematic at scale and one doesn't scale well...

I was kind of under the impression that the new concretizer will give us better options (but don't know what those would be), something about how compilers are represented being completely redone? Depending on what the best long term plan, maybe we just hack somehow with a TODO and revert later.

**Comment by ax3l** [comment]
Just to clarify: only when you declare your package as `CudaPackage` will we pull this dependency list.

Just let us add a `cudacxx` variant to the `CudaPackage`. I did that before for PIConGPU:
https://github.com/ComputationalRadiationPhysics/spack-repo/blob/348e1443150d7134937746b33de3531db31dc340/packages/picongpu/package.py#L56-L59

I'll push a PR after CUDA 11.1.0 is in (#19036).

Update: work started in #19038, please feel free to chime in and test :)
