### ISSUE TITLE
namd: all fetchers fail

### ISSUE THREAD

**Issue by vkallesh** [LLNL/spack#18043]
### Steps to reproduce the issue

```console
1. Download latest spack recipe - 'git rev-parse HEAD' value as on today - ae23f33a31bfbb8b83ba6c73d97635de1ebd75ec
2. spack install namd using following command - spack install namd
	a. This would pick namd version 2.13 for installation
	b. Issue prevailed on version
...
```

### Error Message

```console
$ spack --debug --stacktrace install namd
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

[namd_stacktrace.log](https://github.com/spack/spack/files/5067386/namd_stacktrace.log)
[spack_debug_report.log](https://github.com/spack/spack/files/5067387/spack_debug_report.log)

**Comment by vkallesh** [comment]
Error message:
==> Error: FetchError: All fetchers failed for spack-stage-namd-2.13-rvkidyrofl2uj2w5be3tfeyrznbgnv2w

/home/spack/spack/lib/spack/spack/package.py:1246, in do_fetch:
       1243                raise FetchError("Will not fetch %s" %
       1244                                 self.spec.format('{name}{@version}'), ck_msg)
       1245

**Comment by s-sajid-ali** [comment]
You'd have to manually download the `namd` source code from [here](https://www.ks.uiuc.edu/Development/Download/download.cgi?PackageName=NAMD) by registering for an account (it's free). Then in the directory where the file is located, you can do `spack install namd@downloaded_version`. 

PS: `spack` can fetch the in-development version directly from their git repo.

**Comment by adamjstewart** [comment]
It sounds like this issue has been resolved. If someone wants to contact the NAMD developers and ask if they can release NAMD without requiring login, we can do that.

**Comment by s-sajid-ali** [comment]
They do have a git repo [here](https://charm.cs.illinois.edu/gerrit/gitweb?p=namd.git) which is used to fetch the develop version from spack. Also, they state on their website : ` The Charm++ repository moved to GitHub in May 2019, NAMD is expected to follow. `.

**Comment by adamjstewart** [comment]
In that case, hopefully this won't be an issue in the future.

@tldahlgren is there a way to make this more clear in packages that must be downloaded manually?

**Comment by tldahlgren** [comment]
> In that case, hopefully this won't be an issue in the future.
> 
> @tldahlgren is there a way to make this more clear in packages that must be downloaded manually?

@adamjstewart @tgamblin  Is it safe to assume any package that has `manual_download = True` *must* be manually downloaded?
