### ISSUE TITLE
Installation issue: rocm-opencl

### ISSUE THREAD

**Issue by SirRujak** [LLNL/spack#18073]
### Steps to reproduce the issue

```console
$ spack install rocm-opencl
$ clinfo
ERROR: clGetPlatformIDs(-1001)

```

### Information on your system

* **Spack:** 0.15.4-521-1d152a44f
* **Python:** 3.7.8
* **Platform:** linux-solus4-zen2

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/5076810/spack-build-env.txt)
* [spack-build-out.txt](https://github.com/spack/spack/files/5076811/spack-build-out.txt)

@arjun-raj-kuppala @srekolam 

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

### Extra Information
I've been watching the recently merged pull request https://github.com/spack/spack/pull/17422 to try and  get OpenCL running on my system. The installation step of the rocm-opencl package completes properly but clinfo crashes for a couple reasons.

First, it appears that the OpenCL vendors path is hard coded into the rocm build as "/etc/OpenCL/vendors/" which seems to be a general issue as noted in https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/pull/111. Using the suggestion in https://github.com/RadeonOpenCompute/ROCm/issues/511#issuecomment-415609121 I was able to create the amdocl64.icd using the libamdocl64.so file in the rocm-opencl lib directory. I am not yet familiar enough with Spack to understand the proper way to fix such a path issue. I have seen the RPATH feature but still couldn't quite come up with how to go about it properly. 

Second, even after hackily making it find the proper vendors files it still crashes out due to a necessary runtime dependency on comgr. Changing `depends_on('comgr@3.5.0', type='build', when='@3.5.0')` to `depends_on('comgr@3.5.0', type=('build', 'run'), when='@3.5.0')` in the rocm-opencl package.yaml allows clinfo to run and correctly identifies my RX480 as a OpenCL device. The clinfo output is here:

<details>
  <summary>clinfo output</summary>

  ```
$ clinfo
Number of platforms:				 1
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 2.0 AMD-APP (3137.0)
  Platform Name:				 AMD Accelerated Parallel Processing
  Platform Vendor:				 Advanced Micro Devices, Inc.
  Platform Extensions:				 cl_khr_icd cl_amd_event_callback 


  Platform Name:				 AMD Accelerated Parallel Processing
Number of devices:				 1
  Device Type:					 CL_DEVICE_TYPE_GPU
  Vendor ID:					 1002h
  Board name:					 Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
  Device Topology:				 PCI[ B#45, D#0, F#0 ]
  Max compute units:				 36
  Max work items dimensions:			 3
    Max work items[0]:				 1024
    Max work items[1]:				 1024
    Max work items[2]:				 1024
  Max work group size:				 256
  Preferred vector width char:			 4
  Preferred vector width short:			 2
  Preferred vector width int:			 1
  Preferred vector width long:			 1
  Preferred vector width float:			 1
  Preferred vector width double:		 1
  Native vector width char:			 4
  Native vector width short:			 2
  Native vector width int:			 1
  Native vector width long:			 1
  Native vector width float:			 1
  Native vector width double:			 1
  Max clock frequency:				 1266Mhz
  Address bits:					 64
  Max memory allocation:			 7301444403
  Image support:				 No
  Max size of kernel argument:			 1024
  Alignment (bits) of base address:		 1024
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 No
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 16384
  Global memory size:				 8589934592
  Constant buffer size:				 7301444403
  Max number of constant args:			 8
  Local memory type:				 Scratchpad
  Local memory size:				 65536
  Max pipe arguments:				 16
  Max pipe active reservations:			 16
  Max pipe packet size:				 3006477107
  Max global variable size:			 7301444403
  Max global variable preferred total size:	 8589934592
  Max read/write image args:			 0
  Max on device events:				 1024
  Queue on device max size:			 8388608
  Max on device queues:				 1
  Queue on device preferred size:		 262144
  SVM capabilities:				 
    Coarse grain buffer:			 Yes
    Fine grain buffer:				 Yes
    Fine grain system:				 No
    Atomics:					 No
  Preferred platform atomic alignment:		 0
  Preferred global atomic alignment:		 0
  Preferred local atomic alignment:		 0
  Kernel Preferred work group size multiple:	 64
  Error correction support:			 0
  Unified memory for Host and Device:		 0
  Profiling timer resolution:			 1
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 No
  Queue on Host properties:				 
    Out-of-Order:				 No
    Profiling :					 Yes
  Queue on Device properties:				 
    Out-of-Order:				 Yes
    Profiling :					 Yes
  Platform ID:					 0x7fae78e09c90
  Name:						 gfx803
  Vendor:					 Advanced Micro Devices, Inc.
  Device OpenCL C version:			 OpenCL C 2.0 
  Driver version:				 3137.0 (HSA1.1,LC)
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 1.2 
  Extensions:					 cl_khr_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_media_ops cl_amd_media_ops2 cl_khr_image2d_from_buffer cl_khr_subgroups cl_khr_depth_images cl_amd_copy_buffer_p2p cl_amd_assembly_program 

```
</details>

This is at the point where things really stopped working though. The build is missing image support which makes testing it difficult. At the very least running darktable-cltest while in a Spack environment where rocm-opencl is installed appears to miss the GPU altogether as seen here:

<details>
  <summary>darktable-cltest output</summary>

```

 $ darktable-cltest 
0.019987 [opencl_init] opencl related configuration options:
0.019997 [opencl_init] 
0.019999 [opencl_init] opencl: 1
0.020000 [opencl_init] opencl_scheduling_profile: 'default'
0.020002 [opencl_init] opencl_library: ''
0.020008 [opencl_init] opencl_memory_requirement: 768
0.020013 [opencl_init] opencl_memory_headroom: 400
0.020015 [opencl_init] opencl_device_priority: '*/!0,*/*/*/!0,*'
0.020017 [opencl_init] opencl_mandatory_timeout: 200
0.020019 [opencl_init] opencl_size_roundup: 16
0.020021 [opencl_init] opencl_async_pixelpipe: 0
0.020022 [opencl_init] opencl_synch_cache: active module
0.020024 [opencl_init] opencl_number_event_handles: 25
0.020026 [opencl_init] opencl_micro_nap: 1000
0.020028 [opencl_init] opencl_use_pinned_memory: 0
0.020030 [opencl_init] opencl_use_cpu_devices: 0
0.020031 [opencl_init] opencl_avoid_atomics: 0
0.020033 [opencl_init] 
0.023562 [opencl_init] found opencl runtime library 'libOpenCL'
0.023591 [opencl_init] opencl library 'libOpenCL' found on your system and loaded
0.023595 [opencl_init] found 1 platform
0.042325 [opencl_init] found 1 device
0.042358 [opencl_init] discarding CPU device 0 `pthread-AMD Ryzen 9 3900X 12-Core Processor'.
0.042364 [opencl_init] no suitable devices found.
0.042367 [opencl_init] FINALLY: opencl is NOT AVAILABLE on this system.
0.042369 [opencl_init] initial status of opencl enabled flag is OFF.

```
</details>

Attempting to run Blender from the command prompt seems to get it stuck in a never ending loop with one thread running at 100%. Unfortunately the strace for Blender wasn't particularly helpful due to the large number of commands it was running. The last application I tried was plaidml which, similar to darktable, was able to find my CPU somehow but appeared to never load the configuration for the GPU. With strace I was able to find something that possibly is causing the issue though. It appears that the rocm-opencl build creates both a lib and a lib64 folder and both contain a libOpenCL.so file. Plaidml appears to find the lib64 version first as seen here 

`openat(AT_FDCWD, "/mnt/fe9dcbea-9428-40db-8650-4a941be01d52/Documents/spack/var/spack/environments/cltest/.spack-env/view/lib64/libOpenCL.so", O_RDONLY|O_CLOEXEC) = 4`

I am guessing this is the problem because only the lib folder contains libamdocl64.so which I believe means that it never tries to pull in the vendor file but I am a bit out of my depth here.

Any assistance would be greatly appreciated, I understand the rocm components just got pulled in and issues were to be expected, I have just hit the end of my knowledge and am not quite sure how to progress from here.

**Comment by srekolam** [comment]
@SirRujak  ,  I have got your message and we will look into it.

**Comment by srekolam** [comment]
closing this as this was fixed some time ago
