### ISSUE TITLE
PIpelines: Create downstream rebuild jobs ONLY when spec needs it

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#18121]
Can we consider moving the `spack buildcache check` logic out of the child jobs and into `spack ci generate` or equivalent? Why should we stage out potentially hundreds of CI jobs when we know up-front whether a rebuild of the spec is necessary?

Let's say someone changes `adios2` package such that *only* `adios2` needs to be updated at the build cache. We have ~240 specs part of `E4S environment` (counting dependencies). Current behavior dictates that that we stage out ~240 downstream CI jobs, one for each spec. One of the first tasks in each of these ~240 downstream jobs is to determine whether the spec is up-to-date at the build cache, and to shutdown if it is. Why should we do this when we have all the knowledge we need *up front* to know which specs need to be rebuilt?

@scottwittenburg @opadron @tgamblin @shahzebsiddiqui @becker33

**Comment by shahzebsiddiqui** [comment]
I am in favor of this feature. I like the `spack buildcache check` which should check all hash for for concretize spec in environment with hash in buildcache.

This command should be invoked as part of `spack ci generate` so that downstream job are triggered only if a subdag has a hash mismatch

**Comment by scottwittenburg** [comment]
Thanks for writing this up as an issue @eugeneswalker, this is indeed on our list of things to tackle.  So far our short-hand terminology for it is "DAG-pruning".

**Comment by shahzebsiddiqui** [comment]
this feature is going to be a huge cost saver and compute cycles for site facility.

**Comment by shahzebsiddiqui** [comment]
Hey @tgamblin any idea if this issue will be part of the next release or subsequent one, this feature can certainly save up alot of cpu cycles as our pipeline gets bigger we are just wasting jobs and queue time.

**Comment by scottwittenburg** [comment]
This feature is in spack `develop` now (as of #20435), but I didn't add it to the release project for `0.16.1`, so I'm not sure if it's in there or not.

Now during pipeline generation `spack ci generate` check all specs against configured mirrors for a full hash match, even if you pass `--no-prune-dag` (in which case it writes a variable with each generated job indicating whether the spec needs to be rebuilt or not).  To speed up pipeline generation, make sure your buildcache indices are updated, and then use `spack ci generate --check-index-only`.
