### ISSUE TITLE
bzip2 required but can't be spack installed & is not listed in prerequisites

### ISSUE THREAD

**Issue by sjpb** [LLNL/spack#18152]
### Steps to reproduce the issue

```console
spack install gcc@9.3.0
<snip>
==> Installing gmp
==> No binary for gmp found: installing from source
tar (child): lbzip2: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
/usr/bin/tar: Child returned status 2
/usr/bin/tar: Error is not recoverable: exiting now
==> Error: ProcessError: Command exited with status 2:
    '/usr/bin/tar' '-oxf' '/tmp/centos/spack-stage/spack-stage-gmp-6.1.2-7dgljbuxqrigl347avxrml4xbkgs5ymc/gmp-6.1.2.tar.bz2'
==> Warning: Skipping build of mpfr since gmp failed
==> Warning: Skipping build of gcc since mpfr failed
==> Warning: Skipping build of mpc since mpfr failed
==> Warning: Skipping build of isl since gmp failed
==> Error: Installation of gcc failed.  Review log for details
```

On the slack channel I was told this needed `bzip2` installing. This doesn't seem to be available via spack, which is problematic for unprivileged users. It's also not listed in the [prerequisites](https://spack.readthedocs.io/en/latest/getting_started.html#prerequisites).

### Information on your system

* **Spack:** 0.15.4-592-319d160
* **Python:** 3.8.3
* **Platform:** linux-centos7-cascadelake

### Additional information

- [x ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x ] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by sjpb** [comment]
To be fair googling the `lbzip2: Cannot exec: No such file or directory` bit finds the fixes, I was a bit confused by what the actual error was here, having seen spack unpack archives ok before.

**Comment by michaelkuhn** [comment]
The same is true for xz and some other formats, which we should probably list in the prerequisites.

Spack has packages for bzip2 and lbzip2, though (`spack list bz`). Are they missing from your installation?

**Comment by sjpb** [comment]
Hmm not sure why I though spack didn't have bzip2, sorry. So really this whole issue can probably be closed (there's other things like "patch" not listed in prereqs but if they can be installed via spack I find that ok personally).

**Comment by michaelkuhn** [comment]
I guess it still makes sense to have them listed somewhere. I have updated the linked PR to also include `patch` (I have personally run into this problem a few times already in minimal environments).
