### ISSUE TITLE
Spack doesn't properly read OS descriptor

### ISSUE THREAD

**Issue by ashkan2200** [LLNL/spack#1815]
Hi,
I just installed Os Sierra and now my spack doesn't understand my installed packages. Also 
spack reindex failed.
How do I fix this?

**Comment by tgamblin** [comment]
It doesn't understand them or it doesn't build against them?  Spack won't build packages from a new OS version (sierra) against an old one (el capitan), as they're not guaranteed to be ABI compatible.

**Comment by tgamblin** [comment]
Also, `spack reindex` is being worked on right now.

**Comment by ashkan2200** [comment]
When I do `spack find` I get something like this

    -- darwin-None-x86_64 / clang@7.0.2-apple -----------------------
    environment-modules@3.2.10  tcl@8.6.5  zlib@1.2.8
    
    -- darwin-None-x86_64 / gcc@4.2.1 -------------------------------
    gcc@6.1.0  gmp@6.1.0  isl@0.14  libsigsegv@2.10  m4@1.4.17  mpc@1.0.3  mpfr@3.1.4

and I can't load them into my environment

**Comment by tgamblin** [comment]
Ok that's a bug -- Spack should properly read the old OS descriptor.  Can you attach the output of `spack debug create-db-tarball`?

**Comment by tgamblin** [comment]
@becker33

**Comment by ashkan2200** [comment]
I have uploaded the tarball [here](https://cl.ly/1D0W0g2s3n3V)

**Comment by davydden** [comment]
do you use the latest `develop`?  Specifically, after this PR is merged https://github.com/LLNL/spack/pull/1811 ?

you will need to wipe your installation completely and start anew. But there is nothing to fear, see https://groups.google.com/d/topic/spack/39--LYqIgpc/discussion

**Comment by ashkan2200** [comment]
@davydden I have the latest `develop` . The issue is not that spack doesn't recognise macOS sierra, it is that it doesn't know that I compiled my softwares on Yosemite.

**Comment by davydden** [comment]
oh, i see.

**Comment by adamjstewart** [comment]
This problem is not Mac-specific and has occurred for me in the past when updating Linux to the latest version, or just when updating Spack after a spec-change. Removing the macOS label...

**Comment by becker33** [comment]
Will this issue be resolved when #2261 is merged, or is it a separate bug? @adamjstewart and @ashkan2200 can you check whether that PR resolves your issues?

**Comment by xjrc** [comment]
These problems look very similar to those in  issue #2249.  As such, I believe that they should be fixed by #2261, but it wouldn't hurt to double check!

**Comment by ashkan2200** [comment]
I'll check and report back here

**Comment by tgamblin** [comment]
@ashkan2200: #2249 is merged.  Can you verify that this fixes your issue?

This won't cause Spack to build against your old packages automatically (though you could force it with `spack install package ^/hash`, but it should make the old packages appear properly in `spack find`.

**Comment by tgamblin** [comment]
@ashkan2200: if this is still a problem feel free to reopen.
