### ISSUE TITLE
HDF5 CMake Package support

### ISSUE THREAD

**Issue by azukaitis** [LLNL/spack#18176]
I do not see the hdf5-config.cmake file in any of my hdf5 installs.   Can we please get proper CMake installs of this package?

**Comment by adamjstewart** [comment]
@lrknox is the maintainer of our `hdf5` package, maybe he can comment. Otherwise, PRs are always welcome! Basically, you would need to switch the base class from `AutotoolsPackage` to `CMakePackage` and replace `configure_args` with `cmake_args`. If you want to take a stab at this, I can help you out.

**Comment by sethrj** [comment]
Related: https://github.com/spack/spack/issues/15896 . HDF5 is one of those packages that has changed their build system from autotools to cmake over the lifetime of the spack recipe.

Side note: if you're interested in the modern cmake targets provided by the CMake-installed HDF5, as of CMake 3.19  you will be able to get the targets with the FindHDF5  script (see https://gitlab.kitware.com/cmake/cmake/-/merge_requests/5129). That script can be backported to older versions of cmake if you need it inside the context of a downstream cmake project.

**Comment by adamjstewart** [comment]
@sethrj I was thinking the same thing, but it looks like the oldest version of HDF5 in Spack (1.8.10) actually supports CMake, so there's no reason we can't switch.

**Comment by skosukhin** [comment]
We will lose Libtool files if we switch to CMake. I mean those `*.la` files in the `prefix/lib` that are implicitly used when we build dependent Libtool-based packages, e.g. NetCDF. It will also affect cases when we build a Libtool-based package outside of Spack and want to use Spack's installation of HDF5. I'm not saying that it will break things. It just might.

**Comment by adamjstewart** [comment]
@skosukhin would that problem be solved if we also switch NetCDF to CMake? At some point in the distant future we are planning to add Windows support, in which case CMake will be necessary.

**Comment by skosukhin** [comment]
I just wanted to highlight a possible side effect. It shouldn't stop anybody from switching to CMake. If we get problems with NetCDF, we will find a way to solve them.

**Comment by lrknox** [comment]
Pull request to build HDF5 with CMake:  https://github.com/spack/spack/pull/18937.  Please try with your package and report results or issues.
