### ISSUE TITLE
problem to install netcdf-c, using hdf5 built with szip.

### ISSUE THREAD

**Issue by weiyu11** [LLNL/spack#18180]
Dear Sir/Madam, 

I am using spack to install the netcdf-c library.

spack install szip target=x86_64 %intel@18.0.5
spack install hdf5 +cxx +fortran +hl+mpi +szip +threadsafe target=x86_64 ^intel-mpi %intel@18.0.5

The above two works fine. I have error when install the netcdf-c. 
spack install netcdf-c@4.7.2 +mpi+parallel-netcdf target=x86_64 ^intel-mpi ^hdf5 %intel@18.0.5

configure: error: libhdf5 installed with szip support, but cannot find or link to the szip library

The szip library has been installed successfully. I do not know why it could not find the path, and how could I add it. 

Thank you very  much! 
Wei Yu

**Comment by adamjstewart** [comment]
@skosukhin @WardF

**Comment by weiyu11** [comment]
The error is gone after I updated to the latest git version.
