### ISSUE TITLE
build fail: binutils@2.33.1 on rhel8 - no makeinfo

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#18289]
`binutils@2.33.1 %gcc@8.3.1` is failing using `spack@develop` (26-Aug-2020, 20d37afafa3be3f9b6c3388e22f813261d4c3fec) on `RHEL8` for `x86_64`

Looks like the dependency on `texinfo` (which provides `makeinfo`) extends to 2.33.1 as well as 2.34. The package.py makes this dependency explicit for 2.34. but not 2.33.1. The build proceeds without problem when `texinfo` is added as an explicit dependency for 2.33.1.

Concrete spec: [binutils-422ehg.yml.txt](https://github.com/spack/spack/files/5130808/binutils-422ehg.yml.txt)
Build log: [binutils-build-out.txt](https://github.com/spack/spack/files/5130801/binutils-build-out.txt)

```
$> spack install -f ./binutils-422ehg.yml
...
==> Installing binutils
==> Using cached archive: /spack/var/spack/cache/_source-cache/archive/0c/0cb4843da15a65a953907c96bad658283f3c4419d6bcc56bf2789db16306adb2.tar.bz2
==> binutils: Executing phase: 'autoreconf'
==> binutils: Executing phase: 'configure'
==> binutils: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

3 warnings found in build log:
     1338    checking target system type... if [ x"-fpic" != x ]; then \
     1339      /spack/lib/spack/env/gcc/gcc -c -DHAVE_CONFIG_H -g -O2  -I. -I./../include  -W -Wall -Wwrite-strings -Wc++-compat -Wstrict-prototypes -Wshadow=local -pedantic
             -D_GNU_SOURCE -fpic ./fibheap.c -o pic/fibheap.o; \
     1340    else true; fi
     1341    x86_64-pc-linux-gnu
     1342    checking for x86_64-pc-linux-gnu-gcc... /spack/lib/spack/env/gcc/gcc
     1343    ./dyn-string.c: In function 'dyn_string_insert_cstr':
  >> 1344    ./dyn-string.c:280:3: warning: 'strncpy' output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
     1345       strncpy (dest->s + pos, src, length);
     1346       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     1347    ./dyn-string.c:272:16: note: length computed here
     1348       int length = strlen (src);
     1349                    ^~~~~~~~~~~~
     1350    if [ x"" != x ]; then \

     ...

     1390    else true; fi
     1391    /spack/lib/spack/env/gcc/gcc -c -DHAVE_CONFIG_H -g -O2  -I. -I./../include  -W -Wall -Wwrite-strings -Wc++-compat -Wstrict-prototypes -Wshadow=local -pedantic  -D
             _GNU_SOURCE ./cp-demangle.c -o cp-demangle.o
     1392    if [ x"-fpic" != x ]; then \
     1393      /spack/lib/spack/env/gcc/gcc -c -DHAVE_CONFIG_H -g -O2  -I. -I./../include  -W -Wall -Wwrite-strings -Wc++-compat -Wstrict-prototypes -Wshadow=local -pedantic
             -D_GNU_SOURCE -fpic ./getruntime.c -o pic/getruntime.o; \
     1394    else true; fi
     1395    ./dyn-string.c: In function 'dyn_string_insert_cstr':
  >> 1396    ./dyn-string.c:280:3: warning: 'strncpy' output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
     1397       strncpy (dest->s + pos, src, length);
     1398       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     1399    ./dyn-string.c:272:16: note: length computed here
     1400       int length = strlen (src);
     1401                    ^~~~~~~~~~~~
     1402    yes

     ...

     2229    else \
     2230      rc=$?; \
     2231      $restore $backupdir/* `echo "./bfd.info" | sed 's|[^/]*$||'`; \
     2232    fi; \
     2233    rm -rf $backupdir; exit $rc
     2234    /tmp/root/spack-stage/spack-stage-binutils-2.33.1-422ehgikkmt4cghrtx5bracwl34otohy/spack-src/missing: line 81: makeinfo: command not found
  >> 2235    WARNING: 'makeinfo' is missing on your system.
     2236             You should only need it if you modified a '.texi' file, or
     2237             any other file indirectly affecting the aspect of the manual.
     2238             You might want to install the Texinfo package:
     2239             <http://www.gnu.org/software/texinfo/>
     2240             The spurious makeinfo call might also be the consequence of
     2241             using a buggy 'make' (AIX, DU, IRIX), in which case you might

See build log for details:
  /tmp/root/spack-stage/spack-stage-binutils-2.33.1-422ehgikkmt4cghrtx5bracwl34otohy/spack-build-out.txt
```

@michaelkuhn @mathsen @mwkrentel

**Comment by mwkrentel** [comment]
I tried this on a RH 8.x system without makeinfo installed, and I get
different results from you.

For me, `spack install binutils -nls` builds cleanly without texinfo
for 2.33.1, fails for 2.34 (without texinfo) and again builds cleanly
with 2.35.  This is consistent with the bug report from the binutils
`package.py`.

https://sourceware.org/bugzilla/show_bug.cgi?id=25491

I don't know how to account for your results.  Perhaps start over from
scratch with a minimal spack environment.  I don't understand the
difference, but I do believe it's something different from 2.34 vs 2.35 or
2.33.1.

**Comment by eugeneswalker** [comment]
I have replicated this many times, from scratch. I'm using Red Hat's UBI 8 image, cloning Spack and starting from scratch each time. Please see the link below for a short video showing the whole process by which the issue is consistently reproduced. The videos shows what happens when trying to install:
* `binutils@2.35~nls`
* `binutils@2.33.1~nls`

https://asciinema.org/a/356330

Perhaps Red Hat 8's yum repository is in fact providing a buggy version of `make` as suggested by the error message:

```
...
  >> 2235    WARNING: 'makeinfo' is missing on your system.
     2236             You should only need it if you modified a '.texi' file, or
     2237             any other file indirectly affecting the aspect of the manual.
     2238             You might want to install the Texinfo package:
     2239             <http://www.gnu.org/software/texinfo/>
     2240             The spurious makeinfo call might also be the consequence of
     2241             using a buggy 'make' (AIX, DU, IRIX), in which case you might
```

**Comment by mwkrentel** [comment]
@eugeneswalker  Does your system have the `cmp` program installed?
It's hard to believe that cmp doesn't exist, but maybe.  This is from diffutils rpm.
And note: cmp needs to exist on whatever docker machine that spack is actually running on.

Is this a DOE machine?  I have access to many DOE machines, although I
don't really use docker.

**Comment by eugeneswalker** [comment]
> @eugeneswalker Does your system have the `cmp` program installed?
> It's hard to believe that cmp doesn't exist, but maybe. This is from diffutils rpm.
> And note: cmp needs to exist on whatever docker machine that spack is actually running on.

We are observing the problem inside our RHEL8 container image which we use for CI. The image is on Docker Hub as `ecpe4s/rhel8-runner-x86_64:2020-08-01`. *It does* have `cmp` from `diffutils`. What made you curious about this?

**Comment by mwkrentel** [comment]
Your build log says that `cmp` doesn't exist.

```
/bin/sh ./../../move-if-change linker.tmp linker.texi
./../../move-if-change: line 68: cmp: command not found
/bin/sh ./../../move-if-change mmo.tmp mmo.texi
./../../move-if-change: line 68: cmp: command not found
./../../move-if-change: line 68: cmp: command not found
```

I think what's happening here is: somehow at a critical point when
spack runs this, the `cmp` command isn't available.  This causes the
`move-if-change` script to fail, this causes the time stamps on the
doc and `texi` files to be wrong, this tells `make` that the doc files
need to be rebuilt, `makeinfo` doesn't exist, so the build fails.

It would be cleaner for binutils to test in configure that makeinfo
doesn't exist (it does), pass that into the Makefiles (it doesn't) and
then not even run the docs targets.  Instead, it always runs the docs
targets but uses the time stamps to determine whether to rebuild the
docs (and thus whether makeinfo is needed).  The warning from the
`missing` script hints at this.

```
WARNING: 'makeinfo' is missing on your system.
         You should only need it if you modified a '.texi' file, or
         any other file indirectly affecting the aspect of the manual.
```

Here's an experiment to confirm this.  Edit the binutils `package.py`
file to remove the texinfo dependency and add instead:

```
depends_on('diffutils', type='build')
```

If that works, then that pretty much confirms my theory.  Btw, if you
run spack install at `-j 1`, it makes it easier to see cause and
effect in the build log.

**Comment by eugeneswalker** [comment]
> Here's an experiment to confirm this. Edit the binutils `package.py`
> file to remove the texinfo dependency and add instead:
> 
> ```
> depends_on('diffutils', type='build')
> ```

Yes. That works! Thank you for catching that. I should have been more diligent reviewing the full log.

Since the build system relies on `cmp`, the right thing to do seems to be, to add `diffutils` as an explicit build dependency (regardless of platform). If there are no objections, we will do this PR: https://github.com/spack/spack/pull/18361

**Comment by mwkrentel** [comment]
@eugeneswalker I don't really run docker (not yet), but I'm curious,

How can a linux system not have cmp or diff?
Is this common on docker, something very minimal?
Is diffutils really optional in RH 8.x?

**Comment by eugeneswalker** [comment]
its Red Hat’s Universal BASE Image (UBI8) and yea it is super barebones. Super small. Meant to build on top of.

**Comment by mwkrentel** [comment]
Ok, thanks !
