### ISSUE TITLE
Installation issue: py-lxml doesn't use the spack libxslt and libexslt libraries

### ISSUE THREAD

**Issue by ajw1980** [LLNL/spack#18293]
It looks like py-lxml should have AUTO_RPATH set to true. Otherwise it picks up the OS versions of libxslt instead of the spack built versions. I added this to the package.py and the library dependencies were correct:

```
    def setup_build_environment(self, env):
        env.set('AUTO_RPATH', 'true')
```

**Comment by adamjstewart** [comment]
Want to submit a PR?
