### ISSUE TITLE
Hash error when trying to install or activate an environment

### ISSUE THREAD

**Issue by bvanessen** [LLNL/spack#18338]
Updated to spack to v0.15. Rewrote the environment to comply to the new format.  Tried to reinstall the environment and it fails part way through the installation of the environment.  At that point it also fails to activate the environment. 

### Steps to reproduce the issue

```console
./scripts/install_lbann.sh -d
spack env create lbann-dev-power9le /tmp/tmp.sNWlgHKVtI
==> Updating view at /autofs/nccs-svm1_home1/vanessen/spack.git/var/spack/environments/lbann-dev-power9le/.spack-env/view
==> Created environment 'lbann-dev-power9le' in /autofs/nccs-svm1_home1/vanessen/spack.git/var/spack/environments/lbann-dev-power9le
==> You can activate this environment with:
==>   spack env activate lbann-dev-power9le
spack env activate -p lbann-dev-power9le
spack install
<some packages install>
...
==> Installing py-pytest
==> No binary for py-pytest found: installing from source
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/1d/1d122e8be54d1a709e56f82e2d85dcba3018313d64647f38a91aec88c239b600.tar.gz
######################################################################## 100.0%
==> py-pytest: Executing phase: 'build'
==> py-pytest: Executing phase: 'install'
[+] /ccs/home/vanessen/spack_installed_packages/opt/spack/linux-rhel7-power9le/gcc-8.1.1/py-pytest-5.3.4-ln2l2mdp4jvtfctmfalqlzcjkomctj62
==> gcc@8.1.1 : has external module in ['gcc/8.1.1']
==> Error: '3easygztiqbtrszh4rxogt6wb5r7nvra'...
```

### Error Message

```console
vanessen@login4 [lbann.git] %> spack env activate lbann-dev-power9le
==> Error: '3easygztiqbtrszh4rxogt6wb5r7nvra'
vanessen@login4 [lbann.git] %> spack -d env activate lbann-dev-power9le
==> [2020-08-27-18:17:23.300408] Imported env from built-in commands
==> [2020-08-27-18:17:23.304057] Imported env from built-in commands
==> [2020-08-27-18:17:23.305158] Reading config file /autofs/nccs-svm1_home1/vanessen/spack.git/etc/spack/defaults/config.yaml
==> [2020-08-27-18:17:23.338516] Reading config file /ccs/home/vanessen/.spack/config.yaml
==> [2020-08-27-18:17:23.840768] Using environmennt 'lbann-dev-power9le'
==> [2020-08-27-18:17:23.841232] Reading config file /autofs/nccs-svm1_home1/vanessen/spack.git/var/spack/environments/lbann-dev-power9le/spack.yaml
==> [2020-08-27-18:17:24.030551] DATABASE LOCK TIMEOUT: 3s
==> [2020-08-27-18:17:24.030634] PACKAGE LOCK TIMEOUT: No timeout
Traceback (most recent call last):
  File "/ccs/home/vanessen/spack.git/bin/spack", line 64, in <module>
    sys.exit(spack.main.main())
  File "/autofs/nccs-svm1_home1/vanessen/spack.git/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/autofs/nccs-svm1_home1/vanessen/spack.git/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/autofs/nccs-svm1_home1/vanessen/spack.git/lib/spack/spack/cmd/env.py", line 509, in env
    action(args)
  File "/autofs/nccs-svm1_home1/vanessen/spack.git/lib/spack/spack/cmd/env.py", line 120, in env_activate
    prompt=env_prompt if args.prompt else None
  File "/autofs/nccs-svm1_home1/vanessen/spack.git/lib/spack/spack/environment.py", line 181, in activate
    cmds += env.add_default_view_to_shell(shell)
  File "/autofs/nccs-svm1_home1/vanessen/spack.git/lib/spack/spack/environment.py", line 1198, in add_default_view_to_shell
    mods, errors = self._env_modifications_for_default_view()
  File "/autofs/nccs-svm1_home1/vanessen/spack.git/lib/spack/spack/environment.py", line 1173, in _env_modifications_for_default_view
    for _, spec in self.concretized_specs():
  File "/autofs/nccs-svm1_home1/vanessen/spack.git/lib/spack/spack/environment.py", line 1351, in concretized_specs
    yield (s, self.specs_by_hash[h])
KeyError: '3easygztiqbtrszh4rxogt6wb5r7nvra'
```

### Additional information

- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by tmadlener** [comment]
I am experiencing similar problems. However, in my case the environment has been created with an earlier version of spack (before the update to the new config file format). I am not sure if this information is of any help, but by chance I had an environment activated before updating spack and after updating I can't deactivate that environment any longer (via `spack env deactivate`).

I get a similarly cryptic error message, only the printed hash is different.

**Comment by bvanessen** [comment]
I believe that part of my problem is related to the line that says 

view: true

That is at the end of my spack.yaml file. It is added during the creation of the environment and if I delete it and reconcretize the environment it seems to work. 

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470
---

**Comment by tmadlener** [comment]
It looks like creating a new environment with explicitly disabling the creation of a view also allows me to create, activate and deactivate environments. However, setting `view: false` in the `spack.yaml` file after an environment has been created, concretized and all packages installed with an earlier version of spack has no effect.

The hash that is printed in the error message seems to be the one that belongs to the first package in `spack.lock` that has been installed via spack (i.e. no system packages, even if they appear earlier in the list).

I am not entirely sure on how to best proceed from here, or what information would be the most helpful for the developers. If there is anything that I can do from my side, let me know.

**Comment by bvanessen** [comment]
I did find the problematic has in the lock file as well it is the first one:
```
 "roots": [
  {
   "hash": "3easygztiqbtrszh4rxogt6wb5r7nvra",
   "spec": "aluminum"
  },
```

**Comment by bvanessen** [comment]
It looks like all of the hash values in the lock file do not correspond to the hash values of the installed packages.

**Comment by scheibelp** [comment]
@tmadlener one thing I wanted to check about https://github.com/spack/spack/issues/18338#issuecomment-682408670

@bvanessen reported that this issue comes up if he tries to make an environment from scratch:

```
spack env create <env-name> path/to/spack.yaml
spack env activate <env-name>
spack install
```

Does this also occur for you? Or do activation errors only occur when activating preexisting environments?

**Comment by scheibelp** [comment]
Also @tmadlener is your stack trace the same as https://github.com/spack/spack/issues/18338#issue-687624016, or different?

**Comment by tmadlener** [comment]
Hi @scheibelp, I get the same stack trace as above.

**Comment by alalazo** [comment]
> Updated to spack to v0.15. Rewrote the environment to comply to the new format.

Am I correct that Spack v0.15.X should not be affected by this issue, since the change in `packages.yaml` is only in `develop` at the moment?

**Comment by tmadlener** [comment]
> Am I correct that Spack v0.15.X should not be affected by this issue, since the change in packages.yaml is only in develop at the moment?

Yes, at least for me checking out `0.15.4` (and reverting the changes in the `packages.yaml` config file) allows me to activate and deactivate environments again. Also concretizing environments seems to work again.

**Comment by bvanessen** [comment]
I guess to be precise, I was using head of develop, not the explicit 0.15.4 release.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by scheibelp** [comment]
@tmadlener does removing spaces after module file names and/or enclosing config file values in quotes resolve the issue as mentioned at https://github.com/spack/spack/pull/18368#issuecomment-683580919?

If not, would you be able to post your config file?

@alalazo mentioned being able to fix this issue in the next day so I am assigning him.

**Comment by bvanessen** [comment]
FYI, removing the space after the module file names solved my issues.

Brian C. Van Essen
vanessen1@llnl.gov
(w) 925-422-9300
(c) 925-290-5470

**Comment by alalazo** [comment]
Trying to debug this simple environment:
```yaml
spack:
  specs:
  - openjpeg
  packages:
    cmake:
      externals:
      - spec: cmake@3.18.2
        modules:
        - cmake/1.18.2

  concretization: together
```
which exhibits the same behavior as reported in the description. It seems that doing:
```console
$ spack --env . concretize
```
we read the environment 4 times and we rewrite the `spack.yaml` (so  I think there's a regression on #13546).

**Comment by tmadlener** [comment]
> @bvanessen reported that this issue comes up if he tries to make an environment from scratch:
>```
>spack env create <env-name> path/to/spack.yaml
>spack env activate <env-name>
>spack install
>```
>Does this also occur for you? Or do activation errors only occur when activating preexisting environments?

For me activation errors only occur when I am trying to activate a preexisting environment. Creating one from scratch using the exact same yaml file I used for the original one seems to work just fine.

However, interestingly enough, concretizing the newly created environment yields different hashes for some of the packages. I would have naively have expected that these are stable between spack versions. But maybe that assumption is wrong?

**Comment by alalazo** [comment]
There are further issues reproducible with the environment posted above:
```console
$ spack --env . concretize 
==> Concretized openjpeg
 -   526rapi  openjpeg@2.3.1%gcc@10.1.0 build_type=RelWithDebInfo arch=linux-ubuntu18.04-broadwell
 -   qevuoda      ^cmake@3.18.2%gcc@10.1.0~doc+ncurses+openssl+ownlibs~qt arch=linux-ubuntu18.04-broadwell
 -   kepdmuv      ^zlib@1.2.11%gcc@10.1.0+optimize+pic+shared arch=linux-ubuntu18.04-broadwell

==> Updating view at /home/culpo/tmp/spack-issues/18338/.spack-env/view

$ ls spack.{yaml,lock}
spack.lock  spack.yaml

$ spack --env . concretize 
==> Error: '546hepoobjp5st4xioqkllziy2tbceoz'

$ ls spack.{yaml,lock}
ls: cannot access 'spack.lock': No such file or directory
spack.yaml
```
On a failed command the previously existing lockfile is deleted from disk.

**Comment by alalazo** [comment]
I think I have a full diagnosis. The issue is particularly difficult to trace, since in memory there's no sign of newlines for the `modules` attribute. In fact one can stop and debug and see the following:
```console
>>> self['cmake'].external_modules
['cmake/1.18.2']
```
for both the case where we have a lockfile and where we don't. Anyhow, when we compute the `build_hash` of a spec we pass through the YAML representation of the spec, exactly at this line:

https://github.com/spack/spack/blob/3a5746c6c75d4187e0e6dfc3665a2e34c30de37a/lib/spack/spack/spec.py#L1386-L1387

When we don't have a lockfile present the node dictionary passed to the `syaml.dump` function has a newline in it, which comes from a YAML "comment" in a `CommentedSeq` object (comments are reflected in the dump). When we read from a lockfile the type of the same attribute changes and it's just a Python list, with no attached comments. The new line is thus not present in the dump we use to compute the hash and so the error.

**Comment by alalazo** [comment]
@tmadlener I think I was able to reproduce your problem with this simple environment:
```yaml
spack:
  specs:
  - openjpeg
  packages:
    cmake:
      modules:
        cmake@3.18.2: /cmake/3.18.2
```
and I believe this is a different issue, with a lesser impact than the one reported by @bvanessen . Based on your description above I reproduced by:
```console
$ git checkout releases/latest && cd <env-dir>
$ ls
spack.yaml
$ spack env activate .
$ spack concretize
==> Concretized openjpeg
 -   526rapi  openjpeg@2.3.1%gcc@10.1.0 build_type=RelWithDebInfo arch=linux-ubuntu18.04-broadwell
 -   acoispp      ^cmake@3.18.2%gcc@10.1.0~doc+ncurses+openssl+ownlibs~qt arch=linux-ubuntu18.04-broadwell
 -   kepdmuv      ^zlib@1.2.11%gcc@10.1.0+optimize+pic+shared arch=linux-ubuntu18.04-broadwell

==> Updating view at /home/culpo/tmp/spack-issues/18338/change-release/.spack-env/view
$ cd <spack-dir> && git checkout develop && cd <env-dir>
$ despacktivate
==> Warning: the attribute "modules" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('cmake@3.18.2', '/cmake/3.18.2')])]
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap()]
==> Error: '4mzznkoagjphjoytmpc7kiq2a6ldngjz'
```
If that seems what you are experiencing, it can be solved by:
```console
$ spack env update .
==> Warning: the attribute "modules" in the "packages" section of the configuration has been deprecated [entry=CommentedMap([('cmake@3.18.2', '/cmake/3.18.2')])]
==> Warning: the attribute "paths" in the "packages" section of the configuration has been deprecated [entry=CommentedMap()]
==> The environment "." is going to be updated to the latest schema format.
If the environment is updated, versions of Spack that are older than this version may not be able to read it. Spack stores backups of the updated environment which can be retrieved with "spack env revert"
==> Do you want to proceed? [y/N] y
==> Environment "." has been updated [backup=/home/culpo/tmp/spack-issues/18338/change-release/spack.yaml.bkp]
$ spack concretize -f
==> Concretized openjpeg
 -   526rapi  openjpeg@2.3.1%gcc@10.1.0 build_type=RelWithDebInfo arch=linux-ubuntu18.04-broadwell
 -   chb7asy      ^cmake@3.18.2%gcc@10.1.0~doc+ncurses+openssl+ownlibs~qt arch=linux-ubuntu18.04-broadwell
 -   kepdmuv      ^zlib@1.2.11%gcc@10.1.0+optimize+pic+shared arch=linux-ubuntu18.04-broadwell

==> Updating view at /home/culpo/tmp/spack-issues/18338/change-release/.spack-env/view
```

**Comment by tmadlener** [comment]
Hi @alalazo,

I think I might be experiencing yet another problem...

I am not sure if this really qualifies as the most minimal example, but this is as small as I could get it for now, while still exhibiting the original problem.

For completeness: `spack debug report` yields:
```
* **Spack:** 0.15.4
* **Python:** 3.8.2
* **Platform:** linux-ubuntu20.04-skylake
```

I have then used a stripped down version of my original `environment.yaml` file, which now only has these contents:
```yaml
spack:
  specs:
    - cmake
    - root@6.20.04
  concretization: together
  view: True
```

Creating, activating and concretizing the environment via

```bash
spack env create debug-env environment.yaml
spack env activate debug-env
spack concretize -f
```

populates the `spack.lock` file in `spack/var/spack/environments/debug-env/`. Now the problem I seem to be experiencing is that the hash for `root@6.20.04` in the lock file is different than the hash that is obtained from concretizing the spec.

In my case in the lock file I find the following
```json
 "roots": [
  {
   "hash": "p6dvnoljjhe3qkfvniahoe7weuc6r65t",
   "spec": "cmake"
  },
  {
   "hash": "bldkrkkhftt2gqrxnfmxfqwjt7kc5arv",
   "spec": "root@6.20.04"
  }
```

Whereas when I do `spack find -L root cmake` in the activated environment I get:
```
==> In environment debug-env
==> Root specs
-------------------------------- cmake   -------------------------------- root@6.20.04 

==> 2 installed packages
-- linux-ubuntu20.04-skylake / gcc@9.3.0 ------------------------
p6dvnoljjhe3qkfvniahoe7weuc6r65t cmake@3.16.3  l6fvspq23dskh72nse5rpp56pnyi3wfr root@6.20.04
```

Interestingly the hashes for `cmake` are the same. However, this might be because `cmake` is a system package defined in `packages.yaml` in my case.

**Comment by alalazo** [comment]
@tmadlener What you report in https://github.com/spack/spack/issues/18338#issuecomment-685007048 is not an issue, in the sense that Spack is working as designed. Technically we use different kind of hashes for different purposes internally in Spack. When we show hashes on the command line we usually employ the "dag hash", while to write a lock file for environments we use the "build hash" (if you're interested in the details they're all documented in the docstrings of the corresponding methosds). 

To be more explicit and show how it works:
```console
$ spack-python
Spack version 0.15.4
Python 3.6.9, Linux x86_64
>>> import spack.spec
>>> openjpeg = spack.spec.Spec('openjpeg')
>>> openjpeg.concretize()
>>> openjpeg.dag_hash(), openjpeg.build_hash()
('526rapij3an7l2uwkdrrcaidxsqhqgep', 'if52i4ypij3ey77lgphdlwv6c3ixfj5j')
```
With this:
```yaml
spack:
  specs:
  - openjpeg
```
 `spack.yaml` for instance we obtain:
```console
$ spack --env . concretize
==> Concretized openjpeg
 -   526rapi  openjpeg@2.3.1%gcc@10.1.0 build_type=RelWithDebInfo arch=linux-ubuntu18.04-broadwell
 -   qz6wvej      ^cmake@3.18.2%gcc@10.1.0~doc+ncurses+openssl+ownlibs~qt arch=linux-ubuntu18.04-broadwell
[+]  kepdmuv      ^zlib@1.2.11%gcc@10.1.0+optimize+pic+shar
```
while in `spack.lock` we have this entry:
```
"roots": [
  {
   "hash": "if52i4ypij3ey77lgphdlwv6c3ixfj5j",
   "spec": "openjpeg"
  }
 ]
```

**Comment by tmadlener** [comment]
@alalazo, Thank you for clarifying this :)

**Comment by Char-Aznable** [comment]
I get similar error when activating a previously installed env after a `git pull` in the spack dir. Here is my steps to reproduce:
```
spack env create foo
... edit the spack.yaml and add some packages and set concretize: together and view: true
spack env activate foo
spack  concretize -f
spack install
spack env deactivate
cd ~/spack && git pull (update spack repo with new package definitions)
spack env activate (here I see error: ==> Error: 'r3whsvqnlkaggy2yzsfg7ay4mugj2tje')
```
Also, after the `git pull` step, the spack.lock file has wrong hash tags for the root specs, i.e., the hash in the error message `r3whsvqnlkaggy2yzsfg7ay4mugj2tje`. After replacing it with the actual hash tag of the installed package, I can activate the env again. This looks like a spack env bug

@alalazo @scheibelp
