### ISSUE TITLE
Can Not Build with CCE on Shasta

### ISSUE THREAD

**Issue by riscy768** [LLNL/spack#18356]
My team has little experience with Spack and about the same with our new Shasta system.  While I know Shasta's new (our is one the first), I'm concerned that I must be missing "something" fundamental in how I should be configuring my compiler, etc as I can't even do a base build of zlib with cce.  
```console
$ spack install zlib %cce
==> Installing zlib
==> No binary for zlib found: installing from source
==> zlib: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    './configure' '--prefix=/apps/spack/spack-0.15.4/opt/spack/cray-sles15-zen2/cce-10.0.1/zlib-1.2.11-y3flhbrdjyke55y3dgm6f2iiepfj2rds'
See build log for details:
  /tmp/hpc-adm/spack-stage/spack-stage-zlib-1.2.11-y3flhbrdjyke55y3dgm6f2iiepfj2rds/spack-build-out.txt

hpc-adm@ln02-nmn:/apps/spack/spack-0.15.4/opt/spack/cray-sles15-zen2> cat /tmp/hpc-adm/spack-stage/spack-stage-zlib-1.2.11-y3flhbrdjyke55y3dgm6f2iiepfj2rds/spack-build-out.txt
==> zlib: Executing phase: 'install'
==> [2020-08-28-13:34:30.205627] './configure' '--prefix=/apps/spack/spack-0.15.4/opt/spack/cray-sles15-zen2/cce-10.0.1/zlib-1.2.11-y3flhbrdjyke55y3dgm6f2iiepfj2rds'
Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
** ./configure aborting.
```
### Steps to reproduce the issue

On Shasta system.... 
- extract Spack
- run setup_env.sh
- spack install zlib %cce

### Error Message

The build log shows the following error:
```
Compiler error reporting is too harsh for ./configure (perhaps remove -Werror).
** ./configure aborting.
```

### Information on your system
 spack debug report
* **Spack:** 0.15.4
* **Python:** 3.6.10
* **Platform:** cray-sles15-zen2

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by riscy768** [comment]
Attaching debug output
[debug.out.cce-zlib.txt](https://github.com/spack/spack/files/5142433/debug.out.cce-zlib.txt)

**Comment by becker33** [comment]
It turns out this is because Cray uses `prereq` commands in EnvironmentModules v4 instead of `module load` commands to have the PrgEnv module load other modules. This causes some of Spack's internal module manipulations to fail, and is a different from the XC systems. There is an active bugfix branch for this `bugfix/shasta-hotfix-live-branch` to work out a solution.

**Comment by becker33** [comment]
Cray has changed the way they do their PrgEnv loading (to use module collections instead of meta-modules) because of this change in behavior in `module` v4. Updates to the Cray PE should alleviate this problem (although they will require other mitigations in Spack).

**Comment by alalazo** [comment]
Cray system based on environments have been deprecated, so I'll close this issue as won't fix :disappointed:
