### ISSUE TITLE
M4 installation fail on macOS sierra with GCC

### ISSUE THREAD

**Issue by ashkan2200** [LLNL/spack#1838]
Hi,
I have been trying to compile `M4` on `macOS sierra` using `gcc 6.2.0` but it fails with the error

    ./sched.h:42:8: error: redefinition of 'struct sched_param'
     struct sched_param
            ^~~~~~~~~~~
    In file included from ./sched.h:27:0,
                     from ./spawn.h:37,
                     from execute.c:47:
    /usr/include/sched.h:35:8: note: originally defined here
     struct sched_param { int sched_priority;  char __opaque[__SCHED_PARAM_SIZE__]; };
            ^~~~~~~~~~~
    make[3]: *** [execute.o] Error 1
    make[3]: *** Waiting for unfinished jobs....
    In file included from ./spawn.h:37:0,
                     from spawn-pipe.c:47:
    ./sched.h:42:8: error: redefinition of 'struct sched_param'
     struct sched_param
            ^~~~~~~~~~~
    In file included from ./sched.h:27:0,
                     from ./spawn.h:37,
                     from spawn-pipe.c:47:
    /usr/include/sched.h:35:8: note: originally defined here
     struct sched_param { int sched_priority;  char __opaque[__SCHED_PARAM_SIZE__]; };
            ^~~~~~~~~~~
    make[3]: *** [spawn-pipe.o] Error 1
    make[2]: *** [all] Error 2
    make[1]: *** [all-recursive] Error 1
    make: *** [all] Error 2

I have been able to compile `m4` with the pre-installed `gcc 4.2.1` though. 
Is there a way to tell `spack` to use the installed version of `m4` when other packages (such as `libtool`) depend on it and are being compiled with other compilers?

**Comment by adamjstewart** [comment]
> Is there a way to tell `spack` to use the installed version of `m4` when other packages (such as `libtool`) depend on it and are being compiled with other compilers?

Yep. See http://spack.readthedocs.io/en/latest/configuration.html#external-packages

**Comment by adamjstewart** [comment]
But we should probably also try to fix the M4 package...

**Comment by citibeth** [comment]
>     Is there a way to tell spack to use the installed version of m4 when other packages (such as libtool) depend on it and are being compiled with other compilers?
> 
> Yep. See http://spack.readthedocs.io/en/latest/configuration.html#external-packages

Please see the updated version of this document, it has some important updates on using false paths:  https://github.com/citibeth/spack/blob/efischer/docs2/lib/spack/docs/configuration.rst

> I have been able to compile m4 with the pre-installed gcc 4.2.1 though. 

AFAIK, MacOS now comes with Clang, not GCC --- although it might claim to be "compatible" with GCC 4.2.1 in some way.  Bottom line is, starting with El Capitan lots of things don't build on Mac with GCC.  Try using Clang, you should get better results.  See the note on "mixed toolchains" here: https://github.com/citibeth/spack/blob/efischer/docs2/lib/spack/docs/getting_started.rst

@tgamblin are there any barriers to merging pending doc PRs?  It's taking too much time pointing people to stuff that's written but not yet merged.

**Comment by adamjstewart** [comment]
Also see https://github.com/LLNL/spack/pull/1835#issuecomment-249209617 and https://github.com/LLNL/spack/pull/1835#issuecomment-249218540

**Comment by davydden** [comment]
> But we should probably also try to fix the M4 package, so keep this Issue open.

`m4` was building fine on El Capitan, so we just need to fix it on Sierra.

**Comment by davydden** [comment]
i reported upstream, see http://lists.gnu.org/archive/html/bug-m4/2016-09/msg00002.html

**Comment by davydden** [comment]
PR incoming...
