### ISSUE TITLE
hypre not handling  '--with-lapack-libs=['"'"'openblas'"'"']' correctly

### ISSUE THREAD

**Issue by sarich** [LLNL/spack#1840]
I'm trying to install HYPRE, which launches its own install of openblas. However, the link line for compiling HYPRE contains -l['openblas'] instead of -lopenblas.

From spack-build.out:

 './configure' '--prefix=/sandbox/sarich/sarich/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-4.8/hypre-2.10.1-unr2epq7jznxeg5onw7osjj4w5j3v67j' '--with-lapack-libs=['"'"'openblas'"'"']' '--with-lapack-lib-dirs=/sandbox/sarich/sarich/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-4.8/openblas-0.2.19-wofufd7oxokwglvljpcd4w6hexx3urzo/lib' '--with-blas-libs=['"'"'openblas'"'"']' '--with-blas-lib-dirs=/sandbox/sarich/sarich/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-4.8/openblas-0.2.19-wofufd7oxokwglvljpcd4w6hexx3urzo/lib' '--enable-shared'

...
Building libHYPRE.so ...

mpic++ ... -L/sandbox/sarich/sarich/spack/opt/spack/linux-Ubuntu14-x86_64/gcc-4.8/openblas-0.2.19-wofufd7oxokwglvljpcd4w6hexx3urzo/lib  -l['openblas'] ...

/usr/bin/ld: cannot find -l[openblas]

Also, is there an automatically generated log or info text somewhere that I can attach to an issue that contains all the information about my architecture, compilers, package versions, etc?

**Comment by tgamblin** [comment]
We don't have a log of he user's setup yet, but that is a good idea.  

This looks like an issue with #1682 -- @alalazo @davydden

**Comment by davydden** [comment]
I am looking at it... PR incoming
