### ISSUE TITLE
How to get a patch from website?

### ISSUE THREAD

**Issue by darmac** [LLNL/spack#18433]
We want to introduce a patch from here for `cvs`:
https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-vcs/cvs/files/cvs-1.12.13.1-fix-gnulib-SEGV-vasnprintf.patch

But when we using `patch()` function with above url, we can get a html file only.
So, what should I do to get the real patch file url?

Thanks for your kindly guidance.

**Comment by tkameyama** [comment]
May be https://gentoofan.org/gentoo/poly-c_overlay/dev-vcs/cvs/files/cvs-1.12.13.1-fix-gnulib-SEGV-vasnprintf.patch

**Comment by darmac** [comment]
Yes, thanks, so how can we get the url 
```
https://gentoofan.org/gentoo/poly-c_overlay/dev-vcs/cvs/files/cvs-1.12.13.1-fix-gnulib-SEGV-vasnprintf.patch
```

from

```
https://gentoofan.org/gentoo/poly-c_overlay/dev-vcs/cvs/files/cvs-1.12.13.1-fix-gnulib-SEGV-vasnprintf.patch
```

Just by manully check?

**Comment by tkameyama** [comment]
I search cvs-1.12.13.1-fix-gnulib-SEGV-vasnprintf.patch by google.

**Comment by darmac** [comment]
Got it, I thought there's a method to transfer the url...
