### ISSUE TITLE
nn-c uses invalid self.compiler.pic_flag?  (breaks nn-c build, via elmerfem build)

### ISSUE THREAD

**Issue by michaelkarlcoleman** [LLNL/spack#18469]
These lines fail, because there is no such member, and looking at other packages, it seems that flags like
```
self.compiler.cc_pic_flag
self.compiler.cxx_pic_flag
self.compiler.fc_pic_flag
#or ?
self.compiler.f77_pic_flag
```
would be appropriate.

https://github.com/spack/spack/blob/601f97d8a50b1840df9b056a34256b6dd2b54ce3/var/spack/repos/builtin/packages/nn-c/package.py#L29-L31

I triggered this on recent `devel` (today) by
```
spack install --test=root elmerfem@devel +mpi +hypre +lua +mumps +openmp +scatt2d +trilinos +zoltan
```

**Comment by adamjstewart** [comment]
@michaelkarlcoleman good catch, want to submit a PR to fix this? If not I can also submit a PR.

**Comment by michaelkarlcoleman** [comment]
Apologies, but I'm overrun right now. Thank you for jumping in. --Mike
