### ISSUE TITLE
f95 should be provided by gcc package?

### ISSUE THREAD

**Issue by michaelkarlcoleman** [LLNL/spack#18470]
### Rationale

Not sure whether this makes sense or not, but I feel like I'd like to load the dependencies for a spack package, including the 'gcc' it was built with, and then go to a completely independent git checkout of the software and build it (making use of the spack libs and compiler just loaded).  This didn't quite work because `f95` is magically present in the spack build environment, but not actually provided just by loading `gcc`.

Should this work?  Or is there some other magical way to get this effect?

This is on today's `devel` branch, for example.

### General information

- [ ] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
@michaelkarlcoleman the feature you're looking for is `spack dev-build`. It automatically sets `CC` and friends to Spack's compiler wrappers, sets up all the variables needed by the compiler wrappers, and builds your software. A similar command is `spack build-env`, which sets up the environment but doesn't actually run the build commands.

**Comment by michaelkarlcoleman** [comment]
Thanks very much!
