### ISSUE TITLE
fish: spack load displays warning message

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#18496]
When you run `spack load` with the `fish` shell, it displays a warning message. This can also be seen in [Spack's CI tests](https://github.com/spack/spack/runs/1069407405?check_suite_focus=true).

### Steps to reproduce the issue

```console
$ source $SPACK_ROOT/share/spack/setup-env.fish
$ spack install zlib
$ spack load zlib
```

### Error Message

Here is the warning message from our CI tests:
```console
set: Warning: $PATH entry "/home/runner/work/spack/spack/var/spack/environments/spack_test_env/.spack-env/view/bin:/home/runner/work/spack/spack/bin:/opt/hostedtoolcache/Python/3.8.5/x64/bin:/opt/hostedtoolcache/Python/3.8.5/x64:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games" is not valid (No such file or directory)
set: Did you mean 'set PATH $PATH /home/runner/work/spack/spack/bin:/opt/hostedtoolcache/Python/3.8.5/x64/bin:/opt/hostedtoolcache/Python/3.8.5/x64:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/share/rust/.cargo/bin:/home/runner/.config/composer/vendor/bin:/home/runner/.dotnet/tools:/snap/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games'?
```

### Information on your system

The warning from our CI is from Spack develop, the latest Ubuntu, and Python 3.8.

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

This issue was originally reported to me by @sbaks0820

@JBlaschke @pat-s @gonsie you're all known Spack + Fish users, any idea what's up here?

**Comment by JBlaschke** [comment]
Strange -- I tried to recreate using:
```
spack install zlib
spack load zlib
```
And I get no such warning.  Not saying that it's not my fault -- I just wonder if it might be something specific to my system (or yours/the CI). That warning can be issued if fish is detecting that an incorrect (i.e. non-existent) path exists in `PATH` -- so much is clear from the warning message itself.

Here is a theory: are you running fish from within bash? If so, is it possible that there are paths in `PATH` that are not valid? (maybe `/home/runner/work/spack/spack/var/spack/environments/spack_test_env/.spack-env/view/bin` -- at least that's what the warning message is recommending you leave out). When you launch fish from within bash it inherits bash's environment without checking it first. But when you're adding paths to `PATH` then entire pathstring is checked.

Anyway it's just a theory, I'll test the fish-within-a-bash later (I'm going to have to find a system where I didn't make fish my default shell :P )

**Comment by alalazo** [comment]
Cannot reproduce either:

![Screenshot from 2023-06-13 11-41-04](https://github.com/spack/spack/assets/4199709/7b085e03-40df-4491-8be9-6425ebdda7a3)

**Comment by adamjstewart** [comment]
There's no warning in our CI tests either, must have been fixed.
