### ISSUE TITLE
Installation issue: py-mpi4py ^python+uuid

### ISSUE THREAD

**Issue by EthanS94** [LLNL/spack#18492]
@adamjstewart I run into this issue after https://github.com/spack/spack/pull/18252

### Steps to reproduce the issue

This fails:
```console
$ spack install py-mpi4py@3.0.3%intel@19.0.4.243 arch=linux-rhel7-broadwell
...
  >> 126    //usr/lib64/libpsm_infinipath.so.1: undefined reference to `uuid_parse@@UUID_1.0'
  >> 127    //usr/lib64/libpsm_infinipath.so.1: undefined reference to `uuid_compare@@UUID_1.0'
  >> 128    //usr/lib64/libpsm_infinipath.so.1: undefined reference to `uuid_unparse_lower@@UUID_1.0
            '
  >> 129    //usr/lib64/libpsm_infinipath.so.1: undefined reference to `uuid_generate@@UUID_1.0'
     130    failure.
     131    removing: _configtest.c _configtest.o
  >> 132    error: Cannot link MPI programs. Check your configuration!!!

```

This works:
```console
$ spack install py-mpi4py@3.0.3%intel@19.0.4.243 ^python~uuid arch=linux-rhel7-broadwell
...
```

### Information on your system

```console
$ spack debug report
* **Spack:** 0.15.4-846-fab2622a7
* **Python:** 3.6.8
* **Platform:** linux-rhel7-broadwell
```

packages.yaml:
```yaml
packages:
  cmake:
    version: ['3.15.3']
  freetype:
    version: ['2.7.1']
  hdf5:
    version: ['1.10.2']
    variants: ['+mpi', '+hl']
  llvm:
    version: ['7.1.0']
    variants: ['+link_dylib', '~clang', '~compiler-rt', '~gold', '~internal_unwind', '~libcxx', '~lld', '~lldb', '~polly']
  mesa:
    version: ['18.3.6']
    variants: ['+llvm']
  ncurses:
    version: ['6.1']
    variants: ['+termlib']
  openblas:
    version: ['0.3.6']
  openmpi:
    version: ['2.1.2']
    externals:
    - spec: openmpi@2.1.2
      modules:
      - openmpi/2.1.2
    buildable: False
  openssl:
    version: ['1.0.2o']
  paraview:
    variants: ['+osmesa', '+opengl2', '+python3', '+plugins']
  python:
    version: ['3.6.8']
  py-matplotlib:
    version: ['3.1.1']
  py-numpy:
    version: ['1.17.3']
```

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/5171100/spack-build-out.txt)

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
@EthanS94 can you upload the build log?

@michaelkuhn can you help me debug this? I'm wondering if not all `uuid` libraries are created equal and the one we currently default to doesn't work. I know that #18322 hasn't been merged yet, but this would probably be a good test for it.

**Comment by EthanS94** [comment]
@adamjstewart Uploaded

**Comment by adamjstewart** [comment]
Can you go into the `python` installation directory and run `ld -r` on all of the `.so` files that are generated? It looks like `libuuid` isn't being linked correctly.

**Comment by EthanS94** [comment]
You mean `ldd -r` right? I get one error:
```
./lib/python3.6/lib-dynload/_tkinter.cpython-36m-x86_64-linux-gnu.so: /lustre/scratch4/yellow/stam/pilotlight-spack-grizzly-install/linux-rhel7-broadwell/intel-19.0.4.243/libuuid-1.0.3-pi57ecqey5jqnfimgkoci4xf3cxd2id6/lib/libuuid.so.1: no version information available (required by /lib64/libfontconfig.so.1)
```

The rest of the output is:
[python-ldd-out.txt](https://github.com/spack/spack/files/5171137/python-ldd-out.txt)

**Comment by adamjstewart** [comment]
Based on the error message above, I wonder if another possible issue is that `/usr/lib64/libpsm_infinipath.so` is linking to the system `libuuid` and it's a different version than the one that `python` links to.

**Comment by EthanS94** [comment]
Yes that looks correct:
```console
$ ldd /usr/lib64/libpsm_infinipath.so
...
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00002b9cf074a000)
```

**Comment by adamjstewart** [comment]
@skosukhin also volunteered to help me maintain the Python package, maybe he can help.

@tgamblin do we currently have anything in place to deal with multiple libraries appearing in the DAG? I don't think we currently have a package for infiniband to prevent this problem.

**Comment by skosukhin** [comment]
To my understanding, this is a typical problem with external packages: if you introduce an external package you have to declare all its dependencies as externals too. In this case, `libuuid` should be listed in `packages.yaml` too. The problem is that the library is installed to `/lib64` but the headers are most probably in `/usr/include`. Therefore, it's unclear what path should be set in `packages.yaml`. I would check whether there is a symlink in `/usr/lib/libuuid.so` or in `/usr/lib64/libuuid.so` that points to `/lib64/libuuid.so.1`. If that is the case, the `path:` for `libuuid:` in `packages.yaml` can be set to `/usr`.

**Comment by AndrewGaspar** [comment]
@skosukhin I ran into the same issue on (I think) the same system, and yes, /lib64 symlinks to /usr/lib64.

I think this issue can be closed.

**Comment by EthanS94** [comment]
The initial issue was encountered when letting spack build libuuid instead of using the system's libuuid.

I've moved to using the system's libuuid as an external dependency. A different package depends on it which can't be disabled with a variant `~uuid`.  I think it is xt, but I can't remember. That's been working fine.

I haven't tested with spack-built libuuid in a while. I'm fine with closing this.

**Comment by adamjstewart** [comment]
We recently added a `uuid` virtual package that probably helps with this.
