### ISSUE TITLE
Transitive Dependency Types

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#1849]
This issue comes from #1703, which has now been closed:

> The general issue here seems to be how depedency types are forwarded.  Or
> more specificly... if C --> B --> A, then what is the dependency
> relationship between C and A?  When there was just one kind of dependency,
> this was easy.  But now that there are many kinds, we need a well-defined
> function that tells us the details of the C --> A relationship, based on
> the C --> B and B --> A relationships.

@tgamblin suggested it needs a response.

**Comment by adamjstewart** [comment]
@scheibelp

**Comment by scheibelp** [comment]
In my opinion, #3768 is the spot to address this. Please reopen if that is not the case.
