### ISSUE TITLE
cross-compiling libsigsegv fails

### ISSUE THREAD

**Issue by sarich** [LLNL/spack#1855]
==> Installing libsigsegv
==> Trying to fetch from file:///autofs/nccs-svm1_proj/cli112/sarich/spack/var/spack/cache/libsigsegv/libsigsegv-2.10.tar.gz
######################################################################## 100.0%
==> Staging archive: /autofs/nccs-svm1_proj/cli112/sarich/spack/var/spack/stage/libsigsegv-2.10-noz5upuhx23xwa3ifhnixsdpacesrzx5/libsigsegv-2.10.tar.gz
==> Created stage in /autofs/nccs-svm1_proj/cli112/sarich/spack/var/spack/stage/libsigsegv-2.10-noz5upuhx23xwa3ifhnixsdpacesrzx5
==> No patches needed for libsigsegv
==> Building libsigsegv
==> './configure' '--prefix=/autofs/nccs-svm1_proj/cli112/sarich/spack/opt/spack/cray-CNL-interlagos/intel-15.0.2.164/libsigsegv-2.10-noz5upuhx23xwa3ifhnixsdpacesrzx5' '--enable-shared'

Build Tools:
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking for gcc... /autofs/nccs-svm1_proj/cli112/sarich/spack/lib/spack/env/intel/icc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... configure: error: in `/tmp/sarich/spack-stage/spack-stage-8gbEJ8/libsigsegv-2.10':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use `--host'.
See `config.log' for more details
==> Error: Command exited with status 1:
'./configure' '--prefix=/autofs/nccs-svm1_proj/cli112/sarich/spack/opt/spack/cray-CNL-interlagos/intel-15.0.2.164/libsigsegv-2.10-noz5upuhx23xwa3ifhnixsdpacesrzx5' '--enable-shared'

See build log for details:
  /tmp/sarich/spack-stage/spack-stage-8gbEJ8/libsigsegv-2.10/spack-build.out

/autofs/nccs-svm1_proj/cli112/sarich/spack/var/spack/repos/builtin/packages/libsigsegv/package.py:37, in install:
     35       def install(self, spec, prefix):
     36           configure('--prefix=%s' % prefix,
  >> 37                     '--enable-shared')
     38   
     39           make()
     40           make("install")
==> Error: Installation process had nonzero exit code : 256

**Comment by sarich** [comment]
In case it helps, I'm attaching libsigsegv config.log
[config.log.txt](https://github.com/LLNL/spack/files/493788/config.log.txt)

**Comment by robertdfrench** [comment]
Hi @sarich. Can you post your ~/.spack/compilers.yaml?

**Comment by sarich** [comment]
hard-coding --host=amd64-linux to libsigsegv configure solves this for me on this system, I don't know how to access the correct value for other systems

**Comment by sarich** [comment]
compilers:
- compiler:
    modules:
    - PrgEnv-cray
    - cce/8.4.0
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: cce@8.4.0
- compiler:
    modules:
    - PrgEnv-cray
    - cce/8.4.2
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: cce@8.4.2
- compiler:
    modules:
    - PrgEnv-cray
    - cce/8.4.6
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: cce@8.4.6
- compiler:
    modules:
    - PrgEnv-cray
    - cce/8.5.0
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: cce@8.5.0
- compiler:
    modules:
    - PrgEnv-gnu
    - gcc/4.8.1
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: gcc@4.8.1
- compiler:
    modules:
    - PrgEnv-gnu
    - gcc/4.9.3
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: gcc@4.9.3
- compiler:
    modules:
    - PrgEnv-gnu
    - gcc/5.3.0
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: gcc@5.3.0
- compiler:
    modules:
    - PrgEnv-gnu
    - gcc/4.8.2
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: gcc@4.8.2
- compiler:
    modules:
    - PrgEnv-gnu
    - gcc/5.2.0
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: gcc@5.2.0
- compiler:
    modules:
    - PrgEnv-intel
    - intel/13.1.3.192
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: intel@13.1.3.192
- compiler:
    modules:
    - PrgEnv-intel
    - intel/15.0.2.164
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: intel@15.0.2.164
- compiler:
    modules:
    - PrgEnv-intel
    - intel/14.0.2.144
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: intel@14.0.2.144
- compiler:
    modules:
    - PrgEnv-intel
    - intel/16.0.3.210
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: intel@16.0.3.210
- compiler:
    modules:
    - PrgEnv-pgi
    - pgi/15.10.0
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: pgi@15.10.0
- compiler:
    modules:
    - PrgEnv-pgi
    - pgi/15.7.0
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: pgi@15.7.0
- compiler:
    modules:
    - PrgEnv-pgi
    - pgi/16.4.0
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: pgi@16.4.0
- compiler:
    modules:
    - PrgEnv-pgi
    - pgi/15.3.0
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: pgi@15.3.0
- compiler:
    modules:
    - PrgEnv-pgi
    - pgi/16.3.0
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: pgi@16.3.0
- compiler:
    modules:
    - PrgEnv-pgi
    - pgi/16.5.0
    operating_system: CNL
    paths:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
    spec: pgi@16.5.0
- compiler:
    modules: []
    operating_system: SuSE11
    paths:
      cc: null
      cxx: null
      f77: /usr/bin/gfortran-4.3
      fc: /usr/bin/gfortran-4.3
    spec: gcc@4.3.4
- compiler:
    modules: []
    operating_system: SuSE11
    paths:
      cc: /usr/bin/gcc-4.7
      cxx: /usr/bin/g++-4.7
      f77: null
      fc: null
    spec: gcc@4.7
- compiler:
    modules: []
    operating_system: SuSE11
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: null
      fc: null
    spec: gcc@4.3
- compiler:
    modules: []
    operating_system: SuSE11
    paths:
      cc: /opt/pgi/16.5.0/linux86-64/16.5/bin/pgcc
      cxx: /opt/pgi/16.5.0/linux86-64/16.5/bin/pgc++
      f77: /opt/pgi/16.5.0/linux86-64/16.5/bin/pgfortran
      fc: /opt/pgi/16.5.0/linux86-64/16.5/bin/pgf95
    spec: pgi@16.5-0

**Comment by robertdfrench** [comment]
Just curious -- are you trying to incorporate libsigsegv into an application that you plan to run on the compute nodes, or is this getting built as a dependency of a build tool (cmake or autoconf or some such)?

**Comment by robertdfrench** [comment]
I ask because it looks like your Intel 15 is set up for CNL and not SuSE11, and I'm wondering if you could get away with building libsigsegv for the login nodes so that you wouldn't have to fight the compiler wrappers

**Comment by sarich** [comment]
I'm trying to install moab, which somewhere triggers a build for ilbsigsegv. I don't know where it gets used. It's possible I only need it on the login nodes.

**Comment by sarich** [comment]
You're right, it's a requirement for m4

**Comment by robertdfrench** [comment]
Ah, cool. Somehow it is possible to get Spack to care less about ABI compatibility for things that aren't linked in to your final product. Let me play around with this and see if I can whip up an example

**Comment by robertdfrench** [comment]
Actually, have you got cray-mpich defined in your packages.yaml? I just ran `./bin/spack spec moab %intel@15.0.2 arch=cray-CNL-interlagos` on a fresh Spack install, and it shows that m4 is needed to build openmpi, and that is likely to cause headaches on Titan.

**Comment by adamjstewart** [comment]
Is the problem with libsigsegv or with your compilers? Are you able to compile any other programs?

If libsigsegv is the problem, it's an optional dependency of m4. So you can build with:
```
spack install moab ^m4~sigsegv
```
Or you can set that in your `packages.yaml` file.

**Comment by sarich** [comment]
Oh, I did forget to add cray-mpich for pgi compilers. Thanks for catching that.

**Comment by robertdfrench** [comment]
@sarich you might also consider (if you haven't already) defining cray-trilinos in your packages.yaml.

**Comment by sarich** [comment]
unfortunately, cray-trilinos isn't compatible with pgi (which I need to use)

module load PrgEnv-pgi
module load cray-trilinos
> ftn
Error: PE_TRILINOS is not available for the PGI compiler

I'm trying to modify the moab package.py to use a trilinos-less variant

**Comment by robertdfrench** [comment]
You're absolutely right, says right in the module help that it only supports CCE, Gnu, and Intel. I am shocked.

**Comment by sarich** [comment]
I'm closing this issue, the original problem has been solved. I'll open another one for any more trouble installing moab.

Thanks for all the help,
Jason
