### ISSUE TITLE
Improve error message when view construction fails

### ISSUE THREAD

**Issue by mpokorny** [LLNL/spack#18570]
Attempting to create a view that erroneously links packages with the same name into the same prefix results in a somewhat cryptic error message: `Error: the transactional move of ".../views/default" failed.` A different error message, which tells the end user directly about the conflict, or what might be done to correct the view definition, would be an improvement.

### Steps to reproduce the issue

Create an environment "env" with a view that would link two packages with the same name into the same prefix. Say, package "foo" built for two different targets "A" and "B", and the following view description
```yaml
view:
  default:
    root: views/default
    select: [foo]
    projections:
      all: '{name}'
```
```console
$ spack concretize
```

### Error Message

```console
Error: the transactional move of ".../var/spack/environments/env/views/default" failed.
```

### Information on your system

* **Spack:** 0.15.4-687-81bb372d7
* **Python:** 3.8.2
* **Platform:** linux-rhel7-cascadelake

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by hartzell** [comment]
In lieu of the error message being improved, you can get the gory details, including the thing that's colliding, if you run `spack -d concretize`.

**Comment by scheibelp** [comment]
@becker33 IIRC you handled an issue like this with a vague error message

@mpokorny can you reproduce this on a current develop version of Spack? If the error still occurs, is the message the same?

**Comment by mpokorny** [comment]
I haven't paid much attention to this issue recently, but yesterday I encountered the same error message again. Now there is an additional line of output that identifies the package that caused the conflict. Either I missed that message previously, or it's new, but in any case, I think that this issue is essentially fixed.
