### ISSUE TITLE
require MPI to be always built with Fortran

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#1859]
Since currently we can't pass any variants in virtual packages (see https://github.com/LLNL/spack/issues/1712), there are several options:

1. To each relevant package add `asserts` to make sure `spec['mpi'].mpif77` and `spec['mpi'].mpifc` point to existing files. If not, raise en error that `mpi` installation does not contain fortran wrappers and users need to make sure that `Fortran` compiler is set and re-build `mpi`. This is doable but potentially **a lot of code duplication** which is not a solution, but a workaround.

2. Leave things as is and if something fails to build, let users suffer and dig into output logs to find out that they are building a package which needs fortran but their `mpi` is built without `fortran`.

3. Force all `mpi` implementation to provide Fortran wrappers. Throw an error if fortran compiler is not available during build time. That is the current behaviour of `mpich`, but `openmpi` allows to install it without `fortran`. In the HPC context, probably 99% of times people do have Fortran compilers around. Most likely only mac users may suffer a bit as they will need to always mix `clang` with `gfortran` even if they don't plant to compile packages which need fortran wrappers. But if @tgamblin can engineer a quick fix for this setup (see https://github.com/LLNL/spack/issues/1850#issuecomment-249449306), then i think it's a viable solution. 

in reference to https://github.com/LLNL/spack/pull/1516, https://github.com/LLNL/spack/pull/1441 and https://github.com/LLNL/spack/pull/1084.

@pramodk @suraia @alalazo ping.

I am in favour of (3).

p.s. i don't consider (2) an option, but I list it here anyway.

**Comment by citibeth** [comment]
I agree, I think (3) is the best option.  Probably 90% of MPI code is written Fortran anyway.  This will make peoples' lives easier.

**Comment by suraia** [comment]
I also think option 3 is the best solution. Having the MPI installation fail immediately is much better than having to recompile (almost) everything once you hit a package that needs a Fortran compiler.

**Comment by tgamblin** [comment]
I agree that (3) is the best option until we can pass variants through virtual deps.

I am planning to look at adding extra compiler descriptions for `clang-fortran`, `clang-intel` and maybe `clang-pgi` to as well as some auto-detection logic for these.  I am not overly fond of combinatorial compiler names, but this is intended as a stop-gap until compilers become proper dependencies.  I've talked with @BarrySmith about this recently and he suggested something similar.

**Comment by adamjstewart** [comment]
@tgamblin How do you propose to handle version numbering for your combinatorial compilers? I would ask you to do one for NAG, but I don't think NAG works anyway. Still haven't figured out why...

**Comment by tgamblin** [comment]
@adamjstewart: yeah, that.  The idea is to concatenate versions, e.g. `clang-gfortran@7.0.2-apple-6.2`.  Not pretty, and it prevents you from orthogonally setting constraints on the fortran compiler version needed for something.

That said, we don't require particular compiler version frequently in the current Spack packages, and I'm not sure it makes sense, so I think it is a small price to pay.  The eventual compilers-as-dependencies plan would allow people to depend on virtual deps like `c@99:`, `fortran@95:`, or `openmp@4:`, which compilers would provide.  It think that is a much more sensible way to require compiler capabilities than their native (rather confusing) version numbers, anyway.
