### ISSUE TITLE
Spack gets confused about which packages are installed

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#186]
I was installing `gcc` when I lost my network connection to the server. I assume there's an incomplete build around.

So currently I have:
```
$ spack install gcc
==> gcc is already installed in /xfs1/eschnetter/src/spack/opt/spack/linux-x86_64/gcc-4.9.2/gcc-5.2.0-s2elgk7nmbeuiosmp5xuawinugiej2an.
$ spack uninstall gcc
==> Error: gcc does not match any installed packages.
$ spack find gcc
==> 0 installed packages.
```

**Comment by mathstuf** [comment]
`spack reindex` should fix this, no?

**Comment by adamjstewart** [comment]
The usual fix is:
```bash
rm -rf /xfs1/eschnetter/src/spack/opt/spack/linux-x86_64/gcc-4.9.2/gcc-5.2.0-s2elgk7nmbeuiosmp5xuawinugiej2an
spack reindex
```
but this shouldn't ever happen in the first place. Unfortunately it happens all the time after failed installations.

**Comment by tgamblin** [comment]
@adamjstewart: Recently (can't remember how recently) two things have happened:
  1. I added some code to give a better error message when a prefix exists but doesn't have a valid spec in it.  
  2. The way the removal of the prefix is handled was made a bit more transactional.

I'd be really interested to know why/when Spack fails to remove the install prefix after a failed install.  How often do you see that?

Do you ever see [this error raised in `directory_layout.py`](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/directory_layout.py#L150)?  That is called [from here in `package.py`](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/package.py#L938), where the prefix removal is done automatically if anything goes wrong. I have not seen so many stale install directories.

**Comment by adamjstewart** [comment]
@tgamblin: I haven't come across that particular error message yet, but I'll let you know if I do.

Now that I think about it, the problem described by @eschnett usually occurs for me when I realize I specified something wrong and do a <kbd>Ctrl</kbd>+<kbd>C</kbd> to kill the install. When a user sends the `SIGINT` signal to Spack, does it have special handling to remove the directory it is trying to install into?

**Comment by tgamblin** [comment]
Well, the logic here *should* catch `KeyboardInterrupt` too:

```python
try:                                                                        
    # Create the install prefix and fork the build process.                 
    spack.install_layout.create_install_directory(self.spec)                
    spack.build_environment.fork(self, build_process)                       
except:                                                                     
    # remove the install prefix if anything went wrong during install.      
    if not keep_prefix:                                                     
        self.remove_prefix()                                                
    else:                                                                   
        tty.warn("Keeping install prefix in place despite error.",          
                 "Spack will think this package is installed. " +           
                 "Manually remove this directory to fix:",                  
                 self.prefix, wrap=True)                                    
    raise
```

The unqualified `except:` there should catch anything raised, remove the prefix, and raise the same exception again.  Looking at it, though, this code is not race-free with interrupts.  I don't currently set up signal handling properly for the child process, so you can probably cause the parent to attempt to remove the prefix *before* the child tries to create it, and get a bad install directory.  This should really be reworked to be signal safe.  There is some boilerplate [here](http://stackoverflow.com/questions/11312525/catch-ctrlc-sigint-and-exit-multiprocesses-gracefully-in-python).

**Comment by eschnett** [comment]
It would make sense to put a special marker into incomplete install directories? This way, when `spack install` checks whether a package already exists, it can look for that marker, and then remove the prefix before installing. This would then automatically also handle the case where the prefix is kept on purpose.

**Comment by tgamblin** [comment]
@eschnett: that is a good point.  I think that is worth adding.

**Comment by adamjstewart** [comment]
Just thought I'd mention, I recently tried to install a package that was so large it filled the entire filesystem and crashed Spack (blame static libraries). When I emptied stage and tried installing again, Spack told me:

```
==> Error: Inconsistent state: install prefix exists but contains no spec.yaml:
  /blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-5.3.0/elk-3.3.17-6kvicjiinej5c6df3qthxj3is66ry42p
```

I guess this is an improvement on telling me the package is already installed.

**Comment by adamjstewart** [comment]
Has anyone seen this bug lately? I don't think I have.

**Comment by tgamblin** [comment]
I believe this, #1266, and #1966 are the same issue.
