### ISSUE TITLE
Subversion fails to install on RHEL7.2

### ISSUE THREAD

**Issue by KineticTheory** [LLNL/spack#1860]
I need some help figuring this one out.  I have a basic RHEL7 system (system compiler is gcc-4.8.5) and  `spack install subversion` fails.  The error is:

```
cd subversion/svnfsfs ; /bin/sh "/tmp/kellyt/spack-stage/spack-stage-ZlxsKR/subversion-1.9.3/libtool" --mode=install /bin/install -c svnfsfs /scratch/vendors/spack/opt/spack/linux-redhat7-x86_64/gcc-4.8.5/subversion-1.9.3-ejpzfelikjgc3tbnl2jalo64mh2jajst/bin/svnfsfs
.libs/commit.o: In function `svn_ra_serf__get_commit_editor':
/tmp/kellyt/spack-stage/spack-stage-ZlxsKR/subversion-1.9.3/subversion/libsvn_ra_serf/commit.c:2144: undefined reference to `svn_editor__insert_shims'
collect2: error: ld returned 1 exit status
```

Spack: fresh checkout from 2016/09/26.
[spack-build.out.txt](https://github.com/LLNL/spack/files/494075/spack-build.out.txt)
[spack-build.env.txt](https://github.com/LLNL/spack/files/494076/spack-build.env.txt)

Anyone else seeing this? Any suggestions on how to move forward with this one? BTW - version 1.8.13 fails in exactly the same way.

**Comment by KineticTheory** [comment]
It looks like `spack install -j 1 subversion` fixes the above error.

**Comment by adamjstewart** [comment]
@KineticTheory Can you submit a PR to add that to the package.py? See http://spack.readthedocs.io/en/latest/packaging_guide.html#parallel-builds

**Comment by tgamblin** [comment]
Fixed.
