### ISSUE TITLE
Few questions regarding Spack

### ISSUE THREAD

**Issue by Joe23232** [LLNL/spack#18605]
I have a few questions regarding `spack`

1. Does it support various flags that the portage package manager supports, for example USE flags and all the other flags? In other words is `spack` just as powerful as the portage package manager?
2. Can I install applications in the root area where normal package managers (such as `pacman`) does for various applications such as `firefox`?
3. If question 2 is true, can I use it as a replacement of other package managers such as `pacman`, for example if I have `firefox` already installed by `pacman`, I can update it via `spack`?

**Comment by tgamblin** [comment]
> 1. Does it support various flags that the portage package manager supports, for example USE flags and all the other flags? In other words is `spack` just as powerful as the portage package manager?

Packages can have [variants](https://spack.readthedocs.io/en/latest/packaging_guide.html#variants), and you can control them with [package preferences](https://spack.readthedocs.io/en/latest/build_settings.html#concretization-preferences), which is roughly equivalent and potentially finer-grained than USE flags.

> 2. Can I install applications in the root area where normal package managers (such as `pacman`) does for various applications such as `firefox`?

No, Spack packages have to *install* in separate prefixes.  You can create an environment, where all the packages are linked into a single symlink tree, and you can configure where the tree goes. See https://spack.readthedocs.io/en/latest/environments.html#configuring-environment-views.  You should NOT set the root of your environment to `/`, though -- bad things will happen.  You can make a prefix elsewhere.

> 3. If question 2 is true, can I use it as a replacement of other package managers such as `pacman`, for example if I have `firefox` already installed by `pacman`, I can update it via `spack`?

No, but you could install it somewhere else and just use it.  We are not at the point yet where we can fully replace the system package manager (or coexist with it in the same prefix).

**Comment by Joe23232** [comment]
I see, thanks man.

**Comment by tgamblin** [comment]
Let us know if you have more questions!

**Comment by Joe23232** [comment]
@tgamblin Thank you mate

May I suggest something for `spack`? I wanted to suggest to have an option to allow users to install an application in the root area and it installs it in the same manner as `pacman`.

**Comment by tgamblin** [comment]
@Joe23232: we likely won't do this, at least not unless it is through environments as I mentioned above (we could make it safer to point an environment at `/`).

The reason is that if we made packages actually *install* to the root, we would only be able to have one version of any particular package.  This is one of the limitations of system package managers that Spack is designed to get around.

It would be interesting to know why you need that particular feature and why Spack can't suite the use case.

**Comment by Joe23232** [comment]
> It would be interesting to know why you need that particular feature and why Spack can't suite the use case.

If I were to use something like KISS Linux, I would like to use `Spack` package manager to update the entire OS rather than using the built in package manager as you can't use USE and CFlags.
