### ISSUE TITLE
Undefined symbols from flex

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#1864]
I'm trying to add a package for something that depends on flex, but it's generating the following error message:

```
configure:10912: checking for flex
configure:10928: found /home/ajstewart/spack/opt/spack/linux-fedora24-x86_64/gcc-6.1.1/flex-2.6.0-w6wseh5ilzsol36gf4bwo645u3ovounz/bin/flex
configure:10939: result: flex
configure:10977: flex conftest.l
flex: fatal internal error, exec of /home/ajstewart/spack/opt/spack/linux-fedora24-x86_64/gcc-6.1.1/m4-1.4.17-wrmoocrr55qzqy2es3hjsubmk54hwcn5/bin/m4 failed
flex: error writing output file lex.yy.c
```

When I checked, I noticed the flex library has some undefined symbols:

```
$ ldd -r /home/ajstewart/spack/opt/spack/linux-fedora24-x86_64/gcc-6.1.1/flex-2.6.0-w6wseh5ilzsol36gf4bwo645u3ovounz/lib/libfl.so
    linux-vdso.so.1 (0x00007ffd5375a000)
    libm.so.6 => /lib64/libm.so.6 (0x00007fe038f38000)
    libc.so.6 => /lib64/libc.so.6 (0x00007fe038b76000)
    /lib64/ld-linux-x86-64.so.2 (0x0000560ace3e8000)
undefined symbol: yylex (/home/ajstewart/spack/opt/spack/linux-fedora24-x86_64/gcc-6.1.1/flex-2.6.0-w6wseh5ilzsol36gf4bwo645u3ovounz/lib/libfl.so)
```

Does anyone know how to solve this?

**Comment by eschnett** [comment]
I think `yylex` is the name of the function the user has to define. I think your actual error is that your `m4` is not working, hence the file `lex.yy.c` is not finished, hence this function is missing.

**Comment by alalazo** [comment]
@adamjstewart Was this solved thanks to @eschnett comment?

**Comment by adamjstewart** [comment]
I'm not sure. He suggested that there was something wrong with my `m4`, so I guess the new question is what is wrong with it. I can't even remember what package I was working on when this happened though. I guess if flex is supposed to have that undefined symbol, then I guess we are fine for now.
