### ISSUE TITLE
macOS nightly build tests are failing

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#18642]
Our macOS nightly build tests are failing for jupyter because `qt` can't find its `opengl` dependency even though we are adding it as an external package. We should either fix this, or switch to another package like `jupyterlab` which doesn't depend on `opengl`.

@ax3l do you have time to take a look at this?

**Comment by ax3l** [comment]
Yes, that's #18370. Let's see what the progress on that one is.

**Comment by adamjstewart** [comment]
I new it existed but couldn't find the issue, thanks.
