### ISSUE TITLE
Spack-generated modulefiles may exceed line-length limits for tcl

### ISSUE THREAD

**Issue by quellyn** [LLNL/spack#18667]
We use Spack environments on a variety of platforms. Recently I encountered the following error while trying to load a particular Spack-built modulefile:

```console
shapo/171108-gcc-9.2.0-t34z6v5(7):ERROR:102: Tcl command execution failed: ake/paraview-5.6 -DBUILD_SHAPO_PARALLEL=ON
```

The issue seems to be a single long line (8234 characters) in the modulefile -- a comment containing the package configuration options:
```console
## Configure options: -G Unix Makefiles -DCMAKE_INSTALL_PREFIX:STRING=/projects/shavano/dev/quellyn/dw/DWX86G/spack-environments/DWX86G_9.2.0/1.4/spack/opt/spack/linux-centos7-skylake/gcc-9.2.0/shapo-171108-t34z6v5wv6zk4hiiqkbjvncvbzgtn3vf . . . . . . . .cmake/paraview-5.6 -DBUILD_SHAPO_PARALLEL=ON
```

If I break up this huge line into two separate comments, then the module file loads without a problem.

Although I couldn't find confirmation of this, I'm guessing that Tcl has a line-length limit of 8192 characters.

I suspect that the issue was triggered by my organizational scheme; I tend to use a deep paths to my development/test area. For example:
```console
SPACK_ROOT=/usr/projects/lap/dev/quellyn/dw/darwin-x86-gcc/spack-environments/DWX86G_9.2.0/1.4
```

It's probably that the propagation of these lengthy paths has blown up the size of that line past the limit.

### Steps to reproduce the issue

I believe adding a very long line to any Spack-generated modulefile will likely precipitate this issue.

### Information on your system

```console
$ spack debug report
* **Spack:** 0.15.4-679-878d0b7
* **Python:** 3.6.8
* **Platform:** linux-centos7-skylake_avx512
```

### Additional information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by xdelaruelle** [comment]
This issue seems related to environment-modules@3.2 and not Tcl itself. [A line length limit is set](https://github.com/cea-hpc/modules/blob/c-3.2/modules_def.h#L448) to read each modulefile line.

For the record, this issue does not affect environment-modules 4.0 and newer versions.

**Comment by quellyn** [comment]
> This issue seems related to environment-modules@3.2 and not Tcl itself. [A line length limit is set](https://github.com/cea-hpc/modules/blob/c-3.2/modules_def.h#L448) to read each modulefile line.

That makes more sense; thank you for confirming that.

> For the record, this issue does not affect environment-modules 4.0 and newer versions.

That's good news for the future. Much of our HPC infrastructure is still RHEL/CentOS 7 based and I'm not confident I can convince them to adopt a newer version of environment-modules at this time. Since Spack builds its modulefiles, I was hoping there might be a way to tell it to suppress the inclusion of comments.

**Comment by quellyn** [comment]
Oops, thought I closed this a while back. Anyway, it's not a Spack issue and we can work around it using a custom `modulefile.tcl` that avoids printing the configure line for the package in question.

Thanks again!
