### ISSUE TITLE
Installation issue: Perl failed to recognize macOS Big Sur at step ‘configure’

### ISSUE THREAD

**Issue by zhiyuanzhai** [LLNL/spack#18660]
### Steps to reproduce the issue

```console
$ spack install -v perl
...
*** Unexpected product version 11.0.
***
*** Try running sw_vers and see what its ProductVersion says.
```

This problem is basically due to Apple's bumping the version number to 11.0. It is actually resolved by this [PR](https://github.com/Perl/perl5/pull/17946). I believe that we just have to copy what they did.

### Information on your system

* **Spack:** 0.15.4-947-1aceb38b8
* **Python:** 3.8.5
* **Platform:** darwin-macos-skylake

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/5335141/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/5335142/spack-build-out.txt)

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Want to submit a PR? Basically you would just add that patch and apply it to whatever versions work.

**Comment by zhiyuanzhai** [comment]
@adamjstewart Well... I've got a lot to learn before submitting this PR. I may need some time. But I will try.
