### ISSUE TITLE
pipelines: ci rebuild: env activated via `-e` switch not inherited by subprocess

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#18677]
When `spack ci rebuild` is invoked like `spack -e <path> ci rebuild`, then the subprocess launched to handle installation of dependencies from build cache is launched without awareness of the environment specified by `<path>`.

One important effect here is that if you set `mirrors:` in your `spack.yaml`, and then in your child jobs run `spack -e <path-to-env> ci rebuild`, you won't be able to install dependencies from the mirror because the installation subprocess doesn't know about the `mirrors:` defined in the Spack environment.

@shahzebsiddiqui

**Comment by scottwittenburg** [comment]
Thanks for reporting this @eugeneswalker, I'll take a look when I get a chance.  

In the meantime, and for others who end up here, you can make it work by explicitly activating your environment before you invoke the ci rebuild command.

```
    script:
      - ...
      - spack env activate --without-view <path-to-env>
      - spack ci rebuild
      - ...
```
