### ISSUE TITLE
Installation issue: py-setuptools

### ISSUE THREAD

**Issue by ikitayama** [LLNL/spack#18674]
```

$ spack install jube
==> python@3.6.8 : externally installed in /usr
[+] /usr
==> Installing py-setuptools
==> No binary for py-setuptools found: installing from source
==> Using cached archive: /vol0001/hp200139/data/u00444/projects/spack/var/spack/cache/_source-cache/archive/4a/4a7708dafd2d360ce5e2ac7577374da9fb65fc867bc4cdaf461f9f834dfa6ac3.zip
==> py-setuptools: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 1:
    '/usr/bin/python' '-s' 'setup.py' '--no-user-cfg' 'build'
See build log for details:
  /home/hp200139/u00444/spack-stage/spack-stage-py-setuptools-50.1.0-jef3aqs35wzc5q6kbdqjlby55ep2gskf/spack-build-out.txt

==> Warning: Skipping build of jube since py-setuptools failed
==> Error: Installation of jube failed.  Review log for details
```

**Comment by ikitayama** [comment]
The log:

```
==> py-setuptools: Executing phase: 'build'
==> [2020-09-15-17:01:13.651639] '/usr/bin/python' '-s' 'setup.py' '--no-user-cfg' 'build'
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    import setuptools
  File "/vol0001/hp200139/u00444/spack-stage/spack-stage-py-setuptools-50.1.0-jef3aqs35wzc5q6kbdqjlby55ep2gskf/spack-src/setuptools/__init__.py", line 16, in <module>
    import setuptools.version
  File "/vol0001/hp200139/u00444/spack-stage/spack-stage-py-setuptools-50.1.0-jef3aqs35wzc5q6kbdqjlby55ep2gskf/spack-src/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/vol0001/hp200139/u00444/spack-stage/spack-stage-py-setuptools-50.1.0-jef3aqs35wzc5q6kbdqjlby55ep2gskf/spack-src/pkg_resources/__init__.py", line 1365
    raise SyntaxError(e) from e
                            ^
SyntaxError: invalid syntax
````

**Comment by adamjstewart** [comment]
It looks like you're using an externally installed Python 3.6.8 installed in `/usr`. What I think is going on is that for some reason Spack is picking up a Python 2 installation in `/usr` instead and trying to use that to install the latest version of `py-setuptools`, which only supports Python 3.

Can you check in `/usr/bin` and confirm that `python3.6` is available? Is there also a `python2` in that directory?

**Comment by ikitayama** [comment]
On the Fugaku login node, `python2` is a symbolic link to python2.7. There's no Python 3.6.8 in `/usr/bin`.

**Comment by adamjstewart** [comment]
In that case I think you need to update your `packages.yaml` to use the correct version of Python or the correct installation prefix of Python 3. Spack thinks that `/usr/bin/python` is Python 3.6.8, which is why it's crashing.

**Comment by ikitayama** [comment]
Nope it's 2.7.5.

**Comment by adamjstewart** [comment]
Maybe update your `packages.yaml` to `2.7.5`. Unfortunately you'll have to specify which versions of `py-setuptools` and other packages support Python 2 because the concretizer is currently broken. Alternatively, don't use an external package and let Spack build Python 3.

**Comment by ikitayama** [comment]
I'm doing it right now; is there a Spac command to remove the entry from packages.yaml?

**Comment by ikitayama** [comment]
Or better validat all the packages written in packages.yaml.

**Comment by adamjstewart** [comment]
There is no command to validate, since it can be arbitrary external packages which aren't in the `PATH`. You should be able to remove with `spack config remove packages:...:...`. Or you can add the correct version with `spack external find python`.

**Comment by ikitayama** [comment]
I did `spack install python@3.8.5` on the login node and did `spack external find`:

```
==> The following specs have been detected on this system and added to /home/hp200139/u00444/.spack/packages.yaml
findutils@4.5.11  ncurses@5.9.20130511  ruby@2.0.0
flex@2.5.37       python@3.8.5          texinfo@5.1
```

Now the package of interest `jube` builds fine.
Many thanks to @adamjstewart for guding me through to the perfect solution!

**Comment by adamjstewart** [comment]
If you're building Python with Spack, there's no reason to add it as an external package.
