### ISSUE TITLE
Is cuda package installed as if the NVIDIA provided install script does? 

### ISSUE THREAD

**Issue by ikitayama** [LLNL/spack#18882]
I'm asking this as I seem to have had the app run-time issue on ThunderX2 + V100 system.

@ax3l can you jump in and enlighten us?

**Comment by ax3l** [comment]
Hi @ikitayama,

I'll try my best.

What we do in the `cuda` package is take the [CUDA toolkit `runfile` scripts](https://developer.nvidia.com/cuda-downloads) and install them - minus the drivers - in user-land. The cuda toolkit is a large collection of compilers, some tools, and a lot of libraries that Nvidia bundles into one "release". Some of the packages you can also install independently again, e.g. if you need a newer or patched version of [cub](https://github.com/NVlabs/cub) or [thrust](https://github.com/NVIDIA/thrust#releases).

That means especially if you operate with Spack on a system, which pulls the latest cuda toolkit if you don't constrain it further, it's essential to have up-to-date drivers. Most CUDA operations (e.g. device context selection when starting up a CUDA app) should abort with a clear error message if the driver is too old for the toolkit the app was built against, but I am guessing a bit what the runtime issue is that you experience. Do you have more information on this?

**Comment by ax3l** [comment]
The `install(...):` method in the file opened with `spack edit cuda` is the main logic that is going on.

`spack install -v cuda@<some-version>` shows the exact commands we issue, e.g.:
```
spack install -v cuda@10.0.130
==> Installing cuda
==> No binary for cuda found: installing from source
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/92/92351f0e4346694d0fcb4ea1539856c9eb82060c25654463bfd8574ec35ee39a
##################################################################################################################################################################################################### 100.0%
==> cuda: Executing phase: 'install'
==> [2020-09-22-23:23:08.891309] '/bin/chmod' '+x' '/tmp/axel/spack-stage/spack-stage-cuda-10.0.130-hzeutlaubz7a7rjzadejx4pmfltddk34/spack-src/cuda_10.0.130_410.48_linux'
==> [2020-09-22-23:23:08.895330] '/tmp/axel/spack-stage/spack-stage-cuda-10.0.130-hzeutlaubz7a7rjzadejx4pmfltddk34/spack-src/cuda_10.0.130_410.48_linux' '--silent' '--override' '--toolkit' '--verbose' '--toolkitpath=/home/axel/src/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-8.4.0/cuda-10.0.130-hzeutlaubz7a7rjzadejx4pmfltddk34'
...
```
So in the case above: `download`, `chmod +x` and then calling `cuda_10.0.130_410.48_linux` with the silent installer flags.

**Comment by ikitayama** [comment]
I've reported this lockup issue to the LLVM OpenMP community and Joseph summarises:

"The runtime library just calls abort() immediately after printing that last "Failure while offloading was mandatory" message. I'm not sure what would be causing the process to hang after that if SIGABRT isn't being caught."

this is the situation I am seeing; this happens with Spack CUDA Toolkit or admin installed one regardless on AArch64.
The system went into `drain` state and admin has to reboot it, seems no other way.

**Comment by ax3l** [comment]
Hm, I am not too familiar with this.
Are you using Clang for OpenMP offloading?

Was that Clang/LLVM built with Spack and/or against the Spack CUDA package?

**Comment by ikitayama** [comment]
Yes, I'm using Clang for OpenMP offloading, the target device is V100. I believe that's the case though I am not so certain.

**Comment by ikitayama** [comment]
@ax3l -- after checking env vars `CUDA_HOME` and friends, I realized I did not use Spack `cuda` at all as they are
set to JURECA admins added values like:

`/usr/local/software/jureca/Stages/2019a/software/CUDA/10.1.105`

Envrioment modules set above env vars appropriately when the CUDA Toolkit module is loaded, but
what about Spack?

**Comment by ax3l** [comment]
Yes, Spack does not set that variable unless you configure it to do so. But it's also not really needed.

I think in order to help you further one would need more details: what are your loaded modules on the system and what configurations do you place in Spack's yaml files? Do you have a concrete reproducer code/mini-example, now did you built it and what was the exact error message you see at runtime?

The Clang that you use for OpenMP offloading: is that from the system or built with Spack? In the latter case, experts such as @trws (#14060) might be able to help further.

With respect to the mixed modules: You could try to set the CUDA package from the system module as external package (instead of downloading a CUDA with spack) and build against that in the next try.

(Alternatively, you can also try to ask the JURECA sysadmins for a cuda-enabled Clang compiler module with OpenMP offloading capabilities.)

**Comment by ikitayama** [comment]
Given that it's been a while since I've opened up this Issue, Spack and CUDA Toolkit both have changed a lot, closing this.
