### ISSUE TITLE
Installation issue: 

### ISSUE THREAD

**Issue by payerle** [LLNL/spack#18897]
I have labelled this as an issue with arpack-ng, as that is the package that I am having trouble building, but I suspect the underlying issue is with intel-mkl.

### Steps to reproduce the issue
I have installed intel-parallel-studio following instructions at https://spack.readthedocs.io/en/latest/build_systems/intelpackage.html#install-steps-for-packages-with-compilers-and-libraries.  I want to use fftw-api via MKL, but intel-parallel-studio does not support that, so I installed intel-parallel-studio with ~mkl and install intel-mkl separately, and then try to install arpack-ng.

```console
( add a stub entry for intel@20.0.1 in compilers.yaml)
$ spack install intel-parallel-studio@cluster.2020.1%intel@20.0.1 +advisor+clck+daal+gdb~ilp64+inspector+ipp+itac~mkl+mpi+newdtags+rpath+shared+tbb+vtune auto_dispatch=none threads=openmp
(this installs w/out issue.  Fix paths to compilers, etc in compilers.yaml)
$spack install intel-mkl@2020.1.217%intel@20.0.1   ~ilp64+shared threads=tbb
(this installs w/out issue)
$arpack-ng@3.7.0%intel@20.0.1 ~mpi+shared arch=linux-rhel8-ivybridge
(this fails with errors like)
/.../linux-rhel8-ivybridge/intel-20.0.1/intel-mkl-2020.1.217-.../compilers_and_libraries_2020.1.217/linux/mkl/lib/intel64/libmkl_tbb_thread.so: undefined reference to `tbb::task_group_context::cancel_group_execution()
```
My environment includes
```console
providers:
      blas: [intel-mkl]
      fftw-api: [intel-mkl]
      mkl: [intel-mkl]
      lapack: [intel-mkl]
      scalapack: [intel-mkl]
      tbb: [intel-parallel-studio+tbb]
```
so intel-mkl is used for blas/lapack/et al, and intel-parallel-studio for tbb.

It looks like intel-mkl has a dependency on tbb (which is expected since I gave it threads=tbb), but it is not declaring it in spack (i.e. spack info intel-mkl does *not* show a tbb dependence).

The IntelPackage build system is a bit overwhelming to me, but I tried adding a simple depends_on clause to depend on tbb when threads=tbb to the intel-mkl package.py, but in that test case the spec wanted intel-tbb (despite my environment stating I wanted intel-parallel-studio to provide tbb).  

1) Shouldn't intel-mkl threads=tbb depend on tbb?
2) How does one fix the issue with unresolved tbb symbols in libmkl_tbb_thread.so?
### Information on your system

```console
spack debug report
* **Spack:** 0.14.2
* **Python:** 3.6.8
* **Platform:** linux-rhel8-ivybridge
```
My environment's spack.yaml includes
```consoleackages:
  all:
    compiler:: [intel@20.0.1]
    providers:
      blas: [intel-mkl]
      fftw-api: [intel-mkl]
      mkl: [intel-mkl]
      lapack: [intel-mkl]
      scalapack: [intel-mkl]
      daal: [intel-parallel-studio+daal]
      ipp: [intel-parallel-studio+ipp]
      tbb: [intel-parallel-studio+tbb]
      ...
```
and the full spec of the arpack-ng I am installing is:
[spec.txt](https://github.com/spack/spack/files/5269999/spec.txt)

### Additional information

* [spack-build-env.txt](https://github.com/spack/spack/files/5270001/spack-build-env.txt)
* [spack-build-out.txt](https://github.com/spack/spack/files/5270002/spack-build-out.txt)

I cannot find any maintainers for arpack-ng, intel-mkl, or intel-parallel-studio

### General information

- [x ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x ] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x ] I have uploaded the build log and environment files
- [x ] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Is this an accidental duplicate of #18896?

**Comment by payerle** [comment]
Sorry, must have accidentally submitted twice.
