### ISSUE TITLE
should we add sbin directory to environment by default if it exist.

### ISSUE THREAD

**Issue by darmac** [LLNL/spack#18905]
I found many packages output its binary to a `sbin` directory, but in spack, we only add `bin` to `PATH`, should we add `sbin` to `PATH` too by default?

**Comment by adamjstewart** [comment]
Based on a quick google search (https://superuser.com/q/595818/550210, https://askubuntu.com/q/972611/548115), it seems that it isn't recommended to add `sbin` to the `PATH` for normal users. That's why the executables are installed in `sbin` instead of `bin`.

**Comment by glennpj** [comment]
I have been wanting to ask, is there a reason why spack is bringing in a lot of system/distribution level packages?

**Comment by darmac** [comment]
@glennpj  We have a lot of packages which need to build, run and verify in different distribution, and we think spack is a perfect tool to make it easily.
And also, sometimes we need some new version for these packages.

**Comment by darmac** [comment]
@adamjstewart  got it, thanks for your guidance.
