### ISSUE TITLE
Future of Classic Flang Spack package

### ISSUE THREAD

**Issue by naromero77** [LLNL/spack#18944]
@junghans Would it be acceptable to merge the `pgmath` Spack package into the main `flang` Spack package? This may neccesitate a few changes to the classic flang build system which I am trying to sort out. It would make it easier for me to maintain it.

**Comment by junghans** [comment]
Sure, go ahead

**Comment by naromero77** [comment]
Apologies for re-using the open github issue. I welcome input.

@trws @adamjstewart @gklimowicz @junghans

I get pinged a couple of times a month about the "classic" Flang package. It appears to be mostly by people who are interested in a Fortran compiler with Target offload capabilities. "classic" Flang continues to be developed by several vendors and will be official released under their own brandings (ARM, AMD, etc.), however there are no planned official releases for the open source repo. moving forward. This makes it difficult to maintain and is potential confusing to Spack users who are expecting a certain level of support.

I would like to throw out a couple of options w.r.t. to the Spack packages (flang, pgmath, llvm-flang)
1.  Mark the these packages as deprecated or no support.
2. Delete the following packages from Spack: flang, pgmath, llvm-flang. 

As a reminder, eventually will see a fully functional f18 that will be part of the main llvm Spack package -- and that will have official releases.

**Comment by adamjstewart** [comment]
I don't know anything about compilers, but I assume Apple has no intention of ever shipping a Fortran compiler to go along with Apple Clang. For now I've been using GFortran as my Fortran compiler, but would it make more sense to suggest that users use Flang? If so, which package would they use? Building all of GCC/LLVM just to get a Fortran compiler is unideal...

**Comment by naromero77** [comment]
Apple has no plans to to ever ship a Fortran compiler. Flang will not compile with Apple's Clang and there are no plans to support it AFAIK.

The Flang Spack package currently requires compiling its own custom LLVM flang which is modified from the LLVM and is typically a few releases behind. Right now it uses LLVM 9, though they are transitioning to LLVM 10. The main LLVM package is about to release LLVM 11.

Fortran on Apple has always been a pain. Does GCC build with Apple's Clang?

**Comment by adamjstewart** [comment]
GCC does build with Apple Clang, and lets me compile anything I need. It sounds like Flang isn't an option for Apple Clang users then, which answers my question. I'll let other people comment, but from my point of view, I'm fine with removing those packages and building everything in the LLVM package.

**Comment by naromero77** [comment]
My inclination is to remove these packages as well.

**Comment by naromero77** [comment]
FYI: At the Flang group meeting, Oct. 14, we talked about deleting the package and everyone was on board with the decision.
