### ISSUE TITLE
Version conflicts in concretizer

### ISSUE THREAD

**Issue by sethrj** [LLNL/spack#18958]
The ForTrilinos package uses a couple of SemVer (but not PEP-440) compatible version numbers such as `2.0.0-dev3` building up to a `2.0.0` release. Each of these dev versions requires a slightly different version of Trilinos, encoded as:
```
    depends_on('trilinos@13:', when='@2.0.0:')
    depends_on('trilinos@12.18.1', when='@2.0.0-dev3')
```

however, the concretizer rejects this:
```
==> Error: Conflicting conditional dependencies for spec

	fortrilinos@2.0.0-dev3 ^cmake

Cannot merge constraint

	trilinos@12.18.1

into

	trilinos@13:
```

A possibly similar issue I hit (#17145) earlier indicates the concretizer might have trouble with unusual versions.

### Steps to reproduce the issue

```console
$ spack spec -I fortrilinos@2.0.0-dev3 ^trilinos@12.18.1+nox+stratimikos
...
```

### Information on your system

```
$ spack debug report
* **Spack:** 0.15.4-1165-5f87c7795
* **Python:** 3.7.1
* **Platform:** darwin-mojave-skylake
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by sethrj** [comment]
Another related issue, and possibly the common denominator here: `foo@:1.2.3` matches *any* version name/tag that's not `master` or other special cases. So if the package recipe has limitations for very old pieces of code, it will also match against other unrelated version tags.

**Comment by adamjstewart** [comment]
One workaround would be to use:
```python
depends_on('trilinos@13:', when='@2.0.0,2.0.1:')
depends_on('trilinos@12.18.1', when='@2.0.0-dev3')
```

**Comment by sethrj** [comment]
After further examination this is just a byproduct of the difficulty of "generic" (non-semantic) version comparison, and https://github.com/spack/spack/pull/20695 has a suitable workaround: after experimenting I found `Version('2.0.dev1') < Version('2.0.0')`.
