### ISSUE TITLE
slate: missing header files

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#18978]
Using `spack@develop` (ac7c69e62e61b0a45344690a8ede29f064f8fed5, 2020-09-25 ~1515) and trying to install+use `slate@develop` (cloned 2020-09-25) on:
* `Ubuntu 18.04`
* `X86_64`
* Built with `gcc@7.5.0`

I think there are some missing header files from the `slate` install:

```
$> spack install slate target=x86_64
....
==> Installing slate
==> slate: Executing phase: 'install'
[+] /opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/slate-develop-zm6eauz2qzguhk55psb7rwn6qbicbb5w
```

```
$> grep include `spack location -i slate`/include/slate.hh
#include "slate/Matrix.hh"
#include "slate/HermitianMatrix.hh"
#include "slate/SymmetricMatrix.hh"
#include "slate/TriangularMatrix.hh"
#include "slate/BandMatrix.hh"
#include "slate/TriangularBandMatrix.hh"
#include "slate/HermitianBandMatrix.hh"
#include "slate/types.hh"
#include "simplified_api.hh"
```

These are the only header files present:
```
$> ls `spack location -i slate`/include
slate.hh  slate_lapack_api.hh  slate_scalapack_api.hh
```

Looks like all the header files under `slate/...` are missing:
* slate/Matrix.hh
* slate/HermitianMatrix.hh
* slate/SymmetricMatrix.hh
* ...

@G-Ragghianti @coti

**Comment by G-Ragghianti** [comment]
Hi Eugene.  I think these "missing" header files are only required for building slate.  For building _against_ slate, you only need the three header files that are installed. during the "make install" process.  Are you actually experiencing a problem related to this?

**Comment by G-Ragghianti** [comment]
After looking at this a bit more closely, I think I will consult the devs as to whether there was a reorganization of the header files.

**Comment by eugeneswalker** [comment]
Thanks for the quick response! 

This was the simple example I was trying:

<b>slate-test.cpp</b>
```
#include <iostream>
#include <mpi.h>
#include <slate.hh>

#define DEFAULT_M  256
#define DEFAULT_N  256

int main( int argc, char** argv ){
  int M, N, provided;

  M = DEFAULT_M;
  N = DEFAULT_N;

  MPI_Init_thread( &argc, &argv, MPI_THREAD_FUNNELED, &provided )
  slate::Matrix<double> A( M, N, 1, 1, 1, 1, MPI_COMM_WORLD );
  MPI_Finalize();

  return EXIT_SUCCESS;
}
```

```
$> mpicxx slate-test.cpp -lslate
In file included from slate-test.cpp:3:0:
/opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/slate-develop-jnysy2rh5vxhwua5ubtvq4bsfd3py7d5/include/slate.hh:43:10: fatal error: slate/Matrix.hh: No such file or directory
 #include "slate/Matrix.hh"
          ^~~~~~~~~~~~~~~~~
compilation terminated.
```
