### ISSUE TITLE
Merge commands with overlapping responsibilities

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#1907]
I was wondering if anybody else was in favor of merging :

- [x] `spack package-list` in `spack list`
- [x] `spack test-install` in `spack install`

and demote them from full commands to flags in another command. If there's agreement I'll start working on it.

**Comment by adamjstewart** [comment]
`spack package-list` isn't used by anyone except the documentation, so I don't think anyone will mind that. It's the same idea as `spack list`, just combining `spack list` and `spack info` and outputting to .rst format, so it would make sense to combine into `spack list --rst|-r`

I've never used `spack test-install` before, so I have no opinions on that. Honestly, I don't even know what it does.

**Comment by alalazo** [comment]
> I've never used spack test-install before, so I have no opinions on that. Honestly, I don't even know what it does.

Same as install, but activates `-v` and produces JUnit output (useful if Spack is driven by some CI framework rather than a person)

**Comment by citibeth** [comment]
Both changes sound reasonable to me.

**Comment by adamjstewart** [comment]
When you do get around to this, can you split your changes up into 2 PRs (one for package-list and one for test-install)? That would make it easier to review.
