### ISSUE TITLE
run-flake8 confused when packages change name

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#1910]
@adamjstewart I renamed a package, then ran `run-flake8`.  It got confused and tried to run `flake8` on the old package name, which no longer existed; hence, it caused an error.  This was fixed by checking in my pending commit with `git`.  Then everything worked smoothly again.

I would not spend effort trying to "fix" this issue.  I would add it as a note to the docs on the unit tests.

**Comment by adamjstewart** [comment]
@citibeth Fixed in #1837. I assume you are on an old branch?

**Comment by citibeth** [comment]
Yes, probably.
