### ISSUE TITLE
Warning when deactivating environment with external repos

### ISSUE THREAD

**Issue by mdorier** [LLNL/spack#19126]
I have a spack environment described in a spack.yaml file. This file includes the following entry:

```
spack:
  ...
  repos:
  - /ccs/home/mdorier1/sds-repo # adds the mochi namespace to spack
```

This external repository is known to this environment, but is not in my `~/.spack/repos.yaml` file, which allows me to use it within the environment without making it global to all environments.

When I call `spack env deactivate` to deactivate this environment however, I am getting the following warning message.

```
==> Warning: Unknown namespace: mochi
==> Warning: Could not fully deactivate view due to missing package or repo, shell environment may be corrupt.
```

I think spack should be able to take this scenario into account and properly deactivate the environment even if it uses an external repo.

**Comment by alalazo** [comment]
Cannot reproduce as of:

* **Spack:** 0.21.0.dev0 (64c6d63675f8e45e0be12a9c55acb4b7969e383a)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo
![Screenshot from 2023-07-11 10-11-45](https://github.com/spack/spack/assets/4199709/d860f54e-3786-47e6-ba17-896394f724a3)
