### ISSUE TITLE
using a non-default OS compiler for building images with Spack

### ISSUE THREAD

**Issue by ravil-mobile** [LLNL/spack#19163]
### Description

Hi all, 

I would like to create a docker image and build a set of packages with Spack using a non-default OS compiler. In short, I would like Spack to install a compiler first, add it to a list of compilers and use it to install the rest of a spec. Unfortunately, I can not find an example. 

Building Images with Spack is based on the environment concept. However, the concept assumes that a desired compiler has already been installed and added to Spack before an environment is concretized. My question is whether there is a solution for such a problem?

The one that I personally found is the following: 1) Create a docker file which is going be based of the Spack builder-image 2) install and add a compiler to Spack inside of my builder-image 3) build the image and use it as my custom builder for the rest of a spec

However, the last part of step 3 would require to use a regular expression in order to find and substitute *FROM **spack/ubuntu-bionic:latest** as builder* to something like *FROM **builder-image:latest** as builder*

### General information

- [ ] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by ravil-mobile** [comment]
There is an additional question: how to add the compiler from my custom builder-image to the final image?

**Comment by healther** [comment]
Something like
```
spack install <yourdesiredcompiler>
spack compiler remove
spack compiler add `spack find -p <yourdesiredcompiler>`
spack env activate <yourenv>
spack concretize
spack install
spack view add <yourdesiredcompiler> <pathtotheviewofyourenv>
```
would probably work. What you _really_ want to do is probably is to use the `spack containerize` command, but I don't know enough about this. Except for the environment usage the above is roughly what we are doing internally, but it is a bit painful since you need to do the compiler addition manually afterwards

**Comment by ravil-mobile** [comment]
Hi,
Thanks for your reply. Yes, your solution is perfect for building environments. But it doesn't work with `spack containerize`. Basically `spack containerize` spits out a dockerfile. At the beginning, it  copies my spack.yaml to a container and executes 

```
spack concretize
spack install
spack view add <yourdesiredcompiler> <pathtotheviewofyourenv>
```

there is no way to insert any-code above without editing a dockerfile.

**Comment by healther** [comment]
I haven't looked into `containerize` too closely, so I cannot really help you there. But you can always do the view generation manually

**Comment by wdconinc** [comment]
This seems like it works:
```yaml
spack:
  specs:
  - libelf %gcc@10.2.0
  config:
    install_missing_compilers: true
```
Key line is `install_missing_compilers`.

Maybe there's a way to add this to the [docs](https://spack.readthedocs.io/en/latest/containers.html). A new section seems too much, but I couldn't identify an existing example to add it to either.

**Comment by ravil-mobile** [comment]
Hi, 

Can I ask you whether `install_missing_compilers: true` is going to install and immediately use a missing compiler? If it does then it is very really cool! 

I still have one concern which I wanted make as a proposal to Spack with respect to building images. So, here is the problem. An installation of a spec results in a single RUN docker command. This command (building step) inherently takes lot's of time because Spack installs everything from sources. If something goes wrong with a spec installation then the command gets aborted, a user needs to fix something in his/her spec and try again. There is a crucial point, namely: in case of a failure, the aforementioned building step is not cached in docker and thus Spack is going to start building all the stuff, including a missing compiler, again from scratch. If a compiler installation is moved to a separate RUN command then a user can save lot's of time due to docker caching (especially while doing multi-arch builds with `docker buildx`)

I solved this problem by splitting my build into building two images. The first one installs only a compiler. For example:
```
$ cat Dockerfile.compiler
FROM ravilmobile/spack-ubuntu-1804:latest

# setup a default installation path
RUN (echo "config:" \
&&   echo "  install_tree:" \
&&   echo "    root: /opt/software") > .spack/config.yaml

# install compiler
RUN spack install gcc@8.3.0 arch=x86_64 +piclibs \
&& spack compiler add $(spack location -i gcc@8.3.0) \
&& spack gc -y

# is going to be built as following:
# docker build -t ravilmobile/compiler:gcc8.3.0 -f <path>/Dockerfile.compiler .
```
and the second one installs the rest of my spec
```
spack:
  definitions:
  - compilers: [gcc@8.3.0]
  - mpis: <my mpi spec>
  - targets: [target=x86_64]
  - packages: 
      - <a long list of packages>

  specs:
  - matrix:
    - [\$packages]
    - [\$targets]
    - [\$^mpis]
    - [\$%compilers]
 
  container:
    format: docker

    images:
      build: ravilmobile/compiler:gcc8.3.0
      final: ubuntu:18.04
    strip: true

    ...
```

So, there is a solution that I have in mind. First of all, one needs to add the following into the base [Spack Dockerfile](https://github.com/spack/spack/blob/develop/share/spack/docker/ubuntu-1804.dockerfile):
```
RUN (echo "config:" \
&&   echo "  install_tree:" \
&&   echo "    root: /opt/software") > .spack/config.yaml
```
because Spack always inserts `spack gc -y` which calls the garbage collector.

Secondly, one should add an ability to insert custom pre-install steps above the following: 
```
RUN cd /opt/spack-environment && spack env activate . && spack install --fail-fast && spack gc -y
```
Spack has a similar feature but for inserting post-install steps:
```
extra_instructions:
        build: ...
        final: ...
```
I think it may be extended. I can see that everything boils down to augmenting [Dockerfile Jinja template](https://github.com/spack/spack/blob/develop/share/spack/templates/container/Dockerfile).

**Comment by wdconinc** [comment]
Getting off topic, but `extra_instructions: prepare:` could be useful. Docker buildkit has caching: `RUN --mount=type=cache,target=/opt/software`. Maybe `extra_instructions: cache:` for that.

**Comment by alalazo** [comment]
I think this https://github.com/spack/spack/pull/35187 solves the issue of customizing the Dockerfile. Closing the issue, but feel free to open a new one if you think anything still needs a resolution.
