### ISSUE TITLE
Intel 2020.09.15.001 misidentified as Intel<11.1?

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#19216]
Using `spack@develop` (d43522deeb4af2f435aaa920c266f8282a815f72 from 6-Oct-2020) on `JLSE Iris` and it *looks* like `Intel@2020.09.15.001` is being misidentified as an Intel < 11.1, and is thus unable to use `cxx11_flag` ??

```
$> spack compilers
...
-- intel opensuse_leap15-x86_64 ---------------------------------
intel@2020.09.15.001
```

```
$> spack install superlu-dist%intel ^m4%gcc
...
==> Installing superlu-dist
==> No binary for superlu-dist found: installing from source
==> Error: UnsupportedCompilerFlag: intel (< 11.1) does not support the C++11 standard (as compiler.cxx11_flag).
    If you think it should, please edit the compiler.intel subclass to implement the cxx11_flag property and submit a pull request or issue.

/home/eugeneswalker/spack/var/spack/repos/builtin/packages/superlu-dist/package.py:89, in flag_handler:
         86    def flag_handler(self, name, flags):
         87        flags = list(flags)
         88        if name == 'cxxflags':
  >>     89            flags.append(self.compiler.cxx11_flag)
         90        if name == 'cflags' and '%pgi' not in self.spec:
         91            flags.append('-std=c99')
         92        return (None, None, flags)
```

Any ideas?

@becker33 @shahzebsiddiqui @frankwillmore

**Comment by frankwillmore** [comment]
Spack runs e.g. icc --version to get info from the compiler that it uses to determine capabilities. It parses the output with a regular expression, but the OpenAPI compilers generate an output that the same Regex can't parse. I'm looking into a fix.

**Comment by frankwillmore** [comment]
Good news, everyone! 

I worked in a modified regular expression to parse the oneapi output and was able to get to get superlu-dist to build with both the oneapi toolset (intel@2020.09.15.001) and Intel version @19.0.4.243.  I need to clean it up a bit, but should have a pull request ready shortly. 

This is my first time foray into a real-world python code... very exciting for me.

**Comment by frankwillmore** [comment]
https://github.com/spack/spack/pull/19238

I've cleaned up, commented, and verified this mod still builds superlu-dist with both Intel versions.

**Comment by frankwillmore** [comment]
https://github.com/spack/spack/pull/19330 supersedes 19238 and declares a oneapi compiler class.
