### ISSUE TITLE
SZ: bad source fetch url for older versions

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#19213]
Unable to fetch older versions of `sz` using `spack@develop` (6b70597271232e442b9e729b45adaee02bccf8c0 from 6-Oct-2020):

* `sz@2.0.2.0`
* `sz@1.4.12.3`

Probably introduced via eabfea2e49f6db473401b29ca80966f41a7e7c23

```
$> spack install sz@2.0.2.0
...
==> Installing sz
==> No binary for sz found: installing from source
==> Error: FetchError: All fetchers failed

/opt/spack/lib/spack/spack/package.py:1262, in do_fetch:
       1259                                 self.spec.format('{name}{@version}'), ck_msg)
       1260
       1261        self.stage.create()
  >>   1262        err_msg = None if not self.manual_download else self.download_instr
       1263        self.stage.fetch(mirror_only, err_msg=err_msg)
       1264        self._fetch_time = time.time() - start_time
       1265
```

Same outcome for `sz@1.4.12.3`

@scottwittenburg @disheng222 @robertu94

**Comment by disheng222** [comment]
Hi,
I checked that the .tar.gz package on the SZ website is available to
download and its checksum in the package.py is also correct for 1.4.12.3.
I have no idea what I should do.

Best,
Sheng

**Comment by robertu94** [comment]
@eugeneswalker it works for me.  Perhaps a spurious failure?

```console
[runderwood@voyager experiments]$ spack install sz@2.0.2.0
==> cmake@3.18.1 : externally installed in /usr
[+] /usr
[+] /home/runderwood/git/contrib/spack/opt/spack/linux-gentoo2-skylake/gcc-10.1.0/zlib-1.2.11-x5whpcbwrkid4b7itid7euanufvg4pyy
==> Installing zstd
==> No binary for zstd found: installing from source
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/73/734d1f565c42f691f8420c8d06783ad818060fc390dee43ae0a89f86d0a4f8c2.tar.gz
########################################################################################################################################### 100.0%
==> zstd: Executing phase: 'edit'
==> zstd: Executing phase: 'build'
==> zstd: Executing phase: 'install'
[+] /home/runderwood/git/contrib/spack/opt/spack/linux-gentoo2-skylake/gcc-10.1.0/zstd-1.4.5-ymj3vwmm6hk6n2otwsdl4blvprtbxxr5
==> Installing sz
==> No binary for sz found: installing from source
==> Fetching https://github.com/disheng222/SZ/archive/v2.0.2.0.tar.gz
########################################################################################################################################### 100.0%            -=O=-              #         #         #          #                                                                                  
==> sz: Executing phase: 'cmake'
==> sz: Executing phase: 'build'
==> sz: Executing phase: 'install'
[+] /home/runderwood/git/contrib/spack/opt/spack/linux-gentoo2-skylake/gcc-10.1.0/sz-2.0.2.0-qekt6lyx3dzot7ggcm7vkjmmigyorvrq
[runderwood@voyager experiments]$ spack install sz@1.4.12.3 
==> cmake@3.18.1 : externally installed in /usr
[+] /usr
[+] /home/runderwood/git/contrib/spack/opt/spack/linux-gentoo2-skylake/gcc-10.1.0/zlib-1.2.11-x5whpcbwrkid4b7itid7euanufvg4pyy
[+] /home/runderwood/git/contrib/spack/opt/spack/linux-gentoo2-skylake/gcc-10.1.0/zstd-1.4.5-ymj3vwmm6hk6n2otwsdl4blvprtbxxr5
==> Installing sz
==> No binary for sz found: installing from source
==> Fetching https://github.com/disheng222/SZ/archive/v1.4.12.3.tar.gz
########################################################################################################################################### 100.0%########################################################################################################################################### 100.0%       -=O=-#      #       #         #                                                                                                           
==> sz: Executing phase: 'cmake'
==> sz: Executing phase: 'build'
==> sz: Executing phase: 'install'
[+] /home/runderwood/git/contrib/spack/opt/spack/linux-gentoo2-skylake/gcc-10.1.0/sz-1.4.12.3-mlsltrfajlmq6ph4el5cjavfeyfn35zo
```

**Comment by eugeneswalker** [comment]
> ==> Installing sz
> ==> No binary for sz found: installing from source
> ==> Fetching https://github.com/disheng222/SZ/archive/v1.4.12.3.tar.gz

Your Spack instance is fetching from:
* `https://github.com/disheng222/SZ/archive/v1.4.12.3.tar.gz`

That source url was changed to:
* https://github.com/szcompressor/SZ/releases/download/

via https://github.com/spack/spack/commit/eabfea2e49f6db473401b29ca80966f41a7e7c23

I think if you make sure your Spack instance is checked out at a point past this commit then you will observe the problem.

**Comment by disheng222** [comment]
- https://github.com/disheng222/SZ/archive/v1.4.12.3.tar.gz should be
   available too, because github will automatically resolve the redirecting.

Best,
Sheng

**Comment by eugeneswalker** [comment]
> - https://github.com/disheng222/SZ/archive/v1.4.12.3.tar.gz should be available too, because github will automatically resolve the redirecting

@adamjstewart Do you know anything about this behavior? It isn't working for me and I've tried on:
* RHEL7 x86_64 and ppc64le
* Ubuntu 18.04 x86_64 and ppc64le

Also the versions of `SZ` needed in the E4S `gitlab.spack.io` pipeline are failing because of this fetch error.

Perhaps Spack is not doing the fetch in a way that can handle the redirection @disheng222 mentions?

**Comment by eugeneswalker** [comment]
> - https://github.com/disheng222/SZ/archive/v1.4.12.3.tar.gz should be available too, because github will automatically resolve the redirecting.

```
$> spack fetch sz@1.4.12.3
...
==> [2020-10-06-21:56:29.213582] Fetching from https://github.com/szcompressor/SZ/releases/download/v1.4.12.3/sz-1.4.12.3.tar.gz failed.
==> [2020-10-06-21:56:29.213785] FetchError: All fetchers failed
==> [2020-10-06-21:56:29.213911] Error: All fetchers failed
Traceback (most recent call last):
  File "/opt/spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/opt/spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/opt/spack/lib/spack/spack/cmd/fetch.py", line 53, in fetch
    package.do_fetch()
  File "/opt/spack/lib/spack/spack/package.py", line 1263, in do_fetch
    self.stage.fetch(mirror_only, err_msg=err_msg)
  File "/opt/spack/lib/spack/spack/util/pattern.py", line 68, in getter
    getattr(item, self.name)(*args, **kwargs)
  File "/opt/spack/lib/spack/spack/stage.py", line 490, in fetch
    raise fs.FetchError(err_msg or 'All fetchers failed', None)
spack.fetch_strategy.FetchError: All fetchers failed
```

Notice the URL used is `https://github.com/szcompressor/SZ/releases/download/v1.4.12.3/sz-1.4.12.3.tar.gz` -- this is the URL being tried, and it is failing. 

Trying manually:
```
$> wget https://github.com/szcompressor/SZ/releases/download/v1.4.12.3/sz-1.4.12.3.tar.gz
--2020-10-06 22:07:04--  https://github.com/szcompressor/SZ/releases/download/v1.4.12.3/sz-1.4.12.3.tar.gz
Resolving github.com (github.com)... 192.30.255.112
Connecting to github.com (github.com)|192.30.255.112|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-10-06 22:07:05 ERROR 404: Not Found.
```

**Comment by robertu94** [comment]
@eugeneswalker updated my git repo and was able to replicate this issue.  Just submitted the PR to fix this.  Thanks for catching that.

**Comment by disheng222** [comment]
@eugeneswalker <https://github.com/eugeneswalker> It's a little bit weird
that you used the old link of SZ, though the old link (
http://github.com/disheng222/SZ) should be workable.
In fact, we revised the package.py of SZ so it is using an official github
site (http://github.com/szcompressor/SZ) we created recently.
Did you 'git pull'?

Best,
Sheng

**Comment by eugeneswalker** [comment]
> @eugeneswalker <https://github.com/eugeneswalker> It's a little bit weird that you used the old link of SZ, though the old link ( http://github.com/disheng222/SZ) should be workable. In fact, we revised the package.py of SZ so it is using an official github site (http://github.com/szcompressor/SZ) we created recently. Did you 'git pull'?

This is the new link that *CURRENT* Spack is using:
* `https://github.com/szcompressor/SZ/releases/download/v1.4.12.3/sz-1.4.12.3.tar.gz`

It does not work.

**Comment by disheng222** [comment]
@eugeneswalker <https://github.com/eugeneswalker> We are solving the
problem. The reason is that the previous versions did not use the download
asset link, which was used from version 2.1.9.
I have added all the download asset versions on the SZ-github, and Robert
will add `url_for_version` in the package.py to compute the right URLs, so
the problem will be fixed soon.

Best,
Sheng
