### ISSUE TITLE
Installation issue: py-pillow-simd

### ISSUE THREAD

**Issue by AndrewGaspar** [LLNL/spack#19250]
py-pillow-simd does not build on powerpc64le due to -msse4 flag being incorrectly applied.

### Steps to reproduce the issue

```console
$ spack install py-pillow-simd
...
     19    /home/agaspar/spack/lib/spack/env/gcc/gcc -Wno-unused-result -Wsign-comp
           are -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -fPIC -DHAVE_LIBJPEG -DHAVE_LIBZ
            -DPILLOW_VERSION="7.0.0.post3" -I/home/agaspar/spack/opt/spack/linux-rh
           el7-power9le/gcc-7.4.0/python-3.8.5-bvt4tu23blr4jgq45j5gxnkmgzhjhumr/inc
           lude/python3.8 -I/home/agaspar/spack/opt/spack/linux-rhel7-power9le/gcc-
           7.4.0/zlib-1.2.11-fkwiwuhquvi2cpy3xjyre6fvxz36cbiw/include -I/home/agasp
           ar/spack/opt/spack/linux-rhel7-power9le/gcc-7.4.0/libjpeg-turbo-2.0.4-yh
           hvmbonzgpnp3buiyesk4go4yipqhlm/include -I/ram/tmp/agaspar/spack-stage/sp
           ack-stage-py-pillow-simd-7.0.0.post3-ocscvbije5ae7uimc2dqeet3gmgokw42/sp
           ack-src/src/libImaging -I/ram/tmp/agaspar/spack-stage/spack-stage-py-pil
           low-simd-7.0.0.post3-ocscvbije5ae7uimc2dqeet3gmgokw42/spack-src -I/home/
           agaspar/spack/opt/spack/linux-rhel7-power9le/gcc-7.4.0/python-3.8.5-bvt4
           tu23blr4jgq45j5gxnkmgzhjhumr/include -I/usr/local/include -I/usr/include
            -I/home/agaspar/spack/opt/spack/linux-rhel7-power9le/gcc-7.4.0/python-3
           .8.5-bvt4tu23blr4jgq45j5gxnkmgzhjhumr/include/python3.8 -c src/_imaging.
           c -o build/temp.linux-ppc64le-3.8/src/_imaging.o -msse4
  >> 20    gcc: error: unrecognized command line option '-msse4'; did you mean '-mi
           sel'?
...
```

### Information on your system

```console
* **Spack:** 0.15.4-1452-0d75636a3
* **Python:** 3.8.5
* **Platform:** linux-rhel7-power9le
```

### Additional information

- [spack-build-out.txt](https://github.com/spack/spack/files/5357342/spack-build-out.txt)
- [spack-build-env.txt](https://github.com/spack/spack/files/5357344/spack-build-env.txt)

cc @adamjstewart 

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by AndrewGaspar** [comment]
I'll switch to `py-pillow`, btw. It will probably fix my issue.

**Comment by adamjstewart** [comment]
Thanks for the report! Yes, I imagine switching to `py-pillow` will solve the issue for you. I'm not aware of a way to set the default provider based on target, only based on platform.

Is building on ppc64le something you think should be supported by a SIMD package, or does that not make sense? Maybe open an issue with the developers and ping me. I would like our default provider to build on all platforms if possible. Pillow-SIMD is supposed to be over an order of magnitude faster than Pillow as long as you can get it to build.

**Comment by AndrewGaspar** [comment]
Sure, ppc64le architectures support vector, as do some ARM architectures, but taking a brief look at the library, it seems like a pretty big lift to support non Intel architectures - it doesn't seem like there's a non-SIMD fallback. I don't think pillow-simd is baked enough to be the default on non-Intel platforms.

A possible idea - you could remove the `provides('pil')` from `py-pillow` and `py-pillow-simd` and then add a new empty package that simply indirects to either based on some variant, with the default behavior being to select the "simd" implementation on Intel platforms and the non-simd on other platforms.

**Comment by AndrewGaspar** [comment]
They could potentially use this to at least be portable to other platforms: https://github.com/p12tic/libsimdpp

**Comment by AndrewGaspar** [comment]
nvm, that lib doesn't seem to do what I though it did - I thought it re-implemented the vector intrinsics. I don't see any evidence of that - it just provides generic SIMD routines. And it sounds like it was already considered and rejected: https://github.com/uploadcare/pillow-simd/issues/3

**Comment by AndrewGaspar** [comment]
Actually, THIS is the library I was thinking of: https://github.com/simd-everywhere/simde

**Comment by AndrewGaspar** [comment]
Yeah, it looks promising - I see pretty widespread SIMD intrinsic implementations. If you were so inclined, I'd see if you could get pillow-simd working using simde on non-linux platforms.

**Comment by adamjstewart** [comment]
Thanks for the summary! In that case, I think it makes sense to switch the default back to `py-pillow`. Want to submit a PR and have it close this issue? Just ping me and I'll merge.

**Comment by adamjstewart** [comment]
As for your idea of having a `pil` meta-package that selects `py-pillow` or `py-pillow-simd` based on variants, I don't think that's possible since there is currently no way to choose versions based on variants.
