### ISSUE TITLE
Compilers: Update LLVM support for version 11 with flang built-in

### ISSUE THREAD

**Issue by nicholas-sly** [LLNL/spack#19277]
### Flang support

This involves two high-level tasks.

1. Update the "clang" compiler object in Spack to find and use the flang compiler for fortran by default

2. Update the LLVM package.py to include the latest version (11) and have the ability to utilize the flang/f18 that is now included in LLVM.  

### Rationale

Take advantage of LLVM's Fortran compiler in order to not have to add gfortran to the compilers.yaml configuration after install.

### Description

Task 1: Add executable names and ensure version checks work for flang

Task 2: Include a new variant to utilize flang/f18 (or disable it's use) and install accordingly.

### Additional information
https://releases.llvm.org/11.0.0/docs/ReleaseNotes.html

### General information

- [ ] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by tomgreen66** [comment]
Have made changes to get add flang (and to detect gcc install prefix using print-search-dirs) to local copy.  From what I can see flang support seems to be there now.  Any special issues with this setup?
