### ISSUE TITLE
Newer preseq versions use a different build system

### ISSUE THREAD

**Issue by birnbera** [LLNL/spack#19298]
I was trying to update the [`preseq` package](var/spack/repos/builtin/packages/preseq/package.py) to the latest version and found that the newer releases have updated their build system from a simple Makefile to Autotools. Is there any recommended way to make the build system depend on the version?

I can think of two methods:
1. Convert the package to use a custom build system and specify a different set of build steps depending on the version.
2. Do something wacky with metaclasses to choose the base class dynamically depending on the version.

Is there a middle road?

**Comment by adamjstewart** [comment]
Congratulations, you've stumbled on a really difficult problem we've been trying to solve for years. See #15420, #12941, and #10411 for the long and bloody history.

For now, until one of those PRs becomes the new standard, the best way is probably to use your first suggestion. There are a ton of packages in Spack that already do this. See https://github.com/spack/spack/pull/12941#issuecomment-538105434 for a list of packages that are worth looking at to see how we've handled this before.

**Comment by birnbera** [comment]
Thanks for your suggestions and pointers! A lot of great ideas in the linked issues. As per your suggestion I used some of the other packages that made this type of transition as a guide (particularly the `hpl` package). Cheers!

**Comment by adamjstewart** [comment]
I finally got around to documenting this! Can you see if #25174 does a good job of explaining how to support multiple build systems? If anything is unclear, let me know and I'll try to improve the docs.
