### ISSUE TITLE
Recommend switch in szip package

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/spack#19328]
Just learned in HDF5 User's Group that upcomming releases will utilize a [BSD-2 Clause licensed](https://gitlab.dkrz.de/k202009/libaec/-/blob/master/Copyright.txt) version of [szip](https://gitlab.dkrz.de/k202009/libaec).

The BSD licensing of this version IMHO makes it more attractive for spack. 

The [existing version](https://support.hdfgroup.org/doc_resource/SZIP/) Spack builds supports only non-commercial use.

**Comment by skosukhin** [comment]
The following command builds `hdf5` with `libaec`:
```bash
spack install hdf5+szip ^libaec
```
Another option is to override the default preference in `packages.yaml`: https://github.com/spack/spack/blob/d48b18650034d28d522ec9fbda272279ff91c5c3/etc/spack/defaults/packages.yaml#L46

**Comment by markcmiller86** [comment]
Ah, didn't think to go look to see if aec was already there 👍 . Thanks
