### ISSUE TITLE
Re-Use Cache?

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#1936]
@scheibelp  When I upgrade to a new Spack, I now just do a `git clone` and rebuild everything.  That way I don't have useless old versions sticking around.  (OK, I'm not thrilled with the process but it's not the worst either).

Question: Can I copy the cache/ directory from the old Spack to the new one?  Is there any possible downside or risk to this?

**Comment by tgamblin** [comment]
You can. The cache is in the same format as a spack mirror -- there's nothing preventing it from being reused.
