### ISSUE TITLE
Standard Practice for hashes in PyPI URLs

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#1939]
@jppelteret 

The problem here is that PyPI URLs now contain unwieldy hashes that break Spack's normal way of guessing a URL based on a version number.  We need to document best practices on this issue.  See Google Groups thread...

https://groups.google.com/forum/#!searchin/spack/Cryptic$20error$20when$20installing$20new$20package%7Csort:relevance/spack/VuMGbwCmZzk/tnxixg-7AAAJ

**Comment by jppelteret** [comment]
# Repository for python packages
In addition to their developer websites, many python packages are hosted at the [Python Package Index (PyPi)](https://pypi.python.org/pypi). Although links to these individual files are typically [generated using a hash](https://bitbucket.org/pypa/pypi/issues/438) it is often possible to find a reliable link of the format
```
https://pypi.python.org/packages/source/<first letter of package>/<package>/<package>-<version>.<extension>
```
Packages hosted on `GitHub` and the like are often developer versions that do not contain all of the files (e.g. configuration scripts) necessary to support compilation. For this reason it is ideal to link to a repository such as `PyPi` if possible.

More recently, sources are being indexed at [pypi.io](https://pypi.io) as well. Links obtained from this site follow a similar pattern, namely
```
https://pypi.io/packages/source/<first letter of package>/<package>/<package>-<version>.<extension>
```
These links currently redirect back to `pypi.python.org`, but this [may change in the future](https://bitbucket.org/pypa/pypi/issues/438#comment-27243225).

***
***

How does this sound? I'm not sure if `curl` with `spack` works properly with the links at `pypi.io`
```
$ curl -k https://pypi.io/packages/source/s/setuptools/setuptools-22.0.0.tar.gz
<html><head><title>301 Moved Permanently</title></head><body><center><h1>301 Moved Permanently</h1></center></body></html>
```
, but I did have success with `wget`

```
$ wget https://files.pythonhosted.org/packages/source/s/simplegeneric/simplegeneric-0.8.1.tar.gz
--2016-10-07 07:35:54--  https://files.pythonhosted.org/packages/source/s/simplegeneric/simplegeneric-0.8.1.tar.gz
Resolving files.pythonhosted.org... 151.101.13.63, 2a04:4e42:3::319
Connecting to files.pythonhosted.org|151.101.13.63|:443... connected.
ERROR: cannot verify files.pythonhosted.org's certificate, issued by 'CN=GlobalSign CloudSSL CA - SHA256 - G3,O=GlobalSign nv-sa,C=BE':
  Unable to locally verify the issuer's authority.
To connect to files.pythonhosted.org insecurely, use `--no-check-certificate'.
07:35:55 jp:/tmp$ wget --no-check-certificate https://files.pythonhosted.org/packages/source/s/simplegeneric/simplegeneric-0.8.1.tar.gz
--2016-10-07 07:36:08--  https://files.pythonhosted.org/packages/source/s/simplegeneric/simplegeneric-0.8.1.tar.gz
Resolving files.pythonhosted.org... 151.101.13.63, 2a04:4e42:3::319
Connecting to files.pythonhosted.org|151.101.13.63|:443... connected.
WARNING: cannot verify files.pythonhosted.org's certificate, issued by 'CN=GlobalSign CloudSSL CA - SHA256 - G3,O=GlobalSign nv-sa,C=BE':
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 404 Not Found
2016-10-07 07:36:09 ERROR 404: Not Found.

07:36:09 jp:/tmp$ wget --no-check-certificate https://pypi.io/packages/source/s/setuptools/setuptools-22.0.0.tar.gz
--2016-10-07 07:36:33--  https://pypi.io/packages/source/s/setuptools/setuptools-22.0.0.tar.gz
Resolving pypi.io... 151.101.0.223, 151.101.128.223, 151.101.64.223, ...
Connecting to pypi.io|151.101.0.223|:443... connected.
WARNING: cannot verify pypi.io's certificate, issued by 'CN=DigiCert SHA2 Extended Validation Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US':
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 301 Redirect to Primary Domain
Location: https://pypi.org/packages/source/s/setuptools/setuptools-22.0.0.tar.gz [following]
--2016-10-07 07:36:33--  https://pypi.org/packages/source/s/setuptools/setuptools-22.0.0.tar.gz
Resolving pypi.org... 151.101.192.223, 151.101.64.223, 151.101.0.223, ...
Connecting to pypi.org|151.101.192.223|:443... connected.
WARNING: cannot verify pypi.org's certificate, issued by 'CN=DigiCert SHA2 Extended Validation Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US':
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://files.pythonhosted.org/packages/source/s/setuptools/setuptools-22.0.0.tar.gz [following]
--2016-10-07 07:36:34--  https://files.pythonhosted.org/packages/source/s/setuptools/setuptools-22.0.0.tar.gz
Resolving files.pythonhosted.org... 151.101.13.63, 2a04:4e42:3::319
Connecting to files.pythonhosted.org|151.101.13.63|:443... connected.
WARNING: cannot verify files.pythonhosted.org's certificate, issued by 'CN=GlobalSign CloudSSL CA - SHA256 - G3,O=GlobalSign nv-sa,C=BE':
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 302 Found
Location: https://pypi.python.org/packages/f5/90/010892bde11d2da00548285da29a055e6b0e3b81592bb6021571b87f34a1/setuptools-22.0.0.tar.gz [following]
--2016-10-07 07:36:34--  https://pypi.python.org/packages/f5/90/010892bde11d2da00548285da29a055e6b0e3b81592bb6021571b87f34a1/setuptools-22.0.0.tar.gz
Resolving pypi.python.org... 151.101.12.223, 2a04:4e42:3::223
Connecting to pypi.python.org|151.101.12.223|:443... connected.
WARNING: cannot verify pypi.python.org's certificate, issued by 'CN=DigiCert SHA2 Extended Validation Server CA,OU=www.digicert.com,O=DigiCert Inc,C=US':
  Unable to locally verify the issuer's authority.
HTTP request sent, awaiting response... 200 OK
Length: 675774 (660K) [application/octet-stream]
Saving to: 'setuptools-22.0.0.tar.gz'

setuptools-22.0.0.tar.gz                                   100%[==========================================================================================================================================>] 659.94K  1.38MB/s   in 0.5s

2016-10-07 07:36:35 (1.38 MB/s) - 'setuptools-22.0.0.tar.gz' saved [675774/675774]
```
If its too premature to make a comment regarding `pypi.io`, then we could just leave this out.

Ping @adamjstewart @mathstuf since you helped me with this in the first place

**Comment by jppelteret** [comment]
I suppose I should say that I'm just looking for some generic initial input to my suggestion. I'll create a PR later and will be happy to incorporate the comments into it.

**Comment by mathstuf** [comment]
Pass `--location` to curl to follow 3xx redirection pages.

**Comment by jppelteret** [comment]
Thanks @mathstuf that does work! So how would one pass this flag to spack? Does one need to implement a new optional argument to pass this flag to curl (or might it already be used in the background)? The current options are
```bash
$ spack --help
...
optional arguments:
  -h, --help      show this help message and exit
  -d, --debug     Write out debug logs during compile
  -D, --pdb       Run spack under the pdb debugger
  -k, --insecure  Do not check ssl certificates when downloading.
  -m, --mock      Use mock packages instead of real ones.
  -p, --profile   Profile execution using cProfile.
  -v, --verbose   Print additional output during builds
  -V, --version   show program's version number and exit
```

**Comment by mathstuf** [comment]
It should probably just be added to the core `curl` call; there's no reason to not follow 3xx redirects.

**Comment by citibeth** [comment]
So does this mean that all PyPI downloads are available via a URL without
the hash?  If so, can/should we eliminate hash-based PyPI URLs from Spack?

**Comment by adamjstewart** [comment]
@jppelteret I didn't know about the `pypi.io` URLs thing! Does that work for older versions too? If so, I would be all for converting all of our PyPi downloads to use that URL if possible.

**Comment by jppelteret** [comment]
@citibeth It seems to be a hit-and-miss as to whether they are available. I've found a few packages for which this is not the case, but its only been a handful of them.

@adamjstewart I only came across it this morning so I think we'd have to investigate further. The info that I put in the comment came from the posts linked there (I think you sent me that link in the first place). A few people have complained that the service doesn't work all of the time (caching issues, broken links) so it may not be the most reliable option at the moment. Most of the complaints were from a few month ago though, so maybe they've all been sorted out by now.

There's currently no capability to provide alternative links to the source files, right? I was just thinking that we could smooth the transition to non-hashed `pypi.python.org` URLs or `pypi.io` by adding new links at the top of packages (to be preferrentially used, of course) . In the case when the links become broken, `spack` would fall back to the original hashed URLs. If we find the services to be reliable then we could get rid of all the hashed URLs.

**Comment by adamjstewart** [comment]
> There's currently no capability to provide alternative links to the source files, right?

No, there's not currently any support for providing fallback mirrors in case a URL no longer works, although @citibeth wants to add that.

**Comment by citibeth** [comment]
> There's currently no capability to provide alternative links to the source
> files, right? I was just thinking that we could smooth the transition to
> non-hashed pypi.python.org URLs or pypi.io by adding new links at the top
> of packages (to be preferrentially used, of course) . In the case when the
> links become broken, spack would fall back to the original hashed URLs.
> If we find the services to be reliable then we could get rid of all the
> hashed URLs.
>
I've thought maybe we need a significantly more sophisticated way to
provide links.  Something like url_for_version(), but that understands that
certain repositories contain a lot of interesting tarballs we can
download.  For example, many tarballs we need are available from
Fedora.org.  PyPI tarballs can come from PyPI or sometimes directly from
the source.  There needs to be a better way to build in these smarts...
Spack should be able to find certain things on Fedora, PyPI, etc even if
you didn't tell it EXACTLY where to look (or even that it SHOULD look).

**Comment by adamjstewart** [comment]
@citibeth We would also need a way to make sure that is isn't just pulling down random stuff. It would need to pass a checksum test, and if in the case of GitHub vs. PyPi it has a different checksum, we would need to be able to have multiple registered checksums.

**Comment by citibeth** [comment]
On Fri, Oct 7, 2016 at 11:40 AM, Adam J. Stewart <notifications@github.com>
wrote:

> @citibeth <https://github.com/citibeth> We would also need a way to make
> sure that is isn't just pulling down random stuff. It would need to pass a
> checksum test,
>
Of course.  No problem there with the Fedora repo...

> and if in the case of GitHub vs. PyPi it has a different checksum, we
> would need to be able to have multiple registered checksums.
>
Yes, I suppose so.

These are the reasons I don't yet have a clear, specific idea of a design.

**Comment by citibeth** [comment]
@jppelteret You should have received a GitHub invitation in your email.  Would you be able to please accept it?  Then I'll be able to assign you to this issue (based on your suggestion above that you will be submitting a PR).

**Comment by jppelteret** [comment]
I see that in [fetch_strategy.py](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/fetch_strategy.py#L195) a flag to deal with 3xx redirection is already in place. So hopefully using `pypi.io` URLs won't be an issue.

**Comment by mathstuf** [comment]
For the record, it looks like Fedora went with `files.pythonhosted.org` directly. https://fedoraproject.org/wiki/Packaging:Python#Example_common_spec_file
