### ISSUE TITLE
PETSc 3.14 fails to enable superlu-dist

### ISSUE THREAD

**Issue by garth-wells** [LLNL/spack#19417]
The PETSc version was bumped to 3.14 in https://github.com/spack/spack/commit/569eb866fc7f42da0018b73ac7b4bc7a5dbc76ff, but updates to the SuperLU-dist dependency were overlooked. The lines
```
depends_on('superlu-dist@6.1:6.3.0~int64', when='@3.13.0:3.13.99+superlu-dist+mpi~int64')
depends_on('superlu-dist@6.1:6.3.0+int64', when='@3.13.0:3.13.99+superlu-dist+mpi+int64')
```
should be changed to something like
```
depends_on('superlu-dist@6.1:6.3.0~int64', when='@3.13.0:3.14.99+superlu-dist+mpi~int64')
depends_on('superlu-dist@6.1:6.3.0+int64', when='@3.13.0:3.14.99+superlu-dist+mpi+int64')
```
Otherwise `spack install petsc+superlu-dist` fails to configure PETSc with SuperLU-fist.

@balay

**Comment by balay** [comment]
Fix at https://github.com/spack/spack/pull/19686

**Comment by garth-wells** [comment]
Fixed in https://github.com/spack/spack/pull/19686.
