### ISSUE TITLE
Spack built python does not link to ssl

### ISSUE THREAD

**Issue by s-sajid-ali** [LLNL/spack#19439]
Once a spack built python linked to an external openssl (the system wide one) is loaded (whether by itself or as a dependent or in a environment) spack commands fail. 

### Steps to reproduce the issue

```console
sajid@LAPTOP-CDJT2P3R /m/c/U/sajid> which python3
/usr/bin/python3
sajid@LAPTOP-CDJT2P3R /m/c/U/sajid> spack find -lv python
==> 1 installed package
-- linux-ubuntu20.04-zen2 / gcc@9.3.0 ---------------------------
xvkj7ej python@3.8.6+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87
sajid@LAPTOP-CDJT2P3R /m/c/U/sajid> spack load /xvk
sajid@LAPTOP-CDJT2P3R /m/c/U/sajid> spack find --loaded
Traceback (most recent call last):
  File "/home/sajid/packages/spack/bin/spack", line 63, in <module>
    import spack.main  # noqa
  File "/home/sajid/packages/spack/lib/spack/spack/main.py", line 31, in <module>
    import spack.architecture
  File "/home/sajid/packages/spack/lib/spack/spack/architecture.py", line 69, in <module>
    import spack.compiler
  File "/home/sajid/packages/spack/lib/spack/spack/compiler.py", line 20, in <module>
    import spack.spec
  File "/home/sajid/packages/spack/lib/spack/spack/spec.py", line 105, in <module>
    import spack.repo
  File "/home/sajid/packages/spack/lib/spack/spack/repo.py", line 34, in <module>
    import spack.caches
  File "/home/sajid/packages/spack/lib/spack/spack/caches.py", line 15, in <module>
    import spack.fetch_strategy
  File "/home/sajid/packages/spack/lib/spack/spack/fetch_strategy.py", line 41, in <module>
    import spack.util.web as web_util
  File "/home/sajid/packages/spack/lib/spack/spack/util/web.py", line 15, in <module>
    import ssl
  File "/home/sajid/packages/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/python-3.8.6-xvkj7ejpc5ox2wb2zuiiszucpsy5h62q/lib/python3.8/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
sajid@LAPTOP-CDJT2P3R /m/c/U/sajid>
```

### Error Message
Stacktrace is as shown above.

### Information on your system

```
sajid@LAPTOP-CDJT2P3R ~/p/spack (develop)> git shortlog -n1
iarspider (1):
      Lhapdf extends python (#19398)

sajid@LAPTOP-CDJT2P3R ~/p/spack (develop)> spack debug report
* **Spack:** 0.11.2-9270-d9bb90d06
* **Python:** 3.8.2
* **Platform:** linux-ubuntu20.04-zen2
sajid@LAPTOP-CDJT2P3R ~/p/spack (develop)>
```

```
sajid@LAPTOP-CDJT2P3R ~> cat .spack/packages.yaml
packages:
  perl:
    externals:
    - spec: perl@5.30.0~cpanm+shared+threads
      prefix: /
  openssl:
    externals:
    - spec: openssl@1.1.1f
      prefix: /
  cmake:
    externals:
    - spec: cmake@3.16.3
      prefix: /
sajid@LAPTOP-CDJT2P3R ~>
```

```
sajid@LAPTOP-CDJT2P3R ~> cat .spack/linux/compilers.yaml
compilers:
- compiler:
    spec: gcc@9.3.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: ubuntu20.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: 'clang@11.0.0

      Target:'
    paths:
      cc: /home/sajid/packages/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/llvm-11.0.0-rvxghsel3dq2v35ynccuo5jjkfrokxlr/bin/clang
      cxx: /home/sajid/packages/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.3.0/llvm-11.0.0-rvxghsel3dq2v35ynccuo5jjkfrokxlr/bin/clang++
      f77:
      fc:
    flags: {}
    operating_system: ubuntu20.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
sajid@LAPTOP-CDJT2P3R ~>
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

Related https://github.com/spack/spack/issues/13902

PS : I've seen this bug on multiple platforms recently.

PPS : `spack load llvm && spack compiler find` for a spack built `llvm` gives an erroneous entry in `compilers.yaml` (see the above for clang's `spec`). Is this a known bug ?

**Comment by adamjstewart** [comment]
Yep, this is a duplicate of #13902. Unfortunately I've never been able to reproduce this bug, so I can't help much. You may want to open an issue with the CPython devs.

**Comment by s-sajid-ali** [comment]
Looking through the build logs I see : 

```
Python build finished successfully!
The necessary bits to build these optional modules were not found:
_curses               _curses_panel         _hashlib
_ssl                  _tkinter              _uuid
To find the necessary bits, look in setup.py in detect_modules() for the module's name.


The following modules found by detect_modules() in setup.py, have been
built by the Makefile instead, as configured by the Setup files:
_abc                  atexit                pwd
time


Could not build the ssl module!
Python requires an OpenSSL 1.0.2 or 1.1 compatible libssl with X509_VERIFY_PARAM_set1_host().
LibreSSL 2.6.4 and earlier do not provide the necessary APIs, https://github.com/libressl-portable/portable/issues/381
```

I have the `openssl` executable (which was used to detect it as an external package) but I don't have the ssh headers and Python's configure step shows :
```
checking for openssl/ssl.h in /... no
checking whether compiling and linking against OpenSSL works... no
checking for --with-ssl-default-suites... python
```



Spack assumption  that python has the `_ssl` module causes it to fail. Perhaps it should check for this and tell users that spack needs a `python` executable with `_ssl` enabled to be run ?

**Comment by adamjstewart** [comment]
> Perhaps it should check for this and tell users that spack needs a python executable with _ssl enabled to be run ?

I think this is kind of implied by: "ModuleNotFoundError: No module named '_ssl'"

Our Python package already has a check such that `spack install --test=root python+ssl` will fail if `ssl` doesn't get built. I think you just need to remove the external package and let Spack handle all dependencies.

**Comment by s-sajid-ali** [comment]
>I think you just need to remove the external package and let Spack handle all dependencies.

Yes, that should work.

Since the current `external find` logic only looks for executables and not headers, spack can't differentiate between runtime and development libraries (`libssl` vs `libssl-dev`, where only the second one provides the headers). Once https://github.com/spack/spack/issues/19364 is addressed, the external detection of `openssl` could include searching for headers as well which would solve the issue.

**Comment by adamjstewart** [comment]
In addition to #19364, we currently don't have a way to differentiate between external packages that provide libraries/headers (like python-devel) and external packages that only provide binaries (like python).

**Comment by s-sajid-ali** [comment]
>In addition to #19364, we currently don't have a way to differentiate between external packages that provide libraries/headers (like python-devel) and external packages that only provide binaries (like python).

We could notify a user when they're trying to add external packages without headers/libraries that it might not work but let them add those anyway. That would make debugging easier.
