### ISSUE TITLE
Installation issue: gcc

### ISSUE THREAD

**Issue by tomgreen66** [LLNL/spack#19478]
### Steps to reproduce the issue

```console
$ spack install gcc@master
...
==> No binary for gcc found: installing from source                                                                                               [190/630]
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
2 out of 2 hunks ignored -- saving rejects to file gcc/Makefile.in.rej
Reversed (or previously applied) patch detected!  Assume -R? [n]
Apply anyway? [n]
1 out of 1 hunk ignored -- saving rejects to file gcc/configure.ac.rej
==> Patch /lustre/home/ca-tgreen/Work/git/spack/var/spack/repos/builtin/packages/gcc/zstd.patch failed.
==> Error: ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/lustre/home/ca-tgreen/Work/git/spack/var/spack/repos/builtin/packages/gcc/zstd.patch' '-d' '.'

```

### Information on your system

* **Spack:** 0.15.4-979-ee1725828
* **Python:** 3.6.8
* **Platform:** cray-rhel8-aarch64

### Additional information

* [spack-build-out.txt]()
* [spack-build-env.txt]()
Not present in staging directory.

@michaelkuhn 

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by tomgreen66** [comment]
Had temporary fix by fixing the version that the ztd patch is applied in gcc package.py since the master version of gcc has the patch already applied.

**Comment by adamjstewart** [comment]
@tomgreen66 that sounds like the right fix to me if you want to submit a PR to fix this. Just use:
```python
patch('zstd.patch', when='@10.0:10.2')
```
assuming that it won't be needed in 10.3.
