### ISSUE TITLE
Spack changes order of command line arguments to linker

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#195]
Spack's `cc` compiler and linker wrapper changes the order in which arguments are passed to the linker. Specifically, library paths are moved in front of libraries. This creates problems if a library can be found in multiple locations, and the reordering makes them found in the wrong locations.

This is specifically a problem when building LLVM on a system that has LLVM installed in a system library. The command line passed to Spack's `cc` looks something like
```
-lLLVM-3.3 -L/usr/lib/x86_64-linux-gnu
```
and both the build directory of LLVM as well as the system directory `/usr/lib/x86_64-linux-gnu` contain a file `libLLVM-3.3.so`.

I have modified `cc` to keep the original arguments; a not-so-elegant sample implementation is at <https://gist.github.com/eschnett/f4459534f3b797235aa4>.

With these changes, I can build LLVM 3.3 just fine.

**Comment by eschnett** [comment]
Does the solution outlined in the gist above sound acceptable? If so, I will clean it up and create a PR.

**Comment by tgamblin** [comment]
@eschnett: I think it does -- can you go ahead and submit a PR?  I just haven't had a chance to test this -- sorry for not getting to it faster!
