### ISSUE TITLE
Am I able to restrict applications permissions?

### ISSUE THREAD

**Issue by Joe23232** [LLNL/spack#19520]
Any application that is installed through the `spack` package manager, am I able to restrict the applications permissions, such as file access ~ I can specify which directories can it access and which directories it can't access, create virtual directories for the application to access, microphone, speaker, bluetooth, Internet etc?

Additionally with `spack`, am I able to get applications that are either installed outside of `spack` (installed via `pacman` or something similar) or applications that there binaries are directly being launched, am I able to some how configure it to run through `spack` and to restirct permissions?

**Comment by adamjstewart** [comment]
I think this is the closest thing Spack currently has: https://spack.readthedocs.io/en/latest/build_settings.html#package-permissions

This allows you to set the permissions of all Spack-installed packages, for example, if a license is required and only a certain set of users should have access.

I don't know how to restrict access for Spack-installed packages to different system locations aside from chmod/ACLs.

**Comment by Joe23232** [comment]
Is it possible for me to then use `firejail`?

**Comment by adamjstewart** [comment]
That should be possible, although I haven't personally tried.

**Comment by Joe23232** [comment]
Is `spack` planning to implement more file permissions?

**Comment by adamjstewart** [comment]
@tgamblin would be the best person to answer that question.

**Comment by tgamblin** [comment]
We're not currently planning to implement any runtime permission settings on the different installed packages. You could certainly try to rig something up with firejail, but at the moment all we do is give different applications different group permissions as @adamjstewart said above.

I'm not sure what you want to do with `firejail`, though.  It seems like I would need to patch every installation in Spack if I wanted to force users to use it.

**Comment by scheibelp** [comment]
You may be able to achieve some approximation of this with a post-install hook (https://spack.readthedocs.io/en/latest/spack.hooks.html#module-spack.hooks): you add a python module to the `hooks` directory which hands you the package after it is installed. You can do anything you like with it then (assuming you can achieve what you want with a one-time action conducted at install time).

**Comment by Joe23232** [comment]
@tgamblin 

> We're not currently planning to implement any runtime permission settings on the different installed packages. You could certainly try to rig something up with firejail, but at the moment all we do is give different applications different group permissions as @adamjstewart said above.

I see

> I'm not sure what you want to do with firejail,

I just wanted to restrict applications from having certain access.

@scheibelp 

> You may be able to achieve some approximation of this with a post-install hook (https://spack.readthedocs.io/en/latest/spack.hooks.html#module-spack.hooks): you add a python module to the hooks directory which hands you the package after it is installed. You can do anything you like with it then (assuming you can achieve what you want with a one-time action conducted at install time).

sorry, so in regards to the hooks, are they a way that defines how a package runs or something? I took a look at the article I don't quite understand how modules and hooks work.

**Comment by scheibelp** [comment]
> in regards to the hooks, are they a way that defines how a package runs or something?

No: they provide a means for you to execute whatever logic you want on each package after it is installed: you would have to write a script to modify the package in some way (e.g. changing the executables or replacing them with wrapper scripts). You would have to add a `.py` file to the `hooks/` directory in Spack which contains this script or calls it on files in the package installation prefix.

**Comment by Joe23232** [comment]
Right I see now mate.

**Comment by scheibelp** [comment]
OK, I think then that the original issue posted is resolved. Feel free to reopen if you disagree!

**Comment by Joe23232** [comment]
Cool, thanks
