### ISSUE TITLE
Spack hanging after installing berkeley-db package

### ISSUE THREAD

**Issue by mdorier** [LLNL/spack#19545]
I am installing a bunch of packages with spack, and spack hangs after having built and installed the berkeley-db package. From the spack-build-out.txt log, it seems that berkeley-db was correctly built and installed. The last few lines of the log are `libtool: install: ...` lines and `ps aux` shows no other running commands than two `spack install` commands.

When I kill the hanging spack, and retry installing berkeley-db, I'm getting the following warning after the install phase:

```
==> Warning: Module file already exists : skipping creation
file : /nfs2/mdorier/spack/share/spack/modules/linux-ubuntu14.04-ivybridge/berkeley-db-18.1.40-gcc-8.2.1-vp4zdna
spec : berkeley-db@18.1.40%gcc@8.2.1 arch=linux-ubuntu14.04-ivybridge
```
and it still hangs after that.

I checked out an older commit of spack from October 1st and berkeley-db builds fine with that commit, so the problem was introduced sometime between October 1st and today October 27. I also checked different versions of berkeley-db and it didn't fix the problem.

Though it happens with the berkeley-db package, I am not sure whether other packages would have the same issue. The other packages I needed to build have built fine so far.

### Steps to reproduce the issue

```console
$ spack install berkeley-db
```

### Error Message

```console
$ spack --debug --stacktrace install berkeley-db
```
output: [debug.txt](https://github.com/spack/spack/files/5445719/debug.txt)

The command hangs after that, there is no error message. When I kill it with Ctrl-C however, I'm getting this (along with python stack traces):
```
nfs2/mdorier/spack/lib/spack/spack/installer.py:1609 ==> [2020-10-27-08:50:36.416817] Error: Failed to install berkeley-db due to RuntimeError: can't re-enter readline
```

### Information on your system

* **Spack:** 0.15.4-1674-bb00b1a
* **Python:** 3.4.3
* **Platform:** linux-ubuntu14.04-ivybridge

This also happens on ANL's Theta and Bebop supercomputers (those are the 3 platforms I have tried, and I have tried multiple file systems on them when available). I have very limited packages.yaml files with the minimum (autotools and stuff), and they differ from a platform to the other, so I don't think they are relevant.

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
I installed `berkeley-db` numerous times lately. Is this still an issue for you?

**Comment by mdorier** [comment]
I don't think I have seen this issue again. Feel free to close.
