### ISSUE TITLE
Installation issue: tcl

### ISSUE THREAD

**Issue by andymwood** [LLNL/spack#19546]
### Steps to reproduce the issue

```console
$ spack install tcl
...
==> tcl: Executing phase: 'install'
==> Error: FileNotFoundError: [Errno 2] No such file or directory: '/home/andrew/sta-toolchain/spack/opt/spack/linux-opensuse_leap15-haswell/gcc-8.4.0/tcl-8.6.8-dpeohvixrp4p4ktrfw66eow7nvrbcelq/lib/tclConfig.sh'

/home/andrew/sta-toolchain/spack/var/spack/repos/builtin/packages/tcl/package.py:58, in install:
         55            # Replace stage dir -> installed src dir in tclConfig
         56            filter_file(
         57                stage_src, installed_src,
  >>     58                join_path(self.spec.prefix, 'lib', 'tclConfig.sh'))
         59
         60        # Don't install binaries in src/ tree
         61        with working_dir(join_path(installed_src, self.configure_directory)):
```

### Information on your system

* **Spack:** 0.15.4
* **Python:** 3.6.10
* **Platform:** linux-opensuse_leap15-haswell
[spack-build-env.txt](https://github.com/spack/spack/files/5446022/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/5446024/spack-build-out.txt)

### Additional information

* [spack-build-out.txt]()
* [spack-build-env.txt]()

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
You might have encountered the same issue that @gardner48 reported in #18221, maybe try building Tcl 8.6.10 instead?

I'm able to build Tcl 8.6.10 on macOS without any issues.

**Comment by andymwood** [comment]
Thanks for the reply.

I've just tried `git checkout develop; spack install tcl@8.6.10`. It returns the same error.

**Comment by andymwood** [comment]
A similar error is also returned with `spack install glib@2.56.3`:
```console
spack install glib@2.56.3
...
==> glib: Executing phase: 'install'
==> Error: FileNotFoundError: [Errno 2] No such file or directory: '/home/andrew/sta-toolchain/spack/opt/spack/linux-opensuse_leap15-haswell/gcc-8.4.0/glib-2.56.3-45bhzjvfwssqnhvf2n6bygtnqcczc5nq/lib/pkgconfig/glib-2.0.pc'

/home/andrew/sta-toolchain/spack/var/spack/repos/builtin/packages/glib/package.py:261, in gettext_libdir:
        258            repl = 'Libs: -L{0} -Wl,-rpath={0} '.format(
        259                   spec['gettext'].prefix.lib)
        260            myfile = join_path(self.prefix.lib.pkgconfig, 'glib-2.0.pc')
  >>    261            filter_file(pattern, repl, myfile, backup=False)
```

I wonder if there's a more serious bug in the function `filter_file`?

**Comment by adamjstewart** [comment]
I don't think this is a bug with `filter_file`. My guess is that the missing files in question are being installed to `prefix.lib64` instead of `prefix.lib`. Can you try replacing `lib` with `lib64` and see if that solves the problem? If so we'll have to create a PR to try both or see which directory actually exists.

**Comment by andymwood** [comment]
I've just tried the change you suggest and both tcl and glib@2.56.3 install successfully.
