### ISSUE TITLE
apple-clang support in archspec

### ISSUE THREAD

**Issue by tgamblin** [LLNL/spack#19553]
We currently don't have proper uarch definitions for `apple-clang` -- they need to be added to `archspec`.

**Comment by adamjstewart** [comment]
I think 90% of `%apple-clang` users use Clang + GFortran, so this likely won't be useful until we have better mixed compiler support. I can't even build scipy without a Fortran compiler.

**Comment by alalazo** [comment]
Here https://github.com/archspec/archspec-json/pull/17 the PR that adds apple-clang support for microarchitectures to the JSON  database.
