### ISSUE TITLE
new arch target=graviton breaks everything on ARM/aarch64

### ISSUE THREAD

**Issue by mwkrentel** [LLNL/spack#19653]
This is on ARM64/aarch64, fedora 26, gcc 7.3.1.

The new target=graviton for ARM64 breaks pretty much EVERYTHING, at
least for gcc.  This seems to affect only ARM, not powerpc or x86_64.

```
$ spack arch
linux-fedora26-graviton

$ spack spec libsigsegv
libsigsegv@2.12%gcc@7.3.1 arch=linux-fedora26-graviton

$ spack -d install libsigsegv
...
2 errors found in build log:
     8     checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
     9     checking for gawk... gawk
     10    checking whether make sets $(MAKE)... yes
     11    checking whether make supports nested variables... yes
     12    checking for gcc... /home/krentel/spack/spack-repo/lib/spack/env/gcc/gcc
     13    checking whether the C compiler works... no
  >> 14    configure: error: in `/home/krentel/spack/spack-repo/build-stage/spack-stage-libsigsegv-2.12-53nzpmnlsoniuxoiimmyjf2a57xirln6/spack-src':
  >> 15    configure: error: C compiler cannot create executables
     16    See `config.log' for more details
```

The output of `spack -d` reveals the true problem.  target=graviton
causes -march to be set incorrectly.

```
[ccld] /usr/bin/gcc -march==armv8-a+crc+crypto -mtune=cortex-a72 ...
```

Maybe the mistake is simply the typo with two equal signs (=).

Anyway, with target=aarch64, -march gets set correctly and the build
succeeds.

```
$ ./spack -d install libsigsegv target=aarch64

[ccld] /usr/bin/gcc -march=armv8-a -mtune=generic ...
```

----------

I traced the problem to this commit.

```
commit 458d88eaad3c4e93210915ffa9b3bb64cc52d007
Author: Massimiliano Culpo <massimiliano.culpo@gmail.com>
Date:   Fri Oct 30 21:02:14 2020 +0100

    Make archspec a vendored dependency (#19600)
    
    - Added archspec to the list of vendored dependencies
    - Removed every reference to llnl.util.cpu
    - Removed tests from Spack code base
```

Before this commit, the default arch type is aarch64.  This commit
adds the type graviton and the typo with -march.

ping @alalazo

**Comment by alalazo** [comment]
Can you post:
1. What was your detected arch type before that commit
2. A sample of `/proc/cpuinfo` on your machine
3. Eventually the model of your chip

? The issue is very likely that we don't model the microarchitecture of your chip and our detection at the moment gives a false positive for `graviton`.

For your convenience, and in case you're not doing it already, you can work around this problem consistently by adding:
```
packages:
  all:
    target: ['aarch64']
```
until the issue is solved.

**Comment by mwkrentel** [comment]
Yes, I did know that target=aarch64 is a satisfactory workaround for
now, but thanks.

You did see that the bad march type from the spack gcc wrapper is
`-march==armv8-a+crc+crypto` with two equal signs, right?  For all I
know, maybe `armv8-a+crc+crypto` is correct and the only problem is
that some corner case adds an extra `=`.

Before the commit, spack arch reports ARM targets:

```
$ spack arch --known-targets
Cavium - aarch64
    thunderx2

Fujitsu - aarch64
    a64fx

$ spack arch                
linux-fedora26-aarch64
```

After the commit:

```
$ spack arch --known-targets
Cavium - aarch64
    thunderx2

Fujitsu - aarch64
    a64fx

ARM - aarch64
    graviton  graviton2

$ spack arch
linux-fedora26-graviton
```

cat /proc/cpuinfo reports 4 cores as:

```
processor       : 3
BogoMIPS        : 500.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 2
```

I'm not exactly sure what "model of the chip" is or how to find it.
The best info on this box is that it's a "SoftIron Overdrive 1000."

https://github.com/SoftIron/overdrive/blob/master/1000/OD1000_QSGv1.pdf

AMD Opteron A1100 System-on-Chip with 4 ARM Cortex-A57 cores.

Anything else?

**Comment by alalazo** [comment]
> You did see that the bad march type from the spack gcc wrapper is
-march==armv8-a+crc+crypto with two equal signs, right? For all I
know, maybe armv8-a+crc+crypto is correct and the only problem is
that some corner case adds an extra =

No, thanks for pointing this out explicitly - this is surely a typo that made its way into the codebase.

> Anything else?

That's more than enough at the moment, thanks. I'll need to check how that sample of `/proc/cpuinfo` differs from `graviton` and  how to distinguish among the two microarchitecture. Will do that asap, possibly in the next couple of days.

**Comment by balay** [comment]
I'm seeing the same issue on the same `softiron` ~onedrive~ `overdrive 1000` box with `linux-fedora32-graviton`.

And I can use `target=aarch64`

```
configure:4212: checking whether the C compiler works
configure:4234: /home/balay/spack.x/lib/spack/env/gcc/gcc    conftest.c  >&5
cc1: error: unknown value '=armv8-a+crc+crypto' for '-march'
cc1: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a armv8.5-a armv8.6-a native
```

**Comment by alalazo** [comment]
I'll get to this surely before the next release, sorry for the delay. A workaround is to edit:
```
lib/spack/external/archspec/json/cpu/microarchitectures.json
```
and remove the typo. Searching for `-march==` should suffice to find the right line to edit.

**Comment by balay** [comment]
Thanks, it works!
```
[balay@si spack.x]$ git diff
diff --git a/lib/spack/external/archspec/json/cpu/microarchitectures.json b/lib/spack/external/archspec/json/cpu/microarchitectures.json
index b957f6c5b..889848c8e 100644
--- a/lib/spack/external/archspec/json/cpu/microarchitectures.json
+++ b/lib/spack/external/archspec/json/cpu/microarchitectures.json
@@ -1490,7 +1490,7 @@
               },
               {
                   "versions": "6:",
-                  "flags" : "-march==armv8-a+crc+crypto -mtune=cortex-a72"
+                  "flags" : "-march=armv8-a+crc+crypto -mtune=cortex-a72"
               }
           ],
           "clang" : [
[balay@si spack.x]$ spack find
==> 1 installed package
-- linux-fedora32-graviton / gcc@10.2.1 -------------------------
libiconv@1.16
[balay@si spack.x]$ 
```

**Comment by mwkrentel** [comment]
The Softiron box I reported above has Cortex A57 cores.
I think graviton is A72.  I'm not sure how much difference
that makes.

@balay Is your box SoftIron Overdrive or Onedrive?
What does /proc/cpuinfo report?

Anyway, it would be nice to get the == typo fixed.

**Comment by balay** [comment]
```
[balay@si ~]$ dmesg |grep SoftIron
[    0.000000] Machine model: SoftIron Overdrive 1000 (AMD Seattle (Rev.B1))
[    0.000000] efi: EFI v2.60 by SoftIron Overdrive 1000
[balay@si ~]$ cat /proc/cpuinfo 
processor       : 0
BogoMIPS        : 500.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 2

processor       : 1
BogoMIPS        : 500.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 2

processor       : 2
BogoMIPS        : 500.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 2

processor       : 3
BogoMIPS        : 500.00
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer : 0x41
CPU architecture: 8
CPU variant     : 0x1
CPU part        : 0xd07
CPU revision    : 2

[balay@si ~]$ 
````

Is there a different  Onedrive product? [I remember they had 1000 and 3000 variants]

**Comment by mwkrentel** [comment]
@balay  You had a typo in your original post. (It's Overdrive, not Onedrive.)

> I'm seeing the same issue on the same softiorn onedirve 1000 box

Actually, you have the same box I have.

**Comment by balay** [comment]
I went ahead and created a PR with this change 

https://github.com/spack/spack/pull/19865
