### ISSUE TITLE
netlib-scalapack: reversed (or previously applied) patch detected

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#19650]
Using `spack@develop` (77fc458d2964490c83863d667df10b9a740ce05e from `Sun Nov 1 01:05:13 2020 +0100`)

Can't install `netlib-scalapack` ([netlib-scalapack.spec.yaml.txt](https://github.com/spack/spack/files/5470201/netlib-scalapack.spec.yaml.txt)) on:
* `Ubuntu 18.04`
* `ppc64le`

```
$> spack install -f ./netlib-scalapack.spec.yaml
...
==> Installing netlib-scalapack
==> No binary for netlib-scalapack found: installing from source
==> Using cached archive: /opt/spack/var/spack/cache/_source-cache/archive/61/61d9216cf81d246944720cfce96255878a3f85dec13b9351f1fa0fd6768220a6.tgz
Reversed (or previously applied) patch detected!  Assume -R? [n] <HIT ENTER | 'n' | 'y'>
Apply anyway? [n] <HIT ENTER | 'n' | 'y'>

5 out of 5 hunks ignored -- saving rejects to file PBLAS/SRC/pdamax_.c.rej
Reversed (or previously applied) patch detected!  Assume -R? [n]
...
goes on indefinitely
...
Ctrl+C

==> Error: Keyboard interrupt.
```

Behavior is exactly the same on first fetch:
```
$> spack install -f ./netlib-scalapack.spec.yaml
...
==> Installing netlib-scalapack
==> No binary for netlib-scalapack found: installing from source
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/61/61d9216cf81d246944720cfce96255878a3f85dec13b9351f1fa0fd6768220a6.tgz
################################################################################################################################################################################## 100.0%
Reversed (or previously applied) patch detected!  Assume -R? [n]
.....
```

Offending commit looks to be:
https://github.com/spack/spack/commit/51a9473bf867af3e5f8f024d124c71b5b03384a0#diff-4adf527004d5d4cf80265f7ee109f54d6ca3b75431bdd216f237dcc526c3c8cc

This is kind of a big problem as it breaks ability of E4S to build all packages that depend on `netlib-scalapack` in automated builds, which include at least:
1. `strumpack`
2. `trilinos`
3. `omega-h`
4. `slate`

@vkallesh @adamjstewart @t-karatsu @becker33 @scottwittenburg

**Comment by adamjstewart** [comment]
Ah, the bug is that the patches get applied twice. That's an easy fix.
