### ISSUE TITLE
Installation issue: meson packages can't strip on macOS

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#19661]
So far, I've noticed that this bug affects the following packages:

* at-spi2-atk
* at-spi2-core
* atk
* gdk-pixbuf

It likely affects all meson packages on macOS.

### Steps to reproduce the issue

```console
$ spack install at-spi2-core
...
Stripping target 'atspi/libatspi.0.dylib' using strip.
Could not strip file.

Stdout:


Stderr:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/strip: error: symbols referenced by indirect symbol table entries that can't be stripped in: /Users/Adam/spack/opt/spack/darwin-catalina-x86_64/apple-clang-12.0.0/at-spi2-core-2.38.0-kgbdezwlu3gy4ahg64ekaeqtjhei2ehn/lib/libatspi.0.dylib
```

### Information on your system

* **Spack:** 0.15.4-1763-3576953558
* **Python:** 3.8.6
* **Platform:** darwin-catalina-ivybridge

### Additional information

@michaelkuhn have you ever seen anything like this before? I tried the latest version of meson, ninja, and these 3 packages, but I can't seem to fix them. Homebrew doesn't have any patches either.

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
This suggests that different args for `strip` are needed on macOS: https://github.com/pybind/pybind11/issues/595

Not sure if this is a bug to report to meson, or ninja, or the other packages that use them.

**Comment by adamjstewart** [comment]
This suggests that it may actually be intentional (I think I understand why we were patching meson now): https://github.com/mesonbuild/meson/issues/6541

Do we need to be patching in another place too?

**Comment by adamjstewart** [comment]
I tried removing our meson patches for 0.55.0 and 0.56.0 but I still see the same error.

**Comment by adamjstewart** [comment]
Same bug occurs with meson 0.54.3, so it's not like 0.55 completely broke RPATH stripping.

**Comment by adamjstewart** [comment]
It looks like @citibeth added a similar hack to the `glib` package in #16179, let me try that.

**Comment by adamjstewart** [comment]
That seems to work. Not sure if we should just apply that in the `meson` package? Also, gtk+ doesn't build for me, probably just needs to be updated to use MesonPackage.

**Comment by aweits** [comment]
> That seems to work. Not sure if we should just apply that in the `meson` package? Also, gtk+ doesn't build for me, probably just needs to be updated to use MesonPackage.

Did you look into what can be set in machine files? https://mesonbuild.com/Native-environments.html https://mesonbuild.com/Machine-files.html

**Comment by adamjstewart** [comment]
Nope, I barely use meson. @michaelkuhn is currently our meson maintainer, but if you want to add yourself to the list that would be great.

**Comment by michaelkuhn** [comment]
It seems this is unrelated to rpath stripping but instead caused by us explicitly passing `--strip` to Meson. I guess the easiest way would be to set `STRIP` in `MesonPackage` when on macOS, so we do not have to generate a machine file (on the fly?). We could also disable stripping on macOS, I guess.

**Comment by adamjstewart** [comment]
Should we set `STRIP` in `MesonPackage` or in `meson` or both? A lot of packages don't use `MesonPackage` yet because they support multiple build systems, so I'm leaning toward the latter.

**Comment by michaelkuhn** [comment]
Good point, it probably makes sense to set it in meson then.
