### ISSUE TITLE
non-explicit "All fetchers failed" error when curl is not available

### ISSUE THREAD

**Issue by lpoirel** [LLNL/spack#19673]
When curl is not installed and I try to use spack, I get 
```
$ spack install zlib
==> Installing zlib
==> No binary for zlib found: installing from source
==> Error: FetchError: All fetchers failed

/home/f377482/spack_installs/spack/lib/spack/spack/package.py:1270, in do_fetch:
       1267                                 self.spec.format('{name}{@version}'), ck_msg)
       1268
       1269        self.stage.create()
  >>   1270        err_msg = None if not self.manual_download else self.download_instr
       1271        self.stage.fetch(mirror_only, err_msg=err_msg)
       1272        self._fetch_time = time.time() - start_time
       1273
```

Using pdb, I see 
that a ```spack.util.executable.CommandNotFoundError: spack requires 'curl'. Make sure it is in your path.``` error was generated, but silenced somewhere later.

This message is very helpful and should deserve to be displayed to the user.

**Comment by adamjstewart** [comment]
@tldahlgren this might have happened when we made Spack less verbose...

**Comment by tldahlgren** [comment]
> @tldahlgren this might have happened when we made Spack less verbose...

From the line it looks like the manual download change (https://github.com/spack/spack/pull/18242) was a contributor.

**Comment by tldahlgren** [comment]
> > @tldahlgren this might have happened when we made Spack less verbose...
> 
> From the line it looks like the manual download change (#18242) was a contributor.

On closer inspection, you are correct Adam.
