### ISSUE TITLE
Installation issue: mumps%gcc@10:

### ISSUE THREAD

**Issue by lpoirel** [LLNL/spack#19687]
### Steps to reproduce the issue

```console
$ spack install mumps %gcc@10.2.0
...
.../linux-ubuntu20.10-sandybridge/gcc-10.2.0/openmpi-3.1.6-5buw3dsyti44enea7vodmjltlqrh2qnq/bin/mpif90 -fPIC -O -DALLOW_NON_INIT -I. -I../include   -Dpord -Dparmetis -c ana_omp_m.F -oana_omp_m.o
ana_omp_m.F:758:42:

  758 |         CALL MUMPS_QUICK_SORT_PHYS_L0( N, STEP(1), PHYS_L0_OMP(1),
      |                                          1
Error: Element of assumed-shape or pointer array passed to array dummy argument 'step' at (1)
```

This is corrected by setting `fflags="-fallow-argument-mismatch"`as suggested in [https://gcc.gnu.org/gcc-10/changes.html](https://gcc.gnu.org/gcc-10/changes.html) and confirmed in a private confirmation with the Mumps team.

### Information on your system
```console
$ spack debug report
* **Spack:** 0.15.4-1773-4d6c9a8f2
* **Python:** 3.8.6
* **Platform:** linux-ubuntu20.10-sandybridge
```

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/5477742/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/5477743/spack-build-env.txt)

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by sethrj** [comment]
Ugh, I've seen a bunch of these errors on the legacy Fortran code I have to deal with. GCC10 has gotten a lot more strict about fortran. This will have to be submitted to the upstream Mumps developers; perhaps as a workaround you could patch the FFLAGS using a `@when("%gcc@10:)`?
