### ISSUE TITLE
flake8 tests: Don't overwrite files that haven't changed

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#1974]
@adamjstewart The one funny thing I've noticed with the flake8 tests is they overwrite the files you're working on every time you run.  Not sure why this is needed, but it is a bit annoying...

Below is code that can be used to overwrite files only if they are different.  Two things that could be improved with it:
  *) Should be expanded to be a full Python context manager
  *) It could write to an in-memory file with StringIO, rather than to a temporary file on disk.  Except for REALLY big files, that's probably a better approach these days.

```
import tempfile
import filecmp
import shutil

# ------------------------------------------------------
class WriteIfDifferent(object):
    """Allows user to write to a temporary file, then move it
    to the destination only if it is different from the destination."""
    def __init__(self, ofname, **kwargs):
        """ofname: Name we ultimately want to write to."""
        self.ofname = ofname
        self.file = tempfile.NamedTemporaryFile(delete=False, **kwargs)
        self.tfname = self.file.name

    def close(self):
        self.file.close()
        try:
            if filecmp.cmp(self.tfname, self.ofname):
                # Files are equal, we are done!
                os.remove(self.tfname)
                return
        except: pass # Error means the files were NOT equal.

        # Files are not equal, so copy the temporary file over.
        shutil.copyfile(self.tfname, self.ofname)
        os.remove(self.tfname)

```

**Comment by adamjstewart** [comment]
> The one funny thing I've noticed with the flake8 tests is they overwrite the files you're working on every time you run. Not sure why this is needed, but it is a bit annoying...

I have no idea what you're talking about...

**Comment by citibeth** [comment]
> I have no idea what you're talking about...

See example below.  In this example, I did NOTHING apart from what you see on the command lines.  Notice how the modification date of the file `libgit2/package.py` changed.  [OK.. I don't know whether the file was overwritten or just touched.  Either way, I don't think that should be happening.]

```
$ ls -lT ~/git/spack/var/spack/repos/builtin/packages/libgit2/package.py
-rw-r--r--  1  1956 Oct  8 12:11:33 2016 package.py
$ ./run-flake8-tests 
Dependencies found.
=======================================================
flake8: running flake8 code checks on spack.

Modified files:

  var/spack/repos/builtin/packages/libgit2/package.py
  var/spack/repos/builtin/packages/libssh2/package.py
  var/spack/repos/builtin/packages/py-git2/package.py
=======================================================
Flake8 checks were clean.
$ ls -lT ~/git/spack/var/spack/repos/builtin/packages/libgit2/package.py
-rw-r--r--  1  1956 Oct  8 12:12:34 2016 package.py
```

**Comment by adamjstewart** [comment]
`run-flake8-tests` runs `changed_files` to determine what files have changed. Since users may have multiple commits on a branch, it returns the list of all files that have been added or modified since branching off of develop. Since these are all files that you added to Spack, this is the intended behavior.

**Comment by citibeth** [comment]
This all seems like good behavior.  I just don't understand why it has to
modify the file timestamps in the working directory in order to achieve
that goal.

**Comment by adamjstewart** [comment]
Ah, now I see what you mean. Hmm, let me think about this.

**Comment by adamjstewart** [comment]
I'm sure this could be done, but it would add a lot of unnecessary complexity. Is the change in timestamp your only complaint?

**Comment by citibeth** [comment]
Probably not worth it then.
