### ISSUE TITLE
Installation issue:  py-cython

### ISSUE THREAD

**Issue by rodrigo-ceccato** [LLNL/spack#19759]
### Steps to reproduce the issue

```console
spack install py-cython %gcc@8.3.0
```

### Information on your system

* **Spack:** 0.15.4-1776-b4ea74c
* **Python:** 3.6.8
* **Platform:** linux-centos7-cascadelake

### Additional information
`spack maintainers py-cython` returns nothing

* [spack-build-out.txt](https://github.com/spack/spack/files/5495167/spack-build-out.txt)

* [spack-build-env.txt](https://github.com/spack/spack/files/5495169/spack-build-env.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
So that others don't need to dig into the `spack-build-out.txt`, the specific build failure is:
```
/tmp/root/spack-stage/spack-stage-py-cython-0.29.21-yqkk5btpfl5zub23mqgn26ye2dp7im6q/spack-src/Cython/Plex/Scanners.c:19:10: fatal error: Python.h: No such file or directory
 #include "Python.h"
          ^~~~~~~~~~
```
Can you see if #19768 fixes your problem? If not, my only other guess is that you are using an external package for Python but you don't have `python-devel` installed on your system, so the development headers are missing.

**Comment by rodrigo-ceccato** [comment]
Thanks for the suggestion!

#19768 did not fix my problem, but you were right, installing `python3-devel.x86_64` did the trick.

That was totally my mistake. Again, thank you =]
