### ISSUE TITLE
Add --scope option to spack external find

### ISSUE THREAD

**Issue by victorusu** [LLNL/spack#19763]
Can you please add the `--scope` option to the `external find` command?
Currently `external find` generates the `package.yaml` file in the path `~/.spack/package.yaml`. It would be great if we could select where to create the `package.yaml` file.

**Comment by tkameyama** [comment]
`--scope` option to the `spack external find` is already added by #18165.

**Comment by alalazo** [comment]
Thanks for spotting this @tkameyama !
