### ISSUE TITLE
Installation issue: virtualgl ^libjpeg fails (only seems to work with libjpeg-turbo)

### ISSUE THREAD

**Issue by payerle** [LLNL/spack#19784]
The virtualgl package lists a virtual dependency on 'jpeg', which has providers libjpeg and libjpeg-turbo.   However, virtualgl seems to only be able to build with libjpeg-turbo.

### Steps to reproduce the issue

```console
$ spack install virtualgl ^libturbo
```
fails with errors like 
```console
CMake Error at cmakescripts/FindTurboJPEG.cmake:16 (message):
  Could not find turbojpeg.h in /opt/libjpeg-turbo/include.  If it is
  installed in a different place, then set TJPEG_INCLUDE_DIR accordingly.
Call Stack (most recent call first):
  CMakeLists.txt:311 (include)
```

Bulding against libjpeg-turbo, e.g.
```console
$ spack install virtualgl ^libturbo-jpeg
```
is successful.

I made a quick attempt to hack the package.py to set TJPEG_INCLUDE_DIR and TJPEG_LIBRARY to point to the libjpeg include and libraries, but this still generates errors:

```console
    65    -- X Video support disabled (VGL_USEXV = 0)
  >> 66    CMake Error at cmakescripts/FindTurboJPEG.cmake:16 (message):
     67      Could not find turbojpeg.h in
     68      /software/spack-software/2020.05.14/linux-rhel8-ivybridge/gcc-8.4.0/libjpeg-9c-5upfo56ajuvhkiw5krysf43w3jgzzcy4/include.
     69      If it is installed in a different place, then set TJPEG_INCLUDE_DIR
```
since of course libjpeg does not have a turbojpeg.h include.

A simple solution would be to change the dependency from a virtual dependency on jpeg to a concrete dependency on libjpeg-turbo.   A better solution would be to patch the virtualgl build stuff to accept either libjpeg or libjpeg-turbo, but that is more work than I can deal with right now.  I am not sure if other packages have similar issues.

### Information on your system

```console
$ spack debug report
* **Spack:** 0.14.2
* **Python:** 3.6.8
* **Platform:** linux-rhel8-ivybridge
```

### Additional information

* [spack-build-env.txt](https://github.com/spack/spack/files/5502754/spack-build-env.txt)
* [spack-build-out.txt](https://github.com/spack/spack/files/5502755/spack-build-out.txt)

No maintainers found

### General information

- [x ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x ] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x ] I have uploaded the build log and environment files
- [x ] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
I'm fine with the simple solution if you want to submit a PR for that.
