### ISSUE TITLE
How do I install chromium

### ISSUE THREAD

**Issue by Joe23232** [LLNL/spack#19797]
Hi, I am new to `spack`. After I `clone`ed the repository, I tried running (after `cd`ing into `spack/bin`) `./spack install chromium` and it could not find it. Am I supposed to add some repository or something?

**Comment by adamjstewart** [comment]
Spack does not yet have a build recipe for chromium. If you would like to write one, see the following docs:

https://spack.readthedocs.io/en/latest/contribution_guide.html
https://spack.readthedocs.io/en/latest/packaging_guide.html
https://spack.readthedocs.io/en/latest/build_systems.html

and tutorial:

https://spack-tutorial.readthedocs.io/en/latest/tutorial_packaging.html

**Comment by Joe23232** [comment]
I see, thanks mate.
