### ISSUE TITLE
Modules: regression with ifort caused by CPATH not being set anymore

### ISSUE THREAD

**Issue by RemiLacroix-IDRIS** [LLNL/spack#19840]
Hi,

Commit e3f97b37e64d4de70baf8e58fcd747b021d8f2f9 replaced `CPATH` by language specific environment variables in modules generated by Spack. Unfortunately this caused a regression with the Intel Fortran compilers.

I think there has been a mixed-up regarding the `INCLUDE` environment variable which was added in this commit with the following comment:
> The INCLUDE env variable specifies paths to look for .mod file for Intel Fortran compilers

This is true on Windows but NOT on Linux and MacOS as stated in the documentation (https://software.intel.com/content/www/us/en/develop/documentation/fortran-compiler-developer-guide-and-reference/top/program-structure/using-include-files.html):
> Directories are searched for include files in this order: 
> ...
> 5. In the directories specified with environment variables CPATH (Linux* and macOS*) or INCLUDE (Windows*)

I am not sure what can be done here to support ifort on Linux while avoiding the warnings mentioned by commit e3f97b37e64d4de70baf8e58fcd747b021d8f2f9.

/CC @alalazo 

Best,
Rémi

**Comment by alalazo** [comment]
> I am not sure what can be done here to support ifort on Linux while avoiding the warnings mentioned by commit e3f97b3.

Can you try to modify your `modules.yaml` to set `CPATH` appropriately only for packages providing Intel compilers? If that works consistently across different configurations we may push it to our `modules.yaml` default.

**Comment by RemiLacroix-IDRIS** [comment]
> Can you try to modify your `modules.yaml` to set `CPATH` appropriately only for packages providing Intel compilers?

I am not sure what you mean. This can happen for any packages as soon as they provide `.mod` files.

**Comment by alalazo** [comment]
> Unfortunately this caused a regression with the Intel Fortran compilers.

Sorry for the misunderstanding. I thought that the sentence above meant we had to set `CPATH` to make `ifort` work at all. If that's not the case, I don't think we should modify Spack's defaults, but if you want to set implicit search paths for anything compiled with Intel compilers you can try:

```yaml
modules:
  tcl:
    '%intel':
      environment:
        prepend_path:
          CPATH: '{prefix}'/include
```
You can also modify the match rule to something different from `%intel` or use `all` to apply it to all the specs.

**Comment by RemiLacroix-IDRIS** [comment]
Sorry it wasn't clear. I mean it prevents any `.mod` files (or header files for that matter) to be found automatically when using ifort which basically beats the point of using module.

For example, it means the Fortran modules for NetCDF, HDF5, FFTW, etc will not be in the search path of ifort with the modules Spack currently generated.

**Comment by alalazo** [comment]
> which basically beats the point of using module.

This can be opinionated, which is why we are so flexible with configuring module files. Some sites might say that you should:
```console
ifort -I ${HDF5_ROOT}/include
```
explicitly and they'll set HDF5_ROOT for you with modules. Is the snippet above working for you (modulo typo I might have put in)?

**Comment by RemiLacroix-IDRIS** [comment]
> This can be opinionated, which is why we are so flexible with configuring module files.

I understand that but Spack's default behavior is to set `C_INCLUDE_PATH`, `CPLUS_INCLUDE_PATH`, etc so it does not really seems consistent that it doesn't work only for the Intel Fortran compiler.

> Is the snippet above working for you (modulo typo I might have put in)?

I am sure something like that will work. If the default behavior of Spack cannot be changed so that it is consistent for all compilers, we will probably revert to always setting the CPATH with "prefix inspections" anyway (as we want that some packages compiled with GCC - mostly low-level libraries - works with ifort).

**Comment by RemiLacroix-IDRIS** [comment]
We reverted to using `CPATH` for the time being.

To keep the idea behind e3f97b3 I think a possible solution would be to use `__INTEL_PRE_FFLAGS` together with `-isystemdir`:
> You can insert command line options in the prefix position using `__INTEL_PRE_FFLAGS`

I find to look at the `prefix_inspection` syntax to know if it can be expressed directly in the configuration file.

Note that a similar issue exists with `LIBRARY_PATH` which is taken into account by most compilers except PGI/NVIDIA HPC compilers. Maybe the best way to fix this one is to tweak the `siterc`. I couldn't find any documented environment variables for this.

**Comment by haampie** [comment]
Closing this since these variables can be configured with `spack config add modules:prefix_inspections:./include:[CPATH]`
