### ISSUE TITLE
Installation issue: py-grpcio recipe fails with system ssl

### ISSUE THREAD

**Issue by ptooley** [LLNL/spack#19859]
The recipe for `py-grpcio` specifically looks for `self.spec[dep].libs.directories` and `self.spec[dep].headers.directories` entries for all dependencies, but these are not guaranteed to be present, for example in the case that the system openssl is used and only a prefix is specified:

### Steps to reproduce the issue

```console
cat <<EOF > ~/.spack/packages.yaml
packages:
  openssl:
    externals:
    - spec: openssl@1.1.1c
      prefix: /usr
EOF

$ spack install py-grpcio

==> Installing py-grpcio
==> No binary for py-grpcio found: installing from source
==> Error: IndexError: list index out of range

/home/phil/repos/spack/var/spack/repos/builtin/packages/py-grpcio/package.py:40, in setup_build_environment:
         37
         38        for dep in self.spec.dependencies(deptype='link'):
         39            query = self.spec[dep.name]
  >>     40            env.prepend_path('LIBRARY_PATH', query.libs.directories[0])
         41            env.prepend_path('CPATH', query.headers.directories[0])
```

### Information on your system

* **Spack:** 0.15.4-1886-9d5f4f9c6
* **Python:** 3.8.6
* **Platform:** linux-gentoo2-zen2

### Additional information

No build output as recipe fails too early.

No maintainers listed.

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by ptooley** [comment]
I have a workaround for this locally which simply ignores any IndexErrors raised during the for loop. This works for any system installed deps in expected locations, but if I had a prefix of `/opt/pkg/openssl` rather than `/usr` I suspect the build would fail.

```python
    for dep in self.spec.dependencies(deptype='link'):
        query = self.spec[dep.name]
        try:
            env.prepend_path('LIBRARY_PATH', query.libs.directories[0])
            env.prepend_path('CPATH', query.headers.directories[0])
        except IndexError:
            pass
```

**Comment by adamjstewart** [comment]
Even if you are using an external package for `openssl`, it should still be able to find the system libraries. Are your libraries in `/usr/lib` or `/usr/lib64`? If it's the latter, I think that's an easy fix.

**Comment by ptooley** [comment]
They're in `/usr/lib64`.

I'm not 100% clear on the Spack internals, are you says that given a prefix Spack should be automatically deducing the libdir and populating the `.libs.directories` list but currently is not?

**Comment by adamjstewart** [comment]
Yes, previously packages used `.prefix.lib`, but that was hardcoded to `<prefix>/lib`. We switched most packages to `.libs.directories[0]` as this will search for the library names in both `<prefix>/lib` and `<prefix>/lib64`. #19862 should fix your issue, there was a bug in how we search for OpenSSL libs.

**Comment by ptooley** [comment]
Fantastic. Thanks for the quick fix!
