### ISSUE TITLE
Error: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 0: invalid continuation byte

### ISSUE THREAD

**Issue by mathsen** [LLNL/spack#19867]
### Steps to reproduce the issue
I installed spack on a RedHat 7.9 system (develop branch) and try to install any package, e.g. ncurses

```console
$ spack install -v ncurses
```

### Error Message

The following error is shown:
```console
Error: UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 0: invalid continuation byte

/home/myuser/spack/lib/spack/spack/build_environment.py:863, in child_process:
        860            tb_string = traceback.format_exc()
        861
        862            # build up some context from the offending package so we can
  >>    863            # show that, too.
        864            package_context = get_package_context(tb)
        865
        866            build_log = None

Traceback (most recent call last):
  File "/home/myuser/spack/lib/spack/spack/build_environment.py", line 812, in child_process
    setup_package(pkg, dirty=dirty)
  File "/home/myuser/spack/lib/spack/spack/build_environment.py", line 729, in setup_package
    module('unload', 'cray-libsci')
  File "/home/myuser/spack/lib/spack/spack/util/module_cmd.py", line 39, in module
    env_output = str(module_p.communicate()[0].decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf0 in position 0: invalid continuation byte

```

### Information on your system

* **Spack:** 0.15.4-1902-e80276c
* **Python:** 3.6.8
* **Platform:** linux-rhel7-broadwell

Since spack ran fine for a long time, I did a git bisect, with the following results:
`dd3762d0f936aca41d11deb033e56d68d2036f2f is the first bad commit`
So [this](https://github.com/spack/spack/commit/dd3762d0f936aca41d11deb033e56d68d2036f2f) is the first bad commit, if I checkout a commit before I can build the package as expected.
I don't have the time today to look into the issue any longer, maybe someone has an idea?

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by mathsen** [comment]
I have an additional information:
Via the given Traceback I could find at least the function call, with which the problems start. In develop it's [line 64 in module_cmd](https://github.com/spack/spack/blob/527a81b469cf3df12e4b8c3bcd8609b2d55db2f3/lib/spack/spack/util/module_cmd.py#L64)
In the commit, where the proglems started [it's line 39](https://github.com/spack/spack/blob/dd3762d0f936aca41d11deb033e56d68d2036f2f/lib/spack/spack/util/module_cmd.py#L39)

If I change it to (develop):
`env_out` = str(module_p.communicate()[0].decode('cp850')).strip().split('\n')`

or in dd3762d0f936aca41d11deb033e56d68d2036f2f to:
 `env_output` = str(module_p.communicate()[0].decode('cp850'))

(just adding the 'cp850' encoding), everything works fine, as expected.
I don't think, that this is a "solution", to the real problem... I don't know enough about the underlying problem. Since this call to decode() was there for a longer time like this (even before dd3762d0f936aca41d11deb033e56d68d2036f2f) I think the real culprit is something else... maybe changes to the module_cmd in the commit? Maybe someone with deeper knowledge can help here?

**Comment by mathsen** [comment]
And another addition: The error is in connection with the shell that I use. With the workaround above I was able to use spack as usual and I installed zsh on the cluster and with this I gut revert the changes ('cp850') and I can build packages just fine. If I use system bash again the problem is back again... Strange that nobody else has such issues, since RHEL is pretty common, I guess.

**Comment by mathsen** [comment]
And problem is solved... it is caused by an Intel curl, that is installed on the cluster under "/usr/bin/flashupdt/curl" with an /etc/profile.d/intel.sh script... I realized this already some months ago and changed my PATH variable in .zshrc... therefore it worked in zsh but not in bash (which I used on a new account).
So everything is fine with spack - it was just I didn't realize that the error occurs because of a wrong curl binary and strange thing is that it does just occur after commit dd3762d0f936aca41d11deb033e56d68d2036f2f
Nevertheless it works now again so I close the issue with this comment.

**Comment by scheibelp** [comment]
Sorry we didn't get to this sooner, and thanks for following up with this!
