### ISSUE TITLE
Feature request: Can we have an 'extra verbose' option for install?

### ISSUE THREAD

**Issue by KineticTheory** [LLNL/spack#1986]
I frequently need to debug a failed build in spack.  At least for cmake-based packages, this would be much easier if the project was configured with `-DCMAKE_VERBOSE_MAKEFILE=ON` or equivalently, make was run with the option `VERBOSE=ON`.  Could one of these be the default?  This would save the detailed build instructions into spack-build.out, which is useful IMHO.  If that is not reasonable, maybe we could have a `-V` (very verbose) option for `spack install.`

What do you think?

Are there similar tricks that can be played with other build tools to increase their output verbosity?

**Comment by alalazo** [comment]
I vote for `-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON` to be added to `std_cmake_args`

**Comment by tgamblin** [comment]
@KineticTheory: we should have that stuff in the `std_cmake_args` in `build_environment.py` as @alalazo says.  I think it's an oversight that it's not there already.  Then it'll be on for all builds and it will get put in the `build.out` file, too.
