### ISSUE TITLE
Porting of Anuga code 

### ISSUE THREAD

**Issue by samcom12** [LLNL/spack#19877]
Dear Team,

Wanted to integrate Anuga code to spack list.
https://github.com/GeoscienceAustralia/anuga_core

**Comment by adamjstewart** [comment]
PRs are always welcome! It looks like Anuga is a simple Python program. In that case, the following docs may be helpful: https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html

I'm more than happy to review any PRs once you get a simple package working.

**Comment by samcom12** [comment]
@adamjstewart  I feel like need to go through python and porting python packages in Spack.
I tried it hard but couldn't succeed yet. 
Can I get help for porting the same?
