### ISSUE TITLE
Installation issue: llvm +cuda openmp and nvptx should probably be conditional

### ISSUE THREAD

**Issue by svenevs** [LLNL/spack#19879]
### Steps to reproduce the issue

```console
# mine is an external install but irrelevant
$ spack install cuda@11.1.0

$ spack install llvm@11.0.0 build_type=Release +clang~code_signing+cuda cuda_arch=61 +gold+internal+unwind~ipo+libcxx+lld+lldb~mlir~omp_debug~omp_tsan+polly+python~shared_libs~split_dwarf
```

### Discussion

https://github.com/spack/spack/blob/527a81b469cf3df12e4b8c3bcd8609b2d55db2f3/var/spack/repos/builtin/packages/llvm/package.py#L524-L526

**Important note**: I'm using CUDA 11.1 which they aren't ready for yet (10.2 latest "supported").

Refs:

- [Options for `NVPTX device RTL`](https://github.com/llvm/llvm-project/tree/llvmorg-11.0.0/openmp#options-for-nvptx-device-rtl)
- [D47394](https://reviews.llvm.org/D47394)
    - [Static only](https://stackoverflow.com/questions/35897002/cuda-nvcc-building-chain-of-libraries)?

Failure message something like (sorry, lost the logs in rebuild):

```
-- Performing Test LIBOMPTARGET_NVPTX_CUDA_COMPILER_SUPPORTS_FLAGS_REQUIRED
-- Performing Test LIBOMPTARGET_NVPTX_CUDA_COMPILER_SUPPORTS_FLAGS_REQUIRED - Failed
```

This one is quite entrenched, mostly posting issue so if other users hit this they know that they just need to edit the package and set this to false:

```diff
@@ -521,8 +539,11 @@ def post_install(self):
                     "-DCMAKE_INSTALL_PREFIX:PATH={0}".format(spec.prefix),
                 ]
                 cmake_args.extend(self.cmake_args())
+                # NOTE: line numbers wrong!!! i have other patches, look in post_install
                 cmake_args.append(
-                    "-DLIBOMPTARGET_NVPTX_ENABLE_BCLIB:BOOL=TRUE"
+                    "-DLIBOMPTARGET_NVPTX_ENABLE_BCLIB:BOOL=FALSE"
                 )
```

It's possible that using `sm_35` could cause this for me in [their detection code (see `FIXME`)](https://github.com/llvm/llvm-project/blob/llvmorg-11.0.0/openmp/libomptarget/cmake/Modules/LibomptargetNVPTXBitcodeLibrary.cmake), but more likely it's because I'm using CUDA 11.1 and the provided `libdevice.bc` is unusable for them.  We're having electrical issues and had to shut down the rigs I usually test build issues on so I can't do additional testing right now (need to finish tooling up this one...).  This build error raises a couple of questions:

1. Should `LIBOMPTARGET_NVPTX_ENABLE_BCLIB` be disabled if `+shared`?
2. It doesn't look like there's a way to disable openmp nvptx target, should there be?  (Couldn't see an obvious way to disable it in their cmake options either).  Some kind of `variant("omp_nvptx", ...)`?
3. Hypothesis: would not have this error using CUDA 10.2.  Should LLVM package start tracking officially supported versions and possibly disable this automatically instead of (2)?
    - Other than this build error and possibly switching off `LIBOMPTARGET_NVPTX_ENABLE_BCLIB`, newer CUDA is usually not an issue.  It just means you use an additional flag to squash some warnings, and you won't get any optimizations for the newer CUDA toolkit.  But presumably CUDA 11 and all the new goodies is making this specific component very difficult for them.
    - Theoretically, since we're in `post_install`, we could with a small amount of effort actually run [`LibomptargetNVPTXBitcodeLibrary.cmake`](https://github.com/llvm/llvm-project/blob/llvmorg-11.0.0/openmp/libomptarget/cmake/Modules/LibomptargetNVPTXBitcodeLibrary.cmake) to see if it can actually be used.
    - If this is done, what to do about `llvm@master`?

Again, only really posting to raise awareness of issue and temporary solution.  I will not be able to keep up with the discussion.

CC:
- LLVM maintainers: @trws @naromero77
- CUDA maintainers: @ax3l @Rombur

**Comment by trws** [comment]
If we change from true to false, the result is a compiler that will attempt to compile and link but fail to link nvptx OpenMP offload code.  The assertion that "the provided `lib device.bc` is unusable" intrigues me, it's built by the newly built compiler as a second phase, so it should work for whatever compiler/cuda you have as long as that cuda is supported by the LLVM being built.

Perhaps we should limit the cuda versions supported by the package more tightly, I've been somewhat loath to do that since the versions that are documented to work, and those that do, are not necessarily always the same, but it would avoid this particular issue.

**Comment by svenevs** [comment]
> If we change from true to false, the result is a compiler that will attempt to compile and link but fail to link nvptx OpenMP offload code.

Correct, but there's no option to disable libomp either (nor do I think there should be!).  I just need a CUDA capable LLVM, I'm not building a stack and don't depend on anything using OpenMP (need much finer control over data transfer).  It's only libomp that is unable to manage 11.1 right now.

> The assertion that "the provided lib device.bc is unusable" intrigues me, it's built by the newly built compiler as a second phase, so it should work for whatever compiler/cuda you have as long as that cuda is supported by the LLVM being built.

The version of CUDA I'm using is not "supported" (aka optimized for) by this LLVM version.  Their support is listed in [`clang/include/clang/Basic/Cuda.h`](https://github.com/llvm/llvm-project/blob/master/clang/include/clang/Basic/Cuda.h) (just listing as reference for readers).  `libdevice` is provided by the CUDA toolkit

```console
$ ls /usr/local/cuda-11.1/nvvm/libdevice/
libdevice.10.bc
```

In the past there used to be multiple files there per sm arch, but they consolidated at some point (I think either CUDA 8 or 9 but don't remember).  In the event that you are using a newer version, they emit instructions for the latest one they have optimized for (10.2 here) and give a warning [`-Wunknown-cuda-version`](https://clang.llvm.org/docs/DiagnosticsReference.html#wunknown-cuda-version) which can be disabled.

> I've been somewhat loath to do that since the versions that are documented to work, and those that do, are not necessarily always the same, but it would avoid this particular issue.

Hehehehe.  I'm totally on board, definitely ok with this being closed as #wontfix because it makes things much more complicated.  A warning from `spack` would be nice, but for people reading this, your best choice is to use the correct version of CUDA for the version of LLVM you are building :slightly_smiling_face:  There was a bugfix I needed in latest CUDA though so I don't have that as an option.

**Comment by naromero77** [comment]
LLVM 11.0.0 seems to work only up to CUDA 11.0.2.  I could not get it to work with CUDA 11.1.0. I was told that the build issue with LLVM and CUDA 11.1.0 was fixed in master.

Could someone please point me to where I can find the official versions of CUDA that are supported by LLVM?

I am OK with adding a Spack conflict to limit the version of CUDA that LLVM can use. But what I would like to avoid is trying to figure out the version of CUDA supported by trial and error.

Would this fix at least some of the issues?

**Comment by svenevs** [comment]
Closing as no longer relevant / outdated.
