### ISSUE TITLE
Installation issue: llvm attempts to link against the incorrect python and crashes as a result

### ISSUE THREAD

**Issue by robertu94** [LLNL/spack#19908]
### Steps to reproduce the issue

```console
#have a newer version of python installed on the system outside of spack
$ spack install llvm
...
```

### Information on your system

* **Spack:** 0.15.4-1825-08e825f47
* **Python:** 3.8.5
* **Platform:** linux-gentoo2-skylake

### Additional information

CMake find_package(Python3) doesn't honor the find_package(Python)'s `PYTHON_EXECUTABLE`, but prefers it to be called
`Python3_EXECUTABLE` instead.  However there is also a bug in compiler-rt upstream in LLVM that doesn't honor this variable either which just delays this problem to later on in the build process.

The following *mostly* fixes this if compiling LLVM against python3, but we also need to check what verison of python spack is building against and possibly set `Python2_EXECUTABLE` instead.

```python
cmake_args.append("-DPython3_EXECUTABLE:PATH={0}".format(spec["python"].command.path),)
```

@naromero77  @trws

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

[spack-build-env.txt](https://github.com/spack/spack/files/5539978/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/5539979/spack-build-out.txt)
[spack-configure-args.txt](https://github.com/spack/spack/files/5539980/spack-configure-args.txt)

**Comment by robertu94** [comment]
Here is the corresponding issue in LLVM https://bugs.llvm.org/show_bug.cgi?id=48180

**Comment by robertu94** [comment]
Here is the corresponding PR to LLVM https://reviews.llvm.org/D91536

**Comment by naromero77** [comment]
Thanks for posting here. Once the issue gets merged into LLVM master, we can figure out how to backport the patch to Spack.

**Comment by robertu94** [comment]
The fix has been merged into LLVM master @naromero77

**Comment by naromero77** [comment]
@trws I think it would be nice to back port this patch into Spack package. Do you agree?

@robertu94 Would you be willing to do a PR for Spack with a small patch? I have no idea how far back this issue goes.

**Comment by trws** [comment]
That seems reasonable, especially since python3 is only going to be more prevalent and I expect impacted versions to stay relevant for quite a while.

**Comment by robertu94** [comment]
@naromero77 what would you want in the patch?  Just code like above to add the Python3_EXECUTABLE, or a larger patch which backports the fix to AddCompilerRT.cmake to older versions of LLVM?  I'm happy to do the former, I'm not sure I want to do all of the testing to ensure I didn't break something else in an older LLVM with a backported patch.

**Comment by naromero77** [comment]
If I understand correctly, two things need to happen:
- We need to include this patch
https://reviews.llvm.org/D91536
- Plus we need to add these lines to the Spack package:
`cmake_args.append("-DPython3_EXECUTABLE:PATH={0}".format(spec["python"].command.path),)`

Correct?

If so, I would be happy if you could do a PR for LLVM 11.0. If it happened to work for LLVM 10.0.x, that would be gravy.

**Comment by robertu94** [comment]
We also need to specify `Python2_EXECUTABLE` if the user chose to depend on Python 2.7 instead of 3.  I'll try to upload a patch soon
