### ISSUE TITLE
Fix satisfaction rules for concrete specs

### ISSUE THREAD

**Issue by tgamblin** [LLNL/spack#1992]
From @adamjstewart:

> I'm still seeing a problem on our CentOS 6 cluster. Here is the output:
> 
> ```
> $ spack install gmp %pgi
> ==> Installing gmp
> ==> Installing m4
> ==> libsigsegv is already installed in /blues/gpfs/home/software/spack-0.9.1/opt/spack/linux-centos6-x86_64/pgi-16.5-0/libsigsegv-2.10-3zrk2bhqrgknreumylyvff2tzpqlrt2d
> Traceback (most recent call last):
>   File "/soft/spack-0.9.1/bin/spack", line 192, in <module>
>     main()
>   File "/soft/spack-0.9.1/bin/spack", line 169, in main
>     return_val = command(parser, args)
>   File "/blues/gpfs/home/software/spack-0.9.1/lib/spack/spack/cmd/install.py", line 97, in install
>     explicit=True)
>   File "/blues/gpfs/home/software/spack-0.9.1/lib/spack/spack/package.py", line 1007, in do_install
>     dirty=dirty)
>   File "/blues/gpfs/home/software/spack-0.9.1/lib/spack/spack/package.py", line 1007, in do_install
>     dirty=dirty)
>   File "/blues/gpfs/home/software/spack-0.9.1/lib/spack/spack/package.py", line 985, in do_install
>     rec = spack.installed_db.get_record(self.spec)
>   File "/blues/gpfs/home/software/spack-0.9.1/lib/spack/spack/database.py", line 79, in converter
>     return function(self, spec_like, *args, **kwargs)
>   File "/blues/gpfs/home/software/spack-0.9.1/lib/spack/spack/database.py", line 527, in get_record
>     key = self._get_matching_spec_key(spec, **kwargs)
>   File "/blues/gpfs/home/software/spack-0.9.1/lib/spack/spack/database.py", line 519, in _get_matching_spec_key
>     match = self.query_one(spec, **kwargs)
>   File "/blues/gpfs/home/software/spack-0.9.1/lib/spack/spack/database.py", line 653, in query_one
>     assert len(concrete_specs) <= 1
> AssertionError
> ```

Two things are going on here:
1. OS descriptors are read incorrectly and get assigned `None` if Spack doesn't know about the particular OS, which is wrong.
2. Concrete specs that have hashes should compare by hash for `satisfies()`.  This is faster, cheaper, _and_ it avoids cases where a concrete spec might match several non-concrete ones that have supersets of its attributes.

**Comment by tgamblin** [comment]
(2) is Related to #1377

**Comment by adamjstewart** [comment]
Any updates on this bug? I'm seeing it again, and it makes Spack unusable. For now, reverting back to 5988b3a2224076438bc13ff51bd13a74c7725573 helps, making me think this is related to #1562, or at least the problem wasn't introduced by #1562 but was revealed by it.

**Comment by tgamblin** [comment]
I'm actively working on this and other concretization bugs.
