### ISSUE TITLE
install --cache-only --only dependencies: build deps are excluded

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#19953]
Something changed recently such that `build` dependencies are not installed when running:
* `spack install --cache-only --only dependencies <spec>`

This breaks the pipeline workflow, which relies on being able to:
1. install all package dependencies from build cache, including build deps for (2)
 `spack install --cache-only --only dependencies <spec>`

2. build the package itself from source
`spack install --no-cache --only package <spec>`

I'm using:
* `spack@develop`
* 6fa6af1070908895b77d0ee35650b499971e2719
* `Tue Nov 17 02:41:07 2020 -0800`

@scottwittenburg @tgamblin @tldahlgren

**Comment by scottwittenburg** [comment]
@eugeneswalker I agree this should still work and is a bug if it doesn't.  Just as a heads up though: as of [ef0a555ca2](https://github.com/spack/spack/commit/ef0a555ca2711979e3374a57becb8c80efe695de), the pipeline workflow no longer depends on being able to do that.  If your pipeline is broken, then I think it must be something else, so let's get to the bottom of it.

**Comment by eugeneswalker** [comment]
> as of [ef0a555ca2](https://github.com/spack/spack/commit/ef0a555ca2711979e3374a57becb8c80efe695de), the pipeline workflow no longer depends on being able to do that

I hadn't realized that. Regardless, there must be a way to install all dependencies from cache, *including build dependencies*, from the command line, easily, in order to troubleshoot pipeline issues. Irrespective of whether the pipeline does this, it is necessary for troubleshooting.

Edit: Perhaps we need a new flag such as `--include-build-deps` that can be used in conjunction with `--cache-only`.
