### ISSUE TITLE
Installation issue: Mesa finds system cmake instead of Spack's cmake

### ISSUE THREAD

**Issue by EthanS94** [LLNL/spack#19979]
### Steps to reproduce the issue

```console
$ spack install -v mesa%gcc@8.3.0 ^cmake%clang ^python%clang ^llvm+shared_libs~clang~compiler-rt~gold~internal_unwind~libcxx~lld~lldb~polly
...
[+] /Users/stam/projects/spack/opt/spack/darwin-mojave-haswell/clang-10.0.1-apple/cmake-3.18.4-h3wyisgau2xqendkfrpt3mumbntsjfmb
...
Run-time dependency zlib found: YES 1.2.11
Found CMake: /Users/stam/anaconda2/envs/main/bin/cmake (3.12.2)
...

```

### Information on your system

* **Spack:** 0.16.0-3-b1dc3e787
* **Python:** 3.6.10
* **Platform:** darwin-mojave-haswell

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers @chuckatkins 
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by EthanS94** [comment]
@chuckatkins @v-dobrev ping . Have you run into this problem? Should there be a `depends_on(cmake)` in mesa's package file?

**Comment by v-dobrev** [comment]
Judging by https://gitlab.freedesktop.org/mesa/mesa/-/blob/master/meson.build, it looks like `cmake` may be used by the build system, at least in some cases. However, I'm not sure if `mesa` or `meson` should depend on `cmake` -- technically, I think `mesa` calls `meson` which then finds and calls `cmake`.

**Comment by chuckatkins** [comment]
It looks like CMake needs to be a runtime-only dependency of meson

**Comment by chuckatkins** [comment]
@EthanS94 does #20449 fix the issue for you?

**Comment by EthanS94** [comment]
@chuckatkins trying it out now. Thanks

**Comment by EthanS94** [comment]
@chuckatkins It worked! 

It looks like the same thing is needed for expat, possibly? Shortly after finding cmake, the meson build failed (on a compute node, so no internet access) with:
```
Run-time dependency expat found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency expat
Downloading expat source from https://github.com/libexpat/libexpat/releases/download/R_2_2_5/expat-2.2.5.tar.bz2
<urlopen error [Errno 101] Network is unreachable>
A fallback URL could be specified using source_fallback_url key in the wrap file

../meson.build:1355:2: ERROR: could not get https://github.com/libexpat/libexpat/releases/download/R_2_2_5/expat-2.2.5.tar.bz2 is the internet available?

A full log can be found at /tmp/stam/spack-stage/spack-stage-mesa-20.2.1-qhoprpxrgzdlzmyp7dzcgnyoyu7c2vb4/spack-src/spack-build/meson-logs/meson-log.txt
```

**Comment by EthanS94** [comment]
@chuckatkins Should I open a new issue for this expat problem?

I tried adding `depends_on('expat', type='run')` to meson's package.py which didn't fix it. Adding `depends_on(expat, type='build')` to mesa's package.py did fix it, but I'm not sure if that's the right thing to do.

**Comment by chuckatkins** [comment]
> @chuckatkins Should I open a new issue for this expat problem?
> 
> I tried adding `depends_on('expat', type='run')` to meson's package.py which didn't fix it. Adding `depends_on(expat, type='build')` to mesa's package.py did fix it, but I'm not sure if that's the right thing to do.

It should be applied to the mesa package.
