### ISSUE TITLE
Comments suggestions on petsc.py

### ISSUE THREAD

**Issue by BarrySmith** [LLNL/spack#1998]
1) PETSc doesn't depend on boost in any way so you can remove all the boost stuff.

2) Having system specific things in these spack files like

if sys.platform != "darwin":
            compiler_opts.extend([
                '--with-cpp=cpp',
                '--with-cxxcpp=cpp',
            ])

seems undesirable. Is there something we should add to PETSc ./configure so you don't need this stuff? 

3) Won't it be better if petsc.py used the PETSc tests to check if the build was successful instead of having its own custom tests?. To run the PETSc tests you first need to set PETSC_DIR to the INSTALLED location (but remain in the build directory) unset PETSC_ARCH and then run 
make test. We can add something to the output like Failed or Succeeded if you want that.

Why doesn't each package contain its spack xxxx.py file in its own repository instead of in the central spack repository? Then it would be the PETSc team's responsibility to manage it and keep it up to date.

**Comment by tgamblin** [comment]
@BarrySmith: can you put this over on #1999?
