### ISSUE TITLE
Installation issue: moab

### ISSUE THREAD

**Issue by iulian787** [LLNL/spack#20000]
```console
$ spack spec moab
```
This command does not work on develop; it works on releases/v0.16 on my laptop
If I try this on my laptop (ubuntu 18.04) or on a workstation with ubuntu 14.04, I get this error; how do I track which one is the dependency that is troublesome for blas/openblas/flexiblas lapack?
```console
$ spack spec moab
Input spec
--------------------------------
moab

Concretized
--------------------------------
==> Error: Conflicts in concretized spec "moab@5.0.2%gcc@7.5.0~cgm+coupler~dagmc~debug~fbigeom+fortran+hdf5~irel+metis+mpi~netcdf+parmetis~pnetcdf~shared~zoltan arch=linux-ubuntu18.04-skylake/7apj6yy"

List of matching conflicts for spec:

    openblas@0.3.12%gcc@7.5.0~consistent_fpcsr~ilp64+pic+shared threads=none arch=linux-ubuntu18.04-skylake

1. "%gcc@:8.2.99" conflicts with "openblas@0.3.11:"
```
Actually, I have this on my laptop
```console
$ spack spec blas
Input spec
--------------------------------
blas

Concretized
--------------------------------
==> Error: Conflicts in concretized spec "openblas@0.3.12%gcc@7.5.0~consistent_fpcsr~ilp64+pic+shared threads=none arch=linux-ubuntu18.04-skylake/ewrbb3x"

List of matching conflicts for spec:

    openblas@0.3.12%gcc@7.5.0~consistent_fpcsr~ilp64+pic+shared threads=none arch=linux-ubuntu18.04-skylake

1. "%gcc@:8.2.99" conflicts with "openblas@0.3.11:"
```
So "blas" itself is not building ? How do I read this ?

**Comment by iulian787** [comment]
OK, I noticed that blas itself does not exist as a spack package
spack edit blas 
spack edit blas
==> Error: No package for 'blas' was found.
    Use `spack create` to create a new package

**Comment by adamjstewart** [comment]
> I noticed that blas itself does not exist as a spack package

Spack has a concept of virtual packages (like blas or mpi) that can be provided by multiple libraries (openblas, intel-mkl, mpich, openmpi). That's why `blas` itself doesn't exist as a package.

> How do I read this?

This error message means that `moab` depends on some `blas` library, and `openblas` is the default. But the latest version of `openblas` does not support your older GCC compiler. You have many options to resolve this:

Choose a different blas provider:
```console
$ spack spec moab ^intel-mkl
```
Choose a different compiler:
```console
$ spack spec moab %intel
```
Choose a different version of openblas:
```console
$ spack spec moab ^openblas@0.3.10
```
Alternatively, the new concretizer is designed to solve this kind of problem.

**Comment by iulian787** [comment]
so the issue appears for any package that has "depends_on('blas')"

**Comment by adamjstewart** [comment]
The issue appears for any package that depends on blas if you have an older GCC compiler that isn't supported by the latest version of openblas. The issue only occurs if you are using the old concretizer (currently the default), so I suggest that anyone who runs into this try out the new concretizer.

**Comment by iulian787** [comment]
thanks Adam!
