### ISSUE TITLE
Issue with clingo concretizer

### ISSUE THREAD

**Issue by jacobmerson** [LLNL/spack#20044]
I get an error when trying to use the new clingo concretizer with an invalid keyword argument.

### Steps to reproduce the issue

```console
$ spack spec python # same issue trying to get any spec 
```

### Error Message
```console
$ spack -d --stacktrace spec python
lib/spack/spack/cmd/__init__.py:122 ==> [2020-11-21-18:02:36.921608] Imported spec from built-in commands
lib/spack/spack/cmd/__init__.py:122 ==> [2020-11-21-18:02:36.922823] Imported spec from built-in commands
Input spec
--------------------------------
python

Concretized
--------------------------------
lib/spack/spack/config.py:907 ==> [2020-11-21-18:02:36.930440] Reading config file /home/mersoj/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:907 ==> [2020-11-21-18:02:36.962138] Reading config file /home/mersoj/.spack/config.yaml
lib/spack/spack/config.py:907 ==> [2020-11-21-18:02:36.972896] Reading config file /home/mersoj/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:907 ==> [2020-11-21-18:02:37.231508] Reading config file /home/mersoj/.spack/linux/compilers.yaml
lib/spack/spack/config.py:907 ==> [2020-11-21-18:02:37.247611] Reading config file /home/mersoj/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/config.py:907 ==> [2020-11-21-18:02:37.282880] Reading config file /home/mersoj/.spack/packages.yaml
Traceback (most recent call last):
  File "/home/mersoj/spack/bin/spack", line 66, in <module>
    sys.exit(spack.main.main())
  File "/home/mersoj/spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "/home/mersoj/spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "/home/mersoj/spack/lib/spack/spack/cmd/spec.py", line 102, in spec
    spec.concretize()
  File "/home/mersoj/spack/lib/spack/spack/spec.py", line 2469, in concretize
    self._new_concretize(tests)
  File "/home/mersoj/spack/lib/spack/spack/spec.py", line 2445, in _new_concretize
    result = spack.solver.asp.solve([self], tests=tests)
  File "/home/mersoj/spack/lib/spack/spack/solver/asp.py", line 1838, in solve
    return driver.solve(setup, specs, dump, models, timers, stats, tests)
  File "/home/mersoj/spack/lib/spack/spack/solver/asp.py", line 643, in solve
    solve_result = self.control.solve(
TypeError: 'on_core' is an invalid keyword argument for this function
```

### Information on your system
* **Spack:** 0.16.0-32-4609a126b
* **Python:** 3.8.5
* **Platform:** linux-ubuntu20.04-broadwell
* **Concretizer:** clingo

```console
$ clingo --version
clingo version 5.4.0
Address model: 64-bit

libclingo version 5.4.0
Configuration: with Python 3.8.5, without Lua

libclasp version 3.3.5 (libpotassco version 1.1.0)
Configuration: WITH_THREADS=1
Copyright (C) Benjamin Kaufmann

License: The MIT License <https://opensource.org/licenses/MIT>
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
Spack's new concretizer currently requires `clingo@master+python`, you need to install a newer version of the concretizer.

@alalazo is there somewhere we can document this so that it is more obvious?

**Comment by jacobmerson** [comment]
That worked...Is there an option to give the path to clingo in the `config.yaml`? Otherwise I guess I can just put `spack load clingo` into my `.bashrc`.

**Comment by adamjstewart** [comment]
`spack load` works, or you can set `PATH` and `PYTHONPATH` directly. I use an environment to do this.

**Comment by maxim-belkin** [comment]
I can confirm that this issue still exists with Clingo "v5.4.1" (which reports that it's v5.4.0 btw) and that building from the git repo solves the problem (at which time it reports that it's v5.5.0).

**Comment by alalazo** [comment]
Just a heads up that there's work ongoing to properly bootstrap clingo for Spack:
- We recently merged #20652 introducing a package with options that would help with bootstrapping clingo, both from sources and binaries
-  We are currently working towards reviewing and merging #20207. When that is done  `clingo` will be bootstrappable from sources on any linux with GCC > 6.X or MacOS if Apple Clang supports C++14 (we'll add proper docs for that). 
- The step afterwards would be to build on #20098 to be able to bootstrap from a public binary cache

**Comment by alalazo** [comment]
@jacobmerson Can you please double check if this is solved in `develop`? I can't reproduce the error and I think it was related to missing support for the clingo version based on cffi.

**Comment by jacobmerson** [comment]
I think this is working now with develop (it works on my system).
