### ISSUE TITLE
Installation issue: h5cpp has invalid checksum

### ISSUE THREAD

**Issue by Nischay-Pro** [LLNL/spack#20046]
### Steps to reproduce the issue

```console
$ spack install h5cpp
```

### Information on your system

* **Spack:** 0.16.0-32-4609a126b
* **Python:** 3.6.8
* **Platform:** linux-centos8-broadwell
* **Concretizer:** original

### Additional information

Invalid SHA256 Checksum

Checksum in spack package module: 42d0ca1aaff1ead8998a26d892a51c12b1b89023382f191dc438bd0fa4513455
Checksum upstream: 661ccc4d76e081afc73df71ef11d027837d92dd1089185f3650afcaec9d418ec

@eschnett

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by eschnett** [comment]
I confirm the problem. I don't know what caused it – maybe the tarball changed. I assume that updating the checksum is the right thing to do.

There is now also a newer release `h5cpp-1.10.4-6` available.

**Comment by Nischay-Pro** [comment]
Thanks for the confirmation Erik. I corrected the checksum and tried building the package again. But now I'm facing a CMAKE build error.

I'm attaching some build and error logs. 

[spack-build-out.txt](https://github.com/spack/spack/files/5581099/spack-build-out.txt)
[CMakeOutput.log](https://github.com/spack/spack/files/5581100/CMakeOutput.log)

From the error message it looks like CMAKE is unable to find the HDF5 libraries as it's showing `Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS) (found version "")`.  

It is possible to fix this issue by setting the `dirty` flag in spack install and manually setting the environment variables for it. But then it is more of a temporary hack rather than proper fix.
