### ISSUE TITLE
Distribution of binaries via SPACK

### ISSUE THREAD

**Issue by mariXanna** [LLNL/spack#20094]
Hello,
Is there a way to distribute pre-built binaries via SPACK? 
I realize that building from sources is the main workflow for spack packages, but there are several places in documentation mentioning binary packages, binary caches and binary mirrors, so I guess it possible. However, I cannot find more information on that. 'spack create' help has no options regarding composing package from just binaries without using source code. 
Could you give me a hint where to find some information/instructions if it is possible in general.
Thanks.

**Comment by vvolkl** [comment]
There are some recipes that have to do this for various reasons, but it is definitely to be avoided (in my opinion). Take a look at  [openjdk](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/openjdk/package.py) or [pandoc](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/pandoc/package.py).

**Comment by mariXanna** [comment]
will have a look
thanks!
