### ISSUE TITLE
Installation issue: py-numpy with GCC 7.5

### ISSUE THREAD

**Issue by ax3l** [LLNL/spack#20100]
### Steps to reproduce the issue

```console
$  spack install py-numpy %gcc@7.5.0
```

### Information on your system

Ubuntu 20.04 on x86_64

### Additional information

```
==> Error: Conflicts in concretized spec "py-numpy@1.19.4%gcc@7.5.0+blas+lapack arch=linux-ubuntu20.04-skylake/lwh4kwo"
List of matching conflicts for spec:

    openblas@0.3.12%gcc@7.5.0~consistent_fpcsr~ilp64+pic+shared threads=none arch=linux-ubuntu20.04-skylake

1. "%gcc@:8.2.99" conflicts with "openblas@0.3.11:"
```

I think the concretizer should pick an older version of openblas here. cc @tgamblin 

Related to #19932 #19975

### General information

- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers: @adamjstewart 
- [ ] I have uploaded the build log and environment files
- [ ] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
@ax3l Maybe OT, but I think #20020 and:
```console
$ spack solve py-numpy %gcc@7.5.0
[ ... ]
```
will be able to concretize correctly. Note you need to have `clingo@spack` importable in Spack's Python interpreter before you can use the new concretizer.

**Comment by ax3l** [comment]
Nice :tada: 

Should we independent of that default to `openblas@0.3.10` as preferred until the new concretizer lands?

**Comment by adamjstewart** [comment]
The `openblas` package doesn't have any maintainers listed, so apparently no one cares about it. Feel free to change the default version if you want.

**Comment by ax3l** [comment]
Actually, if I just make the conflict more precise with this new info: https://github.com/spack/spack/issues/19932#issuecomment-733452619 my specific problem will be solvable ;-)
