### ISSUE TITLE
Installation issue: openmpi doesn't configure lustre for romio

### ISSUE THREAD

**Issue by loveshack** [LLNL/spack#20138]
### Steps to reproduce the issue

```console
$ spack install openmpi +lustre
```
doesn't produce a lustre-enabled romio, just an ompio (which isn't meant to be the default on lustre).
I'll supply a fix for the extra configure flag in a bit, but I don't see how to do it properly with +gpfs as the default.

**Comment by sethrj** [comment]
Closing as unverified and missing details. The OpenMPI package has also probably changed a lot in a year and a quarter.
