### ISSUE TITLE
Installation issue: openmpi shouldn't require pmi with slurm and legacylaunchers

### ISSUE THREAD

**Issue by loveshack** [LLNL/spack#20140]
Currently openmpi requires pmi when configured for slurm as the scheduler. That's not necessary, and may fail, when using legacylaunchers.  It failed for me building against a slurm installation  which doesn't have development files for its bundled pmi.
I'll supply a fix.

**Comment by alalazo** [comment]
@hppritcha

**Comment by sethrj** [comment]
Closing as unverified and missing details. The OpenMPI package has also probably changed a lot in a year and a quarter.
