### ISSUE TITLE
module function not available after module load environment-modules in 0.16.0-80-7c26a10de

### ISSUE THREAD

**Issue by varioustoxins** [LLNL/spack#20154]
### Steps to reproduce the issue

```console
# install the latest version 0.16.0-80-7c26a10de
spack --version
0.16.0
spack install environment-modules
. ~/programs/spack/share/spack/setup-env.sh
spack load environment-modules
module
bash: module: command not found
declare -F
...
declare -f _spack_view_rm
declare -f _spack_view_soft
declare -f _spack_view_statlink
declare -f _spack_view_status
declare -f _spack_view_symlink
declare -f _spacktivate
declare -f _subcommands
declare -f _test_vars
declare -f _tests
declare -fx spack
```
repeat on exactly the same machine with version 0.15.4-1503-8619e5b5a

```console
spack --version
0.15.4-1503-8619e5b5a

Modules Release 4.6.0 (2020-09-16)
Usage: module [options] [command] [args ...]

Loading / Unloading commands:
  add | load      modulefile [...]  Load modulefile(s)
  rm | unload     modulefile [...]  Remove modulefile(s)
  purge                             Unload all loaded modulefiles
  reload | refresh                  Unload then load all loaded modulefiles
  switch | swap   [mod1] mod2       Unload mod1 and load mod2
...

declare -f _spack_view_rm
declare -f _spack_view_soft
declare -f _spack_view_statlink
declare -f _spack_view_status
declare -f _spack_view_symlink
declare -f _spacktivate
declare -f _subcommands
declare -f _test_vars
declare -f _tests
declare -f conda
**declare -f module**
declare -fx spack
```

### Information on your system

* **Spack:** 0.16.0-80-7c26a10de
* **Python:** 3.8.3
* **Platform:** darwin-catalina-haswell
* **Concretizer:** original

vs

* **Spack:** 0.15.4-1503-8619e5b5a
* **Python:** 3.8.3
* **Platform:** darwin-catalina-haswell

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

==> [2020-11-28-19:56:22.231623, 43472] Imported load from built-in commands
==> [2020-11-28-19:56:22.233450, 43472] Imported load from built-in commands
==> [2020-11-28-19:56:22.237207, 43472] Reading config file /Users/gst9/programs/spack-0.16/spack/etc/spack/defaults/config.yaml
==> [2020-11-28-19:56:22.273318, 43472] DATABASE LOCK TIMEOUT: 3s
==> [2020-11-28-19:56:22.273447, 43472] PACKAGE LOCK TIMEOUT: No timeout
==> [2020-11-28-19:56:22.273744, 43472] READ LOCK (database): /Users/gst9/programs/spack-0.16/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2020-11-28-19:56:22.274171, 43472] read locking [0:0]: timeout 3 sec
==> [2020-11-28-19:56:22.274317, 43472] READ LOCK (database): /Users/gst9/programs/spack-0.16/spack/opt/spack/.spack-db/lock[0:0] [Acquired at 19:56:22.274265]
==> [2020-11-28-19:56:22.275898, 43472] Reading config file /Users/gst9/programs/spack-0.16/spack/etc/spack/defaults/repos.yaml
==> [2020-11-28-19:56:22.278241, 43472] Reading config file /Users/gst9/.spack/repos.yaml
==> [2020-11-28-19:56:22.409374, 43472] READ LOCK (database): /Users/gst9/programs/spack-0.16/spack/opt/spack/.spack-db/lock[0:0] [Releasing]
==> [2020-11-28-19:56:22.409611, 43472] READ LOCK (database): /Users/gst9/programs/spack-0.16/spack/opt/spack/.spack-db/lock[0:0] [Released at 19:56:22.409535]
==> [2020-11-28-19:56:22.409988, 43472] READ LOCK (database): /Users/gst9/programs/spack-0.16/spack/opt/spack/.spack-db/lock[0:0] [Acquiring]
==> [2020-11-28-19:56:22.410324, 43472] read locking [0:0]: timeout 3 sec
==> [2020-11-28-19:56:22.410466, 43472] READ LOCK (database): /Users/gst9/programs/spack-0.16/spack/opt/spack/.spack-db/lock[0:0] [Acquired at 19:56:22.410410]
==> [2020-11-28-19:56:22.411086, 43472] Reading config file /Users/gst9/programs/spack-0.16/spack/etc/spack/defaults/modules.yaml
==> [2020-11-28-19:56:22.428375, 43472] Reading config file /Users/gst9/programs/spack-0.16/spack/etc/spack/defaults/darwin/modules.yaml
==> [2020-11-28-19:56:22.487629, 43472] Reading config file /Users/gst9/.spack/darwin/compilers.yaml
==> [2020-11-28-19:56:22.563811, 43472] READ LOCK: /Users/gst9/.spack/cache/providers/.builtin-index.json.lock[0:0] [Acquiring]
==> [2020-11-28-19:56:22.564248, 43472] read locking [0:0]: timeout 120 sec
==> [2020-11-28-19:56:22.564459, 43472] READ LOCK: /Users/gst9/.spack/cache/providers/.builtin-index.json.lock[0:0] [Acquired at 19:56:22.564382]
==> [2020-11-28-19:56:22.595883, 43472] READ LOCK: /Users/gst9/.spack/cache/providers/.builtin-index.json.lock[0:0] [Releasing]
==> [2020-11-28-19:56:22.596080, 43472] READ LOCK: /Users/gst9/.spack/cache/providers/.builtin-index.json.lock[0:0] [Released at 19:56:22.596038]
==> [2020-11-28-19:56:22.599572, 43472] READ LOCK: /Users/gst9/.spack/cache/tags/.builtin-index.json.lock[0:0] [Acquiring]
==> [2020-11-28-19:56:22.599838, 43472] read locking [0:0]: timeout 120 sec
==> [2020-11-28-19:56:22.599978, 43472] READ LOCK: /Users/gst9/.spack/cache/tags/.builtin-index.json.lock[0:0] [Acquired at 19:56:22.599927]
==> [2020-11-28-19:56:22.600540, 43472] READ LOCK: /Users/gst9/.spack/cache/tags/.builtin-index.json.lock[0:0] [Releasing]
==> [2020-11-28-19:56:22.600699, 43472] READ LOCK: /Users/gst9/.spack/cache/tags/.builtin-index.json.lock[0:0] [Released at 19:56:22.600661]
==> [2020-11-28-19:56:22.604091, 43472] READ LOCK: /Users/gst9/.spack/cache/patches/.builtin-index.json.lock[0:0] [Acquiring]
==> [2020-11-28-19:56:22.604382, 43472] read locking [0:0]: timeout 120 sec
==> [2020-11-28-19:56:22.604495, 43472] READ LOCK: /Users/gst9/.spack/cache/patches/.builtin-index.json.lock[0:0] [Acquired at 19:56:22.604460]
==> [2020-11-28-19:56:22.620091, 43472] READ LOCK: /Users/gst9/.spack/cache/patches/.builtin-index.json.lock[0:0] [Releasing]
==> [2020-11-28-19:56:22.620276, 43472] READ LOCK: /Users/gst9/.spack/cache/patches/.builtin-index.json.lock[0:0] [Released at 19:56:22.620239]
==> [2020-11-28-19:56:22.629189, 43472] READ LOCK: /Users/gst9/.spack/cache/providers/.nmrpack-index.json.lock[0:0] [Acquiring]
==> [2020-11-28-19:56:22.629767, 43472] read locking [0:0]: timeout 120 sec
==> [2020-11-28-19:56:22.629983, 43472] READ LOCK: /Users/gst9/.spack/cache/providers/.nmrpack-index.json.lock[0:0] [Acquired at 19:56:22.629919]
==> [2020-11-28-19:56:22.630378, 43472] READ LOCK: /Users/gst9/.spack/cache/providers/.nmrpack-index.json.lock[0:0] [Releasing]
==> [2020-11-28-19:56:22.630551, 43472] READ LOCK: /Users/gst9/.spack/cache/providers/.nmrpack-index.json.lock[0:0] [Released at 19:56:22.630488]
==> [2020-11-28-19:56:22.631360, 43472] READ LOCK: /Users/gst9/.spack/cache/tags/.nmrpack-index.json.lock[0:0] [Acquiring]
==> [2020-11-28-19:56:22.632416, 43472] read locking [0:0]: timeout 120 sec
==> [2020-11-28-19:56:22.632880, 43472] READ LOCK: /Users/gst9/.spack/cache/tags/.nmrpack-index.json.lock[0:0] [Acquired at 19:56:22.632817]
==> [2020-11-28-19:56:22.633647, 43472] READ LOCK: /Users/gst9/.spack/cache/tags/.nmrpack-index.json.lock[0:0] [Releasing]
==> [2020-11-28-19:56:22.633884, 43472] READ LOCK: /Users/gst9/.spack/cache/tags/.nmrpack-index.json.lock[0:0] [Released at 19:56:22.633836]
==> [2020-11-28-19:56:22.634335, 43472] READ LOCK: /Users/gst9/.spack/cache/patches/.nmrpack-index.json.lock[0:0] [Acquiring]
==> [2020-11-28-19:56:22.634784, 43472] read locking [0:0]: timeout 120 sec
==> [2020-11-28-19:56:22.634949, 43472] READ LOCK: /Users/gst9/.spack/cache/patches/.nmrpack-index.json.lock[0:0] [Acquired at 19:56:22.634909]
==> [2020-11-28-19:56:22.635269, 43472] READ LOCK: /Users/gst9/.spack/cache/patches/.nmrpack-index.json.lock[0:0] [Releasing]
==> [2020-11-28-19:56:22.635587, 43472] READ LOCK: /Users/gst9/.spack/cache/patches/.nmrpack-index.json.lock[0:0] [Released at 19:56:22.635538]
==> [2020-11-28-19:56:22.650887, 43472] READ LOCK (database): /Users/gst9/programs/spack-0.16/spack/opt/spack/.spack-db/lock[0:0] [Releasing]
==> [2020-11-28-19:56:22.651159, 43472] READ LOCK (database): /Users/gst9/programs/spack-0.16/spack/opt/spack/.spack-db/lock[0:0] [Released at 19:56:22.651116]

**Comment by varioustoxins** [comment]
this maybe an OS X problem, 

~/programs/spack/share/spack/setup-env.sh has

```
#
# make available environment-modules
#
if [ "${need_module}" = "yes" ]; then
    **eval `spack --print-shell-vars sh,modules`**
    # _sp_module_prefix is set by spack --print-sh-vars
    if [ "${_sp_module_prefix}" != "not_installed" ]; then
        # activate it!
        # environment-modules@4: has a bin directory inside its prefix
```

so it depends on the output from spack --print-shell-vars sh,modules

on my  osx 

 ```
spack --print-shell-vars sh,modules gives 

_sp_sys_type='darwin-catalina-cannonlake'
_sp_compatible_sys_types='darwin-catalina-cannonlake:darwin-catalina-skylake:darwin-catalina-broadwell:darwin-catalina-haswell:darwin-catalina-ivybridge:darwin-catalina-sandybridge:darwin-catalina-westmere:darwin-catalina-nehalem:darwin-catalina-core2:darwin-catalina-nocona:darwin-catalina-x86_64'
_sp_tcl_roots='/Users/garythompson/programs/spack/share/spack/modules'
_sp_lmod_roots='/Users/garythompson/programs/spack/share/spack/lmod'
_sp_module_prefix='not_installed'
```

so it doesn't detect modules as being installed, however

spack install environment-modules gives
```
[+] /Users/garythompson/programs/spack/opt/spack/darwin-catalina-cannonlake/apple-clang-12.0.0/zlib-1.2.11-intwx3w44icehrr4dkt4e3oanswrjhlp
[+] /Users/garythompson/programs/spack/opt/spack/darwin-catalina-cannonlake/apple-clang-12.0.0/tcl-8.6.10-xdljjm2wszwls6bbqgoui4i47odcfcgx
[+] /Users/garythompson/programs/spack/opt/spack/darwin-catalina-cannonlake/apple-clang-12.0.0/environment-modules-4.6.1-455cjmpoffe6zgqhzjsxjmtckf2rzmcv

```

the problem seems to be in main.py

   ```
 # print environment module system if available. This can be expensive
    # on clusters, so skip it if not needed.
    if 'modules' in info:
        generic_arch = archspec.cpu.host().family
        module_spec = 'environment-modules target={0}'.format(generic_arch)
        specs = spack.store.db.query(module_spec)
        if specs:
            shell_set('_sp_module_prefix', specs[-1].prefix)
        else:
            shell_set('_sp_module_prefix', 'not_installed')
```

as module_spec is set to 'environment-modules target=x86_64' which gives an empty spec on osx

indeed on my Mac  I get the following outputs to find

```
eniac-2:programs garythompson$ spack find target=x86_64
==> No package matches the query: target=x86_64
eniac-2:programs garythompson$ spack find target=cannonlake
==> 4 installed packages
-- darwin-catalina-cannonlake / apple-clang@12.0.0 --------------
environment-modules@4.6.1  nmrpipe@2020.219.15.07  tcl@8.6.10  zlib@1.2.11  
```

hope this helps, why does the find need to be for an x86_64 environment?

**Comment by varioustoxins** [comment]
I should add that after removing the x86_64 requirement

```
    if 'modules' in info:
        generic_arch = archspec.cpu.host().family
        module_spec = 'environment-modules'#
        specs = spack.store.db.query(module_spec)
        if specs:
            shell_set('_sp_module_prefix', specs[-1].prefix)
        else:
            shell_set('_sp_module_prefix', 'not_installed')
```

 it now works

```
source  ~/programs/spack/share/spack/setup-env.sh
eniac-2:programs garythompson$ module avail
------------------------------------------------------------ /Users/garythompson/programs/spack/share/spack/modules/darwin-catalina-cannonlake -------------------------------------------------------------
environment-modules-4.6.1-apple-clang-12.0.0-455cjmp  nmrpipe-2020.219.15.07-apple-clang-12.0.0-kf64rbf  tcl-8.6.10-apple-clang-12.0.0-xdljjm2  zlib-1.2.11-apple-clang-12.0.0-intwx3w
```

**Comment by alalazo** [comment]
Closing, since behavior changed a lot since here. First change was in #24545 The `environment-modules` package contains a few init files which correctly setup the environment.
