### ISSUE TITLE
@when and @run_after do not work together

### ISSUE THREAD

**Issue by sethrj** [LLNL/spack#20177]
In https://github.com/spack/spack/pull/20078 I wanted to enable a `@run_after('install')` code section restricted by `@when('+doc')`.  I searched the spack packages with `grep -C1 '@run_after'` and found the only existing combination construction to be `@when/@run_after` in the OpenMPI and Nest packages:
```console
$ grep -C1 '@run_after' openmpi/package.py
    @when('+wrapper-rpath')
    @run_after('install')
    def filter_rpaths(self):
...
```

I couldn't find any documentation specifically about when/run_after, but another search for `run_after` leads me to [a warning in the custom build system](https://spack.readthedocs.io/en/latest/build_systems/custompackage.html?highlight=run_after%20when#testing) and https://github.com/spack/spack/issues/3833 . So it looks like MPI's `@when` restriction being ignored.

### Steps to reproduce the issue

I added a post-install method to a fast-building package:
```diff
diff --git a/var/spack/repos/builtin/packages/zlib/package.py b/var/spack/repos/
index 0d30f2d67..c1f849421 100644
--- a/var/spack/repos/builtin/packages/zlib/package.py
+++ b/var/spack/repos/builtin/packages/zlib/package.py
@@ -53,3 +53,9 @@ def install(self, spec, prefix):
         if self.run_tests:
             make('check')
         make('install')
+
+    @when('+shared')
+    @run_after('install')
+    def post_install(self):
+        import llnl.util.tty as tty
+        tty.warn("It ran, dingus")
```

The warning message prints when installing both `+shared` and `~shared`, which is not expected.

### Error Message

Reversing the `@when/@run_after` lines succeeds when `+shared` but crashes after building and installing `~shared`:
```
Traceback (most recent call last):
  File "/projects/spack2020/lib/spack/spack/build_environment.py", line 847, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/projects/spack2020/lib/spack/spack/installer.py", line 1674, in build_process
    phase(pkg.spec, pkg.prefix)
  File "/projects/spack2020/lib/spack/spack/package.py", line 113, in phase_wrapper
    callback(instance)
  File "/projects/spack2020/lib/spack/spack/multimethod.py", line 154, in __call__
    [m[0] for m in self.method_list]
NoSuchMethodError: Package Zlib does not support post_install called with zlib@1.2.11%gcc@10.2.0~optimize+pic~shared arch=linux-rhel7-haswell.  Options are: +shared
```

### Information on your system

```
$ spack debug report
* **Spack:** 0.16.0-32-4609a12
* **Python:** 2.7.5
* **Platform:** linux-rhel7-haswell
* **Concretizer:** original
```

**Comment by sethrj** [comment]
This is the same error message that @scheibelp reported in https://github.com/spack/spack/pull/8092#issuecomment-388434136 two years ago 😬 . Since several packages have mistakenly added the wrong `@when` construction (and it doesn't fail), maybe there needs to be some additional error checking in place preventing multiple decorators from being applied in the wrong order?

**Comment by adamjstewart** [comment]
Also see #3833

**Comment by adamjstewart** [comment]
Duplicate of #12736?

**Comment by sethrj** [comment]
Oh yep, guess it is indeed  a duplicate. Closing in favor of that one.
