### ISSUE TITLE
New concretizer picks random variant

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#20171]
### Steps to reproduce the issue

The new concretizer picks a non-deterministic value for `api` in `hdf5`, where `none` is the default:

```console
$ spack spec hdf5
hdf5@1.10.7%gcc@10.2.0~cxx~debug~fortran~hl~java+mpi+pic+shared~szip~threadsafe api=v18 arch=linux-ubuntu20.04-zen2

$ spack spec hdf5
hdf5@1.10.7%gcc@10.2.0~cxx~debug~fortran~hl~java+mpi+pic+shared~szip~threadsafe api=v110 arch=linux-ubuntu20.04-zen2
```

### Information on your system

* **Spack:** 0.16.0-102-623caf85a9
* **Python:** 3.8.6
* **Platform:** linux-ubuntu20.04-zen2
* **Concretizer:** clingo

**Comment by alalazo** [comment]
@haampie I have seen this happening a couple of times when two or more solutions are "equally optimal" (i.e. they give the same optimal results for minimizations / maximizations in the solver). In this case it may not be straightforward, but the issue points out an inconsistency in the `hdf5` package: the default value is not among the allowed values.

That said, if you add `none` among the `values` and you have a conflict from a dependent on `api=none`, then you are in the same situation where a random value is picked.

**Comment by haampie** [comment]
Shouldn't the optimum here be 'as few values as possible' and isn't 'none' supposed to mean empty set?

The `api` variant is multi-valued, so I guess `none` is supposed to mean Ø / none of the above.

**Comment by alalazo** [comment]
> Shouldn't the optimum here be 'as few values as possible' and isn't 'none' supposed to mean empty set?

None of the above. The variant, as far as I can see, is single-valued:
```python
variant('api', default='none', description='choose api compatibility', values=('v114', 'v112', 'v110', 'v18', 'v16'), multi=False)
```
since it has a `multi=false`. It's basically an enum i.e. you can't ask for `api=v114,v16`. I think what you are referring to are variants declared with `any_combination_of`.

**Comment by haampie** [comment]
Oh sorry, I didn't checkout the package.py as much, just glanced over it and remembered it had something with `multi` :p.

In which case we should ping @lrknox to check what the default value should be, or whether none should be a viable option.

**Comment by alalazo** [comment]
In any case this is a valid issue, it would just happen in more complex cases.

**Comment by aweits** [comment]
"the default value is not among the allowed values."
from lib/spack/spack/variant.py:
```
            # Otherwise assume values is the set of allowed explicit values
            self.values = values
            allowed = tuple(self.values) + (self.default,)
            self.single_value_validator = lambda x: x in allowed
```
?

**Comment by haampie** [comment]
So you are saying it is a bug in spack @aweits? Not an issue of the package?

**Comment by aweits** [comment]
> So you are saying it is a bug in spack @aweits? Not an issue of the package?

It would at least seem that the default value is internally on the list of allowed values (and it will pass validation) - unless we want that to change?

**Comment by aweits** [comment]
For example, I just ran into the example that was pointed out earlier with boost+context:
```
    variant('cxxstd',
            default='98',
            values=('98', '11', '14', '17', '2a'),
            multi=False,
            description='Use the specified C++ standard when building.')

    conflicts('cxxstd=98', when='+context')  # Context requires >=C++11.

```
The concretizer should normally prioritize the default value (which is why #20297 is only a partial fix), but in the case of boost+context it now isn't an option - all the other values are equally costly, so any of the remaining values are a "correct" decision. In my case the only reason I noticed is that I was building slightly different versions of boost over and over again while I was working on a new package.

**Comment by alalazo** [comment]
> all the other values are equally costly, so any of the remaining values are a "correct" decision. In my case the only reason I noticed is that I was building slightly different versions of boost over and over again while I was working on a new package.

That's what I meant, less clearly, by https://github.com/spack/spack/issues/20171#issuecomment-735763014 and https://github.com/spack/spack/issues/20171#issuecomment-735746815

**Comment by alalazo** [comment]
> "the default value is not among the allowed values."

What I mean is that we either need to change this:

https://github.com/spack/spack/blob/59628cd9e85f9ddffa8c2f93bd1b48eb8b782e73/lib/spack/spack/solver/asp.py#L902

to account for the default values or, better, change all the packages to have default values listed as possible values (and enforce the rule during validation). I think the second option is better because it's explicit and permits to deal with cases like:
```python
variant('foo', default='a,b', values=('c','d'), multi=True)
```
in a clear way. Like it stands currently it's unclear whether e.g. `a` and `b` can be used on their own or why they don't appear in the list of values.

**Comment by haampie** [comment]
I guess validating the `default` is part of the `values` makes a lot of sense.

And then to tackle @aweits's example, wouldn't it make sense to give the values in the list some decaying weight? It seems sensible to prefer the first value, if that's impossible, then the second, etc. Is this possible to have @alalazo?
