### ISSUE TITLE
installing software which does not use configure and make

### ISSUE THREAD

**Issue by mictadlo** [LLNL/spack#2017]
Hi,
How would it be possible to compile [MaSuRCA](ftp://ftp.genome.umd.edu/pub/MaSuRCA/MaSuRCA-3.2.1_09012016.tar.gz) with spack, because it does not uses `configure`,`make` and `make install` instead it uses `./install.sh`?

Thank you in advance.

Mic

**Comment by tgamblin** [comment]
Sure.  It's possible -- you can edit makefiles, patch things, or really anything from inside a spack package.  Have a look at `arpack` (type `spack edit arpack`) for a simple example or `cp2k` for a complicated one.

The only issue with MaSuRCA would be that it doesn't have a publicly downloadable link, so we can't download it automatically in Spack.  It looks like they require you to enter a valid email address before they will send you a download link.

**Comment by adamjstewart** [comment]
Another good example to look at would be PGI (`spack edit pgi`). It has a similar problem, where you need to download it manually. By using a url of:
```python
"file://%s/pgi-16.3.tar.gz" % os.getcwd()`
```
I was able to allow Spack to find the tarball either in a mirror or in the current directory. Similarly, PGI needs to be installed by running an `./install` script. Let me know if you need any help!

**Comment by tgamblin** [comment]
And feel free to ask questions here or on the mailing list!

**Comment by mictadlo** [comment]
The public download location ftp://ftp.genome.umd.edu/pub/MaSuRCA/ and thank you for the tips.

**Comment by tgamblin** [comment]
Thanks!  That should make it much easier to package.
