### ISSUE TITLE
Software request

### ISSUE THREAD

**Issue by mictadlo** [LLNL/spack#2018]
Hi, 
Seqping (https://sourceforge.net/projects/seqping/) has the following: 

* BLAST 2.2.25 (ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/)
* CD-HIT 4.5.4 (http://www.bioinformatics.org/downloads/index.php/cd-hit/)
* Exonerate 2.2 (http://www.ebi.ac.uk/~guy/exonerate/)
* GlimmerHMM 3.0 (ftp://ccb.jhu.edu/pub/software/glimmerhmm/)
* AUGUSTUS 2.6.1 (http://bioinf.uni-greifswald.de/augustus/binaries/)
* SNAP-2012-05-17 (http://korflab.ucdavis.edu/Software/)
* MAKER 2.28 (http://www.yandell-lab.org/software/maker.html)
* EMBOSS 6.4.0 (http://emboss.sourceforge.net/download/)
* HMMER 3 (http://hmmer.janelia.org/software)
* RepeatMasker-3-3-0 (http://www.repeatmasker.org/RMDownload.html)
* NCBI C++ Toolkit (ftp://ftp.ncbi.nih.gov/toolbox/ncbi_tools++/)

Would you be able to provide it for spack?

Thank you in advance.

Mic

**Comment by davydden** [comment]
Unless someone else need those packages and is willing to create `package.py` for them in Spack, the best way is to do it yourself. Please read [Packaging Guide](http://spack.readthedocs.io/en/latest/packaging_guide.html) and start from the simplest packages in your list, one by one.

**Comment by tgamblin** [comment]
Those look useful -- maybe @mamelara could comment on whether JGI already has packages for some of them.

@mictadlo: I'd be happy to merge a pull request if you want to package those and submit.

**Comment by mictadlo** [comment]
It will take me probably a while to understand spack.

**Comment by mamelara** [comment]
Hello @mictadlo 
I wrote some package files awhile back as part of learning Spack. I'll revisit them and update them since those packages are what we want for Joint Genome Institute
