### ISSUE TITLE
Installation issue: wrf

### ISSUE THREAD

**Issue by fluidnumericsJoe** [LLNL/spack#20202]
### Steps to reproduce the issue

```console
$ spack install wrf@4.2%gcc@9.3.0+pnetcdf build_type=dmpar compile_type=em_real nesting=basic arch=linux-ubuntu20.04-skylake
...
==> Error: TypeError: int() can't convert non-string with explicit base

/home/joe/apps/spack/var/spack/repos/builtin/packages/wrf/package.py:292, in run_compile_script:
        289        csh = Executable(csh_bin)
        290
        291        # num of compile jobs capped at 20 in wrf
  >>    292        num_jobs = str(min(int(make_jobs, 10)))
        293
        294        # Now run the compile script and track the output to check for
        295        # failure/success We need to do this because upstream use `make -i -k`
```
After correcting this python syntax issue (diff shown in Additional Information), the wrf package still fails to install
```console
$ spack install wrf@4.2%gcc@9.3.0+pnetcdf build_type=dmpar compile_type=em_real nesting=basic arch=linux-ubuntu20.04-skylake
==> Error: TypeError: argument of type 'NoneType' is not iterable

/home/joe/apps/spack/var/spack/repos/builtin/packages/wrf/package.py:305, in run_compile_script:
        302            self.spec.variants["compile_type"].value,
        303        )
        304
  >>    305        if "Executables successfully built" in result_buf:
        306            return True
        307
        308        return False

See build log for details:
  /tmp/joe/spack-stage/spack-stage-wrf-4.2-edueaikvls3ifjmws62swxjiquv7edv2/spack-build-out.txt
```
### Information on your system

```console
$ spack debug report
* **Spack:** 0.16.0-121-32e23f532
* **Python:** 3.8.5
* **Platform:** linux-ubuntu20.04-skylake
* **Concretizer:** original
```

### Additional information
The error is a python syntax error in the WRF package file. Locally patching this syntax error (diff below) gets passed this issue.
```
$ git diff
diff --git a/var/spack/repos/builtin/packages/wrf/package.py b/var/spack/repos/builtin/packages/wrf/package.py
index b0a9fd450..4b8794bb0 100644
--- a/var/spack/repos/builtin/packages/wrf/package.py
+++ b/var/spack/repos/builtin/packages/wrf/package.py
@@ -289,7 +289,7 @@ def run_compile_script(self):
         csh = Executable(csh_bin)
 
         # num of compile jobs capped at 20 in wrf
-        num_jobs = str(min(int(make_jobs, 10)))
+        num_jobs = str(min(int(make_jobs), 10))
 
         # Now run the compile script and track the output to check for
         # failure/success We need to do this because upstream use `make -i -k`
```

@MichaelLaufer  @ptooley

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by fluidnumericsJoe** [comment]
[spack-build-env.txt](https://github.com/spack/spack/files/5625066/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/5625067/spack-build-out.txt)

**Comment by adamjstewart** [comment]
Can you see if #20006 fixes your issues?

**Comment by fluidnumericsJoe** [comment]
Hey @adamjstewart,  #20006 (which I saw has been merged into develop) has resolved the issue on the linux-ubuntu20.04-skylake platform. However, I'm encountering issues on a centos7-broadwell setup that I'm verifying I can reproduce. If I can reproduce on centos7-broadwell, I'll open another ticket.

**Comment by MichaelLaufer** [comment]
@schoonovernumerics 
Regarding a potential issue you saw on your centos7-broadwell.
It appears that you are using MPI from the distro repository. Did you correctly add it as an spack external package?
Why not use spack built MPI?

Let me know if you have any further issues.

**Comment by fluidnumericsJoe** [comment]
Hey @MichaelLaufer , good find! I hadn't noticed that. The spack-build-out I shared was on the Ubuntu system, on which I did not add the distro provided MPI to packages.yaml. 

It's possible that the CentOS build is picking up mpi from an rpm installed openmpi-devel. On the CentOS system, I explicitly concretized openmpi@4.0.2, but I'll double check.
