### ISSUE TITLE
Open MPI:  enable/disable of built-in atomics should be based on version

### ISSUE THREAD

**Issue by hppritcha** [LLNL/spack#20215]
Note this is not really a bug but more of a suggested improvement to the Open MPI spack package.   There were issues in the 3.0 and 3.1 release streams where setting ```--disable-builtin-atomics``` was suggested for working around problems found in the Open MPI shared memory device.  This problem should be resolved in newer releases.  This should be reflected in the Open MPI spack package default for enabling/disabling builtin atomics.

**Comment by johebll** [comment]
Hello @hppritcha,
thank you for this hint.
I just stumbled upon it while trying to understand why Spack 0.21.1 seems to still disable built in atomics by default, at least in my attempt to install openmpi4.1.6%gcc13.2.0. 
Is the reason still that precautionary, conservative default, or is "~atomics" still relevant?
I would highly appreciate your advice,
best
