### ISSUE TITLE
version in packages.yaml is broken for numbers ending in 0

### ISSUE THREAD

**Issue by mwkrentel** [LLNL/spack#20257]
I'm seeing a strange problem with spack/python reading `packages.yaml`.

In packages.yaml, if I use a version with two numeric fields where the
second field ends with `0`, then spack fails to parse the version
correctly.  For example, `1.20` or `2.100` or `0.180`.

With a fresh spack clone fbb127c46a78 from Dec 4, I use this as
packages.yaml.

```
packages:
  elfutils:
    version: [ 0.180 ]
```

Then `spack spec` gets the wrong version.

```
$ spack spec elfutils

Concretized
--------------------------------
elfutils@0.182%gcc@8.3.1~bzip2~debuginfod+nls~xz arch=linux-rhel8-x86_64
    ...
```

This works for 0.177 or 0.173, but not 0.170 or 0.180.
A similar problem happens with amrex version 20.10.

The problem only happens in packages.yaml.  If I use elfutils @0.180
on the command line, then it works.

I would call this a "concretization" problem, but I think the real
problem is parsing the file.  I suspect `0.180` is not being parsed as
a valid version, and certainly not a 2-element list of 0 and 180.
Without a valid version, the concretizer picks the default (latest)
version.

Unfortunately, `spack -d spec` doesn't show any insight.

Is it possible that spack or python is reading 0.180 as a floating
point number, where 0.180 an 0.18 are the same value??

This happens on RH 7.x and 8.x.  On RH 8.2, /usr/bin/python is 2.7.17
and python3 is 3.6.8.

* **Spack:** 0.16.0-167-fbb127c46
* **Python:** 3.6.8
* **Platform:** linux-rhel8-zen2
* **Concretizer:** original

**Comment by adamjstewart** [comment]
I believe this is an issue with the YAML specification, not something we can fix. YAML will likely treat 0.180 as a floating point number and store it as 0.18. I imagine numbers like 0.1.80 work fine since there are two periods and it can't be a floating point number. The workaround is to explicitly store it as a string: `'0.180'`.

**Comment by mwkrentel** [comment]
I've never been clear on what things in .yaml files need to be quoted.
I guess officially everything, at least all numbers, should be quoted.
But for the 95% of cases where the number->string function produces
the same string as the input, then you get away without quotes.
