### ISSUE TITLE
Can't Ctrl+C out of spack test

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#2029]
When running `spack test`, hitting <kbd>Ctrl</kbd>+<kbd>C</kbd> will kill that particular test, but Spack will pick right back up with the next test. The behavior I would expect is that `spack test` should quit all tests.

**Comment by alalazo** [comment]
Question : does `nose.run` do something fancy that causes this behavior ?

**Comment by tgamblin** [comment]
It looks like it [can](http://nose.readthedocs.io/en/latest/plugins/multiprocess.html)... not sure if it does by default, though.

**Comment by scheibelp** [comment]
The following in nose/core.py appears to control this behavior:

```
        try:
            test(result)
        except KeyboardInterrupt:
            pass
```

I think it does this so it can still print results for whatever did run.

**Comment by adamjstewart** [comment]
Yeah, I assumed it had something to do with reporting back all test results in Travis regardless of whether or not the first test crashed. But if we're more specific, it shouldn't be hard to continue for crashes and exit for <kbd>Ctrl</kbd>+<kbd>C</kbd>.
