### ISSUE TITLE
Installation issue: fio

### ISSUE THREAD

**Issue by yellowhat** [LLNL/spack#20303]
### Steps to reproduce the issue
```console
# Compile
$ git clone --depth 1 https://github.com/spack/spack.git
$ source spack/share/spack/setup-env.sh
$ spack compiler find
$ spack -d install fio arch=x86_64

# Run
$ spack load fio
$ spack arch
$ fio --version
```

Hi,
For some reason even if the `arch=x86_64` flag is passed the compiling flag `-march=native` is used anyway.
So:
- compiling `fio` on a Intel machine (Intel(R) Xeon(R) Platinum 8272CL CPU @ 2.60GHz), runs on Intel but on AMD (AMD EPYC 7551 32-Core Processor) returns: `Illegal instruction (core dumped)`
- compiling `fio` on an AMD machine, runs on Intel and AMD

I was under the impression that spack would manage the compiling flag based on the `arch=` flag or by detecting the architecture.

Is there a problem with the `fio` package or something internal to spack?

[spack-amd-cc-fio-hebsxwu.out.log](https://github.com/spack/spack/files/5666166/spack-amd-cc-fio-hebsxwu.out.log)
[spack-intel-cc-fio-hebsxwu.in.log](https://github.com/spack/spack/files/5666167/spack-intel-cc-fio-hebsxwu.in.log)
[spack-intel-cc-fio-hebsxwu.out.log](https://github.com/spack/spack/files/5666168/spack-intel-cc-fio-hebsxwu.out.log)
[spack-amd-cc-fio-hebsxwu.in.log](https://github.com/spack/spack/files/5666169/spack-amd-cc-fio-hebsxwu.in.log)

**Comment by yellowhat** [comment]
[https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/fio/package.py](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/fio/package.py) does not pass any particular flag. Am I correct?

**Comment by akail** [comment]
We're experiencing this same issue with one of our systems as well and I want to share some notes.

Compiled with arch=x86_64 on a skylake_avx512 architecture.

Works on:
- skylake_avx512

Doesn't
- ivybridge

If we instead build on the ivybridge it works across all our systems, which makes sense because the skylake is newer than the ivybridge.
