### ISSUE TITLE
100.0% ==> Error: Attempt to check URLFetchStrategy with no digest. ==> Error: Installation process had nonzero exit code : 256

### ISSUE THREAD

**Issue by BarrySmith** [LLNL/spack#2034]
It would be good if there error message provided more information to help debug the problem.

Doe spack generate a "global" error file that contains information about the process it is performing to help debug when things go wrong?

==> Fetching from file:///scratch/bsmith/spack/var/spack/cache/xsdk/xsdk-.1.tar.gz failed.
==> Trying to fetch from https://bitbucket.org/saws/saws/get/master.tar.gz
######################################################################## 100.0%
==> Error: Attempt to check URLFetchStrategy with no digest.
==> Error: Installation process had nonzero exit code : 256

**Comment by tgamblin** [comment]
No global error file, but you can use `spack --debug` to get more output and to tell Spack not to squash exceptions.  It looks like there is no checksum for the fake file here.  You could run `spack md5` on it to get one.

**Comment by BarrySmith** [comment]
Adding the checksum resolved the problem. Best if the error message told one exactly the problem so I need not both you with my silly mistakes. 

Thanks.
