### ISSUE TITLE
Package build system changed

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#20364]
The `nsimd` package just released version 2.0. It completely changed the build system from `cmake` to `nsconfig`. How should I handle that in Spack? Is it possible to have two separate `Nsimd` functions, one deriving from `CMakePackage`, the other not?

**Comment by adamjstewart** [comment]
There is currently no universally accepted way to handle this. Some packages have split into `foo` and `foo-legacy`. There has been some talk of making a separate `legacy` repo for these older versions. The most common solution is to subclass the `Package` base class and provide separate phases for each version using `@when`. See https://github.com/spack/spack/pull/12941#issuecomment-538105434 for a list of packages that have changed build systems. These should serve as a good reference.

**Comment by adamjstewart** [comment]
I finally got around to documenting this! Can you see if #25174 does a good job of explaining how to support multiple build systems? If anything is unclear, let me know and I'll try to improve the docs.
