### ISSUE TITLE
spack test run --verbose

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#20375]
I would like to see a `--verbose` flag added to `spack test run`.

### Rationale

Currently, the output of `spack test run` looks like:
```
$ spack test run py-setuptools
==> Spack test a3k3zuqk77j6a43f3uov7cmg2f37ys4m
==> Testing package py-setuptools-44.1.0-3tupt4p
==> Testing package py-setuptools-50.1.0-y52kezl
==> Testing package py-setuptools-50.1.0-gfu263a
==> Testing package py-setuptools-50.1.0-6aovrq4
==> Testing package py-setuptools-50.1.0-75gs77c
==> Testing package py-setuptools-50.3.2-nvkcvji
==> Testing package py-setuptools-50.3.2-pidod5m
```
I think by default, we should add a summary at the end, like pytest does. Something like `7 out of 7 tests PASSED`. I would also like a `--verbose` flag that shows more details of the tests for each package.

**Comment by tldahlgren** [comment]
What did you have in mind for `--verbose`?

You can see details of the tests for each package by running 

```
$ spack test results -l -- py-setuptools
```

**Comment by adamjstewart** [comment]
When I run `spack install py-setuptools`, I don't see much in terms of output other than the fact that the package was installed. If I want to see the build log, I can check the `spack-build-out.txt` file later. Alternatively, I can run `spack install --verbose py-setuptools` to see the build output during install.

When I run `spack test run py-setuptools`, I don't see much in terms of output other than the fact that the package is being tested. I think it makes sense to add an analogous `spack test run --verbose py-setuptools` that shows me the output of the testing process, basically the same thing you get from `spack test results` but without the extra step.

**Comment by tldahlgren** [comment]
> When I run `spack install py-setuptools`, I don't see much in terms of output other than the fact that the package was installed. If I want to see the build log, I can check the `spack-build-out.txt` file later. Alternatively, I can run `spack install --verbose py-setuptools` to see the build output during install.
> 
> When I run `spack test run py-setuptools`, I don't see much in terms of output other than the fact that the package is being tested. I think it makes sense to add an analogous `spack test run --verbose py-setuptools` that shows me the output of the testing process, basically the same thing you get from `spack test results` but without the extra step.

Any reason for not just using Spack's `--verbose` option instead of adding one to the subcommand?

**Comment by adamjstewart** [comment]
I guess for consistency with other Spack subcommands. We could remove `spack install --verbose` or `spack unit-test -s` if you think it's preferable to use `spack --verbose *`.

**Comment by tldahlgren** [comment]
> I guess for consistency with other Spack subcommands. We could remove `spack install --verbose` or `spack unit-test -s` if you think it's preferable to use `spack --verbose *`.

Hmm.  In this PR? 

I can add it to the fix PR if you want.  Right now it is using `spack --verbose`.  Up to you.  Just let me know.

**Comment by adamjstewart** [comment]
Nah, let's definitely consider doing that in a separate PR if that's what we decide
