### ISSUE TITLE
Hash changes make binary mirrors unusable

### ISSUE THREAD

**Issue by nithintsk** [LLNL/spack#20429]
### Description

We currently have binary mirrors for the MVAPICH2-X and MVAPICH2-GDR packages that are available through spack. The binaries on these mirrors are rendered unusable whenever the build dependencies of MVAPICH2-X or MVPICH2-GDR (bison and libpciaccess) are updated by their maintainers. 

This causes us to regenerate all our binaries with the latest version of spack and all the dependencies.

### Ask

Is there a way around this? Given the number of variants we have, we generate many combinations of binaries. It is very cumbersome to figure out when our binaries are no longer accessible by users and to regenerate them.

### Steps to reproduce the issue

```console
$ spack install mvapich2-gdr (does not work anymore. binaries not found though it exists.)
...
```

### Additional information

- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by tgamblin** [comment]
This will be addressed by #19085 (which will make the buildcache hashes able to be referenced by users on the command line) as well as a forthcoming concretizer PR, to prefer already-installed packages and binary packages from mirrors.  I think the combination of these two will make mirrors *much* more usable in 0.17.0 (something we've been aiming at for a while).
