### ISSUE TITLE
Problems during install deal.II in spack

### ISSUE THREAD

**Issue by SalvoBella** [LLNL/spack#20445]
Hi everyone, first I want to apologize because I am new into ubuntu, so I could be wrong anywhere.

In order to install a library, I had to clone spack, and then to install deal.II and vtk. 
I followed this code: 

```
.bashrc file: "export SPACK_ROOT=/path/to/spack/
export PATH=${SPACK_ROOT}/bin:${PATH}"
sudo apt install python git curl make g++ gfortran
mkdir -p ${SPACK_ROOT}
cd ${SPACK_ROOT}
git clone https://github.com/spack/spack.git .
spack install environment-modules
.bashrc file: "source $(spack location -i environment-modules)/init/bash
source ${SPACK_ROOT}/share/spack/setup-env.sh"
```

Up to this point, everything seems fine, and I got no errors. 
Then I install 

`spack install dealii@9.2.0 ^suite-sparse@5.2.0`

And I get errors as you see in the screen. 
Do you have any ideas about what could I do? Thanks everyone! 
<img width="595" alt="errore dealii" src="https://user-images.githubusercontent.com/56541934/102512972-ed8c6e00-408a-11eb-8e5c-aff82b0d2a04.PNG">

**Comment by adamjstewart** [comment]
@davydden  @jppelteret  @luca-heltai

**Comment by luca-heltai** [comment]
As far as dealii is concerned, we don't use netcdf support from trilinos. Can you try and see if 

~~~
spack install dealii@9.2.0 ^trilinos~netcdf
~~~
succeeds?

**Comment by SalvoBella** [comment]
> As far as dealii is concerned, we don't use netcdf support from trilinos. Can you try and see if
> 
> ```
> spack install dealii@9.2.0 ^trilinos~netcdf
> ```
> 
> succeeds?

Thanks a lot for the answer!
Unfortunately it doesn't work, this is what I get: 

<img width="590" alt="mandare" src="https://user-images.githubusercontent.com/56541934/103180173-901acd00-4893-11eb-9d3f-a517a7382df4.PNG">

**Comment by pcafrica** [comment]
Hi @SalvoBella!

The following should work (just tested succesfully):
```
spack install dealii@9.2.0 ^boost@1.72.0 ^mumps@5.2.0 ^trilinos~exodus~netcdf
```

**Comment by luca-heltai** [comment]
Thanks @SalvoBella and @elauksap. I've opened #20606 to fix this.

**Comment by SalvoBella** [comment]
@elauksap @luca-heltai 

Thank you very much for your help!
If it could be useful maybe to others, I just want to say that at the end I had other errors with the command `spack install vtk@9.0.0 ^mesa~llvm`, so I managed to install the library through the mk packages. 
If you need any details about the errors, I saved the screens and I wish to be helpful! Thanks again!
