### ISSUE TITLE
openblas installation is very slow: spack 0.16.0

### ISSUE THREAD

**Issue by tachidok** [LLNL/spack#20458]
Openblas is taking too long to finish the installation, around 11 minutes, is that normal?

### Minimal example
```
$ time spack install --fail-fast openblas@0.3.9
==> Installing openblas-0.3.9-rv4ljs7usr6qcqmzy2ywbjdhkevqikgo
==> No binary for openblas-0.3.9-rv4ljs7usr6qcqmzy2ywbjdhkevqikgo found: installing from source
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/17/17d4677264dfbc4433e97076220adc79b050e4f8a083ea3f853a53af253bc380.tar.gz
################################################################################################################################################################################### 100.0%
==> openblas: Executing phase: 'edit'
==> openblas: Executing phase: 'build'
==> openblas: Executing phase: 'install'
[+] /home/tachidok/local/working/research/tmp/spack/opt/spack/linux-ubuntu18.04-skylake/gcc-7.5.0/openblas-0.3.9-rv4ljs7usr6qcqmzy2ywbjdhkevqikgo

real	11m3.647s
user	42m48.538s
sys	6m12.603s
```

I want to add that I came to this minimal example after trying to create a Dockerfile with more packages and noticed that openblas was taking too long to install. I initially tought it was a docker related problem but then I individually installed the packages using the command

```
 spack install --fail-fast <package_name>
```

which is the one produced by the `spack containerize > Dockerfile` command.

Please note that this is a fresh install, nothing else was installed with spack. This is the output after installing openblas@0.3.9

```
$ spack find
==> 1 installed package
-- linux-ubuntu18.04-skylake / gcc@7.5.0 ------------------------
openblas@0.3.9
```

Some other packages I tried to install and take too long are the following:

```
  ncurses
  Fetch: 3.17s.  Build: 3m 13.20s.  Total: 3m 16.36s.
  libxml2
  Fetch: 1m 14.00s.  Build: 1m 4.88s.  Total: 2m 18.88s.
  perl
  Fetch: 29.17s.  Build: 4m 22.73s.  Total: 4m 51.91s.
  openssl
  Fetch: 4.42s.  Build: 6m 18.33s.  Total: 6m 22.75s.
  cmake
  Fetch: 15.58s.  Build: 13m 5.03s.  Total: 13m 20.60s.
  openmpi
  Fetch: 3.03s.  Build: 21m 54.80s.  Total: 21m 57.83s.
```

### Spack version
```
$ spack --version
0.16.0-199-5b1739da7

$ spack compilers
==> Available compilers
-- clang ubuntu18.04-x86_64 -------------------------------------
clang@6.0.0

-- gcc ubuntu18.04-x86_64 ---------------------------------------
gcc@7.5.0
```

### System information
OS: Ubuntu 18.04
Memory: 15.5 GiB
Processor: Intel® Core™ i7-8550U CPU @ 1.80GHz × 8 
OS type: 64-bit

### Spack debug report
* **Spack:** 0.16.0-199-5b1739da7
* **Python:** 3.7.3
* **Platform:** linux-ubuntu18.04-skylake
* **Concretizer:** original

Note sure what else to add as system information.

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
It's normal, it compiles for multiple architectures, and not only compiles blas, but also lapack

**Comment by tachidok** [comment]
Ok, if that is the case then it seems there is nothing else to do but wait.
