### ISSUE TITLE
Installation issue: automake@1.16.3

### ISSUE THREAD

**Issue by EthanS94** [LLNL/spack#20454]
### Steps to reproduce the issue

```console
$ spack install automake@1.16.3%intel@19.0.4.243 arch=linux-rhel7-broadwell
...
2 errors found in build log:
     100      GEN      bin/aclocal-1.16
     101      GEN      doc/aclocal-1.16.1
     102      GEN      bin/automake-1.16
     103      GEN      doc/automake-1.16.1
     104    help2man: can't get `--help' info from aclocal-1.16
     105    Try `--no-discard-stderr' if option outputs to stderr
  >> 106    make: *** [doc/aclocal-1.16.1] Error 126
     107    make: *** Waiting for unfinished jobs....
     108    help2man: can't get `--help' info from automake-1.16
     109    Try `--no-discard-stderr' if option outputs to stderr
  >> 110    make: *** [doc/automake-1.16.1] Error 126
```

### Information on your system

* **Spack:** 0.16.0-281-a879c875d
* **Python:** 3.6.3
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** original

### Additional information

This was found during a build of paraview%intel, but I will test with gcc too. automake@1.16.2 builds fine. I can provide more information if needed. Just wanted to get this up before I forget about it. 

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers 
Doesn't look like there are maintainers listed.
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by EthanS94** [comment]
I get the same error with `gcc@7.4.0`

**Comment by chuckatkins** [comment]
I just started hitting this today as well

**Comment by mdorier** [comment]
Same here.

**Comment by ipdemes** [comment]
I have got the same error

**Comment by ikitayama** [comment]
I am currently seeing it and this prevents Spack from building the latest `gcc`.

**Comment by ikitayama** [comment]
According to the Spack git log, the cause must be purely in the change in the automake between .2 and .3.

**Comment by ikitayama** [comment]
After the holidays, could this be checked promptly, as this seems to be affecting lots of packages?

**Comment by ipdemes** [comment]
@ikitayama : it is affecting at least 2 packages for our build: parmetis, legion

**Comment by mdorier** [comment]
@ipdemes I think it potentially affects all automake-based packages. I found a similar bug reported 2 years ago on the homebrew repo: https://github.com/Homebrew/linuxbrew-core/issues/6275
And 4 years ago here: https://stackoverflow.com/questions/39141038/unable-to-build-gnu-automake
seems to be related to Perl?

**Comment by ikitayama** [comment]
The diff is large so it’s not immediately clear that is related to Perl.

**Comment by lrtfm** [comment]
This is relative to the changes of the Shebang line in the new Automake. See pull request #20579.

**Comment by ikitayama** [comment]
@alalazo I was able to build the latest release of `automake` with Fujitsu compiler without an issue. Thanks!
