### ISSUE TITLE
Quick request for guidance re: X and variants

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#2045]
Now that we have the X11 stuff (yay @adamjstewart !) I'm working from a base image that does not include any of the X libraries.

I'm discovering things that need X (*tk*, *R*).  The simple fix is just to toss in `depends_on('libx11')` and get on with it.

Before I submit the couple of trivial PR's, does the Spack community want to "force" people to use Spack's X stuff?  There aren't that many things in the tree that depend on *libx11* that aren't also part of the X world, it makes sense that they all depend on it unconditionally.  The only non-X-thingy example I can find is sublime text, which also depends on it unconditionally.  Is that the way we want to go?  What about people who want/need to use their system's libraries?

Can someone remind me (I'm rusty...) what the spec for R would look like to ensure that its dependencies used a particular variant.  Do I need to know that R *depends_on* Tk which (soon) *depends_on* libx11?

**Comment by adamjstewart** [comment]
> does the Spack community want to "force" people to use Spack's X stuff?

That's a really good question. There are two ways to look at the problem. Let's say 99% of users already have a particular system library installed. Should we add that dependency to the Spack package? What about the 1% that don't? One of the reasons I originally started packaging X11/Xorg is that I was missing some of these libraries. For example, `ncview` depends on `libxaw`, but I didn't have that installed.

If we don't add the dependency, we force users to either hack the package themselves every time they need to build something, or we force them to use the system package manager to install that library. On the other hand, if we do add the dependency, it means that builds will take longer. Of course, anyone who wants to use the system libraries can always add external packages to `packages.yaml`.

In my opinion, I support adding all dependencies of a package. Spack should just work, it shouldn't require users to hack it or to use the system package manager for stuff. But I can see why it would be annoying to build things that already exist on the system. @tgamblin was talking about adding a script that automatically added all system libraries to your `packages.yaml`. Once that is done, I don't think it will matter as much, and we will definitely want to add the dependency to the package.

> The only non-X-thingy example I can find is sublime text, which also depends on it unconditionally.

I wrote that package, so you can ignore it as an example. Anyway, it's just a pre-build executable, so there wasn't even a way to get it to link to the Spack-installed libx11 automatically.

**Comment by hartzell** [comment]
FWIW (I asked the question, so how is that I have an opinion? :)) I'd be content to add the dependencies.

**Comment by adamjstewart** [comment]
@citibeth will want to comment on this one before you do. I would like to here other people's opinions too. But I agree with you that the only way to ensure that a dependency exists is to install it with Spack. It's just a matter of whether or not others mind waiting longer for their installations to finish.

**Comment by citibeth** [comment]
We should add the dependency to the package.  Spack already has a way to use a system-version of a dependency if you think your system has it; see:
    https://spack.readthedocs.io/en/latest/getting_started.html#openssl

The problem here is that as people add more and more depencies (the correct thing to do), users who don't want to install the world will end up having to put more and more `@system` things in their `packages.yaml`.  We need a better way to address that problem.

The "obvious" solution would be to create a default `packages.yaml` that includes packages (like X) that are both expensive to build and found on most systems.  The default would be to use the system version of these dependencies, the Spack version would only be used if the user explicitly turns them off.  I do think we should think of some sensible defaults here.  We need to think a bit more here on mechanics of how this would work as well...

The above is for NECESSARY dependencies.  If a dependency is only needed for an optional feature of a package, then there should be a variant controlling that feature; and the dependency should only activate if the variant is turned on.

**Comment by hartzell** [comment]
> The above is for NECESSARY dependencies. If a dependency is only needed for an optional feature of a package, then there should be a variant controlling that feature; and the dependency should only activate if the variant is turned on.

On that note, I'll touch up the emacs package to depend on X stuff `when='+X'`, etc...

**Comment by tgamblin** [comment]
This all sounds good to me!

**Comment by citibeth** [comment]
We have used +gui in other packages

**Comment by adamjstewart** [comment]
Speaking of the emacs variants, what is the difference between:
```python
variant('X',       default=True,  description="Enable a X toolkit (GTK+)")         
variant('gtkplus', default=False, description="Enable a GTK+ as X toolkit (ignored if ~X)")
```
Maybe these 2 can be combined.

**Comment by hartzell** [comment]
@citibeth 
> We have used +gui in other packages

The emacs packages already supports an X variant that controls whether it builds the X or non-X version.  I was just going to tag the Spack X bits onto the existing list of dependencies when building the gui version.  I don't see any reason to change the existing variant name.  Do you?

**Comment by hartzell** [comment]
@adamjstewart 
> Maybe these 2 can be combined.

From the emacs INSTALL:

> To get more attractive menus, you can specify an X toolkit when you
configure Emacs; use the option '--with-x-toolkit=TOOLKIT', where
TOOLKIT is 'gtk' (the default), 'athena', or 'motif' ('yes' and
'lucid' are synonyms for 'athena').  Compiling with Motif causes a
standard File Selection Dialog to pop up when you invoke file commands
with the mouse.  You can get fancy 3D-style scroll bars, even without
Gtk or Motif, if you have the Xaw3d library installed (see
"Image support libraries" above for Xaw3d availability).

So, gtk is the default toolkit.  Looking (more carefully, I generally just use ~X since I'm accessing the machines via ssh) at this bit of the package:

```python
            if '+gtkplus' in spec:
                toolkit = 'gtk{0}'.format(spec['gtkplus'].version.up_to(1))
            else:
                toolkit = 'no'
            args = [
                '--with-x',
                '--with-x-toolkit={0}'.format(toolkit)
            ]
```
it seems like perhaps the author was heading towards supporting other toolkits?

I'm inclined to only make the small change of use our X (small change, driven by a reason).

I'd be ok with deleting the gtkplus bits since they seem redundant.  

@nrichart, it looks like you added the gtkplus variant.  Since it seems to be the default (perhaps it didn't use to be), do you have a problem with me removing it?

And now that Pandora's box is open, I'll add support for the latest in the 25 release series....

**Comment by citibeth** [comment]
Sounds good to me.
