### ISSUE TITLE
Error: Class constructor failed for package 'cdd'.

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#2047]
I'm exploring `spack mirror create`.  I just naively tried to run it to see what it would do with the things I have installed, which does **not** include *cdd*, and ran into this:

```
[hartzelg@rss-spack spack]$ spack -v mirror create
==> Error: Class constructor failed for package 'cdd'.

Caused by:
TypeError: 'str' object is not callable
  File "/rss/spack/lib/spack/spack/repository.py", line 584, in get
    self._instances[key] = package_class(copy)
  File "/rss/spack/lib/spack/spack/package.py", line 398, in __init__
    f = fs.for_package_version(self, self.version)
  File "/rss/spack/lib/spack/spack/fetch_strategy.py", line 852, in for_package_version
    attrs['url'] = pkg.url_for_version(version)
  File "/rss/spack/var/spack/repos/builtin/packages/cdd/package.py", line 40, in url_for_version
    str(version.dotted()).replace('.', ''))

[hartzelg@rss-spack spack]$ spack find
```

Before I dig into line 40 of `.../cdd/package.py`, does this ring any bells for anyone?

**Comment by tgamblin** [comment]
`spack mirror create` with no args actually mirrors *everything*, not what is currently installed, so be careful.  That's probably why you're getting this error in `cdd`.

Currently installed stuff seems like a better default, to be honest.  That would be an easy fix in `cmd/mirror.py`

**Comment by hartzell** [comment]
> That's probably why you're getting this error in cdd

Well, that explains why I'm seeing a problem with *cdd* even though I don't have it installed.

It does *not* explain why cdd is exploding (though I guess I don't care...), does it?

**Comment by tgamblin** [comment]
I believe `dotted` is a property, not a function call, so removing the `()` should fix this.
