### ISSUE TITLE
Spack seems to ignore install_tree in ~/.spack/config.yaml in v0.16.0

### ISSUE THREAD

**Issue by weijianwen** [LLNL/spack#20489]
Spack project is installed on a READ-only directory (`/lustre/opt/spack/`) on our cluster. After upgrading it to v0.16.0, Spack seems to ignore install_tree setting in ~/.spack/config.yaml, insisting writing data to `/lustre/opt/spack/opt`.

### Steps to reproduce the issue

```console
$ which spack
/lustre/opt/spack/bin/spack
$ grep install ~/.spack/config.yaml
install_tree: /lustre/opt/cascadelake
$ spack install nvhpc+mpi %gcc@4.8.5 target=x86_64
...
==> Warning: detected deprecated properties in /lustre/home/rpm/.spack/packages.yaml
Activate the debug flag to have more information on the deprecated parts or run:

        $ spack config update packages

to update the file to the new format

==> Installing nvhpc-20.9-j3b7zgc7gcwlr3icso4izmgfqssx6g5n
==> Error: Failed to install nvhpc due to PermissionError: [Errno 13] Permission denied: '/lustre/opt/spack/opt'
==> Error: [Errno 13] Permission denied: '/lustre/opt/spack/opt'
```

### Information on your system

```console
$ cat ~/.spack/config.yaml
config:
  build_stage:
    - $tempdir/$user
  checksum: true
  db_lock_timeout: 180
  dirty: false
  install_tree: /lustre/opt/cascadelake
  misc_cache: /lustre/home/rpm/.spack/misccache
  module_roots:
    tcl: /lustre/share/spack/modules/cascadelake
  source_cache: /lustre/home/rpm/.spack/sourcecache
```

```console
$ spack debug report
* **Spack:** 0.16.0
* **Python:** 3.6.8
* **Platform:** linux-centos7-skylake_avx512
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by weijianwen** [comment]
I found Spack create the following dir structure in `/lustre/opt/spack/opt` after permission enabled.

```console
# tree /lustre/opt/spack/opt
/lustre/opt/spack/opt
└── spack
    └── indices

2 directories, 0 files
```

Seems like indices. Grepping Spack code indicates that I may need to customize `_cache_root` to avoid writing indices into the default directory colocated with Spack binary.

```console
# ack index_cache_root                               
lib/spack/spack/binary_distribution.py                 
71:        self._index_cache_root = os.path.join(self._cache_root, 'indices')                                                                   
99:                self._index_cache_root)                              
265:        on disk under ``_index_cache_root``). """                   
312:                    'cache_key': os.path.join(self._index_cache_root,
```

Any suggestion on setting `_cache_root`  in ~/.spack/config.yaml ? Thank you!

**Comment by EthanS94** [comment]
@weijianwen I don't remember why, but I had to add an extra line with `root:` in my config.yaml a while back. Does this work for you?
```yaml
  install_tree:
    root: /lustre/opt/cascadelake
```

**Comment by weijianwen** [comment]
@EthanS94 I didn't change config.yaml. After adding a writable /lustre/opt/spack/opt directory, it works. Still, it is annoying that a writable dir required under the default location.
