### ISSUE TITLE
spack should use python2 if python3 version is too old

### ISSUE THREAD

**Issue by zorun** [LLNL/spack#20495]
I try to run spack on a Solaris machine that has both python2 and python3, but the python3 version is quite old:

```console
gcc-solaris11:~$ python --version
Python 2.7.14
gcc-solaris11:~$ python3 --version
Python 3.3.6
```

When setting up spack, it tries to use the python3 version and fails:

```console
gcc-solaris11:~$ . spack/share/spack/setup-env.sh
Traceback (most recent call last):
  File "/export/home/foo/spack/bin/spack", line 62, in <module>
    import spack.main  # noqa
  File "/export/home/foo/spack/lib/spack/spack/main.py", line 25, in <module>
    import llnl.util.filesystem as fs
  File "/export/home/foo/spack/lib/spack/llnl/util/filesystem.py", line 23, in <module>
    from llnl.util.lang import dedupe, memoized
  File "/export/home/foo/spack/lib/spack/llnl/util/lang.py", line 35, in <module>
    fork_context = multiprocessing.get_context('fork')
```

According to the Getting Started doc, Python 3.3 is too old, so this is expected. From [getting_started](https://spack.readthedocs.io/en/latest/getting_started.html):  `Python 2 (2.6 or 2.7) or 3 (3.5 - 3.9) to run Spack`.

Forcing python2 works:

```console
gcc-solaris11:~$ sed -i -e "s/for cmd in python3 python python2/for cmd in python2/" bin/spack
gcc-solaris11:~$ . share/spack/setup-env.sh
gcc-solaris11:~$ spack debug report
* **Spack:** 0.16.0-299-e73a65d
* **Python:** 2.7.14
* **Platform:** test-redhat6-x86_64
* **Concretizer:** original
```

### Expected behaviour

Spack should detect when the python3 version is too old, and should fall back to python2 in that case. 

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- I have run the failing commands in debug mode and reported the output -> not applicable

**Comment by adamjstewart** [comment]
I'm not sure if there is an easy way to enforce this. We could search for `python3.9 python3.8 python3.7 python3.6 python3.5 python2.7 python2.6 python3 python2 python` but that seems excessive.

What does `python` symlink to on your system? We could put `python` before `python3`, but that will likely cause problems since `python` usually means `python2` and we're trying to phase out Python 2 support in the future.

**Comment by zorun** [comment]
Yes, python points to python2 on this system.

What about checking the python version with something like this (+ check for python2, you get the idea):
```
pythonX -c 'import sys; exit(sys.version_info.major == 3 and sys.version_info.minor >= 5)'
```

**Comment by alalazo** [comment]
Spack now runs only on Python 3.6 or greater
