### ISSUE TITLE
spack debug reports incorrect version

### ISSUE THREAD

**Issue by bhatiaharsh** [LLNL/spack#20514]
I updated my fork to `v0.16.0`, but `spack debug report` and `spack --version` report `0.11.2`.

### Steps to reproduce the issue

```console
$ spack --version
0.11.2-9807-5771441ec
$ spack debug report
* **Spack:** 0.11.2-9807-5771441ec
* **Python:** 3.7.2
* **Platform:** linux-rhel7-power9le
```

Here is the `git log` (I have 2x commits on top of the released version)
```
$ git lg
5771441ec (Tue Dec 22 09:05:48 2020 -0800) | small fix in tensorflow package (HEAD -> fix/bazel+tf, origin/fix/bazel+tf) [Harsh Bhatia]
0a1499ed3 (Wed Dec 16 01:24:59 2020 -0800) | fix bazel on power9 [Harsh Bhatia]
77d9acb07 (Wed Nov 18 01:30:27 2020 -0800) | update CHANGELOG.md for v0.16.0 [Todd Gamblin]
82383093e (Wed Nov 18 01:31:45 2020 -0800) | bump version number to 0.16.0 [Todd Gamblin]
532fc40e9 (Wed Nov 18 13:21:55 2020 +0100) | clingo: add `master` branch version (#19958) [Massimiliano Culpo]
20367e472 (Wed Nov 18 12:20:56 2020 +0100) | cmd: add `spack mark` command (#16662) [Michael Kuhn]
77b2e578e (Wed Nov 18 02:39:02 2020 -0800) | spack test (#15702) [Greg Becker]
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
You need to run `git fetch upstream --tags` to update the version reporting. Not sure if there is a better way to get this information.

**Comment by bhatiaharsh** [comment]
thanks @adamjstewart  and @becker33 . This is fixed. Closing this issue now.
