### ISSUE TITLE
spack install command incorrectly returning 0 when failing

### ISSUE THREAD

**Issue by mdorier** [LLNL/spack#20510]
I have a CI pipeline that builds a few packages daily to make sure that they keep building correctly. The CI script includes the following in a function:

```
spack install $PKGNAME
RET=$?
```

The script then reports the value of RET in a log file.

For the past week or so, I've been hit by [this issue](https://github.com/spack/spack/issues/20454), effectively making all my packages fail to build because automake-1.16.3 could not be built. The odd thing, however, is that Spack doesn't return an error code when failing to build a package.

Here is what spack displays (the package I'm trying to build is called mochi-margo):

```
==> Installing automake-1.16.3-2p5gwby4xivgjq2jwv6cnvjs5ou7k2r4
==> No binary for automake-1.16.3-2p5gwby4xivgjq2jwv6cnvjs5ou7k2r4 found: installing from source
==> Using cached archive: /sandbox/jenkins-ci/workspace/Mochi/mochi-all/spack/var/spack/cache/_source-cache/archive/ce/ce010788b51f64511a1e9bb2a1ec626037c6d0e7ede32c1c103611b9d3cba65f.tar.gz
==> automake: Executing phase: 'autoreconf'
==> automake: Executing phase: 'configure'

==> automake: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

2 errors found in build log:
     99       GEN      bin/aclocal-1.16
     100      GEN      doc/aclocal-1.16.1
     101      GEN      bin/automake-1.16
     102      GEN      doc/automake-1.16.1
     103    help2man: can't get `--help' info from aclocal-1.16
     104    Try `--no-discard-stderr' if option outputs to stderr
  >> 105    make: *** [doc/aclocal-1.16.1] Error 126
     106    make: *** Waiting for unfinished jobs....
     107    help2man: can't get `--help' info from automake-1.16
     108    Try `--no-discard-stderr' if option outputs to stderr
  >> 109    make: *** [doc/automake-1.16.1] Error 126

See build log for details:
  /sandbox/jenkins-ci/workspace/Mochi/mochi-all/.spack/stage/autotest/spack-stage-automake-1.16.3-2p5gwby4xivgjq2jwv6cnvjs5ou7k2r4/spack-build-out.txt

==> Warning: Skipping build of mochi-margo-0.9-u7muohgv2xx7ibr2udwusxgzyzwhwtj3 since automake-1.16.3-2p5gwby4xivgjq2jwv6cnvjs5ou7k2r4 failed
```

As you can see in the last line, spack skips the installation of the package I asked it to install, and returns 0, making my CI pipeline think that the package was built correctly.

**Comment by carns** [comment]
I've hit this same problem in a different build environment using spack v0.16.0.  In my case the package failure was in a deep dependency, and it's build error output was hidden in the terminal as spack continued attempting to build other packages in the dependency tree.   The final return code from `spack install` was 0,  so there wasn't any way to observe the error other than from a) subsequent build failures in the environment or b) by scrolling back through the spack install output to look for errors.

**Comment by tldahlgren** [comment]
I've been catching up on this thread -- across duplicate tickets -- and now understand the issue.  Build queue processing raises an `InstallError` if any explicitly requested spec fails to install.  I don't recall doing the same if any were skipped.

(Looking at the code now.)
