### ISSUE TITLE
Installation issue: py-tensorflow@2.1 (power9)

### ISSUE THREAD

**Issue by bhatiaharsh** [LLNL/spack#20513]
Tensorflow build on power9 (lassen.llnl) simply hangs (waited ~12 hours before canceling).

### Steps to reproduce the issue

```console
$ spack install -v py-tensorflow@2.1.0~cuda~nccl
```

### Information on your system

* **Spack:** 0.11.2-9807-5771441ec
* **Python:** 3.7.2
* **Platform:** linux-rhel7-power9le

**Note:** There seems to be a bug in the version reported. I am working off of v0.16.0. See the output of `git log`

```
5771441ec (Tue Dec 22 09:05:48 2020 -0800) | small fix in tensorflow package (HEAD -> fix/bazel+tf, origin/fix/bazel+tf) [Harsh Bhatia]
0a1499ed3 (Wed Dec 16 01:24:59 2020 -0800) | fix bazel on power9 [Harsh Bhatia]
77d9acb07 (Wed Nov 18 01:30:27 2020 -0800) | update CHANGELOG.md for v0.16.0 [Todd Gamblin]
82383093e (Wed Nov 18 01:31:45 2020 -0800) | bump version number to 0.16.0 [Todd Gamblin]
532fc40e9 (Wed Nov 18 13:21:55 2020 +0100) | clingo: add `master` branch version (#19958) [Massimiliano Culpo]
20367e472 (Wed Nov 18 12:20:56 2020 +0100) | cmd: add `spack mark` command (#16662) [Michael Kuhn]
77b2e578e (Wed Nov 18 02:39:02 2020 -0800) | spack test (#15702) [Greg Becker]
```

### Additional information

The installation hangs at this point. Here, I reproduced the issue and interrupted to grab the log.
```
INFO: Analyzed target //tensorflow/tools/pip_package:build_pip_package (303 packages loaded, 24805 targets configured).
INFO: Found 1 target...

==> Error: Failed to install py-tensorflow due to KeyboardInterrupt:
==> Error: Exception occurred in writer daemon!
Traceback (most recent call last):
  File "/usr/gapps/mummi/spack/lib/spack/llnl/util/tty/log.py", line 742, in _writer_daemon
    rlist, _, _ = _retry(select.select)(istreams, [], [], 1e-1)
  File "/usr/gapps/mummi/spack/lib/spack/llnl/util/tty/log.py", line 825, in wrapped
    return function(*args, **kwargs)
KeyboardInterrupt

==> Error: Keyboard interrupt.
```

* [spack-build-out.txt](https://github.com/spack/spack/files/5731278/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/5731279/spack-build-env.txt) 

@adamjstewart 

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
> Note: There seems to be a bug in the version reported.

Yeah, you need to run `git fetch upstream --tags` to get it working properly, I think it's a git bug/feature.

**Comment by adamjstewart** [comment]
Is this still the case with the latest version of the package?

**Comment by adamjstewart** [comment]
TensorFlow 2.1 is no longer in Spack. Let me know if you have the same issue with newer versions. In the near future, we're planning on adding a CI stack to build TF and friends on PPC.
