### ISSUE TITLE
Don't build GCC with libisl (graphite) by default

### ISSUE THREAD

**Issue by zorun** [LLNL/spack#20515]
It's a bit surprising that GCC is built with ISL: this is not enabled by default upstream, and most toolchains I know (Debian, OpenWrt) don't enable it.

In addition, compatibility is rather picky, as evidenced by the many version constraints in the current package and by upstream bug reports: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=graphite

It would make more sense to use ISL only as an optional dependency. When the option is disabled, the following is needed to make sure graphite is not used:
```
--without-isl --without-cloog
```

**Comment by adamjstewart** [comment]
@michaelkuhn 

I agree with making it an optional variant, don't know enough about GCC as to whether it should default to True or False.

**Comment by michaelkuhn** [comment]
FWIW, Fedora and consequently RHEL/CentOS have it enabled. I don't have a strong opinion about it, though. We can leave it disabled by default.

@zorun Care to submit a PR?

**Comment by zorun** [comment]
Sure, thanks for the feedback.

Here are the PR: #20531 and (just to be sure) #20532
