### ISSUE TITLE
improve installation of Zoltran: imposing +int64 constrains on parmetis

### ISSUE THREAD

**Issue by ravil-mobile** [LLNL/spack#20545]
### Rationale
zoltan spec has a variant called  `int64` which imposes the corresponding constrain on metis. 
https://github.com/spack/spack/blob/6947951aaf9954b1dfd12ca7a9266d7335f07105/var/spack/repos/builtin/packages/zoltan/package.py#L37-L44

The same constrain must be applied to parmetis. 

### Description
I guess a solution can be something like
```
depends_on('parmetis@4:', when='+parmetis') 
depends_on('parmetis@4: +int64', when='+parmetis+int64')
```

### Additional information

I guess this happens because parmetis package has been recently updated and `int64` has been added. Because there was no such an option in parmetis for a long time people came up with a workaround by specifying `metis+int64` explicitly in their script. The parametis update brings an inconsistency because `int64`   is off by default in parmetis, however, and the ''legacy'' workaround imposes `int64` on metis.
My spack version is 0.16.0

### General information

- [x] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Your suggestion looks good to me, want to submit a PR?

**Comment by ravil-mobile** [comment]
Thanks. I will submit
