### ISSUE TITLE
Installation issue: py-mikado

### ISSUE THREAD

**Issue by t-nojiri** [LLNL/spack#20552]
I have detected two problems.
1) The version of py-biopython and py-pysam specified in depends_on is the version that spack does not support.
2) py-mikado will result in a Fetch Error.

I can handle the error 1), but not 2).

**Comment by adamjstewart** [comment]
For 2), I would change the download to https://pypi.io/packages/source/M/Mikado/Mikado-1.2.4.tar.gz and update the package to that version.

**Comment by t-nojiri** [comment]
Thank you for your comment on how to deal with it.
I have confirmed that it can be built on x86_64 and aarch64 machines.

**Comment by t-nojiri** [comment]
Should I issue this PR as one PR?
Since the change in 1) is the addition of a new version, I am wondering whether to create one PR or separate it.

**Comment by adamjstewart** [comment]
Yes, one PR for the whole package is fine.

**Comment by t-nojiri** [comment]
thank you for your answer.
