### ISSUE TITLE
mumps@5.3.3 fails: patch rejected

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#20590]
`mumps@5.3.3` is failing, I think, because of the patch introduced with 0150b394d7df0a3b6104f061514dfa5539bddde0

Using:
* `spack@develop` (1e971b62de76d731d5a220a0b271e105bf01caca)
* `Mon Dec 28 13:48:20 2020 -0800`
* Ubuntu 18.04 on x86_64

Concrete spec: [mumps-nnlqlp.spec.yaml.txt](https://github.com/spack/spack/files/5748938/mumps-nnlqlp.spec.yaml.txt)

```
$> spack install -f ./mumps-nnlqlp.spec.yaml
...
==> Installing mumps-5.3.3-nnlqlpa4wpvksountoctpeu25pndj2ui
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/27/27e7749ac05006bf8e81a457c865402bb72a42bf3bc673da49de1020f0f32011.tar.gz
##################################################################################################################################################################### 100.0%
1 out of 2 hunks FAILED -- saving rejects to file src/Makefile.rej
==> Patch /opt/spack/var/spack/repos/builtin/packages/mumps/mumps.src-makefile.patch failed.
==> Error: ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/opt/spack/var/spack/repos/builtin/packages/mumps/mumps.src-makefile.patch' '-d' '.'
```

@payerle @adamjstewart @scottwittenburg

**Comment by eugeneswalker** [comment]
@payerle Do you know why these are getting rejected? What version of mumps did you test this with? The src/Makefile lines targeted for patching don't match the patch file with mumps 3.3, did you test on a different version? Do we need to maintain two different patches -- one for the version you tested this with and one for mumps 3.3?

**Comment by payerle** [comment]
My bad.  I tested with mumps@5.2.0, and it looks like they changed ordering of some of the include -I flags between that and 5.3.3.

It looks like two versions of the patch are needed.

**Comment by eugeneswalker** [comment]
Sounds good. I will use your patch for 5.2 as a template and submit a new patch and a PR that applies the correct patch depending on the mumps version.
