### ISSUE TITLE
Could c-blosc2 use some stable version instead of develop version?

### ISSUE THREAD

**Issue by darmac** [LLNL/spack#20650]
It looks like these's some release version for `c-blosc2`, why we only use `develop` version?

`https://github.com/Blosc/c-blosc2/releases`

**Comment by adamjstewart** [comment]
@ax3l is the maintainer

**Comment by ax3l** [comment]
Sounds great, let's tag (only) the latest release for now? @darmac

**Comment by ax3l** [comment]
Ah, I see. `c-blosc2` is still in open beta, with the latest release being `v2.0.0.beta.5`.
https://github.com/Blosc/c-blosc2/releases

My intention was to wait for the first non-preview release before starting to tag things, but if you rely on such a preview release we can also start earlier. Do you like to co-maintain the package if you use it actively, @darmac?

**Comment by darmac** [comment]
@ax3l 
I opened this issue because this package build failed when I use a earlier spack version.

But sorry, infact, I'm not a active user :(
I think using a non-preview release is a good idea, we can just wait the really stable version.

**Comment by ax3l** [comment]
No worries. If someone reads this and needs a tagged version, feel free to submit a PR :+1:
