### ISSUE TITLE
Spack thinks something is installed that was killed long before the install completed.

### ISSUE THREAD

**Issue by BarrySmith** [LLNL/spack#2066]
$ ./spack install --dirty xsdk@develop+skiptrilinos
==> Installing xsdk
==> Installing petsc
==> Installing hypre
==> openmpi is already installed in /scratch/bsmith/spack/opt/spack/linux-Ubuntu12-x86_64/intel-16.0.3/openmpi-2.0.1-lryxkhida6aihfig3jorzoossiwkccdk
==> Installing openblas
==> Trying to fetch from file:///scratch/bsmith/spack/var/spack/cache/openblas/openblas-0.2.19.tar.gz
######################################################################## 100.0%
==> Staging archive: /scratch/bsmith/spack/var/spack/stage/openblas-0.2.19-opuuybyhyzuqhxyyz5jfttiwpkzuw2e7/v0.2.19.tar.gz
==> Created stage in /scratch/bsmith/spack/var/spack/stage/openblas-0.2.19-opuuybyhyzuqhxyyz5jfttiwpkzuw2e7
==> Applied patch make.patch
==> Building openblas
Terminated

      NOTE I put a control c here and kill the build because I did not want it to make openblas, this is   what caused the Terminated

/sandbox/bsmith/spack/bin (barry/develop *>) 
$ ./spack install --dirty xsdk@develop+skiptrilinos
==> Installing xsdk
==> Installing petsc
==> Installing hypre
==> openmpi is already installed in /scratch/bsmith/spack/opt/spack/linux-Ubuntu12-x86_64/intel-16.0.3/openmpi-2.0.1-lryxkhida6aihfig3jorzoossiwkccdk
==> openblas is already installed in /scratch/bsmith/spack/opt/spack/linux-Ubuntu12-x86_64/intel-16.0.3/openblas-0.2.19-opuuybyhyzuqhxyyz5jfttiwpkzuw2e7
Traceback (most recent call last):
  File "./spack", line 202, in <module>
    main()
  File "./spack", line 179, in main
    return_val = command(parser, args)
  File "/scratch/bsmith/spack/lib/spack/spack/cmd/install.py", line 118, in install
    package.do_install(**kwargs)
  File "/scratch/bsmith/spack/lib/spack/spack/package.py", line 1004, in do_install
    dirty=dirty)
  File "/scratch/bsmith/spack/lib/spack/spack/package.py", line 1004, in do_install
    dirty=dirty)
  File "/scratch/bsmith/spack/lib/spack/spack/package.py", line 1004, in do_install
    dirty=dirty)
  File "/scratch/bsmith/spack/lib/spack/spack/package.py", line 983, in do_install
    rec = spack.installed_db.get_record(self.spec)
  File "/scratch/bsmith/spack/lib/spack/spack/database.py", line 79, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/scratch/bsmith/spack/lib/spack/spack/database.py", line 527, in get_record
    key = self._get_matching_spec_key(spec, **kwargs)
  File "/scratch/bsmith/spack/lib/spack/spack/database.py", line 522, in _get_matching_spec_key
    raise KeyError("No such spec in database! %s" % spec)
KeyError: 'No such spec in database! openblas@0.2.19%intel@16.0.3+fpic~openmp+shared arch=linux-Ubuntu12-x86_64'
/sandbox/bsmith/spack/bin (barry/develop *>) 

So spack seems to believe openblas was installed based on just the fact it STARTED to install openblas, not that it was successfully installed. Then of course trouble because it wasn't installed.

**Comment by alalazo** [comment]
@BarrySmith Not a solution, just a work-around to get you going : 
```
$ rm -rf  /scratch/bsmith/spack/opt/spack/linux-Ubuntu12-x86_64/intel-16.0.3/openblas-0.2.19-opuuybyhyzuqhxyyz5jfttiwpkzuw2e7
```
The behavior with <kbd>Ctrl</kbd>+<kbd>C</kbd> is a long-standing one, and maybe we should try to fix it before `0.10`. I'll try to see if I can prepare a PR for it.

**Comment by pramodk** [comment]
From my experiences `spack reindex` also fix the `inconsistent` state.

**Comment by tgamblin** [comment]
I added this as a blocker for `0.10`.

**Comment by alalazo** [comment]
@BarrySmith Can you confirm that with the latest develop this behavior has been fixed ?

**Comment by BarrySmith** [comment]
I will report again in the future if I see the same behavior,

**Comment by tgamblin** [comment]
ok closing for now -- please reopen/refile if it recurs.
