### ISSUE TITLE
`cc` shouldn't unset `LD_LIBRARY_PATH` when it is already unset in `build_environment.py`

### ISSUE THREAD

**Issue by tgamblin** [LLNL/spack#2072]
As reported by @BarrySmith in #1813, `cc` is still unsetting `LD_LIBRARY_PATH` and some other variables when it shouldn't:

`cc.py:`
```bash
unset LD_LIBRARY_PATH
unset LD_RUN_PATH
unset DYLD_LIBRARY_PATH
```

This shouldn't happen because these things are already unset in `build_environment.py` before the build begins:

```python
    # Stuff in here sanitizes the build environemnt to eliminate
    # anything the user has set that may interfere.
    if not dirty:
        # Remove these vars from the environment during build because they
        # can affect how some packages find libraries.  We want to make
        # sure that builds never pull in unintended external dependencies.
        env.unset('LD_LIBRARY_PATH')
        env.unset('LIBRARY_PATH')
        env.unset('CPATH')
        env.unset('LD_RUN_PATH')
        env.unset('DYLD_LIBRARY_PATH')
```

**Comment by mplegendre** [comment]
What a well timed bug report...

I'm trying to use IBM's Spectrum MPI under Spack and just hit the same issue.  The Spectrum MPI compiler wrappers are written to expect LD_LIBRARY_PATH can be passed from the MPI wrapper to ld.  The spack compiler wrappers are sitting between these two and is clearing LD_LIBRARY_PATH.

**Comment by alalazo** [comment]
Hmmm, I didn't consider this a bug. Between unsetting those variables in `build_environment` and again in `cc` there's usually some build-system that could set them to some value.

**Comment by tgamblin** [comment]
@mplegendre: you can thank @BarrySmith 😄 

@alalazo: the issue is that they break `spack install --dirty` and they'll break cray modules and module-loaded compilers.  `build_environment.py` cleans the environment and loads modules that can set `LD_LIBRARY_PATH` for the build environment, and those paths might be needed for the compiler to run. 

Do you know of situations where the build system sets `LD_LIBRARY_PATH` before calling a compiler? I'm actually not sure I've ever seen that.
