### ISSUE TITLE
PNG support in R missing?

### ISSUE THREAD

**Issue by jasonbuechler** [LLNL/spack#20731]
### Steps to reproduce the issue

```console
$ spack info r ## Note: no PNG support/option is listed
$ Rscript <(echo "capabilities()")
$ Rscript <(echo "png()")
```

### Error Message

```console
$ spack info r|grep -A8 Variants
Variants:
    Name [Default]            Allowed values    Description
    ======================    ==============    ============================================

    X [off]                   on, off           Enable X11 support (call configure --with-x)
    external-lapack [off]     on, off           Links to externally installed BLAS/LAPACK
    memory_profiling [off]    on, off           Enable memory profiling
    rmath [off]               on, off           Build standalone Rmath library

$ Rscript <(echo "capabilities()") | grep -A1 png
       jpeg         png        tiff       tcltk         X11        aqua
      FALSE       FALSE       FALSE       FALSE       FALSE       FALSE
$ Rscript <(echo "png()")
Error in .External2(C_X11, paste0("png::", filename), g$width, g$height,  :
  unable to start device PNG
Calls: png
In addition: Warning message:
In png() : no png support in this version of R
Execution halted
```

### Information on your system

output of `spack debug report` -->
```
$ spack debug report
* **Spack:** 0.16.0-247-86f006ffa
* **Python:** 3.6.8
* **Platform:** linux-centos8-ivybridge
* **Concretizer:** original
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

I'm checking the "in debug mode" box even though I don't believe it's relevant, just in case an issue-bot is looking for reasons to ignore this.

**Comment by adamjstewart** [comment]
There is currently no official maintainer for the `r` package in Spack, but you're welcome to submit a PR to add a new `+png` variant.

**Comment by jasonbuechler** [comment]
> There is currently no official maintainer for the `r` package in Spack, but you're welcome to submit a PR to add a new `+png` variant.

Understood.  I took a crack at it here: https://github.com/spack/spack/pull/20753

**Comment by glennpj** [comment]
Support for png is dependent on whether R was built with the `+X` variant or not.
```
./opt/spack/linux-centos7-broadwell/gcc-8.4.0/r-4.0.3-kixr37cujfrkxp3vzkguje4wxyodklv6/bin/Rscript <(echo "capabilities()")
       jpeg         png        tiff       tcltk         X11        aqua 
       TRUE        TRUE        TRUE        TRUE       FALSE       FALSE
```
Interestingly enough, `+X` does not enable X11 support. It looks like the variant combinations need to be worked on a bit. The same issue applies for jpeg and tiff.

**Comment by adamjstewart** [comment]
@glennpj what about #20753?

**Comment by glennpj** [comment]
I am not sure if building with an explicit `--with-libpng` enables PNG support without `+X`. I am wondering if something like the following might be sufficient:
```
depends_on('libpng', when=''+X')
depends_on('libtiff', when=''+X')
depends_on('jpeg', when=''+X')
```

**Comment by glennpj** [comment]
By the way, `libpng` is currently in the spec for `r` but it would be best to make that explicit.

**Comment by glennpj** [comment]
Okay; I just tested #20753. As I suspected, getting png support requires that R be built with `+X`. I think rather than create variants for the graphics formats we just make them part of the build with `+X` as in https://github.com/spack/spack/issues/20731#issuecomment-769360070.

**Comment by glennpj** [comment]
@jasonbuechler You could modify #20753 to modify the dependency specs as above to make png support in R more clear.

**Comment by glennpj** [comment]
@jasonbuechler While libpng support is already in R when using the `+X` variant, I just submitted #21654 which makes this more clear, I hope.

**Comment by tashrifbillah** [comment]
Hi, I am not Redhat 9 and R-4.4.2. I solved this by:

```
./configure --with-libpng
make -j4
```
