### ISSUE TITLE
Clingo concretizer regression

### ISSUE THREAD

**Issue by joshessman-llnl** [LLNL/spack#20736]
### Steps to reproduce the issue

Discovered while merging develop into #20657, appears to have been introduced in https://github.com/spack/spack/commit/0ce08640e08de8f7313a4b3974131e2efa5249e0

Using `clingo@master` with the standard (i.e., non-CFFI) Python module:

```console
$ python3 -c "import clingo; print(hasattr(clingo.Symbol, '_rep'), clingo.__version__)" 
False 5.5.0 # False means non-CFFI
$ git checkout 49ac3471cf97f5308c648a78a9fd7b0c3a083e90
$ ./bin/spack spec -I libxml2+python
# concretizes....
$ git checkout 0ce08640e08de8f7313a4b3974131e2efa5249e0 
$ ./bin/spack spec -I libxml2+python
Input spec
--------------------------------
-   libxml2+python
Concretized
--------------------------------
==> Error: 'sqlite'
```

Result of `git diff` in the spack repo:
```diff
diff --git a/etc/spack/defaults/config.yaml b/etc/spack/defaults/config.yaml
index d1a7f35a6d..e8147838b6 100644
--- a/etc/spack/defaults/config.yaml
+++ b/etc/spack/defaults/config.yaml
@@ -160,7 +160,7 @@ config:
   #
   # 'clingo' currently requires the clingo ASP solver to be installed and
   # built with python bindings. 'original' is built in.
-  concretizer: original
+  concretizer: clingo


   # How long to wait to lock the Spack installation database. This lock is used
diff --git a/etc/spack/defaults/packages.yaml b/etc/spack/defaults/packages.yaml
index bf9148315b..9eacff87c6 100644
--- a/etc/spack/defaults/packages.yaml
+++ b/etc/spack/defaults/packages.yaml
@@ -53,3 +53,9 @@ packages:
    permissions:
      read: world
      write: user
+  python:
+    version: [3.8.2]
+    buildable: false
+    externals:
+    - spec: python@3.8.2
+      prefix: /usr 
```

### Error Message

```console
$ spack spec -I libxml2+python
Traceback (most recent call last):
  File "./bin/spack", line 68, in <module>
    sys.exit(spack.main.main())
  File "spack/lib/spack/spack/main.py", line 762, in main
    return _invoke_command(command, parser, args, unknown)
  File "spack/lib/spack/spack/main.py", line 490, in _invoke_command
    return_val = command(parser, args)
  File "spack/lib/spack/spack/cmd/spec.py", line 102, in spec
    spec.concretize()
  File "spack/lib/spack/spack/spec.py", line 2528, in concretize
    self._new_concretize(tests)
  File "spack/lib/spack/spack/spec.py", line 2498, in _new_concretize
    result = spack.solver.asp.solve([self], tests=tests)
  File "spack/lib/spack/spack/solver/asp.py", line 1625, in solve
    return driver.solve(setup, specs, dump, models, timers, stats, tests)
  File "spack/lib/spack/spack/solver/asp.py", line 362, in solve
    answers = builder.build_specs(tuples)
  File "spack/lib/spack/spack/solver/asp.py", line 1549, in build_specs
    action(*args)
  File "spack/lib/spack/spack/solver/asp.py", line 1429, in version
    self._specs[pkg].versions = spack.version.ver([version])
KeyError: 'sqlite'
```

### Information on your system

* **Spack:** 0.16.0-440-0ce08640e0                                                                                                                                                                                  * **Python:** 3.8.5                                                                                                                                                                                                 * **Platform:** linux-ubuntu20.04-skylake                                                                                                                                                                           * **Concretizer:** clingo   

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by becker33** [comment]
@tgamblin I think this comes from your refactoring work. Do you want to dig into it or should I?

**Comment by tgamblin** [comment]
@becker33 want to try? I’ve been busy with another task and won’t get back to this for a bit, but it’d be good if you looked.

**Comment by becker33** [comment]
@alalazo chimed in via slack and offered to take it on.

**Comment by alalazo** [comment]
Having an external Python in packages.yaml is required to trigger the issue:
```yaml
packages:
  python:
    externals:
    - spec: python@3.8.5+bz2+ctypes+dbm+lzma+nis+pyexpat+readline+sqlite3+ssl~tix~tkinter+uuid+zlib
      prefix: /home/culpo/production/spack/solver-rebased/view
    buildable: false
```

**Comment by alalazo** [comment]
Digging into it, it seems that the answer set contains atoms for node attributes without having that specific node in the solution DAG. In this particular case:
```
node("sqlite")
```
is not in the answer set, but:
```
version("sqlite", "3.34.0")
```
is.

**Comment by alalazo** [comment]
It seems we deduce that certain dependency conditions hold also for external packages. Adding another condition to that rule:
```
dependency_conditions_hold(ID, Parent, Dependency) :-
  attr(Name, Arg1)             : required_dependency_condition(ID, Name, Arg1);
  attr(Name, Arg1, Arg2)       : required_dependency_condition(ID, Name, Arg1, Arg2);
  attr(Name, Arg1, Arg2, Arg3) : required_dependency_condition(ID, Name, Arg1, Arg2, Arg3);
  dependency_condition(ID, Parent, Dependency);
  node(Parent);
  not external(Parent).
```
makes `libxml2+python` concretize for me. Checking right now if all unit tests are passing.

**Comment by alalazo** [comment]
@joshessman-llnl Can you confirm that #20790 solves your issue?

**Comment by joshessman-llnl** [comment]
@alalazo Thanks for taking a look at this, it indeed solves the problem I was running into.
