### ISSUE TITLE
spack external find problem with bzip2

### ISSUE THREAD

**Issue by germasch** [LLNL/spack#20745]
I used `spack external find` on a RHEL-based system (`Red Hat Enterprise Linux Server release 7.7 (Maipo)`)

It detected bzip2:

```
  bzip2:
    externals:
    - spec: bzip2@1.0.6
      prefix: /usr
```

However, that bzip2 isn't actually usable for development, since there is no header file, and just the versioned shared library. If I had root access I could probably install a corresponding devel package, but I don't, and as a user it'd be better to have spack not detect an unusable bzip2, but rather skip it and then build its own bzip2 as required.

### Steps to reproduce the issue

```console
$ spack install adios2
```

This isn't an adios2 problem, though, it'll likely happen to other packages depending on bzip2.

### Error Message

Inside the cmake configuration step of adios2:
```
[...]
   17      Could NOT find BZip2 (missing: BZIP2_LIBRARIES BZIP2_INCLUDE_DIR)
```
### Information on your system

```
* **Spack:** 0.16.0
* **Python:** 2.7.5
* **Platform:** linux-rhel7-zen2
```
### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
This issue is possibly pointing at a documented limitation, see [here](https://spack.readthedocs.io/en/latest/build_settings.html#cmd-spack-external-find):

> The current implementation only collects and examines executable files, so it is typically only useful for build/run dependencies (in some cases if a library package also provides an executable, it may be possible to extract a meaningful Spec by running the executable - for example the compiler wrappers in MPI implementations).

Maybe we can solve the specific problem with `bzip2` in its own `package.py` and collect experience how to generalize the solution to other `link` type dependencies. Off the top of my head this involves just searching for some specific header files before detecting the spec.

**Comment by germasch** [comment]
Thanks, you're right, it's a documented limitation (I hadn't seen that), not a bug. Nevertheless it is a hurdle to getting started with spack, in particular for people who can't make sense of the ensuing errors when afterwards trying to install dependent packages with spack.

I just hit the same issue again with openssl -- `spack external find` found the Ubuntu 20.04 openssl (with the wrong prefix, too, IIRC), but then `spack install cmake` failed. I had to `apt install libssl-dev` to get around this.

A workaround might be to limit `spack external find` to packages that aren't sometimes used as link dependencies. E.g., for cmake I'd never expect a problem. But for openssl, I think the library part is frequently used in dependents. In the case of bzip2, I probably hit the exception in that adios2 was actually using the library part of it, I'd think in most cases dependents would only use the executables.

**Comment by alalazo** [comment]
Related to #19364

**Comment by alalazo** [comment]
This issue is specific to `bzip2`. The general problem exposed here is tracked and discussed in #19364 + since v0.18 Spack also supports detecting libraries, so closing this issue for now. Feel free to reopen if you think any specific point needs to be addressed in terms of new functionality.
