### ISSUE TITLE
sbang relocation broken (again)

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#20766]
`sbang` relocation is broken under some conditions using `spack@develop` (1e3f6489c49f68f3efb3966c81a5f2ae8e0a08c1, `Fri Jan 8 15:48:23 2021 -0500`)

The conditions under which the problem manifests are described below.

1. Build binaries from source, into a long install_tree using <i>both</i>
  * `config: install_tree: root: <root>`
  * `config: install_tree: padded_length: <N>`
  * For instance, here is `config.yaml` for the build-from-source-environment:
```
config: 
  install_tree:
    root: /spack-software
    padded_length: 64
```
2. Cache those binaries
3. Install the binaries into a different `install_tree: root`
  * For instance, here is `config.yaml` for the subsequent install-from-cache-environment:
```
config:
  install_tree:
    root: /spack
```
4. If you then inspect the sbang lines in the installed files, they will still point to the original, unrelocated sbang location. For the example config.yamls above, that would be `/spack-software/bin/sbang`

Here is a concrete reproducer that illustrates the problem with sbang relocation in autoconf.

```
$> git clone https://github.com/spack/spack /opt/spack
$> (cd /opt/spack && git checkout 1e3f6489c)
$> . /opt/spack/share/spack/setup-env.sh

$> spack config edit config <--- use the config.yaml from #1 above (build-from-source-environment)
$> spack install --no-cache autoconf
... OK
$> spack mirror add local /
$> spack gpg create test test
$> spack buildcache create -af --key test -m local autoconf
OK

$> spack uninstall --all
$> spack clean -a
$> rm -rf /spack-software

$> spack config edit config <-- use the config.yaml from #3 above (install-from-cache-environment)
$> spack install --cache-only autoconf
OK

$> head -1 `spack location -i autoconf`/bin/autoreconf
#!/bin/sh /spack-software/bin/sbang

$> spack install --no-cache automake
...
==> Installing automake-1.16.3-yfcevnm4jeomgs3k3hatiuqvqxilcfo4
==> Fetching https://spack-llnl-mirror.s3-us-west-2.amazonaws.com/_source-cache/archive/ce/ce010788b51f64511a1e9bb2a1ec626037c6d0e7ede32c1c103611b9d3cba65f.tar.gz
############################################################################################################################################################################# 100.0%
==> automake: Executing phase: 'autoreconf'
==> automake: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/tmp/root/spack-stage/spack-stage-automake-1.16.3-yfcevnm4jeomgs3k3hatiuqvqxilcfo4/spack-src/configure' '--prefix=/spack/linux-ubuntu18.04-skylake_avx512/gcc-7.5.0/automake-1.16.3-yfcevnm4jeomgs3k3hatiuqvqxilcfo4'

1 error found in build log:
     17    checking for byacc... no
     18    checking for bison... no
     19    checking for lex... no
     20    checking for flex... no
     21    checking whether autoconf is installed... yes
     22    checking whether autoconf works... no
  >> 23    configure: error: The installed version of autoconf does not work.
     24        Please check config.log for error messages before this one.
```

I am going to try and fix this. I just wanted to put this issue up to track it, and to alert others who might be at risk of encountering this in the interim period.

@scottwittenburg @gartung

**Comment by adamjstewart** [comment]
This issue (and your PR) should probably be moved to https://github.com/spack/sbang

**Comment by eugeneswalker** [comment]
except this has to do w relocation of sbang which is not handled by sbang, right?

**Comment by adamjstewart** [comment]
Hmm, not sure, feel free to ignore me

**Comment by gartung** [comment]
@adamjstewart I have been out of the loop with the sbang changes. Is sbang now a "vendored" subpackage of spack. Can the sbang install be outside of both the spack source directory and the spack install root? I seem to recall that there was a problem with long paths and sbang.

**Comment by gartung** [comment]
@eugeneswalker This change was supposed to handle sbang relocation from the old format to the new format. 
https://github.com/spack/spack/commit/a80d221bfa1c9be4b2b9eff9f057edf62c34e50b#diff-f18647423e51ee5a190a09fc1ddeec214b1f8e3b45f68080df621971fd5b0f7d

**Comment by gartung** [comment]
It looks like the sbang line with the new format is not being replaced. Is that correct?

**Comment by eugeneswalker** [comment]
> It looks like the sbang line with the new format is not being replaced. Is that correct?

Yes and no. The problem is only when the binaries are originally built with the `config: install_tree: padded_length:` setting.

When you build with:
```
config:
  install_tree:
    root: <PATH>
    padded_length: 64
```

The sbang script is stored at `unpadded_root/bin/sbang` -- but this is not relocated properly when you later try to install those binaries from the cache.

However, when you build _without_ `config: install_tree: padded_length`, the relocation works.

**Comment by gartung** [comment]
Hmm... I suspect it has something to do with the sbang location being defined as the unpadded root

https://github.com/spack/spack/blob/de3504ca2965e8cdba4e615d6bcb590f274aebef/lib/spack/spack/hooks/sbang.py#L30

**Comment by eugeneswalker** [comment]
> Hmm... I suspect it has something to do with the sbang location being defined as the unpadded root
> 
> https://github.com/spack/spack/blob/de3504ca2965e8cdba4e615d6bcb590f274aebef/lib/spack/spack/hooks/sbang.py#L30

Right. I believe the reasoning there was because of the expectation that padding would make a long path, and using a long path to reference sbang would defeat the purpose of the sbang.

**Comment by gartung** [comment]
Right so with padding the sbang_root != install_root and that sbang line is never replaced. Your proposed solution of storing the old sbang root seems to work.
