### ISSUE TITLE
Installation issue: amrex +cuda

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#20762]
The `amrex` package has an error where it uses `spec` instead of `self.spec`. This happens when installing `amrex +cuda`.

```
==> Installing amrex-21.01-x3ueyxgshtahu3d4ttstr7gvyp4adhol
==> No binary for amrex-21.01-x3ueyxgshtahu3d4ttstr7gvyp4adhol found: installing from source
==> Using cached archive: /home/eschnetter/src/CarpetX/spack/var/spack/cache/_source-cache/archive/59/59de3ed429347ee6a7ad4f09c0c431248f2e081f59c301db37cacb36993622f4.tar.gz
==> amrex: Executing phase: 'cmake'
==> Error: NameError: name 'spec' is not defined

/home/eschnetter/src/CarpetX/spack/var/spack/repos/builtin/packages/amrex/package.py:196, in cmake_args:
        193            args.append('-DAMReX_CUDA_ERROR_CAPTURE_THIS=ON')
        194            args.append('-DAMReX_CUDA_ERROR_CROSS_EXECUTION_SPACE_CALL=ON')
        195
  >>    196            cuda_arch = spec.variants['cuda_arch'].value
        197            if cuda_arch == 'none':
        198                args.append('-DAMReX_CUDA_ARCH=Auto')
        199            else:

See build log for details:
  /tmp/eschnetter/spack-stage/spack-stage-amrex-21.01-x3ueyxgshtahu3d4ttstr7gvyp4adhol/spack-build-out.txt
```

@asalmgren  @mic84

**Comment by eschnett** [comment]
Also, the check `if cuda_arch == 'none':` does not seem to be working. It seems that checking `cuda_arch[0]` instead does work. This would also be an error in the Spack documentation at <https://spack.readthedocs.io/en/latest/build_systems/cudapackage.html?highlight=cudapackage#provided-variants-and-dependencies>.

**Comment by eschnett** [comment]
Sorry to keep adding on to this issue: It seems that Spack wants the `cuda_arch` variant to be set to `75` (no dot), but AMReX wants it to be `7.5` (with a dot). Neither works; it is not possible to use the `cuda_arch=...` setting.

**Comment by mic84** [comment]
@eschnett thank you for reporting. Can you try PR #20786 and see if it solves the issue? Thanks!

**Comment by eschnett** [comment]
I believe the current version of Spack and AMReX solved this issue.

**Comment by alalazo** [comment]
@eschnett Closing this then based on your comment. Feel free to reopen if I misunderstood.
