### ISSUE TITLE
HIP_PLATFORM inconsistency

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#20774]
Currently in https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/hip/package.py we build with `HIP_PLATFORM=rocclr`, but in `setup_dependent_build_environment` we use `HIP_PLATFORM=hcc`.

Can you please comment on this @srekolam / @arjun-raj-kuppala / @amd-toolchain-support? What should the value be?

**Comment by alalazo** [comment]
@amd-toolchain-support

**Comment by srekolam** [comment]
i was able to talk to hip team and they are looking at fixing it with ROCm4.1.
here is what it would look like post the ROCm4.1
HIP_COMPILER : clang
HIP_PLATFORM : amd
HIP_RUNTIME  : rocclr

**Comment by srekolam** [comment]
@haampie  , can we close this ticket ?
