### ISSUE TITLE
do not RPATH external system package

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#2079]
@tgamblin :

> Right now Spack will RPATH any system dependency... But it doesn't have to.

> If an external is in a system search path, we should just not RPATH it. You can find those on Linux by looking at /etc/ld.so.conf, and on Mac OS X the default search paths are embedded in dyld: /Library/Frameworks:/Network/Library/Frameworks:/System/Library/Frameworks and /usr/local/lib:/lib:/usr/lib. Not sure why /lib is preferred over /usr/lib, but whatever. We should just have the build environment exclude these from the automatic -I, -L, and -Wl,-rpath args. They'll still be found, but at a lower precedence than the ones supplied in args.

> ...look at:
> lib/spack/spack/build_environment.py
> lib/spack/spack/test/cc
> lib/spack/env/cc

from https://github.com/LLNL/spack/issues/2067#issuecomment-255410058

**Comment by citibeth** [comment]
> Not sure why /lib is preferred over /usr/lib

On at least some Linux systems, I believe these directories have been merged and are identical.
