### ISSUE TITLE
Installation issue: pytorch@1.4.0

### ISSUE THREAD

**Issue by rblake-llnl** [LLNL/spack#20810]
### Steps to reproduce the issue

```console
$ spack install py-torch@1.4.0

==> Installing py-torch-1.4.0-c7frpmbymqqbsuripw5sh5npugsadueh
==> No binary for py-torch-1.4.0-c7frpmbymqqbsuripw5sh5npugsadueh found: installing from source
==> Using cached archive: /usr/WS1/aml_user/tools/spack/var/spack/cache/_source-cache/git//pytorch/pytorch.git/v1.4.0.tar.gz
==> Warning: Fetching from mirror without a checksum!
This package is normally checked out from a version control system, but it has been archived on a spack mirror. This means we cannot know a checksum for the tarball in advance. Be sure that your connection to this mirror is secure!
==> Using cached archive: /usr/WS1/aml_user/tools/spack/var/spack/cache/_source-cache/archive/17/17561b16cd2db22f10c0fe1fdcb428aecb0ac3964ba022a41343a6bb8cba7049
==> py-torch: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
'/usr/WS1/aml_user/tools/spack/opt/spack/linux-rhel7-haswell/gcc-7.3.0/python-2.7.18-7zkgtan7i7efedgkyqxa3talv7zma5io/bin/python2.7' '-s' 'setup.py' '--no-user-cfg' 'install' '--prefix=/usr/WS1/aml_user/tools/spack/opt/spack/linux-rhel7-haswell/gcc-7.3.0/py-torch-1.4.0-c7frpmbymqqbsuripw5sh5npugsadueh' '--single-version-externally-managed' '--root=/'

$ cat spack-build-out.txt
....
==> py-torch: Executing phase: 'install'
==> [2021-01-12-12:24:38.627661] '/usr/WS1/aml_user/tools/spack/opt/spack/linux-rhel7-haswell/gcc-7.3.0/python-2.7.18-7zkgtan7i7efedgkyqxa3talv7zma5io/bin/python2.7' '-s' 'setup.py' '--no-user-cfg' 'install' '--prefix=/usr/WS1/aml_user/tools/spack/opt/spack/linux-rhel7-haswell/gcc-7.3.0/py-torch-1.4.0-c7frpmbymqqbsuripw5sh5npugsadueh' '--single-version-externally-managed' '--root=/'
fatal: Not a git repository (or any parent up to mount point /tmp)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Building wheel torch-1.4.0
-- Building version 1.4.0
Could not find /tmp/cdoutrix/spack-stage/spack-stage-py-torch-1.4.0-c7frpmbymqqbsuripw5sh5npugsadueh/spack-src/third_party/fbgemm/CMakeLists.txt
Did you run 'git submodule update --init --recursive'?
....

```

Seems to be a bug in 1.4.0, recommended to remove this version.

### Information on your system
* **Spack:** 0.16.0
* **Python:** 3.7.2
* **Platform:** linux-rhel7-haswell

### Additional information

* [spack-build-out.txt]()
* [spack-build-env.txt]()

@adamjstewart 

Related to #20801

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
This is related to https://github.com/pytorch/pytorch/issues/35149   

We are explicitly disabling fbgemm by default, but that doesn't seem to be working for some reason. I'll investigate.

**Comment by rblake-llnl** [comment]
Doh!  I looked for a duplicate in the bug reports, I must have missed this one.  Thanks Adam.  Version 1.4.1 doesn't have this problem, for the record.

**Comment by adamjstewart** [comment]
Yeah, 1.4.1 was a re-release just to fix that bug. We actually remove the submodule itself in 1.4.0, so it shouldn't cause this problem. Trying to figure out why it still complains.

**Comment by adamjstewart** [comment]
I looked into this. We had the same problem for the `nervangpu` submodule in 0.4.1 and the `fbgemm` submodule in 1.4.0. The problem is that the git repo for fbgemm changed its commit hashes (must have been a force push). For `nervangpu`, we could simply remove the submodule and move on. For `fbgemm` that doesn't seem to work due to https://github.com/pytorch/pytorch/blob/master/setup.py#L307. We could simply remove that line, but it might be better to figure out how to change the commit hash for that release. Anyway, using 1.4.1 is the best workaround at the moment.
