### ISSUE TITLE
Installation issue: "julia" does not build with gcc@10.2.0

### ISSUE THREAD

**Issue by AEI-SXSmirror** [LLNL/spack#20837]
### Steps to reproduce the issue

```console
$ spack install julia@master
...
```
also `spack install julia`, `spack install julia@1.4.0` etc.

### Information on your system

Tested on both `linux-debian9-x86_64` and `linux-centos7-haswell`.
```
$ spack debug report
* **Spack:** 0.16.0-510-2f19346c9
* **Python:** 3.5.3
* **Platform:** linux-debian9-zen2 __(but using `arch=linux-debian9-x86_64`)__
* **Concretizer:** original
$ spack debug report
* **Spack:** 0.16.0-510-2f19346
* **Python:** 2.7.5
* **Platform:** linux-centos7-haswell
* **Concretizer:** original
```

Compiler gcc@10.2.0 built with itself (bootstrapped from system-provided gcc). Python 3.8.7 available within SPACK.

### Additional information

Error messages varying, perhaps due to unavailable components?

E.g., `spack install julia@master arch=linux-debian9-x86_64`:
```
(...)
==> julia: Executing phase: 'install'
==> Error: Exception occurred in writer daemon!
Traceback (most recent call last):
  File "/.auto/home/SPACK2021/lib/spack/llnl/util/tty/log.py", line 768, in _writer_daemon
    line = _retry(in_pipe.readline)()
  File "/.auto/home/SPACK2021/lib/spack/llnl/util/tty/log.py", line 830, in wrapped
    return function(*args, **kwargs)
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 6: ordinal not in range(128)
==> Error: ProcessError: Command exited with status -13:
    'make' '-j16'

3 warnings found in build log:
(... irrelevant for now, it seems)
```
this looks like `/usr/bin/python3`, 3.5.3 in Stretch, was used instead of Spack's `python`?

Running the same command on `linux-centos7-haswell`,
```
(...)
==> julia: Executing phase: 'install'
==> Error: Exception occurred in writer daemon!
Traceback (most recent call last):
  File "/home/SPACK2021/lib/spack/llnl/util/tty/log.py", line 782, in _writer_daemon
    log_file.write(_strip(line))
  File "/home/SPACK2021/lib/spack/llnl/util/tty/log.py", line 69, in _strip
    return _escape.sub('', line)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 9: ordinal not in range(128)
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8' 'install'

3 warnings found in build log:
(...)
```
i.e., no reference to "where this came from".
Whatever injects UTF-8 there... is, in the end, this a Spack issue and not a Julia one??

* [spack-build-out.txt]()
* [spack-build-env.txt]()

@glennpj

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by AEI-SXSmirror** [comment]
Addition: following #15206 and prefixing the `spack install` command with `LC_ALL=en_US.UTF-8` doesn't change the outcome. The position of the offending character is shifted though (9 to 11 in the second case).

Second addition: loading the latest Python (`spack load python~debug`) following the hints in #15285, then running `LC_ALL=en_US.UTF-8 spack install julia@master [arch=...]` , as suggested by #14598 #15206, works on Debian9 and CentOS7.

So this isn't a Julia problem proper but just another incarnation of the infamous Unicode issue (as in #18536).

Please feel free to merge / close this issue ...

**Comment by alalazo** [comment]
@glennpj ~Pinging you as the maintainer of the package~ Apologies, diagnosis is already in the first comment (I read just the description before)

**Comment by alalazo** [comment]
Closing, since Spack doesn't support running under Python 2 anymore.
