### ISSUE TITLE
The same module installed twice?

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#2087]
How can this be?  These two modules (probably) have the same hash code, wouldn't they be the same file then?

```
$ module avail 2>&1 | grep modele-control
linux-SuSE11-x86_64/modele-control-develop-gcc-5.3.0-m5n4oux
linux-SuSE11-x86_64/modele-control-develop-gcc-5.3.0-m5n4oux
```

**Comment by alalazo** [comment]
Is there any mean to reproduce this problem or a simpler version of it ?

**Comment by citibeth** [comment]
Let's just chalk it up to a bug that might be fixed now.
