### ISSUE TITLE
Hangs on install

### ISSUE THREAD

**Issue by gipert** [LLNL/spack#20903]
Spack install (any package) step hangs on my remote machine, I cannot even terminate it with SIGINT. Since I know the disk is slow, I let it work for a lot of time, but now I suspect it's hung forever. Any suggestion on how to further debug this?

### Steps to reproduce the issue

```console
$ git clone https://github.com/spack/spack.git
$ cd spack/bin
$ ./spack -d --verbose install zlib
==> [2021-01-14-13:34:56.000371] Imported install from built-in commands
==> [2021-01-14-13:34:56.002932] Reading config file /mnt/e15/ge28fok/spack/etc/spack/defaults/config.yaml
==> [2021-01-14-13:34:56.026833] Imported install from built-in commands
==> [2021-01-14-13:34:56.028281] Reading config file /mnt/e15/ge28fok/spack/etc/spack/defaults/repos.yaml
==> [2021-01-14-13:34:57.281556] Reading config file /mnt/e15/ge28fok/spack/etc/spack/defaults/packages.yaml
==> [2021-01-14-13:34:57.316522] Reading config file /home/ge28fok/.spack/linux/compilers.yaml
==> [2021-01-14-13:34:57.333342] DATABASE LOCK TIMEOUT: 3s
==> [2021-01-14-13:34:57.333403] PACKAGE LOCK TIMEOUT: No timeout
```

### Information on your system

```console
$ ./spack debug report
* **Spack:** 0.16.0-564-f6dd85b
* **Python:** 3.6.8
* **Platform:** linux-rhel7-nehalem
* **Concretizer:** original
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Does it help to run Spack with filesystem locks disabled:
```console
$ spack -L <rest  of the command>
```
? Note that this mode of operation is unsafe and suitable only if you can ensure that a single Spack process is running at a given time.

**Comment by gipert** [comment]
Now it works, indeed. Is it there a permanent workaround for this? Also e.g. `. setup-env.sh` hangs.

**Comment by alalazo** [comment]
Can you check if you have lockfiles in the store you're using? For the default configuration it should be:
```console
$ ls -larth ${SPACK_ROOT}/opt/spack/.spack-db/
total 132K
-rwxr-xr-x 1 culpo culpo    0 feb 21  2020 prefix_failures
-rwxrwxr-x 1 culpo culpo    0 ago 10 18:09 lock
-rwxrwxr-x 1 culpo culpo    0 ago 10 18:09 prefix_lock
drwxrwxr-x 9 culpo culpo 4,0K gen  3 17:01 ..
drwxr-xr-x 2 culpo culpo 4,0K gen  5 10:47 failures
-rw-r--r-- 1 culpo culpo 115K gen 15 09:04 index.json
drwxrwxr-x 3 culpo culpo 4,0K gen 15 09:04 .
-rw-r--r-- 1 culpo culpo   36 gen 15 09:04 index_verifier
```
From what I can see here, it seems Spack cannot acquire a lock and it has no timeout on acquiring it - so I am wondering if there are permission issues in your particular setup.

**Comment by gipert** [comment]
Any issue you know on NFS filesystems? BTW:
```console
$ ls -larth spack/opt/spack/.spack-db/
total 24K
drwxr-xr-x 2 ge28fok TUM 4.0K Jan 14 12:07 failures
-rwxr-xr-x 1 ge28fok TUM    0 Jan 14 12:07 lock
drwxr-xr-x 6 ge28fok TUM 4.0K Jan 15 11:46 ..
-rw-r--r-- 1 ge28fok TUM 6.2K Jan 15 11:57 index.json
drwxr-xr-x 3 ge28fok TUM 4.0K Jan 15 11:57 .
-rw-r--r-- 1 ge28fok TUM   36 Jan 15 11:57 index_verifier
```

**Comment by alalazo** [comment]
> Any issue you know on NFS filesystems?

We require NFS v3 and a lock server, even though I don't see this requirement anywhere in our documentation. A similar comment is in [this old issue](https://github.com/spack/spack/issues/17460#issuecomment-658601643).

**Comment by gipert** [comment]
Oh, #17460 seems really about my very same issue, thanks. Let me try to investigate. Guess what distro the server is?

**Comment by gipert** [comment]
Easy fix: solved by copying the `.spack-db` folder to a local filesystem (e.g. `~`) and symlinking it back to its original location. 

This should be somehow added to the docs, having a tiny disk quota in `~` is very common on HPC clusters. This forces the user to install spack elsewhere (frequently on exported filesystems).

Thanks!
