### ISSUE TITLE
Install hitch

### ISSUE THREAD

**Issue by kimjohn1** [LLNL/spack#21009]
I'm a new user and find that after installation, I have to execute the spack  setup script:

$ . spack/share/spack/setup-env.sh

every time I open a terminal to use spack.  Is there a way to make the setup script changes permanent (Linux Mint 20.04 OS)?

KimJohn

**Comment by adamjstewart** [comment]
Yes, you can add that line to your `~/.bashrc` and it will be sourced upon startup every time you open a new terminal.

**Comment by kimjohn1** [comment]
Adam,
Got it. Thanks!
Kim

**Comment by adamjstewart** [comment]
No problem, let me know if you have any other questions!
