### ISSUE TITLE
Enable spack install petsc +mkl_pardiso 

### ISSUE THREAD

**Issue by lpoirel** [LLNL/spack#21197]
spack installed petsc cannot use the mkl_pardiso solver

### Rationale

It would be awesome to be able to use mkl_pardiso from petsc, as installed by spack

### Description

As shown in https://gitlab.com/petsc/petsc/-/blob/master/config/examples/arch-ci-linux-intel-mkl-single.py, it should be possible to configure petsc to use mkl_pardiso

### General information

- [ ] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
@balay @BarrySmith @jedbrown are our `petsc` package maintainers, maybe they can add this feature. PRs are always welcome!

**Comment by lpoirel** [comment]
I'll be happy to help :-)
Should I simply add 
    '--with-mkl_pardiso-dir={path}'
    '--with-mkl_cpardiso-dir={path}'
path being the intel-mkl spec prefix, as suggested by the following link?  https://gitlab.com/petsc/petsc/-/blob/master/config/examples/arch-ci-linux-intel-mkl-single.py

**Comment by balay** [comment]
Thanks for checking on this.

yes - adding -`-with-mkl_pardiso-dir` should work. Also you might have to add the dependency on `intel-mkl`. [which I think should automatically conflict with any other blas/lapack - i.e openblas or netlib-lapack]

**Comment by adamjstewart** [comment]
I assume we'll want to make a variant for this. Spack's [Packaging Guide](https://spack.readthedocs.io/en/latest/packaging_guide.html) may be useful documentation if you are new to writing package recipes.
