### ISSUE TITLE
Installation issue: default Darwin packages.yaml apple-libuuid prefix causing issues

### ISSUE THREAD

**Issue by aphecetche** [LLNL/spack#21265]
# The Issue

While trying to compile `py-matplotlib` on a Big Sur Mac with Apple Clang, got a bunch of errors of the kind :

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cmath:646:17: error:
      no template named 'numeric_limits'
``` 

After some investigation, turns out the core of the problem is that the build environment has a CommandLineTool include path in SPACK_INCLUDE_DIRS (`/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include`) while the SDK in use is the Xcode one (`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk`)

```
~$ xcrun --show-sdk-path
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
~$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
``` 

```
~$ spack debug report
* **Spack:** 0.16.0-951-3893ce8f71
* **Python:** 3.8.2
* **Platform:** darwin-bigsur-skylake
* **Concretizer:** original
```

```
~$ clang --version
Apple clang version 12.0.0 (clang-1200.0.32.28)
Target: x86_64-apple-darwin20.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

# A (the?) solution

In Spack `etc/spack/defaults/darwin/packages.yaml` the `apple-libuuid` is specified as : 

```
apple-libuuid:
    buildable: false
    externals:
    # Apple bundles libuuid in libsystem_c version 1353.100.2,
    # although the version number used here isn't critical
    - spec: apple-libuuid@1353.100.2
      prefix: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr
```

Changing the `prefix` part to : 

```
      prefix: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
```

has solved the issue in my case.

**Comment by adamjstewart** [comment]
I'm no XCode expert, but I think your solution is the way to go. That directory exists on my system as well, so it's not specific to Big Sur. The only potential issue we may face is for users who have the XCode CommandLineTools installed but not the full XCode suite. Can you submit a PR to make your suggested change? This is a new feature anyway, so if it breaks things for anyone it's easy to fix.
