### ISSUE TITLE
intel-parallel-studio composer 2017 versions

### ISSUE THREAD

**Issue by MBlaschek** [LLNL/spack#21350]
I tried to installed intel-parallel-studio 2017.2, i followed the instructions from Documentation [Installing Intel tools within Spack (Route 2)](https://spack.readthedocs.io/en/latest/build_systems/intelpackage.html) 

License file is available and another version is allready running.
By the way edit the documentation: stub needs to be replaced with nothing see Issue [#19043](https://github.com/spack/spack/issues/19043)

`spack install intel-parallel-studio@composer.2017.2 -mpi %intel@17.0.2`

the download fails with intel 404.html. The same happens until version 2017.7
Version `intel-parallel-studio@composer.2017.7` works again.

### Steps to reproduce the issue
Added a new compiler into `compiler.yaml`
```
- compiler:
  | spec: intel@17.0.2
  | paths:
  | ¦ cc:
  | ¦ cxx:
  | ¦ f77:
  | ¦ fc:
  | target: x86_64
  | operating_sytem: rhel8
  | modules: []
  | environment: {}
  | extra_rpaths: []
```

```console
spack install intel-parallel-studio@composer.2017.2 -mpi %intel@17.0.2
```

### Error Message

```console
$ spack --debug --stacktrace install intel-parallel-studio@composer.2017.2 -mpi %intel@17.0.2
```
[debug.log](https://github.com/spack/spack/files/5881818/debug.log)

### Information on your system

* **Spack:** 0.16.0-959-258550e558
* **Python:** 3.6.8
* **Platform:** linux-rhel8-skylake_avx512 (however, intel 2017.2 would choose haswell)
* **Concretizer:** original

[compilers.yaml.txt](https://github.com/spack/spack/files/5881823/compilers.yaml.txt)

### Additional information
- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Fixed in #22248
