### ISSUE TITLE
spack install font-adobe-utopia-type1 dies in database.py

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#2139]
I'm working in a tree where I've been poking and prodding dependencies on mkfontdir and mkfontscale, so this could be my fault, but when I try to `spack install font-adobe-utopia-type1` it dies like so:

```
[hartzelg@spack-0 spack]$ spack reindex
[hartzelg@spack-0 spack]$ spack install font-adobe-utopia-type1
==> Installing font-adobe-utopia-type1
==> mkfontdir is already installed in /rss/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/mkfontdir-1.0.7-zcq774jm3vq4ockjac5ewmzksh2kt7mm
Traceback (most recent call last):
  File "/rss/spack/bin/spack", line 202, in <module>
    main()
  File "/rss/spack/bin/spack", line 179, in main
    return_val = command(parser, args)
  File "/rss/spack/lib/spack/spack/cmd/install.py", line 117, in install
    package.do_install(**kwargs)
  File "/rss/spack/lib/spack/spack/package.py", line 1183, in do_install
    dirty=dirty)
  File "/rss/spack/lib/spack/spack/package.py", line 1160, in do_install
    rec = spack.installed_db.get_record(self.spec)
  File "/rss/spack/lib/spack/spack/database.py", line 79, in converter
    return function(self, spec_like, *args, **kwargs)
  File "/rss/spack/lib/spack/spack/database.py", line 527, in get_record
    key = self._get_matching_spec_key(spec, **kwargs)
  File "/rss/spack/lib/spack/spack/database.py", line 519, in _get_matching_spec_key
    match = self.query_one(spec, **kwargs)
  File "/rss/spack/lib/spack/spack/database.py", line 653, in query_one
    assert len(concrete_specs) <= 1
AssertionError
[hartzelg@spack-0 spack]$
```

I'm not sure where to dig next.

**Comment by adamjstewart** [comment]
Duplicate of #2123.

**Comment by hartzell** [comment]
I followed the advice of @adamjstewart in #2123 and ended up removing 3 copies of mkfontdir (presumably I ended up with three as the result of me playing with dependencies in the mkfontdir and font-adobe-75dpi packages to get fonts to install).

Now all of the fonts I'm installing (including the above) install cleanly.

@tgamblin -- Should I leave this open as another example of #2123 or close it?

**Comment by adamjstewart** [comment]
Doesn't really matter. If you want you can close it and comment on the old issue. I was having problems recreating the issue, so if you know a reliable way to recreate it that would be very helpful.

**Comment by hartzell** [comment]
I think that my inner/pet chaos-monkey created the problem while I was poking around at the font build problem.  I don't seem to be able to recreate it (that's the problem with chaos monkeys...).

I'll close it and let people track #2123 rather than duplicate things.
