### ISSUE TITLE
Issues loading docbook-xml after install

### ISSUE THREAD

**Issue by skylerpaulus** [LLNL/spack#21396]
I am trying to install wayland with spack but it requires docbook-xsl and docbook-xml to be loaded in modules. Both xml and xsl have been installed with spack with the following commands, 

``$ spack install docbook-xml``
``$ spack install docbook-xsl``

When I try to load xml into my module I receive the following error
``$ module load docbook-xml-4.5-gcc-10.2.0-bs4kifb``
``-bash: eval: --: invalid option``
``eval: usage: eval [arg ...]``

### Steps to reproduce the issue
OS: Centos 7
Spack version: 0.15.4-1446-08e30a2

Modules loaded 
``  1) autotools   3) gnu8/8.3.0       5) ohpc                                 7) libxml2-2.9.10-gcc-10.2.0-4xuwlge            9) gcc-10.2.0-gcc-8.3.0-af6hrdh
  2) prun/1.3    4) openmpi3/3.1.4   6) graphviz-2.44.1-gcc-10.2.0-4hyoxfi   8) xorg-sgml-doctools-1.11-gcc-10.2.0-uzldscv  10) libxslt-1.1.33-gcc-10.2.0-fcpv73n``

``$ module load docbook-xml-4.5-gcc-10.2.0-bs4kifb``
``-bash: eval: --: invalid option``
``eval: usage: eval [arg ...]``

I receive the same error when I try to load docbook-xsl

### Error Message

``-bash: eval: --: invalid option``
``eval: usage: eval [arg ...]``

I tried to edit spacks modulefile for docbook-xml and xsl and found the issue to be in this command: 

``setenv --delim " " XML_CATALOG_FILES "/opt/ohpc/pub/spack/opt/spack/linux-centos7-sandybridge/gcc-10.2.0/docbook-xml-4.5-bs4kifbercjv2pz6pgvttwvto6qhw5ad/catalog.xml"``

If I remove --delim " " from the modulefile I no longer get the error when loading the modules however, wayland fails to install with the following error:

     ``151    checking for docbook stylesheets... no``
     ``152    configure: error: Documentation build requested but docbook-xsl stylesheets are not found. Install the docbook-xsl package or disable the documentation using --disable-documentation``

### Additional information

- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

Thank you for any help you can provide

**Comment by adamjstewart** [comment]
The separator logic was added by @trws way back in #2541, maybe he has some comments. @alalazo may be able to comment on the modules logic.

**Comment by trws** [comment]
Wow, long time ago. IIRC, XSL uses space separated environment variables, and needed to have at least two entries in some cases to support what I was doing, but that doesn't appear in the patch, and the logic looks wrong since both set rather than append, not sure where this falls WRT the module rework from around that time though, it might have been tested with TCL modules.

**Comment by xdelaruelle** [comment]
@adamjstewart  The `--delim` option is only accepted by path-related modulefile commands like [`append-path`](https://modules.readthedocs.io/en/latest/modulefile.html#mfcmd-append-path) or [`prepend-path`](https://modules.readthedocs.io/en/latest/modulefile.html#mfcmd-prepend-path) but [`setenv`](https://modules.readthedocs.io/en/latest/modulefile.html#mfcmd-setenv) does not have such option.

**Comment by skylerpaulus** [comment]
I tried switching setenv to append-path and prepend-path. Both options allow the module to load but it does not work properly. 
I tested this by attempting to install wayland which requires both docbook-xsl and doxbook-xml (both receiving the error reported previously). I get this error when installing: 
```configure: error: Documentation build requested but docbook-xsl stylesheets are not found. Install the docbook-xsl package or disable the documentation using --disable-documentation```

**Comment by adamjstewart** [comment]
@alalazo should we raise a warning/error when `env.set` is called with `separator`? Currently only `docbook-xml` and `lua` make this mistake.

**Comment by skylerpaulus** [comment]
docbook-xsl seems to be fixed when it comes to this error but docbook-xml is still giving the error. @adamjstewart

**Comment by skylerpaulus** [comment]
I attempted adding this to docbook-xsl 
```
prepend-path --delim " " XML_CATALOG_FILES "/opt/ohpc/pub/spack/opt/spack/linux-centos7-x86_64/gcc-9.2.0/docbook-xsl-1.79.2-xgedjij2v4dnjy47dbvgurvlyl2uuxpn/catalog.xml"
```

but I still recieve this error:
```
configure: error: Documentation build requested but docbook-xsl stylesheets are not found. Install the docbook-xsl package or disable the documentation using --disable-documentation
```

**Comment by xdelaruelle** [comment]
> @alalazo should we raise a warning/error when `env.set` is called with `separator`? Currently only `docbook-xml` and `lua` make this mistake.

@adamjstewart @alalazo Thanks to recent modifications on `lib/spack/spack/util/environment.py` (maybe 046416479a7de64e53ab8831f870cbe5e45a5aa5), an error is now obtained when a `separator` argument is set on `env.set`.

If one tries to edit for instance `docbook-xsl/package.py`
```patch
     def setup_run_environment(self, env):
         catalog = self.catalog
-        env.prepend_path("XML_CATALOG_FILES", catalog, separator=" ")
+        env.set("XML_CATALOG_FILES", catalog, separator=" ")
```

Following error is obtained when generating modulefile:
```
==> Warning: Could not write module file [.../linux-fedora38-skylake/docbook-xsl/1.79.2-gcc-13.1.1-kghoocv]
==> Warning: 	--> EnvironmentModifications.set() got an unexpected keyword argument 'separator' <--
```

I do not know if there are still some installation issue with this package, but at least things are fixed on the modules side. I would suggest to remove the `modules` label of this ticket.
