### ISSUE TITLE
Changes in behavior of spack install

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#2140]
@alalazo Can you take a look at this? There's a good chance one or both of these are related to #1186.

1. Previously, when I ran `spack install xyz`, if I pressed <kbd>v</kbd>, it would toggle back and forth to verbose mode. It no longer does this.
2. Previously, when an installation crashed, it would print out the contents of the `package.py` and point to where it crashed. Now it prints out both the `package.py` and the method that calls it. The latter is quite long, and requires the user to scroll up pretty far to find the `spack-build.out`. I don't think we need the latter.

**Comment by alalazo** [comment]
I'll try to have a look as soon as possible. I think they ARE both due to #1186 and the way the forked processes are handled.

**Comment by adamjstewart** [comment]
Take your time, no rush.

**Comment by alalazo** [comment]
Can you check if #2143 solves point 2. ?

**Comment by alalazo** [comment]
I am near to a solution for point 1, but need to sort out a couple of details. Basically I need to forward :
```
input_stream = os.fdopen(os.dup(sys.stdin.fileno()))
```
down to child processes. 

@tgamblin @adamjstewart How urgent do you consider this regression ?

**Comment by adamjstewart** [comment]
Not urgent at all. It's a cool feature, but certainly not a show stopper. Doesn't need to make it into 0.10 as far as I'm concerned.

**Comment by tgamblin** [comment]
Does #2187 fix (2)?  Or is that something different?

**Comment by alalazo** [comment]
@tgamblin Sorry, I meant #2158

**Comment by alalazo** [comment]
Ok I was talking about 1. Sorry for the noise.

**Comment by tgamblin** [comment]
No worries.  Also, (2) happens because previously we just let the child print the stacktrace, and now the parent needs to do it.  I think #2187 should fix it

**Comment by alalazo** [comment]
I think #2187 will cover the case of typos in packages (I didn't test them in #2143). The problem with `SpackError` was pickle serialization when sent cross threads (thus the `__reduce__` methos).
