### ISSUE TITLE
py-petsc4py fails on all systems, all arch

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#21451]
`py-petsc4py@3.14.0` build fails using `spack@develop` (7dcf3f7aedbfdf085451f8fffb2ecdfb08c96c7d from `Tue Feb 2 11:11:51 2021 -0800`)
* `Ubuntu 18.04` w/ `gcc@7.5.0`
* `Ubuntu 20.04` w/ `gcc@9.3.0`
* `RHEL 7` w/ `gcc@8.1.0`
* `RHEL 8` w/ `gcc@8.3.1`

Concrete spec: [py-petsc4py-endo3v.spec.yaml.txt](https://github.com/spack/spack/files/5914488/py-petsc4py-endo3v.spec.yaml.txt)
Full build log: [py-petsc4py-build-out.txt](https://github.com/spack/spack/files/5914490/py-petsc4py-build-out.txt)
Concretize output: [py-petsc4py-dag.txt](https://github.com/spack/spack/files/5914497/py-petsc4py-dag.txt)

```
$> spack install -f ./py-petsc4py-endo3v.spec.yml
...
==> Installing py-petsc4py-3.14.0-endo3vxvolun3ajpssfvyqgypqzkrh43
==> Using cached archive: /opt/spack/var/spack/cache/_source-cache/archive/33/33ac9fb55a541e4c1deabd6e2144da96d5ae70e70c830a55de558000cf3f0ec5.tar.gz
==> py-petsc4py: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 1:
    '/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/python-3.8.6-4aev2ilejphuclznv7zazjxohanwz46i/bin/python3.8' '-s' 'setup.py' '--no-user-cfg' 'build'

2 errors found in build log:
     42    src/petsc4py.PETSc.c:326298:30: note: variable tracking size limit exceeded with '-fvar-tracking-assignments', retrying without
     43    326298 | static CYTHON_SMALL_CODE int __pyx_pymod_exec_PETSc(PyObject *__pyx_pyinit_module)
     44           |                              ^~~~~~~~~~~~~~~~~~~~~~
     45    /opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/mpich-3.3.2-knmzscajrauwght5atlc2vevwjzwn2ke/bin/mpicc -pthread -fPIC -fPIC -Wno-unused-result -Wsign-compare
           -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/zlib-1.2.11-p7dmb5pqi6svirhovljrkp3uyfiytz3m/include -I/opt/spack/opt/sp
           ack/linux-ubuntu20.04-x86_64/gcc-9.3.0/metis-5.1.0-lxkd2thzi5xc5z3aqvw4eodot57r53y5/include -I/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/parmetis-4.0.3-7
           b3zkab7n54xkxkba2etquagx46mr6ze/include -I/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/hdf5-1.10.7-t4jqnkp2mejfioelbtantmf7t2vdnoup/include -I/opt/spack/op
           t/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/superlu-dist-6.4.0-qn52fuce45s64duiwjrv3n5nugai6f2p/include -I/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/hypre
           -2.20.0-celzcb34v2s6hppgktqyrdpubyp4rk5g/include -I/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/petsc-3.14.1-wakbzwrwms2g3xcyc643cnof4s4lf23r/include -Isrc
           /include -I/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/py-numpy-1.20.0-q5r54n5m4zhq6ujwxaaqqlm2hovb54lv/lib/python3.8/site-packages/numpy/core/include -I/
           opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/python-3.8.6-4aev2ilejphuclznv7zazjxohanwz46i/include/python3.8 -c src/libpetsc4py.c -o build/temp.linux-x86_64
           -3.8/src/libpetsc4py.o
     46    /opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/mpich-3.3.2-knmzscajrauwght5atlc2vevwjzwn2ke/bin/mpicc -pthread -fPIC /opt/spack/lib/spack/env/gcc/gcc -shared
            -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -L/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/bzip2-1.0.8-5m22qwv5akdogbbq3qbuhilvi
           ppzqeli/lib -L/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/expat-2.2.10-r4dctmf674e37q4jc2pvphiy5ik4riz3/lib -L/opt/spack/opt/spack/linux-ubuntu20.04-x86_6
           4/gcc-9.3.0/gdbm-1.18.1-iowiob4u4kujr6pyhbolir3nokuqylwh/lib -L/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/gettext-0.21-yt6n2phbjvscurpwbkm2gfx52rsd4rkm/l
           ib -L/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/libffi-3.3-hvrhttuiahh5krx6w4oskf3mryadojct/lib -L/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0
           /ncurses-6.2-pzjdrlluvcj4s6ah6lxbd77vok3eoeaz/lib -L/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/openssl-1.1.1i-6peexc2wtn22oxuevnyhrimerrpmqxeh/lib -L/opt
           /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/readline-8.0-do42wztg5acct7tiuewpgnvgktwrkudh/lib -L/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/sqlite
           -3.33.0-2vrxq4lf2wh2qac4v2ngc2eqbna47oej/lib -L/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/util-linux-uuid-2.36-qm5gupet6fiuoat4m2rnlusdwb5xiot7/lib -L/op
           t/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/xz-5.2.5-kamfyq4jqy3je7qoimrp2tgs6gqswzcf/lib -L/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/zlib-1.2.
           11-p7dmb5pqi6svirhovljrkp3uyfiytz3m/lib build/temp.linux-x86_64-3.8/src/PETSc.o build/temp.linux-x86_64-3.8/src/libpetsc4py.o -L/opt/spack/opt/spack/linux-ubuntu20.04
           -x86_64/gcc-9.3.0/petsc-3.14.1-wakbzwrwms2g3xcyc643cnof4s4lf23r/lib -L/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/python-3.8.6-4aev2ilejphuclznv7zazjxohan
           wz46i/lib -Wl,--enable-new-dtags,-R/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/petsc-3.14.1-wakbzwrwms2g3xcyc643cnof4s4lf23r/lib -Wl,--enable-new-dtags,-R
           /opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/python-3.8.6-4aev2ilejphuclznv7zazjxohanwz46i/lib -lpetsc -o build/lib.linux-x86_64-3.8/petsc4py/lib/PETSc.cpy
           thon-38-x86_64-linux-gnu.so
     47    /opt/spack/lib/spack/env/gcc/gcc: file not recognized: file format not recognized
  >> 48    collect2: error: ld returned 1 exit status
  >> 49    error: command '/opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/mpich-3.3.2-knmzscajrauwght5atlc2vevwjzwn2ke/bin/mpicc' failed with exit status 1
```

This breakage happened fairly recently (~ last month). I will try a bisect to see when this broke.

@balay @adamjstewart

**Comment by adamjstewart** [comment]
@dalcinl is also listed as a maintainer for `py-petsc4py`, and @BarrySmith and @jedbrown are also listed as maintainers for `petsc`, maybe one of them can help.

**Comment by balay** [comment]
>   46    /opt/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.3.0/mpich-3.3.2-knmzscajrauwght5atlc2vevwjzwn2ke/bin/mpicc -pthread -fPIC /opt/spack/lib/spack/env/gcc/gcc -shared

>    47    /opt/spack/lib/spack/env/gcc/gcc: file not recognized: file format not recognized

I see this error. somehow `/opt/spack/lib/spack/env/gcc/gcc` is listed on the link line?

Looks like this issue is getting masked by spack issue in my CI setup - where `spack install xsdk` is not returning an error code on this failure :(

https://gitlab.com/xsdk-project/spack-xsdk/-/jobs/1010107849

**Comment by balay** [comment]
I've switched over to `spack install --fail-fast` for now..

**Comment by balay** [comment]
`git bisect` says - the change in behavior is triggered by 3cc5b7adc7d2167646d6a049d64c710d98e1d6f0 - and the build completes if this commit is reverted (with latest develop)

**Comment by eugeneswalker** [comment]
> `git bisect` says - the change in behavior is triggered by [3cc5b7a](https://github.com/spack/spack/commit/3cc5b7adc7d2167646d6a049d64c710d98e1d6f0) - and the build completes if this commit is reverted (with latest develop)

Ahh thank you! beat me to it.

**Comment by eugeneswalker** [comment]
> `git bisect` says - the change in behavior is triggered by [3cc5b7a](https://github.com/spack/spack/commit/3cc5b7adc7d2167646d6a049d64c710d98e1d6f0) - and the build completes if this commit is reverted (with latest develop)

@skosukhin

**Comment by balay** [comment]
Adding debug print - I see the following env variable is set by the above change
```
LDSHARED = /home/balay/spack/lib/spack/env/gcc/gcc -shared -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now  -g  -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now  -g
```
And checking petsc4py - I see:
```
$ git grep LDSHARED
conf/baseconf.py:        if self['BUILDSHAREDLIB'] != 'yes':
conf/baseconf.py:            'LDFLAGS', 'LDSHARED', 'SO')
conf/baseconf.py:        ldshared = getenv('LDSHARED', ldshared)
demo/wrap-f2py/makefile:        LDSHARED="${FC_LINKER}" \
demo/wrap-swig/makefile:        CC=${CC} F90=${FC} LDSHARED='${CLINKER} -shared' \
```
So perhaps petsc4py is expecting LDSHARED to be set in a different way.? @dalcinl - could check  this?

**Comment by dalcinl** [comment]
@balay Looking at that petsc4py code I wrote ages ago, looks like it naively assumes `LDSHARED` starts with `CC`.
petsc4py has to deal with many scenarios, like PETSc being built with a MPI compiler wrapper, and that compiler wrapper being different than the compiler used to build Python. And now spack seems to be playing games with these definitions of these compiler vars on my back, changing what is usually the default in a Python installation. No surprises things do not longer work.

The quickest way to workaround the issue would be to patch petsc4py this way:

```diff
diff --git a/src/binding/petsc4py/conf/baseconf.py b/src/binding/petsc4py/conf/baseconf.py
index 8a2466a5bd..73c08b923a 100644
--- a/src/binding/petsc4py/conf/baseconf.py
+++ b/src/binding/petsc4py/conf/baseconf.py
@@ -211,7 +211,7 @@ class PetscConfig:
         ldshared = getenv('LDSHARED', ldshared)
         ldflags = getenv('LDFLAGS', cflags + ' ' + (ldflags or ''))
         ldcmd = split_quoted(ld) + split_quoted(ldflags)
-        ldshared = [flg for flg in split_quoted(ldshared) if flg not in ldcmd]
+        ldshared = [flg for flg in split_quoted(ldshared)[-1] if flg not in ldcmd]
         ldshared = str.join(' ', ldshared)
         #
         def get_flags(cmd):
```

Please note that after that fix, petsc4py will continue to link with whatever PETSc links, and not with the compiler specified in `LDSHARED`. Perhaps a better course of action for spack is to just look for `def configure_compiler(...):` in petsc4py's `baseconf.py` and insert a `return` in the first line, and let the Python configuration alone, but then handle yourself potential any issues coming from petsc4py not using the same compiler and linker command as PETSc.

**Comment by balay** [comment]
@dalcinl thanks for the fix. However - now I get:
```
/home/petsc/soft/mpich-3.3b1/bin/mpicc -pthread - g -Wno-unused-result ....
gcc: error: g: No such file or directory
````

Perhaps you want to skip `/home/balay/spack/lib/spack/env/gcc/gcc` from `/home/balay/spack/lib/spack/env/gcc/gcc -shared -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now  -g  -Wl,-z,relro -Wl,--as-needed  -Wl,-z,now  -g` ? How about:
```
+        ldshared = [flg for flg in split_quoted(ldshared) if flg not in ldcmd and (flg.find('/lib/spack/env')<0)]                                                              
```
We could have this as a spack-only patch - so that the other use-cases are not changed.

Edit: even if added upstream - I think it should only affect spack install

**Comment by dalcinl** [comment]
@balay Oh sorry, I my patch above is nonsense, it should actually be:

```diff
-        ldshared = [flg for flg in split_quoted(ldshared) if flg not in ldcmd]
+        ldshared = [flg for flg in split_quoted(ldshared)[1:] if flg not in ldcmd]
```

**Comment by balay** [comment]
@dalcinl thanks! Should we use my patch - as it won't change the behavior in regular release - so can add to upstream [for future releases]?

Or use your patch - and make it spack-only?

**Comment by dalcinl** [comment]
For now, I would suggest to make any patch that works spack-only.

A general solution has to be though more carefully, imagine something like:

```
LDSHARED="/usr/bin/env PATH=/dir/foo:/dir/bar my-super-special-ld-wrapper ..."
```

**Comment by alalazo** [comment]
This one regressed in #45189 due to a change in the path where the Spack wrapper lives.

**Comment by alalazo** [comment]
So, I'm trying to fix the regression, but it's hard to even understand where the sources of `py-petsc4py` live. This homepage:
```
homepage = "https://gitlab.com/petsc/petsc4py"
```
seems really outdated, and I guess sources moved into the petsc repository?

**Comment by alalazo** [comment]
Ok, I think the fix is here:

https://github.com/petsc/petsc/blob/3ba50cbb8987b4dbba70a5df1428185ecadddcf3/src/binding/petsc4py/conf/confpetsc.py#L353

This will break each time the path to the wrapper changes in a way that is not matched by the `find` expression.

**Comment by alalazo** [comment]
For now I solved with this commit https://github.com/spack/spack/pull/45189/commits/f04b6d31a6c328ad7aadd5a1298377118a037b65 but a more robust solution upstream is welcome
