### ISSUE TITLE
Installation issue: py-numpy

### ISSUE THREAD

**Issue by ikitayama** [LLNL/spack#21482]
```console
$ spack install py-numpy

4.3.1/py-cython-0.29.21-ewd7xu2xdndjpby76rntlqelig2bx23k
==> Installing py-numpy-1.20.0-rv5miloycltswjxmrybjhknknb5yzwvy
==> No binary for py-numpy-1.20.0-rv5miloycltswjxmrybjhknknb5yzwvy found: installing from source
==> Using cached archive: /vol0004/hp200139/data/u00444/projects/spack/var/spack/cache/_source-cache/archive/3d/3d8233c03f116d068d5365fed4477f2947c7229582dad81e5953088989294cec.zip
1 out of 1 hunk FAILED -- saving rejects to file numpy/distutils/fcompiler/__init__.py.rej
==> Patch /vol0004/hp200139/data/u00444/projects/spack/var/spack/repos/builtin/packages/py-numpy/add_fj_compiler.patch failed.
==> Error: ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/vol0004/hp200139/data/u00444/projects/spack/var/spack/repos/builtin/packages/py-numpy/add_fj_compiler.patch' '-d' '.'...
```

### Additional information

* [spack-build-out.txt]()
* [spack-build-env.txt]()

### General information

- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [ ] I have searched the issues of this repo and believe this is not a duplicate

**Comment by ikitayama** [comment]
@adamjstewart , this is observed with Fujitsu compiler 4.3.1. Patch did not apply cleanly

**Comment by adamjstewart** [comment]
I believe your team wrote this patch. Was it ever submitted upstream? If not someone will need to update the patch for the latest version.
