### ISSUE TITLE
py-matplotlib: multiple backend support

### ISSUE THREAD

**Issue by lrtfm** [LLNL/spack#21511]
Can the `matplotlib` support multiple backends? 

```
[spack]$ spack install py-matplotlib backend=agg,tkagg
==> Error: multiple values are not allowed for variant "backend"
```

**Comment by adamjstewart** [comment]
Hi @lrtfm, I wrote most of this package recipe. The `backend` variant is only which backend to enable by default, all backends will still be installed and functional as long as their dependencies are found at run-time. We could add another variant to control which backend deps are installed that allows multiple, but I don't think that's necessary. What do you think?

**Comment by lrtfm** [comment]
@adamjstewart, thanks, I got it.  If this is the case, adding more explanation for this option would be better, I think.

**Comment by adamjstewart** [comment]
Where would you document that? In the spack info message? Or in the package?

**Comment by lrtfm** [comment]
In the space info message. Is this ok?
