### ISSUE TITLE
[spack scripting] Unable to import spack depending on having other imports

### ISSUE THREAD

**Issue by vsoch** [LLNL/spack#21547]
This is an interesting bug - I was working on spack scripting, and ran into a case where (using the spack hashbang) it told me that it was not able to find spack. This might be hard to reproduce because I got it to work once, and then it never worked again.

## 1. Setup Environment

I first add my spack bin to the path, and also source the environment setup script (although I'm not sure this is needed)

```bash
$ export PATH=$PATH:$PWD/bin
$ . share/spack/setup-env.sh 
```

I created a basic script (below is `test_script.py`).

```python
#!/usr/bin/env spack-python

from spack.spec import Spec
print(spack.repo)
print("This is successful!")
```
This worked once, but when I came back to it later, it did not.
```bash
$ ./test_script.py
```
```
$ python test_script.py 
Traceback (most recent call last):
  File "test_script.py", line 3, in <module>
    from spack.spec import Spec
ModuleNotFoundError: No module named 'spack'
```
It works totally fine with spack python
```bash
$ spack python test_script.py 
<module 'spack.repo' from '/home/vanessa/Desktop/Code/spack/lib/spack/spack/repo.py'>
This is successful!
```
or the ipython interpreter

```bash
$ spack python -i ipython test_script.py 
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
~/Desktop/Code/spack/test_script.py in <module>
      2 
      3 from spack.spec import Spec
----> 4 print(spack.repo)
      5 print("This is successful!")

NameError: name 'spack' is not defined
```

It worked just once for me, and now I'm not able to reproduce that. Let me know if you want me to try something different! I'm on Ubuntu 20.04, spack develop branch.

---------------
### Update
This is what I need to do to make it successful - add the paths for spack and then the other libraries.

```python
#!/usr/bin/env spack-python

import sys
import os

here = os.path.dirname(os.path.abspath(__file__))
spack_path = os.path.join(here, "lib", "spack")
sys.path.insert(0, spack_path)
spack_libs = os.path.join(spack_path, "external")
sys.path.insert(0, spack_libs)

import spack

from spack.spec import Spec
print(spack.repo)
print("This is successful!")
```
```bash
$ ./test_script.py 
<module 'spack.repo' from '/home/vanessa/Desktop/Code/spack/lib/spack/spack/repo.py'>
This is successful!
```
But my impression is that, given that we use the hashbang, it should work without these extra imports. I also tried the other hasbang (spack python) which isn't supposed to work on Linux - it took me to the same result.

**Comment by vsoch** [comment]
Ah, so when I just import spack, it seems to work:

```python
#!/usr/bin/env spack-python

import spack
from spack.spec import Spec
print(spack.repo)
print("This is successful!")
```
```bash
$ ./test_script.py 
<module 'spack.repo' from '/home/vanessa/Desktop/Code/spack/lib/spack/spack/repo.py'>
This is successful!
```
I guess I expected it to be there without needing to import because of this line: https://github.com/spack/spack/blob/develop/lib/spack/spack/cmd/python.py#L97. But at least it seems to find the module this time! And apologies for all my small oversights, still rather green with spack :)

**Comment by alalazo** [comment]
`spack.repo` was never imported in the scripts above :slightly_smiling_face:

**Comment by vsoch** [comment]
But that's kind of the issue? The statement about it being successful works when I haven't imported it... 

But whatever, this is over 2 years old I don't care anymore. :laughing:

**Comment by alalazo** [comment]
If you don't import the module explicitly my understanding is that the behavior is undefined, and depends on the implementation of the import system and on the imports of the modules you imported explicitly.
