### ISSUE TITLE
Not including the architecture in the hashing causes hash collision on Arch

### ISSUE THREAD

**Issue by krafczyk** [LLNL/spack#2155]
Just for fun, I tried to install an older version of gcc on my Arch machine. I was greated with the following error message:

```
spack install gcc@5.4.0
==> Installing gcc
==> Error: Specs gmp@6.1.1%gcc@6.2.1 arch=linux--x86_64^libsigsegv@2.10%gcc@6.2.1 arch=linux--x86_64^m4@1.4.17%gcc@6.2.1+sigsegv arch=linux--x86_64 and gmp@6.1.1%gcc@6.2.1 arch=linux-None-x86_64 have the same SHA-1 prefix!
```

I suspect this is really happening because spack isn't detecting my architecture or OS correctly, but however it happened, you can see that both packages different arch properties. The manual leads me to believe that this should cause their hashes to differ, but apparently not.

**Comment by tgamblin** [comment]
This should be fixed by #2261.  Can you verify and reopen if not?

**Comment by krafczyk** [comment]
@tgamblin: I'd like to verify that it's fixed, however I deleted the offending spack installation as soon as #2157 was merged which fixed the underlying problem causing spack to assign me two architectures depending on context. This is because I couldn't get anything done with spack otherwise.

**Comment by tgamblin** [comment]
@krafczyk: I'm reasonably sure that it's fixed, based on the error I'm seeing in your `spec` string above.  So we'll leave it closed -- feel free to file another if it reoccurs.
