### ISSUE TITLE
p4est fails to configure with external Openmpi

### ISSUE THREAD

**Issue by ashkan2200** [LLNL/spack#2160]
Hi,
I am installing `p4est` with spack on `redhat`. However, the configuration phase fails with this log

    ==> './configure' '--prefix=/pica/h1/alid/spack/opt/spack/linux-redhat6-x86_64/gcc-6.2.0/p4est-1.1-433ez53cipndb6fqajpvyok5poaqkzqm' '--enable-mpi' '--enable-shared' '--disable-vtk-binary' '--without-blas' 'CPPFLAGS=-DSC_LOG_PRIORITY=SC_LP_ESSENTIAL' 'CFLAGS=-O2' 'CC=/opt/openmpi/2.0.1gcc6.2.0/bin/mpicc' 'CXX=/opt/openmpi/2.0.1gcc6.2.0/bin/mpic++' 'FC=/opt/openmpi/2.0.1gcc6.2.0/bin/mpif90' 'F77=/opt/openmpi/2.0.1gcc6.2.0/bin/mpif77'
    checking for a BSD-compatible install... /usr/bin/install -c
    checking whether build environment is sane... yes 
    checking for a thread-safe mkdir -p... /bin/mkdir -p
    checking for gawk... gawk
    checking whether make sets $(MAKE)... yes 
    checking whether make supports nested variables... yes 
    checking whether make supports nested variables... (cached) yes 
    checking for a sed that does not truncate output... /bin/sed
    checking Major version... 1
    checking Minor version... 1
    checking Point version... 1.1 
    o---------------------------------------
    | Checking options
    o---------------------------------------
    o---------------------------------------
    | Checking MPI and related programs
    o---------------------------------------
    checking whether we are using MPI... yes 
    checking whether we are using MPI I/O... yes 
    checking whether we are using MPI_Init_thread... yes 
    checking for mpiexec... mpiexec
    configure:                             F77 set to /opt/openmpi/2.0.1gcc6.2.0/bin/mpif77
    configure:                              FC set to /opt/openmpi/2.0.1gcc6.2.0/bin/mpif90
    configure:                              CC set to /opt/openmpi/2.0.1gcc6.2.0/bin/mpicc
    configure:                             CXX set to /opt/openmpi/2.0.1gcc6.2.0/bin/mpic++
    checking whether the Fortran 77 compiler works... yes 
    checking for Fortran 77 compiler default output file name... a.out
    checking for suffix of executables... 
    checking whether we are cross compiling... configure: error: in `/home/alid/spack/var/spack/stage/p4est-1.1-433ez53cipndb6fqajpvyok5poaqkzqm/p4est-1.1':
    configure: error: cannot run Fortran 77 compiled programs.
    If you meant to cross compile, use `--host'.
    See `config.log' for more details

If I run the same configuration directly in the staged folder it doesn't fail.

Has anyone encountered this issue before?

**Comment by alalazo** [comment]
It seems you are using an external OpenMPI (not compiled with spack). The best guesses I can make with the information here are that: 
- you are not using spack compiler wrappers underneath or
- some library was not rpath-ed in a dependency

If this is the case then you rely on `LD_LIBRARY_PATH` to run things and this variable is pruned for good reasons during `spack` build. It may work if you do : 
```
spack install --dirty <other-options>
```
If the previous command works consider tracking where libraries were not rpath-ed and correct there, as this **is not the recommended way of doing things**.

**Comment by davydden** [comment]
> configure: error: cannot run Fortran 77 compiled programs.

i would also dig into the `configure.log` to se why it can't run F77 programs. Most likely your `mpi` installation, as pointed out by @alalazo, does not have dependencies RPATH'ed and to run compiled programs requires `LD_LIBRARY_PATH` to be set. Keep an eye on this PR https://github.com/LLNL/spack/pull/943 which is planed to be merged before `v.0.1.0` release soon. If you have modules to load openmpi, then this https://github.com/LLNL/spack/issues/2056 is also relevant to you.

**Comment by ashkan2200** [comment]
Maybe I should have mentioned that I use a preinstalled openmpi and cmake. I tried with the `--dirty` option and it worked. Thanks.

Then my question is that this probably will happen with other pre-installed libraries that are mentioned in `package.yaml` should I just use --dirty for all of them?

**Comment by alalazo** [comment]
If I were you I would rebuild everything I could with spack, and leave in `packages.yaml` only third-party software or software that for some reason cannot be built in the same way within spack (and that's definitely not the case for `cmake` or `openmpi`)

Using external packages you are actually taking yourself part of the responsibility in ensuring that everything is built consistently.

**Comment by pramodk** [comment]
@alalazo : for external packages I am using `modules` in `packages.yaml` to avoid use of `--dirty`. But  as per the discussion in #2056, seems like there is a bug.

**Comment by citibeth** [comment]
Yes, you need "dirty" for this kind of thing.  Otherwise, the build won't be able to find the stuff you so carefully set up in your path when you launched Spack.

**Comment by citibeth** [comment]
> If I were you I would rebuild everything I could with spack, and leave in packages.yaml only third-party software or software that for some reason cannot be built in the same way within spack (and that's definitely not the case for cmake or openmpi).

I agree with this advice.  Certainly no reason to build your own CMake.  But it can be necessary to use an external MPI, on supercomputers with specialized hardware where you just don't know how to properly build MPI to use their stuff.  Or of course if you need to use, say, Intel MPI that came with the computer.
