### ISSUE TITLE
Spack adds duplicates of compilers

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#2164]
So, I have a `~/.spack/compilers.yaml` file from back in the good ol' days when Spack added new compilers there. Then, we added a second level of configurability and set that to be the default. Now when I run `spack compiler find`, it adds new compilers to `~/.spack/linux/compilers.yaml`. Fine. But the problem is that it adds compilers that it already knows about. Now I have multiple copies of the same compiler:

```
$ spack compilers
==> Available compilers
-- nag ----------------------------------------------------------
nag@6.1

-- gcc ----------------------------------------------------------
gcc@6.1.0  gcc@6.1.0  gcc@5.3.0  gcc@4.4.7  gcc@4.4.7

-- intel --------------------------------------------------------
intel@17.0.0  intel@17.0.0  intel@16.0.3  intel@15.0.0

-- pgi ----------------------------------------------------------
pgi@16.5-0  pgi@16.3-0
```

When I run most commands, I get errors like:

```
==> Error: Multiple compilers satisfy spec gcc@6.1.0
```

For the time being, I guess I'm going to just move `~/.spack/compilers.yaml` to `~/.spack/linux/compilers.yaml`, but we should probably patch this bug. Note that this is the same problem that causes #2042, so we can fix both at once.

**Comment by adamjstewart** [comment]
Also, `spack config edit compilers` still opens `~/.spack/compilers.yaml`. We should at least be consistent here.

**Comment by pramodk** [comment]
>For the time being, I guess I'm going to just move ~/.spack/compilers.yaml to ~/.spack/linux/compilers.yaml

I came across this and did the same.

**Comment by adamjstewart** [comment]
Can we get this fixed? It is tripping up a lot of users (#2932 and #2985).

There are two problems here:

1. `spack compiler find` automatically puts things in `~/.spack/linux/compilers.yaml` while `spack config edit compilers` opens up `~/.spack/compilers.yaml`. The default scope for these commands should be consistent.

2. If a compiler is in `~/.spack/compilers.yaml`, `spack compiler find` will add a duplicate in `~/.spack/linux/compilers.yaml`. This results in duplicates in `spack compiler list` and makes it impossible to concretize anything with that compiler.

**Comment by scheibelp** [comment]
I can take a look at this. Hopefully I'll have a PR in the works by Friday.

**Comment by scheibelp** [comment]
Resolved by https://github.com/LLNL/spack/pull/2999 (which also includes an updated error message to point you to files where there are duplicates in case a user manually updates multiple files)

Please reopen if you see this again.
