### ISSUE TITLE
Installation issue: octave

### ISSUE THREAD

**Issue by antiskid56** [LLNL/spack#21650]
When building octave 6.1.0 with fltk support, there is no build error, but the resulting build does not use fltk.

### Steps to reproduce the issue

```console
$ spack install octave@6.1.0  +fftw  +fontconfig +freetype +gnuplot +curl +fltk
...
```
Lack of fltk functionality can be verified by running the octave-6.1.0 binary, and checking the value of available_graphics_toolkits(). It will be found that only the gnuplot toolkit is available, i.e. the fltk support was not linked into the binary.

### Information on your system

* **Spack:** 0.16.0-1262-0724467ad2
* **Python:** 3.8.5
* **Platform:** linux-ubuntu20.04-skylake
* **Concretizer:** original

### Additional information

<https://octave.1599824.n4.nabble.com/Octave-3-4-2-with-fltk-support-td3627783.html> indicates that mesa support must be available at link time in order for fltk support to be functional. Probably mesa should be added as a dependency for fltk.

- [ x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
@mtmiller

**Comment by mtmiller** [comment]
Do you happen to have a full build log that we can look at to see what configure worked out?

My guess is that the spack fltk package doesn't pull in opengl, which octave does require.

**Comment by antiskid56** [comment]
I'm a new spack user. I see scant mention of build logs in the documentation. Some indication that there might be one in /tmp, but I've rebooted since I built.

I'm happy to rebuild, and generate a log. Can you tell me where to look for it?

**Comment by mtmiller** [comment]
I don't know much about spack myself, @adamjstewart can you help get a full configure/build log?

**Comment by adamjstewart** [comment]
If the build fails, Spack will print the location of the build log. If the build succeeds, Spack will print the installation directory. This can also be found with `spack find -p`. In the installation directory, there is a `.spack` directory containing the build log, config.log, build environment, and other useful files.

**Comment by antiskid56** [comment]
Thanks. Build log attached, along with packages.yaml from ~/.spack. Please ignore previously uploaded files in this message; they didn't have the correct build configuration for the problem I'm trying to demonstrate.

[spack-build-out.txt](https://github.com/spack/spack/files/6024731/spack-build-out.txt)
[packages.yaml.zip](https://github.com/spack/spack/files/6024732/packages.yaml.zip)

The top of the build log indicates that octave is being built with fltk support, but without opengl. So I think @mtmiller is correct in his diagnosis.

I experimented with forcing spack to use a system-supplied version of fltk, but octave still doesn't pull in the opengl libraries (although they are also installed on the system).

I don't know whether the fltk package should require opengl, or whether the octave package should provide another option to pull in opengl.

**Comment by mtmiller** [comment]
Yes, I think `+fltk` should implicitly add the `+opengl` flag as well, as it seems to be doing for `+qt`.

**Comment by cessenat** [comment]
I'm soon to update octave so that +fltk automatically induces +opengl ; at the same time I would like to add +qscintilla but for this I first made a PR for compilation bugs correction. I checked this leads to available_graphics_toolkits() reports
fltk, gnuplot, qt.
Is that well what you hope @antiskid56 ?

**Comment by antiskid56** [comment]
Thanks for asking @cessenat.

My scenario is the use of recent releases of octave both locally and remotely. I would like to be able to use it remotely using x2go, which has limited opengl capabilities.

My experience thus far is that the full QT gui doesn't work well with x2go, but that fltk plotting works fine. fltk plotting is basically an alternative to qt plotting, so my preference would be that fltk does _not_ pull in qt, unless qt is specifically requested in the build. The scenario I would like to have working, is asking for fltk, and getting fltk, and with it opengl, without necessarily requiring qt.

However, I suppose octave-cli might be a reasonable way to get what I want at run-time, even if fltk does pull in qt at build-time.

It is understood that fltk is going to be deprecated at some point. But so is X for that matter. Nothing lasts forever, but this is a good working setup for me that will work into the indefinite future.

**Comment by cessenat** [comment]
This exceeds my knowledge ; I did
$ spack install octave+fltk
[from my soon to come PR #21903]
and this provides octave --gui with [fltk,gnuplot,qt].
There is no spec dependency on qt, so I don't know where the magic is.
I will tell you when octave is updated so that you can try and tell me if it is satisfying for you.

**Comment by antiskid56** [comment]
I will be happy to try it. Wouldn't the spec dependency on qt come from qscintilla?

**Comment by antiskid56** [comment]
I haven't seen the patch merged yet. I did give it a look, and it appears to meet the intent of what I was asking for. qtscintilla is just another option that would be supported by the patch, but would not necessarily be required for fltk support.
