### ISSUE TITLE
numactl - installation issue 

### ISSUE THREAD

**Issue by amd-toolchain-support** [LLNL/spack#21665]
Hello,

I am trying to install numactl using spack on Cent OS 8. Latest available version and sha256 are 2.0.14 and "1ee27abd07ff6ba140aaf9bc6379b37825e54496e01d6f7343330cf1a4487035". With this, I am getting below error.
 >> 118    /tmp/spack/spack-stage/spack-stage-numactl-2.0.14-jurtvonp6cbygc32l5avg5ydkqbkod7z/spack-src/configure: line 12682: syntax error near unexpecte
            d token `fi'

I am able to compile if I modify configure file and numactl community 2.0.14 is  also working fine. 

If I fetch checksum of numactl ($spack checksum numactl) and use 2.0.14 version's sha256 i.e "version('2.0.14', sha256='826bd148c1b6231e1284e42a4db510207747484b112aee25ed6b1078756bcff6')", then I am getting below error. 

==> Error: ChecksumError: sha256 checksum failed for /tmp/spack/spack-stage/spack-stage-numactl-2.0.14-jurtvonp6cbygc32l5avg5ydkqbkod7z/v2.0.14.tar.gz
    Expected 826bd148c1b6231e1284e42a4db510207747484b112aee25ed6b1078756bcff6 but got 1ee27abd07ff6ba140aaf9bc6379b37825e54496e01d6f7343330cf1a4487035

Please suggest how to proceed with this error? 

Thanks

**Comment by haampie** [comment]
Can't replicate this with a centos 8 docker image.

numactl uploads their own tar.gz file under releases (which includes the generated configure script), spack checksum might download the github tar.gz (without configure script)? https://github.com/numactl/numactl/releases/tag/v2.0.14 the top link has the correct checksum.

**Comment by amd-toolchain-support** [comment]
Issue with the env. Sorted out now.
