### ISSUE TITLE
Installation issue: genemark-et

### ISSUE THREAD

**Issue by LutzWeischerFujitsu** [LLNL/spack#21677]
[jw@cn05 jw]$ spack/bin/spack install genemark-et
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/berkeley-db-18.1.40-xhqs6cvlnggxtzkysk2fr5rdmzkbar3h
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/pkgconf-1.7.3-kdzlczv6oqysvfvd6kwnpkjjblqoiame
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/ncurses-6.2-vsgvk3ktw3v5pvbdcdnqjynfjwf26lx3
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/readline-8.0-2bgw5veq6zdka6jq2rwqtitmt3rw3l3i
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/gdbm-1.18.1-2dz44zlqyllstopcd42uorqaea6lne7p
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/perl-5.32.0-frdefhbg5p3mvsvixidnnh4sp6n6n7xf
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/perl-clone-choose-0.010-vzen26cdxfte6jkwwpriulyvgc67yrzp
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/perl-module-build-0.4224-xakunolmo5lye535bwiopqlffm45jsjd
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/perl-parallel-forkmanager-1.19-hajabovrpxkjfqubqcj5j4gyk7dvejlc
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/perl-class-data-inheritable-0.08-55m4ue4bejxh6agbwnwigqxbvvr3ojgg
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/perl-yaml-1.27-fbpq5rvoedzihhespv57rh7ztwhpbjab
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/perl-devel-stacktrace-2.02-osfnnjqov43ovbh7dpxjiyhcsi75xdxx
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/perl-scalar-list-utils-1.50-qedjhqhsqynvl7epgparwicxg6a5d4ns
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/perl-exception-class-1.43-mc3oobhrbnkosxbwfrzug447g2ji4o6f
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/perl-hash-merge-0.300-mqvzevxffgabwvnegfvs5xpreozvou5a
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/perl-object-insideout-4.05-wgx2nsqagd6jmm3ci3bwltp42kjl5svp
[+] /data/jw/spack/opt/spack/linux-centos8-a64fx/gcc-8.3.1/perl-logger-simple-2.0-fqhi3dulgey6n5pqh52osaphrua654di
==> Installing genemark-et-4.46-2vh32d3e5ldmushqtaxrvhkwxaswatkr
==> No binary for genemark-et-4.46-2vh32d3e5ldmushqtaxrvhkwxaswatkr found: installing from source
==> Error: FetchError: All fetchers failed

/data/jw/spack/lib/spack/spack/package.py:1335, in do_fetch:
       1332                                 self.spec.format('{name}{@version}'), ck_msg)
       1333
       1334        self.stage.create()
  >>   1335        err_msg = None if not self.manual_download else self.download_instr
       1336        self.stage.fetch(mirror_only, err_msg=err_msg)
       1337        self._fetch_time = time.time() - start_time
       1338

[jw@cn05 jw]$ spack/bin/spack debug report
* **Spack:** 0.16.0-948-9d1d37c432
* **Python:** 3.6.8
* **Platform:** linux-centos8-a64fx
* **Concretizer:** original
[jw@cn05 jw]$

**Comment by glennpj** [comment]
The `genemark-et` package requires registration and manual download. The spack package should make that clearer though.
