### ISSUE TITLE
Activating New Environment does not Work in Fish Shell

### ISSUE THREAD

**Issue by larkwiot** [LLNL/spack#21764]
I ran `spack env create testbed` in a new directory, then ran `spack env activate testbed` immediately after. I had already configured my fish shell to source the proper setup-env script, and restarted it. Everything else (`spack external find`, `spack install ctre`) has been working fine up until this point.

### Steps to reproduce the issue

In fish:
```console
$ spack env create newEnv
$ spack env activate newEnv
```

### Error Message
```console
test: Expected a combining operator like '-a' at index 2

Standard input (line 256):
    if test -z "$_a" or test -z "$_b"
       ^
in function 'match_flag' with arguments 'testbed -h'
in function 'check_env_activate_flags' with arguments 'testbed'
in function 'spack_runner' with arguments 'env activate testbed'
        called on line 579 of file ~/Repos/spack/share/spack/setup-env.fish
in function 'spack' with arguments 'env activate testbed'

(Type 'help test' for related documentation)

<<< Truncated as this error appears in other places of the script >>>
```
```console
$ spack --debug --stacktrace <command>
<<< Snipped error output >>>
lib/spack/spack/cmd/__init__.py:122 ==> [2021-02-18-12:38:36.475826] Imported env from built-in commands
lib/spack/spack/cmd/__init__.py:122 ==> [2021-02-18-12:38:36.479973] Imported env from built-in commands
lib/spack/spack/config.py:894 ==> [2021-02-18-12:38:36.482445] Reading config file /home/me/Repos/spack/etc/spack/defaults/config.yaml
lib/spack/spack/environment.py:135 ==> [2021-02-18-12:38:36.509928] Using environmennt 'testbed'
lib/spack/spack/config.py:894 ==> [2021-02-18-12:38:36.512028] Reading config file /home/me/Repos/spack/var/spack/environments/testbed/spack.yaml
lib/spack/spack/database.py:363 ==> [2021-02-18-12:38:36.514656] DATABASE LOCK TIMEOUT: 3s
lib/spack/spack/database.py:367 ==> [2021-02-18-12:38:36.514836] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:894 ==> [2021-02-18-12:38:36.516137] Reading config file /home/me/Repos/spack/etc/spack/defaults/modules.yaml
lib/spack/spack/config.py:894 ==> [2021-02-18-12:38:36.529787] Reading config file /home/me/Repos/spack/etc/spack/defaults/linux/modules.yaml
```

### Information on your system

* **Spack:** 0.16.0-1341-8e3ac8577f
* **Python:** 3.9.1
* **Platform:** linux-voidrolling-zen
* **Concretizer:** original

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

The issue can be easily demonstrated in the Fish shell without Spack.

```
»»» if test -z "$a" or test -z "$b"
        echo yes
    end
test: Expected a combining operator like '-a' at index 2

(Type 'help test' for related documentation)
```
 I am using Fish version 3.1.2 on Void Linux.

**Comment by carns** [comment]
I can also trigger this with `spack load -r <package>` without using environments.  The load appears to work anyway in that case, though, as best I can tell.

**Comment by s-sajid-ali** [comment]
I've been seeing this on develop as well. This [PR](https://github.com/spack/spack/pull/21679) might fix the issue.

**Comment by carns** [comment]
Thanks for the pointer!  I confirmed that fix works for me at least (loading a package manually without an environment produces no warnings/errors now) using origin/develop just now.

**Comment by larkwiot** [comment]
The PR does seem to have fixed my issue. Thanks!
