### ISSUE TITLE
Doc Error: RPackage configure_args signature wrong in docs

### ISSUE THREAD

**Issue by payerle** [LLNL/spack#21760]
This is to report a bug in the Spack on-line docs, specifically in the 
[page discussing RPackage build system](https://spack.readthedocs.io/en/latest/build_systems/rpackage.html)
In the section "Passing arguments to the configuration", it lists the method
<configure_args(self, spec, prefix)>, however the actual code (lib/spack/spack/build_systems/r.py) declares this method as only taking <self> as an argument (and uses it in that fashion).

This looks to be a simple error in the docs

**Comment by adamjstewart** [comment]
Closed by #21761
