### ISSUE TITLE
`spack use` fails when database is locked

### ISSUE THREAD

**Issue by davidbeckingsale** [LLNL/spack#218]
When the database is locked (e.g. installing a package), invocations of `spack use` rely on the database being unlocked and hence fail. Since the `use` command is only going to be loading packages already compiled, this doesn't really make much sense.

**Comment by tgamblin** [comment]
This is going to get fixed once we have finer-grained locking on particular package install directories.  This is also when parallel build is going to be in there.  I think it'll happen soon.

**Comment by tgamblin** [comment]
@davidbeckingsale This should be fixed by #1562.  Can you verify and reopen if not?
