### ISSUE TITLE
Compiler wrappers and include of directories from /usr (PGI, OpenACC)

### ISSUE THREAD

**Issue by pramodk** [LLNL/spack#2180]
this is bit long but to gives complete picture:

I am working on an application with PGI compiler and didn't understand why I was getting below error while compiling only with spack:

``` bash
  128, Accelerator restriction: call to 'log' with no acc routine information
```

I looked into `spack/lib/spack/env/pgi/pgcc` and enabled some verbose output. I realise that following extra includes are added : 

``` bash
 -I/usr/include
```

The associated code in the compiler wrapper is:

``` bash
# Read spack dependencies from the path environment variable
IFS=':' read -ra deps <<< "$SPACK_DEPENDENCIES"
for dep in "${deps[@]}"; do
    # Prepend include directories
    if [[ -d $dep/include ]]; then
        if [[ $mode == cpp || $mode == cc || $mode == as || $mode == ccld ]]; then
            args=("-I$dep/include" "${args[@]}")
        fi
    fi
```

I am using `OpenACC` with PGI and the `accelerated` kernels are using some `math` functions. PGI compiler doesn't like `/usr/include` (and hence `math.h`) because it needs `OpenACC` annotated declarations from compiler's directory.

Suppose there are two packages `A` and `B`. `A` has following dependencies (specified as externals with path `/usr`): 

``` bash
    depends_on('automake', type='build')
    depends_on('autoconf', type='build')
    depends_on('libtool', type='build')
```

While building package `B` for GPU with `PGI`, spack adds `-I/usr/include` for every dependency mentioned above which causes the problem.

I somewhat understand whats going on and wondering why `build` dependencies path (of `A`) are included for package `B`.

I could work around this by avoiding `/usr`. Has someone else came across this issue and have better way to avoid this situation?

p.s. I tried using `fake` path approach but if one of the dependencies is `python` then I got error like:

``` bash
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "/tmp/kumbhar/spack-stage/spack-stage-zIDsDu/xx/somefile.py", line 12, in <module>
    import os
ImportError: No module named os
```

**Comment by adamjstewart** [comment]
@davydden @citibeth I can't remember who was working on this issue, but your names come to mind. Spack no longer adds `/usr` to the compiler wrappers, right?

**Comment by davydden** [comment]
Yes, I believe this should be fixed as we filter paths with system prefixes before setting SPACK_DEPENDENCIES in build_environment.

Please reopen the issue if it persists on current develop.
