### ISSUE TITLE
Whether the package can be modified to support an installation that is not just client

### ISSUE THREAD

**Issue by simon28li** [LLNL/spack#21840]
When I compile an error for False, by changing the value of the client_only variant

```console
$ spack install openldap~client_only

```
> 1 error found in build log:
     316    checking sasl/sasl.h usability... no
     317    checking sasl/sasl.h presence... no
     318    checking for sasl/sasl.h... no
     319    checking sasl.h usability... no
     320    checking sasl.h presence... no
     321    checking for sasl.h... no
     322    configure: error: Could not locate Cyrus SASL

But I found that this dependency was written in package.py. Py was just commented out. 
Now, except for Pth, spack already has these dependencies.
Can you let go of these comments?
In addition, Pth is not available, but npth is available. Can you replace it?
```
# Recommended dependencies by Linux From Scratch
# depends_on('cyrus-sasl', when='~client_only') # not avail. in spack yet
# depends_on('openslp', when='~client_only') # not avail. in spack yet
# depends_on('Pth', when='~client_only') # not avail. in spack yet
```

### Information on your system

```
* **Spack:** 0.16.0-1376-f65e6ae4e6
* **Python:** 3.6.8
* **Platform:** linux-centos8-aarch64
* **Concretizer:** original
```
### General information

- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [ ] I have searched the issues of this repo and believe this is not a duplicate

**Comment by simon28li** [comment]
@Sinan81 Can you give me some help with this?

**Comment by Sinan81** [comment]
Sure. Why not submit a pull request? All you need to do is to uncomment the lines with cyrus and openslp, and make sure it builds.
