### ISSUE TITLE
shell test kcov suggestion does not work

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#21875]
### Steps to reproduce the issue

```console
$ ./share/spack/qa/run-shell-tests 
ERROR: kcov is required to run this script.

To install with Spack, run:
    $ spack install kcov
Then add the bin directory to your PATH.
$ spack load kcov
$ ./share/spack/qa/run-shell-tests 
ERROR: kcov is required to run this script.

To install with Spack, run:
    $ spack install kcov
Then add the bin directory to your PATH.
```

Seems like there is no kcov binary:

```
$ kcov

Command 'kcov' not found, but can be installed with:

sudo apt install kcov
```

* **Spack:** 0.16.0-1501-e8eb76c198
* **Python:** 3.8.7
* **Platform:** linux-ubuntu20.04-zen2
* **Concretizer:** clingo

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
What do you get when you run:
```console
$ spack load kcov
$ which kcov
```
Spack builds a `kcov` executable for me.

**Comment by haampie** [comment]
```
$ ls /home/harmen/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-10.2.0/kcov-38-ayzjybgqnlsbxr7bvwitlo4xzxop2vki/bin/
kcov-system-daemon
```

**Comment by haampie** [comment]
Oh wow, it's their cmake script :( https://github.com/SimonKagstrom/kcov/blob/master/src/CMakeLists.txt
