### ISSUE TITLE
git shallow clone of submodules as well?

### ISSUE THREAD

**Issue by pramodk** [LLNL/spack#2190]
Currently the repositories are cloned with `--depth=1` but if I set `submodules=True` then submodules are full clones. For large repos it would be nice to have submodules with `shallow` clones as well.

**Comment by junghans** [comment]
Use `--depth=1` for submodule is a bad idea, see #3956. In short the required hash in the submodule could be different from `HEAD` of the main branch, leading to an unfetchable ref.
