### ISSUE TITLE
Zero exit code if dependency fails to build

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#21937]
I'm trying to build a package A with many dependencies B, C, D, etc. I noticed that if B fails, I see:
```
==> Warning: skipping build of A since B failed
```
then Spack continues to install C and D. This is fine, but the exit code of this process is 0 even though the package I want to build (A) did not build. I would also expect an error message at the end of this informing me that the package I requested could not be built.

@tldahlgren I believe this may be related to the parallel build stuff you added a while back, maybe you can take a look. I've seen reports of this bug on Slack, but I don't think anyone has opened an issue on GitHub yet.

### Information on your system

* **Spack:** 0.16.0-1537-29201814cc
* **Python:** 3.8.7
* **Platform:** darwin-catalina-ivybridge
* **Concretizer:** clingo

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
https://github.com/spack/spack/issues/21319
https://github.com/spack/spack/issues/20510

Yeah, this needs to be fixed...

**Comment by adamjstewart** [comment]
Thanks! I knew I had seen this bug before. Closing as a duplicate.

**Comment by haampie** [comment]
how can we raise the priority of that issue? it's reported many times now

**Comment by adamjstewart** [comment]
Be more annoying 😁

**Comment by alalazo** [comment]
Duplicate of #21319

**Comment by tldahlgren** [comment]
> @tldahlgren I believe this may be related to the parallel build stuff you added a while back, maybe you can take a look. I've seen reports of this bug on Slack, but I don't think anyone has opened an issue on GitHub yet.
> 

Yes, it is related to the parallel build support changes.

There is (still) code at the bottom of build queue processing that is *supposed* to be raising an `InstallError` with the following message when a spec that is provided on the command line fails to install:

```
Installation request failed.  Refer to recent errors for specific package(s).
```

The package and associated exception should also be being logged as an ERROR.

I'm wondering if some of the follow-on work for parallelizing environments, perhaps, masks the error or it's an issue with how the particular failure is detected.

**Comment by tldahlgren** [comment]
> > @tldahlgren I believe this may be related to the parallel build stuff you added a while back, maybe you can take a look. I've seen reports of this bug on Slack, but I don't think anyone has opened an issue on GitHub yet.
> 
> Yes, it is related to the parallel build support changes.
> 
> There is (still) code at the bottom of build queue processing that is _supposed_ to be raising an `InstallError` with the following message when a spec that is provided on the command line fails to install:
> 
> ```
> Installation request failed.  Refer to recent errors for specific package(s).
> ```
> 
> The package and associated exception should also be being logged as an ERROR.
> 
> I'm wondering if some of the follow-on work for parallelizing environments, perhaps, masks the error or it's an issue with how the particular failure is detected.

Ah.  Just realized.  The issue here isn't that requested spec failed to install due to an exception; rather, it is skipped because its dependency(ies) failed to install!
