### ISSUE TITLE
Package installed as a dependency whereas it was already installed with same spec

### ISSUE THREAD

**Issue by cessenat** [LLNL/spack#21952]
I installed a package manually:

```shell
$ spack install harfbuzz@2.6.8%gcc@9.3.0~graphite2
[+] /home/cessenat/spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/harfbuzz-2.6.8-tdt4zlgepzzjcxafwzcb2hqxuvdhbitp
and I checked the spec:
$ spack spec harfbuzz %gcc@9.3.0 | grep harfbuzz
harfbuzz%gcc@9.3.0
harfbuzz@2.6.8%gcc@9.3.0~graphite2 arch=linux-centos7-skylake

Then, I installed qgis with
$ spack install --jobs 1 qgis %gcc@9.3.0
==> Installing harfbuzz-2.6.8-6fdhejlubxsxc52zz4wcuzpssioljkkd
where we can see that it as though harfbuzz were not installed.

Specs provide the same output as for the explicitely installed package:
$ spack spec qgis %gcc@9.3.0 | grep harfbuzz
            ^harfbuzz@2.6.8%gcc@9.3.0~graphite2 arch=linux-centos7-skylake
```

There probably is something I mis-understood from the documentation, it might be trivial for an expert.

spack debug report
* **Spack:** 0.16.0-1080-0b58499
* **Python:** 3.8.7
* **Platform:** linux-centos7-skylake
* **Concretizer:** original

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
Can you check the hashes of the two `harfbuzz`? If the hashes differ then the specs are different.

**Comment by cessenat** [comment]
Yes, the hashes differ ; but I do not undestand why.

**Comment by alalazo** [comment]
Can you diff and post the two corresponding `./spack/spec.yaml` files that are installed in the prefix?

**Comment by cessenat** [comment]
In fact I cannot, since when harfbuzz is compiled implicitly because of qgis it fails because cairo was not compiled with +pdf+ft.
Surprisingly it compiles succeefully when compiled explicitly (without specifying anything for cairo).
I found out there is a problem with qgis when installing the version explicitly
$ spack install qgis@3.10.10 %gcc@9.3.0
qscintilla requires py-pyqt5 variant +qsci_api, but spec asked for ~qsci_api
So I suggest that I shall correct both errors in harfbuzz and qgis and then see if it happens again.
The problem occured only on my CentOS 7 platform since, it did not show up on Ubuntu, where another bug, with qscintilla libtool using my system 4: proj instead of the spack proj, makes me stop just before compiling qgis.

**Comment by cessenat** [comment]
Well, since I'm no longer able to reproduce the pb I believe it was probably a newbie error.
