### ISSUE TITLE
【r-dplyr】After the r-dplyr software is installed using the Spack in CentOS8, an error is reported when the test suite is executed in the tests directory.

### ISSUE THREAD

**Issue by Tom-python0121** [LLNL/spack#21985]
Hello,I meet a problem about after the r-dplyr software is installed using the Spack in CentOS8, an error is reported when the test suite is executed in the tests directory.
### Steps to reproduce the issue

```console
[root@centos8 tests]# Rscript testthat.R

Attaching package: ‘dplyr’

The following object is masked from ‘package:testthat’:

    matches

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

══ Skipped tests ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
● dbplyr cannot be loaded (2)
● On CRAN (41)
● RSQLite cannot be loaded (1)

══ Failed tests ═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════
── Error (test-bind.R:19:3): cbind uses shallow copies ───────────────────────────
Error: there is no package called ‘lobstr’
Backtrace:
     █
  1. ├─testthat::expect_equal(lobstr::obj_addrs(df1), lobstr::obj_addrs(df[names(df1)])) test-bind.R:19:2
  2. │ └─testthat::quasi_label(enquo(object), label, arg = "object")
  3. │   └─rlang::eval_bare(expr, quo_get_env(quo))
  4. └─lobstr::obj_addrs
  5.   └─base::getExportedValue(pkg, name)
  6.     └─base::asNamespace(ns)
  7.       └─base::getNamespace(ns)
  8.         └─base::loadNamespace(name)
  9.           └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 10.             └─base:::withOneRestart(expr, restarts[[1L]])
 11.               └─base:::doWithOneRestart(return(expr), restart)
── Error (test-group-by.r:88:3): group_by uses shallow copy ───────────────────────────
Error: there is no package called ‘lobstr’
Backtrace:
     █
  1. ├─testthat::expect_equal(lobstr::obj_addrs(mtcars), lobstr::obj_addrs(m1)) test-group-by.r:88:2
  2. │ └─testthat::quasi_label(enquo(object), label, arg = "object")
  3. │   └─rlang::eval_bare(expr, quo_get_env(quo))
  4. └─lobstr::obj_addrs
  5.   └─base::getExportedValue(pkg, name)
  6.     └─base::asNamespace(ns)
  7.       └─base::getNamespace(ns)
  8.         └─base::loadNamespace(name)
  9.           └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 10.             └─base:::withOneRestart(expr, restarts[[1L]])
 11.               └─base:::doWithOneRestart(return(expr), restart)
── Error (???): no utf8 invasion (#722) ────────────────────────────────────────
Error: there is no package called ‘lobstr’
Backtrace:
     █
  1. ├─testthat::expect_equal(lobstr::obj_addrs(names(df)), lobstr::obj_addrs(names(df2)))
  2. │ └─testthat::quasi_label(enquo(object), label, arg = "object")
  3. │   └─rlang::eval_bare(expr, quo_get_env(quo))
  4. └─lobstr::obj_addrs
  5.   └─base::getExportedValue(pkg, name)
  6.     └─base::asNamespace(ns)
  7.       └─base::getNamespace(ns)
  8.         └─base::loadNamespace(name)
  9.           └─base::withRestarts(stop(cond), retry_loadNamespace = function() NULL)
 10.             └─base:::withOneRestart(expr, restarts[[1L]])
 11.               └─base:::doWithOneRestart(return(expr), restart)

[ FAIL 3 | WARN 0 | SKIP 44 | PASS 1904 ]
Error: Test failures
Execution halted
```
I don't know how to load the **lobstr** module. What is its display in the spack? Can you tell me?

### Information on your system
[root@centos8 spack-src]# spack debug report
* **Spack:** 0.16.1-1492-55eae72bb0
* **Python:** 3.6.8
* **Platform:** linux-centos8-aarch64
* **Concretizer:** original

### Additional information

- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by glennpj** [comment]
@Tom-python0121 
Running tests for `r-` packages generally involves needing to load many, perhaps all, of the "suggested" packages for a given package. To run the tests, you will have to load the package(s) being flagged in the error output. However, since Spack does not consider the packages in the "suggests" category to be dependencies there is the possibility, as in the case for `lobstr`, that the package is not in Spack, and thus can not be loaded, at least not via Spack. You could install `lobstr`, and any other packages that might be missing from Spack, in a personal R library, but be wary of conflicts down the road if you go that route. If you feel up to it, you could create any missing `r-` packages and submit them as PRs for inclusion in Spack.

**Comment by Tom-python0121** [comment]
@glennpj ,you are right.There is no package called'hms' I have added the **r-hms** dependency to solve the problem, but the error: there is no package called'lobstr' is displayed. Currently, the r-lobstr source code package has been found and enabled in the Spack, the **r-lobstr** dependency has been added to the r-dplyr, and the test passes.
