### ISSUE TITLE
Installation issue: JDK

### ISSUE THREAD

**Issue by skylerpaulus** [LLNL/spack#21991]
I believe this error is coming from the licensing side of JDK where to install a package you must first accept the license. 

### Steps to reproduce the issue
```
# spack install jdk@11.0.2_9
==> Installing jdk
==> No binary for jdk found: installing from source
==> Error: FetchError: All fetchers failed

/opt/ohpc/pub/spack/lib/spack/spack/package.py:1262, in do_fetch:
       1259                                 self.spec.format('{name}{@version}'), ck_msg)
       1260
       1261        self.stage.create()
  >>   1262        err_msg = None if not self.manual_download else self.download_instr
       1263        self.stage.fetch(mirror_only, err_msg=err_msg)
       1264        self._fetch_time = time.time() - start_time
       1265


# spack install jdk@14_36
==> Installing jdk
==> No binary for jdk found: installing from source
==> Error: FetchError: All fetchers failed

/opt/ohpc/pub/spack/lib/spack/spack/package.py:1262, in do_fetch:
       1259                                 self.spec.format('{name}{@version}'), ck_msg)
       1260
       1261        self.stage.create()
  >>   1262        err_msg = None if not self.manual_download else self.download_instr
       1263        self.stage.fetch(mirror_only, err_msg=err_msg)
       1264        self._fetch_time = time.time() - start_time
       1265
```

I have also downloaded jdk-11.0.10_linux-x64_bin.tar.gz, jdk-14.0.2_linux-x64_bin.tar.gz, and jdk-15.0.2_linux-x64_bin.tar.gz. Then added this to the spack package installer, i.e spack edit jdk. However, when I try to have spack install them it just goes for the website download instead of grabbing the tar file thats already downloaded. 

### Information on your system
* **Spack:** 0.15.4-1446-08e30a2
* **Python:** 3.6.8
* **Platform:** linux-centos7-sandybridge

### Additional information
example of added tar to spack edit jdk 

```
version('15.0.2', sha256='54b29a3756671fcb4b6116931e03e86645632ec39361bc16ad1aaa67332c7c61',
            url='https://download.oracle.com/otn-pub/java/jdk/15.0.2%2B7/0d1cfde4252546c6931946de8db48ee2/jdk-15.0.2_linux-x64_bin.tar.gz')
```

### General information
@justintoo 

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by bernhardkaindl** [comment]
fixed by #43264
