### ISSUE TITLE
flake8 complains: No module named pkg_resources

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#2205]
I'm currently unable to run `flake8`.

`spack install py-flake8` runs without complaint, but the result does not work:

```
[hartzelg@spack-0 spack-without-x]$ ./opt/spack/linux-centos7-x86_64/gcc-4.8.5/py-flake8-3.0.4-qglmd76ahe64jh4hxbfmepabx6p474ve/bin/flake8
Traceback (most recent call last):
  File "./opt/spack/linux-centos7-x86_64/gcc-4.8.5/py-flake8-3.0.4-qglmd76ahe64jh4hxbfmepabx6p474ve/bin/flake8", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
[hartzelg@spack-0 spack-without-x]$
```

Activating it also brings no joy:

```
[hartzelg@spack-0 spack-without-x]$ spack activate py-flake8
==> Activated extension py-configparser@3.5.0%gcc@4.8.5 arch=linux-centos7-x86_64-bmszhx5 for python@2.7.12~tk~ucs4%gcc@4.8.5
==> Activated extension py-enum34@1.1.6%gcc@4.8.5 arch=linux-centos7-x86_64-fio4enw for python@2.7.12~tk~ucs4%gcc@4.8.5
==> Activated extension py-mccabe@0.5.2%gcc@4.8.5 arch=linux-centos7-x86_64-isctfvl for python@2.7.12~tk~ucs4%gcc@4.8.5
==> Activated extension py-pycodestyle@2.0.0%gcc@4.8.5 arch=linux-centos7-x86_64-biu43lh for python@2.7.12~tk~ucs4%gcc@4.8.5
==> Activated extension py-pyflakes@1.2.3%gcc@4.8.5 arch=linux-centos7-x86_64-47fxdqi for python@2.7.12~tk~ucs4%gcc@4.8.5
==> Activated extension py-flake8@3.0.4%gcc@4.8.5 arch=linux-centos7-x86_64-qglmd76 for python@2.7.12~tk~ucs4%gcc@4.8.5
[hartzelg@spack-0 spack-without-x]$ ./opt/spack/linux-centos7-x86_64/gcc-4.8.5/python-2.7.12-ydag2gnkpeo4gjweh5esagyrkj44j7e5/bin/flake8
Traceback (most recent call last):
  File "./opt/spack/linux-centos7-x86_64/gcc-4.8.5/python-2.7.12-ydag2gnkpeo4gjweh5esagyrkj44j7e5/bin/flake8", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
```

**Comment by hartzell** [comment]
Google sez this type of thing is related to having setuptools properly installed.

Oddly enough there's a tcl modulefile for the py-* things, but not an lmod module.

I'll close this and straighten out my environment.

**Comment by adamjstewart** [comment]
Is your `py-flake8` installation old? I also ran into this bug and changed `py-setuptools` from a build dependency to a regular dependency, so this shouldn't happen anymore. But yes, that is the problem, setuptools needs to be in your PYTHONPATH.

**Comment by hartzell** [comment]
@adamjstewart -- it was old, and that deployment has suffered through many rounds of install/uninstall/branch-switchery.  It's probably not entirely sane....

**Comment by hartzell** [comment]
@adamjstewart -- in a tree cloned yesterday and built last night, I still need to load the dependent module by hand.  Is this the behavior you expect?

```
[hartzelg@spack-0 spack-20161101]$ module load py-flake8-3.0.4-gcc-5.4.0-r2hveh2
[hartzelg@spack-0 spack-20161101]$ spack flake8
=======================================================
flake8: running flake8 code checks on spack.

Modified files:
  var/spack/repos/builtin/packages/cairo/package.py
  var/spack/repos/builtin/packages/lua-luafilesystem/package.py
  var/spack/repos/builtin/packages/R/package.py
  var/spack/repos/builtin/packages/texlive/package.py
  var/spack/repos/builtin/packages/tk/package.py
=======================================================
Traceback (most recent call last):
  File "/rss/spack-20161101/opt/spack/linux-centos7-x86_64/gcc-5.4.0/py-flake8-3.0.4-r2hveh275gsevqv6yhl6gb6o62c2sxbp/bin/flake8", line 5, in <module>
    from pkg_resources import load_entry_point
ImportError: No module named pkg_resources
Flake8 found errors.
[hartzelg@spack-0 spack-20161101]$ module load py-setuptools-25.2.0-gcc-5.4.0-a72bmsd
[hartzelg@spack-0 spack-20161101]$ spack flake8
=======================================================
flake8: running flake8 code checks on spack.

Modified files:
  var/spack/repos/builtin/packages/cairo/package.py
  var/spack/repos/builtin/packages/lua-luafilesystem/package.py
  var/spack/repos/builtin/packages/R/package.py
  var/spack/repos/builtin/packages/texlive/package.py
  var/spack/repos/builtin/packages/tk/package.py
=======================================================
Flake8 checks were clean.
```

**Comment by adamjstewart** [comment]
I've never used modules before. @alalazo?

**Comment by hartzell** [comment]
@adamjstewart -- how do you stitch the various install dirs into your environment?

**Comment by adamjstewart** [comment]
We use something called [SoftEnv](http://www.mcs.anl.gov/hs/software/systems/softenv/softenv-intro.html) at ANL. It's basically modules, but it's a homegrown script that we wrote long before modules existed. It isn't supported by Spack obviously, and we are planning on making the switch to modules in the near future. So if you can discover and work out all the bugs in it now for me that would be great :laughing:

**Comment by adamjstewart** [comment]
Specifically for flake8, I've been activating the package and using the Python soft key/module. But we've ran into enough problems with `spack activate` and changing hashes that I don't think we'll be doing that in the future.

**Comment by alalazo** [comment]
@hartzell Yes, that's the expected behavior. You can have a more permanent solution if you:
```console
$ spack activate py-setuptools
```
See docs [here](http://spack.readthedocs.io/en/latest/basic_usage.html#extensions-python-support).

**Comment by hartzell** [comment]
I think that the ['direct'](http://spack.readthedocs.io/en/latest/module_file_support.html#autoload-dependencies) stuff here might turn out to be useful to me too.

Thanks for the help!
