### ISSUE TITLE
Spack adds external packages to the database (silently) with invalid PREFIX path

### ISSUE THREAD

**Issue by pramodk** [LLNL/spack#2208]
This is bit opposite to #2191 and I commented there about invalid path.

Here is long story...today I saw following error:

```bash
$ spack module refresh
....
  File "..../spack/var/spack/repos/builtin/packages/python/package.py", line 223, in setup_dependent_environment
    raise RuntimeError('Cannot locate python executable')
RuntimeError: Cannot locate python executable
```
Was wondering why python executable is suddenly an issue. Then realise @BarrySmith  added logic to detect `PYTHONHOME` in  #2173. That looks all good. My `packages.yaml` has always been like:
```bash
    python:
        paths:
            python@2.7.10: /System/Library/Frameworks/Python.framework/Versions/2.7
```
Looking at installed packages, I saw that the `python` package silently appears in the installed packages and with the `prefix` path that `doesn't` exist. (Note that this doesn't happen right away but I think when I install dependent packages and stuff....) :

```bash
 → spack find -p python
==> 2 installed packages.
-- darwin-elcapitan-x86_64 / clang@3.9.0 ------------------------
    python@2.7.10  xxx/spack/opt/spack/darwin-elcapitan-x86_64/clang-3.9.0/python-2.7.10-izyruuenr4wd7d4ssfeotod2tqz7g4kz
......

 → ll xxx/spack/opt/spack/darwin-elcapitan-x86_64/clang-3.9.0/python-2.7.10-izyruuenr4wd7d4ssfeotod2tqz7g4kz
ls: xxx/spack/opt/spack/darwin-elcapitan-x86_64/clang-3.9.0/python-2.7.10-izyruuenr4wd7d4ssfeotod2tqz7g4kz: No such file or directory
```

Now how to get around this issue? I tried to uninstall packages (which I never installed!), `reindex`, `purge` etc.. : 
```bash
spack uninstall -af python
==> The following packages will be uninstalled :
....
==> Do you want to proceed ? [y/n]
y
==> Removed stale DB entry for python@2.7.10%clang@3.9.0~tk~ucs4 arch=darwin-elcapitan-x86_64-izyruue
==> Removed stale DB entry for python@2.7.10%gcc@4.9.3~tk~ucs4 arch=darwin-elcapitan-x86_64-mdqov5t

spack reindex
spack purge -as

```
Is removing database safe option? or something else?

**Comment by becker33** [comment]
@pramodk is this still showing up for you? I currently only use one external package, but it appears to be recorded properly in the database. If you're still seeing it I can try for more of a reproducer.

**Comment by alalazo** [comment]
@pramodskumbhar @pramodk Closing this, feel free to reopen if still an issue.

**Comment by pramodskumbhar** [comment]
I missed issue update. This is not an issue anymore.
