### ISSUE TITLE
spack `config.yaml` and module path error

### ISSUE THREAD

**Issue by pramodk** [LLNL/spack#2209]
I am trying `config.yaml` with `install_tree` and `module_roots` (set to non-spack directory). When I do now `spack load` then I get : 
```bash
 spack load mypkg
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'mypkg-github-gcc-4.9.3-o5jdini'
```
@tgamblin : Two question : 
* Am I supposed set proper `MODULEPATH`? If so, we can close this ticket (but documentation doesn't say this).
* Shouldn't spack use it from what I have specified in `config.yaml`?

**Comment by alalazo** [comment]
@pramodk Did you source `share/spack/setup-env.sh` ? Sourcing that file should set up `MODULEPATH` appropriately.

**Comment by pramodk** [comment]
yes I did.

I see below in `setup-env.sh`:
```bash
_sp_source_file="${BASH_SOURCE[0]}"  # Bash's location of last sourced file.
if [ -z "$_sp_source_file" ]; then
    _sp_source_file="$0:A"           # zsh way to do it
    if [[ "$_sp_source_file" == *":A" ]]; then
        # Not zsh either... bail out with plain old $0,
        # which WILL NOT work if this is sourced indirectly.
        _sp_source_file="$0"
    fi
fi

#
# Set up modules and dotkit search paths in the user environment
#
_sp_share_dir=$(cd "$(dirname $_sp_source_file)" && pwd)
_sp_prefix=$(cd "$(dirname $(dirname $_sp_share_dir))" && pwd)
_spack_pathadd PATH       "${_sp_prefix%/}/bin"

_sp_sys_type=$(spack-python -c 'print(spack.architecture.sys_type())')
_spack_pathadd DK_NODE    "${_sp_share_dir%/}/dotkit/$_sp_sys_type"
_spack_pathadd MODULEPATH "${_sp_share_dir%/}/modules/$_sp_sys_type"
```
which doesn't seem like consider new `config.yaml` (?)

**Comment by alalazo** [comment]
@pramodk Sorry, I overlooked this part:

> I am trying config.yaml with install_tree and module_roots

I think this is indeed a bug...

**Comment by alalazo** [comment]
@pramodk I'll try to submit a PR asap to fix this
