### ISSUE TITLE
How can add a special compiler?

### ISSUE THREAD

**Issue by Bitllion** [LLNL/spack#22104]
I want use some special compilers ,like mybuild-new-gcc,I tried to run command 'spack find xxx' but it dosen't work

**Comment by alalazo** [comment]
The `spack find` command is used to query what is available in the database of installed software. The command you're looking for is:
```console
$ spack compiler find <PATH>
```
See the [Getting Started](https://spack.readthedocs.io/en/latest/getting_started.html#compiler-configuration) section of our docs for more information.

**Comment by Bitllion** [comment]
Sorry,it's my fault,I typed less.
Run command 'spack compiler find <PATH>' ,it can't find my compiler.
I also tried to edit the compiler yaml，replace the cc path with my own optimized gcc path,run the command 'spack compilers',the output is normal,but when I install my app,it failed,the output :ERROR 38

**Comment by alalazo** [comment]
Is your compiler in the `PATH`? If you don't specify a path explicitly that's where Spack would look for compilers. Also, do you have other GCC at the same version registered? If you have, say, a GCC 10.2.0 already registered and Spack finds another customized GCC 10.2.0 in the PATH it wouldn't figure out that these two are built differently.

**Comment by Bitllion** [comment]
use sapck commands
input:  spack compiler find /usr/bin/epyc-gcc
output: ==> Found no new compilers

**Comment by alalazo** [comment]
If the executable is named `epyc-gcc` I'm afraid you have to edit your `compilers.yaml` manually. The detection of compiler's type is based on regexes and for GCC none of the current rules include having "epyc" as a prefix.

**Comment by Bitllion** [comment]
Thank u very much,I modify my gcc's name,and it work!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Massimiliano Culpo"<notifications@github.com&gt;; 
发送时间: 2021年3月9日(星期二) 下午3:58
收件人: "spack/spack"<spack@noreply.github.com&gt;; 
抄送: "悦强"<yueqiang_fan@foxmail.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [spack/spack] How can add a special compiler? (#22104)





 
If the executable is named epyc-gcc I'm afraid you have to edit your compilers.yaml manually. The detection of compiler's type is based on regexes and for GCC none of the current rules include having "epyc" as a prefix.
 
&mdash;
