### ISSUE TITLE
Spack on GitLAB is out of date and fails on modern systems

### ISSUE THREAD

**Issue by middelkoopt** [LLNL/spack#22113]
https://gitlab.com/spack/spack.git is way out of date and can cause new user confusion.

### Rationale

The placeholder repo on gitLAB.com is out of date and it is not obvious that the wrong repo was cloned.  Help prevent PEBCAK!

### Description

I was running a live coding demo to teach Spack and cloned the GitLab version of spack.  It errored out because it could not find python (python2 was not installed) and the demo fell apart since was very old.  (Plan B worked just fine - used a previously cloned and built repo).

### Additional information

Although this really PEBCAK it could be very hard to diagnose for a new user and should be easy to fix (remove the repo, put an error message in `spack/share/spack/setup-env.*` or start pushing to GitLab).

### General information

- [ ] I have run `spack --version` and reported the version of Spack 
- [ X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by tgamblin** [comment]
Fixed -- gitlab should now mirror automatically: https://gitlab.com/spack/spack
