### ISSUE TITLE
Can't setup spack: ImportError: No module named 'typing'

### ISSUE THREAD

**Issue by mdorier** [LLNL/spack#22111]
I cloned the develop version of spack and called `. spack/share/spack/setup-env.sh` and got the following error:

```
Traceback (most recent call last):
  File "/homes/mdorier/spack/bin/spack", line 67, in <module>
    import spack.main  # noqa
  File "/nfs2/mdorier/spack/lib/spack/spack/main.py", line 28, in <module>
    from llnl.util.tty.log import log_output
  File "/nfs2/mdorier/spack/lib/spack/llnl/util/tty/log.py", line 23, in <module>
    from typing import Optional  # novm
ImportError: No module named 'typing'
```

The error doesn't show up with the latest release (0.16.1). My platform has python 2.7.6 and python 3.4.3. [This page](https://spack.readthedocs.io/en/latest/getting_started.html) indicates that 2.7 should work fine.

**Comment by alalazo** [comment]
@mdorier Python 2.7 is tested on each PR, so there may be something related to your environment. Can you post both:
```console
$ python2 bin/spack debug report
```
and
```console
$ echo $SPACK_PYTHON
```
?

**Comment by mdorier** [comment]
```
$ python bin/spack debug report
* **Spack:** 0.16.1-1609-aa80795
* **Python:** 2.7.6
* **Platform:** linux-ubuntu14.04-ivybridge
* **Concretizer:** original

$ python3 bin/spack debug report
Traceback (most recent call last):
  File "bin/spack", line 67, in <module>
    import spack.main  # noqa
  File "/nfs2/mdorier/mochi-ci/spack/lib/spack/spack/main.py", line 28, in <module>
    from llnl.util.tty.log import log_output
  File "/nfs2/mdorier/mochi-ci/spack/lib/spack/llnl/util/tty/log.py", line 23, in <module>
    from typing import Optional  # novm
ImportError: No module named 'typing'
```

It would seem that spack is using python 3.4 when setup-env.sh is called. The machine I'm working on hasn't changed its python installation recently so is it possible that spack was previously using python 2.7 by default (or more generally whatever the `python` command points to) and is now using `python3` by default?

**Comment by alalazo** [comment]
I think the issue is the following: we don't support Python 3.4 since a long time and we prefer using python3 over python. The solution in an environment like yours is setting `SPACK_PYTHON=$(which python)` explicitly before sourcing the script. See #21222 for more details. Let me know if you still have issues.

**Comment by mdorier** [comment]
This works, thanks.

**Comment by trws** [comment]
FYI: after a similar issue there's an active PR to print an appropriate error message when an unsupported python version is run. Hopefully if this comes up again it will be more clear what's happening.
