### ISSUE TITLE
Lmod modules no longer autogenerated, not avail as option to `module refresh`?

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#2216]
I have a spack tree that I've been working in for a while; I was pleasantly surprised when I noticed that *lmod* modulefiles were being automagically created.

I cloned a clean tree yesterday to try an end-to-end build of my environment and:

- `.../share/spack/lmod` is no longer present; and
-  `spack module refresh --help` does not list `lmod` as an available type of module, `spack module refresh` offers to rebuild all my *tcl* modules.

I'm not sure what, if anything, I did go end up with *lmod* modules in my old tree and/or what I've done to loose them in the new tree.

I read through the [module file support](lib/spack/docs/module_file_support.rst) docs,  but they did not shed any light.

Should something be happening automagically that isn't, or do I need to configure something, or???

**Comment by alalazo** [comment]
@hartzell The fact that lmod module files were auto-generated was a bug (they were considered in #107 and are effectively a sort of "experimental" feature). You can re-enable the generation adding the line:
```yaml
modules:
  enable:
    -lmod
```
to your ``modules.yaml``. See the docs [here](http://spack.readthedocs.io/en/latest/module_file_support.html#activation-of-other-systems).

**Comment by hartzell** [comment]
Should that also change the behavior of `spack module refresh`?

I made this change:

```diff
index 8864a76..d12f37f 100644
--- a/etc/spack/defaults/modules.yaml
+++ b/etc/spack/defaults/modules.yaml
@@ -15,8 +15,7 @@
 # -------------------------------------------------------------------------
 modules:
   enable:
-    - tcl
-    - dotkit
+    - lmod
   prefix_inspections:
     bin:
       - PATH
```

but `spack module refresh` is still only offering me the opportunity to refresh my *tcl* module files.

**Comment by hartzell** [comment]
However... `spack module refresh -m lmod` does [re]build the lmod modules

**Comment by alalazo** [comment]
@hartzell I cannot reproduce your issue. With the default `modules.yaml` I get:
```console
$ spack module refresh --help
usage: spack module refresh [-h] [--delete-tree] [-m {tcl,dotkit}] [-y]
                            [constraint [constraint ...]]

positional arguments:
  constraint            Constraint to select a subset of installed packages

optional arguments:
  -h, --help            show this help message and exit
  --delete-tree         Delete the module file tree before refresh
  -m {tcl,dotkit}, --module-type {tcl,dotkit}
                        Type of module files
  -y, --yes-to-all      Assume "yes" is the answer to every confirmation
                        request.
```
If I edit `etc/spack/defaults/modules.yaml` like you did:
```console
$ spack module refresh --help
usage: spack module refresh [-h] [--delete-tree] [-m {lmod}] [-y]
                            [constraint [constraint ...]]

positional arguments:
  constraint            Constraint to select a subset of installed packages

optional arguments:
  -h, --help            show this help message and exit
  --delete-tree         Delete the module file tree before refresh
  -m {lmod}, --module-type {lmod}
                        Type of module files
  -y, --yes-to-all      Assume "yes" is the answer to every confirmation
                        request.
```
Note the allowed options for `--module-type` change accordingly.

**Comment by hartzell** [comment]
I can not repeat it either :cry:.

I've been recently educated in #2219 about etc/spack vs. etc/spack/defaults.

If I create an etc/spack/modules.yaml and put this in it:

```
modules:
  enable:
    - lmod
```

Then I seem to have enabled all three:

```
  -m {tcl,lmod,dotkit}, --module-type {tcl,lmod,dotkit}
```

I settled on an `etc/spack/modules.yaml` that contains only this:

```
modules:
  enable::
    - lmod
```

after reading [the documentation](http://spack.readthedocs.io/en/latest/configuration.html#overriding-entire-sections) (which might shock some folks...).

Does that seem like a clean solution?

**Comment by alalazo** [comment]
> Does that seem like a clean solution?

@hartzell It is for me if you want to generate only `lmod`: double colon for the win :smile:

**Comment by hartzell** [comment]
"Read the docs", that'd be a great name for a website!
