### ISSUE TITLE
Should etc/spack/defaults/compilers.yaml be in the .gitignore?

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#2219]
I build the compiler that I want to use and add it to `etc/spack/defaults/compilers.yaml`.

That file does not not exist in the repository.  Once I've made the change it shows up as an untracked file.  I'm worried that I'll commit it in a fit of sloppiness at some point.

Would it be an appropriate addition to the top level .gitignore?

**Comment by adamjstewart** [comment]
You shouldn't edit anything in `etc/spack/defaults`. Put it in `etc/spack`.

**Comment by adamjstewart** [comment]
See http://spack.readthedocs.io/en/latest/configuration.html#configuration-scopes for details.

**Comment by tgamblin** [comment]
Also `/etc/spack/*.yaml` *is* in `.gitignore`

**Comment by tgamblin** [comment]
Note that this has existed for a while but was only recently documented 😊

**Comment by adamjstewart** [comment]
Do we support `/etc/spack` in addition to `$SPACK_ROOT/etc/spack`? I don't remember seeing that in the documentation.

**Comment by tgamblin** [comment]
Sorry -- edited.  No, we don't support `/etc/spack` at the system level.  We could wedge it in between defaults and `$spack_root/etc/spack`
