### ISSUE TITLE
compiler.yaml (and possibly packages.yaml) files requires undocumented order of modules

### ISSUE THREAD

**Issue by jjellio** [LLNL/spack#22222]
I've been developing a SPACK `cray/compiler.yaml` and randomly seemed to start getting missing `<mpi.h>` or the configures would fail to link `cannot find libmpi.so`.  With some digging (verbose compiler flags + linker). I noticed sometimes I was missing my MPI include path, and other times I was missing MPI in the rpath or library path.  My intuition was that I screwed up defining an external `mvapich2` definition in `packages.yaml`.  But no matter what I did to `compilers.yaml` or `packages.yaml` I always seemed to bump into one of the 3 possible problems (missing mpi.h, missing rpath, or failure to link due to missing library path). 

I say *randomly* because as I hit problems I tried to resolve them in `packages.yaml` or `compilers.yaml`, but I was fairly sure the modules I specified should be the correct modules. Likewise, if I loaded the modules (as specified in the yamls) manually `module load ...` I could always compile/link/run binaries.

Doing the naturally thing, I started hacking away trying to pin down why I got some errors some times and other errors others (that wasn't very fruitful).

I finally started getting a very early error:

In `spack install`, i.e., an error in spack's setup:
```
==> [2021-03-10-05:48:11.353899] [TOOLCHAIN] MATCH Cce
==> [2021-03-10-05:48:11.751752] Module name: craype-x86-haswell
==> [2021-03-10-05:48:11.751919] Package directory variable prefix: CRAYPE_X86_HASWELL
==> [2021-03-10-05:48:11.766202] Error: TypeError: expected str, bytes or os.PathLike object, not NoneType

spack/lib/spack/spack/build_environment.py:873, in _setup_pkg_and_run:
        870        tb_string = traceback.format_exc()
        871
        872        # build up some context from the offending package so we can
  >>    873        # show that, too.
        874        package_context = get_package_context(tb)
        875
        876        logfile = None
```

At this point, I had a `cray/compilers.yaml` that likely had modules defined roughly as: 
```
  modules:
  - something
  - craype-x86-haswell
  - something else
  - cce
```

I started looking at how SPACK deals with modules/rpath/etc... and I noticed this:
```
    # Second module is our compiler mod name. We use that to get rpaths from
    # module show output.
```

```python
# lib/spack/spack/build_environment.py:652

def get_rpaths(pkg):
    """Get a list of all the rpaths for a package."""
    rpaths = [pkg.prefix.lib, pkg.prefix.lib64]
    deps = get_rpath_deps(pkg)
    rpaths.extend(d.prefix.lib for d in deps
                  if os.path.isdir(d.prefix.lib))
    rpaths.extend(d.prefix.lib64 for d in deps
                  if os.path.isdir(d.prefix.lib64))
    # Second module is our compiler mod name. We use that to get rpaths from
    # module show output.
    if pkg.compiler.modules and len(pkg.compiler.modules) > 1:
        rpaths.append(path_from_modules([pkg.compiler.modules[1]]))
    return list(dedupe(filter_system_paths(rpaths)))

```
If I moved (in this case) Cray's `cce` to be my second module in `cray/compilers.yaml`, Then my headache miraculously vanishes.

I am a SPACK noob (so please correct me if I've missed something obvious).

I guess if I need to have my core compiler module as the second in the list, I missed that somewhere (In the learning process I've bounced around yaml files from admins and this subtle detail was never conveyed to me).

Given this a Cray platform, getting one core module off can cause really weird things to happen (for example, the rpath, library path, or include error)

Not sure if this is a bug or just a pitfall a new user can fall into.
(Apologies for the ramble, I think there is value in understanding how a user arrived at their dysfunctional state of being)

### Information on your system

This system is a private Cray platform.
```
spack debug report
* **Spack:** 0.16.1-1664-a9fcba827b
* **Python:** 3.6.8
* **Platform:** cray-rhel8-haswell
* **Concretizer:** original
```

### Additional information

- [ x ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ x ] I have searched the issues of this repo and believe this is not a duplicate
- [ x ] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
`platform=cray` has been deprecated, and now Cray are based on a JSON manifest file, closing.
