### ISSUE TITLE
Hash codes on `spack spec`

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#2224]
I'm getting unusual rebuilding... some packages seem to want to install a new version every time I do a `spack install`, for no apparent reason.

In order to debug this, I would like a command flag on `spack spec` that display the hash code of each node in the DAG.  Then I can (for example) do a bunch of `spack spec` calls and see if/when the hashcode changes for certain dependencies.

**Comment by alalazo** [comment]
Another thing that could be useful: a switch that tells you if any spec in the DAG is in the DB (i.e. installed). something like:
```console
$ spack spec -I hdf5~mpi
Input spec
------------------------------
  hdf5~mpi

Normalized
------------------------------
  hdf5~mpi
      ^zlib@1.1.2:

Concretized
------------------------------
[not installed]  hdf5@1.10.0-patch1%gcc@6.2.0+cxx~debug+fortran~mpi+shared~szip~threadsafe arch=linux-Ubuntu14-x86_64
[installed]          ^zlib@1.2.8%gcc@6.2.0 arch=linux-Ubuntu14-x86_64


```

**Comment by citibeth** [comment]
Yes... or just both at once.

On Thu, Nov 3, 2016 at 2:16 AM, Massimiliano Culpo <notifications@github.com

**Comment by citibeth** [comment]
This feature is key to building a simple test case for #2229.
