### ISSUE TITLE
Installation issue: py-pycairo

### ISSUE THREAD

**Issue by iarspider** [LLNL/spack#22277]
Installation of  `py-pycairo` creates weird directory named `""` (quotes quotes).

### Steps to reproduce the issue

```console
$ spack install py-pycairo@1.18.1
$ ls /cvmfs/sw.hsf.org/sft-spack/linux-centos7-haswell/gcc-8.3.0/py-pycairo-1.18.1-uslltv7ca6acskilahdf7v2jgzrgtim4/ -l
total 0
drwxr-sr-x. 4 sftnight sf 44 Mar 12 21:28 ""
drwxr-sr-x. 4 sftnight sf 48 Mar 12 21:28 lib```
```

### Information on your system

* **Spack:** 0.16.1-1650-1492461
* **Python:** 3.6.8
* **Platform:** linux-centos7-haswell
* **Concretizer:** original

### Additional information

Build logs: https://gist.github.com/iarspider/40d08948ac0f904407a80bca973dc0d4

Possibly related to or the same as #22108 

Pinging maintainer @adamjstewart 

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by iarspider** [comment]
Possibly relevant lines from log file:
```
==> [2021-03-12-21:28:20.145850] Warning: Quotes in command arguments can confuse scripts like configure.
  The following arguments may cause problems when executed:
      --install-data=""
  Quotes aren't needed because spack doesn't use a shell.
  Consider removing them
(...)
running install_pkgconfig
creating /cvmfs/sw.hsf.org/sft-spack/linux-centos7-haswell/gcc-8.3.0/py-pycairo-1.18.1-uslltv7ca6acskilahdf7v2jgzrgtim4/""
```

**Comment by adamjstewart** [comment]
It looks like that warning message is caused by @alalazo's #21446.
