### ISSUE TITLE
Installation issue: boost on Ubuntu 20.04

### ISSUE THREAD

**Issue by andredepinhovieira** [LLNL/spack#22291]
### Steps to reproduce the issue
This is related to issue #22252. On Ubuntu 20.04, Spack fails to build 'boost', indicating errors during the install phase. Below is the sequence of steps to reproduce the error, which happens either when trying to build with the Ubuntu 20.04 default gcc 9 or if I first install gcc 8.3.0 within Spack 

```console
$ spack install gcc@8.3.0
$ spack load gcc@8.3.0
$ spack compiler find
$ spack install boost@1.63.0+python+numpy%gcc@8.3.0 ^py-numpy@1.19.5 ^python@3.6.13
==> boost: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    './b2' 'install' 'threading=multi' '-j' '8' '--user-config=/tmp/apvieira/spack-stage/spack-stage-boost-1.63.0-mfubaxjxoj7z5bmgmmyy6qeeb3rgzj2p/spack-src/user-config.jam' 'variant=release' '-s' 'BZIP2_INCLUDE=/home/apvieira/spack/opt/spack/linux-ubuntu20.04-ivybridge/gcc-9.3.0/bzip2-1.0.8-m3hgpkjzvztgbqidh6rsmpqvmgwvs2sv/include' '-s' 'BZIP2_LIBPATH=/home/apvieira/spack/opt/spack/linux-ubuntu20.04-ivybridge/gcc-9.3.0/bzip2-1.0.8-m3hgpkjzvztgbqidh6rsmpqvmgwvs2sv/lib' '-s' 'ZLIB_INCLUDE=/home/apvieira/spack/opt/spack/linux-ubuntu20.04-ivybridge/gcc-9.3.0/zlib-1.2.11-f2quknrcbcclvrubs7rorxvtp5uxbq4d/include' '-s' 'ZLIB_LIBPATH=/home/apvieira/spack/opt/spack/linux-ubuntu20.04-ivybridge/gcc-9.3.0/zlib-1.2.11-f2quknrcbcclvrubs7rorxvtp5uxbq4d/lib' '-s' 'NO_LZMA=1' '-s' 'NO_ZSTD=1' 'link=static,shared' '--layout=system' 'toolset=gcc' 'cxxflags="-std=c++98"'

11962 errors found in build log:
     13731                     from /usr/include/unicode/unistr.h:39,
     13732                     from /usr/include/unicode/strenum.h:20,
     13733                     from /usr/include/unicode/locid.h:40,
     13734                     from /usr/include/unicode/coll.h:64,
     13735                     from ./boost/regex/icu.hpp:24,
     13736                     from libs/regex/build/../src/icu.cpp:23:
  >> 13737    /usr/include/c++/9/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
     13738       32 | #error This file requires compiler and library support \

...
```

### Information on your system

* **Spack:** 0.16.1-1698-d22bad13b1
* **Python:** 3.8.5
* **Platform:** linux-ubuntu20.04-ivybridge
* **Concretizer:** original
[spack-build-out.txt](https://github.com/spack/spack/files/6138099/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/6138102/spack-build-env.txt)

### Additional information

* [spack-build-out.txt]()
* [spack-build-env.txt]()

@hainest
### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by hainest** [comment]
The crux of the issue is that spack is passing `cxxflags="-std=c++98"` to `b2` instead of `cxxflags="-std=c++11"`. You can mitigate this by adding the variant `+cxxstd=11` or your C++ version of choice.

**Comment by Sinan81** [comment]
> The crux of the issue is that spack is passing `cxxflags="-std=c++98"` to `b2` instead of `cxxflags="-std=c++11"`. You can mitigate this by adding the variant `+cxxstd=11` or your C++ version of choice.

In my case, boots@1.63.0 compiles with the default `cxxstd=98` both on linux mint/ ubuntu and on centos7.

**Comment by Sinan81** [comment]
In the above mentioned error, it looks like `b2` is picking up system include directories:
```
/usr/include/unicode...
...
/usr/include/c++/9/bits/..
````
 which is kind of weird since Spack is supposed to sanitise the environment.

**Comment by haampie** [comment]
Seems like the issue is that boost depends on `libicu` here but spack doesn't add it as a dependency.

Does `spack install boost@1.63.0 +python +numpy +icu` work (without setting cxxstd=...)?

The real fix is we should enable the icu dep by default of course.

> which is kind of weird since Spack is supposed to sanitise the environment.

Not really, spack can ensure the build system will detect spack libs first, but it doesn't blacklist system paths. Right now it just hasn't listed icu as a dep so it doesn't provide the search paths. Also the latter path is from the compiler, so obviously that is not 'sanitized'.

**Comment by andredepinhovieira** [comment]
I ran ````spack install icu4c%gcc@8.3.0 ^python@3.6.13```` then ````spack install boost@1.63.0+python+numpy%gcc@8.3.0 ^py-numpy@1.19.5 ^python@3.6.13```` but got the same errors as before. 

Let me add that I noticed the following warning while building 'icu4c', although I suspect this is not relevant for the present problem. (I am really trying to build 'alps', which depends on 'boost' but cannot be built with Python newer than 3.6.)
````==> Warning: Python v3.6.13 does not have the C++ "distutils" patch; errors may occur when installing Python modules w/ mixed C/C++ source files.````
[spack-build-env.txt](https://github.com/spack/spack/files/6141023/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/6141024/spack-build-out.txt)

**Comment by haampie** [comment]
@andredepinhovieira that's not how it works, you have to install `boost +icu`. Also you don't have to run `spack load gcc`.

I think you actually might need to be very explicit:

```
$ spack spec boost cxxstd=11 +icu ^icu4c cxxstd=11
Input spec
--------------------------------
boost+icu cxxstd=11
    ^icu4c cxxstd=11

Concretized
--------------------------------
boost@1.75.0%gcc@10.2.0+atomic+chrono~clanglibcpp~container~context~coroutine+date_time~debug+exception~fiber+filesystem+graph+icu+iostreams+locale+log+math~mpi+multithreaded~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave cxxstd=11 patches=f2409bfa0e69e44817a5f8799e25c2e9e5ee50876a5aaacefd32fa647b80472f visibility=hidden arch=linux-ubuntu20.04-zen2
    ^bzip2@1.0.8%gcc@10.2.0+shared arch=linux-ubuntu20.04-zen2
        ^diffutils@3.7%gcc@10.2.0 arch=linux-ubuntu20.04-zen2
            ^libiconv@1.16%gcc@10.2.0 arch=linux-ubuntu20.04-zen2
    ^icu4c@60.3%gcc@10.2.0 cxxstd=11 arch=linux-ubuntu20.04-zen2
    ^zlib@1.2.11%gcc@10.2.0+optimize+pic+shared arch=linux-ubuntu20.04-zen2
```

Does that install for you?

**Comment by andredepinhovieira** [comment]
I am sorry for my mistakes. I had no previous experience with Spack. Here's what I did following your last message:
````
apvieira@fermi:~$ spack spec boost@1.63 cxxstd=11 +icu ^icu4c cxxstd=11
Input spec
--------------------------------
boost@1.63+icu cxxstd=11
    ^icu4c cxxstd=11

Concretized
--------------------------------
boost@1.63%gcc@9.3.0+atomic+chrono~clanglibcpp~container~context~coroutine+date_time~debug+exception~fiber+filesystem+graph+icu+iostreams+locale+log+math~mpi+multithreaded~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave cxxstd=11 patches=2ab6c72d03dec6a4ae20220a9dfd5c8c572c5294252155b85c6874d97c323199,d1cd178ea5348fafbba797113fc5a92cc822f3606dc2fe65c14cc2275334001b,fb7d84358c36309062fa4aaaa187343eb16871bd95893f0270e0941955c488ab visibility=hidden arch=linux-ubuntu20.04-skylake
    ^bzip2@1.0.8%gcc@9.3.0+shared arch=linux-ubuntu20.04-skylake
        ^diffutils@3.7%gcc@9.3.0 arch=linux-ubuntu20.04-skylake
            ^libiconv@1.16%gcc@9.3.0 arch=linux-ubuntu20.04-skylake
    ^icu4c@67.1%gcc@9.3.0 cxxstd=11 arch=linux-ubuntu20.04-skylake
        ^python@3.8.8%gcc@9.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87 arch=linux-ubuntu20.04-skylake
            ^expat@2.2.10%gcc@9.3.0+libbsd arch=linux-ubuntu20.04-skylake
                ^libbsd@0.10.0%gcc@9.3.0 arch=linux-ubuntu20.04-skylake
            ^gdbm@1.18.1%gcc@9.3.0 arch=linux-ubuntu20.04-skylake
                ^readline@8.0%gcc@9.3.0 arch=linux-ubuntu20.04-skylake
                    ^ncurses@6.2%gcc@9.3.0~symlinks+termlib arch=linux-ubuntu20.04-skylake
                        ^pkgconf@1.7.3%gcc@9.3.0 arch=linux-ubuntu20.04-skylake
            ^gettext@0.21%gcc@9.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-ubuntu20.04-skylake
                ^libxml2@2.9.10%gcc@9.3.0~python arch=linux-ubuntu20.04-skylake
                    ^xz@5.2.5%gcc@9.3.0~pic arch=linux-ubuntu20.04-skylake
                    ^zlib@1.2.11%gcc@9.3.0+optimize+pic+shared arch=linux-ubuntu20.04-skylake
                ^tar@1.32%gcc@9.3.0 arch=linux-ubuntu20.04-skylake
            ^libffi@3.3%gcc@9.3.0 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0 arch=linux-ubuntu20.04-skylake
            ^openssl@1.1.1j%gcc@9.3.0~docs+systemcerts arch=linux-ubuntu20.04-skylake
                ^perl@5.32.1%gcc@9.3.0+cpanm+shared+threads arch=linux-ubuntu20.04-skylake
                    ^berkeley-db@18.1.40%gcc@9.3.0~docs patches=b231fcc4d5cff05e5c3a4814f6a5af0e9a966428dc2176540d2c05aff41de522 arch=linux-ubuntu20.04-skylake
            ^sqlite@3.34.0%gcc@9.3.0+column_metadata+fts~functions~rtree arch=linux-ubuntu20.04-skylake
            ^util-linux-uuid@2.36%gcc@9.3.0 arch=linux-ubuntu20.04-skylake
````
After that, I tried again ````spack install boost@1.63.0+python+numpy+icu^py-numpy@1.19.5 ^python@3.6.13````, but the errors remain. 
[spack-build-env.txt](https://github.com/spack/spack/files/6142298/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/6142299/spack-build-out.txt)

**Comment by andredepinhovieira** [comment]
Now I realized that I should run ````spack install boost@1.63.0+python+numpy cxxstd=11 +icu ^icu4c cxxstd=11 ^py-numpy@1.19.5 ^python@3.6.13````, which works! Thank you!

**Comment by haampie** [comment]
You're welcome, #22301 should simplify this so that `spack install boost` will explicilty disable ICU, and `spack install boost +icu` will automatically set the right cxxstd variants.
