### ISSUE TITLE
Clingo Concretizer Doesn't Respect Custom Install Tree

### ISSUE THREAD

**Issue by alecbcs** [LLNL/spack#22294]
I ran spack containerize with the following spack environment  file and when building the resulting Dockerfile spack continued to install software into `/opt/spack/var/spack` instead of the set install path which results in an empty container being produced. Setting the concretizer to  `original` fixes the issue. Cc'ing @vsoch.

```yaml
spack:
  specs: wget
  view: true
  config:
    concretizer: clingo
  container:
    os_packages:
      build:
        - python3-dev
    strip: false
```

Dockerfile
```Dockerfile
# Build stage with Spack pre-installed and ready to be used
FROM spack/ubuntu-bionic:latest as builder

# Install OS packages needed to build the software
RUN apt-get -yqq update && apt-get -yqq upgrade \
 && apt-get -yqq install python3-dev \
 && rm -rf /var/lib/apt/lists/*

# What we want to install and how we want to install it
# is specified in a manifest file (spack.yaml)
RUN mkdir /opt/spack-environment \
&&  (echo "spack:" \
&&   echo "  specs:" \
&&   echo "  - wget" \
&&   echo "  view: /opt/view" \
&&   echo "  config:" \
&&   echo "    concretizer: clingo" \
&&   echo "    install_tree: /opt/software" \
&&   echo "  concretization: together") > /opt/spack-environment/spack.yaml

# Install the software, remove unnecessary deps
RUN cd /opt/spack-environment && spack env activate . && spack install --fail-fast && spack gc -y

# Modifications to the environment that are necessary to run
RUN cd /opt/spack-environment && \
    spack env activate --sh -d . >> /etc/profile.d/z10_spack_environment.sh


# Bare OS image to run the installed executables
FROM ubuntu:18.04

COPY --from=builder /opt/spack-environment /opt/spack-environment
COPY --from=builder /opt/software /opt/software
COPY --from=builder /opt/view /opt/view
COPY --from=builder /etc/profile.d/z10_spack_environment.sh /etc/profile.d/z10_spack_environment.sh



ENTRYPOINT ["/bin/bash", "--rcfile", "/etc/profile", "-l", "-c"]
```

### Steps to reproduce the issue

```console
$ spack containerize
$ docker run build -t wget .
```

### Information on your system

* **Spack:** 0.16.1
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-skylake
* **Concretizer:** clingo

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
I need to double check, but it's possible this was solved by #22559

**Comment by alalazo** [comment]
It doesn't seem to be solved by #22559 I'll investigate this further and report here the issues I found.

**Comment by alalazo** [comment]
I could reproduce even without the containerize command:
```yaml
spack:
  specs:
  - openjpeg
  config:
    concretizer: clingo
    install_tree:
      root: ./store
```

**Comment by alalazo** [comment]
The bug is related to the bootstrapping procedure, and most likely to the swapping of some part of the configuration. Starting with a python interpreter that can already import `clingo` doesn't trigger the bug.

**Comment by alalazo** [comment]
The issue is with temporary caches and lazily evaluated values. Currently when we bootstrap we call this method:

https://github.com/spack/spack/blob/9d42381d38fff23e9ef2c2d4de5a48efe937eb7a/lib/spack/spack/bootstrap.py#L213-L223

where we swap parts of the internal configuration to match what we want to enforce for bootstrapping. The issue stems from a combined action of having:
1. Configuration scopes swapped before the store
2. Store values being computed lazily

Since we swap the configuration scopes before needing to look at the store for the first time, when we swap the store we evaluate to the default values that have been just swapped in, rather than the ones that were originally in the user configuration.

**Comment by alalazo** [comment]
This diff should be an hotfix to the issue:
```diff
diff --git a/lib/spack/spack/bootstrap.py b/lib/spack/spack/bootstrap.py
index 3d51ca931e..2cb4842465 100644
--- a/lib/spack/spack/bootstrap.py
+++ b/lib/spack/spack/bootstrap.py
@@ -216,9 +216,9 @@ def ensure_bootstrap_configuration():
         # Default configuration scopes excluding command line and builtin
         # but accounting for platform specific scopes
         config_scopes = _bootstrap_config_scopes()
-        with spack.config.use_configuration(*config_scopes):
-            with spack.repo.use_repositories(spack.paths.packages_path):
-                with spack.store.use_store(spack.paths.user_bootstrap_store):
+        with spack.repo.use_repositories(spack.paths.packages_path):
+            with spack.store.use_store(spack.paths.user_bootstrap_store):
+                with spack.config.use_configuration(*config_scopes):
                     with spack_python_interpreter():
                         yield

```

**Comment by alecbcs** [comment]
@alalazo thank you for getting this merged so quickly!
