### ISSUE TITLE
How to use a software repository as a mirror?

### ISSUE THREAD

**Issue by JavierCVilla** [LLNL/spack#2231]
Reading the [mirror documentation](http://spack.readthedocs.io/en/latest/mirrors.html), seems that to create a mirror with a list of packages it is necessary to download all the packages into your local machine and then create the mirror (please correct me if I'm wrong). This list of packages grouped together afterwards could be located in web server. 

This approach is perfect for a small amount of packages for personal use or to provide a concrete stack of package with an specific version each one. But, IMHO it is not scalable when the list counts with thousands of packages or when this list is changing regularly (adding new versions, adding new packages...)

So, is there any way to declare a common web address where spack will have to try to fetch the tarfile of a package before going to the download url of the package recipe without using a created mirror?  

I would like to add a new line to the `mirror.yaml` file just pointing to this web server where I have all the used software and fetching there packages in first place.

**Comment by tgamblin** [comment]
`spack mirror create` does create a mirror the way you describe, and tries to download all the packages automatically.

But, there is also `spack mirror add <name> <url>` will let you register an already-created mirror as  palace to download packages.  So you can do this:

```
    spack mirror add local-server https://your-server.com/path/to/mirror
```

And Spack will do what you're asking.  

Somewhat related is that in `config.yaml`, the `source_cache` is a path to a local mirror directory (`var/spack/cache` by default) that contains downloaded tarballs and gets filled up as you download more packages.  So you could, say, `rsync` that periodically to populate your mirror server.

**Comment by JavierCVilla** [comment]
@tgamblin Ok, so this option:
```
spack mirror add local-server https://your-server.com/path/to/mirror
```
Does it require that the mirror had been previously created? With the command `spack mirror create`?

**Comment by adamjstewart** [comment]
I believe it can be an existing mirror, but it has to have the directory structure that Spack expects. The easiest way to get that is obviously with the `spack mirror create` command.

**Comment by tgamblin** [comment]
@adamjstewart is correct -- the structure is:

```
top-level-mirror-directory/
    <pkg>/
        <pkg>-<version>.<suffix>
```

Where `<pkg>` is the package name, `<pkg>-<version>` is the name, a dash, and the particular version, and `<suffix>` is the suffix in the package's download URL for that version.  

It's intended to be fairly easy to assemble a mirror by hand -- you just move the downloaded archive into the mirror and keep the same format as the original download (which preserves the checksum).

Note that resources and patches also go into the mirror -- we should probably document how they're named.  The easiest way to see how it should be is to just run `spack fetch <package>` and sync what ends up in `var/spack/cache/<package>` with your server.

**Comment by JavierCVilla** [comment]
Ok, I see. So there is no way to use an existing web server where I have all my package tarfiles without preprocessing and modify previously its folder structure to match with the described above.

Let's say that I have now a server with this structure:

```
http://myserver.com/packages/tarFiles/
  |-- Python-2.4.2.tgz   
  |-- Python-2.7.0.tgz
  |-- cmake-3.5.2.tar.gz  
  |-- mysql-5.7.11.tar.gz   
  \-- numpy-1.8.0.tar.gz     
```
So that, just creating a new mirror folder with the structure that Spack expects to find, maybe with softlinks to my current structure should be enough? I mean, this for instance:

 ```
http://myserver.com/packages/newMirror/
  |-- Python
          |-- Python-2.4.2.tgz --> ../tarFiles/Python-2.4.2.tgz
          |-- Python-2.4.2.patch
          \-- Python-2.7.0.tgz -->  ../tarFiles/Python-2.7.0.tgz
  |-- cmake
          \-- cmake-3.5.2.tar.gz   -->  ../tarFiles/cmake-3.5.2.tar.gz
  |-- mysql
          \-- mysql-5.7.11.tar.gz  -->  ../tarFiles/mysql-5.7.11.tar.gz 
  \-- numpy 
          \-- numpy-1.8.0.tar.gz  -->  ../tarFiles/numpy-1.8.0.tar.gz     
```

The reason of using softlinks is just to not duplicate files in other folder or lose my current structure due to it is in use by other services.

And finally specify to spack the new mirror:
```
spack mirror add local-server http://myserver.com/packages/newMirror/
```
Is this a valid way to do it?

**Comment by tgamblin** [comment]
Yep! Two observations:

1. In your example, `Python` should be `python` to match the package. but aside from that yes.
2. The checksums of these tarballs need to match what is in spack's package files.  Otherwise the check will fail after download.

**Comment by JavierCVilla** [comment]
@tgamblin Nice, I'm aware of both things (I used Python with uppercase in a previous service). So, perfect I'll try it!

**Comment by JavierCVilla** [comment]
@tgamblin It works perfectly, thank you very much. I think the issue can be closed.

**Comment by saitoasukakawaii** [comment]
> Yep! Two observations:
> 
> 1. In your example, `Python` should be `python` to match the package. but aside from that yes.
> 2. The checksums of these tarballs need to match what is in spack's package files.  Otherwise the check will fail after download.

yes，Python should be python, but what should be careful about curl?
