### ISSUE TITLE
Installation issue: [MyBayes] serf cannot find libuuid

### ISSUE THREAD

**Issue by vsoch** [LLNL/spack#22335]
We are trying to build MyBayes with containerize, and hitting several [build errors](https://github.com/autamus/registry/pull/66/checks?check_run_id=2114274745):

Specifically, it looks like we cannot build serf because uuid is missing. It's a dependency for MrBayes, but not serf.

```bash
           -laprutil-1 -lexpat -liconv
  >> 89    /usr/bin/ld: cannot find -luuid
  >> 90    collect2: error: ld returned 1 exit status
     91    scons: *** [libserf-1.so.1.3.0] Error 1
     92    scons: building terminated because of errors.

See build log for details:
  /tmp/root/spack-stage/spack-stage-serf-1.3.9-kfnmuhyiolrxhuvgpqnuq4xhhsucthiw/spack-build-out.txt
```
The spack.yaml for containerize is:

```yaml
spack:
  specs: ["mrbayes"]
  view: true
  container:
    os_packages:
      build:
        - python3-dev
      final:
        - ca-certificates
    strip: false
```

**Comment by adamjstewart** [comment]
Just hit this on Ubuntu 20.04, also see #21672. Will try to fix this today.
