### ISSUE TITLE
Installation issue: llvm won't build without '-j1'

### ISSUE THREAD

**Issue by nlvw** [LLNL/spack#22344]
When trying to install llvm (>=11.0.0) on the 0.16/develop branches, it always fails unless I specify '-j1'.  The problem is when I specify '-j1' the build takes 8+ hours.  I've tried with other levels of parallel such as '-j4','-j8',etc.. with the same results.

Here is an example of the error I'm seeing:
![image](https://user-images.githubusercontent.com/5723368/111384595-50cc7300-866f-11eb-8b28-890610ecd609.png)

### Steps to reproduce the issue

Try Installing the following spec:
[llvm.spec.yml.txt](https://github.com/spack/spack/files/6152407/llvm.spec.yml.txt)
```console
$ spack spec -l llvm
Input spec
--------------------------------
llvm

Concretized
--------------------------------
eqkhvuo  llvm@11.0.1%gcc@9.3.0~all_targets+clang~code_signing+compiler-rt~cuda+flang+gold+internal_unwind~ipo+libcxx+lld+lldb~llvm_dylib~mlir~omp_debug~omp_tsan+polly~python~shared_libs~split_dwarf build_type=Release cuda_arch=none arch=linux-centos7-x86_64
33e7wmy      ^binutils@2.36.1%gcc@9.3.0+gold~headers~interwork~ld~libiberty~lto+nls~plugins arch=linux-centos7-x86_64
zxtgsuh          ^diffutils@3.7%gcc@9.3.0 arch=linux-centos7-x86_64
3h4ijv3              ^libiconv@1.16%gcc@9.3.0 arch=linux-centos7-x86_64
xqkgnhw          ^gettext@0.21%gcc@9.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-centos7-x86_64
7p6pftw              ^bzip2@1.0.8%gcc@9.3.0+shared arch=linux-centos7-x86_64
pvvnuip              ^libxml2@2.9.10%gcc@9.3.0~python arch=linux-centos7-x86_64
aso2b7h                  ^pkgconf@1.7.3%gcc@9.3.0 arch=linux-centos7-x86_64
n24wphj                  ^xz@5.2.5%gcc@9.3.0~pic arch=linux-centos7-x86_64
o5eyrr4                  ^zlib@1.2.11%gcc@9.3.0+optimize+pic+shared arch=linux-centos7-x86_64
hwn6g5r              ^ncurses@6.2%gcc@9.3.0~symlinks+termlib arch=linux-centos7-x86_64
hnz4zml              ^tar@1.32%gcc@9.3.0 arch=linux-centos7-x86_64
mgxre4e      ^cmake@3.19.5%gcc@9.3.0~doc+ncurses+openssl+ownlibs~qt build_type=Release patches=b48396c0e4f61756248156b6cebe9bc0d7a22228639b47b5aa77c9330588ce88 arch=linux-centos7-x86_64
pwrr6dy          ^openssl@1.1.1j%gcc@9.3.0~docs+systemcerts arch=linux-centos7-x86_64
srxrr5q              ^perl@5.32.1%gcc@9.3.0+cpanm+shared+threads arch=linux-centos7-x86_64
quwnvxd                  ^berkeley-db@18.1.40%gcc@9.3.0~docs patches=b231fcc4d5cff05e5c3a4814f6a5af0e9a966428dc2176540d2c05aff41de522 arch=linux-centos7-x86_64
v7k2dmp                  ^gdbm@1.18.1%gcc@9.3.0 arch=linux-centos7-x86_64
gqh5clp                      ^readline@8.0%gcc@9.3.0 arch=linux-centos7-x86_64
gkka5py      ^hwloc@2.4.1%gcc@9.3.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml+pci+shared arch=linux-centos7-x86_64
rwtvmjb          ^libpciaccess@0.16%gcc@9.3.0 arch=linux-centos7-x86_64
7h77rfe              ^libtool@2.4.6%gcc@9.3.0 arch=linux-centos7-x86_64
7mznmph                  ^m4@1.4.18%gcc@9.3.0+sigsegv patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 arch=linux-centos7-x86_64
c65ernv                      ^libsigsegv@2.12%gcc@9.3.0 arch=linux-centos7-x86_64
rn4mhf3              ^util-macros@1.19.1%gcc@9.3.0 arch=linux-centos7-x86_64
gtnab2l      ^libedit@3.1-20191231%gcc@9.3.0 arch=linux-centos7-x86_64
nwfnf6b      ^perl-data-dumper@2.173%gcc@9.3.0 arch=linux-centos7-x86_64
rubanf6      ^python@3.8.6%gcc@9.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87 arch=linux-centos7-x86_64
i7lbdia          ^expat@2.2.10%gcc@9.3.0+libbsd arch=linux-centos7-x86_64
lkj3fww              ^libbsd@0.10.0%gcc@9.3.0 arch=linux-centos7-x86_64
3z4ue4q          ^libffi@3.3%gcc@9.3.0 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0 arch=linux-centos7-x86_64
zjhayua          ^sqlite@3.34.0%gcc@9.3.0+column_metadata+fts~functions~rtree arch=linux-centos7-x86_64
2kalov5          ^util-linux-uuid@2.36%gcc@9.3.0 arch=linux-centos7-x86_64
6wl3nr5      ^swig@4.0.2%gcc@9.3.0 arch=linux-centos7-x86_64
cg22j7n          ^pcre@8.44%gcc@9.3.0~jit+multibyte+utf arch=linux-centos7-x86_64
dicciek      ^z3@4.8.9%gcc@9.3.0+python arch=linux-centos7-x86_64
xh3q24y          ^py-setuptools@50.3.2%gcc@9.3.0 arch=linux-centos7-x86_64

```

### Information on your system

```console
$ spack debug report
* **Spack:** 0.16.1-1721-603331e
* **Python:** 3.6.8
* **Platform:** linux-centos7-cascadelake
* **Concretizer:** original
```
[compilers.yaml.txt](https://github.com/spack/spack/files/6152376/compilers.yaml.txt)
[packages.yaml.txt](https://github.com/spack/spack/files/6152377/packages.yaml.txt)
[config.yaml.txt](https://github.com/spack/spack/files/6152379/config.yaml.txt)

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/6152351/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/6152352/spack-build-out.txt)
[spack-configure-args.txt](https://github.com/spack/spack/files/6152355/spack-configure-args.txt)

@naromero77 
@trws 

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by nlvw** [comment]
I did some more testing, llvm@10.0.1 builds successfully (after specifying '~flang') and 11.0.1 builds when disabling flang ('~flang').

So it looks like the problem is specifically with the flang variant, which is enabled by default.

**Comment by alalazo** [comment]
@naromero77 @trws

**Comment by naromero77** [comment]
@becker33 This should have never been merged in:
https://github.com/spack/spack/pull/21229

Neither me (@naromero77) nor @trws reviewed it and we are the package maintainers.

Flang is not ready for broad use and Pat McCormick (LANL) had asked not to include it.

**Comment by naromero77** [comment]
At minimum, that Flang variant should be set to `False.` Its not a fully functional Fortran compiler and needs another compiler, e.g. GCC, to work.

**Comment by trws** [comment]
Ouch, yes.  Default to `False` is a minimum, it really should probably come with a huge warning label on it as experimental or semi-functional or similar. Having it build by default is not something we should be doing until it's part of the default projects list.  As of today it isn't even part of *ALL* yet because of its C++ std requirements (snippet from LLVM CMakeLists.txt):

```cmake
set(LLVM_ALL_PROJECTS "clang;clang-tools-extra;compiler-rt;debuginfo-tests;libc;libclc;libcxx;libcxxabi;libunwind;lld;lldb;mlir;openmp;parallel-libs;polly;pstl")
# The flang project is not yet part of "all" projects (see C++ requirements)
set(LLVM_EXTRA_PROJECTS "flang")
```

**Comment by nlvw** [comment]
@trws I'm not sure this should be closed.  While it fixes the default spec so that it builds the flang variant is still broken.  If the variant is going to be included in the package it really should be in working condition.  Personally I'm not in need of flang at this point in time so I'll leave this as is if you don't want to address the flang variant build issues.

**Comment by trws** [comment]
At the moment, I think all we can really do with that is force j1 if that variant is selected, and I'm not totally comfortable  baking that into the package.  This is definitely an issue that should be fixed, but flang is so unstable I'm tempted to leave it as an upstream problem for the moment.
