### ISSUE TITLE
[Suggestion] [Low Priority] Change output of suggestion to use -k / --insecure for added clarity

### ISSUE THREAD

**Issue by svenevs** [LLNL/spack#2236]
When `curl` has an SSL certificate verification problem (mine was exit code `60` in this specific case), the output is slightly confusing. It prints out

```
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification...
 ...
If this HTTPS server uses a...
 ...
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

For some reason I thought this entire message was coming from `curl`, but only the first two lines were.  The rest is output by `spack`.  It should have been obvious, but I pulled out the man page of `curl` first and found `-K` and thought it was a typo, rather than me being stupid.

I'm suggesting making the final output message a little more explicit

```
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

changes to

```
If you'd like to turn off curl's verification of the certificate, call
 spack with the -k (or --insecure) option.
```

AKA "If you'd like to turn off curl's verification of the certificate, ~use~[call spack with] the -k (or --insecure) option."

I'm probably the only person who has done this, and it didn't take long to figure it out, but I thought it may save somebody 5 minutes one day ;)

**Comment by adamjstewart** [comment]
Wait, is that a Spack command output? I'm not finding that text anywhere in lib. On Linux, the option is `-k, --insecure`. We just happen to use the same syntax. Do you happen to have GNU curl installed in addition to your system curl? I wonder which one it is picking up.

**Comment by svenevs** [comment]
Lol. Oh my, I think you're right that actually is all from `curl`.  Guess there's nothing to do here then?  I ended up realizing it was an option for `spack` after browsing some of the issues and ultimately finding [this PR commit](https://github.com/LLNL/spack/pull/1786/commits/261decd36eabf199040b5ce5196a9a5b4f2c43b4).

So I guess I'll close this...sorry x0

**Comment by adamjstewart** [comment]
Also, if you need to do this permanently, it can now be set in your `~/.spack/config.yaml` with the use of the `verify_ssl` setting: http://spack.readthedocs.io/en/latest/config_yaml.html#verify-ssl

But I wouldn't recommend that. You should probably sort out your SSL cert problems...
