### ISSUE TITLE
Installation issue: udunits package source is very odd

### ISSUE THREAD

**Issue by rhoneyager** [LLNL/spack#22365]
The udunits package is produced by UCAR Unidata. The [Spack package definition](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/udunits/package.py#L13) uses a URL that points to www.gfd-dennou.org. This site seems to be completely unrelated to UCAR, and most of its information pages are only in Japanese.

<img width="1151" alt="Screen Shot 2021-03-17 at 4 35 09 PM" src="https://user-images.githubusercontent.com/7389890/111534880-d9661480-873e-11eb-8b88-82375af32987.png">

Also, the package versions in the package.py file do not correspond to files available on either UCAR's [download page](https://artifacts.unidata.ucar.edu/service/rest/repository/browse/downloads-udunits/) or on gfd-dennou.org. Spack is getting these from its AWS mirrors, and these old versions fail to build on recent macOS releases.

**Comment by rhoneyager** [comment]
No maintainers are listed and a search for udunits-related issues in Spack is rather sparse since 2019. I am mentioning @tgamblin, @adamjstewart, and @michaelkuhn since they show up in git's history for the package.

**Comment by michaelkuhn** [comment]
FYI: Fedora gets the source from `ftp://ftp.unidata.ucar.edu/pub/udunits/`.

Ah, #4798 specifically changed to URL to download via HTTP instead. I still think we should prefer the proper upstream.

**Comment by adamjstewart** [comment]
https://artifacts.unidata.ucar.edu/service/rest/repository/browse/downloads-udunits/ has downloads over HTTP but they only seem to keep the latest patch version, so it wouldn't be very reliable.

**Comment by tgamblin** [comment]
That change came from #4798 by @weijianwen, who did the Spack integration for the Pi machine at Shanghai Jiaotong University.  From the PR: the change was to make downloads easier, as it looks like the UCAR link was FTP.

@rhoneyager: do you want to submit an update to this package? Is there a mirror at UCAR that actually keeps older versions around?

**Comment by tgamblin** [comment]
For the macos issue, I'm guessing we just need a newer version in Spack.  To keep other versions working though we need some reliable mirror.

That said, we do have our own source mirror now, so maybe we allow authoritative mirrors that don't keep history, and let people download older things from Spack S3.

**Comment by tgamblin** [comment]
we could also get past releases here: https://github.com/Unidata/UDUNITS-2, though it looks like the project doesn't attach their release tarballs to their tagged versions -- and github tarball sha's can change.

**Comment by rhoneyager** [comment]
> @rhoneyager: do you want to submit an update to this package? Is there a mirror at UCAR that actually keeps older versions around?

Looking at the Unidata mailing list proved helpful. The udunits developers recently migrated from their old FTP server to a more modern service. They also recently announced that they will retain older versions from now on \[[link](https://www.unidata.ucar.edu/support/help/MailArchives/udunits/msg01057.html)\]. Older tarballs may or may not appear.

Sure, I can submit an update.
