### ISSUE TITLE
Variant issue for mpich

### ISSUE THREAD

**Issue by hyviquel** [LLNL/spack#22427]
### Steps to reproduce the issue

Building and installing mpich with `--with-device=ch4:ucx` outside of Spack then running:

```console
spack external find 
```

### Error Message

```console
==> Error: invalid values for variant "device" in package "mpich": ['ch4:ucx']
```

### Information on your system

```
* **Spack:** 0.16.1-1764-3305a39c55
* **Python:** 3.8.5
* **Platform:** linux-ubuntu20.04-skylake
* **Concretizer:** original
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
@raffenet @yfguo should we change `multi=False` to `multi=True` for this variant?

**Comment by raffenet** [comment]
For the device variant? You can only build one device configuration (ch3 or ch4), so I suspect not. `--with-device=ch4:ucx` specifies the ch4 device with ucx netmod.

**Comment by adamjstewart** [comment]
In that case it sounds like the bug is in the automatic detection.

**Comment by hyviquel** [comment]
do you guys know of any way to avoid the problem from user command as a temporary fix that I could use?

**Comment by adamjstewart** [comment]
If you don't care about mpich and only want to load a add a specific package, you can do `spack external find <package>`. Otherwise I think the fix is pretty simple. I'll push a PR and let you test it.
