### ISSUE TITLE
Intel-parallel-studio installation using stub compiler

### ISSUE THREAD

**Issue by amaji** [LLNL/spack#22456]
I am trying to install `intel-parallel-studio` using the stub compiler approach described here: https://spack.readthedocs.io/en/latest/build_systems/intelpackage.html

I have added a stub intel compiler in my `compilers.yaml` and then try to install intel. This used to work fine in older Spack but seems like Spack 0.16.1 is much stricter about verifying entries in `compilers.yaml` and tells me that the stub compiler is not usable. 

Here is the error message:
```
$ spack install --no-checksum -y intel-parallel-studio@cluster.2019.5 %intel@19.0.5
==> Warning: Intel's compilers may or may not optimize to the same degree for non-Intel microprocessors for optimizations that are not unique to Intel microprocessors
==> Installing intel-parallel-studio-cluster.2019.5-lvbrjeawaaz5i4o6tv6vg2vj6npkqdtz
==> No binary for intel-parallel-studio-cluster.2019.5-lvbrjeawaaz5i4o6tv6vg2vj6npkqdtz found: installing from source
==> Error: CompilerAccessError: Compiler 'intel@19.0.5' has executables that are missing or are not executable: ['stub', 'stub', 'stub', 'stub']

/scratch/a/amaji/spack-test-20210319/framework/spack/lib/spack/spack/build_environment.py:868, in _setup_pkg_and_run:
        865        tb_string = traceback.format_exc()
        866
        867        # build up some context from the offending package so we can
  >>    868        # show that, too.
        869        package_context = get_package_context(tb)
        870
        871        logfile = None
```

Is this method of installing `intel-parallel-studio` no longer supported? If so, please update the documentation.

Let me know if there is a better way to tell Spack to install `intel-parallel-studio` without tying to a specific compiler.

**Comment by alalazo** [comment]
I think this was fixed by #22248
