### ISSUE TITLE
Installation issue: OpenMPI+CUDA fails to build in certain cases due to hwloc version constraint mismatch

### ISSUE THREAD

**Issue by nhanford** [LLNL/spack#22497]
`openmpi requires hwloc constrain a concrete spec hwloc@2.0:+cuda, but spec asked for hwloc@2.4.1`

### Steps to reproduce the issue

1. Install a CUDA of your choice.
2. Install a UCX with that CUDA.
3. Install OMPI with that UCX.

### Information on your system

Should be reproducible on any CUDA-enabled cluster.

### Additional information

@hppritcha I believe https://github.com/spack/spack/blob/95ad5b882c990971e74d04261a665ba680f7c4be/var/spack/repos/builtin/packages/openmpi/package.py#L276
should be
`depends_on('hwloc@2:', when='@4: ~internal-hwloc')`

Otherwise it would appear that the former is slightly too restrictive; forcing hwloc to a 2.0.x version when any 2.y.z version would do.
However, I could be wrong and perhaps there is some compelling reason hwloc needs to be held back to 2.0.x if CUDA is present.

Thanks!

### General information

- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [ ] I have searched the issues of this repo and believe this is not a duplicate

**Comment by hppritcha** [comment]
@nhanford I agree with your depends observation

**Comment by nhanford** [comment]
Sorry for the delay. I believe this issue is now resolved. Thanks!
