### ISSUE TITLE
Using single spack instance for multiple architectures

### ISSUE THREAD

**Issue by pramodk** [LLNL/spack#2257]
I have been using single spack instance/installation for `bg-q` and `x86` cluster. But today on `bg-q` I am seeing `x86` packages : 

```bash
○ → spack arch
bgq-CNK-powerpc

○ → spack find
==> 32 installed packages.
-- linux-redhatenterpriseserver6-x86_64 / gcc@4.9.3 -------------
mytestpkgA@perfmodels  mytestpkgB@perfmodels……
```

Why? Is this expected new behaviour?

**Comment by alalazo** [comment]
Yes, using `spack find` you see all the packages you have installed no matter the architecture.

**Comment by pramodk** [comment]
Ok, I probably didn't notice that before. How `spack load` is supposed to behave / handle this? Currently I see : 
```bash
$ spack load mytestpkgA
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'mytestpkgA-xxxx-gcc-5.2.0-tum75yd'
```
Would be better to say `mytestpkgA  not installed for arch xxx`?

**Comment by citibeth** [comment]
Why don't you just use two Spack instances?

**Comment by pramodk** [comment]
> Why don't you just use two Spack instances?

I will do this. Is this recommended approach / how others use it?

(as there is now `platform` specific `sub-directotirs` inside `~/.spack`, I was wondering if I can just use single instance).

**Comment by adamjstewart** [comment]
You should be able to use a single Spack instance. That's the whole point of having platform-specific subdirectories.

**Comment by pramodk** [comment]
@adamjstewart: on system with shared filesystem between `bg-q` (`bgq-CNK-powerpc`) and `x86` (`linux-redhatenterpriseserver6-x86_64`), which are completely different platforms, we need fix for `spack load` etc? because there is no point of loading `x86` packages on `bg-q` (similarly for other platforms).

**Comment by tgamblin** [comment]
@pramodk: we have shared filesystems between multiple architectures at LLNL, and so do many sites.  You should be able to use a single Spack instance.  Also, on systems like BG/Q, there are multiple platforms involved anyway -- `bgq-cnk-ppc64` and `bgq-rhel7-ppc64` (or whatever the frontend is).   The query `spack find platform=bgq` should work to filter out the results from other platforms - can you test that?

> Would be better to say mytestpkgA not installed for arch xxx?

I think `spack load` needs to be smart about getting the `arch` string into the module it loads.  It may be doing too general a query to find the right modules.  I'm a little confused about the `xxxx` output above -- are you actually seeing `xxxx` in your output?

**Comment by pramodk** [comment]
>spack find platform=bgq should work to filter out the results from other platforms 

yes, thats working as expected.

>  I'm a little confused about the xxxx output above 

that was just my `poor` attempt to say that there should not be module load error (but `at least` something like package not installed for architecture). But I agree that using `arch` string for `module load` would be useful.

**Comment by alalazo** [comment]
@pramodk can this issue be closed or there's something that still needs an answer / some work to be fixed?

**Comment by pramodk** [comment]
I am now using `install_tree` and `module_roots` on `config.yaml`. All looks fine.
