### ISSUE TITLE
Spack not looking for virtual dependencies in custom repositories

### ISSUE THREAD

**Issue by amaji** [LLNL/spack#22589]
I needed to apply a patch to libtirpc package to export `$prefix/include/tirpc` in CPATH. So, I copied it to a custom repository and edited it. Here is my `repos.yaml`
```
repos:
- /scratch/mack8/a/amaji/custom_packages
- $spack/var/spack/repos/builtin
```
Now if I do `spack spec -l libtirpc` things work fine. I can also install libtirpc.
```
$ spack spec -l libtirpc %gcc@8.3.1
Input spec
--------------------------------
libtirpc%gcc@8.3.1

Concretized
--------------------------------
==> Warning: Skipping package at /scratch/mack8/a/amaji/spack-test-20210324/framework/spack/var/spack/repos/builtin/packages/libtirpc.bak. "libtirpc.bak" is not a valid Spack module name.
==> Warning: gcc@8.3.1 cannot build optimized binaries for "zen2". Using best target possible: "zen"
gxkfhga  libtirpc@1.2.6%gcc@8.3.1 arch=linux-centos8-zen
yzhsri5      ^krb5@1.18.2%gcc@8.3.1 arch=linux-centos8-zen
tprtgu6          ^bison@3.6.4%gcc@8.3.1 arch=linux-centos8-zen
ujpucgt              ^diffutils@3.7%gcc@8.3.1 arch=linux-centos8-zen
qbonzhy                  ^libiconv@1.16%gcc@8.3.1 arch=linux-centos8-zen
qceagpt              ^help2man@1.47.11%gcc@8.3.1 arch=linux-centos8-zen
6m52oox                  ^gettext@0.21%gcc@8.3.1+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-centos8-zen
ygtt2p3                      ^bzip2@1.0.8%gcc@8.3.1+shared arch=linux-centos8-zen
6cnl654                      ^libxml2@2.9.10%gcc@8.3.1~python arch=linux-centos8-zen
m5xrq75                          ^pkgconf@1.7.3%gcc@8.3.1 arch=linux-centos8-zen
n7lawhk                          ^xz@5.2.5%gcc@8.3.1~pic arch=linux-centos8-zen
3jwt5sg                          ^zlib@1.2.11%gcc@8.3.1+optimize+pic+shared arch=linux-centos8-zen
2c2b4et                      ^ncurses@6.2%gcc@8.3.1~symlinks+termlib arch=linux-centos8-zen
dcky6it                      ^tar@1.32%gcc@8.3.1 arch=linux-centos8-zen
744u27d                  ^perl@5.32.0%gcc@8.3.1+cpanm+shared+threads arch=linux-centos8-zen
gtaesiu                      ^berkeley-db@18.1.40%gcc@8.3.1 arch=linux-centos8-zen
7mja3it                      ^gdbm@1.18.1%gcc@8.3.1 arch=linux-centos8-zen
42k4c76                          ^readline@8.0%gcc@8.3.1 arch=linux-centos8-zen
bvdpqvw              ^m4@1.4.18%gcc@8.3.1+sigsegv patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 arch=linux-centos8-zen
wwnsges                  ^libsigsegv@2.12%gcc@8.3.1 arch=linux-centos8-zen
ornw2fp          ^openssl@1.1.1d%gcc@8.3.1+systemcerts arch=linux-centos8-zen
```
But if I try to install `hdf` which depends on `libtirpc`:
```
$ spack spec -l hdf %gcc@8.3.1
Input spec
--------------------------------
hdf%gcc@8.3.1

Concretized
--------------------------------
==> Warning: Skipping package at /scratch/mack8/a/amaji/spack-test-20210324/framework/spack/var/spack/repos/builtin/packages/libtirpc.bak. "libtirpc.bak" is not a valid Spack module name.
==> Warning: gcc@8.3.1 cannot build optimized binaries for "zen2". Using best target possible: "zen"
==> Error: Package 'libtirpc' not found.
```

Am I missing something or is Spack losing track of custom repos when installing dependencies?

Expected behavior: `hdf` package should be coming from `builtin` and `libtirpc` package should be coming from `custom_packages`.

**Comment by amaji** [comment]
I have already tried `spack clean -a` couple of times.

**Comment by amaji** [comment]
One more data point.

This seems to be originating from the dependency on the virtual package `rpc`. If I explicitly add a dependency then things work.

```
$ spack spec -l hdf %gcc@8.3.1 ^libtirpc
Input spec
--------------------------------
hdf%gcc@8.3.1
    ^libtirpc

Concretized
--------------------------------
==> Warning: Skipping package at /scratch/mack8/a/amaji/spack-test-20210324/framework/spack/var/spack/repos/builtin/packages/libtirpc.bak. "libtirpc.bak" is not a valid Spack module name.
==> Warning: gcc@8.3.1 cannot build optimized binaries for "zen2". Using best target possible: "zen"
fr3xbhm  hdf@4.2.15%gcc@8.3.1+external-xdr+fortran~java~netcdf+pic~shared+szip arch=linux-centos8-zen
tprtgu6      ^bison@3.6.4%gcc@8.3.1 arch=linux-centos8-zen
ujpucgt          ^diffutils@3.7%gcc@8.3.1 arch=linux-centos8-zen
qbonzhy              ^libiconv@1.16%gcc@8.3.1 arch=linux-centos8-zen
qceagpt          ^help2man@1.47.11%gcc@8.3.1 arch=linux-centos8-zen
6m52oox              ^gettext@0.21%gcc@8.3.1+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-centos8-zen
ygtt2p3                  ^bzip2@1.0.8%gcc@8.3.1+shared arch=linux-centos8-zen
6cnl654                  ^libxml2@2.9.10%gcc@8.3.1~python arch=linux-centos8-zen
m5xrq75                      ^pkgconf@1.7.3%gcc@8.3.1 arch=linux-centos8-zen
n7lawhk                      ^xz@5.2.5%gcc@8.3.1~pic arch=linux-centos8-zen
3jwt5sg                      ^zlib@1.2.11%gcc@8.3.1+optimize+pic+shared arch=linux-centos8-zen
2c2b4et                  ^ncurses@6.2%gcc@8.3.1~symlinks+termlib arch=linux-centos8-zen
dcky6it                  ^tar@1.32%gcc@8.3.1 arch=linux-centos8-zen
744u27d              ^perl@5.32.0%gcc@8.3.1+cpanm+shared+threads arch=linux-centos8-zen
gtaesiu                  ^berkeley-db@18.1.40%gcc@8.3.1 arch=linux-centos8-zen
7mja3it                  ^gdbm@1.18.1%gcc@8.3.1 arch=linux-centos8-zen
42k4c76                      ^readline@8.0%gcc@8.3.1 arch=linux-centos8-zen
bvdpqvw          ^m4@1.4.18%gcc@8.3.1+sigsegv patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 arch=linux-centos8-zen
wwnsges              ^libsigsegv@2.12%gcc@8.3.1 arch=linux-centos8-zen
cykiduy      ^flex@2.6.4%gcc@8.3.1+lex patches=09c22e5c6fef327d3e48eb23f0d610dcd3a35ab9207f12e0f875701c677978d3 arch=linux-centos8-zen
rwczjj7          ^autoconf@2.69%gcc@8.3.1 arch=linux-centos8-zen
aua5o3p          ^automake@1.16.2%gcc@8.3.1 arch=linux-centos8-zen
a4na2ex          ^findutils@4.6.0%gcc@8.3.1 patches=84b916c0bf8c51b7e7b28417692f0ad3e7030d1f3c248ba77c42ede5c1c5d11e,bd9e4e5cc280f9753ae14956c4e4aa17fe7a210f55dd6c84aa60b12d106d47a2 arch=linux-centos8-zen
vuyp5vl              ^libtool@2.4.6%gcc@8.3.1 arch=linux-centos8-zen
lqksjlu              ^texinfo@6.5%gcc@8.3.1 patches=12f6edb0c6b270b8c8dba2ce17998c580db01182d871ee32b7b6e4129bd1d23a,1732115f651cff98989cb0215d8f64da5e0f7911ebf0c13b064920f088f2ffe1 arch=linux-centos8-zen
v7qlthv      ^libjpeg-turbo@2.0.4%gcc@8.3.1 arch=linux-centos8-zen
64enbci          ^cmake@3.18.4%gcc@8.3.1~doc+ncurses+openssl+ownlibs~qt patches=bf695e3febb222da2ed94b3beea600650e4318975da90e4a71d6f31a6d5d8c3d arch=linux-centos8-zen
ornw2fp              ^openssl@1.1.1d%gcc@8.3.1+systemcerts arch=linux-centos8-zen
uj27ok4          ^nasm@2.15.05%gcc@8.3.1 arch=linux-centos8-zen
525betb      ^libszip@2.1.1%gcc@8.3.1 arch=linux-centos8-zen
gxkfhga      ^libtirpc@1.2.6%gcc@8.3.1 arch=linux-centos8-zen
yzhsri5          ^krb5@1.18.2%gcc@8.3.1 arch=linux-centos8-zen
```

**Comment by scheibelp** [comment]
I can replicate this for other packages, for example I can create a test repo with `openmpi` and add the repo, in which case `spack spec -N py-mpi4py` does not use `test.openmpi` (but `spack spec -N py-mpi4py ^openmpi` does).

I'm guessing in your case you tried removing `libtirpc` from the original repo to try to force Spack to use the one in your custom repo, which lead to the "not found" error (in my case, I just see Spack using the package instance from the wrong repo).

**Comment by amaji** [comment]
@scheibelp Precisely. I first tried with `libtirpc` in both repos, but Spack always picked the one in builtin. So, I thought it was a cache issue and removed the one in builtin.

Glad to hear that you can replicate it. Thought I was going insane. :)

**Comment by scheibelp** [comment]
I am adding the `workaround` tag since you mentioned a manual solution in https://github.com/spack/spack/issues/22589#issuecomment-808605712, but I will be looking into how to make this automatic in Spack over the next couple days.

**Comment by amaji** [comment]
Sounds good. I am not in a hurry. Right now, I am just dropping the edit inside builtin.

Would be nice to have this fixed in 16.2 or 17.



-------- Original message --------
From: Peter Scheibel ***@***.***>
Date: 3/29/21 6:13 PM (GMT-05:00)
To: spack/spack ***@***.***>
Cc: "Maji, Amiya K" ***@***.***>, Author ***@***.***>
Subject: Re: [spack/spack] Spack not looking for virtual dependencies in custom repositories (#22589)


I am adding the workaround tag since you mentioned a manual solution in #22589 (comment)<https://github.com/spack/spack/issues/22589#issuecomment-808605712>, but I will be looking into how to make this automatic in Spack over the next couple days.

**Comment by tgamblin** [comment]
Just to follow up on our conversation today (and to get notifications): @scheibelp can you verify whether this works with the new concretizer?  We can fix it there.

**Comment by scheibelp** [comment]
@tgamblin the new concretizer fixes this problem, should we make a tag like `fixed-by-new-concretizer`?

**Comment by amaji** [comment]
Don't know if this is the right place to ask.

If not done already, can you guys please please make Spack's bootstrap store customizable? 
I am currently avoiding using Clingo because I have a shared home directory across clusters and don't want things to get weird.

**Comment by tgamblin** [comment]
@scheibelp: yep let’s make a tag

@amaji: have you seen things get weird with the bootstrap store? It should (like the regular store) keep things separate by architecture/os/etc.

**Comment by amaji** [comment]
@tgamblin thanks! I haven't spent much time with clingo. tried building it manually and use in spack, but that didn't go well. maybe i'll give it another try over next few weeks.

in general, i avoid `~/.spack` scope for site-wide installations. that way every staff gets identical spack behavior (concretization/modules etc.) when deploying things.

**Comment by tgamblin** [comment]
@alalazo: see above — I think @amaji raises a good point. We should allow admins to install clingo in some standard way in their site spack so users don’t have to.

**Comment by alalazo** [comment]
@tgamblin @amaji If I am not missing something, I think adding:
```yaml
config:
    bootstrap_tree:
```
which behaves similarly to `install_tree` would be sufficient for this use case. What do you think?

**Comment by tgamblin** [comment]
Thanks @alalazo -- sorry for missing this.

**Comment by alalazo** [comment]
@amaji I don't think we'll try to fix this (or any other bug) for the original concretizer. I would be inclined to close this issue, but wanted to check first if you still have problems with clingo.

**Comment by alalazo** [comment]
> If not done already, can you guys please please make Spack's bootstrap store customizable?

Spack bootstrap store is customizable using:
```console
$ spack bootstrap root <new-path>
```

I'm closing this issue, but feel free to reopen if you think something is still missing.

**Comment by amaji** [comment]
Thanks @alalazo! I am using explicit dependencies for now.
Re: Clingo: I'll see if I can test it soon.
