### ISSUE TITLE
Is there a version of cap3 that supports the aarch architecture?

### ISSUE THREAD

**Issue by simon28li** [LLNL/spack#22595]
### Steps to reproduce the issue

```console
$ spack install cap3
$ spack cd -i cap3
$ cd bin && ./cap3

```

### Error Message

```console
[root@localhost bin]# ./cap3
-bash: ./cap3: cannot execute binary file: Exec format error
[root@localhost bin]# file cap3
cap3: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.18, BuildID[sha1]=0a86e6c2fe1f9cf0c700f71c4583e20d3dbed475, not stripped
```

### Information on your system

```
spack debug report
```
```
* **Spack:** 0.16.0-1376-f65e6ae4e6
* **Python:** 3.6.8
* **Platform:** linux-centos8-aarch64
* **Concretizer:** original
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

@akthoma @adamjstewart Is there a version of cap3 that supports the aarch architecture?
I checked the hompage page and there seems to be no version supporting aarch. Can you confirm this?

**Comment by adamjstewart** [comment]
You're probably better off contacting the developers directly, I don't know anything about cap3.

**Comment by nightlark** [comment]
@simon28li the README from the download for cap3 has a bit of contact info: `For questions on CAP3, please contact Xiaoqiu Huang at xqhuang@cs.iastate.edu`

From the download page on the CAP3 website (http://seq.cs.iastate.edu/cap3.html) and download directory listing at http://seq.cs.iastate.edu/CAP3/ it looks like there is nothing for aarch64. It doesn't look like source code is provided either, so getting in touch with one of the people that made CAP3 is likely to be the best option; the only alternative that comes to mind if the author doesn't respond would be using an emulator like qemu to run one of the x86 cap3 binaries, but that could run much slower than a native aarch64 version and could be difficult to get working.

**Comment by alalazo** [comment]
Closing since the questions seem to be answered. Feel free to reopen if something is still missing.
