### ISSUE TITLE
ROCM Concretization: hip-rocclr requires hsakmt-roct version 4.0.0, but spec asked for 4.1.0

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#22597]
I'm seeing this with all the `+rocm` variants I'm interested in:

Using `spack@develop` (cc0b3017ea55e7e235dfd2c7a4506d0ba2348e04 from `Sat Mar 27 09:29:51 2021 -0400`):

```
$> spack spec umpire+rocm amdgpu_target=gfx906
Input spec
--------------------------------
 -   umpire+rocm amdgpu_target=gfx906

Concretized
--------------------------------
==> Error: An unsatisfiable version constraint has been detected for spec:

    hsakmt-roct@4.1.0
...
while trying to concretize the partial spec:

    hip-rocclr@4.0.0
...
hip-rocclr requires hsakmt-roct version 4.0.0, but spec asked for 4.1.0
```

Same concretization complaints with:
* `strumpack~slate+rocm amdgpu_target=gfx906`
* `raja+rocm~openmp amdgpu_target=gfx906`
* `kokkos+rocm amdgpu_target=gfx906`

I don't think this is new, but I'm just now running into it as I normally specify my specs with an explicit `^hip@4.0.0` (which works).

@srekolam @arjun-raj-kuppala @tgamblin

**Comment by tgamblin** [comment]
Old or new concretizer?

**Comment by eugeneswalker** [comment]
> Old or new concretizer?

old

**Comment by tgamblin** [comment]
Is there a reason you can’t use the new one? Ideally we’d be able to fix this in the new concretizer.

**Comment by eugeneswalker** [comment]
> Is there a reason you can’t use the new one? Ideally we’d be able to fix this in the new concretizer.

I can use the new concretizer. Should I close this issue? Is the plan to deprecate the old concretizer soon?

**Comment by tgamblin** [comment]
> Is the plan to deprecate the old concretizer soon?

It'll be deprecated or gone in 0.17, and the new one will be default.

**Comment by srekolam** [comment]
@eugeneswalker  , can you please let me know if this is still an issue else, can we close this ?

**Comment by haampie** [comment]
We can close this, the new concretizer should take care of it and is the default (otherwise feel free to reopen)
