### ISSUE TITLE
Informations about debug mode in paraview

### ISSUE THREAD

**Issue by Billae** [LLNL/spack#22632]
Hello

I am on a paraview plugin project and I need to debug it and find memory leaks. I was wondering if there is any debug variant or options which set all debug flags. I am not aware about all debug flag paraview provides, but for example, I have seen the "VTK_DEBUG_LEAKS" flag (which is by default to OFF), but I cannot use it without modify the spack recipe. Is there an installation option with spack to have all the debug features ?

@chuckatkins , @danlipsa , @vicentebolea, have you an idea ?

Thanks,
Eloïse

**Comment by danlipsa** [comment]
There is a build_type=Debug but it does not add VTK_DEBUG_LEAKS flag. I would be open to review a PR that adds a variant for this flag or you can compile ParaView from source or use the ParaView superbuild and add any flags you want.

**Comment by vicentebolea** [comment]
@danlipsa I second the idea of having a `debug variant or options which set all debug flags` maybe summarizing all of the possible `paraview/vtk(m)/cmake` debug flag might be overkill but we can do this incrementally.

**Comment by Billae** [comment]
So the debug variant will set the build_type to debug and add other debug flags ? Which ones ?

Having one debug variant to activate seems cleaner than having the build_type variant and the vtkdebugleak variant and so on.. :)

Eloïse

**Comment by Billae** [comment]
I have PR a first version for debug variant : #22900

But one fact annoyed me: in spack, the cmake build_type is a variant and I have not find how to recursively set variants. That means when i set the debug variant to True, even if the cmake build type is is given to cmake, the spack build_type variant is still in "Rel_with_debug" mode.

Have you an idea ?
