### ISSUE TITLE
The 【spack cd】 does not work in the latest spack version

### ISSUE THREAD

**Issue by Tom-python0121** [LLNL/spack#22738]
### Steps to reproduce the issue

```console
[root@centos8 ~]# spack -V
0.16.1-2002-09dcb16a70
[root@centos8 ~]# spack cd gperf
[root@centos8 ~]#
```
When I updated the spack version and installed the gperf software, then executed the **spack cd gperf** and found that nothing worked, I wondered when the bug would be fixed.

### Information on your system
[root@centos8 ~]# spack debug report
* **Spack:** 0.16.1-2002-09dcb16a70
* **Python:** 3.6.8
* **Platform:** linux-centos8-aarch64
* **Concretizer:** original

### Additional information

- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
@haampie @alalazo #22321 seems to have introduced an unexpected behavior change.

### After

```console
$ cd ~/spack
$ git checkout 8b16728fd97ad063623a26db1d89ac01c5bc706e
$ spack stage zlib
$ spack location zlib
$ echo $?
0
$ spack cd zlib
$ echo $?
1
$ pwd
/Users/Adam/spack
```

### Before

```console
$ git checkout HEAD~1
$ spack location zlib
/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-zlib-1.2.11-x2anksgssxsxa7pcnhzg5k3dhgacglze/spack-src
$ spack cd zlib
$ echo $?
0
$ pwd
/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-zlib-1.2.11-x2anksgssxsxa7pcnhzg5k3dhgacglze/spack-src
```

Easy workaround until this gets fixed:
```console
$ spack location --source-dir zlib
/var/folders/21/hwq39zyj4g36x6zjfyl5l8080000gn/T/Adam/spack-stage/spack-stage-zlib-1.2.11-x2anksgssxsxa7pcnhzg5k3dhgacglze/spack-src
$ spack cd --source-dir zlib
```

**Comment by haampie** [comment]
thanks, that behavior wasn't tested. See #22755
