### ISSUE TITLE
Installation issue: py-numpy @power9le

### ISSUE THREAD

**Issue by ax3l** [LLNL/spack#22759]
### Steps to reproduce the issue

On Summit, with a fresh clone of Spack as of yesterday (2ae7e2550175fb6decfc9bc9d4af5c47b881413e):

```console
$ spack install py-numpy
...
numpy/core/src/common/simd/vsx/operators.h:133:29: error: implicit declaration of function 
             'vec_cmpne' [-Werror=implicit-function-declaration]
...
numpy/core/src/_simd/_simd.dispatch.c.src:314:1: error: AltiVec argument passed to unprotot
             yped function
...
```

### Information on your system

Summit at OLCF using the `gcc/6.4.0` and `python/3.7.0` modules.

```console
$ spack spec py-numpy               
Input spec
--------------------------------
py-numpy

Concretized
--------------------------------
py-numpy@1.20.2%gcc@6.4.0+blas+lapack patches=873745d7b547857fcfec9cae90b09c133b42a4f0c23b6c2d84cf37e2dd816604 arch=linux-rhel7-power9le
    ^openblas@0.3.14%gcc@6.4.0~bignuma~consistent_fpcsr~ilp64+locking+pic+shared threads=none arch=linux-rhel7-power9le
        ^perl@5.32.1%gcc@6.4.0+cpanm+shared+threads arch=linux-rhel7-power9le
            ^berkeley-db@18.1.40%gcc@6.4.0~docs patches=b231fcc4d5cff05e5c3a4814f6a5af0e9a966428dc2176540d2c05aff41de522 arch=linux-rhel7-power9le
            ^gdbm@1.19%gcc@6.4.0 arch=linux-rhel7-power9le
                ^readline@8.1%gcc@6.4.0 arch=linux-rhel7-power9le
                    ^ncurses@6.2%gcc@6.4.0~symlinks+termlib abi=none arch=linux-rhel7-power9le
                        ^pkgconf@1.7.4%gcc@6.4.0 arch=linux-rhel7-power9le
    ^py-cython@0.29.22%gcc@6.4.0 arch=linux-rhel7-power9le
        ^py-setuptools@50.3.2%gcc@6.4.0 arch=linux-rhel7-power9le
            ^python@3.8.8%gcc@6.4.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87 arch=linux-rhel7-power9le
                ^bzip2@1.0.8%gcc@6.4.0+shared arch=linux-rhel7-power9le
                    ^diffutils@3.7%gcc@6.4.0 arch=linux-rhel7-power9le
                        ^libiconv@1.16%gcc@6.4.0 arch=linux-rhel7-power9le
                ^expat@2.2.10%gcc@6.4.0+libbsd arch=linux-rhel7-power9le
                    ^libbsd@0.10.0%gcc@6.4.0 arch=linux-rhel7-power9le
                ^gettext@0.21%gcc@6.4.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-rhel7-power9le
                    ^libxml2@2.9.10%gcc@6.4.0~python arch=linux-rhel7-power9le
                        ^xz@5.2.5%gcc@6.4.0~pic arch=linux-rhel7-power9le
                        ^zlib@1.2.11%gcc@6.4.0+optimize+pic+shared arch=linux-rhel7-power9le
                    ^tar@1.34%gcc@6.4.0 arch=linux-rhel7-power9le
                ^libffi@3.3%gcc@6.4.0 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0 arch=linux-rhel7-power9le
                ^openssl@1.1.1k%gcc@6.4.0~docs+systemcerts arch=linux-rhel7-power9le
                ^sqlite@3.35.3%gcc@6.4.0+column_metadata+fts~functions~rtree arch=linux-rhel7-power9le
                ^util-linux-uuid@2.36.2%gcc@6.4.0 arch=linux-rhel7-power9le
```

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/6250828/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/6250829/spack-build-env.txt)

### General information

* **Spack:** 0.16.1-2016-2ae7e25
* **Python:** 3.7.0
* **Platform:** linux-rhel7-power9le
* **Concretizer:** original

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and mentioned @adamjstewart
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
`-march=native` isn't being added by the Spack package, right? I assume that's coming from the build system. As a first pass, we can hopefully just `s/-march=native/-mcpu=native` somewhere in the source code. But I would love to get something more general contributed upstream. Are you able to reproduce this bug without Spack? If so, open an issue on the numpy repo and ping me.

**Comment by ax3l** [comment]
Oh, I realized that I quoted the wrong line. That one is only a test in the config phase that fails, the actual error during build is:
```
numpy/core/src/common/simd/vsx/operators.h:133:29: error: implicit declaration of function 
             'vec_cmpne' [-Werror=implicit-function-declaration]
...
numpy/core/src/_simd/_simd.dispatch.c.src:314:1: error: AltiVec argument passed to unprotot
             yped function
...
error: Command "/autofs/nccs-svm1_sw/summit/modulefiles/ums/aph114/spack-test/spack/lib/spa
             ck/env/gcc/gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -fPIC 
             -DNPY_INTERNAL_BUILD=1 -DHAVE_NPY_CONFIG_H=1 -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE=1 -
             D_LARGEFILE64_SOURCE=1 -Ibuild/src.linux-ppc64le-3.8/numpy/core/src/_simd -Inumpy/core/incl
             ude -Ibuild/src.linux-ppc64le-3.8/numpy/core/include/numpy -Ibuild/src.linux-ppc64le-3.8/nu
             mpy/distutils/include -Inumpy/core/src/common -Inumpy/core/src -Inumpy/core -Inumpy/core/sr
             c/npymath -Inumpy/core/src/multiarray -Inumpy/core/src/umath -Inumpy/core/src/npysort -Inum
             py/core/src/_simd -I/autofs/nccs-svm1_sw/summit/modulefiles/ums/aph114/spack-test/spack/opt
             /spack/linux-rhel7-power9le/gcc-6.4.0/python-3.8.8-7vlbefus6xoopzgts4ipm5s7weejy2t5/include
             /python3.8 -Ibuild/src.linux-ppc64le-3.8/numpy/core/src/common -Ibuild/src.linux-ppc64le-3.
             8/numpy/core/src/npymath -c build/src.linux-ppc64le-3.8/numpy/core/src/_simd/_simd.dispatch
             .vsx3.c -o build/temp.linux-ppc64le-3.8/build/src.linux-ppc64le-3.8/numpy/core/src/_simd/_s
             imd.dispatch.vsx3.o -MMD -MF build/temp.linux-ppc64le-3.8/build/src.linux-ppc64le-3.8/numpy
             /core/src/_simd/_simd.dispatch.vsx3.o.d -Werror -mcpu=power9 -mtune=power9" failed with exi
             t status 1
```

There is even a `-Werror` lurking in there :scream: 

I did a quick build from source with `python setup.py build` and the dependencies (cython, openblas) loaded and that one succeeded.

**Comment by adamjstewart** [comment]
I guess I would start by trying to disable things in the package to see which one makes the difference. We set `NPY_BLAS_ORDER` and `NPY_LAPACK_ORDER` to force it to choose a particular lib, pass specific linking flags depending on the lib, and sometimes add `self.compiler.c99_flag` depending on the compiler version. There are also a few patches you can try disabling.

**Comment by adamjstewart** [comment]
Is this still an issue on develop? There have been several new numpy releases since then.

**Comment by adamjstewart** [comment]
@rgommers going through old numpy issues and found this, unclear if it's still an issue with newer numpy releases though.

**Comment by rgommers** [comment]
This may still be an issue, it's fairly recent and there's not all that much work on VSX-specific SIMD as far as I know. I can't test though. Agreed this looks like a NumPy bug, not a Spack-specific one.

**Comment by adamjstewart** [comment]
@ax3l can you open an issue in the numpy repo?

**Comment by ax3l** [comment]
I thought I opened one last year and they fixed my power issues:
https://github.com/numpy/numpy/issues/19017

**Comment by ax3l** [comment]
I would close this issue here.
If someone sees new issues with numpy on Power9: Livermore people can test on Lassen & Sierra if all is well and OLCF people can test on Summit :)

**Comment by adamjstewart** [comment]
Awesome! You can add a conflict to the package if you want to signify that old versions won't work on ppc with old GCC.
