### ISSUE TITLE
Fix hip lib amdhip64

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#22768]
### Steps to reproduce the issue

hip@4.1.0 generates a lib name with a dash in the end because cmake can't infer the version number from a tarbal (it assumes git). This can lead to linker errors.

There's already a patch for it but it might have to be rebased.

```
path/to/hip/lib $ ls
cmake  hip_prof_str.h  libamdhip64.so  libamdhip64.so.4  libamdhip64.so.4.1.21134-
```

Currently the patch is only applied to 4.0.0 and below:

```python
patch('0003-Improve-compilation-without-git-repo.3.10.0.patch', when='@3.10.0:4.0.0')
```

**Comment by srekolam** [comment]
fixed with #22762
