### ISSUE TITLE
Package for oneAPI VTune

### ISSUE THREAD

**Issue by rscohn2** [LLNL/spack#22805]
Add a package for VTune

_Originally posted by @rscohn2 in https://github.com/spack/spack/issues/20403#issuecomment-814079607_

Some parts of the VTune installer require sudo to install the driver and would create root-owed files in spack managed files. I see that that the parallel studio spack package allowed installing vtune. Is the driver install optional? Is that useful?

**Comment by rscohn2** [comment]
@DanVev: Could you look into this? We could just provide the user mode install

FYI: @scheibelp Another need to support sudo install: https://github.com/spack/spack/issues/22178#issuecomment-794463319

**Comment by vdanilin** [comment]
@rscohn2 user-mode installation is possible for oneAPI VTune though driver installation is skipped in this case.
I've re-addressed the question about functionality to the VTune team, waiting for a reply.

**Comment by vdanilin** [comment]
I've received a response from VTune team. 
oneAPI Vtune can be used without driver installation in Perf driverless mode: https://software.intel.com/content/www/us/en/develop/documentation/vtune-cookbook/top/configuration-recipes/profiling-hardware-without-sampling-drivers.html 
So user installation makes sense, optionally user can manually install drivers, explained here: https://software.intel.com/content/www/us/en/develop/documentation/vtune-help/top/set-up-analysis-target/linux-targets/building-and-installing-the-sampling-drivers-for-linux-targets.html

**Comment by rscohn2** [comment]
Could you try making a package? The doc string for the class is used as the
description and should note the limitations compared to the full install.

**Comment by vdanilin** [comment]
ok, I'll add a  task to the backlog.

**Comment by rscohn2** [comment]
@vdanilin added the package: #25311
