### ISSUE TITLE
How to name versions of JDK

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#2284]
JDK has a fairly complicated versioning scheme:
http://www.oracle.com/technetwork/java/javase/8u92-relnotes-2949471.html

The latest release can be described as:

1. JDK 8, Update 92, Build 14
2. 8u92
3. 1.8.0_92-b14

We are currently using format 2, although 3 is more in line with how other software is versioned. Does anyone mind if I change things to 3? I would update the packages that depend on it too.

**Comment by davydden** [comment]
(3) LGTM

**Comment by citibeth** [comment]
Can our current version parser parse that?  How about 1.8.0.92.14?

A bigger problem --- and I believe a legal necessity before 0.10 is released --- is to remove the auto-accept of Oracle's license agreement:

https://github.com/LLNL/spack/pull/1298

**Comment by davydden** [comment]
> Can our current version parser parse that? 

I am almost sure it can, it will split whatever you give to it into alphabetical and numeric segments using `segment_regex = r'[a-zA-Z]+|[0-9]+'`.

@adamjstewart : if you wish, you can add a unit test with `1.8.0_92-b14` to confirm the split by calling, for example,  `dotted` method on the instance of `Version` class.

**Comment by citibeth** [comment]
I think it will parse '1.8.0_92-b14' into (1,8,0,92,b,14)

**Comment by davydden** [comment]
> I think it will parse '1.8.0_92-b14' into (1,8,0,92,b,14)

... and when you do `dotted` method you will get `1.8.0.92.b.14`, right? ;-)
