### ISSUE TITLE
Want to build OpenBLAS without Fortran compiler

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#22875]
I want to build without Fortran compiler. Currently, OpenBLAS is the hold-up because it requires a Fortran compiler. A comment there says "As of 06/2016 there is no mechanism to specify that packages which depends on Blas/Lapack need C or/and Fortran symbols. For now require both."

Could we introduce such a mechanism? For example, there could be virtual packages `lapack-c` and `lapack-fortran` which would not require the other language. The current `lapack` virtual package would imply it needs both C and Fortran.

**Comment by climbfuji** [comment]
@eschnett I think this has been addressed, there is now a Fortran variant for the package.
