### ISSUE TITLE
Not super consistent dependency resolution

### ISSUE THREAD

**Issue by maxim-belkin** [LLNL/spack#22871]
The result of `spack spec` is not super consistent and depends on the flags used. This makes debugging lengthy build failures (e.g., `py-torch`) difficult...

### Steps to reproduce the issue

```console
$ spack spec    gettext@0.21%gcc@5.3.0 arch=cray-suse_linux11-bulldozer
$ spack spec -I gettext@0.21%gcc@5.3.0 arch=cray-suse_linux11-bulldozer
$ spack --debug --stacktrace spec    gettext@0.21%gcc@5.3.0 arch=cray-suse_linux11-bulldozer
$ spack --debug --stacktrace spec -I gettext@0.21%gcc@5.3.0 arch=cray-suse_linux11-bulldozer
```

1. `spack spec ...` command resolves `diffutils` and `ncurses` to `arch=cray-cnl5-bulldozer`:
    <details>
    <summary><code>spack spec gettext@0.21%gcc@5.3.0 arch=cray-suse_linux11-bulldozer</code></summary>

    <pre>
    <code>
    Input spec
    --------------------------------
    gettext@0.21%gcc@5.3.0 arch=cray-suse_linux11-bulldozer

    Concretized
    --------------------------------
    ==> Warning: Intel's compilers may or may not optimize to the same degree for non-Intel microprocessors for optimizations that are not unique to Intel microprocessors
    gettext@0.21%gcc@5.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=cray-suse_linux11-bulldozer
        ^bzip2@1.0.8%gcc@5.3.0+shared arch=cray-suse_linux11-bulldozer
            ^diffutils@3.7%gcc@5.3.0 <strong>arch=cray-cnl5-bulldozer</strong>
                ^libiconv@1.16%gcc@5.3.0 arch=cray-suse_linux11-bulldozer
        ^libxml2@2.9.10%gcc@5.3.0~python arch=cray-suse_linux11-bulldozer
            ^pkgconf@1.7.4%gcc@5.3.0 arch=cray-suse_linux11-bulldozer
            ^xz@5.2.5%gcc@5.3.0~pic arch=cray-suse_linux11-bulldozer
            ^zlib@1.2.11%gcc@5.3.0+optimize+pic+shared arch=cray-suse_linux11-bulldozer
        ^ncurses@6.2%gcc@5.3.0~symlinks+termlib abi=none <strong>arch=cray-cnl5-bulldozer</strong>
        ^tar@1.34%gcc@5.3.0 arch=cray-suse_linux11-bulldozer
    </code>
    </pre>
    </details>

2. `spack spec -I ...` command resolves `bzip2`, `libiconv`, `xz`, `zlib`, and `ncurses` to `arch=cray-cnl5-bulldozer`:

    <details>
    <summary>
    <code>spack spec -I gettext@0.21%gcc@5.3.0 arch=cray-suse_linux11-bulldozer</code>
    </summary>

    <pre>
    <code>
    Input spec
    --------------------------------
    -   gettext@0.21%gcc@5.3.0 arch=cray-suse_linux11-bulldozer

    Concretized
    --------------------------------
    ==> Warning: Intel's compilers may or may not optimize to the same degree for non-Intel microprocessors for optimizations that are not unique to Intel microprocessors
    -   gettext@0.21%gcc@5.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=cray-suse_linux11-bulldozer
    [+]      ^bzip2@1.0.8%gcc@5.3.0+shared <strong>arch=cray-cnl5-bulldozer</strong>
    [+]          ^diffutils@3.7%gcc@5.3.0 arch=cray-suse_linux11-bulldozer
    [+]              ^libiconv@1.16%gcc@5.3.0 <strong>arch=cray-cnl5-bulldozer</strong>
    -       ^libxml2@2.9.10%gcc@5.3.0~python arch=cray-suse_linux11-bulldozer
    [+]          ^pkgconf@1.7.4%gcc@5.3.0 arch=cray-suse_linux11-bulldozer
    [+]          ^xz@5.2.5%gcc@5.3.0~pic <strong>arch=cray-cnl5-bulldozer</strong>
    [+]          ^zlib@1.2.11%gcc@5.3.0+optimize+pic+shared <strong>arch=cray-cnl5-bulldozer</strong>
    [+]      ^ncurses@6.2%gcc@5.3.0~symlinks+termlib abi=none <strong>arch=cray-cnl5-bulldozer</strong>
    [+]      ^tar@1.34%gcc@5.3.0 arch=cray-suse_linux11-bulldozer
    </code>
    </pre>
    </details>

3. `spack --debug --stacktrace spec` command resolves `bzip2`, `libiconv`,`pkgconf`, `zlib`, and `ncurses` to `arch=cray-cnl5-bulldozer`:
    <details>
    <summary>
    <code>spack --debug --stacktrace spec gettext@0.21%gcc@5.3.0 arch=cray-suse_linux11-bulldozer</code>
    </summary>

    <pre>
    <code>lib/spack/spack/util/executable.py:188 ==> [2021-04-08-10:54:00.287407] '/bin/bash' '--norc' '--noprofile' '-lc' 'echo $CRAY_CPU_TARGET'
    lib/spack/spack/platforms/cray.py:154 ==> [2021-04-08-10:54:00.306459] default to front-end architecture
    lib/spack/spack/cmd/__init__.py:122 ==> [2021-04-08-10:54:00.466622] Imported spec from built-in commands
    lib/spack/spack/cmd/__init__.py:122 ==> [2021-04-08-10:54:00.468600] Imported spec from built-in commands
    Input spec
    --------------------------------
    gettext@0.21%gcc@5.3.0 arch=cray-suse_linux11-bulldozer
    
    Concretized
    --------------------------------
    lib/spack/spack/config.py:981 ==> [2021-04-08-10:54:00.475995] Reading config file /dev/shm/spack/test/etc/spack/defaults/config.yaml
    lib/spack/spack/config.py:981 ==> [2021-04-08-10:54:00.550154] Reading config file /dev/shm/spack/test/etc/spack/config.yaml
    lib/spack/spack/config.py:981 ==> [2021-04-08-10:54:00.559828] Reading config file /u/staff/mbelkin/.spack/config.yaml
    lib/spack/spack/config.py:981 ==> [2021-04-08-10:54:01.539299] Reading config file /dev/shm/spack/test/etc/spack/defaults/repos.yaml
    lib/spack/spack/config.py:981 ==> [2021-04-08-10:54:01.546097] Reading config file /dev/shm/spack/test/etc/spack/repos.yaml
    lib/spack/spack/config.py:981 ==> [2021-04-08-10:54:02.983742] Reading config file /dev/shm/spack/test/etc/spack/compilers.yaml
    lib/spack/spack/config.py:981 ==> [2021-04-08-10:54:04.806201] Reading config file /dev/shm/spack/test/etc/spack/defaults/packages.yaml
    lib/spack/spack/config.py:981 ==> [2021-04-08-10:54:04.907017] Reading config file /dev/shm/spack/test/etc/spack/packages.yaml
    dev/shm/spack/test/lib/spack/spack/main.py:431 ==> [2021-04-08-10:54:05.868855] Warning: Intel's compilers may or may not optimize to the same degрee for non-Intel microprocessors for optimizations that are not unique to Intel microprocessors
    lib/spack/spack/solver/asp.py:1566 ==> [2021-04-08-10:54:10.186875] opt_criterion(15, version weight)
    lib/spack/spack/solver/asp.py:1566 ==> [2021-04-08-10:54:10.187378] opt_criterion(14, number of non-default variants (roots))
    lib/spack/spack/solver/asp.py:1566 ==> [2021-04-08-10:54:10.187777] opt_criterion(13, multi-valued variants + preferred providers for roots)
    lib/spack/spack/solver/asp.py:1566 ==> [2021-04-08-10:54:10.188175] opt_criterion(11, number of non-default variants (non-roots))
    lib/spack/spack/solver/asp.py:1566 ==> [2021-04-08-10:54:10.188569] opt_criterion(9, number of non-default providers (non-roots))
    lib/spack/spack/solver/asp.py:1566 ==> [2021-04-08-10:54:10.188961] opt_criterion(8, count of non-root multi-valued variants)
    lib/spack/spack/solver/asp.py:1566 ==> [2021-04-08-10:54:10.189354] opt_criterion(7, compiler matches + number of nodes)
    lib/spack/spack/solver/asp.py:1566 ==> [2021-04-08-10:54:10.189762] opt_criterion(6, version badness)
    lib/spack/spack/solver/asp.py:1566 ==> [2021-04-08-10:54:10.190156] opt_criterion(5, non-preferred compilers)
    lib/spack/spack/solver/asp.py:1566 ==> [2021-04-08-10:54:10.190547] opt_criterion(4, target matches)
    lib/spack/spack/solver/asp.py:1566 ==> [2021-04-08-10:54:10.190939] opt_criterion(3, non-preferred targets)
    lib/spack/spack/database.py:364 ==> [2021-04-08-10:54:10.212736] DATABASE LOCK TIMEOUT: 3s
    lib/spack/spack/database.py:368 ==> [2021-04-08-10:54:10.213675] PACKAGE LOCK TIMEOUT: No timeout
    gettext@0.21%gcc@5.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=cray-suse_linux11-bulldozer
        ^bzip2@1.0.8%gcc@5.3.0+shared arch=cray-cnl5-bulldozer
            ^diffutils@3.7%gcc@5.3.0 arch=cray-suse_linux11-bulldozer
                ^libiconv@1.16%gcc@5.3.0 arch=cray-cnl5-bulldozer
        ^libxml2@2.9.10%gcc@5.3.0~python arch=cray-suse_linux11-bulldozer
            ^pkgconf@1.7.4%gcc@5.3.0 arch=cray-cnl5-bulldozer
            ^xz@5.2.5%gcc@5.3.0~pic arch=cray-suse_linux11-bulldozer
            ^zlib@1.2.11%gcc@5.3.0+optimize+pic+shared arch=cray-cnl5-bulldozer
        ^ncurses@6.2%gcc@5.3.0~symlinks+termlib abi=none arch=cray-cnl5-bulldozer
        ^tar@1.34%gcc@5.3.0 arch=cray-suse_linux11-bulldozer
    </code>
    </pre>
    </details>

4. `spack --debug --stacktrace spec -I` command resolves `libiconv` and `xz` to `arch=cray-cnl5-bulldozer`:

    <details>
    <summary>
    <code>spack --debug --stacktrace spec gettext@0.21%gcc@5.3.0 arch=cray-suse_linux11-bulldozer</code>
    </summary>

    <pre>
    <code>
    lib/spack/spack/util/executable.py:188 ==> [2021-04-08-11:22:13.590133] '/bin/bash' '--norc' '--noprofile' '-lc' 'echo $CRAY_CPU_TARGET'
    lib/spack/spack/platforms/cray.py:154 ==> [2021-04-08-11:22:13.610731] default to front-end architecture
    lib/spack/spack/cmd/__init__.py:122 ==> [2021-04-08-11:22:13.802151] Imported spec from built-in commands
    lib/spack/spack/cmd/__init__.py:122 ==> [2021-04-08-11:22:13.804152] Imported spec from built-in commands
    lib/spack/spack/config.py:981 ==> [2021-04-08-11:22:13.808353] Reading config file /dev/shm/spack/test/etc/spack/defaults/config.yaml
    lib/spack/spack/config.py:981 ==> [2021-04-08-11:22:13.881523] Reading config file /dev/shm/spack/test/etc/spack/config.yaml
    lib/spack/spack/config.py:981 ==> [2021-04-08-11:22:13.891616] Reading config file /u/staff/mbelkin/.spack/config.yaml
    lib/spack/spack/database.py:364 ==> [2021-04-08-11:22:13.914982] DATABASE LOCK TIMEOUT: 3s
    lib/spack/spack/database.py:368 ==> [2021-04-08-11:22:13.915445] PACKAGE LOCK TIMEOUT: No timeout
    Input spec
    --------------------------------
    lib/spack/spack/config.py:981 ==> [2021-04-08-11:22:13.993712] Reading config file /dev/shm/spack/test/etc/spack/defaults/repos.yaml
    lib/spack/spack/config.py:981 ==> [2021-04-08-11:22:14.000272] Reading config file /dev/shm/spack/test/etc/spack/repos.yaml
     -   gettext@0.21%gcc@5.3.0 arch=cray-suse_linux11-bulldozer
    
    Concretized
    --------------------------------
    lib/spack/spack/config.py:981 ==> [2021-04-08-11:22:16.414900] Reading config file /dev/shm/spack/test/etc/spack/compilers.yaml
    lib/spack/spack/config.py:981 ==> [2021-04-08-11:22:18.230479] Reading config file /dev/shm/spack/test/etc/spack/defaults/packages.yaml
    lib/spack/spack/config.py:981 ==> [2021-04-08-11:22:18.332947] Reading config file /dev/shm/spack/test/etc/spack/packages.yaml
    dev/shm/spack/test/lib/spack/spack/main.py:431 ==> [2021-04-08-11:22:19.302837] Warning: Intel's compilers may or may not optimize to the same degree for non-Intel microprocessors for optimizations that are not unique to Intel microprocessors
    lib/spack/spack/solver/asp.py:1566 ==> [2021-04-08-11:22:23.475782] opt_criterion(15, version weight)
    lib/spack/spack/solver/asp.py:1566 ==> [2021-04-08-11:22:23.476663] opt_criterion(14, number of non-default variants (roots))
    lib/spack/spack/solver/asp.py:1566 ==> [2021-04-08-11:22:23.477074] opt_criterion(13, multi-valued variants + preferred providers for roots)
    lib/spack/spack/solver/asp.py:1566 ==> [2021-04-08-11:22:23.477476] opt_criterion(11, number of non-default variants (non-roots))
    lib/spack/spack/solver/asp.py:1566 ==> [2021-04-08-11:22:23.477872] opt_criterion(9, number of non-default providers (non-roots))
    lib/spack/spack/solver/asp.py:1566 ==> [2021-04-08-11:22:23.478268] opt_criterion(8, count of non-root multi-valued variants)
    lib/spack/spack/solver/asp.py:1566 ==> [2021-04-08-11:22:23.478662] opt_criterion(7, compiler matches + number of nodes)
    lib/spack/spack/solver/asp.py:1566 ==> [2021-04-08-11:22:23.479056] opt_criterion(6, version badness)
    lib/spack/spack/solver/asp.py:1566 ==> [2021-04-08-11:22:23.479450] opt_criterion(5, non-preferred compilers)
    lib/spack/spack/solver/asp.py:1566 ==> [2021-04-08-11:22:23.479842] opt_criterion(4, target matches)
    lib/spack/spack/solver/asp.py:1566 ==> [2021-04-08-11:22:23.480237] opt_criterion(3, non-preferred targets)
     -   gettext@0.21%gcc@5.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=cray-suse_linux11-bulldozer
    [+]      ^bzip2@1.0.8%gcc@5.3.0+shared arch=cray-suse_linux11-bulldozer
    [+]          ^diffutils@3.7%gcc@5.3.0 arch=cray-suse_linux11-bulldozer
    [+]              ^libiconv@1.16%gcc@5.3.0 arch=cray-cnl5-bulldozer
     -       ^libxml2@2.9.10%gcc@5.3.0~python arch=cray-suse_linux11-bulldozer
    [+]          ^pkgconf@1.7.4%gcc@5.3.0 arch=cray-suse_linux11-bulldozer
    [+]          ^xz@5.2.5%gcc@5.3.0~pic arch=cray-cnl5-bulldozer
    [+]          ^zlib@1.2.11%gcc@5.3.0+optimize+pic+shared arch=cray-suse_linux11-bulldozer
     -       ^ncurses@6.2%gcc@5.3.0~symlinks+termlib abi=none arch=cray-suse_linux11-bulldozer
    [+]      ^tar@1.34%gcc@5.3.0 arch=cray-suse_linux11-bulldozer
    </code>
    </pre>
    </details>

### Error Message

None

### Information on your system

spack debug report
* **Spack:** 0.16.1-2136-68cec598dc
* **Python:** 3.7.9
* **Platform:** cray-suse_linux11-bulldozer
* **Concretizer:** clingo

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
@maxim-belkin Does it consistently depend on flags (which would be weird), or it bounces among a set of solutions? Asking since it may happen, in rare cases, that two solutions have the same optimization score and clingo bounces among that.

**Comment by maxim-belkin** [comment]
Just checked and it definitely bounces between solutions -- even the `spack spec` command produces different results when executed twice in a row.

**Comment by alalazo** [comment]
I can reproduce on Piz Daint. I think this is peculiar to Cray, which allows for backend and frontend architecture.

**Comment by alalazo** [comment]
I think we have a bug in our logic program, since we never use the `node_os_inherit` fact:

https://github.com/spack/spack/blob/4adb76c4c5a65b808864e39d3fb6702e332fff51/lib/spack/spack/solver/concretize.lp#L464-L485

This usually works because most solves are done on systems with a single OS.

**Comment by alalazo** [comment]
@maxim-belkin Can you try to apply this patch:
```diff
diff --git a/lib/spack/spack/solver/concretize.lp b/lib/spack/spack/solver/concretize.lp
index 898927a8a8..bb593ebf41 100644
--- a/lib/spack/spack/solver/concretize.lp
+++ b/lib/spack/spack/solver/concretize.lp
@@ -474,10 +474,14 @@ node_os_set(Package) :- node_os_set(Package, _).
 % inherit OS along dependencies
 node_os_inherit(Package, OS) :- node_os_set(Package, OS).
 node_os_inherit(Dependency, OS)
-  :- node_os_inherit(Package, OS), depends_on(Package, Dependency),
+  :- node_os_inherit(Package, OS),
+     depends_on(Package, Dependency),
      not node_os_set(Dependency).
+
 node_os_inherit(Package) :- node_os_inherit(Package, _).
 
+node_os(Package, OS) :- node_os_inherit(Package, OS).
+
 % fall back to default if not set or inherited
 node_os(Package, OS)
   :- node(Package),
```
it should make everything work also on Cray. I'll try to polish this and come up with a test for a proper PR.

**Comment by maxim-belkin** [comment]
Thanks, @alalazo. Yes, the above patch makes `arch` of the dependencies consistent.
