### ISSUE TITLE
spack create: gitlab releases

### ISSUE THREAD

**Issue by ax3l** [LLNL/spack#2290]
I am trying to add a package for the [IceT](http://icet.sandia.gov/) compositing library but found that `spack create` seems not to understand
 - direct `git://` links in the member `url` (to check for tags)
 - links to `gitlab` releases, such as https://gitlab.kitware.com/icet/icet/tags with download links such as https://gitlab.kitware.com/icet/icet/repository/archive.tar.gz?ref=IceT-2.1.1

Should we can add the handling of those cases, too? :)

(for my specific problem: I will just add the releases I want manually.)

**Comment by adamjstewart** [comment]
I wonder if I broke this in #2028...

**Comment by ax3l** [comment]
Using the `url_for_version` function can solve the second point, but there is currently a bug still requiring a pseudo `url` member: https://github.com/LLNL/spack/pull/2291#issuecomment-259638544

**Comment by adamjstewart** [comment]
Yes, there is a difference between `url_for_version` and `url_version`. The former defines a function that can be used to determine the url based on the version. The latter defines the format of the version itself in the url. For example, in your case where version `2.1.1` appears as `2-1-1` in the url, you could use `url_version` to return `version.dashed`. `url_version` isn't very commonly used (I've never ran into it) but maybe it would help in this case.

**Comment by tgamblin** [comment]
@ax3l: is this fixed by @2296?

It doesn't look like #2296 does `git://` URLs.

**Comment by ax3l** [comment]
The thing with the `git://` URLs was, that I did not know that did always work with explicit git parameters in `version()`.

GitLab support in general is now added for archive links, the same way as for GitHub.

What is still left is the "you always need a `url` member even if `url_version` is implemented" for additional schemes that are not yet covered.

**Comment by tgamblin** [comment]
@ax3l: cool.  can you file a separate issue for the last part?

**Comment by ax3l** [comment]
@tgamblin sure, documented in #2788
