### ISSUE TITLE
list all tags in spack list

### ISSUE THREAD

**Issue by shahzebsiddiqui** [LLNL/spack#22938]
There is a command `spack list -t <TAG>` that can query packages by tagname but we don't know all registered tags. I know of one tagname `ecp` and there are few packages registered with this tagname

```
(base) [tutorial@ip-172-31-36-140 Desktop]$ spack list -t ecp
==> 20 packages.
amr-wind  chombo            er    kvtree  latte      nek5000   nwchem     qmcpack  redset    spath
axl       ecp-data-vis-sdk  filo  lammps  nalu-wind  nektools  parsplice  rankstr  shuffile  veloc
```

The maintainers should be able to register their product with tagname, so first we should have an option in `spack list` to  report all unique tags with an option like  `--list-tags` or `--get-tags` or `--fetch-tags`. There is an equivalent command in `spack find -t <TAG>` so it can be nice to have similar option in `spack find`. 

It's up to the maintainers to pick tag names that are relevant. The `tags` is a class attribute in the package definition so it should be relatively easy to register tags. This output will show up in `spack info` which is nice.

```
class Axl(CMakePackage):
    """Asynchronous transfer library"""

    homepage = "https://github.com/ecp-veloc/AXL"
    url      = "https://github.com/ecp-veloc/AXL/archive/v0.1.1.zip"
    git      = "https://github.com/ecp-veloc/axl.git"

    tags = ['ecp']

```

### Rationale

It would be nice to filter output of `spack find` and `spack list` by E4S tag to see all the packages registered. I think we should have all tagnames in lower case, to avoid mix case. Tagname should only contain alphabets, no special characters or numbers.

**Comment by tldahlgren** [comment]
It may be worth noting:

1. spack only stores tags in lower case
2. `spack find` is intended to search installed packages so adding a mutually exclusive option just to show tags seems awkward
3. `spack list` is intended to search available packages and, IMO has the same issue as 2
