### ISSUE TITLE
Installation issue: paraview

### ISSUE THREAD

**Issue by elleryames** [LLNL/spack#22970]
### Steps to reproduce the issue

```console
$ spack spec paraview
...
Concretized
--------------------------------
==> Error: invalid values for variant "cuda_arch" in package "paraview": ['10']
```
Same error when I select the cuda variant and appropriate architecture for my machine. 
 
```console
$ spack spec paraview+cuda cuda_arch=pascal
...
Concretized
--------------------------------
==> Error: invalid values for variant "cuda_arch" in package "paraview": ['10']
```
What does  the "['10']" at the end of the error message mean? It seems that should help me debug the issue. 

### Information on your system

* **Spack:** 0.16.1-2041-1908e6834d
* **Python:** 3.8.5
* **Platform:** linux-ubuntu20.04-zen2
* **Concretizer:** clingo

[compilers.yaml.txt](https://github.com/spack/spack/files/6305948/compilers.yaml.txt)
[packages.yaml.txt](https://github.com/spack/spack/files/6305950/packages.yaml.txt)

I don't think I have a build log since fails on 'spec'.

### Additional information

@chuckatkins  @danlipsa  @vicentebolea

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by vicentebolea** [comment]
@elleryames I am not abled to reproduce this error. I am also with gcc 10.2 with spark at that commit.

**Comment by elleryames** [comment]
Thanks for checking @vicentebolea . Any ideas for what else I should try or what is throwing an error? Are you using the clingo concretizer? Naively, it seems spack is checking the type or something for variant values and finds a problematic one. I checked the package.py and see no value '10' listed in the cuda_arch values.

**Comment by vicentebolea** [comment]
I could reproduce the error using the clingo concretizer. I found the reason of the problem.

1. Paraview package inherits from the cuda package.
2. They cuda package set the cuda_arch variant too but using the gencode number (thats why the 10)
3. For some reason this does not result in problems with the original concretizer
4. With the clingon the result variant is a mix of both the cuda package and the Paraview.

I wonder whats the best way to deal with without changing the variant name since that would break the paraview dependency to some of our users.

Maybe something hacky to internally translate the variant values from cuda arch family to gencode...

**Comment by elleryames** [comment]
I see; nice find! Would it be possible to enlarge the set of values for cuda_arch in the Paraview package? Something like 

`    variant('cuda_arch', default='native', multi=False,
            values=('native', 'fermi', 'kepler', 'maxwell',
                    'pascal', 'volta', 'turing', 'ampere', 'all', 'none') + cuda_arch_values,
            description='CUDA architecture')`

where `cuda_arch_values` are the gencode numbers from CudaPackage.

**Comment by psakievich** [comment]
I'm seeing this too.  Typically [this](https://github.com/spack/spack/blob/95ad5b882c990971e74d04261a665ba680f7c4be/var/spack/repos/builtin/packages/nalu-wind/package.py#L77) is how I've seen this dealt with.  Is there another package using the arch family?  If there is a list then we can just make a map.  I'll try to throw something together tonight.

Edit: ah looks like that is what vtk-m is doing already.

**Comment by psakievich** [comment]
The above hack will at least allow concretization to happen.  I haven't messed with the rest of the logic. @vicentebolea what are your thoughts? Not really sure of how to get around having a valid variant without appending the list.  Maybe add an override function to check the variant?

**Comment by chuckatkins** [comment]
> I could reproduce the error using the clingo concretizer. I found the reason of the problem.
> 
> 1. Paraview package inherits from the cuda package.
> 2. They cuda package set the cuda_arch variant too but using the gencode number (thats why the 10)
> 3. For some reason this does not result in problems with the original concretizer
> 4. With the clingon the result variant is a mix of both the cuda package and the Paraview.
> 
> I wonder whats the best way to deal with without changing the variant name since that would break the paraview dependency to some of our users.
> 
> Maybe something hacky to internally translate the variant values from cuda arch family to gencode...

I'd opt for paraview not overriding and changing the meaning of `cuda_arch`.  Using standardized variant names across all spack packages using CUDA is one of the big advantages of using the base class.

**Comment by vicentebolea** [comment]
@chuckatkins true, however, changing this variant possible values from architecture family names to the standard ones gencode (10,11,20...) would break the dependency of paraview down the line for other packages or users enviroments depending on paraview.

But that being said this oddity would have to be resolved eventually

**Comment by psakievich** [comment]
@vicentebolea what's the verdict here?  I can update #23002 to maintain the status quo for now by querying `cuda_arch` and mapping it to string if it's an int, or do you just want to make the switch to use the same syntax as the other packages inheriting from `CudaPackage`?

**Comment by vicentebolea** [comment]
@psakievich we have no choice but to eventually change our API since is an oddity that Paraview uses as `cuda_ arch` the cuda microarch families names. 

As for the now, I like what you have proposed at #23002. What remains is the mapping from when the cuda_arch variant is numeric and the translation to the family name. I have a branch where I am working on this, I will soon create the pull request. You could just cherry-pick the changes.

**Comment by vicentebolea** [comment]
https://github.com/spack/spack/pull/23257

**Comment by elleryames** [comment]
@vicentebolea Your fix was looking good. Are we just waiting for a review? Is there anything I can contribute?

**Comment by vicentebolea** [comment]
@elleryames yeah somethings came up and I left the PR there. It works on my machine, could you review it?

**Comment by elleryames** [comment]
Sorry @vicentebolea, I wasn't able to get to it the last few days and I am heading out on a trip for the next week. I'll take a look in a week or so.

**Comment by pelahi** [comment]
Hi @vicentebolea , @elleryames, I have also encountered this issue and wonder if any further work has been done. How can I help? Would it be useful for me to test the proposed solution on a variety of architectures? 
Also, do you know if similar issues have been encountered when using clingo?

**Comment by vicentebolea** [comment]
@pelahi there was a PR that resolved this, however, it has been in hold for 3 months. I will rebase it a ping you from there

**Comment by sethrj** [comment]
I'm also hitting this issue when trying `spack solve nalu-wind`:
```console
$ spack solve nalu-wind
==> Error: invalid values for variant "cuda_arch" in package "paraview": ['10']
```

**Comment by alalazo** [comment]
@vicentebolea What is the state of #23257 ?
