### ISSUE TITLE
Installation issue: qgis

### ISSUE THREAD

**Issue by steo85it** [LLNL/spack#23003]
### Steps to reproduce the issue

```console
$ spack install qgis
```
results in several concretization (`^cairo`, `gobject` conflict) and compilation (`^llvm`, `binutils` missing a property) errors, at least on my platform.
I managed to solve the issues by specifying
```console
$ spack install qgis^cairo+gobject^binutils+plugins
```
Unless this is specific to my system, it might be good to update the default behavior (I unfortunately don't know how to set this up, but hope the details help).

### Information on your system

* **Spack:** 0.16.1-2211-a4d32fd
* **Python:** 3.7.6
* **Platform:** linux-centos7-skylake
* **Concretizer:** original

### Additional information

@Sinan81  @adamjstewart

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by Sinan81** [comment]
This is a shortcoming of the spack concretizer (that does dependency resolution). While Spack will be upgrading to a better concretizer soon (as I understand) in the mean time it might be useful to put some lines in Qgis package file that helps with this. @steo85it could you try doing `spack edit qgis` and putting the following line somewhere after the comment `# Take care of conflicts...`
```
depends_on('cairo+gobject', when='@3.10:')
```
and save it. Afterwards, check if dependency resolution works by doing `spack spec qgis`

**Comment by Sinan81** [comment]
By the way, I am on centos7 too and `spack spec qgis` works without `^binutils+plugin`.

**Comment by steo85it** [comment]
Thanks for the quick feedback! The modification you suggested seems to work for `spack spec qgis`, while the (missing) `^binutils+plugin` doesn't affect the `spec` step, but causes the installation to crash (at least in my system).

**Comment by Sinan81** [comment]
Is it actually `qgis` or rather `llvm`, a indirect dependency, that fails to build without `binutils+plugins`? In my case `qgis` failed to build at `llvm` build step. qgis previously build with llvm@10 but this build issue might have to do with latest version llvm@11

**Comment by steo85it** [comment]
you are right, it is the `llvm` dependency failing to build because of that specific mod.

**Comment by haampie** [comment]
Can you try again after #22988?

**Comment by Sinan81** [comment]
> Can you try again after #22988?

Well. Concretizer is still complaining but now for different reasons. Thanks @haampie

**Comment by haampie** [comment]
In what sense?

**Comment by Sinan81** [comment]
> In what sense?

Concretizer can't resolve the fact that indirect dependency `mesa` requires `binutils` with `~plugins` due to variant defaults while the other indirect dependency `llvm` requires `+plugins`

**Comment by Sinan81** [comment]
I think we will end up putting `depends_on('binutils+plugins')` to help the concretizer which can be removed once we have an improved default concretizer.

**Comment by Sinan81** [comment]
> I think we will end up putting `depends_on('binutils+plugins' type='build')` to help the concretizer which can be removed once we have an improved default concretizer.

On a second thought, this is probably not a good idea since it would artificially introduce a build dependency for `qgis`. Considering that @adamjstewart and I are very responsive to qgis related spack issues, it is ok to leave the package file as it is. Also, Spack might be switching to a better concretizer soon as far as I can tell, and hence the concretization issues will disappear.

**Comment by haampie** [comment]
Ah yeah, works for me with the new concretizer. I'm gonna close the issue then, if people want to have it work better with the current concretizer feel free to reopen.

**Comment by steo85it** [comment]
That's good for me, too! Thanks for your help!
