### ISSUE TITLE
Spack fails to compile an older version of gcc inside a container

### ISSUE THREAD

**Issue by aprokop** [LLNL/spack#2301]
I'm building a docker container (from fedora:latest), setting up spack inside it and running
```bash
$ spack install gcc@4.8.5
```
Spack fails to install gcc, and fails with errors like this:
```
/home/nalu/spack/var/spack/stage/gcc-4.8.5-ccusns5lwdiqigdb3fh64qk7kjowgjp5/gcc-4.8.5/libiberty/../include/libiberty.h:92:22: error: expected '=', ',', ';', 'asm' or '__attribute__' before 'PARAMS'
 extern int writeargv PARAMS ((char **, FILE *));
                      ^~~~~~
```
Here is the full output log:
[spack-build.txt](https://github.com/LLNL/spack/files/584855/spack-build.txt)

Trying to run the configure line explicitly
```
'/home/nalu/spack/var/spack/stage/gcc-4.8.5-ccusns5lwdiqigdb3fh64qk7kjowgjp5/gcc-4.8.5/configure' '--prefix=/home/nalu/spack/opt/spack/linux-fedora24-x86_64/gcc-6.2.1/gcc-4.8.5-ccusns5lwdiqigdb3fh64qk7kjowgjp5' '--libdir=/home/nalu/spack/opt/spack/linux-fedora24-x86_64/gcc-6.2.1/gcc-4.8.5-ccusns5lwdiqigdb3fh64qk7kjowgjp5/lib64' '--disable-multilib' '--enable-languages=c,java,c++,fortran,objc,go' '--with-mpc=/home/nalu/spack/opt/spack/linux-fedora24-x86_64/gcc-6.2.1/mpc-1.0.3-yff53nnt4ci2z7ps5islaogkieagdzaw' '--with-mpfr=/home/nalu/spack/opt/spack/linux-fedora24-x86_64/gcc-6.2.1/mpfr-3.1.4-pmahifjapbfxmgqibng5uj5jpzvpzlaj' '--with-gmp=/home/nalu/spack/opt/spack/linux-fedora24-x86_64/gcc-6.2.1/gmp-6.1.1-jgkljtfxwn43ihlwpupnnm2ubc73x2t2' '--enable-lto' '--with-quad' '--with-sysroot=/' '--with-stage1-ldflags=-Wl,-rpath,/home/nalu/spack/opt/spack/linux-fedora24-x86_64/gcc-6.2.1/gcc-4.8.5-ccusns5lwdiqigdb3fh64qk7kjowgjp5/lib -Wl,-rpath,/home/nalu/spack/opt/spack/linux-fedora24-x86_64/gcc-6.2.1/gcc-4.8.5-ccusns5lwdiqigdb3fh64qk7kjowgjp5/lib64 -Wl,-rpath,/home/nalu/spack/opt/spack/linux-fedora24-x86_64/gcc-6.2.1/gmp-6.1.1-jgkljtfxwn43ihlwpupnnm2ubc73x2t2/lib -Wl,-rpath,/home/nalu/spack/opt/spack/linux-fedora24-x86_64/gcc-6.2.1/mpc-1.0.3-yff53nnt4ci2z7ps5islaogkieagdzaw/lib -Wl,-rpath,/home/nalu/spack/opt/spack/linux-fedora24-x86_64/gcc-6.2.1/binutils-2.27-hwg5hotuah2tnoisau6smalgew7ckmnb/lib -Wl,-rpath,/home/nalu/spack/opt/spack/linux-fedora24-x86_64/gcc-6.2.1/mpfr-3.1.4-pmahifjapbfxmgqibng5uj5jpzvpzlaj/lib -static-libstdc++ -static-libgcc' '--with-boot-ldflags=-Wl,-rpath,/home/nalu/spack/opt/spack/linux-fedora24-x86_64/gcc-6.2.1/gcc-4.8.5-ccusns5lwdiqigdb3fh64qk7kjowgjp5/lib -Wl,-rpath,/home/nalu/spack/opt/spack/linux-fedora24-x86_64/gcc-6.2.1/gcc-4.8.5-ccusns5lwdiqigdb3fh64qk7kjowgjp5/lib64 -Wl,-rpath,/home/nalu/spack/opt/spack/linux-fedora24-x86_64/gcc-6.2.1/gmp-6.1.1-jgkljtfxwn43ihlwpupnnm2ubc73x2t2/lib -Wl,-rpath,/home/nalu/spack/opt/spack/linux-fedora24-x86_64/gcc-6.2.1/mpc-1.0.3-yff53nnt4ci2z7ps5islaogkieagdzaw/lib -Wl,-rpath,/home/nalu/spack/opt/spack/linux-fedora24-x86_64/gcc-6.2.1/binutils-2.27-hwg5hotuah2tnoisau6smalgew7ckmnb/lib -Wl,-rpath,/home/nalu/spack/opt/spack/linux-fedora24-x86_64/gcc-6.2.1/mpfr-3.1.4-pmahifjapbfxmgqibng5uj5jpzvpzlaj/lib -static-libstdc++ -static-libgcc' '--with-gnu-ld' '--with-ld=/home/nalu/spack/opt/spack/linux-fedora24-x86_64/gcc-6.2.1/binutils-2.27-hwg5hotuah2tnoisau6smalgew7ckmnb/bin/ld' '--with-gnu-as' '--with-as=/home/nalu/spack/opt/spack/linux-fedora24-x86_64/gcc-6.2.1/binutils-2.27-hwg5hotuah2tnoisau6smalgew7ckmnb/bin/as'
```
and then running `make` works.

The container's compiler is gcc-6.2.1. As an extra reference, I tried to workaround by first building gcc@5.1.0 (which worked) and then using that downgraded version to build gcc@4.8.5. However, it still failed with the same error.

**Comment by adamjstewart** [comment]
Are you on the latest commit to the develop branch? Can you try:
```
spack install gcc@4.8.5~binutils
```
I've had a lot of trouble building older versions of gcc with newer versions of gcc. I added a patch that allowed me to build gcc 5 with gcc 6 in #2107. If `gcc~binutils` doesn't work, try installing the compatibility versions of gcc:
```
sudo dnf install compat-gcc*
```
That gives you gcc 3.4, which other users have reported allows them to build gcc 4 and 5. Support for these older compatibility versions was added in #2099. See #2044 for more discussion on this topic. Hopefully one of these ideas helps!

**Comment by aprokop** [comment]
Running

```spack install gcc@4.8.5~binutils```

did the trick. I'm not sure though of how to update the spec to check for that.

**Comment by adamjstewart** [comment]
Updating what spec?

**Comment by aprokop** [comment]
What I meant is that ideally one would update the gcc/package.py to test for this scenario, and fallback to ~binutils by default, or throw an exception.

**Comment by adamjstewart** [comment]
Ah. We've talked about a couple of different possibilities. We could default binutils to False, but there are some systems with ancient binutils that require this dependency. Another option would be to try to figure out why `+binutils` isn't working for older versions. It could be that we just need to specify exactly what versions of binutils are compatible with each GCC version:
http://wiki.osdev.org/Cross-Compiler_Successful_Builds

See #2144 for more details.

**Comment by aprokop** [comment]
Closing as there is a #2144 to keep track of the core issue.
