### ISSUE TITLE
Installation issue: conduit+python installs modules to <prefix>/python-modules instead of <prefix>/lib/pythonx.x/site-packages

### ISSUE THREAD

**Issue by EthanS94** [LLNL/spack#23018]
@cyrush 

### Steps to reproduce the issue

```console
$ spack install conduit+python
...
$ spack load python conduit
$ python -c "import conduit; print(conduit.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'conduit'
$ export PYTHONPATH=`spack location -i conduit`/python-modules:${PYTHONPATH}
$ python -c "import conduit; print(conduit.__file__)"
/scratch/users/stam/my-spack-environments-installs/linux-centos7-broadwell/gcc-8.3.0/conduit-develop-ykzlxnjl2mahtjtcgtfypuajk33v36hr/python-modules/conduit/__init__.py
```

### Information on your system

```console
$ spack debug report
* **Spack:** 0.16.1-2232-1a32f4a08c
* **Python:** 3.6.8
* **Platform:** linux-centos7-broadwell
* **Concretizer:** original
```

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
We should either convince `conduit` to install the libraries to the correct location, or add this directory to `PYTHONPATH` via `setup_run_environment`.

**Comment by cyrush** [comment]
conduit's build system supports this via `PYTHON_MODULE_INSTALL_PREFIX`, it was wired up in the spack package but maybe it was broken in recent updates. I'll take a look

**Comment by cyrush** [comment]
yes, looks like it vanished recently.  Here is an old version where it there (https://github.com/spack/spack/blob/ee30ec6a3555862cfda6af4fa1eff1c008643898/var/spack/repos/builtin/packages/conduit/package.py#L446)

I'll get this fixed.

**Comment by cyrush** [comment]
@EthanS94 @adamjstewart  I created #23057 which should resolve the issue.

**Comment by EthanS94** [comment]
@cyrush thanks!
