### ISSUE TITLE
Installation issue: llvm@11.1 fails at cmake stage without `^binutils+plugins`

### ISSUE THREAD

**Issue by Sinan81** [LLNL/spack#23060]
### Steps to reproduce the issue
```console
$ spack install llvm
...
     29        /mnt/local/spack/lib/spack/env/gcc/gcc CMakeFiles/cmTC_7ce86.dir/testCCompiler.c.o -o cmTC_7ce86
  >> 30    /mnt/local/spack/opt/spack/linux-centos7-skylake/gcc-8.3.0/binutils-2.36.1-nph3xe5s4iex3r7h6nb762lfos5nbkk3/bin/ld:
            fatal error: cannot use --plugin: /mnt/local/spack/opt/spack/linux-centos7-skylake/gcc-8.3.0/binutils-2.36.1-nph3x
           e5s4iex3r7h6nb762lfos5nbkk3/bin/ld was compiled without plugin support
  >> 31        collect2: error: ld returned 1 exit status
  >> 32        gmake[1]: *** [cmTC_7ce86] Error 1
...
```

### Information on your system

$ spack debug report
* **Spack:** 0.16.1-2232-1a32f4a
* **Python:** 3.6.8
* **Platform:** linux-centos7-skylake
* **Concretizer:** original

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by Sinan81** [comment]
The build works just fine with ` ^binutils+plugins` This makes sense since in `binutils` package file it is indicated that plugins is required by `+gold` variant. The binutils package might be the original cause of this issue.

**Comment by Sinan81** [comment]
related to #23003

**Comment by haampie** [comment]
Fixed by 22988
