### ISSUE TITLE
Unable to `spack load intel` version which is provided by `intel-oneapi-compilers` spec 

### ISSUE THREAD

**Issue by ikitayama** [LLNL/spack#23078]
### Steps to reproduce the issue

```console
$ spack install intel-oneapi-compilers
$ spack load intel
```
I naively expect the above is always possible.

### Error Message

```console
[kitayama1@jrlogin06 rhythms]$ spack compilers
==> Available compilers
-- gcc centos8-x86_64 -------------------------------------------
gcc@10.3.0  gcc@9.3.0  gcc@8.3.1

-- intel centos8-x86_64 -----------------------------------------
intel@2021.2.0  intel@19.1.2.254

-- oneapi centos8-x86_64 ----------------------------------------
oneapi@2021.2.0
[kitayama1@jrlogin06 rhythms]$ spack load intel@2021.2.0
==> Error: Spec 'intel@2021.2.0' matches no installed packages.
```

### Additional information

- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by ikitayama** [comment]
@DanVev , @rscohn2 is this expected?

**Comment by rscohn2** [comment]
I believe this is expected. 
```
spack load gcc@9.3.0
```
behaves the same way

You do spack load on packages, so you have to do:
```
spack load intel-oneapi-compilers

**Comment by ikitayama** [comment]
Thank you, @rscohn2 , closing this issue.
