### ISSUE TITLE
Lammps install issue with adios2 variant not found error

### ISSUE THREAD

**Issue by Nandinihpc** [LLNL/spack#23126]
Please see this 

spack spec lammps@20210310%gcc@10.2.0 +mpi +exceptions +granular +kspace +latte +manybody +mc +misc +molecule +mpiio +peri +poems +python +qeq +replica +rigid +shock +snap +spin +srd +voronoi +user-atc +user-h5md +user-lb +user-meamc +user-misc +user-netcdf +user-omp +user-reaxc ^netcdf-c@4.7.4/k5w4qtp ^adios2@2.7.1/mpffptq +mpi +parallel-netcdf ^parallel-netcdf@1.12.1/r5b7kru 
openblas@0.3.14/2zqwbx6

Concretized
--------------------------------
==> Error: variant "adios" not found in package "lammps" [required from package "lammps"]

It is missing variant in lammps package.py file? Can we get this fixed for new concretizer.

Thanks

**Comment by alalazo** [comment]
See #23085
