### ISSUE TITLE
Better output for distributed builds

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#23132]
### Rationale

![Screenshot from 2021-04-20 16-42-05](https://user-images.githubusercontent.com/194764/115416262-e8d1f500-a1f7-11eb-881e-1ba2e8651e61.png)

### Description

It would be nice if a process would output these log messages just once instead of repeatedly hundreds of times

**Comment by tldahlgren** [comment]
We go back-and-forth on the amount of noise to add/drop from the builds.  😆
