### ISSUE TITLE
Fix type='build' vs. type=nobuild

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#2314]
@alalazo 

Either all `type=` statements should have quotes or none should have quotes.  The current practice of quotes on some but not on others is an obvious booby trap.  See #2310 for how easily users can fall into this trap (and how others reviewing it don't see the problem either).

**Comment by alalazo** [comment]
Hmmm, I think this is better redirected to @tgamblin or @mathstuf who originally developed the feature.

**Comment by davydden** [comment]
IIRC both should work as one is a list and another is an alias for this list. Certainly both are used
```
$ ag "type='nolink'" var/spack/repos/builtin/packages/
var/spack/repos/builtin/packages/opencv/package.py
79:    depends_on('py-numpy', when='+python', type='nolink')

var/spack/repos/builtin/packages/r-datatable/package.py
42:    depends_on('r-chron', type='nolink')
```
and
```
$ ag "type=\"nolink\"" var/spack/repos/builtin/packages/
var/spack/repos/builtin/packages/py-yt/package.py
59:    depends_on("py-astropy", type="nolink", when="+astropy")
60:    depends_on("py-cython", type="nolink")
61:    depends_on("py-h5py", type="nolink", when="+h5py")
62:    depends_on("py-ipython", type="nolink")
63:    depends_on("py-matplotlib", type="nolink")
64:    depends_on("py-numpy", type="nolink")
65:    depends_on("py-scipy", type="nolink", when="+scipy")
67:    depends_on("py-sympy", type="nolink")
```
and
```
$ ag "type=nolink" var/spack/repos/builtin/packages/
var/spack/repos/builtin/packages/cantera/package.py
60:    depends_on('py-numpy',  when='+python', type=nolink)
61:    depends_on('py-scipy',  when='+python', type=nolink)
62:    depends_on('py-cython', when='+python', type=nolink)
63:    depends_on('py-3to2',   when='+python', type=nolink)

var/spack/repos/builtin/packages/cask/package.py
44:    depends_on('emacs', type=nolink)
```

**Comment by adamjstewart** [comment]
If we're deciding on one or the other, I would prefer all quotes. But yes, both should work for nolink, although only quotes for build.

**Comment by citibeth** [comment]
So it seems the conclusion is we can always use quotes.

**Comment by mathstuf** [comment]
Yes, quotes should be preferred now. The quoted versions of `nolink` and such came after the initial merge and a sweep had not been made.
