### ISSUE TITLE
Installation issue: libsigsegv

### ISSUE THREAD

**Issue by mansourmoufid** [LLNL/spack#23146]
### Steps to reproduce the issue

```console
$ spack install libsigsegv
```

fails with the error:

```
Undefined symbols for architecture arm64:
  "_vm_region", referenced from:
      _sigsegv_get_vma in stackvma.o
ld: symbol(s) not found for architecture arm64
```

This was fixed in version 2.13. I updated libsigsegv/package.py to version 2.13 and it builds fine.

### Information on your system

* **Spack:** 0.16.1-2320-5931995364
* **Python:** 3.8.2
* **Platform:** darwin-bigsur-arm64
* **Concretizer:** original

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/6346171/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/6346172/spack-build-env.txt)

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
Thanks, could you share your edits to the package and make a pull request so this issue can be closed?
