### ISSUE TITLE
Installation issue: LvArray@0.1.0

### ISSUE THREAD

**Issue by tldahlgren** [LLNL/spack#23192]
I am currently building an environment on LC's quartz system.  I am concretizing separately with `raja` and `umpire` being constrained as `~openmp`.

The specification provided below is the one produced by the `clingo` concretizer so the outputs reported here are from building `LvArray` **outside** of the environment.  The error seems to indicate I should be telling the build where to find the library but there appears to be no way to pass that information through Spack and there is no variant in the package to disable openmp.

@corbett5 

### Steps to reproduce the issue

```console
$ spack install lvarray@0.1.0%gcc@8.3.1+addr2line~benchmarks~caliper~chai~cuda~docs~examples~ipo+shared+tests~umpire build_type=RelWithDebInfo cuda_arch=none arch=linux-rhel7-broadwell
...
==> lvarray: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

5 errors found in build log:
     102    cd /tmp/dahlgren/spack-stage/spack-stage-lvarray-0.1.0-peo2xquw7wm3sxuzc6lerd3kboyclkaj/spack-build-peo2xqu/src &
            & /usr/tce/packages/gcc/gcc-8.3.1/bin/g++ -Dlvarray_EXPORTS -I/tmp/dahlgren/spack-stage/spack-stage-lvarray-0.1.0
            -peo2xquw7wm3sxuzc6lerd3kboyclkaj/spack-build-peo2xqu/include -isystem /usr/WS1/dahlgren/spack/opt/spack/linux-rh
            el7-broadwell/gcc-8.3.1/raja-0.13.0-mkff7f3iud6pduvxpnmrdqo3gt3zpneh/include -isystem /usr/WS1/dahlgren/spack/opt
            /spack/linux-rhel7-broadwell/gcc-8.3.1/camp-0.1.0-phejyvygypskp2dlrudbzhri533mlzig/include -Wall -Wextra   -Werro
            r  -Wall -Wextra -Wpedantic -pedantic-errors -Wshadow -Wfloat-equal -Wcast-align -Wcast-qual  -O3 -g -DNDEBUG -fP
            IC -std=c++14 -MD -MT src/CMakeFiles/lvarray.dir/system.cpp.o -MF CMakeFiles/lvarray.dir/system.cpp.o.d -o CMakeF
            iles/lvarray.dir/system.cpp.o -c /var/tmp/dahlgren/spack-stage/spack-stage-lvarray-0.1.0-peo2xquw7wm3sxuzc6lerd3k
            boyclkaj/spack-src/src/system.cpp
     103    [  2%] Building CXX object blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/CMakeFiles/gtest.dir/sr
            c/gtest-all.cc.o
     104    cd /tmp/dahlgren/spack-stage/spack-stage-lvarray-0.1.0-peo2xquw7wm3sxuzc6lerd3kboyclkaj/spack-build-peo2xqu/blt/t
            hirdparty_builtin/googletest-master-2020-01-07/googletest && /usr/tce/packages/gcc/gcc-8.3.1/bin/g++ -DGTEST_CREA
            TE_SHARED_LIBRARY=1 -DGTEST_HAS_DEATH_TEST=0 -Dgtest_EXPORTS -I/var/tmp/dahlgren/spack-stage/spack-stage-lvarray-
            0.1.0-peo2xquw7wm3sxuzc6lerd3kboyclkaj/spack-src/cmake/blt/thirdparty_builtin/googletest-master-2020-01-07/google
            test/include -I/var/tmp/dahlgren/spack-stage/spack-stage-lvarray-0.1.0-peo2xquw7wm3sxuzc6lerd3kboyclkaj/spack-src
            /cmake/blt/thirdparty_builtin/googletest-master-2020-01-07/googletest -Wall -Wextra   -Werror  -O3 -g -DNDEBUG -f
            PIC -Wall -Wshadow -Wno-error=dangling-else -DGTEST_HAS_PTHREAD=1 -fexceptions -Wextra -Wno-unused-parameter -Wno
            -missing-field-initializers -std=c++14 -MD -MT blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/CMa
            keFiles/gtest.dir/src/gtest-all.cc.o -MF CMakeFiles/gtest.dir/src/gtest-all.cc.o.d -o CMakeFiles/gtest.dir/src/gt
            est-all.cc.o -c /var/tmp/dahlgren/spack-stage/spack-stage-lvarray-0.1.0-peo2xquw7wm3sxuzc6lerd3kboyclkaj/spack-sr
            c/cmake/blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/src/gtest-all.cc
     105    [  3%] Linking CXX shared library ../lib/liblvarray.so
     106    cd /tmp/dahlgren/spack-stage/spack-stage-lvarray-0.1.0-peo2xquw7wm3sxuzc6lerd3kboyclkaj/spack-build-peo2xqu/src &
            & /usr/WS1/dahlgren/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/cmake-3.20.1-qnu5li7yigtawhiqjegkknp23e5cvbtz
            /bin/cmake -E cmake_link_script CMakeFiles/lvarray.dir/link.txt --verbose=1
     107    /usr/tce/packages/gcc/gcc-8.3.1/bin/g++ -fPIC      -Wall -Wextra   -Werror  -Wall -Wextra -Wpedantic -pedantic-er
            rors -Wshadow -Wfloat-equal -Wcast-align -Wcast-qual  -O3 -g -DNDEBUG -shared -Wl,-soname,liblvarray.so -o ../lib
            /liblvarray.so CMakeFiles/lvarray.dir/system.cpp.o CMakeFiles/lvarray.dir/totalview/tv_data_display.c.o  -Wl,-rpa
            th,/usr/WS1/dahlgren/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/raja-0.13.0-mkff7f3iud6pduvxpnmrdqo3gt3zpneh
            /lib:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
            :::::::: -ldl /usr/WS1/dahlgren/spack/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/raja-0.13.0-mkff7f3iud6pduvxpnmrd
            qo3gt3zpneh/lib/libRAJA.so -lopenmp -ldl
  >> 108    /usr/tce/packages/gcc/gcc-8.3.1/rh/usr/bin/../libexec/gcc/x86_64-redhat-linux/8/ld: cannot find -lopenmp
  >> 109    collect2: error: ld returned 1 exit status
  >> 110    make[2]: *** [lib/liblvarray.so] Error 1
     111    make[2]: Leaving directory `/tmp/dahlgren/spack-stage/spack-stage-lvarray-0.1.0-peo2xquw7wm3sxuzc6lerd3kboyclkaj/
            spack-build-peo2xqu'
  >> 112    make[1]: *** [src/CMakeFiles/lvarray.dir/all] Error 2
     113    make[1]: *** Waiting for unfinished jobs....
     114    [  3%] Linking CXX shared library ../../../../lib/libgtest.so
     115    cd /tmp/dahlgren/spack-stage/spack-stage-lvarray-0.1.0-peo2xquw7wm3sxuzc6lerd3kboyclkaj/spack-build-peo2xqu/blt/t
            hirdparty_builtin/googletest-master-2020-01-07/googletest && /usr/WS1/dahlgren/spack/opt/spack/linux-rhel7-broadw
            ell/gcc-8.3.1/cmake-3.20.1-qnu5li7yigtawhiqjegkknp23e5cvbtz/bin/cmake -E cmake_link_script CMakeFiles/gtest.dir/l
            ink.txt --verbose=1
     116    /usr/tce/packages/gcc/gcc-8.3.1/bin/g++ -fPIC      -Wall -Wextra   -Werror  -O3 -g -DNDEBUG -shared -Wl,-soname,l
            ibgtest.so -o ../../../../lib/libgtest.so CMakeFiles/gtest.dir/src/gtest-all.cc.o  -lpthread
     117    make[2]: Leaving directory `/tmp/dahlgren/spack-stage/spack-stage-lvarray-0.1.0-peo2xquw7wm3sxuzc6lerd3kboyclkaj/
            spack-build-peo2xqu'
     118    [  3%] Built target gtest
     119    make[1]: Leaving directory `/tmp/dahlgren/spack-stage/spack-stage-lvarray-0.1.0-peo2xquw7wm3sxuzc6lerd3kboyclkaj/
            spack-build-peo2xqu'
  >> 120    make: *** [all] Error 2
```

### Information on your system

* **Spack:** 0.16.1-2245-4cca69f4ed
* **Python:** 3.7.2
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** clingo

### Additional information

The relevant `spack-build-out.txt` information is provided in the output above.

[spack-build-env.txt](https://github.com/spack/spack/files/6355031/lvarray-spack-build-out.txt)

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have identified/uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by corbett5** [comment]
LvArray doesn't have an option to enable/disable OpenMP it just picks up whatever RAJA is built with. Can you post the specs you used to build RAJA? Then I'll try and replicate the issue.

**Comment by corbett5** [comment]
After adding `gcc@8.3.1` to `compilers.yaml` the following worked for me on Quartz, albeit with Spack develop (7322a9e).

> `./bin/spack install lvarray@0.1.0%gcc@8.3.1+addr2line~benchmarks~caliper~chai~cuda~docs~examples~ipo+shared+tests~umpire build_type=RelWithDebInfo cuda_arch=none arch=linux-rhel7-broadwell ^raja@0.13.0~openmp`

Which produces the following output

> `[  3%] Linking CXX shared library ../lib/liblvarray.so
cd /tmp/corbett5/spack-stage/spack-stage-lvarray-0.1.0-lbrbbr5kglo6lgg7nlechpgtwialhcr3/spack-build-lbrbbr5/src && /usr/WS2/corbett5/spack-tmp/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/cmake-3.20.1-qnu5li7yigtawhiqjegkknp23e5cvbtz/bin/cmake -E cmake_link_script CMakeFiles/lvarray.dir/link.txt --verbose=1
/usr/tce/packages/gcc/gcc-8.3.1/bin/g++ -fPIC      -Wall -Wextra   -Werror  -Wall -Wextra -Wpedantic -pedantic-errors -Wshadow -Wfloat-equal -Wcast-align -Wcast-qual  -O3 -g -DNDEBUG -shared -Wl,-soname,liblvarray.so -o ../lib/liblvarray.so CMakeFiles/lvarray.dir/system.cpp.o CMakeFiles/lvarray.dir/totalview/tv_data_display.c.o  -Wl,-rpath,/usr/WS2/corbett5/spack-tmp/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/raja-0.13.0-nx522k2vskx7lcucouc6geeasnxjcket/lib::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: -ldl /usr/WS2/corbett5/spack-tmp/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/raja-0.13.0-nx522k2vskx7lcucouc6geeasnxjcket/lib/libRAJA.so -ldl`

**Comment by tldahlgren** [comment]
> LvArray doesn't have an option to enable/disable OpenMP it just picks up whatever RAJA is built with. Can you post the specs you used to build RAJA? Then I'll try and replicate the issue.

Sure.  The Spack (`clingo`) concretizer determined the `raja` dependency to be:

```
^raja@0.13.0%gcc@8.3.1~cuda+examples+exercises~ipo+openmp~rocm+shared~tests amdgpu_target=none build_type=RelWithDebInfo cuda_arch=none arch=linux-rhel7-broadwell
```

I'm trying to be *minimal* in the environment but I'll try being explicit with the `raja` dependency for `LvArray`.

**Comment by corbett5** [comment]
Great, when I install RAJA separately with the spec you provided I get the same problem.

**Comment by corbett5** [comment]
It appears that RAJA has changed their CMake package with 0.13. The following is what I get with `blt_print_target_properties` with 0.13.0

```-- [RAJA property] 'RAJA' is a cmake target
-- [RAJA property] BINARY_DIR: /usr/WS2/corbett5/LvArray/build-quartz-toss_3_x86_64_ib-gcc@8.3.1-debug
-- [RAJA property] IMPORTED: TRUE
-- [RAJA property] IMPORTED_CONFIGURATIONS: RELWITHDEBINFO
-- [RAJA property] IMPORTED_GLOBAL: FALSE
-- [RAJA property] INTERFACE_INCLUDE_DIRECTORIES: /usr/WS2/corbett5/spack-tmp/opt/spack/linux-rhel7-broadwell/gcc-8.3.1/raja-0.13.0-mkff7f3iud6pduvxpnmrdqo3gt3zpneh/include
-- [RAJA property] INTERFACE_LINK_LIBRARIES: openmp;camp;dl
-- [RAJA property] NAME: RAJA
-- [RAJA property] POSITION_INDEPENDENT_CODE: True
-- [RAJA property] SOURCE_DIR: /usr/WS2/corbett5/LvArray
-- [RAJA property] TYPE: SHARED_LIBRARY
```

The issue here is that it is exporting `openmp` in `INTERFACE_LINK_LIBRARIES`, but you don't link to OpenMP via `-lopenmp` which is what CMake is trying to do here.

With 0.12.1 I have the following output (from a non-spack build so it's not an identical setup)
```
-- [RAJA property] 'RAJA' is a cmake target
-- [RAJA property] AUTOGEN_ORIGIN_DEPENDS: ON
-- [RAJA property] AUTOMOC_COMPILER_PREDEFINES: ON
-- [RAJA property] AUTOMOC_MACRO_NAMES: Q_OBJECT;Q_GADGET;Q_NAMESPACE
-- [RAJA property] BINARY_DIR: /usr/WS2/corbett5/LvArray/build-quartz-gcc@8.1.0-debug
-- [RAJA property] BUILD_WITH_INSTALL_RPATH: OFF
-- [RAJA property] CXX_EXTENSIONS: OFF
-- [RAJA property] CXX_STANDARD: 14
-- [RAJA property] CXX_STANDARD_REQUIRED: ON
-- [RAJA property] Fortran_MODULE_DIRECTORY: /usr/WS2/corbett5/LvArray/build-quartz-gcc@8.1.0-debug/lib/fortran
-- [RAJA property] IMPORTED: TRUE
-- [RAJA property] IMPORTED_CONFIGURATIONS: RELEASE
-- [RAJA property] IMPORTED_GLOBAL: FALSE
-- [RAJA property] INSTALL_RPATH: 
-- [RAJA property] INSTALL_RPATH_USE_LINK_PATH: OFF
-- [RAJA property] INTERFACE_COMPILE_OPTIONS: -fopenmp
-- [RAJA property] INTERFACE_INCLUDE_DIRECTORIES: /usr/WS1/GEOS/GEOSX/TPLs_2020-10-08/install-quartz-gcc@8.1.0-release/raja/include
-- [RAJA property] INTERFACE_LINK_LIBRARIES: camp;dl
-- [RAJA property] INTERFACE_LINK_OPTIONS: SHELL:-fopenmp
-- [RAJA property] NAME: RAJA
-- [RAJA property] POSITION_INDEPENDENT_CODE: TRUE
-- [RAJA property] RUNTIME_OUTPUT_DIRECTORY: /usr/WS2/corbett5/LvArray/build-quartz-gcc@8.1.0-debug/bin
-- [RAJA property] SKIP_BUILD_RPATH: OFF
-- [RAJA property] SOURCE_DIR: /usr/WS2/corbett5/LvArray
-- [RAJA property] TYPE: STATIC_LIBRARY
```

Note that OpenMP is not exported as a library but instead as a compilation flag.

@davidbeckingsale thoughts?

**Comment by davidbeckingsale** [comment]
Fixed by this I think: https://github.com/LLNL/RAJA/pull/987

**Comment by corbett5** [comment]
@davidbeckingsale thanks, building with `raja@develop` fixed the issue!

@tldahlgren If that is a suitable fix for you you'll need to disable the LvArray unit tests with `~tests`. RAJA 0.13 changed how you access the `RAJA::View` members so they won't build. I'll do a LvArray release in the next week or so that will fix that particular issue.

**Comment by tldahlgren** [comment]
> @davidbeckingsale thanks, building with `raja@develop` fixed the issue!
> 
> @tldahlgren If that is a suitable fix for you you'll need to disable the LvArray unit tests with `~tests`. RAJA 0.13 changed how you access the `RAJA::View` members so they won't build. I'll do a LvArray release in the next week or so that will fix that particular issue.

I changed the spec in my `spack.yaml` to be `lvarray ^raja~openmp`, which is consistent with how I'm building `raja` atm,  and it built successfully. I should note that I am concretizing separately so my environment is building two variants of `raja@0.13.0` and one of `raja@develop`.
