### ISSUE TITLE
Add more installation date information to spack find

### ISSUE THREAD

**Issue by psakievich** [LLNL/spack#23205]
I'd like `spack find -L` to include the date-time stamp the package was installed, and a new flag `--latest` added to `spack find` and `spack location`  to show the last install of package that matches the provided spec.

### Rationale

I have found that I often get multiple versions of the same package installed due to packages being updated, or trying to fix bugs as a developer.  In this case I'm wary of just doing a brute force pruning of the old packages by querying with `spack find --end-date`.   Also during the development cycle I can get multiple instances of the same package installed on the same day or very close to one another.  It would be nice to be able to just know from `spack find` when things were installed so I can pick and prune old packages, and to be able to find/select the latest version of a package without having to iterate on the `--end-date` because I can't remember when the last time I installed something.

### Description
Stated at the top of the feature request

### Additional information
```
spack --version
0.16.1-1672-821769c
``` 

### General information

- [x] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
Duplicate of #23182

**Comment by psakievich** [comment]
I'm okay with closing this.  I'll add a comment to #23182 with the features I think it is missing.
