### ISSUE TITLE
Installation issue: mpip

### ISSUE THREAD

**Issue by maxim-belkin** [LLNL/spack#23203]
### Steps to reproduce the issue

```console
$ spack install mpip
```
produces

```log
checking libunwind.h usability... no
checking libunwind.h presence... no
checking for libunwind.h... no

  mpiP on x86_64 platforms requires libunwind.
  Please install libunwind and, if necessary, configure mpiP with
  appropriate CFLAGS and LDFLAGS settings.
```

The issue can be resolved by adding:
```spack
depends_on('libunwind', when='target=x86_64:')
```

### Information on your system

* **Spack:** 0.16.1-2331-a97ef832d9
* **Python:** 3.6.8
* **Platform:** linux-centos8-sandybridge
* **Concretizer:** clingo

Both packages.yml and modules.yml are unmodified.

### Additional information

* [spack-build-out.txt](https://gist.github.com/maxim-belkin/eb626707ee47f4097a2dad7af771e5cd#file-spack-build-out-txt)
* [spack-build-env.txt](https://gist.github.com/maxim-belkin/eb626707ee47f4097a2dad7af771e5cd#file-spack-build-env-txt)

CC @cchambreau

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by glennpj** [comment]
I hit this as well. Looking at the recipe, it is not clear how libunwind fits. The variant defaults to `True`, but the dependency is commented out.
```python
    #  Ideally would use libunwind, but provide backtrace and                                                                               
    #    setjmp functionality, if needed                                                                                                    
    #  depends_on('unwind')  
```
Also, it looks like `libunwind` is not compatible with `setjmp` so there probably needs to be a `conflicts` directive for that.

@cchambreau Any ideas of the appropriate fix?
