### ISSUE TITLE
Fun with Circular Dependencies!

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#2321]
I noticed that `curl` needed to  `depends_on('libssh2')` but it depended on `openssl` instead.  So I added the dependency.  This is where the fun begins. `spack spec curl` works.  But `spack spec netcdf` yields an infinite recursion.  Why?

Because `curl` -> `libssh2` -> `cmake [build]` -> `curl`

So how will you get this built if you can't put `libssh2`, `cmake` or both in your `packages.yaml`? This is a hard problem.... Maybe build dependencies need to be treated a bit differently; notice that `libssh2` only depends on a really old version of CMake.  You should be able to tell Spack that you have that old version.  And then it could be used, when appropriate, to satisfy build dependencies.

The reality is that software is self-bootstrapping, and therefore breaks our DAG dependency model.  If we lose all C-compiler executables on all machines, we won't be able to build anything.  Our circular dependencies need to turn into spiral dependencies.

**Comment by davydden** [comment]
agreed, build-only dependencies should ideally not influence any hashes and it should be possible to have multiple different nodes in DAG if they are build-only dependencies (like `Cmake` or `python`).

I think we should concentrate this discussion in https://github.com/LLNL/spack/issues/839, which appears to be the oldest issue which discuss this problem first.

**Comment by citibeth** [comment]
The problem is deeper than that.  Even if build dependencies are handled
correctly... you need CMake to build libssh2 and you need libssh2 to build
CMake.  This can be straightened out if we can think in terms of spiral
dependencies:

cmake (new version) --> libssh2 --> cmake (old version)


I took this as an opportunity to delve deper into the `cmake` build.  See
#2325.

**Comment by davydden** [comment]
@citibeth :

> The problem is deeper than that. 

what I meant is that one potentially could break circular dependencies by installing (i) `cmake~ssh2` (assuming that you can add an variant); (ii) install `ssh2^cmake~ssh2`; (iii) install `cmake+ssh2`. Thereby i think https://github.com/LLNL/spack/issues/839 could still be a solution.

**Comment by davydden** [comment]
nevermind, on a second though i guess one does not need #839 for this
