### ISSUE TITLE
LD_LIBRARY_PATH (or equivalent) is not set on Cray platforms

### ISSUE THREAD

**Issue by carns** [LLNL/spack#23228]
On conventional Linux systems, loading a Spack package will add it's library path to LD_LIBRARY_PATH.

This does not happen on Cray systems, however.  This makes it difficult for library developers to document how to use their libraries at run time because the behavior is inconsistent across platforms.

### Steps to reproduce the issue

```console
# NOTE: This problem is not peculiar to the libunwind package; I am just using it as an example because it builds quickly
#             and has no additional dependencies to satisfy.
spack install libunwind
spack load  -r libunwind
env |grep LIB |grep unwind
```

### Error Message

```
# On a laptop, the last command listed above displays the following or similar:
$ env |grep LIB |grep unwind
LD_LIBRARY_PATH=/home/carns/working/src/spack/opt/spack/linux-ubuntu20.10-skylake/gcc-10.2.0/libunwind-1.5.0-enb3aln2cmueqdz6tuvdxkvj7trmrddl/lib

# On a Cray system such as Cori (NERSC) or Theta (ALCF) the desired library is not in LD_LIBRARY_PATH
$ env |grep LIB |grep unwind
$
```

The core problem is that external (i.e. non-spack, and could use cmake, autotools, gnu make, or any other build system) applications that link against our library packages do not have a consistent way to determine runtime library paths once the application has been built.

### Information on your system

An example packages.yaml as used on Theta can be found at https://github.com/mochi-hpc-experiments/mochi-tests/blob/main/perf-regression/theta/packages.yaml

### Additional information

- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

@frankwillmore @roblatham00

**Comment by carns** [comment]
Ah, I have found why (in terms of spack config files) this is the case.  On Linux systems, there is a linux-specific modules.yaml file in etc/spack/defaults/linux/ that tells spack to set LD_LIBRARY path when modules are loaded:

```
> spack config blame modules |grep LD_LIBRARY_PATH
/home/carns/working/src/spack/etc/spack/defaults/linux/modules.yaml:19      - LD_LIBRARY_PATH
/home/carns/working/src/spack/etc/spack/defaults/linux/modules.yaml:21      - LD_LIBRARY_PATH
>
```

This is not the case on Cray systems:
```
> spack config blame modules |grep LD_LIBRARY_PATH
>
```

This also means (I think - will confirm shortly) that I can work around the problem by putting my own modules.yaml file with LD_LIBRARY_PATH settings in my own `~/.spack/` directory.

I'm leaving this ticket open, though, because I suspect this may have been an oversight rather than a deliberate policy choice to make the default behavior different on Cray systems?

**Comment by frankwillmore** [comment]
good catch! Looks like it's covered here:

https://spack.readthedocs.io/en/latest/module_file_support.html#customize-environment-modifications

**Comment by carns** [comment]
This was addressed in https://github.com/spack/spack/pull/23932
