### ISSUE TITLE
Installation issue: clingo@master+python missing py-cffi dependency

### ISSUE THREAD

**Issue by omor1** [LLNL/spack#23236]
### Steps to reproduce the issue

```console
$ spack install clingo@master+python
...
```

Later when trying to use the new ASP-based concretizer, Spack is unable to load `clingo`, as the `cffi` dependency is missing. This was initially reported on Slack. Pinging maintainers @alalazo @tgamblin.

This should be a simple fix:
```python
depends_on('py-cffi', type=('build', 'run'), when='@master+python')
```

### Information on your system

```console
$ spack debug report
* **Spack:** 0.16.1-2354-9dab40dd30
* **Python:** 3.8.5
* **Platform:** linux-centos8-zen2
* **Concretizer:** original
```

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
@omor1 I'm on it, will submit a PR shortly. With respect to this:

> Later when trying to use the new ASP-based concretizer

If you want to use `clingo` for the new ASP-based solver you can let Spack bootstrap it from sources. For that we use a commit of clingo that is pinned and is known to work for Python 2.6 too. Details are [here](https://spack.readthedocs.io/en/latest/getting_started.html#optional-bootstrapping-clingo). Also, there's this PR waiting for review #22720 which allows bootstrapping from binaries and should be much faster.

EDIT: Another possibility, if you're using Python 3.6 or later to run Spack, is to `pip install clingo` before using Spack. I usually dogfood on Spack but I think this is at least worth mentioning.
