### ISSUE TITLE
Modifying source code before installation

### ISSUE THREAD

**Issue by afrah** [LLNL/spack#23301]
am working on a cluster with x86_64 GNU/Linux operating system. I want to profile some sparse solvers with TAU using 16 number of processors. However, I got this error.

`TAU bootstreap heap exceeded. Increase BOOTSTRAP_HEAP_SIZE in memory_wrapper.c and try again.`
from memory_wrapper.h, I get:

```
// Assume 4K pages unless we know otherwise.
// We cannot determine this at runtime because it must be known during
// the bootstrap process and it would be unsafe to make any system calls there.
#ifndef PAGE_SIZE
#define PAGE_SIZE 4096
#endif

// Size of heap memory for library wrapper bootstrapping
#ifdef __APPLE__
// Starting on macOS 11, PAGE_SIZE is not constant on macOS
// Apple recommends using PAGE_MAX_SIZE instead.
// see https://developer.apple.com/videos/play/wwdc2020/10214/?time=549
#define BOOTSTRAP_HEAP_SIZE (3*PAGE_MAX_SIZE)
#else
#define BOOTSTRAP_HEAP_SIZE (3*PAGE_SIZE)
#endif
```
I need to modify this file in order to increase page size before the installation since this can not be done at runtime.  I tried to interrupt  the installation and modify the file but that does not help.  Keeping stack configurations and installing TAU does not help for some reason, the installed TAU is different. Is there any way to enforce TAU to install the modified archive file or any other idea

**Comment by alalazo** [comment]
You can patch `tau` before installation. This involves modifying `tau/package.py` to add either a patch directive or a patch method. You may want to search in the builtin repository to look for examples.

**Comment by afrah** [comment]
Thank you for your reply ... I created a patch file called **memory_wrapper.patch** with content
```
--- memory_wrapper.h	2021-04-28 04:22:46.267814124 -0500
+++ memory_wrapper_new.h	2021-04-27 21:33:18.986452000 -0500
@@ -38,9 +38,9 @@
 // Starting on macOS 11, PAGE_SIZE is not constant on macOS
 // Apple recommends using PAGE_MAX_SIZE instead.
 // see https://developer.apple.com/videos/play/wwdc2020/10214/?time=549
-#define BOOTSTRAP_HEAP_SIZE (3*PAGE_MAX_SIZE)
+#define BOOTSTRAP_HEAP_SIZE (256*PAGE_MAX_SIZE)
 #else
-#define BOOTSTRAP_HEAP_SIZE (3*PAGE_SIZE)
+#define BOOTSTRAP_HEAP_SIZE (256*PAGE_SIZE)
 #endif
 
 // Types of function pointers for wrapped functions
```

and modified package.py in inside spack/repos/builtin/packages/tau by adding this line
`    patch('memory_wrapper.patch', when="2.30.1%gcc@7.1.0")
`
how can I tell spack the location of memory_wrapper.h if it is used from cached archive or from the url

**Comment by afrah** [comment]
The path is spack-src/src/wrappers/memory/memory_wrapper.h
