### ISSUE TITLE
SC16 Tutorial Slides

### ISSUE THREAD

**Issue by ax3l** [LLNL/spack#2332]
Hi,

@tgamblin did you already make the SC16 tutorial slides available? We would love spread the word!

update: for SC attendees, there is a authenticated download at http://bit.ly/sc16-tnotes

**Comment by ax3l** [comment]
@tgamblin for some reason, the link in read-the-docs is broken and correcting it to https://software.llnl.gov/spack/files/Spack-SC16-Tutorial.pdf seems also to not find the file

**Comment by tgamblin** [comment]
@ax3l try now -- our server switched to `https` and `software.llnl.gov` links stopped working.  I just switched the link back to `llnl.github.io` which will work even if `software.llnl.gov` starts working again.

**Comment by ax3l** [comment]
@tgamblin still does not work for me, I am talking about the *Download slides* link at this page: http://spack.readthedocs.io/en/latest/tutorial_sc16.html?highlight=supercomputing
