### ISSUE TITLE
Error in Environment.matching_specs() method

### ISSUE THREAD

**Issue by scottwittenburg** [LLNL/spack#23333]
Today I hit an error in this [line](https://codecov.io/gh/spack/spack/src/develop/lib/spack/spack/environment.py#L1577).  The problem there is that `root_matches` is a dictionary mapping concrete specs to abstract specs, but it is indexed with an integer.

I hit this while attempting to use `matching_spec()` in #22657, but you can also make it happen using the `spack location` command (or probably any command that uses `spack.cmd.matching_spec_from_env(spec)`).

### Steps to reproduce the issue

It seems you need to have an environment where a particular package appears both as a root and a dependency (so concretized separately), but that might not be the complete necessary/sufficient set of conditions. To create an example problem environment:

```console
$ spack env create foo
$ spack env activate foo
$ spack add readline
$ spack add ncurses ~termlib
$ spack concretize
```

Now the `foo` environment contains two `ncurses` specs.

### Error Message

To cause the error:

```console
$ spack -d location -s ncurses
==> [2021-04-28-15:41:16.385703] Imported location from built-in commands
==> [2021-04-28-15:41:16.387569] Imported location from built-in commands
==> [2021-04-28-15:41:16.388594] Reading config file /projects/spack/etc/spack/defaults/repos.yaml
==> [2021-04-28-15:41:16.392801] Reading config file /projects/spack/var/spack/environments/blah/spack.yaml
Traceback (most recent call last):
  File "/projects/spack/bin/spack", line 76, in <module>
    sys.exit(spack.main.main())
  File "/projects/spack/lib/spack/spack/main.py", line 772, in main
    return _invoke_command(command, parser, args, unknown)
  File "/projects/spack/lib/spack/spack/main.py", line 496, in _invoke_command
    return_val = command(parser, args)
  File "/projects/spack/lib/spack/spack/cmd/location.py", line 112, in location
    spec = spack.cmd.matching_spec_from_env(spec)
  File "/projects/spack/lib/spack/spack/cmd/__init__.py", line 192, in matching_spec_from_env
    return env.matching_spec(spec) or spec.concretized()
  File "/projects/spack/lib/spack/spack/environment.py", line 1588, in matching_spec
    return root_matches[0][1]
KeyError: 0
```

### Information on your system

```
$ spack debug report
* **Spack:** 0.16.1-2415-ceacc6706f
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-haswell
* **Concretizer:** original
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by scottwittenburg** [comment]
@scheibelp You have the honor of having touched that line last :stuck_out_tongue_winking_eye: 

Apart from just alerting you to this issue, which looks simple to fix, I also wonder if you can help me understand whether `matching_spec()` is right for my use case in #22657.  I'm wondering if I'm the only one hitting this because I'm doing something unexpected that should really be done another way.  If you're not the right person to share the thinking behind that method, maybe you know who is.

**Comment by scheibelp** [comment]
The problem is 

```
        if len(root_matches) == 1:
            return root_matches[0][1]
```

`root_matches` is a dictionary, and this code (that I wrote) is treating like a list and indexing the first element (but python is complaining because the dictionary does not have a `0` key). I can fix this tomorrow.

> Apart from just alerting you to this issue, which looks simple to fix, I also wonder if you can help me understand whether matching_spec() is right for my use case in #22657. 

Note that `Environment.matching_spec` will return a root spec or a dependency of a root spec. Also if the user provides a spec like

`x`

which would normally concretize to

`x+foo`

but the environment has

`x~foo`

then `matching_spec` would return `x~foo` (since that satisfies `x`). If those semantics work for you, then I think `matching_spec` would be a good fit. You would want to make sure to install the spec returned by `matching_spec`, rather than concretizing it separately (I would recommend this even if you concretize before calling `matching_spec`).

**Comment by scottwittenburg** [comment]
Thanks for that explanation @scheibelp.  For my use case (CI pipelines) I'm mainly going to want to install concrete specs (either via cli hash or concrete `spec.yaml` on disk).  In that case there should be no ambiguity for `matching_spec` to deal with, so probably nothing for me to worry about.  

Question in general though: In the environment I described above, there is a single root `ncurses` and a single distinct dep `ncurses`.  In that case `matching_spec('ncurses')` (providing a spec abstract enough that both satisfy it) returns the root one instead of raising an error indicating multiple matches in the environment.  Do you think that's what a user, typing `spack install ncurses`, would expect and thus the correct behavior?

**Comment by scheibelp** [comment]
> there is a single root ncurses and a single distinct dep ncurses. In that case matching_spec('ncurses') (providing a spec abstract enough that both satisfy it) returns the root one instead of raising an error indicating multiple matches in the environment

That's the intended behavior of `matching_spec`, but you can disagree on whether that's the correct behavior (i.e. if that's not what you want for your use case): an environment can have a package as a root and as a dependency, and we assume that when users ask about the package that they care about the root instance. This works well for the commands which currently use `matching_spec` like `spack build-env` and `spack location` (the user would likely be led to running these commands after examining `spack.yaml`, in which case only the info on the roots is available).

**Comment by scottwittenburg** [comment]
I agree with that behavior in general, thanks for providing background on the intentions there.

**Comment by scottwittenburg** [comment]
> You would want to make sure to install the spec returned by `matching_spec`, rather than concretizing it separately (I would recommend this even if you concretize before calling `matching_spec`).

Question about this: The line of code you just fixed in #22657 returns the abstract spec from the `(concrete, abstract)` pair, why do you recommend installing that?  As I was working on this just now, I was surprised to see that what I got back from `matching_spec` had a dag hash that did not previously exist in the environment (at all, as a dep or a root).  For my use case, I don't want to install something new, I want to be sure to install one of the specs already in the environment, or else nothing at all.

**Comment by scottwittenburg** [comment]
Looking again, the docstring of that method does say "find a matching concretized spec in the environment".  Furthermore, in the case where there's exactly one match (be it dep or root) in the environment, the concrete spec is returned.  Is it possible it's a bug that the abstract spec rather than the concrete spec is returned when `len(root_matches) == 1`?

**Comment by scheibelp** [comment]
https://github.com/spack/spack/pull/22657 appears to fix this, so I updated the PR description to reflect that.

> Looking again, the docstring of that method does say "find a matching concretized spec in the environment". Furthermore, in the case where there's exactly one match (be it dep or root) in the environment, the concrete spec is returned. Is it possible it's a bug that the abstract spec rather than the concrete spec is returned when len(root_matches) == 1?

I missed that. #22657 handles that
