### ISSUE TITLE
`spack env activate` does not traverse run dependencies for environment modifications

### ISSUE THREAD

**Issue by vchuravy** [LLNL/spack#23368]
Moving this from #gripes on Slack.

Mine @SteVwonder question was:

> Why does spack env activate not run setup_run_environment for dependencies of packages listed in an env yaml?  Due to this behavior spack load flux-sched behaves differently from spack env activate . with a yaml file containing flux-sched as the only package.

@tgamblin answer was:

> `_env_modifications_for_default_view` doesn’t currently traverse run deps, but it really should

**Comment by tgamblin** [comment]
@scheibelp do you have time to take a stab at this one?

**Comment by scheibelp** [comment]
I think I can look at this on May 4th

EDIT (5/4): other issues are taking longer than expected. My new estimated start date for this is 5/6.

**Comment by haampie** [comment]
So, if `setup_run_environment` is supposed to be called for run type dependencies when loading a root spec (which I think makes a lot of sense), why do we have `setup_dependent_run_environment` at all?
