### ISSUE TITLE
Error during CMake installation on OSX Sierra 10.12.1

### ISSUE THREAD

**Issue by MathiasMen** [LLNL/spack#2337]
During the installation of CMake (actually dealii but in the intermediate step) I get the following error: 
```
Error: Command exited with status 9:
'./bootstrap' '--prefix=/Users/mathiasmentler/Documents/spack/opt/spack/darwin-sierra-x86_64/gcc-6.2.0/cmake-3.6.1-j2wwd3jknj27v6vgxt6amc2pssul52fj' '--parallel=4' '--no-system-jsoncpp' '--system-libs' '--no-qt-gui' '--' '-DCMAKE_USE_OPENSSL=ON'
```

I am sitting on MacOS Sierra 10.12.1, have the command-line-tools installed and updated, updated XCode to version 8.1 and tried installing with clang (8.0.0) and gcc (6.2.0), both to no avail. I also tried installing CMake versions 3.6.0 and 3.5.2 and got the same error. In the `spack-build.out` file (which is attached) I get a ton of errors along the lines of something like:
```
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFURL.h:1066:60: error: 'introduced' was not declared in this scope
```
I also attached the `cmake-bootstrap.log`.

Thanks in advance

Mathias

[cmake_bootstrap.log.txt](https://github.com/LLNL/spack/files/592374/cmake_bootstrap.log.txt)
[spack-build.out.txt](https://github.com/LLNL/spack/files/592375/spack-build.out.txt)

**Comment by davydden** [comment]
I did minor formatting to make OP look better.

**Comment by davydden** [comment]
@MathiasMen `cmake` is known to fail with GCC on macOS, see https://github.com/LLNL/spack/issues/1847. Could you please add logs for build failure with `clang`? Also the content of `~/.spack/compilers.yaml` would be good to have. Other info: do you have `homebrew` or `macports` on your mac?

**Comment by MathiasMen** [comment]
@davydden I have `homebrew` but not `macports` installed. The content of my `~/.spack/darwin/compilers.yaml` is:
```compilers:
- compiler:
    flags: {}
    modules: []
    operating_system: sierra
    paths:
      cc: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
      cxx: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
    spec: clang@8.0.0-apple
- compiler:
    flags: {}
    modules: []
    operating_system: sierra
    paths:
      cc: /usr/local/bin/gcc-6
      cxx: /usr/local/bin/g++-6
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
    spec: gcc@6.2.0
- compiler:
    flags: {}
    modules: []
    operating_system: sierra
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
    spec: gcc@4.2.1
```

After rebooting due to a non-related issue and trying to install the dealii-package with clang however, spack now manages to install CMake but hits an error trying to install openblas with the error: 

```
==> Executing phase : 'install'
==> Error: Command exited with status 1:
'/Users/mathiasmentler/Documents/spack/lib/spack/env/cc' '-o' 'check' 'test_cblas_dgemm.o' '-L/Users/mathiasmentler/Documents/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/openblas-0.2.19-7qdxwznmqzlbqtusssagtxkypivod6ct/lib' '-lopenblas' '-lpthread'

/Users/mathiasmentler/Documents/spack/var/spack/repos/builtin/packages/openblas/package.py:136, in check_install:
     122      def check_install(self, spec):
     123          source_file = join_path(os.path.dirname(self.module.__file__),
     124                                  'test_cblas_dgemm.c')
     125          blessed_file = join_path(os.path.dirname(self.module.__file__),
     126                                   'test_cblas_dgemm.output')
     127  
     128          include_flags = ["-I%s" % join_path(spec.prefix, "include")]
     129          link_flags = self.lapack_libs.ld_flags.split()
     130          if self.compiler.name == 'intel':
     131              link_flags.extend(["-lifcore"])
     132          link_flags.extend(["-lpthread"])
     133          if '+openmp' in spec:
     134              link_flags.extend([self.compiler.openmp_flag])
     135  
  >> 136          output = compile_c_and_execute(source_file, include_flags, link_flags)
     137          compare_output_file(output, blessed_file)
```

I attached the log for openblas. 

[spack-build.out.txt](https://github.com/LLNL/spack/files/592489/spack-build.out.txt)

**Comment by davydden** [comment]
@MathiasMen wait, but it's a different problem now, namely with `openblas`. 

Looking it the logs, I see that are not using the most recent version of Spack, i can tell it from
```
==> 'make' '-j4' 'CC=/Users/mathiasmentler/Documents/spack/lib/spack/env/clang/clang' 'FC=/Users/mathiasmentler/Documents/spack/lib/spack/env/f77' 'MAKE_NO_J=1' 'libs' 'netlib' 'shared'
OpenBLAS: Detecting fortran compiler failed. Cannot compile LAPACK. Only compile BLAS.
```
which shall be different after https://github.com/LLNL/spack/pull/2192 . 

Please do `git pull` and upload logs for `cmake`. If you still have issues with `openblas`, please create a separate issue for it.
