### ISSUE TITLE
Installation issue: intel-oneapi-mpi

### ISSUE THREAD

**Issue by ashki23** [LLNL/spack#23388]
### Steps to reproduce the issue

```console
$ spack install intel-oneapi-mpi
==> Installing intel-oneapi-mpi-2021.2.0-jaxbozu6xiyplv326azedkvt3ha4xc5s
==> No binary for intel-oneapi-mpi-2021.2.0-jaxbozu6xiyplv326azedkvt3ha4xc5s found: installing from source
==> Using cached archive: /opt/spack/var/spack/cache/_source-cache/archive/d0/d0d4cdd11edaff2e7285e38f537defccff38e37a3067c02f4af43a3629ad4aa3
==> No patches needed for intel-oneapi-mpi
==> intel-oneapi-mpi: Executing phase: 'install'
==> Error: RuntimeError: install failed

/opt/spack/lib/spack/spack/build_systems/oneapi.py:61, in install:
         58                 '--install-dir', prefix)
         59
         60        # Some installers have a bug and do not return an error code when failing
  >>     61        if not isdir(join_path(prefix, self.component_dir)):
         62            raise RuntimeError('install failed')

See build log for details:
  /tmp/root/spack-stage/spack-stage-intel-oneapi-mpi-2021.2.0-jaxbozu6xiyplv326azedkvt3ha4xc5s/spack-build-out.txt
```

### Information on your system

```consule
$ spack debug report
* **Spack:** 0.16.0-2536-e359249d7e
* **Python:** 3.8.5
* **Platform:** linux-ubuntu20.04-skylake
* **Concretizer:** original
```

### Additional information

Please click the following links to see the build files:

* [spack-build-out.txt](https://github.com/ashki23/spack-bug-report/blob/main/intel-oneapi-mpi-2021.2.0/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/ashki23/spack-bug-report/blob/main/intel-oneapi-mpi-2021.2.0/spack-build-env.txt)

I have successfully installed `intel-oneapi-compilers@2021.2.0` through Spack.

### Maintainers

@DanVev
@rscohn2 

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by rscohn2** [comment]
I did not consider the possibility that someone would invoke spack as root. While I work on a fix, you need to do this in between installing oneapi packages:
```
sudo rm -r /var/intel/installercache
```

**Comment by ashki23** [comment]
Thank you, @rscohn2. It solved the issue.

**Comment by rscohn2** [comment]
@ashki23 after #23401 is merged, you will not have to manually remove the installercache.

**Comment by rscohn2** [comment]
@tldahlgren : I recommend that you close this issue. #23401 resolves the issue.

**Comment by alalazo** [comment]
Closing this issue following https://github.com/spack/spack/issues/23388#issuecomment-850081620
