### ISSUE TITLE
Installation issue: hdf-eos5 fails to build with hdf5+szip

### ISSUE THREAD

**Issue by payerle** [LLNL/spack#23411]
When trying to build hdf-eos5 using an hdf5 built with +szip, I get an error during configure
about lack of an --with-szlib flag.

It also looks like the check for  zlib libraries will fail if hdf was not built with it it
(e.g. using if self.spec['zlib']: instead of ``if 'zlib' in self.spec:```)

Basically looks to be the hdf-eos5 version of issue #23345 for hdf-eos2.

### Steps to reproduce the issue

```console
$ spack install hdf-eos5 ^hdf5+szip
...
checking for hdf5 szip encoding filter... yes
configure: error: HDF5 was linked with SZIP, but --with-szlib was not given
```

### Information on your system

```console
$ spack debug report
* **Spack:** 0.16.1-2432-16111354aa
* **Python:** 3.6.8
* **Platform:** linux-rhel8-x86_64
* **Concretizer:** original
```

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/6417555/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/6417556/spack-build-env.txt)

No maintainers for hdf-eos2, but IIRC I (@payerle) am the one who uploaded the original version.

### General information

- [x ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x ] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x ] I have uploaded the build log and environment files
- [x ] I have searched the issues of this repo and believe this is not a duplicate

**Comment by sethrj** [comment]
Fixed by https://github.com/spack/spack/pull/23412
