### ISSUE TITLE
Error on Cray Milan system, "Could not determine a platform for this machine"

### ISSUE THREAD

**Issue by pelahi** [LLNL/spack#23439]
I am testing Spack on a Cray (centos:8) machine with Milan CPUs (AMD EPYC 7713 64-Core Processor). Spack produces the following error message with any command. 

### Error Messages  
```console
$ spack --debug --stacktrace find 
/group/pawsey0001/pelahi/amd-milan-tests/codes/spack/lib/spack/spack/util/executable.py:188 ==> [2021-05-05-13:09:03.100362] '/bin/bash' '--norc' '--noprofile' '-lc' 'echo $CRAY_CPU_TARGET'
/group/pawsey0001/pelahi/amd-milan-tests/codes/spack/lib/spack/spack/main.py:777 ==> [2021-05-05-13:09:03.123136] NoPlatformError: Could not determine a platform for this machine.
/group/pawsey0001/pelahi/amd-milan-tests/codes/spack/lib/spack/spack/error.py:55 ==> [2021-05-05-13:09:03.145271] Error: Could not determine a platform for this machine.
Traceback (most recent call last):
  File "/group/pawsey0001/pelahi/amd-milan-tests/codes/spack/lib/spack/spack/main.py", line 751, in main
    setup_main_options(args)
  File "/group/pawsey0001/pelahi/amd-milan-tests/codes/spack/lib/spack/spack/main.py", line 451, in setup_main_options
    spack.config.set('config:debug', True, scope='command_line')
  File "/group/pawsey0001/pelahi/amd-milan-tests/codes/spack/lib/spack/spack/config.py", line 906, in set
    return config.set(path, value, scope)
  File "/group/pawsey0001/pelahi/amd-milan-tests/codes/spack/lib/spack/llnl/util/lang.py", line 762, in __getattr__
    return getattr(self.instance, name)
  File "/group/pawsey0001/pelahi/amd-milan-tests/codes/spack/lib/spack/llnl/util/lang.py", line 752, in instance
    self._instance = self.factory()
  File "/group/pawsey0001/pelahi/amd-milan-tests/codes/spack/lib/spack/spack/config.py", line 805, in _config
    _add_platform_scope(cfg, ConfigScope, name, path)
  File "/group/pawsey0001/pelahi/amd-milan-tests/codes/spack/lib/spack/spack/config.py", line 758, in _add_platform_scope
    platform = spack.architecture.platform().name
  File "/group/pawsey0001/pelahi/amd-milan-tests/codes/spack/lib/spack/llnl/util/lang.py", line 207, in _memoized_function
    func.cache[args] = func(*args)
  File "/group/pawsey0001/pelahi/amd-milan-tests/codes/spack/lib/spack/spack/architecture.py", line 523, in _platform
    return platform_cls()
  File "/group/pawsey0001/pelahi/amd-milan-tests/codes/spack/lib/spack/spack/platforms/cray.py", line 61, in __init__
    raise NoPlatformError()
spack.architecture.NoPlatformError: Could not determine a platform for this machine.
```

_This only applies to spack develop branch including and after the_
```
commit 8cf6ad99170a64becb932c6e4c255c8adf4230c2 (HEAD)
Author: Massimiliano Culpo <massimiliano.culpo@gmail.com>
Date: Thu Mar 18 08:23:09 2021 +0100
 
archspec: update to latest version (#22357)
```

An update to archspec has caused an issue. I have raised this bug here and will also raise this issue in archspec. 

For reference, using the commit just before the update to arch spec gives 
```console
$ git checkout 4c9c5393f1fad00b7e8c77661a02b236db2d0e40
$ spack --version 
0.16.1-1746-4c9c5393f1
$ spack --debug --stacktrace find
/group/pawsey0001/pelahi/amd-milan-tests/codes/spack/lib/spack/spack/util/executable.py:182 ==> [2021-05-05-13:12:25.484080] '/bin/bash' '--norc' '--noprofile' '-lc' 'echo $CRAY_CPU_TARGET'
/group/pawsey0001/pelahi/amd-milan-tests/codes/spack/lib/spack/spack/platforms/cray.py:154 ==> [2021-05-05-13:12:25.509091] default to front-end architecture
/group/pawsey0001/pelahi/amd-milan-tests/codes/spack/lib/spack/spack/cmd/__init__.py:122 ==> [2021-05-05-13:12:25.574501] Imported find from built-in commands
/group/pawsey0001/pelahi/amd-milan-tests/codes/spack/lib/spack/spack/cmd/__init__.py:122 ==> [2021-05-05-13:12:25.575478] Imported find from built-in commands
/group/pawsey0001/pelahi/amd-milan-tests/codes/spack/lib/spack/spack/config.py:969 ==> [2021-05-05-13:12:25.578582] Reading config file /group/pawsey0001/pelahi/amd-milan-tests/codes/spack/etc/spack/defaults/config.yaml
/group/pawsey0001/pelahi/amd-milan-tests/codes/spack/lib/spack/spack/database.py:364 ==> [2021-05-05-13:12:25.634373] DATABASE LOCK TIMEOUT: 3s
/group/pawsey0001/pelahi/amd-milan-tests/codes/spack/lib/spack/spack/database.py:368 ==> [2021-05-05-13:12:25.634652] PACKAGE LOCK TIMEOUT: No timeout
/group/pawsey0001/pelahi/amd-milan-tests/codes/spack/lib/spack/spack/cmd/find.py:253 ==> [2021-05-05-13:12:25.638857] 3 installed packages
-- cray-cnl6-haswell / gcc@7.2.0 --------------------------------
mpich@7.7.0  netlib-scalapack@2.1.0  openblas@0.3.9
```

### Information on your system

Spack reports (for versions pre the commit that breaks spack)
```console
$ spack debug report
* **Spack:** <=0.16.1-1746-4c9c5393f1
* **Python:** 3.6.8
* **Platform:** cray-centos8-zen2
* **Concretizer:** original
```

At the commit 
```console 
./bin/spack debug report
* **Spack:** >=0.16.1-1747-8cf6ad9917
* **Python:** 3.6.8
==> Error: Could not determine a platform for this machine.
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

**Comment by pelahi** [comment]
This is an update to say that error occurs because of an update to `lib/spack/external/archspec/json/cpu/microarchitectures.json`. I am not certain why the updates to archspec's json file are causing these issues (the specific pull requests are https://github.com/archspec/archspec-json/pull/25 and I have also tried the changes to the json file that are in https://github.com/archspec/archspec-json/pull/29). I will continue to dig further but some guidance would be useful if I am going to create a PR that will address this issue.

**Comment by pelahi** [comment]
Another update, this may be due to the an older linux kernel in use on the system which does not recognise the zen3 architecture and may not be inherently due to spack, but rather the interplay between the OS and archspec (the /proc/cpuinfo is missing a microcode entry).

**Comment by pelahi** [comment]
I have tested the latest versions of spack and the commit that included zen3 in archspec's json file one the same machine with several different kernels. Currently using Fedora live 31 () and 34 (5.11.12-300.fc34.x86_64), both linux kernels >4, the error is not present. However, older kernels (4.18.0-240.22.1.el8_3.x86_64) fail. It does appear to be an issue with the linux kernel and the interplay with archspec. An exhaustive search of kernels is not possible but there does appear to be an issue with AMD zen3 Milan's, kernels < 5.3 and archspec.

**Comment by alalazo** [comment]
@pelahi Thanks for the extensive report. Can you post a single entry of `/proc/cpuinfo` in the case that fails and one in the case where it succeeds?

**Comment by pelahi** [comment]
Hi @alalazo , the missing entry was `microcode`. Though I am not certain that in itself will indicate whether archspec will work. Some OS's do not have this entry but worked. We have tested a few other kernels and it is not obvious what kernels will work but we have had 100% success with kernels of >=5.3.x. For older kernels running on Milan CPUs where spack does not work, it is simply a matter of removing the zen3 definition in the `lib/spack/external/archspec/json/cpu/microarchitectures.json`. 

I consider this issue closed as I will not be able to test all OS on Milan architecture. Feel free to test this issue further and close this issue.

**Comment by alalazo** [comment]
> the missing entry was microcode

I don't see any `microcode` listed in the JSON file. Am I missing something?

**Comment by pelahi** [comment]
Ah, I understand the confusion. There was no missing entry in the json file. If there is an entry in the json file for zen3, then on Milan systems running older kernels (such as that of CentOS 8.3), spack cannot detect the platform. When I inspected the `/proc/cpuinfo` information produced by the kernel, this file did not contain a `microcode` entry. This entry is there when running the same OS on other CPUs (Rome, intel cpus) but is missing when running on a Milan system. The absence of this entry might be indicative that a kernel is too old and may not work with archspec.

**Comment by pelahi** [comment]
Sample `/proc/cpuinfo` on several different systems. 
```
$ more /proc/cpuinfo 
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel(R) Xeon(R) Silver 4215 CPU @ 2.50GHz
stepping        : 7
microcode       : 0x5000029
cpu MHz         : 1000.213
cache size      : 11264 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 8
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
...
```

On CentOS 8.3 running on a rome machine

```
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 23
model           : 49
model name      : AMD EPYC 7452 32-Core Processor
stepping        : 0
microcode       : 0x8301025
cpu MHz         : 3277.221
cache size      : 512 KB
physical id     : 0
siblings        : 64
core id         : 0
cpu cores       : 32
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 16
wp              : yes
```

Same but on Milan 
```
processor       : 0
vendor_id       : AuthenticAMD
cpu family      : 25
model           : 1
model name      : AMD EPYC 7713 64-Core Processor
stepping        : 1
cpu MHz         : 1608.016
cache size      : 512 KB
physical id     : 0
siblings        : 128
core id         : 0
cpu cores       : 64
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 16
wp              : yes
```

**Comment by alalazo** [comment]
Closing per https://github.com/spack/spack/issues/23439#issuecomment-839546594
