### ISSUE TITLE
QT5.15.2 +webkit+opengl concretize bug with python versions

### ISSUE THREAD

**Issue by nebulism** [LLNL/spack#23456]
All,
I've encountered a concretize error when the starting off a new spack repo and doing an install of qt+webkit+opengl.

**Reproduce the error**
1.  Start off with fresh spack repo
2. Use gcc/9.3.0 or other compiler (doubt this is an issue here)
3. Create an environment --without-view
4. spack install qt+webkit+opengl

**Result of error**
```
==> Error: An unsatisfiable version constraint has been detected for spec:

    python@2.7.18%gcc@9.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib arch=linux-rhel7-broadwell
        ^bzip2@1.0.8%gcc@9.3.0~debug~pic+shared arch=linux-rhel7-broadwell
            ^diffutils@3.7%gcc@9.3.0 arch=linux-rhel7-broadwell
                ^libiconv@1.16%gcc@9.3.0 arch=linux-rhel7-broadwell
        ^expat
        ^gdbm@1.19%gcc@9.3.0 arch=linux-rhel7-broadwell
            ^readline@8.1%gcc@9.3.0 arch=linux-rhel7-broadwell
                ^ncurses@6.2%gcc@9.3.0~symlinks+termlib abi=none arch=linux-rhel7-broadwell
                    ^pkgconf@1.7.4%gcc@9.3.0 arch=linux-rhel7-broadwell
        ^gettext@0.21%gcc@9.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-rhel7-broadwell
            ^libxml2@2.9.10%gcc@9.3.0~python arch=linux-rhel7-broadwell
                ^xz@5.2.5%gcc@9.3.0~pic arch=linux-rhel7-broadwell
                ^zlib@1.2.11%gcc@9.3.0+optimize+pic+shared arch=linux-rhel7-broadwell
            ^tar@1.34%gcc@9.3.0 arch=linux-rhel7-broadwell
        ^libffi@3.3%gcc@9.3.0 arch=linux-rhel7-broadwell
        ^openssl@1.1.1k%gcc@9.3.0~docs+systemcerts arch=linux-rhel7-broadwell
            ^perl@5.32.1%gcc@9.3.0+cpanm+shared+threads arch=linux-rhel7-broadwell
                ^berkeley-db@18.1.40%gcc@9.3.0+cxx~docs+stl arch=linux-rhel7-broadwell
        ^sqlite@3.35.4%gcc@9.3.0+column_metadata+fts~functions~rtree arch=linux-rhel7-broadwell
        ^util-linux-uuid@2.36.2%gcc@9.3.0 arch=linux-rhel7-broadwell


while trying to concretize the partial spec:

    meson@0.49.2:
```
**Spack Debug report**
* **Spack:** 0.16.1-2515-9a3513b3ec
* **Python:** 3.6.8
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** original

**More Details**
Looks like this references PR https://github.com/spack/spack/pull/22928

**Comment by adamjstewart** [comment]
It looks like this concretization issue is solved by the new concretizer. If you want to stick with the old concretizer, you'll have to explicitly specify which versions of the package and its dependencies you want to build so as to avoid the meson dependency. @sethrj may have some tips.

**Comment by sethrj** [comment]
@nebulism Qt+webkit requires Python 2.7, but Qt requires glib which requires meson which requires Python 3.5 or higher. I'd try building with `^glib@2.56.4` to remove the meson dependency; and if that doesn't work, install clingo and use the new concretizer as Adam suggests.

**Comment by nebulism** [comment]
Thanks all going to try this now!

**Comment by nebulism** [comment]
Trying Clingo now, using the old concretizer seemed to cause issues even when using ^glib@2.56.4

**Comment by sethrj** [comment]
I'm curious what it concretizes to when it's done 🤔 Probably some older versions of multiple software components. You're the third person I know of who's had issues with qt+webkit so maybe someone has a patch for getting it to work with python 3? Is QtWebKit deprecated?

**Comment by nebulism** [comment]
I'm beginning to wonder the same thing , and whether QtWebKit is worth the trouble.  I installed Clingo and it did concretize to the point of building Qt.  So that was a success.  The build itself failed though.  If I get some time next week, I'll dig into the failure.  Thank you for all the assistance!

**Comment by nebulism** [comment]
@sethrj  , @adamjstewart  I am going to close this topic as QWebKit is deprecated in light of there being QWebEngine.  We may want to update the spack entry variant to remove webkit entirely?
