### ISSUE TITLE
Error when installing any python package

### ISSUE THREAD

**Issue by kserradell** [LLNL/spack#2347]
Hello,

I'm getting an error when installing any py-* package. It seems there are error with python core modules.

I'm on openSUSE 13.2 x86_64, 3.16.7-21-desktop and gcc version 4.9.2 (GCC).

Thank you very much,

[spack-build.out.txt](https://github.com/LLNL/spack/files/594300/spack-build.out.txt)

**Comment by alalazo** [comment]
Can you check if this is a duplicate of #2253 and as such will be solved  by #2295 ?

**Comment by kserradell** [comment]
@alalazo, yes it is. The workaround of symlinking 

`lib-dynload -> ../../lib64/python2.7/lib-dynload/`

works perfectly. I just did a quick test but I could build py-numpy.

Thanks again.
