### ISSUE TITLE
Installation issue: libbsd with Intel oneAPI compiler `intel@2021.2.0`

### ISSUE THREAD

**Issue by ikitayama** [LLNL/spack#23486]
### Steps to reproduce the issue

```console
$ spack install libbsd %intel
```

Which tries to apply a patch, but it does not succeed.

### Additional information

* [spack-build-out.txt]()
* [spack-build-env.txt]()

### General information

- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [ ] I have searched the issues of this repo and believe this is not a duplicate

**Comment by ikitayama** [comment]
No one is assigned to this package.

**Comment by ikitayama** [comment]
@pramodk this is a required package by NEURON and building it with Intel compiler fails.

**Comment by ikitayama** [comment]
To be specific, Intel oneAPI compilers.

**Comment by ikitayama** [comment]
I wasn't `load`ing `intel-oneapi-compilers` priro to building `libbsd` Closing this.

**Comment by pramodk** [comment]
> @pramodk this is a required package by NEURON and building it with Intel compiler fails.

this is indirect dependency of some other package? NEURON doesn't depend on this directly.

**Comment by ikitayama** [comment]
Sorry I wasn’t loading oneAPI compiler that’s why I was getting an error.

**Comment by ikitayama** [comment]
Well, I still get this:

```
==> Installing libbsd-0.11.3-ltxu4fow5ln4a7op45flx3smicfcwws3
==> No binary for libbsd-0.11.3-ltxu4fow5ln4a7op45flx3smicfcwws3 found: installing from source
==> Using cached archive: /p/scratch/cjzam11/kitayama1/projects/spack/var/spack/cache/_source-cache/archive/ff/ff95cf8184151dacae4247832f8d4ea8800fa127dbd15033ecfe839f285b42a1.tar.xz
Reversed (or previously applied) patch detected!  Assume -R? [n]
```

@pramodk would you mind checking the build with the Intel oneAPI compiler? Thanks!

**Comment by ikitayama** [comment]
The build initiated as follows:
```
spack install neuron@develop+python+coreneuron~mpi %intel
```

**Comment by pramodk** [comment]
Ok. Thanks for changing the title as the issue is not coming from neuron.
