### ISSUE TITLE
Installation issue: py-matplotlib

### ISSUE THREAD

**Issue by ghost** [LLNL/spack#23509]
### Steps to reproduce the issue

```console
$ spack install py-matplotlib%clang
  >> 582    clang-12: error: linker command failed with exit code 1 (use -v to 
            see invocation)
  >> 583    error: command '/scratch/dsjense/spack/lib/spack/env/clang/clang++'
             failed with exit status 1
```

### Information on your system

This fails to build on RHEL7, Ubuntu 18, and Ubuntu 20 with Clang > 10
```
* **Spack:** 0.16.1-2490-5a747b9
* **Python:** 2.7.5
* **Platform:** linux-rhel7-ivybridge
* **Concretizer:** original
```

### Additional information
@adamjstewart 
[This forum post](https://github.com/termux/termux-packages/issues/5787) suggested turning off link-time optimization when using Clang.  I created a branch with a possible fix [here](https://github.com/dsjense/spack/tree/matplotlib-clang-lto).  I'm not sure if this affects all versions of Clang but I definitely had problems with llvm@10,12.

* [spack-build-out.txt]()
* [spack-build-env.txt]()

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Thanks for the bug report! I only use Apple Clang, so I can't test this, but if you want to open a PR I can take a look!
