### ISSUE TITLE
Does SuSE cPickle 2.7 fix have unintended consequences?

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#2350]
@davydden 
Sorry I didn't see this before it was committed; but I just looked at #2295.  The title implies it affects only Python 2.7, but the code seems to run on all versions of Python.  Since the problem was never reported for Python3, I am reluctant to add a patch that will affect Python3.

Ideally, I would like to see the following tests on SuSE 13:

1. Try to install Python 2.7 without the patch (we know this doesn't work)
2. Try to install Python 2.7 with the patch (we know this does work)
3. Try to install Python 3.5 without the patch
4. Try to install Python 3.5 with the patch

(Once Python is installed, I would try `import pickle` for Python3).

Would you be able to please run tests (3) and (4)?  This will either:
  a) Confirm that the patch is necessary for SuSE 13 on Python3 as well
  b) Show that the patch was not necessary but doesn't break anything.
  c) Show that the patch actually breaks Python3.

**Comment by davydden** [comment]
@christianbaensch could you please try install `python@3.5` to with current Spack to see if it works with the symlinks of `lib64/pythonX.Y/lib-dynload` to `lib/pythonX.Y/lib-dynload`?

**Comment by christianbaensch** [comment]
I´ve tried an installation with python-3.5.2 and it works well with the symlinks!

**Comment by citibeth** [comment]
Thanks for testing!

**Comment by skosukhin** [comment]
> Ideally, I would like to see the following tests on SuSE 13:
> 
>    1. Try to install Python 2.7 without the patch (we know this doesn't work)
>    2. Try to install Python 2.7 with the patch (we know this does work)
>    3. Try to install Python 3.5 without the patch
>    4. Try to install Python 3.5 with the patch

1. Doesn't work
2. Works
3. Doesn't work
4. Works

**Comment by citibeth** [comment]
Thank you; that looks to me like a full endorsement of the patch.

**Comment by becker33** [comment]
Closing this issue as @citibeth created it and has considered it resolved.
