### ISSUE TITLE
Installation issue: neuron: can't fetch 8.0 release 

### ISSUE THREAD

**Issue by ikitayama** [LLNL/spack#23523]
### Steps to reproduce the issue

```console
$ spack edit neuron

[...]
add 8.0 like below:
version('develop', branch='master', submodules='True')
```

### General information

- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by ikitayama** [comment]
@pramodk et al., would you upload the 8.0 tarball?

**Comment by pramodk** [comment]
@ikitayama : it's not tarball issue but 8.0 version is not added to the spack yet. Tarballs are already uploaded (e.g. via GitHub releases). With 8.0 release, spack recipe needs quite some changes. Will try to that in coming week.

**Comment by ikitayama** [comment]
@pramodk I'll leave it to you guys then!
