### ISSUE TITLE
Installation issue: python

### ISSUE THREAD

**Issue by arekfu** [LLNL/spack#23562]
### Steps to reproduce the issue

```
$ spack install intel-oneapi-compilers
$ spack compiler add `spack location -i intel-oneapi-compilers`/compiler/latest/linux/bin
$ spack install python@3.8.10%oneapi
```

### Information on your system

```
$ spack debug report
* **Spack:** 0.16.1-2581-aacba57
* **Python:** 3.5.2
* **Platform:** linux-ubuntu16.04-sandybridge
* **Concretizer:** original
```

No relevant configuration details (reproducible on a clean `spack` clone).

### Additional information

The `install` phase is stuck. `top` shows a few `python` processes running at 100%. Attaching with `gdb` to one of these processes shows that the process is stuck in an infinite loop in `_Py_HashDouble()` around [here](https://github.com/python/cpython/blob/b05955d6f5f149523b5855a335444b7c6324bdb7/Python/pyhash.c#L116) (the `m` variable is equal to `inf` and the `while` loop never ends).

* [spack-build-out.txt](https://github.com/spack/spack/files/6460615/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/6460617/spack-build-env.txt)

@adamjstewart @skosukhin 

I was unsure if I should mention the maintainers of `intel-oneapi-compilers` too.

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
How long did you let it run for? I don't see anything obviously suspicious in the log. Are you able to build Python without Spack?

**Comment by arekfu** [comment]
I let it run for more than 3 hours. I don't think it can escape that while loop if `m=inf`.

Also, if I download Python 3.8.10 from the web, I cannot build it with the OneAPI compiler installed by Spack. I have tried to install the OneAPI compiler on my own but I am having problems.

**Comment by arekfu** [comment]
I found that passing `CFLAGS="-fp-model=strict"` to `configure` fixes the problem. This sounds like another overzealous non-IEEE754 Intel optimization...

**Comment by adamjstewart** [comment]
Want to submit a PR to add that flag to the Spack package? If not I can get to it sometime next week.

**Comment by arekfu** [comment]
Incoming!
