### ISSUE TITLE
virtual packages seem to be ignoring namespaces

### ISSUE THREAD

**Issue by payerle** [LLNL/spack#23640]
I created a spack repo 'hacks' with higher precedence than builtin, and when I place new versions of packages in builtin into hacks, I am not always having the 'hacks' version overriding the 'builtin' version.  This seems to be happening only with virtual packages.

### Steps to reproduce the issue

1. Clone a clean spack from git
```console 
$ git clone https://github.com/spack/spack.git spack.test
```
2. Copy the etc/spack/default/*.yaml config files to etc/spack.  Edit compilers.yaml to use the system default compiler.  Configure packages.yaml to make libtirpc the default provider for rpc, and libszip the default provider for szip.
3. Create a 'hacks' repo and give it higher precedence that 'builtin' (i.e. put ahead of builtin in repos.yaml)
4. Copy the following packages from builtin to hacks repo: bison, libszip, and libtirpc
5. Issue the command
```console
$ spack spec -N hdf
```
This reports:
```console
==> Warning: gcc@rh7-4.8.5 cannot build optimized binaries for "skylake". Using best target possible: "haswell"
builtin.hdf@4.2.14%gcc@rh7-4.8.5+external-xdr+fortran~java~netcdf+pic~shared+szip arch=linux-rhel7-haswell
    ^hacks.bison@3.7.6%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
        ^builtin.diffutils@3.7%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
            ^builtin.libiconv@1.16%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
        ^builtin.m4@1.4.18%gcc@rh7-4.8.5+sigsegv patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 arch=linux-rhel7-haswell
            ^builtin.libsigsegv@2.13%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
        ^builtin.perl@5.32.1%gcc@rh7-4.8.5+cpanm+shared+threads arch=linux-rhel7-haswell
            ^builtin.berkeley-db@18.1.40%gcc@rh7-4.8.5+cxx~docs+stl patches=b231fcc4d5cff05e5c3a4814f6a5af0e9a966428dc2176540d2c05aff41de522 arch=linux-rhel7-haswell
            ^builtin.gdbm@1.19%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
                ^builtin.readline@8.1%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
                    ^builtin.ncurses@6.2%gcc@rh7-4.8.5~symlinks+termlib abi=none arch=linux-rhel7-haswell
                        ^builtin.pkgconf@1.7.4%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
    ^builtin.flex@2.6.3%gcc@rh7-4.8.5+lex~nls arch=linux-rhel7-haswell
        ^builtin.findutils@4.8.0%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
    ^builtin.libjpeg-turbo@2.0.6%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
        ^builtin.cmake@3.20.2%gcc@rh7-4.8.5~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-rhel7-haswell
            ^builtin.openssl@1.1.1k%gcc@rh7-4.8.5~docs+systemcerts arch=linux-rhel7-haswell
                ^builtin.zlib@1.2.11%gcc@rh7-4.8.5+optimize+pic+shared arch=linux-rhel7-haswell
        ^builtin.nasm@2.15.05%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
    ^builtin.libszip@2.1.1%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
    ^builtin.libtirpc@1.2.6%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
        ^builtin.krb5@1.18.2%gcc@rh7-4.8.5+shared patches=3d75052730690579484e65a5bf0f92f6c3b20d9c43a413862d087774f431d9e9 arch=linux-rhel7-haswell
```

Note that bison dependency uses hacks.bison, but libszip and libtirpc still using builtin.
If I instead issue
```console
$ spack spec -N hdf ^libtirpc
```
I get 
```
==> Warning: gcc@rh7-4.8.5 cannot build optimized binaries for "skylake". Using best target possible: "haswell"
builtin.hdf@4.2.14%gcc@rh7-4.8.5+external-xdr+fortran~java~netcdf+pic~shared+szip arch=linux-rhel7-haswell
    ^hacks.bison@3.7.6%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
        ^builtin.diffutils@3.7%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
            ^builtin.libiconv@1.16%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
        ^builtin.m4@1.4.18%gcc@rh7-4.8.5+sigsegv patches=3877ab548f88597ab2327a2230ee048d2d07ace1062efe81fc92e91b7f39cd00,fc9b61654a3ba1a8d6cd78ce087e7c96366c290bc8d2c299f09828d793b853c8 arch=linux-rhel7-haswell
            ^builtin.libsigsegv@2.13%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
        ^builtin.perl@5.32.1%gcc@rh7-4.8.5+cpanm+shared+threads arch=linux-rhel7-haswell
            ^builtin.berkeley-db@18.1.40%gcc@rh7-4.8.5+cxx~docs+stl patches=b231fcc4d5cff05e5c3a4814f6a5af0e9a966428dc2176540d2c05aff41de522 arch=linux-rhel7-haswell
            ^builtin.gdbm@1.19%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
                ^builtin.readline@8.1%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
                    ^builtin.ncurses@6.2%gcc@rh7-4.8.5~symlinks+termlib abi=none arch=linux-rhel7-haswell
                        ^builtin.pkgconf@1.7.4%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
    ^builtin.flex@2.6.3%gcc@rh7-4.8.5+lex~nls arch=linux-rhel7-haswell
        ^builtin.findutils@4.8.0%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
    ^builtin.libjpeg-turbo@2.0.6%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
        ^builtin.cmake@3.20.2%gcc@rh7-4.8.5~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-rhel7-haswell
            ^builtin.openssl@1.1.1k%gcc@rh7-4.8.5~docs+systemcerts arch=linux-rhel7-haswell
                ^builtin.zlib@1.2.11%gcc@rh7-4.8.5+optimize+pic+shared arch=linux-rhel7-haswell
        ^builtin.nasm@2.15.05%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
    ^builtin.libszip@2.1.1%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
    ^hacks.libtirpc@1.2.6%gcc@rh7-4.8.5 arch=linux-rhel7-haswell
        ^builtin.krb5@1.18.2%gcc@rh7-4.8.5+shared patches=3d75052730690579484e65a5bf0f92f6c3b20d9c43a413862d087774f431d9e9 arch=linux-rhel7-haswell
```
i.e. both bison and libtirpc use 'hacks' namespace, but still using builtin.libszip.
Similarly, doing
```console
$ spack spec -N hdf ^libszip
```
results in depending on hacks.bison and hacks.libszip, but builtin.libtirpc, and I need to do
```console
$ spack spec -N hdf ^libszip ^libtirpc
```
to get all three (bison, libszip, litirpc) to use hacks.

### Expected behavior

I would expect 
```console
$ spack spec -N hdf
$ spack spec -N hdf ^libtirpc
$ spack spec -N hdf ^libszip
$spack spec -N hdf ^libszip ^libtirpc
```
to all return the same results, and that in all cases builtin.hdf would depend on hacks.bison, hacks.libszip, and hacks.libtirpc.

### Additional information
```consolespack debug report
* **Spack:** 0.16.1-2635-98cf0f5
* **Python:** 3.6.8
* **Platform:** linux-rhel7-skylake
* **Concretizer:** original
```

@tgamblin on the mailing list suggested the behavior might be concretizer dependent, and so I am working on getting clingo concretizer installed in my test spack, and I will update with that information when I get a chance (but will likely be a couple of weeks).

I saw another issue (#23298 regarding namespaces, but I do not see this as obviously related.

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

* Relevant spack config files
  * [repos.yaml.txt](https://github.com/spack/spack/files/6480403/repos.yaml.txt)
  * [compilers.yaml.txt](https://github.com/spack/spack/files/6480404/compilers.yaml.txt)
  * [config.yaml.txt](https://github.com/spack/spack/files/6480405/config.yaml.txt)
  * [packages.yaml.txt](https://github.com/spack/spack/files/6480406/packages.yaml.txt)
* Output of various spack spec commands with -ddd -v flags
  * spack -ddd -v spec hdf output [debug.spack-Nhdf.txt](https://github.com/spack/spack/files/6480409/debug.spack-Nhdf.txt)
  * spack -ddd -v spec hdf ^libtirpc output [debug.spack-Nhdf-libtirpc.txt](https://github.com/spack/spack/files/6480410/debug.spack-Nhdf-libtirpc.txt)
  * spack -ddd -v spec hdf ^libszip output [debug.spack-Nhdf-libszip.txt](https://github.com/spack/spack/files/6480411/debug.spack-Nhdf-libszip.txt)

**Comment by scheibelp** [comment]
This looks like a duplicate of https://github.com/spack/spack/issues/22589

Are you able to try using the newer concretizer?

**Comment by payerle** [comment]
Agreed --- duplicate of #22589.  Missed that in my search of related tickets, sorry.

Have not been able to try clingo concretizer yet in my test env, it sounds from 22589 that clingo should fix that.  If I manage to get clingo working in test env, I will update 22589.
