### ISSUE TITLE
Installation issue: adios2

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#23643]
### Steps to reproduce the issue

```console
$ spack install adios2 +endian_reverse +python
```

### Information on your system

```
$ spack debug report
* **Spack:** 0.16.1-2651-fc392d2f56
* **Python:** 3.8.5
* **Platform:** darwin-bigsur-skylake
* **Concretizer:** original
```

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/6481152/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/6481155/spack-build-env.txt)

@ax3l  @chuckatkins  @williamfgc

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by ax3l** [comment]
Might be a good upstream report, cc @pnorbert
```
adios2/helper/adiosMemory.cpp:32:22: error: no match for 'operator==' (operand types are 'const adios2::DataType' and 'const char [1]')
   32 |         if (destType == "")
      |             ~~~~~~~~ ^~ ~~
      |             |           |
      |             |           const char [1]
      |             const adios2::DataType
```
Upstream: https://github.com/ornladios/ADIOS2 -> posted as https://github.com/ornladios/ADIOS2/issues/2700

AFAIK, `endian_reverse` is one of the less-intense tested features.

**Comment by ax3l** [comment]
Patch submitted to https://github.com/ornladios/ADIOS2/pull/2701

**Comment by BenWibking** [comment]
I am also affected by this when building `adios2@2.7.1`, which is the version needed for VisIt.
