### ISSUE TITLE
Installation issue: `llvm` main branch fails to build via Spack 

### ISSUE THREAD

**Issue by ikitayama** [LLNL/spack#23654]
### Steps to reproduce the issue

```console
$ spack install llvm@main+omp_debug+cuda cuda_arch=80
[...]
[+] /p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/py-setuptools-50.3.2-daadfdnmkswqtoa5thp5c2zzezbk6nxp
[+] /p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/z3-4.8.9-lapegzcygwpjonwb34dhmjwzz5jvh4mp
==> Installing llvm-main-oi5oojnysupwxabpy6uyo6cziysntbrg
==> No binary for llvm-main-oi5oojnysupwxabpy6uyo6cziysntbrg found: installing from source
==> Warning: Missing a source id for llvm@main
==> Warning: Missing a source id for cuda@11.0.221
==> No patches needed for llvm
==> llvm: Executing phase: 'cmake'
==> llvm: Executing phase: 'build'
==> llvm: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

18 errors found in build log:
     52500    [  9%] Generating amdgcn_smid.gfx906.bc
     52501    [  9%] Generating task.gfx900.bc
     52502    [ 10%] Generating amdgcn_smid.gfx900.bc
     52503    [ 10%] Generating task.gfx803.bc
     52504    [ 10%] Generating task.gfx801.bc
     52505    /bin/sh: CLANG_TOOL-NOTFOUND: command not found
  >> 52506    make[2]: *** [libomptarget/deviceRTLs/amdgcn/CMakeFiles/libomptar
              get-amdgcn-gfx906.dir/build.make:300: libomptarget/deviceRTLs/amd
              gcn/task.gfx906.bc] Error 127
     52507    make[2]: *** Waiting for unfinished jobs....
     52508    /bin/sh: CLANG_TOOL-NOTFOUND: command not found
  >> 52509    make[2]: *** [libomptarget/deviceRTLs/amdgcn/CMakeFiles/libomptar
              get-amdgcn-gfx906.dir/build.make:118: libomptarget/deviceRTLs/amd
              gcn/amdgcn_smid.gfx906.bc] Error 127
     52510    /bin/sh: CLANG_TOOL-NOTFOUND: command not found
  >> 52511    make[1]: *** [CMakeFiles/Makefile2:1035: libomptarget/deviceRTLs/
              amdgcn/CMakeFiles/libomptarget-amdgcn-gfx906.dir/all] Error 2
  >> 52512    make[2]: *** [libomptarget/deviceRTLs/amdgcn/CMakeFiles/libomptar
              get-amdgcn-gfx900.dir/build.make:300: libomptarget/deviceRTLs/amd
              gcn/task.gfx900.bc] Error 127
     52513    make[1]: *** Waiting for unfinished jobs....
     52514    make[2]: *** Waiting for unfinished jobs....
     52515    /bin/sh: CLANG_TOOL-NOTFOUND: command not found
  >> 52516    make[2]: *** [libomptarget/deviceRTLs/amdgcn/CMakeFiles/libomptar
              get-amdgcn-gfx803.dir/build.make:300: libomptarget/deviceRTLs/amd
              gcn/task.gfx803.bc] Error 127
     52517    /bin/sh: CLANG_TOOL-NOTFOUND: command not found
  >> 52518    make[1]: *** [CMakeFiles/Makefile2:1087: libomptarget/deviceRTLs/
              amdgcn/CMakeFiles/libomptarget-amdgcn-gfx803.dir/all] Error 2
  >> 52519    make[2]: *** [libomptarget/deviceRTLs/amdgcn/CMakeFiles/libomptar
              get-amdgcn-gfx900.dir/build.make:118: libomptarget/deviceRTLs/amd
              gcn/amdgcn_smid.gfx900.bc] Error 127
  >> 52520    make[1]: *** [CMakeFiles/Makefile2:1061: libomptarget/deviceRTLs/
              amdgcn/CMakeFiles/libomptarget-amdgcn-gfx900.dir/all] Error 2
     52521    [ 11%] Generating task.gfx701.bc
     52522    /bin/sh: CLANG_TOOL-NOTFOUND: command not found
  >> 52523    make[2]: *** [libomptarget/deviceRTLs/amdgcn/CMakeFiles/libomptar
              get-amdgcn-gfx801.dir/build.make:300: libomptarget/deviceRTLs/amd
              gcn/task.gfx801.bc] Error 127
     52524    make[2]: *** Waiting for unfinished jobs....
     52525    /bin/sh: CLANG_TOOL-NOTFOUND: command not found
  >> 52526    make[2]: *** [libomptarget/deviceRTLs/amdgcn/CMakeFiles/libomptar
              get-amdgcn-gfx701.dir/build.make:300: libomptarget/deviceRTLs/amd
              gcn/task.gfx701.bc] Error 127
     52527    make[2]: *** Waiting for unfinished jobs....
     52528    [ 11%] Generating amdgcn_smid.gfx801.bc
     52529    [ 11%] Generating amdgcn_smid.gfx701.bc
     52530    [ 12%] Generating amdgcn_locks.gfx801.bc
     52531    [ 14%] Generating amdgcn_locks.gfx701.bc
     52532    [ 14%] Generating target_impl.gfx801.bc
     52533    [ 14%] Generating target_impl.gfx701.bc
     52534    /bin/sh: CLANG_TOOL-NOTFOUND: command not found
  >> 52535    make[2]: *** [libomptarget/deviceRTLs/amdgcn/CMakeFiles/libomptar
              get-amdgcn-gfx801.dir/build.make:118: libomptarget/deviceRTLs/amd
              gcn/amdgcn_smid.gfx801.bc] Error 127
     52536    /bin/sh: CLANG_TOOL-NOTFOUND: command not found
  >> 52537    make[2]: *** [libomptarget/deviceRTLs/amdgcn/CMakeFiles/libomptar
              get-amdgcn-gfx701.dir/build.make:118: libomptarget/deviceRTLs/amd
              gcn/amdgcn_smid.gfx701.bc] Error 127
     52538    /bin/sh: CLANG_TOOL-NOTFOUND: command not found
  >> 52539    make[2]: *** [libomptarget/deviceRTLs/amdgcn/CMakeFiles/libomptar
              get-amdgcn-gfx801.dir/build.make:105: libomptarget/deviceRTLs/amd
              gcn/amdgcn_locks.gfx801.bc] Error 127
     52540    /bin/sh: CLANG_TOOL-NOTFOUND: command not found
  >> 52541    make[2]: *** [libomptarget/deviceRTLs/amdgcn/CMakeFiles/libomptar
              get-amdgcn-gfx701.dir/build.make:105: libomptarget/deviceRTLs/amd
              gcn/amdgcn_locks.gfx701.bc] Error 127
     52542    /bin/sh: CLANG_TOOL-NOTFOUND: command not found
     52543    /bin/sh: CLANG_TOOL-NOTFOUND: command not found
  >> 52544    make[2]: *** [libomptarget/deviceRTLs/amdgcn/CMakeFiles/libomptar
              get-amdgcn-gfx701.dir/build.make:287: libomptarget/deviceRTLs/amd
              gcn/target_impl.gfx701.bc] Error 127
  >> 52545    make[2]: *** [libomptarget/deviceRTLs/amdgcn/CMakeFiles/libomptar
              get-amdgcn-gfx801.dir/build.make:287: libomptarget/deviceRTLs/amd
              gcn/target_impl.gfx801.bc] Error 127
  >> 52546    make[1]: *** [CMakeFiles/Makefile2:1139: libomptarget/deviceRTLs/
              amdgcn/CMakeFiles/libomptarget-amdgcn-gfx701.dir/all] Error 2
  >> 52547    make[1]: *** [CMakeFiles/Makefile2:1113: libomptarget/deviceRTLs/
              amdgcn/CMakeFiles/libomptarget-amdgcn-gfx801.dir/all] Error 2
     52548    [ 14%] Built target libomp-needed-headers
     52549    [ 15%] Linking CXX shared library ../../libomptarget.rtl.x86_64.s
              o
     52550    [ 15%] Built target omptarget.rtl.x86_64
     52551    [ 16%] Linking CXX shared library ../libomptarget.so
     52552    [ 16%] Linking CXX shared library ../../libomptarget.rtl.cuda.so
     52553    [ 16%] Built target omptarget.rtl.cuda
```

### Additional information

* [spack-build-out.txt]()
* [spack-build-env.txt]()

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [ ] I have searched the issues of this repo and believe this is not a duplicate

**Comment by ikitayama** [comment]
```
$ spack debug report
* **Spack:** 0.16.1-2659-ef4215360c
* **Python:** 3.8.5
* **Platform:** linux-centos8-zen2
* **Concretizer:** original
```

**Comment by ikitayama** [comment]
@naromero77  @trws, main is failing at this moment.

**Comment by ikitayama** [comment]
[Uploading spack-build-out.txt…]()

**Comment by ikitayama** [comment]
[spack-build-out.txt](https://github.com/spack/spack/files/6486670/spack-build-out.txt)

**Comment by naromero77** [comment]
Is this specific to the Spack-build or is the plain-vanilla version working?

I would recommend sticking to the one of the officially tagged releases. `main` can break at any time.

**Comment by ikitayama** [comment]
For openmp project new features and bug fixes trickled in on a daily bases
this I try to build main.

**Comment by naromero77** [comment]
I understand why you would want to use `main`. My other question is whether the failure is specific to the Spack-build or does it also fail with the plain-vanilla version.

**Comment by ikitayama** [comment]
Log looks so lengthy is three a good way to check CMake options?

**Comment by naromero77** [comment]
You can try:
`-DCMAKE_VERBOSE_MAKEFILE=1`
https://cmake.org/cmake/help/latest/variable/CMAKE_VERBOSE_MAKEFILE.html

**Comment by ikitayama** [comment]
How do I reduce this output down to simpler, sequences of human readable CMake options?

```

'cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/llvm-main-oi5oojnysupwxabpy6uyo6cziysntbrg' '-DCMAKE_BUILD_TYPE:STRING=Release' '-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=OFF' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=OFF' '-DCMAKE_INSTALL_RPATH:STRING=/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/llvm-main-oi5oojnysupwxabpy6uyo6cziysntbrg/lib;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/llvm-main-oi5oojnysupwxabpy6uyo6cziysntbrg/lib64;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/binutils-2.36.1-3dspf5negtfeqgspa74wj57nnem2dada/lib;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/gettext-0.21-rpab6sfbr436eylkwyhtww5nvrfmxq3r/lib;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/bzip2-1.0.8-63o3y6o4ai5nopmqx53qh5cuyyvwy7zm/lib;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/libiconv-1.16-zid6uv2jyijm57tvod4c3nmmzpfp7tsq/lib;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/libxml2-2.9.10-mgjltcdszna35khm4uabrv7vhxmmjbjo/lib;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/xz-5.2.5-5f7lza75r4a4jjnpa7a3tykaoiqq3cxl/lib;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/zlib-1.2.11-ysmifax4vc6oqjhhhb7j7ozvdgfyvj4u/lib;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/ncurses-6.2-vpaqqleappl2opivpyiig26rfxuncaea/lib;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/hwloc-2.4.1-cptbycdajqk7rxrsykzknw5anqa3kltd/lib;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/libpciaccess-0.16-6oqycjah5m3bur6m26aazz7irg7eheln/lib;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/libedit-3.1-20210216-oky3dzex4gogdpe7so376mflivth2hmu/lib;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/libelf-0.8.13-qpfllog2imqum7y7ho4gzdpjgnz65d6i/lib;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/libffi-3.3-kzbenek56ow4c6c2g4bvxrvyvdzf2wx5/lib;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/pcre-8.44-ktiwtltneobkped3eu2uvrbulu2trebc/lib;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/z3-4.8.9-lapegzcygwpjonwb34dhmjwzz5jvh4mp/lib;/p/software/jurecadc/stages/2020/software/CUDA/11.0/lib64;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/libffi-3.3-kzbenek56ow4c6c2g4bvxrvyvdzf2wx5/lib64' '-DCMAKE_PREFIX_PATH:STRING=/p/software/jurecadc/stages/2020/software/CUDA/11.0;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/cmake-3.20.2-lq3m62t7kohhnxz5bym7twckadqecoey;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/python-3.8.10-ko45yplosnfwnwgvhu5pmjvryh75zhpp;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/pkgconf-1.7.4-kdw3p3eo4ujoumzws3emmmudx2cq7ggg;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/z3-4.8.9-lapegzcygwpjonwb34dhmjwzz5jvh4mp;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/perl-data-dumper-2.173-oiyic3qsfomgwky5poimuvn6lp2hzti3;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/hwloc-2.4.1-cptbycdajqk7rxrsykzknw5anqa3kltd;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/libelf-0.8.13-qpfllog2imqum7y7ho4gzdpjgnz65d6i;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/libffi-3.3-kzbenek56ow4c6c2g4bvxrvyvdzf2wx5;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/ncurses-6.2-vpaqqleappl2opivpyiig26rfxuncaea;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/swig-4.0.2-467ulxfdp2ulsljhsa7nq3n4b5amsev7;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/libedit-3.1-20210216-oky3dzex4gogdpe7so376mflivth2hmu;/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/binutils-2.36.1-3dspf5negtfeqgspa74wj57nnem2dada' '-DLLVM_REQUIRES_RTTI:BOOL=ON' '-DLLVM_ENABLE_RTTI:BOOL=ON' '-DLLVM_ENABLE_EH:BOOL=ON' '-DCLANG_DEFAULT_OPENMP_RUNTIME:STRING=libomp' '-DPYTHON_EXECUTABLE:PATH=/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/python-3.8.10-ko45yplosnfwnwgvhu5pmjvryh75zhpp/bin/python3.8' '-DLIBOMP_USE_HWLOC:BOOL=ON' '-DLIBOMP_HWLOC_INSTALL_DIR=/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/hwloc-2.4.1-cptbycdajqk7rxrsykzknw5anqa3kltd' '-DPython3_EXECUTABLE=/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/python-3.8.10-ko45yplosnfwnwgvhu5pmjvryh75zhpp/bin/python3.8' '-DCUDA_TOOLKIT_ROOT_DIR:PATH=/p/software/jurecadc/stages/2020/software/CUDA/11.0' '-DLIBOMPTARGET_NVPTX_COMPUTE_CAPABILITIES=80' '-DCLANG_OPENMP_NVPTX_DEFAULT_ARCH=sm_80' '-DLIBOMPTARGET_ENABLE_DEBUG:Bool=ON' '-DLLDB_ENABLE_PYTHON:Bool=OFF' '-DLLVM_BINUTILS_INCDIR=/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/binutils-2.36.1-3dspf5negtfeqgspa74wj57nnem2dada/include' '-DLINK_POLLY_INTO_TOOLS:Bool=ON' '-DLIBOMPTARGET_ENABLE_DEBUG:Bool=ON' '-DLLVM_TARGETS_TO_BUILD:STRING=NVPTX;AMDGPU;X86' '-DGCC_INSTALL_PREFIX=/p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-9.3.0/gcc-10.3.0-bngre6l5yruuaacklkoqir3q7tzssdwn' '-DCMAKE_BUILD_WITH_INSTALL_RPATH=1' '-DLLVM_ENABLE_PROJECTS:STRING=clang;clang-tools-extra;openmp;lldb;lld;compiler-rt;libcxx;libcxxabi;libunwind;polly' '/p/scratch/cjzam11/kitayama1/spack-stage/spack-stage-llvm-main-oi5oojnysupwxabpy6uyo6cziysntbrg/spack-src/llvm'
```

**Comment by ikitayama** [comment]
By the way, do we want to add an option switch to Ninja build?

**Comment by ikitayama** [comment]
I'll close this for now.

**Comment by ikitayama** [comment]
@naromero77 , as the `llvm` package co-maintainer, is the main branch build completely out of support scope? while I think it is useful to address the issues found in main builds. Just curious to know your thoughts.

**Comment by ikitayama** [comment]
Also-, why we always include both NVPTX and AMDGPU, if not all projects are supposed to be built?

**Comment by ikitayama** [comment]
```
CMake Warning:
  Manually-specified variables were not used by the project:

    CLANG_DEFAULT_OPENMP_RUNTIME
    CLANG_OPENMP_NVPTX_DEFAULT_ARCH
    GCC_INSTALL_PREFIX
    LINK_POLLY_INTO_TOOLS
    LLDB_ENABLE_PYTHON
    LLVM_BINUTILS_INCDIR
    LLVM_ENABLE_PROJECTS
    Python3_EXECUTABLE
```

I don't understand these either as the above options look sane to me.

**Comment by naromero77** [comment]
> By the way, do we want to add an option switch to Ninja build?

We are looking into this. I rather not add another variant, so we would just hard-code it to Ninja which is what the LLVM buildbot normally use.

**Comment by naromero77** [comment]
> Also-, why we always include both NVPTX and AMDGPU, if not all projects are supposed to be built?

I don't really understand your comment.

**Comment by naromero77** [comment]
> @naromero77 , as the `llvm` package co-maintainer, is the main branch build completely out of support scope? while I think it is useful to address the issues found in main builds. Just curious to know your thoughts.

The Spack packages are supported by the community. Neither @trws or I have specific funding earmarked to support the LLVM Spack package. We do this out of our "spare time." If someone else from the community initiate PR, we can review it. However, IMO supporting the `main` branch would be difficult. Most of the Spack packages only support officially releases. So, we have no plans to support `main` in the Spack package. @trws should jump in and correct anything I say.

**Comment by naromero77** [comment]
> ```
> CMake Warning:
>   Manually-specified variables were not used by the project:
> 
>     CLANG_DEFAULT_OPENMP_RUNTIME
>     CLANG_OPENMP_NVPTX_DEFAULT_ARCH
>     GCC_INSTALL_PREFIX
>     LINK_POLLY_INTO_TOOLS
>     LLDB_ENABLE_PYTHON
>     LLVM_BINUTILS_INCDIR
>     LLVM_ENABLE_PROJECTS
>     Python3_EXECUTABLE
> ```
> 
> I don't understand these either as the above options look sane to me.

There are always warnings, but are any of these impacting a build of an official LLVM release.

**Comment by trws** [comment]
> > @naromero77 , as the `llvm` package co-maintainer, is the main branch build completely out of support scope? while I think it is useful to address the issues found in main builds. Just curious to know your thoughts.
> 
> The Spack packages are supported by the community. Neither @trws or I have specific funding earmarked to support the LLVM Spack package. We do this out of our "spare time." If someone else from the community initiate PR, we can review it. However, IMO supporting the `main` branch would be difficult. Most of the Spack packages only support officially releases. So, we have no plans to support `main` in the Spack package. @trws should jump in and correct anything I say.

That's right.  Neither of us are "official support" for this.  I think we both want it to be as usable and useful as possible, main branch included, but only have so much bandwidth for this as a side project.  If there is an issue with *the spack package* that does not appear when building directly, that's what we're here to fix.

**Comment by ikitayama** [comment]
spack-build-02-build-out.txt
spack-build-01-cmake-out.txt

**Comment by ikitayama** [comment]
[spack-build-02-build-out.txt](https://github.com/spack/spack/files/6512256/spack-build-02-build-out.txt)
[spack-build-01-cmake-out.txt](https://github.com/spack/spack/files/6512258/spack-build-01-cmake-out.txt)

**Comment by ye-luo** [comment]
https://lists.llvm.org/pipermail/openmp-dev/2021-May/004002.html
It is mostly LLVM issue and not surprising on main branch. If we change building openmp as LLVM_ENABLE_RUNTIMES instead of LLVM_ENABLE_PROJECTS, the spack build should become more robust.

**Comment by ikitayama** [comment]
I think in upstream main, the AMDGPU target can not be built reliably at this moment.

**Comment by trws** [comment]
Are there docs for that @ye-luo? If it will make things better it would be nice to do.  Glancing at the system I don't see openmp in the all list in the cmake, is it just missing or incomplete or..?

**Comment by ye-luo** [comment]
https://github.com/llvm/llvm-project/tree/main/openmp#options-for-libomptarget

> Glancing at the system I don't see openmp in the all list in the cmake, is it just missing or incomplete or..?

What did you mean? I saw openmp listed
https://github.com/llvm/llvm-project/blob/943839870a0be356c40629c75d4583976cb9e812/llvm/CMakeLists.txt#L67
https://github.com/llvm/llvm-project/blob/943839870a0be356c40629c75d4583976cb9e812/llvm/runtimes/CMakeLists.txt#L10

**Comment by trws** [comment]
Right you are, I must have been looking at the wrong thing somehow, either way thanks for the links!

**Comment by hseara** [comment]
> I think in upstream main, the AMDGPU target can not be built reliably at this moment.

The problem is the following code in the llvm installation file:

```
if "+all_targets" not in spec:  # all is default on cmake

            targets = ["NVPTX", "AMDGPU"]
            if spec.version < Version("3.9.0"):
                # Starting in 3.9.0 CppBackend is no longer a target (see
                # LLVM_ALL_TARGETS in llvm's top-level CMakeLists.txt for
                # the complete list of targets)
                targets.append("CppBackend")
            
           if spec.target.family in ("XXX"):
                targets.append("XXX")
          elif ...
          cmake_args.append(define("LLVM_TARGETS_TO_BUILD", targets))
```
This makes that independently of your spec, when not all targets are requested (default spack option but not cmake one),
both `NVPTX`, `AMDGPU` will be still compiled. And unfortunately `AMDGPU` compilation **always fails** (at least for me). Therefore, I need to remove it from this list in any of my spack installations before attempting the `llvm` installation.

Both `NVPTX`, `AMDGPU`, `CppBackend`, should be explicit options somehow. I don't see requesting the specs the user wants to compile and if needed providing a default spec corresponding to the machine spec only.

Edit: I will publish this as separate issue anyway as is only part of the problem reported here.

**Comment by haampie** [comment]
@trws should we just make targets a list? I julia I'd like to do `depends_on('llvm targets=NVPTX,AMDGPU,WebAssembly,BPF')`

**Comment by trws** [comment]
Yes, we should.  I honestly thought we *had done that* the other day when you asked me about targets, I think the current setup is a holdover from waaaaay back before multi-valued variants happened.  The only sticky bit is I think we should have a way to say "defaults plus <target>" or similar, maybe also "defaults minus <target>" but I'm less sure about that. Mainly because there's no good way to list the native one, though that would be another option.

Also, the nvptx and amdgpu targets should probably be conditional on the cuda and hip variants... The BPF backend should probably be in the default set on linux too, but nowhere else.  Darned complicated conditions. 😞

**Comment by ye-luo** [comment]
The above issue was about OpenMP offload target not LLVM backend target. In the current main. OpenMP offload targets can be built without CUDA or ROCM being installed. I think this issue can be closed to avoid further confusion.

**Comment by FindHao** [comment]
> > I think in upstream main, the AMDGPU target can not be built reliably at this moment.
> 
> The problem is the following code in the llvm installation file:
> 
> ```
> if "+all_targets" not in spec:  # all is default on cmake
> 
>             targets = ["NVPTX", "AMDGPU"]
>             if spec.version < Version("3.9.0"):
>                 # Starting in 3.9.0 CppBackend is no longer a target (see
>                 # LLVM_ALL_TARGETS in llvm's top-level CMakeLists.txt for
>                 # the complete list of targets)
>                 targets.append("CppBackend")
>             
>            if spec.target.family in ("XXX"):
>                 targets.append("XXX")
>           elif ...
>           cmake_args.append(define("LLVM_TARGETS_TO_BUILD", targets))
> ```
> 
> This makes that independently of your spec, when not all targets are requested (default spack option but not cmake one), both `NVPTX`, `AMDGPU` will be still compiled. And unfortunately `AMDGPU` compilation **always fails** (at least for me). Therefore, I need to remove it from this list in any of my spack installations before attempting the `llvm` installation.
> 
> Both `NVPTX`, `AMDGPU`, `CppBackend`, should be explicit options somehow. I don't see requesting the specs the user wants to compile and if needed providing a default spec corresponding to the machine spec only.
> 
> Edit: I will publish this as separate issue anyway as is only part of the problem reported here.

Hi @hseara , I deleted the AMDGPU from targets, but it still fails. Do you have any suggestions to disable AMD-related compilations?

**Comment by hseara** [comment]
I do this manually, and it is tedious, Anyway, I think this issue is now outdated and should be closed.
