### ISSUE TITLE
AttributeError: 'CommentedSeq' object has no attribute 'get'

### ISSUE THREAD

**Issue by sethrj** [LLNL/spack#23663]
I'm trying to install a new package after pulling spack to a recent version; and the install seems to be failing due to an error while building modulefiles deep in the spack config settings.

### Error Message

```console
$ spack -vd install fortrilinos ^trilinos/fi45zpy
# snip
==> [2021-05-16-09:23:02.993000] Installing /var/folders/gy/mrg1ffts2h945qj9k29s1l1dvvmbqb/T/s3j/spack-stage/spack-stage-fortrilinos-2.0.0-xdulgmsdgorsfvtvr73vubopurrs2hn5/spack-src/example/test-installation to /rnsdhpc/code/spack/opt/spack/apple-clang/fortrilinos/xdulgms/.spack/test/example/test-installation
==> [2021-05-16-09:23:03.317370] Error: AttributeError: 'CommentedSeq' object has no attribute 'get'

/rnsdhpc/code/spack/lib/spack/spack/build_environment.py:930, in _setup_pkg_and_run:
        927        tb_string = traceback.format_exc()
        928
        929        # build up some context from the offending package so we can
  >>    930        # show that, too.
        931        package_context = get_package_context(tb)
        932
        933        logfile = None

See build log for details:
  /var/folders/gy/mrg1ffts2h945qj9k29s1l1dvvmbqb/T/s3j/spack-stage/spack-stage-fortrilinos-2.0.0-xdulgmsdgorsfvtvr73vubopurrs2hn5/spack-build-out.txt

Traceback (most recent call last):
  File "/rnsdhpc/code/spack/lib/spack/spack/build_environment.py", line 914, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/rnsdhpc/code/spack/lib/spack/spack/installer.py", line 1792, in build_process
    spack.hooks.post_install(pkg.spec)
  File "/rnsdhpc/code/spack/lib/spack/spack/hooks/__init__.py", line 75, in __call__
    hook(*args, **kwargs)
  File "/rnsdhpc/code/spack/lib/spack/spack/hooks/module_file_generation.py", line 38, in post_install
    _for_each_enabled(spec, 'write')
  File "/rnsdhpc/code/spack/lib/spack/spack/hooks/module_file_generation.py", line 15, in _for_each_enabled
    enabled = spack.config.get('modules:%s:enable' % name)
  File "/rnsdhpc/code/spack/lib/spack/spack/config.py", line 899, in get
    return config.get(path, default, scope)
  File "/rnsdhpc/code/spack/lib/spack/spack/config.py", line 652, in get
    value = value.get(key, default)
AttributeError: 'CommentedSeq' object has no attribute 'get'
==> [2021-05-16-09:23:03.317914] Flagging fortrilinos-2.0.0-xdulgmsdgorsfvtvr73vubopurrs2hn5 as failed: AttributeError: 'CommentedSeq' object has no attribute 'get'
==> [2021-05-16-09:23:03.333998] ChildError: AttributeError: 'CommentedSeq' object has no attribute 'get'
```

### Information on your system

* **Spack:** 0.16.1-2661-2202ce27fa
* **Python:** 3.8.5
* **Platform:** darwin-bigsur-skylake
* **Concretizer:** clingo

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [x] I have run the failing commands in debug mode and reported the output

The modules config looks a little funky, apparently 
```console
$ spack config get modules
modules:
  default:
    lmod:
      core_compilers:
      - apple-clang@12.0.5
      - gcc@10.2.0
      hierarchy:
      - mpi
    prefix_inspections:
      lib:
      - DYLD_FALLBACK_LIBRARY_PATH
      lib64:
      - DYLD_FALLBACK_LIBRARY_PATH
    roots:
      tcl: $spack/share/spack/modules
      lmod: $spack/share/spack/lmod
    enable:
    - tcl

    # Default configurations if lmod is enabled
  'enable:':
  - lmod
  prefix_inspections:
    bin:
    - PATH
    man:
    - MANPATH
    share/man:
    - MANPATH
    share/aclocal:
    - ACLOCAL_PATH
    'include:': []
    lib:
    - LIBRARY_PATH
    lib64:
    - LIBRARY_PATH
    lib/pkgconfig:
    - PKG_CONFIG_PATH
    lib64/pkgconfig:
    - PKG_CONFIG_PATH
    share/pkgconfig:
    - PKG_CONFIG_PATH
    ? ''
    : - CMAKE_PREFIX_PATH

  # These are configurations for the module set named "default"
  lmod:
    core_compilers:
    - apple-clang@12.0.0
    hash_length: 4
    'hierarchy:': []
    ^python:
      autoload: direct
    all:
      suffixes:
        ^python@2: py2
        +cuda: cuda
        +debug: debug
        +mpi: mpi
        +multithreaded: mt
        +openmp: mt
        +threads: mt
        ~shared: static
        cxxstd=98: c++98
        cxxstd=14: c++14
        cxxstd=17: c++17
      environment:
        set:
          ${PACKAGE}_ROOT: ${PREFIX}
```

**Comment by sethrj** [comment]
@becker33 I think this may result from #22588 ? It seems that `spack module lmod refresh` works fine for my other modules, removing all the comments from the `modules` files has no effect, but adding some debug code to `config.get` produces:
```
Failed: section=modules, scope=None, key=enable, value=['lmod'] value_type=<class 'ruamel.yaml.comments.CommentedSeq'>
```
so I guess it's expecting a dict but getting a list?

**Comment by sethrj** [comment]
Indeed, reverting to fc392d2f56 fixes the error...

**Comment by haampie** [comment]
Getting the same after 10 minutes of an install :/

**Comment by sethrj** [comment]
Yeah took me 20 minutes of installs to debug it 😂

**Comment by jgalarowicz** [comment]
@alalazo @sethrj Hi - I am also seeing this.  How did you revert to the fc392d2 mod?  Will:  git checkout fc392d2 be sufficient to get around the problem?

I'm on a system where I need to mirror the spack and project component sources to compile my projects.

==> Installing libsigsegv-2.13-j7noanegkreyrfcaldvjzl5fmbd5h5yj
==> No binary for libsigsegv-2.13-j7noanegkreyrfcaldvjzl5fmbd5h5yj found: installing from source
==> Using cached archive: /pcc-project/sw/may15_spack/spack/var/spack/cache/_source-cache/archive/be/be78ee4176b05f7c75ff03298d84874db90f4b6c9d5503f0da1226b3a3c48119.tar.gz
==> No patches needed for libsigsegv
==> libsigsegv: Executing phase: 'autoreconf'
==> libsigsegv: Executing phase: 'configure'
==> libsigsegv: Executing phase: 'build'
==> libsigsegv: Executing phase: 'install'
==> Error: AttributeError: 'CommentedSeq' object has no attribute 'get'

/pcc-project/sw/may15_spack/spack/lib/spack/spack/build_environment.py:930, in _setup_pkg_and_run:
        927        tb_string = traceback.format_exc()
        928
        929        # build up some context from the offending package so we can
  >>    930        # show that, too.
        931        package_context = get_package_context(tb)
        932
        933        logfile = None

**Comment by sethrj** [comment]
> @alalazo @sethrj Hi - I am also seeing this. How did you revert to the [fc392d2](https://github.com/spack/spack/commit/fc392d2f56beae448dd5d8888dbb2b8cde6d9e64) mod? Will: git checkout [fc392d2](https://github.com/spack/spack/commit/fc392d2f56beae448dd5d8888dbb2b8cde6d9e64) be sufficient to get around the problem?

Yes. There's alsos a pending PR to temporarily revert the broken change, https://github.com/spack/spack/pull/23674, so hopefully soon a "git pull" will fix.

**Comment by jgalarowicz** [comment]
@sethrj Thank you for the update Seth!
