### ISSUE TITLE
Nose: note to users in latest version

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#2368]
The latest version of [nose](http://nose.readthedocs.io/en/latest/) starts with the following note to users:
> Nose has been in maintenance mode for the past several years and will likely cease without a new person/team to take over maintainership. New projects should consider using Nose2, py.test, or just plain unittest/unittest2.

I was wondering if after `v0.10` we should consider moving to [py.test](http://docs.pytest.org/en/latest/) or we should remain with the version of nose that's currently in `lib/external`. 

In case there's consensus around this, I wouldn't mind experimenting with `py.test` to see how much this change will be doable / painful.

**Comment by alalazo** [comment]
@tgamblin @becker33 @scheibelp Did you have time to check this? If we want to stick with nose despite the note above I'll close the issue.

**Comment by tgamblin** [comment]
@alalazo: I have no particular affinity for `nose`, especially if it is not supported.  I think that @scheibelp should comment (in case there's anything in particular we need from `nose`).

How big of a change is switching to `py.test`?  Why'd you pick that one over the other options in the list?

**Comment by alalazo** [comment]
> How big of a change is switching to py.test?

I don't know yet, but I hope it won't be a big change as in `py.test` docs they say that it can run natively `nose` test suite. If you want to go this direction I would be glad to experiment with it in a branch.

> Why'd you pick that one over the other options in the list?

The disclaimer is that I don't a have direct experience with `nose2`, and I used `py.test` only in small personal projects (mainly for educational purpose, see [here](https://github.com/alalazo/dpp/blob/develop/tests/test_finite_state_machine.py) to have an idea of how a simple test may looks like). That said:

1. [this stackoverflow answer](http://stackoverflow.com/questions/22856638/nose-vs-pytest-what-are-the-subjective-differences-that-should-make-me-pick)
2.  [the small paragraph in Kenneth Reitz's guide](http://docs.python-guide.org/en/latest/writing/tests/#tools) and links therein, including features of the tools
3. this talk at EuroPython 2016 this summer [showcasing the flexibility of py.test](https://www.youtube.com/watch?v=EDpwvvU-sPY) in terms of workflow set-up and terse syntax

make me think `py.test` is a better bet other `nose2`.

**Comment by scheibelp** [comment]
The original reason I swapped to nose was to generate XML-formatted test results (specifically: xunit) to be read by a continuous integration server (original PR here: https://github.com/LLNL/spack/pull/202). py.test and nose2 both support this so it should be fine to switch. 

It also should not be much hassle to remove nose: using nose did not require modifying the unit tests directly; most of the switch is achieved by setup in ```test/__init__.py```

**Comment by tgamblin** [comment]
@alalazo: If it works, then, I think going with `py.test` would be good.  i agree with (1) that nose configuration is kind of weird -- there are places where it isn't clear whether we should set an env var, pass a parameter, or add some plugin.  If `py.test` works better and is maintained, let'd do it.

Also, if you remove `nose` and switch to `py.test`, you'll keep growing your removed-lines record on the contributors page 😄

**Comment by alalazo** [comment]
Closed in #2502
