### ISSUE TITLE
Installation issue: Octave with intel-mkl_ilp64

### ISSUE THREAD

**Issue by nkgh77** [LLNL/spack#23809]
### Steps to reproduce the issue

$ spack install octave%gcc@9.3.0+hdf5+zlib ^intel-mkl+ilp64 ^intel-mpi
==> Installing octave-6.2.0-ae3yhbbpigimzj7wac25nmhdaud3p7u7
==> No binary for octave-6.2.0-ae3yhbbpigimzj7wac25nmhdaud3p7u7 found: installing from source
==> Using cached archive: /home/kushida/SPACK/spack/var/spack/cache/_source-cache/archive/45/457d1fda8634a839e2fd7cfc55b98bd56f36b6ae73d31bb9df43dde3012caa7c.tar.gz
==> Ran patch() for octave
==> octave: Executing phase: 'autoreconf'
==> octave: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/tmp/kushida/spack-stage/spack-stage-octave-6.2.0-ae3yhbbpigimzj7wac25nmhdaud3p7u7/spack-src/configure' '--prefix=/home/kushida/SPACK/spack/opt/spack/linux-ubuntu20.04-broadwell/gcc-9.3.0/octave-6.2.0-ae3yhbbpigimzj7wac25nmhdaud3p7u7' '--with-blas=-L/home/kushida/SPACK/spack/opt/spack/linux-ubuntu20.04-broadwell/gcc-9.3.0/intel-mkl-2020.4.304-u3rg45wbwk7dyrgrywfoyusvnjvimxmg/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64 -L/usr/lib/x86_64-linux-gnu -lmkl_intel_ilp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl' '--with-lapack=-L/home/kushida/SPACK/spack/opt/spack/linux-ubuntu20.04-broadwell/gcc-9.3.0/intel-mkl-2020.4.304-u3rg45wbwk7dyrgrywfoyusvnjvimxmg/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64 -L/usr/lib/x86_64-linux-gnu -lmkl_intel_ilp64 -lmkl_sequential -lmkl_core -lpthread -lm -ldl' '--enable-readline' '--without-arpack' '--without-curl' '--without-fftw3' '--without-fftw3f' '--without-fltk' '--without-glpk' '--without-magick' '--with-hdf5-includedir=/home/kushida/SPACK/spack/opt/spack/linux-ubuntu20.04-broadwell/gcc-9.3.0/hdf5-1.10.7-yxcioje6xdwnyasocxazmf7jw6ozhqil/include' '--with-hdf5-libdir=/home/kushida/SPACK/spack/opt/spack/linux-ubuntu20.04-broadwell/gcc-9.3.0/hdf5-1.10.7-yxcioje6xdwnyasocxazmf7jw6ozhqil/lib' '--disable-java' '--without-opengl' '--without-framework-opengl' '--without-qhull' '--without-qrupdate' '--with-z-includedir=/home/kushida/SPACK/spack/opt/spack/linux-ubuntu20.04-broadwell/gcc-9.3.0/zlib-1.2.11-emkoq3o2mtu377gy6plexktmkqchkgkb/include' '--with-z-libdir=/home/kushida/SPACK/spack/opt/spack/linux-ubuntu20.04-broadwell/gcc-9.3.0/zlib-1.2.11-emkoq3o2mtu377gy6plexktmkqchkgkb/lib' 'F77_INTEGER_8_FLAG=-fdefault-integer-8'

1 error found in build log:
     274    checking whether ISAMAX is called correctly from Fortran... yes
     275    checking whether SDOT is called correctly from Fortran... no
     276    checking whether DDOT is called correctly from Fortran... yes
     277    checking whether CDOTU is called correctly from Fortran... yes
     278    checking whether ZDOTU is called correctly from Fortran... yes
     279    checking BLAS library integer size... 8
  >> 280    configure: error: BLAS and LAPACK libraries are required
`

### Information on your system

$ spack debug report
* **Spack:** 0.16.1-2726-8146c0d848
* **Python:** 3.7.7
* **Platform:** linux-ubuntu20.04-broadwell
* **Concretizer:** original

### Additional information
[spack-build-out.txt](https://github.com/spack/spack/files/6514168/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/6514182/spack-build-env.txt)

I have tested with %gcc10 and %oneapi, but none of the compilers worked with the same error.

@mtmiller

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by mtmiller** [comment]
Yeah, I confirm errors when attempting to configure Octave with either

* `-lmkl_intel_lp64`, or
* `-lmkl_intel_ilp64` and `-fdefault-integer-8`

But building Octave does succeed with both

* `-lmkl_gf_lp64`, or
* `-lmkl_gf_ilp64` and `-fdefault-integer-8`

Because Octave contains Fortran source that is built with gfortran and linked with the selected BLAS variant, it needs to use the corresponding `-lmkl_gf_<integer>` library. It looks to me like the spack Intel configuration doesn't support this as is. Maybe the octave packaging is allowed to modify the blas libs to support this?

**Comment by mtmiller** [comment]
:grimacing: I just rediscovered #21772, already attempting to solve this issue.

**Comment by mtmiller** [comment]
This should be fixed now by #25952
