### ISSUE TITLE
Preserve line breaks in spack info output

### ISSUE THREAD

**Issue by bonachea** [LLNL/spack#23831]
The `spack info` output is the main source of package information for users, and thus the primary means for package authors to provide package/variant documentation to end users. 

Currently the display code for `spack info` strips out newlines from description strings, which hinders efforts by package authors to format their package documentation in more readable ways. This happens in at least two notable places: 

1) The package description string, where paragraph breaks indicated by empty lines are removed and collapsed down to a single space.
2) The variant description string, where hard-coded line breaks are converted to a single space.

The latter is especially bad for multi-valued variants, in cases where the meaning of each value is non-obvious and each value deserves an independent description. 

### Description

Here is part of the current output from `spack info gasnet`: (where the wrap varies based on terminal width)

```
Variants:
    Name [Default]    Allowed values          Description
    ==============    ====================    =======================================

    conduits [smp]    none, udp, mpi, smp,    The hardware-dependent network backends
                      ibv                     to enable. (smp) = SMP conduit for
                                              single-node operation ; (ibv) = Native
                                              InfiniBand verbs conduit ; (udp) =
                                              Portable UDP conduit, for Ethernet
                                              networks ; (mpi) = Low-
                                              performance/portable MPI conduit ; For
                                              detailed recommendations, consult
                                              https://gasnet.lbl.gov
    debug [off]       on, off                 Enable library debugging mode

```
That long description string documenting each of the possible values for `conduits` was implemented with newline separators between values, but the display code has discarded those line breaks and mushed it all together into a visual mess.

As a first cut, the **display algorithm should honor/preserve hard-coded newlines**, generating something more like this:
```
Variants:
    Name [Default]    Allowed values          Description
    ==============    ====================    =======================================

    conduits [smp]    none, udp, mpi, smp,    The hardware-dependent network backends
                      ibv                     to enable. 
                                              (smp) = SMP conduit for single-node 
                                              operation ;
                                              (ibv) = Native InfiniBand verbs conduit ;
                                              (udp) = Portable UDP conduit, for 
                                              Ethernet networks ;
                                              (mpi) = Low-performance/portable MPI 
                                              conduit ;
                                              For detailed recommendations, consult
                                              https://gasnet.lbl.gov
    debug [off]       on, off                 Enable library debugging mode
```

This is slightly longer (ie more lines) but is alot more readable.

A better solution would allow each value in a multi-valued variant to be directly associated with a separate documentation string, that is then formatted in an even more readable way. Example output sketch:

```
Variants:
    Name [Default]    Allowed values          Description
    ==============    ====================    =======================================

    conduits [smp]    one or more of:         The hardware-dependent network backends
                                              to enable. For detailed recommendations, 
                                              consult https://gasnet.lbl.gov
                      none                    No conduits enabled
                      smp                     SMP conduit for single-node operation
                      ibv                     Native InfiniBand verbs conduit
                      udp                     Portable UDP conduit, for Ethernet 
                                              networks
                      mpi                     Low-performance/portable MPI conduit
                                              
    debug [off]       on, off                 Enable library debugging mode    
```

However providing that seems like it would probably require a more obtrusive change to the spec interface.

### General information

- [ X ] I have run `spack --version` and reported the version of Spack

0.16.1-2786-1242f10

- [ X ] I have searched the issues of this repo and believe this is not a duplicate

**Comment by tgamblin** [comment]
Fixed by #40998.
