### ISSUE TITLE
Update of flex urls and addition of new versions

### ISSUE THREAD

**Issue by krafczyk** [LLNL/spack#2385]
I found that `flex` was crashing when trying to build the `binutils` dependency which exists in the dependency chain of the `py-yt` package. This was fixed by getting a newer version of `flex`.

I further found that development of `flex` is currently not being done from sourceforge any more. New versions are released on github under a new release naming scheme. I've adjusted the url locations, added a new function to handle the new and old naming schemes, and added two new versions of flex.

#2384 contains the commit with the necessary changes.

This PR was created by the suggestion of @davydden in #2320.

**Comment by davydden** [comment]
@krafczyk : that is not a PR, but an issue. I guess you hit the wrong button.

**Comment by davydden** [comment]
here's the one you refer to https://github.com/LLNL/spack/pull/2384, i suppose. I close this to move the discussion to the actual PR, fi you don't mind.
