### ISSUE TITLE
Installation issue: root

### ISSUE THREAD

**Issue by arekfu** [LLNL/spack#23886]
### Steps to reproduce the issue

Reproducible on CentOS 7, as well as (I suspect) any platform where native compiler in `/usr/bin` uses an old ABI.
```console
$ spack install gcc@7.5.0
$ spack compiler add --scope site $(spack location -i gcc@7.5.0)
$ spack install root@6.22.06%gcc@7.5.0
```
Compilation succeeds. However...
```console
$ spack load gcc@7.5.0 root@6.22.06
$ echo '#include "TObject.h"\nstruct Test : public TObject {\nClassDef(Test, 1)\n};' >Test.h
$ rootcling Test_dict.cxx Test.h
Error in <TInterpreter::InspectMembers>: TClass and cling disagree on the size of the class TBaseClass, respectively 152 128

Error in <TInterpreter::InspectMembers>: TClass and cling disagree on the size of the class TClassRef, respectively 40 16

Error in <TInterpreter::InspectMembers>: TClass and cling disagree on the size of the class TClassRef, respectively 40 16
```
The errors indicate an ABI mismatch between the compiler that was used to build ROOT (gcc 7.5.0) and the compiler that was used to inspect the `Test.h` header file. Indeed, running `rootcling` under `strace` shows that `rootcling` seems to invoke the compiler as `cc`. There is no such symlink in the `gcc` Spack installation, so the link is found in `/usr/bin/cc`, which points to `/usr/bin/gcc`. This was really tricky to figure out! I discussed the issue at length with the ROOT developers [here](https://root-forum.cern.ch/t/tclass-and-cling-disagree-on-the-size-of-the-class/44831).

I would argue that this is a Spack bug. First of all, ROOT really depends on the compiler it was used to build it, although I don't know if Spack is capable of expressing (I don't think we can use `depends_on()`) and enforcing this dependence. Second, the build is broken, but subtly so. I would argue that this is much worse than a package that does not compile.

### Information on your system

```console
$ spack debug report
* **Spack:** 0.16.1-2700-57017d5
* **Python:** 3.6.8
* **Platform:** linux-centos7-skylake_avx512
* **Concretizer:** original
```

I tested this in an environment with this configuration:
```console
$ cat spack.yaml
spack:
  specs: [gcc@7.5.0%gcc@7.5.0, python@3.9.0, root@6.22.06 ~opengl ~gdml ~xml ~x ^python@3.9.0]
  view: true
  packages:
    all:
      target: [x86_64]
```
The additional build flags for ROOT are simply there to remove some dependencies from the concretized spec and accelerate the build.

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/6539104/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/6539105/spack-build-env.txt)

@HadrienG2 @chissg @drbenmorgan @vvolkl 

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by vvolkl** [comment]
Hi @arekfu,

I've been bitten by this before, see https://github.com/spack/spack/issues/17488 and https://github.com/spack/spack/pull/18078 (as you can see from the lengthy conversations it was also tricky for me to figure out).

The good news is that there is a very easy workaround:  just symlink the spack-installed `gcc` to `cc`. Since it is a runtime issue, you don't even need to rebuild, just add the symlink and the build should be fixed.

As for how to fix this more permanently, I'm not sure. I agree that there is nothing to fix on the ROOT side, as in the spack build environment there is a compiler called `cc` and ROOT is right to assume this exists at runtime . On the spack side, it would be possible to create the cc symlink already in the root recipe, but as @adamjstewart pointed out, this won't help with other user-installed gcc's that don't necessarily have this symlink.

All I can think of is some special handling of packages needing the compiler at runtime. we could also create a `cc` symlink to the compiler in the root recipe and install that to bin. Also, a comment in the recipe might be helpful.

**Comment by arekfu** [comment]
The idea to add a `cc` symlink in the ROOT `bin/` directory crossed my mind, too. Would you accept a PR?

**Comment by arekfu** [comment]
@vvolkl As you may have noticed in [the discussion on the ROOT forum](https://root-forum.cern.ch/t/tclass-and-cling-disagree-on-the-size-of-the-class/44831/33), Axel Naumann hinted that ROOT can be configured to look for `cc` elsewhere at build time. Do you know how? That would probably be a cleaner solution, IMO.

**Comment by vvolkl** [comment]
Yes, thinking about this some more, I think this is the best solution. You should be able to get the path for the symlink with `self.compiler.cxx`.

I don't know how to tell ROOT what compiler to look for. If you manage that, you could also set the path to gcc directly there. However, I'm not sure if this will circumvent the compiler wrapper, and that would limit a lot of the functionality of spack, as it is used to inject compiler flags etc. (So, if the path you are setting there is only used by cling during runtime it is fine, but if it is used during the build to compile things it's better to go with the other solution)

**Comment by arekfu** [comment]
You have a good point with the compiler flags etc. Won't the symlink break this? For example, if we inject `-fabi-version=<n>` through the Spack wrapper...

**Comment by vvolkl** [comment]
For Key4hep, we've been using the symlink variant in production for quite a while without problem. In that particular case cling invokes the compiler only to get  include paths so I think it is ok.

**Comment by arekfu** [comment]
Alright, thanks. I'll see what I can do for the PR.

**Comment by vvolkl** [comment]
@arekfu  From Axel's reply on the root forum, it sounds like `-DCLING_CXX_PATH=self.compiler.cxx` would be used by cling at runtime, so that may indeed be be the best option.

**Comment by arekfu** [comment]
OK, I'll try that!
