### ISSUE TITLE
Please, bump elk versions to 7.* and fix linking

### ISSUE THREAD

**Issue by permeakra** [LLNL/spack#23949]
The elk version in the package builtin repo is very old (3.* while 7.* is released) and fails to link against external libxc, at least in my setup

I tried to update the elk/package.py for handling the latest version of elk, but failed. The issue is that elk slightly changed the way it links against external blas/lapack and requires to compile stubs for missing MKL/OpenBLAS

In addition handling of libxc in elk changed, I had to set             
            config['SRC_libxc'] = ' '.join([
                'libxcf90.f90',
                'libxcifc.f90'
            ])
after which this particular part apparently works fine.

**Comment by adamjstewart** [comment]
Spack's `elk` package currently has no official maintainer, which means that updates like adding new versions are up to community contributions. If you would like to submit a PR I would be happy to review it. I think I wrote the original `elk` package years ago but haven't needed it since.

**Comment by permeakra** [comment]
I'm interested, but I defintely can't test all possible configurations. Besides, I'm new with python, so I've no idea how much it might take.

**Comment by adamjstewart** [comment]
No worries, as long as the default configurations build for you I think that's sufficient until we have better package testing. From what you've described so far, it doesn't sound like there's too much that needs to be changed in the package. If you have any questions, you can skim the [Packaging Guide](https://spack.readthedocs.io/en/latest/packaging_guide.html) and [MakefilePackage](https://spack.readthedocs.io/en/latest/build_systems/makefilepackage.html) docs. If you have any questions or get stuck, please let me know!

**Comment by permeakra** [comment]
@adamjstewart could you give this attempt #24107  a look, please?

**Comment by permeakra** [comment]
@adamjstewart please, check #24432

**Comment by permeakra** [comment]
Still have to check how multithreading model is set up for dependencies, might need another commit.
