### ISSUE TITLE
Installation issue: clingo-bootstrap

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#23946]
Clingo fails to bootstrap on my system.

### Steps to reproduce the issue

Enable `clingo` as your preferred concretizer and let Spack build it.
```yaml
config:
  concretizer: clingo
```
You end up with many error messages like:
```
CMake Error at /data/keeling/a/adamjs5/.spack/bootstrap/store/linux-centos7-x86_64/gcc-9.3.0/cmake-3.20.2-kcsfzcfzurr7ywxdigfb2xg6dt27wsxr/share/cmake-3.20/Modules/FindPython/Support.cmake:602 (file):
  file STRINGS file "/usr/include/python3.6m/patchlevel.h" cannot be read.
Call Stack (most recent call first):
  /data/keeling/a/adamjs5/.spack/bootstrap/store/linux-centos7-x86_64/gcc-9.3.0/cmake-3.20.2-kcsfzcfzurr7ywxdigfb2xg6dt27wsxr/share/cmake-3.20/Modules/FindPython/Support.cmake:2916 (_python_get_version)
  /data/keeling/a/adamjs5/.spack/bootstrap/store/linux-centos7-x86_64/gcc-9.3.0/cmake-3.20.2-kcsfzcfzurr7ywxdigfb2xg6dt27wsxr/share/cmake-3.20/Modules/FindPython.cmake:535 (include)
  CMakeLists.txt:130 (find_package)
```

### Information on your system

* **Spack:** 0.14.1-6785-a40e39f
* **Python:** 3.6.8
* **Platform:** linux-centos7-haswell
* **Concretizer:** clingo

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/6550464/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/6550465/spack-build-env.txt)

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
For what it's worth, `clingo@5.5.0` builds just fine with the original concretizer, so I'm first installing and loading that instead of letting Spack bootstrap it.

**Comment by alalazo** [comment]
@adamjstewart Are Python header files installed for the system Python you're using?

**Comment by alalazo** [comment]
A similar issue in this [SO question](https://stackoverflow.com/questions/41732696/file-strings-file-opt-intel-mkl-include-mkl-version-h-cannot-be-read)

**Comment by adamjstewart** [comment]
> Are Python header files installed for the system Python you're using?

It looks like header files are installed for Python 2 but not Python 3 on this system. So if header files are required for bootstrapping I could set `SPACK_PYTHON` to `python2`.

**Comment by alalazo** [comment]
@adamjstewart Header files are required for bootstrapping from sources, since we need to compile a Python extension. Can you try #22720 on this system? That should work since it installs binaries.
