### ISSUE TITLE
Flex installation issues

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#2398]
I believe #2384 introduced some bugs to the flex installation. It now downloads from GitHub and runs autoreconf, but it must be missing some dependencies. On Fedora 24:
```
Can't exec "autopoint": No such file or directory at /home/ajstewart/spack/opt/spack/linux-fedora24-x86_64/gcc-6.2.1/autoconf-2.69-x5rbc5wjqydekkkjihgtjkoi7tzy6sco/share/autoconf/Autom4te/FileUtils.pm line 345.
autoreconf: failed to run autopoint: No such file or directory
autoreconf: autopoint is needed because this package uses Gettext
```
on CentOS 6:
```
autopoint: *** The AM_GNU_GETTEXT_VERSION declaration in your configure.ac file requires the infrastructure from gettext-0.19 but this version is older. Please upgrade to gettext-0.19 or newer.
autopoint: *** Stop.
autoreconf: autopoint failed with exit status: 1
```

**Comment by davydden** [comment]
@krafczyk ping.

**Comment by adamjstewart** [comment]
Adding a `gettext` build-type dependency gets me farther, but now it crashes at:
```
configure.ac:31: option `dist-lzip' not recognized
autom4te: closing standard output: Broken pipe
autoreconf: automake failed with exit status: 1
```

**Comment by adamjstewart** [comment]
Maybe `autoconf` needs to be built with lzip support for that option to be available? Or maybe it was removed in newer versions?

**Comment by adamjstewart** [comment]
Needed to add perl dependency to automake to get that to build, needed to add automake and gettext dependencies to flex to get that to autoreconf, now flex is crashing during make. One step at a time...

**Comment by krafczyk** [comment]
@davydden, @adamjstewart I'm sorry my commit broke the flex build on other OSs.

I'd like to help trouble shoot, but I am currently on vacation with the family and I can't devote time to it. I'll be able to do more on Monday.

**Comment by adamjstewart** [comment]
No worries, it's mostly solved in #2401. There was actually a separate tarball that did include the configure script, so I switched to that for the most recent builds.

**Comment by jgalarowicz** [comment]
I'm currently seeing this on Fedora 19 too.

==> bison is already installed in /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/bison-3.0.4-h6loqjgheotgixbfbadce56hv3icje74
==> Using cached archive: /home/jeg/spack/var/spack/cache/flex/flex-2.6.2.tar.gz
==> Already staged flex-2.6.2-y5p63csox6r5xbcqj2fxewo2fwcnge7e in /home/jeg/spack/var/spack/stage/flex-2.6.2-y5p63csox6r5xbcqj2fxewo2fwcnge7e
==> Already patched flex
==> Building flex [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Error: ProcessError: Command exited with status 1:
    './autogen.sh'
/home/jeg/spack/var/spack/repos/builtin/packages/flex/package.py:53, in autoreconf:
     51       def autoreconf(self, spec, prefix):
     52           autogen = Executable('./autogen.sh')
  >> 53           autogen()

**Comment by jgalarowicz** [comment]
Oh, I now see the 2401 fix in autoconf.  I'll wait and try again when that is merged.
Thanks!
