### ISSUE TITLE
Installation issue:  py-numpy

### ISSUE THREAD

**Issue by permeakra** [LLNL/spack#24076]
```console
$ spack install py-numpy
...
==> Error: ProcessError: Command exited with status 1:
    '/usr/bin/python3.8' '-s' 'setup.py' '--no-user-cfg' 'build'
See build log for details:
  /tmp/permeakra/spack-stage/spack-stage-py-numpy-1.20.3-moeytesgplajh7ebnge5ultezzwfu3h3/spack-build-out.txt

$ spack build-env py-numpy python
Python 3.8.5 (default, Jan 27 2021, 15:41:15) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Cython
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'Cython'
```
### Information on your system

spack debug report 
* **Spack:** 0.16.2-2966-690558f927
* **Python:** 3.8.5
* **Platform:** linux-ubuntu20.04-haswell
* **Concretizer:** original

Forced use of external system python. Spack insists on installing its own Cython. Purging external cython didn't have obvious effect.

### Additional information

there were remnants of python2 in the system. Purging them didn't do anything, but maybe  I missed smth

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by permeakra** [comment]
[spack-build-env.txt](https://github.com/spack/spack/files/6581915/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/6581916/spack-build-out.txt)

**Comment by permeakra** [comment]
@adamjstewart please, look as a maintainer.

**Comment by adamjstewart** [comment]
Hmm, Cython is in your `PYTHONPATH`, so I'm not sure why Python wouldn't be able to find it. Spack should theoretically support this, and I'm not sure why it isn't working. Can you run the following tests for me?
```console
$ ls /home/permeakra/spack/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/py-cython-0.29.22-iyt6swlafaunff4uawkj7w6adtq2wusm/lib*/python3.8/site-packages/
$ spack build-env py-numpy bash
$ echo $PYTHONPATH
```
I don't often to try to use external installations of packages, I just let Spack build everything for me. I'm sure if you let Spack build Python for you, you wouldn't encounter this problem. So that's one workaround if you're in a hurry. But we should also try to fix this.

**Comment by balos1** [comment]
I believe that I am running into this exact same issue.

**Comment by permeakra** [comment]
@adamjstewart 

 
 ```
$ls /home/permeakra/spack/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/py-cython-0.29.22-iyt6swlafaunff4uawkj7w6adtq2wusm/lib*/*/*
```
> /home/permeakra/spack/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/py-cython-0.29.22-iyt6swlafaunff4uawkj7w6adtq2wusm/lib/python3.8/site-packages:
> 
> /home/permeakra/spack/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/py-cython-0.29.22-iyt6swlafaunff4uawkj7w6adtq2wusm/lib/python3/dist-packages:
> Cython  Cython-0.29.22-py3.8.egg-info  cython.py  __pycache__  pyximport
> 

site-packages is empty, dist-packages is not... I assume, site-packages should not be empty and the problem is actually with cython?

```
$spack build-env py-numpy bash
$echo PYTHONPATH | tr : '\n'
```

> /home/permeakra/spack/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/py-numpy-1.20.3-moeytesgplajh7ebnge5ultezzwfu3h3/lib/python3.8/site-packages
> /home/permeakra/spack/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/py-numpy-1.20.3-moeytesgplajh7ebnge5ultezzwfu3h3/lib64/python3.8/site-packages
> /home/permeakra/spack/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/py-cython-0.29.22-iyt6swlafaunff4uawkj7w6adtq2wusm/lib/python3.8/site-packages
> /home/permeakra/spack/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/py-cython-0.29.22-iyt6swlafaunff4uawkj7w6adtq2wusm/lib64/python3.8/site-packages
> /home/permeakra/spack/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/py-setuptools-50.3.2-zoe5bu56il2nupejc2lyqdhbtz6sr622/lib/python3.8/site-packages
> /home/permeakra/spack/opt/spack/linux-ubuntu20.04-haswell/gcc-9.3.0/py-setuptools-50.3.2-zoe5bu56il2nupejc2lyqdhbtz6sr622/lib64/python3.8/site-packages

**Comment by permeakra** [comment]
Hm. Apparently, this situation (dist-package/site-package ) is quite common and seems to have roots in Debian internal conventions. This *might* be Ubuntu/Debian-specific problem.

here are the build/install logs for py-cython
[spack-build-01-build-out.txt](https://github.com/spack/spack/files/6583011/spack-build-01-build-out.txt)
[spack-build-02-install-out.txt](https://github.com/spack/spack/files/6583012/spack-build-02-install-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/6583013/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/6583014/spack-build-out.txt)

it installs into dist-packages.

**Comment by permeakra** [comment]
After further search this appears to be debian-derivative specific problem https://matthew-brett.github.io/pydagogue/debian_python_paths.html
Due to debian conventions, sometimes things go into dist-packages instead of site-packages. 

There were inconsistencies here in the past, https://bugs.launchpad.net/ubuntu/+source/python2.6/+bug/362570 , so some nontrivial problems might arise.

**Comment by adamjstewart** [comment]
Thanks for figuring out the issue! We've had problems with this in the past (`lib` vs `lib64`) so this should be easy to fix. I'll put out a PR tonight for you to test.

**Comment by wspear** [comment]
I believe I'm seeing the same issue. Cython libs are appearing in <install>/lib/python3/dist-packages/ but py-numpy fails when attempting to use cython, on Ubuntu focal.  Would it be too terrible of a kludge to just have the spack package symlink the contents of dist-packages to site-packages for systems that install/look in the wrong place?

**Comment by adamjstewart** [comment]
@wspear this won't work for external packages, so I try to avoid hacks like symlinks. I was hoping there was a way to query Python to ask it where files will be installed to. I'll have to dig deeper into distutils to see how they decide where to install things when you run `python setup.py install`.

**Comment by rgommers** [comment]
Debian indeed makes a giant mess of this. NumPy does provide a public function to query for the correct include path, this is always reliable:
```bash
$ python -c "import numpy; print(numpy.get_include())"
```

**Comment by adamjstewart** [comment]
Thanks @rgommers. It seems like this problem is more broad than just numpy. Numpy just happens to be the second package that people install (after cython) and the build fails because it can't find cython. I believe #24095 should fix this.
