### ISSUE TITLE
Installation issue: py-torch fails to build on air-gap system

### ISSUE THREAD

**Issue by KineticTheory** [LLNL/spack#24091]
### Steps to reproduce the issue

```console
$ spack install py-torch@1.8.1 % gcc@8.3.0

-- Building version 1.8.1
Could not find <path>/spack-src/third_party/gloo/CMakeLists.txt.
Did you run 'git submodule update --init --recursive
==> Error.
```

### Additional information

This issue only occurs on an air-gap system.  I cannot attached build logs.

### General information

I'm not sure how the installer is supposed to access these *third_party* sources.  Does spack have a way to provide these as externals?  Is anyone else trying to build `py-torch` on an air gap system?

**Comment by KineticTheory** [comment]
I am trying to create a source tarfile that contains all of the git submodule information that I can add to my mirror.  I'll update the ticket if this works.

**Comment by KineticTheory** [comment]
> I am trying to create a source tarfile that contains all of the git submodule information that I can add to my mirror. I'll update the ticket if this works.

I found a hack that allowed me to install.  
* clone the pytorch repo
* checked out the 1.8.1 tag
* ran `git submodule update --init --recursive`
* created a source tarball that included all of the submodule packages
* saved the source tarball to the spack mirror on the air gap system
* ran `spack install -n py-torch % gcc@8.3.0`

This doesn't seem like a very elegant solution, but at least it allowed me to install py-torch.

cc: @adamjstewart

**Comment by adamjstewart** [comment]
@KineticTheory thanks for opening this issue! I was aware that PyTorch and TensorFlow couldn't be built on an air-gapped network but it sounds like the situation is better than I thought. If we can get the submodules into the mirror then we should be good to go.

@scheibelp @becker33 @tldahlgren why aren't submodules being included in mirror tarballs? That sounds like it would be an easy thing to do.

**Comment by scheibelp** [comment]
I can look into this by June 8th (upcoming Tuesday)

**Comment by scheibelp** [comment]
If I run

```
spack mirror create -d test-mirror py-torch@1.8.1~cuda~cudnn~nccl
```

(note: for individual specs like here, you have to specify something that concretizes, in my case the easiest way to do that is by adding `~cuda~nccl~cudnn`)

An archive of `py-torch` is created which includes the submodules, and that appears to be used when fetching py-torch (if I add that directory as a mirror).

Is something going wrong when you do something similar? Basically if you have a well-defined version of something (e.g. not a branch tip like in this case) then you should be able to move everything needed with `spack mirror` (i.e. create the mirror with that command, move it and then `spack mirror add` that directory on the other machine).

**Comment by KineticTheory** [comment]
With a modern version of spack, it seems that py-torch has all of the submodules included in the source tar-file in my mirror.  The mirror I'm using is maintained by my organization and they were using a much older version of spack that didn't have this capability and that confused me.

If I only have access to the mirror, is there any way to know what version of spack was used to generate it?

**Comment by scheibelp** [comment]
> If I only have access to the mirror, is there any way to know what version of spack was used to generate it?

No  - no easy way anyway, like a file placed in the mirror directory; if I had to do it, I might try to collect all the hashes and then cross reference from there (but that would require significant programming to make use of).

If you are able to update the mirror using a newer Spack version, do you think that would resolve this issue? Or are there additional problems to address?

**Comment by KineticTheory** [comment]
Now that our mirror is updated with a newer version of spack, this problem is no more. Thanks for working with me.
