### ISSUE TITLE
add support for libxc in quantum espresso package

### ISSUE THREAD

**Issue by permeakra** [LLNL/spack#24178]
recent versions of quantum espresso support linking with libxc.  spack's qe package currently doesn't appear to support it. 

note : linking with libxc@5: requires patching the source atm, see 2.5.1.1 https://www.quantum-espresso.org/Doc/user_guide/node12.html

/

**Comment by alalazo** [comment]
@naromero77

**Comment by naromero77** [comment]
If someone else is willing to do the work and do the PR, I am willing to review it. But I don't have the cycles to do this work at the moment, as it is not aligned with my current work responsibilities.

**Comment by alalazo** [comment]
@naromero77 I realize I have been a bit short of words in the previous comment. I pinged you just to make you aware of this issue since:
```console
$ spack maintainers quantum-espresso 
naromero77
```
@permeakra Would it be fine with you to submit a PR for that?
