### ISSUE TITLE
Change Lmod template syntax for dependencies

### ISSUE THREAD

**Issue by mcuma** [LLNL/spack#24259]
The Lmod template, share/spack/templates/modules/modulefile.lua, defines the loading of the dependencies that a given module may have with
{% block autoloads %}
{% for module in autoload %}
if not isloaded("{{ module }}") then
{% if verbose %}
    LmodMessage("Autoloading {{ module }}")
{% endif %}
    load("{{ module }}")
end
{% endfor %}
{% endblock %}

which results with syntax like
if not isloaded("linux-centos7-nehalem/python/3.8.6") then
    load("linux-centos7-nehalem/python/3.8.6")
end

The effect of the load() function on unload of the parent module is to unconditionally unload this dependent module. This may have the undesired effect of unloading a dependent module that may be a dependence of another loaded module. The depends_on() function is better suited for this situation, the dependent module will not get unloaded if other loaded module has it listed as a dependncy. See https://lmod.readthedocs.io/en/latest/098_dependent_modules.html for details on difference between load() and depends_on().

I suggest to change from load() to depends_on(), as:
{% block autoloads %}
{% for module in autoload %}
{% if verbose %}
    LmodMessage("Autoloading {{ module }}")
{% endif %}
depends_on("{{ module }}")
{% endfor %}
{% endblock %}

which in our concrete example above would also result in a simpler syntax:
depends_on("linux-centos7-nehalem/python/3.8.6")

Thanks,
Martin

**Comment by xdelaruelle** [comment]
Such modification has implemented in 2022 by @haampie with #28352.
