### ISSUE TITLE
qt+webkit does not build

### ISSUE THREAD

**Issue by manuelakuhn** [LLNL/spack#24254]
I wanted to build qt+webkit but ran into multiple problems. I need version 5.12.10 as a dependency for a package I want to build.

I tried to build 
```
$ spack install qt+webkit@5.12.10 %gcc@10.3.0
```
the first problem is that the python2 requirement is not set. This can easily be fixed by

```diff
-    depends_on("python@2.7.5:2.999", when='@5.14: +webkit', type='build')
+    depends_on("python@2.7.5:2.999", when='+webkit', type='build')
```

Then qt builds but webengine does not due to a missing mesa dependency
```
khronos development headers appear to be missing (mesa/libegl1-mesa-dev)
QtWebEngine will not be built.
```

When building `qt+webkit+opengl@5.12.10 %gcc10.3.0` (since gl has a mesa dependency), now nss is missing
```
A suitable version of nss could not be found.
QtWebEngine will not be built.
```
but nss is not in spack

Also the following combinations build qt (with the fix above) but do not build webengine
- `qt+webkit@5.14.2 %gcc@9.3.0` -> missing mesa
- `qt+webkit@5.15.2 %gcc@9.3.0` -> missing nss

I tried these combinations because I found them in #17270

Then I tried the most current combination `qt+webkit@5.15.2 %gcc@11.1.0` but here qt does not build.

@sethrj maybe you can help

### Information on your system

* **Spack:** 0.13.4-8281-849943c63d
* **Python:** 3.5.3
* **Platform:** linux-debian9-piledriver
* **Concretizer:** clingo

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by sethrj** [comment]
OK, thanks for the  bump to the  'conflicts' version: when I add conflicts I try to only add them for "known" versions not "suspected". We should also add a conflict for `+webkit ~opengl`.  Could you submit a PR and mention me on it?

As to the next step, can you upload the log files please? Then we can try to track down the next issue.

**Comment by manuelakuhn** [comment]
I was not sure which combination you wanted, so I added all I had. I also rerun the combinations with the patch to get a updated picture.  For my use case I would only need 5.12.10 preferable with gcc 11.

- `qt+webkit+opengl@5.12.10 %gcc@9.3.0`
   with full patch applied

  -> webengine does not build

  [spack-build-out.txt](https://cloud.ovgu.de/s/EtPPtMD9MRgwASE)

- `qt+webkit+opengl@5.12.10 %gcc@10.3.0`
  with full patch applied

  -> webengine does not build

   [spack-build-out.txt](https://cloud.ovgu.de/s/KMBqSdAEn5H37KZ)

- `qt+webkit+opengl@5.12.10 %gcc@11.1.0`
  with full patch applied

   -> llvm dependency does not build, see #24270

- `qt+webkit@5.15.2 %gcc@11.1.0`
  (only python patch, not conflict)

  -> qt does not build

  [spack-build-out.txt](https://cloud.ovgu.de/s/jbE8N5x4NqQsL3D)

- `qt+webkit+opengl@5.15.2 %gcc@11.1.0`
  with full patch applied

  -> llvm dependency does not build, see #24270

**Comment by sethrj** [comment]
I downloaded the first build output (spack-build-out-qt-5-12-10-gcc-9-3-0) but can't find any actual build errors in it. It looks like it correctly built qtwebengine (which superseded webkit from Qt 5.7+) and successfully finished the qt bulid.

It's not surprising that llvm 10 failed on gcc11... it's the price of compilers geting more strict. Wonder why it didn't use a newer llvm.

**Comment by manuelakuhn** [comment]
Yes that is part of the problem. In the first and second case (gcc 9 and gcc 10) there are no build error for qt itself but it just skips webengine and does not build it
see line 32858 of the gcc 9 (line 33131 of gcc 10):
```
A suitable version of nss could not be found.
QtWebEngine will not be built.
```

**Comment by sethrj** [comment]
Oh there it is... wow that's easy to miss.

From a little googling it looks like you're not the only one with this problem. I don't know why qt errors out so late in the game rather than during configure. And I don't know what nss is...

I'm not sure why the concretizer is picking up an older version of llvm.  Try using `^llvm@11:` and I'll add a PR with the gcc/llvm conflict so the new clingo concretizer will try to find a workaround.  If llvm is coming in through mesa, you can disable that.

But I don't think either of those is going to solve the missing nss  issue. If you can create  a spack package for nss, you can then add `depends_on('nss',  when='@5.7: +webkit')`  to the qt recipe and hope that solves it. I unfortunately lack the time to do that on my own... qt is a beast.
