### ISSUE TITLE
Installation issue: py-gevent

### ISSUE THREAD

**Issue by wspear** [LLNL/spack#24286]
### Steps to reproduce the issue

```console
$ spack install py-gevent
...
```

### Information on your system

* **Spack:** 0.16.2-3107-177750b215
* **Python:** 3.8.5
* **Platform:** linux-ubuntu20.04-westmere
* **Concretizer:** original

### Additional information

Salient error output:
```

1402    src/gevent/_semaphore.c: In function '__Pyx_modinit_type_init_code':
  >> 1403    src/gevent/_semaphore.c:6410:45: error: 'PyTypeObject' {aka 'struct _typeobject'} has no member named 'tp_print'
     1404     6410 |   __pyx_type_6gevent_11__semaphore_Semaphore.tp_print = 0;
     1405          |                                             ^
  >> 1406    src/gevent/_semaphore.c:6423:52: error: 'PyTypeObject' {aka 'struct _typeobject'} has no member named 'tp_print'
     1407     6423 |   __pyx_type_6gevent_11__semaphore_BoundedSemaphore.tp_print = 0;
     1408          |                                                    ^

```

* [spack-build-out.txt](https://github.com/spack/spack/files/6641285/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/6641286/spack-build-env.txt)

@adamjstewart 

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
I'm able to build `py-gevent` without any problems on macOS 10.15.7 with Apple Clang 12.0.0 and on Ubuntu 18.04 with GCC 7.5.0, although I do see that `tp_print` is deprecated and raising warnings. It looks like there are much newer versions of `py-gevent` available. Have you tried any of those?

**Comment by wspear** [comment]
This seems to have been related to something poisonous in my .spack directory (possibly external related but that's not as clear as my issue with mpfr). Cleared it out and now it builds.
