### ISSUE TITLE
Building an Autotools package in a different directory

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#2428]
@alalazo I'm trying to write an Autotools package, but the configure script is in a subdirectory. How can I specify a different directory to build in?

**Comment by alalazo** [comment]
Currently `AutotoolsPackage` doesn't have any mechanism like `CMakePackage` to specify an alternative build directory. If you think it would be a useful feature in general I can prepare a PR tomorrow.

 I didn't implement it in the first place because, even if I know that in principle it can be done, I have never seen an `autotools` package build out of source (only exception `gcc`).

**Comment by adamjstewart** [comment]
I'm having trouble getting it working anyway. With the regular Package class, I'm using:
```python
def install(self, spec, prefix):
    with working_dir('js/src'):
        configure('--prefix={0}'.format(prefix))
        make()
        make('install')
```
but it's crashing with weird error messages. When I do the same outside of Spack, it works.

**Comment by alalazo** [comment]
Just a wild guess, but you may try:
```python
def install(self, spec, prefix):
    configure = Executable(join_path(self.stage.source_path, 'js', 'src'))
    with working_dir('js/src'):
        configure('--prefix={0}'.format(prefix))
        make()
        make('install')
```
and see if it is the path of the `Executable` that creates the problem. Is the package publicly available in case?

**Comment by adamjstewart** [comment]
Still seeing the same error message:
```
Traceback (most recent call last):
  File "/blues/gpfs/home/software/spack-0.10.0/var/spack/stage/mozjs-24.2.0-nctczxjxejy6biupp446u4rylp3bmj2p/mozjs-24.2.0/js/src/config/expandlibs_exec.py", line 26, in <module>
    from expandlibs import ExpandArgs, relativize, isObject, ensureParentDir, ExpandLibsDeps
  File "/tmp/ajstewart/spack-stage/spack-stage-lORb2I/mozjs-24.2.0/js/src/config/expandlibs.py", line 31, in <module>
    import expandlibs_config as conf
  File "/tmp/ajstewart/spack-stage/spack-stage-lORb2I/mozjs-24.2.0/js/src/config/expandlibs_config.py", line 5, in <module>
    from buildconfig import substs
  File "/blues/gpfs/home/software/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-6.1.0/python-2.7.12-xuk7nsxqjm2jlitd4f4b5eyxzkgaf5oz/lib/python2.7/site-packages/buildconfig.py", line 13, in <module>
    raise Exception("Can't find config.status")
Exception: Can't find config.status
```
despite the fact that `config.status` exists in `js/src`. The package is for [SpiderMonkey](https://developer.mozilla.org/en-US/docs/Mozilla/Projects/SpiderMonkey), Mozilla's JavaScript engine. I'm specifically trying to build [this version](http://ftp.mozilla.org/pub/js/mozjs-24.2.0.tar.bz2). I wonder if `js/src` is just not in the PYTHONPATH for some reason. But I thought `.` was always in the PYTHONPATH. Does Spack clear this?

**Comment by adamjstewart** [comment]
Interesting. When I remove the Python build dependency and just use my system Python installation, it works!

**Comment by adamjstewart** [comment]
As of #2742, the `AutotoolsPackage` base class now supports building packages with a configure script that is not in the root directory. Simply override the `build_directory` method. See `tk` and `tcl` for examples.
