### ISSUE TITLE
Installation issue: mpfr

### ISSUE THREAD

**Issue by wspear** [LLNL/spack#24287]
### Steps to reproduce the issue

```console
$ spack install mpfr
...
```

### Information on your system

* **Spack:** 0.16.2-3107-177750b215
* **Python:** 3.8.5
* **Platform:** linux-ubuntu20.04-westmere
* **Concretizer:** original

### Additional information

Salient error:
`/tmp/pytest-of-wspear/pytest-2/mock-stage0/spack-stage-mpfr-4.1.0-6rrd4ugygkcolfme4qt2zq75cmmpc7xk/spack-src/missing: line 81: makeinfo: command not found`

[spack-build-out.txt](https://github.com/spack/spack/files/6641402/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/6641403/spack-build-env.txt)

(No maintainers listed, but the two primary committers on this file.)

@tgamblin 
@adamjstewart 

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
At least on develop, `mpfr` has a build dep on `texinfo`, which provides this command. I was able to build `mpfr` on Ubuntu 18.04 with GCC 7.3.0 even though `makeinfo` isn't on the system. Can you check to make sure the package is up-to-date?

**Comment by wspear** [comment]
My bad. Texinfo was an external and it somehow got removed from my system. A sanity check on existing externals, at least when external find or list is called, might be handy.
