### ISSUE TITLE
Feedback on using Reproducible builds in CI

### ISSUE THREAD

**Issue by adrienbernede** [LLNL/spack#24292]
Disclaimer: I am using Spack pipeline feature in a context that is different than the one in Spack CI. I run CI on a cluster, where runners consist in shells instances that run as me. The file system is shared.

Bug: The current implementation does not support the case where the environment file (`spack.yaml`) includes another file, like `compiler.yaml` or `packages.yaml`.

### Steps to reproduce the issue

Write a spack pipeline with a `spack.yaml` that has includes in it.

### Error Message

The included files will not be detected and added to the artifact. This is impacting:
- at generation level -> the jobs will not be able to run without those files.
- at reproducibility level -> the jobs will not be reproducible without those files. 

### Information on your system

* **Spack:** 0.16.1-3158-8b75e81666
* **Python:** 3.7.2
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** original

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

@scottwittenburg

**Comment by alalazo** [comment]
@scottwittenburg @adrienbernede Is this still an issue?

**Comment by scottwittenburg** [comment]
I'll leave to Adrien to say for sure, but it seems like this could be fixed by the recent environment includes work?

**Comment by adrienbernede** [comment]
@alalazo I acknowledge reading this. It’s not easy to state whether this is still an issue: so many things have changed and I don’t have an updated reproducer handy.
I’m fine with closing this. I would open a brand new issue with updated syntax if needed.
