### ISSUE TITLE
Installation issue:  py-matplotlib with Oneapi intel compiler

### ISSUE THREAD

**Issue by samcom12** [LLNL/spack#24327]
[spack-build-01-build-out.txt](https://github.com/spack/spack/files/6653056/spack-build-01-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/6653057/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/6653058/spack-build-out.txt)

Looks like a linker error with clang++ / icpx 

@danvev @rscohn2

**Comment by samcom12** [comment]
Is it something related to freetype@7 + version, earlier intel compiler doesn't support it.

**Comment by adamjstewart** [comment]
Can you try again with the latest release of matplotlib? If it's still an issue, can you open an issue with the matplotlib developers? This seems like a bug in their code, not in the Spack build recipe. If they provide a patch I can add it to the package.
