### ISSUE TITLE
OpenMPI: Update preferred version

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#24396]
The OpenMPI package lists version 4.0.5 as the preferred version. Initially, this only meant that version 4.1.0 would not be installed by default. By now, successor versions 4.0.6 and 4.1.1 are available.

It might now be possible to remove `preferred=True` tag, or to move it forward. If not, its reason should be documented.

**Comment by adamjstewart** [comment]
Pinging the OpenMPI maintainers to make this happen: @hppritcha @naughtont3

**Comment by hppritcha** [comment]
will deal with this today along with #24391

**Comment by naughtont3** [comment]
@hppritcha Again for my education, this is matter of moving `preferred` up in `packages.yaml`.  Do we have guide/process for when to move from 4.0.x to 4.1.x as "preferred" (i.e., switch forward for minor release based on past procedures)?  Or is it generally to just track "latest" stable at highest release?  Thanks.

**Comment by eschnett** [comment]
The general guideline is to not have a `preferred` tag at all unless necessary. Such a tag would be introduced when a new release is known to be faulty (and shouldn't generally be used), or when it unexpectedly breaks too many other packages.

If there's a known bug or severe incompatibility in 4.1.x, then Spack could reasonably decide to stay on 4.0.x. (In this case, it would make sense to document the problem in a comment near the `preferred` tag.)

If there is no good, specific reason why a particular version should be preferred, then the tag should be removed.

**Comment by hppritcha** [comment]
adding to @eschnett I would generally not have a 0 ompi release be preferred.  so when we added 4.1.0 we should have set 4.0.5 to preferred in any case.

**Comment by naughtont3** [comment]
Thanks @hppritcha and @eschnett
