### ISSUE TITLE
Installation issue: z3

### ISSUE THREAD

**Issue by bcdarwin** [LLNL/spack#24449]
A Z3 Cmake build using a system Python specified via `packages.yaml` tries to write into the system Python's directory and fails due to privileges.  If a non-system Python3 is used, z3 is installed to its `site-packages`.

Possibly related to #24337 ?

### Steps to reproduce the issue

```console
$ spack install z3
 ...
  >> 3267    CMake Error at src/api/python/cmake_install.cmake:49 (file):
     3268      file cannot create directory: /usr/lib/python3/dist-packages/z3.  Maybe
     3269      need administrative privileges.
     3270    Call Stack (most recent call first):
     3271      src/cmake_install.cmake:181 (include)
     3272      cmake_install.cmake:73 (include)
 ...
```

### Information on your system

```
* **Spack:** 0.16.2-3213-7b6ca59038
* **Python:** 3.8.5
* **Platform:** linux-ubuntu20.04-broadwell
* **Concretizer:** original
```

In `packages.yaml`:
```
  python:
    externals:
    - spec: python@3.8.5+bz2+ctypes+dbm+lzma+nis+pyexpat+readline+sqlite3+ssl~tix~tkinter+uuid+zlib
      prefix: /usr
```

### Additional information

* [spack-build-out.txt]()
* [spack-build-env.txt]()

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by EthanS94** [comment]
I'm also hitting this when using an external python.

```console
  >> 3251    CMake Error at src/api/python/cmake_install.cmake:54 (file):
     3252      file cannot create directory:
     3253      /projects/opt/centos7/anaconda3/lib/python3.5/site-packages/z3.  Maybe need
     3254      administrative privileges.
     3255    Call Stack (most recent call first):
     3256      src/cmake_install.cmake:186 (include)
     3257      cmake_install.cmake:78 (include)
     3258    
     3259    
  >> 3260    make: *** [install] Error 1
```
