### ISSUE TITLE
Spack allows relative paths for `install_tree` and similar

### ISSUE THREAD

**Issue by BenWeber42** [LLNL/spack#24465]
It's possible to set relative paths in spack's config files for locations such as the install prefix (`install_tree`), the stage directory, the cache directory, etc. In this case the current working directory will matter when installing software. So when a user `cd`s into another directory, spack will recreate all those resp. directories (e.g., `install_tree`) again.

### Steps to reproduce the issue

`install_tree` is set to a relative path `./pkg`

```console
$ spack config get config | grep install_tree
  install_tree: ./pkg
```

```console
 /scratch/path1 
$ spack install zlib
==> Installing zlib
==> No binary for zlib found: installing from source
==> zlib: Executing phase: 'install'
[+] /scratch/path1/pkg/zlib/1.2.11/pgi/oc33sfxlwznukamv2xwdabgs5wugja3j
```

When `cd`ing into a different directory, the `install_tree` will be recreated there:

```console
 /scratch/path2 
$ spack install zlib
==> Installing zlib
==> No binary for zlib found: installing from source
==> zlib: Executing phase: 'install'
[+] /scratch/path2/pkg/zlib/1.2.11/pgi/oc33sfxlwznukamv2xwdabgs5wugja3j

```

### Information on your system

```console
$ spack debug report
* **Spack:** 0.15.4
* **Python:** 3.7.4
* **Platform:** linux-rhel7-skylake_avx512
```

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] ~~I have run the failing commands in debug mode and reported the output~~

**Comment by alalazo** [comment]
Allowing relative paths is useful e.g. in environments, so that one can move around a `spack.yaml` file and recreate a store, etc. in the same directory where the environment is located.
