### ISSUE TITLE
Feature request: pdb debugging option

### ISSUE THREAD

**Issue by lee218llnl** [LLNL/spack#245]
@tgamblin would it be beneficial to have an option to launch spack under the pdb debugger in a similar manner to what exists for profiling? I can easily implement this myself, but if you think it is worthwhile, then I was hoping to get an opinion on what the command-line arg should be since -d, --debug is already taken. I was thinking -D, --pdb, but am open to other suggestions.

**Comment by tgamblin** [comment]
@lee218llnl: I think it could be useful -- is this just a new option in the base spack script?  `--pdb/-D` is fine with me.  I haven't played much with pdb but I know the code pretty well and know where to put the prints :).

**Comment by lee218llnl** [comment]
Yes, it would be in the base spack script, just like the -p option. It's nice to be able to step through the code and the interface is similar to gdb. I will work on a PR for this.

**Comment by tgamblin** [comment]
Thanks!
