### ISSUE TITLE
Installation issue: openpmd-api / gmp

### ISSUE THREAD

**Issue by LDAmorim** [LLNL/spack#24520]
Hi,

I've been trying to install and run code with the `spack` module `openpmd-api`, but have found a `HDF5`-apparent error message with it (reported in https://github.com/openPMD/openPMD-api/issues/1021).

@ax3l has been helping me and suggested that I tried to use `spack` environments instead.
Although all the modules were installed via `spack`, when installing them in a new environment, `zstd` was re-installed, and `gmp` was starting to be installed, but gave an error message (which is why I am writing this issue and which I don't know how to solve).

### Steps to reproduce the issue

Initial installation of packages:
```console
$ spack install gcc
$ spack compiler find
$ spack load gcc
$ spack compiler find
$ spack install cmake
$ spack load cmake
$ spack install mpich
$ spack load mpich
$  spack install openpmd-api
```

Creation of the environment (ending with `gmp` installation error):
```console
$ spack env create opmd
$  spack env activate opmd
$  spack add cmake
$ spack add mpich
$  spack add gcc
$  spack add openpmd-api
$  spack concretize
$  spack find -c
$  spack install
```

Error messages and more detailed view of what I did/got are in:
[spack_env_shell.txt](https://github.com/spack/spack/files/6715097/spack_env_shell.txt)

### Information on my (Windows 10 local machine) system

```console
$ spack debug report
* **Spack:** 0.16.2-3140-ca1d1c427c
* **Python:** 3.8.2
* **Platform:** linux-ubuntu20.04-skylake
* **Concretizer:** original
```

I have changed *spack/etc/spack/defaults/packages.yaml* line to `mpi: [mpich, openmpi]` to build with mpich by default.

### Additional information

* [[spack-build-env.txt](https://github.com/spack/spack/files/6715090/spack-build-env.txt)
* [spack-build-out.txt](https://github.com/spack/spack/files/6715092/spack-build-out.txt)

@ ax3l

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by scheibelp** [comment]
> Information on my (Windows 10 local machine) system

To check, is this Windows Subsystem for Linux (WSL)?

In the case of the gmp installation failure, it looks like the error message is

> No rule to make target 'hgcd_step.c', needed by 'hgcd_step.lo'.  Stop.

weird. Are you able to build just gmp in a new environment? If there is a failure in that environment, would you be able to `spack cd gmp` and look for something that might generate that `hgcd_step.c` file?

> when installing them in a new environment, zstd was re-installed,

Without seeing the hashes and full-dag, it would be hard to know if this is wrong: if anything changes about a dependency/compiler for example that would be expected.

**Comment by LDAmorim** [comment]
Hi @scheibelp , thanks for your reply.

Yes, this is the ubunto terminal on Windows 10, which is described by its initial message:
```
Welcome to Ubuntu 20.04.1 LTS (GNU/Linux 4.4.0-19041-Microsoft x86_64)
 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  System information as of Mon Jun 28 11:28:18 WEST 2021

  System load:    0.52      Processes:              7
  Usage of /home: unknown   Users logged in:        0
  Memory usage:   38%       IPv4 address for wifi0: 192.168.1.172
  Swap usage:     0%

94 updates can be installed immediately.
35 of these updates are security updates.
To see these additional updates run: apt list --upgradable

The list of available updates is more than a week old.
To check for new updates run: sudo apt update

This message is shown once once a day. To disable it please create the
/home/lidipiamorim/.hushlogin file.
```

I used it without a problem, only with `spack` a few months back to install the same packages (`gcc`, `cmake`, `mpich` and `opepmd-api`).

I tried to install `gmp` in a new environment without anything else and it worked (version 6.2.1), thank you!
But when I tried back the `opmd` environment, even gcc was going to be re-installed and I didn't understand why...
So I made a new `spack` folder, where I didn't install anything except gcc and just created the environment (with all packages added with `%gcc@11.1.0`) to test this better. I will update on the result asap.

Oh sorry, I'm not sure how to get that information but you do make sense.
Does this contain the information you mean?
```
spack load zstd
==> Error: zstd matches multiple packages.
  Matching packages:
    bmyb7y5 zstd@1.5.0%gcc@9.3.0 arch=linux-ubuntu20.04-skylake
    q6s7alr zstd@1.5.0%gcc@11.1.0 arch=linux-ubuntu20.04-skylake
    z3ipeqb zstd@1.5.0%gcc@11.1.0 arch=linux-ubuntu20.04-skylake
  Use a more specific spec.
```

The first `zstd` was used to build `gcc@11.10` with `gcc@9.3.0` from ubunto.
The others were `q6s7alr` created for the environment `opmd` and `z3ipeqb` for `openpmd-api`.

Thanks

**Comment by ax3l** [comment]
Hm, do you need `gcc` (and thus `gmp`) from Spack or can you compile your software stack with the gcc/g++ that is provided by the Ubunu/WSL `apt` packages?

I would try this:
```bash
sudo apt update
sudo apt install build-essential curl gcc git g++ make cmake
```

Then this:
```bash
spack env create openpmd-dev
spack env activate openpmd-dev
spack add cmake
spack add mpich
spack add openpmd-api
# optional:
# spack add python
# spack add py-pip
spack install
```

That should provide a full dev environment.

Important: make sure your downstream projects use the same
- compiler version (`export CC=...`, `export CXX=...`)
- MPI implementation & version (`export MPI_HOME=...`)
- clean CMake build directory

for building. Your underlying issue looks like an OpenMPI/MPICH or compiler mismatch to me.

GMP 6.2.1 seems to have indeed an install issue on your Ubuntu/WSL with GCC 11.1.0:
```
==> Installing gmp-6.2.1-f5iveq5acljav7syj25flco435x5z37z
...
  >> 411    ./config.status: line 1624: /usr/bin/sed: Invalid argument
...
     937    /bin/bash ../libtool  --tag=CC   --mode=compile /mnt/d/Diana/opt/spack/lib/spack/env/gcc/gcc -DHAVE_CONFIG_
            H -I. -I..  -D__GMP_WITHIN_GMP -I.. -DOPERATION_`echo hgcd2 | sed 's/_$//'`   -O2 -pedantic -fomit-frame-po
            inter -m64 -mtune=k8 -march=k8 -c -o hgcd2.lo hgcd2.c
  >> 938    make[2]: *** No rule to make target 'hgcd_step.c', needed by 'hgcd_step.lo'.  Stop.
```

But if you have a system `gcc`/`g++` you won't need to add `spack add gcc` to your environment to install another one.

**Comment by LDAmorim** [comment]
Hi @ax3l ,

That's a very good point, I could just update the ubunto `gcc`version and use that one instead of having spack re-build it. I'll try it out asap.

Thanks!

**Comment by LDAmorim** [comment]
The solution of using environments seems to work well, so I will close this issue.
Thank you @ax3l and @scheibelp for all the help!

**Comment by ax3l** [comment]
Awesome, thanks for closing the loop! :)
