### ISSUE TITLE
Exit with nonzero status if `spack install` fails

### ISSUE THREAD

**Issue by christoph-conrads** [LLNL/spack#24521]
Have `spack install` exit with a nonzero status (e.g., `sys.exit(1)` or `exit(EXIT_FAILURE)`) if one or more packages could not be built. Spack 0.16.2 does not do this.

### Rationale

1. If some packages could not be installed, this is an error and consequently the exit status should not be zero.
2. Always returning zero breaks any attempt at scripting.

### Description

There is no alternative to setting the exit status because
* shells have built-in features working the exit status of a program,
* processes are given the exit code of their child processes (e.g., by `wait()`), and
* continuous integration environments check for nonzero exit statuses to detect pipeline failures.

Parsing standard error is error prone and unreliable.

### Additional information

I am running Spack builds in a container in a continuous integration (CI) environment and everything always succeeds when `spack install` actually fails to install half of the packages.

### General information

- [x] I have run `spack --version` and reported the version of Spack
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by christoph-conrads** [comment]
> ### Additional information
> 
> I am running Spack builds in a container in a continuous integration (CI) environment and everything always succeeds when spack install actually fails to install half of the packages.

Actually, this is is a bug report and not a feature request.

**Comment by adamjstewart** [comment]
@tldahlgren didn't you recently fix this in develop? Maybe we just need to backport it to a 0.16.3 release?

**Comment by christoph-conrads** [comment]
> @tldahlgren didn't you recently fix this in develop? Maybe we just need to backport it to a 0.16.3 release?

If it makes your life easier: using the `develop` branch is an option for me.

**Comment by alalazo** [comment]
@christoph-conrads Did you try the:
```console
$ spack install --fail-fast ...
```
option? I think it should do what you want.

**Comment by christoph-conrads** [comment]
> @christoph-conrads Did you try the:
> 
> ```
> $ spack install --fail-fast ...
> ```
> 
> option? I think it should do what you want.

It does what I want it to do and it found the bug fixed by PR #24564.

**Comment by christoph-conrads** [comment]
> @tldahlgren didn't you recently fix this in develop? Maybe we just need to backport it to a 0.16.3 release?

`spack install` has a non-zero exit status on build failure now (tested with commit 406117148d3e416e518eb911b0768716b00245d6).
