### ISSUE TITLE
Installation issue: Packages with Python dependency fail to build if two interpreters present

### ISSUE THREAD

**Issue by christoph-conrads** [LLNL/spack#24527]
A dummy CMake package with a Python dependency may fail to build on Debian 9 / Devuan Ascii when there is a Python3 interpreter installed on the host and a Spack-built Python3 interpreter. When CMake is run, the host interpreter is called and crashes.

### Steps to reproduce the issue

The issue can be reproduced in a Linux container. The first step shows how to set up the container, the second step sets up a dummy package and builds it successfully with Spack. The third step shows how to break the build.

#### Step 1: Container setup

LXD commands for creating a new Debian 9 LXD container with a user called john:
```sh
#!/bin/bash

set -e
set -u

lxc launch images:debian/9 d9
lxc exec d9 -- apt-get update
lxc exec d9 -- apt-get install -y \
    build-essential \
    bzip2 \
    curl \
    git \
    gzip \
    patch \
    python3 \
    python3-dev \
    tar \
    unzip \
    xz-utils \
    zstd \
    cmake \
    libssl-dev \
    pkg-config \
    sudo
lxc exec d9 -- adduser --disabled-password --gecos '' john
```

#### Step 2: Package Build

Login with `lxc exec d9 -- login -f john` and execute these Spack commands (or pipe them into Bash with `lxc exec d9 -- sudo --login --user john -- /bin/bash <commands.txt`):
```sh
#!/bin/bash

set -e
set -u

cd
if [ ! -d py3-clash/ ]; then
    mkdir py3-clash
    cd py3-clash/
    cat >CMakeLists.txt <<EOF
cmake_minimum_required(VERSION 3.7.2)
project(py3-cmake-spack-clash VERSION 1.0 LANGUAGES C)
find_package(PythonInterp 3.5.3 REQUIRED)
install(CODE "message(\"dummy installation\")")
EOF
fi

cd
if [ ! -d spack/ ]; then
    git clone --depth=1 -- 'https://github.com/spack/spack.git'
    mkdir ~/spack/var/spack/repos/builtin/packages/py3-clash/
    cat >~/spack/var/spack/repos/builtin/packages/py3-clash/package.py <<EOF
from spack import *

class Py3Clash(CMakePackage):
    git      = 'git@gitlab.com:example/py3-cmake-spack-clash.git'
    version('master', branch='master')
    depends_on('cmake')
    depends_on('python')
EOF
fi

cd
. ~/spack/share/spack/setup-env.sh 
spack external find
cd py3-clash/
spack dev-build py3-clash@master
```
Spack complains that nothing was installed but this does not matter.

#### Step 3: Breaking the Build

The error message by the Python interpreter itself is usually suppressed by the CMake `FindPythonInterpreter` module but I patched it to show the error:
```diff
--- FindPythonInterp.cmake	2021-06-25 17:02:00.769962740 +0000
+++ /usr/share/cmake-3.7/Modules/FindPythonInterp.cmake	2021-06-25 17:02:32.310635796 +0000
@@ -106,8 +106,7 @@
     execute_process(COMMAND "${PYTHON_EXECUTABLE}" -c
                             "import sys; sys.stdout.write(';'.join([str(x) for x in sys.version_info[:3]]))"
                     OUTPUT_VARIABLE _VERSION
-                    RESULT_VARIABLE _PYTHON_VERSION_RESULT
-                    ERROR_QUIET)
+                    RESULT_VARIABLE _PYTHON_VERSION_RESULT)
     if(NOT _PYTHON_VERSION_RESULT)
         string(REPLACE ";" "." PYTHON_VERSION_STRING "${_VERSION}")
         list(GET _VERSION 0 PYTHON_VERSION_MAJOR)
```

```console
$ spack dev-build py3-clash ^python@3.5.4:
[...]
2 errors found in build log:
     4     -- Check for working C compiler: /home/john/spack/lib/spack/env/gcc/
           gcc
     5     -- Check for working C compiler: /home/john/spack/lib/spack/env/gcc/
           gcc -- works
     6     -- Detecting C compiler ABI info
     7     -- Detecting C compiler ABI info - done
     8     -- Detecting C compile features
     9     -- Detecting C compile features - done
  >> 10    Fatal Python error: Py_Initialize: Unable to get the locale encoding
     11    ImportError: No module named 'encodings'
     12    
     13    Current thread 0x00007f56f7e3c700 (most recent call first):
  >> 14    CMake Error at /usr/share/cmake-3.7/Modules/FindPackageHandleStandar
           dArgs.cmake:138 (message):
     15      Could NOT find PythonInterp: Found unsuitable version "1.4", but r
           equired
     16      is at least "3.5.3" (found /usr/bin/python3.5)
     17    Call Stack (most recent call first):
     18      /usr/share/cmake-3.7/Modules/FindPackageHandleStandardArgs.cmake:3
           76 (_FPHSA_FAILURE_MESSAGE)
     19      /usr/share/cmake-3.7/Modules/FindPythonInterp.cmake:150 (FIND_PACK
           AGE_HANDLE_STANDARD_ARGS)
     20      CMakeLists.txt:3 (find_package)
```
The `CMakeCache.txt` makes it obvious that the host Python interpreter was called:
```
PYTHON_EXECUTABLE:FILEPATH=/usr/bin/python3.5
```

### Information on your system

```console
john@d9:~/spack$ spack debug report
* **Spack:** 0.16.1
* **Python:** 3.5.3
* **Platform:** linux-debian9-haswell
* **Concretizer:** original
john@d9:~/spack$ git rev-parse HEAD
843c38e69e8b17b5f7585748e9b7ba4a316bb986
```

### Additional information

* `spack-configure-args.txt` is empty
* [spack-build-out.txt](https://github.com/spack/spack/files/6717803/spack-build-out.txt)
* [spack-build-01-cmake-out.txt](https://github.com/spack/spack/files/6717801/spack-build-01-cmake-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/6717802/spack-build-env.txt)
* [CMakeCache.txt](https://github.com/spack/spack/files/6717873/CMakeCache.txt)

querying @adamjstewart @skosukhin because this seems to be Python-related

This issue is very similar to #23436 except that the dummy package is explicitly listing its Python dependency:
> When trying to build zfp on my system, I encountered a bunch of odd python errors. Upon deeper investigation, it appears that the CMake configuration tool zfp was using found/decided to use the system installed python instead of the spack installed python. Looking at the zfp recipe, it had dependencies on py-numpy and py-cython, but no explicit dependency on python.

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate (found #23436 but the fix did not work)

### Remarks

OP ran into the issue when working around #24526.

**Comment by adamjstewart** [comment]
I'm not much of a CMake expert, but I think you need to help CMake find the Python executable by adding `-DPYTHON_EXECUTABLE=/path/to/python`. I don't think there's anything that Spack can do to fix this. Arguably, it's a bug in the CMake Python detection script that it doesn't choose the first executable in the PATH.

**Comment by christoph-conrads** [comment]
> Arguably, it's a bug in the CMake Python detection script that it doesn't choose the first executable in the PATH.

Yes, I think so, too. The dummy package relies on the module [`FindPythonInterpreter.cmake`](https://gitlab.kitware.com/cmake/cmake/-/blob/v3.7.2/Modules/FindPythonInterp.cmake) and requires at least Python version 3.5.3:
```cmake
find_package(PythonInterp 3.5.3 REQUIRED)
```
Thus, the `PythonInterp` module begins searching for a Python interpreter whose executable is called either `python3.5` or `python3` in [line 67](https://gitlab.kitware.com/cmake/cmake/-/blob/v3.7.2/Modules/FindPythonInterp.cmake#L67) (note the semicolon separates items in a list):
```cmake
find_program(PYTHON_EXECUTABLE NAMES python3.5;python3)
```
Note that `python3.5` is the first name to be listed. Consequently, `find_program` searches for an executable called `python3.5` first and `python3` afterwards. This is wrong here because the unsuited host interpreter is found and it is wrong according to the [`find_program` documentation](https://cmake.org/cmake/help/v3.7/command/find_program.html) (emphasis mine):
> ##### `NAMES`
> Specify one or more possible names for the program.
> 
> When using this to specify names with and without a version suffix, **we recommend specifying the unversioned name first so that locally-built packages can be found before those provided by distributions**.


#### Work-arounds:
* Use CMake 3.12+ and its `FindPython3` module: `find_package(Python3 3.5.3 REQUIRED)`
* Keep using `FindPythonInterp` and check the version manually (see below).

```cmake
# the `FindPythonInterp` module contains a list of Python versions; make sure recent releases can be detected
set(Python_ADDITIONAL_VERSIONS 3.9 3.8)
find_package(PythonInterp 3 REQUIRED)
IF(PYTHON_VERSION_STRING VERSION_LESS 3.5.3)
    message(FATAL_ERROR "Python 3.5.3 required, Python ${PYTHON_VERSION_STRING} found")
endif()
