### ISSUE TITLE
mpi not shown as a package with spack.repo.all_package_names

### ISSUE THREAD

**Issue by vsoch** [LLNL/spack#24552]
I'm not sure if this is a bug or the package is intentionally left out, but I noticed that mpi doesn't come through in listing packages via spack.repo.all_package.names:

```python
all_packages = spack.repo.all_package_names(include_virtuals=True)
for package in os.listdir('/home/vanessa/Desktop/Code/spack/var/spack/repos/builtin/packages/'):
   ...:     if package not in all_packages:
   ...:         print(package)
   ...:
mpi
```
It's definitely a folder (as shown above) and it doesn't show up whether I do include_virtuals as True or not. What am I missing?

The package is defined as virtual=True, but I guess my thinking is that include_virtuals=True would have it show up.

**Comment by tgamblin** [comment]
Something is definitely screwy here as it seems like this function depends on how it's called the first time after clearing the cache.

```console
(spackle):spack> cat ~/test.py
#!/usr/bin/env spack-python
import spack.repo
print("mpi" in spack.repo.all_package_names(include_virtuals=False))
print("mpi" in spack.repo.all_package_names(include_virtuals=True))
(spackle):spack> spack clean -m && ~/test.py
==> Removing cached information on repositories
False
False
```

```console
(spackle):spack> cat ~/test.py
#!/usr/bin/env spack-python
import spack.repo
print("mpi" in spack.repo.all_package_names(include_virtuals=True))
print("mpi" in spack.repo.all_package_names(include_virtuals=False))
(spackle):spack> spack clean -m && ~/test.py
==> Removing cached information on repositories
True
True
```

On the bright side, `spack list -v` and `spack list` seem to work -- and that's the only place this is currently used.  I don't fully understand the behavior and we should probably fix it, though.

@becker33?

**Comment by alalazo** [comment]
@tgamblin Looking into this. It doesn't seem to me clearing the cache is required to reproduce:
```console
$ spack python -c 'import spack.repo;print("mpi" in spack.repo.all_package_names(include_virtuals=False));print("mpi" in spack.repo.all_package_names(include_virtuals=True))'
False
False
$ spack python -c 'import spack.repo;print("mpi" in spack.repo.all_package_names(include_virtuals=True));print("mpi" in spack.repo.all_package_names(include_virtuals=False))'
True
True
```

**Comment by alalazo** [comment]
Explanation is kind of simple:
https://github.com/spack/spack/blob/acb8ab338d3df901ec430daa073eff7c1a845b9b/lib/spack/spack/repo.py#L547-L555

We cache the result of the first call and reuse it in the second call. Bug introduced in #15702 since before that PR there was no argument to `all_package_names`.

**Comment by alalazo** [comment]
I'll submit a PR with a bugfix asap.
