### ISSUE TITLE
Installation issue: opencv

### ISSUE THREAD

**Issue by gmfricke** [LLNL/spack#24551]
The +apps variant sets -DBUILD_opencv_apps:BOOL=ON but no apps are output. Specifically, opencv_traincascde isn't built.

```console
$ spack install opencv@3.4.12 +apps
```

### Information on your system

* **Spack:** 0.16.2-3218-b0ceeaa
* **Python:** 3.6.8
* **Platform:** linux-centos7-haswell
* **Concretizer:** original

### Additional information

Build thinks it succeeded so the stage directory is not kept. The expected open_cv apps are simply absent. 

@adamjstewart  
@bvanessen

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
I started digging into this. It looks like this particular application is disabled unless `+core+imgproc+objdetect+imgcodecs+highgui+calib3d+features2d`. My internet is currently down, but once it comes back I'll try to modify the package to add a variant for each possible application and make sure it has the right conflicts.

**Comment by gmfricke** [comment]
@adamjstewart Thanks so much. That worked. The variant calib3d required me to add +flann though.

**Comment by adamjstewart** [comment]
Yes, that's by design. If you switch to the new concretizer, it will automatically enable flann for you. The old concretizer doesn't understand conflicts.
