### ISSUE TITLE
Make "vermin" CI output more informative

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#24550]
Spack run "vermin" to determine which Python versions each source file supports. The respective CI output is not very informative:
- It outputs version bounds for all of Spack's Python files. There are many, and almost always, almost all of them are fine. The output would be easier to examine if only the failures were output, or if the failures were either highlighted or repeated at the bottom. The current output says e.g. "minimum is Python 3.5, expected Python 2.6, this is a failure", but it doesn't say which source file is causing the problem.
- It doesn't output line numbers for failing source files. This would be quite convenient to have.

**Comment by adamjstewart** [comment]
@netromdk is this possible to do in vermin or would someone have to submit a PR to add these features?

**Comment by netromdk** [comment]
I've recently implemented a "show only violations", or linting, mode that requires one or two `--target` arguments. More information [here](https://github.com/netromdk/vermin#linting-showing-only-target-versions-violations).

In addition, there are 4 levels of verbosity. 1+ shows filenames. 3+ shows line numbers.

A combination of this should be what you're seeking.

**Comment by alalazo** [comment]
@netromdk Thanks for the feedback. I opened an issue with a suggestion for further improving the `--violations` option. Let me know if that makes sense to you.

**Comment by netromdk** [comment]
Thanks for the good suggestion in https://github.com/netromdk/vermin/issues/74. The fix has been released in [v1.2.1](https://github.com/netromdk/vermin/releases/tag/v1.2.1).

**Comment by alalazo** [comment]
@netromdk Thanks a lot for the prompt response!
