### ISSUE TITLE
doxygen@1.9.1 infinite build on GCC 7.5.0, Ubuntu 18.04

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#24591]
`doxygen@1.9.1` build never finishes using:
* `GCC 7.5.0`
* `Ubuntu 18.04`
* `spack@develop` (b87d9c29c10bab0b110f2c543105f2957f4e8099 from `Mon Jun 28 22:07:24 2021 +0200`)

Concrete spec: [doxygen.spec.yaml.txt](https://github.com/spack/spack/files/6734535/doxygen.spec.yaml.txt)

```
$> spack install -f ./doxygen.spec.yaml
...
==> Installing doxygen-1.9.1-3fv2srkhm7p3qbegf764owu5fr4psiin
==> Applied patch /spack/var/spack/repos/builtin/packages/doxygen/gcc-partial-inlining-bug.patch
==> Ran patch() for doxygen
==> doxygen: Executing phase: 'cmake'
==> doxygen: Executing phase: 'build'
... forever
```

@chuckatkins Do you know how to fix this? I saw you fixed something like this in https://github.com/spack/spack/pull/21614

**Comment by Billae** [comment]
I have the same issue with the same configuration (doxygen1.9.1 on gcc7.5 & ubuntu 18).
Is there some  fix to do ?

**Comment by Billae** [comment]
update: 
I try to explicitely apply the patch you cite in the MR but it still loop in the build phase
