### ISSUE TITLE
Please upgrade packaging of uriparser from 0.9.3 to 0.9.5 to fix bugs

### ISSUE THREAD

**Issue by hartwork** [LLNL/spack#24630]
### Steps to reproduce the issue

Hi! uriparser packaging is at version 0.9.3 while upstream is at version 0.9.5 which among other things includes [an important bugfix](https://github.com/uriparser/uriparser/blob/d96e1025e98cf99de7dbdea593160a2f6c078b6f/ChangeLog#L18-L21). It would be great to have packaging updated to the latest release to get that fix out to Spack users. Thank you! :pray: 

### Error Message

n/a

### Additional information

- [ ] ~I have run `spack debug report` and reported the version of Spack/Python/Platform~
- [x] I have searched the issues of this repo and believe this is not a duplicate
- [ ] ~I have run the failing commands in debug mode and reported the output~

**Comment by adamjstewart** [comment]
Hi @hartwork, our `uriparser` package doesn't yet have an official maintainer, so it's up to community contributions to update the package. Would you like to submit a PR to do this? Should be a one-line change, just run `spack checksum uriparser` to print the line to add, and `spack edit uriparser` to open the file to add it to.

**Comment by hartwork** [comment]
@adamjstewart I have created PR #24688 just now

**Comment by hartwork** [comment]
PS: @adamjstewart does Spack have an FAQ somewhere?  Right now I'm wondering:
- how to list all dependencies of a package, including indirect ones
- how Spack views its differences to Gentoo, since it feels like a lot like "Gentoo in users space" to me

**Comment by hartwork** [comment]
> * how to list all dependencies of a package, including indirect ones

I found `spack graph` now:

```console
# spack graph uriparser
o  uriparser
|\
o |  googletest
|/
o  cmake
|\
o |  openssl
|\ \
o | |  zlib
 / /
o |  perl
|\ \
o | |  gdbm
o | |  readline
| |/
|/| 
o |  ncurses
o |  pkgconf
 /
o  berkeley-db
```

> * how Spack views its differences to Gentoo, since it feels like a lot like "Gentoo in users space" to me

Found a short answer in https://spack.io/files/spack-rd100-2019-final.pdf now.

**Comment by adamjstewart** [comment]
> does Spack have an FAQ somewhere?

Not an FAQ per say, but we have pretty extensive documentation. The "Basic Usage" guide is probably what you're looking for: https://spack.readthedocs.io/en/latest/basic_usage.html

> how to list all dependencies of a package, including indirect ones

`spack graph` works for this, but `spack spec` is more commonly used since it also shows you what Spack will actually install when you run `spack install`.

> how Spack views its differences to Gentoo, since it feels like a lot like "Gentoo in users space" to me

@tgamblin could answer this better than me, but Spack borrows a lot of ideas from other package managers like Gentoo, Nix, and Homebrew. Originally Spack was specifically targeted towards supercomputers, but now we run on most platforms.
