### ISSUE TITLE
Building compiler on AMD server and using on Intel server causes illegal instruction errors.

### ISSUE THREAD

**Issue by gartung** [LLNL/spack#2465]
I know this doesn't come up on supercomputers because the architecture of all of the nodes is identical. However I ran into an odd problem building gcc on a build server and using it on another machine. The relocated compiler worked as long as I disabled the binutils and gold options. That was a few merges from develop ago. Now when I try to compile with the relocated compiler I get error messages about illegal instructions. As near as I can tell from googling the error message, the compiler or its dependent packages have been optimized to use instructions only found on the build server AMD processor. I thought I should point this out in case you are installing the compiler to an nfs mount and the compiler might be run on machines with different architectures.

**Comment by gartung** [comment]
This may be a case of ccache messing things up again. This is the compilers detected on the build server which gcc@4.9.3 was built with
compilers:
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: scientificfermi6
    paths:
      cc: /usr/lib64/ccache/gcc
      cxx: /usr/lib64/ccache/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    spec: gcc@4.4.7
- compiler:
    environment: {}
    extra_rpaths: []
    flags: {}
    modules: []
    operating_system: scientificfermi6
    paths:
      cc: /usr/lib64/ccache/gcc34
      cxx: /usr/lib64/ccache/g++34
      f77: null
      fc: null
    spec: gcc@3.4.6

**Comment by gartung** [comment]
The presence of ccache is not what effected the build. It seems  the gcc build system will optimize for the x86_64 of AMD or Intel cpus unless you change the config and/or make options. The two build scripts for relocatable gcc@4.9.3 that I have looked at use two different solutions. The first uses 'make profiledbootstrap' along with --host= and --build= config options. The second uses 'make bootstrap' with  the option --enable-stage1-checking.

**Comment by gartung** [comment]
So this seems to be caused by gmp 6.1.1 automatically using  -mtune=bdver2 on the AMD build server. I added flags to use mtune=generic since I want gcc@4.9.3 which depends on gmp to be usable on both out AMD and Intel servers.

**Comment by tgamblin** [comment]
@gartung: We do actually want to support this for hosting binary packages out on the internet, even for supercomputers.

On Linux `x86_64` systems, we don't use a very specific target string.  On the Crays we steal the one the Cray target string, which is something like `haswell`, `ivybridge`, `knl`, etc.  It is on my list to make the Linux builds more specific by querying `/proc/cpuinfo` or similar.

What do you guys think of this?  Spack would probably use this target by default (though we should probably make it customizable via `packages.yaml`).  This would allow packages to optimize for specific architectures if they want to, probably by adding more specific compiler flags.  It would also mean that you wouldn't be able to recycle a `haswell` build on an `ivybridge`, so you might need more build servers.  I talked to some folks at CHEP about this and there was interest in using better compiler flags, but it sounded like the current state of things is that you mostly build for vanilla `x86_64`.

We could continue to offer `x86_64` binaries and allow them to be used in builds even if the root package has a more specific architecture.

**Comment by gartung** [comment]
@tgamblin -mtune=generic seems to be the safest options when building gcc and its dependencies.

**Comment by gartung** [comment]
@tgamblin The HEP computing grid is a very heterogeneous collection of AMD and Intel servers so we optimize to the lowest common architecture. For online data acquisition systems where speed is essential we compile to the system and there is even work on using GPU accelerators.

**Comment by tgamblin** [comment]
@gartung: ok that's useful.  I think we could do something smart to allow either generic or specific binaries on a system like that, depending on what the user wants.
