### ISSUE TITLE
Installation issue: med broken by hdf5 update

### ISSUE THREAD

**Issue by christoph-conrads** [LLNL/spack#24671]
All med versions are broken by commit cc20dbf645d32a45ce6b7ed848c6f25eaf42e350. med 4.0.0 and med 4.1.0 depend on hdf5 1.10.7; med 3.2.0 depends on hdf5 1.8.22.

### Steps to reproduce the issue

(CMake constraint: the system has only CMake 3.7.2 and HDF5 requires CMake 3.12+).

```console
$ spack install med ^cmake@3.12.4
[...]
==> Installing med-4.0.0-oamvn6z2gfevbfx52jid34x632x5zxak
==> No binary for med-4.0.0-oamvn6z2gfevbfx52jid34x632x5zxak found: installing from source
==> Using cached archive: /home/john/spack/var/spack/cache/_source-cache/archive/a4/a474e90b5882ce69c5e9f66f6359c53b8b73eb448c5f631fa96e8cd2c14df004.tar.gz
==> No patches needed for med
==> med: Executing phase: 'cmake'
==> Error: ProcessError: Command exited with status 1:
[...]

1 error found in build log:
     15    -- Detecting CXX compile features
     16    -- Detecting CXX compile features - done
     17    -- No Fortran support
     18    -- Check for HDF5 ...
     19    -- Found HDF5 in CONFIG mode!
     20    -- Found HDF5 version 1.10.7 -- parallel flag is set to ON
  >> 21    CMake Error at config/cmake_files/FindMedfileHDF5.cmake:118 (GET_PRO
           PERTY):
     22      GET_PROPERTY could not find TARGET hdf5.  Perhaps it has not yet b
           een
     23      created.
     24    Call Stack (most recent call first):
     25      config/cmake_files/medMacros.cmake:396 (FIND_PACKAGE)
     26      CMakeLists.txt:101 (MED_FIND_HDF5)
     27    
```

Ignoring line numbers, the error message is the same for all versions.

### Information on your system

```console
john@da:~/spack$ spack debug report
* **Spack:** 0.16.2-3346-406117148d
* **Python:** 3.5.3
* **Platform:** linux-devuan-haswell
* **Concretizer:** original
```

### Additional information

Log files for med 4.0.0 with hdf5 1.10.7:
* [spack-build-01-cmake-out.txt](https://github.com/spack/spack/files/6755637/spack-build-01-cmake-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/6755638/spack-build-env.txt)
* [spack-build-out.txt](https://github.com/spack/spack/files/6755639/spack-build-out.txt)
* [spack-configure-args.txt](https://github.com/spack/spack/files/6755640/spack-configure-args.txt)

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers @likask
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by cessenat** [comment]
I encounter that as well.
Without MPI it goes through:
`spack install med@4.1.0+shared~mpi ^hdf5@1.10.7~mpi ^cmake@3.12.4`
Maybe @likask could help.
I mailed Adrien Bruneton who authored config/cmake_files/FindMedfileHDF5.cmake in case he could help.

**Comment by christoph-conrads** [comment]
The problem is that the HDF5 CMake target name changed from `hdf5` to `hdf5-shared`. Here is a work-around:
```diff
--- config/cmake_files/FindMedfileHDF5.cmake	2021-08-06 14:15:01.461314125 +0200
+++ FindMedfileHDF5.cmake	2021-08-06 14:14:55.893105000 +0200
@@ -122,7 +122,7 @@
       # HDF5 was compiled with MPI support
       # Unfortunately HDF5 doesn't expose its MPI configuration easily ...
       # We sniff the properties of the HDF5 target which should also be there:
-      GET_PROPERTY(_lib_lst TARGET hdf5 PROPERTY IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG)
+      GET_PROPERTY(_lib_lst TARGET hdf5-shared PROPERTY IMPORTED_LINK_INTERFACE_LIBRARIES_NOCONFIG)
       FOREACH(s ${_lib_lst})
         STRING(FIND "${s}" "mpi." _res)   # should cover WIN(?) and LINUX
         IF(_res GREATER -1)
```

**Comment by christoph-conrads** [comment]
The MED README mentions Eric Fayolle as a point of contact. I e-mailed him.
