### ISSUE TITLE
Installation issue: HDF5 macOS HDF5_IS_PARALLEL

### ISSUE THREAD

**Issue by ax3l** [LLNL/spack#24680]
### Steps to reproduce the issue

```console
$ spack install hdf5
```

Then building an MPI-parallel downstream program and checking `HDF5_PREFER_PARALLEL`

cc @lrknox @skosukhin @chuckatkins 

### Information on your system

Since I don't own a mac, I am running nightly tests to install Spack packages on macOS systems on Azure Pipelines.

Since the transition to CMake in the HDF5 package #18937, **only on macOS**, the following line:
```cmake
set(HDF5_PREFER_PARALLEL ON)
find_package(HDF5 1.8.13 COMPONENTS C)
```
still finds the Spack provided HDF5 package but does not set `HDF5_IS_PARALLEL` to true.

The same logic works well on Linux.

### General information

- [ ] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [ ] I have searched the issues of this repo and believe this is not a duplicate

**Comment by ax3l** [comment]
Hm, maybe if the HDF5 config package is picked up I need to check instead `${HDF5_PACKAGE_NAME}_ENABLE_PARALLEL` for this...

https://github.com/HDFGroup/hdf5/blob/257c8c745446ee614f92624b30cec41d8d771e05/config/cmake/hdf5-config.cmake.in#L35

**Comment by ax3l** [comment]
Uff, the HDF5 config packages only mark `major.minor` matches as compatible and even version ranges are not implemented properly....
```
       Could not find a configuration file for package "HDF5" that is compatible
         with requested version range "1.8.13...1.12".
         The following configuration files were considered but not accepted:
         ../share/cmake/hdf5/hdf5-config.cmake, version: 1.10.7
```
https://github.com/HDFGroup/hdf5/blob/hdf5-1_12_1/config/cmake/hdf5-config-version.cmake.in#L16-L20

So manual version check it is...

**Comment by christoph-conrads** [comment]
> Uff, the HDF5 config packages only mark `major.minor` matches as compatible and even version ranges are not implemented properly....
> 
> ```
>        Could not find a configuration file for package "HDF5" that is compatible
>          with requested version range "1.8.13...1.12".
>          The following configuration files were considered but not accepted:
>          ../share/cmake/hdf5/hdf5-config.cmake, version: 1.10.7
> ```

This is strange because CMake 3.20 treats missing version number components as zero, see [_Version Comparisons_](https://cmake.org/cmake/help/v3.20/command/if.html#version-comparisons):
> Component-wise integer version number comparison (version format is major[.minor[.patch[.tweak]]], omitted components are treated as zero). Any non-integer version component or non-integer trailing part of a version component effectively truncates the string at that point.

Older versions do not contain this statement but the Release Notes do not mention changes regarding version comparisons.

**Comment by ax3l** [comment]
Yes, that counterintuitive comparison is implemented in HDF5 itself:
https://github.com/HDFGroup/hdf5/blob/hdf5-1_12_1/config/cmake/hdf5-config-version.cmake.in#L16-L20

Sorry, did not provide the reference above, will edit it in.
