### ISSUE TITLE
SP 001: Common variant names

### ISSUE THREAD

**Issue by tgamblin** [LLNL/spack#247]
Proposal by @markcmiller86 

There are a number of aspects of package installation that are frequently duplicated from package to package.

In Spack parlance, these might be best considered variants. However, in some sense they are global variants as they effect many packages in the same way.

I'd like to start a list of these here and keep track of this. Here's a start. Also, would like to keep variant tags short so here we try to use just 3-character variant names.

## debug/optimized
* `+opt` means to build optimized (production) -O3, etc. (default)
* `-opt` means to build a package with (maximal) debugging features enabled (e.g. -g, -DNDEBUG, etc., maybe special profiling features enabled, etc.). Note that currently Spack automatically sets standard CMake switches to include CMAKE_BUILD_TYPE=RelWithDebInfo. That practice would be replaced with this new way of handling this as a variant (though the proposed variant in fact does not deal with the subtle RelWithDebInfo flavor)

## static/dynamic libraries
* `+dyn` means to build both dynamic and static libraries in the install point
* `-dyn` means to build only static (default)

## 32bit/64bit
* `+b64` means to build both 32 and 64 bit libraries (default)
* `-b64` means to build only 32 bit

## Interface Languages (fortran/cxx/c…)
* `+fort` means to build (all) fortran interfaces (where available) when fc compiler is specified (default)
* `+cxx` means to build C++ interfaces (where available) when cxx compiler is specified
* `+c` means to build C interfaces (default)
* `+pyth' means build python interfaces (where available) if python is also available

Note that C/CXX interface variant switches may be less relevant as typically whenever you have a C compiler, you also have a C++ compiler. The same hasn't always tended to be true for Fortran though (OS X for example) and so having that variant switch is important. OTOH, maybe specifying a fortran compiler is sufficient cause to enable fortran wherever its possible and all three of these variant switches can be argued away.

## serial/parallel
* `+par` means to build both serial and parallel variants (default)
* `-par` means to build only serial variant

In a context where the only parallelism comes from MPI, this works. In a context where there are multiple forms of parallelism (threads, mpi, etc.) it gets more complicated and `parallel` may not be the appropriate moniker. Nonetheless, there are a lot of libraries out there that are designed to work in serial and (MPI) parallel. More thought is required here.

## Libraries, Tools, Tests/Checks and Examples
* `+test` means to both build and run tests as part of installation (failing the installation if tests don't pass), default=False
* `-tools` means to NOT build/install support tools (for example, for HDF5, I don't wanna build/install support tools like h5ls on compute nodes, only for login nodes)
* `+examples` means to build/install examples

## Other switches since starting this page
* handling of -PIC, -fPIC, -qpic and variants ([already have a post in google groups about this](https://groups.google.com/forum/#!topic/spack/7brRuR0v6O4)). Its essential if the package you are building will ever be intended to be used in the creation of shared object (.so).

## Variants for dependent libraries
In my experience, there are basically two kinds of dependent libraries for a package; _required_ and _optional_. Required dependencies are already addressed by Spack and do not involve the use of variants. But, what about variants for optional dependencies? One possibility is to have a package support each such dependency as a variant. But, that seems like it could potentially get unwieldly. This is especially true if the dependency has the potential to ripple down through the dependency graph. Furthermore, with different packages possibly having different optional dependencies, a single spack command-line to build a given package could wind up getting quite long due to package-specific optional dependency variants. Is there any Spack shorthand we can develop to simplify this a bit and perhaps come up with a set of global variants that nonetheless help to specify how optional dependencies in any given package be handled?

What are the downsides of simply treating all optional dependencies as required? In other words, what if we opted to _maximize_ optional dependencies? Well, in a nutshell, its less robust; since more things are being built, there is more chance of a failure either to build or to access a given package on the network; an application linking to the desired package must link more packages into the same executable and maybe not all the packages play well together; some packages are optional because they represent experimental capability that is not fully tested and/or works in limited contexts (e.g. compilers, MPI implementations, etc.). So, there are good reasons for Spack to, by default, _minimize_ optional dependencies.

What are the downsides to minimizing optional dependencies? The key downside is that needed functionality isn't available in a given package requiring that package and possibly some portion of its dependencies to be re-built. As different users in a HPC stack install Spack is managing encounter the need for different combinations of optional dependent libraries, eventually that installation could wind up getting populated with the combinatoric expansion of all possible combinations of optional dependencies. Though Spack is designed to handle this situation, is it really an outcome we want to design towards?

Lets propose the following global variants for handling optional dependent packages
* variant('reqdep', default=False, 'Minimize dependencies. Build only with required dependent libraries')
* variant('stddep', defualt=True, 'Standard dependencies. Build with standard/common optional dependent libraries.')
* variant('alldep', default=False, 'Maximal dependencies. Build with all possible dependent libraries')

The meaning of _reqdep_ should be obvious. It means to turn off *all* optional dependent libraries and build *only* with required dependent libraries. The meaning of _stddep_ means to build the package in its _standard_ or _common_ configuration with those optional libraries the packages that the package is commonly used with. Furthermore, I am proposing this as the default. What constitutes the set of standard or common optional dependent packages can be determined on a package-specific basis. For example, the Silo library is commonly used with the HDF5 library so activation of the HDF5 dependency in Silo will occur by default but can be turned off by setting the variant '+reqdep'.

These are sort of mutually exclusive options in that setting one has implications for the others. It would be nicer to have a 3-value variant such as
* variant('optdeps', values=['off':'Minimize dependencies. Build only with required dependent libraries',
                          'std':'Standard dependencies. Build with standard/common optional dependent libraries.',
                          'all':'Maximal dependencies. Build with all possible dependent libraries']
```

**Comment by bartlettroscoe** [comment]
My first comments are about optional vs. required dependencies.

In particular, the issue with optional vs. required dependencies brings in a host of challenges.  Given that Trilinos (supported by TriBITS) has supported optional and required dependencies for a long time, we have a lot of experience on the issues that they bring up and strategies for handling them.  In particular, when you consider all of the use cases for turning on and off optional dependencies, how that impacts the upstream and downstream dependencies, and how that relates to tests, etc., you get to a pretty complex set of rules. For example:

https://tribits.org/doc/TribitsDevelopersGuide.html#tribits-dependency-handling-behaviors

While this is challenging, I suspect that this is *much* easier to manage when everything is built using the same uniform build system (i.e. TriBITS and CMake).   But I think this gets much harder to manage when you have black-box build systems for each of the packages.

our experience with Trilinos is that specific customers have a specific set of packages and dependencies that they need, and therefore, you are going to build a different a stack of software for every specific major customer on a given system (because each have specific requirements).  That is how it is done, for example, for every major Trilinos customer that I now about.  This is also the argument that I am framing in the short 2-page document here:

http://web.ornl.gov/~8vt/CSEEcosystemSustainability_CSESSP2015.pdf

(see “4) Building a compatible set of packages for a given application from source”).

Cheers,

-Ross

**Comment by BarrySmith** [comment]
We can only add comments at the end of the file? Not associated with particulaar lines of text?

So basically these are spack commands that spack will map to the appropriate options for the underlying autoconf/cmake/other tool for each package. Fine but I don't see what xSDK then has to do with them.

**Comment by BarrySmith** [comment]
xSDK has no concept of -par and never will. xSDK is for HPC, not a single process.

**Comment by BarrySmith** [comment]
We haven't worried about 32 vs 64 bit builds with xSDK. I guess the assumption is always 64 bit (again xSDK is for HPC). Since xSDK already has huge complexity I vote that xSDK just be 64 bit and eliminate this unneeded extra dependency. Of course spack is free to deal with 32 and 64 if you like, it just won't apply to xSDK packages.

**Comment by tgamblin** [comment]
@BarrySmith: There are component packages in xSDK that can build w/o MPI (right?).  Mark's proposal is a bit more broad than just xSDK -- it's to enforce consistency across the different package in Spack.  So while the xSDK meta-package Mark is proposing would always use MPI, it might have to add `depends_on('sub-package +mpi')` to enforce that when built as part of xSDK, that package needs the `+mpi` option turned on.

We're partly discussing this because Lois wants the xSDK parameters exposed in Spack.  It's useful to know that 64-bit/32-bit and `-par` wouldn't matter, but  I guess a more interesting question is what variants are missing from Mark's proposal?

**Comment by tgamblin** [comment]
Another thing to consider (and we'd need a feature for this) -- policies for propagating variants through the stack.  If one package builds with +openmp+cuda, does that imply something for how its dependencies need to be built if they support those things?  What's the policy?

There is discussion here of some of the issues w.r.t. specifying this stuff in a non-combinatorial way using  sensible default policies: https://groups.google.com/forum/#!topic/spack/a4-G7IrXJ0E.

**Comment by bartlettroscoe** [comment]
For xSDK, non-MPI builds don't matter but for Trilinos, there are packages that have very liitle to do with MPI so it seems silly to require MPI if all a users wants is these.  But I don't think that would apply the the Spack "Trilinos" package.

As for dependencies, it would be a mess if you exposed all of the Trilinos enables/disables through something like Spack.  I have no idea of how you would handle all the combinations of what users need from Trilinos using something like Spack.  Therefore, I don't see Spack as a general purpose delivery mechanism for Trilinos.  But as a delivery mechanism for certain specific customers and use cases (like the xSDK), I see the value of Spack.

**Comment by lee218llnl** [comment]
There may be cases where you don’t want +openmp to trickle down. If you application is using all the cores via OpenMP already, then you may not want a linked-in library to launch additional threads.

**Comment by bartlettroscoe** [comment]
A document like this proposal would like be better managed as a Google Doc, IMHO.  That way, people can add comments right in the document and are easy to find and there is history stored for changes to the text.  GitHub does not store history for changes in the description for a GitHub Issue (or if it does, I can' find the history for such changes).  Now Trac does store and show changes to the description field so using a ticket/issue for this purpose makes more sense with Trac.

I will also comment that using the GitHub wiki to log meetings is likely not a great idea.  Just look at how it clutters up the "pages" wiki drop-down.  It is likely better to use Google Docs for such meetings, IMHO.  The GitHub wiki, IMHO, should be reserved for project-specific info that is too much for the README.md file or is a hassle to deal with in a different website (even an GitHub IO website).

**Comment by BarrySmith** [comment]
Roscoe wrote: For xSDK, non-MPI builds don't matter but for Trilinos, there are packages that have very liitle to do with MPI so it seems silly to require MPI if all a users wants is these.

Sure, no one is saying that individial packages MUST require MPI. Only that that xSDK does not prescribe that ALL packages must support a no-MPI mode. So some xSDK packages simply won't build with a -par option.

**Comment by BarrySmith** [comment]
Todd wrote: We're partly discussing this because Lois wants the xSDK parameters exposed in Spack. It's useful to know that 64-bit/32-bit and -par wouldn't matter, but I guess a more interesting question is what variants are missing from Mark's proposal?

Look at the document: https://docs.google.com/document/d/18028D6nsuhIrCvJnX6c07r8m_Np4SH-aGXMX4svMs1w/edit#heading=h.3hcywq83w3x0

Number 7, 8, and the --with-PACKAGENAME option in 10. So presumably if one wants to build PETSc with hypre you would have a spack option the user would pass when requesting PETSc indicating that hypre is a dependency and spack would then automatically install hypre and when it installs PETSc after that it would pass the appropriate --with-hypre-dir (or --with-hypre-lib and --with-hypre-include) to the PETSc configure script.

**Comment by trws** [comment]
I'll just leave this here... [Gentoo use flag index](https://www.gentoo.org/support/use-flags/)

Having standardized dependency arity options seems like a good idea (take over for vim/texlive's small, medium, huge, utterly unreasonable, etc.), but what is "standard" may be partially user and state specific.  For example, a package that can build either a QT or a GTK interface can have a radically different dependency burden depending on which, if either, of those is currently available.  Having a way to set variants globally such that they're activated whenever found, see the global use flags and USE environment variable as examples from gentoo, can help with this especially when variants can be marked as optional conditionally on the presence of other variants.

**Comment by tgamblin** [comment]
Ok, thanks everyone for the feedback here.  I'm closing this and moving the document to Google Docs:

https://docs.google.com/document/d/1Ndz4jOsZX-wxu4_ZoMlUAq0MnqDLWQ_bOQnkCgcvIQA/edit#

People should now be able to comment on Mark's proposal more easily.  I have tried to summarize some of the feedback here in my comments on Google Docs to start the discussion.  We'll update the original wiki proposal after iterating on the Google Doc, since that seems to be more natural for IDEAS folks.
