### ISSUE TITLE
Specify build directory for a package marked for development

### ISSUE THREAD

**Issue by tjfulle** [LLNL/spack#24758]
If I

```console
spack develop -p $SRC_DIR baz@main +foo
spack concretize -f
spack install
```

The build artifacts will be put directly in `$SRC_DIR`.  Eg,

```console
$ ls $SRC_DIR/spack-*
spack-build-env.txt    spack-build-fvndqrb/
spack-build-out.txt    spack-configure-args.txt
```

If I later 

```console
spack install baz@main ~foo
spack develop -p $SRC_DIR baz@main ~foo
spack concretize -f
spack install baz@main ~foo
```

It will overwrite the various `spack-build-*` files for the `+foo` variant.

A build root argument to `spack develop` would alleviate this issue:

```console
spack develop -h
...
-b BUILD_ROOT, --build-root BUILD_ROOT
        Where to build package
```

The following would be the desired result:

```console
$ spack install baz@main ~foo
$ spack install baz@main +foo
$ spack develop -p $SRC_DIR -b /var/tmp/baz_foo baz@main +foo
$ spack develop -p $SRC_DIR -b /var/tmp/baz_nofoo baz@main ~foo
$ spack concretize -f
$ spack install baz@main ~foo
$ spack install baz@main +foo
$ ls /var/tmp/baz_foo/spack-*
spack-build-env.txt    spack-build-fvndqrb/
spack-build-out.txt    spack-configure-args.txt
$ ls /var/tmp/baz_nofoo/spack-*
spack-build-env.txt    spack-build-xzqe4rn/
spack-build-out.txt    spack-configure-args.txt
```

**Comment by tjfulle** [comment]
Other advantages:

- I won't have to ignore the various `spack-build-*` files generated by spack in my vcs
- Some CMake packages will not build with Ninja if the build directory is a subdirectory of the source directory (I'm looking at you Trilinos...)

As an alternative, don't put build artifacts for each spec directly in the source directory, but in a subdirectory `spack-develop-<hash>` so that build artifacts for multiple specs are isolated.  This does not alleviate the two problems noted above.

**Comment by psakievich** [comment]
@tjfulle can we close this? This feature has been implemented. I think it needs to be improved but also the build artifacts are no longer put in the src directory which was the alternative solution proposed.

**Comment by tjfulle** [comment]
@psakievich - when was the change made?  But yes, feel free to close

**Comment by psakievich** [comment]
#39606 and #41373
