### ISSUE TITLE
Spack load But not load compiler environment

### ISSUE THREAD

**Issue by Bitllion** [LLNL/spack#24769]
I have a app that is not compiled with spack, but is installed and managed with spack.Before using it, you need INTEL2018 under source.
So,after source INTEL2018, spack compiler find finds and adds the corresponding compiler.Then I wrote an installation script like this：
```
from spack import *
class Gromacs(Package):
    homepage = "https://www.example.com"
    url      = "file:///home/spack_local_mirror/gromacs/gromacs-2018.4.tgz"
    version('2018.4', sha256='6d0932f10c6d40a83094010a4a9e2caebc518685f43979ce084ef365151ccd33')
    def install(self, spec, prefix):
        install_tree(".",prefix)
```
And run `spack install gromacs@2018.4%intel@18.0.1`.
The installation is easy.
Reopen a terminal and run `spack load  gromacs@2018.4%intel@18.0.1`.
But when I tested it,example try `gmx_mpi --version`  reported that there were no library files,need to load INTEL2018 again!
I try to check the `PATH` variable，obviously, there are only environment variables for GROMACS, not intel2018.

**Comment by alalazo** [comment]
In case of a custom app like this one you likely need to code a custom:
```python
def setup_run_environment(self, env):
    ...
```
too, to setup your environment correctly.
