### ISSUE TITLE
Installation issue: boost

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#24845]
### Steps to reproduce the issue

```console
$ spack install boost
...
A C++11 capable compiler is required for building the B2 engine.
Toolset 'gcc' does not appear to support C++11.

> g++ -x c++ -std=c++11  check_cxx11.cpp
cc1plus: error: unrecognized command line option "-std=c++11"
```

### Information on your system

* **Spack:** 0.16.2-3480-e0017a6666
* **Python:** 2.6.9
* **Platform:** cray-suse_linux11-bulldozer
* **Concretizer:** original

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/6804413/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/6804414/spack-build-env.txt)

@hainest 

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Boost seems to install with the system GCC 5.3.0, but fails to install with my Spack-installed GCC 5.5.0.

**Comment by hainest** [comment]
@adamjstewart Does the spack-installed gcc support the `-std=c++11` flag? I've sometimes found that spack-installed compilers behave differently from those provided by a system package.

**Comment by adamjstewart** [comment]
How do I test this? (I'm a Python person, not a C++ person 😄)

**Comment by hainest** [comment]
$ echo "int main(){}" > test.cpp
    $ /your/spack/g++-5.5.0 -std=c++11 test.cpp

**Comment by adamjstewart** [comment]
@hainest yes that executes successfully. Many of my other C++ packages are building correctly with this compiler, so I don't think it's an issue with the compiler.

**Comment by hainest** [comment]
The b2 check for C++11 functionality is https://github.com/boostorg/build/blob/develop/src/engine/check_cxx11.cpp. What does your compiler say when trying to build that?

**Comment by adamjstewart** [comment]
Both compiling and running `a.out` show no error messages.

This is on a Cray system. There may be some slight difference between the front-end and back-end nodes that could cause a discrepancy.

**Comment by hainest** [comment]
Well, that's.. neat. I'm assuming you are building Boost and this test on the same login/compute node?

I guess the next thing to try is running the build script for b2 directly. Can you hop into the boost install and run src/engine/build.sh?

**Comment by mwkrentel** [comment]
@adamjstewart Could you try this experiment for me?

The boost `package.py` file has a conditional patch for cray platform.
Could you comment this out and retry.

```
  # Fix the bootstrap/bjam build for Cray
  patch('bootstrap-path.patch', when='@1.39.0: platform=cray')
```

The patch removes the spack env wrapper for the compiler on Cray.
(Just for building bjam, not in general for compiling boost libraries.)
This was necessary for older Cray where FE != BE and BE compiled code
(eg, bjam) would crash on FE.  See #10295

I'm hoping to rule this out.  But if that is the problem, then I'm
seriously annoyed.

Btw, is there some reason to use gcc 5.x?
Could you try it with a more recent gcc 8.x or 9.x?

**Comment by adamjstewart** [comment]
Yes, let me try removing that patch.

> Btw, is there some reason to use gcc 5.x? Could you try it with a more recent gcc 8.x or 9.x?

Unfortunately I'm stuck on GCC 5.x due to CUDA 9.1 which can't be upgraded.

**Comment by adamjstewart** [comment]
> I'm hoping to rule this out. But if that is the problem, then I'm seriously annoyed.

Well, prepare to be seriously annoyed. Removing that patch allows me to build boost on the compute node (probably on the login node too).

**Comment by mwkrentel** [comment]
Grrr, that's too bad.  I know that some form of that patch is
necessary for what I'll call "old-style Cray", ie, lots of modules,
PrgEnv, FE != BE, static binaries, etc.  "New-style Cray" is vendor
Cray, but it builds more like standard Linux with compatible FE and BE.

I'll see if I can reproduce this.  My main access to Cray is theta,
theta-gpu at Argonne, cori at NERSC and I think something at JLSE.
Any chance we have some machine in common?

Can you tell me more about your machine?  Does it sound closer to new
or old style Cray?  If /usr/bin/gcc is 5.3, then it sounds pretty old.
In your build environment, what modules are loaded?

And what is your compilers.yaml entry for the gcc 5.5 compiler that
fails?  (I have one last hope that it's not the bootstrap patch.)

If it's not too much trouble, I'm still interested if boost builds cleanly
with gcc 8.x or 9.x.  I suspect the answer is yes, and that would tell me
something about the problem being the -std=c++11 flag not getting
passed correctly.

**Comment by adamjstewart** [comment]
The only Cray I have access to is Blue Waters at NCSA.

I think my Cray is a mix of old and new styles. FE and BE seem to be pretty similar, but there are a lot of modules and PrgEnv. It's CNL 5 so pretty old.

> If /usr/bin/gcc is 5.3, then it sounds pretty old.

Heh, I wish...
```console
$ /usr/bin/gcc --version
gcc (SUSE Linux) 4.3.4 [gcc-4_3-branch revision 152973]
```

> In your build environment, what modules are loaded?

```console
$ module list
Currently Loaded Modulefiles:
  1) modules/3.2.10.4                      12) xpmem/0.1-2.0502.64982.5.3.gem        23) xalt/0.7.6.local
  2) eswrap/1.3.3-1.020200.1280.0          13) dvs/2.5_0.9.0-1.0502.2188.1.113.gem   24) scripts
  3) cce/8.7.7                             14) alps/5.2.4-2.0502.9774.31.12.gem      25) OpenSSL/1.0.2m
  4) craype-network-gemini                 15) rca/1.0.0-2.0502.60530.1.63.gem       26) cURL/7.59.0
  5) craype/2.5.16                         16) atp/2.0.4                             27) git/2.17.0
  6) cray-libsci/18.12.1                   17) PrgEnv-cray/5.2.82                    28) wget/1.19.4
  7) udreg/2.3.2-1.0502.10518.2.17.gem     18) cray-mpich/7.7.4                      29) user-paths
  8) ugni/6.0-1.0502.10863.8.28.gem        19) craype-interlagos                     30) gnuplot/5.0.5
  9) pmi/5.0.14                            20) torque/6.0.4                          31) darshan/3.1.3
 10) dmapp/7.0.1-1.0502.11080.8.74.gem     21) moab/9.1.2-sles11
 11) gni-headers/4.0-1.0502.10859.7.8.gem  22) openssh/7.5p1
```

> And what is your compilers.yaml entry for the gcc 5.5 compiler that fails?

```yaml
- compiler:
    paths:
      cc: /mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-bulldozer/gcc-5.3.0/gcc-5.5.0-rjdchao67bab752ox47lofveq7qfatpp/bin/gcc
      cxx: /mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-bulldozer/gcc-5.3.0/gcc-5.5.0-rjdchao67bab752ox47lofveq7qfatpp/bin/g++
      f77: /mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-bulldozer/gcc-5.3.0/gcc-5.5.0-rjdchao67bab752ox47lofveq7qfatpp/bin/gfortran
      fc: /mnt/a/u/sciteam/stewart1/spack/opt/spack/cray-cnl5-bulldozer/gcc-5.3.0/gcc-5.5.0-rjdchao67bab752ox47lofveq7qfatpp/bin/gfortran
    operating_system: cnl5
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
    flags: {}
    spec: gcc@5.5.0
```
Will try building with a newer GCC.

**Comment by mwkrentel** [comment]
Ah ha!  You built gcc 5.5.0 with spack, right?  In that case, you need
to put the spack module in the compiler spec.  Spack compiler find
doesn't do this automatically.

Try this.  Add the module for gcc 5.5.0 to the compiler entry and
re-activate the bootstrap patch.  See if that works.

**Comment by adamjstewart** [comment]
I'm not using modules. Like I literally disabled Spack's generation of modules. Why would the module be needed to use the compiler if everything is RPATHed?

**Comment by mwkrentel** [comment]
I'll see if theta at ANL is close enough to produce the same behavior.

What does spack arch report for FE and BE?
Run from the FE, I guess.

So, you're building boost on the compute nodes?
On theta, I normally build BE apps on the login nodes.

**Comment by adamjstewart** [comment]
On login nodes:
```console
$ spack arch
cray-cnl5-bulldozer
```
On compute nodes:
```console
$ spack arch
cray-suse_linux11-bulldozer
```
Boost builds fine with GCC 8.2.0 on the compute nodes. Boost fails with the same error message for GCC 5.5.0 on both the compute and login nodes.

**Comment by mwkrentel** [comment]
@adamjstewart Has something changed on your system, or is this your
first time building boost with gcc 5.5?  That is, the bootstrap patch
is 2.5 years old, I'm wondering why you haven't seen this before?

Anyway, the arch tells me that Blue Waters is a standard, "old-style"
Cray, just a really old version.  So, I'm hopeful that I can get the
same result on theta or cori.

The gcc results tell me that the problem is failing to pass the
-std=c++11 flag to the 5.5 compiler.  The later gcc 8.2 doesn't need
the flag, so that's why it works.

The fundamental problem is that boost compiles bjam which needs
to run on the build node.  If building on the login node in a true
cross-compile situation (including Cray), the compiled bjam won't
run.  Neither spack nor boost handle this cleanly.

But you're building on the compute nodes, so I guess the bjam build
runs ok there, so you don't need the patch.  I hadn't really considered
that case.

Perhaps there's a simple solution to restrict the patch to
platform=cray and os=compute nodes (cnl5, cnl6, etc), so it only is
applied in the cross compile case.

Can you write 'os=cnl*' in a when() spec?
Maybe you have to write os=cnl5, os=cnl6, etc separately.

**Comment by adamjstewart** [comment]
I'm not sure if I've ever been able to compile `boost` on this system, this is my first time trying.

Yes, you can write `os=cnl5` in a `when=` arg. But note that my build fails with this patch both on `suse_linux11` (compute) and on `cnl5` (login), so the patch will need to be skipped in both cases on this system.

**Comment by mwkrentel** [comment]
Does building boost with gcc 5.5 work on the login node without the patch?
I would think that falls under the original problem of compute node code
will crash on the login node.  Building for cray-cnl5-bulldozer on login node  ?

**Comment by adamjstewart** [comment]
See above:

> Boost fails with the same error message for GCC 5.5.0 on both the compute and login nodes.

**Comment by mwkrentel** [comment]
It fails on the login node WITHOUT the patch?

I'd expect it to fail on the login node both with and without the
patch, but in different ways.  Without the patch, the CC wrapper code
won't run on the login node.  With the patch, it's missing the
-std=c++11 flag.

**Comment by adamjstewart** [comment]
Ah, sorry for the confusion.

It fails on the login and compute nodes with the patch. It succeeds on the login and compute nodes without the patch.

**Comment by mwkrentel** [comment]
@adamjstewart I'm trying to reproduce your steps and there's something
I don't understand.  I built gcc 5.5.0 (I had to build down, 9.3.0 --> 5.5.0).

On the compute nodes, spack arch reports os=suse_linux11, but your gcc
5.5.0 compiler entry has os=cnl5.  So how can you use that compiler
for that arch?  Spack won't accept that.

Do you have another gcc 5.5.0 entry?
Are you sure spack install is using 5.5.0?

On the compute nodes, for the 'spack install boost' that failed, what
does spack spec report?

**Comment by adamjstewart** [comment]
```console
$ spack spec boost %gcc@5.5.0

Input spec
--------------------------------
boost%gcc@5.5.0

Concretized
--------------------------------
boost@1.76.0%gcc@5.5.0+atomic+chrono~clanglibcpp~container~context~coroutine+date_time~debug+exception~fiber+filesystem+graph~icu+iostreams+locale+log+math~mpi+multithreaded~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave cxxstd=98 patches=57a8401dee8f52b0342e0c8147a5b2db834e8d8f3fbcbbc5950016bd3e9e1ef0 visibility=hidden arch=cray-cnl5-bulldozer
    ^bzip2@1.0.8%gcc@5.5.0~debug~pic+shared arch=cray-cnl5-bulldozer
        ^diffutils@3.7%gcc@5.5.0 arch=cray-cnl5-bulldozer
            ^libiconv@1.16%gcc@5.5.0 arch=cray-cnl5-bulldozer
    ^zlib@1.2.11%gcc@5.5.0+optimize+pic+shared arch=cray-cnl5-bulldozer

$ spack debug report
* **Spack:** 0.16.2-3480-e0017a6666
* **Python:** 3.5.5
* **Platform:** cray-suse_linux11-bulldozer
* **Concretizer:** original
```
It doesn't make a lot of sense to me either. I only have a single GCC 5.5.0 entry in my `compilers.yaml`.

**Comment by mwkrentel** [comment]
@adamjstewart @hainest 
I've tried several things and I've come to the conclusion that most of
the above theories are wrong.

Adam, try this experiment.  Rebuild gcc 5.5.0, but keep the module.
Make a new compilers.yaml entry for gcc 5.5.0 and cnl5 (you may need
to remove the old entry) and add the two modules for this entry:
PrgEnv-gnu and gcc.  Then build for cnl5 (as in your boost spec) with
the bootstrap patch.

Cray is complicated, but I'm beginning to appreciate that you really
need the PrgEnv-gnu module loaded at build time, and pretty much the
gcc module as well, but the PrgEnv-gnu is critical.

**Comment by mwkrentel** [comment]
@adamjstewart Did you try building boost with the PrgEnv-gnu and gcc modules?
All of the other examples do this with Cray and I think that's the answer here.

**Comment by adamjstewart** [comment]
Sorry, I'm traveling at the moment. Will test this out when I get back next week.

**Comment by adamjstewart** [comment]
Thanks, adding `PrgEnv-gnu` to my compiler modules list seems to solve the problem!

**Comment by mwkrentel** [comment]
@adamjstewart For Cray, adding `PrgEnv` to the `compilers.yaml` entry is 
essential.  But I would suggest that the safest course is also to add the module
for the compiler, especially if it's a system (non-spack) module.

For example, I've seen this happen.  A system comes with pre-built
(non-spack) modules for gcc x.y and cmake built with this gcc, and you
add an external cmake to `packages.yaml`.  Cmake requires libstdc++,
but without the gcc module, cmake can't find the right C++ library and
the build fails.

I guess spack puts in enough rpaths that this doesn't happen if
everything is built with spack.  But if the compiler comes from a
non-spack module, then you really need to put this in `compilers.yaml`.

That's the safest thing to do and doesn't really have a downside.  And
it avoids subtle errors like this case where the error message is that
gcc doesn't support C++11, but the real error is that the compiler
doesn't run at all.

**Comment by marius311** [comment]
Super new to Spack but ran into the same issue installing boost, I gather the solution is "adding PrgEnv to the compilers.yaml entry" could one of you describe for a newbie what that means? Or any other info that might be helpful, I'm unable to figure out what I'm supposed to do based on the above discussion.

**Comment by adamjstewart** [comment]
It's important to note that the above discussion only applies on Cray. If you're not on a Cray system, this issue is irrelevant to you.

If you are on Cray, you should take a look at https://spack.readthedocs.io/en/latest/getting_started.html#spack-on-cray. 99% of the time, when you run `spack compiler find`, it will find your compilers for you and create a `compilers.yaml` that is good to go. It's usually found in `~/.spack/cray/compilers.yaml`, and usually contains something like:
```yaml
- compiler:
    ...
    modules:
      - PrgEnv-intel
      - intel/15.0.109
```
Note that the exact compilers and versions may differ. But the idea here is that most compilers on Cray systems won't work unless you load the PrgEnv module that was used to build them. So if you are on Cray and you don't see this line, you'll want to add it.
