### ISSUE TITLE
checksum command fails when fetch and install do not

### ISSUE THREAD

**Issue by tldahlgren** [LLNL/spack#24861]
Trying to check the sha256 for scotch (#24855), shows the `checksum` subcommand fails while `fetch` and `install` works.  The package currently provides `url` and `list_url` properties as well as a `url_for_version` method (gated on previous versions).

### Steps to reproduce the issue

```console
$ spack checksum scotch@6.1.1
==> Found 1 version of scotch:
  
  6.1.1  http://gforge.inria.fr/frs/download.php/latestfile/298/scotch_6.1.1_esmumps.tar.gz

==> Something failed on http://gforge.inria.fr/frs/download.php/latestfile/298/scotch_6.1.1_esmumps.tar.gz, skipping.  (All fetchers failed)
$ spack fetch scotch@6.1.1
==> Fetching http://gforge.inria.fr/frs/download.php/latestfile/298/scotch_6.1.1.tar.gz
$
...
```

### Error Message

See above.

### Information on your system

* **Spack:** 0.16.2-3503-a6f839b880
* **Python:** 3.7.2
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** original

### Additional information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [-] I have searched the issues of this repo and believe this is not a duplicate .. similar/overlap?
- [-] I have run the failing commands in debug mode and reported the output .. skipped inclusion since details not useful

**Comment by sethrj** [comment]
I think this is a problem with misuse of the `@when` inside the scotch package; it reminds me of my past misuse of `@when` , https://github.com/spack/spack/issues/20177 .

Does `spack checksum` concretize the spec when trying to fetch the URL?

**Comment by bernhardkaindl** [comment]
@tldahlgren The cause of `spack checksum` failing (and not install) is simple.

The `list_url` of the package cannot be fetched:
```html
curl https://gforge.inria.fr/frs/?group_id=248
<html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx/1.18.0 (Ubuntu)</center>
</body>
</html>
```
@sethrj Yes, the 2nd bug in the package is that the `@when('@:6.0.0')` is not applied, and therefore must be changed:

This fixes it, but see the question in the patch: 

```diff
diff --git a/var/spack/repos/builtin/packages/scotch/package.py b/var/spack/repos/builtin/packages/scotch/package.py
index 7aa55290c9..dbd0eb82bd 100644
--- a/var/spack/repos/builtin/packages/scotch/package.py
+++ b/var/spack/repos/builtin/packages/scotch/package.py
@@ -13,7 +13,8 @@ class Scotch(Package):
     homepage = "https://gitlab.inria.fr/scotch/scotch"
     git      = "https://gitlab.inria.fr/scotch/scotch.git"
     url      = "https://gforge.inria.fr/frs/download.php/latestfile/298/scotch_6.0.4.tar.gz"
-    list_url = "https://gforge.inria.fr/frs/?group_id=248"
+    # `spack checksum` does not list new 6.x.x versions from this, only adds old tags, why?
+    list_url = 'https://gitlab.inria.fr/scotch/scotch/-/tags'
 
     version('6.1.1', sha256='39052f59ff474a4a69cefc25cf3caf8429400889deba010ee6403ca188f8b311')
     version('6.1.0', sha256='a3bc3fa3b243fcb52f8d68de4272562a0328afb18a96f535724d284e36730485')
@@ -68,10 +69,9 @@ class Scotch(Package):
     # from the Scotch hosting site.  These alternative archives include a
     # superset of the behavior in their default counterparts, so we choose to
     # always grab these versions for older Scotch versions for simplicity.
-    @when('@:6.0.0')
     def url_for_version(self, version):
-        url = "https://gforge.inria.fr/frs/download.php/latestfile/298/scotch_{0}_esmumps.tar.gz"
-        return url.format(version)
+        url = 'https://gforge.inria.fr/frs/download.php/latestfile/298/scotch_{0}{1}.tar.gz'
+        return url.format(version, '_esmumps' if version <= Version('6.0.0') else '')
 
     @property
     def libs(self):
```
(Hint: The comment above `url_for_version` says that they want to append `_esmumps` for '@:6.0.0')

I'd also move `url_for_version` next to the `version()` calls where it belongs.

Ok if I submit this fix as PR?

**Comment by sethrj** [comment]
Great catch! A pr for Scotch would be great. No idea why the list url isn't picking up the newer tags but can look into it. We also ought to improve the failure mode for "list url doesn't work".

**Comment by alalazo** [comment]
This doesn't seem to fail as of:

* **Spack:** 0.21.0.dev0 (64c6d63675f8e45e0be12a9c55acb4b7969e383a)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

This is what I get:
```console
$ spack checksum scotch@6.1.1
==> Found 1 version of scotch:
  
  6.1.1  https://gitlab.inria.fr/scotch/scotch/-/archive/v6.1.1/scotch-v6.1.1.tar.gz

==> Fetching https://gitlab.inria.fr/scotch/scotch/-/archive/v6.1.1/scotch-v6.1.1.tar.gz

    version("6.1.1", sha256="14daf151399fc67f83fd3ff2933854f5e8d2207c7d35dd66a05660bf0bbd583c")
```
