### ISSUE TITLE
Installation issue: py-tensorboard-plugin-wit

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#24946]
### Steps to reproduce the issue

```console
$ spack install py-tensorboard-plugin-wit
...
Segmentation fault (core dumped)
/tmp/spackfykr1z5g/dbe23794a6948018e3519954f7cd2e6d/execroot/ai_google_pair_wit/bazel-out/k8-fastbuild/bin/tensorboard_plugin_wit/pip_package/build_pip_package: 1: /tmp/spackfykr1z5g/dbe23794a6948018e3519954f7cd2e6d/execroot/ai_google_pair_wit/bazel-out/k8-fastbuild/bin/tensorboard_plugin_wit/pip_package/build_pip_package: Bad substitution
/tmp/spackfykr1z5g/dbe23794a6948018e3519954f7cd2e6d/execroot/ai_google_pair_wit/bazel-out/k8-fastbuild/bin/tensorboard_plugin_wit/pip_package/build_pip_package: 1: /tmp/spackfykr1z5g/dbe23794a6948018e3519954f7cd2e6d/execroot/ai_google_pair_wit/bazel-out/k8-fastbuild/bin/tensorboard_plugin_wit/pip_package/build_pip_package: Bad substitution
...
```

### Information on your system

* **Spack:** 0.16.2-3546-88aa8299d8
* **Python:** 3.8.1
* **Platform:** linux-ubuntu18.04-haswell
* **Concretizer:** original

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/6835086/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/6835087/spack-build-env.txt)

@aweits

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [x] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by aweits** [comment]
Do you know what binary is dumping core?

**Comment by adamjstewart** [comment]
How would I determine that?

**Comment by aweits** [comment]
you can run the "file" command on the corefile (if there is one) in the builddir/cwd when the build failed...
