### ISSUE TITLE
spack containerize for Singularity appears to be broken

### ISSUE THREAD

**Issue by jrobbin** [LLNL/spack#24959]
With this spack.yaml:
```shell
spack:
  specs:
  - tcl
  container:
    format: singularity
  view: true
```
The command:
```shell
spack containerize > image.def
```
writes a Singularity definition that fails to build.  The problem will be fixed in [Singularity 3.8.1](https://github.com/sylabs/singularity/issues/159).  The problem is that /opt/view in the first stage of 'image.def' is a symllink and Singularity doesn't handle symlinks correctly.  A short term fix is to not use a symlink:
```shell
rm /opt/view
mkdir /opt/view
mv /opt/._view/*/* /opt/view
```

### system
* **Spack:** 0.16.2-3534-29f10624bd
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-skylake
* **Concretizer:** original

**Comment by alalazo** [comment]
This has been fixed at some point. Cannot reproduce anymore with 0ce548a850eda4b742260dc63afcb7104a44b08c
