### ISSUE TITLE
Installation issue: paraview@master Could NOT find catalyst (missing: catalyst_DIR) 

### ISSUE THREAD

**Issue by EthanS94** [LLNL/spack#25057]
### Steps to reproduce the issue

@mathstuf I'm guessing the recent addition of `VTK_MODULE_USE_EXTERNAL_ParaView_vtkcatalyst` is getting turned on in spack.

```console
$ spack install paraview@master
...
      235    -- Could NOT find catalyst (missing: catalyst_DIR)
  >> 236    CMake Error at VTK/CMake/vtkModule.cmake:4366 (message):
     237      Could not find the catalyst external dependency.
     238    Call Stack (most recent call first):
     239      VTK/CMake/vtkModule.cmake:4960 (vtk_module_find_package)
     240      VTK/CMake/vtkModule.cmake:4831 (vtk_module_third_party_external)
     241      ThirdParty/catalyst/CMakeLists.txt:31 (vtk_module_third_party)
```

### Information on your system

```console
* **Spack:** 0.16.2-3651-25c09e7a56
* **Python:** 3.6.3
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** original
```

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by EthanS94** [comment]
`VTK_MODULE_USE_EXTERNAL_ParaView_vtkcatalyst` is enabled by spack:

```console
$ cat /tmp/stam/spack-stage/spack-stage-paraview-master-2ryfgurki4x53k4cdbmnehmtt7repmgi/spack-build-2ryfgur/CMakeCache.txt | grep VTK_MODULE_USE_EXTERNAL_ParaView_vtkcatalyst
VTK_MODULE_USE_EXTERNAL_ParaView_vtkcatalyst:BOOL=ON
//ADVANCED property for variable: VTK_MODULE_USE_EXTERNAL_ParaView_vtkcatalyst
VTK_MODULE_USE_EXTERNAL_ParaView_vtkcatalyst-ADVANCED:INTERNAL=1
```

**Comment by mathstuf** [comment]
Note that `catalyst` will need to be updated to `master` to have all of the fixes to work externally.

https://gitlab.kitware.com/paraview/catalyst/-/commit/8752c02c10e4ce24f2078d1c61ae8be8ee8dd056

**Comment by mathstuf** [comment]
I'll also note that it is not enabled explicitly by spack, but instead it is the default from the `PARAVIEW_BUILD_WITH_EXTERNAL=ON` setting.

**Comment by EthanS94** [comment]
@mathstuf What does this mean for fixing the spack build? Should the package have a `depends_on(catalyst)`? Or is setting `VTK_MODULE_USE_EXTERNAL_ParaView_vtkcatalyst:BOOL=OFF` as in the above PR the correct path?

**Comment by mathstuf** [comment]
Until Spack packages a new enough `catalyst`, using ParaView master's embedded copy is suitable. There should be a `catalyst` release before 5.10 though.
