### ISSUE TITLE
Replacement of shebang in environment views leaves tilde backup files

### ISSUE THREAD

**Issue by wdconinc** [LLNL/spack#25073]
In scripts in environment views, the shebang line (e.g. `#!/usr/bin/python3.8`) is replaced by the (hidden) view directory. However, this leaves a backup file with `~` with the original shebang line. Probably harmless.

### Steps to reproduce the issue

With a `spack.yaml` in the current directory
```yaml
spack:
  specs:
  - py-setuptools
  view: /opt/bug-tilde
```
setup the environment as follows:
```console
$ spack env activate .
$ spack concretize -f
$ spack install
```

### Error Message

When correctly installed, I don't expect to see any files with `~` suffixed. However,
```console
$ ls /opt/bug-tilde/bin/*~
```
returns
```console
$ ls /opt/bug-tilde/bin/*~
/opt/bug-tilde/bin/easy_install~  /opt/bug-tilde/bin/easy_install-3.8~
```

The first lines of the `easy_install` and `easy_install~` files are:
```console
$ head -n 1 /opt/bug-tilde/bin/easy_install /opt/bug-tilde/bin/easy_install~
==> /opt/bug-tilde/bin/easy_install <==
#!/opt/._bug-tilde/6x4nr3otmtjkbustvme6h3nogieg7or4/bin/python3.8

==> /opt/bug-tilde/bin/easy_install~ <==
#!/opt/software/linux-ubuntu21.04-skylake/gcc-10.3.0/python-3.8.11-q2cz5f6dqnom6d453ob4eg3bvurbhfuc/bin/python3.8
```

### Information on your system

* **Spack:** 0.16.2-3642-10461c68ac
* **Python:** 3.9.5
* **Platform:** linux-ubuntu21.04-skylake
* **Concretizer:** original

### Additional information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [ ] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
@becker33 @scheibelp was it one of you working on environment symlinks recently?

I think this would be as simple as using `backup=False` in `filter_file` to prevent these tilde backup files, but I'm not sure where the code is for this.

**Comment by adamjstewart** [comment]
Another symptom of this: when using `jupyter` from an environment, I see:
```console
$ jupyter -h
...
Available subcommands: bundlerextension bundlerextension~ kernel kernelspec kernelspec~ kernel~ lab labextension labextension~ labhub
labhub~ lab~ migrate migrate~ nbclassic nbclassic~ nbconvert nbconvert~ nbextension nbextension~ notebook notebook~ run run~ server
serverextension serverextension~ server~ troubleshoot troubleshoot~ trust
```
