### ISSUE TITLE
Some spack tests fail because they find system executables instead of spack-provided

### ISSUE THREAD

**Issue by wspear** [LLNL/spack#25093]
We observed this issue operating on the spock system at olcf using the gnu-PrgEnv module and the latest pull of spack to install the e4s environment. Running `spack test run` to do all internal smoke tests resulted in several errors indicating that the spack test for some basic utilities was finding the system executable instead of the one provided by spack. We did not attempt to find any externals in this install of spack.

The error takes the form:

`Executable 'perl' expected in prefix, found in /usr/bin/perl instead`

Packages that exhibited this testing result were: binutils (for 11 of its internally provided executables), cmake, m4 and perl.

**Comment by tldahlgren** [comment]
I have experienced this problem as well with packages depending on a specific `CMake`.

**Comment by adamjstewart** [comment]
I just encountered this as well. This affected `cmake`, `hdf5`, `m4`, `perl`, `python`, and `sqlite`, all of which expect to find their executables in their installation prefix. Are we not running `setup_run_environment` before running these tests?
