### ISSUE TITLE
Recommended approach when a package changes build system (KaHIP)?

### ISSUE THREAD

**Issue by garth-wells** [LLNL/spack#25111]
Is there a recommend approach for when a package changes build system? The package in question is `kahip` [1], which has changed from SCons (v.2) to CMake (v.3). The current Spack package is for KaHIP version 2.0 and uses SCons. The latest KaHIP release series is v.3.

[1] https://github.com/spack/spack/blob/e5bbb6e5b4a1af25dd46101bfc044d04deb10cb5/var/spack/repos/builtin/packages/kahip/package.py

**Comment by adamjstewart** [comment]
I finally got around to documenting this! Can you see if #25174 does a good job of explaining how to support multiple build systems? If anything is unclear, let me know and I'll try to improve the docs.
