### ISSUE TITLE
Installation issue: clingo-bootstrap

### ISSUE THREAD

**Issue by wspear** [LLNL/spack#25164]
### Steps to reproduce the issue

Set up a spack environment to use the clingo concretizer by adding

  config:
    concretizer: clingo

to the spack.yaml file. Then run:

```console
$ spack concretize
...
```

### Information on your system

* **Spack:** 0.16.2-3738-b4c6c11e68
* **Python:** 3.6.13
* **Platform:** cray-sles15-zen2
* **Concretizer:** clingo

### Additional information
I encountered this issue on the Spock EA system so out of an abundance of caution I'm excising the full error output in case there's something NDA-adjacent in there. Let me know what more information might be useful. Selected error output without full paths:

cmake-3.20.5-buohxldhbe7xzsyhnt76m5tanfjbmnty/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.
          cmake:230 (message):
     9      Could NOT find Python (missing: Python_LIBRARIES Interpreter Development
     10     Development.Module Development.Embed)

@alalazo

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [x] I have run `spack maintainers <name-of-the-package>` and @mentioned any maintainers
- [ ] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Bootstrapping clingo currently requires Python's development libraries to be present. @alalazo has a PR that can bootstrap from binaries that may solve this. In the meantime, you'll have to use Spack's original concretizer to build clingo instead of relying on Spack to bootstrap it automatically.

**Comment by wspear** [comment]
When I tried this with the default concretizer I ran into a different (presumably compiler specific) error. I'm pretty sure gcc 10.3 is way above C++14 compliance so I'm not sure what's going on here...

```
==> Installing clingo-bootstrap-5.5.0-oeuddchte4jrrkzzabn3qeggx7k57bpw
==> No binary for clingo-bootstrap-5.5.0-oeuddchte4jrrkzzabn3qeggx7k57bpw found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/c9/c9d7004a0caec61b636ad1c1960fbf339ef8fdee9719321fc1b6b210613a8499.tar.gz
==> Ran patch() for clingo-bootstrap
==> clingo-bootstrap: Executing phase: 'cmake'
==> Error: JSONDecodeError: Expecting value: line 1 column 1 (char 0)

/autofs/nccs-svm1_proj/csc439/wspear/spock/spack/var/spack/repos/builtin/packages/clingo/package.py:83, in cmake_args:
         80        try:
         81            self.compiler.cxx14_flag
         82        except UnsupportedCompilerFlag:
  >>     83            InstallError('clingo requires a C++14-compliant C++ compiler')
         84
         85        args = [
         86            '-DCLINGO_REQUIRE_PYTHON=ON',

See build log for details:
  /tmp/wspear/spack-stage/spack-stage-clingo-bootstrap-5.5.0-oeuddchte4jrrkzzabn3qeggx7k57bpw/spack-build-out.txt

```

**Comment by alalazo** [comment]
@wspear Can you show:
```
$ spack find -d
$ spack compilers
```
?

**Comment by wspear** [comment]
I started over with a fresh clone of spack and removed my compilers.yaml and repopulated it but that didn'thelp. The duplicate compiler entries are identical which seems like a bug but I'm not sure how to reproduce it elsewhere.

spack find -d
```
==> 30 installed packages
-- cray-sles15-zen2 / gcc@10.3.0 --------------------------------
berkeley-db@18.1.40

bison@3.7.6
    m4@1.4.19
        libsigsegv@2.13

bzip2@1.0.8

cmake@3.21.1
    ncurses@6.2
    openssl@1.1.1k
        zlib@1.2.11

diffutils@3.7
    libiconv@1.16

expat@2.4.1
    libbsd@0.11.3
        libmd@1.0.3

gdbm@1.19
    readline@8.1
        ncurses@6.2

gettext@0.21
    bzip2@1.0.8
    libiconv@1.16
    libxml2@2.9.10
        xz@5.2.5
        zlib@1.2.11
    ncurses@6.2
    tar@1.34

libbsd@0.11.3
    libmd@1.0.3

libffi@3.3

libiconv@1.16

libmd@1.0.3

libsigsegv@2.13

libxml2@2.9.10
    libiconv@1.16
    xz@5.2.5
    zlib@1.2.11

m4@1.4.19
    libsigsegv@2.13

ncurses@6.2

openssl@1.1.1k
    zlib@1.2.11

perl@5.34.0
    berkeley-db@18.1.40
    bzip2@1.0.8
    gdbm@1.19
        readline@8.1
            ncurses@6.2
    zlib@1.2.11

pkgconf@1.7.4

py-cffi@1.14.3
    libffi@3.3
    py-pycparser@2.20
        python@3.8.11
            bzip2@1.0.8
            expat@2.4.1
                libbsd@0.11.3
                    libmd@1.0.3
            gdbm@1.19
                readline@8.1
                    ncurses@6.2
            gettext@0.21
                libiconv@1.16
                libxml2@2.9.10
                    xz@5.2.5
                    zlib@1.2.11
                tar@1.34
            openssl@1.1.1k
            sqlite@3.35.5
            util-linux-uuid@2.36.2

py-pycparser@2.20
    python@3.8.11
        bzip2@1.0.8
        expat@2.4.1
            libbsd@0.11.3
                libmd@1.0.3
        gdbm@1.19
            readline@8.1
                ncurses@6.2
        gettext@0.21
            libiconv@1.16
            libxml2@2.9.10
                xz@5.2.5
                zlib@1.2.11
            tar@1.34
        libffi@3.3
        openssl@1.1.1k
        sqlite@3.35.5
        util-linux-uuid@2.36.2

py-setuptools@50.3.2
    python@3.8.11
        bzip2@1.0.8
        expat@2.4.1
            libbsd@0.11.3
                libmd@1.0.3
        gdbm@1.19
            readline@8.1
                ncurses@6.2
        gettext@0.21
            libiconv@1.16
            libxml2@2.9.10
                xz@5.2.5
                zlib@1.2.11
            tar@1.34
        libffi@3.3
        openssl@1.1.1k
        sqlite@3.35.5
        util-linux-uuid@2.36.2

python@3.8.11
    bzip2@1.0.8
    expat@2.4.1
        libbsd@0.11.3
            libmd@1.0.3
    gdbm@1.19
        readline@8.1
            ncurses@6.2
    gettext@0.21
        libiconv@1.16
        libxml2@2.9.10
            xz@5.2.5
            zlib@1.2.11
        tar@1.34
    libffi@3.3
    openssl@1.1.1k
    sqlite@3.35.5
    util-linux-uuid@2.36.2

re2c@1.2.1

readline@8.1
    ncurses@6.2

sqlite@3.35.5
    readline@8.1
        ncurses@6.2
    zlib@1.2.11

tar@1.34
    libiconv@1.16

util-linux-uuid@2.36.2

xz@5.2.5

zlib@1.2.11
```
spack compilers (showing gcc only)
```
-- gcc sles15-any -----------------------------------------------
gcc@10.3.0  gcc@10.3.0  gcc@10.2.0  gcc@9.3.0  gcc@9.3.0  gcc@8.1.0

```

**Comment by alalazo** [comment]
Apologies @wspear there's a typo on my end, I meant:
```console
$ spack find -b
```
to check what was installed in the bootstrap store.

**Comment by wspear** [comment]
$ spack find -b
==> Showing internal bootstrap store at "/ccs/home/wspear/.spack/bootstrap/store"
==> 16 installed packages
-- cray-sles15-x86_64 / gcc@10.3.0 ------------------------------
berkeley-db@18.1.40  bzip2@1.0.8   diffutils@3.7  libiconv@1.16    m4@1.4.19    openssl@1.1.1k  pkgconf@1.7.4  readline@8.1
bison@3.7.6          cmake@3.20.5  gdbm@1.19      libsigsegv@2.13  ncurses@6.2  perl@5.34.0     re2c@1.2.1     zlib@1.2.11

**Comment by alalazo** [comment]
@wspear What I see is that apparently the spec to bootstrap clingo concretized to something, so Spack knows what it _should_ do. 

The bootstrap store though has no mention of `python`, which is strange (it should be registered as an external as `python@3.6`). Also, from the CMake error you posted it seems CMake couldn't detect Python (it needs the interpreter + headers + libraries) and thus couldn't proceed building clingo.

EDIT: there's another thing that we need at the moment which is a static `libstdc++` to avoid spurious dependencies on the compiler being used

**Comment by wspear** [comment]
Not sure if this is useful, but the spec shows a sub-dependency on python@3.8.11. Nothing about 3.6. Anything else I can do to either bypass this or help diagnose? I've successfully used clingo provided by pip but I thought it was worth while trying to get it work from bootstrap here.

```
$ spack spec clingo-bootstrap
Input spec
--------------------------------
clingo-bootstrap

Concretized
--------------------------------
clingo-bootstrap@5.5.0%gcc@10.3.0~docs~ipo+python build_type=Release arch=cray-sles15-zen2
    ^bison@3.7.6%gcc@10.3.0 arch=cray-sles15-zen2
        ^diffutils@3.7%gcc@10.3.0 arch=cray-sles15-zen2
            ^libiconv@1.16%gcc@10.3.0 arch=cray-sles15-zen2
        ^m4@1.4.19%gcc@10.3.0+sigsegv arch=cray-sles15-zen2
            ^libsigsegv@2.13%gcc@10.3.0 arch=cray-sles15-zen2
        ^perl@5.34.0%gcc@10.3.0+cpanm+shared+threads arch=cray-sles15-zen2
            ^berkeley-db@18.1.40%gcc@10.3.0+cxx~docs+stl patches=b231fcc4d5cff05e5c3a4814f6a5af0e9a966428dc2176540d2c05aff41de522 arch=cray-sles15-zen2
            ^bzip2@1.0.8%gcc@10.3.0~debug~pic+shared arch=cray-sles15-zen2
            ^gdbm@1.19%gcc@10.3.0 arch=cray-sles15-zen2
                ^readline@8.1%gcc@10.3.0 arch=cray-sles15-zen2
                    ^ncurses@6.2%gcc@10.3.0~symlinks+termlib abi=none arch=cray-sles15-zen2
                        ^pkgconf@1.7.4%gcc@10.3.0 arch=cray-sles15-zen2
            ^zlib@1.2.11%gcc@10.3.0+optimize+pic+shared arch=cray-sles15-zen2
    ^cmake@3.21.1%gcc@10.3.0~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=cray-sles15-zen2
        ^openssl@1.1.1k%gcc@10.3.0~docs+systemcerts arch=cray-sles15-zen2
    ^py-cffi@1.14.3%gcc@10.3.0 arch=cray-sles15-zen2
        ^libffi@3.3%gcc@10.3.0 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0 arch=cray-sles15-zen2
        ^py-pycparser@2.20%gcc@10.3.0 arch=cray-sles15-zen2
            ^py-setuptools@50.3.2%gcc@10.3.0 arch=cray-sles15-zen2
                ^python@3.8.11%gcc@10.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87,ebdca648c9c1d25f586d7e2a495b62e6d91973b55264a13d89eda1beff72ef56 arch=cray-sles15-zen2
                    ^expat@2.4.1%gcc@10.3.0+libbsd arch=cray-sles15-zen2
                        ^libbsd@0.11.3%gcc@10.3.0 arch=cray-sles15-zen2
                            ^libmd@1.0.3%gcc@10.3.0 arch=cray-sles15-zen2
                    ^gettext@0.21%gcc@10.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=cray-sles15-zen2
                        ^libxml2@2.9.10%gcc@10.3.0~python arch=cray-sles15-zen2
                            ^xz@5.2.5%gcc@10.3.0~pic libs=shared,static arch=cray-sles15-zen2
                        ^tar@1.34%gcc@10.3.0 arch=cray-sles15-zen2
                    ^sqlite@3.35.5%gcc@10.3.0+column_metadata+fts~functions~rtree arch=cray-sles15-zen2
                    ^util-linux-uuid@2.36.2%gcc@10.3.0 arch=cray-sles15-zen2
    ^re2c@1.2.1%gcc@10.3.0 arch=cray-sles15-zen2
```

**Comment by alalazo** [comment]
@wspear When we bootstrap we temporarily override part of the configuration and:
- Set the store to an alternate place (to keep the software installed for Spack's purposes separated from the one you need for your own work)
- Register the current Spack interpreter as an external Python
- Fix the version of clingo we want to use, for compatibility reasons

This is to say that I expected to see `python@3.6` given the output you posted for:
```console
$ spack debug report
```
If you concretize `clingo-bootstrap` yourself outside of bootstrapping, Spack will proceed with the "usual" concretization without applying the temporary modifications above and e.g. happily build a new python for it like above. You can use:
```console
$ spack -d solve zlib
```
for instance to trigger bootstrapping without having to modify any configuration file.

**Comment by wspear** [comment]
Running `spack -d solve zlib` does a lot, but eventually fails with the  `Could NOT find Python (missing: Python_LIBRARIES Interpreter Development` error.

It is trying to use the python3.6 for that. Would it be worth while to try again after setting SPACK_PYTHON to the 3.8 that this spack already built?

**Comment by alalazo** [comment]
> Would it be worth while to try again after setting SPACK_PYTHON to the 3.8 that this spack already built?

Yes, please try something like that. The error here is very likely that the Python you are using doesn't have header files or they can't be located by CMake. 

Also, slightly OT but if you have time it would be appreciated. Can you try #22720 and do:
```console
$ spack -d solve zlib
```
That PR should bootstrap from precompiled binaries and hopefully it should work correctly (will be merged soon).

**Comment by wspear** [comment]
Looks like it works (both the clingo-bootstrap install and spack -d solve zlib) with the manually bootstrapped python (SPACK_PYTHON pointed to spack built 3.8)

The pull request also results in a successful solve zlib. I double checked that it still fails without either the pull request or the spack-built python.

**Comment by alalazo** [comment]
@wspear So I think this issue is due to the default Python interpreter, that either is not providing header files or is not configured in a way that CMake can find them. I'll add this to the list of issues fixed by #22720

**Comment by tldahlgren** [comment]
@alalazo I'm having an issue with clingo-bootstrap on one of the UO machines (gilgamesh).  The error message is:

```
==> [2021-08-12-16:15:55.027368] Already staged spack-stage-clingo-bootstrap-spack-owrs6t57onlctzocu3l4hx5szj4qmepn in /tmp/gitlab-runner/spack-stage/spack-stage-clingo-bootstrap-spack-owrs6t57onlctzocu3l4hx5szj4qmepn
==> [2021-08-12-16:15:55.028223] FILTER FILE: clasp/CMakeLists.txt [replacing "find_package\(Doxygen\)"]
==> [2021-08-12-16:15:55.044779] Error: FileNotFoundError: [Errno 2] No such file or directory: 'clasp/CMakeLists.txt'

/home/gitlab-runner/builds/tldahlgren/llnl-e4s-3a8822b7/spack/var/spack/repos/builtin/packages/clingo/package.py:61, in patch:
         58            filter_file(r'find_package\(Doxygen\)',
         59                        'message("Doxygen disabled for Spack build.")',
         60                        'clasp/CMakeLists.txt',
  >>     61                        'clasp/libpotassco/CMakeLists.txt')


Traceback (most recent call last):
  File "/home/gitlab-runner/builds/tldahlgren/llnl-e4s-3a8822b7/spack/lib/spack/spack/build_environment.py", line 1013, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/home/gitlab-runner/builds/tldahlgren/llnl-e4s-3a8822b7/spack/lib/spack/spack/installer.py", line 1890, in build_process
    return installer.run()
  File "/home/gitlab-runner/builds/tldahlgren/llnl-e4s-3a8822b7/spack/lib/spack/spack/installer.py", line 1727, in run
    self.pkg.do_patch()
  File "/home/gitlab-runner/builds/tldahlgren/llnl-e4s-3a8822b7/spack/lib/spack/spack/package.py", line 1469, in do_patch
    self.patch()
  File "/home/gitlab-runner/builds/tldahlgren/llnl-e4s-3a8822b7/spack/var/spack/repos/builtin/packages/clingo/package.py", line 62, in patch
  File "/home/gitlab-runner/builds/tldahlgren/llnl-e4s-3a8822b7/spack/lib/spack/llnl/util/filesystem.py", line 177, in filter_file
    shutil.copy(filename, backup_filename)
  File "/usr/lib64/python3.6/shutil.py", line 245, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib64/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'clasp/CMakeLists.txt'
==> [2021-08-12-16:15:55.045110] Flagging clingo-bootstrap-spack-owrs6t57onlctzocu3l4hx5szj4qmepn as failed: FileNotFoundError: [Errno 2] No such file or directory: 'clasp/CMakeLists.txt'
==> [2021-08-12-16:15:55.048753] Creating stage lock spack-stage-clingo-bootstrap-spack-owrs6t57onlctzocu3l4hx5szj4qmepn
==> [2021-08-12-16:15:55.052149] ChildError: FileNotFoundError: [Errno 2] No such file or directory: 'clasp/CMakeLists.txt'
```
[[uo-gilgamesh-shell-bootstrap.txt](https://github.com/spack/spack/files/6979132/uo-gilgamesh-shell-bootstrap.txt)
](url)

See https://systems.nic.uoregon.edu/internal-wiki/index.php?title=Compute:_Gilgamesh for details on the server.

**Comment by alalazo** [comment]
@tldahlgren I don't know if anything changed in the meanwhile, but I logged into Gilgamesh and the system Python interpreter there has clingo installed:
```console
$ python3 -m pip show clingo
Name: clingo
Version: 5.5.0.post3
Summary: CFFI-based bindings to the clingo solver.
Home-page: https://github.com/potassco/clingo
Author: Roland Kaminski
Author-email: kaminski@cs.uni-potsdam.de
License: MIT
Location: /usr/local/lib64/python3.6/site-packages
Requires: cffi
Required-by: 
```
so no need to bootstrap.

**Comment by tldahlgren** [comment]
> @tldahlgren I don't know if anything changed in the meanwhile, but I logged into Gilgamesh and the system Python interpreter there has clingo installed:
> 
> ```
> $ python3 -m pip show clingo
> Name: clingo
> Version: 5.5.0.post3
> Summary: CFFI-based bindings to the clingo solver.
> Home-page: https://github.com/potassco/clingo
> Author: Roland Kaminski
> Author-email: kaminski@cs.uni-potsdam.de
> License: MIT
> Location: /usr/local/lib64/python3.6/site-packages
> Requires: cffi
> Required-by: 
> ```
> 
> so no need to bootstrap.

It did.  Luke installed `clingo` and `boto` for me on the machine.  But I thought it could be useful for this issue and associated PR to provide an example of the output I was getting -- since it did appear to be CMake-related.

**Comment by frobnitzem** [comment]
Clingo will also not boostrap on my install using the latest develop branch today.

The first `spack concretize` I ran hung during bootstrapping.  After I killed it, spack used the old concretizer.

However, trying to fix this by installing clingo showed what looks like a parse error from the clingo spackage as it tries to detect the c++14 flag.  The arch/compiler here is `linux-rhel8-x86_64/gcc-10.3.0`, so this should "just work"
```
==> Installing clingo-bootstrap-5.5.0-kgce6uyz5afg6gst2pa5jlfe4e4y2rmx
==> No binary for clingo-bootstrap-5.5.0-kgce6uyz5afg6gst2pa5jlfe4e4y2rmx found: installing from source
==> Using cached archive: /spack/var/spack/cache/_source-cache/archive/c9/c9d7004a0caec61b636ad1c1960fbf339ef8fdee9719321fc1b6b210613a8499.tar.gz
==> Ran patch() for clingo-bootstrap
==> clingo-bootstrap: Executing phase: 'cmake'
==> Error: JSONDecodeError: Expecting value: line 1 column 1 (char 0)

/spack/var/spack/repos/builtin/packages/clingo/package.py:84, in cmake_args:
         81        try:
         82            self.compiler.cxx14_flag
         83        except UnsupportedCompilerFlag:
  >>     84            InstallError('clingo requires a C++14-compliant C++ compiler')
         85
         86        args = [
         87            '-DCLINGO_REQUIRE_PYTHON=ON',

See build log for details:
  /tmp/spack-stage/spack-stage-clingo-bootstrap-5.5.0-kgce6uyz5afg6gst2pa5jlfe4e4y2rmx/spack-build-out.txt
```
