### ISSUE TITLE
Installation issue: hip using cmake-3.21.1 

### ISSUE THREAD

**Issue by srekolam** [LLNL/spack#25195]
### Steps to reproduce the issue

 spack  install -v hip
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/pkgconf-1.7.4-6kb5qdvzffhclwpx25wmbr65hpeidtej
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/berkeley-db-18.1.40-2ppyrsl6t7cjdajhihkucem6tykaqbke
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/libiconv-1.16-ugkwz7ufoj6aa42jvsd7kagsh5wajbpv
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/zlib-1.2.11-57hh2lpkgczcbz7sk5asx5djgwtexyji
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/libsigsegv-2.13-mch2u7h4lpka7hvtduru6p5vwuyx6ebb
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/util-macros-1.19.3-rxbl2urq6uapvhsxp5ae5we6ml6xt7h4
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/xz-5.2.5-e6dke6offxixlrzz6tuu4of7sptmzt6p
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/libelf-0.8.13-rzznv2yyrkxofp7d3d7gxnmfdqzg4b6z
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/libmd-1.0.3-tui4dw3sqjoczxp53zq5vgj3goztgkfm
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/libffi-3.3-qkvt6rnrtexdldlu52uyh7bpagwiioht
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/xxd-standalone-8.2.1201-nlzf6ruvsdltierfkj6ussioy7p4llnz
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/findutils-4.8.0-xfbaw5qnkbyxi4eih6khnwla2j2mhj43
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/libpthread-stubs-0.4-ba2e3mwbnd3jmcjvgo4nl3p4xm4rhild
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/xcb-proto-1.14.1-26fl2wn5nqgloheyrfg5l7xeabim6ug6
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/roctracer-dev-api-4.2.0-itj2ogj4iz5wucrt232u4rjid7ymfk3b
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/ncurses-6.2-mutherq2ribewsdl4jqlf7d5w6ms4srz
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/util-linux-uuid-2.36.2-ao2vvd5hr32nqwsbz6xike2ejmpof3yj
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/diffutils-3.7-sjxgoxvd43sbxvjbdflg3nxqycx7igyc
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/tar-1.34-w2ozxmbszjo33wqntys42tjtu7n5adhu
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/m4-1.4.19-u6tjb6nwvdpephk2p2jofwjgm4y6fvme
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/xextproto-7.3.0-hu7bcgeqnzwudkahppchw3thewhhzl2y
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/glproto-1.4.17-7rl6szqe4m7rrogladg2qxhsmg5zhjgs
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/xproto-7.0.31-6uptneubk4bnwlzjsag6cmfvbo7lufpu
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/xtrans-1.3.5-gqsstt7m7pn2d5gdvdmbcu4c5rbwer36
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/kbproto-1.0.7-5s3idbmn5475pxsj7apx3toe7jnhg6s5
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/inputproto-2.3.2-6xrhuuwrfxr4qszgbg6aufwgpl37pdmd
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/libxml2-2.9.10-sywtqfk4x37wjfbzlmpeytta6hwsyj2p
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/libbsd-0.11.3-jopo5j2mn3toehq3ra6t3tmv4oxggm2u
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/readline-8.1-kftr56amn4rdyj5d3rw4kmnh4lqxl2xl
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/bzip2-1.0.8-tfj4h2jy5jvkag7qrnuviertvrmnxasb
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/libtool-2.4.6-xgjmzy2lfei63ehmcax34cgajp6tunax
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/libxau-1.0.8-f3sqmfksa4guhxmii5kmvs5av7vpv2wi
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/expat-2.4.1-u2i3736ljk5bjontv2rowowbvvwjykto
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/libxdmcp-1.1.2-pcobj7ott6swkma7oex2auy3nyliqhkk
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/sqlite-3.35.5-ktzu2m7nfrkc53nzohmpq6ge4szlmoxd
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/gdbm-1.19-opinul7zjs2podh4sifhi66wxibpz2nx
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/gettext-0.21-ybbvt55cxhblz2wxegeotcifbxcxpjzl
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/libpciaccess-0.16-2cacksdahlpzhlaus6dvdoysqv2jcfk7
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/libxcb-1.14-m62mqbf7seea4lw6bonixxvycgnqin4m
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/perl-5.34.0-aexjsqfisjklb4bovkqbt4qzl77xjlnd
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/binutils-2.36.1-lv5vo3g55zeqrc45rvdbhxupmdysdt7d
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/hwloc-2.5.0-3kdynp57me7bdd4rrhm32jcpxm6wbswi
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/bison-3.7.6-wjde5hbm7ps2esr4oruusd6nlhyryoy2
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/libx11-1.7.0-dzzbznrpqlq6tn7n3k6qe5iq7pgrbuvz
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/autoconf-2.69-tihhiavj4mzd4fdizin4yv2o3ynocsfg
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/openssl-1.1.1k-rovayuj3qrqiacsdlf4q65efihxo2s55
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/perl-data-dumper-2.173-iuwrbk34tblfknsg3ohnocglkl2jmthl
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/flex-2.6.3-uhkd74ra6fpaj7gqplmeh7hl6gh624j7
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/libxext-1.3.3-tdfs34uohetcrs6jpxddszztt63ud4mu
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/automake-1.16.3-heuyrcpmsujbc7dz2ys4ew3pro2dojoz
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/cmake-3.21.1-r27wnvhyfdsak4nzbbtyor45o44fvmck
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/python-3.8.11-vxibe2etltfia3pmefwlasp6sd25ycks
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/numactl-2.0.14-7oo67kwhlga6t7wgw3sj5opxx73tc7of
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/rocm-cmake-4.2.0-dzuqa5ofxmxythjwtv2dmk2uakxmi6p4
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/py-setuptools-50.3.2-nprx27okvnjwvfgciliiit3wnucud35b
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/z3-4.8.9-iqa4wpznkte6v54ickrjz7lfd2k3xa63
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/hsakmt-roct-4.2.0-t4mpgcwyywitly7bzdthnwh4pmhx3acc
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/py-markupsafe-2.0.1-nfsczw73tgsybawxduegfsdihyxcdo3q
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/llvm-amdgpu-4.2.0-2mnw7ps7i3axpbpzzpuyyyy3qhvarh5d
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/py-mako-1.1.4-xwowtpm5bmdshus3pwrsqqauijjdc5j7
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/comgr-4.2.0-tenhwd5dbz6gm7a32hfmhfgc342vr62c
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/hsa-rocr-dev-4.2.0-cfcyk5ssntw73my5ats3rlwdnew4y3bx
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/mesa18-18.3.6-6r7hpymile4jt4thnxgh5vfwoonqlyo6
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/rocminfo-4.2.0-56gwr3hwmor2dtzsqhhifamr6xvhcn3p
[+] /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.3.1/hip-rocclr-4.2.0-2xiidglcl7zn6svppg4w4pzjucngjo2n
==> Installing hip-4.2.0-nhq3hften2ouny37nxzjsmqfrlyzvk2v

### Information on your system

* **Spack:** 0.16.2-3763-2dd2a5b167
* **Python:** 3.6.8
* **Platform:** linux-centos8-skylake_avx512
* **Concretizer:** original

### Additional information

@haampie @arjun-raj-kuppala @srekolam 
[spack-build-env.txt](https://github.com/spack/spack/files/6920092/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/6920093/spack-build-out.txt)

the build is passing when we use the cmake@3.20.5

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
:laughing: cmake 3.21 adds hip language support but it can't build hip?

**Comment by srekolam** [comment]
@haampie  , i think we can close this issue right.

**Comment by haampie** [comment]
Yeah!
