### ISSUE TITLE
Incorrect Spec Resolution When Specifying Hash for Dependency at Install

### ISSUE THREAD

**Issue by xjrc** [LLNL/spack#2520]
There is a bug in Spack that causes a dependency's `spec` to be resolved incorrectly if the dependent package specifies the dependency through its hash when invoking `spack install` (e.g. `spack install package ^/dephash`).

To reproduce this error, perform a fresh install of the latest version of Spack and run the following commands:

```
./bin/spack install zlib~pic
./bin/spack install hdf5~shared~pic~mpi ^/abcdefg # 'abcdefg' is the hash of 'zlib~pic'
```

The second command will fail to install `hdf5~shared~pic~mpi` since the directory containing the `zlib` dependency cannot be found.  Based on the name of the `zlib` directory that this command attempts to use, it's clear that the hash for `zlib` is being resolved incorrectly in the `hdf5` install method.  This error affects all packages that evaluate a `spec['dependency'].prefix` expression at any point during their installation.

**Comment by xjrc** [comment]
This is potentially related to #1377, but I don't think that this bug existed at the time #1377 was submitted.  As far as I can tell, this was issue was introduced into Spack at some point since commit edfe2297fd0bd376c8026d9309b241300ab65ed1 was merged (i.e. the last month or two).

**Comment by becker33** [comment]
@xjrc is this fixed by #2626?

**Comment by xjrc** [comment]
@becker33 I'll verify sometime later today or tomorrow and I'll let you know.

**Comment by xjrc** [comment]
@becker33 I just verified that spec dependencies work again and are resolved correctly when submitted from the command line.  Thanks for your help!
