### ISSUE TITLE
flex and scotch conflicts

### ISSUE THREAD

**Issue by svenevs** [LLNL/spack#2521]
Hello,

I was trying to install something else that through the chain wanted to install `scotch`.  I originally thought that `scotch` was failing, it had a bunch of `undefined reference to scotchyywrap` stuff going on.  The great google gods led me to [here](http://stackoverflow.com/questions/1811125/undefined-reference-to-yywrap), and I realized it was probably a `flex` conflict.  I really have no idea what these things are doing, but `scotch@6.0.3` could not install using `flex@2.6.2`.  I simply commented out the `2.6.2` version of flex (therefore defaulting to `2.6.1`) and then `scotch@6.0.3` was able to install.

If it means anything, the package that was ultimately installing both of these was `eigen` which came from a complicated `opencv` (test) installation.

If helpful, I am compiling with `gcc 5.3.1`.  Unsure if anybody else is even affected by this, but figured I'd post it in case it's helpful to somebody else somewhere :)

**Comment by adamjstewart** [comment]
Confirmed that this bug occurs for me on CentOS 6 with GCC 6.1.0. Confirmed that rolling back to an older version of flex works. Will submit PR shortly.
