### ISSUE TITLE
"--log-file" generating no logfile

### ISSUE THREAD

**Issue by kelbstf** [LLNL/spack#25269]
### Steps to reproduce

Hello,

i currently fail with compiling r and try to debug it, but no log files seem to be available.
````console
# test 1:
$ spack -d -v install --show-log-on-error --log-file r-installation.log r
# test 2:
$ spack -d -v install --log-file r-installation.log r
````
The specified logfiles can not be found on the system.
Is this an expected behaviour, resp. am i missing here s.th.?

### Error message

````console
==> [2021-08-05-12:52:08.587531, 1861413] InstallError: Installation of r failed.  Review log for details
==> [2021-08-05-12:52:08.587565, 1861413] Error: Installation of r failed.  Review log for details
Traceback (most recent call last):
  File "/opt/ohpc/admin/spack/0.15.0/lib/spack/spack/main.py", line 761, in main
    return _invoke_command(command, parser, args, unknown)
  File "/opt/ohpc/admin/spack/0.15.0/lib/spack/spack/main.py", line 489, in _invoke_command
    return_val = command(parser, args)
  File "/opt/ohpc/admin/spack/0.15.0/lib/spack/spack/cmd/install.py", line 386, in install
    install_spec(args, kwargs, abstract, concrete)
  File "/opt/ohpc/admin/spack/0.15.0/lib/spack/spack/cmd/install.py", line 243, in install_spec
    spec.package.do_install(**kwargs)
  File "/opt/ohpc/admin/spack/0.15.0/lib/spack/spack/package.py", line 1475, in do_install
    builder.install(**kwargs)
  File "/opt/ohpc/admin/spack/0.15.0/lib/spack/spack/installer.py", line 1597, in install
    raise InstallError(msg)
````

I seem to not be able to find any of the referenced log files as well, in addition to the missing log file i hoped to have specified via "--log-file" when issuing the installation command.
All i have is a log for each of the packages like "./spack-cc-PACKAGENAME-zxc53zd.out.log", but which seems to provide no helpful information.
E.g.:

````console
./spack-cc-cmake-zxc53zd.out.log
[ ... ]
dlnojkmeowgdpauvawcgc2nny7gctxr2/lib64 -Wl,-rpath,/opt/ohpc/admin/spack/0.15.0/opt/spack/linux-centos8-haswell/gcc-9.3.0/libffi-3.3-dlnojkmeowgdpauvawcgc2nny7gctxr2/lib -Wl,-rpath,/opt/ohpc/admin/spack/0.15.0/opt/spack/linux-centos8-haswell/gcc-9.3.0/cairo-1.16.0-wwdnhjzkrn2c2o3ly3hpxita7paqkpsn/lib -Wl,-rpath,/opt/ohpc/admin/spack/0.15.0/opt/spack/linux-centos8-haswell/gcc-9.3.0/libiconv-1.16-npqkwr6lgj4gwhfcrn7pste7legqssn7/lib -Wl,-rpath,/opt/ohpc/pub/compiler/gcc/9.3.0/lib/gcc/x86_64-pc-linux-gnu/9.3.0 -Wl,-rpath,/opt/ohpc/pub/compiler/gcc/9.3.0/lib64 -fPIC -DPIC -shared -nostdlib /lib/../lib64/crti.o /opt/ohpc/pub/compiler/gcc/9.3.0/lib/gcc/x86_64-pc-linux-gnu/9.3.0/crtbeginS.o .libs/libharfbuzz_icu_la-hb-icu.o -licuuc -licudata -lharfbuzz -lstdc++ -lm -lc -lgcc_s /opt/ohpc/pub/compiler/gcc/9.3.0/lib/gcc/x86_64-pc-linux-gnu/9.3.0/crtendS.o /lib/../lib64/crtn.o -Wl,-soname -Wl,libharfbuzz-icu.so.0 -o .libs/libharfbuzz-icu.so.0.20301.0
````

### Information on your system

* **Spack:** 0.15.0
* **Python:** 3.6.8
* **Platform:** linux-centos8-haswell

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Tracked elsewhere, but short answer is that the `--log-format` argument is mandatory. Note that a text log is always saved in the `.spack` subfolder of the installation prefix. What these argument are about is generating a log that can be ingested by some dashboard (right now either in the JUnit or CDash format).
