### ISSUE TITLE
OpenPBS not provides 'pbs' virtual package

### ISSUE THREAD

**Issue by angelocr** [LLNL/spack#25272]
### Steps to reproduce

I installed OpenPBS from the OpenHPC repository and I added as an external package to Spack:
```console
packages:
  openpbs:
    buildable: false
    externals:
    - spec: openpbs@20.0.1%gcc@9.3.0
      prefix: /opt/pbs
```

When I try to install OpenMPI with "schedulers=tm", the concretization depends on Torque and not OpenPBS:
```console
$ spack spec openmpi@4.1.1 %gcc@9.3.0 schedulers=tm
Input spec
--------------------------------
openmpi@4.1.1%gcc@9.3.0

Concretized
--------------------------------
openmpi@4.1.1%gcc@9.3.0~atomics~cuda~cxx~cxx_exceptions+gpfs~internal-hwloc~java+legacylaunchers~lustre~memchecker~pmi~singularity~sqlite3+static~thread_multiple+vt+wrapper-rpath fabrics=verbs schedulers=tm arch=linux-ol8-x86_64
...
    ^torque@3.0.4%gcc@9.3.0 arch=linux-ol8-x86_64
```

I added the line:
```console
provides('pbs')
```
to OpenPBS "package.py" and OpenMPI concretization depends on OpenPBS as expected.

### Information on your system

* **Spack:** 0.16.2-3816-8f238c03ad
* **Python:** 3.6.8
* **Platform:** linux-ol8-broadwell
* **Concretizer:** original

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
The `openpbs` package does not currently have an official maintainer. I would suggest submitting a PR with your proposed change, it sounds like the right thing to do to me.

**Comment by sethrj** [comment]
@angelocr I think this is fixed on `develop`; https://github.com/spack/spack/pull/16758 should have allowed openpbs support and https://github.com/spack/spack/pull/24568 enables other PBS managers. Can you try building with that instead of the (more stable but out of date) 16.2?

**Comment by adamjstewart** [comment]
@sethrj I think the `openpbs` package is missing `provides('pbs')` like @angelocr mentioned. Right now, `torque` is the only PBS provider in Spack:
```console
$ spack providers pbs
pbs:
torque
```

**Comment by sethrj** [comment]
Ah I see! Thanks for teaching me a new command :) when I made #24568 I only added the providers to the default `packages.yaml`. I'll fix in a new PR.
