### ISSUE TITLE
Publish package list in repology

### ISSUE THREAD

**Issue by jayvdb** [LLNL/spack#25288]
### Summary

Adding spack package list to https://repology.org/ allows library maintainers an easy place to see the library in all packaging systems, especially identifying which are out of date and the maintainer to contact.

### Rationale

https://github.com/repology/ is a meta-repo of packages in various packaging systems.

The list of supported repositories is at https://repology.org/repositories/ , and includes conan, vcpkg and Buckaroo.

Here is the entry for spack, showing the repositories
https://repology.org/project/spack/versions

https://github.com/repology/repology-updater/issues/706 was closed as there wasnt buy-in from spack developers.

### Description

https://repology.org/addrepo for the process.

Either spack emits the package list in a format Repology already can support, or a more custom parser is needed.

All existing parsers are at https://github.com/repology/repology-updater/tree/master/repology/parsers/parsers

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
@vsoch @tldahlgren might be interested in this.

**Comment by vsoch** [comment]
Why are the only packages for spack different versions of spack?

https://repology.org/project/spack/packages

if it helps I keep a list of packages that updates automatically nightly:

https://spack.github.io/packages/data/packages.json

**Comment by vsoch** [comment]
Do y'all just need this format? https://repology.org/addrepo

**Comment by alalazo** [comment]
Leaving a comment to get email notifications, since this issue is quite interesting.

**Comment by jayvdb** [comment]
> Why are the only packages for spack different versions of spack?
> https://repology.org/project/spack/packages

It shows that some distros have an out of date version of spack, and Mageia Cauldron is using an unreleased git based version.

> Do y'all just need this format? https://repology.org/addrepo

That is the first step - publishing JSON with whatever metadata per package is possible, with roughly that structure.

Then spack needs to contribute a parser, like those in https://github.com/repology/repology-updater/tree/master/repology/parsers/parsers , to consume that JSON into the structure Repology needs.

https://github.com/repology/repology-updater/blob/master/repology/parsers/parsers/ravenports.py is a good example.  Some other minor additions elsewhere in repology are needed to describe "spack" as a repository.
c.f. https://github.com/repology/repology-updater/search?q=ravenports , and esp the yaml, e.g. https://github.com/repology/repology-updater/blob/fe40d9a5849f712b6fa7ca63832159e688e821d9/repos.d/bsd/ravenports.yaml

**Comment by vsoch** [comment]
cool thanks! That looks relatively straight forward - I'll start putting together those files for spack.

**Comment by vsoch** [comment]
@jayvdb I have the basic files ready - could you show me how to use repology-update.py (or some other basic Python command) so I can test my parser class? I see there is a database - ideally I'd want to just disable that or use sqlite.

**Comment by vsoch** [comment]
Just to ping others here, I did work for this yesterday https://github.com/repology/repology-updater/pull/1173 and there is something in the parsing that is not detecting/registering the package. If someone with experience with repology could take a look it would be very helpful!

**Comment by vsoch** [comment]
This is published: https://repology.org/repository/spack, and I've opened a PR to address a bulk of the list of problems #25491

**Comment by vsoch** [comment]
I think we can close this - if any further tweaks, etc. are needed we can open new issues. Thanks everyone!
