### ISSUE TITLE
UQTk variant to build PyUQTk and add it to PYTHONPATH

### ISSUE THREAD

**Issue by padamson** [LLNL/spack#25297]
### Summary

UQTk provides a Python interface called PyUQTk that is not currently built. This feature request is to add a variant to build PyUQTk and add it to `PYTHONPATH`.

### Rationale

PyUQTk is a very useful, integral part to UQTk.

### Description

An alternative is to always build PyUQTk, but this would add overhead for those that will not use the PyUQTk interface.

### Additional information

```console
> spack --version
0.16.2-3824-c27e0223d5
```

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
I see that you already added a PR in this sense, which is fine. Usually we use the "feature" tag for feature requests on core Spack, while we just proceed with PRs modifying packages without the additional burden of opening an issue for each modification. I'm going to close this issue and continue the discussion in #25298, but feel free to reopen if you think I missed something.

**Comment by padamson** [comment]
Ok, thanks for your patience while I learn the spack business rules.

**Comment by alalazo** [comment]
No worries, thanks for the PR!
