### ISSUE TITLE
optionally add maintainers to each package

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#2532]
I think it would be good to add _maintainers_ (in a very relaxed sense) -- a list of github users who are recommended to be pinged when the package is modified.

Something like
```
maintainers = @john, @paul, @george, @ringo
```
which is also to be printed in `spack info`. 

Those maintainers could be individuals who: 

- are (co-)authors of the software and are using Spack
- added the `package.py` to Spack 
- sysadmins who use this specific package and are interested in keeping it stable for their HPC users
- ...

The main point is NOT to say that _maintainers_ are responsible for a given package, but instead to simplify getting feedback on PRs/issues.

Given the rapid growth of Spack package base, it will be harder and harder to remember who is interested in what package and if something is wrong, whom should one ask for a feedback.

**Comment by citibeth** [comment]
The alternative is to just use `git blame` when something goes wrong.

**Comment by davydden** [comment]
> The alternative is to just use git blame when something goes wrong.

I think you address a different issue. As I tried to explain above, i would NOT consider maintainer to be responsible for packages, it's more like **volunteer** peers to review PRs or give advices for related issues. In other words, not everyone who ever contributed any changes to the given package will be listed as maintainers.

**Comment by adamjstewart** [comment]
I wonder if we could work some git voodoo so that anyone listed as a maintainer is automatically added to the list of reviewers when a PR is submitted. But as @davydden said, maintainers aren't just the ones who have edited the file. They can also be people who heavily depend on the packages and are willing to vet/test any changes made to that package.

**Comment by davydden** [comment]
> I wonder if we could work some git voodoo so that anyone listed as a maintainer is automatically added to the list of reviewers when a PR is submitted.

yes, ideally that would be good to have.

**Comment by adamjstewart** [comment]
Even without it being automagic, being able to see who is listed as a maintainer and manually pinging them to make sure they are ok with the changes would probably be nice. Especially for packages where the developers are also Spack users/maintainers.

**Comment by tgamblin** [comment]
I think this is an awesome idea.  I'd assume we'd add some more Travis tasks or maybe some other kind of webhook service to handle this.  We'd need to make sure the maintainer mentions don't get picked up in forks, but aside from that I see no problems with allowing people to volunteer to watch packages -- I think it would be really useful.

**Comment by citibeth** [comment]
Are there any more specifics on how this feature would work?  Would we need to add something to the `package.py` files?  Can you please give a mock-up example?  I want to get this idea ready for implementation in a PR.

**Comment by davydden** [comment]
i would say roughly the feature would work along the following lines (example of `dealii`):
(i) `dealii/package.py` would have `maintainers` field (can be set any any pythonic way, does not matter):
```
from spack import *


class Dealii(CMakePackage):
    """C++ software library providing well-documented tools to build finite
    element codes for a broad variety of PDEs."""
    homepage = "https://www.dealii.org"
    url      = "https://github.com/dealii/dealii/releases/download/v8.4.1/dealii-8.4.1.tar.gz"
    maintainers = @davydden, @jppelteret, @Rombur
    [the-rest-of-the-package.py]
```
(ii) `spack info dealii` would show:
```
$ spack info dealii
CMakePackage:    dealii
Homepage:        https://www.dealii.org
Maintainers:     @davydden @jppelteret @Rombur

Safe versions:
    develop    [git] https://github.com/dealii/dealii.git
    8.4.2      https://github.com/dealii/dealii/releases/download/v8.4.2/dealii-8.4.2.tar.gz
    [the-rest-of-the-output]
```

People who volunteer to watch packages would simply add their GitHub user names in PRs next time they modify a package and that's it for now. Then it would be suggested in Packaging guide to manually ping _maintainers_ when modifying a package which would amount to copy-pasting a part of the `spack info` and do `@davydden @jppelteret @Rombur ping`. Maybe later this could be automated with github woodo.

**Comment by citibeth** [comment]
Thanks.

1. It looks like other Spack changes (for now) would be be in the Sphinx
stuff, to pull the maintainers list into the manual on ReadTheDocs.

2. Should we allow maintainers who don't have GitHub handles?  I.e. by
email address?

3. I believe the maintainers should be specified like:
```
maintainers = ('@davydden', '@jppelteret', '@Rombur')
```
or even:
```
maintainers = '@davydden,@jppelteret,@Rombur'
```

4. Should the order of maintainers mean anything? Is the first in the list
a "primary maintainer"?

**Comment by davydden** [comment]
> 1. It looks like other Spack changes (for now) would be be in the Sphinx
stuff, to pull the maintainers list into the manual on ReadTheDocs.

yes, good idea

> 2. Should we allow maintainers who don't have GitHub handles?  I.e. by
email address?

i think it's not that important for now, i would say it can be added later if there is a need.

> 3. I believe the maintainers should be specified like:

I think we should drop `@` so that GitHub won't send notifications in case somebody fork Spack or modify those packages. The `@` character can be added later in the output of `spack info`

> 4. Should the order of maintainers mean anything? Is the first in the list
a "primary maintainer"?

i would say no. I would not impose any hierarchy. The output could be done alphabetically.

**Comment by citibeth** [comment]
>
>
>    1. I believe the maintainers should be specified like:
>
> I think we should drop @ so that GitHub won't send notifications in case
> somebody fork Spack or modify those packages. The @ character can be
> added later in the output of spack info
>
Are you saying that GitHub does "clever" things when `@maintainer` is found
in a source file?  And don't you think the maintainers will WANT to know
when someone modifies a package they maintain?


>
>    1. Should the order of maintainers mean anything? Is the first in the
>    list
>    a "primary maintainer"?
>
> i would say no. I would not impose any hierarchy. The output could be done
> alphabetically.
>
Then the syntax to set it up should be unordered:
```
maintainers = {'davydden', 'jppelteret', 'Rombur'}
```

**Comment by aprokop** [comment]
A sample script to determine authors: 
```bash
cd var/spack/repos/builtin/packages
for i in `find . -name 'package.py'`; do echo '---' $i '---' && git shortlog --format="%aN" -s -e $i | sort -rn; done
```
results in 
```
--- ./ImageMagick/package.py ---
     3	Todd Gamblin <tgamblin@llnl.gov>
     2	Massimiliano Culpo <massimiliano.culpo@epfl.ch>
     2	Adam J. Stewart <ajstewart426@gmail.com>
     1	Jeffrey Salmond <js947@users.noreply.github.com>
     1	Ben Boeckel <ben.boeckel@kitware.com>
--- ./LuaJIT/package.py ---
     2	Todd Gamblin <tgamblin@llnl.gov>
     1	Tom Scogland <tscogland@llnl.gov>
...
```

**Comment by davydden** [comment]
@aprokop Maintainers != authors, see [above](https://github.com/LLNL/spack/issues/2532#issuecomment-266088539).

**Comment by davydden** [comment]
> Are you saying that GitHub does "clever" things when `@maintainer` is found
in a source file?

not sure about the source, but one certainly get pinged when mentioned in the commit.

> And don't you think the maintainers will WANT to know
when someone modifies a package they maintain?

sure, but not in every fork Spack has. So far it's manual business anyway, when a contributor modifies a package he is advised to ping maintainers. To be on the safe side i would not use `@` for now. If we find out later that there is a good reasons to add it, then it's rather simple. On another hand if maintainers will get pinged to much on forks of Spack, then it may discourage individuals to volunteer.

**Comment by davydden** [comment]
p.s. @aprokop but thanks for the script :smile:

**Comment by aprokop** [comment]
@davydden I just thought that if I know nothing about a package, lets look at the authors.

**Comment by davydden** [comment]
> @davydden I just thought that if I know nothing about a package, lets look at the authors.

I agree, maybe this script should be added somewhere in Spack and in case maintainers field is empty, then contributors are advised to check who previously modified the given package and ping them. The problem here is that you have names and e-mails, and not GitHub names to ping... But maybe one can dig this info somehow automatically...

**Comment by davydden** [comment]
p.s. i do those things by-hand looking at the history to check who edited the package before me.

**Comment by davydden** [comment]
On another hand, the individuals who ever contributed some changes to Spack may NOT want to be pinged at all. So it's kind of pinging people without their permission. That's why i think of _maintainers_ as volunteer who themselves add their name to a `package.py`. Shall they decide not be bothered in future -- they create PR to remove the name.

So i kind of feel that this system is more polite towards contributors.

**Comment by aprokop** [comment]
How do you reach people that could be interested to be maintainers, but do not follow spack development after contributing once or twice?

**Comment by davydden** [comment]
> How do you reach people that could be interested to be maintainers, but do not follow spack development after contributing once or twice?

I would say just advertising the feature in release notes. If I am someone who once contributed to `packageA` and use it often/depend on it being functional, then I would consider keeping an eye on the package not being broken and/or help test PRs in my environment/settings. 

p.s. One could of course send e-mails ONCE to all guys who ever contributed changes to each package and invite to be maintainers, but (i) it may be spack-like / illegal (ii) i would expect maintainers to volunteer naturally assuming that people know about the feature.

**Comment by citibeth** [comment]
I think we can just wait for people to come forward. Maintainers are only
needed when a package breaks.

**Comment by citibeth** [comment]
I think this is ready to implement.

**Comment by markcmiller86** [comment]
I like this idea very much also. However I also see an important need for users of packages and that is being able to report bugs to those package Developers. I understand the desire to have a concept of maintainer that does not necessarily mean package authers or Developers. Therefore I would also like to see support for identifying where to submit bug reports. This could be something as simple as an additional field in a package. Py file that specifies an email address or a URL for a web page at which bugs can be submitted. Users of the packages in all likelihood will not know whether a problem is how a package is configured and built or is endemic to the current version of The Source Code actually being used in the package itself. From an end user standpoint by far the simplest thing would be for a additional spack subcommand, call it spack "bug report" which accept texts from the user and a package name and the symbols a bunch of info compilers operating systems package version information package configuration information)  is then sent to the packag's bug report email and possibly also to the maintainers of the package. Py file so that both groups of people are aware
