### ISSUE TITLE
Installation issue: hpctoolkit (unsatisfiable variant constraint)

### ISSUE THREAD

**Issue by BenWibking** [LLNL/spack#25323]
### Steps to reproduce the issue

```
$ spack install hpctoolkit
==> Warning: gcc@8.4.1 cannot build optimized binaries for "cascadelake". Using best target possible: "skylake_avx512"
==> Error: An unsatisfiable variant constraint has been detected for spec:

    xz@5.2.4%gcc@8.4.1~pic libs=shared,static arch=linux-centos8-skylake_avx512


while trying to concretize the partial spec:

    hpctoolkit@2021.05.15%gcc@8.4.1~all-static~cray~cuda~debug~mpi+papi~rocm+viewer arch=linux-centos8-skylake_avx512
        ^binutils+libiberty
            ^diffutils
                ^iconv
            ^zlib@1.2.11%gcc@8.4.1+optimize+pic+shared arch=linux-centos8-skylake_avx512
        ^boost@1.76.0%gcc@8.4.1+atomic+chrono~clanglibcpp~container~context~coroutine+date_time~debug+exception~fiber+filesystem+graph~icu+iostreams+locale+log+math~mpi+multithreaded~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave cxxstd=98 visibility=global arch=linux-centos8-skylake_avx512
            ^bzip2@1.0.6%gcc@8.4.1~debug~pic+shared arch=linux-centos8-skylake_avx512
        ^dyninst@10.2.0:
            ^cmake@3.21.1%gcc@8.4.1~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-centos8-skylake_avx512
            ^elfutils@0.185%gcc@8.4.1+bzip2~debuginfod~nls+xz arch=linux-centos8-skylake_avx512
                ^m4@1.4.18%gcc@8.4.1+sigsegv arch=linux-centos8-skylake_avx512
                ^xz@5.2.4%gcc@8.4.1~pic libs=shared,static arch=linux-centos8-skylake_avx512
            ^intel-tbb@2020.3%gcc@8.4.1+shared+tm cxxstd=default arch=linux-centos8-skylake_avx512
            ^libiberty+pic
        ^gotcha@1.0.3%gcc@8.4.1~ipo~test build_type=RelWithDebInfo arch=linux-centos8-skylake_avx512
        ^libdwarf@20180129%gcc@8.4.1 arch=linux-centos8-skylake_avx512
        ^libmonitor~dlopen+hpctoolkit
        ^libunwind@1.5.0%gcc@8.4.1+pic+xz~zlib arch=linux-centos8-skylake_avx512
        ^mbedtls@2.16.9%gcc@8.4.1~ipo+pic~shared build_type=Release arch=linux-centos8-skylake_avx512
        ^xerces-c@3.2.3%gcc@8.4.1 cxxstd=default netaccessor=curl transcoder=iconv arch=linux-centos8-skylake_avx512
            ^curl


hpctoolkit requires xz variant +pic, but spec asked for ~pic
```

### Information on your system

* **Spack:** 0.16.2-3870-5916afec84
* **Python:** 3.6.8
* **Platform:** linux-centos8-cascadelake
* **Concretizer:** original

### Additional information

N/A

Maintainers: @mwkrentel 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by mwkrentel** [comment]
@BenWibking  What does `spack config blame packages` report, and what is in your
`packages.yaml`?

Either (1) something in your config specifies `xz~pic`, in which case
you need to change that to +pic.

Or (2) the concretizer is being dumb and fixing on xz~pic before it should.

Either way, you can probably fix this by explicity adding `xz+pic` in
packages.yaml.

```
packages:
  xz:
    variants: +pic
```

or else on the command line:

```
spack install hpctoolkit ^xz+pic
```

**Comment by BenWibking** [comment]
`spack config blame packages` reports (along with a lot of other unrelated packages):
```
/home/120/bw0729/.spack/packages.yaml:191                       xz:
/home/120/bw0729/.spack/packages.yaml:192                         externals:
/home/120/bw0729/.spack/packages.yaml:193                         - spec: xz@5.2.4
/home/120/bw0729/.spack/packages.yaml:194                           prefix: /
```

`spack install hpctoolkit ^xz+pic` strangely gives the same error:
```
$ spack install hpctoolkit ^xz+pic
==> Warning: gcc@8.4.1 cannot build optimized binaries for "cascadelake". Using best target possible: "skylake_avx512"
==> Error: An unsatisfiable variant constraint has been detected for spec:

    xz@5.2.4%gcc@8.4.1~pic libs=shared,static arch=linux-centos8-skylake_avx512


while trying to concretize the partial spec:

    hpctoolkit@2021.05.15%gcc@8.4.1~all-static~cray~cuda~debug~mpi+papi~rocm+viewer arch=linux-centos8-skylake_avx512
        ^binutils+libiberty
            ^diffutils
                ^iconv
            ^zlib@1.2.11%gcc@8.4.1+optimize+pic+shared arch=linux-centos8-skylake_avx512
        ^boost@1.76.0%gcc@8.4.1+atomic+chrono~clanglibcpp~container~context~coroutine+date_time~debug+exception~fiber+filesystem+graph~icu+iostreams+locale+log+math~mpi+multithreaded~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded+system~taggedlayout+test+thread+timer~versionedlayout+wave cxxstd=98 visibility=global arch=linux-centos8-skylake_avx512
            ^bzip2@1.0.6%gcc@8.4.1~debug~pic+shared arch=linux-centos8-skylake_avx512
        ^dyninst@10.2.0:
            ^cmake@3.21.1%gcc@8.4.1~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-centos8-skylake_avx512
            ^elfutils@0.185%gcc@8.4.1+bzip2~debuginfod~nls+xz arch=linux-centos8-skylake_avx512
                ^m4@1.4.18%gcc@8.4.1+sigsegv arch=linux-centos8-skylake_avx512
                ^xz@5.2.4%gcc@8.4.1~pic libs=shared,static arch=linux-centos8-skylake_avx512
            ^intel-tbb@2020.3%gcc@8.4.1+shared+tm cxxstd=default arch=linux-centos8-skylake_avx512
            ^libiberty+pic
        ^gotcha@1.0.3%gcc@8.4.1~ipo~test build_type=RelWithDebInfo arch=linux-centos8-skylake_avx512
        ^libdwarf@20180129%gcc@8.4.1 arch=linux-centos8-skylake_avx512
        ^libmonitor~dlopen+hpctoolkit
        ^libunwind@1.5.0%gcc@8.4.1+pic+xz~zlib arch=linux-centos8-skylake_avx512
        ^mbedtls@2.16.9%gcc@8.4.1~ipo+pic~shared build_type=Release arch=linux-centos8-skylake_avx512
        ^xerces-c@3.2.3%gcc@8.4.1 cxxstd=default netaccessor=curl transcoder=iconv arch=linux-centos8-skylake_avx512
            ^curl


hpctoolkit requires xz variant +pic, but spec asked for ~pic
```

**Comment by mwkrentel** [comment]
@BenWibking 
Ah, you're trying to use an external xz, that's the issue.  `~pic` is
the default for xz, so I think the (old) concretizer interprets the
externals spec as `xz~pic` and settles on that early and that
conflicts with hpctoolkit's need for `+pic`.

If my theory is correct, then IMO this is a concretizer bug, not a
toolkit bug.  But unless the new, clingo concretizer has the same bug,
then I think the answer is going to be, "won't fix, upgrade to the new
concretizer."

Anyway, the simple solution is to remove the externals spec for xz and
let spack build a new xz with +pic.

Theoretically, if /lib or /lib64 has a static liblzma.a built with
PIC, then you could change your externals spec to:

```
spec: xz@5.2.4 +pic
```

But that would only work if liblzma.a really was build with PIC.
Hpctoolkit configure tests for this and if not, then configure will
fail.  The easiest solution is to remove the externals spec.

I need to try this with the new concretizer.

@tgamblin @becker33 
This is a bug with the (old) concretizer, right?  He's using an
externals spec as:

```
xz:
  externals:
  - spec: xz@5.2.4
    prefix: /
```

Written this way, `xz@5.2.4` should match both `+pic` and `~pic`, right?
That's how packages.yaml would work if I told spack to build xz without
specifying the pic variant, right?

```
xz:
  version: [5.2.4]
```
That is, why does this match for a build-with-spack xz but not an external xz?

But I'm guessing the answer is "won't fix for the old concretizer",
unless this also happens with clingo, right?

**Comment by BenWibking** [comment]
I removed the external spec for xz and this issue is fixed. However, I still cannot install hpctoolkit because openjdk and binutils fail to build. Neither of these packages has a maintainer, but I've opened issues for them in separate tickets in the hope that someone will take a look (#25354 #25353).

**Comment by alalazo** [comment]
> I removed the external spec for xz and this issue is fixed.

Closing the issue, feel free to reopen if you think there's anything else to discuss here.
