### ISSUE TITLE
Style: 'spack style --fix' fails with isort v4.2.15

### ISSUE THREAD

**Issue by tldahlgren** [LLNL/spack#25341]
### Steps to reproduce

Spack is using a newer `isort` option for the settings file than is supported by the earliest version listed in `py-isort`.  I ran into this problem when, IIRC, Spack bootstrapped to the earlier version when I ran the `spack stye` command.

Current `isort` documentation lists three other options that *might* work on older versions.  I tried two (`--settings` and `--settings-file`) despite the help below only showing the third, or shortcut (i.e., `-sp`).  Both of those options worked so it's just the `--settings-file` one that doesn't.

```
$ spack style --fix hash_types.py
==> Running style checks on spack
  selected: isort, mypy, flake8
==> Modified files
  hash_types.py
==> Running isort checks
  usage: isort [-h] [-y] [-l LINE_LENGTH] [-w LINE_LENGTH] [-s SKIP]
               [-ns NOT_SKIP] [-sg SKIP_GLOB] [-t FORCE_TO_TOP]
               [-f KNOWN_FUTURE_LIBRARY] [-b KNOWN_STANDARD_LIBRARY]
               [-o KNOWN_THIRD_PARTY] [-p KNOWN_FIRST_PARTY] [-m {0,1,2,3,4,5}]
               [-i INDENT] [-a ADD_IMPORTS] [-af] [-r REMOVE_IMPORTS] [-ls] [-d]
               [-c] [-sl] [-ds] [-sd DEFAULT_SECTION] [-df] [-e] [-rc] [-ot]
               [-dt] [-ac] [-cs] [-ca] [-tc] [-v] [-vb] [-q] [-sp SETTINGS_PATH]
               [-ff FROM_FIRST] [-wl WRAP_LENGTH] [-fgw] [-fass] [-fas] [-fss]
               [-lbt LINES_BETWEEN_TYPES]
               [files [files ...]]
  isort: error: unrecognized arguments: --settings-file
  isort found errors
==> Running mypy checks
...
```

The file with the problem was reportedly modified BUT `git diff` did not show any changes until I changed the code to use one of the alternatives above.

### Error message

See `Steps to reproduce`.

### Information on your system

* **Spack:** 0.16.2-3877-1f7d825ea9
* **Python:** 3.7.2
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** original

Note: Checking (but skipping) step 3 in `General information` below since it wasn't necessary to run the debug command BUT this template requires it be checked.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
If only we had a package.py for spack where we could express these constraints ^^
