### ISSUE TITLE
Use system cmake when bootstrapping clingo

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#25363]
### Summary

When bootstrapping the new concretizer, Spack should use the system CMake if it is avaiable.

### Rationale

`clingo-bootstrap` only has 2 dependencies, Python and CMake. When bootstrapping the new concretizer, Spack correctly detects and uses the system Python, but doesn't use the system CMake. This leads to Spack building CMake and all of its 14 dependencies, which takes a substantial amount of time.

### Description

We should detect CMake the same way we detect Python.

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
We'll soon provide bootstrapping from binaries, and the docs already says:

> If you want to speed-up bootstrapping, you may try to search for cmake and bison on your system:
> ```
> $ spack external find cmake bison
> ==> The following specs have been detected on this system and added to /home/spack/.spack/packages.yaml
> bison@3.0.4  cmake@3.19.4
> ```

so I'm not really sure if we should go all the way to try to mock external detection for the sake of bootstrapping from sources.

**Comment by adamjstewart** [comment]
If binaries are coming soon, I'm fine with that. How soon is soon? Is that a different effort than the one to make public binaries for general Spack packages?

**Comment by alalazo** [comment]
> Is that a different effort than the one to make public binaries for general Spack packages?

Yes. Soon is a week or two I think. If you checkout #22720 and try:
```console
$ spack -d solve zlib
```
it should work out of the box and e.g. bootstrap from binaries built on `rhel5` for `x86_64` and `linux`.
