### ISSUE TITLE
Installation issue: perl

### ISSUE THREAD

**Issue by wspear** [LLNL/spack#25418]
### Steps to reproduce the issue

spack install perl %intel@19.1.3.304
This is with the latest pull of spack and installs perl@5.34. Similar errors observed with 5.32.1 and 5.35.0. 5.32.0 works. (EDIT)

Numerous errors occur in the build phase after a successful configure phase starting with:
  >> 38      gcc: error: unrecognized command line option '-we147'
  >> 39      gcc: error: unrecognized command line option '-mp'; did you mean '-p'?
  >> 40      gcc: error: unrecognized command line option '-no-gcc'; did you mean '-fno-dce'?

and followed by dozens similar to:
  >> 959     inline.h(149): error: identifier "__INT_MAX__" is undefined
     960           if (COP_SEQ_RANGE_LOW(pn) == PERL_PADSEQ_INTRO)
     961                                        ^
     962     
  >> 963     pad.c(329): error: type name is not allowed
     964                   if (CvSLABBED(&cvbody)) OpslabREFCNT_dec_padok(OpSLAB(CvROOT(&cvbody)));

### Information on your system

This occurs building on NERSC's CORI system.

* **Spack:** 0.16.2-3901-264b00bff4
* **Python:** 3.8.5
* **Platform:** cray-sles15-haswell
* **Concretizer:** original

### Additional information

@mjwoods @hartzell @justintoo (There are Author credits in the package but no maintainers tagged. Maybe worth updating if these devs are still active?)

[spack-build-env.txt](https://github.com/spack/spack/files/6983836/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/6983837/spack-build-out.txt)
[spack-configure-args.txt](https://github.com/spack/spack/files/6983838/spack-configure-args.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by shahzebsiddiqui** [comment]
There is a relevant issue see https://github.com/Perl/perl5/issues/18624#issuecomment-808970231 looping in @ikitayama who created the issue. I suppose let's wait for this issue to be fixed and then try to install perl

**Comment by alalazo** [comment]
@glennpj Pinging in case this issue might be of interest to you
