### ISSUE TITLE
Installation issue: python bz2 module cannot be imported

### ISSUE THREAD

**Issue by christoph-conrads** [LLNL/spack#25410]
### Steps to reproduce the issue

```console
$ spack install python@3.8.11
==> Installing python-3.8.11-q7dghfieeutuzy3bhhbh7a3aebdv6skj
==> No binary for python-3.8.11-q7dghfieeutuzy3bhhbh7a3aebdv6skj found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/b7/b77464ea80cec14581b86aeb7fb2ff02830e0abc7bcdc752b7b4bdfcd8f3e393.tgz
==> Applied patch /home/john/spack/var/spack/repos/builtin/packages/python/python-3.7.4+-distutils-C++.patch
==> Ran patch() for python
==> python: Executing phase: 'autoreconf'
==> python: Executing phase: 'configure'
==> python: Executing phase: 'build'
==> python: Executing phase: 'install'
==> python: Successfully installed python-3.8.11-q7dghfieeutuzy3bhhbh7a3aebdv6skj
  Fetch: 1.62s.  Build: 58.72s.  Total: 1m 0.34s.
[+] /home/john/spack/opt/spack/linux-devuan3-skylake/gcc-8.3.0/python-3.8.11-q7dghfieeutuzy3bhhbh7a3aebdv6skj
john@db:~$ spack load python/q7dgh
john@db:~$ which python3
/home/john/spack/opt/spack/linux-devuan3-skylake/gcc-8.3.0/python-3.8.11-q7dghfieeutuzy3bhhbh7a3aebdv6skj/bin/python3
john@db:~$ python3 -c 'import bz2'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/john/spack/opt/spack/linux-devuan3-skylake/gcc-8.3.0/python-3.8.11-q7dghfieeutuzy3bhhbh7a3aebdv6skj/lib/python3.8/bz2.py", line 19, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'
john@db:~$ spack find --variants python/q7dgh
==> 1 installed package
-- linux-devuan3-skylake / gcc@8.3.0 ----------------------------
python@3.8.11+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87
```

### Information on your system

```console
john@db:~$ spack debug report
* **Spack:** 0.16.2-3904-6cd8583165
* **Python:** 3.7.3
* **Platform:** linux-devuan3-skylake
* **Concretizer:** original
john@db:~$ cat /etc/os-release 
PRETTY_NAME="Devuan GNU/Linux 3 (beowulf)"
NAME="Devuan GNU/Linux"
VERSION_ID="3"
VERSION="3 (beowulf)"
VERSION_CODENAME=beowulf
ID=devuan
ID_LIKE=debian
HOME_URL="https://www.devuan.org/"
SUPPORT_URL="https://devuan.org/os/community"
BUG_REPORT_URL="https://bugs.devuan.org/"
```

### Additional information

* The problem occurs with Python 3.8.11, 3.7.11.
* The problem described in this issue breaks Mercurial builds.
* [spack-build-out.txt](https://github.com/spack/spack/files/6982375/spack-build-out.txt) (Python 3.8.11 build)
* [spack-build-env.txt](https://github.com/spack/spack/files/6982376/spack-build-env.txt) (Python 3.8.11 build)

Possibly relevant in `spack-build-out.txt`:
```
The necessary bits to build these optional modules were not found:
_bz2                  _lzma                 _tkinter           
_uuid                                                          
To find the necessary bits, look in setup.py in detect_modules() for the module's name.
```

@adamjstewart @skosukhin

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by christoph-conrads** [comment]
The problem vanishes if bzip2 is built by Spack instead of re-using the system bzip2. This is probably a case of missing headers. :roll_eyes:

**Comment by christoph-conrads** [comment]
Installing `libbz2-dev` and `liblzma-dev` (for XZ) and rebuilding the Python interpreter resolves the problem for me.

**Comment by adamjstewart** [comment]
Yep, this is definitely caused by missing headers. I generally let Spack build everything instead of using external system packages.

**Comment by adamjstewart** [comment]
> The problem described in this issue breaks Mercurial builds.

Should we add a dependency on `python+bz2` then?

**Comment by christoph-conrads** [comment]
> Should we add a dependency on `python+bz2` then?

Ok but there is more missing than just `+bz2` (see below). I am investigating.
```
==> mercurial: Executing phase: 'build'
==> [2021-08-19-13:28:27.011927] '/home/john/spack/opt/spack/linux-devuan3-ivybridge/gcc-8.3.0/python-3.7.11-irtziiocozvuyntmm5vhds4bvomvvkbf/bin/python3.7' '-s' 'setup.py' '--no-user-cfg' 'build'
Traceback (most recent call last):
  File "setup.py", line 86, in <module>
    import ssl
  File "/home/john/spack/opt/spack/linux-devuan3-ivybridge/gcc-8.3.0/python-3.7.11-irtziiocozvuyntmm5vhds4bvomvvkbf/lib/python3.7/ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'
```

**Comment by christoph-conrads** [comment]
Exactly what I was looking for: [Mercurial wiki: _Supported Python Versions_](https://www.mercurial-scm.org/wiki/SupportedPythonVersions). I will add all of the information on this webpage to the Spack build.

An excerpt:
> 1. Current support
> 
> Mercurial 5.2 and newer has support for Python 3.5 and newer. Mercurial 4.3 and newer require at least Python 2.7. Python must include the following standard library components:
> 
> * sha/hashlib
> * gzip
> * ssl
> * bz2 (needed for bundles)
> * ctypes (only on Windows)

**Comment by christoph-conrads** [comment]
PR #25506
