### ISSUE TITLE
Installation issue: python

### ISSUE THREAD

**Issue by quellyn** [LLNL/spack#25445]
### Steps to reproduce the issue

1). Login to a node with the ppc64le architecture (IBM Power9):
```console
$ arch
ppc64le
```

2). Verify that the IBM XL compiler is present in your environment:
```console
$ module list

Currently Loaded Modulefiles:
  1) git/2.17.1                                3) ibm/xlc-16.1.1.7-xlf-16.1.1.7-gcc-8.3.0
  2) gcc/8.3.0
```

3). Clone the `spack` source and run the environment setup script:
```console
$ git clone git@github.com:spack/spack.git
$ cd spack
$ source ./share/spack/setup-env.sh
```

4). Verify that Spack knows about your IBM XL compiler:
```console
$ spack compiler list

==> Available compilers
-- gcc rhel7-ppc64le --------------------------------------------
gcc@8.3.0  gcc@4.8.5

-- xl rhel7-ppc64le ---------------------------------------------
xl@16.1

-- xl_r rhel7-ppc64le -------------------------------------------
xl_r@16.1
```

5). Attempt to install python 3.8.0 with the IBM XL compiler (NOTE:  Currently there are several dependencies such as libbsd, ncurses, and perl that cannot build under XL; build those with GCC instead):
```console
$ spack install -v python@3.8.0~uuid%xl_r@16.1 ^libbsd%gcc@8.3.0 ^ncurses%gcc@8.3.0 ^perl%gcc@8.3.0
```

The build attempt hangs indefinitely at this point:
```console
/vast/home/quellyn/GIT/spack/lib/spack/env/xl_r/xlc_r -L/vast/home/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/xl_r-16.1/gettext-0.21-dluhz5xuyb7p6ths56xrzmnsqsefpmdw/lib -L/vast/home/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.0/readline-8.1-z4y4pasaynsdcshsg3htpbp5w4ij7cm7/lib -L/vast/home/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.0/ncurses-6.2-63ymz3mlmh3cfy3kniwzhj7x2uyire4o/lib -L/vast/home/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/xl_r-16.1/openssl-1.1.1k-l7rdohgmihol3qmdzim4q3prg4yhzn4m/lib -L/vast/home/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/xl_r-16.1/sqlite-3.35.5-dgqqtqvlnapucewb6yqplnhxr6oxyubf/lib -L/vast/home/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.0/gdbm-1.19-u6knbvesvyp2uvk3kt2vkudkiuyvzj57/lib -L/vast/home/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/xl_r-16.1/zlib-1.2.11-722ljz2quor3zhxby4wrztndvloiyuqa/lib -L/vast/home/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/gcc-8.3.0/bzip2-1.0.8-u6z4i6i5x2e22cvr74wlbeplkvbcz37a/lib -L/vast/home/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/xl_r-16.1/xz-5.2.5-uz5q5kohv3zdbix5cadx2m34sxr5ivea/lib -L/vast/home/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/xl_r-16.1/expat-2.4.1-yt25nzmmurncvab6smtgxn3mtkyiyfrd/lib -L/vast/home/quellyn/GIT/spack/opt/spack/linux-rhel7-power9le/xl_r-16.1/libffi-3.3-ngcpqce2b66qehwdvofpvyn6bjqmyc6a/lib    -Xlinker -export-dynamic -o Programs/_testembed Programs/_testembed.o -L. -lpython3.8 -lcrypt -lintl -ldl  -lutil -lm   -lm 
LD_LIBRARY_PATH=/ram/tmp/quellyn/spack-stage/spack-stage-python-3.8.0-xkexu6rwqnfwskbkpllxvsbe5ojnwhiz/spack-src/spack-build ./python -E -S -m sysconfig --generate-posix-vars ;\
```

**NOTE** that python 3.7.9 builds under XL without issue. No version of python >= 3.8.0 succeeds, however.

Maintainers for the `python` Spack package are @adamjstewart and @skosukhin . Also mentioning @KineticTheory , as he has an interest in the outcome of this issue as well.

### Information on your system

```console
$ spack debug report

* **Spack:** 0.16.2-3901-264b00bff4
* **Python:** 3.6.8
* **Platform:** linux-rhel7-power9le
* **Concretizer:** original
```

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/6994711/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/6994712/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by quellyn** [comment]
NOTE:  I have [reported this issue upstream](https://bugs.python.org/issue44877) as well, with little attention so far.

**Comment by quellyn** [comment]
Received following response from python developers:
> I don't know nor support IBM XL compiler. PEP 11 only supports GCC and clang for PowerPC.

So I am building all python packages with GCC now (with the exception of `py-mpi4py`).

**Comment by adamjstewart** [comment]
Unfortunate, but certainly not surprising.
