### ISSUE TITLE
Anaconda Python: unable to locate python libraries

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#25468]
### Steps to reproduce

Using a conda installation of Python:
```console
$ ls -1 /anaconda/envs/azureml_py38/lib/libpython*
/anaconda/envs/azureml_py38/lib/libpython3.9.so
/anaconda/envs/azureml_py38/lib/libpython3.9.so.1.0
/anaconda/envs/azureml_py38/lib/libpython3.so
$ spack spec whatever
```

### Error message

```
==> Installing clingo-bootstrap-spack-6x4yakqlis7abi3z66nc2x6t5rjgohk6
==> No binary for clingo-bootstrap-spack-6x4yakqlis7abi3z66nc2x6t5rjgohk6 found: installing from source
==> Error: RuntimeError: Unable to locate libpython3.9.a libraries in /anaconda/envs/azureml_py38/lib

/home/t-astewart/spack/var/spack/repos/builtin/packages/python/package.py:830, in libs:
        827                return LibraryList(os.path.join(frameworkprefix, ldlibrary))
        828            else:
        829                msg = 'Unable to locate {0} libraries in {1}'
  >>    830                raise RuntimeError(msg.format(ldlibrary, libdir))
        831        else:
        832            library = self.get_config_var('LIBRARY')
        833
```

### Information on your system

* **Spack:** 0.16.2-3949-d00fc55e41
* **Python:** 3.9.6
* **Platform:** linux-ubuntu18.04-haswell
* **Concretizer:** clingo

Pretty sure this is a bug in the Python package (me, @skosukhin), but pinging @alalazo so he is aware.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
Current workaround is to set `SPACK_PYTHON=/usr/bin/python3` to avoid using the conda python.

**Comment by alalazo** [comment]
@adamjstewart Is this solved with #22720? Bootstrapping from binaries should not use `libpython*.a`

**Comment by adamjstewart** [comment]
@alalazo not really. We don't seem to have binaries for Python 2, although the bootstrap is working for Python 3. Also, this is a more general problem that likely affects many aspects of Spack when using Anaconda Python as an external package.

**Comment by alalazo** [comment]
> We don't seem to have binaries for Python 2,

We do have them, and they are tested on Ubuntu, see [here](https://github.com/spack/spack/runs/3396267926?check_suite_focus=true)

**Comment by adamjstewart** [comment]
We don't seem to have binaries for Python 2 on macOS?

**Comment by alalazo** [comment]
That's correct. For MacOS we have Python 3.5-3.9. I was reading the output of `spack debug report` and wondering if something was wrong on Ubuntu.

**Comment by adamjstewart** [comment]
The original error was encountered on Ubuntu with Python 3. Binary bootstrapping should solve that, although it won't solve people trying to use external Python packages.

**Comment by alalazo** [comment]
> Binary bootstrapping should solve that, although it won't solve people trying to use external Python packages.

True, but this issue is specific to clingo and bootstrapping. I'm fine changing its scope, but we should modify the title and labels I guess.

**Comment by adamjstewart** [comment]
The Anaconda installation on macOS has both static and shared libs, so this problem may be specific to Linux.

**Comment by adamjstewart** [comment]
Well, this is really strange:
```python
>>> from distutils.sysconfig import get_config_vars
>>> x = get_config_vars()
>>> x['LIBDIR']
'/anaconda/envs/azureml_py38/lib'
>>> x['LIBPL']
'/anaconda/envs/azureml_py38/lib/python3.9/config-3.9-x86_64-linux-gnu'
>>> x['PYTHONFRAMEWORKPREFIX']
''
>>> x['LDLIBRARY']
'libpython3.9.a'
>>> x['LIBRARY']
'libpython3.9.a'
>>> 'libpython3.9.so' in x.values()
False
>>> 'libpython3.so' in x.values()
False
```
Both `LIBRARY` and `LDLIBRARY` say to use a static lib, but the installation only has shared libs. And there are no other env vars that have the shared libs. I guess we could just check for both and ignore `LDLIBRARY`/`LIBRARY`?

**Comment by adamjstewart** [comment]
I haven't seen anyone else report issues with locating Python libs, so I think I'm going to ignore this until someone other than me has an issue. I usually avoid external Python installations anyway.
