### ISSUE TITLE
`spack style` bootstraps over and over

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#25475]
### Steps to reproduce

As much as I like the fact that `spack style` bootstraps its own dependencies, once is enough. Somehow it reinstalls the python packages multiple times a day for me when I just develop (maybe switching branches etc, but usually I rebase on the develop branch).

And in fact it does inst all the exact same packages:

```
$ spack style
[+] ~/.spack/bootstrap/store/linux-ubuntu20.04-zen2/gcc-10.3.0/py-pycodestyle-2.6.0-q47yo4rnnvdt6okra7wwrgxfu7dbkhnt
==> Installing py-pyflakes-2.2.0-4eexbvasziysjqzbmgf2blyo4vwzbgmw
==> No binary for py-pyflakes-2.2.0-4eexbvasziysjqzbmgf2blyo4vwzbgmw found: installing from source
==> Using cached archive: ~/.spack/source_cache/_source-cache/archive/4a/4a6927b9ca7fc19817176d54b3ee2ee4202f064febdee8624ee8340303cfda7b.tar.gz
==> No patches needed for py-pyflakes
==> py-pyflakes: Executing phase: 'build'
==> py-pyflakes: Executing phase: 'install'
==> Warning: Module file already exists : skipping creation
```

since it shows "Module file already exists", and there are no duplicates in `<bootstrap prefix>/<platform>/<compiler>/*`.

### Error message

none.

### Information on your system

* **Spack:** 0.16.2-3962-c9f4ad27c4
* **Python:** 3.8.11
* **Platform:** linux-ubuntu20.04-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
@vsoch

**Comment by vsoch** [comment]
Is it the same for clingo? The spack style bootstrap doesn't do anything special or different from another bootstrap - so this suggests there is some issue with bootstrapping. They all follow this convention:

```
with spack.bootstrap.ensure_bootstrap_configuration():
    # do stuff
```
So I think we should ping @alalazo

**Comment by alalazo** [comment]
I don't experience the same for clingo. I think one difference is that clingo uses a different function to import a module than the one used here to put an executable into the PATH. I'd wait for #22720 and #24003 to be merged (they'll refactor the bootstrapping logic heavily) and then deal with this issue. Or if #24003 takes longer than expected to be merged I can try to solve it there.

**Comment by alalazo** [comment]
I marked this as low impact as it's for developers only, feel free to raise it to medium if you think it's more severe than that.

**Comment by vsoch** [comment]
@tgamblin let's hold off on spack-bot (at least production deploying) the new version that includes running spack style until this is fixed.

**Comment by haampie** [comment]
Yeah, low impact it is indeed, cause it's reasonably fast anyways.

I don't have a bootstrapped clingo, I have my own spack environment with python, clingo, boto and other deps that spack doesnt bootstrap yet, and that has been working fine for a long time. Maybe I could add the style packages there too and see if that fixes it for me

**Comment by haampie** [comment]
Can't reproduce this.
