### ISSUE TITLE
paraview@5.9.0 +cuda build fails: undefined reference to __cudaRegisterLinkedBinary...

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#25485]
### Steps to reproduce the issue

`paraview@5.9.0 +cuda` build fails w/ **CUDA 11.4** using:
* `spack@develop` (b22728d55c126a0034f70c7331b6fabc4d6ad095 from `Wed Aug 18 09:49:51 2021 +0200`)
* Ubuntu 20.04, GCC 9.3.0
* Ubuntu 18.04, GCC 7.5.0
* RHEL 7, GCC 9.3.0
* RHEL 8, GCC 8.4.1

Concrete spec: [paraview.spec.yaml.txt](https://github.com/spack/spack/files/7008885/paraview.spec.yaml.txt)

Reproduced here using Docker container image `ecpe4s/ubuntu20.04-runner-x86_64:2021-07-01`

```
$> spack mirror add E4S https://cache.e4s.io
$> spack buildcache keys -it

$> spack install --cache-only --include-build-deps --only dependencies -f ./paraview.spec.yaml
OK

$> spack install --no-cache -f ./paraview.spec.yaml
...
==> Installing paraview-5.9.1-5osszynx2x3kddw2qlwqr6lh5vrjmnnk
==> Fetching https://mirror.spack.io/_source-cache/archive/0d/0d486cb6fbf55e428845c9650486f87466efcb3155e40489182a7ea85dfd4c8d.tar.xz
==> No patches needed for paraview
==> paraview: Executing phase: 'cmake'
==> paraview: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

237 errors found in build log:
     41538    /usr/bin/ar qc ../../lib/libvtkPVAdaptorsParticle-pv5.9.a CMakeFiles/AdaptorsParticle.dir/ParticleAdaptor.cxx.o CMakeFiles/AdaptorsParticle.dir/vtkParticlePipeline.cxx
              .o
     41539    /usr/bin/ar q ../../lib/libvtkPVAdaptorsParticle-pv5.9.a CMakeFiles/AdaptorsParticle.dir/cmake_device_link.o
     41540    /usr/bin/ranlib ../../lib/libvtkPVAdaptorsParticle-pv5.9.a
     41541    make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-paraview-5.9.1-5osszynx2x3kddw2qlwqr6lh5vrjmnnk/spack-build-5osszyn'
     41542    [100%] Built target AdaptorsParticle
     41543    /usr/bin/ld: ../../lib/libvtkAcceleratorsVTKmFilters-pv5.9.a(vtkmAverageToCells.cxx.o): in function `__sti____cudaRegisterAll()':
  >> 41544    /tmp/tmpxft_00013e5b_00000000-6_vtkmAverageToCells.cudafe1.stub.c:2587: undefined reference to `__cudaRegisterLinkedBinary_53_tmpxft_00013e5b_00000000_7_vtkmAverageToC
              ells_cpp1_ii_5ab189ac'
     41545    /usr/bin/ld: ../../lib/libvtkAcceleratorsVTKmFilters-pv5.9.a(vtkmAverageToPoints.cxx.o): in function `__sti____cudaRegisterAll()':
  >> 41546    /tmp/tmpxft_00013e56_00000000-6_vtkmAverageToPoints.cudafe1.stub.c:2060: undefined reference to `__cudaRegisterLinkedBinary_54_tmpxft_00013e56_00000000_7_vtkmAverageTo
              Points_cpp1_ii_6442f0a3'
     41547    /usr/bin/ld: ../../lib/libvtkAcceleratorsVTKmFilters-pv5.9.a(vtkmCleanGrid.cxx.o): in function `__sti____cudaRegisterAll()':
  >> 41548    /tmp/tmpxft_00013e63_00000000-6_vtkmCleanGrid.cudafe1.stub.c:630: undefined reference to `__cudaRegisterLinkedBinary_48_tmpxft_00013e63_00000000_7_vtkmCleanGrid_cpp1_i
              i_f7912904'
...
```

### Information on your system

* **Spack:** 0.16.2-3951-b22728d55c
* **Python:** 3.8.5
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** original

### Additional information

Build log: 

@vicentebolea @danlipsa @chuckatkins

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by vicentebolea** [comment]
@eugeneswalker thanks for this report, we do not support CUDA yet in ParaView. Yes, we have the flags in the spack package but  it will not work. We are working  on that (Already have a branch where we got this work) but we are having some issues adding testing infrastructure for this setting. We will release this feature in the coming weeks probably.

**Comment by eugeneswalker** [comment]
Oh! Sounds good. Thank you for quick response! Should I close this issue now? Would you like to keep it open until your branch is merged?

**Comment by vicentebolea** [comment]
@eugeneswalker keep it open, it will be also good to have this for future people intending to use ParaView +CUDA

**Comment by RemiLacroix-IDRIS** [comment]
@vicentebolea: Sorry it's not clear to me whether CUDA is not supported in ParaView in general or in the context of Spack?

**Comment by vicentebolea** [comment]
@RemiLacroix-IDRIS in latest versions of ParaView we do not support CUDA in general. But we will soon support it through VTK-m, it will be unlikely to be iincluded in the next ParaView release but it will be in master sometime later.

**Comment by eugeneswalker** [comment]
I see a conflict has been added:
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/paraview/package.py#L84

Now that this is expressed in the package.py, should we close this? What do you think?

**Comment by vicentebolea** [comment]
@eugeneswalker yes, good catch :) we merged that few days ago.
