### ISSUE TITLE
install OpenGL

### ISSUE THREAD

**Issue by hootthompson** [LLNL/spack#25483]
### Steps to reproduce

(notebook) jovyan@jupyter-jhthomps:~$ spack list | grep opengl
opengl
openglu
(notebook) jovyan@jupyter-jhthomps:~$ spack install opengl
==> Error: There are no valid versions for opengl that match ':'

***
This seems to be the same as issue 17512 which appears to be closed. Are suggestions there still valid? You'll see that I'm running in a Python notebook environment.

### Error message

(notebook) jovyan@jupyter-jhthomps:~$ spack list | grep opengl
opengl
openglu
(notebook) jovyan@jupyter-jhthomps:~$ spack install opengl
==> Error: There are no valid versions for opengl that match ':'
(notebook) jovyan@jupyter-jhthomps:~$ 

### Information on your system

(notebook) jovyan@jupyter-jhthomps:~$ spack debug report
* **Spack:** 0.16.2-3816-8f238c03ad
* **Python:** 3.8.8
* **Platform:** linux-ubuntu20.04-skylake_avx512
* **Concretizer:** original

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
`opengl` is an external-only package. Spack can't install it because it requires hardware drivers. If `opengl` is already installed, you can add it as an external package. If not, you can try another `gl` provider like `mesa`.

**Comment by hootthompson** [comment]
Ok, thank you very much for the response!

Hoot

From: "Adam J. Stewart" ***@***.***>
Reply-To: spack/spack ***@***.***>
Date: Thursday, August 19, 2021 at 12:29 PM
To: spack/spack ***@***.***>
Cc: hootthompson ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [spack/spack] install OpenGL (#25483)


opengl is an external-only package. Spack can't install it because it requires hardware drivers. If opengl is already installed, you can add it as an external package. If not, you can try another gl provider like mesa.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fspack%2Fspack%2Fissues%2F25483%23issuecomment-902057867&data=04%7C01%7Cjohn.h.thompson%40nasa.gov%7Cda99f1938e5b44474f0408d9632e8e0e%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637649873874170152%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CWTflzDP78NPi%2B8yv6IP9kTNHdG8K%2BgDenE9cbkWk3k%3D&reserved=0>, or unsubscribe<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAF6ODTTXH7BWUGO2PRJBXHLT5UWPJANCNFSM5CMM4VIQ&data=04%7C01%7Cjohn.h.thompson%40nasa.gov%7Cda99f1938e5b44474f0408d9632e8e0e%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637649873874180110%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=t6ZvkS%2FBQ%2FjQZbrJI189Bk88cd0S9MPvJO9GZyuQ8%2Fg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Cjohn.h.thompson%40nasa.gov%7Cda99f1938e5b44474f0408d9632e8e0e%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637649873874180110%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=r6hR8Gtq3DCiB6o4InU82cy9%2BKQbGSLLonQ4IxzXFfw%3D&reserved=0> or Android<https://gcc02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26utm_campaign%3Dnotification-email&data=04%7C01%7Cjohn.h.thompson%40nasa.gov%7Cda99f1938e5b44474f0408d9632e8e0e%7C7005d45845be48ae8140d43da96dd17b%7C0%7C0%7C637649873874190066%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Yilwj0Stp7hLl5zBSdog9%2FkjwWpH18riMFhAanNUlQw%3D&reserved=0>.
