### ISSUE TITLE
Environments reread, which complicates scripting

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#25532]
### Steps to reproduce

Create an env in `cd $(mktemp -d)`:

```yaml
spack:
  view: true
  specs: [zlib]
  config:
    install_tree:
      root: ./here
```

Run `spack python`

```python
In [1]: from spack.environment import Environment, activate
In [2]: e = Environment(".")
In [3]: activate(e)
In [4]: e.concretize()
In [5]: e.install_all()
In [6]: e.all_specs()
Out[7]: []
```

And `all_specs()` is empty, because `install_all()` rereads the spack.yaml file from disk right here: 

https://github.com/spack/spack/blob/d52a1b8279bb7515669ae3bc6cf6dd5f6f6fca08/lib/spack/spack/environment.py#L1534

and no spack.lock was stored because I didn't call `e.write()` anywhere.

It'd be great if these simple operations did not depend on the filesystem at all... Clearly views write to the environment, but arbitrarily "clearing" the current environment and de-serializing it from disk is very unexpected.

### Error message

none

### Information on your system

* **Spack:** 0.16.2-3959-220a87812c
* **Python:** 3.8.11
* **Platform:** linux-ubuntu20.04-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
@alalazo this ties in to our conversation today:

It'd be nice if we keep track of a list of changes/actions applied to the in-memory representation of an environment, say `env.actions = [...]`, and then whenever a spack.yaml/lock needs to be persisted to disk for whatever reason, and the underlying spack.yaml has changed, we can instantiate an Environment object from disk, apply env.actions, and persist.

**Comment by tgamblin** [comment]
I think fixing this would be good, but don't have the cycles -- is this something you want to tackle @haampie?

**Comment by alalazo** [comment]
This bug was fixed at some point:
![Screenshot from 2023-05-03 09-43-13](https://user-images.githubusercontent.com/4199709/235858362-f2a9be6f-3bfd-47ed-aa09-81289e93cd1e.png)
