### ISSUE TITLE
Option to keep all build files to help debug

### ISSUE THREAD

**Issue by BarrySmith** [LLNL/spack#2553]
Forgive me for asking a question that is probably answered elsewhere but I could not find it.

Is there an option that forces spack to keep all the build directories for packages that it thinks have built correctly? I have a failure that is impossible to debug since spack seems to clean out all the build directories thinking the build was successful. I know the build was not successful because some files that should be installed are not installed.

**Comment by davydden** [comment]
You can run `spack install --keep-stage` to keep the stage. If you need it to exist after the rester of computer, then according to [documentation](http://spack.readthedocs.io/en/latest/configuration.html), you should be able to specify in `config.yaml`
```
build_stage:
  - path/to/spack/var/spack/stage
```
to avoid using temporary folder provided by OS.

**Comment by BarrySmith** [comment]
Works. Thanks!

**Comment by tgamblin** [comment]
@BarrySmith: I dunno if you just stick Spack in your path or source the `setup-env.sh` script, but if you source the script, you can get straight to the build directory with `spack cd`:

```console
$ spack install foo
    # ... build build build
    # error
$ spack cd foo
    # now you're in the failed build directory
```

Note that Spack doesn't delete the build directory if the build fails; only if it succeeds.  So you don't need `--keep-stage` unless it's succeeding but something's going wrong during the build.

Spack *will* delete the install prefix if the build fails.  You can override that with `spack install --keep-prefix` if you need to debug what the build puts there, but remember to delete it manually once you inspect it, as Spack will raise an error when it discovers your prefix already exists before installation on the next run.
