### ISSUE TITLE
Override scope for `spack install`

### ISSUE THREAD

**Issue by spenpw** [LLNL/spack#25547]
### Summary

When running the `spack install` command, an option should be available to specify a configuration scope from which to get build settings.

### Rationale

When an administrator is installing a package globally for all users on a system to access, but the administrator has a `~/.spack` directory containing configuration files for their own local packages, there is no way to install globally without removing or renaming the `~/.spack` directory.

### Description

I propose adding a `--scope=<scope>` flag to the `spack install` command that would allow a user to specify the configuration scope to pull variables from. If the flag is not provided, the current method should be used as the default.

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
Would it work if you use:
```console
$ spack -C <config-dir> ...
```
and start each config with a double colon? Alternatively (and for reproducibility) you can also use an environment with all the needed configuration pulled in.

**Comment by spenpw** [comment]
Could you point me to documentation on the double colon? I'm not familiar with what that does.

Additionally, figured I should mention that this was discussed briefly in Slack: https://spackpm.slack.com/archives/C5W7NKZJT/p1629385848289600.

**Comment by alalazo** [comment]
> Could you point me to documentation on the double colon? I'm not familiar with what that does.

Sure, see [here](https://spack.readthedocs.io/en/latest/configuration.html#overriding-entire-sections)

**Comment by spenpw** [comment]
So I think that `spack install -C /etc/spack` would be a sort of hacky way to make this work, but it would be nice to be able to essentially skip config levels from the command line. I would be interested in taking a crack at implementing a `--scope` flag for `spack install`. Is this a good idea?
