### ISSUE TITLE
spack clean -b: failure on macOS

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#25566]
### Steps to reproduce

```console
$ spack clean -b
```

### Error message

```console
$ spack -d clean -b
==> [2021-08-23-09:54:38.705254] Imported clean from built-in commands
==> [2021-08-23-09:54:38.706919] Imported clean from built-in commands
==> [2021-08-23-09:54:38.707769] Reading config file /Users/Adam/spack/etc/spack/defaults/bootstrap.yaml
==> [2021-08-23-09:54:38.724000] Removing software in "/Users/Adam/.spack/bootstrap/store"
==> [2021-08-23-09:54:38.725467] Reading config file /Users/Adam/spack/etc/spack/defaults/config.yaml
==> [2021-08-23-09:54:38.757834] Reading config file /Users/Adam/.spack/config.yaml
==> [2021-08-23-09:54:38.759907] DATABASE LOCK TIMEOUT: 3s
==> [2021-08-23-09:54:38.760091] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-08-23-09:54:38.761110] DATABASE LOCK TIMEOUT: 3s
==> [2021-08-23-09:54:38.761205] PACKAGE LOCK TIMEOUT: No timeout
==> [2021-08-23-09:54:38.763398] Imported uninstall from built-in commands
==> [2021-08-23-09:54:38.764275] Imported uninstall from built-in commands
Traceback (most recent call last):
  File "/Users/Adam/spack/bin/spack", line 100, in <module>
    sys.exit(spack.main.main())
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 797, in main
    return _invoke_command(command, parser, args, unknown)
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 525, in _invoke_command
    return_val = command(parser, args)
  File "/Users/Adam/spack/lib/spack/spack/cmd/clean.py", line 109, in clean
    uninstall('-a', '-y')
  File "/Users/Adam/spack/lib/spack/spack/main.py", line 599, in __call__
    raise SpackCommandError(
spack.main.SpackCommandError: Command exited with code 1: uninstall('-a', '-y')
```

### Information on your system

* **Spack:** 0.16.2-4008-2971a630b8
* **Python:** 3.8.11
* **Platform:** darwin-catalina-ivybridge
* **Concretizer:** clingo

@alalazo 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
I know what this is: a spec in the bootstrap store occurs in some named environment. Spack can't know from an environment file what database it belongs to, so uninstall errors with a false positive. It could be solved by running with `-f`.

**Comment by haampie** [comment]
The general issue is https://github.com/spack/spack/issues/25203, but we can solve this one apart from it.

**Comment by alalazo** [comment]
Does #25607 solve this issue?

**Comment by adamjstewart** [comment]
I'm actually no longer able to reproduce the original issue anymore lol. I `rm -rf`'ed the entire directory and upgraded Spack so maybe it was a bug specific to the from-source bootstrapping or something?

**Comment by alalazo** [comment]
@adamjstewart Going to close this, but feel free to reopen if you can find a reproducer.
