### ISSUE TITLE
Get rid of `type='nolink'`?

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#2558]
@tgamblin @davydden There's been a proposal to get rid of `depends_on(..., type='nolink')` and replace it with `depends_on(..., type='build,run')`.  So far, there seems to be consensus that this is a good change.  Does anyone wish to provide further discussion?

**Comment by alalazo** [comment]
I think this change will help keep things consistent in the long run. If we extend the types of dependencies to e.g. `test` or any other new type, then the name `nolink` will be wrong and should read `nolink_notest` etc. Having `build,run` instead requires no modification in case any extension is added.

**Comment by becker33** [comment]
I agree with the proposed change as well.

**Comment by citibeth** [comment]
Great!  There is unanimous consent on this issue.  Now somebody just needs
to do it...

**Comment by scheibelp** [comment]
FYI I'll likely do this as part of https://github.com/LLNL/spack/pull/2548 (and I'll add a TODO there)

**Comment by adamjstewart** [comment]
`type='nolink'` has been gone for a while now.
