### ISSUE TITLE
`spack clean -b` may remove specs from environment

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#25603]
### Steps to reproduce

`spack clean -b` calls

https://github.com/spack/spack/blob/f6a9ef5ef51630969635f9068e3420dd4dadc86f/lib/spack/spack/cmd/clean.py#L108-L109

but uninstall is environment aware, and the environment is not deactivated in the 'bootstrap context', so we run:

https://github.com/spack/spack/blob/f6a9ef5ef51630969635f9068e3420dd4dadc86f/lib/spack/spack/cmd/uninstall.py#L326-L332

We shouldn't do this...

### Error message

.

### Information on your system

.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Marked as impact low as we switch the store before doing this, so we don't uninstall anything from the environment :disappointed_relieved: Anyhow, calling `spack clean -b` with an active environment results in wrong output:
```console
$ spack find -b
==> Showing internal bootstrap store at "/home/culpo/.spack/bootstrap/store"
==> In environment /home/culpo/tmp/spackclean
==> Root specs
zlib

==> 0 installed packages
```
and in the bootstrap store not being cleaned.

**Comment by haampie** [comment]
It still calls `_remove_from_env` which can remove something from the specs section of an environment file.

**Comment by alalazo** [comment]
That's true, but it removes that only after uninstall and the chances `clingo-bootstrap@spack` is in an environment are low, I think. I can raise this to `impact-medium` if it seems more appropriate. A draft fix has been submitted already, just waiting for the tests to complete.

**Comment by haampie** [comment]
hehe, i have such an environment :p but yeah. I don't know how it works for dependencies (like zlib), makes me think about @adamjstewart's issue: #25566
