### ISSUE TITLE
Installation issue (Spack 0.16.2): CDO

### ISSUE THREAD

**Issue by adrfantini** [LLNL/spack#25677]
### Steps to reproduce the issue

```
$ spack install cdo
==> Error: Package Ncurses has no version with a URL.
```

### Information on your system

* **Spack:** 0.16.0
* **Python:** 3.9.6
* **Platform:** linux-archrolling-skylake

### Additional information

No .log or .txt files exist in the build directory.

Spack was just installed, no other package is installed.

@skosukhin 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [ ] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Are you using a newer version of the `ncurses` package with an older version of Spack?

**Comment by adrfantini** [comment]
I have not installed `ncurses`, CDO is the first package I tried to install. I'm guessing it's pulling in `ncurses` as a dep? The output does not specify anything. Spack is 0.16.0 (latest version on AUR), so not the latest, maybe that could be the issue.

**Comment by adamjstewart** [comment]
Can you try:
```console
$ spack -d --stacktrace install cdo
```
That may help pinpoint the issue. Also, can you try to reproduce the issue on develop?

**Comment by adrfantini** [comment]
Sure:
https://pastebin.com/8NHEWLbT

**Comment by adamjstewart** [comment]
@tgamblin @alalazo may want to look at this. Even if the package didn't have a URL it still shouldn't fail.

**Comment by tgamblin** [comment]
@adrfantini any chance you can try with 0.16.2? e.g.:

```
git clone https://github.com/spack/spack
cd spack
git checkout v0.16.2
. share/spack/setup-env.sh
spack install cdo 
```

**Comment by adrfantini** [comment]
Sure thing! Tested with the latest 0.16.2:
https://pastebin.com/izv50RTq

Spoiler: still does not work :(

**Comment by rblake-llnl** [comment]
I'm hitting this same bug with python 3.9.7 on Mac OS X Big Sur.

**Comment by rblake-llnl** [comment]
Confirming that everything works-for-me on develop.

**Comment by scheibelp** [comment]
I can replicate this error on my Mac with v0.16.0 by installing and using python@3.9.6 - I'll see if I can figure out a fix tomorrow

**Comment by adamjstewart** [comment]
Is this fixed by #24686?

**Comment by rblake-llnl** [comment]
```releases/v0.16``` currently fixes this issue.

**Comment by adamjstewart** [comment]
Yes, #24686 has been backported to `releases/v0.16` and `v0.16.3` should be coming soon I believe.

**Comment by scheibelp** [comment]
I've added this to the v0.16.3 release project and this can be closed whenever that is finished

**Comment by hpcnpatel** [comment]
Sharing our experience using an older Spack 0.15.4.

We faces a similar problem described here, 

$ spack install gcc arch=linux-sles15-x86_64
==> Error: Package Libsigsegv has no version with a URL.

This is the debug report,

$ spack debug report
* **Spack:** 0.15.4
* **Python:** 3.6.15
* **Platform:** linux-sles15-haswell

Implementing the https://github.com/spack/spack/pull/24686 locally fixes this issue for us.

Reason to use the older Spack: We provide an extensive software stack to the users. For reproducing the exact software versions and settings for that software stack rollout, we freeze all the configs and setting ( including the spack version).
