### ISSUE TITLE
Installation issue: paraview %gcc@11.1.0

### ISSUE THREAD

**Issue by kjrstory** [LLNL/spack#25687]
### Steps to reproduce the issue

```console
$spack install paraview@5.9.1+qt %gcc11.1.0 
```

I compiled Paraview with gcc11.1.0, and the following error occurred.
missing includes: error: ‘numeric_limits’ is not a member of ‘std’
So I found https://www.gnu.org/software/gcc/gcc-11/porting_to.html.

> ### Header dependency changes 
> Some C++ Standard Library headers have been changed to no longer include other headers that they do need to depend on. As such, C++ programs that used standard library components without including the right headers will no longer compile.
> The following headers are used less widely in libstdc++ and may need to be included explicitly when compiled with GCC 11:
> 
> *  **<limits\> (for std::numeric_limits)**
> *  <memory\> (for std::unique_ptr, std::shared_ptr etc.)
> *  <utility\> (for std::pair, std::tuple_size, std::index_sequence etc.)
> *  <thread\> (for members of namespace std::this_thread.)

I think the solution.
Files using "std:numeric_limits" should include this line "#include \<limits\>".
Is there anyone who can make this patch?
Do you have a guide how to make about patch?

```console
...
/tmp/root/spack-stage/spack-stage-paraview-5.9.1-j7r624x4zdefpuufopsv2ln4ntg5gfau/spack-src/VTK/Common/Core/vtkGenericDataArrayLookupHelper.h:52:26: error: 'numeric_limits' is not a member of 'std'
/tmp/root/spack-stage/spack-stage-paraview-5.9.1-j7r624x4zdefpuufopsv2ln4ntg5gfau/spack-src/VTK/Common/Core/vtkGenericDataArrayLookupHelper.h:52:26: error: 'numeric_limits' is not a member of 'std'
/tmp/root/spack-stage/spack-stage-paraview-5.9.1-j7r624x4zdefpuufopsv2ln4ntg5gfau/spack-src/VTK/Common/Core/vtkGenericDataArrayLookupHelper.h:52:42: error: template argument 2 is invalid
/tmp/root/spack-stage/spack-stage-paraview-5.9.1-j7r624x4zdefpuufopsv2ln4ntg5gfau/spack-src/VTK/Common/Core/vtkDataArrayPrivate.txx:97:31: error: 'numeric_limits' is not a member of 'std'
/tmp/root/spack-stage/spack-stage-paraview-5.9.1-j7r624x4zdefpuufopsv2ln4ntg5gfau/spack-src/VTK/Common/Core/vtkDataArrayPrivate.txx:97:31: error: 'numeric_limits' is not a member of 'std'
/tmp/root/spack-stage/spack-stage-paraview-5.9.1-j7r624x4zdefpuufopsv2ln4ntg5gfau/spack-src/VTK/Common/Core/vtkDataArrayPrivate.txx:97:47: error: template argument 2 is invalid
/tmp/root/spack-stage/spack-stage-paraview-5.9.1-j7r624x4zdefpuufopsv2ln4ntg5gfau/spack-src/VTK/Common/Core/vtkGenericDataArrayLookupHelper.h:52:26: error: 'numeric_limits' is not a member of 'std'
/tmp/root/spack-stage/spack-stage-paraview-5.9.1-j7r624x4zdefpuufopsv2ln4ntg5gfau/spack-src/VTK/Common/Core/vtkGenericDataArrayLookupHelper.h:52:26: error: 'numeric_limits' is not a member of 'std'
/tmp/root/spack-stage/spack-stage-paraview-5.9.1-j7r624x4zdefpuufopsv2ln4ntg5gfau/spack-src/VTK/Common/Core/vtkGenericDataArrayLookupHelper.h:52:42: error: template argument 2 is invalid
...
```

### Information on your system

* **Spack:** 0.16.2-4035-4ddc0ff
* **Python:** 3.6.8
* **Platform:** linux-centos7-cascadelake
* **Concretizer:** original

### Additional information
[spack-build-01-cmake-out.txt](https://github.com/spack/spack/files/7073990/spack-build-01-cmake-out.txt)
[spack-build-02-build-out.txt](https://github.com/spack/spack/files/7073991/spack-build-02-build-out.txt)

@chuckatkins
@danlipsa
@vicentebolea

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by danlipsa** [comment]
Look in /home/danlipsa/projects/spack/var/spack/repos/builtin/packages/paraview/package.py
There are several patches already for various versions and reasons. You can add another one that fixes those headers. Another option is to downgrade the compiler %gcc7.4.0 for instance.

**Comment by kjrstory** [comment]
I already compiled paraview %gcc@7.5.0, but it is necessary to compile to gcc11 version for the future use.
I checked the existing paraview patch files as danlipsa said.
I found that the patch file was made using the 'git diff' command.
Using this, I succeeded in compiling paraview@5.9.1 with gcc11 version.
I will make sure that other versions of the paraview are the same. After this check, I'll commit patch.

**Comment by kjrstory** [comment]
I checked that the patch I made works in paraview 5.9.1 version but not in other paraview version.
This is because the position where the "#include \<limits\>" enters is different depending on the version.
In other words, I have to create a patch file for each paraview version, It will be be too complicated.
Instead, it seems to have to use patch function or let the gcc version fall below 11.

**Comment by danlipsa** [comment]
I think it is reasonable to say that older versions of paraview require older versions of gcc and only patch 5.9.1 for gcc 11 as a first step. If someone needs an older paraview compiled with gcc 11 they can add their own patch.

**Comment by vicentebolea** [comment]
This has been an issue in other packages for Paraview 5.9.1. Here is the patch at the OpenSUSE build system https://build.opensuse.org/package/view_file/science/paraview/paraview-gcc11-limits.patch?expand=1
