### ISSUE TITLE
Installation issue: trilinos~kokkos fails

### ISSUE THREAD

**Issue by KineticTheory** [LLNL/spack#25686]
### Steps to reproduce the issue

```console
$ spack install trilinos~kokkos
```

Annoyingly, the above command fails.  I must actually run 

```console
$ spack install trilinos~kokkos~tpetra~amesos2~ifpack2

5 errors found in build log:
     2659                     from /tmp/kellyt/spack-stage/spack-stage-trilinos-13.0.1-maqit3jlyebeuwg4f6ggnk3l55icglm6/spack-src/packages/muelu/src/Interface/MueLu_Pa
             rameterListInterpreter_def.hpp:74,
     2660                     from /tmp/kellyt/spack-stage/spack-stage-trilinos-13.0.1-maqit3jlyebeuwg4f6ggnk3l55icglm6/spack-build-maqit3j/packages/muelu/src/Interfac
             e/MueLu_ParameterListInterpreter.hpp:2,
     2661                     from /tmp/kellyt/spack-stage/spack-stage-trilinos-13.0.1-maqit3jlyebeuwg4f6ggnk3l55icglm6/spack-src/packages/muelu/adapters/xpetra/MueLu_
             CreateXpetraPreconditioner.hpp:24,
     2662                     from /tmp/kellyt/spack-stage/spack-stage-trilinos-13.0.1-maqit3jlyebeuwg4f6ggnk3l55icglm6/spack-src/packages/muelu/adapters/xpetra/MueLu_
             RefMaxwell_def.hpp:98,
     2663                     from /tmp/kellyt/spack-stage/spack-stage-trilinos-13.0.1-maqit3jlyebeuwg4f6ggnk3l55icglm6/spack-build-maqit3j/packages/muelu/src/MueLu_Re
             fMaxwell.hpp:2,
     2664                     from /tmp/kellyt/spack-stage/spack-stage-trilinos-13.0.1-maqit3jlyebeuwg4f6ggnk3l55icglm6/spack-src/packages/muelu/adapters/aztecoo/MueLu
             _AztecEpetraOperator.cpp:8:
  >> 2665    /tmp/kellyt/spack-stage/spack-stage-trilinos-13.0.1-maqit3jlyebeuwg4f6ggnk3l55icglm6/spack-src/packages/muelu/src/Graph/PairwiseAggregation/MueLu_NotayAgg
             regationFactory_def.hpp:55:10: fatal error: KokkosKernels_Handle.hpp: No such file or directory
     2666       55 | #include "KokkosKernels_Handle.hpp"
     2667          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
     2668    compilation terminated.
     2669    In file included from /tmp/kellyt/spack-stage/spack-stage-trilinos-13.0.1-maqit3jlyebeuwg4f6ggnk3l55icglm6/spack-build-maqit3j/packages/muelu/src/MueLu_No
             tayAggregationFactory.hpp:2,
     2670                     from /tmp/kellyt/spack-stage/spack-stage-trilinos-13.0.1-maqit3jlyebeuwg4f6ggnk3l55icglm6/spack-src/packages/muelu/src/Interface/MueLu_Fa
             ctoryFactory_decl.hpp:109,
     2671                     from /tmp/kellyt/spack-stage/spack-stage-trilinos-13.0.1-maqit3jlyebeuwg4f6ggnk3l55icglm6/spack-build-maqit3j/packages/muelu/src/Interfac
             e/MueLu_FactoryFactory.hpp:1,
     2672                     from /tmp/kellyt/spack-stage/spack-stage-trilinos-13.0.1-maqit3jlyebeuwg4f6ggnk3l55icglm6/spack-src/packages/muelu/src/Interface/MueLu_Pa
             rameterListInterpreter_def.hpp:74,
     2673                     from /tmp/kellyt/spack-stage/spack-stage-trilinos-13.0.1-maqit3jlyebeuwg4f6ggnk3l55icglm6/spack-build-maqit3j/packages/muelu/src/Interfac
             e/MueLu_ParameterListInterpreter.hpp:2,
     2674                     from /tmp/kellyt/spack-stage/spack-stage-trilinos-13.0.1-maqit3jlyebeuwg4f6ggnk3l55icglm6/spack-src/packages/muelu/adapters/xpetra/MueLu_
             CreateXpetraPreconditioner.hpp:24,
     2675                     from /tmp/kellyt/spack-stage/spack-stage-trilinos-13.0.1-maqit3jlyebeuwg4f6ggnk3l55icglm6/spack-src/packages/muelu/adapters/epetra/MueLu_
             CreateEpetraPreconditioner.cpp:14:
  >> 2676    /tmp/kellyt/spack-stage/spack-stage-trilinos-13.0.1-maqit3jlyebeuwg4f6ggnk3l55icglm6/spack-src/packages/muelu/src/Graph/PairwiseAggregation/MueLu_NotayAgg
             regationFactory_def.hpp:55:10: fatal error: KokkosKernels_Handle.hpp: No such file or directory
     2677       55 | #include "KokkosKernels_Handle.hpp"
     2678          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
     2679    compilation terminated.
  >> 2680    make[2]: *** [packages/muelu/adapters/CMakeFiles/muelu-adapters.dir/build.make:98: packages/muelu/adapters/CMakeFiles/muelu-adapters.dir/epetra/MueLu_Crea
             teEpetraPreconditioner.cpp.o] Error 1
     2681    make[2]: *** Waiting for unfinished jobs....
  >> 2682    make[2]: *** [packages/muelu/adapters/CMakeFiles/muelu-adapters.dir/build.make:111: packages/muelu/adapters/CMakeFiles/muelu-adapters.dir/aztecoo/MueLu_Az
             tecEpetraOperator.cpp.o] Error 1
     2683    make[2]: Leaving directory '/tmp/kellyt/spack-stage/spack-stage-trilinos-13.0.1-maqit3jlyebeuwg4f6ggnk3l55icglm6/spack-build-maqit3j'
  >> 2684    make[1]: *** [CMakeFiles/Makefile2:4775: packages/muelu/adapters/CMakeFiles/muelu-adapters.dir/all] Error 2
     2685    make[1]: Leaving directory '/tmp/kellyt/spack-stage/spack-stage-trilinos-13.0.1-maqit3jlyebeuwg4f6ggnk3l55icglm6/spack-build-maqit3j'
     2686    make: *** [Makefile:185: all] Error 2
```

cc maintainers: @keitat @kuberry @sethrj 

### Information on your system

```console 
$ spack debug report
* **Spack:** 0.16.2-4032-85f10adaff
* **Python:** 3.6.8
* **Platform:** linux-rhel8-broadwell
* **Concretizer:** original
```

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/7073332/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7073333/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by sethrj** [comment]
Looks like Meulu might also require Kokkos. Trilinos config options have a huge parameter space that is barely explored so it's hard to know what options will work. Can't investigate for another week but try disabling muelu as well?

**Comment by KineticTheory** [comment]
> Looks like Meulu might also require Kokkos. Trilinos config options have a huge parameter space that is barely explored so it's hard to know what options will work. Can't investigate for another week but try disabling muelu as well?

I've already tried `~muelu` with the combo I listed above but that didn't fix the build failure.  

As you say, there is a huge combinatorial space for trilinos variants and it is difficult to capture all of the bad-combinations.  It is interesting that the trilinos build system didn't catch this conflict when running cmake.

For now, my work around is to build the `+kokkos` version as this installation works for me.  I don't need kokkos and this variant makes the trilinos build take more time, but I have something that will work for now!

**Comment by kuberry** [comment]
I'm not sure if the goal of the spack recipe is to attempt to capture every possible conflicting combination (thoughts @sethrj , @keitat) of Trilinos subpackages  (can vary from version to version of Trilinos). I think if **either** the concretizer indicates the conflict or Tribits does, this is desired behavior. The error you are seeing is because `muelu` (specifically `muelu/src/Graph/PairwiseAggregation/MueLu_NotayAggregationFactory_def.hpp`) also requires `kokkos`. This isn't captured in the spack recipe or in Tribits in Trilinos. 

Can you confirm again that running:
`spack install trilinos~kokkos~tpetra~ifpack2~amesos2~muelu`
doesn't work? I tried this, and it worked for me. 

Regardless, `muelu` requires either `tpetra` and `kokkos` or neither. You are right that Tribits _should_ catch this, but it seems that there are .hpp files that rely on Kokkos without Kokkos being in the required set of packages for `muelu`. Under certain configurations, it is possible to build `muelu` without `kokkos` or `tpetra`, but then other issues pop up in `stratimikos`. I'm not sure that `muelu` without `tpetra` and `kokkos` is a tested combination. I suggest addition of a conflict to the recipe indicating that `muelu` relies on `tpetra` (which in turn already relies on `kokkos`). See  https://github.com/spack/spack/pull/25703.

**Comment by KineticTheory** [comment]
@kuberry I really thought I had reproduced this error with `spack install trilinos~kokkos~tpetra~ifpack2~amesos2~muelu`, but I just tried it and it is building correctly. (sigh). I must have had some left over files in the build directory when I got the bad result.

The original command that failed (and continues to fail) is:
`spack install trilinos@12.18.1+superlu-dist~kokkos~tpetra~ifpack2~amesos2~muelu^superlu-dist@5.4.0`

I'm not sure why enabling `+superlu-dist` would cause this failure.  The logic looks orthogonal.  This is for an older version of trilinos because our software is still using superlu-dist@5 APIs (not through trilinos) and the newest trilinos is no longer compatible with this version of `superlu-dist`.  This version diff might also contribute to the error.

**Comment by keitat** [comment]
Adding @jhux2 @bartlettroscoe

**Comment by bartlettroscoe** [comment]
I am shocked this even configures.

**Comment by KineticTheory** [comment]
> 
> 
> I am shocked this even configures.

We've been using that line for several years w/o issue!

**Comment by bartlettroscoe** [comment]
> We've been using that line for several years w/o issue!

So you have been building the Epetra-only stack in Trilinos?  (That is what you get if you disable Kokkos and Tpetra basically.)   I don't think there is much, if any, automated testing to ensure that the Epetra-only stack works in Trilinos these days (or this configuration would still be working).  It is just the opposite, they want the Epetra stack to go away and to get everyone to move over to the newer Kokkos/Tpetra-based stack.  So they likely want you to be building `trilinos~epetra` if anything.  But I really should not be commenting on official Trilinos policy.  I will let the other Trilinos developers CCed on this issue do that.

**Comment by KineticTheory** [comment]
> 
> 
> > We've been using that line for several years w/o issue!
> 
> So you have been building the Epetra-only stack in Trilinos? (That is what you get if you disable Kokkos and Tpetra basically.) I don't think there is much, if any, automated testing to ensure that the Epetra-only stack works in Trilinos these days (or this configuration would still be working). It is just the opposite, they want the Epetra stack to go away and to get everyone to move over to the newer Kokkos/Tpetra-based stack. So they likely want you to be building `trilinos~epetra` if anything. But I really should not be commenting on official Trilinos policy. I will let the other Trilinos developers CCed on this issue do that.

Yep. We started using it in 2003 or 2004 and are still using it today. I'll relay your comments to the main code team, but my understanding is that they aren't ready to adopt the Kokkos/Tpetra-based stack yet.

**Comment by sethrj** [comment]
> I am shocked this even configures.

This is my feeling anytime I build trilinos 😂😂😅

**Comment by kuberry** [comment]
So a quick recap. The recipe does now work for @KineticTheory, once they add `~muelu`. MueLu does have a **required** dependency on Kokkos in Tribits that is currently listed as **optional**. 

I can follow up with the MueLu team to see whether they are intending to support a Tpetra+Kokkos free build or not. If they are not, then PR #25703 should be merged, disabling an Epetra only build path for MueLu. If they are trying to, then I'll need to look into whether it is some other configuration option in the recipe causing the issue or a bug on their end.

https://github.com/trilinos/Trilinos/issues/9648

**Comment by kuberry** [comment]
Follow up: Based on issue https://github.com/trilinos/Trilinos/pull/9532, I was referred to PR https://github.com/trilinos/Trilinos/pull/9532. 

MueLu is going full Kokkos. I suggest we approve PR https://github.com/spack/spack/pull/25703.

**Comment by keitat** [comment]
> > We've been using that line for several years w/o issue!
> 
> So you have been building the Epetra-only stack in Trilinos? (That is what you get if you disable Kokkos and Tpetra basically.) I don't think there is much, if any, automated testing to ensure that the Epetra-only stack works in Trilinos these days (or this configuration would still be working). It is just the opposite, they want the Epetra stack to go away and to get everyone to move over to the newer Kokkos/Tpetra-based stack. So they likely want you to be building `trilinos~epetra` if anything. But I really should not be commenting on official Trilinos policy. I will let the other Trilinos developers CCed on this issue do that.

FYI: One of major Trilinos user, deal.II library, is still using 1st generation library packages.  If necessary, I will assist them to introduce the 2nd gen packages.  deal.II is xSDK member library... it's kind of urgent.

**Comment by keitat** [comment]
@KineticTheory @kuberry  I will add `~zoltan2` because it is 2nd generation libraries.  Are you using "develop" branch?

**Comment by kuberry** [comment]
@keitat, is what you mean that you are going to add `~zoltan2` to the deal.II recipe for calling Trilinos? Do you want to start an issue/PR for not building unused 2nd gen Trilinos packages in deal.II? (maybe link it to this issue and ping me?) Also, when you ask if I'm using 'develop' branch, do you mean on Trilinos?

You could immediately consider adding `~amesos2~ifpack2~zoltan2~muelu` to the deal.II recipe calling Trilinos, since deal.II isn't using 2nd gen packages anyway (a waste to build them).

deal.II has a decent amount of documentation regarding how things are called in Trilinos. Will this start as a deal.II PR to move to 2nd gen and then later become a spack PR to change the recipe?

**Comment by KineticTheory** [comment]
The projects I work with will continue to use the 1st generation library packages like Epetra (at least for another year).  We just need the ability to build those with spack (even if the spack build requires `+kokkoks`),   This discussion has been useful for me and I will communicate with the teams that migrating to the 2nd gen solvers should be scheduled.  

I'm okay closing this issue whenever it seems appropriate.

**Comment by kuberry** [comment]
@KineticTheory you should be fine doing what you did along with `~muelu` going forward, i.e. 
`trilinos~kokkos~tpetra~amesos2~ifpack2~muelu`.

**Comment by keitat** [comment]
@kuberry Currently, we include all important 2nd-gen libraries in deal.ii because we need to maintain the xSDK interoperability (deal.II is an xSDK member package).  I am curious if there is a way to enforce the inclusion of 1st gen libraries from package.py of deal.II or create a special Trilinos build just for deal.II.

**Comment by keitat** [comment]
@kuberry Previously, I observed adding `~zoltan2` is required when removing Kokkos (or building 1st-gen only library) when using Spack **develop** branch.  Do we see this problem? Maybe, it's gone.

As for deal.II, let me clarify. I am just telling that there are still some major Trilinos users relying on the 1st gen Trilinos libraries.  From the xSDK perspective, it is OK with the current package.py of deal.II for the time being.   Eventually, they have to change to 2nd gen libraries to utilize heterogenous computing platforms.

**Comment by kuberry** [comment]
> @kuberry Previously, I observed adding `~zoltan2` is required when removing Kokkos (or building 1st-gen only library) when using Spack **develop** branch. Do we see this problem? Maybe, it's gone.
> 
> As for deal.II, let me clarify. I am just telling that there are still some major Trilinos users relying on the 1st gen Trilinos libraries. From the xSDK perspective, it is OK with the current package.py of deal.II for the time being. Eventually, they have to change to 2nd gen libraries to utilize heterogenous computing platforms.

@keitat Would you mind trying again? I've observed `spack install trilinos~kokkos~tpetra~ifpack2~amesos2~muelu` working (without need for `~zoltan2`). Also, I totally agree that 1st gen Trilinos libraries are important. In all of this, the only thing I found surprising was that MueLu was ever able to build without Tpetra (although it won't in the future), because I thought it would fail to build without Tpetra/Kokkos (being a 2nd gen library).

**Comment by sethrj** [comment]
Maybe we should move toward toggles for first and second generation package groups (epetra and all its solvers, tpetra and all its solvers) instead of adding more variants and propagating tribits logic into the spack recipe?
