### ISSUE TITLE
Installation issue: freetype@2.8 

### ISSUE THREAD

**Issue by markyoder** [LLNL/spack#25757]
### Steps to reproduce the issue

@michaelkuhn
```
(base) [myoder96@sh03-04n63 /scratch/users/myoder96/spack_dev/zen2a] (job 32689036) $ spack --config-scope=config_cees/ --config-scope=config_intel@2021.3.0 install -j8 dealii %intel@2021.3.0 target=zen2
==> Warning: Intel's compilers may or may not optimize to the same degree for non-Intel microprocessors for optimizations that are not unique to Intel microprocessors
==> Error: Conflicts in concretized spec "dealii@9.3.0%intel@2021.3.0+adol-c+arborx+arpack+assimp~cuda~doc+examples+ginkgo+gmsh+gsl+hdf5~int64~ipo+metis+mpi+muparser~nanoflann~netcdf+oce~optflags+p4est+petsc~python+scalapack+simplex+slepc+sundials+symengine+threads+trilinos build_type=Release cuda_arch=none cxxstd=default arch=linux-centos7-zen2/efw2jhh"
List of matching conflicts for spec:

    freetype@2.11.0%intel@2021.3.0 arch=linux-centos7-zen2
        ^bzip2@1.0.8%intel@2021.3.0~debug~pic+shared arch=linux-centos7-zen2
            ^diffutils@3.7%intel@2021.3.0 arch=linux-centos7-zen2
                ^libiconv@1.16%intel@2021.3.0 libs=shared,static arch=linux-centos7-zen2
        ^libpng@1.6.37%intel@2021.3.0 arch=linux-centos7-zen2
            ^zlib@1.2.11%intel@2021.3.0+optimize+pic+shared arch=linux-centos7-zen2
        ^pkg-config@0.29.2%intel@2021.3.0+internal_glib arch=linux-centos7-zen2

1. "%intel" conflicts with "freetype@2.8:" [freetype-2.8 and above cannot be built with icc (does not support __builtin_shuffle)]
```

The `--config-spec=` mostly contain `package.yaml` information. Without getting into too much detail, I typically start with the most recent versions of packages and walk them back until they work. I've see a couple of these "will not compile with `%intel` errors.

Debug report:

```
(base) [myoder96@sh03-04n63 /scratch/users/myoder96/spack_dev/zen2a] (job 32689036) $ spack debug report
* **Spack:** 0.16.2-4111-7adacf9
* **Python:** 3.8.5
* **Platform:** linux-centos7-zen2
* **Concretizer:** original
(base) [myoder96@sh03-04n63 /scratch/users/myoder96/spack_dev/zen2a] (job 32689036) $ 
```

### Information on your system

System is:
Stanford's Sherlock HPC
CentOS-7.x

building an intel based SW stack.

### Additional information

[Archive.zip](https://github.com/spack/spack/files/7100024/Archive.zip)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by michaelkuhn** [comment]
I'm not sure what to do here since the conflict message states that freetype is simply not compatible with %intel:
> freetype-2.8 and above cannot be built with icc (does not support __builtin_shuffle)

You could try checking whether this is still true or building it with %gcc.

**Comment by markyoder** [comment]
I am working around the problem. I wasn't sure if it was of value to put this into the bugs repository. I think I just rolled back the version, or i may have fixed it by adding a `spack load gcc` into the script. If it's not of value to keep it on the bugs-list radar, you can certainly close the ticket.

**Comment by SunSDSE** [comment]
If you are building an application where you want to leverage the Intel optimizations. This issue becomes a show stopper. Having freetype@2.11.0 compiled with gcc on the system is not meeting the requirements for using the Intel OneAPI compilers.

spack install openfoam +paraview%intel
==> Error: Conflicts in concretized spec "openfoam@2106%intel@2021.3.0~float32~int64~kahip~knl~metis~mgridgen+paraview+scotch+source~spdp~vtk~zoltan arch=linux-centos7-skylake_avx512/afpo75h"
List of matching conflicts for spec:

    freetype@2.11.0%intel@2021.3.0 arch=linux-centos7-skylake_avx512
        ^bzip2@1.0.8%intel@2021.3.0~debug~pic+shared arch=linux-centos7-skylake_avx512
            ^diffutils@3.7%intel@2021.3.0 arch=linux-centos7-skylake_avx512
                ^libiconv@1.16%intel@2021.3.0 arch=linux-centos7-skylake_avx512
        ^libpng@1.6.37%intel@2021.3.0 arch=linux-centos7-skylake_avx512
            ^zlib@1.2.11%intel@2021.3.0+optimize+pic+shared arch=linux-centos7-skylake_avx512
        ^pkgconf@1.7.4%intel@2021.3.0 arch=linux-centos7-skylake_avx512

1. "%intel" conflicts with "freetype@2.8:" [freetype-2.8 and above cannot be built with icc (does not support __builtin_shuffle)]

What is the work around?

**Comment by SunSDSE** [comment]
> If you are building an application where you want to leverage the Intel optimizations. This issue becomes a show stopper. Having freetype@2.11.0 compiled with gcc on the system is not meeting the requirements for using the Intel OneAPI compilers.
> 
> spack install openfoam +paraview%intel ==> Error: Conflicts in concretized spec "openfoam@2106%intel@2021.3.0~float32~int64~kahip~knl~metis~mgridgen+paraview+scotch+source~spdp~vtk~zoltan arch=linux-centos7-skylake_avx512/afpo75h" List of matching conflicts for spec:
> 
> ```
> freetype@2.11.0%intel@2021.3.0 arch=linux-centos7-skylake_avx512
>     ^bzip2@1.0.8%intel@2021.3.0~debug~pic+shared arch=linux-centos7-skylake_avx512
>         ^diffutils@3.7%intel@2021.3.0 arch=linux-centos7-skylake_avx512
>             ^libiconv@1.16%intel@2021.3.0 arch=linux-centos7-skylake_avx512
>     ^libpng@1.6.37%intel@2021.3.0 arch=linux-centos7-skylake_avx512
>         ^zlib@1.2.11%intel@2021.3.0+optimize+pic+shared arch=linux-centos7-skylake_avx512
>     ^pkgconf@1.7.4%intel@2021.3.0 arch=linux-centos7-skylake_avx512
> ```
> 
>  1. "%intel" conflicts with "freetype@2.8:" [freetype-2.8 and above cannot be built with icc (does not support __builtin_shuffle)]
> 
> What is the work around?

This does not make sense to me as the Git source of Freetype 2.11 will compile and installs fine using the Intel OneAPI "icc" compiler.
