### ISSUE TITLE
question about version function

### ISSUE THREAD

**Issue by Jarvx** [LLNL/spack#25752]
https://github.com/spack/spack/blob/8a7af82a82fb80b660a08ab54e8d8402d7ca27b5/var/spack/repos/builtin/packages/libaio/package.py#L20

I was just wondering where I can find the definition of the function version in the class body?

**Comment by adamjstewart** [comment]
This function is defined here: https://github.com/spack/spack/blob/develop/lib/spack/spack/directives.py#L303

**Comment by Jarvx** [comment]
Thanks for the quick response ! I was thinking maybe this is imported from somewhere. So in this case,  "version" will be loaded using directives.

**Comment by adamjstewart** [comment]
The import happens here: https://github.com/spack/spack/blob/develop/lib/spack/spack/pkgkit.py#L46

This file is automatically imported here: https://github.com/spack/spack/blob/develop/lib/spack/spack/repo.py#L81

It's a bit confusing, but that's where all the magic happens.

**Comment by Jarvx** [comment]
It is just so exciting to see your help !!!  Many thanks !
