### ISSUE TITLE
amdgpu_target_sram_ecc no longer used in rocfft

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#25773]
The `amdgpu_target_sram_ecc` variant has no effect in newer versions of `rocfft`, we should probably add conflicts for all values other than `none` for the versions where it doesn't apply.

**Comment by srekolam** [comment]
the AMDGPU_TARGETS_SRAM_ECC is removed from the 4.1.0 onwards ..i looked at the cmakelists.txt for rocfft for rocm-4.1.0 and i see it is removed. 
in that case, l propose to do the following change in the recipe. - Line 65-66 ,
 if tgt_sram[0] != 'none' and if spec.satisfies('@3.9.0,4.0.0'):' :
            args.append(self.define('AMDGPU_TARGETS_SRAM_ECC', ";".join(tgt_sram)))
