### ISSUE TITLE
buildcache update-index causes build dependency thrashing

### ISSUE THREAD

**Issue by scottwittenburg** [LLNL/spack#25829]
### Problem Summary

The problem is that running `spack buildcache update-index` repeatedly on the same set of `spec.yaml` files might result in splicing the same dependencies back and forth forever.  Here's some excerpted output from several back-to-back runs to illustrate:

```
$ spack -d buildcache update-index --mirror-url <put-url-here>
...
==> [2021-09-07-17:50:28.918187] Specs sorted by number of dependencies:
==> [2021-09-07-17:50:28.918229]   ncurses/uba77xw -> 1
==> [2021-09-07-17:50:28.918505]   libtool/jdxbjft -> 2
==> [2021-09-07-17:50:28.918674]   libpciaccess/bob4o5m -> 5
==> [2021-09-07-17:50:28.918843]   hwloc/bkzrdnv -> 11
==> [2021-09-07-17:50:28.918909]     needs the following deps spliced:
==> [2021-09-07-17:50:28.918950]       libpciaccess/bob4o5m
==> [2021-09-07-17:50:29.179143]     spliced and wrote file:///Users/scott/Documents/spack/shared_pr_mirror_stuff/smaller_repro/mirror/build_cache/linux-ubuntu18.04-x86_64-gcc-7.5.0-hwloc-2.5.0-bkzrdnv2smjzsvpmwjugmvjtyupp7zhf.spec.yaml
```

From the output we can see that spack spliced a different `libpciaccess` into the dependencies of `hwloc`.  So let's run the same command again.  Since the dependency `spec.yaml` files have not changed, only the `hwloc` has been updated, you might think spack would find there are no more specs that require splicing.

```
$ spack -d buildcache update-index --mirror-url <put-url-here>
==> [2021-09-07-17:50:41.676978] Specs sorted by number of dependencies:
==> [2021-09-07-17:50:41.677019]   ncurses/uba77xw -> 1
==> [2021-09-07-17:50:41.677297]   libtool/jdxbjft -> 2
==> [2021-09-07-17:50:41.677471]   libpciaccess/bob4o5m -> 5
==> [2021-09-07-17:50:41.677644]   hwloc/bkzrdnv -> 11
==> [2021-09-07-17:50:41.677771]     needs the following deps spliced:
==> [2021-09-07-17:50:41.677845]       ncurses/uba77xw
==> [2021-09-07-17:50:41.934255]     spliced and wrote file:///Users/scott/Documents/spack/shared_pr_mirror_stuff/smaller_repro/mirror/build_cache/linux-ubuntu18.04-x86_64-gcc-7.5.0-hwloc-2.5.0-bkzrdnv2smjzsvpmwjugmvjtyupp7zhf.spec.yaml
```

 This time spack had to splice a different `ncurses` into the dependencies of the same spec, `hwloc`.  If we run the command again at this point, spack will again splice in the `libpciaccess` dep of `hwloc`, and running it again after that will result in spack splicing in the `ncurses` dep of `hwloc` again, and so forth forever.

To me, the problem seems to be that the `libpciaccess` and `ncurses` spec yaml files depend on different versions of `pkgconf`, but because `pkgconf` is a build dependency of both, changing its version doesn't change the dag hash of the dependents.  

### Steps to reproduce

To reproduce the problem, download the four concrete spec yaml files which I took from an actual spack binary mirror we use in gitlab pipelines for PR/develop testing.  You have to change the names to remove the `.txt` (which we are forced to add before github will allow us to upload them).  Then do:

```
mkdir -p /Users/<you>/testing/backups
cp ~/Downloads/*.spec.yaml /Users/<you>/testing/backups/
mkdir -p /Users/<you>/testing/mirror/build_cache
cp ~/Downloads/*.spec.yaml /Users/<you>/testing/mirror/build_cache/
spack -d buildcache update-index --mirror-url file:///Users/<you>/testing/mirror
```

The extra copies are so you can be sure to keep the originals pristine for comparison or replacement, as `spack buildcache update-index` can edit them in theory (and does edit the `hwloc` spec in this example).  If you run the last command above, over and over, you should see spack splicing in `libpciaccess`, then splicing in `nurses`, then `libpciaccess` again, etc....

[linux-ubuntu18.04-x86_64-gcc-7.5.0-hwloc-2.5.0-bkzrdnv2smjzsvpmwjugmvjtyupp7zhf.spec.yaml.txt](https://github.com/spack/spack/files/7125063/linux-ubuntu18.04-x86_64-gcc-7.5.0-hwloc-2.5.0-bkzrdnv2smjzsvpmwjugmvjtyupp7zhf.spec.yaml.txt)
[linux-ubuntu18.04-x86_64-gcc-7.5.0-libpciaccess-0.16-bob4o5m3uku6vtdil5imasprgy775zg7.spec.yaml.txt](https://github.com/spack/spack/files/7125064/linux-ubuntu18.04-x86_64-gcc-7.5.0-libpciaccess-0.16-bob4o5m3uku6vtdil5imasprgy775zg7.spec.yaml.txt)
[linux-ubuntu18.04-x86_64-gcc-7.5.0-libtool-2.4.6-jdxbjftheiotj6solpomva7dowrhlerl.spec.yaml.txt](https://github.com/spack/spack/files/7125065/linux-ubuntu18.04-x86_64-gcc-7.5.0-libtool-2.4.6-jdxbjftheiotj6solpomva7dowrhlerl.spec.yaml.txt)
[linux-ubuntu18.04-x86_64-gcc-7.5.0-ncurses-6.2-uba77xwfqaytmx3v5eye43deqq5rqsun.spec.yaml.txt](https://github.com/spack/spack/files/7125066/linux-ubuntu18.04-x86_64-gcc-7.5.0-ncurses-6.2-uba77xwfqaytmx3v5eye43deqq5rqsun.spec.yaml.txt)

### Information on your system

While the attached spec.yaml files are from a linux os, they can be copied to any system to test the `spack buildcache update-index` command.  I ran them on my macbook.

```
$ spack debug report
* **Spack:** 0.16.2-4176-c6e538583f
* **Python:** 3.7.9
* **Platform:** darwin-catalina-skylake
* **Concretizer:** original
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by scottwittenburg** [comment]
@becker33 Is it clear what the problem is here?  If not, let me know, and I can try to explain better.  I've been struggling with why we seem to need to splice so many specs every time we run `spack buildcache update-index`, even when we didn't build anything new to put into the mirror.  The four files I uploaded are sufficient to reproduce the problem.

**Comment by scottwittenburg** [comment]
fyi @zackgalbreath

**Comment by scottwittenburg** [comment]
fyi @eugeneswalker

**Comment by alalazo** [comment]
@scottwittenburg I'm going through old un-triaged issues. Am I correct that this is outdated and can be closed?

**Comment by scottwittenburg** [comment]
Yes, this is outdated, will close.
