### ISSUE TITLE
Is there a way to mirror a package and its dependencies?

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#2583]
I'm having trouble doing end-to-end builds because sourceforge is timing out today.

That encouraged me to get around to playing with `spack mirror` and it doesn't quite do what I assumed (dangerous word, that...) it did.

I was hoping that `spack mirror create -d /path/to/dir emacs@25.1`  would figure out all of the packages and versions that would be used to install that and go get them all.

I also thought that `spack mirror add` would add the dependencies for additional packages to an existing mirror.

Is there a way to abuse some combination of `spack fetch` and `spack mirror` to grab all of the things needed to install my apps given spec's for them?

Failling that, 

```
spack spec -y emacs@25.1+X | frobicator > list; spack mirror create -d ... -f list
```

might work, give a little `go` magic to write the frobnicator (or perhaps practicing my `python` magic would be good for me, except I worry about [this kind of thing...](https://youtu.be/J3cARml0TZ8?t=5m13s)[audio, but safe for work...]).

**Comment by citibeth** [comment]
I've always felt the `spack mirror` functionality is a little weak.  I think the behavior described here would be useful.

**Comment by davydden** [comment]
Same here, IMHO mirror should fetch everything needed to build the spec, not only the root node.

**Comment by citibeth** [comment]
I think this is ready to be implemented, does anyone want to take a stab at it?

**Comment by cyrush** [comment]
I believe spack mirror already does this if you add `--dependencies `

Here is how I am using an ancient version of spack (from within a python script) to fetch the source of a package and everything it depends on:

`"spack/bin/spack mirror create -d {} --dependencies {}".format( mirror_path, pkg_name)`

**Comment by tgamblin** [comment]
@cyrush: I think @hartzell is looking for something that will download all the versions, rather than just those needed for a particular concrete spec.  I've actually got a prototype of this I used to download all the tarballs in Spack; it just needs polishing off.

I think we could make this the default behavior (download tarballs for all potential options) and allow a `--minimal` argument to shrink things down to a concrete spec.  Do people like that idea?

**Comment by cyrush** [comment]
I see -- I would prefer it only download what is needed for the spec given and have an option to broaden. I think it's good to be nice to the folks hosting the files :-)

**Comment by hartzell** [comment]
@tgamblin -- I didn't explain it well, I don't want everything, just everything that I need to install my set of things.

I'll give @cyrush's suggestion a try.

**Comment by alalazo** [comment]
@hartzell I'll close this (no reply since January). Feel free to reopen if it is still an issue.
