### ISSUE TITLE
Installation issue: tasmanian

### ISSUE THREAD

**Issue by wspear** [LLNL/spack#25858]
### Steps to reproduce the issue

On Spock:
spack install tasmanian+rocm~cuda amdgpu_target=gfx908
Fails with numerous errors like: 
/tmp/wspear/spack-stage/spack-stage-tasmanian-7.5-wn73xeo7rheolvi37iiwyqyllees4rb7/spack-src/SparseGrids/tsgCudaBasisEvaluations.hpp:92:13: error: use of undeclared identifier 'threadIdx'

Other undefined identifiers are __syncthreads, grimDim and blockIdx. These all occurs in the same source file. Adding ~cuda to the install command made no difference.

### Information on your system

* **Spack:** 0.16.2-4192-c2a6ccbea8
* **Python:** 3.6.13
* **Platform:** cray-sles15-zen2
* **Concretizer:** original

### Additional information

@mkstoyanov 
[spack-build-env.txt](https://github.com/spack/spack/files/7132589/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7132590/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by mkstoyanov** [comment]
The error indicates that the build is not using the `hipcc` compiler, looking at the logs it is using `clang++`.

In the tasmanian spack package, I have:
```
    def setup_build_environment(self, env):
        # needed for the hipcc compiler
        if "+rocm" in self.spec:
            env.set('CXX', self.spec['hip'].hipcc)
```
and the `CXX` variable is exported in the build environment, but somehow it is not respected.

The issue appears on my test machine now, so it is not specific to a single system. It was not present in a previous version of spack and hip.

Do you know if there is a better way to tell spack and CMake to use the `hipcc` compiler?

**Comment by mkstoyanov** [comment]
The latest CMake 3.21 and ROCm have an issue when it comes to using the `hipcc` compiler. The workaround has been added to the Tasmanian spack packge:

https://github.com/spack/spack/pull/25948 and https://github.com/spack/spack/pull/25949

**Comment by mkstoyanov** [comment]
Old issue, resolved already. Open a new one, if needed.
