### ISSUE TITLE
Spack test may use incorrect cmake

### ISSUE THREAD

**Issue by wspear** [LLNL/spack#25852]
### Steps to reproduce

I'm not sure how to replicate this issue generally but any package that has spack test support and a specific cmake requirement might be subject. 

In a 'clean' environment (where the correct cmake is not loaded manually) `spack test <package>` may use a system-provided or otherwise incorrect cmake, resulting in test components that rely on cmake to fail to build. If doing `spack test `as a batch where there are multiple packages with incompatible cmake versions I don't believe there is a workaround.

This PR addresses this issue: https://github.com/spack/spack/pull/24424
@tldahlgren 

### Information on your system

* **Spack:** 0.16.2-4192-c2a6ccbea8
* **Python:** 3.6.13
* **Platform:** cray-sles15-zen2
* **Concretizer:** original

```
[wspear@login1.spock build]$  /usr/bin/cmake --version
cmake version 3.17.0

CMake suite maintained and supported by Kitware (kitware.com/cmake).
[wspear@login1.spock build]$ which cmake
/autofs/nccs-svm1_proj/csc439/wspear/spock/spack-e4s-21.08-gcc-10.3.0/opt/spack/cray-sles15-x86_64/gcc-10.3.0/cmake-3.20.5-buohxldhbe7xzsyhnt76m5tanfjbmnty/bin/cmake
[wspear@login1.spock build]$ cmake --version
cmake version 3.20.5

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by tldahlgren** [comment]
Technically, #24424 only has a package-specific hack for the problem.  A relatively simple solution that used to work does not seem to fix the general problem (anymore) and I have not had a chance to dig into why that is the case.  For more see #25165.

**Comment by tgamblin** [comment]
@wspear do you still see this?  There was a lot of work done to ensure the correct `cmake` in the environment in #31739, so I wonder if this is still an issue.

**Comment by wspear** [comment]
I was able to successfully run the kokkos spack-test with an outdated version of cmake loaded so it seems this is working at least in that case. We still occasionally run into issues with spack-test related to the need to load up the environment to match the test before running the test so I'm not sure if this is a package-specific fix or if all spack tests are now covered.

**Comment by tgamblin** [comment]
Closing since this seems to be resolved. Please reopen if you see it again.
