### ISSUE TITLE
spack test cannot access results from previous tests

### ISSUE THREAD

**Issue by tldahlgren** [LLNL/spack#25898]
### Steps to reproduce

You'll need test results produced by running `spack test run` prior to around September 8th.  

If you don't have any I can provide a tar ball of some that I was able to copy from my Mac to a Linux box to get the same output.

### Error message

Based on tests I ran on my Mac on August 27th, where I used aliases `p2`, `m4`, and `p3` for testing different installations of `m4`:

```
$ spack test results -- m4
==> Test p2 has no results.
        Check if it is running with `spack test status p2`
==> Test m4 has no results.
        Check if it is running with `spack test status m4`
==> Test p3 has no results.
        Check if it is running with `spack test status p3`
```

but I know there are results:

```
$ ls -al ~/.spack/test/*/results.txt
-rw-r--r--  1 dahlgren1  3378  50 Aug 27 10:34 /Users/dahlgren1/.spack/test/5fkejji3jykzmtl6caghjv5k5fdprekn/results.txt
-rw-r--r--  1 dahlgren1  3378  50 Aug 27 10:19 /Users/dahlgren1/.spack/test/gw7qookzbfi6dapnpk6l5lsjdptb4fnb/results.txt
-rw-r--r--  1 dahlgren1  3378  50 Aug 27 10:35 /Users/dahlgren1/.spack/test/xkxl2mph6uxdlspyi2ot7rt56hclxzzx/results.txt
```

From a Linux box with the test results copied from my Mac into my `$HOME/.spack/test`:

```
$ spack -d test results
==> [2021-09-10-18:32:22.632183] Imported test from built-in commands
==> [2021-09-10-18:32:22.634800] Reading config file /usr/WS1/dahlgren/spack/etc/spack/defaults/config.yaml
==> [2021-09-10-18:32:22.654959] Imported test from built-in commands
==> [2021-09-10-18:32:22.664177] Test p2 has no results.
        Check if it is running with `spack test status p2`
==> [2021-09-10-18:32:22.665159] Test m4 has no results.
        Check if it is running with `spack test status m4`
==> [2021-09-10-18:32:22.666102] Test p3 has no results.
        Check if it is running with `spack test status p3`
```

### Information on your system

This issue arose on the following machines:

* **Spack:** 0.16.2-4214-3a9028427c
* **Python:** 3.8.2
* **Platform:** darwin-bigsur-skylake
* **Concretizer:** original

and 

* **Spack:** 0.16.2-4214-3a9028427c
* **Python:** 3.7.2
* **Platform:** linux-rhel7-cascadelake
* **Concretizer:** original

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
@tldahlgren Is this still an issue?

**Comment by tldahlgren** [comment]
> @tldahlgren Is this still an issue?

Hmmm.  IDK.  I don't think I have any and I don't think I have the tar file anymore.

**Comment by tldahlgren** [comment]
Closing as possibly not relevant anymore.
