### ISSUE TITLE
Decompressing a .zip file spits out thousands of lines of text

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#2592]
If you run `spack install` on a package that downloads a .zip archive, the decompression stage spits out thousands of lines of text like:
```
inflating: sys/java/jre/glnxa64/jre/lib/security/cacerts  
```
You can suppress this output by using `unzip -q` or `unzip -qq` if you want it to be really quiet. I tried adding this to `spack.util.compression.decompressor_for`, but `which()` can't accept a second argument. Can someone else figure this out? We should probably also add it to `spack create`, which is much easier.

Here are a list of packages for testing:

- bliss
- bowtie2
- cryptopp
- docbook-xml
- exodusii
- jasper
- py-3to2
- triangle
- ncl
- openscenegraph
- py-pydatalog

**Comment by tgamblin** [comment]
call `add_default_arg('-q')` (or `-qq`) on the `Executable` object returned by `which`.
