### ISSUE TITLE
Installation issue: exuberant-ctags

### ISSUE THREAD

**Issue by cjobrie** [LLNL/spack#25944]
### Steps to reproduce the issue

```console$
spack -k install exuberant-ctags
```
which uses clang, *or*
```console$
spack -k install exuberant-ctags%gcc
```

### Information on your system

* **Spack:** 0.16.2-3807-5f3c25f6e9
* **Python:** 3.8.2
* **Platform:** darwin-catalina-haswell
* **Concretizer:** original

### Additional information

[spack-build-out.txt](https://github.com/spack/spack/files/7163984/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/7163987/spack-build-env.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by cjobrie** [comment]
Found a [fix](https://sourceforge.net/p/ctags/bugs/383/), but requires changing a good chunk of the `exuberant-ctags`  source too.

**Comment by lrtfm** [comment]
#33135 fixed this.
