### ISSUE TITLE
Installation issue: phist

### ISSUE THREAD

**Issue by wspear** [LLNL/spack#26002]
### Steps to reproduce the issue

On the the Cray system Spock building phist like
`spack install phist@1.9.4%gcc@10.3.0`
Fails with:
```
     973      389 |       call MPI_Allreduce(MPI_IN_PLACE,ierr,1,MPI_INTEGER,MPI_MAX,map1%comm,mpi_ierr)
     974          |                         2
  >> 975    Error: Type mismatch between actual argument at (1) and actual argument at (2) (LOGICAL(4)/INTEGER(4)).
  >> 976    make[2]: *** [CMakeFiles/phist_kernels_builtin.dir/build.make:185: CMakeFiles/phist_kernels_builtin.dir/src/kernels/builtin/map_module.F90.o] Error 1
```

### Information on your system

* **Spack:** 0.16.2-4271-c4e26ac7c8
* **Python:** 3.6.13
* **Platform:** cray-sles15-zen2
* **Concretizer:** clingo

### Additional information

[spack-build-out.txt](https://github.com/spack/spack/files/7180299/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/7180303/spack-build-env.txt)
@jthies

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by melven** [comment]
Hi @wspear 

The output and environment file indicate that the MPI library was built for a different compiler version (9.1 vs. 10.3).
I don't know how the details are handled but usually the generated MPI Fortran module file (`mpi.mod`) is not compatible between different compiler versions.
Could this be a problem?

The actual code in phist looks fine to me. Does the following code compile with the same combination of MPI library and compiler?
```fortran
program mpi_example
  use mpi
  implicit none
  integer :: ierr
  logical :: res, localRes

  call MPI_Init(ierr)

  localRes = .true.
  call MPI_Allreduce(localRes, res, 1, MPI_LOGICAL, MPI_LAND, MPI_COMM_WORLD, ierr)

  call MPI_Finalize(ierr)
end program
```

**Comment by jthies** [comment]
I suspect that you are using a vendor-provided MPI installation but the spack config file (packages.yaml) doesn't fully identify it, so the concretizer mixes packages built with different compiler versions.

**Comment by jthies** [comment]
interestingly, I just switched from the original concretizer to clingo and it is trying to put together phist %gcc@11.2.0 with openmpi%gcc@9.3.0 for some reason. So it almost seems like an error in the concretizer to me.
What I did was
```
spack spec phist %gcc@11.2.0 ^cmake/jcjw6cc
```
Where the installed cmake version was built using gcc@9.3.0. The concretizer, however, then decides to build all other phist dependencies with gcc@9.3.0:
```
--------------------------------
phist@1.9.5%gcc@11.2.0+fortran+host+int64~ipo+mpi+openmp~parmetis+scamac+shared~trilinos build_type=RelWithDebInfo kernel_lib=builtin outlev=2 patches=1fc9ac6c1cce2804d171dd12470e709cd1e3839be6d51f7e5c33427ba4b379ca arch=linux-ubuntu20.04-icelake
    ^cmake@3.21.2%gcc@9.3.0~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=linux-ubuntu20.04-icelake
        ^ncurses@6.2%gcc@9.3.0~symlinks+termlib abi=none arch=linux-ubuntu20.04-icelake
            ^pkgconf@1.8.0%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
        ^openssl@1.1.1l%gcc@9.3.0~docs+systemcerts arch=linux-ubuntu20.04-icelake
            ^perl@5.34.0%gcc@9.3.0+cpanm+shared+threads arch=linux-ubuntu20.04-icelake
                ^berkeley-db@18.1.40%gcc@9.3.0+cxx~docs+stl patches=b231fcc4d5cff05e5c3a4814f6a5af0e9a966428dc2176540d2c05aff41de522 arch=linux-ubuntu20.04-icelake
                ^bzip2@1.0.8%gcc@9.3.0~debug~pic+shared arch=linux-ubuntu20.04-icelake
                    ^diffutils@3.7%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
                        ^libiconv@1.16%gcc@9.3.0 libs=shared,static arch=linux-ubuntu20.04-icelake
                ^gdbm@1.19%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
                    ^readline@8.1%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
                ^zlib@1.2.11%gcc@9.3.0+optimize+pic+shared arch=linux-ubuntu20.04-icelake
    ^openblas@0.3.17%gcc@11.2.0~bignuma~consistent_fpcsr~ilp64+locking+pic+shared threads=none arch=linux-ubuntu20.04-icelake
    ^openmpi@4.0.5%gcc@9.3.0~atomics~cuda~cxx~cxx_exceptions+gpfs~internal-hwloc~java~legacylaunchers~lustre~memchecker~pmi~singularity~sqlite3+static~thread_multiple+vt+wrapper-rpath fabrics=auto patches=60ce20bc14d98c572ef7883b9fcd254c3f232c2f3a13377480f96466169ac4c8 schedulers=none arch=linux-ubuntu20.04-icelake
        ^hwloc@2.5.0%gcc@9.3.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~opencl+pci~rocm+shared arch=linux-ubuntu20.04-icelake
            ^libpciaccess@0.16%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
                ^libtool@2.4.6%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
                    ^m4@1.4.19%gcc@9.3.0+sigsegv patches=9dc5fbd0d5cb1037ab1e6d0ecc74a30df218d0a94bdd5a02759a97f62daca573,bfdffa7c2eb01021d5849b36972c069693654ad826c1a20b53534009a4ec7a89 arch=linux-ubuntu20.04-icelake
                        ^libsigsegv@2.13%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
                ^util-macros@1.19.3%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
            ^libxml2@2.9.12%gcc@9.3.0~python arch=linux-ubuntu20.04-icelake
                ^xz@5.2.5%gcc@9.3.0~pic libs=shared,static arch=linux-ubuntu20.04-icelake
        ^libevent@2.1.12%gcc@9.3.0+openssl arch=linux-ubuntu20.04-icelake
        ^numactl@2.0.14%gcc@9.3.0 patches=4e1d78cbbb85de625bad28705e748856033eaafab92a66dffd383a3d7e00cc94,62fc8a8bf7665a60e8f4c93ebbd535647cebf74198f7afafec4c085a8825c006 arch=linux-ubuntu20.04-icelake
            ^autoconf@2.69%gcc@9.3.0 patches=35c449281546376449766f92d49fc121ca50e330e60fefcfc9be2af3253082c2,7793209b33013dc0f81208718c68440c5aae80e7a1c4b8d336e382525af791a7,a49dd5bac3b62daa0ff688ab4d508d71dbd2f4f8d7e2a02321926346161bf3ee arch=linux-ubuntu20.04-icelake
            ^automake@1.16.3%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
        ^openssh@8.7p1%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
            ^libedit@3.1-20210216%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
    ^python@3.8.11%gcc@9.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87,f2fd060afc4b4618fe8104c4c5d771f36dc55b1db5a4623785a4ea707ec72fb4 arch=linux-ubuntu20.04-icelake
        ^expat@2.4.1%gcc@9.3.0+libbsd arch=linux-ubuntu20.04-icelake
            ^libbsd@0.11.3%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
                ^libmd@1.0.3%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
        ^gettext@0.21%gcc@9.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-ubuntu20.04-icelake
            ^tar@1.34%gcc@9.3.0 arch=linux-ubuntu20.04-icelake
        ^libffi@3.3%gcc@9.3.0 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0 arch=linux-ubuntu20.04-icelake
        ^sqlite@3.36.0%gcc@9.3.0+column_metadata+fts~functions~rtree arch=linux-ubuntu20.04-icelake
        ^util-linux-uuid@2.36.2%gcc@9.3.0 arch=linux-ubuntu20.04-icelake

```

**Comment by wspear** [comment]
This test code and the majority of the mpi-using applications in this environment compile successfully.

The environment pins everything to gcc@10.3.0 so I think we're ok there. Some other packages have had issues with the include and lib paths for mpi, related to conflation between mpich and cray-mpich configurations I think. But that isn't what's happening here as far as I can tell. 

```
phist@1.9.5%gcc@10.3.0+fortran+host+int64~ipo+mpi+openmp~parmetis+scamac+shared~trilinos build_type=RelWithDebInfo kernel_lib=builtin outlev=2 patches=1fc9ac6c1cce2804d171dd12470e709cd1e3839be6d51f7e5c33427ba4b379ca arch=cray-sles15-zen2
    ^cmake@3.20.5%gcc@10.3.0~doc+ncurses+openssl+ownlibs~qt build_type=Release arch=cray-sles15-zen2
        ^ncurses@6.2%gcc@10.3.0~symlinks+termlib abi=none arch=cray-sles15-zen2
            ^pkgconf@1.7.4%gcc@10.3.0 arch=cray-sles15-zen2
        ^openssl@1.1.1l%gcc@10.3.0~docs+systemcerts arch=cray-sles15-zen2
            ^perl@5.34.0%gcc@10.3.0+cpanm+shared+threads arch=cray-sles15-zen2
                ^berkeley-db@18.1.40%gcc@10.3.0+cxx~docs+stl patches=b231fcc4d5cff05e5c3a4814f6a5af0e9a966428dc2176540d2c05aff41de522 arch=cray-sles15-zen2
                ^bzip2@1.0.8%gcc@10.3.0~debug~pic+shared arch=cray-sles15-zen2
                    ^diffutils@3.7%gcc@10.3.0 arch=cray-sles15-zen2
                        ^libiconv@1.16%gcc@10.3.0 libs=shared,static arch=cray-sles15-zen2
                ^gdbm@1.19%gcc@10.3.0 arch=cray-sles15-zen2
                    ^readline@8.1%gcc@10.3.0 arch=cray-sles15-zen2
                ^zlib@1.2.11%gcc@10.3.0+optimize+pic+shared arch=cray-sles15-zen2
    ^cray-mpich@8.1.7%gcc@10.3.0 arch=cray-sles15-zen2
    ^openblas@0.3.17%gcc@10.3.0~bignuma~consistent_fpcsr~ilp64+locking+pic+shared threads=openmp arch=cray-sles15-zen2
    ^python@3.8.10%gcc@10.3.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87,ebdca648c9c1d25f586d7e2a495b62e6d91973b55264a13d89eda1beff72ef56,f2fd060afc4b4618fe8104c4c5d771f36dc55b1db5a4623785a4ea707ec72fb4 arch=cray-sles15-zen2
        ^expat@2.4.1%gcc@10.3.0+libbsd arch=cray-sles15-zen2
            ^libbsd@0.11.3%gcc@10.3.0 arch=cray-sles15-zen2
                ^libmd@1.0.3%gcc@10.3.0 arch=cray-sles15-zen2
        ^gettext@0.21%gcc@10.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=cray-sles15-zen2
            ^libxml2@2.9.10%gcc@10.3.0~python arch=cray-sles15-zen2
                ^xz@5.2.5%gcc@10.3.0+pic libs=shared,static arch=cray-sles15-zen2
            ^tar@1.34%gcc@10.3.0 arch=cray-sles15-zen2
        ^libffi@3.3%gcc@10.3.0 patches=26f26c6f29a7ce9bf370ad3ab2610f99365b4bdd7b82e7c31df41a3370d685c0 arch=cray-sles15-zen2
        ^sqlite@3.35.5%gcc@10.3.0+column_metadata+fts~functions~rtree arch=cray-sles15-zen2
        ^util-linux-uuid@2.36.2%gcc@10.3.0 arch=cray-sles15-zen2


```

**Comment by melven** [comment]
phist uses its own `FindMPI.cmake` script because of some problems in (older) CMake versions on clusters (finding the wrong MPI version).
We should check if it helps to remove it.
Can you reproduce the error if you compile phist without spack? Then you could check if it helps to remove the file `cmake/FindMPI.cmake` in phist.

Unfortunately I don't have access to a Cray system currently - what about you @jthies?

**Comment by jthies** [comment]
I think we may have to get the MPI paths from the spack package.py and force phist to use them, maybe that's not done in a clean way up to now (that is, we rely on phist finding the MPI that spack puts in its way).

**Comment by jthies** [comment]
@wspear, could you post the output of "mpicxx -show"? I noticed that on my Ubuntu-system, "/usr/bin/mpicxx -show" contains paths to spack-installed openmpi headers if I have the corresponding TCL module loaded... Our cmake FindMPI relies on such a command to figure out the MPI include and library paths.

**Comment by wspear** [comment]
Here it is (with the cray-mpich/8.7.1 module loaded, no spack involvement): 

```
[wspear@login1.spock ~]$ mpicxx -show
g++ -I/opt/cray/pe/mpich/8.1.7/ofi/gnu/9.1/include -L/opt/cray/pe/mpich/8.1.7/ofi/gnu/9.1/lib -lmpi_gnu_91
```

**Comment by sethrj** [comment]
@wspear The "Type mismatch" error you're seeing is an extremely common bug in MPI usage (and other functions) that, starting with GCC10, is treated as an error. Basically if you call `MPI_Allreduce` (or other MPI functions) twice from the old-style `mpi` module (or `mpi.h` header) in the same Fortran file but with different types, Gfortran treats it as an error because it derived the function signature from the first instance. The real fix is to use the modern (typed) MPI fortran module, but a workaround is to add the `-fallow-argument-mismatch` flag when calling the fortran compiler.

See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91556 for a discussion on the new external implicit interface detection, or google `"gfortran 10" "type mismatch"` to find many other examples of scientific codes that this behavior change broke.

**Comment by jthies** [comment]
in the corresponding Fortran module there is only a "use mpi", no "#include <mpi.h>" or something similar. Moreover, I can build phist with gfortran 10 without problems.

**Comment by melven** [comment]
Just to clarify (thanks @sethrj):
* ancient: `include 'mpif.h'`
* old: `use mpi`
* new: `use mpi_f08`

We currently have `use mpi` there - the code was partly written before working Fortran 2008 support in the compilers.
@jthies: I would suggest we use the newer Fortran module if available... (I can have a look but I stil have some other points on my todo list ;) )

**Comment by sethrj** [comment]
@jthies The error is definitely related to the `mpi` call:
```fortran
          call MPI_Allreduce(localRes, res, 1, MPI_LOGICAL, MPI_LAND, map1%comm, ierr);
```
on line 167 passes `logical :: res` and 
```fortran
      call MPI_Allreduce(MPI_IN_PLACE,ierr,1,MPI_INTEGER,MPI_MAX,map1%comm,mpi_ierr)
```
on 389 passes `integer :: ierr`.

If the MPI version that defined `mpi.mod` (wherever it's hiding) just declares `EXTERNAL MPI_Allreduce` rather than defining a generic interface, GCC10 will definitely error out. It will infer from the first call that the `MPI_Allreduce` function (which has a defined name but an implied interface) takes logical values, then it errors on the second call because it's not consistent.

It could be that the cray `mpi` module doesn't define generics but rather a single "external"?

I'm willing to bet that the following extension to your example *will* fail to compile on the failing cray environment:

```fortran
program mpi_example
  use mpi
  implicit none
  integer :: ierr, mpi_ierr
  logical :: res, localRes

  call MPI_Init(ierr)

  localRes = .true.
  call MPI_Allreduce(localRes, res, 1, MPI_LOGICAL, MPI_LAND, MPI_COMM_WORLD, ierr)
  call MPI_Allreduce(MPI_IN_PLACE, ierr, 1, MPI_INTEGER, MPI_LAND, MPI_COMM_WORLD, mpi_ierr)

  call MPI_Finalize(ierr)
end program
```
