### ISSUE TITLE
Allow extra_instructions at beginning of container stages

### ISSUE THREAD

**Issue by ktpedre** [LLNL/spack#26036]
### Summary

Some sites may need to add SSL certificates or other things to the beginning of the stages generated by "spack containerize". There are currently "extra_instructions:build" and "extra_instructions:final" options available to add extra commands at the end of each build stage. This request is asking for similar functionality for the beginning of each build stage.

For example:

```
FROM spack/centos7:latest as builder

# Beginning extra_instructions
ADD site_specific_cert.crt /etc/pki/ca-trust/source/anchors/site_specific_cert.crt
RUN update-ca-trust

# Auto-generated content by "spack containerize"

# Ending extra_instructions
RUN yum install -y libgomp

ENTRYPOINT ["/bin/bash", "--rcfile", "/etc/profile", "-l"]
```

### Rationale

Some sites require a site-specific SSL certificate to be installed in order to reach upstream repos outside of the site. Without these certs in place, the "docker build ." fails.

### Description

Add extra_instructions before the Dockerfile contents generated by Spack. Such a feature already exists for extra_instructions after the auto-generated content.

### Additional information

Using spack developer brach:

$ spack --version
0.16.2-4259-5d23638fdc

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by apmccartney** [comment]
As a work-around, `spack containerize` allows you to specify a user-defined image for both the `build` and `final` step.

You can provide images with site-specific credentials for one or both of those steps.

**Comment by climbfuji** [comment]
@mark-a-potts FYI

**Comment by climbfuji** [comment]
Thank you very much @alalazo! I'll work on updating our container build recipes in the next week(s ... as time allows).

**Comment by alalazo** [comment]
@climbfuji :+1: Let me know if you see issues, I'll prioritize fixing them!
