### ISSUE TITLE
Installation issue: qgis

### ISSUE THREAD

**Issue by steo85it** [LLNL/spack#26033]
### Steps to reproduce the issue

```console
spack install qgis
```

### Information on your system

```
* **Spack:** 0.16.2-4279-7e7de25aba
* **Python:** 3.6.8
* **Platform:** linux-centos7-skylake
* **Concretizer:** clingo
```

### Additional information

Here is my compilation output and error message: proj is installed, so I'm not sure why it is complaining.
Thanks for any help @Sinan81  @adamjstewart !

```console
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /home/sberton2/.spack/lib/spack/env/gcc/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /home/sberton2/.spack/lib/spack/env/gcc/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- QGIS version: 3.16.5 Hannover (31605)
-- Looking for openpty
-- Looking for openpty - not found
-- Looking for openpty
-- Looking for openpty - found
-- Found GEOS: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/geos-3.9.1-gi3rqhvsi6zmnzm35xcfltibt4nmf63f/lib/libgeos_c.so (3.9.1)
-- Found GDAL: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/gdal-3.3.2-voikd6xd4d4xdsl6skuv4khsruayxbj5/lib/libg
dal.so (3.3.2)
-- Found Expat: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/expat-2.4.1-pyfatz6cwkcdjsjhjsrzqljry37gzr6y/lib/li
bexpat.so
-- Found Spatialindex: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/libspatialindex-1.9.3-ygmek3iglaw7qzfsvcwadj
dcmc6pxytx/lib/libspatialindex.so
-- Found Qwt: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/qwt-6.1.6-6hmhnw5ppxelzeiqwrznbu2mxxyvfzpl/lib/libqwt
.so (6.1.6)
-- Found LibZip: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/libzip-1.2.0-gqq44oeuobz4oboj45jntgwykl2yshu4/lib/
libzip.so  
-- Found libzip: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/libzip-1.2.0-gqq44oeuobz4oboj45jntgwykl2yshu4/lib/
libzip.so
-- Found Sqlite3: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/sqlite-3.36.0-etpxgynjjno2j3ijbjprfieyetjzixvd/li
b/libsqlite3.so
CMake Warning (dev) at /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/cmake-3.21.2-dk3vtkwamxxxfcey44n672v3hqxlsau
c/share/cmake-3.21/Modules/CheckIncludeFile.cmake:82 (message):
  Policy CMP0075 is not set: Include file check macros honor
  CMAKE_REQUIRED_LIBRARIES.  Run "cmake --help-policy CMP0075" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  CMAKE_REQUIRED_LIBRARIES is set to:

    util

  For compatibility with CMake 3.11 and below this check is ignoring it.
Call Stack (most recent call first):
  /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/cmake-3.21.2-dk3vtkwamxxxfcey44n672v3hqxlsauc/share/cmake-3.21/Mo
dules/FindThreads.cmake:146 (CHECK_INCLUDE_FILE)
  /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/cmake-3.21.2-dk3vtkwamxxxfcey44n672v3hqxlsauc/share/cmake-3.21/Mo
dules/FindProtobuf.cmake:444 (find_package)
  CMakeLists.txt:349 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found Protobuf: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/protobuf-3.17.3-ogsuv7bvdm6iar6b27w7feniejhzs4pw
/lib64/libprotobuf.so;-lpthread (found version "3.17.3") 
-- Found Protobuf: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/protobuf-3.17.3-ogsuv7bvdm6iar6b27w7feniejhzs4pw
/lib64/libprotobuf.so;-lpthread
-- Found ZLIB: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/zlib-1.2.11-3pgwxgsu5kkcetlrm6zlp2o7nkye7c2e/lib/lib
z.so (found version "1.2.11") 
-- Found zlib: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/zlib-1.2.11-3pgwxgsu5kkcetlrm6zlp2o7nkye7c2e/lib/lib
z.so
-- Found PostgreSQL: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/postgresql-11.2-jqenp7owl2oxuus6zp7wc2fwzrmuxl
xr/lib/libpq.so
-- Found SpatiaLite: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/libspatialite-5.0.0-mv7yhghhfnfpmmuj7jyaoeqyox
ty5bqj/lib/libspatialite.so
CMake Error at CMakeLists.txt:373 (message):
  Some dependencies were not found! Proj: , Geos: TRUE, GDAL: TRUE


-- Qt WebKit support DISABLED.
-- Found Threads: TRUE  
-- Found Qt version: 5.14.2
-- Found QScintilla2: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/qscintilla-2.11.6-aanh333hpoxuar7yydselctmote
gijdm/lib/libqscintilla2_qt5.so (2.11.6)
-- Found QtKeychain: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/qtkeychain-0.9.1-dag25c4hfasvjnwy5h232ko2qje7r
p5m/lib64/libqt5keychain.so
-- Found QCA: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/qca-2.2.1-46adakxwfhzqf2ds3aoxwh3xkoqgpjui/lib/libqca
-qt5.so (2.2.1)
-- Found QCA OpenSSL plugin
-- Pedantic compiler settings enabled
-- Debug output enabled
-- Found GSL: -L/home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/gsl-2.7-yjs5ud7wu25yrlx6i2ri3xwrrzdaaxdh/lib -lgsl 
-lgslcblas -lm
-- Found PythonInterp: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/python-3.8.11-doeeci4i2ml7dmybkkvqpkxcgdq226
g6/bin/python3 (found suitable version "3.8.11", minimum required is "3") 
-- Found Python executable: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/python-3.8.11-doeeci4i2ml7dmybkkvqpkxcg
dq226g6/bin/python3
-- Found Python version: 3.8.11
-- Found Python library: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/python-3.8.11-doeeci4i2ml7dmybkkvqpkxcgdq2
26g6/lib/libpython3.8.so
-- Found Python site-packages: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/python-3.8.11-doeeci4i2ml7dmybkkvqpk
xcgdq226g6/lib/python3.8/site-packages
-- Found PyQt5 version: 5.13.1
-- Found SIP version: 4.255.255
-- Found QScintilla2 PyQt module: 2.11.6
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Found exiv2: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/exiv2-0.27.2-qpkouufk2enjd7a6wpksslvkk64p7qkb/lib64
/libexiv2.so
-- Found HDF5: hdf5-shared (found version "1.10.7")  
-- Found PkgConfig: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/pkgconf-1.8.0-mk4dm3vkzbbeddaqfivcmhyiz5xl2tvq/
bin/pkg-config (found version "1.8.0") 
-- Found NetCDF: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/netcdf-c-4.8.0-5fsxzsez7poccxxw5uuiwt5mkb2fje6p/li
b/libnetcdf.so  
-- Found LibXml2: /home/sberton2/.spack/opt/spack/linux-centos7-skylake/gcc-9.3.0/libxml2-2.9.12-zdl3feki4fd36g4mirntxz6nadikhuqo/l
ib/libxml2.so (found version "2.9.12") 
CMake Deprecation Warning at external/qt-unix-signals/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 2.8.12 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.


-- Using PROJ <6 srs database.
-- Qsci sip file not found - disabling bindings for derived classes
-- Ctest Binary Directory set to: /home/sberton2/.tmp/spack-stage/spack-stage-qgis-3.16.5-kuofr6u4ljajfr2bsmxk2uygrl2gddhx/spack-bu
ild-kuofr6u/output/bin
-- Configuring incomplete, errors occurred!
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

[spack-build-env.txt](https://github.com/spack/spack/files/7186554/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7186555/spack-build-out.txt)

**Comment by Sinan81** [comment]
sorry. I've been on vacation, haven't had a chance to look at it. Will look into it this week or so.

**Comment by Sinan81** [comment]
It seems there are two issues. First one is that QGIS can't find proj include dirs correctly as well as sqlite3 libs. So, qgis package file needs to be modifed as follows:
```diff
diff --git a/var/spack/repos/builtin/packages/qgis/package.py b/var/spack/repos/builtin/packages/qgis/package.py
index ab7f60c..3fc57dd 100644
--- a/var/spack/repos/builtin/packages/qgis/package.py
+++ b/var/spack/repos/builtin/packages/qgis/package.py
@@ -161,7 +161,9 @@ def cmake_args(self):
                     self.spec['geos'].prefix.bin,
                     '-DGSL_CONFIG_PREFER_PATH=' + self.spec['gsl'].prefix.bin,
                     '-DPOSTGRES_CONFIG_PREFER_PATH=' +
-                    self.spec['postgresql'].prefix.bin
+                    self.spec['postgresql'].prefix.bin,
+                    '-DPROJ_INCLUDE_DIR=' + self.spec['proj'].prefix.include,
+                    '-DSQLITE3_LIBRARY=' + self.spec['sqlite'].prefix.lib,
                     ])
```
The second issue is that It seems like `sqlite` package was recently revamped, and that might have broke qgis build.

**Comment by steo85it** [comment]
Thank you! I'm testing it but I'm getting into some issues with qt and gcc@11.2.0 . Trying an older compiler to get at least to the qgis installation step.

**Comment by Sinan81** [comment]
I used gcc@7.4 and spack@0.16.3

**Comment by steo85it** [comment]
and did you manage to compile successfully, or did you still get blocked by the `sqlite` issue you mentioned? I still get an error related to that package (see build output attached), even when using gcc@9.3.0 (just to understand if it's worth installing gcc@7.4 that you used).

[spack-build-out.txt](https://github.com/spack/spack/files/7332244/spack-build-out.txt)

**Comment by Sinan81** [comment]
> and did you manage to compile successfully, or did you still get blocked by the `sqlite` issue you mentioned? I still get an error related to that package (see build output attached), even when using gcc@9.3.0 (just to understand if it's worth installing gcc@7.4 that you used).
> 
> [spack-build-out.txt](https://github.com/spack/spack/files/7332244/spack-build-out.txt)

No, I couldn't compile qgis due to sqlite issue. It seems you're at the same point as me (hence no need to downgrade gcc). As I said the issue seems to be the revamping of the sqlite package. I bet if you used the older versions of the sqlite package file, the build will work just fine. Also, to make sure qgis itself is not the issue, you could also try building a version that is previously known to build successfully (3.10.10).

**Comment by steo85it** [comment]
Thanks! I'm trying to compile with an older sqlite version (but maybe you meant an older version of the spack package itself, I'll test that, too), else I'll try an older qgis, indeed.

**Comment by Sinan81** [comment]
It turns out I built qgis@3.16.15 successfully before, of which spec details is attached below.
[qgis_last_known_build.txt](https://github.com/spack/spack/files/7333756/qgis_last_known_build.txt)
in particular, sqlite was built with the following options:
```
^sqlite@3.35.4%gcc@8.3.0+column_metadata+fts~functions+rtree arch=linux-centos7-skylake
```

**Comment by Sinan81** [comment]
> ... (but maybe you meant an older version of the spack package itself, ...

yep! that's exactly what I meant. I also tried building with sqlite@3.35.4 which failed.

**Comment by Sinan81** [comment]
As shown in the package file, in the revamped sqlite package file, `column_metadata` variant seem to be left in a 'TODO' state which might be a clue to the build issue. I'll look into followings next
```
spack blame sqlite
spack blame -g sqlite
git log -p /path/to/sqlite/package.py
```
, and try to have a basic understanding of what has happened, after which we  can ping the developers who contributed that code if necessary.

**Comment by steo85it** [comment]
Ah, great, thanks! I'll try that, too. For the moment I tested 
`spack install qgis ^sqlite@3.34.0 %gcc@9.3.0`
with the `sqlite` package at commit `76424c1` (Mar-21, with some modification to make it compatible with spack@0.16.2-4279-7e7de25aba), and it failed with the same error as before.

**Comment by steo85it** [comment]
Just as a lazy test, I tried to mimic your last successfull spec with
```
spack install qgis@3.16.5 %gcc@9.3.0 ~3d+analysis~apidoc~astyle+bindings~clang_tidy+core~custom_widgets+desktop+georeferencer~globe~grass7+gui+internal_mdal+internal_o2~ipo+oauth2_plugin~oracle+postgresql~py_compile+qsciapi~qspatialite+qt5serialport~qtmobility~qtwebkit~quick~qwtpolar~server+staged_plugins+thread_local~txt2tags ^sqlite@3.35.4 +column_metadata+fts~functions+rtree
```
(by always including the `sqlite` package from Mar-21, in principle before the last revamp) but it still fails with the same problem. So, no luck with the dumb/brute-force testing...

**Comment by Sinan81** [comment]
my bad. Sqlite library Cmake variable should point to the actual library but not the directory:
```diff
...
+                    '-DSQLITE3_LIBRARY=' + join_path(self.spec['sqlite'].prefix.lib,'libsqlite3.so')
...
```
let's see if this makes a difference at all.

**Comment by Sinan81** [comment]
... and it builds successfully! Sorry, because of the above mentioned mistake we wasted a lot of time.

**Comment by steo85it** [comment]
I'm going to test it, but happy to do it with some confidence in success. Fingers crossed it will work for me, too!

**Comment by steo85it** [comment]
I confirm that qgis installs fine with your latest mod (probably something to commit, too).  Specifically, this worked: `spack install qgis@3.16.5 %gcc@9.3.0`
Thanks a lot for your help!

p.s.: As with my last install, I get an error message when opening the gui: wondering if you are familiar with it.
[gis_gui_error.txt](https://github.com/spack/spack/files/7338322/gis_gui_error.txt)
(it's quite harmless, as I can still open it in the end, but just in case you know how to solve this...)

**Comment by Sinan81** [comment]
I think the error has to do with some recent changes to `qscintilla` package breaking some things and hence QGIS turning of qscintilla support. I'll be looking into this in the following days.

**Comment by steo85it** [comment]
Thanks again, that's anyway not urgent! I'll close this issue, as the initial problem has been solved ( https://github.com/spack/spack/issues/26033#issuecomment-941872244 should be included in qgis package, though, at your convenience - or I can also do it, if you prefer).
