### ISSUE TITLE
Trying to get in touch regarding a security issue

### ISSUE THREAD

**Issue by JamieSlome** [LLNL/spack#26053]
Hey there!

I'd like to report a security issue but cannot find contact instructions on your repository.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by tgamblin** [comment]
Thanks for this suggestion!

I’ve added a `SECURITY.md` file here:

https://github.com/spack/spack/blob/develop/SECURITY.md

**Comment by tgamblin** [comment]
@JamieSlome did you end up reporting this?

**Comment by JamieSlome** [comment]
@tgamblin - an e-mail was sent to `maintainers@spack.io` but was never opened?

You can visit the link directly here:

https://huntr.dev/bounties/8764cd1e-1fb3-465d-8575-5e6a0dbc3223/
