### ISSUE TITLE
[Packaging guide] document recommendations for running tests

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#2605]
Document that contributors should NOT add a variant `test` but instead use `self.run_tests`. Explain that the reason is that running installation tests does not change the installed package per-se, it's not really a variant in this sense. It's just an optional step during `spack install`.

**Comment by tgamblin** [comment]
Maybe I'm not remembering correctly, but it would be really nice if we could add a test function to `Package` now, so that the post-install tests could be run with, say, a `spack pkg-test <pkg>` command.

**Comment by davydden** [comment]
> it would be really nice if we could add a test function to Package now, so that the post-install tests could be run with, say, a spack pkg-test <pkg> command.

the issue was related to tests during installation, but I agree, a separate post-install function is nice to have. We already have a good discussion in this topic here https://github.com/LLNL/spack/issues/2060

**Comment by alalazo** [comment]
> the issue was related to tests during installation, but I agree, a separate post-install function is nice to have

This requires a bit of analysis of the use cases we have though. Post-install tests are quite heterogeneous, e.g.:

- link tests we added like in the case of `openblas`
- tests that come with the package require some folder that was in the stage area
- tests that trigger some command from package `prefix`

and we need to be able to run any of those in a way that is transparent to users.

**Comment by davydden** [comment]
> This requires a bit of analysis of the use cases we have though. 

let's keep the discussion in one place --  #2060, several of those usage cases are already mentioned there.
