### ISSUE TITLE
Installation issue: rocblas

### ISSUE THREAD

**Issue by cgmb** [LLNL/spack#26139]
### Steps to reproduce the issue

```console
spack install rocblas@4.0.0
```
Full spec: [spec.txt](https://github.com/spack/spack/files/7208110/spec.txt)

On attempting to install, I see a number of warnings like this:
```
     570    Warning: The specified HIP target: gfx906:xnack- is unknown. Correct compilation is not guaranteed.
```

Followed by errors such as this one:
```
  >> 584    clang-12: error: Invalid offload arch combinations: gfx906 and gfx906:xnack- (For a specific processor, a feature should either exist in all offload archs, or not exist in any offload archs)
     585    Tensile/lib/CMakeFiles/TensileHost.dir/build.make:204: recipe for target 'Tensile/lib/CMakeFiles/TensileHost.dir/source/TensorDescriptor.cpp.o' failed
```

### Information on your system

* **Spack:** 0.16.2-4341-a8977f828e
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-zen2
* **Concretizer:** clingo

### Additional information

@arjun-raj-kuppala @haampie @srekolam
[spack-build-env.txt](https://github.com/spack/spack/files/7208102/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7208103/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by bernhardkaindl** [comment]
https://releases.llvm.org/  -> 14 Apr 2021 | 12.0.0
https://github.com/ROCmSoftwarePlatform/rocBLAS/tags -> rocm-4.0.0 on Nov 10, 2020

Hence, rocBLAS 4.0.0 is far too old to be compile-tested with clang-12 on release day Nov 10, 2020.

You'll likely have to select a newer release of `rocblas` or use an older compiler.

installing `rocblas@4.0.0 %gcc@8.4.0` on Ubuntu 18.0.4 running on  AMD Rome(zen2) worked fine:
```
spack find -v rocblas
==> 1 installed package
-- linux-ubuntu18.04-zen / gcc@8.4.0 ----------------------------
rocblas@4.0.0~ipo build_type=RelWithDebInfo tensile_architecture=all

opt/spack/linux-ubuntu18.04-zen/gcc-8.4.0/rocblas-4.0.0-rxjvb5cywx5rzrvfrin3gjodhnwa5jt2/rocblas/lib/librocblas.so.0.1
```
Have you tried `rocblas@4.3.1` - which is the current version?
```
spack checksum rocblas
==> Found 10 versions of rocblas:
  
  4.3.1   https://github.com/ROCmSoftwarePlatform/rocBLAS/archive/rocm-4.3.1.tar.gz
  4.3.0   https://github.com/ROCmSoftwarePlatform/rocBLAS/archive/rocm-4.3.0.tar.gz
  4.2.0   https://github.com/ROCmSoftwarePlatform/rocBLAS/archive/rocm-4.2.0.tar.gz
  4.1.0   https://github.com/ROCmSoftwarePlatform/rocBLAS/archive/rocm-4.1.0.tar.gz
...
```

**Comment by srekolam** [comment]
it is working fine with 4.3.1 ..But while submitting a PR  #25917, cory bloor recently has observed the failure on 4.0.0 for rocblas and i have suggested to log this issue. During the update of spack rocm recipes for 4.0.0 we were sure that it was working and later changes for 4.1.0 seems to have induced this failure..

**Comment by bernhardkaindl** [comment]
> it is working fine with 4.3.1 ..But while submitting a PR #25917, cory bloor recently has observed the failure on 4.0.0 for rocblas and i have suggested to log this issue. During the update of spack rocm recipes for 4.0.0 we were sure that it was working and later changes for 4.1.0 seems to have induced this failure..

When the  spack rocm recipes were updated for 4.0.0, clang-12.0.0 (released 14 April) wasn't going to be released until 3 further months in the future (see the date, Jan 5):
```yaml
commit f4acf74091d6d6e2e9914bf9380ffde1cfb1ca4f
Author: Sreenivasa Murthy Kolam <67086238+srekolam@users.noreply.github.com>
Date:   Tue *Jan 5 04:32:03 2021* +0530

    bump up rocm math libs recipes for rocm-4.0.0 release (#20651)
```
This means it cannot have been clang@12 back then: it must have been some other or older compiler, as you see!

**Comment by srekolam** [comment]
the llvm-amdgpu@4.0.0 i have just installed - and it shows below- 
/spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.4.1/llvm-amdgpu-4.0.0-4zmj2rrcj2h6tjl5v6vxea5lvpfgmb6c/bin/clang --version
clang version 12.0.0
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /spack/opt/spack/linux-centos8-skylake_avx512/gcc-8.4.1/llvm-amdgpu-4.0.0-4zmj2rrcj2h6tjl5v6vxea5lvpfgmb6c/bin

**Comment by bernhardkaindl** [comment]
> InstalledDir: /spack/opt/spack/linux-centos8-skylake_avx512/**gcc-8.4.1** :+1: /llvm-amdgpu-4.0.0-4zmj2rrcj2h6tjl5v6vxea5lvpfgmb6c/bin

:+1:  **Thanks, good! I said before, with gcc-8.4.0 :+1: , it works just fine!** :1st_place_medal: 

-> (This spack install was using **gcc-8.4.1** :+1:  (see it marked in **bold** above), and also this build is now on *centos8*, not on Ubuntu 18.04 as before!. This means you now used completely different compiler and host distribution :+1: - Good: not clang-12! :-1: )

### This solved your problem, right?

---------
It seems you want to use clang-12 to compile rocblas, but just don't to it, use gcc. You built clang-12, but you didn't load and specify that spack shall use it when building rocblas: That's why it used the standard gcc-8.4.1.

For clang: spack could add a message to not use `clang@12` as compiler for `rocblas@4.0.0`.

This would tell you when clang@12 would be selected as compiler and reject it for rocblas, at least for older releases:

We'd add this to `var/spack/repos/builtin/packages/rocblas/package.py`:
```py
   conflicts('%clang@12', when='@:4.2',
          msg='rocblas <= v4.3.1 cannot be built with Clang 12, '
              'please use a newer release or an older compiler')
```

**Comment by cgmb** [comment]
I don't have the actual Clang 12 compiler installed on my system. Just llvm-amdgpu@4.0.0. The ROCm fork of clang (llvm-amdgpu) is based on the development version of Clang, so it will tend to report version numbers higher than the most recent official Clang release. At the time, of the 4.0.0 release, the version it reported was Clang 12, so the version string there isn't cause for concern.

I think this problem is because ROCm 4.0.0 and earlier did not support specifying target-features like xnack via the target-id (aka. amdgpu_target). I would have expected [this check in the rocBLAS package](https://github.com/spack/spack/blob/2c9dfcabf8aa530b6c5bdb35bd1862ef6eed4c68/var/spack/repos/builtin/packages/rocblas/package.py#L85-L87) would prevent the issue, but it's somehow still getting xnack-.

**Comment by cgmb** [comment]
Oh, you know what I might have screwing things up? A newer version of ROCm installed into /opt/rocm. I'll see if I can reproduce this problem in a clean ubuntu:18.04 container.

**Comment by haampie** [comment]
We're jumping through a lot of hoops not to pick up system stuff in /opt/rocm, if only the rocm ecosystem could drop its references to that location... Providing it in cmake hints is borderline acceptable maybe.

**Comment by bernhardkaindl** [comment]
Hi Cory @cgmb ! 
> Oh, you know what I might have screwing things up? A newer version of ROCm installed into /opt/rocm. I'll see if I can reproduce this problem in a clean ubuntu:18.04 container.

I don't know rocblas at all, sorry I should not even look at this issue, but maybe yes, I don't know!

Now I understand a bit more, you refer to this check:
```
    def cmake_args(self):
        arch = self.spec.variants['tensile_architecture'].value
        if self.spec.satisfies('@4.1.0:'):
            if arch == 'gfx906' or arch == 'gfx908':
                arch = arch + ':xnack-'
```
First:
```py
 if self.spec.satisfies('@4.1.0:'):
```
This looks correct, so what follows is only executed for rocblas@4.1.0 and newer (is this what you intented?)

Then, there is: 
```py
        arch = self.spec.variants['tensile_architecture'].value
        if self.spec.satisfies('@4.1.0:'):
            if arch == 'gfx906' or arch == 'gfx908':
                arch = arch + ':xnack-'
```
So if `self.spec.variants['tensile_architecture'].value` is either `gfx906` or `gfx908`, then
```
                arch = arch + ':xnack-'
```
This done. Does this enable xnack or disable it? I assume it enables xnack but what if it tried to enable it by default?

Just from a coding style (and readability) viewpoint, it would be nicer if you would move getting, modifying and using `arch` together so there is only one place to look at:
```py
        arch = self.spec.variants['tensile_architecture'].value
        # A comment here, what the purpose of this is, like you described above would be good to understand:
        # ROCm 4.0.0 and earlier did not support specifying target-features like xnack via the target-id (aka. amdgpu_target).
        if self.spec.satisfies('@4.1.0:'):
            if arch == 'gfx906' or arch == 'gfx908':
                arch = arch + ':xnack-'
        # See https://github.com/ROCmSoftwarePlatform/rocBLAS/commit/c1895ba4bb3f4f5947f3818ebd155cf71a27b634
        if self.spec.satisfies('@:4.2.0'):
            args.append(self.define('Tensile_ARCHITECTURE', arch))
        else:
            args.append(self.define('AMDGPU_TARGETS', arch))
```
Sorry I don't now rocblas, I'll shut off now :)

**Comment by bernhardkaindl** [comment]
> We're jumping through a lot of hoops not to pick up system stuff in /opt/rocm, if only the rocm ecosystem could drop its references to that location... Providing it in cmake hints is borderline acceptable maybe.

Sounds like it would be really good to use some form of `fakechroot` (https://github.com/dex4er/fakechroot like I think I have read in some proposal for spack) as soon as possible.

**Comment by srekolam** [comment]
I am not seeing this issue ..i took a fresh centos docker container and installed the spack and was able to build it rocblas@4.0.0 with out any failures

**Comment by haampie** [comment]
> Sounds like it would be really good to use some form of fakechroot (https://github.com/dex4er/fakechroot like I think I have read in some proposal for spack) as soon as possible.

Yeah, but it's diffcult with externals, and spack itself has many system dependencies

**Comment by cgmb** [comment]
> We're jumping through a lot of hoops not to pick up system stuff in /opt/rocm, if only the rocm ecosystem could drop its references to that location... Providing it in cmake hints is borderline acceptable maybe.

That complaint has been heard, and it's something we're working towards.

Spack is pretty good at surfacing those sorts of bugs in our build system. Finding environment-related defects one of the main reasons why I've been getting involved with Spack. I'd really like to identify and fix more issues before each library release, rather than patching things up after.

> I am not seeing this issue ..i took a fresh centos docker container and installed the spack and was able to build it rocblas@4.0.0 with out any failures

That lends further credence the the theory that the problem is my environment. I'll update when I figure out exactly what's going on.

**Comment by haampie** [comment]
> Spack is pretty good at surfacing those sorts of bugs in our build system. Finding environment-related defects one of the main reasons why I've been getting involved with Spack. I'd really like to identify and fix more issues before each library release, rather than patching things up after.

Yay, I'm very happy to hear that. Secretly I was hoping that AMD would consider using spack during development :D Apart from finding these bugs (or let's say, non-standard installation issues), Spack is also really good at listing the huge number of environment variables that are scattered around the place: https://github.com/ROCm-Developer-Tools/HIP/issues/2224. One the main offenders there is `ROCM_PATH`. What does that even mean.

**Comment by srekolam** [comment]
@cgmb  can we close this ticket ? let me know what you think ?

**Comment by cgmb** [comment]
> One the main offenders there is ROCM_PATH. What does that even mean.

I don't know. I will watch that issue with interest.

> can we close this ticket ?

It's probably not a Spack issue, but I would like to pin down the cause so we can say so with certainty. That said, I have a lot on my plate... if you don't hear back from me by Oct 7th (1 week), go ahead and close this.

**Comment by cgmb** [comment]
I had set up my `PATH` as per the [ROCm Installation docs](https://rocmdocs.amd.com/en/latest/Installation_Guide/Installation-Guide.html#ubuntu), which breaks [the Spack guidelines for a clean environment](https://spack.readthedocs.io/en/latest/getting_started.html#clean-environment). Given that this was something directly warned about in the docs, it's not too surprising that there were problems.
