### ISSUE TITLE
libbfd.so: undefined reference to `libintl_dgettext'

### ISSUE THREAD

**Issue by jgalarowicz** [LLNL/spack#2613]
Has something changed in the binutils build lately that would cause this undefined reference (libintl_dgettext)?

My cbtf-krell build now fails with the latest develop branch, with no changes in my code.

Thanks for any clues on how to resolve.

Jim G

Partial build output:
/home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/binutils-2.24-ncmqjaexykxcxxgh3cezjfpvnwvtw7rr/lib/libbfd.so: undefined reference to `libintl_dgettext'
collect2: error: ld returned 1 exit status
make[2]: *** [core/daemonTool/daemonTool] Error 1
make[2]: Leaving directory `/tmp/jeg/spack-stage/spack-stage-nNY8iB/cbtf-krell/build_cbtf_krell'
make[1]: *** [core/daemonTool/CMakeFiles/daemonTool.dir/all] Error 2
make[1]: Leaving directory `/tmp/jeg/spack-stage/spack-stage-nNY8iB/cbtf-krell/build_cbtf_krell'
make: *** [all] Error 2

**Comment by adamjstewart** [comment]
You could try adding a `depends_on('gettext')` to the binutils package and reinstalling. You would test it by running:
```
ldd -r $BINUTILS_ROOT/lib/libbfd.so
```

**Comment by jgalarowicz** [comment]
Hi Adam,
Thanks for the suggestions.  It appears that didn't do the trick.  Still have the undefined.
I added the depends_on('gettext') to the binutils package and reinstalled binutils after uninstalling it.

[jeg@localhost packages]$ lsr /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3//binutils-2.24-ncmqjaexykxcxxgh3cezjfpvnwvtw7rr/lib/libbfd.so
0 lrwxrwxrwx. 1 jeg jeg 14 Dec 16 13:48 /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3//binutils-2.24-ncmqjaexykxcxxgh3cezjfpvnwvtw7rr/lib/libbfd.so -> libbfd-2.24.so
[jeg@localhost packages]$ ldd /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3//binutils-2.24-ncmqjaexykxcxxgh3cezjfpvnwvtw7rr/lib/libbfd.so
	linux-vdso.so.1 =>  (0x00007fffdfffe000)
	libz.so.1 => /lib64/libz.so.1 (0x00007fb245ff7000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fb245c36000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003d9e400000)
[jeg@localhost packages]$ nm !$ | grep libintl_dgettext
nm /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3//binutils-2.24-ncmqjaexykxcxxgh3cezjfpvnwvtw7rr/lib/libbfd.so | grep libintl_dgettext
                 U libintl_dgettext

**Comment by tgamblin** [comment]
This is in the gettext FAQ:
https://www.gnu.org/software/gettext/FAQ.html#integrating_undefined

**Comment by schulzm** [comment]
I am running into this as well - it seems to be a bug unrelated to the actual Open|SpeedShop packages, but something made to glib or its dependencies (my guess right now is automake) - from what I can tell, the problem got introduced in "664939eeba8d086106e6154a897214d2da7fe09d", which makes global changes to the automake module, but I don't know the source well enough to tell for sure

**Comment by tgamblin** [comment]
@schulzm and @jgalarowicz: did you check the `gettext` FAQ above?  It looks like the same issue to me.

**Comment by jgalarowicz** [comment]
I looked at it but, where is the change supposed to go?  It seems like that is a binutils build/usage issue.  If that is the case, then someone changed the build or the code lately.   I haven't changed any of the OSS/CBTF files.

**Comment by jgalarowicz** [comment]
Oh. I didn't see Martins comment.

**Comment by schulzm** [comment]
Yes, it seems that the change is unrelated to O|SS - the other commit seems to have broken the build for glib, at least for the version O|SS needs. The FAQ gives a wide range of reasons why this could have happened, but I am not sure I can really dig into this. This shouldn't really happen, though - how can a commit for an unrelated package break this build?

One thing I noticed, though, is that the checkin I mentioned seems to fix versions of other dependencies, even though the module seems to be intended as a general module. Is this right? 

I also noticed that the dependency tree (spack graph) changes for glib after the commit (it removes autoconf from the dependencies), which seemed strange.

**Comment by tgamblin** [comment]
@jgalarowicz: The bug happens when you use `gettext` after including `libintl.h`.  So if something you're using does that, of maybe some part of `bfd` does.

In 664939e, it looks like @adamjstewart a dependency on `gettext` to `flex`, but `binutils` doesn't seem to depend on `gettext`.  I suspect you're getting the header transitively through the dependency on `flex` and it's remapping your `gettext` call to `libintl_gettext` as per the link I sent above.

**Comment by schulzm** [comment]
binutils doesn't, but glib does (based on spack graph glib)

**Comment by tgamblin** [comment]
@schulzm: the linker error is because `libbfd.so` has an undefined reference to `libintl_gettext`.

**Comment by schulzm** [comment]
Doesn't this mean, though, that the changes to flex are the problem and should be taken out? If this breaks a lower level library that others rely on, that new dependency to flex is the issue? It shouldn't be on the higher library/app depending on this to fix it. Or am I not understanding the problem correctly? Was the initial package file before the flex addition broken?

**Comment by tgamblin** [comment]
@schulzm: it's on you and @jgalarowicz to fix it, at least until we have better package testing.  It's affecting the OSS build but no one else is reporting this.  That might involve modifying some other package file.

**Comment by schulzm** [comment]
@tgamblin That can't be the solution - the fix that would work for O|SS is to remove the dependency for flex, which caused the problem (but that obviously has other consequences). The other option would be to change the code of binutils to change the order of the include, which sounds even worse to me. It can't be that adding a new code or library to the build system requires us to change standard low level library code.

**Comment by jgalarowicz** [comment]
I'm looking at the daemonTool build and I'm not sure that we even need libbfd.so in that build.  I'm checking with Don on that now.   Not sure if the problem will show up elsewhere.  I'll update this when I here from Don.

**Comment by schulzm** [comment]
One thing to add, which may have caused the confusion - I get the same error as Jim, but the location is actually different - I do get it during the build of glibc and there it fails during the automake process - it says in the log:

checking for ngettext in -lintl... no
configure: error: 
*** You must have either have gettext support in your C library, or use the
*** GNU gettext library. (http://www.gnu.org/software/gettext/gettext.html

That's why I pointed at the glibc changes that are stemming from the flex change. If I run the same install with the previous commit, the automake for glibc works. Binutils is not involved in this (as far as I can tell). I can't see what the automake process actually tries - is there a way to turn this on within the logging of spack?

**Comment by adamjstewart** [comment]
Hi, sorry if my changes in #2401 caused any problems for you. I initially added the `gettext` dependency to `flex` because `flex` searches for `gettext` during `./configure`:
```
checking for msgfmt... /Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/gettext-0.19.8.1-mnwetocmx2ve7soyab5vhfnydpifnlye/bin/msgfmt
checking for gmsgfmt... /Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/gettext-0.19.8.1-mnwetocmx2ve7soyab5vhfnydpifnlye/bin/msgfmt
checking for xgettext... /Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/gettext-0.19.8.1-mnwetocmx2ve7soyab5vhfnydpifnlye/bin/xgettext
checking for msgmerge... /Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.0.0-apple/gettext-0.19.8.1-mnwetocmx2ve7soyab5vhfnydpifnlye/bin/msgmerge
```
I'm not sure what `flex` needs `gettext` for, so I decided to play it safe and add the dependency. I just tried building `flex` without `gettext`, and it seems to build fine. So if this is causing problems for you, feel free to remove it and submit a PR.

Let me know if I can help in any way.

**Comment by schulzm** [comment]
Thanks! I'll give this a try.

**Comment by schulzm** [comment]
I tried to remove the dependency, but the result was the same. Then I tried backing out all the changes in the commit and prior flex commit that updated the flex versions. This got me over the problem (but then caused a problem in the boost install - I don't know, yet, if those are related). What else could the changes in #2401 have influenced?

**Comment by jgalarowicz** [comment]
I took out the references to libbfd.so in two places in cbtf-krell.  It turns out that those were not needed.  cbtf-krell now builds for me on my laptop where I do most of my development.  I checked in the source changes, so if you want, the changes are available to try.

**Comment by jgalarowicz** [comment]
Closing this because it no longer impacts the OpenSpeedShop build.

**Comment by noloader** [comment]
Also see [I get a linker error “undefined reference to libintl_gettext”](https://www.gnu.org/software/gettext/FAQ.html#integrating_undefined) in the GetText FAQ.
