### ISSUE TITLE
packages using prefix/lib and prefix/lib64

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#2617]
from @tgamblin 

> We may want to have spack packages standardize on either lib or lib64. Each package builds for one architecture so there isn't really a reason to have both. Also, with views people symlink packages into a common prefix. I'd like to make views more common/automatic but it's awkward to load views into the environment if different packages in the same view have different lib directories. I'm trying to think of a reason we wouldn't want to force one or the other of lib/lib64.

This would be good to have, but it may be difficult to implement as one needs a specific OS to encounter such behaviour (i.e. `netcdf-cxx` installs to `lib` on `ubuntu 16.04`, but uses `lib64` on `opensuse tumbleweed`). Also some packages may not have an option to control libs location, then one would need to move libs post-install and if there are more than one, do extra patching.

Taking the above into account, I think it may be easier to address such problems with https://github.com/LLNL/spack/pull/1875 where each package would know things about itself.

**Comment by citibeth** [comment]
You mean Spack still supports 32-bit?  Raise your hand if you have a 32-bit HPC cluster...

`/lib64` was a hack to support 32-bit and 64-bit libraries simultaneously, when we were just beginning to make the switch to 64-bit architecture.  Those days are hopefully now behind us, with everything converted to 64-bit mode.  32-bit Linux builds are no being retired:

https://linux.slashdot.org/story/16/07/05/1838245/linux-letting-go-32-bit-builds-on-the-way-out

Given that reality, I suggest we standardize on putting things in `lib/` whenever possible.  For stubborn packages that insist of putting them in `lib64`, we add the following symlink post-install: `ln -s lib64 lib`.  Spack views would merge `lib64` and `lib` into `lib`, of course.

> Also some packages may not have an option to control libs location, then one would need to move libs post-install and if there are more than one, do extra patching.

Let's not move libs post-install, that can always cause problems.  Symlink instead.

> I'd like to make views more common/automatic

The "automatic" word scares me a bit.  I have no personal interest in using views, and would not want to feel like they are being forced on me.

**Comment by davydden** [comment]
> You mean Spack still supports 32-bit?

no, i mean different packages still install libs in different locations, most of the time it's `prefix/lib`, but on some OS it's `prefix/lib64`.

> For stubborn packages that insist of putting them in lib64, we add the following symlink post-install: ln -s lib64 lib. 

good point, that's far easier than trying to move libs.

> would not want to feel like they are being forced on me.

same here.

**Comment by adamjstewart** [comment]
> I suggest we standardize on putting things in `lib/` whenever possible.

We also need to support externally installed packages, which we have no control over.

I'm actually in the middle of 32-bit library headaches due to a couple legacy software packages that have not yet been ported to 64-bit and require 32-bit dependencies. Trying to compile a 32-bit glibc library? Not fun.

**Comment by davydden** [comment]
> We also need to support externally installed packages, which we have no control over.

agreed. That's one of the reasons I like https://github.com/LLNL/spack/pull/1875

**Comment by adamjstewart** [comment]
#1875 is merged now. Can this issue be closed?

**Comment by davydden** [comment]
yes, let's close it.

**Comment by cpraveen** [comment]
I am facing this issue. On opensuse tumbleweed, libhdf5.a is in lib64 but on my other debian systems it is in lib. I am using spack view. Do you have a suggestion on how to deal with this.

**Comment by davydden** [comment]
@cpraveen yes, you need to patch whoever is using `hdf5` to NOT hard-code `spec['hdf5'].prefix.lib`, but rather use `spec['hdf5'].libs.directories[0]`. What happens is that `libs` return an instance of `LibraryList` class which you can query for extra things.

@alalazo do you know why [documentation](http://spack.readthedocs.io/en/latest/llnl.util.html#llnl.util.filesystem.LibraryList) of this class does not show `directories`?

**Comment by adamjstewart** [comment]
> do you know why documentation of this class does not show `directories`?

Because it is not defined in `LibraryList`. It is common to both `LibraryList` and `HeaderList`, so it is in the base class of both of those. Not sure why `FileList` isn't showing up in the docs though...

**Comment by davydden** [comment]
> Because it is not defined in LibraryList. It is common to both LibraryList and HeaderList,

ah, of course! Thanks! I will create an issue so that we remember to fix it...

**Comment by junghans** [comment]
Some package have `-DCMAKE_INSTALL_LIBDIR=self.prefix.lib`.

**Comment by davydden** [comment]
> Some package have -DCMAKE_INSTALL_LIBDIR=self.prefix.lib.

Unfortunately, it won't help with `hdf5` which is an AutotoolsPackage

**Comment by davydden** [comment]
but maybe there is an equivalent, this would be much easier fix!

**Comment by davydden** [comment]
Interestingly enough, `hdf5` also supports `cmake`. But from `configure`, i see
```
--libdir=DIR            object code libraries [EPREFIX/lib]
```
@cpraveen :

>  I am facing this issue. On opensuse tumbleweed, libhdf5.a is in lib64

do you use `hdf5` installed by Spack or externally provided? 

If it is installed by Spack into `lib64`, you can try modifying the package to explicitly set
```
extra_args = ['--libdir={0}'.format(self.prefix.lib)]
```

**Comment by junghans** [comment]
While we are at it, let's add `includedir` and `bindir` as well.

**Comment by cpraveen** [comment]
@davydden hdf5 was installed with Spack. I have no problem compiling other spack packages that depend on hdf5. In my own application, I use a simple makefile and there I had problem in finding the correct directory where libhdf5.a was located. I used a check and this seems to work ok
```
      ifneq ("$(wildcard $HDF5_DIR/lib/libhdf5.a)","")
         LDFLAG := $(HDF5_DIR)/lib/libhdf5.a $(LDFLAG)
         LDFLAG := $(HDF5_DIR)/lib/libhdf5_cpp.a $(LDFLAG)
      else
         LDFLAG := $(HDF5_DIR)/lib64/libhdf5.a $(LDFLAG)
         LDFLAG := $(HDF5_DIR)/lib64/libhdf5_cpp.a $(LDFLAG)
      endif
```

**Comment by davydden** [comment]
@cpraveen 

> I have no problem compiling other spack packages that depend on hdf5

so what is the problem then? 

p.s. Spack uses RPATH so (ideally) it never relies on environment variables in any way. As I said above `spec['hdf5'].libs.directories[0]` will get you the right directory both for `lib` and `lib64`, see http://spack.readthedocs.io/en/latest/llnl.util.html?highlight=LibraryList#llnl.util.filesystem.LibraryList
