### ISSUE TITLE
Bootstrap disregards command line scopes

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#26189]
### Steps to reproduce

When running `spack -C my_config_scope spec zlib` Spack disregards `my_config_scope` during bootstrapping.

I haven't checked what the behavior of `spack -c x:y:z spec zlib` is during bootstrapping.

I have to be able to specify the staging dir on the command line in some way, also the one used during bootstrapping.

**Comment by alalazo** [comment]
Copying the original report from https://github.com/spack/spack/pull/26071#issuecomment-925881559

> I'm already experiencing this issue on develop:
> 
> I have a pipeline testing different Spack versions fixed at different commits in parallel / in a matrix. I don't want them to have a shared database, as Spack 0.16 and 0.17 are incompatible. The database ensures spack is multiprocess-safe, so I can't rely on that. If I don't specify the stage dir to something unique, Spack breaks during the install of patchelf, because one process cleans up the stage dir as another starts to use it.
>
> So what I do is I specify a config scope on the command line spack -C path/to/$SPACK_VERSION install x which makes it easy to setup config for a particular spack version where I can also set the stage dir.
> 
> But this -C scope is not respected during the bootstrap phase anymore, so I get race conditions :(.

**Comment by alalazo** [comment]
> The database ensures spack is multiprocess-safe, so I can't rely on that. If I don't specify the stage dir to something unique, Spack breaks during the install of patchelf, because one process cleans up the stage dir as another starts to use it.

Besides the issue that there is configuration that we may want to use during bootstrap (as opposed to other that we want to disregard), I think this needs investigation. My understanding is that we should have locks also for the stages, so that if another Spack process is trying to write in a stage that is currently being used it should block and wait.

**Comment by alalazo** [comment]
Can you report where (on which system) this is happening?

**Comment by haampie** [comment]
Piz Daint, but I don't think it's machine specific?

**Comment by alalazo** [comment]
It might be machine specific or a bug in the locks / locking logic. The file system needs to support `fcntl` byte range file locks. The point is that there are two different locks for the store and the staging area, so:

> The database ensures spack is multiprocess-safe, so I can't rely on that. If I don't specify the stage dir to something unique, Spack breaks during the install of patchelf, because one process cleans up the stage dir as another starts to use it.

is a non-sequitur. The config scope issue should be solved in #26071.

**Comment by haampie** [comment]
Hm ok, staging dir is likely a tmpfs/ramfs, I'll check tomorrow

**Comment by haampie** [comment]
The lock tests work on that filesystem btw, so maybe a bug?
