### ISSUE TITLE
Installation issue: GCC on BigSur aarch64

### ISSUE THREAD

**Issue by ax3l** [LLNL/spack#26317]
### Steps to reproduce the issue

Hi,

I got a new macOS Mini (aarch64 with BigSur).

I am trying to bootstrap Spack on it. After installing Xcode, the following compilers are found:
```yaml
compilers:
- compiler:
    spec: apple-clang@12.0.5
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: null
      fc: null
    flags: {}
    operating_system: bigsur
    target: aarch64
    modules: []
    environment: {}
    extra_rpaths: []
```

So I need a GFortran or similar to get OpenMPI installed for basic HPC developer stacks.

Running `spack install gcc`fails with:
```
==> Installing gcc-11.2.0-nkmjtouovrvhwal6ced5jnivv73vfru5
==> No binary for gcc-11.2.0-nkmjtouovrvhwal6ced5jnivv73vfru5 found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/d0/d08edc536b54c372a1010ff6619dd274c0f1603aa49212ba20f7aa2cda36fa8b.tar.xz
==> Applied patch /Users/axel/src/spack/var/spack/repos/builtin/packages/gcc/darwin/gcc-7.1.0-headerpad.patch
==> Ran patch() for gcc
==> gcc: Executing phase: 'autoreconf'
==> gcc: Executing phase: 'configure'
==> gcc: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8' 'V=1'

3 errors found in build log:
     3704    checking for F_SETLKW... yes
     3705    checking for O_CLOEXEC... yes
     3706    checking for AF_UNIX... yes
     3707    checking for AF_INET6... yes
     3708    checking if mkdir takes one argument... no
     3709    *** Configuration aarch64-apple-darwin20.6.0 not supported
  >> 3710    make[2]: *** [configure-stage1-gcc] Error 1
  >> 3711    make[1]: *** [stage1-bubble] Error 2
  >> 3712    make: *** [all] Error 2

See build log for details:
  /var/folders/wy/w22w0mkx67711r3m3t98_g7m0000gn/T/axel/spack-stage/spack-stage-gcc-11.2.0-nkmjtouovrvhwal6ced5jnivv73vfru5/spack-build-out.txt
```

### Information on your system

* **Spack:** 0.16.3-4507-32b5669e8d
* **Python:** 3.9.7
* **Platform:** darwin-bigsur-m1
* **Concretizer:** cling

### Additional information

* [spack-build-01-autoreconf-out.txt](https://github.com/spack/spack/files/7247823/spack-build-01-autoreconf-out.txt)
* [spack-build-02-configure-out.txt](https://github.com/spack/spack/files/7247824/spack-build-02-configure-out.txt)
* [spack-build-03-build-out.txt](https://github.com/spack/spack/files/7247825/spack-build-03-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/7247826/spack-build-env.txt)
* [spack-build-out.txt](https://github.com/spack/spack/files/7247827/spack-build-out.txt)
* [spack-configure-args.txt](https://github.com/spack/spack/files/7247828/spack-configure-args.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by ax3l** [comment]
Possible that GCC does not support aarch64 Darwin yet?
```
*** Configuration aarch64-apple-darwin20.6.0 not supported
```

**Comment by ax3l** [comment]
Looks like
  https://github.com/iains/gcc-darwin-arm64
will earliest land in GCC 12
  https://gcc.gnu.org/pipermail/gcc/2021-September/237340.html

**Comment by sethrj** [comment]
Alas! Thanks for being the one to discover this.

**Comment by ax3l** [comment]
My pleasure. I started formulating a conflict in PR #26318.
Having some trouble there to find the right spec atm :sweat_smile:

**Comment by certik** [comment]
Here is how to get GFortran 11 working today on Apple M1:
```console
$ conda create -n gf gfortran compiler-rt=11.1.0
$ conda activate gf
$ cat examples/expr2.f90
program expr2
implicit none

integer :: x

x = (2+3)*5
print *, x

end program
$ gfortran examples/expr2.f90 
$ ./a.out 
          25
$ file a.out
a.out: Mach-O 64-bit executable arm64
$ gfortran -v       
Using built-in specs.
COLLECT_GCC=gfortran
COLLECT_LTO_WRAPPER=/Users/certik/miniforge3/envs/gf/libexec/gcc/arm64-apple-darwin20.0.0/11.0.1/lto-wrapper
Target: arm64-apple-darwin20.0.0
Configured with: ../configure --prefix=/Users/certik/miniforge3/envs/gf --build=x86_64-apple-darwin13.4.0 --host=arm64-apple-darwin20.0.0 --target=arm64-apple-darwin20.0.0 --with-libiconv-prefix=/Users/certik/miniforge3/envs/gf --enable-languages=fortran --disable-multilib --enable-checking=release --disable-bootstrap --disable-libssp --with-gmp=/Users/certik/miniforge3/envs/gf --with-mpfr=/Users/certik/miniforge3/envs/gf --with-mpc=/Users/certik/miniforge3/envs/gf --with-isl=/Users/certik/miniforge3/envs/gf
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.0.1 20210403 (experimental) (GCC) 
```

How does Conda do it and why Spack cannot do it?

**Comment by sethrj** [comment]
@certik it looks like that version was cross-compiled targeting an M1 but built on an x86. I'm assuming the problem  is that GCC itself won't compile on an M1, so you can't use spack to build it natively. Maybe you could use spack to build GCC on an x86 mac with `target=m1`, and then use a buildcache to "install" it on an M1?

**Comment by certik** [comment]
Yes, conda-forge is using the Intel macOS on Azure and they cross compile to M1. I tested it and it works very well. It's interesting that GCC itself does not build on M1. I didn't realize that. So that explains it.

**Comment by ax3l** [comment]
> How does Conda do it and why Spack cannot do it?

Agree with all the above about the cross-compiled compiler.
On top of that, I think conda-forge did build the fork in https://github.com/spack/spack/issues/26317#issuecomment-929700562 as soon as M1 was released.
