### ISSUE TITLE
Installation issue: gdb@11.1

### ISSUE THREAD

**Issue by zzzoom** [LLNL/spack#26354]
### Steps to reproduce the issue

```console
$ spack install gdb@11.1
[+] /usr (external python-3.6.8-42zz3vk7tj5ooiq2s33wqd4zx2njlxqj)
[+] /usr (external texinfo-6.5-uzihy7vowlztilxfy6wrzmos226rgcqn)
[+] /usr (external xz-5.2.4-aznlbqrcwv5pwolhte6xmvjwtvjrduaq)
==> Installing gdb-11.1-bqvgcs4nr4rbb57x24tldnlbcv3mpmqy
==> No binary for gdb-11.1-bqvgcs4nr4rbb57x24tldnlbcv3mpmqy found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/cc/cc2903474e965a43d09c3b263952d48ced39dd22ce2d01968f3aa181335fcb9c.tar.gz
==> Applied patch /home/bc/spack/var/spack/repos/builtin/packages/gdb/gdb-libintl-11.patch
==> gdb: Executing phase: 'autoreconf'
==> gdb: Executing phase: 'configure'
==> gdb: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16' 'V=1'

1 error found in build log:
     5318    checking size of unsigned __int128... 16
     5319    checking for library containing dlopen... none required
     5320    checking whether to use expat... auto
     5321    checking for libexpat... no
     5322    configure: WARNING: expat is missing or unusable; some features may be unavailable.
     5323    checking for libgmp... no
  >> 5324    configure: error: GMP is missing or unusable
     5325    make[1]: *** [Makefile:10420: configure-gdb] Error 1
     5326    make[1]: Leaving directory '/tmp/bc/spack-stage/spack-stage-gdb-11.1-bqvgcs4nr4rbb57x24tldnlbcv3mpmqy/sp
             ack-src/spack-build'
     5327    make: *** [Makefile:903: all] Error 2

See build log for details:
  /tmp/bc/spack-stage/spack-stage-gdb-11.1-bqvgcs4nr4rbb57x24tldnlbcv3mpmqy/spack-build-out.txt
```

### Information on your system

* **Spack:** 0.16.3-4399-cdcecda9d0
* **Python:** 3.6.8
* **Platform:** linux-rocky8-zen2
* **Concretizer:** clingo

### Additional information

gdb requires GMP to build since version 11.1. (https://www.gnu.org/software/gdb/download/ANNOUNCEMENT)

@robertu94

[spack-build-out.txt](https://github.com/spack/spack/files/7254919/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/7254920/spack-build-env.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by robertu94** [comment]
@zzzoom good catch. Could you please provide a list of external packages and the contents of /etc/os-release so I can verify a fix. I have many deadlines in the next two-three weeks so I’ll have limited bandwidth to work on this until then. 

If you provide a PR, I’d be happy to review it.

**Comment by robertu94** [comment]
I found a fix that I think addresses this, but I don't have time to test all the older versions right now.
