### ISSUE TITLE
Installation issue: gdb +python

### ISSUE THREAD

**Issue by zzzoom** [LLNL/spack#26358]
### Steps to reproduce the issue

```console
$ spack install gdb@10.2 +python
[+] /usr (external python-3.6.8-42zz3vk7tj5ooiq2s33wqd4zx2njlxqj)
[+] /usr (external texinfo-6.5-uzihy7vowlztilxfy6wrzmos226rgcqn)
[+] /usr (external xz-5.2.4-aznlbqrcwv5pwolhte6xmvjwtvjrduaq)
==> Installing gdb-10.2-ejd5glajzmzhn647bg6aekb2y4zbuztj
==> No binary for gdb-10.2-ejd5glajzmzhn647bg6aekb2y4zbuztj found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/b3/b33ad58d687487a821ec8d878daab0f716be60d0936f2e3ac5cf08419ce70350.tar.gz
==> Applied patch /home/bc/spack/var/spack/repos/builtin/packages/gdb/gdb-libintl-10.patch
==> Applied patch /home/bc/spack/var/spack/repos/builtin/packages/gdb/importlib.patch
==> gdb: Executing phase: 'autoreconf'
==> gdb: Executing phase: 'configure'
==> gdb: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16' 'V=1'

1 error found in build log:
     4954    checking for libmpfr... no
     4955    configure: WARNING: MPFR is missing or unusable; some features may be unavailable.
     4956    checking whether to use python... yes
     4957    checking for python... missing
     4958    checking for python... no
     4959    checking for python... no
  >> 4960    configure: error: python is missing or unusable
     4961    make[1]: *** [Makefile:10370: configure-gdb] Error 1
     4962    make[1]: Leaving directory '/tmp/bc/spack-stage/spack-stage-gdb-10.2-ejd5glajzmzhn647bg6aekb2y4zbuztj/sp
             ack-src/spack-build'
     4963    make: *** [Makefile:854: all] Error 2

See build log for details:
  /tmp/bc/spack-stage/spack-stage-gdb-10.2-ejd5glajzmzhn647bg6aekb2y4zbuztj/spack-build-out.txt
```

### Information on your system

* **Spack:** 0.16.3-4399-cdcecda9d0
* **Python:** 3.6.8
* **Platform:** linux-rocky8-zen2
* **Concretizer:** clingo

The relevant part of packages.yaml is that we're using EL8 python as an external, which doesn't include a /usr/bin/python symlink.
```
  python:
    externals:
    - spec: python@3.6.8+bz2+ctypes+dbm+lzma+nis+pyexpat~pythoncmd+readline+sqlite3+ssl~tix~tkinter+uuid+zlib
      prefix: /usr
```

### Additional information

gdb looks for a `python` binary to execute, but it isn't present when spack selects a `python~pythoncmd` package for the dependency.

@robertu94

[spack-build-out.txt](https://github.com/spack/spack/files/7255146/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/7255149/spack-build-env.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by robertu94** [comment]
Another good catch. I’ll look into this when I get time. I can also help you prepare a PR if you have time to make one.

**Comment by robertu94** [comment]
I found a fix that I think addresses this, but I don't have time to test all the older versions right now.
