### ISSUE TITLE
Environment views don't properly create directory symlinks

### ISSUE THREAD

**Issue by sethrj** [LLNL/spack#26377]
### Steps to reproduce

I'm using macOS to install `qt@5+framework`, which installs to $Qt_ROOT/lib (for example) the QtGui framework:
```
Headers@ -> Versions/Current/Headers
QtGui@ -> Versions/Current/QtGui
Resources@ -> Versions/Current/Resources
Versions/
Versions/5/
Versions/Current@ -> 5
```

The view to Qt placed in the environment, however, incorrectly unlinks the symbolic links:
```
Headers/
QtGui@ -> $Qt_ROOT/lib/QtGui.framework/QtGui
Resources/
Versions/
Versions/5/
Versions/5/Headers/
Versions/5/QtGui@ -> $Qt_ROOT/lib/QtGui.framework/Versions/5/QtGui
Versions/5/Resources/
Versions/Current/
```
The `Headers`, `Resources`, and `Versions/Current` in the view are all empty directories.

### Information on your system

* **Spack:** 0.16.2-4234-bafd84e191
* **Python:** 3.8.8
* **Platform:** darwin-bigsur-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by sethrj** [comment]
This bit us again. @becker33 I think this showed up after the big "env views are symlinks" refactor; do you happen to know an easy fix? For now we're laboriously deleting the directories and symlinking in the frameworks directly into the view (ugh).

**Comment by haampie** [comment]
See #29443 for a fix
