### ISSUE TITLE
readthedocs PR build

### ISSUE THREAD

**Issue by shahzebsiddiqui** [LLNL/spack#26450]
it would be useful to enable readthedocs PR preview of docs see https://docs.readthedocs.io/en/stable/pull-requests.html. Once this is enabled incoming PRs will build the PR docs you can view the rendered page. Definitely useful for reviewing documentation changes live by clicking on the PR as pose to reviewing the file. 

Take for example this PR in e4s project https://github.com/E4S-Project/e4s/pull/33

You will see the CI check including the build for user docs 
<img width="936" alt="Screen Shot 2021-10-03 at 8 26 25 PM" src="https://user-images.githubusercontent.com/12942230/135778658-20a0ccb4-b697-452e-acb3-6de8fb723eec.png">
 

One can actually navigate the the PR previewed docs at https://e4s--33.org.readthedocs.build/en/33/.

**Comment by adamjstewart** [comment]
I tried this in another repository of mine and couldn't get it working. But if it does work we could replace the doc tests with this.

**Comment by alalazo** [comment]
It seems this was enabled:
![Screenshot from 2021-10-07 19-12-57](https://user-images.githubusercontent.com/4199709/136433006-5b9dfa62-2ef6-4257-bbda-c197fc2a2583.png)

 Should we remove the doc test?

**Comment by adamjstewart** [comment]
Yes, we should remove the doc tests and make the new tests required the next time we have to update things for black/other test name changes.
