### ISSUE TITLE
mesa18: all fetchers failed - server certificate verification failed

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#26536]
### Steps to reproduce the issue

Using:
* `spack@develop` (c426386f4623d4a087af384ebc2276ca203f3cb9 from `Tue Oct 5 06:38:31 2021 +0900`)

```
$> spack install mesa18@18.3.6
...
==> Installing mesa18-18.3.6-aqkvvxaccpmwzcuvio7aqpteasfr32s2
fatal: unable to access 'https://gitlab.freedesktop.org/mesa/mesa.git/': server certificate verification failed. CAfile: none CRLfile: none
==> Error: FetchError: All fetchers failed for spack-stage-mesa18-18.3.6-aqkvvxaccpmwzcuvio7aqpteasfr32s2

/spack/lib/spack/spack/package.py:1376, in do_fetch:
       1373
       1374        self.stage.create()
       1375        err_msg = None if not self.manual_download else self.download_instr
  >>   1376        start_time = time.time()
       1377        self.stage.fetch(mirror_only, err_msg=err_msg)
       1378        self._fetch_time = time.time() - start_time
       1379
```

### Information on your system

* **Spack:** 0.16.3-4683-c426386f46
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** clingo

### Additional information

@ChristianTackeGSI @chuckatkins @v-dobrev 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by ChristianTackeGSI** [comment]
Hi!

Can you check the following things / verify that I don't look at the wrong places?
* ```bash
  $ git clone 'https://gitlab.freedesktop.org/mesa/mesa.git'
  ```
  on the cmdline?

* Does https://gitlab.freedesktop.org/mesa/mesa.git work in your browser?
* Is your `ca-certificates` package up to date?
  The server seems to be using Letsencrypt. They have lately switched cross signing / etc. Some people seem to have problems with that. Can you check for yourself?
* TLS Test looks good also: https://www.ssllabs.com/ssltest/analyze.html?d=gitlab.freedesktop.org&hideResults=on

**Comment by haampie** [comment]
Is this using `curl` built by Spack somehow?

7fdb879308247c060654a95a9eedfbc628533f01

> 3. Changes the curl configuration to not guess the ca path during
>   config, but rather fall back to whatever the tls provider is
>   configured with. If we don't do this, curl will still pick up system
>   certs if it finds them.

So Spack-built curl defaults to using openssl's certs, which by defaults symlinks the system certs; the idea was there was no change for the user.

FWIW: `git` depends on `curl` depends on `openssl` by default, so if that git somehow is in the PATH and Spack starts using it internally, that could be an issue. Can you test whether `curl https://www.google.com` works for a Spack-built `curl`?

**Comment by eugeneswalker** [comment]
> Is your `ca-certificates` package up to date?

> Is this using `curl` built by Spack somehow?

Using system fetchers (non-spack installed) inside a Docker container image for `Ubuntu 20.04`. The ca-certificates package was last updated on September 1st. I just updated it and now... it works! Thank you!

**Comment by ghost** [comment]
I had this issue with Ubuntu 20.04 as well. It was resolved by reinstalling ca-certificates.
`sudo apt-get install --reinstall ca-certificates`
