### ISSUE TITLE
Patch Autotools-based libraries to use @rpath install_name

### ISSUE THREAD

**Issue by sethrj** [LLNL/spack#26552]
### Summary

Use `install_name_tool -id '@rpath/${filename}' ${prefix}/${filename}` to fix up macOS libraries installed by autotools that have `LC_ID_DYLIB` hard-coded by `libtool`. This would make autotools-installed libraries consistent with CMake-installed libraries in that they use RPATH for propagating link information rather than hard-coding it.

### Rationale

Whereas most spack-CMake-installed packages install libraries with an `install_name` as `@rpath/libname.dylib` (which shows up in `LC_ID_DYLIB` in `otool -l ${path} | grep -A3 LC_ID_DYLIB`), most autotools (libtool) packages hard-code the install prefix using `-install_name ${PREFIX}/lib/${LIBNAME}`. This propagates the hardcoded library path into downstream libraries, making them more difficult to relocate (changing rpaths is insufficient, you have to know the dependent paths and use `-change`).

Patching the installed libraries vastly simplifies the relocation of *any* downstream library, installed by spack or not, because only the `rpath` needs to change.

### Description

I would either add a configuration option or a `@after('install')` hook to the Autotools package, and adjust any non-autotools packages (such as `zstd`) to perform the fixup as needed.

### Additional information

It looks like @gartung is credited with making macOS files relocatable (`spack.relocate`) so perhaps he has some opinions and a better idea of potential pitfalls?

Spack version 0.16.3-4706-3157a97743

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by gartung** [comment]
As long as either @rpath/libname or /full/path/to/libname is used the relocation should work. Some packages used neither and need to be fixed.

**Comment by sethrj** [comment]
@gartung Thanks for those fixes and the info. In this particular case I'm *not* talking about a spack buildcache relocation, which adjusts from one hardcoded path to another hardcoded path.

What my application needs is to be able to copy all the spack-created `.dylib` files in my toolchain to an arbitrary `$INSTALL/lib` (where `$INSTALL` is actually `foo.app/Contents/Resources`) and then fix up all its dependencies by using `-add_rpath @loader_path/../lib` and `-delete_rpath <all the spack prefixes>` on the copied libraries.

I *could* get where I'm going by additionally filtering *all* of the installed binaries and libraries to parse their paths and then call `-change` for all of them, but that will be expensive for the number of dependencies I have to install, whereas the spack fix would be a once and for all solution that wouldn't affect anything else.

If we were able to use `install_name_tool -id` to fix up all the autotools packages, it would also make the `spack.relocate` tool faster since it too could skip all the `-change` commands...

**Comment by gartung** [comment]
Creating a buildcache with relative paths for macOS binaries makes use of @loader_path. 
Making autotools packages do this automatically seems like a good idea.
