### ISSUE TITLE
Installation issue: rocprofiler-dev has a runtime dependency on roctracer-dev

### ISSUE THREAD

**Issue by vchuravy** [LLNL/spack#26554]
`rocprofiler` depends at runtime on libraries installed through rocprofiler https://github.com/ROCm-Developer-Tools/rocprofiler/blob/93778bdc4fa5403fedede3afcc1155338c62a6f3/bin/rpl_run.sh#L29

Despite the assumption that the directory layout is fixed https://github.com/ROCm-Developer-Tools/rocprofiler/issues/58

Spack should probably add a runtime dependency as well.
https://github.com/spack/spack/blob/b92fd080289875382ca31e4eb7a1341508257348/var/spack/repos/builtin/packages/rocprofiler-dev/package.py#L36

(Just run into one system today were everything was broken...)

cc: @haampie @cgmb

**Comment by msimberg** [comment]
@srekolam what's the status of this? I'm seeing what I assume is the same problem. `rocprof` assumes that `libtracer_tool.so` is found in the `rocprofiler-dev` install root, but it's instead in the `roctracer-dev` install root. However, on top of that trying to add `roctracer-dev` as a dependency to `rocprofiler-dev` doesn't work because there already is an inverse dependency between the two. Is there even a short-term workaround for this?

**Comment by srekolam** [comment]
I apologize for keeping this open for long.. This is being tracked for next release. ..i will check with the internal team and will update you if this will be part of the rocm-5.2 release or not.

**Comment by sanjtrip** [comment]
Hi @srekolam, Is this part of ROCm-5.2 ?

**Comment by msimberg** [comment]
This is still an issue in 5.4.3 (and rocprofiler-dev hasn't been updated past that while the other rocm packages are up to 5.5.X and soon 5.6.X; it seems like things are changing anyway in 5.5.X: https://github.com/ROCm-Developer-Tools/rocprofiler/blob/a41faedcef57dc4607dc46a4a2127ef43131f5b1/CHANGELOG.md?plain=1#L75-L85).

In case someone else is interested in a temporary hack, I've got a small modification of the `rocprof` script in 5.4.3 with the following diff compared to the upstream one:
```diff
diff --git a/user-environment/linux-sles15-zen2/gcc-11.4.0/rocprofiler-dev-5.4.3-axl3amlex47db6k67dmvbhsiykgqpitz/bin/rocprof b/users/simbergm/tmp/rocprof
index 49cf0702..b99605a5 100755
--- a/user-environment/linux-sles15-zen2/gcc-11.4.0/rocprofiler-dev-5.4.3-axl3amlex47db6k67dmvbhsiykgqpitz/bin/rocprof
+++ b/users/simbergm/tmp/rocprof
@@ -22,8 +22,12 @@
 # THE SOFTWARE.
 ################################################################################

+if [[ -z "${SPACK_ROCPROF_HIP_VERSION}" ]]; then
+       echo "Set SPACK_ROCPROF_HIP_VERSION to the version you are using in your spack environment"
+       exit 1
+fi
 time_stamp=`date +%y%m%d_%H%M%S`
-BIN_DIR=$(dirname $(realpath ${BASH_SOURCE[0]}))
+BIN_DIR=$(spack location -i rocprofiler-dev@${SPACK_ROCPROF_HIP_VERSION})/bin
 ROOT_DIR=$(dirname $BIN_DIR)
 RUN_DIR=`pwd`
 TMP_DIR="/tmp"
@@ -31,8 +35,8 @@ DATA_DIR="rpl_data_${time_stamp}_$$"

 RPL_PATH=$ROOT_DIR/lib
 TLIB_PATH=$RPL_PATH/rocprofiler
-TTLIB_PATH=$ROOT_DIR/lib/roctracer
-ROCM_LIB_PATH=$ROOT_DIR/lib
+TTLIB_PATH=$(spack location -i roctracer-dev@${SPACK_ROCPROF_HIP_VERSION})/lib64/roctracer
+ROCM_LIB_PATH=$(spack location -i roctracer-dev@${SPACK_ROCPROF_HIP_VERSION})/lib64
 PROF_BIN_DIR=$ROOT_DIR/libexec/rocprofiler

 if [ -z "$ROCP_PYTHON_VERSION" ] ; then
@@ -208,14 +212,13 @@ if !command -v rocminfo > /dev/null 2>&1 ;  then
   error "'rocminfo' utility is not found: please add ROCM bin path to PATH env var.";
 fi

-# setting ROCM_LIB_PATH
-set_rocm_lib_path() {
+# checking ROCM_LIB_PATH
+check_rocm_lib_path() {

-  for ROCM_LIB_PATH in "$ROOT_DIR/lib" "$ROOT_DIR/lib64" ; do
-     if [ -d "$ROCM_LIB_PATH" ]; then
-        return 0
-     fi
-  done
+  # Don't reset ROCM_LIB_PATH that we compute
+  if [ -d "$ROCM_LIB_PATH" ]; then
+     return 0
+  fi

   #error
   return 255
@@ -224,7 +227,7 @@ set_rocm_lib_path() {
 # profiling run method
 OUTPUT_LIST=""
 run() {
-  if ! set_rocm_lib_path ; then
+  if ! check_rocm_lib_path ; then
      echo " Fatal could not find ROCm lib directory "
      fatal
   fi
```

Full script is here: https://gist.github.com/msimberg/97085a6bfd974ae9f96aadfa23ead6bb. YMMV etc. I keep this modified `rocprof` outside of spack. Unless the circular dependencies and other things are cleaned up in the ROCm stack I don't see a clear way to patch up the spack-installed `rocprof` to do the same.

**Comment by srekolam** [comment]
request to check with latest release 6.0.2 version and let us know if this is still the issue.
