### ISSUE TITLE
Installation issue: py-mayavi

### ISSUE THREAD

**Issue by manuelakuhn** [LLNL/spack#26561]
### Steps to reproduce the issue

Installing `py-mayavi` fails with no propper error message
```
$ spack install py-mayavi
```
gives
```
==> Installing py-mayavi-4.7.1-cgsu2qpvxiugbznpqxbig32mjrao7gyn
==> No binary for py-mayavi-4.7.1-cgsu2qpvxiugbznpqxbig32mjrao7gyn found: installing from source
==> Using cached archive: $spack/var/spack/cache/_source-cache/archive/be/be51fb6f886f304f7c593c907e6a2e88d7919f8f446cdccfcd184fa35b3db724.tar.bz2
==> No patches needed for py-mayavi
==> py-mayavi: Executing phase: 'build'
==> [2021-10-06-18:13:48.429844] '$spack/opt/spack/linux-fedora32-haswell/gcc-10.3.1/python-3.8.11-pt3pvvbz7wbtqiewmrbvrdepuib7hn3w/bin/python3.8' '-s' 'setup.py' '--no-user-cfg' 'build'
running build
----------------------------------------------------------------------
Building TVTK classes... ==> Error: ProcessError: Command exited with status -11:
    '$spack/opt/spack/linux-fedora32-haswell/gcc-10.3.1/python-3.8.11-pt3pvvbz7wbtqiewmrbvrdepuib7hn3w/bin/python3.8' '-s' 'setup.py' '--no-user-cfg' 'build'
```

@adams

### Information on your system

* **Spack:** 0.16.3-4720-199bd9f8f8
* **Python:** 3.8.10
* **Platform:** linux-fedora32-haswell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by manuelakuhn** [comment]
I have built the newer patch release 4.7.3 and this works (will open a pull request for it) while 4.7.1 still is broken.

**Comment by adamjstewart** [comment]
Closing now that #26566 has been merged.
