### ISSUE TITLE
py-graphviz: Version 1.7 not available on PyPi

### ISSUE THREAD

**Issue by haralmha** [LLNL/spack#26571]
Steps to reproduce:
`spack checksum py-graphviz`
Version 1.7 does not show up. The tarball is nowhere to be found on the PyPi page: https://pypi.org/project/pygraphviz/1.7/#files

**Comment by haralmha** [comment]
I have also tried to add `version('1.7', sha256='a7bec6609f37cf1e64898c59f075afd659106cf9356c5f387cec\
aa2e0cdb2304')` (where the sha256 is from the zip file on the PyPi page) to the `package.py` file for `py-graphviz`. When I try to `spack checksum py-raphviz`, I get this:
```
==> How many would you like to checksum? (default is 1, q to abort) 1
==> Something failed on https://files.pythonhosted.org/packages/source/g/graphviz/graphviz-1.7.zip, skipping.  (All fetchers failed for spack-stage-eofchv0q)
==> Error: Could not fetch any versions for py-graphviz
```

**Comment by adamjstewart** [comment]
The issue is that [graphviz](https://pypi.org/project/graphviz/) and [pygraphviz](https://pypi.org/project/pygraphviz/) are two different projects. It sounds like you want to add a new package for `py-pygraphviz` instead of using `py-graphviz`.
