### ISSUE TITLE
GCC rpath installation in specs has unintended consequences

### ISSUE THREAD

**Issue by sethrj** [LLNL/spack#26582]
### Steps to reproduce

Spack's GCC install hardwires (through the `specs` file) the linker to adding an rpath entry to GCC's library dir, so that compiled binaries get the right `libstdc++` etc. This is mostly necessary because Spack doesn't currently treat spack-compiled compilers as part of the spec (you can't install `zlib %gcc@8.3 % gcc@4.8` where 4.8 is the system compiler and 8.3 is built by spack): otherwise, you could have GCC add a runtime environment flag to append rpaths to the LDFLAGS.

The problem I'm having is that CMake isn't able to detect this sneaky compiler-added rpath entry when attempting to set the install rpath, so when I ask for the install rpaths to be set to `$ORIGIN/../lib` it actually ends up as `/spack/gcc/lib:$ORIGIN/../lib`. So what I'd *like* to do is add the ability to build *without* forcibly adding this rpath.

I think what I will do is have the GCC package *move* the default `specs` to `specs.norpath` and then write a new `specs` file:
```
%include <specs.norpath>

%rename link orig_link

*link:
-rpath ${GCC}/lib:${GCC}/lib64 $(orig_link)
```

See [kitware/cmake/cmake#22730](https://gitlab.kitware.com/cmake/cmake/-/issues/22730)

### Error message

```
$ patchelf --print-rpath bin/foo
/projects/spack/opt/spack/gcc-4.4.7/gcc/punpbku/lib:/projects/spack/opt/spack/gcc-4.4.7/gcc/punpbku/lib64:$ORIGIN/../lib64
```

### Information on your system

* **Spack:** 0.16.2-3016-1fd1f1c93f
* **Python:** 3.8.10
* **Platform:** linux-rhel6-broadwell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by sethrj** [comment]
It turns out that `%include` doesn't work from the main `specs` file: had to [read the GCC source](https://github.com/gcc-mirror/gcc/blob/0e90799071ee78f712f3b58fca7000bc0a258ade/gcc/gcc.c#L2377) to figure this out.

Other spec file modifications for rpaths:
- [GCC configure-time adjustment](https://www.py4u.net/discuss/105305)
- [Homebrew GCC](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/gcc.rb) 

Updated working solution:
- Instead of patching `*link` directly, let's patch into something easier and more appropriate (`*link_libgcc`) and introduce our own variable `*link_libgcc_rpath` that can be trivially overridden
- Append ` %(link_libgcc_rpath)` to the `link_libgcc` section and add the typical spack rpath to `*link_libgcc_rpath`. This reproduces the current spack behavior.
- To override, define a spec file `norpath.spec` with the contents `*link_libgcc_rpath:` followed by two blank lines; and pass `--specs=norpath.spec` to GCC. This prevents the GCC rpaths from propagating through the compiler options!

I will submit a patch to do Spack's GCC to do this.

**Comment by sethrj** [comment]
*Another* unintented consequence: spack GCC-driven linker ignored `LD_RUN_PATH`, see https://github.com/spack/spack/pull/26590#issuecomment-938549388 .

**Comment by sethrj** [comment]
**Another** surprise: the rpath entries in the spec files are not correct for macOS! They must be two separate rpath commands rather than a colon-separated one.

**Comment by haampie** [comment]
> Another surprise: the rpath entries in the spec files are not correct for macOS! They must be two separate rpath commands rather than a colon-separated one.

What you did just worked by accident on Linux 🙃 on both Linux and macOS a single rpath entry is added and is copied verbatim; linkers do not validate whether it contains `:` or not. On Linux all rpaths are concatenated separated by `:` by the linker, and at runtime they're split on `:` by the dynamic linker. On macOS rpaths end up in separate load commands (so, macOS probably supports `:` characters inside directory names).

Notice that on Linux you can also have directories that contain a `:` character, but you wouldn't be able to use them in rpaths. So `-rpath /hello:world` really means "add an rpath for the directory `/hello:world`", not add two rpaths for `/hello` and `world`. But yeah, it would've been nice if the linker errored given that it will have that interpretation at runtime...
