### ISSUE TITLE
luaposix (lmod) fetch error

### ISSUE THREAD

**Issue by trmwzm** [LLNL/spack#2660]
Link and md5 correct in package.py, .... but debug shows incorrect path during install:

```python
homepage = "https://github.com/luaposix/luaposix/"
url      = "https://github.com/luaposix/luaposix/archive/release-v33.4.0.tar.gz"

version('33.4.0', 'b36ff049095f28752caeb0b46144516c')
```
```
==> Fetching from https://github.com/luaposix/luaposix/archive/33.4.0.tar.gz failed.
==> Failed to fetch file from URL: https://github.com/luaposix/luaposix/archive/33.4.0.tar.gz
    URL https://github.com/luaposix/luaposix/archive/33.4.0.tar.gz was not found!
```

**Comment by tgamblin** [comment]
The [package](https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/lua-luaposix/package.py) could probably use a proper `url_for_version` method.

I think we need to figure out how to offload some of the URL special cases from Spack's `url.py` to package files.  @adamjstewart might like that.

**Comment by adamjstewart** [comment]
Getting rid of special cases is good, but hiding complexity inside of the Spack core libraries is probably better. My goal is that someone who has never even heard of Python can easily use and contribute packages to Spack.

**Comment by trmwzm** [comment]
Would it be possible to use the link containing the git SHA1 of the release ?
