### ISSUE TITLE
`when` context manager fails when additional dependency version constraint is used

### ISSUE THREAD

**Issue by manuelakuhn** [LLNL/spack#26656]
### Steps to reproduce

Running the `when` context manager with a constraint on the dependency version fails when concretizing.

I used the `py-datalad` package to demonstrate the behavior:
- modify spec:
  ```diff
  --- a/var/spack/repos/builtin/packages/py-datalad/package.py
  +++ b/var/spack/repos/builtin/packages/py-datalad/package.py
  @@ -38,7 +38,8 @@ class PyDatalad(PythonPackage):
      # core
      depends_on('py-appdirs', type=('build', 'run'))
      depends_on('py-chardet@3.0.4:', type=('build', 'run'))
  -    depends_on('py-distro', type=('build', 'run'), when='^python@3.8:')
  +    with when('@0.14:'):
  +        depends_on('py-distro', type=('build', 'run'), when='^python@3.8:')
      depends_on('py-importlib-metadata', type=('build', 'run'), when='^python@:3.7')
      depends_on('py-iso8601', type=('build', 'run'))
      depends_on('py-humanize', type=('build', 'run'))
  ```
- run:
  ```
  $ spack spec py-datalad
  ```
This fails (error message see below) whereas these combination all work:
- variant + package version
  ```python
      with when('+full'):
          depends_on('py-distro', type=('build', 'run'), when='@0.14:')
  ```
- package version + variant
  ```python
      with when('@0.14:'):
          depends_on('py-distro', type=('build', 'run'), when='+full')
  ```
- dependency version + package version
  ```python
      with when('^python@3.8:'):
          depends_on('py-distro', type=('build', 'run'), when='@0.14:')
  ```

### Error message

```console
Input spec
--------------------------------
py-datalad

Concretized
--------------------------------
==> Error: A spec cannot contain multiple version signifiers. Use a version list instead.
```

### Information on your system

* **Spack:** 0.16.3-4785-31342a89ae
* **Python:** 3.8.10
* **Platform:** linux-fedora32-haswell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
The issue here is that in the current implementation `when` constraints coming from context managers are appended to the spec, rather than prepended:

https://github.com/spack/spack/blob/4d58661d08879bc95d12ea9888fed99ec5f4fa18/lib/spack/spack/directives.py#L251-L255

so the directive in the description is equivalent to:

```python
depends_on('py-distro', type=('build', 'run'), when='^python@3.8: @0.14:')
```
which leads to the error that has been reported.

Both prepending and appending make sense in different contexts. What we can do is to add an optional keyword argument:
```python
with when('@0.14:', prepend=True):
    depends_on('py-distro', type=('build', 'run'), when='^python@3.8:')
```
that translates to:
```python
depends_on('py-distro', type=('build', 'run'), when=' @0.14: ^python@3.8:')
```

**Comment by alalazo** [comment]
@manuelakuhn Do you have an example of a package for which this use make sense? I can submit a fix with unit tests but it would be also good to have an example in the same PR.

**Comment by manuelakuhn** [comment]
Thanks for the explanation why this happens @alalazo 
Having an optional keyword argument actually would be doable but in the end I am not the biggest fan of this approach. The biggest advantage of the `when` context manager for me is its simplicity and readability. That would decrease and also make its usage not consistent anymore. But as I see you are already discussing about different solutions together with @haampie which looks promising :-)

Regarding an example:
I encountered that problem while trying to build a new package for [nibetaseries](https://github.com/HBClab/NiBetaSeries). The `py-nistats` dependency was integrated into later versions of the `py-nilearn` dependency, so I had
```
    with when('@master'):
        ...
        depends_on('py-nistats@0.0.1b2', when='^py-nilearn@:0.6', type=('build', 'run'))
        depends_on('py-nilearn', type=('build', 'run'))
       ...
```
Due to other problems with the package I could not use this approach (yet) and so do not have a running example for you.

**Comment by haampie** [comment]
This other example should just work after going from string processing to spec intersection / merging / combining constraints.

**Comment by manuelakuhn** [comment]
Thanks, that's also how I understood your discussions in the PR.
