### ISSUE TITLE
Refactor code shared between CMakePackage and general builds using CMake.

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#2665]
@alalazo I noticed that `get_std_cmake_args()` in `build_environment.py` seems to repeat code from `_std_args()` in `build_systems/cmake.py`.  Can one of them be deleted?

**Comment by tgamblin** [comment]
Any `Package` subclass can still use cmake.  Maybe there's a decent way to refactor but I don't think we should get rid of these variables for general builds.

**Comment by citibeth** [comment]
Oh yes, of course.  Let's just say this should be refactored.
