### ISSUE TITLE
Wrong $PATH extension in Tutorial

### ISSUE THREAD

**Issue by juan42** [LLNL/spack#2674]
Using the link from the main repo readme you get redirected to http://spack.readthedocs.io/en/latest/tutorial_sc16.html.

It recommends
```
becker33:spack$ export PATH=~/spack/bin/spack:$PATH
```
which is wrong. You need to set
```
$ export PATH=~/spack/bin:$PATH
```
I'm sorry, i haven't found a branch to edit this directly. But the information is misleading

**Comment by adamjstewart** [comment]
You can edit this directly by submitting a PR to the develop branch. I can fix this.

**Comment by tgamblin** [comment]
@juan42: thanks!
