### ISSUE TITLE
Implement Smoke Test (or stand-alone) for a Header-only Library

### ISSUE THREAD

**Issue by KIwabuchi** [LLNL/spack#26770]
Hello,

Could you tell me how to set up a Spack smoke test (or stand-alone) for a header-only library?

I'm trying to implement a smoke test in the [Metall package](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/metall/package.py) (founded by the Exascale Computing Project).

I read [this](https://spack.readthedocs.io/en/latest/packaging_guide.html#stand-alone-or-smoke-tests) section on Spack's Read the Docs, but I have some questions.

**Executables:**
As Metall is a C++ header-only library, we don't generate any executables during the installation unless users turn on the build-test option (Metall already supports a Spack build-time test).

I found a sentence that says `run_test` method builds executable. But, I don't quite understand how to use it to build an executable:
https://spack.readthedocs.io/en/latest/packaging_guide.html#reading-expected-output-from-a-file

**Compiler:**
Is it possible to install a proper version of a compiler before running a smoke test?

Thank you,
Keita

**Comment by tldahlgren** [comment]
Hello.

You should be able to implement the tests (that are to be performed weeks to months after the installation) however seems appropriate to demonstrate that a user can successfully build against your library and run their code.

Use of `self.run_test()` is not required within `self.test()`.  It is intended to support multiple test parts so that failures of some tests do not prevent running the rest of the test (parts).  It also provides mechanisms for checking the output and or status of running the command against expections, supporting a rudimentary expected failure capability.

Compilers used to build and install the package are made available to stand-alone tests when the `test_requires_compiler` property is `True`.  (See  https://spack.readthedocs.io/en/latest/packaging_guide.html#enabling-test-compilation).

Hopefully this information helps.  Let me know if you have more questions.

**Comment by KIwabuchi** [comment]
@tldahlgren Thank you for reply.

>  Use of self.run_test() is not required within self.test(). 

Could you tell me how to build and run a test program without using  `self.run_test()`?


> Compilers used to build and install the package are made available to stand-alone tests when the test_requires_compiler property is True.

Yes, I understood the feature. However, my issue is that our package does not use a compiler for build and install because it is a header-only library.

Is it possible to specify a compiler as a dependency for smoke tests?
For example, our package file contains the following code for build test:
```Python
depends_on('googletest %gcc@8.1.0:', type=('test'))
````
Is it possible to do the same thing for smoke tests?

Thank you,

**Comment by tldahlgren** [comment]
> @tldahlgren Thank you for reply.
> 
> > Use of self.run_test() is not required within self.test().
> 
> Could you tell me how to build and run a test program without using `self.run_test()`?

Sure.  Ideally you'd have a test program in your repository so it can evolve with your headers but if that's not the case, you have two choices: 1) add one or more custom (test) files or 2) in-line writing a test file.  In both cases, you can compile and run the files.

For 1), there's some documentation at https://spack.readthedocs.io/en/latest/packaging_guide.html#adding-custom-files though the example there is for test data/output.  There are more examples with `Y` in the `Compiles Source` column at https://github.com/spack/spack/wiki/Spack-Stand-Alone-Smoke-Testing-Support (so `c`, `cxx`, `fortran`, `libsigsegv`, and more).

You can check out the `_check_install` method for `hdf5` at https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/hdf5/package.py) for an example of 2) that includes compiling and running the checks outside `self.run_test`.


> 
> > Compilers used to build and install the package are made available to stand-alone tests when the test_requires_compiler property is True.
> 
> Yes, I understood the feature. However, my issue is that our package does not use a compiler for build and install because it is a header-only library.
> 
> Is it possible to specify a compiler as a dependency for smoke tests? For example, our package file contains the following code for build test:
> 
> ```python
> depends_on('googletest %gcc@8.1.0:', type=('test'))
> ```
> 
> Is it possible to do the same thing for smoke tests?

Yes, the intention is that `test` dependencies would also be made available for use by stand-alone tests.

Unfortunately, we're having issues with our test dependency model so have had to use work-arounds that are not addressed by https://github.com/spack/spack/pull/25165.

One work-around (that is not popular) is to temporarily -- with a comment explaining the need for the fix -- to specify the test dependency also as a `run` dependency.  An alternative is to save off the path(s) to the test dependency during the build process and read the path(s) for use during stand-alone testing.  An example of this -- for `cmake` only (see `cmake_bin`) -- can be seen at https://github.com/spack/spack/pull/24424/files.

**Comment by KIwabuchi** [comment]
Thank you for your reply and my apologies for the late reply.

I looked into the work-around. But, unfortunately, it seems too complicated for me.
I'll close this issue and wait for #25165 :)

Again, thank you so much for your help!
