### ISSUE TITLE
Installation issue: intel-oneapi-compilers

### ISSUE THREAD

**Issue by ikitayama** [LLNL/spack#26789]
### Steps to reproduce the issue

```
$ spack install intel-oneapi-compilers
[+] /p/scratch/cjzam11/kitayama1/projects/spack/opt/spack/linux-centos8-zen2/gcc-10.3.0/patchelf-0.13-owslhmxve36hwxcgweu5w2ygxxrbhqn4
==> Installing intel-oneapi-compilers-2021.4.0-e4o6as3xc55kf55q7gbckxxkczfiz4a6
==> No binary for intel-oneapi-compilers-2021.4.0-e4o6as3xc55kf55q7gbckxxkczfiz4a6 found: installing from source
==> Fetching https://registrationcenter-download.intel.com/akdlm/irc_nas/18209/l_dpcpp-cpp-compiler_p_2021.4.0.3201_offline.sh
==> Fetching https://registrationcenter-download.intel.com/akdlm/irc_nas/18210/l_fortran-compiler_p_2021.4.0.3224_offline.sh
==> Moving resource stage
	source : /tmp/kitayama1/spack-stage/resource-fortran-installer-e4o6as3xc55kf55q7gbckxxkczfiz4a6/spack-src/
	destination : /tmp/kitayama1/spack-stage/spack-stage-intel-oneapi-compilers-2021.4.0-e4o6as3xc55kf55q7gbckxxkczfiz4a6/spack-src/fortran-installer
==> No patches needed for intel-oneapi-compilers
==> intel-oneapi-compilers: Executing phase: 'install'
/p/software/jurecadc/stages/2020/software/Python/3.8.5-GCCcore-10.3.0/bin/python3: error while loading shared libraries: libpython3.8.so.1.0: cannot open shared object file: No such file or directory
==> Error: ProcessError: Command exited with status 127:
    '/bin/bash' '-c' 'source /dev/null &> /dev/null && /p/software/jurecadc/stages/2020/software/Python/3.8.5-GCCcore-10.3.0/bin/python3 -E -c "import os, json; print(json.dumps(dict(os.environ)))"'
See build log for details:
  /tmp/kitayama1/spack-stage/spack-stage-intel-oneapi-compilers-2021.4.0-e4o6as3xc55kf55q7gbckxxkczfiz4a6/spack-build-out.txt
```

### Information on your system

$ spack debug report
* **Spack:** 0.16.3-4903-03f84fb440
* **Python:** 3.8.5
* **Platform:** linux-centos8-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by ikitayama** [comment]
@rscohn2 , I'd appreciate you look at this as I've been seeing this on JURECA at JSC for a long time.

**Comment by rscohn2** [comment]
This doesn't look like a problem the intel-oneapi-compilers package, but instead of interaction with the JURECA python and spack. I see you reported the same problem with another package: https://github.com/neuronsimulator/nrn/issues/1398#issuecomment-903047268 I only maintain the oneapi packages and am not familiar with other spack internals. The spack slack channel would be a better way to find someone who can help you resolve the problem.

**Comment by ikitayama** [comment]
Okay Robert thanks.
