### ISSUE TITLE
gdal@3.3.2+zstd not working as expected

### ISSUE THREAD

**Issue by steo85it** [LLNL/spack#26798]
When installing `gdal` with `zstd` compression support, build and installation look fine, but `gdal_translate -co COMPRESS=ZSTD` gives
```
Warning 6: 'ZSTD' is an unexpected value for COMPRESS creation option of type string-select.
ERROR 1: Cannot create TIFF file due to missing codec for ZSTD.
```
I attach my `build-env` and `build-out`
[spack-build-env.txt](https://github.com/spack/spack/files/7366926/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7366927/spack-build-out.txt)
The shown config messages look fine:
```
checking for ZSTD_decompressStream in -lzstd... yes
...
ZSTD support:              yes
```
the dependency is installed, but then the library doesn't seem to be linked correctly (at least this is my first guess).

``` console
spack --version
0.16.3-4766-449a583
```
and I got the same issue testing on 2 different CentOS systems.

Any help from @adamjstewart or others would be greatly appreciated! Thanks!

**Comment by adamjstewart** [comment]
Thanks for the bug report, I was able to reproduce this on macOS too. Based on the [GeoTIFF driver docs](https://gdal.org/drivers/raster/gtiff.html#creation-options):

> ZSTD is available since GDAL 2.3 when using internal libtiff and if GDAL built against libzstd >=1.0, or if built against external libtiff with zstd support.

It looks like the problem is that we are using an external libtiff that isn't compiled with zstd support. I added a zstd variant to the libtiff package. Testing this now and will submit a PR to fix this when I'm done.

**Comment by steo85it** [comment]
That sounds very promising, thanks for looking into this!

I should probably open a separate "issue" about this, but is it possible that something similar is happening when trying to add a `--with-lerc=...` compiler option (to get `lerc` compression support, see [https://github.com/OSGeo/gdal/blob/master/gdal/configure.ac](https://github.com/OSGeo/gdal/blob/master/gdal/configure.ac), [https://github.com/Esri/lerc](https://github.com/Esri/lerc) )? Just in case you are familiar with compiling `gdal` with this option.

**Comment by adamjstewart** [comment]
Correct:

> LERC and LERC_DEFLATE are available only when using internal libtiff for GDAL < 3.3.0. Since GDAL 3.3.0, LERC compression is also available when building GDAL against external libtiff >= 4.3.0, built itself against https://github.com/esri/lerc

I can look into adding a LERC package to Spack.

**Comment by steo85it** [comment]
If possible, that would be amazing, thank you! 
In the meantime, I should compile `libtiff` with both `zstd` and `lerc` support (with the latter being compiled separately, while unavailable in spack)... interesting, thanks!

**Comment by adamjstewart** [comment]
Correct. This shouldn't take me more than an hour.

**Comment by steo85it** [comment]
I can definitely wait, then! Thanks a lot for your help!

**Comment by steo85it** [comment]
The PR looks great, I tested and it works as planned! Thanks!
Just one "doubt": wouldn't the "gdal+zstd" option be meant for forcing a libtiff+zstd dependency? Else, there is no way on the gdal installation level to "activate" support for those compression libraries (and maybe that's fine in spack philosophy, I'm just wondering).
Thanks a lot for your help and effort!

**Comment by adamjstewart** [comment]
@steo85it we could propagate variants like this, but then we would need to add 11 new variants to GDAL to control libtiff build options. Then there are the dozens of other drivers that involve external dependencies. I think it's much simpler to have users say:
```console
$ spack install gdal ^libtiff+lerc+zstd
```
then to add a ton of new variants to the GDAL package and extra `depends_on` lines to propagate these.

**Comment by steo85it** [comment]
Agreed, that would quickly become a mess (plus I got from the PR discussion what the original idea of that option was)!
