### ISSUE TITLE
qgis@3.16.5 gui errors and missing gdal/raster functions

### ISSUE THREAD

**Issue by steo85it** [LLNL/spack#26803]
See last posts of #26033 for more infos (copying here as separate issue).

As from subject, the following errors occur at opening and only 3 operations are then available in the "raster" menu. 
[qgis_gui_error.txt](https://github.com/spack/spack/files/7338322/gis_gui_error.txt)

@Sinan81 commented that this could be related to: 
> I think the error has to do with some recent changes to qscintilla package breaking some things and hence QGIS turning of qscintilla support. I'll be looking into this in the following days.

**Comment by Sinan81** [comment]
As a point of reference, no gui errors in qgis@3.10.10 built with spack@0.16.3. The raster menu looks like the attached image.
![raster_menu](https://user-images.githubusercontent.com/2924561/138622157-5ffc6e96-2fbc-4aa5-848c-e9704bcc7026.png)

**Comment by Sinan81** [comment]
I think the errors are due to using latest versions of Python. I did two things which seemed to fix the issue.
1. compiled with python@3.8.6
2. fix cmake issue in regards to QSci Sip dir:
```diff --git a/var/spack/repos/builtin/packages/qgis/package.py b/var/spack/repos/builtin/packages/qgis/package.py
index a0ef76b..a1f2717 100644
--- a/var/spack/repos/builtin/packages/qgis/package.py
+++ b/var/spack/repos/builtin/packages/qgis/package.py
@@ -151,6 +151,8 @@ def cmake_args(self):
                     self.spec['qscintilla'].prefix.include,
                     '-DQSCINTILLA_LIBRARY=' + self.spec['qscintilla'].prefix +
                     '/lib/libqscintilla2_qt5.so',
+                    '-DQSCI_SIP_DIR=' +
+                    self.spec['qscintilla'].prefix.share.sip.PyQt5,
                     '-DLIBZIP_INCLUDE_DIR=' +
                     self.spec['libzip'].prefix.include,
                     '-DLIBZIP_CONF_INCLUDE_DIR=' +
```
Soon, I'll be submitting a PR (or you could go for it if you feel like it!)

**Comment by steo85it** [comment]
Tested and it works for me!! Thanks a lot @Sinan81 ! (I let you close when the PR is submitted and accepted - would it also need a conflict with newer python versions?)

**Comment by Sinan81** [comment]
Great! Yes I'll add a conflict and more. I'm trying to figure out which python version between 3.8.6 and 3.8.12 breaks the build.

**Comment by Sinan81** [comment]
turns out I was wrong. the runtime error was due to Qscintilla issue only.
