### ISSUE TITLE
Support for banning writing to ~/.spack

### ISSUE THREAD

**Issue by mathstuf** [LLNL/spack#26833]
### Summary

Maybe this is already possible, but it seems that `-C` scopes are always read-only (`ImmutableConfigScope`), so I haven't found a way to provide a custom writeable scope.

### Rationale

On CI machines that are not containerized (e.g., macOS, Windows), ensuring the CI jobs stay in a specific directory is key to keeping machines "clean". I'd like to tell Spack "never write to `~/.spack`" and have it write its configurations elsewhere. Rewriting `HOME` is a sledgehammer that may have other unintended side effects (e.g., other tools not finding their configurations which are treated as read-only).

### Description

Some way to add in a writeable scope at a higher precedence level than the user store. Maybe `--config-scope-write` or something?

### Additional information

```console
$ bin/spack --version
0.16.3-4938-e7c7f44bb6
```

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
See #26735

**Comment by mathstuf** [comment]
Ha, thanks. I haven't gone through my Spack emails in a while, so I didn't see that I'm even mentioned there.

**Comment by haampie** [comment]
Reopening cause the PR is pending

**Comment by bernhardkaindl** [comment]
Tested with rev `b8bc0` of today (~/.spack-removal PR level: #27022) on Ubuntu 18.04:
```py
export SPACK_DISABLE_LOCAL_CONFIG=true
mv ~/.spack ~/.spack.old
bin/spack install m4
==> Bootstrapping clingo from pre-built binaries
==> Installing libsigsegv-2.13-rav76e2xjnkhzb5i2bzgqnnipwv3phr6
==> No binary for libsigsegv-2.13-rav76e2xjnkhzb5i2bzgqnnipwv3phr6 found: installing from source
...
==> Installing m4-1.4.19-2fab4o7m3d5yge76hahvkgmrq5aoh4rs
==> No binary for m4-1.4.19-2fab4o7m3d5yge76hahvkgmrq5aoh4rs found: installing from source
...
==> m4: Successfully installed m4-1.4.19-2fab4o7m3d5yge76hahvkgmrq5aoh4rs
  Fetch: 0.01s.  Build: 26.67s.  Total: 26.68s.
```
Result (trimmed with -maxdepth 3, in total 29 MB where created in `~/.spack`):
```py
cd;find .spack -maxdepth 3
.spack
.spack/reports
.spack/reports/junit
.spack/bootstrap
.spack/bootstrap/store
.spack/bootstrap/store/linux-ubuntu18.04-skylake_avx512
.spack/bootstrap/store/linux-rhel5-x86_64
.spack/bootstrap/store/bin
.spack/bootstrap/store/.tmp
.spack/bootstrap/store/.spack-db
.spack/bootstrap/config
.spack/bootstrap/config/linux
.spack/cache
.spack/cache/providers
.spack/cache/providers/.builtin-index.json.lock
.spack/cache/providers/builtin-index.json
.spack/cache/indices
.spack/cache/indices/.contents.json.lock
.spack/cache/indices/.18933a7089_5d465a2418.json.lock
.spack/cache/indices/contents.json
.spack/cache/indices/18933a7089_5d465a2418.json
.spack/cache/tags
.spack/cache/tags/.builtin-index.json.lock
.spack/cache/tags/builtin-index.json
.spack/cache/patches
.spack/cache/patches/.builtin-index.json.lock
.spack/cache/patches/builtin-index.json
```
@haampie @tgamblin  It can't find an option to move bootstrap to $spack and cache and report look like open issues to be redirected to fix this issue.

**Comment by haampie** [comment]
```SPACK_USER_CACHE_PATH=...```

**Comment by tgamblin** [comment]
This is documented here: https://spack.readthedocs.io/en/latest/configuration.html#overriding-local-configuration

See #26735 and #27022
