### ISSUE TITLE
spack install not setting exit code for bad spec when using the fish shell

### ISSUE THREAD

**Issue by carns** [LLNL/spack#26830]
### Steps to reproduce

```console
carns@carns-x1-7g ~/tmp> spack env create reproducer
==> Updating view at /home/carns/working/src/spack/var/spack/environments/reproducer/.spack-env/view
==> Created environment 'reproducer' in /home/carns/working/src/spack/var/spack/environments/reproducer
==> You can activate this environment with:
==>   spack env activate reproducer
carns@carns-x1-7g ~/tmp> spack env activate reproducer
carns@carns-x1-7g ~/tmp> spack add zlib+oopsbadvariant
==> Adding zlib+oopsbadvariant to environment reproducer
carns@carns-x1-7g ~/tmp> spack install
==> Error: trying to set variant "oopsbadvariant" in package "zlib", but the package has no such variant [happened during concretization of zlib+oopsbadvariant]
carns@carns-x1-7g ~/tmp> echo $status
0
```
In the above example I have deliberately added a spec for the `zlib` package with a variant that does not exist.  When I then run `spack install` it reports an error in stdout or stderr, but it does not set an exit code (note that this happens to be in the fish shell, so I'm using `$status` rather than `$?`).

This is problematic in scripted or CI environments because it is tricky to tell if the installation succeeded or not.

The problem is similar to https://github.com/spack/spack/issues/20510, but I'm guessing this must be a different code path.

### Error message

The error message looks fine to me; the problem is the exit status of the command.

### Information on your system

```console
carns@carns-x1-7g ~/tmp> spack debug report
* **Spack:** 0.16.3-4911-c48b733773
* **Python:** 3.9.5
* **Platform:** linux-ubuntu21.04-skylake
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
```
 ~ $ spack env activate --temp
 ~ $ spack add zlib+oops
==> Adding zlib+oops to environment /tmp/spack-1o6405qt
==> Updating view at /tmp/spack-1o6405qt/.spack-env/view
 ~ $ spack install
==> Error: trying to set variant "oops" in package "zlib", but the package has no such variant [happened during concretization of zlib+oops]
 ~ $ echo $?
1
```

:thinking:

**Comment by carns** [comment]
Hunh.  Possibly something specific to the `fish` shell then?

**Comment by carns** [comment]
I get a 1 return code when using `bash`.

**Comment by haampie** [comment]
Right, maybe the fish shell wrapper is broken

**Comment by carns** [comment]
Thank you @haampie !  I confirmed that #27028 fixed the problem.
