### ISSUE TITLE
Installation issue: py-zipp with py-setuptools-scm@6.3.2

### ISSUE THREAD

**Issue by iarspider** [LLNL/spack#26872]
### Steps to reproduce the issue

```console
$ spack install py-zipp ^py-setuptools-scm@6.3.2
(...)
Error: ProcessError: Command exited with status 1:
(...)
==> Error: py-zipp-3.6.0-u26np7v3tncfi32jyu4pbby6xbkqxoio: Package was not installed
==> Error: Installation request failed.  Refer to reported errors for failing package(s).
$ tail .../spack-build-out.txt
pkg_resources.DistributionNotFound: The 'packaging>=20.0' distribution was not found and is required by the application
```

### Information on your system

* **Spack:** 0.16.3-4967-3720d06e26
* **Python:** 3.10.0
* **Platform:** linux-debian11-skylake_avx512
* **Concretizer:** clingo

### Additional information

@adamjstewart 

Logs: https://gist.github.com/8ea20ef00793767a46e48ed6d4b320cf

Adding an explicit build dependency on `py-packaging` to `py-zipp` allows the installation to complete. 

py-zipp is not the only package with this problem, I think that any package that depends on `py-setuptools-scm` will fail with the newest version.

So, I propose to add `py-packaging` as a run-time dependency to `py-setuptools-scm` with condition `@6.3.1:`

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Hmm, I'm having trouble reproducing this issue locally. It also isn't clear why this dep would be needed for all packages that depend on setuptools-scm. I don't see it mentioned anywhere in `setup_requires` or `install_requires`.

**Comment by iarspider** [comment]
@adamjstewart try starting from `python:3` docker image. I have also reproduced the error on Ubuntu 20.04 (physical) machine and on SLC7 one.

**Comment by iarspider** [comment]
As to why is it needed - no idea. `packaging` is not listed as a requirement for zipp (or anyio, or matplotlib - these are the packages that need this additional dependency).

**Comment by adamjstewart** [comment]
@alalazo this might be related to the CI failures we were seeing.

**Comment by iarspider** [comment]
> 
> 
> As to why is it needed - no idea. `packaging` is not listed as a requirement for zipp (or anyio, or matplotlib - these are the packages that need this additional dependency).

Correction: not matplotlib, but python-dateutil

**Comment by iarspider** [comment]
> 
> 
> Hmm, I'm having trouble reproducing this issue locally. It also isn't clear why this dep would be needed for all packages that depend on setuptools-scm. I don't see it mentioned anywhere in `setup_requires` or `install_requires`.

@adamjstewart It is mentioned [here](https://github.com/pypa/setuptools_scm/blob/v6.3.1/pyproject.toml#L6). The `build-system` table's `requires` key is described in [PEP-518])(https://www.python.org/dev/peps/pep-0518/#build-system-table) as follows:
>  ... must have a value of a list of strings representing PEP 508 dependencies required to execute the build system (currently that means what dependencies are required to execute a setup.py file)

In my opinion, this matches spack's definition of run-time dependency.

**Comment by adamjstewart** [comment]
Isn't that the definition of a build-time dep? The `setup.py` is only executed when we build the package, it doesn't get installed so it isn't used at run-time.

**Comment by iarspider** [comment]
> 
> 
> Isn't that the definition of a build-time dep? The `setup.py` is only executed when we build the package, it doesn't get installed so it isn't used at run-time.

I think the mentioned `setup.py` is not setuptools-scm's one, but (e.g.) zipp' - "required ... to execute the build system", not to build the build system.

**Comment by adamjstewart** [comment]
The docs say to add `requires = ['setuptools', 'wheel']` for most packages. So this is to execute the build system of the package, not dependency packages.

**Comment by iarspider** [comment]
Just did one more test. Using a clean environment, ran `pip install -vvv --no-binary=:all: zipp==3.6.0`, you can find full log here: [gist](https://gist.github.com/iarspider/21b36f565173e2ec94dfcf3001d21150). If you run `grep packaging` on that output, you will see that pip downloads and installs `packaging`, but it is not listed in `pip install`, meaning that it is only installed temporary.

**Comment by iarspider** [comment]
> 
> 
> The docs say to add `requires = ['setuptools', 'wheel']` for most packages. So this is to execute the build system of the package, not dependency packages.

`setuptools-scm` is listed in `requires` key for zipp: [link](https://github.com/jaraco/zipp/blob/v3.6.0/pyproject.toml#L2)

**Comment by adamjstewart** [comment]
Yep, so `py-setuptools-scm` should have a build dep on `py-packaging`, and `py-zipp` should have a build dep on `py-setuptools-scm`. If any other deps are needed, then I think we should report a bug to those developers because the dependency isn't properly listed under `install_requires`.

**Comment by iarspider** [comment]
https://github.com/pypa/setuptools_scm/blob/v6.3.0/setup.cfg#L30 Oops...
