### ISSUE TITLE
`spack buildcache create` needs `file` installed

### ISSUE THREAD

**Issue by lnussbaum** [LLNL/spack#26884]
### Steps to reproduce

Without the `file` package installed, I get:
```
luser@grappe-15:~$ spack buildcache create -d . tar
==> Buildcache files will be output to file:///home/luser/build_cache
==> Error: 'NoneType' object has no attribute 'add_default_arg'
```

Installed it fixes it.
That's on the develop branch.

### Information on your system

```
$ spack debug report
* **Spack:** 0.16.3-4967-3720d06e26
* **Python:** 3.9.2
* **Platform:** linux-debian11-cascadelake
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
This is documented here: https://spack.readthedocs.io/en/latest/getting_started.html

We probably need a better error message or diagnostics.
