### ISSUE TITLE
Cannot create spack environment: [Errno 39] Directory not empty: '.spack-env'

### ISSUE THREAD

**Issue by rlangefe** [LLNL/spack#26949]
### Steps to reproduce

I ran the following command with a fresh Spack installation to attempt to create an environment directory. This is a multi-node system and works on the head node, but I get the error message that's included here when I tried on another node. I should also note that this error occurs both on NFS mounted paths and on non-NFS mounted paths. It also happens when the directory `Cardioid-env/` already exists (but the directory `Cardioid-env/`) and when there is no directory there. This also occurs when I just try `spack env create cardioid-env` without a directory. Again, both commands work fine on the head node, but neither works on the other nodes.
```console
spack env create -d Cardioid-env/
```

### Error message

```console
==> Error: [Errno 39] Directory not empty: '.spack-env'
```

### Information on your system

* **Spack:** 0.16.3-4986-7380161
* **Python:** 3.6.8
* **Platform:** linux-ol7-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
It seems the subdirectory `.spack-env` is not empty, so Spack abprts instead of overriding another environment? Closing, but feel free to reopen if you think something else should be investigated.
