### ISSUE TITLE
Environment activation/deactivation issues with [t]csh

### ISSUE THREAD

**Issue by tldahlgren** [LLNL/spack#27024]
Haven't looked at the code yet to see what is going on but I'm seeing the following behavior:

```
$ spack env create a
$ spack env activate a
$ printenv > act-a.txt
$ spack env activate a
SPACK_OLD_PROMPT: Undefined variable.
$ printenv > act2-a.txt
$ diff act-a.txt act2-a.txt
< SPACK_LD_LIBRARY_PATH=/usr/tce/packages/mvapich2/mvapich2-2.3-intel-19.0.4/lib:/usr/tce/packages/intel/intel-19.0.4/lib/intel64
< SPACK_ENV=/usr/WS1/dahlgren/releases/spack/var/spack/environments/a
---
> SPACK_LD_LIBRARY_PATH=/usr/WS1/dahlgren/releases/spack/var/spack/environments/a/.spack-env/view/lib64:/usr/WS1/dahlgren/releases/spack/var/spack/environments/a/.spack-env/view/lib:/usr/tce/packages/mvapich2/mvapich2-2.3-intel-19.0.4/lib:/usr/tce/packages/intel/intel-19.0.4/lib/intel64
$ spack env deactivate
==> Error: No environment is currently active.
$ printenv > deact-a.txt
$ diff deact-a.txt act2-a.txt   # Note no differences
$ spack env remove a
$ printenv > rem-a.txt
$ diff act2-a.txt rem-a.txt   # Note no differences
```

And environment variables still have paths to the view.

_Originally posted by @tldahlgren in https://github.com/spack/spack/issues/25409#issuecomment-953132990_

**Comment by haampie** [comment]
@scheibelp can we turn your comment into a pull request? I'm not super familiar with csh and its interpolation behavior, so I didn't do it

**Comment by tldahlgren** [comment]
> @scheibelp can we turn your comment into a pull request? I'm not super familiar with csh and its interpolation behavior, so I didn't do it

@haampie I created this via GitHub but could've picked a better comment.  Do you mean turn his comment into an issue?

**Comment by tldahlgren** [comment]
Duplicates #27027
