### ISSUE TITLE
Use AutotoolsPackage for Qt?

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#2702]
@alalazo Can `qt` be converted to `AutotoolsPackage`?  It looks a bit complicated, so I'm looking to you for advice on this one; but I see no fundamental reason it cannot.

https://github.com/LLNL/spack/blob/7043fff8078d0b7a62895302dabbe71904220edf/var/spack/repos/builtin/packages/qt/package.py

**Comment by citibeth** [comment]
See #2703...

**Comment by adamjstewart** [comment]
Should be pretty easy. Just convert each individual `configure` to `configure_args` (keeping the `@when`) and remove the `install` method.

**Comment by citibeth** [comment]
OK, can you please give it a look?  I haven't tried it out, so Travis might
find a syntax error as well.

BTW... can I convert:
```
(['-qt-xcb'] if (not sys.platform == 'darwin') else []) +
(['-skip', 'webengine'] if '~webkit' in self.spec else [])
```
to
```
(['-qt-xcb'] if (sys.platform != 'darwin') else []) +
(['-skip', 'webengine'] if '+webkit' not in self.spec else [])
```
