### ISSUE TITLE
Environment activation/deactivation issue with [t]csh

### ISSUE THREAD

**Issue by tldahlgren** [LLNL/spack#27027]
As for your initial issue in https://github.com/spack/spack/pull/25409#issuecomment-953132990:

```
$ spack env activate a
SPACK_OLD_PROMPT: Undefined variable.
```

There seems to be a problem with our generated csh commands where we don't enclose them in ``` `` ``` and they therefore are evaluated, for example:

```
if ( $?SPACK_OLD_PROMPT ) set prompt="$SPACK_OLD_PROMPT" && unsetenv SPACK_OLD_PROMPT ;
```

Appears in `spack env activate --csh <name-of-env>`, but this fails in my env when `$SPACK_OLD_PROMPT` isn't defined because it tries to evaluate the variable inside the statement (even if the statement itself isn't evaluated). So the following appears to get desirable behavior:

```
if ( $?SPACK_OLD_PROMPT ) `set prompt="$SPACK_OLD_PROMPT" && unsetenv SPACK_OLD_PROMPT` ;
```

I likewise had to make a similar edit to `pathadd.csh` to get `setup-env.csh` to work:

```
diff --git a/share/spack/csh/pathadd.csh b/share/spack/csh/pathadd.csh
index ec394e8990..7f3424518a 100644
--- a/share/spack/csh/pathadd.csh
+++ b/share/spack/csh/pathadd.csh
@@ -22,7 +22,7 @@ endif
 set _pa_old_value = ""
 eval set _pa_set = '$?'$_pa_varname
 if ($_pa_set == 1) then
-    eval set _pa_old_value='$'$_pa_varname
+    eval `set _pa_old_value = '$'$_pa_varname`
 endif
 
 # Do the actual prepending here, if it is a dir and not already in the path
```

_Originally posted by @scheibelp in https://github.com/spack/spack/issues/25409#issuecomment-953332271_

**Comment by tldahlgren** [comment]
@haampie Is this what you meant?  It's definitely a much better comment for the issue. :grin:

**Comment by haampie** [comment]
Yes! Btw, we got a PR in for zsh (#26120), I created a PR for sh (#27012), Peter had this comment for csh, and then there still is this one https://github.com/spack/spack/issues/26830 about fish... Still in time for 0.17? :laughing:

**Comment by tldahlgren** [comment]
> Yes! Btw, we got a PR in for zsh (#26120), I created a PR for sh (#27012), Peter had this comment for csh, and then there still is this one #26830 about fish... Still in time for 0.17? 😆

I've never used the fish shell.  

We're trying to get `0.17` out this week.
