### ISSUE TITLE
does spack work on apple M1 mac mini yet?

### ISSUE THREAD

**Issue by gsiawGH** [LLNL/spack#27050]
### Steps to reproduce

git clone https://github.com/spack/spack ~/spack
cd ~/spack
git checkout releases/v0.16    
. share/spack/setup-env.sh

this is following the steps in https://spack-tutorial.readthedocs.io/en/latest/tutorial_basics.html#

### Error message

sysctl: unknown oid 'machdep.cpu.leaf7_features'
sysctl: unknown oid 'machdep.cpu.vendor'
sysctl: unknown oid 'machdep.cpu.model'
sysctl: unknown oid 'machdep.cpu.leaf7_features'
sysctl: unknown oid 'machdep.cpu.vendor'
sysctl: unknown oid 'machdep.cpu.model'
sysctl: unknown oid 'machdep.cpu.leaf7_features'
sysctl: unknown oid 'machdep.cpu.vendor'
sysctl: unknown oid 'machdep.cpu.model'

### Information on your system

* **Spack:** 0.16.3
* **Python:** 3.8.9
sysctl: unknown oid 'machdep.cpu.leaf7_features'
sysctl: unknown oid 'machdep.cpu.vendor'
sysctl: unknown oid 'machdep.cpu.model'
* **Platform:** darwin-bigsur-arm64

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by gsiawGH** [comment]
this is very similar to https://github.com/spack/spack/issues/22088
but not sure how that was resolved.

**Comment by alalazo** [comment]
@gsiawGH Can you check the latest `develop` branch? It should work there.

**Comment by gsiawGH** [comment]
great, if i use the share/spack/setup-env.sh script from the develop branch, and then checkout the "releases/v0.16" branch, then the installs are working again!

so the work-around is to copy the share/spack/setup-env.sh from the develop branch, after switching to the "releases/v0.16" branch

so that i can create new sessions with the proper setup-env.sh script

**Comment by gsiawGH** [comment]
oh, however, i am still getting these errors, during the installation. but at least its not killing the installation!

sysctl: unknown oid 'machdep.cpu.leaf7_features'
sysctl: unknown oid 'machdep.cpu.vendor'
sysctl: unknown oid 'machdep.cpu.model'
sysctl: unknown oid 'machdep.cpu.leaf7_features'
sysctl: unknown oid 'machdep.cpu.vendor'
sysctl: unknown oid 'machdep.cpu.model'

**Comment by gsiawGH** [comment]
with this workaround, im still getting installation errors 

so far, i can install coreutils and zlib, but cant install fish

while installing fish, it breaks on dependency openssl

spack install openssl
[spack-build-out.txt](https://github.com/spack/spack/files/7445083/spack-build-out.txt)

**Comment by alalazo** [comment]
Sorry for not being clear. This is supposed to be working on latest develop. Whether or not it works on the v0.16.3 release depends on the version of `archspec` we have there.

**Comment by gsiawGH** [comment]
ok, yes, running from develop branch, no issues with . share/spack/setup-env.sh

however, i am not able to install any basic packages, like git or coreutils

**Comment by gsiawGH** [comment]
fixed.  had to reinstall spack from scratch and checkout "releases/v0.17"
