### ISSUE TITLE
py-pylint@2.3.1: ubuntu 18.04: no module named pip

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#27075]
### Steps to reproduce the issue

`py-pylint@2.3.1` build is failing using:
* `spack@develop` (commit 890095e876a85d91ae7359f9120082c4e2f6a249 from `Wed Oct 27 16:26:22 2021 -0400`)
* Ubuntu 18.04, GCC 7.5.0, x86_64
* Python 3.8.12

Concrete spec: [py-pylint-4nn3nb.spec.yaml.txt](https://github.com/spack/spack/files/7444063/py-pylint-4nn3nb.spec.yaml.txt)

Reproduced using Docker container image `ecpe4s/ubuntu18.04-runner-x86_64:2021-11-01`

```
$> spack mirror add E4S https://cache.e4s.io
$> spack buildcache keys -it

$> spack install --cache-only --include-build-deps --only dependencies -f ./py-pylint-4nn3nb.spec.yaml

$> spack install --no-cache -f ./py-pylint-4nn3nb.spec.yaml
...
==> Installing py-pylint-2.3.1-hfmugscen746nlointhvkntjxu6h35hw
==> Fetching https://mirror.spack.io/_source-cache/archive/72/723e3db49555abaf9bf79dc474c6b9e2935ad82230b10c1138a71ea41ac0fff1.tar.gz
==> No patches needed for py-pylint
==> py-pylint: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 1:
    '/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/python-3.8.12-ppq3wrj5444lzrxhw2yctvoza2xmfuhx/bin/python3.8' '-s' 'setup.py' '--no-user-cfg' 'build'

1 warning found in build log:
  >> 3    WARNING: The wheel package is not available.
     4    /spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/python-3.8.12-ppq3wrj5444lzrxhw2yctvoza2xmfuhx/bin/python3.8: No module named pip
     5    Traceback (most recent call last):
     6      File "/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/py-setuptools-58.2.0-6ebyf3yop673cupktevl5jlxv4eoerrq/lib/python3.8/site-packages/setuptools/ins
          taller.py", line 75, in fetch_build_egg
     7        subprocess.check_call(cmd)
     8      File "/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/python-3.8.12-ppq3wrj5444lzrxhw2yctvoza2xmfuhx/lib/python3.8/subprocess.py", line 364, in check_
          call
     9        raise CalledProcessError(retcode, cmd)

See build log for details:
  /tmp/root/spack-stage/spack-stage-py-pylint-2.3.1-hfmugscen746nlointhvkntjxu6h35hw/spack-build-out.txt
```

### Information on your system

* **Spack:** 0.16.3-5058-890095e876
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-cascadelake
* **Concretizer:** clingo

### Additional information

[pylint-build-out.txt](https://github.com/spack/spack/files/7444078/pylint-build-out.txt)
[pylint-build-env.txt](https://github.com/spack/spack/files/7444087/pylint-build-env.txt)

@adamjstewart 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
I'm unable to reproduce this on my own Ubuntu 18.04 machine.

> WARNING: The wheel package is not available.

I'm pretty sure this is a red herring. We don't use wheel because we aren't building any wheels.

**Comment by eugeneswalker** [comment]
From the top of the build log:
```
==> py-pylint: Executing phase: 'build'
==> [2021-10-29-12:57:22.227580] '/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/python-3.8.12-ppq3wrj5444lzrxhw2yctvoza2xmfuhx/bin/python3.8' '-s' 'setup.py' '--no-user-cfg' 'build'
WARNING: The wheel package is not available.
/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/python-3.8.12-ppq3wrj5444lzrxhw2yctvoza2xmfuhx/bin/python3.8: No module named pip
```

Looks like the real issue is this:
```
.../bin/python3.8: No module named pip
```

I'm not having this problem in our Ubuntu 20.04 containers, or in the ppc64le version of our Ubuntu 18.04 container -- do you know what outside of Spack could cause this?

**Comment by eugeneswalker** [comment]
Adding a build dependency on `py-pip` resolved this for me. What do you think @adamjstewart?

Would this be appropriate as a PR? I will make one if you give the nod.

**Comment by adamjstewart** [comment]
I've been planning to overhaul our PythonPackage build system to install with pip instead of `python setup.py install` but haven't gotten a chance yet. I'm hoping that will solve this issue and a lot of others I've seen reported.

**Comment by eugeneswalker** [comment]
> I've been planning to overhaul our PythonPackage build system to install with pip instead of `python setup.py install` but haven't gotten a chance yet. I'm hoping that will solve this issue and a lot of others I've seen reported.

Should we add `py-pip` as build dependency of `py-pylint` until then?

**Comment by adamjstewart** [comment]
If that solves your problem I'm fine with that, just add a comment pointing to this issue so we know why it's there.
