### ISSUE TITLE
Cannot use spack packages from cmake

### ISSUE THREAD

**Issue by acgetchell** [LLNL/spack#27096]
### Steps to reproduce

In short:
```
spack install boost
spack load boost
```

All steps and configurations outlined in this repo:

https://github.com/acgetchell/causal-sets-explorer

### Error message

```
fatal error: 'boost/graph/adjacency_list.hpp' file not found
#include <boost/graph/adjacency_list.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/causal_sets_explorer.dir/src/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/causal_sets_explorer.dir/all] Error 2
make: *** [all] Error 2
```

### Information on your system

```
$ spack debug report
* **Spack:** 0.16.3-5066-8ca3a0fdf8
* **Python:** 3.9.7
* **Platform:** darwin-monterey-skylake
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
You should use `find_package(Boost REQUIRED)` as all Spack does is it sets CMAKE_PREFIX_PATH, and it'd be better to add a package.py for your package either in Spack or in your own repo.
