### ISSUE TITLE
Tests failing for Python 2.6

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#2711]
See https://travis-ci.org/LLNL/spack/jobs/187996732 for details. Looks like it is complaining about [this line](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/file_cache.py#L152).
```
TypeError: exceptions must be old-style classes or derived from BaseException, not str
```

**Comment by adamjstewart** [comment]
Maybe this is a transient error? I added a [commit](https://github.com/LLNL/spack/pull/2709/commits/f601e0016daa9def516df839ec2c726f3607ed30) that fixed a bug I found and the error message no longer appears. I can't tell whether or not they are related.

**Comment by citibeth** [comment]
I saw that transient error at one point too.

**Comment by adamjstewart** [comment]
I haven't seen this in a while so I think it's safe to ignore.
