### ISSUE TITLE
Clingo prefers old versions to using a develop branch

### ISSUE THREAD

**Issue by mdorier** [LLNL/spack#27199]
### Steps to reproduce

Here is an example of situation where spack chooses a lower version than necessary for a dependency:

```console
$ git clone https://github.com/mochi-hpc/mochi-spack-packages.git
$ spack repo add mochi-spack-packages
$ spack spec -I mochi-bedrock        # will use mochi-bedrock@0.3.1
$ spack spec -I mochi-remi        # will use mochi-bedrock@0.2.3
$ spack spec -I mochi-remi ^mochi-bedrock@0.3.1       # will use mochi-bedrock@0.3.1
```

In this example, `mochi-bedrock` has versions `0.2.3`, `0.3`, and `0.3.1` (and some lower numbered versions). `mochi-remi` has `depends_on('mochi-bedrock@0.2:')`. So I would expect `spack spec -I mochi-remi` to show `mochi-bedrock@0.3.1` in the dependency tree, yet I see `mochi-bedrock@0.2.3`. The previous line, requesting the spec for `mochi-bedrock` alone, correctly gives `mochi-bedrock@0.3.1`, and the last line, which explicitly requests 0.3.1, correctly shows it.

The problem seems to be that `mochi-bedrock` depends on a package, `mochi-ssg`, as follows:

```python
    depends_on('mochi-ssg@0.4.5', when='@0.1.0:0.3.0')
    depends_on('mochi-ssg@main', when='@0.3.1:9.9.9')
```

So spack has to choose between using `mochi-bedrock@0.3.1 + mochi-ssg@main` or using `mochi-bedrock@0.2.3 + mochi-ssg@0.4.5`. For some reason, it favors the latter (maybe because it's two numbered versions?).

If I change `main` in the above dependency into `0.4.5`, `spack spec -I mochi-remi` correctly uses the latest version of `mochi-bedrock`. This is what makes me think that it's spack favoring a numbered version down the tree.

This behavior is very counterintuitive and confusing (especially because `spack spec -I mochi-bedrock` gives the latest version), the problem is hard to track down. It is also quite frustrating as in our CI build, spack has continued to use an old version of the `mochi-bedrock` package for some time without us noticing, and we can't rely on spack always picking the latest versions of every packages without telling it to.

### Information on your system

* **Spack:** 0.16.3-4907-1156c7d0a9
* **Python:** 3.9.5
* **Platform:** linux-ubuntu21.04-sandybridge
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
This works as expected. The ordering of versions is done by:

https://github.com/spack/spack/blob/4ace1e660a3ab60a2e510308d700e251126f8c0e/lib/spack/spack/solver/asp.py#L1614-L1619

I would say it would be unexpected to prefer `main` to a known stable version by default. If you need to always use a certain version you can configure Spack with e.g. https://spack.readthedocs.io/en/latest/build_settings.html#package-requirements
