### ISSUE TITLE
hpx package.py: self.variants['instrumentation'].values: 'tuple' object has no attribute 'values'

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#27213]
### Steps to reproduce the issue

`hpx`'s package.py has an issue in `spack@develop` (b9cdaa542916bbdc98b2b6c81fe1126af425e031 from `Wed Nov 3 21:07:35 2021 -0400`)

Seeing the same error on:
* Ubuntu 18.04, GCC 7.5.0, x86_64 and ppc64le
* Ubuntu 20.04, GCC 9.3.0, x86_64 and ppc64le

```
$> spack install hpx
...
==> Installing hpx-1.7.1-dwyyd3j34r3yydrz5vftzv25ms7bqnsn
==> Fetching https://mirror.spack.io/_source-cache/archive/00/008a0335def3c551cba31452eda035d7e914e3e4f77eec679eea070ac71bd83b.tar.gz
==> No patches needed for hpx
==> hpx: Executing phase: 'cmake'
==> Error: AttributeError: 'tuple' object has no attribute 'values'

/spack/var/spack/repos/builtin/packages/hpx/package.py:166, in instrumentation_args:
        165    def instrumentation_args(self):
  >>    166        for value in self.variants['instrumentation'].values:
        167            if value == 'none':
        168                continue
        169
```

### Information on your system

* **Spack:** 0.16.3-5229-b9cdaa5429
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** clingo

### Additional information

@teonnik @msimberg @albestro

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by albestro** [comment]
Thanks for reporting it.

Apparently, the problem has been also noted in https://github.com/spack/spack/pull/27185#discussion_r742385665.

@haampie do you suggest to open a quick patch PR for just that single fix or wait for #27185 to be merged?
