### ISSUE TITLE
`install_tree` in `~/.spack/config.yaml` doesn't take effect.

### ISSUE THREAD

**Issue by weijianwen** [LLNL/spack#2729]
I'm going through Spack tutorials on Cent OS 7 with GCC 4.8.5. All work haven been done on spack v0.9.1 release. 

I find that `install_tree` customized in `~/.spack/config.yaml` doesn't take effect. Installation still goes into `$SPACK_ROOT/opt/spack`.

Documents seem a bit out-of-date which reflect the following changes in spack-v0.9.1.

1. There is no `etc/spack/defaults/config.yaml` file now. (http://spack.readthedocs.io/en/latest/config_yaml.html)
2. `config` is not an acceptable option for `spack config get` now. (http://spack.readthedocs.io/en/latest/configuration.html)

```
$ spack config get compilers
compilers:
  linux-x86_64:
    gcc@4.8.5:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran

$ spack config get config
==> Error: Invalid config section: 'config'. Options are: repos mirrors modules packages compilers

$ cat ~/.spack/config.yaml
config:
  install_tree: /lustre/spack
  build_stage:
    - /tmp

$ spack purge; rm -rf $SPACK_ROOT/var/spack/stage; rm -rf $SPACK_ROOT/spack/opt/

$ spack install libelf
==> Installing libelf
==> Trying to fetch from http://www.mr511.de/software/libelf-0.8.13.tar.gz
######################################################################## 100.0%
==> Staging archive: /home/rpm/spack/var/spack/stage/libelf-0.8.13-zmdylsxe557dvxk32w3rtkad2o3a3xiw/libelf-0.8.13.tar.gz
==> Created stage in /home/rpm/spack/var/spack/stage/libelf-0.8.13-zmdylsxe557dvxk32w3rtkad2o3a3xiw
==> No patches needed for libelf
==> Building libelf
==> Successfully installed libelf
  Fetch: 0.02s.  Build: 4.48s.  Total: 4.51s.
[+] /home/rpm/spack/opt/spack/linux-x86_64/gcc-4.8.5/libelf-0.8.13-zmdylsxe557dvxk32w3rtkad2o3a3xiw
```

**Comment by adamjstewart** [comment]
Spack's documentation is for develop, not for v0.9.1. That release is massively out of date. We plan on a 0.10 release any day now, but I suggest you use develop if you can. We should probably allow older versions of the documentation to appear on readthedocs though...

**Comment by tgamblin** [comment]
@adamjstewart: planned, but the docs didn't build for version 0.9.1 :smile:.

**Comment by weijianwen** [comment]
Thank you. I re-clone the develop branch and everything works like charm.

**Comment by tgamblin** [comment]
> Thank you. I re-clone the develop branch and everything works like charm.

Hopefully that's the experience of the silent majority of Spack users 😄
