### ISSUE TITLE
got an error " This does not look like a tar archive"

### ISSUE THREAD

**Issue by longlong10086** [LLNL/spack#27309]
### Steps to reproduce

spack -d install  kim-api@2.2.1   %gcc@10.2.0

Decompressing the txz compressed package failed with the parameter oxf, but succeeded with oxJf．
How to modify the parameters of tar？

### Error message

==> [2021-11-09-17:43:52.242393] '/bin/tar' '-oxf' '/tmp/globus/spack-stage/spack-stage-kim-api-2.2.1-q2r6i2hujkagi5klbidhkjpbr242zwov/kim-api-2.2.1.txz'          [0/1956]
/bin/tar: This does not look like a tar archive
/bin/tar: Skipping to next header
/bin/tar: Exiting with failure status due to previous errors

### Information on your system

* **Spack:** 0.16.1
* **Python:** 2.6.6
* **Platform:** linux-neokylin3-nehalem
* **Concretizer:** original

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
* **Spack:** 0.20.0.dev0 (2f1e0a372087976e566e8e8b8dbb1d475c08ce4e)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

```console
$ spack stage kim-api
==> Fetching https://mirror.spack.io/_source-cache/archive/1d/1d5a12928f7e885ebe74759222091e48a7e46f77e98d9147e26638c955efbc8e.txz
==> Staged kim-api in /tmp/culpo/spack-stage/spack-stage-kim-api-2.2.1-piofsmovwp36f5z5tn2wkhx52jwcdw73
```
