### ISSUE TITLE
Use zlib tarballs hosted on github release

### ISSUE THREAD

**Issue by weijianwen** [LLNL/spack#2730]
I feel that downloading zlib tallballs fails frequently. At its latest commit 2322ded , downloadig 1.2.10 fails again -- the URL http://pkgs.fedoraproject.org/repo/pkgs/mingw-zlib/zlib-1.2.10.tar.gz/44d667c142d7cda120332623eab69f40/zlib-1.2.10.tar.gz is not available.

How about using zlib's github release page to server zlib tarballs? This page has a clear records of up-to-date and historical zlib tarballs. https://github.com/madler/zlib/releases

**Comment by tgamblin** [comment]
I like this better than the existing URLs.  @citibeth?  @adamjstewart?

FWIW, I plan to have a Spack mirror up at LLNL sometime soon -- for when things fail.

**Comment by weijianwen** [comment]
One disadvantage of downloading tarballs from the github release page is that, the file is named after 'vx.x.x.tar.gz', rather than 'zlib-vx.x.x.tar.gz'. That may result in a higher probability of name conficts for local cached packages.

**Comment by tgamblin** [comment]
@weijianwen The local cache is stored with the same directory structure as a mirror -- the tarballs are always named `<package>/<package>-<version>.<extension>` within the mirror root `var/spack/cache`.  So there shouldn't be conflicts.

**Comment by weijianwen** [comment]
Sounds good. I've successully built GCC 4.9.4 tool chains agains the zlib tarballs from github release page. I'll submit a PR and close this issue.

**Comment by weijianwen** [comment]
See PR #2731 .

**Comment by citibeth** [comment]
There are plenty of unverified forks out there on GitHub.  Who knows what they really contain?  But as long as the tarball has the same hash as the Original True Tarball, I don't care where it came from.  I'm not concerned if PRs like this change URLs, only if they change hashes.

**Comment by weijianwen** [comment]
@citibeth  I thinks the github repo https://github.com/madler/zlib is owned by Mark Adler (@madler), the current maintainer of zlib. Since all the releases are signed Mark's GPG key and being transferred via HTTPS, I consider the tarballs trustful. Sourceforge on the other hand has a not-that-good reputation that it inserted adwares to filezilla and gimp in 2015. Personally I rarely used it since then.

I am preparing a PR which: 1) has a downloading site (yes from sourceforge); 2) and has the identical checksums as the original zlib tarballs. 3) sure with clear URL patterns.

How to build trust aginst package sources remian unsolved. Feedbacks are welcome.

**Comment by weijianwen** [comment]
I see #2733 . So I can close  this issue and RP #2733 .
