### ISSUE TITLE
Installation issue: openmpi

### ISSUE THREAD

**Issue by jthies** [LLNL/spack#27311]
### Steps to reproduce the issue

```console
spack install openmpi schedulers=slurm ^slurm
```
What happens is that this concretizes to openmpi ~pmix schedulers=slurm ^slurm~pmix,
but during the build there is an error message
```
error found in build log:
     150    checking whether cuPointerGetAttributes is declared... no
     151    checking if have cuda support... no
     152    checking if user requested PMI support... no
     153    configure: WARNING: Open MPI requires PMIx support. It can be built
     154    configure: WARNING: with either its own internal copy of PMIx, or with
     155    configure: WARNING: an external copy that you supply.
  >> 156    configure: error: Cannot continue


```
So I believe there is a line missing in the openmpi/package.py like
```
conflicts('~pmi', when='schedulers=slurm')
```

### Information on your system

 **Spack:** 0.17.0-4-4c08beeaef
* **Python:** 3.8.10hppritcha  naughtont3
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo
* 
[spack-build-env.txt](https://github.com/spack/spack/files/7504250/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7504252/spack-build-out.txt)

@hppritcha, @naughtont3

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
See https://github.com/spack/spack/pull/27258, closing assuming this is the solution, otherwise please reopen.

**Comment by steo85it** [comment]
Adding `+pmix` works for me, so I guess #27258 should also work. Thanks for mentioning and solving this!
