### ISSUE TITLE
Correct Zlib Download Link

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#2732]
@BarrySmith @hartzell @tgamblin @adamjstewart 

Here is the correct URL to download old versions of Zlib.  I recommend we move the `1.2.8` link to there.  It should have the same has code as it did before.  Apparently, zlib is one of those annoying sites that changes a URL after it's no longer the latest.

http://zlib.net/fossils/

-- Elizabeth

**Comment by alalazo** [comment]
Fixed by #2735
