### ISSUE TITLE
LD_LIBRARY_PATH not set when environment is re-activated

### ISSUE THREAD

**Issue by jphill4** [LLNL/spack#27346]
Edit: since Spack 0.19 we no longer set LD_LIBRARY_PATH because it breaks system executables.

### Steps to reproduce

I've noticed that when activating an environment, the LD_LIBRARY_PATH variable is not always getting set. A bit of testing showed that the first time an environment is loaded, LD_LIBRARY_PATH is set correctly. If the environment is then deactivated and subsequently re-activated, PATH will be correctly set but LD_LIBRARY_PATH will not be. 

```
spack env activate my_env
spack env deactivate 
spack env activate my_env
```

### Error message

[01_Initial_Environment.txt](https://github.com/spack/spack/files/7518662/01_Initial_Environment.txt)
[02_First_Activation_GOOD.txt](https://github.com/spack/spack/files/7518663/02_First_Activation_GOOD.txt)
[03_First_Deactivate_GOOD.txt](https://github.com/spack/spack/files/7518664/03_First_Deactivate_GOOD.txt)
[04_Second_Activate_BAD.txt](https://github.com/spack/spack/files/7518665/04_Second_Activate_BAD.txt)
[spack.yaml.txt](https://github.com/spack/spack/files/7518675/spack.yaml.txt)

### Information on your system

* **Spack:** 0.16.3-5292-c5be548046
* **Python:** 3.8.2
* **Platform:** linux-ubuntu20.04-skylake
* **Concretizer:** clingo

This is a WSL1 instance running under Windows 10. I have Environment Modules installed in addition to Spack, but the above issue occurs even when all modules are purged.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by RichardYCJ** [comment]
I've encountered similar problem. My `LD_LIBRARY_PATH` will not be set even when activating for the first time. Any updates about this issue? @jphill4

**Comment by jphill4** [comment]
@RichardYCJ: I ended up not pursuing spack (not because of this, and no fault of spack, just not enough time/urgency to justify the effort) so I have not attempted to resolve this or test if it was fixed is later versions.

**Comment by robers97** [comment]
I have run across this too now.  I attribute it to the more popular workflows using module files at runtime instead of spack environments.

**Comment by haampie** [comment]
LD_LIBRARY_PATH is not set by default because it's not necessary for binaries created by Spack, and the big downside is that system executables will pick up spack libraries if you set that variable, causing them to error. The variable may be required in for some dynamic languages that need to dlopen things by name, but that should be fixed on a per-package basis.

If you really need this variable, see the solution in https://github.com/spack/spack/discussions/30634 under v0.19:

```
spack config add modules:prefix_inspections:lib64:[LD_LIBRARY_PATH]
spack config add modules:prefix_inspections:lib:[LD_LIBRARY_PATH]
```

**Comment by robers97** [comment]
Thank you
