### ISSUE TITLE
python curses module broken, ncurses inconsistency

### ISSUE THREAD

**Issue by dylex** [LLNL/spack#27369]
The curses module in python doesn't work (at least when built with readline and ncurses from spack).  Even fairly [simple curses scripts](https://gist.github.com/blackwer/0c0231526f8129ae558700238357d1a4) segfault or otherwise misbehave.  The [`test_curses.py`](https://github.com/python/cpython/blob/main/Lib/test/test_curses.py) python test also fails.

There are a number of things going wrong here, mostly around inconsistencies between the ncurses headers and libraries.  As background, to build something against ncurses, it must include and link against exactly matching versions of ncurses (non-widec) _xor_ ncursesw (widec). If you mix wide-non-wide or different versions things won't work, as struct sizes and char types won't match.

First, python chooses whichever ncurses library readline is linked against.  Since readline is linked with both(!) (#3802) it ends up finding whichever one `ldd` reports first.  If python finds libncursesw, python `setup.py` adds `/usr/include/ncursesw` to the includes, which is likely a different ncurses version.  If it finds libncurses, it uses that.  Either way, it just includes `<ncurses.h>`.

The ncurses package installs only the ncursesw headers, to three places (include, include/ncurses, include/ncursesw), as per #353, #3953. This means that anything that tries to use non-wide ncurses won't work, as it ends up including the wide headers instead.  The only distributions I've found that do this also use libncursesw as libncurses (so only wide everywhere).  Most install non-wide into include or include/ncurses and wide into only include/ncursesw.  #27372 fixes this, installing wide and non-wide headers separately. Though it leaves the question of which version to install un-prefixed (in include/ncurses.h: whether to keep wide for backwards compatibility, or non-wide to match standard practice and libncurses).

So, python's curses library ends up building with the system ncursesw headers and spack libncursesw, or with spack's ncursesw headers and spack libncurses.  Either way, the result is broken.

An added complication is that the python curses library doesn't seem to work properly with non-wide ncurses at all.  I'm not sure if this is a known issue, but every other python distribution/package I can find links with ncursesw, so this should be the goal.  This can be achieved by adding `-I${ncurses.prefix.include}/ncursesw` to CPPFLAGS and `-lncursesw` to `Modules/Setup`.  #27375 solve that, but I wanted to make a place to discuss the issue as a whole.

It's also the case that only #27375 is necessary to fix the python issue, but #27372 is needed if anything wants to build against libncurses as well.

**Comment by adamjstewart** [comment]
Thanks for opening this issue. The `ncurses` vs `ncursesw` (and `+termlib` vs `~termlib`) issue has been a headache in a lot of packages. We previously added a `wide` variant to `ncurses` that controlled whether we built `ncurses` or `ncursesw`, but that had a lot of issues too (some packages in a DAG required `+wide` while others in the same DAG required `~wide`). For most packages, explicitly querying `spec['ncurses'].libs` and `spec['ncurses'].headers` solved most issues, but it could be the case that Python behaves differently here. It'll take me some time to review your proposed solution, but hopefully someone with more ncurses expertise than me can review it first.

**Comment by dylex** [comment]
Thanks.  Yeah, ncurses is a headache for many distributions and everyone does something slightly differently, with no great standard solutions.

For #27372, the important piece is installing the non-wide headers *somewhere*. Wether or not other packages are including the right one is a different question. The safest change would be to only install them in `include/ncurses`, and leave the ncursesw headers in `include`. (This is not what my PR does now but I'm leaning towards doing that instead.)

For #27375, the important piece is making python use only libncursesw headers and library. There may be a better way to do that (or just better syntax, using `.headers` instead of `.prefix.include` for example) but I think the idea is correct.  Ultimately the problem here is some inflexible assumptions in python's `setup.py` which this just works around, though this could also be achieved by patching `setup.py` like is done for `tkinter` (and many other distributions do similar things).

I'm only doing this on CentOS7.  I realize there may be a whole other set of issues on Mac as well.
