### ISSUE TITLE
Typo in madgraph5amc/package.py

### ISSUE THREAD

**Issue by dkonst13** [LLNL/spack#27397]
Hi @iarspider,

https://github.com/spack/spack/blob/95ad5b882c990971e74d04261a665ba680f7c4be/var/spack/repos/builtin/packages/madgraph5amc/package.py#L55

There is a typo. Probably it makes sense to fix it.

**Comment by iarspider** [comment]
Hi @dkonst13,

I will check, but I think patches for 2.8.0 and 2.8.1 were the same.

Ivan

**Comment by dkonst13** [comment]
I guess you are right. Anyway all available versions look kind of old. 
I think you can close the issue then. Thanks!

**Comment by iarspider** [comment]
Feel free to open PR with update :)
