### ISSUE TITLE
Is there a way to pass a URL as a variant?

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#2744]
Ah, texlive....  Sigh.

Many (Murphy's law says that it's actually *every #@%%$! one that I try*) of the texlive mirrors currently have an out of sync tarball for beamer.  This type of problem seems to occur regularly.

The texlive install script uses the URL 'http://mirror.ctan.org/systems/texlive/tlnet' which redirects to a mirror that's close to you (or if you're me, a mirror that's broken...).

I thought it would be nice to add a variant that allowed one to specify the mirror that one wanted to use, like so:

```
spack install texlive scheme=small repository=http://ctan.math.utah.edu/ctan/tex-archive/systems/texlive/tlnet/
```

So I added this:

```
    variant('repository',
            default='http://mirror.ctan.org/systems/texlive/tlnet',
            description='CTAN mirror to use for download')
```

With that in place, `spack install` complains about an 'Unexpected token'.  A strategically placed `import pdb; pdb.set_trace()` leads me to conclude that it's complaining about the ':'.  I tried a couple of other values and discovered other fun things: e.g. if I change the install method so that it glues the `http://` onto the repository string, I end up with this behavior:

```
spack install texlive repository="ctan.math.utah.edu/tex-archive/systems/texlive/tlnet"
==> Error: tex-archive does not match any installed packages.
```

All of this leads me to believe that I'm misusing the `variant` mechanism.

Is there a proper way that I can pass in a URL?

I'm loath to hardcode a particular mirror, but I'm *sooooo* close to doing so....

**Comment by becker33** [comment]
I am currently working on a rewrite of the parser that would get rid of this issue. It also eliminates the need for escape quotes `\"` for compiler flags.

No PR number yet.

**Comment by hartzell** [comment]
@becker33: 

It sounds like I'm correct in my believe that what I've been trying to do is not currently supposed to work.  True?

Is your parser rewrite on the 0.10 timeline, or post?

**Comment by tgamblin** [comment]
> Is your parser rewrite on the 0.10 timeline, or post?

post, but 1.0 is due in late Feb. 😄

**Comment by adamjstewart** [comment]
I cringe when I think about adding a URL as a variant, but I understand that texlive is an exception. Wish we could contact the developers and ask them to release numbered tarballs. I wonder if there are any mirrors out there that maintain this stuff.

**Comment by eschnett** [comment]
You could just pick one known-to-be-good mirror. Given the speed of Spack and HPC file systems, choosing a "good" mirror is not very important. Maybe there's even an "amazon" or "google" mirror that uses a CDN.

**Comment by hartzell** [comment]
It's like you're here looking over my shoulder....

```diff
diff --git a/var/spack/repos/builtin/packages/texlive/package.py b/var/spack/repos/builtin/packages/texlive/package.py
index a960e5b6..27f6c4c7 100644
--- a/var/spack/repos/builtin/packages/texlive/package.py
+++ b/var/spack/repos/builtin/packages/texlive/package.py
@@ -41,7 +41,7 @@ class Texlive(Package):
     # digest values, but don't be surprised if this package is
     # briefly unbuildable.
     #
-    version('live', '01461ec2cc49fe0b14812eb67abbea46',
+    version('live', 'ad230fa814d122084c13d75c0b135fda',
             url="http://ctan.math.utah.edu/ctan/tex-archive/systems/texlive/tlnet/install-tl-unx.tar.gz")

     # There does not seem to be a complete list of schemes.
@@ -59,9 +59,14 @@ class Texlive(Package):
     depends_on('perl', type='build')

     def install(self, spec, prefix):
+        # Using texlive's mirror system leads to mysterious problems,
+        # in lieu of being able to specify a repository as a variant, hardwire
+        # a particular (slow, but central) one for now.
+        _repository='http://ctan.math.washington.edu/tex-archive/systems/texlive/tlnet/'
         env = os.environ
         env['TEXLIVE_INSTALL_PREFIX'] = prefix
         perl = which('perl')
         scheme = spec.variants['scheme'].value
         perl('./install-tl', '-scheme', scheme,
+             '-repository', _repository,
              '-portable', '-profile', '/dev/null')
```
