### ISSUE TITLE
Config argument helper functions do not support conditional variants

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#27494]
### Steps to reproduce

Currently when you have

```python
variant('x', when='+y')
```
the following errors:
```python
def cmake_args(self):
  return [self.define_from_variant('X', 'x')]
```
when the condition for the existence of the variant is not met.

It's a bit questionable what the behavior of `define_from_variant` *should* be. The most sensible to me is to do nothing when the condition for `x`'s existence is not met. I don't think it should be seen as "off".

But then it's awkward, because the only thing `self.define_from_variant(...)` can do is return an empty string, which would result in an empty argument being passed to `cmake` on the command line like `'cmake' '-DY=OFF' '' ..`.

In autotools we do `args += self.with_or_without('x')` which would handle this situation better, since it can then return an empty array when the condition for `x`'s existence is not met.

### Error message

.

### Information on your system

.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Closed by #27504 and #27503
