### ISSUE TITLE
possible concretizing bug? does not list "openfoam" as a package

### ISSUE THREAD

**Issue by olesenm** [LLNL/spack#27611]
### Steps to reproduce

```
spack list openfoam
```
vs
```
spack list -v openfoam
```

This is pretty strange, since _openfoam_ is actually a package, and does not seem to have anything marked "virtual".
Also a bit annoying, after putting proper effort to package the things in the first place.

### Error message

- `spack list openfoam`
```
==> 1 packages.
openfoam-org
```

- `spack list -v openfoam`
```
==> 2 packages.
openfoam  openfoam-org
```

- `spack list -d openfoam`
```
==> 4 packages.
foam-extend  of-catalyst  of-precice  openfoam-org
```

### Information on your system

* **Spack:** 0.17.0-260-2104f1273a
* **Python:** 3.6.13
* **Platform:** linux-opensuse_leap15-haswell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by olesenm** [comment]
@alalazo - something changed that I've missed?

**Comment by alalazo** [comment]
Sorry, but I can't reproduce on:
* **Spack:** 0.17.0-332-54d88f1a1c
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

```console
$ spack list openfoam
==> 2 packages.
openfoam  openfoam-org

$ spack list -v openfoam
==> 2 packages.
openfoam  openfoam-org

$ spack list -d openfoam
==> 5 packages.
foam-extend  of-catalyst  of-precice  openfoam  openfoam-org
```
Also, I see no `openfoam` virtual package:
```console
$ spack providers
Virtual packages:
    D     daal      flame  glu     iconv  jpeg      mariadb-client  mpi           opencl  pil        scalapack  tbb     xxd
    awk   elf       fuse   glx     ipp    lapack    mkl             mysql-client  osmesa  pkgconfig  sycl       unwind  yacc
    blas  fftw-api  gl     golang  java   lua-lang  mpe             onedal        pbs     rpc        szip       uuid    ziglang
```
I'll mark it as unreproducible. Can you try again after:
```console
$ spack clean -ab
```
?

**Comment by olesenm** [comment]
> I'll mark it as unreproducible. Can you try again after:
> 
> ```
> $ spack clean -ab
> ```

Yup, that was it.
Closing out as 'dirty cache' - thanks @alalazo and apologies for the noise.

**Comment by alalazo** [comment]
No worries, thanks for the report!
