### ISSUE TITLE
Installation issue: `py-mayavi`: `mayavi2` application does not start

### ISSUE THREAD

**Issue by manuelakuhn** [LLNL/spack#27627]
### Steps to reproduce the issue

When installing `py-mayavi` the python library seems to be installed (can be imported) but the 'mayavi2' application coming with it cannot be started. #27626 fixes the problem that vtk is not found by pkg_resources, so that the application at least tries to start. It still fails (gui opens and closes instantly) with the error
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  40 (X_TranslateCoords)
  Resource id in failed request:  0x0
  Serial number of failed request:  9
  Current serial number in output stream:  9
```

Steps to reproduce:
```
$ spack install py-mayavi
$ spack load py-mayavi
$ mayavi2
```

### Information on your system

* **Spack:** 0.17.0-272-a5bd6acd90
* **Python:** 3.8.10
* **Platform:** linux-fedora32-haswell
* **Concretizer:** clingo

### Additional information

maintainers: @adamjstewart 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Have you tried reporting this issue to the mayavi developers? It sounds like a bug in their software, not a bug in Spack.

**Comment by adamjstewart** [comment]
No response from OP. Closing, but feel free to reopen if this is indeed still an issue in Spack.
