### ISSUE TITLE
Installation issue: py-sphinx py-sphinx-rtd-theme py-recommonmark

### ISSUE THREAD

**Issue by spakin** [LLNL/spack#27644]
### Steps to reproduce the issue

```console
$ spack env create sphinx
$ spack env activate sphinx
$ spack install py-sphinx py-sphinx-rtd-theme py-recommonmark
```
leads to
```
==> Error: py-sphinx@4.1.2%gcc@9.4.0 arch=linux-centos8-zen2/2nny57e cannot be installed in python@3.8.12%gcc@9.4.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93189bc278fbc37a50ed7f183bd8aaf249a8e1670a465f0db6bb4f8cf87,4c2457325f2b608b1b6a2c63087df8c26e07db3e3d493caf36a56f0ecf6fb768,f2fd060afc4b4618fe8104c4c5d771f36dc55b1db5a4623785a4ea707ec72fb4 arch=linux-centos8-zen2/riiytyl because it conflicts with py-sphinx@4.1.2%gcc@9.4.0 arch=linux-centos8-zen2/ajl326l
```

### Information on your system

* **Spack:** 0.17.0-278-dbf67d912c
* **Python:** 3.6.8
* **Platform:** linux-centos8-zen2
* **Concretizer:** clingo

[compilers.yaml.txt](https://github.com/spack/spack/files/7597492/compilers.yaml.txt)

### Additional information

Command log: [sphinx.log](https://github.com/spack/spack/files/7597511/sphinx.log)

Maintainer of all three packages (`py-sphinx`, `py-sphinx-rtd-theme`, `py-recommonmark`): @adamjstewart

`py-sphinx` (`py-sphinx-4.1.2-2nny57epsov23xqzkpnqge37mhejcbr2`)
[spack-build-env.txt](https://github.com/spack/spack/files/7597704/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7597707/spack-build-out.txt)

`py-sphinx` (`py-sphinx-4.1.2-ajl326lavbsqtgw6ul4xxph5q27vuwcs`)
[spack-build-env.txt](https://github.com/spack/spack/files/7597715/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7597717/spack-build-out.txt)

`py-sphinx-rtd-theme`
[spack-build-env.txt](https://github.com/spack/spack/files/7597691/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7597695/spack-build-out.txt)

`py-recommonmark`
[spack-build-env.txt](https://github.com/spack/spack/files/7597682/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7597685/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
This looks like an issue with Environments. If you want an environment to have a single copy of `py-sphinx` installed, you should use `concretization: together` in your `spack.yaml` file.

**Comment by spakin** [comment]
That worked for me!

I must admit I don't understand why Spack wanted to install multiple copies of `py-sphinx` from my single `spack install` line in the first place, but thanks for so promptly providing a solution.

**Comment by adamjstewart** [comment]
The reason that multiple copies of `py-sphinx` are being installed is that the version of the `py-docutils` dependency is different:

* `py-sphinx` requires `py-docutils@0.14:0.17`
* `py-sphinx-rtd-theme` requires `py-docutils@:0.16` (but also depends on `py-sphinx` so this becomes `py-docutils@0.14:0.16`)
* `py-recommonmark` requires `py-docutils@0.11:` (but also depends on `py-sphinx` so this becomes `py-docutils@0.14:0.17`)

When you install `py-sphinx` and `py-recommonmark`, it will use `py-docutils@0.17.1`, but when you install `py-sphinx-rtd-theme`, it will use `py-docutils@0.15.2` (since there is no 0.16.X in the package). Does that make sense? The only way for Spack to know this ahead of time and reuse the same version of `py-docutils@0.15.2` is for all packages to be concretized at the same time.

**Comment by spakin** [comment]
Thanks for the explanation.  So even if I `spack install` all three packages in a single command, Spack can't determine that `py-docutils@0.15.2` will make everything work out?

**Comment by adamjstewart** [comment]
By default, Spack Environments treat all packages as independent. This allows you to do things like install multiple versions of a package with different MPI/BLAS/LAPACK libraries. If you add `concretization: together`, Spack will try to create a single DAG of all packages, resulting in usage of `py-docutils@0.15.2`.

**Comment by spakin** [comment]
Got it.  Thanks again.
