### ISSUE TITLE
Installation issue:  rocm-smi-lib@4.3.1

### ISSUE THREAD

**Issue by balay** [LLNL/spack#27683]
### Steps to reproduce the issue

```console
spack install rocm-smi-lib
```

### Information on your system

```console
$ spack debug report
* **Spack:** 0.17.0-316-8ff81d4
* **Python:** 3.6.8
* **Platform:** linux-centos7-broadwell
* **Concretizer:** clingo
```

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/7615084/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7615085/spack-build-out.txt)

cc: @srekolam, @arjun-raj-kuppala

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by balay** [comment]
using the following hack as a workaround - to disable the doc build. Perhaps there is a better way to fix this issue in spack.

```patch
--- a/rocm_smi/CMakeLists.txt   2021-11-25 22:23:30.140220395 -0800
+++ b/rocm_smi/CMakeLists.txt   2021-11-25 22:22:31.802343760 -0800
@@ -138,8 +138,8 @@
 
 
 # Generate Doxygen documentation
-find_package(Doxygen)
-find_package(LATEX COMPONENTS PDFLATEX)
+#find_package(Doxygen)
+#find_package(LATEX COMPONENTS PDFLATEX)
 
 if (DOXYGEN_FOUND AND LATEX_FOUND)
   set (RSMI_MANUAL_NAME "ROCm_SMI_Manual")
```

**Comment by srekolam** [comment]
the above changes are now in spack:develop branch for 4.5.2 onwards. hence closing this ticket.
