### ISSUE TITLE
Installation issue: curl does not configure/build with Intel compilers spa

### ISSUE THREAD

**Issue by markyoder** [LLNL/spack#27709]
@rscohn2

### Steps to reproduce the issue

summary:
`spack install curl@7.80.0 %intel@2021.4.0`

detailed:
```
(base) [myoder96@sh03-05n69 /scratch/users/myoder96/spack_dev/base] (job 39691869) $ spack env create curl2
==> Updating view at /scratch/users/myoder96/spack_dev/base/spack/var/spack/environments/curl2/.spack-env/view
==> Created environment 'curl2' in /scratch/users/myoder96/spack_dev/base/spack/var/spack/environments/curl2
==> You can activate this environment with:
==>   spack env activate curl2
(base) [myoder96@sh03-05n69 /scratch/users/myoder96/spack_dev/base] (job 39691869) $ spack env activate curl2
bash: unalias: despacktivate: not found
(base) [myoder96@sh03-05n69 /scratch/users/myoder96/spack_dev/base] (job 39691869) $ spack add curl@7.80.0 %intel@2021.4.0
(base) [myoder96@sh03-05n69 /scratch/users/myoder96/spack_dev/base] (job 39691869) $ spack concretize --force
==> Starting concretization
==> Environment concretized in 10.35 seconds.
==> Concretized curl@7.80.0%intel@2021.4.0
 -   wmkg47t  curl@7.80.0%intel@2021.4.0 fflags="-fallow-argument-mismatch" ~gssapi~ldap~libidn2~librtmp~libssh~libssh2~nghttp2 patches=bb330614c0d3e046348308fa5dc12132a21a834df2887354fb142516e911d6ba tls=openssl arch=linux-centos7-zen2
[+]  snc5qbt      ^openssl@1.1.1l%intel@2021.4.0 fflags="-fallow-argument-mismatch" ~docs certs=system arch=linux-centos7-zen2
[+]  clrzgmh          ^perl@5.34.0%intel@2021.4.0 fflags="-fallow-argument-mismatch" +cpanm+shared+threads arch=linux-centos7-zen2
[+]  v2znlhh              ^berkeley-db@18.1.40%intel@2021.4.0 fflags="-fallow-argument-mismatch" +cxx~docs+stl patches=b231fcc4d5cff05e5c3a4814f6a5af0e9a966428dc2176540d2c05aff41de522 arch=linux-centos7-zen2
[+]  cr3pw7v              ^bzip2@1.0.8%intel@2021.4.0 fflags="-fallow-argument-mismatch" ~debug~pic+shared arch=linux-centos7-zen2
[+]  656g2tf                  ^diffutils@3.8%intel@2021.4.0 fflags="-fallow-argument-mismatch"  arch=linux-centos7-zen2
[+]  zcaujfu                      ^libiconv@1.16%intel@2021.4.0 fflags="-fallow-argument-mismatch"  libs=shared,static arch=linux-centos7-zen2
[+]  3b6vpfg              ^gdbm@1.19%intel@2021.4.0 fflags="-fallow-argument-mismatch"  arch=linux-centos7-zen2
[+]  miykdke                  ^readline@8.1%intel@2021.4.0 fflags="-fallow-argument-mismatch"  arch=linux-centos7-zen2
[+]  rhs4bbi                      ^ncurses@6.2%intel@2021.4.0 fflags="-fallow-argument-mismatch" ~symlinks+termlib abi=none arch=linux-centos7-zen2
[+]  5bxrapa                          ^pkgconf@1.8.0%intel@2021.4.0 fflags="-fallow-argument-mismatch"  arch=linux-centos7-zen2
[+]  e6kgsmc              ^zlib@1.2.11%intel@2021.4.0 fflags="-fallow-argument-mismatch" +optimize+pic+shared arch=linux-centos7-zen2

==> Updating view at /scratch/users/myoder96/spack_dev/base/spack/var/spack/environments/curl2/.spack-env/view
(base) [myoder96@sh03-05n69 /scratch/users/myoder96/spack_dev/base] (job 39691869) $ spack install
==> Installing environment curl2
[+] /scratch/users/myoder96/spack_dev/base/spack/opt/spack/linux-centos7-zen2/intel-2021.4.0/berkeley-db-18.1.40-v2znlhhcxz6bnphocoyhdlhxpkfb624a
[+] /scratch/users/myoder96/spack_dev/base/spack/opt/spack/linux-centos7-zen2/intel-2021.4.0/libiconv-1.16-zcaujfug2vr3vfeddn7kqxyy275mxijd
[+] /scratch/users/myoder96/spack_dev/base/spack/opt/spack/linux-centos7-zen2/intel-2021.4.0/pkgconf-1.8.0-5bxrapabrixdg3ub6uoeqrq35sz6dqg5
[+] /scratch/users/myoder96/spack_dev/base/spack/opt/spack/linux-centos7-zen2/intel-2021.4.0/zlib-1.2.11-e6kgsmcspij4iwnmz2ncgl34qv4p56wh
[+] /scratch/users/myoder96/spack_dev/base/spack/opt/spack/linux-centos7-zen2/intel-2021.4.0/diffutils-3.8-656g2tfnx2ctb5ev6bkwfrtpke6vrhqp
[+] /scratch/users/myoder96/spack_dev/base/spack/opt/spack/linux-centos7-zen2/intel-2021.4.0/ncurses-6.2-rhs4bbiv63eqpebeoly7igd4z552t4qa
[+] /scratch/users/myoder96/spack_dev/base/spack/opt/spack/linux-centos7-zen2/intel-2021.4.0/bzip2-1.0.8-cr3pw7vvsjueevceokwlnflwa65dccca
[+] /scratch/users/myoder96/spack_dev/base/spack/opt/spack/linux-centos7-zen2/intel-2021.4.0/readline-8.1-miykdkeo4emwqvxr7litxxf2ina7h4hi
[+] /scratch/users/myoder96/spack_dev/base/spack/opt/spack/linux-centos7-zen2/intel-2021.4.0/gdbm-1.19-3b6vpfgwczcfsapaciwnlyfvtpdwb4ao
[+] /scratch/users/myoder96/spack_dev/base/spack/opt/spack/linux-centos7-zen2/intel-2021.4.0/perl-5.34.0-clrzgmhzqbf6n7jehotu5laecfnpko2c
[+] /scratch/users/myoder96/spack_dev/base/spack/opt/spack/linux-centos7-zen2/intel-2021.4.0/openssl-1.1.1l-snc5qbtylltrdy2zl7ahb5vz5ympk5jv
==> Installing curl-7.80.0-wmkg47t77tun2ui5wzrufz72x2x5xfqp
==> No binary for curl-7.80.0-wmkg47t77tun2ui5wzrufz72x2x5xfqp found: installing from source
==> Warning: Intel's compilers may or may not optimize to the same degree for non-Intel microprocessors for optimizations that are not unique to Intel microprocessors
==> Using cached archive: /scratch/users/myoder96/spack_dev/base/spack/var/spack/cache/_source-cache/archive/dd/dd0d150e49cd950aff35e16b628edf04927f0289df42883750cf952bb858189c.tar.bz2
==> Applied patch /scratch/users/myoder96/spack_dev/base/spack/var/spack/repos/builtin/packages/curl/curl_7_78_0_configure_ac.diff
==> curl: Executing phase: 'autoreconf'
==> curl: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/scratch/users/myoder96/spack-build_stage/spack-stage-curl-7.80.0-wmkg47t77tun2ui5wzrufz72x2x5xfqp/spack-src/configure' '--prefix=/scratch/users/myoder96/spack_dev/base/spack/opt/spack/linux-centos7-zen2/intel-2021.4.0/curl-7.80.0-wmkg47t77tun2ui5wzrufz72x2x5xfqp' '--with-zlib=/scratch/users/myoder96/spack_dev/base/spack/opt/spack/linux-centos7-zen2/intel-2021.4.0/zlib-1.2.11-e6kgsmcspij4iwnmz2ncgl34qv4p56wh' '--without-brotli' '--without-libgsasl' '--without-libpsl' '--without-zstd' '--without-ca-bundle' '--without-ca-path' '--with-ca-fallback' '--without-gssapi' '--without-gnutls' '--without-mbedtls' '--without-nss' '--with-openssl=/scratch/users/myoder96/spack_dev/base/spack/opt/spack/linux-centos7-zen2/intel-2021.4.0/openssl-1.1.1l-snc5qbtylltrdy2zl7ahb5vz5ympk5jv' '--without-secure-transport' '--without-libidn2' '--without-librtmp' '--without-nghttp2' '--without-libssh2' '--without-libssh' '--disable-ldap'

1 error found in build log:
     130    configure: compiler options added: -O2
     131    checking if compiler accepts strict warning options... yes
     132    configure: compiler options added: -Wno-system-headers -Wenum-conversion
     133    checking if compiler halts on compilation errors... yes
     134    checking if compiler halts on negative sized arrays... yes
     135    checking if compiler halts on function prototype mismatch... no
  >> 136    configure: error: compiler does not halt on function prototype mismatch.

See build log for details:
  /scratch/users/myoder96/spack-build_stage/spack-stage-curl-7.80.0-wmkg47t77tun2ui5wzrufz72x2x5xfqp/spack-build-out.txt

(base) [myoder96@sh03-05n69 /scratch/users/myoder96/spack_dev/base] (job 39691869) $ 

```

### Information on your system

Stanford's Sherlock HPC:
Linux, CentOS-7

(base) [myoder96@sh03-05n69 /scratch/users/myoder96/spack_dev/base] (job 39691869) $ spack debug report
* **Spack:** 0.17.0-270-c263b64
* **Python:** 3.8.8
* **Platform:** linux-centos7-zen2
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/7622261/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7622263/spack-build-out.txt)

Comments: The package builds with gcc; this appears to be, fundamentally, a bug with `icc` and a ticket should be opened with Intel (which I should be able to do from my end).

 We can successfully work around the problem by modifying the `configure.ac`, removing CURL_CHECK_COMPILER_PROTOTYPE_MISMATCH  (or writing a patch to do so).
 
 My thought is to patch the package for the short term, and push up a ticket to Intel for the long term?

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by markyoder** [comment]
Some additional comments -- some of which are targeted at your less-expert user audience, if that's ok:
Also, what approach do the developers recommend to work around cases like this? I think taking a few moments to recommend some best practices could help some of us operate more efficiently and potentially be more of a benefit, not a burden, to the developers community!

The summary of my experience is that the "right" way to solve this problem is to: make a patch, add patch to package, modify package to force-run autoreconf. This, however, ends up being much more complicated than either 1) Write a patch() script that modifies configure.ac and then executes `autoreconf -if` from the Python script, or 2) generate and apply the patch, then just execute `autoreconf` in patch() script.

detailed discussion:
1) It'e easy enough to produce and apply a patch for this (eg., clone the curl GitHub repo, checkout curl-7_80_8, modify `configure.ac` as discussed above, then do a `git diff -p > curl_intel.patch` -- or something similar). 
2) You can also just write a `patch(self)` function in the Spack `curl` package, eg:

```
    # yoder:
    def patch(self):
        # TODO: Verify this is the correct syntax.
        if not self.spec.satisfies('%intel'):
            print('** DEBUG: non-intel compiler. Exit patch()')
            return None
        #
        S = ''
        print('*** DEBUG: exeduting patch function')
        with open('configure.ac', 'r') as fin:
            for rw in fin:
                if rw.startswith('CURL_CHECK_COMPILER_PROTOTYPE_MISMATCH'):
                  rw = f'#{rw}'
                  print(f'*** DEBUG: patching configure.ac: {rw}')
                S = S + f'{rw}\n'.replace('\n\n', '\n')
            #
        #
        os.system('autoreconf -fi')
        pass
```

3) By itself, `autoreconf` will not run (correctly?). This part  appears to be surprisingly complicated and prone to failure.
  3a) It looks like it is necessary to run `autoreconf` with the `-fi` option(s).
  3b) If I just force this in the patch (et `os.system(autoreconf -f)`) above, it works -- easy-peazie!
  3c) Attempting to do this the 'right?' way, by adding `force_autoreconf = True` to the package is more difficult -- resulting I a bunch of dependencies,. etc. namely, you need to add to the package:
`
    depends_on('autoconf', type='build')
    depends_on('automake', type='build')
    depends_on('libtool', type='build')
`

If I do this, then define autoconf, etc. as external packages pointing to the system defaults (which I run from the Python script), I get a bunch of errors. If I let Spack will want to install its own versions the build is successful.

**Comment by markyoder** [comment]
Adding a quick shout out to developer(s):
@rscohn2

**Comment by scheibelp** [comment]
Hi @markyoder thanks for investigating this. I think if possible we should figure out how to get this check to pass (if I understand correctly, it looks like https://github.com/spack/spack/issues/27709#issuecomment-984134782 bypasses the check). 

I see a relevant thread at https://community.intel.com/t5/Intel-C-Compiler/Help-with-icc-2021-1-macOS-and-cURL/m-p/1246308 but I'd have to think on how to apply it here.

**Comment by markyoder** [comment]
@scheibelp - Agreed! All of the threads I've seen, and what I recommend in my post, is exactly that -- use a patch to exclude the test that fails. As I recall, that test itself is actually supposed to fail, but that is not supposed to trip the installation. 

Given the nature of the problem, I would be tempted to use the `patch()` function, but actually applying a proper patch is perhaps more appropriate and consistent with Spack culture.

But looking at that intel community thread, the trick may be to substitute `-stdlib=libstdc++` with 
`-stdlib=libc++`

Also, I put in a ticket with Intel, but I don't know if they intend to look at it.

How can I help?

**Comment by scheibelp** [comment]
Sorry I mean that ideally we can run the check and it passes (vs. skipping it). The thread I posted suggested a means to that, which I like, but setting `-stdlib=...` seems odd to me so I wanted to read about it more.

The thread also suggested possibly setting `-we147` (convert this particular warning to an error) so perhaps adding that flag would be sufficient (Spack allows a user to define a `flag_handler` method in their function, which could include this, although it's probably easier to test by adding the flag to the compiler definition).

**Comment by markyoder** [comment]
got it! I'll have a look at it.

Adding both of those flags to my `cflags` (and also `cxxflags`, but I think curl is all C, appears to fix the problem! It seems that the `-stdlib-libc++` flag might be a good general purpose flag to keep in the compiler config. Maybe the `-we147` as well?

To be absolutely sure, I'll set up a test with a clean spack clone.

**Comment by rscohn2** [comment]
I could not reproduce the problem on my ubuntu system with:
```
 spack install curl@7.80.0 %intel@2021.4.0
```

When I look at spack-build-out.txt, it is running the problematic check:
```
configure: compiler options added: -fno-omit-frame-pointer -fno-strict-aliasing -fp-model precise
checking if compiler halts on compilation errors... yes
checking if compiler halts on negative sized arrays... yes
checking if compiler halts on function prototype mismatch... yes
checking if compiler supports hiding library internal symbols... yes
```
Since I cannot reproduce the problem, can you try the same thing with the oneapi compiler:
```
 spack install curl@7.80.0 %oneapi@2021.4.0
```

This will use icx/icpx instead of icc/icpc. I don't know if intel will fix the issue you are seeing with icc as most new development is only going into icx.
[spack-build-out.txt](https://github.com/spack/spack/files/7650289/spack-build-out.txt)

**Comment by markyoder** [comment]
Wilco. Could this be related to the Core compiler; CentOS-7 uses `gcc@4.8.5` (except I don't think OneAPI compilers actually compile, do they?), or maybe your Compiler configuration?

I"ll compile with `oneapi` and also put my compiler configs into my environment config.

**Comment by rscohn2** [comment]
icc depends on the system header files. We are both using the system
autotools. I would not have expected any of that to matter. Manual test
shows that icc only warns on my ubuntu system, so I would expect curl build
to fail here, too.

```
***@***.***:local$ icc -c test.c
test.c(3): warning #147: declaration is incompatible with "int foo(int)"
(declared at line 1)
  int foo(float a) {}
      ^

***@***.***:local$
```

**Comment by markyoder** [comment]
Ok. Talked to somebody at Intel; done some more sleuthing, and here's what I (think) I have found -- adding some detail hoping that it will be helpful to others:

Summary: 
 Generally, I think the problem is some conflict (or feature) with the Core compiler -- used to build icc vs the loaded gcc. In this case, our core compiler is gcc@4.8.5; our icc compilers are all built with that compiler. Three possible resolutions appear to be:
1. Exclude the test (patch above; as per discussion, this is not a desirable approach)
2. Use default GCC headers
3. Add `-we147` to CFLAGS . Can/should this be done on a per-package basis, or in the compiler definition?

A litte more detail:
1. While building up a SW stack, I ran into multiple cases of, "gcc@4.8.5 compiler is too old," which I fixed by adding `modules: [gcc/10.] to my `intel@2021.4.0` compiler definition. 
2. When I originally test-compiled CURL, outside of Spack, I ran into some errors that I appeared to fix by loading gcc/10, but in retrospect just setting CC, eg `CC=icc ./configure` would have done the trick.
3. From earlier discussions,  `-stdlib=libc++` has no apparent effect
4. `CC=icc ./configure` breaks when: any gcc/ module (v 6.x, 7.x, 8.x, 9.x, 10.x) is loaded, presumably when the `gcc` version does to match the Core compiler version (see resolution below)
5. `CC=icc ./configure` succeeds when:
    - no `gcc/` module is loaded
    - Judging from various comments, when the loaded gcc version matches the Core compiler version?
    _**- with any `gcc` module + `-we147` is added to `CFLAGS`**_

Thoughts and questions:
1. Generally, I think some version of the 3rd solution (add `-we147` to CFLAGS) is best. Can this be done per-package, or in the compiler config?
2. Intel says icc, etc. only support gcc v<=9.x, so maybe configuring `intel@2021.4.0` with to use `gcc/9.` is a good idea?
3. Generally, any recommendations about how to configure the Intel compilers would be much appreciated.

**Comment by scheibelp** [comment]
Regarding 

> 1. Generally, I think some version of the 3rd solution (add -we147 to CFLAGS) is best. Can this be done per-package, or in the compiler config?

You can do either, although I prefer it be done in the package (in that case other users could benefit from it). My understanding from reading through the threads is that gcc reports an error for this issue where icc by default just gives a warning.

(that does not address [2, 3] from https://github.com/spack/spack/issues/27709#issuecomment-985837960)

**Comment by markyoder** [comment]
Clarifying a bit -- is it possible to add `CFLAGS` to an individual package in `packages.yaml` (or equivalently `spack.yaml, packages:` section?
