### ISSUE TITLE
Trouble building go via Spack (but probably not Spack's problem).

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#2770]
FWIW, I'm having trouble building go.  I think its either a local problem or a go problem and have [an open issue](https://github.com/golang/go/issues/18551) with the Go folks about it.

If anything relevant comes of it, I'll follow up.

**Comment by hartzell** [comment]
As an update, I don't have any trouble building the 1.8rc1 candidate on my 144-core box (as long as I bump `ulimit -u 8192`).

**Comment by hartzell** [comment]
Building newer releases (1.7.5 works, as does the 1.8 release candidate) works as long as you raise the process limit.

**Comment by hartzell** [comment]
This heisenbug has resurfaced.  I've been digging into it in [the issue in the go repo](https://github.com/golang/go/issues/18551).

The test that sometimes fails involves "signal trickery".  I asked a question in my [most recent comment](https://github.com/golang/go/issues/18551#issuecomment-278090086) about whether there might be something that Spack is doing that is "provoking" it.  Thought I'd ask the same question here.

**Comment by adamjstewart** [comment]
Whenever I run into a heisenbug, it is almost always due to the fact that the Makefile is poorly written and cannot be executed in parallel. Have you tried `spack install -j1`? If that solves it, you can add `parallel=False` to the package.

**Comment by hartzell** [comment]
Their build is driven by a bash script.  Given Go (and it's authors') focus on concurrency and *etc* I'd be surprised if they snafu'ed something like that.  On the other hand....

I'll add that flag to the build and see what it does.  Thanks for thinking on it.

**Comment by hartzell** [comment]
Nope, adding `-j1` did not fix it.  Sigh...

**Comment by hartzell** [comment]
I've just reproduced the problem with a shell script driving the compilation (no Spack in sight).

FWIW: I can run the script from a shell prompt and it works, but when run it via a Jenkins job (which ssh's from the master into the slave) it fails.
