### ISSUE TITLE
mpich missing dependency?

### ISSUE THREAD

**Issue by vsoch** [LLNL/spack#27741]
### Steps to reproduce

```console
spack install mpich
```

### Error message

```console
==> Error: ProcessError: Command exited with status 1:
    '/tmp/root/spack-stage/spack-stage-mpich-3.1.4-abkbaa6oom6kh7y4dyw4exmsgrn7bwrj/spack-src/configure' '--prefix=/opt/spack/opt/spack/linux-ubuntu20.04-x86_64_v4/gcc-9.3.0/mpich-3.1.4-abkbaa6oom6kh7y4dyw4exmsgrn7bwrj' '--disable-silent-rules' '--enable-shared' '--with-hwloc-prefix=embedded' '--with-pm=hydra' '--enable-romio' '--without-ibverbs' '--enable-wrapper-rpath=yes' '--with-slurm=no' '--with-pmi=simple' '--with-device=ch3:nemesis:mxm' '--enable-libxml2'

1 error found in build log:
     806    checking for knem_io.h... no
     807    configure: RUNNING CONFIGURE FOR ch3:nemesis:mxm
     808    checking mxm/api/mxm_api.h usability... no
     809    checking mxm/api/mxm_api.h presence... no
     810    checking for mxm/api/mxm_api.h... no
     811    checking for mxm_get_version in -lmxm... no
  >> 812    configure: error: 'mxm/api/mxm_api.h or libmxm library not found. D
            id you specify --with-mxm= or --with-mxm-include= or --with-mxm-lib
            =?'

See build log for details:
  /tmp/root/spack-stage/spack-stage-mpich-3.1.4-abkbaa6oom6kh7y4dyw4exmsgrn7bwrj/spack-build-out.txt
```

You can see the error under any of the green steps here, bottom of "Run Analysis" https://github.com/buildsi/spack-splices/runs/4377568535?check_suite_focus=true

### Information on your system

GitHub workflows in a container. To reproduce you can follow these instructions to build (and run the container with the PWD bound as shown)

https://github.com/buildsi/spack-splices#build-the-container

And then in the container:

```
$ spack python splice.py splice hdf5@1.10.1 mpich openmpi --outfile pkg-hdf5-1.10.1-splice-mpich-with-openmpi-experiment-openmpi_mpich-splices.json --experiment openmpi_mpich ompi_info
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by raffenet** [comment]
@vsoch did 067800bc315125caa86037bbb82e45bab71a9896 fix this issue?

**Comment by vsoch** [comment]
I was building en-masse and just skipped using this library, so I am not sure! I know y'all have a ton of issues so I'm good with closing this - I can re-open if I stumble on it again.
