### ISSUE TITLE
fetching nlohmann-json-3.10.4 failed 

### ISSUE THREAD

**Issue by Billae** [LLNL/spack#27819]
Hello,

I'm trying to install paraview@master and it needs nlohmann-json. Spack tried to fetch it but received this error:
```
==> Installing nlohmann-json-3.10.4-we7v7j3d756cdkftron4ztkrdmpcianf
==> No binary for nlohmann-json-3.10.4-we7v7j3d756cdkftron4ztkrdmpcianf found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/11/1155fd1a83049767360e9a120c43c578145db3204d2b309eba49fbbedd0f4ed3.tar.gz
==> Error: timeout: The read operation timed out

/home/billae/install_08.09.21/spackinstaller/spack/lib/spack/spack/package.py:1386, in do_fetch:
       1383
       1384        self.stage.create()
       1385        err_msg = None if not self.manual_download else self.download_instr
  >>   1386        start_time = time.time()
       1387        self.stage.fetch(mirror_only, err_msg=err_msg)
       1388        self._fetch_time = time.time() - start_time

```

I try to fetch manually this package but the checksum seems not good:
```
 spack fetch  nlohmann-json@3.10.4
==> Error: sha256 checksum failed for /tmp/billae/spack-stage/spack-stage-nlohmann-json-3.10.4-we7v7j3d756cdkftron4ztkrdmpcianf/v3.10.4.tar.gz
Expected 1155fd1a83049767360e9a120c43c578145db3204d2b309eba49fbbedd0f4ed3 but got ffcbf31d9af729155f8b2f7a869030aba406373227a558c2a7055a0ee87fdfd5
```

However when I checksum this version, the spack recipe is right:
```
 spack checksum nlohmann-json@3.10.4
==> Found 1 version of nlohmann-json:
  
  3.10.4  https://github.com/nlohmann/json/archive/v3.10.4.tar.gz

==> Fetching https://github.com/nlohmann/json/archive/v3.10.4.tar.gz

    version('3.10.4', sha256='1155fd1a83049767360e9a120c43c578145db3204d2b309eba49fbbedd0f4ed3')
```

I am not sure which checksum is the righ one,
@ax3l have you an idea ?

Regards, 
Eloïse

**Comment by scheibelp** [comment]
Can you retry this after `spack clean -d`?

**Comment by Billae** [comment]
It works ! Thanks.
Can you explain to me why cleaning the cache directories changes ? I had never installed this package before so it should not have any impact ? :o

**Comment by scheibelp** [comment]
My guess is that a temporary network failure resulted in a failed download, which was then cached. If you reran an install command it would have then pulled from the cache and failed on the checksum; if this was the first command you ran, then my guess is likely wrong (I'd need to see any commands/errors you got before the output you included to understand better). 

I'm inclined to leave this open to remind myself I should investigate whether Spack could just automatically remove such resources from the cache.

**Comment by Billae** [comment]
Thanks for answer.
I let you close the issue when you need it =)

Have a good day 
Eloïse

**Comment by ax3l** [comment]
Thanks for the solution @scheibelp.

> I'm inclined to leave this open to remind myself I should investigate whether Spack could just automatically remove such resources from the cache.

Feel free to re-open if you don't want to open a new meta-issue for this.
