### ISSUE TITLE
Monterey misdetected as Big Sur

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#27891]
### Steps to reproduce

```
$ spack arch
darwin-bigsur-skylake
eschnett@redshift:~/Cactus (14:09:06)
$ uname -a
Darwin redshift.local 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64 i386 MacBookPro16,1 Darwin
eschnett@redshift:~/Cactus (14:09:09)
$ spack --version
0.17.0-463-361a2ccdf6
```

### Error message

I am using macOS Monterey. Spack used to detect this correctly. Currently (after a `git pull`), my OS is detected as Big Sur (see above).

### Information on your system

```
$ spack debug report
* **Spack:** 0.17.0-463-361a2ccdf6
* **Python:** 3.8.8
* **Platform:** darwin-bigsur-skylake
* **Concretizer:** clingo
```

The platform is wrong; I'm on Monterey.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by eschnett** [comment]
I found the reason:

Depending on my `PATH` when running `source ./share/spack/setup-env.sh`, Spack either picks `/Users/eschnett/opt/anaconda3/bin/python3` (bad) or `/usr/bin/python3` (good) as Python interpreter. One of them knows about Monterey, the other doesn't.

The unexpected behaviour is that sourcing `./share/spack/setup-env.sh` has a memory. Once it's picked a Python, it remembers that choice, even if I change `PATH` in between:

```sh
# Set up Spack
source ./share/spack/setup-env.sh
# Oh no, it's the wrong Python! Let's correct PATH...
export PATH=$HOME/bin:/usr/bin:/bin:/usr/sbin:/sbin
# ... and set up Spack again:
source ./share/spack/setup-env.sh
```

That doesn't work; the second call to `setup-env.sh` keeps using the previously found Python, even though it's not in the PATH any more. I did not expect this.

I assume the reason is that Spack uses the same environment variable `SPACK_PYTHON` to let people define their Python preference, and to remember the result of its own search. That means, the second time around, it doesn't remember my preference (which was "go look in `PATH` for a good Python").

**Comment by alalazo** [comment]
This seems to be due to a bad interpreter. For issues with the current behavior of `SPACK_PYTHON` it would be better to open a separate discussion.
