### ISSUE TITLE
pflotran requires hdf5 version 1.8.12

### ISSUE THREAD

**Issue by sarich** [LLNL/spack#2797]
currently the pflotran package.py requires hdf5 1.8.12, is there a reason this version is necessary? mira has 1.8.14 that I would like to use.

```
depends_on('hdf5@1.8.12+mpi+fortran')
```

**Comment by tgamblin** [comment]
@BarrySmith

**Comment by citibeth** [comment]
I would give it a try and see what happens...

**Comment by tgamblin** [comment]
@sarich: see also #2772

**Comment by becker33** [comment]
Closed via #2875
