### ISSUE TITLE
Installation issue: llvm

### ISSUE THREAD

**Issue by stephenmsachs** [LLNL/spack#27992]
### Steps to reproduce the issue

I am having trouble building LLVM. The build exits with error:
```
/tmp/ec2-user/spack-stage/spack-stage-llvm-12.0.1-5bglsict2wvmumim44wjhkwk3mextud5/spack-src/lldb/source/Plugins/Process/Linux/NativeRegisterContextLinux_arm64.h:121:26: error: field 'm_sve_header' has incomplete type 'lldb_private::process_linux::user_sve_header'
        struct user_sve_header m_sve_header;
```

Digging through LLVM code revealed that `user_sve_header` is expected to be defined in `<asm/ptrace.h>`. This has only been added to kernel 4.15+ (https://github.com/torvalds/linux/commit/43d4da2c45b2f5d62f8a79ff7c6f95089bb24656). However, Amazon Linux2 runs kernel 4.14. 

The obvious solution would be to update the kernel, but then the question arises why we need the kernel to support SVE on a non-SVE CPU only to install LLVM. I have not been able to find an option to disable SVE on LLVM while still enabling aarch64.  I was hoping one of the authors would know what's thebest way of dealing with this.

Steps to reproduce is `spack install llvm` on a Graviton2 based AWS instance running Amazon Linux2.

Tagging Maintainers @trws @haampie.

### Information on your system

```
* **Spack:** 0.17.0
* **Python:** 3.7.10
* **Platform:** linux-amzn2-graviton2
* **Concretizer:** clingo
```

`uname -a`
```
Linux ip-172-31-5-19 4.14.256-197.484.amzn2.aarch64 #1 SMP Tue Nov 30 00:18:02 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by trws** [comment]
This is probably more of an upstream question.  As a stopgap, I have a feeling an older version would build fine, but no real answer for you as to why this is required.  The best guess I have is that since LLVM is not fine-grained with its architecture support, turning on aarch64 means it tries to build support for all of the aarch64 variants, possibly using constants or macros from that file.

A quick search makes me think lldb is actually what's failing as well, have you tried disabling the lldb variant?

**Comment by stephenmsachs** [comment]
Yes, it works without lldb. Thanks for the pointer.

I guess if there is no other options we can close this issue. Seem like it is a shortcoming of llvm itself.
