### ISSUE TITLE
vtk/package.py patch fails

### ISSUE THREAD

**Issue by KineticTheory** [LLNL/spack#2802]
I'm attempting to install vtk-7.0.0.  The `patch('gcc.patch')` step always fails - even when run by hand:

```
% patch -s -p 1 -i $SPACK_ROOT/var/spack/repos/builtin/packages/vtk/gcc.patch
1 out of 1 hunk FAILED -- saving rejects to file CMake/GenerateExportHeader.cmake.rej

% more CMake/GenerateExportHeader.cmake.rej 
--- CMake/GenerateExportHeader.cmake
+++ CMake/GenerateExportHeader.cmake
@@ -166,6 +166,7 @@
     execute_process(COMMAND ${CMAKE_C_COMPILER} --version
       OUTPUT_VARIABLE _gcc_version_info
       ERROR_VARIABLE _gcc_version_info)
+    string (REPLACE ";" "" _gcc_version_info "${_gcc_version_info}")
     string(REGEX MATCH "[345]\\.[0-9]\\.[0-9]"
       _gcc_version "${_gcc_version_info}")
     # gcc on mac just reports: "gcc (GCC) 3.3 20030304 ..." without the
```

Commenting out the `patch` command from `vtk/package.py` appears to fix the problem.  I'm assuming the patch is needed for some platform or vtk version, but not for gcc@5.3.0 on RHEL6. Maybe someone more knowledgeable can provide some feedback and a bug fix.

**Comment by adamjstewart** [comment]
If the patch doesn't work, you'll have to restrict it to a particular version range. For example, if the patch only applies to versions 6.0.0 and below, it would look like:
```python 
patch('gcc.patch', when='@:6.0.0')
```
