### ISSUE TITLE
Installation issue: py-pygtk is unsatisfiable

### ISSUE THREAD

**Issue by mdorier** [LLNL/spack#28022]
### Steps to reproduce the issue

```console
$ spack spec -I py-pygtk
Input spec
--------------------------------
 -   py-pygtk

Concretized
--------------------------------
==> Error: py-pygtk is unsatisfiable, errors are:
  no version satisfies the given constraints

    To see full clingo unsat cores, re-run with `spack --show-cores=full`
    For full, subset-minimal unsat cores, re-run with `spack --show-cores=minimized
    Warning: This may take (up to) hours for some specs
```

### Information on your system

* **Spack:** 0.17.0-516-5319b6e3b1
* **Python:** 3.9.5
* **Platform:** linux-ubuntu21.04-sandybridge
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
Running:
```
$ time spack --show-cores=minimized spec py-pygtk
Input spec
--------------------------------
py-pygtk

Concretized
--------------------------------
==> Error: py-pygtk is unsatisfiable, conflicts are:
  condition(3615)
  condition(3621)
  condition(915)
  dependency_condition(3615,"py-pygtk","atk")
  dependency_condition(3621,"py-pygtk","gtkplus")
  dependency_type(3615,"build")
  dependency_type(3621,"build")
  dependency_type(915,"build")
  imposed_constraint(3615,"version_satisfies","atk",":2.20.0")
  imposed_constraint(915,"version_satisfies","atk","2.35.1:")
  no version satisfies the given constraints
  root("py-pygtk")

real	0m30,255s
user	0m29,943s
sys	0m0,293s
```
it seems that there's a request to have `atk` >= 2.35.1 and < 2.20.0 at the same time (coming from two different directives).

**Comment by alalazo** [comment]
The request for `atk` < 2.20.0 comes from `py-pygtk` itself, while `gtkplus` needs `atk` > 2.35.1 unconditionally.

**Comment by adamjstewart** [comment]
`py-pygtk` uses Python 2 which has reached EOL almost 2 years ago. `py-pygtk` will be deprecated in #28003 and removed after the next stable Spack release. You should use `py-pygobject` instead.

**Comment by mdorier** [comment]
Thanks, I'll close this issue then.
