### ISSUE TITLE
Cannot depend on virtual package and non-virtual package

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#2807]
If A depends on B and C, and B depends on a virtual package while C depends on a specific implementation of that package, Spack will fail during concretization. This example was discovered with `py-yt`. `py-yt` depends on `py-matplotlib` which depends on `py-pillow`. `py-yt` also depends on `py-scikit-image`, which depends on `pil`. Even though `py-pillow` is the default implementation of `pil`, Spack crashes with the following message:
```
==> Error: Cannot depend on 'py-pillow^binutils@2.26:^bison^bzip2@1.0.6%gcc@6.1.0 arch=linux-centos6-x86_64^flex^gettext@0.19:^help2man^m4^ncurses@6.0%gcc@6.1.0 arch=linux-centos6-x86_64^openssl@1.0.2j%gcc@6.1.0 arch=linux-centos6-x86_64^py-setuptools@25.2.0%gcc@6.1.0 arch=linux-centos6-x86_64^python@2.7.13%gcc@6.1.0+tk~ucs4 arch=linux-centos6-x86_64^readline@6.3%gcc@6.1.0 arch=linux-centos6-x86_64^sqlite@3.8.5%gcc@6.1.0 arch=linux-centos6-x86_64^tcl^tk@8.3:^zlib@1.2.10%gcc@6.1.0+pic arch=linux-centos6-x86_64' twice
```

**Comment by citibeth** [comment]
The dependency of `py-matplotlib` -> `py-pillow` was added in #1041, before `pil` existed as a virtual dependency: https://github.com/LLNL/spack/pull/1041/files    I would fix the immediate problem here by making `py-matplotlib` depend on `pil`.  I think that's the correct thing here anyway.

Stepping back... I'm not sure if this situation should ever "legitimately" come up.  I suppose it can... in that case, we would want `py-matplotlib` to tell the concretizer that it depends on `pil`, which should be fulfilled with `py-pillow`.  Something like `depends_on('pil^py-pillow')`.

**Comment by adamjstewart** [comment]
Yep, switching `py-matplotlib` to depend on `pil` for now. But we should still probably fix this. I don't see why one package can't depend on a virtual dependency and another on a specific implementation.
