### ISSUE TITLE
"spack load" set additional environment variables

### ISSUE THREAD

**Issue by liuyangzhuan** [LLNL/spack#28116]
### Summary

Is there a way to set package-specific environment variables when doing "spack load". More specifically, 
after I do 
spack install gptune
spack load gptune
I would like an additional environment variable "GPTUNE_INSTALL_PATH" to be set automatically. Is this a currently supported feature or not?

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
I think you want to add the following to the `package.py`:
```python
def setup_run_environment(self, spec):
    env.set('GPTUNE_INSTALL_PATH', self.prefix)
```
If this works, can you open a PR?

**Comment by liuyangzhuan** [comment]
Thanks! It works well. I will commit the change accordingly.
