### ISSUE TITLE
intel-oneapi-mkl needs improvements

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#28130]
### Summary

1. It has variants `cluster`, `shared`, `ilp64` which do not influence the contents of the installation, this can lead to many redundant copies of a 6GB+ installation :(.
  
   These variants should be removed, and replaced with query parameters (https://spack-tutorial.readthedocs.io/en/sc20/tutorial_advanced_packaging.html#extra-query-parameters) I can't find the actual docs for this feature.

2. Currently .libs returns system libraries, even when +shared. This should never happen.

Generally I think Spack is too high level to support static linking, cause it doesn't know dependencies. Why not use pkgconfig file or whatever you have. They know the actual linker flags.

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by rscohn2** [comment]
> These variants should be removed, and replaced with query parameters

The spack developers are working on a different solution: https://github.com/spack/seps/pull/2. If you think there is a better way to handle it, you can discuss it there.

> Currently .libs returns system libraries, even when +shared. This should never happen.

I don't understand what you mean. libpthread, libm, libdl are non-default libraries that are required to link. How should the package that depends on blas know that the requested configuration needs the libraries?

**Comment by haampie** [comment]
> The spack developers are working on a different solution: spack/seps#2. If you think there is a better way to handle it, you can discuss it there.

Okay, great! I wasn't aware.

> libpthread, libm, libdl are non-default libraries that are required to link

Right, I expected the shared libs to have libm/libpthread/libdl in dt_needed, but they simply have missing symbols...

I think it's a matter of expectations... In my view `.libs` means "the libraries provided by this package" not "the libraries required to link to this package". So I expect all libraries to be part of the prefix, not on the system.

I still believe (but maybe i'm a minority here) it's better for Spack not to provide link instructions, since Spack is too high level, in particular when it comes to static libs. People should just rely on pkgconfig/cmake config files, which MKL already provides anyways.

**Comment by haampie** [comment]
Just out of curiosity, why is it that MKL's shared libs don't specify libm/libpthread/libgomp etc in DT_NEEDED?

**Comment by rscohn2** [comment]
Is there an libiomp for using the intel compilers omp? I have not looked at
this in a while

**Comment by haampie** [comment]
Closing since I wrongly expected MKL shared libs to list their needed libs in the elf files.
