### ISSUE TITLE
Build error: kokkos-kernels +openmp+cuda arch=zen2

### ISSUE THREAD

**Issue by jrobcary** [LLNL/spack#28175]
### Steps to reproduce

The basic command is
```
spack install trilinos@13.2.0+cuda+hdf5~mpi+openmp cuda_arch=72 ^python~pyexpat ^kokkos-nvcc-wrapper~mpi
```

but attached is the script used to run that, as it sets other variables.  .txt was added to all file names so that github would accept them.  I also attach the build-out.txt file, which contains the full list of errors.

An example error is

/home/bilder/contrib/gcc-9.4.0/lib/gcc/x86_64-pc-linux-gnu/9.4.0/include/avx512fintrin.h(9146): error: identifier "__builtin_ia32_rndscaless_round" is undefined

which may indicate that trilinos is trying to include avx512 instructions that don't exist or are not implemented?

[runspack.sh.txt](https://github.com/spack/spack/files/7789132/runspack.sh.txt)
[setupspack.sh.txt](https://github.com/spack/spack/files/7789133/setupspack.sh.txt)
[spack.yaml.txt](https://github.com/spack/spack/files/7789140/spack.yaml.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7789155/spack-build-out.txt)
.

### Error message

```
cd /home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-build-qqmz7rt/packages/kokkos-kernels/src && /home/research/cary/opt/linux-rocky8-zen2/gcc-9.4.0/kokkos-nvcc-wrapper-3.2.00-4n5jp35hi6jheb7giutnfl5rieynvt74/bin/nvcc_wrapper -Dkokkoskernels_EXPORTS -I/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-build-qqmz7rt -I/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-build-qqmz7rt/packages/kokkos-kernels/src -I/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-src/packages/kokkos-kernels/src -I/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-src/packages/kokkos-kernels/src/impl -I/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-build-qqmz7rt/packages/kokkos-kernels/src/impl -I/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-src/packages/kokkos-kernels/src/impl/tpls -I/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-src/packages/kokkos-kernels/src/blas -I/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-src/packages/kokkos-kernels/src/blas/impl -I/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-src/packages/kokkos-kernels/src/sparse -I/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-src/packages/kokkos-kernels/src/sparse/impl -I/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-src/packages/kokkos-kernels/src/graph -I/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-src/packages/kokkos-kernels/src/graph/impl -I/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-src/packages/kokkos-kernels/src/batched -I/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-src/packages/kokkos-kernels/src/common -I/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-build-qqmz7rt/packages/kokkos/algorithms/src -I/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-src/packages/kokkos/algorithms/src -I/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-build-qqmz7rt/packages/kokkos/containers/src -I/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-src/packages/kokkos/containers/src -I/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-build-qqmz7rt/packages/kokkos/core/src -I/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-src/packages/kokkos/core/src -I/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-build-qqmz7rt/packages/kokkos -I/home/research/cary/opt/linux-rocky8-zen2/gcc-9.4.0/hwloc-2.6.0-ois5nhxvr7jurardayfyrrfmjs3y3cfj/include -I/home/research/cary/opt/linux-rocky8-zen2/gcc-9.4.0/amdlibflame-3.1-pzioontfzjlj6mysxmqosynzdzdrdau4/include -I/home/research/cary/opt/linux-rocky8-zen2/gcc-9.4.0/amdblis-3.1-s7uqgliwjsadqlbqcvsji4owtcqugmot/include -march=znver2 -mtune=znver2  -Xcompiler -fopenmp -expt-extended-lambda -Wext-lambda-captures-this -arch=sm_72  -O2 -g -DNDEBUG -fPIC -std=c++14 -MD -MT packages/kokkos-kernels/src/CMakeFiles/kokkoskernels.dir/impl/generated_specializations_cpp/trmm/Blas3_trmm_eti_DOUBLE_LAYOUTLEFT_EXECSPACE_CUDA_MEMSPACE_CUDASPACE.cpp.o -MF CMakeFiles/kokkoskernels.dir/impl/generated_specializations_cpp/trmm/Blas3_trmm_eti_DOUBLE_LAYOUTLEFT_EXECSPACE_CUDA_MEMSPACE_CUDASPACE.cpp.o.d -o CMakeFiles/kokkoskernels.dir/impl/generated_specializations_cpp/trmm/Blas3_trmm_eti_DOUBLE_LAYOUTLEFT_EXECSPACE_CUDA_MEMSPACE_CUDASPACE.cpp.o -c /home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-build-qqmz7rt/packages/kokkos-kernels/src/impl/generated_specializations_cpp/trmm/Blas3_trmm_eti_DOUBLE_LAYOUTLEFT_EXECSPACE_CUDA_MEMSPACE_CUDASPACE.cpp
/home/bilder/contrib/gcc-9.4.0/lib/gcc/x86_64-pc-linux-gnu/9.4.0/include/avx512fintrin.h(9146): error: identifier "__builtin_ia32_rndscaless_round" is undefined

/home/bilder/contrib/gcc-9.4.0/lib/gcc/x86_64-pc-linux-gnu/9.4.0/include/avx512fintrin.h(9155): error: identifier "__builtin_ia32_rndscalesd_round" is undefined

/home/bilder/contrib/gcc-9.4.0/lib/gcc/x86_64-pc-linux-gnu/9.4.0/include/avx512fintrin.h(14797): error: identifier "__builtin_ia32_rndscaless_round" is undefined

/home/bilder/contrib/gcc-9.4.0/lib/gcc/x86_64-pc-linux-gnu/9.4.0/include/avx512fintrin.h(14806): error: identifier "__builtin_ia32_rndscalesd_round" is undefined

/home/bilder/contrib/gcc-9.4.0/lib/gcc/x86_64-pc-linux-gnu/9.4.0/include/avx512dqintrin.h(1365): error: identifier "__builtin_ia32_fpclassss" is undefined

/home/bilder/contrib/gcc-9.4.0/lib/gcc/x86_64-pc-linux-gnu/9.4.0/include/avx512dqintrin.h(1372): error: identifier "__builtin_ia32_fpclasssd" is undefined

6 errors detected in the compilation of "/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-build-qqmz7rt/packages/kokkos-kernels/src/impl/generated_specializations_cpp/trsm/Blas3_trsm_eti_DOUBLE_LAYOUTLEFT_EXECSPACE_CUDA_MEMSPACE_CUDASPACE.cpp".
make[2]: *** [packages/kokkos-kernels/src/CMakeFiles/kokkoskernels.dir/build.make:1731: packages/kokkos-kernels/src/CMakeFiles/kokkoskernels.dir/impl/generated_specializations_cpp/trsm/Blas3_trsm_eti_DOUBLE_LAYOUTLEFT_EXECSPACE_CUDA_MEMSPACE_CUDASPACE.cpp.o] Error 2
```

### Information on your system

$ spack debug report
* **Spack:** 0.17.1-668-e0d8964453
* **Python:** 3.6.8
* **Platform:** linux-rocky8-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by jrobcary** [comment]
@sethrj
More experiments:

Adding +float gives the same error.

Changing version to 'develop' gives the same error.

**Comment by jrobcary** [comment]
Here is the env file for the develop build.

[spack-build-env.txt](https://github.com/spack/spack/files/7789281/spack-build-env.txt)

**Comment by sethrj** [comment]
OK this looks like an error inside the Kokkos Kernels embedded in Trilinos, possibly a conflict between NVCC and the AVX instructions generated by `-DKokkos_ARCH_ZEN2=ON`. @jrobcary can you try installing kokkos kernels itself to see if this fails:
```
spack install kokkos-kernels +cuda+openmp cuda_arch=72 ^kokkos-nvcc-wrapper~mpi
```

@brian-kelley Have you seen conflicts between CPU specializations and CUDA kernel instantiations? This looks like it's at least using a pretty new GCC (9.4) and very new CUDA (11.5).

**Comment by jrobcary** [comment]
I removed "+hdf5", I assume a typo.  Then I get one arch warning and the same errors:

```
     570    nvcc warning : The 'compute_35', 'compute_37', 'compute_50', 'sm_35
            ', 'sm_37' and 'sm_50' architectures are deprecated, and may be rem
            oved in a future release (Use -Wno-deprecated-gpu-targets to suppre
            ss warning).
  >> 571    /home/bilder/contrib/gcc-9.4.0/lib/gcc/x86_64-pc-linux-gnu/9.4.0/in
            clude/avx512fintrin.h(9146): error: identifier "__builtin_ia32_rnds
            caless_round" is undefined
     572
  >> 573    /home/bilder/contrib/gcc-9.4.0/lib/gcc/x86_64-pc-linux-gnu/9.4.0/in
            clude/avx512fintrin.h(9146): error: identifier "__builtin_ia32_rnds
            caless_round" is undefined
```

**Comment by sethrj** [comment]
OK, that's good news and certainly will make debugging easier. (I removed the `+hdf5` typo.) I'm updating the title to reflect the more specific issue.

@jrobcary You can probably get it to work by disabling processor-specific micro-optimizations, i.e. explicitly specifying `arch=x86_64` as part of the spec. Could you try that? Can you also post the full `spack-build-out.txt` from the kokkos kernels build?

 @brian-kelley @lucbv @srajama1 Should we make this an issue in https://github.com/kokkos/kokkos-kernels/issues ? Or is this an implicit conflict we should add to the spack kokkos/trilinos recipes?

**Comment by jrobcary** [comment]
[spack-build-out.txt](https://github.com/spack/spack/files/7790187/spack-build-out.txt)

The above is the spack-build-out from the failed kokkos-kernels build.

Adding arch=x86_64 to the kokkos-kernels spec unleashed a whole bunch of building, all the way down through cmake, but ultimately it succeeded.  LMK if you need anything else.  For now I will just use arch=x86_64.  Thx..

**Comment by sethrj** [comment]
OK cool, that's what I expected -- I don't think there's a way for just one package in a spec to be "un-optimized" at present. But I'm glad it worked! You can consider adding it to your packages.yaml or spack.yaml . You may see a slight performance hit in some bits of CPU code, but since you're targeting CUDA/GPU I doubt it's worth worrying about.

**Comment by jrobcary** [comment]
Thx.  I am using an environment, hence spack.yaml.  In what section would I put arch=x86_64?  (I did not see this in any yaml file under spack/etc/spack/defaults/.)

**Comment by jrobcary** [comment]
So after arch= change for trilinos, 

```
spack install trilinos@13.2.0+cuda+hdf5~mpi+openmp arch=x86_64 cuda_arch=72 ^python~pyexpat ^kokkos-nvcc-wrapper~mpi
```

I get a failure of hwloc:

```
1 error found in build log:
     242    **** pciaccess configuration
     243    checking for PCIACCESS... no
     244    checking for pciaccess.h... no
     245    **** end of pciaccess configuration
     246    configure: WARNING: Specified --enable-pci switch, but could not
     247    configure: WARNING: find appropriate support
  >> 248    configure: error: Cannot continue
```

and then a bunch of mysterious messages like

```
==> Error: [/home/research/cary/projects/txcspack/vsimall/.spack-env/._view/lt6nup42tealynxecufqrqsq45vmuzqh] Package conflict detected:
   (Linked) libxml2@2.9.12%gcc@9.4.0~python arch=linux-rocky8-x86_64/2k4w63w
(Specified) libxml2@2.9.12%gcc@9.4.0~python arch=linux-rocky8-x86_64/2k4w63w
```
and

```
==> Error: [/home/research/cary/projects/txcspack/vsimall/.spack-env/._view/lt6nup42tealynxecufqrqsq45vmuzqh] Package conflict detected:
   (Linked) libxml2@2.9.12%gcc@9.4.0~python arch=linux-rocky8-x86_64/2k4w63w
(Specified) libxml2@2.9.12%gcc@9.4.0~python arch=linux-rocky8-zen2/gujzs7r
```

This is where the nuclear option seems appropriate, but it would be nice to know what is the minimal set of files to blow away to get things working.

**Comment by sethrj** [comment]
Can you post your environment file? You probably want to have `concretization: together`. Looks like you're getting conflicts between the different arch types.

**Comment by sethrj** [comment]
> Thx. I am using an environment, hence spack.yaml. In what section would I put arch=x86_64? (I did not see this in any yaml file under spack/etc/spack/defaults/.)

You're adding it to the embedded `packages.yaml` essentially, so:
```yaml
spack:
  packages:
    all:
      target: [x86_64]
```

**Comment by jrobcary** [comment]
Which is "the environment file"?  I see lots of individual environment files:

```
cary@vcloud/.../txcspack$ find /home/research/cary/spack/stage -name '*env.txt'
/home/research/cary/spack/stage/spack-stage-trilinos-develop-ymura5ppa4bruolibmmiuqgpco4rfvez/spack-build-env.txt
/home/research/cary/spack/stage/spack-stage-hwloc-2.6.0-ygqpwrbqp3kz37sqvuxesugyi4xzjog3/spack-build-env.txt
/home/research/cary/spack/stage/spack-stage-trilinos-develop-xzi7cw3455eix7bqmo47azlfp5ulfhzm/spack-build-env.txt
/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-qqmz7rt72db76rkdysb3lx6y3cimzkcg/spack-build-env.txt
/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-zujbis67r7gpx22rwkrsagfnvujs4m3p/spack-build-env.txt
/home/research/cary/spack/stage/spack-stage-trilinos-13.2.0-lrhv42xzbqtwddjlpqedd6s4tawwlxpp/spack-build-env.txt
/home/research/cary/spack/stage/spack-stage-kokkos-kernels-3.4.01-7a47excoznofy3tbwitzchbr6eyfwzkf/spack-build-env.txt
```

**Comment by sethrj** [comment]
@jrobcary i mean the Spack environment definition, the yaml file.

**Comment by jrobcary** [comment]
[spack.yaml.txt](https://github.com/spack/spack/files/7790668/spack.yaml.txt)

so I am guess this one.

**Comment by sethrj** [comment]
Yes, you'll note that it starts with `This is a Spack Environment file`. It's different from the `-env.txt` files generated while building, which echo the system environment variables used while building spack.

I see in your environment that you have multiple distinct Trilinos specs but you still have `view: true`. It's the underlying issue causing #28168 and I guess it's interfering with this build?  Maybe we should move the environment-related discussion there and leave this issue for the kokkos-kernels failure.

@becker33 I think you're the expert on environment views: shouldn't `view: true` be disallowed when you've got multiple environments? Or maybe this spec was generated by having the environment active and allowing multiple consecutive `spack install` commands? It seems very odd.
```
  # add package specs to the `specs` list
  specs: [qt+opengl
    trilinos@develop+cuda+hdf5~mpi+openmp cuda_arch=72 ^kokkos-nvcc-wrapper~mpi ^python~pyexpat
    openssl
    trilinos@13.2.0+cuda+hdf5~mpi+openmp cuda_arch=72 ^kokkos-nvcc-wrapper~mpi ^python~pyexpat
    trilinos@13.2.0+cuda+float+hdf5~mpi+openmp cuda_arch=72 ^kokkos-nvcc-wrapper~mpi ^python~pyexpat
    kokkos-kernels+cuda+openmp cuda_arch=72 ^kokkos-nvcc-wrapper~mpi
    kokkos-kernels+cuda+openmp cuda_arch=72 arch=linux-None-x86_64 ^kokkos-nvcc-wrapper~mpi
    trilinos@13.2.0+cuda+hdf5~mpi+openmp cuda_arch=72 arch=linux-None-x86_64 ^kokkos-nvcc-wrapper~mpi ^python~pyexpat]
```

**Comment by jrobcary** [comment]
Yes, this was not put there by me.  I was hoping that my "environment" would be something that does not change unless I explicitly request that.  However, running spack is changing it, adding to the specs, as I keep experimenting, trying to get stuff to build.  Not sure I put 'view' in there.  I don't recall doing that.

Ideally, I would be able to specify things like packages to build, some compilers, etc, in a file that I can use across many systems, and one that I control.  Does spack have such a configuration file?

I am struggling to understand which files are under my control (I thought the environment file was one), and which files are where spack puts its data into.

**Comment by jrobcary** [comment]
I see now that I created the environment initially using

```
spack env create -d vsimall
```

and that created that directory with a default spack.yaml.  That file has in "view: true".    So if that is not a good thing to do, maybe the default creation should change?

I'll put some of these comments into the spack/slack.

**Comment by jrobcary** [comment]
Trilinos now building.  Thanks, @sethrj.
