### ISSUE TITLE
Installation issue: Python fails to build. System version of SQLite does not support loadable extensions on Big Sur

### ISSUE THREAD

**Issue by jrobcary** [LLNL/spack#28186]
### Steps to reproduce the issue

```
spack install python
```

### Information on your system

$ spack debug report
* **Spack:** 0.17.1-677-c2e1a12cdf
* **Python:** 3.8.9
* **Platform:** darwin-bigsur-skylake
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/7793006/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7793007/spack-build-out.txt)
@adamjstewart 
@skosukhin 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by jrobcary** [comment]
This hack fixes the issue

```
--- a/var/spack/repos/builtin/packages/python/package.py
+++ b/var/spack/repos/builtin/packages/python/package.py
@@ -500,7 +500,8 @@ def configure_args(self):
 
         # https://docs.python.org/3.8/library/sqlite3.html#f1
         if spec.satisfies('@3.2: +sqlite3'):
-            config_args.append('--enable-loadable-sqlite-extensions')
+            # config_args.append('--enable-loadable-sqlite-extensions')
+            pass
```

**Comment by adamjstewart** [comment]
That's odd, I also build Python on macOS and I've never hit this issue. Spack should be using Spack-installed sqlite, not the system version, so the OS shouldn't matter.

It looks like @Sinan81 added this feature in #14132, maybe he can comment. It's possible we just need to compile sqlite with a specific flag.

Note that you can also avoid this issue by building `python~sqlite3`, but that's probably undesirable.

**Comment by Sinan81** [comment]
python+sqlite3 builds just fine on centos7. Not sure why it fails for MacOS. if the error can be reproduced by someone else, and root cause is understood, I would entertain to create a new variant for loadable sqlite3 extensions.

**Comment by nilsvu** [comment]
I can reproduce this issue on macOS 12.0.1. I added `python` to a new environment and ran `spack find external` to pick up the system `sqlite`. Then `spack install --reuse` fails with `error: System version of SQLite does not support loadable extensions`.

`spack debug report`:
* **Spack:** 0.17.1-681-fc9bfe5317
* **Python:** 3.9.9
* **Platform:** darwin-monterey-skylake
* **Concretizer:** clingo

**Comment by adamjstewart** [comment]
@Sinan81 it sounds like we should add a variant to the `sqlite` package that enables this feature and add auto-detection of that variant. I'll submit a PR to do this.

**Comment by adamjstewart** [comment]
Can everyone test #28204? I haven't yet figured out auto-detection but you can just set `~dynamic_extensions` in your `packages.yaml` manually.

**Comment by nilsvu** [comment]
Looks good when I set `~dynamic_extensions` manually 👍
