### ISSUE TITLE
Installation issue: amdblis-3.1 fails on darwin-bigsur-x86_64 with malloc.h include error

### ISSUE THREAD

**Issue by jrobcary** [LLNL/spack#28189]
### Steps to reproduce the issue

```
spack install trilinos@13.2.0+hdf5~mpi+openmp
```

```
    134     ==> amdblis: Executing phase: 'build'
     135     ==> [2021-12-30-08:57:57.260078] 'make' '-j16'
  >> 136     bash: -c: line 0: syntax error near unexpected token `&'
     137     bash: -c: line 0: `/Users/cary/projects/txcspack/spack/lib/spack/e
             nv/clang/clang -v |&head -1 |grep -c 'AOCC.LLVM''
```

and later

```
     1618    In file included from aocl_dtl/aoclflist.c:16:
  >> 1619    aocl_dtl/aoclos.h:14:10: fatal error: 'malloc.h' file not found
     1620    #include "malloc.h"
     1621             ^~~~~~~~~~
     1622    1 error generated.
```

I do not understand why amd-anything is needed on MacOS, as Mac does not use AMD chips?

@sethrj  @amd-toolchain-support 

### Information on your system

$ spack debug report
* **Spack:** 0.17.1-677-c2e1a12cdf
* **Python:** 3.8.9
* **Platform:** darwin-bigsur-skylake
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/7793678/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7793679/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by sethrj** [comment]
This isn't a trilinos error, it's an error inside `amdblis`: probably a concretization error. Can you please post `spack spec -I trilinos@13.2.0+hdf5~mpi+openmp`?

It's possible you have something in your packages.yaml that's trying to use (e.g.) AMD blas implementation.

**Comment by jrobcary** [comment]
I got the build to work by setting the provider of blas to openblas.  I also had to turn off openmp on trilinos, as apple_clang does not support that.

I am still having this problem that when I change something in my environment file, I am not sure all of what I have to do to get that picked up.  Trilinos still picks up old configuration parameters.  E.g., if I erroneously configure with two cuda_arch's or with openmp using AppleClang, and it fails, then even when I change the spec at install, it keeps the old, bad cmake defines.  Ultimately, I have to blow away everything, spack and reclone, my environment area and re-check-out everything.

Since I do have this working, I will close this issue.  Thanks for your help.

**Comment by sethrj** [comment]
OK, so this is a weird concretization error I guess. I think the way you're using environments isn't quite how they're intended...

**Comment by jrobcary** [comment]
Thanks.  Can you say more?  Is there some documentation that tells me how to have a portable config file for my builds?  I'll do whatever that takes.

**Comment by sethrj** [comment]
It looks like you're trying to build trilinos with cuda and openmp on macos, which suggests you're not doing something that's truly portable.  Specifying different sets of software variants based on the hardware/OS you're compiling on is very difficult to do.  What you might do is define basic specs (trilinos, qt) and then on your different systems' `packages.yaml` file, specify the hardware-specific variants (openmp, cuda versions, openblas).
