### ISSUE TITLE
Feature request: `--reuse-external`

### ISSUE THREAD

**Issue by nilsvu** [LLNL/spack#28206]
### Summary

I propose to add a `--reuse-external` configuration option as a weaker but more deterministic alternative to the new `--reuse` interface coming to Spack.

### Rationale

The idea is to avoid reinstalling available system packages, but don't try to actively reuse previously Spack-installed packages. I believe this would retain a majority of the predictability that we currently have, while avoiding the overhead of reinstalling system packages. This may even be a less drastic candidate for the new default than `--reuse`. I understand the new `--reuse` interface is currently experimental and an interface based on config files is in the works. A possible interface would be an option like this in an environment's `spack.yaml` file:

```yaml
concretization: together
# ...
reuse: external  # or: none, all
```

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Does `buildable: false` meet your needs? It's not exactly the same because it isn't configurable on the command line, but you can add it on a package-by-package basis and force Spack to only use the externally installed version.

**Comment by nilsvu** [comment]
@adamjstewart My understanding is that `buildable: false` does not quite have the same effect. For instance, consider the `sqlite` issue we just looked at in #28186. If I make the system's `sqlite~dynamic_extensions` non-buildable, then I will never be able to build a `python+sqlite3`. However, if I concretize with the proposed `--reuse-external`, then `something ^sqlite` uses the system sqlite and `python+sqlite3` (which needs `sqlite3+dynamic_extensions`) builds a new sqlite. Does that sound correct?

**Comment by nilsvu** [comment]
Here is another use case to add to the discussion:

Say I want to manage a development environment for an application on an HPC cluster, and share the `spack.lock` file with other users so they can reproduce the same environment. I want to reuse standard system packages to keep installation time and possible failure modes down for other users. Now to upgrade the `spack.lock` file occasionally, I still want to reuse system packages, but I want the concretizer to freely choose and upgrade Spack-installed packages. With `--reuse` the upgraded lockfile would be influenced by whichever packages I happen to have installed in my Spack tree at the time.

**Comment by alalazo** [comment]
Reusing externals when possible should be the default behavior when you have `buildable: true`. Do you have examples where this is not the case?

**Comment by alalazo** [comment]
This is for instance the behavior I see with the CMake version installed on my Ubuntu:

![Screenshot from 2022-01-03 11-11-45](https://user-images.githubusercontent.com/4199709/147919298-beed5fe3-a6a1-4143-a9ab-a32d8ae1061f.png)

**Comment by nilsvu** [comment]
You're right @alalazo 👍 I didn't realize this behaviour was added. I believe the docs need to be updated, they say:

> The packages configuration can tell Spack to use an external location for certain package versions, but it does not restrict Spack to using external packages. In the above example, since newer versions of OpenMPI are available, Spack will choose to start building and linking with the latest version rather than continue using the pre-installed OpenMPI versions.
--- https://spack.readthedocs.io/en/latest/build_settings.html

**Comment by alalazo** [comment]
> I believe the docs need to be updated, 

:+1: I'll try to submit a PR soon. Is it ok with you to close this issue when docs are updated? Or is there something more to be addressed here?

**Comment by nilsvu** [comment]
Yes sounds good 👍 Thanks for looking into this.

**Comment by alalazo** [comment]
Docs have been updated, see https://spack.readthedocs.io/en/latest/build_settings.html#prevent-packages-from-being-built-from-sources
