### ISSUE TITLE
"Error: KeyError: 'LIBDIR'" when an external python is used

### ISSUE THREAD

**Issue by benpm** [LLNL/spack#28274]
### Steps to reproduce

1. Create a packages.yaml that defines an external python (that doesn't have dev libraries installed?)
2. `spack install exodusii`

### Error message

```==> Installing exodusii-2021-04-05-7z43vabdqjnmbdrgwpkv6qjrwgai2hwt
==> No binary for exodusii-2021-04-05-7z43vabdqjnmbdrgwpkv6qjrwgai2hwt found: installing from source
==> Error: KeyError: 'LIBDIR'

/home/user/spack/var/spack/repos/builtin/packages/python/package.py:795, in libs:
        792        # installs them into lib64. If the user is using an externally
        793        # installed package, it may be in either lib or lib64, so we need
        794        # to ask Python where its LIBDIR is.
        795        libdir = self.config_vars['LIBDIR']
        796
        797        # In Ubuntu 16.04.6 and python 2.7.12 from the system, lib could be
        798        # in LBPL```

### Information on your system

```
* **Spack:** 0.17.1
* **Python:** 3.9.5
* **Platform:** linux-centos8-haswell
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by benpm** [comment]
@adamjstewart requested to be assigned to this

**Comment by adamjstewart** [comment]
On the line before the `LIBDIR` line in the Python package, can you add `print(self.config_vars)` and run again with `spack --debug install exodusii`? I want to see if `config_vars` is completely empty or just missing the `LIBDIR` key. Also, what directory is Python installed in? Can you run `find <prefix> -name 'libpython*.so'` to see if there are any library files there?

**Comment by benpm** [comment]
> On the line before the `LIBDIR` line in the Python package, can you add `print(self.config_vars)` and run again with `spack --debug install exodusii`? I want to see if `config_vars` is completely empty or just missing the `LIBDIR` key. Also, what directory is Python installed in? Can you run `find <prefix> -name 'libpython*.so'` to see if there are any library files there?

I would love to, but unfortunately I can no longer reproduce this issue...

**Comment by adamjstewart** [comment]
Is that because you're using Spack-installed Python instead of the system Python? Or can you no longer reproduce with the system Python?

**Comment by benpm** [comment]
Well... I'm actually reporting this for somebody else's sake, I never actually ran in to this problem myself, even though supposedly we're both using the same config for Spack. The issue is now fixed on their end. I'll try to ask them to get it to fail again, but it could take a while.
