### ISSUE TITLE
spack compiler find for nvhpc is not correct

### ISSUE THREAD

**Issue by shahzebsiddiqui** [LLNL/spack#28275]
@lukebroskop @samcmill 

cc: @wspear @eugeneswalker @sameershende 

There is an issue when running `spack compiler find` for detecting nvhpc compilers. According to this line it will create module `PrgEnv-nvhpc` 

https://github.com/spack/spack/blob/a43ed9286fc99f5e9127744d914b7c09a4021836/lib/spack/spack/compilers/nvhpc.py#L28

I think this was the case some time back but now Cray has decided to change this to `PrgEnv-nvidia` according to Perlmutter we get the following modules

```
(spack-pyenv) siddiq90@login06> ml -t av PrgEnv
/opt/cray/pe/lmod/modulefiles/core:
PrgEnv-aocc/8.2.0
PrgEnv-cray/8.2.0
PrgEnv-gnu/8.2.0
PrgEnv-nvidia/8.2.0
```

If i load `PrgEnv-nvidia` i should get spack to detect the compiler but in this case i dont get this

```
(spack-pyenv) siddiq90@login06> ml PrgEnv-nvidia
(spack-pyenv) siddiq90@login06> spack compiler find
==> Found no new compilers
==> Compilers are defined in the following files:
    /global/homes/s/siddiq90/software.nersc.gov/spack-infrastructure/spack-configs/perlmutter-systemlayer/ci/spack.yaml
```

**Comment by shahzebsiddiqui** [comment]
Please take a look at #28276 and see if this would be ok.

**Comment by samcmill** [comment]
NVIDIA and HPE/Cray are working together on how to best address this.

**Comment by shahzebsiddiqui** [comment]
i am going to close this according to @lukebroskop message https://github.com/spack/spack/pull/28276#issuecomment-1036320038
