### ISSUE TITLE
Installation issue: diamond fails to link in spack, works fine outside of spack with gcc 10+

### ISSUE THREAD

**Issue by snehring** [LLNL/spack#28295]
### Steps to reproduce the issue

```console
$ spack install diamond%gcc@11.2.0
```

### Information on your system

* **Spack:** 0.17.1-740-6e31094d77
* **Python:** 3.10.1
* **Platform:** linux-fedora35-zen2
* **Concretizer:** clingo

### Additional information

[spack-build-out.txt](https://github.com/spack/spack/files/7830264/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/7830265/spack-build-env.txt)

Interestingly, it also works if you do 'spack build-env diamond%gcc@11.2.0 bash' and run cmake and make manually

I brought this up on slack and Ewan Roche was able to reproduce the issue and pointed out the resulting object files are indeed different between the spack compilation and gcc outside of spack, I honestly hadn't though to look at that.

Removing the unimplemented virtual destructor it complains about, does fix the problem, and should be fine, but isn't the best solution in my mind. This is what I've done in #28289 however I don't even know where to begin resolving this properly.

``` console
$ nm -C ~/projects/spack/var/spack/stage/spack-stage-diamond-2.0.11-yw7qbzesyog4a7tncq7yak5xw5q7m77z/spack-build-yw7qbze/CMakeFiles/diamond.dir/src/align/align.cpp.o | grep ExtensionPipeline
0000000000000000 W ExtensionPipeline::Swipe::Pipeline::~Pipeline()
0000000000000000 W ExtensionPipeline::Swipe::Pipeline::~Pipeline()
0000000000000000 W ExtensionPipeline::Swipe::Pipeline::~Pipeline()
0000000000000000 n ExtensionPipeline::Swipe::Pipeline::~Pipeline()
                 U vtable for ExtensionPipeline::BandedSwipe::Pipeline
                 U vtable for ExtensionPipeline::Swipe::Pipeline
```
and the outside of spack result
``` console
$ nm -C CMakeFiles/diamond.dir/src/align/align.cpp.o | grep ExtensionPipeline
0000000000000000 W ExtensionPipeline::Swipe::Pipeline::~Pipeline()
0000000000000000 W ExtensionPipeline::Swipe::Pipeline::~Pipeline()
0000000000000000 W ExtensionPipeline::Swipe::Pipeline::~Pipeline()
0000000000000000 n ExtensionPipeline::Swipe::Pipeline::~Pipeline()
                 U vtable for ExtensionPipeline::BandedSwipe::Pipeline
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by ilbiondo** [comment]
The issue seems to be the difference in compiler flags between Spack and the original CMake . the former uses O2 and the latter O3. Quite what is going on is a complete mystery to me.

With O2 and the command line options used by Spack 

```
 g++ -DLEFTMOST_SEED_FILTER -DMAX_SHAPE_LEN=19 -DSEQ_MASK -DSTRICT_BAND -I/dcsrsoft/spack/arolle/v0.1/spack/opt/spack/linux-rhel8-zen2/gcc-11.2.0/zlib-1.2.11-gftyrgy5bmexpemz33m3kxpsp4nr7fbp/include -I/tmp/eroche/spack-stage/spack-stage-diamond-2.0.13-w76lpicf4eaukeboj2odvseans3a4nwo/spack-src/src/lib -Wall -Wextra -Wno-implicit-fallthrough -Wreturn-type -Wno-unused -Wno-unused-parameter -Wno-unused-variable -Wno-uninitialized -Wno-deprecated-copy -Wno-unknown-warning-option -O2 -g -DNDEBUG -std=gnu++14 -MD -MT CMakeFiles/diamond.dir/src/align/align.cpp.o -MF CMakeFiles/diamond.dir/src/align/align.cpp.o.d -o CMakeFiles/diamond.dir/src/align/align.cpp.o -c /tmp/eroche/spack-stage/spack-stage-diamond-2.0.13-w76lpicf4eaukeboj2odvseans3a4nwo/spack-src/src/align/align.cpp

$ nm -C ./CMakeFiles/diamond.dir/src/align/align.cpp.o | grep ExtensionPipeline
0000000000000000 W ExtensionPipeline::Swipe::Pipeline::~Pipeline()
0000000000000000 W ExtensionPipeline::Swipe::Pipeline::~Pipeline()
0000000000000000 W ExtensionPipeline::Swipe::Pipeline::~Pipeline()
0000000000000000 n ExtensionPipeline::Swipe::Pipeline::~Pipeline()
                 U vtable for ExtensionPipeline::BandedSwipe::Pipeline
                 U vtable for ExtensionPipeline::Swipe::Pipeline

``` 

And exactly the same but replacing O2 with O3

```
$ g++ -DLEFTMOST_SEED_FILTER -DMAX_SHAPE_LEN=19 -DSEQ_MASK -DSTRICT_BAND -I/dcsrsoft/spack/arolle/v0.1/spack/opt/spack/linux-rhel8-zen2/gcc-11.2.0/zlib-1.2.11-gftyrgy5bmexpemz33m3kxpsp4nr7fbp/include -I/tmp/eroche/spack-stage/spack-stage-diamond-2.0.13-w76lpicf4eaukeboj2odvseans3a4nwo/spack-src/src/lib -Wall -Wextra -Wno-implicit-fallthrough -Wreturn-type -Wno-unused -Wno-unused-parameter -Wno-unused-variable -Wno-uninitialized -Wno-deprecated-copy -Wno-unknown-warning-option -O3 -g -DNDEBUG -std=gnu++14 -MD -MT CMakeFiles/diamond.dir/src/align/align.cpp.o -MF CMakeFiles/diamond.dir/src/align/align.cpp.o.d -o CMakeFiles/diamond.dir/src/align/align.cpp.o -c /tmp/eroche/spack-stage/spack-stage-diamond-2.0.13-w76lpicf4eaukeboj2odvseans3a4nwo/spack-src/src/align/align.cpp

$ nm -C ./CMakeFiles/diamond.dir/src/align/align.cpp.o | grep ExtensionPipeline
0000000000000000 W ExtensionPipeline::Swipe::Pipeline::~Pipeline()
0000000000000000 W ExtensionPipeline::Swipe::Pipeline::~Pipeline()
0000000000000000 W ExtensionPipeline::Swipe::Pipeline::~Pipeline()
0000000000000000 n ExtensionPipeline::Swipe::Pipeline::~Pipeline()
                 U vtable for ExtensionPipeline::BandedSwipe::Pipeline
```

As an aside O1 also works correctly.

I'd be inclined to say that this is either a compiler bug or undefined behaviour in the code. Changing the flags to O2 in the non Spack build also reproduces the error.

It's perhaps not ideal that Spack isn't using exactly the same options as the developers intended but it's also the first time I've seen a higher optimisation level hide an error.

As the Diamond project is actively maintained and we can reproduce outside of Spack I'd be tempted to submit a bug report there rather than try and hack it in Spack.

**Comment by snehring** [comment]
I guess it'd be more of a compiler bug. If you disable optimizations entirely you end up with that Swipe::Pipeline vtable missing from the symbol list. It only seems to appear with -O2

**Comment by snehring** [comment]
It also seems to be unique to -std=[c|gnu]++14 and up

**Comment by snehring** [comment]
This is now fixed upstream, pending a release. It can be worked around by specifying build_type=Release until such time that I or someone else updates the version.
