### ISSUE TITLE
Build dependencies autoconf and m4 can be incompatible

### ISSUE THREAD

**Issue by nilsvu** [LLNL/spack#28336]
### Steps to reproduce

On macOS 12.0.1:

- Edit the `autoconf` packages: `depends_on('m4@1.4.13:', when='@2.64:')` (see https://bugs.launchpad.net/ubuntu/+source/autoconf/+bug/459422)
- Run `spack external find`: finds `autoconf@2.71` and `m4@1.4.6`. Note that these are incompatible, because `m4@1.4.6` is missing the `--gnu` flag.
- `spack install libtiff`, or another autotools package that runs the default `autoreconf`. It uses the external autoconf and m4, although they are incompatible.

### Error message

```
m4: unrecognized option `--gnu'
```

### Information on your system

* **Spack:** 0.17.1-759-e55fce3cb6
* **Python:** 3.9.9
* **Platform:** darwin-monterey-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
This would not happen if Spack could build the dependencies, and is a known limitation of externals. Basically dependencies are trimmed, so any constraint that comes from the dependency of an external is discarded.
