### ISSUE TITLE
Installation issue: py-torch build failure on Sierra-like platforms (PPC64le + RHEL 7 + GCC 8.3.x)

### ISSUE THREAD

**Issue by quellyn** [LLNL/spack#28367]
### Steps to reproduce the issue

Sanity check of the system:
```console
$ arch
ppc64le

$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.9 (Maipo)
```

Load `gcc/8.3.0` (closest to the Sierra default GCC):
```console
$ module load gcc/8.3.0
```

Pull down Spack, scrub out caches:
```console
$ git clone git@github.com:spack/spack.git
$ cd spack
$ spack clean --all -b
$ rm -rf ~/.spack/         # get rid of any pesky compilers.yaml files lying around
```

Detect our compiler of choice:
```console
$ spack compiler find

==> Added 2 new compilers to /vast/home/quellyn/.spack/linux/compilers.yaml
    gcc@8.3.0  gcc@4.8.5
==> Compilers are defined in the following files:
    /vast/home/quellyn/.spack/linux/compilers.yaml
```

Try to build `py-torch` without CUDA support:
NOTE: Have to specify `netlib-lapack` here, otherwise concretizer picks `intel-mkl` for some strange reason. This happens even if I list netlib-lapack as the blas/lapack provider in `packages.yaml` ...
```console
spack install -v py-torch%gcc@8.3.0 ~caffe2~cuda~cudnn~distributed~fbgemm~gloo~magma~nccl~nnpack~qnnpack~xnnpack ^netlib-lapack@3.8.0
```

The above attempt fails at the end with:
```console
/tmp/quellyn/spack-stage/spack-stage-py-torch-1.10.1-it56biuf5z2rha52odve3lveq7mtw3k5/spack-src/aten/src/ATen/cpu/vec/vec256/vsx/vec256_double_vsx.h: In member function 'void at::vec::{anonymous}::Vectorized<double>::dump() const':
/tmp/quellyn/spack-stage/spack-stage-py-torch-1.10.1-it56biuf5z2rha52odve3lveq7mtw3k5/spack-src/aten/src/ATen/cpu/vec/vec256/vsx/vec256_double_vsx.h:192:12: error: 'cout' is not a member of 'std'
       std::cout << _vec0[0] << "," << _vec0[1] << "," << _vec1[0] << "," << _vec1[1] << std::endl;
            ^~~~
/tmp/quellyn/spack-stage/spack-stage-py-torch-1.10.1-it56biuf5z2rha52odve3lveq7mtw3k5/spack-src/aten/src/ATen/cpu/vec/vec256/vsx/vec256_double_vsx.h:192:12: note: 'std::cout' is defined in header '<iostream>'; did you forget to '#include <iostream>'?
```

Any ideas?

### Information on your system

```console
$ spack debug report
* **Spack:** 0.17.1-781-363a565
* **Python:** 3.6.8
* **Platform:** linux-rhel7-power9le
* **Concretizer:** clingo
```

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/7851282/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7851283/spack-build-out.txt)

```console```
$ spack maintainers py-torch
adamjstewart
```

Mentioning @adamjstewart , as he seems to be the official maintainer.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
The error says:
```
note: 'std::cout' is defined in header '<iostream>'; did you forget to '#include <iostream>'?
```
Did you check if this is the case for the compilation unit that fails?

**Comment by quellyn** [comment]
> The error says:
> 
> ```
> note: 'std::cout' is defined in header '<iostream>'; did you forget to '#include <iostream>'?
> ```
> 
> Did you check if this is the case for the compilation unit that fails?

Get ready to go down the rabbit hole ... 

It looks like `py-torch` removed "unnecessary" iostream includes back in July:
(https://github.com/pytorch/pytorch/pull/61500).

This precipitated some fallout:
https://github.com/pytorch/pytorch/issues/65956

Which they next tried to address with:
https://github.com/pytorch/pytorch/pull/63533

That last patch eliminates the "std::cout" errors but introduced a string of other problems with ppc64:
https://github.com/pytorch/pytorch/issues/66077  (addressed by https://github.com/pytorch/pytorch/pull/66085)
https://github.com/pytorch/pytorch/issues/66867  (addressed by https://github.com/pytorch/pytorch/pull/67331)
https://github.com/pytorch/pytorch/issues/68057 (addressed by https://github.com/pytorch/pytorch/pull/68914

I can try to build `py-torch@master` instead and see if that really fixed this.

**Comment by quellyn** [comment]
Sadly, no:

```console
$ spack install -v py-torch@master%gcc@8.3.0 ~caffe2~cuda~cudnn~distributed~fbgemm~gloo~magma~nccl~nnpack~qnnpack~xnnpack ^netlib-lapack@3.8.0
```

Fails with:
```console
/tmp/quellyn/spack-stage/spack-stage-py-torch-master-k4wvshiw5qlv3pwvcrrsef4mboporo6m/spack-src/aten/src/ATen/native/attention.cpp:145:46: error: use of deleted function 'double& at::vec::CPU_CAPABILITY::Vectorized<double>::operator[](int)'
                   hmax = std::max(max_input[i], hmax);
```

And many more (see attached).
[spack-build-env.txt](https://github.com/spack/spack/files/7857635/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7857636/spack-build-out.txt)

Unless I'm doing something truly dumb here, I'd better go report this to the Py-Torch folks...

Edit: Mentioning @adamjstewart again since I don't think my attempt at doing so in the original ticket submission worked.
Also mentioning @KineticTheory, as he's also interested in having this tool on ppc64le systems.

**Comment by adamjstewart** [comment]
Yes, this definitely looks like an issue in PyTorch. I would report the build issues to them (especially the one on master). We can add patches for any of these if you want (could be to undo the removal of iostream or to add the replacement hacks).

**Comment by adamjstewart** [comment]
Is this still an issue? We've backported quite a few patches to PyTorch for PPC support, and I think it's even tested in CI.

**Comment by quellyn** [comment]
Hi Adam,I am no longer working for LANL, but I believe our difficulties with this package were resolved. You can close this issue.QOn Sep 18, 2024, at 4:39 AM, Adam J. Stewart ***@***.***> wrote:﻿
Is this still an issue? We've backported quite a few patches to PyTorch for PPC support, and I think it's even tested in CI.
