### ISSUE TITLE
Question about MPI and Spack's compiler wrappers

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#2836]
I noticed a lot of packages will have something like this:
```python
if '+mpi' in spec:
    config_args.append('CC={0}'.format(spec['mpi'].mpicc))
```
My question is, if we change `CC` to be something other than Spack's compiler wrapper, does the compiler wrapper still get called? If not, how are things like `-L/path/to/dep`, `-I/path/to/dep`, and RPATH logic for every dependency included in the build?

**Comment by davydden** [comment]
> if we change CC to be something other than Spack's compiler wrapper, does the compiler wrapper still get called?

yes, for `openmpi` this is does by
```
spack_env.set('OMPI_CC', spack_cc)
spack_env.set('OMPI_CXX', spack_cxx)
spack_env.set('OMPI_FC', spack_fc)
spack_env.set('OMPI_F77', spack_f77)
```
and later filtered out to work outside of Spack in `filter_compilers`.

**Comment by davydden** [comment]
i think someone asked exactly this question recently (not sure which issue), so I added a `documentation` tag to make sure it's documented somewhere, if it is not yet.

**Comment by adamjstewart** [comment]
Oh, I see. So the MPI wrappers accept a variable (`OMPI_CC` for OpenMPI, `MPICH_CC` for MPICH, etc.) that can be used to override the default `CC` to use. I knew we were filtering Spack's compiler wrappers out of `CC`, so I was wondering how that came back in to play. A note in the documentation could be useful.

**Comment by tgamblin** [comment]
The relevant google group post is linked from #2419.  I'll see if I can add that to the docs.

**Comment by tgamblin** [comment]
Here's a more direct link: [google group post](https://groups.google.com/d/msg/spack/ECmt5-Ew3yo/Is0F2lLHCAAJ)
