### ISSUE TITLE
libssl version not overriden by packages.yaml ; incompatibility with all system libssl clients then results

### ISSUE THREAD

**Issue by prckent** [LLNL/spack#28362]
### Steps to reproduce the issue

Despite

cat .spack/packages.yaml 
```
packages:
    openssl:
        externals:
        - spec: openssl@1.1.1k
          prefix: /usr
          buildable: False
```

spack installs the preferred version of libssl 1.1.1m when used in other packages.  This then means that I can't run the system provided, (say) emacs once a spack package using libssl is loaded:

```
$ emacs -nw
# it worked
$ spack load cmake
$ emacs -nw
emacs: symbol lookup error: /lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b
``` 
In the present case this is a RHEL system and I believe that like several providers they backport fixes without increasing the version number.  My sysadmin confirms we have the "correct" library installed.

Note that spack can "see" the packages file correctly:
```
spack install openssl@1.1.1k
==> Warning: using "openssl@1.1.1k" which is a deprecated version
[+] /usr (external openssl-1.1.1k-ocr4wa5bbnnwbalbgvu7mdmrzp3xihl6)
```

The override used to work. I believe an override of the deprecation feature is needed as an option in the packages file. An official documented workaround would also help.

### Information on your system

* **Spack:** 0.17.1-772-675210bd8b
* **Python:** 3.6.8
* **Platform:** linux-rhel8-zen2
* **Concretizer:** clingo

### Additional information

`spack maintainers openssl` returns empty.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
As a workaround you could convince spack it's a newer version.

Likely it *is* a newer version, in the sense that RHEL patches 1.1.1k and keeps calling it 1.1.1k.

Edit: can you share a bit more, what openssl version is used by cmake? Or, what is `ldd $(which emacs)` before and after?

**Comment by prckent** [comment]
In this example, cmake was using the latest 1.1.1m installed by spack. RHEL indeed keeps calling their patched openssl 1.1.1k, but it does not correspond any official 1.1.1*

For emacs it is libcrypto that is the problem
```
$ldd $(which emacs)|grep crypto
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f23e5b8f000)
        libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f23e508d000)
$ spack load cmake
$ ldd $(which emacs)|grep crypto
        libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007ffa865ef000)
        libcrypto.so.1.1 =>edited/apps/spack/opt/spack/linux-rhel8-zen2/gcc-11.2.0/openssl-1.1.1m-zq5aq2lw3x3qgdaqu33riqcembchsnd3/lib/libcrypto.so.1.1 (0x00007ffa85ae0000)
```

I could clearly hack the spack package file for libssl to remove the deprecated tags, but that is not a sustainable solution.

**Comment by haampie** [comment]
Can you try #28354? Seems like the problem is with Spack setting LD_LIBRARY_PATH on load

**Comment by prckent** [comment]
#28354 fixed this / Not setting LD_LIBRARY_PATH does indeed bypass this problem. Did a fresh install including the PR, built cmake (libssl consumer), verified the above problem did not occur.

**Comment by haampie** [comment]
Okay, thanks. The bad news is that PR won't be merged immediately. The good news is that LD_LIBRARY_PATH can be disabled from the default variables in your config. For instance

```
$ cat ~/.spack/modules.yaml
modules:
  prefix_inspections::
    bin:
    - PATH
    man:
    - MANPATH
    share/man:
    - MANPATH
    share/aclocal:
    - ACLOCAL_PATH
    lib/pkgconfig:
    - PKG_CONFIG_PATH
    lib64/pkgconfig:
    - PKG_CONFIG_PATH
    share/pkgconfig:
    - PKG_CONFIG_PATH
    '':
    - CMAKE_PREFIX_PATH
```

note the double `::` which means to override that config. and then you simply make sure no LD_LIBRARY_PATH is mentioned there.

**Comment by prckent** [comment]
Thanks Harmen! Confirming that your modules file works for me. Hopefully #28354 will go in, but I'll close this since I have a successful and easily automatable solution.
