### ISSUE TITLE
Installation issue: gcc

### ISSUE THREAD

**Issue by lgiacome** [LLNL/spack#28421]
### Steps to reproduce the issue

`spack install gcc ^ncurses+symlinks`

(I use ^ncurses+symlinks because it's needed when working on the afs file system)

I am getting this weird error:

```
In file included from /tmp/lgiacome/spack-stage/spack-stage-gcc-11.2.0-yqde46ks5t2vg2szmjvadwjv6uwmmytl/spack-src/libgomp/env.c:62:
/tmp/lgiacome/spack-stage/spack-stage-gcc-11.2.0-yqde46ks5t2vg2szmjvadwjv6uwmmytl/spack-src/libgomp/secure_getenv.h:44:1: error: static declaration of 'secure_getenv' follows non-static declaration
   44 | secure_getenv (const char *name)
      | ^~~~~~~~~~~~~
In file included from /tmp/lgiacome/spack-stage/spack-stage-gcc-11.2.0-yqde46ks5t2vg2szmjvadwjv6uwmmytl/spack-src/libgomp/libgomp.h:53,
                 from /tmp/lgiacome/spack-stage/spack-stage-gcc-11.2.0-yqde46ks5t2vg2szmjvadwjv6uwmmytl/spack-src/libgomp/env.c:30:
/usr/include/stdlib.h:569:14: note: previous declaration of 'secure_getenv' with type 'char *(const char *)'
  569 | extern char *secure_getenv (const char *__name)
      |              ^~~~~~~~~~~~~
```

@alalazo @michaelkuhn 

### Information on your system

```
* **Spack:** 0.17.1-828-e0f0445
* **Python:** 3.9.5
* **Platform:** linux-centos7-broadwell
* **Concretizer:** clingo
```

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/7872151/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7872153/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
I can't reproduce with:

* **Spack:** 0.20.0.dev0 (11aa2d721e2a7cc0b1ead7687262545e95b17685)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo
