### ISSUE TITLE
Broken builds as of last night

### ISSUE THREAD

**Issue by vsoch** [LLNL/spack#28436]
I have an automated build for dyninst - you can see the Dockerfile here:  https://github.com/dyninst/dyninst/tree/master/docker built as follows from that directory

```bash
$ docker build -t dyninst -f Dockerfile ../
```

And it hasn't had an issue building nightly... until last night. It fails to apply a patch and then chokes and dies.

![image](https://user-images.githubusercontent.com/814322/149677381-bacc8569-b71d-4972-8c63-408d9600f2b1.png)

https://github.com/dyninst/dyninst/runs/4833782666?check_suite_focus=true

I tried pinning to the last spack release, that produced a different error:

https://github.com/dyninst/dyninst/pull/1185

![image](https://user-images.githubusercontent.com/814322/149677443-1bcef7d4-6b0a-4aca-8ec3-7c0789927ff5.png)

I'm not sure what I can do here - I'd like the build to keep working. Thanks!

**Comment by vsoch** [comment]
Note that the PR link I'm a bit desperate so I'm going to try to pin to an early version of spack. But this was working two days ago so... no ideas here.

**Comment by mwkrentel** [comment]
@pbrady @tgamblin @hainest 
I can reproduce the same failure. 
See:  https://github.com/spack/spack/pull/28322

Maybe the range `when="@1.69.0:1.73.0"` needs to be adjusted.

**Comment by vsoch** [comment]
That was my thoughts too (just copy pasta-d this in slack). For my container I'm trying to do 1.73.0. Perhaps the range should be adjusted to 1.72.0? If we want to decide on something to test I can make a branch for it and redo my build.

**Comment by vsoch** [comment]
I'll test 1.72.0 on my build now and see if it still happens.

**Comment by vsoch** [comment]
And thank you @mwkrentel !

**Comment by hainest** [comment]
The version range comes from https://github.com/spack/spack/issues/28273#issuecomment-1007694749. The open interval version test would then be [1.69.0, 1.73.0), no? Did I muck that up?

**Comment by vsoch** [comment]
1.72 has reached way beyond the original error point so (although the full dyninst container might not build) I think this fixes the issue here! https://github.com/dyninst/dyninst/runs/4835044296?check_suite_focus=true

**Comment by vsoch** [comment]
@hainest I found an example in the docs by grepping for when, and it looks like that syntax is <= so 1.73.0 would be included (highlighted in gray because I'm making good decisions about colors here lol).

![image](https://user-images.githubusercontent.com/814322/149688967-51f6c2e2-7c10-4f19-9580-611ea1eca098.png)

**Comment by vsoch** [comment]
https://github.com/spack/spack/pull/28437

**Comment by hainest** [comment]
@vosch

https://spack.readthedocs.io/en/latest/basic_usage.html#version-specifier

Bah! I should have double-checked. Mea culpa for the breakages.

**Comment by vsoch** [comment]
yep definitely didn't look in basic usage, ug. Thanks @hainest! And I don't think it's anyone's fault, no need to apologize.

**Comment by alalazo** [comment]
Closing this manually, I wasn't fast enough to change to `fixes` in the PR - it was merged while I was editing 🙂
