### ISSUE TITLE
"unalias: despacktivate: not found" error in setup-env.sh 

### ISSUE THREAD

**Issue by carns** [LLNL/spack#28509]
### Steps to reproduce

So far I've only seen this in job batch scripts and not in interactive terminals, but I don't know what the difference is yet.

These scripts have a line that looks something like `. /ccs/home/carns/working/src/spack/share/spack/setup-env.sh`, with the path varying depending on where spack is located.

This command reports a failure, though spack appears to work correctly afterwards if you script is not too picky about checking return codes.

### Error message

```
/ccs/home/carns/working/src/spack/share/spack/setup-env.sh: line 143: unalias: despacktivate: not found
```

### Information on your system

```
$ spack debug report
* **Spack:** 0.17.1-915-c11ce3bd1f
* **Python:** 3.6.8
* **Platform:** linux-rhel8-power9le
* **Concretizer:** clingo
```
This is from the Summit system at the OLCF, but we have seen the same error on at least two entirely different systems at ANL.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by psakievich** [comment]
I'd like to see this addressed soon.  This is bash error that is confusing to a lot of the users in my project.

**Comment by psakievich** [comment]
I'll also throw on another fun one for the deactivate. Can't deactivate if there is a syntax error in a `spack.yaml` because deactivating tried to load the environment to deactivate.

**Comment by haampie** [comment]
> Can't deactivate if there is a syntax error

Deactivate should also undo changes from packages (setup_run_environment), so if the environment is invalid, you can't deactivate.

**Comment by psakievich** [comment]
> > Can't deactivate if there is a syntax error
> 
> Deactivate should also undo changes from packages (setup_run_environment), so if the environment is invalid, you can't deactivate.

Interesting. I wasn't aware of that but it makes sense.

**Comment by haampie** [comment]
To be fair that's quite broken, cause the general use case is: create, activate, add, concretize, install. so, at the end you don't have any package variables set, cause you activated before adding. But if you would deactivate and then activate you get the setup_run_environment changes.
