### ISSUE TITLE
Allow bootstrapping of clingo from an air-gapped network

### ISSUE THREAD

**Issue by quellyn** [LLNL/spack#28510]
Since `clingo` became the default concretizer, we've struggled to be able to use Spack on air-gapped networks.

In the current Spack release, `clingo` is bootstrapped onto the system by downloading the relevant binaries from a buildcache located on GitHub. That of course will not work on an air-gapped network. The other option is to build `clingo` from source, which is time-consuming, requires a compiler with C++14 support (the version of gcc in RHEL 7 won't do), and requires modification of configuration files within $SPACK_USER_CACHE_PATH, which is difficult to capture in revision control.

We would really like the option to point Spack to local resources for bootstrapping `clingo`.

@becker33, @nicholas-sly, and @alalazo have put in a great deal of work to address this need (PRs #26306 and #28392). PR #28392 gets us nearly there by allowing the creation of a local buildcache for the `clingo` binaries. However, the bootstrap process is still trying to pull down `gnuconfig` and `patchelf` sources from GitHub. I've tried pulling those into a local source mirror but the bootstrap seems to be ignoring them.

@alalazo thought this might be related to #27532, and suggested I open a new issue so that they can focus on this problem separately. Hopefully it can be resolved before the original concretizer is removed, as we have no way of accessing resources from GitHub on our air-gapped networks.

Thanks!

**Comment by alalazo** [comment]
I have identified a bug for air-gapped networks. I'll submit a proper fix soon, but for the time being this diff:
```diff
diff --git a/lib/spack/spack/bootstrap.py b/lib/spack/spack/bootstrap.py
index ef33ef641f..9003a87af9 100644
--- a/lib/spack/spack/bootstrap.py
+++ b/lib/spack/spack/bootstrap.py
@@ -319,7 +319,7 @@ def _install_and_test(
     @property
     def mirror_scope(self):
         return spack.config.InternalConfigScope(
-            'bootstrap_buildcache', {'mirrors:': {self.name: self.url}}
+            'bootstrap_buildcache', {'mirrors': {self.name: self.url}}
         )
 
     def try_import(self, module, abstract_spec_str):
```
might be of help as an hotfix/workaround.

**Comment by quellyn** [comment]
> I have identified a bug for air-gapped networks. I'll submit a proper fix soon, but for the time being this diff:
> 
> ```diff
> diff --git a/lib/spack/spack/bootstrap.py b/lib/spack/spack/bootstrap.py
> index ef33ef641f..9003a87af9 100644
> --- a/lib/spack/spack/bootstrap.py
> +++ b/lib/spack/spack/bootstrap.py
> @@ -319,7 +319,7 @@ def _install_and_test(
>      @property
>      def mirror_scope(self):
>          return spack.config.InternalConfigScope(
> -            'bootstrap_buildcache', {'mirrors:': {self.name: self.url}}
> +            'bootstrap_buildcache', {'mirrors': {self.name: self.url}}
>          )
>  
>      def try_import(self, module, abstract_spec_str):
> ```
> 
> might be of help as an hotfix/workaround.

Hmm, instead of GitHub it's now going to `mirror.spack.io`:
```
==> No binary for patchelf-0.13.1-2nwvwzzpbtyppgxavpjd2msw4izvchcv found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/08/08c0237e89be74d61ddf8f6ff218439cdd62af572d568fb38913b53e222831de.tar.gz
```

If I could only get it to consult my `mirrors.yaml`, I'd be golden!

**Comment by alalazo** [comment]
@quellyn I re-tried this scenario and I think the simplest procedure to solve this issue is to download `patchelf` sources in the same mirror used to bootstrap binaries:
```console
$ wget https://github.com/alalazo/spack-bootstrap-mirrors/releases/download/v0.1-rc.2/bootstrap-buildcache.tar.gz
$ tar xzvf bootstrap-buildcache.tar.gz
$ spack mirror create -d bootstrap-buildcache patchelf@0.13.1
```
That works for me if I:
```
$ unshare -r -n spack solve zlib
```

**Comment by quellyn** [comment]
> @quellyn I re-tried this scenario and I think the simplest procedure to solve this issue is to download `patchelf` sources in the same mirror used to bootstrap binaries:
> 
> ```
> $ wget https://github.com/alalazo/spack-bootstrap-mirrors/releases/download/v0.1-rc.2/bootstrap-buildcache.tar.gz
> $ tar xzvf bootstrap-buildcache.tar.gz
> $ spack mirror create -d bootstrap-buildcache patchelf@0.13.1
> ```
> 
> That works for me if I:
> 
> ```
> $ unshare -r -n spack solve zlib
> ```

Hey @alalazo, that seems to have worked for me!

```console 
$ spack mirror create -d ../../spack.mirror/bootstrap-buildcache patchelf@0.13.1

$ spack clean -ab
$ spack concretize -f 
<snip>
==> Installing patchelf-0.13.1-sdo2cfocezxzq3x456mvur7gz2dofgrv
==> No binary for patchelf-0.13.1-sdo2cfocezxzq3x456mvur7gz2dofgrv found: installing from source
==> Fetching file:///usr/projects/shavano/spack-environments/spack.mirror/bootstrap-buildcache/_source-cache/archive/08/08c0237e89be74d61ddf8f6ff218439cdd62af572d568fb38913b53e222831de.tar.gz
```
That time it went to the mirror!

Two points/questions:
- The `spack mirror create` step seemed to take longer than usual. Is Spack bootstrapping `clingo` even before it runs `spack mirror` commands?
- I did not run the last command you suggested (`unshare -r -n spack solve zlib`). I'm not really sure what it's meant to do (pre-concretizing `zlib`?) Did my omitting that step cause the `spack mirror create` to take longer?

**Comment by alalazo** [comment]
@quellyn Glad it worked! To answer your questions:
1. Yes, Spack is concretizing the spec before fetching it to the mirror
2. It's just a command to trigger the concretization of zlib - essentially any other command that needs clingo would work as a test

**Comment by quellyn** [comment]
Great, @alalazo! Pending [your fix mentioned above](https://github.com/spack/spack/issues/28510#issuecomment-1016906375), I think this issue can be closed.
