### ISSUE TITLE
Have `spack bootstrap` print the list of its dependencies

### ISSUE THREAD

**Issue by christoph-conrads** [LLNL/spack#28540]
### Summary

Please add a command line option printing all bootstrap dependencies (e.g., `spack bootstrap dependencies`) in such a way that it can be passed to `spack mirror create` on a machine with a different operating system and/or different instruction set architecture.

### Rationale

On air-gapped systems or systems with restricted internet access, bootstrapping is easily possible if the build cache contains all needed source packages. This could easily be achieved with `spack mirror create` and widely-used tools like scp or rsync if there was just a way to get a list of bootstrapping dependencies.

### Description

* A custom buildcache does _not_ resolve the bootstrapping problem on air-gapped systems without cooperating admins.
* Building on another host and copying the bootstrapped cling does not work if there are operating system, instruction set architecture, or spack version differences.

### Additional information

The C++14 dependency of the bootstrap process is not a problem because the air-gapped systems accessible to the author have modules with more recent compiler versions (GCC 4.8.5 on RHEL 7 does not support C++14).

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
`spack install spack`

**Comment by christoph-conrads** [comment]
On my side, there are actually multiple users of two supercomputers waiting for this issue to be resolved. Thus setting up a mirror is really undesirable since there multiple compute centers involved. In addition these computers run on instruction set architectures and Linux distributions different from the average x86-64 Ubuntu machine; this is currently not handled by #28556.

It is my impression that the Spack developers are putting in a lot of effort to make Spack a better and more capable software with the steady improvement of the bootstrap mirrors. Regrettably this does not capture the special use case on my side. Would you accept a pull request for this issue and #28419? The PR for the latter issue would make Spack check its cache before checking the Spack package mirror. With these PRs, it would be possible to run Spack on a machine with restricted internet access and without administrator support as follows:
1. Untrust `github-actions` on the machine with restricted internet acces to avoid unnecessary waiting.
2. Have `spack bootstrap dependencies` print a machine-readable list of dependencies on the machine with restricted internet acces.
3. Copy-and-paste the output into `spack mirror create` on a machine with internet access.
4. Upload the Spack cache with scp to the machine with restricted internet access.
5. Run `spack spec zlib` on the machine with restricted internet access.

**Comment by alalazo** [comment]
@christoph-conrads The bootstrap dependencies are:

https://github.com/spack/spack/blob/813a0d9b19fe506e64da5e166be76d60c4f62741/lib/spack/spack/bootstrap.py#L756

https://github.com/spack/spack/blob/813a0d9b19fe506e64da5e166be76d60c4f62741/lib/spack/spack/bootstrap.py#L768

https://github.com/spack/spack/blob/813a0d9b19fe506e64da5e166be76d60c4f62741/lib/spack/spack/bootstrap.py#L783

I hope this can get you going. That said, I don't fully understand:
> Thus setting up a mirror is really undesirable since there multiple compute centers involved.

followed by a solution that uses `spack mirror create` and goes to the extra step of adding the cache.

**Comment by christoph-conrads** [comment]
Thank you for these hints, the pull request follows this week or next week.
