### ISSUE TITLE
Installation issue: py-scipy (undefined symbol at runtime)

### ISSUE THREAD

**Issue by bcdarwin** [LLNL/spack#28642]
### Steps to reproduce the issue

This is technically a runtime issue but the build template seems most appropriate.

```console
$ git clone git://github.com/spack/spack.git
$ cd spack
$ git checkout 28ea1bab
$ spack install py-scipy
$ spack load py-scipy
$ python3 -c 'import scipy.linalg.interpolative'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/bdarwin/git/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/py-scipy-1.7.3-7rqcu6qrver6dhtikicct6gxlgv3cn7z/lib/python3.9/site-packages/scipy/linalg/interpolative.py", line 385, in <module>
    import scipy.linalg._interpolative_backend as backend
  File "/home/bdarwin/git/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/py-scipy-1.7.3-7rqcu6qrver6dhtikicct6gxlgv3cn7z/lib/python3.9/site-packages/scipy/linalg/_interpolative_backend.py", line 34, in <module>
    import scipy.linalg._interpolative as _id
ImportError: /home/bdarwin/git/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.3.0/py-scipy-1.7.3-7rqcu6qrver6dhtikicct6gxlgv3cn7z/lib/python3.9/site-packages/scipy/linalg/_interpolative.cpython-39-x86_64-linux-gnu.so: undefined symbol: _ZGVdN4v_cos
```

cc @adamjstewart 

### Information on your system

* **Spack:** 0.17.1-978-28ea1bab68
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-skylake
* **Concretizer:** clingo

### Additional information

(Note the build succeeds.)

[spack-build-out.txt](https://github.com/spack/spack/files/7953091/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/7953092/spack-build-env.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Which GCC are you using, a system GCC or GCC installed manually? This is a long shot, but could you try building with a newer binutils: `spack install binutils && spack load binutils && spack install py-scipy`?

**Comment by bcdarwin** [comment]
I'm using the system gcc (9.3.0) but spack built the latest binutils (2.37) as part of building SciPy.

**Comment by adamjstewart** [comment]
I would report this issue to the scipy devs, I don't see anything that would cause this issue. If they give you a patch, we can add it to the build recipe.

**Comment by bcdarwin** [comment]
For what it's worth, `git bisect` shows that adding Numpy 1.22.0 in 38af2c6c9b was the breaking commit.

**Comment by adamjstewart** [comment]
Is this still an issue?

@rgommers FYI

**Comment by rgommers** [comment]
I'm pretty sure that this is fixed a while ago. Also, `scipy.linalg.interpolative` is now rewritten in Cython, so the original issue is certainly gone. Hence I'll close this issue.
