### ISSUE TITLE
Question: How big is a complete Spack mirror?

### ISSUE THREAD

**Issue by christoph-conrads** [LLNL/spack#28660]
A Spack mirror created with `spack mirror create --all` would solve many problems posed by air-gapped networks. Could you provide an order-of-magnitude estimate of the storage needed for such a mirror? Is there a way to obtain this estimate myself?

**Comment by christoph-conrads** [comment]
Is a number around 100 GB realistic? There exist around 6200 Spack packages and most have probably small tarballs but then there are also packages like GCC (130MB, version 10.1.0) and LLVM+Clang (95MB, version 13.0) in multiple versions. Assuming there are 100 packages with 100 MB tarballs and 10 releases listed in Spack, a mirror will easily occupy at least 100 GB.

**Comment by alalazo** [comment]
@scheibelp might be able to answer this

**Comment by alalazo** [comment]
Also, if you have an environment active which model a stack you're interested in:
```
$ spack mirror create --all
```
will create a mirror with the tarballs you need to rebuild the stack. See [here](https://spack-tutorial.readthedocs.io/en/latest/tutorial_binary_cache.html#setting-up-a-source-cache-mirror) for a tutorial showing that.

**Comment by scheibelp** [comment]
> Is a number around 100 GB realistic? 

Right now it's ~600GB. You can definitely get down to 100GB without too much trouble: for example if you generally use only the later versions of everything, and in particular if you base your mirror off of a whitelist (e.g. list every package you want, then specify every version of that and its `--dependencies`).

**Comment by christoph-conrads** [comment]
Thank you for your responses.
