### ISSUE TITLE
Too Many Commands, Poorly Organized and of Low Quality

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#2867]
I believe Spack has too many commands, poorly organized and of low quality.  The typical user only needs a few commands; the rest are merely clutter.  Some commands are of use only to a small number of Spack users, a small portion of the time --- for example, some of the `spack edit` commands.

We've gotten to this point by merging every command that came to somebody's mind at this point.  To get anything better, we will need to apply some design and make some hard choices (and not necessarily make everbody happy).  I believe we would do well to:

1. Review all commands and recommend a smaller, cleaner, more consistent set of commands moving forward.

2. Split the remaining commands into groups.  Many existing commands are of no use to the average Spack user (i.e. not a Spack developer).

Further notes / rants below...

> Why the opposition [to `spack edit -b`]?

Adding ever-more convenience commands gets away from the core mission of Spack.

I am concerned that Spack's UI is becoming bloated with large numbers (53) of commands of marginal value --- and that command line arguments to those commands are increasingly non-uniform; and therefore hard to guess/remember.  At some point, it becomes easier for most people to just navigate through the directory hierarchy and edit the file themselves; than to use a special-built Spack command to edit package superclasses.

By "marginal value" I mean, go through this thought experiment: suppose Steve Jobs appears and demands that you remove 10 commands from Spack.  Which commands will you remove while affecting Spack functionality as little as possible?  Obviously not `spack install`.  But quite possibly `spack edit -b`.

There's a point where less is more.  And I believe we're past it.  I looked through the commands, and found that I use / am aware of: config, diy, env, find, load, install, location, reindex, setup, spec, test, uninstall, module.  I'm a "power user", and yet I use only 13 out of 53 Spack commands.  And most of those 13, I have only used occasionally.

It's easy to find commands of questionable quality or marginal value.  For example:

* A  call to `spack -h` does not tell me the commands available.  Why not?  I had to guess/know to say `spack commands`.

* What does `spack build` do?  A call to `spack build -h` does not tell me (I don't know why the description string is not printed out when we do `-h`).  Meawhile, the description of the `package` cmd line arg. is misleading.  (OK... looking at the description, I think this is wrongly named as well... `spack build` does NOT build a package).

* What is the difference between `spack config` and `spack configure`?

* I already have the `md5` command, what does `spack md5` buy me?  Will it be easier to figure out how to use `spack md5` to auto-downloand and compute a checksum, or just download it myself with `curl` and then run `md5`?

**Comment by citibeth** [comment]
See here for Microsoft's humorous take on what's wrong with the "more is more" brand of thinking for product design:

https://www.youtube.com/watch?v=EUXnJraKM3k

Unfortunately almost 10 years later now, Windows still has major usability problems compared to Mac.  The response seems to have been to present a "simple" (i.e. dumbed-down) UI up-front, with the "professional" (i.e. cluttered-up) UI behind it.  This just makes the problem worse, since now users have to dig through an ever-deepending set of legacy UIs to get to the features they need to activate.

Why have few other companies been able to match Apple's reputation for simplicity and usability in design?  Certainly not for lack of examples (from Apple) to study and copy...  We can speculate all day.  But I think a large part of it has to do with groups of people getting together, with everyone insisting that their favorite feature / convenience is added to the system.  It's always easier to just "give in and let them have it" than to insist on less.  Steve Jobs was able to insist on less; and in the end, less is more.

**Comment by citibeth** [comment]
> >   A call to spack -h does not tell me the commands available.
> Yes it does:

It doesn't for my current Spack.

**Comment by tgamblin** [comment]
What does it print?

**Comment by citibeth** [comment]
> Spack is not just for you.

I know that, of course.  But I'm the one Spack user that I can easily query.  So I did.  Which is a start.  The study would be more valuable if we knew which Spack commands other users use.

My point was simply that if one "power user" uses only 13 Spack commands, it's likely that many/most Spack users use even fewer.

> Just because you don't use many of the commands doesn't mean that others don't.

I would challenge us to become more informed about what commands Spack users *do* use.  Obviously, others use commands that I do not.  But I suspect you will still find something like "90% of users use only 10% of commands."  Especially if you study which commands are used by *Spack users*, not just Spack developers.

Spack is *not just for its developers*.  New commands like `spack edit -b` are egregious in this respect because they have zero use for Spack users.

> What does it print?

The "positional arguments" section only shows me:
```
positional arguments:
  command
```
But if the current version of Spack is different, then there is no Issue here.

**Comment by tgamblin** [comment]
I'm not sure what happened to `spack -h` on your system, but this might be a useful target:

```
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

These are common Git commands used in various situations:

start a working area (see also: git help tutorial)
   clone      Clone a repository into a new directory
   init       Create an empty Git repository or reinitialize an existing one

work on the current change (see also: git help everyday)
   add        Add file contents to the index
   mv         Move or rename a file, a directory, or a symlink
   reset      Reset current HEAD to the specified state
   rm         Remove files from the working tree and from the index

examine the history and state (see also: git help revisions)
   bisect     Use binary search to find the commit that introduced a bug
   grep       Print lines matching a pattern
   log        Show commit logs
   show       Show various types of objects
   status     Show the working tree status

grow, mark and tweak your common history
   branch     List, create, or delete branches
   checkout   Switch branches or restore working tree files
   commit     Record changes to the repository
   diff       Show changes between commits, commit and working tree, etc
   merge      Join two or more development histories together
   rebase     Forward-port local commits to the updated upstream head
   tag        Create, list, delete or verify a tag object signed with GPG

collaborate (see also: git help workflows)
   fetch      Download objects and refs from another repository
   pull       Fetch from and integrate with another repository or a local branch
   push       Update remote refs along with associated objects

'git help -a' and 'git help -g' list available subcommands and some
concept guides. See 'git help <command>' or 'git help <concept>'
to read about a specific subcommand or concept.
```

or something shorter and sweeter like homebrew (though I think I like the descriptions above a bit better)

```
 brew -h
Example usage:
  brew search [TEXT|/REGEX/]
  brew (info|home|options) [FORMULA...]
  brew install FORMULA...
  brew update
  brew upgrade [FORMULA...]
  brew uninstall FORMULA...
  brew list [FORMULA...]

Troubleshooting:
  brew config
  brew doctor
  brew install -vd FORMULA

Developers:
  brew create [URL [--no-fetch]]
  brew edit [FORMULA...]
  http://docs.brew.sh/Formula-Cookbook.html

Further help:
  man brew
  brew help [COMMAND]
  brew home
```

Either of these would be better than the current `spack -h` output.

**Comment by adamjstewart** [comment]
> I am concerned that Spack's UI is becoming bloated with large numbers (53) of commands of marginal value

Try running `git help -a` sometime 😆 

>  I looked through the commands, and found that I use / am aware of: config, diy, env, find, load, install, location, reindex, setup, spec, test, uninstall, module. I'm a "power user", and yet I use only 13 out of 53 Spack commands. And most of those 13, I have only used occasionally.

If I recall, you were also opposed to `spack config` at one time. Why have a command for opening a configuration file when you have emacs?

Seriously, of the 13 commands you use, I have to this day never ran:

* spack diy
* spack env
* spack load
* spack location
* spack setup
* spack module

I don't even know what they do. If Steve Jobs came to me and asked me to remove 10 commands from Spack, these would be the first to go. You may not use some Spack subcommands, but many other users do. 

> The study would be more valuable if we knew which Spack commands other users use.

Here you go:
```
$ history| awk '{print $2" "$3}' | grep '^spack' | sort | uniq -c | sort -nr
   2312 spack edit
    688 spack install
    215 spack create
    206 spack spec
    201 spack uninstall
    187 spack list
    139 spack info
    125 spack find
    113 spack purge
     60 spack compiler
     48 spack help
     41 spack config
     36 spack reindex
     35 spack graph
     34 spack flake8
     34 spack fetch
     32 spack versions
     25 spack compilers
     24 spack checksum
     19 spack activate
     18 spack md5
     17 spack test
      7 spack arch
      5 spack deactivate
      4 spack clean
      3 spack extensions
      2 spack urls
      2 spack repo
      2 spack providers
```
You'll notice that I use a completely different set of commands than you. In fact, half of the top 10 commands I use didn't even make your list.

> Spack is not just for its developers. New commands like `spack edit -b` are egregious in this respect because they have zero use for Spack users.

So you're saying that commands that are only useful for developers are not useful? Should we also drop `spack test` or `spack flake8` while we're at it? Likewise, are commands that are only useful for users not useful unless they are also useful for developers?

I see no way in which commands that you've never heard of are detrimental to using Spack. If you don't want to use it, then don't.

**Comment by tgamblin** [comment]
@citibeth: it's worth pointing out that Apple (hardly) makes any open source software.  I don't think we can use the apple model, and we don't have such a laser-focus on any particular target audience.  *or* universal appeal.  Spack's core is a dependency system on steroids, built to support combinatorial needs of HPC folks (but useful for other projects as well).  So in many ways a minimalist argument doesn't make that much sense (though I do think we should reign in complexity where possible).

But in the end, Spack is an OSS project for both the users and the developers, and we need to support *both*.  Without the developers, we won't have a project, so I am very inclined to support them.  I think the more accurate model for this project is described in [The Cathedral and the Bazaar](https://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar). Particularly the [list of lessons](https://en.wikipedia.org/wiki/The_Cathedral_and_the_Bazaar).  I'm ok with adding convenience commands for developers as long as they scratch someone's itch.

But, I do think you raise an important point: that the UI needs to steer end users towards the stuff that's likely to be useful to them.  I think we are well overdue for some cleanup, and if power user features are harder to find in the help, then so be it.

So let's clean up the commands, and try to keep them intuitive so that there someone doesn't write [Spack Koans](http://stevelosh.com/blog/2013/04/git-koans/) one day.

**Comment by tgamblin** [comment]
@adamjstewart: I hope we can move `reindex` down towards the bottom of that histogram!

**Comment by adamjstewart** [comment]
> @adamjstewart: I hope we can move reindex down towards the bottom of that histogram!

Hahaha, I think that was back when if you installed a stack of packages and one of them broke, the other packages in the stack that just got installed weren't added to the database. Haven't seen that in a long time, so maybe we are good now.

**Comment by citibeth** [comment]
>
> I am concerned that Spack's UI is becoming bloated with large numbers (53)
> of commands of marginal value
>
> Try running git help -a sometime 😆
>
...and I've heard people on this board report that their users REFUSE to
use Git.  Is there a correlation here?


> I looked through the commands, and found that I use / am aware of: config,
> diy, env, find, load, install, location, reindex, setup, spec, test,
> uninstall, module. I'm a "power user", and yet I use only 13 out of 53
> Spack commands. And most of those 13, I have only used occasionally.
>
>

> If I recall, you were also opposed to spack config at one time. Why have
> a command for opening a configuration file when you have emacs?
>

My opinion hasn't changed, and I don't use that functionality.  Especially
since increasingly the scopes I create are not even inside of Spack.

The one part of `spack config` that I use is `spack config get <section>`,
which does the essential task of telling me what configuration Spack sees,
once all scopes are taken into account.  That has been invaluable for
debugging --- no just my config files, but also Spack's configuration
combiner itself.

I would be happier if `spack config get <section>` weren't buried.

Seriously, of the 13 commands you use, I have to this day never ran:
>
>    - spack diy
>    - spack env
>    - spack load
>    - spack location
>    - spack setup
>    - spack module
>
> I don't even know what they do. If Steve Jobs came to me and asked me to
> remove 10 commands from Spack, these would be the first to go. You may not
> use some Spack subcommands, but many other users do.
>
Please be reasonable... A command isn't useless just because *I* don't use
it.  It's useless if there's an obvious way to get the same thing done
without the command --- or if the functionality provided by the command can
be folded into another command in a simpler / more general way.

You'll notice that I use a completely different set of commands than you.
> In fact, half of the top 10 commands I use didn't even make your list.
>
You are a Spack developer.  At some point we need to think about our users'
interests.

Spack is not just for its developers. New commands like spack edit -b are
> egregious in this respect because they have zero use for Spack users.
>
> So you're saying that commands that are only useful for developers are not
> useful? Should we also drop spack test or spack flake8 while we're at it?
>
I do believe they should be sectioned off as developer commands.

> I see no way in which commands that you've never heard of are detrimental
> to using Spack.
>
Because they add a maintenance burden.  Because people can and do routinely
break commands they haven't heard of and don't use.

**Comment by tgamblin** [comment]
Ok, before this gets out of hand, can we agree to rework the command help?  I think that is the obvious thing we can do to improve things here.

**Comment by adamjstewart** [comment]
I agree that the help output could be more useful. Like `git help`, if we could put "user commands" upfront and "developer commands" below, that would help with the output of `spack help`. Also, `spack help md5` or `spack help create` should go into more detail. It doesn't even print the description. That shouldn't be too hard to fix right? I think we need a short description that gets printed when you run `spack help` and a long description that gets printed when you run `spack help subcommand`.

**Comment by citibeth** [comment]
In the documentation, we already decided there are three kinds of Spack
users:
1. "End users": they use Spack, they don't modify Spack.
2. "Packagers": they might add/modify `package.py` files but no other part
of Spack.
3. "Developers": they modify all parts of Spack.

I would suggest we structure Spack itself in a similar way.

Remember that individual commands cannot always be classed as 1,2 or 3.
Often it is subcommands that are differentiated.  For example, `spack edit`
is in (2), but `spack edit -b` is strictly (3).

One way to go about this would be to have a "user level" configuration in
`config.yaml`.  Only features for that user level would be available in
Spack.  That might be too strict, but I'm throwing it out as a good
starting point...
