### ISSUE TITLE
Installation issue: py-dask-ml unsatisfyable

### ISSUE THREAD

**Issue by YacineOR** [LLNL/spack#28704]
### Steps to reproduce the issue

spack install py-dask-ml

### Information on your system

several architectures

### Additional information

maintainer @adamjstewart

no version satisfies the package's specifications.  It seems that the versioning used by spack is obsolete.
the py-dask-ml package in the built-in repo specifies version '1.8.0'
while the current versioning convention is in the shape 'v2021.11.30'

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by YacineOR** [comment]
spack versions
0.17.1-957-bed3a69498
0.17.1-916-5e699d5354

**Comment by adamjstewart** [comment]
> no version satisfies the package's specifications

On develop I can run `spack spec py-dask-ml` and it successfully concretizes. Maybe this was fixed on develop already?

**Comment by YacineOR** [comment]
> > no version satisfies the package's specifications
> 
> On develop I can run `spack spec py-dask-ml` and it successfully concretizes. Maybe this was fixed on develop already?

You are right, the problem is that I had a hacked version of py-distributed installed in my environment that created a conflict in the dependencies of py-dask-ml.

We can close this issue.
