### ISSUE TITLE
ReadTheDocs not updating?

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#2874]
Is ReadTheDocs no longer automatically updating? I don't see anything for `PythonPackage` or `RPackage` at http://spack.readthedocs.io/en/latest/spack.build_systems.html even though those were merged long ago.

**Comment by tgamblin** [comment]
Is this still an issue?

**Comment by adamjstewart** [comment]
I'm still not seeing any documentation on `PythonPackage` or `RPackage`, unless I'm doing something wrong.

**Comment by alalazo** [comment]
@adamjstewart What about [this](http://spack.readthedocs.io/en/latest/spack.build_systems.html#module-spack.build_systems.python) or [this](http://spack.readthedocs.io/en/latest/spack.build_systems.html#module-spack.build_systems.r) ? Or were you specifically looking for something not in the API part of the docs?

**Comment by davydden** [comment]
at the bottom of the homepage of the docs it says

> Last updated on Mar 12, 2017.

probably it's not an issue of updating, but building documentation?

**Comment by adamjstewart** [comment]
Ah, I see it now. I swear it wasn't there for the longest time. Weird.

**Comment by adamjstewart** [comment]
Okay, am I going crazy?? If I go to the latest documentation:
http://spack.readthedocs.io/en/latest/spack.build_systems.html
I see Autotools, CMake, and Makefile package. Last updated on Apr 24, 2017.

If I go to the stable documentation:
http://spack.readthedocs.io/en/stable/spack.build_systems.html
I see Autotools, CMake, Makefile, Python, R (still no Perl). Last updated on Jan 17, 2017.

Wtf is going on here?? How are we losing documentation?

**Comment by alalazo** [comment]
I don't think we are not losing anything. Last stable is `v0.10` from January 17, 2017.

**Comment by alalazo** [comment]
I just tried to build the docs locally and Python, R, Perl are there as expected.

**Comment by adamjstewart** [comment]
From Read the Docs' [Build Documentation](https://docs.readthedocs.io/en/latest/builds.html#understanding-what-s-going-on):

> When we build your documentation, we run `sphinx-build -b html . _build/html`

I tried running this locally but still wasn't able to reproduce the problem. Does Read the Docs provide access to our build output? I'm curious to see if there are any warning messages.

**Comment by tgamblin** [comment]
I think if you don't clean between builds, API docs are not regenerated.  Does RTD keep old builds around?  Do we need to clean first?

**Comment by adamjstewart** [comment]
Looks like we're not the only ones with this problem:
https://github.com/rtfd/readthedocs.org/issues/208

**Comment by adamjstewart** [comment]
Fixed:
https://github.com/LLNL/spack/pull/3982/commits/5d99f68999c6b1789954ba5420dc17698d12fcc7

**Comment by adamjstewart** [comment]
It worked!
https://spack.readthedocs.io/en/latest/spack.build_systems.html

Thanks for the solution @tgamblin!
