### ISSUE TITLE
Stacks: matrix expansion failing with spack.spec.DuplicateCompilerSpecError

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#28749]
### Steps to reproduce

This error has been originally reported on Slack by @g-mathias (thanks!)

The following environment:
```yaml
spack:
  # add package specs to the `specs` list
  specs:
    # 2020 plumed mpi
    - matrix:
      - [gromacs]
      - ['@2020.1:2020.4'] 
      - ['%intel'] #compiler in extra matrix element
      - ['+plumed ^plumed@2.6.4%intel']

  view: false
```
fails to parse when expanding the matrix. To trigger the error:
```console
$ spack -e . concretize
```

### Error message

The error with a stacktrace is:

<details>
<summary>$ spack -d -e . concretize</summary>

```
==> [2022-02-03-13:13:40.299700] Reading config file /home/culpo/PycharmProjects/spack/etc/spack/defaults/config.yaml
==> [2022-02-03-13:13:40.321068] Reading config file /tmp/matrix/spack.yaml
==> [2022-02-03-13:13:40.323254] Using environment '/tmp/matrix'
==> [2022-02-03-13:13:40.324073] Imported concretize from built-in commands
==> [2022-02-03-13:13:40.324521] Imported concretize from built-in commands
==> [2022-02-03-13:13:40.327576] DuplicateCompilerSpecError: Spec for 'plumed' cannot have two compilers.
==> [2022-02-03-13:13:40.327616] Error: Spec for 'plumed' cannot have two compilers.
Traceback (most recent call last):
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 900, in main
    return _main(argv)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 883, in _main
    return _invoke_command(command, parser, args, unknown)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/main.py", line 553, in _invoke_command
    return_val = command(parser, args)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/cmd/concretize.py", line 39, in concretize
    concretized_specs = env.concretize(
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/environment/environment.py", line 1118, in concretize
    return self._concretize_separately(tests=tests, reuse=reuse)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/environment/environment.py", line 1184, in _concretize_separately
    self.user_specs, self.user_specs.specs_as_constraints
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/spec_list.py", line 63, in specs_as_constraints
    constraints.extend(_expand_matrix_constraints(item))
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/spec_list.py", line 203, in _expand_matrix_constraints
    test_spec = Spec(' '.join(ordered_combo))
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 1115, in __init__
    spec_list = SpecParser(self).parse(spec_like)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/parse.py", line 153, in parse
    return self.do_parse()
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 4747, in do_parse
    dep = self.spec(dep_name)
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 4884, in spec
    spec._set_compiler(self.compiler())
  File "/home/culpo/PycharmProjects/spack/lib/spack/spack/spec.py", line 1241, in _set_compiler
    raise DuplicateCompilerSpecError(
spack.spec.DuplicateCompilerSpecError: Spec for 'plumed' cannot have two compilers.
```

</details>

As a further data point, the following environment which should be equivalent:
```yaml
spack:
  # add package specs to the `specs` list
  specs:
    # 2020 plumed mpi
    - matrix:
      - [gromacs]
      - ['@2020.1:2020.4%intel']
      - [+plumed ^plumed@2.6.4%intel]
  view: false
```
works correctly.

### Information on your system

* **Spack:** 0.17.1-1061-18b83c3833
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

See also #20340 for another issue with best-effort matrix expansion. Adding it here since they can be probably solved at the same time with a refactor PR.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Looking a bit into it it seems that the issue is caused by:

https://github.com/spack/spack/blob/5208fcf1ea135b4500c38fbc7dba44e8558994bd/lib/spack/spack/spec_list.py#L14-L24

which is used during matrix expansion here:

https://github.com/spack/spack/blob/5208fcf1ea135b4500c38fbc7dba44e8558994bd/lib/spack/spack/spec_list.py#L201

I think the current implementation overlooked the possibility to have composite requirements like:
```
+plumed ^plumed@2.6.4
```
that impose a constraint on the root spec and on a dependency simultaneously. We should probably use "spec merge" semantics instead of string concatenation:

https://github.com/spack/spack/blob/5208fcf1ea135b4500c38fbc7dba44e8558994bd/lib/spack/spack/spec_list.py#L203

 in this function.

**Comment by haampie** [comment]
I think we could also "intersect" constraints here

```
$ spack spec zlib %gcc %gcc
==> Error: Spec for 'zlib' cannot have two compilers.
```

the second %gcc is not constraining the solution space, so it doesn't need to error. And this

```
$ spack spec zlib %gcc %gcc@8: %gcc@:10
```
can be equivalent to `%gcc@8:10`

**Comment by alalazo** [comment]
This error is more fundamental, since the strings get reordered to:
```
gromacs@2020.1:2020.4 +plumed ^plumed@2.6.4%intel %intel
```

**Comment by g-mathias** [comment]
I stumbled across this bug because going from spack 0.16.3 to 0.17.1 the concretizer returned the combination `gromacs%intel ^plumed%gcc ^cmake%gcc` from `gromacs%intel ^plumed ^cmake%gcc` (without `--reuse`). I could not figure out, where the `plumed%gcc` was coming from (giving me trouble), so I tried to force to use the intel compiler on `plumed`.
