### ISSUE TITLE
Installation issue: libuv 1.42.0

### ISSUE THREAD

**Issue by nkgh77** [LLNL/spack#28755]
### Steps to reproduce the issue

spack install julia@1.7.1

### Information on your system

* **Spack:** 0.17.1-1070-5208fcf
* **Python:** 3.8.12
* **Platform:** linux-rhel6-broadwell
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/7996663/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/7996664/spack-build-out.txt)

spack install libuv@1.42.0 works fine, but I encounter the problem when I build libuv under julia@1.7.1

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by nkgh77** [comment]
I am sorry but 
$spack maintainers libuv
returns nothing, and cannot mention the developer.

**Comment by haampie** [comment]
Hm, does

```
git clone https://github.com/JuliaLang/libuv.git
cd libuv
./configure
make -j
```

work for you?

**Comment by nkgh77** [comment]
yes, it looks successful
  CCLD     libuv.la

**Comment by haampie** [comment]
Can you try #28780

**Comment by nkgh77** [comment]
I know this is too much ad-hoc, but
I succeeded to compile libuv, by
(1) halting the process with Ctrl-z when the patch is applied,
(2) and copy "spack-src/src/unix/loop-watcher.c" to "spack-src/src/"
(3) and restart the process with "% fg".
not quite sure why the source has gone.

**Comment by haampie** [comment]
weird. can you try with https://spack.readthedocs.io/en/latest/packaging_guide.html#package-level-build-parallelism, maybe there is some race or so.

**Comment by haampie** [comment]
Actually I think something goes wrong when applying the patch.

```
$ spack stage libuv
==> Staged libuv in /tmp/spack-stage-libuv-1.42.0-plz3q6woumw5fz3ccoumckds6lerclps

$ cd /tmp/spack-stage-libuv-1.42.0-plz3q6woumw5fz3ccoumckds6lerclps

$ find . -iname loop-watcher.c
./src/win/loop-watcher.c
./src/unix/loop-watcher.c

$ curl -Lfs https://raw.githubusercontent.com/spack/patches/89b6d14eb1f3c3d458a06f1e06f7dda3ab67bd38/julia/libuv-1.42.0.patch | git apply 
<stdin>:879: trailing whitespace.
    
<stdin>:907: trailing whitespace.
    
<stdin>:910: trailing whitespace.
    may be pending on the next input event on that TTY on Windows, and does not 
<stdin>:3425: trailing whitespace.
  
warning: 4 lines add whitespace errors.
$ find . -iname loop-watcher.c
./src/loop-watcher.c
```

Can you apply the patch by hand and see if it works?

```
$ spack stage libuv@1.42.0
$ cd /path/to/where/it's/staged/spack-src
$ curl -Lfs https://raw.githubusercontent.com/spack/patches/89b6d14eb1f3c3d458a06f1e06f7dda3ab67bd38/julia/libuv-1.42.0.patch | patch --strip=1
$ ./autogen.sh
$ ./configure
$ make -j
```

**Comment by haampie** [comment]
I can reproduce your problem, the default `patch` version on rhel 6 has bugs.

```console
# docker run -it spack/centos6

$ curl -Lfso x.tar.gz https://github.com/libuv/libuv/archive/v1.42.0.tar.gz
$ tar -xf x.tar.gz
$ cd libuv-1.42.0/
$ curl -Lfs https://raw.githubusercontent.com/spack/patches/89b6d14eb1f3c3d458a06f1e06f7dda3ab67bd38/julia/libuv-1.42.0.patch | patch --strip=1
$ find . -iname loop-watcher.c
./src/unix/loop-watcher.c

$ cd .. && rm -rf libuv-1.42.0/ && tar -xf x.tar.gz
$ spack install patch
$ cd libuv-1.42.0/
$ curl -Lfs https://raw.githubusercontent.com/spack/patches/89b6d14eb1f3c3d458a06f1e06f7dda3ab67bd38/julia/libuv-1.42.0.patch | /opt/spack/opt/spack/linux-centos6-x86_64/gcc-4.4.7/patch-2.7.6-mm244o7wg6cura4okveebkgc2mvjjlni/bin/patch --strip=1
$ find . -iname loop-watcher.c
./src/loop-watcher.c
```

**Comment by haampie** [comment]
as a hacky workaround, you can add `depends_on('patch@2.7:', type='build')` to julia/package.py.
