### ISSUE TITLE
Installation issue: py-grpcio

### ISSUE THREAD

**Issue by nkgh77** [LLNL/spack#28781]
### Steps to reproduce the issue
```console
$ spack install py-grpcio
```

### Information on your system

* **Spack:** 0.17.1-1070-5208fcf
* **Python:** 3.8.12
* **Platform:** linux-rhel6-broadwell
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/8003480/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/8003481/spack-build-out.txt)

@adamjstewart  
@aweits

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
The error in the logs seems to be:
```
  third_party/abseil-cpp/absl/synchronization/internal/graphcycles.cc: In member function 'void absl::lts_2020_02_25::synchronization_internal::GraphCycles::RemoveNode(void*)':
  third_party/abseil-cpp/absl/synchronization/internal/graphcycles.cc:451:26: error: 'numeric_limits' is not a member of 'std'
    451 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
        |                          ^~~~~~~~~~~~~~
  third_party/abseil-cpp/absl/synchronization/internal/graphcycles.cc:451:49: error: expected primary-expression before '>' token
    451 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
        |                                                 ^
  third_party/abseil-cpp/absl/synchronization/internal/graphcycles.cc:451:52: error: '::max' has not been declared; did you mean 'std::max'?
    451 |   if (x->version == std::numeric_limits<uint32_t>::max()) {
        |                                                    ^~~
        |                                                    std::max
```
This is the same as https://github.com/abseil/abseil-cpp/issues/992. Unfortunately, because this is a vendored dependency, we can't just use a newer version of abseil-cpp, we have to patch it or convince the grpcio devs to vendor a newer version of abseil-cpp. It looks like the latest release of grpcio may actually include an updated copy of abseil-cpp. Let me open a PR adding the newer version and see if it solves your issue.

**Comment by nkgh77** [comment]
thank you for your help. py-grpcio@1.43.0 is successfully installed.
