### ISSUE TITLE
Installation issue: bazel@3.7.2 via py-tensorflow@2.3.2

### ISSUE THREAD

**Issue by nkgh77** [LLNL/spack#28799]
### Steps to reproduce the issue

spack install py-tensorflow~cuda+mkl ^py-grpcio@1.43.0

### Information on your system

* **Spack:** 0.17.1-1092-d82dcd3
* **Python:** 3.8.12
* **Platform:** linux-rhel6-broadwell
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/8009875/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/8009876/spack-build-out.txt)

@adamjstewart  @aweits

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Looks like this is a GCC 11 bug: https://stackoverflow.com/a/68149587/5828163

@aweits @glennpj any idea which versions of Bazel might support GCC 11?

@nkgh77 for now you could try building with an older version of GCC. I'm hoping that our TF PR (should be done soon) will add a new enough version of Bazel/TF that things will just work.

**Comment by glennpj** [comment]
> any idea which versions of Bazel might support GCC 11?

Potentially bazel-4.1 with #28548 but that has not been completely worked out yet.

**Comment by nkgh77** [comment]
Thank you very much for your comments. I am closing the ticket.
