### ISSUE TITLE
Tarball cache not happening

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#2883]
I just updated to the latest Spack, and am on a "clean" install with a new `~/.spack` directory.  The Spack download cache (#579) is just not appearing.  Not in the `var/spack/cache` directory.  Does anyone know why?

 (OK; my Spack is actually the latest with a couple of PR's merged in).

**Comment by adamjstewart** [comment]
What does `spack config get config` return? Perhaps you overwrote `source_cache` in one of your configuration files and it is no longer the default (`$spack/var/spack/cache`)

**Comment by citibeth** [comment]
Oh I feel dumb... there's no cache directory because I haven't installed anything yet!
