### ISSUE TITLE
spack command not found on Mac

### ISSUE THREAD

**Issue by erikmartinessanches** [LLNL/spack#28845]
### Steps to reproduce

I followed the readme and installed from `./spack install zlib`, however, even after restarting 'spack' is not available in terminal. How do I find it or uninstall it?

### Error message

zsh: command not found: spack

### Information on your system

macOS Big Sur 11.6.3 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
You can either add `spack` to your `PATH` like:
```bash
export PATH+=:~/spack/bin
```
or source our setup script using:
```bash
. ~/spack/share/spack/setup-env.sh
```
Add this to your `.zshrc` file to make it persistent across new terminal sessions. See https://spack.readthedocs.io/en/latest/getting_started.html#shell-support for details.

**Comment by erikmartinessanches** [comment]
Thanks, perhaps I can try it in the future as presently I decided not to use spack. To uninstall do I just delete the repo or did it install elsewhere?

**Comment by adamjstewart** [comment]
To uninstall Spack simply delete the repo you cloned and delete the `~/.spack` directory if one exists.
