### ISSUE TITLE
Spack-Trilinos needs dialing UVM option for CUDA

### ISSUE THREAD

**Issue by keitat** [LLNL/spack#28869]
### Summary

Since 13.2.0, Trilinos is removing UVM options for CUDA build because of the performance issues.  

See line 736-:
```
            if '+cuda' in spec:
                options.extend([
                    define_kok_enable('CUDA_UVM', True),
                    define_kok_enable('CUDA_LAMBDA', True),
                    define_kok_enable('CUDA_RELOCATABLE_DEVICE_CODE', 'cuda_rdc')
                ])
                arch_map = Kokkos.spack_cuda_arch_map
                options.extend(
                    define("Kokkos_ARCH_" + arch_map[arch].upper(), True)
                    for arch in spec.variants['cuda_arch'].value
                )
```

I suggest disabling UVM option for 13.2 or later.

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by keitat** [comment]
@sethrj I cannot assign the task to myself and other people.

**Comment by psakievich** [comment]
@jrood-nrel we should track this change for exawind.
