### ISSUE TITLE
Installation issue: rocksdb conflicts with lua in environment

### ISSUE THREAD

**Issue by mdorier** [LLNL/spack#28884]
### Steps to reproduce the issue

Use the following spack.yaml file:

```
spack:
  specs:
  - lua
  concretization: together
```

Do the following:

```
$ spack env create myenv spack.yaml
$ spack env activate myenv
$ spack install
$ spack env deactivate
$ spack env activate myenv
$ spack add rocksdb
$ spack install
```

RocksDB will fail with the following error:

```
Makefile:442: *** Cannot find lualib.h under /home/mdorier/lua-test/spack/var/spack/environments/myenv/.spack-env/view/lib/lua/5.3/?/init.lua;/home/mdorier/lua-test/spack/var/spack/environments/myenv/.spack-env/view/lib/lua/5.3/?.lua;/home/mdorier/lua-test/spack/var/spack/environments/myenv/.spack-env/view/share/lua/5.3/?/init.lua;/home/mdorier/lua-test/spack/var/spack/environments/myenv/.spack-env/view/share/lua/5.3/?.lua/include.  Try to specify both LUA_PATH and LUA_INCLUDE manually.  Stop.
```

It seems that even though the rocksdb package doesn't depend on lua, the rocksdb Makefile looks for LUA_PATH, which happens to be defined in the context of this environment. The path to which it is defined by spack seems weird, however. It has a "?". The LUA_CPATH environment variable is also defined by spack and also has a "?" in it.

One possible solution would be to make sure LUA_PATH and LUA_CPATH are unset during the install phase of rocksdb, but this problem may be hiding some other issues. I don't know whether the lua package itself has a problem in setting these paths, and I don't know why rocksdb is looking for lua. Rocksdb is also suggesting we set LUA_INCLUDE so maybe that's something missing from the lua package. But I'm also uneasy about the fact that rocksdb could build differently depending on the presence or absence of another package in the active environment...

### Information on your system

* **Spack:** 0.17.1-1150-389b24c4dc
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-sandybridge
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by mdorier** [comment]
@trws, @adamjstewart, @alalazo, sorry to put you on the spot but the Lua package has no maintainer and you seem to be the persons who authored this function: https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/lua/package.py#L155

Could you tell me why the "?" in all these paths? I've been having the issue above with rocksdb for the past 2 years, not being able to have rocksdb in any environment that has Lua in it, and it's becoming more critical that I solve this. I don't know why rocksdb's Makefile is looking for Lua even though it doesn't need it, but I'm trying to cover all the angles to see if I can fix this, either via the Lua package, or via RocksDB's.

Also I have the impression (I have to double-check) that these variables remain set when deactivating an environment, which can then pollute other environments.

**Comment by adamjstewart** [comment]
Sorry, I don't know anything about Lua.

**Comment by trws** [comment]
The `?` in a lua path is the substitution point, it gets replaced by the module name when searching for a lua module. Also the semicolons are, sadly, the required separator between paths in lua’s path env vars. This looks like an unfortunate case of the same env var name being used for two different purposes, and a badly written makefile. The easiest solution to this problem is to add a `setup_build_environment` method to the rocksdb package that clears `LUA_PATH` only for the build of that package. It has to be set for lua modules to work, so that’s almost certainly the least fallout fix.

**Comment by mdorier** [comment]
Oh I see, so the Lua package is correct. I'll try to fix the rocksdb package. Thanks!
