### ISSUE TITLE
root: lib/cppyy_backend/etc not writable

### ISSUE THREAD

**Issue by wdconinc** [LLNL/spack#28899]
### Steps to reproduce

```console
spack install root+python
python -c "import cppyy"
```

### Error message

```console
Python 3.9.10 (main, Feb  2 2022, 13:32:35) 
[GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cppyy
(Re-)building pre-compiled headers (options: -O2 -mavx); this may take a minute ...
/opt/local/bin/python: can't open file '/opt/software/linux-ubuntu21.10-skylake/gcc-11.2.0/root-6.24.06-htb5u3m4n322leld3w2usgnj2nwdfrts/lib/cppyy_backend/etc/dictpch/makepch.py': [Errno 2] No such file or directory
/opt/software/linux-ubuntu21.10-skylake/gcc-11.2.0/root-6.24.06-htb5u3m4n322leld3w2usgnj2nwdfrts/lib/cppyy_backend/loader.py:113: UserWarning: No precompiled header available (failed to build); this may impact performance.
  warnings.warn('No precompiled header available (%s); this may impact performance.' % msg)
```

This can be resolved by a `symlink(self.prefix.etc,join_path(self.prefix.lib,'cppyy_backend/etc))` but I'm not sure it is the appropriate solution. It is possible that instead a PYTHON environment variable should point to `self.prefix.etc`.

### Information on your system

* **Spack:** 0.17.1-1123-a1f69e130c
* **Python:** 3.9.7
* **Platform:** linux-ubuntu21.10-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by wdconinc** [comment]
Maintainers: @HadrienG2 @chissg @drbenmorgan @vvolkl

**Comment by vvolkl** [comment]
Hi @wdconinc,

apologies for the delayed response. I can confirm I see this warning with my installations too, but am not sure how serious it is. Some observations: 
* the warning is not shown when importing ROOT before cppyy, i.e. 

```
spack install root+python
python -c "import ROOT; import cppyy"
```
* When downloading the binaries from the ROOT home page and sourcing `thisroot.sh` (in which case there is no warning), `self.prefix.etc` does not seem to be added to any python paths. But `CLING_STANDARD_PCH` is set to `none`, which also removes the warning  also for the spack installations.

I'll have to ask some colleagues what happens here exactly, but I think we can safely add this variable to the run environment of ROOT as it just emulates what is done in `thisroot.sh`

**Comment by wdconinc** [comment]
> but am not sure how serious it is.

Isn't there some fundamental law that given a large enough user base any bug will be serious for someone? ;-)

**Comment by wdconinc** [comment]
I was thinking of Hyrum's law: "With a sufficient number of users of an API, it does not matter what you promise in the contract: all observable behaviors of your system will be depended on by somebody."

**Comment by wdconinc** [comment]
@vvolkl Are you still seeing this still, or have you implemented any of the solutions you identify in [key4hep-spack](https://github.com/key4hep/key4hep-spack)?

**Comment by vvolkl** [comment]
Still an issue, thanks for the reminder - opened a PR with a fix now.
