### ISSUE TITLE
Installation issue: llvm-amdgpu

### ISSUE THREAD

**Issue by fluidnumericsJoe** [LLNL/spack#28906]
### Steps to reproduce the issue

```console
spack install llvm-amdgpu
```

### Information on your system

```
$ spack debug report
* **Spack:** 0.17.1-1167-d4394d502f
* **Python:** 3.9.7
* **Platform:** linux-pop21-icelake
* **Concretizer:** clingo
```

### Additional information

[spack-build-out.txt](https://github.com/spack/spack/files/8054545/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/8054546/spack-build-env.txt)

@arjun-raj-kuppala 
@haampie 
@srekolam 

This issue appears to be related to the removal of `cyclades.h` from the Linux kernel headers and is more of an issue with the llvm-amdgpu source code. [This ticket on GCC](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100379) suggests the includes for cyclades.h can be simply removed and perhaps a spack patch may help resolve this issue. It looks like https://github.com/ROCm-Developer-Tools/llvm-project hasn't had any major activity for some time, so a patch may be the only route forward unless the llvm-project sees an update.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by srekolam** [comment]
this was reported sometime ago #26861
Here the LLVM commit that fixes the issue: https://github.com/llvm/llvm-project/commit/68d5235cb58f988c71b403334cd9482d663841ab
You could try to C-P this fix or wait for ROCm 5.0 which i am currently working to update now.

**Comment by fluidnumericsJoe** [comment]
@srekolam if older versions of llvm-amdgpu are offered through spack, we really ought to put in patches for those versions so they can be installed on OS's that removed cyclades. Otherwise, this error will still afflict some users. 

Alternatively, OS version requirements need to be strictly enforced for older versions of ROCm that are incompatible with newer OS

**Comment by srekolam** [comment]
submitted the patch for llvm-amdgpu for 4.2.0 till 4.5.2  #29376
