### ISSUE TITLE
Update for package parmgridgen for darwin platforms

### ISSUE THREAD

**Issue by burgreen** [LLNL/spack#28902]
### Summary

$ spack --version
0.17.1-1158-af4d555c20

I have attached an updated package.py and a patch_darwin.txt files that builds successfully on darwin. 

[patch_darwin.txt](https://github.com/spack/spack/files/8054083/patch_darwin.txt)
[package.py.txt](https://github.com/spack/spack/files/8054085/package.py.txt)

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by tgamblin** [comment]
Please submit this as a pull request.
