### ISSUE TITLE
"No satisfying compiler available is compatible with a satisfying os", OpenSuse Tumbleweed

### ISSUE THREAD

**Issue by brenthuisman** [LLNL/spack#28911]
### Steps to reproduce

Although I've tried to setup Spack before with the advised instructions, I just did again with a fresh checkout so see if anything had changed.
```
git clone -c feature.manyFiles=true https://github.com/spack/spack.git
cd spack/bin
./spack install libelf
```

### Error message

The output of `./spack install libelf` is:
```
==> Bootstrapping clingo from pre-built binaries
==> Bootstrapping clingo from sources
[+] /usr (external bison-3.8.2-56ovsszgkcpnuzwzgntdmohdi3366vhd)
[+] /usr (external cmake-3.22.2-eu4vcnjbksf2bvlizbavl2cw423au5u2)
[+] /home/brent/venv (external python-3.10-nxlxbijy2d757frxkekjc2tvaojogamz)
[+] /home/brent/.spack/bootstrap/store/linux-opensuse_tumbleweed20220207-x86_64/gcc-11.2.1/re2c-2.2-gskxehtk4hikpycwoyurcpxqiwi3f4j6
==> Installing clingo-bootstrap-spack-j7zgz22q2dhsekvddoi5x6g47qgy76bn
==> No binary for clingo-bootstrap-spack-j7zgz22q2dhsekvddoi5x6g47qgy76bn found: installing from source
==> Ran patch() for clingo-bootstrap
==> clingo-bootstrap: Executing phase: 'cmake'
==> clingo-bootstrap: Executing phase: 'build'
==> clingo-bootstrap: Executing phase: 'install'
==> clingo-bootstrap: Successfully installed clingo-bootstrap-spack-j7zgz22q2dhsekvddoi5x6g47qgy76bn
  Fetch: 7.44s.  Build: 1m 20.69s.  Total: 1m 28.13s.
[+] /home/brent/.spack/bootstrap/store/linux-opensuse_tumbleweed20220207-x86_64/gcc-11.2.1/clingo-bootstrap-spack-j7zgz22q2dhsekvddoi5x6g47qgy76bn
==> Error: libelf is unsatisfiable, errors are:
  No satisfying compiler available is compatible with a satisfying os

    To see full clingo unsat cores, re-run with `spack --show-cores=full`
    For full, subset-minimal unsat cores, re-run with `spack --show-cores=minimized
    Warning: This may take (up to) hours for some specs
```
The error, `No satisfying compiler available is compatible with a satisfying os`, does not occur in the bug tracker. I actually have current compilers available (see next point) and my system is pretty current (Opensuse Tumbleweed recently updated).

### Information on your system

`./spack debug report`:
```
* **Spack:** 0.17.1-1167-2c56cbd2bc
* **Python:** 3.10.2
* **Platform:** linux-opensuse_tumbleweed20220207-skylake
* **Concretizer:** clingo
```
`./spack compilers`:
```
==> Available compilers
-- clang opensuse_tumbleweed20220101-x86_64 ---------------------
clang@13.0.0  clang@12.0.1

-- gcc opensuse_tumbleweed20220101-x86_64 -----------------------
gcc@11.2.1  gcc@10.3.1
```
The following command fixes this problem:
`./spack compiler find`

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
See https://github.com/spack/spack/pull/28912 The issue is very likely `tumbleweed` detection which brings a date in the name of the operating system.

**Comment by alalazo** [comment]
The other pieces of the puzzle are #28042 (which possibly removed an automated search of compilers for the new `tumbleweed`, thus revealing the bug) and having a previous configuration in the user scope.

I think if you disable the global configs like done [here](https://spack.readthedocs.io/en/latest/configuration.html#overriding-local-configuration) a fresh clone should work as documented.

**Comment by brenthuisman** [comment]
I nuked my Spack dir and `~/.spack`, and this time `./spack compiler find` was not required!

`~/.spack` was created with a checkout after #28042 was merged, so maybe another merge fixed this in the meantime...
