### ISSUE TITLE
Automatically generate a complete package.py that can be compiled successfully

### ISSUE THREAD

**Issue by simon28li** [LLNL/spack#28910]
### Summary

At present, the writing of package.py is to manually add additional dependencies, patches, special environment variables, compilation parameters and so on after generating template files, whether it is possible to automatically generate a complete package.py that can be compiled successfully, so that the efficiency of enabling software can be greatly improved.

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
Unclear what you're asking

**Comment by simon28li** [comment]
@haampie 
For example, when I execute the command `spack create xxx (url) `, spack can automatically identify additional dependencies, patches, special environment variables, compilation parameters, etc., without additional manual operation, is it too difficult to implement?

**Comment by haampie** [comment]
you can't know that :man_shrugging:
