### ISSUE TITLE
OpenSSL should depends_on("perl", type="build")

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#2900]
There's a comment in the openssl package.py noting that it also requires "make" and "perl".

It needs more than just "perl", it also needs (at least) "Test::More", which some distro's (cough CentOS cough) have teased out of the perl package.

My minimal-oid dev image happens to have `/usr/bin/perl`, but not `Test::More`.  I'm not sure why this has worked in the past, probably because I've had a linuxbrew tree on my path that gave me a more modern perl (Does that make me a package manager traitor?).

Just checking if there's a reason to not add the dependency.

If there's no problem I'll submit a PR.

**Comment by adamjstewart** [comment]
I've also run into a lot of packages that say they need Perl, when really they need Perl + some common Perl module. If this module doesn't come with Spack's vanilla Perl package, adding the Perl dependency actually makes things worse. I'm not saying this is the case for openssl, but we should really make Perl extendable one of these days so we can add a few common modules.

**Comment by hartzell** [comment]
This is independent of making Perl extendable.

`Test::More` is part of the core Perl distribution, and has been for a long, long time.  

The problem is that CentOS broke the core Perl into a bunch of separate packages, so it's possible to have "perl installed" but not *really* have perl installed (most of the traditional core bits are missing).

OpenSSL seems to check that it has a perl (in my dev box it discovers `/usr/bin/perl`) and if it finds one it assumes that things will be fine.  This goes ok for a while but when it start's running its tests (which `use Test::More`), things go sour (sadly, not in the whisky sense, though this perl often threatens to drive me to drink).

**Comment by luigi-calori** [comment]
Hi, something similar happened to me when I had to build intltool ( needed for vte, a component of lxde-lxterminal ) on a CentOS.  
That package needed perl extended with xml-parser that does not come with spack-installed perl

I managed to make the install, but the extension does not follow the spack policy of keeping things separate:
It seems that (at least this ) perl extensions installs themselves into perl install folder.

I think that this imply it is not possible to uninstall them ( if you do not uninstall per itself )
I had also to modify sbang in order to overcome intltool usage.

I have a ready PR for that, ok to submit?

**Comment by hartzell** [comment]
> Hi, something similar happened to me when I had to build intltool ( needed for vte, a component of lxde-lxterminal ) on a CentOS.
> That package needed perl extended with xml-parser that does not come with spack-installed perl
> [...]

That's *not* similar to the problem that this PR addresses.

- *This* problem is that CentOS's perl is missing some of its standard parts -- fixing it just requires installing an intact standard perl.
- *The problem you saw with intltool* requires adding modules beyond those in the Perl core (the problem that @adamjstewart mentions above).

I'd love to see a description of your solution to the "additional modules" problem (or a PR if it's already implemented).

**Comment by luigi-calori** [comment]
@hartzell :  As I mentioned, I simply added the extension as a package that depends on perl and install the perl extension in the default way, resulting in an installation within the depending perl spack install tree that is changed by this.

This means that you can not have within spack, two version of the same perl extension sharing the same perl.

II did not made it as a real perl extensions in the spack sense ( you can not activate it )

 I have already a [pr ready](https://github.com/RemoteConnectionManager/spack/tree/pr/intltool_deps):

I just need to rebase to the current development, if you think that this could be of any use to you or others.

from [this post](https://perlmaven.com/how-to-change-inc-to-find-perl-modules-in-non-standard-locations)  it seems that throug env var, perl could be instructed to look into non-standard folders for modules, but I do not feel confident to go the spack extension route without any support from someone with grater spack insight.

**Comment by adamjstewart** [comment]
@luigi-calori I think we'll want to go down the route of making Perl fully extendable. It hopefully shouldn't be too much work. Just take a look at the Python package to see how it was done there. Especially the setup_* and (de)activate methods. If you start a PR, other contributors can guide you in the right direction.

**Comment by adamjstewart** [comment]
@hartzell Sorry for hijacking your thread. Feel free to submit a PR adding the Perl dependency to OpenSSL.

**Comment by adamjstewart** [comment]
Closed by #2909.
