### ISSUE TITLE
Qt fails to build with XCode 8 on Sierra

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#2903]
subj, with 
```
   Xcode not set up properly. You may need to confirm the license
   agreement by running /usr/bin/xcodebuild without arguments.
```
Perhaps while copying  Xcode to inject compiler wrappers, one should do
```
ln -s xcodebuild xcrun
```
(see http://stackoverflow.com/questions/39492617/xcode-8-error-project-error-xcode-not-set-up-properly-even-though-the-licens)

Similar issue on macPorts https://trac.macports.org/ticket/52200

@mathstuf did you see that error before?

**Comment by mathstuf** [comment]
No, I still only have Xcode 7 and 10.10 on the Apple machines that I typically use.
