### ISSUE TITLE
Build issue: diffutils@3.8%nvhpc

### ISSUE THREAD

**Issue by kwryankrattiger** [LLNL/spack#29084]
### Steps to reproduce the issue

```console
$ spack install diffutils@3.8%nvhpc@22.1
```

### Error message

<details><summary>Error message</summary><pre>
"/tmp/ryan.krattiger/spack-stage/spack-stage-diffutils-3.8-zwu4ukysjtqv7k43y2c5z2aplogu5deu/spack-src/lib/malloca.c", line 52: error: 64 bits operations with signed and unsigned operands are currently unsupporte
d by __builtin_add_overflow
    if (!INT_ADD_WRAPV (n, plus, &nplus) && !xalloc_oversized (nplus, 1))
</pre></details>

### Information on your system

```
* **Spack:** 0.17.1-1264-2e86260c89
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-zen2
* **Concretizer:** clingo
```

### Additional information

[diffutils-spack-build-out.txt](https://github.com/spack/spack/files/8100655/diffutils-spack-build-out.txt)
[diffutils-spack-build-env.txt](https://github.com/spack/spack/files/8100656/diffutils-spack-build-env.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by mcuma** [comment]
I see the same error and have wandered here with the help of Google. Apparently, this is a bug in NVHPC:
https://lists.nongnu.org/archive/html/bug-diffutils/2022-01/msg00002.html

What worked for me is to use diffutils@3.7 instead.
