### ISSUE TITLE
pin version for openturns

### ISSUE THREAD

**Issue by shahzebsiddiqui** [LLNL/spack#29095]
@liuyangzhuan please have a version for openturns. Looks like there are several releases according to https://github.com/openturns/openturns/tags but version i see is `master`

https://github.com/spack/spack/blob/9e2d78cffc1beaec2c6e4c3a379c17f25a35b31f/var/spack/repos/builtin/packages/openturns/package.py#L22

Seems like you should be maintainer of this package i was trying to install `gptune` and you are the maintainer and `openturns` is a dependency for this package.

**Comment by liuyangzhuan** [comment]
Hi, @shahzebsiddiqui, I've created a PR to address this 
https://github.com/spack/spack/pull/29097
I required you as the reviewer.

**Comment by shahzebsiddiqui** [comment]
thanks @liuyangzhuan i saw it. We can close this issue once PR is merged. Ill keep an eye on this

**Comment by alalazo** [comment]
Closing since the associated PR has been merged
