### ISSUE TITLE
Installation issue: LLVM@13.0.x

### ISSUE THREAD

**Issue by crtrott** [LLNL/spack#29114]
### Steps to reproduce the issue

```console
$ spack  install llvm@13.0.0 +cuda cuda_arch=70
```

### Error message

<details><summary>Error message</summary><pre>
spack install llvm@13.0.0 +cuda cuda_arch=70
==> Warning: Missing a source id for llvm@13.0.0
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/libiconv-1.16-dh7pvqkkrh4f6emrhl7jbk6o7qisa57o
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/pkgconf-1.8.0-dl6yoge2bc5pj53lftzqi5nztbcku7tl
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/xz-5.2.5-5lu4k4rijnm7nfxlfybtejkdm34rvwzm
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/zlib-1.2.11-kghrhbarmf5klns5lt2sgguszbtf3e74
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/berkeley-db-18.1.40-gfd3ssdyirq3b3i6ysptjc7yv6jt27bh
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/libsigsegv-2.13-kwkzrqncpx6j6wyzr2jpvjntzq7zwwnp
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/util-macros-1.19.3-qtt6ylwdm3kidllhs5jxww6qwq5eknwx
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/libelf-0.8.13-merpg2gy6ldmmfvowmszi4o2vpdiwm2g
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/libffi-3.3-if2fupyeyx6h2mhodch5rcan2feztfrs
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/libmd-1.0.3-e2atdoj6zmvc6ejdzc4uvb6qlwyu6hc2
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/pcre-8.44-azbgbzqvzhx5jv2u732prbxvpcw3lslm
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/diffutils-3.7-aq3cyplbitf325oyg2ugpcavdv364irg
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/tar-1.34-hu2hbrsfh73x7lbo3ex7xbp5lbaqy5vw
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/util-linux-uuid-2.36.2-oorteedynjg3qljq4ocnpasrhdznaxcu
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/ncurses-6.2-7iedlz7upcpxeymnyeatf6d4auhhgqcb
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/libxml2-2.9.12-rjn646zid74l6f3pysrgjcusovacpxbh
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/m4-1.4.19-xjmx22uckh4rjujtczoqg3ycqc3lzlie
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/libbsd-0.11.3-7wf6pa4jzab5vri76pi7tkfqpcqe7yma
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/swig-4.0.2-wxz5odvzvfjggzbzj36x6h2kksvxh2yz
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/bzip2-1.0.8-47n4mq6oorjflm7ghn2y6geijm43ogyk
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/libedit-3.1-20210216-dcgw6jugpt7gtba7x4cnabjr5ai3uxu7
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/readline-8.1-ngtx2h4m3zqyku444323ecjepcts57ue
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/cuda-11.4.0-lig2fzcaga3dkag7k3nqsplk7elhpq24
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/libtool-2.4.6-vmgwajgdmuoirogs2kseexplcrchg65y
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/expat-2.4.1-t6rwnuh3nbn47xfluedhiti3so56ilxb
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/gettext-0.21-4hk2myl3f3agtrdl52ua34mgd3pdugob
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/sqlite-3.36.0-zcfb52mbddcaxjgi5w4n3skmiwpjrm5d
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/gdbm-1.19-c5a2opnwkwpfvxp4jnxdkdcjzrw5trjo
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/libpciaccess-0.16-ba2dkecgicmcm7jkf7vuorbunv45765u
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/binutils-2.37-zmuzheymzdijoguwulw7u5tzjxcgwhuu
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/perl-5.34.0-6t7ouqt4ojaaqofvvgp7oldjtpdh6xgw
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/hwloc-2.5.0-5knoda2wffpxn4uij77ee5zhhq2p6y5m
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/perl-data-dumper-2.173-tjrcxgsz2ugvp5bevd7nyqmowitu4tf4
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/openssl-1.1.1l-ihvb4fgj64kwb4bktfbwdqt6qmhapu5u
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/cmake-3.21.2-rp3ocfilyiikt2mdsxhiu2xn2s7qalxn
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/python-3.8.11-qyntrynd5ekgvo3o2lpx3wxa2ahqy43s
[+] /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/z3-4.8.9-mbzgxkf5eooljhvn3mvk33kpyom6dxig
==> Installing llvm-13.0.0-5arz5zpuhjl7lij4g2qss3rqp5qg5xhk
==> No binary for llvm-13.0.0-5arz5zpuhjl7lij4g2qss3rqp5qg5xhk found: installing from source
==> Warning: There is no checksum on file to fetch llvm@13.0.0 safely.
==>   Fetch anyway? [y/N] y
==> Fetching https://github.com/llvm/llvm-project/archive/llvmorg-13.0.0.tar.gz
==> No patches needed for llvm
==> llvm: Executing phase: 'cmake'
==> llvm: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

4 errors found in build log:
     16907    /home/projects/x86-64/spack/opt/spack/linux-rhel7-skylake_avx512/gcc-9.2.0/binutils-2.37-zmuzheymzdijoguwulw7u5tzjxcgwhuu/bin/ranlib -D ../../../../lib/clang/13.0.0/lib/linux/libclang_rt.ubsan_standalone-x86_64.a
     16908    [ 25%] Building CXX object projects/libcxxabi/src/CMakeFiles/cxxabi_static.dir/cxa_personality.cpp.o
     16909    cd /tmp/crtrott/spack-stage/spack-stage-llvm-13.0.0-5arz5zpuhjl7lij4g2qss3rqp5qg5xhk/spack-build-5arz5zp/projects/libcxxabi/src && /home/projects/x86-64/spack/lib/spack/env/gcc/g++ -D_GNU_SOURCE -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_DISABLE_EXTERN_TEMPLATE -D_LIBCXXABI_BUILDING_LIBRARY
               -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/crtrott/spack-stage/spack-stage-llvm-13.0.0-5arz5zpuhjl7lij4g2qss3rqp5qg5xhk/spack-build-5arz5zp/projects/libcxxabi/src -I/tmp/crtrott/spack-stage/spack-stage-llvm-13.0.0-5arz5zpuhjl7lij4g2qss3rqp5qg5xhk/spa
              ck-src/libcxxabi/src -I/tmp/crtrott/spack-stage/spack-stage-llvm-13.0.0-5arz5zpuhjl7lij4g2qss3rqp5qg5xhk/spack-build-5arz5zp/include -I/tmp/crtrott/spack-stage/spack-stage-llvm-13.0.0-5arz5zpuhjl7lij4g2qss3rqp5qg5xhk/spack-src/llvm/include -I/tmp/crtrott/spack-stage/spack-stage-llvm-1
              3.0.0-5arz5zpuhjl7lij4g2qss3rqp5qg5xhk/spack-src/libcxxabi/include -I/tmp/crtrott/spack-stage/spack-stage-llvm-13.0.0-5arz5zpuhjl7lij4g2qss3rqp5qg5xhk/spack-src/libcxxabi/../libcxx -std=c++11 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra
               -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -W
              no-comment -Wmisleading-indentation -ffunction-sections -fdata-sections  -O3 -DNDEBUG -fPIC -nostdinc++ -Werror=return-type -W -Wall -Wchar-subscripts -Wconversion -Wmissing-braces -Wunused-function -Wshadow -Wsign-compare -Wsign-conversion -Wstrict-aliasing=2 -Wstrict-overflow=4 -Wun
              used-parameter -Wunused-variable -Wwrite-strings -Wundef -Wno-suggest-override -Wno-error -pedantic -fstrict-aliasing -funwind-tables -D_DEBUG -UNDEBUG -I/tmp/crtrott/spack-stage/spack-stage-llvm-13.0.0-5arz5zpuhjl7lij4g2qss3rqp5qg5xhk/spack-build-5arz5zp/include/c++/v1 -std=c++2a -MD
               -MT projects/libcxxabi/src/CMakeFiles/cxxabi_static.dir/cxa_personality.cpp.o -MF CMakeFiles/cxxabi_static.dir/cxa_personality.cpp.o.d -o CMakeFiles/cxxabi_static.dir/cxa_personality.cpp.o -c /tmp/crtrott/spack-stage/spack-stage-llvm-13.0.0-5arz5zpuhjl7lij4g2qss3rqp5qg5xhk/spack-src/
              libcxxabi/src/cxa_personality.cpp
     16910    In file included from /tmp/crtrott/spack-stage/spack-stage-llvm-13.0.0-5arz5zpuhjl7lij4g2qss3rqp5qg5xhk/spack-build-5arz5zp/include/c++/v1/__availability:13,
     16911                     from /tmp/crtrott/spack-stage/spack-stage-llvm-13.0.0-5arz5zpuhjl7lij4g2qss3rqp5qg5xhk/spack-build-5arz5zp/include/c++/v1/optional:149,
     16912                     from /tmp/crtrott/spack-stage/spack-stage-llvm-13.0.0-5arz5zpuhjl7lij4g2qss3rqp5qg5xhk/spack-src/libcxx/src/optional.cpp:9:
  >> 16913    /tmp/crtrott/spack-stage/spack-stage-llvm-13.0.0-5arz5zpuhjl7lij4g2qss3rqp5qg5xhk/spack-build-5arz5zp/include/c++/v1/__config:1065:41: error: a destructor cannot be 'constexpr'
     16914     1065 | #  define _LIBCPP_CONSTEXPR_AFTER_CXX17 constexpr
     16915          |                                         ^~~~~~~~~
     16916    /tmp/crtrott/spack-stage/spack-stage-llvm-13.0.0-5arz5zpuhjl7lij4g2qss3rqp5qg5xhk/spack-build-5arz5zp/include/c++/v1/optional:224:5: note: in expansion of macro '_LIBCPP_CONSTEXPR_AFTER_CXX17'
     16917      224 |     _LIBCPP_CONSTEXPR_AFTER_CXX17 ~__optional_destruct_base()
     16918          |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     16919    make[2]: Leaving directory `/tmp/crtrott/spack-stage/spack-stage-llvm-13.0.0-5arz5zpuhjl7lij4g2qss3rqp5qg5xhk/spack-build-5arz5zp'

     ...
</pre></details>

Looks to me like its trying to compile LLVM with an unsupported C++ standard?

@naromero77 @trws 

### Information on your system

* **Spack:** 0.16.2-4249-c6edfa3f31
* **Python:** 3.6.8
* **Platform:** linux-rhel7-skylake_avx512
* **Concretizer:** original

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/8112692/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/8112694/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by crtrott** [comment]
Note this also happens with 13.0.1, 12.0.1 installed fine for me.

**Comment by trws** [comment]
What gcc were you using for this @crtrott?  I'm running a build in a centos7 container with devtoolset-9 to see if I can repro, but if you're using a gcc built some other way it would be good to know.

**Comment by trws** [comment]
Sadly, that did not do it.  Building with the devtoolset-9 gcc 9.3.1 compiler worked just fine.

**Comment by trws** [comment]
The solve here is update your spack, since we fixed this issue (as much as it can be fixed) in #26584. It's that libcxx can't be built with a gcc that old, and a spack as old as 0.16.2 doesn't encode that requirement.  I didn't see it in current spack because the concretizer automatically turned off the libcxx variant for gcc 9.
