### ISSUE TITLE
Proper use of install_tree in a shared installation

### ISSUE THREAD

**Issue by Try2Code** [LLNL/spack#29178]
### Summary

Setup is this: The admin of our test cluster shares his spack environment, so that users can find, inspect and load installed packages. This is also useful because I as a user don't have to care about compilers.

But as soon as I define `install_tree` (to point a directory where I have write access) in my `~/.spack/config.yml` I don't find any of the system packages anymore. I can install my own stuff based on his package definitions, but his installations are gone. 

I am aware of the upstream setting to chain spack installations. But in the above setup I don't have my own spack installation running and I would like to avoid that.

I know that there are configuration scopes and I clearly set mine the in the users scope whereas the admin used a global scope (I think). So my question is: 
- Why does my user config overwrites a more global configuration?
- Is there a proper configuration for that scenario?
- Is using `upstream` for the already known system installation a proper workaround?
- Do I misuse spack in this kind of _shared_ mode?

This is defo not a normal feature request, but it's also not a bug report or a build problem. Sorry, if I chose the wrong place

### Additional information

spack verson is 0.17.1

I will ask around in slack, but keep the description here. sry for the entropy

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by becker33** [comment]
If `/path/to/local` is the install tree you want, and `/path/to/system` is the system install tree, put in your user config directory (`~/.spack`)

```
$ cat config.yaml
config:
  install_tree:
    root: /path/to/local
$ cat upstreams.yaml
upstreams:
  system_installs:
    install_tree: /path/to/system
```

That should allow you to install packages locally without having to reproduce the upstream builds locally.

**Comment by tgamblin** [comment]
feel free to reopen if @becker33 hasn't addressed your question

**Comment by Try2Code** [comment]
perfect - thx
