### ISSUE TITLE
Renaming `graviton2` target as `neoverse-n1`

### ISSUE THREAD

**Issue by fspiga** [LLNL/spack#29171]
### Summary

I am working on NVIDIA Arm HPC Developer Kit (https://developer.nvidia.com/arm-hpc-devkit) which is equipped with Ampere Computing 'Altra' CPU.

When running spack (any recent released tags and giot head), the CPU is recornised as `graviton2` despite it is not. This is what I get on an internal deployment:
```
[filippos@amp001 ~]$ spack arch -f
linux-rocky8-graviton2
[filippos@amp001 ~]$ spack arch -b
linux-rocky8-graviton2
```

Spack version: `0.17.1-1338-fddc58387c`

### Rationale

`graviton2` is not the only Arm-based CPU supporting Arm Neoverse N1 core IP. See https://www.anandtech.com/show/15578/cloud-clash-amazon-graviton2-arm-against-intel-and-amd and  https://www.anandtech.com/show/15575/amperes-altra-80-core-n1-soc-for-hyperscalers-against-rome-and-xeon

Since two Arm-based CPUs are based on the same Arm Core IP, it is very hard to distinguish them based on what linux reports. Spack does nothing wrong here, it looks at "Features" listed in `/proc/cpuinfo`. However the list of supported CPU uarch features support by AWS Graviton2 and Ampere Compouting Altra are the same

Graviton2:
```
$ cat /proc/cpuinfo | grep "Features"
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
```

Ampere Computing Altra:
```
$ cat /proc/cpuinfo | grep "Features"
Features        : fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm lrcpc dcpop asimddp ssbs
```

### Description

Rename target `graviton2` to `neoverse-n1`. 

### Additional information

In practice, nothing breaks at the moment. However it can be confusing for a non-experienced user to see spack recornising "graviton2"  as target when running on system with Ampere Computing Altra CPU.

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
Can you move this discussion to https://github.com/archspec/archspec-json/issues ?

**Comment by fspiga** [comment]
Done (I miss the notification somehow)

**Comment by alalazo** [comment]
Closing this issue then.
