### ISSUE TITLE
Fetching not up-to-date versions fails

### ISSUE THREAD

**Issue by manuelakuhn** [LLNL/spack#29204]
### Steps to reproduce

I am not sure if this is a R problem or a general one but I only encountered it for R packages so far.

It seems that R packages which have a newer version on cran (for bioconductor I did not check) cannot be built due to missing sources. This only affects packages where the sources are not yet in the spack mirror.

E.g. `r-cli`:

Package in spack: version 3.1.1
newest version on cran: 3.2.0 (see PR #29005)

When installing

```
$ spack install r-cli
==> Installing r-cli-3.1.1-xncfrt777mkotgp7lncpsf7pxrdurqjz
==> No binary for r-cli-3.1.1-xncfrt777mkotgp7lncpsf7pxrdurqjz found: installing from source
==> Error: FetchError: All fetchers failed for spack-stage-r-cli-3.1.1-xncfrt777mkotgp7lncpsf7pxrdurqjz
```

I could reproduce this for `r-rlang` (open PR #29040).

For packages like `r-foreach` (PR #29062) where there is a newer version on cran but the old sources are already in the mirror this problem does not occur.

Additional examples:

no mirror -> fail:
`r-future`
`r-jsonlite`
`r-quantreg`
`r-tinytex`
`r-yaml`

mirror -> work:
`r-colorspace`
`r-clipr`
`r-crayon`
`r-evaluate`
`r-generics`

Disabling the spack mirror results in all of these to fail as well.

Possible reason:
New packages are found under in this case`https://cloud.r-project.org/src/contrib/` and are moved to `https://cloud.r-project.org/src/contrib/Archive/` [2] once a newer release is available. If the newest version in spack is not equal to the newest version on cran, spack looks in [1] although the sources can now only be found in [2].

This is similar to the `spack checksum` issues in #26977

Side note: 
I found two outlier: `r-glue` and `r-mgcv`: 
<https://cloud.r-project.org/src/contrib/glue_1.6.1.tar.gz> and <https://cloud.r-project.org/src/contrib/mgcv_1.8-38.tar.gz> still work although there is a newer version on cran.

ping @glennpj @adamjstewart @bernhardkaindl

### Information on your system

* **Spack:** 0.17.1-1357-d62b8f0bf3
* **Python:** 3.8.10
* **Platform:** linux-fedora32-haswell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by glennpj** [comment]
@manuelakuhn Can you try #29250 and see if it resolves the issue for you?

**Comment by glennpj** [comment]
@manuelakuhn Ignore my PR, #29250 and try #29258 as @trws has a proper fix for the issue.

**Comment by manuelakuhn** [comment]
@glennpj @trws I can confirm that #29258 fixes the problem for me for all of the packages mentioned above.
