### ISSUE TITLE
--reuse does not reuse versions known in the db, but unknown in package.py

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#29201]
### Steps to reproduce

I tried to explicitly add cray-mpich by hand in the db, but realized later the version was not registered in package.py.

This prevents spack from picking it up with --reuse; it will always use a known version from package.py.

### Information on your system

.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
Didn't help to put `packages:cray-mpich:version: [x.y.z]` in packages.yaml, it switched to mpich, for some reason, even though cray-mpich is preferred.

**Comment by haampie** [comment]
Also does not reuse `target=x86_64` on haswell, it seems.

**Comment by alalazo** [comment]
Reproduced using Spack at cd0b6b90881126c73f050ba3b29e0cc570827f10 using `libpng`:
```console
$ spack install zlib
==> Installing zlib-1.2.12-5cwlotgbzgsqhwnb6anfbab4oh5ihhl3
==> No binary for zlib-1.2.12-5cwlotgbzgsqhwnb6anfbab4oh5ihhl3 found: installing from source
==> Using cached archive: /home/culpo/PycharmProjects/spack/var/spack/cache/_source-cache/archive/91/91844808532e5ce316b3c010929493c0244f3d37593afd6de04f71821d5136d9.tar.gz
==> Applied patch /home/culpo/PycharmProjects/spack/var/spack/repos/builtin/packages/zlib/configure-cc.patch
==> zlib: Executing phase: 'install'
==> zlib: Successfully installed zlib-1.2.12-5cwlotgbzgsqhwnb6anfbab4oh5ihhl3
  Fetch: 0.01s.  Build: 2.00s.  Total: 2.01s.
[+] /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu20.04-icelake/gcc-9.4.0/zlib-1.2.12-5cwlotgbzgsqhwnb6anfbab4oh5ihhl3

$ spack find
==> 1 installed package
-- linux-ubuntu20.04-icelake / gcc@9.4.0 ------------------------
zlib@1.2.12

[ Delete v1.2.12 from zlib/package.py ]

$ spack spec --reuse libpng
==> Warning: using "zlib@1.2.11" which is a deprecated version
Input spec
--------------------------------
libpng

Concretized
--------------------------------
libpng@1.6.37%gcc@9.4.0 arch=linux-ubuntu20.04-icelake
    ^zlib@1.2.11%gcc@9.4.0+optimize+pic+shared arch=linux-ubuntu20.04-icelake
```
