### ISSUE TITLE
Installation issue: py-pip in environments not working...

### ISSUE THREAD

**Issue by flxmr** [LLNL/spack#29237]
### Steps to reproduce the issue

So, some packages have explicit pip-dependencies. Now, in a view, this pip does not properly get linked into the fs-hierarchy and thus it's broken, because it's somehow using the python-provided pip partly, which usually is not compatible...

### Error message

```
myhost $ ls -l myviev/lib/python3.8/site-packages/
lrwxrwxrwx  1   181 Feb 26 11:47 __init__.py -> /home/private_software/spack_21Q4/opt/spack/linux-debian10-skylake_avx512/gcc-8.5.0/python-3.8.8-ssvtjfeasmu7dnxoobltatu7pqdxszlj/lib/python3.8/site-packages/pip/__init__.py
drwx------ 16 26 Feb 26 11:47 _internal
lrwxrwxrwx  1  181 Feb 26 11:47 __main__.py -> /home/private_software/spack_21Q4/opt/spack/linux-debian10-skylake_avx512/gcc-8.5.0/python-3.8.8-ssvtjfeasmu7dnxoobltatu7pqdxszlj/lib/python3.8/site-packages/pip/__main__.py
drwx------  2    4 Feb 26 11:47 __pycache__
lrwxrwxrwx  1  179 Feb 26 11:47 py.typed -> /home/private_software/spack_21Q4/opt/spack/linux-debian10-skylake_avx512/gcc-8.5.0/py-pip-21.3.1-ldlhndk5wevzhqoo7jorwkyvvcguarzm/lib/python3.8/site-packages/pip/py.typed
drwx------ 23  32 Feb 26 11:47 _vendor
```
This leads to:
```
ImportError: cannot import name 'InvalidSchemeCombination' from 'pip._internal.exceptions' (/home//private_software/spack_21Q4/var/spack/environments/ml-21Q4/.spack-env/view/lib/python3.8/site-packages/pip/_internal/exceptions.py)
```

### Information on your system

* **Spack:** 0.17.1
* **Python:** 3.7.3
* **Platform:** linux-debian10-cascadelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by flxmr** [comment]
Reverting before this: https://github.com/spack/spack/pull/27798 makes it work again.

**Comment by adamjstewart** [comment]
I have a few suggestions that you can try. These are partly potential workarounds and partly debugging questions.

1. Instead of using `pip install` can you try `python -m pip install`?
2. Can you try using `python~ensurepip` instead of the default `python+ensurepip`?
3. Can you try the following patch?

```patch
diff --git a/lib/spack/spack/build_systems/python.py b/lib/spack/spack/build_systems/python.py
index b3552f0337..fa79ccad8b 100644
--- a/lib/spack/spack/build_systems/python.py
+++ b/lib/spack/spack/build_systems/python.py
@@ -40,7 +40,7 @@ class PythonPackage(PackageBase):
     install_time_test_callbacks = ['test']
 
     extends('python')
-    depends_on('py-pip', type='build')
+    depends_on('py-pip', when='^python~ensurepip', type='build')
     # FIXME: technically wheel is only needed when building from source, not when
     # installing a downloaded wheel, but I don't want to add wheel as a dep to every
     # package manually
```

I believe the issue is that `python+ensurepip` installs pip in the site-packages directory, and Spack packages also have a build dep on `py-pip` which installs a second copy. Since these two versions aren't guaranteed to match, you end up with conflicting files in the symlink tree. Not sure the best way to fix this. Another option would be to force particular versions of Python to use particular versions of pip.

**Comment by flxmr** [comment]
That sounds like a reasonable explanation and should fix the thing as long as I either build python with `python~ensurepip` or don't have any dependencies on `py-pip` in any of the other packages in the environment...

To answer your questions:
1) do that already
2) that works!
3) that doesn't work, if any package drags in `py-pip` as a dependency. Which for example tensorflow (thanks here for pulling that up to 2.7 btw!) does and needs (because it inherits from the plain `Package`).

Probably the easiest thing for now to let people not run into this would be to make `py-pip` conflict with `python+ensurepip`. Or change the environment setup to overwrite files from the base-install.

**Comment by flxmr** [comment]
It seems it also fixes this: https://github.com/spack/spack/issues/29206. Question is why?
