### ISSUE TITLE
Properly define the meaning of x.satisfies(y, strict).

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#29248]
From the `Spec.satisfies` docstring:

```python
        """Determine if this spec satisfies all constraints of another.

        There are two senses for satisfies:

          * `loose` (default): the absence of a constraint in self
            implies that it *could* be satisfied by other, so we only
            check that there are no conflicts with other for
            constraints that this spec actually has.

          * `strict`: strict means that we *must* meet all the
            constraints specified on other.
        """
```

Formally abstract specs can be identified with subspaces of the solution space, and concrete specs can be identified with singletons in the solution space. Concretization comes down to picking an optimal element from the subspace of abstract input specs.

Then `x.satisfies(y, strict=False)` _should_ be defined as `x` and `y` have a non-empty intersection, i.e. `x ∩ y ≠ ∅`.

and similarly `x.satisfies(y, strict=True) `_should_ be defined as `x` is a subset of `y`, i.e. `x ⊆ y`.

However, they don't behave in this way currently.

- Not all `satisfy` methods implement `strict=True/False`:
- `Version.satisfies` is not commutative, but it should
   ```python
   >>> spack.version.ver('3.8.1').satisfies(spack.version.ver('3.8'))
   True
   >>> spack.version.ver('3.8').satisfies(spack.version.ver('3.8.1'))
   False
   ```
   This should be `False` in both cases, since these are concrete versions i.e. singletons and not equal.
- `VersionRange.satisfies` is not commutative (fixed in #29209)

I think Spack would be much easier to follow if these concepts were formalized as above, so they don't leave room for discussion or interpretation.

**Comment by alalazo** [comment]
Fixed in #35681
