### ISSUE TITLE
Error bootstrapping Spack on Cray/HPE Apollo 80

### ISSUE THREAD

**Issue by quellyn** [LLNL/spack#29249]
### Steps to reproduce

We use Spack environments in our software builds. I have been testing #28556 for @alalazo and have had great success with all but one platform: Cray/HPE Apollo 80. The sequence of events are as follows.

1. Clean up and activate my Spack environment:
```console
$ module purge
$ source ./spack/share/spack/setup-env.sh
$ spack env activate -d ./ENV/CCE/
$ spack clean -ab
```

2. Make sure that Spack detects the compilers specified within my [compilers.yaml](https://github.com/spack/spack/files/8157041/compilers.yaml.txt):
```
$ spack compiler list
==> Available compilers
-- cce rhel8-aarch64 --------------------------------------------
cce@12.0.3

-- gcc rhel8-aarch64 --------------------------------------------
gcc@9.4.0
```

4. Next, run a command that invokes the bootstrapping:
```console
$ spack spec zlib
```

### Error message

[trace.txt](https://github.com/spack/spack/files/8157047/trace.txt)

### Information on your system

```console
$ spack debug report

* **Spack:** 0.17.1-1053-202e3e5654
* **Python:** 3.6.8
* **Platform:** cray-rhel8-aarch64
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
@quellyn I don't have access to any of those platforms :cry: Is this still an issue?

**Comment by quellyn** [comment]
Hi Massimiliano,We don’t have those platforms either anymore! I guess this issue can just be closed.On May 21, 2024, at 9:11 AM, Massimiliano Culpo ***@***.***> wrote:﻿
@quellyn I don't have access to any of those platforms 😢 Is this still an issue?

**Comment by alalazo** [comment]
Thanks for the prompt reply @quellyn
