### ISSUE TITLE
Unable to link to libpython using Intel Python

### ISSUE THREAD

**Issue by kgerheiser** [LLNL/spack#29255]
### Steps to reproduce

Spack uses `python -m sysconfig`, specifically the values `LDLIBRARY` and `LIBRARY`, to query the Python libs for `spec['python'].libs`. 

https://github.com/spack/spack/blob/6eef12cd1030e540b470542ee2fe405d20b001e9/var/spack/repos/builtin/packages/python/package.py#L747

https://github.com/spack/spack/blob/6eef12cd1030e540b470542ee2fe405d20b001e9/var/spack/repos/builtin/packages/python/package.py#L856

However, this doesn't work for newer versions of Intel Python on Linux. I went into the build scripts that Intel uses and found that Intel builds Python twice, once with static libraries, and once with shared libraries. The static interpreter is used, but only the shared libraries are installed. This causes Spack to look for `libpython3.a`, but it doesn't exist.

I get that this is a quirk of how Intel builds their Python distribution, but is there some sort of workaround I could use?

### Error message

```
print(json.dumps(config))
'
==> [2022-02-24-21:53:28.823817] Creating stage lock spack-stage-clingo-bootstrap-spack-ho7bogyy6ccoz5s3tmw7ypuoamazhhpj
==> [2022-02-24-21:53:28.827407] Error: RuntimeError: Unable to locate libpython3.9.a libraries in /apps/oneapi/intelpython/latest/lib

spack/var/spack/repos/builtin/packages/python/package.py:889, in libs:
        886                return LibraryList(os.path.join(macos_developerdir, ldlibrary))
        887            else:
        888                msg = 'Unable to locate {0} libraries in {1}'
  >>    889                raise RuntimeError(msg.format(ldlibrary, libdir))
        890        else:
        891            library = self.config_vars['LIBRARY']
        892
```

### Information on your system

* **Spack:** 0.17.1-1372-6eef12cd10
* **Python:** 3.9
* **Platform:** linux-ubuntu20.04-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
If you're using Intel Python, what does your `packages.yaml` look like? If you add `~shared` does that solve your issue?

**Comment by kgerheiser** [comment]
The spec looks like this:

```
  python:
    externals:
    - spec: python@3.9.7+bz2+ctypes+dbm+ensurepip+lzma+nis+pyexpat+pythoncmd~readline+sqlite3+ssl+tix+tkinter+uuid+zlib+shared
      prefix: /apps/oneapi/intelpython/python3.9
      modules:
      - intelpython/2021.3.0
```

The `~shared` option is a good thought, but it doesn't work because `LIBRARY = libpython3.a` as well, but no static library exists. Intel builds the interpreter with `--disable-shared`, deletes the static library, then builds again with `--enable-shared`, and installs the static interpreter with the shared libraries from second build.

https://github.com/spack/spack/blob/6eef12cd1030e540b470542ee2fe405d20b001e9/var/spack/repos/builtin/packages/python/package.py#L896

If it were possible to force the default config vars somehow it would work because it would fallback to `libpython3.so`.

https://github.com/spack/spack/blob/6eef12cd1030e540b470542ee2fe405d20b001e9/var/spack/repos/builtin/packages/python/package.py#L780-L818

https://github.com/spack/spack/blob/6eef12cd1030e540b470542ee2fe405d20b001e9/var/spack/repos/builtin/packages/python/package.py#L791


There aren't many packages that link to `libpython` and the intepreter works fine so it doesn't popup often. I happened to run into this trying to bootstrap Clingo from source.

**Comment by kgerheiser** [comment]
Intel says they're going to fix this.

https://community.intel.com/t5/Intel-Distribution-for-Python/libpython3-9-a-does-not-exist/td-p/1363865?emcs_t=S2h8ZW1haWx8c29sdXRpb25fdG9fcXVlc3Rpb258TDFISjJPVUM5TktVTEl8MTM3Mzc2NnxBQ0NFUFRFRF9TT0xVVElPTlN8aEs
