### ISSUE TITLE
Combining `spack urls` and `spack url-parse`

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#2926]
Does anyone mind if I combine `spack urls` and `spack url-parse` into a single command? I'm not sure how many people other than @tgamblin and I use them, but they are absolutely essential for testing our URL parsing and I'm planning on a big overhaul of how we parse names and versions.

**Comment by adamjstewart** [comment]
Basically, I'm thinking of a single command that accepts either a package name or a URL, or if neither are given, it uses every package in Spack. It then attempts to parse any URLs, reporting back what percentage of them we got "correct". It can optionally spider the web for more versions as well.

Any suggestions for names? I like `parse-urls` better than `url-parse`, and `urls` certainly isn't very descriptive.

**Comment by tgamblin** [comment]
Does't this sound like something that should be in the tests?

**Comment by adamjstewart** [comment]
Well, there will likely never be a day that we parse the URLs correctly for _every_ package, so until we get package-specific testing, I want a command to help me debug things.

**Comment by adamjstewart** [comment]
I want to know what percentage of our URLs are being parsed correctly, so that if I make a change to the URL parser, I can see how many packages were improved and how many were negatively affected.

**Comment by tgamblin** [comment]
How about something like:

```console
spack url parse <url>
spack url list
spack url test [--all | spec [...]]
```

**Comment by adamjstewart** [comment]
I noticed that the way we register subcommands for `compiler` and `repo` is very different from the way we register subcommands for `module`. Any preference between the two?

**Comment by tgamblin** [comment]
What's different?  They're both adding subparsers...

**Comment by adamjstewart** [comment]
`module` has some kind of `subcommand` callback property. Not sure what it's for.

**Comment by tgamblin** [comment]
Oh, module is just using a decorator to add each command to subcommands, whereas `compiler` and `repo` write out that dictionary in the main command method.  It's essentially the same mechanism, just depends on how you want to build up the dict of subcommands.  You can probably use either... I am not sure the decorator adds a whole lot within a simple command, but it is nice that you don't have to modify two places in the file when you add a subcommand.
