### ISSUE TITLE
Installation issue: py-fenics-dolfinx@0.1.0 can't find `-lhdf5-shared`

### ISSUE THREAD

**Issue by jomoulin** [LLNL/spack#29263]
### Steps to reproduce the issue

```console
$ spack env create fenicsx-env
$ spack env activate fenicsx-env
$ echo "  concretization: together" >> ./spack/var/spack/environments/fenicsx-env/spack.yaml
$ spack add py-fenics-dolfinx@0.1.0 %gcc@10.1.0 ^petsc+mumps+hypre cflags="-O3" fflags="-O3" ^openmpi@4.1.1
```

### Error message

<details><summary>Error message</summary><pre>
==> Error: ProcessError: Command exited with status 1:
    '/scratchm/jmoulin/TOOLS/spack/opt/spack/linux-centos7-broadwell/gcc-10.1.0/python-3.9.10-dog6ldmzldm3rcbhqfy6kp4s4jyr5gvv/bin/python3.9' '-m' 'pip' '-vvv' '--no-input' '--no-cache-dir' '--disable-pip-version-check' 'install' '--no-deps' '--ignore-installed' '--no-build-isolation' '--no-warn-script-location' '--no-index' '--prefix=/scratchm/jmoulin/TOOLS/spack/opt/spack/linux-centos7-broadwell/gcc-10.1.0/py-fenics-dolfinx-0.1.0-ixtkcez7ozj7svbmuorq2saiulrv7lil' '.'

11 errors found in build log:
     146      [ 61%] Building CXX object CMakeFiles/cpp.dir/dolfinx/wrappers/la
            .cpp.o
     147      [ 69%] Building CXX object CMakeFiles/cpp.dir/dolfinx/wrappers/lo
            g.cpp.o
     148      [ 76%] Building CXX object CMakeFiles/cpp.dir/dolfinx/wrappers/me
            sh.cpp.o
     149      [ 84%] Building CXX object CMakeFiles/cpp.dir/dolfinx/wrappers/nl
            s.cpp.o
     150      [ 92%] Building CXX object CMakeFiles/cpp.dir/dolfinx/wrappers/re
            finement.cpp.o
     151      [100%] Linking CXX shared library ../lib.linux-x86_64-3.9/dolfinx
            /cpp.cpython-39-x86_64-linux-gnu.so
  >> 152    /usr/bin/ld: cannot find -lhdf5-shared
  >> 153      collect2: error: ld returned 1 exit status
  >> 154      gmake[2]: *** [../lib.linux-x86_64-3.9/dolfinx/cpp.cpython-39-x86
            _64-linux-gnu.so] Error 1
  >> 155      gmake[1]: *** [CMakeFiles/cpp.dir/all] Error 2
  >> 156      gmake: *** [all] Error 2
     157      Traceback (most recent call last):
     158        File "<string>", line 1, in <module>
     159        File "/tmp/jmoulin/spack-stage/spack-stage-py-fenics-dolfinx-0.
            1.0-ixtkcez7ozj7svbmuorq2saiulrv7lil/spack-src/python/setup.py", li
            ne 65, in <module>
     160          setup(name='fenics-dolfinx',
     161        File "/scratchm/jmoulin/TOOLS/spack/opt/spack/linux-centos7-bro
            adwell/gcc-10.1.0/py-setuptools-59.4.0-5u5cgfp3ekuz63njujqwnwydkupe
            m6dy/lib/python3.9/site-packages/setuptools/__init__.py", line 153,
             in setup
     162          return distutils.core.setup(**attrs)

     ...

     198    Failed to build fenics-dolfinx
     199    Installing collected packages: fenics-dolfinx
     200      Created temporary directory: /tmp/pip-record-bg9htmjx
     201        Running setup.py install for fenics-dolfinx: started
     202        Running command /scratchm/jmoulin/TOOLS/spack/opt/spack/linux-c
            entos7-broadwell/gcc-10.1.0/python-3.9.10-dog6ldmzldm3rcbhqfy6kp4s4
            jyr5gvv/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokeni
            ze; sys.argv[0] = '"'"'/tmp/jmoulin/spack-stage/spack-stage-py-feni
            cs-dolfinx-0.1.0-ixtkcez7ozj7svbmuorq2saiulrv7lil/spack-src/python/
            setup.py'"'"'; __file__='"'"'/tmp/jmoulin/spack-stage/spack-stage-p
            y-fenics-dolfinx-0.1.0-ixtkcez7ozj7svbmuorq2saiulrv7lil/spack-src/p
            ython/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__f
            ile__) if os.path.exists(__file__) else io.StringIO('"'"'from setup
            tools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n
            '"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'ex
            ec'"'"'))' install --record /tmp/pip-record-bg9htmjx/install-record
            .txt --single-version-externally-managed --prefix /scratchm/jmoulin
            /TOOLS/spack/opt/spack/linux-centos7-broadwell/gcc-10.1.0/py-fenics
            -dolfinx-0.1.0-ixtkcez7ozj7svbmuorq2saiulrv7lil --compile --install
            -headers /scratchm/jmoulin/TOOLS/spack/opt/spack/linux-centos7-broa
            dwell/gcc-10.1.0/py-fenics-dolfinx-0.1.0-ixtkcez7ozj7svbmuorq2saiul
            rv7lil/include/python3.9/fenics-dolfinx
     203        running install
  >> 204    /scratchm/jmoulin/TOOLS/spack/opt/spack/linux-centos7-broadwell/gcc
            -10.1.0/py-setuptools-59.4.0-5u5cgfp3ekuz63njujqwnwydkupem6dy/lib/p
            ython3.9/site-packages/setuptools/command/install.py:34: Setuptools
            DeprecationWarning: setup.py install is deprecated. Use build and p
            ip and other standards-based tools.
     205          warnings.warn(
     206        running build
     207        running build_py
     208        creating build
     209        creating build/lib.linux-x86_64-3.9
     210        creating build/lib.linux-x86_64-3.9/dolfinx

     ...

     314        [ 61%] Building CXX object CMakeFiles/cpp.dir/dolfinx/wrappers/
            la.cpp.o
     315        [ 69%] Building CXX object CMakeFiles/cpp.dir/dolfinx/wrappers/
            log.cpp.o
     316        [ 76%] Building CXX object CMakeFiles/cpp.dir/dolfinx/wrappers/
            mesh.cpp.o
     317        [ 84%] Building CXX object CMakeFiles/cpp.dir/dolfinx/wrappers/
            nls.cpp.o
     318        [ 92%] Building CXX object CMakeFiles/cpp.dir/dolfinx/wrappers/
            refinement.cpp.o
     319        [100%] Linking CXX shared library ../lib.linux-x86_64-3.9/dolfi
            nx/cpp.cpython-39-x86_64-linux-gnu.so
  >> 320    /usr/bin/ld: cannot find -lhdf5-shared
  >> 321        collect2: error: ld returned 1 exit status
  >> 322        gmake[2]: *** [../lib.linux-x86_64-3.9/dolfinx/cpp.cpython-39-x
            86_64-linux-gnu.so] Error 1
  >> 323        gmake[1]: *** [CMakeFiles/cpp.dir/all] Error 2
  >> 324        gmake: *** [all] Error 2
     325        Traceback (most recent call last):
     326          File "<string>", line 1, in <module>
     327          File "/tmp/jmoulin/spack-stage/spack-stage-py-fenics-dolfinx-
            0.1.0-ixtkcez7ozj7svbmuorq2saiulrv7lil/spack-src/python/setup.py",
            line 65, in <module>
     328            setup(name='fenics-dolfinx',
     329          File "/scratchm/jmoulin/TOOLS/spack/opt/spack/linux-centos7-b
            roadwell/gcc-10.1.0/py-setuptools-59.4.0-5u5cgfp3ekuz63njujqwnwydku
            pem6dy/lib/python3.9/site-packages/setuptools/__init__.py", line 15
            3, in setup
     330            return distutils.core.setup(**attrs)

See build log for details:
  /tmp/jmoulin/spack-stage/spack-stage-py-fenics-dolfinx-0.1.0-ixtkcez7ozj7svbmuorq2saiulrv7lil/spack-build-out.txt

</pre></details>

### Information on your system

* **Spack:** 0.17.1-1368-8f4e029e3a
* **Python:** 2.7.5
* **Platform:** linux-centos7-broadwell
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/8161435/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/8161436/spack-build-out.txt)

@chrisrichardson 
@garth-wells 
@nate-sime 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by garth-wells** [comment]
Earlier versions of `fenics-dolfinx` won't build because of a change that was made to the Spack HDF5 package (I think in https://github.com/spack/spack/pull/18937). Spack HDF5 now builds using CMake and installs its own `hdf5Config.cmake` (or similar, HDF5 on my computer is built with autotools so I can't check at the moment). Annoyingly the HDF5 provided CMake file and the CMake provided `FindHDF5.cmake` use different target names.

DOLFINx was changed to handled this issue in https://github.com/FEniCS/dolfinx/pull/1630 (there were further HDF5/CMake improvements merged around the same time). The latest dolfinx release (0.3) should work fine (we have CI testing for building the latest release and the development version with Spack). 

You could constrain the HDF5 version and test to find a working version. We'll deprecate 0.1, 0.2, etc soon because they are early development versions so I don't think searching for and pinning the version would be a great use of time unless someone is particularly keen.

**Comment by jomoulin** [comment]
Ok, I understand. I will go with 0.3.0 and following then. Thanks for the answer !
