### ISSUE TITLE
mkl: blas_libs lists libm, libpthread and libdl incorrectly

### ISSUE THREAD

**Issue by Zzzoom** [LLNL/spack#2934]
blas_libs and lapack_libs in both MKL packages (intel-mkl and intel-parallel-studio) currently return ```libpthread.so libm.so libdl.so``` without paths, which produces linking failures in some packages that depend on blas (e.g. MUMPS).

I guess there's some reason for avoiding using ```-lpthread -lm -ldl``` and letting the linker figure paths out?

**Comment by davydden** [comment]
@Zzzoom 

> blas_libs and lapack_libs in both MKL packages (intel-mkl and intel-parallel-studio) currently return libpthread.so libm.so libdl.so without paths

the reason is that you need those to link against `mkl`. On another hand, those are system libs, so they should be found without a problem by linker in standard system directories such as `/lib`.

>  which produces linking failures in some packages that depend on blas (e.g. MUMPS).

Last time i checked `mkl` on `ubuntu16` with `gcc@5.4`, i had no problems building `mumps`. Can you be more specific about your platform/compilers/configuration?

> I guess there's some reason for avoiding using -lpthread -lm -ldl

Yes, there is. Not all packages require Blas/Lapack libs to be provided as linker flags. Sometimes you need to have full paths to libraries, sometimes library names etc. However, the `LibraryList` class will give exactly `-lpthread -lm -ldl` when asked for linking flags, of course along with `-lmk_blabla` and friends.

**Comment by davydden** [comment]
i can actually reproduce it
```
make[1]: Entering directory '/tmp/davydden/spack-stage/spack-stage-Fm7Ko_/MUMPS_5.0.2/examples'
/home/davydden/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/openmpi-2.0.1-p4mxz6d7ijxkyjwivlkulp3sgvrhtnid/bin/mpif90 -o ssimpletest -fPIC -O  ssimpletest.o  ../lib/libsmumps.so ../lib/libmumps_common.so  -L../PORD/lib/ -lpord  -L/home/davydden/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/netlib-scalapack-2.0.2-4eo45ngoknvvhiskpvcdyuvdngbgc743/lib -lscalapack /home/davydden/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/intel-mkl-11.3.3.210-phtciokkgfkddicru5txvdg5lmmifp5q/lib/intel64/libmkl_intel_lp64.so /home/davydden/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/intel-mkl-11.3.3.210-phtciokkgfkddicru5txvdg5lmmifp5q/lib/intel64/libmkl_core.so /home/davydden/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/intel-mkl-11.3.3.210-phtciokkgfkddicru5txvdg5lmmifp5q/lib/intel64/libmkl_sequential.so libpthread.so libm.so libdl.so -lpthread
gfortran: error: libpthread.so: No such file or directory
gfortran: error: libm.so: No such file or directory
gfortran: error: libdl.so: No such file or directory
```
So far it's a mystery why it worked before and does not work now. 

Regardless, i think ideally we need to find those libs and have them with the full path.

**Comment by Zzzoom** [comment]
> Yes, there is. Not all packages require Blas/Lapack libs to be provided as linker flags. Sometimes you need to have full paths to libraries, sometimes library names etc. However, the LibraryList class will give exactly -lpthread -lm -ldl when asked for linking flags, of course along with -lmk_blabla and friends.

Those aren't full paths, and even if they were the full name of the library is versioned depending on which libc is in use. But now that I know about LibraryList I understand that those are stubs to get -lpthread -lm -ldl later through ld_flags...which makes me wonder if blas_libs shouldn't just return the current blas_libs.ld_flags in the first place. Oh well.

**Comment by davydden** [comment]
> wonder if blas_libs shouldn't just return the current blas_libs.ld_flags in the first place

no, it should not. Some packages configure not with link flags but with a list of library names (`libfoo.so`->`foo`), see for example `Trilinos`).
