### ISSUE TITLE
Spack linker env makes netcdf-c believe that it doesn't support shared libraries

### ISSUE THREAD

**Issue by climbfuji** [LLNL/spack#29354]
### Steps to reproduce

This is on an HPC called Cheyenne. I used different versions of the Intel compilers (2021.2.0, installed by sysadmins; and 2022.0.2 installed with the Intel installers) with the corresponding Intel-MPI and got the same result. I also tried with netcdf-c-4.7.4 and netcdf-c-4.8.1.

When I run configure manually with those compilers loaded:
```
checking if /glade/work/heinzell/intel-oneapi-2022.1.1/mpi/2021.5.1/bin/mpicc supports -c -o file.o... (cached) yes
checking whether the /glade/work/heinzell/intel-oneapi-2022.1.1/mpi/2021.5.1/bin/mpicc linker (/usr/x86_64-suse-linux/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
```
However, if I run this through spack:
```
checking if /glade/work/heinzell/intel-oneapi-2022.1.1/mpi/2021.5.1/bin/mpicc supports -c -o file.o... (cached) yes
checking whether the /glade/work/heinzell/intel-oneapi-2022.1.1/mpi/2021.5.1/bin/mpicc linker (/glade/work/heinzell/jedi-stack/spack-stack-develop-20220215/spack/lib/spack/env/ld -m elf_x86_64) supports shared libraries... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... unsupported
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... no
checking whether to build shared libraries... no
checking whether to build static libraries... yes
```
Seems like the spack environment gets in the way here. Is there a way to modify the netcdf-c package.py to use the linker directly without going through spack?

Note. The same setup (packages, compiler versions etc.) builds shared libraries just fine on all other platforms I have tested so far (MSU Orion, NOAA RDHPC Gaea, macOS).

### Error message

See above

### Information on your system

* **Spack:** 0.17.1-1150-0cc9bdcf58
* **Python:** 3.7.9
* **Platform:** linux-sles12-broadwell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by climbfuji** [comment]
@skosukhin tagging you as the spack-netcdf expert.

**Comment by climbfuji** [comment]
More information: the exact configure command is
```
/glade/work/heinzell/jedi-stack/spack-stack-develop-20220215/cache/build_stage/spack-stage-netcdf-c-4.8.1-dy67qsy7mvpnf3nx4wwcatw7iout46zu/spack-src/configure \
--prefix=/glade/work/heinzell/jedi-stack/spack-stack-develop-20220215/envs/cheyenne2-intel-2022.0.2-all/install/intel/2022.0.2/netcdf-c-4.8.1-dy67qsy \
--enable-v2 \
--enable-utilities \
--enable-static \
--enable-largefile \
--enable-netcdf-4 \
--disable-fsync \
--enable-dynamic-loading \
--enable-shared \
--enable-dap \
--enable-parallel4 \
--disable-jna \
--disable-pnetcdf \
CC=/glade/work/heinzell/intel-oneapi-2022.1.1/mpi/2021.5.1/bin/mpicc \
--disable-hdf4 \
CFLAGS=-fPIC \
CPPFLAGS='-I/usr/include -I/glade/work/heinzell/jedi-stack/spack-stack-develop-20220215/envs/cheyenne2-intel-2022.0.2-all/install/intel/2022.0.2/hdf5-1.12.1-jdb3rmc/include' \
LDFLAGS='-L/usr/lib64 -L/glade/work/heinzell/jedi-stack/spack-stack-develop-20220215/envs/cheyenne2-intel-2022.0.2-all/install/intel/2022.0.2/hdf5-1.12.1-jdb3rmc/lib' \
LIBS='-lcurl'
```
Run through spack makes configure believe that it can't produce dynamic libraries. Run manually works fine.

If I add `LD=/something/stupid` to the configure command and run it manually, I get the same error as when I run it through spack:
```
checking if /glade/work/heinzell/intel-oneapi-2022.1.1/mpi/2021.5.1/bin/mpicc supports -c -o file.o... (cached) yes
checking whether the /glade/work/heinzell/intel-oneapi-2022.1.1/mpi/2021.5.1/bin/mpicc linker (/something/stupid -m elf_x86_64) supports shared libraries... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... unsupported
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... no
checking whether to build shared libraries... no
checking whether to build static libraries... yes
```

**Comment by climbfuji** [comment]
@skosukhin I found that on the very same machine, with the very same settings, the netcdf-c configure step says that it can't create shared libraries:
```
checking if /glade/work/heinzell/intel-oneapi-2022.1.1/mpi/2021.5.1/bin/mpicc supports -c -o file.o... (cached) yes
checking whether the /glade/work/heinzell/intel-oneapi-2022.1.1/mpi/2021.5.1/bin/mpicc linker (/glade/work/heinzell/jedi-stack/spack-stack-develop-20220215/spack/lib/spack/env/ld -m elf_x86_64) supports shared libraries... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... unsupported
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... no
checking whether to build shared libraries... no
checking whether to build static libraries... yes
```
However, the netcdf-fortran library can. It still fails linking against netcdf-c, either because of the issue I raised in https://github.com/spack/spack/discussions/29349 or because static linking isn't configured correctly to begin with, but:
```
checking if /glade/work/heinzell/intel-oneapi-2022.1.1/mpi/2021.5.1/bin/mpicc supports -c -o file.o... (cached) yes
checking whether the /glade/work/heinzell/intel-oneapi-2022.1.1/mpi/2021.5.1/bin/mpicc linker (/usr/x86_64-suse-linux/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
```
I checked the `package.py` files, both set `config_args.append('CC=%s' % self.spec['mpi'].mpicc)` so there is no difference. However, I found that netcdf-fortran has this complicated `def patch_libtool` routine, which seems to be the hot candidate for the observed different behavior.

Note also that I had to enable `force_autoreconf` for netcdf-c because of `LT_INIT` version mismatch errors.

**Comment by kgerheiser** [comment]
Getting this on Orion as well

**Comment by climbfuji** [comment]
We (mostly @kgerheiser) figured this out. We had some `LDFLAGS` set in the compielr config that worked fine when `ld` was called through the compiler, but it didn't work when `ld` was called directly (like it is the case for the `netcdf-c` and `netcdf-fortran` and other `./configure` steps).

We found better ways to set the necessary flags, thus closing this issue.
