### ISSUE TITLE
How to abort an install?

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#294]
I was looking for a method to abort the `install` routine when an error is detected. I didn't find this described in the manual, and various packages seem to be using various methods:
- `tty.error(...)`
- `raise RunTimeError(...)`
- `raise InstallError(...)`
I think none of these actually work the way they are intended, although they all do abort the install -- because the respective identifiers are not defined.

**Comment by tgamblin** [comment]
@eschnett: which one of these seems best to you?  I think for packagers it would be nice to just have an `abort()` function to call, and it could raise a subclass of `InstallError`... maybe `UserInstallError`?   The other use case I have for this is for external packages like CUDA that need placeholders, which would probably want another subclass like `ExternalInstallOnlyError` (notional name).

Thoughts?

**Comment by eschnett** [comment]
`raise InstallError(...)` seems best; it uses the regular Python way (`raise`), and `InstallError` sounds right.
