### ISSUE TITLE
lib64 directories not added to PKG_CONFIG_PATH

### ISSUE THREAD

**Issue by mdorier** [LLNL/spack#29426]
### Steps to reproduce

```console
spack env create myenv
spack env activate myenv
spack add json-c
spack add pkg-config
spack install
pkg-config --libs json-c
```

One my Ubuntu machine this works fine. On ORNL's Summit, pkg-config can't find json-c.pc. The difference is that on my Ubuntu machine this file is located in the package's `lib` directory, while on Summit it ends up in a `lib64` directory, which isn't in `PKG_CONFIG_PATH`. I don't know why this difference happens, but I suspect it could happen with other packages. `PKG_CONFIG_PATH` should contain such `lib64` directories when they are present.

### Information on your system

* **Spack:** 0.17.1-1507-89e2ee70e2
* **Python:** 3.6.8
* **Platform:** linux-rhel8-power9le
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by mdorier** [comment]
Actually, if I deactivate the environment and reactivate it, I find that the `lib64` directory (of the environment) has been added to `PKG_CONFIG_PATH`, so the problem is: spack doesn't add it right away (contrary to the `lib` directory), and we need to deactivate and reactivate the environment to get the updated variable.

**Comment by mdorier** [comment]
Actually if I do `spack load json-c` within the environment, the problem goes away. Within the context of a larger environment with more packages, the environment's does have a `lib64` folder with a `pkgconfig` subfolder and the .pc file of some packages, but not that of json-c...

**Comment by haampie** [comment]
Feel free to reopen if this is still an issue. As far as I can see `./lib64/pkgconfig` is part of `spack config blame modules`.

Edit: `spack env activate` will not set any variables if nothing is installed yet -- reactivating after install will solve the issue.
