### ISSUE TITLE
Should we merge spack clean and spack purge?

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#2942]
I've talked to some users who mix up `spack clean` and `spack purge`. They basically do the same thing: one deletes the stage directory for a package spec (or multiple package specs) and the other deletes the stage directory for all packages. In light of #2867, should we just merge these into a single command?

**Comment by alalazo** [comment]
What about adding an optional `[anonymous-spec]` at the end of `spack purge` to restrict the cleaning to what matches and remove `spack clean`?

**Comment by adamjstewart** [comment]
That's what I was thinking. I think I like the name `clean` better than `purge` though. But yeah, it would be really easy to do, I'm just wondering if others agree.

**Comment by tgamblin** [comment]
I like `clean` better too, but @alalazo's suggestion is the way to do it.  I think the spec argument should be mutually exclusive with the other options.

@alalazo: why `anonymous`?  Could be any spec, right?
