### ISSUE TITLE
AutotoolsPackage no longer supports legacy setup_environment 

### ISSUE THREAD

**Issue by giltirn** [LLNL/spack#29446]
### Steps to reproduce

I encountered an issue when building with the most recent Spack version where my override 

```
    def setup_environment(self, spack_env, run_env):
        if '+mpi' in self.spec:
            spack_env.set('CXX', self.spec['mpi'].mpicxx)
```
is not being called during the install process, resulting in the build failing due to linker errors from undefined MPI symbols. Reverting to a version from January 25th resolved the issue. Looking at the Spack source, it seems to be happening because an override for  setup_build_environment has been added to AutotoolsPackage to resolve some MacOS compile issues which does not call out to the method in PackageBase which deals with the legacy support.

### Information on your system

[ckelly@login4.summit PerformanceAnalysis]$ spack debug report
* **Spack:** 0.17.1-957-bed3a69498
* **Python:** 3.6.8
* **Platform:** linux-rhel8-power9le
* **Concretizer:** clingo

This version works correctly. The latest commit,  

* **Spack:** 0.17.1-1521-428c63087a
* **Python:** 3.6.8
* **Platform:** linux-rhel8-power9le
* **Concretizer:** clingo
* 
does not

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
`setup_environment` hasn't really been used since #11115, which was 3 years ago. Should we just remove it entirely? Is there any reason you can't use `setup_build_environment` or `setup_run_environment`?

**Comment by alalazo** [comment]
@adamjstewart I'll submit a PR to remove the legacy behavior for v0.18

**Comment by giltirn** [comment]
I can use `setup_build_environment` and am fine with support being removed
