### ISSUE TITLE
Inconsistency with the use of scope user

### ISSUE THREAD

**Issue by npf** [LLNL/spack#29502]
### Steps to reproduce

Adding a compiler in the default scope or user scope ends up in different file paths:

```console
# rm -rf ~/.spack
# spack compiler add --scope user
==> Added 1 new compiler to /root/.spack/compilers.yaml
    gcc@10.2.1
==> Compilers are defined in the following files:
    /root/.spack/compilers.yaml
```
but:
```console
# rm -rf ~/.spack
# spack compiler add
==> Added 1 new compiler to /root/.spack/linux/compilers.yaml
    gcc@10.2.1
==> Compilers are defined in the following files:
    /root/.spack/linux/compilers.yaml
```

### Information on your system

* **Spack:** 0.17.1-6-6391bfe4f5
* **Python:** 3.9.2
* **Platform:** linux-debian11-power8le
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
I don't understand where is the bug:
```console
$ spack compiler find --scope user/linux
==> Added 1 new compiler to /home/culpo/.spack/linux/compilers.yaml
    gcc@9.4.0
==> Compilers are defined in the following files:
    /home/culpo/.spack/linux/compilers.yaml
```

**Comment by npf** [comment]
Well, ok I did not understand that I had to specify the platform in order to get the same behavior as when not giving the scope.

May I suggest to document that not giving a scope is equivalent to setting `--scope user/$(spack arch --platform)` in https://spack.readthedocs.io/en/latest/configuration.html?highlight=scope ?
