### ISSUE TITLE
openmpi@2.0.1+pmi does not compile

### ISSUE THREAD

**Issue by sknigh** [LLNL/spack#2950]
OpenMPI's pmi interface has a source code error in 2.0.1. A patch is available in the mailing list .

https://www.mail-archive.com/users@lists.open-mpi.org/msg30048.html

**Comment by tgamblin** [comment]
@sknigh: can you submit a PR with a conditional [`patch()`](https://spack.readthedocs.io/en/latest/packaging_guide.html#patch) for that?

**Comment by weijianwen** [comment]
I happe to build OpenMPI 2.0.1 on my cluster. This patch works well for me. A PR is available at #2926.

**Comment by sknigh** [comment]
The patched version worked for me. TYVM @weijianwen
