### ISSUE TITLE
Installation issue: Windows: openssl

### ISSUE THREAD

**Issue by trws** [LLNL/spack#29576]
### Steps to reproduce the issue

Before installing nasm, get a cryptic config error from spack that turns out to be lack of nasm.
With nasm installed and in path:
```console
[spack] C:\Users\trws\Repos\spack-clean>spack install camp%msvc@19.29.30140
...
```

### Error message

<details><summary>Error message</summary><pre>
==> Warning: the original concretizer is currently being used.
        Upgrade to "clingo" at your earliest convenience. The original concretizer will be removed from Spack starting at v0.18.0
[+] C:\Users\trws\AppData\Local\Microsoft\WindowsApps (external python-3.9.10-zhlbtwr6mgqjhjz65zdlwkrm6npzmqmz)
[+] C:\Users\trws\Repos\spack-clean\opt\spack\windows-windows10-AMD64\msvc-19.29.30140\nasm-2.15.05-yfumw5sa7vzqsytgqzpjnujj4fqkor6o
[+] C:\Users\trws\Repos\spack-clean\opt\spack\windows-windows10-AMD64\msvc-19.29.30140\perl-5.34.0-5h52c2qke5ztwft7ctx5su55zunr4xaa
[+] C:\Users\trws\Repos\spack-clean\opt\spack\windows-windows10-AMD64\msvc-19.29.30140\zlib-1.2.11-x56c4oc5chybvomstxtvhxni4xsxjpkm
[+] C:\Users\trws\Repos\spack-clean\opt\spack\windows-windows10-AMD64\msvc-19.29.30140\ninja-1.10.2-pf6fue3e32lg3nw6gtrjky5phjeh7ykr
==> Installing openssl-1.1.1n-et2j3meb45n2n6crx7bkwbk5mzjjujqa
==> No binary for openssl-1.1.1n-et2j3meb45n2n6crx7bkwbk5mzjjujqa found: installing from source
==> Using cached archive: C:\Users\trws\Repos\spack-clean\var\spack\cache\_source-cache\archive\40\40dceb51a4f6a5275bde0e6bf20ef4b91bfc32ed57c0552e2e8e15463372b17a.tar.gz
==> Ran patch() for openssl
==> Error: ProcessError: Command exited with status 2:
    'nmake' 'install_sw'

2 errors found in build log:
     34    Microsoft (R) Program Maintenance Utility Version 14.29.30140.0
     35    Copyright (C) Microsoft Corporation.  All rights reserved.
     36
     37         C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\T
           ools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe  /Zi /Fdossl_static.pdb
            /MT /Zl /Gs0 /GF /Gy /W3 /wd4090 /nologo /O2 /I "." /I "include" -D
           "L_ENDIAN" -D"OPENSSL_PIC" -D"OPENSSL_CPUID_OBJ" -D"OPENSSL_IA32_SSE
           2" -D"OPENSSL_BN_ASM_MONT" -D"OPENSSL_BN_ASM_MONT5" -D"OPENSSL_BN_AS
           M_GF2m" -D"SHA1_ASM" -D"SHA256_ASM" -D"SHA512_ASM" -D"KECCAK1600_ASM
           " -D"RC4_ASM" -D"MD5_ASM" -D"AESNI_ASM" -D"VPAES_ASM" -D"GHASH_ASM"
           -D"ECP_NISTZ256_ASM" -D"X25519_ASM" -D"POLY1305_ASM" -D"OPENSSLDIR=\
           "C:\\Users\\trws\\Repos\\spack-clean\\opt\\spack\\windows-windows10-
           AMD64\\msvc-19.29.30140\\openssl-1.1.1n-et2j3meb45n2n6crx7bkwbk5mzjj
           ujqa\\etc\\openssl\"" -D"ENGINESDIR=\"C:\\Users\\trws\\Repos\\spack-
           clean\\opt\\spack\\windows-windows10-AMD64\\msvc-19.29.30140\\openss
           l-1.1.1n-et2j3meb45n2n6crx7bkwbk5mzjjujqa\\lib\\engines-1_1\"" -D"OP
           ENSSL_SYS_WIN32" -D"WIN32_LEAN_AND_MEAN" -D"UNICODE" -D"_UNICODE" -D
           "_CRT_SECURE_NO_DEPRECATE" -D"_WINSOCK_DEPRECATED_NO_WARNINGS" -D"ND
           EBUG"  -c /Foapps\app_rand.obj "apps\app_rand.c"
     38    'C:\Program' is not recognized as an internal or external command,
     39    operable program or batch file.
  >> 40    NMAKE : fatal error U1077: 'C:\Program' : return code '0x1'
     41    Stop.
  >> 42    NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual
            Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\HostX64\x64\nm
           ake.exe"' : return code '0x2'
     43    Stop.
     44    Exception in thread Thread-1:
     45    Traceback (most recent call last):
     46      File "C:\Python39\lib\threading.py", line 954, in _bootstrap_inner
     47        self.run()
     48      File "C:\Python39\lib\threading.py", line 892, in run

See build log for details:
  C:\Users\trws\Repos\spack-clean\.staging\spack-stage-openssl-1.1.1n-et2j3meb45n2n6crx7bkwbk5mzjjujqa\spack-build-out.txt</pre></details>

### Information on your system

* **Spack:** 0.17.1-1606-5a72204d38
* **Python:** 3.9.5
* **Platform:** windows-windows10-AMD64
* **Concretizer:** original

### Additional information

[spack-build-out.txt](https://github.com/spack/spack/files/8292977/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/8292980/spack-build-env.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by billhoffman** [comment]
I was able to get it to work with this change:
```
--- a/var/spack/repos/builtin/packages/openssl/package.py
+++ b/var/spack/repos/builtin/packages/openssl/package.py
@@ -143,8 +143,8 @@ def install(self, spec, prefix):
                      % join_path(prefix, 'etc', 'openssl')]
         if spec.satisfies('platform=windows'):
             base_args.extend([
-                'CC=%s' % os.environ.get('CC'),
-                'CXX=%s' % os.environ.get('CXX'),
+                'CC=\"%s\"' % os.environ.get('CC'),
+                'CXX=\"%s\"' % os.environ.get('CXX'),
                 'VC-WIN64A',
             ])
```

**Comment by trws** [comment]
That's probably a good change in general.
