### ISSUE TITLE
windows: don't make symlink fall back to copy.

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#29635]
### Steps to reproduce

I find it surprising that `symlink` falls back to a copy on Windows, and in some cases it is just bad. In particular here:

https://github.com/spack/spack/blob/6611f0bf4b657543f29f2d62adc396ca33393ee5/lib/spack/spack/environment/environment.py#L535

The trick is to update views atomically, effectively
```
ln -s new_dir ._view_link
mv ._view_link view
```

Can symlink just remain a symlink instead of something hard to reason about?

### Information on your system

.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by KiruyaMomochi** [comment]
It's possible to use symbolic link, but with limitations 

Before Windows 10 Insiders Build 14972 (19H1)
- the program need to be elevated to run as administrator
- *or*, `Create symbolic links`(`SeCreateSymbolicLink`) is granted to user in Group Policy

However, **after Build 14972, after Developer Mode is on, any user on the machine can run the mklink command without elevating a command-line console.**

[Symlinks in Windows 10! - Windows Blogs](https://blogs.windows.com/windowsdeveloper/2016/12/02/symlinks-windows-10/) has a detailed information on this.

**Comment by johnwparent** [comment]
I believe this will be resolved by #34701
