### ISSUE TITLE
Conflict when installing Python on MacOS

### ISSUE THREAD

**Issue by krcb** [LLNL/spack#29667]
### Steps to reproduce

I ran the following command to generate a spec for python 3.8 on MacOS 12.2.1

```spack --show-cores=minimized spec --reuse python@3.8%gcc@11.2.0```

Note that gcc@11.2.0 was built using spack with

```spack install gcc@11.2.0```

### Error message

==> Error: python@3.8%gcc@11.2.0 is unsatisfiable, conflicts are:
  A conflict was triggered
  A node must have exactly one platform
  compiler_version_satisfies("gcc",":","11.2.0")
  condition(473)
  condition(474)
  conflict("python",473,474)
  imposed_constraint("pkae2pfwc2z4ud6dsjnymmn2kvw7xb4b","node_compiler_version","python","apple-clang","13.0.0")
  node_compiler_version_set("python","gcc","11.2.0")
  root("python")

### Information on your system

* **Spack:** 0.17.1-1552-7f03724db2
* **Python:** 3.8.9
* **Platform:** darwin-monterey-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
Python does not compile with GCC on macOS, see https://github.com/python/cpython/pull/13306

You should use Apple Clang on macOS for almost all software installs, many packages don't build with GCC.

**Comment by krcb** [comment]
Thanks! This is really helpful feedback which I can pass along to my team
