### ISSUE TITLE
Git hashes in concretized environment break custom repos

### ISSUE THREAD

**Issue by scheibelp** [LLNL/spack#29707]
### Steps to reproduce

1. Create an environment with a custom package repo

2. In that environment's specs, add any package (whether it's mentioned in the custom repo or not) with `@<git-commit-hash>` as a version

3. Add another package which refers to the custom package repo (i.e. something exclusive to the custom package repository) 

4. Concretize the environment

5. Any future operation using that environment will now ignore the custom repository

This is because resolving the git hash to a version involves querying the repositories, so they are instantiated inside of `Environment.__init__` before the Environment ever has a chance to apply its configuration (including package repository).    

### Error message

The error message will complain about a missing package (since it will only search the builtin repo).

### Information on your system

This should be reproducible on any system

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by scheibelp** [comment]
@vsoch I'm curious: `spack.test.cmd.install.test_install_commit` installs a package which contains the following:

```
    def install(self, spec, prefix):
        assert spec.satisfies('@:0')
        mkdir(prefix.bin)

        # This will only exist for some second commit
        install('file.txt', prefix.bin)
```

what is the meaning of `assert spec.satisfies('@:0')`?

**Comment by vsoch** [comment]
I'm not the best one to ask - ping @becker33 !

**Comment by becker33** [comment]
@scheibelp is this fixed by your PR deferring `.package` access?

**Comment by scheibelp** [comment]
Yes.
