### ISSUE TITLE
#27021 broke GitHub SSH urls

### ISSUE THREAD

**Issue by elfprince13** [LLNL/spack#29706]
### Steps to reproduce

```console
spack install rkt-base
```

### Error message

Empty error message
```console
==> Error: 
```

In debug mode, this leads to an assertion error originating here (code introduced in #27021):

https://github.com/spack/spack/blob/872d29e20168d1ff133fc25cad5932e5949c9c6e/lib/spack/spack/util/url.py#L345-L347

### Information on your system

* **Spack:** 0.18.0.dev0 (c8f1b8c95c4feaa36577d33344c7639f0799bc93)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by KineticTheory** [comment]
I'm also seeing this issue (different package).  Adding `ssh://|` to the regex on line 346 fixes the issue for me.

**Comment by elfprince13** [comment]
and then presumably also adding `ssh://` to the affected packages? This isn't typically specified for git clients.

**Comment by elfprince13** [comment]
@scheibelp - Please note that #29749 is only a partial fix. There are several packages whose URLs needed to be canonicalized from the common GitHub/GitLab/Bitbucket style to `ssh://` style, addressed in #29754.

**Comment by scheibelp** [comment]
Apparently this should be reopened pending https://github.com/spack/spack/pull/29754

**Comment by scheibelp** [comment]
https://github.com/spack/spack/pull/29754 is now merged.
