### ISSUE TITLE
File permissions and calls to "llnl.util.filesystem.remove_linked_tree"

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#29713]
### Steps to reproduce

Call from a script or a unit-test:

https://github.com/spack/spack/blob/f8201f4acc53bbb7efcde77a369546181b802d19/lib/spack/llnl/util/filesystem.py#L1183-L1209

with a path that fails to perform `shutil.rmtree`, e.g. the path of a file. That on linux leaves the file with different permissions because of how `onerror` handles the error.

### Error message

This was leading to issues like #29687 

### Information on your system

System is not relevant

@scheibelp proposed a possible fix for Windows in https://github.com/spack/spack/pull/29690#issuecomment-1076751911

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by johnwparent** [comment]
Apologies, I was out yesterday and didn't get a chance to respond to @scheibelp. Rather than pollute that PR, I'll post my response here. I think Peter has a fine solution, I'll push shortly.
