### ISSUE TITLE
LAMMPS with OpenMP support

### ISSUE THREAD

**Issue by tz-rrze** [LLNL/spack#29833]
### Steps to reproduce

With the Stable release 29 September 2021, the LAMMPS developers reorganized many packages. This included the rename of USER-OMP to OPENMP.
According to https://docs.lammps.org/stable/Build_extras.html#openmp, one now has to define `PKG_OPENMP=yes` for OpenMP support. The package.py of LAMMPS still has `user-omp` in the list of supported packages and only sets `BUILD_OMP` for +openmp.

### Error message

LAMMPS is built, however, OpenMP support is missing in the resulting binary due to outdated config args.

### Information on your system

* **Spack:** 0.18.0.dev0 (cbba0ffc0ca083cf40fa62d0a6a1d30980949cc8)
* **Python:** 3.6.8
* **Platform:** linux-almalinux8-zen3
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by tz-rrze** [comment]
might be solved by #29788

**Comment by alalazo** [comment]
Thanks for the note, closing the issue then!
