### ISSUE TITLE
[Q] Modify the existing py-or-tools package or create a new or-tools package?

### ISSUE THREAD

**Issue by hyoklee** [LLNL/spack#29839]
Hi,

  I'd like to improve Google OR-Tools support by either modifying [py-or-tools](https://github.com/spack/spack/tree/develop/var/spack/repos/builtin/packages/py-or-tools)  package or creating a new one called [or-tools](https://github.com/hyoklee/spack/tree/develop/var/spack/repos/builtin/packages/or-tools). However, I don't know what's  the best for Spack maintainers and users so I'd appreciate if someone can recommend the right approach.

  My goal is to provide the ability to
  
  * turn off Python support via variant.
  * add more CMake build options that OR-tools provide.

  The package name py-or-tools already suggests that it's for Python   so I'm not sure if it is acceptable to add a variant that turns off Python  API to the existing py-or-tools package. Is there any other Spack package that starts with “py-”  but turns off the Python interface through a variant?

  I'd appreciate it if someone could give me a recommendation.  For example, Spack maintainer may want to rename py-or-tools to or-tools  and add `+python` as a variant to turn on Python.

  Best regards,

**Comment by adamjstewart** [comment]
https://spack.readthedocs.io/en/latest/build_systems/pythonpackage.html#choosing-a-package-name has some guidance on this
