### ISSUE TITLE
tcl configuration no longer working after commit e72f87ec

### ISSUE THREAD

**Issue by csbnw** [LLNL/spack#29830]
### Steps to reproduce

First, set up a clean Spack environment:
```console
git clone https://github.com/spack/spack.git
cd spack
source spack/share/spack/setup-env.sh
```

Next create an environment with a package (`git` in this case) with some desired configuration:
```
spack env create test
spack env activate test
echo "spack:                              
  specs: [git]
  view: false
  concretization: together
  modules:
    enable:
    - tcl
    tcl:
      hash_length: 0
      naming_scheme: '\${COMPILERNAME}/\${COMPILERVER}/\${PACKAGE}/\${VERSION}'
      all:
        environment:
          set:
            '{name}_ROOT': '{prefix}'
" > var/spack/environments/test/spack.yaml 
```

Note the last part of the `spack.yaml` file. The intention is to have environment-module files with names like `gcc/11.2.1/<package>`, such that we have separate 'stacks' of packages using the same compiler version.

Moreover, we find it convenient to have `<package>_ROOT` variables for all the environment-modules.

### Error message

With commit `e72f87ec`, the resulting module files look like this (incorrect):

```console
$ ls share/spack/modules/linux-fedora35-zen3/
autoconf-2.69-gcc-11.2.1-3kwhasq        curl-7.81.0-gcc-11.2.1-qzfinjo    gettext-0.21-gcc-11.2.1-na5wf4d          libiconv-1.16-gcc-11.2.1-osltowj    libtool-2.4.6-gcc-11.2.1-nvvvfe6        ncurses-6.2-gcc-11.2.1-atmqel6     perl-5.34.0-gcc-11.2.1-xexayqs    xz-5.2.5-gcc-11.2.1-s7l4upo
automake-1.16.5-gcc-11.2.1-24b4ad5      diffutils-3.8-gcc-11.2.1-n4igklb  git-2.35.1-gcc-11.2.1-4kdmpue            libidn2-2.3.0-gcc-11.2.1-s6ofssk    libunistring-0.9.10-gcc-11.2.1-c5lwnzw  openssh-8.9p1-gcc-11.2.1-uohbm3i   pkgconf-1.8.0-gcc-11.2.1-2sqvvvb  zlib-1.2.11-gcc-11.2.1-uhlnocu
berkeley-db-18.1.40-gcc-11.2.1-vmxo5pc  expat-2.4.6-gcc-11.2.1-7h3fuaj    libbsd-0.11.5-gcc-11.2.1-5rfhjze         libmd-1.0.4-gcc-11.2.1-tajia74      libxml2-2.9.12-gcc-11.2.1-heehdjo       openssl-1.1.1n-gcc-11.2.1-lamvdck  readline-8.1-gcc-11.2.1-hbb5adu
bzip2-1.0.8-gcc-11.2.1-v3le5se          gdbm-1.19-gcc-11.2.1-v2ns3jx      libedit-3.1-20210216-gcc-11.2.1-2zqfxri  libsigsegv-2.13-gcc-11.2.1-5urtt6j  m4-1.4.19-gcc-11.2.1-gywxoin            pcre2-10.39-gcc-11.2.1-okwl34g     tar-1.34-gcc-11.2.1-tgt2jw2
```

And `git-2.35.1-gcc-11.2.1-4kdmpue` lacks `GIT_ROOT`.

While with `e72f87ec~1`, the environment-modules looks like expected:
```console
$ ls share/spack/modules/linux-fedora35-zen3/gcc/11.2.1/
autoconf  automake  berkeley-db  bzip2  curl  diffutils  expat  gdbm  gettext  git  libbsd  libedit  libiconv  libidn2  libmd  libsigsegv  libtool  libunistring  libxml2  m4  ncurses  openssh  openssl  pcre2  perl  pkgconf  readline  tar  xz  zlib
```

With `share/spack/modules/linux-fedora35-zen3/gcc/11.2.1/git/2.35.1` containing:
```
setenv GIT_ROOT "/scratch/spack/opt/spack/linux-fedora35-zen3/gcc-11.2.1/git-2.35.1-4kdmpuevbkiczoewdsg4zetjq7b6iuf2"
```

### Information on your system

* **Spack:** 0.17.1-880-612430859e
* **Python:** 3.10.3
* **Platform:** linux-fedora35-zen3
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
Add `default:` to your module sets, because `etc/defaults/modules.yaml` specifies `modules:default:tcl:...` which takes precedence over `modules:tcl:...`. #28659 should fix this but has been open for months now :( ping @becker33 

```yaml
spack:
  specs: [git]
  view: false
  concretization: together
  modules:
    default: # <-
      enable:
      - tcl
      tcl:
        hash_length: 0
        naming_scheme: '\${COMPILERNAME}/\${COMPILERVER}/\${PACKAGE}/\${VERSION}'
        all:
          environment:
            set:
              '{name}_ROOT': '{prefix}'
```

**Comment by csbnw** [comment]
Awesome, adding the `default:` works just fine!

Without the `default:`, your `hs/deprecate-top-level-module-config` branch also works correctly.

I am fine with using this workaround for now, such that I can keep using the `develop` branch.

How about linking this issue to https://github.com/spack/spack/pull/28659, and closing/resolving this issue (#29830) once #28659 is merged? This behavior is a breaking change, after all, and having this issue open serves as a warning for other users that may encounter something similar.

**Comment by haampie** [comment]
Yeah, sounds good. I'm hoping we can get #28659 merged soon...
