### ISSUE TITLE
Installation issue TX2: LLVM-13

### ISSUE THREAD

**Issue by Game4Move78** [LLNL/spack#29860]
### Steps to reproduce the issue

```console
$ spack install llvm targets=all ~lldb
...
```

### Error message

<details><summary>Error message</summary><pre>
==> Installing llvm-13.0.1-tdovhbelzu62vwsu4uujvdwjv26qsmgj                                                                                                                                                                         [190/255]
==> No binary for llvm-13.0.1-tdovhbelzu62vwsu4uujvdwjv26qsmgj found: installing from source
==> Using cached archive: /media/sdcard/patrick/spack/var/spack/cache/_source-cache/archive/09/09c50d558bd975c41157364421820228df66632802a4a6a7c9c17f86a7340802.tar.gz
==> No patches needed for llvm
==> llvm: Executing phase: 'cmake'
==> llvm: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 1:
    'ninja' '-j4' '-v'

7 errors found in build log:
     21030    [35/565] Building CXX object openmp/runtime/src/CMakeFiles/omp.dir/ompd-specific.cpp.o
     21031    [36/565] Building C object openmp/runtime/src/CMakeFiles/omp.dir/z_Linux_asm.S.o
     21032    [37/565] Building CXX object openmp/runtime/src/CMakeFiles/omp.dir/kmp_ftn_cdecl.cpp.o
     21033    [38/565] Linking CXX shared library openmp/libomptarget/libomptarget.so
     21034    [39/565] Building CXX object openmp/runtime/src/CMakeFiles/omp.dir/kmp_ftn_extra.cpp.o
     21035    [40/565] Building LLVM bitcode omptarget.cu-sm_35.bc
  >> 21036    FAILED: openmp/libomptarget/deviceRTLs/nvptx/omptarget.cu-sm_35.bc /media/sdcard/tmp/patrick/spack-st
              age/spack-stage-llvm-13.0.1-tdovhbelzu62vwsu4uujvdwjv26qsmgj/spack-build-tdovhbe/runtimes/runtimes-bi
              ns/openmp/libomptarget/deviceRTLs/nvptx/omptarget.cu-sm_35.bc
     21037    cd /media/sdcard/tmp/patrick/spack-stage/spack-stage-llvm-13.0.1-tdovhbelzu62vwsu4uujvdwjv26qsmgj/spa
              ck-build-tdovhbe/runtimes/runtimes-bins/openmp/libomptarget/deviceRTLs/nvptx && /media/sdcard/tmp/pat
              rick/spack-stage/spack-stage-llvm-13.0.1-tdovhbelzu62vwsu4uujvdwjv26qsmgj/spack-build-tdovhbe/./bin/c
              lang -S -x c++ -O1 -std=c++14 -mllvm -openmp-opt-disable -target nvptx64 -Xclang -emit-llvm-bc -Xclan
              g -aux-triple -Xclang aarch64-unknown-linux-gnu -fopenmp -fopenmp-cuda-mode -Xclang -fopenmp-is-devic
              e -Xclang -target-feature -Xclang +ptx61 -D__CUDACC__ -I/media/sdcard/tmp/patrick/spack-stage/spack-s
              tage-llvm-13.0.1-tdovhbelzu62vwsu4uujvdwjv26qsmgj/spack-src/openmp/libomptarget/deviceRTLs -I/media/s
              dcard/tmp/patrick/spack-stage/spack-stage-llvm-13.0.1-tdovhbelzu62vwsu4uujvdwjv26qsmgj/spack-src/open
              mp/libomptarget/deviceRTLs/common/include -I/media/sdcard/tmp/patrick/spack-stage/spack-stage-llvm-13
              .0.1-tdovhbelzu62vwsu4uujvdwjv26qsmgj/spack-src/openmp/libomptarget/deviceRTLs/nvptx/src -DOMPTARGET_
              NVPTX_DEBUG=0 -Xclang -target-cpu -Xclang sm_35 -D__CUDA_ARCH__=350 /media/sdcard/tmp/patrick/spack-s
              tage/spack-stage-llvm-13.0.1-tdovhbelzu62vwsu4uujvdwjv26qsmgj/spack-src/openmp/libomptarget/deviceRTL
              s/common/src/omptarget.cu -o omptarget.cu-sm_35.bc
     21038    In file included from /media/sdcard/tmp/patrick/spack-stage/spack-stage-llvm-13.0.1-tdovhbelzu62vwsu4
              uujvdwjv26qsmgj/spack-src/openmp/libomptarget/deviceRTLs/common/src/omptarget.cu:14:
     21039    In file included from /media/sdcard/tmp/patrick/spack-stage/spack-stage-llvm-13.0.1-tdovhbelzu62vwsu4
              uujvdwjv26qsmgj/spack-src/openmp/libomptarget/deviceRTLs/common/omptarget.h:18:
     21040    In file included from /media/sdcard/tmp/patrick/spack-stage/spack-stage-llvm-13.0.1-tdovhbelzu62vwsu4
              uujvdwjv26qsmgj/spack-src/openmp/libomptarget/deviceRTLs/common/debug.h:31:
     21041    In file included from /media/sdcard/tmp/patrick/spack-stage/spack-stage-llvm-13.0.1-tdovhbelzu62vwsu4
              uujvdwjv26qsmgj/spack-src/openmp/libomptarget/deviceRTLs/common/device_environment.h:16:
     21042    In file included from /media/sdcard/tmp/patrick/spack-stage/spack-stage-llvm-13.0.1-tdovhbelzu62vwsu4
              uujvdwjv26qsmgj/spack-src/openmp/libomptarget/deviceRTLs/nvptx/src/target_impl.h:15:
     21043    In file included from /media/sdcard/tmp/patrick/spack-stage/spack-stage-llvm-13.0.1-tdovhbelzu62vwsu4
              uujvdwjv26qsmgj/spack-build-tdovhbe/lib/clang/13.0.1/include/inttypes.h:21:
     21044    In file included from /usr/include/inttypes.h:25:
  >> 21045    /usr/include/features.h:367:12: fatal error: 'sys/cdefs.h' file not found
     21046    #  include <sys/cdefs.h>
     21047               ^~~~~~~~~~~~~
     21048    1 error generated.
</pre></details>

### Information on your system

* **Spack:** 0.18.0.dev0 (a785eeb89663706846c18111e60bd548f9e73930)
* **Python:** 3.5.2
* **Platform:** linux-ubuntu16.04-aarch64
* **Concretizer:** clingo

### Additional information

One thing that seems to solve the issue is running the command:
``
sudo ln -s /usr/include/aarch64-linux-gnu/sys/* /usr/include/sys/
``

@haampie @trws 

[spack-build-env2.txt](https://github.com/spack/spack/files/8404284/spack-build-env2.txt)
[spack-build-02-build-out.txt](https://github.com/spack/spack/files/8404285/spack-build-02-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by trws** [comment]
That looks very much like a broken base system without a complete libc, usually this means you lack either the libc6-dev package or the libc6-dev-i386 package on an ubuntu system.
