### ISSUE TITLE
Installation issue: rocprofiler-dev

### ISSUE THREAD

**Issue by jordialcaraz** [LLNL/spack#29879]
### Steps to reproduce the issue

```console
$ spack install hip
$ spack install rocprofiler-dev
$ spack install roctracer-dev
$ spack install hsa-rocr-dev


$ spack load hip
$ spack load rocprofiler-dev
$ spack load roctracer-dev
$ spack load hsa-rocr-dev

#Compile examples/gpu/hip/add4 from TAU
$ make

#Execute example:
$ ./gpu-stream-hip
GPU-STREAM
Version: 1.0
Implementation: HIP
GridSize: 26214400 work-items
GroupSize: 1024 work-items
Operations/Work-item: 1
Precision: double

Running kernels 10 times
Array size: 200.0 MB (=0.2 GB) 0 bytes padding
Total size: 1000.0 MB (=1.0 GB)
Using HIP device  (compute_units=120)
Driver: 50000000
d_a=0x7fb358000000
d_b=0x7fb348000000
d_c=0x7fb230000000
d_d=0x7fb220000000
d_e=0x7fb210000000
Function    MBytes/sec  Min (sec)   Max         Average
Copy        1017417.586 0.00041     0.00042     0.00041
Mul         1018183.231 0.00041     0.00041     0.00041
Add4        980349.553  0.00107     0.00108     0.00107
Triad       998089.315  0.00063     0.00063     0.00063
GEOMEAN     1003387.960


#Profile example
$ rocprof ./gpu-stream-hip
RPL: on '220404_130418' from '/storage/users/jalcaraz/spack/opt/spack/linux-ubuntu20.04-broadwell/gcc-9.3.0/rocprofiler-dev-5.0.2-jsnf7o6fsa4sozak2l7hblqppqyni72t/rocprofiler' in '/home/users/jalcaraz/tau2/examples/gpu/hip/add4'
RPL: profiling '"./gpu-stream-hip"'
RPL: input file ''
RPL: output dir '/tmp/rpl_data_220404_130418_3998325'
RPL: result dir '/tmp/rpl_data_220404_130418_3998325/input_results_220404_130418'
GPU-STREAM
Version: 1.0
Implementation: HIP
GridSize: 26214400 work-items
GroupSize: 1024 work-items
Operations/Work-item: 1
Precision: double

Running kernels 10 times
Array size: 200.0 MB (=0.2 GB) 0 bytes padding
Total size: 1000.0 MB (=1.0 GB)
ROCProfiler: input from "/tmp/rpl_data_220404_130418_3998325/input.xml"
  0 metrics
Using HIP device  (compute_units=120)
Driver: 50000000
/storage/users/jalcaraz/spack/opt/spack/linux-ubuntu20.04-broadwell/gcc-9.3.0/rocprofiler-dev-5.0.2-jsnf7o6fsa4sozak2l7hblqppqyni72t/bin/rocprof: line 286: 3998459 Aborted                 (core dumped) "./gpu-stream-hip"
File '/home/users/jalcaraz/tau2/examples/gpu/hip/add4/results.csv' is generating
```

### Error message

<details><summary>Error message</summary><pre>
#From rocprof
/storage/users/jalcaraz/spack/opt/spack/linux-ubuntu20.04-broadwell/gcc-9.3.0/rocprofiler-dev-5.0.2-jsnf7o6fsa4sozak2l7hblqppqyni72t/bin/rocprof: line 286: 3998459 Aborted                 (core dumped) "./gpu-stream-hip"

#From TAU
aqlprofile API table load failed: HSA_STATUS_ERROR: A generic error has occurred.
</pre></details>

### Information on your system

* **Spack:** 0.18.0.dev0 (a58fa289b9fb9b593773ace91b531b9547614771)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-broadwell
* **Concretizer:** clingo

### Additional information

Profiling does not work for rocm after installation with spack. Local installation works.

Similar issue found here:
https://githubhot.com/repo/ROCm-Developer-Tools/rocprofiler/issues/29
Using find in the directory where spack install packages, there is no "libhsa-amd-aqlprofile64.so".

Seems that spack does not install the library hsa-amd-aqlprofile 

@arjun-raj-kuppala @srekolam

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by gcongiu** [comment]
@srekolam is there any progress on this issue? We have the same problem in PAPI when the ROCm component is enabled. Unless, libhsa-amd-aqlprofile64.so is installed already in the system, and we load it manually, the spack installation of rocprofiler is of little use to PAPI.

**Comment by srekolam** [comment]
recently submitted a PR to support the newer revisions of rocprofiler along with new package for libhsa-amd-aqlprofile  https://github.com/spack/spack/pull/42459 . these are merged now. Closing this issue.
