### ISSUE TITLE
Bash: messed up display for long lines when terminal prompt is colorized

### ISSUE THREAD

**Issue by climbfuji** [LLNL/spack#29881]
### Steps to reproduce

I am using macOS (Monterey) with bash 5.1.16 installed via homebrew (but same results of I use the native macOS bash). When I use ``spack env activate -p ...`, the display is messed up. A good description for my problem is here:

https://unix.stackexchange.com/questions/389008/bash-messed-up-display-for-long-lines

The solution is in the first answer:
> Your prompt contains colors (and maybe other non-printables).
> In bash, you can surround the parts with \[ and \] to tell bash to ignore those parts to calculate the length of the prompt.

I tried this solution, but couldn't find a clean way to separate the `colorize` calls for bash prompts from those for other spack output (e.g. `spack info ...`) - see closed PR https://github.com/spack/spack/pull/29882.

### Error message

No error message, but display is messed up.

### Information on your system

```
* **Spack:** 0.18.0.dev0 (f69dd0826962438720b5d159baeef6d8e4bf1af9)
* **Python:** 3.9.10
* **Platform:** darwin-monterey-x86_64
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
I encountered this too. We should be able to fix this in a manner similar to #29882. In the long run, I would love to get rid of `lib/spack/llnl/util/tty/color.py` entirely and use colorama instead. That will give us free Windows support for coloring.

**Comment by adamjstewart** [comment]
@tgamblin wrote most of the tty color code, but that stuff hasn't been updated in 9 years. We're only encountering this now because we never used colors for the prompt until environments were introduced.

**Comment by climbfuji** [comment]
> @tgamblin wrote most of the tty color code, but that stuff hasn't been updated in 9 years. We're only encountering this now because we never used colors for the prompt until environments were introduced.

@adamjstewart Trying to clean up old issues, has there been any progress on this?

**Comment by adamjstewart** [comment]
An admirable goal. Unfortunately, I don't think anything has changed.

**Comment by climbfuji** [comment]
I'll close this as won't fix, it's not urgent/important and has been sitting here for some time.
