### ISSUE TITLE
The package `llvm-amdgpu` sets `CFLAGS` and `CXXFLAGS` which overrides defaults in some packages

### ISSUE THREAD

**Issue by v-dobrev** [LLNL/spack#29888]
The flags are set here:
https://github.com/spack/spack/blob/b2717a8abf02e580898f746bfe763072fc0139c1/var/spack/repos/builtin/packages/llvm-amdgpu/package.py#L118-L119

In particular, this results in some packages being built without optimization when `+rocm` is enabled. Examples of such packages are `hypre`, `petsc`, and `mfem`.

**Comment by haampie** [comment]
That looks like a really poor way to handle this. Should be part of pkgconfig / cmake config files, not a global override.

**Comment by srekolam** [comment]
this was introduced as part of https://github.com/spack/spack/pull/29017.will revert this change inside llvm-amdgpu

**Comment by srekolam** [comment]
this is fixed by #30036
