### ISSUE TITLE
Dealing with autotools and %nvhpc

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#29899]
`libtool` doesn't know about `nvc`, `nvc++`, `nvfortran`, only about PGI compilers, and as a result doesn't know how to set some flags for these compilers, in particular `pic`-related ones:

https://git.savannah.gnu.org/cgit/libtool.git/tree/m4/libtool.m4#n4740

A patch was submitted in August 2020 https://www.mail-archive.com/libtool-patches@gnu.org/msg07391.html but this was ignored.

Some packages try to fix libtool themselves now, like MPICH: https://github.com/pmodels/mpich/commit/6ff2ed15b47d5b5c21aabfab75240ed15b4af41a

But we can't expect every autotools package to do this. Also we can't expect packages to come with a configure script generated with a recent libtool (assuming the patch above gets merged in libtool at some point).

So what's the way to deal with it? Add the patch ourselves and force reconfigure, like this?

```python
@property
def force_autoreconf(self):
  return self.spec.satisfies('%nvhpc')

depends_on('libtool+nvhpc_patch', when='%nvhpc')
depends_on('automake', when='%nvhpc')
depends_on('autoconf', when='%nvhpc')
```

**Comment by raffenet** [comment]
We ended up reverting https://github.com/pmodels/mpich/commit/6ff2ed15b47d5b5c21aabfab75240ed15b4af41a and re-applying it with some modifications in https://github.com/pmodels/mpich/pull/5767. I believe the patch that was posted to the libtool list incorrect.

**Comment by teojgo** [comment]
> We ended up reverting [pmodels/mpich@6ff2ed1](https://github.com/pmodels/mpich/commit/6ff2ed15b47d5b5c21aabfab75240ed15b4af41a) and re-applying it with some modifications in [pmodels/mpich#5767](https://github.com/pmodels/mpich/pull/5767). I believe the patch that was posted to the libtool list incorrect.

I could compile mpich 4.0.1 using nvhpc so the patch included in that branch should be fine.

**Comment by samcmill** [comment]
Wouldn't a less invasive approach be something like:

```
if spec.satisfies('%nvhpc'):
    config_args.append('CFLAGS=-fPIC')
```

**Comment by tkameyama** [comment]
AutotoolsPackage is patched libtool after configure for some compilers (#12004 and #18620).

**Comment by haampie** [comment]
Thanks @tkameyama, that's helpful
