### ISSUE TITLE
Installation issue: openssh

### ISSUE THREAD

**Issue by dmentock** [LLNL/spack#29938]
### Steps to reproduce the issue

The current user is part of the group `my_group`:
```
% cd /opt
% sudo git clone https://github.com/spack/spack.git
% sudo chmod -R 774 spack/
% sudo chgrp -R my_group spack/
% cp spack/etc/spack/defaults/packages.yaml spack/etc/spack/packages.yaml
% nano spack/etc/spack/packages.yaml 

# modify packages.yaml as following:
# packages:
#  all:
#    compiler: [gcc, intel, pgi, clang, xl, nag, fj, aocc]
#    providers:
#        ...
#    permissions:
#      read: world
#      write: group
#      group: my_group

% spack/bin/spack install openssh
```

### Error message

```
==> Installing openssh-8.9p1-bduceyccy4v7q7v3chwm4m2r7djoacxq
==> No binary for openssh-8.9p1-bduceyccy4v7q7v3chwm4m2r7djoacxq found: installing from source
==> Using cached archive: /opt/spack/var/spack/cache/_source-cache/archive/fd/fd497654b7ab1686dac672fb83dfb4ba4096e8b5ffcdaccd262380ae58bec5e7.tar.gz
==> No patches needed for openssh
==> openssh: Executing phase: 'autoreconf'
==> openssh: Executing phase: 'configure'
==> openssh: Executing phase: 'build'
==> openssh: Executing phase: 'install'
==> Warning: Module file /opt/spack/share/spack/modules/linux-ubuntu20.04-sandybridge/openssh-8.9p1-gcc-10.3.0-bduceyc exists and will not be overwritten
==> Error: InvalidPermissionsError: Attempting to set suid with group writable

/opt/spack/lib/spack/spack/build_environment.py:1065, in _setup_pkg_and_run:
       1062        tb_string = traceback.format_exc()
       1063
       1064        # build up some context from the offending package so we can
  >>   1065        # show that, too.
       1066        package_context = get_package_context(tb)
       1067
       1068        logfile = None


```

### Information on your system

```
* **Spack:** 0.18.0.dev0 (cd0b6b90881126c73f050ba3b29e0cc570827f10)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-sandybridge
* **Concretizer:** clingo

```

### Additional information

[spack-build-03-build-out.txt](https://github.com/spack/spack/files/8441673/spack-build-03-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/8441684/spack-build-env.txt)

@bernhardkaindl

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by jounathaen** [comment]
Just for a short confirmation: I'm running into the same issue

**Comment by RonRahaman** [comment]
I'm seeing the same issue from openssh-8.7p1-ntpy44vhmpzfymlooanrskm46vor7os5 when it's installed as part of git@2.31.1

**Comment by RonRahaman** [comment]
(I was able to install git through spack by specifying my OS's openssl and openssh as a external packages, but that's certainly not a solution to this particular issue :) )

**Comment by ltalirz** [comment]
In case somebody else finds this: I'm seeing the same issue for `spack install krb5@1.20.0` with gcc 12.2.0

- autoreconf, configure, build stages work fine
- at `install` stage I get `Error: InvalidPermissionsError: Attempting to set suid with group writable` (call stack: post_install => set_permissions_by_spec => set_permissions)
- if it helps, the file whose permissions are supposed to be set is `bin/ksu`

Not expecting a fix, just putting it out there in case someone else runs into the same issue

**Comment by nshobe** [comment]
> In case somebody else finds this: I'm seeing the same issue for `spack install krb5@1.20.0` with gcc 12.2.0
> 
> * autoreconf, configure, build stages work fine
> * at `install` stage I get `Error: InvalidPermissionsError: Attempting to set suid with group writable` (call stack: post_install => set_permissions_by_spec => set_permissions)
> * if it helps, the file whose permissions are supposed to be set is `bin/ksu`
> 
> Not expecting a fix, just putting it out there in case someone else runs into the same issue

FWIW, I just ran into this and solved by adding this to my packages.yaml:
```
  krb5:
    permissions:
      read: world
      write: user
```

My "all" is defined as group writable, but that appears to break for some packages such as krb5.
