### ISSUE TITLE
Ocaml fails to build, AutotoolsPackage issue?

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#2994]
Ocaml is `class Ocaml(AutotoolsPackage):`

When I try to build it, using the devel branch of a clone from 20160131, it dies with the following message in the `spack-build.out` file:

```
==> '/isilon/Analysis/scratch/hartzelg/spack/spack-20170131/var/spack/stage/ocaml-4.03.0-ktkzdjwhbav3td6aqi3zeufdhs4g2is3/ocaml-4.03.0/configure' '--prefix=/isilon/Analysis/scratch/hartzelg/spack/spack-20170131/opt/spack/linux-centos7-x86_64/gcc-5.4.0/ocaml-4.03.0-ktkzdjwhbav3td6aqi3zeufdhs4g2is3'
Configuring OCaml version 4.03.0
[ERROR!] configure expects arguments of the form '-prefix /foo/bar', not '-prefix=/foo/bar' (note the '=').
```

Before I dig in, does this ring any bells?

**Comment by hartzell** [comment]
@adamjstewart -- ping?

**Comment by davydden** [comment]
i suppose you need to move it back to `Package` by adding
```
def install(self, spec, prefix):
         configure('-prefix', '{0}'.format(prefix))
 
         make('world.opt')
         make('install')
```
which was removed in https://github.com/LLNL/spack/pull/2845 That looks as a very infrequent usage case.

**Comment by davydden** [comment]
@adamjstewart converted about 300 packages, so one false conversion is not too bad :smile:

**Comment by adamjstewart** [comment]
Ouch, two in one day. Sorry about that. @davydden has the right answer.

**Comment by hartzell** [comment]
I'm a big fan of @adamjstewart's work.  Happy to do the lazy/testing bit....  PR in the works.
