### ISSUE TITLE
Cannot install pkg-1.8.0

### ISSUE THREAD

**Issue by AliE89** [LLNL/spack#29961]
### Steps to reproduce

Hello, I am trying to install gcc@10.2.0 in this simple way:

./spack install gcc@10.2.0

### Error message

==> Installing pkgconf-1.8.0-jbmkldp2jjx6ifcmhykouce3dppplasg
==> No binary for pkgconf-1.8.0-jbmkldp2jjx6ifcmhykouce3dppplasg found: installing from source
==> Using cached archive: /home/edo/software/spack/var/spack/cache/_source-cache/archive/ef/ef9c7e61822b7cb8356e6e9e1dca58d9556f3200d78acab35e4347e9d4c2bbaf.tar.xz
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
/usr/bin/tar: Child returned status 2
/usr/bin/tar: Error is not recoverable: exiting now
==> Error: ProcessError: Command exited with status 2:
    '/usr/bin/tar' '-oxf' '/tmp/edo/spack-stage/spack-stage-pkgconf-1.8.0-jbmkldp2jjx6ifcmhykouce3dppplasg/pkgconf-1.8.0.tar.xz'

### Information on your system

OpenSuse Leap 15.3 installed on WSL.

 ./spack debug report
* **Spack:** 0.18.0.dev0 (bc34bcfbc2240cb23d4fb3029e2f949f8b83eb55)
* **Python:** 3.6.15
* **Platform:** linux-opensuse_leap15-skylake
* **Concretizer:** clingo 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
you're missing `xz`: https://spack.readthedocs.io/en/latest/getting_started.html#system-prerequisites

**Comment by AliE89** [comment]
Thanks, i'll try again this evening 😀

Il Ven 8 Apr 2022, 08:36 Harmen Stoppels ***@***.***> ha
scritto:
