### ISSUE TITLE
Installation issue: intel-oneapi-compilers with intel-oneapi-mpi: MPI for C++ not working

### ISSUE THREAD

**Issue by MarDiehl** [LLNL/spack#29993]
### Steps to reproduce the issue

```console
spack install petsc +libpng +fftw +scalapack +ptscotch -metis -superlu-dist %oneapi ^intel-oneapi-mkl ^intel-oneapi-mpi ^hdf5 + fortran
```

### Error message

<details><summary>Relevant part of `configure.log` from PETSc</summary><pre>
Error testing C++ compiler: Cannot compile Cxx
</pre></details>

Spacks error message is rather generic
<details><summary>Spacks error message</summary><pre>
==> Installing petsc-3.17.0-y7mv43zfbzkfoar3qyva2ehoei4ivjlw
==> No binary for petsc-3.17.0-y7mv43zfbzkfoar3qyva2ehoei4ivjlw found: installing from source
==> Using cached archive: /opt/spack/var/spack/cache/_source-cache/archive/96/96d5aca684e1ce1425891a620d278773c25611cb144165a93b17531238eaaf8a.tar.gz
==> No patches needed for petsc
==> petsc: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/python-3.9.12-ryhfen2bixiapj7jjuddfab3gtapuox5/bin/python3.9' 'configure' '--prefix=/opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/petsc-3.17.0-y7mv43zfbzkfoar3qyva2ehoei4ivjlw' '--with-ssl=0' '--download-c2html=0' '--download-sowing=0' '--download-hwloc=0' 'CFLAGS=' 'FFLAGS=' 'CXXFLAGS=' '--with-cc=/opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/intel-oneapi-mpi-2021.5.1-yqnwmf3onb4fm55gbbkf6bk4lnzx6yrz/mpi/2021.5.1/bin/mpicc' '--with-cxx=/opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/intel-oneapi-mpi-2021.5.1-yqnwmf3onb4fm55gbbkf6bk4lnzx6yrz/mpi/2021.5.1/bin/mpicxx' '--with-fc=/opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/intel-oneapi-mpi-2021.5.1-yqnwmf3onb4fm55gbbkf6bk4lnzx6yrz/mpi/2021.5.1/bin/mpifc' '--with-precision=double' '--with-scalar-type=real' '--with-shared-libraries=1' '--with-debugging=0' '--with-openmp=0' '--with-64-bit-indices=0' 'COPTFLAGS=' 'FOPTFLAGS=' 'CXXOPTFLAGS=' '--with-blas-lapack-lib=/opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/intel-oneapi-mkl-2022.0.2-7zhw3k5tqfxdiyzm7huskknfp755zc47/mkl/2022.0.2/lib/intel64/libmkl_intel_lp64.so /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/intel-oneapi-mkl-2022.0.2-7zhw3k5tqfxdiyzm7huskknfp755zc47/mkl/2022.0.2/lib/intel64/libmkl_sequential.so /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/intel-oneapi-mkl-2022.0.2-7zhw3k5tqfxdiyzm7huskknfp755zc47/mkl/2022.0.2/lib/intel64/libmkl_core.so /lib/x86_64-linux-gnu/libpthread.so /lib/x86_64-linux-gnu/libm.so /lib/x86_64-linux-gnu/libdl.so' '--with-x=0' '--with-clanguage=C' '--with-cuda=0' '--with-hip=0' '--with-metis=0' '--with-hypre=1' '--with-hypre-include=/opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/hypre-2.24.0-awd4zoe3orltawxpyoq3c6os4vutb5ms/include' '--with-hypre-lib=/opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/hypre-2.24.0-awd4zoe3orltawxpyoq3c6os4vutb5ms/lib/libHYPRE.so' '--with-parmetis=0' '--with-kokkos=0' '--with-kokkos-kernels=0' '--with-superlu_dist=0' '--with-ptscotch=1' '--with-ptscotch-include=/opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/scotch-7.0.1-ke42wt64lfdmk6sjuj5v5dhezoq3pyap/include' '--with-ptscotch-lib=/opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/scotch-7.0.1-ke42wt64lfdmk6sjuj5v5dhezoq3pyap/lib/libesmumps.so /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/scotch-7.0.1-ke42wt64lfdmk6sjuj5v5dhezoq3pyap/lib/libptscotch.so /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/scotch-7.0.1-ke42wt64lfdmk6sjuj5v5dhezoq3pyap/lib/libptscotcherr.so /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/scotch-7.0.1-ke42wt64lfdmk6sjuj5v5dhezoq3pyap/lib/libscotch.so /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/scotch-7.0.1-ke42wt64lfdmk6sjuj5v5dhezoq3pyap/lib/libscotcherr.so /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/zlib-1.2.12-yr4fffbpyi74xz6d2di2vtmqlrepbaqx/lib/libz.so' '--with-suitesparse=0' '--with-hdf5=1' '--with-hdf5-include=/opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/hdf5-1.12.1-lgpcjqeujcn24kbp6qxiyj7vzwkia74f/include' '--with-hdf5-lib=/opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/hdf5-1.12.1-lgpcjqeujcn24kbp6qxiyj7vzwkia74f/lib/libhdf5_fortran.so /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/hdf5-1.12.1-lgpcjqeujcn24kbp6qxiyj7vzwkia74f/lib/libhdf5_f90cstub.so /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/hdf5-1.12.1-lgpcjqeujcn24kbp6qxiyj7vzwkia74f/lib/libhdf5.so' '--with-zlib=1' '--with-zlib-include=/opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/zlib-1.2.12-yr4fffbpyi74xz6d2di2vtmqlrepbaqx/include' '--with-zlib-lib=/opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/zlib-1.2.12-yr4fffbpyi74xz6d2di2vtmqlrepbaqx/lib/libz.so' '--with-mumps=0' '--with-trilinos=0' '--with-fftw=1' '--with-fftw-include=/opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/fftw-3.3.10-yb7ukwsjrqqrntuh3ikufflnjfwhrjlw/include' '--with-fftw-lib=/opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/fftw-3.3.10-yb7ukwsjrqqrntuh3ikufflnjfwhrjlw/lib/libfftw3_mpi.so /opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/fftw-3.3.10-yb7ukwsjrqqrntuh3ikufflnjfwhrjlw/lib/libfftw3.so' '--with-valgrind=0' '--with-gmp=0' '--with-libpng=1' '--with-libpng-include=/opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/libpng-1.6.37-rn4fopasnqcuhg47pz24elnonilkdt6u/include' '--with-libpng-lib=/opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/libpng-1.6.37-rn4fopasnqcuhg47pz24elnonilkdt6u/lib/libpng.so' '--with-giflib=0' '--with-mpfr=0' '--with-netcdf=0' '--with-pnetcdf=0' '--with-moab=0' '--with-random123=0' '--with-exodusii=0' '--with-cgns=0' '--with-memkind=0' '--with-p4est=0' '--with-saws=0' '--with-yaml=0' '--with-hwloc=0' '--with-libjpeg=0' '--with-scalapack=1' '--with-scalapack-lib=/opt/spack/opt/spack/linux-ubuntu20.04-sandybridge/oneapi-2022.0.0/netlib-scalapack-2.2.0-medelrkyzdxigbhoutpllpvuza5qbnhu/lib/libscalapack.so' '--with-strumpack=0' '--with-mmg=0' '--with-parmmg=0' '--with-tetgen=0'
See build log for details:
  /tmp/m.diehl/spack-stage/spack-stage-petsc-3.17.0-y7mv43zfbzkfoar3qyva2ehoei4ivjlw/spack-build-out.txt
</pre></details>

### Information on your system

* **Spack:** 0.18.0.dev0 (3ad3e53ff810ae9047882cabda2ecf929a4b0a65)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-sandybridge
* **Concretizer:** clingo

### Additional information

The problem occurs when compiling PETSc, but it is not directly related to it. The issue is rather related to the names of the compilers and MPI compiler wrappers.

For the new, Clang-based compilers, `I_MPI_CXX` needs to be set `icpx`. This does not work for `mpicxx` which raises the error `Error: unsupported compiler name 'icpx'`.

The source of the issues is in https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/intel-oneapi-mpi/package.py: The names of the compiler wrappers are the generic names `mpicc`, `mpicxx`, `mpif77`, `mpif90`, and `mpifc`. However, Intel MPI also has specific names `mpiicc`, `mpiicpc`, and `mpiifort`. To me, it seems that they should be preferred. At least `mpiicpc` works with `I_MPI_CXX=icpx`.

@rscohn2: Are you aware of any problems when using the Intel specific wrapper names? Otherwise, it seems to be a straight forward fix.

@balay, @barrysmith, @jedbrown: Not sure if you are aware of this already

[configure.log](https://github.com/spack/spack/files/8458663/configure.log)
[spack-build-out.txt](https://github.com/spack/spack/files/8458665/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by MarDiehl** [comment]
[spack-build-env.txt](https://github.com/spack/spack/files/8458711/spack-build-env.txt)

**Comment by rscohn2** [comment]
I am checking with the mpi team if there are any issues with switching.

**Comment by rscohn2** [comment]
The MPI team believes it will be ok, but suggests we give the user the ability to switch back. I think it could be done with a boolean variant that defaults to mpiicpc/mpiicc. I can do this next week, but feel free submit a PR if you have time.

**Comment by markyoder** [comment]
I get a similar problem. Relevant error being:

```
TESTING: checkCCompiler from config.setCompilers(config/BuildSystem/config/setCompilers.py:1341)
*******************************************************************************
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
C compiler you provided with -with-cc=/scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64/intel-2021.7.0/mpich-4.0.2-phvyqp42jr3d54lzxr4jxarxupnhp5fj/bin/mpicc cannot be found or does not work.
Cannot compile/link C with /scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64/intel-2021.7.0/mpich-4.0.2-phvyqp42jr3d54lzxr4jxarxupnhp5fj/bin/mpicc.
*******************************************************************************
```

But that compiler is definitely available:
```
(base) [myoder96@sh03-05n18 /scratch/users/myoder96/spack_dev] (job 66995398) $ /scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64/intel-2021.7.0/mpich-4.0.2-phvyqp42jr3d54lzxr4jxarxupnhp5fj/bin/mpicc --version
icc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is deprecated and will be removed from product release in the second half of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the recommended compiler moving forward. Please transition to use this compiler. Use '-diag-disable=10441' to disable this message.
icc (ICC) 2021.7.0 20220726
Copyright (C) 1985-2022 Intel Corporation.  All rights reserved.
```

**Comment by markyoder** [comment]
And I guess this is my error, from the `configure.log`. 

```
Executing: /scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64/intel-2021.7.0/mpich-4.0.2-phvyqp42jr3d54lzxr4jxarxupnhp5fj/bin/mpicc  -o /tmp/petsc-0ijfa3hv/config.setCompilers/conftest   -we147 -diag-disable=10441 /tmp/petsc-0ijfa3hv/config.setCompilers/conftest.o
Possible ERROR while running linker:exit code 0
stderr:
icc: command line warning #10148: option '-march=x86-64' not supported
Linker output before filtering:

icc: command line warning #10148: option '-march=x86-64' not supported
:
Linker output after filtering:
icc: command line warning #10148: option '-march=x86-64' not supported:
          Error testing C compiler: Cannot compile/link C with /scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64/intel-2021.7.0/mpich-4.0.2-phvyqp42jr3d54lzxr4jxarxupnhp5fj/bin/mpicc.
             MPI compiler wrapper /scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64/intel-2021.7.0/mpich-4.0.2-phvyqp42jr3d54lzxr4jxarxupnhp5fj/bin/mpicc failed to compile
Executing: /scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64/intel-2021.7.0/mpich-4.0.2-phvyqp42jr3d54lzxr4jxarxupnhp5fj/bin/mpicc -show
stdout: /scratch/users/myoder96/spack_dev/spack/lib/spack/env/intel/icc -I/scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64/intel-2021.7.0/mpich-4.0.2-phvyqp42jr3d54lzxr4jxarxupnhp5fj/include -L/scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64/intel-2021.7.0/mpich-4.0.2-phvyqp42jr3d54lzxr4jxarxupnhp5fj/lib -Wl,-rpath -Wl,/scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64/intel-2021.7.0/mpich-4.0.2-phvyqp42jr3d54lzxr4jxarxupnhp5fj/lib -lmpi
             MPI compiler wrapper /scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64/intel-2021.7.0/mpich-4.0.2-phvyqp42jr3d54lzxr4jxarxupnhp5fj/bin/mpicc is likely incorrect.
  Use --with-mpi-dir to indicate an alternate MPI.
            Deleting "CC"
*******************************************************************************
         UNABLE to CONFIGURE with GIVEN OPTIONS    (see configure.log for details):
-------------------------------------------------------------------------------
C compiler you provided with -with-cc=/scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64/intel-2021.7.0/mpich-4.0.2-phvyqp42jr3d54lzxr4jxarxupnhp5fj/bin/mpicc cannot be found or does not work.
Cannot compile/link C with /scratch/users/myoder96/spack_dev/spack/opt/spack/linux-centos7-x86_64/intel-2021.7.0/mpich-4.0.2-phvyqp42jr3d54lzxr4jxarxupnhp5fj/bin/mpicc.
*******************************************************************************
  File "/tmp/myoder96/spack-stage/spack-stage-petsc-3.18.1-z5za56l4qb3y4jdmy6rvhfvljbgwimkz/spack-src/config/configure.py", line 461, in petsc_configure
    framework.configure(out = sys.stdout)
  File "/tmp/myoder96/spack-stage/spack-stage-petsc-3.18.1-z5za56l4qb3y4jdmy6rvhfvljbgwimkz/spack-src/config/BuildSystem/config/framework.py", line 1412, in configure
    self.processChildren()
  File "/tmp/myoder96/spack-stage/spack-stage-petsc-3.18.1-z5za56l4qb3y4jdmy6rvhfvljbgwimkz/spack-src/config/BuildSystem/config/framework.py", line 1400, in processChildren
    self.serialEvaluation(self.childGraph)
  File "/tmp/myoder96/spack-stage/spack-stage-petsc-3.18.1-z5za56l4qb3y4jdmy6rvhfvljbgwimkz/spack-src/config/BuildSystem/config/framework.py", line 1375, in serialEvaluation
    child.configure()
  File "/tmp/myoder96/spack-stage/spack-stage-petsc-3.18.1-z5za56l4qb3y4jdmy6rvhfvljbgwimkz/spack-src/config/BuildSystem/config/setCompilers.py", line 2712, in configure
    self.executeTest(self.checkCCompiler)
  File "/tmp/myoder96/spack-stage/spack-stage-petsc-3.18.1-z5za56l4qb3y4jdmy6rvhfvljbgwimkz/spack-src/config/BuildSystem/config/base.py", line 138, in executeTest
    ret = test(*args,**kargs)
  File "/tmp/myoder96/spack-stage/spack-stage-petsc-3.18.1-z5za56l4qb3y4jdmy6rvhfvljbgwimkz/spack-src/config/BuildSystem/config/setCompilers.py", line 1346, in checkCCompiler
    for compiler in self.generateCCompilerGuesses():
  File "/tmp/myoder96/spack-stage/spack-stage-petsc-3.18.1-z5za56l4qb3y4jdmy6rvhfvljbgwimkz/spack-src/config/BuildSystem/config/setCompilers.py", line 1274, in generateCCompilerGuesses
    raise RuntimeError('C compiler you provided with -with-cc='+self.argDB['with-cc']+' cannot be found or does not work.'+'\n'+self.mesg)
================================================================================
Finishing configure run at Fri, 04 Nov 2022 13:22:40 -0700
================================================================================
```

**Comment by balay** [comment]
How do I reproduce this issue?

I just tried the following and got a working build
```
[balay@pj01 spack.orig]$ ./bin/spack install -j12 petsc%oneapi@2022.2.0 ^intel-oneapi-mpi ^intel-oneapi-mkl
<snip>
==> Installing petsc-3.18.1-ueg7d5yzitpdqjmsiajmsxgw4ttcaamy
==> No binary for petsc-3.18.1-ueg7d5yzitpdqjmsiajmsxgw4ttcaamy found: installing from source
==> Fetching http://ftp.mcs.anl.gov/pub/petsc/release-snapshots/petsc-3.18.1.tar.gz
==> No patches needed for petsc
==> petsc: Executing phase: 'configure'
==> petsc: Executing phase: 'build'
==> petsc: Executing phase: 'install'
==> petsc: Successfully installed petsc-3.18.1-ueg7d5yzitpdqjmsiajmsxgw4ttcaamy
  Fetch: 1.44s.  Build: 7m 39.58s.  Total: 7m 41.02s.
[+] /home/balay/spack.orig/opt/spack/linux-fedora37-skylake/oneapi-2022.2.0/petsc-3.18.1-ueg7d5yzitpdqjmsiajmsxgw4ttcaamy
```

**Comment by balay** [comment]
And likely the following patch to petsc configure will ignore the warning..
```patch
diff --git a/config/BuildSystem/config/framework.py b/config/BuildSystem/config/framework.py
index e0af53c08da..61a56edd63d 100644
--- a/config/BuildSystem/config/framework.py
+++ b/config/BuildSystem/config/framework.py
@@ -524,6 +524,7 @@ class Framework(config.base.Configure, script.LanguageProcessor):
       #Intel
       lines = [s for s in lines if s.find(": command line warning #10121: overriding") < 0]
       lines = [s for s in lines if s.find(': remark #10441:') < 0]
+      lines = [s for s in lines if s.find(": command line warning #10148: option '-march=x86-64' not supported") < 0]
       # PGI: Ignore warning about temporary license
       lines = [s for s in lines if s.find('license.dat') < 0]
       # Cray XT3
```

**Comment by balay** [comment]
This issue is likely fixed by https://github.com/spack/spack/pull/33556

**Comment by markyoder** [comment]
Looks like the recent PR fixed this. Thanks to everybody who helped! Much, much, much appreciated!
