### ISSUE TITLE
Installation issue: Incomplete version in depends_on clause in py-scipy/package.py causes failure to find py-pypthran source.

### ISSUE THREAD

**Issue by jgalarowicz** [LLNL/spack#30054]
### Steps to reproduce the issue

When we build survey one of the depends_on clauses causes py-scipy to be built and it tries to bring in py-pythran version 0.10.0, but it is only specified as version 0.10.  On some platforms this works, but on others it fails to find version 0.10.

### Error message

```
==> Installing py-pythran-0.10-dexcg4mtapdf63elx7g63dmvtzkq6olh
==> No binary for py-pythran-0.10-dexcg4mtapdf63elx7g63dmvtzkq6olh found: installing from source
==> Warning: There is no checksum on file to fetch py-pythran@0.10 safely.
==>   Fetch anyway? [y/N] y
==> Cannot find version 0.10 in url_list
==> Error: FetchError: All fetchers failed for spack-stage-py-pythran-0.10-dexcg4mtapdf63elx7g63dmvtzkq6olh

/home/jeg/spack/lib/spack/spack/package.py:1400, in do_fetch:
       1397
       1398        self.stage.create()
       1399        err_msg = None if not self.manual_download else self.download_instr
  >>   1400        start_time = time.time()
       1401        self.stage.fetch(mirror_only, err_msg=err_msg)
       1402        self._fetch_time = time.time() - start_time
       1403
```

### Information on your system

* **Spack:** 0.18.0.dev0 (0480afe29d772ef03471b3a3ae747ad15bab18a5)
* **Python:** 3.10.2
* **Platform:** linux-fedora35-icelake
* **Concretizer:** clingo

### Additional information

@adamjstewart Hi Adam - I saw you are a maintainer of py-scipy.  So, assigned this issue to you.    Seems to work on some machines but not on others.   Dave Montoya is seeing it on Darwin at LANL.  I'm seeing it on my laptop and another system at Creative C.

Suggested change that allows py-pythran source to be found:

in "py-scipy/package.py" line 64
```python
depends_on('py-pythran@0.10', when='@1.8:', type=('build', 'link'))
```
should be:
```python
depends_on('py-pythran@0.10.0', when='@1.8:', type=('build', 'link'))
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
I'm unable to reproduce this on my system. I'm guessing that this bug only affects the old concretizer. Can you check if the systems where you're encountering this issue are using the original concretizer instead of clingo? `spack debug report` should tell you the answer.

**Comment by jgalarowicz** [comment]
@adamjstewart Yes, you are correct.  When I change back to clingo, spack can find the 0.10.0 version even if the depends_on specifies 0.10.    We have had problems at the national labs using clingo, so that is where the issue was discovered.  I must have be experimenting on my laptop with original instead of clingo.    Sorry for the bother with this.

**Comment by adamjstewart** [comment]
> We have had problems at the national labs using clingo

If you haven't already, please open issues for these and tag @alalazo. We're trying to push pretty hard to make clingo the concretizer of choice and remove the original concretizer. The new concretizer solves many issues in Spack, including the one you found here.

So if you just want to get things working on your system, using `@0.10.0:0.10` or `@0.10.0` should work, but I don't think we'll want to change that globally in Spack since hundreds of packages use the new syntax.

**Comment by jgalarowicz** [comment]
@adamjstewart Ok.  Thank you!  I will close this.
