### ISSUE TITLE
Installation issue: mpich fails to build with gcc 11.2.0

### ISSUE THREAD

**Issue by grondo** [LLNL/spack#30079]
### Steps to reproduce the issue
```console
$ spack install mpich
```

```console
$ spack spec -I mpich
Input spec
--------------------------------
mpich

Concretized
--------------------------------
xg2xsj5  mpich@4.0.2%gcc@11.2.0~argobots+fortran+hwloc+hydra+libxml2+pci+romio~slurm~two_level_namespace~verbs+wrapperrpath device=ch4 netmod=ofi pmi=pmi arch=linux-rhel7-broadwell
y2qcz2u      ^findutils@4.8.0%gcc@11.2.0 patches=440b954 arch=linux-rhel7-broadwell
jtfoifu      ^hwloc@2.7.1%gcc@11.2.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~opencl+pci~rocm+shared arch=linux-rhel7-broadwell
rtfc3ow          ^libpciaccess@0.16%gcc@11.2.0 arch=linux-rhel7-broadwell
czlmttl              ^libtool@2.4.7%gcc@11.2.0 arch=linux-rhel7-broadwell
ypbrhe7                  ^m4@1.4.19%gcc@11.2.0+sigsegv patches=9dc5fbd,bfdffa7 arch=linux-rhel7-broadwell
ben4t7e                      ^libsigsegv@2.13%gcc@11.2.0 arch=linux-rhel7-broadwell
pz3xgy3              ^pkgconf@1.8.0%gcc@11.2.0 arch=linux-rhel7-broadwell
ppqkatw              ^util-macros@1.19.3%gcc@11.2.0 arch=linux-rhel7-broadwell
btacoo3          ^libxml2@2.9.12%gcc@11.2.0~python arch=linux-rhel7-broadwell
hdgtr33              ^libiconv@1.16%gcc@11.2.0 libs=shared,static arch=linux-rhel7-broadwell
jcv5sej              ^xz@5.2.5%gcc@11.2.0~pic libs=shared,static arch=linux-rhel7-broadwell
7hu34rq              ^zlib@1.2.12%gcc@11.2.0+optimize+pic+shared patches=0d38234 arch=linux-rhel7-broadwell
4uphwdi          ^ncurses@6.2%gcc@11.2.0~symlinks+termlib abi=none arch=linux-rhel7-broadwell
kxvh2gt      ^libfabric@1.14.0%gcc@11.2.0~debug~kdreg fabrics=sockets,tcp,udp arch=linux-rhel7-broadwell
```

### Error message

<details><summary>Error message</summary><pre>
==> Installing mpich-4.0.2-xg2xsj54syl5s7akfexidbez46zguvh2
==> No binary for mpich-4.0.2-xg2xsj54syl5s7akfexidbez46zguvh2 found: installing from source
==> Using cached archive: /p/vast1/grondo/spack/var/spack/cache/_source-cache/archive/5a/5a42f1a889d4a2d996c26e48cbf9c595cbf4316c6814f7c181e3320d21dedd42.tar.gz
==> No patches needed for mpich
==> mpich: Executing phase: 'autoreconf'
==> mpich: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/var/tmp/grondo/spack-stage/spack-stage-mpich-4.0.2-xg2xsj54syl5s7akfexidbez46zguvh2/spack-src/configure' '--prefix=/p/vast1/grondo/spack/opt/spack/linux-rhel7-broadwell/gcc-11.2.0/mpich-4.0.2-xg2xsj54syl5s7akfexidbez46zguvh2' '--without-cuda' '--disable-silent-rules' '--enable-shared' '--with-hwloc-prefix=/p/vast1/grondo/spack/opt/spack/linux-rhel7-broadwell/gcc-11.2.0/hwloc-2.7.1-jtfoifu3blfvuzkyjfzvfgmbwa5th56c' '--with-pm=hydra' '--enable-romio' '--without-ibverbs' '--enable-wrapper-rpath=yes' '--with-slurm=no' '--with-pmi=simple' '--with-device=ch4:ofi' '--with-libfabric=/p/vast1/grondo/spack/opt/spack/linux-rhel7-broadwell/gcc-11.2.0/libfabric-1.14.0-kxvh2gtikgrezybjewps7svo7cstwidq' '--enable-libxml2'

1 error found in build log:
     612    checking for shared library (esp. rpath) characteristics of F77...
            done (results in src/env/f77_shlib.conf)
     613    checking whether Fortran 77 accepts ! for comments... yes
     614    checking for include directory flag for Fortran... -I
     615    checking for Fortran 77 flag for library directories... -L
     616    checking whether Fortran 77 compiler processes .F files with C prep
            rocessor... yes
     617    checking whether /p/vast1/grondo/spack/lib/spack/env/gcc/gfortran a
            llows mismatched arguments... yes, with -fallow-argument-mismatch
  >> 618    configure: error: The Fortran compiler /p/vast1/grondo/spack/lib/sp
            ack/env/gcc/gfortran does not accept programs that call the same ro
            utine with arguments of different types without the option -fallow-
            argument-mismatch.  Rerun configure with FFLAGS=-fallow-argument-mi
            smatch and FCFLAGS=-fallow-argument-mismatch
</pre></details>

### Information on your system

* **Spack:** 0.18.0.dev0 (bb70e6ffcd6e6920b24677593a35987d1eb05ce1)
* **Python:** 3.7.2
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** clingo

### Additional information

cc: @raffenet @yfguo

[spack-build-env.txt](https://github.com/spack/spack/files/8492431/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/8492432/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by michaelkuhn** [comment]
Fixed by #30084.
