### ISSUE TITLE
Apple M1 processor not detected correctly in Rosetta 2 emulator mode

### ISSUE THREAD

**Issue by climbfuji** [LLNL/spack#30076]
### Summary

When using the Rosetta 2 emulator to work in a `x86_64` environment on an Apple M1 system, `spack` complains about not being able to detect the CPU:
```
...
==> Ran patch() for m4
sysctl: unknown oid 'machdep.cpu.leaf7_features'
sysctl: unknown oid 'machdep.cpu.vendor'
sysctl: unknown oid 'machdep.cpu.model'
==> m4: Executing phase: 'autoreconf'
sysctl: unknown oid 'machdep.cpu.leaf7_features'
sysctl: unknown oid 'machdep.cpu.vendor'
sysctl: unknown oid 'machdep.cpu.model'
==> m4: Executing phase: 'configure'
...
```
This doesn't seem to hurt, but the messages are annoying.

### Rationale

`spack` should be able to detect an Apple M1 processor in Rosetta 2 emulator mode.

### Additional information

```
> spack --version
sysctl: unknown oid 'machdep.cpu.leaf7_features'
sysctl: unknown oid 'machdep.cpu.vendor'
sysctl: unknown oid 'machdep.cpu.model'
0.18.0.dev0 (44f631d7161e0715ff121ffe3ba3368c2c5b130f)
```

```
> spack debug report
sysctl: unknown oid 'machdep.cpu.leaf7_features'
sysctl: unknown oid 'machdep.cpu.vendor'
sysctl: unknown oid 'machdep.cpu.model'
* **Spack:** 0.18.0.dev0 (44f631d7161e0715ff121ffe3ba3368c2c5b130f)
* **Python:** 3.9.10
* **Platform:** darwin-monterey-x86_64
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
Can you move the issue to https://github.com/archspec/archspec and close it here ?

**Comment by climbfuji** [comment]
Replaced by https://github.com/archspec/archspec/issues/76.
