### ISSUE TITLE
Non-existent system tools should be provided by spack

### ISSUE THREAD

**Issue by mathstuf** [LLNL/spack#301]
On some machines, CMake is not available. In this case, `spack.cmake` is `None`. Instead, `spack` should use a function which installs spack's cmake package and uses that instead. Other build tools such as `scons`, `perl`, or other such bits (and maybe even compilers) should also probably act similarly.

**Comment by eschnett** [comment]
To simplify things -- can the packages that use `cmake` simply depend on it?

Once spack has build-time dependencies, this would become even cleaner.

**Comment by mathstuf** [comment]
They could, but then `spack.cmake` would need some magic to call the built cmake rather than just `which("cmake")` (which may be different based on version requirements).

**Comment by eschnett** [comment]
Some packages require certain versions of cmake... Using spack-packaged cmake would simplify this as well.

**Comment by mathstuf** [comment]
Fixed by bb968fc5a2bf2ceb585676646f68ec2029a298b1.
