### ISSUE TITLE
WISH: spack install defaulting to --jobs=$SPACK_PARALLEL_JOBS

### ISSUE THREAD

**Issue by HenrikBengtsson** [LLNL/spack#3010]
The number of parallel jobs when installing can be controlled as:
```sh
spack install --jobs <njobs> foo
```
If `--jobs` is not specified, the [default is to make use of all cores on the machine](https://github.com/LLNL/spack/blob/v0.10.0/lib/spack/spack/build_environment.py#L355) using `multiprocessing.cpu_count()`.

I'd like to propose that the default could be controlled via an environment variable, e.g. `SPACK_PARALLEL_JOBS` such that if it is set, it's value will be used instead of `multiprocessing.cpu_count()`.

The advantage of `SPACK_PARALLEL_JOBS` is that one don't have to specify `--jobs` explicitly.  If a shared system has a build machine with multiple users, sysadm can set the default number of parallel jobs to say, `SPACK_PARALLEL_JOBS=4`.  If building via a scheduler such as TORQUE / PBS, one set it as `export SPACK_PARALLEL_JOBS=$PBS_NUM_PPN`.

PS. Parallel jobs can be [disabled using `SPACK_NO_PARALLEL_MAKE=true`](https://github.com/LLNL/spack/blob/v0.10.0/lib/spack/spack/build_environment.py#L112-L113).  This could be replaced with `SPACK_PARALLEL_JOBS=1`.

**Comment by adamjstewart** [comment]
Can we add this as a setting in `~/.spack/config.yaml`? It's one of the oldest requested features. See #327.

**Comment by HenrikBengtsson** [comment]
Thxs for the pointer to Issue #327.  Even if this could be configured in a `~/.spack/config.yaml`, which certainly makes life nice for a savvy user, I'd still argue for an environment variable as well, because that can be set in startup scripts etc without modifying user's files.  (Writing this, I realize that I'm not a big fan of I-will-use-all-cores-without-worring-about-others behavior)

**Comment by alalazo** [comment]
While we are discussing this, would it make sense to have an environment variable for **every** option in `config.yaml`? The precedence order should be the one suggested by @HenrikBengtsson : an environment variable overrides the corresponding entry in `config.yaml`. Honestly, I see  a lot of uses for that...

**Comment by tgamblin** [comment]
If it's stuff that doesn't really affect the build I don't see too much wrong with it.  If it's something that can cause a compile to go subtly wrong (`--dirty` is the closest one to that) I'd really rather keep it a config option.  

Either way, if we did it, I think `spack config get config` should be enhanced to show merges from the environment and to show blame for each line in the ultimate YAML config (e.g., this setting comes from `~/.spack/config.yaml`, this one from `SPACK_DIRTY`, etc.)
