### ISSUE TITLE
require_url_format() fails to take into account valid SSH paths

### ISSUE THREAD

**Issue by benpm** [LLNL/spack#30133]
[`require_url_format()`](https://github.com/spack/spack/blob/3835ac0c41ce57dda16de98c40b69dac5d26d34a/lib/spack/spack/util/url.py#L345) in lib/spack/util/url.py fails to take into account valid SSH path values such as `"git@github.com:spack/spack.git"`. Up until this function was added, I've been successfully using values like this in the `git=` property of my packages.

Commit that added this function: 4aee27816e7101753aeb392e868096236a26d84d. I've confirmed my package does indeed build and install correctly before this commit.

Error I get when trying to install my package: `==> Error: Invalid url format from url:` (tested on a4f32dbf8d3ed3a28692caa09a00560096452168)

I'd like to propose that since the `git=` property is not actually always a URL, that URL validation should not be run for it.

**Comment by alalazo** [comment]
Pinging @scheibelp and @johnwparent since, if I recall correctly, this was added as part of the Windows support.

**Comment by robers97** [comment]
I'm running into this too and am not sure of a workaround.
git clone git@github.com:HPC/mini-HACC.git  works, 

SPACK returns
==> Error: Invalid url format from URL

I haven't been able pull the bits out of github with any other syntax.

**Comment by tldahlgren** [comment]
I am able to reproduce the problem in an existing package that I tweaked (i.e., changed the `url` property to use that form).

A quick fix allows me to get past the error; however, I am prompted for my SSH passphrase, which could be problematic for packages contributed back to Spack.

@scheibelp What do you think?

**Comment by scheibelp** [comment]
Using `git = "ssh://git@github.com:spack/spack.git"` should work (i.e. prepending `ssh://`). I assume @tldahlgren that's what you mean by a quick fix; the password prompt AFAIK is expected - @benpm I assume you have ssh keys configured for git interaction, but let me know if prepending `ssh://` does not produce a satisfactory result.

**Comment by benpm** [comment]
> Using `git = "ssh://git@github.com:spack/spack.git"` should work (i.e. prepending `ssh://`). I assume @tldahlgren that's what you mean by a quick fix; the password prompt AFAIK is expected - @benpm I assume you have ssh keys configured for git interaction, but let me know if prepending `ssh://` does not produce a satisfactory result.

using ssh:// does indeed work

**Comment by vectorflux** [comment]
I have the same problem, namely Error: Invalid url format from url: git@github.com:C2SM/icon-exclaim.git.  It can be cloned by hand fine.  But the prefix "ssh://" does not work for me:  git = "ssh://git@github.com:C2SM/icon-exclaim.git"  give the error:  "ssh: Could not resolve hostname github.com:C2SM"  (and it cannot be cloned by hand with the prefix).  Am I missing something obvious?

**Comment by johnwparent** [comment]
Closing this as `require_url_format` is no longer in the codebase as of #34452
