### ISSUE TITLE
run_env.unset() produce a warning

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#3014]
subj
```
==> Warning: Cannot handle command of type <class 'spack.environment.UnsetEnv'>: skipping request
==> Warning: run_env.unset('PETSC_ARCH') at /home/davydden/spack/var/spack/repos/builtin/packages/petsc/package.py:240
```

**Comment by adamjstewart** [comment]
See https://github.com/LLNL/spack/issues/2767#issuecomment-271043075. I think we determined that it's a warning coming from Dotkit. Variable unsetting works fine in Modules, but doesn't work for Dotkit. The warning is safe to ignore. @tgamblin Why do we default to Modules + Dotkit? Does anyone use Dotkit?

**Comment by davydden** [comment]
thanks for the link, i forgot that we actually discussed it.

**Comment by adamjstewart** [comment]
@davydden Can this be closed?
