### ISSUE TITLE
Unable to build ncurses 6.0 with Intel compiler

### ISSUE THREAD

**Issue by weijianwen** [LLNL/spack#3017]
I failed to build ncurses 6.0 with Intel compiler 16.0.3. Has anyone encountered similar issues? Part of the erorr messages are as follows.

```
$ spack install ncurses %intel@16.0.3
...
/bin/sh ./run_tic.sh
/bin/sh -c 'for name in *.pc; do /usr/bin/install -c -m 644 $name /lustre/spack/sandybridge/linux-centos7-x86_64/intel-16.0.3/ncurses-6.0-vzmgon2fmla4wblduj4r7lzamcoponm6/lib/pkgconfig/$name; done'
** Building terminfo database, please wait...
Running sh ./shlib tic to install /lustre/spack/sandybridge/linux-centos7-x86_64/intel-16.0.3/ncurses-6.0-vzmgon2fmla4wblduj4r7lzamcoponm6/share/terminfo ...

        You may see messages regarding extended capabilities, e.g., AX.
        These are extended terminal capabilities which are compiled
        using
                tic -x
        If you have ncurses 4.2 applications, you should read the INSTALL
        document, and install the terminfo without the -x option.

./shlib: line 141: 181458 Segmentation fault      (core dumped) tic -x -s -o /lustre/spack/sandybridge/linux-centos7-x86_64/intel-16.0.3/ncurses-6.0-vzmgon2fmla4wblduj4r7lzamcoponm6/share/terminfo terminfo.tmp
? tic could not build /lustre/spack/sandybridge/linux-centos7-x86_64/intel-16.0.3/ncurses-6.0-vzmgon2fmla4wblduj4r7lzamcoponm6/share/terminfo
make[1]: *** [install.data] Error 1
make[1]: Leaving directory `/tmp/rpm/pytest-of-rpm/pytest-4/test_fetch0/tmp/spack-stage/spack-stage-HvKJK2/ncurses-6.0/misc'
make: *** [install] Error 2
````

**Comment by weijianwen** [comment]
Similar issue is found on LFS mail list http://archive.linuxfromscratch.org/mail-archives/lfs-support/2006-August/031270.html . Following the instruction, I can reproduce this segment fault directly.

```
$ cd /tmp/rpm/pytest-of-rpm/pytest-4/test_fetch0/tmp/spack-stage/spack-stage-HvKJK2/ncurses-6.0/
$ module load icc/16.0; export LD_LIBRARY_PATH=./progs:./lib:$LD_LIBRARY_PATH
$ ./progs/tic -x -s -o
[1]    218671 segmentation fault (core dumped)  ./progs/tic -x -s -o
```

**Comment by pramodk** [comment]
just curious : what is final package you are trying to build? I mean,  whether ncurses is dependency of some other "main" package ?

What I have seen is that many packages doesn't build with proprietary compilers and better to use `GNU` compiler for those.

**Comment by weijianwen** [comment]
I am building the `r` package against GCC and Intel compiler separately. If this issue can be reproduced by other users, I'll submit a bug report to ncurses.

**Comment by weijianwen** [comment]
Bulding ncurses-6.0 with Intel Compiler fails too, giving same error messages. Time for me to submit a bug report to ncurses.

```
$ cd ncurses-6.0
$ module load icc/16.0
$ ./configure --prefix=/tmp/usr  '--with-shared' '--with-cxx-shared' '--enable-widec' '--enable-overwrite' '--disable-lib-suffixes' '--without-ada' '--enable-pc-files'
$ make clean; make -j16
... (OK)
$ make install
...
** Building terminfo database, please wait...
Running sh ./shlib tic to install /tmp/usr/share/terminfo ...

        You may see messages regarding extended capabilities, e.g., AX.
        These are extended terminal capabilities which are compiled
        using
                tic -x
        If you have ncurses 4.2 applications, you should read the INSTALL
        document, and install the terminfo without the -x option.

./shlib: line 141: 245331 Segmentation fault      (core dumped) tic -x -s -o /tmp/usr/share/terminfo terminfo.tmp
? tic could not build /tmp/usr/share/terminfo
make[1]: *** [install.data] Error 1
make[1]: Leaving directory `/tmp/ncurses-6.0/misc'
make: *** [install] Error 2
```

**Comment by weijianwen** [comment]
My bug report to ncurses can be seen on http://lists.gnu.org/archive/html/bug-ncurses/2017-02/msg00008.html . 

I got a reply from Thomas Dickey. He said this issues cannot be reproduced in Inte version 17.  I tried the following approaches but failed.

1. Upgrade Intel Compiler 16 to the latest update 4 (16.0.4). 
2. Rebuild ncurses with environment variables given by Thomas.

```
#!/bin/sh
TOP=/lustre/usr/intel/16u4
export PATH=$TOP/bin:$PATH
export CPPFLAGS="$CPPFLAGS -DNO_IDENT"
export LD_LIBRARY_PATH=$TOP/lib/intel64:$LD_LIBRARY_PATH
export LIBRARY_PATH=$TOP/lib:$LIBRARY_PATH
export C_INCLUDE_PATH=$TOP/include
export CPLUS_INCLUDE_PATH=$TOP/include:$TOP/include/c++
export CC=icc
export CXX=icpc
./configure --prefix=/tmp/usr
make clean
make -j16
make install
```

Poor Intel 16...

**Comment by weijianwen** [comment]
After removing `--with-shared` flag from ncurses flags, I've successfully built and intalled nurses against Intel 16. However, providing ncurses static libraries doesn't sound a good idea for its dependent libs in Spack. What do you think?

If this workaround goes well, I'd like to add a vairant to ncurses which toogles shared library building.

**Comment by adamjstewart** [comment]
Most of those environment variables won't make a difference because Spack unsets them to prevent the wrong dependencies from being picked up. Following [this thread](https://groups.google.com/forum/#!searchin/spack/intel%7Csort:relevance/spack/NxyNTAZyMQg/Cfuj063k70sJ) was very helpful when I first started using Spack. Go into the bin directory (`compilers_and_libraries_2017.1.132/linux/bin/intel64` for Intel 17.0.1, just change the version number). Now add files called `icc.cfg`, `icpc.cfg`, and `ifort.cfg` containing:
```
-Xlinker -rpath -Xlinker /blues/gpfs/home/software/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-4.4.7/intel-parallel-studio-professional.2017.1-zaq5tbp664b2ye2gdx3ry35t3wd4rjn4/compilers_and_libraries_2017.1.132/linux/compiler/lib/intel64_lin
```
Obviously change the paths to match your installation directory and library directory. This forces the Intel compilers to RPATH their own libraries during installation, making environment variables obsolete. If you install your Intel compilers with Spack, it does this automatically for you.

Using these settings, I just installed ncurses 6.0 with Intel 17.0.1 and Intel 16.0.1 on CentOS 6.8 with no problems.

**Comment by weijianwen** [comment]
Thank you, @adamjstewart . I reinstalled `intel-parallel-studio@2015.6`, `intel-parallel-studio-studio@2016.4` and `intel-parallel-studio@2017.1` via spack. Sure `icc.cfg` have been set automatically. `2015.6` and `2017.1` have built ncurses successfully, while `2016.4` fails.

During installation, the following segment fault arises in the kernel message. Similar messages appear during in #3018 and #3036 , which leads to installation failures.
 
```
[1546607.904642] tic[106671]: segfault at b0 ip 00007f0aaf08c65e sp 00007fff6c120558 error 4 in libc-2.17.so[7f0aaf003000+1b6000]
```

I will close this issue. I plan to enable coredump and check what is going on.
