### ISSUE TITLE
Quick question: is Spack in a release freeze?

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#3021]
Hi All,

I have a handful of small PR's pending (#2993, #2995, #2997, #3020 (fresh)) that haven't been merged.

I also noticed that develop hasn't picked up any commits recently.

Is it frozen while people work on the 1.0 release?  Or, to the same end, are all hands working on the release?  If so, are there plans for when "the logjam will burst" :)?

Thanks (as always)!

**Comment by tgamblin** [comment]
A number of us have been at a big U.S. exascale project meeting this week in Knoxville.  We'll be getting back to PRs soon!
