### ISSUE TITLE
scripts in view for python extensions should reference path to the python command in the view's bin directory

### ISSUE THREAD

**Issue by lee218llnl** [LLNL/spack#30256]
### Summary

When I create an environment with python and a bunch of extensions, the resulting python scripts in the view's bin directory do not reference the path to python in the environment's bin directory, but rather reference the full path to the underlying python installation. This has the effect that the necessary site-packages for the script are not found, since the underlying python installation is just the bare interpreter (i.e., the site-packages directory is not populated with the extensions). It seems like the python scripts in the view's bin directory should be modified to reference the path to python via the environment's bin directory.

$ spack --version
0.18.0.dev0 (be99a72d5741ab2d09ee1daac8a2439fc73ef31c)

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
I wonder if this is why I've been having issues getting `mypy` to detect type hints for libraries I have installed in an environment.

**Comment by haampie** [comment]
Can you give an example? For me:

```
$ head -n1 $(grep -rIzl '^#!' .spack-env/view/bin)
==> .spack-env/view/bin/2to3-3.9 <==
#!/tmp/tmp.BJWYnRULz2/.spack-env/._view/ddni6pauxdzchnjoelkyswoaajl3onan/bin/python3.9

==> .spack-env/view/bin/stubgen <==
#!/tmp/tmp.BJWYnRULz2/.spack-env/._view/ddni6pauxdzchnjoelkyswoaajl3onan/bin/python3.9

==> .spack-env/view/bin/python3.9-config <==
#!/bin/sh

==> .spack-env/view/bin/pip3.9 <==
#!/tmp/tmp.BJWYnRULz2/.spack-env/._view/ddni6pauxdzchnjoelkyswoaajl3onan/bin/python3.9

==> .spack-env/view/bin/mypyc <==
#!/tmp/tmp.BJWYnRULz2/.spack-env/._view/ddni6pauxdzchnjoelkyswoaajl3onan/bin/python3.9

==> .spack-env/view/bin/pydoc3.9 <==
#!/tmp/tmp.BJWYnRULz2/.spack-env/._view/ddni6pauxdzchnjoelkyswoaajl3onan/bin/python3.9

==> .spack-env/view/bin/idle3.9 <==
#!/tmp/tmp.BJWYnRULz2/.spack-env/._view/ddni6pauxdzchnjoelkyswoaajl3onan/bin/python3.9

==> .spack-env/view/bin/pip3 <==
#!/tmp/tmp.BJWYnRULz2/.spack-env/._view/ddni6pauxdzchnjoelkyswoaajl3onan/bin/python3.9

==> .spack-env/view/bin/dmypy <==
#!/tmp/tmp.BJWYnRULz2/.spack-env/._view/ddni6pauxdzchnjoelkyswoaajl3onan/bin/python3.9

==> .spack-env/view/bin/stubtest <==
#!/tmp/tmp.BJWYnRULz2/.spack-env/._view/ddni6pauxdzchnjoelkyswoaajl3onan/bin/python3.9

==> .spack-env/view/bin/python3.9-gdb.py <==
#!/usr/bin/python

==> .spack-env/view/bin/mypy <==
#!/tmp/tmp.BJWYnRULz2/.spack-env/._view/ddni6pauxdzchnjoelkyswoaajl3onan/bin/python3.9
```

it works, the exception is python3.9-gdb.py, but its shebang points to the system python anyways, which is a package issue.

**Comment by lee218llnl** [comment]
I think there is a good chance that I broke things myself. When first creating my spack.yaml, I didn't specify a "root" directory, so spack used ._view by default. I subsequently specified a different "root" directory. It would be nice if spack made the necessary adjustments, but I don't think it is a major issue, so I will close this unless someone thinks that it should be fixed.
