### ISSUE TITLE
Possible redundancy bug deriving spec hash?

### ISSUE THREAD

**Issue by vsoch** [LLNL/spack#30310]
I just saw this:

https://github.com/spack/spack/blob/83b91246b101a30f78f246fb40fa9df54a1e8403/lib/spack/spack/spec.py#L4900-L4903

Should this be indexing something else if build_spec is found as a key? Or just nix the if and always look for that hash? It seems to do the same thing either way.

**Comment by alalazo** [comment]
Will be fixed when #28504 is merged, see https://github.com/spack/spack/pull/28504#discussion_r813855165
