### ISSUE TITLE
[hpcx-mpi] external spec cannot use

### ISSUE THREAD

**Issue by Nyovelt** [LLNL/spack#30319]
### Steps to reproduce

```bash
nano ~/.spack/packages.yaml
```

and I add 

```bash
hpcx-mpi:
    externals:
    - spec: hpcx-mpi@2.7.0
       prefix: {path to hpcx-mpi}
```

However, I cannot find any packages related by `spack find`

### Information on your system

```bash
{username}@nia-login:~/scratch/hpcx$ spack debug report
* **Spack:** 0.18.0.dev0
* **Python:** 3.6.8
* **Platform:** linux-centos7-skylake_avx512
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Did you try using `hpcx-mpi` in a spec? If you do it will be installed as "external". Simple example with `zlib`:
```yaml
packages:
  zlib:
    externals:
    - spec: "zlib@1.2.12"
      prefix: /usr
```
Trying to install that:
```console
$ spack install zlib
[+] /usr (external zlib-1.2.12-qv2mwhke47hfwxcf75ft3mvvqk4muzr4)
```
