### ISSUE TITLE
ncurses@6.2 %cce@13 build fails: llvm/lib/Analysis/ScalarEvolution.cpp:3962: uint64_t llvm::ScalarEvolution::getTypeSizeInBits(llvm::Type*) - Type is not SCEVable!

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#30390]
### Steps to reproduce the issue

`ncurses@6.2 %cce@13.0.1` build fails using:
* `spack/develop` (2515cafb9c60851d5b218d1262212034f5606869 from `Wed Apr 27 16:08:33 2022 -0700`)
* `PrgEnv-cray/8.2.0`
* `cce/13.0.1`
* `SUSE Linux Enterprise Server 15 SP2`

Spack Environment
```
# spack/develop 2515cafb9c60851d5b218d1262212034f5606869
# Wed Apr 27 16:08:33 2022 -0700

spack:
  view: false
  concretization: separately
  config:
    concretizer: clingo
  compilers:
  - compiler:
      spec: cce@13.0.1
      paths:
        cc: cc
        cxx: CC
        f77: ftn
        fc: ftn
      operating_system: sles15
      target: any
      modules:
      - PrgEnv-cray
      - cce/13.0.1
  specs:
  - ncurses@6.2 ~symlinks +termlib abi=none %cce
```

Concretization
```
 -   rxz6czb  ncurses@6.2%cce@13.0.1~symlinks+termlib abi=none arch=cray-sles15-zen3
 -   ph4m7wb      ^pkgconf@1.8.0%cce@13.0.1 arch=cray-sles15-zen3
```

Reproducer
```
eugene@perlmutter:login19:~> git clone https://github.com/spack/spack
eugene@perlmutter:login19:~> (cd spack && git checkout 2515cafb)
eugene@perlmutter:login19:~> export SPACK_DISABLE_LOCAL_CONFIG=1
eugene@perlmutter:login19:~> . spack/share/spack/setup-env.sh
eugene@perlmutter:login19:~> spack -e . install
...
==> Installing ncurses-6.2-rxz6czb7cqbe6p7zye6cqj4jqi2evdl4
==> No binary for ncurses-6.2-rxz6czb7cqbe6p7zye6cqj4jqi2evdl4 found: installing from source
==> Using cached archive: /global/cfs/cdirs/m3503/ParaTools/openblas/spack/var/spack/cache/_source-cache/archive/30/30306e0c76e0f9f1f0de987cf1c82a5c21e1ce6568b9227f7da5b71cbea86c9d.tar.gz
==> No patches needed for ncurses
==> ncurses: Executing phase: 'autoreconf'
==> ncurses: Executing phase: 'configure'
==> ncurses: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j12'

7 errors found in build log:
     929     /global/cfs/cdirs/m3503/ParaTools/openblas/spack/lib/spack/env/cce/cc -DHAVE_CONFIG_H -I../ncurses -I. -I../../ncurses -I../include -I../../ncurses/../include -D_DEFAULT
             _SOURCE -D_XOPEN_SOURCE=600 -DNDEBUG -O2 -Qunused-arguments -DUSE_TERMLIB -c ../../ncurses/tinfo/doalloc.c -o ../objects/doalloc.o
     930     /global/cfs/cdirs/m3503/ParaTools/openblas/spack/lib/spack/env/cce/cc -DHAVE_CONFIG_H -I../ncurses -I. -I../../ncurses -I../include -I../../ncurses/../include -D_DEFAULT
             _SOURCE -D_XOPEN_SOURCE=600 -DNDEBUG -O2 -Qunused-arguments -DUSE_TERMLIB -c ../../ncurses/tinfo/entries.c -o ../objects/entries.o
     931     /global/cfs/cdirs/m3503/ParaTools/openblas/spack/lib/spack/env/cce/cc -DHAVE_CONFIG_H -I../ncurses -I. -I../../ncurses -I../include -I../../ncurses/../include -D_DEFAULT
             _SOURCE -D_XOPEN_SOURCE=600 -DNDEBUG -O2 -Qunused-arguments -DUSE_TERMLIB -c ../ncurses/fallback.c -o ../objects/fallback.o
     932     /global/cfs/cdirs/m3503/ParaTools/openblas/spack/lib/spack/env/cce/cc -DHAVE_CONFIG_H -I../ncurses -I. -I../../ncurses -I../include -I../../ncurses/../include -D_DEFAULT
             _SOURCE -D_XOPEN_SOURCE=600 -DNDEBUG -O2 -Qunused-arguments -DUSE_TERMLIB -c ../../ncurses/tinfo/free_ttype.c -o ../objects/free_ttype.o
     933     /global/cfs/cdirs/m3503/ParaTools/openblas/spack/lib/spack/env/cce/cc -DHAVE_CONFIG_H -I../ncurses -I. -I../../ncurses -I../include -I../../ncurses/../include -D_DEFAULT
             _SOURCE -D_XOPEN_SOURCE=600 -DNDEBUG -O2 -Qunused-arguments -DUSE_TERMLIB -c ../../ncurses/tinfo/getenv_num.c -o ../objects/getenv_num.o
     934     /global/cfs/cdirs/m3503/ParaTools/openblas/spack/lib/spack/env/cce/cc -DHAVE_CONFIG_H -I../ncurses -I. -I../../ncurses -I../include -I../../ncurses/../include -D_DEFAULT
             _SOURCE -D_XOPEN_SOURCE=600 -DNDEBUG -O2 -Qunused-arguments -DUSE_TERMLIB -c ../../ncurses/tinfo/home_terminfo.c -o ../objects/home_terminfo.o
  >> 935     clang: /b/worker/clang-craystable-x86/build/src/llvm/lib/Analysis/ScalarEvolution.cpp:3962: uint64_t llvm::ScalarEvolution::getTypeSizeInBits(llvm::Type*) const: Asserti
             on `isSCEVable(Ty) && "Type is not SCEVable!"' failed.
     936     PLEASE submit a bug report to Cray and include the crash backtrace, preprocessed source, and associated run script.
     937     Stack dump:
     938     0.	Program arguments: clang -march=znver3 -dynamic -D__CRAY_X86_MILAN -D__CRAYXT_COMPUTE_LINUX_TARGET --gcc-toolchain=/opt/cray/pe/gcc/8.1.0/snos -isystem /opt/cray/pe/c
             ce/13.0.1/cce-clang/x86_64/lib/clang/13.0.1/include -isystem /opt/cray/pe/cce/13.0.1/cce/x86_64/include/craylibs -fPIC -I../ncurses -I. -I../../ncurses -I../include -I..
             /../ncurses/../include -DHAVE_CONFIG_H -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -DNDEBUG -O2 /global/cfs/cdirs/m3503/ParaTools/openblas/spack/lib/spack/env/cce/cc -DHAVE_CO
             NFIG_H -I../ncurses -I. -I../../ncurses -I../include -I../../ncurses/../include -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -DNDEBUG -O2 -Qunused-arguments -DUSE_TERMLIB -c ..
             /../ncurses/tinfo/lib_acs.c -o ../objects/lib_acs.o
     939     -Qunused-arguments -fPIC -DUSE_TERMLIB -c ../../ncurses/tinfo/read_termcap.c -o ../obj_s/read_termcap.o -I/opt/cray/pe/dsmml/0.2.2/dsmml/include
     940     1.	<eof> parser at end of file
     941     2.	Code generation
...
```

### Error message

<details><summary>Error message</summary><pre>
==> Installing ncurses-6.2-rxz6czb7cqbe6p7zye6cqj4jqi2evdl4
==> No binary for ncurses-6.2-rxz6czb7cqbe6p7zye6cqj4jqi2evdl4 found: installing from source
==> Using cached archive: /global/cfs/cdirs/m3503/ParaTools/openblas/spack/var/spack/cache/_source-cache/archive/30/30306e0c76e0f9f1f0de987cf1c82a5c21e1ce6568b9227f7da5b71cbea86c9d.tar.gz
==> No patches needed for ncurses
==> ncurses: Executing phase: 'autoreconf'
==> ncurses: Executing phase: 'configure'
==> ncurses: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j12'

7 errors found in build log:
     929     /global/cfs/cdirs/m3503/ParaTools/openblas/spack/lib/spack/env/cce/cc -DHAVE_CONFIG_H -I../ncurses -I. -I../../ncurses -I../include -I../../ncurses/../include -D_DEFAULT
             _SOURCE -D_XOPEN_SOURCE=600 -DNDEBUG -O2 -Qunused-arguments -DUSE_TERMLIB -c ../../ncurses/tinfo/doalloc.c -o ../objects/doalloc.o
     930     /global/cfs/cdirs/m3503/ParaTools/openblas/spack/lib/spack/env/cce/cc -DHAVE_CONFIG_H -I../ncurses -I. -I../../ncurses -I../include -I../../ncurses/../include -D_DEFAULT
             _SOURCE -D_XOPEN_SOURCE=600 -DNDEBUG -O2 -Qunused-arguments -DUSE_TERMLIB -c ../../ncurses/tinfo/entries.c -o ../objects/entries.o
     931     /global/cfs/cdirs/m3503/ParaTools/openblas/spack/lib/spack/env/cce/cc -DHAVE_CONFIG_H -I../ncurses -I. -I../../ncurses -I../include -I../../ncurses/../include -D_DEFAULT
             _SOURCE -D_XOPEN_SOURCE=600 -DNDEBUG -O2 -Qunused-arguments -DUSE_TERMLIB -c ../ncurses/fallback.c -o ../objects/fallback.o
     932     /global/cfs/cdirs/m3503/ParaTools/openblas/spack/lib/spack/env/cce/cc -DHAVE_CONFIG_H -I../ncurses -I. -I../../ncurses -I../include -I../../ncurses/../include -D_DEFAULT
             _SOURCE -D_XOPEN_SOURCE=600 -DNDEBUG -O2 -Qunused-arguments -DUSE_TERMLIB -c ../../ncurses/tinfo/free_ttype.c -o ../objects/free_ttype.o
     933     /global/cfs/cdirs/m3503/ParaTools/openblas/spack/lib/spack/env/cce/cc -DHAVE_CONFIG_H -I../ncurses -I. -I../../ncurses -I../include -I../../ncurses/../include -D_DEFAULT
             _SOURCE -D_XOPEN_SOURCE=600 -DNDEBUG -O2 -Qunused-arguments -DUSE_TERMLIB -c ../../ncurses/tinfo/getenv_num.c -o ../objects/getenv_num.o
     934     /global/cfs/cdirs/m3503/ParaTools/openblas/spack/lib/spack/env/cce/cc -DHAVE_CONFIG_H -I../ncurses -I. -I../../ncurses -I../include -I../../ncurses/../include -D_DEFAULT
             _SOURCE -D_XOPEN_SOURCE=600 -DNDEBUG -O2 -Qunused-arguments -DUSE_TERMLIB -c ../../ncurses/tinfo/home_terminfo.c -o ../objects/home_terminfo.o
  >> 935     clang: /b/worker/clang-craystable-x86/build/src/llvm/lib/Analysis/ScalarEvolution.cpp:3962: uint64_t llvm::ScalarEvolution::getTypeSizeInBits(llvm::Type*) const: Asserti
             on `isSCEVable(Ty) && "Type is not SCEVable!"' failed.
     936     PLEASE submit a bug report to Cray and include the crash backtrace, preprocessed source, and associated run script.
     937     Stack dump:
     938     0.	Program arguments: clang -march=znver3 -dynamic -D__CRAY_X86_MILAN -D__CRAYXT_COMPUTE_LINUX_TARGET --gcc-toolchain=/opt/cray/pe/gcc/8.1.0/snos -isystem /opt/cray/pe/c
             ce/13.0.1/cce-clang/x86_64/lib/clang/13.0.1/include -isystem /opt/cray/pe/cce/13.0.1/cce/x86_64/include/craylibs -fPIC -I../ncurses -I. -I../../ncurses -I../include -I..
             /../ncurses/../include -DHAVE_CONFIG_H -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -DNDEBUG -O2 /global/cfs/cdirs/m3503/ParaTools/openblas/spack/lib/spack/env/cce/cc -DHAVE_CO
             NFIG_H -I../ncurses -I. -I../../ncurses -I../include -I../../ncurses/../include -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -DNDEBUG -O2 -Qunused-arguments -DUSE_TERMLIB -c ..
             /../ncurses/tinfo/lib_acs.c -o ../objects/lib_acs.o
     939     -Qunused-arguments -fPIC -DUSE_TERMLIB -c ../../ncurses/tinfo/read_termcap.c -o ../obj_s/read_termcap.o -I/opt/cray/pe/dsmml/0.2.2/dsmml/include
     940     1.	<eof> parser at end of file
     941     2.	Code generation

     ...

     1161    #193 0x0000000003b444a2 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/opt/cray/pe/cce/13.0.1/cce-clan
             g/x86_64/bin/clang-13+0x3b444a2)
     1162    #194 0x0000000003b45636 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) co
             nst (/opt/cray/pe/cce/13.0.1/cce-clang/x86_64/bin/clang-13+0x3b45636)
     1163    #195 0x0000000003b516e9 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/
             opt/cray/pe/cce/13.0.1/cce-clang/x86_64/bin/clang-13+0x3b516e9)
     1164    #196 0x0000000000cdb6d5 main (/opt/cray/pe/cce/13.0.1/cce-clang/x86_64/bin/clang-13+0xcdb6d5)
     1165    #197 0x00007ff7ac0b83e9 __libc_start_main (/lib64/libc.so.6+0x243e9)
     1166    #198 0x0000000000da4689 _start /home/abuild/rpmbuild/BUILD/glibc-2.19/csu/../sysdeps/x86_64/start.S:122:0
  >> 1167    clang-13: error: clang frontend command failed with exit code 134 (use -v to see invocation)
     1168    Cray clang version 13.0.1  (a54f2d2f4987810fa2a729cd15e149dbc8eec9d4)
     1169    Target: x86_64-unknown-linux-gnu
     1170    Thread model: posix
     1171    InstalledDir: /opt/cray/pe/cce/13.0.1/cce-clang/x86_64/share/../bin
     1172    /global/cfs/cdirs/m3503/ParaTools/openblas/spack/lib/spack/env/cce/cc -DHAVE_CONFIG_H -I../ncurses -I. -I../../ncurses -I../include -I../../ncurses/../include -D_DEFAULT
             _SOURCE -D_XOPEN_SOURCE=600 -DNDEBUG -O2 -Qunused-arguments -DUSE_TERMLIB -c ../../ncurses/tinfo/read_termcap.c -o ../objects/read_termcap.o
     1173    clang-13: note: diagnostic msg:

     ...

     1177    Preprocessed source(s) and associated run script(s) are located at:
     1178    clang-13: note: diagnostic msg: /tmp/read_termcap-b25895.c
     1179    clang-13: note: diagnostic msg: /tmp/read_termcap-b25895.sh
     1180    clang-13: note: diagnostic msg:
     1181
     1182    ********************
  >> 1183    make[1]: *** [Makefile:1053: ../obj_s/read_termcap.o] Error 134
     1184    make[1]: *** Waiting for unfinished jobs....
  >> 1185    clang: /b/worker/clang-craystable-x86/build/src/llvm/lib/Analysis/ScalarEvolution.cpp:3962: uint64_t llvm::ScalarEvolution::getTypeSizeInBits(llvm::Type*) const: Asserti
             on `isSCEVable(Ty) && "Type is not SCEVable!"' failed.
     1186    PLEASE submit a bug report to Cray and include the crash backtrace, preprocessed source, and associated run script.
     1187    Stack dump:
     1188    0.	Program arguments: clang -march=znver3 -dynamic -D__CRAY_X86_MILAN -D__CRAYXT_COMPUTE_LINUX_TARGET --gcc-toolchain=/opt/cray/pe/gcc/8.1.0/snos -isystem /opt/cray/pe/c
             ce/13.0.1/cce-clang/x86_64/lib/clang/13.0.1/include -isystem /opt/cray/pe/cce/13.0.1/cce/x86_64/include/craylibs -fPIC -I../ncurses -I. -I../../ncurses -I../include -I..
             /../ncurses/../include -DHAVE_CONFIG_H -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -DNDEBUG -O2 -Qunused-arguments -DUSE_TERMLIB -c ../../ncurses/tinfo/read_termcap.c -o ../ob
             jects/read_termcap.o -I/opt/cray/pe/dsmml/0.2.2/dsmml/include
     1189    1.	<eof> parser at end of file
     1190    2.	Code generation
     1191    3.	Running pass 'Function Pass Manager' on module '../../ncurses/tinfo/read_termcap.c'.

     ...

     1387    #193 0x0000000003b444a2 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/opt/cray/pe/cce/13.0.1/cce-clan
             g/x86_64/bin/clang-13+0x3b444a2)
     1388    #194 0x0000000003b45636 clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) co
             nst (/opt/cray/pe/cce/13.0.1/cce-clang/x86_64/bin/clang-13+0x3b45636)
     1389    #195 0x0000000003b516e9 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/
             opt/cray/pe/cce/13.0.1/cce-clang/x86_64/bin/clang-13+0x3b516e9)
     1390    #196 0x0000000000cdb6d5 main (/opt/cray/pe/cce/13.0.1/cce-clang/x86_64/bin/clang-13+0xcdb6d5)
     1391    #197 0x00007f17b99d33e9 __libc_start_main (/lib64/libc.so.6+0x243e9)
     1392    #198 0x0000000000da4689 _start /home/abuild/rpmbuild/BUILD/glibc-2.19/csu/../sysdeps/x86_64/start.S:122:0
  >> 1393    clang-13: error: clang frontend command failed with exit code 134 (use -v to see invocation)
     1394    Cray clang version 13.0.1  (a54f2d2f4987810fa2a729cd15e149dbc8eec9d4)
     1395    Target: x86_64-unknown-linux-gnu
     1396    Thread model: posix
     1397    InstalledDir: /opt/cray/pe/cce/13.0.1/cce-clang/x86_64/share/../bin
     1398    clang-13: note: diagnostic msg:
     1399    ********************

     ...

     1402    Preprocessed source(s) and associated run script(s) are located at:
     1403    clang-13: note: diagnostic msg: /tmp/read_termcap-9dae6d.c
     1404    clang-13: note: diagnostic msg: /tmp/read_termcap-9dae6d.sh
     1405    clang-13: note: diagnostic msg:
     1406
     1407    ********************
  >> 1408    make[1]: *** [Makefile:1460: ../objects/read_termcap.o] Error 134
     1409    make[1]: Leaving directory '/tmp/eugene/spack-stage/spack-stage-ncurses-6.2-rxz6czb7cqbe6p7zye6cqj4jqi2evdl4/spack-src/build_ncurses/ncurses'
  >> 1410    make: *** [Makefile:119: all] Error 2
</pre></details>

### Information on your system

* **Spack:** 0.18.0.dev0 (2515cafb9c60851d5b218d1262212034f5606869)
* **Python:** 3.6.15
* **Platform:** cray-sles15-zen3
* **Concretizer:** clingo

### Additional information

[spack-build-out.txt](https://github.com/spack/spack/files/8587195/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/8587196/spack-build-env.txt)

@shahzebsiddiqui @sleak-lbl @lukebroskop @wspear 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
Can you report this upstream instead of in spack?

**Comment by lukebroskop** [comment]
Thanks @eugeneswalker! We are aware of this issue. It should be fixed in an upcoming release (CCE14 ~May timeframe).

**Comment by lukebroskop** [comment]
In the meantime, if you want to use CCE13 and work around this problem, you'll need to build ncurses with the `craype-x86-rome` module loaded. However, with spack I was unable to swap the arch targeting modules on crusher, so I forced additional changes to the environment too.
```
  - compiler:
      spec: cce@13.0.1-rome
      paths:
        cc: cc
        cxx: CC
        f77: ftn
        fc: ftn
      flags: {}
      operating_system: sles15
      target: any
      modules:
      - PrgEnv-cray
      - cce/13.0.1
      - craype-x86-rome
      environment:
        set:
          CRAY_CPU_TARGET: x86-rome
          CRAY_LMOD_CPU: x86-rome
        prepend_path:
          PE_PRODUCT_LIST: CRAYPE_X86_ROME
          MODULEPATH: /opt/cray/pe/lmod/modulefiles/cpu/x86-rome/1.0
      extra_rpaths: []
```

**Comment by eugeneswalker** [comment]
> Can you report this upstream instead of in spack?

Yes, sorry. Sounds like Cray is aware of issue. Closing issue here.

**Comment by eugeneswalker** [comment]
> In the meantime, if you want to use CCE13 and work around this problem, you'll need to build ncurses with the `craype-x86-rome` module loaded. However, with spack I was unable to swap the arch targeting modules on crusher, so I forced additional changes to the environment too.

Thank you!
