### ISSUE TITLE
Installation issue: mesa

### ISSUE THREAD

**Issue by gphilip** [LLNL/spack#30453]
### Steps to reproduce the issue

```console
$ spack spec -I mesa
Input spec
--------------------------------
 -   mesa

Concretized
--------------------------------
 -   mesa@22.0.2%gcc@9.4.0+glx+llvm+opengl~opengles+osmesa~strip buildtype=release default_library=shared patches=ada85be arch=linux-linuxmint20-skylake
[+]      ^bison@3.8.2%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]          ^diffutils@3.8%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]              ^libiconv@1.16%gcc@9.4.0 libs=shared,static arch=linux-linuxmint20-skylake
[+]          ^m4@1.4.19%gcc@9.4.0+sigsegv patches=9dc5fbd,bfdffa7 arch=linux-linuxmint20-skylake
[+]              ^libsigsegv@2.13%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]          ^perl@5.34.1%gcc@9.4.0+cpanm+shared+threads arch=linux-linuxmint20-skylake
[+]              ^berkeley-db@18.1.40%gcc@9.4.0+cxx~docs+stl patches=b231fcc arch=linux-linuxmint20-skylake
[+]              ^bzip2@1.0.8%gcc@9.4.0~debug~pic+shared arch=linux-linuxmint20-skylake
[+]              ^gdbm@1.19%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]                  ^readline@8.1%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]                      ^ncurses@6.2%gcc@9.4.0~symlinks+termlib abi=none arch=linux-linuxmint20-skylake
[+]                          ^pkgconf@1.8.0%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]              ^zlib@1.2.12%gcc@9.4.0+optimize+pic+shared patches=0d38234 arch=linux-linuxmint20-skylake
[+]      ^cmake@3.23.1%gcc@9.4.0~doc+ncurses+ownlibs~qt build_type=Release arch=linux-linuxmint20-skylake
[+]          ^openssl@1.1.1n%gcc@9.4.0~docs~shared certs=system arch=linux-linuxmint20-skylake
[+]      ^expat@2.4.8%gcc@9.4.0+libbsd arch=linux-linuxmint20-skylake
[+]          ^libbsd@0.11.5%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]              ^libmd@1.0.4%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]      ^flex@2.6.3%gcc@9.4.0+lex~nls arch=linux-linuxmint20-skylake
[+]          ^findutils@4.9.0%gcc@9.4.0 patches=440b954 arch=linux-linuxmint20-skylake
[+]      ^gettext@0.21%gcc@9.4.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-linuxmint20-skylake
[+]          ^libxml2@2.9.13%gcc@9.4.0~python arch=linux-linuxmint20-skylake
[+]              ^xz@5.2.5%gcc@9.4.0~pic libs=shared,static arch=linux-linuxmint20-skylake
[+]          ^tar@1.34%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]      ^glproto@1.4.17%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]          ^util-macros@1.19.3%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]      ^libunwind@1.6.2%gcc@9.4.0~block_signals~conservative_checks~cxx_exceptions~debug~debug_frame+docs~pic+tests+weak_backtrace~xz~zlib components=none libs=shared,static arch=linux-linuxmint20-skylake
[+]      ^libx11@1.7.0%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]          ^inputproto@2.3.2%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]          ^kbproto@1.0.7%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]          ^libxcb@1.14%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]              ^libpthread-stubs@0.4%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]              ^libxau@1.0.8%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]                  ^xproto@7.0.31%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]              ^libxdmcp@1.1.2%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]              ^xcb-proto@1.14.1%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]          ^xextproto@7.3.0%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]          ^xtrans@1.3.5%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]      ^libxext@1.3.3%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]      ^libxt@1.1.5%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]          ^libice@1.0.9%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]          ^libsm@1.2.3%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]              ^util-linux-uuid@2.37.4%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]      ^llvm@12.0.1%gcc@9.4.0+clang~code_signing+compiler-rt~cuda~flang+gold+internal_unwind~ipo+libcxx~link_llvm_dylib+lld+lldb~llvm_dylib~mlir+omp_as_runtime~omp_debug~omp_tsan+polly~python~shared_libs~split_dwarf~z3 build_type=Release targets=none version_suffix=none arch=linux-linuxmint20-skylake
[+]          ^binutils@2.38%gcc@9.4.0~gas+gold~headers~interwork+ld~libiberty~lto+nls+plugins libs=shared,static arch=linux-linuxmint20-skylake
[+]          ^hwloc@2.7.1%gcc@9.4.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~opencl+pci~rocm+shared arch=linux-linuxmint20-skylake
[+]              ^libpciaccess@0.16%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]                  ^libtool@2.4.7%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]          ^libedit@3.1-20210216%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]          ^ninja@1.10.2%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]              ^python@3.9.12%gcc@9.4.0+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93,4c24573,f2fd060 arch=linux-linuxmint20-skylake
[+]                  ^libffi@3.4.2%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]                  ^sqlite@3.38.3%gcc@9.4.0+column_metadata+dynamic_extensions+fts~functions+rtree arch=linux-linuxmint20-skylake
[+]          ^perl-data-dumper@2.173%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]          ^swig@4.0.2%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]              ^pcre@8.45%gcc@9.4.0~jit+multibyte+utf arch=linux-linuxmint20-skylake
[+]      ^meson@0.62.1%gcc@9.4.0 patches=aa6c50d arch=linux-linuxmint20-skylake
[+]          ^py-pip@21.3.1%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]          ^py-setuptools@59.4.0%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]              ^py-wheel@0.37.0%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]      ^py-mako@1.1.6%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]          ^py-markupsafe@2.0.1%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]      ^xrandr@1.5.0%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]          ^libxrandr@1.5.0%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]              ^libxrender@0.9.10%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]                  ^renderproto@0.11.1%gcc@9.4.0 arch=linux-linuxmint20-skylake
[+]              ^randrproto@1.5.0%gcc@9.4.0 arch=linux-linuxmint20-skylake

$ spack install mesa
```

### Error message

<details><summary>Error message</summary><pre>
==> Error: ProcessError: Command exited with status 1:
    'meson' '/tmp/gphilip/spack-stage/spack-stage-mesa-22.0.2-icpxaou2womg2a54n33g67tekavhzi7s/spack-src' '--prefix=/Storage/builds/spack/opt/spack/linux-linuxmint20-skylake/gcc-9.4.0/mesa-22.0.2-icpxaou2womg2a54n33g67tekavhzi7s' '--libdir=/Storage/builds/spack/opt/spack/linux-linuxmint20-skylake/gcc-9.4.0/mesa-22.0.2-icpxaou2womg2a54n33g67tekavhzi7s/lib' '-Dbuildtype=release' '-Dstrip=false' '-Ddefault_library=shared' '-Dvulkan-drivers=' '-Dgallium-vdpau=disabled' '-Dgallium-xvmc=disabled' '-Dgallium-omx=disabled' '-Dgallium-va=disabled' '-Dgallium-xa=disabled' '-Dgallium-nine=false' '-Dgallium-opencl=disabled' '-Dbuild-tests=false' '-Dglvnd=false' '-Dosmesa=true' '-Dglx=gallium-xlib' '-Degl=disabled' '-Dgbm=disabled' '-Ddri3=disabled' '-Dopengl=true' '-Dgles1=disabled' '-Dgles2=disabled' '-Dshared-glapi=enabled' '--native-file' 'meson-native-config.ini' '-Dllvm=enabled' '-Dshared-llvm=disabled' '-Dplatforms=x11' '-Dgallium-drivers=swrast' '-Ddri-drivers='

1 error found in build log:
     4     Version: 0.62.1
     5     Source dir: /tmp/gphilip/spack-stage/spack-stage-mesa-22.0.2-icpxaou2womg2a54n33g67tekavhzi7s/spack-src
     6     Build dir: /tmp/gphilip/spack-stage/spack-stage-mesa-22.0.2-icpxaou2womg2a54n33g67tekavhzi7s/spack-src/spack-build
     7     Build type: native build
     8     Program python3 found: YES (/Storage/builds/spack/opt/spack/linux-linuxmint20-skylake/gcc-9.4.0/python-3.9.12-arrf3pywdins
           2jmqe3vc7fqrp2ii6i6g/bin/python3)
     9     
  >> 10    ../meson.build:21:0: ERROR: Value "gallium-xlib" (of type "string") for combo option "Build support for GLX platform" is n
           ot one of the choices. Possible choices are (as string): "auto", "disabled", "dri", "xlib".
     11    
     12    A full log can be found at /tmp/gphilip/spack-stage/spack-stage-mesa-22.0.2-icpxaou2womg2a54n33g67tekavhzi7s/spack-src/spa
           ck-build/meson-logs/meson-log.txt

</pre></details>

### Information on your system

* **Spack:** 0.18.0.dev0 (84611b5f29ec6013bbcc4f89222852a637e299c8)
* **Python:** 3.8.10
* **Platform:** linux-linuxmint20-skylake
* **Concretizer:** clingo

### Additional information

[spack-build-out.txt](https://github.com/spack/spack/files/8610588/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/8610591/spack-build-env.txt)
[spack-build-01-meson-out.txt](https://github.com/spack/spack/files/8610594/spack-build-01-meson-out.txt)
[spack-build-env-mods.txt](https://github.com/spack/spack/files/8610595/spack-build-env-mods.txt)

For the kind attention of the mesa package maintainers: @chuckatkins and  @v-dobrev

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by wdconinc** [comment]
Same here. Following diff resolves build issue (ref https://gitlab.freedesktop.org/mesa/mesa/-/commit/76791db0882b3715cd7d0a47fd14e1f784901b09), but ymmv on operation:
```diff
diff --git a/var/spack/repos/builtin/packages/mesa/package.py b/var/spack/repos/builtin/packages/mesa/package.py
index 0f3165ec4e..e947588c26 100644
--- a/var/spack/repos/builtin/packages/mesa/package.py
+++ b/var/spack/repos/builtin/packages/mesa/package.py
@@ -175,7 +175,7 @@ def meson_args(self):
             if '+egl' in spec:
                 args.append('-Dglx=dri')
             else:
-                args.append('-Dglx=gallium-xlib')
+                args.append('-Dglx=xlib')
             args_platforms.append('x11')
         else:
             args.append('-Dglx=disabled')
```

**Comment by wdconinc** [comment]
I am refraining from submitting a PR since it is not clear to me whehter a change from gallium-xlib to xlib for older versions is the right way to resolve this, or if this needs to be conditioned on version @22:.

**Comment by eugeneswalker** [comment]
> I am refraining from submitting a PR since it is not clear to me whehter a change from gallium-xlib to xlib for older versions is the right way to resolve this, or if this needs to be conditioned on version @22:.

I think this is brand new, with `@22:`, but am testing without this patch -- everything else the same -- but with `@21.3.8` to verify. Will update here when finished.

**Comment by eugeneswalker** [comment]
> I think this is brand new, with `@22:`, but am testing without this patch -- everything else the same -- but with `@21.3.8` to verify. Will update here when finished.

`mesa@21.3.8` builds fine for me. We should condition this on `@22:` and submit PR? What do you think?

**Comment by gphilip** [comment]
Thank you @wdconinc , this change makes the build go through. I am marking this issue as closed. 

@eugeneswalker : Thank you for looking into this.

**Comment by wdconinc** [comment]
Don't close it until a PR has been merged.
