### ISSUE TITLE
Missing deps(?): spack install tr gives fatal error: X11/Xlib.h: No such file or directory 

### ISSUE THREAD

**Issue by HenrikBengtsson** [LLNL/spack#3047]
# Problem
`tr` comes with variant `X` and it's off by default:
```sh
Variants:
    Name Default   Description

    X    off       Enable X11 support
```
I get a build error when running (*):
```sh
$ spack install tk
[...]
$ more /tmp/hb/spack-stage/spack-stage-zTToCX/tk8.6.6/spack-build.out
[...]
$ 
/tmp/hb/spack-stage/spack-stage-zTToCX/tk8.6.6/unix/../generic/tk.h:96:25: fatal error: X11/Xlib.h: No such file or directory
 #   include <X11/Xlib.h>
```
suggesting that Tk still needs to `#include <X11/Xlib.h>` when being built (full details below).

BTW, I noticed this error when trying to install R as `spack install r`, which in turn depends on `tk` meaning the above error was a showstopper.  With my below workaround Tk and R installs.

# Troubleshooting
However,  [`repos/builtin/packages/tk/package.py`](https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/tk/package.py#L44) only includes `libx11` only when variant `X` is enabled (i.e. using `+X`):
```sh
    depends_on("tcl")
    depends_on("libx11", when='+X')
```

# Workaround
When removing `when='+X'` above (i.e. using `depends_on("libx11")`), then `spack install tk` installs Tk successfully.

Because of the error message, is the above a bug in `repos/builtin/packages/tk/package.py`?  I'm happy do a PR, but I'm not sure if this is the proper fix?

# Details
```sh
==> Installing tk
==> tcl is already installed in /netapp/home/hb/apps/spack/opt/spack/linux-centos7-x86_64/gcc-4.8.5/tcl-8.6.6-knxyrpxcnki3akcjh2ppgfoufyl7r546
==> Fetching http://prdownloads.sourceforge.net/tcl/tk8.6.6-src.tar.gz
######################################################################## 100.0%
==> Staging archive: /netapp/home/hb/apps/spack/var/spack/stage/tk-8.6.6-oncwbwpqlkoloztntzehow7rad5pjfts/tk8.6.6-src.tar.gz
==> Created stage in /netapp/home/hb/apps/spack/var/spack/stage/tk-8.6.6-oncwbwpqlkoloztntzehow7rad5pjfts
==> Ran patch() for tk
==> Building tk [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Executing phase : 'configure'
==> Executing phase : 'build'
==> Error: ProcessError: Command exited with status 2:
    'make'
/netapp/home/hb/apps/spack/lib/spack/spack/build_systems/autotools.py:275, in build:
     270      def build(self, spec, prefix):
     271          """Makes the build targets specified by
     272          :py:attr:``~.AutotoolsPackage.build_targets``
     273          """
     274          with working_dir(self.build_directory):
  >> 275              inspect.getmodule(self).make(*self.build_targets)

See build log for details:
/tmp/hb/spack-stage/spack-stage-zTToCX/tk8.6.6/spack-build.out
```

```sh
$ more /tmp/hb/spack-stage/spack-stage-zTToCX/tk8.6.6/spack-build.out
[...]
/spack-stage/spack-stage-zTToCX/tk8.6.6/unix/../generic/ttk/ttkStubLib.c
In file included from /tmp/hb/spack-stage/spack-stage-zTToCX/tk8.6.6/unix/../generic/tkPort.h:21:0,
                 from /tmp/hb/spack-stage/spack-stage-zTToCX/tk8.6.6/unix/../generic/tkInt.h:19,
                 from /tmp/hb/spack-stage/spack-stage-zTToCX/tk8.6.6/unix/../generic/tkStubLib.c:14:
/tmp/hb/spack-stage/spack-stage-zTToCX/tk8.6.6/unix/../generic/tk.h:96:25: fatal error: X11/Xlib.h: No such file or directory
 #   include <X11/Xlib.h>
                         ^
compilation terminated.
In file included from /tmp/hb/spack-stage/spack-stage-zTToCX/tk8.6.6/unix/../generic/ttk/ttkStubLib.c:9:0:
/tmp/hb/spack-stage/spack-stage-zTToCX/tk8.6.6/unix/../generic/tk.h:96:25: fatal error: X11/Xlib.h: No such file or directory
 #   include <X11/Xlib.h>
                         ^
compilation terminated.
make: *** [tkStubLib.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [ttkStubLib.o] Error 1
```

# Session info
The above is on a fresh Centos 7:
```sh
rpm --query centos-release
centos-release-7-3.1611.el7.centos.x86_64
```
with today's version of Spack 0.10.0 (from `git clone https://github.com/llnl/spack.git`).

**Comment by adamjstewart** [comment]
I ran into this same problem with the R package in #2864. The problem is that by default, these packages assume you have X11 libraries available and try to build GUI support. With R, you can add the `--without-x` flag to explicitly disable this, which is what I added in #2864. There may be something equivalent for tk, although @hartzell probably has another suggestion. From what he said, it sounds like `tk~X` doesn't make much sense, as `tk` is an X window toolkit for `tcl`. Perhaps a better solution would be to have R only depend on tk `when='+X'`?

You probably know more than I do. Should users generally expect R to be built with tk/tcl support? I disabled X11 support in all of our packages until variant resolution is no longer broken, so they all default to not having tk/tcl support.

**Comment by citibeth** [comment]
>  From what he said, it sounds like tk~X doesn't make much sense, as tk is an X window toolkit for tcl. Perhaps a better solution would be to have R only depend on tk when='+X'?

That sounds right to me.

To cover bases... is the issue reported here on a Mac?

**Comment by HenrikBengtsson** [comment]
> You probably know more than I do. Should users generally expect R to be built with tk/tcl support? I disabled X11 support in all of our packages until variant resolution is no longer broken, so they all default to not having tk/tcl support.

tcltk is one of the core packages.  It will always be installed, but if tcltk is not supported;
```r
> capabilities()
       jpeg         png        tiff       tcltk         X11        aqua 
       TRUE        TRUE        TRUE       FALSE        TRUE       FALSE 
   http/ftp     sockets      libxml        fifo      cledit       iconv 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE 
        NLS     profmem       cairo         ICU long.double     libcurl 
       TRUE        TRUE        TRUE        TRUE        TRUE        TRUE
```
there will be an (intentional) error when the `tcltk` package is loaded (directly or indirectly via another R packages), e.g.
```r
> library("tcltk")
Error : .onLoad failed in loadNamespace() for 'tcltk', details:
  call: fun(libname, pkgname)
  error: Tcl/Tk support is not available on this system
In addition: Warning message:
S3 methods 'as.character.tclObj', 'as.character.tclVar', 'as.double.tclObj', 'as.integer.tclObj', 'as.logical.tclObj', 'as.raw.tclObj', 'print.tclObj', '[[.tclArray', '[[<-.tclArray', '$.tclArray', '$<-.tclArray', 'names.tclArray', 'names<-.tclArray', 'length.tclArray', 'length<-.tclArray', 'tclObj.tclVar', 'tclObj<-.tclVar', 'tclvalue.default', 'tclvalue.tclObj', 'tclvalue.tclVar', 'tclvalue<-.default', 'tclvalue<-.tclVar', 'close.tkProgressBar' were declared in NAMESPACE but not found 
Error: package or namespace load failed for 'tcltk'
```

The tcltk package can / is used also for non-GUI usages, e.g. it provides a mechanism for running async basic event handling in R although R itself is single-threaded.  I don't know whether tcltk uses pure Tcl for that or Tk.  Regardless, from the name "tcltk" I think we can assume that tcltk requires both Tcl+Tk and that Tk is non-optional.

So, tcltk requires Tk and if it's true that Tk requires X11, and R is designed to also be built without X11, then I think we can safely update to use `depends_on("tk", when = "+X")` for the R package.

**Comment by hartzell** [comment]
If you unpack Spack's  `r` package, `cd` into the staging directory and run `configure --help`, the output includes the following lines:

```
  --with-tcltk            use Tcl/Tk (if available), or specify its library
                          dir [yes]
  --with-tcl-config=TCL_CONFIG
                          specify location of tclConfig.sh []
  --with-tk-config=TK_CONFIG
                          specify location of tkConfig.sh []
```

The `tk8.6.6//README` describes Tk thusly:

> This directory contains the sources and documentation for Tk, an X11
toolkit implemented with the Tcl scripting language.

There are docs and knobs to turn that will allow one to build Tk w/ Aqua instead of X11 (on the mac).

`tk8.6.6/unix/configure --help` generates this:

```
hartzelg-UXG8WL:unix hartzelg$ ./configure --help
`configure' configures tk 8.6 to adapt to many kinds of systems.

Usage: ./configure [OPTION]... [VAR=VALUE]...

To assign environment variables (e.g., CC, CFLAGS...), specify them as
VAR=VALUE.  See below for descriptions of some of the useful variables.

Defaults for the options are specified in brackets.

Configuration:
  -h, --help              display this help and exit
      --help=short        display options specific to this package
      --help=recursive    display the short help of all the included packages
  -V, --version           display version information and exit
  -q, --quiet, --silent   do not print `checking...' messages
      --cache-file=FILE   cache test results in FILE [disabled]
  -C, --config-cache      alias for `--cache-file=config.cache'
  -n, --no-create         do not create output files
      --srcdir=DIR        find the sources in DIR [configure dir or `..']

Installation directories:
  --prefix=PREFIX         install architecture-independent files in PREFIX
			  [/usr/local]
  --exec-prefix=EPREFIX   install architecture-dependent files in EPREFIX
			  [PREFIX]

By default, `make install' will install all the files in
`/usr/local/bin', `/usr/local/lib' etc.  You can specify
an installation prefix other than `/usr/local' using `--prefix',
for instance `--prefix=$HOME'.

For better control, use the options below.

Fine tuning of the installation directories:
  --bindir=DIR           user executables [EPREFIX/bin]
  --sbindir=DIR          system admin executables [EPREFIX/sbin]
  --libexecdir=DIR       program executables [EPREFIX/libexec]
  --datadir=DIR          read-only architecture-independent data [PREFIX/share]
  --sysconfdir=DIR       read-only single-machine data [PREFIX/etc]
  --sharedstatedir=DIR   modifiable architecture-independent data [PREFIX/com]
  --localstatedir=DIR    modifiable single-machine data [PREFIX/var]
  --libdir=DIR           object code libraries [EPREFIX/lib]
  --includedir=DIR       C header files [PREFIX/include]
  --oldincludedir=DIR    C header files for non-gcc [/usr/include]
  --infodir=DIR          info documentation [PREFIX/info]
  --mandir=DIR           man documentation [PREFIX/man]

X features:
  --x-includes=DIR    X include files are in DIR
  --x-libraries=DIR   X library files are in DIR

Optional Features:
  --disable-FEATURE       do not include FEATURE (same as --enable-FEATURE=no)
  --enable-FEATURE[=ARG]  include FEATURE [ARG=yes]
  --enable-man-symlinks   use symlinks for the manpages (default: off)
  --enable-man-compression=PROG
                          compress the manpages with PROG (default: off)
  --enable-man-suffix=STRING
                          use STRING as a suffix to manpage file names
                          (default: no, tk if enabled without
                          specifying STRING)
  --enable-threads        build with threads (default: on)
  --enable-shared         build and link with shared libraries (default: on)
  --enable-64bit          enable 64bit support (default: off)
  --enable-64bit-vis      enable 64bit Sparc VIS support (default: off)
  --disable-rpath         disable rpath support (default: on)
  --enable-corefoundation use CoreFoundation API on MacOSX (default: on)
  --enable-load           allow dynamic loading and "load" command (default:
                          on)
  --enable-symbols        build with debugging symbols (default: off)
  --enable-aqua=yes|no    use Aqua windowingsystem on Mac OS X (default: no)
  --enable-xft            use freetype/fontconfig/xft (default: on)
  --enable-xss            use XScreenSaver for activity timer (default: on)
  --enable-framework      package shared libraries in MacOSX frameworks
                          (default: off)

Optional Packages:
  --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
  --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
  --with-tcl              directory containing tcl configuration
                          (tclConfig.sh)
  --with-x                use the X Window System

Some influential environment variables:
  CC          C compiler command
  CFLAGS      C compiler flags
  LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
              nonstandard directory <lib dir>
  CPPFLAGS    C/C++ preprocessor flags, e.g. -I<include dir> if you have
              headers in a nonstandard directory <include dir>
  CPP         C preprocessor

Use these variables to override the choices made by `configure' or to help
it to find libraries and programs with nonstandard names/locations.
```

There *is* a `--with-x` flag.  Out of curiousity, I ran `./configure --without-x`  and the output included:

```
[...]
checking for X... disabled
checking for X11 header files... couldn't find any!
checking for X11 libraries... checking for XCreateWindow in -lXwindow... no
could not find any!  Using -lX11.
checking for main in -lXbsd... no
checking whether to use xft... no
checking for X11/XKBlib.h... no
checking whether XKeycodeToKeysym is deprecated... yes
checking whether to try to use XScreenSaver... yes
checking for X11/extensions/scrnsaver.h... no
checking for XScreenSaverQueryInfo... no
checking for XScreenSaverQueryInfo in -lXext... no
checking for XScreenSaverQueryInfo in -lXss... no
checking whether char is unsigned... no[...]
```

Even when I do that (and do some gross things to point it at a tcl install), running `make` sez:

```
fatal error: X11/Xlib.h: No such file or directory
 #   include <X11/Xlib.h>
                         ^
compilation terminated.
make: *** [tkStubLib.o] Error 1
```

Perhaps there *is* a way to have Tk w/out X on "unix", but I don't see it.

**Comment by citibeth** [comment]
> Perhaps there *is* a way to have Tk w/out X on "unix", but I don't see it.

If someone can research how R is normally built for Windows, maybe the
answer lies there.

**Comment by hartzell** [comment]
Following up on @adamjstewart's earlier comment:

>  From what he [hartzell] said, it sounds like tk~X doesn't make much sense, as tk is an X window toolkit for tcl

Specifically, to the best of my understanding it "doesn't make much sense" **on unix-y things**.  On macos, it seems to be reasonable.  On macs it should enable aqua support (or perhaps both?).  Disabling both is probably just asking for trouble.

**Comment by hartzell** [comment]
> If someone can research how R is normally built for Windows, maybe the
> answer lies there.

I hate to say it, but I don't have a strong enough interest, particularly given my lack of Windows-fu.

If there's someone who needs R and does not want X then they'd be a good candidate to grind away at it.  I think that the simple first step would be to make R build without Tk when it builds without X.  @HenrikBengtsson's comments above makes that sound as if that's a situation that R has accounted for.

If there's someone who needs R *and* Tk but not X on linux-y, then they'd be a great candidate to grind even harder.

**Comment by citibeth** [comment]
I didn't mean to DO it; just spend a few minutes RESEARCHING how others
have done it (and I know they have; I've used R on Windows, without X11).
I expect such research would turn up either:

1. There's a Tk for Windows.  At which point we'd have "conclusive"
evidence that it's really not an X-Windows specific toolkit, at least not
anymore.

2. R for Windows uses something other than Tk; because Tk is really
Unix-only or X11-only.

Understanding that bit of info would help guide the current discussion.
