### ISSUE TITLE
mfem@4.4.0 +rocm build fails: config/defaults.mk:184: Unable to determine HIP_DIR...

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#30483]
### Steps to reproduce the issue

`mfem@4.4.0 +rocm` build fails using:
* `spack/develop` (250d5d2c00ad9d6a747499b1160bc4a460266fae from `Wed May 4 13:30:15 2022 -0400`)
* Ubuntu 20.04, X86_64
* GCC 9.4.0
* ROCm 5.0.2

Concrete spec: [mfem-6kjw6vo.spec.json.txt](https://github.com/spack/spack/files/8626733/mfem-6kjw6vo.spec.json.txt)

Quickly reproducible using cached dependency binaries and Docker container image:
* `ecpe4s/ubuntu20.04-runner-x86_64:2022-05-01`

```
$> git clone https://github.com/spack/spack
$> (cd spack && git checkout 250d5d2c0)
$> . spack/share/spack/setup-env.sh

$> spack mirror add E4S https://cache.e4s.io
$> spack buildcache keys -it

$> spack install --cache-only --include-build-deps --only dependencies -f ./mfem-6kjw6vo.spec.json

$> spack install --no-cache -f ./mfem-6kjw6vo.spec.json
...
# SEE ERROR MESSAGE BELOW
```

### Error message

<details><summary>Error message</summary><pre>
==> Installing mfem-4.4.0-6kjw6voapywitfbej42dh7o35sbfwyxt
==> Using cached archive: /spack/var/spack/cache/_source-cache/archive/37/37250dbef6e97b16dc9ab50973e8d68bc165bb4afcdaf91b3b72c8972c87deef.tar.gz
==> No patches needed for mfem
==> mfem: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 2:
    'make' 'config' 'PREFIX=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/mfem-4.4.0-6kjw6voapywitfbej42dh7o35sbfwyxt' 'MFEM_USE_MEMALLOC=YES' 'MFEM_DEBUG=NO' 'CXX=/spack/lib/spack/env/gcc/g++' 'MFEM_USE_LIBUNWIND=NO' 'MFEM_USE_ZLIB=YES' 'MFEM_USE_METIS=YES' 'MFEM_USE_METIS_5=YES' 'MFEM_THREAD_SAFE=NO' 'MFEM_USE_MPI=YES' 'MFEM_USE_LAPACK=NO' 'MFEM_USE_SUPERLU=NO' 'MFEM_USE_STRUMPACK=NO' 'MFEM_USE_SUITESPARSE=NO' 'MFEM_USE_SUNDIALS=NO' 'MFEM_USE_PETSC=NO' 'MFEM_USE_SLEPC=NO' 'MFEM_USE_PUMI=NO' 'MFEM_USE_GSLIB=NO' 'MFEM_USE_NETCDF=NO' 'MFEM_USE_MPFR=NO' 'MFEM_USE_GNUTLS=NO' 'MFEM_USE_OPENMP=NO' 'MFEM_USE_CONDUIT=NO' 'MFEM_USE_CUDA=NO' 'MFEM_USE_HIP=YES' 'MFEM_USE_OCCA=NO' 'MFEM_USE_RAJA=NO' 'MFEM_USE_AMGX=NO' 'MFEM_USE_CEED=NO' 'MFEM_USE_UMPIRE=NO' 'MFEM_MPIEXEC=mpirun' 'MFEM_MPIEXEC_NP=-np' 'MPICXX=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/mpich-4.0.2-ezlhwrd3oenacpj4jstb2o7jsxebfdwn/bin/mpic++' 'HYPRE_OPT=-I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/hypre-2.24.0-pt6ghf7xa3frzmc6xfnzjyuxpuzjfdnn/include' 'HYPRE_LIB=-Wl,-rpath,/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/hypre-2.24.0-pt6ghf7xa3frzmc6xfnzjyuxpuzjfdnn/lib -Wl,-rpath,/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/openblas-0.3.20-v6f5oo46ojjy43rj7nauj2452c5upjhw/lib -L/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/hypre-2.24.0-pt6ghf7xa3frzmc6xfnzjyuxpuzjfdnn/lib -L/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/openblas-0.3.20-v6f5oo46ojjy43rj7nauj2452c5upjhw/lib -lHYPRE -lopenblas' 'METIS_OPT=-I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/metis-5.1.0-edqxaqcguht7hql2dvj2quhmzbiqssru/include' 'METIS_LIB=-Wl,-rpath,/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/metis-5.1.0-edqxaqcguht7hql2dvj2quhmzbiqssru/lib -L/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/metis-5.1.0-edqxaqcguht7hql2dvj2quhmzbiqssru/lib -lmetis' 'ZLIB_OPT=-I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/zlib-1.2.12-boagchtqr6gynwnipyg5ggqxc6nt6z7f/include' 'ZLIB_LIB=-Wl,-rpath,/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/zlib-1.2.12-boagchtqr6gynwnipyg5ggqxc6nt6z7f/lib -L/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/zlib-1.2.12-boagchtqr6gynwnipyg5ggqxc6nt6z7f/lib -lz' 'HIP_CXX=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/hip-5.0.2-zxtdoythrectfv7epw3a3kdeayjsap2g/bin/hipcc' 'HIP_ARCH=gfx908'

1 error found in build log:
     1    ==> mfem: Executing phase: 'configure'
     2    ==> [2022-05-04-12:51:42.830382] 'make' 'config' 'PREFIX=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/mfem-4.4.0-6kjw6voapywitf
          bej42dh7o35sbfwyxt' 'MFEM_USE_MEMALLOC=YES' 'MFEM_DEBUG=NO' 'CXX=/spack/lib/spack/env/gcc/g++' 'MFEM_USE_LIBUNWIND=NO' 'MFEM_USE_ZLIB=
          YES' 'MFEM_USE_METIS=YES' 'MFEM_USE_METIS_5=YES' 'MFEM_THREAD_SAFE=NO' 'MFEM_USE_MPI=YES' 'MFEM_USE_LAPACK=NO' 'MFEM_USE_SUPERLU=NO' '
          MFEM_USE_STRUMPACK=NO' 'MFEM_USE_SUITESPARSE=NO' 'MFEM_USE_SUNDIALS=NO' 'MFEM_USE_PETSC=NO' 'MFEM_USE_SLEPC=NO' 'MFEM_USE_PUMI=NO' 'MF
          EM_USE_GSLIB=NO' 'MFEM_USE_NETCDF=NO' 'MFEM_USE_MPFR=NO' 'MFEM_USE_GNUTLS=NO' 'MFEM_USE_OPENMP=NO' 'MFEM_USE_CONDUIT=NO' 'MFEM_USE_CUD
          A=NO' 'MFEM_USE_HIP=YES' 'MFEM_USE_OCCA=NO' 'MFEM_USE_RAJA=NO' 'MFEM_USE_AMGX=NO' 'MFEM_USE_CEED=NO' 'MFEM_USE_UMPIRE=NO' 'MFEM_MPIEXE
          C=mpirun' 'MFEM_MPIEXEC_NP=-np' 'MPICXX=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/mpich-4.0.2-ezlhwrd3oenacpj4jstb2o7jsxebfd
          wn/bin/mpic++' 'HYPRE_OPT=-I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/hypre-2.24.0-pt6ghf7xa3frzmc6xfnzjyuxpuzjfdnn/include'
           'HYPRE_LIB=-Wl,-rpath,/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/hypre-2.24.0-pt6ghf7xa3frzmc6xfnzjyuxpuzjfdnn/lib -Wl,-rpat
          h,/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/openblas-0.3.20-v6f5oo46ojjy43rj7nauj2452c5upjhw/lib -L/spack/opt/spack/linux-ub
          untu20.04-x86_64/gcc-9.4.0/hypre-2.24.0-pt6ghf7xa3frzmc6xfnzjyuxpuzjfdnn/lib -L/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/ope
          nblas-0.3.20-v6f5oo46ojjy43rj7nauj2452c5upjhw/lib -lHYPRE -lopenblas' 'METIS_OPT=-I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0
          /metis-5.1.0-edqxaqcguht7hql2dvj2quhmzbiqssru/include' 'METIS_LIB=-Wl,-rpath,/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/metis
          -5.1.0-edqxaqcguht7hql2dvj2quhmzbiqssru/lib -L/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/metis-5.1.0-edqxaqcguht7hql2dvj2quhm
          zbiqssru/lib -lmetis' 'ZLIB_OPT=-I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/zlib-1.2.12-boagchtqr6gynwnipyg5ggqxc6nt6z7f/inc
          lude' 'ZLIB_LIB=-Wl,-rpath,/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/zlib-1.2.12-boagchtqr6gynwnipyg5ggqxc6nt6z7f/lib -L/spa
          ck/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/zlib-1.2.12-boagchtqr6gynwnipyg5ggqxc6nt6z7f/lib -lz' 'HIP_CXX=/spack/opt/spack/linux-
          ubuntu20.04-x86_64/gcc-9.4.0/hip-5.0.2-zxtdoythrectfv7epw3a3kdeayjsap2g/bin/hipcc' 'HIP_ARCH=gfx908'
  >> 3    config/defaults.mk:184: *** Unable to determine HIP_DIR. Please set it manually..  Stop.

See build log for details:
  /tmp/root/spack-stage/spack-stage-mfem-4.4.0-6kjw6voapywitfbej42dh7o35sbfwyxt/spack-build-out.txt
</pre></details>

### Information on your system

* **Spack:** 0.18.0.dev0 (250d5d2c00ad9d6a747499b1160bc4a460266fae)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/8626742/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/8626743/spack-build-out.txt)

@acfisher @goxberry @markcmiller86 @tzanio @v-dobrev @wspear

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by v-dobrev** [comment]
This looks like a non-standard ROCm installation. I've only tested with external system installs of ROCm, which are, in most cases, in `/opt/rocm` or `/opt/rocm-x.y.z`.

I suspect this is `hip` installed through Spack? To support that, I'll need to figure out how Spack breaks down the full ROCm install into packages and then expand the logic in the `mfem` Spack package. This will also create issues with the `hypre` ROCm dependencies (`rocsparse` and `rocrand`, typically) which are currently assumed to be in the standard location, `$ROCM_PATH/lib`.

**Comment by eugeneswalker** [comment]
> I suspect this is `hip` installed through Spack?

Yes, that is right. Any update on this? Would it help if we pinged anyone else on this issue?

**Comment by v-dobrev** [comment]
@eugeneswalker, do you have an easy way to test if #33480 resolves this issue? I'd test it myself but I suspect building ROCm+HIP through Spack takes some time.

**Comment by eugeneswalker** [comment]
> @eugeneswalker, do you have an easy way to test if #33480 resolves this issue? I'd test it myself but I suspect building ROCm+HIP through Spack takes some time.

Yes, I can try.

Here's what happens when I try building `mfem +rocm` w/ PR#33480, using spack-built ROCm components.
```
==> Installing mfem-4.5.0-4txk5u5zllqdbbwhzgw6yqwq4pldbyn4
==> No binary for mfem-4.5.0-4txk5u5zllqdbbwhzgw6yqwq4pldbyn4 found: installing from source
==> Fetching https://bit.ly/mfem-4-5
==> No patches needed for mfem
==> mfem: Executing phase: 'configure'
==> mfem: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16' 'lib'

12 errors found in build log:
     117    /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hip-5.2.3-xm7ihlx36lsdmncrulfewcma633omx2w/bin/hipcc   -O3 -std=c++11 --amdg
            pu-target=gfx90a -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hypre-2.26.0-v3vk2utx4pbr7f5melgf2gxsm3m5naxc/include -I/
            spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/mpich-4.0.2-rev2pv3f7stxoyxtejata3v7uarusf6g/include -I/spack/opt/spack/linux
            -ubuntu20.04-x86_64/gcc-11.1.0/metis-5.1.0-v3fsq7kdbz7rzxqrv36lutpvcmaxtbw3/include  -I/spack/opt/spack/linux-ubuntu20.04-x86_64/
            gcc-11.1.0/zlib-1.2.12-hdtjtngxfoicw3xoif5xrdopjdngev3h/include  -c linalg/cpardiso.cpp -o linalg/cpardiso.o
     118    /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hip-5.2.3-xm7ihlx36lsdmncrulfewcma633omx2w/bin/hipcc   -O3 -std=c++11 --amdg
            pu-target=gfx90a -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hypre-2.26.0-v3vk2utx4pbr7f5melgf2gxsm3m5naxc/include -I/
            spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/mpich-4.0.2-rev2pv3f7stxoyxtejata3v7uarusf6g/include -I/spack/opt/spack/linux
            -ubuntu20.04-x86_64/gcc-11.1.0/metis-5.1.0-v3fsq7kdbz7rzxqrv36lutpvcmaxtbw3/include  -I/spack/opt/spack/linux-ubuntu20.04-x86_64/
            gcc-11.1.0/zlib-1.2.12-hdtjtngxfoicw3xoif5xrdopjdngev3h/include  -c linalg/blockoperator.cpp -o linalg/blockoperator.o
     119    In file included from linalg/densemat.cpp:16:
     120    In file included from linalg/kernels.hpp:21:
     121    In file included from linalg/tlayout.hpp:16:
     122    In file included from linalg/../fem/fespace.hpp:16:
  >> 123    linalg/../fem/../linalg/sparsemat.hpp:26:10: fatal error: 'hipsparse.h' file not found
     124    #include <hipsparse.h>
     125             ^~~~~~~~~~~~~
     126    /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hip-5.2.3-xm7ihlx36lsdmncrulfewcma633omx2w/bin/hipcc   -O3 -std=c++11 --amdg
            pu-target=gfx90a -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hypre-2.26.0-v3vk2utx4pbr7f5melgf2gxsm3m5naxc/include -I/
            spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/mpich-4.0.2-rev2pv3f7stxoyxtejata3v7uarusf6g/include -I/spack/opt/spack/linux
            -ubuntu20.04-x86_64/gcc-11.1.0/metis-5.1.0-v3fsq7kdbz7rzxqrv36lutpvcmaxtbw3/include  -I/spack/opt/spack/linux-ubuntu20.04-x86_64/
            gcc-11.1.0/zlib-1.2.12-hdtjtngxfoicw3xoif5xrdopjdngev3h/include  -c linalg/complex_operator.cpp -o linalg/complex_operator.o
     127    In file included from linalg/blockmatrix.cpp:15:
  >> 128    linalg/sparsemat.hpp:26:10: fatal error: 'hipsparse.h' file not found
     129    #include <hipsparse.h>
     130             ^~~~~~~~~~~~~
     131    In file included from linalg/sparsemat.cpp:14:
     132    In file included from linalg/linalg.hpp:20:
  >> 133    linalg/sparsemat.hpp:26:10: fatal error: 'hipsparse.h' file not found
     134    #include <hipsparse.h>
     135             ^~~~~~~~~~~~~
     136    1 error generated when compiling for gfx90a.
  >> 137    make: *** [makefile:454: linalg/blockmatrix.o] Error 1
     138    make: *** Waiting for unfinished jobs....
     139    In file included from linalg/hypre_parcsr.cpp:19:
     140    In file included from linalg/hypre.hpp:59:
  >> 141    linalg/sparsemat.hpp:26:10: fatal error: 'hipsparse.h' file not found
     142    #include <hipsparse.h>
     143             ^~~~~~~~~~~~~
     144    1 error generated when compiling for gfx90a.
     145    1 error generated when compiling for gfx90a.
  >> 146    make: *** [makefile:454: linalg/densemat.o] Error 1
  >> 147    make: *** [makefile:454: linalg/hypre_parcsr.o] Error 1
     148    In file included from linalg/cpardiso.cpp:2:
     149    In file included from linalg/hypre.hpp:59:
  >> 150    linalg/sparsemat.hpp:26:10: fatal error: 'hipsparse.h' file not found
     151    #include <hipsparse.h>
     152             ^~~~~~~~~~~~~
     153    1 error generated when compiling for gfx90a.
  >> 154    make: *** [makefile:454: linalg/cpardiso.o] Error 1
     155    1 error generated when compiling for gfx90a.
  >> 156    make: *** [makefile:454: linalg/sparsemat.o] Error 1
     157    In file included from linalg/complex_operator.cpp:12:
     158    In file included from linalg/complex_operator.hpp:16:
  >> 159    linalg/sparsemat.hpp:26:10: fatal error: 'hipsparse.h' file not found
     160    #include <hipsparse.h>
     161             ^~~~~~~~~~~~~
     162    1 error generated when compiling for gfx90a.
  >> 163    make: *** [makefile:454: linalg/complex_operator.o] Error 1
```

**Comment by eugeneswalker** [comment]
>      159    linalg/sparsemat.hpp:26:10: fatal error: 'hipsparse.h' file not found
>      160    #include <hipsparse.h>
>      161             ^~~~~~~~~~~~~
>      162    1 error generated when compiling for gfx90a.

Interestingly, making `hipsparse` an explicit dependency doesn't add `hipsparse`'s include path. Once I make `hipsparse` an explicit dependency, I still see lines like this that give the error above:
```
/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hip-5.2.3-xm7ihlx36lsdmncrulfewcma633omx2w/bin/hipcc \
-O3 \
-std=c++11 \
--amdgpu-target=gfx90a \
-I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hypre-2.26.0-v3vk2utx4pbr7f5melgf2gxsm3m5naxc/include \
-I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/mpich-4.0.2-rev2pv3f7stxoyxtejata3v7uarusf6g/include \
-I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/metis-5.1.0-v3fsq7kdbz7rzxqrv36lutpvcmaxtbw3/include  \
-I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/zlib-1.2.12-hdtjtngxfoicw3xoif5xrdopjdngev3h/include \
-c linalg/complex_operator.cpp \
-o linalg/complex_operator.o
```

Simply adding the following is enough. I figured Spack would set this up automatically when `hipsparse` was added as an explicit dependency...
```
-I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hipsparse-5.2.3-f5azlc24pk7p2njvhc7pxplpr3ndyxwk/include
```

**Comment by eugeneswalker** [comment]
Here are the full logs. I can upload more if I missed any that would help.
[spack-build-env.txt](https://github.com/spack/spack/files/9866435/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/9866436/spack-build-out.txt)
[spack-build-01-configure-out.txt](https://github.com/spack/spack/files/9866437/spack-build-01-configure-out.txt)

**Comment by eugeneswalker** [comment]
I was able to get it to find `hipsparse` include directory like this:
* https://github.com/eugeneswalker/spack/commit/d2da57a34a72c4bb09d5fabbdfc9a3367260a272

Maybe not the best way to go about it? What do you think?

**Comment by v-dobrev** [comment]
@eugeneswalker, thank you for testing! I pushed a small tweak to #33480 that should resolve the `hipsparse` include path issue. Can you test it, if you don't mind?

**Comment by eugeneswalker** [comment]
> @eugeneswalker, thank you for testing! I pushed a small tweak to #33480 that should resolve the `hipsparse` include path issue. Can you test it, if you don't mind?

That did it! Thank you!

**Comment by v-dobrev** [comment]
Excellent! Thanks for testing!
