### ISSUE TITLE
hpx@1.7.1 +rocm build fails: asio/query.hpp:274:3: dynamic initialization is not supported for...

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#30484]
### Steps to reproduce the issue

`hpx@1.7.1 +rocm` build fails using:
* `spack/develop` (250d5d2c00ad9d6a747499b1160bc4a460266fae from `Wed May 4 13:30:15 2022 -0400`)
* Ubuntu 20.04, X86_64
* GCC 9.4.0
* ROCm 5.0.2

Concrete spec: [hpx-4br5qqq.spec.json.txt](https://github.com/spack/spack/files/8626750/hpx-4br5qqq.spec.json.txt)

Quickly reproducible using cached dependency binaries and Docker container image:
* `ecpe4s/ubuntu20.04-runner-x86_64:2022-05-01`

```
$> git clone https://github.com/spack/spack
$> (cd spack && git checkout 250d5d2c0)
$> . spack/share/spack/setup-env.sh

$> spack mirror add E4S https://cache.e4s.io
$> spack buildcache keys -it

$> spack install --cache-only --include-build-deps --only dependencies -f ./hpx-4br5qqq.spec.json

$> spack install --no-cache -f ./hpx-4br5qqq.spec.json
...
# SEE ERROR MESSAGE BELOW
```

### Error message

<details><summary>Error message</summary><pre>
  >> 1040    /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/asio-1.21.0-32djidazdwbxmkul4qrs4vesi3fa37ee/include/asio/execution/execute.hpp:254:3: error: dynamic initializat
             ion is not supported for __device__, __constant__, __shared__, and __managed__ variables.
     1041      execute = asio_execution_execute_fn::static_instance<>::instance;
     1042      ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     1043    In file included from /tmp/root/spack-stage/spack-stage-hpx-1.7.1-4br5qqqoybqsvovftix2ooot3wdpflfq/spack-build-4br5qqq/plugins/parcelport/tcp/CMakeFiles/parcelport_t
             cp.dir/Unity/unity_0_cxx.cxx:3:
     1044    In file included from /tmp/root/spack-stage/spack-stage-hpx-1.7.1-4br5qqqoybqsvovftix2ooot3wdpflfq/spack-src/plugins/parcelport/tcp/connection_handler_tcp.cpp:15:
     1045    In file included from /tmp/root/spack-stage/spack-stage-hpx-1.7.1-4br5qqqoybqsvovftix2ooot3wdpflfq/spack-src/libs/core/asio/include/hpx/asio/asio_util.hpp:17:
     1046    In file included from /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/asio-1.21.0-32djidazdwbxmkul4qrs4vesi3fa37ee/include/asio/io_context.hpp:26:
     1047    In file included from /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/asio-1.21.0-32djidazdwbxmkul4qrs4vesi3fa37ee/include/asio/execution.hpp:18:
     1048    In file included from /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/asio-1.21.0-32djidazdwbxmkul4qrs4vesi3fa37ee/include/asio/execution/allocator.hpp:21:
     1049    In file included from /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/asio-1.21.0-32djidazdwbxmkul4qrs4vesi3fa37ee/include/asio/execution/scheduler.hpp:20:
  >> 1050    /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/asio-1.21.0-32djidazdwbxmkul4qrs4vesi3fa37ee/include/asio/execution/schedule.hpp:246:3: error: dynamic initializa
             tion is not supported for __device__, __constant__, __shared__, and __managed__ variables.
     1051      schedule = asio_execution_schedule_fn::static_instance<>::instance;
     1052      ^          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
</pre></details>

### Information on your system

* **Spack:** 0.18.0.dev0 (250d5d2c00ad9d6a747499b1160bc4a460266fae)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/8626795/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/8626796/spack-build-out.txt)

@albestro @msimberg @teonnik @wspear

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by msimberg** [comment]
Thanks @eugeneswalker for reporting. Since the actual error comes from asio this may just need a conflict (if it works with older versions of asio), or some ifdefing in HPX itself... In any case, I'll try to do something about this soonish.

**Comment by eugeneswalker** [comment]
Issue is resolved by https://github.com/spack/spack/pull/30620
