### ISSUE TITLE
slate@2021.05.02 +rocm build fails: hipify-perl: not found

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#30489]
### Steps to reproduce the issue

`slate@2021.05.02 +rocm` build fails using:
* `spack/develop` (250d5d2c00ad9d6a747499b1160bc4a460266fae from `Wed May 4 13:30:15 2022 -0400`)
* Ubuntu 20.04, X86_64
* GCC 9.4.0
* ROCm 5.0.2

Concrete spec: [slate-llhurqr.spec.json.txt](https://github.com/spack/spack/files/8627815/slate-llhurqr.spec.json.txt)

Quickly reproducible using cached dependency binaries and Docker container image:
* `ecpe4s/ubuntu20.04-runner-x86_64:2022-05-01`

```
$> git clone https://github.com/spack/spack
$> (cd spack && git checkout 250d5d2c0)
$> . spack/share/spack/setup-env.sh

$> spack mirror add E4S https://cache.e4s.io
$> spack buildcache keys -it

$> spack install --cache-only --include-build-deps --only dependencies -f ./slate-llhurqr.spec.json

$> spack install --no-cache -f ./slate-llhurqr.spec.json
...
# SEE ERROR MESSAGE BELOW
```

### Error message

<details><summary>Error message</summary><pre>
==> Installing slate-2021.05.02-llhurqrbb5igu3ipvppcce7ueqlztqjr
==> Fetching https://mirror.spack.io/_source-cache/archive/29/29667a9e869e41fbc22af1ae2bcd425d79b4094bbb3f21c411888e7adc5d12e3.tar.gz
==> No patches needed for slate
==> slate: Executing phase: 'cmake'
==> slate: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

12 errors found in build log:
     71     [  4%] Generating src/hip/device_transpose.hip.cc
     72     /bin/sh: 1: hipify-perl: not found
     73     hipify-perl /tmp/root/spack-stage/spack-stage-slate-2021.05.02-llhurqrbb5igu3ipvppcce7ueqlztqjr/spack-src/src/cuda/device_gecopy.cu > /tmp/root/spack-sta
            ge/spack-stage-slate-2021.05.02-llhurqrbb5igu3ipvppcce7ueqlztqjr/spack-build-llhurqr/src/hip/device_gecopy.hip.cc
     74     hipify-perl /tmp/root/spack-stage/spack-stage-slate-2021.05.02-llhurqrbb5igu3ipvppcce7ueqlztqjr/spack-src/src/cuda/device_genorm.cu > /tmp/root/spack-sta
            ge/spack-stage-slate-2021.05.02-llhurqrbb5igu3ipvppcce7ueqlztqjr/spack-build-llhurqr/src/hip/device_genorm.hip.cc
     75     [  5%] Generating src/hip/device_synorm.hip.cc
     76     /bin/sh: 1: hipify-perl: not found
  >> 77     make[2]: *** [CMakeFiles/slate.dir/build.make:126: src/hip/device_util.cuh] Error 127
     78     make[2]: *** Deleting file 'src/hip/device_util.cuh'
     79     make[2]: *** Waiting for unfinished jobs....
  >> 80     make[2]: *** [CMakeFiles/slate.dir/build.make:122: src/hip/device_geadd.hip.cc] Error 127
     81     make[2]: *** Deleting file 'src/hip/device_geadd.hip.cc'
     82     [  6%] Generating src/hip/device_henorm.hip.cc
     83     hipify-perl /tmp/root/spack-stage/spack-stage-slate-2021.05.02-llhurqrbb5igu3ipvppcce7ueqlztqjr/spack-src/src/cuda/device_transpose.cu > /tmp/root/spack-
            stage/spack-stage-slate-2021.05.02-llhurqrbb5igu3ipvppcce7ueqlztqjr/spack-build-llhurqr/src/hip/device_transpose.hip.cc
     84     /bin/sh: 1: hipify-perl: not found
     85     hipify-perl /tmp/root/spack-stage/spack-stage-slate-2021.05.02-llhurqrbb5igu3ipvppcce7ueqlztqjr/spack-src/src/cuda/device_geset.cu > /tmp/root/spack-stag
            e/spack-stage-slate-2021.05.02-llhurqrbb5igu3ipvppcce7ueqlztqjr/spack-build-llhurqr/src/hip/device_geset.hip.cc
     86     /bin/sh: 1: hipify-perl: not found
  >> 87     make[2]: *** [CMakeFiles/slate.dir/build.make:158: src/hip/device_tzcopy.hip.cc] Error 127
     88     make[2]: *** Deleting file 'src/hip/device_tzcopy.hip.cc'
  >> 89     make[2]: *** [CMakeFiles/slate.dir/build.make:130: src/hip/device_gecopy.hip.cc] Error 127
     90     make[2]: *** Deleting file 'src/hip/device_gecopy.hip.cc'
     91     /bin/sh: 1: hipify-perl: not found
     92     hipify-perl /tmp/root/spack-stage/spack-stage-slate-2021.05.02-llhurqrbb5igu3ipvppcce7ueqlztqjr/spack-src/src/cuda/device_synorm.cu > /tmp/root/spack-sta
            ge/spack-stage-slate-2021.05.02-llhurqrbb5igu3ipvppcce7ueqlztqjr/spack-build-llhurqr/src/hip/device_synorm.hip.cc
     93     [  7%] Generating src/hip/device_trnorm.hip.cc
  >> 94     make[2]: *** [CMakeFiles/slate.dir/build.make:134: src/hip/device_genorm.hip.cc] Error 127
     95     make[2]: *** Deleting file 'src/hip/device_genorm.hip.cc'
     96     /bin/sh: 1: hipify-perl: not found
     97     hipify-perl /tmp/root/spack-stage/spack-stage-slate-2021.05.02-llhurqrbb5igu3ipvppcce7ueqlztqjr/spack-src/src/cuda/device_henorm.cu > /tmp/root/spack-sta
            ge/spack-stage-slate-2021.05.02-llhurqrbb5igu3ipvppcce7ueqlztqjr/spack-build-llhurqr/src/hip/device_henorm.hip.cc
     98     /bin/sh: 1: hipify-perl: not found
  >> 99     make[2]: *** [CMakeFiles/slate.dir/build.make:138: src/hip/device_geset.hip.cc] Error 127
     100    make[2]: *** Deleting file 'src/hip/device_geset.hip.cc'
  >> 101    make[2]: *** [CMakeFiles/slate.dir/build.make:150: src/hip/device_transpose.hip.cc] Error 127
     102    make[2]: *** Deleting file 'src/hip/device_transpose.hip.cc'
     103    /bin/sh: 1: hipify-perl: not found
  >> 104    make[2]: *** [CMakeFiles/slate.dir/build.make:146: src/hip/device_synorm.hip.cc] Error 127
     105    make[2]: *** Deleting file 'src/hip/device_synorm.hip.cc'
     106    hipify-perl /tmp/root/spack-stage/spack-stage-slate-2021.05.02-llhurqrbb5igu3ipvppcce7ueqlztqjr/spack-src/src/cuda/device_trnorm.cu > /tmp/root/spack-sta
            ge/spack-stage-slate-2021.05.02-llhurqrbb5igu3ipvppcce7ueqlztqjr/spack-build-llhurqr/src/hip/device_trnorm.hip.cc
     107    /bin/sh: 1: hipify-perl: not found
  >> 108    make[2]: *** [CMakeFiles/slate.dir/build.make:142: src/hip/device_henorm.hip.cc] Error 127
     109    make[2]: *** Deleting file 'src/hip/device_henorm.hip.cc'
     110    /bin/sh: 1: hipify-perl: not found
  >> 111    make[2]: *** [CMakeFiles/slate.dir/build.make:154: src/hip/device_trnorm.hip.cc] Error 127
     112    make[2]: *** Deleting file 'src/hip/device_trnorm.hip.cc'
     113    make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-slate-2021.05.02-llhurqrbb5igu3ipvppcce7ueqlztqjr/spack-build-llhurqr'
  >> 114    make[1]: *** [CMakeFiles/Makefile2:88: CMakeFiles/slate.dir/all] Error 2
     115    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-slate-2021.05.02-llhurqrbb5igu3ipvppcce7ueqlztqjr/spack-build-llhurqr'
  >> 116    make: *** [Makefile:139: all] Error 2

See build log for details:
  /tmp/root/spack-stage/spack-stage-slate-2021.05.02-llhurqrbb5igu3ipvppcce7ueqlztqjr/spack-build-out.txt
</pre></details>

### Information on your system

* **Spack:** 0.18.0.dev0 (250d5d2c00ad9d6a747499b1160bc4a460266fae)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/8627822/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/8627823/spack-build-out.txt)

@G-Ragghianti @mgates3 @wspear @srekolam 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by mgates3** [comment]
The same issue was just reported outside Spack as [SLATE issue #38](https://bitbucket.org/icl/slate/issues/38/hipify-perl-not-found). While [ROCm 5.x docs still have hipify](https://docs.amd.com/bundle/HIPify-Reference-Guide-v5.1/page/HIPify.html), the ROCm installation seems to be missing it.

The easiest solution may be for SLATE to do a new release that includes the HIP source files, so doesn't depend on hipify at compile time. We can do that shortly.

**Comment by G-Ragghianti** [comment]
The hipify-perl command is now provided by the rocm RPM hip-clang.  If the corresponding spack package also provides hipify-perl, then this may be as simple as adding hip-clang to the slate (or blaspp/lapackpp) dependencies. I'm looking into it.

**Comment by G-Ragghianti** [comment]
I'm preparing a PR for this.

**Comment by eugeneswalker** [comment]
Issue resolved by now-merged https://github.com/spack/spack/pull/30576
