### ISSUE TITLE
mesa@22.0.2 ^llvm-amdgpu: meson.build: LLVM was built without RTTI, so Mesa must also disable RTTI

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#30508]
### Steps to reproduce the issue

`mesa@22.0.2 ^llvm-amdgpu@5.0.2` build fails using:
* `spack/develop` (0dd9e5c86fa1c67e72bc64966ccdaceb4b44c193 from `Thu May 5 09:38:45 2022 -0700`)
* Ubuntu 20.04, X86_64
* GCC 9.4.0

Concrete spec: [mesa-723ufme.spec.json.txt](https://github.com/spack/spack/files/8633863/mesa-723ufme.spec.json.txt)

Concretization:
```
 -   mesa@22.0.2%gcc@9.4.0+glx+llvm+opengl~opengles+osmesa~strip buildtype=release default_library=shared patches=ada85be arch=linux-ubuntu20.04-x86_64
[+]      ^bison@3.8.2%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]          ^diffutils@3.8%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]              ^libiconv@1.16%gcc@9.4.0 libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]          ^m4@1.4.19%gcc@9.4.0+sigsegv patches=9dc5fbd,bfdffa7 arch=linux-ubuntu20.04-x86_64
[+]              ^libsigsegv@2.13%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]          ^perl@5.34.1%gcc@9.4.0+cpanm+shared+threads arch=linux-ubuntu20.04-x86_64
[+]              ^berkeley-db@18.1.40%gcc@9.4.0+cxx~docs+stl patches=b231fcc arch=linux-ubuntu20.04-x86_64
[+]              ^bzip2@1.0.8%gcc@9.4.0~debug~pic+shared arch=linux-ubuntu20.04-x86_64
[+]              ^gdbm@1.19%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]                  ^readline@8.1%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]                      ^ncurses@6.2%gcc@9.4.0~symlinks+termlib abi=none arch=linux-ubuntu20.04-x86_64
[+]                          ^pkgconf@1.8.0%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]              ^zlib@1.2.12%gcc@9.4.0+optimize+pic+shared patches=0d38234 arch=linux-ubuntu20.04-x86_64
[+]      ^cmake@3.23.1%gcc@9.4.0~doc+ncurses+ownlibs~qt build_type=Release arch=linux-ubuntu20.04-x86_64
[+]          ^openssl@1.1.1n%gcc@9.4.0~docs~shared certs=system arch=linux-ubuntu20.04-x86_64
[+]      ^expat@2.4.8%gcc@9.4.0+libbsd arch=linux-ubuntu20.04-x86_64
[+]          ^libbsd@0.11.5%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]              ^libmd@1.0.4%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]      ^flex@2.6.3%gcc@9.4.0+lex~nls arch=linux-ubuntu20.04-x86_64
[+]          ^findutils@4.9.0%gcc@9.4.0 patches=440b954 arch=linux-ubuntu20.04-x86_64
[+]      ^gettext@0.21%gcc@9.4.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-ubuntu20.04-x86_64
[+]          ^libxml2@2.9.13%gcc@9.4.0~python arch=linux-ubuntu20.04-x86_64
[+]              ^xz@5.2.5%gcc@9.4.0+pic libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]          ^tar@1.34%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]      ^glproto@1.4.17%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]          ^util-macros@1.19.3%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]      ^libunwind@1.6.2%gcc@9.4.0~block_signals~conservative_checks~cxx_exceptions~debug~debug_frame+docs+pic+tests+weak_backtrace+xz~zlib components=none libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]      ^libx11@1.7.0%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]          ^inputproto@2.3.2%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]          ^kbproto@1.0.7%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]          ^libxcb@1.14%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]              ^libpthread-stubs@0.4%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]              ^libxau@1.0.8%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]                  ^xproto@7.0.31%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]              ^libxdmcp@1.1.2%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]              ^xcb-proto@1.14.1%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]          ^xextproto@7.3.0%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]          ^xtrans@1.3.5%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]      ^libxext@1.3.3%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]      ^libxt@1.1.5%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]          ^libice@1.0.9%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]          ^libsm@1.2.3%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]              ^util-linux-uuid@2.37.4%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]      ^llvm-amdgpu@5.0.2%gcc@9.4.0~ipo~link_llvm_dylib~llvm_dylib~openmp+rocm-device-libs build_type=Release arch=linux-ubuntu20.04-x86_64
[+]          ^python@3.8.12%gcc@9.4.0+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93,4c24573,f2fd060 arch=linux-ubuntu20.04-x86_64
[+]              ^libffi@3.4.2%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]              ^sqlite@3.38.3%gcc@9.4.0+column_metadata+dynamic_extensions+fts~functions+rtree arch=linux-ubuntu20.04-x86_64
[+]          ^z3@4.8.16%gcc@9.4.0~gmp~ipo~python build_type=RelWithDebInfo arch=linux-ubuntu20.04-x86_64
[+]      ^meson@0.62.1%gcc@9.4.0 patches=aa6c50d arch=linux-ubuntu20.04-x86_64
[+]          ^ninja@1.10.2%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]          ^py-pip@21.3.1%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]          ^py-setuptools@59.4.0%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]              ^py-wheel@0.37.0%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]      ^py-mako@1.1.6%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]          ^py-markupsafe@2.0.1%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]      ^xrandr@1.5.0%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]          ^libxrandr@1.5.0%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]              ^libxrender@0.9.10%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]                  ^renderproto@0.11.1%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
[+]              ^randrproto@1.5.0%gcc@9.4.0 arch=linux-ubuntu20.04-x86_64
```

Quickly reproducible using cached dependency binaries and Docker container image:
* `ecpe4s/ubuntu20.04-runner-x86_64:2022-05-01`

```
$> git clone https://github.com/spack/spack
$> (cd spack && git checkout 0dd9e5)
$> . spack/share/spack/setup-env.sh

$> spack mirror add E4S https://cache.e4s.io
$> spack buildcache keys -it

$> spack install --cache-only --include-build-deps --only dependencies -f ./mesa-723ufme.spec.json

$> spack install --no-cache -f ./mesa-723ufme.spec.json
...
# SEE ERROR MESSAGE BELOW
```

### Error message

<details><summary>Error message</summary><pre>
==> Installing mesa-22.0.2-723ufmeqf5spietql4qlkznqilcj6wrs
==> Fetching https://archive.mesa3d.org/mesa-22.0.2.tar.xz
==> Applied patch /spack/var/spack/repos/builtin/packages/mesa/mesa_check_llvm_version_suffix.patch
==> mesa: Executing phase: 'meson'
==> Error: ProcessError: Command exited with status 1:
    'meson' '/tmp/root/spack-stage/spack-stage-mesa-22.0.2-723ufmeqf5spietql4qlkznqilcj6wrs/spack-src' '--prefix=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/mesa-22.0.2-723ufmeqf5spietql4qlkznqilcj6wrs' '--libdir=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/mesa-22.0.2-723ufmeqf5spietql4qlkznqilcj6wrs/lib' '-Dbuildtype=release' '-Dstrip=false' '-Ddefault_library=shared' '-Dvulkan-drivers=' '-Dgallium-vdpau=disabled' '-Dgallium-xvmc=disabled' '-Dgallium-omx=disabled' '-Dgallium-va=disabled' '-Dgallium-xa=disabled' '-Dgallium-nine=false' '-Dgallium-opencl=disabled' '-Dbuild-tests=false' '-Dglvnd=false' '-Dosmesa=true' '-Dglx=xlib' '-Degl=disabled' '-Dgbm=disabled' '-Ddri3=disabled' '-Dopengl=true' '-Dgles1=disabled' '-Dgles2=disabled' '-Dshared-glapi=enabled' '--native-file' 'meson-native-config.ini' '-Dllvm=enabled' '-Dshared-llvm=disabled' '-Dplatforms=x11' '-Dgallium-drivers=swrast' '-Ddri-drivers='

1 error found in build log:
     191    WARNING: CMake: Dependency m for LLVM was not found
     192    WARNING: CMake: Dependency rt for LLVM was not found
     193    WARNING: CMake: Dependency dl for LLVM was not found
     194    WARNING: CMake: Dependency m for LLVM was not found
     195    Run-time dependency LLVM (modules: bitwriter, core, coroutines, executionengine, instcombine, mcdisassembler, mcjit, native, scalaropts, transformutils) fo
            und: YES 14.0.0git
     196
  >> 197    ../meson.build:1735:8: ERROR: Problem encountered: LLVM was built without RTTI, so Mesa must also disable RTTI. Use an LLVM built with LLVM_ENABLE_RTTI or
            add cpp_rtti=false.
     198
     199    A full log can be found at /tmp/root/spack-stage/spack-stage-mesa-22.0.2-723ufmeqf5spietql4qlkznqilcj6wrs/spack-src/spack-build/meson-logs/meson-log.txt

See build log for details:
  /tmp/root/spack-stage/spack-stage-mesa-22.0.2-723ufmeqf5spietql4qlkznqilcj6wrs/spack-build-out.txt
</pre></details>

### Information on your system

* **Spack:** 0.18.0.dev0 (0dd9e5c86fa1c67e72bc64966ccdaceb4b44c193)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/8634545/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/8634546/spack-build-out.txt)

@chuckatkins @v-dobrev @wspear @srekolam 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by kwryankrattiger** [comment]
https://github.com/spack/spack/pull/31145/files
