### ISSUE TITLE
Installation issue: boost context-impl unknown option for version <1.65.0

### ISSUE THREAD

**Issue by mzeyen1985** [LLNL/spack#30642]
### Steps to reproduce the issue

```console
$ spack install boost@1.64.0 +context
...
```

### Error message

<details><summary>Error message</summary><pre>
==> Error: ProcessError: Command exited with status 1:
    './b2' '--clean' '-j' '8' '--user-config=/tmp/zeyen/spack-stage/spack-stage-boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77/spack-src/user-config.jam' 'variant=release' '--disable-icu' 'context-impl=fcontext' 'link=static,shared' '--layout=system' 'toolset=gcc' 'cxxflags="-std=c++11"'

10 errors found in build log:
     25    ==> [2022-05-12-15:06:26.390676] Warning: Quotes in command arguments can confuse scripts like configure.
     26      The following arguments may cause problems when executed:
     27          cxxflags="-std=c++11"
     28      Quotes aren't needed because spack doesn't use a shell. Consider removing them.
     29      If multiple levels of quotation are required, use `ignore_quotes=True`.
     30    ==> [2022-05-12-15:06:26.390761] './b2' '--clean' '-j' '8' '--user-config=/tmp/zeyen/spack-stage/spack-stage-boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77/spack-src/user-config.jam' 'variant=releas
           e' '--disable-icu' 'context-impl=fcontext' 'link=static,shared' '--layout=system' 'toolset=gcc' 'cxxflags="-std=c++11"'
  >> 31    /tmp/zeyen/spack-stage/spack-stage-boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77/spack-src/tools/build/src/build/feature.jam:326: in validate-feature from module feature
  >> 32    error: unknown feature "<context-impl>"
  >> 33    /tmp/zeyen/spack-stage/spack-stage-boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77/spack-src/tools/build/src/build/feature.jam:360: in expand-subfeatures-aux from module feature
  >> 34    /tmp/zeyen/spack-stage/spack-stage-boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77/spack-src/tools/build/src/build/feature.jam:425: in feature.expand-subfeatures from module feature
  >> 35    /tmp/zeyen/spack-stage/spack-stage-boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77/spack-src/tools/build/src/build/build-request.jam:20: in apply-to-property-set from module build-request
     36    (builtin):-1: in sequence.transform from module sequence
  >> 37    /tmp/zeyen/spack-stage/spack-stage-boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77/spack-src/tools/build/src/build/build-request.jam:32: in build-request.expand-no-defaults from module build-request
  >> 38    /tmp/zeyen/spack-stage/spack-stage-boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77/spack-src/tools/build/src/build-system.jam:692: in load from module build-system
  >> 39    /tmp/zeyen/spack-stage/spack-stage-boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77/spack-src/tools/build/src/kernel/modules.jam:295: in import from module modules
  >> 40    /tmp/zeyen/spack-stage/spack-stage-boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77/spack-src/tools/build/src/kernel/bootstrap.jam:139: in boost-build from module
  >> 41    /tmp/zeyen/spack-stage/spack-stage-boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77/spack-src/boost-build.jam:17: in module scope from module
     42
</pre></details>

### Information on your system

* **Spack:** 0.18.0.dev0 (35a91bdd725b3433e7e93f8138468aba6af83d4a)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-skylake
* **Concretizer:** clingo

### Additional information

<details><summary>spack-build-out.txt</summary><pre>
==> boost: Executing phase: 'install'
==> [2022-05-12-15:06:13.392080] './bootstrap.sh' '--prefix=/home/zeyen/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.4.0/boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77' '--with-toolset=gcc' '--with-         libraries=context' '--without-icu'
Building Boost.Build engine with toolset gcc... tools/build/src/engine/bin.linuxx86_64/b2
Unicode/ICU support for Boost.Regex?... disabled.
Generating Boost.Build configuration in project-config.jam...

Bootstrapping is done. To build, run:

    ./b2

To adjust configuration, edit 'project-config.jam'.
Further information:

   - Command line help:
     ./b2 --help

   - Getting started guide:
     http://www.boost.org/more/getting_started/unix-variants.html

   - Boost.Build documentation:
     http://www.boost.org/build/doc/html/index.html

==> [2022-05-12-15:06:26.386253] FILTER FILE: /tmp/zeyen/spack-stage/spack-stage-boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77/spack-src/project-config.jam [replacing "^\s*using gcc.*"]
==> [2022-05-12-15:06:26.388958] '/usr/bin/gcc' '-dumpversion'
==> [2022-05-12-15:06:26.390676] Warning: Quotes in command arguments can confuse scripts like configure.
  The following arguments may cause problems when executed:
      cxxflags="-std=c++11"
  Quotes aren't needed because spack doesn't use a shell. Consider removing them.
  If multiple levels of quotation are required, use `ignore_quotes=True`.
==> [2022-05-12-15:06:26.390761] './b2' '--clean' '-j' '8' '--user-config=/tmp/zeyen/spack-stage/spack-stage-boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77/spack-src/user-config.jam' 'variant=release' '--      disable-icu' 'context-impl=fcontext' 'link=static,shared' '--layout=system' 'toolset=gcc' 'cxxflags="-std=c++11"'
/tmp/zeyen/spack-stage/spack-stage-boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77/spack-src/tools/build/src/build/feature.jam:326: in validate-feature from module feature
error: unknown feature "<context-impl>"
/tmp/zeyen/spack-stage/spack-stage-boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77/spack-src/tools/build/src/build/feature.jam:360: in expand-subfeatures-aux from module feature
/tmp/zeyen/spack-stage/spack-stage-boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77/spack-src/tools/build/src/build/feature.jam:425: in feature.expand-subfeatures from module feature
/tmp/zeyen/spack-stage/spack-stage-boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77/spack-src/tools/build/src/build/build-request.jam:20: in apply-to-property-set from module build-request
(builtin):-1: in sequence.transform from module sequence
/tmp/zeyen/spack-stage/spack-stage-boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77/spack-src/tools/build/src/build/build-request.jam:32: in build-request.expand-no-defaults from module build-request
/tmp/zeyen/spack-stage/spack-stage-boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77/spack-src/tools/build/src/build-system.jam:692: in load from module build-system
/tmp/zeyen/spack-stage/spack-stage-boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77/spack-src/tools/build/src/kernel/modules.jam:295: in import from module modules
/tmp/zeyen/spack-stage/spack-stage-boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77/spack-src/tools/build/src/kernel/bootstrap.jam:139: in boost-build from module
/tmp/zeyen/spack-stage/spack-stage-boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77/spack-src/boost-build.jam:17: in module scope from module
</pre></details>

<details><summary>spack-build-env.txt</summary><pre>
ACLOCAL_PATH=''; export ACLOCAL_PATH
CC=/home/zeyen/spack/lib/spack/env/gcc/gcc; export CC
CXX=/home/zeyen/spack/lib/spack/env/gcc/g++; export CXX
DOCKER_HOST=unix:///usr/local/lib/docker/docker.sock; export DOCKER_HOST
HOME=/home/zeyen; export HOME
HOSTTYPE=x86_64; export HOSTTYPE
LANG=en_US.utf8; export LANG
LC_ALL=C; export LC_ALL
LESSCLOSE='/usr/bin/lesspipe %s %s'; export LESSCLOSE
LESSOPEN='| /usr/bin/lesspipe %s'; export LESSOPEN
LOGNAME=zeyen; export LOGNAME
LS_COLORS='rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:'; export LS_COLORS
MANPATH=.:; export MANPATH
NAME=PSL195; export NAME
#OLDPWD=/home/zeyen; export OLDPWD
PATH='/home/zeyen/spack/lib/spack/env/gcc:/home/zeyen/spack/lib/spack/env/case-insensitive:/home/zeyen/spack/lib/spack/env:/home/zeyen/spack/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/Program Files/Common Files/Oracle/Java/javapath:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0:/mnt/c/WINDOWS/System32/OpenSSH:/mnt/c/Program Files/Java/jdk-15.0.1/bin:/mnt/c/Program Files/SlikSvn/bin:/mnt/c/Program Files/texlive/2017/bin/win32:/mnt/c/Program Files/Microsoft SQL Server/110/Tools/Binn:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files/TortoiseGit/bin:/mnt/c/Program Files/PuTTY:/mnt/c/Program Files (x86)/dotnet:/mnt/c/ProgramData/chocolatey/bin:/mnt/c/Program Files/OpenSSH-Win64:/mnt/c/Users/zeyen/AppData/Local/Microsoft/WindowsApps:/snap/bin'; export PATH
PKG_CONFIG_PATH=''; export PKG_CONFIG_PATH
#PS1='\[\e]0;\u@\h: \w\a\]${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '; export PS1
#PWD=/home/zeyen/spack; export PWD
QT_PLUGIN_PATH=''; export QT_PLUGIN_PATH
SHELL=/bin/bash; export SHELL
SHLVL=1; export SHLVL
SPACK_CC=/usr/bin/gcc; export SPACK_CC
SPACK_CC_RPATH_ARG=-Wl,-rpath,; export SPACK_CC_RPATH_ARG
SPACK_COMPILER_SPEC=gcc@9.4.0; export SPACK_COMPILER_SPEC
SPACK_CXX=/usr/bin/g++; export SPACK_CXX
SPACK_CXX_RPATH_ARG=-Wl,-rpath,; export SPACK_CXX_RPATH_ARG
SPACK_DEBUG_LOG_DIR=/home/zeyen/spack; export SPACK_DEBUG_LOG_DIR
SPACK_DEBUG_LOG_ID=boost-o7y2eop; export SPACK_DEBUG_LOG_ID
SPACK_DTAGS_TO_ADD=--disable-new-dtags; export SPACK_DTAGS_TO_ADD
SPACK_DTAGS_TO_STRIP=--enable-new-dtags; export SPACK_DTAGS_TO_STRIP
SPACK_ENV_PATH=/home/zeyen/spack/lib/spack/env:/home/zeyen/spack/lib/spack/env/case-insensitive:/home/zeyen/spack/lib/spack/env/gcc; export SPACK_ENV_PATH
SPACK_F77_RPATH_ARG=-Wl,-rpath,; export SPACK_F77_RPATH_ARG
SPACK_FC_RPATH_ARG=-Wl,-rpath,; export SPACK_FC_RPATH_ARG
SPACK_INCLUDE_DIRS=''; export SPACK_INCLUDE_DIRS
SPACK_LD_LIBRARY_PATH=/home/zeyen/spack/var/spack/environments/gspc/.spack-env/view/lib64:/home/zeyen/spack/var/spack/environments/gspc/.spack-env/view/lib; export SPACK_LD_LIBRARY_PATH
SPACK_LINKER_ARG=-Wl,; export SPACK_LINKER_ARG
SPACK_LINK_DIRS=''; export SPACK_LINK_DIRS
SPACK_PYTHON=/usr/bin/python3; export SPACK_PYTHON
SPACK_ROOT=/home/zeyen/spack; export SPACK_ROOT
SPACK_RPATH_DIRS=/home/zeyen/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.4.0/boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77/lib:/home/zeyen/spack/opt/spack/linux-ubuntu20.04-skylake/gcc-9.4.0/boost-1.64.0-o7y2eopzwh3kphewsmbvwhk3jc2yln77/lib64; export SPACK_RPATH_DIRS
SPACK_SHORT_SPEC='boost@1.64.0%gcc@9.4.0~atomic~chrono~clanglibcpp~container+context~contract~coroutine~date_time~debug~exception~fiber~filesystem~graph~graph_parallel~icu~iostreams~json~locale~log~math~mpi+multithreaded~nowide~numpy~pic~program_options~python~random~regex~serialization+shared~signals~singlethreaded~stacktrace~system~taggedlayout~test~thread~timer~type_erasure~versionedlayout~wave context-impl=fcontext cxxstd=11 patches=7f95f95 visibility=hidden arch=linux-ubuntu20.04-skylake/o7y2eop'; export SPACK_SHORT_SPEC
SPACK_SYSTEM_DIRS=/bin:/usr/bin:/usr/local/bin:/bin64:/usr/bin64:/usr/local/bin64:/include:/usr/include:/usr/local/include:/lib:/usr/lib:/usr/local/lib:/lib64:/usr/lib64:/usr/local/lib64:/:/usr:/usr/local; export SPACK_SYSTEM_DIRS
SPACK_TARGET_ARGS='-march=skylake -mtune=skylake'; export SPACK_TARGET_ARGS
SSH_AUTH_SOCK=/home/zeyen/.ssh/agent.sock; export SSH_AUTH_SOCK
TERM=xterm-256color; export TERM
USER=zeyen; export USER
WSLENV=WT_SESSION::WT_PROFILE_ID; export WSLENV
WSL_DISTRO_NAME=ubuntu; export WSL_DISTRO_NAME
WSL_INTEROP=/run/WSL/231_interop; export WSL_INTEROP
WT_PROFILE_ID='{75def201-4efb-5e32-93a0-c5647120c025}'; export WT_PROFILE_ID
WT_SESSION=70d28786-aec2-4cbb-ac09-ef6f19b52063; export WT_SESSION
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop; export XDG_DATA_DIRS
XLOCALEDIR=''; export XLOCALEDIR
_=/home/zeyen/spack/bin/spack; export _
</pre></details>

@hainest 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by hainest** [comment]
Ah, sorry. I just haven't had time to run my tests on #30496. I'll make a PR. Thanks for the report!
