### ISSUE TITLE
Installation issue: autoconf

### ISSUE THREAD

**Issue by BenWibking** [LLNL/spack#30644]
### Steps to reproduce the issue

```console
$ spack spec -l autoconf
Input spec
--------------------------------
autoconf

Concretized
--------------------------------
rwkat2a  autoconf@2.69%gcc@11.1.0 patches=35c4492,7793209,a49dd5b arch=linux-rocky8-cascadelake
cm6xqqq      ^m4@1.4.18%gcc@11.1.0+sigsegv patches=3877ab5,fc9b616 arch=linux-rocky8-cascadelake
eg7jxz3      ^perl@5.26.3%gcc@11.1.0~cpanm+shared+threads patches=8cf4302 arch=linux-rocky8-cascadelake
```

### Error message

```console
$ spack install autoconf
==> Error: Couldn't find patch for package builtin.autoconf with sha256: 7793209b33013dc0f81208718c68440c5aae80e7a1c4b8d336e382525af791a7
```

### Information on your system

* **Spack:** 0.18.0.dev0 (181a3d72d57fb3a3b4bed7ed4dc87aadb4e6f27a)
* **Python:** 3.6.8
* **Platform:** linux-rocky8-cascadelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by BenWibking** [comment]
This is a duplicate of https://github.com/spack/spack/issues/30557

**Comment by alalazo** [comment]
Duplicate of #30557

**Comment by BenWibking** [comment]
Fixed by https://github.com/spack/spack/pull/30678
