### ISSUE TITLE
Error in CI tests

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#3067]
@tgamblin I had a nasty failure in #1875 on `TestTcl`, which seems mostly unrelated to the PR. I see that many other PRs are also affected by the same failure. In #1875 I have a fix for that (last commit) that I am not sure if it should be considered a work-around or not.

My guess on the failure is that it may be an interaction between two PRs (#2920 is one of the culprits) that were fine taken singularly, but may trigger a failure if merged together. We didn't see this because we don't force a Travis build when we merge PRs that:
1. are in a green state 
2. were tested on an old revision of `develop`
3. do not exhibits conflict

I think we should enforce a PR being tested on the HEAD of `develop` to avoid errors like this in the future. What do you think?

**Comment by adamjstewart** [comment]
I was wondering why the unit tests were failing on every PR. Yes, that sounds smart to me.

**Comment by alalazo** [comment]
@adamjstewart It's kind of nasty, and I didn't have time to go to the bottom of it. The fact is that we try to install "for real" `libdwarf` and not removing the installation interacts with the mocking done in the tests.

**Comment by alalazo** [comment]
Closing as the request to be up-to-date with develop has been added.

**Comment by tgamblin** [comment]
@alalazo @adamjstewart So, we enabled the up to date checkbox, but the problem with this is that now it's going to be really slow to merge things.  Requiring things to be up to date means that even small version changes require a rebase or merge, AND re-testing.  So essentially everything has to be merged and tested sequentially, at the rate of Travis.

Personally, I'd rather take the risk of the occasional break (and maybe have a policy of immediately reverting if it happens) than require every PR to be merged sequentially.  We have a release branch for stable stuff -- I think it's normal for `develop` can have a bit of churn.  We've had 1885 PRs, and one (two?) of them have failed in `develop`.

So I'm speculatively removing the requirement -- can you let me know if you agree with this?

**Comment by adamjstewart** [comment]
I completely agree. I tried contributing to another project one time and they had this requirement. Worse yet, they sent out an email letting you know that your branch was out-of-date. every. single. new. commit. Needless to say, I closed that PR, unforked the project, and never looked back.

Is there any way that we can not force the PR to be up-to-date with develop, but force the Travis tests to run on the latest develop with the PR merged? I think that was @alalazo's original intent.

**Comment by tgamblin** [comment]
@adamjstewart: Travis by default does merge to whatever the latest develop is at the time of testing, which is pretty effective.  The issue happens when `develop` moves on after the tests complete.

It would be nice if Travis had a little more policy control over this -- e.g. maybe it should re-run every so many hours or so after the initial testing, if `develop` has changed, so that the PR has always been checked against a reasonably current version of `develop`.  I don't believe there are policy settings for that, but we can force it to happen either by closing and re-opening or by clicking the refresh button in the Travis UI.  Maybe we should start doing that for PRs that have sat around for a while.

**Comment by tgamblin** [comment]
closing -- @alalazo can reopen if he disagrees

**Comment by alalazo** [comment]
> I think that was @alalazo's original intent.

@adamjstewart Nope. My intent was to be super-safe (as much as you can be with unit tests at least) **before** merging to develop. But I understand that lowering the rate of merges may be detrimental in particular for packages. 

Ideally I think the best setting would be allow the policy if we are touching code in the core and have it off for packages, but I don't think this can be achieved with github yet. Maybe we should keep this in mind when / if we will split the repo from core.

**Comment by adamjstewart** [comment]
Yeah, I can see why that would be nice for core. But if we can't split it up, that would definitely be a pain for small package changes.
