### ISSUE TITLE
Cannot build `mpc` on Comet

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#3072]
When I try to build `mpc` on Comet, then this fails because it tries to use a system-installed `mpfr` instead of the one that Spack just installed. Spack should pass the respective configure option to point `mpc` to its `mpfr`.

This used to work. I assume this is a fall-out from the recent conversion to `AutotoolsPackage` that removed the respective configure options.

**Comment by adamjstewart** [comment]
The conversion to AutotoolsPackage in #2845 didn't remove any configure options, so it's unrelated. I'm not sure if we ever passed the options properly. I'll try building it locally and see if I can recreate the issue. If so, I'll submit a PR to pass the configure options properly.

**Comment by adamjstewart** [comment]
Hmm, I am unable to reproduce the problem you are seeing:
```
$ ldd -r /home/ajstewart/spack/opt/spack/linux-fedora25-x86_64/gcc-6.2.1/mpc-1.0.3-bjhoziwbvzgftq3gc6w42eyrjromy7wg/lib/libmpc.so
	linux-vdso.so.1 (0x00007ffdf499c000)
	libmpfr.so.4 => /home/ajstewart/spack/opt/spack/linux-fedora25-x86_64/gcc-6.2.1/mpfr-3.1.5-bevr3ajxn6an4lk5il456xm35yfsh263/lib/libmpfr.so.4 (0x00007faf10176000)
	libgmp.so.10 => /home/ajstewart/spack/opt/spack/linux-fedora25-x86_64/gcc-6.2.1/gmp-6.1.2-p2wh3r2fbpgd32a6slpig4nkepaofoxj/lib/libgmp.so.10 (0x00007faf0ff00000)
	libm.so.6 => /lib64/libm.so.6 (0x00007faf0fbda000)
	libc.so.6 => /lib64/libc.so.6 (0x00007faf0f812000)
	/lib64/ld-linux-x86-64.so.2 (0x000055db05ac8000)
```
But adding the configure option would be simple, so I'll submit a PR and you can see if it helps on Comet.

**Comment by eschnett** [comment]
@adamjstewart Yes, this patch helps, even without the explicit version constraints. (I assume those are necessary for other reasons, e.g. because they are documented in `mpc`?)

**Comment by adamjstewart** [comment]
Yep, the explicit version constraints are unrelated. I just noticed them on the [MPC download page](http://www.multiprecision.org/index.php?prog=mpc&page=download) and figured we should add them.
