### ISSUE TITLE
Installation issue: petsc

### ISSUE THREAD

**Issue by wortiz** [LLNL/spack#30727]
### Steps to reproduce the issue

```console
$ spack install petsc+mumps
...
```

### Error message

<details><summary>Error message</summary><pre>
==> Installing petsc-3.17.1-wj7ditzql2ya4eljuzdirblxpimbaium
==> No binary for petsc-3.17.1-wj7ditzql2ya4eljuzdirblxpimbaium found: installing from source
==> Using cached archive: /home/wortiz/spack/var/spack/cache/_source-cache/archive/c5/c504609d9f532327c20b6363d6a6c7647ebd3c98acfb382c28fcd3852300ddd1.tar.gz
==> No patches needed for petsc
==> petsc: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/python-3.9.12-cgrf7xu5rebxprw3s5pyypxu2seztngr/bin/python3.9' 'configure' '--prefix=/home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/petsc-3.17.1-wj7ditzql2ya4eljuzdirblxpimbaium' '--with-ssl=0' '--download-c2html=0' '--download-sowing=0' '--download-hwloc=0' '--with-cc=/home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/openmpi-4.1.3-zre55gzaosgfwzyact5pas4bi72zsiyv/bin/mpicc' '--with-cxx=/home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/openmpi-4.1.3-zre55gzaosgfwzyact5pas4bi72zsiyv/bin/mpic++' '--with-fc=/home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/openmpi-4.1.3-zre55gzaosgfwzyact5pas4bi72zsiyv/bin/mpif90' '--with-precision=double' '--with-scalar-type=real' '--with-shared-libraries=1' '--with-debugging=0' '--with-openmp=0' '--with-64-bit-indices=0' '--with-blas-lapack-lib=/home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/openblas-0.3.20-6jzfpq7elk2t2uoauoelqth355egjhmb/lib/libopenblas.so' '--with-x=0' '--with-clanguage=C' '--with-cuda=0' '--with-hip=0' '--with-metis=1' '--with-metis-include=/home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/metis-5.1.0-rzrhgvam4wcmvx6ufxd5atda6uwg6ynq/include' '--with-metis-lib=/home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/metis-5.1.0-rzrhgvam4wcmvx6ufxd5atda6uwg6ynq/lib/libmetis.so' '--with-hypre=1' '--with-hypre-include=/home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/hypre-2.24.0-arcuualvatqksxs6633nwlph2svyjiql/include' '--with-hypre-lib=/home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/hypre-2.24.0-arcuualvatqksxs6633nwlph2svyjiql/lib/libHYPRE.so' '--with-parmetis=1' '--with-parmetis-include=/home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/parmetis-4.0.3-esnvzcsfnoixhtw4ysj4hy33zcfn6qdz/include' '--with-parmetis-lib=/home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/parmetis-4.0.3-esnvzcsfnoixhtw4ysj4hy33zcfn6qdz/lib/libparmetis.so' '--with-kokkos=0' '--with-kokkos-kernels=0' '--with-superlu_dist=1' '--with-superlu_dist-include=/home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/superlu-dist-7.2.0-vr2woqo6acyeawjvhf233uplol2kdnds/include' '--with-superlu_dist-lib=/home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/superlu-dist-7.2.0-vr2woqo6acyeawjvhf233uplol2kdnds/lib/libsuperlu_dist.so' '--with-ptscotch=0' '--with-suitesparse=0' '--with-hdf5=1' '--with-hdf5-include=/home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/hdf5-1.12.2-a6xroq2vot4wvirv46swa2miizjindmx/include' '--with-hdf5-lib=/home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/hdf5-1.12.2-a6xroq2vot4wvirv46swa2miizjindmx/lib/libhdf5_hl.so /home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/hdf5-1.12.2-a6xroq2vot4wvirv46swa2miizjindmx/lib/libhdf5.so' '--with-zlib=1' '--with-zlib-include=/home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/zlib-1.2.12-dshrvs6e5dwqfh4su7vjsgrk65uzixfo/include' '--with-zlib-lib=/home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/zlib-1.2.12-dshrvs6e5dwqfh4su7vjsgrk65uzixfo/lib/libz.so' '--with-mumps=1' '--with-mumps-include=/home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/mumps-5.4.1-gz2zgkyvgmngwjevb7plo3glw5ih5ezm/include' '--with-mumps-lib=/home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/mumps-5.4.1-gz2zgkyvgmngwjevb7plo3glw5ih5ezm/lib/libsmumps.so /home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/mumps-5.4.1-gz2zgkyvgmngwjevb7plo3glw5ih5ezm/lib/libcmumps.so /home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/mumps-5.4.1-gz2zgkyvgmngwjevb7plo3glw5ih5ezm/lib/libdmumps.so /home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/mumps-5.4.1-gz2zgkyvgmngwjevb7plo3glw5ih5ezm/lib/libzmumps.so /home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/mumps-5.4.1-gz2zgkyvgmngwjevb7plo3glw5ih5ezm/lib/libmumps_common.so /home/wortiz/spack/opt/spack/linux-fedora36-zen3/gcc-12.1.1/mumps-5.4.1-gz2zgkyvgmngwjevb7plo3glw5ih5ezm/lib/libpord.so' '--with-trilinos=0' '--with-fftw=0' '--with-valgrind=0' '--with-gmp=0' '--with-libpng=0' '--with-giflib=0' '--with-mpfr=0' '--with-netcdf=0' '--with-pnetcdf=0' '--with-moab=0' '--with-random123=0' '--with-exodusii=0' '--with-cgns=0' '--with-memkind=0' '--with-p4est=0' '--with-saws=0' '--with-yaml=0' '--with-hwloc=0' '--with-libjpeg=0' '--with-scalapack=0' '--with-strumpack=0' '--with-mmg=0' '--with-parmmg=0' '--with-tetgen=0'
See build log for details:
  /home/wortiz/.cache/spack/stage/spack-stage-petsc-3.17.1-wj7ditzql2ya4eljuzdirblxpimbaium/spack-build-out.txt

</pre></details>

### Information on your system

* **Spack:** 0.18.0.dev0 (2090351d7fa2b3047407da793a4ef80c9a820990)
* **Python:** 3.10.4
* **Platform:** linux-fedora36-zen3
* **Concretizer:** clingo

### Additional information

Notice the `--with-scalapack=0` in the above error message

Reverting #30682 allows install, I'm guessing the scalapack_sp was needed because there are many scalapack providers, this was with `netlib-scalapack` the default for spack on my system

@balay

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by balay** [comment]
@scheibelp @h-murai perhaps https://github.com/spack/spack/pull/30682 needs a revert - and an alternate fix needed for that use case?
