### ISSUE TITLE
Concretizer decides to use mixed compilers

### ISSUE THREAD

**Issue by G-Ragghianti** [LLNL/spack#30730]
### Steps to reproduce

The concretizer appears to be choosing to use an already installed dependency even if it doesn't use the requested compiler.  This breaks the build if the compiler is no longer configured.  In this example, you can see that it is using intel-mkl%gcc@4.8.5 even though the spec requests gcc@10.2.0:

```
-bash-4.2$ spack install intel-mkl %gcc@4.8.5
==> Installing cpio-2.13-rgox5wneab4f6o56x44xlwmyy4wvkhny
==> No binary for cpio-2.13-rgox5wneab4f6o56x44xlwmyy4wvkhny found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/e8/e87470d9c984317f658567c03bfefb6b0c829ff17dbf6b0de48d71a4c8f3db88.tar.gz
==> Ran patch() for cpio
==> cpio: Executing phase: 'autoreconf'
==> cpio: Executing phase: 'configure'
==> cpio: Executing phase: 'build'
==> cpio: Executing phase: 'install'
==> cpio: Successfully installed cpio-2.13-rgox5wneab4f6o56x44xlwmyy4wvkhny
  Fetch: 0.42s.  Build: 1m 5.04s.  Total: 1m 5.46s.
[+] /tmp/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/cpio-2.13-rgox5wneab4f6o56x44xlwmyy4wvkhny
==> Installing intel-mkl-2020.4.304-kthtjqh3pirdmc4ozk3j2jcr42n5npgx
==> No binary for intel-mkl-2020.4.304-kthtjqh3pirdmc4ozk3j2jcr42n5npgx found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/23/2314d46536974dbd08f2a4e4f9e9a155dc7e79e2798c74e7ddfaad00a5917ea5.tgz
==> No patches needed for intel-mkl
==> intel-mkl: Executing phase: 'configure'
==> intel-mkl: Executing phase: 'install'
==> intel-mkl: Successfully installed intel-mkl-2020.4.304-kthtjqh3pirdmc4ozk3j2jcr42n5npgx
  Fetch: 6.74s.  Build: 2m 42.98s.  Total: 2m 49.72s.
[+] /tmp/spack/opt/spack/linux-centos7-haswell/gcc-4.8.5/intel-mkl-2020.4.304-kthtjqh3pirdmc4ozk3j2jcr42n5npgx
-bash-4.2$ spack spec heffte+mkl %gcc@10.2.0
Input spec
--------------------------------
heffte%gcc@10.2.0+mkl

Concretized
--------------------------------
heffte@2.2.0%gcc@10.2.0~cuda~fftw~fortran~ipo~magma+mkl~python~rocm+shared build_type=RelWithDebInfo arch=linux-centos7-haswell
    ^cmake@3.23.1%gcc@10.2.0~doc+ncurses+ownlibs~qt build_type=Release arch=linux-centos7-haswell
        ^ncurses@6.2%gcc@10.2.0~symlinks+termlib abi=none arch=linux-centos7-haswell
            ^pkgconf@1.8.0%gcc@10.2.0 arch=linux-centos7-haswell
        ^openssl@1.1.1o%gcc@10.2.0~docs~shared certs=system arch=linux-centos7-haswell
            ^perl@5.34.1%gcc@10.2.0+cpanm+shared+threads arch=linux-centos7-haswell
                ^berkeley-db@18.1.40%gcc@10.2.0+cxx~docs+stl patches=b231fcc arch=linux-centos7-haswell
                ^bzip2@1.0.8%gcc@10.2.0~debug~pic+shared arch=linux-centos7-haswell
                    ^diffutils@3.8%gcc@10.2.0 arch=linux-centos7-haswell
                        ^libiconv@1.16%gcc@10.2.0 libs=shared,static arch=linux-centos7-haswell
                ^gdbm@1.19%gcc@10.2.0 arch=linux-centos7-haswell
                    ^readline@8.1%gcc@10.2.0 arch=linux-centos7-haswell
                ^zlib@1.2.12%gcc@10.2.0+optimize+pic+shared patches=0d38234 arch=linux-centos7-haswell
    ^intel-mkl@2020.4.304%gcc@4.8.5~ilp64+shared threads=none arch=linux-centos7-haswell
        ^cpio@2.13%gcc@4.8.5 arch=linux-centos7-haswell
    ^openmpi@4.1.3%gcc@10.2.0~atomics~cuda~cxx~cxx_exceptions~gpfs~internal-hwloc~java~legacylaunchers~lustre~memchecker~pmi+pmix+romio+rsh~singularity+static+vt+wrapper-rpath fabrics=none schedulers=none arch=linux-centos7-haswell
        ^hwloc@2.7.1%gcc@10.2.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~opencl+pci~rocm+shared arch=linux-centos7-haswell
            ^libpciaccess@0.16%gcc@10.2.0 arch=linux-centos7-haswell
                ^libtool@2.4.7%gcc@10.2.0 arch=linux-centos7-haswell
                    ^m4@1.4.19%gcc@10.2.0+sigsegv patches=9dc5fbd,bfdffa7 arch=linux-centos7-haswell
                        ^libsigsegv@2.13%gcc@10.2.0 arch=linux-centos7-haswell
                ^util-macros@1.19.3%gcc@10.2.0 arch=linux-centos7-haswell
            ^libxml2@2.9.13%gcc@10.2.0~python arch=linux-centos7-haswell
                ^xz@5.2.5%gcc@10.2.0~pic libs=shared,static arch=linux-centos7-haswell
        ^libevent@2.1.12%gcc@10.2.0+openssl arch=linux-centos7-haswell
        ^numactl@2.0.14%gcc@10.2.0 patches=4e1d78c,62fc8a8,ff37630 arch=linux-centos7-haswell
            ^autoconf@2.69%gcc@10.2.0 patches=35c4492,7793209,a49dd5b arch=linux-centos7-haswell
            ^automake@1.16.5%gcc@10.2.0 arch=linux-centos7-haswell
        ^openssh@9.0p1%gcc@10.2.0 arch=linux-centos7-haswell
            ^libedit@3.1-20210216%gcc@10.2.0 arch=linux-centos7-haswell
        ^pmix@4.1.2%gcc@10.2.0~docs+pmi_backwards_compatibility~restful arch=linux-centos7-haswell
-bash-4.2$ spack compiler remove gcc@4.8.5
==> Removed compiler gcc@4.8.5
-bash-4.2$ spack install heffte+mkl %gcc@10.2.0
[+] /nfs/apps/spacks/2022-02-10/opt/spack/linux-centos7-x86_64/gcc-7.3.0/cmake-3.22.2-rdvpr5odvqzoanneyoq5u4qqufsnfof4 (external cmake-3.22.2-dcehhdjcnc6wt5vpbz4cigf76dxkfxgd)
[+] /nfs/apps/spacks/2022-02-10/opt/spack/linux-centos7-x86_64/gcc-7.3.0/openmpi-4.1.2-lojacwf3pr6xfzbybsvliwob7tlfcnau (external openmpi-4.1.2-cmrzf4pkmeltqda753iiwbgiqfpryuec)
```

### Error message

```
==> Error: Detected uninstalled dependencies for cpio-2.13-rgox5wneab4f6o56x44xlwmyy4wvkhny: {'gcc-4.8.5-vs4zlcqjexwdjai4psmenz4f4nqgjjbi'}
==> Error: Cannot proceed with cpio-2.13-rgox5wneab4f6o56x44xlwmyy4wvkhny: 1 uninstalled dependency: gcc-4.8.5-vs4zlcqjexwdjai4psmenz4f4nqgjjbi
```

### Information on your system

* **Spack:** 0.18.0.dev0
* **Python:** 3.6.8
* **Platform:** linux-centos7-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by G-Ragghianti** [comment]
@alalazo Do you know if this is expected behavior?

**Comment by tgamblin** [comment]
@trws can you take a look at this one?

**Comment by trws** [comment]
Yes, I'll definitely look at this.  This is probably desired behavior from the concretizer, I'm immediately perplexed by the error though, it's asking for a gcc-4.9.4 dependency after building with 4.8.5? For that matter, why does it depend on either, need to dig into why that dependency would cause a failure in the first place since it doesn't appear as a build dependency of a package to be built.

@G-Ragghianti, is the example you gave exactly as it was run, or was the cpio originally built with 4.9.4 at some point?

**Comment by G-Ragghianti** [comment]
I tested this with a number of different OS's so I got the default compilers mixed in this case. In this case, intel-mkl and dependency cpio was built with gcc-4.8.5, but the gcc-4.8.5 compiler was removed from the spack configuration. I accidentally took the error message from a separate test.  I'll correct that now.

**Comment by G-Ragghianti** [comment]
OK I improved the report and included where I removed the gcc@4.8.5 compiler.

My expectation is that when I give a compiler in the spec that it use that compiler for all the dependencies.  To work around this problem, I would have to remove the previously install intel-mkl and cpio or include `^intel-mkl%gcc@10.3.0` explicitly in the spec.

**Comment by trws** [comment]
Right, it should definitely build every dependency *that is built in the current command* with the specified compiler.  We might want to be able to say "force this for the entire graph" somehow, though I think the only way to do that right now is to combine the spec with `--fresh`.  What I meant though was that the gcc 4.8.5 spec shouldn't be a dependency of any build in the current install, it's not being used for anything being built.  Looking into why it is still being required now.

**Comment by trws** [comment]
Bit more information, I managed to repro the problem with the exact same situation.  If I tweak it to be just cpio that's built with the old compiler, then spack decides to build a new copy of cpio instead. I'm getting the impression this is a difference between build and link dependency handling.  It seems off both in that cpio should be reused, and that the error shouldn't happen.

**Comment by trws** [comment]
Ok, need to figure out more information here.  @G-Ragghianti, I managed to repro the spec, but removing the compiler from spack's list with spack compiler remove did not cause a failure.  Was the gcc you were using installed with spack, or specified as an external package or similar?

**Comment by G-Ragghianti** [comment]
The compiler gcc@4.8.5 was a system-installed compiler that is default on RHEL7.  It wasn't installed with spack.  It is weird that it seems to be treating it like a dependency since compilers aren't dependencies in spack as far as I understand (it even has a hash??).  If it would be helpful, I can provide a DockerFile that will reproduce this easily.

**Comment by trws** [comment]
That would be extremely helpful.  There's a plan to make compilers dependencies, but they currently are not, so this is both something we should fix and a good way to iron out a potential pitfall before we get there.

**Comment by alalazo** [comment]
> We might want to be able to say "force this for the entire graph" somehow, though I think the only way to do that right now is to combine the spec with --fresh.

I think that might be relatively easy to obtain as a config option. We could for instance do something similar to:
```
:- 1 { compiler_mismatch(Package, Dependency) : depends_on(Package, Dependency) }, single_compiler_for_dag().
```
and emit `single_compiler_for_dag()` if some config option is true.

**Comment by G-Ragghianti** [comment]
Here is a simple example reproduction for centos:7.  I'm working on some other OS versions.

```
FROM centos:7

ARG gcc1=gcc@4.8.5
ARG gcc2=gcc@7.3.1

RUN yum -y install mpich gcc cmake git
RUN yum -y group install development
RUN git clone https://github.com/spack/spack
RUN yum -y install centos-release-scl && yum -y install devtoolset-7
RUN echo '. spack/share/spack/setup-env.sh;spack compiler find' | scl enable devtoolset-7 bash
RUN source spack/share/spack/setup-env.sh \
    && spack external find mpich cmake \
    && spack install intel-mkl%$gcc1 \
    && spack compiler remove $gcc1 \
    && spack spec heffte+mkl %$gcc2 \
    && spack install heffte+mkl %$gcc2
```

**Comment by trws** [comment]
Thanks for that, it let me repro it, and I'm pretty sure I know what the cause is, but have to consider how to fix it without regressions elsewhere.  It looks like the installer assumes that if `compilers_for_spec(compiler_spec)` doesn't give out a compiler, then *it must already be in the build queue*.  Looks like this is to work around issues with bootstrapped compilers, maybe @becker33 can comment? Conditional [here](https://github.com/spack/spack/blob/557845cccc0523c34072dbeddf6035f54fb2a76e/lib/spack/spack/installer.py#L2126).

The result is that everything that doesn't depend on cpio builds without error, then the root fails when it tries to find a spec in the build queue that doesn't exist.  My first thought is to add a check for whether the compiler is actually in the queue there, but I'm not sure if that will cause additional fallout.

**Comment by RemiLacroix-IDRIS** [comment]
Any news about this? I'm pretty sure I have seen the concretizer mixing compilers too.

**Comment by G-Ragghianti** [comment]
I believe that this issue is currently half fixed.  The most recent develop branch does not result in a fatal error because spack will now not try to use packages that were built with a compiler that is not available (removed from compilers.yaml).  However, the issue of the concretizer mixing packages from different compilers is still remaining.  This is a problem because we are trying to vet software builds for specific compilers, and the concretizer's use of existing packages from other compilers is causing our tests to be invalid and (worse) is causing failures in some cases.  This is particularly frustrating because there is no good way to prevent this behavior (other than to avoid use of multiple compilers within a given spack tree).

I'm working on a second Dockerfile that will show this behavior.

**Comment by trws** [comment]
That behavior should be prevented by always using the --fresh​ option, or the corresponding config setting, since the concretizer will prefer same-compiler builds in that mode.  Are you seeing something different?
________________________________

**Comment by G-Ragghianti** [comment]
The new --fresh option does appear to encourage same-compiler builds, but I question whether this is a good name for the option.  I certainly didn't think it was relevant when I had this problem.  The description or `--fresh` doesn't really seem to correspond with what it actually does since it doesn't appear to rebuild any of the dependencies if they already are installed.

```-U, --fresh           do not reuse installed deps; build newest configuration```

Also the previous behavior was to not reuse, so the defaults seem to have been swapped (i.e. --reuse is on by default and --fresh is off). is this change an intentional decision?

**Comment by trws** [comment]
The name isn't great, but the change was intentional to reduce the amount of duplicate builds of things.  With `--fresh`, spack builds the most recent best-fit version of every dependency, so if python releases a new minor version, and you install something with `--fresh`, you'll build a new python and everything that depends on it even if one is already installed.  It does not rebuild identical packages, but it will build any dependency that has a "better" version available, where better might be more similar compiler, OS, version, basically anything.

**Comment by haampie** [comment]
Notice that

```yaml
packages:
  all:
    require: "%clang"
```

is possible since Spack `0.19.0.dev0`. It gives you the best of both worlds: single compiler for everything & reuse of already installed packages.

Regarding compiler mixing, I think it would make sense if Spack was more strict. I've had issues with Fortran modules due to incompatible compilers. I can only assume that the same issue will happen in the future with C++ modules if they get adopted more broadly.

**Comment by trws** [comment]
> Regarding compiler reuse, I think it would make sense if Spack was more strict. I've had issues with Fortran modules. I can only assume that the same issue will happen in the future with C++ modules if they get adopted more broadly.

This is why we need compilers as dependencies.  For most C compiler situations reuse across compilers is no problem at all, but for fortran modules it's always fatal.  Library issues abound as well, but all we can do right now is try to cover the common case.

**Comment by G-Ragghianti** [comment]
Thank you.
