### ISSUE TITLE
Spack fails when it can't find patches from upstreamed packages that are dependencies

### ISSUE THREAD

**Issue by Paul-Ferrell** [LLNL/spack#30759]
### Steps to reproduce

You'll need two spacks, an upstream and base spack. For the upstream, I checked out `tag/v0.17.2`. For the base, I used the latest `develop`.

On the upstream Spack
```console
$ spack install libtheora
```

On the base Spack add the upstream Spack as an upstream in etc/spack/upstreams.yaml
```console
$ spack env create foo
$ spack env activate foo
$ spack add vtk
$ spack concretize -f
```

So what seems to be going on here is that Spack is trying to do stuff with the upstreamed packages patches, but one of those has an incorrect hash in the package file. In fact the libtheora patch pulled from the web still has an incorrect (and different) hash, even in latest develop.

### Error message

```console
$ spack concretize -f
==> Starting concretization
==> Error: Couldn't find patch for package builtin.libtheora with sha256: 2e4f891f6880386d9391f3e4eaf4a23493de4eea532f9b5cb8a04b5f7cd09301
```

### Information on your system

* **Spack:** 0.18.0.dev0 (55f4950ed4bf3aa6cc40fe0d296f99cf2df17903)
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by Paul-Ferrell** [comment]
I also ran into issues while creating the reproducer (Spack was looking for a libllvm package, but one didn't exist).  Clearing my ~/.spack directory fixed that though. It was still concerning though, as it looked like Spack was checking the existence of packages it wasn't even using in concretization.

**Comment by Paul-Ferrell** [comment]
Also note that trying to upstream `libtheora` by itself isn't enough. It has to be a dependency of something else.

**Comment by adamjstewart** [comment]
May be related to #30557

**Comment by Paul-Ferrell** [comment]
It works for me now too, mostly. There's a separate libtheora package.py problem that needs to be dealt with though.
