### ISSUE TITLE
Reuse reuses spec without required variants

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#30804]
### Steps to reproduce

I've added a variant `y` to a package `x`, and concretization of `x +y` reuses an `x` that does not have the `y` variant.

**Comment by alalazo** [comment]
Cannot reproduce on:

* **Spack:** 0.21.0.dev0 (886946395d33356e2073f4f2112514c366871958)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

![Screenshot from 2023-07-19 14-02-38](https://github.com/spack/spack/assets/4199709/03d33b7d-a55d-4221-b774-8e9b6a00af16)
