### ISSUE TITLE
Installation issue: py-sphinx

### ISSUE THREAD

**Issue by quellyn** [LLNL/spack#30868]
### Steps to reproduce the issue

The `py-sphinx` package has a dependency on `py-alabaster`, expressed in its recipe as:
```console
    depends_on('py-alabaster@0.7', type=('build', 'run'))
```

Notice the lack of colon (':') following the version. It seems to imply that only `0.7` will do, but presumably the intent here is to require `py-alabaster` version `0.7` *or higher* (indeed, there is no `0.7` version available in the `py-alabaster` recipe).

I tested this, and the new `clingo` concretizer seems to make an intelligent guess, picking the current preferred version of `py-alabaster` :
```console
$ spack spec py-sphinx%gcc@9.4.0
```
```console
Input spec
--------------------------------
py-sphinx%gcc@9.4.0

Concretized
--------------------------------
py-sphinx@4.4.0%gcc@9.4.0 arch=linux-rhel8-skylake_avx512
    ^py-alabaster@0.7.12%gcc@9.4.0 arch=linux-rhel8-skylake_avx512
        ^py-pip@21.3.1%gcc@9.4.0 arch=linux-rhel8-skylake_avx512
...
```

But the original concretizer has trouble:
```console
==> Warning: the original concretizer is currently being used.
	Upgrade to "clingo" at your earliest convenience. The original concretizer will be removed from Spack in a future version.
==> Warning: Missing a source id for py-alabaster@0.7
Input spec
--------------------------------
py-sphinx%gcc@9.4.0

Concretized
--------------------------------
py-sphinx@4.4.0%gcc@9.4.0 arch=linux-rhel8-skylake_avx512
    ^py-alabaster@0.7%gcc@9.4.0 arch=linux-rhel8-skylake_avx512
        ^py-pip@21.3.1%gcc@9.4.0 arch=linux-rhel8-skylake_avx512
...
```

I can get around this issue by changing the `py-sphinx` recipe to accept `py-alabaster` version `0.7` *or higher*:
```console
    depends_on('py-alabaster@0.7:', type=('build', 'run'))
```

I know the original concretizer is being deprecated, but should the `py-sphinx` recipe be corrected anyway? It seems to be relying on the good graces of `clingo` right now.

Mentioning @adamjstewart, since I don't see  an official maintainer for `py-sphinx` at the moment.

### Error message

<details><summary>Error message</summary><pre>
==> Warning: Missing a source id for py-alabaster@0.7
</pre></details>

### Information on your system

```console
$ spack debug report
* **Spack:** 0.18.0.dev0 (1b955e66c12a910ac15c650fca5438400da9e290)
* **Python:** 3.6.8
* **Platform:** linux-rhel8-skylake_avx512
* **Concretizer:** clingo
```

Note: 

### Additional information

No build log and environment files obtained.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Sphinx's `setup.py` contains:
```python
    'alabaster>=0.7,<0.8',                                                               
```
which in modern Spack is equivalent to `@0.7`. As you've discovered, this only works with the new clingo concretizer. For the original concretizer, this would look something like `@0.7.0:0.7`, which is a bit more cumbersome. If you need to use the original concretizer, you can change it back to the old format, but there are hundreds of packages in Spack that use the new format, not just Sphinx. Is there any reason you can't use the new clingo concretizer?

**Comment by quellyn** [comment]
> If you need to use the original concretizer, you can change it back to the old format, but there are hundreds of packages in > Spack that use the new format, not just Sphinx. Is there any reason you can't use the new clingo concretizer?

We are using the new concretizer now, but due to programmatic requirements we must maintain some older Spack environments that use the old concretizer. It's good to be aware of this change, thanks!
