### ISSUE TITLE
Installation issue: Lua (Luarocks)

### ISSUE THREAD

**Issue by vanderwb** [LLNL/spack#30943]
### Steps to reproduce the issue

```console
$ spack spec -I lua
Input spec
--------------------------------
 -   lua

Concretized
--------------------------------
 -   lua@5.3.5%gcc@7.5.0~pcfile+shared fetcher=curl arch=linux-sles15-broadwell
 -       ^curl@7.83.0%gcc@7.5.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2~nghttp2 libs=shared,static tls=openssl arch=linux-sles15-broadwell
 -           ^openssl@1.1.1o%gcc@7.5.0~docs~shared certs=system arch=linux-sles15-broadwell
 -               ^perl@5.34.1%gcc@7.5.0+cpanm+shared+threads arch=linux-sles15-broadwell
 -                   ^berkeley-db@18.1.40%gcc@7.5.0+cxx~docs+stl patches=b231fcc arch=linux-sles15-broadwell
 -                   ^bzip2@1.0.8%gcc@7.5.0~debug~pic+shared arch=linux-sles15-broadwell
 -                       ^diffutils@3.8%gcc@7.5.0 arch=linux-sles15-broadwell
 -                           ^libiconv@1.16%gcc@7.5.0 libs=shared,static arch=linux-sles15-broadwell
 -                   ^gdbm@1.19%gcc@7.5.0 arch=linux-sles15-broadwell
 -                       ^readline@8.1%gcc@7.5.0 arch=linux-sles15-broadwell
 -                           ^ncurses@6.2%gcc@7.5.0~symlinks+termlib abi=none arch=linux-sles15-broadwell
 -                               ^pkgconf@1.8.0%gcc@7.5.0 arch=linux-sles15-broadwell
 -                   ^zlib@1.2.12%gcc@7.5.0+optimize+pic+shared patches=0d38234 arch=linux-sles15-broadwell
 -       ^unzip@6.0%gcc@7.5.0 arch=linux-sles15-broadwell
```

### Error message

<details><summary>Error message</summary><pre>
...
==> Installing lua-5.3.5-62dd2cexvmyo2zix534pu7l3sseh4rp6
==> No binary for lua-5.3.5-62dd2cexvmyo2zix534pu7l3sseh4rp6 found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/0c/0c2eed3f960446e1a3e4b9a1ca2f3ff893b6ce41942cf54d5dd59ab4b3b058ac.tar.gz
==> Fetching https://mirror.spack.io/_source-cache/archive/56/56ab9b90f5acbc42eb7a94cf482e6c058a63e8a1effdf572b8b2a6323a06d923.tar.gz
==> Moving resource stage
    source: /glade/scratch/vanderwb/temp/spack-stage/resource-luarocks-62dd2cexvmyo2zix534pu7l3sseh4rp6/spack-src/
    destination: /glade/scratch/vanderwb/temp/spack-stage/spack-stage-lua-5.3.5-62dd2cexvmyo2zix534pu7l3sseh4rp6/spack-src/luarocks/luarocks
==> No patches needed for lua
==> lua: Executing phase: 'edit'
==> lua: Executing phase: 'build'
==> lua: Executing phase: 'install'
==> lua: Executing phase: 'add_luarocks'
==> Error: ProcessError: Command exited with status 1:
    './configure' '--prefix=/glade/scratch/vanderwb/experiment/spack-fix/spack/opt/spack/linux-sles15-broadwell/gcc-7.5.0/lua-5.3.5-62dd2cexvmyo2zix534pu7l3sseh4rp6' '--with-lua=/glade/scratch/vanderwb/experiment/spack-fix/spack/opt/spack/linux-sles15-broadwell/gcc-7.5.0/lua-5.3.5-62dd2cexvmyo2zix534pu7l3sseh4rp6'
See build log for details:
  /glade/scratch/vanderwb/temp/spack-stage/spack-stage-lua-5.3.5-62dd2cexvmyo2zix534pu7l3sseh4rp6/spack-build-out.txt
</pre></details>

### Information on your system

* **Spack:** 0.19.0.dev0 (9ddf45964d010744edac8a088a7179b051b93099)
* **Python:** 3.6.15
* **Platform:** linux-sles15-broadwell
* **Concretizer:** clingo

### Additional information

This failure occurs in a container image that does not have `unzip` in the path (standard OS directories). It does not occur on our system bare-metal, so I'm guessing this is an edge case situation but it still shouldn't happen. I did not get this error with Spack v0.17.1, but it has cropped up with v0.18.0.

[spack-build-env.txt](https://github.com/spack/spack/files/8810403/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/8810404/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by upsj** [comment]
+1, the issue also occurs on a fresh WSL2+Ubuntu install

**Comment by white238** [comment]
> +1, the issue also occurs on a fresh WSL2+Ubuntu install

Same .. hit this today.

**Comment by Thomas-Ulrich** [comment]
Well, I suppose this is because 
https://github.com/spack/spack/blob/releases/v0.19/var/spack/repos/builtin/packages/lua/package.py#L56
which has been changed into:
https://github.com/spack/spack/blob/releases/v0.21/var/spack/repos/builtin/packages/lua/package.py#L56
since v0.21
(so you would need to use a more recent spack)

**Comment by alalazo** [comment]
Can you confirm this is solved on latest Spack?

**Comment by Thomas-Ulrich** [comment]
no, but I can point to the PR where the change was applied, and it seems it was for fixing exactly the problem they are facing
https://github.com/spack/spack/pull/39802
