### ISSUE TITLE
Issues with spack bootstrap

### ISSUE THREAD

**Issue by davide-q** [LLNL/spack#30987]
### Steps to reproduce

1. Attemping to do bootstrapping before activating an environment fails

```console
spack bootstrap add --trust local-sources <absolute path>
spacktivate code
```
Causes apparent random failures like the one below. Switching the order seems to be working fine, as far as I can tell.

3. As described in https://github.com/spack/spack/pull/28556

```console
spack bootstrap add --trust local-sources <relative path>
```
does not work. If it simply produced an error message, that would be fine. Instead it appears to work but then subsequent `spack` actions fail. A simple check for the path being relative, rather than absolute, and replacing it with absolute one, printing a warning, should be an easy fix.

### Information on your system

* **Spack:** 0.18.0
* **Python:** 3.6.4
* **Platform:** linux-centos7-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
> Causes apparent random failures like the one below. 

Am I missing anything? I don't see a stacktrace or an error message

**Comment by davide-q** [comment]
Sorry I was out and I missed this notification. The error message for that problem was identical to the one utilizing the  relative rather than absolute paths. The problem is that it did not happen at bootstrap time, but later.
I have troubles reproducing exactly the same issue now mostly because my `~/.spack` directory has changed. For these use cases (testing) it'd be nice to have something that is totally self-contained in the git checkout directory...
