### ISSUE TITLE
Bootstrap fragility, or hardening bootstrap

### ISSUE THREAD

**Issue by trws** [LLNL/spack#31030]
After looking at relying on bootstrap for clingo provider on LC systems and elsewhere, I've run into a number of distinct but tightly related either bugs or lacks in bootstrap that make it a bit tricky to rely on, posting this up as a tracking issue and place to discuss what to do and how to do it so we can rely on this in some less ideal cases.

* Bootstrap python module imports: Currently bootstrapped python modules in bootstrap are loaded from the store by appending the store to the end of the search path (@alalazo, I think this is what's going on with my issue on lassen), so if there's a non-functional module in the search path they're never found (see [here](https://github.com/trws/spack/blob/9716b9eb42e6cc37304322a885f8a63ed2812239/lib/spack/spack/bootstrap.py)).  The fallback is also directly to source, where it might be more helpful to do something like:
  * try import with store paths at the beginning
  * try import with store paths at the end
  * *maybe* try without store paths, this may be handled elsewhere in the code
* Bootstrap warns about untrusted mirror sources *by default*.  Should the default mirror perhaps be trusted by default, or otherwise handled so this isn't the first thing the user sees?
* Bootstrap does not run `spack compiler find` before trying to bootstrap from source, on ancient distros (like RHEL7) the resulting behavior is that gcc4.x is selected, which can't build clingo: probably just add a "compiler add" in there and we'll be good on this one

@davidbeckingsale, did you have any others you've run into? If we can squash the first, and maybe the last, the raja framework use-case should be a lot more resilient but probably best to get it all in here.

**Comment by davidbeckingsale** [comment]
CC @adrienbernede

**Comment by alalazo** [comment]
> Bootstrap warns about untrusted mirror sources by default. Should the default mirror perhaps be trusted by default, or otherwise handled so this isn't the first thing the user sees?

I think we chose the wording poorly when we introduced bootstrapping. Sometimes ago I had a brief conversation with @ax3l on Slack, and was proposing to reword "trust" and "untrust" to "enable" and "disable", since that's what we are effectively doing - enabling or disabling a registered mirror. What do you think?

**Comment by alalazo** [comment]
I know @adrienbernede might have issues I still have to try reproducing with concurrent bootstrapping from multiple Spack instances.

**Comment by adrienbernede** [comment]
@trws thank you for creating that issue. I have run into a confusing set of issues myself and @alalazo helped me clarify things.

For Umpire CI, I had to install clingo on ruby, lassen and corona. Because things appeared unstable (non reproducible behaviors) and because I work for RADIUSS and not only Umpire, I created https://github.com/LLNL/radiuss-clingo-install to automate this install (documentation here: https://radiuss-clingo-install.readthedocs.io/en/latest/index.html.

The first goal was to reliably reproduce the same environment, e.g. cleaning the bootstrap before re-installing.

In the end, with this "tool" I can install clingo for a given spack version on several machines, within the scope of a given service account.

The good news is that it will install from the binary cache, which is fast, and works around the issue of compiler on lassen which I ran into myself.

The bad news is that in practice, in CI context, it happens that spack fails to find clingo and installs again. This install cannot happen concurrently without causing concurrency/locks errors, so when that happens the CI fails (sometimes all except one job, which ends up installing clingo from source).

Incrementally, we had spack installing clingo form source on several machines, and things seem stable for Umpire.

Now, I need to update 'radiuss-clingo-install' with a step to also install clingo from source, untrusting the binary cache temporarily. That way I should have a "belt and braces" install.

**Comment by trws** [comment]
Ok, we should have a chat about this.  I'm relatively certain we could solve the issues in spack bootstrap in less code, and work, than has already been done in radiuss-clingo-install.  Concurrent installations we should be able to fix with locking if that's on NFS, which honestly I thought was already working, or by ensuring each CI job sets a node or job-specific cache path and/or bootstrap path, all of which is already supported in stable spack.  Was it mainly path conflicts you were running into?

As a start I put up #31035, which apparently has some style issues I'll fix shortly but deals with the clingo install in path issue I was having.

A configuration like the one I use for parallel testing should really be a standard for any CI that involves spack, the full usage is here: #29593 

In a script it's basically:

```sh
mkdir -p ${XDG_RUNTIME_DIR:=$(systemd-path user-run)}/spack-tests
export TMP_DIR=$(mktemp -d spack-test-XXXXX -p ${XDG_RUNTIME_DIR}/spack-tests)
export BOOTSTRAP="/tmp/spack-bootstrap"
mkdir -p $BOOTSTRAP
export SPACK_USER_CACHE_PATH=$TMP_DIR/user_cache ### separate caches
mkdir -p $SPACK_USER_CACHE_PATH
ln -s $BOOTSTRAP $SPACK_USER_CACHE_PATH/bootstrap  ### re-use common bootstrap, note that this locking works
export SPACK_SYSTEM_CONFIG_PATH=$TMP_DIR/sys_conf
export SPACK_USER_CONFIG_PATH=$TMP_DIR/user_conf
mkdir -p $SPACK_USER_CONFIG_PATH
# ensure that installs happen in tmp, and that misc and source caches are rooted in the user cache rather than repo
cat > $SPACK_USER_CONFIG_PATH/config.yaml <<EOF
config:
  install_tree:
    root: $TMP_DIR/install
  misc_cache: $$user_cache_path/cache
  source_cache: $$user_cache_path/source
EOF
```

With that, any number of jobs can share a spack dir and not conflict (unless they try, really, really hard).  The manual recommends something like this, but it isn't sufficient for "interesting" cases where the spack directory is shared, should be if the spack directory is separate though:

```sh
export SPACK_DISABLE_LOCAL_CONFIG=true
export SPACK_USER_CACHE_PATH=/tmp/spack
```

@adrienbernede, do you have an example of the bootstrap locks failing? Probably just the filesystem where you saw it would be enough, because that shouldn't be happening.

**Comment by alalazo** [comment]
Mentioning #31042 as a bugfix that went in today, for an otherwise confusing behavior (Spack was using binaries when explicitly told to not do so).

**Comment by adrienbernede** [comment]
@trws, thank you for taking the time for an in-depth suggestion.
I have several comments about it, although I am digressing w.r.t. the issue:
- I was trying to avoid bootstrapping clingo in each job, precisely.
- I am sharing a single allocation (single node) among several jobs, which gives me fast allocation and responsive CI. I am already implementing similar anti-collision feature, and using /dev/shm to speed-up spack usage. See https://github.com/LLNL/Umpire/blob/4855f40f2a79ac7d949d8f648405cc17a4d720d0/scripts/gitlab/build_and_test.sh#L47

I am used to dealing with conflicting spack instances and also avoiding `~/.spack` for config (hence using uberenv), but clingo caused me some troubles.

Suggestions to improve the current implementation are welcome, but I have a working configuration that is fast in production, and I am a bit conservative considering the effort it was to develop it. E.g., I will consider using "spack for developers" features in the near future.

For an example of a failing job with lock issue at clingo install:
`https://lc.llnl.gov/gitlab/radiuss/Umpire/-/jobs/661191`

**Comment by trws** [comment]
That's all fair, the main thing that isn't set by uberenv (as far as I can tell, I haven't used it much but I can't find anything in the repo or the linked script that would deal with it) is the user cache path.  The bootstrap directory is, by default, a subdirectory of the user_cache_path, and that by default is `~/.spack/` *even if the config is elsewhere*.

This is unfortunate, but if either `SPACK_USER_CACHE_PATH` or `SPACK_BOOTSTRAP_PATH` are set to something independent for each concurrent job (no need to do it for *every* job, just make a separate copy for each that's running, then the contention goes away.  Looking at the log, it seems it was doing bootstrap in the default LC home NFS, which should work.  That's a scary bug and I'll try to look into that.

Where possible, separating the bootstrap dirs (even if it's a straight-up `cp` from a common directory to a `/dev/shm` one which is what I do for parallel unit testing spack itself) can work around any and all conflict issues with this stuff.

**Comment by alalazo** [comment]
@trws The first suspect to check, which is on my list but I didn't get to it yet, is the absence of locks if we're using the API from `spack.binary_distribution`. I would expect everything that does an installation to grab a write lock, but at this point I'm not sure that Python module does it.

**Comment by trws** [comment]
There are literally no mentions of locking in that file, other than to set `enable_transaction_locking=False` on the `Database` instance.  That feels deeply suspicious.  Interestingly enough, the failure is in a source install *after it finished installing* in the link @adrienbernede posted above.  This also is with a version of spack that has the lock repair PR from December in it, so if the NFS system is working correctly it shouldn't be possible with just source installs.  Will definitely look into that more, thanks for the pointer @alalazo.

**Comment by adrienbernede** [comment]
@alalazo @trws thank you both for your help on this:

1 - With the use of `user_cache_path` I am able to get things to work will in RAJA.


2 - Then, I still had a weird behavior with Umpire. In Uberenv we run a `spack spec` followed by a `spack install`. Uberenv would fail to bootstrap from binary at first and get installed from source, and then the `spack install` would trigger a bootstrap from binary again, the result of which is unclear.

```
[exe: spack/bin/spack spec --install-status --very-long umpire@develop%gcc@8.3.1]
==> Bootstrapping clingo from pre-built binaries
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.2/build_cache/linux-centos7-ppc64le-gcc-10.2.1-clingo-bootstrap-spack-isu2rjoicl4xzmbl3k2c4bg35gvejkgz.spec.json
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.2/build_cache/linux-centos7-ppc64le/gcc-10.2.1/clingo-bootstrap-spack/linux-centos7-ppc64le-gcc-10.2.1-clingo-bootstrap-spack-isu2rjoicl4xzmbl3k2c4bg35gvejkgz.spack
==> Installing "clingo-bootstrap@spack%gcc@10.2.1~docs~ipo+python+static_libstdcpp build_type=Release arch=linux-centos7-ppc64le" from a buildcache
==> Bootstrapping clingo from sources
[+] /usr (external bison-3.0.4-rkj44ftdyydl7skyuxaccztlgff3eqvz)
[+] /usr/tce/packages/cmake/cmake-3.20.2 (external cmake-3.20.2-c3i3utoa55pmxpqce75rrvmxxkc3gzn4)
[+] /usr/tce/packages/python/python-3.7.2 (external python-3.7-yesjzofoocy7fkvhunubvql6xuucmyjd)
==> Installing gnuconfig-2021-08-14-kyrjh6ji3f5xj7bx2n5kxpvqmq3urdi3
==> No binary for gnuconfig-2021-08-14-kyrjh6ji3f5xj7bx2n5kxpvqmq3urdi3 found: installing from source
==> Warning: Spec clingo-bootstrap@spack%gcc@10.2.1~docs~ipo+python+static_libstdcpp build_type=Release arch=linux-centos7-ppc64le ^python@3.7%gcc@10.2.1+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib arch=linux-centos7-ppc64le did not provide module clingo
==> Warning: Spec clingo-bootstrap@spack%gcc@10.2.1~docs~ipo+python+static_libstdcpp build_type=Release arch=linux-centos7-ppc64le ^python@3.7%gcc@10.2.1+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib arch=linux-centos7-ppc64le did not provide module clingo
==> Fetching https://mirror.spack.io/_source-cache/archive/69/69b6d2868e70167ba1bdb9030b49beeb20f00b37e30825e83fd04291d96bc5f7.tar.gz
==> No patches needed for gnuconfig
==> gnuconfig: Executing phase: 'install'
==> gnuconfig: Successfully installed gnuconfig-2021-08-14-kyrjh6ji3f5xj7bx2n5kxpvqmq3urdi3
  Fetch: 0.15s.  Build: 0.05s.  Total: 0.19s.
[+] /dev/shm/lassen739/690282/spack-user-cache/bootstrap/store/linux-rhel7-ppc64le/gcc-8.3.1/gnuconfig-2021-08-14-kyrjh6ji3f5xj7bx2n5kxpvqmq3urdi3
==> Installing re2c-2.2-dmgysybbfa6p4d7ssgi26zlkr5nmqjca
==> No binary for re2c-2.2-dmgysybbfa6p4d7ssgi26zlkr5nmqjca found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/0f/0fc45e4130a8a555d68e230d1795de0216dfe99096b61b28e67c86dfd7d86bda.tar.xz
==> No patches needed for re2c
==> re2c: Executing phase: 'autoreconf'
==> re2c: Executing phase: 'configure'
==> re2c: Executing phase: 'build'
==> re2c: Executing phase: 'install'
==> re2c: Successfully installed re2c-2.2-dmgysybbfa6p4d7ssgi26zlkr5nmqjca
  Fetch: 0.15s.  Build: 18.37s.  Total: 18.52s.
[+] /dev/shm/lassen739/690282/spack-user-cache/bootstrap/store/linux-rhel7-ppc64le/gcc-8.3.1/re2c-2.2-dmgysybbfa6p4d7ssgi26zlkr5nmqjca
==> Installing clingo-bootstrap-spack-xirkpfw67656gk2jsg6ciqxacpo7syjl
==> No binary for clingo-bootstrap-spack-xirkpfw67656gk2jsg6ciqxacpo7syjl found: installing from source
==> Ran patch() for clingo-bootstrap
==> clingo-bootstrap: Executing phase: 'cmake'
==> clingo-bootstrap: Executing phase: 'build'
==> clingo-bootstrap: Executing phase: 'install'
==> clingo-bootstrap: Successfully installed clingo-bootstrap-spack-xirkpfw67656gk2jsg6ciqxacpo7syjl
  Fetch: 5.62s.  Build: 50.21s.  Total: 55.82s.
[+] /dev/shm/lassen739/690282/spack-user-cache/bootstrap/store/linux-rhel7-ppc64le/gcc-8.3.1/clingo-bootstrap-spack-xirkpfw67656gk2jsg6ciqxacpo7syjl
==> Warning: Spec clingo-bootstrap@spack%gcc@8.3.1~docs~ipo+python~static_libstdcpp build_type=Release arch=linux-rhel7-ppc64le ^bison@3.0.4%gcc@8.3.1 patches=b72914f arch=linux-rhel7-ppc64le ^cmake@3.20.2%gcc@8.3.1~doc+ncurses+ownlibs~qt build_type=Release arch=linux-rhel7-ppc64le ^gnuconfig@2021-08-14%gcc@8.3.1 arch=linux-rhel7-ppc64le ^python@3.7%gcc@8.3.1+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib arch=linux-rhel7-ppc64le ^re2c@2.2%gcc@8.3.1 arch=linux-rhel7-ppc64le did not provide module clingo
==> Error: cannot bootstrap the "clingo" Python module from spec "clingo-bootstrap@spack+python %gcc target=ppc64le" due to the following failures:
github-actions-v0.1 raised ValueError: source is not trusted
Run `spack --debug ...` for more detailed errors
[exe: spack/bin/spack dev-build --quiet -d /usr/WS2/umdev/gitlab-runner/umdev/builds/zkQzXxmM/010/gitlab/bernede1/umpire-no-mirror -u initconfig umpire@develop%gcc@8.3.1]
==> Bootstrapping clingo from pre-built binaries
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.2/build_cache/linux-centos7-ppc64le-gcc-10.2.1-clingo-bootstrap-spack-isu2rjoicl4xzmbl3k2c4bg35gvejkgz.spec.json
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.2/build_cache/linux-centos7-ppc64le/gcc-10.2.1/clingo-bootstrap-spack/linux-centos7-ppc64le-gcc-10.2.1-clingo-bootstrap-spack-isu2rjoicl4xzmbl3k2c4bg35gvejkgz.spack
==> Installing "clingo-bootstrap@spack%gcc@10.2.1~docs~ipo+python+static_libstdcpp build_type=Release arch=linux-centos7-ppc64le" from a buildcache
[+] /usr/tce/packages/cmake/cmake-3.20.2 (external cmake-3.20.2-c3i3utoa55pmxpqce75rrvmxxkc3gzn4)
==> Installing blt-0.5.1-zydow3wjlmxq5qna5o6cxoh7aqlnivly
==> No binary for blt-0.5.1-zydow3wjlmxq5qna5o6cxoh7aqlnivly found: installing from source
==> Warning: Spec clingo-bootstrap@spack%gcc@8.3.1~docs~ipo+python~static_libstdcpp build_type=Release arch=linux-rhel7-ppc64le ^bison@3.0.4%gcc@8.3.1 patches=b72914f arch=linux-rhel7-ppc64le ^cmake@3.20.2%gcc@8.3.1~doc+ncurses+ownlibs~qt build_type=Release arch=linux-rhel7-ppc64le ^gnuconfig@2021-08-14%gcc@8.3.1 arch=linux-rhel7-ppc64le ^python@3.7%gcc@8.3.1+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib arch=linux-rhel7-ppc64le ^re2c@2.2%gcc@8.3.1 arch=linux-rhel7-ppc64le did not provide module clingo
==> Warning: Spec clingo-bootstrap@spack%gcc@10.2.1~docs~ipo+python+static_libstdcpp build_type=Release arch=linux-centos7-ppc64le ^python@3.7%gcc@10.2.1+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib arch=linux-centos7-ppc64le did not provide module clingo
```

The good news is that updating to spack@develop, things go well for Umpire too !

While I cannot explain the difference between RAJA and Umpire. But things are good for me now. (except for https://github.com/spack/spack/issues/31214).

Thank again.

**Comment by adrienbernede** [comment]
I am closing this as the initial issue was fixed.

**Comment by adrienbernede** [comment]
I am closing this as the initial issue was fixed.

**Comment by adrienbernede** [comment]
@trws how about closing this ?

**Comment by adrienbernede** [comment]
You said you would be investigating this and I reported a weird related behavior, but the initial issue was fixed from my perspective using `user_cache_path`.

**Comment by trws** [comment]
I'll close this and open a separate one for the locking if it comes back up.
