### ISSUE TITLE
spack environment fails to set LD_LIBRARY_PATH, but only when LD_LIBRARY_PATH isn't set

### ISSUE THREAD

**Issue by jrwrigh** [LLNL/spack#31051]
### Steps to reproduce

```console
foo@bar~$ echo $LD_LIBRARY_PATH
[Nothing]
foo@bar~$ spacktivate envA
foo@bar~$ echo $LD_LIBRARY_PATH
[Nothing]
foo@bar~$ spacktivate envB
foo@bar~$ echo $LD_LIBRARY_PATH
[paths to 'lib' directories in environment view]
```

Note this is also consistent when starting with `envB` and then switching to `envA`. However, if I activate an environment with `LD_LIBRARY_PATH` set to something:
```console
foo@bar~$ echo $LD_LIBRARY_PATH
/home/foo
foo@bar~$ spacktivate envA
foo@bar~$ echo $LD_LIBRARY_PATH
spack/lib/paths:/home/foo
```

I have a different environment (call it `envC`) where `LD_LIBRARY_PATH` is set on environment startup normally:
```console
foo@bar~$ echo $LD_LIBRARY_PATH
[Nothing]
foo@bar~$ spacktivate envC
foo@bar~$ echo $LD_LIBRARY_PATH
spack/lib/paths
```

The only similarity between `envA` and `envB` that I can think of is that they both have a development package on them.

### Error message

The only difference between the first `spacktivate` and the second one is the following line:
```console
==> [2022-06-08-11:29:59.708123] Reversing `Set` environment operation may lose original value
==> [2022-06-08-11:29:59.934879] Warning: Skipping reversal of unreversable operation<class 'spack.util.environment.UnsetEnv'> PETSC_ARCH
==> [2022-06-08-11:29:59.934928] Reversing `Set` environment operation may lose original value
```

### Information on your system

```console
❯ spack debug report
* **Spack:** 0.18.0 (c09bf37ff690c29779a342670cf8a171ad1b9233)
* **Python:** 3.10.4
* **Platform:** linux-manjaro21-icelake
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by jrwrigh** [comment]
The same behavior is observed for the `$C_INCLUDE_PATH`.

**Comment by jbigot** [comment]
If this can help, I can provide a docker image where the issue appears

**Comment by jrwrigh** [comment]
Note that spack no longer sets`$LD_LIBRARY_PATH` as of #28354. 

Under that guise, I'll close the issue, but let me know if I should reopen it.
