### ISSUE TITLE
hdf5 1.8.22 parallel Fortran interface is broken with CMake

### ISSUE THREAD

**Issue by pab42** [LLNL/spack#31085]
### Steps to reproduce

I install hdf5 1.8.22 with
```
bin/spack install  hdf5@1.8.22%gcc+mpi+szip+fortran+cxx+hl ^openmpi schedulers=slurm +pmi +thread_multiple +legacylaunchers fabrics=ucx ^ucx+mlx5_dv
```
and then loaded openmpi
```
bin/spack module tcl refresh -y
module use -p share/spack/modules/linux-sles15-haswell/ 
module load openmpi-1.10.7-gcc-11.2.0-5p475pq
```
and tried to compile the hdf5 fortran example [ph5example.f90](https://raw.githubusercontent.com/HDFGroup/hdf5/develop/fortran/examples/ph5example.f90
)
via
```
mpifort ph5example.f90 -Iopt/spack/linux-sles15-haswell/gcc-11.2.0/hdf5-1.8.22-eqz3y6v6ibvvirocnnphhq6aa63czcwd/include -Lopt/spack/linux-sles15-haswell/gcc-11.2.0/hdf5-1.8.22-eqz3y6v6ibvvirocnnphhq6aa63czcwd/lib -lhdf5_fortran -lhdf5
```

### Error message

```
/usr/bin/ld: /tmp/ccV3VZVL.o: in function `MAIN__':
ph5example.f90:(.text+0x33c): undefined reference to `h5pset_fapl_mpio_f_'
/usr/bin/ld: ph5example.f90:(.text+0x6ae): undefined reference to `h5pset_dxpl_mpio_f_'
collect2: error: ld returned 1 exit status
```

If I use the old package.py with the autotools, it builds and compiles correctly. I also built hdf5 by hand with cmake and there the symbol is also missing. I also checked with intel-mpi/intel-compilers, no difference. For newer versions of hdf5 this problem does not exist.

### Information on your system

* **Spack:** 0.19.0.dev0 (cfc46504ac64049df98e5876396a59ccf3deebf9)
* **Python:** 3.6.12
* **Platform:** linux-sles15-haswell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by sethrj** [comment]
@pab42 Can you post the `opt/spack/linux-sles15-haswell/gcc-11.2.0/hdf5-1.8.22-eqz3y6v6ibvvirocnnphhq6aa63czcwd/.spack/spack-build-01-cmake-out.txt` file?

**Comment by pab42** [comment]
[spack-build-01-cmake-out.txt](https://github.com/spack/spack/files/8888480/spack-build-01-cmake-out.txt)

**Comment by sethrj** [comment]
@pab42 It does look like spack is installing HDF5 correctly.

>  I also built hdf5 by hand with cmake and there the symbol is also missing. I also checked with intel-mpi/intel-compilers, no difference. For newer versions of hdf5 this problem does not exist.

From the description and the CMake output, I'm guessing that the HDF5 1.8 branch just has an error in its cmake logic. We can add a "conflict" denoting that this version is broken, but you should probably [open an issue on the HDF5 page](https://github.com/HDFGroup/hdf5/issues/new/choose). As a workaround, you could compile a newer version of HDF5 but select the 1.8 API.

**Comment by pab42** [comment]
Thanks for looking into it and for the suggestions. I opened an issue.
