### ISSUE TITLE
Style checks are currently broken on develop

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#31109]
### Steps to reproduce

Errors like [this one](https://github.com/spack/spack/runs/6863122909?check_suite_focus=true) started in our CI workflows a few hours ago. I could reproduce the same error on my laptop, starting from a clean environment:
```console
$ spack clean -ab
$ spack style
```

### Error message

```console
==> Installing py-setuptools-62.4.0-45naueauwpjyndinwns2vmuslvtpfjgv
==> No binary for py-setuptools-62.4.0-45naueauwpjyndinwns2vmuslvtpfjgv found: installing from source
==> Fetching https://pypi.io/packages/source/s/setuptools/setuptools-62.4.0.tar.gz
==> No patches needed for py-setuptools
==> py-setuptools: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    '/tmp/py38/bin/python3' '-m' 'pip' '-vvv' '--no-input' '--no-cache-dir' '--disable-pip-version-check' 'install' '--no-deps' '--ignore-installed' '--no-build-isolation' '--no-warn-script-location' '--no-index' '--prefix=/home/culpo/.spack/bootstrap/store/linux-ubuntu20.04-x86_64/gcc-9.4.0/py-setuptools-62.4.0-45naueauwpjyndinwns2vmuslvtpfjgv' '.'

1 warning found in build log:
     40        File "/tmp/culpo/spack-stage/spack-stage-py-setuptools-62.4.0-45naueauwpjyndinwns2vmuslvtpfjgv/spack-src/setuptools/dist.py", line 899, in <la
           mbda>
     41          loaded = map(lambda e: e.load(), filtered)
     42        File "/tmp/culpo/spack-stage/spack-stage-py-setuptools-62.4.0-45naueauwpjyndinwns2vmuslvtpfjgv/spack-src/setuptools/_vendor/importlib_metadata
           /__init__.py", line 196, in load
     43          return functools.reduce(getattr, attrs, module)
     44      AttributeError: type object 'Distribution' has no attribute '_finalize_feature_opts'
     45      Preparing metadata (pyproject.toml): finished with status 'error'
  >> 46    WARNING: Discarding file:///tmp/culpo/spack-stage/spack-stage-py-setuptools-62.4.0-45naueauwpjyndinwns2vmuslvtpfjgv/spack-src. Command errored out
            with exit status 1: /tmp/py38/bin/python3 /home/culpo/.spack/bootstrap/store/linux-ubuntu20.04-x86_64/gcc-9.4.0/py-pip-21.3.1-gn6einteae67vuyoqdn
           gv2gkfbr45nvy/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpzn43avit Check the
            logs for full command output.
     47    ERROR: Command errored out with exit status 1: /tmp/py38/bin/python3 /home/culpo/.spack/bootstrap/store/linux-ubuntu20.04-x86_64/gcc-9.4.0/py-pip-
           21.3.1-gn6einteae67vuyoqdngv2gkfbr45nvy/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel 
           /tmp/tmpzn43avit Check the logs for full command output.
     48    Exception information:
     49    Traceback (most recent call last):
     50      File "/home/culpo/.spack/bootstrap/store/linux-ubuntu20.04-x86_64/gcc-9.4.0/py-pip-21.3.1-gn6einteae67vuyoqdngv2gkfbr45nvy/lib/python3.8/site-pa
           ckages/pip/_internal/cli/base_command.py", line 164, in exc_logging_wrapper
     51        status = run_func(*args)
     52      File "/home/culpo/.spack/bootstrap/store/linux-ubuntu20.04-x86_64/gcc-9.4.0/py-pip-21.3.1-gn6einteae67vuyoqdngv2gkfbr45nvy/lib/python3.8/site-pa
           ckages/pip/_internal/cli/req_command.py", line 205, in wrapper

See build log for details:
  /tmp/culpo/spack-stage/spack-stage-py-setuptools-62.4.0-45naueauwpjyndinwns2vmuslvtpfjgv/spack-build-out.txt
```

### Information on your system

* **Spack:** 0.19.0.dev0 (14ae0e0d94d7c78e202a50f351ba56dc83c63f18)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

Similar reports in other repositories: 
- https://github.com/pypa/setuptools/issues/3118
- https://github.com/pypa/setuptools/issues/3113

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
The error seems to be a weird bootstrapping interaction for `setuptools`, between the version to be installed and the one on the system. In my local environment installing `setuptools` calls:
```
'/tmp/py38/bin/python3' '-m' 'pip' '-vvv' '--no-input' '--no-cache-dir' '--disable-pip-version-check' 'install' '--no-deps' '--ignore-installed' '--no-build-isolation' '--no-warn-script-location' '--no-index' '--prefix=/home/culpo/.spack/bootstrap/store/linux-ubuntu20.04-x86_64/gcc-9.4.0/py-setuptools-62.4.0-45naueauwpjyndinwns2vmuslvtpfjgv' '.'
```
and fails when the local setuptools is too old. This is because on my system:
```console
$ pip list
Package       Version
------------- -------
attrs         21.4.0 
iniconfig     1.1.1  
packaging     21.3   
pip           20.0.2 
pkg-resources 0.0.0  
pluggy        1.0.0  
py            1.11.0 
pyparsing     3.0.9  
pytest        7.1.2  
setuptools    44.0.0 
tomli         2.0.1  
```
The slightly different error we have in CI is of the same kind, but happens because the `setuptools` on the system is too new.

We saw this error the first time a couple of hours ago and by chance [setuptools v62.4.0](https://github.com/pypa/setuptools/releases/tag/v62.4.0) was released a couple of hours ago :smirk:

**Comment by lizzyd710** [comment]
This was happening on my PR (#31107) as well. Good to know that it's not just me.

**Comment by tgamblin** [comment]
It looks like setup tools 62.4.0 came out 4 hours ago -- wondering if pinning to the prior 62.3.4 version would fix this for now while we sort out what's wrong.

**Comment by lizzyd710** [comment]
I merged develop after that commit but for some reason I get the same error when I run `spack style` on my local machine. Weirdly enough it doesn't happen anymore on the GitHub action in my PR.

**Comment by alalazo** [comment]
@lizzyd710 Not weird at all, the explanation is https://github.com/spack/spack/pull/31118#issuecomment-1154227939 Basically, updating `py-setuptools` might require some care to fix a few pipelines that break with the new major version. So I pinned the `setuptools` version in our CI as an hotfix.

If you:
```console
$ pip install -U setuptools==62.3.4
```
(or similar, depending on your environment) it should work for you too locally.
