### ISSUE TITLE
spack python base build setuptools conflicts with py-setuptools

### ISSUE THREAD

**Issue by cyrush** [LLNL/spack#31166]
### Steps to reproduce

This will fail due to same-named files during activate:
```console
$ spack install py-numpy
$ spack activate py-numpy
```

### Error message

```console
==> Warning: spack activate is deprecated in favor of environments and will be removed in v0.19.0
==> Activating extension py-numpy@1.22.4%gcc@7.5.0+blas+lapack patches=873745d arch=linux-ubuntu18.04-zen/vqvzkas for python@3.9.13%gcc@7.5.0+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93,4c24573,f2fd060 arch=linux-ubuntu18.04-zen/uha6ya5
==> Activating extension py-setuptools@62.3.2%gcc@7.5.0 arch=linux-ubuntu18.04-zen/if4j442 for python@3.9.13%gcc@7.5.0+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93,4c24573,f2fd060 arch=linux-ubuntu18.04-zen/uha6ya5
==> Error: Package merge blocked by file: /spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/python-3.9.13-uha6ya53k2a3edlcwzvvlgp4l763xbfy/lib/python3.9/site-packages/_distutils_hack/__pycache__/__init__.cpython-39.pyc```
```
The issue:

Spack installed python includes setuptools, however many packages also explicitly depend on py-setuptools, which of course provides the same files:

```
ls spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/python-3.9.13-uha6ya53k2a3edlcwzvvlgp4l763xbfy/l
ib/python3.9/site-packages/
README.txt       distutils-precedence.pth  pip-22.0.4.dist-info  setuptools
_distutils_hack  pip                       pkg_resources         setuptools-58.1.0.dist-info
```

```
root@4799f8213cb8:/# ls spack/opt/spack/linux-ubuntu18.04-zen/gcc-7.5.0/py-setuptools-62.3.2-if4j442dyb4efvxbatqyx3724hv5b4uq/lib/python3.9/site-packages/
_distutils_hack  distutils-precedence.pth  pkg_resources  setuptools  setuptools-62.3.2.dist-info
```

So `spack activate` will fails for python packages that depend on setuptools

I know spack activate is going away, however I am not sure exactly how `py-setuptools` could work well with two copies. 

How does this issue shake out with environment views?

### Information on your system

```
 spack/bin/spack debug report
* **Spack:** 0.19.0.dev0 (4f9f56630bbcee4bc040566d862d3f09f815c938)
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-zen2
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by cyrush** [comment]
`spack activate -f` avoids this problem. 

Multiple versions are still a little worrisome -- but this is no longer a blocker for us.

**Comment by cyrush** [comment]
Update: `spack activate -` it does not fully resolve for all cases. 

I am unblocked with py-numpy, but if I try to directly activate py-setuptools  or py-pip -- it will still fail.

Since the base spack has both setuptools and pip installed - I don't need to activate them any more.

**Comment by adamjstewart** [comment]
You'll likely want to add any missing files to the list [here](https://github.com/spack/spack/blob/v0.18.0/var/spack/repos/builtin/packages/python/package.py#L1288,L1297).

**Comment by adamjstewart** [comment]
Oh, I guess that only works if other packages add those files, not if Python itself does? Not sure how to handle this since not all Python installations will have those files and we always want to override with the possibly newer files from `py-setuptools` installations.

**Comment by white238** [comment]
`spack activate -f` does not activate any dependencies so this didn't work for my case due to the many dependencies of `py-sphinx`.  Going to investigate `spack view add` at @becker33 's advice.

**Comment by white238** [comment]
I was able to bandaid this until I have the time to properly fix this by adding all built python packages in my install prefix (minus a couple that wont activate) to my activate list.  I have ideas on how to move uberenv to views but I really need to unblock my project.

**Comment by alalazo** [comment]
This issue is on a command that has been removed (after being deprecated). Closing.
