### ISSUE TITLE
Installation issue: llvm-amdgpu

### ISSUE THREAD

**Issue by upsj** [LLNL/spack#31176]
### Steps to reproduce the issue

Spack doesn't seem to control the cmake generator environment variable, so the call to make for libcxx inside llvm-amdgpu fails. Unsetting the variable fixes it.

```console
$ CMAKE_GENERATOR=Ninja spack install llvm-amdgpu
```

@arjun-raj-kuppala @haampie @srekolam

### Error message

<details><summary>Error message</summary><pre>
==> llvm-amdgpu: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

1 error found in build log:
     39011        LLVM_EXTERNAL_PROJECTS
     39012        PACKAGE_VENDOR
     39013
     39014
     39015    -- Build files have been written to: /tmp/tribizel/spack-stage/spack-stage-llvm-amdgpu-5.1.3-oqfsc3jrf24q
              zxif2ynii3mouyqhrulx/spack-src/build-bootstrapped-libcxx
     39016    ==> [2022-06-17-08:30:22.012902] 'make' '-j16'
  >> 39017    make: *** No targets specified and no makefile found.  Stop.
</pre></details>

### Information on your system

* **Spack:** 0.19.0.dev0 (1c0bf12e5b21de3d77af2b1025479d30c4c94400)
* **Python:** 3.6.8
* **Platform:** linux-centos8-zen2
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/8925133/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/8925134/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by msimberg** [comment]
@upsj I think https://github.com/spack/spack/pull/31403 fixed this. Could you confirm if it fixed it for you?

**Comment by upsj** [comment]
I would really like to confirm that, but it seems like in the meantime, something else broke:
```
$ CMAKE_GENERATOR=Ninja bin/spack install llvm-amdgpu
==> Error: Package 'armpl' not found.
```

**Comment by upsj** [comment]
I can confirm this fixes the issue
