### ISSUE TITLE
read-cray-manifest tries to access protected directory on Cray EX

### ISSUE THREAD

**Issue by ldalessa** [LLNL/spack#31191]
### Steps to reproduce

```console
$ spack external read-cray-manifest 
==> Error: [Errno 13] Permission denied: '/opt/cray/pe/cpe-descriptive-manifest/cpe-descriptive-manifest-nvidia-21.12.json'
```

This directory has permissions `drwxr--r--` on our installation.

### Information on your system

spack debug report 
* **Spack:** 0.19.0.dev0 (043b2cbb7c99d69a373f3ecbf35bc3b4638bcf85)
* **Python:** 3.6.15
* **Platform:** cray-sles15-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by scheibelp** [comment]
Note these files are installed by RPMs managed by Cray: they are now aware of these issues and future installs (of later versions) should not have these issues; `spack external read-cray-manifest` cannot succeed until these permissions are corrected. In the meantime, if an admin can modify these permissions for you, then Spack will be able to parse them.

It occurs to me that `spack external find` may also be prematurely terminated by this issue, so I should allow that to proceed (without parsing the manifest) if the permissions are insufficient (that doesn't specifically address this issue though).

**Comment by ldalessa** [comment]
Yes, I was seeing the same permissions issues with `spack external find`. Also, when I explicitly ask for a loaded module (like `hdf5`), it doesn't produce the permissions failure but also fails to find the module.

**Comment by scheibelp** [comment]
https://github.com/spack/spack/pull/31201 should address the issues with `spack external find`: although it won't be able to read the manifest, it should be able to find packages using the built-in external detection support (without #31201, it would skip all detection steps if the manifest did not have the right permissions - now it skips broken manifests and continues with the other detection mechanisms).

> Also, when I explicitly ask for a loaded module (like hdf5), it doesn't produce the permissions failure but also fails to find the module.

`spack external find` doesn't search for modules (and it doesn't automatically create packages.yaml entries with defined modules), so I don't think that PR would address this (but I'm also curious if this was working for you before).

**Comment by ldalessa** [comment]
Thanks Peter. I meant when I run `spack external find hdf5` I expected something to happen, but it would just tell me "no new packages found."

No need to worry about it for this issue, you're welcome to close it.

**Comment by alalazo** [comment]
I think this was solved, at least reading https://github.com/spack/spack/issues/31191#issuecomment-1161124722 I also tried:
```
$ spack external read-cray-manifest
```
on Perlmutter, and it works correctly. Feel free to reopen if there's anything still to be fixed from this report.
