### ISSUE TITLE
Spack spec fails with "complex" flags string even if quoted

### ISSUE THREAD

**Issue by adrienbernede** [LLNL/spack#31214]
### Steps to reproduce

```console
spack/bin/spack spec umpire%clang@9.0.0 cxxflags="-stdlib=libc++ -DGTEST_HAS_CXXABI_H_=0"
```

@cosmicexplorer @trws 
I seem to have an issue with this

### Error message

```console
➜  uberenv_libs git:(bernede1/ci/spack-user-cache-path) spack/bin/spack --debug --stacktrace spec umpire%clang@9.0.0 cxxflags="-stdlib=libc++ -DGTEST_HAS_CXXABI_H_=0"
/g/g91/bernede1/Projects/umpire/uberenv_libs/spack/lib/spack/spack/cmd/__init__.py:126 ==> [2022-06-21-07:01:56.277447] Imported spec from built-in commands
/g/g91/bernede1/Projects/umpire/uberenv_libs/spack/lib/spack/spack/cmd/__init__.py:126 ==> [2022-06-21-07:01:56.279183] Imported spec from built-in commands
/g/g91/bernede1/Projects/umpire/uberenv_libs/spack/lib/spack/spack/main.py:896 ==> [2022-06-21-07:01:56.281030] SpackError: Unexpected token: '='  Encountered when parsing spec:
    umpire%clang@9.0.0
                         ^

Some compiler or linker flags were provided without quoting their arguments,
which now causes spack to try to parse the *next* argument as a spec component
such as a variant instead of an additional compiler or linker flag. If the
intent was to set multiple flags, try quoting them together as described below.

Possible flag quotation errors (with the correctly-quoted version after the =>):
(1) cxxflags=-stdlib=libc++ -DGTEST_HAS_CXXABI_H_=0 => cxxflags="-stdlib=libc++ -DGTEST_HAS_CXXABI_H_=0"
/g/g91/bernede1/Projects/umpire/uberenv_libs/spack/lib/spack/spack/error.py:54 ==> [2022-06-21-07:01:56.281606] Error: Unexpected token: '='  Encountered when parsing spec:
    umpire%clang@9.0.0
                         ^

Some compiler or linker flags were provided without quoting their arguments,
which now causes spack to try to parse the *next* argument as a spec component
such as a variant instead of an additional compiler or linker flag. If the
intent was to set multiple flags, try quoting them together as described below.

Possible flag quotation errors (with the correctly-quoted version after the =>):
(1) cxxflags=-stdlib=libc++ -DGTEST_HAS_CXXABI_H_=0 => cxxflags="-stdlib=libc++ -DGTEST_HAS_CXXABI_H_=0"
Traceback (most recent call last):
  File "/g/g91/bernede1/Projects/umpire/uberenv_libs/spack/lib/spack/spack/spec.py", line 5145, in do_parse
    self.unexpected_token()
  File "/g/g91/bernede1/Projects/umpire/uberenv_libs/spack/lib/spack/spack/parse.py", line 133, in unexpected_token
    self.next_token_error("Unexpected token: '%s'" % self.next.value)
  File "/g/g91/bernede1/Projects/umpire/uberenv_libs/spack/lib/spack/spack/parse.py", line 126, in next_token_error
    raise ParseError(message, self.text[0], self.token.end)
spack.parse.ParseError: Unexpected token: '='

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/g/g91/bernede1/Projects/umpire/uberenv_libs/spack/lib/spack/spack/cmd/__init__.py", line 219, in parse_specs
    specs = spack.spec.parse(sargs)
  File "/g/g91/bernede1/Projects/umpire/uberenv_libs/spack/lib/spack/spack/spec.py", line 5366, in parse
    return SpecParser().parse(string)
  File "/g/g91/bernede1/Projects/umpire/uberenv_libs/spack/lib/spack/spack/parse.py", line 157, in parse
    return self.do_parse()
  File "/g/g91/bernede1/Projects/umpire/uberenv_libs/spack/lib/spack/spack/spec.py", line 5148, in do_parse
    raise six.raise_from(SpecParseError(e), e)
  File "<string>", line 3, in raise_from
spack.spec.SpecParseError: Unexpected token: '='

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/g/g91/bernede1/Projects/umpire/uberenv_libs/spack/lib/spack/spack/main.py", line 893, in main
    return _main(argv)
  File "/g/g91/bernede1/Projects/umpire/uberenv_libs/spack/lib/spack/spack/main.py", line 848, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/g/g91/bernede1/Projects/umpire/uberenv_libs/spack/lib/spack/spack/main.py", line 876, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/g/g91/bernede1/Projects/umpire/uberenv_libs/spack/lib/spack/spack/main.py", line 533, in _invoke_command
    return_val = command(parser, args)
  File "/g/g91/bernede1/Projects/umpire/uberenv_libs/spack/lib/spack/spack/cmd/spec.py", line 82, in spec
    input_specs = spack.cmd.parse_specs(args.specs)
  File "/g/g91/bernede1/Projects/umpire/uberenv_libs/spack/lib/spack/spack/cmd/__init__.py", line 236, in parse_specs
    raise spack.error.SpackError(msg)
spack.error.SpackError: Unexpected token: '='  Encountered when parsing spec:
    umpire%clang@9.0.0
                         ^

Some compiler or linker flags were provided without quoting their arguments,
which now causes spack to try to parse the *next* argument as a spec component
such as a variant instead of an additional compiler or linker flag. If the
intent was to set multiple flags, try quoting them together as described below.

Possible flag quotation errors (with the correctly-quoted version after the =>):
(1) cxxflags=-stdlib=libc++ -DGTEST_HAS_CXXABI_H_=0 => cxxflags="-stdlib=libc++ -DGTEST_HAS_CXXABI_H_=0"
```

### Information on your system

* **Spack:** 0.19.0.dev0 (aebb601b70018f2879c537bf6021ba28e39dae49)
* **Python:** 3.7.2
* **Platform:** linux-rhel7-power9le
* **Concretizer:** clingo

@cosmicexplorer @trws, this likely relates to #29282 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by davidbeckingsale** [comment]
If the whole spec is quoted, it seems to parse, e.g.:
```
./bin/spack spec 'umpire%clang@9.0.0 cxxflags="-stdlib=libc++ -DGTEST_HAS_CXXABI_H_=0"'
```

**Comment by trws** [comment]
That seems like a regression, the way @davidbeckingsale posted it is what that patch was meant to fix, but it should have kept working with the individual components quoted as well.

**Comment by davidbeckingsale** [comment]
I think the issue is that (in my investigations) the quotes don't make it from the shell into Spack, so I'm not sure how we can fix it. IIRC I was able to get it to parse by explicitly quoting the flags too:

```
./bin/spack spec umpire%clang@9.0.0 cxxflags=\"-stdlib=libc++ -DGTEST_HAS_CXXABI_H_=0\"
```

**Comment by trws** [comment]
Yeah, the shell would strip them.  They should be represented by the fact that the full cxxflag string is part of the element of the list representing the arguments though, so it's probably getting joined off instead of parsed in pieces somewhere it shouldn't be.

**Comment by adrienbernede** [comment]
@trws I _think_ the problem may be related to the use of `=` inside the flag value.
And again, likely related to https://github.com/spack/spack/pull/29282 although I did not run the `git bisect`.

**Comment by trws** [comment]
Oh definitely, what you had there would have worked before that I'm pretty sure, but the same thing with cflags also specified would have failed in spectacular fashion.  I'll see if I can make some time to look into this.

**Comment by trws** [comment]
It's a bit worse than I thought.  At present, if the parser is passed a string it treats that as a shell command line to be split then processes it, that seems reasonable.  If it's passed a list, it joins the list with spaces, then treats the result as a command line to be split.  This is where things are breaking for quoted flags arguments, because the subsequent splitting breaks them apart.  I tried adding in a corrected quoter that will work for any nested shell quoting, but that produces errors because spack tests currently expect that:

* arguments passed in on the command line will have quotes removed rather than preserved (shell does this, ok)
* arguments passed in as though on the command line but from inside spack tests as a single argument with embedded quotes will have *their* quotes removed and words split (!!?!?)

So at the moment we have conflicting requirements for handling of lists of arguments, and I'm not sure yet how best to deal with this.  I *think* we might be able to get away with taking a join of the flatmap of quoting each argument after applying shutil.split to each of them individually, but man is that strange.

@cosmicexplorer, @tgamblin, @haampie any thoughts?

**Comment by trws** [comment]
Sadly the split and quote method does not work, because it breaks things like `spack spec coreutils 'cflags=-O3 -g'` from the command line.  If that goes away, then `spack spec 'coreutils cflags="-O3 -g"'` breaks, and that's required by existing tests to work.  I'm starting to become convinced that we need a coherent policy for how this is supposed to behave we can implement, because at the moment quoted arguments do not work adequately without embedded quotes.
