### ISSUE TITLE
Spec Build Phase

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#3123]
@alalazo 

A number of packages have restrictions beyond what the concretizer can check for in the specs.  Currently, those restrictions generally go in `install()`, and do not get run until the user tries to install a package.  For example, #3119 

This proposal is to create a new phase in all package superclasses (including `Package`) call `spec`.  This phase will be run either:

1. After concretization in `spack spec`, `spack install`, etc --- allowing the user to know that this combination won't compile, *berfore* install is attempted.

2. During concretization, allowing the concretizer the possibility to pick something else that *will* work.

I understand that (2) would be a bit harder.  But (1) should be simple, and yield immediate benefit over what we have now.  (For example... if I say `spack install myproject`, Spack could spend a lot of time installing prerequisites before it comes back to me and tells me my spec won't install.  This proposal would solve that issue).

Thoughts?

**Comment by alalazo** [comment]
What about using instead a new `conflict` directive in the package? Something like:
```python
conflict('%intel@16', when='@0.2.15:0.2.19')
```
The evaluation semantic would be:
```python
if spec.satisfies(when_condition) and spec.satisfies(conflict_condition):
    raise InstallError(...)
```
and would happen at the end of concretization.

**Comment by citibeth** [comment]
I think that's a great idea!  Without looking too closely at existing use cases (#3121), I suspect it would satisfy at least 90% of our needs.  If we still think we need something more general, we can always add a `config` phase later.  But I'm suspecting we won't feel the need.

**Comment by citibeth** [comment]
> The evaluation semantic would be:

Ideally, it should collect all conflicts for the entire DAG, and then raise them in one giant exception at the end.

**Comment by alalazo** [comment]
> Ideally, it should collect all conflicts for the entire DAG, and then raise them in one giant exception at the end.

That's the idea, I just didn't code on the fly the for loop and the collection list 😄

**Comment by adamjstewart** [comment]
We've talked about a `conflicts()` directive in #2795 as well, just so everyone is aware of both sides of the discussion. I think it would definitely help a lot.

From what I've seen a lot of the special spec checks are either compiler related (clang doesn't allow certain flags) or variant related (`+x` and `+y` are incompatible variants). I think the former would be solved by a `conflicts()` directive and the latter would be fixed by @alalazo's mutually exclusive/multi-valued variants work.

**Comment by alalazo** [comment]
@adamjstewart I forgot completely about #2795 ! I don't know if I should feel reassured by the fact I am proposing basically the same implementation or scared to have the memory of a red-fish :smile:

**Comment by citibeth** [comment]
I'm closing this, we should continue discussion at #2795

**Comment by adamjstewart** [comment]
Sometimes I feel like my biggest contribution to Spack is having an encyclopedic knowledge of every existing PR/issue/comment 😆
