### ISSUE TITLE
Proposal to improve intel-oneapi component support

### ISSUE THREAD

**Issue by becker33** [LLNL/spack#31278]
### Summary

`intel-oneapi-compilers-classic` is currently a bunch of pointers into `intel-oneapi-compilers`. This seems to work really well (although we should add some symlinks to it).

No other intel components are handled this way, and there is no separable component for the new compilers.

Proposal: rename `intel-oneapi-compilers` to `intel-oneapi`, and handle all separable components (including new `intel-oneapi-compilers`) the way we currently handle `intel-oneapi-compilers-classic`. This includes packages like `intel-oneapi-mkl` as well as the compiler components.

### Rationale

The most prominent reason for this proposal is that it is currently impossible to deploy modules for both classic (`icc`) and new (`icx`) intel compilers in Spack for any version of icc more recent than `19.0.4`.

Other benefits of this proposal include:
- Allows us to install the large intel-oneapi suite once, but still have separable components (saves space)
- Allows the %intel and %oneapi compilers to have separate packages, which is good for sites deploying modules for bootstrapped compilers with Spack.
- Each component can create top-level bin/lib/etc libraries (symlinks to deeper structure in intel-oneapi package)
- Allows us to properly map component versions to oneapi version (The version of the entire suite, the oneapi compiler, the legacy compiler, and mkl are all different for the same installation)

### Alternatives

Frankly, I don't have any good alternative proposals. The closest to feature parity that I've come up with is creating separate tarballs for each component, but that seems like a much bigger break from intel's packaging model.

### Cons

The biggest con of this proposal is that we move further from a "vanilla" intel-oneapi install for the individual components.

Another con is that users who only want to install a single component from oneapi will use more disk space (because they will have a full oneapi install, and symlinks to it.

Anyone have feedback?
@rscohn2 @tgamblin @haampie @alalazo @adamjstewart y'all seem most likely to have feedback, but interested in any feedback I can get.

**Comment by rscohn2** [comment]
Adding @scheibelp 

I don't think the proposal would save space. There is some duplication between the packages. I think it is mainly TBB and openmp runtimes. TBB is relatively small, openmp runtime is bigger, but still much smaller than compiler or mkl. The duplicates are unused and could be deleted post-install.

It would likely use more space for many users. We would have to install all the components into intel-oneapi because we would not know which ones might be used in the future. IPP and DAL are huge (comparable to MKL) and rarely used by spack users. The alternative would be to incrementally install more components into intel-oneapi as the user installed intel-oneapi-xxx, but that would break spack build cache.

I would not know how to manage these cases: multiple basekits include the same version of a component, some compiler and vtune releases are not part of any basekit, ....

Installing every component in its own spack prefix gives maximum flexibility.

The motivations that you mention in the rationale are valid, but I think it will be easier to solve them with the current arrangement.

**Comment by becker33** [comment]
@rscohn2 I think you're right about the space constraints.

> multiple basekits include the same version of a component

This one is easy -- if it works for versions 2022.2.1 through 2022.5.0 and 2022.5.2 `depends_on('intel-oneapi@2022.2.1:2022.5.0,2022.5.2')`.

> some compiler and vtune releases are not part of any basekit

Is there currently any way to install these?

Of the motivations I mention, the most difficult to work around is the inability to present modules for the two compilers separately. Handling that in Spack infrastructure would require a complete rewrite of the module generation code, but I think merely updating the `intel-oneapi-compilers-classic` package to include symlinks and a minor modification to Spack compiler bootstrapping would be sufficient to work around it.

Are you amenable to symlinks from `intel-oneapi-compilers-classic` into `intel-oneapi-compilers` to create `bin`, `lib`, and other directories?

**Comment by rscohn2** [comment]
> Is there currently any way to install these?

We never install basekit/hpckit, we just install the standalones from here: https://www.intel.com/content/www/us/en/developer/articles/tool/oneapi-standalone-components.html

I guess the answer is that for most versions, there will be a depends_on some basekit/hpckit and no install, but some versions will require installing as is done today.

> Are you amenable to symlinks from intel-oneapi-compilers-classic into intel-oneapi-compilers to create bin, lib, and other directories?

I don't see any problems with that.  A spack developer would have to say that it is ok as it might break an assumption or limit spack's future flexibility in some way.

**Comment by becker33** [comment]
I'll need to check whether there's work to be done to support out-of-prefix symlinks in binary packages, but for the most part we aim to handle symlinks properly in Spack.

**Comment by scheibelp** [comment]
> The most prominent reason for this proposal is that it is currently impossible to deploy modules for both classic (icc) and new (icx) intel compilers in Spack for any version of icc more recent than 19.0.4.

I assume you can *deploy* them, but that you cannot load them both. I'm not sure why this is a problem: they set CC etc. for ease-of-use (so are incompatible by design) - am I missing something?

**Comment by vanderwb** [comment]
@scheibelp Chiming in on this one - maybe it's my lack of familiarity with how OneAPI compilers are currently handled in Spack, but I don't see a way to load both of them using an Lmod stack.

Right now I have both the oneapi and intel compilers in my Spack setup. Spack creates modules for both of them, but the "classic" module uses a `depends_on` condition to load the oneapi module too. However, in an Lmod hierarchical stack, these two are compiler families and thus should be mutually exclusive loads.

If you have suggestions I'd love to have them, but for the average user it's unclear at best.
