### ISSUE TITLE
containerize's z10_spack_environment.sh "missing" CPATH and LIBRARY_PATH

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#31284]
### Steps to reproduce

1. Build a container using a Dockerfile generated by `spack containerize`.
2. Inspect the resulting `/etc/profile.d/z10_spack_environment.sh` in e.g the final image.
3. Notice that it does not include lines that set CPATH or LIBRARY_PATH

### Error message

When we try to build the R/Bioconductor package `XVector` in some extra_instructions in the builder stage of a build from a Dockerfile generated by `spack containerize`, we get failures related to:

1. the inability of the compiler to find `zlib.h`; and
2. the inability of the linker to find something to link for `-lz`.

We can fix this by explicitly setting `CPATH` and `LIBRARY_PATH` after sourcing `z10_spack_environment.sh`, something like:

``` Dockerfile
    extra_instructions:
      build: |
        # blah blah blah
        RUN source /etc/profile.d/z10_spack_environment.sh \
          && export CPATH=/opt/view/include \
          && export LIBRARY_PATH=/opt/view/lib \
        # blah blah blah
```

Whether "environments" (generic, not Spack envs...) should or should not include affordances to support compiling against things that spack built is [an argument as old as the trees](https://github.com/spack/spack/issues/3955), but given all of the other things that 

```
spack env activate --sh -d .
```
generates, these seem like a reasonable addition.

### Information on your system

``` shellshession
$ ./bin/spack debug report
* **Spack:** 0.18.0 (4c6564f10aa516bc00c1d7dbfdeafe35128985fe)
* **Python:** 3.9.0
* **Platform:** linux-centos7-skylake_avx512
* **Concretizer:** clingo
```

Note that I'm lying when I check the box below about running the failing commands in debug mode and reporting the output, there is no "failing command" _per se_.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
I would consider this working as intended, and thus not a bug. We don't setup CPATH etc. in other places too by default (modules, environments, ...) and if users require those environment variables they have ways of adding them.
