### ISSUE TITLE
`spack python` doesn't support readline

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#3128]
When I run `python`, I get readline support, which enables me to do things like use the arrow keys to go left/right or cycle forward/backward through my history, just as you would expect from your terminal shell.

When I run `spack python`, I don't seem to get this support, and the arrow keys are converted to meta characters:
```
$ spack python
Spack version 0.10.0
Python 2.7.12, Darwin x86_64
>>> print('hello world')^[[D^[[A^[[B^[[C
  File "<console>", line 1
    print('hello world')
                        ^
SyntaxError: invalid syntax
```
Any idea why?

**Comment by citibeth** [comment]
That's strange... `readline` is included as a non-optional dependency.  And autotools generally automagically picks up things like that if they are provided.  I suppose the next step is looking at the build log?

**Comment by adamjstewart** [comment]
Just to clarify, this isn't a Spack-built Python. This is my system Python. I'm running the `spack python` command.
