### ISSUE TITLE
Installation issue: libbsd (and its dependencies, including expat and many others)

### ISSUE THREAD

**Issue by davidedelvento** [LLNL/spack#31345]
### Steps to reproduce the issue

```console
$ spack checkout releases/v0.18
$ spack install expat
```
Should be obvious from the checkout and the system info below, but to be more explicit, this is attempting to install expat@2.4.8%gcc@12.1.0+libbsd which is concretized with arch=linux-rhel8-icelake and it is using libbsd@0.11.5 which in turn is using libmd@1.0.4 both with the same compiler and the same architecture (sorry I cannot copypaste from the machine where this is happening)

### Error message

<details><summary>Error message</summary><pre>
125 configure: error: Enforced use of libbsd cannot be satisfied.
</pre></details>

Note that `spack maintainers libbsd` returns nothing, so I am pinging everybody listed in https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/libbsd/package.py (sorry)

@tgamblin @adamjstewart @michaelkuhn @hartzell @haampie @openmp-arb @samcmill @sethrj @ax3l @arekfu 

### Information on your system

* **Spack:** 0.18.0 (c09bf37ff690c29779a342670cf8a171ad1b9233)
* **Python:** 3.6.8
* **Platform:** linux-rhel8-icelake
* **Concretizer:** clingo

### Additional information

Digging into the `spack-build*txt` logs reveals the cause of the failure:

```
$ ls -l ~/spack/opt/spack/linux-rhel8-icelake/intel-2021.6.0/libbsd-0.11.5-3lhu2gfjpopbp4brnri2kqfqx4kwfm5b/lib

total 1044
-rw-r--r-- 1 691532 Jun 28 10:11 libbsd.a
-rw-r--r-- 1 3652 Jun 28 10:11 libbsd-ctor.a
-rw-r--r-- 1 276 Jun 28 10:11 libbsd.so
lrwxrwxrwx 1 16 Jun 28 10:11 libbsd.so.0 -> libbsd.so.0.11.5
-rwxr-xr-x 1 366552 Jun 28 10:11 libbsd.so.0.11.5
drwxr-sr-x 2 86 Jun 28 10:11 pkgconfig

cat ~/spack/opt/spack/linux-rhel8-icelake/intel-2021.6.0/libbsd-0.11.5-3lhu2gfjpopbp4brnri2kqfqx4kwfm5b/lib/libbsd.so

/* GNU ld script
* The MD5 functions are provided by the libmd library. */
OUTPUT_FORMAT(elf64-x86-64)
GROUP([/home/h505495@honeywell.lab/spack_1/opt/spack/linux-rhel8-icelake/intel-2021.6.0/libbsd-0.11.5-3lhu2gfjpopbp4brnri2kqfqx4kwfm5b/lib/libbsd.so.0.11.5](mailto:/home/h505495@honeywell.lab/spack_1/opt/spack/linux-rhel8-icelake/intel-2021.6.0/libbsd-0.11.5-3lhu2gfjpopbp4brnri2kqfqx4kwfm5b/lib/libbsd.so.0.11.5) AS_NEEDED(-lmd))
```
Manually removing this file with this error message and replacing it with syslink to the versioned so solves the issue.

However that should not have happened in the first place and I did not figure out why it did

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by davidedelvento** [comment]
Forgot to mention: this might be very loosely related to https://github.com/spack/spack/issues/15750 
However that claimed to happen only for the XL compiler, whereas this one happens for both gcc (this bug) and for intel (which I did not bother to report, since the problem is exactly identical, so I assume root cause is too)

**Comment by davide-q** [comment]
This does not happen anymore in v0.20.1 so it *probably* can be closed.

**Comment by davidedelvento** [comment]
Confirmed, this has been solved (not sure when/where/how)
