### ISSUE TITLE
Error: Package 'armpl' not found

### ISSUE THREAD

**Issue by luke-dt** [LLNL/spack#31453]
### Steps to reproduce

```console
$ spack spec python
```

### Error message

```console
Error: Package 'armpl' not found
```

### Information on your system

* **Spack:** 0.19.0.dev0 (30e5828f068ba713432c5489647900baaa2a6a14)
* **Python:** 3.10.5
* **Platform:** linux-fedora36-zen3
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by luke-dt** [comment]
I think this is related to #31437

**Comment by luke-dt** [comment]
not sure why, but running `spack clean -ab` fixed the issue for me

**Comment by brechtm** [comment]
`spack clean -fmps` fixed it for me, keeping cached downloads.

**Comment by jppelteret** [comment]
My colleague, @ecomellas, has run into exactly the same issue on a clean download of spack (on a Macbook with MacOS 12.4 Montrey, if that makes any difference). We ran the two commands suggested above and that seemed to work. Thanks for the suggestions @luke-dt and @brechtm!

**Comment by nish-ant** [comment]
Thanks for the suggestions. Just a note: 
Running the command `spack clean -ab` should suffice as mentioned in the [command manual](https://spack.readthedocs.io/en/latest/command_index.html#spack-clean).

**Comment by ltalirz** [comment]
If someone wants a faster fix: delete all occurences of the respective package from `~/.spack/cache/providers/builtin-index.json`.

As for how it ended up there in the first place I'm still not entirely clear. I'm on a clean install of spack 0.18.1 on CentOS 7.9
