### ISSUE TITLE
spack crashing due to fortran and c compilers during OpenMPI installation phase of dealii installation

### ISSUE THREAD

**Issue by vinayak-gholap1993** [LLNL/spack#3146]
Hello all,
I am trying to install dealii using spack. In the OpenMPI installation phase I get following error

spack install dealii@develop
==> Installing dealii
==> bzip2 is already installed in /home/sfb814/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/bzip2-1.0.6-icdmmm2m6f26ryoszaqexcqtyasv7a45
==> muparser is already installed in /home/sfb814/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/muparser-2.2.5-ckdfrr7gga4hdh4qdqqz7wf7gbt5rdhv
==> cmake is already installed in /home/sfb814/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/cmake-3.7.2-mxs4mxboep5yxtkmujke5kybzoreyqlf
==> Installing hdf5
==> zlib is already installed in /home/sfb814/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/zlib-1.2.10-mr6fyxqiwefloyjj7oaqoqnedakglzfu
==> Installing openmpi
==> hwloc is already installed in /home/sfb814/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/hwloc-1.11.5-wapbsf2untp27ddm2tbnshhto4pzvnce
==> Using cached archive: /home/sfb814/spack/var/spack/cache/openmpi/openmpi-2.0.2.tar.bz2
==> Already staged openmpi-2.0.2-2uaqbv4wzdk2tzbbvzgiukaiz4nger2j in /home/sfb814/spack/var/spack/stage/openmpi-2.0.2-2uaqbv4wzdk2tzbbvzgiukaiz4nger2j
==> Already patched openmpi
==> Building openmpi [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Error: InstallError: OpenMPI requires both C and Fortran compilers!
/home/sfb814/spack/var/spack/repos/builtin/packages/openmpi/package.py:157, in die_without_fortran:
     150      @run_before('autoreconf')
     151      def die_without_fortran(self):
     152          # Until we can pass variants such as +fortran through virtual
     153          # dependencies depends_on('mpi'), require Fortran compiler to
     154          # avoid delayed build errors in dependents.
     155          if (self.compiler.f77 is None) or (self.compiler.fc is None):
     156              raise InstallError(
  >> 157                  'OpenMPI requires both C and Fortran compilers!'
     158              )

See build log for details:
  /tmp/sfb814/spack-stage/spack-stage-yErYv2/openmpi-2.0.2/spack-build.out

I checked the list of compilers and have this

dpkg --list | grep compiler
ii  fort77                                      1.15-10                                       all          Invoke f2c like a real compiler
ii  g++                                         4:5.3.1-1ubuntu1                              amd64        GNU C++ compiler
ii  g++-5                                       5.4.0-6ubuntu1~16.04.4                        amd64        GNU C++ compiler
ii  gcc                                         4:5.3.1-1ubuntu1                              amd64        GNU C compiler
ii  gcc-5                                       5.4.0-6ubuntu1~16.04.4                        amd64        GNU C compiler
ii  gcc-5-multilib                              5.4.0-6ubuntu1~16.04.4                        amd64        GNU C compiler (multilib support)
ii  gcc-multilib                                4:5.3.1-1ubuntu1                              amd64        GNU C compiler (multilib files)
ii  gfortran                                    4:5.3.1-1ubuntu1                              amd64        GNU Fortran 95 compiler
ii  gfortran-5                                  5.4.0-6ubuntu1~16.04.4                        amd64        GNU Fortran compiler
ii  hardening-includes                          2.7ubuntu2                                    all          Makefile for enabling compiler flags for security hardening
ii  libllvm3.8:amd64                            1:3.8-2ubuntu4                                amd64        Modular compiler and toolchain technologies, runtime library
ii  libxkbcommon0:amd64                         0.5.0-1ubuntu2                                amd64        library interface to the XKB compiler - shared library

Could some one help in thiṣ?

**Comment by davydden** [comment]
Make sure that gcc and gfortran are in path
```
$ which gcc
$ which gfortran
```

It’s likely that you **first** tried installing without `gfortran` being in path,
so Spack picked up c/c++ part of GCC only and still try to use it as such.
To fix it, delete `compilers.yaml` in `.spack` hidden folder and retry and edit it manually to provide path to `gfortran`.

**Comment by vinayak-gholap1993** [comment]
Thank you for a quick reply Denis. It worked that way.

**Comment by xiongshiyun** [comment]
Dear Denis @davydden ,

I have encountered the same problem when installing votca using spack. I am not quite clear about the solutions you provided above:
actually my compilers.yaml is not in the .spack hidden folder but instead it is in ./spack/var/spack/mock_configs/site_spackconfig/   In the compilers.yaml file, part of the contents is:

compilers:
  all:
    clang@3.3:
      cc: /path/to/clang
      cxx: /path/to/clang++
      f77: none
      fc: none
      modules: None
      strategy: PATH
    gcc@4.5.0:
      cc: /path/to/gcc
      cxx: /path/to/g++
      f77: /path/to/gfortran
      fc: /path/to/gfortran
      modules: None
      strategy: PATH
    gcc@5.2.0:
      cc: cc
      cxx: CC
      f77: ftn
      fc: ftn
      modules:
        - PrgEnv-gnu
        - gcc/5.2.0
      strategy: MODULES
 
I tried to added gfortran to both f77 and fc in clang with the full path:  /home/xiong/votca_spack/spack/lib/spack/env/clang/gfortran

and in gcc@4.5.0, the path of f77 and fc is changed to /usr/bin/gfortran
But it doesn't help with those changes.

Thanks a lot.
With best regards,
Shiyun

**Comment by davydden** [comment]
@xiongshiyun I would say you are editing the wrong file. Look for `compilers.yaml` inside `$HOME/.spack`. Make sure you run the latest Spack (do `git pull`) and retry.

> I tried to added gfortran to both f77 and fc in clang with the full path: /home/xiong/votca_spack/spack/lib/spack/env/clang/gfortran

this is wrong, it's compiler wrapper used by spack. You never point to it anyhow in your config files.

**Comment by xiongshiyun** [comment]
Dear Denis @davydden 

Thank you very much for your kind help. 
I added gfortran (/usr/bin/gfortran) to f77 and fc in ~/.spack/linux/compilers.yaml and it solved the problem.

With best regards,
Shiyun

**Comment by ewegener** [comment]
@xiongshiyun thanks for posting the path to the file. Solved the problem for me too.

**Comment by davydden** [comment]
for the record, this PR https://github.com/spack/spack/pull/7017 should help with autodetection by Spack.
