### ISSUE TITLE
Installation issue: llvm

### ISSUE THREAD

**Issue by kc9qey** [LLNL/spack#31476]
### Steps to reproduce the issue

<pre>
[arnoldg@dt-login03 delta]$ spack spec -l llvm@14.0.6 %gcc@11.2.0 ^perl@5.34.1
Input spec
--------------------------------
llvm@14.0.6%gcc@11.2.0
    ^perl@5.34.1

Concretized
--------------------------------
3nfs34w  llvm@14.0.6%gcc@11.2.0+clang~code_signing+compiler-rt~cuda~flang+gold+internal_unwind~ipo+libcxx~link_llvm_dylib+lld+lldb~llvm_dylib~mlir+omp_as_runtime~omp_debug~omp_tsan+polly~python~shared_libs~split_dwarf~z3 build_type=Release patches=d85ef51,f920173 shlib_symbol_version=none targets=none version_suffix=none arch=linux-rhel8-zen3
v2fpr7w      ^binutils@2.38%gcc@11.2.0~gas+gold~headers~interwork+ld~libiberty~lto+nls+plugins libs=shared,static arch=linux-rhel8-zen3
4j7vg3u          ^diffutils@3.6%gcc@11.2.0 arch=linux-rhel8-zen3
ivt6yha          ^gettext@0.21%gcc@11.2.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-rhel8-zen3
baq45br              ^bzip2@1.0.6%gcc@11.2.0~debug~pic+shared arch=linux-rhel8-zen3
va3oiyg              ^libiconv@1.16%gcc@11.2.0 libs=shared,static arch=linux-rhel8-zen3
pv2wyvu              ^libxml2@2.9.13%gcc@11.2.0~python arch=linux-rhel8-zen3
iuw23ll                  ^pkgconf@1.4.2%gcc@11.2.0 arch=linux-rhel8-zen3
d4nsvrr                  ^xz@5.2.4%gcc@11.2.0~pic libs=shared,static arch=linux-rhel8-zen3
hiftbn6                  ^zlib@1.2.12%gcc@11.2.0+optimize+pic+shared patches=0d38234 arch=linux-rhel8-zen3
myx5mku              ^ncurses@6.1.20180224%gcc@11.2.0~symlinks+termlib abi=6 arch=linux-rhel8-zen3
wdu5sij              ^tar@1.30%gcc@11.2.0 zip=pigz arch=linux-rhel8-zen3
7ouqbcl      ^cmake@3.18.2%gcc@11.2.0~doc+ncurses+ownlibs~qt build_type=Release patches=bf695e3 arch=linux-rhel8-zen3
exibdnp      ^hwloc@2.2.0%gcc@11.2.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm+shared arch=linux-rhel8-zen3
3w3pt46      ^libedit@3.1-20210216%gcc@11.2.0 arch=linux-rhel8-zen3
uomdyia      ^ninja@1.10.2%gcc@11.2.0 arch=linux-rhel8-zen3
pepf4b6      ^perl-data-dumper@2.173%gcc@11.2.0 arch=linux-rhel8-zen3
4hd374u          ^perl@5.34.1%gcc@11.2.0+cpanm+shared+threads arch=linux-rhel8-zen3
hfm4k4r              ^berkeley-db@18.1.40%gcc@11.2.0+cxx~docs+stl patches=b231fcc arch=linux-rhel8-zen3
5nndgyo              ^gdbm@1.19%gcc@11.2.0 arch=linux-rhel8-zen3
wrjusz5                  ^readline@8.1%gcc@11.2.0 arch=linux-rhel8-zen3
ws32j5o      ^python@3.6.8%gcc@11.2.0+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma+nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=c129e34 arch=linux-rhel8-zen3
ip4xm5k      ^swig@4.0.2%gcc@11.2.0 arch=linux-rhel8-zen3
soenpuf          ^pcre@8.45%gcc@11.2.0~jit+multibyte+utf arch=linux-rhel8-zen3
</pre>

### Error message

<details><summary>Error message</summary><pre>
[+] /u/arnoldg/delta/delta-2022-03/apps/perl-data-dumper/2.173-gcc-11.2.0-pepf4b6
==> Installing llvm-14.0.6-3nfs34w34m7n4jkzx4h2mmhj2yldmw4x
==> No binary for llvm-14.0.6-3nfs34w34m7n4jkzx4h2mmhj2yldmw4x found: installing from source
==> Using cached archive: /u/arnoldg/delta/spack_downloads/_source-cache/archive/98/98f15f842700bdb7220a166c8d2739a03a72e775b67031205078f39dd756a055.tar.gz
==> Applied patch /u/arnoldg/delta/spack/var/spack/repos/builtin/packages/llvm/llvm14-hwloc-ompd.patch
==> Applied patch /u/arnoldg/delta/spack/var/spack/repos/builtin/packages/llvm/libomp-libflags-as-list.patch
==> llvm: Executing phase: 'cmake'
==> llvm: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 1:
    'ninja' '-j16' '-v'

4 errors found in build log:
     43592    [412/441] Building CXX object openmp/runtime/src/CMakeFiles/omp.dir/thirdparty/it
              tnotify/ittnotify_static.cpp.o
     43593    [413/441] Building CXX object openmp/runtime/src/CMakeFiles/omp.dir/kmp_itt.cpp.o
     43594    [414/441] Building CXX object openmp/runtime/src/CMakeFiles/omp.dir/kmp_utility.c
              pp.o
     43595    [415/441] Building CXX object openmp/runtime/src/CMakeFiles/omp.dir/kmp_i18n.cpp.
              o
     43596    [416/441] Building CXX object openmp/runtime/src/CMakeFiles/omp.dir/kmp_error.cpp
              .o
     43597    [417/441] Building CXX object openmp/runtime/src/CMakeFiles/omp.dir/kmp_affinity.
              cpp.o
  >> 43598    FAILED: openmp/runtime/src/CMakeFiles/omp.dir/kmp_affinity.cpp.o
     43599    /tmp/arnoldg/spack-stage/spack-stage-llvm-14.0.6-3nfs34w34m7n4jkzx4h2mmhj2yldmw4x
              /spack-build-3nfs34w/./bin/clang++ --target=x86_64-unknown-linux-gnu -D__STDC_CON
              STANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Domp_EXPORTS -Iopenmp/
              runtime/src -I/tmp/arnoldg/spack-stage/spack-stage-llvm-14.0.6-3nfs34w34m7n4jkzx4
              h2mmhj2yldmw4x/spack-src/openmp/runtime/src -I/tmp/arnoldg/spack-stage/spack-stag
              e-llvm-14.0.6-3nfs34w34m7n4jkzx4h2mmhj2yldmw4x/spack-src/openmp/runtime/src/i18n 
              -I/tmp/arnoldg/spack-stage/spack-stage-llvm-14.0.6-3nfs34w34m7n4jkzx4h2mmhj2yldmw
              4x/spack-src/openmp/runtime/src/include -I/tmp/arnoldg/spack-stage/spack-stage-ll
              vm-14.0.6-3nfs34w34m7n4jkzx4h2mmhj2yldmw4x/spack-src/openmp/runtime/src/thirdpart
              y/ittnotify -std=c++11 -fPIC -fno-semantic-interposition -fvisibility-inlines-hid
              den -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unuse
              d-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-f
              allthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelet
              e-non-virtual-dtor -Wsuggest-override -Wno-comment -Wstring-conversion -Wmisleadi
              ng-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -Wall -Wca
              st-qual -Wformat-pedantic -Wimplicit-fallthrough -Wsign-compare -Wno-extra -Wno-p
              edantic -std=c++14 -O2 -DNDEBUG -fPIC   -D _GNU_SOURCE -D _REENTRANT -fno-excepti
              ons -fno-rtti -Wno-covered-switch-default -Wno-frame-address -Wno-strict-aliasing
               -Wno-switch -Wno-uninitialized -Wno-unused-but-set-variable -Wno-return-type-c-l
              inkage -Wno-cast-qual -Wno-int-to-void-pointer-cast -MD -MT openmp/runtime/src/CM
              akeFiles/omp.dir/kmp_affinity.cpp.o -MF openmp/runtime/src/CMakeFiles/omp.dir/kmp
              _affinity.cpp.o.d -o openmp/runtime/src/CMakeFiles/omp.dir/kmp_affinity.cpp.o -c 
              /tmp/arnoldg/spack-stage/spack-stage-llvm-14.0.6-3nfs34w34m7n4jkzx4h2mmhj2yldmw4x
              /spack-src/openmp/runtime/src/kmp_affinity.cpp
  >> 43600    /tmp/arnoldg/spack-stage/spack-stage-llvm-14.0.6-3nfs34w34m7n4jkzx4h2mmhj2yldmw4x
              /spack-src/openmp/runtime/src/kmp_affinity.cpp:1679:22: error: use of undeclared 
              identifier 'hwloc_cpukinds_get_nr'
     43601      int nr_cpu_kinds = hwloc_cpukinds_get_nr(tp, 0);
     43602                         ^
  >> 43603    /tmp/arnoldg/spack-stage/spack-stage-llvm-14.0.6-3nfs34w34m7n4jkzx4h2mmhj2yldmw4x
              /spack-src/openmp/runtime/src/kmp_affinity.cpp:1697:11: error: use of undeclared 
              identifier 'hwloc_cpukinds_get_info'
     43604          if (hwloc_cpukinds_get_info(tp, idx, cpukinds[idx].mask,
     43605              ^
     43606    /tmp/arnoldg/spack-stage/spack-stage-llvm-14.0.6-3nfs34w34m7n4jkzx4h2mmhj2yldmw4x
              /spack-src/openmp/runtime/src/kmp_affinity.cpp:1768:13: warning: using the result
               of an assignment as a condition without parentheses [-Wparentheses]
     43607      while (pu = hwloc_get_next_obj_by_type(tp, HWLOC_OBJ_PU, pu)) {
     43608             ~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     43609    /tmp/arnoldg/spack-stage/spack-stage-llvm-14.0.6-3nfs34w34m7n4jkzx4h2mmhj2yldmw4x
              /spack-src/openmp/runtime/src/kmp_affinity.cpp:1768:13: note: place parentheses a
              round the assignment to silence this warning

     ...

     43634    [434/441] Building CXX object openmp/runtime/src/CMakeFiles/omp.dir/kmp_atomic.cp
              p.o
     43635    [435/441] Building CXX object openmp/runtime/src/CMakeFiles/omp.dir/kmp_barrier.c
              pp.o
     43636    [436/441] Building CXX object openmp/runtime/src/CMakeFiles/omp.dir/kmp_dispatch.
              cpp.o
     43637    [437/441] Building CXX object openmp/runtime/src/CMakeFiles/omp.dir/kmp_runtime.c
              pp.o
     43638    [438/441] Building CXX object openmp/runtime/src/CMakeFiles/omp.dir/kmp_settings.
              cpp.o
     43639    ninja: build stopped: subcommand failed.
  >> 43640    FAILED: runtimes/runtimes-stamps/runtimes-build
     43641    cd /tmp/arnoldg/spack-stage/spack-stage-llvm-14.0.6-3nfs34w34m7n4jkzx4h2mmhj2yldm
              w4x/spack-build-3nfs34w/runtimes/runtimes-bins && /usr/bin/cmake --build .
     43642    ninja: build stopped: subcommand failed.

See build log for details:
  /tmp/arnoldg/spack-stage/spack-stage-llvm-14.0.6-3nfs34w34m7n4jkzx4h2mmhj2yldmw4x/spack-build-out.txt

[arnoldg@dt-login03 delta]$ 

</pre></details>

### Information on your system

[arnoldg@dt-login03 delta]$ spack debug report
* **Spack:** 0.19.0.dev0 (dac31ef3c405709aadd467eab21686f5a51930db)
* **Python:** 3.6.8
* **Platform:** linux-rhel8-zen3
* **Concretizer:** clingo

### Additional information

[arnoldg@dt-login03 delta]$ ls *.txt
ls: cannot access '*.txt': No such file or directory

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by kc9qey** [comment]
@haampie @trws

**Comment by kc9qey** [comment]
[spack-build-out.txt.gz](https://github.com/spack/spack/files/9064322/spack-build-out.txt.gz)

**Comment by kc9qey** [comment]
NCSA DELTA  , for search terms

**Comment by trws** [comment]
Looks like that interface was added in hwloc 2.4, probably need to up the required dependency version.  I'm not sure which version of LLVM introduced this. @kc9qey, does version 13 build for you with that hwloc version?

**Comment by kc9qey** [comment]
I ended up building llvm 15.0.0 externally and adding it to the setup via packages.yaml.  I'll try llvm@13.x and get back to you...

**Comment by kc9qey** [comment]
That worked.  I've got a path forward now to deploy a couple llvm into our production spack instances.
<pre>
[arnoldg@dt-login03 bin]$ spack find llvm
==> 2 installed packages
-- linux-rhel8-zen3 / gcc@11.2.0 --------------------------------
llvm@13.0.0  llvm@15.0.0
</pre>
Our hwloc is from the system OS
<pre>
[arnoldg@dt-login03 bin]$ grep --after-context=2 hwloc $SPACK_ROOT/etc/spack/packages.yaml 
  hwloc:
    buildable: false
    externals:
    - spec: hwloc@2.2.0
      prefix: /usr
</pre>

**Comment by trws** [comment]
Ok, so 14 and probably higher needs a newer hwloc.  Should be a pretty straightforward fix, any chance you're willing to throw up a PR?

**Comment by kc9qey** [comment]
No, I'm strictly on the user side of spack and not looking to do any of the git devel activity.  My day job is rich with complexity as it is.

**Comment by trws** [comment]
Ok, I'll try to get to it but it may take a bit before I can work it in.  Thanks for helping me track down what we need to specify.
