### ISSUE TITLE
Installation issue: gcc12.1.0

### ISSUE THREAD

**Issue by tagardiner** [LLNL/spack#31479]
### Steps to reproduce the issue

```console
$ spack spec -l gcc
Input spec
--------------------------------
gcc

Concretized
--------------------------------
a4e7g6r  gcc@12.1.0%apple-clang@13.1.6~binutils+bootstrap~graphite~nvptx~piclibs~strip build_type=RelWithDebInfo languages=c,c++,fortran arch=darwin-monterey-m1
jmjgb7g      ^diffutils@2.8.1%apple-clang@13.1.6 arch=darwin-monterey-m1
nf34hq3      ^gawk@5.1.1%apple-clang@13.1.6~nls arch=darwin-monterey-m1
fdddzrl          ^gmp@6.2.1%apple-clang@13.1.6 libs=shared,static arch=darwin-monterey-m1
t3s5iie              ^autoconf@2.69%apple-clang@13.1.6 patches=35c4492,7793209,a49dd5b arch=darwin-monterey-m1
kgshvzr                  ^gnuconfig@2021-08-14%apple-clang@13.1.6 arch=darwin-monterey-m1
eth24yk                  ^m4@1.4.6%apple-clang@13.1.6+sigsegv arch=darwin-monterey-m1
x2d5b32                  ^perl@5.34.1%apple-clang@13.1.6+cpanm+shared+threads arch=darwin-monterey-m1
cw5pmcf                      ^berkeley-db@18.1.40%apple-clang@13.1.6+cxx~docs+stl patches=b231fcc arch=darwin-monterey-m1
6gbjesr                      ^bzip2@1.0.8%apple-clang@13.1.6~debug~pic+shared arch=darwin-monterey-m1
2xcdch3                      ^gdbm@1.19%apple-clang@13.1.6 arch=darwin-monterey-m1
ai2j556                          ^readline@8.1%apple-clang@13.1.6 arch=darwin-monterey-m1
kuzl4os                              ^ncurses@6.2%apple-clang@13.1.6~symlinks+termlib abi=none arch=darwin-monterey-m1
xw7qdku                                  ^pkgconf@1.8.0%apple-clang@13.1.6 arch=darwin-monterey-m1
yyvdsop                      ^zlib@1.2.12%apple-clang@13.1.6+optimize+pic+shared patches=0d38234 arch=darwin-monterey-m1
zvm43tc              ^automake@1.16.5%apple-clang@13.1.6 arch=darwin-monterey-m1
jpaaqnh              ^libtool@2.4.7%apple-clang@13.1.6 arch=darwin-monterey-m1
kblhmvz          ^libsigsegv@2.13%apple-clang@13.1.6 arch=darwin-monterey-m1
3ej3a3o          ^mpfr@4.1.0%apple-clang@13.1.6 libs=shared,static arch=darwin-monterey-m1
rttxdkn              ^autoconf-archive@2022.02.11%apple-clang@13.1.6 patches=130cd48 arch=darwin-monterey-m1
5dqh4ij              ^texinfo@4.8%apple-clang@13.1.6 arch=darwin-monterey-m1
on55dof      ^libiconv@1.16%apple-clang@13.1.6 libs=shared,static arch=darwin-monterey-m1
2q5opfa      ^mpc@1.2.1%apple-clang@13.1.6 libs=shared,static arch=darwin-monterey-m1
vg2x7ka      ^zstd@1.5.2%apple-clang@13.1.6~programs libs=shared,static arch=darwin-monterey-m1

```

### Error message

<details><summary>Error message</summary><pre>

==> Ran patch() for gcc
==> gcc: Executing phase: 'autoreconf'
==> gcc: Executing phase: 'configure'
==> gcc: Executing phase: 'build'
==> [2022-07-07-00:15:30.833161] Error: ProcessError: Command exited with status 2:
    'make' '-j10' 'V=1'

3 errors found in build log:
     3644    checking for O_CLOEXEC... yes
     3645    checking for AF_UNIX... yes
     3646    checking for AF_INET6... yes
     3647    checking for _LK_LOCK... no
     3648    checking if mkdir takes one argument... no
     3649    *** Configuration aarch64-apple-darwin21.5.0 not supported
  >> 3650    make[2]: *** [configure-stage1-gcc] Error 1
  >> 3651    make[1]: *** [stage1-bubble] Error 2
  >> 3652    make: *** [all] Error 2

</pre></details>

### Information on your system

$ spack debug report
* **Spack:** 0.18.0 (c09bf37ff690c29779a342670cf8a171ad1b9233)
* **Python:** 3.10.5
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo

### Additional information

Maintainers: @alalazo @michaelkuhn 

[spack-build-out.txt](https://github.com/spack/spack/files/9064597/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/9064600/spack-build-env.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
This is confusing. We have a conflict for this:
```python
    conflicts('@:11.2,11.3.1:', when='target=aarch64: platform=darwin',                  
              msg='Only GCC 11.3.0 supports macOS M1 (aarch64)')          
```
This should tell Spack that it can only build `gcc@11.3.0`, so I'm not sure why it's trying to build `gcc@12.1.0`. It works properly on my M1 system. Seems like a concretization issue.

Anyway, workaround for now is to specify exactly which version of GCC you want to install:
```console
$ spack install gcc@11.3.0
```

**Comment by tagardiner** [comment]
That's interesting that you're suggesting the concretizer.  The very first challenge I ran into with spack on this system is that the first step of invoking $ spack spec python to bootstrap clingo fails.  A bit of experimentation showed that this was due to an issue with the system python3.  I installed python 3.10 from python.org, put that in my path and then was able to complete the bootstrap process.  Might this be related?

**Comment by adamjstewart** [comment]
Yeah, we don't yet have clingo binaries for M1 (@alalazo any updates on this?). Your solution is the correct approach. It shouldn't cause any issues as far as I know, and Spack seems to be correctly detecting the system as aarch64.

**Comment by tagardiner** [comment]
Ok, thanks

**Comment by tagardiner** [comment]
I started from a fresh clone of spack, switched to the v18.0 branch and I'm getting this error with gcc11.3.0.

[tagardi@s1083700: spack.2022.07.06]$ spack spec gcc@11.3.0
==> Error: Only GCC 12 and newer support macOS M1 (aarch64)

**Comment by adamjstewart** [comment]
Ah, that explains the issue then. You should use the develop branch, the v18.0 branch does not have great support for M1. GCC didn't support M1 until https://github.com/spack/spack/pull/30825.

**Comment by tagardiner** [comment]
I'm restarting the process with the develop branch now.  FWIW, I'm finding the following comment in the gcc package.py file.

    # aarch64/M1 is supported in GCC 12+
    conflicts('@:11.2,11.3.1:', when='target=aarch64: platform=darwin',
              msg='Only GCC 11.3.0 supports macOS M1 (aarch64)')

but the versions listed above in that file are 11.3.0 and 12.1.0.  The comment seems to indicate gcc 12.1.0 is good while the error message says only gcc 11.3.0 is good.  Is this conflicts statement supposed to be detecting 12.1.0?

I'm starting the build of gcc@11.3.0 now.

**Comment by adamjstewart** [comment]
Yep, the comment is outdated. GCC 12 was supposed to be the first release with support, but that PR was pulled at the last minute. Now we just have backports of patches to rely on

**Comment by tagardiner** [comment]
Ok, great - thanks for the help!
The build is running and I'll confirm success (hopefully) when it's done.

**Comment by tagardiner** [comment]
Argh...  Unfortunately it fails as well.  The failure error messages start with this
```
==> Installing gcc-11.3.0-fnr2wt5nxplhgkpcdpnzwe7wdtlawajc
==> No binary for gcc-11.3.0-fnr2wt5nxplhgkpcdpnzwe7wdtlawajc found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/b4/b47cf2818691f5b1e21df2bb38c795fac2cfbd640ede2d0a5e1c89e338a3ac39.tar.xz
==> Fetching https://raw.githubusercontent.com/Homebrew/formula-patches/22dec3fc/gcc/gcc-11.3.0-arm.diff
==> Applied patch https://raw.githubusercontent.com/Homebrew/formula-patches/22dec3fc/gcc/gcc-11.3.0-arm.diff
==> Ran patch() for gcc
==> gcc: Executing phase: 'autoreconf'
==> gcc: Executing phase: 'configure'
==> gcc: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j10' 'V=1'

157 errors found in build log:
     4881      /var/folders/tp/1v20xmk54z96j17gxqjrz_jr001pk6/T/tagardi/spack-s
               tage/spack-stage-gcc-11.3.0-fnr2wt5nxplhgkpcdpnzwe7wdtlawajc/spa
               ck-src/gcc/rtl.h:1229:38: note: expanded from macro 'RTL_CHECK2'
     4882      #define RTL_CHECK2(RTX, N, C1, C2)  ((RTX)->u.fld[N])
     4883                                           ^            ~
     4884      /var/folders/tp/1v20xmk54z96j17gxqjrz_jr001pk6/T/tagardi/spack-s
               tage/spack-stage-gcc-11.3.0-fnr2wt5nxplhgkpcdpnzwe7wdtlawajc/spa
               ck-src/gcc/rtl.h:444:5: note: array 'fld' declared here
     4885          rtunion fld[1];
     4886          ^
  >> 4887      /var/folders/tp/1v20xmk54z96j17gxqjrz_jr001pk6/T/tagardi/spack-s
               tage/spack-stage-gcc-11.3.0-fnr2wt5nxplhgkpcdpnzwe7wdtlawajc/spa
               ck-src/gcc/rtl.h:1475:10: /var/folders/tp/1v20xmk54z96j17gxqjrz_
               jr001pk6/T/tagardi/spack-stage/spack-stage-gcc-11.3.0-fnr2wt5nxp
               lhgkpcdpnzwe7wdtlawajc/spack-src/gcc/rtl.h
     4888      :    ^148523::10 :note:  expanded from macro 'XEXP'warning:
     4889      array index 2 is past the end of the array (which contains 1 ele
               ment) [-Warray-bounds]
     4890      #define XEXP(RTX, N)    (RTL_CHECK2 (RTX, N, 'e', 'u').rt_rtx)
     4891                               ^                ~
     4892      /var/folders/tp/1v20xmk54z96j17gxqjrz_jr001pk6/T/tagardi/spack-s
               tage/spack-stage-gcc-11.3.0-fnr2wt5nxplhgkpcdpnzwe7wdtlawajc/spa
               ck-src/gcc/rtl.h:  return XBBDEF (insn, 2);warning:
     4893      array index 1 is past the end of the array (which contains 1 ele
               ment) [-Warray-bounds]         ^             ~
```

**Comment by tagardiner** [comment]
I can copy the spack-build-{out, env}.txt files as well, but the output file is 68.5 MB.  Should I gzip it?

**Comment by adamjstewart** [comment]
Can you try `spack install gcc~bootstrap` and see if that makes a difference? For some reason I'm the only one who was able to build GCC on M1 without issue, others have reported that disabling bootstrap helps (#31179, #31189).

**Comment by tagardiner** [comment]
That worked!  Why did that work?

I'm really surprised because it selected gcc-11.3.0 even though I didn't qualify the install statement.  That is,

spack install gcc

tries to install gcc@12.1.0

and spack install gcc~bootstrap

installed gcc@11.3.0.  I did execute this directly after trying $spack install gcc@11.3.0, is that why?

Either way, SUCCESS!

**Comment by adamjstewart** [comment]
On develop if you don't specify the version it should pick 11.3.0 automatically since that's the only version that supports arm64.

**Comment by adamjstewart** [comment]
Closing since this is fixed in develop, let me know fi you encounter any other build issues.

**Comment by krcb** [comment]
> That worked! Why did that work?
> 
> I'm really surprised because it selected gcc-11.3.0 even though I didn't qualify the install statement. That is,
> 
> spack install gcc
> 
> tries to install gcc@12.1.0
> 
> and spack install gcc~bootstrap
> 
> installed gcc@11.3.0. I did execute this directly after trying $spack install gcc@11.3.0, is that why?
> 
> Either way, SUCCESS!



> Argh... Unfortunately it fails as well. The failure error messages start with this
> 
> ```
> ==> Installing gcc-11.3.0-fnr2wt5nxplhgkpcdpnzwe7wdtlawajc
> ==> No binary for gcc-11.3.0-fnr2wt5nxplhgkpcdpnzwe7wdtlawajc found: installing from source
> ==> Fetching https://mirror.spack.io/_source-cache/archive/b4/b47cf2818691f5b1e21df2bb38c795fac2cfbd640ede2d0a5e1c89e338a3ac39.tar.xz
> ==> Fetching https://raw.githubusercontent.com/Homebrew/formula-patches/22dec3fc/gcc/gcc-11.3.0-arm.diff
> ==> Applied patch https://raw.githubusercontent.com/Homebrew/formula-patches/22dec3fc/gcc/gcc-11.3.0-arm.diff
> ==> Ran patch() for gcc
> ==> gcc: Executing phase: 'autoreconf'
> ==> gcc: Executing phase: 'configure'
> ==> gcc: Executing phase: 'build'
> ==> Error: ProcessError: Command exited with status 2:
>     'make' '-j10' 'V=1'
> 
> 157 errors found in build log:
>      4881      /var/folders/tp/1v20xmk54z96j17gxqjrz_jr001pk6/T/tagardi/spack-s
>                tage/spack-stage-gcc-11.3.0-fnr2wt5nxplhgkpcdpnzwe7wdtlawajc/spa
>                ck-src/gcc/rtl.h:1229:38: note: expanded from macro 'RTL_CHECK2'
>      4882      #define RTL_CHECK2(RTX, N, C1, C2)  ((RTX)->u.fld[N])
>      4883                                           ^            ~
>      4884      /var/folders/tp/1v20xmk54z96j17gxqjrz_jr001pk6/T/tagardi/spack-s
>                tage/spack-stage-gcc-11.3.0-fnr2wt5nxplhgkpcdpnzwe7wdtlawajc/spa
>                ck-src/gcc/rtl.h:444:5: note: array 'fld' declared here
>      4885          rtunion fld[1];
>      4886          ^
>   >> 4887      /var/folders/tp/1v20xmk54z96j17gxqjrz_jr001pk6/T/tagardi/spack-s
>                tage/spack-stage-gcc-11.3.0-fnr2wt5nxplhgkpcdpnzwe7wdtlawajc/spa
>                ck-src/gcc/rtl.h:1475:10: /var/folders/tp/1v20xmk54z96j17gxqjrz_
>                jr001pk6/T/tagardi/spack-stage/spack-stage-gcc-11.3.0-fnr2wt5nxp
>                lhgkpcdpnzwe7wdtlawajc/spack-src/gcc/rtl.h
>      4888      :    ^148523::10 :note:  expanded from macro 'XEXP'warning:
>      4889      array index 2 is past the end of the array (which contains 1 ele
>                ment) [-Warray-bounds]
>      4890      #define XEXP(RTX, N)    (RTL_CHECK2 (RTX, N, 'e', 'u').rt_rtx)
>      4891                               ^                ~
>      4892      /var/folders/tp/1v20xmk54z96j17gxqjrz_jr001pk6/T/tagardi/spack-s
>                tage/spack-stage-gcc-11.3.0-fnr2wt5nxplhgkpcdpnzwe7wdtlawajc/spa
>                ck-src/gcc/rtl.h:  return XBBDEF (insn, 2);warning:
>      4893      array index 1 is past the end of the array (which contains 1 ele
>                ment) [-Warray-bounds]         ^             ~
> ```

@tagardiner @adamjstewart I am seeing this same error attempting to build gcc@11.3.0 on OSX x86 (clang@14.0.0). @tagardiner solution of building with bootstrapping doesn't appear to address this specific error. @adamjstewart are you aware of a patch that would fix this?

**Comment by adamjstewart** [comment]
GCC does not build with Apple Clang 14.0.0 at the moment: https://github.com/iains/gcc-12-branch/issues/6

I added a conflict to warn about this in #32702. Hopefully Apple will fix the linker bug soon. For now, if you need a Fortran compiler on macOS, I would either use Homebrew or DMG installers.
