### ISSUE TITLE
Installation issue: Error: Package 'armpl' not found

### ISSUE THREAD

**Issue by Billae** [LLNL/spack#31489]
### Steps to reproduce the issue

Hello,
I try to install paraview but there is an error with the concretization:

```console
$ spack spec -I paraview
==> Error: Package 'armpl' not found.
```

I take a look on this and there is a lot of packages with the same error: python, mesa, llvm and so on.

I found the merge wich (i think) created this:
https://github.com/spack/spack/pull/31437

However I don't understand: when I make a grep on "armpl" in my local copy I don't see any package which depends on armpl (or armplgcc with this new name).

maybe @tldahlgren you know something ? :)

### Error message

```
spack spec -I mesa
==> Error: Package 'armpl' not found.

```

### Information on your system

I work on my computer with ubuntu 18.04 and with the develop branch with the last commit (ec7513c8b)

```
$ spack debug report
* **Spack:** 0.19.0.dev0 (ec7513c8b51a2e9ef2443895a95089019b6d768f)
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-skylake
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
It's a cache issue `spack clean -m` should fix it. But there should also be a proper fix to automatically purge stale cache.

**Comment by haampie** [comment]
Duplicate #31453
