### ISSUE TITLE
alquimia install not working

### ISSUE THREAD

**Issue by amklinv** [LLNL/spack#3148]
@tgamblin @BarrySmith 

I recently added an alquimia package to the barry/xsdk branch, but it's not working.  The alquimia install depends on the environment variables PETSC_ARCH and PETSC_DIR, which obviously don't exist.  How can we record that information, generated during the PETSc install, for later use in the alquimia install?

**Comment by davydden** [comment]
just set `PETSC_DIR` to `spec['petsc'].prefix` and `PETSC_ARCH` is empty.

**Comment by adamjstewart** [comment]
You shouldn't need to do anything fancy. If you depend on `petsc`, it sets `PETSC_DIR` in `setup_dependent_environment`. From my conversation with @BarrySmith I was under the impression that `PETSC_ARCH` should never be set, so we explicitly unset it.

**Comment by davydden** [comment]
> I recently added an alquimia package to the barry/xsdk branch, but it's not working

is the branch rebased on top of `develop` (or `develop` is merged into it)? 

@adamjstewart is right, there is this part of the code in the current `develop`:
```
    def setup_dependent_environment(self, spack_env, run_env, dependent_spec):
        # Set up PETSC_DIR for everyone using PETSc package
        spack_env.set('PETSC_DIR', self.prefix)
        spack_env.unset('PETSC_ARCH')
```
so no need to do anything.

**Comment by tgamblin** [comment]
@amklinv: note that the `setup_dependent_environment` method pasted here sets `PETSC_DIR` for Spack builds (i.e., in `spack_env`) but not for PETSc's module file or for module files that depend on it (that would be `run_env`).
