### ISSUE TITLE
Concretizer: reuse broken for external packages

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#31484]
### Steps to reproduce

First, blow away `~/.spack`, clone a fresh copy of Spack, and check for external packages:
```console
$ git clone https://github.com/spack/spack.git
$ . spack/share/spack/setup-env.sh
$ spack external find --not-buildable
```
This will register all external packages it finds on the system in `packages.yaml`. We'll focus on git since it's guaranteed to be found, but this affects all external packages.

Next, install git:
```console
$ spack install git
[+] /usr (external git-2.32.1-lweosdwarje645t4pqta7becf7n5dwbc)
$ spack find -l git
==> 1 installed package
-- darwin-monterey-m1 / apple-clang@13.1.6 ----------------------
lweosdw git@2.32.1
[12:52:36] ajstewart@ajstewart-mbp:~
$ spack spec -Il --reuse git
Input spec
--------------------------------
 -   git

Concretized
--------------------------------
[+]  lweosdw  git@2.32.1%apple-clang@13.1.6+man+nls+perl+subtree~svn~tcltk arch=darwin-monterey-m1
```
Next, modify the git package. For example, add a new variable:
```diff
diff --git a/var/spack/repos/builtin/packages/git/package.py b/var/spack/repos/builtin/packages/git/package.py
index 2d9a7a06f1..71d8d3e6c3 100644
--- a/var/spack/repos/builtin/packages/git/package.py
+++ b/var/spack/repos/builtin/packages/git/package.py
@@ -18,6 +18,7 @@ class Git(AutotoolsPackage):
     homepage = "http://git-scm.com"
     url      = "https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.12.0.tar.gz"
     maintainers = ['jennfshr']
+    foo = 'bar'
 
     tags = ['build-tools']
```
Now, Spack will no longer be able to reuse the existing git installation:
```console
$ spack spec -Il --reuse git
Input spec
--------------------------------
 -   git

Concretized
--------------------------------
 -   634kih5  git@2.32.1%apple-clang@13.1.6+man+nls+perl+subtree~svn~tcltk arch=darwin-monterey-m1

$ spack install --reuse git
[+] /usr (external git-2.32.1-634kih5iv3oxsqem6mrsz75t3zkdwxml)
```
This introduces a lot of inconsistencies in the database. `spack find` claims to only find a single installation, but `spack uninstall` begs to differ:
```
$ spack find -l git
==> 1 installed package
-- darwin-monterey-m1 / apple-clang@13.1.6 ----------------------
lweosdw git@2.32.1
$ spack uninstall git
==> Error: git matches multiple packages:

    -- darwin-monterey-m1 / apple-clang@13.1.6 ----------------------
    lweosdw git@2.32.1  634kih5 git@2.32.1

==> Error: You can either:
    a) use a more specific spec, or
    b) specify the spec by its hash (e.g. `spack uninstall /hash`), or
    c) use `spack uninstall --all` to uninstall ALL matching specs.
```
This also has a recursive effect. If a single package in the DAG is modifed and another package in the DAG is external, Spack will reinstall the modified package and anything that depends on it. Effectively, this means that `--reuse` no longer works if you use external packages and update Spack on occasion.

This is particularly problematic on macOS because many packages depend on `unwind` and `uuid` and Spack ships with a `packages.yaml` that registers these as external. Since Python depends on `uuid`, Spack reinstalls all of my Python libraries any time any file is modified, just like in the days before `--reuse` was added, but worse because we now use a full hash.

### Information on your system

* **Spack:** 0.19.0.dev0 (a12ce9fd59c32e650b43610925e454322995a81d)
* **Python:** 3.9.12
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo

@tgamblin @alalazo 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Confirmed the bug

**Comment by alalazo** [comment]
The issue stems from how we derive the `external_spec_selected` atom. Currently that doesn't take into account if a spec is reused by hash:
https://github.com/spack/spack/blob/0e783b2c47ec1dc36e3356b5c1038c1c014f6478/lib/spack/spack/solver/concretize.lp#L479-L481

As it stands, this rule never allow reuse of "installed" external specs. Even without the change in the `package.py`, that causes a change in the hash and makes everything evident, one can see that for `clingo` an external is always "built" and never "reused". 

This diff seems to solve the issue:
```diff
diff --git a/lib/spack/spack/solver/concretize.lp b/lib/spack/spack/solver/concretize.lp
index 3b264d7bfd..e70aef6d4f 100644
--- a/lib/spack/spack/solver/concretize.lp
+++ b/lib/spack/spack/solver/concretize.lp
@@ -478,7 +478,8 @@ external(Package) :- external_spec_selected(Package, _).
 % determine if an external spec has been selected
 external_spec_selected(Package, LocalIndex) :-
     external_conditions_hold(Package, LocalIndex),
-    node(Package).
+    node(Package),
+    not hash(Package, _).
 
 external_conditions_hold(Package, LocalIndex) :-
     possible_external(ID, Package, LocalIndex), condition_holds(ID).
@@ -1197,7 +1198,7 @@ opt_criterion(5, "version badness").
 #minimize{ 0@5: #true }.
 #minimize{
     Weight@5+Priority,Package
-    : version_weight(Package, Weight),
+    : version_weight(Package, Weight), not root(Package),
       build_priority(Package, Priority)
 }.
```
even though a better approach long term would be to treat externals differently (ideally, register them in the DB directly and avoid all the custom logic we have now)
