### ISSUE TITLE
Cannot build python

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#315]
When building the `python` Spack package, I received the following error on a particular Caltech HPC system:
```
==> Staging archive: /home/eschnett/src/spack/var/spack/stage/python-2.7.11-rv374hyypimz5g67e3psgarihvu7d6i7/Python-2.7.11.tar.xz
/bin/tar: This does not look like a tar archive
/bin/tar: Skipping to next header
/bin/tar: Archive contains obsolescent base-64 headers
/bin/tar: Read 9956 bytes from /home/eschnett/src/spack/var/spack/stage/python-2.7.11-rv374hyypimz5g67e3psgarihvu7d6i7/Python-2.7.11.tar.xz
/bin/tar: Error exit delayed from previous errors
==> Error: Command exited with status 2:
```

I assume this means that the version of `tar` installed there does not support the `xz` format. Remedies are either
- Install a modern GNU tar, and use it
- Download a different version of the Python tarball, e.g. a `gz` package

**Comment by eschnett** [comment]
I just see that several other packages also download an `xz` tarball. This might require a general policy. I don't think that download times and tarball disk space is critical, so using `gz` tarballs may be the easiest thing to do.

**Comment by tgamblin** [comment]
Using gz would be fine for now... I'd really like spack to just download and install a decent version of tar but that is more work and we should wait on it until I add support for build deoendencies.  If you want to change it to use gz that would be great.
