### ISSUE TITLE
SPACK_DEBUG=TRUE is broken

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#3152]
This mechanism (implemented in spack's `cc` wrapper) chooses a log file name that contains `SPACK_SHORT_SPEC`, which is a weird file name containing (among other things) a slash character for the hash. This is an illegal file name, pointing to a directory that does not exist.

We could e.g. replace the slash by an equals sign.

**Comment by eschnett** [comment]
Also, if the log is placed into the build directory, then there's no need to use the Spack spec.

**Comment by adamjstewart** [comment]
Is this the same problem reported in #3144?

**Comment by eschnett** [comment]
Yes, this seems to be the same problem.
