### ISSUE TITLE
LLVM build via Ninja doesn't respect -j

### ISSUE THREAD

**Issue by ye-luo** [LLNL/spack#31531]
### Steps to reproduce

```console
$ spack install -j 1 llvm
```
`-j 1` is not propagated/translated to Ninja and `top` shows parallel building.

spack-build-02-build-out.txt
```
==> llvm: Executing phase: 'build'
==> [2022-07-11-20:35:05.109686] 'ninja' '-v'
```

Since https://github.com/spack/spack/pull/27521

### Error message

OOM kills GCC in dmesg.

### Information on your system

Building LLVM on Raspberry Pi 4B 4GB memory

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
@haampie @trws fyi

**Comment by haampie** [comment]
This is fixed I believe
