### ISSUE TITLE
Installation issue: gdb on Apple Monterey M1

### ISSUE THREAD

**Issue by tagardiner** [LLNL/spack#31579]
### Steps to reproduce the issue

```console
$ spack spec -l gdb+source-highlight+tui
Input spec
--------------------------------
gdb+source-highlight+tui

Concretized
--------------------------------
qeycnak  gdb@11.2%apple-clang@13.1.6~gold~ld~lto+python~quad+source-highlight+tui+xz patches=7590c95 arch=darwin-monterey-m1
445ljdx      ^gmp@6.2.1%apple-clang@13.1.6 libs=shared,static arch=darwin-monterey-m1
y7bfquh          ^autoconf@2.69%apple-clang@13.1.6 patches=35c4492,7793209,a49dd5b arch=darwin-monterey-m1
6ge5mev              ^gnuconfig@2021-08-14%apple-clang@13.1.6 arch=darwin-monterey-m1
hclwv4x              ^m4@1.4.6%apple-clang@13.1.6+sigsegv arch=darwin-monterey-m1
jtliqzx              ^perl@5.34.1%apple-clang@13.1.6+cpanm+shared+threads arch=darwin-monterey-m1
e5dqqjq                  ^berkeley-db@18.1.40%apple-clang@13.1.6+cxx~docs+stl patches=b231fcc arch=darwin-monterey-m1
pn7g2gl                  ^bzip2@1.0.8%apple-clang@13.1.6~debug~pic+shared arch=darwin-monterey-m1
pfdmkku                      ^diffutils@2.8.1%apple-clang@13.1.6 arch=darwin-monterey-m1
chvvbrt                  ^gdbm@1.19%apple-clang@13.1.6 arch=darwin-monterey-m1
ua734bl                      ^readline@8.1.2%apple-clang@13.1.6 arch=darwin-monterey-m1
muw42gz                          ^ncurses@6.2%apple-clang@13.1.6~symlinks+termlib abi=none arch=darwin-monterey-m1
ett7ygi                              ^pkgconf@1.8.0%apple-clang@13.1.6 arch=darwin-monterey-m1
ke4alug                  ^zlib@1.2.12%apple-clang@13.1.6+optimize+pic+shared patches=0d38234 arch=darwin-monterey-m1
tynizn7          ^automake@1.16.5%apple-clang@13.1.6 arch=darwin-monterey-m1
gbgb5q3          ^libtool@2.4.7%apple-clang@13.1.6 arch=darwin-monterey-m1
utpeigz      ^python@3.9.13%apple-clang@13.1.6+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93,4c24573,f2fd060 arch=darwin-monterey-m1
jbbx4ar          ^apple-libuuid@1353.100.2%apple-clang@13.1.6 arch=darwin-monterey-m1
f5zknwn          ^expat@2.4.8%apple-clang@13.1.6~libbsd arch=darwin-monterey-m1
kuoooxg          ^gettext@0.21%apple-clang@13.1.6+bzip2+curses+git~libunistring+libxml2+tar+xz arch=darwin-monterey-m1
fh6dfpn              ^libiconv@1.16%apple-clang@13.1.6 libs=shared,static arch=darwin-monterey-m1
ozh3lkm              ^libxml2@2.9.13%apple-clang@13.1.6~python arch=darwin-monterey-m1
gv3m23p                  ^xz@5.2.5%apple-clang@13.1.6~pic libs=shared,static arch=darwin-monterey-m1
7aofrg3              ^tar@1.34%apple-clang@13.1.6 zip=pigz arch=darwin-monterey-m1
zzd6h23                  ^pigz@2.7%apple-clang@13.1.6 arch=darwin-monterey-m1
cx7gkqf                  ^zstd@1.5.2%apple-clang@13.1.6+programs compression=none libs=shared,static arch=darwin-monterey-m1
rjvdm33          ^libffi@3.4.2%apple-clang@13.1.6 arch=darwin-monterey-m1
ksmzwby          ^openssl@1.1.1p%apple-clang@13.1.6~docs~shared certs=mozilla arch=darwin-monterey-m1
u5bzvfg              ^ca-certificates-mozilla@2022-03-29%apple-clang@13.1.6 arch=darwin-monterey-m1
b567lts          ^sqlite@3.38.5%apple-clang@13.1.6+column_metadata+dynamic_extensions+fts~functions+rtree arch=darwin-monterey-m1
oqsyiv4      ^source-highlight@3.1.9%apple-clang@13.1.6 arch=darwin-monterey-m1
n7rh6is          ^boost@1.79.0%apple-clang@13.1.6~atomic~chrono~clanglibcpp~container~context~contract~coroutine~date_time~debug+exception~fiber~filesystem~graph~graph_parallel~icu~iostreams~json~locale~log~math~mpi+multithreaded~nowide~numpy~pic~program_options~python~random+regex~serialization+shared~signals~singlethreaded~stacktrace~system~taggedlayout~test~thread~timer~type_erasure~versionedlayout~wave cxxstd=98 patches=a440f96 visibility=hidden arch=darwin-monterey-m1
fa4xmbb      ^texinfo@4.8%apple-clang@13.1.6 arch=darwin-monterey-m1
```

### Error message

<details><summary>Error message</summary><pre>
==> Installing gdb-11.2-qeycnak34y3hjgqsquf3k5u4kmh2g3gh
==> No binary for gdb-11.2-qeycnak34y3hjgqsquf3k5u4kmh2g3gh found: installing from source
==> Using cached archive: /Users/tagardi/opt/spack.2022.07.06/var/spack/cache/_source-cache/archive/b5/b558b66084835e43b6361f60d60d314c487447419cdf53adf83a87020c367290.tar.gz
==> Applied patch /Users/tagardi/opt/spack.2022.07.06/var/spack/repos/builtin/packages/gdb/gdb-libintl-11.patch
==> gdb: Executing phase: 'autoreconf'
==> gdb: Executing phase: 'configure'
==> gdb: Executing phase: 'build'
==> gdb: Executing phase: 'install'
==> gdb: Successfully installed gdb-11.2-qeycnak34y3hjgqsquf3k5u4kmh2g3gh
  Fetch: 0.02s.  Build: 1m 8.67s.  Total: 1m 8.69s.
[+] /Users/tagardi/opt/spack.2022.07.06/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/gdb-11.2-qeycnak34y3hjgqsquf3k5u4kmh2g3gh
</pre></details>

### Information on your system

$ spack debug report
* **Spack:** 0.19.0.dev0 (44b48cfe46d05c1bd5fd2ceb51b8884089cb4fe3)
* **Python:** 3.10.5
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo

### Additional information

$ spack maintainers gdb
@robertu94

The build and install completes successfully, however, the executable is not installed.  I can't locate the build log files.  I'm assuming they were cleaned up.  Is there a way to tell spack not to clean up?

$ cd /Users/tagardi/opt/spack.2022.07.06/opt/spack/darwin-monterey-m1/apple-clang-13.1.6/gdb-11.2-qeycnak34y3hjgqsquf3k5u4kmh2g3gh
[tagardi@s1083700: gdb-11.2-qeycnak34y3hjgqsquf3k5u4kmh2g3gh]$ ls
etc     include lib     share
[tagardi@s1083700: gdb-11.2-qeycnak34y3hjgqsquf3k5u4kmh2g3gh]$ ls *
etc:
gdbinit

include:
ansidecl.h    bfdlink.h     ctf.h         dis-asm.h     symcat.h
bfd.h         ctf-api.h     diagnostics.h plugin-api.h

lib:
libbfd.a       libctf-nobfd.a libctf.a       libopcodes.a

share:
info   locale

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by William-Mou** [comment]
This is not the problem of spack
Unfortunately, GDB does not yet support **M1 chips**.

You can build it successfully (without failure), but the GDB executable will not be built.
Maybe use `lldb` debug directly!

ref: https://formulae.brew.sh/formula/gdb#default

**Comment by tagardiner** [comment]
Ah, I see.  Sorry for bringing up a non-issue, and thanks!

**Comment by tagardiner** [comment]
I'm assuming that I should close this issue, since I opened it and it's not a spack problem.
Thanks Again!
