### ISSUE TITLE
Installing python packages with "non-standard" python install

### ISSUE THREAD

**Issue by BarrySmith** [LLNL/spack#3163]
```
$ ./bin/spack install  py-mpi4py
==> Installing py-mpi4py
==> python is externally installed in /usr/bin
==> openmpi is externally installed in /usr/local
==> Installing py-setuptools
==> python is externally installed in /usr/bin
==> Using cached archive: /Users/barrysmith/Src/spack/var/spack/cache/py-setuptools/py-setuptools-25.2.0.tar.gz
==> Already staged py-setuptools-25.2.0-wtwwb2ylkss2ajlglap5yjr4ynulufqu in /Users/barrysmith/Src/spack/var/spack/stage/py-setuptools-25.2.0-wtwwb2ylkss2ajlglap5yjr4ynulufqu
==> No patches needed for py-setuptools
==> Building py-setuptools [PythonPackage]
==> Executing phase : 'build'
==> Error: ProcessError: /usr/bin/bin/python: No such file or directory
    Command: '/usr/bin/bin/python' 'setup.py' '--no-user-cfg' 'build'
/Users/barrysmith/Src/spack/lib/spack/spack/build_systems/python.py:110, in python:
     109      def python(self, *args):
  >> 110          inspect.getmodule(self).python(*args)

See build log for details:
  /private/var/folders/c1/ldz_dt8n2r3dtwv_chp5pfr40000gn/T/barrysmith/spack-stage/spack-stage-Q3uxMF/setuptools-25.2.0/spack-build.out
~/Src/spack (develop=) arch-basic
```

```
$ which python
/usr/local/bin/python
```

In my .spack/packages.yaml file I have 

```
    python:
        paths:
            python@2.7.1: /usr/bin
        buildable: False  
```      

Note it is a different python.

/Users/barrysmith/Src/spack/lib/spack/spack/build_systems/python.py is using some information from the "front end python" (the python I am running spack with) and some information from the "back end python" the python that spack is installing packages for to generate an incorrect location of the python executable. 

Given your complicated way of overlaping .python(args) to execute the python script I cannot figure out how to debug and fix the problem. 

 Note that this is similar to the bug I fixed in https://github.com/LLNL/spack/pull/2173 but different and my fix only resolves the problem in that one place.

**Comment by adamjstewart** [comment]
What happens when you use:
```yaml
python:
  paths:
    python@2.7.1: /usr
  buildable: False
```

**Comment by BarrySmith** [comment]
Closing the issue since it may not be true. I can't find a way to totally delete a bad issue.

**Comment by adamjstewart** [comment]
If you run into it again, my solution above should fix it. The paths should be the installation directory, not the bin directory. You can tell based on the fact that it's looking for `/usr/bin/bin/python`.
