### ISSUE TITLE
Installation issue: Binary libffi fails checksum verification

### ISSUE THREAD

**Issue by stephenmsachs** [LLNL/spack#31640]
### Steps to reproduce the issue

```
# On develop branch
spack mirror add binary_mirror  https://binaries.spack.io/releases/v0.18
spack buildcache keys --install --trust
spack -vvv install /d6d3lh3
```

### Error message

==> Installing libffi-3.4.2-d6d3lh3hgkjwbifbbjuvqs2a3w5xj7pd
==> Fetching https://binaries.spack.io/releases/v0.18/build_cache/linux-amzn2-x86_64_v4-gcc-7.3.1-libffi-3.4.2-d6d3lh3hgkjwbifbbjuvqs2a3w5xj7pd.spec.json.sig
gpg: Signature made Tue 31 May 2022 07:27:40 AM UTC using RSA key ID 3DB0C723
gpg: Good signature from "Spack Project Official Binaries <maintainers@spack.io>"
==> Fetching https://binaries.spack.io/releases/v0.18/build_cache/linux-amzn2-x86_64_v4/gcc-7.3.1/libffi-3.4.2/linux-amzn2-x86_64_v4-gcc-7.3.1-libffi-3.4.2-d6d3lh3hgkjwbifbbjuvqs2a3w5xj7pd.spack
==> Extracting libffi-3.4.2-d6d3lh3hgkjwbifbbjuvqs2a3w5xj7pd from binary cache
==> Error: Failed to install libffi due to NoChecksumException: Package tarball failed checksum verification.
It cannot be installed.

### Information on your system

[ec2-user@ip-10-7-228-156 ~]$ spack debug report
* **Spack:** 0.19.0.dev0 (b065d69136023693ace8e4d35d9fdad817d63d93)
* **Python:** 3.7.10
* **Platform:** linux-amzn2-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by stephenmsachs** [comment]
I proposed a fix to automatically build from source on these errors as I guess they are transient in nature anyway. Today `libffi` donwloads fine, but `py-pip` throws this exception.

**Comment by cameronrutherford** [comment]
#31941 seems similar to this issue. Is consistent with there sometimes being different packages that feel like failing with NoCheckSumException - perhaps I should have piled on this issue, but I wanted to document all of the failures I was seeing as well
