### ISSUE TITLE
Desired package shows up in Spack Package list website but not found in terminal.

### ISSUE THREAD

**Issue by RylanYancey** [LLNL/spack#31663]
### Steps to reproduce

I'm trying to install Cutlass Nvidia library using Spack. 

I've installed Spack via their instructions online and ran "spack install cuda" to install the cuda toolkit beforehand. I then went and used "spack install cutlass".

Cutlass exists on Spack's website, and when I run "spack list", cutlass is not there. 

### Error message

```console
ryancey@Calculator:~/spack$ spack install cutlass                                                                       
==> Error: Package 'cutlass' not found.    
```
```console
ryancey@Calculator:~/spack$ spack list 'cutlass'
==> 0 packages.
```

### Information on your system

I'm using WSL - Ubuntu - 20.04 under a Windows 11 installation. I just installed WSL on this machine and installed GCC, G++, and CMAKE prior to installing spack. 

Spack: 0.18.1
Python: 3.8.10
Platform: linux-ubuntu20.04-zen2
Concretizer: clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
You are viewing the docs for the develop version but using the 0.18.1 release. Cutlass was added in #31379 which was merged after the 0.18 release. You'll have to upgrade to a more recent commit if you want to use that package, or wait for the 0.19 release.
