### ISSUE TITLE
Cannot install cmake via https

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#317]
On a particular system I receive this error message when installing cmake:
```
==> Trying to fetch from https://cmake.org/files/v3.4/cmake-3.4.0.tar.gz
curl: (51) SSL: certificate subject name '*.kitware.com' does not match target host name 'cmake.org'
==> Fetching from https://cmake.org/files/v3.4/cmake-3.4.0.tar.gz failed.
==> Error: All fetchers failed for cmake-3.4.0-eksdikpvslk72amnq7uy5jijjix3ej5s
eschnett@zwicky:~/src/spack (18:34:22)
```

I assume this means that spack wants to use an `https` url to download `cmake`, and fails because the `cmake.org` SSL certificate has problems (or because this system's SSL library is too old).

However, `cmake`'s package file lists all urls as `http`, not as `https`. Is Spack rewriting urls to use `https`? Why would it do so? As Spack also verifies checksums, I don't see much point in using `https` over using `http`.

**Comment by tgamblin** [comment]
Fixed by 4bab6f9
