### ISSUE TITLE
Spack test issue: heffte

### ISSUE THREAD

**Issue by SamBosch77** [LLNL/spack#31702]
### Steps to reproduce the issue

```console
$ spack load heffte
$ spack test run heffte
```

### Error message

<details><summary>Error message</summary><pre>
==> Spack test mpwxbgnv6ksqs5ogbrlhhqw5g23kpjnn
==> Testing package heffte-2.2.0-hi4m7gs
==> Error: ProcessError: Command exited with status 1:
    'cmake' '/storage/users/sbosch/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/heffte-2.2.0-hi4m7gstg27vrdxo4hxreewbrdicusm7/share/heffte/testing'

1 error found in test log:
     4     -- Detecting CXX compiler ABI info
     5     -- Detecting CXX compiler ABI info - done
     6     -- Check for working CXX compiler: /storage/users/sbosch/spack/lib/spack/env/gcc/g++ - skipped
     7     -- Detecting CXX compile features
     8     -- Detecting CXX compile features - done
     9     -- heFFTe post-installation testing
  >> 10    CMake Error at /storage/users/sbosch/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-9.4.0/cmake-3.23.1-y3d2cjiwv2qc
           y65ljekhm5h6ljw5kj2n/share/cmake-3.23/Modules/CMakeFindDependencyMacro.cmake:47 (find_package):
     11      By not providing "Findamd_comgr.cmake" in CMAKE_MODULE_PATH this project
     12      has asked CMake to find a package configuration file provided by
     13      "amd_comgr", but CMake did not find one.
     14
     15      Could not find a package configuration file provided by "amd_comgr" with
     16      any of the following names:

See test log for details:
  /home/users/sbosch/.spack/test/mpwxbgnv6ksqs5ogbrlhhqw5g23kpjnn/heffte-2.2.0-hi4m7gs-test-out.txt

======================== 1 failed, 0 passed of 1 specs =========================
==> Error: 1 test(s) in the suite failed.
</pre></details>

### Information on your system

* **Spack:** 0.18.0 (c09bf37ff690c29779a342670cf8a171ad1b9233)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-broadwell
* **Concretizer:** clingo

### Additional information

[CMakeOutput.log](https://github.com/spack/spack/files/9172648/CMakeOutput.log)
[heffte-2.2.0-hi4m7gs-test-out.txt](https://github.com/spack/spack/files/9172649/heffte-2.2.0-hi4m7gs-test-out.txt)
[spack_find_-dvl_heffte_output.txt](https://github.com/spack/spack/files/9172694/spack_find_-dvl_heffte_output.txt)

@mkstoyanov
@wspear

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by mkstoyanov** [comment]
Fixed in #33390

**Comment by mkstoyanov** [comment]
The fix was merged in https://github.com/spack/spack/pull/33536
