### ISSUE TITLE
build dependency changes hash (ninja^python)

### ISSUE THREAD

**Issue by melven** [LLNL/spack#31716]
### Steps to reproduce

```console
$ spack spec -lt ninja^python@3.9.1
Input spec
--------------------------------
[    ]  ninja
[    ]      ^python@3.9.1

Concretized
--------------------------------
jugtnbl  [    ]  ninja@1.10.2%gcc@12.1.0 arch=linux-ubuntu20.04-x86_64_v3
cboatoj  [b   ]      ^python@3.9.1%gcc@12.1.0+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93,4c24573,f2fd060 arch=linux-ubuntu20.04-x86_64_v3
[...]
$ 
--------------------------------
[    ]  ninja
[    ]      ^python@3.9.2

Concretized
--------------------------------
b4mlafv  [    ]  ninja@1.10.2%gcc@12.1.0 arch=linux-ubuntu20.04-x86_64_v3
ndozxrc  [b   ]      ^python@3.9.2%gcc@12.1.0+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93,4c24573,f2fd060 arch=linux-ubuntu20.04-x86_64_v3

[...]
```

### Error message

According to the documentation (https://spack.readthedocs.io/en/latest/packaging_guide.html), the hash should not change if this is a build-only dependency:

> Another consequence of this is that build-only dependencies do not affect the hash of the package. 

However, the hash changes for every python version that I use here.
Perhaps the documentation is misleading me here or dependencies on python are somewhat special...

The documented behavior would be very helpful as the changing hashes of ninja lead to rebuilding lots of other dependencies...

### Information on your system

* **Spack:** 0.18.1 (13e6f87ef6527954b152eaea303841978e83b992)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
I think the documentation is outdated, but @tgamblin should confirm. In the past, the reason build type deps did not enter the hash was to concretize to the same hashes even when build deps were updated, to avoid redundant rebuilds. This was later replaced by making the concretizer prefer reuse of installed specs over optimizing for the latest version of everything. With that in place, the hash could include the build deps too, which simplifies a lot of things in Spack internally.

**Comment by alalazo** [comment]
@haampie is correct. As of v0.18.0 Spack has only one concept of "hash" for specs, which includes build dependencies. I think we should close this issue once the documentation is properly updated.

**Comment by melven** [comment]
Ok, thanks for the clarification!

**Comment by tgamblin** [comment]
Oops -- nice catch. #31860 fixes the docs.
