### ISSUE TITLE
Python setup.py requirements

### ISSUE THREAD

**Issue by JavierCVilla** [LLNL/spack#3172]
One question related to `PythonPackage`'s.

I've seen this piece of code inside the `setup.py` of a python package:

```
setuptools_args = {}
install_requires = setuptools_args['install_requires'] = [
    'traitlets',
    'ipython_genutils',
    'jupyter_core',
    'jupyter_client>=4.1',
    'pygments',
    'ipykernel>=4.1', # not a real dependency, but require the reference kernel
]
```

Do I have to define all these other python packages as a dependency in the `package.py` or is it enough just defining `py-setuptools` as a dependency to install these requirements? In the latter case, I guess that at least I have to check that all these packages (traitlets, ipython_genutils,...) are supported by Spack.

**Comment by adamjstewart** [comment]
@JavierCVilla Yes, you need to define all of those packages as dependencies. If you don't, it can cause a lot of problems. For example, for users whose cluster is offline, `pip` can't download the dependencies and the build will crash. Also, if `pip` builds those dependencies, they will be installed in the package installation directory. Then, when you try to activate the package, it will crash if any of those dependencies were already installed/activated separately. Luckily all of those dependencies are already in Spack, so it should be easy to get it working. Let me know if you need any help!
