### ISSUE TITLE
symbol lookup error: /lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b

### ISSUE THREAD

**Issue by wyphan** [LLNL/spack#31731]
### Steps to reproduce

For me, this happens whenever I launch `emacs` after loading a Spack-built OpenSSL.
```console
$ spack install openssl@1.1.1q
$ spack load openssl@1.1.1q
```

### Error message

```console
$ emacs
emacs: symbol lookup error: /lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl, version OPENSSL_1_1_1b
```

### Information on your system

```console
$ spack debug report
* **Spack:** 0.19.0.dev0 (b065d69136023693ace8e4d35d9fdad817d63d93)
* **Python:** 3.6.8
* **Platform:** linux-rhel8-zen2
* **Concretizer:** clingo
```
The system-installed version of OpenSSL is 1.1.1k

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
This issue would be closed by https://github.com/spack/spack/pull/28354
