### ISSUE TITLE
re2c error when installing package

### ISSUE THREAD

**Issue by nono-Sang** [LLNL/spack#31745]
### Steps to reproduce the issue

```console
When I install any package, the same error occurs. For example, the following command:
$ spack install autoconf@2.71

As for error, I think it has something to do with re2c-2.2-vxysp3oqitsevuowcpefwvmskcjszrzc
```

### Error message

<details><summary>Error message</summary><pre>
==> Bootstrapping clingo from pre-built binaries
==> Bootstrapping clingo from sources
[+] /usr (external bison-3.0.4-2t7uvfd7sesgvvybwkeyxe6lvkw5gdt4)
[+] /GPUFS/sysu_dhuang_lzg2/MyCmake/cmake (external cmake-3.23.2-75pkscco5znjqot7sv277hqpnrwc6g2g)
[+] /GPUFS/app_GPU/application/anaconda3/5.3.1 (external python-3.6-tkiz6kukbwwaa6x5wnb5zoqimqwf2oui)
==> Installing re2c-2.2-vxysp3oqitsevuowcpefwvmskcjszrzc
==> No binary for re2c-2.2-vxysp3oqitsevuowcpefwvmskcjszrzc found: installing from source
==> Error: FetchError: All fetchers failed for spack-stage-re2c-2.2-vxysp3oqitsevuowcpefwvmskcjszrzc
/GPUFS/sysu_dhuang_lzg2/MySpack/spack/lib/spack/spack/package.py:1537, in do_fetch:
       1534
       1535        self.stage.create()
       1536        err_msg = None if not self.manual_download else self.download_instr
  >>   1537        start_time = time.time()
       1538        self.stage.fetch(mirror_only, err_msg=err_msg)
       1539        self._fetch_time = time.time() - start_time
       1540
==> Warning: Skipping build of clingo-bootstrap-spack-nkzcbzdzm7prkpnrsygbthixi4g5hbo3 since re2c-2.2-vxysp3oqitsevuowcpefwvmskcjszrzc failed
==> Error: cannot bootstrap the "clingo" Python module from spec "clingo-bootstrap@spack+python %gcc target=x86_64" due to the following failures:
github-actions-v0.2 raised RuntimeError: The binary index is empty
github-actions-v0.1 raised ValueError: source is not trusted
spack-install raised InstallError: Terminating after first install failure: FetchError: All fetchers failed for spack-stage-re2c-2.2-vxysp3oqitsevuowcpefwvmskcjszrzc
Run `spack --debug ...` for more detailed errors
</pre></details>

### Information on your system

* **Spack:** 0.18.1
* **Python:** 3.6.13
* **Platform:** linux-centos7-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Can you run `spack bootstrap status`? It's possible that you're missing one of Spack's [required dependencies](https://spack.readthedocs.io/en/latest/getting_started.html#system-prerequisites).

**Comment by nono-Sang** [comment]
Yes, it shows that clingo is missing. The specific information is :

Spack v0.18.1 - python@3.6

[FAIL] Core Functionalities
  [B] MISSING "clingo": required to concretize specs

[PASS] Binary packages


Spack will take care of bootstrapping any missing dependency marked as [B]. Depe                                                                           ndencies marked as [-] are instead required to be found on the system.
