### ISSUE TITLE
spack list: add --tag flag

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#31856]
### Summary

`spack find` has a `--tag` flag that lets you filter packages containing a certain tag. We should add the same flag to `spack list`.

### Rationale

A user may want to list _all_ packages belonging to a certain category, not just _installed_ packages.

### Description

We just need to add a `--tag` flag to `spack list`, should be straightforward to copy this setting from `spack find` and add tests.

### Additional information

We're planning to add an "ml" tag to all machine learning packages. We would like a way to list these packages so that we can ensure they all have common features (maintainers, post-install tests, etc.).

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by sparkyniner** [comment]
Hello, can I work on this?

**Comment by adamjstewart** [comment]
Yes, please do!

**Comment by sparkyniner** [comment]
Yupp!, I'm actually a bit new to this and this will be my first contribution, could I please the know the names of the relevant files from the repo for this issue?

**Comment by adamjstewart** [comment]
The file you'll want to edit is [`lib/spack/spack/cmd/list.py`](https://github.com/spack/spack/blob/develop/lib/spack/spack/cmd/list.py). You'll want to add a new flag in `setup_parser` and use it in `filter_by_name`. For an example of how to do this, look at [`lib/spack/spack/cmd/find.py`](https://github.com/spack/spack/blob/develop/lib/spack/spack/cmd/find.py). Specifically, [this line](https://github.com/spack/spack/blob/develop/lib/spack/spack/cmd/find.py#L64) adds the flag (only add tags), and [these lines](https://github.com/spack/spack/blob/develop/lib/spack/spack/cmd/find.py#L275,L278) use it.

To add tests, you'll want to edit [`lib/spack/spack/test/cmd/list.py`](https://github.com/spack/spack/blob/develop/lib/spack/spack/test/cmd/list.py). See [`lib/spack/spack/test/cmd/find.py`](https://github.com/spack/spack/blob/develop/lib/spack/spack/test/cmd/find.py) for examples, there are a few using tags.

**Comment by sparkyniner** [comment]
Hello!, thanks to your help I was able to add --tag to find.py but I coudn't understand how to add tests. Could you please review my pull request?

**Comment by adamjstewart** [comment]
Just realized `spack tags` provides this same feature. But I still think it's worth including in `spack list` since it's also in `spack find`.

**Comment by tldahlgren** [comment]
> Just realized `spack tags` provides this same feature. But I still think it's worth including in `spack list` since it's also in `spack find`.

Yes, that (IMO more intuitive :wink:) command provides the functionality you want (see https://spack.readthedocs.io/en/latest/command_index.html#spack-tags).

**Comment by adamjstewart** [comment]
Not sure how this got added to 0.18.2 but we should bump this to 0.19.0 since it adds a new feature.
