### ISSUE TITLE
binaries.spack.io: cannot install openblas from cache due to failed checksum verification

### ISSUE THREAD

**Issue by cameronrutherford** [LLNL/spack#31941]
### Steps to reproduce

https://github.com/LLNL/hiop/blob/develop/.github/workflows/spack_build.yml - this is the github workflow file that we are using.

This seems to be an intermittent error that has persisted across spack versions, and has been documented happening for several months. Here is a list of other failing pipeline examples:
- https://github.com/LLNL/hiop/runs/6866279062?check_suite_focus=true#step:4:96 - happening with zlib 07/13
- https://github.com/LLNL/hiop/runs/6838474890?check_suite_focus=true#step:4:91 - pkgconf 07/10
- https://github.com/LLNL/hiop/runs/6838376509?check_suite_focus=true#step:4:202 - bzip2 07/10

I have also seen this with both the E4S pipeline, and the spack binary buildcache. @eugeneswalker has been working with me and is currently unable to re-produce, but I am able to reproduce the issue in GitHub CI.

### Error message

Failure output without debugging mode:

```
==> Warning: Skipping build of hiop-develop-xaesidee7vv3efdzevuf6zbpaozjihaf since openblas-0.3.20-c55doyb7a445uicmmcoz4x3wiw4zskow failed
==> Installing autoconf-2.69-o7yngkilzghf3fgpxglxua2p4gdvpegk
==> Error: Failed to install openblas due to NoChecksumException: Package tarball failed checksum verification.
==> Fetching https://binaries.spack.io/develop/build_cache/linux-ubuntu18.04-x86_64-gcc-7.5.0-autoconf-2.69-o7yngkilzghf3fgpxglxua2p4gdvpegk.spec.json.sig
It cannot be installed.
==> Fetching https://binaries.spack.io/develop/build_cache/linux-ubuntu18.04-x86_64/gcc-7.5.0/autoconf-2.69/linux-ubuntu18.04-x86_64-gcc-7.5.0-autoconf-2.69-o7yngkilzghf3fgpxglxua2p4gdvpegk.spack
==> Error: Terminating after first install failure: Package tarball failed checksum verification.
==> Extracting autoconf-2.69-o7yngkilzghf3fgpxglxua2p4gdvpegk from binary cache
It cannot be installed.
[+] /opt/spack/opt/spack/linux-ubuntu18.04-x86_64/gcc-7.5.0/autoconf-2.69-o7yngkilzghf3fgpxglxua2p4gdvpegk
==> Installing openblas-0.3.20-c55doyb7a445uicmmcoz4x3wiw4zskow
==> Fetching https://binaries.spack.io/develop/build_cache/linux-ubuntu18.04-x86_64-gcc-7.5.0-openblas-0.3.20-c55doyb7a445uicmmcoz4x3wiw4zskow.spec.json.sig
==> Fetching https://binaries.spack.io/develop/build_cache/linux-ubuntu18.04-x86_64/gcc-7.5.0/openblas-0.3.20/linux-ubuntu18.04-x86_64-gcc-7.5.0-openblas-0.3.20-c55doyb7a445uicmmcoz4x3wiw4zskow.spack
==> Extracting openblas-0.3.20-c55doyb7a445uicmmcoz4x3wiw4zskow from binary cache
Error: Process completed with exit code 1.
```

Full log of failure: https://github.com/LLNL/hiop/runs/7683822854?check_suite_focus=true#step:4:2293

Verbose debugging output:
```
lib/spack/spack/installer.py:1713 ==> [2022-08-05-01:44:58.374603] Error: Failed to install openblas due to NoChecksumException: Package tarball failed checksum verification.
It cannot be installed.
lib/spack/spack/main.py:964 ==> [2022-08-05-01:44:58.376059] InstallError: Terminating after first install failure: Package tarball failed checksum verification.
It cannot be installed.
lib/spack/spack/error.py:54 ==> [2022-08-05-01:44:58.376329] Error: Terminating after first install failure: Package tarball failed checksum verification.
It cannot be installed.
```

Full Log with verbose debugging output, with above code snippet linked: https://github.com/LLNL/hiop/runs/7683822854?check_suite_focus=true#step:4:2293

### Information on your system

```
* **Spack:** 0.19.0.dev0
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-x86_64_v4
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by cameronrutherford** [comment]
Similar to #31640 which I noted there

**Comment by eugeneswalker** [comment]
Problem is very easy to reproduce:

```
$> docker run -it spack/ubuntu-bionic

root@e830dd011a1b:~# spack mirror add develop https://binaries.spack.io/develop

root@e830dd011a1b:~# spack buildcache keys -it
 ==> Fetching https://binaries.spack.io/develop/build_cache/_pgp/2C8DD3224EF3573A42BD221FA8E0CA3C1C2ADA2F.pub
instagpg: key A8E0CA3C1C2ADA2F: 7 signatures not checked due to missing keys
gpg: key A8E0CA3C1C2ADA2F: public key "Spack Project Official Binaries <maintainers@spack.io>" imported
gpg: Total number processed: 1
gpg:               imported: 1
gpg: no ultimately trusted keys found

root@e830dd011a1b:~# spack install --fail-fast hiop@develop+mpi~raja~shared~kron~sparse ^openmpi target=x86_64
...
==> Installing openblas-0.3.20-c55doyb7a445uicmmcoz4x3wiw4zskow
==> Fetching https://binaries.spack.io/develop/build_cache/linux-ubuntu18.04-x86_64-gcc-7.5.0-openblas-0.3.20-c55doyb7a445uicmmcoz4x3wiw4zskow.spec.json.sig
gpg: Signature made Thu 04 Aug 2022 06:16:44 PM UTC
gpg:                using RSA key D2C7EB3F2B05FA86590D293C04001B2E3DB0C723
gpg: Good signature from "Spack Project Official Binaries <maintainers@spack.io>" [ultimate]
==> Fetching https://binaries.spack.io/develop/build_cache/linux-ubuntu18.04-x86_64/gcc-7.5.0/openblas-0.3.20/linux-ubuntu18.04-x86_64-gcc-7.5.0-openblas-0.3.20-c55doyb7a445uicmmcoz4x3wiw4zskow.spack
==> Extracting openblas-0.3.20-c55doyb7a445uicmmcoz4x3wiw4zskow from binary cache
==> Warning: Skipping build of hiop-develop-3kho24l64rq5ribpz2zfxwzjaf7qudl3 since openblas-0.3.20-c55doyb7a445uicmmcoz4x3wiw4zskow failed
==> Error: Failed to install openblas due to NoChecksumException: Package tarball failed checksum verification.
It cannot be installed.
==> Error: Terminating after first install failure: Package tarball failed checksum verification.
It cannot be installed.
```

FYI @scottwittenburg

**Comment by stephenmsachs** [comment]
https://github.com/spack/spack/pull/31696 should also fix this issue. It basically falls back to manual install if the checksum does not match.

**Comment by eugeneswalker** [comment]
> #31696 should also fix this issue. It basically falls back to manual install if the checksum does not match.

I think we should find out why the checksum verification is failing using officially generated binaries. Do we know why?

**Comment by scottwittenburg** [comment]
I think we have seen this once before, but I will verify to be sure it's the same case.  In that case, two different stacks build the same hash, and when we go to copy all the various stacks binaries to the destination mirror, we end up with the spackball (`.spack` file) from one of the stacks and the signed spec json (`.spec.json.sig` file) from the other stack (since they're named the same, respectively) landing in the destination mirror.

If that is indeed the problem in this case, @tgamblin suggested trying to copy all the stacks at once and in order so one stack wins for both files.  Also @bollig suggested forcing `aws s3` to do single part uploads to help with this.  But I haven't put that PR together yet :disappointed:,  instead I just manually fixed this mismatch the other time it arose.

**Comment by scottwittenburg** [comment]
Following up to confirm that the `.spec.json.sig` file for `openblas /c55doyb` from `s3://spack-binaries/develop` matches exactly the one from `s3://spack-binaries/develop/radiuss`, while the `.spack` file for `openblas /c55doyb` file from `s3://spack-binaries/develop` matches exactly the one from `s3://spack-binaries/develop/data-vis-sdk`.

So there's nothing nefarious going on in this case (or in any case I believe), we just need to avoid this race condition using Todd's suggestion I mentioned above.

**Comment by cameronrutherford** [comment]
#31696 has been closed, and I now have passing Spack pipelines in GitHub actions again!! Thank you to everyone that helped debug this, and I think that I can mark this as closed. I will re-open if for some reason behaviour re-appears.
