### ISSUE TITLE
spack flake8 doesn't work with git 1.7.1

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#3199]
CentOS 6 comes with git 1.7.1 by default. Apparently, this version of git does not support queries like:
```
$ git diff '*.py'
```
meaning that `spack flake8` always results in:
```
$ spack flake8
=======================================================
flake8: running flake8 code checks on spack.

Modified files:
=======================================================

Flake8 checks were clean.
```
no matter how many files are modified. We should remove the `'*.py'` constraint and do the filetype filtering by ourselves.

**Comment by citibeth** [comment]
Solution is to bootstrap a newer git.  Since this is in testing code, not the main user code, it doesn't really bother me that it doesn't work with CentOS6 out of the box.

**Comment by adamjstewart** [comment]
That's what I've been doing. Just figured I'd mention it.
