### ISSUE TITLE
modules: `exclude_implicits` (and specifying a spec) excludes dependencies required through `autoload`, breaking `module load`.

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#32013]
### Steps to reproduce

```yaml
modules:
  default:
    enable: [lmod]
    lmod:
      exclude_implicits: true
      all:
        autoload: direct
```

```
spack module lmod refresh --delete-tree
```

Generates modules for explicit modules with `depends_on(...)` statements for direct deps. But no modules are generated for those dependencies since they are explicit. So `module load` fails.

Same happens when you do

```
spack install curl
spack module lmod refresh --delete-tree curl
```

It only generates modules for specs satisfying `curl`, but then fails to generate modules that are supposed to be autoloaded.

---

Instead, Spack should just generate modules for "implicit" specs when they are required due to `autoload` config.

They way I see `exclude_implicits`: generate module files for all explicitly installed specs and their required autoloaded deps.

Also Spack would be much more user friendly if it simply generated modules for required implicits but hid them, so they are loaded when you do `module load explicit-spec`, but they don't show up when you do `module avail`. I can only assume this was the point of `exclude_implicts`: reducing the noise of `module avail`. For lmod this requires generating a `.modulerc.lua` file with `hide_version(...)` statements for modules that correspond to implicit specs.

**Comment by simonLeary42** [comment]
I've also found that on my system `spack gc` deletes modulefiles for dependencies, breaking `module load`. Could this be related?

edit: https://github.com/spack/spack/issues/40180

**Comment by gmfricke** [comment]
This seems to be impacting out installation as well. For example I installed r-seurat for our users which has about 30 dependencies that have to be made explicit one-by-one. Is there a PR associated with this issue?

**Comment by wholtz** [comment]
Posting my workaround in case it save someone else some time.

Removed `exclude_implicits: true` so that all modules are generated and then hide the implicit modules with:

```
spack find --format '{name}/{version}-{hash:7}'  --implicit \
| sed 's%\(.*\)%hide_version(\"\1\")%' \
> "${MODULE_DEST}/Core/.modulerc.lua"
```
