### ISSUE TITLE
Order of traversal

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#32056]
Spack likes to traverse spec graphs depth-first, but breadth-first would be more accurate to resolve conflicts in a sensible way.

Consider a graph

```
A
├── B
│   └── C
│       └── D
└── D
```

where `C` sets a runtime env variable `X=C` and `D` sets it to `X=D`. Then in post-order DFS with alphabetically sorted adjacent vertices, visiting each vertex once, you'd get `D`, `C`, `B`, `A`, so you'd end up with `X=C` as it occurs last, even though `D` is a direct dependency of `A`.

In reversed BFS you'd get `C`, `D`, `B`, `A`, so `X=D`.

To me it seems that (non-fatal) conflicts are best resolved by giving priority to proximity to the root.

Similarly for environments, the natural order of iteration to setup a run environment or a view would be to do bfs where the env itself is a special initial vertex with `specs` its adjacent vertices, so proximity to the environment itself is given priority.

Also, when printing specs as a tree, it makes more sense to show direct dependencies of the root spec at depth 1, instead of at an arbitrary depth, which makes it look as if a dependency is transitive.

```
x
    ^y
        ^zlib # unclear if zlib is a dep of x too.
```
vs
```
x
    ^y
    ^zlib # more clear.
```

**Comment by tgamblin** [comment]
Fixed by #33406
