### ISSUE TITLE
Installation issue: hpctoolkit "error adding symbols: DSO missing from command line"

### ISSUE THREAD

**Issue by rscohn2** [LLNL/spack#32061]
### Steps to reproduce the issue

```console
rscohn1@anpfclxlin02:spack$ spack spec -l hpctoolkit
Input spec
--------------------------------
hpctoolkit

Concretized
--------------------------------
uyk5f66  hpctoolkit@2022.05.15%gcc@10.3.0~all-static~cray~cuda~debug~gtpin~level_zero~mpi~opencl+papi~rocm+viewer arch=linux-ubuntu2\
0.04-cascadelake
25eyg3y      ^binutils@2.38%gcc@10.3.0~gas~gold~headers~interwork~ld+libiberty~lto+nls+plugins libs=shared,static arch=linux-ubuntu2\
0.04-cascadelake
lqa4we4          ^diffutils@3.8%gcc@10.3.0 arch=linux-ubuntu20.04-cascadelake
sw66lpl              ^libiconv@1.16%gcc@10.3.0 libs=shared,static arch=linux-ubuntu20.04-cascadelake
xbca5vf          ^gettext@0.21%gcc@10.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-ubuntu20.04-cascadelake
5xp26xn              ^bzip2@1.0.8%gcc@10.3.0~debug~pic+shared arch=linux-ubuntu20.04-cascadelake
3gstumu              ^libxml2@2.9.13%gcc@10.3.0~python arch=linux-ubuntu20.04-cascadelake
jic573p                  ^pkgconf@1.6.3%gcc@10.3.0 arch=linux-ubuntu20.04-cascadelake
m5thkqt                  ^xz@5.2.5%gcc@10.3.0+pic libs=shared,static arch=linux-ubuntu20.04-cascadelake
65soofb                  ^zlib@1.2.12%gcc@10.3.0+optimize+pic+shared patches=0d38234 arch=linux-ubuntu20.04-cascadelake
wfkatn3              ^ncurses@6.3.20211021%gcc@10.3.0~symlinks+termlib abi=6 arch=linux-ubuntu20.04-cascadelake
g7wvixe              ^tar@1.30%gcc@10.3.0 zip=pigz arch=linux-ubuntu20.04-cascadelake
yo5hiyt      ^boost@1.79.0%gcc@10.3.0+atomic+chrono~clanglibcpp~container~context~contract~coroutine+date_time~debug~exception~fiber\
+filesystem+graph~graph_parallel~icu~iostreams~json~locale~log~math~mpi+multithreaded~nowide~numpy~pic~program_options~python~random\
+regex~serialization+shared~signals~singlethreaded~stacktrace+system~taggedlayout~test+thread+timer~type_erasure~versionedlayout~wav\
e cxxstd=98 patches=a440f96 visibility=global arch=linux-ubuntu20.04-cascadelake
4gpngdj      ^dyninst@12.2.0%gcc@10.3.0~ipo+openmp~stat_dysect~static build_type=RelWithDebInfo arch=linux-ubuntu20.04-cascadelake
n2nqhav          ^cmake@3.23.2%gcc@10.3.0~doc+ncurses+ownlibs~qt build_type=Release arch=linux-ubuntu20.04-cascadelake
e4m5nn6          ^elfutils@0.186%gcc@10.3.0+bzip2~debuginfod~nls+xz arch=linux-ubuntu20.04-cascadelake
bpg5be4              ^m4@1.4.18%gcc@10.3.0+sigsegv patches=3877ab5,fc9b616 arch=linux-ubuntu20.04-cascadelake
lo43tjc          ^intel-tbb@2020.3%gcc@10.3.0~ipo+shared+tm build_type=RelWithDebInfo cxxstd=default patches=62ba015,ce1fb16,d62cb66\
 arch=linux-ubuntu20.04-cascadelake
n2nqhav              ^cmake@3.23.2%gcc@10.3.0~doc+ncurses+ownlibs~qt build_type=Release arch=linux-ubuntu20.04-cascadelake
itmnd7s          ^libiberty@2.37%gcc@10.3.0+pic arch=linux-ubuntu20.04-cascadelake
4zbpisc      ^hpcviewer@2022.06%gcc@10.3.0 arch=linux-ubuntu20.04-cascadelake
fuits57          ^openjdk@11.0.15_10%gcc@10.3.0 arch=linux-ubuntu20.04-cascadelake
j2vfwiq      ^intel-xed@2022.04.17%gcc@10.3.0~debug+pic arch=linux-ubuntu20.04-cascadelake
zs6abyp          ^python@3.9.5%gcc@10.3.0+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma+nis~optimizations+pic+pyexpat~pythoncmd+readli\
ne+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93,4c24573,f2fd060 arch=linux-ubuntu20.04-cascadelake
4gp6jxi      ^libdwarf@20180129%gcc@10.3.0 arch=linux-ubuntu20.04-cascadelake
uijd2fv      ^libmonitor@2021.11.08%gcc@10.3.0~commrank~dlopen+hpctoolkit arch=linux-ubuntu20.04-cascadelake
kwxqae3      ^libunwind@1.6.2%gcc@10.3.0~block_signals~conservative_checks~cxx_exceptions~debug~debug_frame+docs+pic+tests+weak_back\
trace+xz~zlib components=none libs=shared,static arch=linux-ubuntu20.04-cascadelake
sc2az6y      ^memkind@1.13.0%gcc@10.3.0 arch=linux-ubuntu20.04-cascadelake
4kc6asj          ^autoconf@2.69%gcc@10.3.0 patches=7793209 arch=linux-ubuntu20.04-cascadelake
rtuzsur          ^automake@1.16.1%gcc@10.3.0 arch=linux-ubuntu20.04-cascadelake
5yytfsl          ^libtool@2.4.6%gcc@10.3.0 arch=linux-ubuntu20.04-cascadelake
bpg5be4          ^m4@1.4.18%gcc@10.3.0+sigsegv patches=3877ab5,fc9b616 arch=linux-ubuntu20.04-cascadelake
g3frz2w          ^numactl@2.0.14%gcc@10.3.0 patches=4e1d78c,62fc8a8,ff37630 arch=linux-ubuntu20.04-cascadelake
rs6x2z6      ^papi@6.0.0.1%gcc@10.3.0~cuda+example~infiniband~lmsensors~nvml~powercap~rapl~rocm~rocm_smi~sde+shared~static_tools arc\
h=linux-ubuntu20.04-cascadelake
z4hb447      ^xerces-c@3.2.3%gcc@10.3.0 cxxstd=default netaccessor=curl transcoder=iconv arch=linux-ubuntu20.04-cascadelake
3f4suoj          ^curl@7.68.0%gcc@10.3.0+gssapi+ldap~libidn2~librtmp~libssh~libssh2+nghttp2 libs=shared,static tls=openssl arch=linu\
x-ubuntu20.04-cascadelake

rscohn1@anpfclxlin02:spack$
```

### Error message

<details><summary>Error message</summary><pre>
In file included from /localdisk/work/rscohn1/projects/spack/spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-10.3.0/dyninst-12.2.0-4gpngdjixzisay2v6hoqadl2inixmfr2/include/concurrent.h:40,
                 from /localdisk/work/rscohn1/projects/spack/spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-10.3.0/dyninst-12.2.0-4gpngdjixzisay2v6hoqadl2inixmfr2/include/IBSTree.h:42,
                 from /localdisk/work/rscohn1/projects/spack/spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-10.3.0/dyninst-12.2.0-4gpngdjixzisay2v6hoqadl2inixmfr2/include/CFG.h:42,
                 from DotGraph.cpp:72:
/localdisk/work/rscohn1/projects/spack/spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-10.3.0/intel-tbb-2020.3-lo43tjca3ixaeuoaxhuly6olgrlxg6ij/include/tbb/concurrent_hash_map.h: In constructor 'tbb::interface5::internal::hash_map_base::hash_map_base()':
/localdisk/work/rscohn1/projects/spack/spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-10.3.0/intel-tbb-2020.3-lo43tjca3ixaeuoaxhuly6olgrlxg6ij/include/tbb/concurrent_hash_map.h:131:76: warning: 'void* memset(void*, int, size_t)' clearing an object of type 'struct tb\
b::interface5::internal::hash_map_base::bucket' with no trivial copy-assignment; use value-initialization instead [-Wclass-memaccess]
  131 |             std::memset(my_embedded_segment, 0, sizeof(my_embedded_segment));
      |                                                                            ^
/localdisk/work/rscohn1/projects/spack/spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-10.3.0/intel-tbb-2020.3-lo43tjca3ixaeuoaxhuly6olgrlxg6ij/include/tbb/concurrent_hash_map.h:93:16: note: 'struct tbb::interface5::internal::hash_map_base::bucket' declared here
   93 |         struct bucket : tbb::internal::no_copy {
      |                ^~~~~~
libtool: link: /localdisk/work/rscohn1/projects/spack/spack/lib/spack/env/gcc/g++ -g -O3 -Wall -faligned-new -I/tmp/rscohn1/spack-stage/spack-stage-hpctoolkit-2022.05.15-uyk5f66e7atmyxgleu6tpp5ufr347f4p/spack-src/src -I/tmp/rscohn1/spack-stage/spack-stage-hpctoolkit-20\
22.05.15-uyk5f66e7atmyxgleu6tpp5ufr347f4p/spack-src/src -I/localdisk/work/rscohn1/projects/spack/spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-10.3.0/binutils-2.38-25eyg3y6uiak3yyfvxkbpuk2ts6ny473/include -I/localdisk/work/rscohn1/projects/spack/spack/opt/spack/lin\
ux-ubuntu20.04-cascadelake/gcc-10.3.0/boost-1.79.0-yo5hiytue4b4jmv7okvfkewqqj25u75u/include -I/localdisk/work/rscohn1/projects/spack/spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-10.3.0/dyninst-12.2.0-4gpngdjixzisay2v6hoqadl2inixmfr2/include -I/localdisk/work/rscoh\
n1/projects/spack/spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-10.3.0/elfutils-0.186-e4m5nn6hpj7oducg4lxplguatdb3bi5k/include -I/localdisk/work/rscohn1/projects/spack/spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-10.3.0/intel-tbb-2020.3-lo43tjca3ixaeuoaxhuly6o\
lgrlxg6ij/include -fopenmp -g -O3 -Wall -faligned-new -o hpcstruct-bin hpcstruct_bin-main.o hpcstruct_bin-Args.o hpcstruct_bin-Structure-Cache.o hpcstruct_bin-SingleBin.o hpcstruct_bin-MeasDir.o  -lm ../../../src/lib/analysis/.libs/libHPCanalysis.a ../../../src/lib/ban\
al/.libs/libHPCbanal.a ../../../src/lib/banal/.libs/libHPCbanal_simple.a ../../../src/lib/prof/.libs/libHPCprof.a ../../../src/lib/binutils/.libs/libHPCbinutils.a ../../../src/lib/prof-lean/.libs/libHPCprof-lean.a ../../../src/lib/isa/.libs/libHPCisa.a /localdisk/work/\
rscohn1/projects/spack/spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-10.3.0/intel-xed-2022.04.17-j2vfwiqihl6zw45mxju564dcnid56sxc/lib/libxed.a ../../../src/lib/xml/.libs/libHPCxml.a ../../../src/lib/support/.libs/libHPCsupport.a ../../../src/lib/support-lean/.libs/\
libHPCsupport-lean.a -L/localdisk/work/rscohn1/projects/spack/spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-10.3.0/dyninst-12.2.0-4gpngdjixzisay2v6hoqadl2inixmfr2/lib -lparseAPI -linstructionAPI -lsymtabAPI -ldynDwarf -ldynElf -lcommon -L/localdisk/work/rscohn1/pro\
jects/spack/spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-10.3.0/boost-1.79.0-yo5hiytue4b4jmv7okvfkewqqj25u75u/lib -lboost_graph -lboost_regex -lboost_system -L/localdisk/work/rscohn1/projects/spack/spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-10.3.0/elfutils-\
0.186-e4m5nn6hpj7oducg4lxplguatdb3bi5k/lib -ldw -lelf /localdisk/work/rscohn1/projects/spack/spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-10.3.0/binutils-2.38-25eyg3y6uiak3yyfvxkbpuk2ts6ny473/lib/libbfd.a /localdisk/work/rscohn1/projects/spack/spack/opt/spack/linu\
x-ubuntu20.04-cascadelake/gcc-10.3.0/binutils-2.38-25eyg3y6uiak3yyfvxkbpuk2ts6ny473/lib/libiberty.a -ldl /localdisk/work/rscohn1/projects/spack/spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-10.3.0/zlib-1.2.12-65soofbomolzv7tbb5pzmnjn5ykjkwq7/lib/libz.a ../../../src\
/lib/binutils/.libs/libHPCgettext.a -L/opt/intel/oneapi/intelpython/latest/lib -llzma -L/localdisk/work/rscohn1/projects/spack/spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-10.3.0/intel-tbb-2020.3-lo43tjca3ixaeuoaxhuly6olgrlxg6ij/lib -ltbb -ltbbmalloc -fopenmp
/usr/bin/ld: ../../../src/lib/banal/.libs/libHPCbanal.a(libHPCbanal_la-GPUCFGFactory.o): undefined reference to symbol '_ZN3tbb16spin_rw_mutex_v316internal_upgradeEv'
/usr/bin/ld: /localdisk/work/rscohn1/projects/spack/spack/opt/spack/linux-ubuntu20.04-cascadelake/gcc-10.3.0/intel-tbb-2020.3-lo43tjca3ixaeuoaxhuly6olgrlxg6ij/lib/libtbb.so.2: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:719: hpcstruct-bin] Error 1
make[4]: *** Waiting for unfinished jobs....
mv -f .deps/dotgraph_bin-DotGraph.Tpo .deps/dotgraph_bin-DotGraph.Po
make[4]: Leaving directory '/tmp/rscohn1/spack-stage/spack-stage-hpctoolkit-2022.05.15-uyk5f66e7atmyxgleu6tpp5ufr347f4p/spack-src/src/tool/hpcstruct'
make[3]: *** [Makefile:625: all] Error 2
make[3]: Leaving directory '/tmp/rscohn1/spack-stage/spack-stage-hpctoolkit-2022.05.15-uyk5f66e7atmyxgleu6tpp5ufr347f4p/spack-src/src/tool/hpcstruct'
make[2]: *** [Makefile:521: all-recursive] Error 1
make[2]: Leaving directory '/tmp/rscohn1/spack-stage/spack-stage-hpctoolkit-2022.05.15-uyk5f66e7atmyxgleu6tpp5ufr347f4p/spack-src/src/tool'
make[1]: *** [Makefile:507: all-recursive] Error 1
make[1]: Leaving directory '/tmp/rscohn1/spack-stage/spack-stage-hpctoolkit-2022.05.15-uyk5f66e7atmyxgleu6tpp5ufr347f4p/spack-src/src'
make: *** [Makefile:651: all-recursive] Error 1
</pre></details>

### Information on your system

```
rscohn1@anpfclxlin02:spack$ spack debug report
* **Spack:** 0.19.0.dev0 (e4d296dfc523afff5763205fe44f1b92fe2e6e76)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** clingo
rscohn1@anpfclxlin02:spack$
```

### Additional information

[spack-build-out.txt](https://github.com/spack/spack/files/9309392/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/9309394/spack-build-env.txt)

@mwkrentel 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by mwkrentel** [comment]
Hmm, I don't see any obvious reason for this failure.
I routinely use gcc 8.x and 9.x and I have used 10.x before.
Anyway, Thanks for reporting it, I'll look into it.

@rscohn2 Is this inside a container?

**Comment by rscohn2** [comment]
It is ubuntu 20.04.4, without a container. I tried with gcc@8.4.0, gcc@9.4.0, and gcc@10.3.0 installed by apt and they all have the same problem. Someone else was able to build with a gcc8 installed by spack so we are not blocked.

**Comment by mwkrentel** [comment]
@rscohn2 In that case, is there a system version of tbb ?
That is, in `/usr/include` and `/usr/lib` (or wherever ubuntu puts libs) ?

**Comment by rscohn2** [comment]
That was it. I did not have the system tbb installed, but one of my externals had a copy of libtbb.so in the same directory. Thanks!

**Comment by mwkrentel** [comment]
Ok, well that was easy.

It should work both with a system (`/usr`) version of tbb or without.
But if you have some extra spack package that's not intel-tbb with
copies of the tbb libraries, then yes, that could cause trouble.
