### ISSUE TITLE
Installation issue:  llvm

### ISSUE THREAD

**Issue by jeffcbecker** [LLNL/spack#32108]
### Steps to reproduce the issue

```console
$ spack spec -I llvm@14.0.6
Input spec
--------------------------------
llvm@14.0.6

Concretized
--------------------------------
cauws4d  llvm@14.0.6%gcc@12.1.0+clang+compiler-rt~cuda~flang+gold+internal_unwind~ipo+libcxx~link_llvm_dylib+lld+lldb+llvm_dylib~mlir+omp_as_runtime~omp_debug~omp_tsan+polly~python~split_dwarf~z3 build_type=Release patches=6379168,d85ef51,f920173 shlib_symbol_version=none targets=none version_suffix=none arch=linux-rhel7-sandybridge
bz56uqf      ^binutils@2.38%gcc@12.1.0~gas+gold~headers~interwork+ld~libiberty~lto+nls+plugins libs=shared,static arch=linux-rhel7-sandybridge
qanjaa2          ^diffutils@3.8%gcc@12.1.0 arch=linux-rhel7-sandybridge
aqkjcnx              ^libiconv@1.16%gcc@12.1.0 libs=shared,static arch=linux-rhel7-sandybridge
xoc2mab          ^gettext@0.21%gcc@12.1.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-rhel7-sandybridge
v6vqvkk              ^bzip2@1.0.8%gcc@12.1.0~debug~pic+shared arch=linux-rhel7-sandybridge
b324xkn              ^libxml2@2.9.13%gcc@12.1.0~python arch=linux-rhel7-sandybridge
74jzup7                  ^pkgconf@1.8.0%gcc@12.1.0 arch=linux-rhel7-sandybridge
mh24b7l                  ^xz@5.2.5%gcc@12.1.0~pic libs=shared,static arch=linux-rhel7-sandybridge
v7akdfg                  ^zlib@1.2.12%gcc@12.1.0+optimize+pic+shared patches=0d38234 arch=linux-rhel7-sandybridge
gnzo6m5              ^ncurses@6.2%gcc@12.1.0~symlinks+termlib abi=none arch=linux-rhel7-sandybridge
wvyqet2              ^tar@1.34%gcc@12.1.0 zip=pigz arch=linux-rhel7-sandybridge
hudp2d7                  ^pigz@2.7%gcc@12.1.0 arch=linux-rhel7-sandybridge
wh37sg7                  ^zstd@1.5.2%gcc@12.1.0+programs compression=none libs=shared,static arch=linux-rhel7-sandybridge
aewh5et      ^cmake@3.23.3%gcc@12.1.0~doc+ncurses~ownlibs~qt build_type=Release arch=linux-rhel7-sandybridge
gizsjhb          ^curl@7.84.0%gcc@12.1.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2~nghttp2 libs=shared,static patches=9b011c9 tls=gnutls arch=linux-rhel7-sandybridge
s4lvb3x              ^gnutls@3.6.15%gcc@12.1.0~guile+zlib arch=linux-rhel7-sandybridge
ztttlpd                  ^libidn2@2.3.0%gcc@12.1.0 arch=linux-rhel7-sandybridge
gxsvuva                      ^libunistring@0.9.10%gcc@12.1.0 arch=linux-rhel7-sandybridge
brncabs                  ^nettle@3.4.1%gcc@12.1.0 arch=linux-rhel7-sandybridge
b7e3ysy                      ^gmp@6.2.1%gcc@12.1.0 libs=shared,static arch=linux-rhel7-sandybridge
lak2y32                          ^autoconf@2.69%gcc@12.1.0 patches=7793209 arch=linux-rhel7-sandybridge
yc6hkxy                          ^automake@1.16.5%gcc@12.1.0 arch=linux-rhel7-sandybridge
g2sk6lg                              ^perl@5.34.1%gcc@12.1.0+cpanm+shared+threads arch=linux-rhel7-sandybridge
oqbulwu                                  ^berkeley-db@18.1.40%gcc@12.1.0+cxx~docs+stl patches=b231fcc arch=linux-rhel7-sandybridge
fze2c5x                                  ^gdbm@1.19%gcc@12.1.0 arch=linux-rhel7-sandybridge
op7l5dw                                      ^readline@8.1.2%gcc@12.1.0 arch=linux-rhel7-sandybridge
iei7lwt                          ^libtool@2.4.7%gcc@12.1.0 arch=linux-rhel7-sandybridge
g3ummln                              ^m4@1.4.19%gcc@12.1.0+sigsegv patches=9dc5fbd,bfdffa7 arch=linux-rhel7-sandybridge
hsgdcj2                                  ^libsigsegv@2.13%gcc@12.1.0 arch=linux-rhel7-sandybridge
c4t27bx          ^expat@2.4.8%gcc@12.1.0+libbsd arch=linux-rhel7-sandybridge
sn5hu6p              ^libbsd@0.11.5%gcc@12.1.0 arch=linux-rhel7-sandybridge
a45ocsx                  ^libmd@1.0.4%gcc@12.1.0 arch=linux-rhel7-sandybridge
htepgqg          ^libarchive@3.5.2%gcc@12.1.0+iconv compression=bz2lib,lz4,lzma,lzo2,zlib,zstd crypto=mbedtls libs=shared,static programs=none xar=expat arch=linux-rhel7-sandybridge
b6lquau              ^lz4@1.9.3%gcc@12.1.0 libs=shared,static arch=linux-rhel7-sandybridge
6yddcsh              ^lzo@2.10%gcc@12.1.0 libs=shared,static arch=linux-rhel7-sandybridge
2q2mbkr              ^mbedtls@2.28.0%gcc@12.1.0+pic build_type=Release libs=static arch=linux-rhel7-sandybridge
pa5eqnr          ^libuv@1.44.1%gcc@12.1.0 arch=linux-rhel7-sandybridge
nz5gxtq          ^rhash@1.4.2%gcc@12.1.0 patches=093518c,3fbfe46 arch=linux-rhel7-sandybridge
shugqek      ^hwloc@2.8.0%gcc@12.1.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm+shared arch=linux-rhel7-sandybridge
pubuiwd          ^libpciaccess@0.16%gcc@12.1.0 arch=linux-rhel7-sandybridge
iz3q3z6              ^util-macros@1.19.3%gcc@12.1.0 arch=linux-rhel7-sandybridge
cfy3kmq      ^libedit@3.1-20210216%gcc@12.1.0 arch=linux-rhel7-sandybridge
rb2q6ky      ^ninja@1.11.0%gcc@12.1.0 arch=linux-rhel7-sandybridge
lncwse2          ^python@3.9.13%gcc@12.1.0+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3~ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93,4c24573,f2fd060 arch=linux-rhel7-sandybridge
cof4dip              ^libffi@3.4.2%gcc@12.1.0 arch=linux-rhel7-sandybridge
2rhnl34              ^sqlite@3.38.5%gcc@12.1.0+column_metadata+dynamic_extensions+fts~functions+rtree arch=linux-rhel7-sandybridge
o74yelu              ^util-linux-uuid@2.37.4%gcc@12.1.0 arch=linux-rhel7-sandybridge
vyov7jm      ^perl-data-dumper@2.173%gcc@12.1.0 arch=linux-rhel7-sandybridge

```

### Error message

error message is too long, tail below - see attached spack-build-out.txt

<details><summary>Error message</summary><pre>
     53569    /nobackupnfs1/jcbecker/spack/opt/spack/linux-rhel7-sandybridge/gcc-12.1.0/binutils-2.38-bz56uqfv
              g6rdr2dczyzo3jzm6jw2teu3/bin/ld: lib/liblldbCore.a(IOHandlerCursesGUI.cpp.o): in function `curse
              s::Window::~Window()':
  >> 53570    IOHandlerCursesGUI.cpp:(.text._ZN6curses6WindowD2Ev[_ZN6curses6WindowD5Ev]+0x433): undefined ref
              erence to `stdscr'
     53571    /nobackupnfs1/jcbecker/spack/opt/spack/linux-rhel7-sandybridge/gcc-12.1.0/binutils-2.38-bz56uqfv
              g6rdr2dczyzo3jzm6jw2teu3/bin/ld: lib/liblldbCore.a(IOHandlerCursesGUI.cpp.o): in function `curse
              s::Window::~Window()':
  >> 53572    IOHandlerCursesGUI.cpp:(.text._ZN6curses6WindowD0Ev[_ZN6curses6WindowD5Ev]+0x41b): undefined ref
              erence to `stdscr'
     53573    /nobackupnfs1/jcbecker/spack/opt/spack/linux-rhel7-sandybridge/gcc-12.1.0/binutils-2.38-bz56uqfv
              g6rdr2dczyzo3jzm6jw2teu3/bin/ld: lib/liblldbCore.a(IOHandlerCursesGUI.cpp.o): in function `std::
              _Sp_counted_ptr_inplace<curses::Window, std::allocator<void>, (__gnu_cxx::_Lock_policy)2>::_M_di
              spose()':
  >> 53574    IOHandlerCursesGUI.cpp:(.text._ZNSt23_Sp_counted_ptr_inplaceIN6curses6WindowESaIvELN9__gnu_cxx12
              _Lock_policyE2EE10_M_disposeEv[_ZNSt23_Sp_counted_ptr_inplaceIN6curses6WindowESaIvELN9__gnu_cxx1
              2_Lock_policyE2EE10_M_disposeEv]+0x423): undefined reference to `stdscr'
     53575    /nobackupnfs1/jcbecker/spack/opt/spack/linux-rhel7-sandybridge/gcc-12.1.0/binutils-2.38-bz56uqfv
              g6rdr2dczyzo3jzm6jw2teu3/bin/ld: lib/liblldbCore.a(IOHandlerCursesGUI.cpp.o): in function `curse
              s::Application::GetMainWindow()':
  >> 53576    IOHandlerCursesGUI.cpp:(.text._ZN6curses11Application13GetMainWindowEv[_ZN6curses11Application13
              GetMainWindowEv]+0x6e): undefined reference to `stdscr'
     53577    /nobackupnfs1/jcbecker/spack/opt/spack/linux-rhel7-sandybridge/gcc-12.1.0/binutils-2.38-bz56uqfv
              g6rdr2dczyzo3jzm6jw2teu3/bin/ld: lib/liblldbCore.a(IOHandlerCursesGUI.cpp.o): in function `Row::
              DrawTreeForChild(curses::Window&, Row*, unsigned int)':
  >> 53578    IOHandlerCursesGUI.cpp:(.text._ZN3Row16DrawTreeForChildERN6curses6WindowEPS_j[_ZN3Row16DrawTreeF
              orChildERN6curses6WindowEPS_j]+0x4b): undefined reference to `acs_map'
  >> 53579    /nobackupnfs1/jcbecker/spack/opt/spack/linux-rhel7-sandybridge/gcc-12.1.0/binutils-2.38-bz56uqfv
              g6rdr2dczyzo3jzm6jw2teu3/bin/ld: IOHandlerCursesGUI.cpp:(.text._ZN3Row16DrawTreeForChildERN6curs
              es6WindowEPS_j[_ZN3Row16DrawTreeForChildERN6curses6WindowEPS_j]+0x7b): undefined reference to `a
              cs_map'
  >> 53580    /nobackupnfs1/jcbecker/spack/opt/spack/linux-rhel7-sandybridge/gcc-12.1.0/binutils-2.38-bz56uqfv
              g6rdr2dczyzo3jzm6jw2teu3/bin/ld: IOHandlerCursesGUI.cpp:(.text._ZN3Row16DrawTreeForChildERN6curs
              es6WindowEPS_j[_ZN3Row16DrawTreeForChildERN6curses6WindowEPS_j]+0xb0): undefined reference to `a
              cs_map'
     53581    /nobackupnfs1/jcbecker/spack/opt/spack/linux-rhel7-sandybridge/gcc-12.1.0/binutils-2.38-bz56uqfv
              g6rdr2dczyzo3jzm6jw2teu3/bin/ld: lib/liblldbCore.a(IOHandlerCursesGUI.cpp.o): in function `Value
              ObjectListDelegate::DisplayRows(curses::Window&, std::vector<Row, std::allocator<Row> >&, Displa
              yOptions&)':
  >> 53582    IOHandlerCursesGUI.cpp:(.text._ZN23ValueObjectListDelegate11DisplayRowsERN6curses6WindowERSt6vec
              torI3RowSaIS4_EER14DisplayOptions[_ZN23ValueObjectListDelegate11DisplayRowsERN6curses6WindowERSt
              6vectorI3RowSaIS4_EER14DisplayOptions]+0x261): undefined reference to `acs_map'
  >> 53583    /nobackupnfs1/jcbecker/spack/opt/spack/linux-rhel7-sandybridge/gcc-12.1.0/binutils-2.38-bz56uqfv
              g6rdr2dczyzo3jzm6jw2teu3/bin/ld: IOHandlerCursesGUI.cpp:(.text._ZN23ValueObjectListDelegate11Dis
              playRowsERN6curses6WindowERSt6vectorI3RowSaIS4_EER14DisplayOptions[_ZN23ValueObjectListDelegate1
              1DisplayRowsERN6curses6WindowERSt6vectorI3RowSaIS4_EER14DisplayOptions]+0x453): undefined refere
              nce to `acs_map'
     53584    /nobackupnfs1/jcbecker/spack/opt/spack/linux-rhel7-sandybridge/gcc-12.1.0/binutils-2.38-bz56uqfv
              g6rdr2dczyzo3jzm6jw2teu3/bin/ld: lib/liblldbCore.a(IOHandlerCursesGUI.cpp.o):IOHandlerCursesGUI.
              cpp:(.text._ZN23ValueObjectListDelegate11DisplayRowsERN6curses6WindowERSt6vectorI3RowSaIS4_EER14
              DisplayOptions[_ZN23ValueObjectListDelegate11DisplayRowsERN6curses6WindowERSt6vectorI3RowSaIS4_E
              ER14DisplayOptions]+0x493): more undefined references to `acs_map' follow
     53585    /nobackupnfs1/jcbecker/spack/opt/spack/linux-rhel7-sandybridge/gcc-12.1.0/binutils-2.38-bz56uqfv
              g6rdr2dczyzo3jzm6jw2teu3/bin/ld: lib/liblldbCore.a(IOHandlerCursesGUI.cpp.o): in function `lldb_
              private::IOHandlerCursesGUI::Activate() [clone .localalias]':
  >> 53586    IOHandlerCursesGUI.cpp:(.text._ZN12lldb_private18IOHandlerCursesGUI8ActivateEv+0xbc3): undefined
               reference to `curs_set'
  >> 53587    /nobackupnfs1/jcbecker/spack/opt/spack/linux-rhel7-sandybridge/gcc-12.1.0/binutils-2.38-bz56uqfv
              g6rdr2dczyzo3jzm6jw2teu3/bin/ld: IOHandlerCursesGUI.cpp:(.text._ZN12lldb_private18IOHandlerCurse
              sGUI8ActivateEv+0xbcf): undefined reference to `stdscr'
  >> 53588    /nobackupnfs1/jcbecker/spack/opt/spack/linux-rhel7-sandybridge/gcc-12.1.0/binutils-2.38-bz56uqfv
              g6rdr2dczyzo3jzm6jw2teu3/bin/ld: IOHandlerCursesGUI.cpp:(.text._ZN12lldb_private18IOHandlerCurse
              sGUI8ActivateEv+0xbdc): undefined reference to `keypad'
  >> 53589    /nobackupnfs1/jcbecker/spack/opt/spack/linux-rhel7-sandybridge/gcc-12.1.0/binutils-2.38-bz56uqfv
              g6rdr2dczyzo3jzm6jw2teu3/bin/ld: IOHandlerCursesGUI.cpp:(.text._ZN12lldb_private18IOHandlerCurse
              sGUI8ActivateEv+0x14f8): undefined reference to `define_key'
  >> 53590    /nobackupnfs1/jcbecker/spack/opt/spack/linux-rhel7-sandybridge/gcc-12.1.0/binutils-2.38-bz56uqfv
              g6rdr2dczyzo3jzm6jw2teu3/bin/ld: IOHandlerCursesGUI.cpp:(.text._ZN12lldb_private18IOHandlerCurse
              sGUI8ActivateEv+0x1509): undefined reference to `define_key'
     53591    /nobackupnfs1/jcbecker/spack/opt/spack/linux-rhel7-sandybridge/gcc-12.1.0/binutils-2.38-bz56uqfv
              g6rdr2dczyzo3jzm6jw2teu3/bin/ld: lib/liblldbCore.a(IOHandlerCursesGUI.cpp.o): in function `Appli
              cationDelegate::MenuDelegateAction(curses::Menu&)':
  >> 53592    IOHandlerCursesGUI.cpp:(.text._ZN19ApplicationDelegate18MenuDelegateActionERN6curses4MenuE[_ZN19
              ApplicationDelegate18MenuDelegateActionERN6curses4MenuE]+0xa55): undefined reference to `stdscr'
  >> 53593    /nobackupnfs1/jcbecker/spack/opt/spack/linux-rhel7-sandybridge/gcc-12.1.0/binutils-2.38-bz56uqfv
              g6rdr2dczyzo3jzm6jw2teu3/bin/ld: IOHandlerCursesGUI.cpp:(.text._ZN19ApplicationDelegate18MenuDel
              egateActionERN6curses4MenuE[_ZN19ApplicationDelegate18MenuDelegateActionERN6curses4MenuE]+0xbd8)
              : undefined reference to `stdscr'
  >> 53594    /nobackupnfs1/jcbecker/spack/opt/spack/linux-rhel7-sandybridge/gcc-12.1.0/binutils-2.38-bz56uqfv
              g6rdr2dczyzo3jzm6jw2teu3/bin/ld: IOHandlerCursesGUI.cpp:(.text._ZN19ApplicationDelegate18MenuDel
              egateActionERN6curses4MenuE[_ZN19ApplicationDelegate18MenuDelegateActionERN6curses4MenuE]+0xd27)
              : undefined reference to `stdscr'
  >> 53595    collect2: error: ld returned 1 exit status
     53596    ninja: build stopped: subcommand failed.
</pre></details>

### Information on your system

* **Spack:** 0.19.0.dev0
* **Python:** 3.6.8
* **Platform:** linux-rhel7-sandybridge
* **Concretizer:** clingo

### Additional information

[spack-build-out.txt](https://github.com/spack/spack/files/9330139/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/9330141/spack-build-env.txt)
@haampie
@trws

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by lrtfm** [comment]
Maybe you could try this: https://github.com/spack/spack/pull/32037

**Comment by eugeneswalker** [comment]
> Maybe you could try this: #32037

And, if that doesn't work by itself, do it in conjunction with https://github.com/spack/spack/pull/32028 -- high probability that if you use both it will work.

**Comment by jeffcbecker** [comment]
That fixes the problem! Thanks. You can close this issue.
