### ISSUE TITLE
umpire@2022.03.1 +rocm fails: Target "blt_hip" INTERFACE_INCLUDE_DIRECTORIES property contains path prefixed in source directory

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#32133]
### Steps to reproduce the issue

Reproducible using:
* `spack@develop` (b32cb5765c598e59f2f91d99807b4331f4eba569 from `Fri Aug 12 23:17:20 2022 -0700`)
* `ecpe4s/ubuntu22.04-runner-x86_64:2022-08-01`
* `%gcc@11.2.0`
* ROCm 5.2.0

Concrete spec: [umpire.spec.json.txt](https://github.com/spack/spack/files/9333671/umpire.spec.json.txt)

<details><summary>Concretization</summary>
<pre>
 -   umpire@2022.03.1%gcc@11.2.0+c~cuda+device_alloc~deviceconst+examples~fortran~ipo~numa~openmp+rocm+shared amdgpu_target=gfx90a build_type=RelWithDebInfo tests=none arch=linux-ubuntu22.04-x86_64
[+]      ^blt@0.5.1%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]          ^cmake@3.20.6%gcc@11.2.0~doc+ncurses+ownlibs~qt build_type=Release arch=linux-ubuntu22.04-x86_64
[+]              ^ncurses@6.2%gcc@11.2.0~symlinks+termlib abi=none arch=linux-ubuntu22.04-x86_64
[+]                  ^pkgconf@1.8.0%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]              ^openssl@1.1.1q%gcc@11.2.0~docs~shared certs=mozilla patches=3fdcf2d arch=linux-ubuntu22.04-x86_64
[+]                  ^ca-certificates-mozilla@2022-07-19%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                  ^perl@5.34.1%gcc@11.2.0+cpanm+shared+threads arch=linux-ubuntu22.04-x86_64
[+]                      ^berkeley-db@18.1.40%gcc@11.2.0+cxx~docs+stl patches=b231fcc arch=linux-ubuntu22.04-x86_64
[+]                      ^bzip2@1.0.8%gcc@11.2.0~debug~pic+shared arch=linux-ubuntu22.04-x86_64
[+]                          ^diffutils@3.8%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                              ^libiconv@1.16%gcc@11.2.0 libs=shared,static arch=linux-ubuntu22.04-x86_64
[+]                      ^gdbm@1.19%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                          ^readline@8.1.2%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                      ^zlib@1.2.12%gcc@11.2.0+optimize+pic+shared patches=0d38234 arch=linux-ubuntu22.04-x86_64
[+]      ^camp@2022.03.0%gcc@11.2.0~cuda~ipo+rocm~tests amdgpu_target=gfx90a build_type=RelWithDebInfo arch=linux-ubuntu22.04-x86_64
[+]          ^hip@5.2.0%gcc@11.2.0~ipo build_type=Release patches=959d1fe arch=linux-ubuntu22.04-x86_64
[+]              ^comgr@5.2.0%gcc@11.2.0~ipo build_type=Release arch=linux-ubuntu22.04-x86_64
[+]                  ^llvm-amdgpu@5.2.0%gcc@11.2.0~ipo~link_llvm_dylib~llvm_dylib~openmp+rocm-device-libs build_type=Release patches=a08bbe1 arch=linux-ubuntu22.04-x86_64
[+]                      ^python@3.8.13%gcc@11.2.0+bz2+ctypes+dbm~debug+ensurepip+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93,4c24573,f2fd060 arch=linux-ubuntu22.04-x86_64
[+]                          ^expat@2.4.8%gcc@11.2.0+libbsd arch=linux-ubuntu22.04-x86_64
[+]                              ^libbsd@0.11.5%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                                  ^libmd@1.0.4%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                          ^gettext@0.21%gcc@11.2.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-ubuntu22.04-x86_64
[+]                              ^libxml2@2.9.13%gcc@11.2.0~python arch=linux-ubuntu22.04-x86_64
[+]                                  ^xz@5.2.5%gcc@11.2.0+pic libs=shared,static arch=linux-ubuntu22.04-x86_64
[+]                              ^tar@1.34%gcc@11.2.0 zip=pigz arch=linux-ubuntu22.04-x86_64
[+]                                  ^pigz@2.7%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                                  ^zstd@1.5.2%gcc@11.2.0+programs compression=none libs=shared,static arch=linux-ubuntu22.04-x86_64
[+]                          ^libffi@3.4.2%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                          ^sqlite@3.38.5%gcc@11.2.0+column_metadata+dynamic_extensions+fts~functions+rtree arch=linux-ubuntu22.04-x86_64
[+]                          ^util-linux-uuid@2.37.4%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                      ^z3@4.8.16%gcc@11.2.0~gmp~ipo~python build_type=RelWithDebInfo arch=linux-ubuntu22.04-x86_64
[+]                  ^rocm-cmake@5.2.0%gcc@11.2.0~ipo build_type=Release arch=linux-ubuntu22.04-x86_64
[+]              ^glx@1.4%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                  ^mesa@22.1.2%gcc@11.2.0+glx+llvm+opengl~opengles+osmesa~strip buildtype=release default_library=shared patches=ada85be arch=linux-ubuntu22.04-x86_64
[+]                      ^bison@3.8.2%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                          ^m4@1.4.19%gcc@11.2.0+sigsegv patches=9dc5fbd,bfdffa7 arch=linux-ubuntu22.04-x86_64
[+]                              ^libsigsegv@2.13%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                      ^flex@2.6.3%gcc@11.2.0+lex~nls arch=linux-ubuntu22.04-x86_64
[+]                          ^findutils@4.9.0%gcc@11.2.0 patches=440b954 arch=linux-ubuntu22.04-x86_64
[+]                      ^glproto@1.4.17%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                          ^util-macros@1.19.3%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                      ^libunwind@1.6.2%gcc@11.2.0~block_signals~conservative_checks~cxx_exceptions~debug~debug_frame+docs+pic+tests+weak_backtrace+xz~zlib components=none libs=shared,static arch=linux-ubuntu22.04-x86_64
[+]                      ^libx11@1.7.0%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                          ^inputproto@2.3.2%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                          ^kbproto@1.0.7%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                          ^libxcb@1.14%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                              ^libpthread-stubs@0.4%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                              ^libxau@1.0.8%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                                  ^xproto@7.0.31%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                              ^libxdmcp@1.1.2%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                              ^xcb-proto@1.14.1%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                          ^xextproto@7.3.0%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                          ^xtrans@1.3.5%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                      ^libxext@1.3.3%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                      ^libxt@1.1.5%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                          ^libice@1.0.9%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                          ^libsm@1.2.3%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                      ^meson@0.62.2%gcc@11.2.0 patches=9c87472,aa6c50d arch=linux-ubuntu22.04-x86_64
[+]                          ^ninja@1.11.0%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                          ^py-pip@22.1.2%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                          ^py-setuptools@63.0.0%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                          ^py-wheel@0.37.1%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                      ^py-mako@1.1.6%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                          ^py-markupsafe@2.0.1%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                      ^xrandr@1.5.0%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                          ^libxrandr@1.5.0%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                              ^libxrender@0.9.10%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                                  ^renderproto@0.11.1%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                              ^randrproto@1.5.0%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]              ^hsa-rocr-dev@5.2.0%gcc@11.2.0+image~ipo+shared build_type=Release patches=71e6851 arch=linux-ubuntu22.04-x86_64
[+]                  ^elfutils@0.186%gcc@11.2.0+bzip2~debuginfod~nls+xz arch=linux-ubuntu22.04-x86_64
[+]                  ^hsakmt-roct@5.2.0%gcc@11.2.0~ipo+shared build_type=Release patches=f926273 arch=linux-ubuntu22.04-x86_64
[+]                      ^libdrm@2.4.110%gcc@11.2.0~docs arch=linux-ubuntu22.04-x86_64
[+]                          ^libpciaccess@0.16%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                              ^libtool@2.4.7%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                      ^numactl@2.0.14%gcc@11.2.0 patches=4e1d78c,62fc8a8,ff37630 arch=linux-ubuntu22.04-x86_64
[+]                          ^autoconf@2.69%gcc@11.2.0 patches=35c4492,7793209,a49dd5b arch=linux-ubuntu22.04-x86_64
[+]                          ^automake@1.16.5%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                  ^xxd-standalone@8.2.1201%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]              ^perl-file-which@1.22%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]              ^perl-uri-encode@1.1.1%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]                  ^perl-module-build@0.4224%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
[+]              ^rocminfo@5.2.0%gcc@11.2.0~ipo build_type=Release arch=linux-ubuntu22.04-x86_64
[+]              ^roctracer-dev-api@5.2.0%gcc@11.2.0 arch=linux-ubuntu22.04-x86_64
</pre>
</details>

Install error:
```
$> spack install -f ./umpire.spec.json
...
==> Installing umpire-2022.03.1-4vbgbdqepywayj2tqt276dtdbmb64qkg
==> No binary for umpire-2022.03.1-4vbgbdqepywayj2tqt276dtdbmb64qkg found: installing from source
==> Using cached archive: /spack/var/spack/cache/_source-cache/git//LLNL/Umpire.git/v2022.03.1.tar.gz
==> Warning: Fetching from mirror without a checksum!
  This package is normally checked out from a version control system, but it has been archived on a spack mirror.  This means we cannot know a checksum for the tarball in advance. Be sure that your connection to this mirror is secure!
==> No patches needed for umpire
==> umpire: Executing phase: 'initconfig'
==> umpire: Executing phase: 'cmake'
==> Error: ProcessError: Command exited with status 1:
    'cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/umpire-2022.03.1-4vbgbdqepywayj2tqt276dtdbmb64qkg' '-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo' '-DBUILD_TESTING:BOOL=OFF' '-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=OFF' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON' '-DCMAKE_INSTALL_RPATH:STRING=/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/umpire-2022.03.1-4vbgbdqepywayj2tqt276dtdbmb64qkg/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/umpire-2022.03.1-4vbgbdqepywayj2tqt276dtdbmb64qkg/lib64;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/camp-2022.03.0-uiwok2eaf43dxzwc53pwawt7re6jdcom/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/hip-5.2.0-dctstabeimjcvlmfca2njf2uohmongbp/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/comgr-5.2.0-2tlkeqi7kchbphp6w2v3x7imvwojygny/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/llvm-amdgpu-5.2.0-xss5b5hv6tnhxh7ebemtfr75ezaxkkhe/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/ncurses-6.2-ylxqh4yqmlbrjiexg3ej3v7vibzvedbk/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/z3-4.8.16-apx7rfmojtgb6gj75rd7gtj6tc5qfx42/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/zlib-1.2.12-edugrkv3cwwfvj7um4p4pcb77joh6bun/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/mesa-22.1.2-65iw33m3pryholdbpvj7nsszuibikold/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/expat-2.4.8-4nhsan54zuhn5xyrhvfcswwyspzmk4fz/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libbsd-0.11.5-z4wmj5q2x6qmyhsu2adra2g4klzs2w5t/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libmd-1.0.4-s4jxh5c7u552tyyabmulx26zbpbsvcme/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/glproto-1.4.17-4nsecaypsbkow7b526uftffnxprkchdy/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libunwind-1.6.2-tkuyd6pc5mbhv5xkx5fm2iazhi7p4rog/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/xz-5.2.5-vs3p73wz5lhzwf66lt3bjlfx6zbudpze/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libx11-1.7.0-hcec2b2urzlwhu6t23jrjtq2fkwddska/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/inputproto-2.3.2-nccbhlzv47qugswdsem3baqjeoafjhvy/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/kbproto-1.0.7-zsoykodpudmncvbclmr7a2ero6khhnyn/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libxcb-1.14-q4ubmiiuctmntaujpjk5qo2ayklvjjio/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libpthread-stubs-0.4-gbdhl7qdkuyctqs7xgnzet6nkv7ib36i/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libxau-1.0.8-2nobcfiynx2sahk6g55qjaqur4rh5m5j/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/xproto-7.0.31-qj7l6eeauiiwsuk5kx426feo4qsjdqg7/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libxdmcp-1.1.2-y5ebqkxo2je7uyy2pceonkfudvmzovzm/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/xcb-proto-1.14.1-64ag6yv3scoh3y3zq224tti2iqcxvfye/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/xextproto-7.3.0-ale4anqj6talw5375zowgx5gvfqy7huo/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libxext-1.3.3-z43rogwixqyfn54yzyy22p7bxgqretc5/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libxt-1.1.5-ua7kpaz2srbonzf7tp4r2jk3kkdi3oyk/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libice-1.0.9-msx6pxsrvca7e2aijb5uczohmfj3e27e/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libsm-1.2.3-y3d4mdcktfu4sazh6dz7syzn3xh5du6f/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/util-linux-uuid-2.37.4-biegun4vnqnkmvanpn3o25pasfmp3w6v/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libxrandr-1.5.0-niex62nxd3yim3mzpkhpmnlhf5aqxui5/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libxrender-0.9.10-pmp3uglbvlvghulosqlf4c7zrsz7i6h2/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/renderproto-0.11.1-y6hlb667lwb4ll6tdxliz6ghik7n2zpp/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/randrproto-1.5.0-jtsawq65lnncp7ucywabo7dguf2vamrq/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/hsa-rocr-dev-5.2.0-4fljdcafjqkakgpqaivsgr3ncrqqpjce/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/elfutils-0.186-6z236ur4sdwrlv4ao2z6zetnrp33vlyh/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/bzip2-1.0.8-ufk3ruarnyb7d5vkutpwgozseljwzmlw/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/hsakmt-roct-5.2.0-lsehmrkz56bfdsibq2u66dt4ga65x5sg/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libdrm-2.4.110-ybsmxyksopjoc6k76z4jfbxcbkbbxe6s/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libpciaccess-0.16-qdz4q24wgopy4sj4w4ohihrxprrpu5ti/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/numactl-2.0.14-mu6zu4ua3p5cl5aaspnapomds37ivm5t/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/perl-file-which-1.22-rtryvfrg4dln2npbm6ngols4su3beexr/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/perl-uri-encode-1.1.1-4c6oogk7gwk53hkrk3d3yrh3nfu5p3vb/lib;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/openssl-1.1.1q-z7o522sll7q3niorflwxugpyqh6ihmqh/lib' '-DCMAKE_PREFIX_PATH:STRING=/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/camp-2022.03.0-uiwok2eaf43dxzwc53pwawt7re6jdcom;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/hip-5.2.0-dctstabeimjcvlmfca2njf2uohmongbp;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/roctracer-dev-api-5.2.0-7l7i7mh7d5eczqd42w3zi3lmzkm6456t;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/rocminfo-5.2.0-ml2uplwjxh4u2jexcwvebbns6vlts3mw;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/perl-uri-encode-1.1.1-4c6oogk7gwk53hkrk3d3yrh3nfu5p3vb;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/perl-file-which-1.22-rtryvfrg4dln2npbm6ngols4su3beexr;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/hsa-rocr-dev-5.2.0-4fljdcafjqkakgpqaivsgr3ncrqqpjce;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/hsakmt-roct-5.2.0-lsehmrkz56bfdsibq2u66dt4ga65x5sg;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/numactl-2.0.14-mu6zu4ua3p5cl5aaspnapomds37ivm5t;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libdrm-2.4.110-ybsmxyksopjoc6k76z4jfbxcbkbbxe6s;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libpciaccess-0.16-qdz4q24wgopy4sj4w4ohihrxprrpu5ti;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/elfutils-0.186-6z236ur4sdwrlv4ao2z6zetnrp33vlyh;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/glx-1.4-36x6mavjiuihq7c7br56siidmjrda7dn;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/mesa-22.1.2-65iw33m3pryholdbpvj7nsszuibikold;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/xrandr-1.5.0-iznzdykcxtjs6bq4fljgjzzzlxlwhjom;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libxrandr-1.5.0-niex62nxd3yim3mzpkhpmnlhf5aqxui5;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/randrproto-1.5.0-jtsawq65lnncp7ucywabo7dguf2vamrq;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libxrender-0.9.10-pmp3uglbvlvghulosqlf4c7zrsz7i6h2;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/renderproto-0.11.1-y6hlb667lwb4ll6tdxliz6ghik7n2zpp;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libxt-1.1.5-ua7kpaz2srbonzf7tp4r2jk3kkdi3oyk;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libsm-1.2.3-y3d4mdcktfu4sazh6dz7syzn3xh5du6f;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libice-1.0.9-msx6pxsrvca7e2aijb5uczohmfj3e27e;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libxext-1.3.3-z43rogwixqyfn54yzyy22p7bxgqretc5;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libx11-1.7.0-hcec2b2urzlwhu6t23jrjtq2fkwddska;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/xtrans-1.3.5-wexmmr2ztsid4m7iemqw5x45nyzs7gng;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/xextproto-7.3.0-ale4anqj6talw5375zowgx5gvfqy7huo;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libxcb-1.14-q4ubmiiuctmntaujpjk5qo2ayklvjjio;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/xcb-proto-1.14.1-64ag6yv3scoh3y3zq224tti2iqcxvfye;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libxdmcp-1.1.2-y5ebqkxo2je7uyy2pceonkfudvmzovzm;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libxau-1.0.8-2nobcfiynx2sahk6g55qjaqur4rh5m5j;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/xproto-7.0.31-qj7l6eeauiiwsuk5kx426feo4qsjdqg7;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libpthread-stubs-0.4-gbdhl7qdkuyctqs7xgnzet6nkv7ib36i;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/kbproto-1.0.7-zsoykodpudmncvbclmr7a2ero6khhnyn;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/inputproto-2.3.2-nccbhlzv47qugswdsem3baqjeoafjhvy;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libunwind-1.6.2-tkuyd6pc5mbhv5xkx5fm2iazhi7p4rog;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/glproto-1.4.17-4nsecaypsbkow7b526uftffnxprkchdy;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/comgr-5.2.0-2tlkeqi7kchbphp6w2v3x7imvwojygny;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/llvm-amdgpu-5.2.0-xss5b5hv6tnhxh7ebemtfr75ezaxkkhe;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/z3-4.8.16-apx7rfmojtgb6gj75rd7gtj6tc5qfx42;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/util-linux-uuid-2.37.4-biegun4vnqnkmvanpn3o25pasfmp3w6v;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/xz-5.2.5-vs3p73wz5lhzwf66lt3bjlfx6zbudpze;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/expat-2.4.8-4nhsan54zuhn5xyrhvfcswwyspzmk4fz;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libbsd-0.11.5-z4wmj5q2x6qmyhsu2adra2g4klzs2w5t;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/libmd-1.0.4-s4jxh5c7u552tyyabmulx26zbpbsvcme;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/blt-0.5.1-ieuaejlklqmvg22kex2ce44awexhjimp;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/cmake-3.20.6-t77lnb2qdcjuao6lsxvuqbmzwjgmmscp;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/openssl-1.1.1q-z7o522sll7q3niorflwxugpyqh6ihmqh;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/zlib-1.2.12-edugrkv3cwwfvj7um4p4pcb77joh6bun;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/bzip2-1.0.8-ufk3ruarnyb7d5vkutpwgozseljwzmlw;/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.2.0/ncurses-6.2-ylxqh4yqmlbrjiexg3ej3v7vibzvedbk' '-C' '/tmp/root/spack-stage/spack-stage-umpire-2022.03.1-4vbgbdqepywayj2tqt276dtdbmb64qkg/spack-src/7709ba2f8ba0-linux-ubuntu22.04-x86_64-gcc@11.2.0.cmake' '/tmp/root/spack-stage/spack-stage-umpire-2022.03.1-4vbgbdqepywayj2tqt276dtdbmb64qkg/spack-src'

2 errors found in build log:
     70    -- Checking for std::filesystem
     71    -- Performing Test UMPIRE_ENABLE_FILESYSTEM
     72    -- Performing Test UMPIRE_ENABLE_FILESYSTEM - Success
     73    -- std::filesystem found
     74    -- Host Shared Memory Disabled
     75    -- Configuring done
  >> 76    CMake Error in CMakeLists.txt:
     77      Target "blt_hip" INTERFACE_INCLUDE_DIRECTORIES property contains path:
     78
     79        "/tmp/root/spack-stage/spack-stage-umpire-2022.03.1-4vbgbdqepywayj2tqt276dtdbmb64qkg/spack-src/HIP_CLANG_INCLUDE_PATH-NOTFOUND/.."
     80
     81      which is prefixed in the source directory.
     82
     83
  >> 84    CMake Error in CMakeLists.txt:
     85      Target "blt_hip" INTERFACE_INCLUDE_DIRECTORIES property contains path:
     86
     87        "/tmp/root/spack-stage/spack-stage-umpire-2022.03.1-4vbgbdqepywayj2tqt276dtdbmb64qkg/spack-src/HIP_CLANG_INCLUDE_PATH-NOTFOUND/.."
     88
     89      which is prefixed in the source directory.
```

### Error message

<details><summary>Error message</summary><pre>
...
</pre></details>

### Information on your system

* **Spack:** 0.19.0.dev0 (b32cb5765c598e59f2f91d99807b4331f4eba569)
* **Python:** 3.10.4
* **Platform:** linux-ubuntu22.04-zen2
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/9333668/spack-build-env.txt)
[spack-build-02-cmake-out.txt](https://github.com/spack/spack/files/9333669/spack-build-02-cmake-out.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/9333667/spack-build-out.txt)

@davidbeckingsale @white238 @wspear 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by davidbeckingsale** [comment]
This is related to #32127 . @trws has a fix for both, coming soon.

**Comment by trws** [comment]
See #32469 for the workaround.

**Comment by eugeneswalker** [comment]
Closing this as fixed by https://github.com/spack/spack/pull/32469
