### ISSUE TITLE
AutotoolsPackage -- improve error message?

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#3214]
Is it possible to improve Spack's error message during the build of AutotoolsPackage? Currently it is:
```
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8'
/home/davydden/spack/lib/spack/spack/build_systems/autotools.py:275, in build:
     270      def build(self, spec, prefix):
     271          """Makes the build targets specified by
     272          :py:attr:``~.AutotoolsPackage.build_targets``
     273          """
     274          with working_dir(self.build_directory):
  >> 275              inspect.getmodule(self).make(*self.build_targets)

See build log for details:
  /home/davydden/spack/var/spack/stage/gnuplot-5.0.5-bjpzudnr6jw6iogpyctzqwe6ye6djuhw/gnuplot-5.0.5/spack-build.out
```
But it does not really say that the build fails, so the first impression I have is that something is wrong within Spack.
Can we do something like (`C/C++`):
```
try
{
}
catch()
{
   // human readable message with the specific make target that failed?
}
```

**Comment by alalazo** [comment]
I agree we should improve in general the output, and avoid showing stack traces if not requested, but to be fair the first two lines of the message are:
```console
Error: ProcessError: Command exited with status 2:
    'make' '-j8'
```
So, yes: `make` didn't exit with `0`.

**Comment by davydden** [comment]
@alalazo funny enough, it's only now when I noticed that there are those two lines. Somehow visually my attention was drawn to the line where error happens and I completely missed the beginning of the message.

**Comment by alalazo** [comment]
I guess debugging  `C++` template novels in my previous job left me with a pavlovian reflex that "the first two lines of the error are what matters!" :laughing:

**Comment by davydden** [comment]
i think @tgamblin fixed this in recent PRs which now output build errors, if found.
