### ISSUE TITLE
Installation issue: gcc@12.1.0 with glibc v 2.36

### ISSUE THREAD

**Issue by raullaasner** [LLNL/spack#32172]
### Steps to reproduce the issue

```console
$ spack install gcc@12.1.0
```
gcc does not build anymore with glibc version 2.36. This is due to API changes in the latest glibc. You can find more information about it here: https://sourceware.org/glibc/wiki/Release/2.36#Packaging_Changes. To the best of my understanding, `<linux/mount.h>` and `<sys/mount.h>` have conflicting definitions which lead to build errors for application such as gcc which include both of them.

### Error message

The key error is (full message below in spack-build-out.txt)
``/usr/include/linux/mount.h:95:6: error: multiple definition of 'enum fsconfig_command'``

### Information on your system

* **Spack:** 0.19.0.dev0 (0d5437ea4eb3151eb506f1f01a05145eb81a588a)
* **Python:** 3.10.5
* **Platform:** linux-arch-zen3
* **Concretizer:** clingo
* **glibc version:** 2.36

### Additional information

[spack-build-out.txt](https://github.com/spack/spack/files/9350594/spack-build-out.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/9350595/spack-build-out.txt)
@alalazo @michaelkuhn 

I think this can be fixed with the following patch for now:
<pre>
--- a/libsanitizer/sanitizer_common/sanitizer_platform_limits_posix.cpp
+++ b/libsanitizer/sanitizer_common/sanitizer_platform_limits_posix.cpp
@@ -73,7 +73,9 @@
 #include &lt;sys/vt.h>
 #include &lt;linux/cdrom.h>
 #include &lt;linux/fd.h>
+#if SANITIZER_ANDROID
 #include &lt;linux/fs.h>
+#endif
 #include &lt;linux/hdreg.h>
 #include &lt;linux/input.h>
 #include &lt;linux/ioctl.h>
@@ -842,10 +844,10 @@
   unsigned IOCTL_EVIOCGPROP = IOCTL_NOT_PRESENT;
   unsigned IOCTL_EVIOCSKEYCODE_V2 = IOCTL_NOT_PRESENT;
 #endif
-  unsigned IOCTL_FS_IOC_GETFLAGS = FS_IOC_GETFLAGS;
-  unsigned IOCTL_FS_IOC_GETVERSION = FS_IOC_GETVERSION;
-  unsigned IOCTL_FS_IOC_SETFLAGS = FS_IOC_SETFLAGS;
-  unsigned IOCTL_FS_IOC_SETVERSION = FS_IOC_SETVERSION;
+  unsigned IOCTL_FS_IOC_GETFLAGS = _IOR('f', 1, long);
+  unsigned IOCTL_FS_IOC_GETVERSION = _IOR('v', 1, long);
+  unsigned IOCTL_FS_IOC_SETFLAGS = _IOW('f', 2, long);
+  unsigned IOCTL_FS_IOC_SETVERSION = _IOW('v', 2, long);
   unsigned IOCTL_GIO_CMAP = GIO_CMAP;
   unsigned IOCTL_GIO_FONT = GIO_FONT;
   unsigned IOCTL_GIO_UNIMAP = GIO_UNIMAP;
</pre>
So my question is this: How to apply a patch when installing a package with Spack? I looked at the output of `spack help install` but did not see an option to apply a patch before building a package.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by raullaasner** [comment]
I'm having trouble editing the original message so posting spack-build-env.txt separately here:
[spack-build-env.txt](https://github.com/spack/spack/files/9350672/spack-build-env.txt)

**Comment by haampie** [comment]
Is there an issue for it in the gcc bug tracker?

**Comment by raullaasner** [comment]
I searched the GCC bug tracker but could not find a related issue. I think it's not a bug if you use compatible versions of glibc and gcc (specifically, the conflict is with building libsanitizer which, as I understand, is a component of gcc). On my platform glibc was recently bumped to 2.36 but it's not possible to change or downgrade something as fundamental as glibc. In any case, I made the following edit:

<pre>diff --git a/var/spack/repos/builtin/packages/gcc/package.py b/var/spack/repos/builtin/packages/gcc/package.py
index 793c4a221d..bf4d501a11 100644
--- a/var/spack/repos/builtin/packages/gcc/package.py
+++ b/var/spack/repos/builtin/packages/gcc/package.py
@@ -341,6 +341,8 @@ class Gcc(AutotoolsPackage, GNUMirrorPackage):
     patch("piclibs.patch", when="+piclibs")
     patch("gcc-backport.patch", when="@4.7:4.9.3,5:5.3")

+    patch("glibc-2.36-libsanitizer.patch", when="@12.1.0")
+
     # Backport libsanitizer patch for glibc >= 2.31 and 5.3.0 <= gcc <= 9.2.0
     # https://bugs.gentoo.org/708346
     patch("glibc-2.31-libsanitizer-1.patch", when="@7.1.0:7.5.0,8.1.0:8.3.0,9.0.0:9.2.0")</pre>

It applies the patch I posted previously and now gcc builds fine. I will use this solution until the next version of gcc comes out.
