### ISSUE TITLE
py-cryptography@3.4.8 - failed to fetch pyo3 as dependency package of cryptography-rust: failed to fetch `https://github.com/rust-lang/crates.io-index`

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#32266]
### Steps to reproduce the issue

Reproducible using:
* `spack@develop` (364e4e03ef25976c24dd8c5f0fe9b8f981b1c336 from `Thu Aug 18 17:53:09 2022 -0500`)
* `ecpe4s/ubuntu20.04-runner-x86_64-oneapi:2022-07-01`
* `%oneapi@2022.1.0`

Environment: [spack.yaml.txt](https://github.com/spack/spack/files/9382854/spack.yaml.txt)

Install error:
```
$> spack -e . install
...
==> Installing py-cryptography-3.4.8-2bmjo36436waoywasnuffgqhjti772zq
==> No binary for py-cryptography-3.4.8-2bmjo36436waoywasnuffgqhjti772zq found: installing from source
==> Using cached archive: /spack/var/spack/cache/_source-cache/archive/94/94cc5ed4ceaefcbe5bf38c8fba6a21fc1d365bb8fb826ea1688e3370b2e24a1c.tar.gz
==> No patches needed for py-cryptography
==> py-cryptography: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    '/spack/opt/spack/linux-ubuntu20.04-x86_64/oneapi-2022.1.0/python-3.8.13-26kecxdjyqf2446yua3r24kn7qylpkdb/bin/python3.8' '-m' 'pip' '-vvv' '--no-input' '--no-cache-dir' '--disable-pip-version-check' 'install' '--no-deps' '--ignore-installed' '--no-build-isolation' '--no-warn-script-location' '--no-index' '--prefix=/spack/opt/spack/linux-ubuntu20.04-x86_64/oneapi-2022.1.0/py-cryptography-3.4.8-2bmjo36436waoywasnuffgqhjti772zq' '.'
See build log for details:
  /tmp/root/spack-stage/spack-stage-py-cryptography-3.4.8-2bmjo36436waoywasnuffgqhjti772zq/spack-build-out.txt
```

Excerpt from `spack-build-out.txt`
```
...
  running build_rust
      Updating crates.io index
  error: failed to get `pyo3` as a dependency of package `cryptography-rust v0.1.0 (/tmp/root/spack-stage/spack-stage-py-cryptography-3.4.8-2bmjo36436waoywasnuffgqhjti772zq/spack-src/src/rust)`

  Caused by:
    failed to fetch `https://github.com/rust-lang/crates.io-index`

  Caused by:
    invalid version 0 on git_proxy_options; class=Invalid (3)
...
```

### Error message

<details><summary>Error message</summary><pre>
... see above
</pre></details>

### Information on your system

* **Spack:** 0.19.0.dev0 (364e4e03ef25976c24dd8c5f0fe9b8f981b1c336)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-zen2
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/9382856/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/9382857/spack-build-out.txt)

FYI @rscohn2 @adamjstewart 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Do newer versions work?

**Comment by eugeneswalker** [comment]
> Do newer versions work?

Yes.

It looks like in this environment we have:

```
exaworks
  --> py-parsl
    --> py-globus-sdk
      --> py-cryptography@3.4.8 (hard upper version limit for py-globus-sdk dependency)
```

I will try unpinning the `py-cryptography` upper version limit on `py-globus-sdk`. Maybe it doesn't have to be this way.

**Comment by adamjstewart** [comment]
Or add a newer version of py-globus-sdk.

**Comment by eugeneswalker** [comment]
> Or add a newer version of py-globus-sdk.

It looks like more than just py-globus-sdk, there is another package that is requiring this version of py-cryptography in the environment. Do you know an easy way to find out every package in the environment that might require this ?

**Comment by adamjstewart** [comment]
You can use:
```console
$ spack dependents py-cryptography
py-adal       py-azure-identity       py-azure-multiapi-storage  py-azureml-core  py-merlin    py-pyjwt      py-requests-ntlm
py-ansible    py-azure-keyvault       py-azure-storage-blob      py-globus-sdk    py-oauthlib  py-pymysql    py-secretstorage
py-azure-cli  py-azure-keyvault-keys  py-azure-storage-common    py-maestrowf     py-paramiko  py-pyopenssl  py-urllib3
```
to find all packages that depend on `py-cryptography`, but I don't think the command is environment-aware so it's hard to narrow it down. You could also try `spack find ^py-cryptography` in the environment but that will also include transitive dependencies. If you cross-reference the two, that should give you what you want.

**Comment by eugeneswalker** [comment]
Found out there are two issues.

The first issue is the constraints in `py-globus-sdk`. Adding a newer version and unpinning the `py-cryptography` version constraint for newer version fixes that.
* https://github.com/spack/spack/pull/32280

The other issue is an improperly expressed constraint on `py-pyjwt`. I have PR for that:
* https://github.com/spack/spack/pull/32279

**Comment by adamjstewart** [comment]
What do we want to do with this? It sounds like you're now able to get newer versions working. Should we deprecate older versions so no one encounters this issue? Not sure if it's worth trying to patch or report since the upstream maintainers likely no longer support these older versions.

**Comment by eugeneswalker** [comment]
> What do we want to do with this? It sounds like you're now able to get newer versions working. Should we deprecate older versions so no one encounters this issue? Not sure if it's worth trying to patch or report since the upstream maintainers likely no longer support these older versions.

I like the idea of deprecating older versions. If someone really wants to use them, they can do it, but there is a gigantic chasm between the current versions which work and the old versions which we would deprecate, and which do not work:
```
Preferred version:
    36.0.1    https://files.pythonhosted.org/packages/source/c/cryptography/cryptography-36.0.1.tar.gz

Safe versions:
    36.0.1    https://files.pythonhosted.org/packages/source/c/cryptography/cryptography-36.0.1.tar.gz
    35.0.0    https://files.pythonhosted.org/packages/source/c/cryptography/cryptography-35.0.0.tar.gz
    3.4.8     https://files.pythonhosted.org/packages/source/c/cryptography/cryptography-3.4.8.tar.gz
    3.4.7     https://files.pythonhosted.org/packages/source/c/cryptography/cryptography-3.4.7.tar.gz
    3.2.1     https://files.pythonhosted.org/packages/source/c/cryptography/cryptography-3.2.1.tar.gz
    2.7       https://files.pythonhosted.org/packages/source/c/cryptography/cryptography-2.7.tar.gz
    2.3.1     https://files.pythonhosted.org/packages/source/c/cryptography/cryptography-2.3.1.tar.gz
    1.8.1     https://files.pythonhosted.org/packages/source/c/cryptography/cryptography-1.8.1.tar.gz
```

**Comment by adamjstewart** [comment]
> there is a gigantic chasm between the current versions which work and the old versions which we would deprecate

The chasm isn't as big as it looks, the next version after 3.4.8 was 35.0.0: https://pypi.org/project/cryptography/#history

**Comment by adamjstewart** [comment]
Note that cryptography 3.3 or older is required for Python 2 support. But I'm currently trying to deprecate Python 2 support anyway, so I don't find this to be an issue.

**Comment by adamjstewart** [comment]
I'm actually able to build cryptography 3.4.8 on my system, not sure why it's different on yours. Let's avoid deprecation for now since it seems to work some of the time. Now that you no longer need to use an older cryptography, let's close this issue.
