### ISSUE TITLE
ecp-data-vis-sdk: remove enforced `+fortran`

### ISSUE THREAD

**Issue by ax3l** [LLNL/spack#32283]
Hi,

the `ecp-data-vis-sdk` package enforces `+fortran` on a lot of packages, e.g., ADIOS2 and HDF5. This is not ideal for me, building a C++ stack where I like to avoid Fortran dependencies as much as possible to save compile time.

Can you please make the hard-coded `+fortran` forwards a variant? :)

**Comment by kwryankrattiger** [comment]
This was a topic of discussion in our group before and I can bring it up again. I am very much on the fence on being able to specify extra language support from the SDK. The use case you present here seems like it may be a valid reason to be able to disable fortran at very least.

From our previous discussion, language extensions like this off of the core C/C++ libraries for fortran and python felt like they could be options, but they are also almost always required in many stacks. The general sentiment has also been to limit the variants for the SDK to only provide high level control, it is a slippery slope to providing too many customizations at the SDK level.

**Comment by ax3l** [comment]
Thanks, to add another use case: half of our team are Mac users and I want to achieve a quick spack experience on new machines where I can keep FC and F77 to be null in compilers.yaml

I think I can achieve that already unless I use the SDK package
https://twitter.com/axccl/status/1560808524586061824
