### ISSUE TITLE
Getting a "command not found" for paraview when loading the openfoam I installed with paraview

### ISSUE THREAD

**Issue by feacluster** [LLNL/spack#32310]
I am new to spack but am familiar with installing OpenFoam from source. I first installed  openfoam@2112 . It worked well and I was able to run some tutorial models. Next I tried to install with paraview with the command, "spack install openfoam@2112+paraview". I believe it installed ok, but when I launch paraFoam, I get "paraview: command not found", per:

```
[me@node openfoam]$ paraFoam
Invalid $PV_PLUGIN_PATH and -plugin-path= not defined
No supplementary ParaView/OpenFOAM reader modules
Using builtin reader: paraFoam -vtk
Created temporary 'openfoam.foam'
/scratch/spack/me/skl/apps/linux-rhel8-skylake/gcc-11.3.0/openfoam-2112-6pjdeey7vh4ghoy2x64oum5wdeklxzyr/bin/paraFoam: line 423: paraview: command not found
```

Not sure how to debug further. I do notice there is no "paraview" in /scratch/spack/me/skl/apps/linux-rhel8-skylake/gcc-11.3.0/paraview-5.9.1-ix3al7cn33mwfuonvwq77zslpoykccag/bin

```
[me@node bin]$ pwd
/scratch/spack/me/skl/apps/linux-rhel8-skylake/gcc-11.3.0/paraview-5.9.1-ix3al7cn33mwfuonvwq77zslpoykccag/bin
[me@node bin]$ ll | awk '{print$9}'
paraview.conf
paraview-config
pvdataserver
pvrenderserver
pvserver
smTestDriver-pv5.9
vtkParseJava-pv5.9
vtkProbeOpenGLVersion-pv5.9
vtkProcessXML-pv5.9
vtkWrapClientServer-pv5.9
vtkWrapHierarchy-pv5.9
vtkWrapJava-pv5.9
vtkWrapPythonInit-pv5.9
vtkWrapPython-pv5.9
```

**Comment by adityakavalur** [comment]
@feacluster did you ever figure this out? I am running into this issue as well

**Comment by feacluster** [comment]
> @feacluster did you ever figure this out? I am running into this issue as well

I opened a chat on the discord page about this and got some helpful replies . But I can't seem to login to discord anymore to copy/paste what they said.
