### ISSUE TITLE
Installation issue: py-poetry-core

### ISSUE THREAD

**Issue by skosukhin** [LLNL/spack#32375]
Steps to reproduce the issue:

```console
$ git config --global core.excludesfile "$HOME/.gitignore"
$ echo '/whatever' >> "$HOME/.gitignore"
$ git clone https://github.com/spack/spack.git
$ cd spack
$ export SPACK_USER_CACHE_PATH="$(pwd)/whatever"
$ . share/spack/setup-env.sh
$ spack config --scope=site add "config:build_stage:[$(pwd)/whatever]"
$ spack build-env py-poetry-core -- python3 -c 'import poetry'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'poetry'
```
Spack "thinks" that `py-poetry-core` is installed successfully but it's not because all relevant files from the [`poetry`](https://github.com/python-poetry/poetry-core/tree/1.0.8/poetry) directory are missing. This happens because the stage directory is gitignored and, therefore, ignored during the installation (see [here](https://github.com/python-poetry/poetry-core/blob/1.0.8/poetry/core/masonry/builders/builder.py#L108)).

Note that removing the [`pyproject.toml`](https://github.com/python-poetry/poetry-core/blob/1.0.8/pyproject.toml) triggers the installation using `setup.py` (not present in the repo but is shipped with the [tarball](https://files.pythonhosted.org/packages/source/p/poetry-core/poetry-core-1.0.8.tar.gz)), which produces the correct result.

@adamjstewart it turns out that the problem has nothing to do with the length of the build directory prefix.

**Comment by adamjstewart** [comment]
These steps to reproduce are very involved. I wonder how common this issue actually is. From what I can tell, this seems like a bug in poetry, not a bug in Spack. Can you open an issue with poetry and see what they think? This should affect not only poetry but all packages that use poetry as a build backend.

**Comment by skosukhin** [comment]
@adamjstewart imagine what the `poetry` guys say when I tell them: "There is, you know, Spack. We love installing packages from sources. Also, some of us, like myself, do it in a way that even other spackiniacs consider as an unhealthy deviation."

I agree that it's not a bug in Spack. However, we could do several things:
1. Python packages should do `python -c 'import <package-name>'` as a post-install step. This, for example, would save me some time when I tried to figure out why the `spack style` bootstrapping didn't work: the error message was rather cryptic and related to `py-isort`, which could not be installed because of this problem with `py-poetry-core`.
2. We should consider setting `GIT_DIR` (and probably several other [environment variables](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables)) in the build environment to jail `git` in the stage prefix.
3. I don't know whether this has been resolved but I remember another git-related problem. Some packages call `git` at the build time (to generate a version file, for example). It's fair to assume (otherwise, I'd call it a bug in the package) that they implement a fallback for the case when that doesn't work (e.g. the package is built from a dist tarball). Now, Spack caches source files of packages that are fetched with `git` and uses the cache if it's available. The problem is that the `.git` subdirectory is not included in the cache tarball and we get different behaviour from the package's build system, depending on whether we install the package "for the first time" and fetch it from git or from the cache tarball. In some cases (like in the described one), it might get worse because `git` works with the `.git` subdirectory of Spack. A solution here could be to remove `.git` subdirectory as the last step of the `GitFetchStrategy`. This would make the builds consistent. Also, together with `2.`, this would help to resolve this particular issue. `git` would simply fail with `fatal: not a git repository` and the build system would treat the source directory as it's not git-tracked.

**Comment by adamjstewart** [comment]
1. We do support this. Both `spack install --test=root py-poetry-core` and `spack install py-poetry-core && spack test run py-poetry-core` will attempt to import all modules. However, it only tries to import what it sees in the installation prefix, so that probably wouldn't catch your issue. We could manually add a list of imports to attempt to every package but that would be a considerable amount of work.
2. This sounds like a good idea to me.
3. I can't remember who was working on caching of git fetches, maybe @scheibelp?

**Comment by scheibelp** [comment]
I assigned https://github.com/spack/spack/issues/32404 to myself, which is both Git and caching-related, but FYI that problem is conceptually separate (i.e. I would have very likely resolved that without fixing this, and now that I've read both, it is my explicit intent that they be resolved separately).

For this problem: I don't know why we discard `.git` when caching repos: 

* the first issue that occurs to me is that we try to pull *just* the one commit and not the full history (this doesn't strictly make `.git` useless, but it is definitely lacking information most people would expect when they `git clone` the repo themselves)
* ... but we also support `get_full_repo` (which gets all the history) and I don't know why `.archive` doesn't include `.git` in that case at least

Overall I assume that packages which call `git` at build time should probably set `get_full_repo`, but we should still modify `GitFetchStrategy.archive` to keep `.git`.

**Comment by iarspider** [comment]
I think [this issue](https://github.com/python-poetry/poetry/issues/5547) in poetry itself is also relevant.

**Comment by skosukhin** [comment]
@iarspider could you come up with a PR for Spack to patch `py-poetry-core` with your patch?

I have stumbled upon a much easier way to reproduce the issue with Spack. My `$TMPDIR` is too small and my `$HOME` is too slow, so I decided to use the old good `$spack/var/spack/stage` for staging:
```yaml
config:
  build_stage:
  - $spack/var/spack/stage
```
and `/var/spack/stage` is the first line in Spack's `.gitignore`, of course.

**Comment by adamjstewart** [comment]
I think a patch to `py-poetry-core` is only a valid approach if that same patch can be contributed upstream. I don't want to maintain a hacky patch for several versions with no end in sight.

**Comment by skosukhin** [comment]
@adamjstewart the problem is reported upstream and got quite some response. Hopefully, it will be resolved in a "proper" way. Once that happens, we remove our patch and fetch the "proper" one from the upstream repo. We do a similar thing for other packages, e.g. `llvm`.

**Comment by adamjstewart** [comment]
> We should consider setting `GIT_DIR` (and probably several other [environment variables](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables)) in the build environment to jail `git` in the stage prefix.

@scheibelp how do you feel about this solution? The poetry devs also recommended this approach: https://github.com/python-poetry/poetry/issues/5547#issuecomment-1265599210

Are there any possible issues? What if someone is behind a firewall and requires proxy stuff that is in their global git configuration file?

Where should we do this? My first thought was in `build_environment.py`, but I don't see a great spot to set non-compiler, non-spack env vars. We could also do it in `setup_build_environment`/`setup_dependent_build_environment` only for poetry packages, but it may be better to do it globally for all packages. I've also seen bug reports that `setup_dependent_build_environment` doesn't work.
