### ISSUE TITLE
Spack should look for examples in share/examples/{project-name}, not in lib/EXAMPLE

### ISSUE THREAD

**Issue by yurivict** [LLNL/spack#32419]
### Steps to reproduce

In [this](https://github.com/xiaoyeli/superlu_dist/issues/111#issuecomment-1229488965) issue the project claims that Spack needs examples in lib/EXAMPLES.

A semi-standard location for examples is ```share/examples/{project-name}```, that's where all linux/BSD package distros install them. Spack should do the same.

### Error message

n/a

### Information on your system

FreeBSD 13.1

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
Spack does not care where example code is installed to, there are no customs in Spack of using that particular directory. Spack simply executes the build system of a package and lets the package decide where it should be installed. The `superlu-dist` package is currently hard-coded to run tests in that directory, but that can easily be changed, and even changed depending on the version of `superlu-dist`. So I don't think there's anything on Spack's side that is forcing `superlu-dist` to behave this way.
