### ISSUE TITLE
[feature request] better error messages when `spack load` has multiple matches

### ISSUE THREAD

**Issue by brandongc** [LLNL/spack#32540]
### Summary

Instead of " Use a more specific spec." the message to users should also mention how to load by hash (ie prepending `/`)

Even better, the message should also give some context about what the difference between matches is (or indicate how to find that). 

### Rationale

Consider

```
perlmutter:login35:> module load e4s
perlmutter:login35:~> spack load libxml2
==> Error: libxml2 matches multiple packages.
 Matching packages:
  4eodgpo libxml2@2.9.13%cce@13.0.2 arch=cray-sles15-zen3
  uaarf7u libxml2@2.9.13%gcc@11.2.0 arch=cray-sles15-zen3
  u2ai4xj libxml2@2.9.13%gcc@11.2.0 arch=cray-sles15-zen3
 Use a more specific spec.
perlmutter:login35:~> 
perlmutter:login35:~> spack load libxml2@2.9.13%gcc@11.2.0 arch=cray-sles15-zen3
==> Error: libxml2@2.9.13%gcc@11.2.0 arch=cray-sles15-zen3 matches multiple packages.
 Matching packages:
  uaarf7u libxml2@2.9.13%gcc@11.2.0 arch=cray-sles15-zen3
  u2ai4xj libxml2@2.9.13%gcc@11.2.0 arch=cray-sles15-zen3
 Use a more specific spec.
> spack load uaarf7u
==> Error: Spec 'uaarf7u' matches no installed packages.
```

1. One has to "just know" to add a `/` for `spack load /uaarf7u` to work
2. There is no obvious difference between "uaarf7u" and "u2ai4xj"

### Additional information

```
> spack --version
0.18.0.dev0 (6040c82740449632aa1d6faab08f93f5e4c54615)
```

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Personally I would love for `spack load` to behave like `module load` and use `--first` by default. By the way, if you didn't know, you can use `spack load --first` if you don't care about the difference.

**Comment by shahzebsiddiqui** [comment]
Could we make the default behavior `spack load <spec>` emulate `spack load --first` and that way we don't need `--first` as an option. If one specifies an explicit spec then it should still work and only error out if the spec is not in the database or invalid hash has been specified. Right now one can't do `spack load cmake` or anything since spack install a bunch of specs at the same version and one has to be very explicit.

**Comment by tldahlgren** [comment]
> Could we make the default behavior `spack load <spec>` emulate `spack load --first` and that way we don't need `--first` as an option. If one specifies an explicit spec then it should still work and only error out if the spec is not in the database or invalid hash has been specified. Right now one can't do `spack load cmake` or anything since spack install a bunch of specs at the same version and one has to be very explicit.

Ah.  After I already started adding unit tests for the requested fix.

**Comment by brandongc** [comment]
I think a behavior change to a basic command is a probably a different issue/discussion? (or at least the title of this issue no longer matches)That seems to be a more significant change to how spack works.
