### ISSUE TITLE
Unwanted concretization behavior with externals and `iconv:: [libc]` in `packages.yaml`

### ISSUE THREAD

**Issue by greenc-FNAL** [LLNL/spack#32620]
### Steps to reproduce

With etc/spack/linux/packages.yaml containing (only):
```.yaml
---
packages:
  all:
    providers:
      pkgconfig:
        - pkg-config
      iconv:: [libc]
      rpc:: [libc]
  libc:
    version:
      - 2.17
    variants: +iconv+rpc
    externals:
      - spec: libc@2.17+iconv+rpc%gcc@4.8.5 os=scientific7
        prefix: /usr
    buildable: false
```

Compare:
```.yaml
$ spack clean -ab
$ spack -d --yaml diffutils > diffutils-spec.yaml 2>&1
```
with
```.yaml
$ spack clean -ab
$ spack -d --yaml diffutils@3.8 > diffutils@3.8-spec.yaml 2>&1
```

In the attached example output, note that the former case concretizes to:
```.yaml
$ spack spec -It diffutils
Input spec
--------------------------------
 -   [    ]  diffutils

Concretized
--------------------------------
 -   [    ]  diffutils@3.7%gcc@4.8.5 arch=linux-scientific7-x86_64
 -   [bl  ]      ^libiconv@1.15%gcc@4.8.5 arch=linux-scientific7-x86_64
```
and the latter to:
```.yaml
$ spack spec -It diffutils@3.8
Input spec
--------------------------------
 -   [    ]  diffutils@3.8

Concretized
--------------------------------
 -   [    ]  diffutils@3.8%gcc@4.8.5 arch=linux-scientific7-haswell
 -   [bl  ]      ^libc@2.17%gcc@4.8.5+iconv+rpc arch=linux-scientific7-haswell
```

[diffutils-spec-yaml.txt](https://github.com/spack/spack/files/9551256/diffutils-spec-yaml.txt)
[diffutils-3.8-spec-yaml.txt](https://github.com/spack/spack/files/9551257/diffutils-3.8-spec-yaml.txt)

### Information on your system

* **Spack:** 0.19.0.dev0@6e5dc7374cefc2fbade06582fb56b45126c97b9b.
* **Python:** 3.6.8
* **Platform:** linux-scientific7-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by greenc-FNAL** [comment]
Note: from my point of view, the former, less-constrained spec is neither understood nor desired, and the latter is what is wanted.

**Comment by Kasbr305** [comment]
Hi🫠

**Comment by alalazo** [comment]
Would this be solved by package requirements?

**Comment by greenc-FNAL** [comment]
This may be solved by a combination of package requirements, and #35450. Still to be verified.

**Comment by alalazo** [comment]
Any news on whether this was solved by requirements + #35450 ?

**Comment by greenc-FNAL** [comment]
I believe this is resolved, thank you. If I experience further problems, I will open a new issue.

**Comment by alalazo** [comment]
Thanks!
