### ISSUE TITLE
OSPRay support in ParaView

### ISSUE THREAD

**Issue by mvictoras** [LLNL/spack#32656]
### Summary

@chuckatkins @danlipsa @vicentebolea Would be nice to have OSPRay support in the PV package. This is so we can use Catalyst for in situ rendering.

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by vicentebolea** [comment]
I might be wrong but I believe there is no OSpray package in Spack. It will be nice to have somebody from Intel to take care of this :)

**Comment by kwryankrattiger** [comment]
CC'ing myself on this

**Comment by mvictoras** [comment]
@kwryankrattiger is there an ETA for this?

**Comment by kwryankrattiger** [comment]
No ETA yet.
