### ISSUE TITLE
Spack uses too many make processes by default

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#327]
I ran Spack on a particular modern workstation, and realized that it was calling make as `make -j40`. The system has 20 cores and hyperthreading enabled, so I see where the number `40` is coming from. However, I think it is too large.

There should be an option to set a machine-specific default for the maximum amount of parallelism, e.g. an option in `.spack`.

**Comment by tgamblin** [comment]
Did you see [this discussion on the google group](https://groups.google.com/forum/#!topic/spack/viVmaAUQCj4)? There were some suggestions (some fairly complicated) for setting this value.  You *can* use `spack install -j<N>` for your favorite `N`.  I'm not sure there is default setting that makes everyone happy, though.

I think you want to set the default and not the max.  If the user wants to build with 400 make jobs, they should be able to, even they don't get any benefit.  Setting a default is more complicated.  Performance-wise, it depends on the particular build. More complex packages will take more advantage of the parallelism, until the system becomes bandwidth bound, and then I guess you want to pick a setting that doesn't thrash your disk read speed.  Policy-wise, it depends on the number of users on the node and *their* usage of the system... that's even more complicated.  IMHO, there should be some interaction with the OS to dynamically control spawning, but AFAIK something like that is not getting integrated into Linux any time soon.

One compromise I suggested was if Spack used *half* the number of cores by default.  Would that be better until I can add a better config file option?  #210 will make it easy for me to add a config file option pretty soon...

**Comment by eschnett** [comment]
There are HPC systems where there is a rather strict ulimit on the number of processes that can be active per user. On these systems, I usually have to specify `-j 4` for every build. I'd like to be able to set the default `-j` value up once for such systems. I don't think Spack can auto-detect this (although looking at `ulimit` might be a way...).

Other limitations come from file systems. These days, there are systems with 20 cores and hyper-threading, and there are network file systems that degrade terribly if one builds with 40 processes. If there are other users on the system, I receive angry emails. (I also receive them if I just type `ninja`, which uses the same defaults as Spack.) To protect myself, I'd also like to be able to set up something once on such a system, so that I don't have to recall using `-j 4` every time.

Regardless of the above, a reasonable default for me would be to ignore hyperthreading when counting cores.

**Comment by mathstuf** [comment]
Does using `-l4` help or does the I/O blockage not get counted (and since the CPU is ahead, just spawn even more I/O)?

**Comment by tgamblin** [comment]
I think @escnett is looking for some better configuration options.

@eschnett: if you want to hack this you could either change `set_module_variables_for_package` in `build_environment.py` or you could add `make_jobs = <N>` as a class property in `Package` in `package.py`.

When we have a Spack `config.yaml` this will go there.

**Comment by adamjstewart** [comment]
@tgamblin Can this be added to `config.yaml`?

**Comment by alalazo** [comment]
@tgamblin Would a PR adding an option to `config.yaml` be sufficient to close this issue?
