### ISSUE TITLE
Installation issue: mfem

### ISSUE THREAD

**Issue by amit112amit** [LLNL/spack#32739]
### Steps to reproduce the issue

```console
$ spack spec -I
Input spec
--------------------------------
mfem@4.4.0+examples+miniapps+petsc+shared+slepc+sundials+threadsafe

Concretized
--------------------------------
d7b2a2p  mfem@4.4.0%gcc@12.2.1~amgx~conduit~cuda~debug+examples~exceptions~fms~gnutls~gslib~lapack~libceed~libunwind+metis+miniapps~mpfr+mpi~netcdf~occa~openmp+petsc~pumi~raja~rocm+shared+slepc+static~strumpack~suite-sparse+sundials~superlu-dist+threadsafe~umpire+zlib timer=auto arch=linux-fedora36-skylake
4oful6r      ^hypre@2.25.0%gcc@12.2.1~complex~cuda~debug+fortran~gptune~int64~internal-superlu~mixedint+mpi~openmp~rocm+shared~superlu-dist~unified-memory arch=linux-fedora36-skylake
sn57izn          ^openblas@0.3.20%gcc@12.2.1~bignuma~consistent_fpcsr~ilp64+locking+pic+shared patches=9f12903 symbol_suffix=none threads=none arch=linux-fedora36-skylake
cigkbvw              ^perl@5.34.1%gcc@12.2.1+cpanm+shared+threads arch=linux-fedora36-skylake
vs6k2iz                  ^berkeley-db@18.1.40%gcc@12.2.1+cxx~docs+stl patches=26090f4,b231fcc arch=linux-fedora36-skylake
kld2ax3                  ^bzip2@1.0.8%gcc@12.2.1~debug~pic+shared arch=linux-fedora36-skylake
xof6fm7                      ^diffutils@3.8%gcc@12.2.1 arch=linux-fedora36-skylake
j3zm66g                          ^libiconv@1.16%gcc@12.2.1 libs=shared,static arch=linux-fedora36-skylake
45filhf                  ^gdbm@1.19%gcc@12.2.1 arch=linux-fedora36-skylake
w7devjg                      ^readline@8.1.2%gcc@12.2.1 arch=linux-fedora36-skylake
xopryzi                          ^ncurses@6.3%gcc@12.2.1~symlinks+termlib abi=none arch=linux-fedora36-skylake
odf5f3y                              ^pkgconf@1.8.0%gcc@12.2.1 arch=linux-fedora36-skylake
qgj2k3j                  ^zlib@1.2.12%gcc@12.2.1+optimize+pic+shared patches=0d38234 arch=linux-fedora36-skylake
cv767dt          ^openmpi@4.1.4%gcc@12.2.1~atomics~cuda~cxx~cxx_exceptions~gpfs~internal-hwloc~java~legacylaunchers~lustre~memchecker+romio+rsh~singularity+static+vt+wrapper-rpath fabrics=none schedulers=none arch=linux-fedora36-skylake
ixqxzyo              ^hwloc@2.8.0%gcc@12.2.1~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm+shared arch=linux-fedora36-skylake
6c2qton                  ^libpciaccess@0.16%gcc@12.2.1 arch=linux-fedora36-skylake
q66gcmk                      ^libtool@2.4.7%gcc@12.2.1 arch=linux-fedora36-skylake
asuik52                          ^m4@1.4.19%gcc@12.2.1+sigsegv patches=9dc5fbd,bfdffa7 arch=linux-fedora36-skylake
nvmamix                              ^libsigsegv@2.13%gcc@12.2.1 arch=linux-fedora36-skylake
kbvhoyv                      ^util-macros@1.19.3%gcc@12.2.1 arch=linux-fedora36-skylake
b7fiys5                  ^libxml2@2.10.1%gcc@12.2.1~python arch=linux-fedora36-skylake
a4hlmtn                      ^xz@5.2.5%gcc@12.2.1~pic libs=shared,static arch=linux-fedora36-skylake
ez3pvq2              ^numactl@2.0.14%gcc@12.2.1 patches=4e1d78c,62fc8a8,ff37630 arch=linux-fedora36-skylake
z3ifuwh                  ^autoconf@2.69%gcc@12.2.1 patches=35c4492,7793209,a49dd5b arch=linux-fedora36-skylake
cdlvyok                  ^automake@1.16.5%gcc@12.2.1 arch=linux-fedora36-skylake
2hlwdbm              ^openssh@9.0p1%gcc@12.2.1+gssapi arch=linux-fedora36-skylake
hrhd2ue                  ^krb5@1.19.3%gcc@12.2.1+shared arch=linux-fedora36-skylake
a7ksxqy                      ^bison@3.8.2%gcc@12.2.1 arch=linux-fedora36-skylake
qv5z3ni                      ^gettext@0.21%gcc@12.2.1+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-fedora36-skylake
4bkhibl                          ^tar@1.34%gcc@12.2.1 zip=pigz arch=linux-fedora36-skylake
e75owqo                              ^pigz@2.7%gcc@12.2.1 arch=linux-fedora36-skylake
oourobw                              ^zstd@1.5.2%gcc@12.2.1+programs compression=none libs=shared,static arch=linux-fedora36-skylake
k22outw                      ^openssl@1.1.1q%gcc@12.2.1~docs~shared certs=mozilla patches=3fdcf2d arch=linux-fedora36-skylake
wpkrm44                          ^ca-certificates-mozilla@2022-07-19%gcc@12.2.1 arch=linux-fedora36-skylake
tondsus                  ^libedit@3.1-20210216%gcc@12.2.1 arch=linux-fedora36-skylake
qzev4do              ^pmix@4.1.2%gcc@12.2.1~docs+pmi_backwards_compatibility~restful arch=linux-fedora36-skylake
doykilh                  ^libevent@2.1.12%gcc@12.2.1+openssl arch=linux-fedora36-skylake
qf7kzd6      ^metis@5.1.0%gcc@12.2.1~gdb~int64~real64+shared build_type=Release patches=4991da9,b1225da arch=linux-fedora36-skylake
xmnq2lq          ^cmake@3.23.3%gcc@12.2.1~doc+ncurses+ownlibs~qt build_type=Release arch=linux-fedora36-skylake
yb54ae4      ^petsc@3.17.4%gcc@12.2.1~X~batch~cgns~complex~cuda~debug+double~exodusii~fftw+fortran~giflib+hdf5~hpddm~hwloc+hypre~int64~jpeg~knl~kokkos~libpng~libyaml~memkind+metis~mkl-pardiso~mmg~moab~mpfr+mpi~mumps~openmp~p4est~parmmg~ptscotch~random123~rocm~saws~scalapack+shared~strumpack~suite-sparse+superlu-dist~tetgen~trilinos~valgrind clanguage=C arch=linux-fedora36-skylake
hcycwbu          ^hdf5@1.12.2%gcc@12.2.1~cxx~fortran~hl~ipo~java+mpi+shared~szip~threadsafe+tools api=default build_type=RelWithDebInfo arch=linux-fedora36-skylake
g7sem7m          ^parmetis@4.0.3%gcc@12.2.1~gdb~int64~ipo+shared build_type=RelWithDebInfo patches=4f89253,50ed208,704b84f arch=linux-fedora36-skylake
eojmmre          ^python@3.9.13%gcc@12.2.1+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93,4c24573,f2fd060 arch=linux-fedora36-skylake
vhydb2c              ^expat@2.4.8%gcc@12.2.1+libbsd arch=linux-fedora36-skylake
u7ma4p2                  ^libbsd@0.11.5%gcc@12.2.1 arch=linux-fedora36-skylake
m2sxsoj                      ^libmd@1.0.4%gcc@12.2.1 arch=linux-fedora36-skylake
ftym7we              ^libffi@3.4.2%gcc@12.2.1 arch=linux-fedora36-skylake
5jx4s4l              ^sqlite@3.39.2%gcc@12.2.1+column_metadata+dynamic_extensions+fts~functions+rtree arch=linux-fedora36-skylake
zwtmxr5              ^util-linux-uuid@2.37.4%gcc@12.2.1 arch=linux-fedora36-skylake
yzaew4u          ^superlu-dist@7.2.0%gcc@12.2.1~cuda~int64~ipo~openmp~rocm+shared build_type=RelWithDebInfo patches=8da9e21 arch=linux-fedora36-skylake
ykksxng      ^slepc@3.17.2%gcc@12.2.1+arpack~blopex~cuda~rocm arch=linux-fedora36-skylake
qxijnnz          ^arpack-ng@3.8.0%gcc@12.2.1+mpi+shared arch=linux-fedora36-skylake
o3aksad      ^sundials@5.8.0%gcc@12.2.1+ARKODE+CVODE+CVODES+IDA+IDAS+KINSOL~cuda+examples+examples-install~f2003~fcmix+generic-math+hypre~int64~ipo~klu~lapack~magma~monitoring+mpi~openmp~petsc~pthread~raja~rocm+shared+static~superlu-dist~superlu-mt~sycl~trilinos build_type=RelWithDebInfo cstd=99 cxxstd=14 patches=a707dfd precision=double arch=linux-fedora36-skylake
```

### Error message

<details><summary>Error message</summary><pre>
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8' 'lib'

2 errors found in build log:
     233    /home/amit/Software/Installations/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/openmpi-4.1.4-cv767dtypco2xoz4prkspg734t7amcfd/bin/mpic++ -fPIC  -O3 -std=c+
            +11 -I/home/amit/Software/Installations/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/hypre-2.25.0-4oful6rfkozijyoioq4wnb6xvlhdz35e/include -I/home/amit/Sof
            tware/Installations/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/metis-5.1.0-qf7kzd6z7bqgbetmewzqishvbtzzryku/include -I/home/amit/Software/Installations/s
            pack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/sundials-5.8.0-o3aksadnlsr7ppc5slkmelmj5bdnqthe/include -I/home/amit/Software/Installations/spack/opt/spack/lin
            ux-fedora36-skylake/gcc-12.2.1/petsc-3.17.4-yb54ae4jtt3yznzo4qqxouiwpmf4fvf4/include -I/home/amit/Software/Installations/spack/opt/spack/linux-fedora36-skylake/
            gcc-12.2.1/slepc-3.17.2-ykksxngbi37f6ahotgdfeykyz2e6bmof/include -I/home/amit/Software/Installations/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/zlib-1.2.
            12-qgj2k3joej45pbqd7uuy3qla3tk3lgpn/include  -c fem/fe/fe_rt.cpp -o fem/fe/fe_rt.o
     234    /home/amit/Software/Installations/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/openmpi-4.1.4-cv767dtypco2xoz4prkspg734t7amcfd/bin/mpic++ -fPIC  -O3 -std=c+
            +11 -I/home/amit/Software/Installations/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/hypre-2.25.0-4oful6rfkozijyoioq4wnb6xvlhdz35e/include -I/home/amit/Sof
            tware/Installations/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/metis-5.1.0-qf7kzd6z7bqgbetmewzqishvbtzzryku/include -I/home/amit/Software/Installations/s
            pack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/sundials-5.8.0-o3aksadnlsr7ppc5slkmelmj5bdnqthe/include -I/home/amit/Software/Installations/spack/opt/spack/lin
            ux-fedora36-skylake/gcc-12.2.1/petsc-3.17.4-yb54ae4jtt3yznzo4qqxouiwpmf4fvf4/include -I/home/amit/Software/Installations/spack/opt/spack/linux-fedora36-skylake/
            gcc-12.2.1/slepc-3.17.2-ykksxngbi37f6ahotgdfeykyz2e6bmof/include -I/home/amit/Software/Installations/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/zlib-1.2.
            12-qgj2k3joej45pbqd7uuy3qla3tk3lgpn/include  -c fem/fe/fe_ser.cpp -o fem/fe/fe_ser.o
     235    /home/amit/Software/Installations/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/openmpi-4.1.4-cv767dtypco2xoz4prkspg734t7amcfd/bin/mpic++ -fPIC  -O3 -std=c+
            +11 -I/home/amit/Software/Installations/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/hypre-2.25.0-4oful6rfkozijyoioq4wnb6xvlhdz35e/include -I/home/amit/Sof
            tware/Installations/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/metis-5.1.0-qf7kzd6z7bqgbetmewzqishvbtzzryku/include -I/home/amit/Software/Installations/s
            pack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/sundials-5.8.0-o3aksadnlsr7ppc5slkmelmj5bdnqthe/include -I/home/amit/Software/Installations/spack/opt/spack/lin
            ux-fedora36-skylake/gcc-12.2.1/petsc-3.17.4-yb54ae4jtt3yznzo4qqxouiwpmf4fvf4/include -I/home/amit/Software/Installations/spack/opt/spack/linux-fedora36-skylake/
            gcc-12.2.1/slepc-3.17.2-ykksxngbi37f6ahotgdfeykyz2e6bmof/include -I/home/amit/Software/Installations/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/zlib-1.2.
            12-qgj2k3joej45pbqd7uuy3qla3tk3lgpn/include  -c fem/ceed/algebraic.cpp -o fem/ceed/algebraic.o
     236    /home/amit/Software/Installations/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/openmpi-4.1.4-cv767dtypco2xoz4prkspg734t7amcfd/bin/mpic++ -fPIC  -O3 -std=c+
            +11 -I/home/amit/Software/Installations/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/hypre-2.25.0-4oful6rfkozijyoioq4wnb6xvlhdz35e/include -I/home/amit/Sof
            tware/Installations/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/metis-5.1.0-qf7kzd6z7bqgbetmewzqishvbtzzryku/include -I/home/amit/Software/Installations/s
            pack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/sundials-5.8.0-o3aksadnlsr7ppc5slkmelmj5bdnqthe/include -I/home/amit/Software/Installations/spack/opt/spack/lin
            ux-fedora36-skylake/gcc-12.2.1/petsc-3.17.4-yb54ae4jtt3yznzo4qqxouiwpmf4fvf4/include -I/home/amit/Software/Installations/spack/opt/spack/linux-fedora36-skylake/
            gcc-12.2.1/slepc-3.17.2-ykksxngbi37f6ahotgdfeykyz2e6bmof/include -I/home/amit/Software/Installations/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/zlib-1.2.
            12-qgj2k3joej45pbqd7uuy3qla3tk3lgpn/include  -c fem/ceed/convection.cpp -o fem/ceed/convection.o
     237    /home/amit/Software/Installations/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/openmpi-4.1.4-cv767dtypco2xoz4prkspg734t7amcfd/bin/mpic++ -fPIC  -O3 -std=c+
            +11 -I/home/amit/Software/Installations/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/hypre-2.25.0-4oful6rfkozijyoioq4wnb6xvlhdz35e/include -I/home/amit/Sof
            tware/Installations/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/metis-5.1.0-qf7kzd6z7bqgbetmewzqishvbtzzryku/include -I/home/amit/Software/Installations/s
            pack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/sundials-5.8.0-o3aksadnlsr7ppc5slkmelmj5bdnqthe/include -I/home/amit/Software/Installations/spack/opt/spack/lin
            ux-fedora36-skylake/gcc-12.2.1/petsc-3.17.4-yb54ae4jtt3yznzo4qqxouiwpmf4fvf4/include -I/home/amit/Software/Installations/spack/opt/spack/linux-fedora36-skylake/
            gcc-12.2.1/slepc-3.17.2-ykksxngbi37f6ahotgdfeykyz2e6bmof/include -I/home/amit/Software/Installations/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/zlib-1.2.
            12-qgj2k3joej45pbqd7uuy3qla3tk3lgpn/include  -c fem/ceed/diffusion.cpp -o fem/ceed/diffusion.o
     238    fem/fe/fe_rt.cpp: In member function 'virtual void mfem::RT_WedgeElement::CalcDivShape(const mfem::IntegrationPoint&, mfem::Vector&) const':
  >> 239    fem/fe/fe_rt.cpp:1180:27: error: 'RTSegmentFE' was not declared in this scope; did you mean 'H1SegmentFE'?
     240     1180 |    Vector      trt_dshape(RTSegmentFE.GetDof());
     241          |                           ^~~~~~~~~~~
     242          |                           H1SegmentFE
  >> 243    make: *** [makefile:438: fem/fe/fe_rt.o] Error 1
     244    make: *** Waiting for unfinished jobs....
</pre></details>

### Information on your system

* **Spack:** 0.19.0.dev0 (71434d8b9d05e5d89a57ba992ded2d22ef6e6765)
* **Python:** 3.10.6
* **Platform:** linux-fedora36-skylake
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/9612868/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/9612877/spack-build-out.txt)

The output of

```console
[user@hostname]$ spack maintainers mfem
acfisher  goxberry  markcmiller86  tzanio  v-dobrev
```
Mentioning the maintainers
@acfisher
@goxberry 
@markcmiller86 
@tzanio 
@v-dobrev 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by tzanio** [comment]
Thanks for reporting this, it is actually a bug in a mode we are not testing regularly.

**Comment by v-dobrev** [comment]
This issue was resolved in https://github.com/mfem/mfem/pull/2919 which is part of MFEM v4.5. This version of MFEM will be added to Spack with #33480.
