### ISSUE TITLE
Do not export SPACK_PYTHON when sourcing setup_env.sh

### ISSUE THREAD

**Issue by wyphan** [LLNL/spack#32747]
### Summary

This happens on a RHEL 7.6 system where the system Python is version 2.7.5 at `/usr/bin/python` and `/usr/bin/python2` and Python 3 is provided through modules. `/usr/bin/python3` does not exist.

If the following order of operations are executed through `.bashrc`,
```bash
. ${HOME}/sw/spack/share/spack/setup-env.sh
module load GCC/11.3.0 Python/3.10.4
```
then Spack is locked to use Python 2 even though Python 3 is available through the `Python/3.10.4` module.

Output of `$ spack debug report`:
* **Spack:** 0.19.0.dev0
* **Python:** 2.7.5
* **Platform:** linux-rhel7-ivybridge
* **Concretizer:** clingo

Output of `env | grep SPACK`:
```
SPACK_ROOT=/home/wp11/sw/spack
SPACK_LD_LIBRARY_PATH=/opt/apps/software/binutils/2.38-GCCcore-11.3.0/lib:/opt/apps/software/zlib/1.2.12-GCCcore-11.3.0/lib:/opt/app
s/software/GCCcore/11.3.0/lib64
SPACK_PYTHON=/usr/bin/python
 eval "if [ -n \"\${${var}-}\" ]; then export SPACK_$var=\${${var}}; fi";
```

This issue arises considering with the [plan to drop Python 2 support in Spack](https://github.com/spack/spack/discussions/31824) and that #32615 has been merged to deprecate Python 2 in Spack 0.19.

The expected behavior of Spack using Python 3 can be achieved by overriding `SPACK_PYTHON` or manually exporting it after the module is loaded. Output of `$ SPACK_PYTHON=$(which python3) spack debug report`:
* **Spack:** 0.19.0.dev0
* **Python:** 3.10.4
* **Platform:** linux-rhel7-ivybridge
* **Concretizer:** clingo

### Rationale

Currently [setup-env.sh](../tree/develop/share/spack/setup-env.sh) locks and exports `SPACK_PYTHON` [here](https://github.com/spack/spack/blob/d07b200b6704d821555b6b8e02a94d731ffb5168/share/spack/setup-env.sh#L335):
```python
# Identify and lock the python interpreter
for cmd in "${SPACK_PYTHON:-}" python3 python python2; do
    if command -v > /dev/null "$cmd"; then
        export SPACK_PYTHON="$(command -v "$cmd")"
        break
    fi
done
```

### Description

- There should be a better way to manage when `SPACK_PYTHON` gets locked, especially such that it doesn't break Spack environments.
- I think a deprecation warning can be added in 0.19 when Spack uses Python 2, which can be converted later into an error in Spack 0.20 when Spack Python 2 support actually ends.
- Alternatively, a `python-bootstrap` recipe can be added and used during the Spack bootstrap process for 0.20. This recipe will also be useful for Spack users with no admin rights that are stuck with systems with only Python 2 for whatever reason.

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
I also find it confusing that Spack doesn't respect `PATH` by default and you have to override `SPACK_PYTHON` if you want to change it. Does anyone else know why we made that decision?

**Comment by alalazo** [comment]
@adamjstewart See https://github.com/spack/spack/pull/21222#issuecomment-767560765
