### ISSUE TITLE
Unable to build Boost with Python 3

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#3274]
I'm trying to build Boost 1.63.0 with Python 3.6.0, but it is failing. The build output contains lines like:
```
./boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory
 # include <pyconfig.h>
                       ^
compilation terminated.
```
My `user-config.jam` looks like:
```
using gcc : : /blues/gpfs/home/software/spack-0.10.0/lib/spack/env/gcc/g++ ;
using python : 3.6 : /blues/gpfs/home/software/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-6.1.0/python-3.6.0-prk6gk3ufbfetjc2bthqokmkjtjnce3j/bin/python : /blues/gpfs/home/software/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-6.1.0/python-3.6.0-prk6gk3ufbfetjc2bthqokmkjtjnce3j/include/python3.6m :  ;
```
`/blues/gpfs/home/software/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-6.1.0/python-3.6.0-prk6gk3ufbfetjc2bthqokmkjtjnce3j/include/python3.6m` does indeed contain `pyconfig.h`, so I'm surprised by this error message. Anyone ever built Boost with Python 3 before?

**Comment by wscullin** [comment]
Can you try:

`
using python  
 :  3.6 : /blues/gpfs/home/software/spack-0.10.0/opt/spack/linux-centos6-x86_64/gcc-6.1.0/python-3.6.0-prk6gk3ufbfetjc2bthqokmkjtjnce3j ;
`

I've run into a path length issue before on the BG/Q that was solved by using the prefix.

**Comment by adamjstewart** [comment]
Unfortunately that didn't solve the problem. Same error message.

**Comment by scheibelp** [comment]
I have not tried building boost with python3.

Does the following link look relevant? https://svn.boost.org/trac/boost/ticket/11120

**Comment by adamjstewart** [comment]
Thanks @scheibelp, the patch at the very bottom worked! I also had to change the `--with-python=%s` line, as we were passing `python` instead of `python3`. I'll send out a PR shortly.
