### ISSUE TITLE
show status of active spack view (spack env view status)

### ISSUE THREAD

**Issue by shahzebsiddiqui** [LLNL/spack#32829]
@becker33 @tldahlgren @tgamblin 

### Summary

We have options `spack env view enable` and `spack env view disable` to change between views but we have no way of telling which view we are in. Similar to `spack env status` which shows the current environment i'd like to see which view we are in.

### Rationale

We would like to deploy multiple views and user should be able to tell which view they are in and switch between views so `spack env view status` with a short option `spack env view st` can be used to show the full path to view_path that is active.

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by becker33** [comment]
Closing this issue as it demonstrates a misunderstanding of `spack env view enable/disable`. Talking with @shahzebsiddiqui out of band about other potential features.
