### ISSUE TITLE
Fine-Grained Control over the reuse-process

### ISSUE THREAD

**Issue by flxmr** [LLNL/spack#32888]
### Summary

So, as I mentioned on the Slack, I would like to have all specs with a specific `target=<desc>` at the root be concretized with that target enforced for all dependencies. So I want to disable reusing non-target dependencies I'd argue.

Where should I start? Would I add an option to the concretizer (seems HARD) or do I just override something in lib/spack/spack/spec.py?

Also: it might be sensible to add more specific rules around the reusing-process (consistent compilers, making security-relevant stuff not be reused). Are there any plans for this?

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
> So, as I mentioned on the Slack, I would like to have all specs with a specific target=<desc> at the root be concretized with that target enforced for all dependencies

Can you be more specific by, e.g. providing one or more concrete use cases? Asking because, depending on the complexity of what you need, this might be already doable with `packages:<name>:require` modulo the bugfix in #32528

**Comment by flxmr** [comment]
Thank you I'll try this in a minute, still looking throught the asp.py.

Essentially I would like a kind of "minimal architecture", which is used by default even if there are packages to reuse. E.g. it might happen that for some reason our ansible-playbook starts building package X for `target=x86_64_v3` (which is some old machines). Then later, something requires package X when building for e.g. `target=skylake_avx512` – here I would like to not reuse anything built with `target=x86_64_v3` (it does currently), but just like to have everything built with `target=skylake_avx512`. If your patch does this, it should be fine for now; longterm I think it would be nice if one could have a flag for spack install like `--reuse-archs x86_64_v3,x86_64_v4`. As reading through asp.py looks like, this shouldn't be too hard either, when I would know, what function to add to `SpackSolverSetup.setup()` ;).

[I generally would like to reuse at least minor version across targets, because otherwise builds take ages and eat up TB of disk soon]

**Comment by flxmr** [comment]
So, from my reading of asp.py the "easiest" (and probably cleanest way) would be to just add some flags to the concretizer config and then just filter here accordingly: https://github.com/spack/spack/blob/7d50fd3b8e82f93df73b86d54a8d15df4ec07b2b/lib/spack/spack/solver/asp.py#L2359

could any of core developers please confirm this is "the way", then I'll try to add more flags to control reuse and make a merge-request on that (excluding packages with relevant security issues, like most recently `expat` also would seem like a nice switch)?

**Comment by simonLeary42** [comment]
I was about to request the same thing.

I was asking around in the spack slack about this issue:
```
spack install --verbose -y --reuse zlib%intel arch=linux-ubuntu20.04-x86_64_v3
==> Error: Cannot concretize 'zlib' with multiple targets
    Requested 'target=x86_64' and 'target=x86_64_v3'
```
And I heard back from @tgamblin :
> it might be unintuitive but you’re asking for both --reuse and for zlib SPECIFICALLY to have the x86_64_v3 target
> but because it’s reusing I think it is telling you that your selected target isn’t the same as the reused one

I feel like if I'm asking for a particular architecture, `--reuse` should be able to do it's job within those bounds.

**Comment by flxmr** [comment]
also (just leaving this here as a note to me): if I have some "basic" specs lying around it looks like target-specifications in the defaults are not really respected when concretizing environments.
