### ISSUE TITLE
setuptools breaks when using inheritance with packages

### ISSUE THREAD

**Issue by iarspider** [LLNL/spack#32922]
### Steps to reproduce the issue

```console
$ mkdir -p cms/packages/py-setuptools
$ wget https://github.com/iarspider/cms-spack-repo/raw/CMSSW_12_6_X/repos/cms/packages/py-setuptools/package.py -O cms/packages/py-setuptools/package.py
$ spack repo create `pwd`/cms cms
$ spack repo add cms
$ spack install py-setuptools 63.4.3
```

### Error message

```
==> Error: NameError: name 'python' is not defined

/home/razumov/spack-setuptools/var/spack/repos/builtin/packages/py-setuptools/package.py:196, in install:
        193        # We work around this issue by installing setuptools from wheels
        194        whl = self.stage.archive_file
        195        args = ["-m", "pip"] + std_pip_args + ["--prefix=" + prefix, whl]
  >>    196        python(*args)
```

### Information on your system

* **Spack:** 0.19.0.dev0 (cf0c4523f34360a601e0e73e12eb36d317862916)
* **Python:** 3.10.7
* **Platform:** linux-fedora36-skylake
* **Concretizer:** clingo

### Additional information

Looks similar to https://github.com/spack/spack/issues/31648, so could be a duplicate.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Yep, looks like a duplicate, just a different error message. I've never used external repos before so unfortunately I can't help.
