### ISSUE TITLE
Inconsistent documentation on setup_dependent_environment

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#3294]
Take a look at the [documentation](http://spack.readthedocs.io/en/latest/packaging_guide.html#setup-dependent-environment) for `setup_dependent_environment`. In the first example, we see:
```python
def setup_dependent_environment(self, module, spec, dep_spec):
```
with a definition of each parameter. In the second example, we see:
```python
def setup_dependent_environment(self, spack_env, run_env, extension_spec):
```
with completely different parameters. This second example matches the parameters for the [documentation](http://spack.readthedocs.io/en/latest/module_file_support.html#package-file-api) on `setup_environment`:
```python
def setup_environment(self, spack_env, run_env):
```
We should make sure all of these examples, and the uses in Spack packages, are consistent. Things will work fine the way they are, but it's just confusing. Similarly, I could use:
```python
def install(self, spec, prefix):
```
and:
```python
def install(self, prefix, spec):
```
interchangeably, but it would be very confusing to see `if '+python' in prefix:` in a package.

Also, we aren't consistent on how we recommend setting environment variables during the build. In the first example, we see:
```python
def setup_dependent_environment(self, module, spec, dep_spec):
    """Dependencies of Qt find it using the QTDIR environment variable."""
    os.environ['QTDIR'] = self.prefix
```
while in the second example we see:
```python
def setup_dependent_environment(self, spack_env, run_env, extension_spec):
    """Set PYTHONPATH to include site-packages dir for the
    extension and any other python extensions it depends on."""
    ...
    spack_env.set('PYTHONHOME', prefix.strip('\n'))
```
We need to decide whether we want people to use `os.environ` or `spack_env`/`run_env`.

**Comment by alalazo** [comment]
@adamjstewart The first signature is probably a leftover from before `spack_env` and the other callbacks were introduced. I think we should always change environment variables using `spack_env`, as it gives the possibility to check the changes before applying them.
