### ISSUE TITLE
"spack test" doesn't list "flake8"

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#3301]
I submitted a pull request, and Travis complained since `Flake8 found errors.`. I wanted to use `spack test` to run flake8 locally to save time, but flake8 doesn't seem to be among the available tests.

**Comment by adamjstewart** [comment]
`spack flake8`. See the contribution guide in the documentation.

**Comment by alalazo** [comment]
Relevant documentation [here](https://spack.readthedocs.io/en/latest/contribution_guide.html#flake8-tests). Closing the issue.
