### ISSUE TITLE
[Solved manually] Installation issue: pigz@2.7%oneapi@2022.1.0

### ISSUE THREAD

**Issue by ADKoishi** [LLNL/spack#33125]
### Steps to reproduce the issue

```console
$ spack install pigz%oneapi@2022.1.0
```

### Error message

<details><summary>Error message</summary><pre>
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

2 errors found in build log:
     12    gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -Wcast-qual -c zopfli/src/zopfli/cache.c
     13    gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -Wcast-qual -c zopfli/src/zopfli/hash.c
     14    gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -Wcast-qual -c zopfli/src/zopfli/util.c
     15    gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -Wcast-qual -c zopfli/src/zopfli/squeeze.c
     16    gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -Wcast-qual -c zopfli/src/zopfli/katajainen.c
     17    gcc -O3 -Wall -Wextra -Wno-unknown-pragmas -Wcast-qual -c zopfli/src/zopfli/symbols.c
  >> 18    pigz.c:415:10: fatal error: zlib.h: No such file or directory
     19      415 | #include "zlib.h"       // deflateInit2(), deflateReset(), deflate(),
     20          |          ^~~~~~~~
     21    compilation terminated.
  >> 22    make: *** [<builtin>: pigz.o] Error 1
     23    make: *** Waiting for unfinished jobs....

</pre></details>

### Information on your system

* **Spack:** 0.18.1
* **Python:** 3.9.10
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** clingo

### Additional information

This issue can be solved by manually editing the Makefile by 
adding -I[pathToZlib2]/include
editing CC as icx
in the temporary build dir in spack-src 
and reinstall the package with --dont-restage option

### General information

- [x] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
Fixed by https://github.com/spack/spack/pull/30912
