### ISSUE TITLE
setup-env.sh takes 1.5s to run

### ISSUE THREAD

**Issue by certik** [LLNL/spack#3318]
For some reason, the shell support takes 1.5s to run:
```
$ time . /home/certik/repos/spack/share/spack/setup-env.sh

real    0m1.452s
user    0m1.236s
sys     0m0.160s
```
That prevents me to put it into `.bashrc`, because then every time I open a new terminal window, I have to wait 1.5s.

**Comment by adamjstewart** [comment]
You might be interested in #2880.

**Comment by citibeth** [comment]
What do you need shell integration for?  If you are planning on using `spack load`, you will probably find it's also slower than you like.  Look in the docs about `spack module loads` to generate module load scripts, or (even faster to load) `spack view` to put everything you need in one tree.

**Comment by certik** [comment]
@citibeth I just want to be able to load the packages somehow. `module available` doesn't list the spack packages, unless the shell integration is enabled. But given how slow it is to enable it, I can't keep it enabled all the time. 

I just want something that's fast and that allows me to use the modules, reliably. See also #3295.

**Comment by adamjstewart** [comment]
@certik All you need to do is add the appropriate directory to your `MODULEPATH` in your `~/.bashrc`. It's a small part of what `setup-env.sh` does.

**Comment by certik** [comment]
@adamjstewart ah, that's it! Thank you, that makes it work for me. Here is the relevant part of my `.bashrc`, for reference:
```
# This is too slow (https://github.com/LLNL/spack/issues/3318):
#. /home/certik/repos/spack/share/spack/setup-env.sh
# So we add the appropriate directory to MODULPATH by hand for now:
export MODULEPATH="/home/certik/repos/spack/share/spack/modules/linux-ubuntu16-x86_64:$MODULEPATH"
```

**Comment by adamjstewart** [comment]
I'll close this issue then. Any discussion on ways to speed up our shell integration can continue in #2880.

**Comment by citibeth** [comment]
On Fri, Mar 3, 2017 at 5:31 PM, Ondřej Čertík <notifications@github.com>
wrote:

> @citibeth <https://github.com/citibeth> I just want to be able to load
> the packages somehow. module available doesn't list the spack packages,
> unless the shell integration is enabled.
>

Just set your `MODULEPATH` env var.  You don't need all the other shell
integration stuff.
