### ISSUE TITLE
`spack env` gives "RuntimeError: Cannot locate python executable"

### ISSUE THREAD

**Issue by certik** [LLNL/spack#3319]
Here is how to reproduce it:
```
$ spack cd mesa@10.2.4 %gcc@5.4.0
~/.../mesa-10.2.4-gqowes7nvl5cnpgvpakilmzrcktjvnhs/Mesa-10.2.4$ spack env mesa@10.2.4 %gcc@5.4.0
Traceback (most recent call last):
  File "/home/certik/repos/spack/bin/spack", line 212, in <module>
    main(sys.argv)
  File "/home/certik/repos/spack/bin/spack", line 208, in main
    _main(args, unknown)
  File "/home/certik/repos/spack/bin/spack", line 174, in _main
    return_val = command(parser, args)
  File "/home/certik/repos/spack/lib/spack/spack/cmd/env.py", line 62, in env
    build_env.setup_package(spec.package)
  File "/home/certik/repos/spack/lib/spack/spack/build_environment.py", line 513, in setup_package
    dpkg.setup_dependent_environment(spack_env, run_env, spec)
  File "/home/certik/repos/spack/var/spack/repos/builtin/packages/python/package.py", line 358, in setup_dependent_environment
    raise RuntimeError('Cannot locate python executable')
RuntimeError: Cannot locate python executable
```

**Comment by adamjstewart** [comment]
A few questions:

1. What version of Python are you running Spack with?
2. Are you using an external Python installation in your `packages.yaml`?
3. What version of Python are you building mesa with?
4. What is the Python executable called?
5. You don't have it symlinked in any weird way do you? Maybe you're using Homebrew or something like that to install Python?

If I had to guess, you're using Python as an external package in `packages.yaml`. Make sure the prefix is set to `/usr` instead of `/usr/bin` or `/usr/bin/python`.

**Comment by certik** [comment]
1. 2.7.12
2. where is this file `packages.yaml`, I didn't find it in `.spack`. I didn't modify any such file by hand though, as far as I know.
3. I used the default spack settings
4. The systemwide is /usr/bin/python
5. I use a stock Ubuntu 16.04.

**Comment by adamjstewart** [comment]
2. It would be in `~/.spack/packages.yaml`, but if you didn't modify it then it doesn't matter anyway.

So it sounds like you tried to build mesa, but it crashed during the process. Can you run `spack find -p python` to see which version of Python it installed and where it is installed? Then tell me what Python executable(s) it installed. It could be called `python`, `python2`, or `python3`.

**Comment by certik** [comment]
The contents of my `~/.spack` directory is:
```
$ ls ~/.spack
cache  config.yaml  linux
```
and the Python package installed `python` and `python2`:
```
$ spack find -p python
==> 1 installed packages.
-- linux-ubuntu16-x86_64 / gcc@5.4.0 ----------------------------
    python@2.7.13  /home/certik/repos/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/python-2.7.13-5gx5sb5s5ns2cmne3qwnl632omokfdqu
$ ls /home/certik/repos/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/python-2.7.13-5gx5sb5s5ns2cmne3qwnl632omokfdqu/bin
2to3  pydoc   python2    python2.7-config  python-config
idle  python  python2.7  python2-config    smtpd.py
```

I removed all packages from spack and all my local modifications, and just used the unmodified development branch, and I can still reproduce the problem using:
```
spack install mesa %gcc@5.4.0
spack cd mesa %gcc@5.4.0
spack env mesa %gcc@5.4.0
```
The reason mesa itself fails to build is due to:
```
checking for XCB_DRI3... yes
checking for XF86VIDMODE... no
checking for DRIGL... yes
configure: error: libudev-dev or sysfs required for building DRI
```
But that's not relevant I assume for this bug.

**Comment by adamjstewart** [comment]
> The reason mesa itself fails to build is due to:
> ```
> checking for XCB_DRI3... yes
> checking for XF86VIDMODE... no
> checking for DRIGL... yes
> configure: error: libudev-dev or sysfs required for building DRI
> ```

Yeah, I ran into that same problem the last time I messed with the Mesa package. I'm the one who added the comment about "libudev" to the package. Btw, I have a work-in-progress `systemd` package in #2631, but gave up on it because I couldn't get `glibc` to build.

Anyway, yeah, that's not relevant to the bug. Let me think some more.

**Comment by adamjstewart** [comment]
When I run:
```
$ spack env mesa %gcc@5.3.0
```
I see a completely different bug:
```
Traceback (most recent call last):
  File "/blues/gpfs/home/ajstewart/spack/bin/spack", line 212, in <module>
    main(sys.argv)
  File "/blues/gpfs/home/ajstewart/spack/bin/spack", line 208, in main
    _main(args, unknown)
  File "/blues/gpfs/home/ajstewart/spack/bin/spack", line 174, in _main
    return_val = command(parser, args)
  File "/blues/gpfs/home/ajstewart/spack/lib/spack/spack/cmd/env.py", line 71, in env
    os.execvp(cmd[0], cmd)
  File "/usr/lib64/python2.6/os.py", line 344, in execvp
    _execvpe(file, args)
  File "/usr/lib64/python2.6/os.py", line 380, in _execvpe
    func(fullname, *argrest)
OSError: [Errno 2] No such file or directory
```
Removing the spack between `mesa` and `%gcc@5.3.0` solves this bug and things behave as expected. Can you see if this fixes it for you? If not it could be an unrelated bug.

**Comment by certik** [comment]
That was it!
```
$ spack env mesa %gcc@5.4.0                       
Traceback (most recent call last):
  File "/home/certik/repos/spack/bin/spack", line 212, in <module>
    main(sys.argv)
  File "/home/certik/repos/spack/bin/spack", line 208, in main
    _main(args, unknown)
  File "/home/certik/repos/spack/bin/spack", line 174, in _main
    return_val = command(parser, args)
  File "/home/certik/repos/spack/lib/spack/spack/cmd/env.py", line 62, in env
    build_env.setup_package(spec.package)
  File "/home/certik/repos/spack/lib/spack/spack/build_environment.py", line 513
, in setup_package
    dpkg.setup_dependent_environment(spack_env, run_env, spec)
  File "/home/certik/repos/spack/var/spack/repos/builtin/packages/python/package
.py", line 358, in setup_dependent_environment
    raise RuntimeError('Cannot locate python executable')
RuntimeError: Cannot locate python executable
```
vs. (btw you meant space instead of spack, it took me a while to figure out what you meant):
```
$ spack env mesa%gcc@5.4.0
...
UPSTART_EVENTS=started starting
SPACK_FC_RPATH_ARG=-Wl,-rpath,
XDG_SESSION_TYPE=x11
SPACK_FILE=/home/certik/repos/spack/bin/spack
SPACK_PREFIX=/home/certik/repos/spack/opt/spack/linux-ubuntu16-x86_64/gcc-5.4.0/mesa-12.0.3-sbxzhjexfzwpflfa7xkdwjrdqzib7har
...
```
and it works.

Thanks for figuring it out!

**Comment by adamjstewart** [comment]
Ha, comment fixed. Glad it was a simple solution!

**Comment by adamjstewart** [comment]
Btw, I took a closer look at `spack env`. Most of our commands allow spaces inside of specs, but `spack env` doesn't. I'm pretty sure this is on purpose. You can add arguments after your spec to run a command, for example:
```
spack spec mesa%gcc@5.4.0 ./configure --prefix=~/mesa
```
The easiest way to figure out what is the spec and what is the command to run is to take everything after the first space and assume it is the command to run. In your case, you were trying to run `%gcc@5.4.0`.

**Comment by certik** [comment]
Ah, ok. I didn't realize that. Thanks for figuring it out. That's tricky.

**Comment by yee379** [comment]
i'm having the same issue building mesa:

    checking for DRIGL... yes
    configure: error: libudev-dev or sysfs required for building DRI

any solution to this?

**Comment by adamjstewart** [comment]
As far as I know, nothing has changed from my comment on [Mar 2](https://github.com/LLNL/spack/issues/3319#issuecomment-283793430). I've never been able to build systemd, nor have I found a standalone libudev download. Until either of those change, you probably won't be able to build mesa. I think systemd is available on CentOS 7, so this is really a CentOS 6 problem only.

**Comment by JusticeForMikeBrown** [comment]
@adamjstewart 

Mesa cannot be built on Centos or RHEL 6 with current build options given Mesa wants udev 151 or greater which cannot be obtained via yum or source from what I can attest so far.

Though has anyone ever tried compiling mesa with "--disable-dri3?"

**Comment by adamjstewart** [comment]
Never tried that, but if it works that would be very helpful. I had just given up on installing mesa.

**Comment by JusticeForMikeBrown** [comment]
@adamjstewart 

I am trying it now.  I have a user that needs rgl.  But in order to add that package first need mesa compiled!

**Comment by JusticeForMikeBrown** [comment]
@adamjstewart 

I was able to build.  Submitting PR.
