### ISSUE TITLE
raja@2022.03.0 +rocm fails: g++-11: error: unrecognized command-line option '--offload-arch=gfx900'

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#33249]
### Steps to reproduce the issue

Having trouble building `raja@2022.03.0 +rocm`

<details><summary>Concretization</summary><pre>
==> Concretized raja+rocm amdgpu_target=gfx90a
 -   ltz5si5  raja@2022.03.0%gcc@11.1.0~cuda+examples+exercises~ipo~openmp+rocm+shared~tests amdgpu_target=gfx90a build_type=RelWithDebInfo arch=linux-ubuntu20.04-x86_64
[+]  y36fzbw      ^blt@0.5.2%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  5ihoqvh          ^cmake@3.20.6%gcc@11.1.0~doc+ncurses+ownlibs~qt build_type=Release arch=linux-ubuntu20.04-x86_64
[+]  i2hv5jc              ^ncurses@6.3%gcc@11.1.0~symlinks+termlib abi=none arch=linux-ubuntu20.04-x86_64
[+]  6kp4r3o                  ^pkgconf@1.8.0%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  faop6us              ^openssl@1.1.1q%gcc@11.1.0~docs~shared certs=mozilla patches=3fdcf2d arch=linux-ubuntu20.04-x86_64
[+]  t3c4o5i                  ^ca-certificates-mozilla@2022-07-19%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  3drusxj                  ^perl@5.34.1%gcc@11.1.0+cpanm+shared+threads arch=linux-ubuntu20.04-x86_64
[+]  fzp4src                      ^berkeley-db@18.1.40%gcc@11.1.0+cxx~docs+stl patches=26090f4,b231fcc arch=linux-ubuntu20.04-x86_64
[+]  3gilvnw                      ^bzip2@1.0.8%gcc@11.1.0~debug~pic+shared arch=linux-ubuntu20.04-x86_64
[+]  6id7p5g                          ^diffutils@3.8%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  nxnzjyt                              ^libiconv@1.16%gcc@11.1.0 libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]  u3nqjvs                      ^gdbm@1.19%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  tfambxv                          ^readline@8.1.2%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  hdtjtng                      ^zlib@1.2.12%gcc@11.1.0+optimize+pic+shared patches=0d38234 arch=linux-ubuntu20.04-x86_64
[+]  xy7tm6z      ^camp@2022.03.2%gcc@11.1.0~cuda~ipo~openmp+rocm~tests amdgpu_target=gfx90a build_type=RelWithDebInfo arch=linux-ubuntu20.04-x86_64
[+]  hfpcdg2          ^hip@5.2.3%gcc@11.1.0~ipo build_type=Release patches=7ed1232 arch=linux-ubuntu20.04-x86_64
[+]  ow27dxy              ^comgr@5.2.3%gcc@11.1.0~ipo build_type=Release arch=linux-ubuntu20.04-x86_64
[+]  vagrfdi                  ^llvm-amdgpu@5.2.3%gcc@11.1.0~ipo~link_llvm_dylib~llvm_dylib~openmp+rocm-device-libs build_type=Release patches=a08bbe1 arch=linux-ubuntu20.04-x86_64
[+]  gftl34f                      ^python@3.8.13%gcc@11.1.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib patches=0d98e93,4c24573,f2fd060 arch=linux-ubuntu20.04-x86_64
[+]  3ns5tna                          ^expat@2.4.8%gcc@11.1.0+libbsd arch=linux-ubuntu20.04-x86_64
[+]  kibpzfz                              ^libbsd@0.11.5%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  5zyum6y                                  ^libmd@1.0.4%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  uswfuz3                          ^gettext@0.21%gcc@11.1.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-ubuntu20.04-x86_64
[+]  qlk2epp                              ^libxml2@2.10.1%gcc@11.1.0~python arch=linux-ubuntu20.04-x86_64
[+]  gwvbhfp                                  ^xz@5.2.5%gcc@11.1.0+pic libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]  2kugi24                              ^tar@1.34%gcc@11.1.0 zip=pigz arch=linux-ubuntu20.04-x86_64
[+]  6jrwfc4                                  ^pigz@2.7%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  x3a2d4r                                  ^zstd@1.5.2%gcc@11.1.0+programs compression=none libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]  5qtg5wc                          ^libffi@3.4.2%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  ihcyikh                          ^sqlite@3.39.2%gcc@11.1.0+column_metadata+dynamic_extensions+fts~functions+rtree arch=linux-ubuntu20.04-x86_64
[+]  dsfre7u                          ^util-linux-uuid@2.37.4%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  zj7acxm                      ^z3@4.8.16%gcc@11.1.0~gmp~ipo~python build_type=RelWithDebInfo arch=linux-ubuntu20.04-x86_64
[+]  vrt2z4v                  ^rocm-cmake@5.2.3%gcc@11.1.0~ipo build_type=Release arch=linux-ubuntu20.04-x86_64
[+]  xzv3omk              ^glx@1.4%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  5b57tdg                  ^mesa@22.1.2%gcc@11.1.0+glx+llvm+opengl~opengles+osmesa~strip buildtype=release default_library=shared patches=ee737d1 arch=linux-ubuntu20.04-x86_64
[+]  xu7jvvq                      ^bison@3.8.2%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  acee3tg                          ^m4@1.4.19%gcc@11.1.0+sigsegv patches=9dc5fbd,bfdffa7 arch=linux-ubuntu20.04-x86_64
[+]  u7hwsy2                              ^libsigsegv@2.13%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  ml5tvbh                      ^flex@2.6.3%gcc@11.1.0+lex~nls arch=linux-ubuntu20.04-x86_64
[+]  5mzjae6                          ^findutils@4.9.0%gcc@11.1.0 patches=440b954 arch=linux-ubuntu20.04-x86_64
[+]  iv6zhz3                      ^glproto@1.4.17%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  5ihrf5i                          ^util-macros@1.19.3%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  ylfxdla                      ^libunwind@1.6.2%gcc@11.1.0~block_signals~conservative_checks~cxx_exceptions~debug~debug_frame+docs+pic+tests+weak_backtrace+xz~zlib components=none libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]  vex4vcl                      ^libx11@1.7.0%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  fis6jp6                          ^inputproto@2.3.2%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  yhhhztg                          ^kbproto@1.0.7%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  pe7dxpq                          ^libxcb@1.14%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  ub7ci27                              ^libpthread-stubs@0.4%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  t7xel4f                              ^libxau@1.0.8%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  w6cnc4k                                  ^xproto@7.0.31%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  n7q2iq6                              ^libxdmcp@1.1.2%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  mref4sa                              ^xcb-proto@1.14.1%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  t22vlc2                          ^xextproto@7.3.0%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  3mwnaio                          ^xtrans@1.3.5%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  24i2cnb                      ^libxext@1.3.3%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  4smd4xv                      ^libxt@1.1.5%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  mhfncfu                          ^libice@1.0.9%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  h52iyaq                          ^libsm@1.2.3%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  e6mv35z                      ^meson@0.63.2%gcc@11.1.0 patches=9c87472,aa6c50d arch=linux-ubuntu20.04-x86_64
[+]  wfpqhjm                          ^ninja@1.11.0%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  yhbf5kl                          ^py-pip@22.2.2%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  zchroq5                          ^py-setuptools@65.0.0%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  s5roi7t                          ^py-wheel@0.37.1%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  uqmugj7                      ^py-mako@1.2.2%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  aza5h7i                          ^py-markupsafe@2.1.1%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  ku4fu3r                      ^xrandr@1.5.0%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  l63xxu7                          ^libxrandr@1.5.0%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  towhy7y                              ^libxrender@0.9.10%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  efo3pqc                                  ^renderproto@0.11.1%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  qqopv4v                              ^randrproto@1.5.0%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  nyqryd3              ^hsa-rocr-dev@5.2.3%gcc@11.1.0+image~ipo+shared build_type=Release patches=71e6851 arch=linux-ubuntu20.04-x86_64
[+]  yted4k6                  ^elfutils@0.186%gcc@11.1.0+bzip2~debuginfod~nls+xz arch=linux-ubuntu20.04-x86_64
[+]  xo6atzn                  ^hsakmt-roct@5.2.3%gcc@11.1.0~ipo+shared build_type=Release patches=f926273 arch=linux-ubuntu20.04-x86_64
[+]  t67ee5n                      ^libdrm@2.4.110%gcc@11.1.0~docs arch=linux-ubuntu20.04-x86_64
[+]  dch343z                          ^libpciaccess@0.16%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  tqvtjqs                              ^libtool@2.4.7%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  jpprdqh                      ^numactl@2.0.14%gcc@11.1.0 patches=4e1d78c,62fc8a8,ff37630 arch=linux-ubuntu20.04-x86_64
[+]  m4tefbd                          ^autoconf@2.69%gcc@11.1.0 patches=35c4492,7793209,a49dd5b arch=linux-ubuntu20.04-x86_64
[+]  mgplfvc                          ^automake@1.16.5%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  ymzwm3g                  ^xxd-standalone@8.2.1201%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  occp6xt              ^perl-file-which@1.22%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  y74btj7              ^perl-uri-encode@1.1.1%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  mw2f3sb                  ^perl-module-build@0.4224%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  7ql2d75              ^rocminfo@5.2.3%gcc@11.1.0~ipo build_type=Release arch=linux-ubuntu20.04-x86_64
[+]  gb5nbls              ^roctracer-dev-api@5.2.3%gcc@11.1.0 arch=linux-ubuntu20.04-x86_64
[+]  5yvj2bh      ^rocprim@5.2.3%gcc@11.1.0~ipo amdgpu_target=auto build_type=Release arch=linux-ubuntu20.04-x86_64
</pre></details>

Build error:
```
==> Installing raja-2022.03.0-ltz5si5tuwx6essz7cfoulxivnrbckgh
==> No binary for raja-2022.03.0-ltz5si5tuwx6essz7cfoulxivnrbckgh found: installing from source
==> Using cached archive: /spack/var/spack/cache/_source-cache/git//LLNL/RAJA.git/v2022.03.0.tar.gz
==> Warning: Fetching from mirror without a checksum!
  This package is normally checked out from a version control system, but it has been archived on a spack mirror.  This means we cannot know a checksum for the tarball in advance. Be sure that your connection to this mirror is secure!
==> No patches needed for raja
==> raja: Executing phase: 'initconfig'
==> raja: Executing phase: 'cmake'
==> raja: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

23 errors found in build log:
     122    /spack/lib/spack/env/gcc/g++ -DRAJA_EXPORTS -D__HIP_PLATFORM_AMD__=1 -D__HIP_PLATFORM_HCC__=1 -I/tmp/root/spack-stage/spack-stage-raja-2022.03.0-ltz5si5tuwx6es
            sz7cfoulxivnrbckgh/spack-src/include -I/tmp/root/spack-stage/spack-stage-raja-2022.03.0-ltz5si5tuwx6essz7cfoulxivnrbckgh/spack-build-ltz5si5/include -isystem /
            spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hip-5.2.3-hfpcdg2uumxftpzv7uhcstwixila35hj/include -isystem /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-1
            1.1.0/llvm-amdgpu-5.2.3-vagrfdijduqwiu34udaobkgt4hr3cp7q/lib/clang/14.0.0/include/.. -isystem /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hsa-rocr-dev
            -5.2.3-nyqryd3jg6ifbyypfduiam5guuuzt2ax/include -isystem /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/rocprim-5.2.3-5yvj2bhumn44xq236jccmmnnvcdjvqmm/in
            clude -isystem /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/camp-2022.03.2-xy7tm6zzfp745gbctojfhjx4obtydnay/include -Wall -Wextra      -O2 -g -DNDEBUG
            -fPIC --rocm-path=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hip-5.2.3-hfpcdg2uumxftpzv7uhcstwixila35hj -x hip --offload-arch=gfx900 -std=c++14 -MD -
            MT CMakeFiles/RAJA.dir/src/MemUtils_CUDA.cpp.o -MF CMakeFiles/RAJA.dir/src/MemUtils_CUDA.cpp.o.d -o CMakeFiles/RAJA.dir/src/MemUtils_CUDA.cpp.o -c /tmp/root/sp
            ack-stage/spack-stage-raja-2022.03.0-ltz5si5tuwx6essz7cfoulxivnrbckgh/spack-src/src/MemUtils_CUDA.cpp
     123    [  5%] Building CXX object CMakeFiles/RAJA.dir/src/MemUtils_SYCL.cpp.o
     124    /spack/lib/spack/env/gcc/g++ -DRAJA_EXPORTS -D__HIP_PLATFORM_AMD__=1 -D__HIP_PLATFORM_HCC__=1 -I/tmp/root/spack-stage/spack-stage-raja-2022.03.0-ltz5si5tuwx6es
            sz7cfoulxivnrbckgh/spack-src/include -I/tmp/root/spack-stage/spack-stage-raja-2022.03.0-ltz5si5tuwx6essz7cfoulxivnrbckgh/spack-build-ltz5si5/include -isystem /
            spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hip-5.2.3-hfpcdg2uumxftpzv7uhcstwixila35hj/include -isystem /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-1
            1.1.0/llvm-amdgpu-5.2.3-vagrfdijduqwiu34udaobkgt4hr3cp7q/lib/clang/14.0.0/include/.. -isystem /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hsa-rocr-dev
            -5.2.3-nyqryd3jg6ifbyypfduiam5guuuzt2ax/include -isystem /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/rocprim-5.2.3-5yvj2bhumn44xq236jccmmnnvcdjvqmm/in
            clude -isystem /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/camp-2022.03.2-xy7tm6zzfp745gbctojfhjx4obtydnay/include -Wall -Wextra      -O2 -g -DNDEBUG
            -fPIC --rocm-path=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hip-5.2.3-hfpcdg2uumxftpzv7uhcstwixila35hj -x hip --offload-arch=gfx900 -std=c++14 -MD -
            MT CMakeFiles/RAJA.dir/src/MemUtils_HIP.cpp.o -MF CMakeFiles/RAJA.dir/src/MemUtils_HIP.cpp.o.d -o CMakeFiles/RAJA.dir/src/MemUtils_HIP.cpp.o -c /tmp/root/spack
            -stage/spack-stage-raja-2022.03.0-ltz5si5tuwx6essz7cfoulxivnrbckgh/spack-src/src/MemUtils_HIP.cpp
     125    [  6%] Building CXX object CMakeFiles/RAJA.dir/src/PluginStrategy.cpp.o
     126    /spack/lib/spack/env/gcc/g++ -DRAJA_EXPORTS -D__HIP_PLATFORM_AMD__=1 -D__HIP_PLATFORM_HCC__=1 -I/tmp/root/spack-stage/spack-stage-raja-2022.03.0-ltz5si5tuwx6es
            sz7cfoulxivnrbckgh/spack-src/include -I/tmp/root/spack-stage/spack-stage-raja-2022.03.0-ltz5si5tuwx6essz7cfoulxivnrbckgh/spack-build-ltz5si5/include -isystem /
            spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hip-5.2.3-hfpcdg2uumxftpzv7uhcstwixila35hj/include -isystem /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-1
            1.1.0/llvm-amdgpu-5.2.3-vagrfdijduqwiu34udaobkgt4hr3cp7q/lib/clang/14.0.0/include/.. -isystem /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hsa-rocr-dev
            -5.2.3-nyqryd3jg6ifbyypfduiam5guuuzt2ax/include -isystem /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/rocprim-5.2.3-5yvj2bhumn44xq236jccmmnnvcdjvqmm/in
            clude -isystem /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/camp-2022.03.2-xy7tm6zzfp745gbctojfhjx4obtydnay/include -Wall -Wextra      -O2 -g -DNDEBUG
            -fPIC --rocm-path=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hip-5.2.3-hfpcdg2uumxftpzv7uhcstwixila35hj -x hip --offload-arch=gfx900 -std=c++14 -MD -
            MT CMakeFiles/RAJA.dir/src/MemUtils_SYCL.cpp.o -MF CMakeFiles/RAJA.dir/src/MemUtils_SYCL.cpp.o.d -o CMakeFiles/RAJA.dir/src/MemUtils_SYCL.cpp.o -c /tmp/root/sp
            ack-stage/spack-stage-raja-2022.03.0-ltz5si5tuwx6essz7cfoulxivnrbckgh/spack-src/src/MemUtils_SYCL.cpp
     127    /spack/lib/spack/env/gcc/g++ -DRAJA_EXPORTS -D__HIP_PLATFORM_AMD__=1 -D__HIP_PLATFORM_HCC__=1 -I/tmp/root/spack-stage/spack-stage-raja-2022.03.0-ltz5si5tuwx6es
            sz7cfoulxivnrbckgh/spack-src/include -I/tmp/root/spack-stage/spack-stage-raja-2022.03.0-ltz5si5tuwx6essz7cfoulxivnrbckgh/spack-build-ltz5si5/include -isystem /
            spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hip-5.2.3-hfpcdg2uumxftpzv7uhcstwixila35hj/include -isystem /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-1
            1.1.0/llvm-amdgpu-5.2.3-vagrfdijduqwiu34udaobkgt4hr3cp7q/lib/clang/14.0.0/include/.. -isystem /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hsa-rocr-dev
            -5.2.3-nyqryd3jg6ifbyypfduiam5guuuzt2ax/include -isystem /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/rocprim-5.2.3-5yvj2bhumn44xq236jccmmnnvcdjvqmm/in
            clude -isystem /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/camp-2022.03.2-xy7tm6zzfp745gbctojfhjx4obtydnay/include -Wall -Wextra      -O2 -g -DNDEBUG
            -fPIC --rocm-path=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hip-5.2.3-hfpcdg2uumxftpzv7uhcstwixila35hj -x hip --offload-arch=gfx900 -std=c++14 -MD -
            MT CMakeFiles/RAJA.dir/src/PluginStrategy.cpp.o -MF CMakeFiles/RAJA.dir/src/PluginStrategy.cpp.o.d -o CMakeFiles/RAJA.dir/src/PluginStrategy.cpp.o -c /tmp/root
            /spack-stage/spack-stage-raja-2022.03.0-ltz5si5tuwx6essz7cfoulxivnrbckgh/spack-src/src/PluginStrategy.cpp
  >> 128    g++-11: error: unrecognized command-line option '--rocm-path=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hip-5.2.3-hfpcdg2uumxftpzv7uhcstwixila35hj'
  >> 129    g++-11: error: unrecognized command-line option '--rocm-path=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hip-5.2.3-hfpcdg2uumxftpzv7uhcstwixila35hj'
  >> 130    g++-11: error: unrecognized command-line option '--rocm-path=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hip-5.2.3-hfpcdg2uumxftpzv7uhcstwixila35hj'
  >> 131    g++-11: error: unrecognized command-line option '--rocm-path=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hip-5.2.3-hfpcdg2uumxftpzv7uhcstwixila35hj'
  >> 132    g++-11: error: unrecognized command-line option '--rocm-path=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hip-5.2.3-hfpcdg2uumxftpzv7uhcstwixila35hj'
  >> 133    g++-11: error: unrecognized command-line option '--rocm-path=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hip-5.2.3-hfpcdg2uumxftpzv7uhcstwixila35hj'
  >> 134    g++-11: error: unrecognized command-line option '--rocm-path=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/hip-5.2.3-hfpcdg2uumxftpzv7uhcstwixila35hj'
  >> 135    g++-11: error: unrecognized command-line option '--offload-arch=gfx900'
  >> 136    g++-11: error: unrecognized command-line option '--offload-arch=gfx900'
  >> 137    make[2]: *** [CMakeFiles/RAJA.dir/build.make:149: CMakeFiles/RAJA.dir/src/MemUtils_SYCL.cpp.o] Error 1
     138    make[2]: *** Waiting for unfinished jobs....
  >> 139    make[2]: *** [CMakeFiles/RAJA.dir/build.make:163: CMakeFiles/RAJA.dir/src/PluginStrategy.cpp.o] Error 1
  >> 140    g++-11: error: unrecognized command-line option '--offload-arch=gfx900'
  >> 141    g++-11: error: unrecognized command-line option '--offload-arch=gfx900'
  >> 142    g++-11: error: unrecognized command-line option '--offload-arch=gfx900'
  >> 143    make[2]: *** [CMakeFiles/RAJA.dir/build.make:79: CMakeFiles/RAJA.dir/src/AlignedRangeIndexSetBuilders.cpp.o] Error 1
  >> 144    make[2]: *** [CMakeFiles/RAJA.dir/build.make:107: CMakeFiles/RAJA.dir/src/LockFreeIndexSetBuilders.cpp.o] Error 1
  >> 145    g++-11: error: unrecognized command-line option '--offload-arch=gfx900'
  >> 146    make[2]: *** [CMakeFiles/RAJA.dir/build.make:93: CMakeFiles/RAJA.dir/src/DepGraphNode.cpp.o] Error 1
  >> 147    make[2]: *** [CMakeFiles/RAJA.dir/build.make:135: CMakeFiles/RAJA.dir/src/MemUtils_HIP.cpp.o] Error 1
  >> 148    g++-11: error: unrecognized command-line option '--offload-arch=gfx900'
  >> 149    make[2]: *** [CMakeFiles/RAJA.dir/build.make:121: CMakeFiles/RAJA.dir/src/MemUtils_CUDA.cpp.o] Error 1
     150    make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-raja-2022.03.0-ltz5si5tuwx6essz7cfoulxivnrbckgh/spack-build-ltz5si5'
  >> 151    make[1]: *** [CMakeFiles/Makefile2:273: CMakeFiles/RAJA.dir/all] Error 2
     152    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-raja-2022.03.0-ltz5si5tuwx6essz7cfoulxivnrbckgh/spack-build-ltz5si5'
  >> 153    make: *** [Makefile:139: all] Error 2

```

### Error message

<details><summary>Error message</summary><pre>
... see above
</pre></details>

### Information on your system

* **Spack:** 0.19.0.dev0 (4b866e8ffc69d89064cf011675f63de12684ef76)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** clingo

### Additional information

[CMakeOutput.log](https://github.com/spack/spack/files/9767009/CMakeOutput.log)
[CMakeError.log](https://github.com/spack/spack/files/9767010/CMakeError.log)
[spack-build-env.txt](https://github.com/spack/spack/files/9767011/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/9767012/spack-build-out.txt)

@davidbeckingsale @wspear @mcfadden8 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by davidbeckingsale** [comment]
Can you try building with amdclang++ as the C++ compiler?

**Comment by eugeneswalker** [comment]
> Can you try building with amdclang++ as the C++ compiler?

What would that compiler definition look like? 

Would it be possible to change the RAJA package.py so it chooses the correct compiler like other `+rocm` packages in Spack? For instance, see https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/amr-wind/package.py#L94-L95 (There are other examples but this one comes to mind quick, most that I've seen do the same thing where they set CMAKE_CXX_COMPILER to `hipcc`)
