### ISSUE TITLE
Combine Environments Under One View

### ISSUE THREAD

**Issue by RikkiButler20** [LLNL/spack#33313]
### Summary

Add the capability to combine any number of environments together under one view.

### Description

Entry point
Check for conflicts in existing environments
Print new combined view
Entry point on the concretize command

Example: 
`spack env combine concretize --name current env1 env2 ... env6 eConf`
`spack -e current install`
generate: current/spack.yaml & current/spack.lock

### Additional information

* **Spack:** 0.19.0.dev0
* **Python:** 3.7.2
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** clingo

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by tldahlgren** [comment]
There's precedent for using `-n` and `--name` as options (see `spack create` and `spack module`).

**Comment by Paul-Ferrell** [comment]
This looks fine. There's a couple definitional things we need to be clear about though. 

If we're building environments **A**, **B**, and **C**, **(A + B + C)** should equal **(A)** + **(B)** + **(C)**. IE - the union of the results, not the union of the inputs. I need to be able to build each by themselves, toss those packages into the build cache, and then build **A + B + C** without needing anything new or different built. 

This will keep things mostly predictable, there are already enough sources of chaos in the process as it is (what happens to be in the build cache at any given time, the fact that A was originally built in an older Spack with older versions of those packages, etc)
