### ISSUE TITLE
behaivor of duplicant variants?

### ISSUE THREAD

**Issue by cyrush** [LLNL/spack#33425]
### Steps to reproduce

I had a package that had the exact same variant twice (cut and paste typo), along the lines of:

```
variant("myvariant", default=False, description="Build with with awesome feature")
variant("myvariant", default=False, description="Build with with awesome feature")
```

Today -- I realized that `+myvariant` wasn't reflecting in the spec. 

```
if `+myvariant` in spec:
    # we can't make it here
else:
    # we always make it here
```

I removed the second copy, and then asking for `+myvariant` worked as I expected. 

This simple error disabled a big chunk of functionality and automatized testing of it.

I didn't think to question `+myvariant`. 

It would be good to have an error or even better make sure that duplicate variant entries don't undermine the state.  

### Information on your system

* **Spack:** 0.19.0.dev0 (6983d520fa64d8c7343dcc627197b0e6c621d1a6)
* **Python:** 3.7.3
* **Platform:** darwin-catalina-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Cannot reproduce on:

* **Spack:** 0.21.0.dev0 (ae00d7c3583008a6baeb860787c779bae320c05a)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo


With the following diff:
```diff
diff --git a/var/spack/repos/builtin/packages/zlib/package.py b/var/spack/repos/builtin/packages/zlib/package.py
index f77e3e0e3d..9b15850951 100644
--- a/var/spack/repos/builtin/packages/zlib/package.py
+++ b/var/spack/repos/builtin/packages/zlib/package.py
@@ -47,7 +47,8 @@ class Zlib(MakefilePackage, Package):
 
     build_system("makefile", conditional("generic", when="platform=windows"), default="makefile")
 
-    variant("pic", default=True, description="Produce position-independent code (for shared libs)")
+    variant("pic", default=False, description="Produce position-independent code (for shared libs)")
+    variant("pic", default=False, description="Produce position-independent code (for shared libs)")
     variant("shared", default=True, description="Enables the build of shared libraries.")
     variant("optimize", default=True, description="Enable -O2 for a more optimized lib")
 
@@ -72,6 +73,10 @@ def setup_build_environment(self, env):
 
 class MakefileBuilder(spack.build_systems.makefile.MakefileBuilder, SetupEnvironment):
     def edit(self, pkg, spec, prefix):
+        if "+pic" in spec:
+            raise RuntimeError("+pic")
+        else:
+            raise RuntimeError("~pic")
         config_args = []
         if "~shared" in self.spec:
             config_args.append("--static")
```
I get:
![Screenshot from 2023-07-07 11-44-54](https://github.com/spack/spack/assets/4199709/b4252182-aaf0-4b18-b4c4-bd4adcae8cb2)

Which seems correct.

**Comment by cyrush** [comment]
thanks for the follow up, glad it seems this isn't an issue any more.
