### ISSUE TITLE
 Spec object has no attribute cppflags - openblas fails to build

### ISSUE THREAD

**Issue by healther** [LLNL/spack#3343]
@davydden mentioned that this a regression and that it worked a couple of days ago in #3333 .

I see the following (taking ```0.2.15``` because it isn't installed yet)

```
spack install openblas@0.2.15
==> Installing openblas
==> Fetching http://github.com/xianyi/OpenBLAS/archive/v0.2.15.tar.gz
######################################################################## 100.0%
==> Staging archive: /scratch/wv385/Documents/git/spack/var/spack/stage/openblas-0.2.15-zazopc3jb6345biluudxxx4qo4igdukz/v0.2.15.tar.gz
==> Created stage in /scratch/wv385/Documents/git/spack/var/spack/stage/openblas-0.2.15-zazopc3jb6345biluudxxx4qo4igdukz
==> Building openblas [MakefilePackage]
==> Executing phase : 'edit'
==> Executing phase : 'build'
==> Executing phase : 'install'
==> Error: AttributeError: 'Spec' object has no attribute 'cppflags'
/scratch/wv385/Documents/git/spack/var/spack/repos/builtin/packages/openblas/package.py:143, in check_install:
     132      @run_after('install')
     133      def check_install(self):
     134          spec = self.spec
     135          # Openblas may pass its own test but still fail to compile Lapack
     136          # symbols. To make sure we get working Blas and Lapack, do a small
     137          # test.
     138          source_file = join_path(os.path.dirname(self.module.__file__),
     139                                  'test_cblas_dgemm.c')
     140          blessed_file = join_path(os.path.dirname(self.module.__file__),
     141                                   'test_cblas_dgemm.output')
     142  
  >> 143          include_flags = spec.cppflags
     144          link_flags = spec.libs.ld_flags
     145          if self.compiler.name == 'intel':
     146              link_flags += ' -lifcore'
     147          link_flags += ' -lpthread'
     148          if '+openmp' in spec:
     149              link_flags += ' ' + self.compiler.openmp_flag
     150  
     151          output = compile_c_and_execute(
     152              source_file, [include_flags], link_flags.split()
     153          )
     154          compare_output_file(output, blessed_file)

See build log for details:
```

**Comment by davydden** [comment]
i don't see the solution, but I am quite sure that it's a regression coming from https://github.com/LLNL/spack/pull/1875 , probably some last minute changes broke somthing. @alalazo could you have a look?

**Comment by alalazo** [comment]
@davydden Can you try: `spec['openblas'].cppflags` ? If that doesn't work I'll try to have a closer look asap.

**Comment by davydden** [comment]
```
include_flags = spec['openblas'].cppflags
link_flags = spec['openblas'].libs.ld_flags
```
fixed the issue.

**Comment by davydden** [comment]
i will create a PR...

**Comment by adamjstewart** [comment]
@alalazo Shouldn't `spec` and `spec['name']` be identical when `'name'` is the name of the package?

**Comment by alalazo** [comment]
I think this is worth an explanation: one of the last changes I did in #1875 was removing the explicit spec deep-copy in `__getitem__` in favor of an object wrapper (`SpecBuildInterface`) which wraps a `spec` and adds all the query you can do during the build.

The fact is you get the wrapper only if you go through `__getitem__`, which should be 99% of the cases as usually you don't try to compile against yourself.

**Comment by adamjstewart** [comment]
Well, as long as we know about it. We might want to go back through existing packages and make sure there are no other packages like this. I take it this means that `self.spec.prefix` no longer exists either?

**Comment by alalazo** [comment]
> I take it this means that self.spec.prefix no longer exists either?

Hmmm, why? What you get back from `spec['name']` is a wrapper to the underlying spec. As such it has **all** the methods of the spec (including `prefix`), and in addition it can be queried for `cppflags` and `libs`.

The relevant code is [here](https://github.com/LLNL/spack/commit/ed582cef68585b6090866fb0bb3aa2cc72dbe2ed), in particular `ObjectWrapper` and `SpecBuildInterface`.

**Comment by adamjstewart** [comment]
Wait, so `spec.prefix` and `spec['openblas'].prefix` are equivalent but `spec.cppflags` and `spec['openblas'].cppflags` aren't?

**Comment by alalazo** [comment]
@adamjstewart Mostly:

> spec.prefix and spec['openblas'].prefix are equivalent 

This is 100% correct.

> but spec.cppflags and spec['openblas'].cppflags aren't

`spec.cppflags` doesn't exist.

**Comment by adamjstewart** [comment]
Huh. Well that's confusing. I'll just stop using `spec.` and always use `spec['name'].` I guess.

**Comment by alalazo** [comment]
@adamjstewart I don't think you'll need to do that. This problem will show up only if in a package you want to retrieve its own `cppflags` or `libs`. At the moment I think only `hdf5` and `openblas` need this kind of treatment for the home-baked build and link tests.
