### ISSUE TITLE
gcc6.3.0 is  broken on Sierra 10.12.3

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#3348]
a fresh installation of GCC results in a broken `gfortran`:
```
configure:33278: /Users/davydden/spack/lib/spack/env/clang/gfortran -o conftest    conftest.f  >&5
ld: file not found: n-dynamic
collect2: error: ld returned 1 exit status
```
(this is the error log from `openmpi` configure).

I did have `6.3.0` working (built around January), it could be related to dependencies. I don't recall any OSX updates in the last couple of months.

**Comment by davydden** [comment]
there was this change to `gcc` recently https://github.com/LLNL/spack/commit/4afb7a729c2886a25809d2c00d78f99f6e4286fa

@gartung: do you think it could be related?

I will try to un-do this patch and see if it fixes the issue...

**Comment by gartung** [comment]
OK. Give it a try. I haven't tested this patch with Sierra.

**Comment by davydden** [comment]
fixed by https://github.com/LLNL/spack/pull/3349
