### ISSUE TITLE
Spack installs libraries in $PREFIX/lib64 instead of $PREFIX/lib for all AutotoolsPackages

### ISSUE THREAD

**Issue by hpcnpatel** [LLNL/spack#33528]
### Error description 

When I install any **AutotoolsPackage**  packages, Spack installs libraries in the **$PREFIX/lib** on one system (1) and on the other system (2), I get all installed libraries in the **$PREFIX/lib64**.

Hence $PREFIX/libdir is different on two different systems.

=========================================================
System 1 info:

> spack debug report
* **Spack:** 0.17.1
* **Python:** 3.6.15
* **Platform:** linux-sles15-skylake_avx512
* **Concretizer:** clingo

System 2 info:  

> spack debug report
* **Spack:** 0.17.1
* **Python:** 3.6.15
* **Platform:** linux-sles15-icelake
* **Concretizer:** clingo

There is one system-side package (**site-config**: This is a Configuration for autoconf Based configure Scripts) installed on system 2.

=========================================================

I believe this site-config on system 2 guides the configure script to make the decision to add $PREFIX/lib64 instead of $PREFIX/lib for all the spack installed packages that depend on AutotoolsPackage. 

This breaks a lot of other packages that depend on other AutotoolsPackage packages. 

For example:

> spack install likwid 

will fail as a result of it can not find hwloc lib files. Spack looks for the lib files in $PREFIX/lib instead of $PREFIX/lib64

The error looks like,
````
==> Installing likwid-5.2.2-kukvrwgumz22jxav6dbvv2n3blf6or2l
==> No binary for likwid-5.2.2-kukvrwgumz22jxav6dbvv2n3blf6or2l found: installing from source
==> Using cached archive: /home/.spack/source_cache/_source-cache/archive/7d/7dda6af722e04a6c40536fc9f89766ce10f595a8569b29e80563767a6a8f940e.tar.gz
==> Ran patch() for likwid
==> likwid: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j24'

2 errors found in build log:
     107    ===>  COMPILE  GCC/access_client.o
     108    ===>  COMPILE  GCC/access.o
     109    ===>  COMPILE  GCC/loadData.o
     110    ===>  EXTERNAL HWLOC
     111    ===>  EXTERNAL LUA
     112    ===>  CREATE SHARED LIB  liblikwid.so
  >> 113    /usr/bin/ld: cannot find /home/stack/opt/icelake/hwloc/2.6.0-gcc-bbur4cz/lib/libhwloc.so: No such file or directory
  >> 114    collect2: error: ld returned 1 exit status
     115    make: *** [Makefile:234: liblikwid.so] Error 1

See build log for details:
  /home/.spack/tmpdir/icelake/spack-stage-likwid-5.2.2-kukvrwgumz22jxav6dbvv2n3blf6or2l/spack-build-out.txt
````
My questions are: 

1) Why can't Spack overwrite $PREFIX/libdir set by site-config for AutotoolsPackage packages? 
2) How to fix this?

One solution is to remove the site-config from the system but that is not the point. And if admins decides  to include it in the system image, we cannot do much about it. 

### Information on your system

System 1 info:

spack debug report

Spack: 0.17.1
Python: 3.6.15
Platform: linux-sles15-skylake_avx512
Concretizer: clingo

System 2 info:

spack debug report

Spack: 0.17.1
Python: 3.6.15
Platform: linux-sles15-icelake
Concretizer: clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run the failing commands in debug mode and reported the output

**Comment by hpcnpatel** [comment]
For the reference: #10842, #17556, https://github.com/spack/spack/pull/18190

**Comment by alalazo** [comment]
This depends on the OS. For instance on Ubuntu we have `lib`:
```console
$ ls /home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu20.04-icelake/gcc-9.4.0/likwid-5.2.2-ws2towym55vtk2j5lk4rgdkqmnaxfwyk
bin  include  lib  man  share
```
