### ISSUE TITLE
Spack install race conditions

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#33547]
There are still multiple races when firing up multiple `spack install` processes:

## sbang

```
==> Error: Failed to install zstd due to FileNotFoundError: [Errno 2] No such file or directory: '/home/software/spack/bin/.sbang.tmp'
```

## Provider cache hang

```
==> Error: Timed out waiting for a write lock after 120.202s.
    Made 281 attempts on file: /root/.spack/cache/providers/.builtin-index.json.lock
```

**Comment by blue42u** [comment]
We're seeing these two races in HPCToolkit's CI on one of our CI runners (very underpowered machine):

## Binary index cache hang
```
==> Error: Failed to install bzip2 due to LockTimeoutError: Timed out waiting for a write lock after 120.200s.
    Made 281 attempts on file: /root/.spack/cache/indices/.783b91ff88_c3d0ebca2d.json.lock
```

## Binary index cache race
```
==> Error: Failed to install zstd due to FileNotFoundError: [Errno 2] No such file or directory: '/root/.spack/cache/indices/1f0f0ff7c4_8567a6c618.json'
```

**Comment by haampie** [comment]
@blue42u are you still seeing this?

**Comment by blue42u** [comment]
@haampie Our CI has avoided running Spack in parallel for the past year or so, so I can't confirm if the bug is still present. Enough has changed on our end that I don't think I can recreate the original scenario.

**Comment by tgamblin** [comment]
Given @blue42u's response let's close this for now and reopen it if he sees issues again.

**Comment by melven** [comment]
The following error still happens for me:

```
==> Error: llvm-14.0.6-ufgvxvrhl4zghtgdoj7up23mos4auffi: LockTimeoutError: Timed out waiting for a write lock after 60.073s.
    Made 161 attempts on file: /tmp/f_jkessx/spack-stage/.lock
```

Version: `develop-2025-02-16`
Setup: running 3 processes on the same node with 128 cores (with `nohup spack -e SomeEnv install -j 128`) with a local build cache and spack directory on NFSv3.
(I know it's using more threads than cores this way, but this helps with download delays, etc).
