### ISSUE TITLE
Cannot specify independent dependencies any more

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#3358]
I want to build a package `a`, which depends on `b`, which depends on `c`, etc. I want to specify the compiler with which `c` is built. This fails:

```
$ spack install cosmomc +planck %gcc@6.3.0 ^planck-likelihood +lensing-ext +plik-DS +plik-HM-ext +plik-unbinned ^openmpi ^hwloc ^libpciacess ^pkg-config %clang
==> Error: cosmomc does not depend on hwloc, openmpi, libpciacess, or pkg-config
```
Here `cosmomc` depends on `planck-likelihood`, which depends on `mpi`, so this should work. I'm quite certain it used to work.

I need to specify the compiler for `pkg-config` because it doesn't build with `gcc` on macOS. On the other hand, `cosmomc` does not build with `clang`.

**Comment by tgamblin** [comment]
@eschnett: You can specify independent dependencies, but this is a problem with Spack's handling of variants.  It doesn't know you can depend on those things unless you add the `+foo` options for the intervening packages.  Same reason you have to write:

```
spack install hdf5 +mpi ^mpich
```

This will be solved with the new concretizer, which will do much more aggressive (and hopefully faster) resolution.

**Comment by eschnett** [comment]
Thanks.

This command line works:
```
spack spec cosmomc +mpi +planck %gcc@6.3.0 ^bzip2%gcc@6.3.0 ^ncurses%gcc@6.3.0 ^openmpi ^openssl%gcc@6.3.0 ^pkg-config%clang ^planck-likelihood +lensing-ext +plik-DS +plik-HM-ext +plik-unbinned ^python%clang ^readline%gcc@6.3.0 ^sqlite%gcc@6.3.0
```

**Comment by tgamblin** [comment]
ew.  apologies in advance. 😞
