### ISSUE TITLE
Copy view still not working

### ISSUE THREAD

**Issue by vsoch** [LLNL/spack#33606]
I can't find my issue from before, but the view with a copy still doesn't work - I get this:

```
#9 1320.0 ==> Warning: Skipping external package: cmake@3.23.1%gcc@11.3.0~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-ubuntu22.04-x86_64/z72yg34
#9 1332.4 ==> Error: [Errno 21] Is a directory: '/opt/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.3.0/ncurses-6.3-qfxtgqwgd46uawkgruouir2supqdeqgx/lib/terminfo'
#9 1332.4 ==> Updating view at /opt/view
```
ping @haampie - I think you'll remember the context (and you wrote most of the code here). I had originally opened the issue for Flux, and we never could update the view to be a copy because of this bug. Thanks!

**Comment by haampie** [comment]
https://github.com/spack/spack/pull/32306#issuecomment-1265248767 no clue why it did not get merged :/
