### ISSUE TITLE
'Spec' object has no attribute 'lapack_libs'

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#3364]
I am seeing this weird error:

```
==> Building planck-likelihood [Package]
==> Executing phase : 'install'
==> Error: AttributeError: 'Spec' object has no attribute 'lapack_libs'
/xfs1/applications/spack/spack/var/spack/repos/builtin/packages/planck-likelihood/package.py:101, in install:
     89       def install(self, spec, prefix):
     90           # Configure
     91           makeflags = [
     92               'PREFIX=%s' % prefix,
     93               'CFITSIOPATH=%s' % spec['cfitsio'].prefix,
     94               'CC=cc',
     95               'FC=fc',
     96               'IFORTLIBPATH=',
     97               'IFORTRUNTIME=-lintlc -limf -lsvml -liomp5 -lifportmt -lifcoremt',
     98               'GFORTRANLIBPATH=',
     99               'GFORTRANRUNTIME=-lgfortran -lgomp',
     100              'LAPACKLIBPATH=',
  >> 101              'LAPACK=%s' % (spec['lapack'].lapack_libs +
     102                             spec['blas'].blas_libs).ld_flags,
     103              'COPENMP=%s' % self.compiler.openmp_flag,
     104              'FOPENMP=%s' % self.compiler.openmp_flag,
     105          ]
     106
     107          # Build
     108          make(*makeflags)
     109
     110          # Install
     111          make('install', *makeflags)
     112          fix_darwin_install_name(prefix.lib)
     113          dirs = ['plc_2.0']
     114          if '+lensing-ext' in spec:
     115              dirs.append('lensing_ext')
     116          if '+plik-DS' in spec:
     117              dirs.append('plik_DS')
     118          if '+plik-HM-ext' in spec:
     119              dirs.append('plik_HM_ext')
     120          if '+plik-unbinned' in spec:
     121              dirs.append('plik_unbinned')
     122          for dir in dirs:
     123              install_tree(dir, join_path(prefix, 'share', 'clik', dir))
```

Do you have any pointers as to what might be causing this? It happens on Linux, but not on Darwin.

**Comment by davydden** [comment]
simply change to `spec['lapack'].libs` and `spec['blas'].libs`. The package is not up-to-date with https://github.com/LLNL/spack/pull/1875.

**Comment by tgamblin** [comment]
@alalazo: would it make sense to allow `spec['lapack'].lapack_libs` to continue working for external packages like @eschnett's?

I like the new convention, but I don't see why we couldn't preserve the real attributes since one would expect them to work in pure Python.

**Comment by davydden** [comment]
@tgamblin but do we really need to? The fix is trivial, i think it would be fewer lines of code to maintain in Spack's core if all packages use `spec['lapack'].libs`.

**Comment by eschnett** [comment]
I see many package that use `lapack_libs` (grep shows about 60 hits). Are they all broken?

**Comment by davydden** [comment]
> I see many package that use lapack_libs (grep shows about 60 hits). Are they all broken?

are you sure you are on the latest `develop` branch? All of them were supposed to be converged in https://github.com/LLNL/spack/pull/1875, @alalazo correct me if I am wrong.

**Comment by eschnett** [comment]
Yepp, needed to merge. Only a few packages are broken (`elemental`, `lammps`, `magma`).

**Comment by davydden** [comment]
I checked and see only a couple: `elemental`, `lammps`, `magma`, `phist`. Which looks like a reasonable amount of packages which slipped through.

**Comment by eschnett** [comment]
Given that `elemental` and `magma` provide very lapack-like features, it seems strange that exactly these are broken.

**Comment by davydden** [comment]
I will fix those...

**Comment by alalazo** [comment]
@eschnett They are broken because they were added after I made the change to all other packages. #1875 has been sitting there for a while and `elemental` and `magma` are pretty recent additions.

**Comment by alalazo** [comment]
@tgamblin 

> would it make sense to allow spec['lapack'].lapack_libs to continue working for external packages like @eschnett's

At a first glance I would say no. The reason is that we are querying from a `Spec`-like instance and not from the package. If we really want to go that way I think we need either:

-  a fat interface with all the virtual dependencies included 
- some meta-programming mechanism (to do things neatly and attach `lapack_libs` only to `lapack` providers)

to be able to say:
```
spec['lapack'].lapack_libs
```
which adds complications for a little benefit. 

One thing I can do though is write docs for the new querying mechanism next week. In that way we could point people to how the querying works after #1875.

**Comment by adamjstewart** [comment]
@alalazo I'm a little confused about the current state of things. In `atlas`, I see:
```python
def libs(self):
```
In `openmpi`, I see:
```python
@property
def libs(self):
```
In `netlib-lapack` I'm seeing:
```python
@property                                                                   
def blas_libs(self):                                                        

@property                                                                   
def lapack_libs(self):
```
I kind of understand why some packages use `blas_libs` and others just use `libs`. But why are some properties and some aren't?

**Comment by alalazo** [comment]
@adamjstewart I'll check it right now.
