### ISSUE TITLE
Installation issue:  krb5

### ISSUE THREAD

**Issue by luke-dt** [LLNL/spack#33674]
### Steps to reproduce the issue

```console
$ spack install krb5
```

### Error message

<details><summary>Error message</summary><pre>
==> Installing krb5-1.19.3-4bwqckllkm2dcucxjokmvbb7ofmneame
==> No binary for krb5-1.19.3-4bwqckllkm2dcucxjokmvbb7ofmneame found: installing from source
==> Using cached archive: /Users/luke/Documents/GitHub/dantaslab/spack/var/spack/cache/_source-cache/archive/56/56d04863cfddc9d9eb7af17556e043e3537d41c6e545610778676cf551b9dcd0.tar.gz
==> Ran patch() for krb5
==> krb5: Executing phase: 'autoreconf'
==> krb5: Executing phase: 'configure'
==> krb5: Executing phase: 'build'
==> krb5: Executing phase: 'install'
==> Error: AttributeError: 'str' object has no attribute 'propagate'

The 'krb5' package cannot find an attribute while trying to build from sources. This might be due to a change in Spack's package format to support multiple build-systems for a single package. You can fix this by updating the build recipe, and you can also report the issue as a bug. More information at https://spack.readthedocs.io/en/latest/packaging_guide.html#installation-procedure

/Users/luke/Documents/GitHub/dantaslab/spack/lib/spack/spack/build_environment.py:1075, in _setup_pkg_and_run:
       1072        tb_string = traceback.format_exc()
       1073
       1074        # build up some context from the offending package so we can
  \>\>   1075        # show that, too.
       1076        package_context = get_package_context(tb)
       1077
       1078        logfile = None

</pre></details>

### Information on your system

* **Spack:** 0.19.0.dev0 (97ae549cc9c31ab1f4c78efb6157eb344f60415b)
* **Python:** 3.10.3
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/9924140/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/9924141/spack-build-out.txt)

I have the exact same error with `llvm` and `icu4c`. Possibly related to #30738 ?

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by beromer** [comment]
I have the exact same error message from ncurses (via spack install gcc@11.3.0) on a freshly imaged Redhat 8 system.  Are there any known workarounds?

**Comment by luke-dt** [comment]
The latest version `0.19.0.dev0 (9f4715ef505886a59e60f27dd4205bcdc432b417)` appears to fix this issue for me
