### ISSUE TITLE
Add the ability to forward install args to depfiles

### ISSUE THREAD

**Issue by psakievich** [LLNL/spack#33769]
### Summary

As a user, I'd like a way to forward arguments for `spack install` into `depfiles` such as `--keep-stage`, `--overwrite` etc.

Pinging @haa

### Rationale

I'm sold on `depfiles`. They are an awesome way to get parallel builds.  They are missing some of the features available in `spack install`.  Certain arguments are needed at the `spack install` call such as `--keep-stage`.  

### Description

It would be nice if there was an argument like `--install_args` that will forward the commands into the commands generated in the `depfile`.

Another option is to add commands for the relevant install commands to the `depfile` command.

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
You can already do `make SPACK_INSTALL_FLAGS=--keep-stage` etc.

You can also set separate flags for deps, for example `make SPACK_INSTALL_FLAGS=--keep-stage x/.install-deps/<hash> && make SPACK_INSTALL_FLAGS=--verbose (x/.install/hash)`.

I was thinking to add phony convenience targets for packages if they are unique in the env, e.g. `make x/.install/python` (should also tab complete)

If you need specific flags just for a specific package, you'll have to edit the makefile by hand

**Comment by haampie** [comment]
Actually why don't we just use `<pkg name>-<version>-<hash>` instead of `<hash>` for target names and remove the `.` so that tab completion works even better.

Then you can do `spack env depfile -o Makefile --make-target-prefix x` and run `make x/i<tab>` -> `make x/install-d<tab>` -> `make x/install-deps/py<tab>` -> `make x/install-deps/python-3.11.0-abcdef`

**Comment by psakievich** [comment]
@jrood-nrel see above 👆

**Comment by jrood-nrel** [comment]
Awesome.

**Comment by haampie** [comment]
Convenience improvemens: https://github.com/spack/spack/pull/33773
