### ISSUE TITLE
Installation issue: hsa-rocr-dev needs numactl

### ISSUE THREAD

**Issue by G-Ragghianti** [LLNL/spack#33763]
### Steps to reproduce the issue

Install hsa-rocr-dev on a  system that doesnt' have /usr/lib64/libnuma.so installed: 
```console
$ spack install hsa-rocr-dev
...
```

### Error message

<details><summary>Error message</summary><pre>
make[2]: *** No rule to make target '/usr/lib64/libnuma.so', needed
             by 'libhsa-runtime64.so.1.5.0'.  Stop.
</pre></details>

### Information on your system

* **Spack:** 0.19.0.dev0
* **Python:** 3.6.8
* **Platform:** linux-centos7-skylake_avx512
* **Concretizer:** clingo
[spack-build-env.txt](https://github.com/spack/spack/files/9964674/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/9964675/spack-build-out.txt)

### Additional information

I tried adding `depends_on("numactl")` to the package, but it needs a bit more encouragement to actually use the available library.  Suggestions?

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
I think we patch this? Or try to fix this. Is there any note regarding numactl in the relevant spack packages? I vaguely remember that hipcc added -lnuma* to the linked libraries for no good reason

**Comment by G-Ragghianti** [comment]
The numactl spack package is a dependency for some rocm/hip packages, but not for hsa-rocr-dev currently.

**Comment by srekolam** [comment]
i have added numactl for hsa-rocr-dev package. Can you please let me know if this issue is still there. else,i can close this issue. Thanks

**Comment by G-Ragghianti** [comment]
Yes it appears to be fixed.  Thanks.
