### ISSUE TITLE
Installation issue: hip cmake fails to find clangrt when using clang

### ISSUE THREAD

**Issue by simonpintarelli** [LLNL/spack#33797]
### Steps to reproduce the issue

```console
$ spack spec -I spla+rocm
  spla@1.5.4%gcc@11.3.0~cuda~fortran~ipo+openmp+rocm~static build_type=RelWithDebInfo arch=linux-sles15-zen3  
spack install  spla+rocm ^hip@5.2.3
```

The problem also affects rocm 5.3.0 (I've merged the respective PRs in my personal branch)

### Error message

<details><summary>Error message</summary><pre>
1 error found in build log:
     17    -- Looking for pthread_create in pthreads
     18    -- Looking for pthread_create in pthreads - not found
     19    -- Looking for pthread_create in pthread
     20    -- Looking for pthread_create in pthread - found
     21    -- Found Threads: TRUE
     22    -- hip::amdhip64 is SHARED_LIBRARY
  >> 23    CMake Error at /user-environment/linux-sles15-zen2/gcc-11.3.0/hip-5.3.0-xjmxg6n6teuxvkaziw7xlo4bjze57ybc/lib/cmake/hip/hip-config.cmake:331 (message):
     24      clangrt builtins lib not found
     25    Call Stack (most recent call first):
     26      CMakeLists.txt:172 (find_package)
     27    
     28    
     29    -- Configuring incomplete, errors occurred!

See build log for details:
  /run/user/25361/simonpi/spack-stage-spla-1.5.4-zxdi4inelnjlnleyf6dgb5k4hpxxtioq/spack-build-out.txt
</pre></details>

### Information on your system

* **Spack:** 0.19.0.dev0 (e5c2cb4ac2721828ffdfa7166c37f32fd5461fb1)
* **Python:** 3.6.15
* **Platform:** linux-sles15-zen3
* **Concretizer:** clingo

### Additional information

IMHO the problem is caused by the following line in `hip-config.cmake`:
```
   set(HIP_CLANG_ROOT "${ROCM_PATH}/llvm")
```
respectively in hipamd git:
https://github.com/ROCm-Developer-Tools/hipamd/blob/rocm-5.3.0/hip-config.cmake.in#L145
It assumes that the rocm packages are installed under a common path.

Manually setting `HIP_CLANG_ROOT` to the spack installed `llvm-amdgpu` fixed it for me.
According to `spack build-env spla -- env | grep HIP_CLANG_ROOT`, the correct location could be taken from the  environment.

I think the line should be changed either in upstream or as a patch in the hip spack package to:
```
   set(HIP_CLANG_ROOT "$ENV{HIP_CLANG_ROOT}/llvm")
```

I'm informing the maintainers of the hip package @srekolam, @renjithravindrankannath, since this isn't a bug in spla.

I've encountered this issue for rocm 5.2.3 and 5.3.0 version packages (I haven't tried other versions).

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by srekolam** [comment]
@simonpintarelli  i have noticed the same failure with few of the packages too ..strumpack , ginkgo etc failing in gitlab-ci for PR 33320 .
the below will fix too but just trying to see if this can be fixed in the hip package etc.
if self.spec.satisfies("^hip@5.3.0:"):
                args.append(
                    self.define(
                        "HIP_CXX_COMPILER", "{0}/bin/clang++".format(self.spec["llvm-amdgpu"].prefix)
                    )
                )

**Comment by renjithravindrankannath** [comment]
hip package updates in PR  #33320 includes the fix for this issue.

**Comment by simonpintarelli** [comment]
@renjithravindrankannath @srekolam Thank you for the fix!
