### ISSUE TITLE
Error: vasp-6.3.2  Package was not installed

### ISSUE THREAD

**Issue by jeffmacdonald7** [LLNL/spack#33816]
### Steps to reproduce

# spack -d install -v -j 16 vasp@6.2.0 +scalapack +openmp %aocc@3.2.0 target=zen3 ^amdfftw@3.1 ^amdblis@3.1 threads=openmp ^amdlibflame@3.1 ^amdscalapack@3.1 ^openmpi@4.1.1 fabrics=auto

or
# spack -d install -v -j 16 vasp@6.3.2 +scalapack +openmp %aocc@3.2.0 target=zen3 ^amdfftw@3.1 ^amdblis@3.1 threads=openmp ^amdlibflame@3.1 ^amdscalapack@3.1 ^openmpi@4.1.1 fabrics=auto

or 
# spack -d install -v -j 16 vasp@5.4.4.pl2 +scalapack +openmp %aocc@3.2.0 target=zen3 ^amdfftw@3.1 ^amdblis@3.1 threads=openmp ^amdlibflame@3.1 ^amdscalapack@3.1 ^openmpi@4.1.1 fabrics=auto

### Error message

lib/spack/spack/installer.py:1846 ==> [2022-11-10-09:59:34.784539, 644057] Error: vasp-6.3.2-vb6htw7vwxrplonzr5yll4yxmptdrgw3: Package was not installed
lib/spack/spack/installer.py:1860 ==> [2022-11-10-09:59:34.784621, 644057] Associating installation failure with first missing package (vasp-6.3.2-vb6htw7vwxrplonzr5yll4yxmptdrgw3) from vasp-6.3.2-vb6htw7vwxrplonzr5yll4yxmptdrgw3
lib/spack/spack/main.py:1010 ==> [2022-11-10-09:59:34.784724, 644057] InstallError: Installation request failed.  Refer to reported errors for failing package(s).
lib/spack/spack/error.py:54 ==> [2022-11-10-09:59:34.784793, 644057] Error: Installation request failed.  Refer to reported errors for failing package(s).
Traceback (most recent call last):
  File "/usr/local/spack/lib/spack/spack/main.py", line 1007, in main
    return _main(argv)
  File "/usr/local/spack/lib/spack/spack/main.py", line 962, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/usr/local/spack/lib/spack/spack/main.py", line 990, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/usr/local/spack/lib/spack/spack/main.py", line 639, in _invoke_command
    return_val = command(parser, args)
  File "/usr/local/spack/lib/spack/spack/cmd/install.py", line 549, in install
    install_specs(zip(abstract_specs, concrete_specs), install_kwargs, args)
  File "/usr/local/spack/lib/spack/spack/cmd/install.py", line 270, in install_specs
    install_specs_outside_environment(specs, install_kwargs)
  File "/usr/local/spack/lib/spack/spack/cmd/install.py", line 346, in install_specs_outside_environment
    builder.install()
  File "/usr/local/spack/lib/spack/spack/installer.py", line 1865, in install
    raise InstallError(
spack.installer.InstallError: Installation request failed.  Refer to reported errors for failing package(s).
[+] /usr/local/spack/opt/spack/linux-ubuntu20.04-zen3/aocc-3.2.0/hwloc-2.8.0-cl2ibypefsjoat7q3in7ue5r5reyjwqk

### Information on your system

spack debug report
* **Spack:** 0.19.0.dev0 (9ca7165ef0537c168f63ab61663a04da4f74cb5b)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-zen3
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by jeffmacdonald7** [comment]
here is the entire build.log output


export VASPVER=6.3.2
export CPU=zen3

spack --debug --stacktrace -d install -v -j 16 vasp@$VASPVER +scalapack +openmp %aocc@3.2.0 target=$CPU ^amdfftw@3.1 ^amdblis@3.1 threads=openmp ^amdlibflame@3.1 ^amdscalapack@3.1 ^openmpi@4.1.1 fabrics=auto

[build.log](https://github.com/spack/spack/files/9982479/build.log)

**Comment by jeffmacdonald7** [comment]
so the problem is that perl does not download from www.cpan.org.

from the same EXACT machine I can use curl to get perl
this works
curl http://www.cpan.org/src/5.0/perl-5.36.0.tar.gz --output perl-5.36.0.tar.gz

wireshark shows 
GET /src/5.0/perl-5.36.0.tar.gz HTTP/1.1
Host: www.cpan.org
User-Agent: curl/7.68.0
Accept: */*

HTTP/1.1 200 OK                    << NICE data incoming.
Connection: keep-alive
Content-Length: 20223817


HOWEVER when spack tries to download perl from same website wireshark shows

GET /src/5.0/perl-5.36.0.tar.gz HTTP/1.1
Accept-Encoding: identity
Host: www.cpan.org
User-Agent: Spackbot/0.19.0.dev0
Connection: close                    << BAD, why you close connection so soon spack ?

**Comment by jeffmacdonald7** [comment]
previously i was trying this on ubuntu 20.04, today I tried on new box ubuntu 22.04.  same error

==> [2022-11-11-11:03:00.083351] Checking existence of https://mirror.spack.io/perl/perl-5.36.0.tar.gz
==> [2022-11-11-11:03:00.457176] Failure reading URL: Download failed: HTTP Error 404: Not Found
==> [2022-11-11-11:03:00.457415] URL does not exist: https://mirror.spack.io/perl/perl-5.36.0.tar.gz
==> [2022-11-11-11:03:00.457574] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/perl/perl-5.36.0.tar.gz
==> [2022-11-11-11:03:00.457904] Checking existence of http://www.cpan.org/src/5.0/perl-5.36.0.tar.gz
==> [2022-11-11-11:03:00.961662] Error: ConnectionResetError: [Errno 104] Connection reset by peer

/usr/local/spack/lib/spack/spack/package_base.py:1455, in do_fetch:
       1452
       1453        self.stage.create()
       1454        err_msg = None if not self.manual_download else self.download_instr
  >>   1455        start_time = time.time()
       1456        self.stage.fetch(mirror_only, err_msg=err_msg)
       1457        self._fetch_time = time.time() - start_time
       1458

**Comment by haampie** [comment]
can you access those urls with `curl` or `wget`?

**Comment by haampie** [comment]
Can you download it with vanilla `urllib`?

```console
$ python -c 'import urllib.request; print(urllib.request.urlopen("http://www.cpan.org/src/5.0/perl-5.36.0.tar.gz").status)'
200
```

**Comment by jeffmacdonald7** [comment]
Yes curl works fine from the same exact machine....no containers or
firewall issues

**Comment by haampie** [comment]
I meant urrlib not curl/wget

**Comment by jeffmacdonald7** [comment]
is there typo in that command ?


python -c 'import urllib.request; print(urllib.request.urlopen("http://www.cpan.org/src/5.0/perl-5.36.0.tar.gz").status)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named request

**Comment by haampie** [comment]
Hm, it's Python 3 API, maybe `python3 -c ...` or `spack python -c ...`

**Comment by jeffmacdonald7** [comment]
yes that worked.
python3 -c 'import urllib.request; print(urllib.request.urlopen("http://www.cpan.org/src/5.0/perl-5.36.0.tar.gz").status)'
200

**Comment by jeffmacdonald7** [comment]
WORKAROUND_IDEA:

I wonder if I manually download and install http://www.cpan.org/src/5.0/perl-5.36.0.tar.gz would spack
realize its already installed and hence work around this issue ?    Or is spack always going to try and download http://www.cpan.org/src/5.0/perl-5.36.0.tar.gz  weather its installed locally allready or not ?

**Comment by haampie** [comment]
You can make Spack use `curl`: `spack config add config:url_fetch_method:curl`.

If you get to the bottom of why `urllib` doesn't work for you in Spack, that'd be great to share.

**Comment by jeffmacdonald7** [comment]
Perfect!!!!! let me try that on Monday.    Thanks Harmen.

**Comment by jeffmacdonald7** [comment]
trust me, once I figure this out...Ill share

**Comment by jeffmacdonald7** [comment]
AFTER running
# spack config add config:url_fetch_method:curl

now spack SUCCESSFULLY downloads and installs perl-5.36.0

many Thanks haampie!

**Comment by jeffmacdonald7** [comment]
Im going to close this issue.

PROBLEM:   
==> [2022-11-11-11:03:00.457904] Checking existence of http://www.cpan.org/src/5.0/perl-5.36.0.tar.gz
==> [2022-11-11-11:03:00.961662] Error: ConnectionResetError: [Errno 104] Connection reset by peer

/usr/local/spack/lib/spack/spack/package_base.py:1455, in do_fetch:
1452
1453 self.stage.create()
1454 err_msg = None if not self.manual_download else self.download_instr

1455 start_time = time.time()
1456 self.stage.fetch(mirror_only, err_msg=err_msg)
1457 self._fetch_time = time.time() - start_time

SOLUTION:   use curl instead of urllib  to download  perl instead.
                       spack config add config:url_fetch_method:curl           << this command tells spack to use curl to download perl
