### ISSUE TITLE
Spack detects Apple Clang as CCE on macOS

### ISSUE THREAD

**Issue by wyphan** [LLNL/spack#33901]
### Steps to reproduce

On a fresh Spack clone on Apple M2 (2022 model), running Monterey,
```shell
$ spack external find --all
```
detects `/usr/bin/cc` as the Cray compiler wrapper `cc`, even though it is really `apple-clang` in disguise. Same goes with `spack compiler find`.

Terminal output of `spack -d external find --all`: [spack-external-find-all.log](https://github.com/spack/spack/files/10006608/spack-external-find-all.log)

Terminal output of `spack -d compiler find`: [spack-compiler-find.log](https://github.com/spack/spack/files/10006660/spack-compiler-find.log)

Of course, it can easily be fixed by `spack compiler rm cce`, so it's not that big of a deal.

(Side note: somehow Spack _correctly_ ignores the fake `/usr/bin/gcc`)

### Error message

```shell
$ /usr/bin/cc --version
Apple clang version 14.0.0 (clang-1400.0.29.202)
Target: arm64-apple-darwin21.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

```shell
$ cat ~/.spack/darwin/compilers.yaml 
compilers:
- compiler:
    spec: apple-clang@14.0.0
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: null
      fc: null
    flags: {}
    operating_system: monterey
    target: aarch64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: cce@14.0.0
    paths:
      cc: /usr/bin/cc
      cxx: null
      f77: null
      fc: null
    flags: {}
    operating_system: monterey
    target: aarch64
    modules: []
    environment: {}
    extra_rpaths: []
```

### Information on your system

Output of `spack debug report`:
* **Spack:** 0.20.0.dev0 (2913f8b42b27868c0ec021e6fb319ec5b26ab605)
* **Python:** 3.9.6
* **Platform:** darwin-monterey-m2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
Same problem with macOS 10.15.7 (x86_64), `spack compiler find` detects `/usr/bin/cc` as cce in addition to apple-clang. @becker33 is this related to your recent Cray refactor?

**Comment by adamjstewart** [comment]
@becker33 you usually fix Cray issues and likely have access to a CCE compiler. Can you make the CCE regex more specific?

**Comment by wyphan** [comment]
@becker33 Looks like Cray has always put their wrappers in `/opt/cray/pe/craype/<version>/bin`, regardless of "old" or "new" Cray as detected by `spack arch`.

Theta - "old" Cray:
```
wyphan@thetalogin4:~$ sw/spack/bin/spack arch
cray-cnl7-haswell
wyphan@thetalogin4:~$ which cc
/opt/cray/pe/craype/2.6.5/bin/cc
```

Polaris - "new" Cray:
```
wyphan@polaris-login-01:~$ sw/spack/bin/spack arch
linux-sles15-zen3
wyphan@polaris-login-01:~$ which cc
/opt/cray/pe/craype/2.7.15/bin/cc
```
