### ISSUE TITLE
Error with `spack add`

### ISSUE THREAD

**Issue by nish-ant** [LLNL/spack#33913]
### Steps to reproduce

I am running `spack add` to install pacakge:
```
$ spack add cgal@4.13 %gcc-7.3.0
```

### Error message

I get the following error:
```
==> Error: gcc-7.3.0: Identifier cannot contain '.'  Encountered when parsing spec:
    cgal@4.13
     ^
```
This error is same with other packages:
```
$ spack add hdf5@1.10.6 +cxx +fortran +hl -mpi +pic +shared +szip %gcc-7.3.0
==> Error: gcc-7.3.0: Identifier cannot contain '.'  Encountered when parsing spec:
    hdf5@1.10.6
     ^
$ spack add parmetis +int64 +shared %gcc-7.3.0
==> Error: gcc-7.3.0: Identifier cannot contain '.'  Encountered when parsing spec:
    parmetis
     ^
```

### Information on your system

* **Spack:** 0.19.0.dev0 (a4cec82841228266d10734ecae2056f2980bf482)
* **Python:** 3.9.2
* **Platform:** linux-centos7-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
You need to use:
```
spack add cgal@4.13 %gcc@7.3.0
                        ^
```
as dots are not allowed in the compiler name.
