### ISSUE TITLE
Defaults in `package_base` unconditionally deactivate package checks for multiple build systems

### ISSUE THREAD

**Issue by greenc-FNAL** [LLNL/spack#33928]
### Steps to reproduce

* Attempt to install a package with `--test=root` for a package using any of the build systems:
  * autotools
  * cmake
  * makefile
  * meson
  * nmake
  * python
  * qmake
  * racket
  * scons
  * sip
  * waf
* **IF** the recipe/build system defines checks at build or install time **AND** the relevant `XXX_time_test_callbacks` attribute is mentioned in the `legacy_attributes` list of the build system **AND** the recipe **DOES NOT** override same in (specifically) the Package class...
* **THEN** those checks will not be executed. 
 

### Error message

**N/A**

### Information on your system

* **Spack:** 0.19.0
* **Python:** 3.6.8
* **Platform:** linux-scientific7-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by greenc-FNAL** [comment]
This issue appears to be the result of the defaulting of `build_time_test_callbacks` and `install_time_test_callbacks` to `None` in `PackageBase` in conjunction with the listing of either or both of these items as `legacy_attributes`.

In the case where the recipe's package class does not override the default, then the `None` default from `PackageBase` overrides anything set by the builder in either the recipe's in-use builder or any of its bases.

Incoming PR with fix.

**Comment by greenc-FNAL** [comment]
This issue and #33942 are both applicable to `develop` and `releases/v0.19`

**Comment by alalazo** [comment]
Confirmed. Thanks for reporting the issue!
