### ISSUE TITLE
spack arch reports linux on cray system

### ISSUE THREAD

**Issue by simonpintarelli** [LLNL/spack#34016]
### Steps to reproduce

It seems spack is not detecting correctly that it is running on a cray system. I noticed it because suddenly all builds are getting linked with cray libsci.

```console
spack arch
```
Expected result `cray-sles15-zen`, but it prints `linux-sles15-zen2`.

According to git bisect the following commit https://github.com/spack/spack/commit/53fbaa5dcded49d4fa04ee307813071873dab4f3 is causing the problem

### Information on your system

```
* **Spack:** 0.20.0.dev0 (da0a6280acda4fc6f75fb90ee5389beb218c9ea7)
* **Python:** 3.6.15
* **Platform:** linux-sles15-zen2 
* **Concretizer:** clingo
*
```
The correct platform is `cray-sles15-zen2` (LUMI supercomputer).

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
This is by design, see #29392

**Comment by simonpintarelli** [comment]
Thank you, I should have read the commit message first. Looks like I need to remove the module section from the `compilers.yaml` then.
