### ISSUE TITLE
spack mirroring hungs

### ISSUE THREAD

**Issue by zeronewb** [LLNL/spack#34012]
### Steps to reproduce
Clean room env for CI ( without keys, github fingerprints, etc )
spack mirror create -d ~/mirror --all
Wait for a day or two ( nic and wan speed 10g+ ).

Mirroring is slow due to nested loops and direct invocations of curl binary; please, consider switching to PycURL  + asyncio with pools, or to PyPy, if you don't like external libs.

### Information on your system

* **Spack:** 0.20.0.dev0 (839a14c0ba11f88ec4cd944adad628430a8076c5)
* **Python:** 3.9.2
* **Platform:** linux-debian11-zen3
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by zeronewb** [comment]
Related 
https://github.com/spack/spack/issues/13604
https://github.com/spack/spack/pull/14616
Please, consider switching to at least https://github.com/libgit2/pygit2, instead of spawning a subshell with git running;
and, please, provide options for creating a mirror directly from s3, with help of AWS SDK.

```lib/spack/spack/util/web.py:392 ==> [2022-11-20-06:52:06.507986] Checking existence of https://mirror.spack.io/sollve/polly-1.0a2.tar.gz
lib/spack/spack/util/web.py:441 ==> [2022-11-20-06:52:07.109886] Failure reading URL: Download failed: HTTP Error 404: Not Found
lib/spack/spack/fetch_strategy.py:339 ==> [2022-11-20-06:52:07.110075] URL does not exist: https://mirror.spack.io/sollve/polly-1.0a2.tar.gz
lib/spack/spack/stage.py:524 ==> [2022-11-20-06:52:07.110211] FailedDownloadError: Failed to fetch file from URL: https://mirror.spack.io/sollve/polly-1.0a2.tar.gz
lib/spack/spack/fetch_strategy.py:843 ==> [2022-11-20-06:52:07.110343] Cloning git repository: https://github.com/SOLLVE/polly.git at commit 96168ae6fb436e95cd756950855a57b895070047
lib/spack/spack/util/executable.py:195 ==> [2022-11-20-06:52:07.110651] '/usr/bin/git' '--version'
lib/spack/spack/util/executable.py:195 ==> [2022-11-20-06:52:07.111909] '/usr/bin/git' '-c' 'advice.detachedHead=false' 'clone' 'https://github.com/SOLLVE/polly.git'
Cloning into 'polly'...
Username for 'https://github.com': ```

**Comment by haampie** [comment]
libgit2 is poor quality, I don't think we want to use it.

See for example the list of issues Julia has with libgit2: https://github.com/JuliaLang/Pkg.jl/issues/2679 and more here: https://github.com/JuliaLang/julia/issues?q=is%3Aissue+is%3Aopen+libgit2+label%3Alibgit2

They even haven't fixed https://github.com/libgit2/libgit2/issues/4019 in 6 years, which causes issues all the time in HPC.

So in short: no, we won't use libgit2.

**Comment by zeronewb** [comment]
>They even haven't fixed https://github.com/libgit2/libgit2/issues/4019 in 6 years, which causes issues all the time in HPC.
> So in short: no, we won't use libgit2.


Ok, valid point. Right now i just dropped all git repos for syncing.
P.S.  My 0.1 cents for MMAP issue, it works with NFS4+

**Comment by tgamblin** [comment]
I've basically found all git wrappers to be less reliable than just invoking git.  FWIW, we do not run external processes in subshells -- we just exec them from Spack.
