### ISSUE TITLE
bison doesn't find m4 at run time

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#3406]
While building `flex`, I had `bison` fail because it could not execute `m4`. The reason was that I had uninstalled the `m4` package (via Spack) which `bison` installed as its build dependency. Then, `bison` failed since this `m4` executable did not exist any more.

I think `m4` needs to be a run-time dependency of `bison` as well.

**Comment by adamjstewart** [comment]
Feel free to contribute a PR. Should be an easy change.
