### ISSUE TITLE
`use_xcode = True` doesn't work for Xcode 13+

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#34064]
### Steps to reproduce

Packages like `qt` require the full Xcode suite, and create a copy of the Xcode compilers in order to inject Spack's compiler wrappers. However, this seems to no longer work on newer versions of macOS.
```console
$ spack install -v qt
```
This command opens a prompt asking the user to install Xcode command line tools. However, the command line tools, and the full suite, are both already installed. 

### Error message

```
Failed to resolve SDK path for 'macosx'
Failed to resolve SDK path for 'macosx'
Failed to resolve SDK path for 'macosx'
Failed to resolve SDK path for 'macosx'
Failed to resolve SDK path for 'macosx'
Failed to resolve SDK path for 'macosx'
Failed to resolve SDK path for 'macosx'
Failed to resolve SDK path for 'macosx'
sh: line 1: 32557 Abort trap: 6           /var/folders/j1/68dlgpr91vlgs26vty2c8xk80000gn/T/ajstewart/spack-stage/xcode-select/apple-clang/14.0.0/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk '' -find make 2> /dev/null
make: error: sh -c '/var/folders/j1/68dlgpr91vlgs26vty2c8xk80000gn/T/ajstewart/spack-stage/xcode-select/apple-clang/14.0.0/Xcode.app/Contents/Developer/usr/bin/xcodebuild -sdk '' -find make 2> /dev/null' failed with exit code 34304: (null) (errno=No such file or directory)
xcode-select: Failed to locate 'make', requesting installation of command line developer tools.
```

### Information on your system

* **Spack:** 0.20.0.dev0 (58096f44c763542644354065c3164d4987aa0900)
* **Python:** 3.10.8
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo

It's unclear if this is an issue with newer macOS, newer Xcode, or arm64. Based on https://github.com/spack/spack/pull/32696#discussion_r1028801122, it may be an issue with Xcode 13+.

@mathstuf @davydden @tgamblin @sethrj

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by hartsw** [comment]
When you delete the build directory (so `/var/folders/j1/68dlgpr91vlgs26vty2c8xk80000gn/T/ajstewart/spack-stage` and whatever else) and re-run does it tell you that it's copying XCode over again?

Sometimes when I have issues with Qt and spack that seems to do the trick.

**Comment by adamjstewart** [comment]
The first time I ran `spack install qt`, I do remember it telling me that it's copying Xcode and not to interrupt the process.

I just ran `spack clean && spack install qt` but it's no longer printing this message. Is there somewhere else where this cache is maintained?

**Comment by adamjstewart** [comment]
It looks like `spack clean` doesn't touch this directory. If I manually remove it and try again, it does copy Xcode again. Is there a different `spack clean` flag that touches this location?

**Comment by hartsw** [comment]
I'm no spack expert, I've just done what you did and delete that directory manually.

**Comment by adamjstewart** [comment]
But yeah, when I delete that directory and try again, I encounter the same issue. It can't find make and asks me to install CLT.

**Comment by sethrj** [comment]
I wonder if this has to do with relocatable binaries on Apple silicon?

**Comment by adamjstewart** [comment]
Can anyone attempt to build Qt on x86_64 macOS with recent Xcode/macOS and see if this is limited to arm64?

**Comment by adamjstewart** [comment]
Any updates on this? Not really sure how to solve this one.

**Comment by bosmacs** [comment]
Appears to be an Xcode 13+ problem. I installed Xcode 12.5.1 on an M1/Monterey Mac, removed the staged Xcode.app copy, and was able to install qt. 

With 13.4 or 14.2 I get the same error when I try to run xcodebuild from the copy:
```
2022-12-26 09:48:04.455 xcodebuild[40552:1424876] Requested but did not find extension point with identifier Xcode.IDEFoundation.TypeRegistry
2022-12-26 09:48:05.483 xcodebuild[40552:1424876] Requested but did not find extension point with identifier Xcode.IDEFoundation.IDEResultKitSerializationConverter
xcodebuild: error: Initialization failed.
	Reason: No macOS Platform was found, but Xcode requires a macOS Platform. You may have an incomplete or damaged installation of Xcode.
```
The same command from `/Applications/Xcode.app` works fine.

**Comment by adamjstewart** [comment]
@haampie would you be interested in working on this? I know you're still working on fixing macOS binary relocation, this may be related.

**Comment by aumuell** [comment]
> Any updates on this? Not really sure how to solve this one.

I removed `use_xode = True` from the qt package, also disabled `qtlocation` for when building with `+opengl` (it didn't build for me on Linux, either), and then building `qt+dbus+opengl` succeeded as well as running a simple GUI application built against it. I didn't try `+webkit`, though. Perhaps Xcode is not required at all?

**Comment by adamjstewart** [comment]
Could you open a PR so I can test this?

If we can get this working without copying Xcode, I believe this is the only package that required it, so we might even be able to rip out a lot of broken code in Spack.
