### ISSUE TITLE
Spack OpenBLAS errors

### ISSUE THREAD

**Issue by DavidPoliakoff** [LLNL/spack#3409]
I was trying to install nwchem. On spack install openblas I get an error (at bottom of message). That package appears to be broken. Thoughts?

==> Error: AttributeError: 'Spec' object has no attribute 'cppflags'
[SPACK_ROOT]/var/spack/repos/builtin/packages/openblas/package.py:143, in check_install:
     132      @run_after('install')
     133      def check_install(self):
     134          spec = self.spec
     135          # Openblas may pass its own test but still fail to compile Lapack
     136          # symbols. To make sure we get working Blas and Lapack, do a small
     137          # test.
     138          source_file = join_path(os.path.dirname(self.module.__file__),
     139                                  'test_cblas_dgemm.c')
     140          blessed_file = join_path(os.path.dirname(self.module.__file__),
     141                                   'test_cblas_dgemm.output')
     142
  '>> 143          include_flags = spec.cppflags
     144          link_flags = spec.libs.ld_flags
     145          if self.compiler.name == 'intel':
     146              link_flags += ' -lifcore'
     147          link_flags += ' -lpthread'
     148          if '+openmp' in spec:
     149              link_flags += ' ' + self.compiler.openmp_flag
     150
     151          output = compile_c_and_execute(
     152              source_file, [include_flags], link_flags.split()
     153          )
     154          compare_output_file(output, blessed_file)

**Comment by adamjstewart** [comment]
Try updating to the latest develop branch. This was fixed in #3344.
