### ISSUE TITLE
`spack checksum` support for GitHub URLs is broken

### ISSUE THREAD

**Issue by manuelakuhn** [LLNL/spack#34164]
### Steps to reproduce

As requested by @adamjstewart in #34162, open this as separate issue:

When trying to see the different versions available upstream for a package on github, `spack checksum` does not detect GitHub URLs automatically.

Reprocuce e.g. with package `dcm2niix`:
```
$ spack checksum dcm2niix
==> Found 1 version of dcm2niix:
  
  1.0.20210317  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20210317.tar.gz

==> Fetching https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20210317.tar.gz

    version("1.0.20210317", sha256="42fb22458ebfe44036c3d6145dacc6c1dc577ebbb067bedc190ed06f546ee05a")
```
Expected output:
```
» spack checksum dcm2niix    
==> Found 10 versions of dcm2niix:
  
  1.0.20220720  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20220720.tar.gz
  1.0.20211006  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20211006.tar.gz
  1.0.20210317  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20210317.tar.gz
  1.0.20201102  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20201102.tar.gz
  1.0.20200331  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20200331.tar.gz
  1.0.20190902  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20190902.tar.gz
  1.0.20190720  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20190720.tar.gz
  1.0.20181125  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20181125.tar.gz
  1.0.20181114  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20181114.tar.gz
  1.0.20180622  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20180622.tar.gz
...
```

### Information on your system

* **Spack:** 0.20.0.dev0 (066ec316047cb6dfc92a3fef9980718ade47d4aa)
* **Python:** 3.11.0
* **Platform:** linux-fedora37-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
I think @tldahlgren recently edited these files and may know which commit might have broken this. If not let me know and I can do some digging after my prelims.

**Comment by tldahlgren** [comment]
After some digging, I noted `list_depth` defaulting to `0` is an issue.  Per https://spack.readthedocs.io/en/latest/packaging_guide.html#list-depth, I added `list_url` and `list_depth` and `spack checksum` and it worked BUT *not consistently* as shown below:

```
$ spack checksum dcm2niix
==> Found 10 versions of dcm2niix:
  
  1.0.20220720  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20220720.tar.gz
  1.0.20211006  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20211006.tar.gz
  1.0.20210317  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20210317.tar.gz
  1.0.20201102  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20201102.tar.gz
  1.0.20200331  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20200331.tar.gz
  1.0.20190902  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20190902.tar.gz
  1.0.20190720  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20190720.tar.gz
  1.0.20181125  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20181125.tar.gz
  1.0.20181114  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20181114.tar.gz
  1.0.20180622  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20180622.tar.gz

==> How many would you like to checksum? (default is 1, q to abort) q
==> Error: Aborted.
$ spack checksum dcm2niix
==> Found 10 versions of dcm2niix:
  
  1.0.20220720  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20220720.tar.gz
  1.0.20211006  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20211006.tar.gz
  1.0.20210317  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20210317.tar.gz
  1.0.20201102  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20201102.tar.gz
  1.0.20200331  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20200331.tar.gz
  1.0.20190902  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20190902.tar.gz
  1.0.20190720  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20190720.tar.gz
  1.0.20181125  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20181125.tar.gz
  1.0.20181114  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20181114.tar.gz
  1.0.20180622  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20180622.tar.gz

==> How many would you like to checksum? (default is 1, q to abort) q
==> Error: Aborted.
$ spack checksum dcm2niix
==> Found 10 versions of dcm2niix:
  
  1.0.20220720  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20220720.tar.gz
  1.0.20211006  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20211006.tar.gz
  1.0.20210317  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20210317.tar.gz
  1.0.20201102  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20201102.tar.gz
  1.0.20200331  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20200331.tar.gz
  1.0.20190902  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20190902.tar.gz
  1.0.20190720  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20190720.tar.gz
  1.0.20181125  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20181125.tar.gz
  1.0.20181114  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20181114.tar.gz
  1.0.20180622  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20180622.tar.gz

==> How many would you like to checksum? (default is 1, q to abort) 1
==> Fetching https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20220720.tar.gz

    version("1.0.20220720", sha256="a095545d6d70c5ce2efd90dcd58aebe536f135410c12165a9f231532ddab8991")

$ spack checksum dcm2niix
==> Found 1 version of dcm2niix:
  
  1.0.20220720  https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20220720.tar.gz

==> Fetching https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20220720.tar.gz

    version("1.0.20220720", sha256="a095545d6d70c5ce2efd90dcd58aebe536f135410c12165a9f231532ddab8991")
```

**Comment by adamjstewart** [comment]
`list_depth` shouldn't matter, https://github.com/rordenlab/dcm2niix/releases lists all release tarballs, there's no need to spider down through different pages.

**Comment by tldahlgren** [comment]
> `list_depth` shouldn't matter, https://github.com/rordenlab/dcm2niix/releases lists all release tarballs, there's no need to spider down through different pages.

It apparently does based on the URLs that are being `spider`ed.  At least that's what I'm seeing for this example.  And it's the https://github.com/rordenlab/dcm2niix/archive/refs/tags/ that show more versions.

**Comment by tldahlgren** [comment]
Note the behavior above may also be related to switching `_spider` to use `ThreadPool` as a context manager.

**Comment by adamjstewart** [comment]
> It apparently does based on the URLs that are being spidered.

The https://github.com/rordenlab/dcm2niix/releases page contains the links we are looking for, spidering shouldn't be necessary. I think what's happening is that it's going from https://github.com/rordenlab/dcm2niix/releases to https://github.com/rordenlab/dcm2niix/tags and getting the links we want from there instead. I'm not sure why that would be necessary.

> And it's the https://github.com/rordenlab/dcm2niix/archive/refs/tags/ that show more versions.

We usually try to prefer releases over tags (especially for Autotools packages) since tags are auto-generated and don't contain built files like `configure`. Otherwise, we could modify the logic in `lib/spack/spack/url.py` to prefer `tags` over `releases`.

> Note the behavior above may also be related to switching _spider to use ThreadPool as a context manager.

What commit was this? Should be easy to test before and after.

**Comment by tldahlgren** [comment]
> > It apparently does based on the URLs that are being spidered.
> 
> The https://github.com/rordenlab/dcm2niix/releases page contains the links we are looking for, spidering shouldn't be necessary. I think what's happening is that it's going from https://github.com/rordenlab/dcm2niix/releases to https://github.com/rordenlab/dcm2niix/tags and getting the links we want from there instead. I'm not sure why that would be necessary.
> 

The links to the .tar.gz files scraped from the releases page point to the tags page.  For example, https://github.com/rordenlab/dcm2niix/archive/refs/tags/v1.0.20220720.tar.gz.

> 
> What commit was this? Should be easy to test before and after.

I agree it should be easy to test pre-commit.  I got a bit caught up in experimenting with changes related to use of `ThreadPool`.

**Comment by adamjstewart** [comment]
Any updates on this? Would love to be able to use `spack checksum` again for GitHub packages.

**Comment by alecbcs** [comment]
Hey all, was there any movement on this issue? I'm noticing that as more packages (e.g. abyss) move from GitHub archive tarballs to release tarballs that `spack version` is no longer finding versions for the packages. I believe this is going to be a growing issue as more packages move away from archive tarballs due to the lack of a permanent checksum.

**Comment by wdconinc** [comment]
Ran into this here too. The releases page has the asset links encapsulated in a fragment, e.g. `<include-fragment loading="lazy" src="https://github.com/VcDevel/Vc/releases/expanded_assets/1.4.3" >` at https://github.com/VcDevel/Vc/releases is linking to https://github.com/VcDevel/Vc/releases/expanded_assets/1.4.3. More at https://github.github.io/include-fragment-element/.
