### ISSUE TITLE
Installation issue: intel-oneapi-compilers

### ISSUE THREAD

**Issue by stephenmsachs** [LLNL/spack#34181]
### Steps to reproduce the issue

Error occurs if you use `intel-oneapi-compilers-classic@2021.6.0` ~= `intel-oneapi-compilers@2022.1.0` installed on top of `gcc@12` and then try to install e.g. OpenFOAM with the `intel` compiler.

```console
spack install openfoam@2012_220610 %intel@2021.6.0 ^scotch@6.0.9 ^intel-oneapi-mpi
```

### Error message

/shared/spack/opt/spack/linux-amzn2-x86_64_v3/gcc-7.3.1/gcc-12.2.0-4tairupdxg2tg2yhvjdlbs7xbd7wudl3/bin/../include/c++/12.2.0/bits/random.h(104): error: expected a declaration
        { __extension__ using type = unsigned __int128; };
                        ^

### Information on your system

* **Spack:** 0.20.0.dev0 (7de39c44b13b0db8278c92ffe63e117747ca655b)
* **Python:** 3.7.10
* **Platform:** linux-amzn2-skylake_avx512
* **Concretizer:** clingo

### Additional information

According to https://matsci.org/t/compilation-error-intel-compilers-and-gcc-12/42302 there seems to be a version dependency of Intel compilers to the underlying GCC. I could not find any GCC dependencies in Intels release notes.

Tagging maintainer @rscohn2 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by rscohn2** [comment]
The dependency on gcc is described here: https://www.intel.com/content/www/us/en/develop/documentation/cpp-compiler-developer-guide-and-reference/top/compatibility-and-portability/gcc-compatibility-and-interoperability.html

If you `spack install intel-oneapi-compilers%gcc@12` then it should use header files from gcc12, and this appears to be happening based on the error message. Try install with gcc11

**Comment by stephenmsachs** [comment]
@rscohn2 thanks for the pointer. However, I cannot find any version specific information in there. I would love to add something like `requires("%gcc@:11", when="@2022.1.0")`, but I don't know to which versions this applies.

**Comment by rscohn2** [comment]
I could not find anything. icc has been deprecated so if it doesn't support gcc12 headers now, it will likely never support it.

**Comment by stephenmsachs** [comment]
Ok, I'll try `requires("%gcc@:11", when="@2022.1.0")` then. It looks like icc from 2022.2.0 supports gcc 12.
