### ISSUE TITLE
apptainer: conmon config flag added in singularityce not available 

### ISSUE THREAD

**Issue by wdconinc** [LLNL/spack#34192]
#33891 has caused a regression in apptainer, which does not like the `--without-conmon` flag in its [mconfig](https://github.com/apptainer/apptainer/blob/main/mconfig), since apptainer uses [singularityce]([url](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/apptainer/package.py)) as its base.

_Originally posted by @wdconinc in https://github.com/spack/spack/issues/33891#issuecomment-1331101581_

**Comment by wdconinc** [comment]
I don't know what the right approach is here: `if singularity_name == 'apptainer'` before `confstring += " --without-conmon"` seems hacky and won't handle well if/when apptainer adds conmon support...

**Comment by alalazo** [comment]
The correct approach is either to have a common shared base class, or (simpler) to create an overrideable method in which all the SingularityCE options are put. That method can be then overridden by Apptainer.

**Comment by wdconinc** [comment]
This was fixed in https://github.com/spack/spack/pull/34329 by overriding `edit`, but I only noticed that after I opened https://github.com/spack/spack/pull/34474.
