### ISSUE TITLE
Installation issue: krb5~shared

### ISSUE THREAD

**Issue by charmoniumQ** [LLNL/spack#34193]
### Steps to reproduce the issue

Note that `krb5+shared` works fine.

```console
$ spack spec -I <spec>
Input spec
--------------------------------
 -   krb5~shared

Concretized
--------------------------------
 -   krb5@1.20.1%gcc@11.3.0~shared build_system=autotools arch=linux-ubuntu22.04-skylake
[+]      ^bison@3.8.2%gcc@11.3.0 arch=linux-ubuntu22.04-skylake
[+]          ^m4@1.4.19%gcc@11.3.0+sigsegv patches=9dc5fbd,bfdffa7 arch=linux-ubuntu22.04-skylake
[+]              ^libsigsegv@2.13%gcc@11.3.0 arch=linux-ubuntu22.04-skylake
[+]          ^perl@5.34.1%gcc@11.3.0+cpanm+shared+threads arch=linux-ubuntu22.04-skylake
[+]              ^berkeley-db@18.1.40%gcc@11.3.0+cxx~docs+stl patches=b231fcc arch=linux-ubuntu22.04-skylake
[+]              ^gdbm@1.19%gcc@11.3.0 arch=linux-ubuntu22.04-skylake
[+]                  ^readline@8.1%gcc@11.3.0 arch=linux-ubuntu22.04-skylake
[+]              ^zlib@1.2.12%gcc@11.3.0+optimize+pic+shared patches=0d38234 arch=linux-ubuntu22.04-skylake
[+]      ^diffutils@3.8%gcc@11.3.0 arch=linux-ubuntu22.04-skylake
[+]          ^libiconv@1.16%gcc@11.3.0 libs=shared,static arch=linux-ubuntu22.04-skylake
[+]      ^gettext@0.21.1%gcc@11.3.0+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=linux-ubuntu22.04-skylake
[+]          ^bzip2@1.0.8%gcc@11.3.0~debug~pic+shared arch=linux-ubuntu22.04-skylake
[+]          ^libxml2@2.10.3%gcc@11.3.0~python build_system=autotools arch=linux-ubuntu22.04-skylake
[+]              ^pkgconf@1.8.0%gcc@11.3.0 arch=linux-ubuntu22.04-skylake
[+]          ^ncurses@6.2%gcc@11.3.0~symlinks+termlib abi=none arch=linux-ubuntu22.04-skylake
[+]          ^tar@1.34%gcc@11.3.0 arch=linux-ubuntu22.04-skylake
[+]          ^xz@5.2.5%gcc@11.3.0~pic libs=shared,static arch=linux-ubuntu22.04-skylake
[+]      ^openssl@1.1.1s%gcc@11.3.0~docs~shared build_system=generic certs=mozilla arch=linux-ubuntu22.04-skylake
[+]          ^ca-certificates-mozilla@2022-10-11%gcc@11.3.0 build_system=generic arch=linux-ubuntu22.04-skylake
[+]          ^perl@5.36.0%gcc@11.3.0+cpanm+shared+threads build_system=generic arch=linux-ubuntu22.04-skylake
[+]          ^zlib@1.2.13%gcc@11.3.0+optimize+pic~shared build_system=makefile arch=linux-ubuntu22.04-skylake
```

### Error message

<details><summary>Error message</summary><pre>
==> Installing krb5-1.20.1-hnlfmq4zdeqzd76iusibekzpox35pvh4
==> No binary for krb5-1.20.1-hnlfmq4zdeqzd76iusibekzpox35pvh4 found: installing from source
==> Using cached archive: /home/sam/.local/share/spack/var/spack/cache/_source-cache/archive/70/704aed49b19eb5a7178b34b2873620ec299db08752d6a8574f95d41879ab8851.tar.gz  
==> Ran patch() for krb5
==> krb5: Executing phase: 'autoreconf'
==> krb5: Executing phase: 'configure'
==> krb5: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j4' 'V=1'

5 errors found in build log:
     2367    /home/sam/.local/share/spack/lib/spack/env/gcc/gcc -DHAVE_CONFIG_H  -I../../include -I../../include -I. -DKRB5_DEPRECATED=1 -DKRB5_PRIVATE  -g -O2 -Wall
              -Wcast-align -Wshadow -Wmissing-prototypes -Wno-format-zero-length -Woverflow -Wstrict-overflow -Wmissing-format-attribute -Wmissing-prototypes -Wretur
             n-type -Wmissing-braces -Wparentheses -Wswitch -Wunused-function -Wunused-label -Wunused-variable -Wunused-value -Wunknown-pragmas -Wsign-compare -Werro
             r=uninitialized -Wno-maybe-uninitialized -Werror=pointer-arith -Werror=int-conversion -Werror=incompatible-pointer-types -Werror=discarded-qualifiers -W
             error=implicit-int -Werror=declaration-after-statement -Werror-implicit-function-declaration -pthread  -c tdumputil.c
     2368    tdumputil.c: In function 'writequoted':
     2369    tdumputil.c:109:5: warning: function 'writequoted' might be a candidate for 'gnu_printf' format attribute [-Wsuggest-attribute=format]
     2370      109 |     ret = vasprintf(&s, fmt, ap);
     2371          |     ^~~
     2372    /home/sam/.local/share/spack/lib/spack/env/gcc/gcc -L../../lib -Wl,--enable-new-dtags -Wl,-rpath -Wl,/home/sam/.local/share/spack/opt/spack/linux-ubuntu
             22.04-skylake/gcc-11.3.0/krb5-1.20.1-hnlfmq4zdeqzd76iusibekzpox35pvh4/lib -g -O2   -o kdb5_util kdb5_util.o kdb5_create.o kadm5_create.o kdb5_destroy.o 
             kdb5_stash.o import_err.o strtok.o dump.o ovload.o kdb5_mkey.o tabdump.o tdumputil.o ../cli/getdate.o -lkadm5srv_mit  -lkdb5 -lkrb5_db2 -lkadm5srv_mit -
             lgssrpc -lgssapi_krb5 -lgssrpc -lgssapi_krb5  -pthread  -lkrb5 -lk5crypto -lcom_err -lkrb5support  -lresolv
  >> 2373    /usr/bin/ld: ../../lib/libkadm5srv_mit.a(server_kdb.o):/tmp/sam/spack-stage/spack-stage-krb5-1.20.1-hnlfmq4zdeqzd76iusibekzpox35pvh4/spack-src/src/lib/k
             adm5/srv/server_kdb.c:18: multiple definition of `master_keyblock'; kdb5_util.o:/tmp/sam/spack-stage/spack-stage-krb5-1.20.1-hnlfmq4zdeqzd76iusibekzpox3
             5pvh4/spack-src/src/kadmin/dbutil/kdb5_util.c:109: first defined here
  >> 2374    collect2: error: ld returned 1 exit status
  >> 2375    make[2]: *** [Makefile:632: kdb5_util] Error 1
     2376    make[2]: Leaving directory '/tmp/sam/spack-stage/spack-stage-krb5-1.20.1-hnlfmq4zdeqzd76iusibekzpox35pvh4/spack-src/src/kadmin/dbutil'
  >> 2377    make[1]: *** [Makefile:834: all-recurse] Error 1
     2378    make[1]: Leaving directory '/tmp/sam/spack-stage/spack-stage-krb5-1.20.1-hnlfmq4zdeqzd76iusibekzpox35pvh4/spack-src/src/kadmin'
  >> 2379    make: *** [Makefile:1521: all-recurse] Error 1

See build log for details:
  /tmp/sam/spack-stage/spack-stage-krb5-1.20.1-hnlfmq4zdeqzd76iusibekzpox35pvh4/spack-build-out.txt

==> Warning: Skipping build of micromamba-1.0.0-l2izhojlglbvysy7jxqrnizqkh2u5ofb since krb5-1.20.1-hnlfmq4zdeqzd76iusibekzpox35pvh4 failed
==> Waiting for libssh2-1.10.0-s4yh3dm4dnp56ofcbnyo6747aoe354wl
[+] /home/sam/.local/share/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/libssh2-1.10.0-s4yh3dm4dnp56ofcbnyo6747aoe354wl
==> Waiting for libsolv-0.7.22-uilhwof2s3ubica724rrdekjf4jjrczg
[+] /home/sam/.local/share/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-11.3.0/libsolv-0.7.22-uilhwof2s3ubica724rrdekjf4jjrczg
==> Error: micromamba-1.0.0-l2izhojlglbvysy7jxqrnizqkh2u5ofb: Package was not installed
==> Error: Installation request failed.  Refer to reported errors for failing package(s).
</pre></details>

### Information on your system

* **Spack:** 0.20.0.dev0 (166e45a337c718c4f5d57926df9c67fe0b46947a)
* **Python:** 3.9.13
* **Platform:** linux-ubuntu22.04-skylake
* **Concretizer:** clingo

### Additional information

- [`spack-build-out.txt`](http://dpaste.com/8VAJMH595)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by zeronewb** [comment]
CFLAGS=-fcommon ?
`            if "%gcc@10:" in spec:
                compilerArgs.append("CFLAGS=-fcommon")`

**Comment by charmoniumQ** [comment]
This seems to work; thanks!
