### ISSUE TITLE
Installation issue: rust-1.65

### ISSUE THREAD

**Issue by thomas-bouvier** [LLNL/spack#34254]
### Steps to reproduce the issue

```console
$ spack spec -I <spec>
Input spec
--------------------------------
 -   rust

Concretized
--------------------------------
 -   rust@1.65.0%gcc@12.2.1+analysis+clippy~rls+rustfmt+src build_system=generic extra_targets=none arch=linux-fedora36-skylake
[+]      ^cmake@3.25.0%gcc@12.2.1~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-fedora36-skylake
[+]          ^ncurses@6.3%gcc@12.2.1~symlinks+termlib abi=none build_system=autotools arch=linux-fedora36-skylake
[+]      ^gmake@4.3%gcc@12.2.1~guile+nls build_system=autotools patches=599f134 arch=linux-fedora36-skylake
[+]          ^gettext@0.21.1%gcc@12.2.1+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=linux-fedora36-skylake
[+]              ^libiconv@1.16%gcc@12.2.1 build_system=autotools libs=shared,static arch=linux-fedora36-skylake
[+]              ^libxml2@2.10.3%gcc@12.2.1~python build_system=autotools arch=linux-fedora36-skylake
[+]              ^tar@1.34%gcc@12.2.1 build_system=autotools zip=pigz arch=linux-fedora36-skylake
[+]                  ^pigz@2.7%gcc@12.2.1 build_system=makefile arch=linux-fedora36-skylake
[+]                  ^zstd@1.5.2%gcc@12.2.1+programs build_system=makefile compression=none libs=shared,static arch=linux-fedora36-skylake
[+]          ^texinfo@7.0%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]      ^libgit2@1.5.0%gcc@12.2.1~curl~ipo+mmap+ssh build_system=cmake build_type=RelWithDebInfo https=system arch=linux-fedora36-skylake
[+]      ^libssh2@1.10.0%gcc@12.2.1~ipo+shared build_system=cmake build_type=RelWithDebInfo crypto=openssl arch=linux-fedora36-skylake
[+]          ^xz@5.2.7%gcc@12.2.1~pic build_system=autotools libs=shared,static arch=linux-fedora36-skylake
[+]          ^zlib@1.2.13%gcc@12.2.1+optimize+pic+shared build_system=makefile arch=linux-fedora36-skylake
[+]      ^ninja@1.11.1%gcc@12.2.1 build_system=generic arch=linux-fedora36-skylake
[+]          ^re2c@2.2%gcc@12.2.1 build_system=generic arch=linux-fedora36-skylake
[+]      ^openssl@1.1.1s%gcc@12.2.1~docs~shared build_system=generic certs=mozilla arch=linux-fedora36-skylake
[+]          ^ca-certificates-mozilla@2022-10-11%gcc@12.2.1 build_system=generic arch=linux-fedora36-skylake
[+]          ^perl@5.36.0%gcc@12.2.1+cpanm+shared+threads build_system=generic arch=linux-fedora36-skylake
[+]              ^berkeley-db@18.1.40%gcc@12.2.1+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-fedora36-skylake
[+]      ^pkgconf@1.8.0%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]      ^python@3.10.8%gcc@12.2.1+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=0d98e93,7d40923,f2fd060 arch=linux-fedora36-skylake
[+]          ^bzip2@1.0.8%gcc@12.2.1~debug~pic+shared build_system=generic arch=linux-fedora36-skylake
[+]              ^diffutils@3.8%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]          ^expat@2.4.8%gcc@12.2.1+libbsd build_system=autotools arch=linux-fedora36-skylake
[+]              ^libbsd@0.11.5%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]                  ^libmd@1.0.4%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]          ^gdbm@1.23%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]          ^libffi@3.4.2%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]          ^libxcrypt@4.4.33%gcc@12.2.1~obsolete_api build_system=autotools arch=linux-fedora36-skylake
[+]          ^readline@8.1.2%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]          ^sqlite@3.40.0%gcc@12.2.1+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-fedora36-skylake
[+]          ^util-linux-uuid@2.38.1%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
```

### Error message

<details><summary>Error message</summary><pre>
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/pkgconf-1.8.0-7gw2utidokm4j4wjo5rzbazgb4npc7n3
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/ca-certificates-mozilla-2022-10-11-wu5ruaxqiapvh7a2v4o4hysieuk7afgb
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/berkeley-db-18.1.40-7igdikyxe3bakacrrnocnwgobio7daby
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/libiconv-1.16-ydwppdsarhpt6d5vg6q3yaje2awudbbz
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/zlib-1.2.13-z2ejqu5rwkpzthixfl2u33cr7pqxto5d
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/xz-5.2.7-k53c4b2ow5mteeqnwthad3gzjckbmjar
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/zstd-1.5.2-ih6rzolz2pgn3ipigmjvtyuyjnbzqa35
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/libmd-1.0.4-yf6j6stncofla6opewklry3gnzlxkjnt
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/libffi-3.4.2-iu37isiisn7qhs25ufgtnkf37o2uzhqu
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/libxcrypt-4.4.33-3y36xqlubxx7qh6o74flsjcaz27tilym
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/re2c-2.2-ns74zyj2uazlhutktnllgalsbdal5ib4
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/util-linux-uuid-2.38.1-ymdgoqs3jnamtttvcss6gppnjh6j744m
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/ncurses-6.3-wn6zyhjhk673nm7kmvaorpor3dnr6nqv
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/diffutils-3.8-n3kjieod65bakai4b7mufqbvav66anb6
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/pigz-2.7-cfoygddupzkyqhyajceuxwxyh2wvsvmw
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/libxml2-2.10.3-vy23qwigp32633zjoplkuxq773zt4pnu
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/libbsd-0.11.5-exucfqo55wr3n6q2vv4wquttpxfee7xc
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/readline-8.1.2-cjlsqviyk6vhgnzknmodilrnsd3enkzy
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/bzip2-1.0.8-eukc333yrn5vf3gcq22ozqafw3oiyvyx
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/expat-2.4.8-i7jc7jl5mgnarccndjtuwss6ikxsrp24
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/sqlite-3.40.0-z6utbhssnjwtllc4vdkfnuoeba33w624
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/gdbm-1.23-b3pl22b7yzxr4k6xeot6xvqsmb6ri2g4
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/tar-1.34-qp3edkfqd3nrxrpzuxpasv5lh4ilwbxw
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/perl-5.36.0-35g7qkauwqb7vmntd3j75etlyqxtvgax
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/gettext-0.21.1-k4ndpqczzwdg2mnda335jjwrkqx4fon6
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/openssl-1.1.1s-zsp2zerliaqbmobjabbthuihw4omsrvn
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/texinfo-7.0-3kzjea43giolo3wtao5l3jb3n2bzqyjq
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/cmake-3.25.0-jroj27bquxy5bhlqajxo45k7ok7hug4q
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/python-3.10.8-cp7as6judwexxg3j4fmoqn3zvzfchuiq
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/gmake-4.3-alg64lgw3kijtjrwdoeixea2zoufpvyw
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/libssh2-1.10.0-twzqa4octqjcnepkmtzqgfbl7grzwtdl
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/ninja-1.11.1-o3chaevauae5ewc7m47snspis36tkmko
[+] /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/libgit2-1.5.0-nfjhlfscpgxcbldvtnkw7wigmvj7ljao
==> Installing rust-1.65.0-zgpzu7iv2c6a37yddwi7sworhxhadvv2
==> No binary for rust-1.65.0-zgpzu7iv2c6a37yddwi7sworhxhadvv2 found: installing from source
==> Using cached archive: /home/spack/var/spack/cache/_source-cache/archive/58/5828bb67f677eabf8c384020582b0ce7af884e1c84389484f7f8d00dd82c0038.tar.gz
==> Using cached archive: /home/spack/var/spack/cache/_source-cache/archive/8f/8f754fdd5af783fe9020978c64e414cb45f3ad0a6f44d045219bbf2210ca3cb9.tar.gz
==> Moving resource stage
        source: /home/.spack/stage/resource-rust-1.65.0-x86_64-unknown-linux-gnu-zgpzu7iv2c6a37yddwi7sworhxhadvv2/spack-src/
        destination: /home/.spack/stage/spack-stage-rust-1.65.0-zgpzu7iv2c6a37yddwi7sworhxhadvv2/spack-src/spack_bootstrap_stage/rust-1.65.0-x86_64-unknown-linux-gnu
==> Ran patch() for rust
==> rust: Executing phase: 'configure'
==> rust: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 1:
    '/home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/python-3.10.8-cp7as6judwexxg3j4fmoqn3zvzfchuiq/bin/python3.10' './x.py' 'build'

4 errors found in build log:
     16118    -- Detecting C compile features
     16119    -- Detecting C compile features - done
     16120    -- Detecting CXX compiler ABI info
     16121    -- Detecting CXX compiler ABI info - failed
     16122    -- Check for working CXX compiler: /home/spack/lib/spack/env/gcc/g++
     16123    -- Check for working CXX compiler: /home/spack/lib/spack/env/gcc/g++ - broken
  >> 16124    CMake Error at /home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/cmake-3.25.0-jroj27bquxy5bhlqajxo45k7ok7hug4q/share/cmake-3.25/Modules/CMakeTestCXXCompiler.cmake:63 (message):
     16125      The C++ compiler
     16126
     16127        "/home/spack/lib/spack/env/gcc/g++"
     16128
     16129      is not able to compile a simple test program.
     16130
     16131      It fails with the following output:
     16132
     16133        Change Dir: /home/.spack/stage/spack-stage-rust-1.65.0-zgpzu7iv2c6a37yddwi7sworhxhadvv2/spack-src/build/x86_64-unknown-linux-gnu/llvm/build/CMakeFiles/CMakeScratch/TryCompile-OcR13F
     16134
     16135        Run Build Command(s):/home/spack/opt/spack/linux-fedora36-skylake/gcc-12.2.1/ninja-1.11.1-o3chaevauae5ewc7m47snspis36tkmko/bin/ninja-build cmTC_72e88 && [1/2] Building CXX object CMakeFiles/cmTC_72e88.dir/testCXXCompiler.cxx.o
     16136        [2/2] Linking CXX executable cmTC_72e88
  >> 16137    FAILED: cmTC_72e88
     16138        : && /home/spack/lib/spack/env/gcc/g++ -ffunction-sections -fdata-sections -fPIC -m64 -Wl,-Bsymbolic -static-libstdc++ CMakeFiles/cmTC_72e88.dir/testCXXCompiler.cxx.o -o cmTC_72e88   && :
  >> 16139        /usr/bin/ld: cannot find -lstdc++
  >> 16140        collect2: error: ld returned 1 exit status
     16141        ninja: build stopped: subcommand failed.
</pre></details>

### Information on your system

```
* **Spack:** 0.20.0.dev0 (b139cab687c9fcb1dc11b39f5bb2ec91b76c3dbc)
* **Python:** 3.10.8
* **Platform:** linux-fedora36-skylake
* **Concretizer:** clingo
```

This issue occurs when trying to install rust locally `spack install rust`.

I was initially trying to install Horovod with PyTorch, whose Rust is an indirect dependency.

```
❯ cat spack.yaml
spack:
  specs:
  - py-horovod@0.26.1 controllers=mpi frameworks=pytorch ^openmpi@4.1.2 ^py-torch -caffe2 -gloo
  concretizer:
    unify: true
  compilers:
  - compiler:
      spec: gcc@12.2.1
      paths:
        cc: /usr/bin/gcc
        cxx: /usr/bin/g++
        f77: /usr/bin/gfortran
        fc: /usr/bin/gfortran
      flags: {}
      operating_system: fedora36
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
```

<details><summary>spack spec -I py-horovod</summary><pre>
Input spec
--------------------------------
 -   py-horovod@0.26.1 controllers=mpi frameworks=pytorch
 -       ^openmpi@4.1.2
 -       ^py-torch~caffe2~gloo

Concretized
--------------------------------
 -   py-horovod@0.26.1%gcc@12.2.1~cuda~rocm build_system=python_pip controllers=mpi frameworks=pytorch tensor_ops=mpi arch=linux-fedora36-skylake
[+]      ^cmake@3.25.0%gcc@12.2.1~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-fedora36-skylake
[+]          ^ncurses@6.3%gcc@12.2.1~symlinks+termlib abi=none build_system=autotools arch=linux-fedora36-skylake
[+]          ^openssl@1.1.1s%gcc@12.2.1~docs~shared build_system=generic certs=mozilla arch=linux-fedora36-skylake
[+]              ^ca-certificates-mozilla@2022-10-11%gcc@12.2.1 build_system=generic arch=linux-fedora36-skylake
[+]      ^openmpi@4.1.2%gcc@12.2.1~atomics~cuda~cxx~cxx_exceptions~gpfs~internal-hwloc~java~legacylaunchers~lustre~memchecker+romio+rsh~singularity+static+vt+wrapper-rpath build_system=autotools fabrics=none schedulers=none arch=linux-fedora36-skylake
[+]          ^hwloc@2.8.0%gcc@12.2.1~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-fedora36-skylake
[+]              ^libpciaccess@0.16%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]                  ^util-macros@1.19.3%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]              ^libxml2@2.10.3%gcc@12.2.1~python build_system=autotools arch=linux-fedora36-skylake
[+]          ^numactl@2.0.14%gcc@12.2.1 build_system=autotools patches=4e1d78c,62fc8a8,ff37630 arch=linux-fedora36-skylake
[+]              ^autoconf@2.69%gcc@12.2.1 build_system=autotools patches=35c4492,7793209,a49dd5b arch=linux-fedora36-skylake
[+]              ^automake@1.16.5%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]              ^libtool@2.4.7%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]              ^m4@1.4.19%gcc@12.2.1+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-fedora36-skylake
[+]                  ^libsigsegv@2.13%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]          ^openssh@9.1p1%gcc@12.2.1+gssapi build_system=autotools arch=linux-fedora36-skylake
[+]              ^krb5@1.20.1%gcc@12.2.1+shared build_system=autotools arch=linux-fedora36-skylake
[+]                  ^bison@3.8.2%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]              ^libedit@3.1-20210216%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]          ^perl@5.36.0%gcc@12.2.1+cpanm+shared+threads build_system=generic arch=linux-fedora36-skylake
[+]              ^berkeley-db@18.1.40%gcc@12.2.1+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-fedora36-skylake
[+]          ^pmix@4.1.2%gcc@12.2.1~docs+pmi_backwards_compatibility~python~restful build_system=autotools arch=linux-fedora36-skylake
[+]              ^libevent@2.1.12%gcc@12.2.1+openssl build_system=autotools arch=linux-fedora36-skylake
[+]          ^zlib@1.2.13%gcc@12.2.1+optimize+pic+shared build_system=makefile arch=linux-fedora36-skylake
[+]      ^pkgconf@1.8.0%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]      ^py-cffi@1.15.1%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]          ^libffi@3.4.2%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]          ^py-pycparser@2.21%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]      ^py-cloudpickle@2.2.0%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]      ^py-packaging@21.3%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]          ^py-pyparsing@3.0.9%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]              ^py-flit-core@3.7.1%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]      ^py-pip@22.2.2%gcc@12.2.1 build_system=generic arch=linux-fedora36-skylake
[+]      ^py-psutil@5.9.2%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
 -       ^py-pytorch-lightning@1.5.3%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]          ^py-fsspec@2022.11.0%gcc@12.2.1+http build_system=python_pip arch=linux-fedora36-skylake
[+]              ^py-aiohttp@3.8.1%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]                  ^py-aiosignal@1.2.0%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]                  ^py-async-timeout@4.0.2%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]                  ^py-attrs@22.1.0%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]                  ^py-frozenlist@1.3.1%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]                  ^py-multidict@6.0.2%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]                  ^py-yarl@1.8.1%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]          ^py-future@0.18.2%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]          ^py-numpy@1.23.5%gcc@12.2.1+blas+lapack build_system=python_pip patches=873745d arch=linux-fedora36-skylake
[+]          ^py-pydeprecate@0.3.1%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
 -           ^py-tensorboard@2.10.0%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]              ^py-absl-py@1.2.0%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]              ^py-google-auth@2.11.0%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]                  ^py-cachetools@5.2.0%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]                  ^py-pyasn1-modules@0.2.8%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]                      ^py-pyasn1@0.4.8%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]                  ^py-rsa@4.9%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]                      ^py-poetry-core@1.2.0%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]              ^py-google-auth-oauthlib@0.4.6%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]                  ^py-requests-oauthlib@1.3.1%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]                      ^py-oauthlib@3.2.1%gcc@12.2.1~rsa~signals~signedtoken build_system=python_pip arch=linux-fedora36-skylake
[+]              ^py-grpcio@1.48.1%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]                  ^c-ares@1.15.0%gcc@12.2.1~ipo build_system=cmake build_type=RelWithDebInfo arch=linux-fedora36-skylake
[+]                  ^re2@2021-06-01%gcc@12.2.1~ipo+pic+shared build_system=cmake build_type=RelWithDebInfo arch=linux-fedora36-skylake
[+]              ^py-markdown@3.4.1%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
 -               ^py-tensorboard-data-server@0.6.1%gcc@12.2.1 build_system=python_pip patches=878bbd6 arch=linux-fedora36-skylake
 -                   ^rust@1.65.0%gcc@12.2.1+analysis+clippy~rls+rustfmt+src build_system=generic extra_targets=none arch=linux-fedora36-skylake
[+]                      ^gmake@4.3%gcc@12.2.1~guile+nls build_system=autotools patches=599f134 arch=linux-fedora36-skylake
[+]                          ^texinfo@7.0%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]                      ^libgit2@1.5.0%gcc@12.2.1~curl~ipo+mmap+ssh build_system=cmake build_type=RelWithDebInfo https=system arch=linux-fedora36-skylake
[+]                      ^libssh2@1.10.0%gcc@12.2.1~ipo+shared build_system=cmake build_type=RelWithDebInfo crypto=openssl arch=linux-fedora36-skylake
[+]              ^py-tensorboard-plugin-wit@1.8.1%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]              ^py-werkzeug@2.2.2%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]                  ^py-markupsafe@2.1.1%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]          ^py-torchmetrics@0.10.3%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]          ^py-tqdm@4.64.1%gcc@12.2.1~notebook~telegram build_system=python_pip arch=linux-fedora36-skylake
[+]              ^py-setuptools-scm@7.0.5%gcc@12.2.1+toml build_system=python_pip arch=linux-fedora36-skylake
[+]                  ^py-tomli@2.0.1%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]          ^py-typing-extensions@4.3.0%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]      ^py-pyyaml@6.0%gcc@12.2.1+libyaml build_system=python_pip arch=linux-fedora36-skylake
[+]          ^libyaml@0.2.5%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]          ^py-cython@0.29.32%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]      ^py-setuptools@59.4.0%gcc@12.2.1 build_system=generic arch=linux-fedora36-skylake
[+]      ^py-torch@1.13.0%gcc@12.2.1~caffe2~cuda~debug+distributed+fbgemm~gloo+kineto~metal+mkldnn+mpi+nnpack+numa+numpy+onnx_ml+openmp+qnnpack~rocm+tensorpipe~test+valgrind+xnnpack build_system=python_pip arch=linux-fedora36-skylake
[+]          ^eigen@3.4.0%gcc@12.2.1~ipo build_system=cmake build_type=RelWithDebInfo arch=linux-fedora36-skylake
[+]          ^fxdiv@2020-04-17%gcc@12.2.1~ipo build_system=cmake build_type=RelWithDebInfo arch=linux-fedora36-skylake
[+]          ^intel-mkl@2020.4.304%gcc@12.2.1~ilp64+shared build_system=generic threads=none arch=linux-fedora36-skylake
[+]              ^cpio@2.13%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]          ^ninja@1.11.1%gcc@12.2.1 build_system=generic arch=linux-fedora36-skylake
[+]              ^re2c@2.2%gcc@12.2.1 build_system=generic arch=linux-fedora36-skylake
[+]          ^protobuf@3.21.7%gcc@12.2.1~ipo+shared build_system=cmake build_type=Release arch=linux-fedora36-skylake
[+]          ^psimd@2020-05-17%gcc@12.2.1~ipo build_system=cmake build_type=RelWithDebInfo arch=linux-fedora36-skylake
[+]          ^pthreadpool@2021-04-13%gcc@12.2.1~ipo build_system=cmake build_type=RelWithDebInfo arch=linux-fedora36-skylake
[+]          ^py-astunparse@1.6.3%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]          ^py-protobuf@3.19.4%gcc@12.2.1~cpp build_system=python_pip arch=linux-fedora36-skylake
[+]          ^py-pybind11@2.10.0%gcc@12.2.1~ipo build_system=cmake build_type=RelWithDebInfo arch=linux-fedora36-skylake
[+]          ^py-requests@2.28.1%gcc@12.2.1~socks build_system=python_pip arch=linux-fedora36-skylake
[+]              ^py-certifi@2022.9.14%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]              ^py-charset-normalizer@2.0.12%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]              ^py-idna@3.4%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]              ^py-urllib3@1.26.12%gcc@12.2.1~brotli~secure~socks build_system=python_pip arch=linux-fedora36-skylake
[+]          ^py-six@1.16.0%gcc@12.2.1 build_system=python_pip arch=linux-fedora36-skylake
[+]          ^valgrind@3.19.0%gcc@12.2.1+boost+mpi+only64bit~ubsan build_system=autotools libs=shared,static arch=linux-fedora36-skylake
[+]              ^boost@1.80.0%gcc@12.2.1+atomic+chrono~clanglibcpp~container~context~contract~coroutine+date_time~debug+exception~fiber+filesystem+graph~graph_parallel~icu+iostreams~json+locale+log+math~mpi+multithreaded~nowide~numpy~pic+program_options~python+random+regex+serialization+shared+signals~singlethreaded~stacktrace+system~taggedlayout+test+thread+timer~type_erasure~versionedlayout+wave build_system=generic cxxstd=98 patches=a440f96 visibility=hidden arch=linux-fedora36-skylake
[+]                  ^zstd@1.5.2%gcc@12.2.1+programs build_system=makefile compression=none libs=shared,static arch=linux-fedora36-skylake
[+]      ^py-wheel@0.37.1%gcc@12.2.1 build_system=generic arch=linux-fedora36-skylake
[+]      ^python@3.10.8%gcc@12.2.1+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=0d98e93,7d40923,f2fd060 arch=linux-fedora36-skylake
[+]          ^bzip2@1.0.8%gcc@12.2.1~debug~pic+shared build_system=generic arch=linux-fedora36-skylake
[+]              ^diffutils@3.8%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]          ^expat@2.4.8%gcc@12.2.1+libbsd build_system=autotools arch=linux-fedora36-skylake
[+]              ^libbsd@0.11.5%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]                  ^libmd@1.0.4%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]          ^gdbm@1.23%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]          ^gettext@0.21.1%gcc@12.2.1+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=linux-fedora36-skylake
[+]              ^libiconv@1.16%gcc@12.2.1 build_system=autotools libs=shared,static arch=linux-fedora36-skylake
[+]              ^tar@1.34%gcc@12.2.1 build_system=autotools zip=pigz arch=linux-fedora36-skylake
[+]                  ^pigz@2.7%gcc@12.2.1 build_system=makefile arch=linux-fedora36-skylake
[+]          ^libxcrypt@4.4.33%gcc@12.2.1~obsolete_api build_system=autotools arch=linux-fedora36-skylake
[+]          ^readline@8.1.2%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]          ^sqlite@3.40.0%gcc@12.2.1+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-fedora36-skylake
[+]          ^util-linux-uuid@2.38.1%gcc@12.2.1 build_system=autotools arch=linux-fedora36-skylake
[+]          ^xz@5.2.7%gcc@12.2.1~pic build_system=autotools libs=shared,static arch=linux-fedora36-skylake
</pre></details>

### Additional information

@adamjstewart @AndrewGaspar 
[spack-build-out.txt](https://github.com/spack/spack/files/10137139/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/10137155/spack-build-env.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by thomas-bouvier** [comment]
Pinging @michaelkuhn as I stumbled upon #34124 :)

**Comment by michaelkuhn** [comment]
Do earlier versions of Rust work? It looks like you might need `libstdc++-devel`.

**Comment by thomas-bouvier** [comment]
I was able to build Rust 1.60 on my system with `spack install rust@1.60.0`.

`libstdc++-devel` is already present on my laptop. Shouldn't Spack take care of that anyway?

**Comment by robertu94** [comment]
@thomas-bouvier actually I think you need `libstdc++-static` instead because the compiler is invoked with `-static_libstdc++`  libstdc++ is the C++ standard library.  It would be like asking spack to try  using a c compiler without libc.  When compilers as dependencies are a thing this could be modeled, but for now, spack kind of has to assume that the compiler is fully installed.

@michaelkuhn assuming this works for @thomas-bouvier , perhaps the list of [required bootstrap dependencies](https://spack.readthedocs.io/en/latest/getting_started.html) should include `libstdc++-static`.

I successfully build spack@1.65.0 on Fedora 36 just last night.

**Comment by thomas-bouvier** [comment]
That was the issue indeed, `libstdc++-static` was missing on my system. Thank you @robertu94 :)

@michaelkuhn depending on your input I'll close the issue!

**Comment by michaelkuhn** [comment]
Glad you got it working. I usually build Rust with a Spack-built GCC, which is probably why I never ran into this issue. I personally wouldn't add `libstdc++-static` to the required dependencies since most packages build fine without it. It might make sense to improve the Rust package to mention this implicit dependency, though. However, I'm not sure whether we can easily catch the error and output a hint in case of failure.
