### ISSUE TITLE
Installation issue: %nvhpc with install_missing_compilers: true

### ISSUE THREAD

**Issue by antoine-morvan** [LLNL/spack#34266]
### Steps to reproduce the issue

```console
$ cat > spack.yaml << EOF
spack:
  specs: [zlib %nvhpc]
  config:
    install_missing_compilers: true
EOF
$ spack env activate -d .
$ spack concretize
$ spack install
```

### Error message

<details><summary>Error message</summary><pre>
==> Error: No valid compiler for zlib satisfies '%nvhpc'
</pre></details>

### Information on your system

Fresh checkout, deleted ~/.spack and no system config

* **Spack:** 0.20.0.dev0 (8420c610fa593699731a3a4b957a00f9baaeba0d)
* **Python:** 3.6.8
* **Platform:** linux-rhel8-zen3
* **Concretizer:** clingo

### Additional information

* changing %nvhpc to any other compilers works fine (tried with: gcc, aocc, oneapi, clang, intel)
* adding a version (%nvhpc@22 for instance) seems to concretize
* we have been able to observe the concretizer fail, but most of the time the concretizer successes but install fails

[spack.install.log](https://github.com/spack/spack/files/10141769/spack.install.log)

@samcmill

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by dguibert** [comment]
Hi,

This issue is still there (on top of 694292ebbf854393e0b15a7e46aa42c76265eacc), il also fails  by replacing %nvhpc with:
- %aocc
- %intel
- %oneapi

With %gcc the concretization is ok.

**Comment by dguibert** [comment]
on top of Commit 6db8e0a61e969835952a88c246166cc009af4e71, the error is now
````sh
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    zlib%nvhpc is unsatisfiable, errors are:
````

**Comment by haampie** [comment]
The option `install_missing_compilers` was removed.
