### ISSUE TITLE
spack compiler find on Cray says no new compilers found

### ISSUE THREAD

**Issue by mamelara** [LLNL/spack#3428]
Deleted my compilers.yaml and tried to create a new one but this happens

```┌[mamelara-edison06::spack
└┤[22:52] ➜ spack compiler find
==> Found no new compilers
```

It still writes to compilers.yaml and the yaml configuration looks correct but the output needs to be fixed.

**Comment by scheibelp** [comment]
I believe I created this with #2999 - I will work on having a fix tomorrow.
