### ISSUE TITLE
Markdown links used in RST docs

### ISSUE THREAD

**Issue by aidanheerdegen** [LLNL/spack#34485]
PR [#3186](https://github.com/spack/spack/pull/31860) added links in markdown instead of RST

https://github.com/spack/spack/pull/31860/files#diff-92248e71a3f43392d467e339068a95642d3cde6ecfa75e103b2c5245d277ef4cR2290-R2296

These are visible in the current docs:

https://spack.readthedocs.io/en/latest/packaging_guide.html#dependency-types

The fix is minor. I am happy to submit a PR. If you don't want small PRs and wish to bundle it with other doc updates let me know, otherwise I'll submit a PR to fix.

**Comment by adamjstewart** [comment]
Good catch, yes please submit a PR to fix these! We love small PRs, if you want to submit a PR that does nothing other than fix all poorly formatted links you find in the docs that would be great.
