### ISSUE TITLE
"self.run_tests" attribute masked by the object wrapper

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#34518]
### Steps to reproduce

Originally reported by @rbberger in https://spackpm.slack.com/archives/C5VL7V81G/p1669578286178559 

Classes that try to use `self.run_tests` to set any custom attribute and are not using builders will see this attribute set to `False` due to the object wrapper.

### Error message

No error message, just unexpected behavior.

### Information on your system

* **Spack:** 0.20.0.dev0 (e030833129337f080c19e953af73624ddd2a16c5)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by tvandera** [comment]
I was trying to reproduce this problem on my macbook, and for some reason it seems to work fine on macOS. Shall I try to make a reproducible example?

**Comment by tvandera** [comment]
This simple example _works_ on macOS and _fails_ on Linux:

```
class RunTestsTest(Package):
    """Test Package"""

    homepage = "http://example.com"
    url      = "https://downloads.sourceforge.net/project/bowtie-bio/bowtie/1.2.1.1/bowtie-1.2.1.1-src.zip"
    version('1.2.1.1', 'ec06265730c5f587cd58bcfef6697ddf')

    def install(self, spec, prefix):
        print("run_tests = ", self.run_tests)
        assert False
```

On Linux:
```
$ spack -vd install --test=root run-tests-test 2>&1 | grep -A1 run_test
run_tests =  False
==> [2022-12-14-15:11:47.854487] Error: AssertionError:
--
          9        print("run_tests = ", self.run_tests)
  >>     10        assert False
(base) [/scratch/vanderaa]
 $ spack-python --version
Python 3.10.6
$ spack --version
0.20.0.dev0 (eec09f791d320c6ba73be0a71a8f0e0f4355a31c)
```

On macOS:

```
 $ spack -vd install --test=root run-tests-test 2>&1 | grep -A1 run_tests
run_tests =  True
==> [2022-12-14-14:37:46.526235] Error: AssertionError:
--
          9        print("run_tests = ", self.run_tests)
  >>     10        assert False
 $ spack-python --version
Python 3.10.8
$ spack --version
0.20.0.dev0 (9fdb36585f083133232686015903c022ea653980)
```

**Comment by alalazo** [comment]
The issue is due to this line:

https://github.com/spack/spack/blob/55356e9edb374bc2e547ed1706dace6c34042dd9/lib/spack/spack/installer.py#L1276

which monkey patches an object that was used, before monkey patching, to create and _cache_ a builder. The wrapping is done here:

https://github.com/spack/spack/blob/55356e9edb374bc2e547ed1706dace6c34042dd9/lib/spack/spack/builder.py#L130

**Comment by alalazo** [comment]
On the difference between macOS and linux, those are likely due to the different strategies used to create the separate process to install a spec. On macOS we use `spawn` which doesn't create an entire in memory copy of the current process, on linux we use `fork`.
