### ISSUE TITLE
Change to compilers/msvc.py breaks detection of other compilers

### ISSUE THREAD

**Issue by G-Ragghianti** [LLNL/spack#34559]
### Steps to reproduce

```console
$ spack install intel-oneapi-compilers
$ spack load intel-oneapi-compilers
$ spack compiler find
==> Error: expected str, bytes or os.PathLike object, not NoneType
```

### Error message

```console
==> Error: expected str, bytes or os.PathLike object, not NoneType
```

This is caused by a recent change to msvc.py here: https://github.com/spack/spack/commit/0e69710f417dce418ca1e3b54ff448493b102c06

The removal of ".exe" from the compiler filename somehow causes a fatal error at [line 92 of msvc.py](https://github.com/spack/spack/blob/0e69710f417dce418ca1e3b54ff448493b102c06/lib/spack/spack/compilers/msvc.py#L92):

```console
Traceback (most recent call last):
  File "/spack/bin/spack", line 54, in <module>
    sys.exit(main())
  File "/spack/lib/spack/spack_installable/main.py", line 36, in main
    sys.exit(spack.main.main(argv))
  File "/spack/lib/spack/spack/main.py", line 1000, in main
    return _main(argv)
  File "/spack/lib/spack/spack/main.py", line 955, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/spack/lib/spack/spack/main.py", line 983, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/spack/lib/spack/spack/main.py", line 632, in _invoke_command
    return_val = command(parser, args)
  File "/spack/lib/spack/spack/cmd/compiler.py", line 203, in compiler
    action[args.compiler_command](args)
  File "/spack/lib/spack/spack/cmd/compiler.py", line 92, in compiler_find
    new_compilers = spack.compilers.find_new_compilers(paths, scope=None)
  File "/spack/lib/spack/spack/compilers/__init__.py", line 276, in find_new_compilers
    compilers = find_compilers(path_hints)
  File "/spack/lib/spack/spack/compilers/__init__.py", line 262, in find_compilers
    return make_compiler_list(map(remove_errors, filter(valid_version, detected_versions)))
  File "/spack/lib/spack/spack/compilers/__init__.py", line 762, in make_compiler_list
    compilers.extend(make_compilers(compiler_id, selected))
  File "/spack/lib/spack/spack/compilers/__init__.py", line 728, in _default_make_compilers
    compiler = compiler_cls(spec, operating_system, str(target.family), paths)
  File "/spack/lib/spack/spack/compilers/msvc.py", line 92, in __init__
    self.setvarsfile = os.path.abspath(os.path.join(self.cc, "../../../../../../.."))
  File "/usr/lib64/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

```

### Information on your system

* **Spack:** 0.20.0.dev0 (08e007e9a6f7cb7822edcb25c0e84bc598f72b0c)
* **Python:** 3.6.8
* **Platform:** linux-rocky8-broadwell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by G-Ragghianti** [comment]
I have prepared a Dockerfile to easily reproduce this:

```
FROM rockylinux:8
RUN dnf -y install python3 gcc gcc-gfortran gcc-c++ git make
RUN git clone https://github.com/spack/spack && \
    spack install intel-oneapi-compilers && \
    spack load intel-oneapi-compilers && \
    spack --debug compiler find
```

Or from the spack image:

```
FROM spack/ubuntu-focal
RUN spack install intel-oneapi-compilers
RUN spack load intel-oneapi-compilers && spack compiler find
```

**Comment by johnwparent** [comment]
Thanks for bringing this to my attention (and tagging me, very helpful). ~~I'll push a fix shortly. It's a combination of lack of error handling and an unexpected side effect of removing the `.exe` extension from the compiler name.~~
This issue is more complex than it initially seemed and will need further investigation, but I am actively investigating this.

**Comment by johnwparent** [comment]
I'm also quite curious as to why Spack thinks its finding MSVC on a rocky machine.

**Comment by G-Ragghianti** [comment]
Cool.  Yes, it was not immediately obvious to me why this code was even being called and why a small change the expected command name made the difference. Good luck!

**Comment by G-Ragghianti** [comment]
My workaround in our CI was to delete msvc.py ;-)

**Comment by physkets** [comment]
I don't have the MSVC compiler, and I still have the same issue:

```
$ spack load intel-oneapi-compilers@2022.2.1
$ spack compiler find 
==> Error: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by johnwparent** [comment]
Documenting here for future reference: `MSVC` utilizes the `oneAPI` fortran compilers from Spack as they do not vendor some of their own. When detecting compilers, `ifx` is discovered during the search, and when assigning the compiler to their classes, `MSVC` is evaluated prior to `oneAPI` and because `MSVC` understands `ifx` as its own compiler, it returns that that is the appropriate class. From there instantiation of `MSVC` obviously fails on non Windows systems.

Prior to #33385 this was a non issue as the compiler names for `MSVC` were postfixed with the executable extension, but this was changed in #33385 to allow for different extensions, resulting in the above failures.

**Comment by scheibelp** [comment]
Thanks @G-Ragghianti for the detailed error report! We have merged a fix that should address this. If you or @physkets see this on the latest develop, please let us know.

**Comment by G-Ragghianti** [comment]
Yes, I've tested it an can verify that is resolves the issue for me in the two docker container tests.  Thanks to you both.

**Comment by physkets** [comment]
It now works on my machine as well. Thank you!
