### ISSUE TITLE
Installation issue: esmf

### ISSUE THREAD

**Issue by AlexanderRichert-NOAA** [LLNL/spack#34720]
### Steps to reproduce the issue

ESMF fails to compile on NOAA WCOSS2/Acorn systems with Cray PE+Intel compilers+Cray MPICH. Builds successfully if ESMF_OS=Linux and ESMF_COMM=mpich3, but esmf/package.py sets those to Unicos and mpi, respectively.

```console
$ spack spec -l esmf
Input spec
--------------------------------
esmf

Concretized
--------------------------------
6rxazwx  esmf@8.3.0b09%intel@19.1.3.304~debug~external-lapack+mpi+netcdf~parallelio+pio~pnetcdf~shared~xerces build_system=makefile arch=linux-sles15-zen2
zhz3fn4      ^cray-mpich@8.1.9%intel@19.1.3.304~wrappers build_system=generic arch=linux-sles15-zen2
7vjuutq      ^libxml2@2.10.3%intel@19.1.3.304~python build_system=autotools arch=linux-sles15-zen2
inla2gw          ^libiconv@1.16%intel@19.1.3.304 build_system=autotools libs=shared,static arch=linux-sles15-zen2
eyz7fdy          ^pkg-config@0.29.2%intel@19.1.3.304+internal_glib build_system=autotools arch=linux-sles15-zen2
ilrrzhx          ^xz@5.2.6%intel@19.1.3.304~pic build_system=autotools libs=shared,static arch=linux-sles15-zen2
e65xq45      ^netcdf-c@4.7.4%intel@19.1.3.304~dap~fsync~hdf4~jna+mpi+optimize~parallel-netcdf+pic~shared build_system=autotools arch=linux-sles15-zen2
xc2opw5          ^hdf5@1.10.6%intel@19.1.3.304~cxx+fortran+hl~ipo~java+mpi~shared~szip+threadsafe+tools api=default build_system=cmake build_type=RelWithDebInfo arch=linux-sles15-zen2
utbfs5w              ^cmake@3.20.2%intel@19.1.3.304~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-sles15-zen2
sj5fkki          ^m4@1.4.18%intel@19.1.3.304+sigsegv build_system=autotools patches=3877ab5,fc9b616 arch=linux-sles15-zen2
cry7dbu      ^netcdf-fortran@4.5.4%intel@19.1.3.304~doc+pic~shared build_system=autotools arch=linux-sles15-zen2
ij722et      ^zlib@1.2.11%intel@19.1.3.304+optimize+pic~shared build_system=makefile arch=linux-sles15-zen2
...
```

@climbfuji @jedwards4b

### Error message

Here is a sampling of the error messages (other undefined references include mpi_send_, mpi_wait_, etc.):
<details><summary>Error message</summary><pre>
  >> 13388    /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /path/to/cache/build_stage/spack-stage-esmf-8.3.0b09-jmblchtb6cpbt4ot6f22x45qwyrju334/spack-src/src/Infrastr
              ucture/IO/PIO/piodarray.F90.in:162: undefined reference to `mpi_bcast_'
  >> 13389    /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /path/to/cache/build_stage/spack-stage-esmf-8.3.0b09-jmblchtb6cpbt4ot6f22x45qwyrju334/spack-src/src/Infrastr
              ucture/IO/PIO/piodarray.F90.in:163: undefined reference to `mpi_bcast_'
  >> 13390    /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /path/to/cache/build_stage/spack-stage-esmf-8.3.0b09-jmblchtb6cpbt4ot6f22x45qwyrju334/spack-src/src/Infrastr
              ucture/IO/PIO/piodarray.F90.in:164: undefined reference to `mpi_bcast_'
  >> 13391    /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /path/to/cache/build_stage/spack-stage-esmf-8.3.0b09-jmblchtb6cpbt4ot6f22x45qwyrju334/spack-src/src/Infrastr
              ucture/IO/PIO/piodarray.F90.in:165: undefined reference to `mpi_bcast_'
</pre></details>

### Information on your system

Lmod modules in ESMF build env:
1) craype-x86-rome (H)   2) envvar/1.0   3) PrgEnv-intel/8.3.3   4) intel/19.1.3.304   5) craype/2.7.13   6) libfabric/1.11.0.0. (H)   7) craype-network-ofi (H)   8) cray-mpich/8.1.9

spack debug report:
* **Spack:** 0.20.0.dev0 (3a152138df8f6db58019b1b8d19b75a0bbbd0c23)
* **Python:** 3.6.15
* **Platform:** linux-sles15-zen2
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/10318160/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/10318162/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA These cray systems! For Gaea and Narwhal, it's the other way round. Cray PE+Intel compilers+Cray MPICH, builds with ESMF_OS=Unicos and ESMF_COMM=MPI (or whatever the correct setting for the latter is), but not with ESMF_OS=Linux. We added a workaround to the ESMF package in our fork so that it would always use ESMF_OS=Unicos when cray_mpich or cray_mvapich2 are used (see https://github.com/NOAA-EMC/spack/blob/3a152138df8f6db58019b1b8d19b75a0bbbd0c23/var/spack/repos/builtin/packages/esmf/package.py#L250).

I think what we really need to do is to default to Linux and MPICH3, and explicitly set a variant for older Cray systems that need Unicos?

**Comment by jedwards4b** [comment]
The current spack master version of the esmf package always sets ESMF_OS=Unicos if cray-mpich is the mpi library.   I spoke to the esmf developers about adding a Linux configuration for cray-mpich but they are reluctant to do that.

**Comment by climbfuji** [comment]
> The current spack master version of the esmf package always sets ESMF_OS=Unicos if cray-mpich is the mpi library. I spoke to the esmf developers about adding a Linux configuration for cray-mpich but they are reluctant to do that.

Ok, would it be ok for you if we did something like I suggested above, or maybe the opposite if ESMF developers prefer Unicos to be the default? That is, provide a variant that overwrites the auto-detected Unicos setting in the spack package with Linux?

**Comment by jedwards4b** [comment]
I'm not sure I understand - currently if you try to use cray-mpich with ESMF_OS=Linux you get an error because
libmpi++ is expected but not provided.

**Comment by AlexanderRichert-NOAA** [comment]
@climbfuji Indeed! I don't know enough about the Cray system and its versions to know whether this is something that can be distinguished by version or some other feature... I'm looking at the cray-mpich lmod module itself to see if there's any indication. There's some documentation that alludes to differences between this and other Cray systems:
```
  Cray MPICH 8.1.12 is based upon ANL MPICH 3.4a2 with support for libfabric
  and is optimized for the Cray Programming Environment.
    
  Major Differences Cray MPICH 8.1.12 from the XC Cray MPICH include:
```
but I don't know what a reliable programmatic approach would be.

That said, what you described makes sense and would suit me fine. Instead or in addition, what about adding variants allowing the user to override ESMF_OS and ESMF_COMM?

@jedwards4b For me, on Acorn, the winning combination is Linux+mpich3.

**Comment by climbfuji** [comment]
Yes, that's what I was thinking. We can leave the default as it is now, namely Unicos and MPI. For the newer Cray systems (that, as a side note, have many other "features" like being able to use the MPI compiler wrappers instead of the Cray compiler wrappers) we could provide a variant or two variants to overwrite the auto-detected values. These could be of kind `esmf_os={auto,...}` and `esmf_comm={auto,...}` where `auto` means to use whatever the package determined.

**Comment by AlexanderRichert-NOAA** [comment]
Sounds reasonable. Out of curiosity, what the cray-mpich version on those other systems you mentioned?

**Comment by climbfuji** [comment]
There is a loooong slack thread between myself and a few spack developers, it all starts here: https://spackpm.slack.com/archives/C5W7NKZJT/p1671108094900259 - has to do with the version of `craype`. Spack detects `craype/21.10` and later as Linux systems, and earlier versions as `Cray` systems w.r.t. using the Cray compiler wrappers or not. ESMF does its own thing, of course, but I think the underlying problem is the same.

**Comment by jedwards4b** [comment]
My system has cray-mpich/8.1.21 and I can confirm that ESMF_OS=LINUX and ESMF_COMM=mpich3 works for intel,
but I think that if you use the cce compiler you still need ESMF_OS=Unicos ESMF_COMM=mpi.
