### ISSUE TITLE
Installation issue: magma

### ISSUE THREAD

**Issue by yonatanwesen** [LLNL/spack#34771]
### Steps to reproduce the issue

```console
$ spack spec magma
Input spec
--------------------------------
magma

Concretized
--------------------------------
magma@2.7.0%gcc@7.5.0+cuda+fortran~ipo~rocm+shared build_system=cmake build_type=RelWithDebInfo cuda_arch=none arch=linux-ubuntu18.04-skylake
    ^cmake@3.25.1%gcc@7.5.0~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-ubuntu18.04-skylake
        ^ncurses@6.3%gcc@7.5.0~symlinks+termlib abi=none build_system=autotools arch=linux-ubuntu18.04-skylake
            ^pkgconf@1.8.0%gcc@7.5.0 build_system=autotools arch=linux-ubuntu18.04-skylake
        ^openssl@1.1.1s%gcc@7.5.0~docs~shared build_system=generic certs=mozilla arch=linux-ubuntu18.04-skylake
            ^ca-certificates-mozilla@2022-10-11%gcc@7.5.0 build_system=generic arch=linux-ubuntu18.04-skylake
            ^zlib@1.2.13%gcc@7.5.0+optimize+pic+shared build_system=makefile arch=linux-ubuntu18.04-skylake
    ^cuda@11.8.0%gcc@7.5.0~allow-unsupported-compilers~dev build_system=generic arch=linux-ubuntu18.04-skylake
        ^libxml2@2.10.3%gcc@7.5.0~python build_system=autotools arch=linux-ubuntu18.04-skylake
            ^libiconv@1.16%gcc@7.5.0 build_system=autotools libs=shared,static arch=linux-ubuntu18.04-skylake
            ^xz@5.2.7%gcc@7.5.0~pic build_system=autotools libs=shared,static arch=linux-ubuntu18.04-skylake
    ^openblas@0.3.21%gcc@7.5.0~bignuma~consistent_fpcsr+fortran~ilp64+locking+pic+shared build_system=makefile patches=a4c642f,c20f518,d3d9b15 symbol_suffix=none threads=none arch=linux-ubuntu18.04-skylake
        ^perl@5.36.0%gcc@7.5.0+cpanm+shared+threads build_system=generic arch=linux-ubuntu18.04-skylake
            ^berkeley-db@18.1.40%gcc@7.5.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu18.04-skylake
            ^bzip2@1.0.8%gcc@7.5.0~debug~pic+shared build_system=generic arch=linux-ubuntu18.04-skylake
                ^diffutils@3.8%gcc@7.5.0 build_system=autotools arch=linux-ubuntu18.04-skylake
            ^gdbm@1.23%gcc@7.5.0 build_system=autotools arch=linux-ubuntu18.04-skylake
                ^readline@8.2%gcc@7.5.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu18.04-skylake

$ spack install magma

...
```
when I run the second command(i.e   $ spack install magma ), I get the error message below. I have set the cuda_arch in package.py to be 75 to match the gpu I have. @G-Ragghianti @luszczek @stomov

### Error message

<details><summary>Error message</summary><pre>
CMake Error at CMakeLists.txt:277 (message):
     47      GPU_TARGET must contain one or more of Fermi, Kepler, Maxwell, Pascal,
     48      Volta, Turing, Ampere, or valid sm_[0-9][0-9]
     49    
     50    
     51    -- Configuring incomplete, errors occurred!

</pre></details>

### Information on your system

* **Spack:** 0.20.0.dev0 (9cbbe64cf79fcf53f6897effeb5dd77757e5b28a)
* **Python:** 3.7.3
* **Platform:** linux-ubuntu18.04-skylake
* **Concretizer:** clingo

### Additional information

[spack-build-out.txt](https://github.com/spack/spack/files/10333770/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/10333771/spack-build-env.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by G-Ragghianti** [comment]
Your concretized spec has "cuda_arch=none", so you have not actually set it successfully.
