### ISSUE TITLE
All builds failing "no module named macholib"

### ISSUE THREAD

**Issue by vsoch** [LLNL/spack#34818]
Tonight all our flux builds failed with 
![image](https://user-images.githubusercontent.com/814322/210706233-fc07d587-04d1-4db3-9e94-e20607c3e6df.png)

see: 

https://github.com/flux-framework/spack/actions/runs/3843811628/jobs/6546391983

Thanks!

**Comment by vsoch** [comment]
nacho nacho maaaan I want to  be... a nacho man...

oh wait I mean macho. I definitely want to import macho!

**Comment by adamjstewart** [comment]
Can you try:
```console
$ rm -rf /opt/spack/lib/spack/external/macholib
```
@alalazo recently moved some of our external vendored deps around, could be related. Also, what version of Spack are you on?

**Comment by vsoch** [comment]
It's always the most latest in develop! I'll see if the run fails tonight and try this trick.

**Comment by adamjstewart** [comment]
`spack clean -p` may also work. I suspect it's finding pyc files from the old location where macholib used to be. Those were left lying around in my repo.

**Comment by vsoch** [comment]
Same error - I'm going to try nuking the whole install and seeing if that works.

**Comment by vsoch** [comment]
Ok cleared everything - same error https://github.com/flux-framework/spack/actions/runs/3852666818/jobs/6564991105#step:18:555 so it isn’t something being cached.

**Comment by alalazo** [comment]
I am on:

* **Spack:** 0.20.0.dev0 (6fdb5dfa0a300f352c5eac51884e36083ab00393)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

and I can import `spack.relocate`:

```console
$ spack python
Spack version 0.20.0.dev0
Python 3.8.10, Linux x86_64
>>> import spack.relocate
>>> 
```

Also, pipelines for commits after the vendoring rework are building succesfully, for instance:
- https://gitlab.spack.io/spack/spack/-/pipelines/249315 

and they import that module. Do you clone Spack every time?

**Comment by alalazo** [comment]
It seems you are not using `spack` but a tool named `pakages`? Looking at the stacktrace, I guess you're not using the correct entrypoint (or if you do some path computation needs adjustments). The lines that `pakages` is possibly missing are:

https://github.com/spack/spack/blob/8780c718ea35947d25ec08e0a6d6be36934baee1/lib/spack/spack_installable/main.py#L16-L23

**Comment by vsoch** [comment]
Thanks @alalazo I think that's probably it! I put in some fixes to pakages and I'll report back after the run tonight.

**Comment by vsoch** [comment]
For context - pakages is a thin wrapper to spack, and handles bundling up spack packages into OCI artifacts to push to a registry and pull down again to a build cache to install from. It handles other kinds of builds but that's the builder we use for the spack-updater actions. I would have contributed oras natively in spack so we could store spack archives in Github packages but it was too hairbally with the current aws build cache.

**Comment by vsoch** [comment]
Just to keep you in the loop! It failed again with the changes https://github.com/flux-framework/spack/actions/runs/3860416113/jobs/6580731454#step:18:555 so tomorrow I’m going to do a manual walk through and try to see what is going on, will update the issue of/when I have learned something. Happy Friday!

**Comment by vsoch** [comment]
okay I can't even get beyond:

```
repos = spack.config.get('repos')
```
because

```
$ pakages install --builder spack . flux-sched
Traceback (most recent call last):
  File "/home/vanessa/Desktop/Code/pakages/env/bin/pakages", line 33, in <module>
    sys.exit(load_entry_point('pakages', 'console_scripts', 'pakages')())
  File "/home/vanessa/Desktop/Code/pakages/pakages/cli/__init__.py", line 243, in run_main
    main(args=args, parser=parser, extra=extra, subparser=helper)
  File "/home/vanessa/Desktop/Code/pakages/pakages/cli/install.py", line 13, in main
    cli.install(args.packages, registry=args.registry, tag=args.tag, **kwargs)
  File "/home/vanessa/Desktop/Code/pakages/pakages/builders/spack/client.py", line 134, in install
    packages = self.parse_packages(packages)
  File "/home/vanessa/Desktop/Code/pakages/pakages/builders/spack/client.py", line 96, in parse_packages
    packages = self.parse_package_request(packages)
  File "/home/vanessa/Desktop/Code/pakages/pakages/builders/spack/client.py", line 58, in parse_package_request
    self.add_repository(repo)
  File "/home/vanessa/Desktop/Code/pakages/pakages/builders/spack/client.py", line 112, in add_repository
    repos = spack.config.get("repos")
  File "/home/vanessa/Desktop/Code/spack/lib/spack/spack/config.py", line 916, in get
    return config.get(path, default, scope)
  File "/home/vanessa/Desktop/Code/spack/lib/spack/llnl/util/lang.py", line 826, in __getattr__
    return getattr(self.instance, name)
  File "/home/vanessa/Desktop/Code/spack/lib/spack/llnl/util/lang.py", line 825, in __getattr__
    raise AttributeError()
AttributeError
```
Can you please show me the proper way to use spack in another library? Everything I try leads to a new error.

**Comment by vsoch** [comment]
I think I'm just going to gut out using spack internally as a python module - it's not really meant for (or reliable for that) but maybe at some point in the far future!

**Comment by vsoch** [comment]
okay this appears to be fixed! https://github.com/flux-framework/spack/actions/runs/3863975693/jobs/6586492013

For future readers, the fix was to refactor to not import spack modules and call spack via a subprocess command.

https://github.com/syspack/pakages/commit/51152fbdd800cdc84277dc82a011ce1d7e7c58bf

Thanks @alalazo @adamjstewart for the help.
