### ISSUE TITLE
`spack activate py-virtualenv` fails to activate `py-setuptools`

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#3484]
I've starting installing and activating py-virtualenv as part of a standard shared toolset.  Here's the bit of the script that drives the installation.

```
spack install python            # default from packages.yaml
spack install py-virtualenv
spack activate py-virtualenv

spack install python@3.6.0
spack install py-virtualenv ^python@3.6.0
spack activate py-virtualenv ^python@3.6.0
```

I was suprised to discover that activating `py-virtualenv` did not activate the apparently-required `py-setuptools` (happens with python2 and python3).  

E.g.  Here's the python3 version: 
- adding the installed python directory to PATH;
- python3 works; and
- virtualenv is on PATH; but
- it blows up; until
- I activate `py-setuptools ^python@3.6.0`.

```
hartzelg@rpbuchop002:spack (llnl/develop)$ export PATH=`pwd`/opt/spack/linux-centos7-x86_64/gcc-5.4.0/python-3.6.0-m5uhlrl7k4ac7gi2agj7xiw6wmquxpq3/bin:$PATH
hartzelg@rpbuchop002:spack (llnl/develop)$ which python
/usr/bin/python
hartzelg@rpbuchop002:spack (llnl/develop)$ which python3
/isilon/Analysis/scratch/hartzelg/spack-cime-rpbuchop002-working-dir/workspace/daily-build/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/python-3.6.0-m5uhlrl7k4ac7gi2agj7xiw6wmquxpq3/bin/python3
hartzelg@rpbuchop002:spack (llnl/develop)$ python3
Python 3.6.0 (default, Mar 17 2017, 11:35:47)
[GCC 5.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>
hartzelg@rpbuchop002:spack (llnl/develop)$ which virtualenv
/isilon/Analysis/scratch/hartzelg/spack-cime-rpbuchop002-working-dir/workspace/daily-build/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/python-3.6.0-m5uhlrl7k4ac7gi2agj7xiw6wmquxpq3/bin/virtualenv
hartzelg@rpbuchop002:spack (llnl/develop)$ virtualenv
Traceback (most recent call last):
  File "/isilon/Analysis/scratch/hartzelg/spack-cime-rpbuchop002-working-dir/workspace/daily-build/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/python-3.6.0-m5uhlrl7k4ac7gi2agj7xiw6wmquxpq3/bin/virtualenv", line 7, in <module>
    from pkg_resources import load_entry_point
ModuleNotFoundError: No module named 'pkg_resources'
hartzelg@rpbuchop002:spack (llnl/develop)$ spack activate py-setuptools ^python@3.6.0
==> Activated extension py-appdirs@1.4.0%gcc@5.4.0 arch=linux-centos7-x86_64 /eajpjfn for python@3.6.0~tk~ucs4%gcc@5.4.0
==> Activated extension py-pyparsing@2.1.10%gcc@5.4.0 arch=linux-centos7-x86_64 /jzlgzex for python@3.6.0~tk~ucs4%gcc@5.4.0
==> Activated extension py-six@1.10.0%gcc@5.4.0 arch=linux-centos7-x86_64 /em5tra4 for python@3.6.0~tk~ucs4%gcc@5.4.0
==> Activated extension py-packaging@16.8%gcc@5.4.0 arch=linux-centos7-x86_64 /wporjj5 for python@3.6.0~tk~ucs4%gcc@5.4.0
==> Activated extension py-setuptools@34.2.0%gcc@5.4.0 arch=linux-centos7-x86_64 /ys7rdd6 for python@3.6.0~tk~ucs4%gcc@5.4.0
hartzelg@rpbuchop002:spack (llnl/develop)$ virtualenv
You must provide a DEST_DIR
Usage: virtualenv [OPTIONS] DEST_DIR

[...]
```

`py-virtualenv` seems to depend on `py-setuptools`....

```python
class PyVirtualenv(PythonPackage):
  [...]
    depends_on('py-setuptools') # not just build-time, requires pkg_resources
```

I have a feeling that I've been around this before.

Is this a bug?  Am I missing something obvious (share a previous Issue and shame my search skills... :1st_place_medal: )?

Thanks!

**Comment by adamjstewart** [comment]
Try:
```python
depends_on('py-setuptools', type=('build', 'run'))
```
If that works I can submit a PR. People keep forgetting that the default deptype is `('build', 'link')`, not `('build', 'run')`. I'm pretty sure we only activate run deptypes.

**Comment by adamjstewart** [comment]
This change solved the problem for me. Note that I had to uninstall and reinstall `py-virtualenv` so that the dependency was correct in the database. `spack reindex` may also have worked. I'll submit a PR shortly.

**Comment by hartzell** [comment]
Do you have enough evidence that I can skip testing your change or should I still take it for a spin?

You get bonus points though, I'm still unhappy with the gyrations I did for making the gtkplus build work again, I'll go check if the thing that's tripping it up is the missing 'run' bit...).

**Comment by adamjstewart** [comment]
Yeah, I'm satisfied that my fix works. But you're welcome to test it as well.

There actually were several other packages missing the `'run'` deptype. See #3486.

**Comment by hartzell** [comment]
@adamjstewart -- **Thank you for fixing/PR-ing it.**

I'll wait for it to come around after the merge and see if it fixes the build.

**Comment by hartzell** [comment]
Closing the loop, @adamjstewart's PR fixed my problem.  **THANKS!**
