### ISSUE TITLE
spec['mpi'].mpicc doesn't work for MPI in intel-parallel-studio

### ISSUE THREAD

**Issue by weijianwen** [LLNL/spack#3487]
I failed to build mdtest with Intel Parallel Studio due to "'Spec' object has no attribute 'mpicc'" issue.  mdtest is an MPI program to test metadata performance on filesystem. 

The command to reproduce this issue and the error message is listed below.

```
$ spack install mdtest %intel ^intel-parallel-studio+mpi 
==> Installing mdtest
==> intel-parallel-studio is externally installed in /lustre/spack/tools/linux-centos7-x86_64/gcc-4.8.5/intel-parallel-studio-cluster.2017.1-4uy7iwkuftkrg5wx2sg5zi6r5355rqbe
==> Using cached archive: /tmp/rpm/spack_source_cache/mdtest/mdtest-1.9.3.tar.gz
==> Warning: Fetching from mirror without a checksum!
  This package is normally checked out from a version control system, but it has been archived on a spack mirror.
This means we cannot know a checksum for the tarball in advance. Be sure that your connection to this mirror is secure!.
==> Already staged mdtest-1.9.3-zwdgfm4vkhmcmqxhla4xhagbywnz7eqm in /home/rpm/spack/var/spack/stage/mdtest-1.9.3-zwdgfm4vkhmcmqxhla4xhagbywnz7eqm
==> No patches needed for mdtest
==> Building mdtest [Package]
==> Executing phase : 'install'
==> Error: AttributeError: 'Spec' object has no attribute 'mpicc'
/home/rpm/spack/var/spack/repos/builtin/packages/mdtest/package.py:40, in install:
     39       def install(self, spec, prefix):
  >> 40           filter_file('$(CC.$(OS))', spec['mpi'].mpicc, 'Makefile', string=True)
     41           make('mdtest')
     42           mkdirp(prefix.bin)
     43           install('mdtest', prefix.bin)

See build log for details:
  /tmp/rpm/spack_stage/spack-stage/spack-stage-XbDO_t/mdtest/spack-build.out
```

mdtest's build process is organized in Makefiile shipped with it. What Spack does is to replace the "$(CC.$(OS))'" string with the selected MPI's mpicc specified in `spec['mpi'].mpicc`,  then run make. The embarrassing thing is that I tested it under `%gcc ^onmpi` only when I submit simul package, leaving `%intel ^intel-parallel-studio` untested. 

According to Spack's doc http://spack.readthedocs.io/en/latest/packaging_guide.html?highlight=mpic , `spec['mpi'].mpicc` should get the MPICC compiler for `intel-parallel-studio`. Please correct me if I use `spec['mpi']` in the wrong way.

Link to mdtest package https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/mdtest/package.py .

**Comment by adamjstewart** [comment]
@alalazo

**Comment by alalazo** [comment]
For other MPI packages this is done like:
```python
    def setup_dependent_package(self, module, dependent_spec):
        self.spec.mpicc = join_path(self.prefix.bin, 'mpicc')
        self.spec.mpicxx = join_path(self.prefix.bin, 'mpic++')
        self.spec.mpifc = join_path(self.prefix.bin, 'mpif90')
        self.spec.mpif77 = join_path(self.prefix.bin, 'mpif77')
```
which seems to be missing from `intel-parallel-studio`.

**Comment by tgamblin** [comment]
The `intel-parallel-studio` package needs to define `mpicc` and related attributes in a `setup-dependent-environment` method.  Parallel studio is based on MPICH, so you can probably take the `setup_dependent_environment` from `mpich` to make this work.  You probably want to set the attributes and environment variables conditionally, depending on whether parallel studio is built with `+mpi`.

This brings up two things we could think about.  

First, with @alalazo's spec interface and the mpicc concention, virtual dependencies are starting to have contracts associated with them in spack.  e.g., "if I provide mpi, I will have an mpicc attribute".  Seems like something that could be declared and checked statically.  

Second, we'd need a place to put that contract.  Having a package placeholder for a vdep is something we've talked about but haven't actually merged.  A placeholder package for `mpi`, `blas`, etc. seem like good places to put sanity checks (and/or something more declarative), to enforce contracts like this one As new MPI/whatever implementations as they are added.

Thoughts?

**Comment by alalazo** [comment]
> Having a package placeholder for a vdep is something we've talked about but haven't actually merged

Now that directives can be inherited in a hierarchy, what do you think of having a `providers` sub-folder in `spack` where to collect virtual dependencies and common implementations in some way? If we come up with a good design, we can probably use the base classes there as mixins. Something like:
```python
class IntelParallelStudio(MpichBasedMpiProvider, LapackProvider):
    ...
```

**Comment by weijianwen** [comment]
@alalazo Regarding MPI wappers, things got a bit compited for `intel-parallel-studio` since it has two suites for invoking GNU and Intel compilers backend seprately. To take `MPICC` for example,

* `mpicc` invokes `gcc`
* `mpiicc` invokes `icc`

I think @adamjstewart mentioned similar simulaition when dealing with `intel` and `intel-parallel-studio`. His workound is to install two (almost) duplicate packages `intel-parallel-studio %gcc` and `intel-parallel-studio %icc` then `mpicc` will work for both compiler backends.

**Comment by tgamblin** [comment]
In spack, that's the best way to handle this, I think.  We don't assume that a package can dynamically swap compiler backends (because most don't), so we install two versions in cases like this.  

Is the wrapper in Intel MPI significantly different from the wrapper in mpich?  The important part for spack builds is that the wrapper accepts MPICH_CC, MPICH_CXX, etc. variables.  If it doesn't, then setup_dependent_package will need to figure out how best to get the MPI wrappers to use the spack wrappers.

**Comment by weijianwen** [comment]
`MPICC` environment variable works for MPI in intel-parallel-studio. But for `MPICH_CC`, I am not sure about it.

**Comment by tgamblin** [comment]
@weijianwen: can you edit the mpich script to see if it is just the same one from mpich?

**Comment by weijianwen** [comment]
@tgamblin Shall I add `setup_dependent_environment` fucntion similiar to `mpich` into `intel-parallel-studio` package? After that I retry buiding of mdtest.

**Comment by tgamblin** [comment]
You likely need both serup_dependent_environment and setup_dependent_package.  But yes!  I would try that.

**Comment by davydden** [comment]
> His workound is to install two (almost) duplicate packages intel-parallel-studio %gcc and intel-parallel-studio %icc then mpicc will work for both compiler backends.

yes, i think this is how it should be done. This is also the same for things like single-threaded Atlas and multithreaded Atlas -- they can probably be stored within a single prefix, but we don't want to do it because we want a single package be specific, in that case have `+openmp` flag and thereby return correct libraries. 

In your case you would have two installations of intel-mpi, the one with intel will return intel MPI wrappers, the one with GCC will return GCC wrappers.

**Comment by davydden** [comment]
@weijianwen i would look at `mpich` and see how everything is done there and what is missing in `intel-parallel-studio` package. Then just copy-paste and add some ifs for intel/gcc compilers.

**Comment by alalazo** [comment]
> Is the wrapper in Intel MPI significantly different from the wrapper in mpich?

If I remember correctly: `mpiicc` always calls `icc` as compiler, while `mpicc` can be driven via `MPICH_CC` and defaults to `gcc` if the environment variable is not set.

**Comment by davydden** [comment]
> If I remember correctly: mpiicc always calls icc as compiler, while mpicc can be driven via MPICH_CC and defaults to gcc if the environment variable is not set.

you are right. 

Actually, there is already a 1.5 month old PR which aims at fixing the issue https://github.com/LLNL/spack/pull/2980

**Comment by davydden** [comment]
see https://github.com/LLNL/spack/pull/2980#issuecomment-276747987

**Comment by weijianwen** [comment]
Thank you, @davydden . I cherry-picked #2980 commits but it doesn't work. That PR needs to fix two things:

1. Missing `setup_dependent_environment` for `MPICC` etc.
2. Incorrect paths for MPI wrappers like `mpicc` for intel-parallel-studio.

I'll this issue and move onto #2980 .
