### ISSUE TITLE
Add possibility to inherit maintainers from base package

### ISSUE THREAD

**Issue by awvwgk** [LLNL/spack#34879]
### Summary

Add a function to `spack.package` to declare maintainers which constructs the `maintainers` attribute of the package.

### Rationale

Adding a Python package with `maintainers = [...]` will overwrite the maintainers declared in `PythonPackage`, to circumvent this the contributor and/or reviewer have to be aware of this issue and change the maintainers declaration to

````python
maintainers = [
    *PythonPackage.maintainers,
    "user1",
    "user2",
]
````

### Description

A solution could be a `maintainer` function to allow declaration of maintainers with

````python
maintainer("user1")
maintainer("user2")
````

The function will construct the `maintainers` attribute by appending the user handles instead of overwriting. Overwriting can still be done by directly writing to ``maintainers``.

### Additional information

See https://github.com/spack/spack/pull/34857#discussion_r1066698621

---

```
❯ spack --version
0.20.0.dev0 (2001be99b36bb18864886c9ae00f41dd55e9c800)
```

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Another option would be to add a new `base_maintainers` variable that is only set in the base class, and `spack maintainers` will concatenate this with `maintainers`. Only downside is that subclasses of subclasses will still have the same problem.

A related issue is that new package PRs don't correctly ping maintainers listed in the base class. Not sure if we can kill two birds with one stone here.

**Comment by alalazo** [comment]
I think we have to deal with both:
1. Overriding the old maintainers list completely
2. Extending it, like proposed here

Can't we use a property for extension? Is that considered too cumbersome?

**Comment by adamjstewart** [comment]
Definitely too cumbersome. I would like it to happen automatically.

**Comment by adamjstewart** [comment]
What if `spack maintainers` ran a while-loop over all superclasses of the package and added all maintainers together? Is that how Python works?

**Comment by alalazo** [comment]
Can you check if #35083 works for you?

**Comment by alalazo** [comment]
> What if spack maintainers ran a while-loop over all superclasses of the package and added all maintainers together? Is that how Python works?

I don't want to add a lot of logic in commands. Imo they should just be simple hooks that trigger some already existing API from the command line.
