### ISSUE TITLE
Installation issue: openspeedshop and openspeedshop-utils seem to be removed from spack???

### ISSUE THREAD

**Issue by jgalarowicz** [LLNL/spack#34884]
### Steps to reproduce the issue

```console
openspeedshop and openspeedshop-utils are not in <spack install>/var/spack/repos/builtin/packages currently.
We did not delete them.  We are trying to find out what happened to our tool.
...
```

### Error message

N/A

### Information on your system

jgalarowicz@fedora:~/jan11_spack/spack/var/spack/repos/builtin/packages$ spack debug report
* **Spack:** 0.20.0.dev0 (b9f48da560374ea9ace74cf1bd630846ca1d00bf)
* **Python:** 3.10.7
* **Platform:** linux-fedora35-icelake
* **Concretizer:** clingo

### Additional information

N/A

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by wdconinc** [comment]
FYI, https://github.com/spack/spack/pull/33898, with suggested actions.

**Comment by alalazo** [comment]
Pinging @adamjstewart for his information on the issue. @jgalarowicz Both `openspeedshop` and `openspeedshop-utils` had no maintainers field, so my guess is that you were not mentioned in that PR because of that.

**Comment by adamjstewart** [comment]
Correct, `openspeedshop` and `openspeedshop-utils` were removed because they require Python 2 which Spack no longer supports. And these packages had no maintainers listed, so no one was notified. Let me know if you have any questions about why Python 2 support was removed or how to restore openspeedshop packages.

**Comment by jgalarowicz** [comment]
@adamjstewart @alalazo @wdconinc Thanks for the comments on the issue.  We are in the process of fixing openspeedshop to support python3, so we could restore and change the requirements for python2 to python3.   How can we restore those packages?   Thanks Jim G.   They were some of the early on packages, probably before maintainers were added to spack and we forgot to add our names to those packages.

**Comment by adamjstewart** [comment]
The easiest way to restore the packages is to checkout Spack v0.19.0 and cp the package.py files somewhere, then checkout develop and cp them back. Then modify the recipes to support Python 3. If there isn't yet a stable release that supports Python 3 you can use the master branch or a Python 3 support branch.

**Comment by wdconinc** [comment]
Or checkout the version from right before the commit that removed them:
```console
git checkout c5883fffd7310f704a8adc2f3666d7539cdfe4e1^ -- var/spack/repos/builtin/packages/openspeedshop/
```
That would likely maintain the git commit history for the files.

**Comment by adamjstewart** [comment]
Yep, this was relatively soon after v0.19.0 and the openspeedshop packages didn't receive very many updates, so should be equivalent.

**Comment by jgalarowicz** [comment]
@adamjstewart @alalazo @wdconinc Thank you!   I will proceed and then make a pull request to get them back in (with a maintainer statement included and python3 instead of python2).

**Comment by jgalarowicz** [comment]
@adamjstewart @alalazo
I keep getting this when I try to check the new packages and updated cbtf* ones.
```
jgalarowicz@fedora:~/put_back_oss/spack$ spack style --tool flake8 
==> Error: maximum recursion depth exceeded while calling a Python object
jgalarowicz@fedora:~/put_back_oss/spack/var/spack/repos/builtin/packages/cbtf$ spack style --tool flake8 package.py 
==> Error: maximum recursion depth exceeded while calling a Python object
```

**Comment by adamjstewart** [comment]
Hmm, maybe some local file has the same name as a builtin import and it's being shadowed? Try running from home directory.

**Comment by jgalarowicz** [comment]
@adamjstewart Thanks!  That was a good clue.   I'm not sure how a path to a different spack repository is getting into my path. When I removed that path, spack style works.   Thanks for your help!

**Comment by alalazo** [comment]
These two packages have been added back at some point:

* **Spack:** 0.23.0.dev0 (ae2f6261689ee1e70b621bf29f2d0f6810b6b309)
* **Python:** 3.11.5
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

```console
$ spack list openspeed
openspeedshop  openspeedshop-utils
==> 2 packages
```
