### ISSUE TITLE
Installation issue: Build container using new version of spack

### ISSUE THREAD

**Issue by aveleda** [LLNL/spack#34904]
### Steps to reproduce the issue

```console
$ singularity build --fakeroot roms.sif roms.def
...
```

### Error message

<details><summary>Error message</summary><pre>
...
+++ command spack --print-shell-vars sh
==> Error: /opt/spack/etc/spack/modules.yaml:3: Additional properties are not allowed ('naming_scheme' was unexpected)
++ stdout='_sp_sys_type='\''linux-rhel9-skylake_avx512'\''
_sp_compatible_sys_types='\''linux-rhel9-skylake_avx512:linux-rhel9-skylake:linux-rhel9-x86_64_v4:linux-rhel9-broadwell:linux-rhel9-haswell:linux-rhel9-ivybridge:linux-rhel9-x86_64_v3:linux-rhel9-sandybridge:linux-rhel9-westmere:linux-rhel9-nehalem:linux-rhel9-core2:linux-rhel9-x86_64_v2:linux-rhel9-nocona:linux-rhel9-x86_64'\'''
++ return
FATAL:   While performing build: while running engine: exit status 1
</pre></details>

### Information on your system

* **Spack:** 0.19.0 (a86911246a8c5571ca210ff25fc990b8eb297a5c)
* **Python:** 3.9.5
* **Platform:** linux-oracle8-skylake_avx512
* **Concretizer:** clingo
[roms.def.txt](https://github.com/spack/spack/files/10404985/roms.def.txt)

### Additional information

This configuration works on spack version 0.18.

[spack-build-env.txt](https://github.com/spack/spack/files/10404900/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/10404901/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
This was deprecated in 0.18 and removed in f11778bb02ae7394cdc9ac24357073d76077a403

```
modules:
  default:
    tcl:
      ...
```

also see https://spack.readthedocs.io/en/latest/module_file_support.html#customize-the-naming-of-modules
