### ISSUE TITLE
Spack mirror mishandles paths

### ISSUE THREAD

**Issue by Paul-Ferrell** [LLNL/spack#34989]
### Steps to reproduce

```
spack mirror create -d /some/absolute/path --all
```
What's happening here is that the Spack mirror command hands the -d/--directory argument off to `spack.util.url.path_to_file_url`, which converts the path into a `file:///some/absolute/path` URI. Then that URI gets passed to `spack.mirror.cache_and_stats`, which uses `os` lib functions to check the existence of that directory and create it if necessary. 

The problem is, `os` filesystem operations don't understand URI's (it interprets it as the relative path `file:/some/absolute/path`). Spack happily creates this directory and puts the mirror there. 

### Error message

None

### Information on your system

* **Spack:** 0.20.0.dev0
* **Python:** 3.6.8
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
Right, I noticed this in #34891, but then reverted `spack mirror create` changes, cause they were breaking. Will push a fix soon.
