### ISSUE TITLE
Installation issue: pFunit / fargparse / gftl / gftl-shared

### ISSUE THREAD

**Issue by ajc445** [LLNL/spack#35055]
### Steps to reproduce the issue

Have mercy on me - this is my first ever github issue and first week using Fortran -  @mathomp4 and @tclune.

Building pfunit in a spack environment, e.g.:
```spack add pfunit
spack install pfunit
spack load pfunit```
then using it within a project using Autotools / Gmake, we find that `PFUNIT-4.6/include/PFUNIT.mk` does not pick up `FARGPARSE_TOP_DIR` which is set to emplty string. In turn, `FARGPARSE.mk` doesn't have `GFTL_SHARED_TOP_DIR := ` set - such that `include ${GFTL_SHARED_TOP_DIR}/include/GFTL_SHARED.mk` is valued `include /include/GFTL_SHARED.mk`, then `GFTL_SHARED.mk` has an empty string for `GFTL_TOP_DIR`leading to the attempted include of `/include/GFTL.mk`. At this stage the dependencies on the libgftl-shared-v2 library seems to get dropped.

Right now I have installed:
 ```
 [acoll@lle-acoll-up linux-rhel9-skylake]$ spack find
-- linux-rhel9-skylake / gcc@11.3.1 -----------------------------
autoconf@2.69                       gmp@6.2.1                                mpich@4.0.2
autoconf-archive@2022.02.11         hdf5@1.12.2                              ncurses@6.3
automake@1.16.5                     hwloc@2.9.0                              openssl@1.1.1s
berkeley-db@18.1.40                 intel-oneapi-compilers@2023.0.0          patchelf@0.16.1
bzip2@1.0.8                         intel-oneapi-compilers-classic@2021.8.0  perl@5.36.0
ca-certificates-mozilla@2022-10-11  libbsd@0.11.5                            pfunit@4.6.1
cmake@3.25.1                        libfabric@1.16.1                         pigz@2.7
diffutils@3.8                       libffi@3.4.2                             pkgconf@1.8.0
environment-modules@5.2.0           libiconv@1.16                            python@3.10.8
expat@2.5.0                         libmd@1.0.4                              readline@8.2
fargparse@1.4.1                     libpciaccess@0.16                        sqlite@3.40.0
findutils@4.9.0                     libsigsegv@2.13                          tar@1.34
gawk@5.1.1                          libtool@2.4.7                            tcl@8.6.12
gawk@5.1.1                          libxcrypt@4.4.33                         texinfo@7.0
gcc@12.2.0                          libxml2@2.10.3                           util-linux-uuid@2.38.1
gdbm@1.23                           m4@1.4.19                                util-macros@1.19.3
gettext@0.21.1                      mpc@1.2.1                                xz@5.2.7
gftl@1.8.1                          mpc@1.2.1                                yaksa@0.2
gftl-shared@1.5.0                   mpfr@4.1.0                               zlib@1.2.13
gmp@6.2.0                           mpfr@4.1.0                               zstd@1.5.2

-- linux-rhel9-skylake / gcc@12.2.0 -----------------------------
libiconv@1.16  libsigsegv@2.13
==> 62 installed packages
```




### Error message

Lots of incomplete paths pointing into /include/ looking for *.mk files when building  the Trivial examples from https://github.com/Goddard-Fortran-Ecosystem/pFUnit_demos

### Information on your system

```[acoll@lle-acoll-up linux-rhel9-skylake]$ spack debug report
* **Spack:** 0.20.0.dev0 (a15b77bdf6745302579044bc92c3d3e196c4645e)
* **Python:** 3.9.14
* **Platform:** linux-rhel9-skylake
* **Concretizer:** clingo
```

### Additional information

For pfunit:
[spack-build-01-cmake-out.txt](https://github.com/spack/spack/files/10470178/spack-build-01-cmake-out.txt)
[spack-build-02-build-out.txt](https://github.com/spack/spack/files/10470179/spack-build-02-build-out.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/10470180/spack-build-out.txt)
[spack-configure-args.txt](https://github.com/spack/spack/files/10470181/spack-configure-args.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/10470183/spack-build-env.txt)
[spack-build-03-install-out.txt](https://github.com/spack/spack/files/10470184/spack-build-03-install-out.txt)

For fargparse:

[spack-build-01-cmake-out.txt](https://github.com/spack/spack/files/10470195/spack-build-01-cmake-out.txt)
[spack-build-02-build-out.txt](https://github.com/spack/spack/files/10470196/spack-build-02-build-out.txt)
[spack-build-03-install-out.txt](https://github.com/spack/spack/files/10470197/spack-build-03-install-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/10470198/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/10470199/spack-build-out.txt)

For gftl-shared:

[spack-build-01-cmake-out.txt](https://github.com/spack/spack/files/10470204/spack-build-01-cmake-out.txt)
[spack-build-02-build-out.txt](https://github.com/spack/spack/files/10470205/spack-build-02-build-out.txt)
[spack-build-03-install-out.txt](https://github.com/spack/spack/files/10470206/spack-build-03-install-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/10470209/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/10470210/spack-build-out.txt)

For gftl:
[spack-build-01-cmake-out.txt](https://github.com/spack/spack/files/10470213/spack-build-01-cmake-out.txt)
[spack-build-02-build-out.txt](https://github.com/spack/spack/files/10470214/spack-build-02-build-out.txt)
[spack-build-03-install-out.txt](https://github.com/spack/spack/files/10470215/spack-build-03-install-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/10470216/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/10470217/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by mathomp4** [comment]
@ajc445 Thanks for the report. The GNU Make interface is not as well tested and it's entirely possible something is broken. We'll take a look...

**Comment by mathomp4** [comment]
@ajc445 Okay. Yeah. The GNU Make support is just broken. Thanks for exposing this to us. The solution most likely a release of *all* the GFE libraries. This might take a couple days to make sure we've fixed GNU Make and not hurt cmake.

**Comment by mathomp4** [comment]
@ajc445 I think that the changes in https://github.com/spack/spack/pull/35119 should fix the GNU Make use.

**Comment by ajc445** [comment]
Thanks. I’ll take a look.

**Comment by aijac0** [comment]
@mathomp4 There appears to be issues with versions of cmake newer than 3.24.3 when installed as a dependency with pFunit i.e. """spack install pfunit ^cmake@3.25.0""". I think it may be advisable to introduce the range on the cmake version for the pFunit installation process to be 3.13.0 - 3.24.3.

**Comment by mathomp4** [comment]
> @mathomp4 There appears to be issues with versions of cmake newer than 3.24.3 when installed as a dependency with pFunit i.e. """spack install pfunit ^cmake@3.25.0""". I think it may be advisable to introduce the range on the cmake version for the pFunit installation process to be 3.13.0 - 3.24.3.

@aijac0 Ahhh. I forgot about that. You found the bug! CMake 3.25.0 had a bug with our code that was fixed in Cmake 3.25.1 and newer. 

I might need to invoke the name of @alalazo and ask "How can I say a *single* version of CMake is not allowed to build this software?" 

ETA: Ah perhaps something like:
```python
    conflicts("^cmake@3.25.0", msg="CMake 3.25.0 has a bug with pFUnit. Please use an older or newer version.")
```

**Comment by mathomp4** [comment]
Also, to that end, @aijac0 Can you try either 3.24.3 or 3.25.1 etc.? If those work, then I can try and figure out how to block a single version of CMake from that package...

**Comment by ajc445** [comment]
3.24.3 works, 3.25.1 does not.

**Comment by mathomp4** [comment]
> 3.24.3 works, 3.25.1 does not.

Really? Huh. I thought the fix got into that version. I'll test myself when I get home.

Now, I *know* 3.25.2 works because I use it on my local laptop. We'll figure this out!

**Comment by aijac0** [comment]
I may have misremembered 3.25.1 not working. I’ll try again tomorrow when
I’m at work.

**Comment by aijac0** [comment]
3.25.1 works! Thanks for fixing the issue

**Comment by mathomp4** [comment]
Thanks for testing!

(NOTE to you, there will be some more updates to these libraries coming soon, bug fixes, etc. But hopefully GNU Make will just keep on working...)
