### ISSUE TITLE
Spack.io is returning a 404

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#35141]
### Steps to reproduce

Browse to `https://spack.io`.

### Error message

<img width="705" alt="Screen Shot 2023-01-24 at 11 24 20 AM" src="https://user-images.githubusercontent.com/312978/214376523-3bc771e7-2729-4533-b1d8-5e6a0417af64.png">

### Information on your system

Mac, running Chrome.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by hartzell** [comment]
Heads up: @tgamblin @adamjstewart @alalazo

**Comment by tgamblin** [comment]
@hartzell do you still see this?  I believe @mvandenburgh fixed it.

**Comment by eugeneswalker** [comment]
Looks good to me

**Comment by hartzell** [comment]
Looks good to me.  Thanks!
