### ISSUE TITLE
ModuleNotFoundError for `pyarrow.parquet` after building `py-pyarrow +parquet`

### ISSUE THREAD

**Issue by thomas-bouvier** [LLNL/spack#35160]
### Steps to reproduce

Hello, I simply ran `spack install py-pyarrow +parquet`. `py-pyarrow@8.0.0%gcc@10.2.1~cuda~orc+parquet build_system=python_pip arch=linux-debian11-broadwell` installed successfully. However, the `parquet` module isn't loading properly when imported from Python.

### Error message

```console
Python 3.10.8 (main, Jan 12 2023, 16:45:18) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pyarrow
>>> import pyarrow.parquet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/view/._chifflot/dyd3mwxjpnsnyhepkwoinysdtdt2hikk/lib/python3.10/site-packages/pyarrow/parquet/__init__.py", line 34, in <module>
    import pyarrow._parquet as _parquet
ModuleNotFoundError: No module named 'pyarrow._parquet'
```

### Information on your system

```console
* **Spack:** 0.20.0.dev0 (051abfb894d41ef488545710a75ea06d8a2013b0)
* **Python:** 3.9.2
* **Platform:** linux-debian11-skylake_avx512
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by matz-e** [comment]
This seems some weird behavior by arrow's `setup.py`. It looks like it should work, but I only got a working version by putting the install options into the environment like this:
```
    def setup_build_environment(self, env):
        args = self.install_options(self.spec, self.prefix)
        for arg in args:
            key = arg[2:]
            if "=" in key:
                key, val = key.split("=", 1)
            else:
                val = "1"
            var = "PYARROW_" + key.replace("-", "_").upper()
            env.set(var, val)
```

(@heerener, FYI)

**Comment by meyersbs** [comment]
I have run into this with packages depending on `py-pyarrow`, notably `py-datasets`.

I haven't found a solution, but a similar issue in conda suggests nuking `__pycache__`: https://stackoverflow.com/questions/52320336/modulenotfounderror-no-module-named-pyarrow

**Comment by thomas-bouvier** [comment]
Thanks @matz-e, the change you suggested solves the issue. Waiting for https://github.com/spack/spack/pull/34463 to be merged :)

@meyersbs I have the same use-case with `py-datasets`!

**Comment by thomas-bouvier** [comment]
Fixed by https://github.com/spack/spack/pull/34463

**Comment by OrionStar25** [comment]
Hello, I am running this bit of code and getting the same error. Any pointers on how to solve this?

```
import transformers

trainer = transformers.Trainer(
    model=model,
    train_dataset=training_dataset,
    args=transformers.TrainingArguments(
        per_device_train_batch_size=1,
        gradient_accumulation_steps=8,
        warmup_steps=2,
        max_steps=200,
        learning_rate=2e-4,
        fp16=True,
        logging_steps=1,
        output_dir="outputs",
        optim="paged_adamw_8bit"
    ),
    data_collator=transformers.DataCollatorForLanguageModeling(tokenizer, mlm=False),
)

trainer.train()
```
