### ISSUE TITLE
Installation issue: py-numpy%intel fails to build unless intel module is manually loaded first

### ISSUE THREAD

**Issue by quellyn** [LLNL/spack#35165]
### Steps to reproduce the issue

```console
[quellyn@cn771 spack]$ spack spec -l py-numpy                      
Input spec
--------------------------------
py-numpy

Concretized
--------------------------------
g5r4bdp  py-numpy@1.24.1%intel@20220630-nda+blas+lapack build_system=python_pip patches=873745d arch=linux-rhel8-icelake
cwxgkts      ^intel-oneapi-mkl@2022.2.1%intel@20220630-nda+cluster+envmods~ilp64+shared build_system=generic arch=linux-rhel8-icelake
6crbcdp          ^intel-oneapi-tbb@2021.8.0%intel@20220630-nda+envmods build_system=generic arch=linux-rhel8-icelake
o7riypv          ^openmpi@4.1.4-intel-classic_20220630-nda%intel@20220630-nda~atomics~cuda~cxx~cxx_exceptions~gpfs~internal-hwloc~java~legacylaunchers~lustre~memchecker~orterunprefix+romio+rsh~singularity+static+vt+wrapper-rpath build_system=autotools fabrics=none schedulers=none arch=linux-rhel8-icelake
qluc4ky      ^py-cython@0.29.32%intel@20220630-nda build_system=python_pip arch=linux-rhel8-icelake
j5gydky      ^py-pip@22.2.2%intel@20220630-nda build_system=generic arch=linux-rhel8-icelake
e5qkros      ^py-setuptools@63.0.0%intel@20220630-nda build_system=generic arch=linux-rhel8-icelake
dnmjdrc      ^py-wheel@0.37.1%intel@20220630-nda build_system=generic arch=linux-rhel8-icelake
virk47c      ^python@3.9.15%intel@20220630-nda+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=0d98e93,4c24573,f2fd060 arch=linux-rhel8-icelake
6jwzyhr          ^bzip2@1.0.8%intel@20220630-nda~debug~pic+shared build_system=generic arch=linux-rhel8-icelake
srmohte              ^diffutils@3.8%intel@20220630-nda build_system=autotools arch=linux-rhel8-icelake
2ze32g6          ^expat@2.5.0%intel@20220630-nda+libbsd build_system=autotools arch=linux-rhel8-icelake
qr4s7ab              ^libbsd@0.11.7%intel@20220630-nda build_system=autotools arch=linux-rhel8-icelake
fgb7mmd                  ^libmd@1.0.4%intel@20220630-nda build_system=autotools arch=linux-rhel8-icelake
qyxlqvf          ^gdbm@1.23%intel@20220630-nda build_system=autotools arch=linux-rhel8-icelake
yoq7dpz          ^gettext@0.21.1%intel@20220630-nda+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=linux-rhel8-icelake
iv3chyb              ^libiconv@1.17%intel@20220630-nda build_system=autotools libs=shared,static arch=linux-rhel8-icelake
kjeozng              ^libxml2@2.10.3%intel@20220630-nda~python build_system=autotools arch=linux-rhel8-icelake
54ayoq5              ^tar@1.34%intel@20220630-nda build_system=autotools zip=pigz arch=linux-rhel8-icelake
zolbefb                  ^pigz@2.7%intel@20220630-nda build_system=makefile arch=linux-rhel8-icelake
ag23ke2                  ^zstd@1.5.2%intel@20220630-nda+programs build_system=makefile compression=none libs=shared,static arch=linux-rhel8-icelake
c2e3haw          ^libffi@3.4.3%intel@20220630-nda build_system=autotools arch=linux-rhel8-icelake
w7hqvzs          ^libxcrypt@4.4.33%intel@20220630-nda~obsolete_api build_system=autotools arch=linux-rhel8-icelake
pt77no4              ^perl@5.36.0%intel@20220630-nda+cpanm+open+shared+threads build_system=generic arch=linux-rhel8-icelake
vmtvcg2                  ^berkeley-db@18.1.40%intel@20220630-nda+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-rhel8-icelake
ebann6c          ^ncurses@6.4%intel@20220630-nda~symlinks+termlib abi=none build_system=autotools arch=linux-rhel8-icelake
n6l4g3n          ^openssl@1.1.1s%intel@20220630-nda~docs~shared build_system=generic certs=mozilla arch=linux-rhel8-icelake
3s7qf7f              ^ca-certificates-mozilla@2023-01-10%intel@20220630-nda build_system=generic arch=linux-rhel8-icelake
ljuq4k6          ^pkgconf@1.8.0%intel@20220630-nda build_system=autotools arch=linux-rhel8-icelake
owovk6f          ^readline@8.2%intel@20220630-nda build_system=autotools patches=bbf97f1 arch=linux-rhel8-icelake
5c4lv67          ^sqlite@3.40.1%intel@20220630-nda+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-rhel8-icelake
xo3u6h5          ^util-linux-uuid@2.38.1%intel@20220630-nda build_system=autotools arch=linux-rhel8-icelake
teyt53c          ^xz@5.2.6%intel@20220630-nda~pic build_system=autotools libs=shared,static arch=linux-rhel8-icelake
7r2fbwl          ^zlib@1.2.13%intel@20220630-nda+optimize+pic+shared build_system=makefile arch=linux-rhel8-icelake
```

### Error message

<details><summary>Error message</summary><pre>
==> Installing py-numpy-1.24.1-g5r4bdpw7ffdomkphelopduzlotcyvpi
==> No binary for py-numpy-1.24.1-g5r4bdpw7ffdomkphelopduzlotcyvpi found: installing from source
==> Error: FileNotFoundError: [Errno 2] No such file or directory: 'icc': 'icc'

/vast/home/quellyn/GIT/spack/var/spack/repos/builtin/packages/py-numpy/package.py:173, in flag_handler:
        170        # This will essentially check the system gcc compiler unless a gcc
        171        # module is already loaded.
        172        if self.spec.satisfies("%intel") and name == "cflags":
  >>    173            p1 = subprocess.Popen([self.compiler.cc, "-v"], stderr=subprocess.PIPE)
        174            p2 = subprocess.Popen(
        175                ["grep", "compatibility"], stdin=p1.stderr, stdout=subprocess.PIPE
        176            )
</pre></details>

### Information on your system

```
[quellyn@cn771 spack]$ spack debug report
* **Spack:** 0.20.0.dev0 (54b9e3ce072664470e99f106728a8906b5ca2a41)
* **Python:** 3.6.8
* **Platform:** linux-rhel8-icelake
* **Concretizer:** clingo
```
-----

NOTE that this failure happens before Spack actually stages the `py-numpy` source code, so no `spack-build-out.txt` or `spack-build-env.txt` files get generated.

If I first load the `intel` module by hand, then the build succeeds:
```
[quellyn@cn771 spack]$ module load intel-classic/20220630-nda
[quellyn@cn771 spack]$ spack install -v py-numpy
```

[compilers.yaml.txt](https://github.com/spack/spack/files/10503357/compilers.yaml.txt)
[packages.yaml.txt](https://github.com/spack/spack/files/10503360/packages.yaml.txt)

### Additional information

```
[quellyn@cn771 spack]$ spack maintainers py-numpy
adamjstewart  rgommers
```

This error feels very similar to that reported in #14729.

Mentioning @DarylGrunau, who first encountered this problem for us, as well as @adamjstewart and @rgommers, as they are listed as `py-numpy` package maintainers.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Your `compilers.yaml` should have the full path to the intel compilers, not just the executable name. Was this file created manually or using `spack compiler find`?

**Comment by quellyn** [comment]
> Your `compilers.yaml` should have the full path to the intel compilers, not just the executable name. Was this file created manually or using `spack compiler find`?

Created manually, since in production we usually need extra flags, etc., to shoehorn in.

Looking, back, we've always just used the executable names and relied on the module load to fill in the blanks as appropriate. This clearly ain't working as expected in every case though. We'll prescribe full paths and let you know!

**Comment by quellyn** [comment]
Using full-qualified paths worked on my Intel platform test! Just waiting to hear back from @DarylGrunau about his...

**Comment by DarylGrunau** [comment]
I concur, this solves my issue too - thank you for the solution!  I think this issue can be closed ...
