### ISSUE TITLE
Installation issue: hpctoolkit: liblzma.a must be compiled with -fPIC

### ISSUE THREAD

**Issue by tldahlgren** [LLNL/spack#35193]
### Steps to reproduce the issue

```console
$ spack install hpctoolkit
```

### Error message

<details><summary>Error message</summary><pre>
...
1 error found in build log:
     184    checking for libunwind... $SPACK_ROOT/opt/spack/linux-r
            hel7-broadwell/gcc-8.3.1/libunwind-1.6.2-gtix5vfd5hqyp442awtv7exqth
            xaiiar
     185    configure: libunwind.a static archive: yes
     186    configure: libunwind.a compiled with -fPIC: yes
     187    checking for lzma... /usr
     188    configure: lzma.a static archive: no
     189    configure: lzma.a compiled with -fPIC: no
  >> 190    configure: error: liblzma.a must be compiled with -fPIC
...
</pre></details>

### Information on your system

* **Spack:** 0.20.0.dev0 (333f1e2816ccf2bd9403e94ff14fa8998c834446)
* **Python:** 3.7.2
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** clingo

### Additional information

[hpctoolkit-022.10.01-spack-build-out.txt](https://github.com/spack/spack/files/10514177/hpctoolkit-022.10.01-spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by mwkrentel** [comment]
@tldahlgren We already have this in the hpctoolkit `package.py` file.

```
depends_on("xz+pic@:5.2.6", type="link")
```

Has something changed?
How did you get lzma without PIC?

Looking at the end of your build log, I see:

```
checking for lzma... /usr
configure: lzma.a static archive: no
configure: lzma.a compiled with -fPIC: no
configure: error: liblzma.a must be compiled with -fPIC
```

Maybe you're using an external `xv` that was not built with PIC?
But your externals entry fails to say `~pic`?

I can see how that's a common and subtle and annoying issue.
But that's really a spack failure, in this case, spack externals find
produced an incorrect entry ?

But I'm happy to see that you're trying to install hpctoolkit !

**Comment by tldahlgren** [comment]
> Maybe you're using an external `xv` that was not built with PIC? But your externals entry fails to say `~pic`?
> 

🤦 Forgot to check my externals.  You're absolutely right that it is using the external that has `~pic`.

Thanks @mwkrentel !

> But I'm happy to see that you're trying to install hpctoolkit !

Thanks.  I'm currently building packages as I convert their stand-alone tests for https://github.com/spack/spack/pull/34236.
