### ISSUE TITLE
failed xsdk build on linux box

### ISSUE THREAD

**Issue by ulrikeyang** [LLNL/spack#3522]
I tried to build the xsdk on my linux box. This time I got further, after it couldn't find the compilers, I was able to add them with spack find compilers.
I was then able to start the build, however it failed with the following messages:
```
==> Executing phase : 'install'
==> Successfully installed libxml2
  Fetch: 4.54s.  Build: 31.00s.  Total: 35.54s.
[+] /home/yang11/Spacktest/spack/opt/spack/linux-rhel7-x86_64/gcc-4.9.2/libxml2-2.9.4-avqchmhxvn54cmwbybmnkxksecg4c24y
==> Fetching http://www.open-mpi.org/software/hwloc/v1.11/downloads/hwloc-1.11.6.tar.gz
######################################################################## 100.0%
curl: (35) Encountered end of file
==> Fetching from http://www.open-mpi.org/software/hwloc/v1.11/downloads/hwloc-1.11.6.tar.gz failed.
==> Could not determine url from list_url.
==> Error: FetchError: All fetchers failed for hwloc-1.11.6-olz5gu5ndzljgcdrnh6rm3pnaq44nz3x
/home/yang11/Spacktest/spack/lib/spack/spack/package.py:948, in do_fetch:
     921      def do_fetch(self, mirror_only=False):
     922          """
     923          Creates a stage directory and downloads the tarball for this package.
     924          Working directory will be set to the stage directory.
     925          """
     926          if not self.spec.concrete:
     927              raise ValueError("Can only fetch concrete packages.")
     928  
     929          start_time = time.time()
     930          if spack.do_checksum and self.version not in self.versions:
     931              tty.warn("There is no checksum on file to fetch %s safely." %
     932                       self.spec.format('$_$@'))
     933  
     934              # Ask the user whether to skip the checksum if we're
     935              # interactive, but just fail if non-interactive.
     936              ck_msg = "Add a checksum or use --no-checksum to skip this check."
     937              ignore_checksum = False
     938              if sys.stdout.isatty():
     939                  ignore_checksum = tty.get_yes_or_no("  Fetch anyway?",
     940                                                      default=False)
     941                  if ignore_checksum:
     942                      tty.msg("Fetching with no checksum.", ck_msg)
     943  
     944              if not ignore_checksum:
     945                  raise FetchError("Will not fetch %s" %
     946                                   self.spec.format('$_$@'), ck_msg)
     947  
  >> 948          self.stage.fetch(mirror_only)
     949  
     950          self._fetch_time = time.time() - start_time
     951  
     952          if spack.do_checksum and self.version in self.versions:
     953              self.stage.check()
     954  
     955          self.stage.cache_local()
```

**Comment by davydden** [comment]
are you on the HEAD of the `develop` branch (do `git pull` if not)? I recently wiped my Ubuntu 16.04 and reinstall a lot of things including `trilinos` without problems.

**Comment by ulrikeyang** [comment]
It was a completely fresh clone, so I would think so.
Ulrike

**Comment by ulrikeyang** [comment]
I was using the barry/xsdk branch, since I was trying to build the xsdk

**Comment by davydden** [comment]
> I was using the barry/xsdk branch, since I was trying to build the xsdk

i think you need to ask @BarrySmith to rebase his branch or merge `develop` so that we are on the same grounds. Otherwise, `xsdktrilinos` is in `develop` as well.

**Comment by ulrikeyang** [comment]
Hi Denis,

I tried to use the develop branch to build xsdktrilinos, and very soon I got the following error:


==> Fetching https://ftp.gnu.org/gnu/libsigsegv/libsigsegv-2.11.tar.gz

curl: (35) Encountered end of file
==> Fetching from https://ftp.gnu.org/gnu/libsigsegv/libsigsegv-2.11.tar.gz failed.
==> Error: FetchError: All fetchers failed for libsigsegv-2.11-pnjkbezbydx4kdlpttvd3zidvqznla5e
/home/yang11/Spacktest/spack/lib/spack/spack/package.py:948, in do_fetch:
     921      def do_fetch(self, mirror_only=False):
     922          """
     923          Creates a stage directory and downloads the tarball for this package.
     924          Working directory will be set to the stage directory.
     925          """
     926          if not self.spec.concrete:
     927              raise ValueError("Can only fetch concrete packages.")
     928
     929          start_time = time.time()
     930          if spack.do_checksum and self.version not in self.versions:
     931              tty.warn("There is no checksum on file to fetch %s safely." %
     932                       self.spec.format('$_$@'))
     933
     934              # Ask the user whether to skip the checksum if we're
     935              # interactive, but just fail if non-interactive.
     936              ck_msg = "Add a checksum or use --no-checksum to skip this check."
     937              ignore_checksum = False
     938              if sys.stdout.isatty():
     939                  ignore_checksum = tty.get_yes_or_no("  Fetch anyway?",
     940                                                      default=False)
     941                  if ignore_checksum:
     942                      tty.msg("Fetching with no checksum.", ck_msg)
     943
     944              if not ignore_checksum:
     945                  raise FetchError("Will not fetch %s" %
     946                                   self.spec.format('$_$@'), ck_msg)
     947
  >> 948          self.stage.fetch(mirror_only)
     949
     950          self._fetch_time = time.time() - start_time
     951
     952          if spack.do_checksum and self.version in self.versions:
     953              self.stage.check()
     954
     955          self.stage.cache_local()

**Comment by davydden** [comment]
anything special in your settings? Can you download the tarbal manually? What happens if you change `https` to `http` in `package.py`?

**Comment by ulrikeyang** [comment]
What would you be looking for with regard to settings?
Which tarball?
Where should I change https to http in package.py? It looks like it’s mostly in comments, except for the ALLOWED_URL_SCHEMES

**Comment by davydden** [comment]
> What would you be looking for with regard to settings?

no idea, i am just asking if you use some custom settings for Spack

> Which tarball?

the one which can't be download, namely https://ftp.gnu.org/gnu/libsigsegv/libsigsegv-2.11.tar.gz

> Where should I change https to http in package.py?

SPACK_ROOT/var/spack/repos/builtin/packages/libsigsegv/package.py

**Comment by adamjstewart** [comment]
It sounds like you might be having problems with your curl certificates. Do the following commands work for you outside of Spack?
```
$ curl -O http://www.open-mpi.org/software/hwloc/v1.11/downloads/hwloc-1.11.6.tar.gz
$ curl -O https://ftp.gnu.org/gnu/libsigsegv/libsigsegv-2.11.tar.gz
```
What about:
```
$ curl -O -k http://www.open-mpi.org/software/hwloc/v1.11/downloads/hwloc-1.11.6.tar.gz
$ curl -O -k https://ftp.gnu.org/gnu/libsigsegv/libsigsegv-2.11.tar.gz
```

**Comment by ulrikeyang** [comment]
since Barry merged the barry/xsdk branch I was able to try again and made progress.
It appears also there was some mismatch with the SPACK_ROOT env variable, but that is fine now.
Now it fails when trying to build Alquimia with the following error messages:
/home/yang11/IDEAS/Spack/spack/lib/spack/spack/build_systems/cmake.py:149, in cmake:
     144      def cmake(self, spec, prefix):
     145          """Runs ``cmake`` in the build directory"""
     146          options = [self.root_cmakelists_dir] + self.std_cmake_args + \
     147              self.cmake_args()
     148          with working_dir(self.build_directory, create=True):
  >> 149              inspect.getmodule(self).cmake(*options)

See build log for details:
  /tmp/yang11/spack-stage/spack-stage-RTq89u/alquimia-dev/spack-build.out

-----
and the error message  in the build log is:

CMake Error at CMakeLists.txt:191 (if):
  if given arguments:

    "STREQUAL" ""

  Unknown arguments specified


-- Configuring incomplete, errors occurred!
See also "/tmp/yang11/spack-stage/spack-stage-RTq89u/alquimia-dev/spack-build/CM
akeFiles/CMakeOutput.log".

------
/tmp/yang11/spack-stage/spack-stage-RTq89u/alquimia-dev/spack-build/CM: No such file or directory
tux340.llnl.gov{yang11}137: more /tmp/yang11/spack-stage/spack-stage-RTq89u/alquimia-dev/spack-build/CM
/tmp/yang11/spack-stage/spack-stage-RTq89u/alquimia-dev/spack-build/CM: No such file or directory

**Comment by ulrikeyang** [comment]
Ignore the bottom portion of my previous comment, but the parts before are important.
Thanks
Ulrike

**Comment by adamjstewart** [comment]
There is no `alquimia-dev` package in Spack, so we likely won't be able to help you. You may want to contact the `alquimia-dev` developers.

**Comment by ulrikeyang** [comment]
So, there is apparently a known alquimia issue, which they are working on.

However, I also tried to build xsdk on cab and it fails for me when building hdf5 with the following error:
==> Ran patch() for hdf5
==> Building hdf5 [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Executing phase : 'configure'
==> Executing phase : 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j32'
/tmp/ulrikey/Spacktest/spack/lib/spack/spack/build_systems/autotools.py:271, in build:
     266      def build(self, spec, prefix):
     267          """Makes the build targets specified by
     268          :py:attr:``~.AutotoolsPackage.build_targets``
     269          """
     270          with working_dir(self.build_directory):
  >> 271              inspect.getmodule(self).make(*self.build_targets)

See build log for details:
  /tmp/ulrikey/spack-stage/spack-stage-Wr3TJX/hdf5-1.10.0-patch1/spack-build.out

Do you have any suggestions on how to deal with that?
Thanks
Ulrike

**Comment by adamjstewart** [comment]
The error message that you posted means that something went wrong during `make`. As for what went wrong, the build log (`spack-build.out`) should be very enlightening.

**Comment by ulrikeyang** [comment]
The last few lines are
Warning: Possible change of value in conversion from INTEGER(4) to INTEGER(2) at (1)
tH5T_F03.F90:1178.18:

    f_ptr = C_LOC(data_out_r31)
                  1
Error: Parameter 'data_out_r31' to 'c_loc' at (1) must be a scalar
f951: warning: unrecognized command line option "-Wno-c-binding-type" [enabled by default]
make[2]: *** [tH5T_F03.o] Error 1
make[2]: Leaving directory `/tmp/ulrikey/spack-stage/spack-stage-Wr3TJX/hdf5-1.10.0-patch1/fortran/test'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/ulrikey/spack-stage/spack-stage-Wr3TJX/hdf5-1.10.0-patch1/fortran'
make: *** [all-recursive] Error 1
