### ISSUE TITLE
can not install package in env

### ISSUE THREAD

**Issue by SuperLight-007** [LLNL/spack#35231]
### Steps to reproduce

![920eb62e-a511-4858-b026-6da9ba3e6de7](https://user-images.githubusercontent.com/39428543/215448901-1ccdd6de-24cd-4dd1-82bf-b1c8d260cd1e.jpeg)

### Error message

ubuntu@VM-170-232-ubuntu:~$ spack env status
==> In environment myenv1
ubuntu@VM-170-232-ubuntu:~$ spack install gcc@9.4.0
==> Error: Cannot install 'gcc@9.4.0' because it is not in the current environment. You can add it to the environment with 'spack add gcc@9.4.0', or as part of the install command with 'spack install --add gcc@9.4.0'
ubuntu@VM-170-232-ubuntu:~$ spack install gcc@9.4.0
==> Error: Cannot install 'gcc@9.4.0' because it is not in the current environment. You can add it to the environment with 'spack add gcc@9.4.0', or as part of the install command with 'spack install --add gcc@9.4.0'
ubuntu@VM-170-232-ubuntu:~$ spack load gcc@9.4.0
==> Error: Spec 'gcc@9.4.0' matches no installed packages.
ubuntu@VM-170-232-ubuntu:~$ spack install gcc@9.4.0
==> Error: Cannot install 'gcc@9.4.0' because it is not in the current environment. You can add it to the environment with 'spack add gcc@9.4.0', or as part of the install command with 'spack install --add gcc@9.4.0'
ubuntu@VM-170-232-ubuntu:~$ spack env status
==> In environment myenv1
ubuntu@VM-170-232-ubuntu:~$ spack add gcc@9.4.0
==> Package gcc was already added to myenv1
ubuntu@VM-170-232-ubuntu:~$ spack install gcc@9.4.0
==> Error: Cannot install 'gcc@9.4.0' because it is not in the current environment. You can add it to the environment with 'spack add gcc@9.4.0', or as part of the install command with 'spack install --add gcc@9.4.0'
ubuntu@VM-170-232-ubuntu:~$ spack install --add gcc@9.4.0
==> Error: cannot install a single spec in an environment that is configured to be concretized together. Run instead:

    $ spack add <spec>
    $ spack install

ubuntu@VM-170-232-ubuntu:~$

### Information on your system

ubuntu@VM-170-232-ubuntu:~$ spack env status
==> In environment myenv1
ubuntu@VM-170-232-ubuntu:~$ spack install gcc@9.4.0
==> Error: Cannot install 'gcc@9.4.0' because it is not in the current environment. You can add it to the environment with 'spack add gcc@9.4.0', or as part of the install command with 'spack install --add gcc@9.4.0'
ubuntu@VM-170-232-ubuntu:~$ spack install gcc@9.4.0
==> Error: Cannot install 'gcc@9.4.0' because it is not in the current environment. You can add it to the environment with 'spack add gcc@9.4.0', or as part of the install command with 'spack install --add gcc@9.4.0'
ubuntu@VM-170-232-ubuntu:~$ spack load gcc@9.4.0
==> Error: Spec 'gcc@9.4.0' matches no installed packages.
ubuntu@VM-170-232-ubuntu:~$ spack install gcc@9.4.0
==> Error: Cannot install 'gcc@9.4.0' because it is not in the current environment. You can add it to the environment with 'spack add gcc@9.4.0', or as part of the install command with 'spack install --add gcc@9.4.0'
ubuntu@VM-170-232-ubuntu:~$ spack env status
==> In environment myenv1
ubuntu@VM-170-232-ubuntu:~$ spack add gcc@9.4.0
==> Package gcc was already added to myenv1
ubuntu@VM-170-232-ubuntu:~$ spack install gcc@9.4.0
==> Error: Cannot install 'gcc@9.4.0' because it is not in the current environment. You can add it to the environment with 'spack add gcc@9.4.0', or as part of the install command with 'spack install --add gcc@9.4.0'
ubuntu@VM-170-232-ubuntu:~$ spack install --add gcc@9.4.0
==> Error: cannot install a single spec in an environment that is configured to be concretized together. Run instead:

    $ spack add <spec>
    $ spack install

ubuntu@VM-170-232-ubuntu:~$

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
This has been fixed recently in `develop`, so is not reproducible anymore:
![Screenshot from 2023-04-05 16-56-30](https://user-images.githubusercontent.com/4199709/230120503-090e9b2a-89d7-42f9-8dec-008433c1bfe8.png)
