### ISSUE TITLE
`-Werror` to `-Wno-error` translation does not work with `nvc++` because it doesn't support `-Wno-error`

### ISSUE THREAD

**Issue by msimberg** [LLNL/spack#35235]
### Steps to reproduce

Enter some `build-env` with `%nvhpc` (version 22.11 in my case):
```console
> spack build-env pika%nvhpc -- bash
```

```console
> nvc++ -Werror ...
nvc++-Error-Unknown switch: -Wno-error
```
Indeed, `nvc++` doesn't have a `-Wno-error` switch (it does have more specific ones, like `-Wno-deprecated-declarations`).

This clearly comes from https://github.com/spack/spack/pull/30882. I see there's a way to disable this behaviour per-package which is nice. However, in this case the behaviour would need to be overridden per-compiler. I didn't see such a toggle but maybe I'm missing it. I'm guessing `nvc++` may some day end up supporting `-Wno-error` so hard-coding somewhere that `nvc++` should not do that replacement seems clunky, but is there a better way?

### Information on your system

```console
> spack debug report
* **Spack:** 0.20.0.dev0 (ee9857d57858888cf3b400c6781ec9968dc19cc2)
* **Python:** 3.6.15
* **Platform:** linux-sles15-zen2
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
@samcmill fyi

**Comment by samcmill** [comment]
I've filed an RFE to add support for this flag.  

In the meantime, there is the `-noswitcherror` option, or the equivalent `NVCOMPILER_NOSWITCHERROR=1` environment variable.

**Comment by alalazo** [comment]
@trws fyi

**Comment by trws** [comment]
That's very, very annoying.  I suppose we could make all packages built with nvhpc leave werror in.  We can't necessarily use the environment variable or other options without breaking build system checks, so we may be stuck with that until they can support what we're currently doing.
