### ISSUE TITLE
External environment module not found

### ISSUE THREAD

**Issue by ScottWales** [LLNL/spack#3523]
I am looking into using Spack to manage a small number of packages on a HPC for my research group. The HPC has an existing large variety of environment modules installed by the administrators, which I would like to use from within Spack.

To get a handle on how Spack works I have created an empty repository with a single package that depends on MPI
```python
class Hdf5(AutotoolsPackage):
    homepage = "https://support.hdfgroup.org/HDF5/"
    url      = "https://support.hdfgroup.org/ftp/HDF5/current18/src/hdf5-1.8.18.tar.bz2"    
    version('1.8.18', '29117bf488887f89888f9304c8ebea0b')
    depends_on('mpi')
    def configure_args(self):
        args = ['--enable-mpi']
        return args
```
and I have set up the central MPI module in `packages.yaml` following http://spack.readthedocs.io/en/latest/build_settings.html#external-packages
```yaml
packages:
    openmpi:
        buildable: False
        modules:
            openmpi@1.10.2%intel@17.0.1.132: openmpi/1.10.2
    all:
        compiler:
            - intel
        providers:
            mpi:
                - openmpi
```
My understanding is that this will run `module load openmpi/1.10.2` when building the package

If I try to install the package I get the following error:
```
$ spack --debug install hdf5
==> Reading config file /short/w35/saw562/scratch/spack/spack/etc/spack/defaults/packages.yaml
==> Reading config file /home/562/saw562/.spack/packages.yaml
==> READ LOCK: /home/562/saw562/.spack/cache/providers/.arccss-index.yaml.lock[0:0] [Acquiring]
==> READ LOCK: /home/562/saw562/.spack/cache/providers/.arccss-index.yaml.lock[0:0] [Released]
==> '/opt/Modules/3.2.6/bin/modulecmd' 'python' 'show' 'openmpi/1.10.2'
==> Error: The spec 'mpi' is configured as not buildable, and no matching external installs were found
```
It appears that the installer is not able to find the openmpi module, although `modulecmd python show openmpi/1.10.2` works fine. Is there something special that it's looking for inside the module?

**Comment by alalazo** [comment]
Can you post the output of:
```
$ spack spec hdf5
...
$ spack compilers
```
My guess is that your default compiler is resolved to be `gcc`.

**Comment by ScottWales** [comment]
```
$ spack spec hdf5
Input spec
--------------------------------
hdf5

Normalized
--------------------------------
hdf5
    ^mpi

Concretized
--------------------------------
==> Error: The spec 'mpi' is configured as not buildable, and no matching external installs were found
```

```
$ spack compilers
==> Available compilers
-- gcc centos6-x86_64 -------------------------------------------
gcc@6.2.0  gcc@4.4.7

-- intel centos6-x86_64 -----------------------------------------
intel@17.0.1.132  intel@12.1.9.293
```
Adding `preferred: True` to the intel compiler gives the same result.

Does there need to be a openmpi package in the repository, or is Spack happy with it just listed in `packages.yaml`?

**Comment by alalazo** [comment]
> Does there need to be a openmpi package in the repository, or is Spack happy with it just listed in packages.yaml?

You need the `package.py` to be in the repository, even if the package is a non-buildable external. This is because the package also carries potential information for dependents or run-time (e.g. through the `setup_dependent_environment` or similar callbacks).

**Comment by davydden** [comment]
> To get a handle on how Spack works I have created an empty repository with a single package that depends on MPI

why would you create an empty repo? I mean, why not checking out spack's `develop` branch and try using?

**Comment by ScottWales** [comment]
@alalazo Thanks, adding a dummy package solved my issue
```
class Openmpi(Package):
    provides('mpi')
    version('1.10.2')
    def url_for_version(self, version):
        return '/dev/null'
```

@davydden The built-in package repository appears to be more of a 'build the world' thing from what I can see, downloading and building all of the libraries itself that we already have available centrally on the HPC. It also seems like a good thing to have a single place where packages are defined - if a package is in the repository then it's in our available modules, and there's just one place to look to find out how a package was built.

**Comment by scheibelp** [comment]
> The built-in package repository appears to be more of a 'build the world' thing from what I can see, downloading and building all of the libraries itself that we already have available centrally on the HPC.

To be clear, the package repository doesn't determine what all gets installed, it just provides "recipes" for installing packages when you want to do so

> if a package is in the repository then it's in our available modules, and there's just one place to look to find out how a package was built.

Would it be sufficient to inspect the installation prefix (e.g. under ```spack/opt/...```)? This would also tell you which modules are installed (as well as ```spack/share/spack/modules/...```. The installation prefix also includes a ```.spack``` directory with a ```spec.yaml``` file that fully details how the package was built (all variants, dependencies, etc.). The package.py in the repository would typically be insufficient to determine exactly how a package is built.
