### ISSUE TITLE
Installation issue: boost (failing concretizing 1.65.0 and 1.64.0 in environment)

### ISSUE THREAD

**Issue by KIwabuchi** [LLNL/spack#35255]
### Steps to reproduce the issue

```console
$ spack env create --with-view view --dir .
$ spack -e . add  boost@1.65.1 boost@1.65.0 boost@1.64.0
$ spack -e . concretize
```

However, FYI, I did not get an error when concretizing only v1.65.0.

```console
$ spack env create --with-view view --dir .
$ spack -e . add  boost@1.65.0
$ spack -e . concretize
==> Concretized boost@1.65.0
 -   byxv3h4  boost@1.65.0%gcc@4.9.3~atomic~chrono~clanglibcpp~container~context~contract~coroutine~date_time~debug~exception~fiber~filesystem~graph~graph_parallel~icu~iostreams~json~locale~log~math~mpi+multithreaded~nowide~numpy~pic~program_options~python~random~regex~serialization+shared~signals~singlethreaded~stacktrace~system~taggedlayout~test~thread~timer~type_erasure~versionedlayout~wave build_system=generic cxxstd=98 patches=7f95f95 visibility=hidden arch=linux-rhel7-broadwell
```

### Error message

<details><summary>Error message</summary><pre>
==> Error: No version for 'boost' satisfies '@1.64.0' and '@1.65.0'. Consider setting `concretizer:unify` to `when_possible` or `false` to relax the concretizer strictness.
</pre></details>

### Information on your system

* **Spack:** 0.20.0.dev0 (ecd4eac184e23252da8ea05581ab1ec58929610c)
* **Python:** 3.7.2
* **Platform:** linux-rhel7-broadwell
* **Concretizer:** clingo

### Additional information

The maintainer of this package is @hainest

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
By default spack concretizes with `concretizer:unify:true`, which means 1 flavor of every package.

Did you follow the hint in the error? You can edit the environment through `spack -e . config edit` and replace `unify: true` with `unify: when_possible` or `unify: false`.

**Comment by KIwabuchi** [comment]
Thank you for your help and for explaining the meaning of the error message.

I tried `unify: when_possible ` and `unify: false`; however, unfortunately, I got another error as follows:

### Error message
<details><summary>Error message</summary><pre>
oslic3:~/tmp/boost-install-test$ spack -e . concretize
==> Concretized boost@1.64.0
[+]  cppq3pf  boost@1.64.0%gcc@4.9.3~atomic~chrono~clanglibcpp~container~context~contract~coroutine~date_time~debug~exception~fiber~filesystem~graph~graph_parallel~icu~iostreams~json~locale~log~math~mpi+multithreaded~nowide~numpy~pic~program_options~python~random~regex~serialization+shared~signals~singlethreaded~stacktrace~system~taggedlayout~test~thread~timer~type_erasure~versionedlayout~wave build_system=generic cxxstd=98 patches=7f95f95 visibility=hidden arch=linux-rhel7-broadwell

==> Concretized boost@1.65.0
[+]  byxv3h4  boost@1.65.0%gcc@4.9.3~atomic~chrono~clanglibcpp~container~context~contract~coroutine~date_time~debug~exception~fiber~filesystem~graph~graph_parallel~icu~iostreams~json~locale~log~math~mpi+multithreaded~nowide~numpy~pic~program_options~python~random~regex~serialization+shared~signals~singlethreaded~stacktrace~system~taggedlayout~test~thread~timer~type_erasure~versionedlayout~wave build_system=generic cxxstd=98 patches=7f95f95 visibility=hidden arch=linux-rhel7-broadwell

==> Concretized boost@1.65.1
[+]  c6pec26  boost@1.65.1%gcc@4.9.3~atomic~chrono~clanglibcpp~container~context~contract~coroutine~date_time~debug~exception~fiber~filesystem~graph~graph_parallel~icu~iostreams~json~locale~log~math~mpi+multithreaded~nowide~numpy~pic~program_options~python~random~regex~serialization+shared~signals~singlethreaded~stacktrace~system~taggedlayout~test~thread~timer~type_erasure~versionedlayout~wave build_system=generic cxxstd=98 patches=7f95f95 visibility=hidden arch=linux-rhel7-broadwell

==> Updating view at /g/g90/iwabuchi/tmp/boost-install-test/view
==> Error: 74 fatal error(s) when merging prefixes:
    `/p/vast1/iwabuchi/spack/opt/spack/linux-rhel7-broadwell/gcc-4.9.3/boost-1.64.0-cppq3pfl47qpjwprxxzs72se6tihkvhp/.spack/install_environment.json` and `/p/vast1/iwabuchi/spack/opt/spack/linux-rhel7-broadwell/gcc-4.9.3/boost-1.65.0-byxv3h4a4g5pa2fqdmzengwvy44p45jq/.spack/install_environment.json` both project to `.spack/boost/install_environment.json`
    `/p/vast1/iwabuchi/spack/opt/spack/linux-rhel7-broadwell/gcc-4.9.3/boost-1.64.0-cppq3pfl47qpjwprxxzs72se6tihkvhp/.spack/install_manifest.json` and `/p/vast1/iwabuchi/spack/opt/spack/linux-rhel7-broadwell/gcc-4.9.3/boost-1.65.0-byxv3h4a4g5pa2fqdmzengwvy44p45jq/.spack/install_manifest.json` both project to `.spack/boost/install_manifest.json`
    `/p/vast1/iwabuchi/spack/opt/spack/linux-rhel7-broadwell/gcc-4.9.3/boost-1.64.0-cppq3pfl47qpjwprxxzs72se6tihkvhp/.spack/install_times.json` and `/p/vast1/iwabuchi/spack/opt/spack/linux-rhel7-broadwell/gcc-4.9.3/boost-1.65.0-byxv3h4a4g5pa2fqdmzengwvy44p45jq/.spack/install_times.json` both project to `.spack/boost/install_times.json`
</pre></details>

**Comment by hainest** [comment]
`unify: when_possible` and `unify: false` are working correctly as of v0.21.2. I'm not sure exactly when this was fixed, though.

@KIwabuchi I'm going to close this for now, but feel free to re-open to let us know if you are still having this problem.
