### ISSUE TITLE
spack load gcc@10.2.0 failed

### ISSUE THREAD

**Issue by SonofCeasar** [LLNL/spack#35278]
### Steps to reproduce

$ spack compiler list
==> Available compilers
-- gcc ubuntu20.04-x86_64 ---------------------------------------
gcc@10.2.0  gcc@9.4.0
$ spack load gcc@10.2.0
==> Error: Spec 'gcc@10.2.0' matches no installed packages.

### Error message

Error: Spec 'gcc@10.2.0' matches no installed packages.

### Information on your system

* **Spack:** 0.16.1-1677-952f76bda3
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** original

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
`spack load` is for all things in the database (i.e. those that show up with `spack find`).

Spack does not register compilers defined in `compilers.yaml` in the database.

You can however create a shell with a build environment, for example `spack build-env zlib%gcc -- bash`, which sets the relevant variables.
