### ISSUE TITLE
Bad error message for patch that doesn't apply

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#35300]
### Steps to reproduce

I am trying to install HDF5. There's a new version out, and some of the patches I apply locally don't apply cleanly. Spack's error messages are unclear.

This bug report is not about these patches, it is about Spack not producing helpful error messages in this case.

### Error message

```console
==> Installing hdf5-1.14.0-3ed5dkvo6djnqiwdkk3gtopkaligqcqn
==> No binary for hdf5-1.14.0-3ed5dkvo6djnqiwdkk3gtopkaligqcqn found: installing from source
==> Fetching https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.14/hdf5-1.14.0/src/hdf5-1.14.0.tar.gz
File to patch:
```

(1) When a patch doesn't apply, then manually asking for a file name isn't useful. Instead, Spack should abort.
(2) Spack doesn't say what it was doing (which patch it is trying to apply) when the failure occurs. That's probably related to (1).

### Information on your system

* **Spack:** 0.20.0.dev0 (0e4178881285ac4d7ecd3c5010bb6b66c2c20d93)
* **Python:** 3.9.6
* **Platform:** darwin-ventura-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Do you have a reproducer to trigger this error?

**Comment by alalazo** [comment]
@eschnett

**Comment by eschnett** [comment]
No, I do not. I will submit one once I have one.
