### ISSUE TITLE
`--scope env:ENVIRONMENT` not recognized

### ISSUE THREAD

**Issue by wholtz** [LLNL/spack#35373]
### Steps to reproduce

I created an environment and then tried to add a compiler within the scope of the environment:
```console
$ spack env create example 
$ spack compiler add --scope env:example /fake/path
```

### Error message

```console
$ spack env create example 
==> Created environment 'example' in /home/foo/spack/var/spack/environments/example
==> You can activate this environment with:
==>   spack env activate example
$ spack compiler add --scope env:example /fake/path
usage: spack compiler find [-h]
                           [--scope {defaults,system,site,user}[/PLATFORM] or
                           env:ENVIRONMENT]
                           ...
spack compiler find: error: argument --scope: invalid choice: 'env:example' choose from:
    _builtin  command_line  defaults  defaults/linux  site  site/linux  system  system/linux
```

I expected the `spack.yaml` for environment `example` to get a new `complier` stanza, but `spack.yaml` was not modified. Additionally, the help output that is shown is for `spack compiler find` but it should be for `spack compiler add`

I was able to get the result I desired by using:
```console
spack -e example compiler add /fake/path
```

And here is the problematic command with debug output:

```console
$ spack --debug compiler add --scope env:example /fake/path
==> [2023-02-07-10:37:56.317544] Imported compiler from built-in commands
==> [2023-02-07-10:37:56.318823] Imported compiler from built-in commands
usage: spack compiler find [-h]
                           [--scope {defaults,system,site,user}[/PLATFORM] or
                           env:ENVIRONMENT]
                           ...
spack compiler find: error: argument --scope: invalid choice: 'env:example' choose from:
    _builtin  command_line  defaults  defaults/linux  site  site/linux  system  system/linux

==> [2023-02-07-10:37:56.323041] Reading config from file /clusterfs/jgi/groups/gentech/genome_analysis/usa/wjholtz/spack/etc/spack/defaults/config.yaml
==> [2023-02-07-10:37:56.352164] Skipping nonexistent config path /clusterfs/jgi/groups/gentech/genome_analysis/usa/wjholtz/spack/etc/spack/defaults/linux/config.yaml
==> [2023-02-07-10:37:56.352236] Skipping nonexistent config path /etc/spack/config.yaml
==> [2023-02-07-10:37:56.352279] Skipping nonexistent config path /etc/spack/linux/config.yaml
==> [2023-02-07-10:37:56.352323] Skipping nonexistent config path /clusterfs/jgi/groups/gentech/genome_analysis/usa/wjholtz/spack/etc/spack/config.yaml
==> [2023-02-07-10:37:56.352581] Skipping nonexistent config path /clusterfs/jgi/groups/gentech/genome_analysis/usa/wjholtz/spack/etc/spack/linux/config.yaml
Traceback (most recent call last):
  File "/usr/lib64/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.6/argparse.py", line 1972, in _parse_known_args
    start_index = consume_optional(start_index)
  File "/usr/lib64/python3.6/argparse.py", line 1912, in consume_optional
    take_action(action, args, option_string)
  File "/usr/lib64/python3.6/argparse.py", line 1824, in take_action
    argument_values = self._get_values(action, argument_strings)
  File "/usr/lib64/python3.6/argparse.py", line 2266, in _get_values
    self._check_value(action, value)
  File "/clusterfs/jgi/groups/gentech/genome_analysis/usa/wjholtz/spack/lib/spack/spack/main.py", line 379, in _check_value
    raise argparse.ArgumentError(action, msg)
argparse.ArgumentError: argument --scope: invalid choice: 'env:example' choose from:
    _builtin  command_line  defaults  defaults/linux  site  site/linux  system  system/linux


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/clusterfs/jgi/groups/gentech/genome_analysis/usa/wjholtz/spack/lib/spack/spack/main.py", line 1007, in main
    return _main(argv)
  File "/clusterfs/jgi/groups/gentech/genome_analysis/usa/wjholtz/spack/lib/spack/spack/main.py", line 962, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/clusterfs/jgi/groups/gentech/genome_analysis/usa/wjholtz/spack/lib/spack/spack/main.py", line 969, in finish_parse_and_run
    args, unknown = parser.parse_known_args()
  File "/usr/lib64/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.6/argparse.py", line 1954, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/lib64/python3.6/argparse.py", line 1931, in consume_positionals
    take_action(action, args)
  File "/usr/lib64/python3.6/argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib64/python3.6/argparse.py", line 1137, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/usr/lib64/python3.6/argparse.py", line 1766, in parse_known_args
    namespace, args = self._parse_known_args(args, namespace)
  File "/usr/lib64/python3.6/argparse.py", line 1954, in _parse_known_args
    positionals_end_index = consume_positionals(start_index)
  File "/usr/lib64/python3.6/argparse.py", line 1931, in consume_positionals
    take_action(action, args)
  File "/usr/lib64/python3.6/argparse.py", line 1840, in take_action
    action(self, namespace, argument_values, option_string)
  File "/usr/lib64/python3.6/argparse.py", line 1137, in __call__
    subnamespace, arg_strings = parser.parse_known_args(arg_strings, None)
  File "/usr/lib64/python3.6/argparse.py", line 1773, in parse_known_args
    self.error(str(err))
  File "/usr/lib64/python3.6/argparse.py", line 2393, in error
    self.exit(2, _('%(prog)s: error: %(message)s\n') % args)
  File "/usr/lib64/python3.6/argparse.py", line 2380, in exit
    _sys.exit(status)
SystemExit: 2
```

### Information on your system

```console
$ spack debug report
* **Spack:** 0.19.0
* **Python:** 3.6.8
* **Platform:** linux-scientific7-zen2
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by scheibelp** [comment]
Given the sequence:

```
$ spack env create example 
$ spack compiler add --scope env:example /fake/path
```

as of now this failure is expected, in particular if you don't activate the environment before specifying the scope. So

```
$ spack env create example 
$ spack env activate example <--- activate this
$ spack compiler add --scope env:example /fake/path <--- the env:example scope only exists because the env is active
```

should work. That being said

```
$ spack env create example 
$ spack env activate example
$ spack compiler add /fake/path <--- no scope specified
```

would have the same effect because by default we modify the scope associated with an active environment (it can be worth specifying `--scope` though because it is explicit and could avoid changing behavior with changing defaults).

You may have also encountered `-E`, which can also be used to perform a single command in the context of an env like:

```
$ spack env create example 
$ spack -E example compiler add --scope env:example /fake/path 
```

Note with https://github.com/spack/spack/pull/35307, you wouldn't have to activate an environment (or use `-E`) to modify it, so that would provide another means.

Overall then, as long as you get the result you want, I'd say this behavior is expected and this issue can be closed. However, if that brings up additional questions (or if you would rather Spack behaved differently) feel free to add those to this thread as well.

**Comment by wholtz** [comment]
The behaviors you describe all seem fine.  The documentation should probably be a bit more explicit about when `--scope env:ENVIRONMENT` is valid to use. In particular, the availability of scopes could be mentioned in the [configuring of environments](https://spack.readthedocs.io/en/latest/environments.html#configuring-environments) section. Maybe I'll get around to a documentation PR for that.

I did note above that  when `spack compiler add` tries to access an invalid scope, the help screen is shown for `spack compiler find`, which could use fixing:
```console
$ spack compiler add --scope env:example /fake/path
usage: spack compiler find [-h]
```

**Comment by fgava90** [comment]
Hello,
I'm finding an issue related to this.
If execute
`$ spack compiler find --scope site /fake/path`
the compiler gets added to correctly to the site file.
However if I then execute:
`$ spack env activate --without-view /path/to/env`
`$ spack compilers --scope env:/path/to/env`
`==> No compilers available`
Which is correct as no compiler was yet defined for that environment.
`$ spack compiler find --scope env:/path/to/env /fake/path`
`==> Found no new compilers`
`==> Compilers are defined in the following files:`
`    /path/to/site/compilers.yaml`
I get that message saying that there are no new compilers found and that they are defined in the site location, but no mention about the environment, which is not modified. 
Is this behaviour expected? Why isn't the compiler added to the environment?
I would expect to be able to define a subset of compilers from site to use in my environment and not use those defined by the site if i don't want them in the environment.

**Comment by scheibelp** [comment]
Hi @fgava90, this sounds like a separate issue: could you open one with this sequence and ping me on it?

Would you be able to add what `/fake/path` is in your case (i.e. the actual path you are providing to `spack compiler find`)?
