### ISSUE TITLE
Installation issue: Quantum Espresso with AOCC/AOCL

### ISSUE THREAD

**Issue by vitduck** [LLNL/spack#35473]
### Steps to reproduce the issue

```
$ spack spec -I  quantum-espresso@7.1 +openmp %aocc@3.2.0 target=zen3 ^amdfftw@3.2 ^amdblis@3.2 threads=openmp ^amdlibflame@3.2 ^amdscalapack@3.2 ^openmpi@4.1.1 fabrics=auto 
Concretized
--------------------------------
 -   quantum-espresso@7.1%aocc@3.2.0~elpa+epw~ipo~libxc+mpi~nvtx+openmp+patch~qmcpack+scalapack build_system=cmake build_type=RelWithDebInfo hdf5=none arch=linux-centos7-zen3
[+]      ^amdblis@3.2%aocc@3.2.0+blas+cblas~ilp64 build_system=makefile libs=shared,static threads=openmp arch=linux-centos7-zen3
[+]          ^python@3.10.8%aocc@3.2.0+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib build_system=generic patches=0d98e93,7d40923,f2fd060 arch=linux-centos7-zen3
[+]              ^bzip2@1.0.8%aocc@3.2.0~debug~pic+shared build_system=generic arch=linux-centos7-zen3
[+]              ^gdbm@1.23%aocc@3.2.0 build_system=autotools arch=linux-centos7-zen3
[+]              ^libffi@3.4.2%aocc@3.2.0 build_system=autotools arch=linux-centos7-zen3
[+]              ^readline@8.1.2%aocc@3.2.0 build_system=autotools arch=linux-centos7-zen3
[+]              ^sqlite@3.39.4%aocc@3.2.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-centos7-zen3
[+]              ^util-linux-uuid@2.38.1%aocc@3.2.0 build_system=autotools arch=linux-centos7-zen3
[+]              ^xz@5.2.7%aocc@3.2.0~pic build_system=autotools libs=shared,static arch=linux-centos7-zen3
 -       ^amdfftw@3.2%aocc@3.2.0~amd-app-opt~amd-dynamic-dispatcher~amd-fast-planner~amd-mpi-vader-limit~amd-top-n-planner~amd-trans~debug+mpi+openmp+shared~static~threads build_system=autotools precision=double,float arch=linux-centos7-zen3
[+]          ^texinfo@6.5%aocc@3.2.0 build_system=autotools patches=12f6edb,1732115 arch=linux-centos7-zen3
 -       ^amdlibflame@3.2%aocc@3.2.0~debug~ilp64+lapack2flame+shared+static build_system=autotools threads=none arch=linux-centos7-zen3
 -       ^amdscalapack@3.2%aocc@3.2.0~ilp64~ipo~pic+shared build_system=cmake build_type=Release arch=linux-centos7-zen3
[+]      ^cmake@3.24.3%aocc@3.2.0~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-centos7-zen3
[+]          ^ncurses@6.3%aocc@3.2.0~symlinks+termlib abi=none build_system=autotools arch=linux-centos7-zen3
[+]          ^openssl@1.1.1s%aocc@3.2.0~docs~shared build_system=generic certs=mozilla arch=linux-centos7-zen3
[+]              ^ca-certificates-mozilla@2022-10-11%aocc@3.2.0 build_system=generic arch=linux-centos7-zen3
[+]      ^git@2.38.1%aocc@3.2.0+man+nls+perl+subtree~svn~tcltk build_system=autotools arch=linux-centos7-zen3
[+]          ^autoconf@2.69%aocc@3.2.0 build_system=autotools patches=35c4492,7793209,a49dd5b arch=linux-centos7-zen3
[+]          ^automake@1.16.5%aocc@3.2.0 build_system=autotools arch=linux-centos7-zen3
[+]          ^curl@7.85.0%aocc@3.2.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2~nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-centos7-zen3
[+]          ^expat@2.4.8%aocc@3.2.0+libbsd build_system=autotools arch=linux-centos7-zen3
[+]              ^libbsd@0.11.5%aocc@3.2.0 build_system=autotools arch=linux-centos7-zen3
[+]                  ^libmd@1.0.4%aocc@3.2.0 build_system=autotools arch=linux-centos7-zen3
[+]          ^gettext@0.21.1%aocc@3.2.0+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=linux-centos7-zen3
[+]              ^libxml2@2.10.1%aocc@3.2.0~python build_system=autotools arch=linux-centos7-zen3
[+]              ^tar@1.34%aocc@3.2.0 build_system=autotools zip=pigz arch=linux-centos7-zen3
[+]                  ^pigz@2.7%aocc@3.2.0 build_system=makefile arch=linux-centos7-zen3
[+]                  ^zstd@1.5.2%aocc@3.2.0+programs build_system=makefile compression=none libs=shared,static arch=linux-centos7-zen3
[+]          ^libiconv@1.16%aocc@3.2.0 build_system=autotools libs=shared,static arch=linux-centos7-zen3
[+]          ^libidn2@2.3.0%aocc@3.2.0 build_system=autotools arch=linux-centos7-zen3
[+]              ^libunistring@0.9.10%aocc@3.2.0 build_system=autotools arch=linux-centos7-zen3
[+]          ^libtool@2.4.7%aocc@3.2.0 build_system=autotools arch=linux-centos7-zen3
[+]          ^openssh@9.1p1%aocc@3.2.0+gssapi build_system=autotools arch=linux-centos7-zen3
[+]              ^krb5@1.19.3%aocc@3.2.0+shared build_system=autotools arch=linux-centos7-zen3
[+]                  ^bison@3.8.2%aocc@3.2.0 build_system=autotools arch=linux-centos7-zen3
[+]              ^libedit@3.1-20210216%aocc@3.2.0 build_system=autotools arch=linux-centos7-zen3
[+]          ^pcre2@10.39%aocc@3.2.0~jit+multibyte build_system=autotools arch=linux-centos7-zen3
[+]          ^perl@5.36.0%aocc@3.2.0+cpanm+shared+threads build_system=generic arch=linux-centos7-zen3
[+]              ^berkeley-db@18.1.40%aocc@3.2.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-centos7-zen3
[+]          ^zlib@1.2.13%aocc@3.2.0+optimize+pic+shared build_system=makefile arch=linux-centos7-zen3
[+]      ^m4@1.4.19%aocc@3.2.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-centos7-zen3
[+]          ^diffutils@3.8%aocc@3.2.0 build_system=autotools arch=linux-centos7-zen3
[+]          ^libsigsegv@2.13%aocc@3.2.0 build_system=autotools arch=linux-centos7-zen3
[+]      ^openmpi@4.1.1%aocc@3.2.0~atomics~cuda~cxx~cxx_exceptions~gpfs~internal-hwloc~java~legacylaunchers~lustre~memchecker+romio+rsh~singularity+static+vt+wrapper-rpath build_system=autotools fabrics=auto schedulers=none arch=linux-centos7-zen3
[+]          ^hwloc@2.8.0%aocc@3.2.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-centos7-zen3
[+]              ^libpciaccess@0.16%aocc@3.2.0 build_system=autotools arch=linux-centos7-zen3
[+]                  ^util-macros@1.19.3%aocc@3.2.0 build_system=autotools arch=linux-centos7-zen3
[+]          ^numactl@2.0.14%aocc@3.2.0 build_system=autotools patches=4e1d78c,62fc8a8,ff37630 arch=linux-centos7-zen3
[+]          ^pkgconf@1.8.0%aocc@3.2.0 build_system=autotools arch=linux-centos7-zen3
[+]          ^pmix@4.1.2%aocc@3.2.0~docs+pmi_backwards_compatibility~restful build_system=autotools arch=linux-centos7-zen3
[+]              ^libevent@2.1.12%aocc@3.2.0+openssl build_system=autotools arch=linux-centos7-zen3
```

### Error message

<details><summary>Error message</summary><pre>
==> amdlibflame: Executing phase: 'autoreconf'
==> amdlibflame: Executing phase: 'configure'
==> amdlibflame: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16' 'V=1'
4 errors found in build log:
     11862    /scratch/optpar01/spack/lib/spack/env/aocc/clang -march=native -O3 -fPIC -D_POSIX_C_SOURCE=200809L -DHAVE_CONFIG_H -DBLIS1_FROM_LIBFLAME -I./include/x86_64-unknown-linux-gnu -I/tmp/optpar01/spack-stage/spack-stage-amdlibflame-3.2-ppszgnoeige7rz3vtdrekf76gwlpllwi/spack-src/src/map/lapack2flamec/ -I/tmp/op
              tpar01/spack-stage/spack-stage-amdlibflame-3.2-ppszgnoeige7rz3vtdrekf76gwlpllwi/spack-src/src/map/lapack2flamec/f2c/install/util/io/ -Isrc/lapacke/LAPACKE/include -c /tmp/optpar01/spack-stage/spack-stage-amdlibflame-3.2-ppszgnoeige7rz3vtdrekf76gwlpllwi/spack-src/src/lapack/util/app/qutinc/front/flamec/FL
              A_Apply_Q_UT_inc_lhfc.c -o obj/x86_64-unknown-linux-gnu/src/lapack/util/app/qutinc/front/flamec/FLA_Apply_Q_UT_inc_lhfc.o
     11863    /scratch/optpar01/spack/lib/spack/env/aocc/clang -march=native -O3 -fPIC -D_POSIX_C_SOURCE=200809L -DHAVE_CONFIG_H -DBLIS1_FROM_LIBFLAME -I./include/x86_64-unknown-linux-gnu -I/tmp/optpar01/spack-stage/spack-stage-amdlibflame-3.2-ppszgnoeige7rz3vtdrekf76gwlpllwi/spack-src/src/map/lapack2flamec/ -I/tmp/op
              tpar01/spack-stage/spack-stage-amdlibflame-3.2-ppszgnoeige7rz3vtdrekf76gwlpllwi/spack-src/src/map/lapack2flamec/f2c/install/util/io/ -Isrc/lapacke/LAPACKE/include -c /tmp/optpar01/spack-stage/spack-stage-amdlibflame-3.2-ppszgnoeige7rz3vtdrekf76gwlpllwi/spack-src/src/lapack/util/app/qutinc/front/flamec/FL
              A_Apply_Q_UT_inc_lnfc.c -o obj/x86_64-unknown-linux-gnu/src/lapack/util/app/qutinc/front/flamec/FLA_Apply_Q_UT_inc_lnfc.o
     11864    /scratch/optpar01/spack/lib/spack/env/aocc/clang -march=native -O3 -fPIC -D_POSIX_C_SOURCE=200809L -DHAVE_CONFIG_H -DBLIS1_FROM_LIBFLAME -I./include/x86_64-unknown-linux-gnu -I/tmp/optpar01/spack-stage/spack-stage-amdlibflame-3.2-ppszgnoeige7rz3vtdrekf76gwlpllwi/spack-src/src/map/lapack2flamec/ -I/tmp/op
              tpar01/spack-stage/spack-stage-amdlibflame-3.2-ppszgnoeige7rz3vtdrekf76gwlpllwi/spack-src/src/map/lapack2flamec/f2c/install/util/io/ -Isrc/lapacke/LAPACKE/include -c /tmp/optpar01/spack-stage/spack-stage-amdlibflame-3.2-ppszgnoeige7rz3vtdrekf76gwlpllwi/spack-src/src/lapack/util/app/qutinc/lhfc/flamec/FLA
              _Apply_Q_UT_inc_lhfc_blk_var1.c -o obj/x86_64-unknown-linux-gnu/src/lapack/util/app/qutinc/lhfc/flamec/FLA_Apply_Q_UT_inc_lhfc_blk_var1.o
     11865    /scratch/optpar01/spack/lib/spack/env/aocc/clang -march=native -O3 -fPIC -D_POSIX_C_SOURCE=200809L -DHAVE_CONFIG_H -DBLIS1_FROM_LIBFLAME -I./include/x86_64-unknown-linux-gnu -I/tmp/optpar01/spack-stage/spack-stage-amdlibflame-3.2-ppszgnoeige7rz3vtdrekf76gwlpllwi/spack-src/src/map/lapack2flamec/ -I/tmp/op
              tpar01/spack-stage/spack-stage-amdlibflame-3.2-ppszgnoeige7rz3vtdrekf76gwlpllwi/spack-src/src/map/lapack2flamec/f2c/install/util/io/ -Isrc/lapacke/LAPACKE/include -c /tmp/optpar01/spack-stage/spack-stage-amdlibflame-3.2-ppszgnoeige7rz3vtdrekf76gwlpllwi/spack-src/src/lapack/util/app/qutinc/lnfc/flamec/FLA
              _Apply_Q_UT_inc_lnfc_blk_var1.c -o obj/x86_64-unknown-linux-gnu/src/lapack/util/app/qutinc/lnfc/flamec/FLA_Apply_Q_UT_inc_lnfc_blk_var1.o
     11866    ar cr lib/x86_64-unknown-linux-gnu/libflame.a @lib/x86_64-unknown-linux-gnu/libflame.a.in
     11867    /scratch/optpar01/spack/lib/spack/env/aocc/clang -shared -Wl,-soname,libflame.so.3 -o ./lib/x86_64-unknown-linux-gnu/libflame.so @lib/x86_64-unknown-linux-gnu/libflame.so.in -L/scratch/optpar01/spack/opt/spack/linux-centos7-zen3/aocc-3.2.0/amdblis-3.2-yjelwac3t3lalr3aygl7yqoaet6x3lj3/lib -L/usr/lib/gcc/x
              86_64-redhat-linux/4.8.5 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/scratch/optpar01/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/aocc-3.2.0-7dhpyrigxngiyr4cm24ddurafwiq7hs3/bin/../lib -L/lib -L/usr/lib -lblis-mt -lflangmain -lflang -lflangrti -
              lpgmath -lquadmath -lompstub -lm -lrt -lpthread
     11868    ar: @@lib/x86_64-unknown-linux-gnu/libflame.a.in: No such file or directory
     11869    make: *** [lib/x86_64-unknown-linux-gnu/libflame.a] Error 1
     11870    make: *** Waiting for unfinished jobs....
     11871    clang-13: error: no such file or directory: '@@lib/x86_64-unknown-linux-gnu/libflame.so.in'
     11872    make: *** [lib/x86_64-unknown-linux-gnu/libflame.so] Error 1
</pre></details>

### Information on your system

* **Spack:** 0.19.1
* **Python:** 3.6.8
* **Platform:** linux-centos7-zen3
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/10728060/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/10728063/spack-build-out.txt)

Since the problem is with ```amdlibflame```, I tried to slate src build packages with binaries provided by AMD via ```packages.yaml```
```
 packages:
   amdblis:
     externals:
         - spec: "amdblis@3.2.0 %aocc@3.2.0 arch=linux-centos7-zen3"
           prefix: "/scratch/optpar01/work/2023/03-numa_balancing/aocl/3.2.0"
   amdfftw:
     externals:
         - spec: "amdfftw@3.2.0 %aocc@3.2.0 arch=linux-centos7-zen3"
           prefix: "/scratch/optpar01/work/2023/03-numa_balancing/aocl/3.2.0"
   amdlibflame:
     externals:
         - spec: "amdlibflame@3.2.0 %aocc@3.2.0 arch=linux-centos7-zen3"
           prefix: "/scratch/optpar01/work/2023/03-numa_balancing/aocl/3.2.0"
   amdscalapack:
     externals:
         - spec: "amdscalapack@3.2.0 %aocc@3.2.0 arch=linux-centos7-zen3"
           prefix: "/scratch/optpar01/work/2023/03-numa_balancing/aocl/3.2.0"
```
Here there was a different error related to incomplete LAPACK
```
1 error found in build log:
     55    -- Looking for Fortran cheev
     56    -- Looking for Fortran cheev - found
     57    -- Found LAPACK: /scratch/optpar01/work/2023/03-numa_balancing/aocl/3.2.0/lib/libflame.so;/scratch/optpar01/work/2023/03-numa_balancing/aocl/3.2.0/
           lib/libblis.so
     58    -- Found LAPACK: /scratch/optpar01/work/2023/03-numa_balancing/aocl/3.2.0/lib/libblis.so;/scratch/optpar01/work/2023/03-numa_balancing/aocl/3.2.0/l
           ib/libflame.so;/scratch/optpar01/work/2023/03-numa_balancing/aocl/3.2.0/lib/libblis.so;/scratch/optpar01/spack/opt/spack/linux-centos7-x86_64_v3/gc
           c-4.8.5/aocc-3.2.0-7dhpyrigxngiyr4cm24ddurafwiq7hs3/lib/libomp.so;/scratch/optpar01/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/aocc-3.2.0-7d
           hpyrigxngiyr4cm24ddurafwiq7hs3/lib/libomp.so
     59    -- Looking for Fortran zhpev
     60    -- Looking for Fortran zhpev - not found
     61    CMake Error at CMakeLists.txt:454 (message):
     62      Incomplete LAPACK! function zhpev not found!
     63    
     64    
     65    -- Configuring incomplete, errors occurred!
     66    See also "/tmp/optpar01/spack-stage/spack-stage-quantum-espresso-7.1-qjcljb5kaiauuinf7fiejnoar334qpmr/spack-build-qjcljb5/CMakeFiles/CMakeOutput.lo
           g".
     67    See also "/tmp/optpar01/spack-stage/spack-stage-quantum-espresso-7.1-qjcljb5kaiauuinf7fiejnoar334qpmr/spack-build-qjcljb5/CMakeFiles/CMakeError.log
           ".
```
@bellenlau  @danielecesarini  @ye-luo please kindly take a look. 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by ye-luo** [comment]
Could you provide the two files?
```
/tmp/optpar01/spack-stage/spack-stage-quantum-espresso-7.1-qjcljb5kaiauuinf7fiejnoar334qpmr/spack-build-qjcljb5/CMakeFiles/CMakeOutput.log
/tmp/optpar01/spack-stage/spack-stage-quantum-espresso-7.1-qjcljb5kaiauuinf7fiejnoar334qpmr/spack-build-qjcljb5/CMakeFiles/CMakeError.log
```

**Comment by vitduck** [comment]
[CMakeError.log](https://github.com/spack/spack/files/10762180/CMakeError.log)
[CMakeOutput.log](https://github.com/spack/spack/files/10762181/CMakeOutput.log)

Here are the files that you requested. Sorry I should have attached them as well.

**Comment by ye-luo** [comment]
In [CMakeError.log](https://github.com/spack/spack/files/10762180/CMakeError.log)
```
Determining if the Fortran zhpev exists failed with the following output:
Change Dir: /tmp/optpar01/spack-stage/spack-stage-quantum-espresso-7.1-qjcljb5kaiauuinf7fiejnoar334qpmr/spack-build-qjcljb5/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/gmake -f Makefile cmTC_51fb3/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_51fb3.dir/build.make CMakeFiles/cmTC_51fb3.dir/build
gmake[1]: Entering directory `/tmp/optpar01/spack-stage/spack-stage-quantum-espresso-7.1-qjcljb5kaiauuinf7fiejnoar334qpmr/spack-build-qjcljb5/CMakeFiles/CMakeTmp'
Building Fortran object CMakeFiles/cmTC_51fb3.dir/testFortranCompiler.f.o
/scratch/optpar01/spack/opt/spack/linux-centos7-zen3/aocc-3.2.0/openmpi-4.1.1-epue44putimgwsv4mxorqhm444mkiovp/bin/mpif90    -c /tmp/optpar01/spack-stage/spack-stage-quantum-espresso-7.1-qjcljb5kaiauuinf7fiejnoar334qpmr/spack-build-qjcljb5/CMakeFiles/CMakeTmp/testFortranCompiler.f -o CMakeFiles/cmTC_51fb3.dir/testFortranCompiler.f.o
Linking Fortran executable cmTC_51fb3
/scratch/optpar01/spack/opt/spack/linux-centos7-zen3/aocc-3.2.0/cmake-3.24.3-iwbihggz3v3oyxc7iaec7rqgxsf2t5tx/bin/cmake -E cmake_link_script CMakeFiles/cmTC_51fb3.dir/link.txt --verbose=1
/scratch/optpar01/spack/opt/spack/linux-centos7-zen3/aocc-3.2.0/openmpi-4.1.1-epue44putimgwsv4mxorqhm444mkiovp/bin/mpif90 CMakeFiles/cmTC_51fb3.dir/testFortranCompiler.f.o -o cmTC_51fb3  -Wl,-rpath,/scratch/optpar01/work/2023/03-numa_balancing/aocl/3.2.0/lib /scratch/optpar01/work/2023/03-numa_balancing/aocl/3.2.0/lib/libblis.so /scratch/optpar01/work/2023/03-numa_balancing/aocl/3.2.0/lib/libflame.so /scratch/optpar01/work/2023/03-numa_balancing/aocl/3.2.0/lib/libblis.so /scratch/optpar01/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/aocc-3.2.0-7dhpyrigxngiyr4cm24ddurafwiq7hs3/lib/libomp.so /scratch/optpar01/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/aocc-3.2.0-7dhpyrigxngiyr4cm24ddurafwiq7hs3/lib/libomp.so /scratch/optpar01/work/2023/03-numa_balancing/aocl/3.2.0/lib/libflame.so /scratch/optpar01/spack/opt/spack/linux-centos7-x86_64_v3/gcc-4.8.5/aocc-3.2.0-7dhpyrigxngiyr4cm24ddurafwiq7hs3/lib/libomp.so 
ld.lld: error: /scratch/optpar01/work/2023/03-numa_balancing/aocl/3.2.0/lib/libflame.so: undefined reference to powf@GLIBC_2.27 [--no-allow-shlib-undefined]
```

So libframe has a dependency on glibc for the function powf. The libflame was packaged with glibc 2.27 but your OS glibc seems old. centos 7 ships glibc 2.17. My advice is never ever attempt to upgrade glibc on your computer because glibc is so fundamental and tightly coupled to the OS. Here are your choices
1) upgrade OS
2) build your own libflame
3) use blas/lapack alternatives like openblas.
