### ISSUE TITLE
inconsistent path used for site scoped compilers.yaml depending on whether SPACK_DISABLE_LOCAL_CONFIG=1 is set

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#35480]
### Steps to reproduce

The path used for the site-scoped compilers.yaml is different depending on whether one uses `spack config --scope site edit compilers` or `SPACK_DISABLE_LOCAL_CONFIG=1 spack config edit compilers`

1.
```
$> spack config --scope site edit compilers
# $SPACK_ROOT/etc/spack/compilers.yaml
```

2.
```
$> SPACK_DISABLE_LOCAL_CONFIG=1 spack config edit compilers
# $SPACK_ROOT/etc/spack/darwin/compilers.yaml
```

### Information on your system

* **Spack:** 0.20.0.dev0 (3430c55b0a0701bfb2149dcab659eeaa483447d1)
* **Python:** 3.9.6
* **Platform:** darwin-ventura-m1
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Not sure I get where is the bug:
```console
% spack config --scope site edit compilers
# ~/PycharmProjects/spack/etc/spack/compilers.yaml
% spack config --scope site/linux edit compilers
# ~/PycharmProjects/spack/etc/spack/linux/compilers.yaml
```
I think the default is just to use platform specific subscopes.

**Comment by eugeneswalker** [comment]
> Not sure I get where is the bug:
> 
> ```
> % spack config --scope site edit compilers
> # ~/PycharmProjects/spack/etc/spack/compilers.yaml
> % spack config --scope site/linux edit compilers
> # ~/PycharmProjects/spack/etc/spack/linux/compilers.yaml
> ```
> 
> I think the default is just to use platform specific subscopes.

OK. I didn't realize there was such a thing as `site/linux` scope! I think this is a nothing burger then, do you agree?

**Comment by alalazo** [comment]
Yeah, if you agree we can close this issue.
