### ISSUE TITLE
Metadata under <prefix>/.spack should be filtered on relocation

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#35486]
### Steps to reproduce

If we generate a module file from a package that was relocated from a buildcache we get the original path with placeholders in the package description:
![Screenshot from 2023-02-08 21-19-36](https://user-images.githubusercontent.com/4199709/218979649-f4b3b156-3069-4fec-9456-9a9efa9999b3.png)

### Error message

There is no error message, just an unexpectedly verbose output for anything that relies on the content of:
```
<prefix>/.spack/spack-configure-args.txt
```
and similar files. These files should probably be filtered too on relocation.

### Information on your system

Not platform specific, but the screenshot was obtained on the `spack/tutorial:cineca23` docker image.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by wspear** [comment]
In addition to module generation I believe this issue causes some spack tests to fail. @tldahlgren @eugeneswalker
