### ISSUE TITLE
Missing py-etils in 0.19+

### ISSUE THREAD

**Issue by hallamt0uring** [LLNL/spack#35496]
### Steps to reproduce

vim \~spack_18.1/var/spack/repos/builtin/packages/py-etils/package.py

### Information on your system

According to the the online list of packages py-etils is meant to be there.  I have just upgraded to 0.19.1, and the boss has 0.19.0.  Both have no py-etils package included

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by adamjstewart** [comment]
py-etils was added in #33876 which is in develop but has not yet made it to a stable release. If you're referring to https://spack.readthedocs.io/en/latest/package_list.html, those are the docs for develop, see https://spack.readthedocs.io/en/v0.19.1/package_list.html for the 0.19.1 docs.
