### ISSUE TITLE
Namespace is ignored depending on the repo order in repos.yaml

### ISSUE THREAD

**Issue by pab42** [LLNL/spack#35536]
### Steps to reproduce

We want to have the same package (e.g. `zlib` here) in two repos, where the `builtin` repository is the default one and `myrepo` to have less priority. 
I start from scratch:
```console
$ cd $SCRATCH
$ git clone -c feature.manyFiles=true https://github.com/spack/spack.git
$ cd spack/
$ . share/spack/setup-env.sh
```
I create my new repository:
```console
$ spack repo create myrepo
$ spack repo add $SCRATCH/spack/myrepo
```
but I want the `builtin` repo to be the default:
```console
# Change the order of the repos:
$ spack config edit repos
# to
$ spack config get repos 
repos:
- $spack/var/spack/repos/builtin
- $spack/myrepo
```
Now I copy from the `builtin` repository to `myrepo` and install the package from `myrepo`:
```console
$ cp -r var/spack/repos/builtin/packages/zlib myrepo/packages/
$ spack install myrepo.zlib
$ spack find -N
-- linux-sles15-haswell / gcc@7.5.0 -----------------------------
builtin.zlib@1.2.13
==> 1 installed package
```
So the namespace seems to be ignored.
But if I reverse the order of the repos, it installs correctly.
```console
$ spack uninstall zlib
# reverse the order
$ spack config get repos 
repos:
- spack/myrepo
- spack/var/spack/repos/builtin

$ spack install myrepo.zlib
$ spack find -N
-- linux-sles15-haswell / gcc@7.5.0 -----------------------------
myrepo.zlib@1.2.13
==> 1 installed package
```

### Error message

Depending on the order of the repos in the `repos.yaml`:
```console
repos:
- $spack/var/spack/repos/builtin
- $spack/myrepo
```
the namespace in `spack install myrepo.zlib` is ignored (see above). 
Also `spack info myrepo.zlib` shows only the information of the builtin one.
But we want to have the `builtin` repo to be the default one and to be able to install a package from `myrepo` if explicitly stated. Do I miss something here? As far as I understood the documentation, that should be possible.

Attached the debug output of `spack install myrepo.zlib`
```console
repos:
- $spack/myrepo
- $spack/var/spack/repos/builtin
```
[wrong_order.log](https://github.com/spack/spack/files/10768243/wrong_order.log)

Debug output of `spack install myrepo.zlib` with
```console
repos:
- $spack/var/spack/repos/builtin
- $spack/myrepo
```
[correct_order.log](https://github.com/spack/spack/files/10768290/correct_order.log)

### Information on your system

```console
$ spack debug report
* **Spack:** 0.20.0.dev0 (983c68cc30be337bfcd1711bb0b95431fefbb2e1)
* **Python:** 3.6.12
* **Platform:** linux-sles15-haswell
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
I think originally namespaces were meant to act as overlays, even though I am not sure if that is written anywhere. We should probably define the semantic more rigorously, document it and enforce its behavior with tests. @tgamblin @haampie fyi

**Comment by flxmr** [comment]
I'll start adding references, as this seems similar to our problem: https://github.com/spack/spack/issues/33036 

As to your problem: I think the canonical way to edit would be to use `spack edit -N namespace`. For spack to pick up packages from lower-ranked namespaces we successfully used this patch: https://github.com/spack/spack/pull/33053 (and I'd be happy to hear any feedback whether it makes sense to someone besides me ;))

**Comment by alalazo** [comment]
This bug has many duplicates, so raising priority

**Comment by knoepfel** [comment]
Thank you for raising the priority of this issue, @alalazo, as it is an important (and [documented](https://spack.readthedocs.io/en/latest/repositories.html#overriding-built-in-packages)) feature.

**Comment by alalazo** [comment]
I started looking into this today. The nice part is that coding regression tests is kind of easy, based on the reports. The difficult part is the absence of any clear semantic for overridden packages. 

Some notes in random order:
1. Fixing the selection from the command line is doable, even though it is more complicated than one could expect. There are many data structures internally that see a package as a "name". The namespace is disregarded and so there are a few "layers" of code to be fixed.
2. Allowing the use of fully qualified names in directives seems to require a major overhaul. Each `depends_on` directive registers only the name. I wonder if a better approach is to explicitly prohibit to have fully qualified names in directives (right now the use of fully qualified names in directives is likely zero).
3. Allowing the use of different repos for the same package in the same solve is worse than 2. I think it should not be allowed at the moment.

**Comment by alalazo** [comment]
@knoepfel Can you try #41957 and see if it fixes the issue for you?
