### ISSUE TITLE
Installation error: netcdf-c 4.9.0 with hdf5+szip

### ISSUE THREAD

**Issue by climbfuji** [LLNL/spack#35646]
### Steps to reproduce

It seems like the logic dealing with hdf5 variants for netcdf-c (around https://github.com/spack/spack/blob/5c7cccd052e0c899aab3c2a7918c5e3b554abe4a/var/spack/repos/builtin/packages/netcdf-c/package.py#L213) or the hdf5 package itself (`setup_dependent_build_environment`?) need to be fixed if `hdf5` is built with `szip` support.

On a system that has no `szip` development package installed in the default (OS) search paths:
```
> spack spec netcdf-c

Input spec
--------------------------------
netcdf-c

Concretized
--------------------------------
netcdf-c@4.9.0%gcc@10.1.0~byterange+dap~fismahigh~fsync~hdf4~jna+mpi+nczarr+optimize~parallel-netcdf+pic+shared+zstd build_system=autotools arch=linux-sles12-cascadelake
    ^curl@7.37.0%gcc@10.1.0~gssapi+ldap~libidn2~librtmp~libssh2~nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-sles12-cascadelake
    ^hdf5@1.14.0%gcc@10.1.0~cxx+fortran+hl~ipo~java+mpi+shared+szip+threadsafe+tools api=default build_system=cmake build_type=RelWithDebInfo arch=linux-sles12-cascadelake
        ^cmake@3.23.1%gcc@10.1.0~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-sles12-cascadelake
            ^ncurses@5.9.20140201%gcc@10.1.0~symlinks+termlib abi=6 build_system=autotools patches=f84b270 arch=linux-sles12-cascadelake
            ^openssl@1.0.2j-fips%gcc@10.1.0~docs~shared build_system=generic certs=mozilla arch=linux-sles12-cascadelake
        ^libaec@1.0.6%gcc@10.1.0~ipo+shared build_system=cmake build_type=RelWithDebInfo arch=linux-sles12-cascadelake
        ^pkg-config@0.28%gcc@10.1.0+internal_glib build_system=autotools patches=49ffcd6 arch=linux-sles12-cascadelake
    ^libxml2@2.10.3%gcc@10.1.0~python build_system=autotools arch=linux-sles12-cascadelake
        ^libiconv@1.16%gcc@10.1.0 build_system=autotools libs=shared,static arch=linux-sles12-cascadelake
        ^xz@5.0.5%gcc@10.1.0~pic build_system=autotools libs=shared,static arch=linux-sles12-cascadelake
    ^m4@1.4.16%gcc@10.1.0+sigsegv build_system=autotools arch=linux-sles12-cascadelake
    ^openmpi@4.1.3%gcc@10.1.0~atomics~cuda~cxx~cxx_exceptions+gpfs~internal-hwloc~java~legacylaunchers~lustre~memchecker~orterunprefix+pmi+romio+rsh~singularity+static+two_level_namespace+vt+wrapper-rpath build_system=autotools fabrics=ucx schedulers=slurm arch=linux-sles12-cascadelake
    ^zlib@1.2.13%gcc@10.1.0+optimize+pic+shared build_system=makefile arch=linux-sles12-cascadelake
    ^zstd@1.5.2%gcc@10.1.0~programs build_system=makefile libs=shared,static arch=linux-sles12-cascadelake
```
Installing:
```
...
checking whether HDF5 allows parallel filters... yes
checking whether szlib was used when building HDF5... yes
checking whether HDF5 library is version 1.10.6 or later... yes
checking whether parallel I/O is enabled for netcdf-4... yes
checking whether we should enable NCZarr filters... yes
checking whether filter testing should be run... yes
...
libtool: compile:  /usr/local/intel/oneapi/2021/mpi/2021.5.0/bin/mpiicc -DHAVE_CONFIG_H -I. -I/discover/nobackup/projects/jcsda/s2127/spack-stack-feature-r2d2-mysql/cache/build_stage/dheinzel/spack-stage-netcdf-c
-4.9.0-gvbhbjdrsxpw76aa2eoog25uypiwvc5i/spack-src/plugins -I.. -I../include -I/discover/nobackup/projects/jcsda/s2127/spack-stack-feature-r2d2-mysql/cache/build_stage/dheinzel/spack-stage-netcdf-c-4.9.0-gvbhbjdrs
xpw76aa2eoog25uypiwvc5i/spack-src/include -I/discover/nobackup/projects/jcsda/s2127/spack-stack-feature-r2d2-mysql/cache/build_stage/dheinzel/spack-stage-netcdf-c-4.9.0-gvbhbjdrsxpw76aa2eoog25uypiwvc5i/spack-src/
oc2 -I/discover/nobackup/projects/jcsda/s2127/spack-stack-feature-r2d2-mysql/cache/build_stage/dheinzel/spack-stage-netcdf-c-4.9.0-gvbhbjdrsxpw76aa2eoog25uypiwvc5i/spack-src/libnczarr -I/usr/include -I/gpfsm/dnb5
5/projects/p01/s2127/spack-stack-feature-r2d2-mysql/envs/unified-4.0.0-rc1/install/intel/2022.0.1/hdf5-1.14.0-dxn2mci/include -I/gpfsm/dnb55/projects/p01/s2127/spack-stack-feature-r2d2-mysql/envs/unified-4.0.0-rc
1/install/intel/2022.0.1/zstd-1.5.2-anx4pko/include -O2 -fPIC -fno-strict-aliasing -MT NCZhdf5filters.lo -MD -MP -MF .deps/NCZhdf5filters.Tpo -c NCZhdf5filters.c  -fPIC -DPIC -o .libs/NCZhdf5filters.o
libtool: compile:  /usr/local/intel/oneapi/2021/mpi/2021.5.0/bin/mpiicc -DHAVE_CONFIG_H -I. -I/discover/nobackup/projects/jcsda/s2127/spack-stack-feature-r2d2-mysql/cache/build_stage/dheinzel/spack-stage-netcdf-c
-4.9.0-gvbhbjdrsxpw76aa2eoog25uypiwvc5i/spack-src/plugins -I.. -I../include -I/discover/nobackup/projects/jcsda/s2127/spack-stack-feature-r2d2-mysql/cache/build_stage/dheinzel/spack-stage-netcdf-c-4.9.0-gvbhbjdrs
xpw76aa2eoog25uypiwvc5i/spack-src/include -I/discover/nobackup/projects/jcsda/s2127/spack-stack-feature-r2d2-mysql/cache/build_stage/dheinzel/spack-stage-netcdf-c-4.9.0-gvbhbjdrsxpw76aa2eoog25uypiwvc5i/spack-src/
oc2 -I/discover/nobackup/projects/jcsda/s2127/spack-stack-feature-r2d2-mysql/cache/build_stage/dheinzel/spack-stage-netcdf-c-4.9.0-gvbhbjdrsxpw76aa2eoog25uypiwvc5i/spack-src/libnczarr -I/usr/include -I/gpfsm/dnb5
5/projects/p01/s2127/spack-stack-feature-r2d2-mysql/envs/unified-4.0.0-rc1/install/intel/2022.0.1/hdf5-1.14.0-dxn2mci/include -I/gpfsm/dnb55/projects/p01/s2127/spack-stack-feature-r2d2-mysql/envs/unified-4.0.0-rc
1/install/intel/2022.0.1/zstd-1.5.2-anx4pko/include -O2 -fPIC -fno-strict-aliasing -MT H5Zdeflate.lo -MD -MP -MF .deps/H5Zdeflate.Tpo -c H5Zdeflate.c  -fPIC -DPIC -o .libs/H5Zdeflate.o
NCZhdf5filters.c(25): catastrophic error: cannot open source file "szlib.h"
  #include <szlib.h>
                    ^

compilation aborted for NCZhdf5filters.c (code 4)
Makefile:933: recipe for target 'NCZhdf5filters.lo' failed
make[3]: *** [NCZhdf5filters.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
H5Zszip.c(25): catastrophic error: cannot open source file "szlib.h"
  #include <szlib.h>
                    ^
```
@skosukhin What would be your preference for fixing this?

### Error message

See above

### Information on your system

```
> spack debug report
* **Spack:** 0.20.0.dev0 (c80dad5da3edcbebb24ff6036028dd5f44102854)
* **Python:** 3.9.7
* **Platform:** linux-sles12-cascadelake
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA FYI

**Comment by skosukhin** [comment]
I see that `libaec` is installed, so `szlib.h` should be there and available via the Spack compiler wrapper. It looks like the MPI compiler wrappers use the compilers directly though. Maybe #34956 was not enough after all.

Also, the commands in the report look inconsistent: `spack spec netcdf-c` concretizes with `%gcc` but the installation command was called for `%intel` (or `%oneapi`) if I'm not mistaken.

Whatever the installation command was, I'd try to install without MPI: `netcdf-c~mpi~parallel-netcdf ^hdf5~mpi`.

**Comment by climbfuji** [comment]
> I see that `libaec` is installed, so `szlib.h` should be there and available via the Spack compiler wrapper. It looks like the MPI compiler wrappers use the compilers directly though. Maybe #34956 was not enough after all.
> 
> Also, the commands in the report look inconsistent: `spack spec netcdf-c` concretizes with `%gcc` but the installation command was called for `%intel` (or `%oneapi`) if I'm not mistaken.
> 
> Whatever the installation command was, I'd try to install without MPI: `netcdf-c~mpi~parallel-netcdf ^hdf5~mpi`.

Thanks. The intel/gnu mixup was just a copy&paste error, it's an environment that concretizes in exactly the same way for Intel and GNU. But I can't build without MPI, that's not an option.

**Comment by skosukhin** [comment]
> But I can't build without MPI, that's not an option.

I'm sorry, why?

**Comment by climbfuji** [comment]
> > But I can't build without MPI, that's not an option.
> 
> I'm sorry, why?

Well, just for debugging and trying what happens, yes I can. But the environment we need to build must have parallel capabilities in hdf5 and netcdf-c enabled.

**Comment by skosukhin** [comment]
Yes, for debugging only, of course. A successful no-MPI installation would be a good indicator that the problem has to do with the MPI compiler wrappers. The next step will be to check what exactly the wrapper call:
```console
$ spack build-env netcdf-c+mpi <the rest of the spec> -- $SHELL
$ /usr/local/intel/oneapi/2021/mpi/2021.5.0/bin/mpiicc -show
```

**Comment by climbfuji** [comment]
Sorry for the misunderstanding. I'll try those steps and report back.

**Comment by AlexanderRichert-NOAA** [comment]
Not sure it's relevant, but when compiling statically (4.9.0 or 4.9.1, I forget), I ran into the same problem as zlib previously, where it's trying to use "-l/path/to/libaec/lib64/libsz" or something like that.

**Comment by skosukhin** [comment]
I must also admit that the `netcdf-c` spackage is sufficiently broken: a lot of things that "happened" to the configure script of the package in version `4.9.0` are not properly addressed (or worked around, to be blunt) yet. And unfortunately, I don't know when I have time to work on that.

**Comment by climbfuji** [comment]
The build of `netcdf-c~mpi~parallel-netcdf ^hdf5~mpi` went through, and it had `+szip` for `hdf5`.

This is the output of the next set of commands:
```
$ spack build-env netcdf-c+mpi <the rest of the spec> -- $SHELL
$ /usr/local/intel/oneapi/2021/mpi/2021.5.0/bin/mpiicc -show
/usr/local/intel/oneapi/2021/compiler/2022.0.1/linux/bin/intel64/icc -I"/usr/local/intel/oneapi/2021/mpi/2021.5.0/include" -L"/usr/local/intel/oneapi/2021/mpi/2021.5.0/lib/release" -L"/usr/local/intel/oneapi/2021/mpi/2021.5.0/lib" -Xlinker --enable-new-dtags -Xlinker -rpath -Xlinker "/usr/local/intel/oneapi/2021/mpi/2021.5.0/lib/release" -Xlinker -rpath -Xlinker "/usr/local/intel/oneapi/2021/mpi/2021.5.0/lib" -lmpifort -lmpi -ldl -lrt -lpthread
```

**Comment by skosukhin** [comment]
Thank you. The MPI wrappers do not use the Spack compiler wrappers but should and that's the problem. If I am not mistaken, you don't have the aforementioned #34956 in [the version that you have reported](https://github.com/spack/spack/blob/c80dad5da3edcbebb24ff6036028dd5f44102854/var/spack/repos/builtin/packages/intel-oneapi-mpi/package.py#L117-L121).

**Comment by climbfuji** [comment]
> Thank you. The MPI wrappers do not use the Spack compiler wrappers but should and that's the problem. If I am not mistaken, you don't have the aforementioned #34956 in [the version that you have reported](https://github.com/spack/spack/blob/c80dad5da3edcbebb24ff6036028dd5f44102854/var/spack/repos/builtin/packages/intel-oneapi-mpi/package.py#L117-L121).

Brilliant, that was it! Thanks very much. I can confirm that it's working if I cherry-pick the change from #34956. Thanks for your help.
