### ISSUE TITLE
strange issues with openmpi

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#3567]
i was reinstalling the software stack and used the current openmpi and got this when trying to use it outside of Spack:
```
$ mpirun -v
PMIx has detected a temporary directory name that results
in a path that is too long for the Unix domain socket:

    Temp dir: /var/folders/5k/sqpp24tx3ylds4fgm13pfht00000gn/T/openmpi-sessions-501@MacBook-Pro-<USER>_0/25440

Try setting your TMPDIR environmental variable to point to
something shorter in length
```

**Comment by davydden** [comment]
probably it's something with the new version of `openmpi`, fixed by setting `TMPDIR`, no idea why it did not complain before.

**Comment by davydden** [comment]
there is even a special issue on OpenMPI FAQ https://www.open-mpi.org/faq/?category=osx#startup-errors-with-open-mpi-2.0.x  strangely, i never came across this problem. Either way - it's not related to Spack.

**Comment by tgamblin** [comment]
@davydden: Mac OS X has some pretty weird, long temp directory names by default.  This might not be Spack's fault, but if there is some config file that we could patch in OpenMPI by default, to make it use a shorter tmp name, then we could add that to the package.

The default `TMPDIR` has the advantage that it is only owned by you, but the OpenMPI guys recommend to set it to `/tmp` as on other systems, for lack of other options.
