### ISSUE TITLE
[site-specific] Multiple spack installs are confusing dotkit

### ISSUE THREAD

**Issue by alfredo-gimenez** [LLNL/spack#357]
I was getting errors trying to `spack use` on a system where multiple spack installs are available. My local spack is in `~/src/spack` but there is a global spack in `/collab/usr/global/tools/spack/`. I want to use my local install exclusively, but it seems the global one is still causing conflicts for dotkit resolution.

In my `~/.bashrc` I execute `. ~/src/spack/share/spack/setup-env.sh` and I do not do anything with the global install. However, `use` still uses the global spack install.

Here is an example:

```
$ use -l spack
spack ----------
         git-2.2.1 - git @2.2.1
```

But git is not actually installed locally:

```
$ spack find git
==> 0 installed packages.
```

Let's see what `use` is finding:

```
$ use git-2.2.1
Prepending: git-2.2.1 (ok)
$ which use
/collab/usr/global/tools/spack/opt/chaos_5_x86_64_ib/gcc@4.4.7/git@2.2.1-ad2560bb/bin/git
```

Sure enough, `use` is using the global spack install. Furthermore, none of my locally installed spack packages are available:

```
$ spack find hwloc
==> 1 installed packages.
-- chaos_5_x86_64_ib / gcc@4.4.7 --------------------------------
hwloc@1.11.2
$ spack use hwloc
Prepending: hwloc@1.11.2%gcc@4.4.7-3cntzof (not found)
$ use -l spack
spack ----------
         git-2.2.1 - git @2.2.1
```

As you can see, local spack installs are not showing up at all in `use`. 

Is there a way to point `use` to a specific spack install? Or an alternative fix? I deleted `~/.spack` and `~/.spackconfig` and cleaned my spack install completely, am on the latest develop branch.

**Comment by alfredo-gimenez** [comment]
Looks like this is possibly related to bug #44

**Comment by mathstuf** [comment]
Does the global spack add any paths to the `use` tool via `/etc` or something? Is there an environment variable `dotkit` uses to add to its module paths?

**Comment by tgamblin** [comment]
@mathstuf: `DK_NODE`

**Comment by mathstuf** [comment]
I'd guess that `DK_NODE` is set somewhere else and needs to be pruned of system-related bits before a specific Spack root could be used.

**Comment by adamjstewart** [comment]
@alfredo-gimenez It sounds like you just need to clean up your `DK_NODE` and things should work properly. You can reopen this issue if that doesn't solve the problem.
