### ISSUE TITLE
Installation issue: Can't install on Linux RHEL 6.10

### ISSUE THREAD

**Issue by nckwcq** [LLNL/spack#35742]
### Steps to reproduce the issue

```console
$ spack spec -I <spec>
...
```
git clone https://github.com/spack/spack.git
. spack/share/spack/setup-env.sh
git install openblas

### Error message

<details><summary>Error message</summary><pre>
...
</pre></details>

==> Installing patchelf-0.13.1-zmfstawaab72t3maxm2yg6bfc6g5kdh6
==> No binary for patchelf-0.13.1-zmfstawaab72t3maxm2yg6bfc6g5kdh6 found: installing from source
==> Error: Failed to install patchelf due to PermissionError: [Errno 13] Permission denied: '/u/ap/cho/.spack/bootstrap/store/linux-rhel6-x86_64/gcc-7.3.1/patchelf-0.13.1-zmfstawaab72t3maxm2yg6bfc6g5kdh6'
==> Error: cannot bootstrap any of the patchelf executables from spec "patchelf@0.13.1:0.13 %gcc target=x86_64" due to the following failures:
github-actions-v0.4 raised PermissionError: [Errno 13] Permission denied: '/u/ap/cho/.spack/bootstrap/store/linux-centos7-x86_64/gcc-10.2.1/patchelf-0.16.1-p72zyan5wrzuabtmzq7isa5mzyh6ahdp'
github-actions-v0.3 raised CannotGrowString: Cannot replace b'/home/spack/spack/opt/spack/linux-centos7-x86_64/gcc-10.2.1/patchelf-0.15.0-htk62k7efo2z22kh6kmhaselru7bfkuc' with b'/u/ap/cho/.spack/bootstrap/store/linux-centos7-x86_64/gcc-10.2.1/patchelf-0.15.0-htk62k7efo2z22kh6kmhaselru7bfkuc' because the new prefix is longer. To fix this, compile with more padding (config:install_tree:padded_length), or install to a shorter prefix.
spack-install raised PermissionError: [Errno 13] Permission denied: '/u/ap/cho/.spack/bootstrap/store/linux-rhel6-x86_64/gcc-7.3.1/patchelf-0.13.1-zmfstawaab72t3maxm2yg6bfc6g5kdh6'

### Information on your system

* **Spack:** 0.20.0.dev0
* **Python:** 3.8.8
* **Platform:** linux-rhel6-sandybridge
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/10854616/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/10854617/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by nckwcq** [comment]
I fixed the prefix length problem. Another error appears while doing `spack install openblas`, something to do with ncurses install.

  >> 3746    /sbin/ldconfig: Can't create temporary cache file /etc/ld.so.cache~: Permission denied
  >> 3747    make[1]: [Makefile:433: /u/ap/cho/spack/store/linux-rhel6-sandybridge/gcc-7.3.1/ncurses-6.4-exp3nlkxi5r25nvpied5cg7qoiijocwl/lib/libform.so.6.4] Error 1 (ignored)

**Comment by nckwcq** [comment]
I was able to install openblas on a newer system running Centos. Not sure if the problem before was "Centos vs Redhat" or "gpfs vs afs" or "new vs old" system.

**Comment by nckwcq** [comment]
Problem fixed.

**Comment by alalazo** [comment]
RHEL 6 is too old for the current Spack, and we kind of removed official support for it when we dropped support for Python 2.6 For instance, the binaries to bootstrap clingo are built on a manylinux2014 image, which is a `centos7` - so already newer than a RHEL 6. Closing this for now, but feel free to reopen if you think there are other issues.
