### ISSUE TITLE
coreutils@8.23 fails with "Too many levels of symbolic links"

### ISSUE THREAD

**Issue by samfux84** [LLNL/spack#3580]
This seems to be the same problem as described in #3387 for the patch package.

Adding

build_directory = 'spack-build'

to the coreutils package seems to solve the problem. I am sorry for not providing directly a pull request. I am new to spack and not used to work with git yet (still have to learn that).

**Comment by adamjstewart** [comment]
Fixed by #3543. If you update to the latest develop branch you should be good to go.
