### ISSUE TITLE
Installation issue: py-gsd

### ISSUE THREAD

**Issue by luke-dt** [LLNL/spack#35806]
### Steps to reproduce the issue

```console
$ spack install py-gsd
```

### Error message

<details><summary>Error message</summary><pre>
==> Installing py-gsd-1.9.3-h4cegq774xlwmco7klj33fsc5i7ioj2i
==> No binary for py-gsd-1.9.3-h4cegq774xlwmco7klj33fsc5i7ioj2i found: installing from source
==> Using cached archive: /home/luke/GitHub/spack/var/spack/cache/_source-cache/archive/c6/c6b37344e69020f69fda2b8d97f894cb41fd720840abeda682edd680d1cff838.tar.gz
==> No patches needed for py-gsd
==> py-gsd: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    '/home/luke/GitHub/spack/opt/spack/linux-fedora37-zen3/gcc-12.2.1/python-3.10.8-2mi2jzwov5vq5so2xgoddrf2p446cpt2/bin/python3.10' '-m' 'pip' '-vvv' '--no-input' '--no-cache-dir' '--disable-pip-version-check' 'install' '--no-deps' '--ignore-installed' '--no-build-isolation' '--no-warn-script-location' '--no-index' '--prefix=/home/luke/GitHub/spack/opt/spack/linux-fedora37-zen3/gcc-12.2.1/py-gsd-1.9.3-h4cegq774xlwmco7klj33fsc5i7ioj2i' '.'

4 errors found in build log:
     11    Created temporary directory: /tmp/pip-install-1urq3o72
     12    Processing /home/luke/GitHub/spack/var/spack/stage/spack-stage-py-gsd-1.9.3-h4cegq774xlwmco7klj33fsc5i7ioj2i/spack-src
     13      Added file:///home/luke/GitHub/spack/var/spack/stage/spack-stage-py-gsd-1.9.3-h4cegq774xlwmco7klj33fsc5i7ioj2i/spack-src to build tracker '/tmp/
           pip-build-tracker-vbj95wiw'
     14      Created temporary directory: /tmp/pip-modern-metadata-hx_c47ki
     15      Preparing metadata (pyproject.toml): started
     16      Running command Preparing metadata (pyproject.toml)
  >> 17    /home/luke/GitHub/spack/opt/spack/linux-fedora37-zen3/gcc-12.2.1/py-setuptools-59.4.0-sgaysa525qqzixodzjkz4vsr3qhfrn47/lib/python3.10/site-package
           s/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the undersc
           ore name 'description_file' instead
     18        warnings.warn(
     19      running dist_info
     20      creating /tmp/pip-modern-metadata-hx_c47ki/gsd.egg-info
     21      writing /tmp/pip-modern-metadata-hx_c47ki/gsd.egg-info/PKG-INFO
     22      writing dependency_links to /tmp/pip-modern-metadata-hx_c47ki/gsd.egg-info/dependency_links.txt
     23      writing requirements to /tmp/pip-modern-metadata-hx_c47ki/gsd.egg-info/requires.txt

     ...

     36    Created temporary directory: /tmp/pip-unpack-k27nk2gs
     37    Building wheels for collected packages: gsd
     38      Created temporary directory: /tmp/pip-wheel-ba3chaze
     39      Destination directory: /tmp/pip-wheel-ba3chaze
     40      Building wheel for gsd (pyproject.toml): started
     41      Running command Building wheel for gsd (pyproject.toml)
  >> 42    /home/luke/GitHub/spack/opt/spack/linux-fedora37-zen3/gcc-12.2.1/py-setuptools-59.4.0-sgaysa525qqzixodzjkz4vsr3qhfrn47/lib/python3.10/site-package
           s/setuptools/dist.py:717: UserWarning: Usage of dash-separated 'description-file' will not be supported in future versions. Please use the undersc
           ore name 'description_file' instead
     43        warnings.warn(
     44      running bdist_wheel
     45      running build
     46      running build_py
     47      creating build
     48      creating build/lib.linux-x86_64-3.10

     ...

     60                       from /home/luke/GitHub/spack/opt/spack/linux-fedora37-zen3/gcc-12.2.1/py-numpy-1.23.5-ay2ay5trocmvit5y7rsoqv6m6jpmwlxh/lib/pyth
           on3.10/site-packages/numpy/core/include/numpy/arrayobject.h:5,
     61                       from gsd/fl.c:601:
     62      /home/luke/GitHub/spack/opt/spack/linux-fedora37-zen3/gcc-12.2.1/py-numpy-1.23.5-ay2ay5trocmvit5y7rsoqv6m6jpmwlxh/lib/python3.10/site-packages/n
           umpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED
           _API NPY_1_7_API_VERSION" [-Wcpp]
     63         17 | #warning "Using deprecated NumPy API, disable it with " \
     64            |  ^~~~~~~
     65      gsd/fl.c: In function '__pyx_tp_dealloc_3gsd_2fl_GSDFile':
  >> 66    gsd/fl.c:12401:5: error: lvalue required as increment operand
     67      12401 |     ++Py_REFCNT(o);
     68            |     ^~
  >> 69      gsd/fl.c:12403:5: error: lvalue required as decrement operand
     70      12403 |     --Py_REFCNT(o);
     71            |     ^~
     72      gsd/fl.c: In function '__Pyx_ParseOptionalKeywords':
     73      gsd/fl.c:14420:21: warning: '_PyUnicode_get_wstr_length' is deprecated [-Wdeprecated-declarations]
     74      14420 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
     75            |                     ^

See build log for details:
  /home/luke/GitHub/spack/var/spack/stage/spack-stage-py-gsd-1.9.3-h4cegq774xlwmco7klj33fsc5i7ioj2i/spack-build-out.txt
</pre></details>

### Information on your system

* **Spack:** 0.20.0.dev0 (942494a7cb7f72f8efe0034f076cd88fa4d06704)
* **Python:** 3.11.2
* **Platform:** linux-fedora37-zen3
* **Concretizer:** clingo

### Additional information

[spack-build-01-install-out.txt](https://github.com/spack/spack/files/10877621/spack-build-01-install-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
No idea. I would suggest trying to update the package to the latest version. If the bug still exists in the latest version, report it to https://github.com/glotzerlab/gsd.

**Comment by luke-dt** [comment]
Thanks for the suggestion. I dug into it a little and it does appear to be related to a very out-of-date numpy requirement which should be fixed in a more modern release. I'll work on a PR with updated versions for this and a related package.

**Comment by adamjstewart** [comment]
You can also add an upper bound on the numpy dependency if you want to get the old version working, up to you.

**Comment by adamjstewart** [comment]
Does #35827 help?

**Comment by luke-dt** [comment]
ooo, I'll try that. I haven't gotten around to addressing this because a separate problem came up

**Comment by luke-dt** [comment]
fixed by https://github.com/spack/spack/pull/35827
