### ISSUE TITLE
Installation issue: binutils

### ISSUE THREAD

**Issue by omsai** [LLNL/spack#35817]
### Steps to reproduce the issue

```console
$ spack spec -I binutils
Input spec
--------------------------------
 -   binutils

Concretized
--------------------------------
 -   binutils@2.40%apple-clang@13.1.6~gprofng~headers~interwork~ld~libiberty~lto~nls~pgo+plugins build_system=autotools libs=shared,static arch=darwin-ventura-skylake
[+]      ^diffutils@3.8%apple-clang@13.1.6 build_system=autotools arch=darwin-ventura-skylake
[+]          ^libiconv@1.17%apple-clang@13.1.6 build_system=autotools libs=shared,static arch=darwin-ventura-skylake
[+]      ^texinfo@7.0%apple-clang@13.1.6 build_system=autotools arch=darwin-ventura-skylake
[+]          ^gettext@0.21.1%apple-clang@13.1.6+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=darwin-ventura-skylake
[+]              ^bzip2@1.0.8%apple-clang@13.1.6~debug~pic+shared build_system=generic arch=darwin-ventura-skylake
[+]              ^libxml2@2.10.3%apple-clang@13.1.6~python build_system=autotools arch=darwin-ventura-skylake
[+]              ^tar@1.34%apple-clang@13.1.6 build_system=autotools zip=pigz arch=darwin-ventura-skylake
[+]                  ^pigz@2.7%apple-clang@13.1.6 build_system=makefile arch=darwin-ventura-skylake
[+]                  ^zstd@1.5.2%apple-clang@13.1.6+programs build_system=makefile compression=none libs=shared,static arch=darwin-ventura-skylake
[+]              ^xz@5.4.1%apple-clang@13.1.6~pic build_system=autotools libs=shared,static arch=darwin-ventura-skylake
[+]          ^ncurses@6.4%apple-clang@13.1.6~symlinks+termlib abi=none build_system=autotools arch=darwin-ventura-skylake
[+]              ^pkgconf@1.8.0%apple-clang@13.1.6 build_system=autotools arch=darwin-ventura-skylake
[+]          ^perl@5.36.0%apple-clang@13.1.6+cpanm+open+shared+threads build_system=generic arch=darwin-ventura-skylake
[+]              ^berkeley-db@18.1.40%apple-clang@13.1.6+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=darwin-ventura-skylake
[+]              ^gdbm@1.23%apple-clang@13.1.6 build_system=autotools arch=darwin-ventura-skylake
[+]                  ^readline@8.2%apple-clang@13.1.6 build_system=autotools patches=bbf97f1 arch=darwin-ventura-skylake
[+]      ^zlib@1.2.13%apple-clang@13.1.6+optimize+pic+shared build_system=makefile arch=darwin-ventura-skylake
```

### Error message

<details><summary>Error message</summary>

<pre>$ spack install --jobs 1 binutils
[...]
==> binutils: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j1' 'V=1'
 
6 errors found in build log:
     2498    /bin/sh ./libtool  --tag=CC   --mode=link /Users/pnanda/src/spack-vanilla/lib/spack/env/clang/clang -std=gnu99 -Wall -W -Wall -Wno-narrowing -Wwrite-strings -Wmissing-format-attribute -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition -pedantic -Wno-long-long   -g -O2     -version-info 0:0:0  -export-symbols-regex ctf_.*  -o libctf-nobfd.la -rpath /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/binutils-2.40-uxdvmda6dkfokfbe4dwahfc62kdnfw3c/lib libctf_nobfd_la-ctf-archive.lo libctf_nobfd_la-ctf-dump.lo libctf_nobfd_la-ctf-create.lo libctf_nobfd_la-ctf-decl.lo libctf_nobfd_la-ctf-error.lo libctf_nobfd_la-ctf-hash.lo libctf_nobfd_la-ctf-labels.lo libctf_nobfd_la-ctf-dedup.lo libctf_nobfd_la-ctf-link.lo libctf_nobfd_la-ctf-lookup.lo libctf_nobfd_la-ctf-open.lo libctf_nobfd_la-ctf-serialize.lo libctf_nobfd_la-ctf-sha1.lo libctf_nobfd_la-ctf-string.lo libctf_nobfd_la-ctf-subr.lo libctf_nobfd_la-ctf-types.lo libctf_nobfd_la-ctf-util.lo  -L/private/var/folders/sb/82r7skjn6yd9b8hsjz63npvr0000gs/T/pnanda/spack-stage/spack-stage-binutils-2.40-uxdvmda6dkfokfbe4dwahfc62kdnfw3c/spack-src/libctf/../libiberty/pic -liberty  -lz
     2499    libtool: link: /opt/local/bin/nm -B  .libs/libctf_nobfd_la-ctf-archive.o .libs/libctf_nobfd_la-ctf-dump.o .libs/libctf_nobfd_la-ctf-create.o .libs/libctf_nobfd_la-ctf-decl.o .libs/libctf_nobfd_la-ctf-error.o .libs/libctf_nobfd_la-ctf-hash.o .libs/libctf_nobfd_la-ctf-labels.o .libs/libctf_nobfd_la-ctf-dedup.o .libs/libctf_nobfd_la-ctf-link.o .libs/libctf_nobfd_la-ctf-lookup.o .libs/libctf_nobfd_la-ctf-open.o .libs/libctf_nobfd_la-ctf-serialize.o .libs/libctf_nobfd_la-ctf-sha1.o .libs/libctf_nobfd_la-ctf-string.o .libs/libctf_nobfd_la-ctf-subr.o .libs/libctf_nobfd_la-ctf-types.o .libs/libctf_nobfd_la-ctf-util.o   | sed -n -e 's/^.*[	 ]\([ABCDGIRSTW][ABCDGIRSTW]*\)[	 ][	 ]*_\([_A-Za-z][_A-Za-z0-9]*\)$/\1 _\2 \2/p' | /usr/bin/sed 's/.* //' | sort | uniq > .libs/libctf-nobfd.exp
     2500    libtool: link: /usr/bin/grep -E -e "ctf_.*" ".libs/libctf-nobfd.exp" > ".libs/libctf-nobfd.expT"
     2501    libtool: link: mv -f ".libs/libctf-nobfd.expT" ".libs/libctf-nobfd.exp"
     2502    libtool: link: sed 's,^,_,' < .libs/libctf-nobfd.exp > .libs/libctf-nobfd-symbols.expsym
     2503    libtool: link: /Users/pnanda/src/spack-vanilla/lib/spack/env/clang/clang -dynamiclib  -o .libs/libctf-nobfd.0.dylib  .libs/libctf_nobfd_la-ctf-archive.o .libs/libctf_nobfd_la-ctf-dump.o .libs/libctf_nobfd_la-ctf-create.o .libs/libctf_nobfd_la-ctf-decl.o .libs/libctf_nobfd_la-ctf-error.o .libs/libctf_nobfd_la-ctf-hash.o .libs/libctf_nobfd_la-ctf-labels.o .libs/libctf_nobfd_la-ctf-dedup.o .libs/libctf_nobfd_la-ctf-link.o .libs/libctf_nobfd_la-ctf-lookup.o .libs/libctf_nobfd_la-ctf-open.o .libs/libctf_nobfd_la-ctf-serialize.o .libs/libctf_nobfd_la-ctf-sha1.o .libs/libctf_nobfd_la-ctf-string.o .libs/libctf_nobfd_la-ctf-subr.o .libs/libctf_nobfd_la-ctf-types.o .libs/libctf_nobfd_la-ctf-util.o   -L/private/var/folders/sb/82r7skjn6yd9b8hsjz63npvr0000gs/T/pnanda/spack-stage/spack-stage-binutils-2.40-uxdvmda6dkfokfbe4dwahfc62kdnfw3c/spack-src/libctf/../libiberty/pic -liberty -lz    -install_name  /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/binutils-2.40-uxdvmda6dkfokfbe4dwahfc62kdnfw3c/lib/libctf-nobfd.0.dylib -compatibility_version 1 -current_version 1.0 -Wl,-single_module -Wl,-exported_symbols_list,.libs/libctf-nobfd-symbols.expsym
  >> 2504    Undefined symbols for architecture x86_64:
     2505      "_ctf_open", referenced from:
     2506          _ctf_link_add_ctf in libctf_nobfd_la-ctf-link.o
     2507          _ctf_link_deduplicating_count_inputs in libctf_nobfd_la-ctf-link.o
     2508    ld: symbol(s) not found for architecture x86_64
  >> 2509    clang: error: linker command failed with exit code 1 (use -v to see invocation)
  >> 2510    make[3]: *** [libctf-nobfd.la] Error 1
  >> 2511    make[2]: *** [all] Error 2
  >> 2512    make[1]: *** [all-libctf] Error 2
  >> 2513    make: *** [all] Error 2
 
See build log for details:
  /var/folders/sb/82r7skjn6yd9b8hsjz63npvr0000gs/T/pnanda/spack-stage/spack-stage-binutils-2.40-uxdvmda6dkfokfbe4dwahfc62kdnfw3c/spack-build-out.txt
</pre></details>

### Information on your system

* **Spack:** 0.20.0.dev0 (c0f48b30cf0cedb542f7b209a119bdfafb9a31d3)
* **Python:** 3.8.9
* **Platform:** darwin-ventura-skylake
* **Concretizer:** clingo

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/10886904/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/10886905/spack-build-env.txt)

@alalazo is the maintainer of binutils

Versions 2.37:2.40 of binutils fail on darwin with the above error.

Versions :2.36.1 don't suffer from this error but still fail because of missing -lintl:
```console
$ spack install binutils@2.36.1
[...]
     2182    ld: library not found for -lintl
  >> 2183    clang: error: linker command failed with exit code 1 (use -v to see invocation)
  >> 2184    make[4]: *** [libbfd.la] Error 1
  >> 2185    make[3]: *** [all-recursive] Error 1
  >> 2186    make[2]: *** [all] Error 2
  >> 2187    make[1]: *** [all-bfd] Error 2
  >> 2188    make: *** [all] Error 2
```
... and therefore need the `nls` variant enabled, which should default be enabled on "darwin" because it's not provided by libc like it is on GNU/Linux.  Alternatively the `nls` variant can be removed entirely so that the dependency on `gettext` should be forced on like `texinfo` (#34312).  PR for the former case incoming.

But I've run out of ideas about what to do next toward fixing the original _ctf_open error 🤷 so any advice appreciated.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by omsai** [comment]
Correction: binutils 2.35.2 and below don't have the _ctf_open error. 2.36:2.40 are affected.

**Comment by adamjstewart** [comment]
I just hit this issue too. Any ideas @alalazo?

**Comment by alalazo** [comment]
Looking into this. Threads on SO which might be related:
- https://stackoverflow.com/a/30949187/771663
- https://stackoverflow.com/q/30948807/771663

**Comment by alalazo** [comment]
So, the issue is actually ~`static`~ `shared` linking. Can you check if:
```
binutils libs=static
```
works for you too?

EDIT: wrote it backward initially

**Comment by adamjstewart** [comment]
Builds:

```console
$ spack install binutils libs=static
```

Fails:

```console
$ spack install binutils libs=shared
$ spack install binutils libs=shared,static
```
