### ISSUE TITLE
Installation issue: llvm

### ISSUE THREAD

**Issue by omsai** [LLNL/spack#35819]
### Steps to reproduce the issue

```console
$ spack spec -I llvm@11.1.0
Input spec
--------------------------------
 -   llvm@11.1.0

Concretized
--------------------------------
 -   llvm@11.1.0%apple-clang@13.1.6+clang~code_signing+compiler-rt~cuda~flang~gold+internal_unwind~ipo+libcxx~link_llvm_dylib+lld+lldb+llvm_dylib~mlir~omp_debug~omp_tsan+polly~python~split_dwarf~z3 build_system=cmake build_type=Release patches=514926d,6811ad4,7b286b1,f920173 targets=none version_suffix=none arch=darwin-ventura-skylake
[+]      ^cmake@3.25.2%apple-clang@13.1.6~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=darwin-ventura-skylake
[+]          ^openssl@1.1.1t%apple-clang@13.1.6~docs~shared build_system=generic certs=mozilla arch=darwin-ventura-skylake
[+]              ^ca-certificates-mozilla@2023-01-10%apple-clang@13.1.6 build_system=generic arch=darwin-ventura-skylake
[+]      ^hwloc@2.9.0%apple-clang@13.1.6~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl~pci~rocm build_system=autotools libs=shared,static arch=darwin-ventura-skylake
[+]          ^libxml2@2.10.3%apple-clang@13.1.6~python build_system=autotools arch=darwin-ventura-skylake
[+]              ^libiconv@1.17%apple-clang@13.1.6 build_system=autotools libs=shared,static arch=darwin-ventura-skylake
[+]      ^libedit@3.1-20210216%apple-clang@13.1.6 build_system=autotools arch=darwin-ventura-skylake
[+]      ^ncurses@6.4%apple-clang@13.1.6~symlinks+termlib abi=none build_system=autotools arch=darwin-ventura-skylake
[+]      ^ninja@1.11.1%apple-clang@13.1.6+re2c build_system=generic arch=darwin-ventura-skylake
[+]          ^re2c@2.2%apple-clang@13.1.6 build_system=generic arch=darwin-ventura-skylake
[+]      ^perl-data-dumper@2.173%apple-clang@13.1.6 build_system=perl arch=darwin-ventura-skylake
[+]          ^perl@5.36.0%apple-clang@13.1.6+cpanm+open+shared+threads build_system=generic arch=darwin-ventura-skylake
[+]              ^berkeley-db@18.1.40%apple-clang@13.1.6+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=darwin-ventura-skylake
[+]      ^pkgconf@1.8.0%apple-clang@13.1.6 build_system=autotools arch=darwin-ventura-skylake
[+]      ^python@3.10.8%apple-clang@13.1.6+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=0d98e93,7d40923,f2fd060 arch=darwin-ventura-skylake
[+]          ^apple-libuuid@1353.100.2%apple-clang@13.1.6 build_system=bundle arch=darwin-ventura-skylake
[+]          ^bzip2@1.0.8%apple-clang@13.1.6~debug~pic+shared build_system=generic arch=darwin-ventura-skylake
[+]              ^diffutils@3.8%apple-clang@13.1.6 build_system=autotools arch=darwin-ventura-skylake
[+]          ^expat@2.5.0%apple-clang@13.1.6~libbsd build_system=autotools arch=darwin-ventura-skylake
[+]          ^gdbm@1.23%apple-clang@13.1.6 build_system=autotools arch=darwin-ventura-skylake
[+]          ^gettext@0.21.1%apple-clang@13.1.6+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=darwin-ventura-skylake
[+]              ^tar@1.34%apple-clang@13.1.6 build_system=autotools zip=pigz arch=darwin-ventura-skylake
[+]                  ^pigz@2.7%apple-clang@13.1.6 build_system=makefile arch=darwin-ventura-skylake
[+]                  ^zstd@1.5.2%apple-clang@13.1.6+programs build_system=makefile compression=none libs=shared,static arch=darwin-ventura-skylake
[+]          ^libffi@3.4.4%apple-clang@13.1.6 build_system=autotools arch=darwin-ventura-skylake
[+]          ^libxcrypt@4.4.33%apple-clang@13.1.6~obsolete_api build_system=autotools arch=darwin-ventura-skylake
[+]          ^readline@8.2%apple-clang@13.1.6 build_system=autotools patches=bbf97f1 arch=darwin-ventura-skylake
[+]          ^sqlite@3.40.1%apple-clang@13.1.6+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=darwin-ventura-skylake
[+]          ^xz@5.4.1%apple-clang@13.1.6~pic build_system=autotools libs=shared,static arch=darwin-ventura-skylake
[+]      ^zlib@1.2.13%apple-clang@13.1.6+optimize+pic+shared build_system=makefile arch=darwin-ventura-skylake
```

### Error message

<details><summary>Error message</summary><pre>
$ spack install -j1 llvm@11.1.0
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/pkgconf-1.8.0-bunqy7qohf3b6dqlzmhzjewnbhv4exlb
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/ca-certificates-mozilla-2023-01-10-euly5mdyl7aunwtrkxlouyz4g3vzavze
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/berkeley-db-18.1.40-lf7dbt6xe4vibmisizxpoatn6bivibtf
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/libiconv-1.17-lxx4rkvs7d4wgnkkudpgsidl5e3faco5
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/zlib-1.2.13-oc6rqfsfqx3xm2xh7hbmsc7mdghmpl3j
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/xz-5.4.1-pk7z4qdpozoe6oe6ojhikr34bwekdq3i
[+] /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk (external apple-libuuid-1353.100.2-ywyienq3742pcackv6uwcprnfebdyxbz)
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/expat-2.5.0-dg4sfhsetgbkiovm6hzot3jhr4gqjq3p
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/zstd-1.5.2-pmtog37regjdgvgbp2ihobbv2ehfkw6i
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/libffi-3.4.4-ougafawixsbvnd4r6jdjydbvsfbzdmzn
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/re2c-2.2-er6vikagttch5fxac3g3flea3uh2qeq2
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/ncurses-6.4-lvvqhcbl7v67r3kwl5un3q4itppsqjkg
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/diffutils-3.8-avtakeagtihmru43r6467gj7ympjgnu2
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/pigz-2.7-ypnybdsuwz5y5qwozj27wirohmalyyff
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/libxml2-2.10.3-6hq2aerd6qn6iohy7rbgchmaqlv3kbib
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/libedit-3.1-20210216-xievxttz434ggxesucz2z7njisrbjhcj
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/readline-8.2-utp7fpz34f4mruwcpvsdppewtuhtf6w5
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/bzip2-1.0.8-3fmdi6kwvwalorovscpskpmorbrf4dpy
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/hwloc-2.9.0-gkekulbwrwbmqupz36ff3xz4cdsrvdzk
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/gdbm-1.23-rlnwwf7hepyzgvua7un5f2tigakbbotp
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/sqlite-3.40.1-pjqlw4ifuxsrfwshkdvybbmizjnwkdi3
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/tar-1.34-qmk62hwpdr2f5od5b5njas6bcf4dv3g5
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/perl-5.36.0-k5ul6mvqnergmzhsmqxuyabdpojknznv
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/gettext-0.21.1-jcqlszulqhrjaeckdopem3j5afw4zqnq
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/libxcrypt-4.4.33-kyenmf335zucckqqs436oqddbbmppx3b
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/openssl-1.1.1t-tfx3ip7f3q6skrckai56r3hywl6sg6jv
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/perl-data-dumper-2.173-7n7tzq2smuhcrm2656dtzddq2p76wgrh
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/python-3.10.8-ccpamrtgbvkgptamryugmaeamz7ajwf5
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/cmake-3.25.2-wiqzbqxraahyzbyn6avw72v36f7yfuu4
[+] /Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/ninja-1.11.1-bscttl5n6sg6joeu6osey2f7mh7x566l
==> Installing llvm-11.1.0-ycjnorxhvjoevwftfcvqxse5ccmcgper
==> No binary for llvm-11.1.0-ycjnorxhvjoevwftfcvqxse5ccmcgper found: installing from source
==> Using cached archive: /Users/pnanda/src/spack-vanilla/var/spack/cache/_source-cache/archive/53/53a0719f3f4b0388013cfffd7b10c7d5682eece1929a9553c722348d1f866e79.tar.gz
==> Using cached archive: /Users/pnanda/src/spack-vanilla/var/spack/cache/_source-cache/archive/51/514926d661635de47972c7d403c9c4669235aa51e22e56d44676d2a2709179b6
==> Applied patch /Users/pnanda/src/spack-vanilla/var/spack/repos/builtin/packages/llvm/llvm_python_path.patch
==> Applied patch /Users/pnanda/src/spack-vanilla/var/spack/repos/builtin/packages/llvm/no_cyclades.patch
==> Applied patch /Users/pnanda/src/spack-vanilla/var/spack/repos/builtin/packages/llvm/libomp-libflags-as-list.patch
==> Applied patch https://github.com/llvm/llvm-project/commit/b498303066a63a203d24f739b2d2e0e56dca70d1.patch?full_index=1
==> llvm: Executing phase: 'cmake'
==> llvm: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 1:
    '/Users/pnanda/src/spack-vanilla/opt/spack/darwin-ventura-skylake/apple-clang-13.1.6/ninja-1.11.1-bscttl5n6sg6joeu6osey2f7mh7x566l/bin/ninja' '-j1' '-v'

2 errors found in build log:
     5172    /private/var/folders/sb/82r7skjn6yd9b8hsjz63npvr0000gs/T/pnanda/spack-stage/spack-stage-llvm-11.1.0-ycjnorxhvjoevwftfcvqxse5ccmcgpe
             r/spack-build-ycjnorx/include/c++/v1/bitset:634:17: note: in implicit copy constructor for 'std::__bit_iterator<std::__bitset<0, 0>
             , true, 0>' first required here
     5173            {return const_iterator(0, 0);}
     5174                    ^
     5175    1 warning generated.
     5176    [1836/10991] /Users/pnanda/src/spack-vanilla/lib/spack/env/clang/clang++ -DNDEBUG -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_HAS_NO_PRAGM
             A_SYSTEM_HEADER -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/private/var/folders/sb/82r7skjn6yd9b8hsjz6
             3npvr0000gs/T/pnanda/spack-stage/spack-stage-llvm-11.1.0-ycjnorxhvjoevwftfcvqxse5ccmcgper/spack-build-ycjnorx/projects/libcxx/src -
             I/private/var/folders/sb/82r7skjn6yd9b8hsjz63npvr0000gs/T/pnanda/spack-stage/spack-stage-llvm-11.1.0-ycjnorxhvjoevwftfcvqxse5ccmcgp
             er/spack-src/libcxx/src -I/private/var/folders/sb/82r7skjn6yd9b8hsjz63npvr0000gs/T/pnanda/spack-stage/spack-stage-llvm-11.1.0-ycjno
             rxhvjoevwftfcvqxse5ccmcgper/spack-build-ycjnorx/include -I/private/var/folders/sb/82r7skjn6yd9b8hsjz63npvr0000gs/T/pnanda/spack-sta
             ge/spack-stage-llvm-11.1.0-ycjnorxhvjoevwftfcvqxse5ccmcgper/spack-src/llvm/include -I/private/var/folders/sb/82r7skjn6yd9b8hsjz63np
             vr0000gs/T/pnanda/spack-stage/spack-stage-llvm-11.1.0-ycjnorxhvjoevwftfcvqxse5ccmcgper/spack-build-ycjnorx/projects/libcxx/include/
             c++build -std=c++11 -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unuse
             d-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers  -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-defaul
             t -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -fdiagnostics-color -O3  -isysroot /Applicati
             ons/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk -mmacosx-version-min=13.0 -fPIC -DLIBCXX_BUILD
             ING_LIBCXXABI -nostdinc++ -fvisibility-inlines-hidden -fvisibility=hidden -Wall -Wextra -W -Wwrite-strings -Wno-unused-parameter -W
             no-long-long -Werror=return-type -Wextra-semi -Wno-user-defined-literals -Wno-covered-switch-default -Wno-ignored-attributes -Wno-e
             rror -I /private/var/folders/sb/82r7skjn6yd9b8hsjz63npvr0000gs/T/pnanda/spack-stage/spack-stage-llvm-11.1.0-ycjnorxhvjoevwftfcvqxse
             5ccmcgper/spack-build-ycjnorx/include/c++/v1 -include /private/var/folders/sb/82r7skjn6yd9b8hsjz63npvr0000gs/T/pnanda/spack-stage/s
             pack-stage-llvm-11.1.0-ycjnorxhvjoevwftfcvqxse5ccmcgper/spack-build-ycjnorx/projects/libcxx/__config_site -std=c++14 -MD -MT projec
             ts/libcxx/src/CMakeFiles/cxx_shared.dir/filesystem/int128_builtins.cpp.o -MF projects/libcxx/src/CMakeFiles/cxx_shared.dir/filesyst
             em/int128_builtins.cpp.o.d -o projects/libcxx/src/CMakeFiles/cxx_shared.dir/filesystem/int128_builtins.cpp.o -c /private/var/folder
             s/sb/82r7skjn6yd9b8hsjz63npvr0000gs/T/pnanda/spack-stage/spack-stage-llvm-11.1.0-ycjnorxhvjoevwftfcvqxse5ccmcgper/spack-src/libcxx/
             src/filesystem/int128_builtins.cpp
     5177    [1837/10991] : && /Users/pnanda/src/spack-vanilla/lib/spack/env/clang/clang++ -std=c++11 -fPIC -fvisibility-inlines-hidden -Werror=
             date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initia
             lizers  -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-d
             tor -Wstring-conversion -fdiagnostics-color -O3 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Deve
             loper/SDKs/MacOSX.sdk -mmacosx-version-min=13.0 -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 1.0.0 -current_
             version 1.0.0 -o lib/libc++.1.0.dylib -install_name @rpath/libc++.1.dylib projects/libcxx/src/CMakeFiles/cxx_shared.dir/algorithm.c
             pp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/any.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/atomic.cpp.o projects/li
             bcxx/src/CMakeFiles/cxx_shared.dir/barrier.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/bind.cpp.o projects/libcxx/src/CMake
             Files/cxx_shared.dir/charconv.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/chrono.cpp.o projects/libcxx/src/CMakeFiles/cxx_s
             hared.dir/condition_variable.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/condition_variable_destructor.cpp.o projects/libcx
             x/src/CMakeFiles/cxx_shared.dir/debug.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/exception.cpp.o projects/libcxx/src/CMake
             Files/cxx_shared.dir/functional.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/future.cpp.o projects/libcxx/src/CMakeFiles/cxx
             _shared.dir/hash.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/ios.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/iostre
             am.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/locale.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/memory.cpp.o proj
             ects/libcxx/src/CMakeFiles/cxx_shared.dir/mutex.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/mutex_destructor.cpp.o projects
             /libcxx/src/CMakeFiles/cxx_shared.dir/new.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/optional.cpp.o projects/libcxx/src/CM
             akeFiles/cxx_shared.dir/random.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/random_shuffle.cpp.o projects/libcxx/src/CMakeFi
             les/cxx_shared.dir/regex.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/shared_mutex.cpp.o projects/libcxx/src/CMakeFiles/cxx_
             shared.dir/stdexcept.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/string.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir
             /strstream.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/system_error.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/thr
             ead.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/typeinfo.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/utility.cpp.o 
             projects/libcxx/src/CMakeFiles/cxx_shared.dir/valarray.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/variant.cpp.o projects/l
             ibcxx/src/CMakeFiles/cxx_shared.dir/vector.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/filesystem/operations.cpp.o projects
             /libcxx/src/CMakeFiles/cxx_shared.dir/filesystem/directory_iterator.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/filesystem/
             int128_builtins.cpp.o  -nodefaultlibs  -lSystem  -lc  -Wl,-force_load  lib/libc++abi.a  -Wl,-unexported_symbols_list,/private/var/f
             olders/sb/82r7skjn6yd9b8hsjz63npvr0000gs/T/pnanda/spack-stage/spack-stage-llvm-11.1.0-ycjnorxhvjoevwftfcvqxse5ccmcgper/spack-src/li
             bcxx/src/../lib/libc++unexp.exp  -Wl,-reexported_symbols_list,/private/var/folders/sb/82r7skjn6yd9b8hsjz63npvr0000gs/T/pnanda/spack
             -stage/spack-stage-llvm-11.1.0-ycjnorxhvjoevwftfcvqxse5ccmcgper/spack-src/libcxx/src/../lib/libc++abi.v2.exp  -Wl,-force_symbols_no
             t_weak_list,/private/var/folders/sb/82r7skjn6yd9b8hsjz63npvr0000gs/T/pnanda/spack-stage/spack-stage-llvm-11.1.0-ycjnorxhvjoevwftfcv
             qxse5ccmcgper/spack-src/libcxx/src/../lib/notweak.exp  -Wl,-force_symbols_weak_list,/private/var/folders/sb/82r7skjn6yd9b8hsjz63npv
             r0000gs/T/pnanda/spack-stage/spack-stage-llvm-11.1.0-ycjnorxhvjoevwftfcvqxse5ccmcgper/spack-src/libcxx/src/../lib/weak.exp  -Wl,-re
             exported_symbols_list,/private/var/folders/sb/82r7skjn6yd9b8hsjz63npvr0000gs/T/pnanda/spack-stage/spack-stage-llvm-11.1.0-ycjnorxhv
             joevwftfcvqxse5ccmcgper/spack-src/libcxx/src/../lib/libc++abi-exceptions.exp  -lSystem && :
  >> 5178    FAILED: lib/libc++.1.0.dylib
     5179    : && /Users/pnanda/src/spack-vanilla/lib/spack/env/clang/clang++ -std=c++11 -fPIC -fvisibility-inlines-hidden -Werror=date-time -We
             rror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers  -Wno-
             long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-
             conversion -fdiagnostics-color -O3 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/Ma
             cOSX.sdk -mmacosx-version-min=13.0 -dynamiclib -Wl,-headerpad_max_install_names -compatibility_version 1.0.0 -current_version 1.0.0
              -o lib/libc++.1.0.dylib -install_name @rpath/libc++.1.dylib projects/libcxx/src/CMakeFiles/cxx_shared.dir/algorithm.cpp.o projects
             /libcxx/src/CMakeFiles/cxx_shared.dir/any.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/atomic.cpp.o projects/libcxx/src/CMak
             eFiles/cxx_shared.dir/barrier.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/bind.cpp.o projects/libcxx/src/CMakeFiles/cxx_sha
             red.dir/charconv.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/chrono.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/con
             dition_variable.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/condition_variable_destructor.cpp.o projects/libcxx/src/CMakeFi
             les/cxx_shared.dir/debug.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/exception.cpp.o projects/libcxx/src/CMakeFiles/cxx_sha
             red.dir/functional.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/future.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/h
             ash.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/ios.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/iostream.cpp.o proj
             ects/libcxx/src/CMakeFiles/cxx_shared.dir/locale.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/memory.cpp.o projects/libcxx/s
             rc/CMakeFiles/cxx_shared.dir/mutex.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/mutex_destructor.cpp.o projects/libcxx/src/C
             MakeFiles/cxx_shared.dir/new.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/optional.cpp.o projects/libcxx/src/CMakeFiles/cxx_
             shared.dir/random.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/random_shuffle.cpp.o projects/libcxx/src/CMakeFiles/cxx_share
             d.dir/regex.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/shared_mutex.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/st
             dexcept.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/string.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/strstream.cp
             p.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/system_error.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/thread.cpp.o pro
             jects/libcxx/src/CMakeFiles/cxx_shared.dir/typeinfo.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/utility.cpp.o projects/libc
             xx/src/CMakeFiles/cxx_shared.dir/valarray.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/variant.cpp.o projects/libcxx/src/CMa
             keFiles/cxx_shared.dir/vector.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/filesystem/operations.cpp.o projects/libcxx/src/C
             MakeFiles/cxx_shared.dir/filesystem/directory_iterator.cpp.o projects/libcxx/src/CMakeFiles/cxx_shared.dir/filesystem/int128_builti
             ns.cpp.o  -nodefaultlibs  -lSystem  -lc  -Wl,-force_load  lib/libc++abi.a  -Wl,-unexported_symbols_list,/private/var/folders/sb/82r
             7skjn6yd9b8hsjz63npvr0000gs/T/pnanda/spack-stage/spack-stage-llvm-11.1.0-ycjnorxhvjoevwftfcvqxse5ccmcgper/spack-src/libcxx/src/../l
             ib/libc++unexp.exp  -Wl,-reexported_symbols_list,/private/var/folders/sb/82r7skjn6yd9b8hsjz63npvr0000gs/T/pnanda/spack-stage/spack-
             stage-llvm-11.1.0-ycjnorxhvjoevwftfcvqxse5ccmcgper/spack-src/libcxx/src/../lib/libc++abi.v2.exp  -Wl,-force_symbols_not_weak_list,/
             private/var/folders/sb/82r7skjn6yd9b8hsjz63npvr0000gs/T/pnanda/spack-stage/spack-stage-llvm-11.1.0-ycjnorxhvjoevwftfcvqxse5ccmcgper
             /spack-src/libcxx/src/../lib/notweak.exp  -Wl,-force_symbols_weak_list,/private/var/folders/sb/82r7skjn6yd9b8hsjz63npvr0000gs/T/pna
             nda/spack-stage/spack-stage-llvm-11.1.0-ycjnorxhvjoevwftfcvqxse5ccmcgper/spack-src/libcxx/src/../lib/weak.exp  -Wl,-reexported_symb
             ols_list,/private/var/folders/sb/82r7skjn6yd9b8hsjz63npvr0000gs/T/pnanda/spack-stage/spack-stage-llvm-11.1.0-ycjnorxhvjoevwftfcvqxs
             e5ccmcgper/spack-src/libcxx/src/../lib/libc++abi-exceptions.exp  -lSystem && :
     5180    ld: requested re-export symbol ___cxa_bad_cast is not from a dylib, but from lib/libc++abi.a(cxa_aux_runtime.cpp.o)
     5181     file 'lib/libc++abi.a' for architecture x86_64
  >> 5182    clang: error: linker command failed with exit code 1 (use -v to see invocation)
     5183    ninja: build stopped: subcommand failed.

See build log for details:
  /var/folders/sb/82r7skjn6yd9b8hsjz63npvr0000gs/T/pnanda/spack-stage/spack-stage-llvm-11.1.0-ycjnorxhvjoevwftfcvqxse5ccmcgper/spack-build-out.txt
</pre></details>

### Information on your system

* **Spack:** 0.20.0.dev0 (c0f48b30cf0cedb542f7b209a119bdfafb9a31d3)
* **Python:** 3.8.9
* **Platform:** darwin-ventura-skylake
* **Concretizer:** clingo

### Additional information

* [spack-build-out.txt](https://github.com/spack/spack/files/10888413/spack-build-out.txt)
* [spack-build-env.txt](https://github.com/spack/spack/files/10888414/spack-build-env.txt)

The maintainers of llvm are @haampie and @trws

`llvm@11` is necessary for the latest `py-lvmlite@0.39.1` package and also the upstream llvm developer branch still requires `llvm@11` (https://github.com/numba/llvmlite/blob/main/ffi/build.py#L167-L173).

I tested that later versions `llvm@12:15` compile without issue on darwin, but unfortunately those versions are not yet supported by `py-llvmlite`

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by omsai** [comment]
I can get past the error by disabling `LIBCXX_ENABLE_STATIC_ABI_LIBRARY` for darwin.  PR incoming:

```diff
diff --git a/var/spack/repos/builtin/packages/llvm/package.py b/var/spack/repos/builtin/packages/llvm/package.py
index e94ff94d75..986f840d45 100644
--- a/var/spack/repos/builtin/packages/llvm/package.py
+++ b/var/spack/repos/builtin/packages/llvm/package.py
@@ -669,13 +669,15 @@ def cmake_args(self):
                 from_variant("LLVM_BUILD_LLVM_DYLIB", "llvm_dylib"),
                 from_variant("LLVM_LINK_LLVM_DYLIB", "link_llvm_dylib"),
                 from_variant("LLVM_USE_SPLIT_DWARF", "split_dwarf"),
-                # By default on Linux, libc++.so is a ldscript. CMake fails to add
-                # CMAKE_INSTALL_RPATH to it, which fails. Statically link libc++abi.a
-                # into libc++.so, linking with -lc++ or -stdlib=libc++ is enough.
-                define("LIBCXX_ENABLE_STATIC_ABI_LIBRARY", True),
             ]
         )
 
+        # By default on Linux, libc++.so is a ldscript. CMake fails to add
+        # CMAKE_INSTALL_RPATH to it, which fails. Statically link libc++abi.a
+        # into libc++.so, linking with -lc++ or -stdlib=libc++ is enough.
+        if sys.platform != "darwin":
+            cmake_args.append(define("LIBCXX_ENABLE_STATIC_ABI_LIBRARY", True))
+
         cmake_args.append(define("LLVM_TARGETS_TO_BUILD", get_llvm_targets_to_build(spec)))
 
         cmake_args.append(from_variant("LIBOMP_TSAN_SUPPORT", "omp_tsan"))
```

**Comment by naromero77** [comment]
Can you try building again with the latest Spack to see if this is still an issue? There have been many changes in the Spack package since March.

**Comment by omsai** [comment]
I no longer have access to that machine. On my replacement m2 mac with the latest spack develop branch, I cannot get as far to reproduce this issue of not being able to install `llvm@11.1.0` because of conflicts with gcc ABI versions which I cannot workaround by compiling a matching gcc version. This version of llvm is fairly old and the reason I was compiling it was to compile llvmlite, but really the Numba people need to support newer llvm versions for macOS - it looks like 14 support is there / upcoming in deveopment. I'll close the issue for now and we can reopen the issue if anyone else encounters it.
