### ISSUE TITLE
spack -k does not propagate to mercurial-based packages

### ISSUE THREAD

**Issue by sknigh** [LLNL/spack#3590]
Some packages, such as pflotran, use mercurial (hg). Mercurial will strictly check certificates unless ```hg clone``` is used with ```--insecure```. ```spack -k``` does not set ```--insecure```

**Comment by adamjstewart** [comment]
If you or anyone else want to take a stab at fixing this, the relevant code would be `HgFetchStrategy` in `lib/spack/spack/fetch_strategy.py`. Compare to `GitFetchStrategy` which does set insecure properly.

**Comment by adamjstewart** [comment]
This will be fixed by #3834.
