### ISSUE TITLE
Installation issue: petsc

### ISSUE THREAD

**Issue by raldone01** [LLNL/spack#35903]
### Steps to reproduce the issue

```console
$ spack spec -I petsc
Input spec
--------------------------------
 -   petsc

Concretized
--------------------------------
 -   petsc@3.18.3%gcc@12.2.1~X~batch~cgns~complex~cuda~debug+double~exodusii~fftw+fortran~giflib+hdf5~hpddm~hwloc+hypre~int64~jpeg~knl~kokkos~libpng~libyaml~memkind+metis~mkl-pardiso~mmg~moab~mpfr+mpi~mumps~openmp~p4est~parmmg~ptscotch~random123~rocm~saws~scalapack+shared~strumpack~suite-sparse+superlu-dist~tetgen~trilinos~valgrind build_system=generic clanguage=C arch=linux-archrolling-icelake
[+]      ^diffutils@3.8%gcc@12.2.1 build_system=autotools arch=linux-archrolling-icelake
[+]          ^libiconv@1.16%gcc@12.2.1 build_system=autotools libs=shared,static arch=linux-archrolling-icelake
[+]      ^hdf5@1.12.2%gcc@12.2.1~cxx~fortran~hl~ipo~java+mpi+shared~szip~threadsafe+tools api=default build_system=cmake build_type=RelWithDebInfo arch=linux-archrolling-icelake
[+]          ^cmake@3.24.3%gcc@12.2.1~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-archrolling-icelake
[+]          ^pkgconf@1.8.0%gcc@12.2.1 build_system=autotools arch=linux-archrolling-icelake
[+]      ^hypre@2.26.0%gcc@12.2.1~complex~cuda~debug+fortran~gptune~int64~internal-superlu~mixedint+mpi~openmp~rocm+shared~superlu-dist~umpire~unified-memory build_system=autotools arch=linux-archrolling-icelake
[+]      ^metis@5.1.0%gcc@12.2.1~gdb~int64~ipo~real64+shared build_system=cmake build_type=RelWithDebInfo patches=4991da9,93a7903,b1225da arch=linux-archrolling-icelake
[+]      ^openblas@0.3.21%gcc@12.2.1~bignuma~consistent_fpcsr+fortran~ilp64+locking+pic+shared build_system=makefile patches=d3d9b15 symbol_suffix=none threads=none arch=linux-archrolling-icelake
[+]          ^perl@5.36.0%gcc@12.2.1+cpanm+shared+threads build_system=generic arch=linux-archrolling-icelake
[+]              ^berkeley-db@18.1.40%gcc@12.2.1+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-archrolling-icelake
[+]      ^openmpi@4.1.4%gcc@12.2.1~atomics~cuda~cxx~cxx_exceptions~gpfs~internal-hwloc~java~legacylaunchers~lustre~memchecker+romio+rsh~singularity+static+vt+wrapper-rpath build_system=autotools fabrics=none schedulers=none arch=linux-archrolling-icelake
[+]          ^hwloc@2.8.0%gcc@12.2.1~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-archrolling-icelake
[+]              ^libpciaccess@0.16%gcc@12.2.1 build_system=autotools arch=linux-archrolling-icelake
[+]                  ^util-macros@1.19.3%gcc@12.2.1 build_system=autotools arch=linux-archrolling-icelake
[+]              ^libxml2@2.10.1%gcc@12.2.1~python build_system=autotools arch=linux-archrolling-icelake
[+]          ^numactl@2.0.14%gcc@12.2.1 build_system=autotools patches=4e1d78c,62fc8a8,ff37630 arch=linux-archrolling-icelake
[+]              ^autoconf@2.69%gcc@12.2.1 build_system=autotools patches=35c4492,7793209,a49dd5b arch=linux-archrolling-icelake
[+]              ^automake@1.16.5%gcc@12.2.1 build_system=autotools arch=linux-archrolling-icelake
[+]              ^libtool@2.4.7%gcc@12.2.1 build_system=autotools arch=linux-archrolling-icelake
[+]              ^m4@1.4.19%gcc@12.2.1+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-archrolling-icelake
[+]                  ^libsigsegv@2.13%gcc@12.2.1 build_system=autotools arch=linux-archrolling-icelake
[+]          ^openssh@9.1p1%gcc@12.2.1+gssapi build_system=autotools arch=linux-archrolling-icelake
[+]              ^krb5@1.19.3%gcc@12.2.1+shared build_system=autotools arch=linux-archrolling-icelake
[+]                  ^bison@3.8.2%gcc@12.2.1 build_system=autotools arch=linux-archrolling-icelake
[+]              ^libedit@3.1-20210216%gcc@12.2.1 build_system=autotools arch=linux-archrolling-icelake
[+]          ^pmix@4.1.2%gcc@12.2.1~docs+pmi_backwards_compatibility~restful build_system=autotools arch=linux-archrolling-icelake
[+]              ^libevent@2.1.12%gcc@12.2.1+openssl build_system=autotools arch=linux-archrolling-icelake
[+]      ^parmetis@4.0.3%gcc@12.2.1~gdb~int64~ipo+shared build_system=cmake build_type=RelWithDebInfo patches=4f89253,50ed208,704b84f arch=linux-archrolling-icelake
[+]      ^python@3.10.8%gcc@12.2.1+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4+uuid+zlib build_system=generic patches=0d98e93,7d40923,f2fd060 arch=linux-archrolling-icelake
[+]          ^bzip2@1.0.8%gcc@12.2.1~debug~pic+shared build_system=generic arch=linux-archrolling-icelake
[+]          ^expat@2.4.8%gcc@12.2.1+libbsd build_system=autotools arch=linux-archrolling-icelake
[+]              ^libbsd@0.11.5%gcc@12.2.1 build_system=autotools arch=linux-archrolling-icelake
[+]                  ^libmd@1.0.4%gcc@12.2.1 build_system=autotools arch=linux-archrolling-icelake
[+]          ^gdbm@1.23%gcc@12.2.1 build_system=autotools arch=linux-archrolling-icelake
[+]          ^gettext@0.21.1%gcc@12.2.1+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=linux-archrolling-icelake
[+]              ^tar@1.34%gcc@12.2.1 build_system=autotools zip=pigz arch=linux-archrolling-icelake
[+]                  ^pigz@2.7%gcc@12.2.1 build_system=makefile arch=linux-archrolling-icelake
[+]                  ^zstd@1.5.2%gcc@12.2.1+programs build_system=makefile compression=none libs=shared,static arch=linux-archrolling-icelake
[+]          ^libffi@3.4.2%gcc@12.2.1 build_system=autotools arch=linux-archrolling-icelake
[+]          ^ncurses@6.3%gcc@12.2.1~symlinks+termlib abi=none build_system=autotools arch=linux-archrolling-icelake
[+]          ^openssl@1.1.1s%gcc@12.2.1~docs~shared build_system=generic certs=mozilla arch=linux-archrolling-icelake
[+]              ^ca-certificates-mozilla@2022-10-11%gcc@12.2.1 build_system=generic arch=linux-archrolling-icelake
[+]          ^readline@8.1.2%gcc@12.2.1 build_system=autotools arch=linux-archrolling-icelake
[+]          ^sqlite@3.39.4%gcc@12.2.1+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-archrolling-icelake
[+]          ^util-linux-uuid@2.38.1%gcc@12.2.1 build_system=autotools arch=linux-archrolling-icelake
[+]          ^xz@5.2.7%gcc@12.2.1~pic build_system=autotools libs=shared,static arch=linux-archrolling-icelake
[+]      ^superlu-dist@8.1.1%gcc@12.2.1~cuda~int64~ipo~openmp~rocm+shared build_system=cmake build_type=RelWithDebInfo arch=linux-archrolling-icelake
[+]      ^zlib@1.2.13%gcc@12.2.1+optimize+pic+shared build_system=makefile arch=linux-archrolling-icelake
```

### Error message

<details><summary>Error message</summary><pre>

[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/libiconv-1.16-k6wtapyszr2ota6jc2l2in6lkiidh2px
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/pkgconf-1.8.0-yae6lxjree3lsx4hrrgyjjelqbumai6i
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/ca-certificates-mozilla-2022-10-11-lrhcrzchpl65gzxcxwpyhbhugtrgsmj3
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/berkeley-db-18.1.40-cqi27x7d5t5lspzr5zgsftwrwcj2h4c7
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/zlib-1.2.13-yphdg2nhomdzdmngniienqheqhlwdxyy
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/libsigsegv-2.13-f3l4tiwlc4hpsnf7pynaffwbefmfvtjw
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/util-macros-1.19.3-i7pbgqemniqud6zcsxlvkpnt3gb7tnw4
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/xz-5.2.7-3isylhl5q4f6axk6rzsfi5ogk6ykmst6
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/zstd-1.5.2-dmdhnwtpbzskhw7tghwfh43352534brk
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/libmd-1.0.4-4vcbkxrdmgquyfrtz65ma7xvwr6rs3pk
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/libffi-3.4.2-dtdh6gyy73w5gnnyj2w7sbcohzobuxou
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/diffutils-3.8-syopoggc6qplbrmhfoplfkqwn4g3slzl
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/util-linux-uuid-2.38.1-7si4u2eevgoy3pmiq63otxhxip4gfuxo
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/ncurses-6.3-cbxve47p6mzcxx36c4mljuewvv45flsz
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/pigz-2.7-ckntkwbobxugfqj7c2ul5em6axh7bm3c
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/libxml2-2.10.1-cf5vzdxb3mvivd2foc3yw6doce3hlwid
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/libbsd-0.11.5-ifofm6fluwlv7lmj3p32m7j54xsb6yzi
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/bzip2-1.0.8-n22rt3ulq7apnnoprm75hw3dgpnd7nfi
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/m4-1.4.19-hgfrm2wedcjy45alrsguhvmh6uzjlgo6
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/libedit-3.1-20210216-ay3gszocbk7x3ipauxgqnohiq76dq5g2
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/readline-8.1.2-n5oer7quyda5jqfvmzq6huurxui7mb65
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/expat-2.4.8-nzsdh7wj7gmu3uyyz7y74k7ymhv7mqkv
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/tar-1.34-4p6mh4wq5mgvwpkahhonbb2f6vacfamh
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/libtool-2.4.7-etbmgfzcjgwupdixvfr7cl6htumvac3g
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/gdbm-1.23-5vbht6qafe727mdy3o6oscvkvkedkhwp
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/sqlite-3.39.4-nkjfmkkse5lceckrgh4h5lteo5nrcaht
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/gettext-0.21.1-cbmus35ryam2ztus6iz7hmbtll6stucb
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/libpciaccess-0.16-72uhlqbbsm5mziokx6nrcyfr3dfht2yx
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/perl-5.36.0-4srm5wn3vfr7pet3jzqrvvznn6f5rnw6
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/hwloc-2.8.0-kwkvncn4ls5wl2nqdg5of5ntqhydjjsg
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/bison-3.8.2-iwqiie4y2kv5n5cwgcicswrpqshlf6su
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/openssl-1.1.1s-cc73epi4w2bhj5nguqvcfaazmwfxwwdy
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/openblas-0.3.21-ashv3ovhlm5ozqpw7tgvuzycjii6p5kx
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/autoconf-2.69-ldklmqmg35m4dfkni5t6hslphz27flcl
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/cmake-3.24.3-goxke6zioq6rwwapvucs6gqkxiqmlazc
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/krb5-1.19.3-fxwkxgyrf664mkoipwfx5l3lsrxzqndu
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/python-3.10.8-fzjhtxh2b7xjfccabqhxgx55lkm6bwo2
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/libevent-2.1.12-rizxbx3pseusizsgoi4hstzccckqarkd
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/automake-1.16.5-cpslz7mkwpzrk7yopatnbvluoyhrhakw
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/metis-5.1.0-tkgdhg6kssjzkxl5smgwpiiutfg3bfql
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/openssh-9.1p1-l5zqf45afvbnl4zkvfeomg35l7dtgvro
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/pmix-4.1.2-xtria3taugdke3bqmt4mbqayeybvgc7e
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/numactl-2.0.14-b7hjnqpahvtcw5azk3eblgdzgls3kpqg
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/openmpi-4.1.4-2n6cz5ekxdccekntifmpeu7iztcgcqll
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/hypre-2.26.0-o3ko2nf22vfbnzerbiwwwongh3os5eml
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/hdf5-1.12.2-xng5dfodyl6umhojn4o5fmjbfwuuph27
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/parmetis-4.0.3-gausulcorpkolcj7gem26vqnh4osyujj
[+] /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/superlu-dist-8.1.1-6s6uyxdkt5osuqjughje4jcownf2rkjz
==> Installing petsc-3.18.1-yocwl2wobrk4sjtok6beamk333ajoee3
==> No binary for petsc-3.18.1-yocwl2wobrk4sjtok6beamk333ajoee3 found: installing from source
==> Using cached archive: /home/main/Desktop/spack/var/spack/cache/_source-cache/archive/02/02f5979a22f5961bb775d527f8450db77bc6a8d2541f3b05fb586829b82e9bc8.tar.gz
==> No patches needed for petsc
==> petsc: Executing phase: 'configure'
==> petsc: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j1' 'V=1'

5 errors found in build log:
     715    xxx=========================================================================xxx
     716     Configure stage complete. Now build PETSc libraries with:
     717       make PETSC_DIR=/tmp/main/spack-stage/spack-stage-petsc-3.18.1-yocwl2wobrk4sjtok6beamk333ajoee3/spack-src PETSC_ARCH=arch-linux-c-opt all
     718    xxx=========================================================================xxx
     719    ==> petsc: Executing phase: 'build'
     720    ==> [2023-03-07-09:10:20.887109] 'make' '-j1' 'V=1'
  >> 721    /tmp/main/spack-stage/spack-stage-petsc-3.18.1-yocwl2wobrk4sjtok6beamk333ajoee3/spack-src/lib/petsc/bin/petscnagupgrade.py:14: DeprecationWarning: The distutils package is deprecated and slated for re
            moval in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
     722      from distutils.version import LooseVersion as Version
     723    make[2]: Entering directory '/tmp/main/spack-stage/spack-stage-petsc-3.18.1-yocwl2wobrk4sjtok6beamk333ajoee3/spack-src'
     724    ==========================================
     725
     726    See documentation/faq.html and documentation/bugreporting.html
     727    for help with installation problems.  Please send EVERYTHING

     ...

     978    Using MAKE: /usr/bin/make
     979    Using MAKEFLAGS: -j7 -l12.0 w -j1 -- PETSC_DIR=/tmp/main/spack-stage/spack-stage-petsc-3.18.1-yocwl2wobrk4sjtok6beamk333ajoee3/spack-src PETSC_ARCH=arch-linux-c-opt V=1
     980    ==========================================
     981    make[3]: Entering directory '/tmp/main/spack-stage/spack-stage-petsc-3.18.1-yocwl2wobrk4sjtok6beamk333ajoee3/spack-src'
     982    /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/python-3.10.8-fzjhtxh2b7xjfccabqhxgx55lkm6bwo2/bin/python3.10 /tmp/main/spack-stage/spack-stage-petsc-3.18.1-yocwl2wobrk4sjtok6b
            eamk333ajoee3/spack-src/config/gmakegentest.py --petsc-dir=/tmp/main/spack-stage/spack-stage-petsc-3.18.1-yocwl2wobrk4sjtok6beamk333ajoee3/spack-src --petsc-arch=arch-linux-c-opt --testdir=./arch-linu
            x-c-opt/tests
     983    /home/main/Desktop/spack/opt/spack/linux-archrolling-icelake/gcc-12.2.1/python-3.10.8-fzjhtxh2b7xjfccabqhxgx55lkm6bwo2/bin/python3.10 ./config/gmakegen.py --petsc-arch=arch-linux-c-opt
  >> 984    make[3]: *** No rule to make target 'w'.  Stop.
     985    make[3]: Leaving directory '/tmp/main/spack-stage/spack-stage-petsc-3.18.1-yocwl2wobrk4sjtok6beamk333ajoee3/spack-src'
  >> 986    make[2]: *** [/tmp/main/spack-stage/spack-stage-petsc-3.18.1-yocwl2wobrk4sjtok6beamk333ajoee3/spack-src/lib/petsc/conf/rules:56: libs] Error 2
     987    make[2]: Leaving directory '/tmp/main/spack-stage/spack-stage-petsc-3.18.1-yocwl2wobrk4sjtok6beamk333ajoee3/spack-src'
     988    **************************ERROR*************************************
     989      Error during compile, check arch-linux-c-opt/lib/petsc/conf/make.log
     990      Send it and arch-linux-c-opt/lib/petsc/conf/configure.log to petsc-maint@mcs.anl.gov
     991    ********************************************************************
  >> 992    make[1]: *** [makefile:34: all] Error 1
  >> 993    make: *** [GNUmakefile:9: all] Error 2

See build log for details:
  /tmp/main/spack-stage/spack-stage-petsc-3.18.1-yocwl2wobrk4sjtok6beamk333ajoee3/spack-build-out.txt

==> Error: petsc-3.18.1-yocwl2wobrk4sjtok6beamk333ajoee3: Package was not installed
==> Error: Installation request failed.  Refer to reported errors for failing package(s).

</pre></details>

### Information on your system

* **Spack:** 0.20.0.dev0 (2ff337a2a59bf919efd10e4858719fbc19c026f2)
* **Python:** 3.10.9
* **Platform:** linux-archrolling-icelake
* **Concretizer:** clingo

### Additional information

[spack-build-01-configure-out.txt](https://github.com/spack/spack/files/10907039/spack-build-01-configure-out.txt)
[spack-build-02-build-out.txt](https://github.com/spack/spack/files/10907040/spack-build-02-build-out.txt)
[spack-build-env-mods.txt](https://github.com/spack/spack/files/10907041/spack-build-env-mods.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/10907042/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/10907043/spack-build-out.txt)

CC @balay  @barrysmith  @jedbrown

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by balay** [comment]
Can you try the fix at https://github.com/spack/spack/pull/35906 ?

**Comment by raldone01** [comment]
Works for me.

**Comment by balay** [comment]
fixed by https://github.com/spack/spack/pull/35906
