### ISSUE TITLE
Mercurial 3.9.1 is not executed at the right directly location (OSX10.11)

### ISSUE THREAD

**Issue by keitat** [LLNL/spack#3591]
I found Mercurial (hg) instantiated by Spack is failing to locate python's modules and library files.

Mercurial's executable is a python script, which start with finding python modules using its relative path. It appears that Spack is not setting the current directory properly when executing Mercurial.

(This is how Mercurial's executable look like:)
```
#!/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python
#
# mercurial - scalable distributed SCM
#
# Copyright 2005-2007 Matt Mackall <mpm@selenic.com>
#
# This software may be used and distributed according to the terms of the
# GNU General Public License version 2 or any later version.

import os
import sys

if os.environ.get('HGUNICODEPEDANTRY', False):
    try:
        reload(sys)
        sys.setdefaultencoding("undefined")
    except NameError:
        pass

**libdir = '../../Library/Python/2.7/site-packages/'**
```

**Comment by adamjstewart** [comment]
Can you try out #3834 and see if it solves your problem? I'm using a Spack-installed mercurial and it works just fine.
