### ISSUE TITLE
Cannot access upstream packages from inside spack environment

### ISSUE THREAD

**Issue by erothe** [LLNL/spack#35927]
### Steps to reproduce

Spack does not allow for upstreams when inside an environment. 

See the following example:

I start by creating the upstream installation with a simple package - `zlib`:

```console
~ git clone git@github.com:spack/spack tmp/upstream
~ source tmp/upstream/share/spack/setup-env.sh
~ spack env create upstream
~ spack -e upstream add zlib
~ spack -e upstream concretize
~ spack -e upstream install
```

Then I create a local spack and set up the upstream. `spack find` will show that everything is correctly configured.

```console
~ git clone git@github.com:spack/spack tmp/local
~ source tmp/local/share/spack/setup-env.sh
~ cat >> tmp/local/etc/spack/upstreams.yaml <<-EOF
upstreams:
  upstream:
    install_tree: ~/tmp/upstream/opt/spack
EOF
spack find
```

Finally I create an environment and try to look for the upstream, but spack reports no installed packages, that is, it does not take upstream into account.

```console
~ spack env create local
~ spack env activate local
~ spack find
```

### Error message

`spack find` shows no packages from the upstream.

### Information on your system

```console
~ spack debug report
* **Spack:** 0.20.0.dev0 (ec73157a3446d8e309cdab32fc4ea40b349b72e4)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by erothe** [comment]
This issue was already discussed in slack. I open an issue here just to keep track.

**Comment by alalazo** [comment]
This is how environment are supposed to work, and has nothing to do with upstreams, I guess. With a local database:
![Screenshot from 2023-04-05 14-58-42](https://user-images.githubusercontent.com/4199709/230087663-0869de69-da26-4ef9-b59d-65898c0e70f8.png)

You can check this [tutorial](https://spack-tutorial.readthedocs.io/en/latest/tutorial_environments.html#creating-and-activating-environments) out to read why it is like that. Closing for now, but feel free to reopen if there are further issues.
