### ISSUE TITLE
install fake creates libraryso instead of library.so

### ISSUE THREAD

**Issue by olesenm** [LLNL/spack#3594]
Came with commit ed582cef68585b

    --- a/lib/spack/spack/package.py
    +++ b/lib/spack/spack/package.py
    @@ -1053,6 +1053,10 @@ class PackageBase(object):
             touch(join_path(self.prefix.bin, 'fake'))
             mkdirp(self.prefix.include)
             mkdirp(self.prefix.lib)
    +        library_name = 'lib' + self.name
    +        dso_suffix = 'dylib' if sys.platform == 'darwin' else 'so'
    +        touch(join_path(self.prefix.lib, library_name + dso_suffix))
    +        touch(join_path(self.prefix.lib, library_name + '.a'))
             mkdirp(self.prefix.man1)

Looks like a missing '.' in dso_suffix

**Comment by tgamblin** [comment]
Yep.  That's a typo.  Care to submit a PR?
