### ISSUE TITLE
LLNL Cardioid homepage no longer exists

### ISSUE THREAD

**Issue by alecbcs** [LLNL/spack#36043]
https://github.com/spack/spack/blob/fe5865da0d4ee4480a85ee1257cb310c036b0c88/var/spack/repos/builtin/packages/cardioid/package.py#L12

@rblake-llnl it looks like Cardioid's [home page](https://baasic.llnl.gov/comp-bio/cardioid-code.php) redirects to a 404 these days. You're listed as the maintainer. Has the home of cardioid moved?

**Comment by rblake-llnl** [comment]
The .php at the end of the page needs to be removed.

**Comment by alecbcs** [comment]
Oh sweet! Thanks for the simple fix!

**Comment by rblake-llnl** [comment]
No problem!  I'm also the maintainer of the code, let me know if you have any questions.

**Comment by alecbcs** [comment]
Thanks! Will do!
