### ISSUE TITLE
Allow providing a list of architectures to `cuda_arch` variant

### ISSUE THREAD

**Issue by ltalirz** [LLNL/spack#36047]
### Summary

Allow users to build a `CudaPackage` with support for multiple CUDA architectures.

### Rationale

The spack [CudaPackage](https://spack.readthedocs.io/en/latest/build_systems/cudapackage.html) class provides a `cuda_arch` variant that allows developers to specify a CUDA (virtual) architecture to compile for.

However, the variant only accepts a single architecture.
The nvidia compiler instead [allows compiling binaries that support a list of (virtual) architectures](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#generate-code-specification-gencode).

This can be especially useful in heterogeneous hardware environments, where one would like to avoid adding another dimension (`cuda_arch`) to the build matrix.

### Description

I'm not familiar enough with spack to suggest the canonical way for passing a list of values to `cuda_arch` here, but if someone can suggest it, the implementation should be straightforward.

One could even just provide a comma-separated list of architectures (but perhaps there are better ways of doing this).

### Additional information

```
$ spack --version
0.20.0.dev0 (f0a7e242d11e86cb6289f43f9347775273497838)
```

### General information

- [X] I have run `spack --version` and reported the version of Spack
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
> I'm not familiar enough with spack to suggest the canonical way for passing a list of values to cuda_arch here, but if someone can suggest it, the implementation should be straightforward.

Just add `multi=True` to the variant defined in `lib/spack/spack/build_systems/cuda.py`

**Comment by ltalirz** [comment]
Thanks a lot @adamjstewart for the quick rely (sorry for the late reply, super busy week).

We will give it a try and open a PR

**Comment by ltalirz** [comment]
After looking into it in more detail, it appears this was actually possible all along (sorry!).

I tried enabling `multi=True`, but this results in 
```
# spack concretize -U -f
==> Error: Remove specification of multi argument: it is handled by an attribute of the 'values' argument [mypackage, variant 'cuda_arch']
```

And, indeed: (I guess this is a different way of handling multiple arguments)
https://github.com/spack/spack/blob/f49e9591b7702268ddc28ce6cae81da4e0b6a4fc/lib/spack/spack/build_systems/cuda.py#L56

I tested specifying `cuda_arch=37,60,70` and it actually works fine.

I'm not entirely sure why I was convinced that passing multiple architectures wouldn't work - maybe because I couldn't find an example of it. Let me know if I should add an example to https://spack.readthedocs.io/en/latest/build_systems/cudapackage.html#variants

**Comment by alalazo** [comment]
@ltalirz See https://spack.readthedocs.io/en/latest/packaging_guide.html#complex-validation-logic-for-variant-values for a brief explanation of these expressions. They are used in a few places with complex validation logic, where we allow combination of values among disjoint sets.

**Comment by ltalirz** [comment]
Thanks @alalazo for the link!

Opened https://github.com/spack/spack/pull/36321 as follow-up
