### ISSUE TITLE
documentation issue with modules.yaml with command 'use'

### ISSUE THREAD

**Issue by shahzebsiddiqui** [LLNL/spack#36090]
In https://spack.readthedocs.io/en/latest/module_file_support.html#using-module-files-via-spack there is mention for command `use`.

![Screen Shot 2023-03-13 at 11 27 24 AM](https://user-images.githubusercontent.com/12942230/224748396-832c7753-b7e1-4d75-b731-b1300881652e.png)

I think its a typo. I am not sure if you meant `module use` or something else. I dont see a command name `use`  so i think its probably i typo unless i am missing something.

```
(spack-pyenv)  /global/u1/s/siddiq90/spack/var/spack/environments/qt/ [develop] which spack
spack () {
	: this is a shell function from: /global/u1/s/siddiq90/spack/share/spack/setup-env.sh
	: the real spack script is here: /global/u1/s/siddiq90/spack/bin/spack
	_spack_shell_wrapper "$@"
	return $?
}
(spack-pyenv)  /global/u1/s/siddiq90/spack/var/spack/environments/qt/ [develop] use --help
zsh: command not found: use
```

**Comment by shahzebsiddiqui** [comment]
@haampie @tgamblin @becker33 @alalazo  looks like according to git history you contributed to this page.

**Comment by alalazo** [comment]
I think it's a leftover from `dotkit` modules, which have been removed in #11986 It can be safely removed. Do you want to submit a PR for that?

**Comment by shahzebsiddiqui** [comment]
sure i will. I was going to at first but needed to confirm this was a real issue
