### ISSUE TITLE
module files for nvhpc compilers end up in wrong location?

### ISSUE THREAD

**Issue by cparrott73** [LLNL/spack#36092]
### Steps to reproduce

We have a customer who has reported an issue with spack when using the nvhpc compilers to build packages.

They can use spack to install the nvhpc compilers themselves, but the nvhpc module files seem to end up in the wrong directory.  We build openmpi below using nvhpc as an example to illustrate the issue here:

Steps to reproduce:

1. Check out spack from git repo and set up env:

```
git clone --depth 100 https://github.com/spack/spack.git
cd spack
. share/spack/setup-env.sh
```

2. Install nvhpc compilers and add them to the list of compilers:

```
spack install nvhpc@22.11
spack compiler add "$(spack location -i nvhpc@22.11)/Linux_x86_64/22.11/compilers/bin"
```

3.  Build and intstall openmpi 4.1.5 using the nvhpc compilers, while using gcc to work around packages that do not build with nvhpc:

```
spack install openmpi@4.1.5 %nvhpc@22.11 target=x86_64 ^xz%gcc ^readline%gcc ^libxcrypt%gcc
```

### Error message

Note that the nvhpc module files are installed under the linux-centos7-haswell directory below, not the linux-centos-x86_64 directory as with all the other packages:

```
$ ls spack/share/spack/modules/linux-centos7-haswell/
nvhpc-22.11-gcc-4.8.5-3tvcpri
$ ls spack/share/spack/modules/linux-centos7-x86_64/
autoconf-2.69-nvhpc-22.11-hnutaer                       libxcrypt-4.4.33-gcc-4.8.5-htuohai
automake-1.16.5-nvhpc-22.11-cjmjalb                     libxml2-2.10.3-nvhpc-22.11-q576uwj
berkeley-db-18.1.40-nvhpc-22.11-olwjfbz                 m4-1.4.19-nvhpc-22.11-r7qotbg
bison-3.8.2-nvhpc-22.11-64ka2vh                         ncurses-6.4-nvhpc-22.11-i4ze3ad
bzip2-1.0.8-nvhpc-22.11-2mzb7kl                         numactl-2.0.14-nvhpc-22.11-6erhmuu
ca-certificates-mozilla-2023-01-10-nvhpc-22.11-465levl  openmpi-4.1.5-nvhpc-22.11-ns6ugss
diffutils-3.7-nvhpc-22.11-loc5vo6                       openssh-9.1p1-nvhpc-22.11-zncm3pi
gdbm-1.23-nvhpc-22.11-d5cgvgo                           openssl-1.1.1t-nvhpc-22.11-trnnljk
gettext-0.21.1-nvhpc-22.11-kn3wtwt                      perl-5.36.0-nvhpc-22.11-qtgi3yd
hwloc-2.9.0-nvhpc-22.11-iivixuc                         pigz-2.7-nvhpc-22.11-z6zqeu2
krb5-1.20.1-nvhpc-22.11-ffp3eu4                         pkgconf-1.8.0-nvhpc-22.11-7zp5meb
libedit-3.1-20210216-nvhpc-22.11-wfcu36f                pmix-4.1.2-nvhpc-22.11-4qbgty4
libevent-2.1.12-nvhpc-22.11-4fst46i                     readline-8.2-gcc-4.8.5-xymfrtr
libiconv-1.17-nvhpc-22.11-cmma7wi                       tar-1.30-nvhpc-22.11-cbhhkcu
libpciaccess-0.16-nvhpc-22.11-uaekh5g                   util-macros-1.19.3-nvhpc-22.11-fx2ohss
libsigsegv-2.13-nvhpc-22.11-iqjvs63                     xz-5.4.1-gcc-4.8.5-luwmzr2
libtool-2.4.7-nvhpc-22.11-a7qvjxu                       zlib-1.2.13-nvhpc-22.11-drump7k
```

### Information on your system

* **Spack:** 0.20.0.dev0
* **Python:** 3.6.8
* **Platform:** linux-centos7-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by cparrott73** [comment]
Closing for now, I believe this is pilot error on my end.

**Comment by manomars** [comment]
I think that when you install nvhpc with target=x86_64, it will end up in the linux-centos-x86_64 directory as well.
