### ISSUE TITLE
Installation issue:  AOCC@4.0.0 didn't install because of a timeout

### ISSUE THREAD

**Issue by daytimothy** [LLNL/spack#36129]
### Steps to reproduce the issue

run:
spack install -v aocc@4.0.0 +license-agreed

As a side note, "spack install -v aocc@3.2.0 +license-agreed" worked.

### Error message

==> No binary for aocc-4.0.0-vyyhc5bzoktt64a3nbcwav4id3mpwltz found: installing from source
==> Error: TimeoutError: The read operation timed out

/opt/spack/lib/spack/spack/package_base.py:1445, in do_fetch:
       1442
       1443        self.stage.create()
       1444        err_msg = None if not self.manual_download else self.download_instr
  >>   1445        start_time = time.time()
       1446        self.stage.fetch(mirror_only, err_msg=err_msg)
       1447        self._fetch_time = time.time() - start_time
       1448

### Information on your system

Don't know if there is an NDA on file.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by physkets** [comment]
@amd-toolchain-support

**Comment by physkets** [comment]
The issue seems to be that the files are no longer at: https://developer.amd.com/wordpress/media/files/aocc-compiler-4.0.0.tar

**Comment by amd-toolchain-support** [comment]
PR #36353 will fix the reported issue

Thanks,
amd-toolchain-support
