### ISSUE TITLE
Version parsing from configs broken in 0.19

### ISSUE THREAD

**Issue by hejamu** [LLNL/spack#36170]
### Steps to reproduce

Have a `packages.yaml` like this:
```yaml
packages:
  cuda:
    version: [":10.2"]
```

### Error message

```console
$ spack spec gcc@11.2.0 
==> Error: Bad characters in version string: :10.2
```

### Information on your system

* **Spack:** 0.19.1
* **Python:** 3.6.8
* **Platform:** linux-centos7-haswell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Fixed by #36273 (so it's solved in v0.20)
