### ISSUE TITLE
how to avoid the use of ~/.spack completely

### ISSUE THREAD

**Issue by ghost** [LLNL/spack#36182]
Is there a way to completely avoid using or creating ~/.spack ?
So far I can't find it.
For context - this is needed:
1. on systems without dedicated user accounts, where every user shares ~/.spack
2. when running multiple spack install jobs in parallel in different slurm jobs, which all use the same ~/.spack.

So I'd like to find a way for spack to create and use files only within custom dirs, with nothing leaking out, and with no use of $HOME at all.

I tried `spack bootstrap root <dir>` , but `spack bootstrap now` still created ~/.spack with bootsrap and cache dirs.

**Comment by haampie** [comment]
See https://spack.readthedocs.io/en/latest/configuration.html#overriding-local-configuration

Set both of

```
export SPACK_USER_CONFIG_PATH=/xyz
export SPACK_USER_CACHE_PATH=/xyz
```

**Comment by ghost** [comment]
so simple... thank you.
I feel a complete idiot for missing that.
