### ISSUE TITLE
Installation issue: `wayland` gone from github

### ISSUE THREAD

**Issue by wdconinc** [LLNL/spack#36212]
### Steps to reproduce the issue

Both `wayland` and `wayland-protocols` are not fetching anymore due to freedesktop.org retiring the GitHub mirrors, https://lists.freedesktop.org/archives/wayland-devel/2023-January/042598.html.

```console
spack install wayland-protocols
```

No maintainers for `wayland` but @darmac as last contributor.

### Error message

<details><summary>Error message</summary><pre>
==> Installing wayland-1.21.0-dbj6phk5434zgizpaci3ogqev5j7e2al
==> No binary for wayland-1.21.0-dbj6phk5434zgizpaci3ogqev5j7e2al found: installing from source
==> Cannot find version 1.21.0 in url_list
==> Error: FetchError: All fetchers failed for spack-stage-wayland-1.21.0-dbj6phk5434zgizpaci3ogqev5j7e2al

/home/wdconinc/git/spack/lib/spack/spack/package_base.py:1445, in do_fetch:
       1442
       1443        self.stage.create()
       1444        err_msg = None if not self.manual_download else self.download_instr
  >>   1445        start_time = time.time()
       1446        self.stage.fetch(mirror_only, err_msg=err_msg)
       1447        self._fetch_time = time.time() - start_time
       1448

==> Warning: Skipping build of wayland-protocols-1.31-c7vest4knt3prgje5croohnmyqwg5gfp since wayland-1.21.0-dbj6phk5434zgizpaci3ogqev5j7e2al failed
</pre></details>

### Information on your system

* **Spack:** 0.20.0.dev0 (7534b8108d7e0ad1ab91753dfab44158c6e6704f)
* **Python:** 3.11.2
* **Platform:** linux-ubuntu23.04-skylake
* **Concretizer:** clingo

### Additional information

I was already working on updating wayland for newer versions. I'll file a PR for the change of URL to the primary location instead of the mirrors. This will change hashes for tar balls.

Other package that may be affected in the near future: `evemu` (also last contribution by @darmac). I'll probably just fix that one too.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by tgamblin** [comment]
Is this fixed by #36217?

**Comment by wdconinc** [comment]
It is!
