### ISSUE TITLE
satisfies promotes concrete versions to ranges

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#36251]
### Steps to reproduce

Currently a declared version 1.0 does not satisfy a when condition @:1.0.0 anymore because 1.0 is promoted to 1.0:1.0 which is indeed not a subset of :1.0.0

this breaks when conditions in general

as a solution, we need declared versions to be concrete

### Information on your system

.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Fixed by #36273
