### ISSUE TITLE
GNUtls can't find  the tarball for 3.5.9

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#3627]
Looks like @healther's  recent update to include v 3.5.9 broke the build:

```
curl: (37) Couldn't open file /home/hartzelg/tmp/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack-mirror/mirror/gnutls/gnutls-3.5.9.tar.xz
curl: (22) The requested URL returned error: 404 Not Found
[...]
==> Fetching http://www.ring.gr.jp/pub/net/gnupg/gnutls/v3.3/gnutls-3.5.9.tar.xz
==> Fetching from http://www.ring.gr.jp/pub/net/gnupg/gnutls/v3.3/gnutls-3.5.9.tar.xz failed.
==> Error: FetchError: All fetchers failed for gnutls-3.5.9-wacj7mrkudwrxskrlqxe7wcxpzrrxhx2
Build step 'Execute shell' marked build as failure
Finished: FAILURE
```

**Comment by hartzell** [comment]
It also looks like whatever changed caused the digest for 3.3.9 to be incorrect.

**Comment by healther** [comment]
sorry for that. I tested the install but forgot to clean my cache (thought ```spack purge``` does that too)

@adamjstewart: Thanks for cleaning up my mess, where would I have found the syntax for your ```url_for_version```? And would a ```list_url``` with ```list_depth=2``` also have worked?

**Comment by adamjstewart** [comment]
I tried adding a `list_url` but it didn't work, no idea why. I believe `url_for_version` is somewhere in the Packaging Guide. Basically it takes a version object as an input parameter and returns the URL for that version.

**Comment by adamjstewart** [comment]
Btw, `spack purge` doesn't clear your download cache by default but there is a flag to do that. See `spack purge --help` for details.
