### ISSUE TITLE
How can I manage a custom package.py effectively?

### ISSUE THREAD

**Issue by nkgh77** [LLNL/spack#36483]
Is there a way that enables us to handle a self-modified package.py easily?

As seen in the following ticket, I modified a package.py (more precisely, added PBS support for MVAPICH), but unfortunately, it is not successfully built in a very generic environment, and it has not been accepted.
https://mail.google.com/mail/u/0/#search/spack/FMfcgzGslbHWtKRRQzzrttnnzDpczQKh

Since the change is not huge, I might be able to apply the same modification every time when a new version comes, but at the same time, repeating the same thing is a bit cumbersome. If someone can help me to handle this situation (having my own package.py and applying the same change to the new versions), I would appreciate it.

**Comment by alecbcs** [comment]
@nkgh77 you could look at creating your own local package repository using [`spack repo create`](https://spack.readthedocs.io/en/latest/repositories.html#spack-repo-create) which would then be layered on top of the builtin repository.

**Comment by alalazo** [comment]
Closing as answered by @alecbcs
