### ISSUE TITLE
spack versions broken

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#3653]
I just ran `spack versions` on every single package in Spack and not a single one of them found a remote version. I've tested this on multiple machines with different versions of Python. Did something break in develop?

**Comment by adamjstewart** [comment]
Seems to be due to this commit: 1d1a14dbe9cfc512cedff7430b694df87b2cd5ee
```
$ git checkout 1d1a14dbe9cfc512cedff7430b694df87b2cd5ee
$ spack versions nco
==> Safe versions (already checksummed):
  4.6.5  4.6.4  4.6.3  4.6.2  4.6.1  4.5.5
==> Remote versions (not yet checksummed):
  Found no versions for nco
$ git checkout HEAD~
$ spack versions nco
==> Safe versions (already checksummed):
  4.6.5  4.6.4  4.6.3  4.6.2  4.6.1  4.5.5
==> Remote versions (not yet checksummed):
  4.6.6-alpha02  4.6.6-alpha01  4.6.5-beta01  4.6.5-alpha04  4.6.5-alpha03  4.6.5-alpha02  4.6.5-alpha01  4.6.4-beta02
```

**Comment by adamjstewart** [comment]
Got things narrowed down to the change in `lib/spack/spack/util/web.py`.

**Comment by adamjstewart** [comment]
Still not sure why things aren't working properly. I wonder if there is a bug in `six`.

**Comment by adamjstewart** [comment]
The bug was due to a missing `urlparse` import. I'll see what I can find in `six`.

**Comment by tgamblin** [comment]
Grep for urllib or six.moves and you can likely find the equivalent.

**Comment by adamjstewart** [comment]
Yep, found it. PR incoming.
