### ISSUE TITLE
Use lmod hierarchy in downstream spack

### ISSUE THREAD

**Issue by jcwright77** [LLNL/spack#36656]
### Summary

Want to use hiearchical lmod modules in user spack when using upstream spack for compiler , etc.

### Rationale

Not sure if this is a feature, a how do I do this, or a bug.
On our system, we have a global spack install that provides compilers and base libraries.

For my group, I have a spack installation pointing upstream to this spack. 'Module avail' and 'spack find' both report the builds in the global spack. lmod modules from the global install have /Core and builds with the spack installed gcc appear only after that module is loaded, same with openmpi. So far all as expected.

Now I try to use lmod modules. My packages are built with the spack gcc@12.2.0. I don't use the system gcc@8.5.0. When I add the lmod path with 'module use' their is no Core path and I just get all modules with fully qualified paths like:
 gcc/12.2.0/fftw/3.3.10-jj3f4tzo             openmpi/4.1.4-oq5tkir/gcc/12.2.0/hdf5/1.14.0-jhtonp42
And I have gcc and openmpi paths but no Core path.

If I create .spack/modules.yaml:
```
modules:
  default:
    enable::
      - lmod
    lmod:
       hash_length: 8
       whitelist:
          - gcc
       blacklist:
          - '%gcc@8.5.0'
       core_compilers:
          - 'gcc@8.5.0'
```
It has no effect  since, I think, nothing is built with gcc@8.5.0 in my spack installation and so Core would be empty and is not created.

I did rebuild the lmod tree each time I made a change. Even logged out an in again. No effect.

### Description

When I run module avail after doing module use for the path to $SPACK_ROOT/share/spack/lmod/linux-rocky8-x86_64/Core

I'd like to see an empty list under that section.
Then if I do 'module load gcc' where this module comes from upstream,
gcc@12.2.0 built modules appear.

Similarly after 'module load openmpi'
The idea eventually being to have flavors of compilers (gcc,intel) and mpi (openmpi, impi) that lmod switches between so the core module names are the same (after setting hash length to 0).

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by yantosca** [comment]
I think I am facing a similar issue with modules built by my research computing staff and Spack modules I've built against them.  See https://github.com/fasrc/User_Codes/issues/11#issuecomment-1535383127.  If anyone knows of a workaround please let me know.

**Comment by jcwright77** [comment]
Specifying core compiler in complilers.yaml kind of improves things in that
you get a /Core in the hierarchy but still is generally messed up. My work
around is just to stick to tcl modules downstream and let the upstream one
have an lmod hierarchy and encourage that maintainer to include any packages
that could be commonly used.

I think the solution is not obvious. For example, what do you do with a chain
of upstream spack installs say: system->project->user each inheriting the one
above?
-john

On Thu, May 4, 2023 5:15 pm, Bob Yantosca wrote:
> I think I am facing a similar issue with modules built by my research
> computing staff with Spack modules I've built against them.  See
> https://github.com/fasrc/User_Codes/issues/11#issuecomment-1535383127.  If
> anyone knows of a workaround please let me know.
>
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/spack/spack/issues/36656#issuecomment-1535422249
> You are receiving this because you authored the thread.
>
> Message ID: ***@***.***>


-- 
Principal Research Scientist John Wright
Office 617-253-9612
zoom: https://mit.zoom.us/my/jcwright

**Comment by jcwright77** [comment]
One workaround I've found is to manually create the module  linux/Core/gcc/12.0.0.lua for example. In that file, add the path to linux/gcc/12.0.0 and also load the upstream gcc/12.0.0.lua module. Then
ml use linux/Core
ml load gcc

will work as expected and expose the %gcc@12.0.0 built packages
