### ISSUE TITLE
Multiple build systems: second builders do not inherit phase callbacks

### ISSUE THREAD

**Issue by skosukhin** [LLNL/spack#36689]
### Steps to reproduce

```console
$ spack install netcdf-c~mpi~zstd build_system=autotools ^hdf5~mpi
$ spack install netcdf-c~mpi~zstd build_system=cmake ^hdf5~mpi
```

### Error message

Both builders ([`CMakeBuilder`](https://github.com/spack/spack/blob/74ad92e16b8a5e56152e75d264b99f006763586b/var/spack/repos/builtin/packages/netcdf-c/package.py#L195) and [`AutotoolsBuilder`](https://github.com/spack/spack/blob/74ad92e16b8a5e56152e75d264b99f006763586b/var/spack/repos/builtin/packages/netcdf-c/package.py#L215)) of [`netcdf-c`](https://github.com/spack/spack/blob/74ad92e16b8a5e56152e75d264b99f006763586b/var/spack/repos/builtin/packages/netcdf-c/package.py) inherit from [`BackupStep`](https://github.com/spack/spack/blob/74ad92e16b8a5e56152e75d264b99f006763586b/var/spack/repos/builtin/packages/netcdf-c/package.py#L181), which implements a `run_after("install")` method [`backup_nc_config`](https://github.com/spack/spack/blob/74ad92e16b8a5e56152e75d264b99f006763586b/var/spack/repos/builtin/packages/netcdf-c/package.py#L187). However, the method is run only when `build_system=cmake`. If we swap the declaration of the builders, i.e. instead of
```python
class CMakeBuilder(...):
    ...

class AutotoolsBuilder(...):
    ...
```
we do
```python
class AutotoolsBuilder(...):
    ...

class CMakeBuilder(...):
    ...
```
the `backup_nc_config` will run only when `build_system=autotools`.

I see a similar pattern in [`proj`](https://github.com/spack/spack/blob/74ad92e16b8a5e56152e75d264b99f006763586b/var/spack/repos/builtin/packages/proj/package.py) (@adamjstewart FYI) where the [`install_datum_grids`](https://github.com/spack/spack/blob/74ad92e16b8a5e56152e75d264b99f006763586b/var/spack/repos/builtin/packages/proj/package.py#L116) method is run when `build_system=cmake` but is not run when `build_system=autotools` (given the issue reported in #36688 is resolved).

@alalazo is probably the right person to mention here.

### Information on your system

* **Spack:** 0.20.0.dev0 (74ad92e16b8a5e56152e75d264b99f006763586b)
* **Python:** 3.9.2
* **Platform:** linux-debian11-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by skosukhin** [comment]
Also, it looks like [`filter_compiler_wrappers`](https://github.com/spack/spack/blob/74ad92e16b8a5e56152e75d264b99f006763586b/var/spack/repos/builtin/packages/netcdf-c/package.py#L154) has no effect on both of the builders.

**Comment by skosukhin** [comment]
I noticed one more thing: `filter_compiler_wrappers` used to be run after all `@run_after`-decorated methods specified in a package. For example,
```python
class NetcdfC(...):
    ...
    filter_compiler_wrappers("nc-config", relative_root="bin")
    ...
    @run_after("install")
    def backup_nc_config(self):
        ...
    ...
```
resulted in `backup_nc_config` being run before `filter_compiler_wrappers`.
Now, we have to be careful and put `filter_compiler_wrappers` in the right place, i.e.
```python
class NetcdfC(...):    
    ...
    @run_after("install")
    def backup_nc_config(self):
        ...
    filter_compiler_wrappers("nc-config", relative_root="bin")
    ...
```
which, I think, goes against the original idea behind `filter_compiler_wrappers`.

**Comment by alalazo** [comment]
@skosukhin I marked this one "low impact" since I see that the bugs introduced by #34935 are mostly due to an incorrect usage of a few (admittedly cryptic) mechanisms. I'll follow shortly with a bugfix, then we can have a look at #36485
