### ISSUE TITLE
Installation issue: lz4

### ISSUE THREAD

**Issue by aphecetche** [LLNL/spack#36811]
### Steps to reproduce the issue

```console
$ spack spec -I lz4 build_system=makefile
Input spec
--------------------------------
 -   lz4 build_system=makefile

Concretized
--------------------------------
 -   lz4@1.9.4%apple-clang@14.0.0 build_system=makefile libs=shared,static arch=darwin-ventura-m1

```

### Error message

<details><summary>Error message</summary><pre>
Error: TypeError: build() takes 3 positional arguments but 4 were given
</pre></details>

### Information on your system

* **Spack:** 0.20.0.dev0 (a7ae996e6ba25c5e3463cd2ecd7943a106d7c80f)
* **Python:** 3.9.6
* **Platform:** darwin-ventura-m1
* **Concretizer:** clingo

### Additional information

[spack-build-out.txt](https://github.com/spack/spack/files/11215780/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/11215781/spack-build-env.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by aphecetche** [comment]
@johnwparent

**Comment by johnwparent** [comment]
No idea how this passed CI like this... Patched and PR'd in: https://github.com/spack/spack/pull/36812
