### ISSUE TITLE
Installation issue: tmux

### ISSUE THREAD

**Issue by xdaniel9** [LLNL/spack#36994]
### Steps to reproduce the issue

```console
spack install tmux
```

### Error message

==> Bootstrapping clingo from pre-built binaries
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.4/build_cache/linux-centos7-x86_64-gcc-10.2.1-clingo-bootstrap-spack-idkenmhnscjlu5gjqhpcqa4h7o2a7aow.spec.json
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.4/build_cache/linux-centos7-x86_64/gcc-10.2.1/clingo-bootstrap-spack/linux-centos7-x86_64-gcc-10.2.1-clingo-bootstrap-spack-idkenmhnscjlu5gjqhpcqa4h7o2a7aow.spack
==> Installing "clingo-bootstrap@spack%gcc@10.2.1~docs~ipo+python+static_libstdcpp build_type=Release arch=linux-centos7-x86_64" from a buildcache
==> Error: Couldn't find patch for package builtin.berkeley-db with sha256: 26090f418891757af46ac3b89a9f43d6eb5989f7a3dce3d1cfc99fba547203b3

### Information on your system

$ spack debug report
* **Spack:** 0.19.2
* **Python:** 3.10.9
* **Platform:** linux-centos7-haswell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
Did you switch from new to old spack? Sometimes you need to manually invalidate cache `spack clean -m`.

**Comment by xdaniel9** [comment]
> Did you switch from new to old spack? Sometimes you need to manually invalidate cache `spack clean -m`.

this command worked for me, thanks a lot
