### ISSUE TITLE
--format of dependency's hash is wrong

### ISSUE THREAD

**Issue by sebhinck** [LLNL/spack#37018]
### Steps to reproduce

I wanted to get the hash from a dependency package and there seems to be a bug. The problem should arise with any spec/dependency combination. Here my example:

```console
$ spack find -ld perl
-- linux-rocky8-zen / gcc@8.5.0 ---------------------------------
mwalrc6 perl@5.36.0
lzfh6ek     berkeley-db@18.1.40
t64oo25     bzip2@1.0.8
lfzvmkn         diffutils@3.9
cv75ifv             libiconv@1.17
u6bdgsp     gdbm@1.23
jrjkg7s         readline@8.2
idtlmtd             ncurses@6.4
m7qknuv                 pkgconf@1.8.0
rw3jnfu     zlib@1.2.13

==> 1 installed package
$ spack find --format="{^gdbm.name}" perl
gdbm
$ spack find --format="{^gdbm.hash}" perl
mwalrc6y3ii2ogb37vk664pqyzrajndq
```

Here in debug mode:
```console
$ spack --debug find --format="{^gdbm.hash}" perl
==> [2023-04-19-08:29:35.866029] Imported find from built-in commands
==> [2023-04-19-08:29:35.866721] Imported find from built-in commands
==> [2023-04-19-08:29:35.867928] Reading config from file /albedo/home/shinck/tmp/spack/etc/spack/defaults/config.yaml
==> [2023-04-19-08:29:35.888015] DATABASE LOCK TIMEOUT: 60s
==> [2023-04-19-08:29:35.888054] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-04-19-08:29:35.899897] Reading config from file /albedo/home/shinck/tmp/spack/etc/spack/defaults/repos.yaml
mwalrc6y3ii2ogb37vk664pqyzrajndq
```

### Error message

There is no error message.

However, if you look at the above output you see that the hash of the dependency package is wrong. It shows the hash of the "original" package instead. Whereas the name of the dependency package is shown correctly!

### Information on your system

```console
$ spack debug report 
* **Spack:** 0.20.0.dev0 (11e5b0cd917cca4665f9e19e078fdd94df418485)
* **Python:** 3.6.8
* **Platform:** linux-rocky8-zen2
* **Concretizer:** clingo
```

For this test I did not change spack's default configuration.

But it also shows the same problem with Spack 0.18.1

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by becker33** [comment]
Fixed in #37073 

I also edited the description for clarity distinguishing between "dependent" and "dependency"
