### ISSUE TITLE
Cannot find any package installation

### ISSUE THREAD

**Issue by thiagotei** [LLNL/spack#3709]
I decided to upgrade my spack and nothing works anymore.
So, I decided to have a fresh installation and got the latest tag 0.10.0.

```
$ spack find -p 
==> 4 installed packages.
-- linux-rhel6-x86_64 / gcc@4.6.1 -------------------------------
    libffi@3.2.1       /usr/workspace/wsa/bluenet/thiago/spack/opt/spack/linux-rhel6-x86_64/gcc-4.6.1/libffi-3.2.1-dtonmgxweviawxhaxh5ksuoyzjoprq7u
    ruby@2.2.0         /usr/workspace/wsa/bluenet/thiago/spack/opt/spack/linux-rhel6-x86_64/gcc-4.6.1/ruby-2.2.0-qezm2l32dhzutgy7eqnfec3tk2rjkliv
    tmuxinator@0.6.11  /usr/workspace/wsa/bluenet/thiago/spack/opt/spack/linux-rhel6-x86_64/gcc-4.6.1/tmuxinator-0.6.11-75czzxglwibzesozshh4tfev3v5ryrfs
    zlib@1.2.10        /usr/workspace/wsa/bluenet/thiago/spack/opt/spack/linux-rhel6-x86_64/gcc-4.6.1/zlib-1.2.10-dwavb3pn4os4kosd2zneb5bpjzpkeygn
```
However, it cannot find any package install:

```
$ spack use tmuxinator
Prepending: tmuxinator-0.6.11-gcc-4.6.1-75czzxg (not found)
```
Thanks

**Comment by adamjstewart** [comment]
If you run:
```
$ spack install tmuxinator
```
does Spack try to reinstall `tmuxinator`?

**Comment by alalazo** [comment]
The problem here seems to be related to the `dotkit` support, but it's difficult to say more about it at the moment...

**Comment by adamjstewart** [comment]
Ah, I see. I was wondering if it was just a case of changing hashes. How popular is `dotkit`?

**Comment by alalazo** [comment]
>  I was wondering if it was just a case of changing hashes.

Maybe some paths in the dotkit module files have been written with a shorter version of the hash, but this is just a guess. 

> How popular is dotkit?

As far as I know dotkits are used by just a few sites (including LLNL).

**Comment by thiagotei** [comment]
Now I could `spack use tmuxinator`:
`Prepending: tmuxinator-0.6.11-gcc-4.6.1-75czzxg (ok)`
I don't know what exactly changed in my environment.
I got out the machine and came back.
Also, sometimes this is happening:
```
$ spack -V
-bash: $1: unbound variable
```

**Comment by adamjstewart** [comment]
For information about that bash error message, see http://redsymbol.net/articles/unofficial-bash-strict-mode/

I'll take a look.

**Comment by adamjstewart** [comment]
I wasn't able to reproduce the unbound variable bug. I tried:
```
$ set -u
$ spack -V
```
but it worked with no problems. It may have something to do with your environment. If you want to get rid of that warning permanently, add `set +u` to your `~/.bashrc`.

**Comment by thiagotei** [comment]
I had  `set  -u` on my `. bashrc`.
Should it be `set +u`?

**Comment by adamjstewart** [comment]
The default is `set +u`. Why did you put `set -u` in your `~/.bashrc`?

**Comment by thiagotei** [comment]
I'm trying to remember why. I think it was something related to spack as well. Weird.
Thanks anyway!

**Comment by tgamblin** [comment]
>> How popular is dotkit?

> As far as I know dotkits are used by just a few sites (including LLNL).

AFAIK, *just* LLNL, and we've switched to `lmod` on our [latest generation Linux machines (CTS-1)](https://www.llnl.gov/news/labs-tap-silicon-valley-bolster-computing)).  We're still using dotkit on the [previous generation (TLCC2)](https://asc.llnl.gov/computing_resources/tlcc/), which may be around for a bit longer.

**Comment by thiagotei** [comment]
I'm happy using cab, hope it stays around :)

**Comment by adamjstewart** [comment]
Ah, so it's the equivalent of ANL's [SoftEnv](http://www.mcs.anl.gov/hs/software/systems/softenv/softenv-intro.html). We're also slowly phasing it out and moving towards Lmod with our newest cluster.

**Comment by thiagotei** [comment]
@adamjstewart I found why I decided to add `set -u`. We discussed this issue already! Look at this [comment made by you ](https://github.com/LLNL/spack/issues/2417#issuecomment-263094637).

**Comment by adamjstewart** [comment]
Ah that's right. Yes, I still wouldn't recommend it. Most Bash scripts are developed assuming that this feature is not set, so it can have unintended consequences. Let me check one last time to see if our scripts work with this set.

**Comment by adamjstewart** [comment]
Ah, I see the problem now. It can be recreated by running:
```
$ set -u
$ source $SPACK_ROOT/share/spack/setup-env.sh
$ spack
```
I'll see if I can fix it. Maybe you should keep it on so you can find more bugs in Spack 😆

**Comment by thiagotei** [comment]
Yes! That's what I was doing on my `.bashrc`. Sorry for not mentioning it.
[Some people advise](http://www.davidpashley.com/articles/writing-robust-shell-scripts/) the use of `set -u`.

**Comment by adamjstewart** [comment]
Oh I completely agree! See [this article](http://redsymbol.net/articles/unofficial-bash-strict-mode/) too. I always add `set -u` to my scripts when I write them. But not to my `~/.bashrc` because that is equivalent to running everyone else's scripts with this setting, whether they expect this or not. If you want to check only your `.bashrc` file, you can add `set -u` to the top and `set +u` to the bottom.

**Comment by thiagotei** [comment]
@adamjstewart Good idea! Thanks
