### ISSUE TITLE
==> Error: YAML ProviderIndex was not a dict.

### ISSUE THREAD

**Issue by ulrikeyang** [LLNL/spack#3716]
I tried to use spack to install xsdk had some issues and then used spack clean xsdk .
Now I keep getting the error message
==> Error: YAML ProviderIndex was not a dict.
even after uninstalling and reinstalling spack.
Anybody know what is going on, and how I can get rid of this problem?
Thanks
Ulrike

**Comment by scheibelp** [comment]
If you completely removed spack, there may be lingering configuration in ```~/.spack/``` - you could try moving that (or removing it if you haven't customized the configuration).

Could you rerun the command with "-d": e.g. ```spack -d install ...``` and include the full stack trace here?

**Comment by ulrikeyang** [comment]
Removing the .spack directory and doing a complete fresh install removed the problem.
Thanks
