### ISSUE TITLE
Valid code is making build crash on GitHub Actions

### ISSUE THREAD

**Issue by DNA-PC** [LLNL/spack#37165]
### Here is a video of the issue:
https://watch.screencastify.com/v/0v4BQsUPP90OZf5iu8pQ

### Steps to reproduce

```
spack
```

### Error message

```
$ spack
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

[Error: load_transformed failed

Caused by:
    0: failed to analyze module
    1: failed to resolve regenerator-runtime from /home/runner/work/MonCDI/MonCDI/src/apps/Espace Client/global-script.ts
    2: index not found] {
  code: 'GenericFailure'
}

Node.js v18.16.0
```

### Information on your system

```js
    fetch(zapierWebhookUrl, {
      method: 'POST',
      body: JSON.stringify(data),
    })
      .then(async (response) => {
        const result = await response.json();
        console.debug('[Custom script] Zapier result', result);

        if (result?.status === 'success') {
          // Store the fact we already synced the user in LS, to avoid performing too many invocations to Zapier (to reduce costs)
          localStorage.setItem(LS_KEY_SYNCED_REGISTERED_DATE, '1')
        } else {
          console.error(`[Custom script] Error occurred:`, result)
        }
      })
      .catch((error) => {
        throw new Error(error)
      })
```

For some reason, this code (which is built fine using Spack on a local computer) crashes when built on GitHub Actions.
![image](https://user-images.githubusercontent.com/107790761/234073027-69736e25-06fb-4fa5-a046-37af66770375.png)

When I comment out the above code, the build passes with success.

![image](https://user-images.githubusercontent.com/107790761/234073151-977bad08-8255-4f6e-8a1b-60ab2b42f09b.png)

I can only guess this is some async/await issue, probably an edge case when mixing await in a `then` or stuff like that.

---

I ran `spack debug report`:
```
Bundling done: 0s 55.354375ms
Done: 0s 0.160166ms
```
I couldn't find a local file in the project to attach, though... Not sure what's supposed to be done.

Debugging isn't easy because the issue only happens on GitHub Actions...
For some reason, it works fine locally. 

I use Node16 locally and Node18 on GHA, but even using Node16 on GHA yields the same result.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
I'm afraid this was submitted to the wrong repo 🤔 this spack is not a bundler for javascript projects, but a package manager.

**Comment by Vadorequest** [comment]
Indeed, you're right. Sorry about that.

Follow-up:
https://github.com/swc-project/swc/issues/7329
