### ISSUE TITLE
Want "spack dependencies"

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#372]
The subcommand `dependents` shows which packages depend on a particular package. I'm looking for the converse, a command that lists the (transitive) dependencies of an installed package.

**Comment by tgamblin** [comment]
What about `spack find -d`?

**Comment by eschnett** [comment]
Yes, thanks.

**Comment by tgamblin** [comment]
There is also `spack graph [--ascii|--dot]` although it doesnt show deps for an installed package yet. It does show connectivity better, though. Fixing #311 and #369 will allow that, though.
