### ISSUE TITLE
Providing scalapack with intel-oneapi-mkl +cluster breaks a few packages

### ISSUE THREAD

**Issue by hpcnpatel** [LLNL/spack#37374]
### Steps to reproduce the issue

Let me explain the issue with intel-oneapi-mkl +cluster.

Scalapack, Lapack, and Blas interfaces are provided via intel-oneapi-mkl by enabling a variant "+cluster". 

In order to satisfy cluster library interfaces for many client packages, the ideal way is to set it in the package.yaml file exclusively. 

```
cat packages.yaml

packages:

  scalapack:
    require: 'intel-oneapi-mkl +cluster'

  lapack:
    require: 'intel-oneapi-mkl +cluster'

  blas:
    require: 'intel-oneapi-mkl +cluster'

```

Adding this +cluster variant breaks a few packages builds. Without +cluster variant, intel-oneapi-mkl is never concretized as a provider of Scalapack, lapack, and blas libraries.

For reference here are some of the errors I am facing when enabling "**intel-oneapi-mkl +cluster**" to get the cluster libs interface. 

1) Arpack-ng and Sundial fails with a similar error signature:

```console
$> spack --env . install 
==> Starting concretization
==> Environment concretized in 31.10 seconds.
==> Concretized arpack-ng%intel
==> Concretized arpack-ng%intel
 -   2ywjnjj  arpack-ng@3.9.0%intel@2023.1.0~icb~ipo+mpi+shared build_system=cmake build_type=RelWithDebInfo generator=make arch=linux-sles15-haswell
[+]  sjtcyti      ^cmake@3.26.3%intel@2023.1.0~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-sles15-haswell
[+]  aqz2wny          ^ncurses@6.4%intel@2023.1.0~symlinks+termlib abi=none build_system=autotools arch=linux-sles15-haswell
[+]  ttkoosz              ^pkgconf@1.8.0%intel@2023.1.0 build_system=autotools arch=linux-sles15-haswell
[+]  on3muvc          ^openssl@1.1.1t%intel@2023.1.0~docs~shared build_system=generic certs=mozilla arch=linux-sles15-haswell
[+]  44xqvtw              ^ca-certificates-mozilla@2023-01-10%intel@2023.1.0 build_system=generic arch=linux-sles15-haswell
[+]  lqahcum              ^perl@5.36.0%intel@2023.1.0+cpanm+open+shared+threads build_system=generic arch=linux-sles15-haswell
[+]  2jh7jzs                  ^berkeley-db@18.1.40%intel@2023.1.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-sles15-haswell
[+]  fmjuxfz                  ^bzip2@1.0.8%intel@2023.1.0~debug~pic+shared build_system=generic arch=linux-sles15-haswell
[+]  a7oxann                      ^diffutils@3.9%intel@2023.1.0 build_system=autotools arch=linux-sles15-haswell
[+]  pndnpl6                          ^libiconv@1.17%intel@2023.1.0 build_system=autotools libs=shared,static arch=linux-sles15-haswell
[+]  w4eg7l5                  ^gdbm@1.23%intel@2023.1.0 build_system=autotools arch=linux-sles15-haswell
[+]  jkkaq5j                      ^readline@8.2%intel@2023.1.0 build_system=autotools patches=bbf97f1 arch=linux-sles15-haswell
[+]  cf7cfdn              ^zlib@1.2.13%intel@2023.1.0+optimize+pic+shared build_system=makefile arch=linux-sles15-haswell
[+]  kbzqf3m      ^gmake@4.4.1%intel@2023.1.0~guile build_system=autotools arch=linux-sles15-haswell
[+]  s5ehoc7      ^intel-oneapi-mkl@2023.1.0%intel@2023.1.0+cluster+envmods~ilp64+shared build_system=generic arch=linux-sles15-haswell
[+]  3jzbxbh          ^intel-oneapi-tbb@2021.9.0%intel@2023.1.0+envmods build_system=generic arch=linux-sles15-haswell
[+]  prg6h64      ^intel-oneapi-mpi@2021.9.0%intel@2023.1.0+envmods~external-libfabric~generic-names~ilp64 build_system=generic arch=linux-sles15-haswell

...
...
...

==> arpack-ng: Executing phase: 'cmake'
==> arpack-ng: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    '/dss/dsshome1/09/di36pex/SPACK_lrz_dir/spack19/opt/haswell/gmake/4.4.1-intel-kbzqf3m/bin/make' '-j24'

1289 errors found in build log:
  >> 572     ld: /dss/dsshome1/09/di36pex/SPACK_lrz_dir/spack19/opt/haswell/intel-oneapi-mkl/2023.1.0-intel-s5ehoc7/mkl/2023.1.0/lib/intel64/libmkl_blacs_intelmpi_lp64.so: undefined reference to `MPI_Waitall'
  >> 573     ld: /dss/dsshome1/09/di36pex/SPACK_lrz_dir/spack19/opt/haswell/intel-oneapi-mkl/2023.1.0-intel-s5ehoc7/mkl/2023.1.0/lib/intel64/libmkl_blacs_intelmpi_lp64.so: undefined reference to `MPI_Abort'
...
```

2) Latte:

```console
$> spack install latte
==> Installing latte-1.2.2-3in27dsvmo7wu3vw75xdyzdurfymc4j6
==> Error: ProcessError: Command exited with status 2:
58 errors found in build log:
...
...
            023.1.0-gcc-552aahy/mkl/2023.1.0/lib/intel64/libmkl_blacs_intelmpi_lp64.so -lpthread -lm /usr/lib64/libdl.so
  >> 556    /usr/bin/ld: /dss/dsshome1/09/di36pex/SPACK_lrz_dir/spack19/opt/haswell/intel-oneapi-mkl/2023.1.0-gcc-552aahy/mkl/2023.1.0/lib/intel64/libmkl_blacs_intelmpi_lp64.so: undefined reference to `MPI_Waitall'
  >> 557    /usr/bin/ld: /dss/dsshome1/09/di36pex/SPACK_lrz_dir/spack19/opt/haswell/intel-oneapi-mkl/2023.1.0-gcc-552aahy/mkl/2023.1.0/lib/intel64/libmkl_blacs_intelmpi_lp64.so: undefined reference to `MPI_Abort'
...
```

3) hpl:

```console

$> spack install hpl
==> Installing hpl-2.3-dvsnvkdinsj4a5oksk6r75uctvy3jn3f
==> Error: ProcessError: Command exited with status 77:
2 errors found in build log:
     9     checking whether the C compiler works... no
  >> 10    configure: error: in `/gpfs/scratch/pr28fa/di36pex/di36pex/haswell/spack-stage-hpl-2.3-dvsnvkdinsj4a5oksk6r75uctvy3jn3f/spack-src':
  >> 11    configure: error: C compiler cannot create executables
     12    See `config.log' for more details
```

4) Atompaw:

```console
$> spack install atompaw
==> Installing atompaw-4.2.0.2-q6jmhh5qabgr3yhtuyopsjzcqekjq2b6
==> Error: ProcessError: Command exited with status 1:
    '/gpfs/scratch/pr28fa/di36pex/di36pex/haswell/spack-stage-atompaw-4.2.0.2-q6jmhh5qabgr3yhtuyopsjzcqekjq2b6/spack-src/configure' '--prefix=/dss/dsshome1/09/di36pex/SPACK_lrz_dir/spack19/opt/haswell/atompaw/4.2.0.2-gcc-q6jmhh5' '--with-linalg-libs=-L/dss/dsshome1/09/di36pex/SPACK_lrz_dir/spack19/opt/haswell/intel-oneapi-mkl/2023.1.0-gcc-552aahy/mkl/2023.1.0/lib/intel64 -L/usr/lib64 -lmkl_scalapack_lp64 -lmkl_cdft_core -lmkl_intel_lp64 -lmkl_sequential -lmkl_core -lmkl_blacs_intelmpi_lp64 -lpthread -lm -ldl' '--enable-libxc' '--with-libxc-incs=-I/dss/dsshome1/09/di36pex/SPACK_lrz_dir/spack19/opt/haswell/libxc/6.1.0-gcc-m2dquhn/include' '--with-libxc-libs=-L/dss/dsshome1/09/di36pex/SPACK_lrz_dir/spack19/opt/haswell/libxc/6.1.0-gcc-m2dquhn/lib -lxcf90 -lxc'

1 error found in build log:
     110    checking how to hardcode library paths into programs... immediate
     111    configure:
     112    configure: ===== Looking for Linear Algebra libraries
     113    configure: ...Linear Algebra: trying with command-line options
     114    checking for library containing zhpev... no
     115    checking for library containing zgemm... no
  >> 116    configure: error: Linear Algebra libraries (blas, lapack) were not found with the specified --with_linalg_libs/--with_linalg_prefix
```

5) R:

```console
$> spack install r +X+external-lapack

==> Installing r-4.2.2-u7bzlaku22m3kgrpyt6dblzq6i7wjaqo
...
1 error found in build log:
     396    checking whether 'struct tm' includes tm_zone... yes
     397    checking whether 'struct tm' includes tm_gmtoff... yes
     398    checking for dgemm_ in -L/dss/dsshome1/lrz/sys/spack/release/23.1.0/opt/haswell/intel-oneapi-mkl/2023.1.0-gcc-552aahy/mkl/2023.1.0/lib/intel64 -L/usr/lib64 -lmkl_scalapack_lp64 -lmkl_cdft_core -lmkl_gf_lp64 -lmkl_sequential -lmkl_core -lmkl_blacs_intelmpi_lp64 -lpthrea
            d -lm -ldl... no
  >> 399    configure: error: BLAS was specified but not available

```

### Error message

-

### Information on your system

$> spack debug report 
* **Spack:** 0.20.0.dev0 (4363b1c2dcdae9245054cd44124f8ac6789bfd39)
* **Python:** 3.6.12
* **Platform:** linux-sles15-haswell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [ ] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [ ] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by hpcnpatel** [comment]
@rscohn2 Hi, could you look into this issue?

**Comment by rscohn2** [comment]
This will reproduce the problem:
```
spack install latte%oneapi ^intel-oneapi-mkl+cluster ^intel-oneapi-mpi
```

I see you closed this issue. Did you find a solution?

**Comment by hpcnpatel** [comment]
Hi, I closed the issue to make a few more build tests. I see that I am setting,

```
cat packages.yaml

packages:

  scalapack:
    require: 'intel-oneapi-mkl +cluster'

  lapack:
    require: 'intel-oneapi-mkl +cluster'

  blas:
    require: 'intel-oneapi-mkl +cluster'

```

I think setting +cluster for lapack and blas is not right. 

So tried, with 

```
cat packages.yaml

packages:

  scalapack:
    require: 'intel-oneapi-mkl +cluster'

  lapack:
    require: 'intel-oneapi-mkl'

  blas:
    require: 'intel-oneapi-mkl'

```

This might fix a few packages. 

For example, this might fix arpack-ng but gmsh which depends on arpack-ng fails. For your info, when I add netlib-* as provider of cluster libs, the installation is okay for both arpack-ng and gmsh. 

Also, How to set an individual provider, mkl +cluster for ScaLAPACK and not for lapack or blas if the definition is not in the packages.yaml file?

I can post more errors of packages if you want, let me know.

**Comment by rscohn2** [comment]
I looked at the build for latte. It is not configured to use MPI so it does not link with the MPI libraries. When you use +cluster, it add libraries that need MPI to the link line (intel-oneapi-mkl+cluster has a depends_on mpi), but MPI is not found. That seems like reasonable behavior for the mkl package.

It is hard to look at these when I don't know exactly what you are doing. If you show me something that can be reproduced, I can try to look at it.

**Comment by rscohn2** [comment]
After thinking about it some more, I could have the mkl package add the mpi libraries when cluster is enabled. That would make it behave more like netlib.

**Comment by rscohn2** [comment]
Please check if #37386 helps.

**Comment by hpcnpatel** [comment]
Sorry, If I was all over the place listing the errors and not clear on what I wanted to achieve. I am building a quite large software stack (~100 packages) for our users. 

Thanks for providing the fix, it works for arpack-ng, lattte and gmsh packages.

I will do further builds and check if the changes are okay for most of the packages in the software stack. 

I will get back to you.

**Comment by rscohn2** [comment]
I will try to get the PR merged. It fixed hpl for me, as well. Thanks for reporting the issue!

**Comment by hpcnpatel** [comment]
Thanks, one more question do you think the documentation on Spack needs to be changed about using intel-oneapi-mpi and -mkl? Or having a reference to intel-mpi & -mkl in most of the documentation is okay?

Refer: https://spack.readthedocs.io/en/latest/build_systems/intelpackage.html

**Comment by rscohn2** [comment]
> Refer: https://spack.readthedocs.io/en/latest/build_systems/intelpackage.html

We have this: https://spack.readthedocs.io/en/latest/build_systems/inteloneapipackage.html
Suggestions are welcome for how to direct people to best information. Maybe it is time to deprecate the intel-mpi and intel-mkl packages.

**Comment by hpcnpatel** [comment]
Thanks for your comments. I am aware of the page you mentioned but the information is not complete here https://spack.readthedocs.io/en/latest/build_systems/intelpackage.html. Specifically https://spack.readthedocs.io/en/latest/build_systems/intelpackage.html#selecting-libraries-to-satisfy-virtual-packages

Again, thanks for your quick support.
