### ISSUE TITLE
Hardlinked files are handled inconsistently when creating binary packages.

### ISSUE THREAD

**Issue by Paul-Ferrell** [LLNL/spack#37390]
### Steps to reproduce

```console 
spack install git
spack mirror add foo /tmp/foo
spack buildcache create -m foo --only git -a "/<hash of git package"
```

Checkout the contents of the installed git's `libexec/git-core/` directory. There are a ton of files there, but most of them are just hardlinks to the the same place. 
Then checkout the `.spack/binary_distribution` file - Only a small fraction of files that are in `libexec/git-core/` are listed under the `relocate_*` keys. That would be fine, except when Spack creates the binary distro it simply creates a tarball, and that doesn't recreate the hardlinks when extracted. 

The result is that one each set of hardlinked files (semi-randomly) will get properly relocated - the rest will be left with their original paths/rpaths.

If you want, you can install that binary package and use `readelf -d` or `ldd` to see that the paths are old and/or broken. (Note that if you install it on the same system, the library paths won't be broken as the original install location will still exist).

### Error message

None

### Information on your system

* **Spack:** 0.19.0 (cb0b70f0d588a067b8bbbf61ae3074debf4088ce)
* **Python:** 3.6.15
* **Platform:** linux-sles15-icelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
Hardlinks should be preserved in the tarball and relocation should be in-place 🤔

**Comment by haampie** [comment]
I cannot reproduce this on `develop`. Hardlinks remain hardlinks: in the tarball, when extracted, and after relocation.

**Comment by Paul-Ferrell** [comment]
Yeah, I see that now. Yet when the packages install the hardlinks are not preserved for us.  I'm looking into it now.

**Comment by Paul-Ferrell** [comment]
So yes, hardlinks are preserved in the tarfile.  They aren't preserved upon extraction (either via Spack or the tar command) on our Shasta systems. So yay!  
It would be nice if this were a filesystem problem, but no, hardlinks work fine.  It's at tar library issue. Sigh.

**Comment by Paul-Ferrell** [comment]
I'm baaack.

It was a Spack issue after all. 

- The tarball extracts fine under Spack, hardlinks preserved.
- Then Spack moves it into place at `spec.prefix`. 
- **Boom!** hardlinks are gone. 

What's happening is that in some circumstances (and I can't find why it's not all circumstances, but it's consistent for us), the `shutil.move` throws an error because the dest dir doesn't exist (IE the parent of `spec.prefix`). `shutil.move` then falls back to doing a `shutil.copytree`, which silently creates the missing parent directories.  It does not, however, preserve hard links.

**Comment by haampie** [comment]
Oof. Thanks for the detective work! 👏 

I never understood why things are not extracted directly into place, that sounds much more sensible to me.
