### ISSUE TITLE
Requiring a specific name for the envfile breaks existing workflows

### ISSUE THREAD

**Issue by greenc-FNAL** [LLNL/spack#37410]
### Steps to reproduce

We generate and store multiple similar `spack.yaml` files from a template, such as:
```console
critic@2.12.02-clang@14.0.6-cxx17-prof-gcc@4.8.5.yaml
critic@2.12.02-clang@15.0.7-cxx17-prof-gcc@4.8.5.yaml
critic@2.12.02-gcc@12.2.0-cxx17-prof-gcc@4.8.5.yaml
critic@2.12.02-gcc@12.2.0-cxx20-prof-gcc@4.8.5.yaml
critic@2.12.02-gcc@13.1.0-cxx20-prof-gcc@4.8.5.yaml
critic@2.12.02-gcc@8.2.0-cxx17-prof-gcc@4.8.5.yaml
critic@2.12.02-gcc@9.3.0-cxx17-prof-gcc@4.8.5.yaml
```
We then use `spack env create <env-name> <file>` to create a suitable environment and then concretize and build it.

We were also planning to extend this to use concretized environment config files, which would have been similarly named.

#36927 breaks this by requiring that the provided environment config file actually be named `spack.yaml` or `spack.lock`.

Is there really no other way to distinguish one type of environment config file from the other without constraining the name?

### Information on your system

* **Spack:** 0.20.0.dev0
* **Python:** 3.6.8
* **Platform:** linux-scientific7-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
I had a similar discussion on this yesterday with @mdorier on slack [here](https://spackpm.slack.com/archives/CMHK7MF51/p1683023649635819) Posting also a screenshot, since the discussion was public and it will be lost in time:

![Screenshot from 2023-05-03 20-47-40](https://user-images.githubusercontent.com/4199709/236014411-796cbab0-d8a0-4c97-aecb-41e8e86a6837.png)

---

The good news is that the lines enforcing this behavior are much localized:

https://github.com/spack/spack/blob/59e2ef6ad64b12fd7f168308f3ac87b7472d2994/lib/spack/spack/environment/environment.py#L2536-L2541

I remain of the opinion expressed above, but in case it wouldn't be hard to lift enforcing the filename.

**Comment by alalazo** [comment]
For the record, yesterday I also checked:
- https://spack-tutorial.readthedocs.io/en/latest/tutorial_environments.html# 
- https://spack.readthedocs.io/en/latest/environments.html

and couldn't find a single example where we use a name that is not `spack.yaml`. Before #36927, anything was fine as a name when creating an environment, but when activating the environment a `spack.yaml` file was required. 

For the lockfile, after #36927 it should be named `spack.lock`, before `*.lock` (which was also inconsistent and not documented).

**Comment by greenc-FNAL** [comment]
I always interpreted the 'spack.yaml' or 'spack.lock' as describing the character and purpose of the file rather than its name.
The ability to generate environment config files and store them for later use is quite important to us, and enforcing a single filename for each type of file and relying on (say) file location for specificity is a high risk for information loss. Just a few days ago on Slack maintainers channel @becker33 viewed favorably the idea of being able to accept environment config files via URL.

I would much prefer the behavior of assuming that a given file or URL describes a `spack.yaml`-type environment configuration unless one provides a non-default flag (say, `--concrete`). Unless I'm misreading things, since the given file was copied into place in the defined (or defaulted) environment directory as `spack.yaml` or `spack.lock` anyway by `spack env create`, it would seem that the filename provided on the command line is irrelevant if there is another way to distinguish  a `spack.yaml`-type file from a `spack.lock`-type one.

**Comment by alalazo** [comment]
I'm fine reverting the place where we enforce the file name, but what should distinguish a lockfile from a manifest? Only the suffix? Also, I'd like to document the behavior properly and be consistent with what the command line help and documentation say.

For the record, any name for the manifest was allowed before:

![Screenshot from 2023-05-02 14-15-04](https://user-images.githubusercontent.com/4199709/236020590-ca585a61-3da1-41f4-8143-1f1767f28e88.png)

and seemed to derive from using an `else` condition after a check on whether the filename ends with `.lock`.

**Comment by mdorier** [comment]
It looks like the code uses `endswith(...)`, so maybe it's still possible to call the file `<whatever>.spack.yaml`? (I haven't tried)

Also note that valid extensions for yaml files are either .yaml or .yml, so it's a bit odd that even `spack.yml` would be refused.

**Comment by alalazo** [comment]
Let me submit a PR to go back to the previous behavior, and enforce consistency by changing the command line help and docs.

**Comment by greenc-FNAL** [comment]
> Let me submit a PR to go back to the previous behavior, and enforce consistency by changing the command line help and docs.

@alalazo Please see https://github.com/spack/spack/pull/37413 with the implementation of my desired behavior. I will be happy to render docs and command-line help consistent but I wanted you to see what I was thinking first.
