### ISSUE TITLE
Installation issue: Unsatisfiable version in py-apache-beam

### ISSUE THREAD

**Issue by jfinney10** [LLNL/spack#37414]
### Steps to reproduce the issue

```console
$ spack spec -I py-apache-beam%gcc@11.2.0
```

Tagging maintainers: @adamjstewart @pradyunsg 

### Error message

<details><summary>Error message</summary>

<pre>
==> Error: concretization failed for the following reasons:

   1. Cannot satisfy 'py-dill@0.3.1.1:0.3.1'
</pre></details>

### Information on your system

This is on OLCF's test system, Peak:

* **Spack:** 0.20.0.dev0 (9d681008914f33ca6a09c623906caa707b7f597b)
* **Python:** 3.6.8
* **Platform:** linux-rhel8-power9le
* **Concretizer:** clingo

### Additional information

<pre>
compilers:
  - compiler:
      spec: gcc@11.2.0
      operating_system: rhel8
      modules: [gcc/11.2.0]
      paths:
        cc: gcc
        cxx: g++
        f77: gfortran
        fc: gfortran
      extra_rpaths: []
      environment:
        append_path:
          PKG_CONFIG_PATH: /usr/lib64/pkgconfig
      flags: {}
</pre>

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by jfinney10** [comment]
Seems to have been changed here:

https://github.com/spack/spack/commit/c2e1a12cdf44edd7f29e465bbdfdc511b97d9669#diff-8baf97f592cc6a2ec17c1b82f6213dfa724cd661c69704448019efc25b8bb14c

from previous dependency on py-dill was:
<pre>
depends_on('py-dill@0.3.1:0.3.2', type=('build', 'run'))
</pre>

is now
<pre>
depends_on('py-dill@0.3.1.1:0.3.1', type=('build', 'run'))
</pre>

**Comment by adamjstewart** [comment]
Fixed by #37415 

@alalazo I'm curious why the package audit didn't catch this.
