### ISSUE TITLE
lua@5.4.5: could not find any remote versions for lua, cannot fetch

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#37427]
### Steps to reproduce the issue

Using `spack@develop` (e6d37b3b612617c02700ac3500d5eed7602011f0 from `Thu May 4 13:48:24 2023 +0200`):

```
$> spack info lua
...
MakefilePackage:   lua

Description:
    The Lua programming language interpreter and library.

Homepage: https://www.lua.org

Preferred version:
    5.4.5    https://www.lua.org/ftp/lua-5.4.5.tar.gz

Safe versions:
    5.4.5    https://www.lua.org/ftp/lua-5.4.5.tar.gz
    5.4.4    https://www.lua.org/ftp/lua-5.4.4.tar.gz
    5.4.3    https://www.lua.org/ftp/lua-5.4.3.tar.gz
...
```

The most recent version shown above is `lua@5.4.5`, but there is a problem:
```
$> spack checksum lua@5.4.5
==> Error: Could not find any remote versions for lua

$> spack fetch lua
==> Error: All fetchers failed for spack-stage-lua-5.4.5-sz7ilnwmrw2uu5hofjzkfngr4pvtkojm
```

### Error message

<details><summary>Error message</summary>

<pre>
... see above
</pre></details>

### Information on your system

* **Spack:** 0.20.0.dev0 (42ede698c26ccf9b1bae1daa2d9df68820191497)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** clingo

### Additional information

NA

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by benc303** [comment]
Version 5.4.5 isn't in the [download area](https://www.lua.org/ftp/) or on the [version history page](https://www.lua.org/versions.html). Does it actually exist?

**Comment by alecbcs** [comment]
I've never seen a project scrub a release like this. It's still on [their work area page](https://www.lua.org/work/) with the announcement of them releasing v5.4.5 but they've wiped it from the FTP server and the official announcement on their news bulletin.
