### ISSUE TITLE
Build Rose compiler needs .git information

### ISSUE THREAD

**Issue by thiagotei** [LLNL/spack#3749]
I'm trying to install Rose with spack using my custom packaging code.
However, even though I specified to fetch a commit, it gets it through tar.gz, but Rose needs the .git dir apparently. How to fetch the without getting the tar.gz?

Partial spack output:
```
==> Using cached archive: /usr/workspace/wsa/bluenet/thiago/spack/var/spack/cache/rose/rose-0.9.8.tar.gz
==> Warning: Fetching from mirror without a checksum!
  This package is normally checked out from a version control system, but it has been archived on a spack mirror.  This means we cannot know a checksum for the tarball in advance. Be sure that your connection to this mirror is secure!.
==> Already staged rose-0.9.8-usp52z54qgddkhicclxmlcsy3amfc3eq in /usr/workspace/wsa/bluenet/thiago/spack/var/spack/stage/rose-0.9.8-usp52z54qgddkhicclxmlcsy3amfc3eq
```

The error:

```
 '../configure' '--prefix=/usr/workspace/wsa/bluenet/thiago/spack/opt/spack/linux-rhel6-x86_64/gcc-4.4.7/rose-0.9.8-usp52z54qgddkhicclxmlcsy3amfc3eq' '--with-boost=/usr/workspace/wsa/bluenet/thiago/spack/opt/spack/linux-rhel6-x86_64/gcc-4.4.7/boost-1.54.0-uovujemr4tpigoswrqzulc7bvljxhep5' '--with-gfortran=/usr/workspace/wsa/bluenet/thiago/spack/lib/spack/env/gcc/gfortran' '--disable-boost-version-check' 'JAVA_HOME=/usr/workspace/wsa/bluenet/thiago/spack/opt/spack/linux-rhel6-x86_64/gcc-4.4.7/jdk-8u92-linux-x64-l7lv77lz3epcdif2gdffaog6fedltsw6' 'JAVA_JVM_LINK=-Wl,-rpath,/usr/workspace/wsa/bluenet/thiago/spack/opt/spack/linux-rhel6-x86_64/gcc-4.4.7/jdk-8u92-linux-x64-l7lv77lz3epcdif2gdffaog6fedltsw6/jre/lib/amd64/server -ljvm'
checking for ROSE Git version information in '..'... configure:
configure: You are using a non-Git version of ROSE that lacks a VERSION file. This may be
configure: due to you having downloaded a ZIP archive of the ROSE repository from github.
configure: ROSE no longer supports being installed from a github ZIP archive; your ROSE
configure: source tree must contain Git version information, i.e., a ".git" directory.
configure:
configure: error: in `/tmp/thiago/spack-stage/spack-stage-zxKrXj/rose/rose-build':
configure: error: ../VERSION file does not exist
See `config.log' for more details
```

It looks like this happens only when try to install it again the same version. Does spack create a tar.gz from cloned git repositories?
By the way, I'm trying to clean cache to see if it starts from scratch, but nothing is changing after
`spack clean rose`. 

Thanks,

**Comment by scheibelp** [comment]
> nothing is changing after ```spack clean rose```

At the moment ```spack clean``` only removes the stage directory. It seems like it would make sense to add a ```--clear-cache``` option that also removes the cache file

I'll aim to have a PR out for that early next week.

```spack purge``` (with the ```--all``` or ```--downloads``` option) clears the cache but it actually clears out the entire cache.

In the meantime, you can manually delete the cache archive directory: either

/usr/workspace/wsa/bluenet/thiago/spack/var/spack/cache/rose/rose-0.9.8.tar.gz

or the rose directory:

/usr/workspace/wsa/bluenet/thiago/spack/var/spack/cache/rose/

**Comment by thiagotei** [comment]
That helps!
But how spack generates the tar.gz from a git clone? Does it remove .git?

**Comment by scheibelp** [comment]
> But how spack generates the tar.gz from a git clone? Does it remove .git?

Apparently it does, in fetch_strategy.GitFetchStrategy:

```
def archive(self, destination):
    super(GitFetchStrategy, self).archive(destination, exclude='.git')
```

I imagine if it didn't do this, the cached archive could be used as is. @tgamblin do you recall why fetcher archive functions remove the SCM data (e.g. .git)?

Either way IMO there should be an easy way to clear the cache for a specific package
