### ISSUE TITLE
module generation very slow following ruamel update

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#37692]
### Steps to reproduce

To generate modules for 905 packages takes me just under 4 minutes consistently, until 600955edd4ca22b2d94e725706fc4733d5c4e4d9 was merged, and now it takes ~1 hour! FYI @alalazo 

### Information on your system

* **Spack:** 0.20.0.dev0 (d265dd248707aff73fae29b67dcc7ad2870a9338)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by eugeneswalker** [comment]
I can confirm, it takes ~4 minutes to generate modules for all 900 of my packages if I use the commit right before 600955edd4ca22b2d94e725706fc4733d5c4e4d9, but takes ~60 minutes at 600955edd4ca22b2d94e725706fc4733d5c4e4d9 :(

**Comment by tgamblin** [comment]
@alalazo can you get a profile before and after?

**Comment by alalazo** [comment]
I think it's a deepcopy operation on the config file:

https://github.com/spack/spack/blob/9ee2d79de172de14477a78e5d407548a63eea33a/lib/spack/spack/modules/common.py#L174-L175

that became much more honerous with the new version of `ruamel.yaml`. I'll double check and try to confirm, but that seems in line with being worse for "complex" environments - i.e. environments with a large configuration dictionary that is deep copied a lot of times.
