### ISSUE TITLE
Module files environment missing

### ISSUE THREAD

**Issue by jxdn** [LLNL/spack#37740]
Hi Expert,

after i successfully install R, i didnt see any module files environment 
last time i check on /home/spack/share/modules/linuxxxx/r-4.x.x

may i know where its going

**Comment by jxdn** [comment]
fix it, refresh the package 
./spack module tcl refresh

**Comment by haampie** [comment]
Automatic module file generation used to be the default, but now you have to enable it:

```spack config add 'modules:default:enable:[tcl]'```
