### ISSUE TITLE
Guidance on adding 'completions' to git package.

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#3778]
I'd like to "gift" the git package with the ability to install the completion bits that live in the `contrib` subdirectory, basically doing [what the homebrew git recipe does](https://github.com/Homebrew/homebrew-core/blob/master/Formula/git.rb#L125-L132).

I'm scratching my head about where to install the bits.

I see that @alalazo has a [TODO about adding completion support in the node.js package](https://github.com/LLNL/spack/blob/8c650303ffdd02c4be273efbce1674706c0182cd/var/spack/repos/builtin/packages/node-js/package.py#L77) as well as a commented-out dependency and variant.  I don't see any other evidence of packages adding completion bits.

I'm on a CentOS 7 system that has all of the RHEL/CentOS bits installed in `/usr/share/bash-completion`.

I see that Spack has a [`bash-completion` package](https://github.com/LLNL/spack/blob/81a5146b1df1f69172c0f76bc3dbe469f4e366f9/var/spack/repos/builtin/packages/bash-completion/package.py) that overlaps with the CentOS stuff (perhaps being newer).  It also pulls in a bash.

I'd like to put the completion files someplace that would be useful to *either/or/both* of consumers of the system's bash-completion bits or the Spack bits.

The best idea I have it to tuck them into $(spack location -i git).

Anyone have a better way to do it?

**Comment by adamjstewart** [comment]
You can add the git completion scripts to the git package as resources, but I wouldn't try to install them outside of the git installation prefix.

**Comment by hartzell** [comment]
@adamjstewart -- I don't think that they need to be [a real resource](https://github.com/LLNL/spack/blob/7043fff8078d0b7a62895302dabbe71904220edf/lib/spack/spack/resource.py), they're already [part of the git source tree](https://github.com/git/git/tree/master/contrib/completion).  It's just a matter of adding a variant that copies them somewhere appropriate.

Actually, since it's going to take explicit user action to activate them (vs. if I copy them into a system directory), if I just tuck them into $(spack location -i git) then perhaps we can just *always* do it.
