### ISSUE TITLE
openmpi with custom configure args

### ISSUE THREAD

**Issue by abhamidipati-msft** [LLNL/spack#37784]
how can I install openmpi using spack with certain configure args as follows
`./configure --prefix=${INSTALL_PREFIX}/openmpi-${OMPI_VERSION} --with-ucx=${UCX_PATH} --with-hcoll=${HCOLL_PATH}`

how can I specify custom ${UCX_PATH} and ${HCOLL_PATH} during openmpi installation using spack?

**Comment by tbhaxor** [comment]
```
spack install -v -j `nproc` openmpi@${OMPI_VERSION} fabrics=ucx ^ucx@${UCX_VERSION}
```
I used this command. Both hcoll and ucx are fabrics used here I think you can use only one of them

**Comment by tbhaxor** [comment]
You can use more than one value in fabrics `fabrics=ucx,hcoll` like this but you need to define hcoll dependency using `^hcoll@${PUT_VERSION_HERE}` .

**Comment by abhamidipati-msft** [comment]
@tbhaxor thank you for the pointers. The UCX installation goes through. However, when I try to add hcoll@3.9.1927, it fails with the following

```
==> Installing hcoll-3.9.1927-lqcfjytm6pkgscjrbzuld4tzuvbit4q7
==> No binary for hcoll-3.9.1927-lqcfjytm6pkgscjrbzuld4tzuvbit4q7 found: installing from source
==> No patches needed for hcoll
==> hcoll: Executing phase: 'install'
==> Error: InstallError: hcoll is not installable, you need to specify it as an external package in packages.yaml

/opt/azurehpc/spack/var/spack/repos/builtin/packages/hcoll/package.py:30, in install:
         29    def install(self, spec, prefix):
  >>     30        raise InstallError(
         31            self.spec.format(
         32                "{name} is not installable, you need to specify "
         33
```


Here is the command I used
`spack install --add openmpi@4.1.5 fabrics=ucx,hcoll ^ucx@1.14.0 ^hcoll@3.9.1927`

On a side note, is there a way to specify just the hcoll and ucx paths to spack's openmpi installation? I already have both of them coming from HPC-x installation (from the error message above, we could specify the path in the packages.yaml but do you know how?)
Please advise.

**Comment by tbhaxor** [comment]
I haven't used hcoll fabrics, won't be able to help you here. Please consider asking help in the slack channel. The team is more active there. All my queries get resolved before 24h.

**Comment by abhamidipati-msft** [comment]
this worked for me

vi .../etc/spack/defaults/packages.yaml
```
packages:
  hcoll:
    externals:
    - spec: hcoll@3.9.1927
      prefix: /path/to/hcoll
    buildable: false
  ucx:
    externals:
    - spec: ucx@1.14.0
      prefix: /path/to/ucx
    buildable: false
```

`spack install --add openmpi@4.1.5 fabrics=ucx,hcoll ^ucx@1.14.0 ^hcoll@3.9.1927`
