### ISSUE TITLE
undefined symbol: omp_get_num_procs when running matplotlib

### ISSUE THREAD

**Issue by jmcarcell** [LLNL/spack#37902]
When running this code
``` python
import matplotlib.pyplot as plt
fig, ax = plt.subplots(1, 1, figsize=(3.72, 2.3))
ax.hist([1, 2, 3])
```
python crashes with:
```
python3: symbol lookup error: /cvmfs/sw-nightlies.hsf.org/key4hep/releases/2023-05-20/x86_64-almalinux9-gcc11.3.1-opt/intel-oneapi-mkl/2023.1.0-dhmczu/mkl/2023.1.0/lib/intel64/libmkl_intel_thread.so.2: undefined symbol: omp_get_num_procs
```

I'm also building `llvm` and the symbol `omp_get_num_procs` can be found there (output of `nm -gC`):
```
libgomp.so
00000000000b2b50 T omp_get_num_procs@OMP_1.0
00000000000b50d0 T omp_get_num_procs_@OMP_1.0
00000000000b2b50 T omp_get_num_procs@@VERSION
00000000000b50d0 T omp_get_num_procs_@@VERSION
libiomp5.so
00000000000b2b50 T omp_get_num_procs@OMP_1.0
00000000000b50d0 T omp_get_num_procs_@OMP_1.0
00000000000b2b50 T omp_get_num_procs@@VERSION
00000000000b50d0 T omp_get_num_procs_@@VERSION
libomp.so
00000000000b2b50 T omp_get_num_procs@OMP_1.0
00000000000b50d0 T omp_get_num_procs_@OMP_1.0
00000000000b2b50 T omp_get_num_procs@@VERSION
00000000000b50d0 T omp_get_num_procs_@@VERSION
```
but naively doing `export LD_LIBRARY_PATH:/path/to/llvm/lib:$LD_LIBRARY_PATH` doesn't seem to work. Any ideas?
More information:
- `np.histogram` works fine, everything I have tried so far in numpy has worked.
-  I have a similar (working) stack built from a few days ago without `llvm` and in that case `intel-mkl` was built instead of `intel-oneapi-mkl`. I was able to find the `omp_get_num_procs` inside `libiomp*.so` in `intel-mkl` and the python code above works fine.
- Checking the numpy build log in both cases (since the dependency on `mkl` comes from numpy) in both cases it correctly identifies and uses `mkl`, both `NPY_BLAS_ORDER` and `NPY_LAPACK_ORDER` are being set to `mkl`. 
- I don't have a minimal environment to reproduce this since it's part of a deployment with lots of packages, but these are the relevant specs (the only change we have is `backend=qt5agg` for matplotlib but all the others should be the default variants)
```
 -   64a6xwv          ^py-numpy@1.24.3%gcc@11.3.1+blas+lapack build_system=python_pip patches=873745d arch=linux-almalinux9-x86_64
 -   dhmczuo          ^intel-oneapi-mkl@2023.1.0%gcc@11.3.1~cluster+envmods~ilp64+shared build_system=generic threads=none arch=linux-almalinux9-x86_64
 -   yxnmgab          ^intel-tbb@2020.3%gcc@11.3.1+shared+tm build_system=makefile cxxstd=17 patches=62ba015,ce1fb16,d62cb66 arch=linux-almalinux9-x86_64
 -   chmhk6f          ^py-matplotlib@3.7.1%gcc@11.3.1~animation~fonts~latex~movies backend=qt5agg build_system=python_pip arch=linux-almalinux9-x86_64
```
- The stack can be sourced by doing `source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh` on Centos 7, Alma 9 or Ubuntu 22.04 if someone wants to reproduce

Tagging the matplotlib maintainer: @adamjstewart

**Comment by adamjstewart** [comment]
I wouldn't try mixing in compilers like LLVM that the package wasn't actually build with. It seems like you're building with the Intel compilers? I don't have a ton of experience with those. Just to narrow down the possibilities, can you try building with GCC to see if that works?

**Comment by jmcarcell** [comment]
This is built with gcc (the system one), we don't have the intel compilers. LLVM is a dependency of the top spec that we have so nothing depends on it but we have it around, I mentioned it because I found the symbols there which may not be relevant
Regarding the symbols, There is also a `/usr/lib64/libgomp.so` library in Alma 9 but `nm` doesn't report any symbols on it. For Centos 7 we also ship a different `gcc` from the system one and then the symbol can be found here:
```
nm -C /cvmfs/sw.hsf.org/contrib/x86_64-centos7-gcc4.8.5-opt/gcc/12.2.0-icg3ob/lib64/libgomp.a | grep omp_get_num_procs
0000000000000280 T gomp_ialias_omp_get_num_procs
0000000000000280 T omp_get_num_procs
                 U gomp_ialias_omp_get_num_procs
00000000000001a0 T omp_get_num_procs_
```
So I'm not sure how to proceed with this; should I try not to build llvm? In that case we built the stack and it built `intel-mkl` so maybe I could try `numpy ^intel-oneapi-mkl` to see if it's that

**Comment by adamjstewart** [comment]
@rgommers I know this isn't numpy/scipy but wondering if you have any thoughts on this bug report.

**Comment by rgommers** [comment]
Mixing compilers and hence OpenMP runtime libraries is indeed a huge pain. It often shows up only depending on import order of python packages; if `libgomp` is already loaded then `libiomp` will not be loaded (the `mkl-service` package should take care of that interop). 

In this case, if `intel-mkl` works but `intel-oneapi-mkl` does not, and with the symbol in question being a standard OpenMP symbol, it looks like a bug in OneAPI-MKL. But that needs confirming it looks like?

Taking a step back, I'd say that to not mix compilers like this, for more robustness you should use Intel compilers if you're using Intel MKL, and if you prefer to use GCC then use a BLAS/LAPACK library that is also built with GCC (e.g., OpenBLAS).

**Comment by jmcarcell** [comment]
I don't remember all the details but I think this was solved by using OpenBLAS instead.
