### ISSUE TITLE
read-cray-manifest does not update package.yml

### ISSUE THREAD

**Issue by dev-zero** [LLNL/spack#37911]
### Steps to reproduce

```
spack external read-cray-manifest
```

### Error message

```
...
==> [2023-05-25-15:47:50.931582] Omitting variant default64 for entry cray-mpich/rbf5mis
==> [2023-05-25-15:47:50.931602] Omitting variant netmod for entry cray-mpich/rbf5mis
==> [2023-05-25-15:47:50.932356] /opt/cray/pe/cpe-descriptive-manifest/cpe-descriptive-manifest-aocc-22.06.json: 31 specs read from manifest
==> [2023-05-25-15:47:50.932723] /opt/cray/pe/cpe-descriptive-manifest/cpe-descriptive-manifest-aocc-22.06.json: 2 compilers read from manifest
user@uan1:~/spack> ls ~/.spack/
bootstrap  cache  linux
```

### Information on your system

* **Spack:** 0.21.0.dev0 (785c31b730586045f5d9ea13fc61ed72b8da7d8e)
* **Python:** 3.6.15
* **Platform:** linux-sles15-zen3
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by dev-zero** [comment]
It seems that this is intentional, but why?

**Comment by alalazo** [comment]
@scheibelp

**Comment by alalazo** [comment]
@dev-zero I think the manifest is reflected into the DB directly.

**Comment by dev-zero** [comment]
@alalazo yes, that's what I realized after some time as well. Will close this and take discussion to Slack.
