### ISSUE TITLE
Mercurial does not work with spack on Titan

### ISSUE THREAD

**Issue by berrill** [LLNL/spack#3793]
Spack does not seem to correctly handle python paths with mercurial on Titan when loaded as a module.  When checking out any mercurial repo through spack I get:

Trying to clone Mercurial repository:
  https://bitbucket.org/pflotran/pflotran-xsdk
==> '/sw/xk6/mercurial/2.6.3/python2.6.8/bin/hg' 'clone' 'https://bitbucket.org/pflotran/pflotran-xsdk'
'import site' failed; use -v for traceback
Traceback (most recent call last):
  File "/sw/xk6/mercurial/2.6.3/python2.6.8/bin/hg", line 10, in <module>
    import os
ImportError: No module named os
==> Fetching from [hg] https://bitbucket.org/pflotran/pflotran-xsdk failed.
==> Command exited with status 1:
    '/sw/xk6/mercurial/2.6.3/python2.6.8/bin/hg' 'clone' 'https://bitbucket.org/pflotran/pflotran-xsdk'
==> Error: FetchError: All fetchers failed for pflotran-0.1.0-vzt5vmfyttvjqre262z3glz7g3jboqik
/autofs/nccs-svm1_home1/mbt/spack/lib/spack/spack/package.py:948, in do_fetch:
     921      def do_fetch(self, mirror_only=False):
     922          """
     923          Creates a stage directory and downloads the tarball for this package.
     924          Working directory will be set to the stage directory.
     925          """
     926          if not self.spec.concrete:
     927              raise ValueError("Can only fetch concrete packages.")
     928  
     929          start_time = time.time()
     930          if spack.do_checksum and self.version not in self.versions:
     931              tty.warn("There is no checksum on file to fetch %s safely." %
     932                       self.spec.format('$_$@'))
     933  
     934              # Ask the user whether to skip the checksum if we're
     935              # interactive, but just fail if non-interactive.
     936              ck_msg = "Add a checksum or use --no-checksum to skip this check."
     937              ignore_checksum = False
     938              if sys.stdout.isatty():
     939                  ignore_checksum = tty.get_yes_or_no("  Fetch anyway?",
     940                                                      default=False)
     941                  if ignore_checksum:
     942                      tty.msg("Fetching with no checksum.", ck_msg)
     943  
     944              if not ignore_checksum:
     945                  raise FetchError("Will not fetch %s" %
     946                                   self.spec.format('$_$@'), ck_msg)
     947  
  >> 948          self.stage.fetch(mirror_only)
     949  
     950          self._fetch_time = time.time() - start_time
     951  
     952          if spack.do_checksum and self.version in self.versions:
     953              self.stage.check()
     954  
     955          self.stage.cache_local()

Traceback (most recent call last):
  File "/autofs/nccs-svm1_home1/mbt/spack/lib/spack/spack/build_environment.py", line 550, in child_execution
    function(input_stream)
  File "/autofs/nccs-svm1_home1/mbt/spack/lib/spack/spack/package.py", line 1220, in build_process
    self.do_patch()
  File "/autofs/nccs-svm1_home1/mbt/spack/lib/spack/spack/package.py", line 974, in do_patch
    self.do_stage()
  File "/autofs/nccs-svm1_home1/mbt/spack/lib/spack/spack/package.py", line 963, in do_stage
    self.do_fetch(mirror_only)
  File "/autofs/nccs-svm1_home1/mbt/spack/lib/spack/spack/package.py", line 948, in do_fetch
    self.stage.fetch(mirror_only)
  File "/autofs/nccs-svm1_home1/mbt/spack/lib/spack/spack/util/pattern.py", line 84, in getter
    getattr(item, self.name)(*args, **kwargs)
  File "/autofs/nccs-svm1_home1/mbt/spack/lib/spack/spack/stage.py", line 445, in fetch
    raise fs.FetchError(errMessage, None)
FetchError: All fetchers failed for pflotran-0.1.0-vzt5vmfyttvjqre262z3glz7g3jboqik

Note that checking out the repository manually works just fine.  

module show mercurial:

/sw/xk6/modulefiles/mercurial/2.6.3:

module-whatis	 mercurial 2.6.3 
prepend-path	 PATH /sw/xk6/mercurial/2.6.3/python2.6.8/bin 
prepend-path	 LD_LIBRARY_PATH /sw/xk6/mercurial/2.6.3/python2.6.8/lib64 
prepend-path	 PYTHONPATH /sw/xk6/mercurial/2.6.3/python2.6.8/lib64/python2.6/site-packages

**Comment by adamjstewart** [comment]
@berrill I'm trying to overhaul Spack's mercurial support in #3834. Can you try my PR and see if the latest version of mercurial works any better for you?
