### ISSUE TITLE
hdf5@1.14.1-2: Fortran API broken when builing with Intel compiler in spack-stack

### ISSUE THREAD

**Issue by climbfuji** [LLNL/spack#37955]
### Steps to reproduce

We seem to have run into a strange bug with spack and `hdf5@1.14.1-2`. The Fortran API/compiled module files seem to be broken. This only occurs with Intel compilers (tested: `2021.3.0` and `2021.6.0`), not with `gcc` or `apple-clang`. And it only happens when building `hdf5` in spack-stack. When building it manually like this, it works:
```
./configure --prefix=${HDF5HOME} --enable-parallel --enable-fortran --enable-fortran2003 \
   --with-zlib FCFLAGS='-g -O3 -fPIC' CFLAGS='-g -O3 -fPIC'
```
The error with the broken Intel-spack builds is:
```
error #7002: Error in opening the compiled module file.  Check INCLUDE paths.   [H5ES]
use hdf5
----^
```
This can be reproduced with a simple Fortran module:
```
module test

use hdf5

implicit none

integer, parameter:: one = 1

end module test
```
Our build specs for `hdf5` are as follows (this is one example, it happens on all platforms we have access to so far):
```
hdf5@1.14.1-2%intel@2021.5.0~cxx+fortran+hl~ipo~java+mpi+shared+szip~threadsafe+tools api=default build_system=cmake build_type=RelWithDebInfo generator=make arch=linux-centos7-skylake_avx512
    ^cmake@3.23.1%intel@2021.5.0~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-centos7-skylake_avx512
        ^ncurses@6.4%intel@2021.5.0~symlinks+termlib abi=none build_system=autotools arch=linux-centos7-skylake_avx512
        ^openssl@1.0.2k-fips%intel@2021.5.0~docs+shared build_system=generic certs=mozilla arch=linux-centos7-skylake_avx512
    ^gmake@3.82%intel@2021.5.0~guile build_system=autotools patches=ca60bd9 arch=linux-centos7-skylake_avx512
    ^intel-oneapi-mpi@2021.5.0%intel@2021.5.0+envmods~external-libfabric~generic-names~ilp64 build_system=generic arch=linux-centos7-skylake_avx512
    ^libaec@1.0.6%intel@2021.5.0~ipo+shared build_system=cmake build_type=RelWithDebInfo generator=make arch=linux-centos7-skylake_avx512
    ^pkg-config@0.27.1%intel@2021.5.0+internal_glib build_system=autotools patches=49ffcd6 arch=linux-centos7-skylake_avx512
    ^zlib@1.2.13%intel@2021.5.0+optimize+pic+shared build_system=makefile arch=linux-centos7-skylake_avx512
```
This means that we will have to reinstall on all systems that use Intel … my fault I should have tested it early with the UFS at least … but who expects such a thing. It’s fine with 1.14.0 on Nautilus, for example, just not with 1.14.1-2. And if the Navy folks build 1.14.1-2 standalone with their flags on Nautilus, it works, too!

### Error message

See above

### Information on your system

* **Spack:** 0.20.0.dev0
* **Python:** 3.9.12
* **Platform:** linux-centos7-skylake_avx512
* **Concretizer:** clingo

(this is just an example, it happens on all systems we have access to)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by climbfuji** [comment]
@lrknox @hyoklee FYI

**Comment by hyoklee** [comment]
@brtnfld - any clue?

**Comment by brtnfld** [comment]
It might have to do with this:

https://github.com/HDFGroup/hdf5/pull/2969/files

**Comment by alalazo** [comment]
> [...] I should have tested it early with the UFS at least [...]

@climbfuji FYI, you can encode a stand-alone test using the snippet you posted to ensure basic sanity of the Fortran modules. Ping me or @tldahlgren if you submit a PR in that sense.

**Comment by climbfuji** [comment]
Revisiting open issues and PRs. Given that we now have hdf5@1.14.2 and 1.14.3 and that at least I haven't seen the above mentioned problems with those versions, should we close this?

And/or add a `conflict` for Intel compilers for version 1.14.1-2? Fine if you don't want it, because I think @hyoklee wasn't able to reproduce the error. Thanks!

**Comment by climbfuji** [comment]
Closing this as won't fix - we have moved past this version and newer versions don't have this problem
