### ISSUE TITLE
Testing issue: pumi

### ISSUE THREAD

**Issue by wspear** [LLNL/spack#38030]
### Steps to reproduce the failure(s) or link(s) to test output(s)

```console
$ spack spec -I pumi

 -   pumi@2.2.7%gcc@11.1.0~fortran~int64~ipo~shared+simmodsuite_version_check~testing~zoltan build_system=cmake build_type=Release generator=make simmodsuite=none arch=linux-ubuntu20.04-x86_64
[+]      ^cmake@3.26.3%gcc@11.1.0~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-ubuntu20.04-x86_64
[+]          ^ncurses@6.3%gcc@11.1.0~symlinks+termlib abi=none build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^pkgconf@1.9.5%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^openssl@1.1.1t%gcc@11.1.0~docs~shared build_system=generic certs=mozilla arch=linux-ubuntu20.04-x86_64
[+]              ^ca-certificates-mozilla@2023-01-10%gcc@11.1.0 build_system=generic arch=linux-ubuntu20.04-x86_64
[+]              ^perl@5.36.0%gcc@11.1.0+cpanm+open+shared+threads build_system=generic arch=linux-ubuntu20.04-x86_64
[+]                  ^berkeley-db@18.1.40%gcc@11.1.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu20.04-x86_64
[+]                  ^bzip2@1.0.8%gcc@11.1.0~debug~pic+shared build_system=generic arch=linux-ubuntu20.04-x86_64
[+]                      ^diffutils@3.9%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                          ^libiconv@1.17%gcc@11.1.0 build_system=autotools libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]                  ^gdbm@1.23%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                      ^readline@8.2%gcc@11.1.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu20.04-x86_64
[+]              ^zlib@1.2.13%gcc@11.1.0+optimize+pic+shared build_system=makefile arch=linux-ubuntu20.04-x86_64
[+]      ^gmake@4.4.1%gcc@11.1.0~guile build_system=autotools arch=linux-ubuntu20.04-x86_64
 -       ^nvhpc@23.3%gcc@11.1.0+blas+lapack+mpi build_system=generic install_type=single arch=linux-ubuntu20.04-x86_64

```

### Error message

<details><summary>Error message</summary>

<pre>
root@gilgamesh:~/testsuite/validation_tests/pumi# ./run.sh 
pumi : 57q5bid
==> Error: TestFailure: 2 tests failed.

Command exited with status -6:
    './uniform' '../testdata/pipe.dmg' '../testdata/pipe.smb' 'pipe_unif.smb'
gmi failed: could not open model file

1 error found in test log:
     3    ==> [2023-05-31-12:40:49.899448] test: test: unspecified purpose
     4    ==> [2023-05-31-12:40:49.899601] Warning: The 'run_test' method is deprecated. Use 'test_part' instead for pumi to process uniform.
     5    ==> [2023-05-31-12:40:49.899813] test: test_uniform_pipe.dmg_pipe.smb_pipe_unif.smb: testing pumi uniform mesh refinement
     6    ==> [2023-05-31-12:40:49.900015] Expecting return code in [0]
     7    ==> [2023-05-31-12:40:49.900206] './uniform' '../testdata/pipe.dmg' '../testdata/pipe.smb' 'pipe_unif.smb'
     8    gmi failed: could not open model file
  >> 9    FAILED: Pumi::test_uniform_pipe.dmg_pipe.smb_pipe_unif.smb: Command exited with status -6:
     10       './uniform' '../testdata/pipe.dmg' '../testdata/pipe.smb' 'pipe_unif.smb'
     11   gmi failed: could not open model file
     12   
     13     File "/spack/bin/spack", line 54, in <module>
     14       sys.exit(main())
     15     File "/spack/lib/spack/spack_installable/main.py", line 37, in main

Command exited with status 134:
    '/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/mpich-4.1.1-4cbi7qhusseuuh6bcs6lokwgwh6s3itl/bin/mpiexec' '-n' '2' 'split' '../testdata/pipe.dmg' '../testdata/pipe.smb' 'pipe_2_.smb' '2'

===================================================================================
=   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
=   PID 79112 RUNNING AT gilgamesh
=   EXIT CODE: 134
=   CLEANING UP REMAINING PROCESSES
=   YOU CAN IGNORE THE BELOW CLEANUP MESSAGES
===================================================================================
YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Aborted (signal 6)
This typically refers to a problem with your application.
Please see the FAQ page for debugging suggestions
gmi failed: could not open model file
gmi failed: could not open model file

1 error found in test log:
     70    ===================================================================================
     71    YOUR APPLICATION TERMINATED WITH THE EXIT STRING: Aborted (signal 6)
     72    This typically refers to a problem with your application.
     73    Please see the FAQ page for debugging suggestions
     74    gmi failed: could not open model file
     75    gmi failed: could not open model file
  >> 76    FAILED: Pumi::test_mpiexec_n_2_split_pipe.dmg_pipe.smb_pipe_2_.smb_2: Command exited with status 134:

See test log for details:
  /root/.spack/test/f7kouf7dytx2bh4ocbxbzof63fut7yzj/pumi-2.2.7-57q5bid-test-out.txt

==> Error: 1 test(s) in the suite failed.

--- ==> Spack test f7kouf7dytx2bh4ocbxbzof63fut7yzj
==> Testing package pumi-2.2.7-57q5bid
============================== 1 failed of 1 spec ==============================

See pumi-2.2.7-57q5bid test results at:
  /root/.spack/test/f7kouf7dytx2bh4ocbxbzof63fut7yzj/pumi-2.2.7-57q5bid-test-out.txt ---

</pre></details>

### Information on your system or the test runner

* **Spack:** 0.20.0.dev0 (0dc6c421561a59e2b00b1daf634c1216f843daa0)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-zen3
* **Concretizer:** clingo

### Additional information

@cwsmi

### General information

- [X] I have reported the version of Spack/Python/Platform/Runner
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded any available logs
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by wspear** [comment]
@cwsmith @tldahlgren I'm still seeing this issue. It may be related to the unwritable status of the spack root/install directory, or to paths being invalid because of string relocation since this was installed from a binary cache.

**Comment by tldahlgren** [comment]
I haven't revisited this since https://github.com/spack/spack/pull/35807 where I made some changes to that package.

**Comment by tldahlgren** [comment]
Does #45181 fix this issue?

**Comment by wspear** [comment]
I believe that did it. I was able to run the test after doing a `chmod -R -w `on the pumi install directory. There's a chance that doesn't replicate the conditions of the failure but I'll revisit this if I see the issue in our next E4S spin.

**Comment by wspear** [comment]
Checked the commit from before the PR was merged and the error was happening there. Quite confident this is fixed now.

**Comment by tldahlgren** [comment]
@AcriusWinter FYI.
