### ISSUE TITLE
Installation issue: OpenMPI aborts configure when building with +pmi and external slurm

### ISSUE THREAD

**Issue by uihsnv** [LLNL/spack#38165]
### Steps to reproduce the issue

```console
$ spack spec -I openmpi %aocc +pmi schedulers=slurm
Input spec
--------------------------------
 -   openmpi%aocc+pmi schedulers=slurm

Concretized
--------------------------------
 -   openmpi@4.1.5%aocc@4.0.0~atomics~cuda~cxx~cxx_exceptions~gpfs~internal-hwloc~java~legacylaunchers~lustre~memchecker~orterunprefix+pmi+romio+rsh~singularity+static+vt+wrapper-rpath build_system=autotools fabrics=none schedulers=slurm arch=linux-ubuntu20.04-zen2
[+]      ^hwloc@2.9.1%aocc@4.0.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-ubuntu20.04-zen2
[+]          ^libpciaccess@0.17%aocc@4.0.0 build_system=autotools arch=linux-ubuntu20.04-zen2
[+]              ^util-macros@1.19.3%aocc@4.0.0 build_system=autotools arch=linux-ubuntu20.04-zen2
[+]          ^libxml2@2.10.3%aocc@4.0.0~python build_system=autotools arch=linux-ubuntu20.04-zen2
[+]              ^libiconv@1.17%aocc@4.0.0 build_system=autotools libs=shared,static arch=linux-ubuntu20.04-zen2
[+]              ^xz@5.4.1%aocc@4.0.0~pic build_system=autotools libs=shared,static arch=linux-ubuntu20.04-zen2
[+]          ^ncurses@6.4%aocc@4.0.0~symlinks+termlib abi=none build_system=autotools arch=linux-ubuntu20.04-zen2
[+]      ^numactl@2.0.14%aocc@4.0.0 build_system=autotools patches=4e1d78c,62fc8a8,ff37630 arch=linux-ubuntu20.04-zen2
[+]          ^autoconf@2.69%aocc@4.0.0 build_system=autotools patches=35c4492,7793209,a49dd5b arch=linux-ubuntu20.04-zen2
[+]          ^automake@1.16.5%aocc@4.0.0 build_system=autotools arch=linux-ubuntu20.04-zen2
[+]          ^libtool@2.4.7%aocc@4.0.0 build_system=autotools arch=linux-ubuntu20.04-zen2
[+]          ^m4@1.4.19%aocc@4.0.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-ubuntu20.04-zen2
[+]              ^diffutils@3.9%aocc@4.0.0 build_system=autotools arch=linux-ubuntu20.04-zen2
[+]              ^libsigsegv@2.14%aocc@4.0.0 build_system=autotools arch=linux-ubuntu20.04-zen2
[+]      ^openssh@9.3p1%aocc@4.0.0+gssapi build_system=autotools arch=linux-ubuntu20.04-zen2
[+]          ^krb5@1.20.1%aocc@4.0.0+shared build_system=autotools arch=linux-ubuntu20.04-zen2
[+]              ^bison@3.8.2%aocc@4.0.0 build_system=autotools arch=linux-ubuntu20.04-zen2
[+]              ^gettext@0.21.1%aocc@4.0.0+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=linux-ubuntu20.04-zen2
[+]                  ^tar@1.34%aocc@4.0.0 build_system=autotools zip=pigz arch=linux-ubuntu20.04-zen2
[+]                      ^pigz@2.7%aocc@4.0.0 build_system=makefile arch=linux-ubuntu20.04-zen2
[+]                      ^zstd@1.5.5%aocc@4.0.0+programs build_system=makefile compression=none libs=shared,static arch=linux-ubuntu20.04-zen2
[+]          ^libedit@3.1-20210216%aocc@4.0.0 build_system=autotools arch=linux-ubuntu20.04-zen2
[+]          ^libxcrypt@4.4.33%aocc@4.0.0~obsolete_api build_system=autotools arch=linux-ubuntu20.04-zen2
[+]          ^openssl@1.1.1t%aocc@4.0.0~docs~shared build_system=generic certs=mozilla arch=linux-ubuntu20.04-zen2
[+]              ^ca-certificates-mozilla@2023-01-10%aocc@4.0.0 build_system=generic arch=linux-ubuntu20.04-zen2
[+]      ^perl@5.36.0%aocc@4.0.0+cpanm+open+shared+threads build_system=generic arch=linux-ubuntu20.04-zen2
[+]          ^berkeley-db@18.1.40%aocc@4.0.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu20.04-zen2
[+]          ^bzip2@1.0.8%aocc@4.0.0~debug~pic+shared build_system=generic arch=linux-ubuntu20.04-zen2
[+]          ^gdbm@1.23%aocc@4.0.0 build_system=autotools arch=linux-ubuntu20.04-zen2
[+]              ^readline@8.2%aocc@4.0.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu20.04-zen2
[+]      ^pkgconf@1.9.5%aocc@4.0.0 build_system=autotools arch=linux-ubuntu20.04-zen2
[+]      ^pmix@4.2.3%aocc@4.0.0~docs+pmi_backwards_compatibility~python~restful build_system=autotools arch=linux-ubuntu20.04-zen2
[+]          ^libevent@2.1.12%aocc@4.0.0+openssl build_system=autotools arch=linux-ubuntu20.04-zen2
[+]      ^slurm@19.05.5%aocc@4.0.0~gtk~hdf5~hwloc~mariadb~pmix+readline~restd build_system=autotools sysconfdir=PREFIX/etc arch=linux-ubuntu20.04-zen2
[+]      ^zlib@1.2.13%aocc@4.0.0+optimize+pic+shared build_system=makefile arch=linux-ubuntu20.04-zen2
```
Attempting to install with that spec produces this issue at the `configure` stage of the openmpi package.

### Error message

<details><summary>Error message</summary>

<pre>
.
.
.
checking if user requested PMI support... yes
checking for pmi.h in /usr... not found
checking for pmi.h in /usr/include... not found
checking for pmi.h in /usr/include/slurm... not found
checking for libpmi in /usr/lib... checking for libpmi in /usr/lib64... not found
checking for pmi2.h in /usr... not found
checking for pmi2.h in /usr/include... not found
checking for pmi2.h in /usr/include/slurm... not found
checking for libpmi2 in /usr/lib... checking for libpmi2 in /usr/lib64... not found
checking can PMI support be built... no
configure: WARNING: PMI support requested (via --with-pmi) but neither pmi.h,
configure: WARNING: pmi2.h or pmix.h were found under locations:
configure: WARNING:     /usr
configure: WARNING:     /usr/slurm
configure: WARNING: Specified path: /usr
configure: WARNING: OR neither libpmi, libpmi2, or libpmix were found under:
configure: WARNING:     /lib
configure: WARNING:     /lib64
configure: WARNING: Specified path: 
configure: error: Aborting
</pre></details>

### Information on your system

```console
$ spack debug report
* **Spack:** 0.21.0.dev0 (6fd8001604c36b2ca534cbfb050c987e6c8cd96c)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-zen2
* **Concretizer:** clingo
```

### Additional information

```console
$ cat ~/.spack/packages.yaml 
packages:
  slurm:
    externals:
    - spec: slurm@19.05.5
      prefix: /usr
    buildable: false
```
Build log: [spack_openmpi-build-out.txt](https://github.com/spack/spack/files/11649274/spack_openmpi-build-out.txt)

@hppritcha @naughtont3 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by james-simone** [comment]
Make sure your system has the package `slurm-libpmi` installed along with the other external slurm pacages.

**Comment by uihsnv** [comment]
I don't see any such package in the repositories of Ubuntu 20.04 . There are packages named `libpmi0` and `libpmi2-0`, which describe themselves as "SLURM PMI (or PMI2) library implementation".

Are they the right ones? There doesn't seem to be a PMIx library, though.

**Comment by uihsnv** [comment]
What I do have installed already, are the `libpmix-dev` and the `libpmix2` packages, which are described to be the : "Process Management Interface (Exascale) library". I also attempted installation of openmpi after adding it to my list of external packages:

```console
$ cat .spack/packages.yaml
packages:
  slurm:
    externals:
    - spec: slurm@19.05.5
      prefix: /usr
    buildable: false
  pmix:
    externals:
    - spec: pmix@3.1.5
      prefix: /usr/lib/x86_64-linux-gnu/pmix
    buildable: false
```

That did not help either.

**Comment by uihsnv** [comment]
I installed the `libpmi2-0` and the `libpmi2-0-dev` packages, and that solves half the problem, with the header file now having been found:

```
checking for pmi2.h in /usr/include/slurm... found
checking pmi2.h usability... yes
checking pmi2.h presence... yes
checking for pmi2.h... yes
```

However, spack is still unable to find the library file, and aborts as earlier

```
checking for libpmi2 in /usr/lib... checking for libpmi2 in /usr/lib64... not found
checking can PMI support be built... no
configure: WARNING: PMI support requested (via --with-pmi) but neither pmi.h
configure: WARNING: nor pmi2.h were found under locations:
configure: WARNING:     /usr
configure: WARNING:     /usr/slurm
configure: WARNING: Specified path: /usr
configure: WARNING: OR neither libpmi nor libpmi2 were found under:
configure: WARNING:     /lib
configure: WARNING:     /lib64
configure: WARNING: Specified path: 
configure: error: Aborting
```

The library files seem to be located here:
```
/usr/lib/x86_64-linux-gnu/libpmi2.so.0
/usr/lib/x86_64-linux-gnu/libpmi2.la
/usr/lib/x86_64-linux-gnu/slurm-wlm/mpi_pmi2.so
/usr/lib/x86_64-linux-gnu/libpmi2.so.0.0.0
/usr/lib/x86_64-linux-gnu/libpmi2.a
/usr/lib/x86_64-linux-gnu/libpmi2.so
```
while, as per the build-log, the configuration is performed `--with-pmi=/usr`. How do I change that? And even if I did, I am guessing that the script would fail to find the header file.

What do I do?

**Comment by james-simone** [comment]
Check which MPI launchers your slurm installation supports
`srun --mpi=list`
You will have to pick one of those listed unless you rebuild slurm and configure it with pmi2 support. For openMPI your best option is to [use pmix](https://docs.open-mpi.org/en/v5.0.0rc8/running-apps/pmix-and-prrte.html).

**Comment by uihsnv** [comment]
The native SLURM installation seems to say that it supports PMIX:

```
$ srun --mpi=list
srun: MPI types are...
srun: none
srun: openmpi
srun: pmi2
srun: pmix_v3
srun: pmix
```

But how do I get spack's openmpi to recognize it?

**Comment by james-simone** [comment]
In the openmpi spec keep schedulers=slurm but drop +pmi2

**Comment by hppritcha** [comment]
if you were building open mpi directly and not thru spack, the solution would straightforward as there's config option to point to the pmix lib location.  if you want to use spack you could tweak your compilers.yaml file to add -L point_to_libpmix_location.  If pmix.h is also in non-standard location you'll need to add -I location of pmix.h to the compiler flag options as well.

**Comment by hppritcha** [comment]
i agree with @james-simone that you may be better off not trying to use pmi and just let ompi use pmix.
if you want to use srun you will need to use the --mpi=pmix_v3 arg.  There's also a SLURM_MPI_TYPE(?) env. you can use to specify this option.

**Comment by uihsnv** [comment]
Installing openmpi without the `+pmi` option does work.

However, I am unable to run any programs. When I use `--mpi=pmix_v3` or `--mpi=pmix` as arguments to srun, the job fails to execute with the output:

```
srun: error: (null) [0] /mpi_pmix.c:133 [init] mpi/pmix: ERROR: pmi/pmix: can not load PMIx library
srun: error: Couldn't load specified plugin name for mpi/pmix: Plugin init() callback failed
srun: error: cannot create mpi context for mpi/pmix
srun: error: invalid MPI type 'pmix', --mpi=list for acceptable types
```

And when I use the `--mpi=pmi2` argument, I see:

```
[s124:1357995] OPAL ERROR: Not initialized in file pmix2x_client.c at line 112
[s124:1357993] OPAL ERROR: Not initialized in file pmix2x_client.c at line 112
--------------------------------------------------------------------------
The application appears to have been direct launched using "srun",
but OMPI was not built with SLURM's PMI support and therefore cannot
execute. There are several options for building PMI support under
SLURM, depending upon the SLURM version you are using:

  version 16.05 or later: you can use SLURM's PMIx support. This
  requires that you configure and build SLURM --with-pmix.

  Versions earlier than 16.05: you must use either SLURM's PMI-1 or
  PMI-2 support. SLURM builds PMI-1 by default, or you can manually
  install PMI-2. You must then build Open MPI using --with-pmi pointing
  to the SLURM PMI library location.

Please configure as appropriate and try again.
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
[s124:1357995] Local abort before MPI_INIT completed completed successfully, but am not able to aggregate error messages, and not able to guarantee that all other processes were killed!
```

So it looks like I do need that option to be passed to spack when compiling openmpi, don't I?

**Comment by hppritcha** [comment]
Actually this looks like a slurm/pmix config problem - not a spack problem.
Looks like you're hitting a variant of this problem

https://bugs.launchpad.net/ubuntu/+source/slurm-llnl/+bug/1862854

**Comment by uihsnv** [comment]
I am, though, able to use `srun --mpi=pmix` with MPICH when I force it to use the system pmix library by adding it as an external package.

```
spack spec -I --fresh mpich pmi=pmix +slurm ^slurm@19.05.5%gcc ^pmix@3.1.5%gcc
```

Looks like I won't be able to use OpenMPI on this machine for now. Shall I close this issue?

**Comment by uihsnv** [comment]
> compilers



> if you want to use spack you could tweak your compilers.yaml file to add -L point_to_libpmix_location.

Where exactly can I add that? The documentation for the compiler configuration does not make that clear.

**Comment by hppritcha** [comment]
I suggest closing this issue.  
I was thinking of the ~/.spack/linux/compilers.yaml

**Comment by naromero77** [comment]
> I am, though, able to use `srun --mpi=pmix` with MPICH when I force it to use the system pmix library by adding it as an external package.
> 
> ```
> spack spec -I --fresh mpich pmi=pmix +slurm ^slurm@19.05.5%gcc ^pmix@3.1.5%gcc
> ```
> 
> Looks like I won't be able to use OpenMPI on this machine for now. Shall I close this issue?

@uihsnv I had a lot of trouble getting either OpenMPI or MPICH packages to work with an external SLURM, even though the SLURM reports that it supports pmi2 (sinfo --mpi=list). When I tried the MPICH build recipe, it complained about a missing `libevent` library because I think the dependencies for MPICH with the pmi=pmix needs an extra dependency on the libevent package (which is missing).

**Comment by physkets** [comment]
Did you add slurm to your external package list (`.spack/packages.yaml`) like i do above?
