### ISSUE TITLE
GSI-ncdiag: new version 1.1.0

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [LLNL/spack#38195]
### Summary

A new version of the GSI-ncdiag library was developed to support changes to the GSI, primarily a new subroutine that converts input doubles to singles and screens for `NaN` in the process.

### Rationale

This version of ncdiag helps to fix problems with the GSI wherein an attempt to convert double `NaN`s to singles cause `floating-invalid` errors and unpredictable behavior.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
@DavidHuber-NOAA The label `feature` is for proposal to add features to Spack :slightly_smiling_face: Feel free to submit version bumps without opening an issue in the future :slightly_smiling_face:

**Comment by DavidHuber-NOAA** [comment]
Noted, thanks @alalazo!
