### ISSUE TITLE
Deprecated features slated for removal in v0.21

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#38222]
A brief list of features that are already deprecated and will be removed in v0.21:

- [x] #37246
- [x] #38199
- [x] #40600 
~- [ ] Old format for the stand-alone tests in packages~

**Comment by alalazo** [comment]
@tldahlgren I see that the last item was barred. What are we going to do with:

https://github.com/spack/spack/blob/da0813b049b016b2bcd021abcf2e520ac8bb41ea/lib/spack/spack/package_base.py#L1152-L1162

and 

https://github.com/spack/spack/blob/da0813b049b016b2bcd021abcf2e520ac8bb41ea/lib/spack/spack/package_base.py#L1820-L1843

?

**Comment by tldahlgren** [comment]
Thanks for the reminder.
