### ISSUE TITLE
`spack spec` doesn't honor concretizer options in the environment scope 

### ISSUE THREAD

**Issue by tldahlgren** [LLNL/spack#38240]
### Steps to reproduce

On a clean clone of Spack:
```console
$ spack config --scope user add concretizer:unify:false
$ spack env activate --temp
$ spack add zlib@1.2.13
$ spack add zlib@1.2.12
$ spack config add concretizer:unify:true
$ spack concretize
==> Error: concretization failed for the following reasons:

   1. Cannot select a single "version" for package "zlib"
   2. Cannot satisfy 'zlib@1.2.13'
   3. Cannot satisfy 'zlib@1.2.12'. You could consider setting `concretizer:unify` to `when_possible` or `false` to allow multiple versions of some packages.

$ spack spec
==> Starting concretization pool with 2 processes
==> Warning: using "zlib@1.2.12" which is a deprecated version
==> Environment concretized in 1.04 seconds.
Input spec
--------------------------------
zlib@1.2.13

Concretized
--------------------------------
zlib@1.2.13%gcc@9.4.0+optimize+pic+shared build_system=makefile arch=linux-ubuntu20.04-icelake

Input spec
--------------------------------
zlib@1.2.12

Concretized
--------------------------------
zlib@1.2.12%gcc@9.4.0+optimize+pic+shared build_system=makefile patches=0d38234 arch=linux-ubuntu20.04-icelake
```

### Error message

No error message, but the output of `spack spec` is wrong (should be the same as the output of `spack concretize`)

Environment is not using the `concretizer:unify` option set in the `spack.yaml` file so that `spack spec` does not follow the correct concretization path when provided.

_Originally posted by @tldahlgren in https://github.com/spack/spack/issues/35298#issuecomment-1581518885_

### Information on your system

* **Spack:** 0.21.0.dev0 (d91ec8500f7f8265c023b217bce0c0ca34a81a24)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Can you post a reproducer for this? I cannot reproduce with an active environment, so I am not sure I fully understand in which situation this bug is triggered. 

What I tried:
```yaml
spack:
  # add package specs to the `specs` list
  specs:
  - zlib@=1.2.12
  - zlib@=1.2.13
  view: true
  concretizer:
    unify: false
```
This concretizes:
```console
==> Starting concretization pool with 2 processes
==> Warning: using "zlib@1.2.12" which is a deprecated version
==> Environment concretized in 0.35 seconds.
==> Concretized zlib@=1.2.12
 -   da4ghop  zlib@1.2.12%gcc@9.4.0+optimize+pic+shared build_system=makefile patches=0d38234 arch=linux-ubuntu20.04-icelake

==> Concretized zlib@=1.2.13
[+]  4kpu5pp  zlib@1.2.13%gcc@9.4.0+optimize+pic+shared build_system=makefile arch=linux-ubuntu20.04-icelake

==> Updating view at /tmp/spack-84fc7mec/.spack-env/view
```
Setting the value to `True` instead:
```console
$ spack concretize -f --fresh
==> Error: concretization failed for the following reasons:

   1. Cannot select a single "version" for package "zlib"
   2. Cannot satisfy 'zlib@=1.2.13'
   3. Cannot satisfy 'zlib@=1.2.12'. You could consider setting `concretizer:unify` to `when_possible` or `false` to allow multiple versions of some packages.
```

**Comment by tldahlgren** [comment]
> Can you post a reproducer for this? I cannot reproduce with an active environment, so I am not sure I fully understand in which situation this bug is triggered.

I could reproduce this with the reproducer in #35298 and the comment at https://github.com/spack/spack/issues/35298#issuecomment-1581468500.  In other words, IIRC, have the configuration set to `unify: false` and the `spack.yaml` to either nothing (so default, which is not `false`) or set to to `true` or `when_possible`.

**Comment by tldahlgren** [comment]
> > Can you post a reproducer for this? I cannot reproduce with an active environment, so I am not sure I fully understand in which situation this bug is triggered.
> 
> I could reproduce this with the reproducer in #35298 and the comment at [#35298 (comment)](https://github.com/spack/spack/issues/35298#issuecomment-1581468500). In other words, IIRC, have the configuration set to `unify: false` and the `spack.yaml` to either nothing (so default, which is not `false`) or set to to `true` or `when_possible`.

If you add `test_environment_concretizer_scheme_used` from #38248 and run without the changes in that PR then the tests should fail (at least they did for me).

**Comment by alalazo** [comment]
> I could reproduce this with the reproducer in https://github.com/spack/spack/issues/35298 and the [ ... ]

I'm not following, or I am missing something trivial. The reproducer in #35298 is:
```yaml
spack:
  specs:
    - nco ^netcdf-c ~~mpi
```
being a single spec, does it matter if it is unified or not?

**Comment by tldahlgren** [comment]
> > I could reproduce this with the reproducer in #35298 and the [ ... ]
> 
> I'm not following, or I am missing something trivial. The reproducer in #35298 is:
> 
> ```yaml
> spack:
>   specs:
>     - nco ^netcdf-c ~~mpi
> ```
> 
> being a single spec, does it matter if it is unified or not?

I can't recall if it matters to the propagation logic -- that may still be under investigation -- but should it not be using the expected option regardless of the number of specs? 

BTW The hint we had that it wasn't was the output of:  `==> Starting concretization`.

**Comment by alalazo** [comment]
> I can't recall if it matters to the propagation logic -- that may still be under investigation -- but should it not be using the expected option regardless of the number of specs?

It seems it is? I can't see a discrepancy between `spack config get` and what is in `spack.yaml`:

![Screenshot from 2023-06-12 22-27-02](https://github.com/spack/spack/assets/4199709/3542f70d-803a-4b99-90b5-71b05dbd0e1d)

To be clear, I'm trying to understand what is the bug we are solving with #38248.

**Comment by tldahlgren** [comment]
> To be clear, I'm trying to understand what is the bug we are solving with #38248.

The problem is the unify value in `spack.yaml` isn't getting read.  Should it not override the value in `concretizer.yaml`, etc.?

**Comment by alalazo** [comment]
> The problem is the unify value in spack.yaml isn't getting read. 

Can you post a `spack.yaml` of an environment that doesn't honor `concretizer:unify` when concretized? I tried to reproduce that and couldn't find any.[^1]

[^1]: The private function might be brittle when the environment is not active, but `spack concretize` requires an active environment, and I can't think of any other way of concretizing the environment off the top of my head.

**Comment by alalazo** [comment]
> BTW The hint we had that it wasn't was the output of: ==> Starting concretization.

In which sense? It seems to behave as it should for me:

![Screenshot from 2023-06-12 23-03-18](https://github.com/spack/spack/assets/4199709/e73e9681-4616-4c38-a3bc-5110378a900e)

The user posted output with `Starting concretization` but it might mean that he had another scope where he was setting `unify:false`, and all scopes were honored, right?

**Comment by tldahlgren** [comment]
If you add debug outputs to `environment/environment.py`for the `_concretize_X` methods; set `concretizer.yaml`'s `unify` option to some value, then set `spack.yaml`'s option to a different value, the configuration option is used by `spack spec`, not the one in `spack.yaml`.

**Comment by alalazo** [comment]
Thanks, so the bug is with `spack spec`. What I was asking was something like:
```console
$ spack config --scope user add concretizer:unify:false
$ spack env activate --temp
$ spack add zlib@1.2.13
$ spack add zlib@1.2.12
$ spack config add concretizer:unify:true
$ spack concretize
==> Error: concretization failed for the following reasons:

   1. Cannot select a single "version" for package "zlib"
   2. Cannot satisfy 'zlib@1.2.13'
   3. Cannot satisfy 'zlib@1.2.12'. You could consider setting `concretizer:unify` to `when_possible` or `false` to allow multiple versions of some packages.

$ spack spec
==> Starting concretization pool with 2 processes
==> Warning: using "zlib@1.2.12" which is a deprecated version
==> Environment concretized in 1.04 seconds.
Input spec
--------------------------------
zlib@1.2.13

Concretized
--------------------------------
zlib@1.2.13%gcc@9.4.0+optimize+pic+shared build_system=makefile arch=linux-ubuntu20.04-icelake

Input spec
--------------------------------
zlib@1.2.12

Concretized
--------------------------------
zlib@1.2.12%gcc@9.4.0+optimize+pic+shared build_system=makefile patches=0d38234 arch=linux-ubuntu20.04-icelake

```
Would you mind if we add this reproducer to the description above, and change the title to:
```
   `spack spec` doesn't honor concretizer options in the environment scope 
```
or something like that (definitely less alarming than the initial bug report)?

**Comment by tldahlgren** [comment]
> Thanks, so the bug is with `spack spec`. What I was asking was something like:

Ah.  I understand now.


> 
> Would you mind if we add this reproducer to the description above, and change the title to:
> 
> ```
>    `spack spec` doesn't honor concretizer options in the environment scope 
> ```
> 
> or something like that (definitely less alarming than the initial bug report)?

Not at all.  My head was on the problem I was helping someone else debug with when I wrote the issue and fix.

**Comment by tldahlgren** [comment]
> > Thanks, so the bug is with `spack spec`. What I was asking was something like:
> 
> Ah. I understand now.
> 
> > Would you mind if we add this reproducer to the description above, and change the title to:
> > ```
> >    `spack spec` doesn't honor concretizer options in the environment scope 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > or something like that (definitely less alarming than the initial bug report)?
> 
> Not at all. My head was on the problem I was helping someone else debug with when I wrote the issue and fix.

Do you want to do that or shall I?

**Comment by alalazo** [comment]
> Do you want to do that or shall I?

I'll take a stab at it. Feel free to edit anything afterwards.

**Comment by alalazo** [comment]
Done editing :slightly_smiling_face:
