### ISSUE TITLE
Variant `when=`: Change of Default for Single/Multi-Variant Transition

### ISSUE THREAD

**Issue by ax3l** [LLNL/spack#38302]
### Steps to reproduce

In https://github.com/spack/spack/pull/37695, I introduced that a variant becomes a multi-variant for a certain version and later.

This [does not work](https://github.com/spack/spack/pull/37695#issuecomment-1558434361): Spack tries to always apply the new multi-variant defaults, even for older versions excluded by then variant `when` condition.

```py
    variant(
        "dimensions",
        default="3",
        values=("1", "2", "3"),
        multi=False,
        description="Dimensionality",
        when="@:23.05",
    )
    variant(
        "dimensions",
        default="1,2,3",
        values=("1", "2", "3"),
        multi=True,
        description="Dimensionality",
        when="@23.06:",
    )
```

### Error message

```bash
spack spec amrex  # >= 23.06
# all great!
```

But:
```bash
spack spec amrex@23.05
```
```
...
amrex@23.05%gcc@12.1.0~amrdata~cuda~eb~fortran~hdf5~hypre~ipo+linear_solvers+mpi~openmp~particles~petsc~pic~plotfile_tools~rocm~shared~sundials~sycl~tiny_profile build_system=cmake build_type=Release dimensions=1,2,3 generator=make precision=double arch=linux-ubuntu22.04-skylake
...
```
(should be `dimensions=3`)

```bash
spack install amrex@23.05
```
```
...
==> Installing amrex-23.05-5crixpvv3zbjvxrdyqkxc7lsqngbcmuv
==> No binary for amrex-23.05-5crixpvv3zbjvxrdyqkxc7lsqngbcmuv found: installing from source
==> Using cached archive: /home/axel/src/spack/var/spack/cache/_source-cache/archive/a4/a4bf5ad5322e706b9fae46ff52043e2cca5ddba81479647816251e9ab21c0027.tar.gz
==> No patches needed for amrex
==> amrex: Executing phase: 'cmake'
==> Error: ProcessError: Command exited with status 1:
    '/home/axel/src/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.1.0/cmake-3.25.2-54fooma2lakox5es5ucus5kzpbn7xosy/bin/cmake' ... '-DAMReX_SPACEDIM:STRING=1;2;3' ...
...
(expected CMake configure-time error follows)
```
(should be `-DAMReX_SPACEDIM=3`)

### Information on your system

* **Spack:** 0.21.0.dev0 (2cdc902ead5894d2fc0ee93de7564c0c883e7d6b)
* **Python:** 3.10.6
* **Platform:** linux-ubuntu22.04-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Not sure I'd call this a bug, since it's documented, see [this section of the docs](https://spack.readthedocs.io/en/latest/packaging_guide.html#overriding-variants) :slightly_smiling_face: 

As a workaround you might use two slightly different names for the variants. In any case, I noted the use case! Thanks for the report.

**Comment by ax3l** [comment]
Comment by @tgamblin on Slack:
> FYI: in re-structuring the directive metadata on classes, I’ve got variants indexed by condition (instead of name) now.  Which should allow us to have conditional defaults (which you can currently express but which do not work).  I think I can fix this

I will try `develop` on AMReX' package.

**Comment by ax3l** [comment]
`development` as of ebd41134fe4001760dde1269baa53b922e00ee15 with #37695:

Good (new hotness multi-variant):
```
spack spec --fresh amrex
... dimension=1,2,3
```

Still kaputt (old versions with single variant) :
```
spack spec --fresh amrex@23.05
... dimension=1,2,3
should be:
... dimension=3
```

**Comment by alalazo** [comment]
@ax3l Changed this to a feature proposal, added it to v0.21 (planned for release around SC23)

**Comment by alalazo** [comment]
Reopening :sweat_smile: 

![2023-11-10_14-29](https://github.com/spack/spack/assets/4199709/861eeb4d-5e1b-4e13-ab44-808949fd6f64)
