### ISSUE TITLE
Issues with system installed hg (Mercurial)

### ISSUE THREAD

**Issue by keitat** [LLNL/spack#3831]
Since Mercurial is built with python, it is highly recommended to use the python modules as the build.  However, Spack builds its own python and tries to import its own python module.  This is a big problem when Spack is calling system-installed hg, throwing an error due to the mismatch.  I strongly recommend that Spack should build its own hg when it builds its own python.

**Comment by adamjstewart** [comment]
We've gotten several other reports of problems with mercurial in Spack:

#3793 
#3591 
#2816
#1645 

Maybe one of those has a suggestion that will help? I don't personally use `hg` or build any packages that require it so I haven't encountered this bug yet myself.

**Comment by keitat** [comment]
Iit is fllow-up of #3591.  It appears hg needs to build mercurial using its own python. In order to avoid this I am using system-installed python and special version of hg that point the absolute path to access python modules and libs.  

Also #2816 seems the relative path issues of hg.

**Comment by adamjstewart** [comment]
What do you think the solution is? Should we modify the shebang so that it points to the Python that Spack installs as a dependency? I'll see if I can reproduce this on my laptop.

**Comment by keitat** [comment]
I suggest two things:
(1) If Spack is building python, it should build hg using its own python.
(2) When hg is build by Sack, hg should point the absolute path of python modules/libraries.  or Spack should set the current directly to hg's location.

**Comment by adamjstewart** [comment]
> (1) If Spack is building python, it should build hg using its own python.

Do you mean "If Spack is building mercurial, it should build mercurial using its own Python"? This is already the case, although it depends on whether or not the user wants to use an external Python package.

> (2) When hg is build by Sack, hg should point the absolute path of python modules/libraries.

Just the shebang for the `hg` executable? I'll see what I can do.

**Comment by keitat** [comment]
As for (1), the answer is partially yes, but it does not cover the case when Spack is building its own python.  The system built mercurial is dependent on the system-built python, but Spack tries to execute the system-built mercurial with its own python. This is a major problem.  I guess there must be workaround to avoid that.

As for (2), yes!

**Comment by keitat** [comment]
I guess resolving the relative path issues of hg (see the content of /usr/bin/hg) will resolve the Spack-mercurial issue.

**Comment by adamjstewart** [comment]
> but Spack tries to execute the system-built mercurial with its own python.

Oh interesting. My `hg` contains `#!/usr/bin/python` so I think it should be using the system Python in that case. I'm not sure if there's a way to prevent this if the shebang looks like `#!/usr/bin/env python`. In that the case the executable uses whatever comes first in the PATH.

**Comment by keitat** [comment]
Is it possible for Spack to edit the content of its own hg?

**Comment by adamjstewart** [comment]
It can edit the content of the `hg` it builds, but it cannot edit the content of `/usr/bin/hg` as the user likely doesn't have permission to do that.

**Comment by adamjstewart** [comment]
Can you try out #3834 and see if it solves any of your problems?
