### ISSUE TITLE
Concretizer infinite loop with "require"

### ISSUE THREAD

**Issue by G-Ragghianti** [LLNL/spack#38323]
### Steps to reproduce

When "requiring" a certain provider (e.g. openmpi for mpi), the concretizer enters what appears to be an infinite loop if another provider is requested as a root spec.  The result is that it is not possible to ever install any other provider if you decide to "require" one.

Dockerfile:
```
FROM spack/ubuntu-focal
COPY packages.yaml /opt/spack/etc/spack/
RUN spack -d solve --show=all mpich
```

packages:yaml:
```
packages:
  all:
    require: "openmpi"
```

### Error message

```
$ spack -d solve --show=all mpich
...
%============================================================================
% Error messages
%============================================================================
internal_error("Two versions with identical weights").
internal_error("Reuse version weight used for built package").
internal_error("External weight used for built package").
internal_error("Reuse version weight used for build package").
internal_error("Build version weight used for reused package").
internal_error("imposed hash without imposing all variant values").
internal_error("imposed hash without imposing all flag values").
internal_error("Virtual when provides not respected").
internal_error("Package provider weights must be unique").
internal_error("External weight used for internal spec").
internal_error("Reused OS incompatible with build OS").
internal_error("Package must resolve to at most one hash").
<process doesn't finish>
```

### Information on your system

* **Spack:** 0.21.0.dev0
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-broadwell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
We certainly need a better error message... but what was the initial purpose of:
```yaml
packages:
  all:
    require: "openmpi"
```
? That doesn't seem to make a lot of sense, since you require every package to be openmpi...

**Comment by G-Ragghianti** [comment]
OK, thanks for the sanity check.  Changing to the following does work more as expected:
```
packages:
   mpi: 
      require: "openmpi"
```

I still have the problem that I'm unable to really use the "require" functionality because we need to sometimes install with another mpi.  I was hoping that by putting "package ^mpich" explicitly in the spec it would override the "require" in packages.yaml, but it looks like that isn't the case.

The problem that I was trying to work around here is that we were finding that spack was picking up a random mpi provider even though I was specifying the preferred provider in packages.yaml and I was using --fresh.  In this case, the "provider" was mpitrampoline which didn't exactly work.  I will try to set up a separate example case for this.

**Comment by alalazo** [comment]
There's a slightly tricky gotcha with requirements semantic, that we still have to decide if we want to put syntactic sugar around and make it a feature. Long story short, you can try:
```yaml
packages:
   mpi: 
      require: 
      - any_of: ["openmpi", "@:"]
```
This is effectively a much stronger form of preference, since the requirements are tried to be satisfied "in order". Leaving a `@:` (any version requirements) let you still decide to put `mpich` on the command line to override the default `openmpi`. Let me know if this works.

**Comment by G-Ragghianti** [comment]
Thanks for the idea, but I get `==> Error: Preference for version : does not match any version defined for mpi (in its package.py or any external)`.

I also tried changing it to `@4`, but it resulted in a similar message.
