### ISSUE TITLE
oneapi modules are broken

### ISSUE THREAD

**Issue by simonLeary42** [LLNL/spack#38401]
### Steps to reproduce

```
# spack version < 0.20.0
$ spack install intel-oneapi-mpi
# upgrade to spack 0.20.0
$ spack module lmod refresh intel-oneapi-mpi
$ module load intel-oneapi-mpi
$ mpirun
no such file or directory
```

### Error message

[This commit](https://github.com/spack/spack/commit/8a02463d7d14de275d5090fdf07a29af26d44e0e
) adds an `envmods` variant to oneapi packages. 
Without `+envmods`, you still get environment modules, they're just broken. They require the administrator to configure prefix inspections by hand.
Because oneapi packages don't have a standard layout, normal prefix inspections cannot find the `bin/` `lib/` `include/` directories. `vars.sh` is included by intel, which adds those directories to their respective paths. Without `+envmods`, `vars.sh` is not sourced.

In the code, it only does `vars.sh` if `+envmods`. Any package installed before this update is **not** `+envmods`. If I change it to do `vars.sh` if  `not ~envmods`, then it generates the correct modulefile. What should have been an "opt-in" feature is now an "opt-out" feature.

here's the fix: https://github.com/spack/spack/pull/38400

### Information on your system

```
* **Spack:** 0.20.0
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-x86_64
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Fixed in #38400
