### ISSUE TITLE
Installation issue: py-gsutil requires google-reauth

### ISSUE THREAD

**Issue by mnijhuis-tos** [LLNL/spack#38414]
### Steps to reproduce the issue

```console
$ gsutil
```

### Error message

<details><summary>Error message</summary>
<pre>
Traceback (most recent call last):
  File "/var/software/spack/opt/spack/linux-rocky8-zen2/gcc-9.4.0/py-gsutil-5.2-jdjkawwy2tq4kngjpoxewyijx25vodev/bin/gsutil", line 5, in <module>
    from gslib.__main__ import main
  File "/var/software/spack/opt/spack/linux-rocky8-zen2/gcc-9.4.0/py-gsutil-5.2-jdjkawwy2tq4kngjpoxewyijx25vodev/lib/python3.9/site-packages/gslib/__main__.py", line 85, in <module>
    from google_reauth import reauth_creds
ModuleNotFoundError: No module named 'google_reauth'
</pre></details>

### Information on your system

* **Spack:** 0.19.2 (45accfac1584ca9c303b61a1f7e9097a3693a73e)
* **Python:** 3.6.8
* **Platform:** linux-rocky8-zen2
* **Concretizer:** clingo

### Additional information

@dorton21 After installing py-gsutil and running it, it complains about a missing google-reauth module.

When I install google-reauth using `pip3 install google-reauth`, for example, gsutil runs fine again.

google-reauth is indeed not in the dependencies of gsutil. There isn't even a spack package for it. On pypi google-reauth is here: https://pypi.org/project/google-reauth/

Please create a spack package for google-reauth and add a (runtime) dependency to it for py-gsutil. I tried both py-gsutil@5.2 and py-gsutil@4.59. Both have the same issue.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by manuelakuhn** [comment]
Can you check if #38450 fixes the problem for you?

**Comment by mnijhuis-tos** [comment]
#38450 indeed fixes the problem. I checked out your py-gsutil-5.24 branch, and used it together with an upstream spack repo at version 0.19.2.

After installing py-gsutil version 5.24, `module load py-gsutil` initially did not work because the new module file has dependencies on python packages in the upstream spack repo, which did not have a module file yet. After installing the module files in the upstream repo, `module load py-gsutil` worked and executing `py-gsutil` works fine, too.

Thanks for the fix!
