### ISSUE TITLE
Installation issue: intel-oneapi-compiler

### ISSUE THREAD

**Issue by dubmarm** [LLNL/spack#38453]
### Steps to reproduce the issue

Using Centos 7.9 with System GCC 4.8.5:

Start by installing a newer GCC with Spack, then installing `intel-oneapi-compilers` using the newer GCC.

```console
spack install gcc@11.3.0
spack compiler find --scope site `spack location -i gcc@11.3.0`
spack install intel-oneapi-compilers@2023.0.0%gcc@11.3.0
spack compiler find --scope site `spack location -i intel-oneapi-compilers@2023.0.0`/compiler/latest/linux/bin/intel64
spack compiler find --scope site `spack location -i intel-oneapi-compilers@2023.0.0`/compiler/latest/linux/bin
```

Now inspect the `icc` library
```console
ldd `spack location -i intel-oneapi-compilers@2023.0.0`/compiler/latest/linux/bin/intel64/icc
```

Notice that `libstdc++.so.6` and `libgcc_s.so.1 ` are pointing to `/usr/lib64` and not the Spack GCC location.

The reason is because Spack does not manage `LD_LIBRARY_PATH` and opts instead for `rpath` through the compiler. Using `rpath` is acceptable when the compiler is used with package installs but `intel-oneapi-compilers` is installed using an offline script with a pre-built binary. This means that the newer GCC isn't performing any `configur` or `build` and thus `rpath` isn't provided to the installation process.

This causes intel-oneapi-compilers to not accept any Spack provided compilers

### Error message

<details><summary>Error message</summary>
<pre>
 linux-vdso.so.1 => (0x00007ffcb4033000)
 libdl.so.2 => /lib64/libdl.so.2 (0x00002aaf05a77000)
 libpthread.so.0 => /lib64/libpthread.so.0 (0x00002aaf05c7b000)
 libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00002aaf05e97000)
 libm.so.6 => /lib64/libm.so.6 (0x00002aaf0619f000)
 libc.so.6 => /lib64/libc.so.6 (0x00002aaf064a1000)
 /lib64/ld-linux-x86-64.so.2 (0x00002aaf0540c000)
 libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00002aaf0686f000)
</pre></details>

### Information on your system

```console
* **Spack:** 0.20.0
* **Python:** 3.6.8
* **Platform:** linux-centos7-cascadelake
* **Concretizer:** clingo
```

### Additional information

@rscohn2 - I propose some logic in the `intel-oneapi-compilers` package:

```python
class IntelOneapiCompilers(...):
    ...
    def setup_build_environment(self, env):
        compiler_prefix = os.path.dirname(os.path.dirname(self.compiler.cc))
        compiler_libdir = os.path.join(compiler_prefix, "lib64")
        compiler_libdir = os.path.join(compiler_prefix, "lib64/lib")
        compiler_libdir = os.path.join(compiler_prefix, "lib/gcc")
        env.prepend_path("LD_LIBRARY_PATH", compiler_libdir)
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by rscohn2** [comment]
What is the actual issue? The compiler cannot run because of missing
symbols?

**Comment by dubmarm** [comment]
On CentOS 7.9 the System Compiler gcc@4.8.5 is not compatible with intel-oneapi-compilers >v2023. You will receive the following on `icc`.

```console
`spack location -i intel-oneapi-compilers@2023.0.0`/compiler/latest/linux/bin/intel64/icc
icc: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found
```

This is alleviated by installing a newer GCC and adding the path to it's libs via `LD_LIBRARY_PATH` prior to the offline install of intel-oneapi-compilers. Upon doing so, icc will function on a CentOS machine.

The issue is that spack is not managing this during install of intel. The spack package for intel-oneapi-compilers can benefits from LD_LIBRARY_PATH additions for the compiler used during install.

**Comment by rscohn2** [comment]
Thanks for the explanation. Do you want to do a PR?

**Comment by dubmarm** [comment]
@rscohn2 - I'm closing this ticket. The truth is that OneApi 2023 is not guaranteed to work with CentOS7.9. Any actions I do to get OneApi 2023 to work on the system are against the grain of standard installation. The solution for me to include `LD_LIBRARY_PATH` for a newer GCC is a personal solution and not one for the community.

Thank you for your time.
