### ISSUE TITLE
Installation issue: `blaspp%clang ^intel-mkl threads=openmp`

### ISSUE THREAD

**Issue by msimberg** [LLNL/spack#38509]
### Steps to reproduce the issue

```console
$ spack spec -lI blaspp%clang ^intel-mkl%clang threads=openmp ^cpio%gcc
Input spec
--------------------------------
 -   blaspp%clang@16.0.3
 -       ^cpio%gcc
 -       ^intel-mkl%clang@16.0.3 threads=openmp

Concretized
--------------------------------
[+]  dqga76p  blaspp@2022.07.00%clang@16.0.3~cuda~ipo+openmp~rocm+shared build_system=cmake build_type=Release generator=make arch=linux-sles15-zen2
[+]  bygfejv      ^cmake@3.26.3%clang@16.0.3~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-sles15-zen2
[+]  tb224zl          ^ncurses@6.4%clang@16.0.3~symlinks+termlib abi=none build_system=autotools arch=linux-sles15-zen2
[+]  debzyfk              ^pkgconf@1.9.5%clang@16.0.3 build_system=autotools arch=linux-sles15-zen2
[+]  gquffzx          ^openssl@1.1.1t%clang@16.0.3~docs~shared build_system=generic certs=mozilla arch=linux-sles15-zen2
[+]  r7jfni4              ^ca-certificates-mozilla@2023-01-10%clang@16.0.3 build_system=generic arch=linux-sles15-zen2
[+]  agxnhxr              ^perl@5.36.0%clang@16.0.3+cpanm+open+shared+threads build_system=generic arch=linux-sles15-zen2
[+]  aiglqel                  ^berkeley-db@18.1.40%clang@16.0.3+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-sles15-zen2
[+]  ms3ryj3                  ^bzip2@1.0.8%clang@16.0.3~debug~pic+shared build_system=generic arch=linux-sles15-zen2
[+]  7crhm2x                      ^diffutils@3.9%clang@16.0.3 build_system=autotools arch=linux-sles15-zen2
[+]  edumkq5                          ^libiconv@1.17%clang@16.0.3 build_system=autotools libs=shared,static arch=linux-sles15-zen2
[+]  5yczp3m                  ^gdbm@1.23%clang@16.0.3 build_system=autotools arch=linux-sles15-zen2
[+]  gii6t5n                      ^readline@8.2%clang@16.0.3 build_system=autotools patches=bbf97f1 arch=linux-sles15-zen2
[+]  uanvqr7              ^zlib@1.2.13%clang@16.0.3+optimize+pic+shared build_system=makefile arch=linux-sles15-zen2
[+]  43d6jwd      ^gmake@4.4.1%clang@16.0.3~guile build_system=autotools arch=linux-sles15-zen2
[+]  vllde3z      ^intel-mkl@2020.4.304%clang@16.0.3~ilp64+shared build_system=generic threads=openmp arch=linux-sles15-zen2
[^]  2dbxane          ^cpio@2.14%gcc@13.1.0 build_system=autotools arch=linux-sles15-zen2
```

You can ignore the `%clang@16.0.3` on `intel-mkl` in the spec, it was only to force the use of clang over an existing `intel-mkl@gcc`. That `intel-mkl` is using `clang` _is_ important for this issue. The `^cpio%gcc` was likewise to force the use of an upstream `cpio`.

### Error message

<details><summary>Error message</summary>

<pre>
==> Installing blaspp-2022.07.00-dqga76ps3oepp4x7m3n4wzlwbn3judfa
==> No binary for blaspp-2022.07.00-dqga76ps3oepp4x7m3n4wzlwbn3judfa found: installing from source
==> Using cached archive: /scratch/e1000/apps/hohgant/simbergm/spack/var/spack/cache/_source-cache/archive/56/566bd644f0364caffde6669e0f86514658eb06ca3d252a4fe67203921a875481.tar.gz
==> No patches needed for blaspp
==> blaspp: Executing phase: 'cmake'
==> [2023-06-21-17:37:16.626589] '/user-environment/linux-sles15-zen2/gcc-11.3.0/llvm-16.0.3-uam36b553br26w5kqdkbyfox6ol3ybqt/bin/clang' '--print-file-name' 'libomp.so'
==> [2023-06-21-17:37:16.656522] blas_libs.openmp_libs: libomp.so
==> [2023-06-21-17:37:16.658888] normalize_path.normalize_suite_dir:    trying /scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/intel-mkl-2020.4.304-vllde3zfeyedptddc4f3k4nt5teszzz3/compilers_and_libraries_2020.4.304
==> [2023-06-21-17:37:16.660948] normalize_path.normalize_suite_dir:    found 1:
  ['/scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/intel-mkl-2020.4.304-vllde3zfeyedptddc4f3k4nt5teszzz3/compilers_and_libraries_2020.4.304']
==> [2023-06-21-17:37:16.662919] normalize_path.normalize_suite_dir:    /scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/intel-mkl-2020.4.304-vllde3zfeyedptddc4f3k4nt5teszzz3/compilers_and_libraries_2020.4.304
==> [2023-06-21-17:37:16.664909] component_lib_dir.normalize_path:      /scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/intel-mkl-2020.4.304-vllde3zfeyedptddc4f3k4nt5teszzz3/compilers_and_libraries_2020.4.304/linux/mkl
==> [2023-06-21-17:37:16.666758] blas_libs.component_lib_dir:   /scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/intel-mkl-2020.4.304-vllde3zfeyedptddc4f3k4nt5teszzz3/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64
==> [2023-06-21-17:37:16.669352] <lambda>.blas_libs:    /scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/intel-mkl-2020.4.304-vllde3zfeyedptddc4f3k4nt5teszzz3/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64/libmkl_intel_lp64.so /scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15
-zen2/clang-16.0.3/intel-mkl-2020.4.304-vllde3zfeyedptddc4f3k4nt5teszzz3/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64/libmkl_gnu_thread.so /scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/intel-mkl-2020.4.304-vllde3zfeyedptddc4f3k4nt5teszzz3/compilers_and_libraries_2020.4.304/linux/mkl/lib
/intel64/libmkl_core.so
==> [2023-06-21-17:37:16.851471] <lambda>.blas_libs:    /usr/lib64/libpthread.so /usr/lib64/libm.so /usr/lib64/libdl.so
==> [2023-06-21-17:37:16.852930] '/scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/cmake-3.26.3-bygfejvcijsoynjy4s3gda62r55iqmex/bin/cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/blaspp-2022.07.00-dqga76p
s3oepp4x7m3n4wzlwbn3judfa' '-DCMAKE_BUILD_TYPE:STRING=Release' '-DBUILD_TESTING:BOOL=OFF' '-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=OFF' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON' '-DCMAKE_INSTALL_RPATH:STRING=/scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/blas
pp-2022.07.00-dqga76ps3oepp4x7m3n4wzlwbn3judfa/lib;/scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/blaspp-2022.07.00-dqga76ps3oepp4x7m3n4wzlwbn3judfa/lib64;/scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/intel-mkl-2020.4.304-vllde3zfeyedptddc4f3k4nt5teszzz3/lib' '-
DCMAKE_PREFIX_PATH:STRING=/scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/intel-mkl-2020.4.304-vllde3zfeyedptddc4f3k4nt5teszzz3;/scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/gmake-4.4.1-43d6jwdilwwiq25mrgzpztuvpc24pvjq;/scratch/e1000/apps/hohgant/simbergm/spack/o
pt/spack/linux-sles15-zen2/clang-16.0.3/cmake-3.26.3-bygfejvcijsoynjy4s3gda62r55iqmex' '-Dbuild_tests=False' '-Duse_openmp=True' '-DBUILD_SHARED_LIBS=True' '-Dgpu_backend=none' '-DBLAS_LIBRARIES=/scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/intel-mkl-2020.4.304-vllde3zfeyedptddc4f3k4nt5teszzz3/comp
ilers_and_libraries_2020.4.304/linux/mkl/lib/intel64/libmkl_intel_lp64.so;/scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/intel-mkl-2020.4.304-vllde3zfeyedptddc4f3k4nt5teszzz3/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64/libmkl_gnu_thread.so;/scratch/e1000/apps/hohgant/simbergm/spack/opt/
spack/linux-sles15-zen2/clang-16.0.3/intel-mkl-2020.4.304-vllde3zfeyedptddc4f3k4nt5teszzz3/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64/libmkl_core.so;libomp.so;/usr/lib64/libpthread.so;/usr/lib64/libm.so;/usr/lib64/libdl.so' '/tmp/simbergm/spack-stage/spack-stage-blaspp-2022.07.00-dqga76ps3oepp4x7m3n4wzlwbn3judfa/spack-src
'
-- The CXX compiler identification is Clang 16.0.3
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /scratch/e1000/apps/hohgant/simbergm/spack/lib/spack/env/clang/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Using CMAKE_INSTALL_PREFIX = /scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/blaspp-2022.07.00-dqga76ps3oepp4x7m3n4wzlwbn3judfa
-- Skipping CUDA search. gpu_backend = none
-- Not building CUDA support in BLAS++
-- Skipping HIP/ROCm search. gpu_backend = none
-- Not building HIP/ROCm support in BLAS++
-- Found OpenMP_CXX: -fopenmp=libomp (found version "5.0")
-- Found OpenMP: TRUE (found version "5.0")
-- Looking for BLAS libraries and options
$BLAS_LIBRARIES
   libs:  /scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/intel-mkl-2020.4.304-vllde3zfeyedptddc4f3k4nt5teszzz3/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64/libmkl_intel_lp64.so;/scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/intel-mkl-2020.4.304-vllde3
zfeyedptddc4f3k4nt5teszzz3/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64/libmkl_gnu_thread.so;/scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/intel-mkl-2020.4.304-vllde3zfeyedptddc4f3k4nt5teszzz3/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64/libmkl_core.so;libomp.so;/usr/lib64/l
ibpthread.so;/usr/lib64/libm.so;/usr/lib64/libdl.so
   -DBLAS_FORTRAN_ADD_                              no (library not found)

   BLAS library not found.
CMake Error at CMakeLists.txt:374 (message):
  BLAS++ requires a BLAS library and none was found.  Ensure that it is
  accessible in environment variables $CPATH, $LIBRARY_PATH, and
  $LD_LIBRARY_PATH.

-- Configuring incomplete, errors occurred!
==> Error: ProcessError: Command exited with status 1:
    '/scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/cmake-3.26.3-bygfejvcijsoynjy4s3gda62r55iqmex/bin/cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/blaspp-2022.07.00-dqga76ps3oepp4x7m3n4wzlwbn3judfa' '-
DCMAKE_BUILD_TYPE:STRING=Release' '-DBUILD_TESTING:BOOL=OFF' '-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=OFF' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON' '-DCMAKE_INSTALL_RPATH:STRING=/scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/blaspp-2022.07.00-dqga76ps3oepp4x
7m3n4wzlwbn3judfa/lib;/scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/blaspp-2022.07.00-dqga76ps3oepp4x7m3n4wzlwbn3judfa/lib64;/scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/intel-mkl-2020.4.304-vllde3zfeyedptddc4f3k4nt5teszzz3/lib' '-DCMAKE_PREFIX_PATH:STRING=/sc
ratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/intel-mkl-2020.4.304-vllde3zfeyedptddc4f3k4nt5teszzz3;/scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/gmake-4.4.1-43d6jwdilwwiq25mrgzpztuvpc24pvjq;/scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/cl
ang-16.0.3/cmake-3.26.3-bygfejvcijsoynjy4s3gda62r55iqmex' '-Dbuild_tests=False' '-Duse_openmp=True' '-DBUILD_SHARED_LIBS=True' '-Dgpu_backend=none' '-DBLAS_LIBRARIES=/scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/intel-mkl-2020.4.304-vllde3zfeyedptddc4f3k4nt5teszzz3/compilers_and_libraries_2020.4.30
4/linux/mkl/lib/intel64/libmkl_intel_lp64.so;/scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/intel-mkl-2020.4.304-vllde3zfeyedptddc4f3k4nt5teszzz3/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64/libmkl_gnu_thread.so;/scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang
-16.0.3/intel-mkl-2020.4.304-vllde3zfeyedptddc4f3k4nt5teszzz3/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64/libmkl_core.so;libomp.so;/usr/lib64/libpthread.so;/usr/lib64/libm.so;/usr/lib64/libdl.so' '/tmp/simbergm/spack-stage/spack-stage-blaspp-2022.07.00-dqga76ps3oepp4x7m3n4wzlwbn3judfa/spack-src'

1 error found in build log:
     26    -- Looking for BLAS libraries and options
     27    $BLAS_LIBRARIES
     28       libs:  /scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/intel-mkl-2020.4.304-vllde3zfeyedptddc4f3k4nt5teszzz3/compiler
           s_and_libraries_2020.4.304/linux/mkl/lib/intel64/libmkl_intel_lp64.so;/scratch/e1000/apps/hohgant/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/in
           tel-mkl-2020.4.304-vllde3zfeyedptddc4f3k4nt5teszzz3/compilers_and_libraries_2020.4.304/linux/mkl/lib/intel64/libmkl_gnu_thread.so;/scratch/e1000/apps/hohgan
           t/simbergm/spack/opt/spack/linux-sles15-zen2/clang-16.0.3/intel-mkl-2020.4.304-vllde3zfeyedptddc4f3k4nt5teszzz3/compilers_and_libraries_2020.4.304/linux/mkl
           /lib/intel64/libmkl_core.so;libomp.so;/usr/lib64/libpthread.so;/usr/lib64/libm.so;/usr/lib64/libdl.so
     29       -DBLAS_FORTRAN_ADD_                              no (library not found)
     30
     31       BLAS library not found.
  >> 32    CMake Error at CMakeLists.txt:374 (message):
     33      BLAS++ requires a BLAS library and none was found.  Ensure that it is
     34      accessible in environment variables $CPATH, $LIBRARY_PATH, and
     35      $LD_LIBRARY_PATH.
     36
     37
     38    -- Configuring incomplete, errors occurred!

See build log for details:
  /tmp/simbergm/spack-stage/spack-stage-blaspp-2022.07.00-dqga76ps3oepp4x7m3n4wzlwbn3judfa/spack-build-out.txt
</pre></details>

### Information on your system

* **Spack:** 0.21.0.dev0 (bc8b0260724387a78fdb5e549fb3f98532e874df)
* **Python:** 3.6.15
* **Platform:** linux-sles15-zen2
* **Concretizer:** clingo

### Additional information

`spack-build-out.txt` and `spack-build-env.txt`: https://gist.github.com/msimberg/f68ec3b5e740f3d62aa2f641cdcabdca

Pinging @teonnik, @Sely85, @G-Ragghianti, @mgates3 as maintainers of `blaspp`, **but I think this is in fact an intel build system/clang/llvm issue** so also pinging @mgsternberg (who added `openmp_libs`) and @luszczek (who added the LLVM OpenMP support). Pinging @trws, @haampie, @skosukhin as `llvm` maintainers. Are there designated maintainers for build systems?

Starting with version 14 clang refuses to link to `-lomp` without also having an `-fopenmp` flag (I don't have a reference for this, so I don't know if this is intentional; I just tested clang 13 to 16, also in the ubuntu repositories, not built with spack). This is what is causing the configuration error. When `intel-mkl` is built with `%clang` and `threads=openmp` `libomp` is explicitly linked because of https://github.com/spack/spack/blob/bcb7af6eb371b8958824e2f0551c4baa88d754a3/lib/spack/spack/build_systems/intel.py#L704. This is then translated to `-lomp` by CMake and clang is unable to find `libomp` (see `blas_libs` and `openmp_libs` in the output). clang is able to find `libomp` if it's passed `-fopenmp=libomp` instead.

With the following patch `blaspp` does build:
```patch
diff --git a/lib/spack/spack/build_systems/intel.py b/lib/spack/spack/build_systems/intel.py
index dbb8313acf..e0eb8edf8e 100644
--- a/lib/spack/spack/build_systems/intel.py
+++ b/lib/spack/spack/build_systems/intel.py
@@ -699,11 +699,7 @@ def openmp_libs(self):
             omp_libs = LibraryList(omp_lib_path.strip())

         elif "%clang" in self.spec:
-            with self.compiler.compiler_environment():
-                omp_lib_path = Executable(self.compiler.cc)(
-                    "--print-file-name", "libomp.%s" % dso_suffix, output=str
-                )
-            omp_libs = LibraryList(omp_lib_path.strip())
+            omp_libs = LibraryList("-fopenmp=libomp")

         if len(omp_libs) < 1:
             raise_lib_error("Cannot locate OpenMP libraries:", omp_libnames)
```
If this seems like a good idea I can open a PR. However, I wasn't sure if there's a specific reason to explicitly link to `libomp` the way it's linked right now.

For reference, in a build env with `%clang@16.0.3`:
```
> cat test.cpp
int main() {}
> clang++ --version
clang version 16.0.3
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /user-environment/linux-sles15-zen2/gcc-11.3.0/llvm-16.0.3-uam36b553br26w5kqdkbyfox6ol3ybqt/bin
> clang++ -lomp test.cpp # not ok
/usr/bin/ld: cannot find -lomp
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
> clang++ -fopenmp -lomp test.cpp # a-ok
> clang++ -fopenmp=libomp test.cpp # a-ok
```
With `%clang@13.0.1`:
```
> clang++ --version
clang version 13.0.1
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /user-environment/linux-sles15-zen2/gcc-11.3.0/llvm-13.0.1-tgqv3rusxtmmynezxtvhywxbaa3ja4fh/bin
> clang++ -lomp test.cpp # a-ok
> clang++ -fopenmp -lomp test.cpp # a-ok
> clang++ -fopenmp=libomp test.cpp # a-ok
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by mgates3** [comment]
Thanks @msimberg for the detailed analysis. I agree this is an issue in the Intel build system, not BLAS++, which simply tries to link with `BLAS_LIBRARIES = spec["blas"].libs.joined(";")`. @msimberg's suggested fix seems fine to me, but I'm not familiar with Spack's Intel build system.

BLAS++ uses CMake's `try_run` with CMake's OpenMP target, `OpenMP::OpenMP_CXX` when blaspp+openmp. When compiling the .o file, try_run adds `-fopenmp=libomp` to the compile line (see output below). When linking the exe, try_run adds `/opt/spack/linux-rocky9-x86_64/gcc-9.5.0/llvm-16.0.3-2u6pqyplnyzghwe3766lc4nsl77tjn3i/lib/libomp.so` (substitute your local path) to the link line.

As @msimberg noted, adding `-lomp` breaks the link line because it can't find libomp, oddly even though it is explicitly mentioned on the link line (/opt/spack/.../libomp.so).

**Using `-lomp` fails**
```
sh leconte build> cmake -DLIBS='-lomp' ..
try_run
compile_result: FALSE
compile_output:
Change Dir: /home/mgates/test/clang/build/CMakeFiles/CMakeTmp

Run Build Command(s):/apps/spacks/2023-05-19/opt/spack/linux-rocky9-x86_64/gcc-9.5.0/cmake-3.26.3-dhly6isoy4zhoyfnbzfc6wogzsywql4s/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_5bafe/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_5bafe.dir/build.make CMakeFiles/cmTC_5bafe.dir/build
gmake[1]: Entering directory '/home/mgates/test/clang/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_5bafe.dir/hello.cc.o
/apps/spacks/2023-05-19/opt/spack/linux-rocky9-x86_64/gcc-9.5.0/llvm-16.0.3-2u6pqyplnyzghwe3766lc4nsl77tjn3i/bin/clang++   -fopenmp=libomp -MD -MT CMakeFiles/cmTC_5bafe.dir/hello.cc.o -MF CMakeFiles/cmTC_5bafe.dir/hello.cc.o.d -o CMakeFiles/cmTC_5bafe.dir/hello.cc.o -c /home/mgates/test/clang/hello.cc
Linking CXX executable cmTC_5bafe
/apps/spacks/2023-05-19/opt/spack/linux-rocky9-x86_64/gcc-9.5.0/cmake-3.26.3-dhly6isoy4zhoyfnbzfc6wogzsywql4s/bin/cmake -E cmake_link_script CMakeFiles/cmTC_5bafe.dir/link.txt --verbose=1
/apps/spacks/2023-05-19/opt/spack/linux-rocky9-x86_64/gcc-9.5.0/llvm-16.0.3-2u6pqyplnyzghwe3766lc4nsl77tjn3i/bin/clang++ CMakeFiles/cmTC_5bafe.dir/hello.cc.o -o cmTC_5bafe  -Wl,-rpath,/apps/spacks/2023-05-19/opt/spack/linux-rocky9-x86_64/gcc-9.5.0/llvm-16.0.3-2u6pqyplnyzghwe3766lc4nsl77tjn3i/lib -lomp /apps/spacks/2023-05-19/opt/spack/linux-rocky9-x86_64/gcc-9.5.0/llvm-16.0.3-2u6pqyplnyzghwe3766lc4nsl77tjn3i/lib/libomp.so /lib64/libpthread.a 
/usr/bin/ld: cannot find -lomp
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
gmake[1]: *** [CMakeFiles/cmTC_5bafe.dir/build.make:102: cmTC_5bafe] Error 1
gmake[1]: Leaving directory '/home/mgates/test/clang/build/CMakeFiles/CMakeTmp'
gmake: *** [Makefile:127: cmTC_5bafe/fast] Error 2


run_result: 0
run_output:

try_run done
-- Configuring done (0.4s)
-- Generating done (0.1s)
-- Build files have been written to: /home/mgates/test/clang/build
```

**Using `-fopenmp=libomp` is okay**
```
sh leconte build> cmake -DLIBS='-fopenmp=libomp' ..
try_run
compile_result: TRUE
compile_output:
Change Dir: /home/mgates/test/clang/build/CMakeFiles/CMakeTmp

Run Build Command(s):/apps/spacks/2023-05-19/opt/spack/linux-rocky9-x86_64/gcc-9.5.0/cmake-3.26.3-dhly6isoy4zhoyfnbzfc6wogzsywql4s/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_66ba0/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_66ba0.dir/build.make CMakeFiles/cmTC_66ba0.dir/build
gmake[1]: Entering directory '/home/mgates/test/clang/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_66ba0.dir/hello.cc.o
/apps/spacks/2023-05-19/opt/spack/linux-rocky9-x86_64/gcc-9.5.0/llvm-16.0.3-2u6pqyplnyzghwe3766lc4nsl77tjn3i/bin/clang++   -fopenmp=libomp -MD -MT CMakeFiles/cmTC_66ba0.dir/hello.cc.o -MF CMakeFiles/cmTC_66ba0.dir/hello.cc.o.d -o CMakeFiles/cmTC_66ba0.dir/hello.cc.o -c /home/mgates/test/clang/hello.cc
Linking CXX executable cmTC_66ba0
/apps/spacks/2023-05-19/opt/spack/linux-rocky9-x86_64/gcc-9.5.0/cmake-3.26.3-dhly6isoy4zhoyfnbzfc6wogzsywql4s/bin/cmake -E cmake_link_script CMakeFiles/cmTC_66ba0.dir/link.txt --verbose=1
/apps/spacks/2023-05-19/opt/spack/linux-rocky9-x86_64/gcc-9.5.0/llvm-16.0.3-2u6pqyplnyzghwe3766lc4nsl77tjn3i/bin/clang++ CMakeFiles/cmTC_66ba0.dir/hello.cc.o -o cmTC_66ba0  -Wl,-rpath,/apps/spacks/2023-05-19/opt/spack/linux-rocky9-x86_64/gcc-9.5.0/llvm-16.0.3-2u6pqyplnyzghwe3766lc4nsl77tjn3i/lib -fopenmp=libomp /apps/spacks/2023-05-19/opt/spack/linux-rocky9-x86_64/gcc-9.5.0/llvm-16.0.3-2u6pqyplnyzghwe3766lc4nsl77tjn3i/lib/libomp.so /lib64/libpthread.a 
gmake[1]: Leaving directory '/home/mgates/test/clang/build/CMakeFiles/CMakeTmp'


run_result: 0
run_output:
tid 0
tid 1
main

try_run done
-- Configuring done (0.5s)
-- Generating done (0.1s)
-- Build files have been written to: /home/mgates/test/clang/build
```
**Using full path `/opt/spack/.../libomp.so` is okay**
CMake's usual MO is to use absolute paths to libraries, which also solves the problem. But then libomp.so is listed twice on the link line, which to me invites conflicts.
```
sh leconte build> cmake -DLIBS='/apps/spacks/2023-05-19/opt/spack/linux-rocky9-x86_64/gcc-9.5.0/llvm-16.0.3-2u6pqyplnyzghwe3766lc4nsl77tjn3i/lib/libomp.so' ..
try_run
compile_result: TRUE
compile_output:
Change Dir: /home/mgates/test/clang/build/CMakeFiles/CMakeTmp

Run Build Command(s):/apps/spacks/2023-05-19/opt/spack/linux-rocky9-x86_64/gcc-9.5.0/cmake-3.26.3-dhly6isoy4zhoyfnbzfc6wogzsywql4s/bin/cmake -E env VERBOSE=1 /usr/bin/gmake -f Makefile cmTC_0e997/fast && /usr/bin/gmake  -f CMakeFiles/cmTC_0e997.dir/build.make CMakeFiles/cmTC_0e997.dir/build
gmake[1]: Entering directory '/home/mgates/test/clang/build/CMakeFiles/CMakeTmp'
Building CXX object CMakeFiles/cmTC_0e997.dir/hello.cc.o
/apps/spacks/2023-05-19/opt/spack/linux-rocky9-x86_64/gcc-9.5.0/llvm-16.0.3-2u6pqyplnyzghwe3766lc4nsl77tjn3i/bin/clang++   -fopenmp=libomp -MD -MT CMakeFiles/cmTC_0e997.dir/hello.cc.o -MF CMakeFiles/cmTC_0e997.dir/hello.cc.o.d -o CMakeFiles/cmTC_0e997.dir/hello.cc.o -c /home/mgates/test/clang/hello.cc
Linking CXX executable cmTC_0e997
/apps/spacks/2023-05-19/opt/spack/linux-rocky9-x86_64/gcc-9.5.0/cmake-3.26.3-dhly6isoy4zhoyfnbzfc6wogzsywql4s/bin/cmake -E cmake_link_script CMakeFiles/cmTC_0e997.dir/link.txt --verbose=1
/apps/spacks/2023-05-19/opt/spack/linux-rocky9-x86_64/gcc-9.5.0/llvm-16.0.3-2u6pqyplnyzghwe3766lc4nsl77tjn3i/bin/clang++ CMakeFiles/cmTC_0e997.dir/hello.cc.o -o cmTC_0e997  -Wl,-rpath,/apps/spacks/2023-05-19/opt/spack/linux-rocky9-x86_64/gcc-9.5.0/llvm-16.0.3-2u6pqyplnyzghwe3766lc4nsl77tjn3i/lib /apps/spacks/2023-05-19/opt/spack/linux-rocky9-x86_64/gcc-9.5.0/llvm-16.0.3-2u6pqyplnyzghwe3766lc4nsl77tjn3i/lib/libomp.so /lib64/libpthread.a 
gmake[1]: Leaving directory '/home/mgates/test/clang/build/CMakeFiles/CMakeTmp'


run_result: 0
run_output:
tid 0
tid 1
main

try_run done
-- Configuring done (0.5s)
-- Generating done (0.1s)
-- Build files have been written to: /home/mgates/test/clang/build
```

Here's a minimal working example to play with:
```
#===== CMakeLists.txt 
cmake_minimum_required( VERSION 3.18 )

project(
    hello
    LANGUAGES CXX
)

add_executable(
    hello
    hello.cc
)

find_package( OpenMP )
target_link_libraries( hello PUBLIC "OpenMP::OpenMP_CXX" )

try_run(
    run_result compile_result ${CMAKE_CURRENT_BINARY_DIR}
    SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/hello.cc"
    LINK_LIBRARIES OpenMP::OpenMP_CXX ${LIBS}
    #LINK_LIBRARIES ${LIBS}
    COMPILE_OUTPUT_VARIABLE compile_output
    RUN_OUTPUT_VARIABLE run_output
)

string( ASCII 27 Esc )
set( bold     "${Esc}[1m"  )
set( not_bold "${Esc}[22m" )
message( "${bold}try_run${not_bold}" )
message( "${bold}compile_result:${not_bold} ${compile_result}" )
message( "${bold}compile_output:${not_bold}\n${compile_output}" )
message( "${bold}run_result:${not_bold} ${run_result}" )
message( "${bold}run_output:${not_bold}\n${run_output}" )
message( "${bold}try_run done${not_bold}" )
```

```
//===== hello.cc 
#include <stdio.h>
#include <omp.h>

int main( int argc, char** argv )
{
    #pragma omp parallel
    {
        printf( "tid %d\n", omp_get_thread_num() );
    }

    printf( "%s\n", __func__ );
    return 0;
}
```

**Comment by msimberg** [comment]
I opened https://github.com/spack/spack/pull/38719 in the hope that CI might tell me if the patch above is even feasible.

**Comment by msimberg** [comment]
With https://github.com/spack/spack/pull/42653 and https://github.com/spack/spack/pull/42717 this is no longer an issue.
