### ISSUE TITLE
Installation issue: hdf-eos2 (permission issue, possible issue with autotools build system???)

### ISSUE THREAD

**Issue by payerle** [LLNL/spack#38527]
### Steps to reproduce the issue

When I try to install hdf-eos2 with
```console
$ spack install hdf-eos2
```
I get the following error regarding a permission error from do_patch_libtool_configure method in autotools.py (see next section).

Did a little digging, and it looks like the root issue is that the configure script included in the hdf-eos2 source does not have write permissions, so the attempt to patch the configure script in autotools fails.  I made a patch to the hdf-eos2 recipe to set write permissions on the configure script after the autoreconf phase, and was able to successfully install the package.

While patching the hdf-eos2 recipe is one way to resolve this issue (and I will gladly create a pull request to do so if there is consensus that such is the right approach), it is not clear to me that this is the best solution.  It seems to me that if autotools.py is going to patch the configure script, it should be responsible for ensuring the configure script is writable.  This probably should be done early in the autoreconf phase as I would not be surprised if similar permission issues arise if for some reason a new configure script needs to be generated.

I concede that the package should not have supplied a read-only version of configure, but insisting on standardized and reasonable behavior from package authors is not going to get one very far.  And while this is obviously not a wide-spread issue, it seems a bit odd to me that the package.py recipe (which makes no mention of patching configure script, and indeed is only patching it due to changes in autotools.py in the past year or two) needs to handle the permissions of the configure script.

As stated before, I am looking for advise from those wiser than me on the best way to handle this.  I can provide a patch for hdf-eos2 to fix the issue if that is where the consensus lies, or should autotools.py be patched (I am willing to look at that as well, but might need some assistance).

<details><summary>Full spec</summary>
**Note**: This is spec is for the package that was installed after patching package.py to chmod u+w the configure script.  That patch to the package.py was the only change, so I believe the spec from the original failed attempt should have been similar.
<pre>

$ spack spec -l hdf-eos2
Input spec
--------------------------------
hdf-eos2

Concretized
--------------------------------
qjb4sem  hdf-eos2@2.20v1.00%gcc@9.4.0+shared+static build_system=autotools patches=13ff7d3 arch=linux-rhel8-zen2
7jy7tin      ^hdf@4.2.15%gcc@9.4.0+external-xdr+fortran~java~netcdf+pic~shared+szip build_system=autotools patches=49733dd,5434f29,ce75518,d54592d,f7d67e8 arch=linux-rhel8-zen2
qtljvjx          ^bison@3.8.2%gcc@9.4.0 build_system=autotools arch=linux-rhel8-zen2
orifjxc              ^diffutils@3.9%gcc@9.4.0 build_system=autotools arch=linux-rhel8-zen2
jmrtao4                  ^libiconv@1.16%gcc@9.4.0 build_system=autotools libs=shared,static arch=linux-rhel8-zen2
ji474c2              ^m4@1.4.19%gcc@9.4.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-rhel8-zen2
soukbeu                  ^libsigsegv@2.13%gcc@9.4.0 build_system=autotools arch=linux-rhel8-zen2
ghy4s7e              ^perl@5.34.0%gcc@9.4.0+cpanm+open+shared+threads build_system=generic arch=linux-rhel8-zen2
nkkrcue                  ^berkeley-db@18.1.40%gcc@9.4.0+cxx+docs+stl build_system=autotools patches=26090f4 arch=linux-rhel8-zen2
gaoosb3                  ^bzip2@1.0.8%gcc@9.4.0~debug+pic+shared build_system=generic arch=linux-rhel8-zen2
tsdsqho                  ^gdbm@1.19%gcc@9.4.0 build_system=autotools arch=linux-rhel8-zen2
ryhrrvu                      ^readline@8.1%gcc@9.4.0 build_system=autotools patches=682a465,e55be05 arch=linux-rhel8-zen2
ayep6uy          ^flex@2.6.4%gcc@9.4.0+lex+nls build_system=autotools patches=f8b85a0 arch=linux-rhel8-zen2
elfboot              ^autoconf@2.69%gcc@9.4.0 build_system=autotools patches=35c4492,7793209,a49dd5b arch=linux-rhel8-zen2
iuzeaf5              ^automake@1.16.3%gcc@9.4.0 build_system=autotools arch=linux-rhel8-zen2
lr5iwpq              ^findutils@4.9.0%gcc@9.4.0 build_system=autotools patches=440b954 arch=linux-rhel8-zen2
cgping7              ^gettext@0.21.1%gcc@9.4.0+bzip2+curses+git+libunistring+libxml2+tar+xz build_system=autotools arch=linux-rhel8-zen2
vfb4rye                  ^libunistring@1.1%gcc@9.4.0 build_system=autotools arch=linux-rhel8-zen2
zteihso                  ^libxml2@2.9.12%gcc@9.4.0~python build_system=autotools patches=3e06d42 arch=linux-rhel8-zen2
2nd5xjs                  ^ncurses@6.2%gcc@9.4.0+symlinks+termlib abi=5 build_system=autotools arch=linux-rhel8-zen2
mu5rza6                  ^tar@1.30%gcc@9.4.0 build_system=autotools zip=pigz arch=linux-rhel8-zen2
onyctuz                      ^pigz@2.7%gcc@9.4.0 build_system=makefile arch=linux-rhel8-zen2
h5xayww                  ^xz@5.2.5%gcc@9.4.0+pic build_system=autotools libs=shared,static arch=linux-rhel8-zen2
pn5aecy              ^help2man@1.49.3%gcc@9.4.0 build_system=autotools arch=linux-rhel8-zen2
ayj63w3              ^libtool@2.4.7%gcc@9.4.0 build_system=autotools arch=linux-rhel8-zen2
aiqnqx7          ^libjpeg-turbo@2.1.5%gcc@9.4.0~ipo~jpeg8+shared+static build_system=cmake build_type=Release generator=make arch=linux-rhel8-zen2
x7qii7o              ^cmake@3.21.4%gcc@9.4.0~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-rhel8-zen2
gwmvljt                  ^openssl@1.1.1o%gcc@9.4.0~docs+shared build_system=generic certs=system arch=linux-rhel8-zen2
vsyhz33              ^gmake@4.3%gcc@9.4.0+guile build_system=autotools patches=599f134 arch=linux-rhel8-zen2
4gunwlj                  ^guile@2.2.6%gcc@9.4.0+readline build_system=autotools threads=posix arch=linux-rhel8-zen2
c26pf64                      ^bdw-gc@8.0.6%gcc@9.4.0+libatomic-ops build_system=autotools threads=posix arch=linux-rhel8-zen2
lhefaa5                          ^libatomic-ops@7.6.12%gcc@9.4.0 build_system=autotools arch=linux-rhel8-zen2
rqjelsl                      ^gmp@6.2.1%gcc@9.4.0+cxx build_system=autotools libs=shared,static patches=69ad2e2 arch=linux-rhel8-zen2
kpsuuut                      ^libffi@3.4.2%gcc@9.4.0 build_system=autotools arch=linux-rhel8-zen2
rxkfgbd                  ^pkg-config@0.29.2%gcc@9.4.0+internal_glib build_system=autotools arch=linux-rhel8-zen2
53zda3b              ^nasm@2.15.05%gcc@9.4.0 build_system=autotools arch=linux-rhel8-zen2
iy5ro4n          ^libszip@2.1.1%gcc@9.4.0 build_system=autotools arch=linux-rhel8-zen2
lzjcice          ^libtirpc@1.2.6%gcc@9.4.0 build_system=autotools arch=linux-rhel8-zen2
3cvjjtq              ^krb5@1.19.2%gcc@9.4.0+shared build_system=autotools arch=linux-rhel8-zen2
jpm3doc          ^zlib@1.2.13%gcc@9.4.0+optimize+pic+shared build_system=makefile arch=linux-rhel8-zen2.
</pre></details>

### Error message

<details><summary>Error message</summary>

<pre>
==> Installing hdf-eos2-2.20v1.00-36txpvlzapnavh7dzzfr53hqrbfweodo
==> No binary for hdf-eos2-2.20v1.00-36txpvlzapnavh7dzzfr53hqrbfweodo found: installing from source
File src/Makefile.am is read-only; trying to patch anyway
File src/Makefile.in is read-only; trying to patch anyway
==> Fetching https://mirror.spack.io/_source-cache/archive/cb/cb0f900d2732ab01e51284d6c9e90d0e852d61bba9bce3b43af0430ab5414903.tar.Z
==> Applied patch /software/spack/git.2023.05.30/var/spack/repos/builtin/packages/hdf-eos2/hdf-eos2.nondarwin-no-single_module.patch
==> hdf-eos2: Executing phase: 'autoreconf'
==> hdf-eos2: Executing phase: 'configure'
==> Error: PermissionError: [Errno 13] Permission denied: '/tmp/devspackswinst/spack-stage/spack-stage-hdf-eos2-2.20v1.00-36txpvlzapnavh7dzzfr53hqrbfweodo/spack-src/configure'

/software/spack/git.2023.05.30/lib/spack/spack/build_systems/autotools.py:359, in _do_patch_libtool_configure:
        356                regex=r'^(\s*test x-R = )("\$p")(; then\s*)$', repl=r'\1x\2 || test x-l = x"$p"\3'
        357            )
        358            # Support Libtool 2.4.2 and older:
  >>    359            x.filter(regex=r'^(\s*test \$p = "-R")(; then\s*)$', repl=r'\1 || test x-l = x"$p"\2')

See build log for details:
  /tmp/devspackswinst/spack-stage/spack-stage-hdf-eos2-2.20v1.00-36txpvlzapnavh7dzzfr53hqrbfweodo/spack-build-out.txt
</pre></details>

### Information on your system

```console
$ spack debug report
* **Spack:** 0.21.0.dev0 (84faf5a6cf342efddb976b7432e44aff12f1c985)
* **Python:** 3.6.8
* **Platform:** linux-rhel8-zen2
* **Concretizer:** clingo
```

### Additional information

[spack-build-out.txt](https://github.com/spack/spack/files/11837774/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/11837775/spack-build-env.txt)
[spack-build-02-configure-out.txt](https://github.com/spack/spack/files/11837776/spack-build-02-configure-out.txt)
[spack-build-01-autoreconf-out.txt](https://github.com/spack/spack/files/11837777/spack-build-01-autoreconf-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by climbfuji** [comment]
@payerle Is this still an issue? I don't see any problem with changing the permissions of the `configure` script for this package.

**Comment by payerle** [comment]
I have not had the opportunity to try it recently (and I am using a patched version of the hdf-eos2 recipe which forces write permission of the configure script, so even when opening the ticket a year or so ago the matter was "resolved" for me --- I was merely looking to avoid others running into this issue).

I did, however, just do a spack stage of hdf-eos2 for @3.0 and @2.20v1.00
I noticed that after spack stage, the .../spack-src/configure script for @3.0 has perms 755 (e.g. has u+w), but the one for @2.20v1.00 is only 555 (i.e. no write perms for anyone).

This would lead me to believe that the issue still exists for @2.20v1.00 but was fixed by the package maintainer for @3.0.

The more general question I have is whether autotools.py (or something elsewhere above the package recipe) should be patched to ensure that if they plan to patch configure or other scripts that these are writable.  While I concede it is bad form for a package to ship with a non-writable configure script, it also seems questionable on spack's part to assume that any file it decides to patch should be writable.

**Comment by climbfuji** [comment]
I saw you fixed this in the package a few months ago. I feel like we should close this issue as completed, since it is specific to hdf-eos2. If you think a broader discussion the autotools build system is warranted, should that be a separate issue/discussion?

**Comment by payerle** [comment]
Fine by me.  If I notice another package with this issue, I will raise up for a broader consideration.
