### ISSUE TITLE
vtk-m@1.9.0 +cuda cuda_arch=90 fails build: CMake/VTKmDeviceAdapters.cmake:216 (message): Error detecting architecture flags for CUDA.  Please set VTKm_CUDA_Architecture manually.

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#38560]
### Steps to reproduce the issue

`vtk-m@1.9.0 +cuda cuda_arch=90` fails to build using:
* spack@develop (5c6c3b403bc4a8cd08b4e9303748933f3f79f5f7 from `Sun Jun 18 07:17:19 2023 -0400`)
* GCC 11.1.0
* CUDA 11.8.0
* Ubuntu 20.04, X86_64

Concrete spec: [vtk-m.spec.json.txt](https://github.com/spack/spack/files/11871666/vtk-m.spec.json.txt)

<details><summary>Concretization</summary>
<pre>
 -   vtk-m@1.9.0%gcc@11.1.0~64bitids+ascent_types+cuda+cuda_native+doubleprecision+examples+fpic~ipo~kokkos~logging+mpi+openmp+rendering~rocm+shared~tbb~testlib~virtuals build_system=cmake build_type=Release cuda_arch=90 generator=make arch=linux-ubuntu20.04-x86_64
[+]      ^cmake@3.26.3%gcc@11.1.0~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-ubuntu20.04-x86_64
[+]          ^ncurses@6.3%gcc@11.1.0~symlinks+termlib abi=none build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^openssl@1.1.1u%gcc@11.1.0~docs~shared build_system=generic certs=mozilla arch=linux-ubuntu20.04-x86_64
[+]              ^ca-certificates-mozilla@2023-01-10%gcc@11.1.0 build_system=generic arch=linux-ubuntu20.04-x86_64
[+]              ^perl@5.36.0%gcc@11.1.0+cpanm+open+shared+threads build_system=generic arch=linux-ubuntu20.04-x86_64
[+]                  ^berkeley-db@18.1.40%gcc@11.1.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu20.04-x86_64
[+]                  ^bzip2@1.0.8%gcc@11.1.0~debug~pic+shared build_system=generic arch=linux-ubuntu20.04-x86_64
[+]                  ^gdbm@1.23%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^zlib@1.2.13%gcc@11.1.0+optimize+pic+shared build_system=makefile arch=linux-ubuntu20.04-x86_64
[+]      ^cuda@11.8.0%gcc@11.1.0~allow-unsupported-compilers~dev build_system=generic arch=linux-ubuntu20.04-x86_64
[+]          ^libxml2@2.10.3%gcc@11.1.0~python build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^libiconv@1.17%gcc@11.1.0 build_system=autotools libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]              ^xz@5.4.1%gcc@11.1.0+pic build_system=autotools libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]      ^gmake@4.4.1%gcc@11.1.0~guile build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]      ^mpich@4.1.1%gcc@11.1.0~argobots~cuda+fortran~hwloc+hydra+libxml2+pci~rocm+romio~slurm~two_level_namespace~vci~verbs~wrapperrpath build_system=autotools datatype-engine=auto device=ch4 netmod=ofi pmi=pmi arch=linux-ubuntu20.04-x86_64
[+]          ^findutils@4.9.0%gcc@11.1.0 build_system=autotools patches=440b954 arch=linux-ubuntu20.04-x86_64
[+]          ^libfabric@1.18.0%gcc@11.1.0~debug~kdreg build_system=autotools fabrics=rxm,sockets,tcp,udp arch=linux-ubuntu20.04-x86_64
[+]          ^libpciaccess@0.17%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^libtool@2.4.7%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^util-macros@1.19.3%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^pkgconf@1.9.5%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^yaksa@0.2%gcc@11.1.0~cuda~rocm build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^autoconf@2.69%gcc@11.1.0 build_system=autotools patches=35c4492,7793209,a49dd5b arch=linux-ubuntu20.04-x86_64
[+]              ^automake@1.16.5%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^m4@1.4.19%gcc@11.1.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-ubuntu20.04-x86_64
[+]                  ^diffutils@3.9%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                  ^libsigsegv@2.14%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^python@3.7.15%gcc@11.1.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=0d98e93,f2fd060 arch=linux-ubuntu20.04-x86_64
[+]                  ^expat@2.5.0%gcc@11.1.0+libbsd build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                      ^libbsd@0.11.7%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                          ^libmd@1.0.4%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                  ^gettext@0.21.1%gcc@11.1.0+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                      ^tar@1.34%gcc@11.1.0 build_system=autotools zip=pigz arch=linux-ubuntu20.04-x86_64
[+]                          ^pigz@2.7%gcc@11.1.0 build_system=makefile arch=linux-ubuntu20.04-x86_64
[+]                          ^zstd@1.5.5%gcc@11.1.0+programs build_system=makefile compression=none libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]                  ^libffi@3.4.4%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                  ^libxcrypt@4.4.33%gcc@11.1.0~obsolete_api build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                  ^readline@8.2%gcc@11.1.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu20.04-x86_64
[+]                  ^sqlite@3.42.0%gcc@11.1.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                  ^util-linux-uuid@2.38.1%gcc@11.1.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
</pre>
</details>

Error:
```
$> spack install -f ./vtk-m.spec.json 
...
==> Installing vtk-m-1.9.0-okorbigkpgcosp6tambnnx5lamtd4n7e
==> No binary for vtk-m-1.9.0-okorbigkpgcosp6tambnnx5lamtd4n7e found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/12/12355dea1a24ec32767260068037adeb71abb3df2f9f920c92ce483f35ff46e4.tar.gz
==> No patches needed for vtk-m
==> vtk-m: Executing phase: 'cmake'
==> Error: ProcessError: Command exited with status 1:
    '/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/cmake-3.26.3-fok342qbpnpiznqxyzdvd4glkq22kvhu/bin/cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/vtk-m-1.9.0-okorbigkpgcosp6tambnnx5lamtd4n7e' '-DCMAKE_BUILD_TYPE:STRING=Release' '-DBUILD_TESTING:BOOL=OFF' '-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=OFF' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON' '-DCMAKE_INSTALL_RPATH:STRING=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/vtk-m-1.9.0-okorbigkpgcosp6tambnnx5lamtd4n7e/lib;/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/vtk-m-1.9.0-okorbigkpgcosp6tambnnx5lamtd4n7e/lib64;/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/libxml2-2.10.3-mxocfz7rp5lgy2yzsfqn7gf2yrrevzf7/lib;/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/libiconv-1.17-5f66p4aoivmlxa7htmpsffk5ov62vgci/lib;/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/xz-5.4.1-tppbn4xhprhizecunvu5egyztf7kmicv/lib;/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/zlib-1.2.13-hi2xsgcpyaect4ojyrhzeqj56vg7ldvj/lib;/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/mpich-4.1.1-pe7z6kruawbnt72svqy2bnsf2eurqc7j/lib;/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/libfabric-1.18.0-iv5kj6s4dciyn5f32scy3e24zxxjgzv3/lib;/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/libpciaccess-0.17-j5kbtglykqfohsexjzn5xgtkw27tf3kj/lib;/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/yaksa-0.2-o2bqqi7oirz77kdi65mm6gcvhqjpypru/lib;/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/cuda-11.8.0-e5qmi3ynerocnxupx3epemw25cezxkoo/lib64' '-DCMAKE_PREFIX_PATH:STRING=/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/mpich-4.1.1-pe7z6kruawbnt72svqy2bnsf2eurqc7j;/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/yaksa-0.2-o2bqqi7oirz77kdi65mm6gcvhqjpypru;/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/libpciaccess-0.17-j5kbtglykqfohsexjzn5xgtkw27tf3kj;/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/libfabric-1.18.0-iv5kj6s4dciyn5f32scy3e24zxxjgzv3;/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/gmake-4.4.1-lp2ol6q2quzz7sjtfkrxeczlsvzukkzk;/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/cuda-11.8.0-e5qmi3ynerocnxupx3epemw25cezxkoo;/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/cuda-11.8.0-e5qmi3ynerocnxupx3epemw25cezxkoo/targets/x86_64-linux/lib/cmake;/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/libxml2-2.10.3-mxocfz7rp5lgy2yzsfqn7gf2yrrevzf7;/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/xz-5.4.1-tppbn4xhprhizecunvu5egyztf7kmicv;/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/cmake-3.26.3-fok342qbpnpiznqxyzdvd4glkq22kvhu;/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/zlib-1.2.13-hi2xsgcpyaect4ojyrhzeqj56vg7ldvj;/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/libiconv-1.17-5f66p4aoivmlxa7htmpsffk5ov62vgci' '-DVTKm_ENABLE_TESTING:BOOL=OFF' '-DBUILD_SHARED_LIBS=ON' '-DVTKm_USE_DOUBLE_PRECISION:BOOL=ON' '-DVTKm_ENABLE_LOGGING:BOOL=OFF' '-DVTKm_ENABLE_MPI:BOOL=ON' '-DVTKm_ENABLE_RENDERING:BOOL=ON' '-DVTKm_USE_DEFAULT_TYPES_FOR_ASCENT:BOOL=ON' '-DVTKm_NO_DEPRECATED_VIRTUAL:BOOL=ON' '-DVTKm_USE_64BIT_IDS:BOOL=OFF' '-DVTKm_ENABLE_CUDA:BOOL=ON' '-DCMAKE_CUDA_HOST_COMPILER=/usr/bin/g++' '-DVTKm_ENABLE_OPENMP:BOOL=ON' '-DVTKm_ENABLE_KOKKOS:BOOL=OFF' '-DVTKm_ENABLE_TBB:BOOL=OFF' '-DVTKm_INSTALL_EXAMPLES:BOOL=ON' '/tmp/root/spack-stage/spack-stage-vtk-m-1.9.0-okorbigkpgcosp6tambnnx5lamtd4n7e/spack-src'

1 error found in build log:
     17    -- The CUDA compiler identification is NVIDIA 11.8.89
     18    -- Detecting CUDA compiler ABI info
     19    -- Detecting CUDA compiler ABI info - done
     20    -- Check for working CUDA compiler: /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.1.0/cuda-11.8.0-e5qmi3ynerocnxupx3epemw25cezxkoo/bin/nvcc - skipped
     21    -- Detecting CUDA compile features
     22    -- Detecting CUDA compile features - done
  >> 23    CMake Error at CMake/VTKmDeviceAdapters.cmake:216 (message):
     24      Error detecting architecture flags for CUDA.  Please set
     25      VTKm_CUDA_Architecture manually.
     26    Call Stack (most recent call first):
     27      CMake/VTKmWrappers.cmake:14 (include)
     28      CMakeLists.txt:201 (include)
     29
```

### Error message

<details><summary>Error message</summary>
<pre>
... see above
</pre></details>

### Information on your system

* **Spack:** 0.21.0.dev0 (10fd13d9ba7d7ec301e62b95f0eca862aafadc91)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/11871678/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/11871679/spack-build-out.txt)

@kmorel @vicentebolea @kwryankrattiger @nchaimov @wspear

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by vicentebolea** [comment]
@eugeneswalker, I think I can see whats the problem, I will correct this for 1.9. In the meanwhile, you can use our latest release 2.0.0

**Comment by eugeneswalker** [comment]
> @eugeneswalker, I think I can see whats the problem, I will correct this for 1.9. In the meanwhile, you can use our latest release 2.0.0

Thanks for taking a look! If you do a patch for 1.9, ping me on the PR and I can expedite approval. Thanks!
