### ISSUE TITLE
bricks@r0.1 build fails on PPC64 and ARM64: VSBrick-7pt.py-Scalar-8x8x8-1:30:3: error: 'vfloat512' was not declared in this scope

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#38785]
### Steps to reproduce the issue

`bricks@r0.1` build fails using:
* `spack@develop` (2dc76248d3154c500fa16edfbc47801d122c7859 from `Fri Jul 7 23:27:32 2023 +0200`)
* GCC 9.4.0
* Ubuntu 20.04, PPC64LE

Also fails using GCC 11 on Ubuntu 20.04 for ARM.

Spack environment: [spack.yaml.txt](https://github.com/spack/spack/files/11986869/spack.yaml.txt)

<details><summary>Concretization</summary>
<pre>
==> Concretized bricks
 -   c24fno5  bricks@r0.1%gcc@9.4.0~cuda~ipo build_system=cmake build_type=Release generator=make patches=7fe8d1d arch=linux-ubuntu20.04-ppc64le
 -   a2a5pfo      ^autoconf@2.69%gcc@9.4.0 build_system=autotools patches=35c4492,7793209,a49dd5b arch=linux-ubuntu20.04-ppc64le
 -   o6oyhz6          ^gnuconfig@2022-09-17%gcc@9.4.0 build_system=generic arch=linux-ubuntu20.04-ppc64le
 -   s5kenrv          ^m4@1.4.19%gcc@9.4.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-ubuntu20.04-ppc64le
 -   jps7iqw              ^diffutils@3.9%gcc@9.4.0 build_system=autotools arch=linux-ubuntu20.04-ppc64le
 -   ztrsaey              ^libsigsegv@2.14%gcc@9.4.0 build_system=autotools arch=linux-ubuntu20.04-ppc64le
 -   x3w7ay3          ^perl@5.38.0%gcc@9.4.0+cpanm+open+shared+threads build_system=generic arch=linux-ubuntu20.04-ppc64le
 -   y5gw6tf              ^berkeley-db@18.1.40%gcc@9.4.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu20.04-ppc64le
 -   ukj6crw              ^bzip2@1.0.8%gcc@9.4.0~debug~pic+shared build_system=generic arch=linux-ubuntu20.04-ppc64le
 -   vmzdi6a              ^gdbm@1.23%gcc@9.4.0 build_system=autotools arch=linux-ubuntu20.04-ppc64le
 -   ixntir5                  ^readline@8.2%gcc@9.4.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu20.04-ppc64le
 -   623xzqa              ^zlib@1.2.13%gcc@9.4.0+optimize+pic+shared build_system=makefile arch=linux-ubuntu20.04-ppc64le
 -   r4hqrrs      ^automake@1.16.5%gcc@9.4.0 build_system=autotools arch=linux-ubuntu20.04-ppc64le
 -   7dmb7ox      ^cmake@3.26.3%gcc@9.4.0~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-ubuntu20.04-ppc64le
 -   ygt3dxq          ^ncurses@6.3%gcc@9.4.0~symlinks+termlib abi=none build_system=autotools arch=linux-ubuntu20.04-ppc64le
 -   6jh2fnr          ^openssl@1.1.1u%gcc@9.4.0~docs~shared build_system=generic certs=mozilla arch=linux-ubuntu20.04-ppc64le
 -   fp7mfbd              ^ca-certificates-mozilla@2023-01-10%gcc@9.4.0 build_system=generic arch=linux-ubuntu20.04-ppc64le
 -   lymdy5l      ^gmake@4.4.1%gcc@9.4.0~guile build_system=autotools arch=linux-ubuntu20.04-ppc64le
 -   gqxhnrc      ^libtool@2.4.7%gcc@9.4.0 build_system=autotools arch=linux-ubuntu20.04-ppc64le
 -   6lh4vab      ^mpich@4.1.1%gcc@9.4.0~argobots~cuda+fortran~hwloc+hydra+libxml2+pci~rocm+romio~slurm~two_level_namespace~vci~verbs~wrapperrpath build_system=autotools datatype-engine=dataloop device=ch4 netmod=ofi pmi=pmi arch=linux-ubuntu20.04-ppc64le
 -   yl5nu23          ^findutils@4.9.0%gcc@9.4.0 build_system=autotools patches=440b954 arch=linux-ubuntu20.04-ppc64le
 -   wbsqauo          ^libfabric@1.18.1%gcc@9.4.0~debug~kdreg build_system=autotools fabrics=rxm,sockets,tcp,udp arch=linux-ubuntu20.04-ppc64le
 -   wprcmut          ^libpciaccess@0.17%gcc@9.4.0 build_system=autotools arch=linux-ubuntu20.04-ppc64le
 -   q4vvvu2              ^util-macros@1.19.3%gcc@9.4.0 build_system=autotools arch=linux-ubuntu20.04-ppc64le
 -   qtz3bua          ^libxml2@2.10.3%gcc@9.4.0~python build_system=autotools arch=linux-ubuntu20.04-ppc64le
 -   fm2fw25              ^libiconv@1.17%gcc@9.4.0 build_system=autotools libs=shared,static arch=linux-ubuntu20.04-ppc64le
 -   6grnzf2              ^xz@5.4.1%gcc@9.4.0+pic build_system=autotools libs=shared,static arch=linux-ubuntu20.04-ppc64le
 -   7c7ye6x          ^pkgconf@1.9.5%gcc@9.4.0 build_system=autotools arch=linux-ubuntu20.04-ppc64le
</pre></details>

Error:
```
$> spack -e . install
...
==> Installing bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao
==> No binary for bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao found: installing from source
==> Applied patch /spack/var/spack/repos/builtin/packages/bricks/bricks-cmakelists-option-opencl.patch
==> bricks: Executing phase: 'cmake'
==> bricks: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    '/spack/opt/spack/linux-ubuntu20.04-ppc64le/gcc-9.4.0/gmake-4.4.1-lymdy5lc4fq67uf3kfdabzr7vcz6mbua/bin/make'

458 errors found in build log:
     193    [ 70%] Building CXX object strong/CMakeFiles/strong-cpu.dir/main-out.cpp.o
     194    cd /tmp/root/spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-build-c24fno5/strong && /spack/lib/spack/env/gcc/g++  -I/tmp/root/spack-stage
            /spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-src/include -I/tmp/root/spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-sr
            c -I/spack/opt/spack/linux-ubuntu20.04-ppc64le/gcc-9.4.0/mpich-4.1.1-6lh4vabqlu7bzeennkys2zo7u6hsdify/include -fopenmp -O2 -DNDEBUG -std=c++14 -mcpu=native -MD -MT s
            trong/CMakeFiles/strong-cpu.dir/main-out.cpp.o -MF CMakeFiles/strong-cpu.dir/main-out.cpp.o.d -o CMakeFiles/strong-cpu.dir/main-out.cpp.o -c /tmp/root/spack-stage/sp
            ack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-src/strong/main-out.cpp
     195    [ 74%] Building CXX object strong/CMakeFiles/strong-cpu.dir/args.cpp.o
     196    cd /tmp/root/spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-build-c24fno5/strong && /spack/lib/spack/env/gcc/g++  -I/tmp/root/spack-stage
            /spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-src/include -I/tmp/root/spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-sr
            c -I/spack/opt/spack/linux-ubuntu20.04-ppc64le/gcc-9.4.0/mpich-4.1.1-6lh4vabqlu7bzeennkys2zo7u6hsdify/include -fopenmp -O2 -DNDEBUG -std=c++14 -mcpu=native -MD -MT s
            trong/CMakeFiles/strong-cpu.dir/args.cpp.o -MF CMakeFiles/strong-cpu.dir/args.cpp.o.d -o CMakeFiles/strong-cpu.dir/args.cpp.o -c /tmp/root/spack-stage/spack-stage-br
            icks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-src/strong/args.cpp
     197    In file included from /tmp/root/spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-src/stencils/3axis.cpp:74:
     198    VSBrick-7pt.py-Scalar-8x8x8-1: In lambda function:
  >> 199    VSBrick-7pt.py-Scalar-8x8x8-1:30:3: error: 'vfloat512' was not declared in this scope
  >> 200    VSBrick-7pt.py-Scalar-8x8x8-1:50:21: error: 'buf0' was not declared in this scope
  >> 201    VSBrick-7pt.py-Scalar-8x8x8-1:81:17: error: 'buf0' was not declared in this scope
  >> 202    VSBrick-7pt.py-Scalar-8x8x8-1:101:13: error: 'buf0' was not declared in this scope
...
  >> 679    make[3]: *** [weak/CMakeFiles/weak-cpu.dir/build.make:83: weak/CMakeFiles/weak-cpu.dir/main-out.cpp.o] Error 1
     680    make[3]: Target 'weak/CMakeFiles/weak-cpu.dir/build' not remade because of errors.
     681    make[3]: Leaving directory '/tmp/root/spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-build-c24fno5'
  >> 682    make[2]: *** [CMakeFiles/Makefile2:299: weak/CMakeFiles/weak-cpu.dir/all] Error 2
  >> 683    make[3]: *** [strong/CMakeFiles/strong-cpu.dir/build.make:83: strong/CMakeFiles/strong-cpu.dir/main-out.cpp.o] Error 1
     684    make[3]: Target 'strong/CMakeFiles/strong-cpu.dir/build' not remade because of errors.
     685    make[3]: Leaving directory '/tmp/root/spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-build-c24fno5'
  >> 686    make[2]: *** [CMakeFiles/Makefile2:411: strong/CMakeFiles/strong-cpu.dir/all] Error 2
  >> 687    make[3]: *** [weak/CMakeFiles/weak-cpu-4d.dir/build.make:83: weak/CMakeFiles/weak-cpu-4d.dir/main-4d-out.cpp.o] Error 1
     688    make[3]: Target 'weak/CMakeFiles/weak-cpu-4d.dir/build' not remade because of errors.
     689    make[3]: Leaving directory '/tmp/root/spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-build-c24fno5'
  >> 690    make[2]: *** [CMakeFiles/Makefile2:327: weak/CMakeFiles/weak-cpu-4d.dir/all] Error 2
     691    [ 83%] Linking CXX executable mpi
     692    cd /tmp/root/spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-build-c24fno5/single && /spack/opt/spack/linux-ubuntu20.04-ppc64le/gcc-9.4.0/
            cmake-3.26.3-7dmb7ox6cmafmqzst3fdnhsayvvv7f3w/bin/cmake -E cmake_link_script CMakeFiles/single-mpi.dir/link.txt --verbose=1
     693    /spack/lib/spack/env/gcc/g++  -fopenmp -O2 -DNDEBUG "CMakeFiles/single-mpi.dir/mpi.cpp.o" "CMakeFiles/single-mpi.dir/__/src/brick-mpi.cpp.o" -o mpi  -Wl,-rpath,/spac
            k/opt/spack/linux-ubuntu20.04-ppc64le/gcc-9.4.0/mpich-4.1.1-6lh4vabqlu7bzeennkys2zo7u6hsdify/lib ../src/libbrick.a ../src/libbrickhelper.a /spack/opt/spack/linux-ubu
            ntu20.04-ppc64le/gcc-9.4.0/mpich-4.1.1-6lh4vabqlu7bzeennkys2zo7u6hsdify/lib/libmpicxx.so /spack/opt/spack/linux-ubuntu20.04-ppc64le/gcc-9.4.0/mpich-4.1.1-6lh4vabqlu7
            bzeennkys2zo7u6hsdify/lib/libmpi.so
     694    make[3]: Leaving directory '/tmp/root/spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-build-c24fno5'
     695    [ 83%] Built target single-mpi
     696    make[2]: Target 'all' not remade because of errors.
     697    make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-build-c24fno5'
  >> 698    make[1]: *** [Makefile:139: all] Error 2
     699    make[1]: Target 'default_target' not remade because of errors.
     700    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-build-c24fno5'
```

### Error message

<details><summary>Error message</summary>

<pre>
... see above
</pre></details>

### Information on your system

* **Spack:** 0.21.0.dev0 (2dc76248d3154c500fa16edfbc47801d122c7859)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-power9le
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/11986884/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/11986885/spack-build-out.txt)

@drhansj @ztuowen @wspear

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by ztuowen** [comment]
There appears to be a bug in the scalar backend, as noted in the error `VSBrick-7pt.py-Scalar-8x8x8-1`. 

A [PR](https://github.com/CtopCsUtahEdu/bricklib/commit/eebaecc269e67b3abf90481fb86ef50dba8ab79d) is merged in the bricklib repo to fix this issue. Can you try it again?

**Comment by eugeneswalker** [comment]
> A [PR](https://github.com/CtopCsUtahEdu/bricklib/commit/eebaecc269e67b3abf90481fb86ef50dba8ab79d) is merged in the bricklib repo to fix this issue. Can you try it again?

Just tried, new error:
```
==> Installing bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao
==> No binary for bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao found: installing from source
==> Applied patch /spack/var/spack/repos/builtin/packages/bricks/bricks-cmakelists-option-opencl.patch
==> bricks: Executing phase: 'cmake'
==> bricks: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    '/spack/opt/spack/linux-ubuntu20.04-ppc64le/gcc-9.4.0/gmake-4.4.1-lymdy5lc4fq67uf3kfdabzr7vcz6mbua/bin/make' '-j16'

5 errors found in build log:
     206    make[2]: Entering directory '/tmp/root/spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-build-c24fno5'
     207    [ 80%] Building CXX object weak/CMakeFiles/weak-cpu-4d.dir/main-4d-out.cpp.o
     208    [ 80%] Building CXX object weak/CMakeFiles/weak-cpu-4d.dir/args.cpp.o
     209    cd /tmp/root/spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-build-c24fno5/weak && /spack/lib/spack/env/gcc/g++  -I/tmp/root
            /spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-src/include -I/tmp/root/spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxer
            dk7kg3vwa6wst2gao/spack-src -I/spack/opt/spack/linux-ubuntu20.04-ppc64le/gcc-9.4.0/mpich-4.1.1-6lh4vabqlu7bzeennkys2zo7u6hsdify/include -fopenmp -O2 -D
            NDEBUG -std=c++14 -mcpu=native -MD -MT weak/CMakeFiles/weak-cpu-4d.dir/main-4d-out.cpp.o -MF CMakeFiles/weak-cpu-4d.dir/main-4d-out.cpp.o.d -o CMakeFil
            es/weak-cpu-4d.dir/main-4d-out.cpp.o -c /tmp/root/spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-src/weak/main-4d-out.cpp
     210    cd /tmp/root/spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-build-c24fno5/weak && /spack/lib/spack/env/gcc/g++  -I/tmp/root
            /spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-src/include -I/tmp/root/spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxer
            dk7kg3vwa6wst2gao/spack-src -I/spack/opt/spack/linux-ubuntu20.04-ppc64le/gcc-9.4.0/mpich-4.1.1-6lh4vabqlu7bzeennkys2zo7u6hsdify/include -fopenmp -O2 -D
            NDEBUG -std=c++14 -mcpu=native -MD -MT weak/CMakeFiles/weak-cpu-4d.dir/args.cpp.o -MF CMakeFiles/weak-cpu-4d.dir/args.cpp.o.d -o CMakeFiles/weak-cpu-4d
            .dir/args.cpp.o -c /tmp/root/spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-src/weak/args.cpp
     211    /tmp/root/spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-src/strong/main.cpp: In function 'int main(int, char**)':
  >> 212    /tmp/root/spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-src/strong/main.cpp:208:23: error: 'munmap' was not declared in th
            is scope
     213      208 |             int ret = munmap(st, len);
     214          |                       ^~~~~~
  >> 215    /tmp/root/spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-src/strong/main.cpp:223:23: error: 'munmap' was not declared in th
            is scope
     216      223 |             int ret = munmap(s.storage[0]->dat.get() + spos, len);
     217          |                       ^~~~~~
  >> 218    make[2]: *** [strong/CMakeFiles/strong-cpu.dir/build.make:83: strong/CMakeFiles/strong-cpu.dir/main-out.cpp.o] Error 1
     219    make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao/spack-build-c24fno5'
  >> 220    make[1]: *** [CMakeFiles/Makefile2:411: strong/CMakeFiles/strong-cpu.dir/all] Error 2
     221    make[1]: *** Waiting for unfinished jobs....
```

What do you think?

**Comment by ztuowen** [comment]
Oops, the includes cleanup affected these source files.
[These](https://github.com/CtopCsUtahEdu/bricklib/compare/eebaecc269e67b3abf90481fb86ef50dba8ab79d..d81725055c117c4b63a1b3835c6b634768b5bea7) merged changes should fix it.

**Comment by eugeneswalker** [comment]
> Oops, the includes cleanup affected these source files. [These](https://github.com/CtopCsUtahEdu/bricklib/compare/eebaecc269e67b3abf90481fb86ef50dba8ab79d..d81725055c117c4b63a1b3835c6b634768b5bea7) merged changes should fix it.

That did it! Thanks!

```
==> Installing bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao
==> No binary for bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao found: installing from source
==> Applied patch /spack/var/spack/repos/builtin/packages/bricks/bricks-cmakelists-option-opencl.patch
==> bricks: Executing phase: 'cmake'
==> bricks: Executing phase: 'build'
==> bricks: Executing phase: 'install'
==> bricks: Successfully installed bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao
  Stage: 0.70s.  Cmake: 2.20s.  Build: 6.36s.  Install: 0.07s.  Post-install: 0.04s.  Total: 9.50s
[+] /spack/opt/spack/linux-ubuntu20.04-ppc64le/gcc-9.4.0/bricks-r0.1-c24fno57brnaxerdk7kg3vwa6wst2gao
```
