### ISSUE TITLE
Tests invoking executable.call are fragile

### ISSUE THREAD

**Issue by scheibelp** [LLNL/spack#388]
As of now any unit test which uses Executable.call without return_output=True will cause a failure in the test framework. As it happens every unit test does this but I can imagine someone writing one and not setting return_output (default is false).

Some nose plugins assign stdout to a stream object that does not have a .fileno attribute. This is required by subprocess.Popen (in executable.call). executable.call uses a pipe if return_output is true.

Possible fix: detect whether stdout has a .fileno attribute and always use a pipe if so.

**Comment by mathstuf** [comment]
Can the test suite just mask the `Executable` class with one which sets `return_output=True`?

**Comment by scheibelp** [comment]
Possibly - as I revisit this I feel I need to revise the issue:

I'm also concerned about indirect executions of Executable.call (i.e. via fetch_strategy) but this must have happened when I opened the issue and isn't causing a problem. So I need to recall why this is a problem. Also: it appears executable.py has been modified since I opened this issue and I also need to determine whether that has resolved anything.

I likely won't get a chance to update this until late next week.

**Comment by scheibelp** [comment]
A significant change is that executable.__call__ no longer assigns sys.stdout as the output by default. Now a unit test must explicitly specify sys.stdout as the output for a failure to occur. I'm not sure if supporting that is a worthwhile use case. Therefore I would no longer characterize such tests as fragile.

That being said a user may be confused that the restriction exists and enforcing it may therefore be worthwhile. It's definitely low-priority for me since I don't imagine someone running into it.

**Comment by alalazo** [comment]
> Some nose plugins assign stdout to a stream object that does not have a .fileno attribute. This is required by subprocess.Popen (in executable.call). executable.call uses a pipe if return_output is true.

@scheibelp Is this issue still relevant now that we passed to `pytest`?

**Comment by scheibelp** [comment]
This no longer appears to be an issue: I can invoke subprocess.Popen while using the capsys fixture (and sys.stdout.fileno is available)
