### ISSUE TITLE
suite-sparse fails to compile with clang

### ISSUE THREAD

**Issue by futuretristan** [LLNL/spack#3880]
I'm on Linuxmint 18.1 having clang 3.8.0 installed via apt-get and work with the current development version of Spack. 

While the build of suite-sparse works well with gcc, it fails when build with clang via `spack install suite-sparse%clang`. This holds for all listed versions of suite-sparse (4.5.1, 4.5.3, 4.5.4) and also the current one (4.5.5). The error is always the same: 

At a certain point in the build process (linking of libcholmod.so), clang is invoked with the `-fopenmp` flag, leading to the message `/usr/bin/ld: cannot find -lomp` and aborting the build process.

**Comment by davydden** [comment]
`-fopenmp` is a valid flag for Clang. This should certainly be reported upstream http://faculty.cse.tamu.edu/davis/suitesparse.html . Spack does not set `openmp` explicitly anywhere, see https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/suite-sparse/package.py

**Comment by davydden** [comment]
could also be that `clang` is broken in your linux mint...

**Comment by futuretristan** [comment]
Thanks for the hint with the broken compiler installation. I found out that on Debian based systems newer versions of clang (3.7+) only work with OpenMP (the -fopenmp flag) if the package libomp-dev is installed. See https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=811283

After installing the libomp-dev package, `spack install suite-sparse%clang` works well.

**Comment by davydden** [comment]
nice to hear that this is resolved!
