### ISSUE TITLE
CDash reporter start and end time are incorrect.

### ISSUE THREAD

**Issue by vbrunini** [LLNL/spack#38818]
### Steps to reproduce

```console
rm -rf spack-cdash-repro
mkdir spack-cdash-repro
cd spack-cdash-repro
spack env create -d .
spack env activate -d .
spack config add config:install_tree:root:"./install"
date +%s
spack install --add --log-file cdash-results --log-format cdash --cdash-build "Test" --cdash-site "Test" --cdash-track "Experimental" zlib
date +%s
```

### Error message

Open `spack-cdash-repro/cdash-results/Update.xml` and observe that the `StartTime` is earlier than result of the first `date +%s` command run by the reproducer script (dependent on how long the zlib install takes on your machine. This will be a bit more reliable with a slower to build/install package).

Looking in `lib/spack/spack/reporters/cdash.py` it appears that `CDash` stores `self.endtime = int(time.time())`  when the reporter is created, and then backs out a start time by subtracting off the duration of the installation process for all specs. However it appears the CDash reporter object is created before any specs are built and installed which leads to the wrong `StartTime` in Update.xml.

### Information on your system

* **Spack:** 0.21.0.dev0 (c3f4822f92e0afc70f3a642310c7e1282434d397)
* **Python:** 3.6.8
* **Platform:** linux-rhel7-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by tldahlgren** [comment]
That behavior may be a side-effect of some of resolving some stand-alone test issues.  Let me take a look.
