### ISSUE TITLE
Stable container tag for rolling `develop`

### ISSUE THREAD

**Issue by blue42u** [LLNL/spack#38816]
The `:latest` tag for the [official Spack container images](https://github.com/orgs/spack/packages?repo_name=spack) refers to the latest image pushed. Usually this is `develop`, but when a release is tagged this becomes the new release. This is problematic esp. for patch releases, which are on side branches and are usually missing many new features present in `develop`.

For users of Spack in automated settings (e.g. CI), we need a stable container tag that represents `develop` and will not be disturbed by releases.

**Comment by blue42u** [comment]
@alalazo 
> We can discuss that in the issue, but if this doesn't cause further problems to people having CI already setup we can just stick with `docker/metadata-action` defaults and call `develop` just `develop`

This is a reasonable idea, the main concern I have is that we have to re-educate people that `:latest` (note: the default tag) should not be used for many (if any) use cases. It's not a huge issue, but it seems weird to "punish" users for accidentally leaving off the `:develop` suffix.

I would ideally arrange it where `:latest` is the latest release and `:develop` is the rolling develop. But I don't know `docker/metadata-action` so :shrug:.

**Comment by tgamblin** [comment]
Let's do this for 0.21.  It needs to be added to:
* https://github.com/spack/spack/discussions/30634

but I don't think this is a huge breaking change.

**Comment by tgamblin** [comment]
To clarify: we should do this *on release* of `0.21` so that `:latest` doesn't move backward.

After `0.21`, `:develop` will refer to the `develop` branch and `:latest` will refer to the latest release (`v0.21`), to be updated on each subsequent release.

**Comment by alalazo** [comment]
@blue42u For what is worth, the scheduled build on the `develop` branch are tagged `:develop` or `:nightly` since 2 days ago.
