### ISSUE TITLE
bash $MODULEPATH not prepended by setup-env.sh

### ISSUE THREAD

**Issue by JusticeForMikeBrown** [LLNL/spack#3888]
Hi

I built spack 0.10.0 on centos 6.3 head node and installed several packages.  These packages work on our centos 6.8 compute nodes.  Though $MODULEPATH isn't prepended by env script so I have to load the modules manually.  That's very annoying.

Head Node That Works:

```
sysadmin@head[~]$ source /mount/stuff/apps/EL6/spack/share/spack/setup-env.sh

sysadmin@head[~]$ cat /etc/redhat-release 
Red Hat Enterprise Linux Server release 6.3 (Santiago)

sysadmin@head[~]$ spack find
==> 42 installed packages.
-- linux-rhel6-x86_64 / gcc@4.4.6 -------------------------------
autoconf@2.69   bedtools2@2.26.0  boost@1.63.0  curl@7.53.1  gcc@6.3.0         gmp@6.1.2        hwloc@1.11.6   libpciaccess@0.13.4  libxml2@2.9.4  mpc@1.0.3    openblas@0.2.19  pcre@8.40          samtools@1.4        xz@5.2.3
automake@1.15   binutils@2.28     bzip2@1.0.6   expat@2.2.0  gettext@0.19.8.1  help2man@1.47.4  isl@0.18       libsigsegv@2.11      m4@1.4.18      mpfr@3.1.5   openmpi@2.1.0    perl@5.24.1        tar@1.29            zip@3.0
bamtools@2.4.1  bison@3.0.4       cmake@3.7.2   flex@2.6.3   git@2.12.1        htslib@1.4       libiconv@1.15  libtool@2.4.6        mawk@1.3.4     ncurses@6.0  openssl@1.0.2k   pkg-config@0.29.2  util-macros@1.19.1  zlib@1.2.11

sysadmin@head[~]$ module avail

------------------------------------------------------------------------------ /mount/stuff/apps/EL6/spack/share/spack/modules/linux-rhel6-x86_64 -------------------------------------------------------------------------------
autoconf-2.69-gcc-4.4.6-iquqclp       bzip2-1.0.6-gcc-4.4.6-sou2qwr         git-2.12.1-gcc-4.4.6-74lirj6          libpciaccess-0.13.4-gcc-4.4.6-7tleclp mpfr-3.1.5-gcc-4.4.6-j7nsnrs          pkg-config-0.29.2-gcc-4.4.6-iydmn3z
automake-1.15-gcc-4.4.6-o7mbo4v       cmake-3.7.2-gcc-4.4.6-4ftp7ke         gmp-6.1.2-gcc-4.4.6-kj7nhml           libsigsegv-2.11-gcc-4.4.6-wxt4khc     ncurses-6.0-gcc-4.4.6-dooyyhq         samtools-1.4-gcc-4.4.6-lmqaw4t
bamtools-2.4.1-gcc-4.4.6-myiowro      curl-7.53.1-gcc-4.4.6-nyd6lf3         help2man-1.47.4-gcc-4.4.6-tbe2kki     libtool-2.4.6-gcc-4.4.6-234bdxl       openblas-0.2.19-gcc-4.4.6-62fsoge     tar-1.29-gcc-4.4.6-khtut33
bedtools2-2.26.0-gcc-4.4.6-efkupa7    expat-2.2.0-gcc-4.4.6-s4kzbv5         htslib-1.4-gcc-4.4.6-pideutw          libxml2-2.9.4-gcc-4.4.6-szkxoqt       openmpi-2.1.0-gcc-4.4.6-g6be566       util-macros-1.19.1-gcc-4.4.6-roiz7ew
binutils-2.28-gcc-4.4.6-a4bouod       flex-2.6.3-gcc-4.4.6-3lhywtv          hwloc-1.11.6-gcc-4.4.6-7oifsdj        m4-1.4.18-gcc-4.4.6-pop62iy           openssl-1.0.2k-gcc-4.4.6-g5whrka      xz-5.2.3-gcc-4.4.6-7ah2pyt
bison-3.0.4-gcc-4.4.6-xk27fhf         gcc-6.3.0-gcc-4.4.6-han2ovj           isl-0.18-gcc-4.4.6-ybcomk4            mawk-1.3.4-gcc-4.4.6-pv64smz          pcre-8.40-gcc-4.4.6-xust2yg           zip-3.0-gcc-4.4.6-376wzxy
boost-1.63.0-gcc-4.4.6-gpfsh3e        gettext-0.19.8.1-gcc-4.4.6-rytpqz2    libiconv-1.15-gcc-4.4.6-ep5mbfs       mpc-1.0.3-gcc-4.4.6-osp65qk           perl-5.24.1-gcc-4.4.6-a43rx7y         zlib-1.2.11-gcc-4.4.6-erzei6x

------------------------------------------------------------------------------------------------------- /usr/share/Modules/modulefiles -------------------------------------------------------------------------------------------------------
dot           module-cvs    module-info   modules       mpich2-x86_64 null          use.own


sysadmin@head[~]$ echo $MODULEPATH
/mount/stuff/apps/EL6/spack/share/spack/modules/linux-rhel6-x86_64:/usr/share/Modules/modulefiles:/etc/modulefiles
```

Node That Does Not Work:

```
sysadmin@node156[~]$ cat /etc/redhat-release
CentOS release 6.8 (Final)

sysadmin@node156[~]$ spack find
==> 42 installed packages.
-- linux-rhel6-x86_64 / gcc@4.4.6 -------------------------------
autoconf@2.69   bedtools2@2.26.0  boost@1.63.0  curl@7.53.1  gcc@6.3.0         gmp@6.1.2        hwloc@1.11.6   libpciaccess@0.13.4  libxml2@2.9.4  mpc@1.0.3    openblas@0.2.19  pcre@8.40          samtools@1.4        xz@5.2.3
automake@1.15   binutils@2.28     bzip2@1.0.6   expat@2.2.0  gettext@0.19.8.1  help2man@1.47.4  isl@0.18       libsigsegv@2.11      m4@1.4.18      mpfr@3.1.5   openmpi@2.1.0    perl@5.24.1        tar@1.29            zip@3.0
bamtools@2.4.1  bison@3.0.4       cmake@3.7.2   flex@2.6.3   git@2.12.1        htslib@1.4       libiconv@1.15  libtool@2.4.6        mawk@1.3.4     ncurses@6.0  openssl@1.0.2k   pkg-config@0.29.2  util-macros@1.19.1  zlib@1.2.11

sysadmin@node156[~]$ module avail

------------------------------------------------------------------------------------------------------- /usr/share/Modules/modulefiles -------------------------------------------------------------------------------------------------------
dot         module-git  module-info modules     null        use.own

sysadmin@node156[~]$ echo $MODULEPATH
/usr/share/Modules/modulefiles:/etc/modulefiles

sysadmin@node156[~]$ module load /mount/stuff/apps/EL6/spack/share/spack/modules/linux-rhel6-x86_64/bedtools2-2.26.0-gcc-4.4.6-efkupa7

sysadmin@node156[~]$ bedtools --version
bedtools v2.26.0
```

The section of code in  setup-env.sh which sets this var seems to be:

```
# Set up modules and dotkit search paths in the user environment
#
_sp_share_dir=$(cd "$(dirname $_sp_source_file)" && pwd)
_sp_prefix=$(cd "$(dirname $(dirname $_sp_share_dir))" && pwd)
_spack_pathadd PATH       "${_sp_prefix%/}/bin"

_sp_sys_type=$(spack-python -c 'print(spack.architecture.sys_type())')
_sp_dotkit_root=$(spack-python -c "print(spack.util.path.canonicalize_path(spack.config.get_config('config').get('module_roots', {}).get('dotkit')))")
_sp_tcl_root=$(spack-python -c "print(spack.util.path.canonicalize_path(spack.config.get_config('config').get('module_roots', {}).get('tcl')))")
_spack_pathadd DK_NODE    "${_sp_dotkit_root%/}/$_sp_sys_type"
_spack_pathadd MODULEPATH "${_sp_tcl_root%/}/$_sp_sys_type"
```

Result:

```

sysadmin@node156[~]$ spack-python -c "print(spack.util.path.canonicalize_path(spack.config.get_config('config').get('module_roots', {}).get('tcl')))"
/mount/stuff/apps/EL6/spack/share/spack/modules

syadmin@node156[~]$ spack-python -c 'print(spack.architecture.sys_type())'
linux-centos6-x86_64

sysadmin@node156[~]$ ls -ltr /mount/stuff/apps/EL6/spack/share/spack/modules/linux-rhel6-x86_64/ | wc -l
43

sysadmin@node156[~]$ ls -ltr /mount/stuff/apps/EL6/spack/share/spack/modules/linux-rhel6-x86_64/ | head
total 168K
-rw-r--r-- 1 root root  961 Apr 13 15:37 libsigsegv-2.11-gcc-4.4.6-wxt4khc
-rw-r--r-- 1 root root  773 Apr 13 15:38 m4-1.4.18-gcc-4.4.6-pop62iy
-rw-r--r-- 1 root root 1006 Apr 13 15:39 gmp-6.1.2-gcc-4.4.6-kj7nhml
-rw-r--r-- 1 root root  984 Apr 13 15:40 mpfr-3.1.5-gcc-4.4.6-j7nsnrs
-rw-r--r-- 1 root root 1001 Apr 13 15:40 mpc-1.0.3-gcc-4.4.6-osp65qk
-rw-r--r-- 1 root root 1.5K Apr 13 15:40 bzip2-1.0.6-gcc-4.4.6-sou2qwr
-rw-r--r-- 1 root root  737 Apr 13 15:40 zip-3.0-gcc-4.4.6-376wzxy
-rw-r--r-- 1 root root 1.2K Apr 13 15:41 isl-0.18-gcc-4.4.6-ybcomk4
-rw-r--r-- 1 root root 1.4K Apr 13 15:42 bison-3.0.4-gcc-4.4.6-xk27fhf

```

So I am unsure why this isn't working.

**Comment by adamjstewart** [comment]
In the snippet you show, you aren't running:
```
$ source /mount/stuff/apps/EL6/spack/share/spack/setup-env.sh
```
on `node156`. Are you expecting `PATH` to be forwarded to this node? We do seem to be exporting `PATH`, so I'm not sure why that isn't working. You could also try out #3736 where I made a few modifications to this script. They aren't designed to solve this problem though.

**Comment by JusticeForMikeBrown** [comment]
Sorry:

sysadmin@node156[~]$ source /mount/stuff/apps/EL6/spack/share/spack/setup-env.sh

syadmin@node156[~]$ echo $MODULEPATH
/usr/share/Modules/modulefiles:/etc/modulefiles

sysadmin@node156[~]$ spack find
==> 42 installed packages.
-- linux-rhel6-x86_64 / gcc@4.4.6 -------------------------------
autoconf@2.69   bedtools2@2.26.0  boost@1.63.0  curl@7.53.1  gcc@6.3.0         gmp@6.1.2        hwloc@1.11.6   libpciaccess@0.13.4  libxml2@2.9.4  mpc@1.0.3    openblas@0.2.19  pcre@8.40          samtools@1.4        xz@5.2.3
automake@1.15   binutils@2.28     bzip2@1.0.6   expat@2.2.0  gettext@0.19.8.1  help2man@1.47.4  isl@0.18       libsigsegv@2.11      m4@1.4.18      mpfr@3.1.5   openmpi@2.1.0    perl@5.24.1        tar@1.29            zip@3.0
bamtools@2.4.1  bison@3.0.4       cmake@3.7.2   flex@2.6.3   git@2.12.1        htslib@1.4       libiconv@1.15  libtool@2.4.6        mawk@1.3.4     ncurses@6.0  openssl@1.0.2k   pkg-config@0.29.2  util-macros@1.19.1  zlib@1.2.11

export@node156[~]$ export MODULEPATH=/mount/stuff/apps/EL6/spack/share/spack/modules/linux-rhel6-x86_64:$MODULEPATH


dod2014@node156[~]$ module avail

------------------------------------------------------------------------------ /mount/stuff/apps/EL6/spack/share/spack/modules/linux-rhel6-x86_64 -------------------------------------------------------------------------------
autoconf-2.69-gcc-4.4.6-iquqclp       bzip2-1.0.6-gcc-4.4.6-sou2qwr         git-2.12.1-gcc-4.4.6-74lirj6          libpciaccess-0.13.4-gcc-4.4.6-7tleclp mpfr-3.1.5-gcc-4.4.6-j7nsnrs          pkg-config-0.29.2-gcc-4.4.6-iydmn3z
automake-1.15-gcc-4.4.6-o7mbo4v       cmake-3.7.2-gcc-4.4.6-4ftp7ke         gmp-6.1.2-gcc-4.4.6-kj7nhml           libsigsegv-2.11-gcc-4.4.6-wxt4khc     ncurses-6.0-gcc-4.4.6-dooyyhq         samtools-1.4-gcc-4.4.6-lmqaw4t
bamtools-2.4.1-gcc-4.4.6-myiowro      curl-7.53.1-gcc-4.4.6-nyd6lf3         help2man-1.47.4-gcc-4.4.6-tbe2kki     libtool-2.4.6-gcc-4.4.6-234bdxl       openblas-0.2.19-gcc-4.4.6-62fsoge     tar-1.29-gcc-4.4.6-khtut33
bedtools2-2.26.0-gcc-4.4.6-efkupa7    expat-2.2.0-gcc-4.4.6-s4kzbv5         htslib-1.4-gcc-4.4.6-pideutw          libxml2-2.9.4-gcc-4.4.6-szkxoqt       openmpi-2.1.0-gcc-4.4.6-g6be566       util-macros-1.19.1-gcc-4.4.6-roiz7ew
binutils-2.28-gcc-4.4.6-a4bouod       flex-2.6.3-gcc-4.4.6-3lhywtv          hwloc-1.11.6-gcc-4.4.6-7oifsdj        m4-1.4.18-gcc-4.4.6-pop62iy           openssl-1.0.2k-gcc-4.4.6-g5whrka      xz-5.2.3-gcc-4.4.6-7ah2pyt
bison-3.0.4-gcc-4.4.6-xk27fhf         gcc-6.3.0-gcc-4.4.6-han2ovj           isl-0.18-gcc-4.4.6-ybcomk4            mawk-1.3.4-gcc-4.4.6-pv64smz          pcre-8.40-gcc-4.4.6-xust2yg           zip-3.0-gcc-4.4.6-376wzxy
boost-1.63.0-gcc-4.4.6-gpfsh3e        gettext-0.19.8.1-gcc-4.4.6-rytpqz2    libiconv-1.15-gcc-4.4.6-ep5mbfs       mpc-1.0.3-gcc-4.4.6-osp65qk           perl-5.24.1-gcc-4.4.6-a43rx7y         zlib-1.2.11-gcc-4.4.6-erzei6x

------------------------------------------------------------------------------------------------------- /usr/share/Modules/modulefiles -------------------------------------------------------------------------------------------------------
dot         module-git  module-info modules     null        use.own

sysadmin@node156[~]$ spack load bedtools2

sysadmin@node156[~]$ bedtools --version
bedtools v2.26.0
```

So if I do export MODULEPATH=/mount/stuff/apps/EL6/spack/share/spack/modules/linux-rhel6-x86_64:$MODULEPATH then that fixes the issue though why does the setup-env.sh script not already handle that process?

**Comment by adamjstewart** [comment]
Looking at `_spack_pathadd`, it seems like it is only added if:

1. The directory exists
2. The directory is not already in your `MODULEPATH`

You could try debugging the script with execution tracing (`bash -x`):
http://tldp.org/LDP/Bash-Beginners-Guide/html/sect_02_03.html
or by adding echo statements everywhere.

**Comment by JusticeForMikeBrown** [comment]
Thanks for the help.  The head node is rhel while the nodes are centos.  So that's the problem.

**Comment by adamjstewart** [comment]
@tgamblin I think another user once asked whether or not we should merge `rhel` and `centos` into a single binary-compatible OS type. I think the idea has merit.

**Comment by JusticeForMikeBrown** [comment]
They are essentially the same so I support that decision though for now a symlink solved the problem!

**Comment by tgamblin** [comment]
@adamjstewart: there's been some debate on this in the past.  I believe the CERN folks like to be specific about their OS's, while I was actually advocating making `centos` show up as RHEL, but we went for "whatever the `distro` package reports" to keep things simple.  I actually ended up kind of liking the fact that we now have more specific descriptors, as I think it's nice to have detailed provenance in the specs, so that you know where things were built.  But that doesn't solve this problem.

Seems like here you want to have *all* binary compatible OS's included in your `MODULEPATH`, and similarly I would eventually like to make Spack's concretizer smart enough to resolve dependencies on one OS using binary compatible installs from another (e.g. it could take `rhel` binaries and use them to resolve deps on `centos`).  For both of those you'd need a file describing which OS's are binary compatible with which, e.g. it could say something like:

```
centos6 <=> rhel6
```

or if you only want to use rhel builds from centos:

```
centos6 <= rhel6
```

Then we could add your OS *and* any compatible ones to MODULEPATH on startup, and use the same information in the new concretizer to pick dependencies later.

**Comment by JusticeForMikeBrown** [comment]
That would be amazing.  We're slowly retiring our RHEL servers but of course busy users make that process difficult!

**Comment by adamjstewart** [comment]
At ANL our management nodes are all RHEL but our login and compute nodes are all CentOS. I've avoided this problem by building everything on the login nodes instead of the management nodes. So no rush from my end. But it would be a cool feature.
