### ISSUE TITLE
I'm worried about whether Lmod's module switching is leading me astray.

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#3892]
I'm confused about Lmod's module switching.

Here's an example. *blast-plus* depends on python and I have a line in my `packages.yaml` that makes `python@2.7.13` the default.  If I then go on to load a different version of python, Lmod helpfully swaps it out.

```
[hartzelg@lb117esx ~]$ module load gcc
[hartzelg@lb117esx ~]$ module load blast-plus
[hartzelg@lb117esx ~]$ module list

Currently Loaded Modules:
  1) gcc/5.4.0     5) zlib/1.2.11      9) python/2.7.13  13) lzo/2.09       17) blast-plus/2.6.0
  2) pcre/8.40     6) openssl/1.0.2k  10) libpng/1.6.27  14) gmp/6.1.2
  3) bzip2/1.0.6   7) sqlite/3.8.5    11) freetype/2.7   15) nettle/3.2
  4) ncurses/6.0   8) readline/7.0    12) jpeg/9b        16) gnutls/3.5.10



[hartzelg@lb117esx ~]$ module load python/3.6.0

The following have been reloaded with a version change:
  1) python/2.7.13 => python/3.6.0

```

I don't think that this is going to leave *blast-plus* in a good place (I'm still trying to figure out what blast's doing with it, perhaps it should become a variant).

Should I be more or less concerned?

**Comment by alalazo** [comment]
In this case module switching will not work the same as with `lapack` or `mpi`, because `python` is not a virtual package in Spack. 

So: yes you may have an inconsistent environment where `blast-plus` want to use `python@2.X` and will thus retrieve what you have installed in `/usr/bin` or something like that (because for `python@3.X` the executable will be `python3`).

**Comment by citibeth** [comment]
I avoid unloading modules because it's tricky and subtle.  I use `module load` and `module purge` to get what I need.

**Comment by hartzell** [comment]
@citibeth -- This wasn't an unload, it was a series of two loads (with Lmod module switching in the mix).

**Comment by hartzell** [comment]
I'm dodging the bullet on this one, I can't figure out anything useful that building blast-plus `--with-python` gives us, so I've updated the package (#3992) to make it a variant and plan to disable it.

I'm not sure if there's a bigger issue here or not.

@alalazo -- I noticed that you assigned this to yourself, should I leave it open for your consideration or close it?

**Comment by alalazo** [comment]
@hartzell Feel free to close the ticket. Sometimes I assign to myself the tickets I am interested in because they appear in a shorter list.
