### ISSUE TITLE
Spack can no longer install unknown versions

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#38962]
### Steps to reproduce

This definitely used to be a feature. Not sure when this changed or if it was intentional.
```console
> spack install py-pycocotools@2.0.5
==> Error: concretization failed for the following reasons:

   1. Cannot satisfy 'py-pycocotools@2.0.5'
```

### Error message

```console
> spack install py-pycocotools@2.0.5
==> Error: concretization failed for the following reasons:

   1. Cannot satisfy 'py-pycocotools@2.0.5'
```

### Information on your system

* **Spack:** 0.21.0.dev0 (e47a2a7a652176d72f888a7e323c5a6020d4c9bf)
* **Python:** 3.10.10
* **Platform:** darwin-ventura-m2
* **Concretizer:** clingo

@alalazo @becker33 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Try:
```console
$ spack install py-pycocotools@=2.0.5
```
What you asked for is a range, and there is no known version in that range. If you use `@=` you specify a version and that is respected by the concretizer.

**Comment by adamjstewart** [comment]
That's... an unfortunate side effect. Was this intentional?

**Comment by alalazo** [comment]
Yes that was intentional and part of the semantic in the version change for v0.20

**Comment by adamjstewart** [comment]
Alright. Well at least I know what to do if I see someone else report this issue. Thanks for the explanation!

**Comment by alalazo** [comment]
For reference, most of the discussion around the semantic is in #36273
