### ISSUE TITLE
Installation issue: esmf%oneapi longtoint.patch

### ISSUE THREAD

**Issue by dubmarm** [LLNL/spack#39068]
### Steps to reproduce the issue

```console
$ spack install esmf%oneapi
...
```

### Error message

Spack fails to patch esmf for OneAPI.

<details><summary>Error message</summary>

<pre>
==> Installing esmf-8.2.0-neond5fjprzka7skvf3dfvh77zww7i7h
==> No binary for esmf-8.2.0-neond5fjprzka7skvf3dfvh77zww7i7h found: installing from source
==> Using cached archive: /home/dubi037/git/spack-20.0.1/var/spack/cache/_source-cache/archive/27/27866c31fdb63c58e78211de970470ca02d274f5d4d6d97e94284d63b1c1d9e4.tar.gz
1 out of 1 hunk FAILED -- saving rejects to file src/Infrastructure/Mesh/src/Legacy/ESMCI_MeshPNC.C.rej
1 out of 1 hunk FAILED -- saving rejects to file src/Infrastructure/Mesh/src/Legacy/ESMCI_WriteWeightsPar.C.rej
==> Patch /home/dubi037/git/spack-20.0.1/var/spack/repos/builtin/packages/esmf/longtoint.patch failed.
==> Error: ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/home/dubi037/git/spack-20.0.1/var/spack/repos/builtin/packages/esmf/longtoint.patch' '-d' '.'
==> Error: esmf-8.2.0-neond5fjprzka7skvf3dfvh77zww7i7h: Package was not installed
==> Error: Installation request failed.  Refer to reported errors for failing package(s).
</pre></details>

### Information on your system

```console
* **Spack:** 0.20.1
* **Python:** 3.6.8
* **Platform:** linux-centos7-cascadelake
* **Concretizer:** clingo
```

### Additional information

I can get esmf to build with the following steps; the key difference is that I include `-F 4` for a fuzz search in the patch command:

```bash
spack stage esmf%oneapi
spack cd esmf%oneapi
/usr/bin/patch -F 4 -p 1 -i /home/dubi037/git/spack-20.0.1/var/spack/repos/builtin/packages/esmf/longtoint.patch -d .
```

@AlexanderRichert-NOAA   @climbfuji @jedwards4b @theurich @uturuncoglu

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by jedwards4b** [comment]
patch("longtoint.patch", when="@:8.3.2 %oneapi@2022:") 
what version of oneapi and esmf are you using?  We do not need this patch for more recent esmf versions.

**Comment by dubmarm** [comment]
OneAPI is `2023.1.0`
ESMF is concretizing to `8.2.0` (dictated by `ncl%oneapi`)

**Comment by dubmarm** [comment]
I see. I can close this. ncl is wanting a super old version of esmf. Thank you
