### ISSUE TITLE
latest release tag not updated

### ISSUE THREAD

**Issue by fgava90** [LLNL/spack#39125]
The latest release tag still points to 0.20.0
 @alalazo tagging you because i think you released 0.20.1

**Comment by alalazo** [comment]
Thanks for reporting

**Comment by alalazo** [comment]
Should be fixed now https://github.com/spack/spack/tree/releases/latest

**Comment by fgava90** [comment]
Hello again,

Tagging @tgamblin this time as he made the v0.21.0 release.

releases/latest is still pointing to v0.20.1
Could you kindly update it to point to v0.21.0?

Perhaps you should automate this task as i see it is regularly forgotten?
