### ISSUE TITLE
py-torch picks up system cuda libs on top of spack installed cuda

### ISSUE THREAD

**Issue by Sinan81** [LLNL/spack#39134]
### Steps to reproduce the issue

1. system cuda libs *were* installed at `/usr/local/cuda` a symlink to `/usr/local/cuda-10.0`
2. in the environment only cuda@11.0 is used (with `concretize: together`)
3. after removing system cuda libs, `py-torch` is failing to even import:
```
$ python
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/disk/hpcpm/myspack/0171/var/spack/environments/qgis_and_venv_gcc750_x64_pysh_20230706/.spack-env/view/lib/python3.8/site-packages/torch/__init__.py", line 196, in <module>
    _load_global_deps()
  File "/disk/hpcpm/myspack/0171/var/spack/environments/qgis_and_venv_gcc750_x64_pysh_20230706/.spack-env/view/lib/python3.8/site-packages/torch/__init__.py", line 149, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/disk/hpcpm/myspack/0171/var/spack/environments/qgis_and_venv_gcc750_x64_pysh_20230706/.spack-env/view/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.10.0: cannot open shared object file: No such file or directory
```
4. after removal of system cuda, triggered a rebuild of py-torch by slightly modifying a dependency. py-torch still giving the same error above after the rebuild.
5. double checked that `ccache` is disabled in spack config, just in case.

### Error message

see above.

### Information on your system

$ spack debug report
* **Spack:** 0.17.1
* **Python:** 3.6.8
* **Platform:** linux-centos7-haswell
* **Concretizer:** clingo

### Additional information

during the rebuild, I looked at `ccmake .` of in py-torch build folder. It looked like cuda was detected correctly. Could py-torch somehow be picking up this system cuda libs from a dependency that's not re-built?

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by Sinan81** [comment]
pinging @adamjstewart 
This is not super urgent, just wanted to report this. it would be great if I didn't have the re-install spack and all the packages and the environment.

**Comment by adamjstewart** [comment]
Can you share the full build log? You can also poke around by running `ldd -r` on the `.so` files that PyTorch installs. 

CUDA is special. The Spack package should be able to install the run-time libraries (in theory), but it isn't possible to install the drivers without manual installation. I've never used Spack-installed CUDA before, and I'm not sure if I would recommend it.

**Comment by Sinan81** [comment]
> CUDA is special. The Spack package should be able to install the run-time libraries (in theory), but it isn't possible to install the drivers without manual installation. 

`libcudart.so` is not part of system drivers but cuda toolkit.

> I've never used Spack-installed CUDA before, and I'm not sure if I would recommend it.

We've been using Spack installed Cuda where I work for a while now. It's working just fine. Installing nvidia drivers is a different story.

**Comment by Sinan81** [comment]
> You can also poke around by running ldd -r on the .so files that PyTorch installs.

here it is.
[log_torch_dyn.txt](https://github.com/spack/spack/files/12218314/log_torch_dyn.txt)

it's interesting to note that py-torch is dynamically linking to both `libcudart.so.11.0` and `libcudart.10.0`

**Comment by Sinan81** [comment]
I guess I could rebuild the entire environment by indicating the arch as `x86_64-v2`. Though in that case would the packages still work on an non-AVX2 machine?

**Comment by adamjstewart** [comment]
Can you share the build log? Maybe that will explain why it's linking to two different versions of CUDA.

**Comment by Sinan81** [comment]
It turns out I cleared spack cache while working on another thing. I'll rebuild it and share build log here.

**Comment by Sinan81** [comment]
Here is the build log. As far as I can tell, there's no indication of a cuda mixup there.
[spack-build-01-install-out.txt](https://github.com/spack/spack/files/12245405/spack-build-01-install-out.txt)

**Comment by adamjstewart** [comment]
Is the issue that your Spack-installed toolkit version doesn't match the system-installed driver version?

**Comment by Sinan81** [comment]
>Is the issue that your Spack-installed toolkit version doesn't match the system-installed driver version?

No. nvidia driver version is 470 which supports up to cuda@11.4. In my spack env I'm using cuda@11.0
The issue is two fold:
1. the package somehow links to both system installed cuda toolkit and the spack installed one. (although it totally looks like it's using spack installed cuda during build). 
2. Even after the system installation is removed and py-torch is rebuilt, the dynamic linking issue lingers (could a dependency, such as python, have cache files lying around which somehow still links to the system cuda that's now removed.)

Could I trigger a rebuild of all the packages in the entire spack env without disturbing all previously installed packages used by other environments?

Again, this is not super urgent. But I just wanted to pick your brain.

**Comment by adamjstewart** [comment]
Yes, you can rebuild one environment without touching other environments.

My best guess is that RPATH is not working correctly. You could try setting `LD_LIBRARY_PATH` and see if that helps.

**Comment by adamjstewart** [comment]
Is this still an issue or can we close?

**Comment by Sinan81** [comment]
This can be closed. Thanks Adam.
