### ISSUE TITLE
Installation issue: py-scipy

### ISSUE THREAD

**Issue by thomas-bouvier** [LLNL/spack#39197]
### Steps to reproduce the issue

Hello,

My installation of `py-scipy` is failing with the following message: ` scipy/meson.build:134:7: ERROR: Dependency "mkl-dynamic-lp64-seq" not found, tried pkgconfig and cmake`.

```console
$ spack spec -I <spec>
root@chifflot-7:~# spack spec -I py-scipy
Input spec
--------------------------------
 -   py-scipy

Concretized
--------------------------------
 -   py-scipy@1.11.1%gcc@10.4.0 build_system=python_pip arch=linux-debian11-skylake_avx512
[+]      ^intel-oneapi-mkl@2023.2.0%gcc@10.4.0~cluster+envmods~ilp64+shared build_system=generic threads=none arch=linux-debian11-skylake_avx512
[+]          ^intel-tbb@2021.9.0%gcc@10.4.0~ipo+shared+tm build_system=cmake build_type=Release cxxstd=default generator=make patches=12a9c3e arch=linux-debian11-skylake_avx512
[+]              ^gmake@4.4.1%gcc@10.4.0~guile build_system=autotools arch=linux-debian11-skylake_avx512
[+]              ^hwloc@2.9.1%gcc@10.4.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-debian11-skylake_avx512
[+]                  ^libpciaccess@0.17%gcc@10.4.0 build_system=autotools arch=linux-debian11-skylake_avx512
[+]                      ^libtool@2.4.7%gcc@10.4.0 build_system=autotools arch=linux-debian11-skylake_avx512
[+]                          ^m4@1.4.19%gcc@10.4.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-debian11-skylake_avx512
[+]                              ^libsigsegv@2.14%gcc@10.4.0 build_system=autotools arch=linux-debian11-skylake_avx512
[+]                      ^util-macros@1.19.3%gcc@10.4.0 build_system=autotools arch=linux-debian11-skylake_avx512
[+]      ^pkgconf@1.9.5%gcc@10.4.0 build_system=autotools arch=linux-debian11-skylake_avx512
[+]      ^py-build@0.10.0%gcc@10.4.0~virtualenv build_system=python_pip arch=linux-debian11-skylake_avx512
[+]          ^py-flit-core@3.7.1%gcc@10.4.0 build_system=python_pip arch=linux-debian11-skylake_avx512
[+]          ^py-packaging@23.1%gcc@10.4.0 build_system=python_pip arch=linux-debian11-skylake_avx512
[+]          ^py-pyproject-hooks@1.0.0%gcc@10.4.0 build_system=python_pip arch=linux-debian11-skylake_avx512
[+]          ^py-tomli@2.0.1%gcc@10.4.0 build_system=python_pip arch=linux-debian11-skylake_avx512
[+]      ^py-cython@0.29.36%gcc@10.4.0 build_system=python_pip arch=linux-debian11-skylake_avx512
[+]          ^py-setuptools@63.4.3%gcc@10.4.0 build_system=generic arch=linux-debian11-skylake_avx512
 -       ^py-meson-python@0.13.1%gcc@10.4.0 build_system=python_pip arch=linux-debian11-skylake_avx512
[+]          ^meson@1.2.0%gcc@10.4.0 build_system=python_pip patches=0f0b1bd arch=linux-debian11-skylake_avx512
[+]          ^py-pyproject-metadata@0.7.1%gcc@10.4.0 build_system=python_pip arch=linux-debian11-skylake_avx512
[+]      ^py-numpy@1.25.1%gcc@10.4.0+blas+lapack build_system=python_pip patches=873745d arch=linux-debian11-skylake_avx512
[+]      ^py-pip@23.0%gcc@10.4.0 build_system=generic arch=linux-debian11-skylake_avx512
 -       ^py-pybind11@2.10.4%gcc@10.4.0~ipo build_system=cmake build_type=Release generator=ninja arch=linux-debian11-skylake_avx512
[+]          ^cmake@3.26.3%gcc@10.4.0~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-debian11-skylake_avx512
[+]              ^curl@8.1.2%gcc@10.4.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-debian11-skylake_avx512
[+]                  ^nghttp2@1.52.0%gcc@10.4.0 build_system=autotools arch=linux-debian11-skylake_avx512
[+]          ^ninja@1.11.1%gcc@10.4.0+re2c build_system=generic arch=linux-debian11-skylake_avx512
[+]              ^re2c@2.2%gcc@10.4.0 build_system=generic arch=linux-debian11-skylake_avx512
[+]      ^py-pythran@0.12.2%gcc@10.4.0 build_system=python_pip arch=linux-debian11-skylake_avx512
[+]          ^py-beniget@0.4.1%gcc@10.4.0 build_system=python_pip arch=linux-debian11-skylake_avx512
[+]          ^py-gast@0.5.3%gcc@10.4.0 build_system=python_pip arch=linux-debian11-skylake_avx512
[+]          ^py-ply@3.11%gcc@10.4.0 build_system=python_pip arch=linux-debian11-skylake_avx512
[+]      ^py-wheel@0.37.1%gcc@10.4.0 build_system=generic arch=linux-debian11-skylake_avx512
[+]      ^python@3.10.12%gcc@10.4.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=0d98e93,7d40923,f2fd060 arch=linux-debian11-skylake_avx512
[+]          ^bzip2@1.0.8%gcc@10.4.0~debug~pic+shared build_system=generic arch=linux-debian11-skylake_avx512                                                                                                                                                   [+]              ^diffutils@3.9%gcc@10.4.0 build_system=autotools arch=linux-debian11-skylake_avx512
[+]          ^expat@2.5.0%gcc@10.4.0~ipo~libbsd+shared build_system=cmake build_type=Release generator=make arch=linux-debian11-skylake_avx512
[+]          ^gdbm@1.23%gcc@10.4.0 build_system=autotools arch=linux-debian11-skylake_avx512
[+]          ^gettext@0.21.1%gcc@10.4.0+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=linux-debian11-skylake_avx512
[+]              ^libiconv@1.17%gcc@10.4.0 build_system=autotools libs=shared,static arch=linux-debian11-skylake_avx512
[+]              ^libxml2@2.10.3%gcc@10.4.0~python build_system=autotools arch=linux-debian11-skylake_avx512
[+]              ^tar@1.34%gcc@10.4.0 build_system=autotools zip=pigz arch=linux-debian11-skylake_avx512
[+]                  ^pigz@2.7%gcc@10.4.0 build_system=makefile arch=linux-debian11-skylake_avx512
[+]                  ^zstd@1.5.5%gcc@10.4.0+programs build_system=makefile compression=none libs=shared,static arch=linux-debian11-skylake_avx512
[+]          ^libffi@3.4.4%gcc@10.4.0 build_system=autotools arch=linux-debian11-skylake_avx512
[+]          ^libxcrypt@4.4.35%gcc@10.4.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-debian11-skylake_avx512
[+]              ^perl@5.38.0%gcc@10.4.0+cpanm+opcode+open+shared+threads build_system=generic arch=linux-debian11-skylake_avx512
[+]                  ^berkeley-db@18.1.40%gcc@10.4.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-debian11-skylake_avx512
[+]          ^ncurses@6.4%gcc@10.4.0~symlinks+termlib abi=none build_system=autotools arch=linux-debian11-skylake_avx512
[+]          ^openssl@3.1.1%gcc@10.4.0~docs~shared build_system=generic certs=mozilla arch=linux-debian11-skylake_avx512
[+]              ^ca-certificates-mozilla@2023-05-30%gcc@10.4.0 build_system=generic arch=linux-debian11-skylake_avx512
[+]          ^readline@8.2%gcc@10.4.0 build_system=autotools patches=bbf97f1 arch=linux-debian11-skylake_avx512
[+]          ^sqlite@3.42.0%gcc@10.4.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-debian11-skylake_avx512
[+]          ^util-linux-uuid@2.38.1%gcc@10.4.0 build_system=autotools arch=linux-debian11-skylake_avx512
[+]          ^xz@5.4.1%gcc@10.4.0~pic build_system=autotools libs=shared,static arch=linux-debian11-skylake_avx512
[+]          ^zlib@1.2.13%gcc@10.4.0+optimize+pic+shared build_system=makefile arch=linux-debian11-skylake_avx512
```

Pinging @adamjstewart  @pradyunsg @rgommers. Thank you!

### Error message

The error message mentions a missing runtime dependency on `mkl-dynamic-lp64-seq`. Should [the recipe](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-scipy/package.py) be updated somehow?

```
     35    Found CMake: /usr/bin/cmake (3.26.2)
     36    WARNING: CMake Toolchain: Failed to determine CMake compilers state
     37    Run-time dependency mkl-dynamic-lp64-seq found: NO (tried pkgconfig and cmake)
     38
  >> 39    scipy/meson.build:134:7: ERROR: Dependency "mkl-dynamic-lp64-seq" not found, tried pkgconfig and cmake
```

<details><summary>Error message</summary>

<pre>
==> py-scipy: Executing phase: 'install'
==> [2023-08-02-01:20:36.133926] '/srv/storage/kerdatalille@storage1.lille.grid5000.fr/spack/linux-debian11-skylake_avx512/gcc-10.4.0/meson-1.2.0-w3grdjwhhp6var4pzh3cj2qsfk67mrns/bin/meson' 'setup' 'build' '-Dblas=mkl-dynamic-lp64-seq' '-Dlapack=mkl-dynamic-lp64-seq' '--prefix=/tmp/spack-stage/root/spack-stage-py-scipy-1.10.1-rjb5hz4h54wahv7xfaiyoxjlrviend3d/spack-src/build-install' '-Ddebug=false' '-Doptimization=2'
The Meson build system
Version: 1.2.0
Source dir: /tmp/spack-stage/root/spack-stage-py-scipy-1.10.1-rjb5hz4h54wahv7xfaiyoxjlrviend3d/spack-src
Build dir: /tmp/spack-stage/root/spack-stage-py-scipy-1.10.1-rjb5hz4h54wahv7xfaiyoxjlrviend3d/spack-src/build
Build type: native build
Project name: SciPy
Project version: 1.10.1
C compiler for the host machine: /home/tbouvier/spack-lille/spack/lib/spack/env/gcc/gcc (gcc 10.4.0 "gcc (Spack GCC) 10.4.0")
C linker for the host machine: /home/tbouvier/spack-lille/spack/lib/spack/env/gcc/gcc ld.bfd 2.35.2
C++ compiler for the host machine: /home/tbouvier/spack-lille/spack/lib/spack/env/gcc/g++ (gcc 10.4.0 "g++ (Spack GCC) 10.4.0")
C++ linker for the host machine: /home/tbouvier/spack-lille/spack/lib/spack/env/gcc/g++ ld.bfd 2.35.2
Cython compiler for the host machine: cython (cython 0.29.36)
Host machine cpu family: x86_64
Host machine cpu: x86_64
Compiler for C supports arguments -Wno-unused-but-set-variable: YES 
Compiler for C supports arguments -Wno-unused-function: YES 
Compiler for C supports arguments -Wno-conversion: YES 
Compiler for C supports arguments -Wno-misleading-indentation: YES 
Compiler for C supports arguments -Wno-incompatible-pointer-types: YES 
Library m found: YES
Fortran compiler for the host machine: /home/tbouvier/spack-lille/spack/lib/spack/env/gcc/gfortran (gcc 10.4.0 "GNU Fortran (Spack GCC) 10.4.0")
Fortran linker for the host machine: /home/tbouvier/spack-lille/spack/lib/spack/env/gcc/gfortran ld.bfd 2.35.2
Compiler for Fortran supports arguments -Wno-conversion: YES 
Checking if "-Wl,--version-script" : links: YES 
Program cython found: YES (/srv/storage/kerdatalille@storage1.lille.grid5000.fr/spack/linux-debian11-skylake_avx512/gcc-10.4.0/py-cython-0.29.36-puyda5tvgf6refmfbutpn5te66mssbwi/bin/cython)
Program python3 found: YES (/srv/storage/kerdatalille@storage1.lille.grid5000.fr/spack/linux-debian11-skylake_avx512/gcc-10.4.0/python-3.10.12-yqqrjwtnpv2x74aldh2rkeiltxzaimxd/bin/python3.10)
Found pkg-config: /srv/storage/kerdatalille@storage1.lille.grid5000.fr/spack/linux-debian11-skylake_avx512/gcc-10.4.0/pkgconf-1.9.5-itdrhtvcglsw4zsln7ubvekswdhttpkw/bin/pkg-config (1.9.5)
Run-time dependency python found: YES 3.10
Program pythran found: YES (/srv/storage/kerdatalille@storage1.lille.grid5000.fr/spack/linux-debian11-skylake_avx512/gcc-10.4.0/py-pythran-0.12.2-zx7f5ah6vfjeot32i6f3euym4dvaselo/bin/pythran)
Run-time dependency threads found: YES
Library npymath found: YES
Library npyrandom found: YES
Found CMake: /usr/bin/cmake (3.26.2)
WARNING: CMake Toolchain: Failed to determine CMake compilers state
Run-time dependency mkl-dynamic-lp64-seq found: NO (tried pkgconfig and cmake)

scipy/meson.build:134:7: ERROR: Dependency "mkl-dynamic-lp64-seq" not found, tried pkgconfig and cmake

A full log can be found at /tmp/spack-stage/root/spack-stage-py-scipy-1.10.1-rjb5hz4h54wahv7xfaiyoxjlrviend3d/spack-src/build/meson-logs/meson-log.txt

</pre></details>

### Information on your system

* **Spack:** 0.21.0.dev0
* **Python:** 3.10.12
* **Platform:** linux-debian11-skylake_avx512
* **Concretizer:** clingo

### Additional information

I enter these [conditions](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-scipy/package.py#L210-L212) in the recipe.

[spack-build-out.txt](https://github.com/spack/spack/files/12234626/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/12234633/spack-build-env.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by rgommers** [comment]
The MKL you picked up is `intel-oneapi-mkl@2023.2.0%gcc@10.4.0~cluster+envmods~ilp64+shared` - the ILP64 part won't work with SciPy as of right now. I'd still expect the build to work though, because MKL provides LP64 and ILP64 symbols in a single library. The error message indicates that the `mkl-dynamic-lp64-seq.pc` file was not installed as it should have been, or to a location that `pkg-config` cannot find. 

Could you check that? E.g., `pkg-config --libs mkl-dynamic-lp64-seq.pc`, or replacing the `lp64` with `ilp64` there? I know there were fixes before to get all the `.pc` files for MKL installed, and it's unclear if they all went missing here, or just one, or they're present but there's an issue with the paths that `pkg-config` searches.

**Comment by thomas-bouvier** [comment]
Thank you. When using pkg-config for the `.pc` files, I get the following:

```
pkg-config --libs mkl-dynamic-lp64-seq
Package mkl-dynamic-lp64-seq.pc was not found in the pkg-config search path.
Perhaps you should add the directory containing `mkl-dynamic-lp64-seq.pc'
to the PKG_CONFIG_PATH environment variable
Package 'mkl-dynamic-lp64-seq.pc', required by 'virtual:world', not found
```

I was able to find the `.pc` files on my system, so I'm confused. Moreover, their path is present in the `PKG_CONFIG_PATH=/srv/storage/kerdatalille@storage1.lille.grid5000.fr/spack/linux-debian11-skylake_avx512/gcc-10.4.0/intel-oneapi-mkl-2023.2.0-dxwgcekggvk6dv22ixbz22fwpyjtyhkw/lib/pkgconfig:/srv/storage/kerdatalille@storage1.lille.grid5000.fr/spack/linux-debian11-skylake_avx512/gcc-10.4.0/intel-oneapi-mkl-2023.2.0-dxwgcekggvk6dv22ixbz22fwpyjtyhkw/mkl/2023.2.0/lib/pkgconfig:...`

```
# find /srv/storage/kerdatalille@storage1.lille.grid5000.fr -name mkl-dynamic-ilp64-seq.pc
/srv/storage/kerdatalille@storage1.lille.grid5000.fr/spack/linux-debian11-skylake_avx512/gcc-10.4.0/intel-oneapi-mkl-2023.2.0-dxwgcekggvk6dv22ixbz22fwpyjtyhkw/mkl/2023.2.0/lib/pkgconfig/mkl-dynamic-ilp64-seq.pc
/srv/storage/kerdatalille@storage1.lille.grid5000.fr/spack/linux-debian11-skylake_avx512/gcc-10.4.0/intel-oneapi-mkl-2023.2.0-dxwgcekggvk6dv22ixbz22fwpyjtyhkw/lib/pkgconfig/mkl-dynamic-ilp64-seq.pc

# find /srv/storage/kerdatalille@storage1.lille.grid5000.fr -name mkl-dynamic-lp64-seq.pc
/srv/storage/kerdatalille@storage1.lille.grid5000.fr/spack/linux-debian11-skylake_avx512/gcc-10.4.0/intel-oneapi-mkl-2023.2.0-dxwgcekggvk6dv22ixbz22fwpyjtyhkw/mkl/2023.2.0/lib/pkgconfig/mkl-dynamic-lp64-seq.pc
/srv/storage/kerdatalille@storage1.lille.grid5000.fr/spack/linux-debian11-skylake_avx512/gcc-10.4.0/intel-oneapi-mkl-2023.2.0-dxwgcekggvk6dv22ixbz22fwpyjtyhkw/lib/pkgconfig/mkl-dynamic-lp64-seq.pc
```

Still investigating.

**Comment by thomas-bouvier** [comment]
I can't reproduce that issue.
