### ISSUE TITLE
setup-env.csh doesn't do anything if SPACK_ROOT is unset

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#3924]
I don't use csh, but I just noticed that `setup-env.csh` doesn't do anything unless `SPACK_ROOT` is set. Is there no way to determine `SPACK_ROOT` automatically? At the very least, it should print a warning message saying that nothing was done and you need to define `SPACK_ROOT`.

**Comment by tgamblin** [comment]
It's true. A warning would be good.

If someone's csh-fu is better than mine they could try to make the script locate itself properly, like the bash one does.  I could not see how to make that work in tcsh or csh, for a sourced script.
