### ISSUE TITLE
Spack still creates environment even if spack.yaml is invalid

### ISSUE THREAD

**Issue by mdorier** [LLNL/spack#39248]
### Steps to reproduce

I was using this outdated spack.yaml file (reduced for simplicity to just one spec):

```
spack:
    specs:
    - py-pkgconfig
    concretization: together
```

Creating the environment with the following command:

```
spack env create myenv spack.yaml
```

I'm correctly getting an error `==> Error:  ... Additional properties are not allowed ('concretization' was unexpected)`.
However, `myenv` is still created by spack, can be found with `spack env list`, and most importantly *cannot be removed*.

```
$ spack env rm myenv
==> Error: /home/mdorier.linux/.spack-env/myenv/spack.yaml:2: Additional properties are not allowed ('concretization' was unexpected)
```

It has to be removed manually (i.e. `rm -rf /home/mdorier.linux/.spack-env/myenv`).

### Information on your system

* **Spack:** 0.21.0.dev0 (d456f32685bcb4a018ac917c7673bff727791733)
* **Python:** 3.11.4
* **Platform:** linux-ubuntu23.04-aarch64
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by mdorier** [comment]
@tldahlgren Not sure it's fully completed. I just cloned spack@develop and tried with an environment file where I had a duplicate entry in the `packages` section. The environment creation failed, and the environment directory was still present, preventing me from trying to create it again afterwards.

**Comment by tldahlgren** [comment]
> @tldahlgren Not sure it's fully completed. I just cloned spack@develop and tried with an environment file where I had a duplicate entry in the `packages` section. The environment creation failed, and the environment directory was still present, preventing me from trying to create it again afterwards.

There's another use case that I tried that needs to be addressed as well.

**Comment by tldahlgren** [comment]
Reopened the issue since there are additional use cases that need to be addressed.
