### ISSUE TITLE
When do packages need to set LD_LIBRARY_PATH/when is RPATH sufficient?

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#3926]
I just noticed that "all" of my automagically generated Lmod modulefiles set LD_LIBRARY_PATH to `prefix().lib`.

This surprised me.  The section of the spack docs on transitive-dependencies [extol the virtues of the RPATH approach](http://spack.readthedocs.io/en/latest/workflows.html#transitive-dependencies) and it's one of the things that attracts me to Spack.

Of the three problematic cases that section discusses, it seems that only 2) & 3) require providing a `LD_LIBRARY_PATH` (and arguably that's a bug) and I'd expect that to be rare.

I know that I can add `LD_LIBRARY_PATH`  to the `environment_blacklist` in the `modules.yaml` file, but I wonder how many surprises are lurking down that road.

Would it be better to *not* automagically set `LD_LIBRARY_PATH` and force packages that require it (e.g. Python extensions) to explicitly provide it?

---

FWIW, I ran into this when I was trying to understand why UGE was telling me that it was stripping LD_LIBRARY_PATH from my `qsub -V`-ed job but that it appeared to be set anyway....

**Comment by hartzell** [comment]
@alalazo -- ping (:mortar_board:)

**Comment by adamjstewart** [comment]
One use is for users who use your Spack installations to build their own software. The things you install with Spack should work, but the things they install with it might not unless:

1. They know what RPATH is and use it when building their applications
2. A friendly sys admin sets LD_LIBRARY_PATH for them

**Comment by tgamblin** [comment]
The modules set `LD_LIBRARY_PATH` as a hint for build systems and programs run outside of Spack.  For example, build systems like CMake will [look at LD_LIBRARY_PATH](https://stackoverflow.com/questions/41566316/does-cmakes-find-library-search-ld-library-path) to find libraries.  So it's there to help users get Spack dependencies into their builds if they have Spack modules loaded.

It should not be necessary to run executables built by Spack -- if it is, the package should be fixed.

**Comment by tgamblin** [comment]
@hartzell: yep -- that one is *just* for CMake.
