### ISSUE TITLE
Installation issue:  esmf requires cmake3 when esmf_pio=internal

### ISSUE THREAD

**Issue by dubmarm** [LLNL/spack#39278]
### Steps to reproduce the issue

```console
$ spack stage esmf esmf_pio="internal"
$ spack cd esmf esmf_pio="internal"
$ ls src/Infrastructure/IO/PIO/ParallelIO
CMakeLists.txt     LICENSE      cmake              ctest     libpio.settings.in  tests
CTestConfig.cmake  Makefile.am  cmake_config.h.in  doc       scripts
CTestScript.cmake  README.md    configure.ac       examples  src
$ head src/Infrastructure/IO/PIO/ParallelIO/CMakeLists.txt | grep cmake_minimum_required
cmake_minimum_required (VERSION 3.5.2)
```

### Error message

Two issues occur.

1. Spack does not advertise a spack installed cmake to esmf during the build requiring a user to do something like this:
- `spack install esmf +esmf_parallelio ^cmake@3.5.2`
- Otherwise the esmf builder looks in $PATH for a cmake and locates a system cmake

2. Build fails for Centos7 because the default cmake is 2.8.12.2. The causes esmf build to fail throwing an error stating that cmake 3.5.2 is required

### Information on your system

Cenos7.9 has system provided `cmake@2.8.12.2`

```console
$ spack debug report
* **Spack:** 0.20.1
* **Python:** 3.6.8
* **Platform:** linux-centos7-cascadelake
* **Concretizer:** clingo
```

### Additional information

@AlexanderRichert-NOAA   @climbfuji   @jedwards4b   @theurich   @utu

Current work around for Centos7 builders is to `yum install cmake3`

The package needs a logic like the following:
```python
depends_on("cmake@3.5.2:", type="build", when="esmf_pio=internal"
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by theurich** [comment]
@dubmarm - please take a look at https://github.com/spack/spack/pull/39347.

Also, I noticed that Ufuk does not correctly show up under the original comment. It should be @uturuncoglu.

**Comment by dubmarm** [comment]
Closing the issue thanks to [#39347 ](https://github.com/spack/spack/pull/39347)
