### ISSUE TITLE
OpenSSL's FTP reorg causing problems

### ISSUE THREAD

**Issue by DavidPoliakoff** [LLNL/spack#3945]
Hey folks,

From a Spack installed this morning

`spack install openssl@1.0.2j
`

Doesn't work. 1.0.1u works and is good enough for me, but 1.0.2j gets error 550. 

==> Fetching ftp://openssl.org/source/openssl-1.0.2j.tar.gz

curl: (78) RETR response: 550
==> Fetching from ftp://openssl.org/source/openssl-1.0.2j.tar.gz failed.
==> Error: FetchError: All fetchers failed for openssl-1.0.2j-gv5uc2m3hf25ifay6rjputcvssgfvask

When I wget the attempted address.

No such file 'openssl-1.0.2j.tar.gz'.

Not a spack bug per se, but a lot uses OpenSSL, updating these would be helpful

**Comment by adamjstewart** [comment]
You should update to the latest develop version. OpenSSL now fetches from http.

**Comment by DavidPoliakoff** [comment]
Thanks, forgot the default clone is from master.

**Comment by adamjstewart** [comment]
@tgamblin Should we change the default branch to be develop?

**Comment by DavidPoliakoff** [comment]
Wow, even when I'm just talking about minor things I complicate Todd's life. That's neat.

**Comment by tgamblin** [comment]
> Thanks, forgot the default clone is from master.

It's not.  `develop` is the default branch for Spack.

**Comment by DavidPoliakoff** [comment]
Hmmm, Cmake must be being especially clever in this invocation. I'll decleverize it.

**Comment by tgamblin** [comment]
```
$ git clone git@github.com:LLNL/spack.git
Cloning into 'spack'...
remote: Counting objects: 62032, done.
remote: Compressing objects: 100% (76/76), done.
remote: Total 62032 (delta 36), reused 4 (delta 4), pack-reused 61948
Receiving objects: 100% (62032/62032), 22.61 MiB | 6.37 MiB/s, done.
Resolving deltas: 100% (29617/29617), done.
Checking connectivity... done.
$ cd spack
$ git branch
* develop
```
