### ISSUE TITLE
Installation issue: openmpi

### ISSUE THREAD

**Issue by BenWibking** [LLNL/spack#39518]
### Steps to reproduce the issue

```console
$ spack spec -I <spec>
Input spec
--------------------------------
 -   openmpi

Concretized
--------------------------------
 -   cz2nxyo  openmpi@4.1.5%apple-clang@14.0.3~atomics~cuda~cxx~cxx_exceptions~gpfs~internal-hwloc~internal-pmix~java~legacylaunchers~lustre~memchecker~openshmem~orterunprefix+romio+rsh~singularity+static+vt+wrapper-rpath build_system=autotools fabrics=none schedulers=none arch=darwin-ventura-m1
[+]  bmsack4      ^gnuconfig@2022-09-17%apple-clang@14.0.3 build_system=generic arch=darwin-ventura-m1
[+]  yynuklg      ^hwloc@2.9.1%apple-clang@14.0.3~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl~pci~rocm build_system=autotools libs=shared,static arch=darwin-ventura-m1
[+]  7dmviea          ^libxml2@2.10.3%apple-clang@14.0.3~python build_system=autotools arch=darwin-ventura-m1
[+]  njaeiaj              ^libiconv@1.17%apple-clang@14.0.3 build_system=autotools libs=shared,static arch=darwin-ventura-m1
[+]  c2ytrif              ^xz@5.4.1%apple-clang@14.0.3~pic build_system=autotools libs=shared,static arch=darwin-ventura-m1
[+]  eixs23r          ^ncurses@6.4%apple-clang@14.0.3~symlinks+termlib abi=none build_system=autotools arch=darwin-ventura-m1
[e]  nb5wwiq      ^openssh@9.0p1%apple-clang@14.0.3+gssapi build_system=autotools arch=darwin-ventura-m1
[+]  mfkjxkh      ^perl@5.38.0%apple-clang@14.0.3+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=darwin-ventura-m1
[+]  vq3xak6          ^berkeley-db@18.1.40%apple-clang@14.0.3+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=darwin-ventura-m1
[+]  okfdaso          ^bzip2@1.0.8%apple-clang@14.0.3~debug~pic+shared build_system=generic arch=darwin-ventura-m1
[e]  tj5yi5t              ^diffutils@2.8.1%apple-clang@14.0.3 build_system=autotools arch=darwin-ventura-m1
[+]  me2iznt          ^gdbm@1.23%apple-clang@14.0.3 build_system=autotools arch=darwin-ventura-m1
[+]  kdegqyh              ^readline@8.2%apple-clang@14.0.3 build_system=autotools patches=bbf97f1 arch=darwin-ventura-m1
[+]  5z42itc      ^pkgconf@1.9.5%apple-clang@14.0.3 build_system=autotools arch=darwin-ventura-m1
[+]  uzs3646      ^pmix@4.2.4%apple-clang@14.0.3~docs+pmi_backwards_compatibility~python~restful build_system=autotools arch=darwin-ventura-m1
[+]  4sqm3jc          ^libevent@2.1.12%apple-clang@14.0.3+openssl build_system=autotools arch=darwin-ventura-m1
[+]  7c3c4tb              ^openssl@3.1.2%apple-clang@14.0.3~docs+shared build_system=generic certs=mozilla arch=darwin-ventura-m1
[+]  jp6h6e4                  ^ca-certificates-mozilla@2023-05-30%apple-clang@14.0.3 build_system=generic arch=darwin-ventura-m1
[+]  fpffuzv      ^zlib-ng@2.1.3%apple-clang@14.0.3+compat+opt build_system=autotools patches=86c3f5b arch=darwin-ventura-m1

```

### Error message

<details><summary>Error message</summary>

<pre>
==> Installing openmpi-4.1.5-cz2nxyocywogdp5tz6hocsov2w2txuos [18/18]
==> No binary for openmpi-4.1.5-cz2nxyocywogdp5tz6hocsov2w2txuos found: installing from source
==> Using cached archive: /Users/benwibking/spack/var/spack/cache/_source-cache/archive/a6/a640986bc257389dd379886fdae6264c8cfa56bc98b71ce3ae3dfbd8ce61dbe3.tar.bz2
==> No patches needed for openmpi
==> openmpi: Executing phase: 'autoreconf'
==> Error: InstallError: OpenMPI requires both C and Fortran compilers!

/Users/benwibking/spack/var/spack/repos/builtin/packages/openmpi/package.py:901, in die_without_fortran:
        898        # dependencies depends_on('mpi'), require Fortran compiler to
        899        # avoid delayed build errors in dependents.
        900        if (self.compiler.f77 is None) and (self.compiler.fc is None):
  >>    901            raise InstallError("OpenMPI requires both C and Fortran compilers!")

See build log for details:
  /tmp/benwibking/spack-stage/spack-stage-openmpi-4.1.5-cz2nxyocywogdp5tz6hocsov2w2txuos/spack-build-out.txt
</pre></details>

### Information on your system

* **Spack:** 0.21.0.dev0 (b2b00df5cc9dcae2bc6e73c24df9cb4e0f37b19d)
* **Python:** 3.11.4
* **Platform:** darwin-ventura-m1
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/12381811/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/12381812/spack-build-out.txt)

`➜  ~ spack maintainers openmpi`
@hppritcha  @naughtont3

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by BenWibking** [comment]
I should add that I have `gfortran` installed on this machine:
```
➜  ~ which gfortran
/opt/homebrew/bin/gfortran
➜  ~ spack compiler find
==> Found no new compilers
==> Compilers are defined in the following files:
    /Users/benwibking/.spack/darwin/compilers.yaml
```

My compilers.yaml file is here:
[compilers.yaml.txt](https://github.com/spack/spack/files/12381845/compilers.yaml.txt)

**Comment by hppritcha** [comment]
I can't tell from the info provided where the install failed.  Was the failure in building a dependency?  Or in the configure/compile/install of Open MPI itself?

**Comment by hppritcha** [comment]
oh never mind I didn't click around enough.

**Comment by hppritcha** [comment]
you will want to rerun the spack install with the ```--verbose``` option to install.  It looks like the open mpi configure isn't liking the gfortran  specified in your compilers.yaml for some reason.

**Comment by BenWibking** [comment]
I think I know what's going on. The default compiler doesn't have a Fortran compiler associated with it, but it doesn't fall back to one of the other Fortran compilers that are listed:
```
compilers:
- compiler:
    spec: apple-clang@14.0.3
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: null
      fc: null
    flags: {}
    operating_system: ventura
    target: aarch64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: clang@16.0.1
    paths:
      cc: /opt/homebrew/opt/llvm/bin/clang
      cxx: /opt/homebrew/opt/llvm/bin/clang++
      f77: /opt/homebrew/bin/gfortran
      fc: /opt/homebrew/bin/gfortran
    flags: {}
    operating_system: ventura
    target: aarch64
    modules: []
    environment: {}
    extra_rpaths: []
```

**Comment by BenWibking** [comment]
If I add the path to gfortran to the first compiler `apple-clang@14.0.3`, then it builds successfully.

**Comment by tiannh7** [comment]
Hi all,

Unfortunately, I encountered some similar errors when installing openmpi using spack, but I couldn't solve them well with the previous methods. I don't know why these problems occur. Any advice will be greatly appreciated.

Ning.

`$ cat ~/.spack/linux/compilers.yaml`
compilers:
- compiler:
    spec: gcc@=11.4.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: ubuntu22.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []

`$ gcc --version`
  gcc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
  Copyright (C) 2021 Free Software Foundation, Inc.
  This is free software; see the source for copying conditions.  There is NO
  warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.


`$ gfortran --version`
GNU Fortran (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

`$ sudo /share/spack/bin/spack install openmpi %gcc`

==> Installing openmpi-5.0.3-byktpllxizlzf3d5jimr6jbhpws27qyu [34/34]
==> No binary for openmpi-5.0.3-byktpllxizlzf3d5jimr6jbhpws27qyu found: installing from source
==> Using cached archive: /share/spack/var/spack/cache/_source-cache/archive/99/990582f206b3ab32e938aa31bbf07c639368e4405dca196fabe7f0f76eeda90b.tar.bz2
==> No patches needed for openmpi
==> openmpi: Executing phase: 'autoreconf'
==> Error: InstallError: OpenMPI requires both C and Fortran compilers!

/share/spack/var/spack/repos/builtin/packages/openmpi/package.py:974, in die_without_fortran:
        971        # avoid delayed build errors in dependents.
        972        if (self.compiler.f77 is None) and (self.compiler.fc is None):
        973            #raise InstallError(self.compiler.f77, self.compiler.fc, self.compiler.gcc, self.compiler.g++)
  >>    974            raise InstallError("OpenMPI requires both C and Fortran compilers!")

See build log for details:
  /tmp/root/spack-stage/spack-stage-openmpi-5.0.3-byktpllxizlzf3d5jimr6jbhpws27qyu/spack-build-out.txt


sudo cat /tmp/root/spack-stage/spack-stage-openmpi-5.0.3-byktpllxizlzf3d5jimr6jbhpws27qyu/spack-build-out.txt
==> openmpi: Executing phase: 'autoreconf'
