### ISSUE TITLE
Cloning git submodule with depth=1 leads to "no such remote ref" error

### ISSUE THREAD

**Issue by junghans** [LLNL/spack#3956]
When cloning git submodule inside spack with depth=1 (now default), one gets an error like:
```
error: no such remote ref 91fdf75b82b55b25dd9e79cc85e32e6fdb9e4f53
Fetched in submodule path 'cinch', but it did not contain 91fdf75b82b55b25dd9e79cc85e32e6fdb9e4f53. Direct fetching of that commit failed.
```
when the required hash in the submodule isn't the current HEAD of master.

**Comment by adamjstewart** [comment]
Could be related to #3779. Can you try undoing that PR and see if it fixes the problem? What package does this occur for?

**Comment by junghans** [comment]
I found this when trying to remove the hack for #3779.

**Comment by hashar** [comment]
The reason is git fetch the sha1 of the submodule and not a reference. That might not be allowed on the server.  With `GIT_TRACE=1` you would see something like:
```
trace: built-in: git 'fetch' 'origin' '--depth=1' 91fdf75b82b55b25dd9e79cc85e32e6fdb9e4f53
```

The server side would need:
```
uploadpack.allowReachableSHA1InWant=true
```
