### ISSUE TITLE
Installation issue: openssh ^zlib

### ISSUE THREAD

**Issue by blue42u** [LLNL/spack#39599]
### Steps to reproduce the issue

```console
$ spack spec openssh ^zlib
Input spec
--------------------------------
 -   openssh
 -       ^zlib

Concretized
--------------------------------
 -   openssh@9.3p1%gcc@11.4.0+gssapi build_system=autotools arch=linux-ubuntu22.04-zen2
[+]      ^krb5@1.20.1%gcc@11.4.0+shared build_system=autotools arch=linux-ubuntu22.04-zen2
[+]          ^bison@3.8.2%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-zen2
[+]              ^m4@1.4.19%gcc@11.4.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-ubuntu22.04-zen2
[+]                  ^libsigsegv@2.14%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-zen2
[+]          ^diffutils@3.9%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-zen2
[+]              ^libiconv@1.17%gcc@11.4.0 build_system=autotools libs=shared,static arch=linux-ubuntu22.04-zen2
[+]          ^findutils@4.9.0%gcc@11.4.0 build_system=autotools patches=440b954 arch=linux-ubuntu22.04-zen2
[+]          ^gettext@0.21.1%gcc@11.4.0+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=linux-ubuntu22.04-zen2
[+]              ^bzip2@1.0.8%gcc@11.4.0~debug~pic+shared build_system=generic arch=linux-ubuntu22.04-zen2
[+]              ^libxml2@2.10.3%gcc@11.4.0~python build_system=autotools arch=linux-ubuntu22.04-zen2
[+]              ^tar@1.34%gcc@11.4.0 build_system=autotools zip=pigz arch=linux-ubuntu22.04-zen2
[+]                  ^pigz@2.7%gcc@11.4.0 build_system=makefile arch=linux-ubuntu22.04-zen2
[+]                  ^zstd@1.5.5%gcc@11.4.0+programs build_system=makefile compression=none libs=shared,static arch=linux-ubuntu22.04-zen2
[+]              ^xz@5.4.1%gcc@11.4.0~pic build_system=autotools libs=shared,static arch=linux-ubuntu22.04-zen2
[+]      ^libedit@3.1-20210216%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-zen2
[+]          ^pkgconf@1.9.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-zen2
[+]      ^libxcrypt@4.4.35%gcc@11.4.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-ubuntu22.04-zen2
[+]          ^perl@5.38.0%gcc@11.4.0+cpanm+opcode+open+shared+threads build_system=generic arch=linux-ubuntu22.04-zen2
[+]              ^berkeley-db@18.1.40%gcc@11.4.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu22.04-zen2
[+]              ^gdbm@1.23%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-zen2
[+]                  ^readline@8.2%gcc@11.4.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu22.04-zen2
[+]      ^ncurses@6.4%gcc@11.4.0~symlinks+termlib abi=none build_system=autotools arch=linux-ubuntu22.04-zen2
[+]      ^openssl@3.1.2%gcc@11.4.0~docs+shared build_system=generic certs=mozilla arch=linux-ubuntu22.04-zen2
[+]          ^ca-certificates-mozilla@2023-05-30%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-zen2
[+]      ^zlib@1.3%gcc@11.4.0+optimize+pic+shared build_system=makefile arch=linux-ubuntu22.04-zen2
```

### Error message

<details><summary>Error message</summary>

<pre>
==> Installing openssh-9.3p1-alrxnaegwjyxxe4ynbt7g5ql4cthkz23 [26/26]
==> No binary for openssh-9.3p1-alrxnaegwjyxxe4ynbt7g5ql4cthkz23 found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/e9/e9baba7701a76a51f3d85a62c383a3c9dcd97fa900b859bc7db114c1868af8a8.tar.gz
==> Ran patch() for openssh
==> openssh: Executing phase: 'autoreconf'
==> openssh: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/tmp/root/spack-stage/spack-stage-openssh-9.3p1-alrxnaegwjyxxe4ynbt7g5ql4cthkz23/spack-src/configure' '--prefix=/opt/spack/opt/spack/linux-ubuntu22.04-zen2/gcc-11.4.0/openssh-9.3p1-alrxnaegwjyxxe4ynbt7g5ql4cthkz23' '--with-privsep-path=/opt/spack/opt/spack/linux-ubuntu22.04-zen2/gcc-11.4.0/openssh-9.3p1-alrxnaegwjyxxe4ynbt7g5ql4cthkz23/var/empty' '--with-kerberos5=/opt/spack/opt/spack/linux-ubuntu22.04-zen2/gcc-11.4.0/krb5-1.20.1-bp3lic45k3lv42rtnczhzkv5vjfiwpmz'

1 error found in build log:
     202    checking for getspnam... yes
     203    checking for library containing basename... none required
     204    checking for zlib... yes
     205    checking for zlib.h... yes
     206    checking for deflate in -lz... yes
     207    checking for possibly buggy zlib... yes
  >> 208    configure: error: *** zlib too old - check config.log ***
     209    Your reported zlib version has known security problems.  It's possible your
     210    vendor has fixed these problems without changing the version number.  If you
     211    are sure this is the case, you can disable the check by running
     212    "./configure --without-zlib-version-check".
     213    If you are in doubt, upgrade zlib to version 1.2.3 or greater.
     214    See http://www.gzip.org/zlib/ for details.

See build log for details:
  /tmp/root/spack-stage/spack-stage-openssh-9.3p1-alrxnaegwjyxxe4ynbt7g5ql4cthkz23/spack-build-out.txt
</pre></details>

### Information on your system

* **Spack:** 0.21.0.dev0 (fd5a8b20750bfcc064dbbeb2db944d594b3f4652)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-zen2
* **Concretizer:** clingo

### Additional information

[spack-build-out.txt](https://github.com/spack/spack/files/12422962/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/12422964/spack-build-env.txt)
[config.log](https://github.com/spack/spack/files/12422965/config.log)

@bernhardkaindl

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by bernhardkaindl** [comment]
https://github.com/spack/spack/pull/39605 fixes this build issue.

@blue42u In case it's not reviewed/merged soon, ping `spack` developers to review and merge it,
e.g. alalazo or other PR reviewers.

**Comment by bernhardkaindl** [comment]
After review, I expect this is fixed by newer versions of `openssh` that have been added since.
