### ISSUE TITLE
`intel-oneapi-mkl` `_find_mkl_libs` returns errors when built with external `hpcx-mpi`

### ISSUE THREAD

**Issue by lorisercole** [LLNL/spack#39629]
### Steps to reproduce the issue

```console
$ spack spec -I intel-oneapi-mkl@2023.2.0%gcc@13.1.0+cluster
Input spec
--------------------------------
 -   intel-oneapi-mkl@2023.2.0%gcc@13.1.0+cluster

Concretized
--------------------------------
[+]  intel-oneapi-mkl@2023.2.0%gcc@13.1.0+cluster+envmods~ilp64+shared build_system=generic mpi_family=none threads=none arch=linux-almalinux8-x86_64_v3
[e]      ^hpcx-mpi@2.15%gcc@13.1.0 build_system=generic arch=linux-almalinux8-x86_64_v3
[+]      ^intel-tbb@2021.9.0%gcc@13.1.0~ipo+shared+tm build_system=cmake build_type=Release cxxstd=default generator=make patches=12a9c3e arch=linux-almalinux8-x86_64_v3
[+]          ^cmake@3.26.3%gcc@13.1.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-almalinux8-x86_64_v3
[+]              ^curl@8.1.2%gcc@13.1.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-almalinux8-x86_64_v3
[+]                  ^nghttp2@1.52.0%gcc@13.1.0 build_system=autotools arch=linux-almalinux8-x86_64_v3
[+]                  ^openssl@3.1.2%gcc@13.1.0~docs+shared build_system=generic certs=mozilla arch=linux-almalinux8-x86_64_v3
[+]                      ^ca-certificates-mozilla@2023-05-30%gcc@13.1.0 build_system=generic arch=linux-almalinux8-x86_64_v3
[+]                      ^perl@5.38.0%gcc@13.1.0+cpanm+opcode+open+shared+threads build_system=generic arch=linux-almalinux8-x86_64_v3
[+]                          ^berkeley-db@18.1.40%gcc@13.1.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-almalinux8-x86_64_v3
[+]                          ^bzip2@1.0.8%gcc@13.1.0~debug~pic+shared build_system=generic arch=linux-almalinux8-x86_64_v3
[+]                          ^gdbm@1.23%gcc@13.1.0 build_system=autotools arch=linux-almalinux8-x86_64_v3
[+]                              ^readline@8.2%gcc@13.1.0 build_system=autotools patches=bbf97f1 arch=linux-almalinux8-x86_64_v3
[+]              ^ncurses@6.4%gcc@13.1.0~symlinks+termlib abi=none build_system=autotools arch=linux-almalinux8-x86_64_v3
[+]              ^zlib@1.2.13%gcc@13.1.0+optimize+pic+shared build_system=makefile arch=linux-almalinux8-x86_64_v3
[+]          ^gmake@4.4.1%gcc@13.1.0~guile build_system=autotools arch=linux-almalinux8-x86_64_v3
[+]          ^hwloc@2.9.1%gcc@13.1.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-almalinux8-x86_64_v3
[+]              ^libpciaccess@0.17%gcc@13.1.0 build_system=autotools arch=linux-almalinux8-x86_64_v3
[+]                  ^libtool@2.4.7%gcc@13.1.0 build_system=autotools arch=linux-almalinux8-x86_64_v3
[+]                      ^m4@1.4.19%gcc@13.1.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-almalinux8-x86_64_v3
[+]                          ^diffutils@3.9%gcc@13.1.0 build_system=autotools arch=linux-almalinux8-x86_64_v3
[+]                          ^libsigsegv@2.14%gcc@13.1.0 build_system=autotools arch=linux-almalinux8-x86_64_v3
[+]                  ^util-macros@1.19.3%gcc@13.1.0 build_system=autotools arch=linux-almalinux8-x86_64_v3
[+]              ^libxml2@2.10.3%gcc@13.1.0~python build_system=autotools arch=linux-almalinux8-x86_64_v3
[+]                  ^libiconv@1.17%gcc@13.1.0 build_system=autotools libs=shared,static arch=linux-almalinux8-x86_64_v3
[+]                  ^xz@5.4.1%gcc@13.1.0~pic build_system=autotools libs=shared,static arch=linux-almalinux8-x86_64_v3
[+]              ^pkgconf@1.9.5%gcc@13.1.0 build_system=autotools arch=linux-almalinux8-x86_64_v3
```

### Error message

The installation of `intel-oneapi-mkl` with the external mpi library `hpcx-mpi` goes fine, but I get this error at the end:
```console
==> Error: Unable to recursively locate hpcx-mpi libraries in /opt/hpcx-v2.15-gcc-MLNX_OFED_LINUX-5-redhat8-cuda12-gdrcopy2-nccl2.17-x86_64/ompi
```

<details><summary>Error message</summary>

<pre>
[+] /opt/hpcx-v2.15-gcc-MLNX_OFED_LINUX-5-redhat8-cuda12-gdrcopy2-nccl2.17-x86_64/ompi (external hpcx-mpi-2.15-hqw4ptno4s5fj2ag2xdrlfhhn4fum6s3)
[+] /anfhome/spack/opt/spack/[padded-to-128-chars]/linux-almalinux8-x86_64_v3/gcc-13.1.0/libpciaccess-0.17-k6pr7iqui4i22l7m6mpaq26qdztrpthi
[+] /anfhome/spack/opt/spack/[padded-to-128-chars]/linux-almalinux8-x86_64_v3/gcc-13.1.0/libiconv-1.17-hprojhmvqalubhdgny463pur3nj4gogt
[+] /anfhome/spack/opt/spack/[padded-to-128-chars]/linux-almalinux8-x86_64_v3/gcc-13.1.0/xz-5.4.1-3xx6zn3ptvpmoghmyfsiky26v4jybtte
[+] /anfhome/spack/opt/spack/[padded-to-128-chars]/linux-almalinux8-x86_64_v3/gcc-13.1.0/zlib-1.2.13-4t7smezzrvygfavczhttqghrkuxmcbkc
[+] /anfhome/spack/opt/spack/[padded-to-128-chars]/linux-almalinux8-x86_64_v3/gcc-13.1.0/ncurses-6.4-hhgoarpk3xcufhdmamyvdcujzge5p7rw
[+] /anfhome/spack/opt/spack/[padded-to-128-chars]/linux-almalinux8-x86_64_v3/gcc-13.1.0/libxml2-2.10.3-6ax6xvlejj4wchyymh7kgrqcu322cfgq
[+] /anfhome/spack/opt/spack/[padded-to-128-chars]/linux-almalinux8-x86_64_v3/gcc-13.1.0/hwloc-2.9.1-qj7jbriwjowxa7vyvbo5dzq3745ixbdp
[+] /anfhome/spack/opt/spack/[padded-to-128-chars]/linux-almalinux8-x86_64_v3/gcc-13.1.0/intel-tbb-2021.9.0-c53rmbpgvqgzwsyixdbn7lez452pee7p
==> Installing intel-oneapi-mkl-2023.2.0-rd46lx5i6tfb2w7ttqvtcot2fct25y6x [10/10]
==> No binary for intel-oneapi-mkl-2023.2.0-rd46lx5i6tfb2w7ttqvtcot2fct25y6x found: installing from source
==> Using cached archive: /anfhome/spack/var/spack/cache/_source-cache/archive/4a/4a0d93da85a94d92e0ad35dc0fc3b3ab7f040bd55ad374c4d5ec81a57a2b872b
==> No patches needed for intel-oneapi-mkl
==> intel-oneapi-mkl: Executing phase: 'install'
==> intel-oneapi-mkl: Successfully installed intel-oneapi-mkl-2023.2.0-rd46lx5i6tfb2w7ttqvtcot2fct25y6x
  Stage: 3.85s.  Install: 2m 59.62s.  Post-install: 44.14s.  Total: 3m 49.35s
[+] /anfhome/spack/opt/spack/[padded-to-128-chars]/linux-almalinux8-x86_64_v3/gcc-13.1.0/intel-oneapi-mkl-2023.2.0-rd46lx5i6tfb2w7ttqvtcot2fct25y6x
==> Error: Unable to recursively locate hpcx-mpi libraries in /opt/hpcx-v2.15-gcc-MLNX_OFED_LINUX-5-redhat8-cuda12-gdrcopy2-nccl2.17-x86_64/ompi
</pre></details>

This looks similar to #38238, and it is caused by #37386.
@rscohn2

A few times I have also gotten the same error when building a package that depended on this `intel-oneapi-mkl` build, causing the installation to fail.

### Information on your system

Notice that I'm already applying the #39625 fix to avoid the [RuntimeError](https://github.com/spack/spack/blob/8a08f09ac0208718feb78077288b4b0eeab3597a/var/spack/repos/builtin/packages/intel-oneapi-mkl/package.py#L207).

```
* **Spack:** 0.21.0.dev0 (2a2fcde7e29034af69e8400c44f4e9679dbe564f)
* **Python:** 3.6.8
* **Platform:** linux-almalinux8-zen2
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by rscohn2** [comment]
This looks different than https://github.com/spack/spack/issues/38238. It occurs when there is an external MKL and spack does not know about the MPI dependence. The problem you are seeing looks like an issue in the configuration of the external hpcx-mpi. Maybe you could try:
```
spack install hpl ^hpcx-mpi
```
and see if it has the same problem

**Comment by lorisercole** [comment]
Your suggestion worked fine. But the problem would arise whenever `intel-oneapi-mkl` is installed with the `+cluster` variant, for example if I do this:
```
spack install hpl ^hpcx-mpi ^intel-oneapi-mkl+cluster
```
I get
```python
==> hpl: Executing phase: 'autoreconf'
==> hpl: Executing phase: 'configure'
==> Error: NoLibrariesError: Unable to recursively locate hpcx-mpi libraries in /opt/hpcx-v2.15-gcc-MLNX_OFED_LINUX-5-redhat8-cuda12-gdrcopy2-nccl2.17-x86_64/ompi

/anfhome/spack/var/spack/repos/builtin/packages/intel-oneapi-mkl/package.py:230, in _find_mkl_libs:
        227        # spec, then MKL is externally installed and application must
        228        # link with MPI libaries
        229        if self.spec.satisfies("+cluster ^mpi"):
  >>    230            resolved_libs = resolved_libs + self.spec["mpi"].libs
        231        return resolved_libs

See build log for details:
  /mnt/scratch/root/spack-stage/spack-stage-hpl-2.3-33tgxwnqxepo3dwjygtj3yrbzbos4lbz/spack-build-out.txt
```

**Comment by rscohn2** [comment]
I see. hpcx-mpi provides mpi, but it does not supply any libraries because it relies on the compiler wrappers to add them. I will look into how to handle it.
