### ISSUE TITLE
boost 1.64.0 not stable

### ISSUE THREAD

**Issue by svenevs** [LLNL/spack#3963]
I see this was added 2 days ago, it should probably not be the preferred version.  Or at the very least, give a warning if `+mpi+python` detected?

There's something weird going on with `mpi` and `python` asked for at the same time.  If I ask for both, neither py2 or py3 can build.  `~mpi+python` builds _for both_, though.

```
/tmp/sven/spack-stage/spack-stage-eUP7Zi/boost_1_64_0/spack-build.out:194:./boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory
/tmp/sven/spack-stage/spack-stage-eUP7Zi/boost_1_64_0/spack-build.out:210:./boost/mpi/python/serialize.hpp:404:16: error: 'make_array' is not a member of 'boost::serialization'
/tmp/sven/spack-stage/spack-stage-eUP7Zi/boost_1_64_0/spack-build.out:214:./boost/mpi/python/serialize.hpp:445:9: error: 'make_array' is not a member of 'boost::serialization'
/tmp/sven/spack-stage/spack-stage-eUP7Zi/boost_1_64_0/spack-build.out:14210:./boost/python/detail/wrap_python.hpp:50:23: fatal error: pyconfig.h: No such file or directory
```

It seems this [is a known issue](https://svn.boost.org/trac/boost/ticket/12516), noting from the last comment that `boost@1.63.0` works fine.  I have verified this, the `boost@1.63.0+python+mpi` works for both python2 and 3.

**Comment by davydden** [comment]
feel free to contribute a PR to make 1.63 preferred and add a comment  why 1.64 isn't

**Comment by svenevs** [comment]
I guess it was more a question. I'm not sure if it's a me problem or not.  Want it anyway?

**Comment by davydden** [comment]
i can try building on ubuntu tomorrow and see if I can reproduce it. If so, then we can make 1.63 preferred

**Comment by svenevs** [comment]
Ok i'll open it so you can just decide then and there.

**Comment by MathiasMen** [comment]
Having the same problem but during installation of `dealii` at the `CMake` phase. Besides the `make_array` issue already mentioned by @svenevs, I also encounter an error along the lines of `./boost/mpi/detail/mpi_datatype_primitive.hpp:28:51: fatal error: boost/serialization/detail/get_data.hpp: No such file or directory`.

**Comment by ax3l** [comment]
boost 1.64 also seems troublesome with `math` and CUDA 8, see
- https://github.com/dmlc/mxnet/issues/2672
- https://github.com/ComputationalRadiationPhysics/picongpu/issues/2048
- CUDA bug report id 1928813 (private, see [this example](https://github.com/ComputationalRadiationPhysics/picongpu/issues/2048#issuecomment-302337805))

**Comment by scheibelp** [comment]
Boost `1.64.0` is no longer currently preferred by Spack and the associated `package.py` has a note referring to this thread, so I'm going to close this.
