### ISSUE TITLE
Gitlab job pruning doesn't track dependencies correctly

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#39656]
Suppose we have

```
A depends on B depends on C
```

and A requires a rebuild because the package was changed, and C requires a rebuild because the binary/spec.json has gone missing, then Spack schedules the jobs A anc C concurrently, and A will fail because it cannot download the binary for C, which is not yet available.

This is due to keeping track of direct deps only:

https://github.com/spack/spack/blob/98daf5b7ecc74152b36c77051c58f2ed0ada1670/lib/spack/spack/ci.py#L1039-L1055

Instead, pruning should be done on the DAG structure, where deleting a node should either be implemented as marking that node, or as actually deleting the node and restoring direct edges between all its parents and all its children.

Doing pruning on the DAG also makes it more generic, and easier to add new CI backends. Right now pruning happens after dividing jobs into "stages" which is a weird concept unique to Gitlab.

**Comment by haampie** [comment]
@kwryankrattiger is this still relevant?

**Comment by kwryankrattiger** [comment]
Yes and no, it should be resolved soon. @scottwittenburg had this fixed in a previous PR but it got hung up on some reviews. He is rebasing it now and stripping it the controversial parts.
