### ISSUE TITLE
Installation issue: libelf

### ISSUE THREAD

**Issue by BenWibking** [LLNL/spack#39827]
### Steps to reproduce the issue

```console
$ spack spec -I <spec>
Input spec
--------------------------------
 -   libelf

Concretized
--------------------------------
 -   libelf@0.8.13%apple-clang@14.0.3 build_system=autotools arch=darwin-ventura-m1
[e]      ^autoconf@2.71%apple-clang@14.0.3 build_system=autotools arch=darwin-ventura-m1
[e]      ^automake@1.16.5%apple-clang@14.0.3 build_system=autotools arch=darwin-ventura-m1
[+]      ^gnuconfig@2022-09-17%apple-clang@14.0.3 build_system=generic arch=darwin-ventura-m1
[e]      ^libtool@2.4.7%apple-clang@14.0.3 build_system=autotools arch=darwin-ventura-m1
[e]      ^m4@1.4.6%apple-clang@14.0.3+sigsegv build_system=autotools arch=darwin-ventura-m1
```

### Error message

<details><summary>Error message</summary>

<pre>
==> Installing libelf-0.8.13-6tysckniszts6eyfnzxn5mobotkoc5it [6/6]
==> No binary for libelf-0.8.13-6tysckniszts6eyfnzxn5mobotkoc5it found: installing from source
==> Using cached archive: /Users/benwibking/spack/var/spack/cache/_source-cache/archive/59/591a9b4ec81c1f2042a97aa60564e0cb79d041c52faa7416acb38bc95bd2c76d.tar.gz
==> No patches needed for libelf
==> libelf: Executing phase: 'autoreconf'
==> Error: ProcessError: Command exited with status 1:
    '/opt/homebrew/bin/autoreconf' '-ivf'

2 errors found in build log:
     10    autoreconf: Entering directory '.'
     11    autoreconf: configure.in: not using Gettext
     12    autoreconf: configure.in: not using aclocal
     13    autoreconf: configure.in: tracing
     14    /Library/Developer/CommandLineTools/usr/bin/m4: unrecognized option `--gnu'
     15    Try `/Library/Developer/CommandLineTools/usr/bin/m4 --help' for more information.
  >> 16    autom4te: error: /usr/bin/m4 failed with exit status: 1
  >> 17    autoreconf: error: /opt/homebrew/Cellar/autoconf/2.71/bin/autoconf failed with exit status: 1

See build log for details:
  /tmp/benwibking/spack-stage/spack-stage-libelf-0.8.13-6tysckniszts6eyfnzxn5mobotkoc5it/spack-build-out.txt

</pre></details>

### Information on your system

* **Spack:** 0.21.0.dev0 (12bc4cf0932837f1c8206c1525f961548561a6c3)
* **Python:** 3.11.4
* **Platform:** darwin-ventura-m1
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/12527435/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/12527436/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by aumuell** [comment]
It seems that you have your spack set up to use `autoconf` and `automake` from homebrew combined with `m4` from Apple. I think this is wrong: the `autoconf.rb` from homebrew lists `m4` as a dependency which is meant to be resolved from homebrew. Otherwise it would have used `uses_from_macos "m4"` instead of `depends_on "m4"`.

**Comment by BenWibking** [comment]
Yes, that looks like it. `spack external find` added `autoconf` and `automake` from homebrew and `m4` from the system installation to my packages.yaml file.

I removed the Apple `m4` from packages.yaml and replaced it with:
```
  m4:
    externals:
    - spec: m4@1.4.19
      prefix: /opt/homebrew/opt/m4
```

However, `spack install libelf` still picks up the Apple-installed `m4`:
```
 ~ spack install libelf
[+] /opt/homebrew (external autoconf-2.71-3p5a3bhhnfglg6oht2o4i7adjdt544hx)
[+] /opt/homebrew (external automake-1.16.5-6o52zbft6c5lx5apb3brlwjywta4y55x)
[+] /Users/benwibking/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/gnuconfig-2022-09-17-bmsack4fvthixz7gbtrvkvhbw4xlf63t
[+] /opt/homebrew (external libtool-2.4.7-lshk6jzr5ejorzpnp2ma66yrg5parzy6)
[+] /usr (external m4-1.4.6-zt4pc7zbbqr24f6jpsnrxogqrwvf2rhl)
==> Installing libelf-0.8.13-6tysckniszts6eyfnzxn5mobotkoc5it [6/6]
==> No binary for libelf-0.8.13-6tysckniszts6eyfnzxn5mobotkoc5it found: installing from source
==> Using cached archive: /Users/benwibking/spack/var/spack/cache/_source-cache/archive/59/591a9b4ec81c1f2042a97aa60564e0cb79d041c52faa7416acb38bc95bd2c76d.tar.gz
==> No patches needed for libelf
==> libelf: Executing phase: 'autoreconf'
==> Error: ProcessError: Command exited with status 1:
    '/opt/homebrew/bin/autoreconf' '-ivf'

2 errors found in build log:
     10    autoreconf: Entering directory '.'
     11    autoreconf: configure.in: not using Gettext
     12    autoreconf: configure.in: not using aclocal
     13    autoreconf: configure.in: tracing
     14    /Library/Developer/CommandLineTools/usr/bin/m4: unrecognized option `--gnu'
     15    Try `/Library/Developer/CommandLineTools/usr/bin/m4 --help' for more information.
  >> 16    autom4te: error: /usr/bin/m4 failed with exit status: 1
  >> 17    autoreconf: error: /opt/homebrew/Cellar/autoconf/2.71/bin/autoconf failed with exit status: 1

See build log for details:
  /tmp/benwibking/spack-stage/spack-stage-libelf-0.8.13-6tysckniszts6eyfnzxn5mobotkoc5it/spack-build-out.txt
```
I did `spack clean` and `spack clean -m` just in case, but it still uses the wrong `m4`.

**Comment by aumuell** [comment]
Perhaps spack tried to reuse installed packages and `spack install --fresh libelf` makes it rethink its decision?

**Comment by BenWibking** [comment]
> Perhaps spack tried to reuse installed packages and `spack install --fresh libelf` makes it rethink its decision?

That fixed it. Thanks!
