### ISSUE TITLE
Ipopt build error with Linux Clang

### ISSUE THREAD

**Issue by futuretristan** [LLNL/spack#3983]
I'm now on an Ubuntu machine working with Clang. After implementing the compiler wrapper fix proposed in #3903, Ipopt still did not compile but showed the error 
`"don't have function for random number generator"`. 

A search revealed that this error comes from the Linux version of Clang (see [here](https://github.com/JuliaOpt/Ipopt.jl/issues/13) and scroll to the end). The suggestion there is to add `coin_skip_warn_cxxflags=yes` to the configure call.

 In file
https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/ipopt/package.py
you see the following section:
```
configure_args = [
  "--prefix=%s" % prefix,
  "--with-mumps-incdir=%s" % mumps_dir.include,
  "--with-mumps-lib=%s" % mumps_libcmd,
  "--enable-shared",
  "--with-blas-incdir=%s" % blas_dir.include,
  "--with-blas-lib=%s" % blas_lib,
  "--with-lapack-incdir=%s" % lapack_dir.include,
  "--with-lapack-lib=%s" % lapack_lib
  ]
```

If this section is extended to account for the additional flag as
```
configure_args = [
  "--prefix=%s" % prefix,
  "--with-mumps-incdir=%s" % mumps_dir.include,
  "--with-mumps-lib=%s" % mumps_libcmd,
  "--enable-shared",
  "coin_skip_warn_cxxflags=yes",
  "--with-blas-incdir=%s" % blas_dir.include,
  "--with-blas-lib=%s" % blas_lib,
  "--with-lapack-incdir=%s" % lapack_dir.include,
  "--with-lapack-lib=%s" % lapack_lib
  ]
```
then the build works fine for me. Note that this additional flag does not have the preceding '--'.

**Comment by davydden** [comment]
@futuretristan i think you would have spend exactly the same amount of time actually implementing the fix in a new pull request instead of creating this issue :smile: . Feel free to do that. (fork spack, create a branch, modify+commit, open PR).

**Comment by futuretristan** [comment]
Now I'm getting nervous... I'll give it a try.

**Comment by davydden** [comment]
@futuretristan have a look at http://spack.readthedocs.io/en/latest/contribution_guide.html , especially Git Workflows.

**Comment by davydden** [comment]
p.s.

> Now I'm getting nervous...

no worries, it sounds more complicated than it actually is. And the workflow is roughly the same regardless of the project, be it Spack, your own C++ code, `dealii` or whatever else.

**Comment by scheibelp** [comment]
> i think you would have spend exactly the same amount of time actually implementing the fix in a new pull request instead of creating this issue

IMO, in general opening an issue is less of a hassle: even in this case where a solution was suggested, the user doesn't have to think about whether their fix is the right fix. So to be clear, I think there is no problem opening an issue and also no problem if the user wants to leave it at that. That being said: for a given package the user is likely to have a greater understanding of it than the Spack maintainers, so I definitely appreciate @futuretristan submitting a PR for it in this case.
