### ISSUE TITLE
Installation issue: glibc@2.29

### ISSUE THREAD

**Issue by kc9qey** [LLNL/spack#39846]
### Steps to reproduce the issue

```console
$ spack spec -I <spec>
...

[svcdeltaswmgt@dt-login03 0.17.1]$ spack spec -l glibc@2.29
Input spec
--------------------------------
 -   glibc@2.29

Concretized
--------------------------------
 -   szbrgl7  glibc@2.29%gcc@11.2.0 build_system=autotools arch=linux-rhel8-zen3
[e]  utqi4kl      ^bison@3.0.4%gcc@11.2.0 patches=b72914f arch=linux-rhel8-zen3
[+]  rpog4gt      ^gettext@0.21%gcc@11.2.0+bzip2+curses+git~libunistring+libxml2+tar+xz arch=linux-rhel8-zen3
[e]  baq45br          ^bzip2@1.0.6%gcc@11.2.0~debug~pic+shared arch=linux-rhel8-zen3
[+]  va3oiyg          ^libiconv@1.16%gcc@11.2.0 libs=shared,static arch=linux-rhel8-zen3
[+]  srqcix2          ^libxml2@2.9.13%gcc@11.2.0~python arch=linux-rhel8-zen3
[e]  iuw23ll              ^pkgconf@1.4.2%gcc@11.2.0 arch=linux-rhel8-zen3
[e]  myx5mku          ^ncurses@6.1.20180224%gcc@11.2.0~symlinks+termlib abi=6 arch=linux-rhel8-zen3
[e]  wdu5sij          ^tar@1.30%gcc@11.2.0 zip=pigz arch=linux-rhel8-zen3
[e]  d4nsvrr          ^xz@5.2.4%gcc@11.2.0~pic libs=shared,static arch=linux-rhel8-zen3
[+]  kma22vl      ^linux-headers@6.2.8%gcc@11.2.0 build_system=generic arch=linux-rhel8-zen3
[+]  rbcr3pz      ^perl@5.35.0%gcc@11.2.0+cpanm+shared+threads arch=linux-rhel8-zen3
[+]  hfm4k4r          ^berkeley-db@18.1.40%gcc@11.2.0+cxx~docs+stl patches=b231fcc arch=linux-rhel8-zen3
[+]  5nndgyo          ^gdbm@1.19%gcc@11.2.0 arch=linux-rhel8-zen3
[+]  wrjusz5              ^readline@8.1%gcc@11.2.0 arch=linux-rhel8-zen3
[+]  mlefudp          ^zlib@1.2.11%gcc@11.2.0+optimize+pic+shared arch=linux-rhel8-zen3
[e]  i37hfbw      ^texinfo@6.5%gcc@11.2.0 patches=12f6edb,1732115 arch=linux-rhel8-zen3

[svcdeltaswmgt@dt-login03 0.17.1]$ 
[svcdeltaswmgt@dt-login03 0.17.1]$ 
```

### Error message

<details><summary>Error message</summary>

<pre>
...

[svcdeltaswmgt@dt-login03 0.17.1]$ spack install glibc@2.29
[+] /usr (external bison-3.0.4-utqi4klxy52sdps7ljpayuzfodbmns4n)
[+] /usr (external bzip2-1.0.6-baq45br2cxrqlvrupkipk7tdaw5fyxoh)
[+] /sw/spack/deltacpu-2022-03/apps/libiconv/1.16-gcc-11.2.0-va3oiyg
[+] /usr (external xz-5.2.4-d4nsvrrlesw2ss56bohqpbgiypipt6cv)
[+] /sw/spack/deltacpu-2022-03/apps/zlib/1.2.11-gcc-11.2.0-mlefudp
[+] /usr (external ncurses-6.1.20180224-myx5mkuvmvixcitps2qad3yl2idkf22q)
[+] /usr (external tar-1.30-wdu5sijhnch5xjpdus7trz5kxvys6hqh)
==> Installing linux-headers-6.2.8-kma22vlbmme7avrsa4sjtdpho2vt5td5 [8/16]
==> No binary for linux-headers-6.2.8-kma22vlbmme7avrsa4sjtdpho2vt5td5 found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/fe/fed0ad87d42f83a70ce019ff2800bc30a855e672e72bf6d54a014d98d344f665.tar.xz
==> No patches needed for linux-headers
==> linux-headers: Executing phase: 'install'
==> linux-headers: Successfully installed linux-headers-6.2.8-kma22vlbmme7avrsa4sjtdpho2vt5td5
  Stage: 14.81s.  Install: 7.80s.  Post-install: 1.90s.  Total: 24.55s
[+] /sw/spack/deltacpu-2022-03/apps/linux-rhel8-zen3/gcc-11.2.0/linux-headers-6.2.8-kma22vl
[+] /sw/spack/deltacpu-2022-03/apps/berkeley-db/18.1.40-gcc-11.2.0-hfm4k4r
[+] /usr (external texinfo-6.5-i37hfbw6rwagtcw3ckkq7nr4j64cfqgy)
[+] /sw/spack/deltacpu-2022-03/apps/libxml2/2.9.13-gcc-11.2.0-srqcix2
[+] /sw/spack/deltacpu-2022-03/apps/readline/8.1-gcc-11.2.0-wrjusz5
[+] /sw/spack/deltacpu-2022-03/apps/gettext/0.21-gcc-11.2.0-rpog4gt
[+] /sw/spack/deltacpu-2022-03/apps/gdbm/1.19-gcc-11.2.0-5nndgyo
[+] /sw/spack/deltacpu-2022-03/apps/perl/5.35.0-gcc-11.2.0-rbcr3pz
==> Installing glibc-2.29-szbrgl7uue3d6fhfocaytksctbwwwlcf [16/16]
==> No binary for glibc-2.29-szbrgl7uue3d6fhfocaytksctbwwwlcf found: installing from source
==> Fetching https://ftpmirror.gnu.org/libc/glibc-2.29.tar.gz
==> Ran patch() for glibc
==> glibc: Executing phase: 'autoreconf'
==> glibc: Executing phase: 'configure'
==> glibc: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16'

4 errors found in build log:
     90328                     from ../inet/netgroup.h:22,
     90329                     from ../include/netdb.h:203,
     90330                     from nss_files/files-hosts.c:23:
     90331    ../setjmp/setjmp.h:54:46: note: previously declared as an array 'struct __jmp_buf_tag[1]
              '
     90332       54 | extern int __sigsetjmp (struct __jmp_buf_tag __env[1], int __savemask) __THROWNL
              ;
     90333          |                         ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
  >> 90334    makedb.c:50:11: fatal error: selinux/selinux.h: No such file or directory
     90335       50 | # include <selinux/selinux.h>
     90336          |           ^~~~~~~~~~~~~~~~~~~
     90337    compilation terminated.
  >> 90338    make[2]: *** [../o-iterator.mk:9: /tmp/svcdeltaswmgt/spack-stage/spack-stage-glibc-2.29-
              szbrgl7uue3d6fhfocaytksctbwwwlcf/spack-src/build/nss/makedb.o] Error 1
     90339    make[2]: *** Waiting for unfinished jobs....
     90340    In file included from ../include/pthread.h:1,
     90341                     from ../nptl/../nptl_db/thread_db.h:25,
     90342                     from ../nptl/descr.h:32,
     90343                     from ../sysdeps/x86_64/nptl/tls.h:130,
     90344                     from ../include/errno.h:25,

     ...

     90371                     from ../include/errno.h:25,
     90372                     from nss_files/files-initgroups.c:19:
     90373    ../setjmp/setjmp.h:54:46: note: previously declared as an array 'struct __jmp_buf_tag[1]
              '
     90374       54 | extern int __sigsetjmp (struct __jmp_buf_tag __env[1], int __savemask) __THROWNL
              ;
     90375          |                         ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
     90376    make[2]: Leaving directory '/tmp/svcdeltaswmgt/spack-stage/spack-stage-glibc-2.29-szbrgl
              7uue3d6fhfocaytksctbwwwlcf/spack-src/nss'
  >> 90377    make[1]: *** [Makefile:258: nss/others] Error 2
     90378    make[1]: Leaving directory '/tmp/svcdeltaswmgt/spack-stage/spack-stage-glibc-2.29-szbrgl
              7uue3d6fhfocaytksctbwwwlcf/spack-src'
  >> 90379    make: *** [Makefile:9: all] Error 2

See build log for details:
  /tmp/svcdeltaswmgt/spack-stage/spack-stage-glibc-2.29-szbrgl7uue3d6fhfocaytksctbwwwlcf/spack-build-out.txt

[svcdeltaswmgt@dt-login03 0.17.1]$ 
</pre></details>

### Information on your system

[svcdeltaswmgt@dt-login03 0.17.1]$ spack debug report
* **Spack:** 0.21.0.dev0 (f7d71ec792b7753ee74835fc2c0f99047f0bf3dc)
* **Python:** 3.6.8
* **Platform:** linux-rhel8-zen3
* **Concretizer:** clingo

### Additional information

@haampie   glibc install problem, selinux.h ?
[spack-build-out.txt](https://github.com/spack/spack/files/12538161/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/12538165/spack-build-env.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
Can you make a PR that sets `--without-selinux`?

**Comment by kc9qey** [comment]
I'm not a spack developer ( no time ) , so no.    I'm wondering why selinux would ever be in play on an HPC system.  I've never encountered an operational HPC system running selinux .

**Comment by pbisbal1** [comment]
@kc9qey, You would never have SELinux enabled on compute nodes, but it's not uncommon for it to be on the public-facing nodes like the login nodes or master node in order to protect the rest of the cluster from the outside world.

**Comment by kc9qey** [comment]
.

**Comment by kc9qey** [comment]
.
