### ISSUE TITLE
tcl module files should test for LMOD_VERSION and LMOD_VERSION_MAJOR, not just LMOD_VERSION_MAJOR

### ISSUE THREAD

**Issue by climbfuji** [LLNL/spack#39858]
### Steps to reproduce

Some systems running `lmod`, including my macOS, have only the environment variable `LMOD_VERSION` set, not `LMOD_VERSION_MAJOR`. The auto-generated tcl module files only look for the latter variable.

A simple change to `share/spack/templates/modules/modulefile.tcl` and the associated tests allows to detect both.

### Error message

The "error" (not a real error, but just an unexpected/false behavior) is that even though a system is using `lmod`, the `tcl` syntax is used instead of the superior `lmod` syntax.

I know that this is not a showstopper, and I also know that `tcl` modules are going away at some point (hopefully sooner than later), but as long as they exist we should fix that simple flag in the logic.

### Information on your system

```
* **Spack:** 0.21.0.dev0 (eda4b00db29d2b8d6ac31686f8756df70f0e5c36)
* **Python:** 3.8.9
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
If `LMOD_VERSION` is always ensured to be there, shouldn't we look just for that?

**Comment by climbfuji** [comment]
> If `LMOD_VERSION` is always ensured to be there, shouldn't we look just for that?

Is it? I don't know, on the two systems I tested this it was, but I didn't check any other systems. I thought that there must have been a reason to use `LMOD_VERSION_MAJOR` in the first place, and not `LMOD_VERSION`.

**Comment by xdelaruelle** [comment]
> The "error" (not a real error, but just an unexpected/false behavior) is that even though a system is using lmod, the tcl syntax is used instead of the superior lmod syntax.

> I know that this is not a showstopper, and I also know that tcl modules are going away at some point (hopefully sooner than later), but as long as they exist we should fix that simple flag in the logic.

`tcl` modules will persist. It is sad to read that in 2023 if you compare the activity of both projects in the past 5 years :). But it is not the point of this issue :).

I introduced this test over the `LMOD_VERSION_MAJOR` environment variable as [it is the recommended way by the Lmod project](https://lmod.readthedocs.io/en/latest/040_FAQ.html).

Could you precise the version of Lmod you use?

As far as I understand the `LMOD_VERSION_MAJOR` environment variable is defined within the execution context of Lmod. You will not find it in your shell session, but when modulefile is evaluated by `lmod` command the if test will be true.

**Comment by climbfuji** [comment]
One system is an AWS Parallel Cluster running Ubuntu 20, where lmod was installed manually because the `apt` version is too old:
```
# Install lua/lmod manually, because apt only has older versions
# that are not compatible with the modern lua modules spack produces
# https://lmod.readthedocs.io/en/latest/030_installing.html#install-lua-x-y-z-tar-gz
mkdir -p /opt/lua/5.1.4.9/src
cd /opt/lua/5.1.4.9/src
wget https://sourceforge.net/projects/lmod/files/lua-5.1.4.9.tar.bz2
tar -xvf lua-5.1.4.9.tar.bz2
cd lua-5.1.4.9
./configure --prefix=/opt/lua/5.1.4.9 2>&1 | tee log.config
make VERBOSE=1 2>&1 | tee log.make
make install 2>&1 | tee log.install
#
echo "# Set environment variables for lua" >> /etc/profile.d/02-lua.sh
echo "export PATH=\"/opt/lua/5.1.4.9/bin:\$PATH\"" >> /etc/profile.d/02-lua.sh
echo "export LD_LIBRARY_PATH=\"/opt/lua/5.1.4.9/lib:\$LD_LIBRARY_PATH\"" >> /etc/profile.d/02-lua.sh
echo "export CPATH=\"/opt/lua/5.1.4.9/include:\$CPATH\"" >> /etc/profile.d/02-lua.sh
echo "export MANPATH=\"/opt/lua/5.1.4.9/man:\$MANPATH\"" >> /etc/profile.d/02-lua.sh
#
source /etc/profile.d/02-lua.sh

mkdir -p /opt/lmod/8.7/src
cd /opt/lmod/8.7/src
wget https://sourceforge.net/projects/lmod/files/Lmod-8.7.tar.bz2
tar -xvf Lmod-8.7.tar.bz2
cd Lmod-8.7
# Note the weird prefix, lmod installs in PREFIX/lmod/X.Y automatically
./configure --prefix=/opt/ \
--with-lmodConfigDir=/opt/lmod/8.7/config \
2>&1 | tee log.config
make install 2>&1 | tee log.install
ln -sf /opt/lmod/lmod/init/profile /etc/profile.d/z00_lmod.sh
ln -sf /opt/lmod/lmod/init/cshrc /etc/profile.d/z00_lmod.csh
ln -sf /opt/lmod/lmod/init/profile.fish /etc/profile.d/z00_lmod.fish
```
The other system where this occurred I don't have access to (DoD / Navy Atlantis), but where the developers reported that only `LMOD_VERSION` is set.

**Comment by xdelaruelle** [comment]
I have read https://github.com/JCSDA/spack-stack/issues/761 and from the initial description, the execution is correct:

```tcl
if {![info exists ::env(LMOD_VERSION_MAJOR)]} {
    module load openmpi/4.1.5
    module load zlib/1.2.13
} else {
    depends-on intel/2021.6.0/openmpi/4.1.5
    depends-on intel/2021.6.0/zlib/1.2.13
}
```

The error obtained indicates that Lmod is correctly going on its branch with the depends-on commands. Error message was:

> Lmod has detected the following error: The following module(s) are unknown: "intel/2021.6.0/openmpi/4.1.5" "intel/2021.6.0/zlib/1.2.13"

So the `if {![info exists ::env(LMOD_VERSION_MAJOR)]} {` test appears to be correct. The issue is on the module names to load which are different between the two sides of the if branch.

**Comment by xdelaruelle** [comment]
Looking at the `modulefile.tcl` template:

https://github.com/spack/spack/blob/e797a89fe118bac468a149789032835f6f9ea87b/share/spack/templates/modules/modulefile.tcl#L30-L37

Same `{{ module }}` template variable is used on both side of the if branch, so generated modulefile should have the same module name designation on both side of the if.

Is there something that tweaks the modulefile after being generated by Spack?

**Comment by climbfuji** [comment]
Well, that's embarrassing but you are correct. The bug fix that went into spack-stack had two parts, one to add LMOD_VERSION (because we didn't see the env variable set due to what you described above), and one that fixed the inconsistency between the two branches (which apparently would have been sufficient). The not-exist test confused us in the first place and led to adding LMOD_VERSION.

I think I should close this issue as invalid and the PR as not needed. Thanks for the explanation of where LMOD_VERSION comes from, and sorry for wasting your time!
