### ISSUE TITLE
Non-deterministic output from spack versions

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#3986]
I made the following change to `libpng`:
```python
list_url = "https://sourceforge.net/projects/libpng/files/"
list_depth = 3
```
When I run `spack versions` I see:
```
$ spack versions libpng
==> Safe versions (already checksummed):
  1.6.27  1.2.57
==> Remote versions (not yet checksummed):
  Found no versions for libpng
$ spack versions libpng
==> Safe versions (already checksummed):
  1.6.27  1.2.57
==> Remote versions (not yet checksummed):
  1.5.29beta01
$ spack versions libpng
==> Safe versions (already checksummed):
  1.6.27  1.2.57
==> Remote versions (not yet checksummed):
  1.6.29  1.6.28
$ spack versions libpng
==> Safe versions (already checksummed):
  1.6.27  1.2.57
==> Remote versions (not yet checksummed):
  1.0.67-no-config  1.0.67  1.0.66-no-config  1.0.66
```

**Comment by citibeth** [comment]
...so what is the problem?  I don't understand what is wrong with the output above.

**Comment by adamjstewart** [comment]
I would expect the remote versions found to be more... consistent. `spack versions` isn't useful unless it can reliably tell me if there is a new version available.

**Comment by adamjstewart** [comment]
I'm seeing this again for another package I'm currently working on:
```python
url      = "https://sourceforge.net/projects/cbench/files/cbench/1.3.0/cbench_release_1.3.0.tar.gz/download"
list_url = "https://sourceforge.net/projects/cbench/files/cbench/"          
list_depth = 1
```
Alternates between finding `1.2.0` and finding no remote versions.

**Comment by tgamblin** [comment]
I don't know whether it is the problem you're seeing here, but some sites have a throttle on he connections they'll accept from one host, and they'll drop some of the requests in spack.util.web.spider.  And the site can sometimes be down, so you're not going to get any guarantees deterministic output from something that makes remote requests like this.   I do still think it is still useful if it tells you there are new versions when it can.

You can run with `spack -d` If you want to see why some of the spider requests were squashed.  [see here](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/util/web.py#L192).

**Comment by adamjstewart** [comment]
Nice! Yeah, I'm seeing a lot of `error: [Errno 104] Connection reset by peer` errors for both packages. Sometimes there will be no errors and it will pick up 5 new versions. Other times it will only find 1 or none at all. As long as it's not a Spack bug, there's not really much we can do about it. Thanks!
