### ISSUE TITLE
Installation issue: TAU

### ISSUE THREAD

**Issue by gcongiu** [LLNL/spack#39862]
### Steps to reproduce the issue

Requires PR https://github.com/spack/spack/pull/39860

```console
$ git checkout 2023.09.07_papi-rocm-fix
$ spack install papi@master +rocm +rocm_smi amdgpu_target=gfx90a ^rocprofiler-dev@5.2.0 ^hsa-rocr-dev@5.2.0 ^hip@5.2.0 ^rocm-smi-lib@5.2.0
$ spack install tau ^papi@master
...
```

### Error message

<details><summary>Error message</summary>

<pre>
g++     -DTAU_LIBRARY_SOURCE  -O2 -g -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/lib64 -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/binutils-2.40-shyusdzbboykg664s6oj2uxfnkcty74x/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/elfutils-0.189-uaz4byn5injvmsxrrgobbrgwnufeykq3/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/hwloc-2.9.1-5mb7m43mddejb46ql2wkcztuiioptj4x/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/libdwarf-20180129-zfpja2op64vy557op2brfobrqzxsxsbg/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/libunwind-1.6.2-4aykx5735behdzbvyzuaojvon2ef7ziv/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/otf2-2.3-cikxvf7vfcxwn2e6ztfm3q4swu3pzyx4/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/papi-master-pj3pvdcjfakf2wgajchpwwdpxtwncmvr/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/pdt-3.25.1-hbmmxngqxuxaf64zhdzdvfdlyhwx34fz/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/zlib-1.2.13-zytvdjryvr4z2zkolcek7dxpy5lnhwgq/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/binutils-2.40-shyusdzbboykg664s6oj2uxfnkcty74x/lib64 -I/tmp/gcongiu/spack-stage/spack-stage-tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/spack-src/include -I/tmp/gcongiu/spack-stage/spack-stage-tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/spack-src/include/Profile -DPROFILING_ON            -DTAU_PAPI -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/papi-master-pj3pvdcjfakf2wgajchpwwdpxtwncmvr/include             -DTAU_GNU -DTAU_DOT_H_LESS_HEADERS    -DCRAYCC -DTAU_DOT_H_LESS_HEADERS   -DPTHREADS -DTAU_PTHREAD_PRELOAD -DTAU_UNIFY                -DTAU_LINUX_TIMERS                       -DTAU_CRAYCNL  -DTAU_AT_FORK           -DTAU_LARGEFILE -D_LARGEFILE64_SOURCE                    -DTAU_BFD   -DHAVE_GNU_DEMANGLE   -DHAVE_TR1_HASH_MAP    -DTAU_SS_ALLOC_SUPPORT  -DEBS_CLOCK_RES=1  -DTAU_STRSIGNAL_OK -DTAU_UNWIND -DTAU_USE_LIBUNWIND -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/libunwind-1.6.2-4aykx5735behdzbvyzuaojvon2ef7ziv/include    -DTAU_TRACK_LD_LOADER        -DTAU_USE_TLS                            -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/otf2-2.3-cikxvf7vfcxwn2e6ztfm3q4swu3pzyx4/include -DTAU_OTF2    -DTAU_ELF_BFD  -DTAU_DWARF  -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/libdwarf-20180129-zfpja2op64vy557op2brfobrqzxsxsbg/include   -fPIC         -hstd=c++11 -DTAU_USE_STDCXX11         -c Profiler.cpp
g++     -DTAU_LIBRARY_SOURCE  -O2 -g -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/lib64 -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/binutils-2.40-shyusdzbboykg664s6oj2uxfnkcty74x/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/elfutils-0.189-uaz4byn5injvmsxrrgobbrgwnufeykq3/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/hwloc-2.9.1-5mb7m43mddejb46ql2wkcztuiioptj4x/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/libdwarf-20180129-zfpja2op64vy557op2brfobrqzxsxsbg/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/libunwind-1.6.2-4aykx5735behdzbvyzuaojvon2ef7ziv/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/otf2-2.3-cikxvf7vfcxwn2e6ztfm3q4swu3pzyx4/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/papi-master-pj3pvdcjfakf2wgajchpwwdpxtwncmvr/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/pdt-3.25.1-hbmmxngqxuxaf64zhdzdvfdlyhwx34fz/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/zlib-1.2.13-zytvdjryvr4z2zkolcek7dxpy5lnhwgq/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/binutils-2.40-shyusdzbboykg664s6oj2uxfnkcty74x/lib64 -I/tmp/gcongiu/spack-stage/spack-stage-tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/spack-src/include -I/tmp/gcongiu/spack-stage/spack-stage-tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/spack-src/include/Profile -DPROFILING_ON            -DTAU_PAPI -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/papi-master-pj3pvdcjfakf2wgajchpwwdpxtwncmvr/include             -DTAU_GNU -DTAU_DOT_H_LESS_HEADERS    -DCRAYCC -DTAU_DOT_H_LESS_HEADERS   -DPTHREADS -DTAU_PTHREAD_PRELOAD -DTAU_UNIFY                -DTAU_LINUX_TIMERS                       -DTAU_CRAYCNL  -DTAU_AT_FORK           -DTAU_LARGEFILE -D_LARGEFILE64_SOURCE                    -DTAU_BFD   -DHAVE_GNU_DEMANGLE   -DHAVE_TR1_HASH_MAP    -DTAU_SS_ALLOC_SUPPORT  -DEBS_CLOCK_RES=1  -DTAU_STRSIGNAL_OK -DTAU_UNWIND -DTAU_USE_LIBUNWIND -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/libunwind-1.6.2-4aykx5735behdzbvyzuaojvon2ef7ziv/include    -DTAU_TRACK_LD_LOADER        -DTAU_USE_TLS                            -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/otf2-2.3-cikxvf7vfcxwn2e6ztfm3q4swu3pzyx4/include -DTAU_OTF2    -DTAU_ELF_BFD  -DTAU_DWARF  -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/libdwarf-20180129-zfpja2op64vy557op2brfobrqzxsxsbg/include   -fPIC         -hstd=c++11 -DTAU_USE_STDCXX11     -c UserEvent.cpp
g++     -DTAU_LIBRARY_SOURCE  -O2 -g -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/lib64 -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/binutils-2.40-shyusdzbboykg664s6oj2uxfnkcty74x/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/elfutils-0.189-uaz4byn5injvmsxrrgobbrgwnufeykq3/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/hwloc-2.9.1-5mb7m43mddejb46ql2wkcztuiioptj4x/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/libdwarf-20180129-zfpja2op64vy557op2brfobrqzxsxsbg/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/libunwind-1.6.2-4aykx5735behdzbvyzuaojvon2ef7ziv/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/otf2-2.3-cikxvf7vfcxwn2e6ztfm3q4swu3pzyx4/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/papi-master-pj3pvdcjfakf2wgajchpwwdpxtwncmvr/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/pdt-3.25.1-hbmmxngqxuxaf64zhdzdvfdlyhwx34fz/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/zlib-1.2.13-zytvdjryvr4z2zkolcek7dxpy5lnhwgq/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/binutils-2.40-shyusdzbboykg664s6oj2uxfnkcty74x/lib64 -I/tmp/gcongiu/spack-stage/spack-stage-tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/spack-src/include -I/tmp/gcongiu/spack-stage/spack-stage-tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/spack-src/include/Profile -DPROFILING_ON            -DTAU_PAPI -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/papi-master-pj3pvdcjfakf2wgajchpwwdpxtwncmvr/include             -DTAU_GNU -DTAU_DOT_H_LESS_HEADERS    -DCRAYCC -DTAU_DOT_H_LESS_HEADERS   -DPTHREADS -DTAU_PTHREAD_PRELOAD -DTAU_UNIFY                -DTAU_LINUX_TIMERS                       -DTAU_CRAYCNL  -DTAU_AT_FORK           -DTAU_LARGEFILE -D_LARGEFILE64_SOURCE                    -DTAU_BFD   -DHAVE_GNU_DEMANGLE   -DHAVE_TR1_HASH_MAP    -DTAU_SS_ALLOC_SUPPORT  -DEBS_CLOCK_RES=1  -DTAU_STRSIGNAL_OK -DTAU_UNWIND -DTAU_USE_LIBUNWIND -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/libunwind-1.6.2-4aykx5735behdzbvyzuaojvon2ef7ziv/include    -DTAU_TRACK_LD_LOADER        -DTAU_USE_TLS                            -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/otf2-2.3-cikxvf7vfcxwn2e6ztfm3q4swu3pzyx4/include -DTAU_OTF2    -DTAU_ELF_BFD  -DTAU_DWARF  -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/libdwarf-20180129-zfpja2op64vy557op2brfobrqzxsxsbg/include   -fPIC         -hstd=c++11 -DTAU_USE_STDCXX11     -c FunctionInfo.cpp
g++     -DTAU_LIBRARY_SOURCE  -O2 -g -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/lib64 -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/binutils-2.40-shyusdzbboykg664s6oj2uxfnkcty74x/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/elfutils-0.189-uaz4byn5injvmsxrrgobbrgwnufeykq3/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/hwloc-2.9.1-5mb7m43mddejb46ql2wkcztuiioptj4x/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/libdwarf-20180129-zfpja2op64vy557op2brfobrqzxsxsbg/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/libunwind-1.6.2-4aykx5735behdzbvyzuaojvon2ef7ziv/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/otf2-2.3-cikxvf7vfcxwn2e6ztfm3q4swu3pzyx4/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/papi-master-pj3pvdcjfakf2wgajchpwwdpxtwncmvr/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/pdt-3.25.1-hbmmxngqxuxaf64zhdzdvfdlyhwx34fz/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/zlib-1.2.13-zytvdjryvr4z2zkolcek7dxpy5lnhwgq/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/binutils-2.40-shyusdzbboykg664s6oj2uxfnkcty74x/lib64 -I/tmp/gcongiu/spack-stage/spack-stage-tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/spack-src/include -I/tmp/gcongiu/spack-stage/spack-stage-tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/spack-src/include/Profile -DPROFILING_ON            -DTAU_PAPI -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/papi-master-pj3pvdcjfakf2wgajchpwwdpxtwncmvr/include             -DTAU_GNU -DTAU_DOT_H_LESS_HEADERS    -DCRAYCC -DTAU_DOT_H_LESS_HEADERS   -DPTHREADS -DTAU_PTHREAD_PRELOAD -DTAU_UNIFY                -DTAU_LINUX_TIMERS                       -DTAU_CRAYCNL  -DTAU_AT_FORK           -DTAU_LARGEFILE -D_LARGEFILE64_SOURCE                    -DTAU_BFD   -DHAVE_GNU_DEMANGLE   -DHAVE_TR1_HASH_MAP    -DTAU_SS_ALLOC_SUPPORT  -DEBS_CLOCK_RES=1  -DTAU_STRSIGNAL_OK -DTAU_UNWIND -DTAU_USE_LIBUNWIND -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/libunwind-1.6.2-4aykx5735behdzbvyzuaojvon2ef7ziv/include    -DTAU_TRACK_LD_LOADER        -DTAU_USE_TLS                            -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/otf2-2.3-cikxvf7vfcxwn2e6ztfm3q4swu3pzyx4/include -DTAU_OTF2    -DTAU_ELF_BFD  -DTAU_DWARF  -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/libdwarf-20180129-zfpja2op64vy557op2brfobrqzxsxsbg/include   -fPIC         -hstd=c++11 -DTAU_USE_STDCXX11     -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/binutils-2.40-shyusdzbboykg664s6oj2uxfnkcty74x/include -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/binutils-2.40-shyusdzbboykg664s6oj2uxfnkcty74x/include/extra -c TauKokkos.cpp
g++     -DTAU_LIBRARY_SOURCE  -O2 -g -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/lib64 -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/binutils-2.40-shyusdzbboykg664s6oj2uxfnkcty74x/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/elfutils-0.189-uaz4byn5injvmsxrrgobbrgwnufeykq3/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/hwloc-2.9.1-5mb7m43mddejb46ql2wkcztuiioptj4x/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/libdwarf-20180129-zfpja2op64vy557op2brfobrqzxsxsbg/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/libunwind-1.6.2-4aykx5735behdzbvyzuaojvon2ef7ziv/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/otf2-2.3-cikxvf7vfcxwn2e6ztfm3q4swu3pzyx4/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/papi-master-pj3pvdcjfakf2wgajchpwwdpxtwncmvr/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/pdt-3.25.1-hbmmxngqxuxaf64zhdzdvfdlyhwx34fz/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/zlib-1.2.13-zytvdjryvr4z2zkolcek7dxpy5lnhwgq/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/binutils-2.40-shyusdzbboykg664s6oj2uxfnkcty74x/lib64 -I/tmp/gcongiu/spack-stage/spack-stage-tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/spack-src/include -I/tmp/gcongiu/spack-stage/spack-stage-tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/spack-src/include/Profile -DPROFILING_ON            -DTAU_PAPI -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/papi-master-pj3pvdcjfakf2wgajchpwwdpxtwncmvr/include             -DTAU_GNU -DTAU_DOT_H_LESS_HEADERS    -DCRAYCC -DTAU_DOT_H_LESS_HEADERS   -DPTHREADS -DTAU_PTHREAD_PRELOAD -DTAU_UNIFY                -DTAU_LINUX_TIMERS                       -DTAU_CRAYCNL  -DTAU_AT_FORK           -DTAU_LARGEFILE -D_LARGEFILE64_SOURCE                    -DTAU_BFD   -DHAVE_GNU_DEMANGLE   -DHAVE_TR1_HASH_MAP    -DTAU_SS_ALLOC_SUPPORT  -DEBS_CLOCK_RES=1  -DTAU_STRSIGNAL_OK -DTAU_UNWIND -DTAU_USE_LIBUNWIND -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/libunwind-1.6.2-4aykx5735behdzbvyzuaojvon2ef7ziv/include    -DTAU_TRACK_LD_LOADER        -DTAU_USE_TLS                            -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/otf2-2.3-cikxvf7vfcxwn2e6ztfm3q4swu3pzyx4/include -DTAU_OTF2    -DTAU_ELF_BFD  -DTAU_DWARF  -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/libdwarf-20180129-zfpja2op64vy557op2brfobrqzxsxsbg/include   -fPIC         -hstd=c++11 -DTAU_USE_STDCXX11      -c RtsLayer.cpp
g++     -DTAU_LIBRARY_SOURCE  -O2 -g -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/lib64 -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/binutils-2.40-shyusdzbboykg664s6oj2uxfnkcty74x/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/elfutils-0.189-uaz4byn5injvmsxrrgobbrgwnufeykq3/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/hwloc-2.9.1-5mb7m43mddejb46ql2wkcztuiioptj4x/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/libdwarf-20180129-zfpja2op64vy557op2brfobrqzxsxsbg/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/libunwind-1.6.2-4aykx5735behdzbvyzuaojvon2ef7ziv/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/otf2-2.3-cikxvf7vfcxwn2e6ztfm3q4swu3pzyx4/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/papi-master-pj3pvdcjfakf2wgajchpwwdpxtwncmvr/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/pdt-3.25.1-hbmmxngqxuxaf64zhdzdvfdlyhwx34fz/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/zlib-1.2.13-zytvdjryvr4z2zkolcek7dxpy5lnhwgq/lib -Wl,-rpath,/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/binutils-2.40-shyusdzbboykg664s6oj2uxfnkcty74x/lib64 -I/tmp/gcongiu/spack-stage/spack-stage-tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/spack-src/include -I/tmp/gcongiu/spack-stage/spack-stage-tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/spack-src/include/Profile -DPROFILING_ON            -DTAU_PAPI -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/papi-master-pj3pvdcjfakf2wgajchpwwdpxtwncmvr/include             -DTAU_GNU -DTAU_DOT_H_LESS_HEADERS    -DCRAYCC -DTAU_DOT_H_LESS_HEADERS   -DPTHREADS -DTAU_PTHREAD_PRELOAD -DTAU_UNIFY                -DTAU_LINUX_TIMERS                       -DTAU_CRAYCNL  -DTAU_AT_FORK           -DTAU_LARGEFILE -D_LARGEFILE64_SOURCE                    -DTAU_BFD   -DHAVE_GNU_DEMANGLE   -DHAVE_TR1_HASH_MAP    -DTAU_SS_ALLOC_SUPPORT  -DEBS_CLOCK_RES=1  -DTAU_STRSIGNAL_OK -DTAU_UNWIND -DTAU_USE_LIBUNWIND -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/libunwind-1.6.2-4aykx5735behdzbvyzuaojvon2ef7ziv/include    -DTAU_TRACK_LD_LOADER        -DTAU_USE_TLS                            -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/otf2-2.3-cikxvf7vfcxwn2e6ztfm3q4swu3pzyx4/include -DTAU_OTF2    -DTAU_ELF_BFD  -DTAU_DWARF  -I/autofs/nccs-svm1_home1/gcongiu/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/libdwarf-20180129-zfpja2op64vy557op2brfobrqzxsxsbg/include   -fPIC         -hstd=c++11 -DTAU_USE_STDCXX11      -c RtsThread.cpp
g++: error: unrecognized command line option '-h'
make[1]: *** [Makefile:658: Profiler.o] Error 1
make[1]: *** Waiting for unfinished jobs....
g++: error: unrecognized command line option '-h'
make[1]: *** [Makefile:766: UserEvent.o] Error 1
g++: error: unrecognized command line option '-h'
make[1]: *** [Makefile:769: FunctionInfo.o] Error 1
g++: error: unrecognized command line option '-h'
make[1]: *** [Makefile:772: TauKokkos.o] Error 1
g++: error: unrecognized command line option '-h'
make[1]: *** [Makefile:790: RtsLayer.o] Error 1
g++: error: unrecognized command line option '-h'
make[1]: *** [Makefile:793: RtsThread.o] Error 1
make[1]: Leaving directory '/tmp/gcongiu/spack-stage/spack-stage-tau-2.32.1-5u4ryjjol6idxkw6ykextpvvyzllaw4o/spack-src/src/Profile'
make: *** [Makefile:193: install] Error 2
</pre></details>

### Information on your system

Frontier log-in node
g++ (SUSE Linux) 7.5.0

### Additional information

$ spack debug report
* **Spack:** 0.21.0.dev0 (d4bb5ac6ad9da3bd7710bbfab780171f3d5e6d50)
* **Python:** 3.6.15
* **Platform:** linux-sles15-zen3
* **Concretizer:** clingo

$ spack maintainers tau
@eugeneswalker @khuck  @sameershende  @wspear

[spack-build-out.txt](https://github.com/spack/spack/files/12546412/spack-build-out.txt)

There problem does not appear to be reported anywhere in the repo.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by khuck** [comment]
How did -hstd=c++11 end up in the compile flags?

**Comment by gcongiu** [comment]
I think TAU expects a cray compiler although spack is using the system compiler. I could solve the issue forcing the system compiler in spack by `export GCC_PATH=/usr/bin`.

**Comment by gcongiu** [comment]
This was probably caused by a faulty environment setup in my workspace. I am closing it as I am no longer able to reproduce it.
