### ISSUE TITLE
Machine-readable output for `spack info`

### ISSUE THREAD

**Issue by Pandapip1** [LLNL/spack#39871]
### Summary

I'm writing a script and need to find out all the installable versions of a spack package. But I can't do that, since `spack info` doesn't have a `--format json` or `--json` option. I would really like if that could be added.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
You can use `spack-python for that, and:
```python
import spack.repo

for pkg_class in spack.repo.PATH.all_package_classes:
   print(pkg_class.versions.keys())
```

**Comment by Pandapip1** [comment]
Thanks! Was not aware that `spack-python` existed.
