### ISSUE TITLE
Wrong autocompletion with spack env activate

### ISSUE THREAD

**Issue by Billae** [LLNL/spack#39886]
### Steps to reproduce

In my prompt I write
```
spack env activate
```
 and I begin to write the name of my env, I push then the TAB key to complete the whole name of my env, but instead spack change it to write "concretize". 

### Information on your system

* **Spack:** 0.21.0.dev0 (d80bc7048159045df36da46da98fbe615efc5da5)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
@tgamblin

**Comment by tgamblin** [comment]
@Billae can you see if #39887 fixes this?

**Comment by Billae** [comment]
Yep it works, thanks =)
