### ISSUE TITLE
--no-cache doesn't skip cached archives.

### ISSUE THREAD

**Issue by marcmengel** [LLNL/spack#39957]
### Steps to reproduce

I would expect that using --no-cache would not used a cached source archive, but it does:

spack install libbsd@0.11.7
....
spack install --no-cache --overwrite libbsd@0.11.7
...
==> Using cached archive: /scratch/packages/spack/v0.19.fermi/NULL/var/spack/cache/_source-cache/archive/9b/9baa186059ebbf25c06308e9f991fda31f7183c0f24931826d83aa6abd8a0261.tar.xz
...

You have to spack clean to get rid of the cached source, i.e. if you are testing changes to a patch() method, etc. 

### Error message

$ spack install --no-cache --overwrite libbsd@0.11.7 
==> The following package specs will be reinstalled:

-- linux-scientific7-x86_64_v2 / gcc@4.8.5 ----------------------
otdtbxp libbsd@0.11.7%gcc  build_system=autotools
==> Do you want to proceed? [y/N] y
[+] /scratch/packages/[padded-to-255-chars]/libmd/1.0.4/linux-scientific7-x86_64_v2-gcc-4.8.5-y3opapfh2cbjflr3bxkxf6v3v44j3h34
==> Installing libbsd-0.11.7-otdtbxps4c43fyy6i4pyfupc5qguhred
==> Using cached archive: /scratch/packages/spack/v0.19.fermi/NULL/var/spack/cache/_source-cache/archive/9b/9baa186059ebbf25c06308e9f991fda31f7183c0f24931826d83aa6abd8a0261.tar.xz

### Information on your system

$ spack debug report
* **Spack:** 0.20.0-fermi
* **Python:** 3.6.8
* **Platform:** linux-scientific7-broadwell
* **Concretizer:** clingo

Also occurs in a fresh checkout of develop:

$ spack debug report
* **Spack:** 0.21.0.dev0
* **Python:** 3.6.8
* **Platform:** linux-scientific7-ivybridge
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
The option is only for binary caches. From the help:
```
--no-cache            do not check for pre-built Spack packages in mirrors
```
