### ISSUE TITLE
Installation issue: petsc+mpi+kokkos+openmp on MacOS, fails on Hypre and SuperLU due to broken Fortran

### ISSUE THREAD

**Issue by DamynChipman** [LLNL/spack#39956]
### Steps to reproduce the issue

```bash
(base) ➜  ~ spack install petsc+mpi+kokkos+openmp
```

### Error message

<details><summary>Error message</summary>

<pre>
(base) ➜  ~ spack install petsc+mpi+kokkos+openmp        
==> Installing gnuconfig-2022-09-17-whbwvpqwkq7nbac4ussy7zu52hqj7gni
==> No binary for gnuconfig-2022-09-17-whbwvpqwkq7nbac4ussy7zu52hqj7gni found: installing from source
==> Using cached archive: /Users/damynchipman/packages/spack/var/spack/cache/_source-cache/archive/95/95306801ad7086e6a6e13397cb859183d8b7adbba2e372ce0819bad5fcb919b7.tar.gz
==> No patches needed for gnuconfig
==> gnuconfig: Executing phase: 'install'
==> gnuconfig: Successfully installed gnuconfig-2022-09-17-whbwvpqwkq7nbac4ussy7zu52hqj7gni
  Stage: 0.01s.  Install: 0.01s.  Total: 0.06s
[+] /Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/gnuconfig-2022-09-17-whbwvpqwkq7nbac4ussy7zu52hqj7gni
[+] /opt/homebrew (external cmake-3.24.1-o7kh3msmkjvwc7lwrf7rqyrfzmc5dicg)
[+] /opt/homebrew (external openmpi-4.1.5-3v4zingu7djpgw634wkrddiy4su6bw33)
==> Installing zlib-1.2.13-oedw7mtq7s6gpifkv2r3ca43ttejtlgh
==> No binary for zlib-1.2.13-oedw7mtq7s6gpifkv2r3ca43ttejtlgh found: installing from source
==> Using cached archive: /Users/damynchipman/packages/spack/var/spack/cache/_source-cache/archive/b3/b3a24de97a8fdbc835b9833169501030b8977031bcb54b3b3ac13740f846ab30.tar.gz
==> No patches needed for zlib
==> zlib: Executing phase: 'edit'
==> zlib: Executing phase: 'build'
==> zlib: Executing phase: 'install'
==> zlib: Successfully installed zlib-1.2.13-oedw7mtq7s6gpifkv2r3ca43ttejtlgh
  Stage: 0.04s.  Edit: 1.07s.  Build: 0.50s.  Install: 0.08s.  Total: 1.73s
[+] /Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/zlib-1.2.13-oedw7mtq7s6gpifkv2r3ca43ttejtlgh
[+] /opt/homebrew/opt/openblas (external openblas-0.3.24-wlrkov2bzpyiq5hjefb42rupo4pbyrka)
[+] /opt/homebrew (external python-3.11.5-fmama7of4etegw7nzdj6juibarocpoul)
==> Installing pkgconf-1.8.0-n45kx4k47t6uwqftchhhbt3jack3unlq
==> No binary for pkgconf-1.8.0-n45kx4k47t6uwqftchhhbt3jack3unlq found: installing from source
==> Using cached archive: /Users/damynchipman/packages/spack/var/spack/cache/_source-cache/archive/ef/ef9c7e61822b7cb8356e6e9e1dca58d9556f3200d78acab35e4347e9d4c2bbaf.tar.xz
==> No patches needed for pkgconf
==> pkgconf: Executing phase: 'autoreconf'
==> pkgconf: Executing phase: 'configure'
==> pkgconf: Executing phase: 'build'
==> pkgconf: Executing phase: 'install'
==> pkgconf: Successfully installed pkgconf-1.8.0-n45kx4k47t6uwqftchhhbt3jack3unlq
  Stage: 0.04s.  Autoreconf: 0.42s.  Configure: 3.96s.  Build: 1.28s.  Install: 0.15s.  Total: 5.88s
[+] /Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/pkgconf-1.8.0-n45kx4k47t6uwqftchhhbt3jack3unlq
==> Installing libiconv-1.17-ujsesismx4lgifuiihupwfi4hfzymyua
==> No binary for libiconv-1.17-ujsesismx4lgifuiihupwfi4hfzymyua found: installing from source
==> Using cached archive: /Users/damynchipman/packages/spack/var/spack/cache/_source-cache/archive/8f/8f74213b56238c85a50a5329f77e06198771e70dd9a739779f4c02f65d971313.tar.gz
==> No patches needed for libiconv
==> libiconv: Executing phase: 'autoreconf'
==> libiconv: Executing phase: 'configure'
==> libiconv: Executing phase: 'build'
==> libiconv: Executing phase: 'install'
==> libiconv: Successfully installed libiconv-1.17-ujsesismx4lgifuiihupwfi4hfzymyua
  Stage: 0.15s.  Autoreconf: 0.50s.  Configure: 19.11s.  Build: 3.76s.  Install: 0.48s.  Total: 24.05s
[+] /Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/libiconv-1.17-ujsesismx4lgifuiihupwfi4hfzymyua
==> Installing metis-5.1.0-s2jmgo2rxg5wwfnagoxs7ofzozk4rwxv
==> No binary for metis-5.1.0-s2jmgo2rxg5wwfnagoxs7ofzozk4rwxv found: installing from source
==> Using cached archive: /Users/damynchipman/packages/spack/var/spack/cache/_source-cache/archive/76/76faebe03f6c963127dbb73c13eab58c9a3faeae48779f049066a21c087c5db2.tar.gz
==> Applied patch /Users/damynchipman/packages/spack/var/spack/repos/builtin/packages/metis/gklib_path.patch
==> Applied patch /Users/damynchipman/packages/spack/var/spack/repos/builtin/packages/metis/install_gklib_defs_rename.patch
==> Ran patch() for metis
==> metis: Executing phase: 'cmake'
==> metis: Executing phase: 'build'
==> metis: Executing phase: 'install'
==> metis: Successfully installed metis-5.1.0-s2jmgo2rxg5wwfnagoxs7ofzozk4rwxv
  Stage: 0.08s.  Cmake: 1.01s.  Build: 1.36s.  Install: 0.41s.  Total: 2.90s
[+] /Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/metis-5.1.0-s2jmgo2rxg5wwfnagoxs7ofzozk4rwxv
[+] /Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/kokkos-3.7.01-3tvpkcyjz2uhrjiie7pkcjauadduhc3q
==> Installing hypre-2.27.0-c7aqbp5uryokvexu7wvjeakyyivoywll
==> No binary for hypre-2.27.0-c7aqbp5uryokvexu7wvjeakyyivoywll found: installing from source
==> Using cached archive: /Users/damynchipman/packages/spack/var/spack/cache/_source-cache/archive/50/507a3d036bb1ac21a55685ae417d769dd02009bde7e09785d0ae7446b4ae1f98.tar.gz
==> No patches needed for hypre
==> hypre: Executing phase: 'autoreconf'
==> hypre: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/private/var/folders/h7/5j0_j37j2qq2mb86sqm7k66m0000gn/T/damynchipman/spack-stage/spack-stage-hypre-2.27.0-c7aqbp5uryokvexu7wvjeakyyivoywll/spack-src/src/configure' '--prefix=/Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/hypre-2.27.0-c7aqbp5uryokvexu7wvjeakyyivoywll' '--prefix=/Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/hypre-2.27.0-c7aqbp5uryokvexu7wvjeakyyivoywll' '--with-lapack-libs=openblas' '--with-lapack-lib-dirs=/opt/homebrew/opt/openblas/lib' '--with-blas-libs=openblas' '--with-blas-lib-dirs=/opt/homebrew/opt/openblas/lib' '--with-MPI' '--with-MPI-lib-dirs=/opt/homebrew/lib' '--with-MPI-include=/opt/homebrew/include' '--without-openmp' '--disable-bigint' '--disable-mixedint' '--disable-complex' '--without-superlu' '--without-mli' '--without-fei' '--disable-debug' '--without-cuda' '--disable-curand' '--disable-cusparse' '--without-hip' '--disable-rocrand' '--disable-rocsparse' '--enable-fortran'

2 errors found in build log:
     24    checking whether we are using the GNU Fortran compiler... no
     25    checking whether /opt/homebrew/bin/mpif90 accepts -g... no
     26    checking how to get verbose linking output from /opt/homebrew/bin/mpif90... configure: WARNING: compilation failed
     27    
     28    checking for Fortran libraries of /opt/homebrew/bin/mpif90...
     29    checking for dummy main to link with Fortran libraries... none
  >> 30    checking for Fortran name-mangling scheme... configure: error: in `/private/var/folders/h7/5j0_j37j2qq2mb86sqm7k66m0000gn
           /T/damynchipman/spack-stage/spack-stage-hypre-2.27.0-c7aqbp5uryokvexu7wvjeakyyivoywll/spack-src/src':
  >> 31    configure: error: cannot compile a simple Fortran program
     32    See `config.log' for more details

See build log for details:
  /var/folders/h7/5j0_j37j2qq2mb86sqm7k66m0000gn/T/damynchipman/spack-stage/spack-stage-hypre-2.27.0-c7aqbp5uryokvexu7wvjeakyyivoywll/spack-build-out.txt

==> Warning: Skipping build of petsc-3.18.3-aj33zsfyf7i54craw4sgf5v2khgu5gqj since hypre-2.27.0-c7aqbp5uryokvexu7wvjeakyyivoywll failed
==> Installing hdf5-1.14.0-augmponetye5ljzbvc7gfen6i6qenpe6
==> No binary for hdf5-1.14.0-augmponetye5ljzbvc7gfen6i6qenpe6 found: installing from source
==> Using cached archive: /Users/damynchipman/packages/spack/var/spack/cache/_source-cache/archive/a5/a571cc83efda62e1a51a0a912dd916d01895801c5025af91669484a1575a6ef4.tar.gz
==> Applied patch /Users/damynchipman/packages/spack/var/spack/repos/builtin/packages/hdf5/hdf5_1_14_0_config_find_mpi.patch
==> Ran patch() for hdf5
==> hdf5: Executing phase: 'cmake'
==> hdf5: Executing phase: 'build'
==> hdf5: Executing phase: 'install'
==> hdf5: Successfully installed hdf5-1.14.0-augmponetye5ljzbvc7gfen6i6qenpe6
  Stage: 0.66s.  Cmake: 16.59s.  Build: 17.27s.  Install: 1.17s.  Total: 35.73s
[+] /Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/hdf5-1.14.0-augmponetye5ljzbvc7gfen6i6qenpe6
==> Installing diffutils-3.8-bby24ptmeglaehp3r6clqveo6vvdhohy
==> No binary for diffutils-3.8-bby24ptmeglaehp3r6clqveo6vvdhohy found: installing from source
==> Using cached archive: /Users/damynchipman/packages/spack/var/spack/cache/_source-cache/archive/a6/a6bdd7d1b31266d11c4f4de6c1b748d4607ab0231af5188fc2533d0ae2438fec.tar.xz
==> No patches needed for diffutils
==> diffutils: Executing phase: 'autoreconf'
==> diffutils: Executing phase: 'configure'
==> diffutils: Executing phase: 'build'
==> diffutils: Executing phase: 'install'
==> diffutils: Successfully installed diffutils-3.8-bby24ptmeglaehp3r6clqveo6vvdhohy
  Stage: 0.19s.  Autoreconf: 0.32s.  Configure: 47.96s.  Build: 2.70s.  Install: 0.71s.  Total: 51.93s
[+] /Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/diffutils-3.8-bby24ptmeglaehp3r6clqveo6vvdhohy
==> Installing parmetis-4.0.3-mmo7i5d6bslxwavh6gqb56jjplpp6dbl
==> No binary for parmetis-4.0.3-mmo7i5d6bslxwavh6gqb56jjplpp6dbl found: installing from source
==> Using cached archive: /Users/damynchipman/packages/spack/var/spack/cache/_source-cache/archive/f2/f2d9a231b7cf97f1fee6e8c9663113ebf6c240d407d3c118c55b3633d6be6e5f.tar.gz
==> Applied patch /Users/damynchipman/packages/spack/var/spack/repos/builtin/packages/parmetis/enable_external_metis.patch
==> Applied patch /Users/damynchipman/packages/spack/var/spack/repos/builtin/packages/parmetis/pkg-parmetis-1c1a9fd0f408dc4d42c57f5c3ee6ace411eb222b.patch
==> Applied patch /Users/damynchipman/packages/spack/var/spack/repos/builtin/packages/parmetis/pkg-parmetis-82409d68aa1d6cbc70740d0f35024aae17f7d5cb.patch
==> parmetis: Executing phase: 'cmake'
==> parmetis: Executing phase: 'build'
==> parmetis: Executing phase: 'install'
==> parmetis: Successfully installed parmetis-4.0.3-mmo7i5d6bslxwavh6gqb56jjplpp6dbl
  Stage: 0.09s.  Cmake: 0.45s.  Build: 1.08s.  Install: 0.23s.  Total: 1.87s
[+] /Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/parmetis-4.0.3-mmo7i5d6bslxwavh6gqb56jjplpp6dbl
[+] /Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/kokkos-kernels-3.7.01-tuhktteznobe4nnpurmkz6a2g33x45fy
==> Installing superlu-dist-8.1.2-aahyse3teqg4sk6vvpcajx73myax54av
==> No binary for superlu-dist-8.1.2-aahyse3teqg4sk6vvpcajx73myax54av found: installing from source
==> Using cached archive: /Users/damynchipman/packages/spack/var/spack/cache/_source-cache/archive/7b/7b16c442bb01ea8b298c0aab9a2584aa4615d09786aac968cb2f3118c058206b.tar.gz
==> No patches needed for superlu-dist
==> superlu-dist: Executing phase: 'cmake'
==> Error: ProcessError: Command exited with status 1:
    '/opt/homebrew/bin/cmake' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:STRING=/Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/superlu-dist-8.1.2-aahyse3teqg4sk6vvpcajx73myax54av' '-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo' '-DBUILD_TESTING:BOOL=OFF' '-DCMAKE_INTERPROCEDURAL_OPTIMIZATION:BOOL=OFF' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_FIND_FRAMEWORK:STRING=LAST' '-DCMAKE_FIND_APPBUNDLE:STRING=LAST' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=ON' '-DCMAKE_INSTALL_RPATH:STRING=/Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/superlu-dist-8.1.2-aahyse3teqg4sk6vvpcajx73myax54av/lib;/Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/superlu-dist-8.1.2-aahyse3teqg4sk6vvpcajx73myax54av/lib64;/Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/metis-5.1.0-s2jmgo2rxg5wwfnagoxs7ofzozk4rwxv/lib;/opt/homebrew/opt/openblas/lib;/opt/homebrew/lib;/Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/parmetis-4.0.3-mmo7i5d6bslxwavh6gqb56jjplpp6dbl/lib' '-DCMAKE_PREFIX_PATH:STRING=/Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/parmetis-4.0.3-mmo7i5d6bslxwavh6gqb56jjplpp6dbl;/Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/metis-5.1.0-s2jmgo2rxg5wwfnagoxs7ofzozk4rwxv;/opt/homebrew;/opt/homebrew/opt/openblas;/opt/homebrew' '-DCMAKE_C_FLAGS=-Xclang -fopenmp -L/opt/homebrew/opt/libomp/lib -lomp -I/opt/homebrew/opt/libomp/include -std=c99 -Xclang -fopenmp -L/opt/homebrew/opt/libomp/lib -lomp -I/opt/homebrew/opt/libomp/include' '-DCMAKE_CXX_FLAGS=-std=c++11 -Xclang -fopenmp -L/opt/homebrew/opt/libomp/lib -lomp -I/opt/homebrew/opt/libomp/include' '-DCMAKE_Fortran_FLAGS=-Xclang -fopenmp -L/opt/homebrew/opt/libomp/lib -lomp -I/opt/homebrew/opt/libomp/include' '-DCMAKE_C_COMPILER:STRING=/opt/homebrew/bin/mpicc' '-DCMAKE_CXX_COMPILER:STRING=/opt/homebrew/bin/mpic++' '-DCMAKE_INSTALL_LIBDIR:STRING=/Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/superlu-dist-8.1.2-aahyse3teqg4sk6vvpcajx73myax54av/lib' '-DCMAKE_INSTALL_BINDIR:STRING=/Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/superlu-dist-8.1.2-aahyse3teqg4sk6vvpcajx73myax54av/bin' '-DTPL_BLAS_LIBRARIES:STRING=/opt/homebrew/opt/openblas/lib/libopenblas.dylib' '-DTPL_LAPACK_LIBRARIES:STRING=/opt/homebrew/opt/openblas/lib/libopenblas.dylib' '-DTPL_ENABLE_LAPACKLIB:BOOL=ON' '-DUSE_XSDK_DEFAULTS:BOOL=ON' '-DTPL_PARMETIS_LIBRARIES:STRING=-L/Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/parmetis-4.0.3-mmo7i5d6bslxwavh6gqb56jjplpp6dbl/lib -lparmetis;-L/Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/metis-5.1.0-s2jmgo2rxg5wwfnagoxs7ofzozk4rwxv/lib -lmetis' '-DTPL_PARMETIS_INCLUDE_DIRS:STRING=/Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/parmetis-4.0.3-mmo7i5d6bslxwavh6gqb56jjplpp6dbl/include;/Users/damynchipman/packages/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/metis-5.1.0-s2jmgo2rxg5wwfnagoxs7ofzozk4rwxv/include' '-DXSDK_INDEX_SIZE:STRING=32' '-Denable_openmp:BOOL=OFF' '-DCMAKE_DISABLE_FIND_PACKAGE_OpenMP:BOOL=ON' '-DBUILD_SHARED_LIBS:BOOL=ON' '/var/folders/h7/5j0_j37j2qq2mb86sqm7k66m0000gn/T/damynchipman/spack-stage/spack-stage-superlu-dist-8.1.2-aahyse3teqg4sk6vvpcajx73myax54av/spack-src'

4 errors found in build log:
     18    -- Checking whether Fortran compiler supports OSX deployment target flag
     19    -- Checking whether Fortran compiler supports OSX deployment target flag - yes
     20    -- Detecting Fortran compiler ABI info
     21    -- Detecting Fortran compiler ABI info - failed
     22    -- Check for working Fortran compiler: /Users/damynchipman/packages/spack/lib/spack/env/clang/gfortran
     23    -- Check for working Fortran compiler: /Users/damynchipman/packages/spack/lib/spack/env/clang/gfortran - broken
  >> 24    CMake Error at /opt/homebrew/Cellar/cmake/3.24.1/share/cmake/Modules/CMakeTestFortranCompiler.cmake:61 (message):
     25      The Fortran compiler
     26    
     27        "/Users/damynchipman/packages/spack/lib/spack/env/clang/gfortran"
     28    
     29      is not able to compile a simple test program.
     30    

     ...

     33        Change Dir: /private/var/folders/h7/5j0_j37j2qq2mb86sqm7k66m0000gn/T/damynchipman/spack-stage/spack-stage-superlu-dis
           t-8.1.2-aahyse3teqg4sk6vvpcajx73myax54av/spack-build-aahyse3/CMakeFiles/CMakeTmp
     34    
     35        Run Build Command(s):/opt/homebrew/bin/gmake -f Makefile cmTC_a5412/fast && /opt/homebrew/bin/gmake  -f CMakeFiles/cm
           TC_a5412.dir/build.make CMakeFiles/cmTC_a5412.dir/build
     36        gmake[1]: Entering directory '/private/var/folders/h7/5j0_j37j2qq2mb86sqm7k66m0000gn/T/damynchipman/spack-stage/spack
           -stage-superlu-dist-8.1.2-aahyse3teqg4sk6vvpcajx73myax54av/spack-build-aahyse3/CMakeFiles/CMakeTmp'
     37        Building Fortran object CMakeFiles/cmTC_a5412.dir/testFortranCompiler.f.o
     38        /Users/damynchipman/packages/spack/lib/spack/env/clang/gfortran   -Xclang -fopenmp -L/opt/homebrew/opt/libomp/lib -lo
           mp -I/opt/homebrew/opt/libomp/include  -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Dev
           eloper/SDKs/MacOSX13.3.sdk -mmacosx-version-min=13.0 -c /private/var/folders/h7/5j0_j37j2qq2mb86sqm7k66m0000gn/T/damynchi
           pman/spack-stage/spack-stage-superlu-dist-8.1.2-aahyse3teqg4sk6vvpcajx73myax54av/spack-build-aahyse3/CMakeFiles/CMakeTmp/
           testFortranCompiler.f -o CMakeFiles/cmTC_a5412.dir/testFortranCompiler.f.o
  >> 39    gfortran: error: unrecognized command-line option '-Xclang'
  >> 40        gmake[1]: *** [CMakeFiles/cmTC_a5412.dir/build.make:78: CMakeFiles/cmTC_a5412.dir/testFortranCompiler.f.o] Error 1
     41        gmake[1]: Leaving directory '/private/var/folders/h7/5j0_j37j2qq2mb86sqm7k66m0000gn/T/damynchipman/spack-stage/spack-
           stage-superlu-dist-8.1.2-aahyse3teqg4sk6vvpcajx73myax54av/spack-build-aahyse3/CMakeFiles/CMakeTmp'
  >> 42        gmake: *** [Makefile:127: cmTC_a5412/fast] Error 2
     43    
     44    
     45    
     46    
     47    
     48      CMake will not be able to correctly generate this project.

See build log for details:
  /var/folders/h7/5j0_j37j2qq2mb86sqm7k66m0000gn/T/damynchipman/spack-stage/spack-stage-superlu-dist-8.1.2-aahyse3teqg4sk6vvpcajx73myax54av/spack-build-out.txt

==> Error: petsc-3.18.3-aj33zsfyf7i54craw4sgf5v2khgu5gqj: Package was not installed
==> Error: Installation request failed.  Refer to reported errors for failing package(s).
</pre></details>

### Information on your system

Output of `spack debug report`:
```bash
(base) ➜  ~ spack debug report
* **Spack:** 0.20.0.dev0 (0478e5f6847ab062abde450dc709a57d7bd61958)
* **Python:** 3.9.16
* **Platform:** darwin-ventura-m1
* **Concretizer:** clingo
```

Contents of `packages.yaml`:
```bash
(base) ➜  ~ cat .spack/packages.yaml 
packages:
  autoconf:
    externals:
    - spec: autoconf@2.71
      prefix: /opt/homebrew
  automake:
    externals:
    - spec: automake@1.16.5
      prefix: /opt/homebrew
  berkeley-db:
    externals:
    - spec: berkeley-db@4.7.25
      prefix: /usr
  bison:
    externals:
    - spec: bison@2.3
      prefix: /usr
  bzip2:
    externals:
    - spec: bzip2@1.0.8
      prefix: /Users/damynchipman/miniforge3
  cmake:
    externals:
    - spec: cmake@3.24.1
      prefix: /opt/homebrew
  coreutils:
    externals:
    - spec: coreutils@9.1
      prefix: /opt/homebrew
  curl:
    externals:
    - spec: curl@7.88.1+gssapi+ldap+nghttp2
      prefix: /usr
  file:
    externals:
    - spec: file@5.41
      prefix: /usr
  flex:
    externals:
    - spec: flex@2.6.4+lex
      prefix: /usr
  gettext:
    externals:
    - spec: gettext@0.21.1
      prefix: /opt/homebrew
  ghostscript:
    externals:
    - spec: ghostscript@10.01.2
      prefix: /opt/homebrew
    - spec: ghostscript@9.53.3
      prefix: /usr/local
  git:
    externals:
    - spec: git@2.39.2~tcltk
      prefix: /usr
  gmake:
    externals:
    - spec: gmake@4.3
      prefix: /opt/homebrew
    - spec: gmake@3.81
      prefix: /usr
  hdf5:
    externals:
    - spec: hdf5@1.14.2+cxx+fortran+hl~java~mpi+szip~threadsafe+tools api=v114
      prefix: /opt/homebrew
    - spec: hdf5@1.14.1+cxx+fortran+hl~java~mpi+szip~threadsafe+tools api=v114
      prefix: /opt/homebrew
  hwloc:
    externals:
    - spec: hwloc@2.9.2
      prefix: /opt/homebrew
  openjdk:
    externals:
    - spec: openjdk@18.0.2_0
      prefix: /usr
  krb5:
    externals:
    - spec: krb5@1.7-prerelease
      prefix: /usr
  libtool:
    externals:
    - spec: libtool@2.4.7
      prefix: /opt/homebrew
  m4:
    externals:
    - spec: m4@1.4.6
      prefix: /usr
  ncurses:
    externals:
    - spec: ncurses@6.3.20211021+termlib abi=6
      prefix: /Users/damynchipman/miniforge3
    - spec: ncurses@5.7.20081102 abi=5
      prefix: /usr
  ninja:
    externals:
    - spec: ninja@1.11.1
      prefix: /opt/homebrew
  openblas:
    externals:
    - spec: openblas@0.3.24
      prefix: /opt/homebrew/opt/openblas
  openmpi:
    externals:
    - spec: openmpi@4.1.5~cuda~cxx~cxx_exceptions~java~memchecker+pmi~static~wrapper-rpath
        schedulers=slurm
      prefix: /opt/homebrew
    - spec: openmpi@4.1.5%apple-clang@14.0.3 arch=darwin
      prefix: /opt/homebrew
    buildable: false
  openssh:
    externals:
    - spec: openssh@9.0p1
      prefix: /usr
  openssl:
    externals:
    - spec: openssl@3.1.2
      prefix: /opt/homebrew
    - spec: openssl@3.1.1
      prefix: /Users/damynchipman/miniforge3
  perl:
    externals:
    - spec: perl@5.30.3~cpanm+open+shared+threads
      prefix: /usr
    - spec: perl@5.34.0~cpanm+open+shared+threads
      prefix: /usr
  pkg-config:
    externals:
    - spec: pkg-config@0.29.2
      prefix: /opt/homebrew
  python:
    externals:
    - spec: python@3.9.18+bz2+crypt+ctypes+dbm+lzma+nis+pyexpat~pythoncmd+readline+sqlite3+ssl~tkinter+uuid+zlib
      prefix: /opt/homebrew
    - spec: python@3.10.13+bz2+crypt+ctypes+dbm+lzma+nis+pyexpat~pythoncmd+readline+sqlite3+ssl~tkinter+uuid+zlib
      prefix: /opt/homebrew
    - spec: python@3.11.5+bz2+crypt+ctypes+dbm+lzma+nis+pyexpat~pythoncmd+readline+sqlite3+ssl~tkinter+uuid+zlib
      prefix: /opt/homebrew
    - spec: python@3.9.16+bz2+crypt+ctypes+dbm+lzma+nis+pyexpat+pythoncmd+readline+sqlite3+ssl+tix+tkinter+uuid+zlib
      prefix: /Users/damynchipman/miniforge3
    - spec: python@3.9.17+bz2+crypt+ctypes+dbm+lzma+nis+pyexpat~pythoncmd+readline+sqlite3+ssl~tkinter+uuid+zlib
      prefix: /opt/homebrew
    - spec: python@3.10.12+bz2+crypt+ctypes+dbm+lzma+nis+pyexpat~pythoncmd+readline+sqlite3+ssl~tkinter+uuid+zlib
      prefix: /opt/homebrew
    - spec: python@3.11.4+bz2+crypt+ctypes+dbm+lzma+nis+pyexpat~pythoncmd+readline+sqlite3+ssl~tkinter+uuid+zlib
      prefix: /opt/homebrew
    - spec: python@3.9.6+bz2+crypt+ctypes+dbm+lzma+nis+pyexpat~pythoncmd+readline+sqlite3+ssl+tix+tkinter+uuid+zlib
      prefix: /usr
  rsync:
    externals:
    - spec: rsync@2.6.9
      prefix: /usr
  ruby:
    externals:
    - spec: ruby@2.6.10
      prefix: /usr
  sqlite:
    externals:
    - spec: sqlite@3.39.5+fts~functions+rtree
      prefix: /usr
  texlive:
    externals:
    - spec: texlive@20220321
      prefix: /Library/TeX/texbin
  xz:
    externals:
    - spec: xz@5.4.4
      prefix: /opt/homebrew
    - spec: xz@5.2.6
      prefix: /Users/damynchipman/miniforge3
    - spec: xz@5.4.3
      prefix: /opt/homebrew
  zip:
    externals:
    - spec: zip@3.0
      prefix: /usr
  p4est:
    externals:
    - spec: p4est@2.8+mpi
      prefix: /Users/damynchipman/packages/p4est/p4est/build/local
  mpi:
    buildable: false
```

Contents of `compilers.yaml`:
```bash
(base) ➜  ~ cat .spack/darwin/compilers.yaml 
compilers:
- compiler:
    spec: apple-clang@14.0.3
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /opt/homebrew/bin/gfortran
      fc: /opt/homebrew/bin/gfortran
    flags:
      cppflags: -Xclang -fopenmp -L/opt/homebrew/opt/libomp/lib -lomp -I/opt/homebrew/opt/libomp/include
      cflags: -Xclang -fopenmp -L/opt/homebrew/opt/libomp/lib -lomp -I/opt/homebrew/opt/libomp/include
    operating_system: ventura
    target: aarch64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@13.1.0
    paths:
      cc: /opt/homebrew/bin/gcc-13
      cxx: /opt/homebrew/bin/g++-13
      f77: /opt/homebrew/bin/gfortran-13
      fc: /opt/homebrew/bin/gfortran-13
    flags:
      cppflags: -fopenmp
      cflags: -fopenmp
    operating_system: ventura
    target: aarch64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@13.2.0
    paths:
      cc: /opt/homebrew/bin/gcc-13
      cxx: /opt/homebrew/bin/g++-13
      f77: /opt/homebrew/bin/gfortran-13
      fc: /opt/homebrew/bin/gfortran-13
    flags: {}
    operating_system: ventura
    target: aarch64
    modules: []
    environment: {}
    extra_rpaths: []
```

### Additional information

The issue seems to be with my `gfortran` on my Mac. It's installed with brew via `brew install gcc` and the XCode tools are up to date and installed properly. I can compile simple Fortran files with `gfortran` and `mpif90` as expected, including with the flags that are used during the Spack installs. I'm not sure if there's an environment variable that's getting set during the Spack installs that breaks my Fortran.

Output files for `hypre`:
[spack-build-out.txt](https://github.com/spack/spack/files/12588170/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/12588171/spack-build-env.txt)
[config.log](https://github.com/spack/spack/files/12588174/config.log)

Output files for `superlu`:
[spack-build-out.txt](https://github.com/spack/spack/files/12588199/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/12588200/spack-build-env.txt)
[CMakeError.log](https://github.com/spack/spack/files/12588207/CMakeError.log)

Mentioning the maintainers of Petsc:
@balay @BarrySmith @jedbrown 

Mentioning the maintainers of Hypre:
@balay @osborn9 @ulrikeyang 

Mentioning the maintainers of SuperLU:
@balay @gchavez2 @liuyangzhuan @pghysels @xiaoye

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by balay** [comment]
What is your goal (or requirements) here (wrt petsc install)?
- what pkgs do you need with openmp?
- and if openmp is requred - why use xcode compilers? [I see you are trying to mix in brew openp stuff with xcode - to get this working]
- why mix xcode, brew, miniforge3 pkgs? [instead of letting spack install consistent set?] Likely this is the issue with hypre failure (as brew mpi - that is specified might not match the compilers specified to spack)
- superlu build has some issues:  it reuses CFLAGS for FFLAGS [or such]. Since clang and gfortran don't share flags - this fails. [but might work with gcc and gfortran]

**Comment by DamynChipman** [comment]
I'm trying to get a version of petsc that's configured with Kokkos+OpenMP for local development on a new math package in preparation for development on a machine with NVIDIA GPUs (Polaris @ ANL), which would use petsc configured with Kokkos+CUDA. I've been successful using Kokkos+OpenMP on my Mac so far with the mixed configs, but not with petsc. But I'll try to use Spack to install a consistent set.

I'll close this issue based on the fact that my configuration seems to be the issue. Thanks!

**Comment by balay** [comment]
You might try (with a cleaner/consistent spack config):
```
spack install petsc~hypre~superlu_dist+kokkos+openmp
```
or:
```
spack install petsc+kokkos ^kokkos+openmp
```
or
```
spack install petsc%gcc@13.2.0 ....
```
