### ISSUE TITLE
Packages should be able to modify injected compiler flags.

### ISSUE THREAD

**Issue by tgamblin** [LLNL/spack#3998]
@junghans @becker33 @alalazo @adamjstewart @davydden 

We're thinking of adding hooks for package authors, maybe something like:

```python 
class Foo(Package):
    def cflags(self, flags):
        # any of these are legitimate implementations 

        # use env vars to pass to build
        env['CFLAGS'] = flags
        return None  # skip compiler flag injection 

        # or

        # use compiler injected flags only
        return flags

        # or

        # do something special
        return flags + "-special-arg"
```

The interface is notional; here we'd need more methods for other types of flags.  We might end up with just one method.

Basically we'd give the package author a chance to modify the compiler  flags from the spec before we use them in compiler wrappers, and packages could inject new things into the compiler wrappers if needed. Note that the spec would retain the original flags (we can't modify a concrete spec), but at least the package would have a say about them.  

The rationale is that we currently inject without asking, even though for many packages, the natural way to pass flags to a build system is through vars like CFLAGS.  Build systems may want to skip flags for certain files, e.g. If they're known to break things. This would allow them to do that. We'd probably make CFLAGS, not injection, the default for cmake and autotools packages and keep the injection as default in PackageBase.

#3962 is the first package I've seen that *really wants* injected flags, so I thought I'd ping @junghans about this.

Thoughts?

**Comment by junghans** [comment]
Gentoo and Fedora add `-grecord-gcc-switches` to gcc and through a maintainer message if the package overwrites flags internally.

**Comment by davydden** [comment]
i like it, can be handy indeed. From the code snippet above, it looks like you update the `flags`, right?

**Comment by tgamblin** [comment]
@davydden: in the interface above, you're passed the flags from the spec, you can set any env vars you want set, and you return the flags you want injected.

**Comment by alalazo** [comment]
@tgamblin I really like the idea: the callback will act as a 'filter' on what gets injected and can execute arbitrary code during the filtering phase. 

As we are at it I'll bring a more complicated use case: what if we want to filter some flags only from a few source files? For example I want to inject `-O3` (because it makes a performance difference) but filter it to be `-O2` only on a couple of translation units. Do you think it would be worth to design a solution for cases like this one?

**Comment by citibeth** [comment]
This would all be compiler and OS-dependent.  Can someone give a more concrete use case?
