### ISSUE TITLE
Installation issue:  seacas@2022-10-14

### ISSUE THREAD

**Issue by fearsomepirate** [LLNL/spack#40150]
### Steps to reproduce the issue

```console
$ spack spec -l seacas@2022-10-14 %clang@14.0.6
...
```
Input spec
--------------------------------
seacas@2022-10-14%clang@14.0.6

Concretized
--------------------------------
kdqrher  seacas@2022-10-14%clang@14.0.6~adios2+applications+cgns~faodel+fortran~ipo+legacy+matio~metis+mpi+shared~thread_safe+x11 build_system=cmake build_type=Release generator=make arch=linux-almalinux9-zen2
k3z6736      ^cgns@4.3.0%clang@14.0.6~base_scope~fortran+hdf5~int64~ipo~legacy~mem_debug+mpi+scoping+shared~static~testing~tools build_system=cmake build_type=Release generator=make arch=linux-almalinux9-zen2
ulaqsv5          ^hdf5@1.14.1-2%clang@14.0.6~cxx~fortran+hl~ipo~java~map+mpi+shared~szip~threadsafe+tools api=default build_system=cmake build_type=Release generator=make arch=linux-almalinux9-zen2
lhieby2      ^cmake@3.26.3%clang@14.0.6~doc+ncurses+ownlibs~qt build_system=generic build_type=Release arch=linux-almalinux9-zen2
3mg4o3o          ^ncurses@6.4%clang@14.0.6~symlinks+termlib abi=none build_system=autotools arch=linux-almalinux9-zen2
uncfb5w          ^openssl@1.1.1t%clang@14.0.6~docs~shared build_system=generic certs=mozilla arch=linux-almalinux9-zen2
a3meoe4              ^ca-certificates-mozilla@2023-01-10%clang@14.0.6 build_system=generic arch=linux-almalinux9-zen2
joqvycx      ^fmt@10.0.0%clang@14.0.6~ipo+pic~shared build_system=cmake build_type=Release cxxstd=11 generator=make arch=linux-almalinux9-zen2
sfaegga      ^gmake@4.4.1%clang@14.0.6~guile build_system=autotools arch=linux-almalinux9-zen2
7yposks      ^libx11@1.8.4%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
bop3yz2          ^inputproto@2.3.2%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
p3dgjrg          ^kbproto@1.0.7%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
2d2xbs6          ^libxcb@1.14%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
2ze6y52              ^libpthread-stubs@0.4%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
d4v4qpf              ^libxau@1.0.8%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
rmoml3w              ^libxdmcp@1.1.4%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
fk3luga                  ^libbsd@0.11.7%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
waycaql                      ^libmd@1.0.4%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
ysz6v2b              ^python@3.10.10%clang@14.0.6+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=0d98e93,7d40923,f2fd060 arch=linux-almalinux9-zen2
eeyjfue                  ^expat@2.5.0%clang@14.0.6+libbsd build_system=autotools arch=linux-almalinux9-zen2
anffg5k                  ^gettext@0.21.1%clang@14.0.6+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=linux-almalinux9-zen2
htx6g2z                      ^tar@1.34%clang@14.0.6 build_system=autotools zip=pigz arch=linux-almalinux9-zen2
ibs2euz                          ^pigz@2.7%clang@14.0.6 build_system=makefile arch=linux-almalinux9-zen2
q2joh2v                  ^libffi@3.4.4%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
qbzj57p                  ^readline@8.2%clang@14.0.6 build_system=autotools patches=bbf97f1 arch=linux-almalinux9-zen2
aebgtzz                  ^sqlite@3.40.1%clang@14.0.6+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-almalinux9-zen2
pascwju                  ^util-linux-uuid@2.38.1%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
fymiswb                  ^xz@5.4.1%clang@14.0.6~pic build_system=autotools libs=shared,static arch=linux-almalinux9-zen2
jm6uhla              ^xcb-proto@1.15.2%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
dljdfgn          ^perl@5.36.0%clang@14.0.6+cpanm+open+shared+threads build_system=generic arch=linux-almalinux9-zen2
whzhl7j              ^berkeley-db@18.1.40%clang@14.0.6+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-almalinux9-zen2
2bpoglh              ^gdbm@1.23%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
vyc6j4s          ^pkgconf@1.9.5%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
jee7atv          ^util-macros@1.19.3%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
47rwnsa          ^xextproto@7.3.0%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
a2as6hk          ^xproto@7.0.31%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
q6yutuh          ^xtrans@1.4.0%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
tzs42ww      ^matio@1.5.17%clang@14.0.6+hdf5+shared+zlib build_system=autotools arch=linux-almalinux9-zen2
biiqklg          ^zlib@1.2.13%clang@14.0.6+optimize+pic+shared build_system=makefile arch=linux-almalinux9-zen2
yh5wa3z      ^netcdf-c@4.9.2%clang@14.0.6+blosc~byterange~dap~fsync~hdf4~jna+mpi~nczarr_zip+optimize+parallel-netcdf+pic+shared+szip+zstd build_system=autotools arch=linux-almalinux9-zen2
7hvfssu          ^bzip2@1.0.8%clang@14.0.6~debug~pic+shared build_system=generic arch=linux-almalinux9-zen2
7rasomt              ^diffutils@3.9%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
sw6wgae                  ^libiconv@1.17%clang@14.0.6 build_system=autotools libs=shared,static arch=linux-almalinux9-zen2
3zpm7cv          ^c-blosc@1.21.2%clang@14.0.6+avx2~ipo build_system=cmake build_type=Release generator=make arch=linux-almalinux9-zen2
lysjmzw              ^lz4@1.9.4%clang@14.0.6 build_system=makefile libs=shared,static arch=linux-almalinux9-zen2
e2cgpgb              ^snappy@1.1.10%clang@14.0.6~ipo+pic+shared build_system=cmake build_type=Release generator=make arch=linux-almalinux9-zen2
b7zgspp          ^libaec@1.0.6%clang@14.0.6~ipo+shared build_system=cmake build_type=Release generator=make arch=linux-almalinux9-zen2
65pihqw          ^parallel-netcdf@1.12.3%clang@14.0.6~burstbuffer+cxx+fortran+pic+shared build_system=autotools arch=linux-almalinux9-zen2
xghj4by              ^m4@1.4.19%clang@14.0.6+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-almalinux9-zen2
k7uzkqy                  ^libsigsegv@2.14%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
qkvgb5q          ^zstd@1.5.5%clang@14.0.6+programs build_system=makefile compression=none libs=shared,static arch=linux-almalinux9-zen2
tno24e6      ^openmpi@4.1.5%clang@14.0.6~atomics~cuda~cxx~cxx_exceptions~gpfs~internal-hwloc~java~legacylaunchers~lustre~memchecker~orterunprefix+romio+rsh~singularity+static+vt+wrapper-rpath build_system=autotools fabrics=none schedulers=none arch=linux-almalinux9-zen2
lyb3o7j          ^hwloc@2.9.1%clang@14.0.6~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-almalinux9-zen2
k7gyp4h              ^libpciaccess@0.17%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
ii5alck              ^libxml2@2.10.3%clang@14.0.6~python build_system=autotools arch=linux-almalinux9-zen2
yh77ysm          ^numactl@2.0.14%clang@14.0.6 build_system=autotools patches=4e1d78c,62fc8a8,ff37630 arch=linux-almalinux9-zen2
mvjk2ld              ^autoconf@2.69%clang@14.0.6 build_system=autotools patches=35c4492,7793209,a49dd5b arch=linux-almalinux9-zen2
dgbc6ni              ^automake@1.16.5%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
rlfmtge              ^libtool@2.4.7%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
7ggphnk          ^openssh@9.3p1%clang@14.0.6+gssapi build_system=autotools arch=linux-almalinux9-zen2
uib4kns              ^krb5@1.20.1%clang@14.0.6+shared build_system=autotools arch=linux-almalinux9-zen2
a4yzyfr                  ^bison@3.8.2%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
hl52omt              ^libedit@3.1-20210216%clang@14.0.6 build_system=autotools arch=linux-almalinux9-zen2
hrdljxd              ^libxcrypt@4.4.33%clang@14.0.6~obsolete_api build_system=autotools arch=linux-almalinux9-zen2
mr22npe          ^pmix@4.2.3%clang@14.0.6~docs+pmi_backwards_compatibility~python~restful build_system=autotools arch=linux-almalinux9-zen2
akvon4n              ^libevent@2.1.12%clang@14.0.6+openssl build_system=autotools arch=linux-almalinux9-zen2

### Error message

<details><summary>Error message</summary>

<pre>
spack/opt/spack/linux-almalinux9-zen2/gcc-11.3.0/fmt-10.0.0-qbygvmsf5w7y4a4xaemkdvv74j3fvsuo/include/fmt/core.h:1691:7: error: static assertion failed: Cannot format an argument. To make type T formattable provide a formatter<T> specialization: https://fmt.dev/latest/api.html#udt
</pre></details>

### Information on your system

* **Spack:** 0.20.1 (e8658d6493887ef702dd38f0e9ee5870a1651c1e)
* **Python:** 3.9.16
* **Platform:** linux-almalinux9-zen2
* **Concretizer:** clingo

### Additional information

I have tried to build this with gcc 9.1.0, gcc 12.3.0, and gcc 11.3.0. No dice. Note that I am running Alma 9 under WSL. Also tried under Oracle 9.1 under WSL, same result.

@gsjaardema
[spack-build-env.txt](https://github.com/spack/spack/files/12695775/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/12695776/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by gsjaardema** [comment]
It will need an older lib::fmt version.  fmt-9.X should work.  The current fmt-10.X series works with newer versions of SEACAS.  I will check next week to see what I can do to make this work out-of-the-box.

**Comment by fearsomepirate** [comment]
I have found a workaround that should give some insight into the cause. It appears to have been related to fmt 10.0.0. By explicitly overriding fmt 10.0.0 and forcing the build to use 9.1.0:

spack install seacas@2022-10-14 %clang@14.0.6 ^fmt@9.1.0%clang@14.0.6

That works. Now I can force vtk to use this version of seacas.

**Comment by aumuell** [comment]
@gsjaardema I made a PR for seacas which should fix this issue: #39756.
Regarding vtk, there is another one with macos build fixes, which restricts seacas to compatible versions: #39896.
