### ISSUE TITLE
Installation issue: tmux built on rocky9 fails on rocky8 / centos7

### ISSUE THREAD

**Issue by skwde** [LLNL/spack#40233]
### Steps to reproduce the issue

```console
$ spack spec -I tmux%gcc@8.5.0 target=x86_64_v3
Input spec
--------------------------------
 -   tmux%gcc@8.5.0 arch=None-None-x86_64_v3

Concretized
--------------------------------
[+]  tmux@3.3a%gcc@8.5.0~static~utf8proc build_system=autotools arch=linux-rocky9-x86_64_v3
[+]      ^libevent@2.1.12%gcc@8.5.0+openssl build_system=autotools arch=linux-rocky9-x86_64_v3
[+]          ^openssl@1.1.1t%gcc@8.5.0~docs~shared build_system=generic certs=mozilla arch=linux-rocky9-x86_64_v3
[+]              ^ca-certificates-mozilla@2023-01-10%gcc@8.5.0 build_system=generic arch=linux-rocky9-x86_64_v3
[+]              ^perl@5.36.0%gcc@8.5.0+cpanm+open+shared+threads build_system=generic arch=linux-rocky9-x86_64_v3
[+]                  ^berkeley-db@18.1.40%gcc@8.5.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-rocky9-x86_64_v3
[+]                  ^bzip2@1.0.8%gcc@8.5.0~debug~pic+shared build_system=generic arch=linux-rocky9-x86_64_v3
[+]                      ^diffutils@3.9%gcc@8.5.0 build_system=autotools arch=linux-rocky9-x86_64_v3
[+]                          ^libiconv@1.17%gcc@8.5.0 build_system=autotools libs=shared,static arch=linux-rocky9-x86_64_v3
[+]                  ^gdbm@1.23%gcc@8.5.0 build_system=autotools arch=linux-rocky9-x86_64_v3
[+]                      ^readline@8.2%gcc@8.5.0 build_system=autotools patches=bbf97f1 arch=linux-rocky9-x86_64_v3
[+]              ^zlib@1.2.13%gcc@8.5.0+optimize+pic+shared build_system=makefile arch=linux-rocky9-x86_64_v3
[+]      ^ncurses@6.4%gcc@8.5.0~symlinks+termlib abi=none build_system=autotools arch=linux-rocky9-x86_64_v3
[+]      ^pkgconf@1.9.5%gcc@8.5.0 build_system=autotools arch=linux-rocky9-x86_64_v3
```

First I installed the compiler

via 

```sh
spack install gcc@8.5.0 target=x86_64_v3
```

with the concretization

```sh
$ spack spec -I gcc@8.5.0 target=x86_64_v3
Input spec
--------------------------------
 -   gcc@8.5.0 arch=None-None-x86_64_v3

Concretized
--------------------------------
[+]  gcc@8.5.0%gcc@11.3.1~binutils+bootstrap~graphite~nvptx~piclibs~profiled~strip build_system=autotools build_type=RelWithDebInfo languages=c,c++,fortran patches=98a9c96,d4919d6 arch=linux-rocky9-x86_64_v3
[+]      ^diffutils@3.9%gcc@11.3.1 build_system=autotools arch=linux-rocky9-x86_64_v3
[+]          ^libiconv@1.17%gcc@11.3.1 build_system=autotools libs=shared,static arch=linux-rocky9-x86_64_v3
[+]      ^gawk@5.2.1%gcc@11.3.1~nls build_system=autotools arch=linux-rocky9-x86_64_v3
[+]          ^libsigsegv@2.14%gcc@11.3.1 build_system=autotools arch=linux-rocky9-x86_64_v3
[+]          ^readline@8.2%gcc@11.3.1 build_system=autotools patches=bbf97f1 arch=linux-rocky9-x86_64_v3
[+]      ^gmake@4.4.1%gcc@11.3.1~guile build_system=autotools arch=linux-rocky9-x86_64_v3
[+]      ^gmp@6.2.1%gcc@11.3.1+cxx build_system=autotools libs=shared,static patches=69ad2e2 arch=linux-rocky9-x86_64_v3
[+]          ^autoconf@2.69%gcc@11.3.1 build_system=autotools patches=35c4492,7793209,a49dd5b arch=linux-rocky9-x86_64_v3
[+]          ^automake@1.16.5%gcc@11.3.1 build_system=autotools arch=linux-rocky9-x86_64_v3
[+]          ^m4@1.4.19%gcc@11.3.1+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-rocky9-x86_64_v3
[+]      ^libtool@2.4.7%gcc@11.3.1 build_system=autotools arch=linux-rocky9-x86_64_v3
[+]      ^mpc@1.1.0%gcc@11.3.1 build_system=autotools libs=shared,static arch=linux-rocky9-x86_64_v3
[+]      ^mpfr@3.1.6%gcc@11.3.1 build_system=autotools libs=shared,static patches=7a6dd71 arch=linux-rocky9-x86_64_v3
[+]      ^perl@5.36.0%gcc@11.3.1+cpanm+open+shared+threads build_system=generic arch=linux-rocky9-x86_64_v3
[+]          ^berkeley-db@18.1.40%gcc@11.3.1+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-rocky9-x86_64_v3
[+]          ^bzip2@1.0.8%gcc@11.3.1~debug~pic+shared build_system=generic arch=linux-rocky9-x86_64_v3
[+]          ^gdbm@1.23%gcc@11.3.1 build_system=autotools arch=linux-rocky9-x86_64_v3
[+]      ^texinfo@7.0.3%gcc@11.3.1 build_system=autotools arch=linux-rocky9-x86_64_v3
[+]          ^gettext@0.21.1%gcc@11.3.1+bzip2+curses+git~libunistring+libxml2+tar+xz build_system=autotools arch=linux-rocky9-x86_64_v3
[+]              ^libxml2@2.10.3%gcc@11.3.1~python build_system=autotools arch=linux-rocky9-x86_64_v3
[+]              ^tar@1.34%gcc@11.3.1 build_system=autotools zip=pigz arch=linux-rocky9-x86_64_v3
[+]                  ^pigz@2.7%gcc@11.3.1 build_system=makefile arch=linux-rocky9-x86_64_v3
[+]                  ^zstd@1.5.5%gcc@11.3.1+programs build_system=makefile compression=none libs=shared,static arch=linux-rocky9-x86_64_v3
[+]              ^xz@5.4.1%gcc@11.3.1~pic build_system=autotools libs=shared,static arch=linux-rocky9-x86_64_v3
[+]          ^ncurses@6.4%gcc@11.3.1~symlinks+termlib abi=none build_system=autotools arch=linux-rocky9-x86_64_v3
[+]              ^pkgconf@1.9.5%gcc@11.3.1 build_system=autotools arch=linux-rocky9-x86_64_v3
[+]      ^zlib@1.2.13%gcc@11.3.1+optimize+pic+shared build_system=makefile arch=linux-rocky9-x86_64_v3
```

then I loaded and added the compiler

```sh
spack load gcc@8.5.0
spack compiler find
```

finally I installed tmux (with the concretization mentioned above) with

```sh
spack install tmux%gcc@8.5.0 target=x86_64_v3
```

This all worked well, the problem only appears when I try to run tmux on older then rocky9 oses like rocky8 / centos7.

### Error message

<details><summary>Error message</summary>
CentOS7:
<pre>
$ tmux --version
tmux: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by tmux)
tmux: /lib64/libc.so.6: version `GLIBC_2.27' not found (required by tmux)
tmux: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by tmux)
tmux: /lib64/libc.so.6: version `GLIBC_2.26' not found (required by tmux)
tmux: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by tmux)
tmux: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by ~/opt/spack/opt/spack/linux-rocky9-x86_64_v3/gcc-8.5.0/ncurses-6.4-figyufbusxg76hdn7jxjj2rv7dqgl46o/lib/libtinfo.so.6)
tmux: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by ~/opt/spack/opt/spack/linux-rocky9-x86_64_v3/gcc-8.5.0/libevent-2.1.12-bevpbmuytmzowexwl3saoyhphg67pywq/lib/libevent_core-2.1.so.7)
tmux: /lib64/libc.so.6: version `GLIBC_2.25' not found (required by ~/opt/spack/opt/spack/linux-rocky9-x86_64_v3/gcc-8.5.0/libevent-2.1.12-bevpbmuytmzowexwl3saoyhphg67pywq/lib/libevent_core-2.1.so.7)
</pre>
Rocky8:
<pre>
$ tmux --version
tmux: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by tmux)
tmux: /lib64/libc.so.6: version`GLIBC_2.34' not found (required by tmux)
tmux: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by ~/opt/spack/opt/spack/linux-rocky9-x86_64_v3/gcc-8.5.0/ncurses-6.4-figyufbusxg76hdn7jxjj2rv7dqgl46o/lib/libtinfo.so.6)
tmux: /lib64/libc.so.6: version`GLIBC_2.33' not found (required by ~/opt/spack/opt/spack/linux-rocky9-x86_64_v3/gcc-8.5.0/libevent-2.1.12-bevpbmuytmzowexwl3saoyhphg67pywq/lib/libevent_core-2.1.so.7)
</pre>
</details>

### Information on your system

```sh
$ spack debug report
* **Spack:** 0.20.1 (e8658d6493887ef702dd38f0e9ee5870a1651c1e)
* **Python:** 3.9.16
* **Platform:** linux-rocky9-skylake
* **Concretizer:** clingo
```

### Additional information

As mentioned the build works fine, only running tmux on older rhel derivates fails.

I installed everything in an environment with `spack.yaml`

```yaml
spack:
  # add package specs to the `specs` list
  specs:
    - tmux
  view: true
  concretizer:
    unify: true
  packages:
    all:
      compiler:
        - gcc@8.5.0
      target:
        - x86_64_v3
```

I also tried using `os=rhel7` when building on rocky9 but then the build fails.

Since I only recently started using `spack` this probably reflects more my lack of understanding then a real bug?!

In any case it seems like tmux is not using the `gcc` used to build.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by aumuell** [comment]
The error that you get when trying to execute the `tmux` that you built on rocky9 on older derivatives of RHEL is to be expected: when building on rocky9, the tmux binary gets linked against a newer glibc C library from the rocky9 distribution , which also contains newer versions of some of its symbols, and the usage of those newer symbol versions gets recorded into the binary. Older versions of glibc, as present on rocky8, do not contain the versions of symbols that have been added in glibc 2.33. This is what the error message during execution of tmux on rocky8 says.

As newer versions of glibc only add symbols and always keep previous versions of symbols, building on centos7 might create binaries compatible with centos7 up to rocky9.

Recently, a package for glibc was added to spack. I don't know if that can help you with your use case. Someone else might help out here.

More information on glibc symbol versioning: https://developers.redhat.com/blog/2019/08/01/how-the-gnu-c-library-handles-backward-compatibility

**Comment by skwde** [comment]
@aumuell thanks for this reply and explanation. In the past I already built tmux on centos7 which was compatible with rocky8 and 9. Back then I was building it by hand.

Besides that, I figured using the rocky8 compiler to build tmux might at least work on rocky8, but apparently this didn't work as well. I am also not sure how the `glibc` package should help me here, because `gcc` doesn't require it to be built nor does tmux.

I thought by using spack I could emulate centos7 using `os=rhel7` or something similar but that didn't work. Any idea why or what the use case of it is then?

**Comment by haampie** [comment]
Libc is always "external". Your compiler itself has runtime libs that depend on libc, so it's hard to avoid the dependency.

Unless you wanna build gcc + glibc together first: https://github.com/spack/spack/wiki/Building-gcc-with-glibc-together-in-10-easy-steps, but even then, Spack's model doesn't include a node for libc anyways.
