### ISSUE TITLE
Uninstalled packages in the database

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#4026]
I recently tried to uninstall all of my installed packages, but ran into an error message (possibly because I have packages installed from other branches and have been updating my branch). I manually deleted all of my Spack installations and tried running `spack reindex`, but everything is still there. `spack install` properly reinstalls packages, but commands like `spack find` and `spack activate` still point to the old installations. I thought `spack reindex` was supposed to fix this?

**Comment by scheibelp** [comment]
I think this is from #1167: it updated reindex to use old DB records when available but doesn't check if they are installed. I'll try to get a PR out for this soon.

**Comment by alalazo** [comment]
@scheibelp You're right, that case slipped through #1167. If we want to remove altogether the necessity to look into the old DB we could install the `./spack` folder with a `spec.yaml` for external packages. Would that be a viable solution?

**Comment by scheibelp** [comment]
> If we want to remove altogether the necessity to look into the old DB we could install the ./spack folder with a spec.yaml for external packages. Would that be a viable solution?

I think that would work but I'm unclear where they would be stored. I just created #4027 which just adds a check for non-external packages. Does that seem reasonable?

**Comment by alalazo** [comment]
> I think that would work but I'm unclear where they would be stored.

I was thinking of the normal prefix where they would have been installed if they were not external. But #4027 is definitely a good fix to the issue.
