### ISSUE TITLE
Install deprecated python versions

### ISSUE THREAD

**Issue by Daisy-Chilin** [LLNL/spack#40320]
### Summary

Is there a way to install older or deprecatated versions of python? I'd like to install python 2.7.16 however i keep getting an error:
![Screen Shot 2023-10-04 at 12 37 51 PM](https://github.com/spack/spack/assets/88690145/79b08c18-7761-49b4-8e30-237c848d2dad)

Then I checked to see which versions are available using `spack info --all python`, however i do not see any of the python2 versions listed (see screenshots for output). 
![Screen Shot 2023-10-04 at 12 41 27 PM](https://github.com/spack/spack/assets/88690145/7c6a2f97-7ce9-47c4-acd1-df8a6352678f)
![Screen Shot 2023-10-04 at 12 41 05 PM](https://github.com/spack/spack/assets/88690145/b70d60e5-673a-4c9d-b08a-dcb5b4843622)
![Screen Shot 2023-10-04 at 12 43 49 PM](https://github.com/spack/spack/assets/88690145/26a68fb6-7897-44d5-9e69-b7c23be25b6e)

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
You have to use Spack 0.19, which still has the versions (but also marked deprecated).

**Comment by alalazo** [comment]
You can also recover the recipe / extend Python in your own custom repository. Closing since this seems answered, but feel free to reopen if you there is anything else to discuss.
