### ISSUE TITLE
Spack Package Installation, KeyError, Key not Found in  'node["name"]',  error "==> Error: 'name'"

### ISSUE THREAD

**Issue by celikten** [LLNL/spack#40338]
### Steps to reproduce

spack --debug install gcc

### Error message

spack --debug install gcc
==> [2023-10-05-13:44:22.832370] Imported install from built-in commands
==> [2023-10-05-13:44:22.833738] Reading config from file /home/osa/.spack/Spack/etc/spack/defaults/config.yaml
==> [2023-10-05-13:44:22.856535] Reading config from file /home/osa/.spack/Spack/etc/spack/defaults/linux/config.yaml
==> [2023-10-05-13:44:22.875723] Reading config from file /home/osa/.spack/Spack/etc/spack/config.yaml
==> [2023-10-05-13:44:22.895197] Reading config from file /home/osa/.spack/Spack/etc/spack/linux/config.yaml
==> [2023-10-05-13:44:22.914164] Reading config from file /home/osa/.spack/config.yaml
==> [2023-10-05-13:44:22.933407] Reading config from file /home/osa/.spack/linux/config.yaml
==> [2023-10-05-13:44:22.958365] Imported install from built-in commands
==> [2023-10-05-13:44:22.962747] DATABASE LOCK TIMEOUT: 60s
==> [2023-10-05-13:44:22.962830] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-10-05-13:44:22.963034] Reading config from file /home/osa/.spack/Spack/etc/spack/defaults/bootstrap.yaml
==> [2023-10-05-13:44:22.970420] Reading config from file /home/osa/.spack/Spack/etc/spack/bootstrap.yaml
==> [2023-10-05-13:44:22.982128] Reading config from file /home/osa/.spack/Spack/etc/spack/defaults/repos.yaml
==> [2023-10-05-13:44:22.984107] Reading config from file /home/osa/.spack/Spack/etc/spack/repos.yaml
==> [2023-10-05-13:44:22.987124] [BOOTSTRAP CONFIG SCOPE] name=_builtin
==> [2023-10-05-13:44:22.987451] Reading config from file /home/osa/.spack/Spack/etc/spack/defaults/bootstrap.yaml
==> [2023-10-05-13:44:22.994470] Reading config from file /home/osa/.spack/Spack/etc/spack/bootstrap.yaml
==> [2023-10-05-13:44:23.000515] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/osa/.spack/Spack/etc/spack/defaults
==> [2023-10-05-13:44:23.000558] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/osa/.spack/Spack/etc/spack/defaults/linux
==> [2023-10-05-13:44:23.000601] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/osa/.spack/bootstrap/config
==> [2023-10-05-13:44:23.000623] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/osa/.spack/bootstrap/config/linux
==> [2023-10-05-13:44:23.001527] Reading config from file /home/osa/.spack/Spack/etc/spack/defaults/config.yaml
==> [2023-10-05-13:44:23.021517] Reading config from file /home/osa/.spack/Spack/etc/spack/defaults/linux/config.yaml
==> [2023-10-05-13:44:23.040642] Reading config from file /home/osa/.spack/bootstrap/config/linux/config.yaml
==> [2023-10-05-13:44:23.051085] DATABASE LOCK TIMEOUT: 60s
==> [2023-10-05-13:44:23.051137] PACKAGE LOCK TIMEOUT: No timeout
==> [2023-10-05-13:44:23.051319] Reading config from file /home/osa/.spack/bootstrap/config/linux/compilers.yaml
==> [2023-10-05-13:44:23.090667] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1: %gcc target=x86_64
==> [2023-10-05-13:44:23.091114] Reading config from file /home/osa/.spack/Spack/etc/spack/defaults/bootstrap.yaml
==> [2023-10-05-13:44:23.103227] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=x86_64'
==> [2023-10-05-13:44:23.159890] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=x86_64'
==> [2023-10-05-13:44:23.161836] Reading config from file /home/osa/.spack/Spack/etc/spack/defaults/modules.yaml
==> [2023-10-05-13:44:23.174160] Reading config from file /home/osa/.spack/Spack/etc/spack/defaults/linux/modules.yaml
==> [2023-10-05-13:44:23.239613] Reading config from file /home/osa/.spack/Spack/etc/spack/defaults/packages.yaml
==> [2023-10-05-13:44:23.278037] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %gcc target=x86_64
==> [2023-10-05-13:44:23.279531] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
==> [2023-10-05-13:44:23.279575] [BOOTSTRAP MODULE clingo] Try importing from Python
==> [2023-10-05-13:44:23.303258] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.6/prqkzynv2nwko5mktitebgkeumuxkveu" provides the "cling                                                            o" Python module
==> [2023-10-05-13:44:23.303531] Reading config from file /home/osa/.spack/Spack/etc/spack/defaults/concretizer.yaml
==> [2023-10-05-13:44:23.310789] Reading config from file /home/osa/.spack/Spack/etc/spack/concretizer.yaml
==> [2023-10-05-13:44:23.317149] Reading config from file /home/osa/.spack/Spack/etc/spack/defaults/repos.yaml
==> [2023-10-05-13:44:23.319135] Reading config from file /home/osa/.spack/Spack/etc/spack/repos.yaml
==> [2023-10-05-13:44:23.329236] Reading config from file /home/osa/.spack/Spack/etc/spack/defaults/config.yaml
==> [2023-10-05-13:44:23.349520] Reading config from file /home/osa/.spack/Spack/etc/spack/defaults/linux/config.yaml
==> [2023-10-05-13:44:23.369443] Reading config from file /home/osa/.spack/Spack/etc/spack/config.yaml
==> [2023-10-05-13:44:23.388975] Reading config from file /home/osa/.spack/Spack/etc/spack/linux/config.yaml
==> [2023-10-05-13:44:23.408135] Reading config from file /home/osa/.spack/config.yaml
==> [2023-10-05-13:44:23.427245] Reading config from file /home/osa/.spack/linux/config.yaml
Traceback (most recent call last):
  File "/home/osa/.spack/Spack/bin/spack", line 52, in <module>
    sys.exit(main())
  File "/home/osa/.spack/Spack/lib/spack/spack_installable/main.py", line 37, in main
    sys.exit(spack.main.main(argv))
  File "/home/osa/.spack/Spack/lib/spack/spack/main.py", line 1022, in main
    return _main(argv)
  File "/home/osa/.spack/Spack/lib/spack/spack/main.py", line 977, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/home/osa/.spack/Spack/lib/spack/spack/main.py", line 1005, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/home/osa/.spack/Spack/lib/spack/spack/main.py", line 646, in _invoke_command
    return_val = command(parser, args)
  File "/home/osa/.spack/Spack/lib/spack/spack/cmd/install.py", line 358, in install
    install_without_active_env(args, install_kwargs, reporter_factory)
  File "/home/osa/.spack/Spack/lib/spack/spack/cmd/install.py", line 471, in install_without_active_env
    concrete_specs = concrete_specs_from_cli(args, install_kwargs) + concrete_specs_from_file(args)
  File "/home/osa/.spack/Spack/lib/spack/spack/cmd/install.py", line 439, in concrete_specs_from_cli
    args.spec, concretize=True, tests=install_kwargs["tests"]
  File "/home/osa/.spack/Spack/lib/spack/spack/cmd/__init__.py", line 218, in parse_specs
    spec.concretize(tests=tests)  # implies normalize
  File "/home/osa/.spack/Spack/lib/spack/spack/spec.py", line 2959, in concretize
    self._new_concretize(tests)
  File "/home/osa/.spack/Spack/lib/spack/spack/spec.py", line 2931, in _new_concretize
    result = solver.solve([self], tests=tests, allow_deprecated=allow_deprecated)
  File "/home/osa/.spack/Spack/lib/spack/spack/solver/asp.py", line 3011, in solve
    reusable_specs = self._check_input_and_extract_concrete_specs(specs)
  File "/home/osa/.spack/Spack/lib/spack/spack/solver/asp.py", line 2949, in _check_input_and_extract_concrete_specs
    if s.virtual:
  File "/home/osa/.spack/Spack/lib/spack/spack/spec.py", line 1711, in virtual
    return spack.repo.PATH.is_virtual(self.name)
  File "/home/osa/.spack/Spack/lib/spack/spack/repo.py", line 892, in is_virtual
    return have_name and pkg_name in self.provider_index
  File "/home/osa/.spack/Spack/lib/spack/spack/repo.py", line 772, in provider_index
    self._provider_index.merge(repo.provider_index)
  File "/home/osa/.spack/Spack/lib/spack/spack/repo.py", line 1105, in provider_index
    return self.index["providers"]
  File "/home/osa/.spack/Spack/lib/spack/spack/repo.py", line 589, in __getitem__
    self._build_all_indexes()
  File "/home/osa/.spack/Spack/lib/spack/spack/repo.py", line 602, in _build_all_indexes
    self.indexes[name] = self._build_index(name, indexer)
  File "/home/osa/.spack/Spack/lib/spack/spack/repo.py", line 623, in _build_index
    indexer.read(old) if old else indexer.create()
  File "/home/osa/.spack/Spack/lib/spack/spack/repo.py", line 505, in read
    self.index = spack.provider_index.ProviderIndex.from_json(stream, self.repository)
  File "/home/osa/.spack/Spack/lib/spack/spack/provider_index.py", line 294, in from_json
    lambda vpkg, plist: (
  File "/home/osa/.spack/Spack/lib/spack/spack/provider_index.py", line 324, in _transform
    for name, mappings in providers.items()
  File "/home/osa/.spack/Spack/lib/spack/spack/provider_index.py", line 324, in <genexpr>
    for name, mappings in providers.items()
  File "/home/osa/.spack/Spack/lib/spack/spack/provider_index.py", line 323, in <listcomp>
    (name, out_mapping_type([transform_fun(vpkg, pset) for vpkg, pset in mapiter(mappings)]))
  File "/home/osa/.spack/Spack/lib/spack/spack/provider_index.py", line 295, in <lambda>
    spack.spec.SpecfileV4.from_node_dict(vpkg),
  File "/home/osa/.spack/Spack/lib/spack/spack/spec.py", line 4856, in from_node_dict
    name, node = cls.name_and_data(node)
  File "/home/osa/.spack/Spack/lib/spack/spack/spec.py", line 5056, in name_and_data
    return node["name"], node
KeyError: 'name'

### Information on your system

* **Spack:** 0.21.0.dev0 (4ce5d140667125525c09183d574957c64600c46a)
* **Python:** 3.6.9
* **Platform:** linux-ubuntu18.04-cascadelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by leanrdchen00918** [comment]
same issue

**Comment by alalazo** [comment]
Looking at the stacktrace, this might be a malformed provider index. A few questions:
- Did you ever <kbd>Ctrl</kbd>+<kbd>C</kbd> when Spack seemed stuck computing the index? Spack does that on the first run, but it takes some time (from 30secs to a few minutes depending on the platform).
- Can you even concretize `spack spec gcc`?
- Does the issue disappear if you do `spack clean -ab` and try to install again (without exiting using <kbd>Ctrl</kbd>+<kbd>C</kbd> )?

**Comment by celikten** [comment]
Actually, I didn't do any  <kbd>Ctrl</kbd>+<kbd>C</kbd> things while installing any package. 
When I first tried the <kbd>spack spec gcc</kbd> command after your questions, I got the same error from spack.  However, after <kbd>spack clean -ab</kbd> command, the error disappeared and spack worked!
Thanks!

**Comment by alalazo** [comment]
Ok, I'll close the issue then. This is a case where a cache index was written in a malformed way, for any reason. Thanks for the feedback.
