### ISSUE TITLE
Spack add parser: Unbounded version specifier followed by another spec 

### ISSUE THREAD

**Issue by rfeki** [LLNL/spack#40342]
### Steps to reproduce

An error occur when running this command:
```spack add opa-psm2^cuda@10.2: nccl
Error: 10.2:nccm is an empty range
```
You can reproduce this whenever you have 2 specs to add, use unbounded version specifier as last part of the first spec. 
It seems like the parser does not treat nccl in this case as a new spec but as the upper bound of the version.

Also, for some reason the last character of the second spec is incremented like in this example: nccl become nccm.
When I used package opa-psm2 instead of nccl, the error would be: Error: 10.2:opa-psm3 is an empty range

### Information on your system

* **Spack:** 0.21.0.dev0 (38dc3a6896f64b894adead3446e8f822f878860b)
* **Python:** 3.6.5
* **Platform:** linux-rhel8-cascadelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
@alalazo why are whitespaces supported in a version range/list? Has this always been the case? It's ambiguous, should be disallowed.

**Comment by haampie** [comment]
For a better error message see #40345
