### ISSUE TITLE
request: add sdfs package

### ISSUE THREAD

**Issue by Pandapip1** [LLNL/spack#40389]
### Summary

https://opendedup.org/odd/download/

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
Feel free to submit a recipe, and ping for review!

**Comment by alalazo** [comment]
FYI, we usually use "feature" to indicate features on the core Spack tool

**Comment by Pandapip1** [comment]
> FYI, we usually use "feature" to indicate features on the core Spack tool

I had to select either 'feature' or 'bug' when submitting an issue. That's why I picked the feature label. You might want to fix that and/or direct users to create a PR (it's possible with a config file).
