### ISSUE TITLE
Variant.__init__ logic error when values == '*'

### ISSUE THREAD

**Issue by tjfulle** [LLNL/spack#40405]
### Steps to reproduce

When setting `variant(name, default, description, values="*")`, [`spack.variant.Variant` sets `self.single_value_validator = lambda x: True`](https://github.com/spack/spack/blob/6c7b2e1056bbd158544da9b6a79fd4099c18cd7a/lib/spack/spack/variant.py#L62).  But, logic block started on [line 77](https://github.com/spack/spack/blob/6c7b2e1056bbd158544da9b6a79fd4099c18cd7a/lib/spack/spack/variant.py#L77)  overwrites whatever `self.single_value_validator` was previously set to.  The solution appears to be replacing `if callable` with `elif callable`.

### Error message

No particular error message, but the `"*"` wildcard is not obeyed.

### Information on your system

System independent.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
I agree that how it is coded right now this is a bug. However, the `*` is mostly used for queries like:
```console
$ spack find -v shared=*
-- linux-ubuntu20.04-icelake / gcc@9.4.0 ------------------------
zlib@1.3+optimize+pic+shared build_system=makefile
==> 1 installed package
```
Looking at the recipes in the builtin repository, I see that we have 0 cases of:
```
values="*"
```
and multiple cases of:
```
values=str
```
So, I was wondering how you uncovered this bug, and in which use case you want to use `values="*"`.

**Comment by tjfulle** [comment]
I define

```python
class MyPackage(CMakePackage):
    variant(
        "extra_cmake_args",
        default="none",
        values="*",
        multi=True,
        description="Comma separated list of extra cmake arguments",
    )
```

To allow sending arbitrary CMake arguments to a package.  Eg, `spack install my-package extra_cmake_args="-DDoSomethingCool:BOOL=ON"`

**Comment by alalazo** [comment]
Curious, why not `values=str` as many other packages do?
