### ISSUE TITLE
Error unpacking spack mirror inside container

### ISSUE THREAD

**Issue by tjfulle** [LLNL/spack#40410]
Our workflow for building packages on air-gapped systems is to create a Spack mirror on one system, transfer it to the air-gapped system, and build packages in a container using the mirror.  When un-archiving packages archives inside the container we hit errors from `tar` because the owner of the file is different from the owner in the mirror (`root`).  Adding `--no-same-owner` to the `tar` unarchiving command at https://github.com/spack/spack/blob/6c7b2e1056bbd158544da9b6a79fd4099c18cd7a/lib/spack/spack/util/compression.py#L71 fixes the problem.

**Comment by haampie** [comment]
Are you talking about source mirror or binary mirror?

The code you're referring to already has `-o`.

Binary cache install uses Python's `tarfile`, but should work regardless, cause tarballs are constructed with uid 0 (so root chowns to root)

**Comment by tjfulle** [comment]
@haampie - I am referring to source mirrors.  Without the suggested modification, I have been unable to get sources to untar inside of containers.

**Comment by tjfulle** [comment]
I don't think `-o`  helps in this situation.  For our use case we have a source mirror that is copied into a container.   When the source are untarred by root, tar will by default preserve the original ownership (to my understanding).  But, the original owner of the file doesn't exist inside the container and the untar operation fails.

That is the error message I get and seems to be consistent with the `tar` documentation:


```
     --no-same-owner
             (x mode only) Do not extract owner and group IDs.  This is the reverse of --same-owner and the default behavior if tar is run as non-root.
    -o      (x mode) Use the user and group of the user running the program rather than those specified in the archive.  Note that this has no significance unless -p is specified, and the program is being run
             by the root user.  In this case, the file modes and flags from the archive will be restored, but ACLs or owner information in the archive will be discarded.
```

From my reading, when run as `root`, `-o` does nothing if `-p` is not also given.  It seems that `--no-same-owner` would have to be used in any case to avoid the situation I explained above.

to my understanding `-o` doesn't do anything when run as root.

**Comment by haampie** [comment]
@tjfulle didn't see your message until now.

> Note that this has no significance unless -p is specified, and the program is being run by the root user

Well, it only needs to be fixed when run by root, and `-p` is  the default when tar is run as root.

What tar are you using? GNU tar says

> When extracting, same as --no-same-owner.

And I don't really see how your tar docs conflict with that.

**Comment by tjfulle** [comment]
@haampie - I am using whatever version of tar comes with the ubuntu and redhat containers.

I have only run into this issue when:

- running as root in the container; and
- the mirror was created outside of the container and copied in
 
#40411 has a fix.

**Comment by tjfulle** [comment]
My reading of the documents is that if tar is run as `root`, the files will maintain original ownership by default.  For the case that a mirror is created outside of the container and copied in, `tar` fails to extract the contents of the archive because the original owner does not exist in the container.  That is what I am seeing when I try to install in a container if the fix in #40411 is not applied.

**Comment by tgamblin** [comment]
@tjfulle @psakievich: can you give more details on the errors you're getting here?  The issue is really that if we add `--no-same-owner` to `tar`, it'll break on macOS.  If we can get away with using only [posix arguments](https://pubs.opengroup.org/onlinepubs/7908799/xcu/tar.html) we can worry a lot less about compatibility.

It would help to see what error you're seeing inside the container b/c I don't get why `-o` would not behave in the container, *unless* maybe something is screwy with fake root in the container?  I wonder if GNU tar is using real or effective uid...

**Comment by tjfulle** [comment]
Thanks @tgamblin - I'll post a MWE in a couple hours.

FWIW, I hit this error with RH ubi8 image using podman on a Linux host and ubuntu:latest using docker on a macOS host.

**Comment by psakievich** [comment]
I'm testing with one of the spack produced containers. But I'm a little clunky with docker so it is taking me a while :sweat_smile:

**Comment by tjfulle** [comment]
@tgamblin - it turns out that I originally ran into the problem with an older version from spack, before [`-o`](https://github.com/spack/spack/pull/17427/commits/2f4c220a6aeb6c04d93d2ed2ab4dd8c435479416#diff-5872c9f40480183591dddc973e8d10f4c3998bf51bb742cfa5f4d43992a4a846R39) was added to the untar command.  I patched my fork at the time and kept cherry picking that patch up to the current version.

**Comment by tgamblin** [comment]
oh awesome -- that was easy!
