### ISSUE TITLE
Installation issue: proj - No spec with name libtiff

### ISSUE THREAD

**Issue by uturuncoglu** [LLNL/spack#40456]
### Steps to reproduce the issue

```console
$ spack spec -I proj@4.9.2~shared~tiff
Input spec
--------------------------------
 -   proj@4.9.2~shared~tiff

Concretized
--------------------------------
 -   proj@4.9.2%gcc@11.4.0+curl~pic~shared~tiff build_system=autotools arch=linux-ubuntu22.04-aarch64
[+]      ^gnuconfig@2022-09-17%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-aarch64
```

### Error message

<details><summary>No spec with name libtiff</summary>

<pre>
==> Installing proj-4.9.2-4f5i32zbkaegkntndsdc3skf6v77wqbz
==> No binary for proj-4.9.2-4f5i32zbkaegkntndsdc3skf6v77wqbz found: installing from source
==> Using cached archive: /opt/spack-stack/cache/source_cache/_source-cache/archive/60/60bf9ad1ed1c18158e652dfff97865ba6fb2b67f1511bc8dceae4b3c7e657796.tar.gz
==> Using cached archive: /opt/spack-stack/cache/source_cache/_source-cache/archive/3f/3ff6618a0acc9f0b9b4f6a62e7ff0f7bf538fb4f74de47ad04da1317408fcc15.tar.gz
==> No patches needed for proj
==> proj: Executing phase: 'autoreconf'
==> proj: Executing phase: 'configure'
==> Error: KeyError: 'No spec with name libtiff in proj@4.9.2%gcc@11.4.0+curl~pic~shared~tiff build_system=autotools arch=linux-ubuntu22.04-aarch64 ^gnuconfig@2022-09-17%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-aarch64'
See build log for details:
  /opt/spack-stack/cache/build_stage/root/spack-stage-proj-4.9.2-4f5i32zbkaegkntndsdc3skf6v77wqbz/spack-build-out.txt
</pre></details>

### Information on your system

* **Spack:** 0.20.0.dev0 (a041f7d05c59a90c2a37b281ac73052c9786a130)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-aarch64
* **Concretizer:** clingo

### Additional information

@adamjstewart I am getting error from proj like `No spec with name libtiff`.

[spack-build-env.txt](https://github.com/spack/spack/files/12873745/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/12873746/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by uturuncoglu** [comment]
@adamjstewart If I remove `libtiff` occurrences from `package.py` it compiles without any issue. BTW, for this version `~tiff` is default.

**Comment by adamjstewart** [comment]
This is easy to fix, will try to submit a PR tonight or tomorrow.

**Comment by uturuncoglu** [comment]
@adamjstewart Thank you.

**Comment by adamjstewart** [comment]
@uturuncoglu you're using `proj~shared`, but the `proj` package doesn't have a `+shared` variant. Are you using a fork of Spack? Do you encounter this issue with upstream Spack or only on your fork?

**Comment by uturuncoglu** [comment]
@adamjstewart Yes, I am using following fork - https://github.com/jcsda/spack. It is not too old and dated to Jul 3. Do you want me to test with head of develop.

**Comment by adamjstewart** [comment]
That fork contains bugs that upstream doesn't. Specifically, #40322 before the last commit. I wouldn't recommend using package recipes before they've been accepted upstream.

**Comment by uturuncoglu** [comment]
@adamjstewart Okay. Thanks. I could update spack in my end. I don't need to use fork. Anyway, thanks for your help. Best,
