### ISSUE TITLE
Allow Spack to activate non-default views

### ISSUE THREAD

**Issue by moloney** [LLNL/spack#40501]
### Steps to reproduce

If the "view" element just references a path the activation works as expected (PATH and other environment variables get updated appropriately):

```console
$ cat path/to/env1/spack.yaml
spack:
  specs: []
  view: /path/to/env1_view
  concretizer:
    unify: true
$ spack env activate --sh env1 | grep PATH
export PATH=/path/to/env1_view/bin:...;
``` 

However, if I try to pass a dict as the view (even the simplest possible) then it will fail to set any environment variables during activation:

```console
$ cat path/to/env2/spack.yaml
spack:
  specs: []
  view: 
    myview:
      root: /path/to/env2_view
  concretizer:
    unify: true
$ spack env activate --sh env2
export SPACK_ENV=/home/exacloud/gscratch/airc/byoe/spack/var/spack/environments/test-env;
alias despacktivate='spack env deactivate';
``` 

### Error message

No error messages are produced, the output is just wrong.

### Information on your system

* **Spack:** 0.21.0.dev0
* **Python:** 3.6.8
* **Platform:** linux-centos7-haswell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Currently:
```console
$ spack env activate ...
```
only uses the view called `"default"`. So, in your case I assume that if you change `myview` with `default` the environment variables would be set.

**Comment by alalazo** [comment]
This is also [documented here](https://spack.readthedocs.io/en/latest/environments.html#activating-environment-views), where the stress is on the words "default view". I don't see why though we can't do something like:
```console
$ spack env activate -v myview .
```
to specifically select a view to activate. That would be a new feature, not a bug to fix (so I'm changing the label).

**Comment by pranav-sivaraman** [comment]
I am also interested in this feature and would like to contribute in implementing this. Any recommendation on where should I begin within the repository?
