### ISSUE TITLE
Support local directory as source

### ISSUE THREAD

**Issue by mathstuf** [LLNL/spack#40548]
### Summary

It seems that, at some point, using a local directory as a `develop` source was lost to some URL verification and then something tries to download it later. Maybe there should be a flag to indicate that a source tree is being handed over?

### Rationale

The intended use case is to test Spack against ParaView in CI where we already have a source tree prepped by CI.

### Description

Maybe `version(is_source_dir=True)` is enough?

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
It's unclear what you are talking about, please expand

**Comment by mathstuf** [comment]
In ParaView's CI, we have our own `package.py`. I'd like to be able to specify the `develop` version to use the already-checked out source tree rather than downloading an artifact.

**Comment by haampie** [comment]
https://spack-tutorial.readthedocs.io/en/sc21/tutorial_developer_workflows.html
