### ISSUE TITLE
Concretization non-deterministic with separate concretization of build deps

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#40595]
### Steps to reproduce

Seen this is in Gitlab CI, where a new commit didn't change anything, but caused a rebuild of `gptune`.

Diffing the concrete specs, I've found that certain packages flip between using py-cython@3 and py-cython@0:

```python
In [1]: [p.name for p in next(x for x in spack.spec.Spec("./first.json").traverse() if x.satisfies("py-cython@3")).dependents()]
Out[1]: ['py-gevent']

In [2]: [p.name for p in next(x for x in spack.spec.Spec("./first.json").traverse() if x.satisfies("py-cython@0")).dependents()]
Out[2]: 
['py-numpy',
 'py-pandas',
 'py-gpy',
 'py-scipy',
 'py-configspace',
 'py-statsmodels',
 'py-pyzmq',
 'py-pyyaml',
 'py-mpi4py',
 'py-scikit-learn']
```

```python
In [1]: [p.name for p in next(x for x in spack.spec.Spec("./second.json").traverse() if x.satisfies("py-cython@3")).dependents()]
Out[1]: ['py-configspace', 'py-gevent']

In [2]: [p.name for p in next(x for x in spack.spec.Spec("./second.json").traverse() if x.satisfies("py-cython@0")).dependents()]
Out[2]: 
['py-numpy',
 'py-pandas',
 'py-gpy',
 'py-scipy',
 'py-statsmodels',
 'py-pyzmq',
 'py-pyyaml',
 'py-mpi4py',
 'py-scikit-learn']
```

The relevant package `py-configspace` does not set any constraint on `py-cython`.

See the attached spec files:

[second.json](https://github.com/spack/spack/files/13030345/second.json)
[first.json](https://github.com/spack/spack/files/13030343/first.json)

### Information on your system

.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
https://gitlab.spack.io/spack/spack/-/pipelines/526310 triggered 85 rebuilds, possibly the same issue.

Yeah, this one seems to rebuild `meson`, *only* because it picks `py-setuptools` in a non-deterministic way, which occurs just once:

```
$ spack spec --cover edges ./a.json | grep py-setuptools
 -       ^py-setuptools@68.0.0%gcc@11.1.0 build_system=python_pip arch=linux-ubuntu20.04-x86_64_v3

$ spack spec --cover edges ./b.json | grep py-setuptools
 -       ^py-setuptools@63.4.3%gcc@11.1.0 build_system=python_pip arch=linux-ubuntu20.04-x86_64_v3
```

Is something wrong with the optimization criteria? Probably still has to do with separate concretization, but it's curious that issues happen too when there's only one instance of these build deps. 

[a.json](https://github.com/spack/spack/files/13043082/a.json)
[b.json](https://github.com/spack/spack/files/13043084/b.json)

**Comment by alalazo** [comment]
This might be an unwanted consequence of:
1. Having minimal duplication on by default
2. Minimizing only on node attributes

That might lead to DAG with different wirings of the same nodes to be equivalent to clingo. I'll look at this asap

**Comment by alalazo** [comment]
Ok, confirmed that https://github.com/spack/spack/issues/40595#issuecomment-1770978619 is an issue. This simple problem:

[float.txt](https://github.com/spack/spack/files/13050857/float.txt)

that I'll use for a unit test has different optimal solutions where a py-setuptools edge is "floating" among two nodes that are in the graph.

**Comment by haampie** [comment]
Right. The meson example from my second comment is likely not useful on its own, since it's only a subdag of the root spec. So, even though py-setuptools only occurs once, and a different version is picked, it's probably because the root has one subdag with meson and another one with another version of setuptools.
