### ISSUE TITLE
Installation issue: intel-oneapi-compilers (and aocc) installs under GCC in package hierarchy

### ISSUE THREAD

**Issue by pbisbal1** [LLNL/spack#40597]
### Steps to reproduce the issue

```console
# spack install gcc

# spack load gcc@13.2.0

# spack compiler find
==> Added 1 new compiler to /root/.spack/linux/compilers.yaml
    gcc@13.2.0
==> Compilers are defined in the following files:
    /root/.spack/linux/compilers.yaml

# spack install aocc +license-agreed

# spack load aocc

# spack compiler find
==> Added 1 new compiler to /root/.spack/linux/compilers.yaml
    aocc@4.1.0
==> Compilers are defined in the following files:
    /root/.spack/linux/compilers.yaml

# spack unload aocc

# spack install intel-oneapi-compilers

```

### Error message

I'm not sure if this is a general spack issue, or if it's specific to intel-oneapi-compilers and aocc. 

intel-oneapi-compilers (and aocc) are installed as if they're dependent on gcc@13.2.0:

<pre>
# spack find
-- linux-rhel9-zen2 / gcc@11.3.1 --------------------------------
autoconf@2.69                berkeley-db@18.1.40  gawk@5.1.0  gmake@4.3      m4@1.4.19   ncurses@6.4    readline@8.2   zstd@1.5.5
autoconf-archive@2023.02.20  bzip2@1.0.8          gcc@13.2.0  gmp@6.2.1      mpc@1.3.1   perl@5.38.0    texinfo@6.7
automake@1.16.2              diffutils@3.7        gdbm@1.23   libtool@2.4.6  mpfr@4.2.0  pkgconf@1.7.3  zlib-ng@2.1.3

-- linux-rhel9-zen2 / gcc@13.2.0 --------------------------------
aocc@4.1.0       diffutils@3.7  intel-oneapi-compilers@2023.2.1  libxml2@2.10.3  patchelf@0.17.2  xz@5.4.1
autoconf@2.69    gawk@5.1.0     libiconv@1.17                    m4@1.4.19       pkgconf@1.7.3    zlib-ng@2.1.3
automake@1.16.2  gmake@4.3      libtool@2.4.6                    ncurses@6.4     texinfo@6.7
==> 39 installed packages
</pre>

This is counterintuitive. I would expect compiler packages to be installed independent of other compilers by default. This creates a couple of problems: 

1.  I intend to use Lmod for environment modules. In this case, aocc and intel-oneapi-compilers are not treated as core-level modules, which breaks desired behavior Lmod: if I switch compilers from gcc to intel-oneapi-compilers, the packages built for gcc are removed from my path, but the packages built for Intel are not added to my path. 
2.  When building other applications with dependencies for intel, it sees those dependencies are already built for GCC, so it doesn't build them again for Intel. This isn't good, since Fortran and C++ libraries built w/ different compilers usually aren't compatible. 

I suspect I can fix this by specifying "^gcc@11.3.1" (the system GCC on my system) and specifying these compilers as core_compilers in modules.yaml, but I would think the default would be to not install compiler packages as compiler-dependent packages themselves. Am I thinking about this wrong, or I am I doing something wrong? I'm very new to Spack (but not software management), so I readily admit my mindset or configuration could be wrong. 

### Information on your system

# spack debug report
* **Spack:** 0.21.0.dev0 (74bbb1ef1bd44283194dc1eea065a066f2387b59)
* **Python:** 3.9.16
* **Platform:** linux-rhel9-zen2
* **Concretizer:** clingo

```console
# cat ~/.spack/modules.yaml 
modules:
  default:
    lmod:
      core_compilers:
      - gcc@=11.3.1
```

The system-wide modules.yaml and packages.yaml files have little/no customization. 

### Additional information

The builds aren't really failing not sure if this is spack-wide issue, package issue, or operator error. 

@rscohn2 
@amd-toolchain-support 
@pschei

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by pbisbal1** [comment]
@scheibelp

**Comment by rscohn2** [comment]
The intel compilers do not come with header files or libraries for the standard APIs. It invokes g++ to get the path for header files and libraries. In your example, icpx will use the same header files and libraries as gcc@13.2.0 . You can  mix g++ and icpx compiled objects because they are all compiled with the same header files. I do not know enough about modules to comment on that issue.

**Comment by pbisbal1** [comment]
Robert,

Thanks for the reply. I've been playing around with this some more this afternoon, and I think the solution is to tell spack to build intel-oneapi-compilers and aocc with my core compiler (GCC 11.3.1) to get everything to work as I want it to. Before I was leaving the compiler version off the spec (%gcc instead of %gcc@11.3.1) so it was using 13.2.0. I think this can be chalked up to my inexperience with spack (user error).

This issue can be closed now.

Prentice
