### ISSUE TITLE
My CI builds broke, something changed with build dependencies or ...

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#4064]
I have a jenkins jobs that builds all of my things every night.

The build at Apr 30, 2017 2:28:42 AM succeeded, using `develop` at 0a9beccc4a4d7336e002d1fbcc2cf77c2d41ecbb.

Last night's build failed while building `direnv` and I'm trying to understand why and what might have changed.  I tried another build this morning and it also failed.

When I cd'ed into the workspace of the failed build and ran

```
spack stage direnv
pushd /path/to/stage/dir/goes/here
spack env direnv bash
cd direnv-2.11.3
go build
```

it fails with

```
_/scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/var/spack/stage/direnv-2.11.3-wixlanate5jvl752xxua5j5wzprohhvn/direnv-2.11.3
./log.go:47: undefined: log.Output
```

That line's a simple:

```
        log.Output(2, msg)
```

Out of habit I checked which go compiler I was using and found that I was invoking the old bootstrap compiler:

```
$ which go
/scratch/hartzelg/spack-cime-sc1-working-dir/workspace/sc1-daily-build/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/go-bootstrap-1.4-bootstrap-20161024-bjdc3swkpiscyoysx5hu6oxleaovrtt5/bin/go
```

Sure enough, it's been prepended to `$PATH`:

```
$ (module purge; spack env direnv | egrep '^PATH=' | perl -lape 's/:/\n/g')
PATH=.
/blah/blah/blah/spack/lib/spack/env
/blah/blah/blah/spack/lib/spack/env/case-insensitive
/blah/blah/blah/spack/lib/spack/env/gcc
/blah/blah/blah/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/go-bootstrap-1.4-bootstrap-20161024-bjdc3swkpiscyoysx5hu6oxleaovrtt5/bin
/blah/blah/blah/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/gdbm-1.13-5o4l6t7ovwa74n4l4kc6dh4l2vj55geq/bin
/blah/blah/blah/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/perl-5.24.1-6eeiyzpngdxb3qhtfxeh277qe6sau4ip/bin
/blah/blah/blah/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/pcre-8.40-rnjaow53pneai2d23pgrq7wzeg2k5p5/bin
/blah/blah/blah/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/gettext-0.19.8.1-qtf3fmomputuj4vsql5e5pjokhwqvitr/bin
/blah/blah/blah/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/expat-2.2.0-zv7petry2d3upbwlfq2mig7njqwae7ef/bin
/blah/blah/blah/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/openssl-1.0.2k-5s7cetd6mdyveeiqqas6rtcwjvyp3afq/bin
/blah/blah/blah/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/curl-7.53.1-5abaxzgglvlebmkn777wx56fzoit6qmk/bin
/blah/blah/blah/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/automake-1.15-zbemo7uxhl54iactqivinmc4ufzpt4gi/bin
/blah/blah/blah/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/m4-1.4.18-ipesuzrivyks743qv7licjfyrqyvxsifkdkpsvt25b3f/bin
/blah/blah/blah/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/libtool-2.4.6-vwgxyfslc5ia6zlesisvn2e3mwvpduaz/bin
/blah/blah/blah/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/libiconv-1.15-dbp3qyi2m6silluqhrrig6ku55guewic/bin
/blah/blah/blah/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/tar-1.29-famxnoser4n2j4blic4fknc7py4htkq5/bin
/blah/blah/blah/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/ncurses-6.0-43qxlcy2renpowsmlfbhqfek2bcm/bin
/blah/blah/blah/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/xz-5.2.guvl5civei5atlkimcrjg6ctpukc6/bin
/blah/blah/blah/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/bzip2-1.0.6-egkg2fbrc3-ehlxwhosxgdfbduwx3nk5zzxmo4qhmaq/bin
/blah/blah/blah/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/pkg-config-0.29.2-cuidxoskfchduid5ebedi/bin
/blah/blah/blah/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/autoconf-2.69-6lvs34zg44gjie4yonsck6lfd4sbobu5/bin
/blah/blah/blah/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/git-2.12.1-nv53m34ehjvxcf23ox7bf223a66p7wkk/bin
/blah/blah/blah/spack/opt/spack/linux-centos7-x86_64/gcc-5.4.0/go-1.8.1-w2kg27p5h6z6bh4pgjcparpochlqhfwx/bin
/blah/blah/blah/spack/bin
/usr/local/bin
/usr/bin
/opt/ibutils/bin
/usr/local/sbin
/usr/sbin
```

direnv has a build dependency on go, go has a build dependency on go-bootstrap.

Here's the base environment in which spack is running:

```
$ (module purge; echo ${PATH} | perl -lape 's/:/\n/g')
/blah/blah/blah/spack/bin
/usr/local/bin
/usr/bin
/opt/ibutils/bin
/usr/local/sbin
/usr/sbin
```

On a possibly related note, I noticed that the version of go that has been installed is `go@1.8.1`, in spite of having it pinned to `go@1.8` in my `packages.yaml` file.

```yaml
  go:
    version: [1.8]
    # tests have two false positives, user_namespaces and threads/exceptions
    variants: ~test
```

**Comment by davydden** [comment]
maybe somehow related to https://github.com/LLNL/spack/pull/3910 ?

**Comment by adamjstewart** [comment]
That would be my first suspicion as well.

**Comment by adamjstewart** [comment]
I think the real problem here is that `go-bootstrap` shouldn't be in the `PATH` at all. It's a build dependency needed to build the correct `go` package.

**Comment by adamjstewart** [comment]
@scheibelp Should build dependencies of dependencies be in the `PATH`?

**Comment by davydden** [comment]
> Should build dependencies of dependencies be in the PATH

i would say no, this something is needed only to build a dependency, but not to use it in another package.

**Comment by adamjstewart** [comment]
I also think the order that dependencies are returned should be a bit more deterministic. A BFS would be nice. That way direct dependencies will always show up first in the `PATH`.

**Comment by scheibelp** [comment]
> @scheibelp Should build dependencies of dependencies be in the PATH

If X->Y->Z, and Z is a build dep of Y, then when building Y, Z should be in Y's path; when building X, Z should not be in X's path (unless X declares a direct build dependency on Z).

(#3768 should be consistent with this - not that I expect folks to consult it but that I mean to mention it wherever I think it's relevant)

**Comment by davydden** [comment]
@adamjstewart @scheibelp 

probably 
```
build_deps      = pkg.spec.traverse(root=False, deptype=('build'))
```
should actually be
```
build_deps      =  pkg.spec.dependencies(deptype='build')
```
to satisfy

> If X->Y->Z, and Z is a build dep of Y, then when building Y, Z should be in Y's path; when building X, Z should not be in X's path (unless X declares a direct build dependency on Z).

**Comment by hartzell** [comment]
I'll bisect and see if #3910 seems to be the culprit.  Simplest thing to do is just run the builds, so it'll take some time (they can run in parallel, but still...).

If I understand @scheibelp, then what I've observed is not the intended behavior.  Is that correct?

**Comment by hartzell** [comment]
The commit before #3910 built, the commit from #3910 failed.

I'll test @davydden's fix.

**Comment by adamjstewart** [comment]
I'm still curious what changed. I didn't intend to change any behavior in #3910 aside from filtering system paths. If you can figure out what line I broke, let me know.

**Comment by davydden** [comment]
@adamjstewart maybe dropping `reversed` https://github.com/LLNL/spack/pull/3910/files#r112293815 ?

**Comment by adamjstewart** [comment]
Ah, so indirect build dependencies have always been present, in a random order, and dropping reversed just broke this particular build. So by dropping reversed I actually uncovered a bug. I'm fine with that.

**Comment by davydden** [comment]
> So by dropping reversed I actually uncovered a bug.

Exactly, which is a good thing!

**Comment by hartzell** [comment]
I can `spack install direnv` from @davydden's branch.

For completeness' sake and transparency of scientific results, etc....:

I tried running my daily build script but it exploded at an earlier step, installing `cask`.   I'll dig into it next (might be that's something's changed in the cask or emacs packages).  When it failed, I tried `spack install direnv` directly to validate @davydden's fix.

For :grin:'s, here's the `cask` crash:

```
hartzelg@lb097hmdev:spack (fix_transitive_build_dep)$ (module purge; spack install cask)
Traceback (most recent call last):
  File "/scratch/hartzelg/tmp/PR-4069/spack/bin/spack", line 220, in <module>
    main(sys.argv)
  File "/scratch/hartzelg/tmp/PR-4069/spack/bin/spack", line 216, in main
    _main(args, unknown)
  File "/scratch/hartzelg/tmp/PR-4069/spack/bin/spack", line 183, in _main
    return_val = command(parser, args)
  File "/scratch/hartzelg/tmp/PR-4069/spack/lib/spack/spack/cmd/install.py", line 317, in install
    specs = spack.cmd.parse_specs(args.package, concretize=True)
  File "/scratch/hartzelg/tmp/PR-4069/spack/lib/spack/spack/cmd/__init__.py", line 116, in parse_specs
    spec.concretize()  # implies normalize
  File "/scratch/hartzelg/tmp/PR-4069/spack/lib/spack/spack/spec.py", line 1712, in concretize
    self._concretize_helper())
  File "/scratch/hartzelg/tmp/PR-4069/spack/lib/spack/spack/spec.py", line 1550, in _concretize_helper
    name].spec._concretize_helper(presets, visited)
  File "/scratch/hartzelg/tmp/PR-4069/spack/lib/spack/spack/spec.py", line 1565, in _concretize_helper
    spack.concretizer.concretize_variants(self)))
  File "/scratch/hartzelg/tmp/PR-4069/spack/lib/spack/spack/concretize.py", line 255, in concretize_variants
    spec.variants[name] = variant.make_default()
  File "/scratch/hartzelg/tmp/PR-4069/spack/lib/spack/spack/variant.py", line 150, in make_default
    return self.make_variant(self.default)
  File "/scratch/hartzelg/tmp/PR-4069/spack/lib/spack/spack/variant.py", line 163, in make_variant
    return self.variant_cls(self.name, value)
  File "/scratch/hartzelg/tmp/PR-4069/spack/lib/spack/spack/variant.py", line 198, in __init__
    self.value = value
  File "/scratch/hartzelg/tmp/PR-4069/spack/lib/spack/spack/variant.py", line 212, in value
    self._value_setter(value)
  File "/scratch/hartzelg/tmp/PR-4069/spack/lib/spack/spack/variant.py", line 394, in _value_setter
    raise ValueError(msg)
ValueError: cannot construct a BoolValuedVariant from a value that does not represent a bool
```

**Comment by adamjstewart** [comment]
@alalazo That sounds like an error message from your multi-valued variant support.

**Comment by alalazo** [comment]
I'll try to fix it in a sec.

**Comment by hartzell** [comment]
at the risk of hijacking this thread, it's the emacs package complaining about this variant.

```python
    variant('toolkit', default='gtk',
            description="Select an X toolkit (gtk, athena)")
```

It there an ongoing multi-valued variant PR?  If so, this made debugging much simpler:

```diff
diff --git a/lib/spack/spack/variant.py b/lib/spack/spack/variant.py
index 7102676..9f3a388 100644
--- a/lib/spack/spack/variant.py
+++ b/lib/spack/spack/variant.py
@@ -389,9 +389,9 @@ class BoolValuedVariant(SingleValuedVariant):
             self._original_value = value
             self._value = False
         else:
-            msg = 'cannot construct a BoolValuedVariant from '
+            msg = 'cannot construct a BoolValuedVariant for {0} from '
             msg += 'a value that does not represent a bool'
-            raise ValueError(msg)
+            raise ValueError(msg.format(self.name))

     def __contains__(self, item):
         return item is self.value
```

otherwise I can toss in a tiny one.

**Comment by scheibelp** [comment]
> If I understand @scheibelp, then what I've observed is not the intended behavior. Is that correct?

Yes: this pulls in transitive build deps for path vs. direct build deps.

Also I agree that run deps of build deps should be included.

> I'm still curious what changed. I didn't intend to change any behavior in #3910 aside from filtering system paths. If you can figure out what line I broke, let me know.

I overlooked it initially but

```
bin_dirs = reversed([d.prefix.bin for d in pkg.spec.dependencies(deptype='build')
```

Was replaced with 

```
build_deps      = pkg.spec.traverse(root=False, deptype=('build'))
```

```traverse``` is transitive while ```dependencies``` is not. So I'd suspect that removing ```reversed``` did not cause the issue; I don't actually see how the order of PATH entries matters as long as there aren't conflicting deps (which Spack ensures) and as long as they all show up before system paths.

**Comment by alalazo** [comment]
Yes. The point is that you didn't specify the admitted values (which default for compatibility to `True` and `False` -> `BoolValuedVariant`). But you specified a `default` that is not a bool, hence the error.

**Comment by hartzell** [comment]
@alalazo -- ok, so this cleans it up:

```diff
diff --git a/var/spack/repos/builtin/packages/emacs/package.py b/var/spack/repos/builtin/packages/emacs/package.py
index dac5768..84bdbe8 100644
--- a/var/spack/repos/builtin/packages/emacs/package.py
+++ b/var/spack/repos/builtin/packages/emacs/package.py
@@ -37,6 +37,7 @@ class Emacs(AutotoolsPackage):

     variant('X', default=False, description="Enable an X toolkit")
     variant('toolkit', default='gtk',
+            values=('gtk', 'athena'),
             description="Select an X toolkit (gtk, athena)")

     depends_on('ncurses')
```

Does providing a list of values obviate the need for the checks around line #56?  I think not, since I'm conditionalizing them on whether its `+X` or not, but....

**Comment by davydden** [comment]
@scheibelp you are absolutely right w.r.t to the cause of the issue. But, this brings another point -- we don't have enough unit/regression tests for build environment (`PATH`'s, etc).

**Comment by hartzell** [comment]
The emacs issues is now #4099, sorry for the distraction.
