### ISSUE TITLE
Spack newbie trying to build their first local package

### ISSUE THREAD

**Issue by m-miller10** [LLNL/spack#40682]
I am new to spack and have built a few dozen packages for my environment.  I have been through a fair number of tutorials and have now built using different compilers and versions.  I believe I have at least a fundamental understanding of spack at ths point.   I have created a local package for a python program that one of the packaged applications (relion@4.0.1) needed for a recommended step.

I am looking for some guidance on how to create a package for a rather complex suite of programs.

I have a licensed source distribution that I have built stand alone and I'm now trying to incorporate it into spack.  I have successfully implemented the file fetch for the distribution tarball but the application build uses a python script to drive scons (a build system that I am not familiar with) and I'm not sure how to use the script instead of one of the build tools.  the script assumes it is being run out of the source subdirectory

here are the commands that I used to build the application tree stand alone.

> $ cd ${INSTALL_PATH}/main/source/
> $ ./scons.py -j8 bin mode=release extras=static

I tried searching for some examples of building in a subdirectory and/or using a custom approach for building from source but I wasn't able to find either.  I would appreciate any guidance, hints or suggestions as how to proceed.

**Comment by adamjstewart** [comment]
Hi @m-miller10, welcome to Spack!

For SCons, you may find https://spack.readthedocs.io/en/latest/build_systems/sconspackage.html useful. It will explain how SCons works and has links to documentation. We have a builtin base class for SConsPackages that you can optionally use.

If you instead just want to run the script, something like this may work:
```python
class Foo(Package):
    def install(self, spec, prefix):
        with working_dir("main/source"):  # or wherever scons.py lives
            scons = Executable("./scons.py")
            scons(f"-j{make_jobs}", "bin", "mode=release", "extras=static")
```

**Comment by m-miller10** [comment]
Thank you! I will read through the documentation and give the class a try.

**Comment by gabrielctn** [comment]
Hi @m-miller10 
I assume you are trying to build Rosetta package (from RosettaCommons) ? I am also trying, I recognized the commands.
Did you manage to install it completely ?
I am currently stuck with this issue:
```
[spack cc] ERROR: Spack compiler must be run from Spack! Input 'SPACK_ENV_PATH' is missing.
```
The `package.py` file looks like this:
```python
import os
from spack.package import *


class Rosetta(Package, CudaPackage):
    """"""

    homepage = "https://www.example.com"
    url = "./rosetta.source.release-356.tar.bz2"

    version("2023.35")
    version(
        "2023.35",
        sha256="86f6a000c853a138d0565634269f680382b9dad50b6fd3cddcb0fe413ecaad4d",
        url="file://{0}/rosetta.source.release-356.tar.bz2".format(
            os.getcwd()
        ),
    )
    manual_download = True

    depends_on("python@3.9:", type=("build", "run"))
    depends_on("cuda@11.8:", type=("build", "run"))
    depends_on("py-tensorflow@2.14", type=("build", "run"))

    def patch(self):
        filter_file("#\s*\"cxx\"\s*:\s*\"~\/path\/to\/compiler\/bin\/g\+\+\"", f"            \"cxx\" : \"{spack_cxx}\"", "main/source/tools/build/site.settings")
        filter_file("#\s*\"cc\"\s*:\s*\"~\/path\/to\/compiler\/bin\/gcc\"", f"            \"cc\"  : \"{spack_cc}\"", "main/source/tools/build/site.settings")

    def install(self, spec, prefix):
        install_tree("main", prefix)
        with working_dir("main/source"):
            scons = Executable("./scons.py")
            scons(f"-j{make_jobs}", "mode=release", "extras=static", "extras=tensorflow_gpu", "extras=cxx11thread", "extras=graphics", "extras=opencl", "bin")
```

**Comment by m-miller10** [comment]
Hi @gabrielctn ,

   Yes I am trying to package it.   I'm starting with just a basic build of the last versioned release.   I hope to move on to more recent release like what you are building once I'm successful with 3.1.3.  I haven't been successful in get it to build with the spack framework.  Though I have mades some progress.   According to the documentation the error message that we are seeing
   
    Input 'SPACK_ENV_PATH' is missing

indicates that 
... the package isn’t compatible with Spack’s compiler wrappers. In this case, you’ll have to use the path to the actual compilers, which are stored in self.compiler.cc and friends. Note that this may involve passing additional flags to the build to locate dependencies, a task normally done by the compiler wrappers. `serf ` is an example of a package with this limitation.

so I've had a look at the serf package and I've been working on manually defining the environment.  I've used spack stage to create the build directory but I haven't yet been successful in figuring out how to compile and install outside the spack environment.  I've tried using `serf` as a guide for how to do this but I haven't quite succeeded yet.  

As a next step I'm try to find other packages that might provide further hints as to how to do this.

**Comment by gabrielctn** [comment]
Ok cool !
Yes I saw the same info about Scons issues to propagate Spack env variables and compilers wrappers today.
I believe we need to manually set paths in the config files `tools/build/*.settings` because Scons seems to wipeout all paths before starting... and these seem to be the config files that allow users to override the variables.
I will continue to try and report here if I get any progress.
Good luck !

**Comment by gabrielctn** [comment]
Well, this works and compiles !
The important part is `filter_file("#            \"ENV\" : os.environ", "            \"ENV\" : os.environ", "main/source/tools/build/site.settings")`
There are more paths to add to `PATH` I believe but here is a recipe that works.
```python
import os
from spack.package import *


class Rosetta(Package, CudaPackage):
    """Rosetta is a suite of software libraries for macromolecular modeling."""

    homepage = "https://www.example.com"
    url = "./rosetta.source.release-356.tar.bz2"

    version("2023.35")
    version(
        "2023.35",
        sha256="86f6a000c853a138d0565634269f680382b9dad50b6fd3cddcb0fe413ecaad4d",
        url="file://{0}/rosetta.source.release-356.tar.bz2".format(
            os.getcwd()
        ),
    )
    manual_download = True

    depends_on("python@3.9:", type=("build", "run"))
    depends_on("cuda@11.8:", type=("build", "run"))
    depends_on("py-tensorflow@2.14", type=("build", "run"))

    def patch(self):
        filter_file("#\s*\"cxx\"\s*:\s*\"~\/path\/to\/compiler\/bin\/g\+\+\"", f"            \"cxx\" : \"{spack_cxx}\"", "main/source/tools/build/site.settings")
        filter_file("#\s*\"cc\"\s*:\s*\"~\/path\/to\/compiler\/bin\/gcc\"", f"            \"cc\"  : \"{spack_cc}\"", "main/source/tools/build/site.settings")
        filter_file("#            \"ENV\" : os.environ", "            \"ENV\" : os.environ", "main/source/tools/build/site.settings")

    def setup_run_environment(self, env):
        env.prepend_path("PATH", self.prefix.source.bin)

    def install(self, spec, prefix):
        with working_dir("main/source"):
            scons = Executable("./scons.py")
            scons(f"-j{make_jobs}", "mode=release", "extras=static", "extras=tensorflow_gpu", "bin")
        install_tree("main", prefix)
```

**Comment by m-miller10** [comment]
@gabrielctn Thank you for sharing your insights.  I'm still coming up to speed with spack but I did find a few useful command that helped me work through the details of getting the build and run environment correct.
`spack build-env <spec> -- bash` generates a shell with the build environment of the spec this made it easy to iterate and debug the build.   I needed to have an mpi version of the package so here's what I final ended up with.   I'm working out the last of the environment variables & working to understand which "scripts" use the different extras 
`example : > ./scons.py -j 5 mode=release bin/rosetta_scripts.mpi.linuxgccrelease extras=mpi`
so I can make the compile more efficient but I think as a framework this  is pretty close.   
```
...(as above)...

    variant("mpi", default=False, description="build using an available mpi package")
    variant("cuda", default=False, description="build using cuda library, tensorflow, opencl")
    variant("threads", default=False, description="build using cxx11threads")
    variant("gui", default=False, description="build using graphics")

    depends_on("python@3.9:", type=("build", "run"))
    depends_on("scons", type="build")
    depends_on("mpi", when="+mpi", type=("build", "run"))
    depends_on("cuda@11.8:", when="+cuda", type=("build", "run"))
    depends_on("py-tensorflow", when="+cuda", type=("build", "run"))
    depends_on("opencl", when="+cuda", type=("build", "run"))

    def patch(self):
        # rosetta uses the file site.settings to define the build environment
        env_in_string  = '#            "ENV"'
        env_out_string = '             "ENV"'
        cxx_in_string  = '#            "cxx" : "~\/path\/to\/compiler\/bin\/g\+\+"'
        cc_in_string   = '#            "cc"  : "~\/path\/to\/compiler\/bin\/gcc"'

        if "+mpi" in self.spec:
            cxx_out_string = '             "cxx" : "%s"' % os.environ['MPICXX']
            cc_out_string  = '             "cc"  : "%s"' % os.environ['MPICC']
        else:
            cxx_out_string = '             "cxx" : "%s"' % os.environ['CXX']
            cc_out_string  = '             "cc"  : "%s"' % os.environ['CC']

        #print(env_in_string, env_out_string, 'main/source/tools/build/site.settings')
        #print(cxx_in_string, cxx_out_string, 'main/source/tools/build/site.settings')
        #print(cc_in_string,  cc_out_string,  'main/source/tools/build/site.settings')

        filter_file(env_in_string, env_out_string, 'main/source/tools/build/site.settings')
        filter_file(cxx_in_string, cxx_out_string, 'main/source/tools/build/site.settings')
        filter_file(cc_in_string , cc_out_string , 'main/source/tools/build/site.settings')

    def setup_run_environment(self, env):
        env.prepend_path("PATH", self.prefix.source.bin)
        env.prepend_path("PATH", self.prefix.source.scripts) # this need to reference $ROSETTA3/source/scripts/python/public:
        env.set('ROSETTA3', self.prefix)
        env.set('ROSETTA3_DB', self.prefix.database)

    def install(self, spec, prefix):
        with working_dir("main/source"):

            extras="extras=static"

            if "+mpi"     in self.spec:
                extras+=" extras=mpi"
            if "+cuda"    in self.spec:
                extras+=" extras=tensorflow_gpu extras=opencl"
            if "+threads" in self.spec:
                extras+=" extras=cxx11thread"
            if "+gui"     in self.spec:
                extras+=" extras=graphics"

            scons = Executable("./scons.py")
            #scons(f"-j{make_jobs}", "mode=release", "extras=static", "bin")
            scons(f"-j{make_jobs}", "mode=release", extras, "bin")
        install_tree("main", prefix)

```

**Comment by m-miller10** [comment]
I'm going to close this topic as I'm able to build with this and just need to clean things up a bit to finish it off.

**Comment by presleydc** [comment]
Having a spack package for rosetta would be super helpful. I'm struggling with a build of it right now. I have a few changes to the file you proposed here. Mainly changing the 'extras' to be an array instead of a string as the spaces in the string seem to break things but no matter how I build, I get a libzlib.so not found error. Should it be built extras=static? I took it out and added a dep for libz and got the same error. Did you get a package.py for Rosetta to work?

**Comment by m-miller10** [comment]
@presleydc, I've been traveling which delayed my response.   I did successfully build rosetta, it's a bit specific for our environment but could be generalized with a bit more effort.   I do recall having an issue early on with libz, however I don't recall exactly what I changed to address it.   I think it was something related to versions that I picked up from the native install documentation.
