### ISSUE TITLE
Intel MKL now free; spack install intel-mkl fails

### ISSUE THREAD

**Issue by yee379** [LLNL/spack#4070]
a fresh `spack install intel-mkl`throws the following errors in compile:

    [centos@spack01 ~]$ spack install --verbose intel-mkl
    ==> Installing intel-mkl
    ==> Using cached archive: /opt/spack/var/spack/cache/intel-mkl/intel-mkl-2017.2.174.tgz
    ==> Staging archive: /opt/spack/var/spack/stage/intel-mkl-2017.2.174-twy6vcyriwtass3cjgsc7wbtkouqnluo/l_mkl_2017.2.174.tgz
    ==> Created stage in /opt/spack/var/spack/stage/intel-mkl-2017.2.174-twy6vcyriwtass3cjgsc7wbtkouqnluo
    ==> Ran patch() for intel-mkl
    ==> Building intel-mkl [Package]
    ==> Found already existing license /opt/spack/etc/spack/licenses/intel/license.lic
    ==> Executing phase : 'install'
    ==> './install.sh' '--silent' 'silent.cfg'
    Name "ACTIVATION_LICENSE_FILE" is not valid
    ==> Error: ProcessError: Command exited with status 2:
        './install.sh' '--silent' 'silent.cfg'
    /opt/spack/var/spack/repos/builtin/packages/intel/package.py:96, in install:
         74       def install(self, spec, prefix):
         75
         76           if not hasattr(self, "intel_prefix"):
         77               self.intel_prefix = self.prefix
         78
         79           silent_config_filename = 'silent.cfg'
         80           with open(silent_config_filename, 'w') as f:
         81               f.write("""
         82   ACCEPT_EULA=accept
         83   PSET_MODE=install
         84   CONTINUE_WITH_INSTALLDIR_OVERWRITE=yes
         85   PSET_INSTALL_DIR=%s
         86   NONRPM_DB_DIR=%s
         87   ACTIVATION_LICENSE_FILE=%s
         88   ACTIVATION_TYPE=license_file
         89   PHONEHOME_SEND_USAGE_DATA=no
         90   CONTINUE_WITH_OPTIONAL_ERROR=yes
         91   COMPONENTS=%s
         92   """ % (self.intel_prefix, self.intel_prefix, self.global_license_file,
         93                   self.intel_components))
         94
         95           install_script = Executable("./install.sh")
      >> 96           install_script('--silent', silent_config_filename)

    See build log for details:
      /tmp/centos/spack-stage/spack-stage-WfZcaO/l_mkl_2017.2.174/spack-build.out

    $ cd /tmp/centos/spack-stage/spack-stage-WfZcaO/l_mkl_2017.2.174/
    $ ./install.sh --silent silent.cfg
    Name "ACTIVATION_LICENSE_FILE" is not valid
    Name "ACTIVATION_TYPE" is not valid
    Name "PHONEHOME_SEND_USAGE_DATA" is not valid
/tmp/centos/spack-stage/spack-stage-WfZcaO/l_mkl_2017.2.174/silent.cfg has errors

commenting out the above directives in `silent_config_filename` under `/opt/spack/var/spack/repos/builtin/packages/intel/package.py` fixes it.

**Comment by adamjstewart** [comment]
This was fixed by #3931. If you aren't already, you should always update to the latest develop branch. Spack is constantly changing. If you're stuck with the last release, you will be missing out on a lot of bug fixes and new features.
