### ISSUE TITLE
visit@3.3.3 build fails: main/viewer.C:210:61: error: invalid use of incomplete type 'class QSurfaceFormat'

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#40731]
### Steps to reproduce the issue

`visit@3.3.3` build fails as part of `ecp-data-vis-sdk +visit ...` spec using:
* `spack@develop` (81172f9251ff0b3409b07d5b9d13b214766ff1b1 from `Thu Oct 26 21:11:43 2023 +0200`)
* GCC 11.4.0
* Ubuntu 20.04, AMD64, ARM64 (Graviton2), PPC64 (Power9le)

Spack environment: [spack.yaml.txt](https://github.com/spack/spack/files/13183790/spack.yaml.txt)

<details><summary>Concretization</summary>

<pre>
 -   visit@3.3.3%gcc@11.4.0+adios2+conduit+gui+hdf5~ipo+mfem+mpi+netcdf~osmesa+plugins+python+silo~vtkm build_system=cmake build_type=Release generator=ninja patches=8fb2ef2,bd43c00 arch=linux-ubuntu20.04-x86_64
[+]      ^adios2@2.9.1%gcc@11.4.0~aws+blosc2+bzip2~cuda+dataman~dataspaces+fortran+hdf5~ipo~kokkos+libcatalyst~libpressio+mgard+mpi+pic+png+python~rocm+shared+sst+sz+zfp build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-x86_64
[+]          ^bzip2@1.0.8%gcc@11.4.0~debug~pic+shared build_system=generic arch=linux-ubuntu20.04-x86_64
[+]              ^diffutils@3.9%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^c-blosc2@2.10.5%gcc@11.4.0+avx2~ipo+lizard+lz4+snappy+zlib+zstd build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-x86_64
[+]              ^lizard@1.0%gcc@11.4.0 build_system=makefile patches=4895619 arch=linux-ubuntu20.04-x86_64
[+]              ^snappy@1.1.10%gcc@11.4.0~ipo+pic+shared build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-x86_64
[+]          ^gmake@4.4.1%gcc@11.4.0~guile build_system=generic arch=linux-ubuntu20.04-x86_64
[+]          ^libcatalyst@2.0.0-rc4%gcc@11.4.0~conduit~ipo+mpi build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-x86_64
[+]          ^libfabric@1.19.0%gcc@11.4.0~debug~kdreg build_system=autotools fabrics=rxm,sockets,tcp,udp arch=linux-ubuntu20.04-x86_64
[+]          ^libffi@3.4.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^libpng@1.6.39%gcc@11.4.0~ipo~pic build_system=cmake build_type=Release generator=make libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]          ^libzmq@4.3.5%gcc@11.4.0~docs~drafts+libbsd+libsodium~libunwind build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^libbsd@0.11.7%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                  ^libmd@1.0.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^libsodium@1.0.18%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^mgard@2023-03-31%gcc@11.4.0~cuda~ipo+openmp+serial~timing~unstructured build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-x86_64
[+]              ^libarchive@3.7.1%gcc@11.4.0+iconv build_system=autotools compression=bz2lib,lz4,lzma,lzo2,zlib,zstd crypto=openssl libs=shared,static programs=none xar=libxml2 arch=linux-ubuntu20.04-x86_64
[+]                  ^lzo@2.10%gcc@11.4.0 build_system=autotools libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]              ^protobuf@3.21.12%gcc@11.4.0~ipo+shared build_system=cmake build_type=Release generator=make patches=cefc4bf arch=linux-ubuntu20.04-x86_64
[+]              ^sed@4.9%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^yaml-cpp@0.7.0%gcc@11.4.0~ipo+pic+shared~tests build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-x86_64
[+]          ^pkgconf@1.9.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^py-mpi4py@3.1.4%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu20.04-x86_64
[+]              ^py-cython@0.29.36%gcc@11.4.0 build_system=python_pip patches=c4369ad arch=linux-ubuntu20.04-x86_64
[+]              ^py-pip@23.1.2%gcc@11.4.0 build_system=generic arch=linux-ubuntu20.04-x86_64
[+]              ^py-setuptools@63.4.3%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu20.04-x86_64
[+]              ^py-wheel@0.41.2%gcc@11.4.0 build_system=generic arch=linux-ubuntu20.04-x86_64
[+]          ^py-numpy@1.24.4%gcc@11.4.0+blas+lapack build_system=python_pip patches=873745d arch=linux-ubuntu20.04-x86_64
[+]              ^openblas@0.3.24%gcc@11.4.0~bignuma~consistent_fpcsr+fortran~ilp64+locking+pic+shared build_system=makefile symbol_suffix=none threads=openmp arch=linux-ubuntu20.04-x86_64
[+]          ^sz@2.1.12.5%gcc@11.4.0+fortran+hdf5~ipo~netcdf~pastri~python+random_access+shared~stats~time_compression build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-x86_64
[+]          ^zfp@0.5.5%gcc@11.4.0~aligned~c~cuda~fasthash~fortran~ipo~openmp~profile~python+shared~strided~twoway+utilities bsws=64 build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-x86_64
[+]      ^cmake@3.27.7%gcc@11.4.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-ubuntu20.04-x86_64
[+]          ^curl@8.4.0%gcc@11.4.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-ubuntu20.04-x86_64
[+]              ^nghttp2@1.57.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^ncurses@6.3%gcc@11.4.0~symlinks+termlib abi=none build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]      ^conduit@0.8.8%gcc@11.4.0~adios+blt_find_mpi~caliper~doc~doxygen+examples+fortran+hdf5~hdf5_compat~ipo+mpi+parmetis+python+shared~silo+test+utilities~zfp build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-x86_64
[+]          ^metis@5.1.0%gcc@11.4.0~gdb~int64~ipo~real64+shared build_system=cmake build_type=Release generator=make patches=4991da9,93a7903,b1225da arch=linux-ubuntu20.04-x86_64
[+]          ^parmetis@4.0.3%gcc@11.4.0~gdb~int64~ipo+shared build_system=cmake build_type=Release generator=make patches=4f89253,50ed208,704b84f arch=linux-ubuntu20.04-x86_64
[+]      ^hdf5@1.14.2%gcc@11.4.0~cxx+fortran+hl~ipo~java~map+mpi+shared~szip+threadsafe+tools api=default build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-x86_64
[+]      ^libfms@0.2.0%gcc@11.4.0+conduit~ipo+shared build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-x86_64
[+]      ^mesa-glu@9.0.2%gcc@11.4.0 build_system=autotools gl=glx patches=3d03e55 arch=linux-ubuntu20.04-x86_64
[+]          ^glx@1.4%gcc@11.4.0 build_system=bundle arch=linux-ubuntu20.04-x86_64
[+]              ^mesa@23.0.3%gcc@11.4.0+glx+llvm+opengl~opengles+osmesa~strip build_system=meson buildtype=release default_library=shared arch=linux-ubuntu20.04-x86_64
[+]                  ^flex@2.6.3%gcc@11.4.0+lex~nls build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                      ^findutils@4.9.0%gcc@11.4.0 build_system=autotools patches=440b954 arch=linux-ubuntu20.04-x86_64
[+]                  ^glproto@1.4.17%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                  ^libunwind@1.6.2%gcc@11.4.0~block_signals~conservative_checks~cxx_exceptions~debug~debug_frame+docs+pic+tests+weak_backtrace+xz~zlib build_system=autotools components=none libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]                  ^llvm@16.0.6%gcc@11.4.0+clang~cuda~flang+gold~ipo+libomptarget~libomptarget_debug~link_llvm_dylib+lld+lldb+llvm_dylib+lua~mlir+polly~python~split_dwarf~z3~zstd build_system=cmake build_type=Release compiler-rt=runtime generator=ninja libcxx=runtime libunwind=runtime openmp=runtime shlib_symbol_version=none targets=all version_suffix=none arch=linux-ubuntu20.04-x86_64
[+]                      ^binutils@2.41%gcc@11.4.0~gas+gold~gprofng+headers~interwork+ld+libiberty~lto~nls~pgo+plugins build_system=autotools compress_debug_sections=zlib libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]                      ^hwloc@2.9.1%gcc@11.4.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]                          ^libpciaccess@0.17%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                      ^libedit@3.1-20210216%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                      ^lua@5.3.6%gcc@11.4.0~pcfile+shared build_system=makefile fetcher=curl arch=linux-ubuntu20.04-x86_64
[+]                          ^unzip@6.0%gcc@11.4.0 build_system=makefile arch=linux-ubuntu20.04-x86_64
[+]                      ^perl-data-dumper@2.173%gcc@11.4.0 build_system=perl arch=linux-ubuntu20.04-x86_64
[+]                      ^swig@4.1.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                  ^py-mako@1.2.4%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu20.04-x86_64
[+]                      ^py-markupsafe@2.1.3%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu20.04-x86_64
[+]                  ^xrandr@1.5.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                      ^libxrandr@1.5.3%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                      ^randrproto@1.5.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]      ^mfem@4.6.0%gcc@11.4.0~amgx+conduit~cuda~debug~examples+exceptions+fms~ginkgo~gnutls~gslib~hiop~lapack~libceed~libunwind+metis~miniapps~mpfr+mpi~netcdf~occa~openmp~petsc~pumi~raja~rocm+shared~slepc+static~strumpack~suite-sparse~sundials~superlu-dist~threadsafe~umpire+zlib build_system=generic patches=718f073 timer=auto arch=linux-ubuntu20.04-x86_64
[+]          ^hypre@2.29.0%gcc@11.4.0~caliper~complex~cuda~debug+fortran~gptune~int64~internal-superlu~magma~mixedint+mpi~openmp~rocm+shared~superlu-dist~sycl~umpire~unified-memory build_system=autotools arch=linux-ubuntu20.04-x86_64
[e]      ^mpich@4.1.2%gcc@11.4.0~argobots~cuda+fortran~hwloc+hydra+libxml2+pci~rocm+romio~slurm~vci~verbs~wrapperrpath build_system=autotools datatype-engine=auto device=ch4 netmod=ofi pmi=pmi arch=linux-ubuntu20.04-x86_64
[+]      ^netcdf-c@4.9.2%gcc@11.4.0+blosc~byterange~dap~fsync~hdf4~jna+mpi~nczarr_zip+optimize~parallel-netcdf+pic+shared+szip+zstd build_system=autotools patches=0161eb8 arch=linux-ubuntu20.04-x86_64
[+]          ^c-blosc@1.21.4%gcc@11.4.0+avx2~ipo build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-x86_64
[+]          ^libaec@1.0.6%gcc@11.4.0~ipo+shared build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-x86_64
[+]          ^zstd@1.5.5%gcc@11.4.0+programs build_system=makefile compression=none libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]      ^netcdf-cxx@4.2%gcc@11.4.0+netcdf4 build_system=autotools patches=8892291 arch=linux-ubuntu20.04-x86_64
[+]      ^ninja@1.11.1%gcc@11.4.0+re2c build_system=generic arch=linux-ubuntu20.04-x86_64
[+]          ^re2c@2.2%gcc@11.4.0 build_system=generic arch=linux-ubuntu20.04-x86_64
[+]      ^python@3.8.18%gcc@11.4.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=0d98e93,4c24573,ebdca64,f2fd060 arch=linux-ubuntu20.04-x86_64
[+]          ^expat@2.5.0%gcc@11.4.0+libbsd build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^gdbm@1.23%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^gettext@0.22.3%gcc@11.4.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^libiconv@1.17%gcc@11.4.0 build_system=autotools libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]              ^tar@1.34%gcc@11.4.0 build_system=autotools zip=pigz arch=linux-ubuntu20.04-x86_64
[+]                  ^pigz@2.7%gcc@11.4.0 build_system=makefile arch=linux-ubuntu20.04-x86_64
[+]          ^libxcrypt@4.4.35%gcc@11.4.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-ubuntu20.04-x86_64
[+]          ^openssl@3.1.3%gcc@11.4.0~docs+shared build_system=generic certs=mozilla arch=linux-ubuntu20.04-x86_64
[+]              ^ca-certificates-mozilla@2023-05-30%gcc@11.4.0 build_system=generic arch=linux-ubuntu20.04-x86_64
[+]          ^readline@8.2%gcc@11.4.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu20.04-x86_64
[+]          ^sqlite@3.43.2%gcc@11.4.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^util-linux-uuid@2.38.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^xz@5.4.1%gcc@11.4.0+pic build_system=autotools libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]      ^qt@5.14.2%gcc@11.4.0~dbus~debug~doc~examples~framework~gtk+gui~location+opengl~phonon+shared+sql+ssl+tools~webkit build_system=generic patches=2081e9c,51aeba5,75bcb42,7f34d48,8449b9f,84b0991,9378afd,ea411b9 arch=linux-ubuntu20.04-x86_64
[+]          ^assimp@5.3.1%gcc@11.4.0~ipo+shared build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-x86_64
[+]          ^double-conversion@3.3.0%gcc@11.4.0~ipo build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-x86_64
[+]          ^fontconfig@2.14.2%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^font-util@1.4.0%gcc@11.4.0 build_system=autotools fonts=encodings,font-adobe-100dpi,font-adobe-75dpi,font-adobe-utopia-100dpi,font-adobe-utopia-75dpi,font-adobe-utopia-type1,font-alias,font-arabic-misc,font-bh-100dpi,font-bh-75dpi,font-bh-lucidatypewriter-100dpi,font-bh-lucidatypewriter-75dpi,font-bh-type1,font-bitstream-100dpi,font-bitstream-75dpi,font-bitstream-speedo,font-bitstream-type1,font-cronyx-cyrillic,font-cursor-misc,font-daewoo-misc,font-dec-misc,font-ibm-type1,font-isas-misc,font-jis-misc,font-micro-misc,font-misc-cyrillic,font-misc-ethiopic,font-misc-meltho,font-misc-misc,font-mutt-misc,font-schumacher-misc,font-screen-cyrillic,font-sun-misc,font-winitzki-cyrillic,font-xfree86-type1 arch=linux-ubuntu20.04-x86_64
[+]                  ^bdftopcf@1.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                      ^fontsproto@2.1.3%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                      ^libxfont@1.5.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                  ^mkfontdir@1.0.7%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                  ^mkfontscale@1.2.2%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                      ^libfontenc@1.1.7%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^gperf@3.1%gcc@11.4.0 build_system=autotools patches=3dd36db arch=linux-ubuntu20.04-x86_64
[+]          ^freetype@2.10.2%gcc@11.4.0+pic+shared build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^glib@2.78.0%gcc@11.4.0~libmount~strip build_system=meson buildtype=release default_library=shared patches=2c25d7b tracing=none arch=linux-ubuntu20.04-x86_64
[+]              ^elfutils@0.189%gcc@11.4.0~debuginfod+exeprefix~nls build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^meson@1.2.2%gcc@11.4.0 build_system=python_pip patches=0f0b1bd,ae59765 arch=linux-ubuntu20.04-x86_64
[+]          ^harfbuzz@7.3.0%gcc@11.4.0~graphite2~strip build_system=meson buildtype=release default_library=shared arch=linux-ubuntu20.04-x86_64
[+]              ^cairo@1.16.0%gcc@11.4.0~X~fc+ft+gobject+pdf+pic~png+shared~svg build_system=autotools patches=7c4da77 arch=linux-ubuntu20.04-x86_64
[+]                  ^pixman@0.42.2%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                  ^which@2.21%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^gobject-introspection@1.76.1%gcc@11.4.0~strip build_system=meson buildtype=release default_library=shared arch=linux-ubuntu20.04-x86_64
[+]          ^icu4c@67.1%gcc@11.4.0 build_system=autotools cxxstd=11 arch=linux-ubuntu20.04-x86_64
[+]          ^libjpeg-turbo@3.0.0%gcc@11.4.0~ipo~jpeg8+shared+static build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-x86_64
[+]              ^nasm@2.15.05%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^libmng@2.0.3%gcc@11.4.0~ipo build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-x86_64
[+]              ^lcms@2.13.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^libsm@1.2.3%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^libice@1.0.9%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^util-macros@1.19.3%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^xproto@7.0.31%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^xtrans@1.4.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^libtiff@4.5.1%gcc@11.4.0+ccitt~ipo~jbig+jpeg~jpeg12~lerc~libdeflate+logluv~lzma+lzw+next~old-jpeg+packbits~pic~pixarlog+shared+thunder~webp+zlib~zstd build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-x86_64
[+]          ^libx11@1.8.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^inputproto@2.3.2%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^kbproto@1.0.7%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^xextproto@7.3.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^libxcb@1.14%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^libpthread-stubs@0.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^libxau@1.0.8%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^libxdmcp@1.1.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^xcb-proto@1.15.2%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^libxext@1.3.3%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^libxkbcommon@1.5.0%gcc@11.4.0~strip~wayland build_system=meson buildtype=release default_library=shared arch=linux-ubuntu20.04-x86_64
[+]              ^bison@3.8.2%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^xkbdata@1.0.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                  ^xkbcomp@1.4.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                      ^libxkbfile@1.0.9%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^libxml2@2.10.3%gcc@11.4.0+pic~python+shared build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^libxrender@0.9.10%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^renderproto@0.11.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^pcre2@10.42%gcc@11.4.0~jit+multibyte build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^xcb-util-image@0.4.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^xcb-util@0.4.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^xcb-util-keysyms@0.4.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^xcb-util-renderutil@0.3.10%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^xcb-util-wm@0.4.2%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]      ^qwt@6.1.6%gcc@11.4.0~designer+opengl build_system=qmake patches=73df727 arch=linux-ubuntu20.04-x86_64
[+]      ^silo@4.11.1%gcc@11.4.0+fortran+fpzip+hdf5+hzip+mpi+pic+shared~silex build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^autoconf@2.69%gcc@11.4.0 build_system=autotools patches=35c4492,7793209,a49dd5b arch=linux-ubuntu20.04-x86_64
[+]          ^autoconf-archive@2023.02.20%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^automake@1.16.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^libtool@2.4.7%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^m4@1.4.19%gcc@11.4.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-ubuntu20.04-x86_64
[+]              ^libsigsegv@2.14%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^perl@5.38.0%gcc@11.4.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-ubuntu20.04-x86_64
[+]              ^berkeley-db@18.1.40%gcc@11.4.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu20.04-x86_64
[+]      ^vtk@8.2.1a%gcc@11.4.0~ffmpeg~ipo+mpi+opengl2~osmesa+python+qt~xdmf build_system=cmake build_type=Release generator=make patches=36b22cd,3b47ee0,760fd6d,9535683,a4c63c6,b0c3cea arch=linux-ubuntu20.04-x86_64
[+]          ^eigen@3.4.0%gcc@11.4.0~ipo build_system=cmake build_type=RelWithDebInfo generator=make arch=linux-ubuntu20.04-x86_64
[+]          ^gl2ps@1.4.2%gcc@11.4.0~doc~ipo+png+zlib build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-x86_64
[+]          ^glew@2.2.0%gcc@11.4.0~ipo build_system=cmake build_type=Release generator=make gl=glx patches=7992e52 arch=linux-ubuntu20.04-x86_64
[+]          ^jsoncpp@1.9.5%gcc@11.4.0~ipo build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-x86_64
[+]          ^libogg@1.3.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^libtheora@1.1.1%gcc@11.4.0~doc build_system=autotools patches=057836e,e01ef71,ff8478d arch=linux-ubuntu20.04-x86_64
[+]          ^libxt@1.1.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^lz4@1.9.4%gcc@11.4.0+pic build_system=makefile libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]          ^pugixml@1.13%gcc@11.4.0~ipo+pic+shared build_system=cmake build_type=Release generator=make arch=linux-ubuntu20.04-x86_64
[+]      ^vtk-m@1.9.0%gcc@11.4.0~64bitids+ascent_types~cuda+doubleprecision+examples+fpic~ipo~kokkos~logging+mpi+openmp+rendering~rocm+shared~tbb~testlib~virtuals build_system=cmake build_type=Release generator=make patches=7cc9541 arch=linux-ubuntu20.04-x86_64
[+]      ^zlib-ng@2.1.4%gcc@11.4.0+compat+opt build_system=autotools arch=linux-ubuntu20.04-x86_64
</pre></details>

Error reproduced here in Docker container image `ecpe4s/ubuntu20.04-runner-amd64-gcc-11.4-mpi-base:2023.08.20`

```
$> spack -e . install -j32 /n72g
...
==> Installing visit-3.3.3-n72glp7wpimw7caeuq5skyc6gvh6daeg [132/132]
==> No binary for visit-3.3.3-n72glp7wpimw7caeuq5skyc6gvh6daeg found: installing from source
==> Using cached archive: /spack/var/spack/cache/_source-cache/archive/cc/cc67abb7585e23b51ad576e797df4108641ae6c8c5e80e5359a279c729769187.tar.gz
==> Applied patch /spack/var/spack/repos/builtin/packages/visit/parallel-hdf5-3.3.patch
==> Applied patch /spack/var/spack/repos/builtin/packages/visit/vtk-8.2-constcorrect.patch
==> Ran patch() for visit
==> visit: Executing phase: 'cmake'
==> visit: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 1:
    'ninja' '-j32' '-v'
...
  >> 33332    FAILED: viewer/main/CMakeFiles/viewer_exe.dir/viewer.C.o
...
     33334    /tmp/root/spack-stage/spack-stage-visit-3.3.3-n72glp7wpimw7caeuq5skyc6gvh6daeg/spack-src/src/viewer/main/viewer.C: In function 'int ViewerMain(int, char**)':
  >> 33335    /tmp/root/spack-stage/spack-stage-visit-3.3.3-n72glp7wpimw7caeuq5skyc6gvh6daeg/spack-src/src/viewer/main/viewer.C:210:61: error: invalid use of incomplete type 'class Q
              SurfaceFormat'
     33336      210 |         auto surfaceFormat = QVTKOpenGLWidget::defaultFormat();
     33337          |                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
     33338    In file included from /tmp/root/spack-stage/spack-stage-visit-3.3.3-n72glp7wpimw7caeuq5skyc6gvh6daeg/spack-src/src/viewer/main/viewer.C:24:
     33339    /spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.4.0/vtk-8.2.1a-2yxtg2nw77l3wnyidalatsn6if5mc4sn/include/vtk-8.2/QVTKOpenGLWidget.h:23:7: note: forward declaration of '
              class QSurfaceFormat'
     33340       23 | class QSurfaceFormat;
     33341          |       ^~~~~~~~~~~~~~
  >> 33342    /tmp/root/spack-stage/spack-stage-visit-3.3.3-n72glp7wpimw7caeuq5skyc6gvh6daeg/spack-src/src/viewer/main/viewer.C:213:25: error: incomplete type 'QSurfaceFormat' used i
              n nested name specifier
     33343      213 |         QSurfaceFormat::setDefaultFormat(surfaceFormat);
     33344          |                         ^~~~~~~~~~~~~~~~
...
```

### Error message

<details><summary>Error message</summary>

<pre>
... see above
</pre></details>

### Information on your system

* **Spack:** 0.21.0.dev0 (81172f9251ff0b3409b07d5b9d13b214766ff1b1)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/13183814/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/13183813/spack-build-out.txt)

@cyrush @kwryankrattiger 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by cyrush** [comment]
FYI:

For VisIt 3.4, we are building Qt6 + Qwt. We have a few patches that we use for qwt:

https://github.com/visit-dav/visit/blob/develop/src/tools/dev/scripts/bv_support/bv_qwt.sh

**Comment by BenWibking** [comment]
I also see this on Fedora 39 ARM64. I have built VisIt with an un-patched Spack on Frontier successfully, so I'm not sure why it doesn't work on my laptop.

**Comment by cyrush** [comment]
Interesting - we have built on macOS + ARM.

The patch in build_visit isn't done much at all  --- not sure if it would help with this issue.

**Comment by kwryankrattiger** [comment]
> I have built VisIt with an un-patched Spack on Frontier successfully, so I'm not sure why it doesn't work on my laptop.

Are you building VisIt with Qt on Frontier? Usually on systems like that you bulid headless since the gui doesn't get you anything.

**Comment by kwryankrattiger** [comment]
Also, Frontier is notably not ARM...

**Comment by BenWibking** [comment]
It turns out it was not an ARM issue at all. For some reason, VisIt is missing header includes for `<QSurfaceFormat>` in several files, which is fixed in the above PR.
