### ISSUE TITLE
should spack find return info regarding packages in packages.yaml

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/spack#4075]
I have a packages.yaml that defines paths to pre-installed cmake.

packages:
  cmake:
    paths:
      cmake@3.0.2%gcc@6.1.0 arch=darwin-elcapitan-x86_64: /Users/miller86/visit/thirdparty_shared/2.12/cmake/3.0.2/i386-apple-darwin15_clang

but a subsequent spack find cmake command returns nothing.

Either I've crafted packages.yaml incorrectly or spack find should be enhance to return information on packages defined in packages.yaml. The latter makes it possible to affirm contents of packages.yaml is having the intended effect on Spack and so I think it would be useful for spack find to return such information.

**Comment by markcmiller86** [comment]
So, after editing packages.yaml, I hadn't actually performed any 'spack install' commands. When I did, I saw this...

h4gseyptik6anm3lm57bv3qn4k
==> cmake@3.0.2 : externally installed in /Users/miller86/visit/thirdparty_shared/2.12/cmake/3.0.2/i386-apple-darwin15_clang
==> cmake@3.0.2 : generating module file
==> cmake@3.0.2 : registering into DB
==> Installing boxlib
==> Fetching https://github.com/BoxLib-Codes/BoxLib/archive/16.12.2.tar.gz

and low, and behold, now spack find cmake does indeed return info on packages defined in package.yaml

**Comment by alalazo** [comment]
For the record: this behavior changed since #1167 got merged. Now we track external packages in the DB.
