### ISSUE TITLE
How do I specify numerical valued variants in depends_on statements

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/spack#4076]
Boxlib has compile time knob for number of spatial dimensions.

I am adding a variant to boxlib like so...

    variant('dims', default=3, description='Number of spatial dimensions')

Ok, fine and good.

But, what is the syntax for having another package that depends on boxlib with dims set to 3?

I tried 

    depends_on('boxlib+dims=3') # how do we say 3D boxlib?

But, that doesn't work. Spack reports...
==> Error: Unexpected token

**Comment by tgamblin** [comment]
The `+foo` and `~foo` syntax originates from Spack's original, boolean-only variant system. They're the same as `foo=true` and `foo=false`.  The key-value pairs and multi-valued variants (#2386) came later.  You just want a space to separate the kvp from the rest of the spec:

```
depends_on('boxlib dims=3')
```

**Comment by alalazo** [comment]
@markcmiller86 Two packages that you may find useful as an example are `mvapich2`:
```python
# 32 is needed when job size exceeds 32768 cores                                                                                                                                                               
variant(
    'ch3_rank_bits',
    default='32',
    values=('16', '32'),
    multi=False,
    description='Number of bits allocated to the rank field (16 or 32)'
)
```
if you have a finite set of integers that are supported by the variant, or `netcdf`:
```python
variant(
    'maxdims',
    default=1024,
    description='Defines the maximum dimensions of NetCDF files.',
    values=is_integral
)
```
if you can accept an arbitrary integer value.

**Comment by markcmiller86** [comment]
@tgamblin Thanks. That worked

@alalazo Thanks. Looked at mvapich and that helped me learn how to specify the integer valued variant but not how to use it in a depends_on statement.
