### ISSUE TITLE
Use of RPATH for implicit link directories problematic for build systems that use `LD_LIBRARY_PATH=<build dir> ./executable`

### ISSUE THREAD

**Issue by Thomas-Ulrich** [LLNL/spack#40848]
### Steps to reproduce this issue:

1. Use a compiler that has its runtime libraries in a directory that also contains `lib<example>.so`
2. Install the package `spack install <example>`
3. The build system invokes its just-built executable: `LD_LIBRARY_PATH=<build dir> ./example ...`

The latter fails because the `example` executable contains an RPATH pointing to the implicit link directory of the compiler, which happens to contain `libexample.so` -- this library is picked up instead of the just-built `libexample.so` in `LD_LIBRARY_PATH`.

Notice that Spack itself adds the rpath, the system compiler would only inject the `-L` flag.

The pattern `LD_LIBRARY_PATH=. ./example` is probably most common in autotools packages. CMake packages are not affected as they use build rpaths to work around this problem.

Below is an example where this happens with `perl`.

### Steps to reproduce the issue

```console
[csbcfmpd@login209-18 spack-src]$ spack spec -I perl
Input spec
--------------------------------
 -   perl

Concretized
--------------------------------
 -   perl@5.38.0%gcc@10.1.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-rocky8-icelake
[+]      ^berkeley-db@18.1.40%gcc@10.1.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-rocky8-icelake
[+]          ^gmake@4.4.1%gcc@10.1.0~guile build_system=generic arch=linux-rocky8-icelake
[+]      ^bzip2@1.0.8%gcc@10.1.0~debug~pic+shared build_system=generic arch=linux-rocky8-icelake
[+]          ^diffutils@3.9%gcc@10.1.0 build_system=autotools arch=linux-rocky8-icelake
[+]              ^libiconv@1.17%gcc@10.1.0 build_system=autotools libs=shared,static arch=linux-rocky8-icelake
[+]      ^gdbm@1.23%gcc@10.1.0 build_system=autotools arch=linux-rocky8-icelake
[+]          ^readline@8.2%gcc@10.1.0 build_system=autotools patches=bbf97f1 arch=linux-rocky8-icelake
[+]              ^ncurses@6.4%gcc@10.1.0~symlinks+termlib abi=none build_system=autotools arch=linux-rocky8-icelake
[+]                  ^pkgconf@1.9.5%gcc@10.1.0 build_system=autotools arch=linux-rocky8-icelake
[+]      ^zlib-ng@2.1.4%gcc@10.1.0+compat+opt build_system=autotools arch=linux-rocky8-icelake
```

### Error message

<details><summary>loadable library and perl binaries are mismatched</summary>
[csbcfmpd@login209-18 spack-src]$ spack install -j 40  perl
[+] /mnt/lustre/scratch/nlsas/home/csic/bcf/mpd/Simulation/spack_SeisSol/spack_packages/linux-rocky8-icelake/gcc-10.1.0/berkeley-db-18.1.40-i3j6vwjja62njh2mi6dgg5mqel3m6ani
[+] /mnt/lustre/scratch/nlsas/home/csic/bcf/mpd/Simulation/spack_SeisSol/spack_packages/linux-rocky8-icelake/gcc-10.1.0/bzip2-1.0.8-oo6spantejf27dmb7bzwccfttwtfx7bb
[+] /mnt/lustre/scratch/nlsas/home/csic/bcf/mpd/Simulation/spack_SeisSol/spack_packages/linux-rocky8-icelake/gcc-10.1.0/ncurses-6.4-2kenxblld7jmiylsjweggbentnz3yrbm
[+] /mnt/lustre/scratch/nlsas/home/csic/bcf/mpd/Simulation/spack_SeisSol/spack_packages/linux-rocky8-icelake/gcc-10.1.0/zlib-ng-2.1.4-575jc3ailnn2g7unxmoivbsov7vls7sw
[+] /mnt/lustre/scratch/nlsas/home/csic/bcf/mpd/Simulation/spack_SeisSol/spack_packages/linux-rocky8-icelake/gcc-10.1.0/readline-8.2-cpx6vq4aolpyqj7tguzpiha4hpuexnr5
[+] /mnt/lustre/scratch/nlsas/home/csic/bcf/mpd/Simulation/spack_SeisSol/spack_packages/linux-rocky8-icelake/gcc-10.1.0/gdbm-1.23-ei62qyttjgwe6qlz3sgbipffqt6b7ome
==> Installing perl-5.38.0-2tubazheh7m4pdei3eugarkkduubhga6 [7/7]
==> No binary for perl-5.38.0-2tubazheh7m4pdei3eugarkkduubhga6 found: installing from source
==> Using cached archive: /mnt/lustre/scratch/nlsas/home/csic/bcf/mpd/Simulation/spack_SeisSol/spack/var/spack/cache/_source-cache/archive/21/213ef58089d2f2c972ea353517dc60ec3656f050dcc027666e118b508423e517.tar.gz
==> Using cached archive: /mnt/lustre/scratch/nlsas/home/csic/bcf/mpd/Simulation/spack_SeisSol/spack/var/spack/cache/_source-cache/archive/9d/9da50e155df72bce55cb69f51f1dbb4b62d23740fb99f6178bb27f22ebdf8a46.tar.gz
==> Moving resource stage
        source: /tmp/csbcfmpd/spack-stage/resource-cpanm-2tubazheh7m4pdei3eugarkkduubhga6/spack-src/
        destination: /tmp/csbcfmpd/spack-stage/spack-stage-perl-5.38.0-2tubazheh7m4pdei3eugarkkduubhga6/spack-src/cpanm/cpanm
==> Applied patch /mnt/lustre/scratch/nlsas/home/csic/bcf/mpd/Simulation/spack_SeisSol/spack/var/spack/repos/builtin/packages/perl/zlib-ng.patch
==> Ran patch() for perl
==> perl: Executing phase: 'configure'
==> perl: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j40'

1 error found in build log:
     2831          \
     2832    
     2833    chmod 755 ../../lib/auto/Unicode/Normalize/Normalize.so
     2834    make[1]: Leaving directory '/tmp/csbcfmpd/spack-stage/spack-stage-perl-5.38.0-2tubazheh7m4pdei3eugarkkduubhga6/spack-src/dist/Unicode-Normalize'
     2835    LD_LIBRARY_PATH=/tmp/csbcfmpd/spack-stage/spack-stage-perl-5.38.0-2tubazheh7m4pdei3eugarkkduubhga6/spack-src  ./perl -Ilib -I. -f pod/buildtoc -q
     2836    Cwd.c: loadable library and perl binaries are mismatched (got handshake key 0xf380080, needed 0xcd00080)
  >> 2837    make: *** [makefile:426: pod/perltoc.pod] Error 1

See build log for details:
  /tmp/csbcfmpd/spack-stage/spack-stage-perl-5.38.0-2tubazheh7m4pdei3eugarkkduubhga6/spack-build-out.txt
</details>

### Information on your system

* **Spack:** 0.21.0.dev0 (80944d22f775b014cfd201e895fc8777a2038786)
* **Python:** 3.7.8
* **Platform:** linux-rocky8-icelake
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/13244340/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/13244341/spack-build-out.txt)

The problem is that the perl version compiled in spack-src is not the 5.38.0 but the 5.30.3
```
[csbcfmpd@login209-18 ~]$ cd /tmp/csbcfmpd/spack-stage/spack-stage-perl-5.38.0-2tubazheh7m4pdei3eugarkkduubhga6/spack-src
[csbcfmpd@login209-18 spack-src]$ ./perl --version
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LC_MEASUREMENT = "de_DE.UTF-8",
        LC_PAPER = "de_DE.UTF-8",
        LC_MONETARY = "de_DE.UTF-8",
        LC_NAME = "de_DE.UTF-8",
        LC_ADDRESS = "de_DE.UTF-8",
        LC_NUMERIC = "de_DE.UTF-8",
        LC_TELEPHONE = "de_DE.UTF-8",
        LC_IDENTIFICATION = "de_DE.UTF-8",
        LC_TIME = "de_DE.UTF-8",
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to a fallback locale ("en_US.UTF-8").

This is perl 5, version 30, subversion 3 (v5.30.3) built for x86_64-linux-thread-multi
(with 30 registered patches, see perl -V for more detail)

Copyright 1987-2020, Larry Wall

Perl may be copied only under the terms of either the Artistic License or the
GNU General Public License, which may be found in the Perl 5 source kit.

Complete documentation for Perl, including FAQ lists, should be found on
this system using "man perl" or "perldoc perl".  If you have access to the
```
maintainer: @LydDeb

The issue is related with:
https://github.com/spack/spack/issues/26738

A direct workaround is to install perl@5.30.3

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
:confused: libperl is built with the perl executable.

Can you show 

```
LD_LIBRARY_PATH=/tmp/csbcfmpd/spack-stage/spack-stage-perl-5.38.0-2tubazheh7m4pdei3eugarkkduubhga6/spack-src ldd ./perl 
```

**Comment by Thomas-Ulrich** [comment]
```
[csbcfmpd@login209-18 spack-src]$ LD_LIBRARY_PATH=/tmp/csbcfmpd/spack-stage/spack-stage-perl-5.38.0-2tubazheh7m4pdei3eugarkkduubhga6/spack-src ldd ./perl 
        linux-vdso.so.1 (0x00007ffcb1b0f000)
        libperl.so => /mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib64/libperl.so (0x00007fc931c90000)
        libpthread.so.0 => /mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/lib64/libpthread.so.0 (0x00007fc931c14000)
        libdl.so.2 => /mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/lib64/libdl.so.2 (0x00007fc931c0e000)
        libm.so.6 => /mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/lib64/libm.so.6 (0x00007fc931acc000)
        libcrypt.so.1 => /mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/lib64/libcrypt.so.1 (0x00007fc931a93000)
        libutil.so.1 => /mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/lib64/libutil.so.1 (0x00007fc931a8e000)
        libc.so.6 => /mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib64/libc.so.6 (0x00007fc9318cf000)
        /mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/lib64/ld-linux-x86-64.so.2 (0x00007fc931ff4000)
```

**Comment by LydDeb** [comment]
What version is printed when you load perl ?
```
spack load perl@5.38.0 # or 'spack load /2tubazh' if you have multiple installation of perl
which(perl) # to be sure
perl --version
```

**Comment by Thomas-Ulrich** [comment]
perl is not (fully) installed by spack, so I cannot load it.

**Comment by LydDeb** [comment]
Did you try to install perl with 1 process instead of 40?
```
$ spack install -j 1 perl
```

**Comment by Thomas-Ulrich** [comment]
same
```
==> Installing perl-5.38.0-2tubazheh7m4pdei3eugarkkduubhga6 [7/7]
==> No binary for perl-5.38.0-2tubazheh7m4pdei3eugarkkduubhga6 found: installing from source
==> Using cached archive: /mnt/lustre/scratch/nlsas/home/csic/bcf/mpd/Simulation/spack_SeisSol/spack/var/spack/cache/_source-cache/archive/21/213ef58089d2f2c972ea353517dc60ec3656f050dcc027666e118b508423e517.tar.gz
==> Using cached archive: /mnt/lustre/scratch/nlsas/home/csic/bcf/mpd/Simulation/spack_SeisSol/spack/var/spack/cache/_source-cache/archive/9d/9da50e155df72bce55cb69f51f1dbb4b62d23740fb99f6178bb27f22ebdf8a46.tar.gz
==> Moving resource stage
        source: /tmp/csbcfmpd/spack-stage/resource-cpanm-2tubazheh7m4pdei3eugarkkduubhga6/spack-src/
        destination: /tmp/csbcfmpd/spack-stage/spack-stage-perl-5.38.0-2tubazheh7m4pdei3eugarkkduubhga6/spack-src/cpanm/cpanm
==> Applied patch /mnt/lustre/scratch/nlsas/home/csic/bcf/mpd/Simulation/spack_SeisSol/spack/var/spack/repos/builtin/packages/perl/zlib-ng.patch
==> Ran patch() for perl
==> perl: Executing phase: 'configure'
==> perl: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j1'

1 error found in build log:
     2772       -lpthread   \
     2773    
     2774    chmod 755 ../../lib/auto/threads/shared/shared.so
     2775    make[1]: Leaving directory '/tmp/csbcfmpd/spack-stage/spack-stage-perl-5.38.0-2tubazheh7m4pdei3eugarkkduubhga6/spack-src/dist/threads-shared'
     2776    LD_LIBRARY_PATH=/tmp/csbcfmpd/spack-stage/spack-stage-perl-5.38.0-2tubazheh7m4pdei3eugarkkduubhga6/spack-src  ./perl -Ilib -I. -f pod/buildtoc -q
     2777    Cwd.c: loadable library and perl binaries are mismatched (got handshake key 0xf380080, needed 0xcd00080)
  >> 2778    make: *** [makefile:426: pod/perltoc.pod] Error 1
```

**Comment by Thomas-Ulrich** [comment]
So I think the problem stems from perl 5.30.3 being installed on the system (/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib64/libperl.so), and interacting with the spack perl installation.

**Comment by haampie** [comment]
Sorry, didn't get back to this.

Does your compiler add an `rpath` to `/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib64/`?

I think that's the most likely explanation.

`readelf -d ./perl` and see if the path pops up.

**Comment by Thomas-Ulrich** [comment]
Yes you are right:

 0x000000000000000f (RPATH)              Library rpath: [/mnt/lustre/scratch/nlsas/home/csic/bcf/mpd/Simulation/spack_SeisSol/spack_packages/linux-rocky8-icelake/gcc-11.2.0/perl-5.38.0-duio5rn3d2cveq46nfjhgayoy57ef5or/lib/5.38.0/x86_64-linux-thread-multi/CORE:/mnt/lustre/scratch/nlsas/home/csic/bcf/mpd/Simulation/spack_SeisSol/spack_packages/linux-rocky8-icelake/gcc-11.2.0/perl-5.38.0-duio5rn3d2cveq46nfjhgayoy57ef5or/lib:/mnt/lustre/scratch/nlsas/home/csic/bcf/mpd/Simulation/spack_SeisSol/spack_packages/linux-rocky8-icelake/gcc-11.2.0/perl-5.38.0-duio5rn3d2cveq46nfjhgayoy57ef5or/lib64:/mnt/lustre/scratch/nlsas/home/csic/bcf/mpd/Simulation/spack_SeisSol/spack_packages/linux-rocky8-icelake/gcc-11.2.0/zlib-ng-2.1.4-bguqjk5vcijhyya3g2sgzsutizdqzl7m/lib:/mnt/lustre/scratch/nlsas/home/csic/bcf/mpd/Simulation/spack_SeisSol/spack_packages/linux-rocky8-icelake/gcc-11.2.0/gdbm-1.23-xibuh3gcim6fcmyvq3ptmr4q2hyvhdch/lib:/mnt/lustre/scratch/nlsas/home/csic/bcf/mpd/Simulation/spack_SeisSol/spack_packages/linux-rocky8-icelake/gcc-11.2.0/readline-8.2-bbmcnyyn2qiafeowfhrqhd3wb4vv4ltd/lib:/mnt/lustre/scratch/nlsas/home/csic/bcf/mpd/Simulation/spack_SeisSol/spack_packages/linux-rocky8-icelake/gcc-11.2.0/ncurses-6.4-6vdzdyphb4q6uzsdoinnk2p5eefcuieh/lib:/mnt/lustre/scratch/nlsas/home/csic/bcf/mpd/Simulation/spack_SeisSol/spack_packages/linux-rocky8-icelake/gcc-11.2.0/bzip2-1.0.8-z6ze3oy3hrl3fq54zvkg523wdswgvnsq/lib:/mnt/lustre/scratch/nlsas/home/csic/bcf/mpd/Simulation/spack_SeisSol/spack_packages/linux-rocky8-icelake/gcc-11.2.0/berkeley-db-18.1.40-63xb6lwyi4sbnfmrpocgpga3tpo6zrjp/lib:/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib/gcc/x86_64-pc-linux-gnu/11.2.0:**/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib64:/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib**]

**Comment by haampie** [comment]
And what does `gcc helloworld.c -###` output for that compiler? (Outside the spack build environment)

I wonder if the compiler just adds generic `-L` flags, and Spack decides it should also `-Wl,-rpath` those, as they are considered implicit link paths.

One way to work around this issue would be to set:

```
spack config add config:shared_linking:type:runpath`
```

that way `LD_LIBRARY_PATH` takes precedence. But if you do that it's best to rebuild everything with that option on, cause mixing rpath and runpath is known to lead to other issues...

**Comment by Thomas-Ulrich** [comment]
```
$gcc helloworld.c -###
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/libexec/gcc/x86_64-pc-linux-gnu/10.1.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/var/tmp/portage/sys-devel/gcc-10.1.0-r2/work/gcc-10.1.0/configure --host=x86_64-pc-linux-gnu --build=x86_64-pc-linux-gnu --prefix=/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr --bindir=/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/x86_64-pc-linux-gnu/gcc-bin/10.1.0 --includedir=/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/include --datadir=/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/share/gcc-data/x86_64-pc-linux-gnu/10.1.0 --mandir=/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/share/gcc-data/x86_64-pc-linux-gnu/10.1.0/man --infodir=/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/share/gcc-data/x86_64-pc-linux-gnu/10.1.0/info --with-gxx-include-dir=/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/include/g++-v10 --with-python-dir=/share/gcc-data/x86_64-pc-linux-gnu/10.1.0/python --enable-languages=c,c++,fortran --enable-obsolete --enable-secureplt --disable-werror --with-system-zlib --enable-nls --without-included-gettext --enable-checking=release --with-bugurl=https://bugs.gentoo.org/ --with-pkgversion='Gentoo 10.1.0-r2 p3' --disable-esp --enable-libstdcxx-time --enable-shared --enable-threads=posix --enable-__cxa_atexit --enable-clocale=gnu --disable-multilib --with-multilib-list=m64 --disable-fixed-point --enable-targets=all --enable-libgomp --disable-libmudflap --disable-libssp --disable-libada --disable-systemtap --enable-vtable-verify --without-zstd --enable-lto --without-isl --enable-default-pie --enable-default-ssp --with-sysroot=/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.1.0 (Gentoo 10.1.0-r2 p3) 
COLLECT_GCC_OPTIONS='-mtune=generic' '-march=x86-64'
 /mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/libexec/gcc/x86_64-pc-linux-gnu/10.1.0/cc1 -quiet helloworld.c -quiet -dumpbase helloworld.c "-mtune=generic" "-march=x86-64" -auxbase helloworld -o /tmp/ccl6JeUH.s
COLLECT_GCC_OPTIONS='-mtune=generic' '-march=x86-64'
 /mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../x86_64-pc-linux-gnu/bin/as --64 -o /tmp/ccYrjgUH.o /tmp/ccl6JeUH.s
COMPILER_PATH=/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/libexec/gcc/x86_64-pc-linux-gnu/10.1.0/:/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/libexec/gcc/x86_64-pc-linux-gnu/10.1.0/:/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/libexec/gcc/x86_64-pc-linux-gnu/:/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/:/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib/gcc/x86_64-pc-linux-gnu/:/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../x86_64-pc-linux-gnu/bin/
LIBRARY_PATH=/opt/cesga/2020/software/Core/python/3.9.9/lib/../lib64/:/opt/cesga/2020/software/Compiler/gcccore/system/ucx/1.11.2/lib/../lib64/:/opt/cesga/2020/software/Core/hwloc/2.2.0/lib/../lib64/:/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib64/../lib64/:/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/:/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../lib64/:/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/lib/../lib64/:/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib/../lib64/:/opt/cesga/2020/software/Core/imkl/2021.3.0/compiler/latest/linux/compiler/lib/intel64_lin/:/opt/cesga/2020/software/Core/imkl/2021.3.0/compiler/latest/linux/lib/emu/:/opt/cesga/2020/software/Core/imkl/2021.3.0/compiler/latest/linux/lib/x64/:/opt/cesga/2020/software/Core/imkl/2021.3.0/compiler/latest/linux/lib/:/opt/cesga/2020/software/Core/imkl/2021.3.0/tbb/latest/lib/intel64/gcc4.8/:/opt/cesga/2020/software/Core/imkl/2021.3.0/lib/intel64/:/opt/cesga/2020/software/Core/python/3.9.9/lib/:/opt/cesga/2020/software/Compiler/gcccore/system/ucx/1.11.2/lib/:/opt/cesga/2020/software/Core/hwloc/2.2.0/lib/:/opt/cesga/2020/software/Core/intel/2021.3.0/compiler/2021.3.0/linux/compiler/lib/intel64_lin/:/opt/cesga/2020/software/Core/intel/2021.3.0/compiler/2021.3.0/linux/lib/x64/:/opt/cesga/2020/software/Core/intel/2021.3.0/compiler/2021.3.0/linux/lib/:/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib64/:/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../x86_64-pc-linux-gnu/lib/:/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/../../../:/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/lib/:/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib/
COLLECT_GCC_OPTIONS='-mtune=generic' '-march=x86-64'
 /mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/libexec/gcc/x86_64-pc-linux-gnu/10.1.0/collect2 -plugin /mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/libexec/gcc/x86_64-pc-linux-gnu/10.1.0/liblto_plugin.so "-plugin-opt=/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/libexec/gcc/x86_64-pc-linux-gnu/10.1.0/lto-wrapper" "-plugin-opt=-fresolution=/tmp/ccyGpswH.res" "-plugin-opt=-pass-through=-lgcc" "-plugin-opt=-pass-through=-lgcc_s" "-plugin-opt=-pass-through=-lc" "-plugin-opt=-pass-through=-lgcc" "-plugin-opt=-pass-through=-lgcc_s" --eh-frame-hdr -m elf_x86_64 -dynamic-linker /mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/lib64/ld-linux-x86-64.so.2 -pie /mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib64/../lib64/Scrt1.o /mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib64/../lib64/crti.o /mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/crtbeginS.o -L/opt/cesga/2020/software/Core/python/3.9.9/lib/../lib64 -L/opt/cesga/2020/software/Compiler/gcccore/system/ucx/1.11.2/lib/../lib64 -L/opt/cesga/2020/software/Core/hwloc/2.2.0/lib/../lib64 -L/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib64/../lib64 -L/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0 -L/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../lib64 -L/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/lib/../lib64 -L/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib/../lib64 -L/opt/cesga/2020/software/Core/imkl/2021.3.0/compiler/latest/linux/compiler/lib/intel64_lin -L/opt/cesga/2020/software/Core/imkl/2021.3.0/compiler/latest/linux/lib/emu -L/opt/cesga/2020/software/Core/imkl/2021.3.0/compiler/latest/linux/lib/x64 -L/opt/cesga/2020/software/Core/imkl/2021.3.0/compiler/latest/linux/lib -L/opt/cesga/2020/software/Core/imkl/2021.3.0/tbb/latest/lib/intel64/gcc4.8 -L/opt/cesga/2020/software/Core/imkl/2021.3.0/lib/intel64 -L/opt/cesga/2020/software/Core/python/3.9.9/lib -L/opt/cesga/2020/software/Compiler/gcccore/system/ucx/1.11.2/lib -L/opt/cesga/2020/software/Core/hwloc/2.2.0/lib -L/opt/cesga/2020/software/Core/intel/2021.3.0/compiler/2021.3.0/linux/compiler/lib/intel64_lin -L/opt/cesga/2020/software/Core/intel/2021.3.0/compiler/2021.3.0/linux/lib/x64 -L/opt/cesga/2020/software/Core/intel/2021.3.0/compiler/2021.3.0/linux/lib -L/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib64 -L/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/../../../../x86_64-pc-linux-gnu/lib -L/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/../../.. -L/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/lib -L/mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib /tmp/ccYrjgUH.o -lgcc --push-state --as-needed -lgcc_s --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib/gcc/x86_64-pc-linux-gnu/10.1.0/crtendS.o /mnt/netapp1/Optcesga_FT2_RHEL7/2020/gentoo/22072020/usr/lib64/../lib64/crtn.o
COLLECT_GCC_OPTIONS='-mtune=generic' '-march=x86-64'
```

**Comment by haampie** [comment]
Yeah, that confirms Spack is shooting itself in the foot by adding rpaths for implicit link directories added by the compiler. 

The compiler just happens to have its support libraries installed in a noisy dir where system libperl.so is too.

Issue would be solved by RUNPATH as a default instead of RPATH.

EDIT: I've updated the PR title and description to something more generic, but kept your original report.

**Comment by haampie** [comment]
A way out would be to determine "system paths" dynamically, which we can do now that `glibc` is external.

For recent `glibc` at least

```
$ /lib64/ld-linux-x86-64.so.2 --help | grep '(system search path)'
  /lib/x86_64-linux-gnu (system search path)
  /usr/lib/x86_64-linux-gnu (system search path)
  /lib (system search path)
  /usr/lib (system search path)
```

and avoid registering rpaths to those directories.

System paths are pretty weird in Spack anwyays... a bunch of hard-coded paths. In reality a "system path" is not static, especially on systems with multiple glibcs like gentoo prefix and nix(os). Also the concept of "the system paths" makes little sense, since it's relative to the  tool as well: `gcc` and `ld.so` may disagree about default paths.
