### ISSUE TITLE
Can Spack NOT echo "Run patch()..." when no patches are defined

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/spack#4085]
Spack appears to echo "Ran patch() for foobar" even if no patch is implemented. This was puzzling me a bit because I hadn't defined any patches for a package I was writing.

Can Spack just NOT echo this line if it is NOT applying any patches?

**Comment by adamjstewart** [comment]
Technically, `patch()` is always defined in `lib/spack/spack/package.py`. It doesn't do anything by default, but can be overridden. So it may be hard to tell whether or not `patch()` has been implemented. But I agree that it can be confusing, so if we can get it to not print that line it would be good.

**Comment by citibeth** [comment]
Come on, this would not be too hard to solve.  Before running `mypackage.patch()`, check if `mypackage.patch == Package.patch`.  Would @markcmiller86 like to submit a PR?

**Comment by alalazo** [comment]
@citibeth See #4103 ?

**Comment by citibeth** [comment]
LGTM.  Only issue is whether it should print anything at all when there's
no patch.

On Wed, May 3, 2017 at 8:07 AM, Massimiliano Culpo <notifications@github.com
