### ISSUE TITLE
Spack list has problems with multiple wildcards in filter

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#409]
`spack list` cannot always handle the case where the filter starts and ends with an asterisk:

```bash
$ spack list *ar
==> 3 packages.
bear  py-pypar  tar
$ spack list ar*
==> 1 packages.
arpack
$ spack list *ar*
==> 0 packages.
```

Sometimes it can:

```bash
$ spack list *log*
==> 1 packages.
glog
$ spack list *l*o*g*
==> 2 packages.
cloog  glog
```

Something must be broken here. Personally, if I didn't know the exact name of a package, I would first try putting a wildcard at the beginning and end, so this isn't a completely trivial bug.

**Comment by adamjstewart** [comment]
Figured out my mistake. Somehow I forgot that Bash expands wildcards before executing commands. So for example, if I'm in the spack root directory:
```
spack list *ar*
```
Actually looks like:
```
spack list share var
```
to Spack. If I properly suppress globbing, I get the expected result:
```
$ spack list '*ar*'
==> 20 packages.
activeharmony   harfbuzz    parallel-netcdf  parpack       py-scikit-learn      
arpack          libarchive  paraver          py-pycparser  sparsehash           
bear            libdwarf    paraview         py-pypar      tar                  
cbtf-argonavis  opari2      parmetis         py-pyparsing  the_silver_searcher  
```

**Comment by tgamblin** [comment]
You could also write this:

```bash
$ spack list \*ar\*
```

Although quoting is prettier IMHO.  In general it's a bit of a pain to allow glob strings for stuff like this -- I wish commands could provide a little context to tell bash when to/not to expand something.
