### ISSUE TITLE
Installation issue: intel-xed

### ISSUE THREAD

**Issue by blue42u** [LLNL/spack#40912]
### Steps to reproduce the issue

```console
$ spack spec -I intel-xed@2022.04.17
Input spec
--------------------------------
 -   intel-xed@2022.04.17

Concretized
--------------------------------
 -   intel-xed@2022.04.17%gcc@11.4.0~debug~pic build_system=generic patches=c6aa5f7 arch=linux-ubuntu22.04-zen2
[+]      ^python@3.11.6%gcc@11.4.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=13fa8bf,b0615b2,ebdca64,f2fd060 arch=linux-ubuntu22.04-zen2
[+]          ^bzip2@1.0.8%gcc@11.4.0~debug~pic+shared build_system=generic arch=linux-ubuntu22.04-zen2
[+]              ^diffutils@3.9%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-zen2
[+]          ^expat@2.5.0%gcc@11.4.0+libbsd build_system=autotools arch=linux-ubuntu22.04-zen2
[+]              ^gmake@4.4.1%gcc@11.4.0~guile build_system=generic arch=linux-ubuntu22.04-zen2
[+]              ^libbsd@0.11.7%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-zen2
[+]                  ^libmd@1.0.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-zen2
[+]          ^gdbm@1.23%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-zen2
[+]          ^gettext@0.22.3%gcc@11.4.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-ubuntu22.04-zen2
[+]              ^libiconv@1.17%gcc@11.4.0 build_system=autotools libs=shared,static arch=linux-ubuntu22.04-zen2
[+]              ^libxml2@2.10.3%gcc@11.4.0+pic~python+shared build_system=autotools arch=linux-ubuntu22.04-zen2
[+]              ^tar@1.34%gcc@11.4.0 build_system=autotools zip=pigz arch=linux-ubuntu22.04-zen2
[+]                  ^pigz@2.7%gcc@11.4.0 build_system=makefile arch=linux-ubuntu22.04-zen2
[+]                  ^zstd@1.5.5%gcc@11.4.0+programs build_system=makefile compression=none libs=shared,static arch=linux-ubuntu22.04-zen2
[+]          ^libffi@3.4.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-zen2
[+]          ^libxcrypt@4.4.35%gcc@11.4.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-ubuntu22.04-zen2
[+]              ^perl@5.38.0%gcc@11.4.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-ubuntu22.04-zen2
[+]                  ^berkeley-db@18.1.40%gcc@11.4.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu22.04-zen2
[+]          ^ncurses@6.4%gcc@11.4.0~symlinks+termlib abi=none build_system=autotools arch=linux-ubuntu22.04-zen2
[+]          ^openssl@3.1.3%gcc@11.4.0~docs+shared build_system=generic certs=mozilla arch=linux-ubuntu22.04-zen2
[+]              ^ca-certificates-mozilla@2023-05-30%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-zen2
[+]          ^pkgconf@1.9.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-zen2
[+]          ^readline@8.2%gcc@11.4.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu22.04-zen2
[+]          ^sqlite@3.43.2%gcc@11.4.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-ubuntu22.04-zen2
[+]          ^util-linux-uuid@2.38.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-zen2
[+]          ^xz@5.4.1%gcc@11.4.0~pic build_system=autotools libs=shared,static arch=linux-ubuntu22.04-zen2
[+]          ^zlib-ng@2.1.4%gcc@11.4.0+compat+opt build_system=autotools arch=linux-ubuntu22.04-zen2
```

### Error message

<details><summary>Error message</summary>

<pre>
...
==> [2023-11-06-18:02:11.737554] Cloning git repository: https://github.com/intelxed/mbuild.git at commit ef19f00de14a9c2c253c1c9b1119e1617280e3f2
==> [2023-11-06-18:02:11.737697] '/usr/bin/git' '-c' 'advice.detachedHead=false' '--version'
==> [2023-11-06-18:02:11.739509] '/usr/bin/git' '-c' 'advice.detachedHead=false' '-c' 'advice.detachedHead=false' 'clone' 'https://github.com/intelxed/mbuild.git'
Cloning into 'mbuild'...
remote: Enumerating objects: 555, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 555 (delta 5), reused 4 (delta 4), pack-reused 539
Receiving objects: 100% (555/555), 208.87 KiB | 1.70 MiB/s, done.
Resolving deltas: 100% (371/371), done.
==> [2023-11-06-18:02:12.369096] '/usr/bin/git' '-c' 'advice.detachedHead=false' '-c' 'advice.detachedHead=false' 'checkout' 'ef19f00de14a9c2c253c1c9b1119e1617280e3f2'
fatal: reference is not a tree: ef19f00de14a9c2c253c1c9b1119e1617280e3f2
==> [2023-11-06-18:02:12.371156] ProcessError: Command exited with status 128:
    '/usr/bin/git' '-c' 'advice.detachedHead=false' '-c' 'advice.detachedHead=false' 'checkout' 'ef19f00de14a9c2c253c1c9b1119e1617280e3f2'
==> [2023-11-06-18:02:12.371194] Fetching from [git] https://github.com/intelxed/mbuild.git at commit ef19f00de14a9c2c253c1c9b1119e1617280e3f2 failed.
==> [2023-11-06-18:02:12.378824] Error: FetchError: All fetchers failed for resource-mbuild-alepac5luv2btoxmeuf4vmg4ltd7okdz
Traceback (most recent call last):
  File "/opt/spack/lib/spack/spack/build_environment.py", line 1092, in _setup_pkg_and_run
    return_value = function(pkg, kwargs)
  File "/opt/spack/lib/spack/spack/installer.py", line 2496, in build_process
    return installer.run()
  File "/opt/spack/lib/spack/spack/installer.py", line 2337, in run
    self.pkg.do_patch()
  File "/opt/spack/lib/spack/spack/package_base.py", line 1463, in do_patch
    self.do_stage()
  File "/opt/spack/lib/spack/spack/package_base.py", line 1448, in do_stage
    self.do_fetch(mirror_only)
  File "/opt/spack/lib/spack/spack/package_base.py", line 1432, in do_fetch
    self.stage.fetch(mirror_only, err_msg=err_msg)
  File "/opt/spack/lib/spack/spack/util/pattern.py", line 16, in __call__
    return [getattr(item, self.name)(*args, **kwargs) for item in self.container]
  File "/opt/spack/lib/spack/spack/util/pattern.py", line 16, in <listcomp>
    return [getattr(item, self.name)(*args, **kwargs) for item in self.container]
  File "/opt/spack/lib/spack/spack/stage.py", line 525, in fetch
    raise spack.error.FetchError(err_msg or default_msg, None)
spack.error.FetchError: All fetchers failed for resource-mbuild-alepac5luv2btoxmeuf4vmg4ltd7okdz
==> [2023-11-06-18:02:12.379160] Flagging intel-xed-2022.04.17-alepac5luv2btoxmeuf4vmg4ltd7okdz as failed: FetchError: All fetchers failed for resource-mbuild-alepac5luv2btoxmeuf4vmg4ltd7okdz
==> [2023-11-06-18:02:12.383650] ChildError: FetchError: All fetchers failed for resource-mbuild-alepac5luv2btoxmeuf4vmg4ltd7okdz
</pre></details>

### Information on your system

* **Spack:** 0.21.0.dev0 (141c7de5d89f32b203438e1d6fca1efd817299f7)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-zen2
* **Concretizer:** clingo

### Additional information

@mwkrentel 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by mwkrentel** [comment]
@blue42u 
Indeed, commit eef9939c21c6 from Aug 2023 added git hashes to versions
of some 150 packages that previously only had git tags, so they now
have both (why?).  But for intel-xed, the hash for mbuild was taken
from the xed repo, so it was the wrong hash.  Probably because both
the xed and mbuild repos had a tag named v2022.04.17.

I've submitted #40922 which should fix this, and also added the new,
latest version 2023.10.11.

Thanks for noticing this.  It seems only rev 2022.04.17 was affected
by the bad hash.
