### ISSUE TITLE
Have a MakefilePackage that wants to be told what fortran name mangling is

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/spack#4104]
I am adding Chombo package.

It has logic to manage fortran name mangling but requires the makefile variables to be set up appropriately. Does spack know the fortran name mangling? I suppose I can have my edit phase do a fortran compile of a hello world program and then query name mangling from that. Anyone have any better ideas?

**Comment by tgamblin** [comment]
@markcmiller86 : Terry Ligocki is already working on a Chombo package -- I believe he's almost done. @drhansj could probably say more, and I'm not sure what Terry's Github username is.

**Comment by markcmiller86** [comment]
Too bad. I need it *this*week*. And, its basically working on OSX. I haven't tried on surface yet but expect to tomorrow. I dropped the ball on some FASTMath work on Spack and am trying to remedy that this week. Oops..there, my build just completed fine.

**Comment by drhansj** [comment]
Your call - we missed our deadlines, if you have to move on without chombo
that's fine.

We have a successful chombo build with spack, but it's re-building
libraries that xsdk installed (probably version issues). Our fork is here,
but the pull request isn't ready:
https://github.com/drhansj/spack

Terry is working on it ... his github is "tjligocki".

Hans

**Comment by tgamblin** [comment]
@tjligocki

**Comment by citibeth** [comment]
CMake auto-detects Fortran name mangling:

https://cmake.org/cmake/help/v3.0/module/FortranCInterface.html

Just write a short `CMakeFiles.txt` file, have Spack run it, and pull the result out of `CMakeCache.txt` and patch it into the `Makefile`.  Or better yet, just write a CMake build for the whole project and switch to `CMakePackage`.  I know the Chombo folks, I could give them a ring over this issue...

If you prefer Autotools, they detect Fortran name mangling as well.  The same principle applies: write a short Autotools script to detect the name mangling, and then pull it out of the resulting config file.  Search this page for "name-mangling":

https://www.gnu.org/software/autoconf/manual/autoconf-2.64/html_node/Fortran-Compiler.html

With Fotran 2003 Interop, you should no longer have to know Fortran name mangling specifics in order to interface with C.  So another possibility would be to convert the application itself to the modern (14-year-old) Fortran standard.

**Comment by adamjstewart** [comment]
@citibeth I don't think either of those solutions will give @markcmiller86 a working Chombo package by the end of this week :laughing:

**Comment by citibeth** [comment]
Not true.  It doesn't take long (30 min) to write a short `CMakeLists.txt`
file that just checks Fortran and does nothing else.  Then parsing out the
resulting `CMakeCache.txt` file isn't too hard either; but will probably
take a little longer than writing the original `CMakeLists.txt`.

Certainly this would be easier than re-inventing the Fortran name mangling
detection logic --- which has apparently already been invented twice.

**Comment by drhansj** [comment]
Hi everyone -

Don't know why I'm on this thread ... but I replied last night that we have
a working chombo-xsdk package.py, Terry's just cleaning up xsdk version
compatibilities. If you want to see/try it, it's here on the "develop"
branch of my fork:
https://github.com/drhansj/spack

Chombo's pre-processor is not just C compatibility, it's also
source-to-source translation. I've talked with the Chombo team about moving
to CMake but they've decided they don't want to at this time.

Hans

**Comment by markcmiller86** [comment]
Lets plan to merge repsective implementations in near futre, after May 15 for me anyways.

FWIW, I am not using xsdk _interface_ to Chombo. I am using Chombo's _native_ make system and not assuming there is anything wrapping that to facilitate a common build api.

**Comment by drhansj** [comment]
Mark -

Do you need to use Chombo for something outside xsdk? That's why Terry is
working on a spack package.py for Chombo that's compatible with xsdk (not
driven by xsdk) ...

Feel free to contact me directly with questions/goals.

Hans

**Comment by citibeth** [comment]
An independent Spack package for Chombo would absolutely be a good thing.
For one thing, it would allow me to (someday) use the BISICLES ice sheet
model.

**Comment by markcmiller86** [comment]
> @drhansj Do you need to use Chombo for something outside xsdk? That's why Terry is
working on a spack package.py for Chombo that's compatible with xsdk (not
driven by xsdk) ...

Yes, outside xsdk. I had forgotten to complete a pull request for an uber FASTMath package that builds a slew of FASTMath SciDAC packages including Chombo. And, I need to have that PR completed this week so our final report matches whats available in Spack. This is something that I had a summer student complete more than a year ago but was left on an ancient version of Spack and so never got pulled in.

**Comment by drhansj** [comment]
Hi Mark -

Shall we continue this discussion about what to do with the 2 different
chombo packages? We just finished our xsdk version, Todd is looking at the
pull request.

Hans

**Comment by markcmiller86** [comment]
Hi Hans,

Sure...first question...what is diff. between Chombo and Chombo-Xsdk?

Here is what I had assumed...I thought that Chombo-Xsdk was Chombo + some additional CMake (or Autoconf) logic to support the XSDK adopted handful of configure/build flags (e.g. --prefix, etc.). Or, are there real differences in Chombo libraries that result from a build?

Mark


"Hans Johansen" wrote:

Hi Mark -

Shall we continue this discussion about what to do with the 2 different
chombo packages? We just finished our xsdk version, Todd is looking at the
pull request.

Hans
