### ISSUE TITLE
Installation issue: Glibc-2.38 fail to compile on Power9

### ISSUE THREAD

**Issue by ipcamit** [LLNL/spack#41052]
### Steps to reproduce the issue

```console
[lassen709:spack-env]$ spack spec -I  glibc
Input spec
--------------------------------
 -   glibc

Concretized
--------------------------------
 -   glibc@2.38%gcc@10.2.1 build_system=autotools arch=linux-rhel7-power9le
[+]      ^bison@3.8.2%gcc@10.2.1 build_system=autotools arch=linux-rhel7-power9le
[+]          ^diffutils@3.9%gcc@10.2.1 build_system=autotools arch=linux-rhel7-power9le
[+]          ^m4@1.4.19%gcc@10.2.1+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-rhel7-power9le
[+]      ^gawk@5.2.2%gcc@10.2.1~nls build_system=autotools arch=linux-rhel7-power9le
[+]          ^gmp@6.2.1%gcc@10.2.1+cxx build_system=autotools libs=shared,static patches=69ad2e2 arch=linux-rhel7-power9le
[+]              ^autoconf@2.69%gcc@10.2.1 build_system=autotools patches=35c4492,7793209,a49dd5b arch=linux-rhel7-power9le
[+]              ^automake@1.16.5%gcc@10.2.1 build_system=autotools arch=linux-rhel7-power9le
[+]              ^libtool@2.4.7%gcc@10.2.1 build_system=autotools arch=linux-rhel7-power9le
[+]          ^libsigsegv@2.14%gcc@10.2.1 build_system=autotools arch=linux-rhel7-power9le
[+]          ^mpfr@4.2.0%gcc@10.2.1 build_system=autotools libs=shared,static arch=linux-rhel7-power9le
[+]              ^autoconf-archive@2023.02.20%gcc@10.2.1 build_system=autotools arch=linux-rhel7-power9le
[+]          ^readline@8.2%gcc@10.2.1 build_system=autotools patches=bbf97f1 arch=linux-rhel7-power9le
[+]      ^gettext@0.22.3%gcc@10.2.1+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-rhel7-power9le
[+]          ^bzip2@1.0.8%gcc@10.2.1~debug~pic+shared build_system=generic arch=linux-rhel7-power9le
[+]          ^libiconv@1.17%gcc@10.2.1 build_system=autotools libs=shared,static arch=linux-rhel7-power9le
[+]          ^libxml2@2.10.3%gcc@10.2.1+pic~python+shared build_system=autotools arch=linux-rhel7-power9le
[+]          ^ncurses@6.4%gcc@10.2.1~symlinks+termlib abi=none build_system=autotools arch=linux-rhel7-power9le
[+]          ^tar@1.34%gcc@10.2.1 build_system=autotools zip=pigz arch=linux-rhel7-power9le
[+]              ^pigz@2.7%gcc@10.2.1 build_system=makefile arch=linux-rhel7-power9le
[+]              ^zstd@1.5.5%gcc@10.2.1+programs build_system=makefile compression=none libs=shared,static arch=linux-rhel7-power9le
[+]          ^xz@5.4.1%gcc@10.2.1~pic build_system=autotools libs=shared,static arch=linux-rhel7-power9le
[+]      ^gmake@4.4.1%gcc@10.2.1~guile build_system=generic arch=linux-rhel7-power9le
[+]      ^gnuconfig@2022-09-17%gcc@10.2.1 build_system=generic arch=linux-rhel7-power9le
[+]      ^linux-headers@6.5.2%gcc@10.2.1 build_system=generic arch=linux-rhel7-power9le
[+]      ^perl@5.38.0%gcc@10.2.1+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-rhel7-power9le
[+]          ^berkeley-db@18.1.40%gcc@10.2.1+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-rhel7-power9le
[+]          ^gdbm@1.23%gcc@10.2.1 build_system=autotools arch=linux-rhel7-power9le
[+]          ^zlib-ng@2.1.4%gcc@10.2.1+compat+opt build_system=autotools arch=linux-rhel7-power9le
[+]      ^python@3.11.6%gcc@10.2.1+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=13fa8bf,b0615b2,ebdca64,f2fd060 arch=linux-rhel7-power9le
[+]          ^expat@2.5.0%gcc@10.2.1+libbsd build_system=autotools arch=linux-rhel7-power9le
[+]              ^libbsd@0.11.7%gcc@10.2.1 build_system=autotools arch=linux-rhel7-power9le
[+]                  ^libmd@1.0.4%gcc@10.2.1 build_system=autotools arch=linux-rhel7-power9le
[+]          ^libffi@3.4.4%gcc@10.2.1 build_system=autotools arch=linux-rhel7-power9le
[+]          ^libxcrypt@4.4.35%gcc@10.2.1~obsolete_api build_system=autotools patches=4885da3 arch=linux-rhel7-power9le
[+]          ^openssl@3.1.3%gcc@10.2.1~docs+shared build_system=generic certs=mozilla arch=linux-rhel7-power9le
[+]              ^ca-certificates-mozilla@2023-05-30%gcc@10.2.1 build_system=generic arch=linux-rhel7-power9le
[+]          ^pkgconf@1.9.5%gcc@10.2.1 build_system=autotools arch=linux-rhel7-power9le
[+]          ^sqlite@3.43.2%gcc@10.2.1+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-rhel7-power9le
[+]          ^util-linux-uuid@2.38.1%gcc@10.2.1 build_system=autotools arch=linux-rhel7-power9le
[+]      ^sed@4.9%gcc@10.2.1 build_system=autotools arch=linux-rhel7-power9le
[+]      ^texinfo@7.0.3%gcc@10.2.1 build_system=autotools arch=linux-rhel7-power9le
```

### Error message

<details><summary>Error message</summary>
<pre>
==> Installing glibc-2.38-7cn4wmb425j6mkh5atnt3uodic3sbpa4 [35/35]
==> No binary for glibc-2.38-7cn4wmb425j6mkh5atnt3uodic3sbpa4 found: installing from source
==> Using cached archive: /p/vast1/username/spack-env/spack/var/spack/cache/_source-cache/archive/16/16e51e0455e288f03380b436e41d5927c60945abd86d0c9852b84be57dd
6ed5e.tar.gz
==> Ran patch() for glibc
==> glibc: Executing phase: 'autoreconf'
==> glibc: Executing phase: 'configure'
==> glibc: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16' '-C' '..' 'objdir=/tmp/username/spack-stage/spack-stage-glibc-2.38-7cn4wmb425j6mkh5atnt3uodic3sbpa4/spack-src/build' 'lib'

8 errors found in build log:   
     9831    a - elf/dl-sym.os 
     9832    a - elf/libc-dl_find_object.os
     9833    a - elf/libc_early_init.os
     9834    /p/vast1/username/spack-env/spack/lib/spack/env/gcc/gcc   -nostdlib -nostartfiles -r -o /tmp/username/spack-stage/spack-stage-glibc-2.38-7cn4wmb425
             j6mkh5atnt3uodic3sbpa4/spack-src/build/libc_pic.os \
     9835     -Wl,--whole-archive /tmp/username/spack-stage/spack-stage-glibc-2.38-7cn4wmb425j6mkh5atnt3uodic3sbpa4/spack-src/build/libc_pic.a -o /tmp/username/
             spack-stage/spack-stage-glibc-2.38-7cn4wmb425j6mkh5atnt3uodic3sbpa4/spack-src/build/libc_pic.os
     9836    /usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/ppc64le-redhat-linux/10/ld: /tmp/username/spack-stage/spack-stage-glibc-2.38-7cn4wmb425
             j6mkh5atnt3uodic3sbpa4/spack-src/build/libc_pic.a(s_modff128.os): in function `__modff128_power9':
  >> 9837    /tmp/username/spack-stage/spack-stage-glibc-2.38-7cn4wmb425j6mkh5atnt3uodic3sbpa4/spack-src/math/../sysdeps/ieee754/float128/../ldbl-128/s_modfl.c
             :36: multiple definition of `__modff128_power9'; /tmp/username/spack-stage/spack-stage-glibc-2.38-7cn4wmb425j6mkh5atnt3uodic3sbpa4/spack-src/build
             /libc_pic.a(s_modff128-power9.os):/tmp/username/spack-stage/spack-stage-glibc-2.38-7cn4wmb425j6mkh5atnt3uodic3sbpa4/spack-src/math/../sysdeps/ieee
             754/float128/../ldbl-128/s_modfl.c:36: first defined here
     9838    /usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/ppc64le-redhat-linux/10/ld: /tmp/username/spack-stage/spack-stage-glibc-2.38-7cn4wmb425
             j6mkh5atnt3uodic3sbpa4/spack-src/build/libc_pic.a(s_scalbnf128.os): in function `__scalbnf128_power9':
  >> 9839    /tmp/username/spack-stage/spack-stage-glibc-2.38-7cn4wmb425j6mkh5atnt3uodic3sbpa4/spack-src/math/../sysdeps/ieee754/float128/../ldbl-128/s_scalbnl
             .c:37: multiple definition of `__scalbnf128_power9'; /tmp/username/spack-stage/spack-stage-glibc-2.38-7cn4wmb425j6mkh5atnt3uodic3sbpa4/spack-src/b
             uild/libc_pic.a(s_scalbnf128-power9.os):/tmp/username/spack-stage/spack-stage-glibc-2.38-7cn4wmb425j6mkh5atnt3uodic3sbpa4/spack-src/math/../sysdep
             s/ieee754/float128/../ldbl-128/s_scalbnl.c:37: first defined here
     9840    /usr/tce/packages/gcc/gcc-10.2.1/rh/usr/bin/../libexec/gcc/ppc64le-redhat-linux/10/ld: /tmp/username/spack-stage/spack-stage-glibc-2.38-7cn4wmb425
             j6mkh5atnt3uodic3sbpa4/spack-src/build/libc_pic.a(s_frexpf128.os): in function `__frexpf128_power9':
  >> 9841    /tmp/username/spack-stage/spack-stage-glibc-2.38-7cn4wmb425j6mkh5atnt3uodic3sbpa4/spack-src/math/../sysdeps/ieee754/float128/../ldbl-128/s_frexpl.
             c:37: multiple definition of `__frexpf128_power9'; /tmp/username/spack-stage/spack-stage-glibc-2.38-7cn4wmb425j6mkh5atnt3uodic3sbpa4/spack-src/bui
             ld/libc_pic.a(s_frexpf128-power9.os):/tmp/username/spack-stage/spack-stage-glibc-2.38-7cn4wmb425j6mkh5atnt3uodic3sbpa4/spack-src/math/../sysdeps/i
             eee754/float128/../ldbl-128/s_frexpl.c:37: first defined here
</pre>
</details>

### Information on your system

* **Spack:** 0.22.0.dev0 (96f3c76052139ee420c7a2c758ef1ee3681928c4)
* **Python:** 3.7.2
* **Platform:** linux-rhel7-power9le
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/13342667/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/13342668/spack-build-out.txt)

Maintainer of Glibc: @haampie

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
I don't have access to power machines, so am unlikely to debug this. Did you google it? Usually patches are available.

**Comment by ipcamit** [comment]
Yes, I tried, but couldn't find anything actionable. Will try again once more, otherwise write to the HPC support. Can you venture a guess, as to what might be wrong? It would be beneficial for me to have some clue as to what can be wrong.

**Comment by yizeyi18** [comment]
Is this a gcc bug, instead of a spack bug? Seems the "first defined here" is the same as where error rises. Is the CC used here OEM installed? Can you try compile it with a different compiler?

**Comment by ipcamit** [comment]
Sorry I so not have the bandwidth to provide additional information at this moment. Plus the PowerPC HPC I was trying it is going away soon. So not sure if I could be of help. One can try replicating it in a virtual machine but it is too much of a task. I guess I can close this issue for now. :(
