### ISSUE TITLE
latest tag not updated on release of new version

### ISSUE THREAD

**Issue by fgava90** [LLNL/spack#41097]
Hello again,

Tagging @tgamblin this time as he made the v0.21.0 release.

releases/latest is still pointing to v0.20.1
Could you kindly update it to point to v0.21.0?

Perhaps you should automate this task as i see it is regularly forgotten?

_Originally posted by @fgava90 in https://github.com/spack/spack/issues/39125#issuecomment-1813256898_

**Comment by haampie** [comment]
I wouldn't mind dropping this tag altogether, cause `git fetch --tags` can error and may break people's scripts

**Comment by fgava90** [comment]
I find it very useful because i have a script that regularly pulls releases/latest and if the spack version is newer than the one on the system it updates it.
I might find another way if you want to drop it, just let me know :)

**Comment by haampie** [comment]
Ok, let's just stick to it

**Comment by fgava90** [comment]
Thanks! :)

**Comment by alalazo** [comment]
Just fixed:
![Screenshot from 2023-11-21 07-16-48](https://github.com/spack/spack/assets/4199709/bb90d594-5fa9-423e-bce7-1e31bb21a07c)

**Comment by tgamblin** [comment]
@alalazo is it possible to automate this one in an action?
