### ISSUE TITLE
with_or_without / enable_or_disable

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#4112]
@alalazo I was hoping to try out the new `with_or_without` and `enable_or_disable` functionality that you added to `AutotoolsPackage` but I'm afraid it doesn't work the way I would expect. I have a package with several optional dependencies that can be specified via configure like so:
```
$ ./configure --with-zlib --without-libpsl --enable-pcre
```
Normally I would have to add the following to `configure_args`:
```python
args = []

if '+zlib' in self.spec:
    args.append('--with-zlib')
else:
    args.append('--without-zlib')

if '+libpsl' in self.spec:
    args.append('--with-libpsl')
else:
    args.append('--without-libpsl')

if '+pcre' in self.spec:
    args.append('--enable-pcre')
else:
    args.append('--disable-pcre')

return args
```
but I was hoping these functions would let me do:
```python
return [
    self.with_or_without('zlib'),                                       
    self.with_or_without('libpsl'),                                     
    self.enable_or_disable('pcre'),
]
```
instead. But I get the error message:
```
==> Error: TypeError: expected string or buffer
```
Do these functions only support multi-valued variants? Can we get this use case working as well? I'm pretty sure it's much more common.

**Comment by alalazo** [comment]
Right now the function says:
```python
def with_or_without(self, name, active_parameters=None):
    """Inspects the **multi-valued variant** 'name' and returns the configure
    arguments that activate / deactivate the selected feature.

    :param str name: name of a valid multi-valued variant
    :param callable active_parameters: if present accepts a single value
        and returns the parameter to be used leading to an entry of the
        type '--with-{name}={parameter}
    """
    ....       
```
but I think extending it to bool valued variant is a really good idea. I'll get to it in the next few days.

**Comment by alalazo** [comment]
I think I'll have time to work on this next week, so I am trying to figure out the API. What do you think of the possibility of handling lists? Something like:
```
self.with_or_without(['zlib', 'libpsl'])
```
Also, can somebody point at a few packages that may use the feature? Better if of different complexity, so that I can give a preliminary idea how it would look in different cases directly in the PR.

**Comment by adamjstewart** [comment]
I think it's fine to only handle single elements at a time. One other use case that we should handle is that sometimes the variant isn't named the same as the flag. For example, the variant and dependency could be called `libpng` while the flag is called `png`. So the ability to pass in an optional parameter to rename the flag would be useful.

**Comment by alalazo** [comment]
I know that *it is not documented yet* :tm: but with multi valued variants you can already do something like:
```python
def with_or_without_libpng(self, activated):
    ...
```
and implement business logic there. There's an example in `openmpi` for verbs:
```python
def with_or_without_verbs(self, activated):
    # Up through version 1.6, this option was previously named
    # --with-openib
    opt = 'openib'
    # In version 1.7, it was renamed to be --with-verbs
    if self.spec.satisfies('@1.7:'):
        opt = 'verbs'
    # If the option has not been activated return
    # --without-openib or --without-verbs
    if not activated:
        return '--without-{0}'.format(opt)
    line = '--with-{0}'.format(opt)
    path = _verbs_dir()
    if (path is not None) and (path not in ('/usr', '/usr/local')):
        line += '={0}'.format(path)
    return line
```
Would something like that be sufficient?
