### ISSUE TITLE
Uber package results in many echos of package.py file path

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/spack#4114]
I am developing an _uber_ package that represents the suite of meshing and numerical libraries in the FASTMath SciDAC project. It has ~20 sub-package dependencies.

Fine and good.

But, whenever I go to build that uber package, I get a couple of screenfulls of echos...

/Users/miller86/spack/spack/var/spack/repos/builtin/packages/fastmath/package.pyc
/Users/miller86/spack/spack/var/spack/repos/builtin/packages/fastmath/package.pyc
/Users/miller86/spack/spack/var/spack/repos/builtin/packages/fastmath/package.pyc
/Users/miller86/spack/spack/var/spack/repos/builtin/packages/fastmath/package.pyc
/Users/miller86/spack/spack/var/spack/repos/builtin/packages/fastmath/package.pyc
/Users/miller86/spack/spack/var/spack/repos/builtin/packages/fastmath/package.pyc
/Users/miller86/spack/spack/var/spack/repos/builtin/packages/fastmath/package.pyc
/Users/miller86/spack/spack/var/spack/repos/builtin/packages/fastmath/package.pyc
/Users/miller86/spack/spack/var/spack/repos/builtin/packages/fastmath/package.pyc
/Users/miller86/spack/spack/var/spack/repos/builtin/packages/fastmath/package.pyc
/Users/miller86/spack/spack/var/spack/repos/builtin/packages/fastmath/package.pyc
/Users/miller86/spack/spack/var/spack/repos/builtin/packages/fastmath/package.pyc
/Users/miller86/spack/spack/var/spack/repos/builtin/packages/fastmath/package.pyc

Same thing happens if I do the command `spack graph fastmath`. It spews a ton of these lines before it prints the graph.

**Comment by adamjstewart** [comment]
Can we see the source code for your `fastmath` package? Or do you know of a package already in Spack that also displays this behavior?

**Comment by adamjstewart** [comment]
P.S. We've seen other problems with `spack graph` before. See #1098 for an example. I suspect your problem is similar, although it has a different error message this time.

**Comment by markcmiller86** [comment]
Here it is...

https://github.com/markcmiller86/spack/blob/develop/var/spack/repos/builtin/packages/fastmath/package.py

**Comment by markcmiller86** [comment]
Ok, well, Doh!. Its that print __file__ in url_for_version.

Sorry for false alarm.

**Comment by adamjstewart** [comment]
By the way:

> ```python
> from os.path import join as pjoin
> ```

Spack already has a `join_path` function (it's just an alias to `os.path.join`) that you can use. It gets imported automatically with `from spack import *`.
