### ISSUE TITLE
Concretized specs are different when variants are specified in packages.yaml or from command line

### ISSUE THREAD

**Issue by fgava90** [LLNL/spack#41172]
### Steps to reproduce

```console
$ head -n $spack/etc/spack/packages.yaml
   packages:
       mysql:
          variants: cxxstd=17

$ spack spec mysql
Input spec
--------------------------------
 -   mysql

Concretized
--------------------------------
 -   mysql@8.0.29%gcc@13.2.0~client_only~ipo build_system=cmake build_type=Release cxxstd=98 generator=make arch=linux-rocky8-x86_64

$ spack spec mysql cxxstd=17
Input spec
--------------------------------
 -   mysql cxxstd=17

Concretized
--------------------------------
 -   mysql@8.0.29%gcc@13.2.0+client_only~ipo build_system=cmake build_type=Release cxxstd=17 generator=make arch=linux-rocky8-x86_64

$ head -n $spack/etc/spack/packages.yaml
   packages:
       mysql:
          variants: ~client_only cxxstd=17

$ spack spec mysql
Input spec
--------------------------------
 -   mysql

Concretized
--------------------------------
 -   mysql@8.0.29%gcc@13.2.0~client_only~ipo build_system=cmake build_type=Release cxxstd=98 generator=make arch=linux-rocky8-x86_64
 
$ spack spec mysql ~client_only cxxstd=17
Input spec
--------------------------------
 -   mysql~client_only cxxstd=17

Concretized
--------------------------------
 -   mysql@5.6.44%gcc@13.2.0~client_only~ipo build_system=cmake build_type=Release cxxstd=17 generator=make arch=linux-rocky8-x86_64
```

### Error message

The package specs result in a different concretization if I enforce cxxstd=17 from command line.
On the first case (cxxstd=17 imposed by packages.yaml) the constraint is ignored and it uses cxxstd=98
In the second case (cxxstd=17 imopsed by command line) the constraint is taken into account and it changes +client_only.
Enforcing `~client_only cxxstd=17` from command line results in a change of version, while from packages.yaml the version remains the latest and cxxstd is ignored.
In this case `~client_only` (default) and `cxxstd=17` are conflicting specs for `@8.0.0:` but i would expect the same concretization or at least an error/warning message.

mysql is just a simple example, it behaves the same with other packages.

### Information on your system

* **Spack:** 0.21.0 (65d3221a9c436e77af9e802e543c71bd702ff4e2)
* **Python:** 3.6.8
* **Platform:** linux-rocky8-x86_64
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Despite not being intuitive, this behaves "as designed" given the dependencies of `mysql`. We have a [FAQ](https://spack.readthedocs.io/en/latest/frequently_asked_questions.html#why-does-spack-pick-particular-versions-and-variants) added recently that explains the mechanics and how it could lead to unexpected behavior. Key points are that:
1. Soft preferences (used here) need not to be enforced by the concretizer, but can be circumvented if a "better" solution is found
2. User can employ `require` to enforce a constraint

In your use case:
```yaml
packages:
  mysql:
    require: cxxstd=17
```
should do it.

**Comment by alalazo** [comment]
Closing, but let me know if everything is clear, or if some specific behavior needs more explanation / another look.

**Comment by fgava90** [comment]
Thanks, i had missed the FAQ there. Very useful.

I guess i just find it confusing that specs are ignored without warning/error.

For example in my packages.py I ask for `+tkinter` for python, which should fail because of the bug in #41146 , (and it does if i ask for +tkinter from command line) wheareas if i just concretize python it ignores it and sets `~tkinter` .

I have a quite complicated CI pipeline creating environments that need to be absolutely "repeatable", so this change in behaviour is somewhat strange between v0.20 and v0.21, because it results in different environments starting from the same yaml files and spack configuration. 
Furthermore the changes are "invisible" to me because once i verified the environments being correct once i trust spack to reproduce them exacly every time i launch my pipeline (otherwise what's the point in automanting if i have to manually check the results every time?), and in this case i have been caught by this change in behaviour. I found out only because some specs actually failed to build.

I will start using `requires` instead of `variants` to guarantee that they are picked up correctly.

**Comment by alalazo** [comment]
> Thanks, i had missed the FAQ there. Very useful.

No worries, we added that just a couple of days ago.

**Comment by alalazo** [comment]
> Furthermore the changes are "invisible" to me because once i verified the environments being correct once i trust spack to reproduce them exacly every time i launch my pipeline 

Changes should be reproducible if you use the exact same version of Spack to reconcretize, otherwise anything added or removed from recipes may alter the result of concretization (meaning, the "optimal" solution might be different).

**Comment by fgava90** [comment]
Ok. 
In this case I have updated spack from v0.20 to v0.21 but kept the same exact configuration.

**Comment by fgava90** [comment]
> Closing, but let me know if everything is clear, or if some specific behavior needs more explanation / another look.

Hello, 

I'm sorry but i'm still a bit confused by all this.
In my `packages.yaml` i have:
```yaml
python:
  version: [3.8.7]
```
If i do `spack spec python` it concretizes correctly to version `3.8.7`.
However if i do `spack spec py-numpy` it concretizes with `python@3.11.6` 

In the FAQ you pointed out above it states:
`As a rule of thumb: requirements + constraints > reuse > preferences > defaults.`

In this case I believe there are no `requirements + constraints` and `reuse` is set to `false` in `concretizer.yaml` so `preferences` should be the one to be picked up, and consequently it should concretize with `python@3.8.7`. Am i right?
If this is not the case, i can't see the point in setting `version` and `variants` in `packages.yaml` (instead of using `require` all the time) as they seem to be blatantly ignored except for root specs.

**Comment by alalazo** [comment]
The requirements in this case come from the `py-numpy` package recipe:

https://github.com/spack/spack/blob/de64ce5541eb4055a26e6ba5d82c37e5797612c0/var/spack/repos/builtin/packages/py-numpy/package.py#L90

And from the fact the concretizer privileges the root over the dependencies. If you want to get a sense of what is really happening, you can check the optimization weights reported by `spack solve`. 

The bottomline for this specific case is:
 - The concretizer privileges root over dependencies
 - `py-numpy` preferred version is 1.26.2
 - That version imposes a requirement on the Python version

**Comment by fgava90** [comment]
Thank you and many apologies, I didn't notice the drop in version of py-numpy when i forced python@3.8.7.
And thank you for suggesting the use of spack solve, i'll use it to understand other suspicious stuff i'm getting :)

**Comment by alalazo** [comment]
No worries, glad it clarified the situation.
