### ISSUE TITLE
sycl: improve support for (compiler) runtime library 

### ISSUE THREAD

**Issue by mabraham** [LLNL/spack#41196]
### Summary

Is it possible, meaningful, and/or desirable for a Spack compiler to implement a Spack virtual package dependency?

### Rationale

#41171 proposed adding support to GROMACS for satisfying `+sycl` either via `^sycl` or via `%oneapi`. The question arose whether this was a good way to do things. If it is, then it would be desirable to modify the Spack core so that oneapi compiler was known to implement `^sycl` and avoid the kind of package-specific logic proposed there being repeated in other packages.

Currently we don't see much adoption of `^sycl` in Spack, but that could change in future.

### Description

These are not exclusive solutions!

1. (preferred) That a Spack compiler can declare that it `provides("sycl")`
2. That packages implement their own support for multiple SYCL providers with `+sycl` by code like `requires("%oneapi", "^sycl", policy="one_of", when="+sycl")`
3. That we make a new package that requires `%oneapi`, and `provides("sycl")`
4. That we extend the existing `intel-oneapi-compilers` package to `provides("sycl")`

Note that the oneAPI C++ compiler supports a range of use cases, including:

* compiling the whole project, using `-fsycl` on all or part of the translation units to do what is needed for host and device code
* compiling only the SYCL translation units as above
* compiling only the device passes for those translation units as above

and in the latter two cases it would be useful to have options 3 or 4 to allow Spack to support something like `some-package %gcc +sycl ^intel-oneapi-compilers`. However it does not seem desirable to *force* packages that want to use `+sycl` to support multiple SYCL implementations to have to have specs like `some-package %oneapi +sycl ^intel-oneapi-compilers` because that is

* more complex for downstream package writers than `some-package %oneapi +sycl`,
* potentially a mismatch because `%oneapi` can be provided by an external compiler, and
* when a mismatch is avoided, it's because the user also had to provide `intel-oneapi-compilers` as an external package, which is clumsy.

So I think *requiring* 4 is a bad idea (as well as causing churn for existing Spack packages).

### Additional information

SYCL support for building a package can in principle be done in a variety of ways. Almost all packages currently in Spack that have `+sycl` variants require or satisfy that by `%oneapi` to use Intel's oneAPI C++ compiler. That is merely the simplest way of doing things with a commonly used SYCL provider, and not at all prescriptive.

In #14051, a virtual package for `sycl` was added along with an implementation package AdaptiveCpp (then called hipSYCL). This provides access to a wrapper compiler that a Spack package that `requires("sycl")` can use in its build system. Both the GROMACS and BabelStream Spack packages do this. The latter also supports the "simple" approach for providing SYCL via the oneAPI compiler.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
Have you seen #41104? It's pretty similar to point 3:

`gcc-runtime` is a package that contains copies of the compiler support libraries and has a 1-1 correspondence with `%gcc`.

Something like that could also be done for compiler support libraries of intel compilers.

**Comment by mabraham** [comment]
> Have you seen #41104? It's pretty similar to point 3:
> 
> `gcc-runtime` is a package that contains copies of the compiler support libraries and has a 1-1 correspondence with `%gcc`.
> 
> Something like that could also be done for compiler support libraries of intel compilers.

Thanks for the suggestion! That's indeed a good model for the kind of project that is unwilling/unable/not ready to switch from gcc/msvc to icpx, yet wants to have key translation units leverage SYCL. But we don't have any such examples in Spack (obviously), I don't know of any, and it is a bad idea to implement that until we have a candidate first use case.

What I'm most looking for is that the simple case of a spec like `some_package %oneapi +sycl` Just Works, because spack understands that `%oneapi` provides SYCL.

Currently that produces a spec that requires AdaptiveCpp (because of `etc/spack/defaults/packages.yaml`), which is almost certainly not what the user wanted. `some_package %oneapi +sycl ^intel-oneapi-sycl-runtime` would work, but is rather verbose. Is there a way to set up the defaults so that the `some_package %oneapi +sycl` would default to `some_package %oneapi +sycl ^intel-oneapi-sycl-runtime`? Or should we have no packages provide SYCL by default in `etc/spack/defaults/packages.yaml`?

**Comment by haampie** [comment]
I think a package `oneapi-runtime` that `provides("sycl", when="+sycl")` and `requires("%oneapi")` and is a default dependency of any package `when="%oneapi"`, together with a default provider list `sycl: [oneapi-runtime +sycl, ...]` should be enough to make `pkg %oneapi` pick `sycl` from the compiler, while people who don't have the oneapi compiler registered will get the current default.

**Comment by mabraham** [comment]
Thanks, I didn't know about default dependencies!

**Comment by alalazo** [comment]
I'll check if we can implement `sycl` support in #42062 or in a follow up PR

**Comment by alalazo** [comment]
`intel-oneapi-runtime` provides `sycl`, so I would say this was fixed by #42062

**Comment by mabraham** [comment]
> `intel-oneapi-runtime` provides `sycl`, so I would say this was fixed by #42062

Seems to work, so https://github.com/spack/spack/pull/47806 is up
