### ISSUE TITLE
Installation issue: GSL on macos

### ISSUE THREAD

**Issue by Chrismarsh** [LLNL/spack#41221]
### Steps to reproduce the issue
```
spack install --add gsl
```

```console
$ spack spec -l gsl
Input spec
--------------------------------
 -   gsl

Concretized
--------------------------------
 -   goo6u4s  gsl@2.7.1%gcc@12.2.0~external-cblas+pic+shared build_system=autotools arch=darwin-ventura-m1
 -   privsw4      ^gmake@4.4.1%gcc@12.2.0~guile build_system=generic arch=darwin-ventura-m1
 -   d5uvb4j      ^gnuconfig@2022-09-17%gcc@12.2.0 build_system=generic arch=darwin-ventura-m1
```

### Error message

<details><summary>Error message</summary>

<pre>
==> Installing gsl-2.7.1-kexghf6wg2qlub47d6e2aqqixax37eoe [22/89]
==> No binary for gsl-2.7.1-kexghf6wg2qlub47d6e2aqqixax37eoe found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/dc/dcb0fbd43048832b757ff9942691a8dd70026d5da0ff85601e52687f6deeb34b.tar.gz
==> No patches needed for gsl
==> gsl: Executing phase: 'autoreconf'
==> gsl: Executing phase: 'configure'
==> gsl: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j10' 'V=1'

5 errors found in build log:
     3978    mv -f .deps/gsl-randist.Tpo .deps/gsl-randist.Po
     3979    libtool: compile:  /Users/cmarsh/Documents/science/code/spack/lib/spack/env/clang/clang -DHAVE_CONFIG_H -I. -I/var/folders/tr/v_kqwm7x25x3y68l_p5qh1gw0000gn/T/cma
             rsh/spack-stage/spack-stage-gsl-2.7.1-kexghf6wg2qlub47d6e2aqqixax37eoe/spack-src -g -O2 -MT version.lo -MD -MP -MF .deps/version.Tpo -c version.c  -fno-common -DP
             IC -o .libs/version.o
     3980    libtool: compile:  /Users/cmarsh/Documents/science/code/spack/lib/spack/env/clang/clang -DHAVE_CONFIG_H -I. -I/var/folders/tr/v_kqwm7x25x3y68l_p5qh1gw0000gn/T/cma
             rsh/spack-stage/spack-stage-gsl-2.7.1-kexghf6wg2qlub47d6e2aqqixax37eoe/spack-src -g -O2 -MT version.lo -MD -MP -MF .deps/version.Tpo -c version.c  -fno-common -DP
             IC -o version.o >/dev/null 2>&1
     3981    mv -f .deps/version.Tpo .deps/version.Plo
     3982    /bin/sh ./libtool  --tag=CC   --mode=link /Users/cmarsh/Documents/science/code/spack/lib/spack/env/clang/clang  -g -O2  -version-info 27:0:0  -o libgsl.la -rpath
             /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/gsl-2.7.1-kexghf6wg2qlub47d6e2aqqixax37eoe/lib version.lo  block/libgslb
             lock.la blas/libgslblas.la bspline/libgslbspline.la bst/libgslbst.la complex/libgslcomplex.la cheb/libgslcheb.la dht/libgsldht.la diff/libgsldiff.la deriv/libgsld
             eriv.la eigen/libgsleigen.la err/libgslerr.la fft/libgslfft.la filter/libgslfilter.la fit/libgslfit.la histogram/libgslhistogram.la ieee-utils/libgslieeeutils.la
             integration/libgslintegration.la interpolation/libgslinterpolation.la linalg/libgsllinalg.la matrix/libgslmatrix.la min/libgslmin.la monte/libgslmonte.la multifit
             /libgslmultifit.la multifit_nlinear/libgslmultifit_nlinear.la multilarge/libgslmultilarge.la multilarge_nlinear/libgslmultilarge_nlinear.la multimin/libgslmultimi
             n.la multiroots/libgslmultiroots.la ntuple/libgslntuple.la ode-initval/libgslodeiv.la ode-initval2/libgslodeiv2.la permutation/libgslpermutation.la combination/li
             bgslcombination.la multiset/libgslmultiset.la poly/libgslpoly.la qrng/libgslqrng.la randist/libgslrandist.la rng/libgslrng.la roots/libgslroots.la siman/libgslsim
             an.la sort/libgslsort.la specfunc/libgslspecfunc.la movstat/libgslmovstat.la rstat/libgslrstat.la statistics/libgslstatistics.la sum/libgslsum.la sys/libgslsys.la
              test/libgsltest.la utils/libutils.la vector/libgslvector.la cdf/libgslcdf.la wavelet/libgslwavelet.la spmatrix/libgslspmatrix.la spblas/libgslspblas.la splinalg/
             libgslsplinalg.la -lm
     3983    libtool: link: /Users/cmarsh/Documents/science/code/spack/lib/spack/env/clang/clang -dynamiclib  -o .libs/libgsl.27.dylib  .libs/version.o   -Wl,-force_load,block
             /.libs/libgslblock.a -Wl,-force_load,blas/.libs/libgslblas.a -Wl,-force_load,bspline/.libs/libgslbspline.a -Wl,-force_load,bst/.libs/libgslbst.a -Wl,-force_load,c
             omplex/.libs/libgslcomplex.a -Wl,-force_load,cheb/.libs/libgslcheb.a -Wl,-force_load,dht/.libs/libgsldht.a -Wl,-force_load,diff/.libs/libgsldiff.a -Wl,-force_load
             ,deriv/.libs/libgslderiv.a -Wl,-force_load,eigen/.libs/libgsleigen.a -Wl,-force_load,err/.libs/libgslerr.a -Wl,-force_load,fft/.libs/libgslfft.a -Wl,-force_load,f
             ilter/.libs/libgslfilter.a -Wl,-force_load,fit/.libs/libgslfit.a -Wl,-force_load,histogram/.libs/libgslhistogram.a -Wl,-force_load,ieee-utils/.libs/libgslieeeutil
             s.a -Wl,-force_load,integration/.libs/libgslintegration.a -Wl,-force_load,interpolation/.libs/libgslinterpolation.a -Wl,-force_load,linalg/.libs/libgsllinalg.a -W
             l,-force_load,matrix/.libs/libgslmatrix.a -Wl,-force_load,min/.libs/libgslmin.a -Wl,-force_load,monte/.libs/libgslmonte.a -Wl,-force_load,multifit/.libs/libgslmul
             tifit.a -Wl,-force_load,multifit_nlinear/.libs/libgslmultifit_nlinear.a -Wl,-force_load,multilarge/.libs/libgslmultilarge.a -Wl,-force_load,multilarge_nlinear/.li
             bs/libgslmultilarge_nlinear.a -Wl,-force_load,multimin/.libs/libgslmultimin.a -Wl,-force_load,multiroots/.libs/libgslmultiroots.a -Wl,-force_load,ntuple/.libs/lib
             gslntuple.a -Wl,-force_load,ode-initval/.libs/libgslodeiv.a -Wl,-force_load,ode-initval2/.libs/libgslodeiv2.a -Wl,-force_load,permutation/.libs/libgslpermutation.
             a -Wl,-force_load,combination/.libs/libgslcombination.a -Wl,-force_load,multiset/.libs/libgslmultiset.a -Wl,-force_load,poly/.libs/libgslpoly.a -Wl,-force_load,qr
             ng/.libs/libgslqrng.a -Wl,-force_load,randist/.libs/libgslrandist.a -Wl,-force_load,rng/.libs/libgslrng.a -Wl,-force_load,roots/.libs/libgslroots.a -Wl,-force_loa
             d,siman/.libs/libgslsiman.a -Wl,-force_load,sort/.libs/libgslsort.a -Wl,-force_load,specfunc/.libs/libgslspecfunc.a -Wl,-force_load,movstat/.libs/libgslmovstat.a
             -Wl,-force_load,rstat/.libs/libgslrstat.a -Wl,-force_load,statistics/.libs/libgslstatistics.a -Wl,-force_load,sum/.libs/libgslsum.a -Wl,-force_load,sys/.libs/libg
             slsys.a -Wl,-force_load,test/.libs/libgsltest.a -Wl,-force_load,utils/.libs/libutils.a -Wl,-force_load,vector/.libs/libgslvector.a -Wl,-force_load,cdf/.libs/libgs
             lcdf.a -Wl,-force_load,wavelet/.libs/libgslwavelet.a -Wl,-force_load,spmatrix/.libs/libgslspmatrix.a -Wl,-force_load,spblas/.libs/libgslspblas.a -Wl,-force_load,s
             plinalg/.libs/libgslsplinalg.a  -lm  -g -O2   -install_name  /Users/cmarsh/Documents/science/code/spack/opt/spack/darwin-ventura-m1/apple-clang-14.0.3/gsl-2.7.1-k
             exghf6wg2qlub47d6e2aqqixax37eoe/lib/libgsl.27.dylib -compatibility_version 28 -current_version 28.0 -Wl,-single_module
  >> 3984    Undefined symbols for architecture arm64:
     3985      "_cblas_caxpy", referenced from:
     3986          _gsl_blas_caxpy in libgslblas.a(blas.o)
     3987      "_cblas_ccopy", referenced from:
     3988          _gsl_blas_ccopy in libgslblas.a(blas.o)
     3989      "_cblas_cdotc_sub", referenced from:
     3990          _gsl_blas_cdotc in libgslblas.a(blas.o)

     ...

     4198          _gsl_blas_ztrmv in libgslblas.a(blas.o)
     4199      "_cblas_ztrsm", referenced from:
     4200          _gsl_blas_ztrsm in libgslblas.a(blas.o)
     4201      "_cblas_ztrsv", referenced from:
     4202          _gsl_blas_ztrsv in libgslblas.a(blas.o)
     4203    ld: symbol(s) not found for architecture arm64
  >> 4204    clang: error: linker command failed with exit code 1 (use -v to see invocation)
  >> 4205    make[2]: *** [Makefile:826: libgsl.la] Error 1
     4206    make[2]: Leaving directory '/private/var/folders/tr/v_kqwm7x25x3y68l_p5qh1gw0000gn/T/cmarsh/spack-stage/spack-stage-gsl-2.7.1-kexghf6wg2qlub47d6e2aqqixax37eoe/spa
             ck-src'
  >> 4207    make[1]: *** [Makefile:987: all-recursive] Error 1
     4208    make[1]: Leaving directory '/private/var/folders/tr/v_kqwm7x25x3y68l_p5qh1gw0000gn/T/cmarsh/spack-stage/spack-stage-gsl-2.7.1-kexghf6wg2qlub47d6e2aqqixax37eoe/spa
             ck-src'
  >> 4209    make: *** [Makefile:684: all] Error 2
</pre></details>

### Information on your system

```
spack debug report
* **Spack:** 0.22.0.dev0 (432f5d64e369f8b63cab9ce65ea2e9b9ee5c386d)
* **Python:** 3.10.4
* **Platform:** darwin-ventura-m1
* **Concretizer:** clingo
```

### Additional information

Same error as #28014 but I don't actually think it's related. Installing `gsl +external-cblas` works. So I think the problem is how the default variant is handled, although as I'm new to spack the problem is not immediately obvious to me.

[spack-build-env.txt](https://github.com/spack/spack/files/13444190/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/13444191/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by climbfuji** [comment]
This is a copy of the slack discussion @chrismarsh and @climbfuji had regarding this issue:

Dom Heinzeller
 I am seeing the same problem on both arm64 and x86_64 mac. I’ve tracked this down (from comparing before updating our spack fork from develop and after) to the following command line arguments missing in the latest spack develop code when creating the libgslcblas.0.dylib:
-Wl,-undefined -Wl,dynamic_lookup
and sure enough, these are the same variables that are mentioned in 28014. Thus something in the latest spack develop code must have undone the fix from 28014, because our working fork was last updated from spack develop about three months ago.

Chris Marsh
Because as I work through getting an env stood up, vtk is failing to compile with a similar error -- it's not linking against libogg correctly
2851    Undefined symbols for architecture arm64:
     2852      "_ogg_stream_clear", referenced from:
     2853          vtkOggTheoraWriterInternal::End() in vtkOggTheoraWriter.cxx.o
     2854      "_ogg_stream_flush", referenced from:
     2855          vtkOggTheoraWriterInternal::WriteHeader() in vtkOggTheoraWriter.cxx.o
     2856      "_ogg_stream_init", referenced from:
     2857          vtkOggTheoraWriterInternal::Start() in vtkOggTheoraWriter.cxx.o

Chris Marsh
Where did you track down that -Wl,-undefined -Wl,dynamic_lookup was missing?

Dom Heinzeller
I compared my gsl build log from a previous working version to the new version

Chris Marsh
what was the previous version of spack?

Dom Heinzeller
hash 64c6d63675f8e45e0be12a9c55acb4b7969e383a from July 10

Dom Heinzeller
This is in gsl’s top-level configure file:
      case ${MACOSX_DEPLOYMENT_TARGET-10.0},$host in
        10.0,*86*-darwin8*|10.0,*-darwin[91]*)
          _lt_dar_allow_undefined='$wl-undefined ${wl}dynamic_lookup' ;;
        10.[012][,.]*)
          _lt_dar_allow_undefined='$wl-flat_namespace $wl-undefined ${wl}suppress' ;;
        10.*)
          _lt_dar_allow_undefined='$wl-undefined ${wl}dynamic_lookup' ;;
      esac

Dom Heinzeller
spack build-env gsl …:
OLD spack (works):
MACOSX_DEPLOYMENT_TARGET="10.16"
NEW spack (does not work)
MACOSX_DEPLOYMENT_TARGET="12.0"
@adamjstewart
 FYI we seem to be running into problems with GSL (and other ?) packages because the MACOSX_DEPLOYMENT_TARGET value changed between July 10 (hash 64c6d63675f8e45e0be12a9c55acb4b7969e383a) and today, and because of that gsl doesn’t set the necessary linker flags -Wl,-undefined -Wl,dynamic_lookup anymore. Do you recall what changed and why? (edited) 


Dom Heinzeller
I think I know what changed, the order of execution of things. For the July 10 2023 spack dev code, setup_platform_environment in spack/lib/spack/spack/platforms/darwin.py gets executed BEFORE setup_build_environment in lib/spack/spack/build_systems/autotools.py . The former sets it to 12.0, the latter hardcodes it to 10.16 for anything that’s >=11. In the CURRENT spack develop, the order is reversed. The autotools logic comes first, setting it to 10.16, but then the darwin.py logic comes in and resets it to 12.0. I’ll capture this conversation and add it to the github issue.

**Comment by climbfuji** [comment]
@AlexanderRichert-NOAA FYI this (https://github.com/spack/spack/issues/41221#issuecomment-1823540941) is why the gsl build is failing on macOS. I don't know yet why the order has changed (first autotools.py logic, then darwin.py logic instead of how it used to be).

**Comment by climbfuji** [comment]
And sure enough, @haampie just merged the bug fix that we need it looks like! https://github.com/spack/spack/pull/41205

**Comment by Chrismarsh** [comment]
This appears to have resolved the gsl build issue for me!

**Comment by climbfuji** [comment]
Same here, so let's close this?
