### ISSUE TITLE
LibraryList class does not show in readthedocs

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#4125]
http://spack.readthedocs.io/en/latest/search.html?q=Librarylist&check_keywords=yes&area=default#

**Comment by adamjstewart** [comment]
It's there:
http://spack.readthedocs.io/en/latest/llnl.util.html#llnl.util.filesystem.LibraryList

Not sure why search doesn't work. Sounds like a Read the Docs problem.

**Comment by davydden** [comment]
thanks, indeed. Strange that search did not work...

**Comment by rspavel** [comment]
This still doesn't work and we still can't find the documentation on this feature without googling. Should it really have been closed?

**Comment by davydden** [comment]
> This still doesn't work

that works just fine: http://spack.readthedocs.io/en/latest/llnl.util.html#llnl.util.filesystem.LibraryList

**Comment by rspavel** [comment]
Yes, but you can only find that page by attempting to search the documentation, fail, google "spack librarylist" and finding this issue thread.

**Comment by davydden** [comment]
i don't see what's the proper, you go to Spack doc and type `LibraryList` in the search field:
http://spack.readthedocs.io/en/latest/search.html?q=LibraryList&check_keywords=yes&area=default
<img width="1076" alt="screen shot 2017-10-02 at 22 22 37" src="https://user-images.githubusercontent.com/8023934/31097634-3c3461aa-a7c0-11e7-8d0d-cea4a41e147f.png">

the first link is what you need.

**Comment by davydden** [comment]
I am closing this because `LibraryList` DOES show in the Spack documentation.
