### ISSUE TITLE
intel-xed: Install tree does not match upstream

### ISSUE THREAD

**Issue by blue42u** [LLNL/spack#41268]
### Steps to reproduce

```console
$ spack install intel-xed
```
vs. the [upstream instructions for an "install kit"](https://intelxed.github.io/build-manual/index.html#INSTALL)
```console
$ cd xed/
$ ../xed/mfile.py doc doc-build examples install
$ ../xed/mfile.py --shared doc doc-build examples install
```

### Error message

The headers are installed without a prefix in Spack, but have a `xed/` prefix in the upstream "install kit":
```
linux-ubuntu22.04-zen2/gcc-11.4.0/intel-xed-2023.10.11-77xoqrfxfwgyhmvv4twnsf2sewdzvmef/
├── include
│   ├── xed-address-width-enum.h
│   ├── xed-agen.h
│   ├── xed-attribute-enum.h
│   ├── xed-attributes.h
...
```
```
kits/xed-install-base-2023-11-27-lin-x86-64/
├── include
│   └── xed
│       ├── xed-address-width-enum.h
│       ├── xed-agen.h
│       ├── xed-attribute-enum.h
│       ├── xed-attributes.h
...
```

Most of the example executables are missing from the Spack install:
```
linux-ubuntu22.04-zen2/gcc-11.4.0/intel-xed-2023.10.11-77xoqrfxfwgyhmvv4twnsf2sewdzvmef/
├── bin
│   └── xed
```
```
kits/xed-install-base-2023-11-27-lin-x86-64/
├── bin
│   ├── xed
│   ├── xed-asmparse-main
│   ├── xed-dec-print
│   ├── xed-dll-discovery
│   ├── xed-ex-agen
│   ├── xed-ex-cpuid
│   ├── xed-ex-ild
│   ├── xed-ex-ild2
│   ├── xed-ex1
│   ├── xed-ex3
│   ├── xed-ex4
│   ├── xed-ex5-enc
│   ├── xed-ex6
│   ├── xed-ex7
│   ├── xed-ex8
│   ├── xed-ex9-patch
│   ├── xed-find-special
│   ├── xed-min
│   ├── xed-reps
│   ├── xed-size
│   ├── xed-tables
│   └── xed-tester
```

The textual instruction tables under `misc/`, and the documentation (`examples/` and `doc/`) are also missing:
```
kits/xed-install-base-2023-11-27-lin-x86-64/
├── doc
│   └── ref-manual
│       ├── html
│       │   ├── annotated.html
│       │   ...
├── examples
│   ├── README.txt
│   ...
├── mbuild
│   └── mbuild
│       ├── __init__.py
│       ...
└── misc
    ├── cdata.txt
    └── idata.txt
```

### Information on your system

* **Spack:** 0.22.0.dev0 (df777dbbaaa4887129d0cb2e66bcf6c3ab37ef09)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-zen2
* **Concretizer:** clingo

Maintainer: @mwkrentel

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by mwkrentel** [comment]
Yes, I've been dreading this day for a while.  :-(

Cut me a little slack. :-)  Intel-xed was my first spack PR back in 2018.
IIRC, the directions were sparse and there was no 'make install' target.

Anyway, I agree that we should rework this to make the spack install
agree with the kits.

This will cause some disruption with hpctoolkit over the location of
the include files.  I'll probably need to use some compatibility code
on both sides.  Plus, the docs require doxygen, so I may make that
optional.

I'll take care of this, but there are a few other priorities right now.
So many packages, so many sins.

**Comment by alalazo** [comment]
@blue42u Just changed the label, as we tend to mark as "bug" only issues with core Spack (not with recipes).

**Comment by blue42u** [comment]
Thanks! I didn't feel like the "build error" template clearly fit what I was trying to report (the build didn't *fail* per se), so I waffled and used the generic "bug report" template instead. Which I guess is for Spack core.

Which template do you suggest using in cases like this? Or is it maybe worth a dedicated "package error" template?

**Comment by alalazo** [comment]
@blue42u We can probably improve the existing template with a better description?

**Comment by mwkrentel** [comment]
Not that it really matters now, but I checked the old Intel pre-built XED
kits.  Long ago, in `xed-install-base-2015-09-10-lin-x86-64.zip`,
Intel installed the header files without the `xed` subdirectory and
their examples used includes like:
```
#include "xed-interface.h" 
#include "xed-portability.h"
#include "xed-examples-util.h"
```
At some point, Intel changed and we didn't adapt.
It's not the first or last time for Intel.  :-(

**Comment by blue42u** [comment]
I don't have a link to these pre-built XED kits, but I can say the change to the `xed/` subdirectory happened towards the end of 2016 (https://github.com/intelxed/xed/commit/fcd2d41b2bd8802eed4e620a6836795fbd7ad919), over a year before the first version of `intel-xed` ever added to Spack (https://github.com/spack/spack/commit/154401de769f2da7ab5ff83242a83af653c6110f#diff-3056b089101c62ec21ba8bbb85dbe57067e71ffaa247e9faf8090c6e74a94783R38-R40). The mbuild `install` target has also been available since before the Spack recipe was added.

So I don't really see it as Intel's fault here. IMHO it seems more that the recipe was wrong from the beginning, it never got updated to match the XED install kits of the day, and thus we (`hpctoolkit`) had no impetus to adapt to the upstream install layout. In short, ~6 years of poor software ecosystem practice.
