### ISSUE TITLE
Doesn't arpack-ng superscede parpack

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/spack#4130]
I am pretty sure arpack-ng is the newest packaging of the old arpack/parpack libraries. So, I think it either makes sense to elim parpack package or to make both arpack/parpack and arpack-ng one of those virtual dependencies sort of things. They both implement the same API.

**Comment by davydden** [comment]
i would just keep `arpack-ng` and remove those old unsupported anymore packages.

**Comment by markcmiller86** [comment]
I did see a recent [Spark paper](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=3&ved=0ahUKEwibsL7JwNnTAhXHwVQKHb1hD_sQFgg0MAI&url=https%3A%2F%2Fstanford.edu%2F~rezab%2Fpapers%2Flinalg.pdf&usg=AFQjCNEYHxUI3Gp7UbB2ly-56TM_wAHSKw&sig2=at17KIXUQD61Gfn3__GiUQ) that actually references the _original_ arpack code. I think the reason the authors used the original code was to prove a point...that Spark can leverage 20+ year old code _without_ modification and have it run well on a parallel cluster. But, I think this is exception rather than rule and I think it makes sense to elim parpack and just keep arpack-ng (which includes parpack).

**Comment by markcmiller86** [comment]
But, what about what others might _name_ arpack? As new as arpack-ng is, I don't think many folks using parpack know about arpack-ng. I didn't when I first started using it. I had to be told by a colleague at ANL.

I mention this because someone writing a package that has, for years, dependend are arpack/parpack is going to have to know to write `depends_on('arpack-ng')` and not `depends_on('parpack')`. Is it _ok_ to create an _alias_ for 'arpack-ng' named just 'parpack'?

**Comment by davydden** [comment]
> that Spark can leverage 20+ year old code without modification and have it run well on a parallel cluster

I am pretty sure the could do the same with `arpack-ng`. I don't think it has any major rewriting/new algorithms/etc, so it's not about being developed, but **being maintained**. And that's very important as there are some ugly to find bugs in the original code which lead to segmentation faults in, say, ScaLAPACK. Bottom line is: i don't see any reason not to use `arpack-ng`, especially given that it now uses `Cmake` as build system.

> is going to have to know to write depends_on('arpack-ng') and not depends_on('parpack'). 

Currently
```
$ spack list arpack
==> 3 packages.
arpack  arpack-ng  parpack
```
shows 3 packages, if we remove `arpack` and `parpack`, then package authors will have to use `arpack-ng`. It would also be a hint that the old version shall not be used.

**Comment by markcmiller86** [comment]
I just happened to be looking at the arpack package and I recall it requiring some patches. If you check the package web site, it clearly says...

```
ARPACK
    README file (readme.arpack)
    Installation procedures ( instruction.arpack)
    Compressed tar file of distribution ( arpack96.tar.Z) and patch (patch.tar.Z)
    GNU zipped tar file of distribution ( arpack96.tar.gz) and patch (patch.tar.gz)

P_ARPACK

    README file (readme.parpack)
    Installation procedures ( instruction.parpack)
    Compressed tar file of distribution ( parpack96.tar.Z) and patch (ppatch.tar.Z)
    GNU zipped tar file of distribution ( parpack96.tar.gz) and patch (ppatch.tar.gz)
```

In addition, there now appears to be a C++ interface...

```
 ARPACK++

    User's Guide (arpackpp.ps.gz)
    GNU zipped tar file of distribution ( arpack++.tar.gz)
```

Am wondering if we need to fix this in arpack or, frankly, remove arpack and use arpack-ng. A brief grep on the packages that depend_on arpack use `arpack-ng`
