### ISSUE TITLE
Runtime environment variables not set by `spack env activate`

### ISSUE THREAD

**Issue by fgava90** [LLNL/spack#41327]
### Steps to reproduce

```console
cat test/spack.yaml

spack:
  specs:
    - gcc languages=c,c++,fortran
  view: true

spack env create test test/spack.yaml
spack env activate test
spack install
spack env deactivate
spack env activate test
echo $CC

```

### Error message

No error message but `CC` `CXX` etc environment variables are not set.
This happens for some other packages as well (environment modules are fine).
This does not happen for other packages like `openmpi` for example where `MPICC` etc are set

### Information on your system

* **Spack:** 0.21.0 (65d3221a9c436e77af9e802e543c71bd702ff4e2)
* **Python:** 3.6.8
* **Platform:** linux-rocky8-x86_64
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by fgava90** [comment]
Forgot to tag the maintainers @alalazo @michaelkuhn

**Comment by michaelkuhn** [comment]
Does it work if you remove these two lines? https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/gcc/package.py#L1019-L1020
That seems to fix it for me (since the view uses symlinks).

@sethrj You have added the symlink check in https://github.com/spack/spack/commit/7bcb306d4a5fc74fff63ea73369211e95270b911, can you remember why?

**Comment by fgava90** [comment]
Thank you, 

I can confirm it actually work removing those two lines.

If there was an issue with symlinks, what if instead of `continue` we resolve the symlink to the actual binary location with `abspath = os.realpath(abspath)`?

**Comment by sethrj** [comment]
I don't remember why, sorry. I think one of the relative/absolute links failed with treating homebrew as an external.

**Comment by michaelkuhn** [comment]
> If there was an issue with symlinks, what if instead of `continue` we resolve the symlink to the actual binary location with `abspath = os.realpath(abspath)`?

I've thought about that but that might not solve the underlying problem (if there is one and, e.g., the symlink points to an invalid location). Maybe we can limit the check to external packages or something similar.

**Comment by fgava90** [comment]
I see.
What about something like:
```python
if os.path.islink(abspath):
  abspath = os.path.realpath(abspath)
  # continue if 
  # - broken symlink 
  # - darwin platform (possible issue with homebrew)
  # - other conditions?
  if not os.path.exists(abspath) or self.spec.satisfies("platform=darwin") or ...
    continue
```
I'm not expert enough in spack to deal with stuff like external packages or more advanced things, sorry

**Comment by michaelkuhn** [comment]
Can you give #41729 a try?
