### ISSUE TITLE
Is there a way to set a "default version" for python2 and python3?

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#4132]
I have this in my packages.yaml

```yaml
  python:
    version: [2.7.13]
```

and also explicitly install python@3.6.0 to provide a particular version for version 3.

Snakemake depends on `python@3.3:`, so it just pulled in `python@3.6.1`

Is there anyway to also pin a version for Python 3?  

My best idea to avoid ending up with two copies of Python 3 is to find the things that I'm installing that depend on it and wire them up individually.  There aren't that many so it's not the end of the world, but I'm just checking to see if there's something more elegant I can do.

**Comment by citibeth** [comment]
I believe the following would work, but my list syntax might be a bit off:
```
  python:
    version: [2.7.13 3.6.0]
```

**Comment by hartzell** [comment]
Dead on in the theory, missing one comma in the syntax.

```yaml
python:
    version: [2.7.13, 3.6.0]
```

**Thanks!**
