### ISSUE TITLE
Installation issue: PETSc package doesn't have a variant for enabling/disabling Zoltan support

### ISSUE THREAD

**Issue by pbisbal1** [LLNL/spack#41468]
### Steps to reproduce the issue

For the PETSc maintainers (@balay, @barrysmith, @jedbrown): 

PETSc has a configure option for Zoltan support. From the output of `./configure --help`: 

```
ZOLTAN:
  --with-zoltan=<bool>
       Indicate if you wish to test for Zoltan  current: 0
  --with-zoltan-dir=<dir>
       Indicate the root directory of the Zoltan installation
  --with-zoltan-pkg-config=<dir>
       Look for Zoltan using pkg-config utility optional directory to look in
  --with-zoltan-include=<dirs>
       Indicate the directory of the Zoltan include files
  --with-zoltan-lib=<libraries: e.g. [/Users/..../libzoltan.a,...]>
       Indicate the Zoltan libraries
  --download-zoltan=<no,yes,filename,url>
       Download and install Zoltan  current: no
  --download-zoltan-commit=commitid
       The commit id from a git repository to use for the build of Zoltan  current: 0
  --download-zoltan-shared=<bool>
       Install ZOLTAN with shared libraries  current: 0
  --download-zoltan-configure-arguments=string
       Additional GNU autoconf configure arguments for the build of Zoltan  current: 0
```

But `spack info petsc` makes no mention of Zoltan, either as a variant or dependency.  Can this be fixed? I have an application here that needs PETSc w/ Zoltan support. Being able to provide PETSc w/ Zoltan support through Spack would be a huge win for me. 

I searched the issues, but didn't see any mention of this.

Thanks, 
Prentice

### Error message

No error message - not applicable 

### Information on your system

* **Spack:** 0.22.0.dev0 (88e738c34346031ce875fdd510dd2251aa63dad7)
* **Python:** 3.9.16
* **Platform:** linux-rhel9-zen2
* **Concretizer:** clingo

### Additional information

Not applicable. 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by balay** [comment]
@pbisbal1 can you try the fix at https://github.com/spack/spack/pull/41472?

**Comment by pbisbal1** [comment]
@balay Thanks for the quick response on this. I'm sorry I haven't had a chance to test it yet. i'm sure it's a simple fix, but I'll test it as soon as a I get the chance.
