### ISSUE TITLE
Installation issue: need to filter spack compiler wrappers when building ESMF

### ISSUE THREAD

**Issue by climbfuji** [LLNL/spack#41487]
### Steps to reproduce the issue

How to reproduce: install ESMF with spack

### Error message

The error is summarized in https://github.com/JCSDA/spack-stack/issues/892: When using spack-built ESMF for compiling applications as a NUOPC components, one gets:
```
ERROR: Spack compiler must be run from Spack! Input ‘some variable' is missing, where variable is:

SPACK_ENV_PATH
SPACK_DEBUG_LOG_DIR
SPACK_DEBUG_LOG_ID
SPACK_COMPILER_SPEC
SPACK_CC_RPATH_ARG
...
 ```
This is because the spack compilers end up in `esmf.mk` as `ESMF_F90COMPILER` etc. I think a similar bug fix than what was needed for `hdf5` (for `h5cc`) and `hdf4` can be applied to https://github.com/spack/spack/blob/7d45e132a669c54cc591fd2c019936c65868358d/var/spack/repos/builtin/packages/esmf/package.py#L393

@AlexanderRichert-NOAA  @theurich  @uturuncoglu

### Information on your system

```
* **Spack:** 0.21.0 (e49e9bfa7500ba31f93769c232eb8ce6ecb5322c)
* **Python:** 3.8.9
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo
```

### Additional information

n/a

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by uturuncoglu** [comment]
@climbfuji Let me reproduce the issue. When I tried to install ESMF through the spack-stack 1.5.1, it was working. Is this related with the ESMF version or something changed in the spack side. Do you have any information about it?

**Comment by climbfuji** [comment]
I think all you need to do is look inside the `esmf.mk` file. If the C/CXX/F90 compilers are pointing to the spack wrappers, you have reproduced the problem.

**Comment by uturuncoglu** [comment]
@climbfuji I check the compilers in my previous installation and it is showing like following for ESMF 8.5.0.

```
ESMF_F90COMPILER=/opt/ufs.local/gcc/11.4.0/openmpi-4.1.5-mlazref/bin/mpif90
ESMF_CXXCOMPILER=/opt/ufs.local/gcc/11.4.0/openmpi-4.1.5-mlazref/bin/mpic++
ESMF_CCOMPILER=/opt/ufs.local/gcc/11.4.0/openmpi-4.1.5-mlazref/bin/mpicc
```

It seems correct to me since it points the correct MPI compiler. I'll also try to install through the spack (just ESMF package) not with spack-stack to see what happens.

**Comment by climbfuji** [comment]
> @climbfuji I check the compilers in my previous installation and it is showing like following for ESMF 8.5.0.
> 
> ```
> ESMF_F90COMPILER=/opt/ufs.local/gcc/11.4.0/openmpi-4.1.5-mlazref/bin/mpif90
> ESMF_CXXCOMPILER=/opt/ufs.local/gcc/11.4.0/openmpi-4.1.5-mlazref/bin/mpic++
> ESMF_CCOMPILER=/opt/ufs.local/gcc/11.4.0/openmpi-4.1.5-mlazref/bin/mpicc
> ```
> 
> It seems correct to me since it points the correct MPI compiler. I'll also try to install through the spack (just ESMF package) not with spack-stack to see what happens.

Thanks for checking. That's interesting. We just merged a major spack dev update, so let me try to see if that fixes it. If not, then another possible reason is that the system where this happens (Narwhal) is a Cray, which is different in many aspects.

**Comment by uturuncoglu** [comment]
@climbfuji I could try on NCAR's derecho system if you want. I am not sure how similar to Narwhal but it might worth to try.

**Comment by climbfuji** [comment]
I see this in my macOS spack build that's based on the most recent update from spack develop:
```
ESMF_F90COMPILER=/Users/heinzell/work/spack-stack/spack-stack-nov2023_spackmerge/envs/unified-env/install/apple-clang/13.1.6/openmpi-4.1.6-2o3f3cj/bin/mpif90
ESMF_F90LINKER=/Users/heinzell/work/spack-stack/spack-stack-nov2023_spackmerge/envs/unified-env/install/apple-clang/13.1.6/openmpi-4.1.6-2o3f3cj/bin/mpic++
```
And this is from spack-stack-1.5.1, also on my macOS:
```
ESMF_F90COMPILER=/Users/heinzell/prod/spack-stack-1.5.1/envs/unified-env/install/apple-clang/13.1.6/openmpi-4.1.5-zhlaupe/bin/mpif90
ESMF_F90LINKER=/Users/heinzell/prod/spack-stack-1.5.1/envs/unified-env/install/apple-clang/13.1.6/openmpi-4.1.5-zhlaupe/bin/mpic++
```
This is on Derecho with spack-stack-1.5.1:
```
ESMF_F90COMPILER=/opt/cray/pe/mpich/8.1.25/ofi/intel/19.0/bin/mpif90
ESMF_F90LINKER=/opt/cray/pe/mpich/8.1.25/ofi/intel/19.0/bin/mpif90
```
And finally, this is on Narwhal with 1.5.1:
```
ESMF_F90COMPILER=/p/app/projects/NEPTUNE/spack-stack/spack-stack-1.5.1/spack/lib/spack/env/intel/ifort
ESMF_F90LINKER=/p/app/projects/NEPTUNE/spack-stack/spack-stack-1.5.1/spack/lib/spack/env/intel/ifort
```
What's the difference? Derecho and Narwhal are both Cray, but Derecho is a newer Cray that does not use the Cray compiler wrappers (`cc`, `CC`, `ftn`) in our spack config: https://github.com/JCSDA/spack-stack/blob/8780bcdff613e970e2cf881301587b72bd7f3ef8/configs/sites/derecho/compilers.yaml#L5

Narwhal uses the compiler wrappers: https://github.com/JCSDA/spack-stack/blob/8780bcdff613e970e2cf881301587b72bd7f3ef8/configs/sites/narwhal/compilers.yaml#L5

And sure enough, Gaea C5 which is also a Cray that uses `cc` `CC` `ftn` in the spack-stack site config also has the wrong compilers:
```
ESMF_F90COMPILER=/lustre/f2/dev/wpo/role.epic/contrib/spack-stack/c5/spack-stack-1.5.1/spack/lib/spack/env/intel/ifort
ESMF_F90LINKER=/lustre/f2/dev/wpo/role.epic/contrib/spack-stack/c5/spack-stack-1.5.1/spack/lib/spack/env/intel/ifort
```

So all this means that we need logic similar to https://github.com/spack/spack/blob/14392efc6ddabfff86eed7356e3b4ef5edd1e8b2/var/spack/repos/builtin/packages/hdf5/package.py#L382 *if and only if* the system is an "old style" Cray (ESMF_OS=Unicos in ESMF I think).

Note that we do have an issue open on trying to move away from the Cray compiler wrappers: https://github.com/JCSDA/spack-stack/issues/771 - nonetheless, we should fix this for old-style Crays.

**Comment by uturuncoglu** [comment]
@climbfuji Thanks for extra checking. Since I have no access to those platforms it would be hard for me to test the fix. BTW, I am not sure Unicos is right way to go to implement fix. @theurich do you have any idea about it?
