### ISSUE TITLE
Installation issue: zlib

### ISSUE THREAD

**Issue by narubi2** [LLNL/spack#41528]
### Steps to reproduce the issue

```console
$ spack spec zlib
Input spec
--------------------------------
 -   zlib

Concretized
--------------------------------
 -   doau55v  zlib@1.3%gcc@12.3.0+optimize+pic+shared build_system=makefile arch=linux-ubuntu22.04-skylake
 -   6uc3vzz      ^gmake@4.4.1%gcc@12.3.0~guile build_system=generic arch=linux-ubuntu22.04-skylake
```

### Error message

<details><summary>Error message</summary>

<pre>
spack install zlib
==> Installing gmake-4.4.1-6uc3vzzlzyqruckprou43so2ddd2z6lh [1/2]
==> No binary for gmake-4.4.1-6uc3vzzlzyqruckprou43so2ddd2z6lh found: installing from source
==> Using cached archive: /home/suhyeok/Programms/spack/var/spack/cache/_source-cache/archive/dd/dd16fb1d67bfab79a72f5e8390735c49e3e8e70b4945a15ab1f81ddb78658fb3.tar.gz
==> No patches needed for gmake
==> gmake: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 77:
    '/tmp/suhyeok/spack-stage/spack-stage-gmake-4.4.1-6uc3vzzlzyqruckprou43so2ddd2z6lh/spack-src/configure' '--prefix=/home/suhyeok/Programms/spack/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/gmake-4.4.1-6uc3vzzlzyqruckprou43so2ddd2z6lh' '--without-guile' '--disable-nls' '--disable-dependency-tracking'

2 errors found in build log:
     7     checking for mawk... mawk
     8     checking whether make sets $(MAKE)... yes
     9     checking whether make supports nested variables... yes
     10    checking whether make supports the include directive... yes (GNU style)
     11    checking for gcc... /home/suhyeok/Programms/spack/lib/spack/env/c++
     12    checking whether the C compiler works... no
  >> 13    configure: error: in `/tmp/suhyeok/spack-stage/spack-stage-gmake-4.4.1-6uc3vzzlzyqruckprou43so2ddd2z6lh/spack-src/spack-build':
  >> 14    configure: error: C compiler cannot create executables
     15    See `config.log' for more details

See build log for details:
  /tmp/suhyeok/spack-stage/spack-stage-gmake-4.4.1-6uc3vzzlzyqruckprou43so2ddd2z6lh/spack-build-out.txt

==> Warning: Skipping build of zlib-1.3-doau55vx63qzglovaut7j5zwkupp2kdj since gmake-4.4.1-6uc3vzzlzyqruckprou43so2ddd2z6lh failed
==> Error: zlib-1.3-doau55vx63qzglovaut7j5zwkupp2kdj: Package was not installed
==> Error: Installation request failed.  Refer to reported errors for failing package(s).

</pre></details>

### Information on your system

* **Spack:** 0.22.0.dev0 (5d999d0e4fb59b8eedc7519a6ed7d9361ce60688)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-skylake
* **Concretizer:** clingo

### Additional information

I am new to Spack and have recently followed the installation process outlined below:
```console
$ git clone -c feature.manyFiles=true https://github.com/spack/spack.git
$ cd spack/bin
$ ./spack install zlib
```
When I check the version of 'gmake' using gmake -v, it indicates the presence of GNU Make 4.3, and locating the executable using which gmake reveals it is installed in '/usr/bin/gmake'.

It appears that Spack is having difficulty finding the installed 'gmake' file and encounters conflicts during its attempt to install 'gmake'. I cannot find 'spack-build-out.txt' or 'spack-build-env.txt'.
I would greatly appreciate any suggestions or advice on how to resolve this issue.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
> See `config.log' for more details

somewhere in this dir:

```
/tmp/suhyeok/spack-stage/spack-stage-gmake-4.4.1-6uc3vzzlzyqruckprou43so2ddd2z6lh
```

**Comment by w8jcik** [comment]
It seems to be more generic issue, it happens for me with multiple packages

`config.log`

```bash
configure:3952: /home/user/dev/spack/lib/spack/env/c++ --version >&5
[spack cc] ERROR: Compiler 'gcc@=12.3.0' does not have a C++ compiler configured.
configure:3963: $? = 1
configure:3952: /home/user/dev/spack/lib/spack/env/c++ -v >&5
[spack cc] ERROR: Compiler 'gcc@=12.3.0' does not have a C++ compiler configured.
configure:3963: $? = 1
configure:3952: /home/user/dev/spack/lib/spack/env/c++ -V >&5
[spack cc] ERROR: Compiler 'gcc@=12.3.0' does not have a C++ compiler configured.
configure:3963: $? = 1
configure:3952: /home/user/dev/spack/lib/spack/env/c++ -qversion >&5
[spack cc] ERROR: Compiler 'gcc@=12.3.0' does not have a C++ compiler configured.
configure:3963: $? = 1
configure:3952: /home/user/dev/spack/lib/spack/env/c++ -version >&5
[spack cc] ERROR: Compiler 'gcc@=12.3.0' does not have a C++ compiler configured.
configure:3963: $? = 1
configure:3983: checking whether the C compiler works
configure:4005: /home/user/dev/spack/lib/spack/env/c++    conftest.c  >&5
[spack cc] ERROR: Compiler 'gcc@=12.3.0' does not have a C++ compiler configured.
configure:4009: $? = 1
configure:4049: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "PCRE2"
| #define PACKAGE_TARNAME "pcre2"
| #define PACKAGE_VERSION "10.42"
| #define PACKAGE_STRING "PCRE2 10.42"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define PACKAGE "pcre2"
| #define VERSION "10.42"
| /* end confdefs.h.  */
| 
| int
| main (void)
| {
| 
|   ;
|   return 0;
| }
configure:4054: error: in `/tmp/user/spack-stage/spack-stage-pcre2-10.42-tqk4ysjjrrakyhgpced2gv2vt7vhimeg/spack-src':
configure:4056: error: C compiler cannot create executables
```

It works in Ubuntu 22.04 Docker container, but it doesn't work in desktop version of Ubuntu 22.04.

Going few weeks back in Spack versions fixes it, so it looks like regression.
