### ISSUE TITLE
Installation issue: spack install gmsh@4.10.3%gcc@13.2.0 

### ISSUE THREAD

**Issue by JohnyMarley** [LLNL/spack#41522]
### Steps to reproduce the issue

spack install gmsh@4.10.3%gcc@13.2.0 

### Error message

==> Error: ProcessError: Command exited with status 2:
    'make' '-j8'

7 errors found in build log:
     2373      245 | #pragma omp atomic capture
     2374          |
     2375    /tmp/jdara/spack-stage/spack-stage-gmsh-4.10.3-dxtbzosbpthuyqoadtpgc3l3tm4pmenz/spack-src/src/geo/GModel.h:256: warning: ignoring '#pragma omp atomic' [-Wunknown-pragmas]
     2376      256 | #pragma omp atomic update
     2377          |
     2378    /tmp/jdara/spack-stage/spack-stage-gmsh-4.10.3-dxtbzosbpthuyqoadtpgc3l3tm4pmenz/spack-src/src/mesh/meshGFacePack.cpp: In function 'double p2triangle_alignment_quality_measure(double*, double*, double*, double*, double*, double*, i
             nt)':
  >> 2379    /tmp/jdara/spack-stage/spack-stage-gmsh-4.10.3-dxtbzosbpthuyqoadtpgc3l3tm4pmenz/spack-src/src/mesh/meshGFacePack.cpp:209:7: error: 'uint32_t' was not declared in this scope
     2380      209 |   for(uint32_t j = 0; j < 6; j++) {
     2381          |       ^~~~~~~~
     2382    /tmp/jdara/spack-stage/spack-stage-gmsh-4.10.3-dxtbzosbpthuyqoadtpgc3l3tm4pmenz/spack-src/src/mesh/meshGFacePack.cpp:16:1: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
     2383       15 | #include "robustPredicates.h"
     2384      +++ |+#include <cstdint>
     2385       16 |
  >> 2386    /tmp/jdara/spack-stage/spack-stage-gmsh-4.10.3-dxtbzosbpthuyqoadtpgc3l3tm4pmenz/spack-src/src/mesh/meshGFacePack.cpp:209:23: error: 'j' was not declared in this scope
     2387      209 |   for(uint32_t j = 0; j < 6; j++) {
     2388          |                       ^
  >> 2389    /tmp/jdara/spack-stage/spack-stage-gmsh-4.10.3-dxtbzosbpthuyqoadtpgc3l3tm4pmenz/spack-src/src/mesh/meshGFacePack.cpp:237:7: error: 'uint32_t' was not declared in this scope
     2390      237 |   for(uint32_t j = 1; j < 5; j++) {
     2391          |       ^~~~~~~~
     2392    /tmp/jdara/spack-stage/spack-stage-gmsh-4.10.3-dxtbzosbpthuyqoadtpgc3l3tm4pmenz/spack-src/src/mesh/meshGFacePack.cpp:237:7: note: 'uint32_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
  >> 2393    /tmp/jdara/spack-stage/spack-stage-gmsh-4.10.3-dxtbzosbpthuyqoadtpgc3l3tm4pmenz/spack-src/src/mesh/meshGFacePack.cpp:237:23: error: 'j' was not declared in this scope
     2394      237 |   for(uint32_t j = 1; j < 5; j++) {
     2395          |                       ^
     2396    /tmp/jdara/spack-stage/spack-stage-gmsh-4.10.3-dxtbzosbpthuyqoadtpgc3l3tm4pmenz/spack-src/src/mesh/meshGFacePack.cpp: At global scope:
     2397    /tmp/jdara/spack-stage/spack-stage-gmsh-4.10.3-dxtbzosbpthuyqoadtpgc3l3tm4pmenz/spack-src/src/mesh/meshGFacePack.cpp:177:15: warning: 'double closest(double, double)' defined but not used [-Wunused-function]
     2398      177 | static double closest(double t, double u)
     2399          |               ^~~~~~~
  >> 2400    make[2]: *** [CMakeFiles/shared.dir/build.make:2613: CMakeFiles/shared.dir/src/mesh/meshGFacePack.cpp.o] Error 1
     2401    make[2]: *** Waiting for unfinished jobs....
     2402    In file included from /tmp/jdara/spack-stage/spack-stage-gmsh-4.10.3-dxtbzosbpthuyqoadtpgc3l3tm4pmenz/spack-src/src/mesh/meshGFaceBamg.cpp:12:
     2403    /tmp/jdara/spack-stage/spack-stage-gmsh-4.10.3-dxtbzosbpthuyqoadtpgc3l3tm4pmenz/spack-src/src/geo/GModel.h:222: warning: ignoring '#pragma omp atomic' [-Wunknown-pragmas]
     2404      222 | #pragma omp atomic write
     2405          |
     2406    /tmp/jdara/spack-stage/spack-stage-gmsh-4.10.3-dxtbzosbpthuyqoadtpgc3l3tm4pmenz/spack-src/src/geo/GModel.h:227: warning: ignoring '#pragma omp atomic' [-Wunknown-pragmas]

     ...

     2413      245 | #pragma omp atomic capture
     2414          |
     2415    /tmp/jdara/spack-stage/spack-stage-gmsh-4.10.3-dxtbzosbpthuyqoadtpgc3l3tm4pmenz/spack-src/src/geo/GModel.h:256: warning: ignoring '#pragma omp atomic' [-Wunknown-pragmas]
     2416      256 | #pragma omp atomic update
     2417          |
     2418    make[2]: Leaving directory '/tmp/jdara/spack-stage/spack-stage-gmsh-4.10.3-dxtbzosbpthuyqoadtpgc3l3tm4pmenz/spack-build-dxtbzos'
  >> 2419    make[1]: *** [CMakeFiles/Makefile2:707: CMakeFiles/shared.dir/all] Error 2
     2420    make[1]: Leaving directory '/tmp/jdara/spack-stage/spack-stage-gmsh-4.10.3-dxtbzosbpthuyqoadtpgc3l3tm4pmenz/spack-build-dxtbzos'
  >> 2421    make: *** [Makefile:169: all] Error 2

See build log for details:
  /tmp/jdara/spack-stage/spack-stage-gmsh-4.10.3-dxtbzosbpthuyqoadtpgc3l3tm4pmenz/spack-build-out.txt

### Information on your system

* **Spack:** 0.21.0 (65d3221a9c436e77af9e802e543c71bd702ff4e2)
* **Python:** 3.11.5
* **Platform:** linux-linuxmint21-icelake
* **Concretizer:** clingo

### Additional information

It seems that gmsh 4.10.3 when compiled with gcc 13.2.0 doesnt have the updated gmsh version which has the +#include <cstdint> header included. I can see that this is fixed with a merge request in the gitlab gmsh repository, but I am assuming that this has not been updated in how spack build gmsh? 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by schrummy14** [comment]
@JohnyMarley, it will be an issue with how spack is pulling the 4.10.3 version as they are pulling the .tgz file from the tag.
Gmsh would need to update this file (as of 2023-12-26, this is not done).
Spack would probably need to add a patch file to get 4.10.3 to work.

**Comment by JohnyMarley** [comment]
I see! I used the workaround to just pull the master branch.
