### ISSUE TITLE
Installation issue: Julia on Fugaku

### ISSUE THREAD

**Issue by otsukay** [LLNL/spack#41571]
### Steps to reproduce the issue

```console
$ spack spec -I julia@1.9.3 %fj
==> Warning: using "openssl@1.1.1k" which is a deprecated version                                                                            [30/11125]
 Input spec
 --------------------------------
  -   julia@1.9.3%fj
 
 Concretized
 --------------------------------
  -   julia@1.9.3%fj@4.8.1+openlibm+precompile build_system=makefile arch=linux-rhel8-a64fx
 [+]      ^curl@8.1.2%fj@4.8.1~gssapi~ldap~libidn2~librtmp~libssh+libssh2+nghttp2 build_system=autotools libs=shared,static tls=mbedtls,openssl arch=lin
 ux-rhel8-a64fx
 [+]          ^gnuconfig@2021-08-14%fj@4.8.1 build_system=generic arch=linux-rhel8-a64fx
 [+]          ^openssl@1.1.1k%fj@4.8.1~docs~shared build_system=generic certs=mozilla arch=linux-rhel8-a64fx
 [+]          ^pkgconf@1.4.2%fj@4.8.1 build_system=autotools arch=linux-rhel8-a64fx
 [+]      ^dsfmt@2.2.5%fj@4.8.1 build_system=makefile patches=b79624c arch=linux-rhel8-a64fx
 [+]      ^gmp@6.1.2%fj@4.8.1 build_system=autotools libs=shared,static arch=linux-rhel8-a64fx
 [+]      ^libblastrampoline@5.8.0%fj@4.8.1 build_system=makefile arch=linux-rhel8-a64fx
 [+]      ^libgit2@1.5.0%fj@4.8.1~curl~ipo+mmap+ssh build_system=cmake build_type=RelWithDebInfo https=system arch=linux-rhel8-a64fx
 [+]          ^cmake@3.24.3%fj@4.8.1~doc+ncurses+ownlibs~qt build_system=generic build_type=Release patches=db77b51 arch=linux-rhel8-a64fx
 [+]      ^libssh2@1.10.0%fj@4.8.1~ipo+shared build_system=cmake build_type=RelWithDebInfo crypto=mbedtls arch=linux-rhel8-a64fx
 [+]          ^xz@5.2.4%fj@4.8.1~pic build_system=autotools libs=shared,static arch=linux-rhel8-a64fx
 [+]      ^libunwind@1.6.2%fj@4.8.1~block_signals~conservative_checks~cxx_exceptions~debug~debug_frame+docs~pic+tests+weak_backtrace~xz~zlib build_syste
 m=autotools components=none libs=shared,static arch=linux-rhel8-a64fx
 [+]      ^libuv-julia@1.44.2%fj@4.8.1 build_system=autotools arch=linux-rhel8-a64fx
 [+]      ^libwhich@1.1.0%fj@4.8.1 build_system=generic arch=linux-rhel8-a64fx
  -       ^llvm@14.0.6%fj@4.8.1+clang~cuda~flang+gold~ipo+libomptarget~libomptarget_debug+link_llvm_dylib+lld+lldb+llvm_dylib+lua~mlir+polly~python~spli
 t_dwarf~z3 build_system=cmake build_type=RelWithDebInfo compiler-rt=runtime libcxx=runtime libunwind=none openmp=runtime patches=1f42874,25bc503,637916
 8,8248141,b216cff,cb8e645,f3def26 shlib_symbol_version=JL_LLVM_14.0 targets=all,amdgpu,bpf,nvptx,webassembly version_suffix=jl arch=linux-rhel8-a64fx
 [+]          ^binutils@2.30%fj@4.8.1~gas+gold+headers~interwork+ld~libiberty~lto+nls+plugins build_system=autotools libs=shared,static arch=linux-rhel8
 -a64fx
 [+]          ^elfutils@0.186%fj@4.8.1~bzip2~debuginfod+nls~xz~zstd build_system=autotools arch=linux-rhel8-a64fx
 [+]          ^hwloc@2.2.0%fj@4.8.1~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,stati
 c arch=linux-rhel8-a64fx
 [+]          ^libedit@3.1%fj@4.8.1 build_system=autotools arch=linux-rhel8-a64fx
 [+]          ^libffi@3.1%fj@4.8.1 build_system=autotools arch=linux-rhel8-a64fx
 [+]          ^libxml2@2.9.7%fj@4.8.1~python build_system=autotools arch=linux-rhel8-a64fx
 [+]          ^lua@5.3.6%fj@4.8.1~pcfile+shared build_system=makefile fetcher=curl arch=linux-rhel8-a64fx
 [+]              ^readline@7.0%fj@4.8.1 build_system=autotools arch=linux-rhel8-a64fx
 [+]              ^unzip@6.0%fj@4.8.1 build_system=makefile arch=linux-rhel8-a64fx
 [+]          ^ncurses@6.1%fj@4.8.1~symlinks+termlib abi=none build_system=autotools arch=linux-rhel8-a64fx
 [+]          ^perl-data-dumper@2.173%fj@4.8.1 build_system=perl arch=linux-rhel8-a64fx
 [+]          ^swig@4.0.2%fj@4.8.1 build_system=autotools arch=linux-rhel8-a64fx
 [+]              ^pcre@8.42%fj@4.8.1~jit+multibyte+utf build_system=autotools arch=linux-rhel8-a64fx
 [+]      ^mbedtls@2.28.0%fj@4.8.1+pic build_system=makefile build_type=Release libs=shared,static arch=linux-rhel8-a64fx
 [+]      ^mpfr@4.1.0%fj@4.8.1 build_system=autotools libs=shared,static arch=linux-rhel8-a64fx
 [+]          ^autoconf@2.69%fj@4.8.1 build_system=autotools patches=7793209 arch=linux-rhel8-a64fx
 [+]          ^autoconf-archive@2022.02.11%fj@4.8.1 build_system=autotools patches=139214f arch=linux-rhel8-a64fx
 [+]          ^automake@1.16.1%fj@4.8.1 build_system=autotools arch=linux-rhel8-a64fx
 [+]          ^libtool@2.4.6%fj@4.8.1 build_system=autotools arch=linux-rhel8-a64fx
 [+]          ^m4@1.4.18%fj@4.8.1+sigsegv build_system=autotools patches=3877ab5,fc9b616 arch=linux-rhel8-a64fx
 [+]          ^texinfo@6.5%fj@4.8.1 build_system=autotools patches=12f6edb,1732115 arch=linux-rhel8-a64fx
 [+]      ^nghttp2@1.48.0%fj@4.8.1 build_system=autotools arch=linux-rhel8-a64fx
 [+]      ^openblas@0.3.21%fj@4.8.1~bignuma~consistent_fpcsr+fortran+ilp64+locking+pic+shared build_system=makefile patches=d3d9b15 symbol_suffix=64_ th
 reads=none arch=linux-rhel8-a64fx
 [+]      ^openlibm@0.8.1%fj@4.8.1 build_system=makefile arch=linux-rhel8-a64fx
 [+]      ^p7zip@16.02%fj@4.8.1 build_system=makefile arch=linux-rhel8-a64fx
 [+]      ^patchelf@0.16.1%fj@4.8.1 build_system=autotools arch=linux-rhel8-a64fx
 [+]      ^pcre2@10.32%fj@4.8.1~jit+multibyte build_system=autotools arch=linux-rhel8-a64fx
 [+]      ^perl@5.26.3%fj@4.8.1+cpanm+shared+threads build_system=generic patches=8cf4302 arch=linux-rhel8-a64fx
 [+]      ^python@3.10.8%fj@4.8.1+bz2+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tix~tkinter~ucs4
 +uuid+zlib build_system=generic patches=0aba3bf,0d98e93,7d40923,f2fd060 arch=linux-rhel8-a64fx
 [+]      ^suite-sparse@5.13.0%fj@4.8.1~cuda~graphblas~openmp+pic build_system=generic arch=linux-rhel8-a64fx
 [+]          ^metis@5.1.0%fj@4.8.1~gdb~int64~ipo~real64+shared build_system=cmake build_type=RelWithDebInfo patches=4991da9,93a7903 arch=linux-rhel8-a6
 4fx
 [+]      ^utf8proc@2.8.0%fj@4.8.1~ipo~shared build_system=cmake build_type=RelWithDebInfo arch=linux-rhel8-a64fx
 [+]      ^zlib@1.2.13%fj@4.8.1+optimize+pic+shared build_system=makefile arch=linux-rhel8-a64fx

```

### Error message

<details><summary>Error message</summary>

<pre>
2 errors found in build log:
     2058    [WARN] xos LPG 2003 - Failed to map HugeTLBfs for data/bss: Layout problem with segments 0 and 1:
     2059       Segments would overlap.
     2060    [WARN] xos LPG 2003 - Failed to map HugeTLBfs for data/bss: Layout problem with segments 0 and 1:
     2061       Segments would overlap.
     2062     cd /vol0003/rccs-sdt/data/a01036/tmp/spack-stage/spack-stage-julia-1.9.3-2b5ejj23dklma6jk6baideq4i2wuxzl2/spack-src/base && /vol0003/rccs-sdt/data/a01036/tmp/spack-stage/spack-stage-julia-1.9
             .3-2b5ejj23dklma6jk6baideq4i2wuxzl2/spack-src/usr/bin/julia -C "a64fx" --output-ji /vol0003/rccs-sdt/data/a01036/tmp/spack-stage/spack-stage-julia-1.9.3-2b5ejj23dklma6jk6baideq4i2wuxzl2/spack-
             src/usr/lib/julia/corecompiler.ji.tmp --startup-file=no --warn-overwrite=yes -g0 -O0 compiler/compiler.jl
     2063    /bin/sh: line 1:  4156 Segmentation fault      /vol0003/rccs-sdt/data/a01036/tmp/spack-stage/spack-stage-julia-1.9.3-2b5ejj23dklma6jk6baideq4i2wuxzl2/spack-src/usr/bin/julia -C "a64fx" --outpu
             t-ji /vol0003/rccs-sdt/data/a01036/tmp/spack-stage/spack-stage-julia-1.9.3-2b5ejj23dklma6jk6baideq4i2wuxzl2/spack-src/usr/lib/julia/corecompiler.ji.tmp --startup-file=no --warn-overwrite=yes -
             g0 -O0 compiler/compiler.jl
  >> 2064    make[1]: *** [sysimage.mk:61: /vol0003/rccs-sdt/data/a01036/tmp/spack-stage/spack-stage-julia-1.9.3-2b5ejj23dklma6jk6baideq4i2wuxzl2/spack-src/usr/lib/julia/corecompiler.ji] Error 139
     2065    make[1]: Leaving directory '/vol0003/rccs-sdt/data/a01036/tmp/spack-stage/spack-stage-julia-1.9.3-2b5ejj23dklma6jk6baideq4i2wuxzl2/spack-src'
  >> 2066    make: *** [Makefile:84: julia-sysimg-ji] Error 2

See build log for details:
  /vol0003/rccs-sdt/data/a01036/tmp/spack-stage/spack-stage-julia-1.9.3-2b5ejj23dklma6jk6baideq4i2wuxzl2/spack-build-out.txt

</pre></details>

### Information on your system

 * **Spack:** 0.19.0 (e69409eb1d2106279ac36b26035990c55252eb43)
 * **Python:** 3.10.8
 * **Platform:** linux-rhel8-a64fx
 * **Concretizer:** clingo

### Additional information

@vchuravy @haampie @giordano

Hi, 
I have been trying to install recent versions of Julia on [Fugaku](https://www.r-ccs.riken.jp/en/fugaku/about/) using Spack but have never succeeded. It was possible to install julia@1.6.3 using Spack-0.17.0, the previous official environment we provided. I have tried Julia 1.7.3, 1.8.5, and 1.9.3 with Spack-v0.19, ending up with a segmentation fault in the `make` process, where the binary file `usr/bin/julia` was compiled but failed to be executed, probably as in the [case reported by @giordano](https://github.com/giordano/julia-on-fugaku). 

I have confirmed that the official binary of Julia 1.9.3 works fine on Fugaku and understand that the official one is sufficient and should even be chosen. However, as far as the policy of our center is concened, it is desired to provide OSSs with Spack instead of just putting precompiled binaries.

[spack-build-out.txt](https://github.com/spack/spack/files/13644472/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/13644474/spack-build-env.txt)

```console
$ diff package.org.py package.py
191,192c191,193
<     depends_on("zlib-api")
<     depends_on("zlib +shared +pic +optimize", when="^zlib")
---
>     depends_on("zlib +shared +pic +optimize")
>     #depends_on("zlib-api")
>     #depends_on("zlib +shared +pic +optimize", when="^zlib")
258a260
>             "zlib",
267,268c269,270
<         for dir in self.spec["zlib-api"].libs.directories:
<             env.prepend_path(linker_var, dir)
---
>         # for dir in self.spec["zlib-api"].libs.directories:
>         #     env.prepend_path(linker_var, dir)
276c278,281
<         march = get_best_target(spec.target, spec.compiler.name, spec.compiler.version)
---
>         #march = get_best_target(spec.target, spec.compiler.name, spec.compiler.version)
>         march = 'armv8-a'
>
>         filter_file(r'libquadmath,0', 'libquadmath,0,ALLOW_FAILURE', "base/Makefile")
335a341
>                 "override LIBGFORTRAN_VERSION:=5",
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by giordano** [comment]
> I have confirmed that the official binary of Julia 1.9.3 works fine on Fugaku and understand that the official one is sufficient and should even be chosen. However, as far as the policy of our center is concened, it is desired to provide OSSs with Spack instead of just putting precompiled binaries.

Any chance of using gcc instead of fj for this package? That should be easier to do, as it's a much better tested configuration.

**Comment by giordano** [comment]
Also, tangentially related question: how did you compile openblas with fj? Every time I tried I got into #31675. If you folks have a fix in spack (or openblas?) for that, it'd be great to upstream it.

**Comment by otsukay** [comment]
@giordano 
Thanks for your comments.
I will try it using gcc (although I wonder if it is what we need).
As for openblas, I could compile it on top of spack-v0.19 using [this recipe](https://github.com/RIKEN-RCCS/spack/tree/fugaku-v0.19/var/spack/repos/builtin/packages/openblas), which I think is older than the built-in recipe of spack-v0.19.

**Comment by giordano** [comment]
> I will try it using gcc (although I wonder if it is what we need).

Note that julia is made of a compiler and a runtime (which includes for example a garbage collector): the compiler you use to build julia shouldn't affect much, if at all, the performance of the code generated by the Julia compiler, it may have some effect on the runtime, but probably that doesn't take much advantage of vectorization and such, so that again the compiler used to build that component shouldn't be very relevant. All in all, I believe using gcc should be fine for you.

**Comment by mofeing** [comment]
@giordano we also find these warnings when loading FujitsuBLAS right?

```
     2058    [WARN] xos LPG 2003 - Failed to map HugeTLBfs for data/bss: Layout problem with segments 0 and 1:
     2059       Segments would overlap.
     2060    [WARN] xos LPG 2003 - Failed to map HugeTLBfs for data/bss: Layout problem with segments 0 and 1:
     2061       Segments would overlap.
```

**Comment by giordano** [comment]
Yes, that seems to be a constant when loading in julia libraries compiled with `-Kopenmp`.  The warning seems harmless in the sense that I haven't had any concrete problems so far, but can't guarantee it's completely safe to ignore.

**Comment by otsukay** [comment]
@giordano
Finally, I was able to install julia using gcc, `julia@1.9.3 % gcc@12.2.0`. Thanks for your suggestion. You wrote that [the gcc build of julia is slow](https://github.com/giordano/julia-on-fugaku), but this is not the case with the recent versions of julia, possibly due to the improved performance of llvm, is it?

**Comment by giordano** [comment]
> Finally, I was able to install julia using gcc, `julia@1.9.3 % gcc@12.2.0`. Thanks for your suggestion.

Glad that it worked!

> You wrote that [the gcc build of julia is slow](https://github.com/giordano/julia-on-fugaku), but this is not the case with the recent versions of julia, possibly due to the improved performance of llvm, is it?

Sorry, I was probably being very unclear, but I meant that it's the build process that is slow, I generally find A64FX to be quite slow at compiling code (not just julia), but running numerical code on that CPU in Julia is usually pretty fast, and as fast as using other toolchains, as the repository showcases!

**Comment by otsukay** [comment]
@giordano
It is embarrassing that I misread the sentence. I didn't carefully check your benchmark result, supposing that it was just showing poor performance.
Anyway, it is good to know that using gcc is OK. Thank you again.
