### ISSUE TITLE
suite-sparse+tbb cannot find include 

### ISSUE THREAD

**Issue by svenevs** [LLNL/spack#4160]
I've been trying to patch this myself but I can't figure out what's going on, and honestly don't know how to debug `spack` very well (I literally raise exceptions and print out `__dict__` half the time, is there a way for me to open up `pdb` or something somehow?)

The issue: `suite-sparse+tbb`:

```
../Source/spqr_parallel.cpp:10:37: fatal error: tbb/task_scheduler_init.h: No such file or directory
```

The file definitely exists, but I can't quite figure out how to include it for this package.

```
 98         if 'tbb' in spec:
 99             make_args.extend([
100                 'SPQR_CONFIG=-DHAVE_TBB',
101                 'TBB=-L%s -ltbb' % spec['tbb'].prefix.lib,
102             ])```
```

I tried to add just a straight `'-I%s' % spec['tbb'].prefix.include` as well as instead setting `'TBB_PATH=%s' % spec['tbb'].prefix`, but it's clearly not the right way to do this.

Unrelated, I'm noticing a bunch of cuda stuff.  I was gonna tinker with this a bit since I'm here, but should that go in a different PR (assuming I can fix the include thing)?

**Comment by davydden** [comment]
`-I` are added automatically in compiler wrappers. I had issues with TBB in suite-sparse before, then at some point it was fixed and then in later releases it got broken again. I would contact developers, see http://faculty.cse.tamu.edu/davis/suitesparse.html for e-mail address.

**Comment by svenevs** [comment]
Ok sounds good. As a corollary, where in the spack setup process can I set environment variables? Like just point me to a package to refer to our docs?

I've been spinning their docs and they seem to need `TBB_PATH`. I want to provide them more information if possible

**Comment by davydden** [comment]
for example

os.environ['SLEPC_DIR'] = os.getcwd()

**Comment by svenevs** [comment]
> `-I` are added automatically in compiler wrappers

Not according to by `spack-build`...the referencing PR is all I actually needed to fix this, I feel quite strongly about leaving the `NOTE` in there.  There seems to be something bigger going on with the staging environment, and if that patch stops being applicable this package is gonna need some love.  Until then, this seems to work :smile:

**Comment by alalazo** [comment]
> Not according to by spack-build...

@svenevs I see that the issue is that we weren't using compiler wrappers, but wanted to point out that you wouldn't see anyhow the `-I<dir>` in `spack-build.out`, because it's done internally to the wrapper.

 What you'll see there (maybe) is if we are using the wrappers or not.
