### ISSUE TITLE
Not Able to Load Modules Built with Intel Compilers

### ISSUE THREAD

**Issue by yangliu2009** [LLNL/spack#41638]
### Steps to reproduce

```
spack install intel-oneapi-compilers@2023.1.0
module load intel-oneapi-compilers/2023.1.0
spack compiler find
spack install sextractor  --enable-mkl %intell@2021.9.0
```

### Error message

After the `sextractor `module is installed, I am not able to load the module because it is under `intel/2021.9.0` but there is no module for `intel/2021.9.0`.

### Information on your system

* **Spack:** 0.20.1
* **Python:** 3.9.16
* **Platform:** linux-rhel9-cascadelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by mladenivkovic** [comment]
You're installing intel-oneapi-compilers at version 2023.1.0, but tell spack to install sextractor for intel 2021.9.0.

Try

```
spack install sextractor  --enable-mkl %intel-oneapi-compilers@2023.1.0
```

instead.

Also make sure to let spack know to add the installed compilers. Once oneapi is installed, load the module and run `spack compiler find`.

**Comment by yangliu2009** [comment]
I tried but receive an error
```
$ spack install sextractor  %intel-oneapi-compilers@2023.1.0
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    sextractor%intel-oneapi-compilers@2023.1.0 is unsatisfiable, errors are:
```

According to[ the user doc here](https://spack.readthedocs.io/en/latest/build_systems/inteloneapipackage.html), Intel-onapi-comilers include the intel compilers (icc/ifort) and oneapi compilers.  Should we add the intel compiler and then compile a package using `%intel`?

**Comment by mladenivkovic** [comment]
I think the compiler is called `oneapi@2023.1.0`, not `intel-oneapi-compilers@2023.1.0`, at least it is on my system.

So maybe try

```
spack install sextractor  --enable-mkl %oneapi@2023.1.0
```

The newer oneapi compilers don't use icc and ifort any more, but icx and ifx. 2023 should still have icc and ifort, but you'll probably have to specify that you want those, and not the default ones.

**Comment by yangliu2009** [comment]
The `spack compiler find` command added three compilers. I could install sextractor using one compiler, i.e., intel@2021.9.0. But there are no modules for the three compilers. And users are not able to load the module via `module load sextractor`.

```
$ spack compiler find
==> Added 3 new compilers to /users/yliu385/.spack/linux/compilers.yaml
    oneapi@2023.1.0  intel@2021.9.0  dpcpp@2023.1.0
==> Compilers are defined in the following files:
    /oscar/rt/9.2/software/0.20-generic/0.20.1/etc/spack/defaults/compilers.yaml  /users/yliu385/.spack/linux/compilers.yaml
[yliu385@login009 0.20-generic]$ spack compilers
==> Available compilers
-- dpcpp rhel9-x86_64 -------------------------------------------
dpcpp@2023.1.0

-- gcc rhel9-x86_64 ---------------------------------------------
gcc@11.3.1

-- intel rhel9-x86_64 -------------------------------------------
intel@2021.9.0

-- oneapi rhel9-x86_64 ------------------------------------------
oneapi@2023.1.0
$ spack find oneapi
==> No package matches the query: oneapi
```

**Comment by mladenivkovic** [comment]
you can look up the details of the compilers in `/users/yliu385/.spack/linux/compilers.yaml`.

The compiler name is different from the package name. While the package is `intel-oneapi-compilers@2023.1.0`, the compiler's name is `oneapi@2023.1.0`.

**Comment by yangliu2009** [comment]
I was able to build sextractor using oneapi@2023.1.0 and load the module. Thanks for the help.
