### ISSUE TITLE
containerize: issues with custom repos in the environment directory

### ISSUE THREAD

**Issue by odoublewen** [LLNL/spack#41656]
### Steps to reproduce

`spack containerize` generates a Dockerfile that, among other things, makes a new dir for the spack environment ([see this line in the Dockerfile template](https://github.com/spack/spack/blob/80f31829a8aaa6cd71b62e3926c9336f239204ac/share/spack/templates/container/Dockerfile#L19)).

However, this command will generate an error during Docker build, if the dir already exists in the base image.

To reproduce:  Create a docker image that already has a dir named `/opt/spack-environment`, and use that docker image for `container.images.build`.

### Error message

```
mkdir: cannot create directory '/opt/spack-environment': File exists
```

### Information on your system

Mostly not relevant.  I am using Spack 0.21.0.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by odoublewen** [comment]
If you agree that what I've describe is a problem worth fixing, I have offered PR #41558, which simply adds a `-p` arg to the `mkdir` command, so it will not throw an error if the dir already exists.

**Comment by odoublewen** [comment]
Hi @alalazo, @hartzell suggested that you might be a good person to consider this, since you have done work on spack containerize.  I've proposed two alternative PRs to address this, the one above (which is probably not good for the reason described by @wdconinc) and https://github.com/spack/spack/pull/41746 (which I hope seem reasonable).

**Comment by odoublewen** [comment]
@alalazo Perhaps a better title for this issue would be:

>spack containerize does not work with custom repos

In other words, if a user writes a `spack.yaml` file like this:
```
spack:
  specs:
  - foo@1.2.3
  repos:
  - my_custom_packages
```

...and tries to use `spack containerize` then they will bump their head on the problem described above.  Besides the two relatively lightweight workarounds that I've proposed in the above-linked PRs, there is arguably a third option: Make spack containerize actually properly deal with custom repos.  If that seems better, I could help with the development.

**Comment by alalazo** [comment]
@odoublewen Yes, that would be a better title. Let me change that and raise priority here.

EDIT: I also specified that the custom repo must be in the env dir to trigger the issue
