### ISSUE TITLE
spack -h does not show extension commands

### ISSUE THREAD

**Issue by tjfulle** [LLNL/spack#41725]
### Steps to reproduce

add an extension with commands to `spack:extensions` and run

```console
spack -h
```

the extensions commands will not show, even if they have `level = "short"` defined.

They will display if you run `spack help --all`.

### Error message

No error message,  extension commands do not display in help message.

### Information on your system

* **Spack:** 0.20.1 (2df338660c37158945c8c94c9fe7e42ed3d68e58)
* **Python:** 3.10.8
* **Platform:** darwin-monterey-m1
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by tjfulle** [comment]
Simply delaying when [`args.help`](https://github.com/spack/spack/blob/b7edcbecd7adc4f7db670392499295bfcf6bdab1/lib/spack/spack/main.py#L955) is processed until after [`set_main_options`](https://github.com/spack/spack/blob/b7edcbecd7adc4f7db670392499295bfcf6bdab1/lib/spack/spack/main.py#L977) is called fixes this issue.

**Comment by alecbcs** [comment]
@psakievich is this something you've had to deal with in `spack-manager` / would you be interested in working on a fix?

**Comment by psakievich** [comment]
@alecbcs there is an open PR on this on(#41726). I will help push it across the finish line this week though.
