### ISSUE TITLE
Environment directory names

### ISSUE THREAD

**Issue by gkedziora** [LLNL/spack#41779]
### Steps to reproduce

$ mkdir LAVAEnv_oneapi@2022.1.0
$ cd LAVAEnv_oneapi@2022.1.0/
$ spack env create --with-view view --dir .
==> Created environment in /nobackupp27/gkedzior/spack-for-lava/LAVAEnv_oneapi@2022.1.0
==> You can activate this environment with:
==>   spack env activate /nobackupp27/gkedzior/spack-for-lava/LAVAEnv_oneapi@2022.1.0
$ spack -d env rm LAVAEnv_oneapi@2022.1.0
==> Error: 'LAVAEnv_oneapi@2022.1.0': names must start with a letter, and only contain letters, numbers, _, and -.

### Error message

$ spack -d env rm LAVAEnv_oneapi@2022.1.0
==> Error: 'LAVAEnv_oneapi@2022.1.0': names must start with a letter, and only contain letters, numbers, _, and -.

Now it becomes difficult to remove this environment and start over without uninstalling spack. Can we have either a check of the name at creation or better yet allow other symbols in the name?

### Information on your system

* **Spack:** 0.22.0.dev0 (ef4274ed2ee9545eab399a6249346b56b66415a4)
* **Python:** 3.6.8
* **Platform:** linux-rhel8-sandybridge
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
I don't think `spack env rm` works at all for anonymous environments, it's for named / managed environments, so it expects a name, not a path.

**Comment by gkedziora** [comment]
Ok. It would be good to have a more specific error message however.

**Comment by psakievich** [comment]
You can delete the directory to remove the environment. Since it is an anonymous env there is no bookkeeping on the installed specs relative to other envs.
