### ISSUE TITLE
py-scipy / netlib-lapack spec is too constrained

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#418]
When trying to install py-scipy, I get an error message. Should we make the +shared variant of netlib-lapack enabled by default?

```bash
$ spack install py-scipy
==> Error: Invalid spec: 'netlib-lapack@3.5.0%gcc@5.3.0~shared=linux-x86_64^cmake@3.4.0%gcc@5.3.0+ncurses=linux-x86_64^ncurses@6.0%gcc@5.3.0=linux-x86_64^netlib-blas@3.5.0%gcc@5.3.0~fpic=linux-x86_64'. Package netlib-lapack requires variant +shared, but spec asked for ~shared
```

**Comment by nrichart** [comment]
Does py-scipy really need a dependency on blas/lapack ?
To build it uses the info regarding blas/lapack comming from numpy. And `py-numpy` as en explicit dependency with `netlib-blas+fpic` and `netlib-lapack+shared`. I guess this should ideally be a dependency with `blas` and `lapack`

**Comment by adamjstewart** [comment]
@nrichart: According to the [SciPy Installation Instructions](http://www.scipy.org/scipylib/building/linux.html), SciPy's dependencies include: "BLAS and LAPACK libraries (optional but strongly recommended for NumPy, required for SciPy)". I made some changes to the packages with #627. I think it makes sense to have NumPy optionally depend on BLAS/LAPACK (but default to True) and have SciPy always depend on BLAS/LAPACK. Yes, we could remove SciPy's dependencies by specifying that it `depends_on('py-numpy+blas+lapack')`. But if the documentation says that SciPy depends on BLAS/LAPACK, I don't see any harm in making this explicit.

#627 solves this particular case, but it does not solve the root problem. From what I understand, Spack sees that py-scipy depends on blas/lapack and chooses openblas. Then it sees that py-numpy depends on a different blas/lapack, but refuses to change its mind. @tgamblin: I'll let you decide whether or not to close this issue once #627 gets merged.

**Comment by nrichart** [comment]
That is perfectly fine with me. My question came from the fact that we installed on our site numpy/scipy following the intel [article](https://software.intel.com/en-us/articles/numpyscipy-with-intel-mkl). And since numpy provides the configuration used for blas/lapack my guess was that scipy reuses this informations, and do not reconfigure them.
