### ISSUE TITLE
Create/refresh lmod for packages installed with a specific compiler

### ISSUE THREAD

**Issue by sheltongeosx** [LLNL/spack#41811]
### Summary

The command "spack module lmod refresh" will re-create lmod modules for all packages installed with all compilers. My question is how to re-create just only the group of packages that were installed with a specific compiler? Thanks!

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
You can do:
```console
$ spack module lmod refresh %gcc
```
to regenerate only the packages installed with `gcc` etc. More details [here](https://spack.readthedocs.io/en/latest/module_file_support.html#refresh-the-set-of-modules)
