### ISSUE TITLE
Add version 6+ to rocm packages (hip/roctracer/rocprofiler etc)

### ISSUE THREAD

**Issue by wspear** [LLNL/spack#41837]
We need to test and deploy the newest versions of roctracer and rocprofiler (and their dependencies). Currently spack-provided versions cap at 5.7.1. Can we get an update to those packages to support the latest releases of the hip/rocm ecosystem?

@renjithravindrankannath @srekolam @jordialcaraz

**Comment by renjithravindrankannath** [comment]
We are working on PR [42026 ](https://github.com/spack/spack/pull/42026)to update the recipes for rocm 6.0.

**Comment by srekolam** [comment]
added https://github.com/spack/spack/pull/42544 for rocm-6.0.2 release and Both 6.0 and 6.0.2 release updates are available in spack develop now.
