### ISSUE TITLE
Spack fails to build python on OSX 10.9

### ISSUE THREAD

**Issue by cyrush** [LLNL/spack#42]
I ran into issues building python using spack on OSX 10.9, using either gcc or clang (Xcode 5.1) see below for the gory details, here is one solution to the problem:

If I explicitly set the MACOSX_DEPLOYMENT_TARGET env var to my OSX version (10.9), I avoid the problem. Given this solution, I am not sure if this is something that should go into the spack python package script, or if it could be resolved better in your compiler wrappers.  In build_visit, we always set the osx deployment target to avoid issues with various libraries - it may be good practice also to do so in the spack compiler wrappers. 

Here is the main symptom that occurs: python’s configure checks fail and report the size of all of the integer types :

checking for uid_t in sys/types.h... yes
checking for uint32_t... yes
checking for uint32_t... yes
checking for uint64_t... yes
checking for uint64_t... yes
checking for int32_t... yes
checking for int32_t... yes
checking for int64_t... yes
checking for int64_t... yes
checking for ssize_t... yes
checking size of int... 0
checking size of long... 0
checking size of void *... 0
checking size of short... 0
checking size of float... 0
checking size of double... 0
checking size of fpos_t... 0
checking size of size_t... configure: error: in `/private/var/folders/wj/jjhjt_0d3kg1vmk56d5bq_38001kr8/T/spack-stage/spack-stage-r5wJGI/Python-2.7.8':
configure: error: cannot compute sizeof (size_t)
See `config.log' for more details
==> Error: command './configure --prefix=/Users/harrison37/Work/uberenv/spack/opt/macosx_10.9_x86_64/gcc@4.2.1/python@2.7.8 --without-gcc --enable-shared' returned error code 77

**Comment by mathstuf** [comment]
I'm having no problem with Python2 or Python3 on OS X 10.10 (with Xcode 7.2.1).

**Comment by cyrush** [comment]
Looking at the current python spack package -- MACOSX_DEPLOYMENT_TARGET is now set. That was the key to avoiding this issue, so think it is now resolved.

**Comment by tgamblin** [comment]
@mathstuf: Should we hard-code the deployment target to 10.6, or take the current OS version (from `platform.mac_ver()`)?  I think starting with El Capitan we can't do that and support newer C++ features.  So we should probably auto-set it to the latest -- I believe this is what Homebrew does.

**Comment by cyrush** [comment]
@tgamblin  - this is the approach I am using in driver code that calls spack:

    if "darwin" in platform.system().lower():
        dep_tgt = platform.mac_ver()[0]
        dep_tgt = dep_tgt[:dep_tgt.rfind(".")]
        print "[setting MACOSX_DEPLOYMENT_TARGET to %s]" % dep_tgt
        env["MACOSX_DEPLOYMENT_TARGET"] = dep_tgt

**Comment by tgamblin** [comment]
@cyrush: I think Spack should probably set that automatically in the build environment.

@mathstuf @eschnett: do you see any problem with moving `MACOSX_DEPLOYMENT_TARGET` up a level to the build environment so that package authors do not have to add it?

**Comment by mathstuf** [comment]
It looks to be well supported, so moving it up seems sensible. What its value should be, however…

**Comment by tgamblin** [comment]
My suggestion is what Cyrus recommended: `'.'.join(platform.mac_ver()[0].split('.')[:2])`

**Comment by mathstuf** [comment]
Yeah, if OS X support is for development and not deployment, just using the system's version is probably sufficient. Apple doesn't support downgrades, so that is unlikely to be a problem.

**Comment by tgamblin** [comment]
@mathstuf: for the most part I think Spack is being used on peoples' laptops as a dev proxy of what they do on supercomputers.  I haven't actually been approached by anyone from the labs who wanted to use a shared NFS volume as a deploy environment, either.

@becker33 should have platform support in pretty soon, at which point we can separate out the mac platforms (and even allow cross-compiling by setting this variable).  For now if you want to submit a PR with this hoisted up to the build environment that would be great.

**Comment by adamjstewart** [comment]
I am also unable to build Python on macOS. For me, the only error message I'm seeing is:
```
/System/Library/Frameworks/CoreGraphics.framework/Headers/CGFont.h:53:40: error: initializer element is not constant
```

**Comment by eschnett** [comment]
@adamjstewart What compiler are you using?

**Comment by adamjstewart** [comment]
I was using a Spack-built gcc

**Comment by davydden** [comment]
on the current develop branch python 2.7.1. builds fine for me on macOS with clang.

**Comment by tgamblin** [comment]
A lot of things do not build properly with `gcc` on El Capitan.  I have contemplated in the past making `clang` the preferred compiler on OS X, but I hesitate to do this because it doesn't have good fortran support, and Spack doesn't have the best provenance for mixed compilers.  However, I suspect that most people are going to use the system `clang` + `gfortran`.   What are you guys using, and what's your sense of the common case?  I know @eschnett uses mostly `gcc`.  How about others?  @cyrush?

**Comment by davydden** [comment]
i use `clang`+`fortran`, but i have no problems in the past with building python with gcc as well.

**Comment by davydden** [comment]
i confirm the same build error as @adamjstewart on el capitan with gcc 6
```
In file included from /System/Library/Frameworks/CoreGraphics.framework/Headers/CGContext.h:18:0,
                 from /System/Library/Frameworks/CoreGraphics.framework/Headers/CGBitmapContext.h:9,
                 from /System/Library/Frameworks/CoreGraphics.framework/Headers/CoreGraphics.h:11,
                 from /System/Library/Frameworks/ApplicationServices.framework/Headers/ApplicationServices.h:35,
                 from /System/Library/Frameworks/Carbon.framework/Headers/Carbon.h:24,
                 from Include/pymactoolbox.h:10,
                 from Python/mactoolboxglue.c:27:
/System/Library/Frameworks/CoreGraphics.framework/Headers/CGFont.h:53:40: error: initializer element is not constant
 static const CGFontIndex kCGGlyphMax = kCGFontIndexMax;
                                        ^~~~~~~~~~~~~~~
```

p.s.
>  i have no problems in the past with building python with gcc as well.

here i referred to linux

**Comment by davydden** [comment]
here's the same issue in hashdist https://github.com/hashdist/hashstack/issues/904

**Comment by cyrush** [comment]
I am now less than 1 day into the El Capitan camp, I can tell there will be  lots of fun will be ahead. 

Should we open a new issue for  El Capitan stuff?

To answer @tgamblin's earlier question -- I use clang + gfortran. 

I think for  El Capitan I am going to have spack build gfortran for me.

**Comment by eschnett** [comment]
On OS X, I use the system Clang to build my own GCC, then I tell Spack about this GCC. From then on, I build everything with this GCC.

This fails with packages such as Python that don't build with GCC, due to the reasons described above.

**Comment by gartung** [comment]
Hah, I found this with a google search for the size_t error. 
Passing  MACOSX_DEPLOYMENT_TARGET=10.11 
option to ./configure got me passed that error. 
I avoided the header errors in mactoolbox glue by disabling it with --disable-toolbox-glue. Its not optimal but our software doesn't use mactoolboxglue.

**Comment by davydden** [comment]
since https://github.com/LLNL/spack/pull/1680 was merged as https://github.com/LLNL/spack/commit/e6dc448f1843078f922d9ff018cc4bd0c9a19967, can we close this issue?

**Comment by tgamblin** [comment]
@citibeth?

**Comment by tgamblin** [comment]
whoops sorry -- meant @cyrush?

**Comment by cyrush** [comment]
yes, sorry for the delay
