### ISSUE TITLE
boost checksum error

### ISSUE THREAD

**Issue by vsoch** [LLNL/spack#42001]
For the build here: https://github.com/flux-framework/spack/actions/runs/7455858988/job/20286295396

It looks like the boost checksum is no good? It could be that the server is down and it's returning an HTML page. 
Note that we aren't caching anything.

```console
[+] /usr (external git-2.43.0-jggjw7rb62gwv2slwa2z4emez3g3sect)
==> Installing boost-1.84.0-y5y6fjw5uov7chihg4kiiwpie3c4diqj [10/80]
==> No binary for boost-1.84.0-y5y6fjw5uov7chihg4kiiwpie3c4diqj found: installing from source
==> Warning: The contents of /tmp/runner/spack-stage/spack-stage-boost-1.84.0-y5y6fjw5uov7chihg4kiiwpie3c4diqj/boost_1_84_0.tar.bz2 look like HTML.  Either the URL you are trying to use does not exist or you have an internet gateway issue.  You can remove the bad archive using 'spack clean <package>', then try again using the correct URL.
```
Let me know what we might try, or if it's something we need to wait for a fix here.

**Comment by haampie** [comment]
It's an issue with a server, the checksum is correct, the server sometimes returns html as the warning indicates.

Spack should mirror the tarball sooner or later, then the issue is gone.

**Comment by vsoch** [comment]
Agree that does appear to be the issue - and it's working again. https://github.com/flux-framework/spack/actions.

I'm not sure there is much we can do, it's unfortunate the flakiness of one URL can break entire builds. Thanks @haampie.
