### ISSUE TITLE
`quantum-espresso` with `+elpa+openmp` logic

### ISSUE THREAD

**Issue by lorisercole** [LLNL/spack#42013]
### Steps to reproduce the issue

```console
$ spack spec -I quantum-espresso+elpa+openmp+scalapack ^elpa+openmp
Input spec
--------------------------------
 -   quantum-espresso+elpa+openmp+scalapack
 -       ^elpa+openmp

Concretized
--------------------------------
 -   quantum-espresso@7.2%gcc@12.3.0+elpa~environ+epw~fox~gipaw~libxc+mpi~nvtx+openmp+patch~qmcpack+scalapack build_system=generic hdf5=none arch=linux-ubuntu22.04-skylake
[+]      ^elpa@2023.05.001%gcc@12.3.0~autotune~cuda+mpi+openmp~rocm build_system=autotools arch=linux-ubuntu22.04-skylake
[e]          ^gmake@4.3%gcc@12.3.0~guile build_system=generic patches=599f134 arch=linux-ubuntu22.04-skylake
[e]          ^libtool@2.4.6%gcc@12.3.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]          ^python@3.11.6%gcc@12.3.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=13fa8bf,b0615b2,ebdca64,f2fd060 arch=linux-ubuntu22.04-skylake
[+]              ^bzip2@1.0.8%gcc@12.3.0~debug~pic+shared build_system=generic arch=linux-ubuntu22.04-skylake
[e]                  ^diffutils@3.8%gcc@12.3.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]              ^expat@2.5.0%gcc@12.3.0+libbsd build_system=autotools arch=linux-ubuntu22.04-skylake
[+]                  ^libbsd@0.11.7%gcc@12.3.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]                      ^libmd@1.0.4%gcc@12.3.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]              ^gdbm@1.23%gcc@12.3.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]              ^gettext@0.22.4%gcc@12.3.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-ubuntu22.04-skylake
[+]                  ^libiconv@1.17%gcc@12.3.0 build_system=autotools libs=shared,static arch=linux-ubuntu22.04-skylake
[+]                  ^libxml2@2.10.3%gcc@12.3.0+pic~python+shared build_system=autotools arch=linux-ubuntu22.04-skylake
[e]                  ^tar@1.34%gcc@12.3.0 build_system=autotools zip=pigz arch=linux-ubuntu22.04-skylake
[+]              ^libffi@3.4.4%gcc@12.3.0 build_system=autotools patches=070b1f3 arch=linux-ubuntu22.04-skylake
[+]              ^libxcrypt@4.4.35%gcc@12.3.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-ubuntu22.04-skylake
[+]              ^ncurses@6.4%gcc@12.3.0~symlinks+termlib abi=none build_system=autotools arch=linux-ubuntu22.04-skylake
[+]              ^openssl@3.1.3%gcc@12.3.0~docs+shared build_system=generic certs=mozilla arch=linux-ubuntu22.04-skylake
[+]                  ^ca-certificates-mozilla@2023-05-30%gcc@12.3.0 build_system=generic arch=linux-ubuntu22.04-skylake
[+]              ^pkgconf@1.9.5%gcc@12.3.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]              ^readline@8.2%gcc@12.3.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu22.04-skylake
[+]              ^sqlite@3.43.2%gcc@12.3.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-ubuntu22.04-skylake
[+]              ^util-linux-uuid@2.38.1%gcc@12.3.0 build_system=autotools arch=linux-ubuntu22.04-skylake
[+]              ^xz@5.4.1%gcc@12.3.0~pic build_system=autotools libs=shared,static arch=linux-ubuntu22.04-skylake
[+]              ^zlib-ng@2.1.5%gcc@12.3.0+compat+opt build_system=autotools arch=linux-ubuntu22.04-skylake
[+]      ^fftw@3.3.10%gcc@12.3.0+mpi+openmp~pfft_patches build_system=autotools precision=double,float arch=linux-ubuntu22.04-skylake
[+]      ^gcc-runtime@12.3.0%gcc@12.3.0 build_system=generic arch=linux-ubuntu22.04-skylake
[e]      ^git@2.34.1%gcc@12.3.0+man+nls+perl+subtree~svn~tcltk build_system=autotools arch=linux-ubuntu22.04-skylake
[e]      ^m4@1.4.18%gcc@12.3.0+sigsegv build_system=autotools patches=3877ab5,fc9b616 arch=linux-ubuntu22.04-skylake
[+]      ^netlib-scalapack@2.2.0%gcc@12.3.0~ipo~pic+shared build_system=cmake build_type=Release generator=make patches=072b006,1c9ce5f,244a9aa arch=linux-ubuntu22.04-skylake
[e]          ^cmake@3.22.1%gcc@12.3.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-ubuntu22.04-skylake
[+]      ^openblas@0.3.25%gcc@12.3.0~bignuma~consistent_fpcsr+fortran~ilp64+locking+pic+shared build_system=makefile symbol_suffix=none threads=openmp arch=linux-ubuntu22.04-skylake
[+]          ^perl@5.38.0%gcc@12.3.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-ubuntu22.04-skylake
[+]              ^berkeley-db@18.1.40%gcc@12.3.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu22.04-skylake
[e]      ^openmpi@4.1.2%gcc@12.3.0~atomics~cuda~cxx~cxx_exceptions~gpfs~internal-hwloc~internal-libevent~internal-pmix~java~legacylaunchers~lustre~memchecker~openshmem~orterunprefix~romio+rsh~singularity~static+vt+wrapper-rpath build_system=autotools fabrics=none schedulers=none arch=linux-ubuntu22.04-skylake
```

### Error message

<details><summary>Error message</summary>

<pre>
==> Installing quantum-espresso-7.2-gh6wqrvrgvnjqfpreyhxrzc24l7r6w7k [30/30]
==> No binary for quantum-espresso-7.2-gh6wqrvrgvnjqfpreyhxrzc24l7r6w7k found: installing from source
==> Using cached archive: /home/lercole/src/spack-dev/var/spack/cache/_source-cache/archive/b3/b348a4a7348b66a73545d9ca317a2645755c98d343c1cfe8def475ad030808c0.tar.gz
==> No patches needed for quantum-espresso
==> quantum-espresso: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j12' 'all' 'epw'

3 errors found in build log:
     197     hint:
     198     hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
     199     hint: 'development'. The just-created branch can be renamed via this command:
     200     hint:
     201     hint:      git branch -m <name>
     202     /bin/sh: 1: cd: can't cd to ../W90
  >> 203     cp: cannot create regular file '../W90/make.inc': No such file or directory
  >> 204     make[1]: *** [plugins_makefile:98: configure-w90] Error 1
     205     make[1]: *** Waiting for unfinished jobs....
     206     /usr/bin/mpif90 -O3 -g -fallow-argument-mismatch -fopenmp -cpp -fopenmp -D__FFTW3 -D__MPI -D__SCALAPACK -D__ELPA  -I/tmp/lercole/spack-stage/spack-stage-quantum-espresso-7.2-gh6wqrvrgvnjqfpreyhxrzc24l7r6w7k/spack-src//external/devxlib/src -I. -I/tmp/lercole/spack-stage/spack-stage-quantum-espresso-7.2-gh6wqrvrgvnjqfpreyhxrzc24l7r6w
             7k/spack-src//include -I/home/lercole/src/spack-dev/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/fftw-3.3.10-rvdcxs5iywzcwzrxzwzamexdke5czoki/include -I/home/lercole/src/spack-dev/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/elpa-2023.05.001-c6zhi53fcspwgqvahhjafcsnuwpftlqb/include/elpa_openmp-2023.05.001/modules  -c fftw_inter
             faces.f90
     207     Initialized empty Git repository in /tmp/lercole/spack-stage/spack-stage-quantum-espresso-7.2-gh6wqrvrgvnjqfpreyhxrzc24l7r6w7k/spack-src/external/mbd/.git/
     208     f951: Warning: Nonexistent include directory '/tmp/lercole/spack-stage/spack-stage-quantum-espresso-7.2-gh6wqrvrgvnjqfpreyhxrzc24l7r6w7k/spack-src//external/devxlib/src' [-Wmissing-include-dirs]
     209     /usr/bin/mpicc -O3 -D__FFTW3 -D__MPI -D__SCALAPACK -D__ELPA -I. -I/tmp/lercole/spack-stage/spack-stage-quantum-espresso-7.2-gh6wqrvrgvnjqfpreyhxrzc24l7r6w7k/spack-src//include -I/home/lercole/src/spack-dev/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/fftw-3.3.10-rvdcxs5iywzcwzrxzwzamexdke5czoki/include -I/home/lercole/src/spack-d
             ev/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/elpa-2023.05.001-c6zhi53fcspwgqvahhjafcsnuwpftlqb/include/elpa_openmp-2023.05.001/modules   -c eval_infix.c
     210     /usr/bin/mpif90 -O3 -g -fallow-argument-mismatch -fopenmp -cpp -fopenmp -D__FFTW3 -D__MPI -D__SCALAPACK -D__ELPA  -I/tmp/lercole/spack-stage/spack-stage-quantum-espresso-7.2-gh6wqrvrgvnjqfpreyhxrzc24l7r6w7k/spack-src//external/devxlib/src -I. -I/tmp/lercole/spack-stage/spack-stage-quantum-espresso-7.2-gh6wqrvrgvnjqfpreyhxrzc24l7r6w
             7k/spack-src//include -I/home/lercole/src/spack-dev/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/fftw-3.3.10-rvdcxs5iywzcwzrxzwzamexdke5czoki/include -I/home/lercole/src/spack-dev/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/elpa-2023.05.001-c6zhi53fcspwgqvahhjafcsnuwpftlqb/include/elpa_openmp-2023.05.001/modules -I. -c find_fr
             ee_unit.f90

     ...

     2164    wannier90-3.1.0/utility/w90vdw/examples/benzene_s_val/ref/benzene_s_val.vdw
     2165    wannier90-3.1.0/utility/w90vdw/examples/benzene_s_val/ref/benzene_s_val.wout
     2166    wannier90-3.1.0/utility/w90vdw/examples/benzene_s_val/ref/benzene_s_val_centres.xyz
     2167    wannier90-3.1.0/utility/w90vdw/w90vdw.f90
     2168    touch uncompress-w90
     2169    make[1]: Leaving directory '/tmp/lercole/spack-stage/spack-stage-quantum-espresso-7.2-gh6wqrvrgvnjqfpreyhxrzc24l7r6w7k/spack-src/install'
  >> 2170    make: *** [Makefile:244: w90] Error 1
     2171    make: *** Waiting for unfinished jobs....
     2172    /usr/bin/mpif90 -O3 -g -fallow-argument-mismatch -fopenmp -cpp -fopenmp -D__FFTW3 -D__MPI -D__SCALAPACK -D__ELPA  -I/tmp/lercole/spack-stage/spack-stage-quantum-espresso-7.2-gh6wqrvrgvnjqfpreyhxrzc24l7r6w7k/spack-src//external/devxlib/src -I. -I/tmp/lercole/spack-stage/spack-stage-quantum-espresso-7.2-gh6wqrvrgvnjqfpreyhxrzc24l7r6w
             7k/spack-src//include -I/home/lercole/src/spack-dev/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/fftw-3.3.10-rvdcxs5iywzcwzrxzwzamexdke5czoki/include -I/home/lercole/src/spack-dev/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/elpa-2023.05.001-c6zhi53fcspwgqvahhjafcsnuwpftlqb/include/elpa_openmp-2023.05.001/modules  -c fft_fwinv.
             f90
     2173    gfortran -O3 -g -fallow-argument-mismatch -fopenmp -cpp -fopenmp -D__FFTW3 -D__MPI -D__SCALAPACK -D__ELPA  -I/tmp/lercole/spack-stage/spack-stage-quantum-espresso-7.2-gh6wqrvrgvnjqfpreyhxrzc24l7r6w7k/spack-src//external/devxlib/src -I. -I/tmp/lercole/spack-stage/spack-stage-quantum-espresso-7.2-gh6wqrvrgvnjqfpreyhxrzc24l7r6w7k/spac
             k-src//include -I/home/lercole/src/spack-dev/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/fftw-3.3.10-rvdcxs5iywzcwzrxzwzamexdke5czoki/include -I/home/lercole/src/spack-dev/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/elpa-2023.05.001-c6zhi53fcspwgqvahhjafcsnuwpftlqb/include/elpa_openmp-2023.05.001/modules   -c mbd_dipole.F90
     2174    /usr/bin/mpif90 -O3 -g -fallow-argument-mismatch -fopenmp -cpp -fopenmp -D__FFTW3 -D__MPI -D__SCALAPACK -D__ELPA  -I/tmp/lercole/spack-stage/spack-stage-quantum-espresso-7.2-gh6wqrvrgvnjqfpreyhxrzc24l7r6w7k/spack-src//external/devxlib/src -I. -I/tmp/lercole/spack-stage/spack-stage-quantum-espresso-7.2-gh6wqrvrgvnjqfpreyhxrzc24l7r6w
             7k/spack-src//include -I/home/lercole/src/spack-dev/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/fftw-3.3.10-rvdcxs5iywzcwzrxzwzamexdke5czoki/include -I/home/lercole/src/spack-dev/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/elpa-2023.05.001-c6zhi53fcspwgqvahhjafcsnuwpftlqb/include/elpa_openmp-2023.05.001/modules -I. -c divide.
             f90
     2175    /usr/bin/mpif90 -O3 -g -fallow-argument-mismatch -fopenmp -cpp -fopenmp -D__FFTW3 -D__MPI -D__SCALAPACK -D__ELPA  -I/tmp/lercole/spack-stage/spack-stage-quantum-espresso-7.2-gh6wqrvrgvnjqfpreyhxrzc24l7r6w7k/spack-src//external/devxlib/src -I. -I/tmp/lercole/spack-stage/spack-stage-quantum-espresso-7.2-gh6wqrvrgvnjqfpreyhxrzc24l7r6w
             7k/spack-src//include -I/home/lercole/src/spack-dev/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/fftw-3.3.10-rvdcxs5iywzcwzrxzwzamexdke5czoki/include -I/home/lercole/src/spack-dev/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/elpa-2023.05.001-c6zhi53fcspwgqvahhjafcsnuwpftlqb/include/elpa_openmp-2023.05.001/modules -I. -c error_h
             andler.f90
     2176    /usr/bin/mpif90 -O3 -g -fallow-argument-mismatch -fopenmp -cpp -fopenmp -D__FFTW3 -D__MPI -D__SCALAPACK -D__ELPA  -I/tmp/lercole/spack-stage/spack-stage-quantum-espresso-7.2-gh6wqrvrgvnjqfpreyhxrzc24l7r6w7k/spack-src//external/devxlib/src -I. -I/tmp/lercole/spack-stage/spack-stage-quantum-espresso-7.2-gh6wqrvrgvnjqfpreyhxrzc24l7r6w
             7k/spack-src//include -I/home/lercole/src/spack-dev/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/fftw-3.3.10-rvdcxs5iywzcwzrxzwzamexdke5czoki/include -I/home/lercole/src/spack-dev/opt/spack/linux-ubuntu22.04-skylake/gcc-12.3.0/elpa-2023.05.001-c6zhi53fcspwgqvahhjafcsnuwpftlqb/include/elpa_openmp-2023.05.001/modules -I. -c mp_band
             s_util.f90

See build log for details:
  /tmp/lercole/spack-stage/spack-stage-quantum-espresso-7.2-gh6wqrvrgvnjqfpreyhxrzc24l7r6w7k/spack-build-out.txt
</pre></details>

This build failure is not fully deterministic: if one runs the installation in serial, or with few threads (e.g. `spack install -j 4`), it runs fine. WIth 8 threads it may fail.

### Information on your system

* **Spack:** 0.22.0.dev0 (fe18b9bda23756e793171dcd8edb56cb723f9405)
* **Python:** 3.10.10
* **Platform:** linux-ubuntu22.04-skylake
* **Concretizer:** clingo

### Additional information

NOTE: The reason I explicitly request `^elpa+openmp` is to make sure that the concretizer uses this variant.
According to `quantum-espresso`'s recipe, then it will be forced to use the `generic` build system, which may fail.

However, if I just asked `quantum-espresso +elpa+openmp+scalapack`, the concretized spec would have `^elpa~openmp`, because according to the recipe, the `cmake` build system (default) only supports this variant.
This logic seems incorrect to me.
**If we ask the variant `+openmp`, is `^elpa+openmp` mandatory or not?**

In the current implementation
https://github.com/spack/spack/blob/62c7dfc6640f903a2388eae6c9f779303f516a4b/var/spack/repos/builtin/packages/quantum-espresso/package.py#L125-L130
`^elpa+openmp` will be built only if the build system is `generic`. Otherwise, with `cmake`, `^elpa~openmp` will be used even if we requested `+openmp`.

If Cmake really does not support `^elpa+openmp`, a `conflict` should be stated, for example like this:
```python
    with when("+elpa"):
        # CMake builds only support elpa without openmp
        conflicts("build_system=cmake", when="+openmp")

        depends_on("elpa+openmp", when="+openmp")
        depends_on("elpa~openmp", when="~openmp")
```
Let me know what you think.

@ye-luo @bellenlau @tgorni

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by lorisercole** [comment]
> If we ask the variant `+openmp`, is `^elpa+openmp` mandatory or not?

I guess so. In fact, `quantum-espresso@7.3%gcc@13.2+elpa+libxc+openmp+scalapack build_system=cmake ^elpa~openmp` fails with this error:
```make
     10178    cd /mnt/nvme/tmpscratch/root/spack-stage/spack-stage-quantum-espresso-7.3-6d7openhctyxt4joz24s5vsxywaew5wj/spack-build-6d7open/EPW && /opt/hpcx-v2.15-gcc-MLNX_OFED_LINUX-5-re
              dhat8-cuda12-gdrcopy2-nccl2.17-x86_64/ompi/bin/mpif90 -DHAVE_MALLINFO -DOMPI_SKIP_MPICXX -DQE_NO_CONFIG_H -D__ELPA -D__FFTW3 -D__MPI -D__SCALAPACK -I/mnt/scratch/root/spack-s
              tage/spack-stage-quantum-espresso-7.3-6d7openhctyxt4joz24s5vsxywaew5wj/spack-src/include -I/mnt/nvme/tmpscratch/root/spack-stage/spack-stage-quantum-espresso-7.3-6d7openhctyx
              t4joz24s5vsxywaew5wj/spack-build-6d7open/EPW/mod/qe_epw -I/mnt/nvme/tmpscratch/root/spack-stage/spack-stage-quantum-espresso-7.3-6d7openhctyxt4joz24s5vsxywaew5wj/spack-build-
              6d7open/external/mod/qe_wannier90 -I/mnt/nvme/tmpscratch/root/spack-stage/spack-stage-quantum-espresso-7.3-6d7openhctyxt4joz24s5vsxywaew5wj/spack-build-6d7open/Modules/mod/qe
              _modules -I/mnt/nvme/tmpscratch/root/spack-stage/spack-stage-quantum-espresso-7.3-6d7openhctyxt4joz24s5vsxywaew5wj/spack-build-6d7open/upflib/mod/qe_upflib -I/mnt/nvme/tmpscr
              atch/root/spack-stage/spack-stage-quantum-espresso-7.3-6d7openhctyxt4joz24s5vsxywaew5wj/spack-build-6d7open/upflib/mod/qe_xml -I/mnt/nvme/tmpscratch/root/spack-stage/spack-st
              age-quantum-espresso-7.3-6d7openhctyxt4joz24s5vsxywaew5wj/spack-build-6d7open/UtilXlib/mod/qe_utilx -I/mnt/nvme/tmpscratch/root/spack-stage/spack-stage-quantum-espresso-7.3-6
              d7openhctyxt4joz24s5vsxywaew5wj/spack-build-6d7open/UtilXlib/mod/qe_utilx_c -I/mnt/nvme/tmpscratch/root/spack-stage/spack-stage-quantum-espresso-7.3-6d7openhctyxt4joz24s5vsxy
              waew5wj/spack-build-6d7open/LR_Modules/mod/qe_lr_modules -I/mnt/nvme/tmpscratch/root/spack-stage/spack-stage-quantum-espresso-7.3-6d7openhctyxt4joz24s5vsxywaew5wj/spack-build
              -6d7open/PHonon/mod/qe_phonon_ph -I/mnt/nvme/tmpscratch/root/spack-stage/spack-stage-quantum-espresso-7.3-6d7openhctyxt4joz24s5vsxywaew5wj/spack-build-6d7open/PW/mod/qe_pw -I
              /mnt/nvme/tmpscratch/root/spack-stage/spack-stage-quantum-espresso-7.3-6d7openhctyxt4joz24s5vsxywaew5wj/spack-build-6d7open/FFTXlib/src/mod/qe_fftx -I/mnt/nvme/tmpscratch/roo
              t/spack-stage/spack-stage-quantum-espresso-7.3-6d7openhctyxt4joz24s5vsxywaew5wj/spack-build-6d7open/XClib/mod/qe_xclib -fallow-argument-mismatch -O3 -DNDEBUG -O3 -Jmod/qe_epw
               -cpp -c /mnt/scratch/root/spack-stage/spack-stage-quantum-espresso-7.3-6d7openhctyxt4joz24s5vsxywaew5wj/spack-src/EPW/src/epw_init.f90 -o CMakeFiles/qe_epw.dir/src/epw_init.
              f90.o
     10179    /mnt/scratch/root/spack-stage/spack-stage-quantum-espresso-7.3-6d7openhctyxt4joz24s5vsxywaew5wj/spack-src/EPW/src/qdabs.f90:1814:9:
     10180
     10181     1814 |     USE elpa
     10182          |         1
  >> 10183    Fatal Error: Cannot open module file 'elpa.mod' for reading at (1): No such file or directory
     10184    compilation terminated.
  >> 10185    make[2]: *** [EPW/CMakeFiles/qe_epw.dir/build.make:754: EPW/CMakeFiles/qe_epw.dir/src/qdabs.f90.o] Error 1
```

**Comment by lorisercole** [comment]
> I guess so. In fact, quantum-espresso@7.3%gcc@13.2+elpa+libxc+openmp+scalapack build_system=cmake ^elpa~openmp fails with this error:

Actually this error always happens when building with `+elpa ~openmp build_system=cmake`, no matter which `elpa` variant I use. The problem is `cmake`, with the `generic` build system it works.

**Comment by ye-luo** [comment]
QE side problem. Will fix it. There will be a new 7.3.1 release end of this month addressing multiple issues.

**Comment by ye-luo** [comment]
QE side has been fixed. You may try building develop.
Regarding your original question.
```
However, if I just asked quantum-espresso +elpa+openmp+scalapack, the concretized spec would have ^elpa~openmp, because according to the recipe, the cmake build system (default) only supports this variant.
This logic seems incorrect to me.
If we ask the variant +openmp, is ^elpa+openmp mandatory or not?
```
QE uses an iterative solver which invokes an eigensolver. Usually such matrices are not large, several thousands of bands at maximum. For this reason, I only saw performance loss in threaded ELPA. If you have data proving threaded ELPA helps, we can fix QE CMake and then enable it in spack.

**Comment by lorisercole** [comment]
> QE uses an iterative solver which invokes an eigensolver. Usually such matrices are not large, several thousands of bands at maximum. For this reason, I only saw performance loss in threaded ELPA. If you have data proving threaded ELPA helps, we can fix QE CMake and then enable it in spack.

I see, thanks for your answer @ye-luo! I'll try to build develop to see if the issue went away.
Then a last point, to summerize: according to the [recipe](https://github.com/spack/spack/blob/62c7dfc6640f903a2388eae6c9f779303f516a4b/var/spack/repos/builtin/packages/quantum-espresso/package.py#L125-L130), if `cmake` is used, `^elpa~openmp` will always be selected.
However, if one used the `generic` build system, does it make sense to use `^elpa~openmp` even if QE is built with `+openmp`? Would that work?
Thanks

**Comment by ye-luo** [comment]
@lorisercole I relaxed the constraint. https://github.com/spack/spack/pull/42322
