### ISSUE TITLE
clingo-bootstrap source tarfile is not constant

### ISSUE THREAD

**Issue by cferenba** [LLNL/spack#42038]
I've been experimenting with creating bootstrap mirrors and I've discovered something odd.  I created source mirrors three times in the past several days, and each time the clingo-bootstrap tarfile is slightly different (note the different sizes):
```
-rw-rw---- 1 cferenba cferenba 3177585 Jan 10 12:27 bootstrap.test/bootstrap_cache/clingo-bootstrap/clingo-bootstrap-spack.tar.gz
-rw-rw---- 1 cferenba cferenba 3178065 Jan  9 14:27 bootstrap/bootstrap_cache/clingo-bootstrap/clingo-bootstrap-spack.tar.gz
-rw-rw---- 1 cferenba cferenba 3176644 Jan  5 17:47 bootstrap.old/bootstrap_cache/clingo-bootstrap/clingo-bootstrap-spack.tar.gz
```
In each case I used the same spack command (only changing the target directory name):
```
spack bootstrap mirror ~/Downloads/bootstrap.test
```
It seems like this shouldn't be happening.  In the clingo package.py file the version definition is this:
```
    version("spack", commit="2a025667090d71b2c9dce60fe924feb6bde8f667", submodules=True)
```
Since the commit hash is constant, the resulting tarfile ought to be constant too.

Am I doing something wrong, or is there something here that needs fixing?  This matters to me because I'm looking to set up a project bootstrap mirror that is updated automatically when any of the files changes, but that will get confusing if a file is getting spurious changes like this.

This is using 0.20.0.dev0, but I'm seeing the same with 0.21.0.

**Comment by haampie** [comment]
It's making an archive from a git commit, I don't think care was taking to make it reproducible.

Might be a matter of order (you can verify by diffing `tar tf <file>`) or time stamps (`tar tvf <file>`)

**Comment by cferenba** [comment]
Did a little more digging, and the difference appears to be the timestamps.  I suppose that makes sense.  If Spack is fetching a numbered version, it retrieves a single once-for-all-time tarball.  But if it's fetching a commit, it has to create a local clone and tar that up, and the local clone will have the current timestamp.

It looks like there might be a way around this using `git archive`, but probably not worth the trouble.  I'll just change my workflow so that the varying tarfiles are not an issue.
