### ISSUE TITLE
Need advice on unpacking cmake project thats' in a tar.gz that's inside a .zip.

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#4206]
I suspect that this has been solved before but I haven't found any direct hits.

I'm putting together a package for [bcl2fastq2](https://support.illumina.com/downloads/bcl2fastq-conversion-software-v2-18.html).

The [source link](https://support.illumina.com/content/dam/illumina-support/documents/downloads/software/bcl2fastq/bcl2fastq2-v2-18-0-12-tar.zip) points to a zip file that Spack unpacks for me into:

```
var/spack/stage/bcl2fastq2-2fastq2-v2-18-0-12-t3cez4v7rtnp3hidzsyf5eaaq73dla5m/spack-expanded-archive
```

That directory contains a gzipped tarball:

```
var/spack/stage/bcl2fastq2-2fastq2-v2-18-0-12-t3cez4v7rtnp3hidzsyf5eaaq73dla5m/spack-expanded-archive/bcl2fastq2-v2.18.0.12.tar.gz
```

I need to unpack that tarball, it contains a `src` dir.  Illumina's build instructions say that I should `cd` into that directory and run configure.  I'm planning to let/help `CMakePackage` handle that final step.

The install method of the turbomole package [does a little dance in the install method](https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/turbomole/package.py#L82) untar-ing something and then doing everything inside a `with working_dir(...`.

Are there any other existing examples of packages for which the source is doubly archived?

Would it be cleaner to extend/override `fetch` or ....

Thanks in advance!

**Comment by adamjstewart** [comment]
> Need advice on unpacking cmake project that's in a tar.gz that's inside a .zip.

Wtf? Why would they do that?? This sounds like something that @svenevs would do...

> Would it be cleaner to extend/override `fetch`

I like this approach. I'm on the train right now so unfortunately I can't find an example or offer suggestions on how to do this. Good luck!

**Comment by tgamblin** [comment]
Spack doesn't know what's in the expanded archive, so I think you currently have to do what `turbomole` does.  I wouldn't override `fetch` -- expanding sources is handled in `do_stage()`, not `do_fetch()`, anyway (the `stage` step is basically expand + cd into the directory).

One annoyance with `turbomole`'s approach is that spack's build process (partially) looks like this:

1. fetch
2. stage
3. patch
4. build
5. install

But if you do what turbomole does, your source isn't actually expanded for patching until somewhere inside install, so you have to do your patching in there too.  Do you need to patch things that are inside the zip file?  If so, we could either think about making fetch and stage (or at least stage) a bit more overridable, so that you can get to the working directory you really want and still use Spack's builtin patch functionality.    That may be difficult because `self.stage` is already the `Stage` object associated with a `Package`.

Actually, on second thought, we may not need anything quite that drastic.  You could just do this with decorators and @alalazo's awesome build pipeline support:

```python
@run_after('stage')
def cd_into_real_zip_directory(self):
    # change directory to wherever that zip is and unzip it
    # cd into next level of russian doll distro
    # repeat until you find the little doll
```

Would that work?  There may be some extra `chdirs` in there that I'm forgetting, but I *believe* this would make it so that `patch()` and `install()` end up running in the nested directory like you want.

**Comment by hartzell** [comment]
@tgamlin -- thanks for the gentle tap with the clue bat.  Sounds like that's just what I was looking for!

**Comment by hartzell** [comment]
> Wtf? Why would they do that??

I could tell you, but then I'd have to etc...

**Comment by hartzell** [comment]
@tgamlin, @alalazo -- When I do this:

```python
    @run_after('stage')
    def cd_into_real_toplevel_dir(self):
        tar = which('tar')
        tar('-x', '-z', '-f', 'bcl2fastq2-v2.18.0.12.tar.gz')
        chdir('bcl2fastq')
```

I get this on e.g. `spack clean bcl2fastq`:

```
==> Error: 'NoneType' object has no attribute 'copy'
```

I think that what's happening is that decorators (attributes?) like `@run_after` only work on things that are listed in a package subclasses `phases` list, and for `cmake` that's just:

```
  #: Phases of a CMake package
  phases = ['cmake', 'build', 'install']
```

For grins, I'll see if I can shim what I need into a `run_before('cmake')`....

**Comment by hartzell** [comment]
This bit:

```python
    root_cmakelists_dir = 'bcl2fastq/src'

    @run_before('cmake')
    def untar_inner_tarball(self):
        mkdirp('spack-build')
        chdir('spack-build')
        tar = which('tar')
        tar('-x', '-z', '-f', '../bcl2fastq2-v2.18.0.12.tar.gz')
```

seems to have gotten me through the speedbump.  I'm having other issues, but that's why they call it "work", right.

Thanks for the pointers.

**Comment by alalazo** [comment]
@hartzell @tgamblin The decorator `@run_before` only knows of the phases of the build system. It's not aware of all the Spack pipeline.

**Comment by hartzell** [comment]
@alalazo, @tgamblin -- It looks like I'm going to have to patch their build process.

I think that my best approach is going to be to override/extend/monkey-patch the stage phase of the pipeline.

Can you point me at prior art?  If not, any other hints would be appreciated.

**Comment by alalazo** [comment]
@hartzell What do you need to do? Add to the current stage behavior, or modify it?

**Comment by hartzell** [comment]
The current code unzips the zipfile, revealing the tarball.

I think that I need to unzip the tarball and then arrange for `self.stage.source_path` to point into the untarred content instead of where it currently seems to point (the unzipped content).

As a first cut (a no-op, before I start adding additional behavior), I've tried adding this to the Bcl2fastq2 class:

```python
def stage(self):
    return super(Bcl2fastq2, self).stage()
```

But it results in this:

```
==> Error: 'function' object has no attribute 'destroy'
```

**Comment by hartzell** [comment]
I'm trying to head towards something like the "Alter Before or After" section of the [Learn Python the Hard Way](https://learnpythonthehardway.org/book/ex44.html) example.

Overriding it entirely seems like too much work....

**Comment by alalazo** [comment]
@hartzell That's what I would have suggested, if you need to add to the current behavior,

**Comment by hartzell** [comment]
Am I perhaps running afoul of the fact that package.py's stage method (line 742 of `lib/spack/spack/package.py`) has an `@property decorator?

**Comment by hartzell** [comment]
Wonder if I'd ever get *this* past those pesky reviewers?

```python
    def _make_stage(self):
        return super(Bcl2fastq2, self)._make_stage()
```

It seems to work as a no-op.  TBD whether it is the crack into which I need to drive my wedge.

**Comment by alalazo** [comment]
Looking at what you have written above, and considering that `PackageBase` stage does:
```python
def do_stage(self, mirror_only=False):
    """Unpacks the fetched tarball, then changes into the expanded tarball
       directory."""
    if not self.spec.concrete:
        raise ValueError("Can only stage concrete packages.")

    self.do_fetch(mirror_only)
    self.stage.expand_archive()
    self.stage.chdir_to_source()
```
I would try to modify the behavior of `stage.expand_archive()`. Note that I am not suggesting this as a good design choice, just as a tentative sniper hack that does the job for just one package.

Now `self.stage` creates lazily `self._stage`. So one possibility to explore, to see if it can lead to just a few lines of code in your package, is to do something like:
```python
def do_stage(self, mirror_only=False):
    self.stage.expand_archive = ... # Monkey patch here
    super(YourPackage, self).do_stage(mirror_only)    
```
This should reduce the scope of what you need to do, and let you operate just on:
```python
# Stage.expand_archive in stage.py
def expand_archive(self):
    """Changes to the stage directory and attempt to expand the downloaded
    archive.  Fail if the stage is not set up or if the archive is not yet
    downloaded."""
    archive_dir = self.source_path
    if not archive_dir:
        self.fetcher.expand()
        tty.msg("Created stage in %s" % self.path)
    else:
        tty.msg("Already staged %s in %s" % (self.name, self.path))
```
probably you can get-by writing a decorator for this and applying it manually above, like:
```python
self.stage.expand_archive = decorator(self.stage.expand_archive)
```
Hope that helps...

**Comment by hartzell** [comment]
@tgamblin (and the rest of you who've built such a beautiful thing) -- I'm sorry for what I'm about to suggest....

Perhaps what I need to do is add behavior to `lib/spck/spack/util/compression.py` so that it can handle (be extended to handle, be desecrated to handle, ...) the russian doll scenario.

It's not clear how I'd do that though:

1. where would I hook in to the package.py; and
2. this function seems to return Executables [SIC] and I don't see any good way to chain them....

**Comment by hartzell** [comment]
> Hope that helps...

Looks golden.  I think I need a peanut-butter and jelly sandwich before I dive back in.

Thanks,

**Comment by hartzell** [comment]
[OMG](https://www.redbubble.com/people/evahhamilton/works/15345302-i-love-programming?grid_pos=6&p=sticker&rbs=0073dde7-8c20-42d5-aee3-fc56170465b0)....

```python
    def unSNAFU(self, f):
        def wrap():
            tty.warn("BEFORE")
            f()
            tty.warn("AFTER")
        return wrap

    def do_stage(self, mirror_only=False):
        self.stage.expand_archive = self.unSNAFU(self.stage.expand_archive)
        super(Bcl2fastq2, self).do_stage(mirror_only)
```

And it seems to give me the hook that I need.  I'll have to be a little careful to do something intelligent when called repeatedly, but...  OMG....

```
$ (module purge; spack stage bcl2fastq2)
==> Using cached archive: /home/hartzelg/tmp/spack-bcl2fastq/var/spack/cache/bcl2fastq2/bcl2fastq2-v2-18-0-12.zip
==> Warning: BEFORE
==> Staging archive: /home/hartzelg/tmp/spack-bcl2fastq/var/spack/stage/bcl2fastq2-v2-18-0-12-z23psqczy3q5musnesmvvpwanosot365/bclv2-18-0-12-tar.zip
==> Created stage in /home/hartzelg/tmp/spack-bcl2fastq/var/spack/stage/bcl2fastq2-v2-18-0-12-z23psqczy3q5musnesmvvpwanosot365
==> Warning: AFTER
$ (module purge; spack stage bcl2fastq2)
==> Using cached archive: /home/hartzelg/tmp/spack-bcl2fastq/var/spack/cache/bcl2fastq2/bcl2fastq2-v2-18-0-12.zip
==> Warning: BEFORE
==> Already staged bcl2fastq2-v2-18-0-12-z23psqczy3q5musnesmvvpwanosot365 in /home/hartzelg/tmp/spack-bcl2fastq/var/spack/stage/bcl2fastq2-v2-18-0-12-z23psqczy3q5musnesmvvpwanosot365
==> Warning: AFTER
```

**Comment by hartzell** [comment]
For posteritie's sake, here's what I've ended up with.  It'll change between now and finishing up the package for bcl2fastq2 (e.g. no hardcoded version numbers, ...), but this particular Issue is no longer an issue.

```python
class Bcl2fastq2(CMakePackage):
    """The bcl2fastq2 Conversion Software converts base
       call (BCL) files from a sequencing run into FASTQ
       files."""

    # [...]

    # Illumina tucks the source inside a gzipped tarball inside a zip file.
    # The normal Spack expansion bits unzip's the zip file.
    # This function untars the tarball after Spack's done it's bit.
    def de_SNAFU(self, f):
        def wrap():
            tty.msg("Bcl2fastq2 expand_archive hack in progress")
            f()
            if os.path.isdir('bcl2fastq'):
                tty.msg("Already hacked up the bcl2fastq directory")
            else:
                shutil.move('spack-expanded-archive/bcl2fastq2-v2.18.0.12.tar.gz', '.')
                os.rmdir('spack-expanded-archive')
                tar=which('tar')
                tar('-xf', 'bcl2fastq2-v2.18.0.12.tar.gz')
            tty.msg("Bcl2fastq2 expand_archive hack finished")
        return wrap

    def do_stage(self, mirror_only=False):
        self.stage.expand_archive = self.de_SNAFU(self.stage.expand_archive)
        super(Bcl2fastq2, self).do_stage(mirror_only)
```

**Comment by hartzell** [comment]
One last note, I could have been worse.  The zip file could have been [one of these...](https://research.swtch.com/zip)...

:scream:

**Comment by adamjstewart** [comment]
@hartzell This is probably the most interesting thing I've read all weak. Thank you!

**Comment by hartzell** [comment]
"May you live in interesting times."
