### ISSUE TITLE
spack install --overwrite doesn't seem to re-install a package

### ISSUE THREAD

**Issue by HealthyPear** [LLNL/spack#42085]
> I have the exact same issue as @ltalirz : I need to update the installation of a package for which there has been a PR merge here and even with `spack install --reuse-deps --overwrite --no-cache blabla` it simply tells me that is already installed.

_Originally posted by @HealthyPear in https://github.com/spack/spack/issues/17060#issuecomment-1890496029_

**Comment by alalazo** [comment]
I cannot reproduce with:

* **Spack:** 0.22.0.dev0 (28675478ce7c8b3dc1d896829585493ce57cd420)
* **Python:** 3.11.5
* **Platform:** linux-ubuntu20.04-icelake
* **Concretizer:** clingo

![Screenshot from 2024-01-17 11-07-11](https://github.com/spack/spack/assets/4199709/e82552ac-7446-41cb-99a4-76576b3f5fbb)

**Comment by haampie** [comment]
@alalazo this is in environments that have some "useful" early exit
