### ISSUE TITLE
openmpi:  A code compiled with spack gcc is slow when compiled with profiling instrumentation

### ISSUE THREAD

**Issue by iamashwin99** [LLNL/spack#42091]
I am trying to compile and run [octopus-code](https://octopus-code.org/) with spack compiler (both gcc@10.3.0 with openmpi@4.1.1and gcc@11.3.0 with openmpi@4.1.4) but both of them have the following problem :
when I compile the program with `-ftest-coverage -fprofile-arcs` the resulting binary is about 3x slower than the binary without this, all else being equal. ( on a serial-only build, it is much smaller at 50% or so slow down)
I compared the same code with the toolchains compiled with EasyBuild (foss2022a and foss2021a) and there this flag has no impact.
I am not sure what might be the problem, any input would be very helpful.
Some of my analyses are done at https://gitlab.gwdg.de/mpsd-cs/octopus_profiling_slowdown/-/tree/master
The relevant environment configuration is at https://gitlab.gwdg.de/mpsd-cs/spack-environments/-/blob/releases/23c/toolchains/foss2022a-mpi/spack.yaml?ref_type=heads

Steps to reproduce:
- build the toolchain `2022a-mpi` as mentioned here https://gitlab.gwdg.de/mpsd-cs/mpsd-software-manager#id1
```bash
pipx install git+https://gitlab.gwdg.de/mpsd-cs/mpsd-software-manager
mpsd-software init
mpsd-software install 23c foss2022a-mpi # takes about 2hrs on 16 core, this copies the environment file and uses spack to install the environment
# load modules mentioned at the end of the installation 
```
- build octopus as mentioned here https://gitlab.gwdg.de/mpsd-cs/octopus_profiling_slowdown/-/tree/master#reproduce-the-results

Any thoughts: @alalazo , @michaelkuhn ?

**Comment by alalazo** [comment]
@iamashwin99 Do I understand correctly that the compilers produce code that performs as expected when no profiling flags are given, and the slowdown is there only with `-fprofile-arcs -ftest-coverage`?

**Comment by iamashwin99** [comment]
In deed

**Comment by michaelkuhn** [comment]
Can you reproduce this using a minimal example? I just gave it a try with a small PDE solver and do not see any performance difference with and without those flags (Spack-built gcc@12.3.0).

**Comment by iamashwin99** [comment]
Is it possible to share your example so that I can test it in my spack environment and compare it?

**Comment by michaelkuhn** [comment]
It's the code in the `pde` directory from here: https://parcio.ovgu.de/parcio_media/Teaching/Winter+2023_2024/Parallele+Programmierung/PP_2023_Uebung_08_Materialien-p-644.tgz

**Comment by iamashwin99** [comment]
From your example, I too don't seem to have a difference : 
```
# Make the regular version
echo "Regular run"
which gcc
gcc -std=c11 -Wall -Wextra -Wpedantic -O3 -g   -c -o partdiff.o partdiff.c
gcc -std=c11 -Wall -Wextra -Wpedantic -O3 -g  partdiff.o  -lm -o partdiff
time  ./partdiff 1 2 1000 2 2 20

Regular run
/opt_mpsd/linux-debian11/23b/sandybridge/spack/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/gcc-11.3.0-5uyv23o3gjfskdf4xyx7uem35j6meh2n/bin/gcc
Berechnungszeit:    22.675004 s
Speicherbedarf:     978.761002 MiB
Berechnungsmethode: Jacobi
Interlines:         1000
Stoerfunktion:      f(x,y) = 2 * pi^2 * sin(pi * x) * sin(pi * y)
Terminierung:       Anzahl der Iterationen
Anzahl Iterationen: 20
Norm des Fehlers:   7.695219e-08

Matrix:
 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000

real	0m22.958s
user	0m22.660s
sys	0m0.296s
```
```
# Make the one with Profiling
echo "with profiling"
which gcc
gcc -std=c11 -Wall -Wextra -Wpedantic -O3 -fprofile-arcs -ftest-coverage -g   -c -o partdiff-prof.o partdiff.c
gcc -std=c11 -Wall -Wextra -Wpedantic -O3 -fprofile-arcs -ftest-coverage -g  partdiff-prof.o  -lm -o partdiff-prof
time  ./partdiff-prof 1 2 1000 2 2 20

with profiling
/opt_mpsd/linux-debian11/23b/sandybridge/spack/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/gcc-11.3.0-5uyv23o3gjfskdf4xyx7uem35j6meh2n/bin/gcc
Berechnungszeit:    22.437989 s
Speicherbedarf:     978.761002 MiB
Berechnungsmethode: Jacobi
Interlines:         1000
Stoerfunktion:      f(x,y) = 2 * pi^2 * sin(pi * x) * sin(pi * y)
Terminierung:       Anzahl der Iterationen
Anzahl Iterationen: 20
Norm des Fehlers:   7.695219e-08

Matrix:
 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000
 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000 0.0000

real	0m22.723s
user	0m22.442s
sys	0m0.276s

```

But the code you provided doesn't seem to make use of mpi, and the slowdown code in question (Octopus) uses mpi.
Octopus compiled and run serially, doesn't have a significant slowdown ( 10% or so so  comparable)
on the other hand, octopus compiled with mpi is more or less 3x slower.

The slowdown persists with `OMP_NUM_THREADS=1` and `MPIEXEC="orterun -n 1"` so that implies that the issue doesnt come with the openmpi.

**Comment by iamashwin99** [comment]
Some example runs from octopus for comparing spack and easybuild runtimes : 

| test_name                            | spack with profiling (in s) | spack without profiling (in s) | Easybuild with profiling (in s) | Easybuild without profiling (in s) |
|--------------------------------------|-----------------------------|--------------------------------|---------------------------------|------------------------------------|
| components/20-dft_u                  | 43.211                      | 3.346                          | 5.36                            | 3.588                              |
| maxwell/06-circular-polarization     | 68.662                      | 7.507                          | 8.292                           | 7.759                              |
| multisystem/07-lorentz-force         | 53.733                      | 6.134                          | 6.558                           | 6.071                              |

so the runs without profiling flags seem comparable with easybuild.
(more data points at https://gitlab.gwdg.de/mpsd-cs/octopus_profiling_slowdown/-/blob/master/runs/spack_vs_eb_mpi_2022a.csv)

**Comment by alalazo** [comment]
How do you add the compiler flags to the build?

**Comment by iamashwin99** [comment]
Here are some of the env variables related to the compilers that are set during build:
```
export CC="mpicc"
MARCH_FLAG="-march=${GCC_ARCH:-native}"
OPTIMISATION_LEVEL="-O3"
export CFLAGS="$MARCH_FLAG $OPTIMISATION_LEVEL -g -fno-var-tracking-assignments -ftest-coverage -fprofile-arcs"
export CXX="mpicxx"
export CXXFLAGS="$MARCH_FLAG $OPTIMISATION_LEVEL -g -fno-var-tracking-assignments -ftest-coverage -fprofile-arcs"
export FC="mpif90"
export FCFLAGS="$MARCH_FLAG $OPTIMISATION_LEVEL -g -fno-var-tracking-assignments -ffree-line-length-none -fallow-argument-mismatch -fallow-invalid-boz -ftest-coverage -fprofile-arcs"

```

Perhaps also worth mentioning that Octopus code is majorly Fortran code.

**Comment by alalazo** [comment]
Hmm, where do you set those variables? Note that we have the following in Spack:

https://github.com/spack/spack/blob/bc9b39cb73a83219306e67191b560412155200d5/lib/spack/spack/build_environment.py#L245-L266

To "sanitize" the environment before building. To avoid cleaning them you have to pass the `--dirty` option to Spack when building.

**Comment by iamashwin99** [comment]
I dont use spack to build Octopus. I use spack to build the toolchain (= gcc + openmpi%gcc + other dependencies%gcc).

I set these variables, before calling the `configure` of octopus. so:
```markdown 
# step1: spack create an environment with gcc + openmpi%gcc + other dependencies%gcc
# step2: spack generate modules for this environment
# step3: module load gcc + openmpi%gcc + other dependencies%gcc generated from previous step

# step4: clone octopus and prepare autotools for build
# step5: set compiler flags
# step6: ./configure --with-{dependecies_compiled_from_spack}={dependencies_root}
# step7: make install -j
# step8: make check   ## Runs 3x slower when profiling enabled in step5
```

**Comment by iamashwin99** [comment]
Another key difference:
When I disassemble the binaries for easy build and spack compiled  octopus, 
I notice that spack uses `lock addq` instructions but `easybuild` only uses `addq`.
In fact easybuild one doesn't have any `lock` at all in the entire binary.
here are few lines from main:
easybuild:
```
00000000004184c0 <MAIN__>:
  4184c0:	41 55                	push   %r13
  4184c2:	41 54                	push   %r12
  4184c4:	55                   	push   %rbp
  4184c5:	53                   	push   %rbx
  4184c6:	48 81 ec 48 04 00 00 	sub    $0x448,%rsp
  4184cd:	48 83 05 eb 22 51 01 	addq   $0x1,0x15122eb(%rip)        # 192a7c0 <__gcov0.MAIN__>
  4184d4:	01 
  4184d5:	48 8d 7c 24 04       	lea    0x4(%rsp),%rdi
  4184da:	e8 51 45 01 00       	call   42ca30 <__command_line_oct_m_MOD_getopt_init>
  4184df:	be 00 01 00 00       	mov    $0x100,%esi
  4184e4:	48 83 05 dc 22 51 01 	addq   $0x1,0x15122dc(%rip)        # 192a7c8 <__gcov0.MAIN__+0x8>
  4184eb:	01 
  4184ec:	48 8d bc 24 30 01 00 	lea    0x130(%rsp),%rdi
  4184f3:	00 
  4184f4:	e8 47 b3 04 00       	call   463840 <__utils_oct_m_MOD_get_config_opts>
  4184f9:	ba 00 01 00 00       	mov    $0x100,%edx
  4184fe:	48 83 05 ca 22 51 01 	addq   $0x1,0x15122ca(%rip)        # 192a7d0 <__gcov0.MAIN__+0x10>
```

spack
```
000000000041d3e0 <MAIN__>:
  41d3e0:	41 55                	push   %r13
  41d3e2:	41 54                	push   %r12
  41d3e4:	55                   	push   %rbp
  41d3e5:	53                   	push   %rbx
  41d3e6:	48 81 ec 48 04 00 00 	sub    $0x448,%rsp
  41d3ed:	f0 48 83 05 4a 57 71 	lock addq $0x1,0x171574a(%rip)        # 1b32b40 <__gcov0.MAIN__>
  41d3f4:	01 01 
  41d3f6:	48 8d 7c 24 04       	lea    0x4(%rsp),%rdi
  41d3fb:	e8 40 58 01 00       	call   432c40 <__command_line_oct_m_MOD_getopt_init>
  41d400:	f0 48 83 05 3f 57 71 	lock addq $0x1,0x171573f(%rip)        # 1b32b48 <__gcov0.MAIN__+0x8>
  41d407:	01 01 
  41d409:	be 00 01 00 00       	mov    $0x100,%esi
  41d40e:	48 8d bc 24 30 01 00 	lea    0x130(%rsp),%rdi
  41d415:	00 
  41d416:	e8 75 3c 05 00       	call   471090 <__utils_oct_m_MOD_get_config_opts>
  41d41b:	f0 48 83 05 2c 57 71 	lock addq $0x1,0x171572c(%rip)        # 1b32b50 <__gcov0.MAIN__+0x10>
```

```
❯ grep "lock " octopus_easybuild.diss| wc -l                                                        ─╯
0
❯ grep "lock " octopus_spack.diss|wc -l
333356
```

**Comment by iamashwin99** [comment]
Looking at configure options, easybuild was configured with `lto` and `gold` but not in spack.
spack:
```
Reading specs from $SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/gcc-11.3.0-5uyv23o3gjfskdf4xyx7uem35j6meh2n/lib/gcc/x86_64-pc-linux-gnu/11.3.0/specs
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=$SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/gcc-11.3.0-5uyv23o3gjfskdf4xyx7uem35j6meh2n/libexec/gcc/x86_64-pc-linux-gnu/11.3.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /tmp/mpsddeb/spack-stage/spack-stage-gcc-11.3.0-5uyv23o3gjfskdf4xyx7uem35j6meh2n/spack-src/configure
--prefix=$SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/gcc-11.3.0-5uyv23o3gjfskdf4xyx7uem35j6meh2n
--with-pkgversion='Spack GCC'
--with-bugurl=https://github.com/spack/spack/issues
--disable-multilib
--enable-languages=c,c++,fortran
--disable-nls
--disable-canonical-system-headers
--with-system-zlib
--with-zstd-include=$SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/zstd-1.5.2-ggudblvtoy475xuc7cm34obvr4rra4db/include
--with-zstd-lib=$SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/zstd-1.5.2-ggudblvtoy475xuc7cm34obvr4rra4db/lib
--enable-bootstrap
--with-mpfr-include=$SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/mpfr-4.1.0-vt74r4wok66y2j7u6wxd44lrxordnh6s/include
--with-mpfr-lib=$SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/mpfr-4.1.0-vt74r4wok66y2j7u6wxd44lrxordnh6s/lib
--with-gmp-include=$SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/gmp-6.2.1-7urt35pthvdwqvxbifq2ujqduv4xspfd/include
--with-gmp-lib=$SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/gmp-6.2.1-7urt35pthvdwqvxbifq2ujqduv4xspfd/lib
--with-mpc-include=$SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/mpc-1.2.1-3tfqbfturndjpl4r35vqlflp6l4ucsxd/include
--with-mpc-lib=$SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/mpc-1.2.1-3tfqbfturndjpl4r35vqlflp6l4ucsxd/lib
--without-isl
--with-stage1-ldflags='-Wl,-rpath,$SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/gcc-11.3.0-5uyv23o3gjfskdf4xyx7uem35j6meh2n/lib -Wl,-rpath,$SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/gcc-11.3.0-5uyv23o3gjfskdf4xyx7uem35j6meh2n/lib64 -Wl,-rpath,$SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/gmp-6.2.1-7urt35pthvdwqvxbifq2ujqduv4xspfd/lib -Wl,-rpath,$SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/mpc-1.2.1-3tfqbfturndjpl4r35vqlflp6l4ucsxd/lib -Wl,-rpath,$SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/mpfr-4.1.0-vt74r4wok66y2j7u6wxd44lrxordnh6s/lib -Wl,-rpath,$SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/zlib-1.2.13-6f6r7d4ibhi5b6ngahxxlcuaeuoid4dx/lib -Wl,-rpath,$SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/zstd-1.5.2-ggudblvtoy475xuc7cm34obvr4rra4db/lib'
--with-boot-ldflags='-Wl,-rpath,$SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/gcc-11.3.0-5uyv23o3gjfskdf4xyx7uem35j6meh2n/lib -Wl,-rpath,$SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/gcc-11.3.0-5uyv23o3gjfskdf4xyx7uem35j6meh2n/lib64 -Wl,-rpath,$SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/gmp-6.2.1-7urt35pthvdwqvxbifq2ujqduv4xspfd/lib -Wl,-rpath,$SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/mpc-1.2.1-3tfqbfturndjpl4r35vqlflp6l4ucsxd/lib -Wl,-rpath,$SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/mpfr-4.1.0-vt74r4wok66y2j7u6wxd44lrxordnh6s/lib -Wl,-rpath,$SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/zlib-1.2.13-6f6r7d4ibhi5b6ngahxxlcuaeuoid4dx/lib -Wl,-rpath,$SPACK_ROOT/opt/spack/linux-debian11-x86_64_v2/gcc-10.2.1/zstd-1.5.2-ggudblvtoy475xuc7cm34obvr4rra4db/lib -static-libstdc++ -static-libgcc'
--with-build-config=spack
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 11.3.0 (Spack GCC)

```
easybuild:
```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=$EB_ROOT/2022a/software/GCCcore/11.3.0/libexec/gcc/x86_64-pc-linux-gnu/11.3.0/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
Target: x86_64-pc-linux-gnu
Configured with: ../configure
--enable-languages=c,c++,fortran
--without-cuda-driver
--enable-offload-targets=nvptx-none
--enable-lto
--enable-checking=release
--disable-multilib
--enable-shared=yes
--enable-static=yes
--enable-threads=posix
--enable-plugins
--enable-gold
--enable-ld=default
--prefix=$EB_ROOT/2022a/software/GCCcore/11.3.0
--with-local-prefix=$EB_ROOT/2022a/software/GCCcore/11.3.0
--enable-bootstrap
--with-isl=/tmp/easybuild/build/GCCcore/11.3.0/system-system/gcc-11.3.0/stage2_stuff
--build=x86_64-pc-linux-gnu
--host=x86_64-pc-linux-gnu
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.3.0 (GCC)
```

**Comment by michaelkuhn** [comment]
LTO seems to be enabled by default and according to this, admittedly old, post (https://stackoverflow.com/questions/31662010/purpose-of-enable-gold-when-configuring-gcc), `--enable-gold` doesn't do anything for GCC.

I'm a bit more curious about the missing `lock`. Are you using atomic variables/functions? If so, that would probably explain them. `lock` apparently can have quite some overhead for misaligned data/accesses. Omitting it could probably lead to incorrect results.

Can you build Octopus using a system compiler and see how that behaves?

**Comment by iamashwin99** [comment]
I will try the system compiler and report. The  `lock` instructions are only added in the profiling instructions (see for eg the comments), so it wont effect the scientific calculations  (I hope)

**Comment by michaelkuhn** [comment]
> The `lock` instructions are only added in the profiling instructions (see for eg the comments), so it wont effect the scientific calculations (I hope)

Ah, I missed that. This sounds a bit like this: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80952
Are you sure both Octopus variants are using the same flags, specifically `-fopenmp` and `-pthread`?

**Comment by michaelkuhn** [comment]
I can now also reproduce this with the `partdiff` code above:
- Normal (`partdiff 1 2 1024 2 2 100`): 26.2s
- `-fprofile-arcs -ftest-coverage`: 26.7s
- `-fprofile-arcs -ftest-coverage -fopenmp`: 67.9s

**Comment by iamashwin99** [comment]
> I can now also reproduce this with the `partdiff` code above:
> 
> * Normal (`partdiff 1 2 1024 2 2 100`): 26.2s
> * `-fprofile-arcs -ftest-coverage`: 26.7s
> * `-fprofile-arcs -ftest-coverage -fopenmp`: 67.9s

I can reproduce the same (all 3 cases) with system compiler, easybuild compiler, and spack compiler.
So perhaps the broad problem is:
- somehow related to octopus
- related to mpi

**Comment by iamashwin99** [comment]
> > The `lock` instructions are only added in the profiling instructions (see for eg the comments), so it wont effect the scientific calculations (I hope)
> 
> Ah, I missed that. This sounds a bit like this: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80952 Are you sure both Octopus variants are using the same flags, specifically `-fopenmp` and `-pthread`?

Looking at this suggestion, I noticed that the spack builds have `-pthread` but not in easybuild.
We traced this to the mpi wrappers ( mpicc, mpifort, mpic++) that add `-pthread` in spack but not in easybuild.

I also noticed that debian openmpi wrappers for eg also come with the `-pthread` indicating that it might perhaps easybuild that is inconsistent here.

I ran a build of octopus with `-pthread` removed from all the wrappers and the resulting binary has no `locks` and is also running at comparable wall time as from easybuild ones.

So the question now is, if easybuild does this by mistake, or if not how can we enable the feature (or bug ) in spack compiler perhaps via a variant.

**Comment by iamashwin99** [comment]
Since this is not particularly a spack-only related issue, I would close this issue here. For anyone having a similar issue, I solved it by using ` -fprofile-update=single`  since I knew that we were not using any multithreading in our runs.
