### ISSUE TITLE
spack.yaml:3: Additional properties are not allowed

### ISSUE THREAD

**Issue by Vahid999** [LLNL/spack#42100]
### Steps to reproduce

Here are the steps I took towards installing spack on Beluga Cluster on Compute Canada

1. git clone https://github.com/spack/spack.git
2. cd spack
3.  git checkout v0.19.0 (recommended by NanoDCAL installation procedure)
4. source share/spack/setup-env.sh
5. cd ..
6. spack env activate .

### Error message

==> Error: /home/vaskarpo/bin/nano/nanodcalplus-2023B/spack.yaml:3: Additional properties are not allowed ('concretization' was unexpected)

### Information on your system

* **Spack:** 0.19.0 (bb8b4f9979e87ae3fb63a3adcb768eda09e5b059)
* **Python:** 3.8.10
* **Platform:** linux-centos7-skylake_avx512
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
If you check v0.19.0 release notes, at the bottom, you'll find:

![Screenshot from 2024-01-16 12-46-57](https://github.com/spack/spack/assets/4199709/ced6b582-9474-482e-ab8b-24990f4da2a4)

It's likely you just need to update your `spack.yaml` file.

**Comment by alalazo** [comment]
Also, I would recommend moving to v0.21 if that is possible.

**Comment by Vahid999** [comment]
Here is my updated spack.yaml (changed “together" to “unify" in line 4 from bottom) and I did use version 0.21 but the error remained unchanged:


spack:
  # add package specs to the `specs` list
  packages:
    all:
      compiler: [gcc@9.3.0]
      providers:
        blas: [openblas threads=openmp]
        fftw-api: [fftw+openmp]
        scalapack: [netlib-scalapack@2.1.0]
  specs:
  - fftw+openmp
  - netlib-scalapack +pic ~shared
  - elpa@2021.05.002 +openmp
  - hdf5@1.10.6+fortran+hl+mpi+shared+szip
  - libxc@4.2.3
  - zofu
  - meson@0.57.0
  - json-fortran
  - patchelf
  concretization: unify
  view: true
  repos:
  - ./spack-repo

Are there other changes needed in spack.yaml?

Thanks,
Vahid


On Jan 16, 2024, at 7:49 AM, Massimiliano Culpo ***@***.***> wrote:

CAUTION: The Sender of this email is not from within Dalhousie.


Also, I would recommend moving to v0.21 if that is possible.

**Comment by alalazo** [comment]
The option should be:
```yaml
concretizer:
  unify: true
```
or 
```yaml
concretizer:
  unify: false
```
depending whether you were using `together` or `separately`.

**Comment by Vahid999** [comment]
Here is my new spack.yaml giving me the same error:

spack:
  # add package specs to the `specs` list
  packages:
    all:
      compiler: [gcc@9.3.0]
      providers:
        blas: [openblas threads=openmp]
        fftw-api: [fftw+openmp]
        scalapack: [netlib-scalapack@2.1.0]
  specs:
  - fftw+openmp
  - netlib-scalapack +pic ~shared
  - elpa@2021.05.002 +openmp
  - hdf5@1.10.6+fortran+hl+mpi+shared+szip
  - libxc@4.2.3
  - zofu
  - meson@0.57.0
  - json-fortran
  - patchelf
  concretization: 
      unify : true
  view: true
  repos:
  - ./spack-repo

**Comment by Vahid999** [comment]
This worked. I also had to change “concentrization” to “concentrizer”.

Thanks,
Vahid

On Jan 16, 2024, at 9:38 AM, Massimiliano Culpo ***@***.***> wrote:

CAUTION: The Sender of this email is not from within Dalhousie.


The option should be:

concretizer:
  unify: true

or

concretizer:
  unify: false

depending whether you were using together or separately.
