### ISSUE TITLE
Installation issue: wgrib2

### ISSUE THREAD

**Issue by curtisecombsjr** [LLNL/spack#42132]
### Steps to reproduce the issue

```console
$ spack spec -I wgrib2
alogin02:/apps/spack # spack spec -I wgrib2
Input spec
--------------------------------
 -   wgrib2

Concretized
--------------------------------
 -   wgrib2@3.1.1%intel@19.1.3.304+aec~disable_alarm~disable_timezone+fortran_api~g2c+jasper~mysql+netcdf3~netcdf4+openmp+png~proj4+regex~spectral+tigge~udf~wmo_validation build_system=makefile ipolates=3 arch=linux-sles15-zen2
[+]      ^gmake@4.4.1%intel@19.1.3.304~guile build_system=autotools arch=linux-sles15-zen2

alogin02:/apps/spack #
...
```

### Error message

<details><summary>Error message</summary>

<pre>
==> Error: ProcessError: Command exited with status 2:
    'make' '-j1'

7 errors found in build log:
     669     checking if /apps/spack/spack-0.21.1/lib/spack/env/intel/ifort PIC flag -fPIC w
             orks... yes
     670     checking if /apps/spack/spack-0.21.1/lib/spack/env/intel/ifort static flag -sta
             tic works... no
     671     checking if /apps/spack/spack-0.21.1/lib/spack/env/intel/ifort supports -c -o f
             ile.o... yes
     672     checking whether the /apps/spack/spack-0.21.1/lib/spack/env/intel/ifort linker
             (/usr/x86_64-suse-linux/bin/ld -m elf_x86_64) supports shared libraries... yes
     673     checking dynamic linker characteristics... ifort: command line warning #10006:
             ignoring unknown option '-print-search-dirs'
     674     /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: /pe/in
             tel/compilers_and_libraries_2020.4.304/linux/compiler/lib/intel64_lin/for_main.
             o: in function `main':
  >> 675     for_main.c:(.text+0x2e): undefined reference to `MAIN__'
     676     GNU/Linux ld.so
     677     checking how to hardcode library paths into programs... immediate
     678     checking for X... disabled
     679     checking whether variable-length arrays are supported... yes
     680     checking whether OpenGL libraries and headers were detected... no
     681     checking for main in -lm... yes

     ...

     4837    /apps/spack/spack-0.21.1/lib/spack/env/intel/icc -c  -I/tmp/root/spack-stage/sp
             ack-stage-wgrib2-3.1.1-y7ki2zv4zxoxyoh5ihhopnftwir65lqp/spack-src/include -O2 -
             DIFORT -cxxlib -qopenmp -I/tmp/root/spack-stage/spack-stage-wgrib2-3.1.1-y7ki2z
             v4zxoxyoh5ihhopnftwir65lqp/spack-src/jasper-1.900.1/src/libjasper/include   v1_
             v2_if.c
     4838    /apps/spack/spack-0.21.1/lib/spack/env/intel/icc -c  -I/tmp/root/spack-stage/sp
             ack-stage-wgrib2-3.1.1-y7ki2zv4zxoxyoh5ihhopnftwir65lqp/spack-src/include -O2 -
             DIFORT -cxxlib -qopenmp -I/tmp/root/spack-stage/spack-stage-wgrib2-3.1.1-y7ki2z
             v4zxoxyoh5ihhopnftwir65lqp/spack-src/jasper-1.900.1/src/libjasper/include   wgr
             ib2.c
     4839    /apps/spack/spack-0.21.1/lib/spack/env/intel/icc -c  -I/tmp/root/spack-stage/sp
             ack-stage-wgrib2-3.1.1-y7ki2zv4zxoxyoh5ihhopnftwir65lqp/spack-src/include -O2 -
             DIFORT -cxxlib -qopenmp -I/tmp/root/spack-stage/spack-stage-wgrib2-3.1.1-y7ki2z
             v4zxoxyoh5ihhopnftwir65lqp/spack-src/jasper-1.900.1/src/libjasper/include   wgr
             ib2_api.c
     4840    /apps/spack/spack-0.21.1/lib/spack/env/intel/icc -c  -I/tmp/root/spack-stage/sp
             ack-stage-wgrib2-3.1.1-y7ki2zv4zxoxyoh5ihhopnftwir65lqp/spack-src/include -O2 -
             DIFORT -cxxlib -qopenmp -I/tmp/root/spack-stage/spack-stage-wgrib2-3.1.1-y7ki2z
             v4zxoxyoh5ihhopnftwir65lqp/spack-src/jasper-1.900.1/src/libjasper/include   wrt
             ieee.c
     4841    /apps/spack/spack-0.21.1/lib/spack/env/intel/icc -c  -I/tmp/root/spack-stage/sp
             ack-stage-wgrib2-3.1.1-y7ki2zv4zxoxyoh5ihhopnftwir65lqp/spack-src/include -O2 -
             DIFORT -cxxlib -qopenmp -I/tmp/root/spack-stage/spack-stage-wgrib2-3.1.1-y7ki2z
             v4zxoxyoh5ihhopnftwir65lqp/spack-src/jasper-1.900.1/src/libjasper/include   wxt
             ext.c
     4842    /apps/spack/spack-0.21.1/lib/spack/env/intel/icc -o wgrib2  -I/tmp/root/spack-s
             tage/spack-stage-wgrib2-3.1.1-y7ki2zv4zxoxyoh5ihhopnftwir65lqp/spack-src/includ
             e -O2 -DIFORT -cxxlib -qopenmp -I/tmp/root/spack-stage/spack-stage-wgrib2-3.1.1
             -y7ki2zv4zxoxyoh5ihhopnftwir65lqp/spack-src/jasper-1.900.1/src/libjasper/includ
             e  AAIG.o AAIGlong.o Aerosol.o Alarm.o Alias.o Ave_test.o Ave_var.o Bbox.o Box_
             ave.o Check_pdt_size.o Checksum.o Cluster.o CodeTable.o Code_Values.o Config.o
             Cress_lola.o Csv.o Csv_long.o CubeFace2global.o Cyclic.o Data.o Dump.o EOF.o Ea
             rth.o Else.o End.o Endif.o Ens_processing.o Ens_qc.o Ensemble.o Export_lonlat.o
              ExtName.o Fcst_ave.o Fi.o File.o Fix_CFSv2_fcst.o Fix_ncep.o Fix_ncep_2.o Fix_
             ncep_3.o Fix_ncep_4.o Fix_undef.o FlagTable.o Flush.o For.o Ftime.o Ftime1.o Ft
             ime2.o Ftn_api.o GDT.o Gctpc.o Geolocation.o Grads.o Grib.o Grib_out_irr.o Grib
             _out_irr2.o Gribtable_used.o Grid_def.o Grid_id.o Gridout.o Help.o Hybrid.o If_
             delayed_error.o If_rec.o Import.o Import_grib.o Import_grib_fs.o Import_lonlat.
             o Import_netcdf.o Inv.o Inv_no.o Irr_grids.o JMA.o Last.o Latlon.o Level.o Limi
             t.o Lola.o Macro.o Match.o Match_fs.o Match_inv.o Mem_buffer.o Merge.o Misc.o M
             od_grib.o Model_version_date.o Mysql.o Mysql_dump.o Mysql_speed.o NCEP_norm.o N
             CEP_uv.o Names.o Ncpu.o Ndate.o Ndates.o Netcdf.o Netcdf_sup.o New_grid.o New_g
             rid_order.o Precision.o Prob.o Proj4.o PyInv.o RPN.o Range.o Reduced_gaussian_g
             rid.o Reset_delayed_error.o Scaling_0001.o Scan.o Sec0.o Sec1.o Sec3.o Sec4.o S
             ec5.o Sec6.o Sec_len.o Set_byte.o Set_date.o Set_ens_num.o Set_ensm_derived_fcs
             t.o Set_ftime1.o Set_ftime2.o Set_gds.o Set_metadata.o Set_pdt.o Set_percentile
             .o Set_prob.o Set_sec_size.o Set_ts_dates.o Set_val.o Small_grib.o SpatialProce
             ssing.o Spectral_bands.o Status.o Submsg_uv.o Summary.o Tigge.o Time_processing
             .o Timer.o Tosubmsg.o UDF.o Undefine.o Unix_time.o Unix_time_old.o Unmerge_fcst
             .o VerfTime.o Warn_old_g2lib.o Waves.o Wind_dir.o Wind_speed.o Wind_uv.o Write_
             sec.o Wrt_grib.o addtime.o aec_pk.o bitstream.o cname.o codetable_4_230.o compl
             ex_pk.o copy.o crc32.o cubed_sphere2ll.o dec_png_clone.o decenc_openjpeg.o enc_
             jpeg2000_clone.o fatal_error.o ffopen.o flt2ieee.o flt2ieee_nan.o fnlist.o gaus
             sian2ij.o gctpc_ll2xy.o geo.o get_unixtime.o gribtab.o grid_ident.o ieee2flt.o
             ieee2flt_nan.o ieee_pk.o init.o int8.o intpower.o itoshort_a.o jpeg_pk.o lat2ij
             .o manage_inv_out.o missing.o mk_gdt.o mk_kgds.o ncep_grids.o new_grid_lambertc
             .o openmp_util.o parse_loop.o parse_msg.o pdt_len.o proj4_initialize.o proj4_tr
             ansform.o rd_inventory.o rd_seq_grib.o rdieee_file.o read_latlon.o rotll.o save
             _string.o sec3_grids.o setup_user_gribtable.o simple_pk.o space_view.o space_vi
             ew2ij.o stagger.o string2time_unit.o subtime.o swap_buffer.o test_sec.o units.o
              unpk.o unpk_0.o unpk_complex.o unpk_run_length.o update_sec3.o update_sec4.o v
             1_v2_if.o wgrib2.o wgrib2_api.o wrtieee.o wxtext.o -L/tmp/root/spack-stage/spac
             k-stage-wgrib2-3.1.1-y7ki2zv4zxoxyoh5ihhopnftwir65lqp/spack-src/lib -lip2_d -li
             fcore -lc -limf -lintlc -lgeo -ljasper -laec -lnetcdf -lpng12 -lz -lm
  >> 4843    /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot
              find -ljasper: No such file or directory
  >> 4844    /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot
              find -laec: No such file or directory
  >> 4845    /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot
              find -lnetcdf: No such file or directory
  >> 4846    /usr/lib64/gcc/x86_64-suse-linux/7/../../../../x86_64-suse-linux/bin/ld: cannot
              find -lpng12: No such file or directory
  >> 4847    make[1]: *** [makefile:25: wgrib2] Error 1
     4848    make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-wgrib2-3.1.1-y7ki
             2zv4zxoxyoh5ihhopnftwir65lqp/spack-src/wgrib2'
  >> 4849    make: *** [makefile:833: wgrib2/wgrib2] Error 2

See build log for details:
  /tmp/root/spack-stage/spack-stage-wgrib2-3.1.1-y7ki2zv4zxoxyoh5ihhopnftwir65lqp/spack-build-out.txt

alogin02:/apps/spack #
</pre></details>

### Information on your system

it identifies as as "linux-sles15-zen2" in Spack, but it is actually a Cray Ex system. Spack is installed on a shared filesystem. Cluster is 3400 nodes.

alogin02:/apps/spack # spack debug report
* **Spack:** 0.21.1
* **Python:** 3.6.15
* **Platform:** linux-sles15-zen2
* **Concretizer:** clingo
alogin02:/apps/spack #

### Additional information

I have tried multiple times with multiple compilers. We primarily use intel, but we have Cray gcc and gcc 13.1.0 installed as well. Seems to fail on all. I have migrated our config (etc/*.yaml) after upgrading from 0.20.1, so i suspect it may be a possible issue.

[spack-build-env.txt](https://github.com/spack/spack/files/13969934/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/13969935/spack-build-out.txt)
[compilers.txt](https://github.com/spack/spack/files/13969975/compilers.txt)
[packages.txt](https://github.com/spack/spack/files/13969976/packages.txt)
[config.txt](https://github.com/spack/spack/files/13969979/config.txt)
[modules.txt](https://github.com/spack/spack/files/13969983/modules.txt)
@AlexanderRichert-NOAA @Hang-Lei-NOAA @edwardhartnett @t-brown 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by curtisecombsjr** [comment]
Something that I thought was odd about this specific package was that it has no "depends_on" statements in its package.py. Please note that we have installed many, many other packages without issue and they seem to pull in the dependencies that they need and automatically build them. This package has default variants like jasper and libaec, but it makes no effort to download and install those when "spack install wgrib2" is run for any of our compilers.

Thank you!

**Comment by AlexanderRichert-NOAA** [comment]
I believe wgrib2 provides its own copies of those libraries (jasper, libaec, netcdf, etc.). Can you upload your spack-build-out.txt (/tmp/root/spack-stage/spack-stage-wgrib2-3.1.1-y7ki2zv4zxoxyoh5ihhopnftwir65lqp/spack-build-out.txt)? My guess is that something is broken in the internal library builds, but it's trying to install anyway, causing the `cannot find -l...` errors.

**Comment by curtisecombsjr** [comment]
[spack-build-out2.txt](https://github.com/spack/spack/files/13970089/spack-build-out2.txt)

certainly, here you go. thanks for the help!

**Comment by curtisecombsjr** [comment]
Some variations that I have tried:
spack install wgrib2@3.1.1%intel@19.1.3.304
spack install wgrib2@3.1.1%intel@2022.2.0.262
spack install wgrib2@3.1.1%gcc@11.2.0
spack install wgrib2@3.1.1%gcc@13.1.0
spack install wgrib2@3.1.0%gcc@11.2.0

gcc 11.2.0 is not GNU gcc, but Cray's "SNOS" gcc. 13.1.0 is GNU gcc that I installed to test with.

all of the above seem to result in the same error, but i did inherit a lot of this configuration, so it may not be 100% correct. please check the config if you hit a wall.

thanks again!

**Comment by AlexanderRichert-NOAA** [comment]
Looking at the log, it appears that some of the libraries are going under `lib64`, but the -L flag only points to `lib`. I'll dig a little further to see how it's determining the directory name. The build system may be determining the lib directory in a platform-dependent (and internally inconsistent) way.

**Comment by curtisecombsjr** [comment]
Ah! Gotcha. My eyes skirted right over that and didn't see it, but that makes sense.

Thanks so much, please let me know what you find. We often have issues with multilib.

**Comment by curtisecombsjr** [comment]
Since you mentioned it, I thought to go looking for myself. I think it might have to do with how we have it configured and I included our configuration in the original post, if it helps. I say this because I have had another, seemingly related, issue with Python where I have to link lib-dynload under the /lib directory to that same directory installed in /lib64 (in the Python directory) for it to find the modules installed with a stock Python install. I thought I should mention it because it sounds related, but I wouldn't know where to configure that behavior.

Thanks again!

**Comment by curtisecombsjr** [comment]
This MIGHT be a fix. I am going to try it again with this and let you know:

https://github.com/spack/spack/issues/40110

**Comment by curtisecombsjr** [comment]
Success:
```
alogin02:~ # spack install wgrib2
[+] /apps/spack/gmake/4.4.1/intel/19.1.3.304/ohpyr3tpsrscrqe476rhapya65pe546l
==> Installing wgrib2-3.1.1-y7ki2zv4zxoxyoh5ihhopnftwir65lqp
==> No binary for wgrib2-3.1.1-y7ki2zv4zxoxyoh5ihhopnftwir65lqp found: installing from source
==> Warning: Intel's compilers may or may not optimize to the same degree for non-Intel microprocessors for optimizations that are not unique to Intel microprocessors
==> Using cached archive: /apps/spack/spack-0.21.1/var/spack/cache/_source-cache/archive/92/9236f6afddad76d868c2cfdf5c4227f5bdda5e85ae40c18bafb37218e49bc04a.tar.gz
==> No patches needed for wgrib2
==> wgrib2: Executing phase: 'edit'
==> wgrib2: Executing phase: 'build'
==> wgrib2: Executing phase: 'install'
==> wgrib2: Successfully installed wgrib2-3.1.1-y7ki2zv4zxoxyoh5ihhopnftwir65lqp
  Stage: 0.37s.  Edit: 0.05s.  Build: 5m 24.29s.  Install: 0.03s.  Post-install: 0.23s.  Total: 5m 25.10s
[+] /apps/spack/wgrib2/3.1.1/intel/19.1.3.304/y7ki2zv4zxoxyoh5ihhopnftwir65lqp
```

**Comment by AlexanderRichert-NOAA** [comment]
Ah yep, sure enough. That's why we weren't running into it before, is we were already unsetting CONFIG_SITE in our site configurations. Let me know if it's alright to close this. Thanks for tracking that down!

**Comment by curtisecombsjr** [comment]
I think we are good to close. I've tried it a few times now and it seems to be a success. I added it to setup-env.sh so we won't ever see it again. Thanks a million!
