### ISSUE TITLE
NCL: Dependencies should be build-only

### ISSUE THREAD

**Issue by DavidHuber-NOAA** [LLNL/spack#42262]
### Summary

NCL is built using static linking for each of its dependencies, so e.g. netCDF dynamic libraries do not need to be linked at runtime.

### Rationale

On systems using `lmod` modules, the modules are populated with `depends_on` statements.  When running scientific workflows, for instance the global workflow, it is necessary to have NCL and a specific version of netCDF loaded at the same time, but the `depends_on` loads different versions of netcdf-c and netcdf-fortran, causing portions of the workflow to fail.

### Description

The dependencies should be set to, e.g.
`depends_on("netcdf-c", type="build")`

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by DavidHuber-NOAA** [comment]
@vanderwb we are running into this issue because system spack-built packages (including NCL) are built with different dependencies than our scientific stacks.  Would it be possible to amend the dependencies?

**Comment by vanderwb** [comment]
@DavidHuber-NOAA - apologies for the slow response. In general, I'm not opposed to the idea, but it would create an issue for logic I recently added to fix the ncarg/nhl compiler wrappers that come with NCL. I also have concerns that this could break the build for users who choose options like ~static for dependent packages. I could make any static options into hard requirements, but again I'd need to investigate.

Before going down that road... the "depends_on" settings can also be limited via the **modules.yaml** configuration file, like so:

```
modules:
  default:
    lmod:
      ncl:
        autoload: none
```

Would that approach satisfy your use case?

**Comment by alalazo** [comment]
Note that this proposal would be incorrect. A "build" dependency in Spack is ought to model a build tool, like e.g. `cmake`, that is invoked when building a package and is not related to the linker. A static library is still a "link" type dependency. There has been discussions of splitting the current "link" dependencies into a more fine grained "link-static" (I think somebody also called this "include", thinking of C++ templates) and "link-dynamic" - but that never happened.

**Comment by DavidHuber-NOAA** [comment]
@alalazo Thanks for the heads up/clarification on the meaning behind 'build' dependencies.  I would add a +1 to the idea of creating 'link-static' and 'link' dependencies, but I think for now I'm OK with closing this as, at least in our case, this NCL issue will be resolved in another way.

@vanderwb Given the note above, I am going to go ahead and close this.  Thanks for entertaining the idea.
