### ISSUE TITLE
Make spackbot documentation accessible from spack documentation

### ISSUE THREAD

**Issue by white238** [LLNL/spack#42271]
### Summary

I can never remember what Spackbot is capable of doing. Searching the documentation found no results.

### Rationale

The problem is I can't remember.

### Description

I would like to have SpackBot style my PR but can't remember the command.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by cmelone** [comment]
Spackbot docs are located separately https://spack.github.io/spackbot/docs/#/

**Comment by alalazo** [comment]
@white238 Is it fine to close this? Or do you think there are further actions to be taken?

**Comment by white238** [comment]
I would have never found that. I searched Spack's documentation and your README which contains how to contribute. I think it would be helpful to have a page on how to develop in Spack or at least a link to that page, while also adding a list of commands that Spackbot has.

If I don't even know I could run `@spackbot help`, `@spackbot commands`, or the above documentation exists. How does a non-everyday Spack developer know this functionality exists?

I renamed the issue to be more accurate/helpful.

Possible solutions to help my poor brain in the future:
* Have Spackbot leave a comment on creation of PRs with basic commands? Maybe something like, "Hi I'm Spackbot you can see my commands here: <insert link>"
* Add a link in your documentation and/or README to the above link (hopefully with a list of example commands
* Have that documentation in Spack's documentation

**Comment by alalazo** [comment]
@white238 What if we add a PR template with some of those instructions ?

**Comment by white238** [comment]
My concern is it may pollute the PR description with basic information but I am open to being proven wrong.

I feel like an auto-comment from Spackbot would be better, but maybe that would cause too much email spam?

**Comment by alalazo** [comment]
> My concern is it may pollute the PR description with basic information but I am open to being proven wrong.

Not sure it's doable, but I was thinking at some comment that would not be part of the final PR, but would be visible from contributors when submitting the PR.

**Comment by becker33** [comment]
Maybe in a collapsed text box would hide it enough to not pollute PRs too badly?

<details>
  <summary>SpackBot documentation</summary>
  
To have SpackBot fix your code style, comment:

 @... fix style

To have SpackBot notify package maintainers, comment
@... maintainers

For help, comment:

@... help
</details>

**Comment by alalazo** [comment]
That, or try to edit this comment :slightly_smiling_face: 





<details>

<summary>What you would see</summary>

![Screenshot from 2024-01-26 20-30-53](https://github.com/spack/spack/assets/4199709/f8b22dd7-cc1b-4229-8b4c-73a85a68e2ab)

</details>

**Comment by becker33** [comment]
Were you thinking include a static image so it takes up less space in the template?

**Comment by alalazo** [comment]
> Were you thinking include a static image so it takes up less space in the template?

No, just an HTML comment that is not visible when the markdown is rendered :smirk:

**Comment by becker33** [comment]
Oh got it. I think the collapsible is better so the PR creator and others can refer back to it.

**Comment by haampie** [comment]
I would go for a comment, cause regular contributors don't need it at some point, and then it feels a bit much to include it.

If you're reminded by a comment every time you open a PR, at some point you'll remember?
