### ISSUE TITLE
Installation issue: <gcc@13.2.0%gcc@11.4.0> 

### ISSUE THREAD

**Issue by keixthb** [LLNL/spack#42292]
#### fails using arm a53 (ubuntu 22.04 && ubuntu 20.04)

```console

Input spec
--------------------------------
 -   gcc@13.2.0%gcc@11.4.0

Concretized
--------------------------------
 -   ojimn2z  gcc@13.2.0%gcc@11.4.0~binutils+bootstrap~graphite~nvptx~piclibs~profiled~strip build_system=autotools build_type=RelWithDebInfo languages='c,c++,fortran' arch=linux-ubuntu22.04-cortex_a72
[+]  xmbsjs5      ^diffutils@3.9%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-cortex_a72
[+]  26gajy5          ^libiconv@1.17%gcc@11.4.0 build_system=autotools libs=shared,static arch=linux-ubuntu22.04-cortex_a72
[+]  dxgv4rt      ^gawk@5.2.2%gcc@11.4.0~nls build_system=autotools arch=linux-ubuntu22.04-cortex_a72
[+]  fopxrko          ^libsigsegv@2.14%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-cortex_a72
[+]  wdkmflz          ^readline@8.2%gcc@11.4.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu22.04-cortex_a72
[+]  7owtyto      ^gcc-runtime@11.4.0%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-cortex_a72
[+]  4oadkd2      ^gmake@4.4.1%gcc@11.4.0~guile build_system=generic arch=linux-ubuntu22.04-cortex_a72
[+]  hd2xd3e      ^gmp@6.2.1%gcc@11.4.0+cxx build_system=autotools libs=shared,static patches=69ad2e2 arch=linux-ubuntu22.04-cortex_a72
[+]  tyz3gfv          ^autoconf@2.72%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-cortex_a72
[+]  4cdnmmq          ^automake@1.16.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-cortex_a72
[+]  ficvuhu          ^m4@1.4.19%gcc@11.4.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-ubuntu22.04-cortex_a72
[+]  5jtzna4      ^gnuconfig@2022-09-17%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-cortex_a72
[+]  tub6g43      ^libtool@2.4.7%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-cortex_a72
[+]  clbnckc          ^findutils@4.9.0%gcc@11.4.0 build_system=autotools patches=440b954 arch=linux-ubuntu22.04-cortex_a72
[+]  azlknur      ^mpc@1.3.1%gcc@11.4.0 build_system=autotools libs=shared,static arch=linux-ubuntu22.04-cortex_a72
[+]  52irycu      ^mpfr@4.2.0%gcc@11.4.0 build_system=autotools libs=shared,static arch=linux-ubuntu22.04-cortex_a72
[+]  qwljlxj          ^autoconf-archive@2023.02.20%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-cortex_a72
[+]  ecewjrh      ^perl@5.38.0%gcc@11.4.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-ubuntu22.04-cortex_a72
[+]  dfl6nsd          ^berkeley-db@18.1.40%gcc@11.4.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu22.04-cortex_a72
[+]  ydo4meq          ^bzip2@1.0.8%gcc@11.4.0~debug~pic+shared build_system=generic arch=linux-ubuntu22.04-cortex_a72
[+]  hvukcqn          ^gdbm@1.23%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-cortex_a72
[+]  dj2yc35      ^texinfo@7.0.3%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-cortex_a72
[+]  duyh5gh          ^gettext@0.22.4%gcc@11.4.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-ubuntu22.04-cortex_a72
[+]  edlkirb              ^libxml2@2.10.3%gcc@11.4.0+pic~python+shared build_system=autotools arch=linux-ubuntu22.04-cortex_a72
[+]  rchoskw              ^tar@1.34%gcc@11.4.0 build_system=autotools zip=pigz arch=linux-ubuntu22.04-cortex_a72
[+]  7qkdo4z                  ^pigz@2.8%gcc@11.4.0 build_system=makefile arch=linux-ubuntu22.04-cortex_a72
[+]  3ltjher              ^xz@5.4.1%gcc@11.4.0~pic build_system=autotools libs=shared,static arch=linux-ubuntu22.04-cortex_a72
[+]  cyua5ng          ^ncurses@6.4%gcc@11.4.0~symlinks+termlib abi=none build_system=autotools arch=linux-ubuntu22.04-cortex_a72
[+]  tvbtcf7              ^pkgconf@1.9.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-cortex_a72
[+]  wy5mnc3      ^zlib-ng@2.1.5%gcc@11.4.0+compat+opt build_system=autotools arch=linux-ubuntu22.04-cortex_a72
[+]  ztkm2cg      ^zstd@1.5.5%gcc@11.4.0+programs build_system=makefile compression=none libs=shared,static arch=linux-ubuntu22.04-cortex_a72


```

### Error message

Make takes about 8 hours so I'll start the compile after work and update with the full report tomorrow morning.

<details><summary>Error message</summary>

make: *** [Makefile:1080 all] Error 2

<pre>
...
</pre></details>

### Information on your system

This was done using the ps side of a zcu102 FPGA. It has four cores and 4gb of ddr4. I tested it with ubuntu 22.04 and ubuntu 20.04 (gcc 9 in that case) and I get the same issue. The zcu102 has an arm a53, so spack might be reading the arch wrong.

 Here's the spack debug report:

```console 
* **Spack:** 0.22.0.dev0 (31ed39303cfb6039082c63f741781ce86cff97df)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-cortex_a72
* **Concretizer:** clingo
```

### Additional information

Maintainers: @alalazo    @michaelkuhn 

[spack-build-env.txt](https://github.com/spack/spack/files/14057206/spack-build-env.txt)

[spack-build-out.txt](https://github.com/spack/spack/files/14057209/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by keixthb** [comment]
Is there a way to manually specify the arch for spack when you create a new environment?

**Comment by yizeyi18** [comment]
If the scratch had not been deleted yet, you could use `install --dont-restage` to skip the non-error part.

**Comment by haampie** [comment]
You've attached the wrong logs? These are from `gcc-runtime`.

**Comment by keixthb** [comment]
My apologies @yizeyi18 @haampie , I ran it using the ubuntu desktop gui last night and it froze up. Looks like it hangs when I'm logged in with mouse & keyboard, and it just fails when using  

```console
sudo init 3
```

I'll run it again with run level 3 and using `install --dont-restage`, and update with the relevant logs.

**Comment by keixthb** [comment]
So this resulted in an "out of memory" error. Is there a way to reduce the memory spack install uses?

**Comment by yizeyi18** [comment]
@keithhbova Try `install -j 1` like using `make`, to reduce parallel processes. Also you could use command line only by `Ctrl+Alt+F3` before logging in.

**Comment by keixthb** [comment]
@yizeyi18 solves the issue here. For anyone from the future with the same problem: spack currently runs make by default with multiple threads. On this particular build system with the arm a53 (an eight stage, inorder pipeline), multiple threads overflow the memory and the install fails. The solution is exactly as described:

```console
spack add gcc@13.2.0%gcc@11.4.0
spack concretize
spack install -v --dont-restage -j1
```

I ran this over the weekend, so I'm not entirely sure how long it takes but the results are shown below:

![Screenshot from 2024-01-29 11-22-51](https://github.com/spack/spack/assets/144962336/5b2d2065-ea5b-4f33-8c39-a1fca6f09108)

NOTE:  @alalazo @michaelkuhn I'm still unsure why the platform is showing up as the a72 when that's not what's in the xilinx datasheet. This may be coming from ubuntu's end and might cause issues for spack in the future. I am marking as closed. Thanks for your help everyone!
