### ISSUE TITLE
Installation issue: py-cython@0.29.36:3.0.4 ^python@3.10.12

### ISSUE THREAD

**Issue by aurianer** [LLNL/spack#42315]
### Steps to reproduce the issue

tagging the maintainer here: @adamjstewart

```console
$ spack spec -l py-cython arch=cray-ubuntu22.04-x86_64 ^python@3.10.12 
Input spec
--------------------------------
 -   py-cython arch=cray-ubuntu22.04-x86_64
 -       ^python@3.10.12

Concretized
--------------------------------
 -   73ob55u  py-cython@3.0.4%gcc@12.2.0 build_system=python_pip arch=cray-ubuntu22.04-x86_64
[+]  jrkzve6      ^gcc-runtime@12.2.0%gcc@12.2.0 build_system=generic arch=cray-ubuntu22.04-x86_64
[+]  ky6nwvy      ^py-pip@23.1.2%gcc@12.2.0 build_system=generic arch=cray-ubuntu22.04-x86_64
[+]  4ud7xo4      ^py-setuptools@68.0.0%gcc@12.2.0 build_system=generic arch=cray-ubuntu22.04-x86_64
[+]  kzk6cl3      ^py-wheel@0.41.2%gcc@12.2.0 build_system=generic arch=cray-ubuntu22.04-x86_64
[e]  43rathh      ^python@3.10.12%gcc@12.2.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma+nis~optimizations+pic+pyexpat~pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=0d98e93,7d40923,ebdca64,f2fd060 arch=cray-ubuntu22.04-x86_64
```
I ran this on a cray platform but could also reproduce it on a linux platform

### Error message

<details><summary>Error message</summary>

<pre>
$ spack install py-cython ^python@3.10.12
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-x86_64-gcc-10.2.1-patchelf-0.18.0-afv7arjarb7nzmlh7c5slkfxykybuqce.spec.json
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-x86_64/gcc-10.2.1/patchelf-0.18.0/linux-centos7-x86_64-gcc-10.2.1-patchelf-0.18.0-afv7arjarb7nzmlh7c5slkfxykybuqce.spack
==> Installing "patchelf@=0.18.0%gcc@=10.2.1 ldflags='-static-libstdc++ -static-libgcc'  build_system=autotools arch=linux-centos7-x86_64" from a buildcache
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-x86_64-gcc-10.2.1-clingo-bootstrap-spack-smkmkb5xqz4v2f7tl22g4e2ghamglox5.spec.json
==> Fetching https://mirror.spack.io/bootstrap/github-actions/v0.5/build_cache/linux-centos7-x86_64/gcc-10.2.1/clingo-bootstrap-spack/linux-centos7-x86_64-gcc-10.2.1-clingo-bootstrap-spack-smkmkb5xqz4v2f7tl22g4e2ghamglox5.spack
==> Installing "clingo-bootstrap@=spack%gcc@=10.2.1~docs+ipo+optimized+python+static_libstdcpp build_system=cmake build_type=Release generator=make patches=bebb819,ec99431 arch=linux-centos7-x86_64" from a buildcache
==> Installing gcc-runtime-12.2.0-jrkzve6z4zfguwhr5eth5nn2736l3dyb [1/6]
==> No binary for gcc-runtime-12.2.0-jrkzve6z4zfguwhr5eth5nn2736l3dyb found: installing from source
==> No patches needed for gcc-runtime
==> gcc-runtime: Executing phase: 'install'
==> gcc-runtime: Successfully installed gcc-runtime-12.2.0-jrkzve6z4zfguwhr5eth5nn2736l3dyb
  Stage: 0.00s.  Install: 0.67s.  Post-install: 0.12s.  Total: 0.84s
[+] /opt/spack-f7db6bf3f90a8e1f46e6e940efe36cd3b056673b/opt/spack/cray-ubuntu22.04-x86_64/gcc-12.2.0/gcc-runtime-12.2.0-jrkzve6z4zfguwhr5eth5nn2736l3dyb
[+] /usr (external python-3.10.12-43rathhm7azeqyhkr6vaus3gwkulgchn)
==> Installing py-pip-23.1.2-ky6nwvyqrm5pkkdlhhabtxxdoznssy5a [3/6]
==> No binary for py-pip-23.1.2-ky6nwvyqrm5pkkdlhhabtxxdoznssy5a found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/3e/3ef6ac33239e4027d9a5598a381b9d30880a1477e50039db2eac6e8a8f6d1b18
==> No patches needed for py-pip
==> py-pip: Executing phase: 'install'
==> py-pip: Successfully installed py-pip-23.1.2-ky6nwvyqrm5pkkdlhhabtxxdoznssy5a
  Stage: 0.12s.  Install: 3.06s.  Post-install: 0.38s.  Total: 3.61s
[+] /opt/spack-f7db6bf3f90a8e1f46e6e940efe36cd3b056673b/opt/spack/cray-ubuntu22.04-x86_64/gcc-12.2.0/py-pip-23.1.2-ky6nwvyqrm5pkkdlhhabtxxdoznssy5a
==> Installing py-wheel-0.41.2-kzk6cl37wa76gzfxdx5azyya6dtsiolm [4/6]
==> No binary for py-wheel-0.41.2-kzk6cl37wa76gzfxdx5azyya6dtsiolm found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/75/75909db2664838d015e3d9139004ee16711748a52c8f336b52882266540215d8
==> No patches needed for py-wheel
==> py-wheel: Executing phase: 'install'
==> py-wheel: Successfully installed py-wheel-0.41.2-kzk6cl37wa76gzfxdx5azyya6dtsiolm
  Stage: 0.08s.  Install: 0.50s.  Post-install: 0.03s.  Total: 0.67s
[+] /opt/spack-f7db6bf3f90a8e1f46e6e940efe36cd3b056673b/opt/spack/cray-ubuntu22.04-x86_64/gcc-12.2.0/py-wheel-0.41.2-kzk6cl37wa76gzfxdx5azyya6dtsiolm
==> Installing py-setuptools-68.0.0-4ud7xo4e5km7p5yukj45vtmu5c2rawiz [5/6]
==> No binary for py-setuptools-68.0.0-4ud7xo4e5km7p5yukj45vtmu5c2rawiz found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/11/11e52c67415a381d10d6b462ced9cfb97066179f0e871399e006c4ab101fc85f
==> No patches needed for py-setuptools
==> py-setuptools: Executing phase: 'install'
==> py-setuptools: Successfully installed py-setuptools-68.0.0-4ud7xo4e5km7p5yukj45vtmu5c2rawiz
  Stage: 0.10s.  Install: 0.96s.  Post-install: 0.19s.  Total: 1.32s
[+] /opt/spack-f7db6bf3f90a8e1f46e6e940efe36cd3b056673b/opt/spack/cray-ubuntu22.04-x86_64/gcc-12.2.0/py-setuptools-68.0.0-4ud7xo4e5km7p5yukj45vtmu5c2rawiz
==> Installing py-cython-3.0.4-73ob55uaswy3irh3aj7hirpj52lcf6mo [6/6]
==> No binary for py-cython-3.0.4-73ob55uaswy3irh3aj7hirpj52lcf6mo found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/2e/2e379b491ee985d31e5faaf050f79f4a8f59f482835906efe4477b33b4fbe9ff.tar.gz
==> No patches needed for py-cython
==> py-cython: Executing phase: 'install'
==> Error: ProcessError: Command exited with status 1:
    '/usr/bin/python3.10' '-m' 'pip' '-vvv' '--no-input' '--no-cache-dir' '--disable-pip-version-check' 'install' '--no-deps' '--ignore-installed' '--no-build-isolation' '--no-warn-script-location' '--no-index' '--prefix=/opt/spack-f7db6bf3f90a8e1f46e6e940efe36cd3b056673b/opt/spack/cray-ubuntu22.04-x86_64/gcc-12.2.0/py-cython-3.0.4-73ob55uaswy3irh3aj7hirpj52lcf6mo' '.'

1 error found in build log:
     372      creating build/temp.linux-x86_64-cpython-310/tmp/aurianer/spack-stage
     373      creating build/temp.linux-x86_64-cpython-310/tmp/aurianer/spack-stage/spack-stage-py-cy
            thon-3.0.4-73ob55uaswy3irh3aj7hirpj52lcf6mo
     374      creating build/temp.linux-x86_64-cpython-310/tmp/aurianer/spack-stage/spack-stage-py-cy
            thon-3.0.4-73ob55uaswy3irh3aj7hirpj52lcf6mo/spack-src
     375      creating build/temp.linux-x86_64-cpython-310/tmp/aurianer/spack-stage/spack-stage-py-cy
            thon-3.0.4-73ob55uaswy3irh3aj7hirpj52lcf6mo/spack-src/Cython
     376      creating build/temp.linux-x86_64-cpython-310/tmp/aurianer/spack-stage/spack-stage-py-cy
            thon-3.0.4-73ob55uaswy3irh3aj7hirpj52lcf6mo/spack-src/Cython/Compiler
     377      /opt/spack-f7db6bf3f90a8e1f46e6e940efe36cd3b056673b/lib/spack/env/gcc/gcc -Wno-unused-r
            esult -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -
            Werror=format-security -g -fwrapv -O2 -fPIC -I/usr/include/python3.10 -c /tmp/aurianer/sp
            ack-stage/spack-stage-py-cython-3.0.4-73ob55uaswy3irh3aj7hirpj52lcf6mo/spack-src/Cython/C
            ompiler/Parsing.c -o build/temp.linux-x86_64-cpython-310/tmp/aurianer/spack-stage/spack-s
            tage-py-cython-3.0.4-73ob55uaswy3irh3aj7hirpj52lcf6mo/spack-src/Cython/Compiler/Parsing.o
  >> 378    /tmp/aurianer/spack-stage/spack-stage-py-cython-3.0.4-73ob55uaswy3irh3aj7hirpj52lcf6mo/sp
            ack-src/Cython/Compiler/Parsing.c:31:10: fatal error: Python.h: No such file or directory
     379         31 | #include "Python.h"
     380            |          ^~~~~~~~~~
     381      compilation terminated.
     382      error: command '/opt/spack-f7db6bf3f90a8e1f46e6e940efe36cd3b056673b/lib/spack/env/gcc/g
            cc' failed with exit code 1
     383      error: subprocess-exited-with-error
     384    

See build log for details:
  /tmp/aurianer/spack-stage/spack-stage-py-cython-3.0.4-73ob55uaswy3irh3aj7hirpj52lcf6mo/spack-build-out.txt

</pre></details>

### Information on your system

$ spack debug report
* **Spack:** 0.22.0.dev0
* **Python:** 3.10.12
* **Platform:** cray-ubuntu22.04-haswell
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Can you upload the build log and environment files? Is this an externally-installed Python or a Spack-installed Python? Does the `<prefix>/include/pythonX.Y/Python.h` file exist in the Python installation prefix?

**Comment by aurianer** [comment]
Actually closing this, it seems to be related to the system python, works when installing from spack, thanks!
EDIT: will try to update the answer to all of your questions once I have more time :)

**Comment by adamjstewart** [comment]
In that case you probably have `python` but not `python-dev` (or whatever your system package manager calls it). So the executables, but not the development headers.
