### ISSUE TITLE
LLVM: Is cxx11 still a dependency?

### ISSUE THREAD

**Issue by yizeyi18** [LLNL/spack#42314]
Currently for package llvm, `flags.append(self.compiler.cxx11_flag)` still lies in `packages.py`, although llvm had been using c++17 partly; that makes in compilation of some files, cxx11 flag (from spack) and cxx17 flag (from cmake) appear in one single command.
As the cxx11 flag was introduced in spack (by commit [https://github.com/spack/spack/commit/c55041e9d47cba97fc461c088c4b935b3355e340](url) ) even earlier than cxx17 standard, is it still a dependency compiling llvm? Could it be removed, at least for some newer compiler?

@haampie  @skosukhin  @trws

**Comment by haampie** [comment]
Uh, very unlikely, I would just remove it. Their CMake should handle this, Spack doesn't have to set it.
