### ISSUE TITLE
Spack complains of missing patch file when staging hsf sqlite package 

### ISSUE THREAD

**Issue by gartung** [LLNL/spack#4236]
This appears to be an incomplete override of builtin.sqlite by hsf.sqlite. The hsf.sqlite package does not have a patch. I appears to pick up newer version from hsf.sqlite which does have a patch.

 spack stage hsf.sqlite
==> Error: No such patch file for package sqlite: /home/gartung/hep-spack/packages/sqlite/sqlite_b0.patch

If the hsf repo is removed then 
spack stage sqlite 
works as expected.

**Comment by alalazo** [comment]
@gartung Do you mean:

>  It appears to pick up newer version from **builtin.sqlite** which does have a patch.

? 

In case can you post your `repos.yaml` and recipe for `sqlite`?

**Comment by gartung** [comment]
@alalzo It has two newer and on older version than builtin.sqlite

https://github.com/HEP-SF/hep-spack/blob/master/repo.yaml

https://github.com/HEP-SF/hep-spack/blob/master/packages/sqlite/package.py

[gartung@gartung spack]$ cat etc/spack/repos.yaml 
repos:
- /home/gartung/hep-spack

**Comment by alalazo** [comment]
@gartung I was able to reproduce a similar problem, but for me it goes the opposite way.

File: `$spack/etc/spack/repos.yaml`
```yaml
repos:
  - /home/mculpo/github/hep-spack
```

File: `$spack/etc/spack/defaults/repos.yaml`
```yaml
repos:
  - $spack/var/spack/repos/builtin
```
What I see is the following:
```console
$ spack info sqlite
Package:    sqlite
Homepage:   www.sqlite.org

Safe versions:  
    3.16.2    http://www.sqlite.org/2017/sqlite-autoconf-3160200.tar.gz
    3.12.2    http://www.sqlite.org/2016/sqlite-autoconf-3120200.tar.gz
    3.8.5     http://www.sqlite.org/2014/sqlite-autoconf-3080500.tar.gz

Variants:
    None

Installation Phases:
    install

Build Dependencies:
    None

Link Dependencies:
    None

Run Dependencies:
    None

Virtual Packages: 
    None

Description:
    SQLite3 is an SQL database engine in a C library. Programs that link the
    SQLite3 library can have SQL database access without running a separate
    RDBMS process.

$ spack info hsf.sqlite
Package:    sqlite
Homepage:   www.sqlite.org

Safe versions:  
    3.16.2    http://www.sqlite.org/2017/sqlite-autoconf-3160200.tar.gz
    3.12.2    http://www.sqlite.org/2016/sqlite-autoconf-3120200.tar.gz
    3.8.5     http://www.sqlite.org/2014/sqlite-autoconf-3080500.tar.gz

Variants:
    None

Installation Phases:
    install

Build Dependencies:
    None

Link Dependencies:
    None

Run Dependencies:
    None

Virtual Packages: 
    None

Description:
    SQLite3 is an SQL database engine in a C library. Programs that link the
    SQLite3 library can have SQL database access without running a separate
    RDBMS process.

$ spack info builtin.sqlite
==> Error: No such patch file for package sqlite: /home/mculpo/github/hep-spack/packages/sqlite/sqlite_b0.patch
```
---------

If instead I put both repos in `$spack/etc/spack/defaults/repos.yaml` everything seems to be working as expected. This make me think that the problem may happen during the merge of the configurations. Does it make sense to you (or am I seeing another problem)?

**Comment by gartung** [comment]
Yes I think you are on the right track.

**Comment by adamjstewart** [comment]
I agree that this is a bug worth fixing, but out of curiousity, why don't you just contribute those other versions of sqlite back to Spack and use the builtin version?

**Comment by gartung** [comment]
Never got around to it.

**Comment by gartung** [comment]
But we also have requirements for building builtin packages that require our own copy.

**Comment by adamjstewart** [comment]
Well, until the repo situation is figured out, it might be easiest for you to use the builtin sqlite.

**Comment by alalazo** [comment]
@gartung It's kind of difficult to debug this: the configuration part seems to be working fine, in the sense that the two repos are always constructed in the order you expect (had a look at them with a debugger).

From what I could see the problems start to happen when a user-defined repository has higher priority than the built-in one. My best bet so far is some bug in the import process, but I still couldn't figure what the wrong part is. The code raises during one of our import hooks customization:
```python
module = imp.load_source(fullname, file_path)            
```
Will try to dig further.

**Comment by alalazo** [comment]
Found the culprit. At line 93 of `patch.py` the call
```python
pkg_dir = spack.repo.dirname_for_package_name(pkg.name)
```
is returning the wrong repository for the package `sqlite`.
