### ISSUE TITLE
`pkg.windows_establish_runtime_linkage()` runs in the wrong place

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#42445]
Missed in review of https://github.com/spack/spack/pull/31930

The following

https://github.com/spack/spack/blob/9c4e44a0ad2a65f12a8cc4ee88729208ab78844b/lib/spack/spack/installer.py#L1694-L1697

is executed after post install hooks are run, but modifies files in the package's prefix.

That means it mutates the prefix after the `write_install_manifest` post install hook, which is wrong.

It should really itself be a post-install hook that runs before `write_install_manifest`.

**Comment by johnwparent** [comment]
What is `write_install_manifest` responsible for doing?

**Comment by haampie** [comment]
Used for `spack verify`
