### ISSUE TITLE
Installation issue: numpy becasue of openblas

### ISSUE THREAD

**Issue by d-beltran** [LLNL/spack#42453]
### Steps to reproduce the issue

It is openblas which fails to build when you run `spack install py-numpy`
However there is no error if you run `spack install openblas`

### Error message

```
 Error: ProcessError: Command exited with status 2:
     'make' '-j8' '-s' 'CC=/home/dbeltran/libraries/spack/lib/spack/env/clang/clang' 'FC=/home/dbeltran/libraries/spack/lib/spack/env/clang/flang' 'MAKE_NB_JOBS=0' 'ARCH=x86_64' 'TARGET=SKYLAKEX' 'NO_AVX512=1' 'USE_LOCKING=1' 'USE_OPENMP=0' 'USE_THREAD=0' 'TIMER=INT_CPU_TIME' 'RANLIB=ranlib' 'all'
 
 6 errors found in build log:
      29    ar: `u' modifier ignored since `D' is the default (see `U')
      30    ar: `u' modifier ignored since `D' is the default (see `U')
      31    ar: `u' modifier ignored since `D' is the default (see `U')
      32    ar: `u' modifier ignored since `D' is the default (see `U')
      33    [spack cc] ERROR: Compiler 'clang@=8.0.0' does not have a Fortran 90 compiler configured.
      34    [spack cc] ERROR: Compiler 'clang@=8.0.0' does not have a Fortran 90 compiler configured.
   >> 35    make[2]: *** [Makefile:66: spotrf2.o] Error 1
      36    make[2]: *** Waiting for unfinished jobs....
   >> 37    make[2]: *** [Makefile:66: sgetrf2.o] Error 1
      38    [spack cc] ERROR: Compiler 'clang@=8.0.0' does not have a Fortran 90 compiler configured.
   >> 39    make[2]: *** [Makefile:66: sgbbrd.o] Error 1
      40    [spack cc] ERROR: Compiler 'clang@=8.0.0' does not have a Fortran 90 compiler configured.
   >> 41    make[2]: *** [Makefile:66: sgbcon.o] Error 1
   >> 42    make[1]: *** [Makefile:27: lapacklib] Error 2
   >> 43    make: *** [Makefile:280: netlib] Error 2
```

I have searched the internet about this clang and fortran compiler problem but all I have tried has failed so far.

### Information on your system

* **Spack:** 0.22.0.dev0 (9c4e44a0ad2a65f12a8cc4ee88729208ab78844b)
* **Python:** 3.10.8
* **Platform:** linux-ubuntu18.04-skylake
* **Concretizer:** clingo

### Additional information

Hi @adamjstewart and @rgommers ,

As stated previously, when I try to install py-numpy it fails when building openblas.
However, if I run `spack install openblas` it works perfectly.
They both try to install the same version of openblas but with different "code".
py-numpy -> openblas-0.3.26-gukytilksef6pzpxfqyx3pejcswnhsjo
openblas -> openblas-0.3.26-hkmfaajh2fgg7vxrzw3ssohup7pgqv7a

This also happened to me some time ago, with the previous version:
py-numpy -> openblas-0.3.25-mlmmbcuvqkdwgxjnjfzm3vnhr5l63wy5
openblas -> openblas-0.3.25-vbsvndx4o7sms5rv4dy3sipohwjjby3s

Any clues?

[spack-build-out.txt](https://github.com/spack/spack/files/14142630/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/14142632/spack-build-env.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [x] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Not sure exactly what's going on here. Can you reproduce the different openblas configuration if you use `spack install --fresh` so that pre-installed packages are ignored?

**Comment by d-beltran** [comment]
![openblas](https://github.com/spack/spack/assets/44979434/1a3c6e41-199a-449a-bad5-8c033be790f5)
![numpy](https://github.com/spack/spack/assets/44979434/20bf18f3-800e-44da-8633-5c338d35d9da)

**Comment by keixthb** [comment]
@d-beltran Have you tried compiling openblas with spack, and referencing it inside a python env with numpy installed using pip? 

I'm not sure if that fits your use case, but for example:

```console
spack add openblas
spack concretize
spack install 
```
and then:

```console
python3.12 -m venv foo
source !$/bin/activate
pip install --upgrade pip
pip install numpy
```

**Comment by adamjstewart** [comment]
I can't copy-n-paste since it's a picture, but can you try:
```console
> spack diff /hkmf /guky
```
You may need to add more characters from the hash to differentiate them. This should tell you the difference between the two installations. But it might only work after they are successfully installed, I'm not sure.

**Comment by adamjstewart** [comment]
One is building with GCC and one is building with Clang. Have you tried building py-numpy with GCC instead of Clang? Also, do you have a flang compiler installed? What's the output of `spack config get compilers`?

**Comment by keixthb** [comment]
@adamjstewart I can definitely see this being an issue. @d-beltran you might try manually specifying the compiler for each install (using the output from ```spack config get compilers```) and record the output. For example:

```console
spack add openblas%your_compiler_goes_here
spack add py-numpy%your_compiler_goes_here
spack concretize
spack install -v
```

**Comment by d-beltran** [comment]
@adamjstewart,

> What's the output of spack config get compilers?

compilers:
- compiler:
    spec: clang@=6.0.0
    paths:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: null
      fc: null
    flags: {}
    operating_system: ubuntu18.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: clang@=8.0.0
    paths:
      cc: /usr/bin/clang-8
      cxx: /usr/bin/clang++-8
      f77: null
      fc: null
    flags: {}
    operating_system: ubuntu18.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []
- compiler:
    spec: gcc@=7.5.0
    paths:
      cc: /usr/bin/gcc
      cxx: /usr/bin/g++
      f77: /usr/bin/gfortran
      fc: /usr/bin/gfortran
    flags: {}
    operating_system: ubuntu18.04
    target: x86_64
    modules: []
    environment: {}
    extra_rpaths: []

**Comment by d-beltran** [comment]
@adamjstewart, @keithhbova,

> Have you tried building py-numpy with GCC instead of Clang?

> you might try manually specifying the compiler

`spack install py-numpy%gcc` worked!

Thank you :)

**Comment by adamjstewart** [comment]
Gotcha. The issue is that OpenBLAS and scipy require a Fortran compiler to build, but you were trying to build them with Clang, which doesn't have a Fortran compiler. You can either install Flang or GFortran and combine it with Clang, or use GCC instead.

As far as I can tell the issue has been solved, but let me know if you still have any questions.

**Comment by d-beltran** [comment]
The issue is solved to me but others may have the same problem.
Should we edit the openblas package to add flang/gfortran as dependency or force gcc as the compiler (not sure of how to do this)?
I see this package has no maintainers

**Comment by adamjstewart** [comment]
Spack does not yet register compilers as formal "dependencies", but there is a lot of work planned to make this happen in the near future (1 year timescale). So it should be possible to do this soonish. Once that happens, we can revisit this discussion.
