### ISSUE TITLE
Unusual behavior cross-compiling x86_64-aarch64

### ISSUE THREAD

**Issue by keixthb** [LLNL/spack#42466]
### Steps to reproduce

I am trying to compile a CentOS 9 Stream system from source. My target platform is an AMD ZCU-102 FPGA using a NVidia H100 accelerator. I am following a similar process as [this](https://xilinx-wiki.atlassian.net/wiki/spaces/A/pages/230948865) article. To do this, I need a x86_64-aarch64 cross-compiler. Does spack officially support this? Reading the documentation, I saw that we can specify the target using:

```console
git clone --depth=100 https://github.com/spack/spack.git ~/spack
echo "source ~/spack/share/spack/setup-env.sh" >> ~/.bashrc
echo "spacktivate" >> !$
source !$
spack add gcc@13.2.0 target=aarch64
```

...but when I concertize,
```console
spack concretize
```

### Error message

I get this error:

<details><summary>Error message</summary>

<pre>

lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.320033] Reading config from file /home/admin/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.350353] Reading config from file /home/admin/spack/var/spack/environments/default/spack.yaml
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.353385] Reading config from file /home/admin/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.373422] Reading config from file /home/admin/spack/var/spack/environments/default/spack.yaml
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.376204] Reading config from file /home/admin/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.395809] Reading config from file /home/admin/spack/var/spack/environments/default/spack.yaml
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.398479] Reading config from file /home/admin/spack/etc/spack/defaults/config.yaml
lib/spack/spack/environment/environment.py:222 ==> [2024-02-02-15:41:08.417371] Using environment 'default'
lib/spack/spack/cmd/__init__.py:119 ==> [2024-02-02-15:41:08.420699] Imported concretize from built-in commands
lib/spack/spack/cmd/__init__.py:119 ==> [2024-02-02-15:41:08.421211] Imported concretize from built-in commands
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.424458] Reading config from file /home/admin/spack/var/spack/environments/default/spack.yaml
lib/spack/spack/environment/environment.py:246 ==> [2024-02-02-15:41:08.426768] Deactivated environment 'default'
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.427397] Reading config from file /home/admin/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.447503] Reading config from file /home/admin/spack/var/spack/environments/default/spack.yaml
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.450407] Reading config from file /home/admin/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.469588] Reading config from file /home/admin/spack/var/spack/environments/default/spack.yaml
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.472346] Reading config from file /home/admin/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.491664] Reading config from file /home/admin/spack/var/spack/environments/default/spack.yaml
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.494345] Reading config from file /home/admin/spack/etc/spack/defaults/config.yaml
lib/spack/spack/environment/environment.py:222 ==> [2024-02-02-15:41:08.513524] Using environment 'default'
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.513936] Reading config from file /home/admin/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.521062] Reading config from file /home/admin/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.656019] Reading config from file /home/admin/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/database.py:645 ==> [2024-02-02-15:41:08.683549] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:181 ==> [2024-02-02-15:41:08.683718] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.684741] Reading config from file /home/admin/spack/etc/spack/defaults/mirrors.yaml
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.688801] Reading config from file /home/admin/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.694965] Reading config from file /home/admin/spack/var/spack/environments/default/spack.yaml
lib/spack/spack/environment/environment.py:246 ==> [2024-02-02-15:41:08.697288] Deactivated environment 'default'
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.698607] Reading config from file /home/admin/spack/etc/spack/defaults/repos.yaml
lib/spack/spack/bootstrap/config.py:125 ==> [2024-02-02-15:41:08.700904] [BOOTSTRAP CONFIG SCOPE] name=_builtin
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.701319] Reading config from file /home/admin/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/config.py:138 ==> [2024-02-02-15:41:08.707097] [BOOTSTRAP CONFIG SCOPE] name=defaults, path=/home/admin/spack/etc/spack/defaults
lib/spack/spack/bootstrap/config.py:139 ==> [2024-02-02-15:41:08.707249] [BOOTSTRAP CONFIG SCOPE] name=defaults/linux, path=/home/admin/spack/etc/spack/defaults/linux
lib/spack/spack/bootstrap/config.py:138 ==> [2024-02-02-15:41:08.707363] [BOOTSTRAP CONFIG SCOPE] name=bootstrap, path=/home/admin/.spack/bootstrap/config
lib/spack/spack/bootstrap/config.py:139 ==> [2024-02-02-15:41:08.707471] [BOOTSTRAP CONFIG SCOPE] name=bootstrap/linux, path=/home/admin/.spack/bootstrap/config/linux
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.708225] Reading config from file /home/admin/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.728129] Reading config from file /home/admin/.spack/bootstrap/config/linux/config.yaml
lib/spack/spack/database.py:645 ==> [2024-02-02-15:41:08.737926] DATABASE LOCK TIMEOUT: 60s
lib/spack/spack/store.py:181 ==> [2024-02-02-15:41:08.738060] PACKAGE LOCK TIMEOUT: No timeout
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.738486] Reading config from file /home/admin/.spack/bootstrap/config/linux/compilers.yaml
lib/spack/spack/bootstrap/_common.py:227 ==> [2024-02-02-15:41:08.868102] [BOOTSTRAP ROOT SPEC] patchelf@0.13.1: %gcc target=x86_64
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.868523] Reading config from file /home/admin/spack/etc/spack/defaults/bootstrap.yaml
lib/spack/spack/bootstrap/_common.py:186 ==> [2024-02-02-15:41:08.878855] [BOOTSTRAP EXECUTABLES patchelf] Try installed specs with query 'patchelf@0.13.1: %gcc target=x86_64'
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.881181] Reading config from file /home/admin/spack/etc/spack/defaults/modules.yaml
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.891718] Reading config from file /home/admin/spack/etc/spack/defaults/linux/modules.yaml
lib/spack/spack/build_environment.py:1014 ==> [2024-02-02-15:41:08.909789] Adding env modifications for patchelf
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:08.911906] Reading config from file /home/admin/spack/etc/spack/defaults/packages.yaml
lib/spack/spack/bootstrap/_common.py:227 ==> [2024-02-02-15:41:08.940666] [BOOTSTRAP ROOT SPEC] gnupg@2.3: %gcc target=x86_64
lib/spack/spack/bootstrap/_common.py:227 ==> [2024-02-02-15:41:08.941704] [BOOTSTRAP ROOT SPEC] clingo-bootstrap@spack+python %gcc target=x86_64
lib/spack/spack/bootstrap/core.py:380 ==> [2024-02-02-15:41:08.941820] [BOOTSTRAP MODULE clingo] Try importing from Python
lib/spack/spack/bootstrap/_common.py:79 ==> [2024-02-02-15:41:09.004203] [BOOTSTRAP MODULE clingo] The installed spec "clingo-bootstrap@spack+python %gcc target=x86_64 ^python@3.9/bhqgwuvef354fwuxq7heeighavunpber" provides the "clingo" Python module
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:09.004989] Reading config from file /home/admin/spack/etc/spack/defaults/config.yaml
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:09.025327] Reading config from file /home/admin/spack/var/spack/environments/default/spack.yaml
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:09.028025] Reading config from file /home/admin/spack/etc/spack/defaults/config.yaml
lib/spack/spack/environment/environment.py:222 ==> [2024-02-02-15:41:09.047245] Using environment 'default'
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:09.047613] Reading config from file /home/admin/spack/etc/spack/defaults/concretizer.yaml
lib/spack/spack/config.py:1095 ==> [2024-02-02-15:41:09.054137] Reading config from file /home/admin/spack/etc/spack/defaults/packages.yaml
/home/admin/spack/lib/spack/spack/solver/concretize.lp:1071:10-54: info: atom does not occur in any rule head:
  compiler_supports_target(CompilerID,Target)

/home/admin/spack/lib/spack/spack/solver/concretize.lp:1072:6-41: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/admin/spack/lib/spack/spack/solver/concretize.lp:1073:6-43: info: atom does not occur in any rule head:
  compiler_version(CompilerID,Version)

/home/admin/spack/lib/spack/spack/solver/concretize.lp:1106:44-67: info: atom does not occur in any rule head:
  compiler_id(CompilerID)

/home/admin/spack/lib/spack/spack/solver/concretize.lp:1114:6-45: info: atom does not occur in any rule head:
  compiler_name(CompilerID,CompilerName)

/home/admin/spack/lib/spack/spack/solver/concretize.lp:1115:6-51: info: atom does not occur in any rule head:
  compiler_version(CompilerID,CompilerVersion)

/home/admin/spack/lib/spack/spack/solver/concretize.lp:1121:6-45: info: atom does not occur in any rule head:
  compiler_name(CompilerID,CompilerName)

/home/admin/spack/lib/spack/spack/solver/concretize.lp:1122:6-51: info: atom does not occur in any rule head:
  compiler_version(CompilerID,CompilerVersion)

/home/admin/spack/lib/spack/spack/solver/concretize.lp:1160:6-41: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/admin/spack/lib/spack/spack/solver/concretize.lp:1179:6-41: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/admin/spack/lib/spack/spack/solver/concretize.lp:1180:6-43: info: atom does not occur in any rule head:
  compiler_version(CompilerID,Version)

/home/admin/spack/lib/spack/spack/solver/concretize.lp:1181:10-37: info: atom does not occur in any rule head:
  compiler_os(CompilerID,OS)

/home/admin/spack/lib/spack/spack/solver/concretize.lp:1208:5-40: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/admin/spack/lib/spack/spack/solver/concretize.lp:1209:5-36: info: atom does not occur in any rule head:
  compiler_version(CompilerID,V)

/home/admin/spack/lib/spack/spack/solver/concretize.lp:1210:5-40: info: atom does not occur in any rule head:
  compiler_weight(CompilerID,Weight)

/home/admin/spack/lib/spack/spack/solver/concretize.lp:1214:5-40: info: atom does not occur in any rule head:
  compiler_name(CompilerID,Compiler)

/home/admin/spack/lib/spack/spack/solver/concretize.lp:1215:5-36: info: atom does not occur in any rule head:
  compiler_version(CompilerID,V)

/home/admin/spack/lib/spack/spack/solver/concretize.lp:1216:9-39: info: atom does not occur in any rule head:
  compiler_weight(#X0,#P1)

/home/admin/spack/lib/spack/spack/solver/concretize.lp:1240:6-29: info: atom does not occur in any rule head:
  compiler_id(CompilerID)

/home/admin/spack/lib/spack/spack/solver/concretize.lp:1275:6-29: info: atom does not occur in any rule head:
  compiler_id(CompilerID)

lib/spack/spack/main.py:1069 ==> [2024-02-02-15:41:12.221115] UnsatisfiableSpecError: concretization failed for the following reasons:

   1. No valid value for variant 'build_system' of package 'gcc'
   2. No valid compiler version found for 'zstd'
   3. No valid compiler version found for 'zlib-ng'
   4. No valid compiler version found for 'texinfo'
   5. No valid compiler version found for 'readline'
   6. No valid compiler version found for 'pkgconf'
   7. No valid compiler version found for 'perl'
   8. No valid compiler version found for 'ncurses'
   9. No valid compiler version found for 'mpfr'
   10. No valid compiler version found for 'mpc'
   11. No valid compiler version found for 'm4'
   12. No valid compiler version found for 'libtool'
   13. No valid compiler version found for 'libsigsegv'
   14. No valid compiler version found for 'libiconv'
   15. No valid compiler version found for 'gmp'
   16. No valid compiler version found for 'gmake'
   17. No valid compiler version found for 'gettext'
   18. No valid compiler version found for 'gdbm'
   19. No valid compiler version found for 'gcc'
   20. No valid compiler version found for 'gawk'
   21. No valid compiler version found for 'findutils'
   22. No valid compiler version found for 'diffutils'
   23. No valid compiler version found for 'bzip2'
   24. No valid compiler version found for 'berkeley-db'
   25. No valid compiler version found for 'automake'
   26. No valid compiler version found for 'autoconf'
   27. Cannot find compatible targets for gcc and zstd
   28. Cannot find compatible targets for gcc and zlib-ng
   29. Cannot find compatible targets for gcc and texinfo
   30. Cannot find compatible targets for gcc and perl
   31. Cannot find compatible targets for gcc and mpfr
   32. Cannot find compatible targets for gcc and mpc
   33. Cannot find compatible targets for gcc and libtool
   34. Cannot find compatible targets for gcc and gmp
   35. Cannot find compatible targets for gcc and gmake
   36. Cannot find compatible targets for gcc and gawk
   37. Cannot find compatible targets for gcc and diffutils
   38. 'gcc target=aarch64' is not compatible with this machine

</pre></details>

### Information on your system

This was run on an intel i9 9900k. 

```console
* **Spack:** 0.22.0.dev0 (8fa8dbc26998bf5bd23b096b522e4d6258e9e75d)
* **Python:** 3.9.18
* **Platform:** linux-centos9-skylake
* **Concretizer:** clingo
```

@alalazo  @michaelkuhn I  built the bootstrap kernel using the binaries from gnu's website, but when I deploy on the FPGA, I'm getting strange errors that might be traced back to combining the two compilers. Is there an officially supported way to build the cross-compiler? Is ```gcc target=aarch64``` really not compatiable with my machine? Thanks in advance!

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
Spack doesn't support cross compilation

**Comment by keixthb** [comment]
@haampie understood, thank you!
