### ISSUE TITLE
Installation issue: CompilerAccessError: Compiler 'aocc@=4.1.0' has executables that are missing or are not executable

### ISSUE THREAD

**Issue by DanielYang59** [LLNL/spack#42467]
### Steps to reproduce the issue

I was trying to install `AOCL` with `AOCC@4.1.0` with `spack`. For some reason I was getting `CompilerAccessError: Compiler 'aocc@=4.1.0' has executables that are missing or are not executable`. What might be the reason? Thanks.

```bash
(base) yanghaoyu@epyc-server:~/HPC-tuning/spack/share/spack$ spack compilers
==> Available compilers
-- aocc ubuntu22.04-x86_64 --------------------------------------
aocc@4.1.0

-- gcc ubuntu22.04-x86_64 ---------------------------------------
gcc@11.4.0
(base) yanghaoyu@epyc-server:~/HPC-tuning/spack/share/spack$ spack load aocc
(base) yanghaoyu@epyc-server:~/HPC-tuning/spack/share/spack$ which clang
/home/yanghaoyu/HPC-tuning/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/aocc-4.1.0-crxs4lvh4pevhxiwscxrfhbdpmiyubez/bin/clang
(base) yanghaoyu@epyc-server:~/HPC-tuning/spack/share/spack$ spack install amdblis %aocc
```

### Error message

<details><summary>Error message</summary>

<pre>
(base) yanghaoyu@epyc-server:~/HPC-tuning/spack/share/spack$ spack install amdblis %aocc
==> Installing gmake-4.4.1-ob32mfo26n2v3gbvli4haoqcxil2jbjl [1/28]
==> No binary for gmake-4.4.1-ob32mfo26n2v3gbvli4haoqcxil2jbjl found: installing from source
==> Error: CompilerAccessError: Compiler 'aocc@=4.1.0' has executables that are missing or are not executable: ['/home/yanghaoyu/opt/spack-develop/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/aocc-4.1.0-2z5qkhsrp3blofawip3v5ym63nadxp67/bin/clang', '/home/yanghaoyu/opt/spack-develop/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/aocc-4.1.0-2z5qkhsrp3blofawip3v5ym63nadxp67/bin/clang++', '/home/yanghaoyu/opt/spack-develop/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/aocc-4.1.0-2z5qkhsrp3blofawip3v5ym63nadxp67/bin/flang', '/home/yanghaoyu/opt/spack-develop/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/aocc-4.1.0-2z5qkhsrp3blofawip3v5ym63nadxp67/bin/flang']
==> Warning: Skipping build of libmd-1.0.4-jnazy2fcbsubs65flzy4pvdbii56ydsk since gmake-4.4.1-ob32mfo26n2v3gbvli4haoqcxil2jbjl failed
==> Warning: Skipping build of libbsd-0.11.7-r52hxwt4wksybh6w3nkkgkwjzukbqqca since libmd-1.0.4-jnazy2fcbsubs65flzy4pvdbii56ydsk failed
==> Warning: Skipping build of expat-2.5.0-lvhkpuu6wsgqaupm4hb4dwyt2yzt2euv since libbsd-0.11.7-r52hxwt4wksybh6w3nkkgkwjzukbqqca failed
==> Warning: Skipping build of python-3.11.7-f4cg6vvrn263kpizj35agoderjnpgidm since expat-2.5.0-lvhkpuu6wsgqaupm4hb4dwyt2yzt2euv failed
==> Warning: Skipping build of amdblis-4.1-ftqhr5ri57azhpnlaqspn4vo4c35hwv6 since python-3.11.7-f4cg6vvrn263kpizj35agoderjnpgidm failed
==> Warning: Skipping build of libxml2-2.10.3-gmc4d54sv6zpitevmcbdkm7jvdkjlj47 since gmake-4.4.1-ob32mfo26n2v3gbvli4haoqcxil2jbjl failed
==> Warning: Skipping build of gettext-0.22.4-kdhuudkzs3wt47riwgkqqtggey45g2xt since libxml2-2.10.3-gmc4d54sv6zpitevmcbdkm7jvdkjlj47 failed
==> Warning: Skipping build of bzip2-1.0.8-lnjwntyogqf3xzqeo5qwvrzr2rjxzrir since gmake-4.4.1-ob32mfo26n2v3gbvli4haoqcxil2jbjl failed
==> Warning: Skipping build of perl-5.38.0-t3q4znunaf6owwcwway2mhv42yuc2qxe since bzip2-1.0.8-lnjwntyogqf3xzqeo5qwvrzr2rjxzrir failed
==> Warning: Skipping build of libxcrypt-4.4.35-pdovhuh75s5kiy55o46vs4jjknid32dp since perl-5.38.0-t3q4znunaf6owwcwway2mhv42yuc2qxe failed
==> Warning: Skipping build of openssl-3.1.3-d4e543pludkup5ehpag6373wugjd6aox since perl-5.38.0-t3q4znunaf6owwcwway2mhv42yuc2qxe failed
==> Warning: Skipping build of tar-1.34-y25tvxwwuv5f753h6cvzx3vh6q5oauqf since bzip2-1.0.8-lnjwntyogqf3xzqeo5qwvrzr2rjxzrir failed
==> Warning: Skipping build of readline-8.2-c3e66bx3lqypkeya43dbaglfdsroj4r5 since gmake-4.4.1-ob32mfo26n2v3gbvli4haoqcxil2jbjl failed
==> Warning: Skipping build of gdbm-1.23-mz4cpn565vdgzq35hekfgjkdzdfigeuu since readline-8.2-c3e66bx3lqypkeya43dbaglfdsroj4r5 failed
==> Warning: Skipping build of sqlite-3.43.2-bs47imr7hdqhsralhievbwhjmdbybyen since readline-8.2-c3e66bx3lqypkeya43dbaglfdsroj4r5 failed
==> Warning: Skipping build of libffi-3.4.4-xiewyin2n4oq7mt52odvdgjycup6zjti since gmake-4.4.1-ob32mfo26n2v3gbvli4haoqcxil2jbjl failed
==> Warning: Skipping build of pigz-2.8-jxwelrzg3tcb3wmr3hkd3vdcriqc5sd7 since gmake-4.4.1-ob32mfo26n2v3gbvli4haoqcxil2jbjl failed
==> Warning: Skipping build of zstd-1.5.5-cqmek2i5xdixjbjud4kedmx4ie3z4yrw since gmake-4.4.1-ob32mfo26n2v3gbvli4haoqcxil2jbjl failed
==> Warning: Skipping build of ncurses-6.4-nfmyolednbgyh4y2dyppml6q5r4nhshu since gmake-4.4.1-ob32mfo26n2v3gbvli4haoqcxil2jbjl failed
==> Warning: Skipping build of diffutils-3.9-wnk6ttmb5m7euj5uvtz6tarvobvflnkb since gmake-4.4.1-ob32mfo26n2v3gbvli4haoqcxil2jbjl failed
==> Warning: Skipping build of pkgconf-1.9.5-tzmo4ucyvpkqkrtrxsawswlj2txxguij since gmake-4.4.1-ob32mfo26n2v3gbvli4haoqcxil2jbjl failed
==> Warning: Skipping build of util-linux-uuid-2.38.1-i5tb2edqhnnlhwhcinohnqlusfxjsufj since pkgconf-1.9.5-tzmo4ucyvpkqkrtrxsawswlj2txxguij failed
==> Warning: Skipping build of zlib-ng-2.1.5-i335xn6ggfh7ovrxwuc6knceawo3csjh since gmake-4.4.1-ob32mfo26n2v3gbvli4haoqcxil2jbjl failed
==> Warning: Skipping build of berkeley-db-18.1.40-6pi6oqxafueydyfp7tajjzxps6gojmoj since gmake-4.4.1-ob32mfo26n2v3gbvli4haoqcxil2jbjl failed
==> Warning: Skipping build of xz-5.4.1-e32cdzac2ygsdfm6nwu4cgvxl26vglwt since gmake-4.4.1-ob32mfo26n2v3gbvli4haoqcxil2jbjl failed
==> Warning: Skipping build of libiconv-1.17-edu4o3rhbgshgj6nehk53sdgpnou43az since gmake-4.4.1-ob32mfo26n2v3gbvli4haoqcxil2jbjl failed
==> Installing ca-certificates-mozilla-2023-05-30-5uvthwzkyxbyd57afrkr6zr2lrhtzgpx [2/28]
==> No binary for ca-certificates-mozilla-2023-05-30-5uvthwzkyxbyd57afrkr6zr2lrhtzgpx found: installing from source
==> Error: CompilerAccessError: Compiler 'aocc@=4.1.0' has executables that are missing or are not executable: ['/home/yanghaoyu/opt/spack-develop/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/aocc-4.1.0-2z5qkhsrp3blofawip3v5ym63nadxp67/bin/clang', '/home/yanghaoyu/opt/spack-develop/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/aocc-4.1.0-2z5qkhsrp3blofawip3v5ym63nadxp67/bin/clang++', '/home/yanghaoyu/opt/spack-develop/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/aocc-4.1.0-2z5qkhsrp3blofawip3v5ym63nadxp67/bin/flang', '/home/yanghaoyu/opt/spack-develop/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/aocc-4.1.0-2z5qkhsrp3blofawip3v5ym63nadxp67/bin/flang']
==> Error: amdblis-4.1-ftqhr5ri57azhpnlaqspn4vo4c35hwv6: Package was not installed
==> Error: Installation request failed.  Refer to reported errors for failing package(s).
</pre></details>

### Information on your system

* **Spack:** 0.22.0.dev0 (8fa8dbc26998bf5bd23b096b522e4d6258e9e75d)
* **Python:** 3.11.5
* **Platform:** linux-ubuntu22.04-zen3
* **Concretizer:** clingo

### Additional information

@amd-toolchain-support

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by amd-toolchain-support** [comment]
Hi there,  it looks like AOCC may have been removed and reinstalled since doing `spack compiler find`.    If you take a look at the logs you will notice that Spack is looking for your AOCC to have hash `2z5qkhsrp3blofawip3v5ym63nadxp67`, while your installed AOCC has hash `crxs4lvh4pevhxiwscxrfhbdpmiyubez`.  Because the hash is part of the install path, and Spack uses fully qualified paths to its compilers rather than relying on `$PATH` it can't find the correct executable.

Can you please try removing the existing reference to AOCC and then rerunning `spack compiler find`?

```shell
$ spack compiler rm aocc@4.1.0
$ spack load aocc
$ spack compiler find
```

Note: 
```
==> Error: CompilerAccessError: Compiler 'aocc@=4.1.0' has executables that are missing or are not executable: ['
/home/yanghaoyu/opt/spack-develop/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/aocc-4.1.0-2z5qkhsrp3blofawip3v5ym63nadxp67/bin/clang'
```

vs.

```
(base) yanghaoyu@epyc-server:~/HPC-tuning/spack/share/spack$ which clang
/home/yanghaoyu/HPC-tuning/spack/opt/spack/linux-ubuntu22.04-zen3/gcc-11.4.0/aocc-4.1.0-crxs4lvh4pevhxiwscxrfhbdpmiyubez/bin/clang
```

**Comment by DanielYang59** [comment]
Hi @amd-toolchain-support, thanks a ton for pointing out the issue, new lesson learned and problem solved. Deeply appreciate that and wishing you a wonderful day. Huge love to AMD 💖!
