### ISSUE TITLE
For some packages (dos2unix, lmod) untaring the package results in errors when using tar built with spack instead of using /bin/tar

### ISSUE THREAD

**Issue by samfux84** [LLNL/spack#4247]
Hi,

I have built tar with spack:

spack install tar@1.29 %gcc@4.8.5 arch=linux-centos7-x86_64

The package has built without giving any error message. I would like spack to use this tar version to unpack the sources for any other spack package that is installed. For most packages this works without any problem. For some cases (dos2unix, lmod), using the self-compiled tar instead of the one in /bin/tar results in error messages:

```
[spackapps@lo-login-02 bin]$ spack install dos2unix@7.3.4 %gcc@4.8.5 arch=linux-centos7-x86_64
==> Installing dos2unix
==> Fetching https://waterlan.home.xs4all.nl/dos2unix/dos2unix-7.3.4.tar.gz
######################################################################## 100.0%
==> Staging archive: /cluster/apps/spack/var/spack/stage/dos2unix-7.3.4-zlsgdhmavstgkyubcnmucmi3gfb3cqrm/dos2unix-7.3.4.tar.gz
/cluster/spack/apps/linux-centos7-x86_64/sfos/bin/tar: Skipping to next header
/cluster/spack/apps/linux-centos7-x86_64/sfos/bin/tar: Exiting with failure status due to previous errors
==> Error: ProcessError: Command exited with status 2:
    '/cluster/spack/apps/linux-centos7-x86_64/sfos/bin/tar' '-xf' '/cluster/apps/spack/var/spack/stage/dos2unix-7.3.4-zlsgdhmavstgkyubcnmucmi3gfb3cqrm/dos2unix-7.3.4.tar.gz'
/cluster/apps/spack/lib/spack/spack/package.py:939, in do_stage:
     932      def do_stage(self, mirror_only=False):
     933          """Unpacks the fetched tarball, then changes into the expanded tarball
     934             directory."""
     935          if not self.spec.concrete:
     936              raise ValueError("Can only stage concrete packages.")
     937  
     938          self.do_fetch(mirror_only)
  >> 939          self.stage.expand_archive()
     940          self.stage.chdir_to_source()


[spackapps@lo-login-02 bin]$
```
When using the tar version from /bin/tar, the error does not show up.

Did anyone else also notice this problem ?

**Comment by adamjstewart** [comment]
I am unable to reproduce this problem.
```
$ spack install -v --run-tests tar
$ export PATH=/home/ajstewart/spack/opt/spack/linux-fedora25-x86_64/gcc-6.2.1/tar-1.29-cuhiobelvg3aodsovoobamkceqj4v72v/bin:$PATH
$ which tar
/home/ajstewart/spack/opt/spack/linux-fedora25-x86_64/gcc-6.2.1/tar-1.29-cuhiobelvg3aodsovoobamkceqj4v72v/bin/tar
$ spack -d stage dos2unix
==> '/home/ajstewart/spack/opt/spack/linux-fedora25-x86_64/gcc-6.2.1/tar-1.29-cuhiobelvg3aodsovoobamkceqj4v72v/bin/tar' '-xf' '/home/ajstewart/spack/var/spack/stage/dos2unix-7.3.4-g7nt5z3nsnzyrqy4gjz46orhdw4n4yfu/dos2unix-7.3.4.tar.gz'
$ spack -d stage lmod
==> '/home/ajstewart/spack/opt/spack/linux-fedora25-x86_64/gcc-6.2.1/tar-1.29-cuhiobelvg3aodsovoobamkceqj4v72v/bin/tar' '-xf' '/home/ajstewart/spack/var/spack/stage/lmod-7.4.11-nxj4exoczchihdtir6nzutosrprsnfs2/7.4.11.tar.gz'
```
Can you try rebuilding `tar` with `--run-tests`? I'm interested to see which (if any) of its unit tests fail. I have noticed that some of the sparse file tests have crashed for me. I reported this to the developers but they never responded.

**Comment by adamjstewart** [comment]
Repeated my above tests specifically for `tar@1.29 %gcc@4.8.5 arch=linux-centos7-x86_64` and still couldn't reproduce the problem.

**Comment by samfux84** [comment]
@adamjstewart Thank you for having a look at the problem. I have rebuilt tar with --run-tests and there were no tests failing:

```
## ------------- ##
## Test results. ##
## ------------- ##

181 tests were successful.
23 tests were skipped.
```

I noticed one thing. I have compiled tar once with

cxxflags = ['-O2', '-fPIC', '-ftree-vectorize', '-march=core-avx2', '-mavx2']

and once with

cxxflags = ['-O2', '-fPIC', '-ftree-vectorize', '-march=corei7', '-msse4']

With the SSE4 version I can also not reproduce the problem, whereas the MAVX2 version the problem is reproducible. Therefore I think it is somehow related to the "march" and "mavx2" compiler flags. I think not many people will be affected by this, therefore I close the issue.

If somebody is affected by this problem, then it can be solved by recompiling tar without -mavx2 and -march=core-avx2
