### ISSUE TITLE
hdf5@1.8.18 +mpi c++ error (with intel and intelmpi)

### ISSUE THREAD

**Issue by cnelson3** [LLNL/spack#4250]
Hi All,
I'm trying to install hdf5 1.8.18 with Spack, using the Intel 2017 compiler, IntelMPI 2017, both of which are installed external to spack.

The build crashes out when it gets to the C++ section, as the build complains (correctly) that it can't find:
/awe/intel/impi/2017.1.132/intel64/bin/mpic++    This file doesn't exist in the intel MPI directory. - I assume that it should be pointing to /awe/intel/impi/2017.1.132/intel64/bin/mpicxx?

This file is specified when spack issues the hdf5 configuration stage by setting the CXX flag.

Does anyone know where this is set?

The hdf5 package.py, has the line:
```
202:                  if '+cxx' in spec
202:                      extra_args.append("CXX=%s" % spec.['mpi']/mpicxx)

```
I then looked in in the Intel-parallel-studio package.py file
at the end there is the line:

```
424:         self.spec.mpicxx = join.path(bindir, 'mpic++')
```
I tried changing the mpic++ to mpicxx, but to no avail.

Does anyone have any ideas?

(I cloned a fresh version of spack today)

cheers,

Chris.

**Comment by adamjstewart** [comment]
> I tried changing the mpic++ to mpicxx, but to no avail.

Can you elaborate? Did the error message change to being unable to find:
```
/awe/intel/impi/2017.1.132/intel64/bin/mpicxx
```
or did it remain the same? Can you give us the output of `spack config get packages`? Are you using `intel` or `intel-parallel-studio` to build hdf5? Do you actually have a license for Intel MPI (the cluster edition comes with it but not professional or composer). Did you build `intel-parallel-studio@cluster.2017.1 +all` or `+mpi`?

**Comment by cnelson3** [comment]
Hi Adam,
No the error message in the spack-build.out remains the same.
I can't easily get you the output of the `spack config get packages` as it is a computer not on the internet. (mayhabve themsometime tomorrow)
in the packages.yaml file, I've specified`
```
packages:
  intel-parallel-studio:
    modules:
      intel-parallel-studio@cluster.2017.1%intel@17.0.1 arch=Linux-opensuse12-x86_64: intelmpi/2017.1-intel
    buildable: False
```
if that is of any help?
and, yes we have the necessary licenses for intel MPI.
we didn't build intel-parallel-studio - this was installed by our sys admins external to spack.

I will hopefully be able to share some files tomorrow.

Thanks.

**Comment by adamjstewart** [comment]
Thanks @cnelson3. Can you try changing `intel-parallel-studio` to `intel-mpi` in your `packages.yaml` and build with `intel-mpi` instead? `intel-parallel-studio` may have a different installation directory layout (I've seen this before with `intel-mkl`). It's also not a good idea to trick Spack into thinking that you have the full `intel-parallel-studio` suite installed when you actually only have `intel-mpi` installed.

**Comment by cnelson3** [comment]
Thanks @adamjstewart, that seems to have fixed it - thought I don't understand why, as we have the full intel-parallel-studio suite installed.
cheers,
Chris.
