### ISSUE TITLE
Updating PSyclone package (`py-psyclone`) to latest release 2.5.0

### ISSUE THREAD

**Issue by oakleybrunt** [LLNL/spack#42578]
Add support for the PSyclone release 2.5.0. This requires the fparser release 0.1.4.

Changes in dependencies since PSyclone 2.4.0 release:

#### PSyclone
`jsonschema` version is not specified any more. See https://github.com/stfc/PSyclone/commit/b2eb7793ecec6db1f6ea52960c75d1100871a3a5.
    pylint version is pinned down to < 3.0 (only important for PSyclone development on target platform). See https://github.com/stfc/PSyclone/commit/2215d085642c0009f586c1c9ecb00c4f7b5cad4c.

#### fparser
`setuptools_scm` is required as a dependency and setuptools version is specified to >= 61. See https://github.com/stfc/fparser/commit/835c26b0b387514c031166d7b4f4c19668ebab48.

### Spack recipes
For info, the [recipe for fparser 0.1.3](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-fparser/package.py) is now on Spack repository. **Need to add 0.1.4.**
[PSyclone recipe](https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/py-psyclone/package.py. ), however, is still very old (latest change for 1.5.0). I suggest **adding all major versions between and including 1.6.0 and 2.5.0.**

**Comment by alalazo** [comment]
Feel free to submit a PR for this update and ping me in there :slightly_smiling_face: I'm going to close the issue since usually we don't have issues to request the addition of a new version to a package[^1].

[^1]: With ~7k packages that would be unmaneageable. Usually contributors submit a PR to add the new version and discussion on requirements is held there, if needed.

**Comment by oakleybrunt** [comment]
> Feel free to submit a PR for this update and ping me in there 🙂 I'm going to close the issue since usually we don't have issues to request the addition of a new version to a package[1](#user-content-fn-1-12c3f6477a4857fb7bd43124c3acba07).
> ## Footnotes
> 
>     1. With ~7k packages that would be unmaneageable. Usually contributors submit a PR to add the new version and discussion on requirements is held there, if needed. [↩](#user-content-fnref-1-12c3f6477a4857fb7bd43124c3acba07)

No problem, thank you for letting me know!
