### ISSUE TITLE
concretization of environment quietly fails to concretize some roots

### ISSUE THREAD

**Issue by payerle** [LLNL/spack#42608]
### Steps to reproduce

**Overview** 

I build large software libraries using rather complicated set of Spack environments.  Concretization is painful, many iterations of spack concretize, fixing constraints, and repeat, but eventually I get something to concretize and then begin the "fun" of building.  Recently I encountered a situation wherein the environment concretized w/out any errors or warning diagnostics, b ut some of the root specs in the environment where not concretized.

I.e., "spack concretization" command seemingly succeeded, and spack find for the environment listed all the root specs I expected, but one of the root specs was not in the specs output by the concretization command, and was not in the spack.lock file.  

I was able to trace the problem to issues with the environment config file, but spack did not complain about the issues, just silently decided not to concretize the package.  I consider this a bug.
I was able to trace the problem to issues with the environment config file, but spack did not complain about the issues, just silently decided not to concretize the package.  I consider this a bug.

**Simplified example to reproduce issue**
(relevant files attached afterwards)
```console
$ git  clone https://github.com/spack/spack.git spack.tptest
...
$ cd spack.tptest
$ cp ~/spack.tptest.configs/*.yaml ./etc/spack/
$ ./bin/spack env create tptest
...
$ cp ~/spack.yaml.tptest ./var/spack/environments/tptest/spack.yaml
$ cat var/spack/environments/tptest/spack.yaml
# Test of issue with concretizer
spack:
  concretizer:
    unify: when_possible
    reuse: false
  specs:
    - openmpi %gcc@8.5.0 ^openmpi@4.1.5 arch=linux-rhel8-x86_64
    - spfft +mpi ~cuda ~rocm  %gcc@8.5.0 ^openmpi@4.1.5 arch=linux-rhel8-x86_64
    - caffe ~cuda %gcc@8.5.0 ^openmpi@4.1.5 arch=linux-rhel8-x86_64
  view: false
  packages:
    protobuf:
      require: [ '@3.21.12' ]
$
$ spack --env tptest find
==> In environment tptest
==> Root specs
-- no arch / gcc@8.5.0 ------------------------------------------
caffe%gcc@8.5.0 ~cuda
openmpi%gcc@8.5.0
spfft%gcc@8.5.0 ~cuda+mpi~rocm
$
$ spack --env tptest concretize -f --fresh
... (putput available  below)
$
$ spack --env tptest install caffe

==> Error: Cannot install 'caffe' because no matching specs are in the current environment. You can add specs to the environment with 'spack add caffe', or as part of the install command with 'spack install --add caffe'
$
$ grep caffe var/spack/environments/tptest/spack.lock
$
```
Notes:
1) caffe shows up as a root spec in spack --env tptest find command
2) The output of spack --env tptest concretize looks normal, a list of specs concretized.  Note that caffe and openmpi do not appear as concretized roots (although openmpi is there as a dependency of spfft).  In general, with dozens of root specs in the environment, the failure to list one or two here would go unnoticed,
3) caffe does not appear in the spack.lock file

This is the spack,yaml file used (e.g. ~/spack.yaml.tptest)
[spack.yaml.txt](https://github.com/spack/spack/files/14226799/spack.yaml.txt)

These are the spack configuration files:
[compilers.yaml.txt](https://github.com/spack/spack/files/14226806/compilers.yaml.txt)
[concretizer.yaml.txt](https://github.com/spack/spack/files/14226807/concretizer.yaml.txt)
[config.yaml.txt](https://github.com/spack/spack/files/14226808/config.yaml.txt)
[modules.yaml.txt](https://github.com/spack/spack/files/14226809/modules.yaml.txt)
[packages.yaml.txt](https://github.com/spack/spack/files/14226810/packages.yaml.txt)
[repos.yaml.txt](https://github.com/spack/spack/files/14226811/repos.yaml.txt)

These are the command outputs from the example script above:
Output of spack --env tptest find
[tptest.find.txt](https://github.com/spack/spack/files/14226820/tptest.find.txt)
Output of spack --env tptest concretize -f --fresh
[tptest.concretize-f--fresh.txt](https://github.com/spack/spack/files/14226825/tptest.concretize-f--fresh.txt)
Output of spack --env tptest --debug --stacktrace concretize -f --fresh
[tptest.concretize-f--fresh-debug-stacktrace.txt](https://github.com/spack/spack/files/14226827/tptest.concretize-f--fresh-debug-stacktrace.txt)
Output of spack --env tptest install caffe
[tptest.install-caffe.txt](https://github.com/spack/spack/files/14226829/tptest.install-caffe.txt)

### Error message

I acknowledge that there are issues with the environments spack.yaml, but I expected Spack to complain about those issues, not just silently drop the request.  The issues with the spack.yaml are:
1) The openmpi root spec has a dependency on itself.  (This was not quite so
obvious in the original version which used matrix root specs). a
2) caffe cannot concretize because caffe depends on protobuf@:3.17 and we are
constraining protobuf to @3.21.12.

I am assuming that the openmpi ^openmpi spec should be considered as an
invalid spec, as openmpi is not a dependency of itself.  And while I expect
it to be a rare occurrence to have such an spec given explicitly like in
this example, the use of matrix specs and list references might allow such
abnormal specs to occur in less obvious ways.  (E.g., in the real case
environment for which this issue first cropped up, I had a list of matrices
for packages depending on MPI but not CUDA/ROCM to be installed; one matrix
for packages with boolean mpi, cuda, and rocm flags, one for packages with
boolean mpi, cuda but no rocm flags, one for packages with just boolean
mpi flags, one for packages with MPI dependencies but no mpi, cuda, or rocm
flags.  To ensure packages in the latter were built to depend on +mpi versions
of any dependencies which had + and ~ mpi variants, I added a ^openmpi to
the outer product.  Somehow, openmpi got added to that somewhat long list
of packages, at which point it was not trivially obvious that this would
produce an effective "openmpi ^openmpi" spec).

Again, I suspect such specs should be considered as invalid by Spack, but
in such cases they should produce an error message, as Spack does in other
cases of attempts to write a spec with a dependency on a package which the
original package does not depend on, e.g.
```console
$ ./bin/spack spec -lI cmake ^hdf5
==> Error: Package cmake does not depend on hdf5
```
If openmpi ^openmpi is considered as a valid (albeit unusual) spec, then:
1) openmpi should have been conretized as a root spec for the environment
2) the inability to concretize caffe and/or protobuf should have caused an error

With the spack,yaml as given in the simplified example, the concretization
appears to only concretize the spfft root spec; openmpi and caffe do not
appear to be concretized as roots (although openmpi gets concretized as a
dependency of spfft),  But there are no warnings or errors; openmpi and caffe
simply get quietly dropped as roots.

If I remove the 'spfft' root spec (all else as in the original spack.yaml),
the concretization proceeds with no error or warning messages, but no specs
are output either.  And no spack.lock is produced.  This seems to be consistent
with the above (only spfft being concretized as a root spec), and while the
lack of specs being printed and lack of a spack.lock file strongly suggest a
problem, the presence of any concretizable root spec will cause a spack.lock to
be created and a list of specs to be output by the concretization command.

If I remove the ^openmpi@4.1.5 part of the openmpi root spec (again, all
else as in the original spack.yaml) , the concretization
fails with the error message:
```console
==> Error: concretization failed for the following reasons:

   1. cannot satisfy a requirement for package 'protobuf'.
```
This is the expected result (although a more informative error message would be nice:)

### Information on your system

```console
 ./bin/spack debug report
* **Spack:** 0.22.0.dev0 (27b72b76918e9c14df1ca81e7a3e929a4fc44e7e)
* **Python:** 3.6.8
* **Platform:** linux-rhel8-skylake
* **Concretizer:** clingo
```

My apologies in advance, but I will have very limited ability to respond for the next week.  I will respond the following week.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by scheibelp** [comment]
I think I see where we can improve this - thanks for the report!

We improved related messages in [55bbb10](https://github.com/spack/spack/commit/55bbb1098436d6ac9d83fea0715a3daa7be02ed3) from Feb 23rd

However, because this uses `unify: when_possible`, the change there will not help. I think @becker33 we assumed that `solve_in_rounds` would fail in this case, but as I inspect it now, I think it will just bail on

```
            if not result.satisfiable or not result.specs:
                break
```

(specifically the `not result.specs` part: once we whittle the set of specs down to only specs we cannot resolve, this would be empty)
