### ISSUE TITLE
mesa@23.0.3 build fails: libgallium.a.p/gallivm_lp_bld_init.c.o: lp_bld_init.c:45:10: fatal error: llvm-c/Transforms/Scalar.h: No such file or directory

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#42632]
### Steps to reproduce the issue

`mesa@23.0.3` build is failing for us using:
* Ubuntu 20.04, AMD64
* GCC 11.4.0

We are trying to install this so that we can build `glvis` package. We see the same `mesa` build error on all of:
* Ubuntu 20.04, ARM64, GCC 11.4.0
* Ubuntu 22.04, AMD64, OneAPI 2024
* Ubuntu 20.04, PPC64, GCC 11.4.0
* OEL 8, AMD64, GCC 11.2.1

Spack environment: [spack.yaml.txt](https://github.com/spack/spack/files/14251935/spack.yaml.txt)

<details><summary>Concretization</summary>

<pre>
 -   mesa@23.0.3%gcc@11.4.0+glx+llvm+opengl~opengles+osmesa~strip build_system=meson buildtype=release default_library=shared arch=linux-ubuntu20.04-x86_64
[+]      ^bison@3.8.2%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^diffutils@3.9%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^gmake@4.4.1%gcc@11.4.0~guile build_system=generic arch=linux-ubuntu20.04-x86_64
[+]          ^m4@1.4.19%gcc@11.4.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-ubuntu20.04-x86_64
[+]              ^libsigsegv@2.14%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^perl@5.38.0%gcc@11.4.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-ubuntu20.04-x86_64
[+]              ^berkeley-db@18.1.40%gcc@11.4.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu20.04-x86_64
[+]      ^cmake@3.27.9%gcc@11.4.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-ubuntu20.04-x86_64
[+]          ^curl@8.4.0%gcc@11.4.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-ubuntu20.04-x86_64
[+]              ^nghttp2@1.57.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^ncurses@6.3%gcc@11.4.0~symlinks+termlib abi=none build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]      ^expat@2.5.0%gcc@11.4.0+libbsd build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^libbsd@0.11.7%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^libmd@1.0.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]      ^flex@2.6.3%gcc@11.4.0+lex~nls build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^findutils@4.9.0%gcc@11.4.0 build_system=autotools patches=440b954 arch=linux-ubuntu20.04-x86_64
[+]      ^gcc-runtime@11.4.0%gcc@11.4.0 build_system=generic arch=linux-ubuntu20.04-x86_64
[+]      ^gettext@0.22.4%gcc@11.4.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^bzip2@1.0.8%gcc@11.4.0~debug~pic+shared build_system=generic arch=linux-ubuntu20.04-x86_64
[+]          ^libiconv@1.17%gcc@11.4.0 build_system=autotools libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]          ^libxml2@2.10.3%gcc@11.4.0+pic~python+shared build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^tar@1.34%gcc@11.4.0 build_system=autotools zip=pigz arch=linux-ubuntu20.04-x86_64
[+]              ^pigz@2.8%gcc@11.4.0 build_system=makefile arch=linux-ubuntu20.04-x86_64
[+]              ^zstd@1.5.5%gcc@11.4.0+programs build_system=makefile compression=none libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]          ^xz@5.4.1%gcc@11.4.0+pic build_system=autotools libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]      ^glproto@1.4.17%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^util-macros@1.19.3%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]      ^libunwind@1.6.2%gcc@11.4.0~block_signals~conservative_checks~cxx_exceptions~debug~debug_frame+docs+pic+tests+weak_backtrace+xz~zlib build_system=autotools components=none libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]      ^libx11@1.8.7%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^inputproto@2.3.2%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^kbproto@1.0.7%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^xextproto@7.3.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^xproto@7.0.31%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^xtrans@1.5.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]      ^libxcb@1.16%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^libpthread-stubs@0.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^libxau@1.0.11%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^libxdmcp@1.1.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^xcb-proto@1.16.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]      ^libxext@1.3.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]      ^libxt@1.3.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^libice@1.1.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^libsm@1.2.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]      ^llvm@17.0.4%gcc@11.4.0+clang~cuda~flang+gold~ipo+libomptarget~libomptarget_debug~link_llvm_dylib+lld+lldb+llvm_dylib+lua~mlir+polly~python~split_dwarf~z3~zstd build_system=cmake build_type=Release compiler-rt=runtime generator=ninja libcxx=runtime libunwind=runtime openmp=runtime shlib_symbol_version=none targets=all version_suffix=none arch=linux-ubuntu20.04-x86_64
[+]          ^binutils@2.41%gcc@11.4.0~gas+gold~gprofng+headers~interwork+ld+libiberty~lto~nls~pgo+plugins build_system=autotools compress_debug_sections=zlib libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]          ^hwloc@2.9.1%gcc@11.4.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-ubuntu20.04-x86_64
[+]              ^libpciaccess@0.17%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]                  ^libtool@2.4.7%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^libedit@3.1-20210216%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^libffi@3.4.4%gcc@11.4.0 build_system=autotools patches=070b1f3 arch=linux-ubuntu20.04-x86_64
[+]          ^lua@5.3.6%gcc@11.4.0~pcfile+shared build_system=makefile fetcher=curl arch=linux-ubuntu20.04-x86_64
[+]              ^unzip@6.0%gcc@11.4.0 build_system=makefile arch=linux-ubuntu20.04-x86_64
[+]          ^perl-data-dumper@2.173%gcc@11.4.0 build_system=perl arch=linux-ubuntu20.04-x86_64
[+]          ^swig@4.1.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^pcre2@10.42%gcc@11.4.0~jit+multibyte build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]      ^meson@1.2.2%gcc@11.4.0 build_system=python_pip patches=0f0b1bd,ae59765 arch=linux-ubuntu20.04-x86_64
[+]          ^py-pip@23.1.2%gcc@11.4.0 build_system=generic arch=linux-ubuntu20.04-x86_64
[+]          ^py-setuptools@68.0.0%gcc@11.4.0 build_system=generic arch=linux-ubuntu20.04-x86_64
[+]          ^py-wheel@0.41.2%gcc@11.4.0 build_system=generic arch=linux-ubuntu20.04-x86_64
[+]      ^ninja@1.11.1%gcc@11.4.0+re2c build_system=generic arch=linux-ubuntu20.04-x86_64
[+]          ^re2c@2.2%gcc@11.4.0 build_system=generic arch=linux-ubuntu20.04-x86_64
[+]      ^pkgconf@1.9.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]      ^py-mako@1.2.4%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu20.04-x86_64
[+]          ^py-markupsafe@2.1.3%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu20.04-x86_64
[+]      ^python@3.11.6%gcc@11.4.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=13fa8bf,b0615b2,ebdca64,f2fd060 arch=linux-ubuntu20.04-x86_64
[+]          ^gdbm@1.23%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^libxcrypt@4.4.35%gcc@11.4.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-ubuntu20.04-x86_64
[+]          ^openssl@3.1.3%gcc@11.4.0~docs+shared build_system=generic certs=mozilla arch=linux-ubuntu20.04-x86_64
[+]              ^ca-certificates-mozilla@2023-05-30%gcc@11.4.0 build_system=generic arch=linux-ubuntu20.04-x86_64
[+]          ^readline@8.2%gcc@11.4.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu20.04-x86_64
[+]          ^sqlite@3.43.2%gcc@11.4.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^util-linux-uuid@2.38.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]      ^xrandr@1.5.2%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^libxrandr@1.5.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]              ^renderproto@0.11.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^libxrender@0.9.11%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]          ^randrproto@1.5.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu20.04-x86_64
[+]      ^zlib-ng@2.1.5%gcc@11.4.0+compat+opt build_system=autotools arch=linux-ubuntu20.04-x86_64
</pre></details>

Reproduced here using Docker container image `ecpe4s/ubuntu20.04-runner-amd64-gcc-11.4-mpi-base:2023.08.20` and publicly cached binaries:

```
$> docker run -it ecpe4s/ubuntu20.04-runner-amd64-gcc-11.4-mpi-base:2023.08.20
root@8f846a385d35:/# git clone https://github.com/spack/spack
root@8f846a385d35:/# git -C /spack checkout 2064934ed3c02edeab05bbd5719df6acf5743784
root@8f846a385d35:/# . spack/share/spack/setup-env.sh

root@8f846a385d35:/# spack mirror add E4S https://cache.e4s.io/24.02
root@8f846a385d35:/# spack buildcache keys -it

# Download spack.yaml attached near top of this issue description
root@8f846a385d35:/# spack -e . install
...
==> Installing mesa-23.0.3-f4wtakejru73ei6tlkz227y2gxxwuted [81/84]
==> No binary for mesa-23.0.3-f4wtakejru73ei6tlkz227y2gxxwuted found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/38/386362a5d80df3b096636b67f340e1ce67b705b44767d5bdd11d2ed1037192d5.tar.xz
==> Ran patch() for mesa
==> mesa: Executing phase: 'meson'
==> mesa: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 1:
    'ninja' '-j16' '-v'
...
  >> 1067    FAILED: src/gallium/auxiliary/libgallium.a.p/gallivm_lp_bld_init.c.o
     1068    /spack/lib/spack/env/gcc/gcc -Isrc/gallium/auxiliary/libgallium.a.p -Isrc/gallium/auxiliary -I../spack-src/src/gallium/auxiliary -Isrc/loader -I../spack-src/src/loader -I../
             spack-src/src/gallium/include -Isrc -I../spack-src/src -Iinclude -I../spack-src/include -I../spack-src/src/gallium/auxiliary/util -Isrc/compiler/nir -I../spack-src/src/compi
             ler/nir -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.4.0/zlib-ng-2.1.5-5x6i3wn4nd3uvng3wggbb6n7jjqrqpv6/include -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.4.0/
             zstd-1.5.5-xlag2ogmesbivpmveq3abu4doxstckwd/include -I/spack/opt/spack/linux-ubuntu20.04-x86_64/gcc-11.4.0/libunwind-1.6.2-gda2zh73vqsl6ojzkpo3katmnrhcwmiw/include -fvisibil
             ity=hidden -fdiagnostics-color=always -DNDEBUG -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c11 -O3 '-DPACKAGE_VERSION="23.0.3"' '-DPACKAGE_BUGREPORT="https://gitlab.free
             desktop.org/mesa/mesa/-/issues"' -DHAVE_SWRAST -DVIDEO_CODEC_VC1DEC=0 -DVIDEO_CODEC_H264DEC=0 -DVIDEO_CODEC_H264ENC=0 -DVIDEO_CODEC_H265DEC=0 -DVIDEO_CODEC_H265ENC=0 -DHAVE_
             X11_PLATFORM -DHAVE_XCB_PLATFORM -DENABLE_ST_OMX_BELLAGIO=0 -DENABLE_ST_OMX_TIZONIA=0 -DUSE_XSHM -DENABLE_SHADER_CACHE -DHAVE___BUILTIN_BSWAP32 -DHAVE___BUILTIN_BSWAP64 -DHA
             VE___BUILTIN_CLZ -DHAVE___BUILTIN_CLZLL -DHAVE___BUILTIN_CTZ -DHAVE___BUILTIN_EXPECT -DHAVE___BUILTIN_FFS -DHAVE___BUILTIN_FFSLL -DHAVE___BUILTIN_POPCOUNT -DHAVE___BUILTIN_P
             OPCOUNTLL -DHAVE___BUILTIN_UNREACHABLE -DHAVE___BUILTIN_TYPES_COMPATIBLE_P -DHAVE_FUNC_ATTRIBUTE_CONST -DHAVE_FUNC_ATTRIBUTE_FLATTEN -DHAVE_FUNC_ATTRIBUTE_MALLOC -DHAVE_FUNC
             _ATTRIBUTE_PURE -DHAVE_FUNC_ATTRIBUTE_UNUSED -DHAVE_FUNC_ATTRIBUTE_WARN_UNUSED_RESULT -DHAVE_FUNC_ATTRIBUTE_WEAK -DHAVE_FUNC_ATTRIBUTE_FORMAT -DHAVE_FUNC_ATTRIBUTE_PACKED -D
             HAVE_FUNC_ATTRIBUTE_RETURNS_NONNULL -DHAVE_FUNC_ATTRIBUTE_ALIAS -DHAVE_FUNC_ATTRIBUTE_NORETURN -DHAVE_FUNC_ATTRIBUTE_VISIBILITY -DHAVE_UINT128 -DHAVE_REALLOCARRAY -DUSE_SSE4
             1 -DUSE_GCC_ATOMIC_BUILTINS -DUSE_X86_64_ASM -DMAJOR_IN_SYSMACROS -DHAS_SCHED_H -DHAS_SCHED_GETAFFINITY -DHAVE_LINUX_FUTEX_H -DHAVE_ENDIAN_H -DHAVE_DLFCN_H -DHAVE_SYS_SHM_H
             -DHAVE_CET_H -DHAVE_STRTOF -DHAVE_MKOSTEMP -DHAVE_TIMESPEC_GET -DHAVE_MEMFD_CREATE -DHAVE_RANDOM_R -DHAVE_FLOCK -DHAVE_STRTOK_R -DHAVE_GETRANDOM -DHAVE_GNU_QSORT_R -DHAVE_ST
             RUCT_TIMESPEC -DHAVE_PROGRAM_INVOCATION_NAME -DHAVE_ISSIGNALING -DHAVE_POSIX_MEMALIGN -DHAVE_DIRENT_D_TYPE -DHAVE_STRTOD_L -DHAVE_DLADDR -DHAVE_DL_ITERATE_PHDR -DHAVE_ZLIB -
             DHAVE_ZSTD -DHAVE_COMPRESSION -DHAVE_PTHREAD -DHAVE_PTHREAD_SETAFFINITY -DLLVM_AVAILABLE '-DMESA_LLVM_VERSION_STRING="17.0.4"' -DLLVM_IS_SHARED=1 -DDRAW_LLVM_AVAILABLE -DMES
             A_EXECMEM -DHAVE_LIBUNWIND -DHAVE_OPENMP -DVK_USE_PLATFORM_XCB_KHR -DVK_USE_PLATFORM_XLIB_KHR -DVK_USE_PLATFORM_XLIB_XRANDR_EXT -DVK_USE_PLATFORM_DISPLAY_KHR -mtls-dialect=g
             nu2 -Werror=implicit-function-declaration -Werror=missing-prototypes -Werror=return-type -Werror=empty-body -Werror=incompatible-pointer-types -Werror=int-conversion -Wimpli
             cit-fallthrough -Wmisleading-indentation -Wno-missing-field-initializers -Wno-format-truncation -fno-math-errno -fno-trapping-math -fno-common -Wno-unused-function -Werror=f
             ormat -Wformat-security -ffunction-sections -fdata-sections -Wno-unused-variable -Wno-unused-but-set-variable -fPIC -DWITH_GZFILEOP -pthread -isystem/spack/opt/spack/linux-u
             buntu20.04-x86_64/gcc-11.4.0/llvm-17.0.4-vy4zlheuha4kju3y747nziri53yk23ip/include -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Werror
             =pointer-arith -Werror=vla -MD -MQ src/gallium/auxiliary/libgallium.a.p/gallivm_lp_bld_init.c.o -MF src/gallium/auxiliary/libgallium.a.p/gallivm_lp_bld_init.c.o.d -o src/gal
             lium/auxiliary/libgallium.a.p/gallivm_lp_bld_init.c.o -c ../spack-src/src/gallium/auxiliary/gallivm/lp_bld_init.c
  >> 1069    ../spack-src/src/gallium/auxiliary/gallivm/lp_bld_init.c:45:10: fatal error: llvm-c/Transforms/Scalar.h: No such file or directory
     1070       45 | #include <llvm-c/Transforms/Scalar.h>
     1071          |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
     1072    compilation terminated.
...
```

### Error message

<details><summary>Error message</summary>

<pre>
see above
</pre></details>

### Information on your system

* **Spack:** 0.22.0.dev0 (2064934ed3c02edeab05bbd5719df6acf5743784)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-cascadelake
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/14251951/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/14251952/spack-build-out.txt)

@v-dobrev @goxberry @tomstitt @tzanio (including `glvis` maintainers in case they know) @sameershende 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by v-dobrev** [comment]
It looks like this issue in mesa was fixed with this mesa PR: https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/22980 which is part of v23.2 of mesa, so I'll suggest switching to `mesa@23.2.1`. The issue seems to be due to the removal of the missing file in llvm 17 (specifically here: https://github.com/llvm/llvm-project/commit/f7ca01333214f934c580c162afdee933e7430b6c), so probably using an older llvm is another solution.

**Comment by eugeneswalker** [comment]
Closing this as resolved either by using older llvm<17 or newer `mesa@23.2.1:`

thank you @v-dobrev
