### ISSUE TITLE
Installation issue: Issue with binutils package not building the assembler binary

### ISSUE THREAD

**Issue by mmrezaie** [LLNL/spack#42675]
### Steps to reproduce the issue

```console
$ spack spec -I <spec>
Input spec
--------------------------------
 -   binutils

Concretized
--------------------------------
[+]  binutils@2.41%gcc@13.2.0~gas~gprofng~headers~interwork~ld~libiberty~lto~nls~pgo+plugins build_system=autotools compress_debug_sections=zlib libs=shared,static arch=linux-centos7-x86_64_v4
[+]      ^diffutils@3.9%gcc@13.2.0 build_system=autotools arch=linux-centos7-x86_64_v4
[+]          ^libiconv@1.17%gcc@13.2.0 build_system=autotools libs=shared,static arch=linux-centos7-x86_64_v4
[+]      ^gmake@4.4.1%gcc@13.2.0~guile build_system=generic arch=linux-centos7-x86_64_v4
[+]      ^pkgconf@1.9.5%gcc@13.2.0 build_system=autotools arch=linux-centos7-x86_64_v4
[+]      ^zlib-ng@2.1.4%gcc@13.2.0+compat+opt build_system=autotools arch=linux-centos7-x86_64_v4
[+]      ^zstd@1.5.5%gcc@13.2.0+programs build_system=makefile compression=none libs=shared,static arch=linux-centos7-x86_64_v4
```

### Error message

There is no error message. The issue is there is no built assembler binary.

ls "where binutils is being installed at"/bin:
`addr2line  ar  c++filt  elfedit  gprof  nm  objcopy  objdump  ranlib  readelf  size  strings  strip`

### Information on your system

I would like to use Spack's libgc and assembler for every package build. I have several partitions with Centos 7, Ubuntu, and Rockylinux 8. I am building binutils on the centos 7 machine. 

### Additional information

`spack debug report`:
* **Spack:** 0.21.1 (e30fedab102f9281a220fb4fae82e3f8c43a82ac)
* **Python:** 3.6.8
* **Platform:** linux-centos7-skylake_avx512
* **Concretizer:** clingo

`spack maintainers binutils
alalazo`

My env is clean for this test with only an installed gcc-13.2.0. 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
It's under a variant: `+gas`.

The reason being that just `strings` or `readelf` from `binutils` are sometimes used in packages as an actual dependency, but that should not influence what assembler / linker is used when building that package. So `depends_on("binutils")` by default does not include a linker / assembler.

**Comment by mmrezaie** [comment]
Thank you very much.
