### ISSUE TITLE
Compilers with similar versions may be mixed up without warning

### ISSUE THREAD

**Issue by adrienbernede** [LLNL/spack#42679]
[IMPORTANT EDIT]: it turns out I was not using "@=" _in the compilers.yaml_ for that specific machine.
I think my comment about spack not using the string of the compiler actually being used still holds.

### Steps to reproduce

**Reproduce**
I defined two compilers: `clang@14.0.5` and **then** `clang@14.0.5.gcc.8.3.1`. Binary path used to be the same, flags are different.
Later on, to make investigation easier, I used a different path for both compilers.

Then I asked for `spack install blt%clang@=14.0.5.gcc.8.3.1`.

I am getting no warning, the clang binary detected is the good one (same in both compilers...), and the concretization, logs and path all use the string "clang@14.0.5.gcc.8.3.1" to describe the compiler. However **Spack is in fact using clang@14.0.5**.

There is one location where a warning is printed, and that’s the .spack/spack-build-out.txt.gz in the install directory.

To investigate the behavior, I added "print("self.compiler.cc is {0}".format(self.compiler.cc))" to the BLT packages install phase.

**Analysis**
The problem is two-fold:
- Spack does considers that `clang@14.0.5` is a match for `clang@14.0.5.gcc.8.3.1`, _even when using @=_.
- Spack uses the compiler spec from the command line everywhere instead of using the `spec` field of the compiler actually being used.

**Workaround:**
We can work around the issue by defining `clang@14.0.5.gcc.8.3.1` first in the compilers.yaml. Indeed, `clang@14.0.5.gcc.8.3.1` is not considered a match for `clang@14.0.5`.

@becker33 @scheibelp @trws @white238 

### Error message

The only location where a message can be found is in the `.spack/spack-build-out.txt`. I had to use a different path for both compilers for the issue to be clearly visible:

```
==> blt: Executing phase: 'install'
==> [2024-02-14-06:41:25.597029] Installing . to /usr/WS2/bernede1/Umpire/1685064-1707749560/spack-and-build-root/spack/opt/spack/linux-rhel7-power9le/**clang-12.0.1.gcc.8.3.1**/blt-0.6.1-iqs4sbjgw6utkcstv2pgelkpk6j7zopk
==> [2024-02-14-06:41:31.032484] Multiple definitions of compiler clang@=12.0.1.gcc.8.3.1 for architecture linux-rhel7-power9le:
 [clang(**/usr/tce/packages/clang/clang-12.0.1/bin/clang**
     /usr/tce/packages/clang/clang-12.0.1/bin/clang++
     /usr/tce/packages/xl/xl-2021.09.22/bin/xlf_r
     /usr/tce/packages/xl/xl-2021.09.22/bin/xlf2003_r
     []
     rhel7), clang(/usr/tce/packages/clang/clang-12.0.1-gcc-8.3.1/bin/clang
     /usr/tce/packages/clang/clang-12.0.1-gcc-8.3.1/bin/clang++
     /usr/tce/packages/xl/xl-2021.09.22/bin/xlf_r
     /usr/tce/packages/xl/xl-2021.09.22/bin/xlf2003_r
     []
     rhel7)]
self.compiler.cc is **/usr/tce/packages/clang/clang-12.0.1/bin/clang**
```

We can clearly see here that although I asked for the second compiler, I got the first one, but the install path still suggests that I got what I asked for (so does the concretized spec).

This is printed out if I run spec in debug mode, but no reason for me to do so when there is no warning or a clue about what is really happening.

### Information on your system

* **Spack:** 0.22.0.dev0 (7d4dcd52d96b593fb5e1557794ad57a7c5eb2304)
* **Python:** 3.7.2
* **Platform:** linux-rhel7-power9le
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
Looks like a satisfies(a, b) is called with arguments swapped, I can submit a fix.

**Comment by adrienbernede** [comment]
@haampie thank you for the super fast fix. I can test that for tomorrow.
