### ISSUE TITLE
Installation issue: mpich@4.1.2 insists on detecting pmi.h even if `pmi=off`

### ISSUE THREAD

**Issue by climbfuji** [LLNL/spack#42685]
### Steps to reproduce the issue

On a system that does not have `pmi` installed (`pmi.h` etc.), for example a user laptop or docker container:
```
spack install mpich@4.1.2 pmi=off
```
The issue is that `mpich` tries to find `pmi.h` no matter what option for variant `pmi` is set. For `pmi=off`, `spack` uses
```
'/tmp/root/spack-stage/spack-stage-mpich-4.1.2-xzvi62blqdg5kd5kejlmyztcwkk5i4ht/spack-src/configure' ... '--with-pmi=no' ...
```
and the `mpich` `configure` file looks for `pmi.h`. The same happens if I try `--with-pmi=off` or `--without-pmi`. If, however, I remove the option altogether from `./configure` (i.e. no `--with-pmi=WHATEVER` and no `--without-pmi`), then the call to `configure` succeeds.

### Error message

```
configure: ===== done with src/mpi/romio configure =====
configure: sourcing src/mpi/romio/localdefs
checking pmi.h usability... no
checking pmi.h presence... no
checking for pmi.h... no
configure: error: pmi.h or libpmi library not found. Did you specify --with-pmi= or --with-pmi-include= or --with-pmi-lib=?
```

### Information on your system

```
* **Spack:** 0.22.0.dev0 (07db2824377293d08684d840c54fbca0f9f5c92c)
* **Python:** 3.8.10
* **Platform:** linux-ubuntu20.04-aarch64
* **Concretizer:** clingo
```

### Additional information

@raffenet @yfguo

[spack-build-01-autoreconf-out.txt](https://github.com/spack/spack/files/14284204/spack-build-01-autoreconf-out.txt)
[spack-build-01-install-out.txt](https://github.com/spack/spack/files/14284205/spack-build-01-install-out.txt)
[spack-build-02-configure-out.txt](https://github.com/spack/spack/files/14284206/spack-build-02-configure-out.txt)
[spack-build-env-mods.txt](https://github.com/spack/spack/files/14284207/spack-build-env-mods.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/14284208/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/14284209/spack-build-out.txt)
[spack-configure-args.txt](https://github.com/spack/spack/files/14284210/spack-configure-args.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by raffenet** [comment]
`pmi=off` should not be an option. MPICH cannot function without a PMI library.

**Comment by climbfuji** [comment]
> `pmi=off` should not be an option. MPICH cannot function without a PMI library.

Thanks for your quick reply. So what happens then if I don't specify either of `--with-pmi=...` or `--without-pmi` and `configure` runs through?

**Comment by raffenet** [comment]
By default, MPICH will use the internal embedded PMI library which is compatible with the internal process manager (Hydra). If no option is specified, the PMI v1 API and protocol will be used to communication with Hydra.

**Comment by climbfuji** [comment]
Ok, that makes sense. I think the mpich package needs some attention, not just the `pmi` option but also others. I see this for `mpich@4.1.2`:
```
configure: WARNING: unrecognized options: --without-ibverbs, --enable-wrapper-rpath, --without-cuda, --without-hip, --enable-libxml2
```

**Comment by raffenet** [comment]
> Ok, that makes sense. I think the mpich package needs some attention, not just the `pmi` option but also others. I see this for `mpich@4.1.2`:
> 
> ```
> configure: WARNING: unrecognized options: --without-ibverbs, --enable-wrapper-rpath, --without-cuda, --without-hip, --enable-libxml2
> ```

The cuda and hip warnings should be resolved in the newest version. That reminds me I need to get it added to the package 😅.

`--without-ibverbs` is another invalid option I should remove. I'll take a look at the others.

**Comment by climbfuji** [comment]
Thanks very much @raffenet!
