### ISSUE TITLE
Conditional dependencies in MFEM

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/spack#4269]
Was trying to build MFEM like so...

`spack install mfem%gcc@6.1+hypre+metis+superlu-dist+debug+netcdf+suite-sparse`

But, that failed with
```
==> Error: InstallError: mfem+suite-sparse must be built with +metis and +lapack!
/Users/miller86/spack/spack/var/spack/repos/builtin/packages/mfem/package.py:102, in check_variants:
     95       def check_variants(self, spec):
     96           if '+mpi' in spec and ('+hypre' not in spec or '+metis' not in spec):
     97               raise InstallError('mfem+mpi must be built with +hypre ' +
     98                                  'and +metis!')
     99           if '+suite-sparse' in spec and ('+metis' not in spec or
     100                                          '+lapack' not in spec):
     101              raise InstallError('mfem+suite-sparse must be built with ' +
  >> 102                                 '+metis and +lapack!')
     103          if 'metis@5:' in spec and '%clang' in spec and (
     104                  '^cmake %gcc' not in spec):
```

My first thought is to just enforce this requirement by adding following...

```
    depends_on('lapack', when='+suite-sparse')
    depends_on('metis', when='+suite-sparse')
```

But, then I was wondering if the logic in line 99, above, would still fail? I mean, would `+metis` and `+lapack` appear in spec given the `depends_on` lines above? I was thinking not.

Finally, I started wondering why MFEM included logic to check this error and I believe its because suite-sparse depends on lapack and metis...in which case, why does MFEM include any logic for this? Why doesn't it just depend on suite-sparse package to get it  right? 

So, I guess my question is, isn't this MFEM logic wrong and shouldn't it be removed?

**Comment by markcmiller86** [comment]
@adamjstewart ...can you add `question` label to this issue too?

**Comment by adamjstewart** [comment]
Ask and you shall receive

**Comment by tgamblin** [comment]
@markcmiller86: Maybe @tzanio or @goxberry can say something about why this is in the MFEM package, but they seem to already have the conditions you want in MFEM:

```python
    depends_on('blas', when='+suite-sparse')                                                                            
    depends_on('metis@5:', when='+suite-sparse ^suite-sparse@4.5:')                                                     
```

The conditions you're pointing to will fail for `suite-sparse` at versions before `4.5`.  I suspect they wrote this code before we added the directive, but you could replace their code with a `conflict` declaration, e.g.:

```python
    conflicts('^suite-sparse@:4.4')
```
