### ISSUE TITLE
Boxlib name is changing to AMReX

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/spack#4277]
So, what is the right way to handle a package name change like this? 

1. Keep boxlib package and add new AMReX package
   - What happens to all the `depends_on('boxlib'...` in all the other packages
   - Why maintain two copies of basically same package?
1. Change boxlib package to AMReX and update all `depends_on('boxlib'...` instances
   - Then, spack would loose knowledge of the boxlib name entirely and might be confusing for folks who have yet to catch up with the name change.
1. Change boxlib package to AMReX but define a 'boxlib' alias for it (can we do that?)

I like 3rd option best because it maintains knowledge of the old name

**Comment by adamjstewart** [comment]
In the past, I've gone with option 2.

**Comment by tgamblin** [comment]
Have the `boxlib` developers outlined a plan for folks who actually use `boxlib`?  Are the library names staying the same?  If not, then I would keep the old package and add a new one called `amrex`.

**Comment by markcmiller86** [comment]
So, aside from enhancing Spack proper to handle the concept of an 'alias' for a package, 2 is probably best I can do. But, what if I wanted `spack info boxlib` to still return some useful message like `Boxlib has been replaced with AMReX`. I supposed I could keep a `boxlib/package.py` so that `spack info boxlib` does something. But, then, what would happen if someone did `spack install boxlib`? Maybe make that `depends_on('AMReX',...` and then a no-op install?

**Comment by markcmiller86** [comment]
@tgamblin 

> Have the boxlib developers outlined a plan for folks who actually use boxlib? Are the library names staying the same? If not, then I would keep the old package and add a new one called amrex.

Well, I am told boxlib will stop existing and AMReX will take its place. So, that I guess means the plan will be that all users will have to adjust things...probably Makefiles at a minimum and maybe call instances in source code too

**Comment by adamjstewart** [comment]
If AMReX is a replacement for boxlib, not just a simple rename, then I would keep both packages.

**Comment by tgamblin** [comment]
Maybe @asalmgren can advise?

**Comment by markcmiller86** [comment]
@tgamblin 

> Maybe @asalmgren can advise?

That is who I have been getting this information from...Boxlib will cease to exist and AMReX will take its place.

**Comment by tgamblin** [comment]
> Boxlib will cease to exist and AMReX will take its place.

@markcmiller86: I wouldn't call that a formal description of what's going to happen.  See questions above.  Is it going to have the same library interface?  Do codes need to change to use the new package?

**Comment by markcmiller86** [comment]
Yeah, I agree...I really didn't pose that quite right. It made sense in my head though ;)

**Comment by markcmiller86** [comment]
FYI...in Spack-world anyways, looks like FASTMath is only package that currently `depends_on('boxlib'...`. Might make sense just to replace boxlib with ARMeX and update FASTMath to use that. OTOH, what about future packages that, for one reason or another, might wind up using old boxlib and not new AMReX?...

More I think about it, more I agree with @tgamblin that 1 is the right option here.
