### ISSUE TITLE
Any way to check flake8 locally automagically prior to push

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/spack#4278]
I would like to avoid pushing code to a PR that fails flake8 checks.

In my current workflow I need to remember to run flake8 checks manually on my code before I commit and push.

Is there any way to make this happen locally automagically, perhaps with a `git commit`?

**Comment by aprokop** [comment]
You can add a pre-commit git hook that does that. Something along the lines of `http://flake8.pycqa.org/en/latest/user/using-hooks.html`.

**Comment by alalazo** [comment]
@markcmiller86 Try:
```
spack flake8
```
and make sure your local `develop` branch is up to date (as it will be used for the diff).

**Comment by markcmiller86** [comment]
@alalazo ...I know how to invoke flake8. That isn't the problem. The problem is having it happen automatically **locally** so that I don't have to keep remembering to do it before I push. I don't like delaying PRs due to flake8 failures.

**Comment by markcmiller86** [comment]
@aprokop ...oh, great, that is just what I was hoping for. Thanks

**Comment by alalazo** [comment]
@markcmiller86 My bad: I thought locally meant "not on Travis", and missed the "automagically" part on first read.
