### ISSUE TITLE
Feature Request: Display List of Packages Maintained by a Specific User in Spack

### ISSUE THREAD

**Issue by kjrstory** [LLNL/spack#42781]
### Summary

Display List of Packages Maintained by a Specific User in Spack

### Description

Currently, it's straightforward to identify the maintainer of a specific package in Spack. This can be done through commands like `spack info`, by viewing the recipe file, or even on the website(https://packages.spack.io). However, the reverse process - identifying all the packages a particular user maintains - is not as straightforward.

For instance, I am currently maintaining packages such as fds, openfoam-org, su2, openradioss-solver, and openradioss-starter. This list relies solely on my memory, which is not always reliable. Wouldn't it be beneficial to have a feature in Spack that allows users to easily view a list of package recipes maintained by a specific user? Such functionality would not only be a great asset for maintainers to keep track of their contributions but also help in building their profiles.

Maintaining packages is a voluntary and often challenging task. Providing maintainers with a clear overview of their contributions could serve as a form of recognition and motivation. Additionally, it would simplify the process for other users and developers to find packages maintained by a specific individual, potentially fostering more collaboration.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
I think you forgot `of-precice` and possibly `openradioss-solver` is `openradioss-engine` :slightly_smiling_face: [^1]
```console
$ spack maintainers --by-user kjrstory
fds  of-precice  openfoam-org  openradioss-engine  openradioss-starter  su2
```
[^1]: The feature is already there, albeit a bit hidden? In any case let me know if you were seeking anything more than this.
