### ISSUE TITLE
Replace `buildable` with `from`

### ISSUE THREAD

**Issue by RikkiButler20** [LLNL/spack#42813]
### Summary

Depreciate `buildable: [true, false]` and add `from: [source,  external, buildcache, installed]`

### Description

Add `from` along with `buildable`, cannot have both at the same time, `buildable: false` to be replaced with `from: external` 
The order of `from` is up to the discretion of the user

### Additional information

`buildable: false` works the same as `from: [external]`
Should fail if both `buildable` & `from` are used
`from: [source]` without `buildcache` should work similarly to `--fresh`
`from: [source]` without `installed` should work similarly to `--overwrite`

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
This is somehow done in https://github.com/spack/spack/pull/42782, or at least it has a lot of overlap.

**Comment by alalazo** [comment]
Also, just a name doesn't allow extensions later (for instance `buildcache` doesn't say which mirror, if we have more than one).

**Comment by alalazo** [comment]
> from: [source] without installed should work similarly to --overwrite

Imo this would be bad, since it is mixing install and concretization options. Also, that means Spack would rebuild that package every time, even if it matches the hash. Isn't that the use case covered by `spack develop`?
