### ISSUE TITLE
Installation issue: openimageio

### ISSUE THREAD

**Issue by sebastianelsner** [LLNL/spack#42837]
### Steps to reproduce the issue

```console
$ ./spack install  openimageio
```

### Error message

<details><summary>Error message</summary>

<pre>
1 error found in build log:
     110    -- Found Boost 108400
     111    -- Found ZLIB 1.3
     112    -- Found TIFF 4.5.1
     113    -- OpenEXR library not found
     114    --     Try setting OpenEXR_ROOT ?
     115    --     Maybe this will help:  src/build-scripts/build_openexr.bash
  >> 116    CMake Error at src/cmake/checked_find_package.cmake:128 (message):
     117      OpenEXR is required, aborting.
     118    Call Stack (most recent call first):
     119      src/cmake/externalpackages.cmake:88 (checked_find_package)
     120      CMakeLists.txt:117 (include)
     121    
     122  
</pre></details>

### Information on your system

* **Spack:** 0.22.0.dev0 (6680c6b72e9e1c6c461b66065433c467b23ed9b4)
* **Python:** 3.12.1
* **Platform:** linux-fedora39-skylake
* **Concretizer:** clingo

[spack-build-env.txt](https://github.com/spack/spack/files/14393062/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/14393058/spack-build-out.txt)

### Additional information

I am basically a first time user. Just followed the README and typed

spack install openimageio

and got the error

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by sebastianelsner** [comment]
I would be willing to debug. Are there any guidelines how to best do that in context of spack? I know of course the basics if done without spack. Much appreciated, thank you :) !

**Comment by Sinan81** [comment]
looks like you just need to add a dependency: openexr:
please see: 
https://spack.readthedocs.io/en/latest/build_systems/cmakepackage.html
and 
https://github.com/spack/spack/tree/develop/var/spack/repos/builtin/packages/openexr
This should be a quick fix.
hope this helps.

**Comment by Sinan81** [comment]
actually, dependency is already indicated in the packagefile:
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/openimageio/package.py
I guess the package isn't able to automatically find the dependency anymore. This might happen due to changes in cmake, python, or depencency versions. may be the corresponding cmake option should be explicitly added in the `def cmake_args..` section of openimageio package file.
I would try going to the spack-build directory, running `ccmake .` and see what is relevant to openexr there.
Hope this helps.

**Comment by sebastianelsner** [comment]
Thanks! Will look into this.

**Comment by beatreichenbach** [comment]
@sebastianelsner This can be solved by updating the OpenImageIO version: https://github.com/spack/spack/pull/46045
