### ISSUE TITLE
Slack Integration

### ISSUE THREAD

**Issue by JusticeForMikeBrown** [LLNL/spack#4296]
Hi

Does Spack have any way of integrating with Slack?  I think that would be a great way to notify users that a new package was installed.

This could be done by wrapping Spack into an Ansible role, or some other configuration management tool that has Slack integration, though checking here to see if anyone has other ideas.

Twitter would be cool, too!

**Comment by tgamblin** [comment]
You could add this in a post-install hook in `lib/spack/spack/hooks`.  Before and after a package is installed or uninstalled, Spack calls hook methods in each module in that directory.  Look at, e.g, `lib/spack/spack/hooks/sbang.py` for the code that patches files with long shebang lines.

Currently you can define these hooks in your modules (look in `__init__.py` to see where the `HookRunner`s are set up):

```python
def pre_run():
    """Runs at the beginning of every spack invocation."""

def pre_install(spec):
    """Runs before a package build."""

def post_install(spec):
    """Runs after a package is installed."""

def pre_uninstall(spec):
    """Runs before a package is uninstalled."""

def pre_uninstall(spec):
    """Runs after a package is uninstalled."""
```

The `spec` is the same spec passed to install, and represents the build configuration.  If you want the package object (which has all the static metadata), it's `spec.package`.  If you want to see how to get information about a package out of that object, you can look at `lib/spack/spack/cmd/info.py`, which implements the `spack info <pkgame>` command.

**Comment by JusticeForMikeBrown** [comment]
Thanks so much @tgamblin!

I'll try this out and get back!

**Comment by alalazo** [comment]
@JusticeForMikeBrown I'll close the issue as it seems solved. Feel free to reopen if not.
