### ISSUE TITLE
gdrcopy@2.4.1 patching failure

### ISSUE THREAD

**Issue by G-Ragghianti** [LLNL/spack#42995]
### Steps to reproduce

The version of gdrcopy@2.4.1 includes an update to the src/Makefile which causes a failure when the patch to remove ldconfig is applied.  See comment here: https://github.com/spack/spack/pull/42051

```
spack install gdrcopy@2.4.1
==> Installing gdrcopy-2.4.1-ldnhwwwbmeqwbeoksm2wpoijctzchg6m [9/9]
==> No binary for gdrcopy-2.4.1-ldnhwwwbmeqwbeoksm2wpoijctzchg6m found: installing from source
==> Using cached archive: /spack/var/spack/cache/_source-cache/archive/fa/faa7e816e9bad3301e53d6721457f7ef5ab42b7aa3b01ffda51f8e5620bb20ed.tar.gz
1 out of 1 hunk FAILED -- saving rejects to file src/Makefile.rej
==> Patch /spack/var/spack/repos/builtin/packages/gdrcopy/ldconfig.patch failed.
==> Error: ProcessError: Command exited with status 1:
    '/usr/bin/patch' '-s' '-p' '1' '-i' '/spack/var/spack/repos/builtin/packages/gdrcopy/ldconfig.patch' '-d' '.'
```

### Information on your system

* **Spack:** 0.22.0.dev0 (df92f0a7d43f7cf5852ed784a3f26a59c581985a)
* **Python:** 3.9.18
* **Platform:** linux-rocky9-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by jack-morrison** [comment]
[Copying @G-Ragghianti's comment from the 2.4.1 new version PR here]
> This version doesn't build because a change in the src/Makefile in version 2.4.1 causes the patch to fail to apply. Should the application of the patch be removed, or should a new patch be created?

It seems to me like the patch is to remove a call to ldconfig, and [this may not be recommended](https://github.com/NVIDIA/gdrcopy/pull/229#issuecomment-1646504215)?

In any case, I can confirm that 2.4.1 builds without the patch. 
edit: at least on a RHEL8.6 host. This might not be the case OOTB on a SLES distro if ldconfig is in sbin.

**Comment by G-Ragghianti** [comment]
I think the rationale is that **sometimes** ldconfig may be unavailable, but I can't say what cases that may be.  The upstream gdrcopy seems to have added a PATH in the call to ldconfig in hopes of making it more likely to find an available ldconfig. I would vote for no patch and just trust that something basic like glibc's ldconfig is available somewhere.

**Comment by G-Ragghianti** [comment]
Thank you.  Issue is resolved.
