### ISSUE TITLE
Installation issue: rocm-openmp-extras 5.4.3

### ISSUE THREAD

**Issue by G-Ragghianti** [LLNL/spack#43021]
### Steps to reproduce the issue

```console
spack install papi +rocm amdgpu_target=gfx90a ^rocm-openmp-extras@5.4.3

==> Installing rocm-openmp-extras-5.4.3-vv6ewzkcdi2swbmrvainyrbxnd4ka6xi [103/107]
==> No binary for rocm-openmp-extras-5.4.3-vv6ewzkcdi2swbmrvainyrbxnd4ka6xi found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/7f/7f90634fb621169b21bcbd920c2e299acc88ba0eeb1a33fd40ae26e13201b652.tar.gz
==> Error: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/jenkins/workspace/Users/Ragghianti/papi_spack_prtest/3b7e6bf7/stage/spack-stage-rocm-openmp-extras-5.4.3-vv6ewzkcdi2swbmrvainyrbxnd4ka6xi/spack-src/rocm-openmp-extras/llvm-project/openmp/libomptarget/cmake/Modules/LibomptargetGetDependencies.cmake'

/tmp/jenkins/workspace/Users/Ragghianti/papi_spack_prtest/3b7e6bf7/var/spack/repos/builtin/packages/rocm-openmp-extras/package.py:299, in patch:
        296
        297        # Openmp adjustments
        298        # Fix relocation error with libffi by not using static lib.
  >>    299        filter_file(
        300            "libffi.a",
        301            "",
        302            libomptarget.format(src) + "/cmake/Modules/LibomptargetGetDependencies.cmake",


==> Error: Terminating after first install failure: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/jenkins/workspace/Users/Ragghianti/papi_spack_prtest/3b7e6bf7/stage/spack-stage-rocm-openmp-extras-5.4.3-vv6ewzkcdi2swbmrvainyrbxnd4ka6xi/spack-src/rocm-openmp-extras/llvm-project/openmp/libomptarget/cmake/Modules/LibomptargetGetDependencies.cmake'
```

### Error message

==> Error: Terminating after first install failure: FileNotFoundError: [Errno 2] No such file or directory: '/tmp/jenkins/workspace/Users/Ragghianti/papi_spack_prtest/3b7e6bf7/stage/spack-stage-rocm-openmp-extras-5.4.3-vv6ewzkcdi2swbmrvainyrbxnd4ka6xi/spack-src/rocm-openmp-extras/llvm-project/openmp/libomptarget/cmake/Modules/LibomptargetGetDependencies.cmake'

### Information on your system

* **Spack:** 0.22.0.dev0
* **Python:** 3.9.18
* **Platform:** linux-rocky9-icelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by srekolam** [comment]
https://github.com/spack/spack/pull/43046 has the fix.

**Comment by srekolam** [comment]
the PR is merged and the changes are in spack:develop
