### ISSUE TITLE
Installation issue: NetCDF CMake config broken for consumers

### ISSUE THREAD

**Issue by johnwparent** [LLNL/spack#43038]
@scheibelp @Chrismarsh [This](https://github.com/spack/spack/pull/42878) MR breaks support for projects consuming NetCDF-C on Windows because the renamed targets do not exist for all versions of `hdf5`.
For context, I am testing with `hdf5@1.14.3` which is the latest non development `hdf5` version in Spack.

In https://github.com/spack/spack/pull/42749 I add the `find_dependency` call suggested by @skosukhin for hdf5, as this is the correct idiom for a CMake config module to load in dependencies. I added the patch only for Windows, as I did not want to rock the boat for other platforms, but in general this is how all installations of netcdf-c should be configured.

This means that netcdf-c is acquiring its hdf5 dep from a call to `find_package(HDF5...`. The results of which:

`hdf5`'s CMake config exports targets:
```
-- hdf5-static
-- hdf5-shared
-- mirror_server
-- mirror_server_stop
-- hdf5_tools-static
-- hdf5_tools-shared
-- h5diff
-- h5diff-shared
-- h5ls
-- h5ls-shared
-- h5debug
-- h5repart
-- h5mkgrp
-- h5clear
-- h5delete
-- h5debug-shared
-- h5repart-shared
-- h5mkgrp-shared
-- h5clear-shared
-- h5delete-shared
-- h5import
-- h5import-shared
-- h5repack
-- h5repack-shared
-- h5jam
-- h5unjam
-- h5jam-shared
-- h5unjam-shared
-- h5copy
-- h5copy-shared
-- h5stat
-- h5stat-shared
-- h5dump
-- h5dump-shared
-- h5format_convert
-- h5format_convert-shared
-- h5perf_serial
-- hdf5_hl-static
-- hdf5_hl-shared
-- h5watch
-- h5watch-shared
```
as you can see, `hdf5` and `hdf5_hl` are not in the list, but the targets removed by this PR _are_ present.
If this is routed through the `FindHDF5.cmake` module vendored by CMake, targets:
```
-- HDF5::HDF5
-- hdf5::hdf5
-- hdf5::hdf5_hl
-- hdf5::h5diff
```
are added. This still does not cover the targets created here.

This results in the `hdf5` and `hdf5_hl` targets being unresolved, resulting in: `LINK : fatal error LNK1104: cannot open file 'hdf5.lib'` errors from a project as simple as:
```
cmake_minimum_required(VERSION 3.20)
project(TEST)

find_package(netcdf REQUIRED)
add_executable(hash hash.cxx)
target_link_libraries(hash PUBLIC netCDF::netcdf)
```
(where all `hash.cxx` does is call `std::hash` on argv[0], no use of netcdfc)
This can also be observed in any package that consumes NetCDF-C (like VTK for example).

If I remove the post install step added by https://github.com/spack/spack/pull/42878, everything behaves as expected.

#42878 is either handling an older hdf5 version that exports its targets differently or things are done _very_ differently for the Linux side CMake by NetCDF-C (I don't think that's the case) or this was only tested against projects like VTK, that perform a good deal of extra work to ensure TPLs are consumable. 

If this is an issue of HDF5 versions exporting differently named targets, then the post install step added in #42878 should be scoped to that version of HDF5. If that is not the case however, IMO #42878 takes a backwards approach. If this is an issue of versions, the next section can be ignored.
If this is an HDF5 configuration issue, then this should be patched in the NetCDF-C CMake code, not by a post install step of Spack. 
Otherwise, CMake projects are responsible for exporting their own dep interfaces, generated based on the manner of consumption in the projects themselves (i.e. if netcdf-c links against a target named `hdf5_hl-shared`, it should export the _actual_ link interface it used). Consumers who engage in behavior supplementary to that are responsible for handling this in whatever way is best for their own project. This is _why_ VTK has so much custom logic around external TPLs. However, #42878 takes the reverse approach, where it sets the netcdfC exports up so that they are more easily utilized by a particular consumer.

I think either way, an Hdf5 versioning issue or otherwise, #42878 is very VTK specific and does not generalize to other consumers.

@Chrismarsh I think applying my patch in VTK that modifies VTK's vendored `FindHDF5.cmake` will resolve the issue you were experiencing. I can iterate with you in more detail about what's going on there and why what happens happens.

Note: the pkgconf modifications seem correct/good, this is only an issue with `netCDFConfig.cmake`

### Error message

<details><summary>Error message</summary>

<pre>
LINK : fatal error LNK1104: cannot open file 'hdf5.lib'
</pre></details>

### Information on your system

* **Spack:** 0.22.0.dev0 (b394c95ac618241260c23ff3ea5a7e0ed5fb49cb)
* **Python:** 3.11.3
* **Platform:** windows-windows10.0.22621-AMD64
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by Chrismarsh** [comment]
Well crap, I'm sorry that broke for you.

I understood the problem I was hitting to be a specific problem to `netcdf-c` in that it treated a target name `hdf5-shared` as a library name. But maybe I'm muddled in that it's actually a vtk issue (https://github.com/Unidata/netcdf-c/issues/1444#issuecomment-621027824)?

>https://github.com/spack/spack/pull/42878 is either handling an older hdf5 version

I would need to double check but iirc it's the most recent.

> this was only tested against projects like VTK, 

Indeed, that's where the link failure was occurring where it was using netcdf-c's export as library names instead of targets


>@Chrismarsh I think applying my patch in VTK that modifies VTK's vendored FindHDF5.cmake will resolve the issue you were experiencing. I can iterate with you in more detail about what's going on there and why what happens happens.

I will give it a try, I like the approach more. I had been following the netcdf-c cmake approach for how it handled the pkconfig which was perhaps a mistake.

**Comment by johnwparent** [comment]
>  specific problem to netcdf-c in that it treated a target name hdf5-shared as a library name

I think this is still correct for the pkgconf stuff, just not the CMake. The exported CMake link interface will be generated to include the appropriate hdf5 CMake targets that netCDF was linked against.

> But maybe I'm muddled in that it's actually a vtk issue (https://github.com/Unidata/netcdf-c/issues/1444#issuecomment-621027824)?

I think what you encountered was a VTK issue. VTK has its own `FindHDF5.cmake` which it prefers over the CMake vendored version, which adds logic, likely resulting in this issue (probably some target scoping/naming issues)

> > https://github.com/spack/spack/pull/42878 is either handling an older hdf5 version

> I would need to double check but iirc it's the most recent.

Perhaps a different build configuration could cause different names?

> I had been following the netcdf-c cmake approach for how it handled the pkconfig which was perhaps a mistake.

You patched the pkgconf correctly AFAICT (admittedly I don't really use it) but applying the same logic to the CMake I think is a step away from allowing CMake to generate the link interface, which we want to avoid.
