### ISSUE TITLE
spack numpy distutils compilers

### ISSUE THREAD

**Issue by lee218llnl** [LLNL/spack#431]
I don't recall if we ever tried to address this issue, but if I attempt to build something like scipy on top of a spack python with numpy, it tries to bring in the spack compilers:

$ /usr/apps/python3.5.1/bin/python3 setup.py -v build

...

compiling C sources
C compiler: /collab/usr/gapps/python/build/spack-python-3.5.1/lib/spack/env/gcc/gcc -pthread -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

compile options: '-I/usr/apps/python3.5.1/lib/python3.5/site-packages/numpy/core/include -I/usr/apps/python3.5.1/lib/python3.5/site-packages/numpy/core/include -I/usr/apps/python3.5.1/include/python3.5m -c'
gcc: scipy/cluster/_hierarchy.c
exec_command(['/collab/usr/gapps/python/build/spack-python-3.5.1/lib/spack/env/gcc/gcc', '-pthread', '-Wsign-compare', '-Wunreachable-code', '-DNDEBUG', '-g', '-fwrapv', '-O3', '-Wall', '-Wstrict-prototypes', '-fPIC', '-I/usr/apps/python3.5.1/lib/python3.5/site-packages/numpy/core/include', '-I/usr/apps/python3.5.1/lib/python3.5/site-packages/numpy/core/include', '-I/usr/apps/python3.5.1/include/python3.5m', '-c', 'scipy/cluster/_hierarchy.c', '-o', 'build/temp.linux-x86_64-3.5/scipy/cluster/_hierarchy.o'],)
Retaining cwd: /g/g0/lee218/src/python/scipy-0.17.0
_preserve_environment([])
_update_environment(...)
_exec_command_posix(...)
Running os.system('( /collab/usr/gapps/python/build/spack-python-3.5.1/lib/spack/env/gcc/gcc -pthread -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/apps/python3.5.1/lib/python3.5/site-packages/numpy/core/include -I/usr/apps/python3.5.1/lib/python3.5/site-packages/numpy/core/include -I/usr/apps/python3.5.1/include/python3.5m -c scipy/cluster/_hierarchy.c -o build/temp.linux-x86_64-3.5/scipy/cluster/_hierarchy.o ; echo $? > /var/tmp/lee218/tmp87yy_gfd/jclr35pl ) 2>&1 | tee /var/tmp/lee218/tmp87yy_gfd/xsk06kuy ')
Spack compiler must be run from spack!  Input SPACK_PREFIX was missing!
_update_environment(...)
Spack compiler must be run from spack!  Input SPACK_PREFIX was missing!
error: Command "/collab/usr/gapps/python/build/spack-python-3.5.1/lib/spack/env/gcc/gcc -pthread -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/usr/apps/python3.5.1/lib/python3.5/site-packages/numpy/core/include -I/usr/apps/python3.5.1/lib/python3.5/site-packages/numpy/core/include -I/usr/apps/python3.5.1/include/python3.5m -c scipy/cluster/_hierarchy.c -o build/temp.linux-x86_64-3.5/scipy/cluster/_hierarchy.o" failed with exit status 1

**Comment by tgamblin** [comment]
@lee218llnl: this looks similar to what happens when we don't patch the mpich and openmpi wrappers. Is there a config that is written when numpy is installed? Where's it getting the compilers?

**Comment by lee218llnl** [comment]
Todd,

Actually, the spack compiler paths appears to be stored in various places within the Python 3 installation itself (not numpy):

/collab/usr/gapps/python/build/spack-python-3.5.1/opt/spack/chaos_5_x86_64_ib/gcc-4.4.7/python-3.5.1-rh6cgjltcqw5pm4geqxgpvou5xi6awta/lib/python3.5/_sysconfigdata.py
/collab/usr/gapps/python/build/spack-python-3.5.1/opt/spack/chaos_5_x86_64_ib/gcc-4.4.7/python-3.5.1-rh6cgjltcqw5pm4geqxgpvou5xi6awta/lib/python3.5/config-3.5m/Makefile

I don't see this in Python 2 installations.

**Comment by tgamblin** [comment]
Interesting -- so it seems like we'd want to patch Python when it's version 3 or higher.

**Comment by lee218llnl** [comment]
It turns out this happens in Python 2.7 too. My spack-based Python 2.7 installation at LLNL was built using an older version of spack, which apparently didn't propagate the full path to gcc/g++ into those files. Anyway, I have a fix to propose, so a PR will be coming shortly.

**Comment by adamjstewart** [comment]
@lee218llnl Is this issue now resolved? If so can you close it?

**Comment by tgamblin** [comment]
I merged this PR so I assume yes.

**Comment by lee218llnl** [comment]
Just tested this on the develop branch and it looks good.
