### ISSUE TITLE
How to install a Python package in the site-packages directory instead of separate prefix ?

### ISSUE THREAD

**Issue by samfux84** [LLNL/spack#4311]
Hi all,

the spack documentation states that installing a Python package in the site-packages directory of the Python installation directory should be possible:

> Spack’s installation model assumes that each package will live in its own install prefix. However, certain packages are typically installed within the directory hierarchy of other packages. For example, modules in interpreted languages like Python are typically installed in the $prefix/lib/python-2.7/site-packages directory.
> 
> Spack has support for this type of installation as well. In Spack, a package that can live inside the prefix of another package is called an extension. Suppose you have Python installed like so:

How can this be done ? I would like to avoid having separate installation directories for Python packages. Further more I would like to avoid having module files for Python packages. If a user load a Python module, he expects to have access to all Python packages within that installation without having to load another module.

When I try to install any Python package, it creates a separate installation directory, creates a module file that sets PYTHONPATH.

Best regards

Sam

**Comment by adamjstewart** [comment]
`spack activate`

**Comment by samfux84** [comment]
@adamjstewart spack activate will help me to avoid having users loading separate modules for Python packages, but how does it help to avoid that Python packages are installed in separate directories ?

**Comment by adamjstewart** [comment]
There is no way to avoid that. Spack installs every package to a separate installation prefix. If that wasn't the case, it would be literally impossible to maintain multiple versions of the same software package as they would conflict and there would be no way to uninstall them.

**Comment by samfux84** [comment]
@adamjstewart Thank you for your answer. I just need to get used to doing things a little different than before when manually installing Python and some packages.
