### ISSUE TITLE
post-solve `output.satisfies(input)` check returns false positive when input is (partially) concrete

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#43267]
### Steps to reproduce

`spack spec pkg ^/hash` currently fails post-solve even though the solve is correct

The reason is that the input spec contains build dependencies that are omitted in the solver.

Reproducer:

```
$ spack spec --fresh --json cmake > cmake.json
$ spack spec --fresh fmt ^./cmake.json 
==> Error: Internal Spack error: the solver completed but produced specs that do not satisfy the request. Please report a bug at https://github.com/spack/spack/issues
```

The issue is that `spec.json` contains all dependencies of cmake, including `pkgconf`, which is a pure build dep. It's dropped by the solver.

**Comment by alalazo** [comment]
I cannot reproduce this, so I think some bits that trigger the issue are missing? I installed `zlib-ng ^gmake@=4.4` and added:
```diff
diff --git a/var/spack/repos/builtin/packages/hdf5/package.py b/var/spack/repos/builtin/packages/hdf5/package.py
index a7f267d810..8ca927a879 100644
--- a/var/spack/repos/builtin/packages/hdf5/package.py
+++ b/var/spack/repos/builtin/packages/hdf5/package.py
@@ -114,6 +114,8 @@ class Hdf5(CMakePackage):
     depends_on("szip", when="+szip")
     depends_on("zlib-api")
 
+    depends_on("gmake@4.4.1:")
+
     # The compiler wrappers (h5cc, h5fc, etc.) run 'pkg-config'.
     # Skip this on Windows since pkgconfig is autotools
     for plat in ["cray", "darwin", "linux"]:
```
What I get is:
![Screenshot from 2024-03-19 13-40-36](https://github.com/spack/spack/assets/4199709/aa5178bd-9294-4043-a205-892f54dcc30a)

**Comment by haampie** [comment]
See updated top level comment.

**Comment by alalazo** [comment]
Currently the case above fails because this assumption:

https://github.com/spack/spack/blob/e37870ff43514e79d7b520f930270bc41fc52e13/lib/spack/spack/spec.py#L3901-L3903 

is wrong, in the sense  that we might have a concrete dependency on the rhs.

**Comment by alalazo** [comment]
This might be enough to fix the concretization:
```diff
diff --git a/lib/spack/spack/spec.py b/lib/spack/spack/spec.py
index 7d8266400e..a06e761fcd 100644
--- a/lib/spack/spack/spec.py
+++ b/lib/spack/spack/spec.py
@@ -3910,6 +3910,9 @@ def satisfies(self, other: Union[str, "Spec"], deps: bool = True) -> bool:
             if not rhs_edge.virtuals:
                 continue
 
+            if rhs_edge.parent.concrete:
+                continue
+
             if not lhs_edges:
                 # Construct a map of the link/run subDAG + direct "build" edges,
                 # keyed by dependency name

```
Now I need to come up with a regression test.

**Comment by haampie** [comment]
Would be nice not to descend into the right hand side for concrete subbranches

**Comment by alalazo** [comment]
> Would be nice not to descend into the right hand side for concrete subbranches

It would be a nice an optimization. What I'm doing right now is just skipping the edges of those subdags.
