### ISSUE TITLE
py-matplotlib fails with missing dependency package

### ISSUE THREAD

**Issue by teague-23andme** [LLNL/spack#43276]
### Steps to reproduce

```console 
$ spack install py-matplotlib
```

### Error message

```console
```console
$ spack install py-matplotlib
==> Error: Package 'spack.pkg.builtin.py-pil' not found.
Use 'spack create' to create a new package.

Did you mean one of the following packages?
  py-ply
  py-pip
  py-pid
$ spack info py-matplotlib | grep -A4 "Run Dependencies"
Run Dependencies:
    ghostscript
    pil
    py-contourpy
    py-cycler
$ spack info pil
==> Error: Package 'spack.pkg.builtin.pil' not found.
Use 'spack create' to create a new package.

Did you mean one of the following packages?
  pilon
  ppl
  ply
```

### Information on your system

* **Spack:** 0.22.0.dev0
* **Python:** 3.6.8
* **Platform:** linux-centos7-zen2
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
I think this is an issue caused by cache invalidation problems when switching between commits in Spack.

Can you retry after `spack clean -m`?

**Comment by teaguesterling** [comment]
Confirmed that `spack clean -m` resolved this issue. Thank you!

**Comment by teague-23andme** [comment]
Confirmed that `spack clean -m` resolved this issue. Thank you!
