### ISSUE TITLE
Installation issue: Trilinos

### ISSUE THREAD

**Issue by lucbv** [LLNL/spack#43274]
### Steps to reproduce the issue

```console
$ spack spec -I trilinos +mpi+exodus+tpetra+muelu+belos+ifpack2+amesos2+zoltan+stk+boost~superlu-dist+superlu+hdf5+shards~hypre
...
```

### Error message

<details><summary>
==> Error: concretization failed for the following reasons:

   1. Cannot satisfy 'superlu@4.3'
   2. Cannot satisfy 'superlu@4.3'
        required because trilinos depends on superlu@4.3+pic when +superlu 
          required because trilinos+amesos2+belos+boost+exodus+hdf5~hypre+ifpack2+mpi+muelu+shards+stk+superlu~superlu-dist+tpetra+zoltan requested explicitly 
   3. Cannot satisfy 'superlu@5:' and 'superlu@4.3
        required because superlu variant build_system value cmake when [, , ] 
          required because trilinos depends on superlu@4.3+pic when +superlu 
            required because trilinos+amesos2+belos+boost+exodus+hdf5~hypre+ifpack2+mpi+muelu+shards+stk+superlu~superlu-dist+tpetra+zoltan requested explicitly 
        required because trilinos depends on superlu@4.3+pic when +superlu 
          required because trilinos+amesos2+belos+boost+exodus+hdf5~hypre+ifpack2+mpi+muelu+shards+stk+superlu~superlu-dist+tpetra+zoltan requested explicitly
</summary>
</details>

### Information on your system

* **Spack:** 0.22.0.dev0 (fa8fb7903beafff5cd5065de1a4f08266708f7df)
* **Python:** 3.9.16
* **Platform:** linux-rhel9-broadwell
* **Concretizer:** clingo

### Additional information

@jwillenbring @psakievich @sethrj 

The spec above is actually used by nalu which requires a trilinos build using superlu.
In the latest update of the superlu package, version 4.3 is marked as deprecated and this should be reflected in the Trilinos package by bumping up the version of superlu from 4.3 to at least 5.1 or another 5.X version as appropriate.
It is additionally surprising that this was not caught by the e4s builds?

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by keixthb** [comment]
@lucbv is this for nalu cfd, or nalu wind?

**Comment by lucbv** [comment]
@keixthb it's for nalu cfd, see here: https://github.com/spack/spack/blob/f16e29559ee3095a95b5e64f0d973c2646ad6571/var/spack/repos/builtin/packages/nalu/package.py#L40
That could also be an issue for nalu-wind but I would not know about that at this time. In any case that's something to be fixed in Trilinos and that would have been nice to catch in e4s when SuperLU was updated.

**Comment by keixthb** [comment]
@lucbv Nalu CFD says in the [docs](https://nalu.readthedocs.io/en/latest/source/user/build_spack.html) that: "The routine usage of Spack has been deprecated in favor of the manual-based build process."

**Comment by sethrj** [comment]
Good god that's a huge build stack to try to do independently.

**Comment by psakievich** [comment]
This has not been an issue for nalu-wind. We need to update that package here though.

**Comment by lucbv** [comment]
I can update the SuperLU version, that's easy enough and Trilinos certainly supports it based on its CMake options.
On the other hand it would be nice to have e4s at least do a concretization which is much cheaper than a build and realize that there is a conflict that needs to be resolved. A warning at least would have been good : )

**Comment by psakievich** [comment]
We need to fix this concretization for sure.

**Comment by lucbv** [comment]
I am proposing PR #43346 to fix this issue. Will mention the issue in the PR for better cross-referencing.

**Comment by lucbv** [comment]
All fixed let us close this then!
