### ISSUE TITLE
Installation issue: py-kaleido

### ISSUE THREAD

**Issue by A-N-Other** [LLNL/spack#43302]
### Steps to reproduce the issue

```console
$ spack install py-kaleido@0.2.1
```

### Error message

Two issues...

Firstly, the `sha256` for this version has changed. The new one is:
`version("0.2.1", sha256="372928676d2843e316ea7d7272d6a85f10f936a0ca685b56db410e88769f4cdd")`

Secondly, the install process attempts to find a `spack-src/repos/kaleido/py/repos/kaleido/py/kaleido/_version` file, which is absent, giving:

<details><summary>Error message</summary>

<pre>
     64          setup_py_code = "from setuptools import setup; setup()"
     65    
     66      exec(compile(setup_py_code, filename, "exec"))
     67      '"'"''"'"''"'"' % ('"'"'/opt/software/.spack/build/root/spack-stage-py-kaleido-0.2.1-2iqpnu3zgryqv3imtx3maksjpkdj74g2/spack-src/repos/kaleido/py/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' egg_info --egg-base /tmp/pip-pip-egg-info-gev2sn6_
     68      cwd: /opt/software/.spack/build/root/spack-stage-py-kaleido-0.2.1-2iqpnu3zgryqv3imtx3maksjpkdj74g2/spack-src/repos/kaleido/py/
     69      Preparing metadata (setup.py): finished with status 'error'
  >> 70    error: metadata-generation-failed
     71    
     72    × Encountered error while generating package metadata.
     73    ╰─> See above for output.
     74    
     75    note: This is an issue with the package mentioned above, not pip.
     76    hint: See above for details.
</pre></details>

This file could be inserted, but it appears from the [docs](https://pypi.org/project/kaleido/) that the install methods are all actually reliant on Docker. I'm not sure how this was installing itself before (I assume it was doing so correctly?), therefore, as it's otherwise a very minimal `package.py`.

Preferred means of distribution appears to be by [`.whl`](https://pypi.org/project/kaleido/0.2.1/#files).

### Information on your system

```
* **Spack:** 0.22.0.dev0 (b521b5edefa0393eae6b05c22a1456fdbed20729)
* **Python:** 3.6.8
* **Platform:** linux-rocky8-icelake
* **Concretizer:** clingo
```

### Additional information

@Pandapip1 There's obviously been a change in what's downloaded as the `sha256` has changed. Was this definitely working previously?

[spack-build-env.txt](https://github.com/spack/spack/files/14694738/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/14694739/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by Pandapip1** [comment]
I don't have a record of the installation, but I can confirm that right now, it does not install. Oddly enough though, I get a different installation error:

```console
gavinjohn@n001:/ref/djslab/software/spack-unstable $ ./bin/spack install py-kaleido
[+] /ref/djslab/software/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/gcc-runtime-8.5.0-pq3wyldkdxhlvscwppjdbqpxyuqanylv
[+] /ref/djslab/software/spack-0.18.1/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/bzip2-1.0.8-ft3hy4zsnbqlr264ghvej7hbh72wylcn
[+] /ref/djslab/software/spack-0.18.1/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/libmd-1.0.4-pwusa7kbrtatnrwevxydlhimnecfnzw7
[+] /ref/djslab/software/spack-0.18.1/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/ncurses-6.2-upjxwloceqgryetrerh4ldfshxpjqtq5
[+] /ref/djslab/software/spack-0.18.1/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/libiconv-1.16-gt3op62awzogqhmtelixckmnrs75pryn
[+] /ref/djslab/software/spack-0.18.1/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/xz-5.2.5-ws6hl5n5sqkzas72ufw3xpff5w3socoz
[+] /ref/djslab/software/spack-0.18.1/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/zlib-1.2.12-k7a42vgqevrisqxdk3nw62ypakbwgm74
[+] /ref/djslab/software/spack-0.18.1/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/zstd-1.5.2-d2l42sglnynwjyeq4qg74nqnxtwnka54
[+] /ref/djslab/software/spack-0.18.1/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/libffi-3.4.2-gbfy247g7u6m2xhabmrbjkm2fhkidjnf
[+] /ref/djslab/software/spack-0.18.1/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/util-linux-uuid-2.37.4-pws2nxk7ljovqqdeb6gtaassoij5omlb
[+] /ref/djslab/software/spack-0.18.1/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/libbsd-0.11.5-uo2tqxhivkobql2oawsi6y76ysljgvrb
[+] /ref/djslab/software/spack-0.18.1/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/readline-8.1-k5nhz2lnjlllacnaulapv6g5mullue7h
[+] /ref/djslab/software/spack-0.18.1/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/openssl-1.1.1o-dw3vvrvlnhmiydfxt2ohnhxhjf7ri6pd
[+] /ref/djslab/software/spack-0.18.1/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/libxml2-2.9.13-v6gby4xcbitydai2qd4bdzh7rbssgjdu
[+] /ref/djslab/software/spack-0.18.1/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/pigz-2.7-ygmqiek7wyk2te66s7ezlzllxvwhmsnz
[+] /ref/djslab/software/spack-0.18.1/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/expat-2.4.8-mi6fg7fbva64xc5tgfbthrdop6htojd3
[+] /ref/djslab/software/spack-0.18.1/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/gdbm-1.19-kjkveqodsc3wuguxjafjipbp2vlioi2p
[+] /ref/djslab/software/spack-0.18.1/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/sqlite-3.38.5-sqd6levzkymahqnrtxcwszgd3k4vmzxq
[+] /ref/djslab/software/spack-0.18.1/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/tar-1.34-sx6mc7oveh3542bad3bzi7ag7qen6awt
[+] /ref/djslab/software/spack-0.18.1/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/gettext-0.21-7vtz7647ivp65swzrur3kut5qjhzhxkb
[+] /ref/djslab/software/spack-0.18.1/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/python-2.7.18-zcq73awkux5lp6zuoawyu4b3ggpoqrnd
[+] /ref/djslab/software/spack-0.18.1/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/py-wheel-0.37.0-3mrzfnwpgtsejz4fytij5ie4dmqfdxfo
[+] /ref/djslab/software/spack-0.18.1/opt/spack/linux-rocky8-x86_64/gcc-8.5.0/py-pip-20.2-axbdvl6up2oonqpbao4mujgjovavhzhh
==> Installing py-kaleido-0.2.1-5gyo5ar2axlmojrhrku6y6n236jeyr7s [24/24]
==> No binary for py-kaleido-0.2.1-5gyo5ar2axlmojrhrku6y6n236jeyr7s found: installing from source
==> Error: Failed to install py-kaleido due to MirrorError: Unable to parse extension from https://files.pythonhosted.org/packages/source/k/kaleido/kaleido-0.2.1-py2.py3-none-manylinux2014_armv7l.whl.

If this URL is for a tarball but does not include the file extension
in the name, you can explicitly declare it with the following syntax:

    version('1.2.3', 'hash', extension='tar.gz')

If this URL is for a download like a .jar or .whl that does not need
to be expanded, or an uncompressed installation script, you can tell
Spack not to expand it with the following syntax:

    version('1.2.3', 'hash', expand=False)
```

**Comment by Pandapip1** [comment]
Odd. The package file I have in our personal testing repository is as follows:

```
# Copyright 2013-2023 Lawrence Livermore National Security, LLC and other
# Spack Project Developers. See the top-level COPYRIGHT file for details.
#
# SPDX-License-Identifier: (Apache-2.0 OR MIT)

from spack.package import *

class PyKaleido(PythonPackage):
    """Static image export for web-based visualization libraries with zero dependencies"""

    homepage = "https://github.com/wdecoster/nanostat"
    pypi = "kaleido/kaleido-0.2.1.post1-py2.py3-none-manylinux2014_armv7l.whl"

    version("0.2.1", sha256="d313940896c24447fc12c74f60d46ea826195fc991f58569a6e73864d53e5c20")

    depends_on("python@:3.4")
```

I bet that one works. Weird! I'll submit a PR once I confirm.
