### ISSUE TITLE
Installation issue: py-tensorflow-2.16.1 fails to build in develop/Ubuntu 22.04

### ISSUE THREAD

**Issue by bernhardkaindl** [LLNL/spack#43320]
### Steps to reproduce the issue

Trying to test #43283 on Ubuntu 22.04, TF-2.16.1 fails to build in the config for py-keras:

```console
$ gh co 43283
$ bin/spack install -v py-keras
```

### Error message

<details><summary>Error message</summary>

Fails with different errors:
 ERROR: /tmp/t_bernhardk/spack-stage/spack-stage-py-tensorflow-2.16.1-ix4nnhfgv2lerdg6jzew4fbga4svfaqo/spack-src/tensorflow/compiler/mlir/tensorflow/BUILD:485:11: Compiling tensorflow/compiler/mlir/tensorflow/ir/tf_ops.cc failed: (Exit 1): gcc failed: error executing command (from target //tensorflow/compiler/mlir/tensorflow:tensorflow_ops)
             
<pre>
  >> 3766    ERROR: /tmp/t_bernhardk/spack-stage/spack-stage-py-tensorflow-2.16.1-ix4nnhfgv2lerdg6jzew4fbga4svfaqo/spa
             ck-src/tensorflow/compiler/mlir/tensorflow/BUILD:485:11: Compiling tensorflow/compiler/mlir/tensorflow/ir
             /tf_ops.cc failed: (Exit 1): gcc failed: error executing command (from target //tensorflow/compiler/mlir/
             tensorflow:tensorflow_ops)
...
     3804    compilation terminated.
     3805    [14,787 / 16,401] Compiling tensorflow/compiler/mlir/tf2xla/transforms/legalize_tf.cc; 462s local ... (7
             actions running)
     3806    [14,794 / 16,401] checking cached actions
     3807    Target //tensorflow/tools/pip_package:build_pip_package failed to build
     3808    INFO: Elapsed time: 5338.880s, Critical Path: 522.21s
     3809    INFO: 14794 processes: 1431 internal, 13363 local.
  >> 3810    FAILED: Build did NOT complete successfully
</pre></details>

### Information on your system

* **Spack:** 0.22.0.dev0 (1f02de55313b73c9c9227b5595400ece7d412966)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-skylake
* **Concretizer:** clingo

### Additional information

@adamjstewart @aweits
[spack-build-out.txt](https://github.com/spack/spack/files/14721928/spack-build-out.txt)
[spack-build-env.txt](https://github.com/spack/spack/files/14721930/spack-build-env.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by adamjstewart** [comment]
Error message means nothing to me. Might be worth reporting the bug to the TF developers.

**Comment by adamjstewart** [comment]
Is this still broken on develop? There are a lot of newer TF versions now.

**Comment by adamjstewart** [comment]
In fact, we currently build TF on Ubuntu 22 in CI. I'm currently working on porting this to Ubuntu 24, which should soon work as well. Going to close, but feel free to reopen if this is still an issue.
