### ISSUE TITLE
Set Default Package Version To Be Loaded

### ISSUE THREAD

**Issue by JusticeForMikeBrown** [LLNL/spack#4336]
Hi

I added this to `~/.spack/packages.yaml` after installing three versions of R.

```
packages:
  r:
    compiler: [gcc@6.3.0]
    version: [3.4.0]
```

When doing `spack load r` or `spack load -r r` older versions of R are shown in `module list`.

```
user@server[~]$ module list
Currently Loaded Modulefiles:
  1) r-3.3.2-gcc-6.3.0-kg66bw6   2) r-3.3.3-gcc-6.3.0-jup76eq   3) r-3.4.0-gcc-6.3.0-ljduq4h
```

After reading about [Concretization Preferences](https://spack.readthedocs.io/en/latest/build_settings.html#concretization-preferences) it's unclear to me if what I am trying to do can be accomplished **after** packages are already installed.  Do you know of a way?

Thanks!
Doug

**Comment by JusticeForMikeBrown** [comment]
Thanks as always @adamjstewart!

**Comment by adamjstewart** [comment]
I'm not sure if there is a way to do it with Environment Modules, but I know it's possible to set a default outside of Spack with Lmod: http://lmod.readthedocs.io/en/latest/060_locating.html#marking-a-version-as-default

**Comment by luigi-calori** [comment]
Looking at my system that has environment modules, we used the third method:
a file .version inside the module folder, containing
#%Module
set ModulesVersion <version>
