### ISSUE TITLE
Package renaming in mirrors.

### ISSUE THREAD

**Issue by t-brown** [LLNL/spack#4342]
When using spack on a machine that does not have internet access the mapping of package names from those downloaded to the mirror is not always 1:1.

For example.

```
==> Installing lcms
==> Fetching file:///home/Role.Apps/src/lcms/lcms-2.8.tar.gz
curl: (37) Couldn't open file /home/Role.Apps/src/lcms/lcms-2.8.tar.gz
==> Fetching from file:///home/Role.Apps/src/lcms/lcms-2.8.tar.gz failed.
==> Fetching http://downloads.sourceforge.net/project/lcms/lcms/2.8/lcms2-2.8.tar.gz
```

Here the package name that gets downloaded is `lcms2-2.8.tar.gz`. However it is looking in the off-line (local disk) mirror for `lcms-2.8.tar.gz`.

Other examples are**libtiff**,

```
==> Fetching file:///home/Role.Apps/src/libtiff/libtiff-4.0.7.tar.gz
curl: (37) Couldn't open file /home/Role.Apps/src/libtiff/libtiff-4.0.7.tar.gz
==> Fetching from file:///home/Role.Apps/src/libtiff/libtiff-4.0.7.tar.gz failed.
==> Fetching http://download.osgeo.org/libtiff/tiff-4.0.7.tar.gz
```

**Grib-API**: `grib_api-1.21.0-Source.tar.gz` (download) vs `grib-api-1.21.0.tar.gz` (local mirror).

This is also true for **wgrib2**, which has an even crazier online/download name of `wgrib2.tgz.v2.0.6c`, then mirror is expecting `wgrib2-2.0.6c.tar.gz`. 

In the case of Ruby gems, #3127, stalled as I couldn't get around the `.None` suffix.

Is this non-easily download, xfer/sync meant to work and does `spack mirror ...` work instead?

**Comment by tgamblin** [comment]
@t-brown: the mirrors are designed to be easy to construct by hand -- the archives in them are just `package-version.<suffix>`.  We do match the suffix to what is downloaded so that the checksum doesn't change (if we standardized the compression scheme, the package wouldn't be able to rely on the same checksum for a mirror and the original download).

Can you clarify this part:

> Is this non-easily download, xfer/sync meant to work and does spack mirror ... work instead?

**Comment by t-brown** [comment]
So what I really should be doing is using `spack mirror ...`. Instead what I have been doing:

1. local laptop: `spack install foo` (so this gets all dependencies)
2. local laptop: `rsync -e ssh -az spack/var/spack/cache hpc_system:src/`
3. hpc system: `spack install foo`

**Comment by alalazo** [comment]
@t-brown Any update?
