### ISSUE TITLE
Scalasca missing a depend otf2

### ISSUE THREAD

**Issue by abouteiller** [LLNL/spack#4349]
Scalasca depends on otf2, but is missing a depend clause. On a machine that provides an older version of otf, the configure phase fails with error about otf not providing version 6 or 7. 

Simply fixed by hand issuing a spack load otf2, but that should happen automatically.

**Comment by adamjstewart** [comment]
If you want, you can open a PR that adds:
```python
depends_on('otf2')
```
to the `scalasca` package. If you know it needs `otf2` version 6+, you can encode this as well:
```python
depends_on('otf2@6:')
```

**Comment by abouteiller** [comment]
I digged a bit more into this and it seems more complicated than simply adding otf2 to the depends: 

Scalasca depends on Scorep; it should inherit cube, otf2 and other  things from the scorep, which itself depends on otf2. So in theory all should be loading, but it is not happening. 

I see in scores that the otf2 appears as a build/link depend, but not a run depend. That may be the reason why otf2-config does not get in the path, but I'm not sure.

**Comment by tgamblin** [comment]
@daboehme: can you take a look at this?

**Comment by daboehme** [comment]
The Scalasca package shouldn't depend on Score-P (if anything, it's a run dependency, and even that is debatable). Spack doesn't "forward" dependencies, so while the Score-P package depends on otf2 and cube, the PATH for those isn't added to the Scalasca build. That's probably why otf2 wasn't found. 

Will fix by explicitly adding otf2 (and cube) dependencies.

**Comment by adamjstewart** [comment]
> Spack doesn't "forward" dependencies, so while the Score-P package depends on otf2 and cube, the PATH for those isn't added to the Scalasca build.

For the record, Spack doesn't forward _build_ dependencies (it does forward _link_ dependencies though). `otf2` will still be added to the link line by the compiler wrappers, but unless it is explicitly marked as a _build_ dependency of `scalasca`, it won't be added to the `PATH`.

**Comment by abouteiller** [comment]
Ok, that make sense. However the configure will need the correct otf2-config in PATH.

**Comment by adamjstewart** [comment]
Yep, just add it as a direct dependency. The default deptype if you don't specify one is `build/link`, which sounds like what you want.

**Comment by adamjstewart** [comment]
And don't worry, deptypes are fairly complicated and confuse everyone (myself included). See https://github.com/LLNL/spack/issues/3768 for a decent summary of what they imply.
