### ISSUE TITLE
GoogleTest variant pthreads should be reversed

### ISSUE THREAD

**Issue by alephpiece** [LLNL/spack#43545]
### Steps to reproduce

When googletest is built with `+pthreads`, it actually disables pthreads.
See https://github.com/spack/spack/blame/3f2fa256fc818934fbbcb22e61a297de9da3ba1f/var/spack/repos/builtin/packages/googletest/package.py#L47

Before moving to `define_from_variant`, the `pthreads` variant works fine.

### Error message

A `pthread_mutex_lock` error occurs in some situations when building pthreads-enabled apps with `googletest+gmock+pthreads`, which actually disables pthreads. My guess is that gMock with mixed pthreads flags causes a thread to somehow acquire the same mutex recursively.

FYI, the error messages are listed below.
```
// Message 1: 
pthread_mutex_lock.c:94: ___pthread_mutex_lock: Assertion `mutex->__data.__owner == 0' failed.
Aborted

// Message 2:
[ FATAL ] /path/to/gtest/.../gtest-port.h:1650:: pthread_mutex_lock(&mutex_)failed with error 22
Aborted
```

I'm running into these errors in a project enabling  both `fmt` and `googletest+gmock+pthreads`. Any of the workarounds below should work:
- reversing [this line](https://github.com/spack/spack/blame/3f2fa256fc818934fbbcb22e61a297de9da3ba1f/var/spack/repos/builtin/packages/googletest/package.py#L47) of the spack package file to a previous commit and reinstalling googletest, or
- disabling pthreads in googletest by defininig `GTEST_HAS_PTHREAD=0`, or
- disabling gMock

### Information on your system

* **Spack:** 0.22.0.dev0 (3f2fa256fc818934fbbcb22e61a297de9da3ba1f)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Fixed by #43649 Thanks!
