### ISSUE TITLE
parmetis build with pgi

### ISSUE THREAD

**Issue by eklee15** [LLNL/spack#4360]
parmetis build using pgi compiler creates problem because of the "Illegal use of symbol, __thread" in 
spack/opt/spack/linux-rhel7-ppc64le/pgi-17.4-0/metis-5.1.0-manzuky5hfiezbpvn7ng2at4hdgpmgkt/include/GKlib/gk_externs.h
 
As **parmetis** is dependent on **metis** and the problem is related to **metis**, I do not know what would be the best way to solve this. 

I confirmed I was able to build parmetis by commenting out those three lines in metis/include/GKlib/gk_externs.h, but not sure even this is allowed. 
`//extern __thread int gk_cur_jbufs;
//extern __thread jmp_buf gk_jbufs[];
//extern __thread jmp_buf gk_jbuf;`

**Comment by davydden** [comment]
Add this as a patch to metis when it's build with PGI?

**Comment by eklee15** [comment]
IMO, we cannot just comment out the code because it is for thread local storage. 
Apparently pgi does not support __thread or __Thread (https://www.pgroup.com/userforum/viewtopic.php?p=21461&sid=618de2966e71048ab6470d237053f07c). 

I will look for another option by contacting PGI compiler group.

**Comment by eklee15** [comment]
Need to add -c11 for TSL
