### ISSUE TITLE
spack info mfem not returning safe version info

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/spack#4361]
This used to work but now `spack info mfem` is not returning version information. `spack info silo` and `spack info fastmath` do report version information (like I think all packages would).

The mfem package.py file is a bit odd in the way it specifies versions and so maybe that is part of the problem?

**Comment by adamjstewart** [comment]
Are you on `develop`? Works for me:
```
$ spack info mfem
Package:    mfem
Homepage:   http://www.mfem.org

Safe versions:  
    3.2    http://goo.gl/Y9T75B
    3.1    http://goo.gl/xrScXn
...
```

**Comment by markcmiller86** [comment]
Can someone on OSX please try. That is where I am.

**Comment by markcmiller86** [comment]
FYI...this is from a clean fork, created only 10 mins ago.

**Comment by markcmiller86** [comment]
Ah, I know whats happening. Old spack in my path. Fixed now.
