### ISSUE TITLE
Guidance needed on github URLs for bwa

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#4365]
*bwa* simply tagged older "releases", but recently started using real github releases, which seem to have different URL's.  [Here is the release page](https://github.com/lh3/bwa/releases).

Yesterday I added info for `@0.7.12` and last night `@0.7.15` failed to fetch because it tried to use a pattern based on the `0.7.12` URL.

```python
   url      = "https://github.com/lh3/bwa/releases/download/v0.7.15/bwa-0.7.15.tar.bz2"

   version('0.7.15', 'fcf470a46a1dbe2f96a1c5b87c530554')
   version('0.7.12', 'e24a587baaad411d5da89516ad7a261a',
           url='https://github.com/lh3/bwa/archive/0.7.12.tar.gz')
```

I have a feeling this is not a new situation.  Is there a standard approach?

**Comment by adamjstewart** [comment]
Duplicate of #2737. This is a known issue that we first encountered with the zlib package. For now, the workaround is to specify the version-specific URL for every newer version.

**Comment by hartzell** [comment]
And #2737 in turn points to #2725, which was submitted by that guy @hartzell.

Thanks!
