### ISSUE TITLE
Installation issue: perl

### ISSUE THREAD

**Issue by alexrichert** [LLNL/spack#43725]
### Steps to reproduce the issue

This isn't technically a build error with perl, it's a probably with its effect on downstream packages.
```console
# with, e.g., root:
$ spack install ecflow
# with some other user:
$ spack load ecflow
```

### Error message

```
PermissionError: [Errno 13] Permission denied: '/myfs/spack/opt/spack/linux-sles15-zen/gcc-7.5.0/ecflow-5.8.3-v54njvwdorvcyzaivcaxgimfch5s7tlh/lib/perl5'
```

### Information on your system

* **Spack:** 0.21.0.dev0
* **Python:** 3.6.15
* **Platform:** linux-sles15-zen3
* **Concretizer:** clingo

### Additional information

The problem is that the `setup_dependent_package()` function is called in loading downstream packages (at least, some; I don't know exactly when/why this happens), and contains a `mkdirp()` call:
```
            # Make the site packages directory for extensions,
            # if it does not exist already.
            mkdirp(module.perl_lib_dir)
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
can you submit a pr that deletes that `mkdirp`? it shoudn't be there
