### ISSUE TITLE
Installation issue: intel-oneapi-vtune sampling drivers are not automatically built during installation

### ISSUE THREAD

**Issue by bowling233** [LLNL/spack#43757]
### Steps to reproduce the issue

```console
$ spack spec -I intel-oneapi-vtune
Input spec
--------------------------------
 -   intel-oneapi-vtune

Concretized
--------------------------------
[+]  intel-oneapi-vtune@2023.2.0%dpcpp@2023.2.0+envmods build_system=generic arch=linux-debian12-icelake
$ mpirun -n 116 -machinefile hostfile vtune -collect hpc-performance -data-limit=0 -r hpc-performance ./program
```

### Error message

<details><summary>Error message</summary>

<pre>
vtune: Error: This analysis requires one of these actions: a) Install Intel Sampling Drivers. b) Configure driverless collection with Perf system-wide profiling. To enable Perf system-wide profiling, set /proc/sys/kernel/perf_event_paranoid to 1 or set up Perf tool capabilities.
</pre></details>

### Information on your system

* **Spack:** 0.21.2
* **Python:** 3.11.2
* **Platform:** linux-debian12-icelake
* **Concretizer:** clingo

### Additional information

@rscohn2 It appears that sampling drivers are not automatically built during installation. Can an option be added to build sampling drivers during the installation process of intel-oneapi-vtune? This would bring us great convenience.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by rscohn2** [comment]
Installing the drivers requires root permission. If you install as root, the drivers should be installed by default. If you install vtune as non-root, then you should be able to install the drivers following instructions on this page: https://www.intel.com/content/www/us/en/docs/vtune-profiler/user-guide/2024-1/build-install-sampling-drivers-for-linux-targets.html

**Comment by bowling233** [comment]
Thank you for your reply!
