### ISSUE TITLE
Add the new version 0.16.6 wandb

### ISSUE THREAD

**Issue by yichiac** [LLNL/spack#43769]
### Summary

A new version, 0.16.6, of Wandb was released, and I hope to have it on Spack.
https://pypi.org/project/wandb/
I want to inform the maintainer @thomas-bouvier to please add the new version. Thank you.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by thomas-bouvier** [comment]
Corresponding PR: https://github.com/spack/spack/pull/43891

**Comment by alalazo** [comment]
PRs are welcome, but we don't open issues usually for new versions (with 8k packages, they would create too much noise)

**Comment by alalazo** [comment]
Also, "feature" is a feature request on Spack as a package manager :slightly_smiling_face:
