### ISSUE TITLE
uninstalled package still in the index?

### ISSUE THREAD

**Issue by fgava90** [LLNL/spack#43776]
### Steps to reproduce

Uninstall something and then rebuild the index.
Also works with garbage collector
```console
$ spack gc -y
==> Successfully uninstalled autoconf-archive@2023.02.20%gcc@11.3.0 build_system=autotools arch=linux-rocky8-x86_64/4k6uqa4
$ spack reindex
==> Warning: autoconf-archive@2023.02.20%gcc@11.3.0 build_system=autotools arch=linux-rocky8-x86_64/4k6uqa4 is being updated in the database with prefix /mrltools/spack/opt/linux-rocky8-x86_64/gcc-11.3.0/autoconf-archive/2023.02.20-4k6uqa4oagksq6djik4fsuqaok2pfkyt, but this directory does not contain an installation of the spec, due to: Install prefix /mrltools/spack/opt/linux-rocky8-x86_64/gcc-11.3.0/autoconf-archive/2023.02.20-4k6uqa4oagksq6djik4fsuqaok2pfkyt does not exist.
``` 

### Error message

```console
==> Warning: autoconf-archive@2023.02.20%gcc@11.3.0 build_system=autotools arch=linux-rocky8-x86_64/4k6uqa4 is being updated in the database with prefix /mrltools/spack/opt/linux-rocky8-x86_64/gcc-11.3.0/autoconf-archive/2023.02.20-4k6uqa4oagksq6djik4fsuqaok2pfkyt, but this directory does not contain an installation of the spec, due to: Install prefix /mrltools/spack/opt/linux-rocky8-x86_64/gcc-11.3.0/autoconf-archive/2023.02.20-4k6uqa4oagksq6djik4fsuqaok2pfkyt does not exist.
``` 

### Information on your system

* **Spack:** 0.21.1 (e30fedab102f9281a220fb4fae82e3f8c43a82ac)
* **Python:** 3.6.8
* **Platform:** linux-rocky8-x86_64
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
`spack uninstall` does not delete things from the database if they are referenced by some dependent.

`spack reindex` does not delete existing entries from the database

You can ignore those warnings

**Comment by fgava90** [comment]
If i uninstall stuff with `spack gc` it means that it's stuff that is not referenced by anything, right?
If so, why is it not removed from the database?

Also, if i `spack spec` something that has been removed but for which `spack reindex` gives a warning, it appears with `[-]` coloured in red rather than the standard colour. 
What does that mean?

I'm just trying to understand the uninstall/reindex process and behaviour

**Comment by haampie** [comment]
`spack gc` deletes install prefixes from the file system, and usually doesn't delete anything from the database. We keep track of what build deps were (originally) used, so you could reinstall them later.

So `[-]` means it is no longer installed on the file system.

**Comment by fgava90** [comment]
I see. 
Thanks for the explaination. 
I will close the issue then.
