### ISSUE TITLE
`convert_path` is not part of setuptools API and will be removed 

### ISSUE THREAD

**Issue by abravalheri** [LLNL/spack#43781]
Importing `setuptools.convert_path` has been deprecated for almost 2 years and is about to be removed.

https://github.com/spack/spack/blob/d6baae525fd3a0ace512f6ffd56b907d8802810c/var/spack/repos/builtin/packages/py-cartopy/proj6.patch#L29

In the past setuptools would import convert_path from one of its dependencies for internal use[^1], but that is no longer true.

It seems that newer versions of [catopy](https://github.com/SciTools/cartopy/blob/e9bef0cf39a909c1b58ed540dd50fc93c31c1acb/setup.py#L10) no longer use that function.

[^1]: So it was not part of its public API, but rather an import side effect.

**Comment by adamjstewart** [comment]
What version of setuptools will convert_path be removed in? I can tell older cartopy not to use newer setuptools.

**Comment by adamjstewart** [comment]
Looks like convert_path was removed in https://github.com/SciTools/cartopy/pull/2027, so this only affects cartopy 0.20 and older.

**Comment by adamjstewart** [comment]
Older versions of cartopy will no longer build with older versions of Python, so I think this issue is solved.
