### ISSUE TITLE
log CMake commands to be copy-pastable

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#4379]
untill `spack setup` is fixed, do you guys think it's possible to make the logging of `Cmake` configure command for a package copy-pastable? What i mean is the following. Currently, logs looks like
```
==> 'cmake' 'path/to/prefix' '-DNETCDF_LIBRARIES=path/to/spack/darwin-sierra-x86_64/clang-8.1.0-apple/netcdf-cxx-4.2-lufryppgipbc7i4el5pyongmmfrbuspk/lib/libnetcdf_c++.dylib;path/to/spack/opt/spack/darwin-sierra-x86_64/clang-8.1.0-apple/netcdf-4.4.1.1-tybgpm73o522k2z46w5sevpowfbgjhk5/lib/libnetcdf.dylib'
```
so direct copy-paste won't do. Also removing those `'` symbols won't help either as what one actually have to do is
```
cmake path/to/prefix -DNETCDF_LIBRARIES="path/to/spack/darwin-sierra-x86_64/clang-8.1.0-apple/netcdf-cxx-4.2-lufryppgipbc7i4el5pyongmmfrbuspk/lib/libnetcdf_c++.dylib;path/to/spack/opt/spack/darwin-sierra-x86_64/clang-8.1.0-apple/netcdf-4.4.1.1-tybgpm73o522k2z46w5sevpowfbgjhk5/lib/libnetcdf.dylib"
```
(note the double quotes).

One could, of course, write a python script to transform the original logged output to the desired one, but if the same can be achieved by a minor tweaking of the logging in Spack, that could be useful for developers in combination with `spack env` command.

**Comment by adamjstewart** [comment]
The latter logging would look nicer. But does the former logging not work if you copy and paste it? Single quotes should work equally well.

**Comment by davydden** [comment]
you are absolutely right, it works flawlessly. I must admit i never even though that it's a viable syntax.
