### ISSUE TITLE
Feedback on simplistic install of a Java based app (aka, download the jar file...).

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#4386]
I need to provide [picard](https://github.com/broadinstitute/picard).  It's a java application that depends on at least one other library ([htdjdk](https://github.com/samtools/htsjdk)).  Building from source seems opaque while just plopping the jar file into `prefix` seems easy.  I wouldn't suggest using spack to copy a platform-specific binary into place, but since jar files are platform agnostic, perhaps this isn't so offensive.  Or, perhaps it is.

What's the Spack stand on copying jar files from upstream providers?

---

Additional details....

I haven't totally sussed out the build from source bit, but it seems like it's going to need the htsjdk jar and is likely to reach out and grab it.  There are instructions for using one's own htsjdk.jar, but they include this bit describing what to do with that jar

> to install that version to your local maven repository

All of this seems like a lot of overhead....

My users would be content if I grabbed the distributed jar file, dropped it into `prefix` and set the `$PICARD` environment variable to point there.  

[Picard's instructions](https://broadinstitute.github.io/picard/) recommend running it as follows:

```bash
java -jar /path/to/picard.jar -h
```

and their warm fuzzy recommendation is to abstract that path into an environment variable:

```bash
java -jar $PICARD -h 
```

with the general usage pattern being:

```
java jvm-args -jar $PICARD PicardToolName OPTION1=value1 OPTION2=value2...
```

Apparently no one has revolted and written a `picard` bash script to wrap it up.....

**Comment by adamjstewart** [comment]
I'm fine with just plopping the `.jar` into place, that's what I did for the [Jmol package](https://github.com/LLNL/spack/pull/3041).

**Comment by samfux84** [comment]
@hartzell For pure java tools, I copy the .jar into place and provide a bash wrapper script:

```
[sfux@euler10 2.0.1]$ ls
htsjdk-2.0.1.jar  libIntelDeflater.so  picard  picard.jar  picard-lib.jar
[sfux@euler10 2.0.1]$ cat picard
#!/usr/bin/env bash
java -jar `dirname $0`/picard.jar "$@"
[sfux@euler10 2.0.1]$
```
I think having a wrapper script is handy, because it can be added to the PATH variable, which simplifies usage and cluster users can call it like a binary

**Comment by hartzell** [comment]
@samfux84 -- there are a bunch of java tools that folks here use, and they're all run as `java -jar .../blah.jar ARGS GO HERE`.  I'm surprised that the authors or users haven't wrapped it up as you have.  I suspect it's a language blindness thing (like me with some of Perl's "features").

I'm not sure that it's my, or Spack's, place to be adding functionality to packages.  Are there other examples where Spack adds things like this as part of its installs?

**Comment by hartzell** [comment]
> #!/usr/bin/env bash
> java -jar `dirname $0`/picard.jar "$@"

This doesn't seem bash specific, why not just use `#!/bin/sh` as the sbang line and avoid the dependency on bash?

**Comment by hartzell** [comment]
> I'm not sure that it's my, or Spack's, place to be adding functionality to packages.

On the other hand, this would be a fine place for me to hook in the path to a particular Spack-installed `java` executable....

**Comment by hartzell** [comment]
@samfux84 -- I took your advice and am installing a wrapper.  Your feedback on #4398 would be appreciated.

**Comment by samfux84** [comment]
@hartzell You are right, that the wrapper is not bash specific an one could also use /usr/bin/sh or any other scripting language that allows you to run a java command.

In my opinion it would be the developers job to wrap up things to make them better usable, but there are enough examples that show that we cannot solely rely on developers to provide usable software.

**Comment by hartzell** [comment]
Seems like this has been nicely discussed.

I'll leave on last link that I stumbled on over the weekend and close it.

http://www.gettinggeneticsdone.com/2013/08/script-for-launching-bare-jar-files.html
