### ISSUE TITLE
libc lost iconv variant

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#43874]
### Steps to reproduce

`libc` used to be an actual package with an `iconv` variant, which was used as an external.

Now it's virtual and provided by `glibc` and `musl`, which are automatic externals, and do not have the variant.

We may need to restore this for glibc and maybe fix some packages.

### Information on your system

.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by greenc-FNAL** [comment]
The old `libc` concrete recipe not only had `iconv` and `rpc` variants, but also had `provides` clauses for the corresponding virtual packages. `iconv` could be provided by `libc` or `iconv`, and `rpc` could be provided by `libc` or `libtirpc`. RedHat-like distributions are known for having Glibc built this way, and multiple packages have features in their build systems (usually via autotools) to handle this.

**Comment by greenc-FNAL** [comment]
This is analogous to (but separable from) the `gettext`/`libintl` issue.
