### ISSUE TITLE
Compiler environment (PATH) not loaded when `modules` is empty

### ISSUE THREAD

**Issue by stephenmsachs** [LLNL/spack#43895]
### Steps to reproduce

See current develop pipeline genrate steps for aws-pcluster-x86_64_v4 stack, e.g. https://gitlab.spack.io/spack/spack/-/jobs/10937087

The error seems to be related to the [early return in compiler_environment when no modules](https://github.com/spack/spack/pull/29441). 

While [compiling a test file](https://github.com/spack/spack/blob/4a40a76291f05fdd76e12497b1891c5ad1705ebe/lib/spack/spack/compiler.py#L496) the `$PATH` is not set although the correct `compilers.yaml` file is read. This results in the wrong `binutils` being used and the compilation fails.

If I add some dummy `modules: [foo/bar]` to the `%onapi` compiler the issue disappears.

### Error message

```
==> Warning: cannot detect libc from oneapi@=2023.2.0. The compiler will not be used during concretization.
```

### Information on your system

```
bash-4.2# spack debug report
* **Spack:** 0.22.0.dev0 (7d87369ead99046f04211cd95047cabf1e2b30c1)
* **Python:** 3.7.16
* **Platform:** linux-amzn2-zen2
* **Concretizer:** clingo
```
I only had a `zen2` machine handy. The error is the same with the `x86_64_v3` target, but you need to remove the `x86_64_v4` target from the stacks `spack.yaml` to reproduce on this machine.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
Oof, not sure what I was thinking when submitting the linked pr. Thanks for figuring that one out :grimacing:.

**Comment by stephenmsachs** [comment]
The proposed PR fixes the issue for me. Thanks!
