### ISSUE TITLE
RHEL9 arch=None-None-x86_64 is unsatisfiable

### ISSUE THREAD

**Issue by wlugmayr** [LLNL/spack#43917]
### Steps to reproduce

I have a spack installation tree on centos7 and added rhel9 packages due an upgrade of the linux on new nodes. After some git pull in the last weeks I cannot make packages anymore due the error below. I moved the centos7/rhel9 ~/.spack away and made a new compiler find so the message should be from a clean directory.

### Error message

spack install -j 8 patchelf target=x86_64
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    patchelf arch=None-None-x86_64 is unsatisfiable

### Information on your system

$ spack debug report
* **Spack:** 0.22.0.dev0 (7f2cedd31fa83e404c9701d93c9496d6d1824e4e)
* **Python:** 3.9.18
* **Platform:** linux-rhel9-broadwell
* **Concretizer:** clingo

$ cat /etc/os-release 
NAME="Red Hat Enterprise Linux"
VERSION="9.3 (Plow)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="9.3"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Red Hat Enterprise Linux 9.3 (Plow)"
ANSI_COLOR="0;31"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:redhat:enterprise_linux:9::baseos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9"
BUG_REPORT_URL="https://issues.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 9"
REDHAT_BUGZILLA_PRODUCT_VERSION=9.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.3"

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
Hm, is this a very involved way of saying "you have no compilers for the current os"?

What if you remove `~/.spack/**/compilers.yaml`

**Comment by wlugmayr** [comment]
Thanks, the issue has something to do with my exiting local repository from centos7. But it contains only the repo.yaml and some recipies.

The error appears when after i call
    spack repo add /gpfs/cssb/software/repositories/spack/cssb
    spack repo list

So I created a new empty repository, created a new package and copied the existing recipie in. Then the install works for builtin e.g. patchelf and my package as usual. I have only a handful of recipies, so this solution is fine for me. From my point this issue can be closed.

**Comment by jsta** [comment]
what solved this for me was ensuring the system met the spack prerequisites (https://spack.readthedocs.io/en/latest/getting_started.html#id7) and re-running `spack compiler find`
