### ISSUE TITLE
Python 3 testing

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#4396]
We have a lot of unit tests for Spack, and we use Travis to test several versions of Python 3. But these tests never seem to catch anything. After we added Python 3 support, commands like `spack fetch`, `spack checksum`, and `spack info` didn't work at all for Python 3, but all of our unit tests passed. It occurred to me that perhaps we are not actually testing Python 3 at all. When we run `spack`, isn't it picking up the first `python` in the `PATH`, usually for the system `python2` installation?

@alalazo @tgamblin

**Comment by alalazo** [comment]
The Travis instances are correctly picking up `python@2` vs. `python@3`. I may be remember it wrong, but I think we even discussed some time ago an error in a PR that was reported differently depending on the python version, due to the different behavior of `hasattr` between 2 and 3.

**Comment by adamjstewart** [comment]
That's true, I do recall that. It's pretty sad that our coverage is so poor that things like `spack fetch`, `spack checksum`, and `spack info` aren't covered...

**Comment by alalazo** [comment]
PRs welcome :smile:
