### ISSUE TITLE
Installation issue: gromacs on Neoverse V2 with/without SVE

### ISSUE THREAD

**Issue by dslarm** [LLNL/spack#44062]
### Steps to reproduce the issue

```console
$ spack spec -I gromacs +sve
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    gromacs+sve is unsatisfiable
```

### Error message

<details><summary>Error message</summary>
spack spec -l gromacs +sve

<pre>
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    gromacs+sve is unsatisfiable
</pre></details>

### Information on your system

Neoverse V2, Rocky 9.
The default gromacs will build - but it won't add SVE as a variant - and so it won't allow it to be disabled, or enabled, without triggering internal spack issue. I'd expect both options to be there (FWIW - I intend to benchmark to help figure out if this should be default on, or default off).

```
* **Spack:** 0.22.0.dev0 (f7afd67a266be82d426ce3a6d80e7a7c7500d122)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-neoverse_v2
* **Concretizer:** clingo
```

### Additional information

@danielahlin @eirrgang @junghans 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by giordano** [comment]
I take this is fixed by #44183?
