### ISSUE TITLE
Update version of iperf3 from 3.6 to 3.16

### ISSUE THREAD

**Issue by dmagdavector** [LLNL/spack#44096]
### Steps to reproduce

Spack currently only explicitly has version 3.6 of the iPerf3 package (out of ESnet / LBNL). This makes the default the latest version of 3.16, and adds some other versions (found in some Linux distros, for possible compat purposes).

```
diff --git a/var/spack/repos/builtin/packages/iperf3/package.py b/var/spack/repos/builtin/packages/iperf3/package.py
index 162ea1b65a..aeca3aafcf 100644
--- a/var/spack/repos/builtin/packages/iperf3/package.py
+++ b/var/spack/repos/builtin/packages/iperf3/package.py
@@ -12,6 +12,10 @@ class Iperf3(AutotoolsPackage):
     maintained project."""
 
     homepage = "https://software.es.net/iperf/"
-    url = "https://github.com/esnet/iperf/archive/3.6.tar.gz"
+    url = "https://downloads.es.net/pub/iperf/iperf-3.16.tar.gz"
 
+    version("3.16", sha256="cc740c6bbea104398cc3e466befc515a25896ec85e44a662d5f4a767b9cf713e")
+    version("3.14", sha256="723fcc430a027bc6952628fa2a3ac77584a1d0bd328275e573fc9b206c155004")
+    version("3.12", sha256="72034ecfb6a7d6d67e384e19fb6efff3236ca4f7ed4c518d7db649c447e1ffd6")
+    version("3.9", sha256="24b63a26382325f759f11d421779a937b63ca1bc17c44587d2fcfedab60ac038")
     version("3.6", sha256="1ad23f70a8eb4b892a3cbb247cafa956e0f5c7d8b8601b1d9c8031c2a806f23f")
```

### Information on your system

* **Spack:** 0.21.0 (65d3221a9c436e77af9e802e543c71bd702ff4e2)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-cascadelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by wdconinc** [comment]
Would you be interested in contributing this change as a pull request? We would very much welcome this contribution, and it does not imply any future maintenance promise from you end. Feel free to ping me if you do, and I can give it a review.

**Comment by dmagdavector** [comment]
See pull/44152
