### ISSUE TITLE
Installation issue: ffmpeg@7.0

### ISSUE THREAD

**Issue by aiPenguin** [LLNL/spack#44125]
### Steps to reproduce the issue

```console
$ spack spec -I ffmpeg@7.0
Input spec
--------------------------------
 -   ffmpeg@7.0

Concretized
--------------------------------
 -   ffmpeg@7.0%gcc@8.5.0~X~avresample+bzlib~drawtext+gpl~libaom~libmp3lame~libopenjpeg~libopus~libsnappy~libspeex~libssh~libvorbis~libvpx~libwebp~libx264~libzmq~lzma~nonfree~openssl~sdl2+shared+version3 build_system=autotools arch=linux-almalinux8-zen
[+]      ^alsa-lib@1.2.3.2%gcc@8.5.0~python build_system=autotools arch=linux-almalinux8-zen
[^]      ^bzip2@1.0.8%gcc@8.5.0~debug~pic+shared build_system=generic arch=linux-almalinux8-zen
[^]          ^diffutils@3.8%gcc@8.5.0 build_system=autotools arch=linux-almalinux8-zen
[^]      ^libiconv@1.16%gcc@8.5.0 build_system=autotools libs=shared,static arch=linux-almalinux8-zen
[+]      ^yasm@1.3.0%gcc@8.5.0 build_system=autotools arch=linux-almalinux8-zen
[^]      ^zlib@1.2.13%gcc@8.5.0+optimize+pic+shared build_system=makefile arch=linux-almalinux8-zen```
```

### Error message

<details><summary>Error message</summary>

<pre>
[+] /home/atuin/b211dd/b211dd11/USER-SPACK/opt/linux-almalinux8-zen/gcc-8.5.0/alsa-lib-1.2.3.2-t4lcbsfgfezaph3rkbaqmdmgos5gvrcq
[+] /apps/SPACK/0.19.1/opt/linux-almalinux8-zen/gcc-8.5.0/libiconv-1.16-fldvcfrja7xsgftadlxegkv6mfnhq6xs
[+] /home/atuin/b211dd/b211dd11/USER-SPACK/opt/linux-almalinux8-zen/gcc-8.5.0/yasm-1.3.0-ifuujrkb7nfhmaalqsiyaf6lhzvoomkh
[+] /apps/SPACK/0.19.1/opt/linux-almalinux8-zen/gcc-8.5.0/zlib-1.2.13-elttwwbchphhdbb22kyl4tdn27yrjcjw
[+] /apps/SPACK/0.19.1/opt/linux-almalinux8-zen/gcc-8.5.0/diffutils-3.8-dvdahpvh3x7cvc3426ql7sqhk7k4o536
[+] /apps/SPACK/0.19.1/opt/linux-almalinux8-zen/gcc-8.5.0/bzip2-1.0.8-v5ilnc2ytto6u36ah2euw467acedfdyu
==> Installing ffmpeg-7.0-csfu4b4xjvzvkkujjy67w3y2xz444kmp
==> No binary for ffmpeg-7.0-csfu4b4xjvzvkkujjy67w3y2xz444kmp found: installing from source
==> Warning: There is no checksum on file to fetch ffmpeg@7.0 safely.
==>   Fetch anyway? [y/N] y
==> Fetching https://ffmpeg.org/releases/ffmpeg-7.0.tar.bz2
==> No patches needed for ffmpeg
==> ffmpeg: Executing phase: 'autoreconf'
==> ffmpeg: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/var/tmp/b211dd11/spack-stage-ffmpeg-7.0-csfu4b4xjvzvkkujjy67w3y2xz444kmp/spack-src/configure' '--prefix=/home/atuin/b211dd/b211dd11/USER-SPACK/opt/linux-almalinux8-zen/gcc-8.5.0/ffmpeg-7.0-csfu4b4xjvzvkkujjy67w3y2xz444kmp' '--enable-pic' '--cc=/apps/SPACK/0.19.1/lib/spack/env/gcc/gcc' '--cxx=/apps/SPACK/0.19.1/lib/spack/env/gcc/g++' '--disable-libxcb' '--disable-libxcb-shape' '--disable-libxcb-shm' '--disable-libxcb-xfixes' '--disable-xlib' '--disable-libfontconfig' '--disable-libfreetype' '--disable-libfribidi' '--enable-bzlib' '--enable-gpl' '--disable-libmp3lame' '--disable-libopenjpeg' '--disable-libopus' '--disable-libspeex' '--disable-libvorbis' '--disable-libvpx' '--disable-libx264' '--disable-avresample' '--disable-nonfree' '--disable-openssl' '--enable-shared' '--enable-version3' '--disable-libzmq' '--disable-libssh' '--disable-libwebp' '--disable-lzma' '--disable-libsnappy' '--disable-sdl2' '--disable-libaom'
See build log for details:
  /var/tmp/b211dd11/spack-stage-ffmpeg-7.0-csfu4b4xjvzvkkujjy67w3y2xz444kmp/spack-build-out.txt
</pre></details>

### Information on your system

* **Spack:** 0.19.1
* **Python:** 3.9.5
* **Platform:** linux-almalinux8-zen3
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/spack/spack/files/15278983/spack-build-env.txt)
[spack-build-out.txt](https://github.com/spack/spack/files/15278984/spack-build-out.txt)
[spack-configure-args.txt](https://github.com/spack/spack/files/15279062/spack-configure-args.txt)

[avail_args.txt](https://github.com/spack/spack/files/15279039/avail_args.txt)

Hi there and @xjrc,

while building the `ffmpeg` of version 7.0, there is an error about the used argument, which is shown above.
With running `./configure --help` the available arguments are listed in `avail-args.txt`, there is no argument containing `avresample`.

But in the `spack-configure-args.txt`, there is.

Is there any way I can modify the `spack-configure-args.txt` and install the `ffmpeg@7.0` locally?
Or will this issue be fixed soon?

Thx.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by drkrynstrng** [comment]
@aiPenguin Try modifying this line in your local ffmpeg package.py so that it restricts the avresample variant to the older versions: https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/ffmpeg/package.py#L83

```
variant("avresample", default=False, when="@0.11:4.4", description="AV reasmpling component")
```

**Comment by aiPenguin** [comment]
Thanks a lot! @drkrynstrng
