### ISSUE TITLE
spack dependents command

### ISSUE THREAD

**Issue by samfux84** [LLNL/spack#4414]
If I would like to know which of my installed packages depend on a particular package, then I would use the  spack dependents command. For instance, checking for cuda:

```
[spackapps@lo-login-02 spack]$ spack dependents cuda
==> Dependents of cuda@8.0.61%gcc@4.8.5/mxdqob5
-- linux-centos7-x86_64 / gcc@4.8.5 -----------------------------
cudnn@6.0  libgpuarray@0.6.2
[spackapps@lo-login-02 spack]$
```

Is there also a possibility to check within the entire package repository (not depending if the packages are installed or not on my system)?

At the moment I am using a workaround which is not very pretty:

```
[spackapps@lo-login-02 spack]$ grep depends_on ./var/spack/repos/builtin/packages/*/package.py | grep cuda | cut -d "/" -f 7 | sort | uniq
caffe
cbtf-argonavis
cntk
cuda-memtest
cudnn
flann
gromacs
hoomd-blue
hpx5
hwloc
isaac
kaldi
kokkos
lbann
libgpuarray
mallocmc
nccl
opencv
openmpi
openspeedshop
osu-micro-benchmarks
py-theano
relion
suite-sparse
[spackapps@lo-login-02 spack]$
```

Is it possible to do this within spack ?

**Comment by adamjstewart** [comment]
@markcmiller86 also expressed interest in this capability in #4334. I would love to see `spack dependents` extended to do this. I've been using the exact same grep command as you in the meantime.
