### ISSUE TITLE
hpx: Invalid default variant

### ISSUE THREAD

**Issue by wspear** [LLNL/spack#44194]
The max_cpu_count variant for hpx is set to 64 by default.  If that value doesn't match the actual number of cpus this can result in runtime failures like:

```
mpirun -np 1 ./build/test_future --hpx:use-process-mask
hpx::init: hpx::exception caught: Currently, HPX_HAVE_MAX_CPU_COUNT is set to 64 while your system has 96 processing units. Please reconfigure HPX with -DHPX_WITH_MAX_CPU_COUNT=96 (or higher) to increase the maximal CPU count supported by HPX.: HPX(invalid_status)
```

Does the correct cpu count need to be determined at install time (making binary relocation ungeneralizable for hpx), or is there a flag that can be added at build or runtime to force hpx to allow a sub-optimal cpu count? Alternatively, is there a way to determine the correct value from inside the spack package and use that for configuration?

@albestro  @hkaiser  @msimberg  @teonnik

**Comment by msimberg** [comment]
HPX itself actually already defaults to not setting a max CPU count and uses dynamic bitsets instead for CPU masks (that's what the max count is primarily for). The default in the spack package doesn't reflect the HPX default. From previous testing performance was not affected by using dynamic bitsets so changing the default in the spack package would probably make sense. @hkaiser do any of the new schedulers care more about using static or dynamic bitsets?

https://github.com/spack/spack/blob/e9149cfc3cfc94bd66aa0e0901ce562cf8b75713/var/spack/repos/builtin/packages/hpx/package.py#L61-L66 would need to be changed to allow some special value to represent no limit. In HPX's CMake logic it's represented by an empty string, but maybe something like `none` is a better way to represent it in the spack package?

**Comment by hkaiser** [comment]
I think currently HPX still uses a maximum of 64 cores as the default internal value (if nothing else was specified). However @msimberg is right that we could (and should) remove this restriction. I will prepare a PR to be integrated with the upcoming HPX V1.10.0 release.
