### ISSUE TITLE
py-warpx: missing libwarpx.3d.so

### ISSUE THREAD

**Issue by wspear** [LLNL/spack#44196]
When running py-warpx with this spec:
<details><pre>
Singularity> spack find -dvl py-warpx
-- linux-ubuntu22.04-x86_64 / gcc@11.4.0 ------------------------
v2c3ijh py-warpx@23.08+mpi build_system=python_pip
6cqtdnc     gcc-runtime@11.4.0 build_system=generic
sv53zqp     py-mpi4py@3.1.5 build_system=python_pip
w2qwypv         mpich@4.1.2~argobots~cuda+fortran~hwloc+hydra+libxml2+pci~rocm+romio~slurm~vci~verbs~wrapperrpath~xpmem build_system=autotools datatype-engine=auto device=ch4 netmod=ofi pmi=pmi
cr3n6rf         py-cython@0.29.36 build_system=python_pip patches=c4369ad
5xecxy6     py-numpy@1.26.4 build_system=python_pip patches=873745d
lwfqkzc         openblas@0.3.26~bignuma~consistent_fpcsr+dynamic_dispatch+fortran~ilp64+locking+pic+shared build_system=makefile symbol_suffix=none threads=openmp
fqkbmyz             perl@5.38.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1
y2dkgvn                 berkeley-db@18.1.40+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc
dqe6k55         py-cython@3.0.8 build_system=python_pip
zozobat         py-meson-python@0.15.0 build_system=python_pip
7uxm2d6             meson@1.3.2 build_system=python_pip patches=0f0b1bd
ciukme5                 ninja@1.11.1+re2c build_system=generic
ubsvgtp                     re2c@2.2 build_system=generic
v3cu2nr             py-pyproject-metadata@0.7.1 build_system=python_pip
inqb4jv                 py-packaging@23.1 build_system=python_pip
ns5afel     py-periodictable@1.5.0 build_system=python_pip
xjokjsx         py-pyparsing@3.1.2 build_system=python_pip
texmlek             py-flit-core@3.9.0 build_system=python_pip
eib7nyn     py-picmistandard@0.25.0 build_system=python_pip
rfkb743         py-scipy@1.13.0 build_system=python_pip
yt35oks             py-pybind11@2.12.0~ipo build_system=cmake build_type=Release generator=ninja
aa4f7ge             py-pythran@0.15.0 build_system=python_pip
vmicg23                 py-beniget@0.4.1 build_system=python_pip
kwfwpsz                 py-gast@0.5.4 build_system=python_pip
lg5s3e5                 py-ply@3.11 build_system=python_pip
7iflr6e     py-pip@23.1.2 build_system=generic
kdxc323     py-setuptools@69.2.0 build_system=generic
6a7c3gr     py-wheel@0.41.2 build_system=generic
beq7w7g     python@3.11.7+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=13fa8bf,b0615b2,ebdca64,f2fd060
mvv5tmf         bzip2@1.0.8~debug~pic+shared build_system=generic
ppgdy35             diffutils@3.10 build_system=autotools
47hbnkz         expat@2.6.2+libbsd build_system=autotools
ipezmag             libbsd@0.12.1 build_system=autotools
4o7v5qt                 libmd@1.0.4 build_system=autotools
xc5bypn         gdbm@1.23 build_system=autotools
7pjbhkg         gettext@0.22.4+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools
vn2i3ot             libiconv@1.17 build_system=autotools libs=shared,static
tomx3zi             libxml2@2.10.3+pic~python+shared build_system=autotools
4kecmsc             tar@1.34 build_system=autotools zip=pigz
kox732v                 pigz@2.8 build_system=makefile
pmda3i7                 zstd@1.5.6+programs build_system=makefile compression=none libs=shared,static
kunl7zm         gmake@4.4.1~guile build_system=generic
gr7x2kq         libffi@3.4.6 build_system=autotools
ifj2qvd         libxcrypt@4.4.35~obsolete_api build_system=autotools patches=4885da3
7a4mbz3         ncurses@6.4~symlinks+termlib abi=none build_system=autotools patches=7a351bc
ms4sbsh         openssl@3.2.1~docs+shared build_system=generic certs=mozilla
5bui7u7             ca-certificates-mozilla@2023-05-30 build_system=generic
xbzeeoo         pkgconf@1.9.5 build_system=autotools
fl4uzzk         readline@8.2 build_system=autotools patches=bbf97f1
cggmg33         sqlite@3.43.2+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools
wjsrjs3         util-linux-uuid@2.38.1 build_system=autotools
7w2vrb7         xz@5.4.6+pic build_system=autotools libs=shared,static
nsjxqfd         zlib-ng@2.1.6+compat+new_strategies+opt+pic+shared build_system=autotools
5gt7i7c     warpx@23.08+app~ascent~eb~ipo+lib+mpi+mpithreadmultiple+openpmd+psatd+qed~qedtablegen~sensei+shared+tprof build_system=cmake build_type=Release compute=omp dims=1,2,3,rz generator=make precision=double
oua6mx2         blaspp@2023.11.05~cuda~ipo+openmp~rocm+shared~sycl build_system=cmake build_type=Release generator=make
3gq4owh         cmake@3.27.9~doc+ncurses+ownlibs build_system=generic build_type=Release
bqjvf6e             curl@8.6.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl
pz4ulyn                 nghttp2@1.57.0 build_system=autotools
yb5cjjd         fftw@3.3.10+mpi+openmp~pfft_patches+shared build_system=autotools precision=double,float
n667d7f         lapackpp@2023.11.05~cuda~ipo~rocm+shared~sycl build_system=cmake build_type=Release generator=make
p2ragba         openpmd-api@0.15.2~adios1+adios2+hdf5~ipo+mpi~python+shared build_system=cmake build_type=Release generator=make
fhdsl6r             adios2@2.10.0~aws+blosc2+bzip2~cuda~dataspaces+fortran~hdf5~ipo~kokkos+libcatalyst~libpressio+mgard+mpi~pic+png~python~rocm+sst~sycl+sz+zfp build_system=cmake build_type=Release generator=make
oqersnh                 c-blosc2@2.11.1+avx2~ipo+lizard+lz4+snappy+zlib+zstd build_system=cmake build_type=Release generator=make
h2jq3ak                     lizard@1.0 build_system=makefile patches=4895619
p4zke22                     lz4@1.9.4+pic build_system=makefile libs=shared,static
35xzcjq                     snappy@1.1.10~ipo+pic+shared build_system=cmake build_type=Release generator=make
ja7hh6e                 libcatalyst@2.0.0-rc4~conduit~fortran~ipo+mpi~python build_system=cmake build_type=Release generator=make
tvt2a5g                 libfabric@1.21.0~debug~kdreg~uring build_system=autotools fabrics=rxm,sockets,tcp,udp
t4bvllv                 libpng@1.6.39~ipo~pic build_system=cmake build_type=Release generator=make libs=shared,static
fyotdh6                 mgard@2023-12-09~cuda~ipo+openmp+serial~timing~unstructured build_system=cmake build_type=Release generator=make
foi6iac                     libarchive@3.7.1+iconv build_system=autotools compression=bz2lib,lz4,lzma,lzo2,zlib,zstd crypto=openssl libs=shared,static programs=none xar=libxml2
3d6ay7f                         lzo@2.10 build_system=autotools libs=shared,static
wedunko                     protobuf@3.25.3~ipo+shared build_system=cmake build_type=Release generator=make
ee74qz5                         abseil-cpp@20240116.1~ipo+shared build_system=cmake build_type=Release cxxstd=14 generator=make
kzdcd4w                     sed@4.9 build_system=autotools
5gdypvk                     yaml-cpp@0.7.0~ipo+pic+shared~tests build_system=cmake build_type=Release generator=make
wb2ylj7                 sz@2.1.12.5~fortran~hdf5~ipo~netcdf~pastri~python~random_access+shared~stats~time_compression build_system=cmake build_type=Release generator=make
n2etbeb                 zfp@0.5.5~aligned~c~cuda~fasthash~fortran~ipo~openmp~profile~python+shared~strided~twoway+utilities bsws=64 build_system=cmake build_type=Release generator=make
s4ksdaq             hdf5@1.14.3~cxx+fortran+hl~ipo~java~map+mpi+shared~subfiling~szip~threadsafe+tools api=default build_system=cmake build_type=Release generator=make patches=82088c8
jypesrd             nlohmann-json@3.11.2~ipo+multiple_headers build_system=cmake build_type=Release generator=make
6es2wos             toml11@3.8.1~ipo build_system=cmake build_type=Release cxx_std=11 generator=make

==> 1 installed package

</pre></details>
to execute the example from: Examples/Tests/gaussian_beam/PICMI_inputs_gaussian_beam.py

I get this error:
<pre><details>
Traceback (most recent call last):
  File "/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-warpx-23.08-v2c3ijhudpzgwc7tt4xxljcdaf2kpvlh/lib/python3.11/site-packages/pywarpx/_libwarpx.py", line 111, in load_library
    self.libwarpx_so = ctypes.CDLL(os.path.join(self._get_package_root(), libname))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.4.0/python-3.11.7-beq7w7gyojt45jvcdcneocen6ikp2nkf/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-warpx-23.08-v2c3ijhudpzgwc7tt4xxljcdaf2kpvlh/lib/python3.11/site-packages/pywarpx/libwarpx.3d.so: cannot open shared object file: No such file or directory

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/users/wspear/gilgamesh-e4s-24.05/testsuite-cuda90-x86_64_24.05/validation_tests/py-warpx/PICMI_inputs_gaussian_beam.py", line 95, in <module>
    sim.step()
  File "/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-warpx-23.08-v2c3ijhudpzgwc7tt4xxljcdaf2kpvlh/lib/python3.11/site-packages/pywarpx/picmi.py", line 1851, in step
    self.initialize_warpx(mpi_comm)
  File "/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-warpx-23.08-v2c3ijhudpzgwc7tt4xxljcdaf2kpvlh/lib/python3.11/site-packages/pywarpx/picmi.py", line 1843, in initialize_warpx
    pywarpx.warpx.init(mpi_comm, max_step=self.max_steps, stop_time=self.max_time)
  File "/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-warpx-23.08-v2c3ijhudpzgwc7tt4xxljcdaf2kpvlh/lib/python3.11/site-packages/pywarpx/WarpX.py", line 95, in init
    libwarpx.initialize(argv, mpi_comm=mpi_comm)
  File "/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-warpx-23.08-v2c3ijhudpzgwc7tt4xxljcdaf2kpvlh/lib/python3.11/site-packages/pywarpx/_libwarpx.py", line 451, in initialize
    self.amrex_init(argv, mpi_comm)
  File "/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-warpx-23.08-v2c3ijhudpzgwc7tt4xxljcdaf2kpvlh/lib/python3.11/site-packages/pywarpx/_libwarpx.py", line 437, in amrex_init
    self.libwarpx_so.amrex_init(argc, argvC)
    ^^^^^^^^^^^^^^^^
  File "/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-warpx-23.08-v2c3ijhudpzgwc7tt4xxljcdaf2kpvlh/lib/python3.11/site-packages/pywarpx/_libwarpx.py", line 61, in __getattr__
    self.load_library()
  File "/spack/opt/spack/linux-ubuntu22.04-x86_64/gcc-11.4.0/py-warpx-23.08-v2c3ijhudpzgwc7tt4xxljcdaf2kpvlh/lib/python3.11/site-packages/pywarpx/_libwarpx.py", line 115, in load_library
    raise Exception(f'"{libname}" was not installed. Installation instructions can be found here https://warpx.readthedocs.io/en/latest/install/users.html') from e
Exception: "libwarpx.3d.so" was not installed. Installation instructions can be found here https://warpx.readthedocs.io/en/latest/install/users.html
</pre></details>

libwarpx.3d.so isn't anywhere I can find. The only .so file provided by the spack install of py-warpx is named: lib/python3.11/site-packages/pywarpx/libwarpx.rz.so. The warpx install py-warpx uses has libwarpx.3d.MPI.OMP.DP.PDP.OPMD.PSATD.QED.so and libwarpx.rz.so.

@RemiLehe  @ax3l  @dpgrote

**Comment by haampie** [comment]
Fixed in newer versions iirc

**Comment by haampie** [comment]
Closing because it's not a package issue, not a spack issue.
