### ISSUE TITLE
Installation issue: openmpi (Spack v0.21 & v0.22) with compiler intel@2021.10.0

### ISSUE THREAD

**Issue by harshula** [LLNL/spack#44275]
### Steps to reproduce the issue

```console
$ spack spec -I openmpi@4.1.5 %intel@2021.10.0 target=x86_64
Input spec
--------------------------------
 -   openmpi@4.1.5%intel@2021.10.0 arch=None-None-x86_64

Concretized
--------------------------------
 -   openmpi@4.1.5%intel@2021.10.0~atomics~cuda~cxx~cxx_exceptions~gpfs~internal-hwloc~internal-pmix~java~legacylaunchers~lustre~memchecker~openshmem~orterunprefix+romio+rsh~singularity+static+vt+wrapper-rpath build_system=autotools fabrics=none schedulers=none arch=linux-rocky8-x86_64
[+]      ^gmake@4.4.1%intel@2021.10.0~guile build_system=generic arch=linux-rocky8-x86_64
[+]      ^hwloc@2.9.1%intel@2021.10.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-rocky8-x86_64
[+]          ^libpciaccess@0.17%intel@2021.10.0 build_system=autotools arch=linux-rocky8-x86_64
[+]              ^util-macros@1.19.3%intel@2021.10.0 build_system=autotools arch=linux-rocky8-x86_64
[+]          ^libxml2@2.10.3%intel@2021.10.0+pic~python+shared build_system=autotools arch=linux-rocky8-x86_64
[+]              ^libiconv@1.17%intel@2021.10.0 build_system=autotools libs=shared,static arch=linux-rocky8-x86_64
[+]              ^xz@5.4.1%intel@2021.10.0~pic build_system=autotools libs=shared,static arch=linux-rocky8-x86_64
[+]          ^ncurses@6.4%intel@2021.10.0~symlinks+termlib abi=none build_system=autotools arch=linux-rocky8-x86_64
[+]      ^numactl@2.0.14%intel@2021.10.0 build_system=autotools patches=4e1d78c,62fc8a8,ff37630 arch=linux-rocky8-x86_64
[+]          ^autoconf@2.69%intel@2021.10.0 build_system=autotools patches=35c4492,7793209,a49dd5b arch=linux-rocky8-x86_64
[+]          ^automake@1.16.5%intel@2021.10.0 build_system=autotools arch=linux-rocky8-x86_64
[+]          ^libtool@2.4.6%intel@2021.10.0 build_system=autotools arch=linux-rocky8-x86_64
[+]          ^m4@1.4.19%intel@2021.10.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-rocky8-x86_64
[+]              ^diffutils@3.9%intel@2021.10.0 build_system=autotools arch=linux-rocky8-x86_64
[+]              ^libsigsegv@2.14%intel@2021.10.0 build_system=autotools arch=linux-rocky8-x86_64
[+]      ^openssh@9.5p1%intel@2021.10.0+gssapi build_system=autotools arch=linux-rocky8-x86_64
[+]          ^krb5@1.20.1%intel@2021.10.0+shared build_system=autotools arch=linux-rocky8-x86_64
[+]              ^bison@3.8.2%intel@2021.10.0 build_system=autotools arch=linux-rocky8-x86_64
[+]              ^findutils@4.9.0%intel@2021.10.0 build_system=autotools patches=440b954 arch=linux-rocky8-x86_64
[+]              ^gettext@0.22.3%intel@2021.10.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-rocky8-x86_64
[+]                  ^bzip2@1.0.8%intel@2021.10.0~debug~pic+shared build_system=generic arch=linux-rocky8-x86_64
[+]                  ^tar@1.34%intel@2021.10.0 build_system=autotools zip=pigz arch=linux-rocky8-x86_64
[+]                      ^pigz@2.7%intel@2021.10.0 build_system=makefile arch=linux-rocky8-x86_64
[+]                      ^zstd@1.5.5%intel@2021.10.0+programs build_system=makefile compression=none libs=shared,static arch=linux-rocky8-x86_64
[+]          ^libedit@3.1-20210216%intel@2021.10.0 build_system=autotools arch=linux-rocky8-x86_64
[+]          ^libxcrypt@4.4.35%intel@2021.10.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-rocky8-x86_64
[+]          ^openssl@3.1.3%intel@2021.10.0~docs+shared build_system=generic certs=mozilla arch=linux-rocky8-x86_64
[+]              ^ca-certificates-mozilla@2023-05-30%intel@2021.10.0 build_system=generic arch=linux-rocky8-x86_64
[e]      ^perl@5.26.3%intel@2021.10.0~cpanm+opcode+open+shared+threads build_system=generic patches=8cf4302 arch=linux-rocky8-x86_64
[+]      ^pkgconf@1.9.5%intel@2021.10.0 build_system=autotools arch=linux-rocky8-x86_64
[+]      ^pmix@4.2.2%intel@2021.10.0~docs+pmi_backwards_compatibility~python~restful build_system=autotools arch=linux-rocky8-x86_64
[+]          ^libevent@2.1.12%intel@2021.10.0+openssl build_system=autotools arch=linux-rocky8-x86_64
[+]      ^zlib-ng@2.1.4%intel@2021.10.0+compat+opt build_system=autotools arch=linux-rocky8-x86_64

...
```

### Error message

<details><summary>Error message</summary>

<pre>
libtool: compile: mv -f "opal_datatype_pack.o" ".libs/opal_datatype_pack.o"
mv: cannot stat 'opal_datatype_pack.o': No such file or directory
make[2]: *** [Makefile:1919: opal_datatype_pack.lo] Error 1
make[2]: *** Waiting for unfinished jobs....
libtool: compile: mv -f "opal_copy_functions_heterogeneous.o" ".libs/opal_copy_functions_heterogeneous.o"
libtool: compile: mv -f "opal_datatype_unpack.o" "libdatatype_reliable_la-opal_datatype_unpack.o"
libtool: compile: mv -f "opal_datatype_unpack.o" ".libs/opal_datatype_unpack.o"
libtool: compile:  /opt/spack/lib/spack/env/intel/icc -DHAVE_CONFIG_H -I. -I../../opal/include -I../../ompi/include -I../../oshmem/include -I../../opal/mca/hwloc/hwloc201/hwloc/include/private/autogen -I../../opal/mca/hwloc/hwloc201/hwloc/include/hwloc/autogen -I../../ompi/mpiext/cuda/c -I../.. -I../../orte/include -I/opt/release/linux-rocky8-x86_64/intel-2021.10.0/zlib-ng-2.1.4-4tvwm2k222uptzkuasvov6kp6ltswesr/include -I/opt/release/linux-rocky8-x86_64/intel-2021.10.0/hwloc-2.9.1-2yajwwfpq5qqtith3vgtxg2cc63fol3h/include -I/opt/release/linux-rocky8-x86_64/intel-2021.10.0/libevent-2.1.12-ddhx67xlj5bq33jeoekytmmtagojds2c/include -I/usr/local/include -I/usr/local/include -O3 -DNDEBUG -finline-functions -fno-strict-aliasing -restrict -Qoption,cpp,--extended_float_types -pthread -MT opal_copy_functions_heterogeneous.lo -MD -MP -MF .deps/opal_copy_functions_heterogeneous.Tpo -c opal_copy_functions_heterogeneous.c >/dev/null 2>&1
mv: cannot stat 'opal_datatype_unpack.o': No such file or directory
mv -f .deps/libdatatype_reliable_la-opal_datatype_unpack.Tpo .deps/libdatatype_reliable_la-opal_datatype_unpack.Plo
make[2]: *** [Makefile:1919: opal_datatype_unpack.lo] Error 1
make[2]: Leaving directory '/tmp/root/spack-stage/spack-stage-openmpi-4.1.5-s33yfyeebyfb34il4vdjhdblaevtsy4u/spack-src/opal/datatype'
make[1]: *** [Makefile:2394: all-recursive] Error 1
make[1]: Leaving directory '/tmp/root/spack-stage/spack-stage-openmpi-4.1.5-s33yfyeebyfb34il4vdjhdblaevtsy4u/spack-src/opal'
make: *** [Makefile:1912: all-recursive] Error 1

</pre></details>

### Information on your system

* **Spack:** 0.21.2 (f17445a582bb076993f88fef0e0e121a2062a816)
* **Python:** 3.6.8
* **Platform:** linux-rocky8-skylake
* **Concretizer:** clingo

### Additional information

Hi @hppritcha and @naughtont3 ,

Openmpi can be successfully compiled with `%intel@2021.6.0`, but fails with `%intel@2021.10.0`. i.e. `spack install openmpi@4.1.5 %intel@2021.6.0 target=x86_64` succeeds.

packages.yaml:
```
  libtool:
    version: [:2.4.6]
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by hppritcha** [comment]
could you rerun the build adding ```--debug``` to the spack command line?  Hopefully we'll get a helpful compiler error message. 

also, are you really wanting to use the intel classic compilers?  they are EOL or almost.

**Comment by harshula** [comment]
[spack-install-openmpi.log](https://github.com/spack/spack/files/15382432/spack-install-openmpi.log)

Yes, we are still using the Intel classic compilers.

**Comment by harshula** [comment]
Hi @hppritcha , Are you able to reproduce the issue?

**Comment by hppritcha** [comment]
the system where i can test this is down for DST for the next couple of days.

**Comment by hppritcha** [comment]
hmm looking at your log note what the EOF compiler is saying:

```
icc: remark #10441: The Intel(R) C++ Compiler Classic (ICC) is dep
             recated and will be removed from product release in the second hal
             f of 2023. The Intel(R) oneAPI DPC++/C++ Compiler (ICX) is the rec
             ommended compiler moving forward. Please transition to use this co
             mpiler. Use '-diag-disable=10441' to disable this message.
```
you will need to set this compiler option with this version of the intel classic compiler.

**Comment by harshula** [comment]
Thanks! This worked: `spack install openmpi@4.1.5 cppflags="-diag-disable=10441" %intel@2021.10.0 target=x86_64`
Do you plan on inserting this compiler flag when an `%intel` classic compiler versions `2021.7.0` (https://www.intel.com/content/www/us/en/developer/articles/release-notes/oneapi-c-compiler-release-notes.html) and up are building openmpi?

**Comment by hppritcha** [comment]
sorry just saw this.  i will add this to my spack todo list.

**Comment by harshula** [comment]
Hi @hppritcha , I thought I'd help out by creating PR https://github.com/spack/spack/pull/44614 to fix this issue.

**Comment by harshula** [comment]
Fixed by https://github.com/spack/spack/pull/44614
