### ISSUE TITLE
Environments: root specs are not always marked explicit

### ISSUE THREAD

**Issue by koysean** [LLNL/spack#44326]
### Steps to reproduce

When Spack concretizes and installs an environment where some root specs are dependencies of other root specs, it can mistakenly mark some of the root specs as implicit. For example, given this `spack.yaml`, `cmake` (a dependency of `blt`) will be installed as an implicit spec:

```
spack:
  view: false
  concretizer:
    reuse: true
    unify: when_possible
  specs:
    - blt
    - cmake
```

After concretizing and installing, the output of `spack find --explicit` is
```
==> In environment /home/skoyama/work/spack_dev/issues/root_specs_not_explicit
==> 2 root specs
[+] blt  [+] cmake

==> Installed packages
-- linux-ubuntu22.04-skylake / gcc@11.4.0 ---------
blt@0.6.2
==> 1 installed package
```
and `cmake` appears in the output of `spack find --implicit`.

This causes the `cmake` module to be hidden if generating modules with `hide_implicits: true`. Luckily, `spack gc` does not try to uninstall `cmake`, so I guess that's identifying unused/implicit specs differently.

This did not happen when concretizing an environment containing `cmake` and `libpng`, another package that has a `cmake` dependency. My guess is that this has to do with the alphabetical ordering of the concretized specs, since regardless of the order of root specs in `spack.yaml`, they come out alphabetized in `spack concretize` output.

This issue is similar to https://github.com/spack/spack/issues/43146 (and I suspect has the same root cause). 

### Information on your system

* **Spack:** 0.22.0 (5fe93fee1eec46a0750bd340198bffcb92ff9eec)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
I cannot reproduce this

**Comment by haampie** [comment]
Ok, I guess I get it now. And I think it was by design.

Suppose you install two specs `x` and `y`. The two ways here are roughly equivalent:


```sh
spack install x y  # no env

spack env create .
spack env activate .
spack add x y
spack install  # active env
```

in both cases `x` and `y` are marked explicit.

Now if you do `spack install z`, whether an env is active or not, `z` will be marked explicit. The only difference with an active env is that `z` is located in the env instead of concretized.

Similarly, if you would install one root specifically with `spack install x` on the active env, `x` gets marked explicit, since it's installed specifically. If `y` happens to be a dependency of `x`, it does not get marked explicit, since you didn't specifically ask to install it.

So, either leave it as is, or also add environment roots that are deps of the specifically selected `spack install z` to the list of things to mark explicit.

**Comment by koysean** [comment]
In case there's still trouble with reproducing this: I deleted my `~/.spack` and was able to reproduce it again with a fresh clone of spack. Here's my step-by-step:
1. clone spack and check out `v0.22.0`
2. make a directory for the environment and copy the `spack.yaml` above into the environment
3. source the Spack shell env and activate the environment (`. spack/share/spack/setup-env.sh; spack env activate <env_dir>`)
4. `spack concretize`
5. `spack install`
6. `spack find --explicit`

Since I had no configs set up, Spack automatically populated the compiler config in the environment, speccing out the system `gcc@11.4.0` installation in `/usr/bin`.

With that out of the way -- I'm installing the environment with `spack install`. When I run this command I am explicitly asking Spack to install all of the concretized root specs. To me this means all root specs should be marked as explicit.

It seems to me that running `spack concretize; spack install` off of the `spack.yaml` I posted above is equivalent to this example you gave:
```
spack env create .
spack env activate .
spack add x y
spack install  # active env
```
in which, as you said, both `x` and `y` should be marked explicit.

edit: forgot to mention, but I think someone on the Spack Slack speculated that this has to do with the `reuse` and `unify` settings. I can try testing with other settings to see if certain combinations don't produce this bug.

**Comment by koysean** [comment]
Did a bit more testing, and these settings
```
reuse: true
unify: true
```
makes both `cmake` and `blt` explicit, which is the expected behavior.

`unify: false` and `unify: when_possible` both reproduce the issue, even though I'm pretty sure they concretize the same specs.

**Comment by haampie** [comment]
OK, I managed to reproduce an issue.
