### ISSUE TITLE
Spack Tutorial and Software Requests

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#4433]
Hey everyone,

I just posted this to our [Google Group](https://groups.google.com/forum/#!topic/spack/o_VJvGFGUFs), but I'm going to be hosting a Spack Tutorial next week here at ANL. If you're in the Chicago area and would like to attend, let me know.

More importantly, I need a list of packages that I can install during the packaging demonstration. Does anyone have any requests for software they would like to see in Spack? Ideally, it would be fairly simple to package and wouldn't have too many dependencies. I would also like at least one package from each of the following build systems:

* `MakefilePackage`
* `AutotoolsPackage`
* `CMakePackage`
* `PythonPackage`
* `RPackage`

I'll mark this post as `up-for-grabs` so that new users can find a list of software to attempt to package.

**Comment by samfux84** [comment]
@adamjstewart TensorFlow would be great, but I am not sure if this is feasible as it is quite a pain to compile it (I did it on a CentOS 6.8 system).

**Comment by adamjstewart** [comment]
I think there's a lot of open pull requests for tensorflow, aren't there?

**Comment by samfux84** [comment]
@adamjstewart I overlooked the pull requests about tensorflow and only checked the list of available packages. But you are right. It does not make sense to come up with a tensorflow package if there are already quite some PR's about this.

**Comment by adamjstewart** [comment]
Closing this issue now that the ANL Spack Tutorial is now complete. We got around 25-30 eager potential/newish Spack users in attendance.

**Comment by llpesce** [comment]
any chance I can get a copy of that tutorial? I missed it.

**Comment by adamjstewart** [comment]
I didn't really produce any slides, but if you're looking for a good Spack tutorial you should check out http://spack.readthedocs.io/en/latest/tutorial.html. That's the one we use an SC every year.

**Comment by llpesce** [comment]
Thanks a lot. I will look it up.

Lorenzo Pesce, Ph.D.
The Computation Institute
The University of Chicago, Northwestern University and  Argonne National laboratories
lpesce@uchicago.edu
