### ISSUE TITLE
Installation issue: hip@5.7.0 +cuda ~rocm fails to build

### ISSUE THREAD

**Issue by pranav-sivaraman** [LLNL/spack#44385]
### Steps to reproduce the issue

```console
$ spack spec
Input spec
--------------------------------
 -   hip@5.7.0+cuda~rocm

Concretized
--------------------------------
 -   hip@5.7.0%gcc@12.3.0+cuda~ipo~rocm build_system=cmake build_type=Release generator=make patches=5bb9b0e,7668b2a,aee7249,b589a02,c2ee21c arch=linux-sles15-zen3
[+]      ^cmake@3.27.9%gcc@7.5.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-ubuntu18.04-x86_64_v3
[+]          ^curl@8.7.1%gcc@7.5.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-ubuntu18.04-x86_64_v3
[+]              ^nghttp2@1.61.0%gcc@7.5.0 build_system=autotools arch=linux-ubuntu18.04-x86_64_v3
[+]              ^openssl@3.3.0%gcc@7.5.0~docs+shared build_system=generic certs=mozilla arch=linux-ubuntu18.04-x86_64_v3
[+]                  ^ca-certificates-mozilla@2023-05-30%gcc@7.5.0 build_system=generic arch=linux-ubuntu18.04-x86_64_v3
[+]          ^gcc-runtime@7.5.0%gcc@7.5.0 build_system=generic arch=linux-ubuntu18.04-x86_64_v3
[e]          ^glibc@2.27%gcc@7.5.0 build_system=autotools arch=linux-ubuntu18.04-x86_64_v3
[+]          ^ncurses@6.5%gcc@7.5.0~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-ubuntu18.04-x86_64_v3
[+]          ^zlib-ng@2.1.6%gcc@7.5.0+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-ubuntu18.04-x86_64_v3
[e]      ^cuda@12.2.91%gcc@12.3.0~allow-unsupported-compilers~dev build_system=generic arch=linux-sles15-zen3
[+]      ^gcc-runtime@12.3.0%gcc@12.3.0 build_system=generic arch=linux-sles15-x86_64_v3
[e]      ^glibc@2.31%gcc@12.3.0 build_system=autotools arch=linux-sles15-x86_64_v3
[+]      ^gmake@4.4.1%gcc@7.5.0~guile build_system=generic arch=linux-ubuntu18.04-x86_64_v3
[+]      ^libedit@3.1-20230828%gcc@7.5.0 build_system=autotools arch=linux-ubuntu18.04-x86_64_v3
[+]          ^pkgconf@2.2.0%gcc@7.5.0 build_system=autotools arch=linux-ubuntu18.04-x86_64_v3
[+]      ^perl@5.38.2%gcc@7.5.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-ubuntu18.04-x86_64_v3
[+]          ^berkeley-db@18.1.40%gcc@7.5.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu18.04-x86_64_v3
[+]          ^bzip2@1.0.8%gcc@7.5.0~debug~pic+shared build_system=generic arch=linux-ubuntu18.04-x86_64_v3
[+]              ^diffutils@3.10%gcc@7.5.0 build_system=autotools arch=linux-ubuntu18.04-x86_64_v3
[+]          ^gdbm@1.23%gcc@7.5.0 build_system=autotools arch=linux-ubuntu18.04-x86_64_v3
[+]              ^readline@8.2%gcc@7.5.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu18.04-x86_64_v3
[+]      ^perl-file-which@1.27%gcc@12.3.0 build_system=perl arch=linux-sles15-zen3
[+]      ^perl-uri-encode@1.1.1%gcc@12.3.0 build_system=perl arch=linux-sles15-zen3
[+]          ^perl-module-build@0.4234%gcc@12.3.0 build_system=perl arch=linux-sles15-zen3
```

### Error message

<details><summary>Error message</summary>

<pre>
[+] /usr (external glibc-2.27-txizrnr5izvzixdg5eg7kcq2wnkxzuwg)
[+] /opt/nvidia/hpc_sdk/Linux_x86_64/23.9/cuda/12.2 (external cuda-12.2.91-azcxjeatgeqzcunc3l4brbgx6xor5qd3)
[+] /usr (external glibc-2.31-5o7v6xevdoh5rad5zevk3ufi2ivixvuw)
[+] /global/u2/p/psivaram/spack/opt/spack/linux-ubuntu18.04-x86_64_v3/gcc-7.5.0/gcc-runtime-7.5.0-m6wt5o3xabjg46jiscjohm5djjrdmea5
[+] /global/u2/p/psivaram/spack/opt/spack/linux-sles15-x86_64_v3/gcc-12.3.0/gcc-runtime-12.3.0-gz2rubmnz2tox6gann6lzwtmsh4xwhsq
[+] /global/u2/p/psivaram/spack/opt/spack/linux-ubuntu18.04-x86_64_v3/gcc-7.5.0/berkeley-db-18.1.40-qcn5ywkuqgvepggvjdemhlzh6yspsiht
[+] /global/u2/p/psivaram/spack/opt/spack/linux-ubuntu18.04-x86_64_v3/gcc-7.5.0/bzip2-1.0.8-57b5n5hbqasoav5yspzzmfdxj7iqcydx
[+] /global/u2/p/psivaram/spack/opt/spack/linux-ubuntu18.04-x86_64_v3/gcc-7.5.0/zlib-ng-2.1.6-sp4y6abyivcnvzhmdo4mmcmxak4nvl76
[+] /global/u2/p/psivaram/spack/opt/spack/linux-ubuntu18.04-x86_64_v3/gcc-7.5.0/ncurses-6.5-lxxhn2v5powrwivojzzmnvyorbodrjdr
[+] /global/u2/p/psivaram/spack/opt/spack/linux-ubuntu18.04-x86_64_v3/gcc-7.5.0/nghttp2-1.61.0-3xhqy7acuk7q6h3rpvifvbdzmg6kmsbs
[+] /global/u2/p/psivaram/spack/opt/spack/linux-ubuntu18.04-x86_64_v3/gcc-7.5.0/gmake-4.4.1-tgae3j3od3imqeq54adogofwiiydnneb
[+] /global/u2/p/psivaram/spack/opt/spack/linux-ubuntu18.04-x86_64_v3/gcc-7.5.0/libedit-3.1-20230828-w7rifve7otzinive5l6b6sae223wdn47
[+] /global/u2/p/psivaram/spack/opt/spack/linux-ubuntu18.04-x86_64_v3/gcc-7.5.0/readline-8.2-x6vpyovcqq7cquk2ldafwr54az2zi7sr
[+] /global/u2/p/psivaram/spack/opt/spack/linux-ubuntu18.04-x86_64_v3/gcc-7.5.0/openssl-3.3.0-wv32wt5wzexeuawspk7pk2pjlatnsbks
[+] /global/u2/p/psivaram/spack/opt/spack/linux-ubuntu18.04-x86_64_v3/gcc-7.5.0/gdbm-1.23-iw3umntwrtsj2hy2ksyzzzvpxkdbuet7
[+] /global/u2/p/psivaram/spack/opt/spack/linux-ubuntu18.04-x86_64_v3/gcc-7.5.0/curl-8.7.1-xkqyjd6e3uqiwowci353f25ygtvcsly2
[+] /global/u2/p/psivaram/spack/opt/spack/linux-ubuntu18.04-x86_64_v3/gcc-7.5.0/perl-5.38.2-iz6ggl2fe6ln4gqw2us34w3arndjeqil
[+] /global/u2/p/psivaram/spack/opt/spack/linux-ubuntu18.04-x86_64_v3/gcc-7.5.0/cmake-3.27.9-z2u4v7v6vxm32pfgl4lkiok5is6jqsge
[+] /global/u2/p/psivaram/spack/opt/spack/linux-sles15-zen3/gcc-12.3.0/perl-file-which-1.27-3jnncca75o4sij3wgvnuistsunq2uu7e
[+] /global/u2/p/psivaram/spack/opt/spack/linux-sles15-zen3/gcc-12.3.0/perl-uri-encode-1.1.1-ejjerxk6u2z247xxeuum5yjglp5p7ibe
==> Installing hip-5.7.0-rmwwxizapkse74ya5ymwqiqfz3pgcbcp [21/21]
==> No binary for hip-5.7.0-rmwwxizapkse74ya5ymwqiqfz3pgcbcp found: installing from source
==> Using cached archive: /global/u2/p/psivaram/spack/var/spack/cache/_source-cache/archive/cb/cb61234eec7879fb7e20937659ad535b93a6e66fc8de0a543da8b7702474f2fc.tar.gz
==> Using cached archive: /global/u2/p/psivaram/spack/var/spack/cache/_source-cache/archive/bc/bc2447cb6fd86dff6a333b04e77ce85755104d9011a14a044af53caf02449573.tar.gz
==> Using cached archive: /global/u2/p/psivaram/spack/var/spack/cache/_source-cache/archive/9f/9f839bf7226e5e26f3150f8ba6eca507ab9a668e68b207736301b3bb9040c973.tar.gz
==> Using cached archive: /global/u2/p/psivaram/spack/var/spack/cache/_source-cache/archive/b1/b1dae3cfc715e71dce92ac1da94265a9398944c76cee85ffab8f0c93665a48d6.tar.gz
==> Using cached archive: /global/u2/p/psivaram/spack/var/spack/cache/_source-cache/archive/5b/5bb9b0e08888830ccf3a0a658529fe25f4ee62b5b8890f349bf2cc914236eb2f
==> Using cached archive: /global/u2/p/psivaram/spack/var/spack/cache/_source-cache/archive/76/7668b2a710baf4cb063e6b00280fb75c4c3e0511575e8298a9c7ae5143f60b33
==> Using cached archive: /global/u2/p/psivaram/spack/var/spack/cache/_source-cache/archive/c2/c2ee21cdc55262c7c6ba65546b5ca5f65ea89730
==> Moving resource stage
	source: /tmp/psivaram/spack-stage/resource-clr-rmwwxizapkse74ya5ymwqiqfz3pgcbcp/spack-src/
	destination: /tmp/psivaram/spack-stage/spack-stage-hip-5.7.0-rmwwxizapkse74ya5ymwqiqfz3pgcbcp/spack-src/clr
==> Moving resource stage
	source: /tmp/psivaram/spack-stage/resource-hipcc-rmwwxizapkse74ya5ymwqiqfz3pgcbcp/spack-src/
	destination: /tmp/psivaram/spack-stage/spack-stage-hip-5.7.0-rmwwxizapkse74ya5ymwqiqfz3pgcbcp/spack-src/hipcc
==> Moving resource stage
	source: /tmp/psivaram/spack-stage/resource-hip-tests-rmwwxizapkse74ya5ymwqiqfz3pgcbcp/spack-src/
	destination: /tmp/psivaram/spack-stage/spack-stage-hip-5.7.0-rmwwxizapkse74ya5ymwqiqfz3pgcbcp/spack-src/hip-tests
==> Applied patch https://github.com/ROCm/clr/commit/c4f773db0b4ccbbeed4e3d6c0f6bff299c2aa3f0.patch?full_index=1
==> Applied patch https://github.com/ROCm/clr/commit/7868876db742fb4d44483892856a66d2993add03.patch?full_index=1
==> Applied patch /global/u2/p/psivaram/spack/var/spack/repos/builtin/packages/hip/0014-Remove-compiler-rt-linkage-for-host-for-5.7.0.patch
==> Applied patch /global/u2/p/psivaram/spack/var/spack/repos/builtin/packages/hip/0015-reverting-operator-mixup-fix-for-slate.patch
==> Applied patch https://github.com/ROCm/HIP/commit/50ee82f6bc4aad10908ce09198c9f7ebfb2a3561.patch?full_index=1
==> Ran patch() for hip
==> hip: Executing phase: 'cmake'
==> Error: KeyError: 'No spec with name llvm-amdgpu in hip@=5.7.0%gcc@=12.3.0+cuda~ipo~rocm build_system=cmake build_type=Release generator=make patches=5bb9b0e,7668b2a,aee7249,b589a02,c2ee21c arch=linux-sles15-zen3 ^[deptypes=build,link] berkeley-db@=18.1.40%gcc@=7.5.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu18.04-x86_64_v3 ^[deptypes=build,link] bzip2@=1.0.8%gcc@=7.5.0~debug~pic+shared build_system=generic arch=linux-ubuntu18.04-x86_64_v3 ^[deptypes=build] ca-certificates-mozilla@=2023-05-30%gcc@=7.5.0 build_system=generic arch=linux-ubuntu18.04-x86_64_v3 ^[deptypes=build] cmake@=3.27.9%gcc@=7.5.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-ubuntu18.04-x86_64_v3 ^[deptypes=build,link] cuda@=12.2.91%gcc@=12.3.0~allow-unsupported-compilers~dev build_system=generic arch=linux-sles15-zen3 ^[deptypes=build,link] curl@=8.7.1%gcc@=7.5.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-ubuntu18.04-x86_64_v3 ^[deptypes=build] diffutils@=3.10%gcc@=7.5.0 build_system=autotools arch=linux-ubuntu18.04-x86_64_v3 ^[deptypes=link] gcc-runtime@=7.5.0%gcc@=7.5.0 build_system=generic arch=linux-ubuntu18.04-x86_64_v3 ^[deptypes=link] gcc-runtime@=12.3.0%gcc@=12.3.0 build_system=generic arch=linux-sles15-x86_64_v3 ^[deptypes=build,link] gdbm@=1.23%gcc@=7.5.0 build_system=autotools arch=linux-ubuntu18.04-x86_64_v3 ^[deptypes=build,link virtuals=iconv,libc] glibc@=2.27%gcc@=7.5.0 build_system=autotools arch=linux-ubuntu18.04-x86_64_v3 ^[deptypes=link virtuals=libc] glibc@=2.31%gcc@=12.3.0 build_system=autotools arch=linux-sles15-x86_64_v3 ^[deptypes=build,link] gmake@=4.4.1%gcc@=7.5.0~guile build_system=generic arch=linux-ubuntu18.04-x86_64_v3 ^[deptypes=build] libedit@=3.1-20230828%gcc@=7.5.0 build_system=autotools arch=linux-ubuntu18.04-x86_64_v3 ^[deptypes=build,link] ncurses@=6.5%gcc@=7.5.0~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-ubuntu18.04-x86_64_v3 ^[deptypes=build,link] nghttp2@=1.61.0%gcc@=7.5.0 build_system=autotools arch=linux-ubuntu18.04-x86_64_v3 ^[deptypes=build,link] openssl@=3.3.0%gcc@=7.5.0~docs+shared build_system=generic certs=mozilla arch=linux-ubuntu18.04-x86_64_v3 ^[deptypes=build,run] perl@=5.38.2%gcc@=7.5.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-ubuntu18.04-x86_64_v3 ^[deptypes=build,link] perl-file-which@=1.27%gcc@=12.3.0 build_system=perl arch=linux-sles15-zen3 ^[deptypes=build] perl-module-build@=0.4234%gcc@=12.3.0 build_system=perl arch=linux-sles15-zen3 ^[deptypes=build,link] perl-uri-encode@=1.1.1%gcc@=12.3.0 build_system=perl arch=linux-sles15-zen3 ^[deptypes=build virtuals=pkgconfig] pkgconf@=2.2.0%gcc@=7.5.0 build_system=autotools arch=linux-ubuntu18.04-x86_64_v3 ^[deptypes=build,link] readline@=8.2%gcc@=7.5.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu18.04-x86_64_v3 ^[deptypes=build,link virtuals=zlib-api] zlib-ng@=2.1.6%gcc@=7.5.0+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-ubuntu18.04-x86_64_v3'

/global/u2/p/psivaram/spack/var/spack/repos/builtin/packages/hip/package.py:564, in cmake_args:
        561            args.append(self.define("AMD_OPENCL_PATH", self.stage.source_path + "/clr/opencl"))
        562            args.append(self.define("CLR_BUILD_HIP", True)),
        563            args.append(self.define("CLR_BUILD_OCL", False)),
  >>    564            args.append(self.define("HIP_LLVM_ROOT", self.spec["llvm-amdgpu"].prefix))
        565        if "@5.6:5.7" in self.spec:
        566            args.append(self.define("HIPCC_BIN_DIR", self.stage.source_path + "/hipcc/bin")),
        567        if "@6.0:" in self.spec:

See build log for details:
  /tmp/psivaram/spack-stage/spack-stage-hip-5.7.0-rmwwxizapkse74ya5ymwqiqfz3pgcbcp/spack-build-out.txt

</pre></details>

### Information on your system

* **Spack:** 0.23.0.dev0 (72deb53832477792b1eff8bd9b6289e84ca85ead)
* **Python:** 3.6.15
* **Platform:** linux-sles15-zen3
* **Concretizer:** clingo

### Additional information

Spack Environment
```shell
spack:
  specs:
  - hip@5.7.0 ~rocm +cuda
  view: true
  concretizer:
    unify: true
  mirrors:
    develop-2024-05-19: https://binaries.spack.io/develop-2024-05-19
  packages:
    cuda:
      externals:
      - spec: cuda@12.2.91
        prefix: /opt/nvidia/hpc_sdk/Linux_x86_64/23.9/cuda/12.2

``` 

@haampie @renjithravindrankannath @srekolam 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by renjithravindrankannath** [comment]
Created PR [44453 ](https://github.com/spack/spack/pull/44453)to address this issue.

**Comment by srekolam** [comment]
[44453  is](https://github.com/spack/spack/pull/44453) is merged now .Closing this issue

**Comment by mariodirenzo** [comment]
Hello,
I was experiencing the same error while installing HIP.
After updating spack to the latest version of `develop`, I got into this new error
```
Error: ChecksumError: sha256 checksum failed for /tmp/mariodr/spack-stage/resource-hipother-vgji3m3ukquzltlu3zqx4e5ltf7oojwn/rocm-6.1.2.tar.gz
    Expected 8b975623c8ed1db53feea2cfd5d29f2a615e890aee1157d0d17adeb97200643f but got 2740d1e3dcf1f2d07d2a8db6acf4c972941ae392172b83fd8ddcfe8706a40d0b. File size = 33490 bytes. Contents = b'\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x03\xec]kr\xdbH...\xfe\x9e\xbf\xe7O\xfb\xfe\x7f\xfbA\xd5\x9c\x00\xc0\x03\x00'
```
which is fixed by this patch
```
diff --git a/var/spack/repos/builtin/packages/hip/package.py b/var/spack/repos/builtin/packages/hip/package.py
index af9feff5be..7bd920a6b8 100644
--- a/var/spack/repos/builtin/packages/hip/package.py
+++ b/var/spack/repos/builtin/packages/hip/package.py
@@ -234,7 +234,7 @@ class Hip(CMakePackage):
         )
     # Add hipother sources thru the below
     for d_version, d_shasum in [
-        ("6.1.2", "8b975623c8ed1db53feea2cfd5d29f2a615e890aee1157d0d17adeb97200643f"),
+        ("6.1.2", "2740d1e3dcf1f2d07d2a8db6acf4c972941ae392172b83fd8ddcfe8706a40d0b"),
         ("6.1.1", "8b975623c8ed1db53feea2cfd5d29f2a615e890aee1157d0d17adeb97200643f"),
         ("6.1.0", "43a48ccc82f705a15852392ee7419e648d913716bfc04063a53d2d17979b1b46"),
         ("6.0.2", "0bebb3774debcecc0b29a0cc5aa98e373a3ee7acf161503d0d9c9d0ecc8b8010"),
```

**Comment by renjithravindrankannath** [comment]
> Hello, I was experiencing the same error while installing HIP. After updating spack to the latest version of `develop`, I got into this new error
> 
> ```
> Error: ChecksumError: sha256 checksum failed for /tmp/mariodr/spack-stage/resource-hipother-vgji3m3ukquzltlu3zqx4e5ltf7oojwn/rocm-6.1.2.tar.gz
>     Expected 8b975623c8ed1db53feea2cfd5d29f2a615e890aee1157d0d17adeb97200643f but got 2740d1e3dcf1f2d07d2a8db6acf4c972941ae392172b83fd8ddcfe8706a40d0b. File size = 33490 bytes. Contents = b'\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x03\xec]kr\xdbH...\xfe\x9e\xbf\xe7O\xfb\xfe\x7f\xfbA\xd5\x9c\x00\xc0\x03\x00'
> ```
> 
> which is fixed by this patch
> 
> ```
> diff --git a/var/spack/repos/builtin/packages/hip/package.py b/var/spack/repos/builtin/packages/hip/package.py
> index af9feff5be..7bd920a6b8 100644
> --- a/var/spack/repos/builtin/packages/hip/package.py
> +++ b/var/spack/repos/builtin/packages/hip/package.py
> @@ -234,7 +234,7 @@ class Hip(CMakePackage):
>          )
>      # Add hipother sources thru the below
>      for d_version, d_shasum in [
> -        ("6.1.2", "8b975623c8ed1db53feea2cfd5d29f2a615e890aee1157d0d17adeb97200643f"),
> +        ("6.1.2", "2740d1e3dcf1f2d07d2a8db6acf4c972941ae392172b83fd8ddcfe8706a40d0b"),
>          ("6.1.1", "8b975623c8ed1db53feea2cfd5d29f2a615e890aee1157d0d17adeb97200643f"),
>          ("6.1.0", "43a48ccc82f705a15852392ee7419e648d913716bfc04063a53d2d17979b1b46"),
>          ("6.0.2", "0bebb3774debcecc0b29a0cc5aa98e373a3ee7acf161503d0d9c9d0ecc8b8010"),
> ```

Created PR #45152 to correct the checksum
