### ISSUE TITLE
Speeding up Modules Tutorial

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#4448]
@tgamblin @alalazo I'm planning on walking through the [Modules Tutorial](http://spack.readthedocs.io/en/latest/tutorial_modules.html#modules-tutorial) at our ANL Spack Tutorial and I noticed that it requires you to build the following software:
```
$ spack install gcc
$ spack install netlib-scalapack ^openmpi ^openblas
$ spack install netlib-scalapack ^mpich ^openblas
$ spack install netlib-scalapack ^openmpi ^netlib-lapack
$ spack install netlib-scalapack ^mpich ^netlib-lapack
$ spack install py-scipy ^openblas
```
Depending on whether you are building on a supercomputer or a laptop, installing GCC can take anywhere from 15 minutes (32-core Broadwell) to 4 hours (MacBook Pro). OpenMPI and MPICH usually take another half hour as well. Is there any way we can speed this up??

I was thinking about using `spack install --fake`, but that won't work for GCC. You can't `spack compiler add` GCC unless the executables print the right version message. Apparently, it also doesn't work for Python packages due to my changes in #3367 (still trying to track down why). Does anyone have a better idea?

**Comment by alalazo** [comment]
@adamjstewart What I usually do is to prepare an instance of Spack with the software beforehand, and use it during the tutorial.

**Comment by adamjstewart** [comment]
And you distribute it via tarball? That's not a bad idea.

**Comment by tgamblin** [comment]
Yeah I'm looking forward to having support for binary packages, as I think this will make tutorials much easier.

**Comment by tgamblin** [comment]
We did this with AWS instances for our SC16 tutorial and locally at LC with a partially symlinked Spack install in the shared filesystem that users could `cp -r` to their home directory.  Neither of those is as simple as I'd like.
