### ISSUE TITLE
Spack does not allow to specify a dependency for a variant that is true

### ISSUE THREAD

**Issue by serbanmaerean** [LLNL/spack#4456]
I am trying to build matio and I get the following error when I try to show the dependencies graph:
```
--> spack graph matio%xl_r^zlib%gcc
==> Error: matio does not depend on zlib
```

However, the default is to use zlib:
```
--> spack graph matio
o  matio
|\
| o  hdf5
|/| 
o |  zlib
 /
o  spectrum-mpi
```

If I add +zlib, then yes, it's fine, but why do I have to add that when zlib is built by default?
```
--> spack graph matio+zlib%xl_r^zlib%gcc
o  matio
|\
| o  hdf5
|/| 
o |  zlib
 /
o  spectrum-mpi
```

**Comment by davydden** [comment]
> why do I have to add that when zlib is built by default?

this is a known issue and limitation of the conretizer. @adamjstewart would probably link to the occurrence of this problem, more than a year ago.

**Comment by davydden** [comment]
see http://spack.readthedocs.io/en/latest/known_issues.html#default-variants-are-not-taken-into-account-during-concretization

**Comment by serbanmaerean** [comment]
Great, so I am not doing anything wrong.  Thx much.
