### ISSUE TITLE
Tracking configuration files with git

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#4457]
Since I make changes to our Spack configuration files so frequently, I like to track them with git and store them on our GitLab server. Up until now, I've stored my configuration files in `~/.spack`. However, we are getting to the point where multiple sys admins need to maintain the same site installation of Spack. Each one of these sys admins would have to maintain an identical set of configuration files in their home directories. I want to move our configuration files to `$SPACK_ROOT/etc/spack` to make it easier to ensure that everyone is on the same page. The problem is that this directory is within the Spack git repo and contains other directories. I don't want any of my configuration files to be tracked by Spack's git repo, and I don't want any of Spack's files to be tracked by my configuration git repo. Can anyone think of a way to do this? The only idea I've come up with would be to move the `$SPACK_ROOT/etc/spack` configuration hierarchy to `$SPACK_ROOT/etc/spack/site` so that we can ignore everything in that directory in Spack's `.gitignore`.

**Comment by tgamblin** [comment]
Just because the in that directory doesn't mean it is tracked.  I *believe* the root dir there is in .gitignore.  If it is not, it probably should be, with an exception for `etc/spack/default/*`.

Note we're also talking on the telcon today (in 10 min) about adding a `/etc/spack` scope, which would be above default but below `$spack/etc/spack`.  We need it so spack will have sensible defaults for users on our CORAL early access (power/gpu) machines. @mplegendre is going to add that.

**Comment by alalazo** [comment]
@adamjstewart Not sure if our solution could apply to your case. Anyhow: we deploy software via Spack in an automated way using a few Jenkins job. One of the job in the workflow check out the configuration files we maintain in a separate repository and copies them in the right position within Spack folders.

**Comment by adamjstewart** [comment]
> I _believe_ the root dir there is in .gitignore. If it is not, it probably should be, with an exception for `etc/spack/default/*`

Currently, we have:
```
/etc/spack/licenses
/etc/spack/*.yaml
```
in the `.gitignore`. So `.yaml` files are ignored, but not all of the other scripts and directories I usually store there. My .gitignore and .git folder would also not be ignored, which is the real problem.

I was talking to @svenevs and we came up with a couple ideas. Apparently you can do the equivalent of a `gitinclude` in your `.gitignore` by ignoring the entire directory but explicitly including `etc/spack/defaults`. Another idea would be to store everything elsewhere outside of the Spack repo and symlink all of the `.yaml` files into `etc/spack`.

> adding a `/etc/spack` scope

This sounds like a great idea, and makes perfect sense. We currently have 5 Spack installations due to changing hashes, so it would be nice to make sure that every Spack instance has the same settings. But this won't be too helpful for us as our clusters are NFS mounted, so we can't edit `/etc` files without rebooting the cluster.

P.S. If you're going to be talking about adding configuration scopes, see https://github.com/LLNL/spack/issues/4427 for another useful idea I had.

**Comment by samfux84** [comment]
@adamjstewart We are solving the problem of multiple people working on the same spack in a different way.

We created a technical user account "spackapps", which is the owner of the spack installation directory and everything installed by spack. The config files are in the home directory of this technical user and every sysadmin that needs to work with spack switches to the technical user via sudo.

This way we only need to maintain one set of config files.

**Comment by hartzell** [comment]
I have a variation of @alalazo's solution, my builds are scripted, the scripts live in a CI repo and the scripts starts off with variations on:

```sh
cat << EOYAML > etc/spack/mirrors.yaml
mirrors:
  local: file://some/path/to/mirror
EOYAML

cat << "EOYAML" > etc/spack/packages.yaml
packages:
  all:
    compiler: [gcc@5.4.0, gcc@4.8.5, gcc@4.8.3]
  ack:
    version: [2.16]
  ant:
    version: [1.9.9]
[...]
spack install ack
spack install ant
[...]
```
