### ISSUE TITLE
Installation issue: mbedtls

### ISSUE THREAD

**Issue by eamathw** [LLNL/spack#44587]
### Steps to reproduce the issue

Spack is unable to create a spec for mbedtls@2.24.0.

```console
$ spack spec -I mbedtls@2.24.0
==> Error: concretization failed for the following reasons:

   1. Cannot satisfy 'mbedtls@2.24.0'
   2. Cannot satisfy 'mbedtls@2.24.0'
        required because mbedtls@2.24.0 requested explicitly 

```

### Error message

<details><summary>Error message</summary>

See above.

### Information on your system

* **Spack:** 0.22.0 (5fe93fee1eec46a0750bd340198bffcb92ff9eec)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-cascadelake
* **Concretizer:** clingo

### Additional information

@haampie

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
We no longer have good error messages, but `spack spec --deprecated ...` should work. The version was deprecated over some CVE.

**Comment by eamathw** [comment]
Ah, there. Thank you.Sorry about the noise.
