### ISSUE TITLE
Help...using git and my own spack fork to create PRs

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/spack#4465]
I simply do not seem to be able to get the hang of git. I continue to have conceptual errors using it. Last time, I had to totally blow away my own fork of spack repo and start over. This time, I have a fork of develop and I have created two branches, mfem_update, which I already had a PR accepted and committed for and, adding_h5z_zfp, which I just tried to do. However, that branch seems to also include the work I did on the mfem branch on it. So, when I tried to initiate a PR, I get the changes I wanted for h5z-zfp and I get stuff I already did from mfem_update. WTF? 

I would like to be able to create branches and then PRs for work on those branches, *separately*, and I don't seem to be able to make it happen.

Finally, I think I need to sync. my local spack fork with the current develop. I've tried git pull, git fetch and they all say I am up to date. Do I need to take action, after forking on github, to ensure my fork is setup to update via pull or fetch from the main spack repo?

**Comment by adamjstewart** [comment]
> This time, I have a fork of develop and I have created two branches, mfem_update, which I already had a PR accepted and committed for and, adding_h5z_zfp, which I just tried to do. However, that branch seems to also include the work I did on the mfem branch on it. So, when I tried to initiate a PR, I get the changes I wanted for h5z-zfp and I get stuff I already did from mfem_update. WTF?

If I had to guess, you probably started on the `develop` branch, then created a `mfem_update` branch off of develop. Then you created a `adding_h5z_zfp` branch off of `mfem_update`. When you create a new branch, make sure you create that branch off of `develop`.

> Finally, I think I need to sync. my local spack fork with the current develop. I've tried git pull, git fetch and they all say I am up to date. Do I need to take action, after forking on github, to ensure my fork is setup to update via pull or fetch from the main spack repo?

It sounds to me like you are all set. Just make sure you are on the develop branch when you sync. I use these commands to sync:
```
$ git checkout develop       # make sure you are on the develop branch
$ git pull upstream develop  # update your local develop branch with respect to upstream
$ git push origin develop    # push these changes to your fork on GitHub
```

Spending a day to sit down and really learn git well will save you weeks in the long run. I would recommend [this tutorial](https://www.atlassian.com/git/tutorials). It's what I used to learn git. [Git Pro](https://git-scm.com/book/en/v2) is like the official git book, and is another good resource available for free online. If you're especially having trouble understanding branching, [this is another tutorial](http://learngitbranching.js.org/) that someone recommended to me. It provides a more graphical approach to understanding branching.

**Comment by adamjstewart** [comment]
Another thing I like to do is include the branch name in my bash prompt. See [here](https://github.com/adamjstewart/dotfiles) for screenshots. This git bash prompt script comes straight from the git developers, and adds a `+` for new untracked files and a `*` for modifications to tracked files. It helps to see what branch I am on and whether or not any files have been changed before I create a new branch or try to sync develop.

**Comment by markcmiller86** [comment]
Thanks @adamjstewart so much. It looks like I probably need to define what *upstream* is. After doing that, life is making more sense now. I just submitted the PR. Thanks again.

**Comment by aprokop** [comment]
@markcmiller86 By default, when you clone a repo, the remote is called `origin`. You can then change it to `upstream` by doing
```bash
$ git remote rename origin upstream
```

**Comment by adamjstewart** [comment]
In general, `upstream` refers to the upstream development repository, in this case https://github.com/LLNL/spack, while `origin` refers to your own fork of this repository. Of course, these are suggestions, not hard rules. You can call your remotes whatever you want, but these names are common in tutorials. See `man git-remote` for more information on adding, removing, renaming, and listing remotes.
