### ISSUE TITLE
linux-pam: c compiler cannot create executables

### ISSUE THREAD

**Issue by vsoch** [LLNL/spack#44678]
There was a change to linux-pam merged yesterday: https://github.com/spack/spack/commit/9151fc1653317059097ae51a238cbb7c05197240

That I suspect might be the cause of the bug here?

https://github.com/flux-framework/spack/actions/runs/9475771589/job/26107603047

```console
==> Error: ProcessError: Command exited with status 77:
    '/tmp/runner/spack-stage/spack-stage-linux-pam-1.5.2-vx26dqv7vwes7khuokqhvcrfivtl3olk/spack-src/configure' '--prefix=/opt/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-10.5.0/linux-pam-1.5.2-vx26dqv7vwes7khuokqhvcrfivtl3olk' '--includedir=/opt/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-10.5.0/linux-pam-1.5.2-vx26dqv7vwes7khuokqhvcrfivtl3olk/include/security'

2 errors found in build log:
     14    checking whether make supports nested variables... yes
     15    checking build system type... x86_64-pc-linux-gnu
     16    checking host system type... x86_64-pc-linux-gnu
     17    checking whether make supports the include directive... yes (GNU sty
           le)
     18    checking for gcc... /opt/spack/lib/spack/env/gcc/gcc
     19    checking whether the C compiler works... no
  >> 20    configure: error: in `/tmp/runner/spack-stage/spack-stage-linux-pam-
           1.5.2-vx26dqv7vwes7khuokqhvcrfivtl3olk/spack-src':
  >> 21    configure: error: C compiler cannot create executables
     22    See `config.log' for more details

See build log for details:
  /tmp/runner/spack-stage/spack-stage-linux-pam-1.5.2-vx26dqv7vwes7khuokqhvcrfivtl3olk/spack-build-out.txt

==> Warning: Skipping build of libpam-1.09-g6thnzh4qntsdec3rxvinpxohrzckt7p since linux-pam-1.5.2-vx26dqv7vwes7khuokqhvcrfivtl3olk failed
```
Note that the build yesterday worked (before the change): https://github.com/flux-framework/spack/actions/runs/9458637968

Ping @teaguesterling and @alecbcs that approved / merged this PR. Thanks!

**Comment by teaguesterling** [comment]
Investigating now on my end.

**Comment by teaguesterling** [comment]
I'm trying to reproduce this and am not able to from either the Bionic or Focal Ubuntu Spack image:
```console
$ echo "
> spack cd -r
> git fetch
> git switch develop
> git pull
> spack install linux-pam@1.5.2
> " | podman run -it spack/ubuntu-focal:latest
...
==> Installing linux-pam-1.5.2-s6aokh64yxyvfprmimv6bcclhicbte2x [31/31]
==> No binary for linux-pam-1.5.2-s6aokh64yxyvfprmimv6bcclhicbte2x found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/e4/e4ec7131a91da44512574268f493c6d8ca105c87091691b8e9b56ca685d4f94d.tar.xz
==> No patches needed for linux-pam
==> linux-pam: Executing phase: 'autoreconf'
==> linux-pam: Executing phase: 'configure'
==> linux-pam: Executing phase: 'build'
==> linux-pam: Executing phase: 'install'
==> linux-pam: Successfully installed linux-pam-1.5.2-s6aokh64yxyvfprmimv6bcclhicbte2x
  Stage: 0.46s.  Autoreconf: 0.00s.  Configure: 12.16s.  Build: 16.44s.  Install: 14.92s.  Post-install: 0.11s.  Total: 44.24s
[+] /opt/spack/opt/spack/linux-ubuntu20.04-zen2/gcc-9.4.0/linux-pam-1.5.2-s6aokh64yxyvfprmimv6bcclhicbte2x
```

Looking at the logs in that run, I noticed that a CentOS version of GCC was being pulled from the build cache and being used in an Ubuntu image. I'm going to try building GCC 10.5.0 (as was used in your log) in the Focal image and retry the linux-pam install to see if I can reproduce the error again.

**Comment by vsoch** [comment]
Thanks @teaguesterling ! Yes to reproduce you'll want to use focal, that's what we do here. https://github.com/flux-framework/spack/actions/runs/9475771589/workflow I'm running again without that one cache and I can report back. We can also update to jammy, which probably makes sense to do soon anyway. Let me know what you find (and if it's related to focal).

**Comment by teaguesterling** [comment]
Sadly, it doesn't seem that Focal or gcc@10.5.0 was able to reproduce it:
```console
> spack install linux-pam@1.5.2%gcc@10.5.0
...
==> Installing linux-pam-1.5.2-vyue7m7g6i6fmj7gegsndrt5yzf2xori [31/31]
==> No binary for linux-pam-1.5.2-vyue7m7g6i6fmj7gegsndrt5yzf2xori found: installing from source
==> Using cached archive: /opt/spack/var/spack/cache/_source-cache/archive/e4/e4ec7131a91da44512574268f493c6d8ca105c87091691b8e9b56ca685d4f94d.tar.xz
==> No patches needed for linux-pam
==> linux-pam: Executing phase: 'autoreconf'
==> linux-pam: Executing phase: 'configure'
==> linux-pam: Executing phase: 'build'
==> linux-pam: Executing phase: 'install'
==> linux-pam: Successfully installed linux-pam-1.5.2-vyue7m7g6i6fmj7gegsndrt5yzf2xori
  Stage: 0.07s.  Autoreconf: 0.00s.  Configure: 12.10s.  Build: 16.17s.  Install: 14.86s.  Post-install: 0.14s.  Total: 43.47s
[+] /opt/spack/opt/spack/linux-ubuntu20.04-zen3/gcc-10.5.0/linux-pam-1.5.2-vyue7m7g6i6fmj7gegsndrt5yzf2xori
```

I'm going to try installing all of the specs you have (as linux-pam is a dependency to something in there). Maybe that will help piece together what's going wrong.

**Comment by vsoch** [comment]
Yep - this was just an install of flux-security, so that's the one to try!

Clearing the cache still failed for me, unfortunately.

**Comment by teaguesterling** [comment]
I wasn't able to reproduce but ran into another issue with flux-security. Two last thoughts for now:
1) Is the gcc version being used built by spack or provided by the image?
2) You could try adding `depends_on("gettext")` to the `linux-pam` package.

**Comment by vsoch** [comment]
I updated to ubuntu 22.04 - didn't fix anything. I think the gcc is being provided by the base container. Why would adding gettetxt to the linux-pam need to be done?

**Comment by haampie** [comment]
I've submitted a revert https://github.com/spack/spack/pull/44682

**Comment by haampie** [comment]
Ah okay, gettext is a required dep of linux-pam.

... but can be disabled. updated the pr.

**Comment by teague-23andme** [comment]
I had a draft PR that added some more variants for the linux-pam package, including disabling nls. Seeing what happened, here it would have been a good idea to put some more investigation into it prior. I'll hold off on opening a PR for that to let this stabilize a bit but I'd still like to be able to reproduce this for testing purposes.

**Comment by teaguesterling** [comment]
@vsoch I assume this resolved the issue. Can we close?

**Comment by vsoch** [comment]
I think you did! Thank you!
