### ISSUE TITLE
Would anyone support logoname="CaseSensitive&OtherCharsPackageName"

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/spack#4469]
I think I understand why spack wants all the package dirs to be all lower case and no funny chars. Thats fine. Though the python code then uses uppercase for the first letter in the class name to define the package.

I would like to suggest something like `logoname` which may be optionally included with a package next to `url` and `homepage` that holds the case-senstive (and perhaps funny chars included) package name so that I can do something like...

```
    logoname="AMReX"
```

And then `spack info` would produce...

```
CMakePackage:    AMReX (amrex)
Homepage:        https://ccse.lbl.gov/AMReX/index.html
.
.
.
```

**Comment by tgamblin** [comment]
I don't see why we need to do this.

**Comment by markcmiller86** [comment]
Perhaps I mischaracterized things...I don't think this is specific to AMReX. I think there are *a lot* of packages whose names are clearer when capital letters and other chars actually used in those names as intended by package developers are printed...VisIt, ParaView, OpenMP, MACSio, NetCDF, Node.js, xSDK, PNGwriter, PostgreSQL, etc. I think it helps when spack presents package names in the typesetting the developers intended.

BTW...
```
[scratlantis:~/spack/spack] miller86% spack find AMReX
==> No package matches the query: AMReX
[scratlantis:~/spack/spack] miller86% spack find amrex
==> 3 installed packages.
-- darwin-elcapitan-x86_64 / gcc@6.1.0 --------------------------
amrex@17.06  amrex@17.06  amrex@17.06
[scratlantis:~/spack/spack] miller86% spack list AMReX
==> 1 packages.
amrex
```

**Comment by tgamblin** [comment]
It seems like to me that we should just make `spack find` case insensitive.

I *never* remember how HPC packages are capitalized (looking at you, PETSc), and I'm not sure we should bother cluttering packages just so that `spack info` shows a name that's not actually useful within Spack.  The URL is in there -- if they want the real name they can go to the website...

**Comment by tgamblin** [comment]
Or, maybe we could just move the description to the top of Spack info.  If someone wants to put the "correct" capitalization in, they can write it in the description.

e.g.:

```
Package:    petsc
Homepage:   http://www.mcs.anl.gov/petsc/index.html

[97 lines]

Description:
    PETSc is a suite of data structures and routines for the scalable
    (parallel) solution of scientific applications modeled by partial
    differential equations.
```

We could put the Description *above* the 97 lines, after homepage.

**Comment by markcmiller86** [comment]
> @tgamblin We could put the Description above the 97 lines, after homepage.

That makes sense. I am fine with that.
