### ISSUE TITLE
fenics doesn't install on Ubuntu 16

### ISSUE THREAD

**Issue by mpilosov** [LLNL/spack#4472]
Would love to get this working but I keep getting the following super ambiguous error

[repos]$ spack install fenics @2016.2.0
==> Error: 'doc'
[repos]$ spack install fenics @2016.1.0
==> Error: 'doc'
[repos]$ spack install fenics @2017.1.0
==> Error: 'doc'
[repos]$ spack install fenics @1.6.0
==> Error: 'doc'
[repos]$ spack install fenics
==> Error: 'doc'

**Comment by adamjstewart** [comment]
Can reproduce. I know what the problem is. I'll submit a PR shortly.

**Comment by mpilosov** [comment]
Wow, that was the fastest developer response I've ever received. Thank you!
