### ISSUE TITLE
Installation issue: uftrace

### ISSUE THREAD

**Issue by AcriusWinter** [LLNL/spack#44729]
### Steps to reproduce the issue

```console
$ spack install uftrace
```

### Error message

<pre>
==> uftrace: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16' 'V=1'
  >> 305    collect2: error: ld returned 1 exit status
  >> 306    collect2: error: ld returned 1 exit status
  >> 307    make: *** [Makefile:263: /tmp/lawrence31/spack-stage/spack-stage-uftrace-0.11-utrci35mrt5r4k4vbdmc2il4oqv2envn/spack-src/libmcount/libmcou
            nt-fast.so] Error 1
  >> 309    make: *** [Makefile:260: /tmp/lawrence31/spack-stage/spack-stage-uftrace-0.11-utrci35mrt5r4k4vbdmc2il4oqv2envn/spack-src/libmcount/libmcou
            nt.so] Error 1
  >> 386    collect2: error: ld returned 1 exit status
  >> 387    make: *** [Makefile:266: /tmp/lawrence31/spack-stage/spack-stage-uftrace-0.11-utrci35mrt5r4k4vbdmc2il4oqv2envn/spack-src/libmcount/libmcou
            nt-single.so] Error 1

### Information on your system

* **Spack:** 0.23.0.dev0 (6e4f8ea7e4f7207da7162306f086dc2da0c0ce83)
* **Python:** 3.9.12
* **Platform:** linux-rhel8-broadwell
* **Concretizer:** clingo

### Additional information

```
...         libelf: [ on  ] - more flexible ELF data handling
...          libdw: [ on  ] - DWARF debug info support
...      libpython: [ on  ] - python scripting support
...      libluajit: [ on  ] - luajit scripting support
...    libncursesw: [ on  ] - TUI support
...   cxa_demangle: [ on  ] - full demangler support with libstdc++
...     perf_event: [ on  ] - perf (PMU) event support
...       schedule: [ on  ] - scheduler event support
...       capstone: [ on  ] - full dynamic tracing support
...      libunwind: [ on  ] - libunwind support
```

@bernhardkaindl - maintainer

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by tldahlgren** [comment]
I still can't build the package.

**Comment by tldahlgren** [comment]
> I still can't build the package.

```
...
capstone-5
            .0.1-yteibrpp3zx3tnj65t64myadccyzik2c/lib64/libcapstone.a(Mapping.c
            .o): relocation : relocation R_X86_64_32R_X86_64_32 against  agains
            t ``.rodata.str1.8.rodata.str1.8' can not be used when making ' can
             not be used when making a shared objecta shared object; recompile 
            with -fPIC; recompile with -fPIC
...
  >> 311    : final link failed: Nonrepresentable section on output
  >> 312    collect2: error: ld returned 1 exit status
  >> 313    collect2: error: ld returned 1 exit status
```
