### ISSUE TITLE
mesa w/ ROCm 6.1: missing llvm-config; unable to check llvm-config --has-rtti and other settings; llvm-config was present in ROCm 5.7

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#44745]
### Steps to reproduce the issue

`mesa@23.3.6` build fails using:
* spack@develop (641075539c0a888d4378bd7dfdb19a872c5c42de from `Mon Jun 3 14:37:51 2024 -0700`)
* ROCm 6.1.1 installed via apt, externally defined via `packages:` config
* Ubuntu 22.04, X86_64

We are hitting this as we try to build `ecp-data-vis-sdk +rocm +paraview +vtkm ...` with ROCm 6.

We don't see this error using an external install of ROCm 5.7. There, `llvm-config` is present:
* `/opt/rocm-5.7.1/llvm/bin/llvm-config`

Can we get this back @renjithravindrankannath @srekolam @haampie ? CC @kwryankrattiger 

Spack environment: [spack.yaml.txt](https://github.com/user-attachments/files/15874470/spack.yaml.txt)

<details><summary>Concretization</summary>

<pre>
 -   mesa@23.3.6%gcc@11.4.0+glx+llvm+opengl~opengles+osmesa~strip build_system=meson buildtype=release default_library=shared arch=linux-ubuntu22.04-x86_64_v3
[+]      ^bison@3.8.2%gcc@11.4.0~color build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^diffutils@3.10%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^gmake@4.4.1%gcc@11.4.0~guile build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]          ^m4@1.4.19%gcc@11.4.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-ubuntu22.04-x86_64_v3
[+]              ^libsigsegv@2.14%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]      ^cmake@3.29.4%gcc@11.4.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-ubuntu22.04-x86_64_v3
[+]          ^curl@8.7.1%gcc@11.4.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-ubuntu22.04-x86_64_v3
[+]              ^nghttp2@1.62.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^ncurses@6.5%gcc@11.4.0~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-ubuntu22.04-x86_64_v3
[+]      ^expat@2.6.2%gcc@11.4.0+libbsd build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^libbsd@0.12.2%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]              ^libmd@1.0.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]      ^flex@2.6.3%gcc@11.4.0+lex~nls build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^findutils@4.9.0%gcc@11.4.0 build_system=autotools patches=440b954 arch=linux-ubuntu22.04-x86_64_v3
[+]      ^gcc-runtime@11.4.0%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]      ^gettext@0.22.5%gcc@11.4.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^bzip2@1.0.8%gcc@11.4.0~debug~pic+shared build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]          ^tar@1.34%gcc@11.4.0 build_system=autotools zip=pigz arch=linux-ubuntu22.04-x86_64_v3
[+]              ^pigz@2.8%gcc@11.4.0 build_system=makefile arch=linux-ubuntu22.04-x86_64_v3
[+]              ^zstd@1.5.6%gcc@11.4.0+programs build_system=makefile compression=none libs=shared,static arch=linux-ubuntu22.04-x86_64_v3
[+]          ^xz@5.4.6%gcc@11.4.0~pic build_system=autotools libs=shared,static arch=linux-ubuntu22.04-x86_64_v3
[e]      ^glibc@2.35%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]      ^glproto@1.4.17%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^util-macros@1.20.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]      ^libunwind@1.6.2%gcc@11.4.0~block_signals~conservative_checks~cxx_exceptions~debug~debug_frame+docs~pic+tests+weak_backtrace~xz~zlib build_system=autotools components=none libs=shared,static arch=linux-ubuntu22.04-x86_64_v3
[+]      ^libx11@1.8.7%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^inputproto@2.3.2%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^kbproto@1.0.7%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^perl@5.38.2%gcc@11.4.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-ubuntu22.04-x86_64_v3
[+]              ^berkeley-db@18.1.40%gcc@11.4.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu22.04-x86_64_v3
[+]          ^xextproto@7.3.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^xproto@7.0.31%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^xtrans@1.5.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]      ^libxcb@1.17.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^libpthread-stubs@0.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^libxau@1.0.11%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^libxdmcp@1.1.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^xcb-proto@1.17.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]      ^libxext@1.3.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]      ^libxml2@2.10.3%gcc@11.4.0+pic~python+shared build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]      ^libxt@1.3.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^libice@1.1.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^libsm@1.2.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[e]      ^llvm-amdgpu@6.1.1%gcc@11.4.0~link_llvm_dylib~llvm_dylib+rocm-device-libs build_system=cmake build_type=Release generator=ninja patches=b4774ca arch=linux-ubuntu22.04-x86_64_v3
[+]      ^meson@1.3.2%gcc@11.4.0 build_system=python_pip patches=0f0b1bd arch=linux-ubuntu22.04-x86_64_v3
[+]          ^py-pip@23.1.2%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]          ^py-setuptools@69.2.0%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]          ^py-wheel@0.41.2%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]          ^python-venv@1.0%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]      ^ninja@1.12.0%gcc@11.4.0+re2c build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]          ^re2c@2.2%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]      ^pkgconf@2.2.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]      ^py-mako@1.2.4%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]          ^py-markupsafe@2.1.3%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]      ^python@3.11.9%gcc@11.4.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=13fa8bf,b0615b2,ebdca64,f2fd060 arch=linux-ubuntu22.04-x86_64_v3
[+]          ^gdbm@1.23%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^libffi@3.4.6%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^libxcrypt@4.4.35%gcc@11.4.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-ubuntu22.04-x86_64_v3
[+]          ^openssl@3.3.0%gcc@11.4.0~docs+shared build_system=generic certs=mozilla arch=linux-ubuntu22.04-x86_64_v3
[+]              ^ca-certificates-mozilla@2023-05-30%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]          ^readline@8.2%gcc@11.4.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu22.04-x86_64_v3
[+]          ^sqlite@3.43.2%gcc@11.4.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^util-linux-uuid@2.40.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]      ^xrandr@1.5.2%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^libxrandr@1.5.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]              ^renderproto@0.11.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^libxrender@0.9.11%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^randrproto@1.5.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]      ^zlib-ng@2.1.6%gcc@11.4.0+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
</pre>
</details>

Error:
```
$> spack -e . install /mklh
...
==> Installing mesa-23.3.6-mklhip5h4ffkqttohattg4dhj63fn3gf [61/61]
==> No binary for mesa-23.3.6-mklhip5h4ffkqttohattg4dhj63fn3gf found: installing from source
==> Using cached archive: /spack/var/spack/cache/_source-cache/archive/cd/cd3d6c60121dea73abbae99d399dc2facaecde1a8c6bd647e6d85410ff4b577b.tar.xz
==> Ran patch() for mesa
==> mesa: Executing phase: 'meson'
==> Error: ProcessError: /opt/rocm-6.1.1/llvm/bin/llvm-config: No such file or directory
    Command: '/opt/rocm-6.1.1/llvm/bin/llvm-config' '--has-rtti'
See build log for details:
  /tmp/root/spack-stage/spack-stage-mesa-23.3.6-mklhip5h4ffkqttohattg4dhj63fn3gf/spack-build-out.txt
```

### Error message

<details><summary>Error message</summary>

<pre>
... see above
</pre></details>

### Information on your system

* **Spack:** 0.23.0.dev0 (136308c8fdc3d3d0593d563103f34e60ab15a5d6)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-cascadelake
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/user-attachments/files/15874467/spack-build-env.txt)
[spack-build-out.txt](https://github.com/user-attachments/files/15874468/spack-build-out.txt)

@v-dobrev 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by renjithravindrankannath** [comment]
From 6.1 llvm-config is available in the package rocm-llvm-dev. Please do `apt-get install rocm-llvm-dev`

**Comment by eugeneswalker** [comment]
> From 6.1 llvm-config is available in the package rocm-llvm-dev. Please do `apt-get install rocm-llvm-dev`

Thank you @renjithravindrankannath !

For installation by `amdgpu-install` method, which use case includes rocm-llvm-dev? Do you know? In my case, I installed ROCm like this:
```
amdgpu-install -y --usecase=rocm,rocmdev,hip,hiplibsdk,mllib,mlsdk --rocmrelease=6.1.1 --no-dkms
```

Even installing with `rocmdev` it did not install `rocm-llvm-dev` for me. What is the correct use case to get this installed as part of amdgpu-install method?

**Comment by renjithravindrankannath** [comment]
Below the steps to install rocm-llvm-dev on Ubuntu 22.04
```
wget https://repo.radeon.com/amdgpu-install/6.1/ubuntu/jammy/amdgpu-install_6.1.60100-1_all.deb
apt install ./amdgpu-install_6.1.60100-1_all.deb
sudo apt update
apt install  rocm-llvm-dev
```
Reference: https://rocm.docs.amd.com/projects/install-on-linux/en/docs-6.1.0/tutorial/quick-start.html

**Comment by eugeneswalker** [comment]
`apt install rocm-llvm-dev6.1.1` works but, is there not a way to get this installed as part of amdgpu-install script? The linked documentation does not say anything about rocm-llvm-dev as far as I can see...
