### ISSUE TITLE
Installation issue: ffmpeg patch checksum changed

### ISSUE THREAD

**Issue by teaguesterling** [LLNL/spack#44773]
### Steps to reproduce the issue

```console
$ spack stage ffmepg@6.0
```

FYI @xjrc

### Error message

<details><summary>Error message</summary>

<pre>
$ spack stage ffmpeg@6.0
==> Fetching https://mirror.spack.io/_source-cache/archive/47/47d062731c9f66a78380e35a19aac77cebceccd1c7cc309b9c82343ffc430c3d.tar.bz2
==> Fetching https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff_plain/effadce6c756247ea8bae32dc13bb3e6f464f0eb
==> Fetching https://git.ffmpeg.org/gitweb/ffmpeg.git/commitdiff_plain/f01fdedb69e4accb1d1555106d8f682ff1f1ddc7
==> Error: sha256 checksum failed for /tmp/teague/spack-stage/spack-stage-patch-416751f41cfbf086c28b4bbf01ace4c08e5651e59911dca6240292bb1b5c6b53/f01fdedb69e4accb1d1555106d8f682ff1f1ddc7
Expected 416751f41cfbf086c28b4bbf01ace4c08e5651e59911dca6240292bb1b5c6b53 but got 673813d13f5c37b75ff5bcb56790ccd6b16962fdb9bddcbbeeead979d47d31b3. File size = 8260 bytes. Contents = b"From: Frank Plow...atting('float',\n"

</pre></details>

### Information on your system

* **Spack:** 0.23.0.dev0 (c2835265dd0a4310f2c694186bca628bb59041c2)
* **Python:** 3.10.12
* **Platform:** linux-pop22-zen3
* **Concretizer:** clingo

### Additional information

Build logs not applicable.

Patch in question: 
[f01fdedb69e4accb1d1555106d8f682ff1f1ddc7.patch.txt](https://github.com/user-attachments/files/15903456/f01fdedb69e4accb1d1555106d8f682ff1f1ddc7.patch.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by klin938** [comment]
Having the same issur for 6.1.1:

```
~$ spack stage ffmpeg@6.1.1
==> Error: sha256 checksum failed for /tmp/dice/spack-stage/spack-stage-patch-856bdc2b6e2a7066cf683a235193b9025d4d73dd7686eda2fbcf83e7e65f8bf9/fef22c87ada4
Expected 856bdc2b6e2a7066cf683a235193b9025d4d73dd7686eda2fbcf83e7e65f8bf9 but got 5726e8e999e3fc7a5ae4c4c846c9151246e5846c54dc3b8ff8326ee31c59631a. File size = 5124 bytes. Contents = b'From: Jan Ekstr\xc3... could be used:\n'
```

**Comment by jmurugan-fzj** [comment]
@teaguesterling Is this issue already resolved? Could you please let me know the specific Spack version in which it has been fixed?

**Comment by teaguesterling** [comment]
I'd forgotten about this. I'll check and close if it's now irrelevant.

**Comment by jmurugan-fzj** [comment]
@teaguesterling Thank you for the response. It seems that the issue is still reproducible in Spack version v22.0. Since the issue appears to be closed, I was hoping for confirmation regarding which specific version contains the fix. Could you provide more details on the fixed version or resolution?
