### ISSUE TITLE
Spack on Gentoo prefix

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#44782]
### Steps to reproduce

When using Spack on gentoo prefix there are various issues.

Using cvmfs w/ soft.computecanada.ca:

```
sudo docker run --rm \
    -e CVMFS_CLIENT_PROFILE=single \
    -e CVMFS_REPOSITORIES=soft.computecanada.ca \
    --privileged \
    --cap-add SYS_ADMIN \
    --device /dev/fuse \
    --volume /cvmfs:/cvmfs:shared \
    registry.cern.ch/cvmfs/service:latest
```

I found:

- `python@:3.11` adds explicit `-I/usr/include/...` headers, so the compiler takes the wrong libc headers, breaking the build of the `ssl` module and others (which isn't an error, but should be...)
- Spack built `cmake` will not search `lib64` subdirs, so `find_library(MATH_LIB NAMES m)` fails to locate `libm.so`. I have to pass `-DCMAKE_FIND_LIBRARY_CUSTOM_LIB_SUFFIX=64` to make it work. Submitted a fix here: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9614
- `rpath`s are registered to default search paths like `/cvmfs/soft.computecanada.ca/gentoo/2023/x86-64-v3/usr/lib64` in CMake packages, since CMakePackage directly calls `get_rpaths` which is not return spack managed paths before externals. This is separate from #40848

**Comment by haampie** [comment]
fyi @Chrismarsh

**Comment by Chrismarsh** [comment]
@haampie I'm wondering where you are with this -- have these changes been fully merged into develop now?

**Comment by haampie** [comment]
I think the majority of the issues is fixed. What remains is specific package issues.

1. For `-rpath`, `-L` and `-I` flags, we've gone from ordering as [not system path | system path] to [spack path | not spack path]: so this part does not rely on a hard-coded list of /usr, /usr/local system paths anymore.
2. We no longer add rpaths to directories that are default search paths of the dynamic linker.
3. `CMakePackage` install rpath logic was fixed
4. `cmake` 3.31.0 contains my fix https://gitlab.kitware.com/cmake/cmake/-/commit/05b4883bfefa77312b44d028b19469fe51ff92c7

We still have a few places in Spack though where `is_system_path(...)` is used, which continues to be wrong on gentoo prefix, but I think it's minor.
