### ISSUE TITLE
Possibility for external mismatch (internal)

### ISSUE THREAD

**Issue by scheibelp** [LLNL/spack#44828]
(NOTE: this is a potential issue that I noticed by looking at the code as part of another effort, I do not have a reproducer)

### Steps to reproduce

`SpackSolverSetup.external_packages`: any concretization that filters any externals inside this function may run into this problem:

* This function generates the full set of externals, then applies a filtering step to remove some
* Later in the function, externals in the generated ASP are mapped to indices based on enumerating the filtered set
* Later, in `SpecBuilder.external_spec_selected`, this index is used to retrieve the external, but it is based on the unfiltered set of externals, which would appear to create an offset error

I think the end result would be that concretizations have the potential to silently match up the wrong externals.

@alalazo this filtering was added in https://github.com/spack/spack/commit/4e876b4014cccf477dce155159198a5dc9c0730b and https://github.com/spack/spack/commit/c7cf5eabc1fc7fae57719d294de21b418854124d

I noticed this as part of https://github.com/spack/spack/pull/44810, but I'm not sure the timeline for fixing this should align with that PR.

### Error message

(no error message)

### Information on your system

(this is for all systems, latest Spack as of today: [57b83e5](https://github.com/spack/spack/commit/57b83e5fb29ae3c84cf81eb0ed89c83e49dd3217))

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by rbberger** [comment]
I'm noticing a strange new error during mirror creation that happens on `develop` when I have `git` as one of the root specs in an environment and define it as external.

Usually this turns into
```bash
# when creating a mirror for the environment:
Skipping git@2.31.1%gcc@12.2.1+man+nls+perl+subtree~svn+tcltk build_system=autotools arch=linux-rhel8-zen3/4p3djc3 as it is an external spec.
# or when installing
[+] /usr (external git-2.31.1-4p3djc3oqv3a3erx5467cle34qi4mb7r)
```
But occasionally this happens:
```
==> Error: git-2.31.1-4p3djc3oqv3a3erx5467cle34qi4mb7r cannot be installed locally: is external
[+] /usr/tce/packages/git/git-2.31.1 (external git-2.31.1-4p3djc3oqv3a3erx5467cle34qi4mb7r)
```
Could this be related?

**Comment by scheibelp** [comment]
@rbberger that error seems more like https://github.com/spack/spack/issues/44533, but only that message is coming up as part of installing a package that depends on git; there might be a possibility for that error to combine with this (in particular if you weren't expecting any of the packages you were installing to depend on git)
