### ISSUE TITLE
kokkos@4.3.01 +rocm build fails w/ ROCm 6.1: CMake: Could not find a package configuration file provided by "rocthrust"

### ISSUE THREAD

**Issue by eugeneswalker** [LLNL/spack#44832]
### Steps to reproduce the issue

`kokkos@4.3.01 +rocm` fails to build using:
* spack@develop (58db81c3233b5a0fd81f555b6152f1e00d336f65 from `Thu Jun 20 12:39:58 2024 -0400`)
* Ubuntu 22.04, AMD64
* GCC 11.4.0

Spack environment: [spack.yaml.txt](https://github.com/user-attachments/files/15948859/spack.yaml.txt)

<details><summary>Concretization</summary>

<pre>
 -   kokkos@4.3.01%gcc@11.4.0~aggressive_vectorization~compiler_warnings~cuda~debug~debug_bounds_check~debug_dualview_modify_check~deprecated_code~examples~hpx~hpx_async_dispatch~hwloc~ipo~memkind~numactl~openmp~openmptarget~pic+rocm+serial+shared~sycl~tests~threads~tuning~wrapper amdgpu_target=gfx90a build_system=cmake build_type=Release cxxstd=17 generator=make intel_gpu_arch=none arch=linux-ubuntu22.04-x86_64_v3
[+]      ^cmake@3.29.4%gcc@11.4.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-ubuntu22.04-x86_64_v3
[+]          ^curl@8.7.1%gcc@11.4.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-ubuntu22.04-x86_64_v3
[+]              ^nghttp2@1.62.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^diffutils@3.10%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]              ^openssl@3.3.0%gcc@11.4.0~docs+shared build_system=generic certs=mozilla arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^ca-certificates-mozilla@2023-05-30%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]          ^ncurses@6.5%gcc@11.4.0~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-ubuntu22.04-x86_64_v3
[+]          ^zlib-ng@2.1.6%gcc@11.4.0+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]      ^gcc-runtime@11.4.0%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[e]      ^glibc@2.35%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]      ^gmake@4.4.1%gcc@11.4.0~guile build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]      ^hip@6.1.1%gcc@11.4.0~cuda~ipo+rocm build_system=cmake build_type=Release generator=make patches=1f65dfe,6bbe83b arch=linux-ubuntu22.04-x86_64_v3
[+]          ^comgr@6.1.1%gcc@11.4.0~asan~ipo build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-x86_64_v3
[+]              ^rocm-cmake@6.1.1%gcc@11.4.0~ipo build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-x86_64_v3
[+]          ^glx@1.4%gcc@11.4.0 build_system=bundle arch=linux-ubuntu22.04-x86_64_v3
[+]              ^mesa@23.3.6%gcc@11.4.0+glx+llvm+opengl~opengles+osmesa~strip build_system=meson buildtype=release default_library=shared arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^bison@3.8.2%gcc@11.4.0~color build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^flex@2.6.3%gcc@11.4.0+lex~nls build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^glproto@1.4.17%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^util-macros@1.20.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^libunwind@1.6.2%gcc@11.4.0~block_signals~conservative_checks~cxx_exceptions~debug~debug_frame+docs+pic+tests+weak_backtrace+xz~zlib build_system=autotools components=none libs=shared,static arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^libx11@1.8.9%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^inputproto@2.3.2%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^kbproto@1.0.7%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^xextproto@7.3.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^xproto@7.0.31%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^xtrans@1.5.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^libxcb@1.17.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^libxau@1.0.11%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^libxdmcp@1.1.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^xcb-proto@1.17.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^libxext@1.3.6%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^libxml2@2.10.3%gcc@11.4.0+pic~python+shared build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^libxt@1.3.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^libice@1.1.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^libsm@1.2.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^llvm@17.0.6%gcc@11.4.0+clang~cuda~flang+gold~ipo+libomptarget~libomptarget_debug~link_llvm_dylib+lld+lldb+llvm_dylib+lua~mlir+polly~python~split_dwarf~z3~zstd build_system=cmake build_type=Release compiler-rt=runtime generator=ninja libcxx=runtime libunwind=runtime openmp=runtime shlib_symbol_version=none targets=all version_suffix=none arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^binutils@2.42%gcc@11.4.0~gas+gold~gprofng+headers~interwork+ld+libiberty~lto~nls~pgo+plugins build_system=autotools compress_debug_sections=zlib libs=shared,static arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^hwloc@2.9.3%gcc@11.4.0~cairo~cuda~gl~libudev+libxml2~netloc~nvml~oneapi-level-zero~opencl+pci~rocm build_system=autotools libs=shared,static arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^lua@5.3.6%gcc@11.4.0~pcfile+shared build_system=makefile fetcher=curl arch=linux-ubuntu22.04-x86_64_v3
[+]                          ^unzip@6.0%gcc@11.4.0 build_system=makefile patches=f6f6236 arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^perl-data-dumper@2.173%gcc@11.4.0 build_system=perl arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^swig@4.1.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                          ^pcre2@10.43%gcc@11.4.0~jit+multibyte build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^meson@1.3.2%gcc@11.4.0 build_system=python_pip patches=0f0b1bd arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^py-mako@1.2.4%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^py-markupsafe@2.1.3%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^xrandr@1.5.2%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^libxrandr@1.5.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                          ^renderproto@0.11.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^libxrender@0.9.11%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^randrproto@1.5.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^hipcc@6.1.1%gcc@11.4.0~ipo build_system=cmake build_type=Release generator=make patches=f9d4d87 arch=linux-ubuntu22.04-x86_64_v3
[+]          ^hipify-clang@6.1.1%gcc@11.4.0~asan~ipo build_system=cmake build_type=Release generator=make patches=3ad49b7 arch=linux-ubuntu22.04-x86_64_v3
[+]          ^hsakmt-roct@6.1.1%gcc@11.4.0~asan~ipo+shared build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-x86_64_v3
[+]              ^libdrm@2.4.120%gcc@11.4.0~docs build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^libpciaccess@0.17%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^libpthread-stubs@0.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^libedit@3.1-20230828%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^numactl@2.0.14%gcc@11.4.0 build_system=autotools patches=4e1d78c,62fc8a8,ff37630 arch=linux-ubuntu22.04-x86_64_v3
[+]              ^autoconf@2.72%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]              ^automake@1.16.5%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]              ^libtool@2.4.7%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^findutils@4.9.0%gcc@11.4.0 build_system=autotools patches=440b954 arch=linux-ubuntu22.04-x86_64_v3
[+]              ^m4@1.4.19%gcc@11.4.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^libsigsegv@2.14%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^perl@5.38.2%gcc@11.4.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-ubuntu22.04-x86_64_v3
[+]              ^berkeley-db@18.1.40%gcc@11.4.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-ubuntu22.04-x86_64_v3
[+]              ^bzip2@1.0.8%gcc@11.4.0~debug~pic+shared build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]              ^gdbm@1.23%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^perl-file-which@1.27%gcc@11.4.0 build_system=perl arch=linux-ubuntu22.04-x86_64_v3
[+]          ^perl-uri-encode@1.1.1%gcc@11.4.0 build_system=perl arch=linux-ubuntu22.04-x86_64_v3
[+]              ^perl-module-build@0.4234%gcc@11.4.0 build_system=perl arch=linux-ubuntu22.04-x86_64_v3
[+]          ^py-cppheaderparser@2.7.4%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]              ^py-pip@23.1.2%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]              ^py-ply@3.11%gcc@11.4.0 build_system=python_pip arch=linux-ubuntu22.04-x86_64_v3
[+]              ^py-setuptools@69.2.0%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]              ^py-wheel@0.41.2%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]              ^python-venv@1.0%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]          ^rocm-core@6.1.1%gcc@11.4.0~ipo build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-x86_64_v3
[+]          ^rocminfo@6.1.1%gcc@11.4.0~ipo build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-x86_64_v3
[+]          ^roctracer-dev-api@6.1.1%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]      ^hsa-rocr-dev@6.1.1%gcc@11.4.0~asan+image~ipo+shared build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-x86_64_v3
[+]          ^elfutils@0.191%gcc@11.4.0~debuginfod+exeprefix~nls build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]              ^xz@5.4.6%gcc@11.4.0+pic build_system=autotools libs=shared,static arch=linux-ubuntu22.04-x86_64_v3
[+]              ^zstd@1.5.6%gcc@11.4.0+programs build_system=makefile compression=none libs=shared,static arch=linux-ubuntu22.04-x86_64_v3
[+]          ^pkgconf@2.2.0%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^xxd-standalone@8.2.1201%gcc@11.4.0 build_system=makefile arch=linux-ubuntu22.04-x86_64_v3
[+]      ^llvm-amdgpu@6.1.1%gcc@11.4.0~ipo~link_llvm_dylib~llvm_dylib+rocm-device-libs build_system=cmake build_type=Release generator=ninja patches=b4774ca arch=linux-ubuntu22.04-x86_64_v3
[+]          ^ninja@1.12.0%gcc@11.4.0+re2c build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]              ^re2c@2.2%gcc@11.4.0 build_system=generic arch=linux-ubuntu22.04-x86_64_v3
[+]          ^python@3.11.9%gcc@11.4.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=13fa8bf,b0615b2,ebdca64,f2fd060 arch=linux-ubuntu22.04-x86_64_v3
[+]              ^expat@2.6.2%gcc@11.4.0+libbsd build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^libbsd@0.12.2%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^libmd@1.0.4%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]              ^gettext@0.22.5%gcc@11.4.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]                  ^tar@1.34%gcc@11.4.0 build_system=autotools zip=pigz arch=linux-ubuntu22.04-x86_64_v3
[+]                      ^pigz@2.8%gcc@11.4.0 build_system=makefile arch=linux-ubuntu22.04-x86_64_v3
[+]              ^libffi@3.4.4%gcc@11.4.0 build_system=autotools patches=070b1f3 arch=linux-ubuntu22.04-x86_64_v3
[+]              ^libxcrypt@4.4.35%gcc@11.4.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-ubuntu22.04-x86_64_v3
[+]              ^readline@8.2%gcc@11.4.0 build_system=autotools patches=bbf97f1 arch=linux-ubuntu22.04-x86_64_v3
[+]              ^sqlite@3.43.2%gcc@11.4.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]              ^util-linux-uuid@2.40.1%gcc@11.4.0 build_system=autotools arch=linux-ubuntu22.04-x86_64_v3
[+]          ^z3@4.12.4%gcc@11.4.0~gmp~ipo~python build_system=cmake build_type=Release generator=make arch=linux-ubuntu22.04-x86_64_v3
</pre></details>

Error:
```
$> spack -e . install /ujjc
...
==> Installing kokkos-4.3.01-ujjc3aufcg56lzih54gkqo66mslja7uy [90/90]
==> No binary for kokkos-4.3.01-ujjc3aufcg56lzih54gkqo66mslja7uy found: installing from source
==> Fetching https://github.com/kokkos/kokkos/archive/4.3.01.tar.gz
==> No patches needed for kokkos
==> kokkos: Executing phase: 'cmake'
==> Error: ProcessError: Command exited with status 1:
...
1 error found in build log:
     17    --     Host Parallel: NoTypeDefined
     18    --       Host Serial: SERIAL
     19    --
     20    -- Architectures:
     21    --  VEGA90A
     22    -- Found TPLLIBDL: /usr/include
  >> 23    CMake Error at cmake/Modules/FindTPLROCTHRUST.cmake:11 (FIND_PACKAGE):
     24      By not providing "Findrocthrust.cmake" in CMAKE_MODULE_PATH this project
     25      has asked CMake to find a package configuration file provided by
     26      "rocthrust", but CMake did not find one.
     27
     28      Could not find a package configuration file provided by "rocthrust" with
     29      any of the following names:
```

### Error message

<details><summary>Error message</summary>

<pre>
... see above
</pre></details>

### Information on your system

* **Spack:** 0.23.0.dev0 (1650b3d371003494467bb0fc9159fdaf5ba4d3c6)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-cascadelake
* **Concretizer:** clingo

### Additional information

[spack-build-env.txt](https://github.com/user-attachments/files/15948856/spack-build-env.txt)
[spack-build-out.txt](https://github.com/user-attachments/files/15948857/spack-build-out.txt)

@cedricchevalier19 @lucbv @nmm0

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by lucbv** [comment]
Hm, we should give you a better error message than this, that's true. Will improve that once back from travel.

**Comment by srekolam** [comment]
i think https://github.com/spack/spack/pull/44459 should fix it

**Comment by eugeneswalker** [comment]
> i think #44459 should fix it

Yes, it does! Thank you!

**Comment by eugeneswalker** [comment]
Closing as this is fixed by:
* https://github.com/spack/spack/pull/44459
