### ISSUE TITLE
Testing issue: hypre-cmake

### ISSUE THREAD

**Issue by AcriusWinter** [LLNL/spack#44845]
### Steps to reproduce the failure(s) or link(s) to test output(s)

```console
$ spack test run hypre-cmake
```

### Error message

<details><summary>Error message</summary>

<pre>
1 error found in test log:
     52    
     53    ex5big.c(539): warning #181: argument of type "HYPRE_Int={int}" is incompatible with format "%lld", expecting argument of type "long long"
     54               printf("Iterations = %lld\n", num_iterations);
     55                                             ^
     56    
     57    ld: cannot find -lHYPRE
  >> 58    make: *** [Makefile:116: ex5big] Error 1
     59    
     60      File "/spack/bin/spack", line 52, in <module>
</pre></details>

### Information on your system or the test runner

* **Spack:** 0.23.0.dev0 (27e28b33eecbf1f47bca2675340dbaeb669827e5)
* **Python:** 3.9.12
* **Platform:** linux-rhel8-broadwell
* **Concretizer:** clingo

### Additional information
```
===================== SUMMARY: hypre-cmake-2.22.0-6y5p64f ======================
HypreCmake::test_make_hyprecmake2.22.06y5p64ft4ipfu7m2i7gzdl3oxb6q6lb3_bigint .. FAILED
HypreCmake::test_ex5big .. SKIPPED
HypreCmake::test_ex15big .. SKIPPED
HypreCmake::test .. FAILED
======================== 2 failed, 2 skipped of 4 parts ========================
==> [2024-06-24-13:24:27.719047]
```
### General information

- [X] I have reported the version of Spack/Python/Platform/Runner
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded any available logs
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by tldahlgren** [comment]
@AcriusWinter Please add the build information for the package(s).

**Comment by tldahlgren** [comment]
> @AcriusWinter Please add the build information for the package(s).

Rather, please add the command line used to install the package.

**Comment by AcriusWinter** [comment]
Tried again with:
```
$ spack install hypre-cmake +mpi
```
Recreate:
```
$spack test run hypre-cmake
```
Test log:
```
===================== SUMMARY: hypre-cmake-2.22.0-6y5p64f ======================
HypreCmake::test_make_hyprecmake2.22.06y5p64ft4ipfu7m2i7gzdl3oxb6q6lb3_bigint .. FAILED
HypreCmake::test_ex5big .. SKIPPED
HypreCmake::test_ex15big .. SKIPPED
HypreCmake::test .. FAILED
======================== 2 failed, 2 skipped of 4 parts ========================
==> [2024-06-24-14:16:48.349379] 
...
1 error found in test log:
     52    
     53    ex5big.c(539): warning #181: argument of type "HYPRE_Int={int}" is incompatible with format "%lld", expecting argument of type "long long"
     54               printf("Iterations = %lld\n", num_iterations);
     55                                             ^
     56    
     57    ld: cannot find -lHYPRE
  >> 58    make: *** [Makefile:116: ex5big] Error 1
     59    
     60      File "/spack/bin/spack", line 52, in <module>
```

**Comment by tldahlgren** [comment]
This issue is not reproduced as of https://github.com/spack/spack/pull/45144.
