### ISSUE TITLE
Testing issue: strumpack

### ISSUE THREAD

**Issue by AcriusWinter** [LLNL/spack#44848]
### Steps to reproduce the failure(s) or link(s) to test output(s)

```console
$ spack test run strumpack

```

### Error message

<details><summary>Error message</summary>

<pre>
        232        # TODO: Remove/replace once self.spec['cmake'] is available here
        233        cmake_bin = self.cmake_bin(set=False)
        234
  >>    235        opts = self.std_cmake_args
        236        opts += self.cmake_args()
        237        opts += ["."]
        238

</pre></details>

### Information on your system or the test runner

* **Spack:** 0.23.0.dev0 (27e28b33eecbf1f47bca2675340dbaeb669827e5)
* **Python:** 3.9.12
* **Platform:** linux-rhel8-broadwell
* **Concretizer:** clingo

### Additional information
```
======================= SUMMARY: strumpack-7.2.0-ck6btof =======================
Strumpack::test .. FAILED
============================= 1 failed of 1 parts ==============================
==> [2024-06-24-16:14:51.989947]

See test results at:
/.spack/test/gscrja4vk4bpfkymzhrl3rwxrctvaehu/strumpack-7.2.0-ck6btof-test-out.txt
Test failure: TestFailure: 1 test failed.


'Strumpack' object has no attribute 'std_cmake_args'

/spack/var/spack/repos/builtin/packages/strumpack/package.py:235, in _test_example:
        232        # TODO: Remove/replace once self.spec['cmake'] is available here
        233        cmake_bin = self.cmake_bin(set=False)
        234
^[[0;91m  >>    235        opts = self.std_cmake_args^[[0m
        236        opts += self.cmake_args()
        237        opts += ["."]
        238
```

### General information

- [X] I have reported the version of Spack/Python/Platform/Runner
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded any available logs
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by tldahlgren** [comment]
The problem is that the property moved to the builder.
