### ISSUE TITLE
Remove use of `std_cmake_args` from builtin repo

### ISSUE THREAD

**Issue by haampie** [LLNL/spack#44857]
`std_cmake_args` used to be a pretty static list of arguments, but by now it is dynamic and expensive to compute correctly. I'd like to get rid of it and ensure CMAKE_INSTALL_RPATH argument is computed correctly in one place only.

- [x] `apcomp`, `dray` depend on https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9623 #45015 
- [x] `cutlang` #44853
- [x] `libbison` #44852 
- [x] `eztrace` #44855 
- [x] `glog` #44858 
- [x] `jasper` #44859 
- [x] `kallisto` #44862
- [x] `mpifileutils` #44863
- [x] `oce` #44864
- [x] `mongo-c-driver` #44866
- [x] `memaxes` #44869
- [x] `opennurbs` #44871

**Comment by tgamblin** [comment]
I like it. Once you're done with this we should make this an audit and deprecate the global so that folks with private repos are sufficiently warned.

**Comment by haampie** [comment]
This is done, including:

* std_cmake_args
* std_meson_args
* std_pip_args

All of which are currently discouraged from returning through audits:

* #44895
* #47259
* #47320
