### ISSUE TITLE
spack find is case sensitive

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/spack#4493]
```
[scratlantis:mfem/mfem-3.3/examples] miller86% spack find MFEM
==> No package matches the query: MFEM
[scratlantis:mfem/mfem-3.3/examples] miller86% spack find mfem
==> 1 installed packages.
-- darwin-elcapitan-x86_64 / gcc@6.1.0 --------------------------
mfem@3.3
```
This is happening on an OSX system. Not sure if correct behavior elsewhere.

**Comment by tgamblin** [comment]
So the issue here is that specs themselves are case sensitive.  Should they not be?

We've made all the mainline packages lowercase, so it doesn't matter for mainline spack, but someone may still be using mixed-case packages.

**Comment by tgamblin** [comment]
I do agree this is inconsistent with how `spack list` works... I'm not sure how we'd implement this correctly at the command level -- we'd need to rewrite the query specs to look like what is installed.  That, or make specs case insensitive.

**Comment by markcmiller86** [comment]
Didn't know spec's *were* case sensitive. So, a spec includes many things like package name, variants, etc. Those parts are already case *IN*sensitive, right? Whats left? I mean, what parts of a spec are case sensitive if package names and variants are not?

**Comment by markcmiller86** [comment]
> @tgamblin I do agree this is inconsistent with how spack list works...

By "spack list" here, do you mean queries on the packages available vs. queries on the packages installed? Because other operations, like `spack info` are also *not* case sensitive.

**Comment by tgamblin** [comment]
@markcmiller86 

> So, a spec includes many things like package name, variants, etc. Those parts are already case INsensitive, right? Whats left? I mean, what parts of a spec are case sensitive if package names and variants are not?

They're actually implemented as case SENSITIVE, but we lowercased all the package names and variant names because remembering capitalization drives people nuts.  But the implementation would support uppercase if you made a package with an uppercase name or variant.

**Comment by tgamblin** [comment]
> By "spack list" here, do you mean queries on the packages available vs. queries on the packages installed? Because other operations, like spack info are also not case sensitive.

Yep.  The difference between these is that `spack find` operates on `Spec` objects, and it relies on methods like `satisfies()` to figure out if there's a match.  `spack list` and `spack info` take package names, which we just compare as strings.  It's easy to lowercase those because the command does the comparison.

**Comment by markcmiller86** [comment]
Ok, well, to be honest, this isn't a big deal to me. I mean, now that I understand some of the idosyncracies, I can just work with them. It just seemed odd that spack seemed to *prefer* case **IN**sensitivity in package names and variants (at least from current practice) but then seems to be inconsistent about how it handles case in some commands. In a perfect world, I guess I would opt for always lower-case for everything (package names, python package class names, package dir names, variant names, etc., etc.)

**Comment by adamjstewart** [comment]
> I guess I would opt for always lower-case for everything (package names, python package class names, package dir names, variant names, etc., etc.)

* package names: all are already lowercase
* python package class names: this would make our modules no longer [PEP 8](https://www.python.org/dev/peps/pep-0008/) compliant. Users don't need to know or use these class names ever anyway.
* package dir names: all are already lowercase, and have to match the package name
* variant names: most are lowercase, but there are a few (e.g. `+X`) that still need to be converted

Regardless of which command you use, you should always use lowercase package names. One of the things I hate about Fedora's package manager (dnf) is that I never know whether or not a package is called `lmod` or `Lmod` (hint: it's the latter). With Spack, every package name is always lowercase. No ifs, ands, or buts.

**Comment by markcmiller86** [comment]
> @adamjstewart ... With Spack, every package name is always lowercase. No ifs, ands, or buts.

Fair enough.
