### ISSUE TITLE
Testing/examples issue: umpire: shared libraries not loading when run examples

### ISSUE THREAD

**Issue by tldahlgren** [LLNL/spack#44960]
### Steps to reproduce the failure(s) or link(s) to test output(s)

```console
$ spack install umpire+examples
$ spack load umpire   # Or the hash of the above installation
$ strategy_example
strategy_example: error while loading shared libraries: libumpire.so: cannot open shared object file: No such file or directory
```

### Error message

<details><summary>Error message</summary>

Attempts to run all 29 of the examples result in the same error:

<pre>
error while loading shared libraries: libumpire.so: cannot open shared object file: No such file or directory</pre></details>

### Information on your system or the test runner

* **Spack:** 0.23.0.dev0 (728d7ef9f751ae51c13c481da4b0fa879e17c691)
* **Python:** 3.9.12
* **Platform:** linux-rhel8-broadwell
* **Concretizer:** clingo

### Additional information

This issue is affecting the ability to run stand-alone tests for at least the latest package.

### General information

- [X] I have reported the version of Spack/Python/Platform/Runner
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded any available logs
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
Looks like `CMAKE_INSTALL_RPATH` is not used.

Is `CachedCMakePackage` broken in Spack?
