### ISSUE TITLE
Installation issue: recent update on libint is buggy

### ISSUE THREAD

**Issue by ningli-amd** [LLNL/spack#45028]
### Steps to reproduce the issue

```console
$ spack install libint@2.6.0  # with any compiler
...
```

### Error message

No error message

### Information on your system

* **Spack:** 0.23.0.dev0 (f47c307bf4121ee09859321b9350aa43cab70a4e)
* **Python:** 3.9.18
* **Platform:** linux-rocky9-zen4
* **Concretizer:** clingo

### Additional information

@dev-zero @snehring

The recent recipe updates in https://github.com/spack/spack/pull/44776 are buggy, at least for `libint@2.6.0`. Installation appears to be completed and successful. However, the installed `lib/pkgconfig/libint2.pc` file has empty paths. Here is what I got:
```
prefix=
exec_prefix=
libdir=
includedir=

Name:
Description: a library for the evaluation of molecular integrals of many-body operators over Gaussian functions
Version:
Libs: -L${libdir} -lint2
Cflags: -I${includedir} -I${includedir}/libint2
```
As a result, `cp2k` build with this version of `libint` will fail because `cp2k` recipe is accessing the pkgconfig info  (see https://github.com/spack/spack/blob/5262412c13f49266e4a45a3ef450934531b47592/var/spack/repos/builtin/packages/cp2k/package.py#L495) incorrect flags `-I -I/libint2` would be injected into cp2k's build system.

It appears that the CMake logic in `libint@2.6.0` is either incomplete or otherwise not implemented correctly. Before applying the PR https://github.com/spack/spack/pull/44776 `libint2.pc` would be correctly generated by autotools.  

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by snehring** [comment]
Looks like their cmake process isn't populating the variables in the template for the pkgconf file. In this specific case it'd probably make sense to modify the cp2k package to instead of calling pkgconf to use `spec["libint"].headers.cpp_flags`. I can also probably add a fix_pkconfig_file function to add the missing paths into the pc file.

**Comment by ningli-amd** [comment]
You mean adding a function in the libint recipe to modify the generated .pc file before installations? That would be my preferred solution. libint is being used by applications other than cp2k. It would be easier to fix the problem once from its source.

**Comment by snehring** [comment]
Hmm. 2.6.0 doesn't seem to be generating shared libs either. I'm going to make a case for 2.6.0 that restores the old behavior. The pc file seems to be generated correctly in 2.9.0.  @ningli-amd other than 2.6.0 being broken for cp2k at the moment, does 2.9.0 work as expected with that package?

**Comment by ningli-amd** [comment]
> @ningli-amd other than 2.6.0 being broken for cp2k at the moment, does 2.9.0 work as expected with that package?

Yes, 2.9.0 works as expected.

**Comment by snehring** [comment]
@ningli-amd give #45034 a try

**Comment by ningli-amd** [comment]
I can confirm that https://github.com/spack/spack/pull/45034 has fixed the reported problem. Thanks!
