### ISSUE TITLE
Concretizer outputs excessive info in mixed systems

### ISSUE THREAD

**Issue by rbberger** [LLNL/spack#45030]
Using a shared spack instance to compile both `x86_64` and `aarch64` packages, leads to excessive `info: tuple ignored:` messages during concretization.

```
.../spack/lib/spack/spack/solver/concretize.lp:1640:5-11: info: tuple ignored:                                                               
  #sup@2                                     
                                                                                               
.../spack/lib/spack/spack/solver/concretize.lp:1604:5-11: info: tuple ignored:                                                               
  #sup@205             
                                                                                               
.../spack/lib/spack/spack/solver/concretize.lp:1604:5-11: info: tuple ignored:                                                               
  #sup@205
```

**Steps to reproduce:**
- Clone current `develop` on a shared filesystem
- System A (e.g. `linux-sles15-neoverse_v2`):
   * do `spack spec -I zlib`, does a clean concretization, no messages.
- System B (e.g. `linux-sles15-sapphirerappids`):
  * install `zlib` for `x86_64`, `spack install zlib`
- System A:
  * do `spack spec -I zlib` again; this produces `info: tuple ignored` messages for each installed `x86_64` dependency. Uninstalling zlib and its dependencies one by one removes the messages in the same manner.

@alalazo FYI

**Comment by alalazo** [comment]
@rbberger Can you confirm #45269 solves this?

**Comment by ax3l** [comment]
Fixed for me, too :tada:
