### ISSUE TITLE
oce built with spack missing TKCAF

### ISSUE THREAD

**Issue by iulian787** [LLNL/spack#4508]
The default oce, built on my laptop or desktop (ubuntu 14.04), is missing some libraries, like
TKCAF; 

I logged on  issue on oce repo too, I was wondering if anyone knows what options I could change to have TKCAF built?

https://github.com/tpaviot/oce/issues/669

**Comment by scheibelp** [comment]
It looks like you figured out the required option to build TKCAF at https://github.com/tpaviot/oce/issues/669#issuecomment-308578574. Specifically, this is controlled by `-DOCE_DISABLE_X11:BOOL=ON` and in the Spack `oce` package with the `+X11` variant. If that does not resolve the issue for you feel free to reopen.
