### ISSUE TITLE
Installation issue: intel-onapi-dpct@2024.2.0 hash failure

### ISSUE THREAD

**Issue by G-Ragghianti** [LLNL/spack#45099]
### Steps to reproduce the issue

```console
spack stage intel-oneapi-dpct
==> Fetching https://registrationcenter-download.intel.com/akdlm/IRC_NAS/6b83dabd-75cf-4371-b4cd-91160175d5ff/l_dpcpp-ct_p_2024.2.0.424_offline.sh
==> Error: sha256 checksum failed for /tmp/gragghia/spack-stage/spack-stage-intel-oneapi-dpct-2024.2.0-gja2elwobv5n5ec7slehzyzggzzrbb6o/l_dpcpp-ct_p_2024.2.0.424_offline.sh
Expected 84e4dfba142c3c629424012ad5e8e5f78d2a05983bf03cdc7e3ec6b530142d0e but got 43a6c5fa646291ea4f8ee94e2e711ee42bbd6aff7901bda1694e1ea99e6852e2. File size = 95700739 bytes. Contents = b'#!/bin/sh\n# shel...\x9f?\xfe|\xc1?\xff\x1fM\xea\x1e\xec\x00h\xb3\x07'
```

### Error message

```
==> Error: sha256 checksum failed for /tmp/gragghia/spack-stage/spack-stage-intel-oneapi-dpct-2024.2.0-gja2elwobv5n5ec7slehzyzggzzrbb6o/l_dpcpp-ct_p_2024.2.0.424_offline.sh
Expected 84e4dfba142c3c629424012ad5e8e5f78d2a05983bf03cdc7e3ec6b530142d0e but got 43a6c5fa646291ea4f8ee94e2e711ee42bbd6aff7901bda1694e1ea99e6852e2. File size = 95700739 bytes. Contents = b'#!/bin/sh\n# shel...\x9f?\xfe|\xc1?\xff\x1fM\xea\x1e\xec\x00h\xb3\x07'
```

### Information on your system

* **Spack:** 0.23.0.dev0 (297874bfed27caedf32d93bba550206729ba353e)
* **Python:** 3.9.18
* **Platform:** linux-rocky9-skylake_avx512
* **Concretizer:** clingo

### Additional information

I would have submitted a PR with the "correct" hash, but I guess we should make sure that intel intended for the hash to change?

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by wdconinc** [comment]
Fixed by #45100.
