### ISSUE TITLE
Testing issue: rccl

### ISSUE THREAD

**Issue by AcriusWinter** [LLNL/spack#45117]
### Steps to reproduce the failure(s) or link(s) to test output(s)

```console
$ spack spec test run rccl
...
```

### Error message

<details><summary>Error message</summary>

<pre>
...
==> Spack test mchvqwla3sficr54yckacrzlkzq6yj4u
==> Testing package rccl-6.1.1-5k4jec4
==> Error: TestFailure: 1 test failed.

Failed to find executable 'UnitTests'

See test log for details:
  /g/g16/.spack/test/mchvqwla3sficr54yckacrzlkzq6yj4u/rccl-6.1.1-5k4jec4-test-out.txt

============================== 1 failed of 1 spec ==============================

==> Error: 1 test(s) in the suite failed.
</pre></details>

### Information on your system or the test runner

* **Spack:** 0.23.0.dev0 (a04b12a3ef1ba0e31c6a43332920a596b8b0660e)
* **Python:** 3.9.12
* **Platform:** linux-rhel8-broadwell
* **Concretizer:** clingo

### General information

- [X] I have reported the version of Spack/Python/Platform/Runner
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded any available logs
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by afzpatel** [comment]
Created PR https://github.com/spack/spack/pull/45240 to address this issue.

**Comment by afzpatel** [comment]
https://github.com/spack/spack/pull/45240 is now merged
