### ISSUE TITLE
Testing issue: py-amrex

### ISSUE THREAD

**Issue by AcriusWinter** [LLNL/spack#45115]
### Steps to reproduce the failure(s) or link(s) to test output(s)

```console
$ spack test run py-amrex
...
```

### Error message

<details><summary>Error message</summary>

<pre>
...
==> Testing package py-amrex-24.04-gglidsd
==> Error: TestFailure: 1 test failed.

'NoneType' object is not callable

1 error found in test log:
  >> 5    FAILED: PyAmrex::test: 'NoneType' object is not callable
     6      File "/usr/WS2/spack/bin/spack", line 52, in <module>

See test log for details:
  /g/g16/.spack/test/5rfcgwqmuqimrc2txrnty344b36p57jm/py-amrex-24.04-gglidsd-test-out.txt

============================== 1 failed of 1 spec ==============================

See py-amrex-24.04-gglidsd test results at:
  /g/g16/.spack/test/5rfcgwqmuqimrc2txrnty344b36p57jm/py-amrex-24.04-gglidsd-test-out.txt
==> Error: 1 test(s) in the suite failed.
</pre></details>

### Information on your system or the test runner

* **Spack:** 0.23.0.dev0 (a04b12a3ef1ba0e31c6a43332920a596b8b0660e)
* **Python:** 3.9.12
* **Platform:** linux-rhel8-broadwell
* **Concretizer:** clingo

### General information

- [X] I have reported the version of Spack/Python/Platform/Runner
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded any available logs
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by tldahlgren** [comment]
This is not the error that arises from the `develop` version of `py-amrex`.
