### ISSUE TITLE
Testing issue: raja

### ISSUE THREAD

**Issue by AcriusWinter** [LLNL/spack#45116]
### Steps to reproduce the failure(s) or link(s) to test output(s)

```console
$ spack test run raja
...
```

### Error message

<details><summary>Error message</summary>

<pre>
...
==> Testing package raja-2024.02.2-g7s32uv
==> Error: TestFailure: 1 test failed.

'Raja' object has no attribute 'build_dirname'

/usr/WS2/spack/var/spack/repos/builtin/packages/raja/package.py:449, in _test_examples:
        446                installed=False,
        447                purpose=reason,
        448                skip_missing=True,
  >>    449                work_dir=self._extra_tests_path,
        450            )

============================== 1 failed of 1 spec ==============================

See raja-2024.02.2-g7s32uv test results at:
  /g/g16/.spack/test/wtmhdsdkkqrku33phww5kqqhls6hntj6/raja-2024.02.2-g7s32uv-test-out.txt
==> Error: 1 test(s) in the suite failed.
</pre></details>

### Information on your system or the test runner

* **Spack:** 0.23.0.dev0 (a04b12a3ef1ba0e31c6a43332920a596b8b0660e)
* **Python:** 3.9.12
* **Platform:** linux-rhel8-broadwell
* **Concretizer:** clingo

### General information

- [X] I have reported the version of Spack/Python/Platform/Runner
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded any available logs
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by tldahlgren** [comment]
This issue was resolved in https://github.com/spack/spack/pull/45184.
