### ISSUE TITLE
Testing issue: sz

### ISSUE THREAD

**Issue by AcriusWinter** [LLNL/spack#45120]
### Steps to reproduce the failure(s) or link(s) to test output(s)

```console
$ spack test run sz
...
```

### Error message

<details><summary>Error message</summary>

<pre>
...
==> [2024-07-08-15:11:58.701082] Completed testing
==> [2024-07-08-15:11:58.701211] 
========================= SUMMARY: sz-2.1.12.5-yzdbaqe =========================
Sz::test_sz_z_f_i_testfloat_8_8_128.dat_M_REL_R_1E3_2_8_1024 .. FAILED
Sz::test_sz_x_f_i_testfloat_8_8_128.dat_s_testfloat_8_8_128.dat.sz_2_8_1024_a .. FAILED
Sz::test_sz_z_f_i_testfloat_8_8_128.dat_M_REL_R_1E3_3_8_8_128 .. FAILED
Sz::test_sz_x_f_i_testfloat_8_8_128.dat_s_testfloat_8_8_128.dat.sz_3_8_8_128_a .. FAILED
Sz::test .. FAILED
============================= 5 failed of 5 parts ==============================
==> [2024-07-08-15:11:58.701261] 

See test results at:
  /g/g16/lawrence31/.spack/test/7lech4aytx2lfstyvo2yhshydwkn5ci5/sz-2.1.12.5-yzdbaqe-test-out.txt
Test failure: TestFailure: 4 tests failed.

Executable 'sz' expected in prefix, found in /usr/bin/sz instead

Executable 'sz' expected in prefix, found in /usr/bin/sz instead

Executable 'sz' expected in prefix, found in /usr/bin/sz instead

Executable 'sz' expected in prefix, found in /usr/bin/sz instead
</pre></details>

### Information on your system or the test runner

* **Spack:** 0.23.0.dev0 (a04b12a3ef1ba0e31c6a43332920a596b8b0660e)
* **Python:** 3.9.12
* **Platform:** linux-rhel8-broadwell
* **Concretizer:** clingo

### General information

- [X] I have reported the version of Spack/Python/Platform/Runner
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded any available logs
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by tldahlgren** [comment]
The failures here don't match the tests from #45363 plus the tests pass (or skip) as expected for me.
