### ISSUE TITLE
Request To Add Kokkos-tools to spack package list

### ISSUE THREAD

**Issue by dhope-lab** [LLNL/spack#45149]
### Summary

Would be appreciated if kokkos-tools can be added to spack’ list of packages. 

### Description

Installing kokkos-tools separate of spack defeats the purpose of using spack. Not to mention installing separate of spack can lead to unintentional conflicting dependencies being installed. 

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by wdconinc** [comment]
I'm tagging @lucbv who may have this on the Kokkos roadmap already (or have good reasons for why it isn't there yet).

The fastest path to the addition of new packages remains users contributions, however. Writing most new package recipes is not complicated at all, and largely automated. It starts with (in your case):
```console
spack create https://github.com/kokkos/kokkos-tools/archive/refs/tags/2.5.00.tar.gz
```
More details in out [packaging guide](https://spack.readthedocs.io/en/latest/packaging_guide.html).
