### ISSUE TITLE
Bootstrap always tries to write to the default install tree root path in activated Spack environment

### ISSUE THREAD

**Issue by cpearse** [LLNL/spack#45247]
### Steps to reproduce

If we activate a Spack environment with an existing `spack.yaml` that has both a defined `config` `install_tree` `root` in a personal location writable to the user and an `upstream` section:

```
spacktivate -p spack-environment
```

Any command involving the bootstrap, i.e.:

```
spack spec
```

or

```
spack install
```

will fail as below:

### Error message

```
==> Error: [Errno 13] Permission denied: '/path/to/extracted/tarball/of/spack/release/opt'
```

Full debug output:

[spec-debug.txt](https://github.com/user-attachments/files/16249293/spec-debug.txt)

`spack.yaml` file:

[spack-yaml.txt](https://github.com/user-attachments/files/16249330/spack-yaml.txt)

### Information on your system

```
* **Spack:** 0.22.0
* **Python:** 3.9.18
* **Platform:** linux-rocky9-cascadelake
* **Concretizer:** clingo
```

We are refactoring our cluster around Spack and aim to offer Spack itself via an environment module. We download and extract a tarball release to a shared location, then set the permissions to read-only for all users. The module then sources `setup-env.sh` when you load it. This works well in normal `spack` usage when you pass `-C /path/to/personal/configs` to any command.

The `spack.yaml` file for the environment above contains all relevant sections of a personal config scope, particularly both a defined `config` `install_tree` `root` in a personal location writable to the user and an `upstream` section, but it still seems to want to see if it can write to `$spack/opt`. I would have thought that the `config` `install_tree` `root`  section of `spack.yaml` would override this.

I spoke to @alalazo on Slack and was advised to raise this issue. It was suggested I include this:

```
$ spack bootstrap root
/homedir/.spack/bootstrap
```

So, a writable path in my own home directory. I can get the `spec` command to run if I give it a personal config scope:

```
$ spack -d -C /path/to/personal/configs spec
```

But I was hoping to not need to do this as all those files (`config.yaml` etc.) are already integrated into each relevant section (`config` etc.) in `spack.yaml` for the environment. 

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by cpearse** [comment]
OK, an update.

I decided to try this again with a local clone of Spack from GitHub to a location that is r/w for me. When I activate the Spack env from the same YAML, then run `spack spec` without a config scope, it works, and I noticed it creates the following directory inside the cloned version of Spack:

```
opt/spack/.spack-db/failures
```

The `failures` directory is empty. So, with a bit of lateral thinking I created the same directory in the read-only version of Spack we have for the environment module version, i.e.:

```
/path/to/extracted/tarball/of/spack/release/opt/spack/.spack-db/failures
```

With that directory present (even if empty and read-only), all Spack commands in the activated env like `spack spec` and `spack install` work without issue.

I couldn't see anything in the docs about defining a `failures` directory in any of the config YAML files/environment stanzas. So is there something in the bootstrap Python that always needs to check for `opt/spack/.spack-db/failures` in the default path and creates it if missing?

**Comment by alalazo** [comment]
Thanks for the additional info. Very helpful. I confirm that using this simple environment:
```yaml
spack:
  specs: []
  view: true
  concretizer:
    unify: true
  config:
    install_tree:
      root: ./store
```
we indeed create:
```console
$ tree -a opt
opt
└── spack
    └── .spack-db
        └── failures

3 directories, 0 files
```
in the _default_ store location too.

**Comment by alalazo** [comment]
> So is there something in the bootstrap Python that always needs to check for opt/spack/.spack-db/failures in the default path and creates it if missing?

No, it's definitely a bug on our side when using a custom install tree root. Checking that right now.

**Comment by alalazo** [comment]
This should fix it:
```diff
diff --git a/lib/spack/spack/store.py b/lib/spack/spack/store.py
index dc2d5de54b..0ee39b56cb 100644
--- a/lib/spack/spack/store.py
+++ b/lib/spack/spack/store.py
@@ -371,10 +371,10 @@ def use_store(
         data.update(extra_data)
 
     # Swap the store with the one just constructed and return it
-    ensure_singleton_created()
     spack.config.CONFIG.push_scope(
         spack.config.InternalConfigScope(name=scope_name, data={"config": {"install_tree": data}})
     )
+    ensure_singleton_created()
     temporary_store = create(configuration=spack.config.CONFIG)
     original_store, STORE = STORE, temporary_store
```
I wish we could get rid of using globals for configuration someday :disappointed: I'll write a unit test and submit a PR.

EDIT: turns out this operation should just be removed, not swapped with config modifications

**Comment by alalazo** [comment]
@cpearse Can you confirm that #45268 fixes your issue?
