### ISSUE TITLE
spack require GitHub account and password

### ISSUE THREAD

**Issue by xiongshiyun** [LLNL/spack#4525]
Dear spack developers and users,

recently I am trying to install a software using spack to install a software (https://github.com/votca/csg/wiki/Installing#spack), when downloading the packages from GitHub, it asks me to give the GitHub account and password containing the source code. I am wondering if anyone knows what is the problem and how to solve it?

Thank you very much!
With best regards,
Shiyun

**Comment by davydden** [comment]
```
git clone https://github.com/llnl/spack.git
```
shall not ask for any password. Can you copy-paste the terminal commands you are doing and the output, preferably from a fresh start?

**Comment by adamjstewart** [comment]
@junghans

**Comment by junghans** [comment]
Yeah, I haven't seen this issue before either, especially because `https://github.com/...` is usally working anonymously.

**Comment by xiongshiyun** [comment]
Dear Davydden and Junghans,

Thank you very much for your help. 
git clone https://github.com/llnl/spack has no problem. But after downloaded the spack, I used the spack to install votca by the command:
spack install votca-csg@develop votca-tools@develop
During this step, it asked me GitHub account and passphase when cloning the votca-csg source. The full output is attached.
Thanks a lot
With best regards,
Shiyun
[spack_out.txt](https://github.com/LLNL/spack/files/1082525/spack_out.txt)

**Comment by aprokop** [comment]
The URL in Spack's votca-csg is wrong. It uses the correct `https://github.com/votca/csg/tarball/v1.4` for the tarball, but a wrong one `https://github.com/csg/tools` for version. Because that repository does not exist, github asks for password (probably, assuming that's a private one).

Just need to fix an URL.

**Comment by junghans** [comment]
Thanks @aprokop !

**Comment by xiongshiyun** [comment]
Thanks a lot for the help!
