### ISSUE TITLE
Installation issue: hipify-clang (can't find cassert)

### ISSUE THREAD

**Issue by teaguesterling** [LLNL/spack#45345]
### Steps to reproduce the issue

```console
$ spack spec -I hipify-clang
Input spec
--------------------------------
 -   hipify-clang

Concretized
--------------------------------
 -   hipify-clang@6.1.2%gcc@14.1.0~asan~ipo build_system=cmake build_type=Release generator=make patches=3ad49b7 arch=linux-pop22-zen3
[+]      ^cmake@3.29.6%gcc@11.4.0~doc+ncurses+ownlibs build_system=generic build_type=Release patches=dbc3892 arch=linux-pop22-zen3
[+]          ^curl@8.7.1%gcc@11.4.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-pop22-zen3
[+]              ^nghttp2@1.62.0%gcc@11.4.0 build_system=autotools arch=linux-pop22-zen3
[+]                  ^diffutils@3.10%gcc@11.4.0 build_system=autotools arch=linux-pop22-zen3
[+]              ^openssl@3.3.1%gcc@11.4.0~docs+shared build_system=generic certs=mozilla arch=linux-pop22-zen3
[+]                  ^ca-certificates-mozilla@2023-05-30%gcc@11.4.0 build_system=generic arch=linux-pop22-zen3
[+]              ^perl@5.38.2%gcc@11.4.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-pop22-zen3
[+]                  ^berkeley-db@18.1.40%gcc@11.4.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-pop22-zen3
[+]          ^gcc-runtime@11.4.0%gcc@11.4.0 build_system=generic arch=linux-pop22-zen3
[e]          ^glibc@2.35%gcc@11.4.0 build_system=autotools arch=linux-pop22-zen3
[+]          ^ncurses@6.5%gcc@11.4.0~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-pop22-zen3
[+]          ^zlib-ng@2.2.1%gcc@11.4.0+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-pop22-zen3
[+]      ^gcc-runtime@14.1.0%gcc@14.1.0 build_system=generic arch=linux-pop22-zen3
[e]      ^glibc@2.35%gcc@14.1.0 build_system=autotools arch=linux-pop22-zen3
[+]      ^gmake@4.4.1%gcc@11.4.0~guile build_system=generic arch=linux-pop22-zen3
[+]      ^llvm-amdgpu@6.1.2%gcc@11.4.0~ipo~link_llvm_dylib+llvm_dylib+rocm-device-libs build_system=cmake build_type=Release generator=ninja patches=b4774ca arch=linux-pop22-zen3
[+]          ^ninja@1.12.0%gcc@11.4.0+re2c build_system=generic arch=linux-pop22-zen3
[+]              ^re2c@3.0%gcc@11.4.0 build_system=generic arch=linux-pop22-zen3
[+]          ^pkgconf@2.2.0%gcc@11.4.0 build_system=autotools arch=linux-pop22-zen3
[+]          ^python@3.11.9%gcc@11.4.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=13fa8bf,b0615b2,ebdca64,f2fd060 arch=linux-pop22-zen3
[+]              ^bzip2@1.0.8%gcc@11.4.0~debug~pic+shared build_system=generic arch=linux-pop22-zen3
[+]              ^expat@2.6.2%gcc@11.4.0+libbsd build_system=autotools arch=linux-pop22-zen3
[+]                  ^libbsd@0.12.2%gcc@11.4.0 build_system=autotools arch=linux-pop22-zen3
[+]                      ^libmd@1.0.4%gcc@11.4.0 build_system=autotools arch=linux-pop22-zen3
[+]              ^gdbm@1.23%gcc@11.4.0 build_system=autotools arch=linux-pop22-zen3
[+]              ^gettext@0.22.5%gcc@11.4.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-pop22-zen3
[+]                  ^libiconv@1.17%gcc@11.4.0 build_system=autotools libs=shared,static arch=linux-pop22-zen3
[+]                  ^libxml2@2.10.3%gcc@11.4.0+pic~python+shared build_system=autotools arch=linux-pop22-zen3
[+]                  ^tar@1.34%gcc@11.4.0 build_system=autotools zip=pigz arch=linux-pop22-zen3
[+]                      ^pigz@2.8%gcc@11.4.0 build_system=makefile arch=linux-pop22-zen3
[+]                      ^zstd@1.5.6%gcc@11.4.0+programs build_system=makefile compression=none libs=shared,static arch=linux-pop22-zen3
[+]              ^libffi@3.4.6%gcc@11.4.0 build_system=autotools arch=linux-pop22-zen3
[+]              ^libxcrypt@4.4.35%gcc@11.4.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-pop22-zen3
[+]              ^readline@8.2%gcc@11.4.0 build_system=autotools patches=bbf97f1 arch=linux-pop22-zen3
[+]              ^sqlite@3.43.2%gcc@11.4.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-pop22-zen3
[+]              ^util-linux-uuid@2.40.2%gcc@11.4.0 build_system=autotools arch=linux-pop22-zen3
[+]              ^xz@5.4.6%gcc@11.4.0~pic build_system=autotools libs=shared,static arch=linux-pop22-zen3
[+]          ^z3@4.12.4%gcc@11.4.0~gmp~ipo~python build_system=cmake build_type=Release generator=make arch=linux-pop22-zen3
[+]      ^rocm-core@6.1.2%gcc@14.1.0~ipo build_system=cmake build_type=Release generator=make arch=linux-pop22-zen3
[+]          ^cmake@3.29.6%gcc@14.1.0~doc+ncurses+ownlibs build_system=generic build_type=Release patches=dbc3892 arch=linux-pop22-zen3
[+]              ^curl@8.7.1%gcc@14.1.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-pop22-zen3
[+]                  ^nghttp2@1.62.0%gcc@14.1.0 build_system=autotools arch=linux-pop22-zen3
[-]                      ^diffutils@3.10%gcc@14.1.0 build_system=autotools arch=linux-pop22-zen3
[+]                          ^libiconv@1.17%gcc@14.1.0 build_system=autotools libs=shared,static arch=linux-pop22-zen3
[+]                  ^openssl@3.3.0%gcc@14.1.0~docs+shared build_system=generic certs=mozilla arch=linux-pop22-zen3
[-]                      ^ca-certificates-mozilla@2023-05-30%gcc@14.1.0 build_system=generic arch=linux-pop22-zen3
[+]                  ^perl@5.38.2%gcc@14.1.0+cpanm+opcode+open+shared+threads build_system=generic arch=linux-pop22-zen3
[+]                      ^berkeley-db@18.1.40%gcc@14.1.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-pop22-zen3
[+]                      ^bzip2@1.0.8%gcc@14.1.0~debug~pic+shared build_system=generic arch=linux-pop22-zen3
[+]                      ^gdbm@1.23%gcc@14.1.0 build_system=autotools arch=linux-pop22-zen3
[+]                          ^readline@8.2%gcc@14.1.0 build_system=autotools patches=bbf97f1 arch=linux-pop22-zen3
[+]                  ^pkgconf@2.2.0%gcc@14.1.0 build_system=autotools arch=linux-pop22-zen3
[+]              ^ncurses@6.5%gcc@14.1.0~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-pop22-zen3
[+]              ^zlib@1.3.1%gcc@14.1.0+optimize+pic+shared build_system=makefile arch=linux-pop22-zen3
[+]          ^gmake@4.4.1%gcc@14.1.0~guile build_system=generic arch=linux-pop22-zen3

```
FYI: @renjithravindrankannath  @srekolam (and @haampie for llvm-amdgpu)

### Error message

<details><summary>Error message</summary>

<pre>
Error: ProcessError: Command exited with status 2:
    'make' '-j16'

21 errors found in build log:
     77     /home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/llvm-amdgpu-6.1.2-hzp2
            6dybttascrfy6agox33jxw5wendk/bin/clang++  -I/home/teague/System/apps/spack/opt/spack/linux-
            pop22-zen3/gcc-11.4.0/llvm-amdgpu-6.1.2-hzp26dybttascrfy6agox33jxw5wendk/include -isystem /
            home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/zlib-ng-2.2.1-ok5p4onfd
            4zhb7vywf34ygy3gogaweue/include -std=c++17 -pthread -fno-rtti -fvisibility-inlines-hidden  
            -DLIB_CLANG_RES=17  -O3 -DNDEBUG   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_M
            ACROS -D__STDC_LIMIT_MACROS  -fno-exceptions -funwind-tables -MD -MT CMakeFiles/hipify-clan
            g.dir/src/CUDA2HIP_DNN_API_types.cpp.o -MF CMakeFiles/hipify-clang.dir/src/CUDA2HIP_DNN_API
            _types.cpp.o.d -o CMakeFiles/hipify-clang.dir/src/CUDA2HIP_DNN_API_types.cpp.o -c /tmp/teag
            ue/spack-stage/spack-stage-hipify-clang-6.1.2-mr4sznarz5o3xg6tppkiihnywbjaxcoo/spack-src/sr
            c/CUDA2HIP_DNN_API_types.cpp
     78     [ 43%] Building CXX object CMakeFiles/hipify-clang.dir/src/CUDA2HIP_Device_types.cpp.o
     79     /home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/llvm-amdgpu-6.1.2-hzp2
            6dybttascrfy6agox33jxw5wendk/bin/clang++  -I/home/teague/System/apps/spack/opt/spack/linux-
            pop22-zen3/gcc-11.4.0/llvm-amdgpu-6.1.2-hzp26dybttascrfy6agox33jxw5wendk/include -isystem /
            home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/zlib-ng-2.2.1-ok5p4onfd
            4zhb7vywf34ygy3gogaweue/include -std=c++17 -pthread -fno-rtti -fvisibility-inlines-hidden  
            -DLIB_CLANG_RES=17  -O3 -DNDEBUG   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_M
            ACROS -D__STDC_LIMIT_MACROS  -fno-exceptions -funwind-tables -MD -MT CMakeFiles/hipify-clan
            g.dir/src/CUDA2HIP_Device_functions.cpp.o -MF CMakeFiles/hipify-clang.dir/src/CUDA2HIP_Devi
            ce_functions.cpp.o.d -o CMakeFiles/hipify-clang.dir/src/CUDA2HIP_Device_functions.cpp.o -c 
            /tmp/teague/spack-stage/spack-stage-hipify-clang-6.1.2-mr4sznarz5o3xg6tppkiihnywbjaxcoo/spa
            ck-src/src/CUDA2HIP_Device_functions.cpp
     80     /home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/llvm-amdgpu-6.1.2-hzp2
            6dybttascrfy6agox33jxw5wendk/bin/clang++  -I/home/teague/System/apps/spack/opt/spack/linux-
            pop22-zen3/gcc-11.4.0/llvm-amdgpu-6.1.2-hzp26dybttascrfy6agox33jxw5wendk/include -isystem /
            home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/zlib-ng-2.2.1-ok5p4onfd
            4zhb7vywf34ygy3gogaweue/include -std=c++17 -pthread -fno-rtti -fvisibility-inlines-hidden  
            -DLIB_CLANG_RES=17  -O3 -DNDEBUG   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_M
            ACROS -D__STDC_LIMIT_MACROS  -fno-exceptions -funwind-tables -MD -MT CMakeFiles/hipify-clan
            g.dir/src/CUDA2HIP_Doc.cpp.o -MF CMakeFiles/hipify-clang.dir/src/CUDA2HIP_Doc.cpp.o.d -o CM
            akeFiles/hipify-clang.dir/src/CUDA2HIP_Doc.cpp.o -c /tmp/teague/spack-stage/spack-stage-hip
            ify-clang-6.1.2-mr4sznarz5o3xg6tppkiihnywbjaxcoo/spack-src/src/CUDA2HIP_Doc.cpp
     81     /home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/llvm-amdgpu-6.1.2-hzp2
            6dybttascrfy6agox33jxw5wendk/bin/clang++  -I/home/teague/System/apps/spack/opt/spack/linux-
            pop22-zen3/gcc-11.4.0/llvm-amdgpu-6.1.2-hzp26dybttascrfy6agox33jxw5wendk/include -isystem /
            home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/zlib-ng-2.2.1-ok5p4onfd
            4zhb7vywf34ygy3gogaweue/include -std=c++17 -pthread -fno-rtti -fvisibility-inlines-hidden  
            -DLIB_CLANG_RES=17  -O3 -DNDEBUG   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_M
            ACROS -D__STDC_LIMIT_MACROS  -fno-exceptions -funwind-tables -MD -MT CMakeFiles/hipify-clan
            g.dir/src/CUDA2HIP_Driver_API_functions.cpp.o -MF CMakeFiles/hipify-clang.dir/src/CUDA2HIP_
            Driver_API_functions.cpp.o.d -o CMakeFiles/hipify-clang.dir/src/CUDA2HIP_Driver_API_functio
            ns.cpp.o -c /tmp/teague/spack-stage/spack-stage-hipify-clang-6.1.2-mr4sznarz5o3xg6tppkiihny
            wbjaxcoo/spack-src/src/CUDA2HIP_Driver_API_functions.cpp
     82     /home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/llvm-amdgpu-6.1.2-hzp2
            6dybttascrfy6agox33jxw5wendk/bin/clang++  -I/home/teague/System/apps/spack/opt/spack/linux-
            pop22-zen3/gcc-11.4.0/llvm-amdgpu-6.1.2-hzp26dybttascrfy6agox33jxw5wendk/include -isystem /
            home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/zlib-ng-2.2.1-ok5p4onfd
            4zhb7vywf34ygy3gogaweue/include -std=c++17 -pthread -fno-rtti -fvisibility-inlines-hidden  
            -DLIB_CLANG_RES=17  -O3 -DNDEBUG   -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_M
            ACROS -D__STDC_LIMIT_MACROS  -fno-exceptions -funwind-tables -MD -MT CMakeFiles/hipify-clan
            g.dir/src/CUDA2HIP_Device_types.cpp.o -MF CMakeFiles/hipify-clang.dir/src/CUDA2HIP_Device_t
            ypes.cpp.o.d -o CMakeFiles/hipify-clang.dir/src/CUDA2HIP_Device_types.cpp.o -c /tmp/teague/
            spack-stage/spack-stage-hipify-clang-6.1.2-mr4sznarz5o3xg6tppkiihnywbjaxcoo/spack-src/src/C
            UDA2HIP_Device_types.cpp
  >> 83     /tmp/teague/spack-stage/spack-stage-hipify-clang-6.1.2-mr4sznarz5o3xg6tppkiihnywbjaxcoo/spa
            ck-src/src/CUDA2HIP_Doc.cpp:23:10: fatal error: 'sstream' file not found
     84        23 | #include <sstream>
     85           |          ^~~~~~~~~
     86     In file included from In file included from In file included from /tmp/teague/spack-stage/s
            pack-stage-hipify-clang-6.1.2-mr4sznarz5o3xg6tppkiihnywbjaxcoo/spack-src/src/CUDA2HIP_Compl
            ex_API_types.cpp/tmp/teague/spack-stage/spack-stage-hipify-clang-6.1.2-mr4sznarz5o3xg6tppki
            ihnywbjaxcoo/spack-src/src/CUDA2HIP_Device_types.cpp/tmp/teague/spack-stage/spack-stage-hip
            ify-clang-6.1.2-mr4sznarz5o3xg6tppkiihnywbjaxcoo/spack-src/src/CUDA2HIP_CAFFE2_API_function
            s.cpp:::2323In file included from 23:
     87     In file included from :
     88     :
     89     /tmp/teague/spack-stage/spack-stage-hipify-clang-6.1.2-mr4sznarz5o3xg6tppkiihnywbjaxcoo/spa
            ck-src/src/CUDA2HIP_Complex_API_functions.cppIn file included from /tmp/teague/spack-stage/
            spack-stage-hipify-clang-6.1.2-mr4sznarz5o3xg6tppkiihnywbjaxcoo/spack-src/src/CUDA2HIP_CAFF
            E2_API_types.cppIn file included from In file included from :In file included from /tmp/tea
            gue/spack-stage/spack-stage-hipify-clang-6.1.2-mr4sznarz5o3xg6tppkiihnywbjaxcoo/spack-src/s
            rc/CUDA2HIP.h/tmp/teague/spack-stage/spack-stage-hipify-clang-6.1.2-mr4sznarz5o3xg6tppkiihn
            ywbjaxcoo/spack-src/src/CUDA2HIP.h/tmp/teague/spack-stage/spack-stage-hipify-clang-6.1.2-mr
            4sznarz5o3xg6tppkiihnywbjaxcoo/spack-src/src/CUDA2HIP.h:23:::/tmp/teague/spack-stage/spack-
            stage-hipify-clang-6.1.2-mr4sznarz5o3xg6tppkiihnywbjaxcoo/spack-src/src/CUDA2HIP_CUB_API_ty
            pes.cpp23:

     ...

     99     :
     100    :/home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/llvm-amdgpu-6.1.2-hzp
            26dybttascrfy6agox33jxw5wendk/include/llvm/ADT/DenseMapInfo.h23:/home/teague/System/apps/sp
            ack/opt/spack/linux-pop22-zen3/gcc-11.4.0/llvm-amdgpu-6.1.2-hzp26dybttascrfy6agox33jxw5wend
            k/include/llvm/ADT/StringRef.h/home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc
            -11.4.0/llvm-amdgpu-6.1.2-hzp26dybttascrfy6agox33jxw5wendk/include/llvm/ADT/DenseMapInfo.h/
            home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/llvm-amdgpu-6.1.2-hzp26
            dybttascrfy6agox33jxw5wendk/include/llvm/ADT/DenseMapInfo.h25::
     101    12:
     102    ::In file included from :
     103    In file included from 1217:In file included from /home/teague/System/apps/spack/opt/spack/l
            inux-pop22-zen3/gcc-11.4.0/llvm-amdgpu-6.1.2-hzp26dybttascrfy6agox33jxw5wendk/include/llvm/
            ADT/StringRef.h:
     104    :17/tmp/teague/spack-stage/spack-stage-hipify-clang-6.1.2-mr4sznarz5o3xg6tppkiihnywbjaxcoo/
            spack-src/src/CUDA2HIP.h/home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.
            0/llvm-amdgpu-6.1.2-hzp26dybttascrfy6agox33jxw5wendk/include/llvm/ADT/DenseMapInfo.h:/tmp/t
            eague/spack-stage/spack-stage-hipify-clang-6.1.2-mr4sznarz5o3xg6tppkiihnywbjaxcoo/spack-src
            /src/CUDA2HIP_CUB_API_functions.cpp/home/teague/System/apps/spack/opt/spack/linux-pop22-zen
            3/gcc-11.4.0/llvm-amdgpu-6.1.2-hzp26dybttascrfy6agox33jxw5wendk/include/llvm/ADT/DenseMapIn
            fo.hIn file included from 17:1210:::::/tmp/teague/spack-stage/spack-stage-hipify-clang-6.1.
            2-mr4sznarz5o3xg6tppkiihnywbjaxcoo/spack-src/src/CUDA2HIP_DNN_API_functions.cpp17:
  >> 105    ::102510:23: 17:
     106     :/home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/llvm-amdgpu-6.1.2-hz
            p26dybttascrfy6agox33jxw5wendk/include/llvm/ADT/DenseMapInfo.h 23:
     107    :fatal error: :In file included from In file included from 'cassert' file not found10fatal 
            error: 10fatal error: :
     108    In file included from 17/home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.
            0/llvm-amdgpu-6.1.2-hzp26dybttascrfy6agox33jxw5wendk/include/llvm/ADT/StringRef.h/tmp/teagu
            e/spack-stage/spack-stage-hipify-clang-6.1.2-mr4sznarz5o3xg6tppkiihnywbjaxcoo/spack-src/src
            /CUDA2HIP.h
     109    ::'cassert' file not found:'cassert' file not foundIn file included from /tmp/teague/spack-
            stage/spack-stage-hipify-clang-6.1.2-mr4sznarz5o3xg6tppkiihnywbjaxcoo/spack-src/src/CUDA2HI
            P_Device_functions.cpp
     110    :: 12
     111    /tmp/teague/spack-stage/spack-stage-hipify-clang-6.1.2-mr4sznarz5o3xg6tppkiihnywbjaxcoo/spa
            ck-src/src/CUDA2HIP.h::

     ...

     170    In file included from /tmp/teague/spack-stage/spack-stage-hipify-clang-6.1.2-mr4sznarz5o3xg
            6tppkiihnywbjaxcoo/spack-src/src/ArgParse.cpp:23:
     171    In file included from /tmp/teague/spack-stage/spack-stage-hipify-clang-6.1.2-mr4sznarz5o3xg
            6tppkiihnywbjaxcoo/spack-src/src/ArgParse.h:25:
     172    In file included from /home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/
            llvm-amdgpu-6.1.2-hzp26dybttascrfy6agox33jxw5wendk/include/clang/Tooling/CommonOptionsParse
            r.h:29:
     173    In file included from /home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/
            llvm-amdgpu-6.1.2-hzp26dybttascrfy6agox33jxw5wendk/include/clang/Tooling/ArgumentsAdjusters
            .h:19:
     174    In file included from /home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/
            llvm-amdgpu-6.1.2-hzp26dybttascrfy6agox33jxw5wendk/include/clang/Basic/LLVM.h:21:
     175    In file included from /home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/
            llvm-amdgpu-6.1.2-hzp26dybttascrfy6agox33jxw5wendk/include/llvm/Support/Casting.h:18:
  >> 176    /home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/llvm-amdgpu-6.1.2-hzp2
            6dybttascrfy6agox33jxw5wendk/include/llvm/Support/type_traits.h:17:10: fatal error: 'type_t
            raits' file not found
     177       17 | #include <type_traits>
     178          |          ^~~~~~~~~~~~~
     179    1 error generated.
     180    1 error generated.
     181    1 error generated.
     182    1 error generated.
     183    1 error generated.
     184    1 error generated.
     185    1 error generated.
  >> 186    make[2]: *** [CMakeFiles/hipify-clang.dir/build.make:261: CMakeFiles/hipify-clang.dir/src/C
            UDA2HIP_Device_types.cpp.o] Error 1
     187    make[2]: *** Waiting for unfinished jobs....
  >> 188    make[2]: *** [CMakeFiles/hipify-clang.dir/build.make:191: CMakeFiles/hipify-clang.dir/src/C
            UDA2HIP_Complex_API_functions.cpp.o] Error 1
  >> 189    make[2]: *** [CMakeFiles/hipify-clang.dir/build.make:205: CMakeFiles/hipify-clang.dir/src/C
            UDA2HIP_Complex_API_types.cpp.o] Error 1
  >> 190    make[2]: *** [CMakeFiles/hipify-clang.dir/build.make:135: CMakeFiles/hipify-clang.dir/src/C
            UDA2HIP_CAFFE2_API_functions.cpp.o] Error 1
  >> 191    make[2]: *** [CMakeFiles/hipify-clang.dir/build.make:177: CMakeFiles/hipify-clang.dir/src/C
            UDA2HIP_CUB_API_types.cpp.o] Error 1
  >> 192    make[2]: *** [CMakeFiles/hipify-clang.dir/build.make:93: CMakeFiles/hipify-clang.dir/src/CU
            DA2HIP.cpp.o] Error 1
     193    1 error generated.
  >> 194    make[2]: *** [CMakeFiles/hipify-clang.dir/build.make:121: CMakeFiles/hipify-clang.dir/src/C
            UDA2HIP_BLAS_API_types.cpp.o] Error 1
     195    1 error generated.
     196    1 error generated.
  >> 197    make[2]: *** [CMakeFiles/hipify-clang.dir/build.make:233: CMakeFiles/hipify-clang.dir/src/C
            UDA2HIP_DNN_API_types.cpp.o] Error 1
     198    1 error generated.
     199    1 error generated.
     200    1 error generated.
  >> 201    make[2]: *** [CMakeFiles/hipify-clang.dir/build.make:289: CMakeFiles/hipify-clang.dir/src/C
            UDA2HIP_Driver_API_functions.cpp.o] Error 1
  >> 202    make[2]: *** [CMakeFiles/hipify-clang.dir/build.make:247: CMakeFiles/hipify-clang.dir/src/C
            UDA2HIP_Device_functions.cpp.o] Error 1
  >> 203    make[2]: *** [CMakeFiles/hipify-clang.dir/build.make:107: CMakeFiles/hipify-clang.dir/src/C
            UDA2HIP_BLAS_API_functions.cpp.o] Error 1
  >> 204    make[2]: *** [CMakeFiles/hipify-clang.dir/build.make:219: CMakeFiles/hipify-clang.dir/src/C
            UDA2HIP_DNN_API_functions.cpp.o] Error 1
  >> 205    make[2]: *** [CMakeFiles/hipify-clang.dir/build.make:149: CMakeFiles/hipify-clang.dir/src/C
            UDA2HIP_CAFFE2_API_types.cpp.o] Error 1
     206    1 error generated.
  >> 207    make[2]: *** [CMakeFiles/hipify-clang.dir/build.make:163: CMakeFiles/hipify-clang.dir/src/C
            UDA2HIP_CUB_API_functions.cpp.o] Error 1
     208    1 error generated.
  >> 209    make[2]: *** [CMakeFiles/hipify-clang.dir/build.make:79: CMakeFiles/hipify-clang.dir/src/Ar
            gParse.cpp.o] Error 1
     210    1 error generated.
  >> 211    make[2]: *** [CMakeFiles/hipify-clang.dir/build.make:275: CMakeFiles/hipify-clang.dir/src/C
            UDA2HIP_Doc.cpp.o] Error 1
     212    make[2]: Leaving directory '/tmp/teague/spack-stage/spack-stage-hipify-clang-6.1.2-mr4sznar
            z5o3xg6tppkiihnywbjaxcoo/spack-build-mr4szna'
  >> 213    make[1]: *** [CMakeFiles/Makefile2:222: CMakeFiles/hipify-clang.dir/all] Error 2
     214    make[1]: Leaving directory '/tmp/teague/spack-stage/spack-stage-hipify-clang-6.1.2-mr4sznar
            z5o3xg6tppkiihnywbjaxcoo/spack-build-mr4szna'
  >> 215    make: *** [Makefile:139: all] Error 2
</pre></details>

### Information on your system

* **Spack:** 0.23.0.dev0 (0d04223ccdae43e606d7022fb59eb700c7bb896c)
* **Python:** 3.10.12
* **Platform:** linux-pop22-zen3
* **Concretizer:** clingo

### Additional information

I suspect this is related to `llvm-amdgpu` not having all of the same includes as `llvm` as the paths below don't include the files mentioned in the error message, but they are present in the `llvm` install prefix. I don't know if this should be considered a build error for this package or for `llvm-amdgpu`, however.

```
...
-- Found LLVM 17.0.0git:
--    - CMake module path  : /home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/llvm-amdgpu-6.1.2-hzp26dybttascrfy6agox33jxw5wendk/lib/cmake/llvm
--    - Clang include path : /home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/llvm-amdgpu-6.1.2-hzp26dybttascrfy6agox33jxw5wendk/include
--    - LLVM Include path  : /home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/llvm-amdgpu-6.1.2-hzp26dybttascrfy6agox33jxw5wendk/include
--    - Binary path        : /home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/llvm-amdgpu-6.1.2-hzp26dybttascrfy6agox33jxw5wendk/bin
...
```

```console
$ find $(spl -i llvm-amdgpu/qfe7xum)/include/ -name '*cassert*'
$ find $(spl -i llvm/caug6zt)/include/ -name '*cassert*'
/home/teague/System/apps/spack/opt/spack/linux-pop22-zen3/gcc-11.4.0/llvm-17.0.6-caug6zte55duv2tbq7t7vbgm2yi6wylf/include/c++/v1/cassert
```

[spack-build-env.txt](https://github.com/user-attachments/files/16322412/spack-build-env.txt)
[spack-build-out.txt](https://github.com/user-attachments/files/16322413/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by srekolam** [comment]
i see inside the config spec for hipify-clang,  2 versions of gcc-runtime and glibc is mentioned..any reason why
^gcc-runtime@11.4.0%gcc@11.4.0 build_system=generic arch=linux-pop22-zen3
^glibc@2.35%gcc@11.4.0 build_system=autotools arch=linux-pop22-zen3

^gcc-runtime@14.1.0%gcc@14.1.0 build_system=generic arch=linux-pop22-zen3
^glibc@2.35%gcc@14.1.0 build_system=autotools arch=linux-pop22-zen3

**Comment by teaguesterling** [comment]
That's bleed from packages built with a system GCC and with a Spack compiled GCC. I could be wrong, but given this specific error, I don't believe it would be related. Happy to explore if it is like the cause, though/

**Comment by afzpatel** [comment]
I tried reproducing the issue on ubuntu 22 but I was able to successfully build both hipify-clang%gcc@11.4.0 and hipify-clang%gcc@14.1.0. I also tried to match the specs in the post by building hipify-clang%gcc@14.1.0  ^llvm-amdgpu%gcc@11.4.0. and this was also successful. I've attached the spec for that package for reference.
[hipify-clang-spec.txt](https://github.com/user-attachments/files/16474802/hipify-clang-spec.txt)

**Comment by teaguesterling** [comment]
Odd! I'll try it fresh again. I suspect this is a consequence of how llvm-amdgpu is installed on my machine, but I've tried multiple reinstalls to no avail.

**Comment by teaguesterling** [comment]
I decided to look at this again. This is likely an issue with `llvm-amdgpu` as that *should* have the C++ stdlib installed with it (or at least ensure something else provides it) but it explicitly does not include it.

I'll close this as it doesn't seem to have anything to do with `hipify-clang` specifically.
