### ISSUE TITLE
Installation issue: fms: need to set CMAKE_ environment variables [regression]

### ISSUE THREAD

**Issue by harshula** [LLNL/spack#45358]
### Steps to reproduce the issue

```console
$ spack spec -I fms@2023.02 %intel@2021.6.0 target=x86_64
...
Input spec
--------------------------------
 -   fms@2023.02%intel@2021.6.0 arch=None-None-x86_64

Concretized
--------------------------------
 -   fms@2023.02%intel@2021.6.0~deprecated_io+gfs_phys+internal_file_nml~ipo~large_file+openmp~pic+quad_precision~yaml build_system=cmake build_type=Release constants=GFDL generator=make precision=32 arch=linux-rocky8-x86_64
[e]      ^cmake@3.24.2%intel@19.0.5.281~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-rocky8-x86_64
[e]      ^glibc@2.28%intel@2021.6.0 build_system=autotools arch=linux-rocky8-x86_64
[+]      ^gmake@4.4.1%intel@19.0.5.281~guile build_system=generic arch=linux-rocky8-x86_64
[e]          ^glibc@2.28%intel@19.0.5.281 build_system=autotools arch=linux-rocky8-x86_64
[+]      ^netcdf-c@4.7.4%intel@19.0.5.281~blosc~byterange~dap~fsync~hdf4~jna+mpi~nczarr_zip+optimize~parallel-netcdf+pic+shared~szip~zstd build_system=autotools arch=linux-rocky8-x86_64
[+]          ^hdf5@1.14.3%intel@19.0.5.281~cxx~fortran+hl~ipo~java~map+mpi+shared~subfiling~szip~threadsafe+tools api=default build_system=cmake build_type=Release generator=make patches=82088c8 arch=linux-rocky8-x86_64
[+]              ^pkgconf@2.2.0%intel@19.0.5.281 build_system=autotools arch=linux-rocky8-x86_64
[+]              ^zlib-ng@2.1.6%intel@19.0.5.281+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-rocky8-x86_64
[+]      ^netcdf-fortran@4.5.2%intel@19.0.5.281~doc+pic+shared build_system=autotools patches=b050dbd arch=linux-rocky8-x86_64
[e]      ^openmpi@4.0.2%intel@19.0.5.281~atomics~cuda~cxx~cxx_exceptions~gpfs~internal-hwloc~internal-libevent~internal-pmix~java~legacylaunchers~lustre~memchecker~openshmem~orterunprefix~romio+rsh~singularity~static+vt+wrapper-rpath build_system=autotools fabrics=none patches=073477a,60ce20b romio-filesystem=none schedulers=none arch=linux-rocky8-x86_64
```

### Error message

<details><summary>Error message</summary>

<pre>
$ spack install fms@2023.02 %intel@2021.6.0 target=x86_64
...
[openmpi 4.0.2]
1 error found in build log:
     9     -- Detecting C compile features - done
     10    -- Detecting Fortran compiler ABI info
     11    -- Detecting Fortran compiler ABI info - done
     12    -- Check for working Fortran compiler: /[...]/test-v0.22/spack/lib/spack/env/intel/ifort - skipped
     13    -- Found MPI_C: /apps/openmpi/4.0.2/lib/libmpi.so (found version "3.1")
     14    -- Could NOT find MPI_Fortran (missing: MPI_Fortran_F77_HEADER_DIR MPI_Fortran_MODULE_DIR) (found version "3.1")
  >> 15    CMake Error at /apps/cmake/3.24.2/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
     16      Could NOT find MPI (missing: MPI_Fortran_FOUND Fortran) (found version
     17      "3.1")
     18    Call Stack (most recent call first):
     19      /apps/cmake/3.24.2/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
     20      /apps/cmake/3.24.2/share/cmake-3.24/Modules/FindMPI.cmake:1835 (find_package_handle_standard_args)
     21      CMakeLists.txt:84 (find_package)
...
[openmpi 4.1.5]
1 error found in build log:
     9     -- Detecting C compile features - done
     10    -- Detecting Fortran compiler ABI info
     11    -- Detecting Fortran compiler ABI info - done
     12    -- Check for working Fortran compiler: /[...]/test-v0.22-fms/spack/lib/spack/env/intel/ifort - skipped
     13    -- Found MPI_C: /apps/openmpi/4.1.5/lib/libmpi.so (found version "3.1")
     14    -- Could NOT find MPI_Fortran (missing: MPI_Fortran_F77_HEADER_DIR MPI_Fortran_MODULE_DIR) (found version "3.1")
  >> 15    CMake Error at /apps/cmake/3.24.2/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
     16      Could NOT find MPI (missing: MPI_Fortran_FOUND Fortran) (found version
     17      "3.1")
     18    Call Stack (most recent call first):
     19      /apps/cmake/3.24.2/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
     20      /apps/cmake/3.24.2/share/cmake-3.24/Modules/FindMPI.cmake:1835 (find_package_handle_standard_args)
     21      CMakeLists.txt:84 (find_package)
</pre></details>

### Information on your system

* **Spack:** 0.22.1 (42e310074a69cb4ee052a73e830e07ad26a15440)
* **Python:** 3.6.8
* **Platform:** linux-rocky8-cascadelake
* **Concretizer:** clingo
* Openmpi on gadi.nci.org.au has filenames and a layout that is non-standard.

### Additional information

Hi @AlexanderRichert-NOAA  @Hang-Lei-NOAA  @climbfuji  @edwardhartnett  @rem1776,

Please let me know if you want any other information. It appears that the PR https://github.com/spack/spack/pull/43726 removed setting the CMAKE_ environment variables.

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by climbfuji** [comment]
Do you know if this problem also occurs for newer versions of `fms`?

**Comment by harshula** [comment]
Hi @climbfuji ,

I added the following changes to the fms SPD (Spack Package Definition) in Spack `v0.22.1`:
```
diff --git a/var/spack/repos/builtin/packages/fms/package.py b/var/spack/repos/builtin/packages/fms/package.py
index 95465966a5..350353152c 100644
--- a/var/spack/repos/builtin/packages/fms/package.py
+++ b/var/spack/repos/builtin/packages/fms/package.py
@@ -19,6 +19,10 @@ class Fms(CMakePackage):
     license("LGPL-3.0-or-later")
 
     maintainers("AlexanderRichert-NOAA", "Hang-Lei-NOAA", "edwardhartnett", "rem1776", "climbfuji")
+    version(
+        "2024.01.01", sha256="41c8686bad2b1aed76275e35cbe1af855f7dfce9b6d8907744ea2e8174758f6a"
+    )
+    version("2024.01", sha256="29ac23a5a2a4765ae66d218bb261cb04f7ad44618205ab0924c4e66c9ef8fa38")
     version("2023.04", sha256="feb895ea2b3269ca66df296199a36af335f0dc281e2dab2f1bfebb19fd9c22c4")
     version("2023.02", sha256="dc029ffadfd82c334f104268bedd8635c77976485f202f0966ae4cf06d2374be")
     version(
```

Same failure:
```
$ spack install fms@2024.01.01 %intel@2021.6.0 target=x86_64
...
1 error found in build log:
     9     -- Detecting C compile features - done
     10    -- Detecting Fortran compiler ABI info
     11    -- Detecting Fortran compiler ABI info - done
     12    -- Check for working Fortran compiler: /[...]/test-v0.22-fms/spack/lib/spack/env/intel/ifort - skipped
     13    -- Found MPI_C: /apps/openmpi/4.1.5/lib/libmpi.so (found version "3.1")
     14    -- Could NOT find MPI_Fortran (missing: MPI_Fortran_F77_HEADER_DIR MPI_Fortran_MODULE_DIR) (found version "3.1")
  >> 15    CMake Error at /apps/cmake/3.24.2/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
     16      Could NOT find MPI (missing: MPI_Fortran_FOUND Fortran) (found version
     17      "3.1")
     18    Call Stack (most recent call first):
     19      /apps/cmake/3.24.2/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
     20      /apps/cmake/3.24.2/share/cmake-3.24/Modules/FindMPI.cmake:1835 (find_package_handle_standard_args)
     21      CMakeLists.txt:84 (find_package)
```

**Comment by harshula** [comment]
If I make the following changes. i.e. set CMAKE_* environment variables:
```
diff --git a/var/spack/repos/builtin/packages/fms/package.py b/var/spack/repos/builtin/packages/fms/package.py
index 95465966a5..a922e3d11b 100644
--- a/var/spack/repos/builtin/packages/fms/package.py
+++ b/var/spack/repos/builtin/packages/fms/package.py
@@ -19,6 +19,10 @@ class Fms(CMakePackage):
     license("LGPL-3.0-or-later")
 
     maintainers("AlexanderRichert-NOAA", "Hang-Lei-NOAA", "edwardhartnett", "rem1776", "climbfuji")
+    version(
+        "2024.01.01", sha256="41c8686bad2b1aed76275e35cbe1af855f7dfce9b6d8907744ea2e8174758f6a"
+    )
+    version("2024.01", sha256="29ac23a5a2a4765ae66d218bb261cb04f7ad44618205ab0924c4e66c9ef8fa38")
     version("2023.04", sha256="feb895ea2b3269ca66df296199a36af335f0dc281e2dab2f1bfebb19fd9c22c4")
     version("2023.02", sha256="dc029ffadfd82c334f104268bedd8635c77976485f202f0966ae4cf06d2374be")
     version(
@@ -111,5 +115,8 @@ def cmake_args(self):
             self.define_from_variant("FPIC", "pic"),
             self.define_from_variant("USE_DEPRECATED_IO", "deprecated_io"),
         ]
+        args.append(self.define("CMAKE_C_COMPILER", self.spec["mpi"].mpicc))
+        args.append(self.define("CMAKE_CXX_COMPILER", self.spec["mpi"].mpicxx))
+        args.append(self.define("CMAKE_Fortran_COMPILER", self.spec["mpi"].mpifc))
 
         return args
```

The build succeeds:
```$ spack install fms@2024.01.01 %intel@2021.6.0 target=x86_64

==> Installing fms-2024.01.01-2svm6sreycaaagii3wgjpjunoh7k5k2c [16/16]
==> No binary for fms-2024.01.01-2svm6sreycaaagii3wgjpjunoh7k5k2c found: installing from source
==> Using cached archive: /[...]/test-v0.22-fms/spack/var/spack/cache/_source-cache/archive/41/41c8686bad2b1aed76275e35cbe1af855f7dfce9b6d8907744ea2e8174758f6a.tar.gz
==> No patches needed for fms
==> fms: Executing phase: 'cmake'
==> fms: Executing phase: 'build'
==> fms: Executing phase: 'install'
==> fms: Successfully installed fms-2024.01.01-2svm6sreycaaagii3wgjpjunoh7k5k2c
  Stage: 0.81s.  Cmake: 32.68s.  Build: 4m 36.38s.  Install: 2.94s.  Post-install: 1.87s.  Total: 5m 16.55s
```

**Comment by climbfuji** [comment]
I am ok with adding this back in, but I am wondering why @srherbener had to remove it in the last PR.

**Comment by srherbener** [comment]
I proposed the removal of the MPI wrappers in the last PR because that enabled the FMS (and MAPL) build processes to find the Fortran component of OpenMP. I'm okay with putting the MPI wrappers back in, and finding another solution. Interestingly, with Ventura and Xcode 14.x the MPI wrappers worked fine, I'm only seeing the issue with Sonoma and Xcode 15.1. I think some more digging might reveal another solution that allows it to work with the MPI wrappers.

**Comment by AlexanderRichert-NOAA** [comment]
It might be worth trying to do some debugging of cmake's FindMPI.cmake and see why it's not picking up on the Fortran component. This wouldn't be the first time we ran into an edge that that file misses as far as detecting MPI providers.

**Comment by harshula** [comment]
Hi, The supercomputer we use, Gadi, has a non-standard openmpi directory layout. e.g. If I set `$CMAKE_PREFIX_PATH` to include "/apps/openmpi/4.1.5/include/Intel", the FMS build succeeds even without the MPI compiler wrappers being passed explicitly to CMake. i.e. `args.append(self.define("CMAKE_PREFIX_PATH", join_path(self.spec["mpi"].prefix.include, "Intel")))`

However, if I try to use [Extra attributes for external packages](https://spack.readthedocs.io/en/latest/packages_yaml.html#extra-attributes-for-external-packages), it doesn't seem to work. e.g.
```
    - spec: openmpi@4.1.5
      prefix: /apps/openmpi/4.1.5
      extra_attributes:
        environment:
          prepend_path:
            CMAKE_PREFIX_PATH: /apps/openmpi/4.1.5/include/Intel
```

Should this work?
```
        args.append(self.define("MPI_Fortran_COMPILER", self.spec["mpi"].mpifc))
```

**Comment by harshula** [comment]
Hi, Good news! [Extra attributes for external packages](https://spack.readthedocs.io/en/latest/packages_yaml.html#extra-attributes-for-external-packages) does work. For it to work, I had to uninstall `openmpi` and its dependents first. Then install `fms` along with all its dependencies, including `openmpi`.
