### ISSUE TITLE
ninja-build for Fortran

### ISSUE THREAD

**Issue by aprokop** [LLNL/spack#4538]
Kitware maintains a [fork](https://github.com/Kitware/ninja) of `ninja-build`. There are outstanding PRs for mainline, but no progress has been made in months. 

I think it would be nice if Spack provided an easy way to access that. Few questions:
- Does this sound like a good idea?
- If yes, is it better to a) add a `fortran` variant to existing ninja-build, or create a new `ninja-fortran` package?
- If a), how does one change a url based on variant?

**Comment by adamjstewart** [comment]
You can't change a URL based on a variant, so you would have to create a separate package.
