### ISSUE TITLE
Installation issue: rocm-openmp-extras, another target with the same name already exists.

### ISSUE THREAD

**Issue by jordialcaraz** [LLNL/spack#45411]
### Steps to reproduce the issue

```console
$ spack spec -l rocm-openmp-extras

Input spec
--------------------------------
 -   rocm-openmp-extras

Concretized
--------------------------------
 -   w3ez3wv  rocm-openmp-extras@6.1.1%gcc@8.5.0~asan build_system=generic patches=9b9ddd0 arch=linux-rhel8-zen
[+]  uypdcrw      ^cmake@3.29.4%gcc@8.5.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-rhel8-zen
[+]  2olgdk2          ^curl@8.7.1%gcc@8.5.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-rhel8-zen
[+]  f5djzsy              ^nghttp2@1.62.0%gcc@8.5.0 build_system=autotools arch=linux-rhel8-zen
[+]  j3exw3w          ^gmake@4.4.1%gcc@8.5.0~guile build_system=generic arch=linux-rhel8-zen
[+]  owimakl          ^ncurses@6.5%gcc@8.5.0~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-rhel8-zen
[+]  enyzsx5          ^zlib-ng@2.1.6%gcc@8.5.0+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-rhel8-zen
[+]  kd4bcm4      ^comgr@6.1.1%gcc@8.5.0~asan~ipo build_system=cmake build_type=Release generator=make arch=linux-rhel8-zen
[+]  gk7wgtv          ^rocm-cmake@6.1.1%gcc@8.5.0~ipo build_system=cmake build_type=Release generator=make arch=linux-rhel8-zen
[+]  4ehvlay          ^z3@4.12.4%gcc@8.5.0~gmp~ipo~python build_system=cmake build_type=Release generator=make arch=linux-rhel8-zen
[+]  qgqlkke      ^elfutils@0.191%gcc@8.5.0~debuginfod+exeprefix+nls build_system=autotools arch=linux-rhel8-zen
[+]  2iit3sj          ^bzip2@1.0.8%gcc@8.5.0~debug~pic+shared build_system=generic arch=linux-rhel8-zen
[+]  akqtq3d              ^diffutils@3.10%gcc@8.5.0 build_system=autotools arch=linux-rhel8-zen
[+]  hyezgix          ^gettext@0.22.5%gcc@8.5.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-rhel8-zen
[+]  ruqvhyk              ^libxml2@2.10.3%gcc@8.5.0+pic~python+shared build_system=autotools arch=linux-rhel8-zen
[+]  bsbkowk              ^tar@1.34%gcc@8.5.0 build_system=autotools zip=pigz arch=linux-rhel8-zen
[+]  dvbvlth                  ^pigz@2.8%gcc@8.5.0 build_system=makefile arch=linux-rhel8-zen
[+]  n67pr2r          ^m4@1.4.19%gcc@8.5.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-rhel8-zen
[+]  rjsasmr          ^pkgconf@2.2.0%gcc@8.5.0 build_system=autotools arch=linux-rhel8-zen
[+]  y5pts66          ^xz@5.4.6%gcc@8.5.0~pic build_system=autotools libs=shared,static arch=linux-rhel8-zen
[+]  wp7w57y          ^zstd@1.5.6%gcc@8.5.0+programs build_system=makefile compression=none libs=shared,static arch=linux-rhel8-zen
[+]  cvlggtv      ^gawk@5.3.0%gcc@8.5.0~nls build_system=autotools arch=linux-rhel8-zen
[+]  7bz3b32          ^gmp@6.3.0%gcc@8.5.0+cxx build_system=autotools libs=shared,static arch=linux-rhel8-zen
[+]  bvdqnro              ^autoconf@2.72%gcc@8.5.0 build_system=autotools arch=linux-rhel8-zen
[+]  d35gvat              ^automake@1.16.5%gcc@8.5.0 build_system=autotools arch=linux-rhel8-zen
[+]  ct4x75h              ^libtool@2.4.7%gcc@8.5.0 build_system=autotools arch=linux-rhel8-zen
[+]  aioqwyj                  ^findutils@4.9.0%gcc@8.5.0 build_system=autotools patches=440b954 arch=linux-rhel8-zen
[+]  6ip5fay          ^libsigsegv@2.14%gcc@8.5.0 build_system=autotools arch=linux-rhel8-zen
[+]  s63oqw5          ^mpfr@4.2.1%gcc@8.5.0 build_system=autotools libs=shared,static arch=linux-rhel8-zen
[+]  3tx7o7y              ^autoconf-archive@2023.02.20%gcc@8.5.0 build_system=autotools arch=linux-rhel8-zen
[+]  owfg3kz              ^texinfo@7.1%gcc@8.5.0 build_system=autotools arch=linux-rhel8-zen
[+]  wugc5n7          ^readline@8.2%gcc@8.5.0 build_system=autotools patches=bbf97f1 arch=linux-rhel8-zen
[+]  rve2d45      ^gcc-runtime@8.5.0%gcc@8.5.0 build_system=generic arch=linux-rhel8-zen
[e]  surmby3      ^glibc@2.28%gcc@8.5.0 build_system=autotools arch=linux-rhel8-zen
[+]  afa7jni      ^hsa-rocr-dev@6.1.1%gcc@8.5.0~asan+image~ipo+shared build_system=cmake build_type=Release generator=make arch=linux-rhel8-zen
[+]  mhq7q4t          ^numactl@2.0.14%gcc@8.5.0 build_system=autotools patches=4e1d78c,62fc8a8,ff37630 arch=linux-rhel8-zen
[+]  77ovgzk          ^xxd-standalone@8.2.1201%gcc@8.5.0 build_system=makefile arch=linux-rhel8-zen
[+]  g762dmg      ^hsakmt-roct@6.1.1%gcc@8.5.0~asan~ipo+shared build_system=cmake build_type=Release generator=make arch=linux-rhel8-zen
[+]  scysyw7          ^libdrm@2.4.120%gcc@8.5.0~docs build_system=generic arch=linux-rhel8-zen
[+]  ax6v2hk              ^libpciaccess@0.17%gcc@8.5.0 build_system=autotools arch=linux-rhel8-zen
[+]  lknb6gm                  ^util-macros@1.20.1%gcc@8.5.0 build_system=autotools arch=linux-rhel8-zen
[+]  q3mmga7              ^libpthread-stubs@0.5%gcc@8.5.0 build_system=autotools arch=linux-rhel8-zen
[+]  vcm3qog              ^meson@1.3.2%gcc@8.5.0 build_system=python_pip patches=0f0b1bd arch=linux-rhel8-zen
[+]  5bbjt7m                  ^py-wheel@0.41.2%gcc@8.5.0 build_system=generic arch=linux-rhel8-zen
[+]  4h2vze2      ^libffi@3.4.6%gcc@8.5.0 build_system=autotools arch=linux-rhel8-zen
[+]  gtpjunc      ^llvm-amdgpu@6.1.1%gcc@8.5.0~ipo~link_llvm_dylib~llvm_dylib+rocm-device-libs build_system=cmake build_type=Release generator=ninja patches=b4774ca arch=linux-rhel8-zen
[+]  hi6bb4f          ^ninja@1.12.0%gcc@8.5.0+re2c build_system=generic arch=linux-rhel8-zen
[+]  bxabhhg              ^re2c@2.2%gcc@8.5.0 build_system=generic arch=linux-rhel8-zen
[+]  feiimmu      ^perl-data-dumper@2.173%gcc@8.5.0 build_system=perl arch=linux-rhel8-zen
[+]  nmlzl6c          ^perl@5.38.2%gcc@8.5.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-rhel8-zen
[+]  zcsbfi3              ^berkeley-db@18.1.40%gcc@8.5.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-rhel8-zen
[+]  kyvjoqt      ^py-setuptools@69.2.0%gcc@8.5.0 build_system=generic arch=linux-rhel8-zen
[+]  zfjxdg6          ^py-pip@23.1.2%gcc@8.5.0 build_system=generic arch=linux-rhel8-zen
[+]  iwb3mvh          ^python-venv@1.0%gcc@8.5.0 build_system=generic arch=linux-rhel8-zen
[+]  d3tcvha      ^python@3.10.14%gcc@8.5.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=0d98e93,7d40923,ebdca64,f2fd060 arch=linux-rhel8-zen
[+]  olpqvn6          ^expat@2.6.2%gcc@8.5.0+libbsd build_system=autotools arch=linux-rhel8-zen
[+]  vphemzm              ^libbsd@0.12.2%gcc@8.5.0 build_system=autotools arch=linux-rhel8-zen
[+]  fplynlg                  ^libmd@1.0.4%gcc@8.5.0 build_system=autotools arch=linux-rhel8-zen
[+]  smedmzt          ^gdbm@1.23%gcc@8.5.0 build_system=autotools arch=linux-rhel8-zen
[+]  ydj7tth          ^libxcrypt@4.4.35%gcc@8.5.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-rhel8-zen
[+]  t5a5kdz          ^openssl@3.3.1%gcc@8.5.0~docs+shared build_system=generic certs=mozilla arch=linux-rhel8-zen
[+]  hx3ebwi              ^ca-certificates-mozilla@2023-05-30%gcc@8.5.0 build_system=generic arch=linux-rhel8-zen
[+]  463yf2b          ^sqlite@3.43.2%gcc@8.5.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-rhel8-zen
[+]  xsrhfsz          ^util-linux-uuid@2.40.1%gcc@8.5.0 build_system=autotools arch=linux-rhel8-zen
[+]  3o6rz34      ^rocm-core@6.1.1%gcc@8.5.0~ipo build_system=cmake build_type=Release generator=make arch=linux-rhel8-zen




```

### Error message

<details><summary>Error message</summary>

<pre>
-- LIBOMPTARGET: DeviceRTLs gfx1031: Getting ROCm device libs from /storage/users/jalcaraz/spackkkk/spack/opt/spack/linux-rhel8-zen/gcc-8.5.0/llvm-amdgpu-6.1.1-gtpjunczjatptmlzv4hlchumtsrexl6k/lib/cmake/AMDDeviceLibs
 ===================> bc_files: Configuration.cpp-400-gfx1031.bc;Debug.cpp-400-gfx1031.bc;Kernel.cpp-400-gfx1031.bc;LibC.cpp-400-gfx1031.bc;Mapping.cpp-400-gfx1031.bc;Misc.cpp-400-gfx1031.bc;Parallelism.cpp-400-gfx1031.bc;Reduction.cpp-400-gfx1031.bc;State.cpp-400-gfx1031.bc;Synchronization.cpp-400-gfx1031.bc;Tasking.cpp-400-gfx1031.bc;Utils.cpp-400-gfx1031.bc;Workshare.cpp-400-gfx1031.bc;ExtraMapping.cpp-400-gfx1031.bc;Xteamr.cpp-400-gfx1031.bc;Memory.cpp-400-gfx1031.bc;Xteams.cpp-400-gfx1031.bc;/tmp/jalcaraz/spack-stage/spack-stage-rocm-openmp-extras-6.1.1-w3ez3wvssco52eehypq7ybssajcp747d/spack-src/spack-build-openmp/libm-400-gfx1031.bc;/tmp/jalcaraz/spack-stage/spack-stage-rocm-openmp-extras-6.1.1-w3ez3wvssco52eehypq7ybssajcp747d/spack-src/spack-build-openmp/libomptarget/hostexec/libhostexec-400-gfx1031.bc;/storage/users/jalcaraz/spackkkk/spack/opt/spack/linux-rhel8-zen/gcc-8.5.0/llvm-amdgpu-6.1.1-gtpjunczjatptmlzv4hlchumtsrexl6k/amdgcn/bitcode/ocml.bc;/storage/users/jalcaraz/spackkkk/spack/opt/spack/linux-rhel8-zen/gcc-8.5.0/llvm-amdgpu-6.1.1-gtpjunczjatptmlzv4hlchumtsrexl6k/amdgcn/bitcode/ockl.bc;/storage/users/jalcaraz/spackkkk/spack/opt/spack/linux-rhel8-zen/gcc-8.5.0/llvm-amdgpu-6.1.1-gtpjunczjatptmlzv4hlchumtsrexl6k/amdgcn/bitcode/oclc_wavefrontsize64_off.bc;/storage/users/jalcaraz/spackkkk/spack/opt/spack/linux-rhel8-zen/gcc-8.5.0/llvm-amdgpu-6.1.1-gtpjunczjatptmlzv4hlchumtsrexl6k/amdgcn/bitcode/oclc_isa_version_1031.bc;/storage/users/jalcaraz/spackkkk/spack/opt/spack/linux-rhel8-zen/gcc-8.5.0/llvm-amdgpu-6.1.1-gtpjunczjatptmlzv4hlchumtsrexl6k/amdgcn/bitcode/oclc_abi_version_400.bc ========================
-- LIBOMPTARGET: DeviceRTLs gfx1031: Getting ROCm device libs from /storage/users/jalcaraz/spackkkk/spack/opt/spack/linux-rhel8-zen/gcc-8.5.0/llvm-amdgpu-6.1.1-gtpjunczjatptmlzv4hlchumtsrexl6k/lib/cmake/AMDDeviceLibs
 ===================> bc_files: Configuration.cpp-500-gfx1031.bc;Debug.cpp-500-gfx1031.bc;Kernel.cpp-500-gfx1031.bc;LibC.cpp-500-gfx1031.bc;Mapping.cpp-500-gfx1031.bc;Misc.cpp-500-gfx1031.bc;Parallelism.cpp-500-gfx1031.bc;Reduction.cpp-500-gfx1031.bc;State.cpp-500-gfx1031.bc;Synchronization.cpp-500-gfx1031.bc;Tasking.cpp-500-gfx1031.bc;Utils.cpp-500-gfx1031.bc;Workshare.cpp-500-gfx1031.bc;ExtraMapping.cpp-500-gfx1031.bc;Xteamr.cpp-500-gfx1031.bc;Memory.cpp-500-gfx1031.bc;Xteams.cpp-500-gfx1031.bc;/tmp/jalcaraz/spack-stage/spack-stage-rocm-openmp-extras-6.1.1-w3ez3wvssco52eehypq7ybssajcp747d/spack-src/spack-build-openmp/libm-500-gfx1031.bc;/tmp/jalcaraz/spack-stage/spack-stage-rocm-openmp-extras-6.1.1-w3ez3wvssco52eehypq7ybssajcp747d/spack-src/spack-build-openmp/libomptarget/hostexec/libhostexec-500-gfx1031.bc;/storage/users/jalcaraz/spackkkk/spack/opt/spack/linux-rhel8-zen/gcc-8.5.0/llvm-amdgpu-6.1.1-gtpjunczjatptmlzv4hlchumtsrexl6k/amdgcn/bitcode/ocml.bc;/storage/users/jalcaraz/spackkkk/spack/opt/spack/linux-rhel8-zen/gcc-8.5.0/llvm-amdgpu-6.1.1-gtpjunczjatptmlzv4hlchumtsrexl6k/amdgcn/bitcode/ockl.bc;/storage/users/jalcaraz/spackkkk/spack/opt/spack/linux-rhel8-zen/gcc-8.5.0/llvm-amdgpu-6.1.1-gtpjunczjatptmlzv4hlchumtsrexl6k/amdgcn/bitcode/oclc_wavefrontsize64_off.bc;/storage/users/jalcaraz/spackkkk/spack/opt/spack/linux-rhel8-zen/gcc-8.5.0/llvm-amdgpu-6.1.1-gtpjunczjatptmlzv4hlchumtsrexl6k/amdgcn/bitcode/oclc_isa_version_1031.bc;/storage/users/jalcaraz/spackkkk/spack/opt/spack/linux-rhel8-zen/gcc-8.5.0/llvm-amdgpu-6.1.1-gtpjunczjatptmlzv4hlchumtsrexl6k/amdgcn/bitcode/oclc_abi_version_500.bc ========================
CMake Error at cmake/OpenMPTesting.cmake:209 (add_custom_target):
  add_custom_target cannot create target
  "check-libomptarget-nvptx64-nvidia-cuda" because another target with the
  same name already exists.  The existing target is a custom target created
  in source directory
  "/tmp/jalcaraz/spack-stage/spack-stage-rocm-openmp-extras-6.1.1-w3ez3wvssco52eehypq7ybssajcp747d/spack-src/rocm-openmp-extras/llvm-project/openmp/libomptarget/test".
  See documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  libomptarget/test/CMakeLists.txt:23 (add_openmp_testsuite)

CMake Error at cmake/OpenMPTesting.cmake:209 (add_custom_target):
  add_custom_target cannot create target
  "check-libomptarget-nvptx64-nvidia-cuda-LTO" because another target with
  the same name already exists.  The existing target is a custom target
  created in source directory
  "/tmp/jalcaraz/spack-stage/spack-stage-rocm-openmp-extras-6.1.1-w3ez3wvssco52eehypq7ybssajcp747d/spack-src/rocm-openmp-extras/llvm-project/openmp/libomptarget/test".
  See documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  libomptarget/test/CMakeLists.txt:23 (add_openmp_testsuite)

-- Looking for __atomic_load_1
-- Looking for __atomic_load_1 - not found
-- Looking for __atomic_load_1 in atomic
-- Looking for __atomic_load_1 in atomic - found
-- Found Python3: /storage/users/jalcaraz/spackkkk/spack/opt/spack/linux-rhel8-zen/gcc-8.5.0/python-3.10.14-d3tcvhav3gfwahjl4d6svfntk7kw3psp/bin/python3.10 (found version "3.10.14") found components: Interpreter Development Development.Module Development.Embed
-- Configuring incomplete, errors occurred!

</pre></details>

### Information on your system

* **Spack:** 0.23.0.dev0 (910b923c5dc4b7d5096f58ef0783bdd0d92eee46)
* **Python:** 3.6.8
* **Platform:** linux-rhel8-zen3
* **Concretizer:** clingo

### Additional information

[spack-build-01-install-out.txt](https://github.com/user-attachments/files/16363370/spack-build-01-install-out.txt)
[spack-build-env.txt](https://github.com/user-attachments/files/16363371/spack-build-env.txt)
[spack-build-env-mods.txt](https://github.com/user-attachments/files/16363372/spack-build-env-mods.txt)
[spack-build-out.txt](https://github.com/user-attachments/files/16363374/spack-build-out.txt)

@estewart08  @renjithravindrankannath  @srekolam

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by srekolam** [comment]
from the log, it seems to be a case where it is trying to build the cuda plugin and trying to Enable tests using CUDA plugin. (from the log i see LIBOMPTARGET: Building CUDA offloading plugin.
-- LIBOMPTARGET: Building CUDA plugin for dlopened libcuda
-- LIBOMPTARGET: Enable tests using CUDA plugin
)
this could be because may be it is detecting libcuda on the machine where it is built.
when i try it on my local machine, i do not see the issue because i dont have the libcuda. 
May be setting LIBOMPTARGET_BUILD_CUDA_PLUGIN to FALSE inside the rocm-openmp-extras may force it not to build the plugin .. Need to check with the @estewart08   on this.

**Comment by srekolam** [comment]
the above will help but still when building hostexec it may fail..
Basically inside cmake/Modules/LibomptargetGetDependencies.cmake they are doing find_package(CUDAToolkit QUIET) and based on that they set the LIBOMPTARGET_DEP_CUDA_FOUND . When building hostexec, it is checking this flag and based on that adds the nvptx targets. I think need to check if LIBOMPTARGET_DEP_CUDA_FOUND  can be set to false inside rocm-openmp-extras recipe

**Comment by renjithravindrankannath** [comment]
Created the PR [45658](https://github.com/spack/spack/pull/45658) to  avoid duplicate registration of check-targets and fix for the failure in hostexec.

**Comment by renjithravindrankannath** [comment]
PR [45658](https://github.com/spack/spack/pull/45658) has been merged.
