### ISSUE TITLE
veclibfort fix on osx 10.11

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/spack#4544]
I apparently need veclibfort on my osx system for mfem+petsc+sundials+hypre+lapack.

It doesn't build out of the box on my osx 10.11 system. But, I think my os version is 1 patch behind what is typical at this point. I have an easy fix but I dunno if it would hurt others.

Next, I didn't honestly find veclibfort package.py file to be too complete. For example it calls make specifying a value for PREFIX= but the Makefile for that package sets PREFIX by fiat in first line of the Makefile ignoring whatever Spack passed in via PREFIX= on the command line to Make. So, I honestly don't think that package has ever been installed correctly by spack. It winds up installing to /usr/local/lib. Next, it uses 'clang' compiler by default. Now, it may be that Spack's compiler magic winds up `catching` that and still doing the right thing anyways. Finally, with gcc-6.1 on my osx system, I needed to add CFLAGS=-flax-vector-conversions to get it compile and run correctly.

Does anyone see any problems with a pull request with these changes?

**Comment by adamjstewart** [comment]
Looks like you'll have to edit the Makefile to use the correct variables. See the `stream` package for a good example of how to do this.

**Comment by davydden** [comment]
> So, I honestly don't think that package has ever been installed correctly by spac

i did test it on el-capitan (at the time when I added the package) and it worked perfectly fine where `prefix` should be.

also have a look at https://github.com/Homebrew/homebrew-science/blob/master/veclibfort.rb
`homebrew` do **not** install into `user/local/lib`, they install into `Cellar/package/whatever` and then symlink into `usr/local/lib`. So it looks like it works for them as well.

**Comment by davydden** [comment]
proof that it works on Sierra:
```
$ spack install veclibfort
==> Installing veclibfort
==> Using cached archive: /Users/davydden/spack/var/spack/cache/veclibfort/veclibfort-0.4.2.tar.gz
==> Staging archive: /Users/davydden/spack/var/spack/stage/veclibfort-0.4.2-kcrm3ojmkyedljw6da45iq5x42gfpw77/0.4.2.tar.gz
==> Created stage in /Users/davydden/spack/var/spack/stage/veclibfort-0.4.2-kcrm3ojmkyedljw6da45iq5x42gfpw77
==> Ran patch() for veclibfort
==> Building veclibfort [Package]
==> Executing phase : 'install'
==> Successfully installed veclibfort
  Fetch: 0.00s.  Build: 14.99s.  Total: 15.00s.
[+] /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.1.0-apple/veclibfort-0.4.2-kcrm3ojmkyedljw6da45iq5x42gfpw77
$ ls /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.1.0-apple/veclibfort-0.4.2-kcrm3ojmkyedljw6da45iq5x42gfpw77
lib
$ ls /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.1.0-apple/veclibfort-0.4.2-kcrm3ojmkyedljw6da45iq5x42gfpw77/lib/
libvecLibFort.a		libvecLibFort.dylib	libvecLibFortI.dylib
```

**Comment by markcmiller86** [comment]
Can you do `otool -L` on the installed libvecLibFort.dylib and show what that returns?

**Comment by markcmiller86** [comment]
Also, can you sucessfully link to that lib? My claim is that `-install_name` (which is part of the compiler command for that lib) winds up creating a bogus path for that lib. Homebrow probably creats a symlink in /usr/local/lib to work around this problem

**Comment by davydden** [comment]
what a mess:
```
$ otool -L /Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.1.0-apple/veclibfort-0.4.2-kcrm3ojmkyedljw6da45iq5x42gfpw77/lib/libvecLibFort.dylib
/Users/davydden/spack/opt/spack/darwin-sierra-x86_64/clang-8.1.0-apple/veclibfort-0.4.2-kcrm3ojmkyedljw6da45iq5x42gfpw77/lib/libvecLibFort.dylib:
	/usr/local/lib/libvecLibFort.dylib (compatibility version 0.0.0, current version 0.0.0)
	/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate (compatibility version 1.0.0, current version 4.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
```
@markcmiller86 you were right. It does indeed silently install into `/usr/local/lib/`...

**Comment by markcmiller86** [comment]
Yeah, look at the line for `/usr/local/lib/libvecLibFort.dylib`. That is just plain wrong and you won't be able to link to it correctly until you put a symlink in /usr/local/lib.

**Comment by davydden** [comment]
i agree. This is ugly and should be fixed eventually.

**Comment by markcmiller86** [comment]
Ok, will submit a PR shortly to make some adjustments
