### ISSUE TITLE
spack install suite-sparse fails with appleclang

### ISSUE THREAD

**Issue by goxberry** [LLNL/spack#4549]
See gist here https://gist.github.com/goxberry/e2fdb6dca02bb4ab132f3515a6e02f18 for full details. 

It seems like the crash in building `suite-sparse` is due to the way `spack` handles OpenMP flags: for `appleclang`, it assumes that lack of OpenMP is a hard failure for all packages.

Would adding an `openmp` variant to packages that can disable OpenMP, like `suite-sparse`, be accepted in a pull request?

**Comment by markcmiller86** [comment]
Hmmm. Judging from suite-sparse package.py file, I kinda think lack of OpenMP is a hard-failure for suite-sparse. I mean, it appears to *always* set CFOPENMP flag to self.compiler.openmp_flag. So, maybe just have it raise install error if self.compiler.openmp_flag is empty? But, that assumes that every OpenMP enabled compiler actually needs a flag to enable OpenMP features. Maybe that isn't true of all compilers? Or, maybe it won't always be true in distant future? I dunno.

**Comment by davydden** [comment]
Generally, I think packages should have flags to enable/disable openmp regardless of compiler. That's because sometimes I don't want thread parallelism in a dependency. So I think it's perfectly fine to add a variant.

**Comment by markcmiller86** [comment]
What about packages that actually don't work *without* openmp? It is my impression from looking at suite-sparse that it seems to want openmp by fiat. If that turns out to be false and openmp for suite-sparse is optionally, I agree with @goxberry and @davydden, add the variant for it.

**Comment by goxberry** [comment]
If you download and unzip the archive, the SuiteSparse default for `CFOPENMP` is the empty string, and [version 4.5.4 builds on a Mac with clang](https://github.com/Homebrew/homebrew-science/blob/master/suite-sparse.rb), so it should be just fine to build SuiteSparse without OpenMP. It looks like no one's added the variant yet. I've already started, so I should have a notional PR in an hour or two.

**Comment by davydden** [comment]
as for Apple's Clang, to my knowledge it did not support openmp (as of late 2016). So throwing an error is perfectly legitimate IMO.

**Comment by goxberry** [comment]
@davydden I agree. I'm adding `conflicts('+openmp', when='%appleclang')` as a precaution.

**Comment by davydden** [comment]
> What about packages that actually don't work without openmp?

I am not aware of such packages. Suite-sparse is certainly not one of them. Hard requirement of Openmp there was introduced recently and is a BUG. I have it installed on my Sierra for ages.
