### ISSUE TITLE
unable to set cflags in package spec

### ISSUE THREAD

**Issue by carns** [LLNL/spack#45507]
### Steps to reproduce

I am trying to install Spack packages with the CFLAGS overridden to enable debugging symbols and disable optimizations.  I used to be able to do this (and similar one-off build flags) by setting `cflags` `cxxflags`, `cppflags`, and/or `ldflags` in the spec, but that doesn't seem to work now.

The problem isn't particular to uring; I just chose it as a reproducer here because the package recipe is simple and it doesn't have any elaborate dependencies.  This example shows me attempting to set the CFLAGS to `-g -O0` and then checking them to find that the build still used the package defaults, which in this case appears to be `-g -O3`.

```console
spack install liburing cflags="-g3 -O0" cppflags="-g3 -O0"
zcat (spack location -i liburing)/.spack/spack-build-out.txt.gz |grep "\-O" |head -n 3

/home/carns/working/src/spack/lib/spack/env/gcc/gcc -D_GNU_SOURCE -Iinclude/ -include ../config-host.h -MT "setup.ol" -MMD -MP -MF "setup.ol.d" -g -O3 -Wall -Wextra -fno-stack-protector -Wno-unused-parameter -Wno-sign-compare -DLIBURING_INTERNAL  -c -o setup.ol setup.c
/home/carns/working/src/spack/lib/spack/env/gcc/gcc -D_GNU_SOURCE -Iinclude/ -include ../config-host.h -MT "queue.ol" -MMD -MP -MF "queue.ol.d" -g -O3 -Wall -Wextra -fno-stack-protector -Wno-unused-parameter -Wno-sign-compare -DLIBURING_INTERNAL  -c -o queue.ol queue.c
/home/carns/working/src/spack/lib/spack/env/gcc/gcc -D_GNU_SOURCE -Iinclude/ -include ../config-host.h -MT "register.ol" -MMD -MP -MF "register.ol.d" -g -O3 -Wall -Wextra -fno-stack-protector -Wno-unused-parameter -Wno-sign-compare -DLIBURING_INTERNAL  -c -o register.ol register.c
```

I've also reproduced this with packages that use Cmake, and packages that use C++ compilers rather than C compilers.

I do not see any relevant additional information in debug mode.

### Error message

No error messages are produced.

### Information on your system

```console
spack debug report                  e: none
* **Spack:** 0.23.0.dev0 (b8d10916af1ddf4b6beb543600f173d35d39d008)
* **Python:** 3.12.3
* **Platform:** linux-ubuntu24.04-skylake
* **Concretizer:** clingo
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by scheibelp** [comment]
Can you add the output of `spack spec`? That ends up looking pretty close to your original command:

```
spack spec liburing cflags="-g3 -O0" cppflags="-g3 -O0"
```

I want to check if this is an issue with the spec before the build, or if it's a matter of the build system not listening to whatever flags Spack tries to tell it to use.

**Comment by carns** [comment]
Sure thing: 
```carns-x1-11g ~> spack spec liburing cflags="-g3 -O0" cppflags="-g3 -O0" 
Input spec
--------------------------------
 -   liburing cflags='-g3 -O0' cppflags='-g3 -O0' 

Concretized
--------------------------------
 -   liburing@2.3%gcc@13.2.0 cflags='-g3 -O0' cppflags='-g3 -O0'  build_system=autotools arch=linux-ubuntu24.04-skylake
[+]      ^gcc-runtime@13.2.0%gcc@13.2.0 build_system=generic arch=linux-ubuntu24.04-skylake
[e]      ^glibc@2.39%gcc@13.2.0 build_system=autotools arch=linux-ubuntu24.04-skylake
[e]      ^gmake@4.3%gcc@13.2.0~guile build_system=generic patches=599f134 arch=linux-ubuntu24.04-skylake
```

**Comment by scheibelp** [comment]
I'm going to check if I can replicate this for `liburing` tomorrow

If you run `spack -d ...` then it will generate logs for the compiler wrapper invocations in your CWD. One thing I'm curious about, do the `spack-cc...out` logs contain any additional flags in your case?

**Comment by carns** [comment]
Oh, interesting!  Compare what shows up in the `spack-cc...out` with what shows up in `spack-build-out.txt.gz` for one of the source files:

```
carns-x1-11g ~> grep queue.c spack-cc-liburing-etguic7.out.log           e: none
[cc] /usr/bin/gcc -march=skylake -mtune=skylake -Iinclude/ -D_GNU_SOURCE -include ../config-host.h -MT queue.ol -MMD -MP -MF queue.ol.d -g -O3 -Wall -Wextra -fno-stack-protector -Wno-unused-parameter -Wno-sign-compare -DLIBURING_INTERNAL -c -o queue.ol queue.c -g3 -O0 -g3 -O0
[cc] /usr/bin/gcc -march=skylake -mtune=skylake -Iinclude/ -D_GNU_SOURCE -include ../config-host.h -MT queue.os -MMD -MP -MF queue.os.d -fPIC -g -O3 -Wall -Wextra -fno-stack-protector -Wno-unused-parameter -Wno-sign-compare -DLIBURING_INTERNAL -c -o queue.os queue.c -g3 -O0 -g3 -O0
```

```
carns-x1-11g ~/w/s/s/o/s/l/g/l/.spack (develop=) [1]> zcat spack-build-out.txt.gz |grep queue.c
/home/carns/working/src/spack/lib/spack/env/gcc/gcc -D_GNU_SOURCE -Iinclude/ -include ../config-host.h -MT "queue.ol" -MMD -MP -MF "queue.ol.d" -g -O3 -Wall -Wextra -fno-stack-protector -Wno-unused-parameter -Wno-sign-compare -DLIBURING_INTERNAL  -c -o queue.ol queue.c
/home/carns/working/src/spack/lib/spack/env/gcc/gcc -D_GNU_SOURCE -Iinclude/ -include ../config-host.h -MT "queue.os" -MMD -MP -MF "queue.os.d" -fPIC -g -O3 -Wall -Wextra -fno-stack-protector -Wno-unused-parameter -Wno-sign-compare -DLIBURING_INTERNAL  -c -o queue.os queue.c
```

The cflags (and cppflags, being redundant in this case) _do_ show up in the former, but they are tacked on to the end of the command line arguments instead of in the position that  you would expect.  In the latter they are gone.

**Comment by scheibelp** [comment]
Thanks for adding that info!

In short, I recommend setting

```
class Liburing(AutotoolsPackage):
     ...
    flag_handler = env_flags
```

* By default, Spack will insert flags into the compiler wrapper invocations. Because these are invoked at the lowest level, they typically aren't visible anywhere but in the logs generated by `spack -d`
* Our default mode for flag insertion is append, so that behavior is intended. For optimization flags, the last one wins, so I think that would work
* This flag insertion mechanism has no awareness of the build system, and vice versa. That often leads to duplicated/conflicting values for flags, so it can be useful to explicitly communicate flag settings to the build system
  * You can also set `flag_handler = build_system_flags`, but from looking up `liburing`, it appears to work with `CFLAGS` etc., and when I tested it myself with `liburing` that worked fine

Overall, we could start universally setting CFLAGS etc., which might avoid the need to edit this on a per-package basis

**Comment by carns** [comment]
Ok.  I think I'm asking the wrong question then.  How about this:

What is the recommended method to build an arbitrary package or set of packages (not necessarily liburing) with different compiler options (i.e., debugging symbols or address sanitizers)?

This is helpful for debugging problems that are most easily replicated when a package is built within a particular spack environment.  I could try to recreate the dependency versions and build options by hand, but of course this can be complex in some cases.  It would be easier if I could just pass it along to Spack somehow.

It doesn't have to be a particularly clean solution; this is only for debugging.  I'm happy to use custom environment yaml configurations, but I'd rather not alter package files if I can help it.

The reason for my more specific bug report is that at some point in the past I used to be able to do this with `cflags=` in the spec, but I don't necessarily need to use that method.

**Comment by scheibelp** [comment]
One thing I want to check: we've established at this point that the flags are actually added (although it's not logged well) and in an order that should work; is some post-install check you are doing implying that the flags did not in fact take effect though?

> The reason for my more specific bug report is that at some point in the past I used to be able to do this with cflags= in the spec, but I don't necessarily need to use that method.

Without editing the packages to insert flags, `cflags=` is the only mechanism we provide for inserting flags (e.g. we go out of our way to unset CFLAGS if it it appears in the env for the running spack instance). When you say we used to be able to do it, I might be confused, as this wrapper insertion mechanism has been the default for several years; the order of inserted flags changed about a year ago (in https://github.com/spack/spack/commit/7dc485d2887c70e3e1ebdc6f680cda926444da72 but in a way that would help.

> What is the recommended method to build an arbitrary package or set of packages (not necessarily liburing) with different compiler options (i.e., debugging symbols or address sanitizers)?

There is no one method for properly communicating flags to an arbitrary package. Our default method is inserting them via the low level wrappers; for `liburing` at least, they are inserted, and in an order where they would have precedence (both `-g3` and `-O0`) - so the end result appears to work with no modifications (but the logged invocations are either misleading or confusing, depending on what logs you examine - which is why I suggested `flag_handler = ...`).

**Comment by carns** [comment]
I don't know if I'll have time today, but I'll try a fresh build and get back to you.

The thing that prompted my bug report was that I built a package with the cflags discussed here, attempted to look at it in a debugger and found several things optimized out, then checked the spack-build-out.txt.gz and did not see the cflags I had specified.  I'll inspect the actual binary next time and make certain what is actually making it to the compilation stage.

**Comment by scheibelp** [comment]
> The thing that prompted my bug report was that I built a package with the cflags discussed here, attempted to look at it in a debugger and found several things optimized out

This definitely happens for some packages (e.g. if they bypass the spack compiler wrappers). We usually address on a case-by-case basis (and that usually seems like the best we can do). If you ~add~ mention a package where this occurs, I can try to reproduce it and make a suggestion on how to influence the build system (that generally involves modifying the package.py though).

**Comment by carns** [comment]
Ok!  I'm getting somewhere now.

First of all, me looking at `spack-build-out.txt.gz ` (and checking several packages that way) was a red herring for sure.  I did not realize that Spack was using a compiler wrapper that hid the `cflags` in that context.  I'm now just compiling packages and using `strings` on the resulting binary to look for the effective compiler flags that `gcc` actually ended up using.  That's probably available more elegantly from `readelf` or something but I can't figure out where.

The liburing package looks fine; the resulting library does indeed have -g3 set, and it's late enough in the ordering to override any other -g flags that were already present.

`darshan-util` is a little different (this is the original package that I was having a problem with.    If I build with `spack install darshan-util cflags="-g3 -O0"`, the resulting libdarshan-util.so looks like this (the flags are missing):

```
carns-x1-11g ~/w/s/s/o/s/l/g/d/lib (develop=)> strings libdarshan-util.so |grep "\-O"
GNU C17 13.2.0 -mtune=generic -march=x86-64 -g -O2 -fPIC -fasynchronous-unwind-tables -fstack-protector-strong -fstack-clash-protection -fcf-protection
```

I compared what's different about the `liburing` and `darshan-util` packages, and this is the key is https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/darshan-util/package.py#L85 where it sets `extra_args.append("CC=%s" % self.compiler.cc)`.  If I remove that and do the same spack install command, the resulting binary library looks correct:

```
carns-x1-11g ~/w/s/s/o/s/l/g/d/lib (develop *=)> strings libdarshan-util.so |grep "\-O"
GNU C17 13.2.0 -march=skylake -mtune=skylake -g -g3 -O2 -O0 -fPIC -fasynchronous-unwind-tables -fstack-protector-strong -fstack-clash-protection -fcf-protection
```

So!  It was package-specific after all; I apologize for the wild goose chase based on the Spack build logs, though I do think it would be better if it reflected the true build options.

@shanedsnyder will need to confirm, but I don't _think_ we actually need that line any more in this package; I think it may be a leftover artifact from an older autoconf arrangement.

I don't know if any other packages in Spack might be effected if they are manipulating that parameter and inadvertently dropping build flags that are set by the Spack wrapper.

**Comment by carns** [comment]
We've got a PR open to fix this issue in the Darshan package; closing this discussion.  That solves the bulk of our problem.

I think just for clarity it would help if the build logs were more transparent about the flags being passed to the compiler, but that's a less pressing issue for us.
