### ISSUE TITLE
Installation issue: binutils 2.42

### ISSUE THREAD

**Issue by fspiga** [LLNL/spack#45580]
### Steps to reproduce the issue

```console
spack install -j144 gcc@12.4.0%gcc
```

### Error message

<details><summary>Error message</summary>

<pre>
[filippos@ggcompile001 spack]$ spack install -j144 gcc@12.4.0%gcc
[+] /usr (external diffutils-3.7-i57yv7alkv22oo4pqagr6vwrxs2ri4vp)
[+] /usr (external glibc-2.34-7esimr4qq66vfzewcqvdzd42mg3q4u7i)
[+] /usr (external gmake-4.3-zey3wri6nvxypbodk32qczqsdwld2tvs)
[+] /usr (external pkgconf-1.7.3-pnzk4cz7oqre7oywd2dlqlj6njulvaxg)
[+] /usr (external zstd-1.5.1-rqn4uxmuc4rblst4lmgo4ajo7toof5h7)
[+] /usr (external gawk-5.1.0-mtpz2obqpwmtbsysdnlbleyh7tr6vtu5)
[+] /usr (external gmp-6.2.0-bn4hcakgdsuy5tslwmrpsczlgfg5ox2s)
[+] /usr (external libtool-2.4.6-ag2ueohwjtfl6jtzxmuun3rcfwhojswj)
[+] /usr (external mpc-1.2.1-koicsspjwkanhy3z6jabohihc6zyqbxy)
[+] /usr (external mpfr-4.1.0-dircf75ow2jyhfnrc63tsolf5rv2i7dz)
[+] /usr (external perl-5.32.1-dvntdzkdjd4jjdkhddsqxvxteu5atqo7)
[+] /usr (external texinfo-6.7-qv3eammgfudyw5fjj5vuevcfitigq2dn)
[+] /global/scratch/groups/gg/gg-sw-202408/spack/opt/spack/linux-rocky9-neoverse_v2/gcc-11.4.1/gcc-runtime-11.4.1-3ufyvbiso7l7xco4hu5fthtzv5yrx7lv
[+] /global/scratch/groups/gg/gg-sw-202408/spack/opt/spack/linux-rocky9-neoverse_v2/gcc-11.4.1/gnuconfig-2022-09-17-72xjbhookxjhwu2opvt5omhivgohibeg
[+] /global/scratch/groups/gg/gg-sw-202408/spack/opt/spack/linux-rocky9-neoverse_v2/gcc-11.4.1/zlib-ng-2.2.1-awfh4zuctykset2ubq3n7bnpairqyytj
==> Installing binutils-2.42-vuct2lizexr6n77ecmhuynuojwttblxe [16/17]
==> No binary for binutils-2.42-vuct2lizexr6n77ecmhuynuojwttblxe found: installing from source
==> Using cached archive: /global/scratch/groups/gg/gg-sw-202408/spack/var/spack/cache/_source-cache/archive/aa/aa54850ebda5064c72cd4ec2d9b056c294252991486350d9a97ab2a6dfdfaf12.tar.bz2
==> No patches needed for binutils
==> binutils: Executing phase: 'autoreconf'
==> Error: AttributeError: 'AutotoolsBuilder' object has no attribute 'name'

The 'binutils' package cannot find an attribute while trying to build from sources. This might be due to a change in Spack's package format to support multiple build-systems for a single package. You can fix this by updating the build recipe, and you can also report the issue as a bug. More information at https://spack.readthedocs.io/en/latest/packaging_guide.html#installation-procedure

/global/scratch/groups/gg/gg-sw-202408/spack/lib/spack/spack/build_systems/autotools.py:298, in _do_patch_config_files:
        295   `config.sub` files.
        296"""
        297            raise spack.build_environment.InstallError(
  >>    298                msg.format(", ".join(to_be_found), self.name)
        299            )
        300
        301        # Copy the good files over the bad ones

See build log for details:
  /tmp/filippos/spack-stage/spack-stage-binutils-2.42-vuct2lizexr6n77ecmhuynuojwttblxe/spack-build-out.txt

==> Warning: Skipping build of gcc-12.4.0-5m66ttqpnmhubs2yqc3apz22ucilmm6b since binutils-2.42-vuct2lizexr6n77ecmhuynuojwttblxe failed
==> Error: gcc-12.4.0-5m66ttqpnmhubs2yqc3apz22ucilmm6b: Package was not installed
==> Error: Installation request failed.  Refer to reported errors for failing package(s).
</pre></details>

### Information on your system

* **Spack:** 0.23.0.dev0 (0257b2db4bb2539c103fe324435bb9e14eaa0644)
* **Python:** 3.9.18
* **Platform:** linux-rocky9-neoverse_v2
* **Concretizer:** clingo

### Additional information

From `packages.yaml`:
```
  gcc:
    variants: +binutils
    require:
    - "%gcc@11"
  binutils:
    variants: +gas+gold~gprofng+headers~interwork+ld~libiberty~lto~nls~pgo+plugins build_system=autotools compress_debug_sections=zlib libs=shared,static
    require:
    - "@2.42"
    - "%gcc@11"
 ```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by fspiga** [comment]
This is a bit annoying problem. I want to force `gcc` to build with a new binutils (`gcc@12.4.0%gcc +binutils`) to better support Neoverse V2 and this problem blocks in cascade to refresh anything else.

**Comment by fspiga** [comment]
The problem persists if built standalone:

```
[filippos@ggcompile001 gg-sw-202408]$ spack spec -I binutils@2.41

Input spec
--------------------------------
 -   binutils@2.41

Concretized
--------------------------------
 -   binutils@2.41%gcc@11.4.1~gas~gprofng~headers~interwork~ld~libiberty~lto~nls~pgo+plugins build_system=autotools compress_debug_sections=zlib libs=shared,static arch=linux-rocky9-neoverse_v2
[e]      ^diffutils@3.7%gcc@11.4.1 build_system=autotools arch=linux-rocky9-neoverse_v2
[+]      ^gcc-runtime@11.4.1%gcc@11.4.1 build_system=generic arch=linux-rocky9-neoverse_v2
[e]      ^glibc@2.34%gcc@11.4.1 build_system=autotools arch=linux-rocky9-neoverse_v2
[e]      ^gmake@4.3%gcc@11.4.1~guile build_system=generic patches=599f134 arch=linux-rocky9-neoverse_v2
[+]      ^gnuconfig@2022-09-17%gcc@11.4.1 build_system=generic arch=linux-rocky9-neoverse_v2
[e]      ^pkgconf@1.7.3%gcc@11.4.1 build_system=autotools arch=linux-rocky9-neoverse_v2
[+]      ^zlib-ng@2.2.1%gcc@11.4.1+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-rocky9-neoverse_v2
[e]      ^zstd@1.5.1%gcc@11.4.1~programs build_system=makefile libs=shared,static arch=linux-rocky9-neoverse_v2

[filippos@ggcompile001 gg-sw-202408]$
[filippos@ggcompile001 gg-sw-202408]$ spack install -j144 binutils@2.41

[+] /usr (external diffutils-3.7-i57yv7alkv22oo4pqagr6vwrxs2ri4vp)
[+] /usr (external glibc-2.34-7esimr4qq66vfzewcqvdzd42mg3q4u7i)
[+] /usr (external gmake-4.3-zey3wri6nvxypbodk32qczqsdwld2tvs)
[+] /usr (external pkgconf-1.7.3-pnzk4cz7oqre7oywd2dlqlj6njulvaxg)
[+] /usr (external zstd-1.5.1-rqn4uxmuc4rblst4lmgo4ajo7toof5h7)
[+] /global/scratch/groups/gg/gg-sw-202408/spack/opt/spack/linux-rocky9-neoverse_v2/gcc-11.4.1/gcc-runtime-11.4.1-3ufyvbiso7l7xco4hu5fthtzv5yrx7lv
[+] /global/scratch/groups/gg/gg-sw-202408/spack/opt/spack/linux-rocky9-neoverse_v2/gcc-11.4.1/zlib-ng-2.2.1-awfh4zuctykset2ubq3n7bnpairqyytj
[+] /global/scratch/groups/gg/gg-sw-202408/spack/opt/spack/linux-rocky9-neoverse_v2/gcc-11.4.1/gnuconfig-2022-09-17-72xjbhookxjhwu2opvt5omhivgohibeg
==> Installing binutils-2.41-j6anbclh2f5nkq5al5v4wz3hqadphpuo [9/9]
==> No binary for binutils-2.41-j6anbclh2f5nkq5al5v4wz3hqadphpuo found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/a4/a4c4bec052f7b8370024e60389e194377f3f48b56618418ea51067f67aaab30b.tar.bz2
==> No patches needed for binutils
==> binutils: Executing phase: 'autoreconf'
==> Error: AttributeError: 'AutotoolsBuilder' object has no attribute 'name'

The 'binutils' package cannot find an attribute while trying to build from sources. This might be due to a change in Spack's package format to support multiple build-systems for a single package. You can fix this by updating the build recipe, and you can also report the issue as a bug. More information at https://spack.readthedocs.io/en/latest/packaging_guide.html#installation-procedure

/global/scratch/groups/gg/gg-sw-202408/spack/lib/spack/spack/build_systems/autotools.py:298, in _do_patch_config_files:
        295   `config.sub` files.
        296"""
        297            raise spack.build_environment.InstallError(
  >>    298                msg.format(", ".join(to_be_found), self.name)
        299            )
        300
        301        # Copy the good files over the bad ones

See build log for details:
  /tmp/filippos/spack-stage/spack-stage-binutils-2.41-j6anbclh2f5nkq5al5v4wz3hqadphpuo/spack-build-out.txt
```

**spack-build-out.txt:**
```
cat   /tmp/filippos/spack-stage/spack-stage-binutils-2.41-j6anbclh2f5nkq5al5v4wz3hqadphpuo/spack-build-out.txt
==> binutils: Executing phase: 'autoreconf'
==> [2024-08-05-08:58:33.034923] Find (recursive): /tmp/filippos/spack-stage/spack-stage-binutils-2.41-j6anbclh2f5nkq5al5v4wz3hqadphpuo ['config.sub', 'config.guess']
==> [2024-08-05-08:58:33.055280] Find complete: /tmp/filippos/spack-stage/spack-stage-binutils-2.41-j6anbclh2f5nkq5al5v4wz3hqadphpuo ['config.sub', 'config.guess']
==> [2024-08-05-08:58:33.075921] CalledProcessError: Command '['/tmp/filippos/spack-stage/spack-stage-binutils-2.41-j6anbclh2f5nkq5al5v4wz3hqadphpuo/spack-src/config.guess']' returned non-zero exit status 1.
==> [2024-08-05-08:58:33.076518] Find (not recursive): /global/scratch/groups/gg/gg-sw-202408/spack/opt/spack/linux-rocky9-neoverse_v2/gcc-11.4.1/gnuconfig-2022-09-17-72xjbhookxjhwu2opvt5omhivgohibeg ['config.guess']
==> [2024-08-05-08:58:33.076721] Find complete: /global/scratch/groups/gg/gg-sw-202408/spack/opt/spack/linux-rocky9-neoverse_v2/gcc-11.4.1/gnuconfig-2022-09-17-72xjbhookxjhwu2opvt5omhivgohibeg ['config.guess']
==> [2024-08-05-08:58:33.092431] CalledProcessError: Command '['/global/scratch/groups/gg/gg-sw-202408/spack/opt/spack/linux-rocky9-neoverse_v2/gcc-11.4.1/gnuconfig-2022-09-17-72xjbhookxjhwu2opvt5omhivgohibeg/config.guess']' returned non-zero exit status 1.
```

**Comment by alalazo** [comment]
Why "breaking-change"? :slightly_smiling_face: (I removed that, we usually use that label to mark PRs that introduce breaking changes in core Spack)

**Comment by fspiga** [comment]
The issue was on my side, something changes on the filesystem and I was not notified. I spot this when I tried to build another package.
