### ISSUE TITLE
How to handle non-installed options/targets

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/spack#4562]
I am thinking of adding a `+examples` variant to MFEM so that it can build, optionally, all of MFEM's examples. 

On the one hand, this makes life simpler for me. OTOH, adding such a variant, which does nothing to affect how the package is installed, is probably totally meaningless to Spack.

What is the right answer here? Avoid adding stuff to packages that have nothing to do with installing said pacakges (e.g. outcome of `make install` is no different either way)? Or, this is ok and/or encouraged?

**Comment by alalazo** [comment]
If the examples are not applications that will be installed but are just a way to check that the package is working correctly, then I would avoid having a variant and I would encode their build as a part of the optional tests that could be run during the installation:
```console
$ spack install --run-tests mfem
```

**Comment by adamjstewart** [comment]
The closest discussions I could find are #169, #1169, and #3923. But @markcmiller86 seems to already understand the rationale, variants are variations of installed packages. If the examples flag doesn't change what gets installed, it shouldn't be a variant. However, there are several packages in Spack that do have an `+examples` variant:
```
$ grep variant.*examples */package.py
adol-c/package.py:    variant('examples', default=True,  description='Install examples')
flann/package.py:    variant("examples", default=False, description="Build the examples.")
moab/package.py:    # There are many possible variants for MOAB. Here are examples for
pagmo/package.py:    variant('examples', default=False, description='Build examples')
pagmo/package.py:            '-DBUILD_EXAMPLES={0}'.format(self.variant_to_bool('+examples')),
qt/package.py:    variant('examples',   default=False,
stat/package.py:    variant('examples', default=False, description="enable examples")
```
If the examples are installed, I'm fine with that variant being present. If the examples aren't installed and their only purpose is to test the installation, you can instead do something like:
```python
if self.run_tests:
    args.append('--enable-examples')
else:
    args.append('--disable-examples')
```
in `configure_args` or whatever you are using.

**Comment by markcmiller86** [comment]
That all makes perfect sense to me. Wasn't aware of the `self.run_tests` thingy though. That helps a lot. 

But, what if I want to keep those around *after* `spack install` has completed. I am guessing right answer is to also `--keep-stage`

**Comment by adamjstewart** [comment]
Yes, if you run `spack install --keep-stage mfem` it will keep those examples around, at least until you delete the stage with `spack purge`. If you think it would be wise to install the examples, there's no reason you can't add a `+examples` variant that optionally installs the examples. See the `install_tree` method for this.

**Comment by markcmiller86** [comment]
Ok, thanks. I actually like the idea of having it install the examples even if the package's `make install` isn't necessarily designed to do that.
