### ISSUE TITLE
SAMRAI undefined variable build error

### ISSUE THREAD

**Issue by benjaminjeliot** [LLNL/spack#4564]
The SAMRAI package fails to build due to an undefined variable in package.py.

It looks like line 84 of package.py should be "if '+debug' in self.spec:" instead of "if '+debug' in spec:".

**Comment by tgamblin** [comment]
That looks like the fix to me, too -- want to submit a PR for this?

**Comment by benjaminjeliot** [comment]
Yeah, I'm working on it

**Comment by adamjstewart** [comment]
Closed by #4565

**Comment by tgamblin** [comment]
Thanks @benjaminjeliot!
