### ISSUE TITLE
libmng fails to build on rzmanta (power 8) when trying to build the default qt qt5 package or in the case below where I tried to build qt@4.8.6.

### ISSUE THREAD

**Issue by jgalarowicz** [LLNL/spack#4571]
libmng fails to build on rzmanta (power 8) when trying to build the default qt qt5 package or in the case below where I tried to build qt@4.8.6.
```
rzmanta23{jeg}95: spack install qt@4.8.6%gcc@4.9.3
==> libffi is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/libffi-3.2.1-koz6ilfnimuamh36wagjaomek4jefunq
==> pcre is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/pcre-8.40-i24p6qpn7f2srcwvoqcaoqlqezeyfc4f
==> zlib is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/zlib-1.2.11-p4bioy6xvjuc7df3khprcblqmfqxta6u
==> ncurses is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/ncurses-6.0-z3yrrfqe5k72cfw5ibrusybwvjp7uxro
==> libxml2 is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/libxml2-2.9.4-auvw2hu5ifah67gf22n5tcnsg475lb6l
==> bzip2 is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/bzip2-1.0.6-afxnmm6v4scy5ojncsdxm2pjf4buf5zt
==> xz is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/xz-5.2.3-juummrlqltu3vhsamztx2jh5ft4y2det
==> tar is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/tar-1.29-aulseurrgx7dsgsqsjgrdfgnmtxumcoj
==> Installing gettext
==> Using cached archive: /usr/global/tools/openspeedshop/oss-dev/spack/var/spack/cache/gettext/gettext-0.19.8.1.tar.xz
==> Staging archive: /usr/global/tools/openspeedshop/oss-dev/spack/var/spack/stage/gettext-0.19.8.1-fwlkr3rti572q2wsqvlqvek6a5f4jepj/gettext-0.19.8.1.tar.xz
==> Created stage in /usr/global/tools/openspeedshop/oss-dev/spack/var/spack/stage/gettext-0.19.8.1-fwlkr3rti572q2wsqvlqvek6a5f4jepj
==> Applied patch test-verify-parallel-make-check.patch
==> Ran patch() for gettext
==> Building gettext [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Executing phase : 'configure'
==> Executing phase : 'build'
==> Executing phase : 'install'
==> Successfully installed gettext
  Fetch: 0.07s.  Build: 3m 17.47s.  Total: 3m 17.54s.
[+] /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/gettext-0.19.8.1-fwlkr3rti572q2wsqvlqvek6a5f4jepj
==> pkg-config is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/pkg-config-0.29.2-qqswtyqkpsz2cgarcxwqx7nxgsicrlem
==> Installing glib
==> Using cached archive: /usr/global/tools/openspeedshop/oss-dev/spack/var/spack/cache/glib/glib-2.53.1.tar.xz
==> Staging archive: /usr/global/tools/openspeedshop/oss-dev/spack/var/spack/stage/glib-2.53.1-pmbhbpw45m4ocb67vt55sldtzsofmqrk/glib-2.53.1.tar.xz
==> Created stage in /usr/global/tools/openspeedshop/oss-dev/spack/var/spack/stage/glib-2.53.1-pmbhbpw45m4ocb67vt55sldtzsofmqrk
==> Applied patch no-Werror=format-security.patch
==> Ran patch() for glib
==> Building glib [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Executing phase : 'configure'
==> Executing phase : 'build'
==> Executing phase : 'install'
==> Successfully installed glib
  Fetch: 0.08s.  Build: 1m 14.79s.  Total: 1m 14.87s.
[+] /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/glib-2.53.1-pmbhbpw45m4ocb67vt55sldtzsofmqrk
==> freetype is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/freetype-2.7.1-6riwnbtyysii3lwe22jkzx2uszc5jmnc
==> libx11 is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/libx11-1.6.5-pubxxiurkbpysgjh2fz3tjfxzut5jkwr
==> libxml2 is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/libxml2-2.9.4-auvw2hu5ifah67gf22n5tcnsg475lb6l
==> libtiff is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/libtiff-4.0.7-udmro3xeljxd3zpdjj5nddiuatrqz5j7
==> zlib is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/zlib-1.2.11-p4bioy6xvjuc7df3khprcblqmfqxta6u
==> Installing openssl
==> Using cached archive: /usr/global/tools/openspeedshop/oss-dev/spack/var/spack/cache/openssl/openssl-1.0.2k.tar.gz
==> Staging archive: /usr/global/tools/openspeedshop/oss-dev/spack/var/spack/stage/openssl-1.0.2k-rrstyyjndf4lkwober25ujfc5atbk6an/openssl-1.0.2k.tar.gz
==> Created stage in /usr/global/tools/openspeedshop/oss-dev/spack/var/spack/stage/openssl-1.0.2k-rrstyyjndf4lkwober25ujfc5atbk6an
==> Ran patch() for openssl
==> Building openssl [Package]
==> Executing phase : 'install'
==> Successfully installed openssl
  Fetch: 0.05s.  Build: 3m 27.97s.  Total: 3m 28.03s.
[+] /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/openssl-1.0.2k-rrstyyjndf4lkwober25ujfc5atbk6an
==> jpeg is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/jpeg-9b-ptvkqetyhl7n6zm2unbttvvsisu7i5gk
==> icu4c is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/icu4c-58.2-vlumxqmwjd4ykish25fkxxjkt2abkvfx
==> zlib is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/zlib-1.2.11-p4bioy6xvjuc7df3khprcblqmfqxta6u
==> libxcb is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/libxcb-1.12-x5f4fsty7oa6a46vq62dlvv5uggqee22
==> libpng is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/libpng-1.6.29-k3fy52d53abe2g4ch242lpqmn5lcsojn
==> zlib is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/zlib-1.2.11-p4bioy6xvjuc7df3khprcblqmfqxta6u
==> jpeg is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/jpeg-9b-ptvkqetyhl7n6zm2unbttvvsisu7i5gk
==> lcms is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/lcms-2.8-goiy5qz3bdbmkcpr5gzmad7ml7xpwqrz
==> Installing libmng
==> Using cached archive: /usr/global/tools/openspeedshop/oss-dev/spack/var/spack/cache/libmng/libmng-2.0.2.tar.gz
==> Already staged libmng-2.0.2-vopezpq5mdia7sfmr5yfa6ujgb7lg7yg in /usr/global/tools/openspeedshop/oss-dev/spack/var/spack/stage/libmng-2.0.2-vopezpq5mdia7sfmr5yfa6ujgb7lg7yg
==> Already patched libmng
==> Building libmng [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Executing phase : 'configure'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j160' 'distclean'
/usr/global/tools/openspeedshop/oss-dev/spack/var/spack/repos/builtin/packages/libmng/package.py:48, in clean_configure_directory:
     46       @run_before('configure')
     47       def clean_configure_directory(self):
  >> 48           make('distclean')

See build log for details:
  /var/tmp/jeg/spack-stage/spack-stage-wEbCpp/libmng-2.0.2/spack-build.out
rzmanta23{jeg}96: 

rzmanta23{jeg}32: cat   /var/tmp/jeg/spack-stage/spack-stage-wEbCpp/libmng-2.0.2/spack-build.out
==> 'make' '-j160' 'distclean'
make: *** No rule to make target 'distclean'.  Stop.
```
This page doesn't mention doing a "make distclean"
http://www.linuxfromscratch.org/blfs/view/cvs/general/libmng.html

**Comment by adamjstewart** [comment]
I think I know what the problem is. I'll bet you tried to build this package, it ran `make distclean` which deletes the Makefile, then it crashed somewhere. Now you are trying to install again and when it runs `make distclean` there is no Makefile to process. Let me try removing that line and make sure it still works.

**Comment by adamjstewart** [comment]
When I try to run the package without that line, `configure` crashes with:
```
configure: error: source directory already configured; run "make distclean" there first
```
So we can't simply remove that line.

**Comment by adamjstewart** [comment]
Let me see if this has been fixed in the newer release.

**Comment by adamjstewart** [comment]
Nope, latest release has the same bug. If we don't run `make distclean`, `configure` crashes. Can you try running `spack purge` and then `spack install -v libmng`?

**Comment by adamjstewart** [comment]
Oddly enough, `configure` works if I just download the tarball and run it outside of Spack, but in Spack it results in that error message. Can anyone else reproduce this? @alalazo

**Comment by jgalarowicz** [comment]
Here is the install -v output:

    50	10:34	spack purge

rzmanta23{jeg}53: spack install -v libmng%gcc@4.9.3
==> zlib is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/zlib-1.2.11-p4bioy6xvjuc7df3khprcblqmfqxta6u
==> jpeg is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/jpeg-9b-ptvkqetyhl7n6zm2unbttvvsisu7i5gk
==> lcms is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/lcms-2.8-goiy5qz3bdbmkcpr5gzmad7ml7xpwqrz
==> Installing libmng
==> Using cached archive: /usr/global/tools/openspeedshop/oss-dev/spack/var/spack/cache/libmng/libmng-2.0.2.tar.gz
==> Staging archive: /usr/global/tools/openspeedshop/oss-dev/spack/var/spack/stage/libmng-2.0.2-vopezpq5mdia7sfmr5yfa6ujgb7lg7yg/libmng-2.0.2.tar.gz
==> Created stage in /usr/global/tools/openspeedshop/oss-dev/spack/var/spack/stage/libmng-2.0.2-vopezpq5mdia7sfmr5yfa6ujgb7lg7yg
==> Ran patch() for libmng
==> Building libmng [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Executing phase : 'configure'
==> 'make' '-j160' 'distclean'
test -z "libmng.la" || rm -f libmng.la
rm -rf .libs _libs
rm -f *.o
rm -f *.lo
rm -f *.tab.c
test -z "libmng.pc" || rm -f libmng.pc
rm -f config.h stamp-h1
rm -f libtool config.lt
rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
rm -f cscope.out cscope.in.out cscope.po.out cscope.files
test . = "." || test -z "" || rm -f 
rm -f ./so_locations
rm -f config.status config.cache config.log configure.lineno config.status.lineno
rm -f Makefile
==> '/usr/global/tools/openspeedshop/oss-dev/spack/var/spack/stage/libmng-2.0.2-vopezpq5mdia7sfmr5yfa6ujgb7lg7yg/libmng-2.0.2/configure' '--prefix=/usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/libmng-2.0.2-vopezpq5mdia7sfmr5yfa6ujgb7lg7yg'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... /usr/global/tools/openspeedshop/oss-dev/spack/lib/spack/env/gcc/gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/global/tools/openspeedshop/oss-dev/spack/lib/spack/env/gcc/gcc accepts -g... yes
checking for /usr/global/tools/openspeedshop/oss-dev/spack/lib/spack/env/gcc/gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of /usr/global/tools/openspeedshop/oss-dev/spack/lib/spack/env/gcc/gcc... none
checking for library containing strerror... none required
checking build system type... /usr/global/tools/openspeedshop/oss-dev/spack/var/spack/stage/libmng-2.0.2-vopezpq5mdia7sfmr5yfa6ujgb7lg7yg/libmng-2.0.2/config.guess: unable to guess system type

This script, last modified 2012-12-29, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
and
  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD

If the version you run (/usr/global/tools/openspeedshop/oss-dev/spack/var/spack/stage/libmng-2.0.2-vopezpq5mdia7sfmr5yfa6ujgb7lg7yg/libmng-2.0.2/config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2012-12-29

uname -m = ppc64le
uname -r = 3.10.0-514.16.1.1chaos.ch6_1.ppc64le
uname -s = Linux
uname -v = #1 SMP Wed Apr 26 15:30:05 PDT 2017

/usr/bin/uname -p = ppc64le
/bin/uname -X     = 

hostinfo               = 
/bin/universe          = 
/usr/bin/arch -k       = 
/bin/arch              = ppc64le
/usr/bin/oslevel       = 
/usr/convex/getsysinfo = 

UNAME_MACHINE = ppc64le
UNAME_RELEASE = 3.10.0-514.16.1.1chaos.ch6_1.ppc64le
UNAME_SYSTEM  = Linux
UNAME_VERSION = #1 SMP Wed Apr 26 15:30:05 PDT 2017
configure: error: cannot guess build type; you must specify one
==> Error: ProcessError: Command exited with status 1:
    '/usr/global/tools/openspeedshop/oss-dev/spack/var/spack/stage/libmng-2.0.2-vopezpq5mdia7sfmr5yfa6ujgb7lg7yg/libmng-2.0.2/configure' '--prefix=/usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/libmng-2.0.2-vopezpq5mdia7sfmr5yfa6ujgb7lg7yg'
/usr/global/tools/openspeedshop/oss-dev/spack/lib/spack/spack/build_systems/autotools.py:266, in configure:
     258      def configure(self, spec, prefix):
     259          """Runs configure with the arguments specified in
     260          :py:meth:`~.AutotoolsPackage.configure_args`
     261          and an appropriately set prefix.
     262          """
     263          options = ['--prefix={0}'.format(prefix)] + self.configure_args()
     264  
     265          with working_dir(self.build_directory, create=True):
  >> 266              inspect.getmodule(self).configure(*options)

See build log for details:
  /var/tmp/jeg/spack-stage/spack-stage-I5hnll/libmng-2.0.2/spack-build.out
rzma    50	10:34	spack purge
    51	10:34	spack install -v libmng@gcc.4.9.3
    52	10:36	wdid
rzmanta23{jeg}53: spack install -v libmng%gcc@4.9.3
==> zlib is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/zlib-1.2.11-p4bioy6xvjuc7df3khprcblqmfqxta6u
==> jpeg is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/jpeg-9b-ptvkqetyhl7n6zm2unbttvvsisu7i5gk
==> lcms is already installed in /usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/lcms-2.8-goiy5qz3bdbmkcpr5gzmad7ml7xpwqrz
==> Installing libmng
==> Using cached archive: /usr/global/tools/openspeedshop/oss-dev/spack/var/spack/cache/libmng/libmng-2.0.2.tar.gz
==> Staging archive: /usr/global/tools/openspeedshop/oss-dev/spack/var/spack/stage/libmng-2.0.2-vopezpq5mdia7sfmr5yfa6ujgb7lg7yg/libmng-2.0.2.tar.gz
==> Created stage in /usr/global/tools/openspeedshop/oss-dev/spack/var/spack/stage/libmng-2.0.2-vopezpq5mdia7sfmr5yfa6ujgb7lg7yg
==> Ran patch() for libmng
==> Building libmng [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Executing phase : 'configure'
==> 'make' '-j160' 'distclean'
test -z "libmng.la" || rm -f libmng.la
rm -rf .libs _libs
rm -f *.o
rm -f *.lo
rm -f *.tab.c
test -z "libmng.pc" || rm -f libmng.pc
rm -f config.h stamp-h1
rm -f libtool config.lt
rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags
rm -f cscope.out cscope.in.out cscope.po.out cscope.files
test . = "." || test -z "" || rm -f 
rm -f ./so_locations
rm -f config.status config.cache config.log configure.lineno config.status.lineno
rm -f Makefile
==> '/usr/global/tools/openspeedshop/oss-dev/spack/var/spack/stage/libmng-2.0.2-vopezpq5mdia7sfmr5yfa6ujgb7lg7yg/libmng-2.0.2/configure' '--prefix=/usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/libmng-2.0.2-vopezpq5mdia7sfmr5yfa6ujgb7lg7yg'
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... /usr/global/tools/openspeedshop/oss-dev/spack/lib/spack/env/gcc/gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether /usr/global/tools/openspeedshop/oss-dev/spack/lib/spack/env/gcc/gcc accepts -g... yes
checking for /usr/global/tools/openspeedshop/oss-dev/spack/lib/spack/env/gcc/gcc option to accept ISO C89... none needed
checking for style of include used by make... GNU
checking dependency style of /usr/global/tools/openspeedshop/oss-dev/spack/lib/spack/env/gcc/gcc... none
checking for library containing strerror... none required
checking build system type... /usr/global/tools/openspeedshop/oss-dev/spack/var/spack/stage/libmng-2.0.2-vopezpq5mdia7sfmr5yfa6ujgb7lg7yg/libmng-2.0.2/config.guess: unable to guess system type

This script, last modified 2012-12-29, has failed to recognize
the operating system you are using. It is advised that you
download the most up to date version of the config scripts from

  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.guess;hb=HEAD
and
  http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD

If the version you run (/usr/global/tools/openspeedshop/oss-dev/spack/var/spack/stage/libmng-2.0.2-vopezpq5mdia7sfmr5yfa6ujgb7lg7yg/libmng-2.0.2/config.guess) is already up to date, please
send the following data and any information you think might be
pertinent to <config-patches@gnu.org> in order to provide the needed
information to handle your system.

config.guess timestamp = 2012-12-29

uname -m = ppc64le
uname -r = 3.10.0-514.16.1.1chaos.ch6_1.ppc64le
uname -s = Linux
uname -v = #1 SMP Wed Apr 26 15:30:05 PDT 2017

/usr/bin/uname -p = ppc64le
/bin/uname -X     = 

hostinfo               = 
/bin/universe          = 
/usr/bin/arch -k       = 
/bin/arch              = ppc64le
/usr/bin/oslevel       = 
/usr/convex/getsysinfo = 

UNAME_MACHINE = ppc64le
UNAME_RELEASE = 3.10.0-514.16.1.1chaos.ch6_1.ppc64le
UNAME_SYSTEM  = Linux
UNAME_VERSION = #1 SMP Wed Apr 26 15:30:05 PDT 2017
configure: error: cannot guess build type; you must specify one
==> Error: ProcessError: Command exited with status 1:
    '/usr/global/tools/openspeedshop/oss-dev/spack/var/spack/stage/libmng-2.0.2-vopezpq5mdia7sfmr5yfa6ujgb7lg7yg/libmng-2.0.2/configure' '--prefix=/usr/global/tools/openspeedshop/oss-dev/spack/opt/spack/linux-rhel7-ppc64le/gcc-4.9.3/libmng-2.0.2-vopezpq5mdia7sfmr5yfa6ujgb7lg7yg'
/usr/global/tools/openspeedshop/oss-dev/spack/lib/spack/spack/build_systems/autotools.py:266, in configure:
     258      def configure(self, spec, prefix):
     259          """Runs configure with the arguments specified in
     260          :py:meth:`~.AutotoolsPackage.configure_args`
     261          and an appropriately set prefix.
     262          """
     263          options = ['--prefix={0}'.format(prefix)] + self.configure_args()
     264  
     265          with working_dir(self.build_directory, create=True):
  >> 266              inspect.getmodule(self).configure(*options)

See build log for details:
  /var/tmp/jeg/spack-stage/spack-stage-I5hnll/libmng-2.0.2/spack-build.out
rzmanta23{jeg}54: 
nta23{jeg}54:

**Comment by adamjstewart** [comment]
Awesome, so `spack purge` gets you past the original error message. Now the problem is that the `config.guess` doesn't recognize PowerPC. @lee218llnl You wrote the `patch_config_guess` logic in #2221 right? Can you take a look at this package? Perhaps we need to separate that logic out of `patch`, which may be overriden by the package.

**Comment by jgalarowicz** [comment]
I bet the config.sub and config.guess files don't have power8 in the list.

configure:3859: result: none required
configure:3896: checking build system type
configure:3905: error: cannot guess build type; you must specify one

## ---------------- ##

**Comment by jgalarowicz** [comment]
Oops, I see you found that out as well.

**Comment by jgalarowicz** [comment]
I replaced the config.sub and config.guess with newer versions - in the spack build directory and was able to build it and get past this issue temporarily on this particular machine.  I guess I could create a patch to the default tarball source that basically replaces the config.sub and config.guess with the latest gnu versions of those files.

**Comment by adamjstewart** [comment]
@jgalarowicz There's already a `patch_config_guess` function in the `AutotoolsPackage` base class that @lee218llnl wrote that does just that. We just need to get it working for `libmng`.

**Comment by lee218llnl** [comment]
I create a PR to fix this. We can and perhaps should patch config.guess ASAP (i.e., after autoreconf) to catch cases like this. I will say, however, that libmng is evil for shipping with pre-configured Makefiles.

**Comment by adamjstewart** [comment]
@jgalarowicz Can you see if this is fixed now that #4604 has been merged?

**Comment by jgalarowicz** [comment]
@adamjstewart Sorry I didn't see this.  I will try today.

**Comment by jgalarowicz** [comment]
@adamjstewart This works (I can build libmng) on the Power 8 rzmanta system.
