### ISSUE TITLE
Cryptic "Error: 'name'" error when trying to build any package using spack on linux-rhel8-broadwell

### ISSUE THREAD

**Issue by ikalash** [LLNL/spack#45768]
### Steps to reproduce

```spack install cmake```

### Error message

```spack install cmake
==> Error: 'name'
```

### Information on your system

I just tried building some packages using spack on a ```linux-rhel8-broadwell``` system.  No matter what package I try to build, I get the cryptic error message: 
```
spack install cmake
==> Error: 'name'
```
Could you please help me figure out what is causing this?  I am attaching the log generated when I run ```spack -d list```.  Is the issue with the ```arch``` that is being set, which I think is different from other machine where I have used spack?

I am using spack 0.23.0.dev0 (dd53eeb32272cb912234382af52c586c1158d65f).

[log.txt](https://github.com/user-attachments/files/16620318/log.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
@ikalash Looking at the log, can you try:
```console
$ spack clean -a
```
and retry the command ? Does it make any difference?

**Comment by ikalash** [comment]
This fixed it.  Thank you!  I will close the issue.
