### ISSUE TITLE
Compiler-Independent Packages

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#458]
Some packages don't depend on which compiler you used to compile them (or they don't involve a compiler at all).  For example... I installed gcc@4.9.3.  The GCC bootstrap process compiles the compiler with itself, so it doesn't matter what compiler you started off with.

However... I'm getting it installed in a directory like this:
    ~spack/linux-x86_64/gcc-4.8.5/gcc-4.9.3-layphctulnk3omsbjpzftqv6dlxpfe3d/bin/gcc

How do we get Spack to NOT put gcc-4.8.5 in the identifier or hash?

**Comment by tgamblin** [comment]
For packages that don't involve a compiler I can understand this. I'd like to generalize compiler support more at some point in the future to handle this case and the case where some packages use compilers spack doesn't really understand.

For `gcc`, I'm actually still interested in which compiler bootstrapped gcc, for full provenance just in case something is really wrong, though I agree it's less important.

Probably more annoying to you is the fact that Spack concretizes first and looks for reuse second, when it should really do something smarter.  That was discussed at length in #157 and we decided people rally want Spack to take a usable installed thing v.s. building something newer/fancier/slightly different.  Once *that* is implemented, it won't really matter much whether the installed gcc was built with gcc 4.9.3 or icc, we'll be able to use it to satisfy dependencies just as easily.

**Comment by mathstuf** [comment]
Does spack do the three-pass build for GCC where it verifies that it can compile itself without any differences in the binary? I don't see any staging information in GCC's `package.py`, but if it does, then the bootstrapping compiler itself doesn't matter since it really actually built itself.

**Comment by tgamblin** [comment]
It does do a 3-step build.  This would be another good spot to use compiler-independent packages.

**Comment by alalazo** [comment]
@citibeth Can this issue be closed?

**Comment by citibeth** [comment]
Yes.  I think we will see more possibilities in this direction when compilers get turned into regular dependencies, as @tgamblin has outlined.
