### ISSUE TITLE
oneAPI CI GitLab do not support IPO/LTO

### ISSUE THREAD

**Issue by ax3l** [LLNL/spack#45819]
### Steps to reproduce

I think there might be a bug on the CI GitLab runners with oneAPI compilers: https://github.com/spack/spack/pull/45251#issuecomment-2295363500

I think the linker might not properly set because I observe that [CMake's IPO tests](https://cmake.org/cmake/help/latest/module/CheckIPOSupported.html) fail.

Remove the `~python_ipo` and `~ipo` calls I added in https://github.com/spack/spack/pull/45251 for oneapi runners or turn on `+ipo` for general CMake packages in Spack using the oneapi runner to see the issue.

### Error message

CMake reports that IPO cannot be found.

### Information on your system

Spack CI

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by rscohn2** [comment]
I believe it is an issue with oneapi compiler not setting RUNPATH correctly:

```
rscohn1@anpfclxlin02:lib$ readelf -d /opt/intel/oneapi/compiler/latest/lib/icx-lto.so | grep -E '(RPATH|RUNPATH)'                                                                    
 0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN/../../lib]                                                                  
rscohn1@anpfclxlin02:lib$
```
workarounds:

* Install oneapi basekit in same prefix. It will put libs in /opt/intel/oneapi/lib
* patch RUNPATH in the binary to be $ORIGIN
* set LD_LIBRARY_PATH to include /opt/intel/oneapi/compiler/latest/lib

I filed a ticket with Intel. It might be too late for 2025.0 release.
