### ISSUE TITLE
Can package teams maintain package.py in their own repos?

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/spack#4594]
From what I can tell, the current development model for Spack packages involves a package and in particular, that package's build interface (e.g. CMakeList.txt, configure.ac, Makefile, etc.), owned, developed and maintained over *there* and then a Spack *recipe* for building that package in Spack as a `package.py` file. So, its pretty easy for the two to fall out of sync. with each other. When it does, who is responsible for fixing that?

Is it possible that package owners might, at some point, wanna maintain the Spack *recipe* themselves? Just as a package in Spack *knows* where to go to download the package source code, is it concievable a `package.py` file might know where to get updates of itself? So, the first thing it would do is download an up to date `package.py`. Of course, this feature could be off by default but it would allow package owners to maintain build recipes themselves and keep them up to date as the package build interface changes.

**Comment by tgamblin** [comment]
See discussion in #1136 and attempt in #1151.  I'd still accept a PR for this -- I think it would be useful.

**Comment by hartzell** [comment]
Seems like a neat idea.

A `package.py` file is a bridge between two worlds: the Spack framework on one side and the package on the other, it needs to be in sync with *both* sides.

Some (many?) of them already accommodate changes in the way their target is built by checking the version number and acting accordingly (a simple case is `fontconfig@2.12.2:` depending on `gperf`.

If `package.py` files are maintained outside of Spack you'll need a way to check what version of Spack is ingesting them and perhaps alter behavior accordingly.
