### ISSUE TITLE
SPACK_TARGETS_HOST_COMPATIBLE does not work as expected

### ISSUE THREAD

**Issue by babouFomb** [LLNL/spack#46198]
### Steps to reproduce

How can I make my Spack base, installed in a Docker image, usable on other machines without having to recompile and reinstall the entire base? 

I've added these lines in my CMakeLists.txt file:
```
set(SPACK_TARGETS_GRANULARITY "generic")
set(SPACK_TARGETS_HOST_COMPATIBLE "false") 
```
but it's not working. 

The Docker image is built on an Intel Skylake processor which gives me `arch=linux-ubuntu22.04-x86_64_v4` in the spack' specs. But when I run `spack arch` the output is `linux-ubuntu20.04-skylake_avx512`.

When I run my Docker image on another Intel Skylake processor, I see `arch=Slinux-ubuntu22.04-x86_64_v3` in the spack' specs and then the libraries (of my Spack base) are recompiled. The output of `spack arch` on this machine is `linux-ubuntu22.04-skylake`.

### Information on your system

* **Spack:** 0.22.1 (d66dce2d668a6234504594661506cdd1eaca4adc)
* **Python:** 3.10.12
* **Platform:** linux-ubuntu22.04-skylake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by rdiarra** [comment]
Please, someone can help me ?

**Comment by alalazo** [comment]
Given that these are giving no result:
```console
$ grep SPACK_TARGETS_GRANULARITY -R spack/
$ grep SPACK_TARGETS_HOST_COMPATIBLE -R spack/
```
I'll label this one not-a-bug. Where did you read about these variables?
