### ISSUE TITLE
libssh2: configure error

### ISSUE THREAD

**Issue by karqo** [LLNL/spack#46253]
### Steps to reproduce

In order to install libssh2, I ran the command
```
spack install -v --overwrite --show-log-on-error --fail-fast libssh2
```
(after successful concretization)

### Error message

```
==> Error: ProcessError: Command exited with status 1:
    '<tmp.dir>/spack-stage/spack-stage-libssh2-1.11.0-o6nylbnxcawfdvc7vdov7ohjcb7pk275/spack-src/configure' '--prefix=<root dir>/install-trees/linux-ubuntu22.04-sandybridge/gcc-11.4.0/libssh2-1.11.0-o6nylbnxcawfdvc7vdov7ohjcb7pk275' '--disable-tests' '--disable-docker-tests' '--disable-examples-build' '--enable-shared' '--with-libssl-prefix=/usr'

1 error found in build log:
     124    checking if the linker (<spack root dir.>/lib/spack/env/ld -m elf_x86_64) is GNU ld...
            yes
     125    checking for shared library run path origin... done
     126    checking for libssl... no
     127    checking for libgcrypt... no
     128    checking for libmbedcrypto... no
     129    checking for libbcrypt... no
  >> 130    configure: error: When using wolfSSL, must specify prefix with --with-libwolfssl-prefix in order to find OpenSSL compatib
            ility headers.
```

### Information on your system

* **Spack:** 0.23.0.dev0 (9604c0a9b36048a6d5eaee642c4c6adcf0162ab9)
* **Python:** 3.10.6
* **Platform:** linux-ubuntu22.04-sandybridge

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
looks like you're using external openssl. missing libssl-dev?

**Comment by karqo** [comment]
Yes, indeed that was the problem. However, ultimately making openssl an explicit dependency and installing it from source solved it too and a little handier.
Thanks!

**Comment by karqo** [comment]
In addition, do you think it is possible to implement a little fallback mechanism 
(i.e., if installation with an external dependency fails, then fall back to try installing this dependency from source) 
or, respectively, allow to activate such a behviour with an appropriate config. parameter?

**Comment by haampie** [comment]
I think it doesn't fit well in Spack's model, cause you'd ask to install X but end up installing Y, whereas Spack lets users fix the thing to install once and for during concretization.

Maybe we could do better at detecting libraries though. E.g. if libssl.so.X is there but libssl.so is missing, then warn about incomplete installations, or something.
