### ISSUE TITLE
hdf5 download paths

### ISSUE THREAD

**Issue by iulian787** [LLNL/spack#4626]
It seems that hdf5 download paths have changed, for some of the versions. Is anybody in charge of hdf5, or can anybody submit a PR?

**Comment by davydden** [comment]
http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.1/src/hdf5-1.10.1.tar.gz works perfectly fine for me

**Comment by adamjstewart** [comment]
Anybody can submit a PR for any package.

**Comment by cyrush** [comment]
FYI

Here is an example the new url for 1.8.16:

"https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.16/src/hdf5-1.8.16.tar.gz"

(I don't have time to prepare a pull request right now, but figured this may help)

**Comment by adamjstewart** [comment]
Oh shit, this new directory structure seems much more stable than the old one! Let me take a stab at this.
