### ISSUE TITLE
Installation issue: how to  install the  sqlite3   to compile sqlite3 column table_name  function

### ISSUE THREAD

**Issue by honghh2018** [LLNL/spack#46275]
### Steps to reproduce the issue

```console
$spack find
==> In environment gdal-env1
==> 3 root specs
 -  gdal@3.7.0 +spatialite
[+] openssl@3.1.5
 -  sqlite@3.38.5 +column_metadata+dynamic_extensions+functions
 
 
 $spack spec 
Input spec
--------------------------------
 -   sqlite@3.38.5+column_metadata+dynamic_extensions+functions

Concretized
--------------------------------
 -   sqlite@3.38.5%gcc@9.3.0+column_metadata+dynamic_extensions+fts+functions+rtree build_system=autotools arch=linux-centos7-cascadelake
[+]      ^gcc-runtime@9.3.0%gcc@9.3.0 build_system=generic arch=linux-centos7-cascadelake
[e]      ^glibc@2.17%gcc@9.3.0 build_system=autotools patches=be65fec,e179c43 arch=linux-centos7-cascadelake
[+]      ^gmake@4.4.1%gcc@9.3.0~guile build_system=generic arch=linux-centos7-cascadelake
[+]      ^readline@8.2%gcc@9.3.0 build_system=autotools patches=bbf97f1 arch=linux-centos7-cascadelake
[+]          ^ncurses@6.5%gcc@9.3.0~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-centos7-cascadelake
[+]              ^pkgconf@2.2.0%gcc@9.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]      ^zlib-ng@2.1.6%gcc@9.3.0+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-centos7-cascadelake

Input spec
--------------------------------
 -   openssl@3.1.5

Concretized
--------------------------------
[+]  openssl@3.1.5%gcc@9.3.0~docs+shared build_system=generic certs=mozilla arch=linux-centos7-cascadelake
[+]      ^ca-certificates-mozilla@2023-05-30%gcc@9.3.0 build_system=generic arch=linux-centos7-cascadelake
[+]      ^gcc-runtime@9.3.0%gcc@9.3.0 build_system=generic arch=linux-centos7-cascadelake
[e]      ^glibc@2.17%gcc@9.3.0 build_system=autotools patches=be65fec,e179c43 arch=linux-centos7-cascadelake
[+]      ^gmake@4.4.1%gcc@9.3.0~guile build_system=generic arch=linux-centos7-cascadelake
[+]      ^perl@5.38.0%gcc@9.3.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-centos7-cascadelake
[+]          ^berkeley-db@18.1.40%gcc@9.3.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-centos7-cascadelake
[+]          ^bzip2@1.0.8%gcc@9.3.0~debug~pic+shared build_system=generic arch=linux-centos7-cascadelake
[+]              ^diffutils@3.10%gcc@9.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]                  ^libiconv@1.17%gcc@9.3.0 build_system=autotools libs=shared,static arch=linux-centos7-cascadelake
[+]          ^gdbm@1.23%gcc@9.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]              ^readline@8.2%gcc@9.3.0 build_system=autotools patches=bbf97f1 arch=linux-centos7-cascadelake
[+]                  ^ncurses@6.5%gcc@9.3.0~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-centos7-cascadelake
[+]                      ^pkgconf@2.2.0%gcc@9.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]      ^zlib-ng@2.1.6%gcc@9.3.0+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-centos7-cascadelake

Input spec
--------------------------------
 -   gdal@3.7.0+spatialite

Concretized
--------------------------------
 -   gdal@3.7.0%gcc@9.3.0~archive~armadillo~arrow~basisu~blosc~brunsli~cfitsio~crnlib~cryptopp~csharp+curl~deflate~ecw+expat~filegdb~freexl~fyba+geos~gif~gta~hdf4~hdf5~hdfs~heif~iconv~idb~ipo~java+jpeg~jxl~kdu~kea~lerc~libcsf~libkml~liblzma~libqb3~libxml2~luratech~lz4~mongocxx~mrsid~mssql_ncli~mssql_odbc~mysql~netcdf~odbc~odbccpp~ogdi~opencad~opencl~openexr~openjpeg~openssl~oracle~parquet~pcidsk~pcre2~pdfium+png~podofo~poppler~postgresql~python~qhull~rasterlite2~rdb~sfcgal+spatialite+sqlite3~teigha~tiledb~webp~xercesc~zstd build_system=cmake build_type=Release generator=ninja patches=52459dc arch=linux-centos7-cascadelake
[+]      ^cmake@3.27.9%gcc@9.3.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-centos7-cascadelake
[+]          ^gmake@4.4.1%gcc@9.3.0~guile build_system=generic arch=linux-centos7-cascadelake
[+]          ^ncurses@6.5%gcc@9.3.0~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-centos7-cascadelake
[+]      ^curl@8.7.1%gcc@9.3.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-centos7-cascadelake
[+]          ^nghttp2@1.57.0%gcc@9.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]              ^diffutils@3.10%gcc@9.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]          ^openssl@3.1.5%gcc@9.3.0~docs+shared build_system=generic certs=mozilla arch=linux-centos7-cascadelake
[+]              ^ca-certificates-mozilla@2023-05-30%gcc@9.3.0 build_system=generic arch=linux-centos7-cascadelake
[+]          ^perl@5.38.0%gcc@9.3.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-centos7-cascadelake
[+]              ^berkeley-db@18.1.40%gcc@9.3.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-centos7-cascadelake
[+]              ^bzip2@1.0.8%gcc@9.3.0~debug~pic+shared build_system=generic arch=linux-centos7-cascadelake
[+]              ^gdbm@1.23%gcc@9.3.0 build_system=autotools arch=linux-centos7-cascadelake
 -       ^expat@2.6.2%gcc@9.3.0+libbsd build_system=autotools arch=linux-centos7-cascadelake
[+]          ^libbsd@0.12.1%gcc@9.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]              ^libmd@1.0.4%gcc@9.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]      ^gcc-runtime@9.3.0%gcc@9.3.0 build_system=generic arch=linux-centos7-cascadelake
 -       ^geos@3.12.1%gcc@9.3.0~ipo+shared build_system=cmake build_type=Release generator=ninja arch=linux-centos7-cascadelake
[e]      ^glibc@2.17%gcc@9.3.0 build_system=autotools patches=be65fec,e179c43 arch=linux-centos7-cascadelake
[+]      ^json-c@0.16%gcc@9.3.0~ipo build_system=cmake build_type=Release generator=make arch=linux-centos7-cascadelake
 -       ^libgeotiff@1.7.1%gcc@9.3.0+jpeg+proj+zlib build_system=autotools arch=linux-centos7-cascadelake
[+]      ^libjpeg-turbo@3.0.0%gcc@9.3.0~ipo~jpeg8~partial_decoder+pic build_system=cmake build_type=Release generator=make libs=shared,static arch=linux-centos7-cascadelake
[+]          ^nasm@2.15.05%gcc@9.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]      ^libpng@1.6.39%gcc@9.3.0~ipo~pic build_system=cmake build_type=Release generator=make libs=shared,static arch=linux-centos7-cascadelake
 -       ^libspatialite@5.1.0%gcc@9.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]          ^freexl@2.0.0%gcc@9.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]          ^libiconv@1.17%gcc@9.3.0 build_system=autotools libs=shared,static arch=linux-centos7-cascadelake
 -           ^librttopo@1.1.0%gcc@9.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]              ^autoconf@2.72%gcc@9.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]              ^automake@1.16.5%gcc@9.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]              ^libtool@2.4.7%gcc@9.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]                  ^findutils@4.9.0%gcc@9.3.0 build_system=autotools patches=440b954 arch=linux-centos7-cascadelake
[+]              ^m4@1.4.19%gcc@9.3.0+sigsegv build_system=autotools patches=9dc5fbd,bfdffa7 arch=linux-centos7-cascadelake
[+]                  ^libsigsegv@2.14%gcc@9.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]          ^libxml2@2.10.3%gcc@9.3.0+pic~python+shared build_system=autotools arch=linux-centos7-cascadelake
[+]              ^xz@5.4.6%gcc@9.3.0~pic build_system=autotools libs=shared,static arch=linux-centos7-cascadelake
[+]          ^minizip@1.2.11%gcc@9.3.0 build_system=autotools patches=7f8df10 arch=linux-centos7-cascadelake
[+]      ^libtiff@4.5.1%gcc@9.3.0+ccitt~ipo~jbig+jpeg~jpeg12~lerc~libdeflate+logluv~lzma+lzw+next~old-jpeg+packbits~pic~pixarlog+shared+thunder~webp+zlib~zstd build_system=cmake build_type=Release generator=make arch=linux-centos7-cascadelake
 -       ^ninja@1.11.1%gcc@9.3.0+re2c build_system=generic arch=linux-centos7-cascadelake
 -           ^python@3.11.7%gcc@9.3.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=13fa8bf,b0615b2,ebdca64,f2fd060 arch=linux-centos7-cascadelake
 -               ^gettext@0.22.5%gcc@9.3.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-centos7-cascadelake
 -                   ^tar@1.34%gcc@9.3.0 build_system=autotools zip=pigz arch=linux-centos7-cascadelake
 -                       ^pigz@2.8%gcc@9.3.0 build_system=makefile arch=linux-centos7-cascadelake
 -                       ^zstd@1.5.6%gcc@9.3.0+programs build_system=makefile compression=none libs=shared,static arch=linux-centos7-cascadelake
 -               ^libffi@3.4.6%gcc@9.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]              ^libxcrypt@4.4.35%gcc@9.3.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-centos7-cascadelake
[+]              ^util-linux-uuid@2.38.1%gcc@9.3.0 build_system=autotools arch=linux-centos7-cascadelake
[+]          ^re2c@2.2%gcc@9.3.0 build_system=generic arch=linux-centos7-cascadelake
[+]      ^pkgconf@2.2.0%gcc@9.3.0 build_system=autotools arch=linux-centos7-cascadelake
 -       ^proj@9.2.1%gcc@9.3.0+curl~ipo~pic+shared+tiff build_system=cmake build_type=Release generator=make arch=linux-centos7-cascadelake
 -       ^sqlite@3.38.5%gcc@9.3.0+column_metadata+dynamic_extensions+fts+functions+rtree build_system=autotools arch=linux-centos7-cascadelake
[+]          ^readline@8.2%gcc@9.3.0 build_system=autotools patches=bbf97f1 arch=linux-centos7-cascadelake
[+]      ^zlib-ng@2.1.6%gcc@9.3.0+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-centos7-cascadelake



...
```

### Error message

<details><summary>Error message</summary>

<pre>
...
</pre></details>
==> Error: sqlite-3.38.5-b5nf7zi3g4vtumtkeuy3drdiz7vqkffp: AttributeError: 'AutotoolsBuilder' object has no attribute 'compiler'

The 'sqlite' package cannot find an attribute while trying to build from sources. This might be due to a change in Spack's package format to support multiple build-systems for a single package. You can fix this by updating the build recipe, and you can also report the issue as a bug. More information at https://spack.readthedocs.io/en/latest/packaging_guide.html#installation-procedure
==> Error: sqlite-3.38.5-b5nf7zi3g4vtumtkeuy3drdiz7vqkffp: Package was not installed
==> Error: gdal-3.7.0-uprmxq4uxr6zv4n4oea5qkcrdftpjqr6: Package was not installed
==> Updating view at /share/apps/spack_env/spack-0.22.1/var/spack/environments/gdal-env1/.spack-env/view
==> Error: Installation request failed.  Refer to reported errors for failing package(s).
You have new mail in /var/spool/mail/hhhong

### Information on your system

$spack debug report
* **Spack:** 0.22.1
* **Python:** 3.7.10
* **Platform:** linux-centos7-cascadelake
* **Concretizer:** clingo

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by honghh2018** [comment]
Hi, had any advice for this?

**Comment by honghh2018** [comment]
Had anyone know the sqlite3 self-define compile with column_metadata  in spack env?
Any advice would be appreciated

**Comment by haampie** [comment]
Fixed in a6c638d0fa90f178f6243951c8b2823488f3ba82

**Comment by honghh2018** [comment]
Thanks the urgent reply, 
Cheer, it fix when replace the code in https://github.com/spack/spack/commit/a6c638d0fa90f178f6243951c8b2823488f3ba82
Best,

**Comment by honghh2018** [comment]
Although, through the compile, 
but the  sqlite@3.38.5 +column_metadata+dynamic_extensions+functions  cannot find the  sqlite3_column_table_name function

the R package build still error in spack env gdal-env1
checking GDAL: linking with --libs only... no
checking GDAL: linking with --libs and --dep-libs... yes
checking GDAL: /share/apps/spack_env/spack-0.22.1/opt/spack/linux-centos7-cascadelake/gcc-9.3.0/gdal-3.7.0-uprmxq4uxr6zv4n4oea5qkcrdftpjqr6/share/gdal/pcs.csv readable... no
checking GDAL: checking whether PROJ is available for linking:... yes
checking GDAL: checking whether PROJ is available for running:... ./gdal_proj: symbol lookup error: /share/apps/spack_env/spack-0.22.1/var/spack/environments/gdal-env1/.spack-env/view/lib64/libgdal.so.33: undefined symbol: sqlite3_column_table_name
no

The spack env info lying below:
$spack find
==> In environment gdal-env1
==> 3 root specs
[+] gdal@3.7.0 +spatialite
[+] openssl@3.1.5
[+] sqlite@3.38.5 +column_metadata+dynamic_extensions+functions

==> Installed packages
-- linux-centos7-cascadelake / gcc@9.3.0 ------------------------
autoconf@2.72                       json-c@0.16          ncurses@6.5
automake@1.16.5                     libbsd@0.12.1        nghttp2@1.57.0
berkeley-db@18.1.40                 libffi@3.4.6         ninja@1.11.1
bzip2@1.0.8                         libgeotiff@1.7.1     openssl@3.1.5
ca-certificates-mozilla@2023-05-30  libiconv@1.17        perl@5.38.0
cmake@3.27.9                        libjpeg-turbo@3.0.0  pigz@2.8
curl@8.7.1                          libmd@1.0.4          pkgconf@2.2.0
diffutils@3.10                      libpng@1.6.39        proj@9.2.1
expat@2.6.2                         librttopo@1.1.0      python@3.11.7
findutils@4.9.0                     libsigsegv@2.14      re2c@2.2
freexl@2.0.0                        libspatialite@5.1.0  readline@8.2
gcc-runtime@9.3.0                   libtiff@4.5.1        sqlite@3.38.5
gdal@3.7.0                          libtool@2.4.7        tar@1.34
gdbm@1.23                           libxcrypt@4.4.35     util-linux-uuid@2.38.1
geos@3.12.1                         libxml2@2.10.3       xz@5.4.6
gettext@0.22.5                      m4@1.4.19            zlib-ng@2.1.6
glibc@2.17                          minizip@1.2.11       zstd@1.5.6
gmake@4.4.1                         nasm@2.15.05
==> 53 installed packages

The sqlite info  
how to build the sqlite with function sqlite3_column_table_name, 
Is not right with sqlite@3.38.5 +column_metadata+dynamic_extensions+functions to build the sqlite3_column_table_name function ?
the env spec 
$spack info sqlite
AutotoolsPackage:   sqlite

Description:
    SQLite is a C-language library that implements a small, fast, self-
    contained, high-reliability, full-featured, SQL database engine.

Homepage: https://www.sqlite.org

Preferred version:  
    3.43.2    https://www.sqlite.org/2023/sqlite-autoconf-(3, 43, 2)0300.tar.gz

Safe versions:  
    3.43.2    https://www.sqlite.org/2023/sqlite-autoconf-(3, 43, 2)0300.tar.gz
    3.42.0    https://www.sqlite.org/2023/sqlite-autoconf-(3, 42, 0)0300.tar.gz
    3.40.1    https://www.sqlite.org/2022/sqlite-autoconf-(3, 40, 1)0300.tar.gz
    3.40.0    https://www.sqlite.org/2022/sqlite-autoconf-(3, 40, 0)0300.tar.gz
    3.39.4    https://www.sqlite.org/2022/sqlite-autoconf-(3, 39, 4)0300.tar.gz
    3.39.2    https://www.sqlite.org/2022/sqlite-autoconf-(3, 39, 2)0300.tar.gz
    3.38.5    https://www.sqlite.org/2022/sqlite-autoconf-(3, 38, 5)0300.tar.gz
    3.38.3    https://www.sqlite.org/2022/sqlite-autoconf-(3, 38, 3)0300.tar.gz
    3.37.2    https://www.sqlite.org/2022/sqlite-autoconf-(3, 37, 2)0300.tar.gz
    3.37.1    https://www.sqlite.org/2021/sqlite-autoconf-(3, 37, 1)0300.tar.gz
    3.37.0    https://www.sqlite.org/2021/sqlite-autoconf-(3, 37, 0)0300.tar.gz
    3.36.0    https://www.sqlite.org/2021/sqlite-autoconf-(3, 36, 0)0300.tar.gz
    3.35.5    https://www.sqlite.org/2021/sqlite-autoconf-(3, 35, 5)0300.tar.gz
    3.35.4    https://www.sqlite.org/2021/sqlite-autoconf-(3, 35, 4)0300.tar.gz
    3.35.3    https://www.sqlite.org/2021/sqlite-autoconf-(3, 35, 3)0300.tar.gz
    3.34.0    https://www.sqlite.org/2020/sqlite-autoconf-(3, 34, 0)0300.tar.gz
    3.33.0    https://www.sqlite.org/2020/sqlite-autoconf-(3, 33, 0)0300.tar.gz
    3.32.3    https://www.sqlite.org/2020/sqlite-autoconf-(3, 32, 3)0300.tar.gz
    3.31.1    https://www.sqlite.org/2020/sqlite-autoconf-(3, 31, 1)0300.tar.gz
    3.30.1    https://www.sqlite.org/2019/sqlite-autoconf-(3, 30, 1)0300.tar.gz
    3.30.0    https://www.sqlite.org/2019/sqlite-autoconf-(3, 30, 0)0300.tar.gz
    3.29.0    https://www.sqlite.org/2019/sqlite-autoconf-(3, 29, 0)0300.tar.gz
    3.28.0    https://www.sqlite.org/2019/sqlite-autoconf-(3, 28, 0)0300.tar.gz
    3.27.2    https://www.sqlite.org/2019/sqlite-autoconf-(3, 27, 2)0300.tar.gz
    3.27.1    https://www.sqlite.org/2019/sqlite-autoconf-(3, 27, 1)0300.tar.gz
    3.27.0    https://www.sqlite.org/2019/sqlite-autoconf-(3, 27, 0)0300.tar.gz
    3.26.0    https://www.sqlite.org/2018/sqlite-autoconf-(3, 26, 0)0300.tar.gz

Deprecated versions:  
    None

Variants:
    build_system [autotools]         autotools, nmake
        Build systems supported by the package
    fts [true]                       false, true
        Include fts4 and fts5 support
    rtree [true]                     false, true
        Build with Rtree module

    when arch=cray-None-None
      column_metadata [true]         false, true
          Build with COLUMN_METADATA
      dynamic_extensions [true]      false, true
          Support loadable extensions

    when arch=darwin-None-None
      column_metadata [true]         false, true
          Build with COLUMN_METADATA
      dynamic_extensions [true]      false, true
          Support loadable extensions

    when arch=freebsd-None-None
      column_metadata [true]         false, true
          Build with COLUMN_METADATA
      dynamic_extensions [true]      false, true
          Support loadable extensions

    when arch=linux-None-None
      column_metadata [true]         false, true
          Build with COLUMN_METADATA
      dynamic_extensions [true]      false, true
          Support loadable extensions

    when +dynamic_extensions
      functions [false]              false, true
          Provide mathematical and string extension functions for SQL queries using
          the loadable extensions mechanism

Build Dependencies:
    gmake  gnuconfig  readline  tcl  zlib-api

Link Dependencies:
    readline  tcl  zlib-api

Run Dependencies:
    None

Licenses: 
    blessing



Best,
hanhuihong

**Comment by honghh2018** [comment]
Had any advice for this issue?

**Comment by honghh2018** [comment]
Any advice would be appreciated
