### ISSUE TITLE
netcdf-fortran wants to install netcdf even though it's installed

### ISSUE THREAD

**Issue by mathomp4** [LLNL/spack#4627]
All,

I'm sure this is a "Matt's a newbie" issue, but I'm stumped.

One of my ultimate goals in life is to get GEOS (Goddard's model) in spack. Why? Good challenge if nothing else, but also to have a nice one command install line? Oooh. 

But, that first means being able to install all the libraries it needs. In the end that is essentially ESMF but it seems to have an issue beyond me when I try installing that (Conflicts in concretized spec?). So I started installing libraries one by one. If nothing else, I learn more spack. I eventually installed netcdf with:
```
spack install netcdf-fortran %gcc@7.1.0 +hdf4+dap
```
I use those variants because I currently build netcdf with those in ESMA Baselibs (the library distribution I currently use for GEOS), so I'm trying to be consistent. That works just fine but then:
```
(212) $ spack install netcdf-fortran %gcc@7.1.0 
==> m4 is already installed in /ford1/share/gmao_SIteam/spack/opt/spack/linux-rhel7-x86_64/gcc-7.1.0/m4-1.4.18-uiess2b3dajx4okgtf2sxjswqwte76ve
==> zlib is already installed in /ford1/share/gmao_SIteam/spack/opt/spack/linux-rhel7-x86_64/gcc-7.1.0/zlib-1.2.11-zqrm3wqa4icvkftszlqhyte5ndwxc2r3
==> hdf5 is already installed in /ford1/share/gmao_SIteam/spack/opt/spack/linux-rhel7-x86_64/gcc-7.1.0/hdf5-1.10.1-eynuttgv4gx46bv62sz5fm57xejvyduy
==> Installing netcdf
==> Using cached archive: /ford1/share/gmao_SIteam/spack/var/spack/cache/netcdf/netcdf-4.4.1.1.tar.gz
==> Staging archive: /ford1/share/gmao_SIteam/spack/var/spack/stage/netcdf-4.4.1.1-pdbryx6sv47sfukz7qvikghucqqqwhpy/netcdf-4.4.1.1.tar.gz
==> Created stage in /ford1/share/gmao_SIteam/spack/var/spack/stage/netcdf-4.4.1.1-pdbryx6sv47sfukz7qvikghucqqqwhpy
==> Ran patch() for netcdf
==> Building netcdf [AutotoolsPackage]
==> Executing phase : 'autoreconf'
==> Executing phase : 'configure'
Process logger_daemon:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/ford1/share/gmao_SIteam/spack/lib/spack/llnl/util/tty/log.py", line 197, in _spawn_writing_daemon
    line = read_file.readline()
KeyboardInterrupt

==> Error: Keyboard interrupt.
```
But I have netcdf and it installed, so it shouldn't need to install again. At first I thought "Oh, I forgot the variants, duh" but:
```
(215) $ spack install netcdf-fortran %gcc@7.1.0 +hdf4+dap
==> Error: Package netcdf-fortran has no variant set(['dap', 'hdf4'])!
```
So...yeah. How does one get netcdf-fortran to see netcdf is installed?

**Comment by adamjstewart** [comment]
> One of my ultimate goals in life is to get GEOS (Goddard's model) in spack.

Isn't there already a `geos` package?

> But I have netcdf and it installed, so it shouldn't need to install again.

Spack doesn't look at already installed packages before it decides what to install. It takes an abstract spec (`netcdf-fortran %gcc@7.1.0`), concretizes it, and then installs anything that's missing. You can see what is going to be installed by running:
```
$ spack spec -I netcdf-fortran %gcc@7.1.0
```
Anything with a green `[+]` next to it is already installed.

> At first I thought "Oh, I forgot the variants, duh"

As you correctly surmised, unless you explicitly tell it to install `netcdf+hdf4+dap`, it will choose the defaults. You just got the syntax wrong. The correct syntax to specify this is:
```
$ spack install netcdf-fortran %gcc@7.1.0 ^netcdf+hdf4+dap
```
but if you always want to install `netcdf+hdf5+dap`, you can make these options the default. Create a new file if you don't already have one called `~/.spack/packages.yaml` containing:
```yaml
packages:
  netcdf:
    variants: +hdf4+dap
```
and you'll never have to specify it on the command line again.

> In the end that is essentially ESMF but it seems to have an issue beyond me when I try installing that (Conflicts in concretized spec?)

When I run `spack spec esmf` I see:
```
==> Error: Conflicts in concretized spec "esmf@7.0.1%gcc@6.3.1~debug+lapack+mpi+netcdf+pio+pnetcdf+xerces arch=linux-fedora25-x86_64 /zasmp7y"

List of matching conflicts:

1. "%gcc@6:" conflicts with "esmf" ...
```
If you run `spack edit esmf` and search for `conflicts` you'll see a note I left when I wrote the ESMF package:

> NOTE: ESMF cannot be installed with GCC 6. It uses constructs that are no longer valid in GCC 6. GCC 4 is recommended for installation.

So that's why you're seeing the error message. You'll have to use an older compiler (or convince the ESMF developers to get with the times). Also, I wrote the ESMF package, but I'm not convinced that it actually works. I'm worried that the build system assumes that `netcdf` and `netcdf-fortran` are installed to the same directory, which isn't the case. So if you get it working, let me know. It may need a little work...

**Comment by mathomp4** [comment]
> Isn't there already a `geos` package?
Yeah. That's a different geos (Geometry Engine Open Source probably). If I do get it in at some point I'll probably need to talk with the bosses. We were GEOS-5, but I think we now mainly refer to it as GEOS. That's in the future though!

> Spack doesn't look at already installed packages before it decides what to install. It takes an abstract spec (netcdf-fortran %gcc@7.1.0), concretizes it, and then installs anything that's missing. You can see what is going to be installed by running:
> 
> $ spack spec -I netcdf-fortran %gcc@7.1.0
> Anything with a green [+] next to it is already installed.
Ooh. I'm learning!

> As you correctly surmised, unless you explicitly tell it to install netcdf+hdf4+dap, it will choose the defaults. You just got the syntax wrong. The correct syntax to specify this is:
> 
> $ spack install netcdf-fortran %gcc@7.1.0 ^netcdf+hdf4+dap

Ah. I knew it had to be something like that.

> but if you always want to install netcdf+hdf5+dap, you can make these options the default. Create a new file if you don't already have one called ~/.spack/packages.yaml containing:
> 
> packages:
>   netcdf:
>     variants: +hdf4+dap
> and you'll never have to specify it on the command line again.

Ah. Very nice! I'll do that forthwith. And add it to other packages too. Like:

> If you run spack edit esmf and search for conflicts you'll see a note I left when I wrote the ESMF package:
> 
> NOTE: ESMF cannot be installed with GCC 6. It uses constructs that are no longer valid in GCC 6. GCC 4 is recommended for installation.

Huh. I've built it with pretty much every gcc/gfortran since 4.9 (up to 7.1.0). I'll take a gander at it once I get netcdf-fortran as it should work! But, yes, their build system is...idiosyncratic shall we say.

> Also, I wrote the ESMF package, but I'm not convinced that it actually works. I'm worried that the build system assumes that netcdf and netcdf-fortran are installed to the same directory, which isn't the case. So if you get it working, let me know. It may need a little work...

Yeah. I have to do some wrangling on my end in ESMA Baselibs. My guess is you have to set ESMF_NETCDF_LIBPATH, &c. to have both directories in the path. If not, I know the ESMF folks and I can ask them how. Half that build system has changed in recent years because of me. :)

**Comment by adamjstewart** [comment]
> Huh. I've built it with pretty much every gcc/gfortran since 4.9 (up to 7.1.0).

If you can get it working, feel free to remove the `conflicts()` and my comment. It didn't work for me when I wrote the package though.

> If not, I know the ESMF folks and I can ask them how. Half that build system has changed in recent years because of me. :)

You are my new hero.

**Comment by mathomp4** [comment]
@adamjstewart I'll probably need your help with esmf soon on how to best edit that make script (i.e., handling different mpich's etc). I'll make a new ticket for that.
