### ISSUE TITLE
gmsh misses dependencies 

### ISSUE THREAD

**Issue by prudhomm** [LLNL/spack#46326]
### Steps to reproduce

on a ubuntu system install gmsh (which install the required dependencies
then 
```
spack install gmsh
```

### Error message

there are missing dependencies in the package that fail then to be concretized and if the software is installed locally then spack install compiles gmsh with external dependencies .
then if we use spack containerize, gmsh is unusable due to missing external dependencies

missing dependencies include : jpeg, szip and aec

### Information on your system

ubuntu 22.04

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Fixed by #46395
