### ISSUE TITLE
pkg_config only sets ACLOCAL_PATH if you're on a cray

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#4633]
As written, [pkg_config only adds ACLOCAL_PATH to the environment when `platform = cray`](https://github.com/LLNL/spack/blame/develop/var/spack/repos/builtin/packages/pkg-config/package.py#L54)

That variable should be set all of the time (I need it for a new package that's in progress).

I'll fix this, but I'm not sure about how the `when` bits are handled.

If I supply a second `setup_dependent_environment` that handles `ACLOCAL_PATH`, without a decorator, will *both* run when `platform=cray`?

Or, should I remove the `@when` decorator and check the platform in the body of the function?

**Comment by hartzell** [comment]
I've found a download site for the package I'm working on (lftp) that does not require me to do all of the autoconf steps, so I'm off the hook for this.

I still think it's a problem, and I can use my previous false start to test a fix.

**Comment by hartzell** [comment]
(in case it wasn't clear from the previous comment)

... and with a little guidance I will produce the PR that I test with my WIP package.

**Comment by adamjstewart** [comment]
Presumably this is resolved by #4736. Reopen if not.
