### ISSUE TITLE
Installation issue: maeparser fails to build

### ISSUE THREAD

**Issue by m-miller10** [LLNL/spack#46417]
### Steps to reproduce the issue

```console
$ spack spec -I <spec>
Input spec
--------------------------------
 -   maeparser%gcc@8.5.0
 -       ^boost@1.70.0 arch=None-rhel8-x86_64_v3

Concretized
--------------------------------
 -   maeparser@1.3.1%gcc@8.5.0~ipo+shared build_system=cmake build_type=Release generator=make arch=linux-rhel8-x86_64_v3
[+]      ^boost@1.70.0%gcc@8.5.0 cppflags=-fPIC ~atomic~chrono~clanglibcpp~container~context~contract~coroutine~date_time~debug~exception~fiber+filesystem~graph~graph_parallel~icu+iostreams~json~locale~log~math~mpi+multithreaded~nowide~numpy~pic~program_options~python~random~regex~serialization+shared~signals~singlethreaded~stacktrace~system~taggedlayout+test~thread~timer~type_erasure~versionedlayout~wave build_system=generic cxxstd=11 patches=5da7ad2 visibility=hidden arch=linux-rhel8-x86_64_v3
[+]          ^bzip2@1.0.8%gcc@8.5.0~debug~pic+shared build_system=generic arch=linux-rhel8-x86_64_v3
[+]              ^diffutils@3.10%gcc@8.5.0 build_system=autotools arch=linux-rhel8-x86_64_v3
[+]                  ^libiconv@1.17%gcc@8.5.0 build_system=autotools libs=shared,static arch=linux-rhel8-x86_64_v3
[+]          ^gcc-runtime@8.5.0%gcc@8.5.0 build_system=generic arch=linux-rhel8-x86_64_v3
[+]          ^xz@5.4.6%gcc@8.5.0~pic build_system=autotools libs=shared,static arch=linux-rhel8-x86_64_v3
[+]          ^zstd@1.5.6%gcc@8.5.0~programs build_system=makefile libs=shared,static arch=linux-rhel8-x86_64_v3
[+]      ^cmake@3.27.9%gcc@8.5.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-rhel8-x86_64_v3
[+]          ^curl@8.7.1%gcc@8.5.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-rhel8-x86_64_v3
[+]              ^nghttp2@1.57.0%gcc@8.5.0 build_system=autotools arch=linux-rhel8-x86_64_v3
[+]              ^openssl@3.3.0%gcc@8.5.0~docs+shared build_system=generic certs=mozilla arch=linux-rhel8-x86_64_v3
[+]                  ^ca-certificates-mozilla@2023-05-30%gcc@8.5.0 build_system=generic arch=linux-rhel8-x86_64_v3
[+]              ^perl@5.38.0%gcc@8.5.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-rhel8-x86_64_v3
[+]                  ^berkeley-db@18.1.40%gcc@8.5.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-rhel8-x86_64_v3
[+]                  ^gdbm@1.23%gcc@8.5.0 build_system=autotools arch=linux-rhel8-x86_64_v3
[+]                      ^readline@8.2%gcc@8.5.0 build_system=autotools patches=bbf97f1 arch=linux-rhel8-x86_64_v3
[+]              ^pkgconf@2.2.0%gcc@8.5.0 build_system=autotools arch=linux-rhel8-x86_64_v3
[+]          ^ncurses@6.5%gcc@8.5.0~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-rhel8-x86_64_v3
[+]      ^gcc-runtime@8.5.0%gcc@8.5.0 build_system=generic arch=linux-rhel8-x86_64_v3
[e]          ^glibc@2.28%oneapi@2024.1.0 build_system=autotools arch=linux-rhel8-x86_64_v3
[e]      ^glibc@2.28%gcc@8.5.0 build_system=autotools arch=linux-rhel8-x86_64_v3
[+]      ^gmake@4.4.1%gcc@8.5.0~guile build_system=generic arch=linux-rhel8-x86_64_v3
[+]      ^zlib-ng@2.1.6%gcc@8.5.0+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-rhel8-x86_64_v3

$ spack install maeparser  %gcc@8.5.0 ^boost@1.70.0  target=x86_64_v3 os=rhel8
```

### Error message

<details><summary>Error message</summary>

<pre>
[ 42%] Linking CXX shared library libmaeparser.so
/software/spack.0.22.1/opt/spack/linux-rhel8-x86_64_v3/gcc-8.5.0/cmake-3.27.9-nlvvlt3/bin/cmake -E cmake_link_script CMakeFiles/maeparser.dir/link.txt --verbose=1
/software/spack.0.22.1/lib/spack/env/gcc/g++ -fPIC -O3 -DNDEBUG -shared -Wl,-soname,libmaeparser.so.1 -o libmaeparser.so.1.3.1 CMakeFiles/maeparser.dir/Buffer.cpp.o CMakeFiles/maeparser.dir/MaeBlock.cpp.o CMakeFiles/maeparser.dir/MaeParser.cpp.o CMakeFiles/maeparser.dir/Reader.cpp.o CMakeFiles/maeparser.dir/Writer.cpp.o  -Wl,-rpath,/software/spack.0.22.1/opt/spack/linux-rhel8-x86_64_v3/gcc-8.5.0/zlib-ng-2.1.6-m6zb4h5/lib::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: /software/spack.0.22.1/opt/spack/linux-rhel8-x86_64_v3/gcc-8.5.0/boost-1.70.0-j67hmtv/lib/libboost_iostreams.a /software/spack.0.22.1/opt/spack/linux-rhel8-x86_64_v3/gcc-8.5.0/zlib-ng-2.1.6-m6zb4h5/lib/libz.so 
/usr/bin/ld: /software/spack.0.22.1/opt/spack/linux-rhel8-x86_64_v3/gcc-8.5.0/boost-1.70.0-j67hmtv/lib/libboost_iostreams.a(gzip.o): relocation R_X86_64_32S against `.rodata' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: /software/spack.0.22.1/opt/spack/linux-rhel8-x86_64_v3/gcc-8.5.0/boost-1.70.0-j67hmtv/lib/libboost_iostreams.a(zlib.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Nonrepresentable section on output
collect2: error: ld returned 1 exit status
</pre></details>

### Information on your system

``` console
$ spack debug report
* **Spack:** 0.22.1
* **Python:** 3.6.8
* **Platform:** linux-rhel8-zen2
* **Concretizer:** clingo
```

### Additional information

[spack-configure-args.txt](https://github.com/user-attachments/files/17019250/spack-configure-args.txt)
[spack-build-out.txt](https://github.com/user-attachments/files/17019251/spack-build-out.txt)
[spack-build-env.txt](https://github.com/user-attachments/files/17019252/spack-build-env.txt)
@RMeli

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by RMeli** [comment]
I haven't managed to reproduce this locally, unfortunately. Have you tried to set `cppflags=-fPIC` explicitly, as suggested by the error?

Something odd I noticed, is that you have `glibc` with two different compilers:
```
[+]      ^gcc-runtime@8.5.0%gcc@8.5.0 build_system=generic arch=linux-rhel8-x86_64_v3
[e]          ^glibc@2.28%oneapi@2024.1.0 build_system=autotools arch=linux-rhel8-x86_64_v3
[e]      ^glibc@2.28%gcc@8.5.0 build_system=autotools arch=linux-rhel8-x86_64_v3
```

**Comment by m-miller10** [comment]
Thank you.   Yes I did try setting the compiler flag but it fails later on due to the lazy loading feature in the main application.    We do have multiple compilers installed.  Good call on the 2 glibc (not sure why both get included unless another dependency was pulled from there).   I will see if I can force just the one or a fresh build.

-Mike

From: Rocco Meli ***@***.***>
Date: Tuesday, September 17, 2024 at 4:09 AM
To: spack/spack ***@***.***>
Cc: Michael Miller ***@***.***>, Author ***@***.***>
Subject: Re: [spack/spack] Installation issue: maeparser fails to build (Issue #46417)
I haven't managed to reproduce this locally, unfortunately. Have you tried to set cppflags=-fPIC explicitly, as suggested by the error? Something odd I noticed, is that you have glibc with two different compilers: [+] ^gcc-runtime@ 8. 5. 0%gcc@ 8. 5. 0


I haven't managed to reproduce this locally, unfortunately. Have you tried to set cppflags=-fPIC explicitly, as suggested by the error?

Something odd I noticed, is that you have glibc with two different compilers:

[+]      ***@***.******@***.*** build_system=generic arch=linux-rhel8-x86_64_v3

[e]          ***@***.******@***.*** build_system=autotools arch=linux-rhel8-x86_64_v3

[e]      ***@***.******@***.*** build_system=autotools arch=linux-rhel8-x86_64_v3

**Comment by RMeli** [comment]
I tried in another system and I can finally reproduce this with `boost@1.70` and `%gcc@11.4.0`. Not sure yet what is going on, but with `boost@1.71.0` and `boost@1.85.0` the problem does not occur.

**Comment by m-miller10** [comment]
Thank you Rocco I will give 1.71.0 a try on my end.   I found that 1.85.0 caused problems with  the rdkit build that has a dependence on maeparser.

From: Rocco Meli ***@***.***>
Date: Wednesday, September 18, 2024 at 12:02 AM
To: spack/spack ***@***.***>
Cc: Michael Miller ***@***.***>, Author ***@***.***>
Subject: Re: [spack/spack] Installation issue: maeparser fails to build (Issue #46417)
I tried in another system and I can finally reproduce this with boost@ 1. 70 and %gcc@ 11. 4. 0. Not sure yet what is going on, but with boost@ 1. 71. 0 and boost@ 1. 85. 0 the problem does not occur. — Reply to this email directly, view it on GitHub,


I tried in another system and I can finally reproduce this with ***@***.*** and ***@***.*** Not sure yet what is going on, but with ***@***.*** and ***@***.*** the problem does not occur.

**Comment by RMeli** [comment]
No worries. If you don't need the `maeparser` for RDKit you can simply disable it as `rdkit~maeparser` (I made it a variant when I added it). If you need it, I tested
```
spack install rdkit@2024_03_3 ^boost@1.71.0 %gcc@11.4.0
```
and it works. I also tested it with `boost@1.85.0` and works too. 

Which version of RDKit are you trying to install? Which kind of error are you getting with `boost@1.85.0`?

**Comment by m-miller10** [comment]
Thank you.   I've tested and maeparser does build fine with boost@1.71.    However I get an interesting cmake checksum error from GraphMol (It is the same error that I get with boost@1.85).  
```
     77    Downloading https://fonts.google.com/download?family=Comic%20Neue...
  >> 78    CMake Error at Code/cmake/Modules/RDKitUtils.cmake:257 (MESSAGE):
     79      The md5 checksum for
     80      /scratch/spack/spack-stage/spack-stage-rdkit-2023_03_1-ygogvyzvqrw
           scb623srd5xcb2zvbntzv/spack-src/Code/GraphMol/MolDraw2D/Comic_Neue.z
           ip
     81      is incorrect; expected: 850b0df852f1cda4970887b540f8f333, found:
     82      9ab181dffc1231150cf24f926e1778d4
```

The spec for this build is:
```
Concretized
--------------------------------
 -   rdkit@2023_03_1%gcc@8.5.0~contrib+coordgen+descriptors3d~freesasa+freetype~ipo+maeparser+python~xyz2mol+yaehmop build_system=cmake build_type=Release generator=make arch=linux-rhel8-x86_64_v3
[+]      ^boost@1.71.0%gcc@8.5.0~atomic~chrono~clanglibcpp~container~context~contract~coroutine~date_time~debug~exception~fiber+filesystem~graph~graph_parallel~icu+iostreams~json~locale~log~math~mpi+multithreaded~nowide~numpy~pic~program_options+python~random~regex+serialization+shared~signals~singlethreaded~stacktrace+system~taggedlayout+test~thread~timer~type_erasure~versionedlayout~wave build_system=generic cxxstd=11 patches=2ab6c72,5da7ad2 visibility=hidden arch=linux-rhel8-x86_64_v3
[+]          ^bzip2@1.0.8%gcc@8.5.0~debug~pic+shared build_system=generic arch=linux-rhel8-x86_64_v3
[+]              ^diffutils@3.10%gcc@8.5.0 build_system=autotools arch=linux-rhel8-x86_64_v3
[+]          ^gcc-runtime@8.5.0%gcc@8.5.0 build_system=generic arch=linux-rhel8-x86_64_v3
[+]          ^xz@5.4.6%gcc@8.5.0~pic build_system=autotools libs=shared,static arch=linux-rhel8-x86_64_v3
[+]          ^zlib-ng@2.1.6%gcc@8.5.0+compat+new_strategies+opt+pic+shared build_system=autotools arch=linux-rhel8-x86_64_v3
[+]          ^zstd@1.5.6%gcc@8.5.0+programs build_system=makefile compression=none libs=shared,static arch=linux-rhel8-x86_64_v3
[+]      ^cmake@3.27.9%gcc@8.5.0~doc+ncurses+ownlibs build_system=generic build_type=Release arch=linux-rhel8-x86_64_v3
[+]          ^curl@8.7.1%gcc@8.5.0~gssapi~ldap~libidn2~librtmp~libssh~libssh2+nghttp2 build_system=autotools libs=shared,static tls=openssl arch=linux-rhel8-x86_64_v3
[+]              ^nghttp2@1.57.0%gcc@8.5.0 build_system=autotools arch=linux-rhel8-x86_64_v3
[+]              ^perl@5.38.0%gcc@8.5.0+cpanm+opcode+open+shared+threads build_system=generic patches=714e4d1 arch=linux-rhel8-x86_64_v3
[+]                  ^berkeley-db@18.1.40%gcc@8.5.0+cxx~docs+stl build_system=autotools patches=26090f4,b231fcc arch=linux-rhel8-x86_64_v3
[+]          ^ncurses@6.5%gcc@8.5.0~symlinks+termlib abi=none build_system=autotools patches=7a351bc arch=linux-rhel8-x86_64_v3
[+]      ^coordgen@3.0.2%gcc@8.5.0~example~ipo+maeparser+shared build_system=cmake build_type=Release generator=make arch=linux-rhel8-x86_64_v3
[+]      ^eigen@3.4.0%gcc@8.5.0~ipo build_system=cmake build_type=RelWithDebInfo generator=make arch=linux-rhel8-x86_64_v3
[+]      ^freetype@2.13.2%gcc@8.5.0+pic+shared build_system=autotools arch=linux-rhel8-x86_64_v3
[+]          ^libpng@1.6.39%gcc@8.5.0~ipo~pic build_system=cmake build_type=Release generator=make libs=shared,static arch=linux-rhel8-x86_64_v3
[+]          ^pkgconf@2.2.0%gcc@8.5.0 build_system=autotools arch=linux-rhel8-x86_64_v3
[+]      ^gcc-runtime@8.5.0%gcc@8.5.0 build_system=generic arch=linux-rhel8-x86_64_v3
[e]          ^glibc@2.28%oneapi@2024.1.0 build_system=autotools arch=linux-rhel8-x86_64_v3
[e]      ^glibc@2.28%gcc@8.5.0 build_system=autotools arch=linux-rhel8-x86_64_v3
[+]      ^gmake@4.4.1%gcc@8.5.0~guile build_system=generic arch=linux-rhel8-x86_64_v3
[+]      ^maeparser@1.3.1%gcc@8.5.0~ipo+shared build_system=cmake build_type=Release generator=make arch=linux-rhel8-x86_64_v3
[+]      ^py-numpy@1.26.4%gcc@8.5.0 build_system=python_pip patches=873745d arch=linux-rhel8-x86_64_v3
[+]          ^openblas@0.3.26%gcc@8.5.0~bignuma~consistent_fpcsr+dynamic_dispatch+fortran~ilp64+locking+pic+shared build_system=makefile symbol_suffix=none threads=none arch=linux-rhel8-x86_64_v3
[+]          ^py-cython@0.29.36%gcc@8.5.0 build_system=python_pip patches=c4369ad arch=linux-rhel8-x86_64_v3
[+]              ^py-setuptools@69.2.0%gcc@8.5.0 build_system=generic arch=linux-rhel8-x86_64_v3
[+]          ^py-meson-python@0.15.0%gcc@8.5.0 build_system=python_pip arch=linux-rhel8-x86_64_v3
[+]              ^meson@1.3.2%gcc@8.5.0 build_system=python_pip patches=0f0b1bd arch=linux-rhel8-x86_64_v3
[+]                  ^ninja@1.11.1%gcc@8.5.0+re2c build_system=generic arch=linux-rhel8-x86_64_v3
[+]                      ^re2c@2.2%gcc@8.5.0 build_system=generic arch=linux-rhel8-x86_64_v3
[+]              ^py-pyproject-metadata@0.7.1%gcc@8.5.0 build_system=python_pip arch=linux-rhel8-x86_64_v3
[+]                  ^py-packaging@21.3%gcc@8.5.0 build_system=python_pip arch=linux-rhel8-x86_64_v3
[+]                      ^py-pyparsing@3.1.2%gcc@8.5.0 build_system=python_pip arch=linux-rhel8-x86_64_v3
[+]              ^py-tomli@2.0.1%gcc@8.5.0 build_system=python_pip arch=linux-rhel8-x86_64_v3
[+]                  ^py-flit-core@3.9.0%gcc@8.5.0 build_system=python_pip arch=linux-rhel8-x86_64_v3
[+]          ^py-pip@23.1.2%gcc@8.5.0 build_system=generic arch=linux-rhel8-x86_64_v3
[+]          ^py-wheel@0.41.2%gcc@8.5.0 build_system=generic arch=linux-rhel8-x86_64_v3
[+]      ^python@3.9.18%gcc@8.5.0+bz2+crypt+ctypes+dbm~debug+libxml2+lzma~nis~optimizations+pic+pyexpat+pythoncmd+readline+shared+sqlite3+ssl~tkinter+uuid+zlib build_system=generic patches=0d98e93,4c24573,ebdca64,f2fd060 arch=linux-rhel8-x86_64_v3
[+]          ^expat@2.6.2%gcc@8.5.0+libbsd build_system=autotools arch=linux-rhel8-x86_64_v3
[+]              ^libbsd@0.12.1%gcc@8.5.0 build_system=autotools arch=linux-rhel8-x86_64_v3
[+]                  ^libmd@1.0.4%gcc@8.5.0 build_system=autotools arch=linux-rhel8-x86_64_v3
[+]          ^gdbm@1.23%gcc@8.5.0 build_system=autotools arch=linux-rhel8-x86_64_v3
[+]          ^gettext@0.22.5%gcc@8.5.0+bzip2+curses+git~libunistring+libxml2+pic+shared+tar+xz build_system=autotools arch=linux-rhel8-x86_64_v3
[+]              ^libiconv@1.17%gcc@8.5.0 build_system=autotools libs=shared,static arch=linux-rhel8-x86_64_v3
[+]              ^libxml2@2.10.3%gcc@8.5.0+pic~python+shared build_system=autotools arch=linux-rhel8-x86_64_v3
[+]              ^tar@1.34%gcc@8.5.0 build_system=autotools zip=pigz arch=linux-rhel8-x86_64_v3
[+]                  ^pigz@2.8%gcc@8.5.0 build_system=makefile arch=linux-rhel8-x86_64_v3
[+]          ^libffi@3.4.6%gcc@8.5.0 build_system=autotools arch=linux-rhel8-x86_64_v3
[+]          ^libxcrypt@4.4.35%gcc@8.5.0~obsolete_api build_system=autotools patches=4885da3 arch=linux-rhel8-x86_64_v3
[+]          ^openssl@3.3.0%gcc@8.5.0~docs+shared build_system=generic certs=mozilla arch=linux-rhel8-x86_64_v3
[+]              ^ca-certificates-mozilla@2023-05-30%gcc@8.5.0 build_system=generic arch=linux-rhel8-x86_64_v3
[+]          ^readline@8.2%gcc@8.5.0 build_system=autotools patches=bbf97f1 arch=linux-rhel8-x86_64_v3
[+]          ^util-linux-uuid@2.38.1%gcc@8.5.0 build_system=autotools arch=linux-rhel8-x86_64_v3
[+]      ^python-venv@1.0%gcc@8.5.0 build_system=generic arch=linux-rhel8-x86_64_v3
[+]      ^sqlite@3.43.2%gcc@8.5.0+column_metadata+dynamic_extensions+fts~functions+rtree build_system=autotools arch=linux-rhel8-x86_64_v3
```

**Comment by RMeli** [comment]
This issue seems to happen from time to time:
* https://github.com/rdkit/rdkit/pull/4885
* https://github.com/rdkit/rdkit/pull/7096

The checksum you get does not correspond to the one in `master`
https://github.com/rdkit/rdkit/blob/c8cd4e7c20fc74defdab589973d6e80c6e137eec/Code/GraphMol/MolDraw2D/CMakeLists.txt#L24
therefore there might be something wrong with the download. Or the checksum changed again.

For the latter case, the only solution I see for Spack is to create a [patch](https://spack.readthedocs.io/en/latest/packaging_guide.html#patches).

**Comment by m-miller10** [comment]
Rocco,

   Thank you I really appreciate your help, I’m still learning spack.   I will clear the cached copy to see if it resolves.  The suggestion of a patch is a great idea, I’ve not done that before but I’m going to give it a go as this could be helpful for similar cases in the future.

-Mike

From: Rocco Meli ***@***.***>
Date: Thursday, September 19, 2024 at 1:14 AM
To: spack/spack ***@***.***>
Cc: Michael Miller ***@***.***>, Author ***@***.***>
Subject: Re: [spack/spack] Installation issue: maeparser fails to build (Issue #46417)
This issue seems to happen from time to time: rdkit/rdkit#4885 rdkit/rdkit#7096 The checksum you get does not correspond to the one in master https: //github. com/rdkit/rdkit/blob/c8cd4e7c20fc74defdab589973d6e80c6e137eec/Code/GraphMol/MolDraw2D/CMakeLists. txt#L24


This issue seems to happen from time to time:

  *   rdkit/rdkit#4885<https://urldefense.com/v3/__https:/github.com/rdkit/rdkit/pull/4885__;!!Dq7g1IpY!jnlnFJsArVN7aW97xCMs4-w16vumNdfMPuidF8OO_U4-8OND0py68ga3mutIm6HOscHSUnwsQ0SjMuZHik4X1-Gmy0EKhAE$>
  *   rdkit/rdkit#7096<https://urldefense.com/v3/__https:/github.com/rdkit/rdkit/pull/7096__;!!Dq7g1IpY!jnlnFJsArVN7aW97xCMs4-w16vumNdfMPuidF8OO_U4-8OND0py68ga3mutIm6HOscHSUnwsQ0SjMuZHik4X1-GmING7HdU$>

The checksum you get does not correspond to the one in master
https://github.com/rdkit/rdkit/blob/c8cd4e7c20fc74defdab589973d6e80c6e137eec/Code/GraphMol/MolDraw2D/CMakeLists.txt#L24<https://urldefense.com/v3/__https:/github.com/rdkit/rdkit/blob/c8cd4e7c20fc74defdab589973d6e80c6e137eec/Code/GraphMol/MolDraw2D/CMakeLists.txt*L24__;Iw!!Dq7g1IpY!jnlnFJsArVN7aW97xCMs4-w16vumNdfMPuidF8OO_U4-8OND0py68ga3mutIm6HOscHSUnwsQ0SjMuZHik4X1-GmGZYvRRc$>
therefore there might be something wrong with the download. Or the checksum changed again.

For the latter case, the only solution I see for Spack is to create a patch<https://urldefense.com/v3/__https:/spack.readthedocs.io/en/latest/packaging_guide.html*patches__;Iw!!Dq7g1IpY!jnlnFJsArVN7aW97xCMs4-w16vumNdfMPuidF8OO_U4-8OND0py68ga3mutIm6HOscHSUnwsQ0SjMuZHik4X1-GmxMN6Eug$>.

**Comment by m-miller10** [comment]
clearing the cache didn't resolve the problem.  I created a crude patch that resolved the issue and rdkit built with maeparser.   I'm going to close this issue as I now have a version of rdkit.    I'll also see if I can apply these learnings to the newer version of rdkit which has a completely different cmake error.

**Comment by RMeli** [comment]
I'm glad you got it working. Let me know if there are other issues. I'd be happy to review PRs with fixes to RDKit in Spack (I'm not using RDKit much anymore, so I'm definitely missing a lot of issues...).
