### ISSUE TITLE
Installation issue: texlive

### ISSUE THREAD

**Issue by moloney** [LLNL/spack#46450]
### Steps to reproduce the issue

```console
$ spack install texlive@20240312
```

### Error message

<details><summary>Error message</summary>

<pre>
==> texlive: Executing phase: 'install'
==> Error: ProcessError: /arc/scratch1/airc/usr/byoe/repo/._internal/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_p/linux-rhel9-haswell/gcc-13.3.0/texlive-20240312-pknqpvf3i4eyc4zilfyndbia7hbzqkhz/bin/x86_64-linux/mtxrun: No such file or directory
    Command: '/arc/scratch1/airc/usr/byoe/repo/._internal/spack/opt/spack/__spack_path_placeholder__/__spack_path_placeholder__/__spack_path_p/linux-rhel9-haswell/gcc-13.3.0/texlive-20240312-pknqpvf3i4eyc4zilfyndbia7hbzqkhz/bin/x86_64-linux/mtxrun' '--generate'

</pre></details>

### Information on your system

* **Spack:** 0.23.0.dev0 (883e43e599921e824e71ac5352c3b79e48a03cd2)
* **Python:** 3.9.17
* **Platform:** linux-rhel9-sapphirerapids

### Additional information

Installing the previous version `20220321` works.

[spack-build-env.txt](https://github.com/user-attachments/files/17036424/spack-build-env.txt)
[spack-build-out.txt](https://github.com/user-attachments/files/17036428/spack-build-out.txt)

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have run `spack maintainers <name-of-the-package>` and **@mentioned** any maintainers
- [X] I have uploaded the build log and environment files
- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by rbberger** [comment]
The spack placeholders in the path look suspicious.

**Comment by rbberger** [comment]
Seems to be related: https://gitlab.archlinux.org/archlinux/packaging/packages/texlive-texmf/-/issues/4
