### ISSUE TITLE
petsc@3.21.5+rocm with rocm@6.1.2

### ISSUE THREAD

**Issue by chapman39** [LLNL/spack#46468]
### Steps to reproduce

I am trying to install petsc using rocm amd clang and it's failing during the configure step.

* spec: `petsc@3.21.5+rocm amdgpu_target=gfx90a`
* spack version: [develop 6df831ef00bec38d7f5f0cf5d1fb0c53e4573aa0](https://github.com/spack/spack/commit/6df831ef00bec38d7f5f0cf5d1fb0c53e4573aa0)
* system: tioga machine, `toss_4_x86_64_ib_cray`
* concretizer tree: [concretizer-tree.txt](https://github.com/user-attachments/files/17048747/concretizer-tree.txt)
* spack.yaml: [spack.yaml.txt](https://github.com/user-attachments/files/17048748/spack.yaml.txt)
* petsc spack build output: [spack-build-out.txt](https://github.com/user-attachments/files/17048750/spack-build-out.txt)
* petsc configure log (~37k lines): [configure.log](https://github.com/user-attachments/files/17048794/configure.log)
* `spack install` debug output: [spack-install-output.txt](https://github.com/user-attachments/files/17048752/spack-install-output.txt)

### Error message

```
==> Installing petsc-3.21.5-4jvmgdrqhu2y5qlyjfrj47uj473rqonb [26/26]
==> No binary for petsc-3.21.5-4jvmgdrqhu2y5qlyjfrj47uj473rqonb found: installing from source
==> Using cached archive: /usr/WS2/meemee/spack/spack/var/spack/cache/_source-cache/archive/4e/4eb1ec04c1a8988bd524f71f8d7d980dc1853d5be8791c0f19f3c09eef71fdd2.tar.gz
==> No patches needed for petsc
==> petsc: Executing phase: 'configure'
==> Error: ProcessError: Command exited with status 1:
    '/usr/tce/packages/python/python-3.9.12/bin/python3.9' 'configure' '--prefix=/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/petsc-3.21.5-4jvmgdrqhu2y5qlyjfrj47uj473rqonb' '--with-ssl=0' '--download-c2html=0' '--download-sowing=0' '--download-hwloc=0' '--with-make-exec=make' '--with-cc=/usr/tce/packages/cray-mpich-tce/cray-mpich-8.1.30-rocmcc-6.1.2/bin/mpicc' '--with-cxx=/usr/tce/packages/cray-mpich-tce/cray-mpich-8.1.30-rocmcc-6.1.2/bin/mpicxx' '--with-fc=/usr/tce/packages/cray-mpich-tce/cray-mpich-8.1.30-rocmcc-6.1.2/bin/mpif90' '--with-precision=double' '--with-scalar-type=real' '--with-shared-libraries=1' '--with-debugging=0' '--with-openmp=0' '--with-64-bit-indices=0' '--with-blas-lapack-lib=/usr/lib64/libopenblas.so' '--with-x=0' '--with-sycl=0' '--with-clanguage=C' '--with-cuda=0' '--with-hip=1' '--with-hip-include=/opt/rocm-6.1.2/include' '--with-metis=1' '--with-metis-include=/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/metis-5.1.0-udb2xge7x3icanmdj2yv4mjis5j4dtyx/include' '--with-metis-lib=/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/metis-5.1.0-udb2xge7x3icanmdj2yv4mjis5j4dtyx/lib/libmetis.so' '--with-hypre=0' '--with-parmetis=1' '--with-parmetis-include=/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/parmetis-4.0.3-qejqnbwuzru4bqz4nwz2lyxyi7kpbfhn/include' '--with-parmetis-lib=/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/parmetis-4.0.3-qejqnbwuzru4bqz4nwz2lyxyi7kpbfhn/lib/libparmetis.so' '--with-kokkos=0' '--with-kokkos-kernels=0' '--with-superlu_dist=1' '--with-superlu_dist-include=/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/superlu-dist-8.2.1-2nqrkt642putcfcbldcvir7qpew5adlp/include' '--with-superlu_dist-lib=/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/superlu-dist-8.2.1-2nqrkt642putcfcbldcvir7qpew5adlp/lib/libsuperlu_dist.so' '--with-ptscotch=0' '--with-suitesparse=0' '--with-hdf5=1' '--with-hdf5-include=/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/hdf5-1.14.3-mj7dexl4l3rgj5vohi2ipet6viekp2ja/include' '--with-hdf5-lib=/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/hdf5-1.14.3-mj7dexl4l3rgj5vohi2ipet6viekp2ja/lib/libhdf5.so' '--with-zlib=1' '--with-zlib-include=/usr/include' '--with-zlib-lib=/usr/lib64/libz.so' '--with-mumps=0' '--with-trilinos=0' '--with-fftw=0' '--with-valgrind=0' '--with-gmp=0' '--with-libpng=0' '--with-giflib=0' '--with-mpfr=0' '--with-netcdf=0' '--with-pnetcdf=0' '--with-moab=0' '--with-random123=0' '--with-exodusii=0' '--with-cgns=0' '--with-memkind=0' '--with-p4est=0' '--with-saws=0' '--with-yaml=0' '--with-hwloc=0' '--with-libjpeg=0' '--with-scalapack=0' '--with-strumpack=0' '--with-mmg=0' '--with-parmmg=0' '--with-tetgen=0' '--with-zoltan=0' '--with-hip-arch=gfx90a' 'HIPPPFLAGS=-I/opt/rocm-6.1.2/include -I/opt/rocm-6.1.2/include -I/opt/rocm-6.1.2/include -I/opt/rocm-6.1.2/include -I/opt/rocm-6.1.2/include -I/opt/rocm-6.1.2/include -I/opt/rocm-6.1.2/include -I/opt/rocm-6.1.2/include -I/opt/rocm-6.1.2/include -I/opt/rocm-6.1.2/include ' '--with-hip-lib=/opt/rocm-6.1.2/lib/libhipsparse.so /opt/rocm-6.1.2/lib/libhipblas.so /opt/rocm-6.1.2/lib/libhipsolver.so /opt/rocm-6.1.2/lib/librocsparse.so /opt/rocm-6.1.2/lib/librocsolver.so /opt/rocm-6.1.2/lib/librocblas.so  -L/opt/rocm-6.1.2/lib -lamdhip64'
See build log for details:
  /usr/WS2/meemee/spack/build_stage/spack-stage-petsc-3.21.5-4jvmgdrqhu2y5qlyjfrj47uj473rqonb/spack-build-out.txt
```

The `spack-build-out.txt` I'm directed to mentioned to look at `configure.log`, so that's what I did.

```
107 *********************************************************************************************
108            UNABLE to CONFIGURE with GIVEN OPTIONS (see configure.log for details):
109 ---------------------------------------------------------------------------------------------
110   Configure must be able to determined the version information for hip. It was unable to,
111   please send configure.log to petsc-maint@mcs.anl.gov
112 *********************************************************************************************
```

Searching the `configure.log` for "error:", I find the following error first. Though there is probably something failing beforehand.

```
  816 Executing: /usr/tce/packages/cray-mpich-tce/cray-mpich-8.1.30-rocmcc-6.1.2/bin/mpicc  -o /var/tmp/meemee/petsc-ggp79bff/config.setCompilers/conftest    /var/tmp/meemee/petsc-ggp79bff      /config.setCompilers/conftest.o  -lpetsc-ufod4vtr9mqHvKIQiVAm
  817 stdout:
  818 ld.lld: error: unable to find library -lpetsc-ufod4vtr9mqHvKIQiVAm
  819 clang: error: linker command failed with exit code 1 (use -v to see invocation)
  820 Possible ERROR while running linker: exit code 1
  821 stderr:
  822 ld.lld: error: unable to find library -lpetsc-ufod4vtr9mqHvKIQiVAm
  823 clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

### Information on your system

```
[meemee@tioga10:test_env]$ spack debug report
* **Spack:** 0.23.0.dev0 (6df831ef00bec38d7f5f0cf5d1fb0c53e4573aa0)
* **Python:** 3.9.12
* **Platform:** linux-rhel8-zen3
```

@balay @barrysmith @jedbrown

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by balay** [comment]
Can you use rocm-5.x for petsc-3.21?

the fix for rocm-6.x is in petsc@main

**Comment by balay** [comment]
To get petsc-3.21 built - you can try:
```diff
diff --git a/var/spack/repos/builtin/packages/petsc/package.py b/var/spack/repos/builtin/packages/petsc/package.py
index 64465cc42b..33b6f2e5b4 100644
--- a/var/spack/repos/builtin/packages/petsc/package.py
+++ b/var/spack/repos/builtin/packages/petsc/package.py
@@ -184,6 +184,16 @@ class Petsc(Package, CudaPackage, ROCmPackage):
             when="@3.20.0",
             sha256="ba327f8b2a0fa45209dfb7a4278f3e9a323965b5a668be204c1c77c17a963a7f",
         )
+        patch(
+            "https://gitlab.com/petsc/petsc/-/commit/20d5ecbf88175ced320006c488dcefa2efb1e67f.diff",
+            when="@3.21 ^hip@6:",
+            sha256="2904ea20c71e2f21b8475513c3e5de7465e328e2485ae706b003aa79314e3e7c",
+        )
+        patch(
+            "https://gitlab.com/petsc/petsc/-/commit/bdb83d9f3e3c55b3bd4c8732bfe2066c23f10f61.diff",
+            when="@3.21 ^hip@6:",
+            sha256="89cf2c9a01d4a3233c889dd98496a29bf43db1bc69195892f9e5405c537b87e3",
+        )
         patch("hip-5.6.0-for-3.18.diff", when="@3.18:3.19 ^hipsparse@5.6.0")
         patch("hip-5.7-plus-for-3.18.diff", when="@3.18:3.19 ^hipsparse@5.7:")
         patch(
```

cc: @eugeneswalker ref: https://github.com/spack/spack/issues/44600

**Comment by chapman39** [comment]
@balay I unfortunately get the same error when using `rocm@5.7.1`.

> ==> [2024-09-18-15:22:58.533454] No patches needed for petsc
==> [2024-09-18-15:22:58.589265] petsc: Executing phase: 'configure'
==> [2024-09-18-15:24:43.010834] Error: ProcessError: Command exited with status 1:
    '/usr/tce/packages/python/python-3.9.12/bin/python3.9' 'configure' '--prefix=/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/petsc-3.21.5-saklgyn57eozvlh73shzggc7jmv3xc6a' '--with-ssl=0' '--download-c2html=0' '--download-sowing=0' '--download-hwloc=0' '--with-make-exec=make' '--with-cc=/usr/tce/packages/cray-mpich-tce/cray-mpich-8.1.27-rocmcc-5.7.1/bin/mpicc' '--with-cxx=/usr/tce/packages/cray-mpich-tce/cray-mpich-8.1.27-rocmcc-5.7.1/bin/mpicxx' '--with-fc=/usr/tce/packages/cray-mpich-tce/cray-mpich-8.1.27-rocmcc-5.7.1/bin/mpif90' '--with-precision=double' '--with-scalar-type=real' '--with-shared-libraries=1' '--with-debugging=0' '--with-openmp=0' '--with-64-bit-indices=0' '--with-blas-lapack-lib=/usr/lib64/libopenblas.so' '--with-x=0' '--with-sycl=0' '--with-clanguage=C' '--with-cuda=0' '--with-hip=1' '--with-hip-include=/opt/rocm-5.7.1/hip/include' '--with-metis=1' '--with-metis-include=/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/metis-5.1.0-udb2xge7x3icanmdj2yv4mjis5j4dtyx/include' '--with-metis-lib=/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/metis-5.1.0-udb2xge7x3icanmdj2yv4mjis5j4dtyx/lib/libmetis.so' '--with-hypre=1' '--with-hypre-include=/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/hypre-2.31.0-2rj2chxvz3k6qj4om3wjmejbpg3s5nzc/include' '--with-hypre-lib=/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/hypre-2.31.0-2rj2chxvz3k6qj4om3wjmejbpg3s5nzc/lib/libHYPRE.so' '--with-parmetis=1' '--with-parmetis-include=/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/parmetis-4.0.3-upkfgfy6qlducywjlawmvxws62lvzed6/include' '--with-parmetis-lib=/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/parmetis-4.0.3-upkfgfy6qlducywjlawmvxws62lvzed6/lib/libparmetis.so' '--with-kokkos=0' '--with-kokkos-kernels=0' '--with-superlu_dist=1' '--with-superlu_dist-include=/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/superlu-dist-8.2.1-5uz3ge4rnzbieotk5wwihrtkwdn5e6gz/include' '--with-superlu_dist-lib=/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/superlu-dist-8.2.1-5uz3ge4rnzbieotk5wwihrtkwdn5e6gz/lib/libsuperlu_dist.so' '--with-ptscotch=0' '--with-suitesparse=0' '--with-hdf5=1' '--with-hdf5-include=/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/hdf5-1.14.3-5mjwscy3o6rqhissuywuja2s3oxzcwvy/include' '--with-hdf5-lib=/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/hdf5-1.14.3-5mjwscy3o6rqhissuywuja2s3oxzcwvy/lib/libhdf5.so' '--with-zlib=1' '--with-zlib-include=/usr/include' '--with-zlib-lib=/usr/lib64/libz.so' '--with-mumps=0' '--with-trilinos=0' '--with-fftw=0' '--with-valgrind=0' '--with-gmp=0' '--with-libpng=0' '--with-giflib=0' '--with-mpfr=0' '--with-netcdf=0' '--with-pnetcdf=0' '--with-moab=0' '--with-random123=0' '--with-exodusii=0' '--with-cgns=0' '--with-memkind=0' '--with-p4est=0' '--with-saws=0' '--with-yaml=0' '--with-hwloc=0' '--with-libjpeg=0' '--with-scalapack=0' '--with-strumpack=0' '--with-mmg=0' '--with-parmmg=0' '--with-tetgen=0' '--with-zoltan=0' '--with-hip-arch=gfx90a' 'HIPPPFLAGS=-I/opt/rocm-5.7.1/include -I/opt/rocm-5.7.1/include -I/opt/rocm-5.7.1/include -I/opt/rocm-5.7.1/include -I/opt/rocm-5.7.1/include -I/opt/rocm-5.7.1/include -I/opt/rocm-5.7.1/include -I/opt/rocm-5.7.1/include -I/opt/rocm-5.7.1/include -I/opt/rocm-5.7.1/include ' '--with-hip-lib=/opt/rocm-5.7.1/lib/libhipsparse.so /opt/rocm-5.7.1/lib/libhipblas.so /opt/rocm-5.7.1/lib/libhipsolver.so /opt/rocm-5.7.1/lib/librocsparse.so /opt/rocm-5.7.1/lib/librocsolver.so /opt/rocm-5.7.1/lib/librocblas.so  -L/opt/rocm-5.7.1/hip/lib -lamdhip64'
See build log for details:
  /usr/WS2/meemee/spack/build_stage/spack-stage-petsc-3.21.5-saklgyn57eozvlh73shzggc7jmv3xc6a/spack-build-out.txt

spack-build-out.txt:

```
*********************************************************************************************
           UNABLE to CONFIGURE with GIVEN OPTIONS (see configure.log for details):
---------------------------------------------------------------------------------------------
  --with-hip-lib=['/opt/rocm-5.7.1/lib/libhipsparse.so',
  '/opt/rocm-5.7.1/lib/libhipblas.so', '/opt/rocm-5.7.1/lib/libhipsolver.so',
  '/opt/rocm-5.7.1/lib/librocsparse.so', '/opt/rocm-5.7.1/lib/librocsolver.so',
  '/opt/rocm-5.7.1/lib/librocblas.so', '', '-L/opt/rocm-5.7.1/hip/lib', '-lamdhip64'] and
  --with-hip-include=['/opt/rocm-5.7.1/hip/include'] did not work
*********************************************************************************************
```

**Comment by balay** [comment]
Hm - this builds for me [on ubuntu-22.04].

 Perhaps this issue is due to differences on cray software stack. Can you re-attach configure.log from this failure?

Does `spack install petsc@main +rocm ..` also fail?

**Comment by eugeneswalker** [comment]
> To get petsc-3.21 built - you can try:
> ...
> cc: @eugeneswalker ref: #44600

This did it! Thank you!
```
==> Installing petsc-3.21.5-5qxef3hmtbo3vkkx4wmjgwzh5v6fxslq
==> No binary for petsc-3.21.5-5qxef3hmtbo3vkkx4wmjgwzh5v6fxslq found: installing from source
==> Fetching https://mirror.spack.io/_source-cache/archive/4e/4eb1ec04c1a8988bd524f71f8d7d980dc1853d5be8791c0f19f3c09eef71fdd2.tar.gz
==> Fetching https://gitlab.com/petsc/petsc/-/commit/20d5ecbf88175ced320006c488dcefa2efb1e67f.diff
==> Fetching https://gitlab.com/petsc/petsc/-/commit/bdb83d9f3e3c55b3bd4c8732bfe2066c23f10f61.diff
==> Applied patch https://gitlab.com/petsc/petsc/-/commit/20d5ecbf88175ced320006c488dcefa2efb1e67f.diff
==> Applied patch https://gitlab.com/petsc/petsc/-/commit/bdb83d9f3e3c55b3bd4c8732bfe2066c23f10f61.diff
==> petsc: Executing phase: 'configure'
==> petsc: Executing phase: 'build'
==> petsc: Executing phase: 'install'
==> petsc: Successfully installed petsc-3.21.5-5qxef3hmtbo3vkkx4wmjgwzh5v6fxslq
  Stage: 3.96s.  Configure: 2m 2.11s.  Build: 1m 6.93s.  Install: 1.89s.  Post-install: 2.19s.  Total: 3m 17.29s
[+] /spack/opt/spack/linux-ubuntu22.04-x86_64_v3/gcc-11.4.0/petsc-3.21.5-5qxef3hmtbo3vkkx4wmjgwzh5v6fxslq
```

Should I make PR to update petsc Spack package with these patches?

**Comment by balay** [comment]
Sure - adding these compatibility patches for petsc-3.21 might help with some builds

petsc-3.22 is scheduled by the month end - so that should also help [with rocm6+]

**Comment by chapman39** [comment]
@balay 
[configure-with-rocm-5.log](https://github.com/user-attachments/files/17065390/configure-with-rocm-5.log)

**Comment by balay** [comment]
```
In file included from /opt/rocm-5.7.1/hip/include/hip/amd_detail/../../../../include/hip/amd_detail/amd_hip_runtime.h:114:
/opt/rocm-5.7.1/hip/include/hip/amd_detail/amd_device_functions.h:32:2: warning: "amd_device_functions.h has moved to /opt/rocm-5.7.1/include/hip/amd_detail and package include paths have changed. Provide include path as /opt/rocm-5.7.1/include when using cmake packages." [-W#warnings]
#warning "amd_device_functions.h has moved to /opt/rocm-5.7.1/include/hip/amd_detail and package include paths have changed. Provide include path as /opt/rocm-5.7.1/include when using cmake packages."
```

I suspect these warnings are triggering build failures.

```
--with-hip-include=/opt/rocm-5.7.1/hip/include
```

Would be good try a change to  `--with-hip-include=/opt/rocm-5.7.1/include` [via a change to hip package spec in this build]

Maybe @eugeneswalker has better suggestions on how to update hip package spec to avoid these warnings..

**Comment by chapman39** [comment]
@balay thanks! that appears to have resolved the configure issue.

i got the following build error (see below). i was able to resolve the build error by adding these flags to my spack.yaml compiler section. let me know if there is a better solution:

```yaml
flags:
        cflags: -O0
        cxxflags: -O0
```

>  1008    /usr/tce/packages/cray-mpich-tce/cray-mpich-8.1.27-rocmcc-5.7.1/bin/mpicc -c -fPIC -Wall -Wwrite-strings -Wno-unknown-pragmas -fstack-protector -Qunused-arguments -fvisibility=hidden -g 
         -O3  -I/usr/WS2/meemee/spack/build_stage/spack-stage-petsc-3.21.5-azkj62p7shkreycg32c34aqvphhll6xi/spack-src/include -I/usr/WS2/meemee/spack/build_stage/spack-stage-petsc-3.21.5-azkj62p7
         shkreycg32c34aqvphhll6xi/spack-src/arch-linux-c-opt/include -I/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/hypre-2.31.0-d6or4mc4yv2osyvgjkaj7ivqwgju35yb/include -I/usr/WS2/meemee/spack/T
         PLs_cray/clang-17.0.0/superlu-dist-8.2.1-74n3ces3zd3q6jtx5jukvzilbbgeste7/include -I/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/parmetis-4.0.3-upkfgfy6qlducywjlawmvxws62lvzed6/include -
         I/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/metis-5.1.0-udb2xge7x3icanmdj2yv4mjis5j4dtyx/include -I/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/hdf5-1.14.3-5mjwscy3o6rqhissuywuja2s3oxz
         cwvy/include -I/usr/include -I/opt/rocm-5.7.1/include    -MMD -MP /usr/WS2/meemee/spack/build_stage/spack-stage-petsc-3.21.5-azkj62p7shkreycg32c34aqvphhll6xi/spack-src/src/mat/impls/baij
         /seq/baij2.c -o arch-linux-c-opt/obj/src/mat/impls/baij/seq/baij2.o

 > 1009 fatal error: error in backend: Instruction Combining seems stuck in an infinite loop after 1000 iterations. 1010 PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script. 1011 Stack dump: 1012 0. Program arguments: /opt/rocm-5.7.1/llvm/bin/clang -march=znver3 -mtune=znver3 -I/usr/WS2/meemee/spack/build_stage/spack-stage-petsc-3.21.5-azkj62p7shkreycg32c34aqvphhll6xi/spack-src/i nclude -I/usr/WS2/meemee/spack/build_stage/spack-stage-petsc-3.21.5-azkj62p7shkreycg32c34aqvphhll6xi/spack-src/arch-linux-c-opt/include -I/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/hyp re-2.31.0-d6or4mc4yv2osyvgjkaj7ivqwgju35yb/include -I/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/superlu-dist-8.2.1-74n3ces3zd3q6jtx5jukvzilbbgeste7/include -I/usr/WS2/meemee/spack/TPLs _cray/clang-17.0.0/parmetis-4.0.3-upkfgfy6qlducywjlawmvxws62lvzed6/include -I/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/metis-5.1.0-udb2xge7x3icanmdj2yv4mjis5j4dtyx/include -I/usr/WS2/ meemee/spack/TPLs_cray/clang-17.0.0/hdf5-1.14.3-5mjwscy3o6rqhissuywuja2s3oxzcwvy/include -I/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/superlu-dist-8.2.1-74n3ces3zd3q6jtx5jukvzilbbgeste 7/include -I/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/parmetis-4.0.3-upkfgfy6qlducywjlawmvxws62lvzed6/include -I/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/metis-5.1.0-udb2xge7x3ican mdj2yv4mjis5j4dtyx/include -I/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/hypre-2.31.0-d6or4mc4yv2osyvgjkaj7ivqwgju35yb/include -I/usr/WS2/meemee/spack/TPLs_cray/clang-17.0.0/hdf5-1.14.3 -5mjwscy3o6rqhissuywuja2s3oxzcwvy/include -I/opt/rocm-5.7.1/include -I/opt/cray/pe/mpich/8.1.27/ofi/amd/5.0/include -I/opt/rocm-5.7.1/include -I/opt/rocm-5.7.1/llvm/include -I/usr/tce/pa ckages/cray-mpich-tce/cray-mpich-8.1.27-rocmcc-5.7.1/include -I/usr/include -c -fPIC -Wall -Wwrite-strings -Wno-unknown-pragmas -fstack-protector -Qunused-arguments -fvisibility=hidden - g -O3 -MMD -MP /usr/WS2/meemee/spack/build_stage/spack-stage-petsc-3.21.5-azkj62p7shkreycg32c34aqvphhll6xi/spack-src/src/mat/impls/baij/seq/baij2.c -o arch-linux-c-opt/obj/src/mat/impls/ baij/seq/baij2.o 1013 1. parser at end of file 1014 2. Optimizer 1015 #0 0x00000000020d5468 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/rocm-5.7.1/llvm/bin/clang+0x20d5468)

**Comment by balay** [comment]
> fatal error: error in backend: Instruction Combining seems stuck in an infinite loop after 1000 iterations. 1010 PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/

yeah to work around "internal compiler errors" I also tweak compiler/optimization flags to see if any such change can overcome it.

glad you have a working build now!

**Comment by chapman39** [comment]
thanks for the help! also, i found i could simply apply the flag to petsc itself by adding `^petsc cflags=-O0` to the spec, which is a bit nicer. ill consider this issue closed.
