### ISSUE TITLE
package_list.html missing from Spack's docs -- dead links for spack shields!

### ISSUE THREAD

**Issue by freifrauvonbleifrei** [LLNL/spack#46604]
It appears that this page https://spack.readthedocs.io/en/latest/package_list.html has been removed from the docs -- which means that most packages using the spack shield from shields.io now link to a dead link. 

Example for DisCoTec code:
[![Latest spack version](https://img.shields.io/spack/v/discotec)](https://spack.readthedocs.io/en/latest/package_list.html#discotec)

Was this an intentional choice? If yes, where to best link instead to demonstrate there is a spack package for a particular software?

**Comment by alalazo** [comment]
Removal was intentional. We could use a link from https://packages.spack.io/ instead

**Comment by freifrauvonbleifrei** [comment]
Yeah, I think I am quite happy with
[![Latest spack version](https://img.shields.io/spack/v/discotec)](https://packages.spack.io/package.html?name=discotec)

markdown diff:
```diff
- [![Latest spack version](https://img.shields.io/spack/v/discotec)](https://spack.readthedocs.io/en/latest/package_list.html#discotec)
+ [![Latest spack version](https://img.shields.io/spack/v/discotec)](https://packages.spack.io/package.html?name=discotec)
```

thx!
