### ISSUE TITLE
How to enforce concretisation preferences specified in packages.yaml?

### ISSUE THREAD

**Issue by pramodk** [LLNL/spack#4665]
I have following in `packages.yaml` : 

```bash
    packageA:
        compiler: [gcc@4.9.3]
```

Now if I try to build `packageB` with `clang` which has `packageA` as dependency, I thought `packageA` will be concretised with `gcc` but this is not the case. I can explicitly specify this at command line `... ^packageA %gcc@4.9.3`  but wonder if there is any way to enforce the rule/preferences specified in `packages.yaml`

**Comment by adamjstewart** [comment]
Unfortunately not. This is a long-standing issue that I first raised in #1371. I've seen no progress on resolving this issue.

**Comment by pramodk** [comment]
Ah ok, thanks for pointer. I will close this issue!
