### ISSUE TITLE
clingo-bootstrap: pyclingo@spack fails on Fedora 41

### ISSUE THREAD

**Issue by hainest** [LLNL/spack#46754]
### Steps to reproduce

```
docker run --rm -it fedora:41

yum install -y cmake gcc g++ git m4 autoconf python3 python3-devel pkgconf curl patch which
git clone --depth=1 --branch=develop https://github.com/spack/spack
alias spack='/spack/bin/spack'
spack compiler find

python3 --version
  Python 3.13.0rc3

spack bootstrap now
```

### Error message

```
spack bootstrap now

  >> 1993    /tmp/root/spack-stage/spack-stage-clingo-bootstrap-spack-zdraelqnmaiebssvxme3ls6bxnkx4fuw/spack-src/libpyclingo/pyclingo.cc:10466:14: error: 'Py
             Eval_ThreadsInitialized' was not declared in this scope
     1994    10466 |         if (!PyEval_ThreadsInitialized()) { PyEval_InitThreads(); }
```

`PyEval_ThreadsInitialized` was deprecated in Python 3.9 and removed in 3.11, but it looks like Fedora's package didn't remove it until 3.13 (Fedora 40's 3.12 works fine). Currently, clingo@spack points to 2a0256670 which is from 2020. This is likely due to pyclingo being removed by f92009c4 in 2021. This leaves spack in a bind. However, I was able to find a workaround. 

```
pip3 install clingo
spack clean -a
spack bootstrap now

spack spec zlib

    Input spec
    --------------------------------
     -   zlib
    
    Concretized
    --------------------------------
     -   zlib@1.3.1%gcc@14.2.1+optimize+pic+shared build_system=makefile arch=linux-fedora41-zen3
     -       ^gcc-runtime@14.2.1%gcc@14.2.1 build_system=generic arch=linux-fedora41-zen3
    [e]      ^glibc@2.40%gcc@14.2.1 build_system=autotools arch=linux-fedora41-zen3
     -       ^gmake@4.4.1%gcc@14.2.1~guile build_system=generic arch=linux-fedora41-zen3
```

I don't know how much that will be of help. Full log is attached.
[clino-fedora41.log](https://github.com/user-attachments/files/17246720/clino-fedora41.log)

### Information on your system

```
* **Spack:** 0.23.0.dev0 (4cace0cb620adea1a0a2d74b66536585d3b5666a)
* **Python:** 3.13.0rc3
* **Platform:** linux-fedora41-zen3
```

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by haampie** [comment]
Let's see if we can backport/patch anything, otherwise newer versions of clingo work fine as well. We pinned the `@spack` version because it performed better.
