### ISSUE TITLE
Storing build logging information

### ISSUE THREAD

**Issue by garvct** [LLNL/spack#469]
For each spack build I would ideally like to have a copy of the building log and a copy of the package.py deposited the the install prefix.
My current work-around is to (set use_tmp_stage = False in __init__.py) and build with the --keep-stage flag. This is not ideal because I am now building in a shared slow permanent filesystem.
I would like to have the option of building in a local fast filesystem, but keeping a copy of the build log and package.py in my install prefix.

Thanks
Cormac.

**Comment by tgamblin** [comment]
@garvct: FYI, the build log is already installed to `$prefix/.spack`.  The `package.py` files are not.

#475 adds additional provenance to the `.spack` directory.  See if you like the way it's done there.
