### ISSUE TITLE
Allow skipping compiler checking during concretization.

### ISSUE THREAD

**Issue by zetxtech** [LLNL/spack#46932]
### Summary

During the concretization process, all compilers undergo testing, which is run multiple times and is particularly time-consuming for certain compilers that require lengthy startup times, such as Intel ICC. This has become a significant time-drain during concretization. Please provide a configuration to disable this feature, or use cache to store info for defined compilers.

### Rationale

Run:
```bash
spack --debug spec -I gcc
```
In debug log:
```
[2024-10-13-00:09:02.902192] '/usr/bin/gcc' '-v' '/tmp/spack-implicit-link-infoym_ku0em/main.c' '-o' '/tmp/spack-implicit-link-infoym_ku0em/output'
...(multiple times)
```

### Description

This feature may relate to:
https://github.com/spack/spack/blob/e65be13056b1b71d1c5fe92bdf58d3713cd76473/lib/spack/spack/compiler.py#L446-L476
which is called in:
https://github.com/spack/spack/blob/e65be13056b1b71d1c5fe92bdf58d3713cd76473/lib/spack/spack/solver/asp.py#L324-L325
https://github.com/spack/spack/blob/e65be13056b1b71d1c5fe92bdf58d3713cd76473/lib/spack/spack/solver/asp.py#L3167-L3173
This will call every defined compilers, which may consume a lot of time.

### Additional information

Also used in:
https://github.com/spack/spack/blob/e65be13056b1b71d1c5fe92bdf58d3713cd76473/lib/spack/spack/compiler.py#L403-L425
It may be a better pracitice to cache `compiler_verbose_output`.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
My suggestion is to make yet another file system cache of the form `hash(compiler entry) => compiler_verbose_output`.
