### ISSUE TITLE
multiple downloads of the same software

### ISSUE THREAD

**Issue by garvct** [LLNL/spack#470]
It appears that by default spack always downloads software before installing. It would be nice to have an option to store the downloaded software locally (maybe update a local mirror), so if you have a need to install the same software again it does not attempt to download it (just grabs the local copy). 

Thanks,
Cormac.

**Comment by alalazo** [comment]
You may want to have a look at the `spack mirror` command on the `develop` branch, which does exactly that.

**Comment by tgamblin** [comment]
@trws recently added the ability to recursively fetch dependencies, too, so you can easily build a mirror of just the software you want.

On the feature list is the download cache idea described in #281, which is similar to what you're mentioning.  Likely we would just make a mirror in `~/.spack`

**Comment by tgamblin** [comment]
Closing as duplicate -- please reopen if this doesn't answer your question!
