### ISSUE TITLE
Hipsparse may not be a dependency of MFEM

### ISSUE THREAD

**Issue by adrienbernede** [LLNL/spack#47044]
@v-dobrev although the MFEM package declares `hipsparse` as a dependency...

https://github.com/spack/spack/blob/adaa0a4863a810fa99d392a96c372f8be45e81f4/var/spack/repos/builtin/packages/mfem/package.py#L284

`hipsparse` is treated as if it should be found within the rocm installation.

https://github.com/spack/spack/blob/adaa0a4863a810fa99d392a96c372f8be45e81f4/var/spack/repos/builtin/packages/mfem/package.py#L970

https://github.com/spack/spack/blob/adaa0a4863a810fa99d392a96c372f8be45e81f4/var/spack/repos/builtin/packages/mfem/package.py#L972

Being a dependency this results in Spack trying to install `hipsparse` anyways. I suggest turning hipsparse into a variant.

[EDIT]
Actually, the best thing to do could be to allow `hipsparse` to be found where it has been installed by Spack. In practice, this would allow us to set `hipsparse` as an externally installed package.
This sounds like the only way after uncovering that we have a similar issue with `rocrand`, which opens to door to the way `hypre` is written, with many rocm tools declared as dependencies.

[[EDIT]]
Declaring hip "tools" a as depencies is fine. I think the issues I am facing have to do with the fact those tools moved within the rocm install tree with version changes.

**Comment by v-dobrev** [comment]
Hi @adrienbernede, `hipsparse` is a required dependency under the specified conditions: `@4.4.0:+rocm`. The assumption in the `mfem` package is that all ROCm/HIP packages (`hip`, `hipsparse`, `hipblas`, `rocblas`, `rocrand`, etc) are all either external or they are all installed by Spack -- anything else does not really make sense to me. Therefore, the logic for `hipsparse` checks if `hip` is external and handles the two cases based on that.

I think the logic is correct and it has been tested on both external HIP installs (by me) and on Spack installed ROCm/HIP (by Spack CI).

Are you encountering any issues with the current state of the `mfem` package? If so, what are they?

**Comment by adrienbernede** [comment]
On `tioga` with `rocm@6.2.0` spack builds hipsparse for MFEM while it's defined as an external.

On `corona` with `rocm@5.7.1` mfem fails to find the hipsparse externally installed.
https://lc.llnl.gov/gitlab/radiuss/radiuss-spack-testing/-/jobs/2185376

Please note that in both cases, hipsparse now lives in `/opt/rocm-x.x.x/`, not in the `hip` subdirectory anymore.

**Comment by adrienbernede** [comment]
@v-dobrev it may be a problem with how I set the externals... checking that.

**Comment by adrienbernede** [comment]
Definitely a problem on my side...
