### ISSUE TITLE
Allow users to direct on the command line where to put the source_cache

### ISSUE THREAD

**Issue by calcuttj** [LLNL/spack#47169]
### Summary

One can specify in configuration where to put  when building (i.e. `source cache` in an environment's spack.yaml)

It would be good to let people change this on the fly when running spack install 

### Rationale

This was an easy pitfall to run into when trying to build a package in my environment while using a spack instance on a read only file system. 

### Description

add --source_cache option to spack install that directs where to put fetched tars/repos/etc

In addition to overriding the current source_cache, it might be useful to have it add the source_cache to the current spack.yaml i.e. if one is using an environment

### Additional information

<pre>
spack_build_test$ spack --version
0.22.0
</pre>

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by haampie** [comment]
You can already using

```
spack -c config:source_cache:/tmp install ...
```

try out

```
spack -c config:source_cache:/tmp config blame config
```
