### ISSUE TITLE
Allow site configuration without editing source files

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#472]
Source files (eg: spack/__init__.py) are part of the GitHub repository; Spack should work with the same source files across all sites.  The site should be configured with one or more files that are NOT part of the git repo.  Such files would be searched for in SPACK_HOME, $HOME, etc. and loaded if found.

**Comment by tgamblin** [comment]
Yes. :+1: This is coming but not fully done yet.  It'll be in for 1.0.

**Comment by citibeth** [comment]
Unless I'm mistaken, I think #120 will do this.
