### ISSUE TITLE
fmi4cpp: add new package

### ISSUE THREAD

**Issue by prudhomm** [LLNL/spack#47239]
### Summary

FMI4cpp is a cross-platform FMI 2.0 implementation written in modern C++.
FMI4cpp supports both Co-simulation and Model Exchange.

### Rationale

Packaging FMI4cpp for Spack is highly beneficial for the scientific and engineering communities that rely on model-based design and simulation. FMI4cpp is a modern C++ implementation of the Functional Mock-up Interface (FMI) 2.0 standard, which facilitates the exchange and co-simulation of dynamic models across different software tools.

FMI is an open standard that allows simulation models to be packaged into Functional Mock-up Units (FMUs). These FMUs can be shared and integrated into various simulation environments, promoting interoperability and flexibility in model-based development. The benefits of FMI include:

- Tool Independence: Enables models developed in one tool to be used in another without compatibility issues.
- Reusability: Encourages the reuse of models across different projects and platforms.
- Collaboration: Simplifies collaboration between teams using different tools and languages.
- Efficiency: Reduces duplication of effort by allowing models to be easily shared and integrated.

### Description

package FMI4cpp which has a FMI 2.0 implementation for Co-simulation and Model Exchange.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by alalazo** [comment]
@prudhomm No need to open an issue to add new packages, just open a PR for it :wink: Also, the "feature" label is for feature proposal / requests on core Spack. Feel free to ping me, or any other maintainer, when you open a PR for `fmi4cpp`. Thanks!

**Comment by prudhomm** [comment]
Thanks for the info. Isn't it spackbot who added the label?
I don't think i have the permissions to add labels

**Comment by alalazo** [comment]
No, it's the template you select when you open an issue. Each one of them has labels associated with it:
![Screenshot from 2024-10-28 09-29-24](https://github.com/user-attachments/assets/41e5da3b-3e06-4825-8bf9-b0fc31209e20)
