### ISSUE TITLE
can't install vasp@6.4.3 with scalapack

### ISSUE THREAD

**Issue by SQLimit** [LLNL/spack#47246]
### Steps to reproduce

```spack spec -I --fresh vasp@6.4.3 +scalapack```

### Error message

```
$ spack spec -I --fresh vasp@6.4.3 +scalapack
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    vasp@6.4.3+scalapack is unsatisfiable
```

### Information on your system

* **Spack:** 0.23.0.dev0 (c348891c07a3d6cdd4cd2b828086527bcc6f1e81)
* **Python:** 3.11.2
* **Platform:** linux-debian12-zen2

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
Similar to #47247 In the `vasp` package we have:
```console
variant("scalapack", default=False, when="@:5", description="Enables build with SCALAPACK")
```
This means that the `scalapack` variant exists only for `vasp@:5` Since you explicitly asked for `vasp@6.4.3` the problem is unsat. Again, we can improve the error message, but the input spec has no solutions given the current packages.

**Comment by SQLimit** [comment]
thanks for your reply

> ```
> variant("scalapack", default=False, when="@:5", description="Enables build with SCALAPACK")
> ```
> 
also, there have 
```
    depends_on("scalapack", when="+scalapack")
    # wiki (and makefiles) suggest scalapack is expected in 6:
    depends_on("scalapack", when="@6:")
```
does it mean that scalapack is supported and suggested in vasp@6?

**Comment by alalazo** [comment]
@SQLimit It means it's added without a variant from version 6 onward. Basically, it should work if you omit `+scalapack`

**Comment by SQLimit** [comment]
> @SQLimit It means it's added without a variant from version 6 onward. Basically, it should work if you omit `+scalapack`

I see, thanks again for your reply.
