### ISSUE TITLE
installation error: gromacs@main +sycl

### ISSUE THREAD

**Issue by SQLimit** [LLNL/spack#47247]
### Steps to reproduce

```spack spec -I gromacs@main %gcc@15 +sycl ^sycl+rocm amdgpu_target=gfx1100```

but this worked ```spack spec -I gromacs@main %gcc@15 +sycl ^hipsycl+rocm amdgpu_target=gfx1100```

### Error message

```
spack spec -I gromacs@main %gcc@15 +sycl ^sycl+rocm amdgpu_target=gfx1100
==> Error: Spack concretizer internal error. Please submit a bug report and include the command, environment if applicable and the following error message.
    gromacs@main%gcc@15+sycl ^sycl+rocm amdgpu_target=gfx1100 is unsatisfiable
```

### Information on your system

* **Spack:** 0.23.0.dev0 (fea2171672737687195572d920cc911d3c194229)
* **Python:** 3.11.2
* **Platform:** linux-debian12-zen4

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
In the following spec:
```
$ spack spec -I gromacs@main %gcc@15 +sycl ^sycl+rocm amdgpu_target=gfx1100
```
`sycl` is a virtual package, and as such it does not support having variants. I'll submit a PR to improve the error message, but the input spec is malformed.

For the record, these facts are currently generated:
```
imposed_constraint(52750,"virtual_node","sycl").
imposed_constraint(52750,"variant_set","sycl","amdgpu_target","gfx1100").
imposed_constraint(52750,"variant_set","sycl","rocm","True").
imposed_constraint(52750,"variant_default_value_from_cli","gromacs","sycl","True").
imposed_constraint(52750,"variant_default_value_from_cli","sycl","amdgpu_target","gfx1100").
imposed_constraint(52750,"variant_default_value_from_cli","sycl","rocm","True").
```
which _can't_ be satisfied.
