### ISSUE TITLE
Compiler dependency

### ISSUE THREAD

**Issue by jiseung** [LLNL/spack#4733]
Is there a way to specify that a package *must* be built using clang? It will build with other compilers, but the executable will fail if clang wasn't used.

**Comment by davydden** [comment]
U can declare other compilers to be conflicting: conflict('%gcc')

**Comment by adamjstewart** [comment]
@davydden is correct. Unfortunately, there is currently no "not" in the spec syntax, so you can't say `conflicts('not %clang')`. We've talked about reworking our compiler support to make it more similar to `depends_on`, but I haven't seen any progress on this front.

**Comment by jiseung** [comment]
Are there only six compilers in total for Spack? gcc, intel, pgi, xl, nag, and clang?

Also, is there a way to reconcretize spec or some way to resolve this issue? 
`$ spack spec nut
Input spec
--------------------------------
nut

Normalized
--------------------------------
nut
    ^cmake
    ^random123

Concretized
--------------------------------
==> Error: Conflicts in concretized spec "nut@serial%gcc@4.8.5 arch=linux-rhel7-x86_64 /unrgeco"

List of matching conflicts:

1. "%gcc" conflicts with "nut" in spec "nut@serial%gcc@4.8.5 arch=linux-rhel7-x86_64 ^cmake@3.8.1%gcc@4.8.5~doc+ncurses+openssl+ownlibs~qt arch=linux-rhel7-x86_64 ^ncurses@6.0%gcc@4.8.5~symlinks arch=linux-rhel7-x86_64 ^openssl@1.0.2k%gcc@4.8.5 arch=linux-rhel7-x86_64 ^pkg-config@0.29.2%gcc@4.8.5+internal_glib arch=linux-rhel7-x86_64 ^random123@1.09%gcc@4.8.5 arch=linux-rhel7-x86_64 ^zlib@1.2.11%gcc@4.8.5+pic+shared arch=linux-rhel7-x86_64"`

**Comment by adamjstewart** [comment]
> Are there only six compilers in total for Spack?

You can see a list of supported compilers with `ls lib/spack/spack/compilers`. If it's not there, it isn't supported.

> is there a way to reconcretize spec or some way to resolve this issue?

Unfortunately not. I really wish there were. There are quite a few packages that don't build with PGI, and I happen to need to build things with PGI that depend on these packages.

**Comment by jiseung** [comment]
Thank you so much!
