### ISSUE TITLE
Question about how to specify arguments to qmake in spack

### ISSUE THREAD

**Issue by jgalarowicz** [LLNL/spack#4745]
Hi all,

I'm trying to add a new package, cbtf-argonavis-gui, which requires a qmake line that creates the Makefile.  The code in def install currently looks like this:
```python
    def install(self, spec, prefix):
        options = ['-o Makefile openss-gui.pro']
        qmake = which('qmake')
        qmake(*options)
        #qmake('-o Makefile openss-gui.pro')
        make()
        make("install")
```

When ever I try to build, it appears that qmake doesn't think there is an option -o Makefile openss-gui.pro.   However, I can do that command outside of spack.   So, I'm wondering if anyone can spot what I'm doing wrong.   Here is the output from spack:
```
==> Error: ProcessError: Command exited with status 1:
    '/home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/qt-5.9.1-jqgklthpzv3yktdnjftatzwaibs4vazx/bin/qmake' '-o Makefile openss-gui.pro'
/home/jeg/spack/var/spack/repos/builtin/packages/cbtf-argonavis-gui/package.py:93, in install:
     89       def install(self, spec, prefix):
     90   
     91           options = ['-o Makefile openss-gui.pro']
     92           qmake = which('qmake')
  >> 93           qmake(*options)
     94           #qmake('-o Makefile openss-gui.pro')
     95           make()
     96           make("install")

See build log for details:
  /tmp/jeg/spack-stage/spack-stage-3Garsy/cbtf-argonavis-gui/spack-build.out
[jeg@localhost packages]$ cat /tmp/jeg/spack-stage/spack-stage-3Garsy/cbtf-argonavis-gui/spack-build.out
==> '/home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/qt-5.9.1-jqgklthpzv3yktdnjftatzwaibs4vazx/bin/qmake' '-o Makefile openss-gui.pro'
*****Unknown option -o Makefile openss-gui.pro**
Usage: /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/qt-5.9.1-jqgklthpzv3yktdnjftatzwaibs4vazx/bin/qmake [mode] [options] [files]
```

This is my full cbtf-argonavis-gui/package.py file:
```python
[jeg@localhost packages]$ cat cbtf-argonavis-gui/package.py
<header text removed>
from spack import *
class CbtfArgonavisGui(Package):
    """CBTF Argo Navis GUI project contains the GUI that views CUDA performance
       information.

    """
    homepage = "http://sourceforge.net/p/cbtf/wiki/Home/"
    # Mirror access template example
    url = "file:/home/jeg/cbtf-argonavis-gui-0.8.1.tar.gz"
    version('0.8.1', '9bdbffcc9259875bca80e2bc3a660cc7')
    #version('0.8.1', branch='master',
    #        git='https://github.com/OpenSpeedShop/cbtf-argonavis-gui.git')

    depends_on("cmake@3.0.2", type='build')
    depends_on("openspeedshop+noqt3gui")
    depends_on('qt@4.8.6:')
    depends_on("boost@1.50.0:1.59.0")
    depends_on("cbtf")
    depends_on("cbtf-krell")
    depends_on("cbtf-argonavis")
    depends_on("cuda")
    depends_on("mrnet@5.0.1:+lwthreads", when='+cbtf')
    depends_on("xerces-c@3.1.1:")
    depends_on("graphviz")
    depends_on("QtGraph")
    parallel = False

    def setup_environment(self, spack_env, run_env):
        """Set up the compile and runtime environments for a package."""
        spack_env.set('BOOSTROOT', self.spec['boost'].prefix)
        spack_env.set('CBTF_ROOT', self.spec['cbtf'].prefix)
        spack_env.set('CBTF_KRELL_ROOT', self.spec['cbtf-krell'].prefix)
        spack_env.set('CBTF_ARGONAVIS_ROOT', self.spec['cbtf-argonavis'].prefix)
        spack_env.set('OSS_CBTF_ROOT', self.spec['openspeedshop'].prefix)
        spack_env.set('GRAPHVIZ_ROOT', self.spec['graphviz'].prefix)
        spack_env.set('QTGRAPHLIB_ROOT', self.spec['QtGraph'].prefix)
        spack_env.set('KRELL_ROOT_MRNET', self.spec['mrnet'].prefix)
        spack_env.set('KRELL_ROOT_XERCES', self.spec['xerces-c'].prefix)
        #spack_env.set('QTDIR', self.spec['qt'].prefix)

    def install(self, spec, prefix):
        options = ['-o Makefile openss-gui.pro']
        qmake = which('qmake')
        qmake(*options)
        #qmake('-o Makefile openss-gui.pro')
        make()
        make("install")
```

**Comment by adamjstewart** [comment]
Replace:
```python
options = ['-o Makefile openss-gui.pro']
```
with:
```python
options = ['-o', 'Makefile',  'openss-gui.pro']
```
and you should be good to go. `which` creates an `Executable` which runs a `subprocess` when it gets called. Like `subprocess`, it needs a list of arguments. When you pass `'-o Makefile openss-gui.pro'` as a single argument, the shell puts quotes around:
```
qmake '-o Makefile openss-gui.pro'
```
Here the option isn't `-o`, it's `-o Makefile openss-gui.pro`, which obviously isn't a valid option.

**Comment by jgalarowicz** [comment]
Hi Adam @adamjstewart 
Thanks much for this information!   Much appreciated!
Jim G

I get this now, but I think that is because I still have some build issues with the setup of the build environment.

See build log for details:
  /tmp/jeg/spack-stage/spack-stage-KGBcJ_/cbtf-argonavis-gui/spack-build.out
[jeg@localhost packages]$ cat /tmp/jeg/spack-stage/spack-stage-KGBcJ_/cbtf-argonavis-gui/spack-build.out
==> '/home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/qt-5.9.1-jqgklthpzv3yktdnjftatzwaibs4vazx/bin/qmake' '-o' 'Makefile' 'openss-gui.pro'
Info: creating stash file /tmp/jeg/spack-stage/spack-stage-KGBcJ_/cbtf-argonavis-gui/.qmake.stash
/home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/qt-5.9.1-jqgklthpzv3yktdnjftatzwaibs4vazx/mkspecs/features/toolchain.prf:154: Variable QMAKE_CXX.COMPILER_MACROS is not defined.
Project WARNING: /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/openspeedshop-2.3-4vbg4fyjbue2u2aqopibhtbwlls6w2z2/libopenss-queries-cuda.so was not found
Project WARNING: /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/openspeedshop-2.3-4vbg4fyjbue2u2aqopibhtbwlls6w2z2/lib/libopenss-queries-cuda.so was not found
Project WARNING: /home/jeg/spack/opt/spack/linux-fedora19-x86_64/gcc-4.8.3/openspeedshop-2.3-4vbg4fyjbue2u2aqopibhtbwlls6w2z2/lib64/libopenss-queries-cuda.so was not found
Project ERROR: Please ensure that you have already built the Open|SpeedShop tool framework.
[jeg@localhost packages]$ cd /tmp/jeg/spack-stage/spack-stage-KGBcJ_/cbtf-argonavis-gui
