### ISSUE TITLE
Help finding old discussion re: the tip under getting_started.html#build-your-own-compiler

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#4747]
I believe that I once stumbled across a discussion about the tip in the ["Building your own compiler" section of the getting started docs](http://spack.readthedocs.io/en/latest/getting_started.html#build-your-own-compiler).

My memory is that some people thought it would work and others didn't but that not many people actually follow the tip.

I can not find the discussion.  I *think* it was an Issue, but it might have been in the Google group.

Anyone remember?

**Comment by adamjstewart** [comment]
#4061 is the most recent discussion of this tip.

The reasoning is that if you aren't a sys admin and want to play around with Spack, you may end up blowing away your entire installation tree from time to time, but you don't necessarily want to delete all of your compilers. By building your compilers with a separate Spack installation, you can avoid accidentally deleting them.

**Comment by hartzell** [comment]
That's the one, thanks!
