### ISSUE TITLE
Makefile with file generating scripts

### ISSUE THREAD

**Issue by homerdin** [LLNL/spack#4758]
I am working on a makefile package that calls two scripts that generate files before creating the executable.  These files are generated in the stage, but the executable target does not see them.  Setting parallel to False does not fix the issue.  Does anyone know why this is happening?  I have worked around the issue by calling the scripts seperately in build:

``` python
   def build(self, spec, prefix):
        with working_dir('miniXyce_ref'):
            # Call Script Targets First to Generate Needed Files

            make('generate_info')
            make('common_files')
            make(*self.build_targets)
```

Here are the Makefile Targets:

```
all:common_files generate_info miniXyce.x

miniXyce.x:common_files $(MAIN_OBJ) $(OBJS) $(UTIL_OBJS) $(OPTIONAL_OBJS) *.hpp generate_info
        $(INSTRUMENT) $(CXX) $(CXXFLAGS) $(CPPFLAGS) $(MAIN_OBJ) $(OBJS) $(UTIL_OBJS) $(OPTIONAL_OBJS) -o miniXyce.x $(LDFLAGS) $(OPTIONAL_LIBS) $(LIBS)

common_files:
        ./get_common_files

generate_info:
        ./generate_info_header "$(CXX)" "$(CXXFLAGS)" "miniXyce" "MINIXYCE"```

**Comment by scheibelp** [comment]
If I add the following to your definition (and remove the definition of ```build```) then it builds:

```
    @property
    def build_directory(self):
        return join_path(self.stage.source_path, 'miniXyce_ref')
```

The ```build``` function is always called and will call ```make``` in the directory indicated by ```build_directory```, which defaults to the base directory unless you override it.

Feel free to reopen if this seems unresolved.
