### ISSUE TITLE
Spack assumes terminal output when sending stdout to a pipe

### ISSUE THREAD

**Issue by woodard** [LLNL/spack#4761]
The terminal coloration seems to be stuck on and doesn't turn off when stdout is directed into a pipe:
Consider:
spack find | sort | uniq -c | less
Which shows you something unreadable like:
      2 abyssESC[0;36m@2.0.2ESC[0m
      2 ackESC[0;36m@2.16ESC[0m
      2 adept-utilsESC[0;36m@1.0.1ESC[0m
      2 adiosESC[0;36m@1.11.1ESC[0m
      2 adlbxESC[0;36m@0.8.0ESC[0m
      2 adol-cESC[0;36m@2.6.2ESC[0m
when what you want to see is:
      2 abyss@2.0.2
      2 ack@2.16
      2 adept-utils@1.0.1
      2 adios@1.11.1
      2 adlbx@0.8.0
      2 adol-c@2.6.2
      2 albert@4.0a_opt4
The escape characters make it hard to make use the output in scripts. 

Spack already seems to detect the fact that it is not outputting to a terminal because when you do:

$ spack find | less

It doesn't print things in columns the way that it does when you simply do "spack find"

**Comment by adamjstewart** [comment]
Can you test out #3013 and see if it solves your problem? I would really like to see that PR merged.

**Comment by tgamblin** [comment]
@woodard: #3013 is merged -- can you see if piping works now?

**Comment by tgamblin** [comment]
Also it wouldn't be hard for us to add, e.g., json output for Spack find.
