### ISSUE TITLE
Makefile.  MPI compiler wrapper and LIBS

### ISSUE THREAD

**Issue by homerdin** [LLNL/spack#4768]
I am working with a Makefile package and adding `LIBS=-lm` to the make call.  This appears to prevent the wrappers from injecting flags. I needed to explicitly add flags to get it to build.  

```
            targets.append('FC={0}'.format(self.spec['mpi'].mpif77))
            targets.append('CC={0}'.format(self.spec['mpi'].mpicc))
            targets.append('LIBS=-lm -lgfortran -lmpi_usempi -lmpi_mpifh -lmpi')
```
It does not find the mpi libraries without the flags

**Comment by adamjstewart** [comment]
Spack's compiler wrappers don't tell the package what libraries to link to (`-l`), it tells them where to find the libraries (`-L`, `-I`, and RPATH). Maybe you should be using `+=` instead of overwriting the variables in the Makefile?
