### ISSUE TITLE
CDash Reporting not working as expected with long build names

### ISSUE THREAD

**Issue by jnhealy2** [LLNL/spack#47723]
CDash reports that contain build errors do not display on CDash when a long build name is passed to spack for the report.  This can be replicated by building a package that has build errors with the following command:

```command
spack install --cdash-track=track --cdash-upload-url=a-very-long...url <package>
```
where "a-very-long...url" is a string containing at least 256 characters.  In this case Spack creates a Build.xml file containing the build name and then uploads that XML to the provided CDash URL by first encoding the CDash track and CDash build name into the upload URL.  It appears that the CDash server truncates the build name as encoded in the URL to  255 characters, but the build name in the XML is still full-length.  This creates a build name miss-match between the build name as reported in the URL and the build name as reported in the XML.  When this happens the report looks like it was submitted correctly and the build line shows up on CDash with the correct number of errors.  However, when attempting to view the specifics of the build errors by clicking on them, a blank page containing only the following text is displayed:
```text
Site: test
Build Name: a-very-long...url
Build Time: 2024-11-21 14:37:44
Found 0 Errors
Warnings are here. 
```
It is relatively easy to generate long build names when using spack.  In my case this occurred as a result of using the definition of the spec (with all variants specified) for each package being reported.

I'm wondering what the best approach to fixing this is.  Should Spack do something to assert a max length for build names or perhaps this is an issue for Kitware to look into CDash side?  @zackgalbreath can you provide any insight into what the right approach might be here?

**Comment by jnhealy2** [comment]
@psakievich, tagging you in case you have any additional thoughts/input.

**Comment by zackgalbreath** [comment]
Sorry for the slow reply.

> Should Spack do something to assert a max length for build names or perhaps this is an issue for Kitware to look into CDash side? @zackgalbreath can you provide any insight into what the right approach might be here?

As you discovered, CDash currently limits build names to 191 characters by default. We could revisit this decision, but in the meantime I think the quickest way forward is to similarly truncate build names as generated by Spack.

**Comment by psakievich** [comment]
That seems reasonable to me.  Perhaps if we just truncate automatically and throw a warning. @jnhealy2 would you have time to implement that?

**Comment by jnhealy2** [comment]
Yes, I'll get started on this today.

**Comment by jrood-nrel** [comment]
We have this same problem I recently discovered in Exawind as well https://my.cdash.org/index.php?project=Exawind . It wouldn't show build warnings unless I truncated the build name, but it seems to work for me as long as the name is less than 255.
