### ISSUE TITLE
OneAPI packages have a non-conforming implementation of the `headers` property

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#47791]
### Steps to reproduce

See https://github.com/spack/spack/pull/47764#discussion_r1856395556

The `OneApi` packages implement the `header` property differently from all the other packages, ~and return a different type,~ see https://github.com/spack/spack/blob/develop/lib/spack/spack/build_systems/oneapi.py#L270

### Error message

No error message, but these packages don't have a list of files, but just a list of directories

### Information on your system

* **Spack:** 0.24.0.dev0 (3c220d098954af581a0ff0dfa2024b9142f64340)
* **Python:** 3.11.5
* **Platform:** linux-ubuntu20.04-icelake

### General information

- [X] I have run `spack debug report` and reported the version of Spack/Python/Platform
- [X] I have searched the issues of this repo and believe this is not a duplicate
- [X] I have run the failing commands in debug mode and reported the output

**Comment by alalazo** [comment]
At a closer look, they return an `HeaderList` - I'll lower priority and double check why this works on `gromacs` without accessing the `.directories` property.

**Comment by mabraham** [comment]
> At a closer look, they return an `HeaderList` - I'll lower priority and double check why this works on `gromacs` without accessing the `.directories` property.

My guess is that `HeaderList` inherits the `__str__` method from `FileList`, which joins a single-element list of directories into the single directory that was actually wanted by GROMACS.

**Comment by alalazo** [comment]
@mabraham I'm getting back to this:
```console
Spack version 0.24.0.dev0
Python 3.11.5, Linux x86_64
>>> 
>>> 
KeyboardInterrupt
>>> from spack.spec import Spec
>>> h = Spec("gromacs+itt")
>>> h.concretize()
>>> h1 = h["intel-oneapi-vtune"].package.headers
>>> h1
HeaderList([])
>>> str(h1)
''
>>> h1.directories
['/home/culpo/PycharmProjects/spack/opt/spack/linux-ubuntu20.04-icelake/gcc-10.5.0/intel-oneapi-vtune-2025.0.1-o6q2ihfgiu4olrt2mfho6cbfgg4txtex/vtune/2025.0/sdk/include']
```
Are you sure `gromacs` is getting a directory during configuration? I started a build right now to verify.

**Comment by alalazo** [comment]
@mabraham I was too quick in merging #47764, without verifying it first. This is what `cmake` gets:
```
'-DITTNOTIFY_INCLUDE_DIR='
```
So, I was correct in my first comment https://github.com/spack/spack/pull/47764#discussion_r1856395556 which I dismissed out of the reply. :sweat: Fix incoming

**Comment by mabraham** [comment]
> @mabraham I'm getting back to this:
> Are you sure `gromacs` is getting a directory during configuration? I started a build right now to verify.

I thought I was... but you're right. I saw ITT trace artifacts from a GROMACS build I did manually.
