### ISSUE TITLE
Use of "tags" attribute in packages

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#4781]
I noticed that a few packages lately introduced the attribute `tags`, e.g. :
```python
class Cloverleaf3d(MakefilePackage):
    """Proxy Application. CloverLeaf3D is 3D version of the
       CloverLeaf mini-app. CloverLeaf is a mini-app that solves
       the compressible Euler equations on a Cartesian grid,
       using an explicit, second-order accurate method.
    """

    homepage = "http://uk-mac.github.io/CloverLeaf3D/"
    url      = "http://mantevo.org/downloads/releaseTarballs/miniapps/CloverLeaf3D/CloverLeaf3D-1.0.tar.gz"

    tags = ['proxy-app']
    ...
```
Other packages go even further, and they have a last line in their docstring providing redundant information:
```python
class Aspa(MakefilePackage):
    """A fundamental premise in ExMatEx is that scale-bridging performed in
        heterogeneous MPMD materials science simulations will place important
        demands upon the exascale ecosystem that need to be identified and
        quantified.
        tags = proxy-app
    """
    tags = ['proxy-app']
    ...
```
In #4774 `tags` is only in the docstring (no attribute), and it uses a colon as a separator.

I would like to start a discussion on this, because I think we should decide how to tag packages before introducing multiple inconsistent ways of doing it. Also, in case none of the above is tied to a query mechanism, I think we should also decide which use we want to make of this information (e.g. where it can be used to filter a query, and what should be the result).

**Comment by davydden** [comment]
> we should decide how to tag packages before introducing multiple inconsistent ways of doing it

:+1:

FYI, we have had some discussion here https://groups.google.com/d/msg/spack/zGs-0RKz3_U/ybkeTDxTCQAJ  , https://github.com/LLNL/spack/issues/1526 and https://github.com/LLNL/spack/issues/1456

**Comment by pkondamudi** [comment]
````
ref: [#1526](https://github.com/LLNL/spack/issues/1526)
spack tags                   (show all tags with their short description, two column print out)
spack list --tag=<var>       (show all packages from a tag <var>)
spack find --tag=<var>       (show all installed packages from a tag <var>)
````

Above way of handling is good. I also think ```` spack list tag1, tag2, tag3 ```` should also be allowed for enhanced search experience. This can easily done by using some information retrieval packages like [Whoosh](http://whoosh.readthedocs.io/en/latest/intro.html) which take the inputs gives the results ranked with scores and stops words which can be easily added too. Indexing and updating the index the strings in this subsystem can be overhead job to do.
