### ISSUE TITLE
OpenBLAS compilation error with GCC 7 on POWER8

### ISSUE THREAD

**Issue by katherlee** [LLNL/spack#4782]
This is a reported bug posted on https://github.com/xianyi/OpenBLAS/issues/1078, and a patch was proposed at https://groups.google.com/forum/#!topic/openblas-dev/YI1of4HODmw, which has been merged to the develop branch of OpenBLAS but not in version 0.2.19. See also https://github.com/xianyi/OpenBLAS/pull/1098.

**Comment by adamjstewart** [comment]
Want to submit a PR adding this patch to the package?

**Comment by katherlee** [comment]
Yep, already did :)

**Comment by adamjstewart** [comment]
Thanks! For the record, there's no need to submit an issue if you plan on immediately submitting a PR.
