### ISSUE TITLE
intel-*: Missing locations in LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by robert-mijakovic** [LLNL/spack#48004]
### Summary

Intel GPUs are not detected by sycl because Intel compilers are missing two locations in the library path.

The missing locations are:
1. $INTEL_ONEAPI_COMPILERS_BASE/tcm/1.2/lib
2. $INTEL_ONEAPI_COMPILERS_BASE/umf/0.9/lib

### Description

```
module load intel-compilers/2025.0.1 

sycl-ls ; echo empty
```

This results in an empty list.

Adding their locations fixes the issue.

`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$INTEL_ONEAPI_COMPILERS_BASE/tcm/1.2/lib:$INTEL_ONEAPI_COMPILERS_BASE/umf/0.9/lib`

### Proposed solution

The package.py from intel-compilers and possibly other packages should contain the location in the LD_LIBRARY_PATH.

### General information

- [X] I have searched the issues of this repo and believe this is not a duplicate

**Comment by robert-mijakovic** [comment]
I will check whether UMF is the only thing missing in intel-compilers package and close the ticket accordingly.

**Comment by rscohn2** [comment]
TCM is linked in to compilers lib directory:
```
(venv) rscohn1@gkdse-dnp-23:spack$ ls -l /opt/intel/oneapi/compiler/2025.0/lib/libtcm*
lrwxrwxrwx 1 root root 39 Nov 28 09:07 /opt/intel/oneapi/compiler/2025.0/lib/libtcm_debug.so -> ../../../tcm/latest/lib/libtcm_debug.so
lrwxrwxrwx 1 root root 33 Nov 28 09:07 /opt/intel/oneapi/compiler/2025.0/lib/libtcm.so -> ../../../tcm/latest/lib/libtcm.so
(venv) rscohn1@gkdse-dnp-23:spack$ 
```

**Comment by robert-mijakovic** [comment]
Thank you for your explanation. I've tested it and it works fine.
