### ISSUE TITLE
What is the easiest way to keep the log file for successfully built packages ?

### ISSUE THREAD

**Issue by samfux84** [LLNL/spack#4801]
Hi,

When installing a package with spack, I can have a look at the log file in case there is a problem with the installation. Is there also a good way to keep the log file, if there was no problem with the installation ?

I tohugh about the "dirty" option in the config.yaml file, but this is not exactly what I am looking for, because it also does not cleanup the environment. I would like to just keep the logfile of the installation.

**Comment by alalazo** [comment]
Hmmm, log files should be already saved inside the `<prefix>/.spack` directory, right?

**Comment by samfux84** [comment]
@alalazo Thank you for the hint. I was not aware of this.

**Comment by adamjstewart** [comment]
This really needs to make its way into the documentation...
