### ISSUE TITLE
Installations with Intel MPI 

### ISSUE THREAD

**Issue by ssergien** [LLNL/spack#4803]
All my software installs involving Intel MPI fail. I tried PETSc, parallel-netcdf, and cp2k yesterday. Looking at the spack-build.out it looks for mpi wrappers in /blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/intel-mpi-2017.3-dfphq6kavje2olnichisvjjndtridrok/bin and it cant find them there. They are in  /blues/gpfs/home/software/spack-0.10.1/opt/spack/linux-centos7-x86_64/intel-17.0.4/intel-mpi-2017.3-dfphq6kavje2olnichisvjjndtridrok/compilers_and_libraries_2017.4.196/linux/mpi/intel64/bin.

**Comment by adamjstewart** [comment]
This will be fixed [here](https://github.com/LLNL/spack/pull/4300/files#diff-beae594d7f7a5e02b701962e97ca283bR96). You can use that `bindir` for now as a workaround until I'm done with #4300.

**Comment by ssergien** [comment]
So it seems that spack installing packages that already exist second time. I looked at the build options and they are the same. Why is that?
```
$ spack find -v parmetis
==> 2 installed packages.
-- linux-centos7-x86_64 / intel@17.0.4 --------------------------
parmetis@4.0.3~debug~gdb+shared  parmetis@4.0.3~debug~gdb+shared
```
The last 2 seems the same too:
```
$ spack find -v hdf5    
-- linux-centos7-x86_64 / intel@17.0.4 --------------------------
hdf5@1.10.1+cxx~debug+fortran~mpi+pic+shared+szip~threadsafe  hdf5@1.10.1+cxx~debug+fortran+mpi+pic+shared+szip~threadsafe
hdf5@1.10.1+cxx~debug+fortran+mpi+pic+shared+szip~threadsafe
```
I tried to install petsc again it started pulling dependencies that already exist.

Petsc is still doesn't work though same MKL errors we saw before.

**Comment by adamjstewart** [comment]
Try comparing the `.spack/spec.yaml` in the installation directories. The variants may be the same for the package, but not for the dependencies. The versions of the dependencies could also be different. The compiler flags or virtual dependencies could also be different. As far as I know, Spack's hashing algorithm hasn't changed in a while, so I don't think that's the problem.
