### ISSUE TITLE
Build Dependencies

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#482]
Spack current lacks build dependencies --- dependencies that are required at build-time, but not later when a package is used.  CMake is a common example.

Proposal:

1. Add build_depends_on(), which works just like depends_on(), but specifies build dependencies.  For version 1, build_depends_on() can be an alias for depends_on().

2. When things are specified from build_depends_on(), don't put them in the module file, and other places where build dependencies are not needed.

**Comment by tgamblin** [comment]
See PR #378

**Comment by citibeth** [comment]
Looks well thought out.
