### ISSUE TITLE
Packages without build systems

### ISSUE THREAD

**Issue by jiseung** [LLNL/spack#4829]
Is there a way to build a package that doesn't utilize any build systems?

**Comment by alalazo** [comment]
There's the `Package` class which is meant to be generic (i.e. is not tailored to any build system). You'll need to implement a function:
```python
def install(self, spec, prefix):
    ...
```
that does everything is needed to install the package.

**Comment by jiseung** [comment]
Great! Thank you so much

**Comment by jiseung** [comment]
Are there any examples of these kinds of packages?

**Comment by adamjstewart** [comment]
```
$ cd var/spack/repos/builtin/packages
$ grep '(Package)' */package.py
```
There's about 357 of them. Once upon a time, there was only a single `Package` class, so many of them are waiting to be converted.

If you give me a package name, homepage, or installation instructions, I can help you convert it to Spack.

**Comment by jiseung** [comment]
Oh, thank you so much! It's called miniGMG, and it doesn't have a homepage, just a [tarball](http://crd.lbl.gov/departments/computer-science/PAR/research/previous-projects/miniGMG/). The instructions on the README say that I should run ```cc -O3 -fno-alias -fno-fnalias -xAVX   -openmp miniGMG.c mg.c box.c solver.c     operators.ompif.c timer.x86.c -D__MPI -D__COLLABORATIVE_THREADING=6 -D__TES    T_MG_CONVERGENCE -D__PRINT_NORM -D__USE_BICGSTAB -o run.miniGMG
``` to build the baseline code.

**Comment by adamjstewart** [comment]
Interesting. Most package authors are nice enough to give you a Makefile, but I guess that's not the case here. I would translate this in Spack to:
```python
phases = ['build', 'install']

def build(self, spec, prefix):
    cc = Executable(spack_cc)
    cc('-O3', '-fno-alias', '-fno-fnalias', '-xAVX', ...)

def install(self, spec, prefix):
    mkdir(prefix.bin)
    install(run.miniGMG, prefix.bin)
```

**Comment by jiseung** [comment]
I see. Thank you so much!
