### ISSUE TITLE
xsdk build broken by recent commits to petsc and trilinos

### ISSUE THREAD

**Issue by amklinv** [LLNL/spack#4891]
See https://github.com/LLNL/spack/commit/47fe9e7aad850bf2d650b33e5faa32cb7fe312a4 and https://github.com/LLNL/spack/commit/182554520f68a742f3c2fb15f7121e1faf583aaa

**Comment by amklinv** [comment]
I'll issue a pull request with the changes that worked for me.

**Comment by adamjstewart** [comment]
Presumably fixed by #4893.
