### ISSUE TITLE
gnat dependency of gcc

### ISSUE THREAD

**Issue by samfux84** [LLNL/spack#4914]
I am trying to build GCC 5.4.0 with spack. It has a variant languages:

```
    languages [all]    all, ada, brig, c,      Compilers and runtime libraries to
                       c++, fortran, go,       build
                       java, jit, lto,         
                       objc, obj-c++         
```

The packages.py file contains the following statement:

    depends_on('gnat', when='languages=ada')

When trying to build it with languages=all, I would expect that it keeps the dependency on gnat, since all should include ada:

```
spack install gcc@5.4.0+binutils~piclibs languages=all ^binutils@2.28 ^gmp@6.1.2 ^gnat@2016 ^isl@0.18 ^mpc@1.0.3 ^mpfr@3.1.5 ^zip@3.0 ^zlib@1.2.11 %gcc@4.8.5 arch=linux-centos7-x86_64
==> Error: gcc does not depend on gnat or zip
```

How would the syntax in the packages.py file need to be changed such that it keeps the dependency if languages is ada or all ?

Best regards

**Comment by davydden** [comment]
> When trying to build it with languages=all,

we should really remove `all` from `gcc` and stick with the defaults. There is a discussion on this elsewhere (few months back), but i don't remember where...

**Comment by davydden** [comment]
feel free to create a PR to clean this up.

**Comment by samfux84** [comment]
I will try to create a PR. Is there any documentation about how to do this (specific to spack) apart from the documentation on github ?

**Comment by davydden** [comment]
> Is there any documentation about how to do this (specific to spack)

yes, have a brief look here http://spack.readthedocs.io/en/latest/contribution_guide.html

**Comment by samfux84** [comment]
Added PR #4916. Hope that I did not do anything wrong.

@davydden Thank you for the link to the documentation.

**Comment by davydden** [comment]
> Hope that I did not do anything wrong.

it's all fine, no worries

**Comment by adamjstewart** [comment]
`all` does not include `ada`, it only includes the most commonly used languages. I know this is confusing, but blame GCC. I would also like to replace `all` with `c,c++,fortran`, but unfortunately not every version supports those languages.

**Comment by samfux84** [comment]
Tried

`spack install gcc@5.4.0+binutils~piclibs languages=ada,c,c++,fortran,go,java,jit,objc,obj-c++ ^binutils@2.28 ^gmp@6.1.2 ^isl@0.18 ^mpc@1.0.3 ^mpfr@3.1.5 ^zip@3.0 ^zlib@1.2.11 ^gettext@0.19.8.1+bzip2+curses+git+libunistring+libxml2+tar+xz %gcc@4.8.5 arch=linux-centos7-x86_64`

Failed with

```
checking for the correct version of gmp.h... yes
checking for the correct version of mpfr.h... yes
checking for the correct version of mpc.h... yes
checking for the correct version of the gmp/mpfr/mpc libraries... yes
checking for compatible ISL... yes
 'c++' language required by 'go' in stage 1; enabling
configure: error: GNAT is required to build ada
```

**Comment by adamjstewart** [comment]
Yeah, I was never able to get the GNAT/Ada stuff working. Do you actually need it?

**Comment by samfux84** [comment]
@adamjstewart I don't think that it is required. I just wanted to build GCC with all available features. How do you build the GCC compiler with spack ? Are you using languages=all ?

**Comment by adamjstewart** [comment]
Yes, I've always used `all`. That's the default if you don't specify, so I figured it would be a good default for Spack too.

**Comment by samfux84** [comment]
@adamjstewart Thank you for your reply. Then I will also install it with languages=all.

**Comment by adamjstewart** [comment]
Of course, if you can get Ada working, that would be great too. But I don't think you'll need it. It's mostly used in flight control systems for helicopters and planes. Not a commonly used language.
