### ISSUE TITLE
OpenBLAS post-installation tests fail

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#4933]
```
==> '/Users/Adam/spack/lib/spack/env/cc' '-c' '-I/Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.1.0-apple/openblas-0.2.20-dravpszbgy6i7a6l25xmvnnsyqlrnqq7/include ' '/Users/Adam/spack/var/spack/repos/builtin/packages/openblas/test_cblas_dgemm.c'
/Users/Adam/spack/var/spack/repos/builtin/packages/openblas/test_cblas_dgemm.c:1:10: fatal error: 'cblas.h' file not found
#include <cblas.h>
         ^
1 error generated.
```
If I skip the tests, `cblas.h` is correctly installed:
```
$ ls /Users/Adam/spack/opt/spack/darwin-sierra-x86_64/clang-8.1.0-apple/openblas-0.2.20-dravpszbgy6i7a6l25xmvnnsyqlrnqq7/include/
cblas.h            lapacke.h          lapacke_mangling.h openblas_config.h
f77blas.h          lapacke_config.h   lapacke_utils.h
```
Not sure why it can't find it.

**Comment by davydden** [comment]
Is it, by any chance, running before installation?

**Comment by adamjstewart** [comment]
Nope, it was definitely post-installation. I saw the "generating cblas.h file in <prefix>/include directory" message.

**Comment by davydden** [comment]
weird.... Compiler wrappers won't have the prefix of the package being installed, but we add it manually via `-L`, IIRC. So this should be ok.

**Comment by adamjstewart** [comment]
Hmm, I wonder if it's because of that space at the end of the `-I` line. That's the only thing I can think of.

**Comment by adamjstewart** [comment]
Removing the space at the end of the `-I` line worked! I'll write up a PR to fix this.
