### ISSUE TITLE
#include <library>

### ISSUE THREAD

**Issue by jiseung** [LLNL/spack#4950]
Could someone tell me how make works with a source file that includes a line like 
```
#include <dependency/file>
```
where `dependency` corresponds to what would normally be in `depends_on()`?

Currently, I'm getting compiling errors from not being able to find these files.

**Comment by adamjstewart** [comment]
Which dependency is it? Spack adds `-I<prefix>/include` for every link dependency. Not every package has the same directory structure after installation, so this might not always be enough. If a package includes, for example, `<foo/foo.h>`, my understanding is that the file needs to exist in `prefix/include/foo/foo.h`. Are both of these packages in Spack yet?

**Comment by jiseung** [comment]
The package depends on 'eigen' and references it by <Eigen/Dense>

**Comment by adamjstewart** [comment]
Ah yes, I was about to say, `eigen` has known problems with this. They have a particularly confusing directory structure of:
```
<prefix>/include/eigen3/Eigen
```
Depending on what environment variables the package uses, you should be able to do something like:
```
CFLAGS=-I<prefix>/include/eigen3
```

**Comment by jiseung** [comment]
Great! That works. Thank you so much!
