### ISSUE TITLE
building gcc 5.4.0 fails with "cannot find -lstdc++"

### ISSUE THREAD

**Issue by samfux84** [LLNL/spack#4972]
I am trying to install GCC 5.4.0 with the following command:

`spack install gcc@5.4.0+binutils~piclibs languages=all ^binutils@2.28 ^gmp@6.1.2 ^isl@0.18 ^mpc@1.0.3 ^mpfr@3.1.5 ^zip@3.0 ^zlib@1.2.11 ^gettext@0.19.8.1+bzip2+curses+git+libunistring+libxml2+tar+xz %gcc@4.8.5 arch=linux-centos7-x86_64`

and it fails with

```
==> Error: ProcessError: Command exited with status 2:
    'make' '-j36'
/cluster/apps/spack/lib/spack/spack/build_systems/autotools.py:273, in build:
     268      def build(self, spec, prefix):
     269          """Makes the build targets specified by
     270          :py:attr:``~.AutotoolsPackage.build_targets``
     271          """
     272          with working_dir(self.build_directory):
  >> 273              inspect.getmodule(self).make(*self.build_targets)

See build log for details:
  /scratch/spackapps/spack-stage/spack-stage-kFlS4I/gcc-5.4.0/spack-build.out
```

The log file contains the error message:

```
/bin/sh /cluster/apps/spack/var/spack/stage/gcc-5.4.0-bvtn6sudt232zijglsj5hsa3x4odu6bv/gcc-5.4.0/gcc/../move-if-change tmp-options.h options.h
echo timestamp > s-options-h
/cluster/spack/apps/linux-centos7-x86_64/gcc-4.8.5/binutils-2.28-rrcp2p7yfho5b33wbctod6c52miif4w5/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status
Makefile:2613: recipe for target 'build/genchecksum' failed
make[3]: *** [build/genchecksum] Error 1
```

Did somebody encounter simliar problems ?

**Comment by adamjstewart** [comment]
What happens when you try `gcc~binutils`? I've never gotten `gcc+binutils` to build on any platform with any compiler.

**Comment by samfux84** [comment]
Setting "~binutils" solves the problem.

Thank you for your help.

**Comment by hartzell** [comment]
You didn't provide enough of the log files for me to be certain, but there's a good chance that that bit of the build is trying to link something statically and you don't have the static version of those libraries available.

On my CentOS 7 systems, in addition to the "usual" development packages I've had to explicitly asked to have the `libstdc++-static` package installed.  I also install `glibc-static` for similar reasons.

That might let you build w/out the variant.

**Comment by samfux84** [comment]
@hartzell Thank you for your comment. This sound very reasonable. On our system, we do not have the static versions of these libraries installed.

**Comment by hartzell** [comment]
I just stumbled upon this while searching for something else and happened to be in a position to test it.

I've successfully built gcc@5.5.0+binutils on a CentOS system.  It *does* have the static libraries I mentioned above, and it's sensible that they're needed given this bit of the gcc package.

```
        # Binutils
        if spec.satisfies('+binutils'):
            static_bootstrap_flags = '-static-libstdc++ -static-libgcc'
```

**Comment by samfux84** [comment]
@hartzell Thank you for pointing this out. On our system, the RPM for the static libstdc++ was not installed (we have a customized CentOS installation). After we installed it, compiling GCC worked.
