### ISSUE TITLE
Unable to build LLVM on CentOS 7

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#4986]
I'm trying to build LLVM on CentOS 7 with GCC 7.1.0. I'm seeing the following error message:
```
In file included from /blues/gpfs/home/ajstewart/spack/var/spack/stage/llvm-4.0.0-iwr5xsmpa2scpclnuhevp4od7pa3j7mq/llvm-4.0.0.src/tools/lldb/source/Utility/TaskPool.cpp:10:0:
/blues/gpfs/home/ajstewart/spack/var/spack/stage/llvm-4.0.0-iwr5xsmpa2scpclnuhevp4od7pa3j7mq/llvm-4.0.0.src/tools/lldb/include/lldb/Utility/TaskPool.h: In static member function ‘static std::future<typename std::result_of<_Functor(_ArgTypes ...)>::type> TaskPool::AddTask(F&&, Args&& ...)’:
/blues/gpfs/home/ajstewart/spack/var/spack/stage/llvm-4.0.0-iwr5xsmpa2scpclnuhevp4od7pa3j7mq/llvm-4.0.0.src/tools/lldb/include/lldb/Utility/TaskPool.h:122:12: error: ‘bind’ is not a member of ‘std’
       std::bind(std::forward<F>(f), std::forward<Args>(args)...));
            ^~~~
/blues/gpfs/home/ajstewart/spack/var/spack/stage/llvm-4.0.0-iwr5xsmpa2scpclnuhevp4od7pa3j7mq/llvm-4.0.0.src/tools/lldb/include/lldb/Utility/TaskPool.h:122:12: note: suggested alternative: ‘end’
       std::bind(std::forward<F>(f), std::forward<Args>(args)...));
            ^~~~
            end
```
Full build log [here](https://github.com/LLNL/spack/files/1203298/spack-build.txt).

**Comment by KineticTheory** [comment]
This looks like a bug in `TaskPool.h.`  [std::bind](http://en.cppreference.com/w/cpp/utility/functional/bind) is defined in the C++ header `<functional>` but this header isn't included by `TaskPool.h.`.  Interestingly, https://github.com/llvm-mirror/lldb/blob/master/include/lldb/Utility/TaskPool.h has this header added to the source.

My guess is that `<functional>` was unknowingly included via another C++ header prior to GCC 7.

**Comment by aprokop** [comment]
Got hit by this too today. I guess a simple PR with a patch is in order. The condition is gcc >= 7.0, I guess. I wonder what are the restrictions on llvm versions, though.

**Comment by aprokop** [comment]
Checked llvm-4.0.1, no cigar, still missing `<functional>`.

**Comment by aprokop** [comment]
Would like to write something like this:
```python
    patch('llvm_gcc7.patch', when='@4.0.0+lldb ^gcc@7.0:')
    patch('llvm_gcc7.patch', when='@4.0.1+lldb ^gcc@7.0:')
```
Not sure if this works, though.

**Comment by s-sajid-ali** [comment]
This needs another fix. I'm trying to use spack installed llvm for numba ^python@3.6.5 and the old numba package had a requirement llvm@4 which in turn forced spack to install numba for python@2.7. 

I raised an [issue](https://github.com/numba/llvmlite/issues/258#issuecomment-388882748) in the numba repository and it looks like another [patch](https://github.com/numba/llvmlite/blob/master/conda-recipes/0001-Transforms-Add-missing-header-for-InstructionCombini.patch) is required for llvm.
