### ISSUE TITLE
Adios2 missing zeromq dependency

### ISSUE THREAD

**Issue by olesenm** [LLNL/spack#5021]
@ax3l : I did a normal build without specifying any variants

    Call Stack (most recent call first):
    ..../cmake-3.9/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
    cmake/FindZeroMQ.cmake:44 (find_package_handle_standard_args)
    source/dataman/CMakeLists.txt:51 (find_package)

**Comment by ax3l** [comment]
ah, I accidentally removed that in a rebase!
will add it again asap.

**Comment by olesenm** [comment]
thanks - things getting lost in a rebase is too familiar.

**Comment by olesenm** [comment]
BTW: for cmake things you might want to take a look at how the paraview/package.py manages ON/OFF bool values for cmake. Seems to reduce some typing.

**Comment by ax3l** [comment]
@olesenm oh, `(n)variant_bool` looks efficient, I like that. thanks!
