### ISSUE TITLE
Add -fPIC (or equivalent) compiler flag to SPack Compiler Wrappers

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#508]
This would allow packages producing shared libraries to link to packages producing only static libraries, even if the static library packages not add -fPIC in their build.

@mathstuf said:

> Well, it's not always spelled '-fPIC', but yes, this makes sense. Here's
> CMake's "table" of -fPIC flags:
> 
> ```
> Modules/Compiler/GNU.cmake:  set(CMAKE_${lang}_COMPILE_OPTIONS_PIC "-fPIC")
> Modules/Compiler/NAG-Fortran.cmake:set(CMAKE_Fortran_COMPILE_OPTIONS_PIC "-PIC")
> Modules/Compiler/SCO.cmake:  set(CMAKE_${lang}_COMPILE_OPTIONS_PIC -Kpic)
> Modules/Compiler/SunPro-C.cmake:set(CMAKE_C_COMPILE_OPTIONS_PIC -KPIC)
> Modules/Compiler/SunPro-CXX.cmake:set(CMAKE_CXX_COMPILE_OPTIONS_PIC -KPIC)
> Modules/Compiler/SunPro-Fortran.cmake:set(CMAKE_Fortran_COMPILE_OPTIONS_PIC "-KPIC")
> Modules/Compiler/XL.cmake:  set(CMAKE_${lang}_COMPILE_OPTIONS_PIC "-qpic")
> ```

**Comment by KineticTheory** [comment]
+1 for always using appropriate compiler flags to ensure position independent code in libraries.  This small change would save me a lot of hacking on spack's package.py files to manually enable this feature.  I had to reinstall Trilinos today, re-compiling with `-fPIC` this time around (`-DCMAKE_POSITION_INDEPENDENT_CODE=ON`).

**Comment by davydden** [comment]
:+1:

should be straight forward to add to compiler classes as
```
 @property
 def fpic_flag(self):
```
with default to `-fPIC` and overwrided in `nag` and `xl`.

**Comment by adamjstewart** [comment]
I would call it `pic_flag`, since `-f` is compiler specific.

**Comment by adamjstewart** [comment]
Examples for other compilers:

Compiler | Flag(s) | Notes
--- | --- | ---
GCC | -fpic / -fPIC | -fpic and -fPIC are not equivalent
Intel | -fpic / -fPIC | -fPIC is a synonym for -fpic
PGI | -fpic / -fPIC / -kpic / -kPIC | all are synonyms for -fpic
NAG | -pic / -PIC | -pic and -PIC are not equivalent
XL | -fpic / -fPIC / -qpic | not equivalent

**Comment by adamjstewart** [comment]
Another problem that would need to be addressed is mixed compiler support. NAG provides a Fortran compiler that uses `-PIC`, and would need to be combined with a C/C++ compiler like GCC that uses `-fPIC`.

**Comment by adamjstewart** [comment]
Closed by #2375.

**Comment by skosukhin** [comment]
> Another problem that would need to be addressed is mixed compiler support. NAG provides a Fortran compiler that uses -PIC, and would need to be combined with a C/C++ compiler like GCC that uses -fPIC.

@adamjstewart did you find a workaround for this problem?

**Comment by adamjstewart** [comment]
The workaround would be to replace `compiler.pic_flag` with `compiler.cc_pic_flag` and friends, much like we did with `rpath_flag`. Even then, it's still a bit sketchy, as you have to assume which compiler NAG will be paired with. Spack currently has terrible mixed compiler support.
