### ISSUE TITLE
Installing Blast Error: Curl: (9) Server denied you to change to the given directory 

### ISSUE THREAD

**Issue by mamelara** [LLNL/spack#51]
Hi I'm working with NERSC and we are thinking of implementing the spack package manager to our system.
We would like to eventually build a substantial amount of bioinformatic tools using spack.

I've been testing out writing formula using blast. I've been receiving this error:
==> Installing blast
==> Trying to fetch from ftp://ftp.ncbi.nlm.nih.gov/2.2.30/executables/blast+/2.2.30/ncbi-2.2.30-2.2.30+-src.tar.gz

curl: (9) Server denied you to change to the given directory
==> Fetching from ftp://ftp.ncbi.nlm.nih.gov/2.2.30/executables/blast+/2.2.30/ncbi-2.2.30-2.2.30+-src.tar.gz failed.
==> Error: All fetchers failed for blast@2.2.30%gcc@4.8=unknown_arch

One thing that I've noticed is that it changes blast into version 2.2.30 thus giving the wrong URL. Does spack recognize the blast keyword and turns it into it's version number?

Here is the formula that I've written:
 

       from spack import *
       class Blast(Package) 
       homepage = "http://blast.ncbi.nlm.nih.gov"
       url      = "ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.2.30/ncbi-blast-2.2.30+-src.tar.gz"
   
       version('2.2.30', 'f8e9a5eb368173142fe6867208b73715')
  
      def install(self, spec, prefix):
          configure("--prefix=%s" % prefix)
          make()
          make("install")

Thanks for your help!

**Comment by tgamblin** [comment]
Hi Mario -- great to hear that you guys are trying out Spack.

Spack can't always extrapolate a URL.  So in this case I would use a version-specific URL (see http://scalability-llnl.github.io/spack/packaging_guide.html#version-urls), e.g.:
    ```
    version('2.2.30', 'f8e9a5eb368173142fe6867208b73715',
        url='ftp://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.2.30/ncbi-blast-2.2.30+-src.tar.gz')
    ```

If you provide a version-specific URL, Spack will take it verbatim and won't try anything fancy.

The FTP error you're getting is related to the wrong URL, so see if this fixes the problem. I can look into making Spack extrapolate this type of URL, but in general it's not going to handle all of them.  If you want better extrapolation for your package you *can* override the url_for_version() function in your package.

**Comment by adamjstewart** [comment]
Can this be closed now?

**Comment by tgamblin** [comment]
@mamelara: I'm assuming this isn't an issue anymore?
