### ISSUE TITLE
Remove +fpic variant from packages

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#511]
@mathstuf:

> @citibeth:
> > If position-independent code is an option for a library, it should be controlled by a variant "+fpic"
> 
> I don't think this should ever be an option since it makes it incompatible with all shared libraries (including things like Python modules which have to be shared).
> 

```
$ grep fpic `find . -name '*.py'`
./py-numpy/package.py:    depends_on('netlib-blas+fpic', when='+blas')
./netlib-blas/package.py:    variant('fpic', default=False, description="Build with -fpic compiler option")
./netlib-blas/package.py:        if '+fpic' in self.spec:
./netlib-blas/package.py:            mf.filter('^OPTS.*=.*',  'OPTS = -O2 -frecursive -fpic')
./netlib-blas/package.py:            mf.filter('^CFLAGS =.*',  'CFLAGS = -O3 -fpic')
./trilinos/package.py:    # Everything should be compiled with -fpic
./netlib-scalapack/package.py:    variant('fpic', default=False, description="Build with -fpic compiler option")
./netlib-scalapack/package.py:        if '+fpic' in spec:
```

**Comment by alalazo** [comment]
@tgamblin @citibeth The problem should be mainly due to  netlib-blas, I tried a possible fix in #485

**Comment by tgamblin** [comment]
There are a lot of issues rolled up in here -- I need to respond properly to the discussion on the mailing list.  We do actually care about static libs and building without `-fpic`, and there may be platforms (or accelerators) where we don't want to do this in a blanket way. I think that that per-package stuff is still the right way to do this, but we need something like #391 to do it right.

I need to look at #485 too.  The thing there is that we often want to combine `netlib-lapack` with a vendor BLAS, and I haven't looked but I need to see if combining the packages disallows that.

**Comment by alalazo** [comment]
@tgamblin I agree that static libraries should stay. I was just noticing that despite the 'conceptual' problem, it seems that right now the only package that poses a real issue is `netlib-blas`.

**Comment by citibeth** [comment]
I think PR #485 would fix this in practice.

Should we specify that packages build PIC code by default?
 netlib-blas~fpic would still be possible, if the user specifies it.

On Tue, Mar 8, 2016 at 4:44 PM, Massimiliano Culpo <notifications@github.com
