### ISSUE TITLE
Fix hypre/package.py: Not linking MPI properly

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#512]
Follows is the key to fix hypre/package.py to build with shared libraries:

@psaravan:

Rob Falgout <rfalgout@llnl.gov> added the comment:

Hi Elizabeth,

Sorry, it wasn't clear from your email (unless I missed something) if you were a developer or a user, and the problem seemed like it could be related to spack.

Anyhow, it looks to me like the issue is that you are setting the CC environment variable to 'gcc', so the hypre configure script does not look for an mpi compiler, it just uses the one you provide.  When using a non-mpi compiler, you need to add the mpi library and include file information to the configure line:

  --with-MPI-include=DIR
  --with-MPI-libs=LIBS
  --with-MPI-lib-dirs=DIRS

I'm not exactly sure how you are passing the openmpi path information to hypre.  If it's through a CFLAGS environment variable, then that might appear after the MPI stuff.

Hope this helps.  Let me know.

Log file of erroneous build:

[hypre-package.txt](https://github.com/LLNL/spack/files/163873/hypre-package.txt)
[log.txt](https://github.com/LLNL/spack/files/163870/log.txt)
[environ.txt](https://github.com/LLNL/spack/files/163871/environ.txt)

**Comment by tgamblin** [comment]
FYI: hypre has some more recent [pre-releases on github](https://github.com/LLNL/hypre/releases) -- you have to expand the newer tags.  You might want to try those out if you're messing w/the hypre package, as they're pretty close to what the next release drop will look like.

If you've already integrated this stuff into Hypre, a PR would be awesome.

**Comment by glennpj** [comment]
I am curious, can spack use the MPI compiler wrappers, mpicc and friends for building software in spack? If not, could/should they be added as compilers to spack?
