### ISSUE TITLE
buildcache makes malformed HTML

### ISSUE THREAD

**Issue by sknigh** [LLNL/spack#5123]
```spack buildcache create``` makes an index.html file in the ```build_cache``` directory.

``` html
<html>
<head></head>
<list><li><a href="index.html" index.html</a><li><a href="linux-centos7-x86_64-gcc-4.8.5-zlib-1.2.11-yrijbmajetpxrkyaa4uclsyw62zbhc5m.spec.yaml"> linux-centos7-x86_64-gcc-4.8.5-zlib-1.2.11-yrijbmajetpxrkyaa4uclsyw62zbhc5m.spec.yaml</a></list></html>
```

It is missing a ```>``` between the ```href``` argument and its text value, and should look like

``` html
... <a href="index.html">index.html</a> ...
```

I think a better option would be to suppress the generation of the index.html unless it is supposed to do more than generate a list. Web servers will automatically create static web pages when no index.html is present.

**Comment by adamjstewart** [comment]
There is no `spack buildcache` command. Are you on a different branch?

**Comment by adamjstewart** [comment]
@gartung

**Comment by gartung** [comment]
Fixed here
https://github.com/LLNL/spack/pull/5127
