### ISSUE TITLE
Reuse of utils?

### ISSUE THREAD

**Issue by ax3l** [LLNL/spack#5155]
Are `llnl.util` or `spack.util.executable` also available as separate projects?

I found them really convenient for writing cmd wrappers and would like to re-use them in other projects such as [PIConGPU](https://github.com/ComputationalRadiationPhysics/picongpu/).

Did you consider re-publishing them as a separate little python lib, so we can set them as requirements? (Otherwise copying & modifying the files would also be possible as long as we keep the license header since we are LGPL compatible.)

**Comment by alalazo** [comment]
I think this is somehow related to discussions in #1385 and #4021

**Comment by ax3l** [comment]
True.

Actually I am proposing the opposite of @tgamblin in #4021: move some parts of `spack.util` (`executable`) to `llnl.util` and publish `llnl.util` :D
