### ISSUE TITLE
Best practices when naming packages: multiple interfaces and namespace collisions

### ISSUE THREAD

**Issue by wscullin** [LLNL/spack#5206]
I am working on adding several tomography packages. While my group exclusively uses them via their python interfaces (and that's pretty common), about a quarter of the wider community is likely to use them via Matlab, C++, or IDL. Naming the package py- would normally make sense, but then it would seem to be Python-exclusive. What's the best practice for naming in such situations?

Likewise, one of the packages astra-toolkit is very similar in name to astra. In naming packages - and options for variants - is there a best practice when there are similarities in name that just seem likely to trip up the concretizer. I'm thinking of the qmcpack spec when:

 depends_on('espresso@5.3.0+qmcpack~elpa', when='+mpi')

and we went with to get around it:

 depends_on('espresso@5.3.0+qmcpackconv~elpa', when='+mpi')

Thanks,
William

**Comment by markcmiller86** [comment]
Hmm. Sounds like you are saying you have package(s) that support C++, Python, IDL and Matlab _interfaces_. The package is not specifcally and solely available in python or for python. So, I agree, using py-whatever would be a bad idea. 

I think this situation is analagous to packages that support multiple langage bindings such as C, CXX, Fortran (90/2003), Java, Python, etc. A good example is HDF5.

IMHO, I would treat these as variants either each as a sep. variant or maybe an _uber_ variant that turns on/off _all additional_ interfaces beyond the interface of the native implementation language (e.g. for HDF5 that would be C). The only issue with the latter approach is that such an all or nothing switch causes the resulting package to be too vulnerable to build failures, especially if some of the interface(s) the package supports are more widely supported and tested than others.

Regarding similarly named packages, yeah, I think that is a problem that is likely to become more apparent as Spack's package repository continues to grow.

**Comment by scheibelp** [comment]
> is there a best practice when there are similarities in name that just seem likely to trip up the concretizer

As long as the names differ at all, the concretizer will not get confused.

> I'm thinking of the qmcpack spec when:
>
>depends_on('espresso@5.3.0+qmcpack~elpa', when='+mpi')
>
>and we went with to get around it:
>
>depends_on('espresso@5.3.0+qmcpackconv~elpa', when='+mpi')

I'm not sure what you are getting around here - could you link to the original issue?

There is no naming scheme for packages which attempts to reduce user confusion. For similarly-named packages, the description (docstring) should help distinguish it. I agree with @markcmiller86 and your intuition on not using "py-..." in this case.

**Comment by tgamblin** [comment]
> Naming the package py- would normally make sense, but then it would seem to be Python-exclusive. What's the best practice for naming in such situations?

There's no reason you *have* to use the `py-` prefix.  It's mostly there to make it easy to see all the Python packages in `spack list`.  With #4786, we could think about getting rid of the `py-` prefix, but that would be a lot of renaming.

In general, if the package is primarily *not* a python tool, but maybe exports a Python interface or something, we've been known to omit the prefix.  Examples:

```
$ grep extends */package.py | grep -v ^py- | grep ': *extends' | grep python
adios2/package.py:    extends('python', when='+python')
antlr/package.py:    extends('python', when='+python')
caffe/package.py:    extends('python', when='+python')
cantera/package.py:    extends('python', when='+python')
cmor/package.py:    extends('python', when='+python')
conduit/package.py:    extends("python", when="+python")
cosmomc/package.py:    extends('python', when='+python')
cram/package.py:    extends('python@2.7:')
eccodes/package.py:    extends('python', when='+python')
elemental/package.py:    extends('python', when='+python')
espressopp/package.py:    extends("python")
fenics/package.py:    extends('python')
flann/package.py:    extends("python",      when="+python")
gdal/package.py:    extends('python')
hoomd-blue/package.py:    extends('python')
ibmisc/package.py:    extends('python')
libgpuarray/package.py:    extends('python')
libxml2/package.py:    extends('python', when='+python',
ont-albacore/package.py:    extends('python')
openbabel/package.py:    extends('python', when='+python')
opencv/package.py:    extends('python', when='+python')
pagmo/package.py:    extends('python', when='+python')
piranha/package.py:    extends('python',         when='+pyranha')
simulationio/package.py:    extends('python')
thrift/package.py:    extends('python', when='+python')
vtk/package.py:    extends('python', when='+python')
```

>  is there a best practice when there are similarities in name that just seem likely to trip up the concretizer

I don't 100% understand what you're asking.  As @scheibelp mentioned, Packages and variants have different namespaces, so there wouldn't be a conflict between a `qmcpack` package and a `qmcpack` variant on some other package.  We do this all the time with optional dependencies, e.g., look at `python` in all the `extends` directives above.

Variant names only need to be unique on a package-by-package basis, and you can even have a spec like `app+mpi ^hdf5~mpi`; `mpi` doesn't have to be enabled for all packages at once.

Does that help or am I missing something?
