### ISSUE TITLE
Can or will Spack parallelize the dependency graph, perhaps across nodes?

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/spack#5209]
Spack can parallelize builds of any package by the package's makefile. Some packages don't support parallel make (e.g. their make's fail with `make -j K` if `K` is greater than one).

Sometimes, I may be sitting on a resource reservation with multiple nodes; maybe 3 nodes each with 16 cores. Can spack parallelize its dependency graph across (or even within) nodes?

I mean, can it launch parallel builds of multiple independent dependents and, can it do so across nodes? Even within a single node, it would be useful because in many cases `make -j K` underutilizes available CPU resources because the source directory contains less than `K` targets.

This is really more of a curiosity if anyone is looking at this kind of parallelism in Spack? I can see it being *very* useful in situations involving large and complex build matricies though.

**Comment by tgamblin** [comment]
Yes.  We'd like to make it so that `srun spack install foo` will parallelize across nodes in the DAG.  It's on my list, and the locking is in place for it.  We would just need to make `spack install` a bit smarter about how it decides what to build.
