### ISSUE TITLE
Presenting Spack

### ISSUE THREAD

**Issue by ax3l** [LLNL/spack#5220]
Hi,

I would like to present spack as part of a talk at this year's [Datenspuren](http://datenspuren.de/) conference in Dresden, Germany.

Datenspuren is a small open conference organized by a local [hackerspace](https://en.wikipedia.org/wiki/Hackerspace) and focused on privacy, open software/hardware development and general nerd-ism. As with my minor contributions for [travis](https://github.com/LLNL/spack/pull/5133) and [docker](https://github.com/LLNL/spack/pull/4480), I think this is a great opportunity for outreach and would like to present/advertize the usefulness of spack, comparing it to orthogonal solutions we used previously in our software stack and why, when and where it is useful and how we (I) use it already and in the future. The talk will likely contain a lot of introduction to general concepts of FOSS distribution/packaging and is not solely focused on spack.

I will create and publish slides in English, although the talks are most of the time held German (and recorded and published under CC licenses as well).

Quick questions:
- Is it of if I present a talk *about (using)* spack there? The talk will likely be held from me as a private person, but I need to cross check with my employer/lab.
- I would lend a slide or two from the materials from your SC16 tutorials if that is ok. As usual, I would highlight the persons and institutions that do the actual work on spack (not me, I am just cheering from the side lines). Are the institute slides still up to date or did more join? I think e.g. CERN is not yet in the list and contributed recently?
- Can I use the logo?
- Any comments?

**Comment by tgamblin** [comment]
Hi @ax3l:

> I would like to present spack as part of a talk at this year's Datenspuren conference in Dresden, Germany.

Yes! Please do!

> I will create and publish slides in English, although the talks are most of the time held German (and recorded and published under CC licenses as well).

Cool!  Can you follow up here with a link when it's over?  Or tweet it?

> * Is it ok if I present a talk about (using) spack there? The talk will likely be held from me as a private person, but I need to cross check with my employer/lab.

Yes!  We encourage people to present about Spack.

> I would lend a slide or two from the materials from your SC16 tutorials if that is ok.

Definitely!  Let me know if you want the latest .pptx version.  I suppose we should also make that available online so that people can use it.

> As usual, I would highlight the persons and institutions that do the actual work on spack (not me, I am just cheering from the side lines). 

Feel free to highlight your own stuff too!

> Are the institute slides still up to date or did more join? I think e.g. CERN is not yet in the list and contributed recently?

CERN/Fermi/BNL others in the HEP Software Foundation have been in there for a while.  The logos are getting smaller...

> Can I use the logo?

Yes!  Let me know if you want a vector version.

> Any comments?

Thanks for doing this!

**Comment by ax3l** [comment]
Jippey, thank you for the feedback and I will keep you posted and share the slides!
