### ISSUE TITLE
Spurious errors due to invalid caches

### ISSUE THREAD

**Issue by healther** [LLNL/spack#5228]
I'm not yet 100% certain, but I think I just ran into a spurious cache issue. 

The problem were dependencies on ```java@8:``` which lead to a ```Multiple providers found``` error, caused by the introduction of ```icedtea``` in #4804. Adding the entry ```java: [jdk]``` into the providers section of ```etc/spack/packages.yaml``` didn't help and commenting out the ```provides('java')``` line in ```icedtea``` lead to ```Package not found: java```.

I believe this is due to: 
1) Me not realizing that there are now multiple ```java```-providers and ```spack``` not automatically choosing a default
2) ```spack``` not automatically updating its caches if setting-files have changed
3) dependency resolving seems to depend on whether there are multiple providers of a given ?name?

First of all: Does my explanation make sense? Or am I missing something?

To 1) is this intentional? Or should there be always a default provider (if a new package gets added the old one takes precedence?)
To 2) is there a way to get ```spack```'s currently used settings? I.e. a complete current dictionary the is the union of all used ```*.yaml``` files, ideally with markings where which entry originates.
2b) how hard would it be for spack to validate its caches? 

As always thanks for any feedback/pointers

**Comment by scheibelp** [comment]
Sorry about the late response on this: could you mention which package you are concretizing (and e.g. the spec passed to ```spack spec```? You shouldn't have to specify a default even when there are multiple providers.

**Comment by healther** [comment]
The original issue occurred with one of our internal meta-packages (that we use to wrap our software state). But I had been able to reproduce it with ```stc```. However I just tried to do that again and failed.

I was also doing a lot of branch switches that included preferences files... I just realized that in ```defaults/packages.yaml``` there is an entry ```java: [jdk]```, 1) shouldn't have happened at all...

As I don't seem to be able to reproduce this right now, feel free to close this. Do you know any way to print out the current configuration of spack (i.e. the currently used ```packages.yaml``` etc?)

**Comment by adamjstewart** [comment]
> Do you know any way to print out the current configuration of spack (i.e. the currently used `packages.yaml` etc?)

```
$ spack config get packages
```

**Comment by scheibelp** [comment]
> As I don't seem to be able to reproduce this right now, feel free to close this.

OK, and feel free to reopen it if it comes up again!
