### ISSUE TITLE
Install does not keep stage after crash

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#524]
I just tried installing a package, but it crashed during configure. I went to take a look at `spack-build.out` but found that `/tmp/<username>/spack-stage/` was empty. Did a recent commit break something?

**Comment by dhandeo** [comment]
+1

**Comment by adamjstewart** [comment]
If I pass `--keep-stage` it works as expected, but if I leave it out the entire stage gets deleted. Did the default somehow change?

**Comment by tgamblin** [comment]
Fixed.  This is what I get for trying to be fancy.  Reverted to the old semantics for `keep_stage`
