### ISSUE TITLE
Fix URL on spack.io

### ISSUE THREAD

**Issue by aprokop** [LLNL/spack#5245]
At the bottom, "View `Spack on Github`" points to https://github.llnl.gov/spack, which is probably a historical artifact.

**Comment by mathstuf** [comment]
@tgamblin Is this a public repo?

**Comment by mathstuf** [comment]
Ping @tgamblin.

**Comment by aprokop** [comment]
@mathstuf Interestingly, the webiste github.llnl.gov seems to be gone, and disappeared from search results.

**Comment by mathstuf** [comment]
I think it may have been an enterprise install. It is probably just only visible from inside LLNL today.

**Comment by tgamblin** [comment]
Fixed!
