### ISSUE TITLE
Vague "==> Error: 'shared'" message when attempting to build cntk

### ISSUE THREAD

**Issue by bwelton** [LLNL/spack#5266]
I am getting a rather vague error message when attempting to build cntk with spack (gitrev: bb29ec1) on ORNL Titan. The following is the output that I am getting from spack:

> titan-ext2: ./bin/spack install cntk %gcc@4.9.3 
> titan-ext2: ==> Error: 'shared'

This error message appears irregardless of what node type I attempt to compile on (login, service, and compute all show the same error) and it only appears with cntk (other packages compile/install without issue). 

What exactly is this error message indicating and what would I need to do to sidestep this problem?

**Comment by pramodskumbhar** [comment]
@bwelton : for such abstract errors `debug` flag is your friend i.e. try `spack -d install ...`

**Comment by pramodskumbhar** [comment]
Ok, I can reproduce this locally. Culprit is : 

```
depends_on('protobuf~shared')
```

There is no `shared` variant in protobuf now. I will submit PR.

**Comment by bwelton** [comment]
Thanks a bunch for the quick response on this (likely saved me a few hours of time digging through python debug traces trying to figure this out).  I will change the reference to protobuf locally and give it another go. 

In the future I will keep the -d flag in mind for any future issues I run into. Should have read the man page on that since i was using --verbose for some reason to try and obtain debug info.
