### ISSUE TITLE
[PGI Compiler] url_for_version while fetching from mirror 

### ISSUE THREAD

**Issue by pramodskumbhar** [LLNL/spack#5299]
Hello,

I have copied PGI compiler tarball in the mirror : 

```
~/SPACK_HOME/install_home/mirror/pgi/pgilinux-2017-177-x86_64.tar.gz
```
The actual version of compiler is:

```
version('17.7',  '62d86721f92355a6480f4181cdeeb6e0')
```

When I try to install : 

```
$ spack install -v pgi
==> Installing pgi
==> Fetching file://~/SPACK_HOME/install_home/mirror/pgi/pgi-17.7.tar.gz
curl: (37) Couldn't open file /SPACK_HOME/install_home/mirror/pgi/pgi-17.7.tar.gz
==> Fetching from file://~/SPACK_HOME/install_home/mirror/pgi/pgi-17.7.tar.gz failed.


==> Fetching file:///gpfs/bbp.cscs.ch/home/kumbhar-adm/SPACK_HOME/pgilinux-2017-177-x86_64.tar.gz
curl: (37) Couldn't open file /gpfs/bbp.cscs.ch/home/kumbhar-adm/SPACK_HOME/pgilinux-2017-177-x86_64.tar.gz
==> Fetching from file:///gpfs/bbp.cscs.ch/home/kumbhar-adm/SPACK_HOME/pgilinux-2017-177-x86_64.tar.gz failed.
==> Error: FetchError: All fetchers failed for pgi-17.7-ds56srieuvkapc4hh772owdv3kwn73vk
FetchError: FetchError: All fetchers failed for pgi-17.7-ds56srieuvkapc4hh772owdv3kwn73vk
```

So while fetching from mirror Spack use `version` i.e. `17.7`. The `url_for_version ` method returns `tarball` in the current directory with different version scheme : 

```
    def url_for_version(self, version):
        return "file://{0}/pgilinux-20{1}-{2}-x86_64.tar.gz".format(
            os.getcwd(), version.up_to(1), version.joined)
```

I could rename the tarball while copying to the mirror directory but if there is other way to resolve this, it would be great.

**Comment by adamjstewart** [comment]
When Spack places files in the mirror, it always renames them to `packageName-version.tar.gz`. If you are going to manually place files in the mirror, you need to follow this convention as well. Otherwise, as long as this tarball is in your current directory, Spack will find it, copy it to the mirror for you, and install it.

**Comment by pramodskumbhar** [comment]
ok, thanks for clarification. 

@adamjstewart : this is not related to above problem but : it seems that even if I install `+network`, when I try compile code on different node than the installation I get:

```
$ pgcc a.c
pgcc-Error-Please run makelocalrc to complete your installation
```

I will look into installation instructions.

**Comment by pramodskumbhar** [comment]
Install [guide](https://www.pgroup.com/doc/pgiinstall174.pdf) has necessary instructions. Just for reference:

```
For a network installation, you must run the local installation script on each system
on the network where the compilers and tools will be available for use.

If your installation base directory is /opt/pgi and /usr/pgi/shared/17.4 is the
common local directory, then run the following commands on each system on the
network.

/opt/pgi/linux86-64/17.4/bin/makelocalrc -x /opt/pgi/linux86-64/17.4 \
 -net /usr/pgi/shared/17.4

These commands create a system-dependent file localrc.machinename in
both of these directories...

```
