### ISSUE TITLE
Feature Request: Make Spack Load Report Absent Packages

### ISSUE THREAD

**Issue by JusticeForMikeBrown** [LLNL/spack#5308]
Hi

Our users want an error message printed if "spack load" does not find a package installed.  We use environment modules which will print an error message if you try to load a module that does not exist.  For example if I forget the last character in a module that Spack installed:

```

user@server[~]$ module load git-2.12.1-gcc-6.3.0-vl5jrn
ModuleCmd_Load.c(213):ERROR:105: Unable to locate a modulefile for 'git-2.12.1-gcc-6.3.0-vl5jrn'

```

Could Spack simply print that error message or something similar?

```
user@server[~]$ spack load blah
user@server[~]$ 
```

**Comment by davydden** [comment]
duplicate of https://github.com/LLNL/spack/issues/2570

**Comment by JusticeForMikeBrown** [comment]
Ah, sorry, @davydden
