### ISSUE TITLE
inconsistencies in dependent info

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/spack#5309]
I am trying to figure out how many packages in Spack use HDF5 directly (e.g. call HDF5) and how many use HDF5 indirectly (call some package that calls other packages that eventually call HDF5). 

Some basic sanity checkes don't seem to add up...

```
[scratlantis:~/spack/spack] miller86% find var/spack/repos/builtin/packages -name package.py -exec sh -c 'grep -H "^[^#]*depends_on(" {} | grep -m 1 -i hdf5' \; | wc -l
      64
[scratlantis:~/spack/spack] miller86% spack dependents hdf5 | xargs -n 1 | wc -l
      61
```

When I examine the difference in the two approaches, above, I see that these 3 packages were not included by the `spack depdendents` command...
  - hdf5
  - nalu
  - xsdk

First, should the package itself be listed by `spack dependents`?

Next, `spack graph` does show `hdf5` for xsdk but not for nalu. But, nalu's `depends_on` declaration is quite complex

```
[scratlantis:~/spack/spack] miller86% spack graph xsdk
o  xsdk
|\
| |\
| | |\
| | | |\
| | | | |\
| | | | | o  alquimia
.
.
.
| | | | | | o | | | | |  matio
| | |/| |_|/ / / / /
| | | |/| | | | | | 
| | | | | o | | | |  hdf5
| |_|_|_|/| | | | | 
|/| | |_|/ / / / /
| | |/| | | | | | 
| | o | | | | | |  openmpi
| | o | | | | | |  hwloc
| | |\ \ \ \ \ \ \
| | | o | | | | | |  libxml2
| |_|/| | | | | | | 
|/| |/| | | | | | | 
| | | | | | o | | |  boost
.
.
.
o |  m4
o |  libsigsegv
 /
o  bzip2
```

**Comment by tgamblin** [comment]
`spack dependents` only shows direct dependencies by default.  You want `spack dependents --transitive`.

```
$ spack dependents --transitive hdf5
abinit         conduit   grackle     lbann      ncl                partitionfinder  py-meep           raft
adios          dealii    grib-api    libemos    nco                petsc            py-netcdf4        rockstar
adios2         eccodes   h5hut       libmesh    ncview             pflotran         py-ont-fast5-api  samrai
alquimia       esmf      h5part      libsplash  netcdf             py-abipy         py-petsc4py       savanna
armadillo      espresso  h5utils     lulesh     netcdf-cxx         py-astropy       py-pipits         silo
aspa           etsf-io   h5z-zfp     magics     netcdf-cxx4        py-biom-format   py-pytables       simulationio
caffe          exodusii  hdf5-blosc  matio      netcdf-fortran     py-cdat-lite     py-slepc4py       slepc
cdo            falcon    highfive    meep       octave             py-cdo           py-sncosmo        slurm
cgns           fastmath  ibmisc      meshkit    octave-splines     py-dxchange      py-tomopy         swiftsim
chombo         fenics    ior         mfem       octopus            py-dxfile        py-tuiview        trilinos
cleverleaf     ferret    julia       moab       of-adios-write     py-guidata       py-wcsaxes        visit
cmor           flann     kallisto    molcas     ont-albacore       py-guiqwt        py-yt             vtk
cntk           gdal      kealib      nalu       opencv             py-h5py          quinoa            xsdk
codar-cheetah  gmsh      lammps      nccmp      pacbio-dextractor  py-mdanalysis    r-ncdf4           xsdktrilinos
```

**Comment by tgamblin** [comment]
Note that `spack dependents` and `spack dependencies` by default show all *possible dependencies*, regardless of conditions (variants and optional dependencies).  If you use `spack dependen*  --installed`, they'll show *actual* dependencies/dependents for an installed package (e.g. everything installed that depends on MPI).

`spack spec` and `spack graph` by default show what happens when the spec you provide is concretized; so they're really graphing what would be installed if you asked for that thing.  You can get `spack graph` to show you a graph of possible dependencies with `spack graph --static`.

**Comment by markcmiller86** [comment]
Great. `spack dependents --transitive` is exactly what I needed. Thanks.

BTW... `spack graph --static nalu` still doesn't produce `hdf5` anywhere in the output.

At the same time, that really isn't important to me at this point either.
