### ISSUE TITLE
Install error after downloading code from Openwrt 15.05

### ISSUE THREAD

**Issue by hinson-liu** [LLNL/spack#5329]
I try to use git clone git://git.openwrt.org/15.05/openwrt.git
./scripts/feeds update -a 
./scripts/feeds install -a 
## to update openwrt 15.05 but found below issue 

the Update feed is ok 

Updating feed 'packages' from 'https://github.com/openwrt/packages.git;for-15.05' ...
Cloning into './feeds/packages'...
remote: Counting objects: 2702, done.
remote: Compressing objects: 100% (2276/2276), done.
remote: Total 2702 (delta 100), reused 2254 (delta 65), pack-reused 0
Receiving objects: 100% (2702/2702), 1.72 MiB | 1.91 MiB/s, done.
Resolving deltas: 100% (100/100), done.

when install :+1: 
Build dependency: Please install Git (git-core) >= 1.6.5

Prerequisite check failed. Use FORCE=1 to override.
make[1]: *** [staging_dir/host/.prereq-build] Error 1
make: *** [prepare-tmpinfo] Error 2
Cannot open './tmp/.packageinfo': No such file or directory
Can't open file './tmp/.targetinfo': No such file or directory

I got this issue , try to update this with master branch git in mydir/feeds/package/net/git  but not work.

Any help would be appreciated
Thanks

**Comment by hinson-liu** [comment]
I try to use the Master branch code on my environment but worked ok 
The PC with ubuntu 14.04 is 64bit with me
also when i use 32bit pc this 15.05 branch worked also 
looks like related to working environment?

_Ask for help ----From a newer_

**Comment by hinson-liu** [comment]
Any comment ?

**Comment by scheibelp** [comment]
Generally Spack expects to clone the source itself. The section http://spack.readthedocs.io/en/latest/packaging_guide.html#git talks about how to tell Spack to fetch source using git (if you are building an Openwrt package). Or are you building a package which depends on Openwrt?

**Comment by hinson-liu** [comment]
@scheibelp Thanks for your reply. i was try to install Openwrt , and build it .Below is  the steps from Wiki of Openwrt.
https://wiki.openwrt.org/doc/howto/buildroot.exigence
Usually this should not have the above error ,however ,it happens and i have no idea where to track into. Since when i use the trunk branch (Master) will work fine . 
BTW: i have also try to  use package of git in Master Branch of OpenWrt to replace the one in 15.05 , but also fail .  Any more comment on the wiki steps ?

**Comment by puleglot** [comment]
It is an openwrt bug in ```include/prereq-build.mk```:
https://github.com/openwrt/openwrt/blob/chaos_calmer/include/prereq-build.mk#L148
And it is already fixed in LEDE.

**Comment by scheibelp** [comment]
This appears to not be related to Spack so I'm going to close this (but perhaps https://github.com/LLNL/spack/issues/5329#issuecomment-336408884 is useful). If you are having an issue with `spack install openwrt` for example feel free to reopen.
