### ISSUE TITLE
Problems compiling boost with intel

### ISSUE THREAD

**Issue by luigi-calori** [LLNL/spack#535]
I' m trying to build boost with intel as
spack -d --verbose install --jobs 20 --keep-stage boost%intel@15.0.2

result is 

==> Building boost
==> ./bootstrap.sh --prefix=/galileo/home/userinternal/lcalori0/myinstall/spack_sources/spack_virtualgl/opt/spack/linux-x86_64/intel-15.0.2/boost-1.60.0-3kzhbi5ii2szlnvbiixnqoxprv2g4ii2 --with-toolset=intel --with-libraries=locale,random,wave,atomic,serialization,iostreams,regex,date_time,log,thread,chrono,graph,system,signals,program_options,filesystem,test,math
Building Boost.Build engine with toolset intel... 
Failed to build Boost.Build build engine
Consult 'bootstrap.log' for more details

That read:
### 
### 
### 
### 
### 

I' ll try to make a PR with patch

**Comment by tgamblin** [comment]
It looks like the `intel` toolset has changed in more recent versions of boost and we'll need to include the platform in the name to translate to `bjam`.  i think this patch should be relatively simple to make. 

Out of curiosity, does the boost build work with prior versions of boost, e.g. `boost@1.59.0`? or `boost@1.47.0`?

**Comment by luigi-calori** [comment]
tested with 1.47.0 ... it' s the same
I' ve also got some issue with the fact that the toolset is specified twice: 
once as a bootstrap.sh option --with-toolset ( line 118 ) and another ( newly added 126-128) in user-config.jam
I've tried to remove the second one and it seem workin
Is it ok?
Now I plan to test python and mpi

**Comment by citibeth** [comment]
Do the following instructions help?

https://software.intel.com/en-us/articles/building-boost-with-intel-c-compiler-150

**Comment by luigi-calori** [comment]
Thanks for  the hint.
The procedure suggested there is different from what Spack currently does:

1) It' s already possible to register a script to be executed by a compiler to set up it's environment? Currently in order to use my intel compiler ( provided with modules ) with Spack I have to manually load it in the shell where spack commands will be executed, otherwise things do not work.
Is there currently a better approach with new external modules support?
As I' m finding other issues with Intel compiler,  [Status of intel based builds](https://groups.google.com/forum/#!topic/spack/Jj9-iWiMIAU)  would make sure my setup is correct

2) in my PR #550  I' ve tried to adapt to the current package implementation. I think it is working ( it is compiling ) but did not tried to link to it yet.

3) the current implementation adds a lot of variants, letting the user select the components but this has other drawback such as the long filename that prevent log file to be created and errors if the selected version does not include one of the ( default on ) variants, as reported on the list:
[Broken boost builds](https://groups.google.com/forum/#!topic/spack/Pv0DXuplJDU)

**Comment by alalazo** [comment]
@luigi-calori We are currently able to build `boost` with the Intel compiler. Is this still an issue for you, or can we close it?

**Comment by alalazo** [comment]
Closed as there was no reply since March. Feel free to reopen if still an issue.
