### ISSUE TITLE
Non-boolean variant does not work in ADIOS

### ISSUE THREAD

**Issue by kshitij-v-mehta** [LLNL/spack#5379]
Recent updates to spack have introduced the with-or-without functionality. 
In the adios package, the `staging` variant was modified accordingly to have multiple values: flexpath and dataspaces.

Now `spack install adios staging=flexpath` does not install adios with flexpath. The staging variant seems to be ignored.

**Comment by davydden** [comment]
I am not sure, but it looks like there are other issues in `adios`: 

```
    depends_on('libevpath', when='+flexpath')
    depends_on('libevpath', when='+staging')
```
should probably be
```
    depends_on('libevpath', when='staging=flexpath')
    depends_on('libevpath', when='staging=???')
```

p.s. supposedly the relevant PR is https://github.com/LLNL/spack/pull/5020

@alalazo ping.

**Comment by alalazo** [comment]
Can you confirm #5392 works?

**Comment by kshitij-v-mehta** [comment]
Thanks for the fix!
