### ISSUE TITLE
spack path length too long for Python scripts that use #!

### ISSUE THREAD

**Issue by lee218llnl** [LLNL/spack#54]
I suspect this will be an issue in general with spack python builds given the inherently long path:

rzalastor1@lee218:/collab/usr/gapps/python/build/spack/opt/spack/chaos_5_x86_64_ib/gcc-4.4.7/python-2.7.10-yqkr6m74axh3nafjscgtjb3zj3htx3fe/bin/ipython	
bash: /collab/usr/gapps/python/build/spack/opt/spack/chaos_5_x86_64_ib/gcc-4.4.7/python-2.7.10-yqkr6m74axh3nafjscgtjb3zj3htx3fe/bin/ipython: /collab/usr/gapps/python/build/spack/opt/spack/chaos_5_x86_64_ib/gcc-4.4.7/pyt: bad interpreter: Permission denied

**Comment by tgamblin** [comment]
@lee218llnl we could get rid of 42 characters of that particular path by getting rid of the prefix.  e.g., we could install by default into $spack/opt/spack/<hash>.  The only problem is that you lose human readability that way.  That could be solved with Matt's views.  I had thought about making a minimal install location, and using views for actually browsing, but it seemed like we could get the best of both worlds.

I know @mplegendre likes the default paths.  @mplegendre: any thoughts on this?  Looks like the default length for shebang paths in Linux is 128 bytes :-1: http://lxr.free-electrons.com/source/include/uapi/linux/binfmts.h#L18

**Comment by jprotze** [comment]
The alternative would be using some wrapper script to handle oversized 
shebangs as in:

http://stackoverflow.com/questions/10813538/shebang-line-limit-in-bash-and-linux-kernel

- Joachim

Am 09.06.2015 um 13:43 schrieb Todd Gamblin:
> @lee218llnl <https://github.com/lee218llnl> we could get rid of 42
> characters of that particular path by getting rid of the prefix. e.g.,
> we could install by default into $spack/opt/spack/. The only problem is
> that you lose human readability that way. That could be solved with
> Matt's views. I had thought about making a minimal install location, and
> using views for actually browsing, but it seemed like we could get the
> best of both worlds.
>
> I know @mplegendre <https://github.com/mplegendre> likes the default
> paths. @mplegendre <https://github.com/mplegendre>: any thoughts on
> this? Looks like the default length for shebang paths in Linux is 128
> bytes :-1:
> http://lxr.free-electrons.com/source/include/uapi/linux/binfmts.h#L18
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/scalability-llnl/spack/issues/54#issuecomment-110498972>.
>


-- 
Dipl.-Inf. Joachim Protze

IT Center
Group: High Performance Computing
Division: Computational Science and Engineering
RWTH Aachen University
Seffenter Weg 23
D 52074  Aachen (Germany)
Tel: +49 241 80- 24765
Fax: +49 241 80-624765
protze@itc.rwth-aachen.de
www.itc.rwth-aachen.de

**Comment by tgamblin** [comment]
I think that's more of a pain because we'd have to implement wrapper generation in Spack for everything installed as a script.  I suppose I can imagine how to implement that, but it does change the way the package is installed.  I worry that this would break assumptions for some packages, though.  Imagine a package where the author wants to patch an installed script, but Spack replaces it with a wrapper.  I suppose if spack does that only after all build tasks it would be ok, but I still think it might be hard to maintain...

**Comment by cyrush** [comment]
This bit us on chaos5 LLNL LC systems -- the kernel limit is actually *80* chars (after the shebang). 

For our path we were getting cut off before the the hash is even displayed.

**Comment by tgamblin** [comment]
@cyrush: not sure the kernel limit is actually 80 chars, but that is what is printed out if this error happens.  Want to test the fix I pushed?

**Comment by cyrush** [comment]
@tgamblin great timing -- we are meeting all day Tuesday to resolve build system issues. I will test this then.

**Comment by mathstuf** [comment]
I've seen shebangs being rewritten, so this should be fine now?

**Comment by tgamblin** [comment]
Yes.  We've had a number of reports of this being fixed.  Reopen if not.

**Comment by cyrush** [comment]
sorry for not reporting back -- we are successfully using the fix
