### ISSUE TITLE
Integration with System Package Managers

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#541]
With Emacs, the issue has come up of dependencies on the underlying OS that are not built by Spack.  For example, Emacs relies on GTK, which Spack does not (currently) build.  Although it would be nice for Spack to build GTK one day, that would require a number of packages.  And... in many cases, that would not be desirable: it's a good idea to use the widgets shipped with the OS when displaying windows on the OS.

PR #120 now allows one to specify that some packages are to be not built, using the system instead.  But other than "not building" a package, Spack provides no other mechanisms to ensure that the correct prerequisite system packages are installed before building.  I then have to manually guess what to install with yum or apt-get.  For example, I required the following to build Emacs on my Ubuntu 14.04 LTS machine:

```
    # For Ubuntu 14.04 LTS:
    #     sudo apt-get install libgtk-3-dev libxpm-dev libtiff5-dev libjpeg8-dev libgif-dev libpng12-dev
```

It would be nice if this could be formalized, encoded and automated.  In general, it would work either as:
1. A bunch of system packages to install as prerequisited.  I.e. the prerequisites above would be listed in the emacs/package.py.
2. An extension of the nobuild functionality.  In this case, one would have to create at least a dummy Spack package for all the prerequisites above.

Then, when Spack runs, it could automatically call yum/apt-get to get the correct system stuff installed.  There are caveats here, of course:
 a) Spack usually doesn't run as root.  So it will need to just SUGGEST what needs to be installed and get the user to install it.
 b) This will all be OS-specific.  There will be different list of system package installs on a per-OS basis.

**Comment by citibeth** [comment]
OK, here is a more specific proposal, I'm looking for comments.

1. (Already done): the version `@system` means the OS-installed version of a package.  Spack internals can interpret this specially if and when needed.

2. spack.Version will need to be able to numerically compare '@system' with regular numeric versions.  Eg: is 'openssl@system' < 'openssl@1.2.4'?  It will do this by using yum/apt-get/etc. to inspect the system-installed version.  That will be either done once per Spack run (if it's fast enough), or cached when you "instlal" an `@system` version.  In the case of a system upgrade, there would need to be a procedure to update all the numerical equivalents to the `@system` versions in the Spack database.

This version comparison will allow conditional depends_on to work appropriately.  For example:
```
                depends_on('binutils@2.23:')
```
would be able to use the system-installed version of binutils on a newer Linux, but would install its own binutils on an older LInux.

4. Make OS specs as functional as package specs.  I should be able to say, for example: `ubuntu@14.04:`, `rhel@:6`, etc.

3. Packages can (optionally) add a os_packages() method.  It will return a list of OS packages whose installation would be consistent with this installation.  For exampe:
```
class OpenSSL(Package):
    def os_packages():
        if (system matches 'ubuntu@14.04:'):
            return ['openssl']
        elif (system matches 'rhel'):
             return ['openssl']
```

4. When a user tries to install the '@system' version of a package, Spack will try to call os_packages().  If that succeeds, then it will check that the list of packages is properly installed (via apt-get, yum, or whatever).  If they are, it will proceed to look up a the version number that's intsalled (by running apt-get, yum, etc. on the first item in the returned list) and produce a dummy installation in Spack.  If they are not installed, it will stop and produce an error, telling the user which apt-get/yum command to run.  (This prevents any need for Spack to run as root; the restriction could be relaxed later, if people are willing and able to make that security choice).

**Comment by brettviren** [comment]
Two random comments.

* A lazy function can do a "dpkg -l" or "rpm -qa" (maybe similar for mac/brew) the first time an `@system` needs to be resolved to a version string.  The entire result for all OS packages can then be memoized into a package-version map.  I think subsequent lookups of this map should be fast enough to not be a concern.

* There are vendor-specific version string "spelling" to worry about.  Eg, on my Ubuntu 15.04 workstation openssl is version `1.0.1f-1ubuntu11` while on RHEL 6.7 it looks like `1.0.1e-42.el6_7.2.x86_64`.  Besides OpenSSL's own little letter version ("f" vs "e") there is the distro-specific extra stuff to complicate version comparisons.

I have some discussion points which I'll take to the mailing list.

**Comment by mathstuf** [comment]
> A lazy function can do a "dpkg -l" or "rpm -qa" (maybe similar for mac/brew) the first time an @system needs to be resolved to a version string. The entire result for all OS packages can then be memoized into a package-version map. I think subsequent lookups of this map should be fast enough to not be a concern.

Installed packages can change over time. How would the cache be rebuilt?

> There are vendor-specific version string "spelling" to worry about. Eg, on my Ubuntu 15.04 workstation openssl is version 1.0.1f-1ubuntu11 while on RHEL 6.7 it looks like 1.0.1e-42.el6_7.2.x86_64. Besides OpenSSL's own little letter version ("f" vs "e") there is the distro-specific extra stuff to complicate version comparisons.

For RPM at least, you can just do `rpm -q --qf "%{version}\n" $package` to get just the version. However, if multilib is installed, you'll get two entries: one for the 32bit and another for the 64bit, so something like `%{version} %{arch}\n` might be a better format where spack can then filter out the arches which don't apply.

**Comment by citibeth** [comment]
I'm not sure it's worth the effort to track the system-supplied version.
If you REALLY care what version you're using, you should built it yourself
with Spack.

-- Elizabeth

**Comment by brettviren** [comment]
Ben Boeckel <notifications@github.com> writes:

>     A lazy function can do a "dpkg -l" or "rpm -qa" (maybe similar for
>     mac/brew) the first time an @system needs to be resolved to a
>     version string. The entire result for all OS packages can then be
>     memoized into a package-version map. I think subsequent lookups of
>     this map should be fast enough to not be a concern.
>
> Installed packages can change over time. How would the cache be
> rebuilt?

There's no persistent cache intended.  I am merely suggesting that a
single "dpkg -l" or "rpm -qa" (etc) be run to get a full listing of
*all* OS packages installed when Spack encounters the first @system
reference and then save this full list in memory in case any subsequent
@system references are encountered.

This was merely a suggestion as to how to avoid suffering the time
penalty that per-@system-package calls to "dpkg" and "rpm" would incur.


-Brett.

**Comment by mathstuf** [comment]
Ah, yeah, a cache per-run would be fine.

@citibeth The reason for finding the version is so that you can satisfy version requirements without (potentially obscure) errors later. If something requires `cmake@3.3:`, but the system cmake is 3.2, spack should automatically build a viable cmake for you instead of erroring out in that package's build.

**Comment by citibeth** [comment]
The approach outlined in this Issue is the "right" approach according to
the Spack model.  But I'm also beginning to believe it's so complex that it
might never get implemented.  And once implemented, it would force users to
create a lot of entries in packages.yaml, and a lot of dummy packges for
things that Spack might never know how to build.  So.. I think it's too
hard to implement and too hard to use.

I'm going to suggest here an alternate approach.  It doesn't necessarily
subsume the approach being discussed; but it would get something that gives
us 80% easily, allowing for a possible transition over time.  The proposal:

Add a depends_on_os() directive to be used in ``package.py``.  When the
package is installed, Spack would first check that the given packages are
installed via rpm/apt-get/etc.  If not, it would tell the user what to
install and quit.  Mock-up examples:

class Mypackage(Package);
    variant('gui', ...)
    depends_on_os('kde-devel', 'xaw-devel', when='+gui', os='CentOS@7')
    depends_on_os('libkde-dev', 'libxaw-dev', when='+gui', os='Ubuntu@14.04
')

I believe there's already smarts in Spack about OS versions, so this
feature would need to use whatever is already there to specify OS versions.

-- Elizabeth

**Comment by brettviren** [comment]
I would like to push for not placing any information about the OS/non-OS disposition of a dependency into a `package.py` file.  Several reasons:

* One must repeat these `depends_on_os()` calls for every package that depends on KDE (taking your example).
* One must maintain two packages in order to handle one host wanting to build from source and another wanting to use the OS package - on the same OS.

What I'd like is if we can come up with something where a package declares its dependencies as it does now with no knowledge as to how those dependencies are satisfied (that's Spack's job).

Then, have some way to write (ideally) a single `package.py` that can either present an existing OS package to Spack as if it were a normal Spack package OR build from source in the usual manner.

And, have a mechanism whereby the behavior that is actually followed depends on a policy setting by the user.  Eg, some user may want to ignore the OS package even if it exists, some user may want Spack to fail if the OS package is missing instead of failing over to building from source.

**Comment by alalazo** [comment]
Is this discussion still active? Can it be closed?

**Comment by citibeth** [comment]
I think this is supercede by #2700.  #2700 is more of a manual process.  But I think it will yield good results with a little bit of forethought: basically, that we ship Spack to work "out of the box" with system-supplied packages on certain Linux distros.  And that Spack's `packages.yaml` format can be extended to give a list of `yum installs` needed to make each package work.
