### ISSUE TITLE
need to specify preferred variant for mpi

### ISSUE THREAD

**Issue by olesenm** [LLNL/spack#5428]
For my package I have the following:

    depends_on('mpi')

since it is not restricted to any particular mpi implementation, but if openmpi is being selected (automatically or otherwise), I'd like to have a particular variant *required*. Eg, as pseudo-code

    depend_on('openmpi+thread_multiple', when="(mpi is openmpi)")

Adding this into `~/.spack/packages.yaml` isn't really an option since this doesn't work very well when distributing the package and would be rather error-prone.

What solutions are available?

I've tagged the usual suspects: @adamjstewart  @tgamblin @alalazo

**Comment by davydden** [comment]
```
conflicts('openmpi~thread_multiple', when='^openmpi')
```
is what you probably want.

**Comment by olesenm** [comment]
Thanks, this looks promising but seems to get ignored.
I guess this might be because the mpi dependency is indirectly resolved by the package dependency on `fftw`.

**Comment by davydden** [comment]
maybe something like
```
conflicts('^openmpi~thread_multiple')
```
will do? Given that you have `depends_on('mpi')`, that shall work.

**Comment by olesenm** [comment]
Unfortunately that just got me

    1. "^openmpi~thread_multiple" conflicts with "openfoam-com"

**Comment by davydden** [comment]
> Unfortunately that just got me 

but that's what you want, isn't it? You always want to use `openmpi+thread_multiple`, right?

**Comment by davydden** [comment]
> What I want is an additional layer of safety

that's what you get with the `conflict` statement.

>  If the specified or fallback value is openmpi, then I would like to insist that my package always wants openmpi with the +thread_multiple variant. 

as far as I know, that's not possible. You need to ask users to enable `+thread_multiple` from the command line or set this in their `packages.yaml`.

> this is IMO too fragile.

i don't think it's fragile, you have a `conflict`, there is no way anyone will build your package with `openmpi~ thread_multiple`. Nothing is fragile here.
Users might not like it, though. As if they are not careful, they will get error during concretization.

**Comment by olesenm** [comment]
Handled by PR https://github.com/LLNL/spack/pull/5479 which represents a less than optimal solution, but I really want to avoid any user installing a newer openfoam version with the wrong openmpi variant.
Of course, they should still be allowed to use any other mpi provider, but if the concretizer resolves openmpi, always have the +thread_multiple variant.

Making +thread_variant a default for openmpi would of course also circumvent this problem, but not really the nicest solution either.
