### ISSUE TITLE
libtool @2.4.6 does not install

### ISSUE THREAD

**Issue by deleeke** [LLNL/spack#544]
I was running into troubles when installing petsc.
It was getting an error when installing libtool, which it was by default going for the newest version.

```
/home/myusername/Repos/spack/var/spack/repos/builtin/packages/libtool/package.py:12, in install:
     11       def install(self, spec, prefix):
  >> 12           configure("--prefix=%s" % prefix)
     13   
     14           make()
     15           make("install")
==> Error: Installation process had nonzero exit code.
```

So i went in and commented out `version('2.4.6', .....` because libtool @ 2.4.2 is working fine.

**Comment by adamjstewart** [comment]
Can you post the `spack-build.out` and `config.log`?

**Comment by deleeke** [comment]
I searched around and could not find those files (grep, locate, etc)...in my messing around I may have gotten rid of them, or I might be looking in the wrong place?

Anyways, I just tried to re-create the problem and actually it only fails when I am trying to install petsc
```
me@myhost:~/path/to/spack$ spack install petsc
==> Installing petsc
==> Installing hypre
==> Installing openmpi
==> Installing hwloc
==> Installing libpciaccess
==> Installing libtool
==> Trying to fetch from http://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz
######################################################################## 100.0%
curl: (7) Failed to connect to mirrors.axint.net port 80: No route to host
==> Fetching from http://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz failed.
==> Error: All fetchers failed for libtool-2.4.6-e4qlvqh6swwfj6ixwhyjbg6ku5zgfvdr
==> Error: Installation process had nonzero exit code.
```
That error code is also more informative, looks like it has a stale link.

But if I just try and install libtool @ 2.4.6 it does fine:
```
me@myhost:~/path/to/spack$ spack install libtool @2.4.6
==> Installing libtool
==> Trying to fetch from http://ftpmirror.gnu.org/libtool/libtool-2.4.6.tar.gz
######################################################################## 100.0%
==> Staging archive: /path/to/spack/var/spack/stage/libtool-2.4.6-e4qlvqh6swwfj6ixwhyjbg6ku5zgfvdr/libtool-2.4.6.tar.gz
==> Created stage in /path/to/spack/var/spack/stage/libtool-2.4.6-e4qlvqh6swwfj6ixwhyjbg6ku5zgfvdr
==> No patches needed for libtool
==> Building libtool
==> Successfully installed libtool
  Fetch: 14.38s.  Build: 14.57s.  Total: 28.95s.
[+] /path/to/spack/opt/spack/linux-x86_64/gcc-4.8/libtool-2.4.6-e4qlvqh6swwfj6ixwhyjbg6ku5zgfvdr
```

**Comment by adamjstewart** [comment]
Hmm, these are definitely different errors then. In the first error you reported, you failed during configure. In the second error you reported, you were unable to download the file at all. I just successfully downloaded both with wget, so the URLs are valid. What version of cURL are you running?

**Comment by citibeth** [comment]
What is your OS?

**Comment by deleeke** [comment]
I'm on Ubuntu 14.04 (64bit)

```
~$ curl --version
curl 7.35.0 (x86_64-pc-linux-gnu) libcurl/7.35.0 OpenSSL/1.0.1f zlib/1.2.8 libidn/1.28 librtmp/2.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtmp rtsp smtp smtps telnet tftp 
Features: AsynchDNS GSS-Negotiate IDN IPv6 Largefile NTLM NTLM_WB SSL libz TLS-SRP 
```

**Comment by adamjstewart** [comment]
Can you try changing url from http://ftpmirror.gnu.org/libtool/libtool-2.4.2.tar.gz to ftp://ftp.gnu.org/gnu/libtool/libtool-2.4.2.tar.gz in the package.py file?

**Comment by deleeke** [comment]
I did a fresh ```git clone https://github.com/LLNL/spack.git ``` and edited the libtool package.py. Installing petsc went fine, no errors.

**Comment by adamjstewart** [comment]
I just installed libtool@2.4.6 without any problems. Is anyone else still seeing this issue or can this be closed?

**Comment by adamjstewart** [comment]
#883 claims that this has been solved, so I think this can be closed.
