### ISSUE TITLE
spack.stage.Stage() not working for Git strategy

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/spack#5462]
I have the following script...

```
#!/usr/bin/env spack-python

import spack
import spack.main
import spack.store
from spack.main import SpackCommand
from llnl.util.filesystem import working_dir
from spack.util.executable import which

import os
import mmap
import re
from shutil import rmtree as rmdashf
import sys

idir = '/Users/miller86/spack/spack/opt/foobar'
rmdashf(idir)
spack.store.layout = spack.directory_layout.YamlDirectoryLayout(idir)
spack.store.db = spack.database.Database(idir)

pkgSpec = 'amrex'
specs = spack.cmd.parse_specs(pkgSpec, concretize=True)
assert(len(specs)==1)
pkg = spack.repo.get(specs[0])

with spack.stage.Stage(pkg.url) as stage:
    stage.fetch()
    print os.getcwd()
    print os.listdir(os.getcwd())
```

If I use `amrex` (a Git fetch strategy package), I get this output...

```
[scratlantis:~/spack/spack] miller86% ./fitck_download.py
Git
==> Fetching https://github.com/AMReX-Codes/amrex.git
######################################################################## 100.0%
==> Warning: The contents of 
  the archive
   look like HTML.
  The checksum will likely be bad.  If it is, you can use
  'spack clean <package>' to remove the bad archive, then
  fix your internet gateway issue and install again.
/private/var/folders/nx/mtgf501d3573jd6cmgv9lnzr0003jr/T/miller86/spack-stage/spack-stage-CCVG_A
['amrex.git']
```

In particular, it does not actually stage the package but instead appears to attempt to fetch amrex vi its Get repo URL. The downloaded file is indeed an HTML file with...

```
<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

However, if I do zlib, a URL fetch strategy, it works as expected.

I think this is a bug.

**Comment by tgamblin** [comment]
`Stage` takes a URL or a `FetchStrategy`, and it checks that by testing whether the parameter is a `str` or  a `FetchStrategy`.  It doesn't inspect the URL; the fetcher to use is determined based on the package version and the `kwargs` passed to `version`.  Look at `fetch_strategy.for_package_version()`.

You can use `pkg.stage` instead, which figures all that out for you:

```python
with pkg.stage as stage:
    stage.fetch()
    # etc.
```

**Comment by markcmiller86** [comment]
Well, when I try that, I get a different kind of problem...

```
[scratlantis:~/spack/spack] miller86% ./fitck_download.py
Traceback (most recent call last):
  File "./fitck_download.py", line 69, in <module>
    with pkg.stage() as stage:
TypeError: 'StageComposite' object is not callable
```

**Comment by markcmiller86** [comment]
Also, I did not find a way to create a `FetchStrategy` from a package. I tried passing pkg.fetcher to spack.stage.Stage() but that failed also. Am looking for examples of this stuff in actualy use too and not always able to find examples

**Comment by markcmiller86** [comment]
I guess another way of asking the same question is this.

Is there an example or is anyone aware of `spack.stage.Stage()` working for a package employing a Git Fetch Strategy? I had assumed, perhaps naively, that `spack.stage.Stage()` would work for any kind of package fetch strategy.

**Comment by scheibelp** [comment]
The error:

```
Traceback (most recent call last):
  File "./fitck_download.py", line 69, in <module>
    with pkg.stage() as stage:
TypeError: 'StageComposite' object is not callable
```

indicates that you did

```
with pkg.stage() as stage:
    stage.fetch()
```

vs. 

```
with pkg.stage as stage:
    stage.fetch()
```

Does it fail when you try the latter?

**Comment by markcmiller86** [comment]
Ah, ok, that worked. Thanks so much!
