### ISSUE TITLE
MPI as external package not working

### ISSUE THREAD

**Issue by KineticTheory** [LLNL/spack#5473]
I'm on a Linux system and I use external packages for the compiler and MPI. The compiler works fine, but a very simply TPL won't build due to MPI issues (actually *hwloc*). This is a new issue that appeared over the last few weeks.

```
% spack install parmetis % intel@17.0.4 ^ openmpi@1.10.5
==> openmpi@1.10.5 : has external module in openmpi/1.10.5
==> openmpi@1.10.5 : is actually installed in /usr/projects/hpcsoft/toss3/snow/openmpi/1.10.5-intel-17.0.4
==> openmpi@1.10.5 : generating module file
==> Error: 'No spec with name hwloc in openmpi@1.10.5%intel@17.0.4~cuda fabrics=verbs ~java schedulers= ~sqlite3~thread_multiple+vt arch=linux-rhel7-x86_64'
```

* packages.yaml
```
packages:
  openmpi:
    version: [1.10.5]
    modules:
      openmpi@1.10.5: openmpi/1.10.5
```

* The spec seems happy:

```
% spack spec parmetis % intel@17.0.4 ^ openmpi@1.10.5
Input spec
--------------------------------
parmetis%intel@17.0.4
    ^openmpi@1.10.5

Normalized
--------------------------------
parmetis%intel@17.0.4
    ^cmake@2.8:
    ^metis@5:
    ^openmpi@1.10.5
        ^hwloc
            ^pkg-config

Concretized
--------------------------------
parmetis@4.0.3%intel@17.0.4~debug~gdb+shared arch=linux-rhel7-x86_64 
    ^cmake@3.9.0%intel@17.0.4~doc+ncurses+openssl+ownlibs~qt arch=linux-rhel7-x86_64 
    ^metis@5.1.0%intel@17.0.4~debug~gdb~int64~real64+shared arch=linux-rhel7-x86_64 
    ^openmpi@1.10.5%intel@17.0.4~cuda fabrics=verbs ~java schedulers= ~sqlite3~thread_multiple+vt arch=linux-rhel7-x86_64 
```

Also:
* Using `--dirty` doesn't help.
* Same error with different versions of openmpi.
* I'm not sure why spack needs to know about hwloc since only the MPI dependency needs it and MPI is *external*.

Suggestions or workarounds are welcome.

**Comment by KineticTheory** [comment]
On a whim, I tried the `--only package` option to `spack install` and that allows me to move forward.  But this behavior seems broken.

**Comment by pramodskumbhar** [comment]
Could you post debug output? (spack -d install ...)
I think I have seen this myself but don't remember precisely ATM.

**Comment by KineticTheory** [comment]
Ah - I found the issue.  It was a stupid user issue.  I had an openmpi module already loaded in my environment.  I think spack was failing to load the new openmpi module (as specified in packages.yaml) due to a module-conflict.  

That '-d' option is really nice. I didn't know about it.  Thanks!

**Comment by pramodskumbhar** [comment]
@KineticTheory : I am seeing this issue again if I switched to latest develop (see #3581). Are you using latest develop?

**Comment by KineticTheory** [comment]
@pramodskumbhar Yes, I'm seeing this error again with the most recent 'develop' branch of spack.  I did a fresh clone into a new directory.

**Comment by mamelara** [comment]
Just adding my findings here too:

```shell
mamelara@cori09 ~ $ spack install abinit%intel+hdf5+openmp+scalapack ^intel-mkl
==> libxc is already installed in /global/homes/m/mamelara/common/sw/cray-cnl6-haswell/libxc/2.2.2/intel/17.0.2.174/jvk2ots
==> hdf5@1.10.0.3 : has external module in cray-hdf5-parallel
==> hdf5@1.10.0.3 : is actually installed in /opt/cray/pe/hdf5-parallel/1.10.0.3/INTEL/16.0
==> hdf5@1.10.0.3 : generating module file
==> Error: 'No spec with name mpi in hdf5@1.10.0.3%intel@17.0.2.174+cxx~debug+fortran+mpi+pic~shared~szip~threadsafe arch=cray-cnl6-haswell'
```
it looks like it's in configure_options in the BaseContext class in common.py

**Comment by scheibelp** [comment]
I'll try to look at this tomorrow (9/29)

**Comment by scheibelp** [comment]
@KineticTheory @mamelara do you have relevant dependencies for your respective cases defined as externals in packages.yaml?

**Comment by pramodskumbhar** [comment]
@scheibelp : in above OpenMPI case even if I add `hwloc` entry in `packages.yaml`, nothing changes.

**Comment by alalazo** [comment]
@scheibelp I was pointed to this issue from a discussion in the modules channel on Slack. I'll probably have a fix ready by today - so don't worry diving into it.
