### ISSUE TITLE
Patch path to python in shebang after installation

### ISSUE THREAD

**Issue by dlukes** [LLNL/spack#5484]
I'm putting together a package which installs (among other things) python scripts which have hardcoded `#!/usr/bin/python` shebangs, and I would like to replace these with the version of Python used as an optional dependency for the package (if provided). I know I can get the appropriate path in the package definition file with `self.spec["python"].prefix.bin.python`, but I wasn't able to figure out where to put the shebang replacing code. Is there some kind of post-install hook that I can implement?

(I took a look at the documentation for `spack.build_systems.autotools.AutotoolsPackage` and `spack.package.PackageBase`, but maybe I missed something, in which case apologies!)

**Comment by michaelkuhn** [comment]
Take a look at #5195 where I do something similar for csh. You can add a method with `run_before` or `run_after`. If you use `run_before('install')`, Spack's sbang hook will automatically fix up lines that are too long.

**Comment by dlukes** [comment]
Thank you very much, I'll investigate!

**Comment by dlukes** [comment]
This is perfect, thank you very much!
