### ISSUE TITLE
Comments on package/plumed

### ISSUE THREAD

**Issue by GiovanniBussi** [LLNL/spack#5506]
Dear all,

@alalazo asked me to have a look at the [plumed package](https://github.com/LLNL/spack/blob/develop/var/spack/repos/builtin/packages/plumed/package.py) in spack. First of all, thanks to you guys for maintaining it and helping people installing PLUMED on their systems.

I am not sure how much I can help, though I write some comments below. I hope this is the right place to do it.

#### List of patches
In [this part](https://github.com/LLNL/spack/blob/733965b3c6fdc9bb16b5c9985fe5ff35d31a5a22/var/spack/repos/builtin/packages/plumed/package.py#L78) you are hardcoding a map of indexes of plumed patches. I think this is correct since you point to a specific plumed version (X.Y.Z). However, I guess your life could be a bit easier using the following commands:

````
  plumed patch -q -l | grep -v Available
````

should print a list of the available patches, and

````
  plumed patch -e gromacs-5.1.4 -p
````

would directly apply the patch for gromacs-5.1.4, without knowing which is its index in the list. You may construct the list within the `apply_patch` method, so as to avoid the need to update your map at every new PLUMED release.

#### Patch command

In [this part](https://github.com/LLNL/spack/blob/733965b3c6fdc9bb16b5c9985fe5ff35d31a5a22/var/spack/repos/builtin/packages/plumed/package.py#L120) you call `plumed` executable directly. Notice that:

- If the node on which you run the install job has no MPI available and your `plumed` executable is linked to MPI, you might have troubles. `plumed --no-mpi` should work in this case.
- If you are cross-compiling, also `plumed --no-mpi` will not work. `plumed-patch` directly calls a bash scripts and is the most general choice.

So, I would recommend using `plumed-patch`, which always works. It should be installed side-by-side with the regular `plumed` executable.

#### Linking plumed and MD codes

I see you patch MD codes with `plumed patch -p`, which by defaults links plumed as a shared library. You might want to try `plumed patch --runtime -p`, which does the following:
- Link a single object file, plus `-ldl` flag. This object is a dummy wrapper that never changes.
- When MD code is launched, it looks for plumed based on the `PLUMED_KERNEL` environment variable. Basically, shared object `libplumedKernel.so` is opened with `dlopen`. 

I am using this procedure to keep up to date a local cluster using tcl env modules. I basically have a number of gromacs and plumed modules (corresponding to different versions) that can be combined in an arbitrary manner.

**warning**: the following comments would not work with some of the PLUMED versions that you support, so they might be useless.

#### GSL and BLAS

[Here](https://github.com/LLNL/spack/blob/733965b3c6fdc9bb16b5c9985fe5ff35d31a5a22/var/spack/repos/builtin/packages/plumed/package.py#L138) you remove `-lgslcblas` from the libraries that are linked. Notice that as of PLUMED 2.2.4 (and 2.3.0 as well) the problem you mention is solved. Namely, our `./configure` script first tries to link `-lgsl` alone, and `-lgslblas` is only linked if required. Thus, when using system BLAS and gsl, `-lgslblas` will not be linked.

#### About linked libraries

While implementing a `Portfile` for [MacPorts](https://github.com/macports/macports-ports/blob/b11eeec11714b8c4c376d11dc78e7c6ec828ada3/science/plumed/Portfile), I had troubles making sure that not-requested libs were not linked just because they were present in the system. In principle, one might explicitly disable features (e.g. using `--disable-matheval`). However, I found it easier to add an option to our `./configure` (`--disable-libsearch`, available as of PLUMED 2.3.2) which tells not to try any default name for libraries. Only libraries specified in `LIBS=...` are linked. So you can do for instance
````
./configure --disable-libsearch LIBS=-lmatheval
````
to enable matheval library.

I hope this helps... Thanks again and feel free to cross link our official repository whenever you find issues or want to propose solutions.

Regards

Giovanni

**Comment by alalazo** [comment]
@GiovanniBussi Thanks for the prompt feedback!

**Comment by alalazo** [comment]
Closed by accident because of a cherry-pick in our fork.
