### ISSUE TITLE
Spack create does not set version

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#551]
When running `spack create` on a URL, Spack correctly detects the version of the package:
```
$ spack create http://sourceforge.net/projects/pyqt/files/QScintilla2/QScintilla-2.9.1/QScintilla-gpl-2.9.1.tar.gz
==> This looks like a URL for QScintilla-gpl version 2.9.1
==> Creating template for package QScintilla-gpl
==> Warning: Got an error parsing HTML. Use Python 2.7.3 or newer for better HTML parsing.
  http://sourceforge.net/projects/pyqt/files/QScintilla2/QScintilla-2.9.1
  HTMLParseError: malformed start tag, at line 762, column 115
==> Downloading...
==> Trying to fetch from http://sourceforge.net/projects/pyqt/files/QScintilla2/QScintilla-2.9.1/QScintilla-gpl-2.9.1.tar.gz
######################################################################## 100.0%
==> Created package /blues/gpfs/home/software/spack/var/spack/repos/builtin/packages/QScintilla-gpl/package.py
```
but sets the version to `version`:
```python
version('version', '38e6248cb970adf6d05aea7d94f1288e')
```

**Comment by tgamblin** [comment]
I could swear someone recently submitted a fix for this... hm

**Comment by tgamblin** [comment]
Are you sure you're using the latest develop?

**Comment by eschnett** [comment]
This was still broken yesterday.

**Comment by adamjstewart** [comment]
Interesting. I checked out the latest develop branch and I can confirm that this bug still occurs on our CentOS 6 machine (which runs Python 2.6.6). However, based on the warning suggestion: "Use Python 2.7.3 or newer for better HTML parsing", I tried the same `spack create` out with Python 2.7.3 and 2.7.6 and the bug magically disappeared!
