### ISSUE TITLE
Bison fails to compile on Mac OS High Sierra

### ISSUE THREAD

**Issue by deOliveira-R** [LLNL/spack#5521]
Something seem to have changed in Mac OS High Sierra that breaks the build process of bison.
Apparently something related to a change in command line tools.

[spack-build.out.txt](https://github.com/LLNL/spack/files/1339056/spack-build.out.txt)

I have sent an email to bug-bison@gnu.org in order to investigate the issue.
I'm not very experienced so, in the mean time, anyone would care to look into this issue as well?

**Comment by tgamblin** [comment]
Are you using Spack with the MacPorts linker? If so can you try building without that?

**Comment by davydden** [comment]
Checkout Homebrew and see if rhey apply any pathes to bison. They certainly patch GCC for the new file system

**Comment by deOliveira-R** [comment]
I'm not using MacPorts. I do have Homebrew installed but I haven't downloaded any compiler, liker or part of the toolchain there... This is the purpose of spack on my system.

I did check Homebrew and they seem to apply a patch on top of Bison specifically targeted at High Sierra and later (I guess):

if MacOS.version >= :high_sierra
    patch :p0 do
      url "https://raw.githubusercontent.com/macports/macports-ports/14451f57e89/devel/bison/files/secure_snprintf.patch"
      sha256 "57f972940a10d448efbd3d5ba46e65979ae4eea93681a85e1d998060b356e0d2"
    end
  end

**Comment by tgamblin** [comment]
Thanks!  Mind adding that patch in Spack?  I think you'll need to add a mapping from `10.13` to `highsierra` to the `mac_releases` in `lib/spack/spack/operating_systems/macos.py`, and then you can add a `patch()` directive to bison.

**Comment by tgamblin** [comment]
Also, it's kind of amusing that spack people looked at homebrew to find a patch from macports 😄 .

**Comment by deOliveira-R** [comment]
I can try. I don't know how to do it since I'm new to spack, but I'm willing to learn.

Oh yeah... an example of shared development of sorts. XD

**Comment by tgamblin** [comment]
Great!  If you wait for #5476 to be merged, which should happen in a day or so, the needed patch directive should look pretty close to what homebrew's looks like:

```python
    patch('https://raw.githubusercontent.com/macports/macports-ports/14451f57e89/devel/bison/files/secure_snprintf.patch',
        level=0, 
        sha256='57f972940a10d448efbd3d5ba46e65979ae4eea93681a85e1d998060b356e0d2',
        when='os=highsierra')
```

#5476 is just needed for the sha256 -- currently patches in Spack only use MD5.

The other change is just a line in the macos detection logic.  I guess we need to be faster!

**Comment by deOliveira-R** [comment]
I can wait, sure. In the mean time I started a bugfix/bison branch and added highsierra to macos.py. I will wait for #5476 to be merged in order to merge it into bugfix/bison and go from there.

Is there a way to make the patch apply not only to "highsierra" but to anything later in order to make it future proof? In principle I shouldn't speculate if bison will need a patch or not in the future, but chances are massive that it will, so it sounds reasonable.

**Comment by tgamblin** [comment]
Yeah we should add a bit to the syntax to make mac versions comparable like the symbols homebrew uses.

Closest thing you can do right now, which should be fine, is this:

```
when=(int(platform.mac_ver()[0].split('.')[1]) >= 13)
```

That'll work.  The syntax isn't perfect for everything we do since technically it's a test on the host OS (i.e., the Spack execution environment) not the target OS (`os` on the spec), but we never cross compile on macs so it should be fine.

**Comment by tgamblin** [comment]
@deOliveira-R: FYI, #5476 is merged

**Comment by deOliveira-R** [comment]
Thanks! I'll have a go at this issue as soon as I can.

**Comment by deOliveira-R** [comment]
After adding "highsierra" to lib/spack/spack/operating_systems/macos.py and adding the patch line to Bison in var/spack/repos/builtin/packages/bison/package.py, it compiles successfully.

As a side effect of adding highsierra to macos.py, I got the error message:
` Error: No compilers found for operating system highsierra and target x86_64.
If previous installations have succeeded, the operating system may have been updated.
Compilers are defined for the following operating systems and targets:
	macos-x86_64
Run 'spack compiler find' to add compilers.`

When I run spack compilers I get the expected: 

`==> Available compilers
-- clang macos-x86_64 -------------------------------------------
clang@9.0.0-apple`

I dodged this by removing and reinstalling all packages. Was there an easier way?

**Comment by deOliveira-R** [comment]
In principle, the whole point of this is to compile llvm. Now I'm getting an error during compilation of gettext:

`==> Successfully installed gettext
  Fetch: 0.05s.  Build: 3m 38.24s.  Total: 3m 38.29s.
[+] /Users/rodrigo/opt/spack-tools/opt/spack/darwin-highsierra-x86_64/clang-9.0.0-apple/gettext-0.19.8.1-moozlpli7vyocs4ofpc7fkhuukgqayf2
==> Warning: Dependency missing due to corrupt install directory:
  /Users/rodrigo/opt/spack-tools/opt/spack/darwin-highsierra-x86_64/clang-9.0.0-apple/gettext-0.19.8.1-moozlpli7vyocs4ofpc7fkhuukgqayf2
  Specs gettext@0.19.8.1%clang@9.0.0-apple+bzip2+curses+git~libunistring+libxml2 patches=9acdb4e73f67c241b5ef32505c9ddf7cf6884ca8ea661692f21dca28483b04b8 +tar+xz arch=darwin-highsierra-x86_64 ^bzip2@1.0.6%clang@9.0.0-apple+shared arch=darwin-highsierra-x86_64 ^libxml2@2.9.4%clang@9.0.0-apple~python arch=darwin-highsierra-x86_64 ^ncurses@6.0%clang@9.0.0-apple patches=f84b2708a42777aadcc7f502a261afe10ca5646a51c1ef8b5e60d2070d926b57 ~symlinks arch=darwin-highsierra-x86_64 ^pkg-config@0.29.2%clang@9.0.0-apple+internal_glib arch=darwin-highsierra-x86_64 ^tar@1.29%clang@9.0.0-apple patches=08921fcbd732050c74ddf1de7d8ad95ffdbc09f8b4342456fa2f6a0dd02a957c,5c314db58d005043bf407abaf25eb9823b9032a22fd12a0b142d4bf548130fa4,d428578be7fb99b831eb61e53b8d88a859afe08b479a21238180899707d79ce4,e34d2470461037933737c0a60fbcc5d5ea905fefb6b414b4a2e88a440fcae23a arch=darwin-highsierra-x86_64 ^xz@5.2.3%clang@9.0.0-apple arch=darwin-highsierra-x86_64 ^zlib@1.2.11%clang@9.0.0-apple+pic+shared arch=darwin-highsierra-x86_64 and gettext@0.19.8.1%clang@9.0.0-apple+bzip2+curses+git~libunistring+libxml2 patches=9acdb4e73f67c241b5ef32505c9ddf7cf6884ca8ea661692f21dca28483b04b8 +tar+xz arch=darwin-highsierra-x86_64 ^bzip2@1.0.6%clang@9.0.0-apple+shared arch=darwin-highsierra-x86_64 ^libxml2@2.9.4%clang@9.0.0-apple~python arch=darwin-highsierra-x86_64 ^ncurses@6.0%clang@9.0.0-apple patches=f84b2708a42777aadcc7f502a261afe10ca5646a51c1ef8b5e60d2070d926b57 ~symlinks arch=darwin-highsierra-x86_64 ^tar@1.29%clang@9.0.0-apple patches=08921fcbd732050c74ddf1de7d8ad95ffdbc09f8b4342456fa2f6a0dd02a957c,5c314db58d005043bf407abaf25eb9823b9032a22fd12a0b142d4bf548130fa4,d428578be7fb99b831eb61e53b8d88a859afe08b479a21238180899707d79ce4,e34d2470461037933737c0a60fbcc5d5ea905fefb6b414b4a2e88a440fcae23a arch=darwin-highsierra-x86_64 ^xz@5.2.3%clang@9.0.0-apple arch=darwin-highsierra-x86_64 ^zlib@1.2.11%clang@9.0.0-apple+pic+shared arch=darwin-highsierra-x86_64 have the same SHA-1 prefix!`

Is this new, specific to me or worth another issue?

**Comment by deOliveira-R** [comment]
This seems to be good, pending only the merging.

Regarding the problem with gettext, which seems to be reproducible in my mac, a ubuntu machine at work and a scientific linux server, I will open another issue to discuss it!
