### ISSUE TITLE
Installing Licensed Software with Spack

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#553]
I would like to create a package to install the PGI compilers. The download and license key setup need to be done manually, but the build step can be completely automated. Does Spack currently have the capability to do this? If so, how do I tell it where to find my .tar.gz?

**Comment by tgamblin** [comment]
You can do this with a mirror.  make a package called, e.g., `pgi-compiler`.
```bash
$ mkdir -p local-pkgs/pgi-compiler
$ cp <tarball> local-pkgs/pgi-compiler/pgi-compiler-<version>.tar.gz
$ spack mirror add local file:///$(pwd)/local-pkgs
$ spack mirror list
$ spack mirror list
local    file:///Users/gamblin2/local
```
Spack should then be able to fetch from the mirror, if it can find the tarballs. The path format is basically just `$mirror/$package/$package-$version.tar.gz`.

The manual copying above is kind of cumbersome.  Spack currently makes it easy to create a mirror from remote packages, but it doesn't have an easy way to add local ones.  We could probably improve that, e.g. something like:

```bash
spack mirror add local-pkgs pgi-compiler@14.2 /path/to/tarball
```
Which would copy the tarball into place automatically...

**Comment by tgamblin** [comment]
Note that for some commercial stuff that doesn't come in nice tarballs, there is also the recently added `expand=False` feature from #499.

**Comment by adamjstewart** [comment]
What do I do about the `url`? Would I just use the homepage as a "fake" url? It would be neat if I could put a message to the user explaining how they need to download it manually and add it to a mirror. I guess I can just put that in the description.

**Comment by tgamblin** [comment]
Currently, yes, the URL would need to be something fake.  I think this is another aspect where the support for this use case could be better.  I probably don't have time to get this implemented right now, although if you want to take a stab at it that would be great.  There is already some support for fetching in a so-called `mirror_only` way in `package.py`.  It's there because it's used by the stage test.  It could probably be re-jiggered to use for this.... 

e.g. you could put `mirror_only = True` or `fetch=False` or something like that in your package file, and provide the fetch message you want with another property.

**Comment by adamjstewart** [comment]
What about `url = "file://pgi-compiler-16.3.tar.gz"`?

**Comment by tgamblin** [comment]
So, you can do that and that's actually supported.  If you *just* want to get local fetching working for your site, you could make your own package repo, with a local pgi-compiler package that has a locally valid `file:///` URL.

The disadvantage of that is that it will only succeed in fetching at your site, so it's probably not what you want in the mainline.  You could start by doing it the way you outlined above, and then we could work on the mirror stuff later if you want to get your PGI installation back into the mainline -- would that work?

**Comment by adamjstewart** [comment]
I'm just trying to think of ways to get around using a fake url. I would still require the user to set up a mirror. I am also setting `mirror_only = True`. But I feel like if I set the url to point to a fake local file, it would at least suggest to the user that they can't just install it like a normal package. Does that make sense, or am I just being silly?

**Comment by tgamblin** [comment]
No, that makes perfect sense.  You could make the URL a valid local one for ANL, and still use a mirror.  It will just be weird if the local URL fails for others.  I would like to find a better way to handle that for "mirror only" packages, but I don't have one right now.

**Comment by adamjstewart** [comment]
Yeah, but if I used the homepage as the url, it would also fail. This would just be an extra indicator to the user that Spack can't download it. I'll also mention this in the description. And theoretically, the user might be able to install it without a mirror as long as they are in the same directory as the downloaded file.

I'll do this for now. We can discuss this further once I submit a PR. I'll let you know if I run into any other problems with installing licensed software like PGI.

**Comment by tgamblin** [comment]
Sounds good to me.  I will think about whether a simple directive could make this easier and more obvious.

**Comment by tgamblin** [comment]
@lee218llnl is thinking of making Spack install intel compilers here, and I'm sure it would be nice to have it install PGI compilers here as well.  So maybe he has some feedback.

**Comment by adamjstewart** [comment]
Spack installed Intel compilers would be amazing! Taking a look at the Issues and Google Group, it's becoming clear that a lot of people (myself included) have been having trouble getting Intel working. At the very least, Spack could automatically set up icc.cfg, icpc.cfg, and ifort.cfg files for us. @lee218llnl: let me know if you would like any help with this!

**Comment by adamjstewart** [comment]
For the record, `url = "file://pgi-compiler-16.3.tar.gz"` does not work even if a file of the same name is in the current directory. Curl exits with mysterious error messages.

**Comment by eschnett** [comment]
@adamjstewart I believe that `file` urls are always absolute. You would write `file:///path/dir/wherever/pgi-compiler-16.3.tar.gz` instead. There are three slashes after the colon.

**Comment by adamjstewart** [comment]
Yeah, it just won't work for anyone else. I'll leave it as is for now and we can discuss adding further support for mirror_only files when I submit the PR.

**Comment by eschnett** [comment]
For a mirror url you can use a fake url. Spack will still look into the mirror for the files.

**Comment by lee218llnl** [comment]
I will look into this for the Intel compilers, but this will be tricky for several reasons. First, the Intel compiler come packaged in various product suites. The product is Parallel Studio and the various suites are 1. Composer Edition, 2. Professional Edition, and 3. Cluster Edition. The first is just the compiler and some libraries, the second adds Inspector, Advisor, and VTune, and the third adds MPI and the Intel Trace Analyzer. I guess they could all be separate packages in spack that provide the Intel compiler.

Another issue is that the main installation mechanism is to run an interactive install script. For our local installations, though, you can specify a install.ini file with the components and other install options. This would get messy in spack. I can look into how we package this up using RPMs in /opt and maybe find a better way to unpackage everything, but I think this will omit some of the symlinks that Intel adds.

Yet another issue is how to deal with local customizations, but I think Spack has the appropriate mechanisms to allow this.

**Comment by adamjstewart** [comment]
Yeah, PGI also has the same problem of having various suites. Luckily PGI makes it very simple to run their interactive install script silently. Check out #558 and let me know if you have any ideas for improvements. Not sure what to do about the suites/OS problem.

**Comment by adamjstewart** [comment]
This discussion seems to have stagnated, so I'm going to close it for now. If anyone wants to discuss better ways to install licensed software with Spack, we can reopen it. I think #558 is an adequate solution for the time being.
