### ISSUE TITLE
How Do You Pronounce "Spack"

### ISSUE THREAD

**Issue by JusticeForMikeBrown** [LLNL/spack#5569]
Is it "s" + "pack" or spack?

**Comment by scheibelp** [comment]
> Is it "s" + "pack" or spack?

The latter: as one word.

**Comment by scheibelp** [comment]
(I assumed that addressed it but feel free to reopen if there was a follow up question)

**Comment by JusticeForMikeBrown** [comment]
Thanks, @scheibelp!  A user though it would be the former, given it could stand for "software package," though I always though it was indeed latter.
