### ISSUE TITLE
Document Best Practices for Variant Naming

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#557]
See: https://github.com/LLNL/spack/issues/337

@tgamblin:
agree -- do you think the documentation is the right place for a best practices guide like this? Want to start a PR with an extra top-level doc section on variant naming?

**Comment by tgamblin** [comment]
Yes I do agree!  I can't start the PR but if you want to start a PR that adds this, it would be great.

**Comment by citibeth** [comment]
Feel free to assign it to me (or not).  I'm generating far more issues than I realistically have time to implement, prioritization is essential.  By entering it as an issue, I can remember that we decided it was a good idea.

**Comment by citibeth** [comment]
This already made it into the docs, I'm closing.
