### ISSUE TITLE
xSDK - same SHA-1 prefix error

### ISSUE THREAD

**Issue by AlexisPerry** [LLNL/spack#5574]
I get the following error when trying to install xSDK:

`==> Error: Specs superlu-dist@xsdk-0.2.0%gcc@5.4.0~int64 arch=linux-centos7-x86_64 ^cmake@3.7.1%gcc@5.4.0~doc+ncurses+openssl+ownlibs~qt arch=linux-centos7-x86_64 ^metis@5.1.0%gcc@5.4.0~debug~gdb~int64 patches=4991da938c1d3a1d3dea78e49bbebecba00273f98df2a656e38b83d55b281da1 +real64+shared arch=linux-centos7-x86_64 ^netlib-lapack@system%gcc@5.4.0~debug~external-blas+lapacke+shared arch=linux-centos7-x86_64 ^openmpi@1.10.3%gcc@5.4.0~cuda fabrics=verbs ~java schedulers= ~sqlite3~thread_multiple+vt arch=linux-centos7-x86_64 ^parmetis@4.0.3%gcc@5.4.0~debug~gdb patches=4f892531eb0a807eb1b82e683a416d3e35154a455274cf9b162fb02054d11a5b,50ed2081bc939269689789942067c58b3e522c269269a430d5d34c00edbc5870,704b84f7c7444d4372cb59cca6e1209df4ef3b033bc4ee3cf50f369bce972a9d +shared arch=linux-centos7-x86_64 and superlu-dist@xsdk-0.2.0%gcc@5.4.0~int64 arch=linux-centos7-x86_64 ^metis@5.1.0%gcc@5.4.0~debug~gdb~int64 patches=4991da938c1d3a1d3dea78e49bbebecba00273f98df2a656e38b83d55b281da1 +real64+shared arch=linux-centos7-x86_64 ^netlib-lapack@system%gcc@5.4.0~debug~external-blas+lapacke+shared arch=linux-centos7-x86_64 ^openmpi@1.10.3%gcc@5.4.0~cuda fabrics=verbs ~java schedulers= ~sqlite3~thread_multiple+vt arch=linux-centos7-x86_64 ^parmetis@4.0.3%gcc@5.4.0~debug~gdb patches=4f892531eb0a807eb1b82e683a416d3e35154a455274cf9b162fb02054d11a5b,50ed2081bc939269689789942067c58b3e522c269269a430d5d34c00edbc5870,704b84f7c7444d4372cb59cca6e1209df4ef3b033bc4ee3cf50f369bce972a9d +shared arch=linux-centos7-x86_64 have the same SHA-1 prefix!`

**Comment by davydden** [comment]
@tgamblin maybe add conretization of `xsdk` as a unit/regression test?

**Comment by scheibelp** [comment]
A couple similar reports have come up. In your case, are you installing new packages using already-installed dependencies the way #5565 is?

**Comment by AlexisPerry** [comment]
I am using my own compilers and my own python (external to Spack).  Other than that, I'm starting from a fresh clone of the spack repository with nothing installed.

**Comment by scheibelp** [comment]
Could you also add the full command line of `spack install`, and invoke it with the `-d` option: e.g. `spack -d install...`?

**Comment by junghans** [comment]
Fixed by #5580.
