### ISSUE TITLE
sha collision errors, possibly introduced by new hashes for patches

### ISSUE THREAD

**Issue by baberlevi** [LLNL/spack#5578]
We have a couple students currently working for our team creating spack packages, and after the weekend started getting errors for packages that have a patch somewhere in the dependency chain.  Packages without patches involved don't seem to have a problem.

Errors end with:
`have the same SHA-1 prefix!`
I see two other issues opened today that look very similar: #5565 and #5574 

The issue was just reported to me a few minutes ago, so I haven't dug in deeply yet, but I suspect this was a bug introduced by https://github.com/LLNL/spack/commit/4f8c7d57eb3839ea866a9fbfb55f9a44af99d6c0.

A quick guess is that the new patch hash prefixes are colliding with the hashes for existing packages.

**Comment by scheibelp** [comment]
In your case, are you installing new packages using already-installed dependencies the way #5565 is?

**Comment by baberlevi** [comment]
Yes, that does seem to be what's going on.

**Comment by becker33** [comment]
I am closing this as fixed. Reopen if the problem persists.

**Comment by scheibelp** [comment]
I think given the update at https://github.com/LLNL/spack/issues/5578#issuecomment-333724759 this is not yet resolved but is an instance of #5565, so it should be resolved by #5580
