### ISSUE TITLE
New patch deps: AttributeError: 'str' object has no attribute 'parent'

### ISSUE THREAD

**Issue by junghans** [LLNL/spack#5602]
Try to build #5459:
```
==> Error: AttributeError: 'str' object has no attribute 'parent'
AttributeError: AttributeError: 'str' object has no attribute 'parent'

/home/junghans/spack/lib/spack/spack/package.py:1042, in do_patch:
     9             has_patch_fun = hasattr(self, 'patch') and callable(self.patch)
     10
     11            # Get the patches from the spec (this is a shortcut for the MV-variant)
  >> 12            patches = self.spec.patches
     13
     14            # If there are no patches, note it.
     15            if not patches and not has_patch_fun:
```

**Comment by scheibelp** [comment]
Is this with the latest develop?

**Comment by scheibelp** [comment]
I'm trying to find a smaller reproducer than something which depends on llvm. Could you tell me which package this fails on (e.g. does it get all the way to flang)?

**Comment by scheibelp** [comment]
Oh and including the `spack install...` line would also be helpful (if it's anything different from `spack install flang`) and mention if externals are set up in packages.yaml

**Comment by junghans** [comment]
It fails when building `llvm` for `flang` running:
```
spack install -j2 -v flang
```
(no `packages.yaml`).

**Comment by scheibelp** [comment]
OK I think I've got a sense of the problem. I should have a PR shortly.

Thanks for the info!

**Comment by scheibelp** [comment]
Hi @junghans feel free to reopen if this problem persists for you in the latest develop

**Comment by junghans** [comment]
@scheibelp: I rebase #5459 on top of #5608, so let's see.
