### ISSUE TITLE
git should install a stable version by default, not a release candidate

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#564]
The git package installs 2.8.0-rc2 by default, instead of 2.7.3.

**Comment by tgamblin** [comment]
Does 2.8.0-rc2 break?  This was part of #560.  I'm not opposed to making 2.7.3 default or to having a policy to not make rc's default.

**Comment by citibeth** [comment]
According to the advisory I read, v2.8 is the only version that is free of known vulnerabilities.  Ideal would be for the upstream authors to release a fully functional version known to be bug-free.  But we cannot count on that.  Consider the consequences of a policy in which Spack intentionally provides, by default, versions known to have vulnerabilities.  For that reason, I felt that making an RC version the default was the lesser of two evils.

Or put another way, I would suggest the following policies, in which policy #1 takes precedence over #2:
 1. Never knowingly provide a version with a security vulnerability.
 2. Provide fully released versions, not RC versions.

**Comment by eschnett** [comment]
In this case I'm happy with 2.8.0-rc2. The git package already has a good set of comments (thank you!), another comment near the respective version statement would be good.

**Comment by tgamblin** [comment]
Would optional version descriptions that would appear in `spack info` be useful?
