### ISSUE TITLE
subversion build error

### ISSUE THREAD

**Issue by LewisChien** [LLNL/spack#5658]
brew upgrade subversion

==> make
==> make install
==> make tools
==> make install-tools
==> make swig-pl
==> make install-swig-pl
==> make javahl
==> make install-javahl
==> `make swig-rb EXTRA_SWIG_LDFLAGS=-L/usr/lib`
Last 15 lines from /Users/allen/Library/Logs/Homebrew/subversion/13.make:
2017-10-09 22:18:45 +0800

```
make
swig-rb
EXTRA_SWIG_LDFLAGS=-L/usr/lib
```

/bin/sh **`"/private/tmp/subversion-20171009-39687-o40106/subversion-1.9.7/libtool" --tag=CC`** --silent --mode=compile none  -I/usr/local/opt/sqlite/include -I/usr/local/opt/readline/include -I/usr/local/opt/openssl/include -F/usr/local/Frameworks -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.13.sdk  -DDARWIN -DSIGPROCMASK_SETS_THREAD_MASK -DDARWIN_10  -I/private/tmp/subversion-20171009-39687-o40106/subversion-1.9.7/subversion/bindings/swig/ruby/libsvn_swig_ruby -prefer-pic -c -o subversion/bindings/swig/ruby/svn_client.lo subversion/bindings/swig/ruby/svn_client.c
**`/private/tmp/subversion-20171009-39687-o40106/subversion-1.9.7/libtool: line 1760: none: command not found`**
make: *** [subversion/bindings/swig/ruby/svn_client.lo] Error 1

**Comment by scheibelp** [comment]
I do not see Spack being used here (for example `spack install subversion`). I'm going to close this. Feel free to reopen if I'm mistaken and this error occurs when you call a Spack command or if you installed a package with Spack and you want to use that when building subversion.
