### ISSUE TITLE
OCE fails due to missing xlocale.h

### ISSUE THREAD

**Issue by cpraveen** [LLNL/spack#5713]
While installing OCE-0.18.1 on OpenSUSE Tumbleweed, it fails

```
     337   In file included from /tmp/praveen/spack-stage/spack-stage-oi6nni/oce-OCE-0.18.1/src/Standard/Standard_CLocaleSentry.cxx:16:0:
  >> 338   /tmp/praveen/spack-stage/spack-stage-oi6nni/oce-OCE-0.18.1/src/Standard/Standard_CLocaleSentry.hxx:39:12: fatal error: xlocale.h: No such file or directory
     339      #include <xlocale.h>
     340               ^~~~~~~~~~~
     341   compilation terminated.
```

xlocale.h seems to be removed in glibc-2.26 which is what I have.

**Comment by davydden** [comment]
it's discussed upstream already https://github.com/tpaviot/oce/issues/675

There is patch there, do you want to give it a try and submit a PR to Spack with this patch?
All you need to do is to add that patch to the `oce` folder and then add
```
patch('my.patch', when='@0.18.1')
```

**Comment by cpraveen** [comment]
@davydden Thanks. I could compile with that patch.

**Comment by davydden** [comment]
@cpraveen can you please contribute a PR? The issue is still there for all other users...

**Comment by cpraveen** [comment]
Let me try. I put the patch into a file xlocale.patch and put it in
```
var/spack/repos/builtin/packages/oce/xlocale.patch
```
and added ```patch('xlocale.patch', when='@0.18.1')``` to ```var/spack/repos/builtin/packages/oce/package.py```. What else do I need to do ? When I compiled, it stopped at the patching stage and asked me to select a file

```
==> Created stage in /home/spack/var/spack/stage/oce-0.18.1-4f2pa5f25vyzv3ct3pxwfhnou63ar3g5
The text leading up to this was:
--------------------------
|--- src/Standard/Standard_CLocaleSentry.hxx.ORIG	2017-08-11 07:51:11.000000000 +0200
|+++ src/Standard/Standard_CLocaleSentry.hxx	2017-08-18 01:07:11.639206272 +0200
--------------------------
File to patch:
```
I had to take a manual action here. So what am I doing wrong ?

**Comment by davydden** [comment]
@cpraveen it probably has to do with patch level. try `patch('xlocale.patch', level=0, when='@0.18.1')` and have a look [this part of the Packaging guide](http://spack.readthedocs.io/en/latest/packaging_guide.html#patches)
