### ISSUE TITLE
module refresh gives Error: 'core_compilers' key not found in configuration file

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#5721]
```
$ spack module refresh
==> You are about to regenerate tcl, lmod, dotkit module files for:

-- darwin-highsierra-x86_64 / clang@9.0.0-apple -----------------
<blablabla>

==> Do you want to proceed? [y/n] y
==> Regenerating tcl module files
==> Warning: Could not write module file [/Users/davydden/spack/share/spack/modules/darwin-highsierra-x86_64/gettext-0.19.8.1-clang-9.0.0-apple-6gzxwhl]
==> Warning: 	--> global name 'prefix' is not defined <--
==> Error: 'core_compilers' key not found in configuration file
```
I have no idea what that is

**Comment by alalazo** [comment]
I need to check the defaults (and remove `lmod` from them), in the meanwhile you can:
```
$ spack module refresh -m tcl
```

**Comment by davydden** [comment]
thanks, @alalazo ! Limiting it to `tcl` worked as expected.

**Comment by alalazo** [comment]
Incidentally: the module system is also reporting a bug (due to a typo) in `builtin/gettext/package.py`.

**Comment by davydden** [comment]
> the module system is also reporting a bug (due to a typo) in builtin/gettext/package.py.

where's the typo?

**Comment by alalazo** [comment]
I'll fix it, don't worry. It seems a `prefix` is used somewhere instead of `self.prefix`. It comes in a warning because the failure of writing a single module shouldn't prevent other modules to be written.
