### ISSUE TITLE
Problems building OpenSSL with PGI

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#573]
Why doesn't anyone support non-GCC compilers? :sob: 

Trying to build NetCDF with PGI. NetCDF depends_on OpenSSL, which is crashing during the build. See [spack-build-original.txt](https://github.com/LLNL/spack/files/180034/spack-build-original.txt). Going off of the error messages, I tried adding:
```python
filter_file(r'-Wall', '', 'Makefile')
make("depend")
```
but no luck. See [spack-build-Wall.txt](https://github.com/LLNL/spack/files/180035/spack-build-Wall.txt).

Any thoughts? This seems to be a recurring problem. I am able to build OpenSSL outside of Spack, but I think that's only because they hard code it to use GCC. When I replace `CC=gcc` with `CC=pgcc` I get the same problems.

**Comment by eschnett** [comment]
Can't you do the same -- check whether the compiler is PGI, and if so, use another compiler instead? C-only code is binary compatible between compilers.

**Comment by adamjstewart** [comment]
Is there a way to do that automatically in Spack? Appending `^openssl%gcc` to `spack install netcdf` doesn't even seem to work.

**Comment by eschnett** [comment]
This used to work a while back; I used it to install Python with a different compiler. Maybe a recent change broke this?

**Comment by adamjstewart** [comment]
@mplegendre? @tgamblin? I think you were the last people to mess with dependency resolution.

**Comment by tgamblin** [comment]
That's a bug.  That must've broken with #120.  Sigh.  It should keep the compiler the user asked for through concretization.  @mplegendre: can you take a look at this if I do not get to it?  it looks like the `concretize.py` is ignoring the compiler constraint.

**Comment by adamjstewart** [comment]
I can confirm that #595 solves the issue that arose with #120. I'm going to close this PR for now. It may still be wise to add some logic that will allow us to mark packages as not-buildable on certain platforms or with specific compilers. But for now, I am content with adding `^openssl%gcc` to every package I build with PGI that depends on OpenSSL.

**Comment by adamjstewart** [comment]
Finally got around to submitting a [bug report](https://github.com/openssl/openssl/issues/916) with OpenSSL.
