### ISSUE TITLE
Spack install can't handle .tar files (not gzipped or bzipped)

### ISSUE THREAD

**Issue by ajkunen** [LLNL/spack#575]
If i setup a package to point at a URL like "file:///somepath/XXX.tar"  i get the error:

==> Installing mypackage
==> Error: Cannot deduce archive type in file:///somepath/mypackage-1.23.4.tar
==> Error: Installation process had nonzero exit code.

If i create a mypackage-1.23.4.tar.gz, and point the package URL at the gzipped version, it works.

However, I don't really have control over the source of this package, so I think that .tar files should work as well.

**Comment by adamjstewart** [comment]
Let me take a look at this. Can you give me an example package.py if you have one, or just the URL if you don't?

**Comment by tgamblin** [comment]
I think you could test this with a package like this:

```python
class Test(Package):
    """Test package."""
    homepage = 'http://www.example.com'
    version('test', 'abc123abc123', url='file:///Users/gamblin2/test.tar')

    def install(self, spec, prefix):
        touch('%s/dummyfile' % prefix)
```

And just make a dummy tar file in your home directory and adjust the path above.

**Comment by adamjstewart** [comment]
Done. #576

**Comment by tgamblin** [comment]
@ajkunen: can you verify and close?
