### ISSUE TITLE
spack does not handle multiple repos any more

### ISSUE THREAD

**Issue by luigi-calori** [LLNL/spack#5754]
I had recently updated develop. I was using an additional repo.
 Now this seem to prevent spack to work:

To reproduce:
cd /tmp
git clone https://github.com/LLNL/spack.git 
cd spack
source share/spack/setup-env.sh 
spack spec zlib
---------- WORK as expected ----------
spack repo create /tmp/goofy
spack repo add /tmp/goofy
spack spec zlib
==> Error: Invalid namespace for goofy repo: builtin

**Comment by luigi-calori** [comment]
I' ve used git bisect to find the problem ( beware I' m a newbie on bisect.... first time ) and seems the problem shows up after commit 
65b38764aedf56192568f5d49eb9a9c87257761b
That is the concretizer speedup
Am I doing something wrong?

**Comment by luigi-calori** [comment]
@tgamblin Sorry, It seems to me the problem persist: Am I alone in using multiple repos or am I doing something basically wrong? Thanks in advance

**Comment by luigi-calori** [comment]
By trying and testing I found that this problem goes away by changing fullname to name in line 1198 of spec.py
https://github.com/RemoteConnectionManager/spack/commit/adaa4781d2924eb64919bea247ce606883c83b39

As I' ve not the slightest idea of what I' m doing, hope that someone shade some light on this.
For now, continue testing as I need the repo functionality

In case still work, will submit a PR

**Comment by mwkrentel** [comment]
I was just about to report the same problem.
I get the same 'Invalid namespace' error.

Reverting to commit db149876 seems to solve the problem,
at least for the few examples I've tried so far.

**Comment by scheibelp** [comment]
I think I see the issue here, although I'm not sure how it was triggered only recently. I'll open a PR in the next hour or so.

**Comment by pramodskumbhar** [comment]
Same issue here!

**Comment by luigi-calori** [comment]
Confirm that #5787 fix the issue, Thanks a lot @scheibelp
