### ISSUE TITLE
consistent naming of packages

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#580]
looking at `spack list` most of the packages are named `name1-name2`. 
There are couple of exceptions: `SuiteSparse`, `SAMRAI`, `the_silver_searcher` and `R`. I guess `R` should really stay as an exception, but I don't see any reason why you shouldn't use `suite-sparse`, `samrai` and `the-silver-searcher` instead.

**Comment by tgamblin** [comment]
I'm not opposed to these changes -- 
@trws: do you have any objections to refactoring `the_awkwardly_named_silver_searcher`?

**Comment by mathstuf** [comment]
Well, in `the_silver_searcher`'s case, that *is* the upstream name. Changing it to use dash instead of underscore is weird. Where there's a space, dashes are probably better.

**Comment by trws** [comment]
I do not.  As @mathstuf notes, the upstream for it uses lower snake case for their repository and package, but that doesn't mean we have to.  The name itself has spaces in it, as the others do, so if hyphenation is the order of the day that's fine by me.

**Comment by alalazo** [comment]
If we go for this minor change, then we should add logic to `spack create`. I don't know the other packages, but if I remember well `SuiteSparse` was created by `spack create <url>`.

**Comment by trws** [comment]
I would love for that to happen @alalazo, but reliably detecting the caseing type to convert it is... well, it's not always straightforward.  There's a vim extension that attempts to do this to convert current case type to a selected one, but the logic has quite a lot of messy checks to make that work.  Having a simple check to convert snake case to hypenated makes sense to me, but detecting the various versions of camel case might not be worth it. (other than to print a warning to the user perhaps?)

**Comment by tgamblin** [comment]
@mathstuf: why's it weird?  I guess I just don't like typing `_` and generally prefer `-`.

**Comment by mathstuf** [comment]
I also prefer dashes, but if upstream uses underscores (rather than spaces), I'd follow that. What does Debian do?

**Comment by tgamblin** [comment]
I guess I don't see a strong reason to prefer the exact spelling used by upstream.  I dunno what Debian does, but homebrew uses all lowercase and dashes (I think that is where @davydden gets his preferences).

**Comment by trws** [comment]
Homebrew does lowercase hyphenated for everything except packages that use underscores upstream.  Both the silver and platinum searcher projects are examples of lower-snake cased homebrew packages.

**Comment by tgamblin** [comment]
Ok I kind of don't care that much about this anymore.  Do people think it's necessary to use consistent names, or are we getting into [Ralph Waldo Emerson](http://www.goodreads.com/quotes/353571-a-foolish-consistency-is-the-hobgoblin-of-little-minds-adored) territory here?

**Comment by trws** [comment]
Not that important.  Having it be consistent where there's no reason to be otherwise would be nice, but there's always going to be some package with a reason.

**Comment by tgamblin** [comment]
Ok closing -- if people *really* want consistent names (the names are pretty consistent generally) then please reopen.  I think any package manager is going to require some investigation of names, though.  MacPorts certainly isn't consistent, and I've never had a problem finding packages with it.
