### ISSUE TITLE
need to get at openmp library flag

### ISSUE THREAD

**Issue by olesenm** [LLNL/spack#5800]
I have a slightly odd situation. I'm trying to use the kahip package in my own package, but I am running into this slight difficulty. KaHIP is compiled with openmp (eg -fopenmp for gcc) and produces a static library. When I link my non-openmp libraries against kahip, the openmp symbols are not found. Presumably a dynamic kahip lib would carry the dependencies, but  I didn't seem to have much luck there either.

I've added a hack with `-lgomp` into my package to ensure that the corresponding library is linked in. This solves things in an ad hoc, non-portable manner.
* Is there a better way of getting at the library name (it might be different between gcc, icc, pgi, etc)?
* Should I just reuse the `openmp_flag` (ie, `-fopenmp`) for the link stage as well?
* Or do the compiler packages need to provide this information?

**Comment by davydden** [comment]
I would say you can either fix it in a single package via something like
```
if (self.spec.satisfies('%clang')):
  ...
elif (self.spec.satisfies('%gcc')):
  ...
```

or extend compiler classes (lib/spack/spack/compilers) to have

```
    @property
    def openmp_lib(self):
        return find_libraries(
            'libomp', root=..., shared=shared, recurse=True
        )
```

**Comment by olesenm** [comment]
Thank you for the information. For the moment it sound like I'll go with a workaround (don't want to touch compilers and risk destroying anything.)
