### ISSUE TITLE
openmpi-3.0.0: build fail on vulcan

### ISSUE THREAD

**Issue by ulrikeyang** [LLNL/spack#5804]
I tried to build the xsdk on Vulcan and it failed with the output I have copied at the end of this message
Apparently something called Big endian PPC is no longer supported
Any suggestion how I can get around this issue?
Thanks
Ulrike

==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> '/usr/bin/ibv_devices'
==> '/g/g20/ulrikey/Spacktest/spack/var/spack/stage/openmpi-3.0.0-rwo5iltlykplgcdt4ks2lculmf3opatx/openmpi-
3.0.0/configure' '--prefix=/g/g20/ulrikey/Spacktest/spack/opt/spack/bgq-cnk-ppc64/gcc-4.4.7/openmpi-3.0.0-r
wo5iltlykplgcdt4ks2lculmf3opatx' '--enable-shared' '--enable-static' '--enable-mpi-cxx' '--without-psm' '--
without-psm2' '--without-pmi' '--with-verbs' '--without-mxm' '--without-alps' '--without-lsf' '--without-tm
' '--without-slurm' '--without-sge' '--without-loadleveler' '--with-hwloc=/g/g20/ulrikey/Spacktest/spack/op
t/spack/bgq-cnk-ppc64/gcc-4.4.7/hwloc-1.11.7-gm3in23ktray3buu5wyoy2tfohknd4ad' '--disable-java' '--disable-
mpi-java' '--disable-mpi-thread-multiple' '--without-cuda'
configure: WARNING: unrecognized options: --without-loadleveler, --disable-mpi-thread-multiple
checking for perl... perl

============================================================================
== Configuring Open MPI
============================================================================

*** Startup tests
checking build system type... powerpc64-unknown-linux-gnu
checking host system type... powerpc64-unknown-linux-gnu
checking target system type... powerpc64-unknown-linux-gnu
configure: error: Big endian PPC is no longer supported.

**Comment by tgamblin** [comment]
@ulrikeyang: you should be able to get around this issue with the `packages.yaml` config for Mira here:

https://xsdk.info/release-0-2-0-alpha/

The paths may be different for some packages bt/w vulcan and Mira, but the `mpich` configuration should be the same (as it points to the system mpich).
