### ISSUE TITLE
flang installation fails on macOS 10.13 (High Sierra) with GCC 7.2

### ISSUE THREAD

**Issue by rouson** [LLNL/spack#5809]
I just submitted an [issue] on the flang repository regarding installing flang using spack with the above referenced OS/compiler combination.  I'm submitting this here in case it's an issue with spack.  If not, please feel free to close this.  The log file is attached as [spack-build.out.txt].

[spack-build.out.txt]: https://github.com/LLNL/spack/files/1396249/spack-build.out.txt

[issue]: https://github.com/flang-compiler/flang/issues/278

**Comment by junghans** [comment]
Duplicate of #4519

**Comment by rouson** [comment]
Thanks for the quick reply.  I'll switch to Linux.
