### ISSUE TITLE
Messages of the conflicts statements are not printed

### ISSUE THREAD

**Issue by skosukhin** [LLNL/spack#5821]
Messages that are passed to the `conflicts()` statements through 'msg' parameter are not printed when running `spack install`. They are printed when running `spack spec` though. Is it a bug or a feature?

**Comment by scheibelp** [comment]
I'd say we ought to do do it.

Even though this was reported before https://github.com/LLNL/spack/issues/6001 that is the same issue and has more discussion so I'm going to close this (feel free to reopen if you disagree).
