### ISSUE TITLE
m4 is failing to configure under Intel 17.0.2

### ISSUE THREAD

**Issue by jrood-nrel** [LLNL/spack#5836]
It seems due to https://github.com/LLNL/spack/commit/e76cfbbfd8707716a02f9849fbba962c20f0c37f#diff-5385006294b11a771037d296b7d79055 . If I comment the added lines out, it builds for me again.

Currently the error is:
```
configure: error: C compiler cannot create executables
```

**Comment by davydden** [comment]
@certik ping. That worked for you with `%intel@17.0.1`? It's unlikely that something changed so much between `17.0.1` and `17.0.2` to cause the difference. Maybe it's not only up to compiler version? I can't comment as I don't use `intel`.

**Comment by certik** [comment]
I don't know what's going on. I think there is no difference with regards to 17.0.1 and 17.0.2. The difference must come from the gcc version or how the gcc interacts with Intel.

What should be the correct fix?

**Comment by davydden** [comment]
> The difference must come from the gcc version or how the gcc interacts with Intel.

:+1:

@tgamblin @scheibelp ping

**Comment by jrood-nrel** [comment]
Underneath Intel I use GCC 5.2.0 on this machine. I haven't tried it yet on my other machine that has Intel 17 and GCC 4.9.2, but I will when I can.

**Comment by jrood-nrel** [comment]
Wait a second. Don't waste your time thinking about this. I had to modify my `compilers.yaml` due to some changes involving the dirty flag I didn't fully understand and it's having side effects I'm not expecting. This just built for me with no modification after I simplified my compiler configuration. I'm going to close this for now. Sorry!

**Comment by jrood-nrel** [comment]
For reference I think #5109 was having an effect on my compiler configuration. There was a few commits that dealt with the dirty flag, that initially caused me to add my compiler libraries to my compiler config, but I can't find all the commits to be more complete here.
