### ISSUE TITLE
ParaView +qt: Does not depend on qt?

### ISSUE THREAD

**Issue by ax3l** [LLNL/spack#5841]
When installing paraview with GUI, which depends on qt, spack does not allow to control the dependency to the paraview legacy frontend (qt4) via the GUI.

```bash
$ spack install paraview+qt ^qt@4.8.6
==> Error: paraview does not depend on qt
```

The combination is valid, but why does spack not honor the dependency properly to modify it?
```
    depends_on('qt', when='@5.3.0:+qt')
```
(As a work-around, I now just changed the in-package dependency to `qt@:4` to get the result I wanted.)

**Comment by davydden** [comment]
because you need to specify all parts of `when`, i.e. `$ spack spec -I paraview@5.4.1+qt ^qt@4.8.6`

**Comment by davydden** [comment]
it's essentially this http://spack.readthedocs.io/en/latest/known_issues.html#default-variants-are-not-taken-into-account-during-concretization

**Comment by davydden** [comment]
also see https://github.com/LLNL/spack/wiki/Issue-Disambiguation

**Comment by ax3l** [comment]
all right, thanks! so it's a know issue :)

the work-around `spack install paraview@5.4.1+qt ^qt@4.8.6` works :)
