### ISSUE TITLE
Use bash script to build

### ISSUE THREAD

**Issue by certik** [LLNL/spack#5858]
It would be nice to just spit out a bash script and use that to build the package, so that one can debug it easily.

Currently if I want to reproduce what spack is doing, is there any other way besides painfully copy & pasting the lines from the `spack-build.out` and loading the `spack-build.env` by hand? I found this hack to help most of the time:
```
$ cat spack-build.out | grep "==> '"
==> 'cmake' '/home/certik/repos/spack/var/spack/stage/amrex-17.06-fhekkyv7l74gtypc2q4yjxqh6z7bl56k/amrex' '-G' 'Unix Makefiles' '-DCMAKE_INSTALL_PREFIX:PATH=/home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/amrex-17.06-fhekkyv7l74gtypc2q4yjxqh6z7bl56k' '-DCMAKE_BUILD_TYPE:STRING=RelWithDebInfo' '-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON' '-DCMAKE_INSTALL_RPATH_USE_LINK_PATH:BOOL=FALSE' '-DCMAKE_INSTALL_RPATH:STRING=/home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/amrex-17.06-fhekkyv7l74gtypc2q4yjxqh6z7bl56k/lib:/home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/amrex-17.06-fhekkyv7l74gtypc2q4yjxqh6z7bl56k/lib64:/home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/openmpi-2.1.1-ywm4hkx6cyjqfxxwnsggbc3qaoi5ijax/lib:/home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/hwloc-1.11.7-2ymnl3e3czf6hemzel7xwogxttxkkstl/lib:/home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/libpciaccess-0.13.5-yf2577f2imu7jdf25doy6krwvov6wydi/lib:/home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/libxml2-2.9.4-j26m2sopxpelbb2vhdtbfdb7gdhczbl2/lib:/home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/xz-5.2.3-3k7sp3y2joy5gqakygyh26ma7fq4xw3t/lib:/home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/zlib-1.2.11-whz3v7mejgeegpoiblv4vgkgv7dtaiqg/lib' '-DCMAKE_PREFIX_PATH:STRING=/home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/openmpi-2.1.1-ywm4hkx6cyjqfxxwnsggbc3qaoi5ijax;/home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/cmake-3.9.4-4e7en6f27k3m4jiu7chakc72y4h4gvdn' '-DENABLE_POSITION_INDEPENDENT_CODE=ON' '-DBL_SPACEDIM:INT=3' '-DBL_PRECISION:STRING=DOUBLE' '-DENABLE_FMG=True' '-DENABLE_FBASELIB=True' '-DBL_DEBUG:INT=0' '-DBL_USE_PARTICLES:INT=0' '-DENABLE_MPI:INT=1' '-DENABLE_OpenMP:INT=0' '-DCMAKE_C_COMPILER=/home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/openmpi-2.1.1-ywm4hkx6cyjqfxxwnsggbc3qaoi5ijax/bin/mpicc' '-DCMAKE_CXX_COMPILER=/home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/openmpi-2.1.1-ywm4hkx6cyjqfxxwnsggbc3qaoi5ijax/bin/mpic++' '-DCMAKE_Fortran_COMPILER=/home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/intel-16.0.2/openmpi-2.1.1-ywm4hkx6cyjqfxxwnsggbc3qaoi5ijax/bin/mpif90' '-DENABLE_FORTRAN_MPI=True'
==> 'make' '-j32'
```
But even this is not complete --- for example spack loaded the intel compiler module behind the scene.

For debugging, it would greatly help if spack could just spit out the bash file itself, that I can just run to reproduce the error. Then I can debug it.

**Comment by alalazo** [comment]
For certain package types you can stop at some point of the whole installation process, and continue from there. For instance:
```console
$ spack configure <package>
```
will stop at the `cmake` stage of `CMakePackage` objects, at the `edit` stage of `MakefilePackage` objects etc. Similarly you have the commands `fetch`, `stage`, `build`.

Using a bash script to build is imo a major regression in the flexibility of what we can currently do. How would you deal with all the arbitrary python code that can go in a recipe? 

----

For what is worth, I debug the most annoying packages with a python debugger. For all the others I proceed manually as outlined above.

**Comment by certik** [comment]
So the argument is that Spack requires to use the Python language to build packages, that the Python can't be used to just declaratively tell Spack what to do, and so a bash script can't be generated. If so, how do you propose to fix this issue:

https://github.com/LLNL/spack/issues/1155

I thought the idea was to generate a bash script that Conda can then use to build the package.

**Comment by certik** [comment]
> Using a bash script to build is imo a major regression in the flexibility of what we can currently do. How would you deal with all the arbitrary python code that can go in a recipe?

I looked at spack packages. It seems that most of them can indeed by easily converted to simply generate a bash script. A typical example would be:

https://github.com/LLNL/spack/blob/328dc3d14029e576f38e920a4df116af89071dfe/var/spack/repos/builtin/packages/abinit/package.py

which if you look at it, the build script is not easy, but it's all declarative --- at the point when you do `spack spec`, spack knows all the information to generate the bash script. Most spack packages are in fact of this form.

There are packages that can't be easily converted, an example would be:

https://github.com/LLNL/spack/blob/328dc3d14029e576f38e920a4df116af89071dfe/var/spack/repos/builtin/packages/python/package.py

But there I will argue that spack should have a better support for the functionality that the `python/package.py` script needs, so that you can in fact declare things declaratively in a simple way and let spack handle the logic (e.g. this subroutine https://github.com/LLNL/spack/blob/328dc3d14029e576f38e920a4df116af89071dfe/var/spack/repos/builtin/packages/python/package.py#L227 seems like some kind of a hack, that spack itself should in my opinion by handling in some way). It can be done, since that's what we do in Hashdist. The question is, is this a "major regression", as you ask? I don't think so, but it depends on the details of course.

The thing that you gain is a much simpler debugging, better hash handling (see #5865), and you can then actually fix #1155 in a natural way.

**Comment by tgamblin** [comment]
@certik: So, I think this is cool, and I liked this aspect of `hashdist`, but I don't think it's really high on the priority list right now.  There would be a lot of details to work out, and I dunno if it's worth supporting because it reduces the flexibility Python gives you for a lot of packages.  I like the fact that a bash script is potentially reproducible w/o Spack itself, and I like the idea that you could generate a bash script and has it as a proxy for functional equivalence bt/w packages.

I'd argue that a lot of HPC folks know what they're doing scripting-wise in Python more than they do in bash.  And while most packages could compile to simple bash, we have some packages with fancier things, like @alalazo's spec interface for virtual packages, and the ability to provide some support for things like Ruby, Python, etc. *without* modifying Spack core.  That's what things like the Python hack you're pointing at are for, though I do agree that particular one could be simplified.  Anyway, it's something to think about but we've got other stuff to do at the moment, and I'm not sure we could completely capture everything in our Spack DSL.  I seem to remember Dag actually arguing to write hashdist packages in Python instead of bash, so is there even agreement among the hashdist folks about this 😄 ?

RE: hashing: we can hash the Python as well -- to do that we parse out all the directives and constraints, and hash *only* the build script part of the `package.py` file, then include that hash in the spec.  I have a prototype for that, which we'll likely use when we get around to #5865.  But the priorities right now are testing and better concretization solving.

> For debugging, it would greatly help if Spack could just spit out the bash file itself, that I can just run to reproduce the error. Then I can debug it.

While we can't spit out a bash file, you *can* get into a shell to test things out.  Do this:

```console
$ spack stage <spec>
```

**Comment by certik** [comment]
@tgamblin, I think all your objections are solvable:

> it reduces the flexibility Python gives you for a lot of packages.

You can keep doing Python coding for those few packages that require it. Those packages would not support a bash script, at least not initially.

> I'd argue that a lot of HPC folks know what they're doing scripting-wise in Python more than they do in bash. 
> ...
> I seem to remember Dag actually arguing to write hashdist packages in Python instead of bash

You can keep using the exact same Python "script" that spack already uses, but just use it declaratively, along the lines of #6067. Then spack just loads this class, examines the declarations (as it already does!), and can (optionally) spit out a bash file.

> the ability to provide some support for things like Ruby, Python, etc. without modifying Spack core. 

Hashdist does not have hardwired support for Ruby or Python either, yet you can use those. All you need is a general support for things that Ruby or Python requires, like setting up some paths, etc.

Most packages can be fully moved to this declarative way and one can do it step by step. And for packages that cannot be moved, because you really have to do some non-declarative Python coding, there I will argue that the Python coding should be abstracted and moved to the spack library itself from the package file --- but either way, those packages are in the vast minority. If the majority of packages use declarative way, then spack can (optionally) spit out a bash file for those, which is very useful and clean.

So it's a gradual process. For the very few packages, that can't be converted this way, I argue there is something more fundamental that would benefit from a more general solution (in spack itself) and just use this solution.


I think you are thinking of coding in bash. That's not what I am proposing at all. I am proposing to do what you already do e.g. for this package:

https://github.com/LLNL/spack/blob/328dc3d14029e576f38e920a4df116af89071dfe/var/spack/repos/builtin/packages/abinit/package.py

which together with #6067 will become fully declarative and as such spack *can* spit out a bash file, since it will know all the information without running any Python code.

Spack is already half way in this "functional" direction, e.g. by inventing the spack's mini-language which can be used with the "when" keyword. You could argue that it's better to "code in Python" than use this mini-language, but in practice it's better to use this mini-language, as things are shorter/cleaner and declarative. Anyway, I think I don't have to convince you on that particular point. ;)
