### ISSUE TITLE
spack does not pickup changes to package.py and the hash is not updated

### ISSUE THREAD

**Issue by certik** [LLNL/spack#5865]
Steps to reproduce:
```
$ spack install libelf
==> Installing libelf
==> Fetching http://www.mr511.de/software/libelf-0.8.13.tar.gz
######################################################################## 100.0%
==> Staging archive: /home/certik/repos/spack/var/spack/stage/libelf-0.8.13-vrhrruxrmpu3poh7zztvpybbttfgsxg7/libelf-0.8.13.tar.gz
==> Created stage in /home/certik/repos/spack/var/spack/stage/libelf-0.8.13-vrhrruxrmpu3poh7zztvpybbttfgsxg7
==> No patches needed for libelf
==> Building libelf [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Successfully installed libelf
  Fetch: 1.21s.  Build: 4.18s.  Total: 5.39s.
[+] /home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.2.0/libelf-0.8.13-vrhrruxrmpu3poh7zztvpybbttfgsxg7
```
Apply the following patch:
```diff
diff --git a/var/spack/repos/builtin/packages/libelf/package.py b/var/spack/repos/builtin/packages/libelf/package.py
index 56c4f19..0bf4fbe 100644
--- a/var/spack/repos/builtin/packages/libelf/package.py
+++ b/var/spack/repos/builtin/packages/libelf/package.py
@@ -46,4 +46,4 @@ class Libelf(AutotoolsPackage):
         return args

     def install(self, spec, prefix):
-        make('install', parallel=False)
+        make('installXXX', parallel=False)
```
then the changes are not picked up and the hash is not updated:
```
$ spack install libelf
==> libelf is already installed in /home/certik/repos/spack/opt/spack/linux-ubuntu16.04-x86_64/gcc-7.2.0/libelf-0.8.13-vrhrruxrmpu3poh7zztvpybbttfgsxg7
```
To make spack pickup the changes, one must do:
```
$ spack uninstall libelf
$ spack install libelf
==> Installing libelf
==> Using cached archive: /home/certik/repos/spack/var/spack/cache/libelf/libelf-0.8.13.tar.gz
==> Staging archive: /home/certik/repos/spack/var/spack/stage/libelf-0.8.13-vrhrruxrmpu3poh7zztvpybbttfgsxg7/libelf-0.8.13.tar.gz
==> Created stage in /home/certik/repos/spack/var/spack/stage/libelf-0.8.13-vrhrruxrmpu3poh7zztvpybbttfgsxg7
==> No patches needed for libelf
==> Building libelf [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Executing phase: 'install'
==> Error: ProcessError: Command exited with status 2:
    'make' 'installXXX'

1 error found in build log:
     [ ... ]
     371   making all in po
     372   make[1]: Entering directory '/home/certik/tmp/spack-stage/spack-stage-8pfgyO/libelf-0.8.13/po'
     373   make[1]: Nothing to be done for 'all'.
     374   make[1]: Leaving directory '/home/certik/tmp/spack-stage/spack-stage-8pfgyO/libelf-0.8.13/po'
     375   ==> Executing phase: 'install'
     376   ==> 'make' 'installXXX'
  >> 377   make: *** No rule to make target 'installXXX'.  Stop.

See build log for details:
  /home/certik/repos/spack/var/spack/stage/libelf-0.8.13-vrhrruxrmpu3poh7zztvpybbttfgsxg7/libelf-0.8.13/spack-build.out
```
Now the changes are picked up (and so the build fails), but the hash is still the old one... 

@tgamblin, in Hashdist, the hash contains the build script as well, so if you change it, the hash changes, which allows you to install several versions of the same package, just differing with how you build it.

**Comment by davydden** [comment]
this is expected behaviour, `packages.py` is not hashed at all, what is hashed is the concretized DAG with all the specifics (variants/compilers/versions/etc) for each node. Any changes in any of dependencies will change the hash of the root.

**Comment by certik** [comment]
I see, so if you change the `package.py`, you have to "expose" the change in some kind of variant, so that the change makes it into DAG and gets hashed.

But how do you handle the problem, that you fix a bug in some package, but then the subsequent packages should be rebuild, but they won't, since the hash does not change?

**Comment by davydden** [comment]
> But how do you handle the problem, that you fix a bug in some package, but then the subsequent packages should be rebuild, but they won't, since the hash does not change?

indeed, if a bug-fix was only inside the `package.py` and did not affect any variants/dependencies/etc, then Spack will not notice that the package has changed and needs to be re-isntalled.

But to be fair, I personally don't think it's a big deal. Often if there is a bug, then a package does not build at all for this combo of compiler/os/etc. Or it's missing dependency on some other package, which was picked up from system.

**Comment by tgamblin** [comment]
So, just FYI, the intent is to eventually hash `package.py` and expose this stuff.  The reason we don't right now is that nearly everyone's biggest complaint is the number of rebuilds Spack does, and we need better concretization to, by default, "prefer" already-installed versions of things.  Once we have that capability, expect the `package.py` to be hashed and the provenance to reflect that.

Of possible interest here might be #5476, where we recently started adding the `SHA256` of patches to the provenance.

**Comment by certik** [comment]
@tgamblin thanks for the explanation. @davydden regarding your point about comments and other changes that don't change the actual build --- that's related to #5858. If spack just generated a bash script, then you hash the bash script, and that way any changes to the source code that don't change the actual bash build script will not be picked up.
