### ISSUE TITLE
configuring libxcb fails: xproto not found

### ISSUE THREAD

**Issue by dlukes** [LLNL/spack#5869]
Configuring `libxcb` currently fails with the following error:

```
configure: error: Package requirements (pthread-stubs xau >= 0.99.2) were not met:

Package 'xproto', required by 'xau', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables NEEDED_CFLAGS
and NEEDED_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```

In other words, `xproto` is needed at the configure stage of `libxcb`, even though it's not a direct dependency, but a dependency of a dependency (`libxau`).

Leaving aside the philosophical issue whether a configure script checking for a dependency's dependency is something that should be done at all, from Spack's point of view, I think the cleanest solution is just to include `xproto` as a direct dependency of `libxcb`:

https://github.com/dlukes/spack/commit/ad88ba0c3006c512aedf6fb5f181c91585eeb97e

Which it effectively currently is anyway, because of the configure script :)

**Comment by luigi-calori** [comment]
I' ve tried to reproduce, as found somehow similar issue #5936
No success: fresh checkout seem to build fine

**Comment by dlukes** [comment]
Thanks for trying to reproduce! I uninstalled `libxcb` and its dependents, then reinstalled it, and everything went fine, to my surprise (this is the same spack install on the same machine).

Hard to say what happened originally -- my environment may have been dirty (today's attempt was obviously in a new shell)... At any rate, can't reproduce now, so closing :) I'll try and gather more details instead of a quick fix if the issue crops up again.
