### ISSUE TITLE
What Does Spack Reindex Do?

### ISSUE THREAD

**Issue by JusticeForMikeBrown** [LLNL/spack#5903]
After running "reindex" it seems that "spack find" returns packages that I previously uninstalled.  Is that expected?

**Comment by tgamblin** [comment]
How did you uninstall them?  With `spack uninstall`?

`spack reindex` rebuilds the package index (database) from what's in `$spack/opt`.  If some prior uninstall failed, it might still find the spec file for that package and include it in the DB.

**Comment by JusticeForMikeBrown** [comment]
Yeah, spack uninstall.  I manually uninstalled them again.  I'll close this since now I know how reindex works.  Thanks @tgamblin!

**Comment by tgamblin** [comment]
If you know how the directories weren’t removed by uninstall, let me know!
