### ISSUE TITLE
bdftopcf not building due to missing xproto dep

### ISSUE THREAD

**Issue by luigi-calori** [LLNL/spack#5936]
when building on CentOS cluster :
spack install bdftopcf

fail

  >> 80    checking for BDFTOPCF... configure: error: Package requirements (xfont) were not met:
     81    
     82    Package 'xproto', required by 'xfont', not found

**Comment by mathstuf** [comment]
Hmm, I'm seeing `xproto` in the dependency tree, so something is off with being able to find it.
