### ISSUE TITLE
Dependency Namespace isn't carried down a dependency chain

### ISSUE THREAD

**Issue by FrankD412** [LLNL/spack#5938]
When creating a new namespace containing custom repositories, if a repository within the new namespace depends on (in the literal Spack context of ```depends_on(x)```) a builtin package, spack throws the following error:

```
[fdinatal@machine]~/mynamespace% spack install mypackage
==> Error: Invalid namespace for mynamespace repo: builtin
```

This is after setting up the namespace such that spack is reporting the following:
```
[fdinatal@quartz1922]~/mynamespace% spack repo list
==> 2 package repositories.
mynamespace       ~/mynamespace
builtin                    spack/var/spack/repos/builtin
```

Commenting out the error check
```
if namespace and (namespace != self.namespace):
                raise InvalidNamespaceError(‘Invalid namespace for %s repo: %s’
                                                                        % (self.namespace, namespace))
```
using the ```spack edit –m repository``` command results in the following error (in this case my custom repository depends on ```mpi``` and ```boost```:
```
[fdinatal@machine]~/mynamespace% spack install conveyorlc
==> Error: Package libyogrt not found in repository [Repo 'mynamespace' at '~/mynamespace']
```

Adding my custom packages to the ```builtin`` directory fixes the issue after removing my custom namespace. It almost seems from the errors that the builtin namespace is not propagated down the dependency chain when a dependency is found to depend on something else. That's a best guess though.

**Comment by scheibelp** [comment]
This may be another instance of https://github.com/LLNL/spack/issues/5754 which is fixed by https://github.com/LLNL/spack/pull/5787. If it's easy, I'd be curious whether you could confirm if that works for you.

**Comment by FrankD412** [comment]
That fix appears to have solved the issue. So fix confirmed.

**Comment by scheibelp** [comment]
#5787 is now merged so this should be resolved

**Comment by tgamblin** [comment]
Thanks @scheibelp!
