### ISSUE TITLE
add extra flags to cc/cxx wrappers to suppress clang: warning: argument unused during compilation: '-L...'

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#596]
`clang` is picky about unused `-L` flags in compiler wrappers which may confuse configure systems of some packages, see this workaround PR for petsc https://github.com/LLNL/spack/pull/589 . 
In case of `clang` compiler, by default add `-Qunused-arguments` to wrappers of both `cc` and `cxx` to suppress those warnings.

**Comment by eschnett** [comment]
In this case the solution should be to avoid adding an `-L` flag if the linker is not called. The cc wrapper knows whether the linker is called, so there's no reason to first add the `-L` flag, and then add an argument to suppress the warning. Suppressing a warning will also suppress other warnings caused e.g. by typos or errors in package files.

**Comment by davydden** [comment]
Could the fact that we mix compilers on mac complicate things?
```
clang@7.0.2-apple:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
```

**Comment by eschnett** [comment]
No, that should not be relevant. The flags deciding whether to link or not are standardized.

**Comment by davydden** [comment]
fixed in https://github.com/LLNL/spack/pull/677
