### ISSUE TITLE
requesting cuda on OSX fails

### ISSUE THREAD

**Issue by cyrush** [LLNL/spack#5976]
If you have a cuda dependency on OSX spack seems to fetch linux cuda runtime. 

```
==> Installing cuda
==> Fetching https://developer.nvidia.com/compute/cuda/9.0/Prod/local_installers/cuda_9.0.176_384.81_linux-run
######################################################################## 100.0%
==> Already staged cuda-9.0.176-46cahgpcwtgwlktx6jkfhatrtsisdajd in /Users/harrison37/Work/alpine/spack/var/spack/stage/cuda-9.0.176-46cahgpcwtgwlktx6jkfhatrtsisdajd
==> No patches needed for cuda
==> Building cuda [Package]
==> Executing phase: 'install'
==> Error: ProcessError: Command exited with status 255:
    '/Users/harrison37/Work/alpine/spack/var/spack/stage/cuda-9.0.176-46cahgpcwtgwlktx6jkfhatrtsisdajd/cuda_9.0.176_384.81_linux-run' '--silent' '--verbose' '--override' '--toolkit' '--toolkitpath=/Users/harrison37/Work/alpine/spack/opt/spack/darwin-elcapitan-x86_64/clang-7.3.0-apple/cuda-9.0.176-46cahgpcwtgwlktx6jkfhatrtsisdajd'

1 error found in build log:
     [ ... ]
  >> 4     cat: /etc/issue: No such file or directory

```

Thats not good, but I am secretly hoping someone can share an example `packages.yml` file that demonstrates how to use a system install of cuda on OSX.

**Comment by tgamblin** [comment]
https://xsdk.info/release-0-2-0-alpha/

**Comment by cyrush** [comment]
@tgamblin awesome, thanks!

**Comment by davydden** [comment]
i guess we can close this as AFAIK CUDA downloads on macOS are `.dmg` files which Spack can't handle. So the only way is to install manually and set it up as an external package.

**Comment by cyrush** [comment]
Could we add an error message, so it's clear when someone tries to install cuda on OSX that the only viable path is external?

I'd be happy to add the message, are there any examples of this nature to follow?

**Comment by davydden** [comment]
> I'd be happy to add the message, are there any examples of this nature to follow?

```
conflicts('platform=darwin')
```
is probably what is needed.

**Comment by davydden** [comment]
~~is probably what is needed.~~
Now, that's wrong, it can still be used on darwin. You really need to throw an error during installation.

**Comment by tgamblin** [comment]
That would work for now.

I'd eventually like to figure out how we could automatically install DMGs... doesn't homebrew cask do that?  We'd need to add a `when` clause to `version()` first, to make this work.

**Comment by cyrush** [comment]
@tgamblin this case likely requires admin, so that may be an additional barrier

**Comment by tgamblin** [comment]
Is that different from how it is on Linux?  Are the drivers installed at the same time as the SDK on macs?

**Comment by cyrush** [comment]
not quite sure, i don't recall install process for OSX exactly. 
I am 99% sure thats the case for windows, but thats not relevant here.

**Comment by tgamblin** [comment]
Ok, well if that is the case, then auto-detection of externals is the way to go, and we can recommend that the user do the installation.  We could also just fire up the DMG and have them enter a password, but we'd want to prompt first.
