### ISSUE TITLE
intel-mkl recipe is broken for LANL HPC machines

### ISSUE THREAD

**Issue by KineticTheory** [LLNL/spack#6002]
**Problem Statement**

It looks like commit db657d938d38775e4364a6917cc78cb9cdb0b133 on Aug 16 changed the recipe for *intel-mkl* in a way that prevents the use *intel-mkl* on LANL HPC machines.  The current recipe wants to set `MKLROOT` to `self.prefix.compilers_and_libraries.linux.mkl.lib.intel64`, but that is an invalid path for LANL machines.  The correct path for us is `self.prefix.lib.intel64`.

**Background/Context**

On LANL HPC machines, *intel-mkl* is provided as an *external package* via the following entry in `packages.yaml`:

```yaml
packages:
  intel-mkl:
    version: [11.4.1]
    modules:
      intel-mkl@11.4.1: mkl/11.4.1
```

The modulefile `mkl/11.4.1` provides the following information:

```
conflict("mkl")
whatis("Intel Math Kernel Library 11.4.1 ")
whatis("Default settings for arch=intel64, 4-byte integers ")
setenv("MKLROOT","/usr/projects/hpcsoft/toss3/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017.1.132/linux/mkl")
prepend_path("LD_LIBRARY_PATH","/usr/projects/hpcsoft/toss3/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/mkl/lib/intel64")
prepend_path("LIBRARY_PATH","/usr/projects/hpcsoft/toss3/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/mkl/lib/intel64")
prepend_path("INCLUDE","/usr/projects/hpcsoft/toss3/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017.1.132/linux/mkl/include")
prepend_path("FPATH","/usr/projects/hpcsoft/toss3/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017.1.132/linux/mkl/include")
prepend_path("CPATH","/usr/projects/hpcsoft/toss3/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017.1.132/linux/mkl/include")
prepend_path("MANPATH","/usr/projects/hpcsoft/toss3/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017.1.132/linux/man/common")
```

It looks like `get_path_from_module` (found at `module_cmd.py`) extracts the *intel-mkl* prefix from `LD_LIBRARY_PATH` provided by the module file (i.e.: `/usr/projects/hpcsoft/toss3/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/mkl/`) and `intel-mkl/package.py` appends `compilers_and_libraries.linux.mkl.lib.intel64` to that path.  This is clearly the wrong behavior for LANL systems.  The following patch provides a work around for LANL HPC machines, but breaks the existing design.  

```diff
diff --git a/var/spack/repos/builtin/packages/intel-mkl/package.py b/var/spack/repos/builtin/packages/intel-mkl/package.py
index 9a3b9b9..185444a 100644
--- a/var/spack/repos/builtin/packages/intel-mkl/package.py
+++ b/var/spack/repos/builtin/packages/intel-mkl/package.py
@@ -98,7 +98,7 @@ class IntelMkl(IntelPackage):
                 omp_threading = ['libiomp5']
 
                 if sys.platform != 'darwin':
-                    omp_root = prefix.compilers_and_libraries.linux.lib.intel64
+                    omp_root = prefix.lib.intel64
                 else:
                     omp_root = prefix.lib
                 omp_libs = find_libraries(
@@ -114,7 +114,7 @@ class IntelMkl(IntelPackage):
         # TODO: TBB threading: ['libmkl_tbb_thread', 'libtbb', 'libstdc++']
 
         if sys.platform != 'darwin':
-            mkl_root = prefix.compilers_and_libraries.linux.mkl.lib.intel64
+            mkl_root = prefix.lib.intel64
         else:
             mkl_root = prefix.mkl.lib
 
@@ -166,7 +166,7 @@ class IntelMkl(IntelPackage):
 
         integer = 'ilp64' if '+ilp64' in self.spec else 'lp64'
         mkl_root = self.prefix.mkl.lib if sys.platform == 'darwin' else \
-            self.prefix.compilers_and_libraries.linux.mkl.lib.intel64
+            self.prefix.lib.intel64
 
         shared = True if '+shared' in self.spec else False
 
@@ -184,8 +184,8 @@ class IntelMkl(IntelPackage):
             mkl_lib = self.prefix.mkl.lib
             mkl_root = self.prefix.mkl
         else:
-            mkl_lib = self.prefix.compilers_and_libraries.linux.mkl.lib.intel64
-            mkl_root = self.prefix.compilers_and_libraries.linux.mkl
+            mkl_lib = self.prefix.lib.intel64
+            mkl_root = self.prefix
 
         spack_env.set('MKLROOT', mkl_root)
         spack_env.append_path('SPACK_COMPILER_EXTRA_RPATHS', mkl_lib)
```

**Next Steps**

I'm not sure how to resolve the different ways in which *intel-mkl* is installed.  Thoughts?

**Comment by davydden** [comment]
judging from 
```
setenv("MKLROOT","/usr/projects/hpcsoft/toss3/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017.1.132/linux/mkl")
```
you don't use a stand-alone `intel-mkl` as provided by Intel. I don't know whether there is a difference between `intel-cluster-studio` and `intel-parallel-studio`, but you probably should use `intel-parallel-studio` from Spack, which also provides `mkl`:
```
intel-parallel-studio+mkl provides mkl, scalapack, blas, lapack
```
Note that `mkl` is a virtual package which can be provided by different Intel packages in Spack.

p.s. I would argue that the current implementation of `intel-mkl` is correct because that's what you get if you download a stand-alone `intel-mkl` and that's what this package meant to be used with.

**Comment by mamelara** [comment]
I would disagree since intel-mkl package file also broke our install. I've only had experienced with our systems but it seems to me that compilers_and_libraries_{version} is a lot more common than what is currently implemented with package file.

**Comment by davydden** [comment]
> I would disagree since intel-mkl package file also broke our install.

can you be more specific? Are you sure you use a stand-alone `intel-mkl` package and not `intel-parallel-studio` or alike?

**Comment by davydden** [comment]
@KineticTheory @mamelara

> resolve the different ways in which intel-mkl is installed

that's handled by different packages which can provide `mkl`:
```
$ spack providers mkl
    intel-mkl  intel-parallel-studio+mkl
```
Those package have their own functions `def blas_libs(self):`, which can in principle look for `mkl` in different locations.

Another issue could be that you have to point spack to the actual prefix of the installed software, in this case it's probably `/usr/projects/hpcsoft/toss3/common/intel-clusterstudio/2017.1.024/`.

Probably the **ultimate problem** is in this 

> It looks like get_path_from_module (found at module_cmd.py) extracts the intel-mkl prefix
> LD_LIBRARY_PATH provided by the module file (i.e.: /usr/projects/hpcsoft/toss3/common/intel-clusterstudio/2017.1.024/compilers_and_libraries_2017/linux/mkl/) 

which accidentally was not a problem before. 
Try using `prefix`, i.e. 
```
  intel-mkl:
    version: [2018.0.128]
    paths:
      intel-mkl@2018.0.128 threads=none: /opt/intel/
    buildable: False
```

**Comment by mamelara** [comment]
But that doesn't work because I use the prefix. The common path is to have compilers_and_libraries_X.X.X and instead the pacakge.py of intel-mkl uses prefix.compilers_and_libraries.lib.intel64 which leads to: 

`/opt/intel/compilers_and_libraries/linux/mkl`
 instead of  
`/opt/intel/compilers_and_libraries_2018.0.128/linux/mkl`

**Comment by davydden** [comment]
> /opt/intel/compilers_and_libraries_2018.0.128/linux/mkl

sorry, i did not notice this part of the path `compilers_and_libraries_2018.0.128` . A few more questions to understand, is this directory structure default from Intel installer? If so, I guess it's from that Intel Cluster Sudio? Then `Spack` should simply have another Intel package, namely `intel-cluster-studio` with paths which are representative to this installer.

**Comment by davydden** [comment]
@lee218llnl since you know those Intel packages, I ping you here for the discussion on how to make this work.

**Comment by mamelara** [comment]
Yeah, I'm not exactly sure what we have. These are usually provided through Cray but judging from their documentation (or lack thereof) it looks like intel-parallel-studio. I'll ask someone here if they know better.

**Comment by davydden** [comment]
@tgamblin ping.

**Comment by mamelara** [comment]
That being said, I found another issue with intel-mkl when it involves static linking. Should I open another issue about that? Basically if you want to statically link intel-mkl you need to use the flags
-Wl,--start-group ... -Wl,--end-group since mkl has circular dependencies.

**Comment by davydden** [comment]
> Should I open another issue about that?

yes, for sure.

**Comment by KineticTheory** [comment]
> If so, I guess it's from that Intel Cluster Studio? Then Spack should simply have another Intel package, namely intel-cluster-studio with paths which are representative to this installer.

I like this solution, but I think additional input from other spack developers is required before we make a decision.

**Comment by davydden** [comment]
>  I think additional input from other spack developers is required before we make a decision.

absolutely!

@adamjstewart @alalazo ping.

**Comment by adamjstewart** [comment]
I hate Intel. There installation directories change with every release, making it next to impossible to make a single package that works for everyone. I chose directories that worked for me when I installed things with Spack. If you can find a more generic way of locating the correct directories that will work for everyone, that would obviously be better. But before I changed things, many of the directories (including MKL and MPI) were incorrect for my Spack-installed versions.

**Comment by alalazo** [comment]
> If so, I guess it's from that Intel Cluster Studio? Then Spack should simply have another Intel package, namely intel-cluster-studio with paths which are representative to this installer.

If the problem comes from the different layout of Cluster Studio, then another package seems the natural solution to me.

In the long term we probably need to improve the support for external packages in terms of "prefix" customization. I need to work this out on a couple of relevant use cases, but being able to specify what `prefix.lib` or `prefix.bin` or similar should expand to may help in some "pathological" cases.

**Comment by KineticTheory** [comment]
What is the consensus for moving forward on this issue?  Would you like me to attempt a PR for *intel-clusterstudio*?

**Comment by lee218llnl** [comment]
sorry to chime in late, but as far as I can tell, the standard for all Intel installers (parallel studio, cluster studio, and standalone mkl) is to install in the prefix.compilers_and_libraries.linux.mkl.lib.intel64. I can see this from the 2016, 2017, and 2018 versions. Whatever is being done at LANL and on Cray systems is customized. I can tell you that for our installation here at LLNL (which I control and do outside of Spack), I add symlinks to prefix.lib, but ultimately they point to the compiler_and_libraries... directory.

That said, I think what the Spack package is doing is technically correct and sites that have a customized external build of MKL may just have to customize their Spack builds to look in the modified location. The one compromise I might argue for is to have the Spack package create symlinks like I mentioned we do here at LLNL (into prefix.lib) and then you can set MKLROOT to that symlinked directory.

**Comment by KineticTheory** [comment]
@lee218llnl Thank you for the input.  I don't have access to the Intel installers so I didn't know what paths are *standard*.  I also don't know why intel-mkl is installed with the directory structure used at LANL, but I'm fine with maintaining my own intel-mkl package file to support our non-standard paths.
