### ISSUE TITLE
Spack install Python fails macOS Sierra

### ISSUE THREAD

**Issue by IanLee1521** [LLNL/spack#6010]
I think this is probably something minor, but I'm not sure...

I just tried to spack (v0.8.17-6787-gf9599c177) install python on a macOS computer (10.12.6) and got:

```bash
$ ./bin/spack install python
==> Error: No compilers found for operating system sierra and target x86_64.
If previous installations have succeeded, the operating system may have been updated.
Compilers are defined for the following operating systems and targets:
	elcapitan
Run 'spack compiler find' to add compilers.
```

Anyone else seeing similar issues?

**Comment by IanLee1521** [comment]
Or maybe it is me...?  from a fresh, clean clone of develop, I see the same type of error on a TOSS2 / RHEL6 host: 

```bash
$ ./bin/spack install python
==> Error: No compilers found for operating system rhel6 and target x86_64.
If previous installations have succeeded, the operating system may have been updated.
Compilers are defined for the following operating systems and targets:
	redhat6
Run 'spack compiler find' to add compilers.
```

**Comment by IanLee1521** [comment]
@lee218llnl helped me solve this by standing next to me and giving it the stink eye....

aka, we removed `~/.spack` and that then rebuild the compiler cache. Now to open a new ticket for the issue this led me to on mac...

**Comment by scheibelp** [comment]
Great! I'm going to close this then but feel free to reopen if this comes up again

**Comment by IanLee1521** [comment]
oops, thanks! Forgot to do that!

New issue is #6013 ...
