### ISSUE TITLE
So long and thanks for all the fish!

### ISSUE THREAD

**Issue by hartzell** [LLNL/spack#6021]
Borrowing from [Douglas Adams](https://en.wikipedia.org/wiki/Douglas_Adams)....

The gig for which I've been using Spack is ending this coming Monday.  I'll no longer have access to those systems or be (directly) involved in solving their problems.  Hopefully they'll continue with it and be able to contribute to the public project.

I'm not sure what's next for me and/or whether Spack will be applicable.  Either way, I might try to peel off a project or two to practice my Python.

But, I probably won't be following the project as closely as I have been so I wanted to give folks a heads up.

I **REALLY** appreciate all of the help all y'all have given me since I stumbled in the front door.

**Comment by hartzell** [comment]
ps.  If I broke something and you don't want to let me off the hook (or, if you want that beer that I owe you, or ...), you can reach me at [`hartzell@alerce.com`](mailto:hartzell@alerce.com).

**Comment by mamelara** [comment]
See you Space Cowboy

**Comment by tgamblin** [comment]
Oh no!  We'll certainly miss you @hartzell!  But feel free to come back to Spack any time -- you're always welcome.  We'll try to get all your PRs merged, too!

If you feel so inclined, please feel free to direct whoever's working on your old Spack cluster here.  We'd he happy to help those folks out.
