### ISSUE TITLE
Not able to install SUNDIALS 2.7.0 after recent changes

### ISSUE THREAD

**Issue by juan42** [LLNL/spack#6074]
https://github.com/LLNL/spack/blob/b53adc90f71ed24bfa405a044b65abfafad71450/var/spack/repos/builtin/packages/sundials/package.py#L135

shouldn't this be
```
conflicts('+int64',         when='@:2.7.0')
```
?

**Comment by davydden** [comment]
No, it's correct as-is. 

@gardner48 had a note that

> only 64bit integers are supported before v3.0.0.

so you need to specify `+int64` which is `off` by default to build `sundials` prior to `3.0.0.`

Feel free to re-open if issue is not resolved.

**Comment by juan42** [comment]
This sounds off. If you compile SUNDIALS 2.7.0 with hypre support you have to build hypre with long long int as well. The config used by most packages which depend on SUNDIALS + hypre is just "int"

**Comment by davydden** [comment]
> The config used by most packages which depend on SUNDIALS + hypre is just "int"

but that's a different problem, is it? I am just saying that the `conflict` is right according to the information above.

**Comment by juan42** [comment]
Ok, but its not even possible to install using "spack install sundials@2.7.0"

**Comment by davydden** [comment]
> but its not even possible to install using "spack install sundials@2.7.0"

It is perfectly possible to get what you want. The reason is 

```
$ spack info sundials
...
int64 [off]                    True, False             Use 64bit integers for indices
...
```
so you need to explicitly enable `int64` via
```
$ spack install sundials@2.7.0+int64
```
or put this into your `~/.spack/packages.yaml`
```
packages:
  sundials:
    variants: +int64
```

Yes, it would be better if Spack could have default values dependent on version, but it's NOT the case right now.

**Comment by juan42** [comment]
Okay thanks for the heads up. This may be a bug in a third party package which uses this combination!

**Comment by gardner48** [comment]
@davydden Is there any discussion on adding version dependent defaults to Spack?

**Comment by davydden** [comment]
> Is there any discussion on adding version dependent defaults to Spack?

Not to my knowledge

**Comment by davydden** [comment]
> Not to my knowledge

Actually, now I recall that there was a discussion somewhere with @tgamblin about variants being dependent on version (not only the default values). That's useful if some variants appear only in newer versions. But i guess it's not a trivial thing to do. `dealii` and `trilinos` would certainly  benefit from that.
