### ISSUE TITLE
Spack-built SciPy calls Spack compiler wrapper

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#608]
Oh the joys of running Spack in production...

I just had a user report that he was having major problems running Spack-built Python. I took a look at his error message and found that it was trying to call the Spack compiler wrapper instead of the system gcc.

This problem can be recreated by installing python and py-scipy with a spack-built gcc.

Create a file containing:
```python
#!/usr/bin/env python

from scipy import weave

source = """
int main(void) {
    return 0;
}
"""

weave.inline(source, compiler='gcc')
```
When run from Spack-built Python, this program produces the error message:
```
Spack compiler must be run from spack!  Input SPACK_PREFIX was missing!
Spack compiler must be run from spack!  Input SPACK_PREFIX was missing!
Traceback (most recent call last):
  File "./test.py", line 11, in <module>
    weave.inline(source, compiler='gcc')
  File "/soft/spack/opt/spack/linux-x86_64/gcc-5.3.0/python-2.7.11-mbvirl2oruaqyp7kpdzz7lfxl6ciggif/lib/python2.7/site-packages/scipy/weave/inline_tools.py", line 366, in inline
    **kw)
  File "/soft/spack/opt/spack/linux-x86_64/gcc-5.3.0/python-2.7.11-mbvirl2oruaqyp7kpdzz7lfxl6ciggif/lib/python2.7/site-packages/scipy/weave/inline_tools.py", line 496, in compile_function
    verbose=verbose, **kw)
  File "/soft/spack/opt/spack/linux-x86_64/gcc-5.3.0/python-2.7.11-mbvirl2oruaqyp7kpdzz7lfxl6ciggif/lib/python2.7/site-packages/scipy/weave/ext_tools.py", line 373, in compile
    verbose=verbose, **kw)
  File "/soft/spack/opt/spack/linux-x86_64/gcc-5.3.0/python-2.7.11-mbvirl2oruaqyp7kpdzz7lfxl6ciggif/lib/python2.7/site-packages/scipy/weave/build_tools.py", line 279, in build_extension
    setup(name=module_name, ext_modules=[ext],verbose=verb)
  File "/soft/spack/opt/spack/linux-x86_64/gcc-5.3.0/python-2.7.11-mbvirl2oruaqyp7kpdzz7lfxl6ciggif/lib/python2.7/site-packages/numpy/distutils/core.py", line 169, in setup
    return old_setup(**new_attr)
  File "/soft/spack/opt/spack/linux-x86_64/gcc-5.3.0/python-2.7.11-mbvirl2oruaqyp7kpdzz7lfxl6ciggif/lib/python2.7/distutils/core.py", line 166, in setup
    raise SystemExit, "error: " + str(msg)
scipy.weave.build_tools.CompileError: error: Command "/blues/gpfs/home/software/spack/lib/spack/env/gcc/g++ -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -I/soft/spack/opt/spack/linux-x86_64/gcc-5.3.0/python-2.7.11-mbvirl2oruaqyp7kpdzz7lfxl6ciggif/lib/python2.7/site-packages/scipy/weave -I/soft/spack/opt/spack/linux-x86_64/gcc-5.3.0/python-2.7.11-mbvirl2oruaqyp7kpdzz7lfxl6ciggif/lib/python2.7/site-packages/scipy/weave/scxx -I/soft/spack/opt/spack/linux-x86_64/gcc-5.3.0/python-2.7.11-mbvirl2oruaqyp7kpdzz7lfxl6ciggif/lib/python2.7/site-packages/numpy/core/include -I/soft/spack/opt/spack/linux-x86_64/gcc-5.3.0/python-2.7.11-mbvirl2oruaqyp7kpdzz7lfxl6ciggif/include/python2.7 -c /home/ajstewart/.cache/scipy/python27_compiled/sc_ee5a589152be75eefeb2b60fb2235ec52.cpp -o /tmp/scipy-ajstewart-svKPMx/python27_intermediate/compiler_8dcbb390c5f7d775e8e51e82751bb966/home/ajstewart/.cache/scipy/python27_compiled/sc_ee5a589152be75eefeb2b60fb2235ec52.o" failed with exit status 1
```
You'll notice that the last line is directly calling `lib/spack/env/gcc/g++`, causing the message `Spack compiler must be run from spack!  Input SPACK_PREFIX was missing!`. Note that gcc-5.3.0 and lib/spack/env/gcc are not in my PATH. The only thing built by Spack in my path is Python.

I'm currently trying to reinstall gcc, python, and py-scipy from scratch to see if this problem has been resolved since I first installed these packages. Can someone else try to recreate this in the meantime?

**Comment by tgamblin** [comment]
Isn't this fixed by @lee218llnl in #431?

**Comment by adamjstewart** [comment]
I was hoping you would say that. Let me try reinstalling just Python and see if that fixes the problem.

**Comment by adamjstewart** [comment]
```bash
$ spack install py-numpy ^python@2.7.11
==> Installing py-numpy
==> python is already installed in /blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-5.3.0/python-2.7.11-zowdyyxtbfjheerrhpvewuri34noptxf
==> netlib-lapack is already installed in /blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-5.3.0/netlib-lapack-3.6.0-mqxuixltish3qdax7ef66kgtqlpm6x3m
==> Installing py-nose
==> python is already installed in /blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-5.3.0/python-2.7.11-zowdyyxtbfjheerrhpvewuri34noptxf
==> Installing py-setuptools
==> python is already installed in /blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-5.3.0/python-2.7.11-zowdyyxtbfjheerrhpvewuri34noptxf
==> Already downloaded /blues/gpfs/home/software/spack/var/spack/stage/py-setuptools-19.2-du56khujkzkl7lcz3xzlvlgpeubqocob/setuptools-19.2.tar.gz
==> Already staged py-setuptools-19.2-du56khujkzkl7lcz3xzlvlgpeubqocob in /blues/gpfs/home/software/spack/var/spack/stage/py-setuptools-19.2-du56khujkzkl7lcz3xzlvlgpeubqocob
==> No patches needed for py-setuptools
==> Building py-setuptools
Traceback (most recent call last):
  File "/blues/gpfs/home/software/spack/lib/spack/spack/build_environment.py", line 367, in fork
    function()
  File "/blues/gpfs/home/software/spack/lib/spack/spack/package.py", line 910, in build_process
    self.install(self.spec, self.prefix)
  File "/blues/gpfs/home/software/spack/var/spack/repos/builtin/packages/py-setuptools/package.py", line 16, in install
    python('setup.py', 'install', '--prefix=%s' % prefix)
NameError: global name 'python' is not defined
==> Error: Installation process had nonzero exit code.
```
Well this is new. I don't think I had any problem installing Python modules before. Am I doing something wrong?

**Comment by alalazo** [comment]
@adamjstewart @tgamblin It seems that `python` still has a call to `modify_module`...

**Comment by adamjstewart** [comment]
@alalazo: is it `setup_dependent_package` or `setup_dependent_python_module`? #552 says:

> `modify_module` is renamed to `setup_dependent_python_module` to be consistent with the other methods, and to distinguish the python module scope from environment modules in the name.

**Comment by alalazo** [comment]
Check below There's a gentlemen agreement on the name :smile:

**Comment by adamjstewart** [comment]
Ah, gotcha

**Comment by adamjstewart** [comment]
Once this successfully builds I'll submit a PR to fix it. I think the only remaining call was in `lib/spack/spack/modules.py`

**Comment by adamjstewart** [comment]
Hmm, still not working. Same error message. Any other suggestions?

**Comment by alalazo** [comment]
@adamjstewart Sorry no linux at hand. You have to give me a few mins. as I turn on a VM :smile:

**Comment by tgamblin** [comment]
gah!  sorry.  I apparently missed a spot.  Let me know if you want me to submit the fix, but it looks like you have it.

**Comment by adamjstewart** [comment]
@tgamblin: That may be a bug, but fixing it doesn't seem to solve this issue. Can you take a quick look?

**Comment by alalazo** [comment]
@tgamblin I am just waiting for a build of `py-nose` to finish on a fresh `spack` clone. If it finishes succesfully I'll submit a PR.

@adamjstewart Did you change the signature? `modify_module` had a different one...

**Comment by adamjstewart** [comment]
... What is a signature?

**Comment by alalazo** [comment]
@adamjstewart Just in case you missed it PR in #610

**Comment by adamjstewart** [comment]
@alalazo: I actually just left work for the day. I can test it tomorrow morning. Thanks for the quick response!

**Comment by tgamblin** [comment]
@adamjstewart: find in the commit above -- please verify

**Comment by adamjstewart** [comment]
@tgamblin: I'm trying to do a fresh install of Python but now I'm running into new problems. So far I ran:
```bash
cd /soft/spack/opt/spack/linux-x86_64/gcc-5.3.0
rm -rf py*
rm -rf netlib*
spack reindex
```
to uninstall everything, and ran:
```bash
spack install python
spack install py-numpy
```
Everything appears to have installed properly so far. But when I try:
```bash
spack install py-scipy
==> Error: Multiple providers found for 'lapack': ['netlib-lapack+shared', 'openblas@0.2.16%gcc@5.3.0=linux-x86_64']
```
This was already reported in #418. The workaround that previously worked was:
```bash
$ spack install py-scipy ^netlib-blas+fpic ^netlib-lapack+shared
```
but that produced [this spack-build.out](https://github.com/LLNL/spack/files/186352/spack-build.txt). It looks like it couldn't find any of my Blas/Lapack libraries. Any idea what's up?

**Comment by adamjstewart** [comment]
Also, why does py-numpy depend on `netlib-blas+fpic` and `netlib-lapack+shared`? The installation documentation just suggests any `blas` and `lapack`. Removing this constraint would solve a lot of annoyances such as #418.

**Comment by alalazo** [comment]
@adamjstewart #485 removes that particular constraint on `py-numpy`. I just did a fresh install with : 
```
spack install py-numpy+blas ^ python@2.7.11
```
and it worked correctly on my Ubuntu. I am not sure though if I should advise you on trying it in production, as it is not tested much and will maybe need some more work (in particular on supporting external blas)

**Comment by adamjstewart** [comment]
@alalazo: I just edited `py-numpy` to look like:
```python
variant('blas',   default=True)
variant('lapack', default=True)

extends('python')
depends_on('py-nose')
depends_on('blas',   when='+blas')
depends_on('lapack', when='+lapack')
```
and `py-numpy` and `py-scipy` build without any trouble. It installs with openblas, which is the default blas/lapack provider. Would you consider making this change in #485? Openblas doesn't have a shared variant, so I can imagine that it would cause problems if you tried to install it.

Since openblas worked and netlib-blas/netlib-lapack didn't, there may be a bug in their installations.

**Comment by tgamblin** [comment]
@alalazo I reinstated `preferred` so installing python should default to `2.7.11` again, too.

**Comment by adamjstewart** [comment]
@tgamblin: Yes, I noticed that. Works for me now.
