### ISSUE TITLE
Parmetis does not compile with newer version of gcc (on UNIX systems)

### ISSUE THREAD

**Issue by nrichart** [LLNL/spack#614]
The split of the `parmetis` package introduced a bug that appears with new version of gcc, we tested 4.8 and 5.3. With 4.4 it compiles.

The problem is with a missing link with libm, before the change this link is pulled by metis that was a cmake subdirectory. The target `metis` is explicitely linked with `m` in case of unix system. The `parmetis` target is then linked by transitivity.

No that `parmetis` is linked with an external `metis` library this transitivity does not exists anymore.

I see 3 solutions:
  - patch the `metis` cmake to export the target and use a find_package in `parmetis` to link correctly with `metis`
  - do a quick and dirty patch in `parmetis` to make it link with the same condition as `metis` on `libm`
  - fallback to the version of the package where `metis` is in `parmetis`

The last one is the less invasive and needs no patch on compilation system of the packages,
The first one would be the cleanest if we stay with split packages, but also the most invasive and thus the hardest to maintain.
The second one is as already mentioned a quick and dirty fix.

This raise another problem, depending on the compiler we need or not link with `libm` explicitly. I guess we should hope the build system of packages should handle it correclty. But for `metis` for example the condition is `if(UNIX)` this will most probably already fail with intel compilers so perhaps with others too.

**Comment by eschnett** [comment]
Is there a system where adding `-lm` to the link line would cause problems?

**Comment by nrichart** [comment]
Intel compilers complain because they automatically link with an internal one, so by adding `-lm` you can hid symbols

**Comment by davydden** [comment]
did this solve your isue https://github.com/LLNL/spack/pull/624 ?

**Comment by davydden** [comment]
> patch the metis cmake to export the target and use a find_package in parmetis to link correctly with metis
do a quick and dirty patch in parmetis to make it link with the same condition as metis on libm

either of these should be ok. Can you execute patches conditionally? If so, then that would be an easy solution for Intel compilers, which don't like linking with `-lm` explicitly.

**Comment by davydden** [comment]
or even better, take the approach of https://github.com/LLNL/spack/pull/619 and add extra flags only for non-intel compilers?

**Comment by alalazo** [comment]
As we are talking of parmetis, I see another potential problem with #585 : it seems that as of now the parmetis package uses headers for GKLIB that are **internal to the version of metis we disabled**, while **it links to potentially another version of metis**. I argue this from the line:
```
'-DGKLIB_PATH:PATH={metis_source}/GKlib'.format(metis_source=metis_source), # still need headers from METIS source, and they are not installed with METIS. shame...
```
Before parmetis shipped with its own internal metis to compile and link which ensured consistency. If we want to separate parmetis from metis (and I would go for it) we should do things properly and make sure to:
1. match consistent versions of the two libraries
2. modify metis to install everything that is needed by parmetis
As it is now the package is prone to break whenever a new version will come out.

**Comment by davydden** [comment]
@alalazo makes sense. I will have a look into this direction and see what Macports already do in terms of patches to make it properly : [metis](https://trac.macports.org/browser/trunk/dports/math/metis/files), [parmetis](https://trac.macports.org/browser/trunk/dports/math/parmetis/files)

**Comment by nrichart** [comment]
At a point why not keeping the packages in there vanilla states instead of patching them in all directions. The more we add patches on a packages the more there is work to maintain them.
And I still do not get what was the problem with the package `parmetis` at first appart from it was different than `homebrew`. Is this really a problem ? At the end the changes seams to bring more potential problem that there was in the beginning.

**Comment by davydden** [comment]
> And I still do not get what was the problem with the package parmetis at first appart from it was different than homebrew.

Mumps did not work.

**Comment by nrichart** [comment]
Couln't it be solved in the mumps package the linking problem ?
The particular case of metis and parmetis was the one I tested in installing multiple configuration of the variants for this package. And at least on RHEL6 with gcc 4.4 and 4.8 it was working.
