### ISSUE TITLE
Allow custom install base

### ISSUE THREAD

**Issue by hegner** [LLNL/spack#635]
Instead of installing packages in-source (in opt/spack/... ), it would be nice if spack would allow to specify a custom install base dir. 

This ticket is an outcome of the discussion on:
 https://groups.google.com/forum/#!topic/spack/RF_jbW8qY9I

**Comment by mathstuf** [comment]
What I do locally is make `opt` a symlink to another location. This will likely be part of getting `lib/spack/__init__.py` to be a configuration file rather than a module at some point.

**Comment by adamjstewart** [comment]
See the lengthy conversation in #568. It sounds like @mplegendre already has some kind of implementation of "views". Basically, it would involve installing packages in /opt/spack/... where they currently are, but creating a hierarchical directory of symlinks, as @mathstuf suggested. Then, in some configuration file, you could specify how you want your directory structure organized. Perhaps @tgamblin could comment more if you have any questions.

**Comment by hegner** [comment]
created PR #908 that makes the install directory a config option.
