### ISSUE TITLE
Document Common Compiler Setups

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#638]
Add information to the documentation.  Common setups that need documentation so far are:
1. GNU compilers
1. Intel compilers
1. PGI compilers
1. Mixed compilers (particularly Clang+GNU on Macintosh)

@adamjstewart:

> 
> Documenation issue:
> There currently isn't much documentation on setting up compilers. You may have noticed on GitHub and the Google Group that a lot of people are having problems getting the Intel compilers to work with Spack. There are dozens of suggested workaround, and I've been meaning to add documentation for these. I would like an entire section on compilers, with specific instructions for each compiler. It could include instructions on installing PGI with Spack (see #558), workarounds for setting up Intel (see https://groups.google.com/forum/#!topic/spack/NxyNTAZyMQg), and instructions for setting up mixed compilers.
>

**Comment by adamjstewart** [comment]
I've been collecting notes on this. Here is what I have so far:

The Spack documentation is a little lacking on setting up compilers. In particular, the Intel compilers have been causing everyone headaches. A dedicated section on Compilers should be added to http://software.llnl.gov/spack/index.html

Here are some links to discussions on how to get certain compilers working:

**GCC**
Relatively problem free, unless you are on OS X

**Intel**
Barely works. Have to source environment variables. Need to add support for sourcing scripts when using compilers.
https://groups.google.com/forum/#!topic/spack/NxyNTAZyMQg
https://github.com/LLNL/spack/pull/451

**PGI**
Still some bugs to work out, but promising. Some packages like libpciaccess simply can't be built with PGI. I've been submitting bug reports in an attempt to fix this.
https://github.com/LLNL/spack/pull/558
https://github.com/LLNL/spack/pull/493
https://github.com/LLNL/spack/issues/518
https://github.com/LLNL/spack/issues/553
https://groups.google.com/forum/#!topic/spack/7xmKGBZ-jRg

**NAG**
A good example of the steps for adding support for a brand new compiler. Still need to add module every time for license environment variable.
https://github.com/LLNL/spack/pull/350
https://groups.google.com/forum/#!topic/spack/PWI2ntNUxm0
https://groups.google.com/forum/#!topic/spack/_oOT-ceoxIM

**Comment by citibeth** [comment]
See #846 for information on clang + gfortran on Mac.

**Comment by citibeth** [comment]
@adamjstewart, are these notes still relevant?  Or have --dirty and module-loaded compiler support fixed most of them?

@davydden I added the text below to the docs for mixed toolchains, are there any changes you would suggest?

```
^^^^^^^^^^^^^^^^
Mixed Toolchains
^^^^^^^^^^^^^^^^

Modern compilers typically come with related compilers for C, C++ and
Fortran bundled together.  When possible, results are best if the same
compiler is used for all languages.

In some cases, this is not possible.  For example, starting with
Macintosh OS X El Capitan (10.11), many packages no longer build with
GCC, but XCode provies no Fortran compilers.  The user is therefore
forced to use a mixed toolchain: the XCode-provided Clang is used for
C/C++ code, but GNU ``gfortran`` is used for Fortran code.

One might also need to use mixed toolchains with Intel compilers:
Intel's C and Fortran compilers work well, but in the past its C++
compiler was not able to build some basic packages, such as ``boost``.

Follows are instructions on how to hack together hack together
``clang`` and ``gfortran`` on Macintosh OS X.  A similar approach
should work for other mixed toolchain needs.

#. Edit ``compilers.yaml``:

.. code-block:: yaml

    compilers:
      darwin-x86_64:
        clang@7.3.0-apple:
          cc: /usr/bin/clang
          cxx: /usr/bin/clang++
          f77: /path/to/bin/gfortran
          fc: /path/to/bin/gfortran

#. Create a symlink inside ``clang`` environement:

.. code-block:: console

    $ cd $SPACK_ROOT/lib/spack/env/clang
    $ ln -s ../cc gfortran


#. Patch ``clang`` compiler file:


.. code-block:: console

    $ diff --git a/lib/spack/spack/compilers/clang.py b/lib/spack/spack/compilers/clang.py
    index e406d86..cf8fd01 100644
    --- a/lib/spack/spack/compilers/clang.py
    +++ b/lib/spack/spack/compilers/clang.py
    @@ -35,17 +35,17 @@ class Clang(Compiler):
         cxx_names = ['clang++']
     
         # Subclasses use possible names of Fortran 77 compiler
    -    f77_names = []
    +    f77_names = ['gfortran']
     
         # Subclasses use possible names of Fortran 90 compiler
    -    fc_names = []
    +    fc_names = ['gfortran']
     
         # Named wrapper links within spack.build_env_path
         link_paths = { 'cc'  : 'clang/clang',
                        'cxx' : 'clang/clang++',
                        # Use default wrappers for fortran, in case provided in compilers.yaml
    -                   'f77' : 'f77',
    -                   'fc'  : 'f90' }
    +                   'f77' : 'clang/gfortran',
    +                   'fc'  : 'clang/gfortran' }
     
         @classmethod
         def default_version(self, comp):
```

**Comment by davydden** [comment]
@citibeth :

> In some cases, this is not possible.  For example, starting with
Macintosh OS X El Capitan (10.11), many packages no longer build with
GCC, but XCode provies no Fortran compilers.  The user is therefore forced to use a mixed toolchain: the XCode-provided Clang is used for
C/C++ code, but GNU ``gfortran`` is used for Fortran code.

Are there indeed issues on `El Capitan` with `gcc`? I have been building with `gcc` both for c/c++ and fortran some time ago but currently prefer clang for c/c++ because it compiles faster and compiler errors are much better for heavyly templated code. 
Also Macports don't force users to compile with clang, so it must be working for them.


> One might also need to use mixed toolchains with Intel compilers:
Intel's C and Fortran compilers work well, but in the past its C++
compiler was not able to build some basic packages, such as ``boost``.

could be wrong here, but i think one has to use intel compilers with gcc, see `How the Intel Compiler Uses GCC` from https://software.intel.com/en-us/node/522750

> to hack together hack together

repetition


Otherwise LGTM.

**Comment by adamjstewart** [comment]
@davydden I've ran into a problems with GCC on macOS. Specifically, I can't compile Python with GCC. I'm sure there are other examples in the Issues.

@citibeth My notes are still mostly relevant. See below for updates.

### GCC

No updates.

### Intel

I would include some of the instructions from that Google Group post, as that is how I finally got Intel working. Loading modules and using `--dirty` should also work too, although I don't do it that way.

When I started using Intel, there were several important packages like MPI and NetCDF that I just couldn't build with Intel, but @alalazo has fixed all of them now I think. Thanks @alalazo!

The env var problem for finding the license has been mitigated by my licensed software support.

### PGI

Actually had fewer problems with PGI than I did with Intel. It worked out of the box and had no env var problems.

One gotcha that I still haven't fixed is #518. Older PGI compilers come with pgf77 and pgf90 but no pgfortran. At some point, they caught onto the GCC bandwagon and created a combined pgfortran compiler, but kept the old compilers for backwards compatibility. In Spack, we detect F77 as pgf77 or pgfortran and FC as pgf90 or pgfortran. Right now, order is not important, so if it detects pgf77 before pgfortran, it will choose that instead. The only problem I've run into is that HDF4 can't be built with pgf77, it needs to be built with pgfortran. Until #518 is fixed, you might want to mention that they should check their compilers.yaml and replace pgf77 and pgf90 with pgfortran.

As far as installation problems, libpciaccess and openssl still cannot be built with PGI. Now that I think about it, I should probably raise a warning when someone tries to install these packages with PGI...

The env var problem for finding the license has been mitigated by my licensed software support.

### NAG

Still a good example of how to add a new compiler to Spack. Unfortunately, I've never gotten NAG to work. It installs just fine out of Spack, but I've never gotten it to install anything with Spack. If someone could fix it, I would be eternally grateful. See #590 for details.

**Comment by citibeth** [comment]
> The env var problem for finding the license has been mitigated by my
> licensed software support.
>
Can you describe this further, or point to past text on it?  This sounds
like something that maybe should be documented.

The other advice you gave on PGI and NAG, I just copied verbatim into the
manual in getting_started.rst.  I don't have the time to write it up
tonight, but don't want to lose that information.  It would be great if
someone can expand on those two sections.

 -- Elizabeth

**Comment by adamjstewart** [comment]
The licensed software support is already documented:
http://spack.readthedocs.io/en/latest/packaging_guide.html#licensed-software

**Comment by citibeth** [comment]
OK got it.  I added the following section on licensed compilers:
```
^^^^^^^^^^^^^^^^^^
Licensed Compilers
^^^^^^^^^^^^^^^^^^

Some proprietary compilers require licensing to use.  If you need to
use a licensed compiler (eg, PGI), the process is similar to a mix of
build your own, plus modules:

#. Create a Spack package (if it doesn't exist already) to install
   your compiler.  Follow instructions on installing :ref:`license`.

#. Once the compiler is installed, you should be able to test it by
   using Spack to load the module it just created, and running simple
   builds (eg: ``cc helloWorld.c; ./a.out``)

#. Add the newly-installed compiler to ``compilers.yaml`` as shown
   above.
```
