### ISSUE TITLE
Generally Relocatable Packages via chrpath

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#641]
Have Spack Pad RPATHs so they can be later relocated via chrpath.  Thoughts:
1. Spack will need some formula of how long to make the padded RPATH, based on how many items are in it.
2. The user should be able to configure this.

See general discussion at:
https://github.com/LLNL/spack/issues/640

**Comment by alalazo** [comment]
@tgamblin Isn't this approach deprecated in favor of [patchelf](http://nixos.org/patchelf.html) ?

**Comment by citibeth** [comment]
Yes, `patchelf` is definitely better.  But I think this general idea is fraught with problems.  Paths get written into installs in all sorts of places OTHER than binaries.  #1013 takes these ideas further; would be interested in seeing how they pan out.
