### ISSUE TITLE
package.yaml Hierarchy

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#644]
A hierarchy of package.yaml files has been proposed; implement it:

See also "hierarchy of package.yaml"  in Discussion section at: https://github.com/LLNL/spack/wiki/Telcon%3A-2016-03-17

**Comment by adamjstewart** [comment]
#1309 implements at least one of these hierarchies.

**Comment by citibeth** [comment]
I think some thinking is still needed on this one.  A big obvious problem with #1309 is it modifies files inside the Spack git tree, thereby mixing real code changes with configuration files.  Sorry I didn't look at it earlier.  I think there are easier and more flexible ways to build hierarchies of configuration files.

**Comment by adamjstewart** [comment]
Can this be closed now? We have a [pretty complex hierarchy]( http://spack.readthedocs.io/en/latest/configuration.html#configuration-scopes) now. Or is there something you think is missing?

**Comment by alalazo** [comment]
@citibeth ping on @adamjstewart question

**Comment by citibeth** [comment]
We need to merge #2686, then we will have (most of) the machinery needed to make this work.  We might also want to add OS-specific scopes to the standard hierarhcy (#2700).
