### ISSUE TITLE
[BUG] Spurious Warning for System OpenSSL

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#647]
With PR #120 in place, I can now configure Spack to use the system's OpenSSL instead of trying to compile its own.  I did:

packages.yaml:
```
    openssl:
        paths:
            openssl@system: /usr
        buildable: False```
```
So far so good.  Now when I install something that uses OpenSSL, I get a spurious warning.  The good news is, everything seems to basically work. But the warning does look ominous (and I'm 99% sure it's totally spurious).

```
[spack]$ spack install py-scipy ^python@3.5.1 ^netlib-lapack+shared ^netlib-blas+fpic
==> Warning: This installation depends on an old version of OpenSSL, which may have known security issues. 
==> Warning: Consider updating to the latest version of this package.
==> Warning: More details at http://www.openssl.org
```

**Comment by mathstuf** [comment]
@alalazo Seems that `@system` should be handled specially in `url_for_version`?

**Comment by alalazo** [comment]
@mathstuf @citibeth  If we agree on the version tag `@system` (which is fine with me), then I think we should really handle it as a special case. Should I prepare a PR?

**Comment by citibeth** [comment]
@system seems like a fine convention to me, I will add that to the docs.
I'm generally against special cases.  But I haven't taken the time to
understand this issue, so I have no alternative suggestion.

One additional detail... builds don't usually need to be told where system
packages reside.  I put "/usr" in my packages.yaml file because (I assumed)
it wanted something there.  Now that the lib vs lib64 thing seems to be
getting straightened out, that will be a little more correct (but still
redundant).

Yes, a PR would be appreciated!

Thank you,
-- Elizabeth
