### ISSUE TITLE
[Feature Request] Improvements to spack uninstall

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#651]
The following improvements would be nice:

1. It should check for all errors in your command before uninstalling anything.  Eg: if I say ``spack uninstall openmpi foobar``, it should tell me that ``foobar`` is not a valid package name, and NOT uninstall ``openmpi``.

2. It should give a summary of what's going to happen  before it does the uninstalls; and (optionally) ask you interactively to confirm.

3. There should be a --recursive option that goes on an uninstall spree.

**Comment by adamjstewart** [comment]
:+1: for the --recursive option

**Comment by adamjstewart** [comment]
2 and 3 have been implemented, not sure about 1

**Comment by citibeth** [comment]
I believe it now asks for confirmation.  Uninstall has been much improved.
