### ISSUE TITLE
CMake Broken

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#652]
See PR #650 

For some reason, after the most recent merges, the symbol cmake is no longer working inside of package.py.  Replacing ``cmake(...)`` with ``which('cmake')(...)`` makes it work again.  I don't think this is really the solution.

I can see where ``m.cmake`` is getting set, so I don't know why it's not available by the time package.py is running.  In the meantime, I will use ``which('cmake')`` as needed to get stuff built.

**Comment by citibeth** [comment]
Until this issue is resolved, I'm collecting fixes in PR #664.  I imagine either that PR will be merged, or another fix to the problem will be applied (or has already been applied).  In the meantime, I think this Issue  can be closed.

**Comment by tgamblin** [comment]
See #620
