### ISSUE TITLE
compilers.yaml: gcc@version -> gnu@version

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#654]
currently compilers.yaml use the following naming
```
gcc@5.3.0:
      cc: null
      cxx: null
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
```
i think `gcc` compiler name is not fully correct as it groups C and Fortran compilers. 
It would be better to call it `gnu`, i.e.
```
gnu@5.3.0:
      cc: null
      cxx: null
      f77: /usr/local/bin/gfortran
      fc: /usr/local/bin/gfortran
```
Otherwise when there is a support for C/Fortran compilers mixing, one would have to write quite strange looking code like
```
if self.fortran_compiler.name == "gcc":
    # special case for GNU fortran
    bla-bla-bla
```

**Comment by alalazo** [comment]
> i think gcc compiler name is not fully correct as it groups C and Fortran compilers

GCC stands for "GNU Compiler Collection" - It's a fact anyhow that the C compiler in the collection is named as well `gcc`

**Comment by davydden** [comment]
@alalazo right.
