### ISSUE TITLE
Annoying stuff: colorizing breaks less

### ISSUE THREAD

**Issue by citibeth** [LLNL/spack#656]
Try the following to see the problem:
```
spack spec git | less
```

**Comment by tgamblin** [comment]
```
spack spec git | less -R
```

**Comment by tgamblin** [comment]
Something like `ls --color=auto` where there's better tty detection would probably be good, though.

**Comment by citibeth** [comment]
Thanks for the magic -R flag.  Now, why doesn't less turn that on by
default?

**Comment by citibeth** [comment]
I've added documentation to this effect in a PR: https://github.com/LLNL/spack/pull/663
Since less with colorized output is more useful than less without, I don't think it's worth the effort to have Spack de-colorize output when using less.  Therefore, I'm closing this Issue.
