### ISSUE TITLE
config parser not using the user scope

### ISSUE THREAD

**Issue by glennpj** [LLNL/spack#666]
There seems to be a problem with the config parser not using the user scope. I have the following in my modules configuration:

```
cat $HOME/.spack/modules.yaml

modules:
  enable: ['tcl']
```

Installs will still create dotfiles though because the user scope is not being used.
```
spack config get modules

modules:
  enable:
  - tcl
  - dotkit
```

shows the site scope although I expected the user scope to take precedence. The following should definitely show the user scope but still shows the site scope.

```
spack config --user get modules

modules:
  enable:
  - tcl
  - dotkit
```

**Comment by alalazo** [comment]
@glennpj The semantic for user configuration will be such that
```
modules:
  enable: ['tcl']
```
will **update** the site configuration (i.e. will add `tcl` if not already present), while : 
```
modules::
  enable: ['tcl']
```
(double '::') will **override** the site configuration (i.e. only `tcl` will be enabled)

**Comment by glennpj** [comment]
Okay; good to know. I found a mention of this in the docs here, once I knew what to look for:
http://software.llnl.gov/spack/spack.html?highlight=config#precedence

**Comment by tgamblin** [comment]
is this too subtle? I couldn't think of anything cleaner.

**Comment by glennpj** [comment]
It is subtle but I think if it gets documented in the main documentation section in addition to the API documentation section it should be fine.

**Comment by tgamblin** [comment]
Ok great -- glad people like it.  Without this configuring is either very tedious (entire file overrides site file) or it becomes very hard to disable specific site settings (merge only)
