### ISSUE TITLE
check Blas/Lapack symbols when requirements are known

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#675]
I quite like what PETSc guys are doing in their config system, namely checking for blas/lapack symbols for a given package, see for example [hypre](https://bitbucket.org/petsc/petsc/src/90564b43f6b05485163c147b464b5d6d28cde3ef/config/BuildSystem/config/packages/hypre.py?fileviewer=file-view-default#hypre.py-91:93).

I think it's a good feature to have, especially given the variety of Blas/Lapacks. Having that error before trying to build a package is much more descriptive and would save time.

**Comment by tgamblin** [comment]
This is really up to the packager, not Spack.  We could add a feature to make it easy but the packager still has to know what symbols are needed.

**Comment by tgamblin** [comment]
Adding a function that uses either `nm` or `otool` to search a library seems like all you'd really need.

**Comment by davydden** [comment]
sure, ideally the package would know and check. But if it does not once could check it with `nm` or `otool`. 

In real life, however, I don't know in how many cases we would know exactly which symbols a given package needs. Perhaps this feature is not as useful as I initially thought.

**Comment by tgamblin** [comment]
If the packager knows the symbols, it's a decent sanity check at configure time, but I don't know how we'd do this generally.

**Comment by davydden** [comment]
i was not thinking about doing it generally. Rather, have a sanity check inside a given package **iff** we know what symbols are needed to compile it, like the case with Hypre above.

**Comment by tgamblin** [comment]
Sure.  If you want to implement a function that does this, e.g. with `nm` or `otool`, I think it makes sense to allow them to do that.

**Comment by davydden** [comment]
i am closing this for now as it is not a critical feature.
