### ISSUE TITLE
building gdal via libtool

### ISSUE THREAD

**Issue by sixy6e** [LLNL/spack#679]
Building GDAL with spack fails unless the "--without-libtool" switch is set during configure.

Maybe related to #254 

`/bin/bash -pthread -shared -L/home/sixy/opt/spack/opt/spack/linux-x86_64/gcc-4.9.2/openssl-1.0.2g-6hycjtiiaqog4nptvrea2prziubttutr/lib -L/home/sixy/opt/spack/opt/spack/linux-x86_64/gcc-4.9.2/bzip2-1.0.6-c5tfobtnfsqtn7qi3vv26njdisxlomh3/lib -L/home/sixy/opt/spack/opt/spack/linux-x86_64/gcc-4.9.2/readline-6.3-x7lp7h466jt3t7sbpgxcd7xrwj4tu3pi/lib -L/home/sixy/opt/spack/opt/spack/linux-x86_64/gcc-4.9.2/ncurses-6.0-ahkfye5u2g5ivubnstskk5au37lbnfuf/lib -L/home/sixy/opt/spack/opt/spack/linux-x86_64/gcc-4.9.2/sqlite-3.8.5-ezw3lfkkg3kpbudc4nmiccl3hfozqhc6/lib -L/home/sixy/opt/spack/opt/spack/linux-x86_64/gcc-4.9.2/zlib-1.2.8-o6fa4gxlqdizqgxhepxqz3pca5abxqau/lib build/temp.linux-x86_64-2.7/extensions/gdal_wrap.o -L../../.libs -L../../ -L/home/sixy/opt/spack/opt/spack/linux-x86_64/gcc-4.9.2/python-2.7.11-3efy7qofkhvidrqqzqlaegial5ahq7ke/lib -L/tmp/sixy/spack-stage/spack-stage-i4yKhS/gdal-2.0.2/lib -lpython2.7 -lgdal -o build/lib.linux-x86_64-2.7/osgeo/_gdal.so
/bin/bash: -d: invalid option`

Building manually the same line has c++ in place of /bin/bash

Line 3701 of the spack build log, and line 3714 of the manual build log.

[gdal-spack-build.txt](https://github.com/LLNL/spack/files/192842/gdal-spack-build.txt)

[gdal-manual-make.txt](https://github.com/LLNL/spack/files/192843/gdal-manual-make.txt)

Setting "--without-libtool" builds gdal successfully.

**Comment by citibeth** [comment]
Is there any reason NOT to just add '--without-libtool' to package.py?

**Comment by sixy6e** [comment]
That's what I've done.  See pull request #632 

Just thought I'd post an issue regarding spack and libtool.

**Comment by mathstuf** [comment]
Closing since #632 has been merged.

**Comment by mathstuf** [comment]
Oh, don't have closing rights. This can be closed :) .
