### ISSUE TITLE
doxygen is missing dependencies

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#686]
subj, discovered by @Rombur . I guess these are `flex` and `bison`, @Rombur correct me if I am wrong.

**Comment by davydden** [comment]
I think adding `depends_on('flex')` and `depends_on('bison')` should solve the issue.

**Comment by Rombur** [comment]
Yes that's the two packages, I had to install.

**Comment by tgamblin** [comment]
Happy to merge a PR :smile:

**Comment by davydden** [comment]
i can't compile `flex` and have the same issue as reported here https://sourceforge.net/p/flex/mailman/message/32209632/

So i guess we need to keep this one open for now...

**Comment by tgamblin** [comment]
Reopening for flex issues.

**Comment by citibeth** [comment]
We should be able to merge a PR that depends_on('flex').  And then for systems that can't compile flex, set buildable=False in packages.yaml

**Comment by davydden** [comment]
i am closing this as `flex` appears to build fine on `osx` now, so i changed it in the doxygen package https://github.com/LLNL/spack/pull/959
