### ISSUE TITLE
arpack-ng is broken on OSX with native libtool

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#699]
subj, in https://github.com/LLNL/spack/commit/44b89474453bf80fd603eb5ea5b629b0d9dff123

```
==> Building arpack-ng
Traceback (most recent call last):
  File "/Users/davydden/spack/lib/spack/spack/build_environment.py", line 367, in fork
    function()
  File "/Users/davydden/spack/lib/spack/spack/package.py", line 910, in build_process
    self.install(self.spec, self.prefix)
  File "/Users/davydden/spack/var/spack/repos/builtin/packages/arpack-ng/package.py", line 54, in install
    which('libtoolize')()
TypeError: 'NoneType' object is not callable
==> Error: Installation process had nonzero exit code.
```
with
```
ackages:
  libtool:
    paths:
      libtool@2.4.6%clang@7.0.2-apple: <system> 
    buildable: False
```
as on Darwin where is no `libtoolize`.

**Comment by davydden** [comment]
this
```
$ git diff
diff --git a/var/spack/repos/builtin/packages/arpack-ng/package.py b/var/spack/repos/builtin/packages/arpack-ng/package.py
index 6b152f7..5476506 100644
--- a/var/spack/repos/builtin/packages/arpack-ng/package.py
+++ b/var/spack/repos/builtin/packages/arpack-ng/package.py
@@ -1,5 +1,5 @@
 from spack import *
-
+import sys

 class ArpackNg(Package):
     """
@@ -51,7 +51,8 @@ class ArpackNg(Package):
         # Apparently autotools are not bootstrapped
         # TODO: switch to use the CMake build in the next version
         # rather than bootstrapping.
-        which('libtoolize')()
+        if (sys.platform != 'darwin'):
+            which('libtoolize')()
         bootstrap = Executable('./bootstrap')

         options = ['--prefix=%s' % prefix]
```
is not a solution as make will complain 
```
error: you must have libtool 2.4.2 or a more recent version
Makefile.am:8: error: Libtool library used but 'LIBTOOL' is undefined
```
For now I disabled usage of Darwin's libtool

**Comment by tgamblin** [comment]
@davydden: I'm really keen to get the new CMake build going for this package, or to get the `arpack-ng` folks to properly bootstrap their autotools install.  Do you have a suggestion for how best to get this working cross-platform?

**Comment by tgamblin** [comment]
It also appears we need to have better ways to differentiate between `darwin`'s libtool and the GNU one.  I wonder if having those as separate packages is a good way to do this.  Or, make `libtool` a virtual dependency and allow packages to declare conflicts with the Darwin one somehow...

**Comment by tgamblin** [comment]
@davydden: when i build this on OS X, I get a bunch of errors like this:

`/var/folders/0s/q_y0zhfj6xdd5n7rn780zz6h001qr7/T//ccLojiWn.s:280:suffix or operands invalid for `movq'`.

Is this a `libtool` thing?  Or something else?

**Comment by davydden** [comment]
@tgamblin i would also prefer a CMake build, note that `CMakeList.txt` is already there https://github.com/opencollab/arpack-ng/blob/master/CMakeLists.txt . Can one download it somehow (as an extra resource for the package) and place it in the build folder?

w.r.t. darwin's libtool and GNU, i know that Macports install GNU with the prefix "g" to distinguish between the two, see https://trac.macports.org/browser/trunk/dports/devel/libtool/Portfile#L58 . Perhaps @eschnett has some comments on Darwin's libtool vs GNU libtool.

I have not seen those errors. Arpack-ng+mpi builds for me with GNU libtool and originally it was fine with Darwin's (before automake/autoconf dependencies). I am on El Capitan 10.11 with XCode 7.2.1.

**Comment by tgamblin** [comment]
Easier would be to just remove the 3.3 version and add a new version (3.4-rc1 or something), and have it build from git.  Would that work?

    version('3.4-rc1', git='<github URL>', commit='<current master commit hash>')

**Comment by tgamblin** [comment]
I'll play with the build on OS X a bit more later.

**Comment by davydden** [comment]
doing `3.4-rc1` should work.

**Comment by davydden** [comment]
just a few days ago there was a `3.4.0` release, which has cmake https://github.com/opencollab/arpack-ng/releases. i will try it out...

**Comment by davydden** [comment]
fixed in https://github.com/LLNL/spack/pull/1175
