### ISSUE TITLE
Boost library naming is potentially misleading for layout=tagged

### ISSUE THREAD

**Issue by scheibelp** [LLNL/spack#710]
See also: https://groups.google.com/forum/#!msg/spack/tWExKuaBqIA/QcyfiNfaDwAJ

~~Building with layout=tagged appends "-mt" to the names of libraries built with multithreading support. Consequently dependents which reference boost libraries like "-lboost_thread" may unknowingly reference the single-threaded libs (which lack that suffix).~~

@eschnett I'm curious if you are opposed to the following proposal (since you initially enabled building both the single and multi-threaded libraries and using layout=tagged):

@tgamblin's thought was that the multithreaded libraries could appear under a different prefix 

This would involve updating boost package.py to use layout=system, and to add a switch that chooses either single or multithreaded builds (but not both). A user who wants both could do two separate boost installs.

Edit (4/1) crossed out some faulty reasoning: Erik points out below that layout=tagged is standard; it seems tools like cmake are comfortable with the tagged layout and e.g. RHEL boost package uses tagged layout for boost libs.

**Comment by eschnett** [comment]
The `-mt` suffixes should not be "surprising" since they are part of the standard Boost install. I like building as many things in one go as possible to make things easier for the user; there's usually not much point in splitting things if users might want to use both at the same time.

Here, it doesn't seem likely that people would use both the single-threaded and the multi-threaded Boost libraries at the same time. I assume that the multi-threaded builds can act as drop-in replacement for the single-threaded ones? If so, I would not oppose to dropping the suffix, and using a `+multithreaded` variant to choose the desired build type.

**Comment by scheibelp** [comment]
> I assume that the multi-threaded builds can act as drop-in replacement for the single-threaded ones?

Yes (everything I've read so far suggests replacing multi-threaded with single-threaded is problematic but not the other way around). However to be clear different boost install directories will be created when the user specifies ~multithreaded and +multithreaded.

**Comment by eschnett** [comment]
What do you mean by "different boost install directories"? Is there anything beyond the obvious "if you install different variants of the same package, they will have different hashes, and you can use at most one at a time"?

**Comment by scheibelp** [comment]
> Is there anything beyond the obvious...

No. I brought this up because you asked about the multi-threaded libraries as a drop-in replacement and just wanted to be explicit that they would be kept separate in spack, so I'm not sure how useful that feature would be in the context of spack

**Comment by scheibelp** [comment]
Actually from reading through Cmake's findboost libraries (https://github.com/Kitware/CMake/blob/master/Modules/FindBoost.cmake) it seems like using the system layout might not be a good idea - it appears to assume a tagged layout. I can't say I'm sure about that so I'd have to look into it more (@mathstuf I'm curious if you know). 

Either way there isn't a problem with using the tagged layout as I originally thought, so @tgamblin I'm of a mind to close the issue

**Comment by mathstuf** [comment]
Here's a changelog message from the Fedora package:

```
- There's no physical difference between single-threaded and
  multi-threaded builds, except some libraries are only built in
  multi-threaded mode.  So build everything in multi-threaded mode,
  and ditch tagged layout, which we don't need anymore.
  https://bugzilla.redhat.com/show_bug.cgi?id=971956
```

I think the ABI might only change on some platforms (Windows?) based on multi-threading, but to be cross platform, they declare it everywhere. FWIW, I've had no issues with `FindBoost` and the non-tagged layout in Fedora (other issues, but not with tagged vs. non-tagged).

**Comment by davydden** [comment]
since https://github.com/LLNL/spack/pull/1955 is merged, i guess we can close this issue?
