### ISSUE TITLE
spack does not pick up updated compilers

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#713]
subj. When one updates XCode from 7.2.1. to 7.3. clang version changes accordingly. However, spack does not pick up those changes. Presumably because `compilers.yaml` is already created and available. If one removes the file and reruns `spack compilers`, then the new file with the correct version is generated.

**Comment by tgamblin** [comment]
If you just run `spack compiler add`, it will re-search.  Do you think `spack compilers` itself should redo the search?  We could also add a more explicit, clearer command for this, e.g. `spack compiler find`.

**Comment by davydden** [comment]
i think i was a bit confused by description:
```
    list       list available compilers
```
which I interpreted as **available in the system**, whereas it means those which have been previously found by spack and thereby available to spack.

I think that `spack compiler find` is indeed a better subcommand that `add`.

**Comment by davydden** [comment]
perhaps change to something along the lines
```
usage: spack compiler [-h] SUBCOMMAND

positional arguments:
  SUBCOMMAND
    find        Find compilers and add the results to the Spack configuration.
    remove (rm)
               Remove compiler by spec.
    list       list previously found compilers (default). When executed for the first time, find subcommand is invoked.
    info       Show compiler paths.

optional arguments:
  -h, --help   show this help message and exit
```

**Comment by tgamblin** [comment]
Seems like find could just be a synonym for `add`.  We could keep `add` as an alias.
