### ISSUE TITLE
Cannot use compiler spec with dependency

### ISSUE THREAD

**Issue by eschnett** [LLNL/spack#745]
This used to work, but now there is an error:
```
$ spack install $installopts petsc %gcc@5.3.0-spack +boost +hdf5 +mpi ^boost+mpi ^hdf5+mpi ^openblas ^openmpi ^python %clang-7.3.0-apple
==> Error: Identifier cannot contain '.'
```

The problem seems to be the dots in the compiler name `clang-7.3.0-apple`.

**Comment by tgamblin** [comment]
Sure you didn't mean clang@7.3.0-apple?

**Comment by eschnett** [comment]
`spec.py` contains this code:
```Python
    def check_identifier(self, id=None):
        """The only identifiers that can contain '.' are versions, but version
           ids are context-sensitive so we have to check on a case-by-case
           basis. Call this if we detect a version id where it shouldn't be.
        """
        if not id:
            id = self.token.value
        if '.' in id:
            self.last_token_error("Identifier cannot contain '.'")
```
The comment is wrong; compiler specs can also contain dots.

Also, the error message isn't very useful -- it should point to the particular command line argument by position; it should at least output the command line argument in question.

**Comment by eschnett** [comment]
I was confused.

**Comment by eschnett** [comment]
Yes, that's what I meant -- sorry.
