### ISSUE TITLE
develop: "spack mirror remove" does not work

### ISSUE THREAD

**Issue by fpruvost** [LLNL/spack#76]
Hi,

The "spack mirror remove" seems to be broken:

$ spack mirror add local_filesystem file:///home/pruvost/work/spack-mirrors/spack-mirror-2015-06-24/
$ spack mirror list
local_filesystem    file:///home/pruvost/work/spack-mirrors/spack-mirror-2015-06-24/
$ spack mirror remove local_filesystem
==> Error: Unknown scope None.  Valid options are site, user

**Comment by tgamblin** [comment]
This was fixed by e8e6368, part of #210
