### ISSUE TITLE
Spack directory naming structure

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#770]
Out of curiosity, why are all of the directories in Spack setup the way they are? Specifically, I noticed that etc, lib, opt, share, and var all have a single spack directory in them. Why not remove this spack directory and make all of the paths one depth shorter?

**Comment by alalazo** [comment]
@adamjstewart My guess : if the directories will be migrated to `/etc`, `/lib` etc. as part of a system installation you'll need a `spack` directory to better separate `spack` configuration files from those of other installed applications.

**Comment by citibeth** [comment]
I believe @tgamblin mentioned they are patterned after Homebrew or something like it.  I agree, it is evil for the average user.

**Comment by goxberry** [comment]
@citibeth As a long time Homebrew user and occasional contributor to Homebrew-affiliated repos (mostly [homebrew-science](https://github.com/Homebrew/homebrew-science)), I don't recognize the similarities to the Homebrew directory structure.

The directory tree looks inspired by the [Filesystem Hierarchy Standard](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard), with some quirks in `lib` to handle Python packaging/import rules, and the ability to integrate it into the root directory tree (per @alalazo's comment).
