### ISSUE TITLE
Problem with OpenBLAS and OpenMP

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#771]
I'm building a package (not in Spack yet) that depends on BLAS/LAPACK. When I build it with OpenBLAS and run `make test`, I see the following warning:
```
OpenBLAS Warning : Detect OpenMP Loop and this application may hang. Please rebuild the library with USE_OPENMP=1 option.
```
This warning message continuously prints to `spack-build.out` until it eventually fills up the filesystem. Has anyone ever ran into this before? Is it safe to add `USE_OPENMP=1` to OpenBLAS or will that cause problems for others?

**Comment by eschnett** [comment]
I assume that this is safe. I expect this to lead to problems if one uses a C compiler that does not support OpenMP. Older versions of Clang (< 3.8, i.e. the previous release) come to mind.

Making this conditional on `not (compiler==clang and clang-version<3.8)` should be mostly safe.

**Comment by tgamblin** [comment]
I think a variant defaulting to true should be good for this.

**Comment by adamjstewart** [comment]
It worked! I'll make a PR once I finish a few more tests here. Thanks!
