### ISSUE TITLE
GCC dependencies not detected properly

### ISSUE THREAD

**Issue by RalphTheBest** [LLNL/spack#778]
Hello,

I'm testing Spack for possible use in my organization and I found a little issue when trying to install gcc (v5.3.0). At first I just tried `spack install gcc@5.3.0`, but there was an error during the binutils installation. So I tried to install only binutils first and I received and error again (link to the stdout and the log from `spack install binutils`):

**Stdout**
https://drive.google.com/open?id=0B0eJDPNaAh6BLXNmQUt6eHBIQ0k
**Log**
https://drive.google.com/open?id=0B0eJDPNaAh6BWDQ2eFV4NnZDWVU

Looking at the binutils info, I decided to try to install it without the gold variant. For some unknown reason, it worked and spack was able to install binutils.
Apart from that (if someone knows why it worked the second time and not the first please tell me) I thought my problem was solved, but as said in other issues like #311, when I tried `spack install gcc@5.3.0` it didn't recognized my previous installation of binutils (due to the variant, I assume) and tried to install it again, which ended failing.

The real problem came when I tried to install gcc referring directly to my successful installation of binutils with the command `spack install gcc@5.3.0 ^binutils -gold` and the response was that gcc doesn't depend on binutils. After looking at the file of gcc, it does say that gcc depends on binutils, the only difference I can see is that it has a conditional `when` in the `depends_on()` clause.

I assume that spack shouldn't say that it doesn't depend, when actually it tries to install it during gcc installation. Can someone tell if this is actually an error or it's something that I'm doing wrong?

thanks for your help

**Comment by alalazo** [comment]
Having a fast look at `gcc` it seems that you can achieve what you want just specifying the variants of gcc:
```bash
spack install gcc~binutils~gold
```
Can you confirm this works?


> I assume that spack shouldn't say that it doesn't depend, when actually it tries to install it during gcc installation. Can someone tell if this is actually an error or it's something that I'm doing wrong?

Right now `spack` requires a bit of verbosity when dealing with variants and dependencies together. See #397 for a similar issue.

**Comment by RalphTheBest** [comment]
Unfortunately, It didn't work. Every time I try to run it, it gets stuck on _building gcc_ and doesn't really seem to be doing anything, but it doesn't stop and gives an error either. I let it run for 2 hours, hoping that maybe it was just being slow. But I don't really think that's the case, any other program takes like 2~3 min to install.

I wanted to give some more info to help finding the problem, but as I said, when it reaches the _building gcc_ step I don't get anything else from spack and I haven't been able to find any other helpful info about it in my system.

**Comment by tgamblin** [comment]
@RalphTheBest: `gcc` takes a very long time to build so it's likely that it is still building `gcc`.  If you use `spack install -v gcc~binutils~gold`, Spack will write the output directly to the terminal in addition to the build log, so you can see what's going on.

**Comment by tgamblin** [comment]
@RalphTheBest: @alalazo is right — try his invocation and I think the install should work for you.  The error you’re hitting is this:

```
/tmp/adrian/spack-stage/spack-stage-klGOCV/binutils-2.26/missing: 81: /tmp/adrian/spack-stage/spack-stage-klGOCV/binutils-2.26/missing: bison: not found
WARNING: 'bison' is missing on your system.
         You should only need it if you modified a '.y' file.
         You may want to install the GNU Bison package:
         <http://www.gnu.org/software/bison/>
make[4]: *** [yyscript.c]` 127
make[4]: *** Waiting for unfinished jobs....
```

It looks like when you build with gold, the binutils build really wants to use `bison`.  I submitted a PR for this (#779).  If you check out that PR and verify that `spack install gcc` just works for you, I can check it in.

**Comment by tgamblin** [comment]
@alalazo: we could probably make the `gcc` package a bit more concise by removing the `gold` variant to `gcc` and having `gcc` figure out whether to use `gold` based on whether `binutils` is built with gold.  Right now the information effectively appears in a `gcc` spec twice.

So right now you’d need:

	spack install gcc ~gold

Which *implies* that `binutils` should build w/o `gold`.  After this you would need:

	spack install gcc ^binutils ~gold

Which is actually more verbose but possibly less confusing.. thoughts?

**Comment by tgamblin** [comment]
@RalphTheBest: FYI, there is a bit more relevant discussion in #311 and #646 as well.

**Comment by adamjstewart** [comment]
@tgamblin: I'm also not a big fan of the gold variant. It doesn't really serve any purpose that I can see, as it doesn't change how the gcc package is built. It only changes how the binutils package is built.
```bash
spack install gcc +gold
```
is functionally equivalent to:
```bash
spack install gcc ^binutils+gold
```
Sure, it's shorter to type, but that argument could be made about passing variants up every package that depends on another.

**Comment by RalphTheBest** [comment]
You were right, using `spack install -v gcc~binutils~gold` worked,  it was only taking a really long time to install (3hours). I actually agree with @adamjstewart, I don't know if there is a reason for the duplicated variant, but it may be clearer if it's only included in the binutils package.

On the other hand @tgamblin , I tried your PR and it solved the problem. I was able to install gcc with just `spack install gcc`.
I think this solves all the points related exclusively to this issue, I think is better to follow the topic of the dependencies handling on the other issues mentioned before, since the discussion there is wider and seems more productive.

Thanks for your help.

**Comment by tgamblin** [comment]
@RalphTheBest: Great!  Glad to hear this worked.  If you forget to type `-v` in the future, note that you can just press `v` during an install to toggle between verbose and non-verbose modes.

I'll merge the `binutils` PR and will probably also refactor the `gcc` package so that it doesn't have a separate `gold` variant.

**Comment by trws** [comment]
As a note on gcc, I added the gold variant to pass the flag to build the gcc LTO plugin for gold.  That is not actually necessary anymore (in fact I'm not sure it ever was for versions we care about) so feel free to yank it.  The llvm variant of the same purpose is completely necessary however.

**Comment by tgamblin** [comment]
I merged the binutils changes (plus another dep on `m4`) in #779.

@trws: The deps get built before the package does, so gcc can check in `install()` whether `binutils` was built with `gold`.  Likewise for LLVM.  I'm suggesting just having the `llvm` and `gcc` packages build themselves with `gold` fanciness if they find themselves building with `binutils+gold`.  This simplifies the variants.

Is there a situation for `llvm` where you'd want to build `llvm~gold ^binutils+gold`?  Or can you even build `llvm+gold ^binutils~gold`?  If the answer to both of those is no, then I *think* it's sufficient to just let the `binutils` configuration determine how `gcc` and `llvm` are built.  Thoughts?

**Comment by trws** [comment]
That's a fair point, especially for gcc, but in llvm the actual option 
controls whether it builds support for LTO or not.  As of right now, 
gcc's LTO support does not depend on gold, but llvm's does.  It's 
entirely possible that LTO could become independent of gold in LLVM as 
well in the future.  For now, it should be sufficient, but we'll have to 
keep an eye on it.  Alternatively, we could give each an LTO variant 
that would be more explicit about what the flag is really doing.
