### ISSUE TITLE
Problems building HDF5 with Intel OpenMPI

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#784]
Is anyone else have trouble building HDF5 with Intel and OpenMPI? It works fine outside of Spack but with Spack it crashes during make. It also works with Spack with any other compiler or any other MPI library, just not Intel and OpenMPI. Here is the configuration I'm using:
```
spack install hdf5 %intel +szip -cxx +mpi ^openmpi+tm+psm
```
The Intel compiler is 16.0.1, OpenMPI 1.10.2, and HDF5 1.10.0 (although I think this problem still occurred with the previous HDF5 version).

When built outside of Spack, everything looks good:
```
checking for Fortran INTEGER KINDs... {1,2,4,8}
checking for Fortran REAL KINDs... {4,8,16}
checking for Fortran REALs maximum decimal precision... 34
checking sizeof of native KINDS...
checking for Fortran INTEGER KINDs... {1,2,4,8}
checking for Fortran REAL KINDs... {4,8,16}
checking for Fortran REALs maximum decimal precision... 34
checking sizeof of available INTEGER KINDs... {1,2,4,8}
checking sizeof of available REAL KINDs... {4,8,16}
checking if Fortran compiler supports intrinsic C_LONG_DOUBLE... yes
checking if Fortran C_LONG_DOUBLE is different from C_DOUBLE... yes
checking for Fortran interoperable KINDS with C... {4,8,16}
```
When built with Spack, I'm seeing the following warning message during configure:
```
Error
configure: WARNING: Failed to run program to determine available KINDs
checking sizeof of native KINDS... configure: WARNING: Fortran program fails to build or run!

Error
configure: WARNING: Failed to run program to determine available KINDs
checking sizeof of available INTEGER KINDs... {}
checking sizeof of available REAL KINDs... {}
checking if Fortran compiler supports intrinsic C_LONG_DOUBLE... yes
checking if Fortran C_LONG_DOUBLE is different from C_DOUBLE... yes
configure: WARNING:
           Fortran REAL(KIND=) is  Bytes, but no corresponding C float type exists of that size
                     !!! Fortran interfaces will not be generated for REAL(KIND=) !!!

checking for Fortran interoperable KINDS with C...
```
This eventually leads to errors in make:
```
H5match_types.c(155): error: expected an expression
    int IntKinds[] = H5_FORTRAN_INTEGER_KINDS;
                                             ^
```
Logs outside of Spack:
[config.log](https://github.com/LLNL/spack/files/219936/config.txt)
[soft-build.out](https://github.com/LLNL/spack/files/219938/soft-build.txt)

Logs when using Spack:
[config.log](https://github.com/LLNL/spack/files/219939/config.txt)
[spack-build.out](https://github.com/LLNL/spack/files/219940/spack-build.txt)

**Comment by adamjstewart** [comment]
Ping? @luigi-calori appears to be having this same problem as well.

**Comment by becker33** [comment]
On April 25th I successfully built hdf5 +mpi ^ openmpi. Here’s the full spec.


(cab690):spack$ bin/spack find -d hdf5 +mpi %intel@16

==> 1 installed packages.

-- chaos_5_x86_64_ib / intel@16.0.0 -----------------------------

    hdf5@1.8.15+cxx~debug+fortran+mpi+shared~szip~threadsafe

        ^openmpi@1.10.2~psm~tm~verbs

            ^hwloc@1.11.2

                ^libpciaccess@0.13.4

                    ^libtool@2.4.6

        ^zlib@1.2.8

How recently did your problem manifest in develop?

-Greg

**Comment by luigi-calori** [comment]
@adamjstewart  I have just compiled with my custom module installed intel cs-xe-2015.

I've loaded our custom installed module and set up a config file containing -Xlinker -rpath=.. in directives [here](https://github.com/RemoteConnectionManager/RCM_spack_deploy/blob/master/setup/intel/setup.sh)  then sourced spack setup-env in [here](https://github.com/RemoteConnectionManager/RCM_spack_deploy/blob/master/setup/setup_clean_intel.sh)

The install lines are:

spack install -v -j 30  hdf5%intel@15  +mpi ^ openmpi

and

spack install -v -j 30  parmetis%intel@15  ^ openmpi

Both apparently compiled ok, but not sure they are really ok:  I tried to run executables produced by parmetis and they exit in segmentation fault.

h5dump seems ok and do not bail out.

I' ll try to dig further but 
Is there a package available in spack that implements test or better benchmarks on mpi? 
I think it would help to have some test / benchmarks packages to assess spack products.

**Comment by adamjstewart** [comment]
Just a thought. Could the problem be that ifort ignores rpath, so the only solution would be to compile with LD_LIBRARY_PATH and other environment variables?

**Comment by alalazo** [comment]
@adamjstewart Just tried on a RHLE 6 cluster:
```
 spack install hdf5~cxx+mpi ^ openmpi+slurm+psm%intel
==> Installing hdf5
==> zlib is already installed in /home/culpo/github/spack-scitas/opt/spack/linux-x86_64/intel-16.0.2/zlib-1.2.8-wp6ab5ra3amenxbg4mbetf2k2ix5sz64
==> openmpi is already installed in /home/culpo/github/spack-scitas/opt/spack/linux-x86_64/intel-16.0.2/openmpi-1.10.2-qw4mkceu36ce4mbn4woujotclnzcvwsq
==> Trying to fetch from http://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.16/src/hdf5-1.8.16.tar.gz
######################################################################## 100,0%
==> Staging archive: /home/culpo/github/spack-scitas/var/spack/stage/hdf5-1.8.16-j4vwhvzsboleej5sb2ukdcnunmnz2ovm/hdf5-1.8.16.tar.gz
==> Created stage in /home/culpo/github/spack-scitas/var/spack/stage/hdf5-1.8.16-j4vwhvzsboleej5sb2ukdcnunmnz2ovm
==> No patches needed for hdf5
==> Building hdf5
==> Successfully installed hdf5
  Fetch: 25.04s.  Build: 5m 34.53s.  Total: 5m 59.57s.
[+] /home/culpo/github/spack-scitas/opt/spack/linux-x86_64/intel-16.0.2/hdf5-1.8.16-j4vwhvzsboleej5sb2ukdcnunmnz2ovm
```
I had to add a couple of custom configuration files (basically the ones we have already discussed in the mailing list), but `RPATH` seem to work for me on the executable:
```
$ module list
No Modulefiles Currently Loaded.
$ ldd /home/culpo/github/spack-scitas/opt/spack/linux-x86_64/intel-16.0.2/hdf5-1.8.16-j4vwhvzsboleej5sb2ukdcnunmnz2ovm/bin/h5diff
	linux-vdso.so.1 =>  (0x00007fff305ff000)
	libhdf5.so.10 => /home/culpo/github/spack-scitas/opt/spack/linux-x86_64/intel-16.0.2/hdf5-1.8.16-j4vwhvzsboleej5sb2ukdcnunmnz2ovm/lib/libhdf5.so.10 (0x00007ff7e4d1f000)
	libz.so.1 => /home/culpo/github/spack-scitas/opt/spack/linux-x86_64/intel-16.0.2/zlib-1.2.8-wp6ab5ra3amenxbg4mbetf2k2ix5sz64/lib/libz.so.1 (0x00007ff7e4b04000)
	libdl.so.2 => /lib64/libdl.so.2 (0x0000003dc7800000)
	libm.so.6 => /lib64/libm.so.6 (0x00000032d6c00000)
	libmpi.so.12 => /home/culpo/github/spack-scitas/opt/spack/linux-x86_64/intel-16.0.2/openmpi-1.10.2-qw4mkceu36ce4mbn4woujotclnzcvwsq/lib/libmpi.so.12 (0x00007ff7e457c000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x0000003dc8800000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x0000003dc7400000)
	libc.so.6 => /lib64/libc.so.6 (0x0000003dc7000000)
	libimf.so => /ssoft/intel/2016/RH6/all/x86_E5v2/compilers_and_libraries_2016.2.181/linux//compiler/lib/intel64/libimf.so (0x00007ff7e407e000)
	libsvml.so => /ssoft/intel/2016/RH6/all/x86_E5v2/compilers_and_libraries_2016.2.181/linux//compiler/lib/intel64/libsvml.so (0x00007ff7e31c0000)
	libirng.so => /ssoft/intel/2016/RH6/all/x86_E5v2/compilers_and_libraries_2016.2.181/linux//compiler/lib/intel64/libirng.so (0x00007ff7e2e60000)
	libintlc.so.5 => /ssoft/intel/2016/RH6/all/x86_E5v2/compilers_and_libraries_2016.2.181/linux//compiler/lib/intel64/libintlc.so.5 (0x00007ff7e2bf4000)
	/lib64/ld-linux-x86-64.so.2 (0x0000003dc6c00000)
	libpsm_infinipath.so.1 => /usr/lib64/libpsm_infinipath.so.1 (0x00007ff7e299f000)
	libopen-rte.so.12 => /home/culpo/github/spack-scitas/opt/spack/linux-x86_64/intel-16.0.2/openmpi-1.10.2-qw4mkceu36ce4mbn4woujotclnzcvwsq/lib/libopen-rte.so.12 (0x00007ff7e2685000)
	libopen-pal.so.13 => /home/culpo/github/spack-scitas/opt/spack/linux-x86_64/intel-16.0.2/openmpi-1.10.2-qw4mkceu36ce4mbn4woujotclnzcvwsq/lib/libopen-pal.so.13 (0x00007ff7e23ac000)
	librt.so.1 => /lib64/librt.so.1 (0x0000003dc8000000)
	libutil.so.1 => /lib64/libutil.so.1 (0x0000003dd7400000)
	libhwloc.so.5 => /home/culpo/github/spack-scitas/opt/spack/linux-x86_64/intel-16.0.2/hwloc-1.11.3-ogtoac6inmjv55n6iqezjqmg2rtd7ugu/lib/libhwloc.so.5 (0x00007ff7e2158000)
	libnuma.so.1 => /usr/lib64/libnuma.so.1 (0x0000003dc9000000)
	libpciaccess.so.0 => /home/culpo/github/spack-scitas/opt/spack/linux-x86_64/intel-16.0.2/libpciaccess-0.13.4-5awh3ovyhmnm5js6ygf46suia6lkhbb7/lib/libpciaccess.so.0 (0x00007ff7e1f4c000)
	libinfinipath.so.4 => /usr/lib64/libinfinipath.so.4 (0x00007ff7e1d3f000)
```

**Comment by luigi-calori** [comment]
We have an openmpi module compiled with intel here and I remember being able to solve this problem by adding specific variants.  If I remember well the issue was related to dlopen and hwloc openmpi option. The problem is that it gives no error at build time but it has problems at runtime.
That was the reason to ask for a simple code that test mpi.
I was thinking to try [Intel® MPI Benchmarks](https://software.intel.com/en-us/articles/intel-mpi-benchmarks/) that seems to be [downloadable]( https://software.intel.com/sites/default/files/managed/a3/b2/IMB_4.1.tgz) does it make sense to make a spack package of it that can depends on mpi and add a test function?   ( hints wanted ;-)

**Comment by adamjstewart** [comment]
I'm currently trying to compile it after uncommenting the unset lines in lib/spack/env/cc. If that doesn't work, I'll try @luigi-calori's suggestion of building without hwloc or using `--disable-dlopen`.

**Comment by davydden** [comment]
@luigi-calori maybe a `+test` variant which optionally downloads, compiles and runs the benchmark. Although I am not sure if spack can download extra resources within a single package. In one of the threads there was a discussion on `spack test <package>` function, but I don't remember what was its outcome.

**Comment by adamjstewart** [comment]
OpenMPI could `depends_on('intel-mpi-benchmarks', when='+test')`, but I'm not sure how I feel about that. Ideally, it would be cool to have a separate `test()` function in every Spack package, and whenever you run `spack install -t` or `spack test`, it would run those test commands. It could include simple things like `make test`

**Comment by adamjstewart** [comment]
It would also require the implementation of "test dependencies", much like the "build dependencies" and "run dependencies" that are being worked on in another PR.

**Comment by alalazo** [comment]
In the long run I think we should keep compile-time tests (i.e. those who require to have a stage available) separated from run-time tests (i.e. those who are just a sanity check of the installed software). None of the two imo should change the hash of the installed spec.

**Comment by luigi-calori** [comment]
@adamjstewart Not sure your problem is the same: I do not get any compile error for hdf5

Regarding test I was thinking of something much simpler:  a completely separate package for imb ( test-imb? that depends on mpi so it could be installed using a spec that build openmpi, build test-imb and, as last pass of install, optionally, run the test.


@alalazo did you try to actually use the library?  On my side it seemed ok but then runtime errors happened . This is my report on ldd on h5diff

ldd /gpfs/work/Dec00_remviz/prod/test_intel/spack_clean/opt/spack/linux-x86_64/intel-15.0.2/hdf5-1.8.16-zpnenrfrhy7z5bgrb6z5pxglwa2nokjn/bin/h5diff
        linux-vdso.so.1 =>  (0x00007fff61bf1000)
        libhdf5.so.10 => /gpfs/work/Dec00_remviz/prod/test_intel/spack_clean/opt/spack/linux-x86_64/intel-15.0.2/hdf5-1.8.16-zpnenrfrhy7z5bgrb6z5pxglwa2nokjn/lib/libhdf5.so.10 (0x00007f95fa875000)
        libz.so.1 => /gpfs/work/Dec00_remviz/prod/test_intel/spack_clean/opt/spack/linux-x86_64/intel-15.0.2/zlib-1.2.8-xl62l56tok26rkmedrd4i6ztsmedl3rv/lib/libz.so.1 (0x00007f95fa65a000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f95fa438000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f95fa136000)
        libmpi.so.12 => /gpfs/work/Dec00_remviz/prod/test_intel/spack_clean/opt/spack/linux-x86_64/intel-15.0.2/openmpi-1.10.2-vr2zs5yeiwhgyci4l5ln4lqbm2g53kmv/lib/libmpi.so.12 (0x00007f95f9bcf000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f95f99b9000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f95f979d000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f95f93db000)
        libimf.so => /cineca/prod/compilers/intel/cs-xe-2015/binary/lib/intel64/libimf.so (0x00007f95f8f20000)
        libsvml.so => /cineca/prod/compilers/intel/cs-xe-2015/binary/lib/intel64/libsvml.so (0x00007f95f804c000)
        libirng.so => /cineca/prod/compilers/intel/cs-xe-2015/binary/lib/intel64/libirng.so (0x00007f95f7e45000)
        libintlc.so.5 => /cineca/prod/compilers/intel/cs-xe-2015/binary/lib/intel64/libintlc.so.5 (0x00007f95f7bea000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f95fae40000)
        libopen-rte.so.12 => /gpfs/work/Dec00_remviz/prod/test_intel/spack_clean/opt/spack/linux-x86_64/intel-15.0.2/openmpi-1.10.2-vr2zs5yeiwhgyci4l5ln4lqbm2g53kmv/lib/libopen-rte.so.12 (0x00007f95f78db000)
        libopen-pal.so.13 => /gpfs/work/Dec00_remviz/prod/test_intel/spack_clean/opt/spack/linux-x86_64/intel-15.0.2/openmpi-1.10.2-vr2zs5yeiwhgyci4l5ln4lqbm2g53kmv/lib/libopen-pal.so.13 (0x00007f95f7607000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f95f73ff000)
        libutil.so.1 => /lib64/libutil.so.1 (0x00007f95f71fc000)
        libhwloc.so.5 => /gpfs/work/Dec00_remviz/prod/test_intel/spack_clean/opt/spack/linux-x86_64/intel-15.0.2/hwloc-1.11.3-n54ydfwxtbcsmt42ic622zcalqmuvcry/lib/libhwloc.so.5 (0x00007f95f6fa7000)
        libpciaccess.so.0 => /gpfs/work/Dec00_remviz/prod/test_intel/spack_clean/opt/spack/linux-x86_64/intel-15.0.2/libpciaccess-0.13.4-5owitd4kd4yx2zyytojweardo56ubazs/lib/libpciaccess.so.0 (0x00007f95f6d9c000)
        libxml2.so.2 => /lib64/libxml2.so.2 (0x00007f95f6a33000)
        liblzma.so.5 => /lib64/liblzma.so.5 (0x00007f95f680d000)

**Comment by adamjstewart** [comment]
Commenting out unset didn't work. Trying again without the hwloc dependency.

**Comment by adamjstewart** [comment]
Nope. Exact same error message as first reported. Does anyone else have any suggestions?

**Comment by adamjstewart** [comment]
By the way, my `icc.cfg` contains the following:
```
-Xlinker -rpath -Xlinker /blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-5.3.0/intel-parallelstudio-professional.2016.3-sz7z7dmdxcdkuhakijzapfj3b5ysuhte/compilers_and_libraries_2016.3.210/linux/compiler/lib/intel64 -Xlinker -rpath -Xlinker /blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-5.3.0/intel-parallelstudio-professional.2016.3-sz7z7dmdxcdkuhakijzapfj3b5ysuhte/compilers_and_libraries_2016.3.210/linux/compiler/lib/intel64_lin -Xlinker -rpath -Xlinker /blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-5.3.0/intel-parallelstudio-professional.2016.3-sz7z7dmdxcdkuhakijzapfj3b5ysuhte/compilers_and_libraries_2016.3.210/linux/mpi/intel64/lib -Xlinker -rpath -Xlinker /blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-5.3.0/intel-parallelstudio-professional.2016.3-sz7z7dmdxcdkuhakijzapfj3b5ysuhte/compilers_and_libraries_2016.3.210/linux/mpi/mic/lib -Xlinker -rpath -Xlinker /blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-5.3.0/intel-parallelstudio-professional.2016.3-sz7z7dmdxcdkuhakijzapfj3b5ysuhte/compilers_and_libraries_2016.3.210/linux/ipp/lib/intel64 -Xlinker -rpath -Xlinker /blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-5.3.0/intel-parallelstudio-professional.2016.3-sz7z7dmdxcdkuhakijzapfj3b5ysuhte/compilers_and_libraries_2016.3.210/linux/compiler/lib/intel64 -Xlinker -rpath -Xlinker /blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-5.3.0/intel-parallelstudio-professional.2016.3-sz7z7dmdxcdkuhakijzapfj3b5ysuhte/compilers_and_libraries_2016.3.210/linux/mkl/lib/intel64 -Xlinker -rpath -Xlinker /blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-5.3.0/intel-parallelstudio-professional.2016.3-sz7z7dmdxcdkuhakijzapfj3b5ysuhte/compilers_and_libraries_2016.3.210/linux/tbb/lib/intel64/gcc4.4 -Xlinker -rpath -Xlinker /blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-5.3.0/intel-parallelstudio-professional.2016.3-sz7z7dmdxcdkuhakijzapfj3b5ysuhte/debugger_2016/libipt/intel64/lib -Xlinker -rpath -Xlinker /blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-5.3.0/intel-parallelstudio-professional.2016.3-sz7z7dmdxcdkuhakijzapfj3b5ysuhte/compilers_and_libraries_2016.3.210/linux/daal/lib/intel64_lin -Xlinker -rpath -Xlinker /blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-5.3.0/intel-parallelstudio-professional.2016.3-sz7z7dmdxcdkuhakijzapfj3b5ysuhte/compilers_and_libraries_2016.3.210/linux/daal/../compiler/lib/intel64_lin -L/blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-5.3.0/intel-parallelstudio-professional.2016.3-sz7z7dmdxcdkuhakijzapfj3b5ysuhte/compilers_and_libraries_2016.3.210/linux/ipp/lib/intel64 -L/blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-5.3.0/intel-parallelstudio-professional.2016.3-sz7z7dmdxcdkuhakijzapfj3b5ysuhte/compilers_and_libraries_2016.3.210/linux/compiler/lib/intel64 -L/blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-5.3.0/intel-parallelstudio-professional.2016.3-sz7z7dmdxcdkuhakijzapfj3b5ysuhte/compilers_and_libraries_2016.3.210/linux/mkl/lib/intel64 -L/blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-5.3.0/intel-parallelstudio-professional.2016.3-sz7z7dmdxcdkuhakijzapfj3b5ysuhte/compilers_and_libraries_2016.3.210/linux/tbb/lib/intel64/gcc4.4 -L/blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-5.3.0/intel-parallelstudio-professional.2016.3-sz7z7dmdxcdkuhakijzapfj3b5ysuhte/compilers_and_libraries_2016.3.210/linux/daal/lib/intel64_lin -L/blues/gpfs/home/software/spack/opt/spack/linux-x86_64/gcc-5.3.0/intel-parallelstudio-professional.2016.3-sz7z7dmdxcdkuhakijzapfj3b5ysuhte/compilers_and_libraries_2016.3.210/linux/daal/../compiler/lib/intel64_lin
```
With all of these paths, I was at least able to compile most programs. Just not `hdf5 %intel ^openmpi`

**Comment by lee218llnl** [comment]
I haven't read through all of this, but will throw out some experience that many MPI compiler wrapper scripts specify --enable-new-dtags, which does evil things w.r.t. rpaths.

**Comment by tgamblin** [comment]
@lee218llnl: do we patch that out of our compiler scripts?  AFAIK Spack doesn't, so if a package actually uses `mpicc` directly it would cause the `RPATH`s not to get set properly.  We should probably remove that from the MPI wrappers that Spack installs.

**Comment by lee218llnl** [comment]
@tgamblin, @adammoody will have to confirm, but I believe locally we do patch our compiler scripts in our /usr/local installations of mvapich and OpenMPI (and I do this with Intel MPI). I haven't implemented this in the Spack Intel MPI package, but can do this if you think it makes sense. Perhaps I should make it a variant and default it to remove the new-dtags?

**Comment by tgamblin** [comment]
@lee218llnl a PR would be great. I think it should just strip the flag by default, though.  The only place I'd disable the flag is when we merge the support the CERN guys want for using RUNPATH instead of RPATH (#639).  @hegner was saying they are still working on that, though.  In that narrow case, we'd check whether the particular install tree is configured for `RUNPATH` or `RPATH` and act accordingly.

**Comment by adamjstewart** [comment]
From #946:

> I'm not sure why you would need all of the other library paths in the .cfg file. Do you know which one in particular it needed (I would have just thought the lib/intel64 would be sufficient)? Note that one of the paths that you added is the Intel MPI lib path, which might not be the best thing to include.

@lee218llnl YOU ARE A GENIUS!!!

When I first installed Intel, I tried only specifying `-Xlinker -rpath -Xlinker` for the main library path. But I was unable to install anything. Then I tried adding the other paths from the `LD_LIBRARY_PATH` generated by sourcing `compilervars.sh`, and that gave me a little more success, but still failed on some packages. I later discovered that I was missing some paths from `LIBRARY_PATH`, and added them to the .cfg files. This allowed me to build everything, except `hdf5 %intel ^openmpi`.

I just tried cutting things down to see what paths were actually necessary, and discovered that if I add `-Xlinker -rpath -Xlinker` AND `-L` for ONLY the `lib/intel64` directories, `hdf5 %intel ^openmpi` magically installs!

We should probably add more documentation for using compilers with Spack, and this should probably be added to #946, but I'm very happy right now. I'm going to try compiling everything else with these new .cfg files overnight.

For future reference, the following `icc.cfg`, `icpc.cfg`, and `ifort.cfg` files worked for me:
```
-Xlinker -rpath -Xlinker /soft/spack/opt/spack/linux-x86_64/gcc-5.3.0/intel-parallelstudio-professional.2016.3-sz7z7dmdxcdkuhakijzapfj3b5ysuhte/compilers_and_libraries_2016.3.210/linux/compiler/lib/intel64 -L/soft/spack/opt/spack/linux-x86_64/gcc-5.3.0/intel-parallelstudio-professional.2016.3-sz7z7dmdxcdkuhakijzapfj3b5ysuhte/compilers_and_libraries_2016.3.210/linux/compiler/lib/intel64
```

**Comment by hegner** [comment]
@tgamblin - the RPATH vs. RUNPATH #909 is only "blocked" by #908 because it is on top of it. And both are ready for review. What's not ready is still marked as WIP.

**Comment by lee218llnl** [comment]
@adamjstewart I'm flattered! One question, though, do you really need to add the -L option to the .cfg file? The Intel compiler should add this to the link line by default. If you remove it from your .cfg files, you can do an icc/icpc/ifort with the -v option to confirm what it passes to ld.

**Comment by adamjstewart** [comment]
I do. I'm not sure why, but with only the `-Xlinker -rpath -Xlinker` option, I'm unable to build anything. Simple packages like libsigsegv or jpeg crash during configure and claim that the compiler cannot create C executables. If you want I can recreate this and post some config.log files.

**Comment by svenevs** [comment]
Hello, I am experiencing this and don't quite understand the "fix" described in [@adamjstewart's comment](https://github.com/LLNL/spack/issues/784#issuecomment-219845340) above.

> For future reference, the following icc.cfg, icpc.cfg, and ifort.cfg files worked for me:

Where are these files supposed to be?  Right now I'm just trying to compile `tmux %intel@15.0.3` (on a RHEL 6 cluster if it matters), arriving at a missing `libimf.so` error on `make install` for `ncurses`.  The thing that confuses me:

```cosole
$ locate libimf.so
/usr/local/intel/composer_xe_2015.3.187/compiler/lib/intel64/libimf.so
/usr/local/intel/composer_xe_2015.3.187/compiler/lib/mic/libimf.so
/usr/local/intel/itac/9.0.3.051/intel64/bin/rtlib/libimf.so

$ echo $LD_LIBRARY_PATH | grep -Hn --color=auto /usr/local/intel/composer_xe_2015.3.187/compiler/lib/intel64
(standard input):1:/usr/local/intel//impi/5.0.3.048/intel64/lib:/usr/local/intel//itac/9.0.3.051/mic/slib:/usr/local/intel//itac/9.0.3.051/intel64/slib:/usr/local/intel/composer_xe_2015.3.187/compiler/lib/intel64:/opt/intel/mic/coi/host-linux-release/lib:/opt/intel/mic/myo/lib:/usr/local/intel/composer_xe_2015.3.187/mpirt/lib/intel64:/usr/local/intel/composer_xe_2015.3.187/ipp/../compiler/lib/intel64:/usr/local/intel/composer_xe_2015.3.187/ipp/lib/intel64:/usr/local/intel/composer_xe_2015.3.187/ipp/tools/intel64/perfsys:/opt/intel/mic/coi/host-linux-release/lib:/opt/intel/mic/myo/lib:/usr/local/intel/composer_xe_2015.3.187/compiler/lib/intel64:/usr/local/intel/composer_xe_2015.3.187/mkl/lib/intel64:/usr/local/intel/composer_xe_2015.3.187/tbb/lib/intel64/gcc4.4:/usr/local/intel/composer_xe_2015.3.187/debugger/libipt/intel64/lib
```

The intel compiler I'm using was made available by an already-existing `module load psxe`.  I vaguely recall that `spack` will ignore my personal `$LD_LIBRARY_PATH` and/or clean the environment or something, but don't know how to inform `spack` where to look otherwise with the above specified `.cfg` files x0

**Comment by adamjstewart** [comment]
@svenevs I think this discussion is even more clear:
https://groups.google.com/d/topic/spack/NxyNTAZyMQg/discussion

Basically, Intel's compilers do not know where Intel's libraries live, they rely on things like `LD_LIBRARY_PATH` to locate them. As you noted, Spack unsets `LD_LIBRARY_PATH` before building to clean the environment, so we can't rely on it. The recommended way to get around this is to create `icc.cfg`, `icpc.cfg`, and `ifort.cfg` files to tell the compilers where their libraries can be found. These files need to be located in the same directory as the compilers themselves. Note that `prefix/bin` contains these compilers, but these are just symlinks. The config files need to be in the same directory as the actual compilers.

Also note that this problem only occurs when using an externally installed Intel compiler. If you let Spack install your compilers, it will solve this problem for you. Check out `rpath_configuration` in both `intel` and `intel-parallel-studio` for the details.

The installation directories change with each version, but it should look something like:
```
# Find icc directory
$ which icc
/usr/local/intel/compilers_and_libraries_2015.3.187/bin/icc
# Follow symlinks to find real icc directory
$ readlink -f /usr/local/intel/compilers_and_libraries_2015.3.187/bin/icc
/usr/local/intel/compilers_and_libraries_2015.3.187/linux/bin/intel64/icc
# Create icc.cfg, icpc.cfg, and ifort.cfg files in this directory containing:
$ cat /usr/local/intel/compilers_and_libraries_2015.3.187/linux/bin/intel64/icc.cfg
-Xlinker -rpath -Xlinker /usr/local/intel/compilers_and_libraries_2015.3.187/linux/compiler/lib/intel64_lin
```

**Comment by svenevs** [comment]
Ahhhhhh ok I'll have to get el jefe to make those then, I don't have write access there.  I thought the `*.cfg` files were supposed to be going under `spack` somewhere, thanks!

**Comment by adamjstewart** [comment]
Alternatively, in https://groups.google.com/forum/#!topic/spack/5jVVwd1OeqQ, James recommends adding this directory as an `extra_rpaths` in `compilers.yaml`. I've never tried this before, but it may work if you don't have write access. Worth a shot if you're in a rush.

**Comment by svenevs** [comment]
Excellent, I went with the `compilers.yaml` approach since we'd have to jump through some annoying hoops to create the `.cfg` files down there (only IT has root privs...).  So for completeness, in my specific case, the relevant section of `compilers.yaml` is:

```yaml
- compiler:
    environment: {}
    extra_rpaths: [/usr/local/intel/composer_xe_2015.3.187/compiler/lib/intel64]
    flags: {}
    modules: []
    operating_system: rhel6
    paths:
      cc: /usr/local/intel/bin/icc
      cxx: /usr/local/intel/bin/icpc
      f77: /usr/local/intel/bin/ifort
      fc: /usr/local/intel/bin/ifort
    spec: intel@15.0.3
    target: x86_64
```

There **may** be some unexpected errors in the future, from the above we had

```console
$ locate libimf.so
/usr/local/intel/composer_xe_2015.3.187/compiler/lib/intel64/libimf.so
/usr/local/intel/composer_xe_2015.3.187/compiler/lib/mic/libimf.so
/usr/local/intel/itac/9.0.3.051/intel64/bin/rtlib/libimf.so
```

I chose the `intel64` folder and things are seemingly happy.  The issue is the pesky `mic` folder.  On this cluster we have the old version of the Xeon Phi cards which use a `#pragma offload(target:mic)` programming model.  These were the first generation, where the host compiler and Phi compiler are **different**.  Anybody else reading this should hopefully not even have a `mic` compiler (assuming newer cards and/or more up to date intel compiler) described in the google forum link Adam provides above :wink:

Thanks so much for consolidating all of the information @adamjstewart :heart_eyes:

**Comment by alalazo** [comment]
@svenevs Just for completeness: you can still use `.cfg` files and put them wherever you want. In that case you need to set `ICCCFG` & Co. to point the Intel compilers to the configuration files. [See here.](https://software.intel.com/en-us/node/522780)

**Comment by svenevs** [comment]
@alalazo I'm not sure how related this is, but I think [these lines would need to respect this](https://github.com/LLNL/spack/blob/db657d938d38775e4364a6917cc78cb9cdb0b133/var/spack/repos/builtin/packages/intel-parallel-studio/package.py#L407-L416) as well then?

Should only affect installations (not using), would it just be

```py
lib_dir = os.path.join(self.prefix, self.lib_dir)
# NOTE: these are the linux ones, not windows (see above post)
# NOTE: what about the fortran compiler?
for compiler, cfg_env in [('icc', 'ICCCFG'), ('icpc', 'ICPCCFG'), ('ifort', '???')]:
    # Do not write config files if user has custom configs setup already
    if cfg_env not in os.environ:
        cfgfilename = os.path.join(
            self.prefix, self.bin_dir, '{0}.cfg'.format(compiler))
        with open(cfgfilename, 'w') as f:
            f.write('-Xlinker -rpath -Xlinker {0}\n'.format(lib_dir))
```

There's a half-baked intel PR out thanks to adam's help in #5172 I can add this too.  Adam had mentioned the other intel packages will need the same love for that to be ready to merge though.
