### ISSUE TITLE
default openblas fails with clang

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#799]
subj, due to a new `+openmp` variant recently introduced by @adamjstewart .
I am not sure, but perhaps the best is to change default of the option to `false` for clang compiler.

**Comment by davydden** [comment]
or perhaps do some checks inside for clang version, at least it fails with `Apple LLVM version 7.3.0`.

**Comment by adamjstewart** [comment]
Oops. I don't believe there is currently a way to set the default based on compiler. Like you said, we could remove the variant and just do a version check inside for clang. Ideally, anyone should be able to build a package with the default variants. Elk needed this set or else I couldn't build it. I'll take a look at this and try to put out a PR later today.

**Comment by adamjstewart** [comment]
How are Clang and Apple LLVM related? Clang fully supports OpenMP 3.1 as of 3.8.0 (the latest release).

**Comment by adamjstewart** [comment]
If Clang and Apple LLVM have different release versions, I'm not sure how to ensure that the compiler supports OpenMP. Perhaps they should be split into 2 different compilers?

**Comment by davydden** [comment]
yes, AFAIK annoyingly they have different versioning. 

I could not find any definitive answer to OpenMP in Appple's Clang, but most likely it is actually not supported.

W.r.t. different versioning, i think it's ok to have it in a single compiler as long as one could do version checks
```
clang@7.3.0-apple:
```
and
```
clang@3.8.0:
```

I don't know whether `clang@3.8.0:` will be satisfied by `clang@7.3.0-apple`. If not, we are good.

**Comment by gartung** [comment]
This also happens to fftw when you try to build with clang.

**Comment by adamjstewart** [comment]
Well, we don't personally use Clang here, so I guess it's up to you guys how you want it implemented. From the documentation I've read, Clang 3.8.0 supports at least some level of OpenMP. I couldn't find much of any info on what version of Apple/LLVM supports OpenMP. I could just make it easy and always build with OpenMP unless the compiler is Clang.

**Comment by davydden** [comment]
> I could just make it easy and always build with OpenMP unless the compiler is Clang.

perhaps, this is the best solution. Any refinement of this strategy inside the package can be done without changing variants.

**Comment by eschnett** [comment]
Both clang 3.7 and clang 3.8 support OpenMP. Clang 3.7 required a special setup when installing the compiler, with clang 3.8 it's automatic. Thus, please don't use "clang" as discriminator -- please look at the version numbers as well.

**Comment by davydden** [comment]
>  Thus, please don't use "clang" as discriminator -- please look at the version numbers as well.

I suppose the current version form Apple would be `7.3.0-apple`, unless the `-apple` is cut off somewhere inside. If it is, there will be nothing to discriminate Apple's clang from other.

**Comment by adamjstewart** [comment]
@eschnett: Do you think there is enough of a reason to separate the Clang and Apple/LLVM compilers as separate compilers? The different versions are really making this more trouble than it should be.

**Comment by eschnett** [comment]
@adamjstewart Having two compilers `clang` and `clang-apple` would be one way. Another option would be to somehow convert versions, but I don't know which versions correspond to each other.

Yes, I think distinguishing between `clang` and `clang-apple` makes most sense. On one hand, this makes checking for the operating system unnecessary, as we'd just check the compiler name instead. On the other hand, all packages currently checking for `clang` need to be reviewed to see whether they should be checking `clang-apple` instead.

**Comment by davydden** [comment]
i also think it's best to keep the two separate. Apple dropped mentioning which Clang they used in their version since `7.0`. There used to be something like `(based on LLVM 3.6.0svn)`.

**Comment by adamjstewart** [comment]
I'll leave it to you two to start that process if you want to. I don't even use Clang :smiley:

**Comment by mathstuf** [comment]
> (based on LLVM 3.6.0svn)

This really means "some arbitrary commit around 3.6.0" and could have any number of random features.

> On one hand, this makes checking for the operating system unnecessary, as we'd just check the compiler name instead.

One can still use a custom-built clang on Apple, so you still need to check for the target OS.

**Comment by eschnett** [comment]
@mathstuf OpenBLAS does not handle OpenMP when clang is used. This is an OpenBLAS limitation, not a clang limitation; see my comment above.
