### ISSUE TITLE
add support of -std=c++1y and -std=c++14

### ISSUE THREAD

**Issue by gartung** [LLNL/spack#801]
Many HEP packages make use of the c++1y and c++14 std when compiling with gcc. For example: 
https://github.com/HEP-SF/hep-spack/blob/master/packages/clhep/package.py#L40

Options for handling these were added by Adam Lyon but need to be reviewed 

https://github.com/LLNL/spack/commit/6010bdba6dd22ee6b521c30be2476807f58e7f45

**Comment by gartung** [comment]
https://github.com/LLNL/spack/pull/802

**Comment by drbenmorgan** [comment]
Looks good - certainly from the HEP side, it should also be added for Clang and Intel compilers.

**Comment by gartung** [comment]
#802 merged
