### ISSUE TITLE
gcc build on OS X broken (again)

### ISSUE THREAD

**Issue by gartung** [LLNL/spack#809]
After updating to the HEAD of develop the build on gcc 4.9.3 on OS X is broken (again). Testing the build of gcc 5.3.0 now. May be a moot point as the HEP community may abandon compiling with gcc on OS X.

**Comment by gartung** [comment]
Looks like the "ld -r -rpath" problem has come up again
make[2]: *** [compare] Error 1
make[1]: *** [stage3-bubble] Error 2
make: *** [bootstrap] Error 2

**Comment by gartung** [comment]
@tgamblin where is $OSTYPE set?

https://github.com/eschnett/spack/blob/83d6e04d39ce81376c96cf6b4aa3261ff9e6fbc9/lib/spack/env/cc#L166

**Comment by gartung** [comment]
#821 fixes this

**Comment by tgamblin** [comment]
@gartung: `OSTYPE` is a bash thing -- it's builtin (see [bash variables](https://www.gnu.org/software/bash/manual/bashref.html#Bash-Variables)) so if somehow `cc` was invoked in a POSIX non-compliant way, it wouldn't be there.

Is `OSTYPE` not there or is it set to something other than expected?  I'm now curious what aspects of `bash` we can rely on.  `cc` and other scripts start with `#!/bin/bash`, so they shouldn't be invoked with `/bin/sh` to make `bash` run in a weird mode.

Either way, your PR looks like a reliable way to fix this.

**Comment by gartung** [comment]
It might have been the missing $ in front on mode.

**Comment by gartung** [comment]
I looked at the changes to env/cc since the last time I was able to compile gcc on OSX. I immediately saw the change from single to double braces. One of our shell scripts used double braces and behaved differently when going from bash on RHEL6 to bash on Ubuntu 14.  I missed the missing $ in front of mode and I did not know where $OSTYPE came from.
