### ISSUE TITLE
develop: Version URL incorrectly parsed (Maven)

### ISSUE THREAD

**Issue by alfredo-gimenez** [LLNL/spack#81]
Maven has the following download URL:
http://mirrors.sonic.net/apache/maven/maven-3/3.3.3/source/apache-maven-3.3.3-src.tar.gz

Spack tries to determine the download URL for version 3.3.3 and incorrectly tries:
http://mirrors.sonic.net/apache/maven/maven-3.3.3.3/source/apache-maven-3.3.3-src.tar.gz

**Comment by adamjstewart** [comment]
I don't see a package for Maven. Is this something you were trying to add yourself?

**Comment by alfredo-gimenez** [comment]
Yes, this happened when I tried to do a "spack create" for the maven url.

**Comment by adamjstewart** [comment]
I just ran `spack create` with the URL you provided and it worked fine. Are you still able to reproduce this bug?

**Comment by alfredo-gimenez** [comment]
Just tried it again and looks like it works fine for me too!

**Comment by adamjstewart** [comment]
Glad to hear!
