### ISSUE TITLE
[environment modules] setup_dependent_environment() and DYLD_LIBRARY_PATH?

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#815]
I played a bit with environment modules. I would like to discuss a couple of enhancement points:

1. In some cases it makes sense to set up some extra environment variables for a given package. Say if you use `deal.II` in your personal project, most likely your `CMakeFiles` have `DEAL_II_DIR` as a hint to CMake where to look for a library. In case of `petsc`, the commonly used variable is `PETSC_DIR`. It possible, one could reuse  `def setup_dependent_environment(self, spack_env, run_env, dependent_spec):` assuming that `spack_env.set('PETSC_DIR', self.prefix)` would also set the environment variable. Otherwise one could define another method for a package which is to be called when `module load package` is executed.

2. Currently, the `lib` folder is added to `LD_LIBRARY_PATH`. It would make sense to use `DYLD_LIBRARY_PATH` on OS-X, if possible. I don't know whether it is modules-ecosystem or Spack's related. This feature is not relevant to the latest OSX where `DYLD_LIBRARY_PATH` shall not be used anyway.

(2) is not a deal breaker, whereas IMHO (1) would be a good feature to have.

@citibeth ping.

**Comment by alalazo** [comment]
The line : 
```
spack_env.set('PETSC_DIR', self.prefix)
```
in `setup_dependent_environment` will set the environment variable at build time **for dependencies** of petsc. To have the same variable set in the module file that is generated for petsc you need to set : 
```
run_env.set('PETSC_DIR', self.prefix)
```
int the function `setup_environment`. FYI, you may want to have a look at #744 for further customization on module files that can be done from a configuration file.

**Comment by davydden** [comment]
@alalazo cool, thanks for the link to the PR. That's a lot of nice features.

I did not know about `def setup_environment(self, spack_env, env):`, apparently it is currently used only in a single (!) package -- qt. Will use that to fulfil (1).

Since (2) is not that important, I am closing the issue.
