### ISSUE TITLE
git depends indirectly on expat, but expat wasn't built first.

### ISSUE THREAD

**Issue by timattox** [LLNL/spack#817]
When I tried to do a "spack install git" from a fresh (empty) spack installation, git failed to build with an error "http-push.c:18:19: fatal error: expat.h: No such file or directory" on a Cray XC40 login node.

**Comment by mathstuf** [comment]
There is a `+expat` variant in git already. Are you using `develop`?

**Comment by timattox** [comment]
Yes, I am using develop.  I am new to spack, so it could be user error.

**Comment by adamjstewart** [comment]
No worries, welcome to Spack!

To install Git, simply run:
```bash
spack install git +expat
```
To the other developers: Why was expat an optional variant? Is there any reason we shouldn't always depend_on expat?

**Comment by mathstuf** [comment]
We should probably pass `--without-expat` if the variant isn't given.

**Comment by mathstuf** [comment]
Yeah, looking at the configure step, it looks like git tries to build with expat by default; all `+expat` does is have it build with spack's expat rather than a system copy (same with curl). See #819.

**Comment by adamjstewart** [comment]
The history doesn't go back far enough to see why expat and curl are optional dependencies. Do they not build on some systems?

**Comment by mathstuf** [comment]
The history probably stops when the repos directory was added. Search `*/git/package.py` to get results no matter where it was in the repo. That points to 31863c68d8d3010dc28945f35e323d4541962788 where they've been optional since the beginning.

**Comment by citibeth** [comment]
If expat is needed, then it should be listed as a non-optional dependency.  If a user wants to use the system's expat, she can do that in ~/.spack/packages.yaml.  Maybe Spack should provide a default or initial packages.yaml file.

**Comment by mathstuf** [comment]
Well, the difference here is that the dependency can be turned off, but that also means `git push http://...` doesn't work.

**Comment by mathstuf** [comment]
Fixed by #819; this can be closed.

**Comment by adamjstewart** [comment]
Ping @tgamblin, needs closing.

**Comment by mathstuf** [comment]
Ping :) .
