### ISSUE TITLE
Packaging software without versions or tars

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#823]
I'm trying to write a package for the [STREAM benchmark](https://www.cs.virginia.edu/stream/). Frustratingly, the [source code](https://www.cs.virginia.edu/stream/FTP/Code/) isn't packaged in a tar, nor is it numbered with any versions. I found a slightly older tar packaged by [NERSC](http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/stream/), so I can use that if I have to and just give it a fake number. I'm just wondering if there's a better way to go about this that I haven't thought of yet. Can Spack download a ftp directory like STREAM uses?

**Comment by adamjstewart** [comment]
Actually, I'm not sure if this can even be packaged. It uses hardcoded parameters that you have to edit in the source code before building. I don't think there's a way to automate that for all users.

**Comment by tgamblin** [comment]
well, actually after we get #cflags merged I think we have at least part of what we need for non-boolean build parameters i.e., we could potentially build:

```
spack install streams param1=4 param2=5
```

Where param1 and param2 have some defaults if you don't add them.  Different param versions would be installed in different prefixes with different hashes, like other spack things.  Thoughts?

**Comment by adamjstewart** [comment]
That ought to solve the problem with hardcoded variables. Any thoughts on the other issues I raised?

**Comment by adamjstewart** [comment]
Just to clarify, there's no way for Spack to download files from an FTP repo, right?

**Comment by tgamblin** [comment]
- [package.py:65](https://github.com/LLNL/spack/blob/develop/lib/spack/spack/package.py#L65)

```bash
$ cd src/spack/var/spack/repos/builtin/packages/
$ grep ftp: */*
bash/package.py:    url      = "ftp://ftp.gnu.org/gnu/bash/bash-4.3.tar.gz"
cfitsio/package.py:        url = 'ftp://heasarc.gsfc.nasa.gov/software/fitsio/c/cfitsio{0}.tar.gz'
grep: gcc/darwin: Is a directory
gnutls/package.py:    url      = "ftp://ftp.gnutls.org/gcrypt/gnutls/v3.3/gnutls-3.3.9.tar.xz"
gromacs/package.py:    url = 'ftp://ftp.gromacs.org/pub/gromacs/gromacs-5.1.2.tar.gz'
libffi/package.py:    version('3.2.1','83b89587607e3eb65c70d361f13bab43',url = "ftp://sourceware.org/pub/libffi/libffi-3.2.1.tar.gz")
libffi/package.py:    #version('3.1', 'f5898b29bbfd70502831a212d9249d10',url = "ftp://sourceware.org/pub/libffi/libffi-3.1.tar.gz") # Has a bug $(lib64) instead of ${lib64} in libffi.pc
libgcrypt/package.py:    url      = "ftp://ftp.gnupg.org/gcrypt/libgcrypt/libgcrypt-1.6.2.tar.bz2"
libgpg-error/package.py:    url      = "ftp://ftp.gnupg.org/gcrypt/libgpg-error/libgpg-error-1.18.tar.bz2"
libsigsegv/package.py:    url      = "ftp://ftp.gnu.org/gnu/libsigsegv/libsigsegv-2.10.tar.gz"
m4/package.py:    url      = "ftp://ftp.gnu.org/gnu/m4/m4-1.4.17.tar.gz"
mesa/package.py:    url      = "ftp://ftp.freedesktop.org/pub/mesa/older-versions/8.x/8.0.5/MesaLib-8.0.5.tar.gz"
mesa/package.py:    # url      = "ftp://ftp.freedesktop.org/pub/mesa/10.4.4/MesaLib-10.4.4.tar.gz"
mpc/package.py:    url      = "ftp://ftp.gnu.org/gnu/mpc/mpc-1.0.2.tar.gz"
mpc/package.py:            return "ftp://ftp.gnu.org/gnu/mpc/mpc-%s.tar.gz" % version
mpe2/package.py:    url      = "ftp://ftp.mcs.anl.gov/pub/mpi/mpe/mpe2-1.3.0.tar.gz"
mrnet/package.py:    url      = "ftp://ftp.cs.wisc.edu/paradyn/mrnet/mrnet_5.0.1.tar.gz"
ncview/package.py:    url      = "ftp://cirrus.ucsd.edu/pub/ncview/ncview-2.1.7.tar.gz"
netcdf/package.py:    url      = "ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.3.3.tar.gz"
octave/package.py:    url      = "ftp://ftp.gnu.org/gnu/octave/octave-4.0.0.tar.gz"
openssl/package.py:        latest = 'ftp://ftp.openssl.org/source/openssl-{version}.tar.gz'
pcre/package.py:    url      = "ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre-8.36.tar.bz2"
pcre2/package.py:    url      = "ftp://ftp.csx.cam.ac.uk/pub/software/programming/pcre/pcre2-10.20.tar.bz2"
readline/package.py:    url      = "ftp://ftp.cwru.edu/pub/bash/readline-6.3.tar.gz"
udunits2/package.py:    url      = "ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.2.20.tar.gz"
vim/package.py:    url      = "ftp://ftp.vim.org/pub/vim/unix/vim-7.4.tar.bz2"
```

**Comment by adamjstewart** [comment]
Sorry, by FTP repo I mean this:
http://www.cs.virginia.edu/stream/FTP/Code/

There's no tarball :(

**Comment by adamjstewart** [comment]
I found a couple mirrors:
https://github.com/jeffhammond/STREAM
http://www.nersc.gov/users/computational-systems/cori/nersc-8-procurement/trinity-nersc-8-rfp/nersc-8-trinity-benchmarks/stream/
but they're a bit older or less complete. I think I'm going to have to use one or the other though.

**Comment by tgamblin** [comment]
You could hack a package that fetches just one file, and use `expand=False` with the version (look at `mfem`).  That will skip the expand stage.  Then make your package depend on `wget` and do it that way.  But that is kind of nasty and more support would be nice.

**Comment by adamjstewart** [comment]
Yeah, I'll stick with that GitHub mirror for now. I'll have enough work making it work with various compilers and flags.

**Comment by adamjstewart** [comment]
Closing this now that I have a package prepared. See #975.
