### ISSUE TITLE
Packages with shared setup infrastructure

### ISSUE THREAD

**Issue by lee218llnl** [LLNL/spack#832]
I’m working on the various Intel software packages in Spack #796. They all use the same installer and thus all share a lot of setup in their package.py. It would be nice if the shared setup could be encapsulated in an Intel base package class that the various packages can derive from. I’m wondering if there are any thoughts on the best way to implement this would be. 

I was thinking that we could have an intel sub directory in the repo/builtin/packages and then have sub directories for each package, but then Spack won’t recognize the packages and they won’t be directly visible to users in the repos/builtin/packages directory. Perhaps the latter fact isn't a big issue since users should be doing a spack list instead of an ls on the packages directory.

Alternatively, I could keep each package in it’s on repos/builtin/packages directory and then put the Intel base class somewhere that it could be imported. The question here, however, is where should that Intel base class module live?

Is there another mechanism that exists that I'm not thinking of? I'm not sure if this is a general enough issue that it warrants putting new infrastructure in place for Spack itself. If not, I can easily just have each individual Intel package do some tricks to modify their sys.path to find my base Intel class, but it wouldn't be very elegant. Any thoughts @tgamblin @mplegendre @becker33?

**Comment by mathstuf** [comment]
Would absolute imports be a viable solution? Then you could do:

```python
from .support.intel import *
```

and place the `intel.py` module in `packages/support`.

**Comment by lee218llnl** [comment]
@mathstuf That doesn't appear to work. Could this be because the packages directory is not in sys.path. My hack of adding it to sys.path does work, though. Using the file and directory names in your example, my package would do:

sys.path.append(os.path.split(os.path.dirname(os.path.realpath(__file__)))[0])
from support.intel import *
sys.path.pop()

**Comment by mathstuf** [comment]
Oh, probably needs:

```python
from __future__ import absolute_import
```

to work properly.

**Comment by lee218llnl** [comment]
@mathstuf I think what you suggest is actually considered a relative import and doesn't need the __future__. Plus I think absolute import is the default for newer Python versions anyway. That said, I can't for the life of me get this to work. If I try verbatim what you suggest, I get "ImportError: No module named support.intel. I get the same error if I try what I think looks more correct "from ..support.intel import *" I get the same error. From my understanding, relative imports only work for modules within a python package and the spack package directory isn't considered a python package. Unless you are able to demonstrate something that actually works, I'll probably just stick with my hack for now, since I know the hack works.

**Comment by mathstuf** [comment]
Ah, yeah, got mixed up there. You do want a relative import, but also, yeah, the use of `__import__` (or `importlib`) probably does block such things :( .

**Comment by lee218llnl** [comment]
@tgamblin gave me a pointer that allowed me to do what I wanted in commit f87011e as part of PR #796. I created my base IntelInstaller class in var/spack/repos/builtin/packages/intel/package.py and then loaded it with `from spack.pkg.builtin.intel import IntelInstaller`.
