### ISSUE TITLE
[Question] Building MVAPICH2 for Use on QLogic Infiniband Networks

### ISSUE THREAD

**Issue by xjrc** [LLNL/spack#840]
I've been having a bit of trouble using Spack-built versions of MVAPICH2 to compile MPI codes on the LC machines.  Specifically, I'm running into troubles getting basic MPI codes built with a Spack-provided MVAPICH2 to run with more than one task on [`cab`](https://computing.llnl.gov/?set=resources&page=OCF_resources#cab) (I'm able to compile and build without any troubles); the codes that I build in this environment fail to distribute MPI tasks properly and (consequently) execute the same code for each task.

Since I'm able to compile and link the code, I'm fairly certain that the problem is related to the variant of MVAPICH2 that I've been using for my builds.  I've been trying `mvapich2@2.2b+slurm+psm` since the LC machines use SLURM for resource management and [`cab`](https://computing.llnl.gov/?set=resources&page=OCF_resources#cab) has QLogic infiniband interconnects, but I'm not entirely certain that this is correct.  Does this seem like the correct variant to be using or do I need to switch to a different resource manager/network type?  If this does seem like the correct variant, is there something else I should look into?  Also, for the LLNL folks (e.g. @tgamblin, @lee218llnl, @markcmiller86), have you been using MVAPICH2 and if so, what variant have you been using on machines like  [`cab`](https://computing.llnl.gov/?set=resources&page=OCF_resources#cab)?

Thanks in advance for any help that you can provide!

**Comment by tgamblin** [comment]
@xjrc: The `mvapich2` package is a bit old -- I think Adam will probably update it after TOSS3 is released but for now I'd use [concretization policies](http://software.llnl.gov/spack/packaging_guide.html#concretization-policies), specifically a `packages.yaml` file, to point at LC's installs in `/usr/local/tools`.  

@adammoody: can you comment on this too?

**Comment by alalazo** [comment]
Not sure if it may be of help, but we experienced similar weird issues when running `mvapich2` applications not started by `srun` when an `mpiexec` or an `mpirun` coming from somewhere else was accidentally in `PATH`...

**Comment by xjrc** [comment]
@tgamblin: Thanks for the information; I'll wait on the updated version of the `mvapich2` package before I try and use it again.  It looks like concretization policies will allow me to continue testing MPI-dependent packages for the time being.  For anyone in a similar situation, here's the `packages.yaml` file that I'm using:

```
packages:
  mvapich2:
    paths:
      mvapich2@1.9%gcc@4.7.2=chaos_5_x86_64_ib~debug~gforker~hydra~mrail~nemesis~nemesisib~nemesisibtcp+psm~remshell+slurm~sock: /usr/local/tools/mvapich2-gnu-1.9
      mvapich2@1.9%gcc@4.7.2=chaos_5_x86_64_ib+debug~gforker~hydra~mrail~nemesis~nemesisib~nemesisibtcp+psm~remshell+slurm~sock: /usr/local/tools/mvapich2-gnu-debug-1.9
      mvapich2@2.0%gcc@4.7.2=chaos_5_x86_64_ib~debug~gforker~hydra~mrail~nemesis~nemesisib~nemesisibtcp+psm~remshell+slurm~sock: /usr/local/tools/mvapich2-gnu-2.0
      mvapich2@2.0%gcc@4.7.2=chaos_5_x86_64_ib+debug~gforker~hydra~mrail~nemesis~nemesisib~nemesisibtcp+psm~remshell+slurm~sock: /usr/local/tools/mvapich2-gnu-debug-2.0
  all:
    compiler: [gcc@4.7.2]
    providers:
      mpi: [mvapich2]
```

@alalazo: I've been trying to run applications exclusively using `srun` so far, but this is certainly helpful information for when I need to test without it!  I'll be sure to disable the parts of my path that include superfluous `mpiexec` or `mpirun` binaries when I try to run locally.  Thanks!

**Comment by xjrc** [comment]
Since I have an intermittent solution working, I'm going to close this issue for now.  I'll reopen it if I have any need for a Spack-installed `mvapich2` package.
