### ISSUE TITLE
openblas fails to pick up fortran compiler from Spack

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#846]
`openblas` really drives me nuts. Apparently, the solution of this PR https://github.com/LLNL/spack/pull/751 was not enough. It seems that if the fortran compiler is not in the path (i.e. build by Spack and is used as `f77: /path/to/spack/opt/spack/darwin-x86_64/clang-7.3.0-apple/gcc-5.3.0-ctakkbfikm76kcnssbb3gv53mlrwldbl/bin/gfortran`) then `openblas` does not pick it up
```
OpenBLAS: Detecting fortran compiler failed. Cannot compile LAPACK. Only compile BLAS.
```

Previously it seemed to work for me because I had `gfortran` from `homebrew` in path. Now I removed homebrew completely and thereby discovered this issue.

I noticed that `openblas` has `cmake` config, maybe it's time to use that to avoid the buggy make scripts?

@tgamblin ideas?

**Comment by davydden** [comment]
I checked with `spack evn openblas bash` and indeed if I add to path location of `gfortran`, `openblas` is happy.

**Comment by davydden** [comment]
FIY i create a topic on Openblas forum https://groups.google.com/forum/#!topic/openblas-dev/C_oUHWQm4Tk

**Comment by citibeth** [comment]
As a stopgap, you can do a "module load" of the Fortran compiler you want to build with before you launch Spack.

**Comment by davydden** [comment]
thanks @citibeth , this workaround worked for me on osx.

**Comment by davydden** [comment]
@tgamblin given this compiler puckup issues with openblas, should we try adding location of compilers to PATH inside the `package.py`? I assume the same issue will appear with openblas for any other compiler which is not in PATH during `make FC=XYZ`.

**Comment by davydden** [comment]
Some important updates to this issue, apparently
```
make -j8 CC=clang FC=/Users/davydden/spack/opt/spack/darwin-x86_64/clang-7.3.0-apple/gcc-5.3.0-ctakkbfikm76kcnssbb3gv53mlrwldbl/gfortran libs netlib shared
```
picks up fortran just fine. It must have to do with the naming and inability to understand that it's `GCC` from a simple `f77`. @tgamblin explained the wrapper structure here https://github.com/LLNL/spack/issues/736#issuecomment-206185306 , so my understanding is that until we have a proper support to mixing 'c/c++' with 'f77/f90' from different families (`clang` and `gcc`), then we will have these problems.

A workaround for now is to do something along the lines
```
cd $SPACK_ROOT/lib/spack/env/clang
ln -s ../cc gfortran
```
**BUT** this does not yet work as I still have
```
make -j8 CC=/Users/davydden/spack/lib/spack/env/clang/clang FC=/Users/davydden/spack/lib/spack/env/f77 libs netlib shared
```

@tgamblin @alalazo  What does one have to do in addition to make it
```
make -j8 CC=/Users/davydden/spack/lib/spack/env/clang/clang FC=/Users/davydden/spack/lib/spack/env/clang/gfortran libs netlib shared
```
?

Then i would suggest to add this to documentation to guide users how to mix `clang` and `gcc` until it is properly supported.

**Comment by davydden** [comment]
Below are instructions how to (hopefully) properly hack together `clang` and `gfortran`:

(i) edit `compilers.yaml`
```
compilers:
  darwin-x86_64:
    clang@7.3.0-apple:
      cc: /usr/bin/clang
      cxx: /usr/bin/clang++
      f77: /path/to/bin/gfortran
      fc: /path/to/bin/gfortran
```

(ii) create a symlink inside `clang` environement
```
cd $SPACK_ROOT/lib/spack/env/clang
ln -s ../cc gfortran
```

(iii) Patch `clang` compiler file
```
diff --git a/lib/spack/spack/compilers/clang.py b/lib/spack/spack/compilers/clang.py
index e406d86..cf8fd01 100644
--- a/lib/spack/spack/compilers/clang.py
+++ b/lib/spack/spack/compilers/clang.py
@@ -35,17 +35,17 @@ class Clang(Compiler):
     cxx_names = ['clang++']
 
     # Subclasses use possible names of Fortran 77 compiler
-    f77_names = []
+    f77_names = ['gfortran']
 
     # Subclasses use possible names of Fortran 90 compiler
-    fc_names = []
+    fc_names = ['gfortran']
 
     # Named wrapper links within spack.build_env_path
     link_paths = { 'cc'  : 'clang/clang',
                    'cxx' : 'clang/clang++',
                    # Use default wrappers for fortran, in case provided in compilers.yaml
-                   'f77' : 'f77',
-                   'fc'  : 'f90' }
+                   'f77' : 'clang/gfortran',
+                   'fc'  : 'clang/gfortran' }
 
     @classmethod
     def default_version(self, comp):
```

By doing so, one can write in `openblas`
```
make_defs = ['CC=%s' % spack_cc,
                     'FC=%s' % spack_f77]
```
which now becomes
```
CC=/Users/davydden/spack/lib/spack/env/clang/clang FC=/Users/davydden/spack/lib/spack/env/clang/gfortran
```
and there is no warning that `fortran` compiler could not be found.

**Comment by citibeth** [comment]
Thank you, I've added this to the following page, which will (hopefully)
turn into documentation in the manual:

https://github.com/LLNL/spack/issues/638

**Comment by davydden** [comment]
closing this as it's not an issue, but a feature -- the way OpenBlas works, see https://github.com/LLNL/spack/issues/846#issuecomment-215633754
