### ISSUE TITLE
develop: fetching a tarball coming from a mirrored svn version fails

### ISSUE THREAD

**Issue by fpruvost** [LLNL/spack#85]
Hi,

I tried to install an svn version of a package from a tarball acquired with a spack mirror create.
The problem is that on the machine where I add the mirror I'm not able to install the package because the fetch step fails:

    $ spack -d fetch chameleon@trunk
    ==> Trying to fetch from file:///home/pruvost/work/spack_mirrors/spack-mirror-2015-06-24/chameleon/chameleon-trunk.tar.gz
    ==> /usr/bin/curl -O -f -D - -L file:///home/pruvost/work/spack_mirrors/spack-mirror-2015-06-24/chameleon/chameleon-trunk.tar.gz -#
    ######################################################################## 100,0%
    ==> Fetching from file:///home/pruvost/work/spack_mirrors/spack-mirror-2015-06-24/chameleon/chameleon-trunk.tar.gz failed.

It is strange because if I try the command:

    $  /usr/bin/curl -O -f -D - -L file:///home/pruvost/work/spack_mirrors/spack-mirror-2015-06-24/chameleon/chameleon-trunk.tar.gz

the tarball is properly downloaded in the current directory.

I do not have the problem with a released version.
I reproduce the same problem with another package using a SVN version.

Any idea?

Thanks,
Florent

**Comment by tgamblin** [comment]
This is related to #228

**Comment by tgamblin** [comment]
I tracked this down and should be able to get a fix out early this week -- the mirror logic is kind of old and kludged into the stage and fetch policies.  I will try to clean it up a bit.
