### ISSUE TITLE
`spack cd` changes directory when no target exists

### ISSUE THREAD

**Issue by trws** [LLNL/spack#852]
When the requested stage doesn't exist, `spack cd` changes directory to the user's home.  At least personally I would expect it to stay in the same directory in this case.

```
scogland at cab668 in /tmp/scogland/spack-stage/spack-stage-D1e76p
$ cd ~/spack

scogland at cab668 in ~/spack (e53571d...)
$ spack cd gcc
==> Error: Build directory does not exist yet. Run this to create it:
  spack stage gcc

scogland at cab668 in ~ (gem:32)
$ pwd
/g/g12/scogland
```

**Comment by tgamblin** [comment]
I agree... want to fix?

**Comment by trws** [comment]
It's on my list, just wanted to get the issue in lest I forget.
