### ISSUE TITLE
Automate the creation of the bash completion file

### ISSUE THREAD

**Issue by alalazo** [LLNL/spack#8780]
As a user I want the bash completion file always synchronized with the current set of commands and options, so that I won't receive wrong suggestions when pressing <kbd>Tab</kbd>.

### Description

Right now Spack has a completion file for bash that is manually maintained. As such it's very likely to go out of sync with the current set of commands and options. A simple improvement to this state of things could be:

1. Have a way to generate that file automatically (the procedure might be a script, or a Spack command triggered manually by a contributor).
2. Run a test during CI that checks if the content of the completion file needs an update (and fails in that case).

More sophisticated options could be relying on something like [argcomplete](http://argcomplete.readthedocs.io/en/latest/), though this might trigger some incompatibilities between our custom version of `argparse` and the standard one the package expects.

@adamjstewart @tgamblin @scheibelp @healther

**Comment by adamjstewart** [comment]
#2356 adds a zsh completion script that was autogenerated. I think the program they used is zsh specific though. If we're going to autogenerate for bash, it would be great if we could get other shells in too.
