### ISSUE TITLE
up-to-date documentation online

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#892]
it would be good to have up-to-date documentation compiled into `html` pages online, similar to http://software.llnl.gov/spack/index.html which is `0.8`.

If/when new features are documented, it is much easier to browse `html` page as opposed to using text editor to display ``packaging_guide.rst` and alike.

**Comment by tgamblin** [comment]
Is there a way to do this from `.travis.yml`?

**Comment by davydden** [comment]
frankly i have no experience with tranvis ci at all. I suppose you mean updating the documentation automatically using travis in each PR?

**Comment by tgamblin** [comment]
yep.  No need to work on it if you're not familiar -- I'll get to it and I'm pretty sure it's a fairly easy fix.  If not through travis we can do it with another web hook of some sort.

**Comment by tgamblin** [comment]
Ok so, update.  I don't think we can deploy to software.llnl.gov very easily because I'm not sure I'm ready to allow travis to push straight to the github repo.   However, we recently got back [spack.readthedocs.io](http://spack.readthedocs.io/en/latest/), which will automatically update the documentation.  What if we pointed the documentation link in `README.md` there?

readthedocs is nice b/c it autogenerates the docs and lets you version docs (something I don't think is possible with just the RTD theme).  It does have ads, but they're not super intrusive.

@adamjstewart @davydden

**Comment by davydden** [comment]
> What if we pointed the documentation link in README.md there?

sound good to me. That way users will be redirected to the up-to-date documentation from the main GitHub page of spack.

**Comment by adamjstewart** [comment]
Agreed. I don't see any ads, but maybe that's because I have AdBlock Plus enabled. This sounds like a much easier solution that pushing from Travis.

**Comment by adamjstewart** [comment]
@tgamblin I'll update the README.md to point to [spack.readthedocs.io](http://spack.readthedocs.io/en/latest/index.html) in #1576. Can we redirect the current http://software.llnl.gov/spack/index.html to this new address?

**Comment by adamjstewart** [comment]
Hmm, the [readthedocs](http://spack.readthedocs.io/en/latest/index.html) webpage seems to be missing the [Command Index](http://software.llnl.gov/spack/command_index.html), [Package List](http://software.llnl.gov/spack/package_list.html), and [API Docs](http://software.llnl.gov/spack/spack.html) sections of the old documentation. What's up with that?

**Comment by tgamblin** [comment]
@adamjstewart: 

> Hmm, the readthedocs webpage seems to be missing the Command Index, Package List, and API Docs sections of the old documentation. What's up with that?

Fixed by dae00fe

**Comment by tgamblin** [comment]
@adamjstewart ok I lied -- I can't figure out why it won't generate the package list.  The command index is generated fine, and the package list works for me locally with a sphinx build.  But the package list is empty on readthedocs.

**Comment by tgamblin** [comment]
@adamjstewart ok I lied -- I can't figure out why it won't generate the package list.  The command index is generated fine, and the package list works for me locally with a sphinx build.  But the package list is empty on readthedocs.

**Comment by adamjstewart** [comment]
Is `conf.py` the right place for these?

**Comment by tgamblin** [comment]
If we want them to be generated by `readthedocs`, which doesn't actually use the `Makefile`, it is...

**Comment by adamjstewart** [comment]
@tgamblin Looks like this issue can be closed now that we are using readthedocs. Can you redirect http://software.llnl.gov/spack/index.html to http://spack.readthedocs.io/en/latest/?

**Comment by tgamblin** [comment]
Done.
