### ISSUE TITLE
Problem downloading gmp ( needed when building gcc)

### ISSUE THREAD

**Issue by luigi-calori** [LLNL/spack#895]
I' ve tried to install a gcc 4.9.3 that depends on gmp.
On my system, mys system curl return error when
curl https://gmplib.org/download/gmp/gmp-6.1.0.tar.bz2
wget downloads and also spack installed curl does.

I modified gmp to dpend on curl and to use it in fetch.
I made that optional with a variant.
Is this stuff worth a PR? or better I put this on one private repo?

**Comment by davydden** [comment]
i would say add `curl` as an optional dependency with `on` by default so that there are fewer surprises when somebody installs `gcc`. This should make `gcc` more robust in a variety of environments. 

_disclaimer_: I am not a maintainer :smile:

**Comment by adamjstewart** [comment]
I'm not sure if adding curl as a dependency changes what version of curl is used to fetch a package...

**Comment by adamjstewart** [comment]
But this would definitely be useful as a PR if it works

**Comment by luigi-calori** [comment]
No it' s not enough, I had to do override do_fetch as:

https://github.com/RemoteConnectionManager/spack/commit/32743c177a6d85c988e78ea70055356ef456e37f

As you can see I have defined a variant default to false to be compliant with previous behaviour.
I' ve verified on my side (bit old develop + some other PR):
spack install gmp           ---> ERROR
spack install gmp+curl   ---> OK

To submit good PR do I have to  checkout current develop in a new branch then merge the single commit, then submit PR or are better ways?

**Comment by davydden** [comment]
@luigi-calori for a PR you can cherry-pick your commit. Most likely it will apply without any issues at current `develop`
```
git checkout develop
git pull
git checkout -b fix_gmg
git cherry-pick 32743c177a6d85c988e78ea70055356ef456e37f
git push <your_git_remote>
```

**Comment by adamjstewart** [comment]
I believe we've discussed this elsewhere, but the problem is that the system curl installation is too old. Curl isn't a dependency of gmp, it is a dependency of Spack. Most packages download with curl, and we obviously don't want to add curl as a dependency of every package. The solution is to install a newer version of curl with Spack (or any other package manager) and add it to your PATH.
