### ISSUE TITLE
check which versions (if any) of petsc/trilinos supports Superlu_dist 5.0

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#901]
@tgamblin 
>mark petsc and trilinos with more specific depends_on() constraints. Seems like they need to say:
```
    depends_on('SuperLU_DIST@:4.3', when='@:<some version>')
    depends_on('SuperLU_DIST@5:', when='@<some version++>:')
```

or from a certain version they may support both `4.3.` and `5.0`.

**Comment by tgamblin** [comment]
oh right -- in which case this should be ok:

```
   depends_on('SuperLU_DIST@:4.3', when='@:<some version>')
   depends_on('SuperLU_DIST', when='@<some version++>:')
```

dep constraints shouldn't have to be disjoint, especially if the `when` constraints are.

**Comment by KineticTheory** [comment]
I did a little digging...

`trilinos@:12.6.1` (the current default in spack) is not compatible with `superlu-dist@5.0.0`.  According to https://github.com/trilinos/Trilinos/issues/245, a fix was put in on 2016 March 30 and should be available in `trilinos@12.6.2:`.  A specific reference to _superlu-dist@5_ is in  `packages/amesos/src/Amesos_Superludist.cpp` for compatible versions of trilinos.  I think spack's `trilinos/package.py` needs this:

```
    depends_on('superlu-dist@:4.3',when='@:12.6.1+superlu-dist')
    depends_on('superlu-dist',when='@12.6.2:+superlu-dist')
```

but I haven't had time to test it.

**Comment by davydden** [comment]
judging from the `superlu_dist` version `petsc` host on bitbucket https://bitbucket.org/petsc/pkg-superlu_dist it seems that they do not support `5.0` yet.

**Comment by davydden** [comment]
and the changelog of `petsc`  `3.7` (the most recent version) do not have anything on `superlu_dist` https://www.mcs.anl.gov/petsc/documentation/changes/37.html .

**Comment by davydden** [comment]
i am also fixing the petsc part in https://github.com/LLNL/spack/pull/1053 as 3.7 actually supports superlu-dist 5.0.

**Comment by davydden** [comment]
that's fixed already.
