### ISSUE TITLE
GMsh installation not fully contained with prefix

### ISSUE THREAD

**Issue by jppelteret** [LLNL/spack#915]
The installation paths for the GMsh binaries, tutorials etc. are not contained within the CMake installation path (see the end of [build.out](https://gist.github.com/jppelteret/24b7ef9c38ee10072c721bcc89872b7a)). The result is that the destination directory contains the `include` folder, while binaries sit in another folder one level down (`../MacOS`) and the tutorials and examples are somewhere else entirely (`opt/spack`).

**Comment by jppelteret** [comment]
Also, as a result of this, the binary directory is not loaded into path when `spack load gmsh` is called.

**Comment by davydden** [comment]
i think i know how to fix it, will try now...

**Comment by jppelteret** [comment]
@davydden Done already thanks!

**Comment by jppelteret** [comment]
@davydden And thanks a lot for being willing to take a look at this :-)

**Comment by davydden** [comment]
@jppelteret np ;-)
