### ISSUE TITLE
Stage archives without a hash for DAG

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#917]
currently, the packaging documentation says

> The staging directory will be located under $SPACK_HOME/var/spack. When run after the archive has already been downloaded, spack fetch is idempotent and will not download the archive again.

which is actually not entirely correct. For example for `trilinos`, spack stages under
```
 $SPACK_HOME/var/spack/stage/trilinos-12.6.1-ddppcv7qgrv4a4rutk7d2rqyvzlunxpr/trilinos-release-12-6-1.tar.gz
```
so if a user installs trilinos again but with a different DAG (different flags or a new version of openmpi), it appears that the same archive will be downloaded again into a new directory.

I think spack should download archives and keep them if needed without any references to the DAG, i.e. download to something like
```
 $SPACK_HOME/var/spack/stage/trilinos/trilinos-release-12-6-1.tar.gz
```

**Comment by tgamblin** [comment]
#579

**Comment by davydden** [comment]
@tgamblin thanks for the link, i even forgot that i saw that :smile:
