### ISSUE TITLE
Compiling a multiple architecture executable

### ISSUE THREAD

**Issue by adamjstewart** [LLNL/spack#974]
I would like to be able to compile an executable that works across multiple architectures. For example, our cluster contains both sandybridge and haswell nodes. In order to run a program in parallel across both, multiple architecture support must be specified at compile time. Here are some flags that do this:

| Compiler | Flag |
| --- | --- |
| Intel | -axCORE-AVX2,AVX |
| GCC | -march=haswell,sandybridge |
| PGI | -tp=haswell,sandybridge |

What's the best way to do this? I would love to integrate the new better arch support.

**Comment by mathstuf** [comment]
Do you mean fat binaries or is this auto-generating CPU-detection code for functions with differing assembly?

**Comment by adamjstewart** [comment]
Um, I'm not exactly sure. I was just told to make a single executable to do benchmarks across both Sandybridge and Haswell nodes, and that these were the flags to use.

**Comment by mathstuf** [comment]
According to the manpage, that value isn't valid:

-march=name
    Specify the name of the target architecture, optionally suffixed by one or more feature modifiers.  This option has the form -march=arch{+[no]feature}*, where the only permissible value for arch is armv8-a.  The permissible values for feature are documented in the sub-section below.  
    Where conflicting feature modifiers are specified, the right-most feature is used.  
    GCC uses this name to determine what kind of instructions it can emit when generating assembly code.  
    Where -march is specified without either of -mtune or -mcpu also being specified, the code is tuned to perform well across a range of target processors implementing the target architecture.

**Comment by mathstuf** [comment]
Ack, that's the AArch64 section.

**Comment by mathstuf** [comment]
Yeah, it doesn't seem to support comma-separated values for `-march`: `foo.cpp:1:0: error: bad value (haswell,sandybridge) for -march= switch`.

**Comment by adamjstewart** [comment]
Well, PGI and Intel accept comma separated values at least.

**Comment by mathstuf** [comment]
[GCC 6](https://lwn.net/Articles/691932/) might support this, but not through compiler flags.

**Comment by adamjstewart** [comment]
This can be closed now that Spack supports specifying compiler flags in `compilers.yaml`.

**Comment by adamjstewart** [comment]
By the way, if anyone wants to know what I'm talking about, this article can explain it much better than I can.
https://www.chpc.utah.edu/documentation/software/single-executable.php
