### ISSUE TITLE
Cannot uninstall packages if they don't have a URL

### ISSUE THREAD

**Issue by jgalarowicz** [LLNL/spack#98]
JEG: I built cbtf from the git repository using this source access line:
        version('master', branch='master', git='http://git.code.sf.net/p/cbtf/cbtf')

TODD: This looks fine, although if you check out 'master' you run the risk of getting a different version every time.

JEG:    and now I can't uninstall it.

JEG:        spack uninstall -a cbtf
JEG:        ==> Error: Class constructor failed for package 'cbtf'.
JEG        Package Cbtf has no version with a URL.

TODD: Can you file a bug for this?  In the meantime, try:
TODD:    spack uninstall cbtf@master
TODD:    do a spack find -p cbtf to see where it is installed, then just remove it manually.

JEG: I believe I had to remove the install directory.
JEG: Sorry, to be filing this weeks after being asked to.

**Comment by adamjstewart** [comment]
This bug is still present in develop over a year later:
```
$ spack uninstall -y r-biocgenerics
==> Error: Class constructor failed for package 'builtin.r-biocgenerics'.

Caused by:
NoURLError: Package RBiocgenerics has no version with a URL.
  File "/Users/Adam/spack/lib/spack/spack/repository.py", line 580, in get
    self._instances[key] = package_class(copy)
  File "/Users/Adam/spack/lib/spack/spack/package.py", line 557, in __init__
    f = fs.for_package_version(self, self.version)
  File "/Users/Adam/spack/lib/spack/spack/fetch_strategy.py", line 878, in for_package_version
    url = pkg.url_for_version(version)
  File "/Users/Adam/spack/lib/spack/spack/package.py", line 677, in url_for_version
    raise NoURLError(cls)
```

**Comment by alalazo** [comment]
@jgalarowicz I just tried:
```console
$ spack install cbtf
...
$ spack uninstall -a cbtf
==> The following packages will be uninstalled : 

-- linux-ubuntu14-x86_64 / gcc@4.8 ------------------------------
q7fatss cbtf@1.6%gcc~runtime


==> Do you want to proceed ? [y/n]
y
==> Successfully uninstalled cbtf@1.6%gcc@4.8~runtime arch=linux-ubuntu14-x86_64-q7fatss
```
and had no problem with it. Do you think this issue can be closed?

**Comment by adamjstewart** [comment]
@alalazo Definitely still an issue. Try installing and uninstalling `r-biocgenerics`. The problem affects any package that does not have a url.

**Comment by becker33** [comment]
@adamjstewart I've just successfully installed and uninstalled `r-biocgenerics` without modifying the package.py file. Can you confirm that the bug persists?

**Comment by adamjstewart** [comment]
Testing it out now. It might take a while to build...

**Comment by becker33** [comment]
`cbtf` is another example that builds a bit faster, I was able to uninstall it as well.

**Comment by adamjstewart** [comment]
Ok, I successfully installed and uninstalled `r-biocgenerics`. I wonder when this was fixed! It was broken for me a couple of weeks ago.
