### ISSUE TITLE
spack spec dealii takes now 18 minutes instead of 10 seconds on master branch

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#980]
i just checked out `develop` (d94972503a4377b017e5a0e33b8a6b0b68cb862b) and it seems something got broken badly as `spack spec dealii@dev` ~~never reaches the concretized specs~~ takes insane amount of time (18 minutes instead of 10 seconds):
```
$ spack spec dealii@dev
Input spec
------------------------------
  dealii@dev

Normalized
------------------------------
  dealii@dev
      ^astyle@2.04
      ^blas
      ^bzip2
      ^cmake
      ^lapack
      ^muparser
      ^numdiff
          ^gettext
      ^suite-sparse
      ^tbb
      ^zlib

Concretized
------------------------------
```

The last working commit I am aware of is 1774c7a7b38fa60eaf30aa9d5cef5a6a18b8c55d  (May 17). So it must be in the last couple of days.

**Comment by davydden** [comment]
my best bet is that it is related to https://github.com/LLNL/spack/pull/963. I don't know whether something is wrong in one of the packages or the logic in the mentioned PR.

**Comment by davydden** [comment]
It breaks right at 502420ceff7214d11b6956d42f44f22cc8c6ca6e , which is

**Comment by davydden** [comment]
@tgamblin As a preventive measure, maybe one could add a couple of unit tests which do `spack speck <package>` for some big packages like `ares` (mentioned in your paper but AFAIK not in the repo), `dealii` and maybe a few others which have a big dependency tree?

**Comment by davydden** [comment]
@tgamblin @becker33: update to this issue. Prior to `cfags` PR (current `master`), `spack spec dealii` took **10 seconds**, after the PR (current `develop`) it takes **18 minutes**. That is **~100 times slower**. I don't have any experience deubugging python, some logic somewhere must be wrong. Could you give this issue a look?

**Comment by davydden** [comment]
Here is profiling output `spack -p spec dealii`: 
[profile.txt](https://github.com/LLNL/spack/files/275703/profile.txt)

**Comment by tgamblin** [comment]
Looks like a call to `dag_hash()` was accidentally included in the fast hash (`__hash__`) in `spec.py`.  That causes lots of calls to `yaml.dump()` during concretization, which is bad news.  Fixed.

**Comment by davydden** [comment]
thanks :+1:
