### ISSUE TITLE
spack install hdf5 followed by spack install hdf5~fortran downloads hdf5 tarball twice

### ISSUE THREAD

**Issue by markcmiller86** [LLNL/spack#988]
I was working on OS X. 
I ran spack install hdf5.
That failed due to Fortran being on by default and no fortran compiler on my OS X machine
I ran spack install hdf5~fortran
That downloaded HDF5 a second time. Why?

**Comment by tgamblin** [comment]
See #579.  Spack downloads a tarball per configuration right now -- that was intended to help out when we have parallel builds, and each node gets a package to build from the DAG.  It's not that helpful and we'd probably want to implement it differently anyway.  Once #579 is in this will go away.
