### ISSUE TITLE
metis/parmetis website is down

### ISSUE THREAD

**Issue by davydden** [LLNL/spack#990]
[par]metis website is down at the moment: http://glaros.dtc.umn.edu/gkhome/metis/metis/overview

 FIY, here are the mirrors:

http://pkgs.fedoraproject.org/repo/pkgs/metis/metis-5.1.0.tar.gz/md5/5465e67079419a69e0116de24fce58fe/metis-5.1.0.tar.gz

https://launchpad.net/ubuntu/+archive/primary/+files/parmetis_4.0.3.orig.tar.gz

**Comment by xjrc** [comment]
@davydden: Thanks for providing these mirrors!  The Par[METIS] website doesn't have the best track record for uptime, so these will prove quite useful to those of us that use these libraries.  Also, I just checked and it looks like the website is finally back up.

**Comment by davydden** [comment]
@xjrc you are welcome!

p.s. as website is up again, i am closing this issue, but it will be easy to find in case the website is down again.

**Comment by kwierman** [comment]
Hey guys, the website is down again, and has been for some time. We might want to reconsider re-opening this, or altering the url of the package to point someplace more... stable.

**Comment by davydden** [comment]
given the significant number of open issues, i am closing this, minor issue in order not to destruct developer's attention.

**Comment by cponder** [comment]
Is there a support page we can contact about this? Given that the regular METIS website is down, I can't look there....
